### ISSUE TITLE
Provide ability to chose base branch on Pull Request Panel

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#10007]
### Description
User do not have ability to chose base branch  on Pull Request Panel at the moment.
![pr_panel](https://user-images.githubusercontent.com/5676062/41282527-f66a79c2-6e3c-11e8-9d01-0697d4199cd0.png)
I think we can implement it like list box for contribution banches:
![pr_p](https://user-images.githubusercontent.com/5676062/41282733-7cf2c9e0-6e3d-11e8-812f-be63abfaa65c.png)

### Reproduction Steps
1. Be sure Pull Request Panel is closed
2. Import a project
3. Checkout on new branch.
4. Do some changes and commit them.
5. Open PR panel and try to create pull rerquest

You can see your current branch in the field for base branch and you do not have ability to change this field. So you can not create PR from current branch to master for example.
![pr_panel](https://user-images.githubusercontent.com/5676062/41283717-fec89d8a-6e3f-11e8-88a6-8482078d662a.gif)

**Comment by vparfonov** [comment]
not actual
