### ISSUE TITLE
Adding a new Language Server as a side car

### ISSUE THREAD

**Issue by shahar-h** [eclipse-che/che#10002]
I'm trying to add a new Language Server as a side car using the following guide:
https://www.eclipse.org/che/docs/language-servers.html#ls-sidecars

The last part there explains how to add a server to the workspace config.
You mention there that I can register my own language id or use any ID from the default list:
https://github.com/eclipse/che/blob/master/wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/registry/DefaultLanguages.java

However, this link is broken.

**Comment by tsmaeder** [comment]
That code has been refactored, but the documentation is not yet updated.

**Comment by eivantsov** [comment]
Docs are here https://www.eclipse.org/che/docs/language-servers.html#ls-sidecars
