### ISSUE TITLE
There are two parent folders with a same name when import recursively maven project

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#10012]
### Description

**Reproduction Steps:**
* Open the IDE and import recursively a project (e.g. https://github.com/artaleks9/multimodule-submodule-project.git)
* Perform the project configuration 
* Expand the project

**Expected behavior:** 
* should not be present parent folders with a same name

**Observed behavior:**
* there are two parent folders with a same name in the project explorer

**Che version**: 6.7.0
**OS and version:** Fedora 28
**Che install:** Docker/OCP
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Related selenium tests: _ImportWizardFormTest_ 
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**screenshot:**
![two-same-name-folders](https://user-images.githubusercontent.com/5408906/41289600-011eb30e-6e53-11e8-8f4e-d6b0509267e7.png)

**video:**
![import-recursive-two-same-folders](https://user-images.githubusercontent.com/5408906/41290341-43cb005c-6e55-11e8-94a1-17be9383784e.gif)

**Comment by artaleks9** [comment]
13.08.2018 
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/357/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.gitImportWizardFormTest

**Comment by artaleks9** [comment]
_19.09.2018_
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/403/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.gitImportWizardFormTest

**Comment by artaleks9** [comment]
_21.09.2018_
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/367/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.gitImportWizardFormTest

**Comment by vparfonov** [comment]
ok, @artaleks9 thanks for adding information looks like. Do you have manual steps how to reproduce it?

**Comment by vkuznyetsov** [comment]
not actual
