### ISSUE TITLE
Check the working of all workspaces with samples according to optimize the list of stacks

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#10027]
### Description
* We need to check by hand all list of stacks:
  - in UD click tab and create a workspace
  - build, run and test commands
  - build, run the samples
  - working Language Servers associated with the stacks
* Related issue: #9960 
* Related document: https://docs.google.com/spreadsheets/d/1y74uc41OwVE20A8VYOVxH0eg5rOPwVYuITN7fmGNiNg/edit#gid=0

**Comment by artaleks9** [comment]
Checked on the docker-single platform. Need to check on the openshift platform.

**Comment by SkorikSergey** [comment]
Done.
