### ISSUE TITLE
Regular user can't start workspace on Eclipse Che with openshift-v3 identity provider

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10038]
### Description
After we have registered _OpenShift identity provider_ as described [here](https://www.eclipse.org/che/docs/openshift-admin-guide.html#create-workspace-objects-in-personal-namespaces), regular user is still able to register as usual from login page omitting OpenShift Web Console. But then he/she can't start workspace because of error:
> Client [che-public] not authorized to retrive tokens from identity provider [openshift-v3]
![screenshot from 2018-06-14 10-40-15](https://user-images.githubusercontent.com/1197777/41398673-bcd2f5b0-6fc0-11e8-9177-7cf192d8b9a1.png)

Che server REST API error message:
```
You should link your account with the <strong>openshift-v3</strong> 
identity provider by visiting the <a href='http://keycloak-eclipse-che.172.19.20.137.nip.io/auth/realms/che/account/identity?referrer=che-public&referrer_uri=http%3A%2F%2Fche-eclipse-che.172.19.20.137.nip.io%2Fdashboard%2F?redirect_fragment%3D%2Fworkspaces' target='_blank' rel='noopener noreferrer'><strong>Federated Identities</strong></a> page of your Che account
```

![out](https://user-images.githubusercontent.com/1197777/41408777-7e26f5f2-6fdc-11e8-88f3-6b5b0bbdaf9f.gif)

This issue is related to #8178.

## Update
Initially the issue was about error `Client [che-public] not authorized to retrive tokens from identity provider [openshift-v3]` which caused by absence of create-token role. After adding the role error message which user saw in IDE was changed to the meaningful one `You should link your account with the openshift-v3 identity provider by visiting the Federated Identities page of your Che account`:
![screenshot from 2018-06-14 18-13-43](https://user-images.githubusercontent.com/1197777/41460287-e09dd8f0-7094-11e8-90ee-78a5fd03e308.png)

But it's still unknown:
1. Should regular user which registered directly in the _Eclipse Che_ be unable to start workspace until account is linked with *openshiht-v3*?
1. Should we forbid user registration in _Eclipse Che_ in case we have added *openshift-v3* provider?
1. Should we forbid registration of other identity providers together with *openshift-v3*, (for example, github provider) if we can't start workspace until user links account with *openshift-v3*?:
![screenshot from 2018-06-14 18-54-48](https://user-images.githubusercontent.com/1197777/41458858-76fc2cca-7090-11e8-8d5f-4aea687e6d1a.png)

**Comment by davidfestal** [comment]
1. Are you sure you created the `openshift-v3` identity provider in Keycloak with the same options as defined in the documentation, especially the following options:

![image](https://user-images.githubusercontent.com/686586/41414466-6a7c32a6-6fe6-11e8-9ce9-2a74314a0648.png)

Seems strange that the alternate Openshift login method is proposed in the Che login page.

 2. Are you sure you added a default read-token role as stated in the same documentation ?

**Comment by dmytro-ndp** [comment]
Actually, identity provider was created with the next options:
![screenshot from 2018-06-14 13-51-47](https://user-images.githubusercontent.com/1197777/41414926-fc08dfae-6fef-11e8-9813-d9a2ff30173c.png)

Documentation doesn't mention enabling of options `Account Linking Only` and `Hide on Login Page` https://www.keycloak.org/docs/3.3/server_admin/topics/identity-broker/social/openshift.html 

Also, _read-token_ wasn't added. Sorry - my bad :-(

I am going to fix the configuration as you mentioned and check workspace creation again.

**Comment by dmytro-ndp** [comment]
@davidfestal: enabling `Account Linking Only` and `Hide on Login Page` options of OpenShift v3 identity provider hides section `Login with OAuth: openshift-v3` at _Login Page_.

Also, adding _read-token_ role is fixes error message in case of starting workspace:
![screenshot from 2018-06-14 18-13-43](https://user-images.githubusercontent.com/1197777/41421182-d7ae5a08-6ffe-11e8-914a-bd10fd8ec8b8.png)

Then, after setting up _Identity Provider_ workspace is starting as expected.

But I don't quite sure if it is still correct behavior to demand regular user to setting up Federation Identity.

**Comment by dmytro-ndp** [comment]
@davidfestal, @eivantsov:  another moment is - should Eclipse Che on OCP support several identity providers at a time, for example: **OpenShift** and **GitHub**?
![screenshot from 2018-06-14 18-54-48](https://user-images.githubusercontent.com/1197777/41423623-75ccd836-7004-11e8-96a3-daaf5e891ab1.png)

Now user which is logged in with _GitHub_ account is still requested to link account with _OpenShift identity provider_ as well.
