### ISSUE TITLE
Unable to build Che images if default shell doesn't support `<<<` operator

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10041]
### Description
Unable to build Che images if default shell doesn't support `<<<` operator.

### Reproduction Steps
1. Try to build Che Server image where default shell is configured to `dash`.
Expected: Image is built.
Actual: The following error appears:
```
serg@sergpad ~/projects/che/dockerfiles/che $ ./build.sh 
./build.sh: 25: /home/serg/projects/che/dockerfiles/che/../build.include: Syntax error: redirection unexpected
```
**OS and version:**    
```
$ uname -a
Linux sergpad 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia
```

**Diagnostics:**

**Comment by sleshchenko** [comment]
Looks like it was introduced in https://github.com/eclipse/che/pull/9850. @riuvshin Can you take a look?

**Comment by garagatyi** [comment]
@riuvshin I have the same issue, please, fix it

**Comment by vitaliy-guliy** [comment]
Still have the same problem on Linux Mint 18.3

**Comment by monaka** [comment]
Same here and fixed it. My build environment is Ubuntu. Ubuntu uses `ash` as `/bin/sh` even though many Linux distros use `bash`. I'm not sure but probably same as Mint is based on Ubuntu.
I make some patches. I'm going to send PR.
