### ISSUE TITLE
CHE build fail on Java 10 (build doesn't pass running tests)

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#10040]
### Description
CHE build fail on Java 10 (build doesn't pass some tests).

### Reproduction Steps
1. Build che by `mvn clean install`. Java version: 10.0.1. With skip tests build is succesfull.

**OS and version:**    
Fedora 28.
**Diagnostics:** 
<pre> It is recommended that the compiler be upgraded.
100 warnings
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ che-core-commons-lang ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Che Parent 6.7.0-SNAPSHOT .......................... SUCCESS [  1.312 s]
[INFO] Che Core Parent .................................... SUCCESS [  0.046 s]
[INFO] Che Core :: Commons :: Parent ...................... SUCCESS [  0.045 s]
[INFO] Che Core :: Commons :: Annotations ................. SUCCESS [  1.862 s]
[INFO] Che Core :: Commons :: Java API extension classes .. FAILURE [  2.963 s]
[INFO] Che Core :: API :: DTO ............................. SKIPPED
[INFO] Che Core :: Commons :: Json helpers ................ SKIPPED
[INFO] Che Core :: Commons :: Utilities for tests ......... SKIPPED
[INFO] Che Core :: Commons :: Dependency Injecting ........ SKIPPED
[INFO] Che Core :: Commons :: Scheduler service ........... SKIPPED
[INFO] Che Core :: API :: DTO Maven Plugin ................ SKIPPED
[INFO] Che Core :: API :: Core ............................ SKIPPED
[INFO] Che Core :: Commons :: Auth ........................ SKIPPED
[INFO] Che Core :: Commons :: Commons Logback ............. SKIPPED
[INFO] Che Core :: Commons :: XML ......................... SKIPPED
[INFO] Che Core :: Commons :: Commons J2ee ................ SKIPPED
[INFO] Che Core :: Commons :: Mail sender ................. SKIPPED
[INFO] Che Core :: API :: TypeScript DTO maven plugin ..... SKIPPED
[INFO] Che Agent Parent ................................... SKIPPED
[INFO] Che Core :: API :: Debug :: Shared ................. SKIPPED
[INFO] Che Core :: API :: Debug ........................... SKIPPED
[INFO] Che Core :: API :: Git :: Shared ................... SKIPPED
[INFO] Che Core :: API :: Model ........................... SKIPPED
[INFO] Che Master Parent .................................. SKIPPED
[INFO] Che Core :: API :: Workspace :: Shared ............. SKIPPED
[INFO] Che Core :: API :: Project Shared .................. SKIPPED
[INFO] Che Core :: DB ..................................... SKIPPED
[INFO] Che Core :: DB :: Vendor H2 ........................ SKIPPED
[INFO] Che Core :: SQL :: Schema .......................... SKIPPED
[INFO] Che Core :: API :: Account ......................... SKIPPED
[INFO] Che Core :: API :: Installer :: Shared ............. SKIPPED
[INFO] Che Core :: API :: Installer ....................... SKIPPED
[INFO] Che Core :: API :: System Shared ................... SKIPPED
[INFO] Che Core :: API :: System .......................... SKIPPED
[INFO] Che Core :: API :: SSH :: Shared ................... SKIPPED
[INFO] Che Core :: API :: User :: Shared .................. SKIPPED
[INFO] Che Core :: API :: User ............................ SKIPPED
[INFO] Che Core :: API :: SSH ............................. SKIPPED
[INFO] Che Core :: API :: Workspace ....................... SKIPPED
[INFO] Che Core :: API :: Project ......................... SKIPPED
[INFO] Che Core :: API :: Agent ........................... SKIPPED
[INFO] Che Core :: API :: Git ............................. SKIPPED
[INFO] Che Core :: API :: Language Server Shared .......... SKIPPED
[INFO] Che Core :: API :: Language Server Maven Plugin .... SKIPPED
[INFO] Che Core :: API :: Language Server ................. SKIPPED
[INFO] Che Core :: API :: Authentication :: Shared ........ SKIPPED
[INFO] Che Core :: API :: OAuth ........................... SKIPPED
[INFO] Che Core :: SSH Key :: Server ...................... SKIPPED
[INFO] Che Core :: Git Impl JGit .......................... SKIPPED
[INFO] Che Multiuser :: Parent ............................ SKIPPED
[INFO] Che Multiuser :: Machine Auth Parent ............... SKIPPED
[INFO] Che Multiuser :: Machine Authentication Shared ..... SKIPPED
[INFO] Che Multiuser :: Machine Authentication Agent ...... SKIPPED
[INFO] Che Workspace Agent War Packaging .................. SKIPPED
[INFO] Che Core :: API :: DynaModule maven plugin ......... SKIPPED
[INFO] Che Core :: IDE .................................... SKIPPED
[INFO] Che Core :: Commons :: GWT ......................... SKIPPED
[INFO] Che Core :: Commons :: GWT Logger .................. SKIPPED
[INFO] Che Agents Parent .................................. SKIPPED
[INFO] Agent :: Exec :: Parent ............................ SKIPPED
[INFO] Agent :: Exec :: Shared ............................ SKIPPED
[INFO] Che Core :: API :: Factory :: Shared ............... SKIPPED
[INFO] Che Core :: API :: Project Templates :: Shared ..... SKIPPED
[INFO] Che Core :: IDE :: API ............................. SKIPPED
[INFO] Che Core :: IDE :: Generators ...................... SKIPPED
[INFO] Che Core :: IDE :: UI .............................. SKIPPED
[INFO] che-core-dyna-provider-generator-maven-plugin Maven Mojo SKIPPED
[INFO] Che Core :: IDE :: App ............................. SKIPPED
[INFO] Che Plugin :: Orion :: Editor ...................... SKIPPED
[INFO] Che Multiuser :: Keycloak Integration Parent ....... SKIPPED
[INFO] Che Multiuser :: Keycloak Shared module ............ SKIPPED
[INFO] Che Multiuser :: Machine Authentication IDE ........ SKIPPED
[INFO] Che Multiuser :: Keycloak IDE ...................... SKIPPED
[INFO] Che Core  IDE :: Basic IDE ......................... SKIPPED
[INFO] Che Plugin :: Parent ............................... SKIPPED
[INFO] Che Plugin :: Composer :: Parent ................... SKIPPED
[INFO] Che Plugin :: Composer :: Shared ................... SKIPPED
[INFO] Che Plugin :: PHP :: Parent ........................ SKIPPED
[INFO] Che Plugin :: PHP :: Shared ........................ SKIPPED
[INFO] Che Plugin :: Composer :: IDE ...................... SKIPPED
[INFO] Che Plugin :: C/C++ :: Parent ...................... SKIPPED
[INFO] Che Plugin :: C/C++ :: Shared ...................... SKIPPED
[INFO] Che Plugin :: C/C++ :: IDE ......................... SKIPPED
[INFO] Che Plugin :: C# :: Parent ......................... SKIPPED
[INFO] Che Plugin :: C# :: Shared ......................... SKIPPED
[INFO] Che Plugin :: C# :: IDE ............................ SKIPPED
[INFO] Che Plugin :: Debugger :: Parent ................... SKIPPED
[INFO] Che Plugin :: Debugger :: Extension Debugger IDE ... SKIPPED
[INFO] Che Plugin :: Dashboard :: Parent .................. SKIPPED
[INFO] Che Plugin :: Dashboard :: Client .................. SKIPPED
[INFO] Che Plugin :: GDB :: Parent ........................ SKIPPED
[INFO] Che Plugin :: GDB :: GDB IDE ....................... SKIPPED
[INFO] Che Plugin :: Orion :: Parent ...................... SKIPPED
[INFO] Che Plugin :: Orion :: Compare Widget .............. SKIPPED
[INFO] Che Plugin :: Git :: Parent ........................ SKIPPED
[INFO] Che Plugin :: Git :: Extension ..................... SKIPPED
[INFO] Che Plugin :: Github :: Parent ..................... SKIPPED
[INFO] Che Plugin :: Github :: Shared ..................... SKIPPED
[INFO] Che Core :: SSH Key :: Client ...................... SKIPPED
[INFO] Che Plugin :: Github :: IDE ........................ SKIPPED
[INFO] Che Plugin :: Pull request :: Parent ............... SKIPPED
[INFO] Che Plugin :: Pull request :: Shared ............... SKIPPED
[INFO] Che Plugin :: Pull request :: IDE .................. SKIPPED
[INFO] Che Plugin :: Github :: Pull request ............... SKIPPED
[INFO] Che Plugin :: Golang :: Parent ..................... SKIPPED
[INFO] Che Plugin :: Golang :: Extension Shared ........... SKIPPED
[INFO] Che Plugin :: Golang :: IDE ........................ SKIPPED
[INFO] Che Plugin :: GWT :: Parent ........................ SKIPPED
[INFO] Che Plugin :: GWT .................................. SKIPPED
[INFO] Che Plugin :: Help :: Parent ....................... SKIPPED
[INFO] Che Plugin :: Help :: Client ....................... SKIPPED
[INFO] Che Plugin :: Java :: Parent ....................... SKIPPED
[INFO] Che Plugin :: Java :: Extension Java Shared ........ SKIPPED
[INFO] Che Plugin :: Java :: Plain ........................ SKIPPED
[INFO] Che Plugin :: Java :: Plain :: Shared .............. SKIPPED
[INFO] Che Plugin :: Java :: Plain :: IDE ................. SKIPPED
[INFO] Che Plugin :: Java :: Extension Java Client ........ SKIPPED
[INFO] Che Plugin :: Java Debugger :: Parent .............. SKIPPED
[INFO] Che Plugin :: Java :: Java Debugger IDE ............ SKIPPED
[INFO] Che Plugin :: Key Binding Eclipse :: Parent ........ SKIPPED
[INFO] Che Plugin :: Key Binding Eclipse :: IDE ........... SKIPPED
[INFO] Che Plugin :: Language Server :: Parent ............ SKIPPED
[INFO] Che Plugin :: Language Server :: IDE ............... SKIPPED
[INFO] Che Plugin :: Machine :: Parent .................... SKIPPED
[INFO] Che Plugin :: Machine :: SSH Client ................ SKIPPED
[INFO] Che Plugin :: Maven :: Parent ...................... SKIPPED
[INFO] Che Plugin :: Maven :: Extension Maven Shared ...... SKIPPED
[INFO] Che Plugin :: Maven :: Extension Maven Client ...... SKIPPED
[INFO] Che Plugin :: NodeJs Debugger :: Parent ............ SKIPPED
[INFO] Che Plugin :: NodeJs Debugger :: IDE ............... SKIPPED
[INFO] Che Plugin :: NodeJs :: Parent ..................... SKIPPED
[INFO] Che Plugin :: NodeJs :: Extension Shared ........... SKIPPED
[INFO] Che Plugin :: NodeJs :: IDE ........................ SKIPPED
[INFO] Che Plugin :: PHP :: IDE ........................... SKIPPED
[INFO] Che Plugin ::  Product Info :: Client .............. SKIPPED
[INFO] Che Plugin :: Python :: Parent ..................... SKIPPED
[INFO] che-plugin-python-lang-shared ...................... SKIPPED
[INFO] Che Plugin :: Python :: IDE ........................ SKIPPED
[INFO] Che Plugin :: SDK :: Parent ........................ SKIPPED
[INFO] Che Plugin :: SDK :: Plugins Development ........... SKIPPED
[INFO] Che Core :: API :: Testing Shared .................. SKIPPED
[INFO] Che Plugin :: Testing :: Parent .................... SKIPPED
[INFO] Che Plugin :: Testing :: IDE ....................... SKIPPED
[INFO] Che Plugin :: JAVA Testing :: Java Testing Parent .. SKIPPED
[INFO] Che Plugin :: Java Testing :: JUnit Parent ......... SKIPPED
[INFO] Che Plugin :: Java Testing :: JUnit IDE ............ SKIPPED
[INFO] Che Plugin :: PHP Testing :: PHP Testing Parent .... SKIPPED
[INFO] Che Plugin :: PHP Testing :: PHPUnit Parent ........ SKIPPED
[INFO] Che Plugin :: PHP Testing :: PHPUnit IDE ........... SKIPPED
[INFO] Che Plugin :: Java Testing :: TestNG Parent ........ SKIPPED
[INFO] Che Plugin :: Java Testing :: TestNG IDE ........... SKIPPED
[INFO] Che Plugin :: Web :: Parent ........................ SKIPPED
[INFO] che-plugin-web-ext-shared .......................... SKIPPED
[INFO] Che Plugin :: Web :: File Types .................... SKIPPED
[INFO] Che Plugin :: YAML :: Parent ....................... SKIPPED
[INFO] Che Plugin :: Yaml :: Shared ....................... SKIPPED
[INFO] Che Plugin :: Yaml :: Ide .......................... SKIPPED
[INFO] Che Plugin :: PHP :: Zend Debugger Parent .......... SKIPPED
[INFO] Che Plugin :: PHP :: Zend Debugger IDE ............. SKIPPED
[INFO] Che Core  IDE :: Full IDE .......................... SKIPPED
[INFO] Che Core :: IDE :: GWT Maven Plugin ................ SKIPPED
[INFO] Che Core :: DB :: Vendor PostgreSQL ................ SKIPPED
[INFO] Che Core :: API :: Authentication .................. SKIPPED
[INFO] Che Core :: API :: Project Templates ............... SKIPPED
[INFO] Che Multiuser :: API Parent ........................ SKIPPED
[INFO] Che Multiuser :: Permissions :: Shared ............. SKIPPED
[INFO] Che Multiuser :: Sql Schema ........................ SKIPPED
[INFO] Che Multiuser :: Permissions API ................... SKIPPED
[INFO] Che Multiuser :: Permissions Parent ................ SKIPPED
[INFO] Che Multiuser :: Workspace Permissions ............. SKIPPED
[INFO] Che Core :: Workspace Activity ..................... SKIPPED
[INFO] Che Core :: API :: Factory ......................... SKIPPED
[INFO] Che Core :: API :: Impl Local ...................... SKIPPED
[INFO] Integration Tests :: Parent ........................ SKIPPED
[INFO] Integration Tests :: Cascade Removal ............... SKIPPED
[INFO] Che Core :: API :: Logger :: Shared ................ SKIPPED
[INFO] Che Core :: API :: Logger .......................... SKIPPED
[INFO] Workspace Agent .................................... SKIPPED
[INFO] Che Core :: API :: Testing ......................... SKIPPED
[INFO] Che Workspace :: Activity Server ................... SKIPPED
[INFO] Che Multiuser :: API :: Authorization .............. SKIPPED
[INFO] Che Multiuser :: API :: Authorization Impl ......... SKIPPED
[INFO] Che Multiuser :: Resource :: Shared ................ SKIPPED
[INFO] Che Multiuser :: Resource .......................... SKIPPED
[INFO] Che Multiuser :: Organization :: Shared ............ SKIPPED
[INFO] Che Multiuser :: Organization ...................... SKIPPED
[INFO] Che Infrastructures Parent ......................... SKIPPED
[INFO] Infrastructure :: Docker :: Parent ................. SKIPPED
[INFO] Infrastructure :: Docker :: Docker Auth ............ SKIPPED
[INFO] Infrastructure :: Docker :: Environment ............ SKIPPED
[INFO] Infrastructure :: Kubernetes ....................... SKIPPED
[INFO] Che Multiuser :: JGroups API Implementation ........ SKIPPED
[INFO] Che Multiuser :: Workspace Activity ................ SKIPPED
[INFO] Che Multiuser :: User Permissions .................. SKIPPED
[INFO] Che Multiuser :: Workspace Activity Permissions .... SKIPPED
[INFO] Che Multiuser :: Factory Permissions ............... SKIPPED
[INFO] Che Multiuser :: System Permissions ................ SKIPPED
[INFO] Che Multiuser :: Installer Permissions ............. SKIPPED
[INFO] Che Multiuser :: Resource :: Permissions ........... SKIPPED
[INFO] Che Multiuser :: Logger Permissions ................ SKIPPED
[INFO] Che Multiuser :: Machine Authentication ............ SKIPPED
[INFO] Che Multiuser :: Personal account .................. SKIPPED
[INFO] Che Multiuser :: Keycloak Server ................... SKIPPED
[INFO] Che Plugin :: Github :: OAuth2 ..................... SKIPPED
[INFO] Che Multiuser :: Keycloak Token Provider ........... SKIPPED
[INFO] Che Multiuser :: Integration Tests ................. SKIPPED
[INFO] Che Multiuser :: Integration Cascade ............... SKIPPED
[INFO] Che Multiuser :: PostgreSQL Tck .................... SKIPPED
[INFO] Che Core :: IDE :: TEMPLATES ....................... SKIPPED
[INFO] Che Core :: IDE :: STACKS .......................... SKIPPED
[INFO] Agents :: Bootstrapper ............................. SKIPPED
[INFO] Agent :: Golang agents ............................. SKIPPED
[INFO] Language Server Golang Agent ....................... SKIPPED
[INFO] Agent :: Exec :: Client ............................ SKIPPED
[INFO] Agent :: Exec ...................................... SKIPPED
[INFO] Agent :: Terminal .................................. SKIPPED
[INFO] SSH Agent .......................................... SKIPPED
[INFO] Unison Agent ....................................... SKIPPED
[INFO] Language Server Json Agent ......................... SKIPPED
[INFO] Git Credentials Agent .............................. SKIPPED
[INFO] Language Server PHP Agent .......................... SKIPPED
[INFO] Language Server python Agent ....................... SKIPPED
[INFO] Language Server typescript Agent ................... SKIPPED
[INFO] Language Server C# Agent ........................... SKIPPED
[INFO] Test Language Server Agent ......................... SKIPPED
[INFO] Language Server Yaml Agent ......................... SKIPPED
[INFO] Language Server Apache Camel Agent ................. SKIPPED
[INFO] Language Server Clang Agent ........................ SKIPPED
[INFO] Infrastructure :: Docker :: Docker Client .......... SKIPPED
[INFO] Infrastructure :: Docker ........................... SKIPPED
[INFO] Infrastructure :: OpenShift ........................ SKIPPED
[INFO] che-plugin-web-ext-server .......................... SKIPPED
[INFO] che-plugin-machine-ext-server ...................... SKIPPED
[INFO] Che Plugin :: Java :: Extension JDT ................ SKIPPED
[INFO] Che Plugin :: Java :: Eclipse JFace ................ SKIPPED
[INFO] Che Plugin :: Java :: Eclipse JFace Text ........... SKIPPED
[INFO] Che Plugin :: Java :: org.eclipse.core.filesystem .. SKIPPED
[INFO] Che Plugin :: Java :: org.eclipse.core.resources ... SKIPPED
[INFO] Che Plugin :: Java :: org.eclipse.core.filebuffers . SKIPPED
[INFO] Che Plugin :: Java :: Eclipse Search ............... SKIPPED
[INFO] Che Plugin :: Java :: Eclipse IDE UI ............... SKIPPED
[INFO] Che Plugin :: Java :: Eclipse LTK Refactoring ...... SKIPPED
[INFO] Che Plugin :: Java :: Eclipse JDT UI ............... SKIPPED
[INFO] Che Plugin :: Java :: Extension Java Server ........ SKIPPED
[INFO] Che Plugin :: Java :: Plain :: Server .............. SKIPPED
[INFO] Che Plugin :: Java :: Java Debugger Server ......... SKIPPED
[INFO] Che Plugin :: Maven :: Maven Server ................ SKIPPED
[INFO] Che Plugin :: Maven :: Maven Server API ............ SKIPPED
[INFO] Che Plugin :: Maven :: Maven Server Impl ........... SKIPPED
[INFO] Che Plugin :: Maven :: Maven Tools ................. SKIPPED
[INFO] Che Plugin :: Maven :: Archetype Generator ......... SKIPPED
[INFO] Che Plugin :: Maven :: Extension Maven Server ...... SKIPPED
[INFO] Che Plugin :: GDB :: GDB Server .................... SKIPPED
[INFO] Che Plugin :: SDK :: Tools ......................... SKIPPED
[INFO] Che Plugin :: Github :: Credential provider ........ SKIPPED
[INFO] Che Plugin :: Github :: Server ..................... SKIPPED
[INFO] Che Plugin :: URL Factory .......................... SKIPPED
[INFO] Che Plugin :: Github :: Factory Resolver ........... SKIPPED
[INFO] Che Plugin :: Python :: Extension Server ........... SKIPPED
[INFO] Che Plugin :: C/C++ :: Extension Server ............ SKIPPED
[INFO] Che Plugin :: C# :: Extension Server ............... SKIPPED
[INFO] Che Plugin :: NodeJs :: Extension Server ........... SKIPPED
[INFO] Che Plugin :: NodeJs Debugger :: Server ............ SKIPPED
[INFO] Che Plugin :: PHP :: Extension Server .............. SKIPPED
[INFO] Che Plugin :: TEST LS :: Extension Server .......... SKIPPED
[INFO] Che Plugin :: JSON :: Parent ....................... SKIPPED
[INFO] Che Plugin :: JSON :: Extension Server ............. SKIPPED
[INFO] Che Plugin :: Composer :: Server ................... SKIPPED
[INFO] Che Plugin :: PHP :: Zend Debugger Server .......... SKIPPED
[INFO] Che Plugin :: Java Testing :: Classpath ............ SKIPPED
[INFO] Che Plugin :: Java Testing :: JUnit Runtime ........ SKIPPED
[INFO] Che Plugin :: Java Testing :: JUnit Server ......... SKIPPED
[INFO] Che Plugin :: Java Testing :: TestNG Runtime ....... SKIPPED
[INFO] Che Plugin :: Java Testing :: TestNG Server ........ SKIPPED
[INFO] Che Plugin :: PHP Testing :: PHPUnit Server ........ SKIPPED
[INFO] Che Plugin :: Pull request :: Server ............... SKIPPED
[INFO] Che Plugin :: Yaml :: Server ....................... SKIPPED
[INFO] Che Plugin :: Apache Camel :: Parent ............... SKIPPED
[INFO] Che Plugin :: Apache Camel :: Server ............... SKIPPED
[INFO] Che Plugin :: Clangd :: Parent ..................... SKIPPED
[INFO] Che Plugin :: ClangD C/C++ :: Extension Server ..... SKIPPED
[INFO] Che Plugin :: Golang :: Extension Server ........... SKIPPED
[INFO] Che IDE :: GWT App ................................. SKIPPED
[INFO] Che Dashboard :: Web App ........................... SKIPPED
[INFO] Che Workspace Loader :: Web App .................... SKIPPED
[INFO] Che IDE :: Parent .................................. SKIPPED
[INFO] Che Workspace Agent War Packaging .................. SKIPPED
[INFO] Che Assembly Workspace Agent Server ................ SKIPPED
[INFO] Che IDE :: War Packaging ........................... SKIPPED
[INFO] Che IDE :: Compiling WS Master WAR ................. SKIPPED
[INFO] Che Workspace Loader :: War Packaging .............. SKIPPED
[INFO] Che IDE :: Assemblies Tomcat ....................... SKIPPED
[INFO] Che Selenium :: Parent ............................. SKIPPED
[INFO] Che Selenium :: Core ............................... SKIPPED
[INFO] Che Selenium :: Test 6.7.0-SNAPSHOT ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.045 s
[INFO] Finished at: 2018-06-14T11:38:45+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project che-core-commons-lang: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed.: NullPointerException -&gt; [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn &lt;goals&gt; -rf :che-core-commons-lang
</pre>

**Comment by eivantsov** [comment]
@AndrienkoAleksandr i think maven logs that precede reactor summary will help identify failing tests.

**Comment by eivantsov** [comment]
Closed due to inactivity.
