### ISSUE TITLE
Create a general model of JavaElement in che-ls-jdt  

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#10045]
In che-ls-jdt project we have a set of DTOs which are describe java elements (for example PackageFragment, PackageFragmentRoot, JavaProjectElement and others). So the main idea to create some general object to describe all these elements.
@tsmaeder proposed to create something like:
```
Element {
  kind: Kind;
  name: String;
  uri: String;
  children?: Element[];
}

**Comment by fbricon** [comment]
it should also have an `attributes?:Map` field
