### ISSUE TITLE
sdk-embed-htmljs broken

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#10046]
Hi,

I'm developing a native JS component for che. I already read some stuff here and I guess that the info that I need has a broken link for it.
https://www.eclipse.org/che/docs/assemblies/sdk-embed-htmljs/index.html

Are you able to fix it?

Thanks,

**Comment by eivantsov** [comment]
@mstavares the approach to write gwt extensions that inject own js has been deprecated.

At this moment, there's an ongoing effort to integrate Theia into Che workspaces, so plugins will be authored in JS.

**Comment by mstavares** [comment]
@eivantsov thanks for your reply.
I'm developing a kind of visual code generator for JS. I just connect some visual components and then the code is automatically generated.
This implementation is coded in html and JS and I really need to integrate it with che. I was expecting that the broken link could help me to integrate it.

**Comment by eivantsov** [comment]
Perhaps this can help https://github.com/che-samples/che-plugin-embedjs

**Comment by mstavares** [comment]
@eivantsov I will check it. Thanks a lot :)

**Comment by mstavares** [comment]
@skabashnyuk

**Comment by skabashnyuk** [comment]
@mstavares got it.
