### ISSUE TITLE
csharp language server  init failed when open demo.csproj file

### ISSUE THREAD

**Issue by xuzhiop** [eclipse-che/che#10055]
### Description
csharp language server init failed when open web.csproj 

### Reproduction Steps
1, create .net workspace 
2, import project from https://github.com/che-samples/dotnet-web-simple.git
3, open web.csproj, then get init failed error

**OS and version:**    
che 6.6.0
Kubernetes 1.9.2

**Comment by dkuleshov** [comment]
Depends on https://github.com/eclipse/che/issues/10047
