### ISSUE TITLE
space character in path of REST call

### ISSUE THREAD

**Issue by FusionFabricUser** [eclipse-che/che#10064]
### Reproduction Steps
Create a file called  a b
In your devTools, a REST call  to  a%20b is issued and fails

**OS and version:**    
Che 6.4

**Diagnostics:** 
The space character is displayed as %20 in the REST call but badly parsed

**Comment by skabashnyuk** [comment]
Can you give example from chrome console?

**Comment by FusionFabric** [comment]
dev machine shows:
![image](https://user-images.githubusercontent.com/40062501/41525000-cd18e926-72df-11e8-8256-b5ebbeb5f9d7.png)

chrome console:
![image](https://user-images.githubusercontent.com/40062501/41525080-1dfddbd0-72e0-11e8-9882-aabd5642ac1c.png)

**Comment by vparfonov** [comment]
can't reproduce this issue
