### ISSUE TITLE
[Language server] Content of PHP language server hover feature is doubled.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10065]
### Description
Content of  **PHP** language server hover feature is doubled.

### Reproduction Steps

1. Create a workspace based on **PHP** stack.
2. Create **web-php-gae-simple** project from wizard.
3. Open **helloworld.php** file.
4. Hover mouse on **"**htmlspecialchars**"** text in line 9.

**Actual result:** content of  hover feature is doubled.

**OS and version:**  Che 6.8.0-SNAPSHOT; Chrome 66.0; Fedora 28

**Additional information:**
![untitled](https://user-images.githubusercontent.com/7760565/41470073-262c660c-70b8-11e8-8fc0-41983cd54c57.png)

**Comment by tsmaeder** [comment]
This might be a duplicate of https://github.com/eclipse/che/issues/10049. @SkorikSergey could you comment on that hypothesis?

**Comment by SkorikSergey** [comment]
Its problem is almost the same, except that the hover content is doubled after the first launch of the workspace. 
After each restart of the workspace, the content of the hover will be doubled.
![screenshot from 2018-06-20 12-21-39](https://user-images.githubusercontent.com/7760565/41649716-e65390ca-7484-11e8-86fb-c17ccf7ce147.jpg)

**Comment by musienko-maxim** [comment]
Looks similar: https://github.com/eclipse/che/issues/10086

**Comment by SkorikSergey** [comment]
Duplicated https://github.com/eclipse/che/issues/10117.
