### ISSUE TITLE
TypeScript language server doesn't format selected code fragment properly 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10068]
### Reproduction Steps
1. Create workspace from **Node** stack with **nodejs-hello-world** project.
2.  Enable **TypeScript** language server by slider on workspace details page and start the workspace.
3. Create **Greeter.ts** file and add content:
```
class Greeter {
    greeting: string;
    constructor(message: string) {
        this.greeting = message;
    }
        greet()     {
          return "Hello, "  +        this.greeting;
                                               }
}
```
4. Select part of code from **6** to **8** line and  start **Format** feature from context menu.

**Expected result:**
Code changed to:
```
class Greeter {
    greeting: string;
    constructor(message: string) {
        this.greeting = message;
    }
    greet() {
        return "Hello, " + this.greeting;
    }
}
```

**Actual result:**
Nothing changed.

**Addition information:**
![screencast-172 19 20 234-8080-2018 06 15-17-58-01](https://user-images.githubusercontent.com/7760565/41474829-b6252750-70c5-11e8-981a-8c8a9f04da72.gif)

**Comment by dkuleshov** [comment]
Is fixed by https://github.com/eclipse/che/issues/10066
