### ISSUE TITLE
Investigate Java Debug Adapter

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10079]
A team from Microsoft has created an extension to jdt.ls that works as a debug adapter. We need to investigate how to best integrate that into Theia. The options I see are:
1. We consume the MS extension as a build dependency and build che-ls-jdt with the relevant bundles includes.
2. We replicate a mechanism like in the VSCode Java exension that allows other plugins to add bundles to the jdt.ls installation.

<tbd: link relevant repos/issues>

**Comment by svor** [comment]
### 1. To build `che-ls-jdt` with `java-debug` bundle
For now it isn't possible as `java-debug` plugin is not available from the Eclipse Target Platform and just add maven dependency can't help. If it is important to have included bundle in `che-ls-jdt` need to ask guys from **vscode-java-debug** to expose java-debug plugin into P2 repository. 
### 2. Activate java-debug bundle from Theia
We can do something like VSCode does. So what do we need to do:

1.  Java-debug is on sonatype nexus central repositories (https://oss.sonatype.org/content/groups/public/com/microsoft/java/com.microsoft.java.debug.plugin/) and for downloading it needs to create a task in gulpfile.js in debug-java module. 
2. The second step is to add into package.json the path to the downloaded library:
something like: 
```json
"contributes": {
    "javaExtensions": [
      "./server/com.microsoft.java.debug.plugin-0.10.0.jar"
    ]
 } 
```
3. And finally need to add `bundles` option to `initializationOptions` of jdt.ls  and provide location to the java-debug plugin:
```javascript
initializationOptions: {
       bundles: [bundleLoaction]
}
```
where `bundleLocation` is path to the extension + path to the downloaded archive.

After that `java-debug` bundle will be loaded and installed after jdt.ls initialization. 

I propose to choose second way, @tsmaeder  WDYT?

**Comment by tsmaeder** [comment]
One problem we haven't looked at is how to run this in a sidecar. I think we can't go the Theia extensions way.

**Comment by tsmaeder** [comment]
We'll close this once we have issues for execution.

**Comment by svor** [comment]
The p2 artifacts for javadebug has been published to bintray server.

The latest p2 site: https://dl.bintray.com/vscjavaci/javadebug/
The history p2 site: https://dl.bintray.com/vscjavaci/javadebug/releases/0.11.0/

So now we can include java-debug plugin into our extension.
