### ISSUE TITLE
Multi-user setup: dashboard won't load

### ISSUE THREAD

**Issue by nickmansrob** [eclipse-che/che#10071]
Hello everyone

I've installed Eclipse Che in Docker, Proxmox as guest OS. In single user modus works everything fine. But when I enable multi user mode, the Eclipse logo keeps blinking and nothing happens. 
This is the run command I've used: docker run -it -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start

In the attachments: the Keycloak configuration of che-public and the loading screen.

How do I fix this?

Thanks in advance
Rob Nickmans
![image 001](https://user-images.githubusercontent.com/17934406/41510272-dbfc235a-7261-11e8-95b5-4df7a5ffe860.png)
![image 002](https://user-images.githubusercontent.com/17934406/41510273-dc140736-7261-11e8-978a-13cacbbbeb24.png)

**Comment by eivantsov** [comment]
@nickmansrob can you open browser dev console and share a screenshot taken when Che logo is blinking? 

Also, you seem to have modified redirectURIs, since it should have `/*` in the end.

**Comment by nickmansrob** [comment]
@eivantsov I've updated the Keycloak "Valid Redirect URLs" but it still doesn't work. In the attachments, the screenshot of the dev console, and it doesn't look that good...
![image 1](https://user-images.githubusercontent.com/17934406/41674975-aad17eb2-74c1-11e8-8cc3-ac1552194d09.png)

**Comment by eivantsov** [comment]
@nickmansrob hm.. 500 is not good indeed. 

Can you run:
```
docker ps // grab Che container ID
docker logs -f $che_container
```

Do the same for a Keycloak container.It does not look like Che server has started correctly.

**Comment by nickmansrob** [comment]
[che.log](https://github.com/eclipse/che/files/2123000/che.log)
[keycloak.log](https://github.com/eclipse/che/files/2123001/keycloak.log)
[postgresql.log](https://github.com/eclipse/che/files/2123002/postgresql.log)
Those are the 3 logs, the log of Che contains 63421 lines so that isn't good news I think...

**Comment by eivantsov** [comment]
@nickmansrob I can see that postgres failed to start, as a result Kyecloak could not connect to it and as a result Che wasn't able to start too.

I'd remove a local directory that you mounted into `:/data` and give it a try again (save the logs - they will be smaller this time)

**Comment by nickmansrob** [comment]
@eivantsov I've searched for the data directory in the logs: /var/lib/pgsql/data/userdata but it doesn't exist.  As far as I know, I haven't assigned a data directory to the postgresql server as it was started automatically.

**Comment by eivantsov** [comment]
@nickmansrob I mean your local dir that you mounted to `:/data`. `-v $local_dir:/data`

**Comment by nickmansrob** [comment]
I've deleted the folder of Che, located at /root/.che-multiuser but it doesn't make sense. The icon still keeps blinking. An error from Keycloak: Internal server occurs. API is not accessible. Do you need the logs again?

**Comment by eivantsov** [comment]
@nickmansrob 

So, Keycloak cannot get to Postgres DB because of 

```
{"log":"Caused by: java.net.UnknownHostException: postgres\n","stream":"stdout","time":"2018-06-21T12:18:47.351373645Z"}
```

I don't know why but postgres cannot be resolved to IP on a postgres container (docker compose does that resolution).

And it looks like CHE_HOST isn't set for some reason. You can see the URL isn't a valid one.
```
{"log":"1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://:5050/auth/realms/che/.well-known/openid-configuration\n","stream":"stdout","time":"2018-06-21T12:04:03.452299103Z"}
```

**Comment by nickmansrob** [comment]
Okayy, that's a lot of Chinese to me... Any idea how I set the Host for Che? And also, how can I solve the postgres problem? Little remark: I just want to have a login panel before I can access Che. So if there's another solution for that, hints are welcome!

**Comment by eivantsov** [comment]
I think smth is wrong with networking in a VM that you use. I cannot tell what exactly though.

Have you tried to run a simple 2 container app using Docker compose in that VM?

**Comment by nickmansrob** [comment]
Docker compose isn't installed because Che uses something special, described [here.](https://www.eclipse.org/che/docs/docker-multi-user.html). From that page, I've installed all the things I needed to.

**Comment by nickmansrob** [comment]
@eivantsov I'm sorry, I've suspended my project, since I now use Codeanywhere. Maybe I'll resume the project in the future. Thanks for your very good support though!
