### ISSUE TITLE
Create CQ for jwtproxy

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#10078]
### Description
Since we will probably need to build/use own fork of jwtproxy,  the appropriate CQ need to be created.

**Comment by skabashnyuk** [comment]
done

- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16851	github.com/Sirupsen/logrus 0.11.5
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16852	github.com/coreos/go-oidc a93f71f
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16853	github.com/coreos/goproxy 25fe259
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16854	github.com/coreos/pkg v4
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16855	github.com/gregjones/httpcache 9cad4c3
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16856	github.com/jonboulle/clockwork v0.1.0
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16857	github.com/patrickmn/go-cache 2.1.0
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16858	github.com/tylerb/graceful 1.2.15
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16859	gopkg.in/square/go-jose.v2 2.1.6
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16860   github.com/coreos/jwtproxy  3538699
