### ISSUE TITLE
oAuth sign in problem!

### ISSUE THREAD

**Issue by Dave199011** [eclipse-che/che#10070]
Google sign-in oAuth button doesn't work and the server gives out an error! (screenshot submitted)

Also I'm not able to sign in with username and password!

Login page error with username and password: "Authentication failed. Please check username and password."

Ps: I have changed my password successfully but still can't login with new password!

Sorry if I don't know the right format for submitting issues!
![codenvy2](https://user-images.githubusercontent.com/16555813/41499854-07265dd6-719d-11e8-985a-9a24cda8e8a8.JPG)

**Comment by skabashnyuk** [comment]
What version of Codenvy are you using?

**Comment by eivantsov** [comment]
Closing as not relevant to Che. Openan issue with Codenvy repo https://github.com/codenvy/issues

**Comment by Dave199011** [comment]
@eivantsov Thank you. Would you please consider to take a look at the issue in Codenvy repo.
