### ISSUE TITLE
Cover ws-agent/exec-agent/terminal with JWT proxy on K8s/OpenShift infrastuctures

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10081]
### Description
Cover ws-agent/exec-agent/terminal with JWT proxy on K8s/OpenShift infrastuctures.

It includes the following operations:
- add `jwtproxy` container for one workspace;
- configure `jwtproxy` in the added container, the corresponding public key and config file should be injected into the container. The injection can be implemented with using secrets.
- rewrite public accessible servers to `jwtproxy` ones instead of original;

For implementing the same in Docker infrastructure there is an issue https://github.com/eclipse/che/issues/10242.
**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
Instead of hardcoding the described servers I'm going to introduce an abstract way for covering workspace servers with authentication. It may be done with attributes in servers configs, as example workspace agent installer
```json
{
  "id": "org.eclipse.che.ws-agent",
  "version": "1.0.3",
  "name": "Workspace API",
  "description": "Workspace API support",
  "dependencies": [],
  "properties": {},
  "servers": {
    "wsagent/http": {
      "port": "4401/tcp",
      "protocol": "http",
      "path" : "/api",
      "attributes": {
        "secure": "true"
      }
    },
    "wsagent/ws": {
      "port": "4401/tcp",
      "protocol": "ws",
      "path" : "/wsagent",
      "attributes": {
        "secure": "true"
      }
    },
    "wsagent-debug": {
      "port": "4403/tcp",
      "protocol": "tcp"
    }
  }
}
```
I'm open to suggestions attribute name or another way for abstracted covering servers with authentication.
@gazarenkov @garagatyi  @skabashnyuk WDYT?

**Comment by gazarenkov** [comment]
According to "add jwtproxy container for one workspace;" - should not such a thing be on workspace level configuration instead?

**Comment by sleshchenko** [comment]
@gazarenkov Do you mean that all servers should be covered with authentication or not according to the configuration on a workspace level? I think it may be redundant to cover user's applications servers, so we need somehow to add an ability for user/installer developer (later feature developer) to mark servers which should be covered with authentication and which shouldn't.
Please elaborate more what do you mean if you mean something else.

**Comment by gazarenkov** [comment]
Got it, thanks.
Pls, be maximum clear documenting the policies (like how infrastructure behaves for each particular configuration), especially "default" case.

**Comment by sleshchenko** [comment]
Merged the initial implementation of secure servers for Kubernetes and OpenShift infrastructures and created a new issue for improving it https://github.com/eclipse/che/issues/10404
