### ISSUE TITLE
Information regarding workspace logs

### ISSUE THREAD

**Issue by Mohdzaved2434** [eclipse-che/che#10082]
### Please let us know the concrete procedure for storing workspace logs including the followings.
1: Container name to be logged in  (eclipse/che-server etc.) 
2: Output destination directory of logs
3: Log file name
4: How to output debug logs, how to switch output modes, output destination

**Comment by skabashnyuk** [comment]
@Mohdzaved2434  can you give some context about what are you doing and what are you trying to achieve. From issues description, it was not very clear.

**Comment by Mohdzaved2434** [comment]
We are printing some logs on Eclipse che console using a tool.
We want to know that is there any log file in which these logs are being stored?

please find the attached image for the same




![image](https://user-images.githubusercontent.com/29610208/41577556-295ee08e-73ab-11e8-9feb-f50fe9f4264a.png)

**Comment by eivantsov** [comment]
@Mohdzaved2434 workspace logs are in `/workspace_logs` in workspace containers. Container names are generated.

**Comment by Mohdzaved2434** [comment]
@eivantsov Thank you
