### ISSUE TITLE
Python language server doesn't format selected code fragment properly 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10086]
### Reproduction Steps
1. Create a workspace based on Default Python Stack stack.
2. Enable **Python** language server installer if it need.
3. Create  `web-python2.7-simple` project from wizard.
4. Open `main.py` file.
5.  Change content from file something like that:.
```python
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return       "Hello World!"

if __name__ ==      "__main__":
    app.run                 (host='0.0.0.0', port=8080,  debug=True)
```
6. Select next fragment of code from line 8:
```python 
if __name__ ==      "__main__":
```
7. Apply **Edit** -> **Format**.

**Expected result:**  The content should be 
```python
 if __name__ == "__main__":
``` 

**Actual result:** The formatting is not applied

**OS and version:**   Fedora 28, Chrome browser v.  66.0.33, CHE- 6.7.0

**Comment by musienko-maxim** [comment]
The same problem: https://github.com/eclipse/che/issues/10065
