### ISSUE TITLE
Make a unique nonce as optional check in jwtproxy

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10090]
### Description
There is a plan to secure tooling servers with authentication that are done by coreos/jwtproxy. But there is a thing that prevents us to use it: a requirement to use a unique nonce for each request.
While the main client of tooling servers is IDE in a browser, where is no a way to generate a token, because it is not secure to provide a client with a private key. So, we are not able to provide new token from server side for each client's request. It is why do we need to disable this check.

It is planned to create a fork and make these changes there, build custom image and use it.
For the same time, create a PR to coreos/jwtproxy and when it will be merged just configure it and use default `jwtproxy` image

**OS and version:**    

**Diagnostics:**

**Comment by mshaposhnik** [comment]
It's done here: https://github.com/eclipse-che-staging/jwtproxy/commit/e3aff4ebccaf3fe41539d0a68a574fae857ad150
