### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by umurgdk** [eclipse-che/che#101]
How can I uninstall che on OSX environment completely. It messed up my docker configurations.

**Comment by benoitf** [comment]
Hello,

I don't see how it has changed your docker configuration as it is a client of docker.

Removing the app will uninstall Che.

**Comment by sotsugov** [comment]
It also seems to redirect localhost to /che/default even though the app is removed.

```
Error

Invalid client request received: First line of request did not contain an absolute URL - try enabling invisible proxy support.
GET /che/default HTTP/1.1
Host: 127.0.0.1:8080
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
DNT: 1
Referer: http://127.0.0.1:8080/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-GB,en;q=0.8,et;q=0.6

```

**Comment by skabashnyuk** [comment]
Have you remove ROOT war?

**Comment by sotsugov** [comment]
I removed the che folder, not sure about anything else.

**Comment by benoitf** [comment]
did you have kill the process ? else server is still listening

**Comment by sotsugov** [comment]
The process is killed, yes.

**Comment by caioquirino** [comment]
docker ps?

**Comment by stevesloka** [comment]
I had the same issue after deleting the folder. I also removed the startup from /Library/LaunchDaemons. After that, Chrome would still redirect localhost:8080 to /che/xxx. But it was only in Chrome, Firefox was fine. I ended up clearing my browser cache / history, etc and that resolved for me.

**Comment by sotsugov** [comment]
@stevesloka's fix worked for me. Thanks.
