### ISSUE TITLE
Consider using the final version of Keycloak image

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10100]
### Description
Now we using jboss/keycloak-openshift:3.3.0.CR2-3 version of keycloak https://github.com/eclipse/che/blob/master/dockerfiles/cli/version/nightly/images#L6
Consider using one of this versions
- 3.3.0.Final
- 3.4.3.Final
- 4.0.0.Final

**Comment by mkuznyetsov** [comment]
Using now 3.4.3.Final version
