### ISSUE TITLE
Create CI job to test Recreate Workspace Update Strategy

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10106]
### Description
We have a test **RecreateUpdateStrategyTest** which should be executed against _Eclipse Che Multiuser_ deployed on _OpenShift_ with _Recreate Update Strategy_.

To deploy _Eclipse Che on OCP_ with _Recreate Update Strategy_ we should pre-set system environment `export UPDATE_STRATEGY=Recreate`.

Command to execute the test:
`selenium-tests.sh --test=RecreateUpdateStrategyTest  ....`

This issue is related to #9646

**Comment by riuvshin** [comment]
done: https://ci.codenvycorp.com/view/qa/job/che-multiuser-master-ocp-recreate-strategy-test/
