### ISSUE TITLE
Different Quickfix Behaviour Java vs. LSP

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#10112]
### Description
The difference is that in CHE-master we don't need to set the cursor into the position with a problem it is enough to set it into the line with a problem.
  
**Master**
![qfmaster](https://user-images.githubusercontent.com/1271546/41645759-3571b460-7472-11e8-8f5a-3f231b9530d1.gif)

**LSP**
![qf_lsp](https://user-images.githubusercontent.com/1271546/41645791-48c128b6-7472-11e8-82f2-5669ffd1325c.gif)

**Comment by tsmaeder** [comment]
The thing here is that the specialized Java editor in master seems to behave differently from LSP editors. I think we should have consisten behaviour for all editors.
