### ISSUE TITLE
[Language server] Content of language server hover feature is duplicated

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10117]
### Description
Content of hover feature is duplicated **after workspace restarting** in next LS:
- **PHP** language server.
- **Python** language server
- **Camel** language server
- **Yaml** language server.
- **Golang** language server.

For **PHP** and **Python** language servers hover content is duplicated on the first start of workspace( **PHP** - https://github.com/eclipse/che/issues/10065 and  **Python** - https://github.com/eclipse/che/issues/10063.).

### Reproduction Steps
1. Start a workspace with enabled language server from list above.
2. Open a file and check that a LS initialized.
3. Check hover content.
4. Restart the workspace.
5. Check hover content again.

**Addition information:**
![41470300-e288e438-70b8-11e8-9790-dfc81b053f1c](https://user-images.githubusercontent.com/7760565/41664033-78601600-74ad-11e8-96fb-267a8af7e213.png)

**Comment by tsmaeder** [comment]
In the constructor of org.eclipse.che.plugin.languageserver.ide.LanguageServerExtension, a listener is hooked up which calls defaultHoverProviderInitializer.initialize() on each workpace startup. That in turn registers our hover provider each time.

**Comment by eivantsov** [comment]
Labeled as P1 since it affects language support for all languages.

**Comment by amisevsk** [comment]
C# as well. In the `ps -ax` output for the workspace I see 
```
bash /home/user/che/ls-csharp/run -lsp
/home/user/che/ls-csharp/bin/mono.linux-x86_64 /home/user/che/ls-csharp/omnisharp/OmniSharp.exe -lsp
```
