### ISSUE TITLE
Wrong behavior when create a factory with an existing name on the dashboard

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#10121]
### Description
* Open the dashboard and create a factory
* Try to create a factory with a same name

**Expected behavior:** 
* the 'Create' button should be disabled in this case
 

**Observed behavior:**
* there is the error message below the name field: 'This factory name is already used.' 
* but the 'Create' button' is enabled and the factory will be created with a random generate name
 

**Che version**: 6.8.0
**OS and version:** Fedora 28
**Che install:** Docker/OCP
**Docker version:** 17.09
**API docker version:** 1.32
**Failed selenium test:** CreateFactoryTest

**Additional information:**
* Related selenium tests: _CreateFactoryTest_ [_checkHandlingOfFactoryNames_()]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![factorry-exist-name](https://user-images.githubusercontent.com/5408906/41669086-9d14cf16-74b9-11e8-8811-fdd0346e2118.png)

**Comment by skabashnyuk** [comment]
@ashumilova wdyt is it a bug or new feature?
