### ISSUE TITLE
Workspace Can't Start in Multi-User Mode(Cant Connect to Websocket)

### ISSUE THREAD

**Issue by Jimmyscene** [eclipse-che/che#10122]
### Workspace Can't Start in Multi-User Mode

Environ: Multi User Che deployed on Minikube 

Problem: Can't connect to terminal server after workspace has started, getting the following error in the console: 

_Firefox can’t establish a connection to the server at 
ws://$INTERNAL_IP/serveracwwqc5n-dev-machine/server-4412/connect?token=$token_

This seems to be caused by the following endpoint returning the internal IP for the address of the exec -agent: 
http://$EXTERNAL_IP/api/workspace/workspaceuef8qold8wprap61 

Returns json including the following:
```
...
    "runtime": {
        "machines": {
            "dev-machine": {
                "attributes": {
                    "memoryLimitBytes": "2147483648"
                },
                "servers": {
                    "wsagent/ws": {
                        "url": "ws://$INTERNAL_IP/serveracwwqc5n-dev-machine/server-4401/wsagent",
                        "attributes": {},
                        "status": "UNKNOWN"
                    },
                    "exec-agent/ws": {
                        "url": "ws://$INTERNAL_IP/serveracwwqc5n-dev-machine/server-4412/connect",
                        "attributes": {},
                        "status": "UNKNOWN"
                    },
....
    }
```

Any help in solving this issue would be greatly appreciated!

**Comment by eivantsov** [comment]
@Jimmyscene can the workspace start otherwise?

Also, can you share your run syntax and a few words on the networking environment, ie where Che runs and where your browser is located.

**Comment by Jimmyscene** [comment]
Hi @eivantsov, thanks for responding!

I'm running on top of Minikube, which is running on a single VM in openstack, whose internal IP I'm calling $INTERNAL_IP, I've assigned a floating IP, $EXTERNAL_IP to the VM so it can be accessed from my laptop, which is where my browser is located.

This is the order of the commands I've been running:
```
1) git clone https://github.com/eclipse/che.git
2) minikube start --vm-driver=none --cpus 2 --memory 4096 --extra-config=apiserver.authorization-mode=RBAC
3) kubectl apply -f che/deploy/kubernetes/helm/che/tiller-rbac.yaml
4) kubectl create serviceaccount tiller --namespace kube-system
5) minikube addons enable ingress
6) helm init --service-account tiller
7) helm upgrade --set global.ingressDomain=$EXTERNAL_IP --set global.isHostBased=false --install che-test --namespace che-test -f che/deploy/kubernetes/helm/che/values/multi-user.yaml che/deploy/kubernetes/helm/che/
8) helm upgrade --install che-test --namespace che-test -f che/deploy/kubernetes/helm/che/values/default-host.yaml --set global.ingressDomain=$EXTERNAL_IP --set global.isHostBased=false che/deploy/kubernetes/helm/che/
```

**Comment by eivantsov** [comment]
@Jimmyscene what if you try it this way:

```
kubectl create namespace eclipse-che
helm upgrade --install eclipse-che--namespace eclipse-che -f ./values/multi-user.yaml --set global.ingressDomain=${EXTERNAL_IP}.nip.io ./
```
Will it work this way?

It's weird though that servers return internal IPs which you haven't provided in your run syntax or yamls

**Comment by Jimmyscene** [comment]
@eivantov ignore the last comment, that was a user error =), but using nip.io results in the same error as without

**Comment by eivantsov** [comment]
What the failed websocket endpoint this time?

**Comment by Jimmyscene** [comment]
The internal/minikube IP again

**Comment by eivantsov** [comment]
@Jimmyscene 

Drop `--set global.isHostBased=false` and restart either with 

`--set global.serverStrategy=single-host` or `--set global.serverStrategy=multi-host`  

Make sure you keep `--set global.ingressDomain=${EXTERNAL_IP}.nip.io`

**Comment by Jimmyscene** [comment]
@eivantsov Sorry about that, multi host did actually work _and_ fixed the problem, I'll go ahead and close the issue! Thanks so much
