### ISSUE TITLE
Unexpected mismatch the name of GitHub user to name in the 'Federate Identity' of the 'Keycloak'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#10138]
### Description

**Reproduction Steps:**
* Run the che-ocp multi-user and go to the admin console
* Add the GitHub provider (Note: the user name of GitHub account have to begin from the capital letter) 
* After that go to the dashboard Che
* Go to _Account_ - > click on _Edit_ -> select _Federated Identity_  

**Expected behavior:** 
* the names have to be equals

**Observed behavior:**
* the names are different by the first letter

**Che version:** 6.8.0
**OS and version:** Fedora 28
**Che install:** OCP
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Related selenium test: _ImportWizardFormTest_
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* See the attachment:

![capital-letter-github-user](https://user-images.githubusercontent.com/5408906/41731281-a68a13c6-7586-11e8-97f3-10e1261f3115.png)

![small-letter-github-user](https://user-images.githubusercontent.com/5408906/41731292-af8726a8-7586-11e8-8d95-8f359f697bca.png)

**Comment by skabashnyuk** [comment]
expected behavior
