### ISSUE TITLE
Project's name in jdt.ls is artifact-id of this project

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#10133]
### Description
Che has an ability to create many maven projects with same `artifact-id` but it doesn't work for jdt.ls.
For jdt.ls the name of the maven project is its `artifact-id` so in that case we can't have two or more projects with same `artifact-id`.

Selenium test reproduces this problem: `org.eclipse.che.selenium.refactor.packages.RenamePackageSpringTest`

**Comment by svor** [comment]
I'd say that it's an issue for jdt.ls? @tsmaeder What do you think?

**Comment by tsmaeder** [comment]
@svor why are there two projects with the same artifact id used in this test?

**Comment by svor** [comment]
@tsmaeder this test has two different use cases and each of them runs for different projects. 
Whatever che user can ease create many projects from samples which will have same `artfact-id` and all of them except one won't be supported by jdt.ls. 
So, I think the way to change logic of test is wrong.
