### ISSUE TITLE
Theia workspace state is not reported correctly on Dashboard.

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#10140]
I have created a workspace with the Theia IDE stack on che.openshift.io. When the workspace is idled eventually by openshift but Dashboard never realizes this new state and show the workspace as running.

**Comment by gorkem** [comment]
@ashumilova @l0rd assigned to both teams as I am not sure where the issue lies.

**Comment by garagatyi** [comment]
Works as expected now.
