### ISSUE TITLE
Deployment to minikube using helm fails with error: "Error: gzip: invalid header"

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#10175]
### Description

Deployment eclipse che on minikube using helm produces helm error "Error: gzip: invalid header". 

### Reproduction Steps

Deploying with helm:

helm install  --namespace che1 --set isHostBased=false  -f ./values/multi-user.yaml .\Chart.yaml
Error: gzip: invalid header

in the following environment:
OS Windows 10
minikube version: v0.28.0
helm client/server version v2.9.1

**Diagnostics:** 

helm inspect gives the same error for Chart.yaml from deploy\kubernetes\helm\che.
This is known issue which is not specifically related to Che. The root cause is a bug in Repository software which sends to the client corrupted gz stream /headers which can't be opened by helm, It looks like the same as https://github.com/kubernetes/helm/issues/2916.

Could you pay your attention?

**Comment by eivantsov** [comment]
@PavelSosin never seem that on Fedora/Ubuntu. Can this be related to Win?

**Comment by PavelSosin** [comment]
OK
Since yesteday I made some progress and found that it is related to recent helm behaviour. I almost succeeded to upgrade my Che on Windows 10:

helm install  --namespace che1 --set isHostBased=false  -f ./values/multi-user.yaml .

from che\deploy\kubernetes\helm\che. But Chart.yaml itself points to the old Che release and my Che version makes no progress. Imaging my table is not so close to the Gui room, who must care about Chart versioning? The person which installs Che for productive use should be able to take all stuff from corresponding helm repository and not from github. Something is missed in delivery chain :(.
