### ISSUE TITLE
[Language server] Find definition feature does not show results for the C# LS

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#10178]
### Description
**Steps to reproduce:**
* Create a workspace based on .Net stack.
* Open the workspace and create dotnet-web-simple project from wizard
* Restore dependencies by command `name your project: update dependencies` by command pallete or command explorer widgets. Also we can use command in the terminal: `cd path-to-the-project && dotnet restore`. 
We need this because: https://github.com/eclipse/che/issues/10047
* Open `Program.cs` file. Remove `;` `.Build()`, wait appearance of the error marker for make sure that LS is working. Set cursor to the `Build` item and invoke the **Go to the Definition** feature

**Expected result:** Should be opened the `IWebHostBuilder` file in the `Build` position
**Actual result:**  **Go to the Definition** feature is available but nothing happens

**Additional info:**
But Go to the Definition feature works properly with the classes from in the current project

**Env.:** Env.: CHE on single/docker v.: 6.8.0-snapshot,rev.,: a1128b9, Chrome browser.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
