### ISSUE TITLE
KeysInjector not working when CHE_HOST environment variable set

### ISSUE THREAD

**Issue by ThomasDeLetter** [eclipse-che/che#10182]
### Description
When running Che on docker with the CHE_HOST environment variable set, I noticed that the KeysInjector has the following error:

> 2018-06-25 15:40:50,249[onPool-worker-1]  [WARN ] [o.e.c.i.e.m.s.ssh.KeysInjector 146]  - Unable to inject workspace workspaceszldv6cyl8ykxb7n public keys. Error: java.net.ConnectException: Connection refused (Connection refused)

The call to `machine.getServers().get(SERVER_EXEC_AGENT_HTTP_REFERENCE)` in KeysInjector.java returns a localhost url. When I replace localhost with the ip provided in CHE_HOST, everything works fine.

I found this issue while writing a custom plugin that adds a private ssh key to the workspace.

Is this a bug, or am i doing something wrong?

**Comment by eivantsov** [comment]
@ThomasDeLetter  I tried to reproduce but the key was injected in authorized_keys for me.

Can you share your run syntax?

**Comment by ThomasDeLetter** [comment]
My docker syntax run syntax is the following. 

> docker run -it --rm -e CHE_HOST=192.168.0.157 -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v ~/removeMe/:/data -v ~/che/assembly/assembly-main/target/eclipse-che-1.0.0/eclipse-che-1.0.0/:/assembly eclipse/che:6.7.0 start --debug

For information: I am running the latest version of Docker Community Edition for Mac

**Comment by ThomasDeLetter** [comment]
I'm getting the same error when running Che without my custom assembly:

> docker run -it --rm -e CHE_HOST=192.168.0.157 -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v ~/che/:/data start --debug

**Comment by eivantsov** [comment]
Probably a Mac thing - urls are returned as localhost as they should be on a Mac. However, when the call is being made from within the container itself, localhost:port is unavailable.

**Comment by ThomasDeLetter** [comment]
So is this a bug, or

**Comment by ThomasDeLetter** [comment]
Will this be solved? Or is this a docker bug? Is there a way to work around this problem?

**Comment by eivantsov** [comment]
I wouldn't say it's a Docker bug. More like a Che bug

**Comment by skabashnyuk** [comment]
it's a che-docker-osx bug.

**Comment by skabashnyuk** [comment]
won't fix. Not relevant for che7

**Comment by senthurai** [comment]
Using local ip address in mac solves the issue, and able to import the projects
