### ISSUE TITLE
Create CI job to test creation of OpenShift objects under the current user account on OCP

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10183]
### Description
We have package of E2E selenium tests **org.eclipse.che.selenium.site.ocpoauth** which should be executed against _Eclipse Che Multiuser_ deployed on _OpenShift_ with set up OpenShift OAuth server identity provider.

To deploy _Eclipse Che on OCP_ properly with OCP OAuth configuration on CI job we need to use **deploy/openshift/ocp.sh** script with parameter **--setup-ocp-oauth**:
`bash ${WORKSPACE}/deploy/openshift/ocp.sh --run-ocp --deploy-che --multiuser --setup-ocp-oauth `

Command to execute the tests:
`selenium-tests.sh --test=org.eclipse.che.selenium.site.ocpoauth.**  ....`

This issue is related to #9818.

**Comment by riuvshin** [comment]
done, https://ci.codenvycorp.com/view/qa/job/che-multiuser-master-ocpoauth-test
