### ISSUE TITLE
OpenJDK missing plugin.jar

### ISSUE THREAD

**Issue by brostbeef** [eclipse-che/che#10184]
Have existing swing applet that cannot compile in Eclipse Che due to the missing plugin.jar file.  Is there already a stack available containing this library?

**Comment by brostbeef** [comment]
To be more specific... I need the netscape.javascript.JSObject package usually part of the JRE

**Comment by eivantsov** [comment]
@brostbeef you can build own stack with Oracle Java for example.

**Comment by brostbeef** [comment]
If I understand the documentation correctly... I need to build a custom version of Che to add a new Installer for installing the Oracle JDK?  Can you point me in the right direction?

**Comment by brostbeef** [comment]
It appears I found my answer here: https://www.eclipse.org/che/docs/custom-installers.html
Have to call REST API.  Hopefully a GUI gets added at some point within Che to do this.  (Swagger doesn't count IMO).
