### ISSUE TITLE
Maximum Transmission Unit (MTU)  Settings for Eclipse che    

### ISSUE THREAD

**Issue by mznec** [eclipse-che/che#10188]
Currently, The network that we are using has limitation on the packet size.
We would like to change the size of Maximum Transmission Unit (MTU) to 1400 when communicating outside from the Workspace screen of Eclipse Che.
Is there a way to change it through settings of Eclipse Che?

The usage environment is as follows:
OS : RedHat Enterprise Linux 7.4
Infra : Docker 1.13.1
Eclipse Che: 6.0.0
*Kubernetes, OpenShift are not used.

We will be thankful if you could provide the supporting method, even if the source file of Eclipse Che is to be modified.

We are using Eclipse Che 6.0.0 and if it can be solved by version upgrade, then can you to please let us know the target version?

**Comment by skabashnyuk** [comment]
@mznec can you give more context. What is "Maximum Transmission Unit " in your meaning?

**Comment by eivantsov** [comment]
Closed due to inactivity.
