### ISSUE TITLE
mounting local ide to che

### ISSUE THREAD

**Issue by rahul545** [eclipse-che/che#10189]
Hi.....i want to use my local ide with che....However, the documentation says that I will find an ssh key in the console. But its not there. How can I use my local ide?

**Comment by eivantsov** [comment]
@rahul545 have you turned on ssh agent?

Also, what exact documentation page are you referring to?

**Comment by rahul545** [comment]
https://codenvy.com/docs/user-guide/using-desktop-ides/index.html
I m referring to this. However when I follow the steps, I am asked for a password. I dont know the password

**Comment by eivantsov** [comment]
@rahul545 are you trying this with Che?

Also, can you confirm you can see your key in ~/.ssh/authorized_keys in a workspace?

**Comment by eivantsov** [comment]
Closed due to inactivity
