### ISSUE TITLE
There should be better feedback of errors on opening che pages

### ISSUE THREAD

**Issue by iamslite** [eclipse-che/che#10185]
### Description

When initialising the web UI -- such as as the entrypoint URL, or pasting in/bookmarking a workspace URL -- there are a number of errors which can occur which prevent the system starting up in the browser. For example failing to connect to the websocket. As it stands these messages are only logged in the console. Even when, for example, the websocket has failed to connect 100 times the message that che is giving up is only displayed in the console. You are just left with the che logo and no indication that there is some form of issue/potential issue. Whilst as a developer I'm quite familiar with the console I shouldn't need to have it open to tell if the application is going to start!

### Reproduction Steps

Any way that you can trigger a failure on startup. One way is to try and start che 6 in multiuser and single entry point mode under docker, but it applies whenever there is some form of problem initialising the web UI.

**OS and version:**    

N/A

**Diagnostics:** 

N/A

**Comment by skabashnyuk** [comment]
Can you give more precise steps to reproduce this issue? Some screenshots with errors?

**Comment by iamslite** [comment]
The point is not about reproducing this specific issue because it is a general class of problem -- there is no useful feedback during the Web UI intialisation process. I can give you a command which will reliably cause CHE to fail but this is not about fixing that failure, it is about making sure that the users know what is happening:

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/che:/data -e CHE_MULTIUSER=true -e CHE_SINGLE_PORT=true eclipse/che:start`

This will try to start up and run but the front-end code will fail to talk to all sorts of things properly, such as the websocket.

And please do not say that this isn't a supported configuration. That isn't the point. It is just an easy and reliable way to induce errors in the intialisation process.

**Comment by eivantsov** [comment]
@skabashnyuk should Keycloak initialization errors perhaps be propagated to UI (bad URL, filtered port etc)?

**Comment by skabashnyuk** [comment]
sorry, guys, you are asking too broad questions. Each of them has a very specific cause and can't be fixed in general. Can you identify use cases and create individual issues.
