### ISSUE TITLE
Make internal API accessible

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-che/che#1018]
The che code is often relatively protected and hard to extend/reuse. For instance EditorInputImpl can not be reused but needs to be copied.

I understand that you don't want to expose too much public API too early, but I think it would be nicer to communicate it more informally. E.g. you could introduce (or reuse) an annotation similar to @Beta from guava to indicate that some concepts are not public and might change. This leaves the decision to ignore it and live with breaking changes to the user. Also you won't be forced to copy/paste your own code (e.g. org.eclipse.che.ide.extension.machine.client.perspective.widgets.recipe.editor.RecipeEditorInput).

In Eclipse there are even more fine grained information, about how some API might be used how not (see https://wiki.eclipse.org/API_Javadoc_tags).

**Comment by vparfonov** [comment]
When we develop EditorInputImpl we don't see why we will need to extend it. It was used only one time on Editor initialization. But any way thanks for your review of our code and your advice

**Comment by svenefftinge** [comment]
ok, thanks. feel free to close this issue as it is rather vague. I just wanted to share, that I often prefer using internal API and get possibly broken at some point rather than copying over large chunks of code and running out of sync.
