### ISSUE TITLE
What is meant by "Single-Port Routing" in the docs?

### ISSUE THREAD

**Issue by iamslite** [eclipse-che/che#10181]
### Description

The documentation refers to [Single-Port Routing](https://www.eclipse.org/che/docs/docker-config.html#single-port-routing) in the configuration guide and then says that this is not currently supported in Che 6. In the discussion of [Single Port Policy](https://www.eclipse.org/che/docs/docker-config.html#single-port-policy) at the start of that document there is no mention of this limitation, even though Multi-User has only been available in Che (as opposed to Codenvy) since version 6.

Are these referring to the same things, or is there some subtle difference?

**Comment by eivantsov** [comment]
@iamslite but in docs. Will be fixed asap.
