### ISSUE TITLE
InternalServers removed from ws-config

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#10194]
### Description
This commit removed internal servers from ws config - https://github.com/eclipse/che/commit/c3a982ce2f6a898c46a90243dd954489b123809d.

As a result, runtime does not return such server with internal=true in attributes at all, which is a blocker for LS client that looks for a particular server type in all machines, and uses connection endpoint returned by runtime to initialize a remote language server.

**Comment by dkuleshov** [comment]
Seems like [this](https://github.com/eclipse/che/commit/c3a982ce2f6a898c46a90243dd954489b123809d#diff-2241d4e18de99bf3d54557aa3e261441L204) 
```diff 
-.queryParam("includeInternalServers", true)
``` 
line.

**Comment by gazarenkov** [comment]
Yes, I believe we need to add it to WorkspaceProjectSynchronizer (actually not doing it may cause WS synchronization problem)?

**Comment by dkuleshov** [comment]
I've already provided a fix that adds it.

**Comment by DrRSatzteil** [comment]
For me the problem is still there with che 6.8.0

**Comment by eivantsov** [comment]
@DrRSatzteil can you open a new issue with a proper description?
