### ISSUE TITLE
6.7.0 che startup error

### ISSUE THREAD

**Issue by qianlei90** [eclipse-che/che#10190]
### Description

Che(version 6.7.0) failed to start when deployed in k8s with helm.

### Reproduction Steps

Change to tag 6.7.0:

```shell
$ git clone https://github.com/eclipse/che.git che
$ cd che && git checkout -b 6.7.0 6.7.0
```

Deploy to k8s:

```shell
$ cat values.yaml
cheImage: eclipse/che-server:6.7.0
cheImagePullPolicy: IfNotPresent

global:
  multiuser: true
  cheNamespace: ""
  ingressDomain: che.dev.ant-colony.cn

che-postgres:
  image: eclipse/che-postgres:6.7.0

che-keycloak:
  image: eclipse/che-keycloak:6.7.0

$ helm install --name che-dev -f values.yaml deploy/kubernetes/helm/che
```

**OS and version:**    

OS: CentOS7.4
Kubernetes: 1.10.4

**Diagnostics:** 

[pod-che.log](https://github.com/eclipse/che/files/2135873/pod-che.log)

**Comment by eivantsov** [comment]
@qianlei90 do you connect to own postgres instance?

**Comment by skabashnyuk** [comment]
@qianlei90 can you modify GuiceJpaInitializer

```java
public class GuiceJpaInitializer implements JpaInitializer {

  private static final Logger LOG = LoggerFactory.getLogger(GuiceJpaInitializer.class);

  @Inject private PersistService persistService;

  public void init() {
    try {
      LOG.error("Test 1", new Exception());
      persistService.start();
      LOG.error("Test 1", new Exception());
    } catch (Exception x) {
      LOG.error(x.getLocalizedMessage(), x);
    }
  }
}
```
and run against your setup?

**Comment by qianlei90** [comment]
@eivantsov No. But I have a dynamic nfs provisioner in cluster. Each PVC has a default storageclass and PV will be automatically created. I don't know whether it is relevant.
@skabashnyuk Sorry. I know little about java and do not have a develop environment. Can you build a docker image for test? I'll feedback the logs to you.

**Comment by skabashnyuk** [comment]
@qianlei90 is this issue still relevant for you?
