### ISSUE TITLE
Create CI job to test Rolling Workspace Update Strategy

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10200]
### Description
We have tests of package **org.eclipse.che.selenium.hotupdate.rolling** which should be executed against _Eclipse Che Multiuser_ deployed on _OpenShift_ with _Rolling Update Strategy_.

To deploy _Eclipse Che on OCP_ with _Rolling Update Strategy_ we should pre-set system environment  variable: `export UPDATE_STRATEGY=Rolling`

Command to execute the test:
`selenium-tests.sh --test=org.eclipse.che.selenium.hotupdate.rolling.**  ....`

This issue is related to #10176

**Comment by riuvshin** [comment]
https://ci.codenvycorp.com/view/qa/job/che-multiuser-master-ocp-rolling-strategy-test/ done
