### ISSUE TITLE
Word wrap should not obscure indentation

### ISSUE THREAD

**Issue by pvutov** [eclipse-che/che#10207]
### Description
The IDE has a word wrap feature where if a line of text is wider than the viewport, the part that does not fit is shown on the next row.  Eclipse will avoid breaking up words even at the cost of obscuring indentation or otherwise changing the first row. It should be possible to disable this behavior and have "dumb" word wrapping that does not change the first row.

### Reproduction Steps
Open the IDE. Shrink the text window to 90 columns, for example by making a 2x2 layout. Enter the following line, where '\t' is a tab: "\t\tISomeLongInterfaceHTTP::ISomeLongInterfaceMessageHelper::CreateSomeThing(response_header);"

Current behaviour:
![Image of line indented by four cols, indentation obscured](https://i.imgur.com/GAZMOmA.jpg)

You can only find out what the indentation is by highlighting or putting your cursor on the line above.

Desired behaviour:
![Image of line indented by four cols, indentation not obscured](https://i.imgur.com/nulRzJ1.jpg)

**OS and version:**    
Arch Linux, GTK3, Oxygen 3a Release (4.7.3a) CDT

**Comment by AndrienkoAleksandr** [comment]
@pvutov It's a repository of Eclipse CHE - Eclipse cloud IDE . You reported issue about Desktop Eclipse. And we don't use desktop Eclipse Editor.

**Comment by pvutov** [comment]
Thanks for the quick heads-up.
