### ISSUE TITLE
Directory + jars created by a dockerfile are not present in the Web IDE

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#10211]
### Description

In a [dockerfile](https://hub.docker.com/r/51234/che_minecraft_springbootcli/~/dockerfile/) that inherits "eclipse/stack-base:ubuntu", mkdir is used to create a directory within the "projects" directory and use a third party jar to create more jars. The directory created by the dockerfile are not present while in the web ide.

![image](https://user-images.githubusercontent.com/4656027/41966434-b8ce4722-79c4-11e8-85b1-ae10f3277cdb.png)

Yet, the folder appears when accessed with just the docker command line

![image](https://user-images.githubusercontent.com/4656027/41966538-fee274c2-79c4-11e8-86fd-51e64f3f4527.png)

`docker run -it --name minecraftex  51234/che_minecraft_springbootcli /bin/bash`

### Reproduction Steps

- Start Che

- Create a workspace with dockerfile 51234/che_minecraft_springbootcli (exported as a file below)

- notice lack of "minecraft" directory

**OS and version:**    

Ubuntu 18.04 LTS

Che
- Version: 6.7.0
- Revision: /a31054913ca277d6
- Build Time: 2018-06-20 08:34:38

**Diagnostics:** 

### Workspace as file

```
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "main": {
          "attributes": {
            "memoryLimitBytes": "4294967296"
          },
          "servers": {
            "minecraft": {
              "attributes": {},
              "port": "25565",
              "protocol": "tcp"
            }
          },
          "volumes": {},
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh"
          ],
          "env": {
            "CHE_MACHINE_NAME": "main"
          }
        }
      },
      "recipe": {
        "type": "compose",
        "content": "services:\n main:\n  image: 51234/che_minecraft_springbootcli\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [],
  "name": "wksp-tmwd",
  "commands": []
}
```

**Comment by AndrienkoAleksandr** [comment]
"projects" directory in the docker container replaced by docker volume. You can store your files by another path.

**Comment by AndrienkoAleksandr** [comment]
Or you can apply command to the workspace config to download resources, and run this command after start workspace.

**Comment by gnoejuan** [comment]
After updating the dockerfile to create the directory in "/" with `sudo mkdir /minecraft && sudo chown -R user: /minecraft`, the directory and jars are present.

Thank you.
