### ISSUE TITLE
Create selenium test to launch factory created from 'Config' on the dashboard 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#10219]
### Description
* Need to create selenium test to covered launch the factory created from the _Config_ tab on the dashboard
* Test scenario:
   - on the dashboard select the  _Config_ tab
   - upload the configuration file and create the factory
   - click on the named url to launch factory
   - in the IDE expand the project
   -  run the commands
   - repeat the actions for the id url 
* Related to the known issue: #10215

**Comment by vkuznyetsov** [comment]
not actual
