### ISSUE TITLE
Opening an editor that does not correspond to an existing resource throws an exception

### ISSUE THREAD

**Issue by julsarik** [eclipse-che/che#10222]
### Description
Opening an editor that does not correspond to an existing file system resource throws an exception on workspace side.

### Reproduction Steps
Open any editor that does not correspond to an existing resource.
For instance for a maven project : Assistant => Generate Effective Pom
It results in the following exceptions :

![exceptions](https://user-images.githubusercontent.com/33962711/42022826-8ad691da-7abe-11e8-83af-c84b409c8953.png)

**OS and version:**    
Ubuntu 16.04 with Che 6.8.0-SNAPSHOT

**Diagnostics:** 
FileTrackingOperationEvent listeners (e.g. EditorWorkingCopyManager, JavaReconciler) throw exceptions when the event is fired.
However the class SyntheticFile is documented as if it prevents this issue.
But the EditorAgentImpl ignores it.
Here is the flow :
1. EditorAgentImpl.initEditor() fires a FileEvent (with the OPEN state)
2. FileOpenCloseEventListener process the FileEvent transmitting FileTrackingOperationDto to the server 
3. EditorFileOperationHandler deserializes the event and fires it on the server side
4. FileTrackingOperationEvent listeners process the event and throw exception

**Comment by eivantsov** [comment]
@vparfonov can you take a look please?

**Comment by RomanNikitenko** [comment]
Related issues:
- https://github.com/eclipse/che/issues/9655
- https://github.com/eclipse/che/issues/8984
