### ISSUE TITLE
Theia: support for multiple tabs per language server

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10227]
Currently, Theia starts a copy of a language server per instance of the front end (tab or browser window). Because initialization of jdt.ls, for example is very expensive, we should move to a model where the metadata created by jdt.ls (and othter language servers) can be shared between tabs and consecutive runs of the language server.
I particular, this would mean introducing shared buffers for editors, in order to send consistent events about open files to the language servers (didOpen, didChange, etc.)

**Comment by benoitf** [comment]
shouldn't be an issue of theia repository ?

**Comment by l0rd** [comment]
Multi tab is not supported in Theia. This is a Theia limitation. Closing this issue.
