### ISSUE TITLE
Question: how much minikube memory I need to create 5 workspaces based on Ubuntu Jdk stacks?

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#10223]
How much Minikube memory I need to create 4-5 workspaces based on Ubuntu Jdk8 with a couple language serverse

### Reproduction Steps
I'm creating Stacks and Workspaces from Docker images stored in our internal secured Artifact repository using Che 6.7.0 SNAPSHOT. 

Minikube version v1.19.0
Minikube memory 12360

**OS and version:**    
Windows 10 on 16G memory laptop

**Diagnostics:** 
Minikube died when I tried to create 5th workspace and came back only when I increased Minikube memory to 13200. Creating a new Workspace resulted in "Creation failed ... Insufficient memory" error message which, I suppose, has Minikube source.

What is your estimation how much "test" workspaces I can create until minikube crahes?

**Comment by eivantsov** [comment]
@PavelSosin by default ready to go stacks use 2GB RAM.

Do you use single or multi user Che?

**Comment by PavelSosin** [comment]
I use single user Che and stack 2GB but I would like to know the real figures for multiuser configuration as soon as possible. Could you provide some basic resourse consumption grid for different Che flavors taken into account that our customer projects may require up to 1G memory for some LSP servers and builders? I struck the memory consumption barrier too early. Could we disscuss the concept of resourse allocation by Fabric8 for pods  with resourse limits off-line?

**Comment by PavelSosin** [comment]
Some hints:

- A new workspace which uses dev machine with 2.5G memory can't start even the overall memory situation looks OK:
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  825m (41%)    10m (0%)    692Mi (36%)      1390Mi (73%)

Stack test hangs on message "Waiting workspace machines to be booted...". Could I see a log? What is written on Master log?

**Comment by eivantsov** [comment]
@PavelSosin it is your infrastructure that says it does not have resources to schedule a new pod. Server logs just grab events from k8s.

I can see that the default is:

```
Memory: 1717 MB to 2147483648
```
Rough RAM estimates are here https://www.eclipse.org/che/docs/openshift-admin-guide.html#ram

**Comment by PavelSosin** [comment]
It is hard to believe - all minikube memory settings have no effect untill entire cluster is deleted and re-created: [Minikube issue](https://github.com/kubernetes/minikube/issues/567). Good luck to other Che6 on Minikube users!
