### ISSUE TITLE
Freeze when logging into Eclipse Che

### ISSUE THREAD

**Issue by ktdjun** [eclipse-che/che#10226]
### Description
When Eclipse Che operates, an event such as stopping Workspace can not be performed.
The reproduction method is unknown.

When this event occurs, you can not transition from the login screen of Eclipse Che to the DashBoard screen.

Also, the Keycloak Administration Console can not transit from the login screen.

Could you tell me how to know about this event if you know it?

Thank you.

**OS and version:**    
RedHat Enterprise Linux 7.4
Eclipse Che 6.0.0

**Diagnostics:**

**Comment by eivantsov** [comment]
@ktdjun can you perhaps illustrate your uses case with a few screenshots? I cannot understand what exact problem you face.

**Comment by ktdjun** [comment]
@eivantsov 
OK.
Although it differs from the login screen, I will send the image when the same event occurs on the user registration screen.

After pressing the Register button, if it calls KeyCloak's authentication process, as shown in the next screen,
ERR_CONNECTION_RESET occurs and the screen does not shift to the next screen.

![eclipseche_freeze](https://user-images.githubusercontent.com/36942369/42090529-c4153680-7bdc-11e8-9419-da412f8efa97.png)

When Eclipse Che's environment was constructed, there was no particular problem, but suddenly this kind of problem occurred.
Please let me know if you have any other necessary information.

**Comment by eivantsov** [comment]
@ktdjun it does look like some local networking problem.

Can you look for errors in browser dev console? Also, it'd be interesting to look at keycloak container logs:

```
docker ps
docker logs -f $keycloak_id
```

**Comment by ktdjun** [comment]
@eivantsov 
This is Dev tool when logging in from the login screen. There was no response.
![devtool_freeze](https://user-images.githubusercontent.com/36942369/42120418-ad6949b6-7c55-11e8-8591-6cf453e47964.png)

Once again, accessing http://{Che Machine IP}:8080 will result in the following. But there is no response.
The request has been retried several times.
![che_freeze_reaccess](https://user-images.githubusercontent.com/36942369/42120521-2c0b59d4-7c57-11e8-8a14-76c7232f2053.png)

The result of executing the docker command is as follows.
None of the initial accesses were output to the log of keycloak.
When re-accessing http://{Che Machine IP}:8080, a warning log at the end was output.

Please let me know if you have any other necessary information.
I appreciate your cooperation.

     $ docker ps
     CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                  PORTS                                            NAMES
     819786b6ef6d        eclipse/che-server:6.0.0               "/entrypoint.sh"         13 hours ago        Up 13 hours             0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp   che
     6a3fb0d55e78        jboss/keycloak-openshift:3.3.0.CR2-3   "start-keycloak.sh..."   13 hours ago        Up 13 hours             0.0.0.0:5050->8080/tcp                           che_keycloak_1
     e3e1fe1e3325        centos/postgresql-96-centos7:9.6       "container-entrypo..."   13 hours ago        Up 13 hours (healthy)   0.0.0.0:5432->5432/tcp                           che_postgres_1

     $ docker logs -f che_keycloak_1
     [KEYCLOAK DOCKER IMAGE] Using the external postgres database
     12:05:04,945 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.0.Final
     12:05:05,351 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
     12:05:05,811 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) starting
     12:05:05,954 INFO  [org.jboss.vfs] (MSC service thread 1-2) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
     12:05:11,441 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
     12:05:11,805 INFO  [org.wildfly.security] (Controller Boot Thread) ELY00001: WildFly Elytron version 1.1.1.Final
     12:05:11,873 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
     12:05:12,618 INFO  [org.jboss.as.patching] (MSC service thread 1-2) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
     12:05:12,760 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
     12:05:13,117 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
     12:05:13,126 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) started in 8137ms - Started 67 of 81 services (25 services are lazy, passive or on-demand)
     The batch executed successfully
     12:05:13,884 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) stopped in 38ms
     12:05:16,390 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.0.Final
     12:05:16,697 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
     12:05:16,964 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) starting
     12:05:17,122 INFO  [org.jboss.vfs] (MSC service thread 1-2) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
     12:05:23,063 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
     12:05:23,433 INFO  [org.wildfly.security] (Controller Boot Thread) ELY00001: WildFly Elytron version 1.1.1.Final
     12:05:23,478 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
     12:05:24,252 INFO  [org.jboss.as.patching] (MSC service thread 1-1) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
     12:05:24,369 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
     12:05:24,725 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
     12:05:24,727 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) started in 8322ms - Started 67 of 86 services (30 services are lazy, passive or on-demand)
     The batch executed successfully
     12:05:25,540 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) stopped in 41ms
     =========================================================================
       JBoss Bootstrap Environment
       JBOSS_HOME: /opt/jboss/keycloak
       JAVA: /usr/lib/jvm/java/bin/java
       JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
     =========================================================================
     12:05:27,114 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.0.Final
     12:05:28,134 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
     12:05:28,484 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) starting
     12:05:28,650 INFO  [org.jboss.vfs] (MSC service thread 1-2) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
     12:05:34,072 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
     12:05:34,272 INFO  [org.wildfly.security] (ServerService Thread Pool -- 16) ELY00001: WildFly Elytron version 1.1.1.Final
     12:05:34,322 INFO  [org.jboss.as.controller.management-deprecated] (ServerService Thread Pool -- 24) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
     12:05:34,849 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
     12:05:34,956 INFO  [org.xnio] (MSC service thread 1-1) XNIO version 3.5.1.Final
     12:05:34,999 INFO  [org.xnio.nio] (MSC service thread 1-1) XNIO NIO Implementation Version 3.5.1.Final
     12:05:35,108 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 33) WFLYCLINF0001: Activating Infinispan subsystem.
     12:05:35,318 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 41) WFLYNAM0001: Activating Naming Subsystem
     12:05:35,416 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 46) WFLYSEC0002: Activating Security Subsystem
     12:05:35,103 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 34) WFLYRS0016: RESTEasy version 3.0.24.Final
     12:05:35,413 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 47) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments running multiple servers. Please make sure the attribute value is unique.
     12:05:35,483 INFO  [org.jboss.as.jsf] (ServerService Thread Pool -- 39) WFLYJSF0007: Activated the following JSF Implementations: [main]
     12:05:35,700 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 32) WFLYIO001: Worker 'default' has auto-configured to 2 core threads with 16 task threads based on your 1 available processors
     12:05:35,937 INFO  [org.jboss.remoting] (MSC service thread 1-2) JBoss Remoting version 5.0.0.Final
     12:05:35,975 INFO  [org.jboss.as.naming] (MSC service thread 1-1) WFLYNAM0003: Starting Naming Service
     12:05:36,152 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 28) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
     12:05:36,256 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0003: Undertow 1.4.18.Final starting
     12:05:36,312 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 28) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 42.1)
     12:05:36,306 INFO  [org.jboss.as.connector] (MSC service thread 1-2) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.4.6.Final)
     12:05:36,359 INFO  [org.jboss.as.security] (MSC service thread 1-1) WFLYSEC0001: Current PicketBox version=5.0.2.Final
     12:05:36,748 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0018: Started Driver service with driver-name = h2
     12:05:36,789 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0018: Started Driver service with driver-name = postgresql
     12:05:36,790 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-2) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
     12:05:36,875 INFO  [org.jboss.as.ejb3] (MSC service thread 1-2) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 4 (per class), which is derived from the number of CPUs on this host.
     12:05:36,877 INFO  [org.jboss.as.ejb3] (MSC service thread 1-1) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 16 (per class), which is derived from thread worker pool sizing.
     12:05:37,383 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 48) WFLYUT0014: Creating file handler for path '/opt/jboss/keycloak/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
     12:05:37,841 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0012: Started server default-server.
     12:05:38,108 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0018: Host default-host starting
     12:05:38,395 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0006: Undertow HTTP listener default listening on 0.0.0.0:8080
     12:05:38,468 INFO  [org.jboss.as.ejb3] (MSC service thread 1-1) WFLYEJB0493: EJB subsystem suspension complete
     12:05:39,064 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
     12:05:39,105 INFO  [org.jboss.as.patching] (MSC service thread 1-1) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
     12:05:39,108 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-1) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/keycloak/standalone/deployments
     12:05:39,187 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
     12:05:39,194 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0001: Bound data source [java:jboss/datasources/KeycloakDS]
     12:05:39,226 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
     12:05:39,649 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTPS listener https listening on 0.0.0.0:8443
     12:05:41,915 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-1) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.8.Final
     12:05:43,066 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 56) WFLYCLINF0002: Started loginFailures cache from keycloak container
     12:05:43,085 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 55) WFLYCLINF0002: Started authenticationSessions cache from keycloak container
     12:05:43,085 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 59) WFLYCLINF0002: Started authorization cache from keycloak container
     12:05:43,085 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 54) WFLYCLINF0002: Started actionTokens cache from keycloak container
     12:05:43,085 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 58) WFLYCLINF0002: Started keys cache from keycloak container
     12:05:43,085 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 51) WFLYCLINF0002: Started offlineSessions cache from keycloak container
     12:05:43,085 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 52) WFLYCLINF0002: Started users cache from keycloak container
     12:05:43,085 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 53) WFLYCLINF0002: Started work cache from keycloak container
     12:05:43,088 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 57) WFLYCLINF0002: Started sessions cache from keycloak container
     12:05:43,103 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 50) WFLYCLINF0002: Started realms cache from keycloak container
     12:05:43,118 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 60) WFLYCLINF0002: Started client-mappings cache from ejb container
     12:05:47,535 INFO  [org.keycloak.services] (ServerService Thread Pool -- 57) KC-SERVICES0001: Loading config from standalone.xml or domain.xml
     12:05:48,715 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 57) WFLYCLINF0002: Started realmRevisions cache from keycloak container
     12:05:48,744 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 57) WFLYCLINF0002: Started userRevisions cache from keycloak container
     12:05:48,759 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 57) WFLYCLINF0002: Started authorizationRevisions cache from keycloak container
     12:05:48,759 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (ServerService Thread Pool -- 57) Node name: 6a3fb0d55e78, Site name: null
     12:05:55,851 INFO  [org.hibernate.jpa.internal.util.LogHelper] (ServerService Thread Pool -- 57) HHH000204: Processing PersistenceUnitInfo [
             name: keycloak-default
             ...]
     12:05:55,959 INFO  [org.hibernate.Version] (ServerService Thread Pool -- 57) HHH000412: Hibernate Core {5.1.10.Final}
     12:05:55,961 INFO  [org.hibernate.cfg.Environment] (ServerService Thread Pool -- 57) HHH000206: hibernate.properties not found
     12:05:55,965 INFO  [org.hibernate.cfg.Environment] (ServerService Thread Pool -- 57) HHH000021: Bytecode provider name : javassist
     12:05:56,027 INFO  [org.hibernate.annotations.common.Version] (ServerService Thread Pool -- 57) HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
     12:05:56,314 INFO  [org.hibernate.dialect.Dialect] (ServerService Thread Pool -- 57) HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL94Dialect
     12:05:56,658 INFO  [org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl] (ServerService Thread Pool -- 57) HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
     12:05:56,660 INFO  [org.hibernate.type.BasicTypeRegistry] (ServerService Thread Pool -- 57) HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@4a742d7d
     12:05:56,678 INFO  [org.hibernate.envers.boot.internal.EnversServiceImpl] (ServerService Thread Pool -- 57) Envers integration enabled? : true
     12:05:57,673 INFO  [org.hibernate.validator.internal.util.Version] (ServerService Thread Pool -- 57) HV000001: Hibernate Validator 5.3.5.Final
     12:05:59,283 INFO  [org.hibernate.hql.internal.QueryTranslatorFactoryInitiator] (ServerService Thread Pool -- 57) HHH000397: Using ASTQueryTranslatorFactory
     12:06:00,801 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (ServerService Thread Pool -- 57) Importing from directory /opt/jboss/keycloak/realms
     12:06:01,211 INFO  [org.keycloak.services] (ServerService Thread Pool -- 57) KC-SERVICES0030: Full model import requested. Strategy: IGNORE_EXISTING
     12:06:01,504 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 57) Realm 'master' already exists. Import skipped
     12:06:01,661 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 57) Realm 'che' already exists. Import skipped
     12:06:01,686 INFO  [org.keycloak.services] (ServerService Thread Pool -- 57) KC-SERVICES0032: Import finished successfully
     12:06:01,866 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.keycloak.services.resources.KeycloakApplication
     12:06:01,869 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002200: Adding class resource org.keycloak.services.resources.ThemeResource from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,869 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002205: Adding provider class org.keycloak.services.filters.KeycloakTransactionCommitter from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,869 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002200: Adding class resource org.keycloak.services.resources.JsResource from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,869 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.ServerVersionResource from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,870 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RobotsResource from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,870 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002210: Adding provider singleton org.keycloak.services.util.ObjectMapperResolver from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,870 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RealmsResource from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,870 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.WelcomeResource from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:01,870 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 57) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.admin.AdminRoot from Application class org.keycloak.services.resources.KeycloakApplication
     12:06:02,019 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 57) WFLYUT0021: Registered web context: '/auth' for server 'default-server'
     12:06:02,051 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 49) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
     12:06:02,141 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
     12:06:02,147 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
     12:06:02,147 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
     12:06:02,147 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.3.0.CR2 (WildFly Core 3.0.1.Final) started in 36176ms - Started 537 of 859 services (570 services are lazy, passive or on-demand)
     12:20:53,637 WARN  [org.keycloak.events] (default task-3) type=REFRESH_TOKEN_ERROR, realmId=che, clientId=che-public, userId=null, ipAddress={IP different from the connected machine}, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
     12:20:53,749 WARN  [org.keycloak.events] (default task-4) type=REFRESH_TOKEN_ERROR, realmId=che, clientId=che-public, userId=null, ipAddress={IP different from the connected machine}, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
     02:07:42,460 WARN  [org.keycloak.events] (default task-16) type=LOGIN_ERROR, realmId=che, clientId=che-public, userId=null, ipAddress={My machine IP}, error=user_not_found, auth_method=openid-connect, auth_type=code, redirect_uri=http://{Che machine IP}:8080/dashboard/, code_id=a9faaf75-f90e-4b84-8749-275bbb6119c5

**Comment by eivantsov** [comment]
@ktdjun can you access `$IP:5050/auth`? Default credentials are `admin:admin`

Also, can you try logging in to Che with `admin:admin` instead of registering a new user?

Once again, it does look like some sort of a networking issue on your side

**Comment by ktdjun** [comment]
@eivantsov 
I'm sorry for the late reply.
I can access `$IP:5050/auth`, but if I log in with `admin: admin`, it freezes like logging in to Che.

However, I was able to solve this problem as follows.
- Reconnect the network of the machine that uses the browser
- Restart the machine that uses the browser

Is there anything that can be considered as a reason?

I appreciate your cooperation.

**Comment by ktdjun** [comment]
The issue has been resolved, so close this ticket.
Thank you for responding.
