### ISSUE TITLE
Can't copy-paste error message on chrome without going to browser's debug console

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#10232]
### Description
While reporting bug for https://github.com/openshiftio/openshift.io/issues/3884 I fount that it's not easy to copy-paste error message without going to debug console.
While it maybe OK for web-devs it cause problems for regular users and might impact quality of bug reports. Probably users will forced to insert screenshots more often and this prevent from doing text search for github issues.

### Reproduction Steps
Try to copy-paste text from error message.

**OS and version:**    
che.openshift.io - Revision: 7d88e4900d0452ee Build Time: 2018-06-27 17:47:56

BTW can't copy-paste version info from dialog Help -> About

**Diagnostics:**

**Comment by vparfonov** [comment]
fixed in https://github.com/eclipse/che/issues/9727
