### ISSUE TITLE
Need to publish PVC events to the machine logs

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#10230]
Currently only pod / container events are published to the machine logs. It would be great to enrich the logs with the pvc events e.g. "Failed Binding":

![image](https://user-images.githubusercontent.com/1461122/42095600-52b067a4-7bb3-11e8-81e5-59f4a66a7363.png)

**Comment by eivantsov** [comment]
@ibuziuk can you reference this issue in your PR?

**Comment by benoitf** [comment]
AFAIK @eivantsov issue of PR is https://github.com/eclipse/che/issues/10229 not this one

**Comment by eivantsov** [comment]
Hm.. the other one says all events, this one says pvc events.

@ibuziuk can you clarify?

**Comment by ibuziuk** [comment]
https://github.com/eclipse/che/issues/10229 says about publishing all `pod` events (not just containers), this one is about adding PVC events to the logs

**Comment by eivantsov** [comment]
But do all pod events contain pvc events too?

**Comment by ibuziuk** [comment]
well, events are related to objects, so pod & pvc events are different. On the screenshot in the issue description there are 4 events - 2 of them are `pod` events (Failed Sync / Failed Sheduling) and a two are `pvc` events (Failed binding)

**Comment by gazarenkov** [comment]
We definitely should not miss a single event generated by kubernetes, it is the main (and only?) source of truth for support. I believe we have RuntimeStatusEvent for all of it (see no problems even if some of them are duplicated with MachineStatusEvents). 
@sleshchenko wdyt?

**Comment by eivantsov** [comment]
@ibuziuk thanks - yes it does make sense!

**Comment by sleshchenko** [comment]
@gazarenkov Well, I think `RuntimeStatusEvent` can not be used for publishing such events. When [RuntimeEvents](https://github.com/eclipse/che/issues/7046) will be ready to use, all K8s/OpenShift events may be republished with them. But it won't be shown anywhere and clients should be improved to receive and display somewhere such information.

**Comment by gazarenkov** [comment]
@sleshchenko 
Could you please rephrase your concerns?

Is that we are technically not able to emit them or you mean even if they will be emitted we will not be able to show them?
(making them visible is exactly the point AFAIU)

**Comment by sleshchenko** [comment]
@gazarenkov 
```java
public interface RuntimeStatusEvent {
  String getStatus();
  String getPrevStatus();
  RuntimeIdentityDto getIdentity();
  String getError();
  boolean isFailed();
}
```
I just say that `RuntimeStatusEvent` is not flexible enough to wrap Kubernetes/OpenShift event with related object info, message, status, etc.
But it will be possible when `RuntimeEvent` will be introduced.

**Comment by sleshchenko** [comment]
As far as I know, the only place where `RuntimeStatusEvent` is used - notifying Workspace API (WorkspaceRuntimes) about runtime abnormal stop by infrastructures (like when one of the machines crashed). So, it's used as an internal event - there is no need to publish it to clients, and it would be even more clear to create a special event for that `RuntimeAbnormallyStoppedEvent` IMHO.
