### ISSUE TITLE
Simplify the CLI command for launch selenium tests

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10240]
### Description
Our selenium tests launcher is specialized for launch selenium tests on docker environment. This is related to the old strategy when we had only che on the docker platform.  But in current time we have the which runs on the different environments (for example "openshift-origin").  And we should specify a lot of arguments in CLI:
```
./selenium-tests.sh -Mlocal --threads=1 --host=http://che-eclipse-che.***********.nip.io --port=80 --test=DialogAboutTest
```
So we should update our launcher for checking "Che" assembly and working with default values of each 
assemblies. In the result, we should be able to launch tests on any assembly on the host machine without providing additional arguments.
For example:
```
./selenium-tests.sh -Mlocal --threads=1 --test=DialogAboutTest
```

**Comment by rhopp** [comment]
Obsolete. Closing.
