### ISSUE TITLE
Implement servers authentication with jwtproxy for Docker infrastructure

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10242]
### Description
Cover ws-agent/exec-agent/terminal with JWT proxy on Docker infrastructure.

It includes the following operations:

- add jwtproxy container for one workspace;
- configure jwtproxy in the added container, the corresponding public key and config file should be injected into the container. The injection can be implemented with using secrets;
- rewrite public accessible servers to jwtproxy ones instead of original;

It's related to https://github.com/eclipse/che/issues/10081.

**Comment by skabashnyuk** [comment]
won't fix. Not relevant for che7.
