### ISSUE TITLE
Apply javascript method.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#10258]
### Description ###
To cover xterm.js 3.3.0 by selenium tests(https://github.com/eclipse/che/pull/10037) should be applied javascript method to get text from newer version of the xterm.js terminal. New version of the xterm.js use canvas render instead of dom render, so with help selenium web driver we can't get text from terminal, because selenium web driver designed to get text from dom element's.

**Comment by gazarenkov** [comment]
Thanks @AndrienkoAleksandr 

@musienko-maxim I guess you're interested to follow this.

**Comment by musienko-maxim** [comment]
I'm looking forward to it

**Comment by AndrienkoAleksandr** [comment]
I applied to the dom method to get terminal text:
```
this.IDE.TerminalContentProvider.getRenderedText("Terminal", "dev-machine");

 - first argument is terminal name;
 - second argument is machine name;
```

**Comment by dmytro-ndp** [comment]
method name is actually `IDE.TerminalContentProvider.getVisibleText("Terminal", "dev-machine")`
