### ISSUE TITLE
Installer agent timeout

### ISSUE THREAD

**Issue by upnica** [eclipse-che/che#10276]
Hi, just a question at the moment, is there any way to increase the timeout of an installer script?

I have a very long running set of instructions, and the installer times out during the build of the factory, ideally i would want to keep this as an installer script so it can be used in multiple factories.

I have tried changing the timeout environment variable with no success so i'm assuming installers have a separate timeout.

I had changed `CHE_INFRA_DOCKER_BUILD__TIMEOUT__SEC` to an hour with no change.

**Comment by sleshchenko** [comment]
Hi,

Here are properties that configure bootstrapping timeouts for Docker infrastructure

https://github.com/eclipse/che/blob/f80c1867fc6de818bb585cd14774a6cf2fadc585/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L256-L262

The corresponding environment variables are: `CHE_INFRA_DOCKER_BOOTSTRAPPER_TIMEOUT__MIN` and `CHE_INFRA_DOCKER_BOOTSTRAPPER_INSTALLER_TIMEOUT_SEC`.

There are the same properties for Kubernetes and OpenShift infrastructures
https://github.com/eclipse/che/blob/f80c1867fc6de818bb585cd14774a6cf2fadc585/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L361-L362

Notify me if it doesn't work for you.

**Comment by upnica** [comment]
Thanks @sleshchenko, setting the environment variable `CHE_INFRA_DOCKER_BOOTSTRAPPER_INSTALLER__TIMEOUT__SEC` to a higher number seems to have the job. Thanks very much.
