### ISSUE TITLE
Create E2E selenium tests to check creation of workspace from Java Theia stacks

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10280]
### Description
We need to automate E2E testing of usage _Java Theia_ stacks to create workspace (both _Docker_ and _OpenShift_ versions): ensure that workspace is created successfully with default parameters, and that _Che Theia_ works correctly inside workspace:
![eclipse che new workspace](https://user-images.githubusercontent.com/1197777/42308765-3574f098-803f-11e8-9da6-5a47c73ec5d7.png)

Light check of _Che Theia_ working capacity could be the call of `Help > About` menu and wait on _About Dialog_ appearance:
![screenshot from 2018-07-12 12-34-11](https://user-images.githubusercontent.com/1197777/42625866-80739396-85d1-11e8-819d-5dfdf861ea6f.png)

Basic part of test has been created: https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/CreateWorkspaceFromJavaTheiaOpenshiftStackTest.java

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10050

**Comment by SkorikSergey** [comment]
Done by https://github.com/eclipse/che/pull/11079.
