### ISSUE TITLE
Extend GitHub VSCode Extension to integrate Pull Request Review Flows

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#10282]
### Description
With the version Che 6 (and prior), we had introduce a pull request panel which automated the creation of a pull request from the IDE. 

The goal of this epic is to extend the GitHub VSCode extension (https://github.com/eclipse/che/issues/11867) in order to integrate the different flows we were previously handling. 

**User Stories:**
- When a user is creating a pull request from Che, it will provide in the comment of the pull request a reviewer link (factory based on the dedicated devfile).
- When the reviewer link is opened, it will directly checkout the proper PR branch and show the list of comments in the source code (using the capabilities on the GitHub VSCode Extension

**Comment by ibuziuk** [comment]
Initial implementation of the plugin would be done as part of the - https://github.com/redhat-developer/rh-che/issues/778
