### ISSUE TITLE
Links in che/CUSTOMIZING.md are not working

### ISSUE THREAD

**Issue by fErten** [eclipse-che/che#10296]
### Description
There is a documentation related to extending the eclipse-che framework inside of [CUSTOMIZING.md](https://github.com/eclipse/che/blob/master/CUSTOMIZING.md) file in the root. However, the links that are provided for detailed explanation/example are not working.

**Comment by eivantsov** [comment]
@fErten thanks for the pointer.

While it is being fixed, you may take a look at https://www.eclipse.org/che/docs/
