### ISSUE TITLE
Command removed after a freeze

### ISSUE THREAD

**Issue by lmorel3** [eclipse-che/che#10309]
### Description
Sometimes Che freeze when I'm trying to save a Command. Then, I must reload the tab and when Che has been reloaded, the command has disappeared. Even if I was editing an existing one.

### Reproduction Steps
Edit a command and save it (maybe too quickly), so that Che freeze.
Reload the tab.

**OS and version:**    
Ubuntu 18.10 (x64), running Che in a Docker container

**Diagnostics:** 
I don't have any error log.

**Comment by eivantsov** [comment]
@lmorel3 if you click save, and do not wait till command is saved and reload the tab, chances are that request from the client never reaches server.

Can you consistently reproduce it? Maybe you can record a short gif or a screencast?

**Comment by lmorel3** [comment]
@eivantsov I'll try to record a short gif. Thanks.

Moreover, sometimes I had another strange message telling that "A command with this name already exists" whereas I was editing it.. :)

**Comment by lmorel3** [comment]
@eivantsov I had the same problem twice this week. But today, when I tried to record a gif, I wasn't able to reproduce...

However, when I open a command, I always have this in the browser's console:

![Stacktraces](https://user-images.githubusercontent.com/1393808/42562711-bc74bbc0-84fc-11e8-8b6b-f7556744e2d6.png)


Is it a normal behavior? :)

**Comment by lmorel3** [comment]
@eivantsov I finally reproduced the bug!

![command-freeze](https://user-images.githubusercontent.com/1393808/42563908-b3266692-84ff-11e8-8d9e-c933a6e9c03c.gif)

As you can see, I had other files opened when it happened. I try to save the command and then run it. Finally the tab freeze, so I have to reload it. Then, the command is not here anymore... :)

But I can't find related logs. Maybe I'm not looking at the right place?

**Comment by RomanNikitenko** [comment]
As I can see the first two logs from browser's console are related to https://github.com/eclipse/che/issues/8984, but it can not impact on commands, just redundant actions in command editor case (sure we should skip and do not fire these events from client side for command editor case).
The next two logs are more helpful and we should investigate this case.

**Comment by eivantsov** [comment]
@vparfonov can this be taken to a sprint?

**Comment by lmorel3** [comment]
It happened again. :)

**Comment by RomanNikitenko** [comment]
@lmorel3 
Hello!
I've fixed [errors](https://github.com/eclipse/che/issues/10309#issuecomment-404104105), but can not reproduce freezing IDE. 
Could you try to reproduce the bug on current version of CHE or provide some details like your project, command and so on.
Thank you!

**Comment by lmorel3** [comment]
Hi @RomanNikitenko, and thanks for the fix. Perhaps, I can't reproduce... :)
