### ISSUE TITLE
REST-API compatibility is not reflected in swagger.json version number

### ISSUE THREAD

**Issue by toorog** [eclipse-che/che#10321]
### Description
If I have an application connected to che via swagger definition, there is no way to know if my generated client is still compatible with the server API. Root cause of that problem is that the API version field of the swagger file is not used at all.

My suggestion would be to use the `info.version` field in swagger.json to maintain the version compatiblity of that API. Every change in the API needs to lead to a new swagger version number.

A more easy approach could be to simply use the current che version number as API-Version number. But of course this is not such a good solution as it would always make the API incompatible when a new release is created.

**Comment by eivantsov** [comment]
@toorog good point but Che API isn't versioned. You may safely assume that client is compatible with the API.

But I agree that we should either remove API version or replace it with Che release version:

![image](https://user-images.githubusercontent.com/5337267/42489898-691795d8-8416-11e8-9fde-4d809c946d40.png)

@skabashnyuk it looks like @mkuznyetsov can take care of it as he dealt with swagger more often that the others.

**Comment by toorog** [comment]
@eivantsov I partitally agree, if che API is not versioned at all, it is good to use the che version for the API as well. But there should definitely be some version inside the swagger file.
I am working in a microservice environment where che is just one of many services. Without a version number in swagger.json there would be no way (for a REST-Client) to dynamically determine the current supported API version and therefore using a matching client implementation. Hence removing the api version tag completely, would always require the clients to be manually configured for the che version currently deployed.

**Comment by eivantsov** [comment]
@toorog so, what you are looking is a way for the client to determine current Che master version?

Right now the version is hardcoded and indeed does not make any sense https://github.com/eclipse/che-lib/blob/master/swagger/che-swagger-module/src/main/java/org/eclipse/che/swagger/deploy/BasicSwaggerConfigurationModule.java#L29

**Comment by eivantsov** [comment]
@toorog I see what you mean, but there's no such thing as api version for Che. At least at the moment. 

So, your client may safely assume that it is ALWAYS compatible with whatever API Che master serves.

**Comment by toorog** [comment]
@eivantsov My experience is unfortunately a different one. I am using the swagger API since che 5.x. Now we are at 6.7.1 and I can't remember a single che upgrade where the API remained compatible to the previous one. Our REST-Clients were always broken because either and endpoint was removed, or DTO structures changed.

**Comment by skabashnyuk** [comment]
@toorog we are very sorry that you experience such kind of problems. Maybe we missed something. Can you provide some examples in 6.0.x-6.7.x window?

**Comment by eivantsov** [comment]
@toorog if that's upgrade from 5.x to 6.x then yes, there can be incompatibilities.

**Comment by slemeur** [comment]
@skabashnyuk : We have been discussing this over the last years and we discussed about introducing a versioning model to the API (separated indeed from the Che versions itself.) We need to track the changes in APIs versions after versions so third part contributors can track and document the changes and easily adapt their clients. 

What was your plan in order to introduce versioning of the API and backward/supportability strategies, and API changelog? 

cc @l0rd

**Comment by skabashnyuk** [comment]
>What was your plan in order to introduce versioning of the API and backward/supportability strategies, and API changelog?

We have no (suppose to) breaking changes between major releases.
Now I'm looking for more information if it's not the case.

**Comment by l0rd** [comment]
@skabashnyuk can't we follow https://semver.org/ when it's about versions and breaking changes?

**Comment by gorkem** [comment]
How hard would it to be to have an automated test set that checks the compatibility and flags incompatible changes? This is not the first time I heard from an adopter about API compatibility, I feel that automating the checks and managing breaking changes is the way forward. 

Also updating `info.version`  is not a good idea.

**Comment by skabashnyuk** [comment]
>@skabashnyuk can't we follow https://semver.org/ when it's about versions and breaking changes?

See no reason why not.

>How hard would it to be to have an automated test set that checks the compatibility and flags incompatible changes?

Good question. It would be nice to narrow the scope about which API we are talking about, then we can try to figure out something.

>This is not the first time I heard from an adopter about API compatibility, I feel that automating the checks and managing breaking changes is the way forward.

Until now I have no confirmed facts of API change since our last major release. 


>Also updating info.version is not a good idea.

Info version in swagger now hardcoded to 1.0. During this sprint, we want to make it possible to show che version in swagger instead of hardcoded value https://github.com/eclipse/che/issues/10351

As far as I remember our rules were:
 - Incompatible changes are possible during a major release
 - If incompatible changes are needed in minor version, we need to warn a community at least for 1.5 months before this changes happened. Now it's 2 minor releases.

**Comment by skabashnyuk** [comment]
>@skabashnyuk : Where are all the changes on the apis listed? I don't think we do that today, but we should - it would definitely make the plateform easier to leverage for OEM and contributors.

A good question to discuss on next community call.

**Comment by skabashnyuk** [comment]
done in https://github.com/eclipse/che-lib/pull/92
