### ISSUE TITLE
Theia: Investigate Reuse jdt.ls Workspace

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10325]
Currently, a new instance of jdt.ls is started for every new window containing Theia. In a first step, we would like to change the policy for allocating a data directory that we reuse the same workspace location when starting on the same workspace. Copies 2-n should have a policy that allows to reuse copies 2-n of eclipse workspaces.
In the long run, we would like to have one instance of jdt.ls running per theia back end, but for that we will have to establish some shared buffer infrastructure to make "didChange|open|close" consistent.

**Comment by svenefftinge** [comment]
> In the long run, we would like to have one instance of jdt.ls running per theia back end, but for that we will have to establish some shared buffer infrastructure to make "didChange|open|close" consistent.

That should be encapsulated and supported by the LS. I.e. allowing multiple LSP sessions and internally reusing caching where possible.
