### ISSUE TITLE
Create CI job to run E2E selenium tests of creation workspaces from stacks

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10346]
### Description
We need to have separate CI job for E2E selenium tests to check creation of workspaces from various kinds of stacks in _Eclipse Che Multiuser_ deployed on _OCP_ infrastructure daily.

Command to run the tests which are situated in the package **org.eclipse.che.selenium.stack**:
```
selenium-tests.sh --test=org.eclipse.che.selenium.stack.** --multiuser --threads=2
```
### References
#10050

**Comment by riuvshin** [comment]
https://ci.codenvycorp.com/view/qa/job/che-multiuser-master-ocp-stacks-test
