### ISSUE TITLE
Outdated Guide

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#10343]
### Reproduction Steps
https://www.eclipse.org/che/docs/parts.html#implementing-a-view

**OS and version:**    
Che 6.6.0

**Diagnostics:** 
I think, ide plugin guide is outdated, is there any sample code to create custom editor ui with new file type?

**Comment by eivantsov** [comment]
@cenkce thanks for pointing that out.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/7)
