### ISSUE TITLE
Display Che version in swagger UI

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#10351]
### Description

Currently, Swagger UI displays hardcoded API version which does not make a lot of sense: https://github.com/eclipse/che-lib/blob/master/swagger/che-swagger-module/src/main/java/org/eclipse/che/swagger/deploy/BasicSwaggerConfigurationModule.java#L29

It'd be good to grab actual Che version there.

**Comment by skabashnyuk** [comment]
I think it would be more reasonable to display rest Specification-Version instead of Implementation-Version. Specification-Version  - will reflect REST api version and will be not connected to Che version itself.
