### ISSUE TITLE
Implement terminal sidecar compatible with Kubernetes (and Openshift)

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10357]
### Description
We have a terminal sidecar that provides terminal access in other containers of a workspace.
But we don't have this functionality on Kubernetes and Openshift infras. 
This is an important part of Workspace.Next flow.   

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
link with this one https://github.com/eclipse/che/issues/10314
