### ISSUE TITLE
Implement exec sidecar compatible with Kubernetes (and Openshift)

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10358]
### Description
We need an exec sidecar that provides commands execution in other containers of a workspace on Kubernetes and Openshift infras. 
This is an important part of Workspace.Next flow.   

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
@garagatyi @AndrienkoAleksandr Isn't it already implemented?
