### ISSUE TITLE
Open in Terminal feature 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#10356]
### Description
Will be useful provide ability to open select folder in Project Explorer in terminal 

### Expected next behavior

1. User select some folder in Project Explorer
2. Call context menu (or action form menu) - "Open in Terminal"
3. Should be opened new terminal to the dev-machine and navigate to selected folder

**Comment by garagatyi** [comment]
Would be nice to have! But opening a file that is listed in the terminal in the editor would be also very cool!

**Comment by vparfonov** [comment]
@garagatyi 
Yes possibly useful but need to know editor name. Maybe just `cat some_file_name` ?

**Comment by garagatyi** [comment]
It was just an idea, not sure how hard it is to implement. But the content of the file is not what I was thinking about. It was rather figuring out a path to a file and open it in the editor. OS X terminal has something like that, but it works with paths, not just file names.

**Comment by benoitf** [comment]
it's for Theia  ?

**Comment by slemeur** [comment]
@vparfonov : This should be targeting the new IDE.

**Comment by vparfonov** [comment]
I want to use it in current Che version
