### ISSUE TITLE
Add websocket reconnection feature to workspace loader app

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10365]
### Description
Because of Ingress implementation details in k8s infra we have a situation when websocket connection from workspace-loader to master gets closed.
Since workspace-loader is using such a connection it gets stuck when this happens and doesn't open IDE when workspace becomes running.
UD handle this situation with automatic reconnection of a websocket. We need the same functionality in workspace-loader. 
This leads to a broken workspace start on kubernetes infrastructure.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@ashumilova not sure how to qualify the issue - bug or task. Please, take a look and, if possible, take in the new sprint.

**Comment by ashumilova** [comment]
need to try reconnecting-websocket library
