### ISSUE TITLE
Unable to create Workspace in Che 6.8.0 - Openshift 3.9.0

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#10378]
### Description
I've deployed Che 6.8.0 on Openshift 3.9 backed by Gluster for storage.
On launching the default Java stack with web-java-spring project, following issue is reported.

**Workspace Start Logs**
mkdir -p /tmp/bootstrapper/ /workspace_logs/bootstrapper
mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1
Bootstrapping of machine dev-machine failed. Cause: mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1

**Che-Server Logs**
2018-07-11 10:34:47,624[ineSharedPool-0]  [ERROR] [a.l.ErrorMachineLogEventLogger 42]   - Machine `dev-machine` error from owner=`che` env=`default` workspace=`workspacek7agz98y7d6azqc2` text=`mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
  | command terminated with non-zero exit code: Error executing in Docker Container: 1` time=`2018-07-11T10:34:47.624Z`
  | 2018-07-11 10:34:47,633[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 191]  - Failed to start Kubernetes runtime of workspace workspacek7agz98y7d6azqc2. Cause: Bootstrapping of machine dev-machine failed. Cause: mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
  | command terminated with non-zero exit code: Error executing in Docker Container: 1

### Reproduction Steps
Deployed single user che using deploy.sh provided in the repository.

In addition I've set the following variables

export CHE_IMAGE_REPO=eclipse/che-server
export CHE_IMAGE_TAG=6.8.0
export CHE_OPENSHIFT_PROJECT=che
export CHE_INFRA_OPENSHIFT_PROJECT=che
export CHE_INFRA_KUBERNETES_PVC_STRATEGY=common
export CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS=true
export ENABLE_SSL=true
export CHE_INFRA_KUBERNETES_PVC_ACCESS__MODE=ReadWriteMany
export CHE_INFRA_KUBERNETES_PVC_QUANTITY=5Gi

**OS and version:**    
Openshift 3.9
Che 6.8.0

**Diagnostics:**

**Comment by eivantsov** [comment]
@hbhargav an arbitrary user does not have permissions to create files and folders. You need to investigate why your PVs have bad permissions.

**Comment by hbhargav** [comment]
@eivantsov 
I deleted the namespace & re-created.
The permissions issue is resolved.

Not sure if this is related to [https://github.com/openshift/origin/issues/17933](url)

Anyways, I'll close this ticket.

**Comment by kingkeivn** [comment]
@hbhargav how to delete namespace & re-created？
I've had the same experence as you .
