### ISSUE TITLE
tab names truncated when there is a  '-'  and the length overtakes the limit

### ISSUE THREAD

**Issue by lolo58200** [eclipse-che/che#10374]
### Description
tab names truncated when there is a  '-'  and the length overtakes the limit

### Reproduction Steps
create a file  1_234567890123456789012345678901234567890123.txt
a tab named 1_234567890123456789012345678901234567890123...  opens
rename file and replace '_' by '-'
tab renamed 1-
expected 
tab renamed 1-234567890123456789012345678901234567890123...

**OS and version:**    
6.4

**Diagnostics:** 
![image](https://user-images.githubusercontent.com/32546163/42563351-57957d46-84fe-11e8-856b-ee5adfc34a17.png)

it is linked to a css property

**Comment by eivantsov** [comment]
@lolo58200 does it depend on the number of symbols? Can you reproduce it with less than 44? What happens if numbers are replaced with letters (uppercase/lowercase)?

**Comment by lolo58200** [comment]
with numbers: 
one can display up to 36
ex:  123456789012345678901234567890123456 is displayed 123456789012345678901234567890123456
but 1234567890123456789012345678901234567 is displayed 1234567890123456789012345678901234...
when there is a '-',  if the length > 36, then name is truncated up to the '-'
![image](https://user-images.githubusercontent.com/32546163/42804063-23da8114-89a8-11e8-9c27-cd3d5bc4822c.png)

with letters

**Comment by eivantsov** [comment]
Closed due to inactivity. This does not seem like a critical bug. Will be reopened when properly prioritized
