### ISSUE TITLE
Language servers with "internal": "true" are missing in workspace

### ISSUE THREAD

**Issue by DrRSatzteil** [eclipse-che/che#10396]
### Description
This is a follow up of issue #10194

When setting "internal": "true" for servers in the workspace config the server is not brought up when starting the workspace.

Without "internal": "true"
![image](https://user-images.githubusercontent.com/2452988/42628092-506ee2f6-85cf-11e8-95a9-ed81f21232be.png)

With "internal": "true"
![image](https://user-images.githubusercontent.com/2452988/42628212-add5106e-85cf-11e8-802a-0928234da4f0.png)

### Reproduction Steps

I currently use this ws config. The used recipes can be found in my github repository:
localhost:5000/myintelephense_sidecar: https://github.com/DrRSatzteil/che-dockerfiles/tree/master/recipes/sidecars/intelephense
localhost:5000/myjsts_sidecar: https://github.com/DrRSatzteil/che-dockerfiles/tree/master/recipes/sidecars/javascript-typescript-langserver
localhost:5000/myeclipse_php: https://github.com/DrRSatzteil/che-dockerfiles/tree/master/recipes/php (modified)
Stackbase: https://github.com/DrRSatzteil/che-dockerfiles/tree/master/recipes/stack-base/ubuntu (modified)

{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "js-ls-machine": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {
            "jsls": {
              "attributes": {
                "languageRegexes": "[{\"languageId\":\"js\", \"regex\":\".*\\\\.js$\"}]",
                "id": "js-ls",
                "type": "ls"
              },
              "port": "3334",
              "protocol": "tcp"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.terminal"
          ],
          "env": {
            "CHE_MACHINE_NAME": "js-ls-machine"
          }
        },
        "php-ls-machine": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {
            "phpls": {
              "attributes": {
                "languageRegexes": "[{\"languageId\":\"php\", \"regex\":\".*\\\\.php$\"}]",
                "id": "php-ls",
                "type": "ls"
              },
              "port": "3333",
              "protocol": "tcp"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.terminal"
          ],
          "env": {
            "CHE_MACHINE_NAME": "php-ls-machine"
          }
        },
        "dev-machine": {
          "attributes": {
            "memoryLimitBytes": "4294967296"
          },
          "servers": {
            "80/tcp": {
              "attributes": {},
              "port": "80",
              "protocol": "http"
            },
            "8080/tcp": {
              "attributes": {},
              "port": "8080",
              "protocol": "http"
            },
            "8000/tcp": {
              "attributes": {},
              "port": "8000",
              "protocol": "http"
            }
          },
          "volumes": {},
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ls.json"
          ],
          "env": {
            "CHE_MACHINE_NAME": "dev-machine"
          }
        }
      },
      "recipe": {
        "type": "compose",
        "content": "services:\n php-ls-machine:\n  image: 'localhost:5000/myintelephense_sidecar'\n  mem_limit: 1073741824\n js-ls-machine:\n  image: 'localhost:5000/myjsts_sidecar'\n  mem_limit: 1073741824\n dev-machine:\n  image: 'localhost:5000/myeclipse_php'\n  mem_limit: 4294967296\n  depends_on:\n   - php-ls-machine\n   - js-ls-machine\n",
        "contentType": "text/x-yaml"
      }
    }
  },
  "projects": [
    {
      "links": [],
      "name": "documentmanager",
      "attributes": {
        "contribute_to_branch": [
          "master"
        ]
      },
      "type": "blank",
      "source": {
        "location": "git@github.com:DrRSatzteil/documentmanager.git",
        "type": "github",
        "parameters": {}
      },
      "path": "/documentmanager",
      "problems": [],
      "mixins": [
        "pullrequest"
      ]
    },
    {
      "links": [],
      "name": "/nextcloudserver",
      "attributes": {},
      "type": "blank",
      "source": {
        "location": "https://github.com/nextcloud/server.git",
        "type": "git",
        "parameters": {}
      },
      "path": "/nextcloudserver",
      "problems": [],
      "mixins": []
    }
  ],
  "name": "wksp-3rnj",
  "commands": [
    {
      "commandLine": "[ -z ${editor.current.file.path} ] && echo \"Open a PHP file in the editor before executing this command.\" || php ${editor.current.file.path}",
      "name": "run php script",
      "attributes": {
        "goal": "Run",
        "previewUrl": ""
      },
      "type": "custom"
    },
    {
      "commandLine": "[ -z ${editor.current.file.path} ] && echo \"Open a PHP file in the editor before executing this command.\" || QUERY_STRING=\"start_debug=1&debug_host=localhost&debug_port=10137\" php ${editor.current.file.path}",
      "name": "debug php script",
      "attributes": {
        "goal": "Debug",
        "previewUrl": ""
      },
      "type": "custom"
    },
    {
      "commandLine": "service apache2 start && tail -f /var/log/apache2/access.log -f /var/log/apache2/error.log",
      "name": "start apache",
      "attributes": {
        "goal": "Run",
        "previewUrl": "${server.80/tcp}/${current.project.relpath}"
      },
      "type": "custom"
    },
    {
      "commandLine": "service apache2 stop",
      "name": "stop apache",
      "attributes": {
        "goal": "Run",
        "previewUrl": ""
      },
      "type": "custom"
    },
    {
      "commandLine": "service apache2 restart",
      "name": "restart apache",
      "attributes": {
        "goal": "Run",
        "previewUrl": "${server.80/tcp}/${current.project.relpath}"
      },
      "type": "custom"
    }
  ],
  "links": []
}

**OS and version:**    
Ubuntu 18.04

**Diagnostics:** 
Screenshots are provided above. Needless to say the ls servers are not accessible with server config: "internal": "true".

**Comment by DrRSatzteil** [comment]
Running che 6.8.0

**Comment by gazarenkov** [comment]
I believe the intension of "internal" is to not to return them by default request and not to show by default in the client (just because client can do nothing with it), so, this behavior looks correct, no?

**Comment by DrRSatzteil** [comment]
To be honest I don't really get the point of this attribute. I was following these instructions:
https://www.eclipse.org/che/docs/language-servers.html
where it says:
"attributes.internal - true. Mandatory! Used to get an internal link to server"

The thing is: As long as I set internal to true I cannot use the language server at all so this cannot be correct. Maybe the documentation needs to be updated? Everything seems to work fine when I do not set servers to be internal.

However internal servers that were setup via installers (like the terminal in my example) are shown in the server tab as well.

**Comment by gazarenkov** [comment]
I think terminal provided by installer is not internal in any case.

Are you sure the ONLY changing the attribute "internal": "true" makes your LS non-functional?

**Comment by DrRSatzteil** [comment]
@gazarenkov I thought it is because it is hidden when I check "hide internal servers"

@skabashnyuk che tells me that the wokspace cannot be found

However I just realized that compared to che 6.7.1 the language server in 6.8.0 in fact does work even when it is not shown in the server tab. So if this is the expected behaviour there is really no issue here.

Thanks for your help!
