### ISSUE TITLE
Can't access web interface for docker image

### ISSUE THREAD

**Issue by OliverCole** [eclipse-che/che#104]
Latest docker, Windows 7, following the docs at https://eclipse-che.readme.io/docs/install-using-docker.

After running the image, I can't connect to localhost:8080, or any other mapped port. I suspect it relates to these errors!

```
Oliver@velocity MINGW64 ~
$ docker run -it -p 9000:8080 -p 49152-49162:49152-49162 codenvy/che
Using CATALINA_BASE:   /home/user/che-3.13.4.2
Using CATALINA_HOME:   /home/user/che-3.13.4.2
Using CATALINA_TMPDIR: /home/user/che-3.13.4.2/temp
Using JRE_HOME:        /opt/jdk1.8.0_45
Using CLASSPATH:       /home/user/che-3.13.4.2/conf/:/opt/jdk1.8.0_45/lib/tools.jar:/home/user/che-3.13.4.2/bin/bootstrap.jar:/home/user/che-3.13.4.2/bin/tomcat-juli.jar
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Command failed
mount: permission denied
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
time="2015-12-02T22:01:47.227010437Z" level=error msg="'overlay' is not supported over aufs."
time="2015-12-02T22:01:47.310522402Z" level=fatal msg="Error starting daemon: Error initializing network controller: error obtaining controller instance: Failed to create NAT chain: iptables failed: iptables -t nat -N DOCKER: iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)\nPerhaps iptables or your kernel needs to be upgraded.\n (exit status 3)"
2015-12-02 22:01:48,577[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.21
# Continues Tomcat launch
```

```
Oliver@velocity MINGW64 ~
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by TylerJewell** [comment]
Hi.  First, the docker image that is on the Che site is outdated. We do not yet have automation to support re-generation of the image. The image is for version 3.12.x, which is part of the old release train, and not part of the next generation platform for Eclipse. The next gen stuff is pre-alpha as part of the 4.0 branch.

Specific to the docker run - did you do this with root privs or another user?

If you'd like to test the latest stuff, we need you to build from source. It's relatively easy to do if you have 10 minutes.  Requires Java 8 and Maven 3.1.1+.

git clone http://github.com/codenvy/che
cd che
git checkout 4.0
cd assembly-sdk
mvn clean install
cd ..
./che.sh run
http://localhost:8080

We'll update the docker image for the alpha soon.

**Comment by ghost** [comment]
Hi,

The version itself does not matter here.

You took an example of mapping it to 9000 port, so che should be available at localhost:9000

Also, the image has to be run in a privileged mode, to support Docker in Docker.

So, docker run --privileged -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che should work

**Comment by OliverCole** [comment]
When I use --privileged the errors disappear, but I still can't access the web interface.

**Comment by TylerJewell** [comment]
This is an older version.  Can you tell us what you see with localhost:9000/che and also localhost:9000/dashboard 
Thanks.

-Tyler

On Thu, Dec 3, 2015 at 2:15 PM -0800, "OliverCole" notifications@github.com wrote:

When I use --privileged the errors disappear, but I still can't access the web interface.

**Comment by freewind** [comment]
I met this same issue. You should not connect to `localhost`, but the ip which the virtual machine provided, for me, it's `192.168.99.100` in the welcome message from "Docker Quickstart Terminal":

```
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com
```

This is really confused me who doesn't know docker, in the end I asked for help from some docker expert after several hours of struggling. 

Hope to put this information to the installation document

**Comment by ghost** [comment]
Yes, we'll add a boot2docker section to the installation docs. In this case, you should access VM IP directly, while for OS having a native Docker support it's just localhost.

**Comment by freewind** [comment]
Seems like `boot2docker` is deprecated?

https://github.com/boot2docker/boot2docker-cli

> Deprecated
> This project is officially deprecated in favor of Docker Machine. The code and documentation here only exist as a reference for users who have not yet switched over (but please do soon). The recommended way to install Machine is with the Docker Toolbox.

**Comment by OliverCole** [comment]
> You should not connect to `localhost`, but the ip which the virtual machine provided

That was it - thanks!
