### ISSUE TITLE
Add debug logging on each step of K8s/OS runtime start

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10408]
### Description
The motivation to do that is providing as many as possible information about K8s/OS workspace start fail.
If we have debug logs it will be easier to investigate on which step workspace fails to start, like in the following issue https://github.com/eclipse/che/issues/10390.
So, to debug such cases it will be possible to set `CHE_LOGGER_CONFIG=org.eclipse.che.workspace.infrastructure=DEBUG` as environment variable of Che Master deployment, retry to start a workspace and fetch Che Master Logs.

**Comment by mshaposhnik** [comment]
Here is example output of Che7 workspace startup:
<details>
  <summary>Logs</summary>
2018-10-30 12:07:36,112[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 322]   - Starting workspace 'admin/wksp-fibm' with id 'workspacebj642zwlxnogzj3d' by user 'admin'
--
  | 2018-10-30 12:07:36,950[aceSharedPool-2]  [DEBUG] [.k.w.SidecarToolingProvisioner 61]   - Started sidecar tooling provisioning workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:36,989[aceSharedPool-2]  [DEBUG] [penShiftEnvironmentProvisioner 102]  - Start provisioning OpenShift environment for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:36,989[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 99]   - Provisioning PVC strategy for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,056[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 116]  - PVC strategy provisioning done for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,059[aceSharedPool-2]  [DEBUG] [penShiftEnvironmentProvisioner 126]  - Provisioning OpenShift environment done for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,062[aceSharedPool-2]  [DEBUG] [.c.w.i.k.w.PluginBrokerManager 103]  - Entering plugin brokers deployment chain. Ws: workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,066[aceSharedPool-2]  [DEBUG] [c.w.i.k.w.b.ListenBrokerEvents 59]   - Subscribing broker events listener for ws workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,070[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 126]  - Preparing PVC started for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,107[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 132]  - Preparing PVC done for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,107[aceSharedPool-2]  [DEBUG] [o.e.c.w.i.k.w.b.DeployBroker 69]     - Starting brokers deployment for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,772[aceSharedPool-2]  [DEBUG] [o.e.c.w.i.k.w.b.DeployBroker 91]     - Brokers deployment finished for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:37,774[aceSharedPool-2]  [DEBUG] [e.c.w.i.k.w.b.WaitBrokerResult 53]   - Trying to get brokers result for ws workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:48,900[aceSharedPool-2]  [DEBUG] [.k.w.SidecarToolingProvisioner 72]   - Finished sidecar tooling provisioning workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:48,905[aceSharedPool-2]  [DEBUG] [penShiftEnvironmentProvisioner 102]  - Start provisioning OpenShift environment for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:49,209[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 99]   - Provisioning PVC strategy for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:49,223[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 116]  - PVC strategy provisioning done for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:49,225[aceSharedPool-2]  [DEBUG] [penShiftEnvironmentProvisioner 126]  - Provisioning OpenShift environment done for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:49,226[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 183]  - Provisioning of workspace workspacebj642zwlxnogzj3d completed.
  | 2018-10-30 12:07:49,227[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 126]  - Preparing PVC started for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:49,257[aceSharedPool-2]  [DEBUG] [n.p.UniqueWorkspacePVCStrategy 132]  - Preparing PVC done for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:49,660[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 602]  - Begin pods creation for workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:49,874[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 605]  - Creating pod workspacebj642zwlxnogzj3d.ws in workspace workspacebj642zwlxnogzj3d.
  | 2018-10-30 12:07:49,874[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 609]  - Creating machine ws/dev in workspace workspacebj642zwlxnogzj3d.
  | 2018-10-30 12:07:49,918[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 609]  - Creating machine ws/che-machine-exec in workspace workspacebj642zwlxnogzj3d.
  | 2018-10-30 12:07:49,940[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 609]  - Creating machine ws/theia-ide in workspace workspacebj642zwlxnogzj3d.
  | 2018-10-30 12:07:50,083[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 605]  - Creating pod workspacebj642zwlxnogzj3d.che-jwtproxy in workspace workspacebj642zwlxnogzj3d.
  | 2018-10-30 12:07:50,084[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 609]  - Creating machine che-jwtproxy in workspace workspacebj642zwlxnogzj3d.
  | 2018-10-30 12:07:50,208[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 623]  - Pods creation finished in in ws workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:51,219[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 314]  - Waiting to start machines of workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:55,533[ineSharedPool-1]  [DEBUG] [.i.k.KubernetesInternalRuntime 416]  - Bootstrapping machine che-jwtproxy in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:55,536[ineSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 366]  - Performing servers check for machine che-jwtproxy in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:07:55,539[ineSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 375]  - Servers checks done for machine che-jwtproxy in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,847[ineSharedPool-4]  [DEBUG] [.i.k.KubernetesInternalRuntime 416]  - Bootstrapping machine ws/che-machine-exec in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,877[ineSharedPool-3]  [DEBUG] [.i.k.KubernetesInternalRuntime 416]  - Bootstrapping machine ws/dev in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,901[ineSharedPool-6]  [DEBUG] [.i.k.KubernetesInternalRuntime 366]  - Performing servers check for machine ws/che-machine-exec in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,909[ineSharedPool-6]  [DEBUG] [.i.k.KubernetesInternalRuntime 375]  - Servers checks done for machine ws/che-machine-exec in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,910[ineSharedPool-7]  [DEBUG] [.i.k.KubernetesInternalRuntime 366]  - Performing servers check for machine ws/dev in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,910[ineSharedPool-5]  [DEBUG] [.i.k.KubernetesInternalRuntime 416]  - Bootstrapping machine ws/theia-ide in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,912[ineSharedPool-7]  [DEBUG] [.i.k.KubernetesInternalRuntime 375]  - Servers checks done for machine ws/dev in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:21,914[ineSharedPool-6]  [DEBUG] [.i.k.KubernetesInternalRuntime 366]  - Performing servers check for machine ws/theia-ide in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:25,793[aceSharedPool-2]  [DEBUG] [.i.k.KubernetesInternalRuntime 327]  - Machines of workspace workspacebj642zwlxnogzj3d started
  | 2018-10-30 12:09:25,793[ServersChecker]   [DEBUG] [.i.k.KubernetesInternalRuntime 375]  - Servers checks done for machine ws/theia-ide in workspace workspacebj642zwlxnogzj3d
  | 2018-10-30 12:09:25,798[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 364]   - Workspace 'admin:wksp-fibm' with id 'workspacebj642zwlxnogzj3d' started by user 'admin'


</details>
@sleshchenko  @skabashnyuk  It that looks sufficient?

**Comment by benoitf** [comment]
maybe the workspace id should be written first
```
workspacebj642zwlxnogzj3d : Started sidecar tooling provisioning 
```
instead of
```
Started sidecar tooling provisioning workspace workspacebj642zwlxnogzj3d
```

IMHO it's easier to read

**Comment by sleshchenko** [comment]
@benoitf I like your proposal. It would be easier to read if we would have one structure for debug logs at least for Infrastructures -> `Subject` (workspace id, machine name (optional), server name (optional)): `Action` (what happened)

**Comment by mshaposhnik** [comment]
It is require to rewrite also existing errors/warns/debugs to be similar and avoid mess in the logs.

**Comment by sleshchenko** [comment]
> It is require to rewrite also existing errors/warns/debugs to be similar and avoid mess in the logs.

`errors/warns` -> It would be nice to rework but is not really required.
`debugs` -> I don't think that we have many debug log during runtime start, so cool to do it now if we all agree with proposed format

**Comment by benoitf** [comment]
BTW here you're already adding tons of debug message so these one should be at least fixed
https://github.com/eclipse/che/pull/11787/files

**Comment by skabashnyuk** [comment]
@benoitf @sleshchenko is this blocker requirement or nice to have for https://github.com/eclipse/che/pull/11787 please clarify your POV.

**Comment by benoitf** [comment]
IMHO it's related to UX, so code owners are up to decide if UX is part of the requirements or not.
My POV is that we're using more time to discuss it than to move in the code workspaceID at the beginning instead at the end.

**Comment by slemeur** [comment]
@mshaposhnik : why the issue has been closed while the discussion was providing feedbacks? Is there  a new issues created related to those feedbacks? In this case, it would be nice to cross reference them in this issue.

**Comment by mshaposhnik** [comment]
@slemeur with c/owners we agrreed that for now pr satisfies issue requirements.
If we will see the need to change logging format/depth/etc we will create separate one.
