### ISSUE TITLE
Question: chown: changing ownership of ‘/projects’: Read-only file system while creating a new project

### ISSUE THREAD

**Issue by Katsuya-Tomioka** [eclipse-che/che#1040]
I'm getting "chown: changing ownership of ‘/projects’: Read-only file system" while creating a sample java project. I'm using native/native-docker on Ubuntu 15.10, OpenJDK 1.8.0_66. The running user has uid 1000.

**Comment by ghost** [comment]
What is your Docker version?

**Comment by Katsuya-Tomioka** [comment]
I was using default 1.6.2. I'll upgrade. Thanks.

**Comment by ghost** [comment]
Upgrade should solve the problem for you. I suspect it's because of `:z` suffix that we use when mounting workspace projects.

**Comment by ghost** [comment]
@Katsuya-Tomioka any update on this?

**Comment by Katsuya-Tomioka** [comment]
Works fine now as local native/local docker. As to exposing docker ip, I'm a bit confused. I think I need to expose the IP that the container gets assigned, correct? Am I correct to assume even in "server" setup, native che can talk to a docker server via local pipe? Thanks.
