### ISSUE TITLE
Wait until project will be removed functionality is removed from ocp.sh script

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10409]
### Description
There was a functionality to wait until project will be fully removed if error occurs during project creation.
But it was removed in https://github.com/eclipse/che/commit/a22a2b3510cfb3ab97779df0497909186e4831df#diff-700dab0819ba6724ee90d7050f15e35eL393

It would be nice to restore this functionality

### Reproduction Steps
1. Execute `oc new-project eclipse-che`.
2. Execute `ocp.sh --remove-che`
3. Execute `ocp.sh --deploy-che`
Expected: ocp script will wait until project will fully removed and then will create `eclipse-che` project
Actual: the following error is displayed
```
serg@sergpad:~/projects/che$ ocp --deploy-che --multiuser --rolling --debug --no-pull
Logging in to OpenShift cluster...
....
[INFO]: Checking if you are currently logged in... 
[INFO]: Active session found. Your current context is: /172-17-0-1:8443/developer 
[INFO]: Creating namespace "eclipse-che" 
Error from server (AlreadyExists): project.project.openshift.io "eclipse-che" already exists
[ERROR]: Failed to create namespace eclipse-che. It may exist in someone else's account or namespace deletion has not been fully completed. Try again in a short while or pick a different project name -p=myProject
```
**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
@sleshchenko thanks for reporting it. I'll take a look anytime soon

**Comment by metlos** [comment]
Fixed by https://github.com/eclipse/che/pull/13443.
