### ISSUE TITLE
How to add a service witch runs on docker

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#10419]
Hi,

I have a dockerfile witch builds a docker image that runs a node service on port 8081.
I would like to build and start this docker service when I start eclipse che.

How could I do this? I already tried to add my dockerfile inside of the dockerfiles directory expecting that my docker images was built, but is not working.

Thanks.

**Comment by eivantsov** [comment]
@mstavares you can either build an image, push it to a registry and create a custom stack in Che, or create a custom stack from a Dockerfile

https://www.eclipse.org/che/docs/creating-starting-workspaces.html

**Comment by mstavares** [comment]
Hi @eivantsov, thanks for your reply.

Your solutions seems fit very well. There is a way to get the docker IP that I'm gonna launch in when my workspace is built?

**Comment by eivantsov** [comment]
@mstavares not sure I understood your question? Are you asking me to find out your host machine IP? :)

**Comment by mstavares** [comment]
@eivantsov for instance:

"frontend": {
              "installers": [
                "org.eclipse.che.exec", "org.eclipse.che.terminal"
              ],
              "servers": {
                "8081/tcp": {
                  "port": "8081",
                  "protocol": "http"
                }
              },
              "attributes" : {}
            }

Is it possible to define a static IPv4 address for this machine in the stack?
This machine "frontend" runs a docker when I instantiate a workspace through this stack. I would like to know the IP address of this docker container.

**Comment by eivantsov** [comment]
@mstavares no it is not possible

**Comment by mstavares** [comment]
@eivantsov is not possible to define it in the stack, but is it possible to define it somewhere else?

**Comment by eivantsov** [comment]
Container gets some IP from Docker subnet. Che cannot set or predict it.

**Comment by mstavares** [comment]
Hi @eivantsov 

Is it possible to set a static port?

Key             PORT    PROTOCOL    RUNTIME
8081/tcp     8081       http                 URL: http://172.17.0.1:32962

For instance, I would like to set this port 32962 to this one 8081 even when I reboot my workspace.
