### ISSUE TITLE
Update theia version to 0.3.12 in Che

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#10429]
As far as Theia has released [0.3.12](https://github.com/theia-ide/theia/releases/tag/v0.3.12) and it contains a new plugin model - there is need to update Theia to the latest version in eclipse/che-theia image, in [hosted plugin manager](https://github.com/eclipse/che-theia-hosted-plugin-manager-extension).

**Comment by mmorhun** [comment]
Won't fix
