### ISSUE TITLE
TextMate grammer support in Eclipse Che for Language Server provided via sidecar

### ISSUE THREAD

**Issue by ElectronicWizzard** [eclipse-che/che#10439]
# Description

With the 6.8.0 version of Che my LS sidecar following https://www.eclipse.org/che/docs/language-servers.html#ls-sidecars works now! Means I have syntax check and code completion support working. However I am missing syntax highlighting. I have a TextMate language grammer I would like to provide with my Language Server sidecar as well. Do you plan to support this as well?

**Comment by eivantsov** [comment]
@ElectronicWizzard Eclipse Che supports LSP and whatever LSP and the particular language server has in its capabilities. If your language server does not perform code analysis, you won't see editor warnings in Che.

You can track available language servers and progress being made at https://langserver.org/

**Comment by ElectronicWizzard** [comment]
Editor warnings is working, however I do not have syntax highlighting and saw that Eclipse Photon allows to use TextMate files.  Youtube vide https://www.youtube.com/watch?v=Pe_6mA8c48Y 

![textmate2](https://user-images.githubusercontent.com/21276419/42812934-7815bcc8-89bf-11e8-955f-0f6d78a6168c.png)
![textmate1](https://user-images.githubusercontent.com/21276419/42812937-7a5ecaf6-89bf-11e8-8f7a-606a5732810d.png)

**Comment by eivantsov** [comment]
Syntax highlighting is provided by Orion Editor, not bu the language server. And it's not possible to dynamically provision custom syntax coloring schemes for custom file types.
