### ISSUE TITLE
Right-click menu can not display completely in some resolution

### ISSUE THREAD

**Issue by liubin10** [eclipse-che/che#10447]
### Description
Right-click menu can not display completely in some resolution of laptop.
What I have known is that if the right-click menu can not pop down completely, it will pop up.
What if it can not also  pop up completely?
In my case, I right click the middle file of project, it can not pop up completely.

![1531819979683](https://user-images.githubusercontent.com/32632875/42810008-7d895578-89e9-11e8-9225-8349e55b4333.png)

**Comment by vparfonov** [comment]
rise to P1 looks like bud UX
