### ISSUE TITLE
NumberFormatException in PodEvents class

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10444]
### Description
After reviewing ws-master log file that is made after selenium tests, I've noticed this error. @ibuziuk zuik I think this class is made by you. Can you take a look?
[che-server-pod.log.txt](https://github.com/eclipse/che/files/2200835/che-server-pod.log.txt)

**Comment by ibuziuk** [comment]
PR has been sent - https://github.com/eclipse/che/pull/10546
