### ISSUE TITLE
Source folders of Plain Java project  are not properly shown in Project Explorer after WS is restarted

### ISSUE THREAD

**Issue by vrubezhny** [eclipse-che/che#10456]
### Description

(Using LS branch)
Source folders of Plain Java project  are not properly shown in Project Explorer after workspace is restarted

### Reproduction Steps
1. Create Plain java project;
2. Expand its tree in Project Explorer - check if 'src' folder is shown with 'blue' folder icon
3. Stop workspace, restart it once it's finally stopped and wait for it's fully started (including LS) 
4. Expand its tree in Project Explorer - check if 'src' folder is shown with 'blue' folder icon 
    (FAILED - 'src' folder is shown with 'yellow' folder icon despite the fact it is a Source folder and as such it should be shown with the blue one. You can open 'Configure Classpath' dialog to make sure if it is really a source folder)

![project-creation-and-restart](https://user-images.githubusercontent.com/620781/42825492-69a7fc64-89e2-11e8-9dc9-1f1d4eb00812.gif)

**Comment by eivantsov** [comment]
@vrubezhny I failed to reproduce it on master. What's interesting, in your case a project loses its project type after restart, and then acquires it again.

Can you check if the issue is there when you use master? If not, we'll assign to languages team then.
