### ISSUE TITLE
ProjectExplorer.expandAll() sometimes does not expand all

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10462]
In some selenium tests (CheckFileWatcherExcludeFeatureTest, line 86, for example) we get failures because "projectExplorer.quickExpandWithJavascript()" does not reveal some files. In this particular case, it does not expand the ".che" folder.
Manually expanding the .che folder or putting a breakpoint on line 85 makes the test pass, so there seems to be some kind of timing dependency.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/6)
