### ISSUE TITLE
Wrong wait in CheckFileWatcherExcludeFeatureTest

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10479]
The mentioned test waits for invisibility of the ".che" folder, but really should wait for "projectname/.che" to be _visible_

**Comment by eivantsov** [comment]
@eclipse/eclipse-che-qa can you comment please and label the issue accordingly?

**Comment by SkorikSergey** [comment]
I cannot find checking ".che" folder invisibility in https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/filewatcher/CheckFileWatcherExcludeFeatureTest.java selenium test. Could you provide additional information.

**Comment by tsmaeder** [comment]
It's in the jdt.ls branch.

**Comment by musienko-maxim** [comment]
I suspect, that this test is out of date. As variant you can try to replace this one on the latest version from upstream and run again
