### ISSUE TITLE
Section "Machines" disappeared while renaming stack

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#10486]
### Description
When creating new workspace there is possibilty of renaming Machine. When I try to rename it using uppercase letters, whole section "Machines" disappears.

### Reproduction Steps

- Go to che dashboard and click on Stacks in left menu.
- Click Add Stack button.
- Click on pencil icon next to machine name in "Machines" - POD/MAIN
- Rename it to something containing upper case letters - e.g. SOMETHING or Something

**OS and version:**    
Che version 6.8.0 (run on minishift using minishift addon che).

**Diagnostics:** 
![output](https://user-images.githubusercontent.com/29278800/42940548-34c98692-8b5a-11e8-935f-a5b12fe968ca.gif)

**Comment by eivantsov** [comment]
@Katka92 I recommend that you check with the latest nightly. A PR was merged that removes one of these buttons.

**Comment by eivantsov** [comment]
@Katka92 thanks for checking.

Closed
