### ISSUE TITLE
Dev-machine can be removed after renaming

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#10487]
### Description
After renaming the machine, it can be deleted. Project then does not have any machine specified and new machine can not be added. 

### Reproduction Steps
- Go to che dashboard and click on Stacks in left menu.
- Click Add Stack button.
- Click on pencil icon next to machine name in "Machines" - POD/MAIN
- Rename it - e.g. "renamed"
- Click trash icon and delete the machine.
(Now whole section "Machines" has disappeared.)
- Click on Add button and create new machine.
(Nothing happens.)

**OS and version:**    
Che version 6.8.0 running on minishift (using minishift addon che). 

**Diagnostics:** 
After deleting there is an error in browser console:

![screenshot from 2018-07-19 13-55-21](https://user-images.githubusercontent.com/29278800/42941004-97037308-8b5b-11e8-924d-1fd27eea45b3.png)
The same error appears when I try to create new machine after that deletion. 
There is a video: https://youtu.be/a-sH5UCFqXU

**Comment by eivantsov** [comment]
@Katka92 please check with the latest master. I see a slightly different behavior. In my case, machine isn't deleted:

![image](https://user-images.githubusercontent.com/5337267/42951035-f9e69cf8-8b7d-11e8-8170-1221c56dec15.png)

**Comment by Katka92** [comment]
This issue is not relevant to 7.1.0 as dashboard has changed and devfiles are used instead of stacks. Closing.
