### ISSUE TITLE
XSS attack

### ISSUE THREAD

**Issue by liubin10** [eclipse-che/che#10489]
### Description
Many [input] label do not avoid XSS attack.
For example,the Title and Host in Machine and VCS configuration,the name of Create New File or Create New Folder,the name of Command.

**Comment by eivantsov** [comment]
@liubin10 can you elaborate on how exactly do you see vulnerability and risks?

**Comment by liubin10** [comment]
I think when call InnerHtml(String param) method, it does not make sure that the param is safeHtml.

For example , set the command name <img src=1 onerror=alert('aaaaaaa')> and click Run, it will pop up the alert.

ConfirmDialogPresenter class is the case.
@eivantsov

**Comment by liubin10** [comment]
![1532594158465](https://user-images.githubusercontent.com/32632875/43251265-1220d2ba-90f2-11e8-8b7d-436292940322.png)

**Comment by liubin10** [comment]
@eivantsov
