### ISSUE TITLE
MAVEN_OPTS defined in a stack gets overriden by workspace

### ISSUE THREAD

**Issue by siamaksade** [eclipse-che/che#10495]
When defining the `MAVEN_OPTS` env var via the stack configuration, the workspace overrides the env var.

stack definition:
```
         ...
        "machines": {
          "dev-machine": {
            "env": {
              "MAVEN_OPTS" : "-Xmx512m"
            },
         ...
```

And in the workspace:
```
[user@workspacejegnbkonc07zrzqt projects]$ env | grep MAVEN_OPTS
MAVEN_OPTS=-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePoli
cyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
```

**Comment by eivantsov** [comment]
@siamaksade do you have this env in ~/.bashrc in a container?

**Comment by siamaksade** [comment]
To reproduce, create a new stack using this json https://hastebin.com/moyifanoji.json and then create a workspace based of this stack.

**Comment by siamaksade** [comment]
@eivantsov no, it's in the stack json https://hastebin.com/moyifanoji.json L15

**Comment by eivantsov** [comment]
@siamaksade ok, you did not want to check it, I did it for you.

In your ~/.bashrc, there's an interesting line:

```
[user@workspace2ijl3shz90dbzhsh projects]$ cat ~/.bashrc | grep MAVEN
export MAVEN_OPTS=$JAVA_OPTS
```
If you remove it, your `MAVEN_OPTS` will be what you expect:

```
[user@workspace2ijl3shz90dbzhsh projects]$ echo $MAVEN_OPTS
-Xmx512m
```
Does this answer your question?

**Comment by siamaksade** [comment]
My image just drives from `eclipse/centos_jdk8`, which I suppose is doing what you described:
https://github.com/siamaksade/che-jdk-recipes/blob/master/Dockerfile

Thanks for tracing this but this just tracks down the root cause of the reported issue to `eclipse/centos_jdk8` overriding defined `MAVEN_OPTS`.

**Comment by eivantsov** [comment]
@siamaksade yes, that line should be removed. I'll take care of it.

**Comment by siamaksade** [comment]
Created an issue on the che recipes repo:
https://github.com/eclipse/che-dockerfiles/issues/204

Closing this one.
