### ISSUE TITLE
can't connect to bitbucket with OAuth

### ISSUE THREAD

**Issue by itaimalek** [eclipse-che/che#1049]
Hi, I'm using `eclipse-che-4.2.0-RC1-SNAPSHOT` on a CentOS 7 machine, I've configured OAuth for my user in BitBucket and got key/secret pair as you can see here:
![image](https://cloud.githubusercontent.com/assets/8522568/14532339/654bc892-0269-11e6-84d4-1851da1771e4.png)

in my che.properties I've put this:

```
oauth.github.clientid=<Key from BitBucket>
oauth.github.clientsecret=<Secret from BitBucket>
oauth.github.authuri= https://bitbucket.org/site/oauth2/authorize
oauth.github.tokenuri= https://bitbucket.org/site/oauth2/access_token
oauth.github.redirecturis= http://<my external IP>/:${SERVER_PORT}/ide/api/oauth/callback
auth.oauth.access_denied_error_page=/error-oauth
```

When I try to import project from my bitbucket repo I get this:
`Remote repository requires authentication, but no OAuth provider found for this url`

Any idea what am I doing wrong?

**Comment by ghost** [comment]
You are using properties for GitHub. BitBucket oAuth plugin isn't part of Che while GitHub is - https://github.com/eclipse/che/tree/master/plugins/plugin-github

**Comment by itaimalek** [comment]
so, how can I pull from Bitbucket?
using SSH keys is supported with Bitbucket?

**Comment by itaimalek** [comment]
OK, I'm trying to work with the SSH keys method instead of oAuth with BitBucket,
the preferences wizard asks me for a Host Name - which hostname is this? my BitBucket? my container?

![image](https://cloud.githubusercontent.com/assets/8522568/14533199/cdb10246-026c-11e6-9765-b3f0114d50f7.png)

**Comment by ghost** [comment]
bitbucket.org

**Comment by itaimalek** [comment]
Thanks, that did it :)
