### ISSUE TITLE
Configuring max import size in workspace agent

### ISSUE THREAD

**Issue by i300543** [eclipse-che/che#10504]
### Description
It seems that POST: /api/project/import/{path}
does not allow me to import projects bigger than 1Mb (zipped)
i get 413 Request entity too large response.

Is there any way for me to configure this ? this limitation doesn't seem too logical.

### Reproduction Steps
deploy wsmaster on k8s from stable image version 6.7.1, create new workspace, import a new project with zipped size > 1Mb

**OS and version:**    
Linux version 4.14.48-coreos-r2
**Diagnostics:**

**Comment by eivantsov** [comment]
@vparfonov do you happen to know if such a limit exists?

**Comment by skabashnyuk** [comment]
@i300543 I guess you need to make sure your ingress controller has this fix https://github.com/kubernetes/ingress-nginx/pull/100

**Comment by eivantsov** [comment]
Closing as the fix is on K8S side.
