### ISSUE TITLE
Openshift 3.9 - Che 6.8.0 - Workspace restart failure 

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#10518]
### Description
I've deployed Che 6.8.0 on Openshift 3.9.
Creating of workspace, running projects is working as expected.
Once I stop a workspace & try to start the workspace again they take a very long time to launch (5 min) or start throwing the following error.

Failed to start Kubernetes runtime of workspace workspacemegaxsn9gtbo6r8x. Cause: Runtime start for identity 'workspace: workspacemegaxsn9gtbo6r8x, environment: default, ownerId: che' is interrupted

However, after stopping the workspace if I manually delete the workspace replica set using oc delete.
Workspace restart goes through fine, with workspace launch time being around 30 seconds.

### Reproduction Steps
- Deploy Che 6.8.0 on Openshift 3.9
- Launch Workspace 
- Stop the Workspace
- Re-start the workspace

**OS and version:**    
Openshift 3.9
Che 6.8.0

**Diagnostics:** 
Based on my analysis, I see the issue is triggered since the workspace replica set is not deleted on delete of workspace deployment, which is triggered on Stop/Deletion of workspace.

The issue described in seen 6.8.0 & not in previous che versions.
I believe this want introduced in the following PR https://github.com/eclipse/che/pull/10021

Solution could be to cascade deletion of workspace replica set on deletion of workspace deployment.

**Comment by garagatyi** [comment]
@hbhargav Thank you for the analysis! 
@amisevsk Please, take a look, this might be interesting for the issue you will work on in this sprint.

**Comment by eivantsov** [comment]
@hbhargav @garagatyi I failed to reproduce it with OpenShift 3.9 and Che 6.8.0

**Comment by hbhargav** [comment]
@eivantsov
I'm not sure if this issue is specific to openshift origin, coz its working fine on minishift.
Please find screenshots for reference.

**Initial launch of workspace**

<img width="1279" alt="screen shot 2018-07-24 at 1 57 33 pm" src="https://user-images.githubusercontent.com/12011767/43126158-91e60150-8f49-11e8-8afb-0c6c60957748.png">

<img width="1265" alt="screen shot 2018-07-24 at 1 58 44 pm" src="https://user-images.githubusercontent.com/12011767/43126619-cec1231a-8f4a-11e8-97da-2b5e745d6bb0.png">

<img width="1267" alt="screen shot 2018-07-24 at 1 59 30 pm" src="https://user-images.githubusercontent.com/12011767/43126303-f03135c2-8f49-11e8-8b1a-434e43ac0cb8.png">

**Che Server logs on Start**

2018-07-24 08:21:14,942[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 329]   - Starting workspace 'che/wksp-r2oc' with id 'workspacevx7k4qzrw3vea277' by user 'che'
  | 2018-07-24 08:21:32,135[equestProcessor]  [ERROR] [l.ErrorInstallerLogEventLogger 42]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspacevx7k4qzrw3vea277` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-07-24T08:21:32.132976588Z`
  | 2018-07-24 08:21:44,125[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 371]   - Workspace 'che:wksp-r2oc' with id 'workspacevx7k4qzrw3vea277' started by user 'che'

As you can see it takes 30 seconds to start the workspace.

**After stopping workspace**
<img width="1280" alt="screen shot 2018-07-24 at 2 01 13 pm" src="https://user-images.githubusercontent.com/12011767/43126339-10ca4efe-8f4a-11e8-880e-00f6ec4d3bca.png">

<img width="826" alt="screen shot 2018-07-24 at 2 02 07 pm" src="https://user-images.githubusercontent.com/12011767/43126406-3d45dd54-8f4a-11e8-8f2b-ea81ad8b4dfe.png">

**NOTE:** Replica Set doesn't get deleted

**On Restart of the same workspace**

<img width="1279" alt="screen shot 2018-07-24 at 2 04 02 pm" src="https://user-images.githubusercontent.com/12011767/43126489-7580945c-8f4a-11e8-9a02-62727c7b9f78.png">
<img width="1259" alt="screen shot 2018-07-24 at 2 04 24 pm" src="https://user-images.githubusercontent.com/12011767/43126529-95364468-8f4a-11e8-8d32-86592c1feb7e.png">
<img width="1256" alt="screen shot 2018-07-24 at 2 05 31 pm" src="https://user-images.githubusercontent.com/12011767/43126586-b7da055e-8f4a-11e8-91f6-728b33c24bee.png">

As you can see from the above screenshot 

NAME                                           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/workspacevx7k4qzrw3vea277.dockerimage   1         0         0            0           1m

NAME                                                 DESIRED   CURRENT   READY     AGE
rs/workspacevx7k4qzrw3vea277.dockerimage-774d8b6d4   1         1         1         4m

Deployment count is 0.

It's also strange to see that pod is absent for the workspace deployment in the openshift console, as it reports no deployments.
However, pod is up & running. 
po/workspacevx7k4qzrw3vea277.dockerimage-774d8b6d4-7z79v   1/1       Running   0          1m

**Che Server logs on Restart**

2018-07-24 08:33:39,282[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 329]   - Starting workspace 'che/wksp-r2oc' with id 'workspacevx7k4qzrw3vea277' by user 'che'
  | 2018-07-24 08:36:37,478[equestProcessor]  [ERROR] [l.ErrorInstallerLogEventLogger 42]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspacevx7k4qzrw3vea277` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-07-24T08:36:37.475071626Z`
  | 2018-07-24 08:36:49,532[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 371]   - Workspace 'che:wksp-r2oc' with id 'workspacevx7k4qzrw3vea277' started by user 'che'

It takes more than 3 mins to bring up the workspace, sometimes 5 mins or results in failure.

**Comment by eivantsov** [comment]
```
2018-07-24 08:36:49,532[aceSharedPool-0] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 371] - Workspace 'che:wksp-r2oc' with id 'workspacevx7k4qzrw3vea277' started by user 'che'
```

According to this log, the workspace has started. As to why it takes 3 mins - can you check events?

@amisevsk any idea on what might potentially go wrong when deployed is scaled to 0 and then back to 1?

**Comment by hbhargav** [comment]
@eivantsov  
As you rightly stated container is started almost immediately.  

<img width="1269" alt="screen shot 2018-07-24 at 6 11 16 pm" src="https://user-images.githubusercontent.com/12011767/43138757-887074c4-8f6d-11e8-9c69-c35cdfece7cd.png">

The issue that I'm focussing is on the contrary that though I don't see anything strange under workspace pod events & workspace pod is started, dashboard continues to report
"Waiting workspace machines to be booted... " for close to 5 mins.

Please see the che-server logs below from starting to started its takes 5 mins.

**Che Server logs on restart.**

2018-07-24 06:08:33,843[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 329]   - Starting workspace 'che/wksp-ymjm' with id 'workspacew35dfuw9lfbcagxj' by user 'che'
  | 2018-07-24 06:12:33,049[equestProcessor]  [ERROR] [l.ErrorInstallerLogEventLogger 42]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspacew35dfuw9lfbcagxj` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-07-24T12:42:33.046016562Z`
  | 2018-07-24 06:13:00,427[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 371]   - Workspace 'che:wksp-ymjm' with id 'workspacew35dfuw9lfbcagxj' started by user 'che'


Start of workspace at 06:08:33
Started workspace container at 06:08:39 (in 6 secs)
Che-Server reports workspace started at 06:13:00 (close to 4.5 mins)

I'm not sure whats happening between start of container started state to che server reporting workspace started.
I'm guessing, I was clear in my description of the issue this time.

**Comment by eivantsov** [comment]
@hbhargav 

> It takes more than 3 mins to bring up the workspace, sometimes 5 mins or results in failure

Since I cannot reproduce it on OSO and local Origin, I'd ask the following question:

* when the workspace is being loaded, do you see any progressor in the IDE? Like installers, machine status

> I'm not sure whats happening between container started state to che server reporting workspace started

The deployed is scaled to 1, and the server waits for a pod to get into a running state. Once in a running state, bootstrapping of a workspace start.

**Comment by hbhargav** [comment]
@eivantsov 
Nothing happens on the IDE expect stating "Waiting workspace machines to be booted..."

<img width="1275" alt="screen shot 2018-07-24 at 6 53 45 pm" src="https://user-images.githubusercontent.com/12011767/43141320-4510b116-8f73-11e8-9016-8ab74929a37a.png">
<img width="1272" alt="screen shot 2018-07-24 at 6 54 24 pm" src="https://user-images.githubusercontent.com/12011767/43141329-47c988ba-8f73-11e8-88e3-58a10afe3459.png">

Bootstrapping starts in the last few seconds.

**Comment by eivantsov** [comment]
OK. When the pod is running, can you run ps ax in it? Is bootstrapper running there?

**Comment by hbhargav** [comment]
@eivantsov 
I restarted the openshift cluster, issue seems to be resolved.
Now, replica set also gets deleted on issuing workspace STOP.
Workspace launch as expected on restart.

**Comment by amisevsk** [comment]
@hbhargav I can't seem to reproduce the `replicaSet` sticking around locally on minishift, but I will investigate this more. 

Regarding the failure to start, the 5 minute timeout and interrupted message is likely due to the workspace not coming to a working state within the ~5 minute timeout that Che allows. I've had this issue before if e.g. my internet connection is bad and the docker image is not downloaded quickly enough. As far as I know though, the `ReplicaSet` being scaled to 0 is intended Kubernetes behavior (although I can't find the issue at the moment) -- It is scaled to 0 and then cleaned up by the Kubernetes later. I'll look into this too.

@eivantsov It seems to me that (given the 5 minute timeout) there should be something preventing the workspace from starting fully, whether that is a ReplicaSet/Pod failing to start, or, as it seems in this case, the workspace within the (running) pod failing to report as running to Che. I know we're currently facing an issue around logs during workspace start, but we should still have access to logs after the Pod is up and running. If the Pod is coming into a running state, then I'm not sure what could be causing the issue, as once the Deployment is created there should be no difference to Che.

Regarding the deployment scaled to 0 and back to 1, that shouldn't be happening, as we delete deployments (and as far as I know the fabric8 client does cascading deletes implicitly). I'm not 100% on this so I will look into it more closely.
