### ISSUE TITLE
Is LSP4J 0.4.0 supported in eclipse che 6.6.0 

### ISSUE THREAD

**Issue by r-purva** [eclipse-che/che#10512]
### Description
 Hi,

Is lsp4j 0.4.0 supported in eclipse che 6.6.0 version?
As i was trying to get a callback for "didChangeWorkspaceFolders" for my lsp implementation.
But was not successful. 
Below is the code i added in LanguageServer initialization:
                `WorkspaceServerCapabilities wsCapabilities = new WorkspaceServerCapabilities();`
		`WorkspaceFoldersOptions wsFoldersOptions = new WorkspaceFoldersOptions();`
		`wsFoldersOptions.setSupported(Boolean.TRUE);`
		`wsFoldersOptions.setChangeNotifications(Boolean.TRUE);`
		`wsCapabilities.setWorkspaceFolders(wsFoldersOptions);`
		`capabilities.setWorkspace(wsCapabilities);`

If not supported, when is the plan to support lsp4j 0.4.0?
Or am i missing some part while implementation?

And is there any other way to get callbacks for folder deletion/creation and file creation/deletions in 0.3.0 lsp4j? 

Regards,
Purva

**Comment by r-purva** [comment]
Thanks 
And is there any other way to get callbacks for folder deletion/creation and file creation/deletions in 0.3.0 lsp4j?

**Comment by AndrienkoAleksandr** [comment]
@vparfonov @dkuleshov Could you share plans about lsp4j and help?
P.S. Seems CQ for lsp4j 0.4 is already exist and it was approved https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16100

**Comment by dkuleshov** [comment]
@r-purva Hi, as I know the 0.4.0 version is planned for jdt.ls branch which should be merged into master in the closest future.

**Comment by r-purva** [comment]
can anyone help me how to get callback for file creation /deletion in lsp 0.3 from eclipse che?
Or how do we get callback from eclipse che to lsp "didChangeWatchedFiles" for workspace service?

**Comment by dkuleshov** [comment]
Did you try to use `org.eclipse.che.api.languageserver.LanguageServerFileWatcher`?

**Comment by r-purva** [comment]
No, We have extended `org.eclipse.che.api.languageserver.LanguageServerConfig` class and added below code:
This is in lang-server plugin.
 
```
 @Override
  public RegexProvider getRegexpProvider() {
    return new RegexProvider() {
      @Override
      public Map<String, String> getLanguageRegexes() {
        return ImmutableMap.of(Module.LANGUAGE_ID, REGEX);
      }

      @Override
      public Set<String> getFileWatchPatterns() {
        return ImmutableSet.of();
      }
    };
  }
```
  And regex has file type extension ,we are able to start language server on file type creation.
But didn't get call back for method didChangeWatchedFiles.
  Is there anything else needs to be done to get a callback in lsp4j for didChangeWatchedFiles ?

**Comment by dkuleshov** [comment]
Then I think you can try `org.eclipse.che.api.languageserver.LanguageServerFileWatcher`.

**Comment by r-purva** [comment]
Thanks. Is there any document for LanguageServerFileWatcher?

**Comment by es13b1018** [comment]
@r-purva, getFileWatchPatterns() is returning an empty Set. You can give your file pattern to watch:

```
 @Override
  public Set<String> getFileWatchPatterns() {
        return ImmutableSet.of("regex:" + REGEX);
  }
```
You will get call backs for those file in your LSP at `org.eclipse.lsp4j.services.WorkspaceService#didChangeWatchedFiles(org.eclipse.lsp4j.DidChangeWatchedFilesParams)`

**Comment by r-purva** [comment]
Thanks. it worked 👍
