### ISSUE TITLE
Dependencies between modules aren't resolved in multi-module maven project

### ISSUE THREAD

**Issue by gorbunkov** [eclipse-che/che#1051]
As I see now, in case of multi-module maven project Che doesn't see a dependencies to other modules until I install them to the local maven repo. Is this correct? And if it is so, do you plan to implement a kind of 'source-based' dependencies resolving?
I use Che 4.1.0.

**Comment by TylerJewell** [comment]
@evidolib: is this part of the new maven plugin that is coming in 4.3?  I believe this and the standard Java project type is what he is referencing.

**Comment by evidolob** [comment]
Yes it is. This functionality will be available in 4.3 with new maven plugin.

**Comment by gorbunkov** [comment]
When do you plan to release 4.3?

**Comment by TylerJewell** [comment]
4.1 is getting released this week.  It's been in QA for about a week.  We will do a 4.2 release by the end of next week which introduces a number of improvements related to SSH and remote systems management.  4.3 work will begin after that.  We have a number of major sub-systems to integrate and stabilize as there are multiple major new features getting introduced.  There is no way to determine how long the integration cycle will take.  This new maven plugin, for example, has been in development for about 4 months.

**Comment by ghost** [comment]
I'm closing it now. Feel free to reopen after Maven plugin is shipped and you face issues with it.
