### ISSUE TITLE
Cannot Start Che-in-Che Workspace

### ISSUE THREAD

**Issue by Jimmyscene** [eclipse-che/che#10519]
Hey guys, I'm following this tutorial `https://www.eclipse.org/che/docs/che-in-che-quickstart.html` and upon clicking the preview url for both Deploy IDE and Deploy Workspace Agent, I am greeted with the error attached. 

It's pretty hard to reach so to transcript it: 

IDE initialization failed: Cannot read property 'DA' of undefined

I'm running the latest tag of eclipse/che in kubernetes. 

Looking at the network requests, it seems to me it may be an issue with Keycloak, as it's getting a 502 back for the /api/keycloak/settings endpoint. 

Any help would be greatly appreciated!

![image](https://user-images.githubusercontent.com/6708446/43104043-0a04f670-8e9e-11e8-8715-c60445827eba.png)

**Comment by eivantsov** [comment]
@Jimmyscene are there any errors in logs you see in command output?

**Comment by Jimmyscene** [comment]
Hi @eivantsov - sorry for the delayed reply. I'm getting " Runtime exception caught in thread LuceneSearcherInitThread. Message: Java heap space
java.lang.OutOfMemoryError: Java heap space" in the IDE Start commands window. 

Is this normal, or do you guys recommend increasing the heap space?

**Comment by eivantsov** [comment]
@Jimmyscene how much RAM do you have? Do you use Docker or OpenShift/K8S infra?

**Comment by Jimmyscene** [comment]
@eivantsov I'm using K8s and I allocated 8 gigs to the workspace, but the actual cluster has 75 gigs

**Comment by Jimmyscene** [comment]
@eivantsov Hey, sorry for the slow response, I restarted my workspace to attempt a clean fix of that and now I'm getting 502 errors from Tomcat(Bad Gateway), no matter what i do. Any idea how I can resolve this? I'm getting no errors in the tomcat window, but the Traefik command is spitting out: 
```
time="2018-07-25T19:16:38Z" level=warning msg="Error forwarding to http://localhost:8080, err: dial tcp 127.0.0.1:8080: getsockopt: connection refused" 
time="2018-07-25T19:16:45Z" level=warning msg="Error forwarding to http://localhost:8080, err: dial tcp 127.0.0.1:8080: getsockopt: connection refused" 
time="2018-07-25T19:16:45Z" level=warning ms
```

**Comment by Jimmyscene** [comment]
So that error went away but I'm getting the same "Cannot read proprety DA of undefined message",

the traefik command console is logging out
```
time="2018-07-25T21:37:29Z" level=debug msg="Round trip: http://localhost:8080, code: 200, duration: 330.581039ms" 
time="2018-07-25T21:37:30Z" level=warning msg="Error forwarding to http://che-host:8080, err: dial tcp: lookup che-host on 10.96.0.10:53: no such host" 
time="2018-07-25T21:37:30Z" level=debug msg="Round trip: http://localhost:8080, code: 200, duration: 3.80224ms" 
time="2018-07-25T21:37:30Z" level=warning msg="Error forwarding to http://che-host:8080, err: dial tcp: lookup che-host on 10.96.0.10:53: no such host" 
time="2018-07-25T21:37:30Z" level=warning msg="Error forwarding to http://che-host:8080, err: dial tcp: lookup che-host on 10.96.0.10:53: no such host" 
```

I've updated the traefik.toml to point at 
che-eclipse-che.$IP.nip.io(which is where I access che) instead of http://che-host and this stops the "error forwarding to" messages, but causes these in the traefik console
```
level=debug msg="Round trip: http://che-eclipse-che.$IP.nip.io, code: 502, duration: 235.590233ms"
```
and results in the same "Cannot read property 'DA' of undefined" message in the UI

**Comment by eivantsov** [comment]
@Jimmyscene can you run `ping che-host` in the workspace container? It looks like this hostname cannot be resolved in your K8S cluster

**Comment by Jimmyscene** [comment]
@eivantsov I cannot, i get `ping: che-host: Name or service not known`

**Comment by Jimmyscene** [comment]
I believe this is due to the fact that the workspaces are not in the same k8s namespace

**Comment by jdflemin** [comment]
Was going through the same tutorial and was getting the same error upon clicking the preview url. I then ran `ping che-host` and got the same response of `ping: che-host: Name or service not known`.

Has there been any resolution to this or work around found at this time?

**Comment by eivantsov** [comment]
@Jimmyscene you need to reconfigure Che to create all workspaces in one namespace. In Che config map, make sure CHE_INFRA_KUBERNETES_PROJECT is your Che namespaces.

Closing the issue, feel free to reopen if it does not solve the problem
