### ISSUE TITLE
Jwt-proxy is displayed as machine on IDE UI

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10521]
### Description
In this PR (#10463) @mshaposhnik add a "jwt-proxy" functionality. 
The problem is the "jwt-proxy" displays as the machine in the workspace. It leads to regression (almost 20 %) in the tests which oriented to the using of the workspace with a single machine and unexpected machine selection dialog causes the fails:

![fffff](https://user-images.githubusercontent.com/22724619/43130117-98ac4ec8-8f3e-11e8-888a-2297be78cc75.png)

Besides it looks veard for user which expects single machine in his workspace. And as @sleshchenko wrote in the ##10463 the "jwt-proxy" doesn't have terminal, or exec-agent servers. @vparfonov could you clarify this issue?

**Test report with reproduced bug:**
https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/505/Selenium_20tests_20report/

**Comment by eivantsov** [comment]
We should probably mark/tag such machines somehow, so that clients can filter machines accordingly.

**Comment by skabashnyuk** [comment]
I don't think this is a bug either

**Comment by skabashnyuk** [comment]
>@skabashnyuk Could you elaborate why do you think so? How is it possible to execute a command in a machine where exec server is not present?

We will figure out that with Theia based ide. 
My point: we should not spend much time with new components with GWT based IDE.

**Comment by sleshchenko** [comment]
@skabashnyuk 
> we should not spend much time with new components with GWT based IDE.

Good point. I don't think that it changes the kind of issue but I agree with you about it.
I don't think that it requires a lot of time to fix this issue.

BTW It is not a critical issue since `jwtproxy` is disabled by default but it would be fixed before enabling jwtproxy by default.

**Comment by skabashnyuk** [comment]
Ok. let's reformulate issue. Do not show machine without exec agent for the command execution target. WDYT?

**Comment by sleshchenko** [comment]
There is an issue for marking tooling machines with a special attribute https://github.com/eclipse/che/issues/11804
