### ISSUE TITLE
[Python language server] The Refactor -> Rename feature does not work if py file not formatted properly 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10523]
**Reproduction Steps:**
1. Create and start workspace from **Python** stack with **console-python3-simple** project.
2. Open "main.py" file from the project and add text to it(without  blank line in the end of file)
```python
def add(a, b):
    return a + b
```
3. Click on any variable and select **Refactoring**->**Rename**(Shift+F6) feature from context menu.
4. Change name of the variable and press **ENTER**.

**Expected behavior:** 
The variable name changed
 
**Observed behavior:**
The variable was not changed.
There is "**org.eclipse.che.plugin.languageserver.ide.rename.RenamePresenter
SEVERE: Cannot read property 'start' of undefined**" error message in browser console.
The **Rename** feature will work correctly if add a blank line to the end of file or format this file by **Format** feature.
 
**Che version**: 6.9.0
**OS and version:** Fedora 28
**Che install:** OCP-single

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshots:**
![selection_049](https://user-images.githubusercontent.com/7760565/43135632-b9f6078a-8f4e-11e8-9ab4-365e7bf2b26f.png)

![selection_131](https://user-images.githubusercontent.com/7760565/45614981-e3c2cd00-ba73-11e8-98f1-093309c8a1b2.png)

**Comment by tsmaeder** [comment]
Does this work for other language servers (not Java, because that does not use the same code)

**Comment by SkorikSergey** [comment]
This works on **Clang** and **TypeScript** language servers. 
Not works **Golang** language server - https://github.com/eclipse/che/issues/10524.

**Comment by SkorikSergey** [comment]
Not reproduced in CHE-6.14.0 SNAPSHOT.
