### ISSUE TITLE
create workspce fail with Permission denied

### ISSUE THREAD

**Issue by zeyuanpinghe** [eclipse-che/che#10530]
I had deploy openshift3.9 cluster on my computer (master node:1,slave node:2)

oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

I tried to deply a example which name is cakephp-ex on this cluster ,and it worked fine.

I tring  to deploy eclipse che on this cluster.
steps are as fllows.

oc create serviceaccount che -n che2
oc adm policy add-scc-to-user anyuid system:serviceaccount:che2:che
oc adm policy add-scc-to-user privileged system:serviceaccount:che2:che
oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:che2:che
oc adm policy add-scc-to-group anyuid system:authenticated

oc DEPLOY_ROOT_URL=https://raw.githubusercontent.com/eclipse/che/master/deploy/openshift/templates
curl -fsSL ${DEPLOY_ROOT_URL}/che-server-template.yaml -o che-server-template.yaml
curl -fsSL ${DEPLOY_ROOT_URL}/pvc/che-server-pvc.yaml -o che-server-pvc.yaml
oc create new-project che2
oc new-app -f che-server-template.yaml -p ROUTING_SUFFIX=master.10.121.198.81.nip.io
oc apply -f pvc/che-server-pvc.yaml
oc set volume dc/che --add -m /data --name=che-data-volume --claim-name=che-data-volume
I tring to add parameter "privileged" in che yaml file.like this :
securityContext:
  privileged: true
  allowPrivilegeEscalation: true

Then eclipse che can show on the browse.
There was an error when I tried to create a workspace on eclipse che.
error message is shown below:
Loading...
mkdir -p /tmp/bootstrapper/ /workspace_logs/bootstrapper
mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1
Bootstrapping of machine dev-machine failed. Cause: mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1

sameone can resove this issue?

**Comment by kingkeivn** [comment]
logs in che  pod :
Machine `dev-machine` error from owner=`che` env=`default` workspace=`workspacejxtcmersa5p69t8g` text=`mkdir: cannot create directory ‘/workspace_logs/bootstrapper’: Permission denied

**Comment by eivantsov** [comment]
@kingkeivn something is wrong with your PVC - an arbitrary user in the container cannot create a directory for logs

**Comment by kingkeivn** [comment]
@eivantsov I  can not devide this user. 
How can i specify a user with pvc?

**Comment by kingkeivn** [comment]
this is pvc's yaml:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2018-07-25T09:16:48Z
  labels:
    che.workspace.volume_name: projects
    che.workspace_id: workspaces8nz1anpko35tdj2
  name: claim-che-workspace-wpmbw7xx
  namespace: che2
  resourceVersion: "1441761"
  selfLink: /api/v1/namespaces/che2/persistentvolumeclaims/claim-che-workspace-wpmbw7xx
  uid: 75483633-8feb-11e8-967c-0cda411da757
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv0005
status:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 3Gi
  phase: Bound

**Comment by kingkeivn** [comment]
this pvc provider with eclipse che .
And I create the pv:
pv yaml :
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2018-07-25T09:17:45Z
  labels:
    volume: pv0005
  name: pv0005
  resourceVersion: "1441759"
  selfLink: /api/v1/persistentvolumes/pv0005
  uid: 9794ef50-8feb-11e8-967c-0cda411da757
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 3Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: claim-che-workspace-wpmbw7xx
    namespace: che2
    resourceVersion: "1441575"
    uid: 75483633-8feb-11e8-967c-0cda411da757
  hostPath:
    path: /opt/data
    type: ""
  persistentVolumeReclaimPolicy: Recycle
status:
  phase: Bound

**Comment by eivantsov** [comment]
@kingkeivn you need to investigate why your PV is not writable.

**Comment by kingkeivn** [comment]
how can i check pv writable?

**Comment by eivantsov** [comment]
@kingkeivn maybe you have hit a bad pv.

I'd delete Che namespace and redeploy.

**Comment by kingkeivn** [comment]
@eivantsov 
Thank you .
 I had delete che  namespce and redeploy it for twice. but it can not work fine .
I tryed deploy che-postgres .and it can mkdir file on pv.
I feel the error is images built it with a default user which can not mikdir file on pv .

**Comment by eivantsov** [comment]
@kingkeivn it is not. The arbitrary user is an OpenShift thing. It makes sense asking a question in at https://github.com/openshift/origin/issues

**Comment by kingkeivn** [comment]
@eclipsewebmaster  ok

**Comment by kingkeivn** [comment]
@eivantsov I resolve it
