### ISSUE TITLE
Read workspace permission allows to use/delete projects as well

### ISSUE THREAD

**Issue by es13b1018** [eclipse-che/che#10536]
Hi,

I am using Che 6.6.0 in multi-user mode on docker. 

When I give workspace permission as "read" to a user, he can't edit the workspace configurations but he is able to delete projects from the editor. Is this a bug?
If a user can edit and use the projects inside that workspace with just "read" workspace permissions then what is the significance of having "use" permission?

**Comment by eivantsov** [comment]
@es13b1018 it's not a bug. When sharing a workspace, you also share source code, and any information that your workspace container may contain.

**Comment by es13b1018** [comment]
Thanks, @eivantsov. 

Then what is the significance of "use" permission if a user can edit and use the projects inside a workspace with just "read" workspace permissions?

Also, is there a way to restrict a user from deleting the source code (projects and files)? 

With just "read" permission a user is not able to delete a project from Workspaces -> my workspace -> Projects but is able to delete from the _Project Explorer_. I doubt either of this should be correct and the other might be a bug.

**Comment by eivantsov** [comment]
@es13b1018 this is how things work at the moment - permissions are applied to objects like workspaces, stacks, users etc

**Comment by sleshchenko** [comment]
@eivantsov I think it is a bug. And it happens because WorkspaceService component doesn't check if a user has `use` permission or not before machine token generation. Also, I think runtime should not be exposed at all if a user doesn't have `use` permissions.
@es13b1018 Thanks for reporting such a bug.

**Comment by es13b1018** [comment]
Thanks @sleshchenko.
