### ISSUE TITLE
Bootstrapping does not work with images not containing curl

### ISSUE THREAD

**Issue by toorog** [eclipse-che/che#10537]
Bootstrapper cannot be downloaded if the machine's image has no curl installed and

- distribution is not listed in `org.eclipse.che.exec.script.sh` or
- distro is not recognized for any reason (e.g. missing distribution descriptor in /etc) or
- distro is recognized, but the package manager can for some reason not download any additional packages (e.g. firewall or a pure local setup without any internet connection at all)

A more versatile approach would be to put the bootstrapper script inside a configmap (K8s) or a shared volume (docker-compose), and mount that one inside the workspace pod / container. This strategy would remove the limitation of "well known distributions" being mandatory.

### Reproduction Steps
1. Configure a stack with a machine based on `busybox` image
2. Start a workspace based on that stack

**OS and version:**    
Che 6.7.0 on Kubernetes

**Comment by eivantsov** [comment]
@toorog this is expected behavior and known limitation. Missing curl isn't the only problem - there are others, like permissions for home directory etc.

This problem's gone with workspace.next implementation.
