### ISSUE TITLE
Is there a UI provided to configure permissions in Che (6.6.0) running in multi-user mode on docker?

### ISSUE THREAD

**Issue by es13b1018** [eclipse-che/che#10535]
Hi,

I have a query regarding permissions in Che (6.6.0) running in multi-user mode on docker. 

Is there a user interface to configure permissions in Che? Using swagger APIs one can do that, but still wondering if there is any plan to have a UI to configure permissions, for the ease of users?

**Comment by eivantsov** [comment]
@es13b1018 you can share a workspace in user dashboard > workspace view > Share.

**Comment by es13b1018** [comment]
@eivantsov thanks for the answer. But still I can't change permissions from dashboard > workspace view > Share? 
Is there any UI for doing that or any further plan to include changing permissions in this view itself?

**Comment by eivantsov** [comment]
@es13b1018 there's no admin UI in User Dashboard, unfortunately

**Comment by es13b1018** [comment]
Thanks, @eivantsov. 

Can this be something included in Che roadmap? I suppose this should not a very big work. I have seen that view already contains Permissions as one of its columns. A user should just be able to edit it and the rest services can be used to change the permissions.

**Comment by eivantsov** [comment]
There are no immediate plans. Closing the issue. It may be reopened in future.
