### ISSUE TITLE
How to make a custom stack as default?

### ISSUE THREAD

**Issue by es13b1018** [eclipse-che/che#10539]
Hi,

I am running Che 6.6.0 with a local repo mounted. I have my custom stack defined in stacks.json file inside che-core-ide-stacks module.

Is there a way to make my stack as default, so that while adding a new workspace my custom stack shows up on the top and is selected by default?

I tried changing product.json file inside dashboard module but without any luck.

**Comment by AndrienkoAleksandr** [comment]
@es13b1018 you need set up general scope for your stack. Example:
https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L7
On the UI:
1. On the user dashboard select "Stacks".
![selectstack](https://user-images.githubusercontent.com/6873095/43207469-d6aa70a4-9030-11e8-97c4-765444782864.png)

2. Find your stack.
![selectyourstack](https://user-images.githubusercontent.com/6873095/43207489-df644ce2-9030-11e8-899b-4be4227a3240.png)

3. Click on the your stack.

4. Select Category "Ready to Go".
![selectreadytogocategory](https://user-images.githubusercontent.com/6873095/43207550-f35c69a0-9030-11e8-8307-59a832350f8d.png)

5. Click Save button.
![save](https://user-images.githubusercontent.com/6873095/43207569-fb8001fa-9030-11e8-8a27-131d073bd576.png)

**Comment by AndrienkoAleksandr** [comment]
I guess external stacks.json should not work. Seems this functionality was reworked to use stacks.json from jar, and it should not work for external file... And this functionality is deprecated.

**Comment by es13b1018** [comment]
Thanks, @AndrienkoAleksandr. 

What you mentioned is already in place. My stack is shown in the _Quick Start_ list. But I want my stack to be selected by default in that list instead of _Java-MySQL_.

This is default:
![stack_java_mysql](https://user-images.githubusercontent.com/28301279/43246124-45997e04-90ce-11e8-8ee3-0334ab492191.JPG)

I want something like this as default behaviour on clicking on _Add Workspace_:
![stack_custom](https://user-images.githubusercontent.com/28301279/43246160-60b3bfec-90ce-11e8-8158-19d48c1c33d1.JPG)

Inside _product.json_ file inside _dashboard_ module, i can see:
```
"workspace": {
    "priorityStacks": ["Java", "Java-MySQL", "Blank"],
    "defaultStack": "java-mysql"
  },
```
Also, inside the same module inside _che-branding.factory.ts_ there are these options:
`const DEFAULT_WORKSPACE_PRIORITY_STACKS = ['Java', 'Java-MySQL', 'Blank'];
const DEFAULT_WORKSPACE_DEFAULT_STACK = 'java-mysql';`

Is there any such place where I can configure to make my custom stack default?

**Comment by ruzalsh** [comment]
is there any documentation for Customizing plugin/Extension   and assembly **as above ?** (Step by Step)

**Comment by ruzalsh** [comment]
@AndrienkoAleksandr  Thank you . where can i find product.json file ?

**Comment by AndrienkoAleksandr** [comment]
https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/product.json

**Comment by eivantsov** [comment]
Ordering defined in product.json should work.

**Comment by es13b1018** [comment]
Thanks for the comments.

Changing in _product.json_ works. I was unable to see changes because of some caching issue in Firefox browser.
