### ISSUE TITLE
Create Project Make XSS attack ~~~

### ISSUE THREAD

**Issue by yinpeng0007** [eclipse-che/che#10549]
Create Project will make XSS attack  when I use a special name.

![default](https://user-images.githubusercontent.com/39823740/43253191-f411b7d0-90f6-11e8-86a3-4191db2d18e4.png)

**Comment by vzhukovskii** [comment]
Fixed with https://github.com/eclipse/che/commit/cad8575f40a8d6ef5e2a279b6d3d8e42a5468f73
