### ISSUE TITLE
Unexpected the 'java.lang.OutOfMemoryError' in ws-agent after import Eclipse Che

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#10543]
### Description

**Reproduction Steps:**
* Create the workspace from the _Eclipse Che_ stack on the dashboard
* Open the IDE, import the _eclipse-che_ project (https://github.com/eclipse/che.git)
* Select the _Maven_ type and click on the _Save_ button on the _Project Configuration_ form
* Wait while the dependencies are resolved
* Open in the editor a several file (e.g. there were opened three file: java file, ts file and pom.xml)
* Do some actions in the editor and refresh page

**Expected behavior:** 
* the _OutOfMemoryError_ should not be in ws-agent log
 
**Observed behavior:**
* there is the _java.lang.OutOfMemoryError: Java heap space_ in ws-agent log
 
**Che version**: 6.9.0
**OS and version:** Fedora 28
**Che install:** OCP-multiuser
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Related known issue: #9477
* Related selenium tests: _ImportAndValidateEclipseCheProjectTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**screenshot:**

![out-memory-eclipse-che](https://user-images.githubusercontent.com/5408906/43210313-687cf8c0-9037-11e8-89d3-698807d64b59.png)

![java-heap-space](https://user-images.githubusercontent.com/5408906/43212367-767535c8-903c-11e8-8671-1da023fce07d.png)

**ws-agent-log:**

[eclipseWS-ws-agent-2018-07-25.log](https://github.com/eclipse/che/files/2228487/eclipseWS-ws-agent-2018-07-25.log)

**Comment by eivantsov** [comment]
@artaleks9 what are `MAVEN_OPTS` and `JAVA_OPTS` in a workspace?

**Comment by artaleks9** [comment]
@eivantsov 
[user@workspace98p7qo45friyro8l /]$ echo $MAVEN_OPTS
-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=t
rue -Xms20m -Djava.security.egd=file:/dev/./urandom

**Comment by HouzuoGuo** [comment]
I experienced a very similar issue with Go machine image together with its language server.

In a Java CentOS-based workspace, both the JAVA_OPTS and MAVEN_OPTS of terminal environment are:

`-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m`

However, in a Go-based workspace:

<pre>
JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m
MAVEN_OPTS=-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
</pre>

The ws-agent process appears to be using MAVEN_OPTS. In an attempt to work around the issue, I manually added the following environment variables into the workspace settings:

<pre>
"CHE_WORKSPACE_MAVEN__SERVER__JAVA__OPTIONS": "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=4096m -Xms256m -Xmx3072m",
"CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS": "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=4096m -Xms256m -Xmx3072m"
</pre>

Apparently that helped a lot and the workspace no longer runs into out-of-memory errors.

Be aware that, similar environment variables that restrict memory usage to 1200MB like the Java CentOS workspace still results in out-of-memory errors. Apparently 1.2GB is not enough for the Go workspace.

**Comment by vinokurig** [comment]
Proposed a solution, but it has a little side effect. See the PR above.

**Comment by vinokurig** [comment]
Should be fixed by https://github.com/eclipse/che/issues/10696

**Comment by skabashnyuk** [comment]
We can increase CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS for che-in-che stack

**Comment by musienko-maxim** [comment]
So, i applied next configuration: to the CHE stack like:
```
  "env": {
            "CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS": "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms50m -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom"
          },
```
end this one fix the problem, but during Dog Fooding session i got the similar problem for the Maven plugin. I'll try to increase heap space for maven plugin in the next test session and check this.

**Comment by skabashnyuk** [comment]
try
 
"CHE_WORKSPACE_MAVEN__SERVER__JAVA__OPTIONS": "-XX:MaxRAMFraction=4 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms50m -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom"

**Comment by vinokurig** [comment]
Optimization of `GitStatusProvider` (https://github.com/eclipse/che/pull/10690) reduces Git status calls on expanding project. This should minimize the risk of OOM because Git Status is called not more than 1 time during the project expand.
