### ISSUE TITLE
Deleting a not supported workspace breaks dashboard in OpenShift

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#10544]
### Description
If you create a workspace that is not supported in a particular spin of Che and then delete it, the workspaces tab fails to populate with error `Failed to retrieve workspace wksp-o078 data. Reason: Workspace with id 'workspacenn25oh2umzhkbgt9' doesn't exist` until the page is refreshed. On the dashboard tab the deleted workspace is still listed.

### Reproduction Steps
1. Deploy current snapshot of Che on minishift
2. Create Java-MySQL workspace, choose "Edit" option (or click top "Create" button)
3. See that this workspace stack is not supported, delete workspace
4. Che redirects to workspaces tab, which fails to load any workspaces. 
5. Dashboard tab still lists deleted workspace

**OS and version:**    
```
Che 6.9.0-SNAPSHOT (current master branch)
minishift v1.21.0+a8c8b37
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.148:8443
openshift v3.9.0+46ff3a0-18
kubernetes v1.9.1+a0ce1bc657
```

**Comment by garagatyi** [comment]
@ashumilova FYI

**Comment by garagatyi** [comment]
This issue is probably caused by this [PR](https://github.com/eclipse/che/pull/10385) which removes validation of workspace environment on workspace creation and leave it only on workspace start.
