### ISSUE TITLE
Make workspace-loader (or UD) show an error received from websocket on workspace start failure

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10540]
### Description
When workspace start fails after some time workspace-loader and UD receive the message with the error, but provide UX that might be not clear to some users:
- There is a red circle near the workspace name
- There is no error shown
- The workspace loading progress bar doesn't disappear that might make a user think that workspace is still starting  

Instead of that, it would be nice to:
- stop showing the progress bar
- show a popup with the error message and a button to restart the workspace (the same as reloading the page) 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@slemeur @ashumilova I decided to label this issue as a bug since it is about confusing UX when a user might not understand that workspace start failed and nothing will happen.
But feel free to relabel it as a task if you think otherwise.

**Comment by slemeur** [comment]
ok thanks @garagatyi
