### ISSUE TITLE
How to hide the token in URL?

### ISSUE THREAD

**Issue by paraseleneelf** [eclipse-che/che#10551]
Whether there is a security problem in URL containing token?Is it possible to put token in header?
these API:
    1./export   download project
    2./pty
    3./connect
    4./wsagent
![1532598843438](https://user-images.githubusercontent.com/20433295/43255696-2bd1e702-90fd-11e8-90e2-ff9d190bada2.JPG)
![1532598843935](https://user-images.githubusercontent.com/20433295/43255701-2d9030f8-90fd-11e8-9897-814a5cfee3e0.JPG)

**Comment by vparfonov** [comment]
There is no way put token in header in request what you mention.

- ` /pty`, `/connect`, `/wsagent` - are WebSocket connections 
- `/export` (download project) - this action create hidden frame element with source located to the zip archive
