### ISSUE TITLE
Update fmt plugin to latest to enable skipping check

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10554]
We have build modes that allow us to build che faster locally by skipping execution of maven plugins, for examply by skipping tests or version checks.
However, the version of the maven:fmt plugin we use (2.0.0) does not allow skipping execution (-Dfmt.skip). We should update to enable this.

**Comment by garagatyi** [comment]
I think that adding `-Dskip-validate-sources` should do the trick. But it is not that fine-grained if you want to skip formatting, but not other checks, so +1 to upgrade.
