### ISSUE TITLE
Pycodestyle not respecting project level configuration (setup.cfg)

### ISSUE THREAD

**Issue by andrewsosa** [eclipse-che/che#10563]
### Description
The default Python 3.5.1 stack which comes with Che has pycodestyle pre-installed. Normally, pycodestyle can be configured with a `setup.cfg` file in a project's root. 

The problem is twofold: 

1. Che/pycodestyle does not detect `/projects/<my_project>/setup.cfg`. 
2. Che/pycodestyle _does_ find and use `/projects/setup.cfg`. However, now the single `setup.cfg` file is detected as a folder by Che and is no longer editable, nor is stored in the Git repo. 

Not only is this undesirable behavior for linting on a project-by-project basis, but this also shows a single file as a folder which is a bug on it's own. 

*I believe this is an issue with Che and not Pycodestyle*, because due to the way these stacks are setup, Pycodestyle is "tricked" into believing `/projects` is the project root instead of `/projects/<actual_proj_root>`. 

### Reproduction Steps
1. Create a workspace from the default Python 3.5.1 stack.
2. Create the sample "hello world" project
3. Create a `setup.cfg` file in `/projects/<your_project>`
4. Make the following modifications to your files:

**In main.py**
```python
x = ['hello','world']  # note there is no space after the ','
```
**In setup.cfg**
```
[pycodestyle]
ignore = E231
```

You should now see the linting error as seen:
![pycodestyle](https://user-images.githubusercontent.com/2829058/43320962-690785b6-9178-11e8-8015-06ecd8c0b1bd.PNG)

If you then `cp setup.cfg ..` from within your project so it's full path is now `/projects/setup.cfg`, your linting error will go away, but `setup.cfg` will now be detected as a project of it's own, seen here:

![lint2](https://user-images.githubusercontent.com/2829058/43321056-bbf78708-9178-11e8-9e3e-ff1bc675c1dd.PNG)

**OS and version:**    
This is within the "ubuntu_python" Docker image for the default Python 3.5.1 stack in Eclipse Che. 
The machine host is RHEL 7. 

**Diagnostics:** 
n/a

**Comment by eivantsov** [comment]
@andrewsosa the fact that a file is being treated as a folder is a bug. 

As to the linting file being picked up from the root of a workspace, rather than a project's root, I think it makes sense to ask https://github.com/palantir/python-language-server which is used in Che Python stack as Che solely relies on the language server to provide language support.

**Comment by andrewsosa** [comment]
@eivantsov For the file being treated as a folder, I don't see an open issue labeled as a bug, would you like me to open a new issue, or maybe edit this issue to highlight that part? Alternatively close if there's an existing issue for it. 

Regarding the config itself, I'll go ask the palantir folks.

**Comment by eivantsov** [comment]
Fixed by https://github.com/eclipse/che/pull/9522
