### ISSUE TITLE
Running Eclipse Che in private VPC

### ISSUE THREAD

**Issue by vincentarthur** [eclipse-che/che#10566]
Hi all,

I am now running into an issue which is quite frustrating. 

In a VPC on GCP, i've created a public subnet and a private subnet which is to simulate to network of my company. 

I am trying to deploy Eclipse Che with using Docker to _**GCE instances inside the private subnet**_ (no public IP). And only one GCE instance inside the public subnet can access the machines in private subnet as a bastion.  I can successfully run up Eclipse Che with "offline" mode on private instance and setup SSH tunnel from bastion host to the private instance (8080/5050).

Now comes the problem, when i am accessing the bastion ip with 8080 to access the Eclipse Che Dashboard, i am unable to correctly open it (it keeps showing the loading page).

![image](https://user-images.githubusercontent.com/4783098/43354827-7073c766-9285-11e8-92f3-8c3bc0792f58.png)

I am using below command to run Eclipse Che.
`
sudo docker run -it   -e CHE_HOST=<internal ip of private instance> -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start --offline
`

And i notice that, on the dashboard, it's requesting the "keycloak.js" with using my internal IP of private instance which is impossible to be accessed directly through UI.

May i know if anyone can share the solution if met before ? Thanks a lot.

Hi @eivantsov Could you please help ? thanks a lot.

**Comment by eivantsov** [comment]
@vincentarthur your `CHE_HOST` must be available for clients (your browser).

**Comment by vincentarthur** [comment]
Hi @eivantsov , Thanks for your response. Sounds like, Che will only be available in either public or private network, but not available for my current network design ? (SSH Tunnel + Bastion Host + Private Instances) 

If i must have this type of network design, may i know how i can have the Che successfully run up ?

Other than that, I wonder if we could add another parameter (let's say _CHE_HOST_INTERNAL_) which will be used for KeyCloak redirection instead of using _CHE_HOST_ always...

Thanks a lot.

**Comment by eivantsov** [comment]
@vincentarthur you can use  `-e CHE_KEYCLOAK_AUTH__SERVER__URL=http://$INTERNAL_IP:5050/auth`

**Comment by vincentarthur** [comment]
@eivantsov Thanks for your reply. I've tried this before, unfortunately, it does not work.

You mentioned one key point, the _CHE_HOST_ must be accessible from browser. I think the implied case is, **_the browser will directly make request to KEYCLOAK for authentication_**. However, in my case, i am now using a bastion & SSH Tunnel from one public subnet to access CHE in private subnet, which means the browser **CANNOT** directly access the IP where my KEYCLOAK running on.

Do you see any workaround solution for my case ? Appreciate all your response ! thanks a lot.!

**Comment by eivantsov** [comment]
@vincentarthur what happens when you specify CHE_HOST as IP in a private subnet? Redirects are fine, as long as your browsers can reach destination IPs.

**Comment by vincentarthur** [comment]
Hi @eivantsov , when i specify the CHE_HOST as IP of private subnet, i can access the dashboard with the url -- _http://<my-bastion-public-ip>:8080/dashboard_. with ONLY the loading icon. The KeyCloak is using CHE_HOST by default.

Furthermore, when i F12 to the console on Chrome, i can see it's actually querying the "_http://<CHE_HOST(private ip)>:5050/auth/js/keycloak.js_" which is unreachable. I believe this leads to my failure on accessing the dashboard as i expect.

Thanks again.

**Comment by eivantsov** [comment]
SO, use IP that your browser can resolve

**Comment by vincentarthur** [comment]
@eivantsov so you mean i can only access it within same network (either public or private), but NOT current case i am facing (public + private subnet) ....?

**Comment by eivantsov** [comment]
@vincentarthur you need to make sure that your browser should access Keycloak container, as well as other containers.

**Comment by vincentarthur** [comment]
@eivantsov Quite pity about the final decision, but really thank you so much !! :1st_place_medal:
