### ISSUE TITLE
eclipse/che - Symfony4

### ISSUE THREAD

**Issue by Modify76** [eclipse-che/che#10579]
### Description
Hi, I would like to use eclipse/che as a development environment for a symfony 4 project but at the time of installation I am asked for the 7.1 version of PHP. When chosing the PHP Worspace I noticed that only version 7.0.3 is proposed, how can I install 7.1? Thank you

**Comment by eivantsov** [comment]
@Modify76 you can build a Docker image with PHP 7.1:

```
FROM eclipse/php
RUN <remove *php -packages>
RUN <install php7.1>
```

**Comment by eivantsov** [comment]
@Modify76 thanks. Maybe it makes sense to update the default image for php to 7.1
