### ISSUE TITLE
Create test session for checking interaction of language servers with two open browser instances

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#10581]
### Description
We have feature like File Watcher and we have tests which check actions like: editing, deleting, adding files and folders and other test actions under File Watcher. But we have never tested how work Language servers under File watcher. 
**For instance:** The user # 1  and use # 2 work with common **go lang** project with chrome browser. The user # 1 open a project file and add new method for handling a request. The user#2 also is worjing with the same file. We should figur out how language server will be work in this case (how will be update file, code validation, documentation,  hovering, syntax highlighting and etc. ).
For beginning we can use existed test plan for language servers  and check it under 2 browsers.
The bug list should be attached to this issue

**OS and version:**   The Che under docker and openshift infrastructure, upstream version, chrome browser, 2 users

**Comment by gazarenkov** [comment]
@musienko-maxim 
Would not say it is clear what exactly you expect here

**Comment by SkorikSergey** [comment]
**After test session we found two global problems:**
1. Error markers unexpectedly disappear in second browser session.
2. Main language server features are broken after closing a file in second browser session.

**User story 1**
Steps to reproduce:
Preconditions: Create workspace with project which related with current language server. Language server should be enabled and initialized.
1. The users # 1 and # 2 work with the same project in 2 different browsers.
2. The users # 1 and # 2 open the same file. The user # 1 make error and check that error marker is appeared.

**Expected results:**
Error marker should appear in both browsers.

**Actual results:**
Error marker has been appeared only in user # 1 browser. There is no any markers in user # 2 browser (It is actual for next LS: Clang, Python, PHP, TypeScript, Yaml, C#).

---------------------------------------------------------------------------

**User story 2**
Steps to reproduce:
Preconditions: Create workspace with project which related with current language server. Language server should be enabled and initialized.
1. The users # 1 and # 2 work with the same project in 2 different browsers.
2. The users # 1 and # 2 open the same file. 
3. The user # 1 check a LS feature(for example autocomplete, hovering, find definition).
4. The user # 2 close the edited file.

**Expected results:**
All features which depended on LS should work as expected.

**Actual results:**
All features become broken with error message like ```Can't update file, item does not exist:```. After the file reopening all features work as expected.
