### ISSUE TITLE
Figure out of reason increasing building time of maven project between docker and k8s infrastructure

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#10582]
### Description
We had some unexpected decline of building performance for some maven projects which are used by selenium tests. For some selenium tests for example like debugger we should build war or jar by maven for further steps in a test. For this we apply default timeout (180 sec.) for simple spring project. But on k8s infrastructure sometimes this timeout is not enough. The delay looks too long for this simple action. We should clarify how often  this happens, this was just once or it happens often. Also we can compare differents in time on docker and k8s. As variant run 100 iteration of building on docker and k8s, calculate average value and compare.

**Comment by gazarenkov** [comment]
@musienko-maxim 

any guesses why presence of K8s may impact on project build time?
I suppose you use the same conditions for comparison:
i.e. Docker containers are created from the same images and have the same resources constraints (memory limit, cpu etc)?

**Comment by musienko-maxim** [comment]
Yes, the docker images the same and resources constraints the same limit. But k8s run in pretty specific conditions on CI. These one run under k8s dind tool more info [here:](http://callistaenterprise.se/blogg/teknik/2017/12/20/kubernetes-on-docker-in-docker). It may be reason of the problem. I supposes that on real cluster this one wll be not actual. But anyway i think we should gather more information.
