### ISSUE TITLE
File in /projects treated as a project

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#10586]
### Description

A file is in workspace projects root is treated as a project

### Reproduction Steps

1. Create a file in /projects in the terminal
2. Watch a new folder pops up in project explorer which is treated as a project
3. Refresh the page - the new project is now treated as a misconfigured project

![image](https://user-images.githubusercontent.com/5337267/43450070-966a003e-94ba-11e8-9234-020bf562e9f8.png)

**Comment by vzhukovskii** [comment]
Possible solution will be not to display files at all in the workspace root directory.
