### ISSUE TITLE
Impossible the update the copyright header

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#1059]
I am working on a fix and I tried to update the copyright header in the source code. Whatever change I make results in a fail in the Maven build:

```
[INFO] --- license-maven-plugin:2.10:check (check-headers) @ che-core-api-machine ---
[INFO] Checking licenses...
[WARNING] Missing header in: /home/kraev/git/che/wsmaster/che-core-api-machine/src/main/java/org/eclipse/che/api/machine/server/MachineInstanceProviders.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

This way it is impossible for contributors to denote their contributions in the copyright header.

**Comment by skabashnyuk** [comment]
Try mvn license:format

**Comment by kaloyan-raev** [comment]
`mvn license:format clean install` works.

But is this the expected way to run the build? This may cause troubles to other developers trying the run the build.

**Comment by TylerJewell** [comment]
See this page as you can skip license check as well, which is what you need to do right now:
https://eclipse-che.readme.io/docs/developing-extensions#section-licensing

We know it's not proper to force an EPL license header onto plugins.  We are starting to think about a simpler overall approach to building plugins.  ie, letting you create a plugin and then we'll drag along all of the runtime dependencies needed to build / run it.  And in this we could use a maven BOM to help isolate what is being built, along with giving the end developer more control over the license + dependencies, etc.

**Comment by kaloyan-raev** [comment]
OK. I will abstain changing the copyright header in my contributions until this is resolved.

**Comment by TylerJewell** [comment]
It could be a long time before we introduce the improved plugin building approach.  So please bear that in mind.  I would envision us having something more flexible by the end of the year.

**Comment by kaloyan-raev** [comment]
BTW, a temporary solution would be to switch the license-maven-plugin off. Then the license header must be maintained manually, but this will allow contributors to change them.

**Comment by TylerJewell** [comment]
The challenge with doing that is that we open the risk of committing in code to the repository that has licenses that invalidate the requirements for submission by eclipse foundation.  It may be the type of check that is unnecessary to enforce, and we could theoretically have it as part of the build system / CI.  We had a history where our repository had a lot of transitive dependencies and core committers being a little too "free wheeling" with various standards they were using. Though we may have swung too far to the other side.

**Comment by kaloyan-raev** [comment]
@eivantsov is this issue resolved now? I don't see any pull request or commit linked.
