### ISSUE TITLE
Editor tab header icon moves on top of label when typing

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#10593]
See https://twitter.com/eclipse_che/status/1024244543556919296
The class icon on the header of the tab moves around as I type/save. It ends up on top of the label 'Main' and back.

**Comment by RomanNikitenko** [comment]
Looks like related to https://github.com/eclipse/che/issues/10547

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/5)
