### ISSUE TITLE
Udpate jdt.ls-specific stuff to EPL 2.0

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10595]
Our code in master has been updated to EPL 2.0. There are some files in the 5730_java_ls_poc branch that are not in master, and as such have not been updated. @skabashnyuk has said there is a script that does the update.
The update should also include code in che-ls-jdt and in our Theia/Java plugin repo.

**Comment by skabashnyuk** [comment]
```mvn license:format```
but you need to build che-parent first, at least once with this pr https://github.com/eclipse/che-parent/pull/66

**Comment by vrubezhny** [comment]
The result of the execution of `mvn license:format` doesn't lead into appearing of any changed files neigher in `5730_java_ls_poc` branch nor in `master` branch of `che-js-jdt` repository.

However we still have a bunch of `the Eclipse Public License v1.0` appearances in java and xml files. The lists of such files don't differ too much between `5730_java_ls_poc` and master branches...

@skabashnyuk it looks like not all the java and xml files are being processed by `mvn license:format`, f.i (in `eclipse/che master`) :
* https://github.com/eclipse/che/blob/master/plugins/plugin-java/che-plugin-java-ext-lang-server/src/test/resources/projects/test/pom.xml#L5
* https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/hotupdate/rolling/RollingUpdateStrategyWithStartedWorkspaceTest.java#L28
as well as pretty big number of java classes (mostly in tests) and xml files.

**Comment by skabashnyuk** [comment]
@vrubezhny it can happen.
