### ISSUE TITLE
Can not delete Command

### ISSUE THREAD

**Issue by liubin10** [eclipse-che/che#10609]
### Description
Can not delete Command with prefix of [/]
![1533092895258](https://user-images.githubusercontent.com/32632875/43499102-8bb62ac4-957c-11e8-9514-c72ca1943fd9.png)

**Comment by eivantsov** [comment]
@liubin10 can it be related to command name perhaps? Slashes in the beginning I mean...

**Comment by liubin10** [comment]
@eivantsov I think so.I think regex check should be added for Command name

**Comment by gazarenkov** [comment]
P1 since looks like a quick fix

**Comment by azatsarynnyy** [comment]
added validation in https://github.com/eclipse/che/pull/11535

**Comment by azatsarynnyy** [comment]
A previously created command, with a not valid name, can be deleted by editing workspace configuration in the dashboard.
