### ISSUE TITLE
JDT.LS integration issues

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#10621]
### Description
Umbrella issue for JDT.LS selenium tests incompatibility. 
Under this issue we need to fix the problem in the code or adapt failed Selenium tests according to JDT.LS specific behavior.

**Comment by tsmaeder** [comment]
I would propose that we coordinate work on https://github.com/eclipse/che/issues/9591

**Comment by vparfonov** [comment]
- [ ] JDT.LS: fix selenium tests in org.eclipse.che.selenium.miscellaneous #10805
- [ ] JDT.LS: fix selenium tests in org.eclipse.che.selenium.intelligencecommand  #10803
