### ISSUE TITLE
Does Eclipse Che support importing projects from gitHub Enterprise?

### ISSUE THREAD

**Issue by kwangpa88** [eclipse-che/che#1063]
It fails when I import a project from  gitHub Enterprise host even if  I have configured che.properties for oauth.github.**\*

**Comment by ghost** [comment]
oAuth works OK with GitHub.com API. I cannot say for sure it may or may not work. How did you configure che.properties?

**Comment by kwangpa88** [comment]
It works well with github.com API  but not other gitHub enterprise domain.
My che.properties is like below.

oauth.github.clientid=XXX
oauth.github.clientsecret=XXX
oauth.github.authuri= https://oss.XX.com/login/oauth/authorize
oauth.github.tokenuri= https://oss.XX.com/login/oauth/access_token
oauth.github.redirecturis=  http://xxxx:8080/ide/api/oauth/callback
auth.oauth.access_denied_error_page=/error-oauth

One thing I should mention is that che server send request to **"https://api.github.com/users" in the middle of oAuth with my GitHub Enterprise domain.  
I think the domain should be my github enterprise host.

**Comment by ghost** [comment]
GitHub is the only oAuth provider available in Che. As a workaround you may generate SSH key and save it to your GitHub Enterprise account to be able to clone and push to private repositories.
