### ISSUE TITLE
che workspaces commands can not interactive

### ISSUE THREAD

**Issue by village-way** [eclipse-che/che#10630]
### Description
I really want to know, is there a way to run the che commands with interactive.
i want to use the command `mysql` `tail -f /path/xx.log` `vim pom.xml` `top`

but the command only execute with result, can not run in the terminal native.

### Here is the tips

![image](https://user-images.githubusercontent.com/11625846/43563161-53e030d6-9653-11e8-8039-ab0809c2dbe1.png)

**OS and version:**    
che 6.9.0
Google chrome67
macos 10.12.6

**Diagnostics:** 
i can run the commands in the terminal.

**Comment by eivantsov** [comment]
@HiDevine commands are execs, so for now I'd say this is expected behavior. You can use terminal for interactive commands.
