### ISSUE TITLE
Provide code navigation with Ctrl+Click

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#10637]
### Description

currently code navigation is provided with F4. Generally IDEs are allowing to ctrl+click to navigate (at least for Eclipse and IntelliJ and VS Code)
(F4 can be kept)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
@tsmaeder @svor @tolusha is this smth that we can/will do in GWT IDE or Theia?
