### ISSUE TITLE
Deploy the Plugin Registry on OSIO

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#10652]
### Description

Deploy a plugin registry instance for osio (necessary for the ws.next + theia stacks)

- [x] Create a new dockerfile based on RHEL
- [x] Create a centos CI job that build the RHEL based image and push it to devshift
- [x] Create a yaml to deploy on openshift
- [x] Add a new service here https://github.com/openshiftio/saas-openshiftio/blob/master/dsaas-services/che-plugin-registry/

**Comment by riuvshin** [comment]
Done.
rhel image: https://quay.io/repository/openshiftio/rhel-che-plugin-registry
ci job: https://ci.centos.org/job/devtools-che-plugin-registry-build-master
service is deployed on rh-idev and prod already. 
note there is no public route yet.
