### ISSUE TITLE
[Walking Skeleton] Setup a CI for the Plugin Registry

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#10651]
Use DockerHub automated build to build `eclipse/che-plugin-registry` image for every commit on master branch.

Use travis.ci only if it there are techincal difficulties to use docker hub automated build for an eclipse organization repository.

**Comment by skabashnyuk** [comment]
done in https://hub.docker.com/r/eclipse/che-plugin-registry/builds/
