### ISSUE TITLE
[Walking Skeleton] Edit Workspace Attributes from the dashboard

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#10650]
Currently workspace.next plugins and editor are defined as workspace attributes. As a consequence they cannot be edited from the dashboard before the workspace is started.

This issue is to solve that problem: as a developer I would like to be able to manually edit the workspace configuration to add new plugins and editor.

![image](https://user-images.githubusercontent.com/606959/43640175-2e039f84-971f-11e8-881f-6128114719e3.png)

Solving this issue may require to extend the workspace config model. Something that is somehow necessary anyway to define workspace.next based stacks and factories. 

This issue is **NOT** about adding a dashboard widget.

**Comment by sleshchenko** [comment]
The attributes field is added into WorkspaceConfig object and it is supposed that workspace.next configuration will be placed there. So, now it is possible to manually edit plugins and editor via dashboard
![screenshot_20180816_104216](https://user-images.githubusercontent.com/5887312/44195218-101bbe80-a141-11e8-8689-dccb74e6e5df.png)
