### ISSUE TITLE
Find replace for factories in Theia

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#10653]
### Description
Look if there is anything to do to have `find replace` feature in factory implementation in Theia execpt commands.
https://www.eclipse.org/che/docs/factories_json_reference.html#action-find-and-replace

**Comment by olexii4** [comment]
A working sample for https://github.com/eclipse/che-theia-task-plugin/pull/3 :
`
    {
      "commandLine": "sudo sed -i 's/\\*/\\*\\*\\*/g' console-java-simple/README.md",
      "name": "console-java-simple:replace",
      "type": "custom",
      "attributes": {
        "machineName": "dev-machine",
        "previewUrl": "",
        "goal": "Common"
      }
    }
`
We have "couldn't open temporary file console-java-simple ... Permission denied" without sudo
