### ISSUE TITLE
Could docker be called the same way in all poms?

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#10660]
### Description

I noticed today looking through the poms in this repo that invoking docker is done three different ways:

```
<exec dir="${basedir}" executable="docker" failonerror="true">
<arg value="build" />
<arg value="-t" />
```
(2 files)

```
<exec executable="bash">
<arg value="-c" />
<arg value="docker run --rm eclipse-che-dashboard | tar -C target/ -xf -" />
   or
<arg value="docker run --rm eclipse-che-workspace-loader | tar -C target/ -xf -" />
```
(2 files)

```
docker-maven-plugin
```
(4 files)

### Reproduction Steps

Here's the list of files that call docker one of 3 ways, matching the above lists:

dashboard/pom.xml
workspace-loader/pom.xml

dashboard/pom.xml
workspace-loader/pom.xml

multiuser/integration-tests/che-multiuser-postgresql-tck/pom.xml 
plugins/plugin-gdb/che-plugin-gdb-server/pom.xml 
plugins/plugin-java-debugger/che-plugin-java-debugger-server/pom.xml 
wsmaster/integration-tests/postgresql-tck/pom.xml 

So, I'm wondering if there's a way we can rewrite these poms so they all use the docker-maven-plugin to invoke docker, thus removing the dependency on bash and docker executables and relying on the maven abstraction.

**Comment by skabashnyuk** [comment]
In some places, docker is used to build something on others to test something. Which one are you interested in?

**Comment by benoitf** [comment]
I think we're in a egg and chicken issue. You can either use:
- native tools (go, npm) installed on the system
- docker containers to use portable way of launching commands

it seems you want "portable way" without docker but then it's using tools installed on your own.

> Why, you ask? Portability. Not every OS / build slave can be guaranteed to have bash & docker on it.

so if Docker is not there, you should rely on native tools provided on the system. I don't see how using maven will avoid the use of docker or bash. If docker is not available, it is clearly not available.

**Comment by nickboldt** [comment]
@skabashnyuk I'm trying to figure out why we need to call bash sometimes, docker other times, and docker-maven-plugin other times. 

Surely we could achieve both building and testing with a single approach?

@benoitf I'm not trying to solve the chicken-egg issue. I'm asking why we use:

* maven mojo to call docker 4 times, 
* maven exec to call bash to call docker exe 2 times, and 
* maven exec to call docker exe directly (no bash) 2 times. 

Why do the same thing 3 different ways?

**Comment by benoitf** [comment]
Different ways of calling:
-> I think it's because it has been made by different person at different times
Also as Sergii said, sometimes it's used to only build the image, to test the image or run something.

**Comment by nickboldt** [comment]
ok so in theory we could streamline this so it's the same type of invocation in all 8 places. Would you agree?

**Comment by skabashnyuk** [comment]
>Also as Sergii said, sometimes it's used to only build the image, to test the image or run something.

Not an image.
To build some code - like a dashboard.
To test some code - like SQL integration testing on real PostgreSQL in the container.

**Comment by skabashnyuk** [comment]
closing. feel free to reopen this issue if you think it is still relevant for you
