### ISSUE TITLE
use which develop environment（IDE） to extension Che code？

### ISSUE THREAD

**Issue by lovedshell** [eclipse-che/che#10668]
I use local eclipse to extension Che code without debugging  .Because Che use docker to run，after little bit of code change, I  have to restart Che to see my code change whether take effect.
  So，I spend lots of time to run build command and restart Che. 
  I want to ask your Che developers, what development tools do you use to run debugging at development time?

**Comment by eivantsov** [comment]
@lovedshell are you talking about Che master or do you develop a plugin for Che?

**Comment by lovedshell** [comment]
Thank you for your reply @eivantsov .I want to develop a plugin for Che based on Che master code on Windows.

**Comment by eivantsov** [comment]
@lovedshell you can use Che itself or any local IDE of choice. https://www.eclipse.org/che/docs/framework-overview.html
