### ISSUE TITLE
Node Debugging

### ISSUE THREAD

**Issue by davidtay** [eclipse-che/che#10669]
### Description
Node Debugging not Working

### Reproduction Steps
1. Created new Workspace with Node Stack
2. Started workspace
2. Created Express Project with Express Generator
3. Set breakpoint on app.js (. 
4. Create Run command
5. Run the Express app
6. Selected Run -> Debug -> Remote Node JS

Breakpoints never hit. App runs fine.

**OS and version:**    
Mac OS High Sierra

**Diagnostics:** 
Have read this a hundred times https://www.eclipse.org/che/docs/debug.html to no avail, and the screenshot is running a little too fast and too small to see any thing.

**Comment by eivantsov** [comment]
@davidtay I'd say that Che does not support Node.js debugger.  Though the break point should have been hit but there're no threads and envs stack.
