### ISSUE TITLE
che-theia-factory extension is not working if che-theia-hosted-plugin-manager-extension is activated

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#10663]
### Description
Theia factory extension is not cloning projects defined in a factory configuration when che-theia-hosted-plugin-manager-extension is activated.

#### context
- docker infra,
- che-single user
- localhost

#### Steps to reproduce the bug
1. Build [dockerfiles/theia](https://github.com/eclipse/che/tree/master/dockerfiles/theia) with `./build.sh`. Tag it however you want:  
    ```
    docker tag eclipse/che-theia:nightly someone/che-theia:withplhosted
    ```
2. Create a factory file based on the theia docker stacks and add few projects to clone. Mine looks like this 
https://gist.github.com/sunix/0b85bcfe903e9f62eb8ad303ec02c357 .
3. Replace the Theia image to use in the compose file: `someone/che-theia:withplhosted`
    ```
            "recipe": {
          "type": "compose",
          "content": "services:\n terminal:\n  image: aandrienko/machine-exec:latest\n theia:\n  image: someone/che-theia:withplhosted\n  mem_limit: 1073741824\n dev-machine:\n  image: eclipse/che-dev:nightly\n  mem_limit: 2147483648\n  depends_on:\n    - theia",
          "contentType": "application/x-yaml"
        }

    ```
4.  Open the factory: none of the projects is cloned

#### Steps to verify that it is working without che-theia-hosted-plugin-manager-extension
1. Remove from the file [dockerfiles/theia/src/extensions.json](https://github.com/eclipse/che/blob/master/dockerfiles/theia/src/extensions.json) the lines
    ```
            {
            "name": "@eclipse-che/che-theia-hosted-plugin-manager-extension",
            "source": "https://github.com/eclipse/che-theia-hosted-plugin-manager-extension.git",
            "checkoutTo": "latest-deps",
            "type": "git"
        },
    ```
2. Build [dockerfiles/theia](https://github.com/eclipse/che/tree/master/dockerfiles/theia) with `./build.sh`. Tag it however you want:  
    ```
    docker tag eclipse/che-theia:nightly someone/che-theia:withoutplhosted
    ```
3. Create a factory file based on the theia docker stacks and add few projects to clone. Mine looks like this 
https://gist.github.com/sunix/0b85bcfe903e9f62eb8ad303ec02c357 .
4. Replace the Theia image to use in the compose file: `someone/che-theia:withoutplhosted`
    ```
            "recipe": {
          "type": "compose",
          "content": "services:\n terminal:\n  image: aandrienko/machine-exec:latest\n theia:\n  image: someone/che-theia:withoutplhosted\n  mem_limit: 1073741824\n dev-machine:\n  image: eclipse/che-dev:nightly\n  mem_limit: 2147483648\n  depends_on:\n    - theia",
          "contentType": "application/x-yaml"
        }

    ```
5.  Open the factory: projects are cloned: cloning messages appears and then projects are visible from the project explorer

**Comment by mmorhun** [comment]
I see no interference of this problem with `hosted-plugin-manager-extension`. The extension works only with hosted instance related things. If you do not use it - it does nothing and cannot be the reason of falling.
I would suggest to retest more carefully and update the issue title and description. I think the problem might be in the extension adding mechanism, which cause some dependencies problem, but this is just an assumption.
