### ISSUE TITLE
GWT Error

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#10672]
Hi,

I have fallowed your embedjs sample without issues, then I change the package name from org.eclipse.che.sample and now I cannot compile this module and I don't know why

[INFO] Che IDE :: GWT App ................................. FAILURE [ 51.504 s]

[ERROR] Line 30: No source code is available for type org.eclipse.che.plugin.vfos.menu.VfOsMenuViewExtension; did you forget to inherit a required module?

Are you able to help me please?

**Comment by skabashnyuk** [comment]
Can you share your source code somewhere on Github?

**Comment by mstavares** [comment]
Hi @skabashnyuk ,

My issue is related with a plugin -> che-plugin-vfos-menu-ide

https://github.com/mstavares/che_issue

**Comment by skabashnyuk** [comment]
Did you follow some guide or made a sample from one of this projects https://github.com/che-samples ? Looks like you have very old fork of che? Am I right?

**Comment by mstavares** [comment]
Hi @skabashnyuk 

Yes, you guys sent me a tutorial from embedjs

**Comment by skabashnyuk** [comment]
Can you point me on that comment?
AFAIK this is  https://github.com/che-samples/che-plugin-embedjs sample. And It doesn't contain the whole Che repository.

**Comment by mstavares** [comment]
https://github.com/eclipse/che/issues/10046

**Comment by skabashnyuk** [comment]
@mstavares are you sure https://github.com/che-samples/che-plugin-embedjs has something in common with https://github.com/mstavares/che_issue? Can you fork again https://github.com/che-samples/che-plugin-embedjs and put your changes as separate commit?

**Comment by mstavares** [comment]
Yes, it has.
Please, look at plugins/plugin-vfos/che-plugin-vfos-menu

**Comment by eivantsov** [comment]
@mstavares you do not need to build the entire Che.

Just fork https://github.com/che-samples/che-plugin-embedjs

Change package name and make sure it is changed here to https://github.com/che-samples/che-plugin-embedjs/blob/master/assembly/assembly-ide-war/pom.xml#L38

**Comment by mstavares** [comment]
@eivantsov I already changed the package name but I still having the same issue.

[INFO] Compiling module org.eclipse.che.ide.IDE
[INFO]    Ignored 92 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    Computing all possible rebind results for 'com.google.gwt.useragent.client.UserAgentAsserter'
[INFO]       Rebinding com.google.gwt.useragent.client.UserAgentAsserter
[INFO]          Checking rule <generate-with class='com.google.gwt.editor.rebind.SimpleBeanEditorDriverGenerator'/>
[INFO]             [WARN] Detected warnings related to 'com.google.gwt.editor.client.SimpleBeanEditorDriver'.   Are validation-api-<version>.jar and validation-api-<version>-sources.jar on the classpath?
[INFO]             Specify -logLevel DEBUG to see all errors.
[INFO]             [WARN] Unknown type 'com.google.gwt.editor.client.SimpleBeanEditorDriver' specified in deferred binding rule
[INFO]    Computing all possible rebind results for 'org.eclipse.che.ide.client.inject.IDEInjector'
[INFO]       Rebinding org.eclipse.che.ide.client.inject.IDEInjector
[INFO]          Checking rule <generate-with class='org.eclipse.che.util.ExtensionRegistryGenerator'/>
[INFO]             Tracing compile failure path for type 'org.eclipse.che.ide.client.inject.IDEInjector'
[INFO]                [ERROR] Errors in 'file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-ide-gwt-app/target/generated-sources/gen/org/eclipse/che/ide/client/inject/IDEInjector.java'
[INFO]                   [ERROR] org.eclipse.che.ide.bootstrap.IdeBootstrap cannot be resolved to a type
[INFO]                [ERROR] Errors in 'jar:file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-core-ide-app/target/che-core-ide-app-6.7.0-SNAPSHOT.jar!/org/eclipse/che/ide/bootstrap/IdeBootstrap.java'
[INFO]                   [ERROR] org.eclipse.che.ide.bootstrap.ExtensionInitializer cannot be resolved to a type
[INFO]                [ERROR] Errors in 'jar:file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-core-ide-app/target/che-core-ide-app-6.7.0-SNAPSHOT.jar!/org/eclipse/che/ide/bootstrap/ExtensionInitializer.java'
[INFO]                   [ERROR] org.eclipse.che.ide.client.ExtensionManager cannot be resolved to a type
[INFO]                [ERROR] Errors in 'file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-ide-gwt-app/target/generated-sources/gen/org/eclipse/che/ide/client/ExtensionManager.java'
[INFO]                   [ERROR] Line 30: No source code is available for type org.eclipse.che.plugin.vfos.menu.VfOsMenuViewExtension; did you forget to inherit a required module?
[INFO]    [ERROR] Errors in 'org/eclipse/che/ide/client/IDE.java'
[INFO]       [ERROR] Line 23: Failed to resolve 'org.eclipse.che.ide.client.inject.IDEInjector' via deferred binding


assembly-ide-war

        <dependency>
            <groupId>org.eclipse.che.plugin.vfos</groupId>
            <artifactId>che-plugin-vfos-menu-ide</artifactId>
            <version>6.7.0-SNAPSHOT</version>
            <type>gwt-lib</type>
        </dependency>

My package name is:

package org.eclipse.che.plugin.vfos.menu.view;

**Comment by skabashnyuk** [comment]
can you fork now https://github.com/che-samples/che-plugin-embedjs with 6.10.0-snapshot version and apply your changes as separate commit?

**Comment by mstavares** [comment]
@skabashnyuk 

Done, but remains with the same error

INFO] --- gwt-maven-plugin:1.0-rc-8:compile (default-compile) @ che-ide-gwt-app ---
[INFO] Compiling module org.eclipse.che.ide.IDE
[INFO]    Ignored 92 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    Computing all possible rebind results for 'com.google.gwt.useragent.client.UserAgentAsserter'
[INFO]       Rebinding com.google.gwt.useragent.client.UserAgentAsserter
[INFO]          Checking rule <generate-with class='com.google.gwt.editor.rebind.SimpleBeanEditorDriverGenerator'/>
[INFO]             [WARN] Detected warnings related to 'com.google.gwt.editor.client.SimpleBeanEditorDriver'.   Are validation-api-<version>.jar and validation-api-<version>-sources.jar on the classpath?
[INFO]             Specify -logLevel DEBUG to see all errors.
[INFO]             [WARN] Unknown type 'com.google.gwt.editor.client.SimpleBeanEditorDriver' specified in deferred binding rule
[INFO]    Computing all possible rebind results for 'org.eclipse.che.ide.client.inject.IDEInjector'
[INFO]       Rebinding org.eclipse.che.ide.client.inject.IDEInjector
[INFO]          Checking rule <generate-with class='org.eclipse.che.util.ExtensionRegistryGenerator'/>
[INFO]             Tracing compile failure path for type 'org.eclipse.che.ide.client.inject.IDEInjector'
[INFO]                [ERROR] Errors in 'file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-ide-gwt-app/target/generated-sources/gen/org/eclipse/che/ide/client/inject/IDEInjector.java'
[INFO]                   [ERROR] org.eclipse.che.ide.bootstrap.IdeBootstrap cannot be resolved to a type
[INFO]                [ERROR] Errors in 'jar:file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-core-ide-app/target/che-core-ide-app-6.7.0-SNAPSHOT.jar!/org/eclipse/che/ide/bootstrap/IdeBootstrap.java'
[INFO]                   [ERROR] org.eclipse.che.ide.bootstrap.ExtensionInitializer cannot be resolved to a type
[INFO]                [ERROR] Errors in 'jar:file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-core-ide-app/target/che-core-ide-app-6.7.0-SNAPSHOT.jar!/org/eclipse/che/ide/bootstrap/ExtensionInitializer.java'
[INFO]                   [ERROR] org.eclipse.che.ide.client.ExtensionManager cannot be resolved to a type
[INFO]                [ERROR] Errors in 'file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-ide-gwt-app/target/generated-sources/gen/org/eclipse/che/ide/client/ExtensionManager.java'
[INFO]                   [ERROR] Line 38: No source code is available for type org.eclipse.che.plugin.vfos.HelloWorldViewExampleExtension; did you forget to inherit a required module?
[INFO]    [ERROR] Errors in 'org/eclipse/che/ide/client/IDE.java'
[INFO]       [ERROR] Line 23: Failed to resolve 'org.eclipse.che.ide.client.inject.IDEInjector' via deferred binding
[INFO] ------------------------------------------------------------------------

I have used that sample and then I changed the package name

**Comment by skabashnyuk** [comment]
can you share your new fork?

**Comment by eivantsov** [comment]
@mstavares have you changed it here too https://github.com/che-samples/che-plugin-embedjs/blob/master/pom.xml#L67?

Try text search across the project to see where the old artifact name might be.

**Comment by mstavares** [comment]
@skabashnyuk 

I didn't change nothing on your sample code, I just tried to change the package name and the same error remains.

**Comment by mstavares** [comment]
@eivantsov 

Mine is like this:
          <dependency>
                <groupId>org.eclipse.che.plugin</groupId>
                <artifactId>plugin-embedjs-ide</artifactId>
                <version>${che.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.che.plugin</groupId>
                <artifactId>plugin-embedjs-ide</artifactId>
                <version>${che.version}</version>
                <type>gwt-lib</type>
            </dependency>

Should I remove this one?

             <dependency>
                <groupId>org.eclipse.che.plugin</groupId>
                <artifactId>plugin-embedjs-ide</artifactId>
                <version>${che.version}</version>
            </dependency>
