### ISSUE TITLE
improve che-theia-task-extension README file

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#10683]
### Description
At the moment, che-theia-task-extension comes with a README file https://github.com/eclipse/che-theia-task-plugin/blob/master/che-theia-task-extension/README.md with few informations how to run the extension but we still missed some more information on it so anyone could try the extension
- More detailed step by step (with command line samples) setup how to: for instance, how to build machine-exec and include it in a workspace config side by side with the theia container.
- Complete user stories of the features that it covers: launched commands added from a workspace config with preview url, etc ...
- maybe a list of typical issues we could encounter + how to fix it

**Comment by olexii4** [comment]
1. Clone [eclipse/che-theia-terminal-plugin](git@github.com:eclipse/che-theia-terminal-plugin.git). And build the needed "eclipse/machine-exec:latest" image with  [./machine-exec-server/buildImage.sh](https://github.com/eclipse/che-theia-terminal-plugin/blob/master/machine-exec-server/buildImage.sh)

2. Clone [eclipse/che](git@github.com:eclipse/che.git). 
```
cd che/dockerfiles/theia
```
Aply the [che-theia.patch](https://gist.githubusercontent.com/olexii4/f9386bdf72349a6f995ca4ba7698a2ed/raw/bb80f89b8103bbdffa621ab39688f03d0d09961c/che-theia.patch) and build the needed "eclipse/che-theia:0.3.12-nightly" image with using build script
```
./build.sh --build-args:GITHUB_TOKEN=$GITHUB_TOKEN,THEIA_VERSION=0.3.12 --tag:0.3.12-nightly
```

3. The following mount should be set in the che.env file: CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock;
Change and restart CHE if it wasn't.

**Comment by mmorhun** [comment]
To me it is a problem but not that one which blocks Che

**Comment by sunix** [comment]
@mmorhun It is not because it is not a bug on the application that it can not has the severity/blocker. To me, an issue is blocker when the user can not find any easy way to have a feature working. Here, without a proper README file, it is impossible to know how to make this work.
Also this is something that we concider as mandatory. So, if something is marked as 'done' where some mandatory pieces are not here, we have to fix it ASAP.
