### ISSUE TITLE
Same stack boots with different users on Kubernetes and Docker

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#10680]
### Description

I have Che running on Kubernetes as well as docker. When I attempt to load the Go CentOS stack on the Docker one the container boots with `user` as the user as visible in the terminal. But in the Kubernetes environment, it boots up as `root`.

On Docker:
![docker-screenshot](https://user-images.githubusercontent.com/16825130/43755337-1bdfcf10-9a2d-11e8-95c4-7e50e62828ba.png)

On Kubernetes:
![kubernetes-screenshot](https://user-images.githubusercontent.com/16825130/43755351-28cc90be-9a2d-11e8-9882-d9637b5ec66d.png)

Any reason for this discrepancy? And is it possible to run as `user` even on Kubernetes?

**Related side-note**: 

I attempted bringing up the default ubuntu image as user but it always seems to come up as `root` and not `user`.

 But when I modified the Dockerfile to use the user as `ubuntu` instead of `user` it comes up as `ubuntu` and not `root`. Except the project cloned from Git is always owned by root and hence without doing a chown of the folder the `ubuntu` user does not have permission to make any changes to the project files.

**OS and version:**

Che 6.6.0 on Docker
Che 6.6.0 on Kubernetes on GKE

**Diagnostics:**

**Comment by eivantsov** [comment]
@mjshashank i think it **might** be a purely K8S question, not Che one...In image dockerfiles we have `USER user`.

Have you tried creating a pod without Che from `eclipse/ubuntu_jdk8` image, for example? 

I wonder if this is somehow related with `runAsUser` .
