### ISSUE TITLE
[Language server] Find References feature displays incorrect line positions

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10698]
**Reproduction Steps:**
1. Create and start workspace from **PHP** stack with "web-php-simple" project.
2. Open index.php file and change text to:
``` 
<?php
function sum($x, $y) {
    return $x + $y;
}
echo "14 + 16 = " . sum(14,16)
?>
```
3. Click on ```sum()``` in line 2.
4. Start **Find References** feature from **Assistant** menu or by Alt+F7 buttons.

**Expected behavior:**
There is ```/web-php-simple/index.php From:5:20 To:5:23``` message in opened **References** panel.

**Observed behavior:**
The expected value is less by one - ```/web-php-simple/index.php From:4:20 To:4:23```.
 
**Che version**: 6.10.0
**OS and version:** Fedora 28
**Language servers that have this feature:** PHP, Python, Type Script, Golang.

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_070](https://user-images.githubusercontent.com/7760565/43830171-5e8f9156-9b09-11e8-82ff-3b1dc2204cb2.png)

**Comment by tsmaeder** [comment]
Note that this is a display bug only, double-clicking the result correctly jumps to the location of the reference.
The problem here seems to be the LSP positions are 0-based, so for display we would have to add 1, because the displayed line numbers start at 1.

**Comment by tsmaeder** [comment]
I've updated the title from "returns" to "displays" to better reflect the fact that this is display bug.
