### ISSUE TITLE
Implement Git Status Cache

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#10696]
### Description
 
Frequent Git status calls may cause `out of memory error` in the `JGit`library (see #10543). We need to have a storage with Git statuses, that will be updated by Git events. `GitStatusProvider` should use this storage to get Git status instead of calling the `JGit` library.

We already have a Git Status event that notifies about Status changes, e.g Add to index.
We have a file changed event, **but** the event works only for files that are opened in the project explorer or in the editor.
We **don't** have a file created event to set untracked statuses.
For current direct status calls those events are enough, but for cashed storage it is needed to detect those change.

Need to update current Selenium test to check added from terminal files.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by vkuznyetsov** [comment]
Changed status to bug because this should fix existed bug

**Comment by skabashnyuk** [comment]
This enhancement can improve the performance of the file tree and it's not fixing https://github.com/eclipse/che/issues/10543. It might reduce a probability of OOM but not fixing it.
