### ISSUE TITLE
Find References panel icon has incorrect hover message

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10700]
**Reproduction Steps:**
1. Create and start workspace from **PHP** stack with "web-php-simple" project.
2. Open **index.php** file.
3. Start **Find References** feature from **Assistant** menu or by **Alt+F7** buttons.
4. Hover mouse pointer on the **Find References** panel icon to get hover message.

**Observed behavior:**
There is ```null``` text(see screenshot).
 
**Che version**: 6.10.0
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![find references null](https://user-images.githubusercontent.com/7760565/43831800-f8578fe2-9b0d-11e8-935c-329db0381ca4.png)

**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 08 08-13-17-26](https://user-images.githubusercontent.com/7760565/43831805-fc21afe0-9b0d-11e8-8740-5ec4150fd011.gif)

**Comment by vzhukovskii** [comment]
Issue can't be reproduced
