### ISSUE TITLE
Che build is failing in docker

### ISSUE THREAD

**Issue by shahar-h** [eclipse-che/che#10702]
### Description
I'm trying to build che inside docker conatainer using eclipse/che-dev image, as described in the documentation:
https://www.eclipse.org/che/docs/build-reqs.html#build-in-docker

I'm using maven native profile: mvn clean install -Pnative.
Build is failing with the following error:
![image](https://user-images.githubusercontent.com/16555289/43835788-cec85cf2-9b1b-11e8-8377-ab40d7d1dfe0.png)

It appears that TypeScriptDTOGeneratorMojoITest.java integration test is trying run a docker container.
I would expect that docker should not be used when running maven with native profile.

### Reproduction Steps
Build latest che with "docker run -ti -v ~/.m2:/home/user/.m2 -v /path/to/che/assembly:/che eclipse/che-dev:nightly sh -c "mvn clean install -Pnative"

#### OS and version:  Ubuntu 16.04

**Comment by skabashnyuk** [comment]
try this way

```
docker run -ti -v ~/.m2:/home/user/.m2 -v /Users/sj/dev/src/redhat/che/core/che-core-typescript-dto-maven-plugin/:/projects eclipse/che-dev:nightly sh -c "mvn clean install -Pnative -DskipIntegrationTests"
```
important part ``` -DskipIntegrationTests```

**Comment by shahar-h** [comment]
Can someone refer to my last comment?

**Comment by skabashnyuk** [comment]
we are welcome for any pr that can fix this issue

**Comment by mmorhun** [comment]
Covered by https://github.com/eclipse/che/pull/14181

**Comment by mmorhun** [comment]
Feel free to reopen in case of any issues.
