### ISSUE TITLE
Limit scope of APIs that can be called with machine token

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10710]
### Description
We want to limit the number of APIs that can be called with machine token (not user token).
In this case, machine token usually is used by workspace server side to get some user information (profile, ssh keys, OAuth token) or workspace related information  (workspace config, project config)
For sure we want to deny: workspace start-stop-delete operation, new machine token generation.
Making a concrete list of APIs allowed to call with machine token on the master is a part of this issue too.

**Comment by sleshchenko** [comment]
Let me clarify that in the case of Workspace API it makes sense not just deny some methods BUT deny parameters of allowed methods. I mean get workspace and update workspace where workspace id is a parameter. So, we need to deny to perform a workspace-related operation with foreign workspace machine token.

**Comment by Ido-Itz** [comment]
First off - thanks for opening this issue Sergii.

It's not only a matter of which APIs should be available with a machine token and which should not. The question is - why should the workspace master respond to any request (that came with a machine token), with any information about a different workspace (e.g. even listing the other workspaces)? As far as I know there's no business justification for this.
The main concerns are:
1. In terms of architecture/concept - this makes the scope of machine tokens unclear.
2. Security - If the machine token is stolen, the breach now extends to all of the user's workspaces and not just one.


Also,
> machine token usually is used by workspace server side to get some user information (profile, ssh keys, OAuth token)  

What do you mean by "OAuth token"? Does this mean that the machine token can somehow be used to get access to the user's JWT?

**Comment by skabashnyuk** [comment]
>It's not only a matter of which APIs should be available with a machine token and which should not. >The question is - why should the workspace master respond to any request (that came with a >machine token), with any information about a different workspace (e.g. even listing the other >workspaces)? As far as I know there's no business justification for this.

@Ido-Itz  right.  You and @sleshchenko are talking about the same thing https://github.com/eclipse/che/issues/10710#issuecomment-411663286  I think we will restrict actions with workspace api with machine token to the workspace wich this token belongs.


>What do you mean by "OAuth token"?

I mean you should be able to get Github OAuth token from IDE

>Does this mean that the machine token can somehow be used >to get access to the user's JWT?

No. The whole point of machine token is to **NOT** give an access to user's JWT(keycloak) token with machine token.

**Comment by mshaposhnik** [comment]
Ci tests reported the following machine token signed requests:
 - `/api/workspace/ws123` ( sometimes with includeInternalServers=true )
- `/api/activity/ws123`  workspace activity tracking
- `/api/websocket`  WS connections
- `/api/ssh/vcs/findname=github.com`, /api/ssh/generate`  SSH keys
- `/api/preferences?filter=git.committer` git preferences

**Comment by sleshchenko** [comment]
I propose the following plan for accessing Factory service with machine token.
There are two kinds of Factory Service's methods:
1. Workspace related: `getFactoryJson` - get factory json by workspace id. This method may be restricted by workspace id in machine token, the same as method `get workspace by id` from WorkspaceService.
2. Factory related: all other - create a new factory, get factory, resolve factory, update factory, remove factory. Since read factory operations are public methods which are accessible for each user - we can allow to use them with machine token too. And modifiable operations should be forbidden with machine token.
