### ISSUE TITLE
Incorrect autocompletion of template with variables

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#10711]
If I use autocompletion on templates containing variables the cursor is not correctly placed after the completion for example: 

syso^

(where ^ is autocompletion request)

yields System.out.println() and the 'Syst' part being selected. Normally I'd expect the cursor to be in between the () of println() so I can keep typing. Right now if I press any key I delete 'Syst' and type right there resulting in messy compile errors.

**Comment by eivantsov** [comment]
@scela i think it's worth trying again when jdt.ls is merged
