### ISSUE TITLE
Incorrect link on the docs site.

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#10720]
Eclipse docs site refers to 5.x docs which also seems to be missing from the site.

![image](https://user-images.githubusercontent.com/82738/43932801-1beedef4-9c14-11e8-937f-659a8496d062.png)

**Comment by slemeur** [comment]
We can remove the 5.x docs now.

cc @eivantsov

**Comment by gorkem** [comment]
Seems to be fixed
