### ISSUE TITLE
Unexpected behavior of notification pop up in specific cases

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#10728]
### Reproduction Steps
On CI infrastructure the notification pop ups do not appear  in the tests like:
* https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/314/Selenium_20tests_20report/ - (**CheckFactoryWithPerUserCreatePolicyTes**t)
* https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/314/Selenium_20tests_20report/ (**JavaTestPluginTestNgTest**)
* https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/596//Selenium_20tests_20report/ (**CheckFactoryWithMultiModuleTest**)

This can be reproduced only CI jobs which run under 3 threads, reproduced randomly but  influence on tests stability. This require a lot time and efforts for investigating. As solution in the tests which depend on this problem, checking pop ups may be replaced on check this events in the Event panel.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/4)

**Comment by rhopp** [comment]
Not relevant anymore. Closing.
