### ISSUE TITLE
[Yaml language server] Unexpected warnings in the 'dev-machine' console after every changes in file

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10735]
**Reproduction Steps:**
1. Create workspace through Dashboard based on **Node** stack with any project. 
2. Enable **Yaml** language server and start the workspace.
3. Set YAML schema: 
    - menu **Profile** -> **Preferences**. 
    - select **Yaml** -> click 'Add Schema Url' button -> type "**kubernetes**".
4. Create "**openshift.yaml**" file and add content:
```
apiVersion: v1
kind: PersistentVolume
metadata:
```
5. Make some changes in file.

**Actual result:**
 There are warning in "**dev-machine**" console after every changes in file:``` [WARN] [o.e.l.j.s.GenericEndpoint 115]       - Unsupported request method: custom/schema/request```
 
**Che version**: 6.10.0
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_076](https://user-images.githubusercontent.com/7760565/43957489-aa1e9010-9cb0-11e8-86bc-1de3c264a604.png)

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 10-15-03-02](https://user-images.githubusercontent.com/7760565/43957483-a6595b40-9cb0-11e8-9bf9-6e4fc8a10da2.gif)

**Comment by vinokurig** [comment]
This is internal problem of the Yaml language server. It probably comes from: 
https://github.com/redhat-developer/yaml-language-server/blob/e2e641f3a1b4f19b460fa8a07f8e857dcb5ad28e/src/server.ts#L48

Opened an issue in the related repo, see the comment above.

**Comment by vinokurig** [comment]
@l0rd I'll check it today

**Comment by l0rd** [comment]
Thank you @vinokurig !
