### ISSUE TITLE
Open a preview URL in an embedded panel in Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#10738]
The issue based on the discussion https://github.com/eclipse/che/issues/8974#issuecomment-392965012

For now, a preview URL for a running command can be opened in a separate browser's tab only.
It'd be useful to have both options available: open URL in a separate tab or open URL inside Theia.

**Comment by azatsarynnyy** [comment]
To keep track of the progress more transparently here's the subtasks I plan to work on:

`Preview URLs` panel
- [ ] Implement a `Preview URLs` panel, at the bottom, to display all the preview URLs. Temporary, a list of the URLs will be updated on each panel opening. `Preview URLs` panel can be opened via a widget on the status panel.
- [ ] A preview URL can be opened in a separate browser's tab.
- [ ] Preview URL list is synchronized with the running tasks automatically.

`Preview` panel - internal mini-browser
- [ ] Implement a `Preview` panel, at the right, with an embedded mini-browser that can open a URL.
- [ ] Make it possible to open any preview URL in a `Preview` panel.

Preview URL notifications
- [ ] Notifications are shown, at the top, as soon as a che-task is running and propose to open a related preview URL (internally or externally)

**Comment by benoitf** [comment]
is it done through Theia plug-in webview ?

**Comment by azatsarynnyy** [comment]
@benoitf no, it's done through Theia extension view contribution

**Comment by slemeur** [comment]
must be with the plugin API

**Comment by azatsarynnyy** [comment]
Subtasks list has been updated after the discussion with @slemeur
