### ISSUE TITLE
How to configure private repository for workspaces in K8S

### ISSUE THREAD

**Issue by i300543** [eclipse-che/che#10744]
### Description
Hello guys,
We at SAP have a task of storing workspace images in secured docker repo.
we are working with k8s runtime.
i have tried changing the values in che.env as described [here](https://www.eclipse.org/che/docs/docker-config.html) , but it doesnt work (maybe because we are not working with the init cli

what i did was:
- change the che.env 
- run dockerfiles/che/build.sh to build wsmaster image
- push the image to docker repo
- deploy to k8s with helm scripts

this doesn't seem to do anything tho, because i didnt see any changes in config map in k8s, wsmaster deployment, or in 
che.properties, and wsmaster fails to create workspaces because credentials are needed to pull image.

next i tried to modify che.properties directly before building the image:
added those lines there:
che.docker.registry.auth.dmz.url=<our_repository_host>
che.docker.registry.auth.dmz.username=<user>
che.docker.registry.auth.dmz.password=<password>
(replaced the actual values)
pushed with this image, still  no joy - Authentication is needed when trying to pull image for create and start workspace.

am i missing something ?
are private repositories supported in k8s ?
if yes, how do i configure them ?

Thanks in advance

**Comment by sleshchenko** [comment]
@i300543 Hello, ASAIK there is no any configuration properties that allow configuring docker credentials for all workspace. But there is implemented an ability for a user to specify his own credentials for private docker repo.
It is implemented in the following PR https://github.com/eclipse/che/pull/9962.
The following UI you can find on the Che Dashboard under Administration>Docker Registries
![screenshot_20180813_095752](https://user-images.githubusercontent.com/5887312/44016932-73774bd4-9edf-11e8-93d8-40ee71905e98.png)

Does it work for you? Is it good enough for your needs to have an ability to configure credentials per user?

**Comment by i300543** [comment]
Not really, we need a global configuration for the common workspace image (shared for all users)
also we don't use the ui currently.
So this is not supported then ?
i was hoping something similar to InitialAuthConfig.java logic was in play in k8s infrastructure.

Could you point me in the direction of point where we could add such a feature as a PR maybe ?

Thanks

**Comment by sleshchenko** [comment]
> So this is not supported then ?

Yes, ASAIK it is not supported.

> Could you point me in the direction of point where we could add such a feature as a PR maybe ?

Maybe you can improve `ImagePullSecretProvisioner` and then it will provision values from Che Server configuration or user specific if present.

Only one question, as far as I understand user is able to read configured credentials, isn't it an issue?

**Comment by i300543** [comment]
if the credentials are provided centrally into che master config, and then passed to ImagePullSecretProvisioner (parallel to UserSpecificDockerRegistryCredentialsProvider),
how would the user be able to read them ?
is .dockercfg passed into the user workspace  pod ?

**Comment by sleshchenko** [comment]
`.dockercfg` is provided via `Secret` object that is created in the same namespace as workspace pod. And for OpenShift the token of default secret account is mounted into workspace pod. So, a user is able to read secret data.
I don't really know the secure model of Kubernetes but I guess it's very similar to OpenShift and a user is able to read all objects withing current namespace. Correct me if I'm wrong. 
Maybe there is another way to specify docker credentials without an ability further reading of them?

**Comment by doreplado** [comment]
Running into the same issue. 

@sleshchenko - I tried the user specific UI that you referenced above and that doesn't seem to allow any access to private images either. 

Could you clarify what the documentation is referencing here if its not a Che-Wide auth setting for a registry?:
https://www.eclipse.org/che/docs/docker-config.html#private-images

**Comment by sleshchenko** [comment]
> @i300543 are you deploying with helm? I've been using
> helm upgrade -f che/deploy/kubernetes/helm/che/values/multi-user.yaml
> --set che.docker.registry.auth.your-repo.url=URL
> --set che.docker.registry.auth.your-repo.username=USERNAME
> --set che.docker.registry.auth.your-repo.password=PASSWORD
> 
> and that works for me

Maybe I missed something but for me it's kind of magic. I don't see any bound components that use such these properties on Kubernetes/OpenShift infrastructures.

@doreplado 
> Could you clarify what the documentation is referencing here if its not a Che-Wide auth setting for a registry?:
> https://www.eclipse.org/che/docs/docker-config.html#private-images

Sure, as you can see this article is under `Che on Docker` section. 
I've checked and AFAIS components that use these configuration properties is not used by Kubernetes neither OpenShift infrastructures.

Kubernetes/OpenShift infrastructure fetch credentials only from user preferences.
Actually, I tried it some time ago and it worked. Maybe it is broken now or you specify wrong value for registry. I'll check it again and notify you.

**Comment by sleshchenko** [comment]
@doreplado 
I've checked it and it works for me on Che on OCP, I suppose it might not work on Kubernetes but it should. Please create a separate issue if it doesn't work for you
![privateregistry](https://user-images.githubusercontent.com/5887312/45030189-b88fb500-b053-11e8-9b78-cd0def19b03e.gif)
