### ISSUE TITLE
invalid Default Chart Value

### ISSUE THREAD

**Issue by Jimmyscene** [eclipse-che/che#10743]
Hey, 

It looks to me like the change here: https://github.com/eclipse/che/pull/10705 is causing the following issue when trying to upgrade via helm
```
Error: release eclipse-che failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap: Data: ReadString: expects " or n, but found -, error found in #10 byte of ...|TIMEOUT":-1,"CHE_LOC|..., bigger context ...|REALM":"che","CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT":-1,"CHE_LOCAL_CONF_DIR":"/etc/conf","CHE_LOGS_APPEN|...
```
This seems to be due to the value being -1. Replacing the value in the config map with
`CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "{{ .Values.global.workspaceIdleTimeout }}"`
seems to cause the error to go away, but I'm not familiar enough with the codebase to know if the value is getting propagated downward correctly.

**Comment by eivantsov** [comment]
@Jimmyscene it looks like this PR fixes it https://github.com/eclipse/che/pull/10747. Thanks for reporting a bug
