### ISSUE TITLE
Permission problems after resolve factory with Theia.

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#10749]
### Description
When I create a workspace with one theia machine and a java machine from that [workspace url](https://gist.githubusercontent.com/olexii4/99aa676393255e70e03f70b0cafe5bde/raw/39c50e5501ce657e516a21ca9ead2f58e6d740d9/gistfile1.txt) and try to run a command,
the command is failing because of permission issue: theia is user root where java machine is user.

### Reproduction Steps

Just create a workspace from that [workspace url](https://gist.githubusercontent.com/olexii4/99aa676393255e70e03f70b0cafe5bde/raw/39c50e5501ce657e516a21ca9ead2f58e6d740d9/gistfile1.txt) and try to run a command.

**OS and version:**    

Che version: `6.10.0-SNAPSHOT`
Theia image: `olexii4dockerid/che-theia:0.3.12-nightly`

**Comment by skabashnyuk** [comment]
can you provide your factory.json or workspace.json?

**Comment by eivantsov** [comment]
@olexii4 as far as I understand the problem comes from having two different users in Theia and java image (Theia image is run as root). So, when `/projects` volume is shared root permissions are propagated to a Java machine volume, and as a result, user cannot write to it.

This refers to Docker infra only. There should not be such a problem on OpenShift infra with an arbitrary user.

**Comment by olexii4** [comment]
@eivantsov  Thanks a lot.

`
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "theia": {
          "attributes": {},
          "servers": {
            "theia": {
              "attributes": {
                "type": "ide"
              },
              "port": "3000",
              "protocol": "http"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {
            "CHE_MACHINE_NAME": "theia"
          }
        },
        "terminal": {
          "attributes": {
            "memoryLimitBytes": "2147483648"
          },
          "servers": {
            "terminal-exec": {
              "attributes": {
                "type": "terminal"
              },
              "port": "4444",
              "protocol": "ws"
            }
          },
          "volumes": {},
          "installers": [],
          "env": {
            "CHE_MACHINE_NAME": "terminal"
          }
        },
        "dev-machine": {
          "attributes": {},
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {
            "CHE_MACHINE_NAME": "dev-machine"
          }
        }
      },
      "recipe": {
        "type": "compose",
        "content": "services:\n theia:\n  image: 'olexii4dockerid/che-theia:0.3.12-nightly'\n  mem_limit: 1073741824\n dev-machine:\n  image: 'eclipse/ubuntu_jdk8'\n  mem_limit: 2147483648\n  depends_on:\n   - theia\n terminal:\n  image: 'olexii4dockerid/machine-exec:latest'\n  mem_limit: 2147483648\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [
    {
      "links": [],
      "name": "console-java-simple",
      "attributes": {
        "language": [
          "java"
        ]
      },
      "type": "maven",
      "source": {
        "location": "https://github.com/che-samples/console-java-simple.git",
        "type": "git",
        "parameters": {}
      },
      "path": "/console-java-simple",
      "description": "A hello world Java application.",
      "problems": [],
      "mixins": []
    }
  ],
  "name": "wksp-xonk",
  "commands": [
    {
      "commandLine": "mvn -f console-java-simple clean install",
      "name": "console-java-simple:build",
      "attributes": {
        "machineName": "dev-machine",
        "previewUrl": "",
        "goal": "Build"
      },
      "type": "mvn"
    },
    {
      "commandLine": "mvn -f console-java-simple clean install \njava -jar console-java-simple/target/*.jar",
      "name": "console-java-simple:run",
      "attributes": {
        "goal": "Run",
        "previewUrl": ""
      },
      "type": "mvn"
    },
    {
      "commandLine": "sed -i 's/\\*/\\*\\*\\*/g' console-java-simple/README.md",
      "name": "console-java-simple:replace",
      "attributes": {
        "machineName": "dev-machine",
        "previewUrl": "",
        "goal": "Common"
      },
      "type": "custom"
    },
    {
      "commandLine": "git --git-dir console-java-simple/.git --work-tree console-java-simple reset --hard HEAD",
      "name": "console-java-simple:git-reset",
      "attributes": {
        "machineName": "dev-machine",
        "previewUrl": "",
        "goal": "Common"
      },
      "type": "custom"
    }
  ],
  "links": []
}
`

**Comment by eivantsov** [comment]
A quick fix would be adding a user with uid 1000 in Theia image

**Comment by sunix** [comment]
maybe related to https://github.com/eclipse/che/issues/10756

**Comment by eivantsov** [comment]
@sunix it does not look like it

It's weird that a root user cannot access a file owned by a root.
