### ISSUE TITLE
Create workspace faild offline

### ISSUE THREAD

**Issue by zeyuanpinghe** [eclipse-che/che#10742]
I want to create workspace on che which deploy on openshift.
 And workspace pod is running,But the pages is not workfine,
 a few minutes later,it show me an error :"Server 'terminal' in machine 'dev-machine' not available".
  openshift: V3.9.0
  k8s: 1.9.1
  docker: 1.13.1
  che:6.9.0
 
Any one can help me ?

**Comment by eivantsov** [comment]
@kingkeivn the title of the issue says smth about offline mode? Can you elaborate?

**Comment by eivantsov** [comment]
```
ERROR:Installer org.eclipse.che.ws-agent error from machine=dev-machine owner=che env=default workspace=workspacew8cgifzdhc5kqc5m text=Debugger failed to attach:handshake failed-connection prematurally closed
```

You can disregard this error. It looks like Che server cannot verify the agent is running. It can happen because of no connectivity.

**Comment by kingkeivn** [comment]
@eivantsov 
THen create workspace failed .has no other error.
I have exactly the same cluster on system which can be connected.
On this system  create workspace success,And it did not have this error.
And in path /projects/che-logs-dockerimage ,
I see three files:
bootstrapper,ws-agent,exec-agent

**Comment by kingkeivn** [comment]
I can not understand what happening with this offline system.

**Comment by kingkeivn** [comment]
Maybe DNS error

**Comment by kingkeivn** [comment]
@eivantsov 
Hello,I resolve it by modify config in dnsmasq.   “/etc/dnsmasq.conf  insert 'address=/openshiftmasternodename/masterip'   like this 'address=/node4/101.8.174'”  
This is a Network error.
I got this error from che-host/api/workspace/workspacepodID
