### ISSUE TITLE
Add a "Plugin Registry API" to retrieve the list of plugins

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10745]
### Description
Since now metha.yaml are served by apache and we don't want to introduce some API server
we decided to create index.json file with a list of all existed plugins and editors.

**Comment by skabashnyuk** [comment]
@garagatyi @ashumilova @evidolob 
are you ok with such content of index.json

```json
[
  {
    "name": "che-dummy-plugin",
    "version": "0.0.1"
  },
  {
    "name": "che-editor-theia",
    "version": "1.0.0"
  },
  {
    "name": "che-service-plugin",
    "version": "0.0.1"
  }
]
```

**Comment by benoitf** [comment]
I would say that the type is missing. (Che plugin or che editor)

**Comment by garagatyi** [comment]
Yes, you are right. I created an issue for that https://github.com/eclipse/che/issues/10781
