### ISSUE TITLE
Intellij GWT Debug Error

### ISSUE THREAD

**Issue by village-way** [eclipse-che/che#10753]
### Description
I want to debug IDE Extensions by follow this workflow, https://github.com/eclipse/che/wiki/Development-Workflow#debugging-che-ide-extensions

after many time attempt， i still get this error 
![image](https://user-images.githubusercontent.com/11625846/44031593-102784a6-9f37-11e8-80b3-05cf7152491f.png)
 
i look up some similar in the issues, but still find an solution.

### Here is my configuration

![image](https://user-images.githubusercontent.com/11625846/44031658-3f7ffc24-9f37-11e8-9b5c-f58f33a74a98.png)

![image](https://user-images.githubusercontent.com/11625846/44031680-5362c488-9f37-11e8-87d9-98feae95d9d2.png)

![image](https://user-images.githubusercontent.com/11625846/44031693-5bd63bea-9f37-11e8-9477-9514b6d65e94.png)

![image](https://user-images.githubusercontent.com/11625846/44031706-67691950-9f37-11e8-9457-76c70bac375e.png)

**OS and version:**    
macos 10.12.6
jdk 1.8
maven 3.5.0
gwt 2.8.2

**Diagnostics:** 

this is my start command
`docker run -it -e CHE_HOST=192.168.65.3 -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /Users/devine/Downloads/webide-data:/data -v /Volumes/Data/IdeaProjects/WebIDE:/repo eclipse/che start --debug`
this is my workspace page

![image](https://user-images.githubusercontent.com/11625846/44032110-c642bebc-9f38-11e8-861c-8c8f45fbf979.png)

**Comment by eivantsov** [comment]
@HiDevine here's more accurate docs https://www.eclipse.org/che/docs/ide-extensions-gwt.html#debugging-with-super-devmode

**Comment by HiDevine** [comment]
@eivantsov 
according to the docs you provided, i execute this command
`mvn gwt:codeserver -pl :che-ide-gwt-app -am -Dmaven.main.skip -Dmaven.resources.skip -Dche.dto.skip -Dskip-enforce -Dskip-validate-sources` 
this is the result 
![image](https://user-images.githubusercontent.com/11625846/44066988-cd820756-9fa5-11e8-9af6-4ebcd1ce9a92.png)

![image](https://user-images.githubusercontent.com/11625846/44066996-db5d83aa-9fa5-11e8-8fa9-10c49f9578e3.png)

![image](https://user-images.githubusercontent.com/11625846/44067005-ebff9aea-9fa5-11e8-9aa8-dd87ceae0626.png)

what do next, can i debug in the intellij 

![image](https://user-images.githubusercontent.com/11625846/44067047-161ce800-9fa6-11e8-990e-8c516ff63c31.png)

**Comment by HiDevine** [comment]
i can debug ide extension in chrome dev tool now, but i still can not debug in the intellij. 
i can also see the change result, after compile the source.

**Comment by eivantsov** [comment]
In Chrome only

**Comment by HiDevine** [comment]
Thanks for you great help.
hope one day, i can debug in the intellij.
you can close this question.
