### ISSUE TITLE
Add or Import Project and GitHub and "Connect your github fails with 404

### ISSUE THREAD

**Issue by vorburger** [eclipse-che/che#10758]
In version 6.9.0, when you Create a New Workspace and Add or Import Project and GitHub and "Connect your github (should be 'GitHub' BTW) account" then you get a pop-up with a 404 from github.com for this URL:

https://github.com/login/oauth/authorize?client_id=changeme&response_type=code&scope=user,repo,write:public_key&state=oauth_provider%3Dgithub%26scope%3Duser,repo,write:public_key%26userId%3Dche%26redirect_after_login%3Dhttp://che-mini-che.192.168.42.231.nip.io/dashboard/gitHubCallback.html

**Comment by vorburger** [comment]
FYI I had already tried this back in Che version 6.3.0 where it was also broken (and, likely, since). The 6.9.0 seems to be the latest release - and it's what I got with https://github.com/minishift/minishift-addons/tree/master/add-ons/che.

**Comment by eivantsov** [comment]
@vorburger what are steps to reproduce? Deploy single user Che to MiniShift and provide GitHub clientID and secret?

Did you register an app on GitHub side?

**Comment by vorburger** [comment]
@eivantsov using https://github.com/minishift/minishift/tree/master/addons/che and have not provided any GitHub clientID and secret nor registered an app on the GitHub side ... seeing `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` only now - I guess one needs to set those, and then it works? :smile: Sorry. Let's close this, and I'll try with that, and re-open if still NOK.

**Comment by eivantsov** [comment]
@vorburger yes, https://www.eclipse.org/che/docs/version-control.html#github-oauth
