### ISSUE TITLE
Regular(ldap) users cannot start/connect to a workspace

### ISSUE THREAD

**Issue by donenocode** [eclipse-che/che#10770]
I have an issue where 'regular'(ldap) users cannot start and connect to a workspace.

My Setup:
Docker (on an Ubuntu 16.04LTS VM (4cpu 20GB RAM 300GB Disk)) local)
Eclipse Che 6.9.0
A.D. configured in Keycloak

The steps to reproduce this are:
1. Login to Che with a 'regular' user account
2. Add a new workspace (in this case using the 'PHP' stack)
3. Open IDE

The window changes to the IDE window with a 'loading..' bar but does not complete.
I can see the container gets started with 'docker ps' and can connect to it manually with 'docker exec'.

If I try the above steps as the Che admin user it works fine.
Another interesting thing is if the Che admin starts a workspace and shares it then the 'regular' user can connect to that just fine also!

The issue appears to be that the user cannot start and connect to her own workspace.

I tried to look for some logs and do some debugging:
I try to curl che-host:8080 inside the container and it works ok.
I've looked at the bootstrap log on this container and a working container that admin started and they are identical.
I've looked at the logs from the che container (docker log che) but it only says:
  'Starting workspace 'some-test' with id 'workspace....' by user 'someuser'
  then (around 7 minutes later):
  'Workspace 'some-test' with id 'workspace...' start failed

I also tried setting up a complete new setup on a different server and I get the same results..

Im not sure where else to look for logs or debug info.
I looked at the section in the documentation about workspace starting failures but this didnt not help.

Thanks.

**Comment by eivantsov** [comment]
Can you provide server logs?

**Comment by donenocode** [comment]
Thanks for the response.
The only log I seem to be able to find is from the che-server container (see below).

I notice that there is an error when admin starts a workspace but it works anyway!

I understand that this may be a network issue, but it wasn't my first thought because the Che admin account can start workspaces (via the same browser on the same workstation as the user who cannot start workspaces).
And when the admin does start a workspace, if she shares it the user can also access it just fine..?


**This is from a failed start by a user**
_(via: docker logs che):_
`2018-08-14 14:17:24,550[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'test-org/test-this' with id 'workspace0000000000000000' created by user 'someuser'
2018-08-14 14:17:27,837[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 330]   - Starting workspace 'test-org/test-this' with id 'workspace0000000000000000' by user 'someuser'
2018-08-14 14:27:30,762[aceSharedPool-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 391]   - Workspace 'test-org:test-this' with id 'workspace0000000000000000' start failed`

_(in the browser window):_
`[DOCKER] latest: Pulling from eclipse/php
[DOCKER] Digest: sha256......
[DOCKER] Status: Image is up to date for eclipse/php:latest
<Much Time Passes>
Bootstraping of machine dev-machine reached timeout`



**This is from a successful start by the admin**
_(via: docker logs che):_
`2018-08-14 14:30:11,366[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'test-org/another-test' with id 'workspace0000000000000000' created by user 'admin'
2018-08-14 14:30:12,786[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 330]   - Starting workspace 'test-org/another-test' with id 'workspace0000000000000000' by user 'admin'
2018-08-14 14:30:24,160[equestProcessor]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`00000000-0000-0000-0000-000000000000` env=`default` workspace=`workspace0000000000000000` text=`Debugger failed to attach: handshake failed - connection prematurally closed` time=`2018-08-14T14:30:24.16018707Z`
2018-08-14 14:30:27,808[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 372]   - Workspace 'test-org:another-test' with id 'workspace0000000000000000' started by user 'admin'`



_(in the browser window):_
`[DOCKER] latest: Pulling from eclipse/php
[DOCKER] Digest: sha256......
[DOCKER] Status: Image is up to date for eclipse/php:latest
IDE is loaded successfully`

**Comment by eivantsov** [comment]
@donenocode indeed if admin user can start workspaces, networking is just fine.

Do workspaces fail to start when attempting to start them in an organization? Can users create own individual workspaces and start them?

**Comment by donenocode** [comment]
Users do not appear to be able to start workspaces inside or outside of an organisation.
I tried on a completely new setup and connected to a different A.D. setup just incase but this is the same result.

The admin **can** start workspaces inside or outside of an organisation.

The only difference I can see is the users are LDAP users and the Che admin user is created on keycloak directly. I will create a user account on keycloak directly and see if this works for creating workspaces (but this will have to wait until tomorrow!)

**Comment by eivantsov** [comment]
What you can also try, is doing exec into a workspace container after it is created and run `ps ax` there to see if bootstrapping has ever started.

**Comment by donenocode** [comment]
So this morning I created a test user account directly in Keycloak and this works just fine!
It appears the issue is somewhere in the LDAP settings, but im not sure how this can be?!

LDAP users can login fine, and they can create a workspace, they can even connect to a workspace some other user has started. They just cannot successfully start their own workspace??

I did a docker exec on a workspace that the LDAP user tries to start it only ever has the _SSHD_ running (and the log tail).
I did the same on a workspace the admin user created and I can clearly see the bootstrapping.

Im not sure where to look for any more logs.

**Comment by donenocode** [comment]
I may have found something interesting..

While investigating various settings, I noticed that the LDAP user source configured in keycloak does not have a 'First Name' mapper. None of my users when synced had their first name set.
I dismissed this as I cant see why it would matter, but when nothing else helped I decided to look into it..
I created a mapper manually in the keycloak LDAP config and re-synced the users.

When I do that the user can start a workspace successfully!

I have changed plenty of settings upto this point so I am trying to work out which ones helped, but so far I think 'First Name' is the issue!

I am going to roll back my setup and start from scratch, and change only the minimum of settings and will report back..


_Also worth noting I have also changed a setting on the Che realm settings in keycloak, I have disabled the 'Login with email' option, which may have helped._

**Comment by donenocode** [comment]
Further to this I have changed the setting of the LDAP provider to enable 'Import Users'.
This changes the user ID in keycloak and allows creation of workspaces.

I would rather not use this mode but it appears to solve the issue.

But still a call to the API **'/api/users/find?name=someuser'** will not return the details of any user that has not logged in yet. Can this behaviour be changed? Is there a way to inform Che that these users can be used?
The reason this is important is that I would ideally like to use automation to pre-create workspaces for users who may not have logged in yet.

**Comment by donenocode** [comment]
Thanks for the clarification on this.
