### ISSUE TITLE
Incorporate Eclipse Collections into Che

### ISSUE THREAD

**Issue by itohro** [eclipse-che/che#1078]
Hi team.

I'm one of the committers of [Eclipse Collections](https://www.eclipse.org/collections/) project. I was looking into your project code and wondering if you are interested in incorporating Eclipse Collections into your code base. 
- Took a heap dump of Che and its 3rd and 4th largest memory usages are coming from HashMap$Node and HashMap$Node[]. This memory footprint could be significantly reduced by replacing HashMap with UnifiedMap, and HashSet with UnifiedSet from [Eclipse Collections](https://www.eclipse.org/collections/#memory). 
- There are number of [streams/Collectors usages](https://github.com/eclipse/che/search?utf8=%E2%9C%93&q=Collectors) in code that can be simplified by leveraging our [rich APIs](https://www.eclipse.org/collections/#concept). 

We (Eclipse Collections team) are happy to take up the conversion and submit a pull request if you agree adding Eclipse Collections as a dependency to your project. 

Please let us know your thoughts!

**Comment by TylerJewell** [comment]
Hello @itohro.  We were able to discuss your very interesting idea on this week's Che roadmap planning sessions.  

There were a couple of initial thoughts.  First, we have about 50 contributors to Eclipse Che and there are 100s of references to the standard HashMap in our product.  So changing the collection would require having a strategy for how it would be maintained along with a training period for the engineers. Given that training and education can take awhile, it may not be a good idea to do a wholesale transformation.   Second, the initial hash scans from our tests don't show a lot of consumption from our HashMaps.  It would be helpful if you could provide some performance metrics on what you are seeing and help us assess the hot spots of poor performance.

I think we could then look at targeting a couple hot spots where the biggest gains can be had, which are also isolated in the core stack.  We can then educate a smaller group of engineers, measure the gains, and then look at what would be involved with a broader set of changes.

What do you think?

**Comment by itohro** [comment]
Thanks @TylerJewell for discussing this! We really appreciate your consideration.

I actually have to take back one of my previous analysis. It was a bit premature performance analysis indeed.  Many of the HashMap references were actually coming from Tomcat, not directly referenced from Che code, so my first statement may not hold true. 

I'd like to understand the Che architecture itself more to perform better analysis (it's actually fun to learn Che's architecture BTW:) ). Especially I'm struggling to figure out how each workspace is spawned into docker container, and how I could connect to the JVM on the containers.

Is this issue a good place to ask general Che architecture question, or do you recommend I post my questions to any other forum?

**Comment by TylerJewell** [comment]
It's ok to ask them here.

We run a 2nd JVM inside of each container. You will need to SSH into the container and then analyze the JVM that is running within that container.   Think of Che as a tripod - browser + che server + workspace.  Each are a process that interconnect to the others.  So the che server and workspace each have separate JVMs.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
