### ISSUE TITLE
Che AWS ECR configuration issue

### ISSUE THREAD

**Issue by eoperez** [eclipse-che/che#10796]
### Description
I'm getting an error: 
Can't create machine from image. Cause: Error response from docker API, status: 500, message: Get https://213550595639.dkr.ecr.us-east-1.amazonaws.com/v2/cstp/manifests/latest: no basic auth credentials

when trying to create a workspace from a stack that reference an image hosted in AWS ECR

### Reproduction Steps
Installed Eclipse Che multi user: eclipse/che-server:6.9.0 running on docker with:
`
sudo docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=<host> -e "CHE_PORT=80" -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start
`

che.env
`
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ID=213550595639
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_REGION=us-east-1
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ACCESS__KEY__ID=***************
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_SECRET__ACCESS__KEY=****************
`

I created stack to access my image:
`
....
"workspaceConfig": {
      "environments": {
        "default": {
          "recipe": {
            "type": "dockerimage",
            "content": "213550595639.dkr.ecr.us-east-1.amazonaws.com/cstp:latest"
          },
....
`

**OS and version:**    
Linux Ubuntu SMP Wed May 16 15:22:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

How can I validate that Che is taking the configuration provided in che.env?

**Comment by eivantsov** [comment]
@eoperez i think you can get envs and props that Che server uses only through debugging.

I suspect that this feature may be broken since it hasn't been validated for quite a long time.

**Comment by eoperez** [comment]
@eivantsov - thanks! I'll play with the configuration and debug to see what I can find, however should this be marked for investigation instead of just a question. I'm happy to bring more information as needed because this feature is critical for my implementation.

**Comment by eivantsov** [comment]
@eoperez yes, the feature is most likely broken as it hasn't been tested in quite a while
