### ISSUE TITLE
JDT.LS: fix selenium tests in org.eclipse.che.selenium.intelligencecommand

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#10803]

**Comment by azatsarynnyy** [comment]
The only one test that is failed is `org.eclipse.che.selenium.intelligencecommand.CheckIntelligenceCommandFromToolbarTest`.
I've investigated the reasons and described it [here](https://github.com/eclipse/che/issues/10809#issuecomment-415381540).
