### ISSUE TITLE
Investigation of Openshift API to provide the solution for exec work on it

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#10813]
The implementation of [issue](https://github.com/eclipse/che/issues/10314) requires some strategy to be defined. So the current task includes investigation and analyzing of existing Openshift APIs, how commands could be executed with the use of it.

**Comment by AndrienkoAleksandr** [comment]
Investigation is completed some time ago, working on https://github.com/eclipse/che/issues/10314
