### ISSUE TITLE
che-theia-task-extension: rewrite from scratch classes in https://github.com/eclipse/che-theia-task-plugin/tree/master/che-theia-task-extension/src/node/messaging

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#10822]
### Description
rewrite from scratch (without copying them) class from https://github.com/eclipse/che-theia-task-plugin/tree/master/che-theia-task-extension/src/node/messaging

**Comment by azatsarynnyy** [comment]
closed by https://github.com/eclipse/che-theia-task-plugin/pull/6
