### ISSUE TITLE
Create README.md to eclipse/che-plugin-registry

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10834]
### Description
Add README.md to eclipse/che-plugin-registry repository.
Describe the purpose and usage of this service.

**Comment by garagatyi** [comment]
Please, add a description of how to get a list of plugins (index.json), how to get meta.yaml of a plugin from this list.

**Comment by garagatyi** [comment]
@skabashnyuk there is no explanation of how to get list of plugins, how to construct a link to download plugin meta.  I would consider reopening this issue to address that.
