### ISSUE TITLE
Plugin registry build process should ensure that meta.yaml content is aligned with its location 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10839]
### Description
Plugin registry build process should ensure that meta.yaml content is aligned with its location.
For now, it is possible that ID in meta.yaml differs from the path to the file which leads to a broker plugin.
To validate:
- ID field
- Version field
- Path of a meta.yaml

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
in case if path and id are not matched what should happen?
