### ISSUE TITLE
JSON_RPC framework doesn't support deserialization of fields with names not compatible with java syntax 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10841]
### Description
For example in Walking skeleton, we have field names such as `editor-commands`, `public`.
We can add an ability to use some annotations to serialize/deserialize in a custom way or we can add an ability to use some custom deserializer to the part of the JSON_RPC framework that works with pretty object transmitted by the framework. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
I think you can specify `@JsonFieldName` to make object field name and json field name different. Example of usage you can find in tests of `api-dto` module: https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/core/che-core-api-dto/src/test/java/org/eclipse/che/dto/definitions/DtoWithFieldNames.java#L35-L36

**Comment by garagatyi** [comment]
I forgot that we have got this feature. Thanks for reminding! 

And new Github feature of adding code snippet is awesome!
