### ISSUE TITLE
Consider the process of resolving dependencies as activity of the workspace

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#10853]
### Description
* _When a user imports a big project and resolves dependencies, it can take a very long time. The resolving of dependencies is a background process, and in this case the workspace may be stopped by timeout_
* _We should consider the process of resolving dependencies as workspace activity and find the  solution for it_

**Che version**: 6.10.0
**Che install:** OCP/Docker

**Additional information:**
* Related closed issue: #10560
* See the attachment:

**screenshot:**

![unexpected-stop-ws-when-resolve-dependencies](https://user-images.githubusercontent.com/5408906/43308039-d038bf9c-9188-11e8-8b13-2b5195b80a30.png)

**Comment by vkuznyetsov** [comment]
not actual
