### ISSUE TITLE
How does Eclipse Che realize the automatic UI test?

### ISSUE THREAD

**Issue by ktdjun** [eclipse-che/che#10860]
I'd like to create an automatic UI test that manipulates the screen of "Multi-User Che".
How does Eclipse Che realize the automatic UI test?

Although Selenium's test code has been released to GitHub,
Can I also test the operation of WebSocket communication like the following?

   1. Command input and response to Terminal
   2. Own coding and saving to the file (synchronization with the server)

If you have a good method, I will be saved if you give me advice.

**Comment by eivantsov** [comment]
@ktdjun here are some docs for selenium https://github.com/eclipse/che-docs/blob/Selenium/src/main/_docs/setup/setup-selenium.md

I think there are tests that write smth to terminal https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/TerminalTypingTest.java

**Comment by ktdjun** [comment]
@eivantsov 
Thank you for your reply.
It was my shortage of confirmation. I will confirm the information you presented.
