### ISSUE TITLE
cant access WSagent

### ISSUE THREAD

**Issue by itaimalek** [eclipse-che/che#1087]
I'm trying to get to my WSagent, I get this error:
![image](https://cloud.githubusercontent.com/assets/8522568/14654035/723c9f44-0684-11e6-83cc-0c2c2b9947d0.png)

**Comment by ghost** [comment]
Swagger isn't deployed with a workspace agent tomcat.

**Comment by itaimalek** [comment]
how do I enable it?
I cant find instructions for it...

**Comment by ghost** [comment]
It isn't part of a workspace agent now, there are no instructions on how to do it at the moment.

**Comment by itaimalek** [comment]
ok, thanks

**Comment by ghost** [comment]
Sorry for misinforming you. There's swagger in ws-agent. Give me some time to provide you with instructions on how to use it.

**Comment by TylerJewell** [comment]
Did you mean accessing swagger like this?   https://eclipse-che.readme.io/docs/rest-api

**Comment by itaimalek** [comment]
Yes, exactly

**Comment by ghost** [comment]
So, here's the URL - `http://localhost:${PORT}/api/ext/docs/swagger.json` where `${PORT}` is the port mapped to ws-agent (you can find it in the servers tab, Operations perspective).

**Comment by ghost** [comment]
@itaimalek did it work for you?

**Comment by ghost** [comment]
Closing the issue. Feel free to reopen if the offered solution did not work for you.
