### ISSUE TITLE
Clean Up Java/Maven Leftovers

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10872]
We have some leftovers from the old Java support in the jdt.ls branch, for example the Maven IDE stuff (che-plugin-maven-ide) or some usages of eclipse projects (org.eclipse.resources). We need to go over the che project and remove those references. 
For finding references to eclipse projects, starting in che-parent and removing the version numbers would reveal where they are used in a build.

**Comment by sunix** [comment]
Looks like fixed
