### ISSUE TITLE
Project tree items are not updated with VCS status colors after changes in the terminal

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#10875]
### Description
 
Project explorer shows outdated VCS status colors on its item if changes were done but the project explorer tree was collapsed and the file wasn't opened in the editor.

### Reproduction Steps

1. Create a Git project
2. Do not open any files. Expand and collapse back the project's directory in the project explorer.
3. Edit any file from the project's root directory in the terminal e.g. with the help of mcedit.
4. Expand the project's root directory in the project explorer.
WRONG: The file is not colored as modified. It will be colored in blue after the page refresh.
Expected: The file must be colored in blue (edited).

**OS and version:**    
Version:     6.10.0-SNAPSHOT 
**Diagnostics:**

**Comment by bencaldwell** [comment]
It would also be useful if the changes were visible on the project root directory in project explorer e.g:
1. Collapse project root directory in project explorer
2. Make changes to project files in terminal 
3. The project name changes color to blue to indicate changed files inside
