### ISSUE TITLE
No 'Access-Control-Allow-Origin' despite addition to Keycloak client Web origins

### ISSUE THREAD

**Issue by nickarls** [eclipse-che/che#10887]
### Description

I am running a multi-user Che in docker on a host without a DNS entry. The docker host is known as "dev" (through /etc/hosts) but I have to use the IP of the host as CHE_HOST since the bootstrap container fails its browser connectivity checks if I use the name since the "dev" is not known inside that container. I'm accessing Che from my client as http://dev:8080 (and dev also resolves on my client through a hosts definition) but when I log in I get stuck on the "dashboard loading icon" and my console complains 

Failed to load http://<IP>:5050/auth/realms/che/protocol/openid-connect/token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dev:8080' is therefore not allowed access.

I have added http://dev:8080/* to both the keycloak che-public client valid redirect urls and  web origins.

If I access http://<IP>:8080, everything works

Thanks in advance,
  Nik

**Comment by skabashnyuk** [comment]
Can you make your question more concrete?

**Comment by nickarls** [comment]
After using an IP as CHE_HOST during installation, what further configuration is required so that you can access Che using a host name?

**Comment by nickarls** [comment]
One would think that this situation is equivalent with che being installed on a host named "reallyfancydevmachinewithlongname" and someone calls it "dev" in their local resolver. Shouldn't it be enough to list "dev" in the Keycloak Web origins?

**Comment by skabashnyuk** [comment]
I'm not sure that it will work in that fake environment. Are you able to use real dns names or IP?

**Comment by skabashnyuk** [comment]
To be honest it is not tested that way.  In case if you find a way to work around it, we will be happy to add your instructions to the docs.

**Comment by nickarls** [comment]
OK, I'll use IP for now and keep this as a background project
