### ISSUE TITLE
How can I provide custom che properties outside the docker?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#109]
I install eclipse-che via docker, I want to provide custom properties from outside docker, which file do I need to mount? 

I see there is `/home/user/che-3.13.4.2/webapps/che/WEB-INF/classes/codenvy/che.properties` inside the docker, is it correct file I need to mount with?

**Comment by ghost** [comment]
Hello,

Yes, this file is used by default, but in the image, we have exported CHE_LOCAL_CONF_DIR=/home/user/.che and placed properties file into that directory.

So, you need to mount /home/user/.che/che.properties

**Comment by freewind** [comment]
@eivantsov Thanks!

**Comment by gonella** [comment]
Hi,

I'm trying to change DOCKER_HOST_IP= 172.17.0.1. It is always getting this value. Is there any to change? 

I already tried:
1.  Changing /home/user/.che/che.properties
   machine.docker.local_node_host=IP1
2.  Changing /home/user/che/conf/che.properties
   machine.docker.local_node_host=IP1

3.
docker run --rm -t -e CHE_HOST_IP="IP1" -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start

For both attempts above 1 and 2 don't work, number 3 work, but change only: 

INFO: ECLIPSE CHE: Use: http://IP1:8080
INFO: ECLIPSE CHE: API: http://IP1:8080/swagger

If I call "che info" I can still see old entries point to  172.17.0.1. 

Any clue?

**Comment by TylerJewell** [comment]
Why are you trying to change DOCKER_HOST_IP?

**Comment by gonella** [comment]
I'm trying to follow https://eclipse-che.readme.io/docs/networking#native-process-for-che-native-docker-for-workspace. Make "docker-ip" and "workspace-ip" have external access and not 172.17.0.1.

**Comment by TylerJewell** [comment]
Are we looking at the same docs - I think you maybe have some old links.  Are you studying this page?  

https://eclipse-che.readme.io/docs/networking

It's not clear why you should set docker-ip to be external, that is an internal system that only Che uses.  the only thing you should have to configure is CHE_HOST_IP to make workspaces externally accessible.

**Comment by gonella** [comment]
From the same link, I have highlight in bold. It is saying both ip must be reachable by the browser.

"The browser client initiates communication with the Che server by connecting to che-ip. **This IP address must be accessible by your browser clients.** Internally, Che runs on Tomcat which is bound to port 8080. This port can be altered with Configuration.

When a user creates a workspace, the Che server connects to the Docker daemon at docker-ip and uses the daemon to launch a new set of containers that will power the workspace. These workspace containers will have a Docker-configured IP address, workspace-ip. **The workspace-ip must also be reachable by your browser host.**"

I'm facing same issues related others, I can't start the workspace. The ports are opened. Any idea?

2016-09-16 19:32:25,349[nio-4401-exec-1]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.
2016-09-16 19:32:25,349[nio-4401-exec-2]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.
2016-09-16 19:33:04,899[ted-scheduler-0]  [ERROR] [.w.s.WsAgentAnalyticsAddresser 37]   - Failed to send agent analytics
java.net.UnknownHostException: install.codenvycorp.com

**Comment by TylerJewell** [comment]
We hvae some posting guidelines.  Please create a new GitHub issue.  You need to provide a step by step set of instructions of what you configured.  You need to provide all of your host, OS, docker configuration details.

You should only need to:
1. Get docker installed
2. Get the Che CLI
3. export CHE_HOST_IP=<external-ip>
4. che start

If that doesn't work properly, then post all logs and explanation of what you see including output of chrome dev console.  Thx!
