### ISSUE TITLE
Allow Git Committer details to be mapped from Keycloak user details

### ISSUE THREAD

**Issue by david-martin** [eclipse-che/che#10909]
### Description
Allow Git Committer details to be mapped from Keycloak user details.
This will avoid the user having to set them manually in Che (Profile > Preferences > Git > Committer) before they can commit and push code to their imported repo.

### Reproduction Steps

* When setup with Keycloak (& a github identity provider), login to Che.
* Authorize Che to your Github account (Profile > Preferences > SSH > VCS > Github icon)
* Import a project from Github
* Modify a file and commit/push it back (Git > Commit)
* The below error is shown

![image](https://user-images.githubusercontent.com/878251/44587866-1eef1a80-a7ac-11e8-8262-c103563c3049.png)

**OS and version:**    

**Diagnostics:** 

Would it be possible to set the Git user name & email based on the user details from Keycloak (JWT?)

**Comment by skabashnyuk** [comment]
@david-martin can you elaborate a bit more about which exactly Keycloak user details you are talking about.

**Comment by david-martin** [comment]
@skabashnyuk If I have my email address & first name set in my Keycloak account, they will get mapped to the Git user name and email config in Che.

**Comment by skabashnyuk** [comment]
@david-martin What I should do to set up email address & first name in my Keycloak account?
Do I need to setup it manually?  Or create Github IDP mapper
<img width="822" alt="2018-08-27 12 44 12" src="https://user-images.githubusercontent.com/1614429/44653289-fc9d0d00-a9f6-11e8-8d07-681d09554211.png">

**Comment by david-martin** [comment]
@skabashnyuk I would say it could be set manually, maybe when the user was created in that Keycloak (Or automatically if users are federated to ldap or some other user system).
i.e. they show up in below screen before the user even tries to login to Che for the first time

![image](https://user-images.githubusercontent.com/878251/44654025-3fa3b400-a9e8-11e8-86e8-1b6b3f07c1a1.png)

After they login to Che, Che is able to read user details from Keycloak (from a JWT maybe?)

**Comment by skabashnyuk** [comment]
@david-martin So this has no relation to Github. You want to map Keycalok email to gitcommiter email and KK first and last name to gitcommiter name?

**Comment by david-martin** [comment]
@skabashnyuk Yes, exactly.
Apologies for any confusion about github

**Comment by skabashnyuk** [comment]
OK. I may rephrase this issue as follows.
In ```LocalGitUserResolver``` implementation of ```GitUserResolver``` add fallback logic.
git.committer.name - to username
git.committer.email - to user mail

**Comment by david-martin** [comment]
@skabashnyuk Sure, that sounds reasonable.

**Comment by gorkem** [comment]
@vparfonov @skabashnyuk can you please see if you can take this on to the next sprint?

**Comment by skabashnyuk** [comment]
@gorkem yes sure.

**Comment by vinokurig** [comment]
Blocked by issue above

**Comment by gazarenkov** [comment]
@vinokurig to make sure - it will take default value (if empty) from user/email but it can be filled manually (as it is) as well, correct?

**Comment by vinokurig** [comment]
@gazarenkov sure, user will be able to change it in the preferences

**Comment by david-martin** [comment]
Thanks @vinokurig
