### ISSUE TITLE
Unexpected error in che-server pod logs during selenium test session on OpenShift infra

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#10903]
### Description
* During selenium test session we have defined unexpected errors like: ```Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table "che_sign_key_pair" violates foreign key constraint "fk_sign_workspace_id"
  Detail: Key (workspace_id)=(workspaceiodud1ga8xwrg7tr) is not present in table "workspace".
Error Code: 0
Call: INSERT INTO che_sign_key_pair (workspace_id, private_key, public_key) VALUES (?, ?, ?)
	bind => [3 parameters bound]```
This looks like we try to get token from a deleted workspace.  But i guess we should throw more informative information into exception in this case
**More details:** Openshift upstream,  [CI Job URL](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/ws/ocp_logs/che-server-pod.log)
**OS and version:**  Openshift multiuser,  upstream version, CI infrastructure

**Comment by ibuziuk** [comment]
@skabashnyuk @sleshchenko @mshaposhnik guys, after update on prod to 6.11.0 we have an enormous number of this logs kibabana (more than 105 000 thousand of entries and this figure keeps growing - the common number of log entries in kibana for this pod is 125 000). Any ideas how this might affect che-server functionality ? (not sure if it is related somehow but che-server pod has been restarted 4 times with OOMKilled after update)

**Comment by mshaposhnik** [comment]
@ibuziuk we're already merged the fix which will catch such kind of errors and produce more lightweight exception.  But the reason of such behavior is still not fully clean. We see that some ws-agent code is still running afters the WS itself is deleted. Investigation issue is https://github.com/eclipse/che/issues/11257

**Comment by mshaposhnik** [comment]
We fixed the DB ex, for futher investigations there is https://github.com/eclipse/che/issues/11257
