### ISSUE TITLE
Automated way to trust certs in a stack

### ISSUE THREAD

**Issue by david-martin** [eclipse-che/che#10910]
### Description

When running Che on OpenShift with self-signed certs, there are manual steps I need to do before I can launch a workspace and use it from my browser.

I can automate the creation of the certificate secret that Che Server looks for. That's OK.

However, the manual steps below are cumbersome and slow down the user experience when trying to get up and running.

* retrieve the openshift wildcard certificate
* build a custom container image that imports this certificate (need to do this once per stack that I intend to use)
* push the image somewhere the OpenShift cluster can pull from
* Create/Clone a stack and configure the dev-machine to use the custom image
* Lastly, I need to import the certificate into my browser (so the wss connection works)

### Reproduction Steps

See description

**OS and version:**    

**Diagnostics:** 

Paraphrased comment from @eivantsov:

> theoretically, before making the initial exec with curl, Che server can check of there's env variable with cert in it (Che server can inject it in every workspace container) and once found, add the cert as root cert and to Java trust store

I'm not sure how to get around the browser cert import in an automated way :/

**Comment by eivantsov** [comment]
@david-martin I don't think we can skip adding cert to browser.

As to some automation for workspace containers, I will try to post my thoughts and possible solutions
