### ISSUE TITLE
Project view is broken if Theia is used as IDE in a workspace

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10915]
### Description
Project view in a running workspace depends on Ws-agent APIs and opening it when Theia (or no IDE at all) is used shows a black screen.
We can remove this view completely or use just workspace config. We can also provide an error message when a workspace doesn't contain ws-agent.

### Reproduction Steps
1. Create a workspace with Theia and add a project to it
1. Go to UD view of the project

Expected:
An error about this feature not available for a workspace (we would have the same if no IDE is present in a workspace).
Actual:
Black screen:
![image](https://user-images.githubusercontent.com/1851863/44646160-cc4b7380-a9e2-11e8-94d6-ab742fa5ba12.png)

How it looks on a workspace with the ws-agent:
![image](https://user-images.githubusercontent.com/1851863/44646136-b9d13a00-a9e2-11e8-80cf-7712594b24fa.png)

**OS and version:**    

**Diagnostics:**

**Comment by ashumilova** [comment]
@slemeur maybe we could remove the project details view? 
Here is the information that it contains now:
![screenshot from 2019-01-15 13-10-04](https://user-images.githubusercontent.com/1611939/51176983-0bf9f580-18c7-11e9-8850-f68359311acb.png)
It allows only to edit the description and delete the project and those actions depend on wsagent API. 
When agent is not running we have following page:
![screenshot from 2019-01-15 13-13-35](https://user-images.githubusercontent.com/1611939/51177103-6430f780-18c7-11e9-9f74-aa123d7e5eb4.png)

No agent (in case of Theia IDE or any another except GWT one) - causes the bug described in the following issue. So to fix that we could:
option 1: Remove project details and keep only projects list with nearly the same data
option 2: Show message - there is no ws agent similar to "This project's workspace is not currently running."

I am +1 for option 1.

**Comment by AndrienkoAleksandr** [comment]
+1 For fires option

**Comment by slemeur** [comment]
+1 for option1
