### ISSUE TITLE
Recipe-stack based Workspace doesn't start

### ISSUE THREAD

**Issue by nickarls** [eclipse-che/che#10917]
### Description
I can create, start and open a quickstart-based workspace but new ones fail

### Reproduction Steps
Create a stack based on recipe

```
services:
  tomcat:
    image: tomcat

```
Create a workspace based on stack
Start workspace
Try to open workspace

a dialog appears "RuntimeException: wsagent server doesn't exist"

**OS and version:**    
CentOS Linux release 7.3.1611 (Core)
Latest che docker image
CHE_MULTIUSER=true
firewall opened for 32k-65k ports

**Diagnostics:** 
che and workspace logs show normal startup and nothing more at open failure

**Comment by nickarls** [comment]
I noticed that the "installers"-section was empty in the config so I tried adding the WS API but I get a 
"Process of installation 'org.eclipse.che.ws-agent' exit code is 0 but servers are not available"

**Comment by nickarls** [comment]
The config indicates that I don't have any servers. Am I to understand that the approach is to explicitly add a tomcat as a server?

**Comment by eivantsov** [comment]
@nickarls when adding a new stack you need to add Workspace API in the installers view.

**Comment by nickarls** [comment]
Looks like a case of Reading The Fine Manual, closing.
