### ISSUE TITLE
Process names in Processes list doubled after restarting workspace

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10927]
**Reproduction Steps:**
1. Create and start workspace through **Dashboard** based on **Java** stack with "**console-java-simple**" project. 
2. Select project in the **Project Explorer**.
3. Start "**console-java-simple:build**" command from project context menu and wait that build finished.
4. Restart this workspace
5. Start "**console-java-simple:build**" command from project context menu again.

**Expected result:**
There is only one "**console-java-simple:build**" process in the **Command Toolbar**.

**Actual result:**
There are two "**console-java-simple:build**" processes in the **Command Toolbar**(see screenshot 1). After closing "**console-java-simple:build**" console duplicated process still exists(see screenshot 2).
 
**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot 1**
![selection_099](https://user-images.githubusercontent.com/7760565/44660386-1bf46400-aa10-11e8-9a43-6dce34421073.png)

**Screenshot 2**
![selection_100](https://user-images.githubusercontent.com/7760565/44660394-1f87eb00-aa10-11e8-8cfb-c30f16210062.png)

**Comment by azatsarynnyy** [comment]
closed by https://github.com/eclipse/che/pull/11566
