### ISSUE TITLE
Keycloak registration calls from https to http

### ISSUE THREAD

**Issue by ctron** [eclipse-che/che#10924]
### Description

Setting up Che with Keycloak support, using HTTPS results in a call to HTTP when registering a new user.

### Reproduction Steps

* Setup Che on OKD with Keycloak and proper HTTPS
* Go to the Che URL
* Register a new user

At this point you can see in the HTML code of the registration form, that the form call goes to `http:` instead of either `https:` or simply `//`.

~~~html
<form id="kc-register-form" class="" action="http://keycloak-che.foo.bar/auth/realms/che/login-actions/registration?code=…&amp;execution=…&amp;client_id=che-public&amp;tab_id=…" method="post">
  <input type="text" readonly value="this is not a login form" style="display: none;">
  <input type="password" readonly value="this is not a login form" style="display: none;">
~~~

This will let the browser trigger a warning.

**OS and version:**    

* CentOS 7.5
* OKD 3.10
* Che 6.10

**Diagnostics:**

**Comment by ctron** [comment]
![image](https://user-images.githubusercontent.com/202474/44658305-9f0dbe00-aa00-11e8-9a8a-04e17203ea7b.png)

**Comment by ctron** [comment]
Ok, so that works for generating the proper URLs, but then Che fails with some token issues.

**Comment by ctron** [comment]
So after the change I ran into some weird token issues, complaining about "https:" not being "http:", but that did resolve after a restart of Che.

**Comment by eivantsov** [comment]
@ctron thanks. Opened a PR
