### ISSUE TITLE
Enabling "SSH" installer breaks workspace

### ISSUE THREAD

**Issue by ctron** [eclipse-che/che#10929]
### Description

Enabling the "SSH" installer on the "Java CentOS" stack breaks the workspace.

### Reproduction Steps

* Create workspace with "Java CentOS" stack
* Open
* Switch back to edit workspace settings
* Enable "SSH" installer
* Click on "Apply"
* Bang!

**OS and version:**    

* CentOS 7
* OKD 3.10
* Che 6.10

**Diagnostics:** 

~~~
pulling image "eclipse/centos_jdk8"
Successfully pulled image "eclipse/centos_jdk8"
Created container
Started container
Error: Failed to run the workspace: "Installation 'org.eclipse.che.ssh' failed, script exit code is 1"
~~~

**Comment by ctron** [comment]
It looks like the same is true for the "Java Ubuntu" stack:

~~~
pulling image "eclipse/ubuntu_jdk8"
Successfully pulled image "eclipse/ubuntu_jdk8"
Created container
Started container
Error: Failed to run the workspace: "Installation 'org.eclipse.che.ssh' failed, script exit code is 1"
~~~

**Comment by eivantsov** [comment]
@ctron this is expected behavior on OpenShift without anyuid. SSH installer starts sshd with sudo which isn;t possible in runtime on OpenShift unless anyuid is enabled.

**Comment by ctron** [comment]
I would never expect a completely broken workspace. So in that case I would suggest to no allow this option. Or at least to give out a big fat warning.

**Comment by eivantsov** [comment]
Unfortunately, SSH installer cannot work on OpenShift, moreover, it does not make sense for this platform at all.

**Comment by ctron** [comment]
> Unfortunately, SSH installer cannot work on OpenShift, moreover, it does not make sense for this platform at all.

Then simply remove it. Or rename it to "break your workspace" :wink:

**Comment by eivantsov** [comment]
It works on Docker :)

**Comment by ctron** [comment]
> It works on Docker :)

Which helps my exactly how?

So the remove it for OpenShift.

**Comment by eivantsov** [comment]
@ctron User Dashboard can detect which infrastructure Che is running on. However, there are no plans to do anything in this regard since Che will retire the concept of installers with the advent of **workspace.next** which implies running services as sidecars.
