### ISSUE TITLE
[Language server] Yaml language server features do not work with a file correctly after renaming it 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10937]
**Reproduction Steps:**
1. Create workspace through Dashboard based on **Node** stack with any project. 
2. Enable **Yaml** language server on this workspace details page and start the workspace.
3. Set YAML schema: 
    - menu **Profile** -> **Preferences**. 
    - select **Yaml** -> click 'Add Schema Url' button -> type "**kubernetes**".
4. Create "**openshift.yaml**" file and add content:
```
apiVersion: v1
kind: PersistentVolume
metadata:
```
5. Check that language server initialized and works:
    - make some mistake and check that code validation feature works;
    - move mouser pointer on "**apiVersion**" text in line 1 and check that hover feature works.
6. Rename this file and check language server functionality again.

**Expected result:**
Language server functionality works as expected.

**Actual result:**
Language server functionality doesn't work. 
The language server will work with this file correctly after renaming it to previous name or reopening. 

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 27-18-03-00-_1_](https://user-images.githubusercontent.com/7760565/44667467-8531a280-aa23-11e8-929a-edc57fdd230e.gif)

**Comment by dkuleshov** [comment]
Should be fixed by https://github.com/eclipse/che/pull/11483 please recheck after it is merged.
