### ISSUE TITLE
[Language server] PHP language server features do not work correctly with a php file after renaming it

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10932]
**Reproduction Steps:**
1. Create and start workspace through **Dashboard** based on **PHP** stack with "**web-php-gae-simple**" project. 
2. Open "**helloworld.php**" file, check that language server initialized and works:
    - make some mistake and check that code validation feature works;
    - move mouser pointer on "**htmlspecialchars**" text in line 9 and check that hover feature works.
3. Rename this file and check language server functionality again.

**Expected result:**
Language server functionality works as expected.

**Actual result:**
Code validation and hover feature don't work. The language server will work with this file correctly after renaming this file to previous name or reopening it. 

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 27-16-05-16](https://user-images.githubusercontent.com/7760565/44661404-4136a180-aa13-11e8-864a-1b438a5b7982.gif)

**Comment by dkuleshov** [comment]
Should be fixed by https://github.com/eclipse/che/pull/11483 please recheck after it is merged.
