### ISSUE TITLE
[Language server] TypeScript language server features do not work with a file correctly after renaming it 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10948]
**Reproduction Steps:**
1. Create workspace through Dashboard based on **Node** stack with any project. 
2. Enable **TypeScript** language server on this workspace details page and start the workspace.
3. Create "**greeter.ts**" file and add content:
```
function greeter(person) {
    return "Hello, " + person;
}

let user = "User";

document.body.innerHTML = greeter(user);
```
4. Check that language server initialized and works:
    - make some mistake and check that code validation feature works;
    - format code by **Format** feature from context menu.
5. Rename this file and check language server functionality again.

**Expected result:**
Language server functionality works as expected.

**Actual result:**
**Code validation** feature doesn't work. There are error messages in **dev-machine** console:
```
2018-08-28 08:21:03,542[ool-11-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - Notification handler 'textDocument/didChange' failed with message: Received change on non-opened document file:///projects/nodejs-hello-world/greeter.ts
2018-08-28 08:21:03,540[ool-11-thread-1]  [ERROR] [o.e.c.a.l.CheLanguageClient 75]      - [lspserver] Received change on non-opened document file:///projects/nodejs-hello-world/greeter.ts
```
**Format** feature doesn't work and there is error message in **Event log** panel(see screenshot below).
The language server will work with this file correctly after renaming it to previous name or reopening. 

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 08 28-11-28-39](https://user-images.githubusercontent.com/7760565/44714473-0dfd1c80-aabe-11e8-9273-15a6f5f0c0dc.gif)

**Screenshot:**
![selection_102](https://user-images.githubusercontent.com/7760565/44714807-e65a8400-aabe-11e8-84be-cf883b7904ae.png)

**Comment by dkuleshov** [comment]
Should be fixed by https://github.com/eclipse/che/pull/11483
