### ISSUE TITLE
Terminal font excessive spacing in 6.10.0

### ISSUE THREAD

**Issue by bencaldwell** [eclipse-che/che#10945]
### Description
After upgrading from Che 6.9.0 to 6.10.0 the font in the terminal has excessive spacing (see attached screenshot). There is no setting under preferences to allow changing this back to its previous more readable font setting.

### Reproduction Steps
1. Start Che 6.9.0 multi-user in docker environment using `docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start`
1. Configure and run a workspace, the terminal font is fine.
1. Upgrade to to Che 6.10.0 using `docker run -it --rm -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che-cli:latest upgrade`
1. After restarting the previously created workspace open a terminal and the font is changed to excessive width

**OS and version:**    
* Ubuntu 18.04 LTS
* Docker Server Version: 18.03.1-ce
* Che 6.9.0 upgraded to Che 6.10.0

**Diagnostics:** 
![image](https://user-images.githubusercontent.com/380684/44708729-6cd08f00-aada-11e8-9647-24f90e0199e4.png)

`docker run -it --rm -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che-cli:latest info`

```
INFO: (che cli): 6.10.0 - using docker 18.03.1-ce / native

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che-cli:latest
 Version:        6.10.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /home/user/.che-multiuser
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    6.10.0
 CHE_HOST:       <host ip redacted>
 CHE_INSTANCE:   /home/user/.che-multiuser/instance
 CHE_CONFIG:     /home/user/.che-multiuser
 CHE_BACKUP:     /home/user/.che-multiuser/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   <host ip redacted>
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:6.10.0
 IMAGE_CHE=eclipse/che-server:6.10.0
 IMAGE_COMPOSE=docker/compose:1.10.1
 IMAGE_POSTGRES=centos/postgresql-96-centos7:9.6
 IMAGE_KEYCLOACK=jboss/keycloak-openshift:3.4.3.Final
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:6.10.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:6.10.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:6.10.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:6.10.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:6.10.0
che.env:
 CHE_HOST=<host ip redacted>
 CHE_SINGLE_PORT=false
 CHE_DOCKER_ALWAYS__PULL__IMAGE=true
```

**Comment by eivantsov** [comment]
@bencaldwell does it happen on the latest nightly version?

**Comment by bencaldwell** [comment]
@eivantsov yes I've just tested and it happens on the latest nightly version.

## Reproduction steps
1. New install of che on a new docker host `docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che:nightly start`
1. Create a new default workspace using the che provided quickstart Java stack
1. Terminal font is still strange as per original screenshot

**Comment by eivantsov** [comment]
Cannot reproduce unfortunately. What browser do you use?

**Comment by Xhelliom** [comment]
same issue using chrome 68.0.3440.106 (also on edge) on Windows 10 and CHE 6.10.0

**Comment by POTION4** [comment]
Same here. I am using Brave and Firefox, the result is a weird-looking serif font being forced into monospacing shape. I am using macOS High Sierra.

**Comment by benoitf** [comment]
I reproduce the issue with Chrome and Firefox on macOS High Sierra

**Comment by triacontakai** [comment]
Having the same issue on Chrome 68.0.3440.106 with Che 6.10.0

**Comment by sathibault** [comment]
Same here, broken on Windows 10 Chrome 68.0.3440.106 and Firefox 61.0.2 with Che 6.10.0.

**Comment by eivantsov** [comment]
@KOSSOKO what is your OS?

**Comment by kalzi** [comment]
> I have same issue on Windows 10 with Firefox 43.0.1 and Chrome 60.0.3112.113
> Using che 6.10
> 
> ![cattura_console](https://user-images.githubusercontent.com/31631282/45087471-37452a80-b106-11e8-9edb-3fec836d914c.PNG)

Same Issue Observed in 6.11.0 too.. ENV: Windows 10, Chrome and Firefox Stable Releases

**Comment by eivantsov** [comment]
@abhinavprateek can you reproduce the issue with 6.9.0?

**Comment by abhinavprateek** [comment]
Unable to downgrade the CLI version. Couldn't find any documentation to do
it. Can you please guide?

**Comment by eivantsov** [comment]
@abhinavprateek you may start Che with a different local data folder and use 6.9.0 tag for eclipse/che image

**Comment by KOSSOKO** [comment]
@eivantsov, please, could I know if this issue will be corrected soon or I have to downgrade my che version ? Thanks

**Comment by eivantsov** [comment]
@KOSSOKO the thing is that I have hard time reproducing it on my Fedora machine.

**Comment by sathibault** [comment]
Version 6.9.0 does not have this issue for me.  I used browser inspection to compare the terminal windows between the working 6.9.0 version and the non-working 6.10.0 version and found that terminal windows in version 6.10.0 are rendered using a canvas object and 6.9.0 is using html dom elements.

We have downgraded to 6.9.0 but that version loads really slowly compared to 6.10.0, so I hope to be able to get back to 6.10.0.

**Comment by AndrienkoAleksandr** [comment]
I stable reproduced this issue on the virtual machine. I will take a look.

**Comment by skabashnyuk** [comment]
I have the same issue on
macOS 10.13.6
Chrome  69.0.3497.100

**Comment by celevra** [comment]
same here on 6.12

**Comment by buggtb** [comment]
Yeah sad times, its just about usable but makes my eyes bleed. Hopefully that merge works.
