### ISSUE TITLE
Incorrect icons for *.cc and *.c files in the Project Explorer

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10964]
**Reproduction Steps:**
1. Create workspace from **C++** stack with "console-cpp-simple" project. **Clang** language server is disabled by default.
2. Create "**hello.c**" file.
4. See icons for "**hello.c**" and "**hello.cc**" files in the **Project Explorer**.

**Expected behavior:**
"**hello.c**" file has icon for "c" files and "**hello.cc**" file has icon for cpp files.

**Observed behavior:**
"**hello.c**" file has icon for "cpp" files and "**hello.cc**" file has icon for default files.
 
**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_111](https://user-images.githubusercontent.com/7760565/44730397-84fbda80-aae9-11e8-8391-cf99f22d452b.png)

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/2)

**Comment by SkorikSergey** [comment]
Not actual.
