### ISSUE TITLE
[Language server] Apache Camel language server features do not work with a file correctly after renaming it

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10962]
**Reproduction Steps:**
1. Create workspace through Dashboard based on **Java** stack with any project. 
2. Enable **Apache Camel** language server on this workspace details page and start the workspace.
3. Create "**camel.xml**" file and add content:
```
<!-- here we have Spring XML file with all the namespaces here in the top of the XML file -->
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:camel="http://camel.apache.org/schema/spring"
  xmlns:cxf="http://camel.apache.org/schema/cxf"
  xsi:schemaLocation="
         http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
         http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd
         http://camel.apache.org/schema/cxf http://camel.apache.org/schema/cxf/camel-cxf.xsd">

  <!-- this is Spring XML example of the Camel route in the ReportIncidentRoutes class -->
  <!-- this is for demonstration purpose, to show how you can use Camel with XML DSL -->

  <!-- here we define the CXF endpoint, where {{port}} refers to a placeholder so we can define the port number
          in an external .properties file -->
  <cxf:cxfEndpoint id="reportIncident"
    address="http://localhost:{{port}}/camel-example-reportincident/webservices/incident"
    wsdlURL="etc/report_incident.wsdl"
    serviceClass="org.apache.camel.example.reportincident.ReportIncidentEndpoint"/>

  <!-- We use a bean to make the response bean that CXF expects -->
  <bean id="responseBean" class="org.apache.camel.example.reportincident.MyBean"/>

  <!-- this is the bean we use to generate the dynamic file name -->
  <bean id="filenameGenerator" class="org.apache.camel.example.reportincident.FilenameGenerator"/>

  <!-- this CamelContext contains the equivalent route from the Java DSL, but in XML
       so end users can see how to implement the route in both Java and XML -->
  <camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">

    <!-- property which contains port number -->
    <!-- we have file:target/custom.properties which can be optional and override existing values, we use this for testing purpose -->
    <camel:propertyPlaceholder id="properties" location="classpath:incident.properties,file:target/custom.properties"/>

    <!-- this is the first route that uses CXF as web service -->
    <route>
      <from uri="timer:timerName?fixedRate=false&amp;exchangePattern=InOnly"/>
      <convertBodyTo type="org.apache.camel.example.reportincident.InputReportIncident"/>
      <setHeader headerName="CamelFileName">
        <method bean="filenameGenerator" method="generateFilename"/>
      </setHeader>
      <to uri="velocity:etc/MailBody.vm"/>
      <to uri="file://target/subfolder"/>
      <transform>
        <method bean="responseBean" method="getOK"/>
      </transform>
    </route>

    <!-- this is the 2nd route that pickup files and send them as emails -->
    <route>
      <from uri="file://target/subfolder"/>
      <setHeader headerName="subject">
        <constant>new incident reported</constant>
      </setHeader>
      <to uri="smtp://someone@localhost?password=secret&amp;to=incident@mycompany.com"/>
    </route>
  </camelContext>
</beans>
```

4. Check that language server initialized and works:
    - move mouser pointer on text in line **37** and check that hover feature works.
5. Rename this file and check language server functionality again.

**Expected result:**
Language server functionality works as expected.

**Actual result:**
**Hover** feature doesn't work. 
The language server will work with this file correctly after renaming it to previous name or reopening. 

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 28-16-48-34](https://user-images.githubusercontent.com/7760565/44727329-6fcf7d80-aae2-11e8-9471-6fbf1c15f173.gif)

**Comment by apupier** [comment]
@SkorikSergey do you know if it is a problem from Eclipse Che side or from Camel language Server side?

**Comment by SkorikSergey** [comment]
There are similar issues for other language servers:

  |  
-- | --
[Language server] Yaml language server features do not work with a file correctly after renaming it | https://github.com/eclipse/che/issues/10937
[Language server] Golang language server features do not work with a file correctly after renaming it | https://github.com/eclipse/che/issues/10936
[Language server] Python language server features do not work correctly with a file after renaming it | https://github.com/eclipse/che/issues/10935
[Language server] PHP language server features do not work correctly with a php file after renaming it | https://github.com/eclipse/che/issues/10932
[Language server] TypeScript language server features do not work with a file correctly after renaming it | https://github.com/eclipse/che/issues/10948
[Language server] Apace Camel language server features do not work with a file correctly after renaming it | https://github.com/eclipse/che/issues/10962
