### ISSUE TITLE
How to edit che.env file?

### ISSUE THREAD

**Issue by osullivp** [eclipse-che/che#10977]
I wish to run an Android app on my device. I am using Codenvy.io with an Android stack and a new Simple Android project. One of the pre-requisites for running code on the actual device (rather than in the emulator) is to amend the che.env file as per this article:

[https://codenvy.com/docs/tutorials/android/index.html
](url)

However, despite searching numerous articles, I cannot find a description of how to amend the che.env file. Apparently this file is in :/data but how do I access this? From the terminal window in Codenvy?

Please note that I did try using the web emulator but our organisation has blocked this so I am therefore wishing to use the run on device feature.

**Comment by eivantsov** [comment]
Codenvy.io does not expose its che.env. This is the file that you can edit if you deploy Che yourself.

**Comment by osullivp** [comment]
Many thanks for confirming.
