### ISSUE TITLE
Initial `catalina.sh run` logs for `web-java-spring-petclinic` / `build and run` command are printed in red in the terminal

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#10973]
This issue is one of the sub-tasks of the `Java development with Eclipse Che / che.openshift.io on OpenShift ` workshop epic [1] based on: https://docs.google.com/document/d/1Vsk0A6xjgxQ9_pdpfLgXCZATGvi3Q1yS9DxRVOkKZEY/edit

Steps to reproduce:
1. create workspace from the official factory from https://github.com/che-samples/web-java-spring-petclinic/tree/che-osio  - https://che.openshift.io/f?id=factorymtyoro1y0qt8tq2j
2. "build and run" command would be executed automatically  - `mvn -f ${current.project.path} clean install && cp ${current.project.path}/target/*.war $TOMCAT_HOME/webapps/ROOT.war && $TOMCAT_HOME/bin/catalina.sh run`
3. For some reason `$TOMCAT_HOME/bin/catalina.sh run` console output is printed in red color which cause the feelings that some error have just happened:

![image](https://user-images.githubusercontent.com/1461122/44742508-4c1b3000-ab00-11e8-806a-87fad74d7b16.png)

It is expected that the initial catalina logs e.g. 

> 28-Aug-2018 18:20:33.629 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.24

 would be printed in the same color as the other console output and only errors would be printed in red.

[1] https://github.com/openshiftio/openshift.io/issues/4243

**Comment by ibuziuk** [comment]
@vparfonov could you please comment ?

**Comment by skabashnyuk** [comment]
@ibuziuk as I understand  https://tomcat.apache.org/tomcat-8.0-doc/logging.html
```The default logging.properties in the JRE specifies a ConsoleHandler that routes logging to System.err``` which means that you see default Tomcat behavior.

**Comment by ibuziuk** [comment]
@skabashnyuk thanks for update. Wondering, if it is possible to somehow override this behavior in particular factory and redirect output to `system.out` ?

**Comment by skabashnyuk** [comment]
I see two ways.
1. Make custom assembly of user's tomcat and configure logger.
2. Redirect stderror to stdout https://askubuntu.com/questions/625224/how-to-redirect-stderr-to-a-file

**Comment by ibuziuk** [comment]
@skabashnyuk thanks, it looks like the easiest way would be updating the command with `2>&1` e.g. 
`mvn -f ${current.project.path} clean install 2>&1 && cp ${current.project.path}/target/*.war $TOMCAT_HOME/webapps/ROOT.war && $TOMCAT_HOME/bin/catalina.sh run 2>&1`
tested on osio and this seem to work just fine:

![image](https://user-images.githubusercontent.com/1461122/44898776-22c8f280-ad00-11e8-8f76-9a1e22a86f18.png)

**Comment by ibuziuk** [comment]
Closing since workaround has been provided and in general this was an expected tomcat behavior - https://github.com/eclipse/che/issues/10973#issuecomment-416835533
