### ISSUE TITLE
'Build' console tab switches to another tab if rerun it by 'Re-run' button 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10979]
### Description
Build console tab switches to another tab if rerun its process by 'Re-run' button. 

**Preconditions**
Create and start workspace through **Dashboard** based on **Java** stack with "web-java-spring" project. 

**Reproduction steps with "web-java-spring:build" command:**
1. Start "**web-java-spring:build**" command and wait that build is finished.
2. Click on **Re-run** button in "**web-java-spring:build**" console.

**Expected result:**
Build is stared and "**web-java-spring:build**" tab is active.

**Actual result:**
Build is stared but **Terminal** tab is active. (see screencast below)

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
**Build command**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 08 29-13-10-12](https://user-images.githubusercontent.com/7760565/44781522-4cadd800-ab8d-11e8-9675-60b4bba6d2d6.gif)

**Comment by vparfonov** [comment]
normal behavior if re-run not finished command
