### ISSUE TITLE
Drop single-user support from E2E selenium tests of Eclipse Che

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10999]
### Description
Selenium tests of _Eclipse Che_ which are located in https://github.com/eclipse/che/tree/master/selenium project have some staff to run tests against _Eclipse Che Single User_. They became redundant after we drop single user support. 
And there could be another adaptation needed, for example, if it will be decided to use something instead keycloak on the local deployment.

It is related to https://github.com/eclipse/che/issues/10996.

**Comment by rhopp** [comment]
Obsolete. Closing
