### ISSUE TITLE
Wrong HTTP Statuscode returned when getting non existent stack

### ISSUE THREAD

**Issue by toorog** [eclipse-che/che#10995]
### Description
When requesting a non existing stack (e.g. by calling `/api/stack/doesnotexist`) the REST-API returns `403 Access Denied` whereas it should return `404 Not Found`.

Even the swagger UI provided by che states:

> 200 | The response contains requested stack entity |   |  
> 403 | The user has not permission get requested stack |   |  
> 404 | The requested stack was not found |   |  
> 500 | Internal server error occurred

### Reproduction Steps
1. Call REST API to get a stack that does not exist e.g. `/api/stack/A-B-C`
2. Have a look at the response

**OS and version:**    
Che 6.7.0

**Diagnostics:** 
```
Response Body
{
  "message": "The user does not have permission to read stack with id 'A-B-C'"
}

Response Code
403
```

**Comment by mshaposhnik** [comment]
This is because reading of stacks requires permissions.  So when checking premissions, there is no difference between `No permission for given stack` and `No given stack`. Need to find idea how to workaronud this.

**Comment by sleshchenko** [comment]
Stack service is deprecated, so it's not actual anymore
