### ISSUE TITLE
Provide an access token for `terminal` and `exec` sidecar

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#10991]
### Description
It is needed for https://github.com/eclipse/che/issues/10314.

The idea of implementing k8s/OS implementation for terminal server side is to use k8s/OS APIs for executing command and proxy Input/Output between client and k8s/OS API.

And there is an issue with an access token that can be used to accessing to k8s/OS API.
Now, no any Service Account is not declared to be bind to workspaces Pods. As result, default service account is here which doesn't have needed permissions to read objects in a namespace and execute commands in pods.

The easiest way is to create a service account per workspace and provide needed permissions for it (I suppose it may be `namespace-admin` role). But there can be a security issue since in this case if a user has an access to a terminal to any workspace container in a namespace then he is able to perform any operation there. It is needed whether it is an issue.

To avoid that we can bind the corresponding service account token to `exec` container only. Since service account is bounded to a Pod but not to a container, we can use `secret` and `volume` to inject the service account token into a particular container. But it requires some hardcoding on server side, since it should know that `secret` should be mounted to `exec` container.

It is needed to investigate all possible ways and decide what is the most suitable.

The plan is to do the following items:
- [x] Add an ability to configure existing service account to be bound to workspaces pods https://github.com/eclipse/che/pull/11178
- [x] Make OpenShift infrastructure create a special service account for workspaces https://github.com/eclipse/che/pull/11199
- [ ] Add documenting of workspace service account into Che Docs

Implementing create a special service account for workspaces by Kubernetes infrastructure will be done in a separate issue since it depends on upgrading to Fabric8 Client v4.0.4

**Comment by sleshchenko** [comment]
There was a discussion with @garagatyi @l0rd @ibuziuk @davidfestal and me. 
There was discussed two possible ways:
1. Che Server should grant default service account in workspace namespace with needed permissions.
2. Che Server should inject a special service account with needed permissions into workspace environment (the same as we so with docker credentials secret, it should be created on workspace start and removed on workspace stop)

In both ways, services account token should be mounted into each workspaces' Pods.

It is proposed to implement first way as simpler since there are no known issues or limitations with that.

Guys, please check that I didn't miss anything.

**Comment by l0rd** [comment]
@sleshchenko I think that we should not use the default SA (it may be used by other non Che pods as well) but use a specific SA (eg che-exec). We should also use SA token automount when creating workspaces pods and support 2 scenarios:
1. If all workspaces run in the same namespace the SA account and its associated role binding are created when installing Che (with ocp.sh or helm chart)
2. If every workspace run in a distinct namespace the SA and its associated role binding are created by wsmaster (when creating the new namespace)

Does it make sense?

**Comment by sleshchenko** [comment]
> We should also use SA token automount

Just to clarify: What you mean by `automount`?:
1. Specifying special `serviceAccount` in each workspace Pod explicitly to make its token mounted into each workspace container? 
2. Making special `serviceAccount` bounded to each pod in the namespace by default?

I think the first way is more reasonable.

> support 2 scenarios:
> 1. If all workspaces run in the same namespace the SA account and its associated role binding are created when installing Che (with ocp.sh or helm chart)
> 2. If every workspace run in a distinct namespace the SA and its associated role binding are created by wsmaster (when creating the new namespace)

We discussed the following way with @garagatyi:
During workspace start Che Server check if the needed namespace exists:
  - if yes then Che Server make sure that needed service account and role binding are there (check existense and create if needed);
  - if no then Che Server tries to create a namespace, service account and role binding.

This scenario should work well for both configurations. Do you think it's good enough or it would be better to have different strategies for each of configurations like you described?

**Comment by ibuziuk** [comment]
@sleshchenko @garagatyi @l0rd I have created the following PR so that new `exec` role would be created in *-che namepsace and granted to user and che-exec SA - https://github.com/fabric8-services/fabric8-tenant-che/pull/111/files. One can test in production via https://github.com/fabric8-services/fabric8-tenant-che/pull/111#issuecomment-418831136

**Comment by l0rd** [comment]
@sleshchenko for your first question I mean specify the pod `serviceAccountName`:

```json
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: che-exec
  automountServiceAccountToken: true
  ...
```

For your second question consider that:
- `che` ServiceAccount should not be granted more than `edit` privileges
- viewing or creating a `rolebinding` requires `admin` privileges (c.f. [k8s default roles and bindings](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings))

That means that in some cases checking the existence of the rolebinding will be hard (probably impossible) so I would not rely on that. I would rather:
- create SA + RB if Che is configured [to create workspaces in personal namespaces](https://www.eclipse.org/che/docs/openshift-admin-guide.html#create-workspace-objects-in-personal-namespaces)
- don't create SA + RB otherwise

**Comment by sleshchenko** [comment]
@l0rd 
> That means that in some cases checking the existence of the rolebinding will be hard (probably impossible) so I would not rely on that. I would rather:
> 
> * create SA + RB if Che is configured to create workspaces in personal namespaces
> * don't create SA + RB otherwise

Thanks for detailed explanaition. That makes sense to me.

> `che` ServiceAccount should not be granted more than edit privileges

Just to clarify: Are you talking about upstream or OSIO case?
As far as I see in upstream Che it has admin role in namespace for OpenShift
https://github.com/eclipse/che/blob/27bed82d5c57dc0c95093a1cea6043cfa47877f1/deploy/openshift/templates/che-server-template.yaml#L22-L30
And admin cluster role for Kubernetes
https://github.com/eclipse/che/blob/dcb00c53d09fc8ad71b0bc12d44115d7269d2481/deploy/kubernetes/helm/che/templates/cluster-role-binding.yaml#L10-L21
Are there plans to change it?

**Comment by l0rd** [comment]
> As far as I see in upstream Che it has admin role in namespace for OpenShift

I think we should fix that upstream (for kube as well). We should not need admin rights and therefore we should not requires them. That's more secure and makes it possible to deploy Che even on infrastructure where services are not allowed to run with admin privileges.
But no there is no plan anywhere yet. I consider it a bug. Let me open one in fact :-)

**Comment by ibuziuk** [comment]
PR for adding SA with view/exec permissions on osio - https://github.com/fabric8-services/fabric8-tenant-che/pull/111

**Comment by sleshchenko** [comment]
It is fully implemented for OpenShift infrastructure.
For Kubernetes infrastructure: helm chart is updated to create the needed service account for workspaces if the workspaces namespace is configured. If workspaces namespace is not configured (each workspace is created in a new namespace) then Kubernetes infrastructure has to create the needed service account too. It was not implemented because of API leaks in fabric8 client which we use. There is a separate issue to make Kubernetes infrastructure to create workspace service account https://github.com/eclipse/che/issues/11349.
