### ISSUE TITLE
Make resources exposed by REST and WebSocket private by default

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11007]
### Description
Now, new rest services and web socket methods are public by default, no any authorization checks there.
The idea of this issue is to make them private by default.
It will help to avoid a situation when a private resource is publicly accessible by mistake. It may happen when a developer forgets to implement permissions check.
REST Service/WebSocket method developer has to implement authorization way too or specify explicitly that resource is public.

So, in this PR it is needed to make resources exposed by REST and WebSocket private by default.

**Comment by garagatyi** [comment]
I would want to add that it is a popular approach among vendors of modern software to make it secure by default. This allows businesses to address the modern flow of vulnerabilities easier.

**Comment by garagatyi** [comment]
@l0rd @gorkem FYI
