### ISSUE TITLE
404s in CUSTOMIZING.md

### ISSUE THREAD

**Issue by ctron** [eclipse-che/che#11009]
### Description

Many of the links in the file seem to be dead. e.g. check the links of "Project Samples": -> https://github.com/eclipse/che/blob/master/CUSTOMIZING.md#project-samples

### Reproduction Steps

Click on any link of -> https://github.com/eclipse/che/blob/master/CUSTOMIZING.md#project-samples

**Comment by eivantsov** [comment]
@ctron thanks. will fix asap
