### ISSUE TITLE
Beaglebone Che - Stuck on Finishing Editor Initialization

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1100]
I am currently waiting for this 'Finishing Editor Initialization' to finish. Is there some kind of log I can check to see what is happening? I don't see anything in the terminal window I started che server from.

![image](https://cloud.githubusercontent.com/assets/16562450/14694499/90fa49cc-072e-11e6-853f-554d6621145a.png)

![image](https://cloud.githubusercontent.com/assets/16562450/14694524/c8418102-072e-11e6-97ff-828ec5f3c4d2.png)

Doesn't seem to be downloading dependencies.

![image](https://cloud.githubusercontent.com/assets/16562450/14694693/acacc670-0730-11e6-823f-bab82500ab97.png)

**Comment by james10174** [comment]
Ok I got simple hello world without opening the text editor by starting a new project. May seem like a small thing but that "Hello World" took a long time for me to get too :). However, it still hangs on 'Finishing Editor Initialization' when I try to edit a file.

![image](https://cloud.githubusercontent.com/assets/16562450/14695059/06d45b56-0734-11e6-8bf8-554d35c9d1bd.png)

![image](https://cloud.githubusercontent.com/assets/16562450/14695089/4ca76fb0-0734-11e6-8bd7-7bb27086a74a.png)

**Comment by ghost** [comment]
Does the loader go away or it's there all the time and blocks the IDE?

**Comment by james10174** [comment]
@eivantsov There all the time and blocks IDE.

**Comment by ghost** [comment]
I cannot reproduce it with current master. What version do you have?

**Comment by james10174** [comment]
eclipse-che-4.1.1. I am running on an arm processor so I wonder if that has anything to do with it. I changed the java-default stack to the following. Maybe the docker image doesn't have a required library 'kartben/armhf-che-jdk8' I need?

`{
    "id": "java-default",
    "creator": "ide",
    "name": "Java",
    "description": "Default Java Stack with JDK 8, Maven and Tomcat.",
    "scope": "general",
    "tags": [
      "Java",
      "JDK",
      "Maven",
      "Tomcat",
      "Subversion",
      "Ubuntu",
      "Git"
    ],
    "components": [
      {
        "name": "JDK",
        "version": "1.8.0_45"
      },
      {
        "name": "Maven",
        "version": "3.2.2"
      },
      {
        "name": "Tomcat",
        "version": "8.0.24"
      }
    ],
    "source": {
      "type": "image",
      "origin": "kartben/armhf-che-jdk8"
    },
    "workspaceConfig": {
      "environments": [
        {
......
`

**Comment by ghost** [comment]
It shouldn't do anything with the environment I think. Can you reproduce this error on a regular Linux amd64?

**Comment by james10174** [comment]
@eivantsov I have my pc with amd64 at home running with no issues. Is there any logs I can view that tells me where things are getting held up at?

**Comment by ghost** [comment]
Any errors and timeouts in browser dev console?

**Comment by james10174** [comment]
@eivantsov I will have to get che server running again to see. I am pretty sure I did not see anything. Also I can open the workspace and it will automatically have a file open for editing that I had open already. I have to click on console repeatedly before I it hangs/locks out so I can get it open. No way for me to close file before it's locked out. I do not do anything but try to open for editing and it hangs.
