### ISSUE TITLE
Walking skeleton pulling strategies

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#11017]
### Description
I noticed that with the sample workspace skeleton, the wsskeleton/che-hello is always pulled
![image](https://user-images.githubusercontent.com/436777/44903622-5100ff00-ad0d-11e8-908f-2f7d48a2f1b5.png)

here is a run 10mn after
![image](https://user-images.githubusercontent.com/436777/44903636-58c0a380-ad0d-11e8-9232-d82ab00d2c5d.png)

while Theia image is loaded from the cache (already present on the machine)
both of them are described in plug-ins

### Reproduction Steps
Create a workspace with workspace.next plug-ins

**Comment by benoitf** [comment]
related to https://github.com/eclipse/che/issues/11030

**Comment by garagatyi** [comment]
I investigated this issue and found out:
- we do not set explicitly pull policy
- if pull policy is not set and image tag is `latest`: OS uses default policy `Always`
- if pull policy is not set and image tag is not `latest`, e.g. `nightly`: OS uses default policy `IfNotPresent`

So we need to explicitly set pull policy in sidecar containers to `Always`

**Comment by benoitf** [comment]
Can it be a parameter ? instead of `Always` so I can tweak it do `IfNotPresent` on demand

When I try locally ws.next if I download each image at each workspace restart I have to wait a very long time with my internet connection.

**Comment by garagatyi** [comment]
@benoitf sure

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/11536
