### ISSUE TITLE
Unable to import project from Git with branch that contains a slash ("/")

### ISSUE THREAD

**Issue by ctron** [eclipse-che/che#11012]
### Description

It is not possible to clone a project from Git with a branch that contains a slash ("/").

### Reproduction Steps

* Import new project
  * Enter some Git URL – e.g. `https://github.com/ctron/kura-examples.git`
  * Tick "Branch"
  * Enter branch with slash – e.g. `tutorials/ece2018`

**OS and version:**    

* OKD 3.10
* CentOS 7.5
* Che 6.10

**Diagnostics:** 

![image](https://user-images.githubusercontent.com/202474/44912417-5751a400-ad2a-11e8-9ed3-cca3a53b6184.png)

When manually cloning:

~~~
[user@workspaceqkx9m2iqokcapjv4 projects]$ git clone https://github.com/ctron/kura-examples -b tutorials/ece2018
Cloning into 'kura-examples'...
remote: Counting objects: 264, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 264 (delta 20), reused 73 (delta 3), pack-reused 172
Receiving objects: 100% (264/264), 45.85 KiB | 0 bytes/s, done.
Resolving deltas: 100% (64/64), done.
[user@workspaceqkx9m2iqokcapjv4 projects]$ cd kura-examples/
[user@workspaceqkx9m2iqokcapjv4 kura-examples]$ git branch
* tutorials/ece2018
[user@workspaceqkx9m2iqokcapjv4 kura-examples]$
~~~

**Comment by ctron** [comment]
A workaround also can be to clone `master` and then switch to `tutorials/ece2018`. It seems this is only an issue when importing.

**Comment by andrew-mclachlan** [comment]
Interesting how we're using "branch":"feature-1.1.0" for a sample project and although we end up with a branch called "feature-1.1.0", it appears to correctly switch to the branch "develop/feature-1.1.0".
Is there something subtle going on that I am not aware of - I can't `git clone -b feature-1.1.0` or `git checkout feature-1.1.0` so I am wondering if there's some magic happening in the Che plugins (I should really just read the code!)

**Comment by vinokurig** [comment]
@andrew-mclachlan the logic you are looking for is placed in the `GitProjectImporter`: https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java
