### ISSUE TITLE
Create project operation freezes for custom project types

### ISSUE THREAD

**Issue by fErten** [eclipse-che/che#11026]
### Description

I have defined a custom project type based on your documentation and sample projects which work fine with the v6.8.0-SNAPSHOT. When I update the che-version to 6.11.0, project creation operation freezes when the create button in the project wizard is clicked. The same problem appears in your sample [che-plugin-wizard](https://github.com/che-samples/che-plugin-wizard) project.

**Comment by eivantsov** [comment]
@fErten thanks for reporting it

**Comment by fErten** [comment]
@eivantsov Can you duplicate the issue, after the release 6.9.0-SNAPSHOT, I having the same problem for each snapshot and project type extensions don't respond.

**Comment by vzhukovskii** [comment]
I'll take a look on it

**Comment by vzhukovskii** [comment]
@fErten can you look at logs, may be there is any exception (in workspace agent's tomcat on there is a suspicious response from the server) ?

I've built the sample from provided repo and can't reproduce the issue. So need more information about environment and possible errors that occurred in you dev environment.

**Comment by fErten** [comment]
@eivantsov @vzhukovskii Can you please tell me where the logs are stored?

**Comment by eivantsov** [comment]
@fErten it's in the workspace container at `/home/user/che/ws-agent/logs...`

**Comment by vzhukovskii** [comment]
And it would be better to see if something appears in browser console.
