### ISSUE TITLE
How to connect remote http/https git repository using GUI in Eclipse Che?

### ISSUE THREAD

**Issue by myhry** [eclipse-che/che#11040]
How can I connect to a remote http/https Git repository using GUI in Eclipse Che without SSH?

Is SSH required to connect to the remote repository?
I can connect to the https git repository using the git commands, but I'd like to use Eclipse Che GUI.

Is Eclipse Che planning to support connecting to the Git repository at http / https without SSH?
If it does not correspond, please tell me the reason.

I referred to the following.
[https://www.eclipse.org/che/docs/version-control.html](https://www.eclipse.org/che/docs/version-control.html)

**Comment by eivantsov** [comment]
@myhry only ssh when using UI Git.

**Comment by myhry** [comment]
@eivantsov 
Thank you for your reply. 
Why only support SSH?

**Comment by skabashnyuk** [comment]
Because we have no secure/user-friendly way to store user password.
Closing. Feel free to reopen this issue if you think it's still relevant for you.
