### ISSUE TITLE
Add support of Github PR URLs to a git repo URL Factory 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11045]
### Description
Che supports the creation of factories for a Github repo https://www.eclipse.org/che/docs/factories-getting-started.html#invoke-factory-for-a-specific-git-repo
We can add a new feature: support of PR URLs to this Factory capability. 
For a link like [https://che-url/factory?url=https://github.com/eclipse/che/pull/10740](https://che-url/factory?url=https://github.com/eclipse/che/pull/10740) we would apply a factory that clones git repo and checks out to a PR branch.
Note that there might be 2 kinds of repos for a PR:
- a branch that exists in the repo pointed by a PR URL :  https://github.com/eclipse/che/pull/10740
- a branch that exists in a fork of the repo pointed by a PR URL https://github.com/garagatyi/che 

We can implement one of the cases for the beginning and create a separate issue for another one, or we can implement both in the same contribution. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by benoitf** [comment]
PR provided handling both cases.
just a notice: it works only for `Opened` PR, it doesn't work on closed/merged PR (as branch may be gone)

**Comment by benoitf** [comment]
already merged
