### ISSUE TITLE
Create selenium tests for the walking skeleton flow

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11047]
### Description
We have 2 flows for the walking skeleton described in the [epic](https://github.com/eclipse/che/issues/10123). We have [merged](https://github.com/eclipse/che/pull/10740) support of the walking skeleton in Che recently and want to be able to check it on CI.
These 2 tests would not be included in the default test suite but we should be able to run them separately.

If the description of the flow, tests cases, deployment of any other part is not clear, ping @garagatyi for details or help

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@l0rd how do you think which team Che QA and OSIO QE should work on that?

**Comment by l0rd** [comment]
@garagatyi Che QA team. We should be able to test master.

**Comment by l0rd** [comment]
The following 2 issues were created by QA team:

https://github.com/eclipse/che/issues/11327
https://github.com/eclipse/che/issues/11400

@vkuznyetsov @Ohrimenko1988 is the test you created for #11327 already included in the list of tests run every nightl?

**Comment by garagatyi** [comment]
Outdated
