### ISSUE TITLE
Workspace.Next: Propagate broker pod logs to a client

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#11069]
### Description

Having broker pod logs on the Client Side (like we have installers output)  will be extremely helpful in debugging issues and finding out what has caused workspace start failure. Currently, the only way to get these logs is from the pod itself but since it's quite short lived, one may not have enough time to collect them.

**Comment by garagatyi** [comment]
@eivantsov Am I correct that publishing logs into a workspace start output would be enough to tackle this issue?

**Comment by sleshchenko** [comment]
@garagatyi Could you clarify what do you mean publishing logs into a workspace start output?

**Comment by sleshchenko** [comment]
I can propose to print all Che Plugin Broker pod into Che Servers logs (at debug or error level) when plugin broking failed (pod failed or FAILED broker status received). I believe it should be enough to determine the cause of failing in most cases.

**Comment by garagatyi** [comment]
> Could you clarify what do you mean publishing logs into a workspace start output?

I mean logs (events) that workspace loader app shows on a workspace start

**Comment by garagatyi** [comment]
> I can propose to print all Che Plugin Broker pod into Che Servers logs (at debug or error level) when plugin broking failed (pod failed or FAILED broker status received). I believe it should be enough to determine the cause of failing in most cases.

It would help in development but would be almost useless for the OSIO case when user can't see Che master logs and Ops team can't provide that for all the interested sides in case it is needed.

**Comment by sleshchenko** [comment]
> It would help in development but would be almost useless for the OSIO case when user can't see Che master logs and Ops team can't provide that for all the interested sides in case it is needed.

I agree. 

> I mean logs (events) that workspace loader app shows on a workspace start

Actually, it shows Pod events and installers logs which are machine related and we don't have any event to be published as workspace log that is not machine related. So, we should introduce some new one or find another way how to deliver them to clients.

@eivantsov If you are OK to publish plugin broker output to client somehow but not really store them at Che Server side, if yes please edit an issue.

**Comment by eivantsov** [comment]
@sleshchenko just having output on client may work - better than nothing

**Comment by sleshchenko** [comment]
I've investigated possible ways how to publish PluginBroker logs to a client and on meeting with @garagatyi we decided which way should be implemented.
So, I'm going to do the following changes:
Workspace API:
1. Rename `MachineLogEvent` to `RuntimeLogEvent`, and makes `machineName` field there optional. It will allow publishing log to a client which may be machine related or machine independent (like in case with plugin broker that it is not related to a particular machine).
2. Introduce new `runtime/log` JSON RPC method through which `RuntimeLogEvent`s will be published.
3. Deprecate `machine/log` JSON RPC method but publish machine logs there for time being.

Plugin Broker:
1. Introduce `PluginBrokerLogEvent` and Plugin Broker will use it for publishing its logs to the corresponding JSON RPC method on Che Server.
2. Make Che Server republish `PluginBrokerLogEvent` as `RuntimeLogEvent`.

Please let me know if somebody see any issues in this approach. Then we'll find another one.
