### ISSUE TITLE
Workspace is restarted after start interruption

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11077]
### Description
It is not really possible to interrupt a workspace start if the workspace was started via Workspace Loader. Workspace is restarted after start interruption.

### Reproduction Steps
1. Create a workspace.
2. Open a workspace.
3. Go to "Workspace" section and try to interrupt workspace start
Expected: Workspace start is interrupted.
Actual: Workspace is STARTING just after start interruption.

<details>

<summary>Screencast</summary>

![startinterruption](https://user-images.githubusercontent.com/5887312/45093574-7765d680-b121-11e8-9d6c-403df2d1e978.gif)

</details>

**Comment by mmorhun** [comment]
Issue was gone for a long time, but recently I faced it again.
I've tried to stop my starting workspace, the start was interrupted and then in a moment the workspace became starting again. This repeated several time until I give in and waited for full workspace start.

Infrastructure:
Minishift minishift v1.34.1+c2ff9cb
Che master: nightly, multiuser

**Comment by sunix** [comment]
@mmorhun as discussed, open a new issue and link to this one, let the triagers prioritise the new issue
