### ISSUE TITLE
[ci] [docker] Deploy che-theia images from PR to dockerhub

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#11078]
### Description
It would be nice that CI jobs could push theia images with the Pull Request ID to a dockerhub repo

so in order to test the image, we could only download the image without rebuilding it locally.

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.

**Comment by benoitf** [comment]
why closing ?

**Comment by benoitf** [comment]
CI is now doing that
