### ISSUE TITLE
Eclipse CHE documentation is displayed without images

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11093]
**Reproduction steps:**
From **Dashboard** open "Eclipse Che Documentation" page by clicking on "**Docs**" button.

**Actual result:**
Eclipse CHE documentation is displayed without images

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 09 06-12-03-06](https://user-images.githubusercontent.com/7760565/45147125-e9dfc080-b1cc-11e8-9f63-232e0cd2aaf2.gif)

**Screenshot:**
![selection_116](https://user-images.githubusercontent.com/7760565/45146613-eb5cb900-b1cb-11e8-9de1-6a9665e24012.png)

**Comment by rkratky** [comment]
I'm travelling until Wednesday, but I'll try to get to it before that.

**Comment by rkratky** [comment]
Oops, I forgot to update this issue. This has been fixed in https://github.com/eclipse/che-docs/pull/493
