### ISSUE TITLE
Cleanup plugins on Che Plugin Broker start to avoid usage of Theia plugins that were removed from workspace

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11095]
### Description
Now Plugin broker only adds plugins but doesn't remove them. This means that when a user wants to swap or remove a plugin from a workspace plugin broker doesn't respect that and user might end up with different implementations of a functionality in the same WS.
Plugin broker should remove all the plugins from the plugins folder before delivering plugins configured in a workspace.

Plugin broker [sources](https://github.com/eclipse/che-plugin-broker)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by amisevsk** [comment]
Closing as https://github.com/eclipse/che-plugin-broker/pull/7 is merged.
