### ISSUE TITLE
Upgrade fabric8-kubernetes-client version to v.4.1.0

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11112]
### Description
Che Server needs to create the special service account, role and role binding for workspace but role and role binding are not included into Kubernetes API of client version which we use. It is needed to update fabric8-kubernetes-client verion to v.4.0.4 as there is [the commit](https://github.com/fabric8io/kubernetes-client/pull/1111/commits/b5892eb158ad53fa33012b5c99b657de131860e4) which adds an ability to use RBAC objects via Kubernetes API.

It is needed for providing an access token for `terminal` and `exec` sidecars on Kubernetes Infrastructure https://github.com/eclipse/che/issues/10991

**Comment by amisevsk** [comment]
One major change in the move to `>4.0.0` is that `deployments` have moved from the beta api branch to v1, so [KubernetesDeployments.java](https://github.com/eclipse/che/blob/2bfa0cb7e6f8ae65814ce926ff9dcd8702851a91/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java#L146) should be changed (remove `extensions()` part) and tested thoroughly.

**Comment by skabashnyuk** [comment]
I'm wondering: who will do that and when?

**Comment by amisevsk** [comment]
@skabashnyuk It's not in the current sprint but we could talk to @ibuziuk about including it if it's blocking others. Has a CQ been created?

**Comment by garagatyi** [comment]
I don't think it is a blocker for the eclipse con epic

**Comment by ibuziuk** [comment]
@sleshchenko are you ok if we postpone this task till the next sprint ?

**Comment by sleshchenko** [comment]
@ibuziuk Yes, I'm OK.
