### ISSUE TITLE
[ws.next] Workspace engine should throw error if plugins are required but plug-in registry is not there

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#11124]
### Description
If I start a workspace with plug-ins being inside the workspace attributes but the plugin registry is not there (or not configured) the workspace will start without warning or errors but the plug-ins will not be there.

In that case I would say we should prevent to start the workspace as plug-ins are requested but registry is not there.
It will provide a better UX for end-users

### Reproduction Steps
Create a workspace.next workspace (like one from the stack) and without having the registry. 
BTW workspace will not start correctly in that case as ws.agent is not there and it tries to load the default IDE (thus the error message is not straightforward)

**Comment by amisevsk** [comment]
@benoitf Could you confirm that this issue still exists on current master? I just tried to start a workspace with plugins, with the `che-plugin-registry` deployment scaled to zero, and I got the error message 
```
Failed to start Kubernetes runtime of workspace workspace6188vxqyhoxs0507. Cause: Error occurred on retrieval of plugin che-dumy-plugin:0.0.1. Error: http://che-plugin-registry-eclipse-che.192.168.42.203.nip.io/plugins/che-dumy-plugin/0.0.1/meta.yaml
```
This is with current latest images, on minishift and the dev-cluster.

**Comment by benoitf** [comment]
issue was when registry is not even deployed and that master has not the URL provided as well

**Comment by garagatyi** [comment]
@amisevsk I think the case is when registry env var is set to NULL - then we completely ignore WS.NEXT config in a workspace.
