### ISSUE TITLE
Configure broker timeout in Che

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11120]
### Description
Che plugin broker timeout is hardcoded. We need to add an ability to configure it using a property.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by mshaposhnik** [comment]
Is that this|(https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/WaitBrokerResult.java#L44) timeout meant?

**Comment by sleshchenko** [comment]
@mshaposhnik Yes, it's there.
