### ISSUE TITLE
Feature Request: Explicit Container Names from CLI

### ISSUE THREAD

**Issue by glitch-bane** [eclipse-che/che#11129]
I scanned through the documentation and couldn't find this option being available at this time.  It'd be nice to explicitly set the primary container names at CLI start.  This way, orchestration could be better tracked.  Something like:

--env CHE_CONTAINER_NAME=<name of server container> \
--env CHE_POSTGRES_CONTAINER_NAME=<name of postgres container> \
--env CHE_KEYCLOAK_CONTAINER_NAME=<name of keycloak container> \

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
