### ISSUE TITLE
"Breadcrumbs" or "Go to Location" feature

### ISSUE THREAD

**Issue by bencaldwell** [eclipse-che/che#11132]
### Description
I can not find an obvious way to find which project/folder a file is located in. When navigating through a complex product with multiple projects I often use Open Declaration (F4). Once I am at the declaration I have no easy way to tell where that declaration lives.

When I have a tab open in the IDE I would like to see at least one of the following:
1. Breadcrumbs at the top showing where my class lives in the project explorer
1. A right click context item on the tab with "Go to Location" that would expand and highlight the file in project explorer.

### Reproduction Steps
1. Import a project and one of its dependendency libraries into project explorer
1. Select a method from the project and then Open Declaration
1. You cannot determine the location of the newly opened file

**Comment by RomanNikitenko** [comment]
You can use 'Reveal in project explorer' action, but, sure, we should improve this behavior.
![reveal](https://user-images.githubusercontent.com/5676062/45348744-1f632000-b5b8-11e8-8c6a-995ab3463b99.gif)

**Comment by bencaldwell** [comment]
Ok - it is not where I expect to find it but 'Reveal in project explorer' achieves what I want to do.
