### ISSUE TITLE
HandleDocumentSymbol LSP Type

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11139]
LSP has introduced support for hierarchical return values for "textDocument/documentSymbols". We should update our LSP editor to use this facility if avaliable.

See: https://github.com/Microsoft/language-server-protocol/issues/520

There are two tasks here:
1. Use DocumentSymbol where available: 
Easiest way would be to convert everything to DocumentSymbol instances in TextDocumentService#documentSymbol(). SymbolInformation result would simply transform to a flat list, with both source ranges being the same.
2. Convert our Java support in che-ls-jdt to use DocumentSymbol instead of our own classes. We could move the support for structured outline to jdt.ls and keep the version with inherited symbols in che-ls-jdt.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
