### ISSUE TITLE
WebDriverWait Instances Should not be Shared

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11149]
In reponse to this issue: https://github.com/eclipse/che/issues/8472, web driver waits are shared. However, instances of WebDriverWait can be customized (with custom message providers, for example). This can lead to bogus messages for test failures Was such, I don't think they are made to be shared. Is there a reason we are sharing the WebDriverWait instances? The linked issue gives no explanation.

**Comment by dmytro-ndp** [comment]
*WebDriverWait* instances are sharing to reduce number of it's instantiation during the selenium tests execution. The only difference we have between the instances is a timeout. It isn't expected that there could be another difference like the error message supplier.

**Comment by dmytro-ndp** [comment]
If we a setting up message supplier in addition to timeouts, it increases complexity of **WebDriverWaitFactory**. In that case it would make sense not to share instances.
