### ISSUE TITLE
Che Service Account should only need edit privileges

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11142]
It doesn't make sense to ask for more privileges then the one needed. This have security consequences and won't allow customers to install Che on k8s clusters where SA with admin privileges cannot be created.

The `wsmaster` should only need edit privileges in its namespace but today we set the serviceaccount to have admin (and even cluster-admin) rights:
- for OpenShift: https://github.com/eclipse/che/blob/27bed82d5c57dc0c95093a1cea6043cfa47877f1/deploy/openshift/templates/che-server-template.yaml#L22-L30
- for Kubernetes:
https://github.com/eclipse/che/blob/dcb00c53d09fc8ad71b0bc12d44115d7269d2481/deploy/kubernetes/helm/che/templates/cluster-role-binding.yaml#L10-L21

**Comment by eivantsov** [comment]
@l0rd Just change admin into edit?

On K8S service account can create objects at a cluster scope and this is done on purpose, since there's no flow on K8S similar to OpenShift Identity provider (using user's token to create objects)

**Comment by sleshchenko** [comment]
Also, note that Single User Che on OpenShift doesn't have `OpenShift Identity provider` too. Is it OK to declare that by default Single User Che is able to create workspaces only in its namespace or cluster-admin role should be bounded to `che` service account?

**Comment by eivantsov** [comment]
@sleshchenko good point. I think it would be fair to say so - with a single user Che (that may become history soon) one should not expect a lot of workspaces and there's no security too - one can access services of other workspaces.

**Comment by l0rd** [comment]
@eivantsov I suspect that changing from `admin` to `edit` will not work out of the box. This issue is to verify that assumption. And if there are issues let's discuss them here and find a solution. 

Good point for k8s. We should probably make the role configurable with a variable. But it should be `edit` by default. Anyway why do you think that running all workspaces in the same namespace means that "one can access services of other workspaces"? Che users should not be granted view/edit privileges to the Che namespace right, only Che SA should. 

@guydaichs you use Che with Kube in production: what do you think about not granting Che ServiceAccount cluster-admin rights by default?

@sleshchenko yeah for single user Che (until it exist) we should support having all workspaces in the same namespace only.

**Comment by eivantsov** [comment]
`edit` worked for me on OpenShift

**Comment by eivantsov** [comment]
![image](https://user-images.githubusercontent.com/5337267/45346879-4539f600-b5b3-11e8-9f0a-a96fcb6d48e3.png)

```
2018-09-11 08:10:44,981[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'admin/wksp-ducj' with id 'workspaceerp1mhzcto4ubi2j' created by user 'admin'
--
  | 2018-09-11 08:10:49,061[io-8080-exec-10]  [INFO ] [.c.a.w.s.w.PluginMetaRetriever 67]   - Che tooling plugins feature is disabled - Che plugin registry API endpoint property 'che.workspace.plugin_registry_url' is not configured
  | 2018-09-11 08:10:49,231[io-8080-exec-10]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 317]   - Starting workspace 'admin/wksp-ducj' with id 'workspaceerp1mhzcto4ubi2j' by user 'admin'
  | 2018-09-11 08:10:51,718[aceSharedPool-0]  [WARN ] [i.f.k.c.i.VersionUsageUtils 55]      - The client is using resource type 'deployments' with unstable version 'v1beta1'
  | 2018-09-11 08:11:31,533[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 359]   - Workspace 'admin:wksp-ducj' with id 'workspaceerp1mhzcto4ubi2j' started by user 'admin'
```

**Comment by guydaichs** [comment]
@l0rd  - If the default permissions in k8s can be limited without removing any multiuser functionality, it's a good idea. If not, I think that there should be a convenient way to create the cluster admin role and bind it as part of the installation, assuming it's possible in the target cluster (by chart configuration, like you suggest). The docs also have to be clear on this subject.

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.
