### ISSUE TITLE
Bundling custom stacks

### ISSUE THREAD

**Issue by sathibault** [eclipse-che/che#11154]
### Description

Is there a good way to provision Eclipse Che servers with a custom set of predefined stacks?

I've tried replacing the /assembly/stacks/stacks.json, but that did not work. It apparently gets the predefined stacks elsewhere. Also, the json file is reportedly deprecated, so is maybe not the right approach.

Using the UI or REST API are not reasonable because we want to be able to provision these servers without any manual configuration.

**OS and version:**    

Che 6.9.0/Ubuntu 16.04

**Comment by eivantsov** [comment]
@sathibault Do you run Che on Docker or K8S/OpenShift? On Docker stack.json is mounted onto the local file system.

**Comment by sathibault** [comment]
I'm using Docker with the eclipse/che-cli image and my custom assemblies (editor/server plugins) mounted at /assembly.

**Comment by eivantsov** [comment]
@sathibault you will need to build your custom assembly for that and either create a new module with stacks and exclude existing one or edit https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json, rebuild the module, then wsmaster and assembly main.

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
