### ISSUE TITLE
The alternative way to extend Eclipse Che?

### ISSUE THREAD

**Issue by gibbon-cn** [eclipse-che/che#11158]
I hope to deliver the power of Che to developers in my team. So it is needed to extend Che with our tool chain which will act as recipes and agents. Everyone would be able to build a server and start their work with our tools. I think it's a good way to do it by building image based on eclipse/che-server.

According to che docs, I have done it by adding installers to `api.war` and building the image `eclipse/che-server`. I also modify `ide\che-core-ide-stacks\src\main\resources\stacks.json` so that others can choose the specified image at dashboard to create their workspaces.

Every time I build the image from the slightly modified source code of Che as a whole project. 

Is it possible to do that in another way, which means I can start my work from a Docker file like:

```dockfile
FROM eclipse/che-server

# do something to extend che by adding workspace agents and so on...
```

**Comment by eivantsov** [comment]
@gibbon-cn no, you cannot do that in a Dockerfile.

By the way, if you want just to add agents and stacks you do not need to rebuild the entire project, just wsmaster-assembly and assembly main should be enough

**Comment by gibbon-cn** [comment]
"just wsmaster-assembly and assembly main should be enough" make things simple, while the image of `eclipse/che` still need to be built, isn't it? And that's the recommended way for vendors who apply eclipse/che in their saas products?

**Comment by eivantsov** [comment]
Yes, you first build custom binaries and then an image with those binaries
