### ISSUE TITLE
Welcome checkbox in the Preferences widget looks like is not actual

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#11166]
### Reproduction Steps
* Preconditions:
Create a workspace with any project for the IDE wizard.
* Go to the IDE and open Profile -> Preferences. Select Welcome item and set checkbox  (under `Welcome for persistent workspaces` label ) in enabled state. This add to preferences `plugin-factory.welcome: "true"` value.
* Create a factory based on the workspace and consume
**Expected result:** We should get Welcome docker panel with depended content
**Actual results** The panel is not opened 
**OS and version:**  IDE v.6.11.0 Snapshot, Openshift, Docker  assemblies.

**Comment by azatsarynnyy** [comment]
closed by https://github.com/eclipse/che/pull/11567
