### ISSUE TITLE
Use containerized docker-compose when running E2E selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#11188]
### Description
_Eclipse Che E2E selenium tests_ are using **docker-compose** to run tests in grid mode. It requires to have **docker-compose** installed locally, and can cause the problem if [docker-compose.yml](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/docker-compose.yml) doesn't comply with local **docker-compose**. For example, local **docker-compose** of version 1.21.2 produces  warning:
```
WARNING: The scale command is deprecated. Use the up command with the --scale flag instead.
```

**_Solution_**: use containerized **docker-compose** to not to depend on local one.

**Comment by rhopp** [comment]
Obsolete. Closing.
