### ISSUE TITLE
Housekeeping of legacy Eclipse Che E2E selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#11189]
### Description
There is outdated and unused code in selenium tests which should be removed or refactored:
- staff named `Codenvy`;
- unused methods and fields inside page objects and tests;
- instantiations of `FluentWait` and `WebDriverWait` instances, which should be replaced with [WebDriverWaitFactory](WebDriverWaitFactory) and [SeleniumWebDriverHelper](https://github.com/eclipse/che/blob/master/selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/webdriver/SeleniumWebDriverHelper.java) classes usage.

Removal of such staff will allow to make clearer and more stable tests.

**Comment by rhopp** [comment]
This should be responsibility of everybody, when doing any refactoring. Closing.
