### ISSUE TITLE
Make a release of che-ls-jdt

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11182]
We have never made a relaese of che-ls-jdt. In order to satisfy Eclipse legal rules, we need to do so before releasing anything based on it (aka the jdt.ls branch of Che6).

**Comment by tsmaeder** [comment]
Build is currently broken because che moved it's snapshot repo to sonatype.

**Comment by riuvshin** [comment]
Before release please make sure that you will have a way to pull tags of `eclipse.jdt.ls` artifacts from somewhere, because what I see for now you pulling SNAPSHOTS from CI job workspace...

**Comment by riuvshin** [comment]
I thin this can be closed
