### ISSUE TITLE
Worspace creation issue

### ISSUE THREAD

**Issue by lumkamhiga** [eclipse-che/che#1118]
Hi,

I'm trying to create a project on my Codenvy installation and keep getting this error

Error when starting agent
Unable to start workspace agent. Error when trying to start the workspace agent: Can't start machine ws-machine. Machine recipe downloading failed. Recipe url http://13.94.255.129/api/recipe/recipe5pl6pfjitj1z8ox8/script. Server returned HTTP response code: 403 for URL: http://13.94.255.129/api/recipe/recipe5pl6pfjitj1z8ox8/script

**Comment by ghost** [comment]
I can see that you aren't running Che on localhost. Can you elaborate on the way you have launched Che? Also, is this an existing workspace? Does it happen when you create a new one?
