### ISSUE TITLE
Helm chart should use README.md and not readme.md

### ISSUE THREAD

**Issue by obeyler** [eclipse-che/che#11193]
### Description
Helm chart should use README.md and not readme.md as describe into helm specification.
If it's stay in lower case tools like kubeapps or monocular won't be able to show description of the charts

### Reproduction Steps
Add the chart to a repository such as chartmuseum or artifactory and use kubeapps tools to see that the description is lacking.
![image](https://user-images.githubusercontent.com/23224162/45453611-9942f880-b6e1-11e8-8fd7-a3db71e147c6.png)

**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
Fixed. Thanks @obeyler
