### ISSUE TITLE
You volume mounted ':/repo', did not detect a valid eclipse Che source Repo

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#11195]
**Description**
WARN: Bound 'eclipse/che' to 'eclipse/che:6.10.0'
INFO: (che cli): /repo mounted - using assembly and manifests from your local repository
INFO: Welcome to Eclipse Che!
INFO:
INFO: You volume mounted ':/repo', but we did not detect a valid Eclipse Che source repo.
INFO:
INFO: Volume mounting ':/repo' activates dev mode, using assembly and CLI files from Eclipse Che repo.
INFO:
INFO: Please check the path you mounted to verify that is a valid Eclipse Che git repository.
INFO:
INFO: Simplest syntax:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/data
INFO:                       -v <YOUR_CHE_REPO>:/repo
INFO:                          eclipse/che start
INFO:
INFO:
INFO: Or run with overrides for instance, and backup (all required):
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/data
INFO:                       -v <YOUR_INSTANCE_PATH>:/data/instance
INFO:                       -v <YOUR_BACKUP_PATH>:/data/backup
INFO:                       -v <YOUR_CHE_REPO>:/repo
INFO:                          eclipse/che start

**Reproduction Steps**
What is the exact directory that we have to give the local path into in the :/repo?
I'm following the https://github.com/eclipse/che/wiki/Development-Workflow#build-and-run to build and run che and develop a  plugin.

**OS and version:** Windows 10   

**Diagnostics:** 
This is the command that i'm using
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v D:/EclipseCheCLI/backup:/data -v D:/EclipseCheCLI/che/assembly/assembly-main/target/eclipse-che-6.10.0/eclipse-che-6.10.0:/repo eclipse/che start

**Comment by eivantsov** [comment]
@LahiruT94 if D drive mounted into your Docker VM?

**Comment by LahiruT94** [comment]
Yes it is. I mounted it and it gave me this error
![6 11](https://user-images.githubusercontent.com/34393074/45481548-7825ea80-b769-11e8-9c9e-5c12e50f3fbf.PNG)

**Comment by LahiruT94** [comment]
![loca](https://user-images.githubusercontent.com/34393074/45483625-18324280-b76f-11e8-8432-1402dfd65bc8.PNG)

Is this how i should add it? It didnt work

**Comment by LahiruT94** [comment]
![run](https://user-images.githubusercontent.com/34393074/45483663-3bf58880-b76f-11e8-8aae-841055105ff8.PNG)

Is this how i should add it? it didnt work

**Comment by eivantsov** [comment]
Append it after start

**Comment by LahiruT94** [comment]
This error is giving because the mounted data volume directory is not empty.  When i directed it to the immediate directory it worked.

docker run -it --rm -v /eclipse/che:/repo -v /eclipse/che/assembly/assembly-main/target/eclipse-che-6.11.0:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start --skip:scripts

![closed](https://user-images.githubusercontent.com/34393074/45604340-04c5f680-ba51-11e8-90a6-e013a967622f.PNG)

**Comment by svkr2k** [comment]
I too got the same error:
/scripts/base/startup_01_init.sh: line 321: /repo/dockerfiles/cli/scripts/post_init.sh: No such file or directory

As suggested above, i added "--skip:scripts" at the end of docker run command.
Now, i'm getting the following error:

'
$ docker run -it --rm -v //var/run/docker.sock://var/run/docker.sock -v //d/che24Apr/che/assembly/assembly-main/target/eclipse-che-7.0.0-beta-3.0:/data -v //d/che24Apr/che
:/repo -e CHE_HOST=192.168.1.5 eclipse/che start --skip:scripts
WARN: Bound 'eclipse/che' to 'eclipse/che:7.0.0-beta-3.0'
INFO: (che cli): /repo mounted - using assembly and manifests from your local repository
INFO: (che cli): 7.0.0-beta-3.0 - using docker 18.09.2 / docker4windows
WARN: (che cli): 'CHE_HOST=192.168.1.5' from command line overriding 'CHE_HOST=10.0.75.2' from che.env
WARN: Newer version '7.0.0-beta-3.0' available
cp: can't stat '/files/docs': No such file or directory
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
WARN: You mounted ':/repo' or ':/assembly', but we did not find an assembly.
WARN: Have you built the assembly with 'mvn clean install'?
WARN: CHE_ASSEMBLY=/repo/assembly/assembly-main/target/eclipse-che*/eclipse-che-*
'
