### ISSUE TITLE
Add support for MySQL

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-che/che#11192]
### Description

Provide support for MySQL.  Persistence of Che data into MySQL will benefit users.
The database and driver does not need to be provided in an image/container.  Consumers can add it themselves and configure che.env.

**OS and version:**    
All OS.  Eclipse Che Version 6.12.

- [ ] Figure out version of Mysql server, jdbc driver, container image
- [x] CQ for MySQL  jdbc driver - testing only.
- [x] Contribute MySQL support(exception handlers) + MySQL TCK modules
- [x] Identify fields in a model that has conflicts with MySQL and provide migration to new fields
- [ ] Find a way how jdbc driver can be added in the end product
- [ ] End to  end  use case documentation.

**Comment by skabashnyuk** [comment]
@BarryDrez I've discussed this topic with @mshaposhnik . And he asked to identify fields in a model that has conflicts with MySQL. With that data, he can help with migrations.

**Comment by BarryDrez** [comment]
@skabashnyuk The only field that EclipseLink has a problem with is the values column in projectattribute_values.

**Comment by BarryDrez** [comment]
As far as table creation and modification goes, dealing with MySQL can be done in the SQL scripts using the framework you have indicated.

**Comment by skabashnyuk** [comment]
@BarryDrez fyi https://github.com/eclipse/che/pull/11237

**Comment by mshaposhnik** [comment]
@BarryDrez FYI we merged everything in master

**Comment by BarryDrez** [comment]
Thank you @mshaposhnik.  I am going to install and try it.

**Comment by BarryDrez** [comment]
@mshaposhnik, @skabashnyuk - I have added a dependency for mysql-support to our assembly-wsmaster-war project and built.  I created a db in mysql and started our custom assembly using the proper JDBC properties (pointing to my MySQL database).  I started che, and the tables were successfully created.  I created some organizations, then I created a workspace that uses an organization.  So far, everything looks good.  I can see entries in the MySql tables.  Is there anything else you'd like for me to test from the Che IDE?

**Comment by skabashnyuk** [comment]
- [ ] invite users to your organization

**Comment by BarryDrez** [comment]
@skabashnyuk Yes, I should have mentioned that I did invite users to the organizations.

**Comment by BarryDrez** [comment]
Tested with MySQL 8.0.12.  Unless you have anything else that you would like for me to try in the IDE, I will test with MySQL 5.7.

**Comment by skabashnyuk** [comment]
ок

**Comment by BarryDrez** [comment]
Tested with MySQL 5.7.23.  Tck tests single-user and multi-user run successfully. 
 Everything looks good.  As done for 8.0.12, I created a db in mysql and started our custom assembly using the proper JDBC properties (pointing to my MySQL database). I started che, and the tables were successfully created. I created some organizations, then I created a workspace that uses an organization. Everything looks good. I can see entries in the MySql tables.  Added users to the organizations.

**Comment by skabashnyuk** [comment]
How did you add jdbc driver?

**Comment by BarryDrez** [comment]
We have the jar file in our Maven repository.  Then, in my custom assembly, I include it in assembly.xml within assembly-main.  I have it as a dependency pom.xml files in assembly-main, assembly-wsmaster-war and our top level parent project within our custom assembly.
