### ISSUE TITLE
How to control display order of plugins in "Run" menu?

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#11196]
I'm developing several Eclipse Che plugins that are started via "Run" manu in the menu bar .
Each plugin is extended BaseAction and created with specified name like blow.

```
@Singleton
public class MyAction extends BaseAction {

  @Inject
  public MyAction(...) {
    super("Start My Action");
```

Each plugin is registered in ActionManager by following code.

```
  actionManager.registerAction("myAction", myAction);
  DefaultActionGroup mainContextMenuGroup = (DefaultActionGroup) actionManager.getAction(GROUP_MAIN_CONTEXT_MENU);
  mainContextMenuGroup.add(action);
  DefaultActionGroup runGroup = (DefaultActionGroup) actionManager.getAction(GROUP_RUN);
  runGroup.add(action);
```

As a result of that, my plugins are displayed in "Run" menu but the display order of plugins is not as I expected.
One plugin is displayed in the middle of "Run" menu, the others are displayed in the bottom.
There seems to be no regularity in the display order.

What kind of rules determine the display order of menu items?
Plugin name or menu string or something else?

How can I control the display order of plugins in the "Run" menu?

**Comment by eivantsov** [comment]
@vparfonov can you help here?

**Comment by azatsarynnyy** [comment]
Hi @hsgwd,
Action API provides the [Constraints class](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/constraints/Constraints.java) to define an action's position in an action group.
See the example of its usage [here](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/LanguageServerExtension.java#L114).

**Comment by hsgwd** [comment]
@azatsarynnyy
Thank you for your reply.
We could successfully change plugins order!
