### ISSUE TITLE
CPP Workspace

### ISSUE THREAD

**Issue by stephanfr** [eclipse-che/che#1120]
What is the current level of support for the CPP workspace in the 4.0.1 and 4.1.0 releases of Che?  The 4.0 documentation online shows a CPP workspace in the 'Ready to Go' stacks - but is not present in my deployments.  In looking over the source code, it appears as if the CPP plugin gets built into the framework but the stack does not appear in the 'predefined stacks' JSON file.

It looks as if the CPP support is not fully baked in yet - is this the case or am I missing something?

Thanks,

Stephan

**Comment by TylerJewell** [comment]
Stephan:

The support with 4.2 is quite high: debugger, syntax, custom stack, templates.  4.2 will be released on Monday.  I can get you instructions on how to install it early if you like.

**Comment by stephanfr** [comment]
Tyler,

Thanks so much for the quick reply - I will grab 4.2 on Monday.

Best Wishes,

Stephan

**Comment by TylerJewell** [comment]
You can build from master now if you want.  The Che changes are just going through qa.  There is also a vagrantfile there that you can use.  Just have it download the nightly tar not the latest.

**Comment by stephanfr** [comment]
I built the master branch and things look good.  The C++ workspace is there and I successfully ran the Hello World.

There is the single 'build and run command' in the IDE - I take it if I want to debug or start a project with a makefile, the approach would be to create custom commands?

Thanks,

Stephan

**Comment by TylerJewell** [comment]
Close.

You need to:
1. Launch a gdbserver in the workspace against your app.  This would be a custom command.  We are about to ship an ARTIK IDE tomorrow, and this assembly has these commands built into it.  You can launch this in the terminal if you know gdbserver.
2. After the gdbserver is running, you then create a debug configuration with the details on how to connect to it.
3. You then select that debug configuration and do Run ... Debug, and the debugger will connect directly to the gdbserver.

If you look into the ARTIK IDE Getting Started docs, you can see how we do it for that, and it works the same in regular Che.

**Comment by stephanfr** [comment]
Ok - will do.

Thanks!

**Comment by stephanfr** [comment]
Hmmm.....   I cannot find gdb on the workspace machine.  gcc is located at /usr/bin/gcc but in poking around I cannot find gdb.

What is the base OS for the c++ stack?  I tried apt-get without success.

Thanks

**Comment by TylerJewell** [comment]
Oh my gosh...  @eivantsov, @ddementieva - we did include the right gdbserver components in our Python, C, C++, Java, Go, JavaScript stacks, right?   @slemeur - lets also have QA verify that each of the samples that are provided have the same minimum set of command sets available: build (even if interpreted), run, launch debug server, etc.  

We focused so much on the ARTIK IDE scenarios, we need to double check that our embedded stacks have all of the services necessary for these common scenarios.

**Comment by slemeur** [comment]
Indeed, the pre-configured project templates are not providing all the commands. 
https://github.com/eclipse/che/blob/master/core/ide/che-core-ide-templates/src/main/resources/samples.json

**Comment by ghost** [comment]
@TylerJewell I haven't included gdb and gdbserver to C,CPP and Python stacks yet. As to Go stack, it has to be built first.

**Comment by stephanfr** [comment]
I'm curious where this stands.  Are the ready to go stacks going to get gdb/gdbserver injected and the extra commands soon -or- should I patch my local stacks?

Thanks

**Comment by ghost** [comment]
I'll issue a PR pretty soon. And I have added gdb and gdbserver to codenvy/cpp_gcc base image. So, you may give it a try.

**Comment by stephanfr** [comment]
I checked out and built the tip yesterday.  The Java and 'blank' workspaces and projects work fine - but still no CPP workspace joy.  The server times out waiting for the agent to come up.  In passing through the logs, the following looks suspicious:

[STDOUT] 2016-05-03 23:34:52,498[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/ws-agent/webapps/wsagent.war
[STDOUT] Tue May 03 23:35:38 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2016-05-03 23:35:38,988[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[.[/wsagent] 4818]       - Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CheBootstrap
[STDOUT] com.google.inject.CreationException: Unable to create injector, see the following errors:
[STDOUT] 
[STDOUT] 1) Error injecting constructor, java.lang.NullPointerException
[STDOUT]   at org.eclipse.che.plugin.maven.server.core.classpath.ClasspathManager.<init>(ClasspathManager.java:73)
[STDOUT]   at org.eclipse.che.plugin.maven.server.core.classpath.ClasspathManager.class(ClasspathManager.java:60)
[STDOUT]   while locating org.eclipse.che.plugin.maven.server.core.classpath.ClasspathManager

Any thoughts?

Thanks,

Stephan

**Comment by ghost** [comment]
@stephanfr issue is confirmed in the current master. Working on it. However, it's not there in 4.2 version, so please use it.

**Comment by ghost** [comment]
@stephanfr have you been able to debug a C/CPP app? I have just tried both samples. Looks ok to me. `codenvy/cpp_gcc` base image has both gdb and gdbserver now.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
