### ISSUE TITLE
Selenium: Create the method to set the 'Contribute' property in 'true' when the test start

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#11206]
### Description
* We have several selenium tests which check working or state of the PR panel
* That the tests would be independent from each other and of the state of the _Contribute_ property (especially for single mode ), we need to do next:
  - before the start test to check if there is the _Contribute_ property
  - if it is exist, need to set this property in 'true'
 * So we need to create the special API method which perform these actions before start appropriate selenium tests
* Related selenium tests:
  - _PullRequestPluginTest_
  - _PullRequestPluginWithForkTest_
  - _ContributeTabTest_
  - _CheckFactoryWithMultiModuleTest_
  - _CheckFactoryWithSparseCheckoutTest_
  - _CreateFactoryFromUiWithKeepDirTest_
  - _CreateNamedFactoryFromDashboardTest_
  - _DirectUrlFactoryWithSpecificBranchTest_

**Comment by dmytro-ndp** [comment]
Setting 'Git Contribute' preference to default value after/before the test execution would not be enough, so that tests could intersect each other being executed in parallel.
