### ISSUE TITLE
Cover the "Python" language server functionality by selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11218]
### Description
According to updated language servers test plan ( https://github.com/eclipse/che/wiki/Test-plan-for-checking-Language-servers) we need to add selenium tests for the next features of  **Python** language server:
format selected code
- code comment
- rename
- hover
- find references
- signature help
- go to symbol

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11293
