### ISSUE TITLE
Wrong token is set when requesting profile from Keycloak service in ws-agent

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#11214]
### Description
 
Request from ws-agent to `PrfileService` fails because the request  to Keycloak service is signed with machine token.

### Reproduction Steps

Make a request to `PrfileService` from ws-agent:
```
requestFactory
              .fromUrl(apiUrl + "/profile")
              .useGetMethod()
              .request()
              .asDto(ProfileDto.class);
```
**Actual**: Exception is caught:
 `Failed access: http://172.17.0.1:5050/auth/realms/che/protocol/openid-connect/userinfo?token, method: GET, response code: 401, message: {"error":"invalid_token","error_description":"Token invalid: Public key not set"}`
**OS and version:**    

**Diagnostics:**

**Comment by vinokurig** [comment]
Is needed for #10909

**Comment by gazarenkov** [comment]
@vinokurig Why do you need that?
Is not it easier to set it from IDE? (it knows the profile)

**Comment by vinokurig** [comment]
@gazarenkov You are right, I'll do in that way.
