### ISSUE TITLE
Investigate the failing selenium test 'ImportWizardFormTest' on CI job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#11227]
### Description
* In the last time the selenium test _ImportWizardFormTest_ is failed when run on the CI job via the _'StaleElementReferenceException'_
* Need to find the solution for it and fix

**See the report:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/398/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.gitImportWizardFormTest

**Comment by artaleks9** [comment]
I agree, we see in the report:
`</div> is not clickable at point (130, 71).`, but this is consequence.

But I would like to note to the important detail: before that we get the _StaleElementReferenceException_ in the _try/catch_ block: 
```
public void waitAndSelectItem(String path, int timeout) {
    waitItem(path);
    try {
      waitAndGetItem(path, timeout).click();
    }
    // sometimes an element in the project explorer may not be attached to the DOM. We should
    // refresh all items.
    catch (StaleElementReferenceException ex) {
      LOG.debug(ex.getLocalizedMessage(), ex);

      waitProjectExplorer();
      clickOnRefreshTreeButton();
      waitItem(path);
      waitAndGetItem(path, timeout).click();
    }
  }
```

On my opinion - this  is a main reason.
I think we need to handle correctly the _StaleElementReferenceException_, and it will allow to avoid failed tests.

**Comment by dmytro-ndp** [comment]
I see, thank you for explanation.

**Comment by artaleks9** [comment]
The last reports on the master CI show,  that the test does not have any failed test methods related to the _'StaleElementReferenceException'_
