### ISSUE TITLE
Update code of conduct which is mentioning to contact info@codenvy.com

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11238]
### Description

https://github.com/eclipse/che/blame/master/CODE_OF_CONDUCT.md#L38
Codenvy has been bought for several months now. Is the mail address still active?
By which one should it be replaced?

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
@slemeur may know

**Comment by ibuziuk** [comment]
@slemeur assigning this one to you

**Comment by apupier** [comment]
the issue is still present

**Comment by ibuziuk** [comment]
PR sent - https://github.com/eclipse/che/pull/16424

**Comment by ibuziuk** [comment]
PR has been merged. Closing
