### ISSUE TITLE
Remake the 'waitAndClick()' method from the 'SeleniumWebDriverHelper' according to the 'StaleElementReferenceException'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#11241]
### Description
* Sometimes selenium tests are failed (especially when they run on the CI) by the '_StaleElementReferenceException_'
* We need to remake the method _waitAndClick()_ in the _SeleniumWebDriverHelper_ to handle correctly  this exception and avoid fail the tests
* Also we need to remake two methods in the _Project Explorer_:
  - _waitAndSelectItem()_
  - _openItemByPath()_

using the handling of the _'StaleElementReferenceException'_ in the _SeleniumWebDriverHelper_:
* Related known issue: #11227

**Comment by tsmaeder** [comment]
Do we understand why the stale element references occur?

**Comment by Ohrimenko1988** [comment]
@tsmaeder The reason is - UI has been updated and web element reference is obsolete. So we are working on fixing this. You may see PR https://github.com/eclipse/che/pull/11246 which fixes this problem.

**Comment by tsmaeder** [comment]
I understand the meaning of stale references. But do we understand why the references change when we expect them not to? That is the interesting questions, IMO.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11246
