### ISSUE TITLE
Che Theia - CORS issue when Theia IDE client side browser trying to reach Che master

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#11240]
### Description
It happens that in some cluster configuration, Che Theia IDE is not located in the same location and when we are trying to reach Che master API from the browser, we encounter CORS issue like

```
Failed to load https://che.openshift.io/api/factory/factorywj3405v4cnxdjmln: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://routecw4tc0mt-sutan-1-che.8a09.starter-us-east-2.openshiftapps.com' is therefore not allowed access. The response had HTTP status code 403.
```

**Comment by sunix** [comment]
I see 2 ways of fixing it:
- somehow allow as origin all the possible cluster public url that a che master could have. That would be done dynamically according to Che configuration
- create a dedicated proxy in Theia node side for all our Che API.

**Comment by sunix** [comment]
@l0rd GWT app was hosted by che master

**Comment by skabashnyuk** [comment]
@sunix would it help if we enable CORS for factories?

**Comment by sunix** [comment]
@skabashnyuk yes and no
Factory is not the only component trying to reach CHE_API_EXTERNAL:
- https://github.com/eclipse/che-theia-machines-plugin/blob/master/theia-machines-extension/src/browser/che-workspace-client-service.ts#L22
-  https://github.com/eclipse/che-theia-task-plugin/blob/master/che-theia-task-extension/src/browser/che-api-external-endpoint-provider.ts#L26
- https://github.com/eclipse/che-theia-terminal-extension/blob/master/che-theia-terminal/src/browser/workspace/workspace.ts#L82

IMHO, we have to find a common way to fix all of them. BTW, most of these calls are to retrieve machine definition.

**Comment by AndrienkoAleksandr** [comment]
Maybe we should create common component and reuse it https://github.com/eclipse/che/issues/11072

**Comment by benoitf** [comment]
I would say that if extensions were plug-ins, then they would call APIs from server-side and then it won't hit CORS.

So if extension is still mandatory, they should use a server-side service.
I'm not sure it is interesting to have a proxy service as extensions should not be used

**Comment by sunix** [comment]
@benoitf thanks so maybe we could start moving factory extension to a plugin. It has to be done sooner or later anyway.

**Comment by ashumilova** [comment]
@sunix do we know which APIs are missing to convert factory extension to plugin?

**Comment by evidolob** [comment]
The problem should be fixed by https://github.com/eclipse/che/issues/11306

**Comment by sunix** [comment]
It is fixed as far as I know
