### ISSUE TITLE
Setup a CI job to build che-plugin-broker

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11255]
### Description

We currently use docker hub automated build to release `eclipse/che-plugin-broker` images. The problem is that it only tag images with `latest` and we would like to a tag corresponding to the git commit hash.

To solve that we would like to setup a CI job that is triggered at every commit in https://github.com/eclipse/che-plugin-broker master branch, builds the docker image and tag it twice: with `latest` and using the commit hash (e.g. `c5dfd6b`).  

cc @garagatyi @skabashnyuk

**Comment by riuvshin** [comment]
once we will have this should I disable automated build?

**Comment by riuvshin** [comment]
on our ci we don;t have recent docker with builder feature needed here https://github.com/eclipse/che-plugin-broker/blob/master/Dockerfile#L13
So I will need to update docker

**Comment by riuvshin** [comment]
done
https://hub.docker.com/r/eclipse/che-plugin-broker/tags/
https://ci.codenvycorp.com/job/che-plugin-broker-build-deploy/

**Comment by l0rd** [comment]
👍 thank you @riuvshin

**Comment by skabashnyuk** [comment]
@l0rd why do we need hashed images?

**Comment by l0rd** [comment]
@skabashnyuk we need to tag images (with the hash) to be able to pull and use them even when a newer version has been pushed to the docker hub. Previously, at every commit to master, the old image was replaced by a new one. There was no way to pull and use the old one anymore (it's like if we were using a SNAPSHOT version).
