### ISSUE TITLE
Calls to unexisting workspaces during ci tests

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#11257]
### Description
During CI tests, there is a lot of stacktraces indicating unexisting workspaces tried to be accessed (using machine token).
By adding debug output, it is confirmed that requests are made by `WorkspaceProjectSynchronizer` class, which is wsagent - side class. Logically, if workspace is stopped and removed, there must be no more agent classes belonging to it. Need futher investigation.

See master log attached.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by mshaposhnik** [comment]
[che-server-pod.log](https://github.com/eclipse/che/files/2392490/che-server-pod.log)

**Comment by skabashnyuk** [comment]
not reproduced on last CI build

**Comment by sleshchenko** [comment]
It is fixed by https://github.com/eclipse/che/pull/11253
