### ISSUE TITLE
Add an ability to use a custom registry for WS.NEXT plugins

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11265]
### Description
In some cases, usage of Che plugin registry configured for the whole Che is not convenient. 
An example is a development of a Che plugin - a user might not want to contribute to the official registry repo until the plugin is finished, but still wants to try it out for the development purposes.
We can allow setting registry identifier before plugin id in the workspace config and a plugin developer would be able to run his custom registry with his plugin and point it in Che workspace running on some hosted service such as Openshift.io.

Now plugin attributes look like:
```
"plugins": "my.id:version",
"editor": "edtr.id:version"
``` 
We want something like:
```
"plugins": "registry.cool-startup.com/garagatyi/my.id:version",
"editor": "user-1.openshiftcluster-22.openshift.com:5000/edtr.id:version"
```
Where we would support:
- separate registry
- specified port of the registry
- a specified path to the registry (in case it is hosted registry service with a user notion)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by mshaposhnik** [comment]
@garagatyi @l0rd 
A few questions appeared during issue analysis:
 - Should we consider duplicate and reject plugins with same id + version but different registry?  
-  Sholud we expect a specified registry protocol (http/https) or  try to recognize it ?

**Comment by garagatyi** [comment]
1. I would say yes. At least for the time being. 
2. I would guess the protocol. We use colon character to separate version, adding protocol would complicate the format.

**Comment by l0rd** [comment]
1. agree with @garagatyi 
2. I don't know how easy would be guessing the protocol. I would rather add it explicitly.

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/11588
