### ISSUE TITLE
Theia sidecar on Kubernetes?

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-che/che#11260]
### Description
Does Che support Theia on Kubernetes? If so, how?

### Reproduction Steps

If I start a Che cluster following instructions on https://www.eclipse.org/che/docs/kubernetes-multi-user.html and then try to create a workspace based on _Theia IDE on docker_ I get the following error:

> Failed
> InternalEnvironmentFactory is not configured for recipe type: 'compose'
>

**Comment by garagatyi** [comment]
We do not support compose recipes on Kubernetes infra. You'll need to use a kubernetes recipe based stack.

**Comment by jonahgraham** [comment]
Thanks, can you point me at one for Theia as it doesn't appear that there are any in the default stacks shipped with Che?

**Comment by jonahgraham** [comment]
OK, I think the problem is that yesterday's commit (https://github.com/eclipse/che/commit/8189276d9e2ab17f1bb3647b60#diff-be4e3a94b98c39160862773dcffad022R62) changed the _Theia IDE on docker_ from a dockerimage to a docker compose. I am trying out putting in my own stack with the version from before commit 8189276d.

**Comment by l0rd** [comment]
@garagatyi I don't get your answer. There are [3](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L79) [stacks](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L165) [to run theia](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L213). Why these are not compatible with Kubernetes?

**Comment by l0rd** [comment]
> @jonahgraham was asking why not to have default stack compatible with all of the infras

@garagatyi but @jonahgraham asked if it was possible to "add a new stack for Theia that just works in Kube" https://github.com/eclipse/che/issues/11260#issuecomment-422406298

#11266 is an excellent idea

**Comment by garagatyi** [comment]
@jonahgraham you can copy stack of Openshift and change recipe type field to "kubernetes". It would work. 
@l0rd After merging my PR we would be able to use k8s stack for both k8s and OS infras

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
