### ISSUE TITLE
Che + theia: Theia IDE do not send any activity events to wsmaster

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#11267]
### Description
When using Theia in Che and having `CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS` being set, workspace is killed after that time even if there is some activity in Che Theia IDE.

### Reproduction Steps
In http://che.openshift.io, create a workspace using a theia stack for instance https://che.openshift.io/dashboard/#/factory/factorywj3405v4cnxdjmln. After 15 minutes, even if the user is working editing files or doing anything else, the workspace is being killed.

**Comment by sunix** [comment]
maybe should reuse https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/resources/org/eclipse/che/public/activity.js client side

**Comment by sunix** [comment]
will we have CORS issue with that as well ?

**Comment by skabashnyuk** [comment]
@sunix can you consolidate all API on master on which you need CORS and create an issue for that?

**Comment by mmorhun** [comment]
Done.
Activity checker is added as Theia extension.
Requests to workspace master are performed from backend.
Both frontend and backend are optimized to send minimal amount of requests.
