### ISSUE TITLE
Timeout on Refactorings in Selenium Tests

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11275]
Some tests on the jdt.ls branch fail because a refactoring action has timed out, for example RenamePackageTest#checkTest8(), for instance. The screenshot shows that a timeout has occured on the rename. Manually performing the rename takes about 3 seconds on my well speced machine, so it is believeable that this would take over 10 seconds when running 3 tests in parallel on the qa-slaves. The solution here is to use a longer timeout: 30 seconds instead of 10, like for "get effective pom".

**Comment by dmytro-ndp** [comment]
Constant TestTimeoutsConstants.ELEMENT_TIMEOUT_SEC = 20 seconds would be enough, IMHO.
