### ISSUE TITLE
Create a global stack in che

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#11270]
Hi everybody,
    with my team, we are developing a platform for scientists and we use eclipse che to provide them a development tool. So I created a stack based on a docker image with all plugins they needed. By they can't see this stack in their when they log in. 

How could I declare my stack in order to make it visible among the default stacks present in che ?
Thanks

**Comment by eivantsov** [comment]
@KOSSOKO though there's no UI for that, you can still give your global stack the right permissions

**Comment by KOSSOKO** [comment]
@eivantsov thanks for your answer. I'm trying to follow the instructions under the link  but i face difficulties to connect to eclipse che with my Keycloak admin account  (username admin and password admin). I decided to get a token using curl with the command curl    `--data "grant_type=password&client_id=cb07ed3daz58-edddd50-4addd6e-be17-fcf49dff8b242&username=admin&password=admin"   http://10.29.150.153:5050/auth/realms/che/protocol/openid-connect/token` but I got the error 

> {"error":"unauthorized_client","error_description":"INVALID_CREDENTIALS: Invalid client credentials"}

Please I could I do tpo connect to eclipse che as admin and how could I get a token to be able to access to the full API

**Comment by eivantsov** [comment]
@KOSSOKO it should be your Che user admin. It is admin by default but perhaps you have changed password?

**Comment by KOSSOKO** [comment]
@eivantsov thanks a lot. Indeed, the password was modified by my colleague. Thanks
