### ISSUE TITLE
Avoid progress reporting blocked at 100% for several minutes when importing big project

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11284]
### Description
I tried to import Che in Che.
it took several minutes and the progress reporting was saying "100%" after several seconds.

![image](https://user-images.githubusercontent.com/1105127/45755452-c2521480-bc1e-11e8-8a21-ea355662e924.png)

it would be nice to have a smoother progress reporting and avoid to be blocked at 100% for several minutes

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
@apupier what do you suggest? Close the import wizard and let a user edit files while the project is being cloned?

**Comment by apupier** [comment]
> what do you suggest? Close the import wizard and let a user edit files while the project is being cloned?

if it i possible to start working, yes.
But I guess if it is still blocked, it is not completely possible, and in this case, i would suggest to improve the progress reporting and have it continuing reporting progress instead of being blocked at 100%

**Comment by apupier** [comment]
this was related to Che 6
