### ISSUE TITLE
Support ANSI color for Maven console output

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11285]
### Description

since Maven 3.5.0, Maven console output is providing ANSI color by default: https://issues.apache.org/jira/browse/MNG-3507

the current console in Che doesn't support it which leads to strange values displayed: "[1m--- [0;32"

![image](https://user-images.githubusercontent.com/1105127/45758816-cbdf7a80-bc26-11e8-89eb-5afe1048d4e3.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by amisevsk** [comment]
I believe this issue can be closed, I get color output running maven in the terminal on current Che:

![Screenshot from 2019-09-09 11-11-24](https://user-images.githubusercontent.com/16168279/64543185-bdd0b100-d2f2-11e9-8d6d-8f8adcc7d3ce.png)

(similar behaviour for the light theme)
