### ISSUE TITLE
How to add a brand new language to Eclipse Che

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#11299]
I'm quite new to Eclipse Che, and I've been trying to find a way to add new language support to it. How exactly do I add a completely new language to Eclipse Che so that it is possible to develop programs in Che using my language?

**Comment by geiseri** [comment]
I was looking at: https://www.eclipse.org/che/docs/language-servers.html#adding-a-language-server-config as a start.  I am currently using the LS sidecar approach.

**Comment by SharkJ** [comment]
> I was looking at: https://www.eclipse.org/che/docs/language-servers.html#adding-a-language-server-config as a start. I am currently using the LS sidecar approach.

Was it successful? I'm quite confused by the explanations in the sidecar approach explained in che docs.

**Comment by eivantsov** [comment]
@SharkJ you need to create own Docker image with a language server running inside it and listening on a port. After that, create a workspace with a custom recipe and declared server.

**Comment by SharkJ** [comment]
> @SharkJ you need to create own Docker image with a language server running inside it and listening on a port. After that, create a workspace with a custom recipe and declared server.

What I'm confused about is how to run my language server in a docker image. I'm very new to Che and Docker and I can't seem to find the answer. How do I include the Language server in the Docker image? My language server is not currently available in the internet. How do I either use it from the local directory or by adding it to github?

This question is linked with issue #11415
