### ISSUE TITLE
Error occured when creating workspace with volumes

### ISSUE THREAD

**Issue by gibbon-cn** [eclipse-che/che#11290]
Error occured when creating workspace with volumes

First in localhost:

    docker create -v /dbdata --name dbstore ubuntu /bin/true

Then a workspace is created with config for machine 

    {
        "dev-machine": {
            "attributes": {
                "memoryLimitBytes": "2147483648"
            },
            "env": {},
            "installers": [
                "org.eclipse.che.ws-agent",
                "org.eclipse.che.exec",
                "org.eclipse.che.terminal",
                "org.eclipse.che.ssh"
            ],
            "volumes": {
                "dbstore": {
                    "path": "/tmp"
                }
            },
            "servers": {
                "dot.net.server": {
                    "attributes": {},
                    "protocol": "http",
                    "port": "5000"
                }
            }
        }
    }

Server responds with "message":"Internal Server Error occurred, error time: 2018-09-20 07:48:33", and client with "Impossible to save and apply the configuration. Errors in Config".

The following is also tried, having the same error:

    docker volume create --name dbstore

**Comment by eivantsov** [comment]
@gibbon-cn Che does not support mounting named volumes or bind mount.

You can declare a volume per machine, and Che will create it

**Comment by gibbon-cn** [comment]
"declare a volume per machine", How to do that?

**Comment by eivantsov** [comment]
https://www.eclipse.org/che/docs/volumes.html

**Comment by eivantsov** [comment]
Try it without previously creating a volume with such a name on the host

**Comment by gibbon-cn** [comment]
In the doc:

>If you want your workspace machines to share volumes, just create volumes for each machine with an identical name. This way, machines will share the same volume.

I created volume in two workspaces, with the same name 'vol1'. However, Che created two volumes with different names:

![](http://ww1.sinaimg.cn/large/006R7Jbbly1fvlm0vo0k9j30sr04xq35.jpg)

![](http://ww1.sinaimg.cn/large/006R7Jbbly1fvlm1ik4fyj30nx04zgls.jpg)

**Comment by gibbon-cn** [comment]
Will Che support mounting named volumes or bind mount in the comming versions?

**Comment by eivantsov** [comment]
There are no such plans

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
