### ISSUE TITLE
Add new "che" namespace to Plugin API to have dedicated APIs

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#11306]
The Che specific namespace for Plugin API is needed to bring the ability for plugins to interact with Che specific objects (workspace, factory, machine, commands etc).
The Che plugin APIs should be provided by separate extension, that will extend the existing plugin system, and will be included in Che+Theia image by default.
For now the needed APIs are the following:
- [x] workspaces
- [x] factories
- [x] commands

but could be extended with more in time.

**Comment by benoitf** [comment]
I think it should more "extend" than "patch" the existing plugin system
