### ISSUE TITLE
Adapt OpenShift-related E2E test workspace templates to use JDT LS

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#11304]
### Description
There are [openshift-related test workspace templates](https://github.com/eclipse/che/tree/512329915d8ff4f29c937b99c40c3ca4f3170b39/selenium/che-selenium-test/src/test/resources/templates/workspace/openshift) which should be adapted to use JDT LS as well as [docker-related ones](https://github.com/eclipse/che/tree/512329915d8ff4f29c937b99c40c3ca4f3170b39/selenium/che-selenium-test/src/test/resources/templates/workspace/docker). 

Otherwise, we will have huge regression of Eclipse Che E2E selenium tests as described [here](https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-multiuser-master-ocp/155/Selenium_20tests_20report), where a lot of configuration methods like `setUp()` failed and caused skipping of test methods.

### Reference
It is related to PR https://github.com/eclipse/che/pull/10863

**Comment by tsmaeder** [comment]
We'll need to add jdt.ls as a language server wherever java is used.
