### ISSUE TITLE
Concept of ProjectTypes and FileTypes in Next Gen Che -Theia IDE?

### ISSUE THREAD

**Issue by es13b1018** [eclipse-che/che#11308]
Hi,

I have extended the Eclipse Che ide (GWT) to have custom ProjectTypes and FileTypes. I want to know if there is going to be anything like that in the Next Gen Che -Theia IDE. Will there be something like Create JAVA project, etc. Any insight on this will help.

Also, is there any documentation as of now regarding extending Theia in Che?

Thanks

**Comment by eivantsov** [comment]
@es13b1018 there are no project types as such. You will be able to create factories though and factory extension in Theia will import a project.

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
