### ISSUE TITLE
Fails to connect to WS (browser and server)

### ISSUE THREAD

**Issue by AffectedArc07** [eclipse-che/che#11316]
### Description
I am trying to run the docker image on VMware PhotonOS, container optimised Linux distro designed to run in ESXI easily. When I run the command to start up the image, I am told that the (browser => ws) and (server => ws) connections are not ok.

Command log:
```
root@photon-machine [ / ]# docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /local/path:/data eclipse/che start
WARN: Bound 'eclipse/che' to 'eclipse/che:6.11.1'
INFO: (che cli): 6.11.1 - using docker 17.06.0-ce / native
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]


ERROR: Try 'docker run <options> eclipse/che info --network' for more tests.
root@photon-machine [ / ]#
```

### Reproduction Steps
Make a PhotonOS VM on ESXI 6.5 out of this image:
http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw13-2.0-304b817.ova

Setup static IP
Attempt to start with docker
See this
![image](https://user-images.githubusercontent.com/25063394/45895587-80190680-bdc9-11e8-9d82-ddaf8f090044.png)
Get annoyed
**OS and version:**    
Photon OS 2.0 GA for ESXi 6.5 (V13)

**Diagnostics:** 
```
root@photon-machine [ / ]# docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /local/path:/data eclipse/che info --network
WARN: Bound 'eclipse/che' to 'eclipse/che:6.11.1'
INFO: (che cli): 6.11.1 - using docker 17.06.0-ce / native
INFO:
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: (che network): eclipse/che-ip:6.11.1: 192.168.0.103
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (192.168.0.103): Connection failed
INFO: (che network): Server  => Workspace Agent (External IP): Connection failed
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded
root@photon-machine [ / ]#
```

**Comment by eivantsov** [comment]
@AffectedArc07 you need to make sure the ephemeral port range isn't filtered.

**Comment by AffectedArc07** [comment]
Ok, Apolgoies for being new to this. Would I make sure its not blocked in my router, or is there something in OS to configure. And is there any way at all to check if the ports are unblocked/open/whatever.

Again, apologies, I am very new to this.

**Comment by AffectedArc07** [comment]
Found the issue, PhotonOS does wierd port filtering crap. I am running bare ubuntu now, and it works great. Thanks.
