### ISSUE TITLE
Explore Che master memory consumption with the grow of load from requests/WS starts

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11326]
### Description
When the amount of WS starts/requests to Che master grows memory consumption of tomcat process grows too and for managing Che on an enterprise scale an operator would want to know how much memory does it need to serve N users or N workspaces in parallel.

**Comment by skabashnyuk** [comment]
@garagatyi are you sure you are looking on correct config .
What about this line https://github.com/redhat-developer/rh-che/blob/master/openshift/rh-che.config.yaml#L36?

**Comment by garagatyi** [comment]
Yes, it was changed today only.

**Comment by skabashnyuk** [comment]
I would say this is expected behavior with such small XMX.

**Comment by garagatyi** [comment]
Isn't lack of Xmx lead to Java OOM exception? In our case, it was Linux OOM as far as I understand.

**Comment by skabashnyuk** [comment]
@garagatyi I'm not sure that you expect from upstream Che? Do you know how to reproduce this issue or something that can identify the root of this issue?

**Comment by skabashnyuk** [comment]
Right now me and @ibuziuk investigating logs on rh-che. and this issue has a perfect sense for me https://github.com/redhat-developer/rh-che/issues/898. But until the time when we see real usecase on upstream Che  I see no value on this issue. Especially with custom JVM config with such low Xmx.

**Comment by garagatyi** [comment]
@skabashnyuk I removed info about our OOM case since it is indeed not related to the topic. The idea is to explore overall memory consumption to properly operate Che on an enterprise-level cluster.

**Comment by garagatyi** [comment]
Outdated
