### ISSUE TITLE
Create Selenium test covered Theia stack

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#11327]
Cover next steps with Selenium tests

1. Open Che Dashboard
2. Select the “Workspace Next Hello World example on OpenShift” Stack
3. Create the workspace and Open in IDE
4. Verify if WS created successfuly
5. Open a terminal in Theia container
6. Git clone a sample Theia plugin and build it

**Comment by Ohrimenko1988** [comment]
This task blocked by issue: https://github.com/eclipse/che/issues/11340

**Comment by l0rd** [comment]
Now even step 3 ("Start Theia in hosted mode works"). Could you please add to the following test to the list:

7. Start Theia in Hosted mode and Run the plugin in the Development Host
