### ISSUE TITLE
[Language server] The hoverProvider for TypeScript language server does not work

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#11324]
### Reproduction Steps
* Create a workspace based on `node js` stack with enabled TypeScript LS
* Create the `typescript-greeter project` from the IDE Wizard
* Open the `greeter.ts` file and make sure that LS has been initialized properly.
* Hover cursor on `Greeter` 
**Expected result:** The hover pop up should display message like `class Greeter`
**Actual result:** There is nothing happens
**Additional info:** The LS support  capability like: `hoverProvider:true` (we get this through websocket after LS initializing). But looks like client does  not send any info to LS.
**OS and version:**    Upstream CHE, docker and OpenShift versions.

**Comment by tsmaeder** [comment]
Does this work with other langauge servers?

**Comment by tsmaeder** [comment]
The duplicated content is a know issue, I doubt it has any bearing on this problem.

**Comment by musienko-maxim** [comment]
Yes, this problem is reproduced for TypeScript LS only

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
