### ISSUE TITLE
Don't fail when waiting for jdt.ls console messages

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11328]
There is a suspicion that we have cases where the jdt.ls startup messages ("started", "workspace updated") are missed because the ide is starting too slowly and the message have been written before the IDE is showing the "workspace machine" console window.
Not failing the tests when we time out waiting for the would be more reliable. Writing out a message to the log would still allow to identify the case.

**Comment by eivantsov** [comment]
Closing the issue since the PR is merged. Feel free to reopen though
