### ISSUE TITLE
Investigate and fix problem with running E2E tests on K8S infrastructure

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#11320]
### Description
We have last 12 run on CI with failed status. The reason error like: `error: release che failed: roles.rbac.authorization.k8s.io "exec" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods/exec"], APIGroups:[""], Verbs:["create"]}] user=&{system:serviceaccount:kube-system:tiller 3555748f-bfcd-11e8-8ddd-02426ee598ca [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]`

**Comment by sleshchenko** [comment]
It is related to the following PR which adds creating of exec role https://github.com/eclipse/che/pull/11178. I've tested it on the latest `minikube`, used instructions in README.md to setting up Minikube and Che there and it worked just well.
Need to test it why it doesn't work on CI with https://github.com/riuvshin/k8s_dind/blob/master/k8s.sh
