### ISSUE TITLE
Terminal and project not loading in Eclipse Che in Amazon EC2

### ISSUE THREAD

**Issue by chintanp** [eclipse-che/che#11335]
### Description
I followed the Che installation process as described here: https://www.eclipse.org/che/docs/quick-start.html and added a security group to expose the port 8080 and 32700+ on my EC2 instance on my local machines IP address so that che server can be accessed from this machine (As described here: https://stackoverflow.com/questions/35121115/how-do-i-get-eclipse-che-running-on-amazon-ec2). 

Then I use the public IP address:8080 to open the Che in my browser and created a workspace with stack java-mysql. When I try to add projects into it and open the workspace, I see nothing in the directory tree. Screenshot attached. 
![che_local](https://user-images.githubusercontent.com/752869/45983804-1855fc00-c013-11e8-9161-a43023d6c075.png)
I am also not able to see any terminal or create new projects. 

Most probably this has something to do with the docker/che being able to access the filesystem on the EC2 remote machine. 

My che installation is: Version:     6.11.1               
Build Time:  2018-09-20 15:48:32  
Revision:    29b7fc94bfa80dee     

Remote Machine: EC2 ubuntu
Local Machine: Win 10, browser: Firefox 61.0.2

Am I missing some configuration steps? Any way to debug the situation further?

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
