### ISSUE TITLE
Theia terminal is terminated after executing "yarn" command

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11340]
### Reproduction Steps
 - Open dashboard and launch "Theia workspace next hello world" stack
![stack](https://user-images.githubusercontent.com/22724619/46000313-daa7b080-c0b0-11e8-902c-ce08feaed0d2.png)

 - In the opened workspace click on "File|" -> "Open New Terminal" items in the top menu 
 - In the opened terminal execute the next command: ```git clone https://github.com/ws-skeleton/che-dummy-plugin.git```
 - Wait until project is cloned and execute ```cd che-dummy-plugin``` command
 - Execute ```./build.sh``` command

**Expected behavior:**
The script is successfully done with next output:
![image5](https://user-images.githubusercontent.com/22724619/46000873-7e459080-c0b2-11e8-8c80-e9ddcdd6f09f.png)

**Observed behavior**
The command is terminated:
![ggggghhhh](https://user-images.githubusercontent.com/22724619/46000977-ccf32a80-c0b2-11e8-8936-3479177d79d0.gif)

**Brewser console log:**
![screenshot from 2018-09-25 11-10-17](https://user-images.githubusercontent.com/22724619/46001330-b26d8100-c0b3-11e8-83a5-dc3fd6e09c52.png)

**OS and version:**    
Che 6.12.0 ; Chrome 69.0 ; Fedora 25

**Comment by l0rd** [comment]
@Ohrimenko1988 can you please provide the memory limit for the theia container?

![image](https://user-images.githubusercontent.com/606959/46073488-507d4c00-c185-11e8-80a5-56be53f5acda.png)

**Comment by Ohrimenko1988** [comment]
@l0rd Please, take a look:
![eeee](https://user-images.githubusercontent.com/22724619/46076980-e9b55e00-c197-11e8-95c9-f7813605db01.png)

But I supose that problem is solved because I got expected output after try of bug reproduce.
![rrrtrtrtr](https://user-images.githubusercontent.com/22724619/46077046-2bde9f80-c198-11e8-9c03-c6ccc871c6ca.png)

**Comment by l0rd** [comment]
Cool. Yes that was a memory problem. We had a few PRs that addressed that in the last days. I think we can close this issue now.
