### ISSUE TITLE
Avoid long "Loading..." without details when trying to navigate in a relatively big projects

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11341]
### Description
I imported Che in Che.
Every time I try to navigate in the project tree, I have to wait several seconds with a "Loading..." before continuing. it is breaking my development flow

![image](https://user-images.githubusercontent.com/1105127/46002500-88fe2680-c0ae-11e8-8946-9f7b24003e44.png)

### Reproduction Steps

**OS and version:**    
Che 3.11.1 in Docker on Windows 10

**Diagnostics:**

**Comment by apupier** [comment]
in browser console log, I have this error:

PUT http://localhost:32775/api/project/che 500
_app-0.js:17760 ERROR (org.eclipse.che.plugin.pullrequest.client.ContributionMixinProvider): Failed to apply mixin to project: che. Cause: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.0.v20170811-d680af5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.h2.jdbc.JdbcSQLException: Column "VALUES" not found; SQL statement:
INSERT INTO projectattribute_values (projectattribute_id, values) VALUES (?, ?) [42122-196]
Error Code: 42122
Call: INSERT INTO projectattribute_values (projectattribute_id, values) VALUES (?, ?)
	bind => [2 parameters bound]
Query: DataModifyQuery(sql="INSERT INTO projectattribute_values (projectattribute_id, values) VALUES (?, ?)")

**Comment by eivantsov** [comment]
@apupier I think it happens when you expand sub modules, and the IDE is resolving them.

**Comment by apupier** [comment]
@eivantsov label is "kind/question". What is the question?

**Comment by eivantsov** [comment]
@apupier would you qualify this as a bug?

**Comment by apupier** [comment]
it depends on your quality requirements on User Experience.
More than 10 seconds freeze between each click on a node of the tree seems a bug for me.
It can be considered as an enhancement request too (functionally it is working)

**Comment by eivantsov** [comment]
@apupier btw, I cannot reproduce it on linux. Also, your screenshot says that project isn't configured as a maven project. 

This is how Che looks for me:

![image](https://user-images.githubusercontent.com/5337267/46273565-ba6b6c00-c55e-11e8-9d1a-a61c7d629f87.png)

In your case, modules aren't recognized as Maven modules.
