### ISSUE TITLE
Make Kubernetes infrastructure create a special service account for workspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11349]
### Description
If Kubernetes infrastructure creates a namespace for workspace then special service account (with `view` and `exec` rights) should be created there, otherwise, Tasks and Exec sidecars will fail because of permissions leaks. The same is done for OpenShift infrastructure https://github.com/eclipse/che/pull/11199

It depends on upgrading fabric8-kubernetes-client version to v.4.0.4 #11112 

**OS and version:**    

**Diagnostics:**

**Comment by l0rd** [comment]
@skabashnyuk @sleshchenko is there any chance to work on this issue in current sprint?

**Comment by sleshchenko** [comment]
@AndrienkoAleksandr Could you please update `README.md` file in `che-exec-terminal` plugin since this issue is closed and `Terminal` and `Exec` should work fine on both of listed helm chart configurations https://github.com/ws-skeleton/che-machine-exec.

**Comment by AndrienkoAleksandr** [comment]
@sleshchenko thanks, I will update README.md file.
