### ISSUE TITLE
Renamed Open Files Are Closed

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11359]
We have intermittent failures in Selenium tests when refactoring classes and then checking that the class is open in an editor (for example, in TestEnumerationsTest). The suspected reason for this is that the class EditorFileStatusNotificationOperation is closing the editor because it gets the "delete" notification from a rename or move and closes the editor before ApplyWorkspaceEditAction is able to adjust the editor to show the new File.
The proposed fix would be to suspend EditorFileStatusNotificationOperation while the workspace edit is being applied.

**Comment by eivantsov** [comment]
Closing as fixed.
