### ISSUE TITLE
Ls-Sidecars Build Failure - java.lang.RuntimeException: wsagent server doesn't exist

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#11372]
I followed the Ls-Sidecars instructions provided in che docs. However, when I open the workspace built using the new stack, I get an error saying IDE initialization failed: java.lang.RuntimeException: wsagent server doesn't exist.

![untitled](https://user-images.githubusercontent.com/23653853/46127944-c0580900-c24f-11e8-9e4e-9b954ffcd1ae.png)

Please, If anyone could help here, it'll be highly appreciated.

**Comment by eivantsov** [comment]
@SharkJ you need to enable Workspace API engine for your machine. You can do that in Dashboard, Workspaces view > Installers

**Comment by SharkJ** [comment]
> @SharkJ you need to enable Workspace API engine for your machine. You can do that in Dashboard, Workspaces view > Installers

It is already enabled along with Exec and Terminal.

**Comment by eivantsov** [comment]
Share your workspace config

**Comment by SharkJ** [comment]
> Share your workspace config

{
  "commands": [],
  "environments": {
    "default": {
      "recipe": {
        "contentType": "application/x-yaml",
        "type": "compose",
        "content": "services:\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n   - gols\n gols:\n  image: eivantsov/go-lang\n  mem_limit: 1073741824\n"
      },
      "machines": {
        "gols": {
          "env": {
            "CHE_MACHINE_NAME": "gols"
          },
          "servers": {
            "golsp": {
              "attributes": {
                "languageRegexes": "[ {\"languageId\":\"golang\", \"regex\":\".*\\\\.go$\"}]",
                "internal": "true",
                "id": "go-ls",
                "type": "ls"
              },
              "protocol": "tcp",
              "port": "5555"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.terminal",
            "org.eclipse.che.exec",
            "org.eclipse.che.ws-agent"
          ],
          "attributes": {
            "memoryLimitBytes": "1073741824"
          }
        },
        "dev-machine": {
          "env": {
            "CHE_MACHINE_NAME": "dev-machine"
          },
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal"
          ],
          "attributes": {}
        }
      }
    }
  },
  "projects": [
    {
      "source": {
        "location": "https://github.com/che-samples/web-go-simple",
        "type": "git",
        "parameters": {}
      },
      "description": "",
      "links": [],
      "mixins": [
        "pullrequest"
      ],
      "problems": [],
      "name": "web-go-simple",
      "type": "blank",
      "path": "/web-go-simple",
      "attributes": {
        "contribute_to_branch": [
          "master"
        ]
      }
    }
  ],
  "defaultEnv": "default",
  "name": "golang",
  "attributes": {},
  "links": []
}

**Comment by eivantsov** [comment]
ws-agent installer should be in dev-machine

**Comment by SharkJ** [comment]
> ws-agent installer should be in dev-machine

It works fine now! Thank You for helping!

**Comment by SharkJ** [comment]
![image](https://user-images.githubusercontent.com/23653853/46133172-80981e00-c25d-11e8-8b52-6d656c5498ed.png)

![image](https://user-images.githubusercontent.com/23653853/46133192-8b52b300-c25d-11e8-9f31-1ab2c78c05e6.png)

![image](https://user-images.githubusercontent.com/23653853/46133206-9279c100-c25d-11e8-9780-c8b12c1040d4.png)

Some of the messages I'm getting

**Comment by SharkJ** [comment]
The error was due to Terminal not being activated while running the workspace.  The issue is solved by activating Terminal Installer in the machines.
