### ISSUE TITLE
 MachineTokenAccessFilter binding customization

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11374]
### Description
In this place https://github.com/eclipse/che/pull/11370#issuecomment-424984870 we met situation when developers of custom Che assembly are struggling with zero ability to customize binding of  
KeycloakAuthenticationFilter and MachineTokenAccessFilter. The goal of this issue is to provide a better way to configure this filters.

**Comment by mshaposhnik** [comment]
Done for machine auth, will create separate issue for Keykloak Auth
