### ISSUE TITLE
Not able to create new project using any stack

### ISSUE THREAD

**Issue by gma-git-admin** [eclipse-che/che#1138]
I upgraded to eclipse che 4.2.0 and have been trying to create workspace and project using python3.5 stack.

The workspace gets created successfully but when I try to create project, it doesn't seem to do anything and after a while retry option appears. I don't see any message on the console during the create project task. However, in the log downloaded from the link provided on UI page, it appears that client unexpectedly aborts. Please refer to the log files attached.

Tried with Java stack too to verify if this issue is only with Python stack or exists in in general and it didn't work for Java either. Am attaching the log for this one too which of course similar to the other one.

[ubuntu_jdk8.txt](https://github.com/eclipse/che/files/237263/ubuntu_jdk8.txt)
[ubuntu_python.txt](https://github.com/eclipse/che/files/237264/ubuntu_python.txt)

**Comment by gma-git-admin** [comment]
Please note that I can connect to workspace IDE. I tried restarting the Docker as well. Didn't change any other configuration so am not sure for the root cause of this issue. Did restart the EC2 instance but the security rules are unchanged with port 8080 and 32768-65535 open. 

Thanks.

**Comment by ghost** [comment]
According to the log the ws agent has successfully started. What error do you see on the UI? And yeah, I think this is ports issue with browser not being able to connect to ws agent.

**Comment by ghost** [comment]
You may also want to take a look at websocket connections that a browser initiates. Is it localhost vs the VM IP?

**Comment by gma-git-admin** [comment]
UI don't show any error. After trying for a while it just gives up and a retry button appears. This is VM IP. So Che is running on EC2 using run --remote:[public-ip-address_of_ec2-instance]. I checked the security rules associated with the ec2 instance and the required ports are open. Interestingly it worked earlier. I can't get as to what might have changed to cause this issue. On the ec2 console I don't see any message corresponding to the create project task. Is there any other log that can guide us?

**Comment by ghost** [comment]
> The workspace gets created successfully but when I try to create project, it doesn't seem to do anything and after a while retry option appears. 

What if you go to workspaces tab after that and open a workspace in the IDE?

**Comment by gma-git-admin** [comment]
Workspace opens successfully in the IDE. Just that there is no project there.

**Comment by gma-git-admin** [comment]
Interestingly the same thing also happens with Che-4.1.1 too. So I guess the problem is not specific to 1.2.0. There seems to be some issue with the host ec2 environment just that I can't figure out what. And there is no descriptive log to provide any definitive clue.

**Comment by ghost** [comment]
Well, I cannot reproduce it with 4.2.0 both locally and on a remote server (Digital Ocean).

**Comment by ghost** [comment]
Do you have any configuration persisted locally?

**Comment by gma-git-admin** [comment]
I configured it following the steps specified here: https://eclipse-che.readme.io/docs/configuration-che-on-ec2.

Also Che-4.1.1 and 4.2.0 versions are both there on the same ec2 machine. Hope that's not causing any issue. Further, I noticed that when a workspace is deleted from UI, it doesn't show up again in the UI but I can see the corresponding workspace folder under Che root dir. Also the corresponding containers are also there under Docker though not running. If it helps I can try cleaning up the ec2 instance and re-installing just 4.2.0.

**Comment by gma-git-admin** [comment]
So I did further research on this. I installed Che-4.2.0 on fresh Ubuntu machine and still the same issue. Looked into the docker images and containers and didn't find any containers running for the newly created workspace. So I tried to create new container from existing ubuntu_python image. While the container was created and run successfully when trying to attach to it, it didn't result anything similar to the behavior of UI while trying to create new project. So I guess there is some problem with the ubuntu_python image probably. Then I tried to create custom workspace with the docker file at https://github.com/codenvy/dockerfiles/blob/master/ubuntu_python/2.7/Dockerfile but still the same issue.

Finally I went back to Che-4.1.1, created the custom workspace with the python27 docker file and could create project successfully. So there seems to be some issue with Che-4.2.0 in the way it tries to connect to a container. Hope this provides some clue as to the root cause. Will keep looking into it and let me know if you find something helpful there.

**Comment by ghost** [comment]
I just checked 4.2.0 release and found no issues on Ubuntu. Can you record a short video demoing Che working and failing if possible?

**Comment by ghost** [comment]
@gma-git-admin it looks like a cache issue. I did reproduce the problem with 4.1.1 and 4.2.0 on a clean remote Ubuntu 14 node. First ran 4.1.1 (success) and then 4.2.0 (ran into issues you had previously described). An incognito window fixed it for me. So, clearing cache should fix it.

Let me know if it helps. And thanks for your patience :)

**Comment by ghost** [comment]
Closing the issue since clearing cache solved the problem for multiple users. Feel free to reopen if the problem is still there for you.
