### ISSUE TITLE
Editor behaves improperly when in debug mode

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#11398]
### Description
See the recording
![problem-editor](https://user-images.githubusercontent.com/1636769/46197315-beeb1700-c309-11e8-8f53-bb4d74966bd6.gif)

It automatically jump to the line above.
There are also a lot of formatting issue

### Reproduction Steps

**OS and version:**    
che.openshift.io

**Diagnostics:**

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che/pull/11672
