### ISSUE TITLE
PVC cleanup is never performed for the ephemeral workspaces

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#11391]
### Description
https://github.com/eclipse/che/issues/11350 brings support of the ephemeral workspaces via `persistVolumes` attribute. Since the `persistVolumes`attribute is mutable (i.e. workspace can be started  with bound volume and then later `persistVolumes` could be added to the config), when ephemeral workspace is deleted no PVC cleanup will be performed.  

### Reproduction Steps
- create workspace and start it
- depending on the strategy either new PVC (unique) or subpath in existing PVC (common) would be created
- stop workspace and add `persistVolumes` attribute to the config
- delete workspace 
- ERROR: no pvc cleanup performed since cleanup is not executed for ephemeral workspaces

Since the main purpose of the ephemeral workspaces is to avoid problems with volume mount, cleaning pvc for `common` strategy might cause some issues since `rm` pod performs a volume mount (smth. that we are trying to avoid). There should not be any problems with ephemeral `cleanup` execution while using `unique` strategy, since if pvc does not exist it will just not be removed.

**Comment by eivantsov** [comment]
@ibuziuk can this be closed since the PR is merged?

**Comment by garagatyi** [comment]
@ibuziuk ping

**Comment by amisevsk** [comment]
@eivantsov I believe this issue was created to cover an edge case in ephemeral workspaces, and so is not yet fixed (at least not by #11343).

**Comment by ibuziuk** [comment]
@eivantsov @garagatyi sorry missed your messages. Angel is right, this issue is about the edge case when user:
- first create & start non-ephemeral workspaсe
- than stops it
- makes it ephemeral via attribute 
- once this workspace is deleted PVC cleanup is not performed
This issue is not fixed in master, but for me it does not look super urgent, since it could be treated as an edge case
