### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#114]
How to manage registered users and allow each of them have their own projects?

I'm going to set a che on a server, and allow the students of the class have their own workspace and own projects. But I found for a che instance, there is only one shared workspace and not support for user registering or custom workspace.

**Comment by TylerJewell** [comment]
Che is a single user, but multi workspace system.  You can manage access for multiple user by having many workspaces on the server with each having their own URL.  You can them assign each workspace to a different user.
You can also consider Codenvy which uses Che to offer a multi tenant, multi user and multi workspace offering.  Codenvy is free for use up to ten people simultaneously.

-Tyler

On Wed, Dec 9, 2015 at 3:34 AM -0800, "freewind" notifications@github.com wrote:

How to manage registered users and allow each of them have their own projects?

I'm going to set a che on a server, and allow the students of the class have their own workspace and own projects. But I found for a che instance, there is only one shared workspace and not support for user registering or custom workspace.

**Comment by TylerJewell** [comment]
Closed as this is covered by another issue.
