### ISSUE TITLE
Cannot install che on Openshift Origin. Keycloak fails to deploy: "openshift-identity-provider"

### ISSUE THREAD

**Issue by dwhiteOteemo** [eclipse-che/che#11403]
### Description
Attempting to deploy multiuser che on Openshift Origin but the deployment fails on keycloak. Get the following error:

Error syncing pod, skipping: failed to "StartContainer" for "che" with RunContainerError: "GenerateRunContainerOptions: secrets \"openshift-identity-provider\" not found"

Followed the instructions and launched the deployment with "deploy_che.sh --multiuser" but not able to figure what's either missing or not configured correctly.

### Reproduction Steps
1. curl -fsSL https://raw.githubusercontent.com/eclipse/che/master/deploy/openshift/deploy_che.sh -o deploy_che.sh
2. oc login <using developer/developer>
3. . ./deploy_che  --multiuser

**OS and version:**  
Amazon Linux ami-04681a1dbd79675a5 us-east-1
Linux version 4.14.70-72.55.amzn2.x86_64 (mockbuild@ip-10-0-1-219) (gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)) #1 SMP Wed Sep 19 19:09:24 UTC 2018
  

**Diagnostics:** 
Attempting to deploy directly from the template templates/multi/keycloak-template.yaml has the same result.

Error syncing pod, skipping: failed to "StartContainer" for "che" with RunContainerError: "GenerateRunContainerOptions: secrets \"openshift-identity-provider\" not found"

**Comment by eivantsov** [comment]
@dwhiteOteemo can you make sure that in your template the following env is set to optional? https://github.com/eclipse/che/blob/master/deploy/openshift/templates/multi/keycloak-template.yaml#L64

**Comment by dwhiteOteemo** [comment]
Thanks. I ended up setting 

export SETUP_OCP_OAUTH=true
export KEYCLOAK_USER=admin
export KEYCLOAK_PASSWORD=admin

And that got me past the keycloak issue.  Apart from the above, what other env variables do I need for multiuser on openshift? Couldn't really tell from the install guide. Pretty sure all my problems are based on not having the right vars. 

OAuth client ID=
OAuth client secret=

**Comment by dwhiteOteemo** [comment]
Thanks, I found the problem. We we're using 3.6 of Openshift Origin. When I switched to 3.10 everything worked.
