### ISSUE TITLE
Create Selenium test covered "start Theia in hosted mode and test the plugin"

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11400]
### Description
Cover next steps with Selenium tests:
 - do all steps which described in issue: https://github.com/eclipse/che/issues/11327
 - open command palette by "CTRL+ SHIFT + P ";
 - select folder projects/che-dummy-plugin/ui as Hosted Plugin Path:
 - click “Open” to start the new IDE instance in a new browser tab
 - in root window open the command palette, type “Hello” and select the “Hello World” command
 - modify the source code of the plugin and change the message to “Aloha Che!”
 - check that modification is automatically applied and deployed

**Comment by benoitf** [comment]
FYI there are E2E tests for theia there
https://github.com/eclipse/che/tree/master/dockerfiles/theia/e2e/cypress/integration/theia

**Comment by Ohrimenko1988** [comment]
@benoitf Of course you are right. But we have very urgent requirement for creating and tracking this functionality. And the simplest way is creating of the selenium test and run it in common scope on the existing infrastructure. Thank you for attention. We are definitely should figure out how to work with "Cyprus".

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11783
