### ISSUE TITLE
Ask a user to remove installer from a workspace when they enables WS.NEXT editor or plugin

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11401]
### Description
Now we can enable WS.NEXT editor and plugins from UD. And we even have UI for that on the creation of a  workspace. But this UI allows a user to enable WS.NEXT plugins without disabling Che 6 installers. 
[This](https://github.com/eclipse/che/pull/11392) PR would prevent the start of such a workspace and that would mean that UD would create invalid WS from UI. 
It would be a way better UX if we adapt UD to these changes and show user pop-up dialog to remove installers from the workspace if the user tries to enable plugin/editor. We can also add a link to docs about that (they are missing for the time being as far as I know).

### Reproduction  Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@ashumilova FYI

**Comment by ashumilova** [comment]
we took to the current sprint
