### ISSUE TITLE
Add permanently displayed message when IDE lost connection to ws-agent

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#11406]
The problem is when ws-agent is down by some reason (OOM or so) IDE react displaying notification, disabling files menu, clearing project tree etc. But if user miss notification there is nothing telling him that IDE is not normally functioning (off-line in fact)

**Comment by slemeur** [comment]
+1

**Comment by RomanNikitenko** [comment]
I investigated the issue and as far as I can see we have the following use cases:
- ws agent is stopped and some files are opened
we show warning message during a few seconds only to inform user why we switch files to read-only mode
![warning](https://user-images.githubusercontent.com/5676062/46596370-041b0000-cae5-11e8-808e-1c125526fd63.png)
 and permanently displayed notification with proposition to restart ws agent
![notification](https://user-images.githubusercontent.com/5676062/46596387-0da46800-cae5-11e8-96e4-d87cb4880a5c.png)
- ws agent is stopped and any files are not opened
we show only permanently displayed notification with proposition to restart ws agent
![notification](https://user-images.githubusercontent.com/5676062/46596405-19902a00-cae5-11e8-963a-15f10c81e006.png)
- ws agent is stopped and user is trying to open this workspace from dashboard or refresh current page
we do not display any warnings, notifications and so on 
![current_behavior](https://user-images.githubusercontent.com/5676062/46597080-578e4d80-cae7-11e8-9016-f1737fcdb139.gif)

I added fix for last case  - when IDE is initialized and ws agent is not running, the new behavior is
![new_behavior](https://user-images.githubusercontent.com/5676062/46597094-5eb55b80-cae7-11e8-9b06-23fb0c4d59c6.gif)

Please let me know if I should to change behavior for first two cases or you see another cases.

**Comment by slemeur** [comment]
sounds good to me.
thanks @RomanNikitenko

**Comment by gazarenkov** [comment]
This message is fine
Generalizing of what you said: make sure IDE is in-sync with ws-agent state and behaves accordingly.
