### ISSUE TITLE
Implementing a new language by LS-Sidecars in Eclipse Che

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#11415]
I'm currently following the LS-Sidecar implementation in the Eclipse Che document. However, I have come across a question on how to use a dockerfile for a language that I created by myself. If my language is in a Git repo, how do I access it by a dockerfile when implementing the sidecar? If anybody can answer, it will be much appreciated.

**Comment by SharkJ** [comment]
This is the sample Dockerfile given in the Eclipse Che doc.

# inherit an image with node.js and npm - runtime requirements for TypeScript LS
FROM eclipse/node

# install socat
RUN sudo apt-get install socat -y && \
    sudo npm install -g typescript@2.5.3 typescript-language-server@0.1.4

# run socat that listens on port 4417 with exec command that starts LS
CMD socat TCP4-LISTEN:4417,reuseaddr,fork EXEC:"typescript-language-server --stdio"


It is stated in the document to start the language server in the entrypoint. This is where I'm confused. If I am to implement a new language server (for a new language), where do I direct the entrypoint to? Can I add my language server to github and build an image from it to be included as the entrypoint, or is there any other way to do it?

**Comment by eivantsov** [comment]
@SharkJ say, you have built your language server locally, and the binary name is `myls`. Your Dockerfile will look like

```
ADD myls /home/user/myls
CMD socat TCP4-LISTEN:4417,reuseaddr,fork EXEC:"myls"
```

**Comment by SharkJ** [comment]
> @SharkJ say, you have built your language server locally, and the binary name is `myls`. Your Dockerfile will look like
> 
> ```
> ADD myls /home/user/myls
> CMD socat TCP4-LISTEN:4417,reuseaddr,fork EXEC:"myls"
> ``

Do I still have to include the "FROM eclipse/node" entrypoint in the dockerfile?
And "RUN sudo apt-get install socat -y && \ sudo npm install -g typescript@2.5.3 typescript-language-server@0.1.4" is no longer needed, am I correct?

**Comment by eivantsov** [comment]
@SharkJ well, if your language server supports listening on tpc socket, you do not need `socat`. As to base image, in the example above I used eclipse/node since Typerscript language server needs nodejs and npm. You can use whatever base image makes sense for your particular language server.

**Comment by SharkJ** [comment]
Thank you very much! I think I understand now.

**Comment by SharkJ** [comment]
> @SharkJ say, you have built your language server locally, and the binary name is `myls`. Your Dockerfile will look like
> 
> ```
> ADD myls /home/user/myls
> CMD socat TCP4-LISTEN:4417,reuseaddr,fork EXEC:"myls"
> ```

I created a simple LS using this tutorial 
http://www.eclipse.org/Xtext/documentation/102_domainmodelwalkthrough.html

I have 5 folders in this server directory that I created. 
org.example.domainmodel
org.example.domainmodel.ide
org.example.domainmodel.tests
org.example.domainmodel.ui
org.example.domainmodel.ui.tests

Which bin directory should I use out of these five folders? I explored some existing language servers and their file structures and content is much different than what I have created.

**Comment by SharkJ** [comment]
I created a dockerfile including my language server, and now I'm getting this error.

![untitled](https://user-images.githubusercontent.com/23653853/46340429-039ce800-c653-11e8-8d94-c6b3409aa535.png)

What might be the cause? think something's wrong with the path specified.

**Comment by SharkJ** [comment]
Is the binary file a .bat file?

**Comment by SharkJ** [comment]
I was going through[ this tutorial,](https://tomassetti.me/language-server-dot-visual-studio/)  and had a question whether a similar approach is possible in eclipse or eclipse che. The tutorial is about building a language server and client for an Antlr4 based language (Dot), extending Visual Studio. Is it possible to do using LS-sidecars, and how do I do it?
