### ISSUE TITLE
Selenium Tests Rely on Sort Order in "Document Symbols" Widget

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11417]
there are a bunch of failures in the language server tests (both master and jdt.ls) in "checkGoToSymbolFeature()"
I think in this case, the tests are wrong: the use org.eclipse.che.selenium.pageobject.AssistantFindPanel.clickOnActionNodeWithTextContains(String), which selects all node containing the string in question.
This selects the first item, which is not something we should check for: the sort order of the symbols is up to the language server and can change at any time.

**Comment by dmytro-ndp** [comment]
@tsmaeder: could you, please, add the link to the failed test results on CI?

**Comment by rhopp** [comment]
This test was implemented in selenium suite (using GWT). As GWT is not a focus anymore, we will not work on this one (in selenium suite).
Closing.
