### ISSUE TITLE
Selenium Tests for "References" (for Example) Should Check for Selection, not Position

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11435]
Many selenium tests for language features like "find references" use the current location in the editor to check that a reference has been opened in the editor. Instead, we should check that the match has been selected in the editor. 
I understand that there is currently no way to check for this from Selenium, we need to build this into the gwt ide (Javascript functions to access the Editor selection)

**Comment by rhopp** [comment]
GWT & Selenium suite is slowly being decommissioned. Closing.
