### ISSUE TITLE
Workspaces that fail recovery on startup can be broken completely

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#11447]
### Description
When the Che server fails to recover a workspace on startup, it does nothing to clean up its database. As a result, the entry for that workspace stays in the relevant tables and prevents that workspace from being started again. A not-useful error is logged to the console when the user tries to start such a workspace:
```
Workspace 'asdf:wksp-z042' with id 'workspace3ob15dnpujw9eamy' start failed
```
and a message `Runtime is already started` is displayed to the user. 

In cases where Che is running under a memory limit, this can prevent affected users from starting *any* workspaces until their namespace is cleaned.

### Reproduction Steps
1. Deploy Che multiuser on minishift
2. Log in, create and start workspace in dashboard
3. Scale Che server deployment config to 0
4. modify postgres database: e.g. `owner_id` for that workspace to `0` in table `che_k8s_runtime`
5. Scale Che server back to 1

then:
- Che will log 
   ```
   An error occurred while attempted to recover runtimes using infrastructure 'openshift'. Reason: 'Couldn't recover runtime 'workspace3ob15dnpujw9eamy:default'. Error: The user `0` doesn't have the required `use` permission for workspace `workspace3ob15dnpujw9eamy`'
   ```
   on startup
- The database will be unmodified regarding this workspace
- In the dashboard the workspace will appear as `STOPPED`, and will log errors above when attempting to start.
- Deleting the workspace via the dashboard gives the log 
   ```
   Workspace is being removed while Kubernetes runtime state 'workspace3ob15dnpujw9eamy:default:0' exists. This situation indicates a bug that needs to be reported. Runtime state will be removed from DB, but Kubernetes resources (pods, pvcs, etc.) won't be cleaned up.
   ```

**OS and version:**    
Che on OpenShift

**Comment by fpmJamesReeves** [comment]
Is it possible to correct this issue?  If not then it possible to recover my code?

I run Eclipse Che through my browser so after I login I go to my workspaces.  The workspace shows "Stopped" but when I try to run it I get the message "Failed runtime is already started".  If I try to Open the workspace i just get the Loading screen and it never loads.

I have searched but was not able to find any answers to my questions above.

I was just testing out Che and actually had some code that I would like to recover instead of having to start from scratch.

**Comment by amisevsk** [comment]
@fpmJamesReeves It is recoverable, but not in a very user-friendly way at the moment. Basically what you need to do is remove the workspace deployment through the OpenShift console directly. 

How are you running Che at the moment -- is it local or through e.g. openshift.io?

**Comment by fpmJamesReeves** [comment]
openshift.io through my browser: https://che.openshift.io/dashboard/#/

**Comment by amisevsk** [comment]
@fpmJamesReeves I'm looking into a solution for you; sorry for the inconvenience.

**Comment by amisevsk** [comment]
@fpmJamesReeves Could you try accessing the workspace now? che.openshift.io moved to Che 6.12 earlier today and it fixed an [issue](https://github.com/eclipse/che/issues/11445) around workspace startup and it *may* have solved your problem.

**Comment by fpmJamesReeves** [comment]
I was able to finally get into my workspace.  Initially it would not load and get the errors below.  I was able to stop the workspace but could not get it to start again BUT I was able to "Open" it and it brought up my workspace with no problems.

After I got my workspace up I immediately download all the source code.  I do plan on connecting it to Github soon.

Thank you so much for your assistance.

![image](https://user-images.githubusercontent.com/43866934/46676546-fc6b6200-cb9d-11e8-804a-f1a63fa9deb2.png)

**Comment by amisevsk** [comment]
@fpmJamesReeves I'm so glad you were able to recover your code.

The failed loading and having to restart it is somewhat expected -- what happened behind the scenes is that Che cleaned up the old OpenShift resources and then recreated them when you restarted. Not ideal but like so many things, it just needed to be turned off and on again :).

**Comment by garagatyi** [comment]
@sleshchenko Should be fixed now, right?

**Comment by sleshchenko** [comment]
@garagatyi Need to recheck. I think that the described scenario is not handled.

**Comment by amisevsk** [comment]
My thinking for this issue was originally that if a workspace can't be recovered for whatever reason, it should be stopped. As it stands (and I haven't tested since recovery was made async to startup), I think failed-to-recover workspaces stay in the DB as running, which can cause inconsistency.

**Comment by garagatyi** [comment]
@sleshchenko  But for the new runs of workspaces we would have them cleaned up from the DB after a timeout, right?

**Comment by sleshchenko** [comment]
@garagatyi Not for this case when an error happens during Runtime recovering.

**Comment by RafaelMiquelino** [comment]
@amisevsk, I'm getting this message "Error: Failed to run the workspace: "Runtime is already started"" on my workspace running on che.openshift.com. Did you manage to find a solution for that? My project is hosted at GitHub but there is some good amount of work since the last commit/push. Would appreciate if you have a solution fo that. Thanks.
