### ISSUE TITLE
Che LS-Sidecar Initializing Error: Broken Pipe

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#11474]
I built a language server sidecar made using XText and set it up in Eclipse Che as mentioned in the che document. Now, when I create a file with the file extension of my new LS, a Language Server starts to initialize. However, after some time, a timeout error occurs and the following error is displayed:

![broken pipe](https://user-images.githubusercontent.com/23653853/46462386-f4e33c00-c7de-11e8-9713-e8e49595e31c.png)

Following is my Dockerfile that I run my language server in:
```
FROM barais/eclipse-xtend
ADD build/libs/dsl-language-server-ls.jar dsl-language-server-ls.jar
RUN sudo apt-get install socat
CMD socat TCP4-LISTEN:4417,reuseaddr,fork EXEC:"mydsl"
```
Apart from this I included everything mentioned in the che document.

Please, any help is highly appreciated.

**Comment by SharkJ** [comment]
Is it possible to add an Xtext LS as a sidecar in Eclipse Che?

**Comment by eivantsov** [comment]
@SharkJ shouldn't your exec be `java -jar dsl-language-server-ls.jar`

**Comment by SharkJ** [comment]
Yes it is!  I had to install jdk as well to run it. It is working now! Thank you so much! 👍 👍 👍
