### ISSUE TITLE
[ JDT LS ] Can't move java class to the package which placed in the same directory

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11472]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
  - Run default java stack with default spring project
 - Create any lava class in "org.eclipse.che.examples" package
 - Create new package in the "org.eclipse.che.examples"
 - Click on the created java class 
 - Run "Assistant" -> "Refactoring" -> "Move" command
 - In the opened "Move item" form expanf "web-java-spring" -> "src/main/java" nodes
 - Pay attention that created package doesn't display

**Expected behavior:**
Created package is displayed in the destination list.

**Observed behavior:**
Created package doesn't displayed.

**Attachment:**
![rtrtt](https://user-images.githubusercontent.com/22724619/46458803-a5d9de80-c7bf-11e8-944d-e9bd97c7b2f6.png)

**OS and version:**    
JDT LS assembly Che 6.12.0 ; Chrome 68; Fedora 28;

**Comment by tsmaeder** [comment]
We're not getting change notifications: https://github.com/eclipse/che/issues/10794
