### ISSUE TITLE
Support running Che 7 plugins and runtime in separate pods

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11476]
### Description

Currently in Kube and OpenShift infrastructure all Che 7 plugins, editors and runtime are spawned in one unique fat pod:

![image](https://user-images.githubusercontent.com/606959/46469406-8fd61900-c7d3-11e8-913c-33130d5e26fb.png)

This was a limitation that we had to live with because all containers needed access to the same Persistent Volume and we needed to support RWO Persistent Volumes first. 

But this configuration has many drawbacks:

- ports collisions
- ~~cannot support deployment/deployment config based recipes~~ configurations with more than one pod
- cannot run short living sidecars
- cannot restart plugins
- cannot restart runtime

This epic is about supporting an alternative configuration with every container running in its own Pod:

![image](https://user-images.githubusercontent.com/606959/46470018-7cc44880-c7d5-11e8-845b-593af79baebd.png)

This configuration should be the default when the workspace persistent volume is RWX.

**Comment by garagatyi** [comment]
We can separate sidecars that do not declare the dependency on the projects' volume even now!
Apart from that, we can implement different strategies of volume content syncing. RWX is not supported everywhere, but we can add also use sync sidecar to emulate it. 
I would start from separating non-volume dependent sidecars to separate pods.

**Comment by ibuziuk** [comment]
@garagatyi @l0rd I have created an issue for supporting non-volume dependent sidecars as separate pods in rh-che [1]. Do you happen to have some ideas about other potential sub-tasks that we could add to the next sprint related to this epic ?

[1] https://github.com/redhat-developer/rh-che/issues/1005

**Comment by l0rd** [comment]
@ibuziuk the goal of these 2 issues is to run containers in distinct pods. But besides that they are not related (e.g one is a subtask of the other). Let me clarify:
- this issue is about taking advantage of eventual RWX PVs
- https://github.com/redhat-developer/rh-che/issues/1005 is about containers that don't need persistence and can be run in a distinct POD

As mentioned in a call we had today I would prioritize the work in this order:
1. support fully ephemeral workspaces (che 7)
2. run containers that don't need access to the PV in a distinct Pod
3. take advantage of RWX PR when available

**Comment by l0rd** [comment]
This issue is not current anymore. We are rather aiming to run all IDE services in the developer container.
