### ISSUE TITLE
[ JDT LS ] Unexpected files when add into git index

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#11478]
### Description
**Reproduction Steps:**
* Run default java stack with default _web-java-spring_ project
* Select the project
* Perform git status using git menu commands
* Add to index

**Expected behavior:** 
* only expected files should be added to index

**Observed behavior:**
* unexpected files are added to index
 
**Che version**: JDT LS assembly Che 6.12.0
**OS and version:** Fedora 28
**Che install:** OCP-multiuser
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**screenshot:**

![git-index](https://user-images.githubusercontent.com/5408906/46470074-0841d780-c7de-11e8-81ec-65cdab1c41a8.png)

![add-to-index](https://user-images.githubusercontent.com/5408906/46470316-d8470400-c7de-11e8-81b0-0f83e2be290e.png)

**Comment by tsmaeder** [comment]
These files are normal: jdt.ls runs an eclipse workspace and these files are the metadata. Like .vscode.

**Comment by vkuznyetsov** [comment]
not actual
