### ISSUE TITLE
[ JDT LS ] Code Formatter category not exists in Preferences form

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11487]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
1. Create and start workspace from **Java** stack with **web-java-spring** project.
2. Wait for **Java** language server initialized.
3. Open **Preferences** form by menu **Profile** -> **Preferences**.

**Expected behavior:**
**Code Formatter** category exists at the top of **Preferences** form(see screenshot 1).

**Observed behavior:**
**Code Formatter** category missed(see screenshot 2).

**Attachment:**
Screenshot 1:
![selection_138](https://user-images.githubusercontent.com/7760565/46475289-cc167300-c7ed-11e8-8169-83c7af1ece76.png)

Screenshot 2:
![selection_137](https://user-images.githubusercontent.com/7760565/46475296-cf116380-c7ed-11e8-835a-c679e45f9b9a.png)

**OS and version:**    
JDT LS assembly Che 6.12.0; Chrome 68; Fedora 28;

**Comment by tsmaeder** [comment]
@SkorikSergey could you verify and close, please?

**Comment by SkorikSergey** [comment]
Fixed.
