### ISSUE TITLE
[ JDT LS ] Error highlighting doesn't work in the pom.xml file after typing unexisted artifact

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11482]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
 - Run default "Java" stack with default "spring" project
 - Wait until workspace is started
 - Open "pom.xml" file
 - In the 16-th row change 
```<groupId>javax.servlet</groupId>``` 
to 
```<groupId>unexisted-group-id</groupId>``` 
 - Pay attention to error marker which displayed in the 1-st row

**Expected behavior:**
The error marker is displayed in the 16-th row and wrong group id highlited by red.

**Observed behavior:**
The error marker is displayed in 1-st row, not existed group id is not highlited.

**Attachment:**
![ttttttttt](https://user-images.githubusercontent.com/22724619/46473914-3fb68100-c7ea-11e8-99a2-e3e400ca7eb8.png)

**OS and version:**    
JDT LS assembly Che 6.12.0; Chrome 68; Fedora 28

**Comment by tsmaeder** [comment]
This happens in VSCode, as well. jdt.ls issue, then.
