### ISSUE TITLE
[ JDT LS ] The progress of language server resolving doesn't displayed in the bottom status bar 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11481]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

**```Description:```**
Do not meet expectations according to this issue:
https://github.com/eclipse/che/issues/8412
![screenshot from 2018-10-04 15-02-13](https://user-images.githubusercontent.com/22724619/46472659-8d30ef00-c7e6-11e8-8765-e36c6847b58c.png)

### Reproduction Steps
 - Deploy JDT LS assembly
 - Start default "java" stack with default "spring" project
 - Wait until workspace is started
 - Wait for maven progress bar disappearance
 - Pay attention to the terminal output  and bottom status bar

**Expected behavior:**
The progress bar of the language server starting is displayed in the bottom status bar

**Observed behavior**
The language server is starting (according to the terminal output) but the progress bar doesn't display

**Attachment:**
![hhhhh](https://user-images.githubusercontent.com/22724619/46472207-1e9f6180-c7e5-11e8-9328-0b9a3828528d.png)

**Browser terminal output**
![gggfgfg](https://user-images.githubusercontent.com/22724619/46472440-d59bdd00-c7e5-11e8-9cc9-1dadd6e0420e.png)

**OS and version:**    
JDT LS assembly Che 6.12.0 ; Chrome 68; hedora 28

**Comment by tsmaeder** [comment]
Yes, this is the expected behaviour: jdt.ls does not send progress messages for startup, it sends status messages, which are not expected to be progress.
