### ISSUE TITLE
Add Theia Plugin APIs to support VS Code OpenShift Tooling

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11488]
### Description

When the work to add [the necessery Theia Plugin APIs to support vscode Kubernetes tooling](https://github.com/eclipse/che/issues/10574) is completed we should analyse what needs to be done to support [vscode OpenShift tooling](https://github.com/redhat-developer/vscode-openshift-tools) too.

**Comment by azatsarynnyy** [comment]
Since the OpenShift Connector plugin depends on the K8s plugin we need https://github.com/theia-ide/theia/issues/3645

**Comment by l0rd** [comment]
cc @jeffmaury

**Comment by azatsarynnyy** [comment]
Closing it since OpenShift Connector Che Plugin is added to the plugin registry https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/redhat/vscode-openshift-connector
