### ISSUE TITLE
Using che-install-plugin.sh to install example IDE plugin

### ISSUE THREAD

**Issue by objectiser** [eclipse-che/che#1148]
Hi

I built Che and the simple IDE extension from source. I then copied the che-examples-action-<version>.jar into the plugins/ide folder of the Che assembly. Then I ran the che-install-plugin.sh command, which seemed to detect the plugin:
###### 

CHE SDK: Adding IDE extensions as dependencies
###### 

Extension found org.eclipse.che:che-examples-action:4.2.0-RC1-SNAPSHOT
    Including GWT module examples.MyExtension
Found: 1 extension(s)

However, when I started up the server in the new'y build plugins/assembly/target folder, and opened the brower, created a workspace, etc, it didn't show the My Action menu item.

When looking at the documentation on https://eclipse-che.readme.io/docs/developing-extensions IDE Extension Example, it only talks about manually changing the maven files, etc, before doing a build - but I assume that these steps were automatically being performed by the che-install-plugin.sh script? If that is correct, any ideas what I have missed?

Thanks in advance.

**Comment by TylerJewell** [comment]
Hello:

Everything that you said was accurate.  If you ran the script without modifying any options then the Che assembly should be modified with your changes.  The output seems to indicate that happened.   Do you have the full output to share?

**Comment by ghost** [comment]
@TylerJewell I confirm that the extension never ends up in the assembly. No entries in GWT.xml and pom, no jar in tomcat's webapps.

**Comment by objectiser** [comment]
Ok great - was just about to upload the build log, but I guess not necessary now.

**Comment by ghost** [comment]
Yes, the manual way (adding pom deps and gwt inheritance) still works:

![menu](https://cloud.githubusercontent.com/assets/5337267/14878586/2347d322-0d2d-11e6-8a16-53e6057dd22f.png)

We'll take a look at what has broken in the script. Thanks for letting us know.

**Comment by TylerJewell** [comment]
@objectiser @eivantsov -- Head scratcher for me.  I just installed from master (4.3.0 RC1-SNAPSHOT) and was able to get the server-side extension to compile and was able to use the utility script to get it added.  I did not yet try the IDE extension, however.  Will you go ahead and post your logs for output?

**Comment by ghost** [comment]
@TylerJewell I tried IDE extension. Will give it another shot later today.

**Comment by objectiser** [comment]
@TylerJewell The log is here: http://paste.fedoraproject.org/361348/14620343

Thanks.

**Comment by TylerJewell** [comment]
@objectiser Thank you.  Most helpful.  Will you confirm that you ran the script with no options?  You didn't have any flags on the command.

**Comment by objectiser** [comment]
I just used the assembly option.

**Comment by TylerJewell** [comment]
@objectiser @eivantsov I can confirm the issue and have a resolution. It turns out that pom model writing of the IDE extension was being overwritten because we use the InstallExtension utility twice.  Long story short, your extension was being added and then it was being removed.

I'll issue a fix to the che-install-plugin.sh script shortly.  @eivantsov - FYI, the IDE extension no longer compiles with 4.3.0-RC1-SNAPSHOT.  The dependencies have shifted around and it looks like the notify() method has different parameters.  I had to update the pom.xml and the source file to make it work.

Fix: https://github.com/eclipse/che/pull/1164/files

**Comment by ghost** [comment]
I will update parent versions for example extentions.

**Comment by ghost** [comment]
@objectiser @TylerJewell I merged the PR and updated sample extensions to use 4.2.1 parent.

@objectiser you may just grab the updated script here https://raw.githubusercontent.com/eclipse/che/master/assembly/assembly-main/src/assembly/bin/che-install-plugin.sh and give it another shot.

**Comment by TylerJewell** [comment]
@objectiser This is now fixed in master.
https://github.com/eclipse/che/pull/1164

Going to close this issue.  Thank you for reporting it.

**Comment by objectiser** [comment]
Sorry was away so didn't get to try - will try it out soon.

Thanks for fixing so quickly.
