### ISSUE TITLE
Volumes Are not Writeable by Container User

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11486]
This is in the jdt.ls branch.

1. Create a centos-blank workspace
2. Add a volume to the configuration, for example /homer/user/foobar
3. Open the workspace.
4. In the terminal, cd to ~/foobar
5. enter the command "touch foobar.txt".
6. Observe: you get "permission denied"

**Comment by eivantsov** [comment]
@tsmaeder what OpenShift version and cluster type? I cannot reproduce with Origin 3.9 running locally

**Comment by tsmaeder** [comment]
It's a docker limitation that non-existing dirs for persisten volumes are created as root.
