### ISSUE TITLE
mysql-support cannot be resolved when -Pintegration profile not enabled, so MYSQL Tck Tests can't be built

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#11495]
### Description

I build Che like this:

````
mvn clean deploy '-Pfast,native,!docker,!docs' -V -ff -B -e -Dskip-enforce -DskipTests \
-Dskip-validate-sources -Dfindbugs.skip -DskipIntegrationTests=true \
-Dmdep.analyze.skip=true -Dmaven.javadoc.skip -Dgpg.skip \
-Dorg.slf4j.simpleLogger.showDateTime=true \
-Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss \
-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
-DnodeDownloadRoot=http://nodejs.org:80/dist/ \
-DnpmDownloadRoot=http://registry.npmjs.org:80/npm/-/ \
-DnpmRegistryURL=http://registry.npmjs.org:80/ \
-DYARN_REGISTRY=http://registry.yarnpkg.com:80/ \
-Dche.dashboard.version=6.12.0-20181004.124001-96
````
but 

````
15:03:16 [INFO] Che Multiuser :: MYSQL Tck Tests ................... FAILURE [01:21 min]
15:03:16 [ERROR] Failed to execute goal on project che-multiuser-mysql-tck: Could not resolve 
dependencies for project org.eclipse.che.multiuser:che-multiuser-mysql-tck:jar:6.12.0.redhat-00013:

Could not find artifact org.eclipse.che.core:mysql-support:jar:6.12.0.redhat-00013 in 
indy-mvn (http://indy.project-newcastle.svc.cluster.local/api/folo/track/build_eclipse-che-master-3-dashboard-upstream-SNAPSHOT_20181004.1441/maven/group/build_eclipse-che-master-3-dashboard-upstream-SNAPSHOT_20181004.1441) -> [Help 1]
````

because not building with the `-Pintegration` profile. So this: 

````
        <dependency>
            <groupId>org.eclipse.che.core</groupId>
            <artifactId>mysql-support</artifactId>
            <scope>test</scope>
        </dependency>
````
(and probably others too) cannot resolved in [che/multiuser/integration-tests/che-multiuser-mysql-tck/pom.xml:95](https://github.com/eclipse/che/blob/master/multiuser/integration-tests/che-multiuser-mysql-tck/pom.xml#L95)

Why? Because that artifact is only built when the `-Pintegration` profile is enabled:

````
    <profiles>
        <profile>
            <id>integration</id>
            <modules>
                <module>postgresql-tck</module>
                <module>mysql-tck</module>
            </modules>
        </profile>
    </profiles>
````
-- https://github.com/eclipse/che/blob/master/wsmaster/integration-tests/pom.xml#L34

Proposed solution:

move these test-time deps into the integration profile so they're NOT expected to be resolved when we're not building & running ITests

### Reproduction Steps

See above. Build failed in NCL here:

http://orch.cloud.pnc.engineering.redhat.com/pnc-web/#/projects/153/build-configs/504/build-records/8229

Full log:

http://orch.cloud.pnc.engineering.redhat.com/pnc-rest/rest/build-records/8229/log

**OS and version:**    

Linux pnc-ba-pod-509158 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Diagnostics:** 

http://orch.cloud.pnc.engineering.redhat.com/pnc-rest/rest/build-records/8229/log

**Comment by riuvshin** [comment]
release 6.12.0 failed with same issue.
