### ISSUE TITLE
Find out the minimum memory requirements to run a Che 7 workspace

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11499]
### Description

To be able to use a Che 7 preview workspace with minishift today we are suggesting to start minishift with 8GB of memory:

```bash
minishift start --docker-opt userland-proxy=false --memory 8GB
```

Theia sidecar needs 2GB: currently it runs both jdt LS and ts LS (besides Theia itself), wsmaster needs ~1GB. And then we need to consider a runtime and eventual plugins. Would that fit in 4GB? 6GB?

@benoitf @evidolob @ashumilova @sunix any suggestion?

**Comment by sunix** [comment]
From my experience, building theia (running `yarn`) + running a theia instance (+ Typescript LS) in the same container requires at least 3 GB.
It is hard to tell, it would be good to have a kind of widget that shows the memory usage inside a workspace ... if memory counts, we have to provide tools for users to know what is wrong in his workspace.

**Comment by l0rd** [comment]
@sunix I have come to your same conclusions. I could work fine with 4GB of RAM. Less than that can provoke OOM exceptions in workspace containers. Closing this issue for now.

A memory consumption dashboard is a nice plugin idea ;-)
