### ISSUE TITLE
[ JDT LS ] Dependencies do not resolve after fixing an errors in the "pom.xml" file

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11493]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
 - Start default "Java" stack with default "Spring" project
 - Open "GreetingController.java" file
 - Pay attention that any errors are not displayed
 - Open "pom.xml" file
 - Make some error in "pom.xml" file and wait for error marker
 - Click on "GreetingController" editor tab
 - Pay attention to the displayed error markers
 
**Expected behavior:**
The "GreetingController" editor tab displayed without errors

**Observed image:**
The "GreetingController" editor tab displayed with errors

**Attachment:**
![peek 2018-10-04 18-03](https://user-images.githubusercontent.com/22724619/46483320-06890b80-c800-11e8-817f-8e3f249cb5cd.gif)

**Dev-machine-logs:**
![screenshot from 2018-10-04 18-04-18](https://user-images.githubusercontent.com/22724619/46483299-f8d38600-c7ff-11e8-9317-449aaa0fcd63.png)

**OS and version:**    
JDT LS assembly Che 6.12.0; Chrome 68; Fedora 28

**Comment by tsmaeder** [comment]
We never get a notification from jdt.ls for the GreetingController file. Looks like a jdt.ls problem

**Comment by tsmaeder** [comment]
Yup. Confirmed in vscode.
