### ISSUE TITLE
Workspace Connection Error eclipse-che-4.2.0

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#1149]
Hello, I already have eclipse-che-4.0.0-RC11 and I can create projects. Now I try to update its version so I have downloaded eclipse-che-4.2.0 to test: I have the same error each time when starting the workspace agent: "Workspace connection error" (see error in detail below).  I run che with: bin/che.sh run. I am on ubuntu 14.04.
Can it be because of the previous che version? What changed between the two versions that could justify this error?

And to be honest, I also tried the unsigned nightly (eclipse-che-4.3.0-RC1-SNAPSHOT), that gives the error "Error: Can't load project types: Error: 404 Not Found http://localhost:8080 at ... see detailed picture". 
![screenshot from 2016-04-27 16 17 11](https://cloud.githubusercontent.com/assets/18055132/14857524/dec1a98e-0c9c-11e6-9950-672061bd20cd.png)

Error 4.2.0 in detail:
Workspace Connection Error
It seems that your workspace is running, but we cannot connect your browser to it. This commonly happens when Che was not configured properly. If your browser is connecting to workspaces running remotely, then you must start Che with the --remote:<ip-address> flag where the <ip-address> is the IP address of the node that is running your Docker workspaces.Please restart Che with this flag. You can read about what this flag does and why it is essential at: https://eclipse-che.readme.io/docs/configuration#envrionment-variables.

**Comment by ghost** [comment]
Do you have any local configuration exported?  Like workspace from RC11? I haven't tried the nightly but 4.2 works ok for me.

**Comment by ghost** [comment]
@agnesagnes Please take a look at my comment here - https://github.com/eclipse/che/issues/1138#issuecomment-215317966

Try it in an incognito window and/or clear cache.

**Comment by agnesagnes** [comment]
Great, it was that! Incognito window solved my two different problems. Thank you!

**Comment by els-pnw** [comment]
I have this problem in Incognito or not in 4.6.2 running on docker 1.10.

when I try in Firefox I get:
window.IDE.eventHandlers.initializationFailed@http://morbo.lab.eng.rdu.redhat.com:8080/che/esammons?uid=748344:39:27
mtb@_app-0.js:1970:145
ztb@_app-0.js:1976:57
_.yp@_app-0.js:4163:319
iM/<@_app-0.js:967:84

**Comment by ddementieva** [comment]
@eanxgeek How did you start Che? Have you added -r:$IP parameter to the Che start syntax, where $IP is a public IP of you server? 

Can you send a screenshot with a browser dev console opened? Also you need to make sure that ephemeral port range is opened.

**Comment by els-pnw** [comment]
@ddementieva I'll admit I am a bit new to docker so bear with me.   I set CHE_HOST_IP to the public IP address of my host server.  The behavior remained.  Based on what I've read, "under the hood", -r:$IP should be substituted with what ever you have set CHE_HOST_IP to.

Here are some info shots:

> # che info --networking
> 
>  WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled
> DEBUG: 
> DEBUG: ---------------------------------------
> DEBUG: -------- CHE CONNECTIVITY TEST --------
> DEBUG: ---------------------------------------
> DEBUG: Browser             => Workspace Agent (Hostname)   : Connection succeeded
> DEBUG: Browser             => Workspace Agent (External IP): Connection succeeded
> DEBUG: Che Server          => Workspace Agent (External IP): Connection succeeded
> DEBUG: Che Server          => Workspace Agent (Internal IP): Connection succeeded
> 
> # che info
> 
>  WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled
> DEBUG: ---------------------------------------
> DEBUG: ---------  CHE CLI DEBUG INFO  --------
> DEBUG: ---------------------------------------
> DEBUG: 
> DEBUG: ---------  PLATFORM INFO  -------------
> DEBUG: DOCKER_INSTALL_TYPE       = native
> DEBUG: DOCKER_HOST_IP            = 172.17.0.1
> DEBUG: IS_DOCKER_FOR_WINDOWS     = NO
> DEBUG: IS_DOCKER_FOR_MAC         = NO
> DEBUG: IS_BOOT2DOCKER            = NO
> DEBUG: IS_NATIVE                 = YES
> DEBUG: HAS_DOCKER_FOR_WINDOWS_IP = NO
> DEBUG: IS_MOBY_VM                = NO
> DEBUG: 
> DEBUG: ---------------------------------------
> DEBUG: ---------------------------------------
> DEBUG: ---------------------------------------
> INFO: 
> INFO: ECLIPSE CHE: FOUND IMAGE codenvy/che-launcher:latest
> INFO: ECLIPSE CHE: LAUNCHING LAUNCHER
> DEBUG: ---------------------------------------
> DEBUG: ---------  CHE DEBUG INFO  ------------
> DEBUG: ---------------------------------------
> DEBUG: 
> DEBUG: ---------  PLATFORM INFO  -------------
> DEBUG: DOCKER_INSTALL_TYPE       = native
> DEBUG: DOCKER_HOST_OS            = CentOS Linux 7 (Core)
> DEBUG: DOCKER_HOST_IP            = 172.17.0.1
> DEBUG: DOCKER_DAEMON_VERSION     = 1.10.3
> DEBUG: 
> DEBUG: 
> DEBUG: --------- CHE INSTANCE INFO  ----------
> DEBUG: CHE CONTAINER EXISTS      = YES
> DEBUG: CHE CONTAINER STATUS      = running
> DEBUG: CHE SERVER STATUS         = running
> DEBUG: CHE IMAGE                 = codenvy/che-server:latest
> DEBUG: CHE SERVER CONTAINER ID   = 07b1c72a9f5d
> DEBUG: CHE CONF FOLDER           = not set
> DEBUG: CHE DATA FOLDER           = /home/user/che/workspaces
> DEBUG: CHE DASHBOARD URL         = http://localhost:8080
> DEBUG: CHE API URL               = http://localhost:8080/api
> DEBUG: CHE LOGS                  = run `docker logs -f che-server`
> DEBUG: 
> DEBUG: 
> DEBUG: ----  CURRENT COMMAND LINE OPTIONS  ---
> DEBUG: CHE_PORT                  = 8080
> DEBUG: CHE_VERSION               = latest
> DEBUG: CHE_RESTART_POLICY        = no
> DEBUG: CHE_USER                  = root
> DEBUG: CHE_HOST_IP               = $HOST_SERVER_PUBLIC_IP
> DEBUG: CHE_LOG_LEVEL             = info
> DEBUG: CHE_HOSTNAME              = localhost
> DEBUG: CHE_DATA_FOLDER           = /home/user/che
> DEBUG: CHE_CONF_FOLDER           = not set
> DEBUG: CHE_LOCAL_BINARY          = not set
> DEBUG: CHE_SERVER_CONTAINER_NAME = che-server
> DEBUG: CHE_SERVER_IMAGE_NAME     = codenvy/che-server
> DEBUG: 
> DEBUG: ---------------------------------------
> DEBUG: ---------------------------------------
> DEBUG: ---------------------------------------

The log files don't appear to reveal anything, they seem to indicate everything is ok. 

And finally here is iptables, it could be the ephemeral ports.  I work on that next.
![screenshot from 2016-08-26 07-46-59](https://cloud.githubusercontent.com/assets/1113174/18004477/3f1702d8-6b62-11e6-9d1d-f9f6fe95a9c4.png)
![screenshot from 2016-08-26 07-46-40](https://cloud.githubusercontent.com/assets/1113174/18004484/42d0f442-6b62-11e6-8f73-6cd13fb980e7.png)

**Comment by ghost** [comment]
@eanxgeek  can you open browser dev console and share a screenshot? I'd like to take a look at failed websocket requests.

Also, can you confirm that the ephemeral port range is opened for morbo.lab.eng.rdu.redhat.com?

Your client (browser) cannot connect to a workspace agent that is running in a Docker container on the host where Che server is running. There can be multiple reasons: blocked websockets, filtered ports, firewall restrictions etc.

**Comment by els-pnw** [comment]
So to simplify things I set my docker command line options to include --iptabeles=false.  My system should be wide open at this point.

> # iptables -L
> 
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination         
> 
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination         
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination  

Nothing shows up in the dev console, assuming I'm accessing the correct one from "Open IDE".

![screenshot from 2016-08-26 09-48-53](https://cloud.githubusercontent.com/assets/1113174/18007510/5d35387e-6b72-11e6-8ee1-2286cdd51e08.png)

**Comment by TylerJewell** [comment]
@eanxgeek - Since this is centos 7, instead of disabling iptables, can you also check about firewalld?  `systemctl disable firewalld`.   We have had issues with centos7 and firewalld by default blocking certain incoming traffic.  We had another thread on this. 

About firewalld: http://www.liquidweb.com/kb/how-to-stop-and-disable-firewalld-on-centos-7/
Linking in reference to the old issue: https://github.com/eclipse/che/issues/1924

**Comment by ghost** [comment]
@eanxgeek i mean Chrome dev console - F12.

**Comment by slemeur** [comment]
I'm running into the same issues, running latest nightly build.

DEBUG: ---------------------------------------
DEBUG: ---------  CHE DEBUG INFO  ------------
DEBUG: ---------------------------------------
DEBUG: 
DEBUG: ---------  PLATFORM INFO  -------------
DEBUG: DOCKER_INSTALL_TYPE       = docker4mac
DEBUG: DOCKER_HOST_OS            = Alpine Linux v3.4
DEBUG: DOCKER_HOST_IP            = 192.168.65.2
DEBUG: DOCKER_DAEMON_VERSION     = 1.12.0
DEBUG: 
DEBUG: 
DEBUG: --------- CHE INSTANCE INFO  ----------
DEBUG: CHE CONTAINER EXISTS      = YES
DEBUG: CHE CONTAINER STATUS      = running
DEBUG: CHE SERVER STATUS         = stopped
DEBUG: CHE IMAGE                 = 
DEBUG: CHE SERVER CONTAINER ID   = 614ca958a209
DEBUG: CHE CONF FOLDER           = not set
DEBUG: CHE DATA FOLDER           = not set
DEBUG: CHE DASHBOARD URL         = http://localhost:8080
DEBUG: CHE API URL               = http://localhost:8080/api
DEBUG: CHE LOGS                  = run `docker logs -f che-server`
DEBUG: 
DEBUG: 
DEBUG: ----  CURRENT COMMAND LINE OPTIONS  ---
DEBUG: CHE_PORT                  = 8080
DEBUG: CHE_VERSION               = nightly
DEBUG: CHE_RESTART_POLICY        = no
DEBUG: CHE_USER                  = root
DEBUG: CHE_HOST_IP               = 192.168.65.2
DEBUG: CHE_LOG_LEVEL             = info
DEBUG: CHE_HOSTNAME              = localhost
DEBUG: CHE_DATA_FOLDER           = /home/user/che
DEBUG: CHE_CONF_FOLDER           = not set
DEBUG: CHE_LOCAL_BINARY          = not set
DEBUG: CHE_SERVER_CONTAINER_NAME = che-server
DEBUG: CHE_SERVER_IMAGE_NAME     = codenvy/che-server
DEBUG: 
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------

![screen shot 2016-08-29 at 11 49 13](https://cloud.githubusercontent.com/assets/1636769/18048085/6f561dfa-6de0-11e6-8cbd-b9637cfcd5c6.png)
![screen shot 2016-08-29 at 11 58 47](https://cloud.githubusercontent.com/assets/1636769/18048086/6f57d5aa-6de0-11e6-8179-2b822d992599.png)

**Comment by TylerJewell** [comment]
This issue was confirmed for Mac OS and fixed with an improvement to the Che launcher made yesterday.  It probably has not flowed into the nightly yet.  However this issue still exists for the vagrant box but no longer on Windows or Mac or native Linux.   Roman is researching with Alex.

**Comment by els-pnw** [comment]
Problem persisted after disabling firewalld.  I'm going to try using nightly and see what / if any different behavior I may get.

Update: nightly tag is not available from docker.io/eclipse/che

**Comment by ghost** [comment]
@eanxgeek Please share a screenshot with browser dev console on. Since you are running Che remotely it is possible that this is a blocked ports issue.

**Comment by ddementieva** [comment]
@eanxgeek Any update on this?

**Comment by muhsinvp** [comment]
Any open source alternative for Eclipse Che in which we can create workspace for multiple developers with authentication, as Che dashboard & workspace can be accessed by any developer without authentication...!!

**Comment by TylerJewell** [comment]
Codenvy offers a fair source license for up to 3 users.  But there are not other open source alternatives.  There are dozens of people supporting the project and there has to be some way in which they are supported by the community.   You could consider running your own Che farm or giving back by purchasing codenvy.

**Comment by muhsinvp** [comment]
I have 80+ Developers with different projects(PHP,python), we develop web application with php and Apache Server installed in every developer machine, my present scenarios is, checkout source codes  from Local Subversion server to each developer machine(Ubuntu) and commit after work.. . they run projects as localhost.... what i really need is AVOID checkouting source code to developer desktops, instead of this they could code from browser or any other option like that.. So can you explain How Codenvy can do this..??

**Comment by TylerJewell** [comment]
You can get some more information from our technical & customer support teams with contact@codenvy.com.  But, please, we need to try and keep issues on the topic of the original posting.  Otherwise, our support engineers cannot track it appropriately and close it.  

From the original thread - this issue should be resolved from commits made for 4.7.2, so going to close this.
