### ISSUE TITLE
[ JDT LS ] The "Navigate File Form" has difference if compare with upstream

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11490]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
 - Run default "Java" stack with default "Spring" project
 - Open "GreetingController.java" file
 - Type in the class body
```
       private int privateVariable = 1;
       public int publicVariable = 1;
```
 - Press "Ctrl" + "F12"
 - In the opened form press "Ctrl" + "F12" once more
 - Pay attention to icons 

**Expected behavior:**
![docker](https://user-images.githubusercontent.com/22724619/46478610-07b53b00-c7f6-11e8-83ef-21b7544c3c09.png)

**Observed behavior:**
![hhhhhheee](https://user-images.githubusercontent.com/22724619/46478626-13086680-c7f6-11e8-9725-ac10a82adfb1.png)

**OS and version:**    
JDT LS assembly Che 6.12.0; Chrome 68; Fedora 28

**Comment by tsmaeder** [comment]
Yes, the rendering and sorting is slightly different. I think the rendering is better, because you can't override based on return type, so that info is useless here. 
Need to check why the icon is "private"

**Comment by tsmaeder** [comment]
I can confirm that the visiblity is indeed ignored. This is actually a LSP problem: https://github.com/Microsoft/language-server-protocol/issues/98

We can fix this for the file structure window, though, since it uses a custom command.
