### ISSUE TITLE
che-machine-exec filter doesn't work(Regresion) on the Openshift/Kubernetes with activated auth

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#11496]
### Description
che-machine-exec filter doesn't work(Regresion) on the Openshift/Kubernetes with activate auth, fail with error:
"unexpected exception! Filter found more than one pods for workspace"

**Comment by sunix** [comment]
Could you describe what the error you have ?

**Comment by AndrienkoAleksandr** [comment]
@sunix I add error to the description.
