### ISSUE TITLE
Support ConfigMap object in Kubernetes/OpenShift recipe

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11507]
### Description
A using of `ConfigMap` is a very common way to store application configuration. But Eclipse Che ignores ConfigMaps which are specified in Kubernetes/OpenShift recipe which leads to workspace start failing if there is any Pod which references it.
It is needed to support `ConfigMap` object in Kubernetes/OpenShift recipe.
The only one issue that should be decided - should we create `ConfigMap` with an original name, or rename it to a random one (with fixing references in Pods) to avoid collisions if two or more workspaces are run in the same namespace/project.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by ibuziuk** [comment]
@amisevsk I believe we can close it now
