### ISSUE TITLE
[Docker-CLI] Subdomain & SSL Possibilities

### ISSUE THREAD

**Issue by Sixosable** [eclipse-che/che#11500]
### Description
I've been trying to Eclipse Che on an actual Domain and enable SSL so it would be able to be used as a nice actual secure Cloud IDE for my team.
However, there is little to no documentation on making Docker run Eclipse Che on a subdomain, let alone running it with SSL / HTTPS Support.
All references to do basically refer to OpenShift.

I was wondering how one would be able to use a subdomain and SSL with a Docker CLI approach.

### Reproduction Steps
After Installation of Ubuntu & Newest Docker:
`docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP} -e CHE_PORT=8081 -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start`

**OS and version:**    
Ubuntu 16.04 TLS

**Diagnostics:** 
Not needed for this issue?

**Comment by eivantsov** [comment]
@Sixosable SSL isn't supported for Che on Docker.

**Comment by Sixosable** [comment]
@eivantsov Thank you very much. Closing this issue, thanks for the clear and fast answer.
