### ISSUE TITLE
Support Secret object in Kubernetes/OpenShift recipe

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11508]
### Description

A using of Secret is a very common way to store application credentials. But Eclipse Che ignores Secrets which are specified in Kubernetes/OpenShift recipe which leads to workspace start failing if there is any Pod/ConfigMap which references it.
It is needed to support `Secret` object in Kubernetes/OpenShift recipe.
The only one issue that should be decided - should we create Secret with an original name, or rename it to a random one (with fixing references in Pods, ConfigMaps) to avoid collisions if two or more workspaces are run in the same namespace/project.

**Comment by amisevsk** [comment]
Added in https://github.com/eclipse/che/pull/12486
