### ISSUE TITLE
Support Deployment object in Kubernetes/OpenShift recipe

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11505]
### Description
A common way for deploying an application on Kubernetes/OpenShift is using of `Deployment`/`DeploymentConfig` while we allow a user to specify only bare Pods.

It should not be difficult to implement supporting of `Deployment` in K8s/OS recipe since we convert bare Pods from recipe to Deployments objects.

As for `DeploymentConfig`, it should be investigated whether we can convert it to `Deployment` or create `DeploymentConfig`. There is a separate issue for implementing support of `DeploymentConfig` https://github.com/eclipse/che/issues/5967

**Comment by amisevsk** [comment]
@sleshchenko Sorry about the delay, I got distracted with other things.

I think supporting Deployment / DeploymentConfig shouldn't much trouble at all, depending on what we're expecting implementation-wise. Currently, the internal representation for workspaces is based off pods *until* we hit `KubernetesDeployments`, which wraps the Pod in a Deployment. So, if we want to support Deployment and DeploymentConfig recipes by translating into the current internal representation, that is simple. Both Deployment and DeploymentConfig (IIRC) contain pod specs somewhere.

If however we want to support specifying deployments directly (i.e. the recipe is directly linked to the deployment that is created), that might be more difficult. I would have to look into it more.

**Comment by garagatyi** [comment]
@amisevsk the idea is to grab all the information about the deployment, not just pods info that we do at the moment

**Comment by amisevsk** [comment]
@garagatyi Right. I'm thinking mostly about how it looks internally to Che -- does the entire flow down to KubernetesDeployments also support Deployments as objects now, or is the relevant info from the Deployment pulled out and the control flow down to KubernetesDeployments remain unchanged? If it's the former I don't see a lot of trouble implementing it, if it's the latter, I'm not so sure.

**Comment by garagatyi** [comment]
It is the latter. And yes, this is not an easy task.

**Comment by ibuziuk** [comment]
all PRs are merged to master. Closing
