### ISSUE TITLE
[ JDT LS ] Show argument hints functionality doesn't display "No documentation found" in the case with absence "javadoc"

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11503]
### Reproduction Steps
 - Run default "Java" stack with default "Spring" project
 - In the started workspace open "GreetingController.java" file
 - Create next java class in the "org.eclipse.che.examples" package:
```
package org.eclipse.che.examples;

public class B {
    
    /**
     * The first documentation
     */
    public void b(int i){}
    
    public void b(int i, int b){}
    
    /**
     * The second documentation
     */
    public void b(int i, int b, int c){}
}

```
 - Go to "GreetingController" editor tab
 - Set cursor to 21-th row and type next text:
```
new B().b()
```
 - Place cursor between "b()" brackets
 - Press "Ctrl" + "P" buttons
 - In the opened popup window navigate by "Up", "Down" arrows between proposals
 - Pay attention than in ```"b(int i, int b):void"``` case, expected "No documentation found" text doesn't display

**Expected behavior:**
In case with proposal which doesn't have "javadov" the "No documentation found" text is displayed.
![tttt](https://user-images.githubusercontent.com/22724619/46527965-3d602f80-c89b-11e8-87d6-18752eb06bcf.gif)

**Observed behavior:**
In case with proposal which doesn't have "javadov" the previous "javadoc" text is displayed.
![peek 2018-10-05 12-37](https://user-images.githubusercontent.com/22724619/46528050-7b5d5380-c89b-11e8-9f84-a18649421c9e.gif)

**OS and version:**    
JDT LS assembly Che 6.12.0 ; Chrome 68 ; Fedora 28

**Comment by tsmaeder** [comment]
The browser console shows a NPE.

**Comment by tsmaeder** [comment]
@Ohrimenko1988 can you verify and close, please?

**Comment by Ohrimenko1988** [comment]
The bug is fixed.
