### ISSUE TITLE
Store logs of test workspaces which are created during the E2E test scenario execution

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#11506]
### Description
E2E selenium tests stores only injecting test workspace logs after the test failed.
But there are the [tests](https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-multiuser-master-ocp/172/Selenium_20tests_20report/) which create test workspace from Eclipse Che Dashboard during execution. We need to store their logs as well.

**Comment by sunix** [comment]
looks like merged
