### ISSUE TITLE
Make UD don't show workspace memory consumption for sidecar-based workspace

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11512]
### Description
When workspace uses WS.NEXT model with sidecars UD can't figure out overall memory consumption by the workspace.
So showing it on UD doesn't make sense and can be misleading. I suggest hiding it for the time being, at least until we have a way to figure it out.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@evidolob @slemeur @l0rd

**Comment by sleshchenko** [comment]
Related to https://github.com/eclipse/che/issues/11801

**Comment by sleshchenko** [comment]
I think the issue should be resolved on Resources API side but not UD https://github.com/eclipse/che/issues/11424

**Comment by sleshchenko** [comment]
Close this issue since similar problem is discussed in another issue https://github.com/eclipse/che/issues/11801
