### ISSUE TITLE
[ JDT LS ] Editor tab name is not correct after changing 'artifactId' in 'pom.xml' file

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11514]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
1. Create and start workspace from **Java** stack with **web-java-spring** project.
2. Wait for **Java** language server initialized.
3. Open "pom.xml" file.
4. Change **artifactId** to "**jdtls-web-java-spring**".

**Expected behavior:**
Editor tab name changed from "**web-java-spring**" to "**jdtls-web-java-spring**".

**Observed behavior:**
Nothing happened.

**Failed selenium test on CI jdtls job:** ConvertToProjectWithPomFileTest

**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 10 05-15-43-26](https://user-images.githubusercontent.com/7760565/46535904-7b6a4d00-c8b5-11e8-9591-d5ed866ba687.gif)

**OS and version:**    
JDT LS assembly Che 6.12.0; Chrome 68; Fedora 28;

**Comment by tsmaeder** [comment]
This is a know limitation.

**Comment by tsmaeder** [comment]
I see two approaches to fixing this:
1. pick up some change notification in jdt.ls (if available)
2. hook some listener on save and update the tab in the same way we do it when opening the editor.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
