### ISSUE TITLE
[ JDT LS ] Implementation form is missed

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11513]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
1. Create and start workspace from **Java** stack with **web-java-spring** project.
2. Wait for **Java** language server initialized.
3. Open **GreetingController.java** class.
4. Move cursor position to 9:23.
5. From **Assistant** menu select **Implementation(s)**.

**Expected behavior:**
Implementation form appeared with "**No implementations found**" text in it.
![selection_141](https://user-images.githubusercontent.com/7760565/46534379-9f775f80-c8b0-11e8-8588-c22ce7dd953f.png)

**Observed behavior:**
Nothing happened.

**Failed selenium test on CI jdtls job:** ImplementationBaseOperationsTest

**OS and version:**    
JDT LS assembly Che 6.12.0; Chrome 68; Fedora 28;

**Comment by tsmaeder** [comment]
The idea here is to show "no implementations" when there could be implementations, but none are found, but show nothing if now symbol is at the location in question that _can_ have implementations.
