### ISSUE TITLE
Publish UD sources as maven artifact again

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11525]
### Description
This commit https://github.com/eclipse/che/commit/29818c2c0c44b8c1b2de553e1b6da1ec1f62ea41#diff-1995988aac5df423beab26da739d1c0bL71 removes publishing of UD sources as maven artifact. I believe that it was done unintentionally, so should be reverted (only publishing sources, not the whole commit). 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@evidolob @olexii4 FYI

**Comment by garagatyi** [comment]
@olexii4 I believe you've fixed this issue. Can you close it if so?

**Comment by olexii4** [comment]
Yes. I have fixed this issue.
https://github.com/eclipse/che/pull/11528
