### ISSUE TITLE
Persisting Custom Stacks in Eclipse Che

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#11527]
How do I make a custom stack to exist permanently in Eclipse che. I have an LS-sidecar stack that I have to remake every time I restart Che. How do I make it permanent so that it will be in the list of stacks just like Java, .NET, Android etc. ?

**Comment by SharkJ** [comment]
Building Che assemblies seems like a deprecated approach now. So what is the correct approach to customize che? I tried building the assembly after adding a new stack into stacks.json file in "che-core-ide-stacks -> target -> classes" path. However, the new stack was not added into che. Is it something wrong in the way I did it, or is this approach no longer works?

**Comment by skabashnyuk** [comment]
Hello @SharkJ . Stack database populated only once on the first start. So maybe you have already initialized stack database. That is why they are not loaded.

**Comment by SharkJ** [comment]
Is there any way to persist a stack instead of adding it to the assembly?

**Comment by skabashnyuk** [comment]
@SharkJ yes https://www.eclipse.org/che/docs/stacks.html#stack-sharing-and-system-stacks

**Comment by skabashnyuk** [comment]
Let me know if its working/not working for you. AFAIK @eivantsov checked this functionality when he edited this document

**Comment by SharkJ** [comment]
> Let me know if its working/not working for you. AFAIK @eivantsov checked this functionality when he edited this document

I do not find the permission tab in swagger. What do you think the reason must be? I ran the browser as administrator, but it made no difference.

**Comment by SharkJ** [comment]
The other thing I do not understand is the location where I should change the che.env file. Do I need to clone the che repo and rebuild it after I change the che.env file, or can I do it without cloning the che repo at all?

**Comment by eivantsov** [comment]
@SharkJ it's in your local directory that you mounted into `:/data` when starting Che.

**Comment by SharkJ** [comment]
@eivantsov Once I changed che.env, I need to restart che with the same `:/data ` path, am I correct?

**Comment by SharkJ** [comment]
![permission](https://user-images.githubusercontent.com/23653853/46728618-d7abe300-cca0-11e8-8a19-a9133ce3bc6a.png)
 This is what I get when I try to access "/swagger/#!/permissions" as stated in "https://www.eclipse.org/che/docs/stacks.html#stack-sharing-and-system-stacks".
Why don't I get the permissions tab?

**Comment by eivantsov** [comment]
@SharkJ is it single user Che?

**Comment by SharkJ** [comment]
@eivantsov Yes it is. Is that the reason?

**Comment by SharkJ** [comment]
@eivantsov I guess you mean it is not required to set permission since it is single user. WHat I want to do now is to make a custom stack permanent. For this, I need to edit stacks.json and set `CHE_PREDEFINED_STACKS_RELOADONSTART=true` in `che.env`. 
Now where I get confused is, can I input my new stack into stacks.json without cloning and editing the che repo? Can I add my stack into stacks.json by posting a new stack in swagger? If it doesn't become permanent after posting in swagger, what is the actual purpose of swagger/stacks/POST?

**Comment by eivantsov** [comment]
After a POST request it will be persisted in a DB. And as long as you don't flush it, it will be there

**Comment by SharkJ** [comment]
I tried the below configuration in the /swagger/#!/stack/createStack:

```
{
  "scope": "general",
  "description": "New MyDSL Stack",
  "id": "stackoagu6iqbdkatncv3",
  "creator": "che",
  "tags": [
     "Java 1.8",
      "MYDSL 1.0"
  ],
  "workspaceConfig": {
    "attributes": {},
    "defaultEnv": "default",
    "environments": {
		 "default": {
          "machines": {
            "dsl-language-server-ls": {
              "env": {},
              "volumes": {},
              "installers": [],
              "servers": {
                "mydsl1-ls": {
                  "attributes": {
                    "languageRegexes": "[ {\"languageId\":\"mydsllang\", \"regex\":\".*\\\\.mydsl$\"}]",
                    "internal": "true",
                    "id": "mydsl-ls",
                    "type": "ls"
                  },
                  "protocol": "tcp",
                  "port": "4417"
                }
              },
              "attributes": {
                "memoryLimitBytes": "2147483648"
              }
            },
            "dev-machine": {
              "env": {},
              "volumes": {},
              "installers": [
                "org.eclipse.che.terminal",
                "org.eclipse.che.ws-agent"
              ],
              "servers": {},
              "attributes": {
                "memoryLimitBytes": "2147483648"
              }
            }
          },
          "recipe": {
            "contentType": "text/x-yaml",
            "type": "compose",
            "content": "services:\n dsl-language-server-ls:\n  image: sharkj/mydsl1\n  mem_limit: 1073741824\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n   - dsl-language-server-ls\n"
          }
        }
	},
    "commands": [],
    "projects": []
  },
  "components": [],
  "name": "MyDSL1",
  "links": [
    {
      "parameters": [],
      "method": "DELETE",
      "href": "http://localhost:8080/api/stack/stackoagu6iqbdkatncv3",
      "rel": "remove stack",
    },
	{
	  "parameters": [],
	  "method": "get stack by id",
	  "href": "http://localhost:8080/api/stack/stackoagu6iqbdkatncv3",
	  "rel": "get stack by id",
	  "produces": "application/json"
	}
  ]
}
```
But in the response body I get a 500 and "message": "Internal Server Error occurred, error time: 2018-10-11 02:43:26".

**Comment by SharkJ** [comment]
@eivantsov @skabashnyuk It worked when I removed the content inside `"links":[]`. Still, my end goal of persisting the stack hasn't been achieved. When I restart Docker, the stack no longer exists.

**Comment by SharkJ** [comment]
@eivantsov @skabashnyuk I created a stack using Swagger. But when I restarted my PC, it was no longer existing. 
I followed this `https://www.eclipse.org/che/docs/stacks.html#community-supported-stacks` and added a `mydsl-stack.json` file to `\che\instance\data\templates` Still I do not get a different outcome. 
Could you kindly help me to understand what I can do to have my stack permanently existing even when I restarted my PC?

**Comment by eivantsov** [comment]
Templates are sample apps not stacks.

Having added a stack using Swagger it should be in a database. And database is persisted. As long as you do not reset your Docker for Windows your stack should be there.

**Comment by SharkJ** [comment]
@eivantsov Here's what I did. 
I went to `http://localhost:8080/swagger/#!/stack/createStack`, and entered the below code into "body" under "Parameters" section: -

```
{
  "id": "my-dsl-1",
  "scope": "general",
  "description": "New MyDSL Stack",
  "id": "stackoagu6iqbdkatncv3",
  "creator": "che",
  "tags": [
    "Java 1.8",
    "MYDSL 1.0"
  ],
  "workspaceConfig": {
    "attributes": {},
    "description": "string",
    "defaultEnv": "default",
    "environments": {
        "default": {
          "machines": {
            "dsl-language-server-ls": {
              "env": {},
              "volumes": {},
              "installers": [],
              "servers": {
                "mydsl1-ls": {
                  "attributes": {
                    "languageRegexes": "[ {\"languageId\":\"mydsllang\", \"regex\":\".*\\\\.mydsl$\"}]",
                    "internal": "true",
                    "id": "mydsl-ls",
                    "type": "ls"
                  },
                  "protocol": "tcp",
                  "port": "4417"
                }
              },
              "attributes": {
                "memoryLimitBytes": "2147483648"
              }
            },
            "dev-machine": {
              "env": {},
              "volumes": {},
              "installers": [
                "org.eclipse.che.terminal",
                "org.eclipse.che.ws-agent"
              ],
              "servers": {},
              "attributes": {
                "memoryLimitBytes": "2147483648"
              }
            }
          },
          "recipe": {
            "contentType": "text/x-yaml",
            "type": "compose",
            "content": "services:\n dsl-language-server-ls:\n  image: sharkj/mydsl1\n  mem_limit: 1073741824\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n   - dsl-language-server-ls\n"
          }
        }
    },
    "commands": [],
    "projects": [],
    "name": "default",
    "links": []
  },
  "components": [],
  "name": "MyDSL1",
  "links": []
}
```

Then I hit the `"Try it out!"` button, and got a code of 201. Then I browsed for localhost and saw my stack in the list of stacks in eclipse che. I closed all windows and restarted my COMPUTER. Once I logged in again, I waited till Docker automatically started, and then navigated to localhost (Eclipse Che) and rechecked for my stack. It was not there. I didn't restarted docker or anything. I just restarted my computer.

**Comment by SharkJ** [comment]
Could anyone kindly tell me what must have gone wrong?
