### ISSUE TITLE
[JDT LS] Maven submodules and packages are not recognized in the Che project after importing

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#11537]
### Reproduction Steps
1) Create workspace based on Eclipse Che stack. 
2) Set next env. variables: `CHE_WORKSPACE_JDT_LS_HEAP_OPTIONS = -Xmx4G -Xms2G`, 
`CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS = -Xmx2G`
3) Import CHE project  into workspace and build all maven modules (we can use console maven)
4) Stop the workspace and run again. Wait full init. language server and importing all dependencies.
5) Expand some maven module (for example: `/che/selenium/che-selenium-core/src/test/java`).
**Expected result:**  The `java` folder should be highlighted, also we should see `org.eclipse.che.selenium.core` package. 
**Actual result:** The java folders and packages are not recognized. But main Language Server features work fine.
**OS and version:**    OpenShift multiuser, JDT LS assembly, Che 6.12.0 ; Chrome 68; Fedora 28
![selection_066](https://user-images.githubusercontent.com/1640058/46614743-48c38d00-cb1f-11e8-95ad-10edd4bc0e24.png)

**Comment by tsmaeder** [comment]
Looks like this is a performance issue: we are trying to get the list of maven projects after we have imported the project. This fails with a timeout because jdt.ls is busy handling "didChangeWatchedFiles" message.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
