### ISSUE TITLE
Support Route object in OpenShift recipe

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11530]
### Description
An application on OpenShift usually has at least one Route to make application accessible outside from cluster. 
Now Che Server ignores Routes in the original recipe and requires a user to declare Che Machine for container and Che Server inside it for exposing container port. But it is not really needed and it would be better from UX perspective to respect Routes object from the recipe.

**Comment by amisevsk** [comment]
Support added in https://github.com/eclipse/che/pull/12486
