### ISSUE TITLE
Unable to create/start workspace: Host unreachable

### ISSUE THREAD

**Issue by lhein** [eclipse-che/che#11538]
### Description & Reproduction Steps
I create a workspace using the "Workspace Next Hello World example on OpenShift" quickstart. When prompted I select "Open in IDE". In the following screen I can see a red error message.

![bildschirmfoto von 2018-10-08 16-17-15](https://user-images.githubusercontent.com/435853/46614757-eebec980-cb16-11e8-84f3-b52b709a4d77.png)

When trying the same with a Blank Project I receive an error too:

![bildschirmfoto von 2018-10-08 16-22-40](https://user-images.githubusercontent.com/435853/46614772-f5e5d780-cb16-11e8-80e3-18e94b181e4a.png)

OS: Latest Fedora

**Comment by l0rd** [comment]
@lhein please provide some more details:

1. What version of Che are you using? The version number should be at the bottom of the Che dashboard.
2. What version of docker (output of `docker version`) and  OpenShift (output of `oc version`)
3. Is che-plugin-registry running (output of `oc get pods`)
4. Can you check if your OpenShift DNS is working properly? For example can you:
```
~ $ oc run -i -t busybox --image=busybox --restart=Never
/ $ nslookup -query=any google.com
```

**Comment by lhein** [comment]
1. 
Eclipse Che directly from MASTER ->  6.13.0-SNAPSHOT

2. 
```
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-61.git9cb56fd.fc28.x86_64
 Go version:      go1.10.3
 Git commit:      1556cce-unsupported
 Built:           Wed Aug  1 17:21:17 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-61.git9cb56fd.fc28.x86_64
 Go version:      go1.10.3
 Git commit:      1556cce-unsupported
 Built:           Wed Aug  1 17:21:17 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

3.
```
oc get pods
NAME                          READY     STATUS    RESTARTS   AGE
che-2-g4wql                   1/1       Running   0          2m
che-plugin-registry-1-hrcph   1/1       Running   0          2m
```

4.
```
nslookup -query=any google.com
Server:		172.30.0.1
Address:	172.30.0.1:53

** server can't find google.com: REFUSED

```

**Comment by l0rd** [comment]
Thank you @lhein 

Everything looks fine except the nslookup. Could you check that your firewall is configured properly to run openshift: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux

**Comment by lhein** [comment]
I followed the steps to configure the firewall as I know I did not do that before but sadly I still have the same issue and nslookup still tells me the same.

**Comment by eivantsov** [comment]
Definitely connectivity issue. How did you start your cluster? `oc cluster up`?

Is firewalld running? If so, can you stop it, restart docker and Origin? Also, you may want to add exceptions to firewalld. This is how it looks like on my machine:

```
[root@ivantsoft ~]# cat /etc/firewalld/zones/FedoraWorkstation.xml
<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>Fedora Workstation</short>
  <description>Unsolicited incoming network packets are rejected from port 1 to 1024, except for select network services. Incoming packets that are related to outgoing network connections are accepted. Outgoing network connections are allowed.</description>
  <service name="dhcpv6-client"/>
  <service name="ssh"/>
  <service name="samba-client"/>
  <service name="mdns"/>
  <port port="1025-65535" protocol="udp"/>
  <port port="1025-65535" protocol="tcp"/>
  <port port="80" protocol="tcp"/>
<port port="443" protocol="tcp"/>
</zone>
```

**Comment by lhein** [comment]
Eugene, that did the trick for me. Thank you for the pointers.
