### ISSUE TITLE
Error to create jwtproxy sidecar on OSIO

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11547]
### Description

Looks like the sidecar `resources.requests` is > to memory limit. When starting a Che 7 preview workspace on che.openshift.io I have the following error in the OpenShift events:

```
Error creating: Pod "workspaceataiwq6bp2cs9gsw.che-jwtproxy-864465cb55-k9rwr" is invalid: spec.containers[0].resources.requests: Invalid value: "150Mi": must be less than or equal to memory limit
```

### Reproduction Steps

- Add a Che 7 stack on osio (using this [raw config](https://gist.github.com/l0rd/2ff9391d9cabbc861d9e7e9102efcaf3))
- Start a workspace based on that stack
- Look at the events (`oc get events -w`)

**Comment by garagatyi** [comment]
Weird. I thought that I had fixed this issue in [this](https://github.com/eclipse/che/commit/46c74a92e7f73a696c59357e397c4064509f0b33) commit which is in 6.12

**Comment by garagatyi** [comment]
But yeah, looks like I missed one of the places.

**Comment by garagatyi** [comment]
@l0rd can you try to add workspace config attribute `che.server.secure_exposer=default` and check whether workspace would start?

**Comment by l0rd** [comment]
You mean `"che.server.secure_exposer": "default"`? Yes it worked

**Comment by garagatyi** [comment]
So, it is a workaround for the time being. I created a proper fix upstream and we will be able to deliver it as a bug fix version later

**Comment by garagatyi** [comment]
You are absolutely correct. I missed that the default sidecar limit is too low. I'll provide a fix in RhChe

**Comment by l0rd** [comment]
@garagatyi  #11600
