### ISSUE TITLE
Help with apache2 proxy to che server

### ISSUE THREAD

**Issue by wouterdebruijn** [eclipse-che/che#11541]
### Description
Hello,
I am hosting a Che server (Debian 9.4.0) with Docker in multi user mode. The service itself runs perfect, my only problem is that is can only run locally. When I try to port forward the service, and use my apache2 server as a proxy. I get the error "Authorization token is missed, Click here to reload the page".

I tried opening port 5050 and changing the url of the token ip to my public ip but that did not work.

Is there anything special I should know to fix this?

### Reproduction Steps
Make a Che service with Docker and make a apache2 proxy to it. Change the Valid Redirect URIs and the CHE_KEYCLOAK_AUTH__SERVER__URL="http://publicip:5050/auth"

**OS and version:**    
Che runs on Debian 9.4.0 in Docker

Apache2 also runs on Debian 9.4.0 running proxy as:
```
ProxyPass / http://192.168.22.31:85/
ProxyPassReverse / http://192.168.22.31:85/
```

**Comment by eivantsov** [comment]
@ElectroGamez I recommend running Che multi user with a single port policy. This way, you do not need Apache in front. Che CLI will start Traefik container that will execute routing tasks.

**Comment by ElectroGamez** [comment]
Got it fixed, did a fresh install and opened port 32768. Just tried the single port mode, Did not really work, not sure why. But I will deal with that later. Thanks.
