### ISSUE TITLE
Failed to run the workspace: "Installation 'org.eclipse.che.ws-agent' failed, script exit code is 126"

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#11544]
### Failed to run the workspace
I followed the documentation for building an IDE extension for EclipseChe. [Link](https://www.eclipse.org/che/docs/ide-extensions-gwt.html#extension-points)

Using the example custom repository given, I build the EclipseChe 6.12.0. 
![126-first](https://user-images.githubusercontent.com/34393074/46649543-19f8f580-cbb7-11e8-8275-c9157fb3470c.PNG)

After I created the workspace and run it then it gives this error.
![126-second](https://user-images.githubusercontent.com/34393074/46649876-52e59a00-cbb8-11e8-9ed4-78dc633fa1d7.PNG)

**OS and version:**    Windows 10

**Diagnostics:** docker logs -f che indicates,
2018-10-09 06:10:11,195[equestProcessor]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace17vxv891ejyclshr` text=`/bin/sh: 292: /home/user/che/ws-agent/bin/catalina.sh: Permission denied` time=`2018-10-09T06:10:11.1949413Z`

Run command that i'm using,

docker run -it --rm -v D:\custom_assembly\che-ide-server-extension:/repo -v D:\custom_assembly\che-ide-server-extension\assembly\assembly-main\target\eclipse-che-6.12.0:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che-cli:6.12.0 start --skip:scripts

I skipped the scripts also.

**Comment by eivantsov** [comment]
@LahiruT94 I think that it's Windows that somehow messes file permissions. However, I do not have any suggestions on how to fix it.

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
