### ISSUE TITLE
Stopped Workspace Browser produces 20% CPU Load

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11546]
When I stop a workspace, chromium still consumes 20% CPU load on my 8-core machine. Closing the browser drops the load to ~2-3%. My expectation would be that a stopped workspace produces negligable load.
1. Open a workspace java-default workspace with spring web example project
2. From the workspace menu, select stop
3. Wait until the workapce has stopped
4. Open your favourite performances tool and observe a significant CPU usage.

**Comment by garagatyi** [comment]
Might be caused by a constant reconnection to websockets
