### ISSUE TITLE
When create workspace,I got error about tty.

### ISSUE THREAD

**Issue by slackwareer** [eclipse-che/che#1155]
When create workspace,I got error "[STDERR] sudo: no tty present and no askpass program specified
".
Does anyone met the same problem?

**Comment by slackwareer** [comment]
On stage:Inject and start workspace agent
The full error message:
[STDERR] sudo: no tty present and no askpass program specified
[ERROR] Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.

**Comment by ghost** [comment]
@slackwareer Can you share the entire log? What is your OC and Docker version? What is your kernel version? Also, what stack did you use? One of the ready to go stacks or a custom one?

**Comment by ghost** [comment]
@slackwareer any update on this? Details information about your local system setup will help.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
