### ISSUE TITLE
[Regression] Unable to start hosted plugin instance for Theia

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#11559]
### Description
yarn run v1.10.1 error An unexpected error occurred: "EACCES: permission denied, open '/home/theia/.npmrc'". info If you think this is a bug, please open a bug report with the information provided in "/home/theia/yarn-error.log". info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproduction Steps
1. Import some plugin.
2. "Ctrl + Shift + P" and select command: "Hosted Plugin: Start instance"
3. Select cloned project.
Expected result: hosted instance should start and give url to hosted instance Theia.
Actual result: hosted instance throw error: 
```
yarn run v1.10.1 error An unexpected error occurred: "EACCES: permission denied, open '/home/theia/.npmrc'". info If you think this is a bug, please open a bug report with the information provided in "/home/theia/yarn-error.log". info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**OS and version:**    
Kubuntru 18.04

**Comment by benoitf** [comment]
sorry for the error.
Fixed by https://github.com/eclipse/che/pull/11531
