### ISSUE TITLE
Define plugin testing process

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11555]
### Description
The issue is we need to provide a place to host meta.yaml and plugin.tar.gz that is under development.

Proposed process.

Define http-server plugin as a sidecar. Define volume /project to this sidecar.
From Environment variable we will configre a root folder to serve for example HTTP_SERVE_FOLDER=web.
During plugin development, a user will have to put his meta.yaml and plugin.tar.gz under /project/web folder
To be able to specify plugin served by this server we need to fix this  ```Add an ability to use a custom registry for WS.NEXT plugins``` https://github.com/eclipse/che/issues/11265

**Comment by garagatyi** [comment]
Looks good

**Comment by l0rd** [comment]
@skabashnyuk 
- When you say `Define http-server plugin as a sidecar` you mean `Add a che-plugin-server as a workspace plugin`? Or `Add an http-server as a workspace plugin`?
- `Define volume /project` you mean `Mount folder /projects as a volume`?

**Comment by l0rd** [comment]
The problem with having an http-server or che-plugin-registry in a workspace is that it won't work if we need to restart the workspace. It should be a separate pod.

**Comment by skabashnyuk** [comment]
>When you say Define http-server plugin as a sidecar you mean Add a che-plugin-server as a workspace plugin? Or Add an http-server as a workspace plugin?

Not sure I understand  a difference. I meant https://www.npmjs.com/package/http-server as a server-side Che-plugin

>Define volume /project you mean Mount folder /projects as a volume?

yes

>The problem with having an http-server or che-plugin-registry in a workspace is that it won't work if we need to restart the workspace. It should be a separate pod.

What for? I think if it's not related to workspace it's closer to prod mode then dev.

**Comment by garagatyi** [comment]
> The problem with having an http-server or che-plugin-registry in a workspace is that it won't work if we need to restart the workspace. It should be a separate pod.

I forgot my own argument) Mario is correct! Since broker is working before workspace is up we can not use registry as part of the workspace.

**Comment by skabashnyuk** [comment]
@l0rd @garagatyi 
>The problem with having an http-server or che-plugin-registry in a workspace is that it won't work if we need to restart the workspace. It should be a separate pod.

Restart is not a problem since all data will be saved on the /project volume.
Or may be you want to consider availability of the data when workspace are STOPPED?

**Comment by skabashnyuk** [comment]
Small addition after a talk with @garagatyi . I thought that the newly developed plugin will be tested as part of a separate workspace. Where in workspace configuration we will define a reference to resources served by http-server sidecar of the first workspace.

**Comment by garagatyi** [comment]
If we put a meta.yaml file to the plugins or projects volume we can implement fetching the stuff from it in the broker.

**Comment by l0rd** [comment]
I would avoid using volumes among pods as much as possible for the well known problems we have on real clusters.

- The tar.gz can be copied with `oc cp` from the dev container to the httpd server container
- meta.yaml data can be provided as a configmap to the plugin-registry deployment config and restarted: when the `che-plugin-registry` starts it looks at the environment variables and if it founds a variable `CHE_PLUGIN_DATA_<plugin_id>="id: \nversion: ...` it parses it and create/update the plugin folder.

**Comment by skabashnyuk** [comment]
I think we need to make a step back and talk about prerequisites.
1. Do we want to have a generic workflow or just something quick and dirty just to see how it works?
2. Do we want to have something similar for OpenShift, kubernetes, docker?
3. Do we want to have this process limited to only one workspace or we can use two. I think
   might be some corner cases then developing and testing in the same workspace can be uncomfortable/impossible.
4. Request not to use volumes is nice to have or must have? A broker is using it, so why don't we use the same strategy.  For instance, I like @garagatyi 's idea https://github.com/eclipse/che/issues/11555#issuecomment-428149473 to read meta.yaml and plugins from ```/projects``` volume. We can define it something like this
```
  "attributes": {
    "editor": "volume:/projects/org.eclipse.che.editor.theia/1.0.0/meta.yaml",
    "plugins": "che-dummy-plugin:0.0.1,che-machine-exec-plugin:0.0.1"
  }
```

**Comment by l0rd** [comment]
The problem of using volumes to share the meta.yaml among pods is that it doesn't work in ephemeral mode. In ephemeral mode we use EmptyDir volumes and these are not shared between 2 pods. Look at [this issue](https://github.com/eclipse/che/issues/11554) with the plugin broker volume.

Currently ephemeral mode looks like the best way to run Che on public OpenShift/Kube clusters like OSO. That's why I am considering it important. Even more important than thinking about Docker support.

I find @garagatyi proposal brilliant but it should work on ephemeral mode too. And I don't know how to do it. I hope that this answers some of your questions.

**Comment by skabashnyuk** [comment]
There is no ideal solution at this moment. We would like to take into account the technical difficulties and limitations that introduced by using PV. That is why for Workshop we would like to develop a set of "oc" command that will allow.
 - Start some server in user namespace to host plugin metadata and plugin content
 - Copy metadata and plugin content from user workspace to this servers.
 - Metadata should be accessible for ChePlugin broker.

**Comment by benoitf** [comment]
is that this feature will be available on che.openshift.io on Tuesday next week ?

**Comment by skabashnyuk** [comment]
Yes. We are trying to do that. @mshaposhnik is working on it.

**Comment by benoitf** [comment]
ok thanks for the feedback

**Comment by mshaposhnik** [comment]
To make `oc cp`, we need a folder to be already present. To run `oc exec mkdir ....` seems we need chmod the `/var/www/html/plugins` in the image

**Comment by garagatyi** [comment]
As far as I remember k8s services are isolated in per-namepsace. So it might be expected that you can't access a service from another namespace.

**Comment by mshaposhnik** [comment]
With light modification in registry dockerfile (add chmod for plugins folder), i was able to hot-deploy the plugin yaml.
Sequence:
1. Login (as above)
2. Create service (as above)
3. Create route `oc create route edge --service=che-plugin-registry`
4. Get route path `oc get route`
5. Get pod name `oc get pod`
5. Create subfolder for plugin `oc exec che-plugin-registry-1-qqzzs  -- mkdir -p /var/www/html/plugins/che-makis-plugin/0.0.1`
6. Copy meta.yaml from project
`oc cp ./blankproj/meta.yaml che-plugin-registry-1-qqzzs:/var/www/html/plugins/che-makis-plugin/0.0.1`

Result: yaml is accessible at 
https://che-plugin-registry-mshaposh.8a09.starter-us-east-2.openshiftapps.com/plugins/che-makis-plugin/0.0.1/meta.yaml

**Comment by mshaposhnik** [comment]
So appropriate script was added into dev-toolign image, under path `/home/user/publish.sh`. It accepts plugin name and version as parameters. Script installs an local degistry and performs deploy of plugin binary on it. Currenlty only `.tar.gz` binaries are supported.
Short demo is at: https://www.youtube.com/watch?v=-EoFKr9sLkg
