### ISSUE TITLE
Weird error during creating a factory from workspaces made from ws.next stacks

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11562]
### Description
Weird error during creating a factory from workspaces made from ws.next stacks
### Reproduction Steps
1. Create workspace from  ws.next stacks
![2018-10-09 15 23 38](https://user-images.githubusercontent.com/1614429/46669240-8e439100-cbd7-11e8-8b20-0e5a5c900ee3.png)
2. Add some project to this workspace.
3. Try to create a workspace.
![2018-10-09 15 11 05](https://user-images.githubusercontent.com/1614429/46669277-a5827e80-cbd7-11e8-9d56-ce5d515c91ab.png)
**OS and version:**    
OSX, Chrome.

**Comment by garagatyi** [comment]
I think it is related to the absence of a project in your factory.

**Comment by skabashnyuk** [comment]
@garagatyi  project config exists.

**Comment by olexii4** [comment]
It should be fixed with  https://github.com/eclipse/che/pull/11569

**Comment by skabashnyuk** [comment]
Thanks, @olexii4 . We are improving error message from our side.
