### ISSUE TITLE
[ JDT LS ] Unexpected delay before a command starting

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11568]
**Note**
The bug is actual for this assembly:
https://github.com/eclipse/che/pull/10863

### Reproduction Steps
1. Create workspace from **Java** stack with **web-java-spring** project.
2. Disable **Java language server** and start this workspace.
3. Wait for the **IDE** is ready to work.
4. Start any command.

**Expected behavior:**
A new tab with command name appeared in the **Processes** tab. Command started.

**Observed behavior:**
There is error in **dev-machine** tab(see screenshot below). A command will start after delay in 20-25 second. 

**Failed selenium tests:** CreateWorkspaceFromAndroidStackTest, CreateWorkspaceFromEclipseCheStackTest  (https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-multiuser-master-ocp/175/Selenium_20tests_20report/failsafe-report.html)

**Screenshot:**
![selection_142](https://user-images.githubusercontent.com/7760565/46675215-93f4a300-cbe6-11e8-8754-c4575ee31b08.png)

**Screencast:**
![screencast-172 19 20 234-8080-2018 10 09-17-11-05](https://user-images.githubusercontent.com/7760565/46675225-9d7e0b00-cbe6-11e8-8554-0e63cbd8c38e.gif)

**OS and version:**    
JDT LS assembly Che 6.12.0; Chrome 68; Fedora 28;

**Comment by tsmaeder** [comment]
I suspect that the command you're using is trying to use some classpath related code?

**Comment by SkorikSergey** [comment]
Fox example predefined ```buid``` command from **Java** stack - "```mvn clean install -f ${current.project.path}/pom.xml```".
