### ISSUE TITLE
Check code assistance when verifying workspaces created from stacks in E2E selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#11578]
### Description
We have package of E2E selenium tests **org.eclipse.che.selenium.stack** which verify creation of workspace from stacks in Eclipse Che Dashboard. 

We need to verify if user can edit project source files having code assistance inside the workspaces, in addition to building and running the project.

**Comment by slemeur** [comment]
what do you mean by a "non-default" stacks? there could be a lot different ones.

**Comment by dmytro-ndp** [comment]
I mean stacks which we can see at the "_New Workspace_" page:
![new-workspace-page](https://user-images.githubusercontent.com/1197777/46740438-805f4000-ccab-11e8-884d-da1983e76d23.png)

**Comment by slemeur** [comment]
Yes all the stacks in this list are the default stacks that we are shipping with Che.

I thought you meant the stacks that users are building themselves.

**Comment by dmytro-ndp** [comment]
In that case I should fix issue title and description.
So, what do you think about adding automatic verification of code assistance to stack-related E2E tests?

**Comment by slemeur** [comment]
Yes, users are expecting to pick a stack and get the code intellisense capabilities enable and working for the technologies the stacks are covering.
So it should be tested, yes.
