### ISSUE TITLE
 Chrome / Firefox / Safari / Edge Browser extension

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#11584]
### Description
With this extension you could register your Che instances you are using:
- localhost
- local-minishift
- che.openshift.io
- private che or code ready workspaces

che.openshift.io would be registered by default
when navigating to a che instance, the extension would suggest to register it automatically

Registered instances would be used when navigating or viewing any factory config file in the browser:
- a gist with factory file
- a raw factory file
- any dashboard view (of any che instance) editing/viewing a factory configuration
- a factory url in a webpage (maybe hard ...)

In these cases, the extension would show a button next to the url bar that would run the factory in either of your registered instance (option to run with one instance by default, right click to run on another registered instance)

Registered instances could be saved in a private git repo or che instances.

**Comment by slemeur** [comment]
@sunix: https://chrome.google.com/webstore/detail/che-on-openshiftio-cloud/fkkgabogjbijdhfbbmdllhoobpeenbjo/related

cc @jeffmaury

**Comment by jeffmaury** [comment]
Mine is limited to che.openshift.io

**Comment by sunix** [comment]
Yes my proposal is for users who love Che factories and intensively use Che factories everyday. A problem these users are facing is that they do not want to restrict their usage of Che to a single instance. They want to use Che either in their local minishift, or che.openshift.io or their on prem CodeReady Workspace instances depends on the context but would like to be able to instantiate his or others factory configuration anywhere. Write once, run everywhere.

**Comment by jeffmaury** [comment]
I really hate those auto closing bots

**Comment by ibuziuk** [comment]
@jeffmaury hi, we are interested in improving / updating and promoting the extension more
could you clarify where the source-code can be found and how can we contribute?

**Comment by jeffmaury** [comment]
> @jeffmaury hi, we are interested in improving / updating and promoting the extension more could you clarify where the source-code can be found and how can we contribute?

https://github.com/jeffmaury/github-che-openshift-io-chrome-extension

Feel free to move it to Che org

**Comment by ibuziuk** [comment]
@l0rd @Kasturi1820 what do you think would be the best home for it ? is https://github.com/redhat-developer the right place?
Also, I believe we need to update the name of the repo to smth. like `try-in-web-ide-browser-extension` to mimic https://github.com/marketplace/actions/try-in-web-ide

**Comment by l0rd** [comment]
I am ok with Red Hat developer org. For rebranding as `try-in-web-ide-browser-extension`: if the code in the repo is specific to chrome then we should `s/browser/chrome/`. We should also make sure that it shows up when someone search for `Che` or `Dev Spaces` in the extension marketplace (despite the extension name doesn't include those words).

**Comment by Kasturi1820** [comment]
Yes, Red Hat developer is the right place. Agreed and +1 with Mario

**Comment by l0rd** [comment]
Related to [this downstream issue](https://issues.redhat.com/browse/CRW-3482).

**Comment by ibuziuk** [comment]
@l0rd as part of this issue I believe we should create a vendor nutural / cross-browser extention - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension so I would rather stick to the `try-in-web-ide-browser-extension`

**Comment by ibuziuk** [comment]
The extension code is available on https://github.com/redhat-developer/try-in-dev-spaces-browser-extension
Going to close the issue once it is published on all major browser marketplaces

**Comment by dkwon17** [comment]
The extension has been released under Red Hat for the Chrome Web Store [1], Safari (Mac App Store) [2], and Firefox [3]

[1] https://chrome.google.com/webstore/detail/try-in-dev-spaces/gbookaeilomckmoofeocnkfidfeendan
[2] https://apps.apple.com/us/app/try-in-dev-spaces/id6446597744
[3] https://addons.mozilla.org/en-US/firefox/addon/try-in-dev-spaces

**Comment by ibuziuk** [comment]
Thanks, David
I believe we can close it as done
