### ISSUE TITLE
Unable to create workspace

### ISSUE THREAD

**Issue by rkondre** [eclipse-che/che#11587]
### Description
Newly configured the Eclipse/Che and while trying to create the new work space from UI, getting the error like below.

**Error: Failed to run the workspace: "Error response from docker API, status: 500, message: error while creating mount source path '/home/user/eclipse-che/lib/linux_amd64/exec': mkdir /home/user: permission denied**

In my Environment "/home" is not authorized to use. I like to change the path from default path. But I am unable to find the configuration about where "/home" configured to change it. 

**OS and version:**    

RHEL 7 -

**Comment by eivantsov** [comment]
That's probably legacy code since this mount isn't actually required

**Comment by rkondre** [comment]
OK. Do you have any recommendations to resolve this issue?

**Comment by eivantsov** [comment]
@rkondre no solutions at the moment. But I will take a look if we can remove that code

**Comment by rkondre** [comment]
Let me know your available time, if required we can have a quick webex for few mins.

**Comment by rkondre** [comment]
In entrypoint.sh file and in docker files we have the path(/home/user) configured. That's why we are getting the error like this. For more information check in github files. 

https://github.com/eclipse/che

**Comment by eivantsov** [comment]
@rkondre good observation but it is a path inside a Che server container which starts file. The problem is that /home/user mount happens when a workspace container is created. And I suspect that's truly unnecessary code.

**Comment by rkondre** [comment]
Yes.. I am getting that error while creating a new workspace from UI only.. Unable to create a workspace.

**Comment by rkondre** [comment]
Could you please let me know, your available time? if you have some free time, we will connect in webex.

**Comment by JavaJoeS** [comment]
Are there any work arounds for this issue?

**Comment by rkondre** [comment]
No work around provided by product owner yet..
