### ISSUE TITLE
OpenShift Container Platform 3.11

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11582]
### Description
The goal of this task is to provide support and migrate all internal development to OCP 3.11.
This release is based on OKD 3.11, and it uses Kubernetes 1.11

Cool staff
- PROMETHEUS CLUSTER MONITORING https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-311-prometheus
 - Operators  https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-311-operators
-  CLUSTER ADMINISTRATOR CONSOLE https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-311-cluster-admin-console

See more 
- https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html
- https://www.redhat.com/en/blog/generally-available-today-red-hat-openshift-container-platform-311-ready-power-enterprise-kubernetes-deployments

**Comment by eivantsov** [comment]
I think we should wait for Origin release which is not yet there https://github.com/openshift/origin/releases

**Comment by skabashnyuk** [comment]
@eivantsov good point.

**Comment by skabashnyuk** [comment]
not sure we need this issue. We already are able to successfully use on minishift with OS 3.11
