### ISSUE TITLE
How to hide the projects belong to other workspaces?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#116]
Finally, I got eclipse-che 4.x running, and created several different workspace, and created different projects in some of them:

![image](https://cloud.githubusercontent.com/assets/333781/11738061/39e0ba3e-a01a-11e5-9941-94cd430be2d0.png)

But the problem is, when I open the `lipeng3` workspace `http://localhost:8080/che/lipeng3`, it will also show the `test_another_spring` project which belongs to another workspace

![image](https://cloud.githubusercontent.com/assets/333781/11738095/912a7b86-a01a-11e5-8b97-a60e4067bf53.png)

I can even edit it:

![image](https://cloud.githubusercontent.com/assets/333781/11738078/7044ba44-a01a-11e5-9a91-15968e194252.png)

Since I want to create workspaces for different users, they should not see other's projects. Is there any way to hide them?

**Comment by TylerJewell** [comment]
This seems like a bug. I did not find an existing issue so opened a jira internally.  We will let you know after investigation.

https://jira.codenvycorp.com/browse/IDEX-3834

-Tyler

**Comment by freewind** [comment]
@TylerJewell thanks!

**Comment by TylerJewell** [comment]
This was resolved.
https://github.com/codenvy/che-plugins/commit/7ea4b5bcb3ad9d6ceede1564d6c01c3f44f65909
