### ISSUE TITLE
keycloak-template.yaml Invokes command that causes Keycloak to use H2

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-che/che#11620]
### Description
Attempting to create and start a pod for Keycloak within OpenShift for multi-user che.  Using the file: che/deploy/openshift/templates/multi/keycloak-template.yaml.

The file invokes the command: /scripts/kc_realm_user.sh.  When tracing through the steps of the command, we can see that the standalone.xml file for Keycloak is never modified and defaults to allow Keycloak to use the H2 database.

### Reproduction Steps
Create a project in OpenShift.
Create a pod for Postgresql using postgres-template.yaml (not really necessary)
Create a pod for Keycloak using keycloak-template.yaml
Note that the Postgresql db is not used and that H2 is.

**OS and version:**    
Any OS, Latest Version

**Comment by BarryDrez** [comment]
There is something strange when I create a pod from the image: jboss/keycloak-openshift:3.4.3.Final and run the command:
/usr/bin/start-keycloak.sh -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.dir=/opt/jboss/keycloak/realms/ -Djboss.bind.address=0.0.0.0
I get the error:
java.lang.IllegalStateException: Directory /opt/jboss/keycloak/realms doesn't exists

It works when running che standalone in multiuser mode.

Wondering if this is related.

**Comment by BarryDrez** [comment]
@eivantsov Can I please get an update on this?

**Comment by eivantsov** [comment]
There's a PR in works https://github.com/eclipse/che/pull/11761

**Comment by BarryDrez** [comment]
Thank you

**Comment by skabashnyuk** [comment]
@l0rd @slemeur  can you triage this issue, I think it might be important to fix for 7.0. WDYT?

**Comment by slemeur** [comment]
Before adding it to the scope, I think it's important to review this issue and check if this is still accurate. The deployment on openshift is now handle through the operator. 
I'm labelling it for platform team.

**Comment by skabashnyuk** [comment]
@mkuznyetsov could you take a look?

**Comment by mkuznyetsov** [comment]
yes, on Operator it works with correct database, although it uses different keycloak image and it's entrypoint

**Comment by skabashnyuk** [comment]
@slemeur so, basically this issue is linked to the installation way that is no longer relevant.

**Comment by l0rd** [comment]
@mkuznyetsov @skabashnyuk so we close right?

**Comment by skabashnyuk** [comment]
>@mkuznyetsov @skabashnyuk so we close right? 

+0
Maybe it supposes to happen at the same time with https://github.com/eclipse/che/issues/13888
