### ISSUE TITLE
Need help for server side plugin debug

### ISSUE THREAD

**Issue by RaymanNg** [eclipse-che/che#11621]
### Description
 
I have read the document [Development Workflow](https://github.com/eclipse/che/wiki/Development-Workflow), but I still can't debug server side plugin(for example, che-plugin-java-debugger-server). I attach the che server successfully, but it just won't stop at breakpoints I add.

### Reproduction Steps

What I did:
1.Modify the che.env
CHE_DEBUG_SUSPEND=true
CHE_DEBUG_PORT=8000
CHE_ENVIRONMENT="development"

2.Start che in debug mode through CLI
docker run  -it --rm -e CHE_HOST=192.168.56.101 -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/repo -v ~/che-data:/data eclipse/che-cli start --skip:scripts --debug

3.In the local eclipse IDE, add "Remote Java Application" Debug Configuration
![image](https://user-images.githubusercontent.com/18614142/46956243-69638800-d0c7-11e8-99ef-f8c26803c082.png)

4.Click "Debug"
remote debug is running, and I add several breakpoints in  JavaDebugger.java, including the constructer method

5.Use JavaDebugger in client side
open eclipse che in my chrome browser, import a Java Hello World sample project
click the debug button, then the Hello World program is "Listening for transport dt_socket at address:9394"
Run -> Debug -> Java Debug(with port 9394)
The debug did start, but NOTHING happened in my eclipse IDE  

**OS and version:**    
Ubuntu 18.04

Did I do something wrong? I will appreciate it if someone gives me a detailed instruction on how to debug the server side code of eclipse che

PS: I think it would be nice to have some video tutorials about the development workflow, because sometimes I can not figure out the complete process

**Comment by eivantsov** [comment]
@RaymanNg you need to debug ws-agent.

Start Che workspace, thenm run `docker ps`. You will see a container with exposed ports. Port 4403 is the port you need, and it is published to a random port from the ephemeral range. Grab that port and use it instead of 8000

**Comment by RaymanNg** [comment]
@eivantsov Thank you. I can now debug the plugin
