### ISSUE TITLE
What is the configuration of AWS Load Balancer to work with Eclipse Che ?

### ISSUE THREAD

**Issue by garrablanca** [eclipse-che/che#11635]
Hi guys, I have installed Eclipse Che in an instance of EC2 and I have put it after a load balancer, the point is that when I try to reach it I simply can not open it.

The configuration of the EC2 instance is basically an installation of Eclipse Che in Docker over Linux.

When I publish directly the EC2 instance in the subdomain in "Routte 53" setting aside the load balancer, I can see Eclipse Che, but it is not the configuration we are looking for.

The execution is done as follows:

1. First, I set up Route 53 to access the EC2 instance using the subdomain name such as "** subdomain.domain.com **"

2. Then I run the Eclipse Che pointing to the subdomain, otherwise it will point to the internal IP and not the URI, it could be reached, but it will present some problems.

sudo docker run --restart = always -it -e CHE_MULTIUSER = true -e CHE_HOST = ** subdomain.domain.com ** -v /var/run/docker.sock:/var/run/docker.sock - v ~ / .che-multiuser: / data eclipse / che start

3.- I proceed to check that I can log in and interact with Eclipse Che through the URI or the subdomain name, which looks good so far.
**NOTE**: I also had configure the WSO2 Identity server to handle the login, and also is working find so far, then after testing I logged out.

4.- Then I simply change the Ruote 53 subdomain configuration so that's points to the Load Balancer instead of the direct access to the EC2 instance.
this Load Balancer is fully open in its own Source Security Group and this is just for the purpose of this test.
In Listeners
I set it up like this
HTTP 8080
HTTP 5050
HTTP 80
SSL 443

I know there is an issue [#9056](https://github.com/eclipse/che/issues/9056) that it looks like this one and it seems to be closed, but I'll like to understand why is not working.

What is the reason why it is not possible to publish Eclipse Che through the Load Balancer?

Thank you so much.

**OS and version:**    
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)

**Docker:**
Docker version 1.13.1, build 8633870/1.13.1

**Diagnostics:** 
When I try to open the site Eclipse Che after a while it only shows a black screen even that I haven't signed in, it's showing a message related to the Authorization Token:
![image](https://user-images.githubusercontent.com/11811349/47037738-58f1f280-d145-11e8-8748-4d46b4e3a2d7.png)

**Comment by garagatyi** [comment]
@skabashnyuk you might be interested in this issue. Seems somewhat related to the Auth subsystem

**Comment by skabashnyuk** [comment]
@garrablanca hi.
It would help if you can provide the log from che-master and from browser console.
Also, I'm not sure about what was the concrete value of CHE_HOST you used.

**Comment by garrablanca** [comment]
@skabashnyuk hi. oh thank you for reply and my apologizes for the delay of this response, well, I'm obfuscating the name of the domain ( **subdomain.domain.com** ) because I'm not allowed to share the exact name, but you can consider it is any name you can imagine that match this mask subdomain.domain.com could be like ide.mysite.com, of course this domain name is configured in the Route 53 and pointing to the Load Balancer which it's also configured to publish the Eclipse che EC2 instance in **AWS**.

**Comment by skabashnyuk** [comment]
@garrablanca is there any reason that you think this is a Eclipse Che issues and not Amazon misconfiguration? I  think that you have misconfigured your Ec2 instance or Route 53.

**Comment by garrablanca** [comment]
@skabashnyuk well, when I tried the configuration with the Route 53 domain to direct work with the EC2 Instance, then works perfectly fine, the problem is when I configure the **Load Balancer** in between, and that's the goal here, to work with the Load Balancer.
I wonder if someone have been configured Eclipse Che like this in AWS.

**Comment by garrablanca** [comment]
Hi guys,
Ok this is what I found out so far...
First every time you start the Eclipse Che service, it runs a bunch of checks to ensure everything is going smooth and it's available for the rest of the services to start, and it's here when we start having some issues since the **Load Balancer** only exposes ports 80, 8080 and 5050 (_because that's the way we configure it_) and also has a dependency to have the check health on active in order to route to that EC2 instance, but needs to also have available a bunch of ports from the range of 32768 - 65535 so because is so hard to configure port by port in the **Load Balancer**, this way to deploy the service behind the **Load Balancer in AWS** is not practical.

Although there is a way to do it.... but it also needs some twist tricks to make it work.
First we need to serve the Eclipse Che in a Single Port configuration in order to workaround the need of ports 5050 and the range of 32768 - 65535, you know with the single port configuration everything should be pass trough the 8080 port.
however, internally this checks still needs to ensure the availability of some ports.
So then we end forcing the start without the checks :'( by using the flag **--skip:preflight**
but this would not be all, we also need to wait until the health check for the **Load Balancer** passes, and then we just need to restart the docker image of the Che service, and **voilà** we finally can have the Eclipse Che working behind a **Load Balancer in AWS**.

I wondering if we can deploy this in a smoothly better way, since we need to automate this process.

**Comment by skabashnyuk** [comment]
I would say you should look at OpenShift/Kubernetes infrastructure. Docker infrastructure is not scalable at all. It doesnt make sense to investigate it compatibility with AWS load balancer

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
