### ISSUE TITLE
Support more modern version of Java

### ISSUE THREAD

**Issue by geiseri** [eclipse-che/che#11634]
### Description

I am trying to use Ubuntu bionic for development dependencies of my project, but it doesn't ship with a version of Java older than 11.

### Reproduction Steps

Change base ubuntu installation from 16.04 to 18.04.  It cannot find `openjdk-8-jdk-headless`

If you manually change the docker to use `openjdk-11-jdk-headless` the actual agent install fails at runtime.

**OS and version:**    

Docker image of `eclipse/che-server:6.11.1`

**Comment by geiseri** [comment]
Added copy of the docker project.  It is a hacked version of the upstream ubuntu 16.04 version.

[stack-base.zip](https://github.com/eclipse/che/files/2484110/stack-base.zip)

**Comment by geiseri** [comment]
This seemed to work around the issue: https://linuxconfig.org/how-to-install-java-on-ubuntu-18-04-bionic-beaver-linux#h8-1-1-java-version-8

**Comment by eivantsov** [comment]
@geiseri building a custom image with Ubuntu 18 and openjdk 1.8 will solve the problem. In the long term, when workspace agent isn't required, the problem will solve itself.
