### ISSUE TITLE
The desired archetype does not exist (org.eclipse.che.archetype:plugin-wizard-archetype:6.12.0)

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#11637]
### Description
 In order to create a custom assembly, it tried to use the Archetype generator. But it keeps giving me this error.
This is for the latest relaese 6.12.1

![archetype1](https://user-images.githubusercontent.com/34393074/47064239-42f33900-d1fc-11e8-87a4-27c1c849f1b6.PNG)

I changed the cli versio to an older relase but, it keeps giving me the same error.

![archetype2](https://user-images.githubusercontent.com/34393074/47064277-6c13c980-d1fc-11e8-809e-9773983ba126.PNG)

### Reproduction Steps
Docker run command: 
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v D:\customAssembly:/archetype -v D:\customAssembly\backup:/data -v C:\Users\lahglk\.m2\repository:/m2 eclipse/che-cli:6.12.1 archetype generate`

**OS and version:**    
Windows 10

Thanks.

**Comment by skabashnyuk** [comment]
Archetypes are deprecated since 6.x try to use generated samples https://github.com/che-samples/

**Comment by LahiruT94** [comment]
Thanks
