### ISSUE TITLE
Add an ability to add plugin from custom plugin registry from Dashboard

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11642]
### Description
There is an implemented ability to configure plugins from custom registry https://github.com/eclipse/che/issues/11265
But now user has to edit Workspace Config JSON manually 
![screenshot_20181017_110311](https://user-images.githubusercontent.com/5887312/47071629-abdab100-d1fc-11e8-85d3-fb2289ef02f1.png)
It would be nice to Add an ability to add plugin from custom plugin registry from Dashboard.

**Comment by sleshchenko** [comment]
@l0rd Do you think we need this issue for EclipseCon workshop or editing workspace config JSON would be good enough?

**Comment by l0rd** [comment]
workspace config JSON should be enough

**Comment by benoitf** [comment]
@sleshchenko what is an example of `Workspace Config JSON manually` ?

**Comment by l0rd** [comment]
@benoitf this worked for me:

```yaml
"plugins": "https://che-plugin-registry.openshift.io/plugins/che-machine-exec-plugin:0.0.1, https://che-plugin-registry-mloriedo.8a09.starter-us-east-2.openshiftapps.com/plugins/formatter-plugin:0.0.1"
```

**Comment by sleshchenko** [comment]
Just small note, if Custom Che Registry is deployed in the same project where workspace is run then service name could be used instead of Route host, like `http://che-plugin-registry/plugins/formatter-plugin:0.0.1` .

**Comment by gorkem** [comment]
Closing, I do not think this is valid anymore
