### ISSUE TITLE
Building che-plugin-wizard (sample) 

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#11645]
### Description
I cloned the repo from GIT and Build it with no errors and ran it. Che started without a problem. But how to check the wizard plugin is working or not?

### Reproduction Steps
1. Cloned https://github.com/che-samples/che-plugin-wizard.git
2. checkout tag 6.12.0
2. mvn clean install the repository
3. Run command: 
docker run -it --rm -v D:\che-plugin-wizard:/repo -v D:\BackupPluginWizard:/data -v D:\che-plugin-wizard\assembly:/assembly -v /var/run/docker.sock:/var/run/docker.sock eclipse/che-cli:6.12.0 start --skip:scripts

**OS and version:**    
Windows 10

**Diagnostics:** 
![wizard](https://user-images.githubusercontent.com/34393074/47072747-53171280-d214-11e8-8a6a-9da71047b17d.PNG)

Thanks.

**Comment by skabashnyuk** [comment]
why do you think this command should work?

**Comment by skabashnyuk** [comment]
let me take a look for a correct one

**Comment by skabashnyuk** [comment]
Plese take a look https://www.eclipse.org/che/docs/build-reqs.html#build-in-docker

**Comment by skabashnyuk** [comment]
try
```
docker run -ti -v ~/.m2:/home/user/.m2 -v /Users/sj/dev/tmp/che-plugin-wizard/:/projects eclipse/che-dev:nightly sh -c "mvn clean install"
```
Also take a look https://www.eclipse.org/che/docs/assemblies.html#custom-assemblies

**Comment by LahiruT94** [comment]
Build it using the command and gives me an exception,

![ide-server](https://user-images.githubusercontent.com/34393074/47130891-6b8d3880-d2b9-11e8-80e1-3be6fb6c77c9.PNG)

Can you please look into this.

I thought it is correct because of [this](https://github.com/eclipse/che/issues/9587#issuecomment-389743174).

**Comment by skabashnyuk** [comment]
@LahiruT94 more logs, please. Is this original master of https://github.com/che-samples/che-plugin-wizard.git or you custom fork?

**Comment by LahiruT94** [comment]
Yes it is the original master.

![editedlog](https://user-images.githubusercontent.com/34393074/47278320-a22ec000-d5e5-11e8-8436-dee2f0518043.png)


This is the most part of the log. Its too long.

**Comment by mkuznyetsov** [comment]
@LahiruT94 can you please try build it once again, only configure your Docker to use at least 3GB of RAM? 
Build fails on a module that does GWT compilation, which takes up a lot of memory and may be crashing because of low RAM limit

**Comment by LahiruT94** [comment]
Yes, thank you it worked. (build succeeded). 

But I could not figure out how to run it using the che-dev nightly build.

Run command that i used:
`docker run -it --rm -v D:/che-samples/che-ide-server-extension:/repo -v D:\che-samples\che-ide-server-extension-data:/data -v D:/che-samples/che-ide-server-extension/assembly:/assembly -v /var/run/docker.sock:/var/run/docker.sock eclipse/che-dev:nightly start --skip:scripts`

It gives me this error:
`/home/user/entrypoint.sh: line 41: exec: start: not found`

**Comment by LahiruT94** [comment]
Okay, i figured it out. Have to provide the assembly path inside the target.

```
docker run -it --rm -v D:/che-samples/che-ide-server-extension:/repo -v D:/che-samples/che-ide-server-extension-data:/data -v D:/che-samples/che-ide-server-extension/assembly/assembly-mai
n/target/eclipse-che-6.13.0/eclipse-che-6.13.0:/assembly -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.12.1 start --skip:scripts
```
