### ISSUE TITLE
Dashboard does not show more than 30 workspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11643]
### Description
Dashboard does not show more than 30 workspaces.

### Reproduction Steps
1. Create more than 30 workspaces.
2. Open Dashboard.
Expected: Dashboard provides paging for fetching all of the user's workspaces.
Actual: Dashboard shows only first 30 workspaces.
![screenshot_20181017_111706](https://user-images.githubusercontent.com/5887312/47072277-66b77e80-d1fe-11e8-87e0-532fbacd0160.png)

**OS and version:**    

**Diagnostics:** 

![screenshot_20181017_111814](https://user-images.githubusercontent.com/5887312/47072262-60c19d80-d1fe-11e8-8fea-57f4bdc451e5.png)
![screenshot_20181017_111912](https://user-images.githubusercontent.com/5887312/47072338-7e8f0280-d1fe-11e8-9c06-90fd08a411b6.png)

**Comment by RomanNikitenko** [comment]
Looks like duplicated https://github.com/eclipse/che/issues/9752

**Comment by sleshchenko** [comment]
@RomanNikitenko you're right. Thanks for pointing.
