### ISSUE TITLE
Avoid parsing each JSON_RPC message several times

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11655]
### Description
On receiving of each JSON_RPC message we parse it [here](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcMessageReceiver.java#L65) to check whether it is a valid JSON and [here](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcMessageReceiver.java#L70) we parse it the second time to proceed with the processing.
Does it make sense to parse the message two times? How it influences the performance of the Che master.
Well, we actually parse it [here](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/GsonJsonRpcUnmarshaller.java#L45) and [here](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/GsonJsonRpcUnmarshaller.java#L141). So, in general, we parse it 3 times.   
I also spotted that we do some useless work [here](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/impl/GsonJsonRpcQualifier.java#L66) for debug log. But if debug is not enabled it is wasting CPU cycles. I would consider not processing it just for the logging purposes. 
Later logger might support lambdas, but for the time being, I think it would be better to remove this logging at all. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by gorkem** [comment]
@vparfonov Is this still valid?
