### ISSUE TITLE
Failed to start che container waiting for Keycloak openID configuration

### ISSUE THREAD

**Issue by roobkit** [eclipse-che/che#11654]
### Description
I've to install multi-user docker version of  eclipse che in a vhost `192.168.100.34/24` behind a proxy in `192.168.100.1/24` but Keycloak container don't start while waiting for openid conf.

### Reproduction Steps
I use [docker guide](https://www.eclipse.org/che/docs/docker-multi-user.html) with `CHE_HOST=192.168.0.34` and `--fast` flag . Installation never ends.

**OS and version:**    
host Debian GNU/Linux 9.5 (stretch)

Docker version 18.06.1-ce, build e68fc7a
* eclipse/che-server:6.12.1
* jboss/keycloak-openshift:3.4.3.Final
* centos/postgresql-96-centos7:9.6

**Diagnostics:** 
`docker logs -f che ` says every 2 minutes  :
    
       [ost-startStop-1]  [INFO ] [o.e.c.m.k.s.KeycloakSettings 86]     - Retrieving OpenId configuration from endpoint: http://192.168.100.34:5050/auth/realms/che/.well-known/openid-configuration
In browser and curl `http://192.168.100.34:5050/auth/realms/che/.well-known/openid-configuration` works fine

If I use *CHE_HOST* to `127.0.0.1` or `localhost` installation ends with error and dashboard show red error.

**Comment by skabashnyuk** [comment]
@mshaposhnik can you take a look?

**Comment by roobkit** [comment]
@mshaposhnik I'm still with the problem. I'll be able to try this monday. Thanks!

**Comment by roobkit** [comment]
@mshaposhnik In this case the installation ends with error 

In my case I need multiport mode because the machine don't have permanent internet access (intranet enviroment).

> ERROR: (che start): Timeout waiting for server. Run "docker logs che" to inspect.

che log returns 35 errors like this:

> Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak.172.17.0.1.nip.io:8080/auth/realms/che/.well-known/openid-configuration

**Other test on Multiport mode**
I tested connection from che docker container and works fine too

```
/* works fine */
root@myhost # wget http://192.168.100.34:5050/auth/realms/che/.well-known/openid-configuration

root@myhost  # sudo docker exec -i -t che /bin/bash
bash-4.3# wget http://192.168.100.34:5050/auth/realms/che/.well-known/openid-configuration
```

Thanks!

**Comment by eivantsov** [comment]
Maybe you need to configure proxy for ws-master? I mean JAVA_OPTS for Che contrainer

**Comment by roobkit** [comment]
@eivantsov I removed proxy settings from docker ( I only need it for download images ) and the issue persist. (also in Debian stretch)

Aparently keycloack server works fine.

I use `--fast` to force docker error DNS menssage (although the proxy works fine and pull images). Can this affect?

Thanks!
