### ISSUE TITLE
[ JDT LS ] External libraries list doesn't change after editing dependencies in the "pom.xml" file

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11660]
**Related test:**
 - TransitiveDependencyTest

### Reproduction Steps
 - Run default "Java" stack with default "spring" project
 - Wait for the end of the language server starting
 - In the created workspace open "pom.xml" file
 - Open "External Libraries" folder
 - In the opened "pom.xml" file delete dependency ( from 21 to 25 line):
```
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>3.0.5.RELEASE</version>
        </dependency>
```
 - Pay attention that list of the external libraries has not changed 

**Expected Behavior:**
![expected](https://user-images.githubusercontent.com/22724619/47140916-28869180-d2c8-11e8-902e-dd3ad6d13376.png)

**Observed Behavior:**
![observed](https://user-images.githubusercontent.com/22724619/47140928-2fad9f80-d2c8-11e8-94e9-2c6dbc1bc234.png)

**OS and version:**    
Che 6.13.0 ; Chrome 68 ; Fedora 28

**Comment by tsmaeder** [comment]
I cannot reproduce this one. Works for me every time :-(

**Comment by Ohrimenko1988** [comment]
Sorry, it still reproduced.
The easiest way to reproduce is run docker image:
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v <your data folder>:/data eclipse/che-cli:nightly start
```
And perform "Reproduction steps" which described in this issue.

**Comment by tsmaeder** [comment]
This seems to have been broken by https://github.com/eclipse/che/pull/11515/files We're sending workspace paths to language servers, which is wrong. Fixing...please stand by.

**Comment by tsmaeder** [comment]
Sorry about not seeing this...I guess I was running old code from before I rebased on master with the LS filewatcher changes :-(

**Comment by Ohrimenko1988** [comment]
It is ok. If you have any questions or you need some clarification, you may ask me at any time here or in "Mattermost" (@iokhrimenko)

**Comment by Ohrimenko1988** [comment]
Fixed
