### ISSUE TITLE
Unable to open secure server with cookiesAuthEnabled if server has https protocol

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11664]
### Description
Unable to open secure server with cookiesAuthEnabled if a server has https protocol.

### Reproduction Steps
1. Login to [prod-preview](https://che.prod-preview.openshift.io/dashboard/) instance.
2. Create a workspace with Che Theia Editor Activated.
3. Try to start workspace.
**Expected**: Workspace is started. 
**Actual**: JwtProxy sends wrong redirect to `loader.htlm` with redirect url `http://{SERVER_HOST}` instead of `https://{SERVER_HOST}`. See attachment.
![photo_2018-10-18_15-31-05](https://user-images.githubusercontent.com/5887312/47154414-f0447a80-d2ea-11e8-80ce-55782ae507d1.jpg)

**OS and version:**    

**Diagnostics:** 
Here are places where `http` value is hardcoded:
https://github.com/eclipse/che-jwtproxy/blob/master/jwt/jwt.go#L98
https://github.com/eclipse/che-jwtproxy/blob/master/jwt/jwt.go#L137

**Comment by ibuziuk** [comment]
unassigning David since platform team is going to work on finalizing https://github.com/eclipse/che-jwtproxy/pull/9

**Comment by mshaposhnik** [comment]
Added workspround fix in https://github.com/eclipse/che-jwtproxy/commit/951bfa8be198ec3551f5d3fbb1162982b9158488
Now i'm able to run workspaces with jwtproxy on prod.
