### ISSUE TITLE
JREContainer hashcode implementation

### ISSUE THREAD

**Issue by Wajihulhassan** [eclipse-che/che#1167]
In che/plugins/plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/che/jdt/core/launching/JREContainer.java , Class RuleEntry does not implements hashcode() while it overrides equals().
According to Java [API`](http://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode%28%29) 

> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result. 

So, in this case it is necessary to implement hashcode() too.

**Comment by evidolob** [comment]
Hi, this is bug related to Eclipse JDT code: https://github.com/eclipse/eclipse.jdt.debug/blob/master/org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/JREContainer.java#L119
You should create issue in https://github.com/eclipse/eclipse.jdt.debug project.
