### ISSUE TITLE
Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-8:compile (default) on project assembly-ide-war: GWT exited with status 137

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#11675]
### Description
When building the custom plugin-wizard (sample) it gives this error.

### Reproduction Steps
1. Cloned the che-plugin-wizard
2. Checkout 6.12.0
3. Run command:
`docker run -ti -v C:/Maven:/home/user/.m2 -v D:/che-plugin-wizard:/projects eclipse/che-dev:nightly sh -c "mvn clean install"`

**OS and version:**    
Windows 10 and IntellijIDEA 2018.2.5

**Diagnostics:** 
![memory](https://user-images.githubusercontent.com/34393074/47196253-48c45800-d37d-11e8-975c-2cbf5be8897c.PNG)

**Comment by skabashnyuk** [comment]
@mkuznyetsov  can you take a look?

**Comment by mkuznyetsov** [comment]
Hi, as I commented in other issue, try building again, with setting Docker to use 3GB or more RAM.
https://github.com/eclipse/che/issues/11645#issuecomment-432630606
