### ISSUE TITLE
Provide Camel yeoman generator in Camel Stack

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11699]
### Description

Camel is providing a yeoman generator https://github.com/camel-tooling/generator-camel-project https://www.npmjs.com/package/generator-camel-project

it would be nice to have it available by default.

With Che 7, there is a yeoman plugin which is looking for installed npm. So seems that needed tasks are:
- ensure Camel stack compatible with Che 7
- ensure yeoman server/plugin is available in the stack
- install generator-camel-project npm
- add steps in Camel Stack test, creating a project with yeoman and using it with command provided if it is building

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by apupier** [comment]
to have the Camel Genrator based on yeoman preconfigured so that users can use _yo camel-project_ in their che Workspace from command-line and when using Theia from the yeoman integration in palette

**Comment by skabashnyuk** [comment]
@evidolob @ashumilova @benoitf can you help here?

**Comment by apupier** [comment]
Currently we prefer to rely on project Initializer than yeoman to create Camel/Fuse project.
As the memory is limited for Camel stack already, I'm closing this request.
