### ISSUE TITLE
Che extension Deployment

### ISSUE THREAD

**Issue by 781227k** [eclipse-che/che#11706]
### Description

I start building a custom IDE based on eclipse-che by using core plugins for ide and server side. And finally added some extensions to that. I am able to run the second instance of IDE within Eclipse-che. 

I was wondering how can I build and deploy my own custom ide, locally or in a virtual machine using docker.

**Comment by skabashnyuk** [comment]
@781227k to make sure we are talking about the same thing: your mean gwt based IDE? Right?

**Comment by 781227k** [comment]
Yes, based your sample https://github.com/che-samples/che-ide-server-extension

I've added a few more gwt ui-extensions such as custom editor and added some behavior to the editor with server extensions.
 I can build and run customized assembly within Eclipse che using the commands; Deploy IDE / Deploy Workspace Agent.

But I was wondering how exactly can I build the custom ide outside of eclipse-che, maybe in a virtual machine using docker?
