### ISSUE TITLE
che-dockerfiles-theia module fails regularly on CI

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11703]
### Description
I saw this fail a lot of time also I've heard many times complains from developers.
```
22:02:39 [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (Check Theia image) on project che-dockerfiles-theia: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
22:02:39 [ERROR] 
22:02:39 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
22:02:39 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
22:02:39 [ERROR] 
```

### Reproduction Steps
<details><summary>Log</summary>

[INFO] --- maven-antrun-plugin:1.8:run (build-image) @ che-dashboard-war ---
[INFO] Executing tasks

main:
     [exec] Sending build context to Docker daemon  6.726MB
     [exec] Step 1/8 : FROM node:8.10.0
     [exec]  ---> 41a1f5b81103
     [exec] Step 2/8 : RUN apt-get update &&     apt-get install -y git     && apt-get -y clean     && rm -rf /var/lib/apt/lists/*
     [exec]  ---> Using cache
     [exec]  ---> 9db64b6c3a83
     [exec] Step 3/8 : COPY package.json /dashboard/
     [exec]  ---> Using cache
     [exec]  ---> ce6389a7b9d6
     [exec] Step 4/8 : RUN cd /dashboard && npm i yarn && npx yarn install --ignore-scripts
     [exec]  ---> Using cache
     [exec]  ---> c405adb29e9c
     [exec] Step 5/8 : COPY . /dashboard/
     [exec]  ---> Using cache
     [exec]  ---> 303e616ad83f
     [exec] Step 6/8 : RUN cd /dashboard  && npx yarn
     [exec]  ---> Running in 2b909e196374
     [exec] yarn install v1.10.1
     [exec] [91mwarning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
     [exec] [0m[1/5] Validating package.json...
     [exec] [2/5] Resolving packages...
     [exec] [3/5] Fetching packages...
     [exec] info fsevents@1.2.4: The platform "linux" is incompatible with this module.
     [exec] info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
     [exec] [4/5] Linking dependencies...
     [exec] [91mwarning " > angular-gravatar@0.2.4" has unmet peer dependency "grunt-cli@0.1.13".
     [exec] [0m[91mwarning " > eslint-loader@1.0.0" has unmet peer dependency "eslint@^1.0.0".
     [exec] [0m[91mwarning " > file-loader@1.1.11" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
     [exec] [0m[91mwarning " > karma-jasmine@0.3.8" has unmet peer dependency "jasmine-core@*".
     [exec] [0m[91mwarning " > ts-jest@22.4.6" has incorrect peer dependency "typescript@2.x".
     [exec] [0m[5/5] Building fresh packages...
     [exec] success Saved lockfile.
     [exec] $ yarn run typings && yarn run build
     [exec] yarn run v1.10.1
     [exec] $ typings install
     [exec] [91mtypings WARN deprecated 2016-5-10: "registry:dt/js-yaml#3.5.2+20160316171810" is deprecated (updated, replaced or removed)
     [exec] [0m[?25h
     [exec] +-- angular (global)
     [exec] +-- angular-animate (global)
     [exec] +-- angular-cookies (global)
     [exec] +-- angular-material (global)
     [exec] +-- angular-mocks (global)
     [exec] +-- angular-resource (global)
     [exec] +-- angular-route (global)
     [exec] +-- angular-sanitize (global)
     [exec] +-- jasmine (global)
     [exec] +-- jquery (global)
     [exec] +-- js-yaml (global)
     [exec] +-- karma-jasmine (global)
     [exec] +-- moment (global)
     [exec] `-- moment-node (global)
     [exec] 
     [exec] Done in 1.86s.
     [exec] yarn run v1.10.1
     [exec] $ gulp build
     [exec] Using remote Che server http://localhost:8080
     [exec] [18:58:32] Using gulpfile /dashboard/gulpfile.js
     [exec] [18:58:32] Starting 'outputcolorstemplate'...
     [exec] [18:58:32] Starting 'proxySettingsTemplate'...
     [exec] [18:58:32] Starting 'colorstemplate'...
     [exec] [18:58:32] Starting 'styles'...
     [exec] [18:58:33] Starting 'partials'...
     [exec] [18:58:33] Starting 'images'...
     [exec] [18:58:33] Starting 'htmlassets'...
     [exec] [18:58:33] Starting 'brandingassets'...
     [exec] [18:58:33] Starting 'existingfonts'...
     [exec] [18:58:33] Starting 'other'...
     [exec] [18:58:33] Finished 'htmlassets' after 39 ms
     [exec] [18:58:33] Finished 'outputcolorstemplate' after 1.47 s
     [exec] [18:58:33] Starting 'outputcolors'...
     [exec] [18:58:33] Finished 'proxySettingsTemplate' after 1.46 s
     [exec] [18:58:33] Starting 'proxySettings'...
     [exec] [18:58:33] Finished 'colorstemplate' after 1.46 s
     [exec] [18:58:33] Starting 'colors'...
     [exec] [18:58:33] Finished 'outputcolors' after 44 ms
     [exec] [18:58:33] Finished 'proxySettings' after 36 ms
     [exec] [18:58:33] Finished 'colors' after 31 ms
     [exec] [18:58:33] Starting 'scripts'...
     [exec] [18:58:36] Finished 'brandingassets' after 2.7 s
     [exec] [18:58:38] Finished 'images' after 5 s
     [exec] [18:58:38] Finished 'existingfonts' after 5.62 s
     [exec] [18:58:38] Starting 'fonts'...
Hash: 69ff744d8e7b063b3651
Version: webpack 4.22.0
Time: 98137ms
Built at: 2018-10-22 18:59:01
 17 assets
Entrypoint main = bundle.js bundle.js.map
  [49] (webpack)/buildin/global.js 489 bytes {0} [built]
 [167] ./node_modules/jsonc-parser/lib/esm/main.js + 2 modules 53.6 KiB {0} [built]
       |    3 modules
 [400] (webpack)/buildin/module.js 497 bytes {0} [built]
 [712] ./node_modules/react-virtualized/dist/es/index.js + 66 modules 324 KiB {0} [built]
       |    67 modules
 [716] ./src-gen/frontend/index.js 7.25 KiB {0} [built]
[1041] ./node_modules/moment/locale sync ^\.\/.*$ 2.91 KiB {0} [optional] [built]
[1122] ./node_modules/vscode-textmate/release sync 160 bytes {0} [built]
[1751] ./node_modules/@theia/debug/node_modules/jsonc-parser/lib/esm/main.js + 4 modules 54.3 KiB {0} [built]
       |    5 modules
    + 1744 hidden modules

WARNING in ./node_modules/vscode-textmate/release/main.js 14:15-27
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js
 @ ./node_modules/@theia/monaco/lib/browser/textmate/index.js
 @ ./node_modules/@theia/python/lib/browser/python-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ./node_modules/vscode-textmate/release/main.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap '_suffix.js.map': Error: Can't resolve './_suffix.js.map' in '/home/theia/node_modules/vscode-textmate/release'
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js 73:24-50
 @ ./node_modules/@theia/monaco/lib/browser/textmate/index.js
 @ ./node_modules/@theia/python/lib/browser/python-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ./node_modules/typescript-language-server/lib/commands.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/commands.ts': Error: Can't resolve '../src/commands.ts' in '/home/theia/node_modules/typescript-language-server/lib'
 @ ./node_modules/@theia/typescript/lib/browser/typescript-frontend-contribution.js 83:17-67
 @ ./node_modules/@theia/typescript/lib/browser/typescript-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ./node_modules/reflect-metadata/Reflect.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file 'Reflect.ts': Error: Can't resolve './Reflect.ts' in '/home/theia/node_modules/reflect-metadata'
 @ ./src-gen/frontend/index.js 3:0-27

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve '@eclipse-che/theia-activity-tracker/lib/browser/che-theia-activity-tracker-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 79:47-148

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve '@eclipse-che/theia-dashboard-extension/lib/browser/che-theia-dashboard-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 75:47-135

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve '@eclipse-che/theia-factory-extension/lib/browser/che-theia-factory-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 74:47-140

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve '@eclipse-che/theia-java-extension/lib/browser/che-theia-java-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 76:47-134

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve '@eclipse-che/theia-task-extension/lib/browser/che-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 78:47-123

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve 'che-theia-ssh-extension/lib/browser/ssh-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 72:47-113

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve 'che-theia-terminal/lib/browser/terminal-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 77:47-113

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve 'github-extension/lib/browser/github-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 71:47-109

ERROR in ./src-gen/frontend/index.js
Module not found: Error: Can't resolve 'theia-machines-extension/lib/browser/theia-machines-frontend-module' in '/home/theia/src-gen/frontend'
 @ ./src-gen/frontend/index.js 73:47-125
Child worker:
     2 assets
    Entrypoint main = worker-ext.4b58979dadecf0f112a4.js worker-ext.4b58979dadecf0f112a4.js.map
     [7] (webpack)/buildin/global.js 489 bytes {0} [built]
    [84] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 83 hidden modules

[91mError: webpack exited with an unexpected code: 2.
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/application-manager/lib/application-process.js:66:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[0m[91merror Command failed with exit code 1.
[0minfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c /tmp/builder/scripts/assemble-theia.sh' returned a non-zero code: 1
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[JENKINS] Archiving disabled
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds

</details>

https://gist.github.com/skabashnyuk/1b38dccfcd14c59d33656e5eee4fba02
https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1040/console

**Comment by AndrienkoAleksandr** [comment]
Seems it's infrastructure issue.

**Comment by AndrienkoAleksandr** [comment]
Should be fixed.
