### ISSUE TITLE
Add Theia Plugin APIs to support VS Code Camel Tooling

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11705]
It would be nice to cover the use case of Camel Language Server https://marketplace.visualstudio.com/items?itemName=camel-tooling.vscode-apache-camel
The VS Code plugin is here https://github.com/camel-tooling/camel-lsp-client-vscode
The Server code is here https://github.com/camel-tooling/camel-language-server

I'm not sure how to know all the API/commands that are used.

On Language Server side, we can see the "activated" features here https://github.com/camel-tooling/camel-language-server/blob/c50fb5954cf521b3471651e2856ca4e1ce00b8a9/src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java#L78-L86

~~Please note that for now when using the released VS Code plugin NPEs are thrown, which seems to be due to the fact that exitServer is called before a startServer. I made it more robust to avoid NPE camel-tooling/camel-language-server#166 and it will be better in next release.~~ _--> it is now fixed_
Even wit this new version, it is not working, there is no more errors or logs.
Reported camel-tooling/camel-lsp-client-vscode#72 to be able to remote debug the server part.

//cc @slemeur

**Comment by apupier** [comment]
@benoitf tried it on a "pure" Theia and it is working. he reproduced the error on che.openshift.io

things interesting to try:
- try installation on theiaide/theia-full
- try in Che with a stack not containing other "default plugins"
- try to install from a specific registry

**Comment by paoloantinori** [comment]
// subscribe

**Comment by benoitf** [comment]
@paoloantinori FYI there is on the right column on github a `Notifications` section with a button `subscribe` if you need to get notify on new comments

**Comment by tsmaeder** [comment]
The API usage report shows no unimplemented APIs used by the Camel extensions. Closing this one.
