### ISSUE TITLE
How to get all workpaces info created by users ?

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#11714]
Hi all,
     We are trying to show contents created by our scientists inside their workspaces in our platform. Che is included inside this platform thanks to an Iframe.
      As an admin, I want to get all of workspaces created by the user using the api workspaces/get, but I get just mine. Is it possible to do that ? 
     Thanks in advance

**Comment by skabashnyuk** [comment]
@KOSSOKO take a look on method ``` GET /workspace/namespace/{namesapcename}```  ```  @Path("/namespace/{namespace:.*}")``` . Also make sure you admin is che admin, see ```che.system.admin_name``` in configuration.

**Comment by KOSSOKO** [comment]
@skabashnyuk thanks for your answer. Sorry but I didn't totally understand. For example, when I do this request using swagger as admin `http://ipadresse:8088/api/workspace/namespace/kosted` I got 

> {
>   "message": "User is not authorized to use specified account"
> }

About `@Path("/namespace/{namespace:.*}")`, you meant that I have to set the namespace by .* ? I tried, but got the error 404 not found

**Comment by KOSSOKO** [comment]
@skabashnyuk thanks I understand well. I discover also after looking in the che database that the namespace is the username of a user.
The problem now is when I run my request outside swagger context, in the java code of my back end, I got the error 

> token is missing.
How could I generate a token or disable this security? All of my system (Che, Liferay, my back end) are in a protected zone, behind the bastion, so I don't really need this security

**Comment by skabashnyuk** [comment]
you can use this property to setup che admin
```
#     Grant system permission for 'che.admin.name' user. If the user already exists it'll happen on
#     component startup, if not - during the first login when user is persisted in the database.
che.system.admin_name=admin
```
and this page to get info about how to get token
https://www.eclipse.org/che/docs/authentication.html#obtaining-token-from-keycloak

**Comment by KOSSOKO** [comment]
@skabashnyuk thanks a lot

**Comment by KOSSOKO** [comment]
@skabashnyuk where could I find this `che.system.admin_name=admin` variable ?

And if I understand well, to allow the admin profile to get all users metadata, I have to setup che.system.admin_name to admin ? 

In my code, with all information you gave to me, I have for each user to send a request. But, the problem is that I can't have the password. If I can use the profile admin with the password admin, I can get all workspaces, then in a second time, I can filter to keep only workspaces for the current user, because the pseudo (namespace) of the current user is something I have.
		```
HttpUriRequest request = RequestBuilder.post()
				.setUri("http://myurl:5050/auth/realms/che/protocol/openid-connect/token")
				.setHeader("Content-Type", "application/x-www-form-urlencoded")
				.setHeader("Accept", "application/json")
				.addParameter("username", "myusername")
				.addParameter("client_id", "che-public")
				.addParameter("password", "theUserPassword")
				.addParameter("grant_type", "password")
				.build();
		HttpClient client = HttpClientBuilder.create().build();
		HttpResponse response = client.execute(request);
		HttpEntity entity = response.getEntity();

```

**Comment by skabashnyuk** [comment]
@KOSSOKO We updating our documentation regarding systemAdmin role
It should help you.  https://github.com/eclipse/che-docs/pull/549/files

**Comment by KOSSOKO** [comment]
@skabashnyuk thanks a lot.

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen if you think it's needed.

**Comment by puneetshukla-siemens** [comment]
I have multi-host eclipse che deployed in K8s running in aws, As a admin in want all the workspace created by different users. But with admin login I can only see workspace created by admin and workspace comes under organization created by admin.
Is there a way to get all the workspace by different users?
