### ISSUE TITLE
Create workspace - Add project - git URL never adds the project

### ISSUE THREAD

**Issue by DougTidwell** [eclipse-che/che#11717]
### Description
Using the web UI to create a new workspace, it's impossible to add a project via a git URL. 

### Reproduction Steps
1. Open the New workspace page. 
1. Select a stack and scroll down to Add or Import Project.
1. Paste in the URL of a git repo. 
1. Click the Add button. A green check mark appears in the entry field next to the URL, but the project is never added to the workspace. [NB: It isn't clear what the check mark indicates. Putting a nonexistent URL in the field still gives me the check box.]

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/2179651/47417224-d20dcd00-d777-11e8-848d-8677d401e6f0.png">

If I click the Create button to start the workspace, it tells me that I have unsaved changes. So somewhere in the system it knows I've added a project: 

<img width="760" alt="image" src="https://user-images.githubusercontent.com/2179651/47417868-367d5c00-d779-11e8-9026-4a79f7cb5e04.png">

**OS and version:**    
Mac High Sierra 10.13.6. Fails in Safari, Chrome, and Firefox. 

**Diagnostics:** 
All tests passed, fwiw.

**Comment by DougTidwell** [comment]
Update: Also fails on Firefox on Fedora Server 28 and in Edge and Chrome on Windows 10.

**Comment by ashumilova** [comment]
@DougTidwell Did you click on Add button on project popover layout? This may be the cause of that warning.
