### ISSUE TITLE
Che samples docs

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11721]
### Description
Each sample https://github.com/che-samples/ should contain :
- How to build
- How to run section

**Comment by mkuznyetsov** [comment]
Added README to following che assembly samples:
https://github.com/che-samples/che-plugin-json/pull/21
https://github.com/che-samples/che-ide-extension/pull/23
https://github.com/che-samples/che-ide-server-extension/pull/23
https://github.com/che-samples/che-plugin-menu/pull/18
https://github.com/che-samples/che-plugin-embedjs/pull/18
https://github.com/che-samples/che-plugin-wizard/pull/19
