### ISSUE TITLE
Java Documentation doesn't open in the editor by key combination ("Ctrl" + "q")

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11735]
**Reproducing:**
 - reproduced only on OCP assembly

**Related test:**
 - CheckAutocompleteFeaturesInTheTestFolderTest

### Reproduction Steps
 - Run "java" default stack with default "spring" project
 - In the started workspace open the "GreetingController.java" file
 - Place cursor on the middle of the "String" word
 - Press "Ctrl" + "q" key combination
 - Pay attention that documentation doesn't open (also by using context menu)

**Expected behavior:**
Java documentation popup is opened and "String" class documentation displayed

**Observed behavior:**
Java documentation is not opened

**OS and version:**    
Che 6.14.0 ; Chrome 28 ; Fedora 28

**Comment by tsmaeder** [comment]
This works for me on local docker. The fact that it's on ocp should really not make any difference on whether a keybinding works. Does hover work in the same place? Otherwise, I'll need to have more info to analyze this.

**Comment by Ohrimenko1988** [comment]
I didn't find any errors in the logs. So probably you should just reproduce it. This bug reproduces only on openshift assembly (As I wrote in description)
