### ISSUE TITLE
Hints do not display after press "Ctrl" + "p" keys combination when cursor placed between arguments brackets in the method

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#11747]
**Notes**
 - Permanent reproduced bug
 - Reproduced after merge "jdt ls"

**Related test:**
 - ShowHintsCommandTest

### Reproduction Steps
 - Run default "Java" stack with default "spring" project
 - In the opened workspace open the "GreetingController.java" file
 - In the opened file place cursor to 21-th line
 - Type next code:
```
String.format()
``` 
 - Place cursor between brackets
 - Press "Ctrl" + "p" keys combination
 - Pay attention that hints are not displayed 

**Expected Behavior:**
Hints with arguments suggestions are displayed 

**Observed Behavior:**
Hints are not displayed

**Browser log:**
[browser.log](https://github.com/eclipse/che/files/2518966/browser.log)

**Workspace logs:**
[localhost-access.log](https://github.com/eclipse/che/files/2518967/localhost-access.log)
[catalina.log](https://github.com/eclipse/che/files/2518968/catalina.log)
[bootstrapper.log](https://github.com/eclipse/che/files/2518970/bootstrapper.log)

**Report with reproduced bug:**
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/406/Selenium_20tests_20report/

**OS and version:**    
Che 6.14.0 ; Chrome 68.0 ; Fedora 28

**Diagnostics:**

**Comment by gorkem** [comment]
Sounds like Che 6
