### ISSUE TITLE
Che-theia: hosted mode, user should be able to use / exclude some plugins to be used in hosted mode

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#11764]
### Description
The goal is to find a mechanism for developers who wants to work on existing default che-theia plugins: for instance factory-plugin. Hosted mode include by default factory-plugin, but running the customized hosted factory plugin.
Hosted theia should be as closed as possible but do not include default factory plugin include customized factory plugin

**Comment by gorkem** [comment]
I am not sure I follow the request on this one? Are you thinking about extensions vs plugins ?
