### ISSUE TITLE
Che-theia loader undefined

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#11773]
### Description
When opening (a starting) a stopped workspace, Che is showing the loader with the error 'undefined'

![eclipse che che7-theia-dev - google chrome_162](https://user-images.githubusercontent.com/650571/47704067-a6309280-dc22-11e8-8d23-c977266f4a24.png)

### Reproduction Steps
- Create a new workspace with the che7 stack
- click 'open'
- the error appears within the loader

**OS and version:**    
Could reproduce in che.openshift.io

**Diagnostics:** 

Maybe between the openshift events:
- Scheduled 	Successfully assigned workspaces.... to ip-172-31-xx-xx.us-east-2.compute.internal
- Pulling 	pulling image "wsskeleton/che-plugin-dev-tooling"

**Comment by OonjuoO** [comment]
Hello, 

I tried several che-server images, all of them would pop up this undefined error when I try to create a workspace. 

But it seems this problem is not solved yet, is there any work around to escape this undefined error?
I am using helm chart to deploy che on K8s.

Thanks

**Comment by rhopp** [comment]
I'm able to reproduce this error also with che6 workspaces on che.openshift.io.

**Comment by evidolob** [comment]
![screen shot 2019-02-20 at 17 37 12](https://user-images.githubusercontent.com/929743/53103621-a38ddc00-3536-11e9-81f6-d84dd5acd7fa.png)
Some additional info, thx to @vparfonov

**Comment by evidolob** [comment]
@rhopp If you have steps to reproduce, can you add them in this issue?
