### ISSUE TITLE
Add Theia Plugin APIs to support VS Code XML Tooling

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11775]
### Description

Che is not providing XML support currently; it would be nice to reuse the VS Code xml work https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml

### Reproduction Steps
 currently it is failing with:

```
root ERROR [hosted-plugin: 211] (node:211) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at getSettings (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/out/src/extension.js:74:29)
    at requirements.resolveRequirements.catch.then.requirements (/tmp/vscode-unpacked/vscode_extension_redhat_vscode_xml.vsix/extension/out/src/extension.js:45:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

the corresponding code is:
```
function getSettings() {
        let configXML = vscode_1.workspace.getConfiguration();
        configXML = configXML.get('xml');
        let x = JSON.stringify(configXML);
        let settings = JSON.parse(x);
        settings['logs']['file'] = logfile;
        return settings;
    }
```

Line 74 is the JSON.parse

**OS and version:**    

**Diagnostics:**

**Comment by apupier** [comment]
seems to be a Theia issue so reported https://github.com/theia-ide/theia/issues/3317

**Comment by skabashnyuk** [comment]
@ashumilova @evidolob can you help here?

**Comment by slemeur** [comment]
@evidolob + @tsmaeder : Could you check the status of this issue regarding the progress on https://github.com/theia-ide/theia/issues/2341  ?

**Comment by tsmaeder** [comment]
@slemeur testing the xml plugin (and identifying missing/broken API is on our plan), however, there are two things you might not be aware of: 
1. Plugins use VSCode API beyond the "languages" namespace
2. The "renameProvider" API is still missing. As far as I understand, the IDE2 team is tasked with completing https://github.com/theia-ide/theia/issues/2341

**Comment by tsmaeder** [comment]
Update: there seems to be a PR pending for the rename provider.

**Comment by benoitf** [comment]
rename provider https://github.com/theia-ide/theia/pull/4025 has been merged upstream

**Comment by apupier** [comment]
@benoitf @tsmaeder if I understand well, this has been done, right?
If yes, I will close the issue

**Comment by tsmaeder** [comment]
Well, we added a lot of API, did you recently try to run the camel extension in Theia again?

**Comment by apupier** [comment]
no, I haven't recently try to run the Camel Extension but this issue is about XML in general.

**Comment by apupier** [comment]
this issue is about pure XML.
As the item to have xml support in Che is closed, it means that it has been done for Theia: https://github.com/eclipse/che/issues/12437
