### ISSUE TITLE
ANTLR4 Parser for Eclipse Che

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#11772]
Hi,
Does Eclipse Che support ANTLR4? Is it possible to implement a parser (created using ANTLR4) in Eclipse Che?
I've been trying for so long to implement such a parser to Che. I just wanted to know whether it's possible so that I could move on to Xtext. Please let me know whether ANTLR4 is supported in Che.
Thanks in advance!

**Comment by eivantsov** [comment]
@SharkJ it depends on what exactly you are trying to achieve. Can you elaborate?

**Comment by SharkJ** [comment]
I have a .g4 file for a custom language from which I can generate the necessary lexer, parser etc. I want to implement this language into Eclipse Che, so that when I enter a statement/expression, the editor identifies it. I know this requires language server support. However, I couldn't find a way to implement a language server for ANTLR4 grammar that could be implemented to Eclipse Che. Can you let me know if there is such a method?
To make it more simple, I want my ANTLR4 language to work the same way as it was when I created a DSL in Xtext, ran it in a Docker container, and implemented it in a stack.

**Comment by skabashnyuk** [comment]
@SharkJ I think there is no bridge between ANTLR4 grammar for a random language and language server implementation.

**Comment by SharkJ** [comment]
Then, what should be the correct procedure I must follow if I want to implement a DSL made using ANTLR4+Java into Eclipse Che? Could you kindly let me know?

**Comment by SharkJ** [comment]
If I'm to extend the JDT.LS support (which I believe is easier to implement than creating my own Java LS), what is the process to follow to implement it as a sidecar to che? 

> I think there is no bridge between ANTLR4 grammar for a random language and language server implementation.

Does the above mean that there is no possible way to connect my ANTLR4 grammar into the Java LS support using the parser, lexer, etc. generated by it? Does one have to create his own text highlighting, code completion etc. if he is to implement language support to ANTLR4-based DSL?

**Comment by skabashnyuk** [comment]
@tsmaeder @tolusha can you help here? This topic becomes out of my expertize.

**Comment by tsmaeder** [comment]
@SharkJ Che uses Language Server Protocol in order to implement things like code assist, go to definition, etc. So if you want to add support for a new language (whether trough a parser generated by Antlr or any other way), you need to need a language server. In order to implement a language server, you need to have code that can answer the requests LSP specifies, like: "in Text file foo.mylang, line 15, position 7, what could be possible completions?". I am not aware of a library that can take an arbitrary grammar (or parser) and create a language server from it.

**Comment by tsmaeder** [comment]
To me, it's still not clear what features you want to enable in the editor. Syntax highlighting? Code completion?

**Comment by SharkJ** [comment]
Thank You! It became a little clear to me the path that I should follow. I want to implement the basic developer support provided by the editor. To start with I'm trying to find out the way to implement syntax highlighting and code completion.
