### ISSUE TITLE
CORS header(s) to be added

### ISSUE THREAD

**Issue by delchev** [eclipse-che/che#11774]
### Description
I would like to run my WebIDE in Che 7 (dev) - Eclipse Dirigible. I have prepared the necessary descriptors, publish them, configure the workspace and it runs successfully. The issue is that Dirigible WebIDE requires access to the top level page objects e.g. window, to communicate between the components served via iframes.

Ref: https://enable-cors.org/

### Reproduction Steps
The plugin sources:
https://github.com/dirigiblelabs/dirigible-che-editor-plugin
Published at OpenShift:
https://che-plugin-registry-delchevn.4e1e.starter-us-east-1b.openshiftapps.com/plugins/dirigible-che-editor-plugin:1.0.0

In the Che wrapper page e.g. https://che.openshift.io/dashboard/#/ide/XXX/wksp-uknv
it appears only the side-bar of Dirigible.
In the standalone/direct link e.g. https://routeom5ypznw-XXX-che.4e1e.starter-us-east-1b.openshiftapps.com/services/v3/web/ide/index.html
it functioning normally. 

**OS and version:**    
Che 7 dev

**Diagnostics:** 
A possible fix would be all the hosts serving the Che workspace components to be allowed via CORS headers to have access to the top level Che wrapper page.
Another option is the workspace link from the Che side-bar to open the WebIDE in a new window instead of the embedded iframe.

**Comment by skabashnyuk** [comment]
can you share your workspace config?

**Comment by slemeur** [comment]
cc @slemeur

**Comment by l0rd** [comment]
cc @ashumilova @evidolob

**Comment by skabashnyuk** [comment]
Have some issues to reproduce this on OpenShift
![11 18 40](https://user-images.githubusercontent.com/1614429/47778121-cfbeec00-dcfe-11e8-9584-6e79ee14ae0c.png)

**Comment by skabashnyuk** [comment]
As far as I can see all images starting from root https://github.com/eclipse/dirigible/tree/master/releng

**Comment by delchev** [comment]
Sorry! I was pushed it manually yesterday for my tests. No it is fixed via https://github.com/eclipse/dirigible/issues/361 and updated https://hub.docker.com/r/dirigiblelabs/dirigible-anonymous/tags/ by the CI

Just start again your test workspace. Initially it will give an error that the application is not available, but after a few seconds (Dirigible's bootstrap time) you can reload the iframe and it appears.

**Comment by delchev** [comment]
this is my workspace config:

```
{
  "projects": [],
  "commands": [
    {
      "commandLine": "echo ${CHE_OSO_CLUSTER//api/console}",
      "name": "Get OpenShift Console URL",
      "type": "",
      "attributes": {}
    }
  ],
  "defaultEnv": "default",
  "environments": {
    "default": {
      "recipe": {
        "contentType": "application/x-yaml",
        "type": "openshift",
        "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: wsskeleton/che-plugin-dev-tooling\n     name: dev\n     resources:\n      limits:\n       memory: 512Mi\n"
      },
      "machines": {
        "ws/dev": {
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {},
          "attributes": {
            "memoryLimitBytes": "536870912"
          }
        }
      }
    }
  },
  "name": "wksp-uknv",
  "attributes": {
    "che.server.secure_exposer": "default",
    "plugins": "che-machine-exec-plugin:0.0.1",
    "editor": "https://che-plugin-registry-delchevn.4e1e.starter-us-east-1b.openshiftapps.com/plugins/dirigible-che-editor-plugin:1.0.0"
  },
  "links": []
}
```

**Comment by skabashnyuk** [comment]
@delchev I was able to reproduce this issue. Can you clarify what will happen when we enable cors? I mean what Eclipse Dirigible are going to do with the parent frame?

**Comment by delchev** [comment]
@skabashnyuk , we would like to to use window.postMessage() and window.addEventListener() https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage for cross-iframe communication. To be able to do so, we need permissions for the top level page. In a standalone Dirigible we load the message-hub.js script in the top level page itself, that's why it works even on OpenShift as a standalone app. When the Dirigible's WebIDE is embedded within another outer page it does not have permissions by default to manipulate window object. The CORS headers set this permissions and the browser allow a page fed from the exact location (from CORS) to access window object. We need only permissions for the hosts/containers from the same workspace not the whole OpenShift which will be security issue.

**Comment by skabashnyuk** [comment]
@delchev I've talked with @vitaliy-guliy . And we have such question.
Is this code https://github.com/eclipse/dirigible/blob/master/ide/ui/ide-core/src/main/resources/ide-core/ui/message-hub.js#L34
and Eclipse Dirigible itself expect that parent iframe can be loaded from another host?

Because this error looks that they are not expected.
![12 51 38](https://user-images.githubusercontent.com/1614429/47847934-6c53bd80-ddd5-11e8-8372-f7fc5911e6f6.png)
![12 51 26](https://user-images.githubusercontent.com/1614429/47847935-6c53bd80-ddd5-11e8-9d5a-bdd474c82a63.png)
And this is not http request where CORS can help. We tend to think that this more message-hub.js issue.

**Comment by delchev** [comment]
Thanks a lot @skabashnyuk and @vitaliy-guliy for the quick investigation! We with @shturec tried to dynamically resolve the 'top' dirigible's window in our code. The fix was provided with: https://github.com/eclipse/dirigible/issues/362 and https://github.com/eclipse/dirigible/issues/363 and it works just fine:
![dirigible_in_che](https://user-images.githubusercontent.com/6852373/47922178-1e1ae900-debf-11e8-9816-a1a60f50cc89.png)

**Comment by skabashnyuk** [comment]
Cool. 
@delchev  Can you let us know:
- when a new image will be available?
- are you going to submit dirigible editor https://github.com/eclipse/che-plugin-registry

**Comment by delchev** [comment]
Thanks @skabashnyuk !
For completeness the pull request for https://github.com/eclipse/che-plugin-registry is https://github.com/eclipse/che-plugin-registry/pull/54
and the new image built by CI at:
https://hub.docker.com/r/dirigiblelabs/dirigible-anonymous/tags/
