### ISSUE TITLE
Allow configuration of syntax highlighting

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-che/che#1178]
We need a way to configure orion with syntax highlighting for additional mime types.
Currently it seems like the way is to patch embeddedToolingPlugin.js, which is inconvenient.

**Comment by svenefftinge** [comment]
I think it would be good to add a method to org.eclipse.che.ide.editor.orion.client.jso.OrionCodeEditWidgetOverlay which allows to access the serviceRegistry.

**Comment by ashumilova** [comment]
If you need Che support additional highlighting (supported by Orion) - you can register it [here](https://github.com/eclipse/che/blob/master/core/ide/che-core-ide-jseditor/src/main/java/org/eclipse/che/ide/jseditor/client/filetype/ExtensionFileTypeIdentifier.java) by file extension. 
If you need to add new content type to Orion, then we can create an issue to provide access to services like "orion.core.contenttype" one.

**Comment by svenefftinge** [comment]
I would like to add not-yet-supported highlighting. The hook you reference only let me associate file extensions with mime types, what I was asking is to add a new mime-type together with an [orion highlighting service](https://wiki.eclipse.org/Orion/Documentation/Developer_Guide/Plugging_into_the_editor#orion.edit.highlighter).
