### ISSUE TITLE
Unexpected fail of FindUsagesBaseOperationTest selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11780]
### Description
We have unexpected fail of **FindUsagesBaseOperationTest** selenium test. The test sometimes fails after selecting item in **Find Usage** panel by **ENTER** key. We should clarify reason and fix it.

**Failed selenium test:** FindUsagesBaseOperationTest.

**Log:**
```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for org.eclipse.che.selenium.pageobject.CodenvyEditor$$Lambda$145/1175825039@5bbc4bad (tried for 10 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144'
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.CodenvyEditor.expectedNumberOfActiveLine(CodenvyEditor.java:1782)
	at org.eclipse.che.selenium.miscellaneous.FindUsagesBaseOperationTest.checkFindUsagesBaseOperation(FindUsagesBaseOperationTest.java:218)
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/411/Selenium_20tests_20report/

**Screenshot:**
![org eclipse che selenium miscellaneous findusagesbaseoperationtest checkfindusagesbaseoperation_time-1540854292842-millis](https://user-images.githubusercontent.com/7760565/47728958-0138a880-dc68-11e8-81ad-57d8b86ae050.png)

**Comment by rhopp** [comment]
Not relevant anymore. Closing.
