### ISSUE TITLE
Create docs on how to prepare Che installation to showcase Che 7 and other stuff in a case when internet is completely down

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11793]
### Description
Che is using the internet for downloading docker images heavily. In some environments, such as conference booth or a talk/workshop internet connection is completely down and we struggle to show at least something on our laptops. 
We should have a plan B that would not require usage of internet connection if everything is pre-pulled. 
Some features might not work (e.g. git clone) but we would be able to show something at least.
It also would help us to preserve a preconfigured state of Che for the case when some breaking change is introduced during the conference and breaks the talk/workshop/booth demos.    

We need a document that describes how to configure Che to:
- not to pull images from the internet
- not connect to remote services during the start of a workspace
And also:
- how to discover what is needed to be pre-pulled
- how to pre-pull that and retag to not being erased by the next pulling
 
This should include:
- workspace images
- Che installation images (including registry, keycloak, postgre) 
- brokers
- sidecars (Theia, etc)
- not well-known sidecars (JWTProxy)

Would be also useful to have a description on how to deal with the npm/maven/git in a network outage case.

We also need instructions on how Che/Openshift/Kubernetes (and different flavors) behave when you change the network from LAN cable to WiFi, from one WiFi to another one and so on. This would warn ppl that changing of some networks might break the installation.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by l0rd** [comment]
@garagatyi that's useful. Once we have the documentation we should also have an e2e that verifies that we don't break it. Not sure we can fit it in K train or in a team backlog. It could be a task for the next (lucky :-)) member of the team that will speak at a conference.
 
Something I believe is missing from your list are npm/maven/git servers. That something that we usually need during a demo.

**Comment by garagatyi** [comment]
Added `npm/maven/git` to the description

**Comment by themr0c** [comment]
@garagatyi I am closing this issue because I believe the current state of https://www.eclipse.org/che/docs/che-7/installing-che-in-restricted-environment/ is satisfying the requirements expressed here. Please reopen, or open a more specific issue, for anything missing in current documentation.
