### ISSUE TITLE
Include sidecars memory into total memory of workspace on dashboard

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#11801]
### Description
When a Che 7 workspace is created, dashboard shows RAM consuming only for added by user machines and doesn't include sidecars (IDEs, plugins) in total sum. In such case dashboard shows needed RAM for workspace not correctly.
More specific example: user's container needs 1Gb of RAM (and this is shown), but actual consuming is, for example, 3Gb (2Gb is needed for sidecars).

### Reproduction Steps
Create Che 7 workspace, add IDE and plugin(s). Dashboard shows memory only for user defined machine(s).

**Comment by l0rd** [comment]
The `memory-limit` attribute of an editor/plugin is currently defined in the [che_pluing.yaml](https://github.com/ws-skeleton/che-editor-theia/blob/master/etc/che-plugin.yaml#L41). Currently the dashboard doesn't have access to that attribute. 

The possible solution that comes to mind is to add the memory-limit field in the plugin registry meta.yaml files. If not set the dashboard will override it to a default of 500MB.

To overwrite the memory setting the dashboard should set the following attribute in the workspace config json:

```json
"sidecar.<plugin-id>.memory_limit": "300Mi"
```

**Comment by garagatyi** [comment]
It is also possible that che-plugin.yaml doesn't contain memory limit field. Then Che master would use its default value.
Another case is when Che master adds some additional sidecars, e.g. jwt-proxy sidecar. It is not shown anywhere in the workspace config that this sidecar will be added.

**Comment by benoitf** [comment]
I agree that today it's very difficult to users to know how to override the memory as it's based on the container name, so even if you do know the plug-in which is installed you don't know why attribute to use.
So to provide this nice UX in UD, somehow UD need to ask wsmaster

**Comment by garagatyi** [comment]
If we want to have a precise memory estimation than UD cannot do that technically.
For now, we don't even have a way how to do that on wsmaster to provide an API or so.

**Comment by l0rd** [comment]
> If we want to have a precise memory estimation than UD cannot do that technically.
For now, we don't even have a way how to do that on wsmaster to provide an API or so.

UD can do that if memory limit are in meta.yaml. UD can set the memory limit in workspcae configuration attributes. We don't need to add that to wsmaster API. Let's not make it more complicated than it is.

**Comment by l0rd** [comment]
As a prerequisite to fix this @ibuziuk team will work on  #12908

**Comment by mmorhun** [comment]
The issue is still actual. On dashboard I still see `-` in the `RAM` column for a workspace.

**Comment by sleshchenko** [comment]
The references UI is not available on the new dashboard

**Comment by mmorhun** [comment]
Is there any plans to have some indicator that shows how many resources a workspace consumes?
