### ISSUE TITLE
Do not hardcode IDE servers names on Che master

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11802]
### Description
We track servers with specific names and show status in the API. We should reconsider this approach to be able to adopt other IDEs and not fail workspace when some server appears to have the same name as a hardcoded one but has different API

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
is this the same issue https://github.com/eclipse/che/issues/10273?

**Comment by garagatyi** [comment]
Yeah, I think it is a duplicate. Closing it.
