### ISSUE TITLE
Get Started Webpage Has Incorrect Spelling

### ISSUE THREAD

**Issue by bryantson** [eclipse-che/che#11807]
### Description

Eclipse Che's Getting Started page has the incorrect spelling:
https://www.eclipse.org/che/getting-started/

It should "che.openshift.io"

kind/docs level/beginner

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
Thanks for spotting that! 

@eivantsov do you happen to know who has access to fix that?

**Comment by curran** [comment]
Hilarious.

**Comment by eivantsov** [comment]
Fixed
