### ISSUE TITLE
Apply ability filter user containers from among others

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#11804]
### Description
In the Che 7 Workspace Model, a user is able to define a list of own "containers" and apply Che Plugins "tooling containers". Then all containers(machines) are available in `Workspace#getRuntime#getMachines` but it is not possible to identify which of containers are user-defined.
It makes sense to have an ability to identify where container comes from User Recipe or Che Plugin since this list is used for opening a terminal, executing of command.
A special attribute in [Machine#getAttributes](https://github.com/eclipse/che/blob/master/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/runtime/Machine.java#L24) would be fine.

**Comment by garagatyi** [comment]
Well, sometimes it makes sense to execute command or have a terminal into tolling containers too! For example into Theia container

**Comment by sleshchenko** [comment]
> Well, sometimes it makes sense to execute command or have a terminal into tolling containers too! For example into Theia container

@garagatyi Yeah, I agree. Let me clarify that Client would be able not just filter machines, but like order them (like first user-defined and then tooling) or display some labels near machine names to make it clear where it comes from.

**Comment by slemeur** [comment]
What is your proposal for jwt-proxy then?

**Comment by AndrienkoAleksandr** [comment]
Needed for https://github.com/eclipse/che/issues/11804 too.
