### ISSUE TITLE
Allow adding Che 7 plugins and editors from a custom registry on UD

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11819]
### Description
PR #11588 brought an ability to use the custom registry for Che 7 plugins.
To leverage that user has to add it in a RAW workspace config on UD since UD doesn't support this feature directly. 
It would be awesome to have a direct support of it on the UD.
BTW we have another issue to add support of specifying meta.yaml URL without a need for a custom registry. Would be cool to have UD support of it too.  

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
Does not this issue duplicate https://github.com/eclipse/che/issues/11642 ?

**Comment by garagatyi** [comment]
Absolutely
