### ISSUE TITLE
[broker] Theia plug-in broker should not rely on plugin's name

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#11827]
### Description
Theia plug-in broker is using plugin's name for workspace convention, etc
https://github.com/eclipse/che-plugin-registry/blob/master/plugins/org.eclipse.che.samples.container-fortune/0.0.1/meta.yaml

Then we need to have short name in the meta.yaml

The name is and should be only display name so it should not be mandatory to have a name less than 20 characters and without spaces.

### Reproduction Steps
If we deploy a plug-in like https://github.com/eclipse/che-plugin-registry/blob/master/plugins/org.eclipse.che.samples.container-fortune/0.0.1/meta.yaml but with a name longer or with spaces, deployment is failing.

cc @garagatyi

**Comment by garagatyi** [comment]
Cannot reproduce anymore.
