### ISSUE TITLE
[factory plug-in] Annoying popup "clone projects"

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#11838]
### Description
Each time I open a workspace, I got a popup about "Git projects cloned"
but I'm just reopening an existing workspace, project is already there

I also receive this notification even when there is no project defined in my workspace.

![image](https://user-images.githubusercontent.com/436777/48005988-18b6dc00-e115-11e8-8b29-384ae26c4d4e.png)

### Reproduction Steps

Create a workspace on che.openshift.io with Che7 workspace

cc @sunix

**Comment by gorkem** [comment]
Also there is no indication that a clone operation has started. Can we add some sort of progress indicator to cloning?

**Comment by benoitf** [comment]
@gorkem plug-in can't use progress indicator for now
PR providing that is on hold https://github.com/theia-ide/theia/pull/2979
