### ISSUE TITLE
[factory plug-in] Duplicates of clone operation

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#11837]
### Description
When using a factory, I received a clone failure as it seems two clones operations are triggered
- one for the missing project in /projects directory
- one for the import flow of factory where it clones the projects.
![factory-import](https://user-images.githubusercontent.com/436777/48005650-3cc5ed80-e114-11e8-80ac-d8a888f981ea.gif)

### Reproduction Steps
https://che.openshift.io/f?id=factoryq53top82edduxmct

cc @sunix

**Comment by sunix** [comment]
OK I could not reproduce the error but there is definitely an issue with timing: workspace clone should be run after factories actions.
I suspect things to happen asynchronously :(
