### ISSUE TITLE
`che.limits` properties are not ignored on the multiuser environment.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#11843]
### Description

`che.limits` properties are ignored on the multiuser environment.
 I've not checked on the another env.

### Reproduction Steps

1. Spawn `che-server` with multiuser settings
2. Call `https://{che-server}/api/resource/:id`

**OS and version:**    

Eclipse Che 6.14.0-SNAPSHOT / nightly build.

**Diagnostics:** 

The part of `deployment/che`.

```
    - name: CHE_LIMITS_USER_WORKSPACE_COUNT
      value: "3"
    - name: CHE_LIMITS_USER_WORKSPACE_RUN_COUNT
      value: "1"
    - name: CHE_LIMITS_USER_WORKSPACE_RAM
      value: 4gb
    - name: CHE_LIMITS_ORGANIZATION_WORKSPACE_COUNT
      value: "3"
    - name: CHE_LIMITS_ORGANIZATION_WORKSPACE_RUN_COUNT
      value: "1"
    - name: CHE_LIMITS_ORGANIZATION_WORKSPACE_RAM
      value: 4gb
    - name: CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT
      value: "15"
```

The body of `https://{che-server}/api/resource/63ce8604-2eb5-46b0-b41e-xxxx`

```
[
  {
    "unit": "item",
    "amount": 3,
    "type": "workspace"
  },
  {
    "unit": "item",
    "amount": -1,
    "type": "runtime"
  },
  {
    "unit": "minute",
    "amount": 0,
    "type": "timeout"
  },
  {
    "unit": "mb",
    "amount": -1,
    "type": "RAM"
  }
]
```

**Comment by skabashnyuk** [comment]
>properties are not ignored 

Is this statement correct?

**Comment by monaka** [comment]
incorrect... edited.

**Comment by sleshchenko** [comment]
From what I see env variables names have typo: `workspace` -> `workspaces`. See names in [DefaultUserResourcesProvider](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/multiuser/personal-account/src/main/java/org/eclipse/che/multiuser/api/account/personal/DefaultUserResourcesProvider.java#L38.)
`CHE_LIMITS_USER_WORKSPACE_COUNT`, `CHE_LIMITS_USER_WORKSPACE_RUN_COUNT`, `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT`, `CHE_LIMITS_ORGANIZATION_WORKSPACE_COUNT` - should work fine.
But note that `CHE_LIMITS_USER_WORKSPACE_RAM` and `CHE_LIMITS_ORGANIZATION_WORKSPACE_RAM` don't work correctly with Che 7. The corresponding is registered here https://github.com/eclipse/che/issues/11424

**Comment by sleshchenko** [comment]
@monaka Feel free to reopen issue if changing the corresponding env var does not influence Resource API

**Comment by monaka** [comment]
@sleshchenko @skabashnyuk Thanks for your response. I see I have two mistakes. Not `USER_WORKSPACE` but `USER_WORKSPACES`. And the unit of `TIMEOUT` is millisecond, not second. I checked work fine after fixing them.

**Comment by monaka** [comment]
BTW, are some documents incorrect?  "[minutes](https://github.com/eclipse/che-docs/blame/50e4a878189b93a9eb5fd81716b14baaa02f1832/src/main/pages/user-management/resource-management.adoc#L76)" should be `millisecond`.
And I couldn't find any code for "[By default, this value is set to 3600000 (1 hour)](https://github.com/eclipse/che-docs/blame/master/src/main/pages/setup-docker/docker-config.adoc#L131)"

**Comment by skabashnyuk** [comment]
From what I can see from https://github.com/eclipse/che/search?q=che.limits.workspace.idle.timeout&unscoped_q=che.limits.workspace.idle.timeout @monaka  you are right. @sleshchenko can you confirm?

**Comment by sleshchenko** [comment]
> BTW, are some documents incorrect? "minutes" should be millisecond.

You're right, "minutes" should be milliseconds. Thanks for creating a corresponding PR.

> And I couldn't find any code for "By default, this value is set to 3600000 (1 hour)"

Good catch. It is an outdated comment and `-1` is set by default.
https://github.com/eclipse/che/blob/534a961e844049d5b4b84dd694176175eb367c97/dockerfiles/init/manifests/che.env#L668
It would be kind from your side to fix this part of doc as well or I can do it.

**Comment by monaka** [comment]
@sleshchenko 
> It is an outdated comment and -1 is set by default.

I think the default value is `0` since ...

At the first, `CHE_LIMIT_WORKSPACE_IDLE_TIMEOUT` will be converted the property `che.limit.workspace.idle.timeout`.
Second, the injected variable by `@Named(che.limited.workspace.idle.timeout)` has 0 as the default value.
