### ISSUE TITLE
Theia is not showing git status annotations in the project explorer. Nor unstaged files in Git panel on OSIO

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#11858]
### Description
Git status is failing. Annotations on the project explorer do not appear. Unstaged modified files are not poping up in the git panel. 
```
root ERROR The command `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 129. The caller should either handle this error, or expect that exit code.
root ERROR error: option `porcelain' takes no value
usage: git status [<options>] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns
```
### Reproduction Steps

1. Clone any project from git repo.
2. Make any modification on any file
3. Open `Git` left panel
4. Click on refresh button on that panel

- The file is supposed to appear in the panel as a modified file
- Annotations should appear in the project explorer

You see exception provided above in Theia machine logs

Expected:
![image pasted at 2018-11-6 16-28](https://user-images.githubusercontent.com/650571/48145653-97e21680-e2b3-11e8-9051-f4bfd29970a3.png)

Current:
![image pasted at 2018-11-6 16-29](https://user-images.githubusercontent.com/650571/48145682-a4666f00-e2b3-11e8-979b-275173d9a28d.png)

**OS and version:**    
che.openshift.io

**Diagnostics:**

**Comment by sunix** [comment]
Could you describe the problem from the user perspective (what is expected, what is happening) ?
