### ISSUE TITLE
workspace won't stop when idle.timeout = 1

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#11853]
### Description

The value of CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT is [converted from millisecond to minutes](https://github.com/eclipse/che/blob/b8576d956ccbb0e5999d73d4a13dbe01d6a5728f/multiuser/personal-account/src/main/java/org/eclipse/che/multiuser/api/account/personal/DefaultUserResourcesProvider.java#L50).
So small timeout values will be converted to 0.
At the same time, 'timeout == 0' means ["workspaces will not be stopped automatically"](https://github.com/eclipse/che-docs/blame/d908163122e29a322eef4641f738c36dc5318819/src/main/pages/setup-docker/docker-config.adoc#L131)

So the workspace won't stop.

### Reproduction Steps

Run che-server with `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT=1` (or smaller than 1 minutes).

**Comment by skabashnyuk** [comment]
1 millisecond or 1 minute is kind of interesting from the scientific point of view. I would say all values less than 5 minutes should mean that idling is disabled.

**Comment by sleshchenko** [comment]
@monaka Thanks for reporting it.

> 1 millisecond or 1 minute is kind of interesting from the scientific point of view. I would say all values less than 5 minutes should mean that idling is disabled.

I agree that 1 millisecond timeout is not a case and I see two issues here:
1. `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT` configuration env var is not self-explained and it is not clear that value should be set in milliseconds.
2. Che Server might throw configuration exception if a value is not big enough. Also, there might be check that configurated value will work correctly with the configured period of `che.workspace.activity_check_scheduler_period_s`. Now default value for  `che.workspace.activity_check_scheduler_period_s` is 60 seconds, so idle timeout less than 1 minute will work incorrect.

**Comment by monaka** [comment]
@skabashnyuk I agree that it should be rejected small timeout values. In addition, it's better to show a warning/error message to logs.

In my case, I believed the unit of `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT` is `minute`.
Similar cases won't be reproduced since the doc was [fixed](https://github.com/eclipse/che-docs/pull/564)

**Comment by monaka** [comment]
I close this issue as #11878 was merged. Thanks for your powerful works.
