### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:analyze-only (analyze) on project plugin-spell-ls: Dependency problems found

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#11854]
### Description

I want to create a plugin to run the installer module.

![plugin](https://user-images.githubusercontent.com/34393074/48114225-3c4c6480-e284-11e8-9069-557f8325fe57.PNG)

[SpellingModule.txt](https://github.com/eclipse/che/files/2556270/SpellingModule.txt)
[SpellingLanguageServerConfig.txt](https://github.com/eclipse/che/files/2556271/SpellingLanguageServerConfig.txt)

When i build the module it gives this error.

**OS and version:**   Windows 10

**Diagnostics:** 
`dependency:analyze -Dlicense.skip=true`
[dependencyAnalysis.txt](https://github.com/eclipse/che/files/2556281/dependencyAnalysis.txt)

`dependency:tree`
[dependencyTree.txt](https://github.com/eclipse/che/files/2556283/dependencyTree.txt)

**Comment by eivantsov** [comment]
Can you share detailed maven build output?

**Comment by LahiruT94** [comment]
[Log.txt](https://github.com/eclipse/che/files/2556520/Log.txt)
Maven build output
