### ISSUE TITLE
Errors in log when importing fuse-financial-cicd project

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11869]
### Description
tried with Che 6 nightly
imported https://github.com/jbossdemocentral/fuse-financial-cicd

led to these errors in dev-machine log

![image](https://user-images.githubusercontent.com/1105127/48194335-032bf700-e34d-11e8-8a87-3a6839adb843.png)

### Reproduction Steps

- create Workspace using java stack
- click on "import project..."
- use https://github.com/jbossdemocentral/fuse-financial-cicd as project to import

**OS and version:**    

**Diagnostics:**

**Comment by tsmaeder** [comment]
@apupier is this reproducible?

**Comment by apupier** [comment]
@tsmaeder I tried 2 times and it occured 2 times
