### ISSUE TITLE
Quick Tips for Creating a Wizard

### ISSUE THREAD

**Issue by stephanfr** [eclipse-che/che#1186]
I have looked over the Java Wizard and a couple of older wizards from the Codenvy github repository but I have not been able to find a concise description of how to create and then add a wizard to Che.  There is a brief page on writing wizards in the V1.0 documentation but I cannot find references to wizards in the latest docs.  Is it there and I am simply missing it?

I would like to create a new project type and have the wizard popped on creation to walk the user through filling out an initial project skeleton.

I can follow the example of the Java Wizard, but would like to limit my flailing if possible.  If there a document that describes how to bind a wizard into a new project definition, that would be very helpful.  Barring that, could someone provide a bit advice or a quick outline of steps to follow?

Thanks,

Stephan

**Comment by TylerJewell** [comment]
@slemeur -- Is this part of the Plugin Resource Center work that is currently under way?  @stephanfr - we are working with a partner to create a long list of examples and tutorials around techniques for extending Eclipse Che.  I believe we'll have a draft in a couple weeks and first publication by the end of the month.  There is a wide range of items covered in the resource center, so am curious if the wizard is an area that is discussed.

@vinokurig, @vparfonov Igor, Vitalii - you are the primary architects around Che's wizard tooling.  So perhaps you have something additional to add.

**Comment by TylerJewell** [comment]
Here is a sample that:
1. Is a complete Che custom assembly.  This is a stand alone IDE that you can build which includes this extension.
2. Declares a new project type for a programming language called "x" and gives it a pretty name of "Sample Project Type".
3. Includes a sample action that is invoked from within the help menu.
4. Includes a wizard that adds a compiler version property.

```
git clone http://github.com/vparfonov/plugin-sample-wizard
mvn clean install
## Your assembly will be in \assembly\assembly-main\target.
## Run Che normally
```

STEP 1: Defining new project type.
https://github.com/vparfonov/plugin-sample-wizard/blob/master/che-plugin-sample-wizard-server/src/main/java/org/eclipse/che/plugin/sample/wizard/projecttype/SampleProjectType.java

STEP 2: Register the project type on the server side through Guice injection
here we register it https://github.com/vparfonov/plugin-sample-wizard/blob/master/che-plugin-sample-wizard-server/src/main/java/org/eclipse/che/plugin/sample/wizard/inject/SampleWizardModule.java#L26

STEP 3: Create a simple action which uses notification API
https://github.com/vparfonov/plugin-sample-wizard/blob/master/che-plugin-sample-wizard-ide/src/main/java/org/eclipse/che/plugin/sample/wizard/ide/action/SampleAction.java

STEP 4: Register this action within the extension to the help menu
https://github.com/vparfonov/plugin-sample-wizard/blob/master/che-plugin-sample-wizard-ide/src/main/java/org/eclipse/che/plugin/sample/wizard/ide/SampleWizardExtension.java#L42

STEP 5: Create the UI for the wizard (view and presenter), and have it registered into the wizard registry. 
https://github.com/vparfonov/plugin-sample-wizard/tree/master/che-plugin-sample-wizard-ide/src/main/java/org/eclipse/che/plugin/sample/wizard/ide/wizard 

SamplePageView.java - interface of wizard page
SamplePageViewImpl.java - impl of the wizard page 
SamplePageViewImpl.ui.xml - UI Declaration of wizard page
SamplePagePresenter.java - logic of wizard page
SampleWizardRegistrar - class that register new wizard

STEP 6: Use GIN injection to register the new wizard
https://github.com/vparfonov/plugin-sample-wizard/blob/master/che-plugin-sample-wizard-ide/src/main/java/org/eclipse/che/plugin/sample/wizard/ide/inject/SampleWizardGinModule.java

**Comment by wn092943** [comment]
@TylerJewell 
hi,you mentioned that your team are creating a long list of examples and tutorials in your comment. I want to know whether these docs have been published.

**Comment by TylerJewell** [comment]
@wn092943 - the new plugin resource center has been published in the Che docs.
