### ISSUE TITLE
Make it possible to specify path for command execution in its configuration

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#11866]
### Description
To make command execution more flexible and compatible with new `devfile` feature, it is proposed to add possibility to specify the path inside machine where the command should be executed.
It can be passed through the `workingDir` attribute of the command. 
Example:
```
{ 
 "commandLine": "mvn clean install", 
  "name": "console-java-simple:build", 
  "attributes": { 
        "goal": "Build", 
        "machineName": "dev-machine", 
  >>>>>>"workingDir": "/projects/console-java-simple"
    }
}
```

**Comment by garagatyi** [comment]
In Che 7 use-case machine name is controlled by a plugin author and Che master code. So, it is subject to change without user awareness. And if this happens a command would not work.

**Comment by AndrienkoAleksandr** [comment]
Blocked https://github.com/kubernetes/kubernetes/issues/71350#issuecomment-441804368

**Comment by AndrienkoAleksandr** [comment]
Blocked by https://github.com/kubernetes/kubernetes/issues/71350

**Comment by l0rd** [comment]
Can't we just `cd <working-dir>; <command>`

**Comment by l0rd** [comment]
@AndrienkoAleksandr ^^ ?

**Comment by AndrienkoAleksandr** [comment]
> Can't we just `cd <working-dir>; <command>`?
Yes, we can do it like workaround.

**Comment by l0rd** [comment]
> Yes, we can do it like workaround.

Ok let's start with that because I am afraid it will take years to have a patch on Kubernetes

**Comment by sleshchenko** [comment]
@AndrienkoAleksandr Looks like exec sidecar respects `workingDir` in command attributes, does not matter with a workaround (cd workindDir && ...), right?
If yes, then can we close this issue?

**Comment by skabashnyuk** [comment]
@AndrienkoAleksandr wdyt ??
