### ISSUE TITLE
Change Che master Java from JRE to JDK 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11872]
### Description
Now we use JRE and it doesn't provide tools to analyze the weird behavior of JVM: jps, jstack, etc.
JDK has these tools and would be valuable in the image.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
-1 - IP issues to do that I think.
AFAIK there was a concrete reason why Eclipse IP team asked  @TylerJewell  to do that.

**Comment by skabashnyuk** [comment]
AFAIK it's not an issue for osio since che-master repackaged there with JDK

**Comment by garagatyi** [comment]
@skabashnyuk do you mean that we had issues with the Oracle JDK or Open JDK?

**Comment by skabashnyuk** [comment]
Afaik both. @riuvshin maybe you remember some details?

**Comment by riuvshin** [comment]
I do not remember details but OpenJDK was the problem. (OracleJDK we are not even discussing here)
I think you are looking for proper JVM monitoring instead of doing manual analysis on prod inside a pod/container.

**Comment by garagatyi** [comment]
Now there is no way to analyze upstream Che thread dump or heap at all. Having proper monitoring is great but we are not yet and I'm not sure when we would be there (at least being able to do what JDK tools do).

**Comment by skabashnyuk** [comment]
why don't you run Che with custom che server image?

**Comment by garagatyi** [comment]
Because I never know beforehand when Che would get a weird state that worth investigation

**Comment by skabashnyuk** [comment]
doubt that we have a way to fix this

**Comment by skabashnyuk** [comment]
From what I've studied there is no legal requirement from Eclipse IP to not to use JDK.

**Comment by garagatyi** [comment]
@skabashnyuk thanks for addressing this issue!
