### ISSUE TITLE
How to deploy Che to google cloud?

### ISSUE THREAD

**Issue by ukman** [eclipse-che/che#1187]
Hi, 
Tyler Jewell asked me to write my question here (not in google group)

I'm trying to deploy Eclipse Che to my Google Cloud Container Engine.
I did the following
1. Pulled codeenvy/che image from repo to my local docker.
2. Tagged the image with new name
3. Pushed the image to google cloud Container Registry
4. Created cluster
5. Started image on cluster 
   `kubectl run che --image=gcr.io/my-project/che --port=8080`
6. Exposed it
   `kubectl expose deployment che --type="LoadBalancer"`

After that I got logs from the pod
`kubectl logs che-9999999-xxxxxx`
And I see the following

```
!!!
!!! Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon.
!!!
```

So It does not work.
What am I doing wrong?

**Comment by ghost** [comment]
If you want to run Che as a docker container there are a number of must have things:
1. Make sure docker can run either inside a container or Docker in the container actually calls Docker on the host. You may want to take a look at https://eclipse-che.readme.io/docs/usage-docker#using-docker-syntax. We recommend either mounting `/var/run/docker.sock` or exporting DOCKER_HOST env variable to point to a host IP where Docker listens over tcp. There are also other maust have mounts. You will find details in docs.
2. Ports. Even if the container has started and Che run successfully, you need to make sure that you can reach workspace ports from your browser (so inbound connections for a workspace container on an ephemeral port range should be allowed).

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
