### ISSUE TITLE
Add an Ansible Stack

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#11877]
### Description
Ansible Stack with YAML, Ansible-Review, Ansible-Lint

**Comment by victorock** [comment]
@slemeur Any updates on this?

**Comment by slemeur** [comment]
That is not something we have prioritized right now. (Probably post Che 7 GA)

With Che 7, the stacks are revisisted and getting much simpler to create. If you have a container with ansible-review and ansible-lint integrated, it's completely possible create a stack which will provide those tools + the appropriated language server.

We are writing documentation on how to create those new Che 7 stacks, but if you are interested, it is something we can explore together.

**Comment by victorock** [comment]
Absolutely @slemeur, just let me know how i can help.
I already have a "ansible developper" container image.

**Comment by slemeur** [comment]
Wonderful.
I added that into the scope of Che 7 GA - I think it would be very interesting if you can contribute that with some help from @tsmaeder 's team.

Creating a devfile would be the initial way to move forward:  https://redhat-developer.github.io/devfile/ 
We are still working on the documentation, but feel free to ping @mshaposhnik or @sleshchenko.

**Comment by victorock** [comment]
i have a container for it, using theia-runtime, doing some tests now...
i'd prefer to have a UBI base image...

**Comment by slemeur** [comment]
Sounds good @victorock ! In this case, I'll add the label `7.1.0`, as it seems you would be able to provide a PR after `7.0.0` release.
Would be ideal to add the stack to the default stacks (devfile registry: https://github.com/eclipse/che-devfile-registry)

**Comment by sunix** [comment]
We have a draft plugin + devfile here: https://github.com/sunix/che-ansible

**Comment by sympatheticmoose** [comment]
Additionally for consideration is the new [Ansible extension](https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible) for VS Code
