### ISSUE TITLE
Support copy of text from terminal via classical shortcut 'Ctrl+C'

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11881]
### Description
the text which is in terminal/output views cannot be copied. it would be nice to be able to copy it. It will ease issue reporting for instance

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by apupier** [comment]
> does `Ctrl + Insert` work?

yes it is. First time that I heard about this shortcut to copy-paste.
Updating title then

**Comment by skabashnyuk** [comment]
@AndrienkoAleksandr can you comment? @ashumilova @evidolob  wdyt?

**Comment by AndrienkoAleksandr** [comment]
@apupier Do you mean Ctrl +C does not work for Che 7 workspace with Theia?

**Comment by AndrienkoAleksandr** [comment]
@apupier For CHE 6 'Ctrl + C' should work. For Theia such ability was applied too, but since version 0.3.17.

**Comment by gorkem** [comment]
closing since this does not seem to be valid
