### ISSUE TITLE
When selecting several folder and try to convert to "Project", only the one right-clicked is converted

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#11880]
### Description
When several folder are selected and right-click on them I would expect to have all of them considered for the action

### Reproduction Steps
- have several folders
- select several tof them (with ctrl+click for instance)
- right-click on one of them
- "Convert to project"
--> only the the folder below cursor at the right-click moment is converted

**OS and version:**    
Che 6.13.1

**Diagnostics:**

**Comment by SkorikSergey** [comment]
Similar issue - https://github.com/eclipse/che/issues/2913.

**Comment by apupier** [comment]
closing as duplicated
