### ISSUE TITLE
About SSO using login authentication of Eclipse Che

### ISSUE THREAD

**Issue by ktdjun** [eclipse-che/che#11884]
Using Eclipse Che's login authentication, launched on Che's Workspace
I would like to apply single sign-on to access applications.

I made the following correspondence to the application I am creating.

  1. In the application's source code, define the following script.
```
    <script src="http://{hostname}:5050/auth/js/keycloak.js"></script>
    <script>
       var keycloak = Keycloak();
        keycloak.init({ onLoad: 'login-required',checkLoginIframe: false })
        .success(function(authenticated) {
          alert(authenticated ? 'authenticated' : 'not authenticated');
        }).error(function() {
          alert('failed to initialize');
        });
    </script>
```
  2. Set the following parameters in keycloak.json.
```
  {
    "realm": "che",
    "auth-server-url": "http://{hostname}:5050/auth",
    "resource": "che-public"
  }
```

With the above settings, single sign-on could be realized, but there are issues such as Eclipse Che's environment-dependent settings are included.
If you have a good solution please advise on the following points.

a) The value of the above {hostname} varies depending on the Eclipse Che environmental establishment.
    I want to make environment independent setting, how does Eclipse Che set the URL of Keycloak?

b) In order to perform single sign-on with the setting of 1 and 2 above, it was necessary to add the URL that published the application to "Web Origins" in the settings of Keycloak's Clients (che-public) .

    Ex.) http://{hostname}:33119

However, because it is an application running on Workspace, the port number will be changed when the Workspace container is restarted.
Is there a way to deal with not changing the port number?

c) Under the above settings 1 and 2, if you describe a path after "http: // {hostname}: 33119", the login screen will not be displayed.
    Eclipse Che always makes a transition to the login screen if I am not logged in, but how do you set it?

**Comment by skabashnyuk** [comment]
Che version?

**Comment by ktdjun** [comment]
@skabashnyuk 
I'm sorry,
The Eclipse Che version uses 6.8.0.

**Comment by skabashnyuk** [comment]
Please upgrade to 6.13 or above. I think https://github.com/eclipse/che/pull/11090 this may help you.

**Comment by ktdjun** [comment]
@skabashnyuk 
Thank you for your response.

I will try it with Eclipse Che 6.13 or higher. I will also confirm the description in # 11090.
For now, I will close the issue.

**Comment by ktdjun** [comment]
I upgraded Che to 6.14.1.
I checked #11090  and tried setting che.keycloak.use_fixed_redirect_urls, but I need to prepare my own OIDC Provider.

If possible I am looking for ways to make use of the keycloak configuration standardized by Eclipse Che as it is.
However, the following problems can not be solved.

*  Every time the workspace is restarted, I need to add the setting to Keycloak's Web Origin. Specifically, it is as follows.
![problem](https://user-images.githubusercontent.com/36942369/49853845-cc556f00-fe2b-11e8-96d1-018515bb666d.png)

I only want to realize this with just setting once.
Is there a way to solve this problem with Eclipse Che's feature?

**Comment by skabashnyuk** [comment]
@ktdjun can you clearly define what issue do you have?
>Every time the workspace is restarted, I need to add the setting to Keycloak's Web Origin. 

I'm not sure I follow you. Why you need that?

**Comment by ktdjun** [comment]
@skabashnyuk  Thank you for your reply.

First of all, what I want to realize is as follows.
* I want to restrict access to an application running on Workspace only to the person who logged into Workspace.

This is because I do not want other users to see the product being developed.
Because of the configuration of the network that I use, I can not control access by IP address and it will be visible to unrelated people.

The problem I am having happens when Keycloak's administrator and the user accessing Workspace are different.
The setting to Keycloak should be done by the keycloak administrator.
Keycloak's administrator can not determine when Workspace users will restart Workspace, so we need to generalize Keycloak settings.
However, as described above, my problem is that it is impossible to generalize the setting with Ephemeral port.

I'd be very grateful if you could give me your opinion.
