### ISSUE TITLE
Change setting of openshift creds in tests

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#11885]
### Description
It is not clear that openshift credentials like OPENSHIFT_USERNAME and OPENSHIFT_PASSWORD need to be set as envitonment variables.
While ADMIN and TESTUSER credentials are set via VM parameters (e.g. -Dche.testuser.username), it would be nice to have this option for openshift credentials as well.

**Comment by rhopp** [comment]
@Katka92 I guess we can close this one, right? If you disagree, please reopen.
