### ISSUE TITLE
Python project syntax error (python 2.x vs 3.x)

### ISSUE THREAD

**Issue by timfreund** [eclipse-che/che#11891]
### Description

Che ships with a Python stack that includes Python 3.5.1 and pip 8.1.1, but the default Python content for new projects uses the Python 2.x print statement.

### Reproduction Steps

1. Install Che (I have installed via docker and from source)
2. Create a new Python workspace from the Quick Start list
3. Create a new Python project within the workspace.
4. Open main.py
5. Notice the syntax error on line 1

**OS and version:** Ubuntu 18.04

**Diagnostics:** 

I've found the source file, signed the CLA, and will submit a PR to the project to fix this issue.

**Comment by eivantsov** [comment]
Merged. @timfreund thanks
