### ISSUE TITLE
depency problem

### ISSUE THREAD

**Issue by irwinai** [eclipse-che/che#119]
$ mvn clean install
[INFO] Scanning for projects...
Downloading: http://192.168.11.201:8081/nexus/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/4.0.0-M5-SNAPSHOT/maven-metadata.xml
Downloading: http://192.168.11.201:8081/nexus/content/groups/public/org/eclipse/che/depmgt/maven-depmgt-pom/4.0.0-M5-SNAPSHOT/maven-depmgt-pom-4.0.0-M5-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.eclipse.che.sdk:che-sdk-parent:4.0.0-M5-SNAPSHOT: Could not find artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:4.0.0-M5-SNAPSHOT in nexus-osc (http://192.168.11.201:8081/nexus/content/groups/public) and 'parent.relativePath' points at wrong local POM @ org.eclipse.che.sdk:che-sdk-parent:4.0.0-M5-SNAPSHOT, D:\develop\che\pom.xml, line 16, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.eclipse.che.sdk:assembly-sdk:[unknown-version](D:developcheassembly-sdkpom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.che.sdk:che-sdk-parent:4.0.0-M5-SNAPSHOT: Could not find artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:4.0.0-M5-SNAPSHOT in nexus-osc (http://192.168.11.201:8081/nexus/content/groups/public) and 'parent.relativePath' points at wrong local POM @ org.eclipse.che.sdk:che-sdk-parent:4.0.0-M5-SNAPSHOT, D:\develop\che\pom.xml, line 16, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by TylerJewell** [comment]
Can you let us know the OS you built, the repository you build from, and
the branch selected?

Also - what is your JDK & maven version.

I just did a checkout & build of 4.0 branch and it was successful.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by kkmohanta** [comment]
i did as said in https://www.eclipse.org/che/

git clone https://github.com/codenvy/che 
 git checkout 4.0 
 cd assembly-sdk
 mvn clean install

but its causing error:-

![cheproblem](https://cloud.githubusercontent.com/assets/7828739/11761845/696fe142-a0f8-11e5-85df-40c020a6a0b7.PNG)

My os= windows 10.
branch is 4.0 [i think //i m new to open source]

java version "1.8.0_65"
Apache Maven 3.3.9

**Comment by benoitf** [comment]
I would say jdk is required while you've a jre

**Comment by kkmohanta** [comment]
oh......thanks a lot sir for replying.....working on getting jdk.
