### ISSUE TITLE
Create a JSON-schema for the Devfile 

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11904]
### Description
Create a JSON-schema for the Devfile.
It's a well-known standard for defining data formats. It will help with the discussion and allows to generate doc and API source code too.

**Comment by l0rd** [comment]
@sleshchenko I have moved devfile to https://github.com/redhat-developer/devfile

**Comment by mshaposhnik** [comment]
Json validation library research:
1) Officially recommended, supports latest draft, but requires external repo set-up: https://github.com/everit-org/json-schema 
2) Popular one, a continuation of popular fge library https://github.com/java-json-tools/json-schema-validator 
3) Good one, but only draft v.4 support now (planned to update soon) https://github.com/networknt/json-schema-validator


Unfortunately, none of them supports validating yaml directly. So for phase 1 we can convert incoming yaml to JSON before validation.

**Comment by mshaposhnik** [comment]
The best way to generate POJO from schema is seems to be https://github.com/joelittlejohn/jsonschema2pojo library. We shall review it and start a CQ process if we found it acceptable for us.

**Comment by mshaposhnik** [comment]
Will be closed together with merge of https://github.com/eclipse/che/pull/11998
