### ISSUE TITLE
Fix rename operation availability for golang language server

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#11907]
According to this issue https://github.com/eclipse/che/issues/10524 currently we are unable to provide a proper fix for golang rename operation, so probably it would be okay to disable the rename operation for golang language server until the solution is found.

FYI @dmytro-ndp

**Comment by slemeur** [comment]
ok for me

**Comment by vzhukovskii** [comment]
@dmytro-ndp https://github.com/eclipse/che/issues/12106
