### ISSUE TITLE
Installing language server as a installer into eclipse che

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#11917]
### Description
I created a language server installer. 

![installers](https://user-images.githubusercontent.com/34393074/48394524-eb33e900-e739-11e8-9036-aa4a3eb8d099.png)

Folder structure

![folderstructure](https://user-images.githubusercontent.com/34393074/48394556-fa1a9b80-e739-11e8-815b-18dd005a6574.PNG)

When the workspace is starting it gives this error

![error](https://user-images.githubusercontent.com/34393074/48394577-0f8fc580-e73a-11e8-8186-123be2b4c5d4.PNG)

Script file:
[org.eclipse.che.ls.mydsl.script.sh.txt](https://github.com/eclipse/che/files/2574864/org.eclipse.che.ls.mydsl.script.sh.txt)

Json:
`{
  "id": "org.eclipse.che.ls.mydsl",
  "version": "1.0.1",
  "name": "MyDsl (Xtext) language server",
  "description": "MyDsl (Xtext) language server",
  "dependencies": [],
  "properties": {}
}`
### Reproduction Steps
1. clone che master
2. create a moudle in the agents
3. create the folder strcture and the files
4. build and run

**OS and version:**    Windows 10

**Comment by eivantsov** [comment]
```
if [ ! -f ${LS_DIR}run ]; then
    echo Downloading MYDSL language server
    curl -s -L -o ${LS_DIR}mydsl.tar  ${AGENT_BINARIES_URI}
    cd ${LS_DIR} && tar -xzf mydsl.tar
fi
```
Aren't you missing `/` in paths? In other parts of the script as well.

**Comment by LahiruT94** [comment]
I'm sorry I didn't catch that, / in paths means? If you can illustrate one, it is a great help.

**Comment by LahiruT94** [comment]
I corrected `/` that and ran it again with the above command. It gives this error `ERROR: (che start): Timeout waiting for server. Run "docker logs che" to inspect.`

This is the log
[log.txt](https://github.com/eclipse/che/files/2623517/log.txt)

**Comment by eivantsov** [comment]
@LahiruT94 I recommend to start Che with a clean local storage.

**Comment by LahiruT94** [comment]
I did and it builds, then when i start the workspace it gives this error.

![insidelog](https://user-images.githubusercontent.com/34393074/49210853-27c33e00-f3e4-11e8-93cd-a325b0fc00b5.PNG)

Complete log
[log2.txt](https://github.com/eclipse/che/files/2628339/log2.txt)

Script file
[script.txt](https://github.com/eclipse/che/files/2628345/script.txt)

**Comment by eivantsov** [comment]
Just try to start a workspace without this installer, and then manually execute a script in the workspace. It looks like your script is broken
