### ISSUE TITLE
Tracing workspace related operation

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11922]
### Description
 - [x] workspace creation
 - [x] workspace start 
 - [x] trace workspace deletion
 - [x]   trace volume claim attachment 
 - [x]  trace creation of che plugins -> moved to  https://github.com/eclipse/che/issues/12003
 - [x]  define meaningful set of tags to apply to the traces. (Postponed)
 - [x]  review https://github.com/eclipse/che/pull/11920 maybe we need some traces here

**Comment by metlos** [comment]
I've opened https://github.com/eclipse/che/pull/11924 to start the review of and discussion about the implementation details.

**Comment by metlos** [comment]
Done through PR #11924
