### ISSUE TITLE
[Regression] File Structure feature doesn't work

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#11927]
**Reproduction Steps:**
1. Create and start workspace through **Dashboard** based on **Java** stack.
2. Open any java class in the **Editor**.
3. Start 'File Structure' feature from menu - **Assistant** -> **Navigate File Structure**.

**Expected result:**
**File Structure** widget is visible.

**Actual result:**
Nothing happened. 

This issues started to reproduce from 052f719c64556e3b1f63b0570d79aa9aeadecc76 commit(https://github.com/eclipse/che/pull/11898).

**Failed selenium tests:** FileStructureBaseOperationTest, FileStructureByKeyboardTest, FileStructureCodeEditorTest, FileStructureNodesTest.
 
**Che version**: 6.14.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
![screencast-172 19 20 234-8080-2018 11 14-10-08-16](https://user-images.githubusercontent.com/7760565/48468716-5393d080-e7f5-11e8-8bcf-268124ada45e.gif)

**Screenshot:**
![selection_155](https://user-images.githubusercontent.com/7760565/48469546-d61d8f80-e7f7-11e8-8c88-756959bb95f2.png)

**Comment by RomanNikitenko** [comment]
As I can see we have NPE [here](https://github.com/eclipse/che/blob/052f719c64556e3b1f63b0570d79aa9aeadecc76/plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/util/SymbolIcons.java#L89)
![file_structure](https://user-images.githubusercontent.com/5676062/48472675-6f03d900-e7ff-11e8-8b2f-9154b153bf2d.gif)

**Comment by vzhukovskii** [comment]
This regression blocks investigation of https://github.com/eclipse/che/issues/8300

**Comment by vzhukovskii** [comment]
This issue will be resolved after https://github.com/eclipse/che/pull/11941 merge.

**Comment by SkorikSergey** [comment]
Fixed.
