### ISSUE TITLE
Tracing operation made over JSON-RPC

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11923]
### Description
Quite a lot of operation are made over JSON-RPC. We would like to track them too.

**Comment by garagatyi** [comment]
I found [this](https://about.sourcegraph.com/go/gophercon-2018-from-prototype-to-production-lessons-from-building-and) article about Reddit's experience with Go interesting and it has a part that is interesting for this particular case. It describes their case with tracing/logging/metrics of RPC.
