### ISSUE TITLE
wsagent-debug unavailable on 6.14.0?

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#11928]
### Description
Hi,

I'm developing some modules on wsagent on my eclipse che fork. Yesterday I have updated my fork to 6.14.0 snapshot and I realized that the service which allows me to debug wsagent is not there anymore.

Here on 6.10.0:
https://ibb.co/dRzYfL

Then on 6.14.0 is missing:
https://ibb.co/d24MZf

Are you able to help me please?

**Comment by benoitf** [comment]
Hello, FYI https://github.com/eclipse/che-docs/blob/97a662cfff47401db40176ba220a4394f18c9be5/src/main/pages/developer-guide/workspace-agent.adoc

**Comment by sleshchenko** [comment]
Debugging of workspace agent debug is not the thing that should be enabled by default since there is no any authentication, it's why we disabled it in 6.14.0. 
@benoitf Shared Doc with instruction how to enable it. This doc will be available on https://www.eclipse.org/che/docs/ after next updating of the site, I hope soon.

**Comment by mstavares** [comment]
Hi @benoitf 

Should I enable it here?
wsagent/agent/target/classes/installers/1.0.1/org.eclipse.che.ws-agent.script.sh:279:DEFAULT_WSAGENT_DEBUG=false

**Comment by sleshchenko** [comment]
@mstavares https://github.com/eclipse/che-docs/blob/master/src/main/images/wsagent/wsagent-debug-env.png

**Comment by mstavares** [comment]
@sleshchenko thanks a lot!

**Comment by mstavares** [comment]
Is it possible to add this by default temporarily on my custom stack?

**Comment by sleshchenko** [comment]
> Is it possible to add this by default temporarily on my custom stack?
@mstavares Yes, it is to configure stack to enable wsagent debug by default. Just add needed env vars to a machine configuration.
Not sure that I understand what you do mean by `temporarily` here. You can configure your stack with Debug enabled by default, and then you can disable it. There is no functionality out of the box to `temporarily` configure your stack.

**Comment by mstavares** [comment]
@sleshchenko Maybe I'm doing something wrong, but after create those environment variables my workspace stucks at starting state.

https://ibb.co/mbS8VL

**Comment by sleshchenko** [comment]
@mstavares Try to remove `WSAGENT_DEBUG_SUSPEND` or set it to `n`. Docs shows just an example how to set env vars. Workspace stucks at starting state because wsagent waits until someone connects to debug port.

**Comment by mstavares** [comment]
It's already working, thanks a lot!

**Comment by sleshchenko** [comment]
Feel free to reopen it or create a new issue if you still have any issues/questions.
