### ISSUE TITLE
Pod won't create and fails with Pod creation timeout exceeded

### ISSUE THREAD

**Issue by harryk8sgit** [eclipse-che/che#11934]
### Description
I have deployed Eclipse Che on Kubernetes using Helm
Che server has started successfuly. And when i am trying create a workspace, the pod creation fails with error "Pod creation timeout exceeded. -id: workspace6p5cmqqx4ba1x5f1.dockerimage -message: null"
I have also tried running self diagnostics, which also fail during pod creation

### Reproduction Steps
Case 1:
Deployed Eclipse Che with the following command
helm install --name che --namespace che -f ./values/default-host.yaml ./ --debug

Where the values of default-host.yaml is as below

global:
  multiuser: false
  ingressDomain: 172.21.63.54
  serverStrategy: default-host
  
I have kept all other values unchanged in the Helm chart.

Here is the partial output of helm install:
NAME:   che
REVISION: 1
RELEASED: Wed Nov 14 17:50:19 2018
CHART: che-0.1.0
USER-SUPPLIED VALUES:
global:
  ingressDomain: 172.21.63.54
  multiuser: false
  serverStrategy: default-host

COMPUTED VALUES:
cheImage: eclipse/che-server:6.13.1
cheImagePullPolicy: Always
cheKeycloakClientId: che-public
cheKeycloakRealm: che
cheWorkspaceHttpProxy: ""
cheWorkspaceHttpsProxy: ""
cheWorkspaceNoProxy: ""
global:
  cheNamespace: ""
  cheWorkspaceServiceAccount: che-workspace
  cheWorkspacesNamespace: ""
  gitHubClientID: ""
  gitHubClientSecret: ""
  ingressAnnotationsPrefix: nginx.
  ingressDomain: 172.21.63.54
  log:
    appenderName: plaintext
    loggerConfig: ""
  multiuser: false
  pvcClaim: 1Gi
  serverStrategy: default-host
  tls:
    enabled: false
    secretName: che-tls
    useCertManager: true
    useStaging: true
  workspaceIdleTimeout: "-1"

I have created a new Workspace in the dashboard. And when i start the workspace, the error shows up.

Error: Failed to run the workspace: "Pod creation timeout exceeded. -id: workspace6p5cmqqx4ba1x5f1.dockerimage -message: null"

And the Kubernetes event have the entry
Error creating: pods "workspace6p5cmqqx4ba1x5f1.dockerimage-c86f795b-" is forbidden: error looking up service account workspace6p5cmqqx4ba1x5f1/che-workspace: serviceaccount "che-workspace" not found

As the per Readme, "che-workspace" service account will be created only when "cheWorkspacesNamespace" is non-empty
And, i have set "cheWorkspacesNamespace" as empty string(cheWorkspacesNamespace="").

So, in this case Kubernetes will not create the "che-workspace" service account and also should not lookup for "che-workspace" service account while creating pods.

Case 2:
I have created a namespace with name "wrk" and specified cheWorkspacesNamespace="wrk" and then deployed Eclipse Che.
In this case, the pod creation was successful.

**OS and version:**    
CentOS 7.
Eclipse Che version: 6.13.1

**Diagnostics:** 
[che-server.log](https://github.com/eclipse/che/files/2580760/che-server.log)

**Comment by sleshchenko** [comment]
@harryk8sgit Are you using helm chart from `6.13.1` tag or master branch?

**Comment by harryk8sgit** [comment]
> @harryk8sgit Are you using helm chart from `6.13.1` tag or master branch?
I have used helm chart of both 6.13.1 and master branches. And have observed the issue as reported.

Could you please provide me instructions if any additional debug options can be used to troubleshoot the issue?
