### ISSUE TITLE
Image for dev che-theia in che-theia should be the che-theia builder

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#11938]
Part of the goal  Che-Theia in Che-Theia
maybe without theia sources

**Comment by benoitf** [comment]
@sunix not on short term.
For now image is multi-staged build image and then, only production image is pushed

**Comment by AndrienkoAleksandr** [comment]
@benoitf I think You have already done this issue. So Could You closed it?

**Comment by benoitf** [comment]
@AndrienkoAleksandr you're correct, thx

**Comment by benoitf** [comment]
Fixed by https://github.com/eclipse/che/pull/12171
