### ISSUE TITLE
Kubernetes and Che

### ISSUE THREAD

**Issue by ukman** [eclipse-che/che#1193]
Is it possible to work with containers that work under kubernetes?

We want to use Google Cloud Container Engine so it uses kubernetes to access to containers (not Docker API).

Thanks

**Comment by garagatyi** [comment]
Hi. Right now kubernetes integration is not implemented.
But you can contribute such an integration to Che. We are open for different kinds of extension.
See the example of docker integration implementation https://github.com/eclipse/che/tree/master/plugins/plugin-docker/che-plugin-docker-machine

**Comment by wernight** [comment]
I'd suggest to use Docker for development and deploy on Kubernetes. The reason is that it allows reload (or even auto-reload) on file change which is only possible else if you're running Kubernetes on the same machine as the one you're coding or somehow mounting the volume with your source code.

**Comment by advoretsky** [comment]
If you work on a module that is part of complex assemble of microservices with lot of interconnections, you'd better to run app in kubernets cluster, not to emulate environment for it on local host and/or bare docker.

**Comment by TylerJewell** [comment]
We will be working to improve workspaces so that you can submit recipes that are dockerfiles, compose files, or other topological definitions.  By having support for a variety of topology definitions for multi-container constructs, we'll allow users to use their definitions in Che, and then they can push them out to other systems like Kubernetes.

**Comment by TylerJewell** [comment]
#1829 - crosslinking this issue, which is our vendor API that is under development that will allow for different orchestrators to be implemented under Che.

**Comment by gorkem** [comment]
This should be linked to #2847

**Comment by wernight** [comment]
I have it working under Kubernetes pretty decently https://github.com/wernight/kubernetes-che/

My only issue is that SPDY seems to disconnect WebSockets when not used for a while.
I think Che could ping to keep it alive, but another improvement would be to use another proxy, like nghttpx with Apache Traffic Server. The issue is that the later is pretty difficult to set up authentication while keeping any port pointing to Che.

**Comment by gorkem** [comment]
@wernight you may also try the [openshift branch](https://github.com/eclipse/che/tree/openshift-connector) which works with k8s/openshift APIs. We are yet to try it for k8s instances other than openshift but eventually we will get there.

**Comment by garagatyi** [comment]
@wernight 
> Long lived HTTP requests like the terminal, or possibly other parts, seem to disconnect after a while if there was no I/O.

Is already fixed :)

**Comment by wernight** [comment]
@gorkem How does it differ from the master branch? Actually the only real issue for having it work on Kubernetes is the [issue with the so many ports](https://github.com/eclipse/che/issues/1560)

**Comment by wernight** [comment]
@garagatyi Wow nice! In which release? I'm using 5.0.0-M6 which seems to be the latest but it's 5 months old.

**Comment by gorkem** [comment]
@wernight yes, openshift had the same issue see https://github.com/eclipse/che/commit/908a6e1700c76b887e0dd8154ffc87b3a37685ec. Also docker port is a privileged port so the branch reimplements all calls to docker with k8s ones.

**Comment by garagatyi** [comment]
@wernight in 5.6.0. Released today. 
5.0.0-M6 is quite old now.

**Comment by wernight** [comment]
@garagatyi I'll be watching https://hub.docker.com/r/codenvy/che-server/tags/ for this one.

@gorkem I see part of single port, but I don't see how that might work "magically" with k8s without actually fixing https://github.com/eclipse/che/issues/1560. If there is a dockerized version I may try it if I find issues with 5.6.0 (as I said 5.0.0 is working on Kubernetes).

**Comment by wernight** [comment]
@garagatyi It looks like `codenvy/che` and `codenvy/che-server` are not maintained anymore, but their README hasn't been updated on Docker Hub. I see 5.6.0 on `codenvy/init`, so I'll look into upgrading if possible.

**Comment by garagatyi** [comment]
@wernight eclipse che now uses new images, take a look at https://www.eclipse.org/che/docs/setup/getting-started/index.html

**Comment by benoitf** [comment]
@wernight images of che are now on `eclipse` dockerhub organization ( eclipse/che and eclipse/che-server and eclipse/che-init)

**Comment by jlewi** [comment]
@wernight @slemeur any update on eclipse-che on Kubernetes? I see docs for [openshift](https://www.eclipse.org/che/docs/setup/openshift/index.html). Does this imply it ought to work on Kubernetes?

**Comment by skabashnyuk** [comment]
Officially no,  you can track progress here https://github.com/eclipse/che/issues/5908

**Comment by ghost** [comment]
I am going to close this one. Everyone is welcome to track https://github.com/eclipse/che/issues/5908
