### ISSUE TITLE
It is not possible to start workspace with a remote plugin enabled

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11937]
### Description
It is not possible to start workspace with a remote plugin enabled.

### Reproduction Steps
1. Create workspace from Che 7 Stack.
2. Enable Che-Samples-Fortune remote plugin.
Expected: Workspace is started and a fortune teller plugin is available.
Actual: Workspace failed to start with the following error:
```
Error: Failed to run the workspace: "Plugin 'org.eclipse.che.samples.container-fortune:0.0.1' has unsupported type 'Theia plugin'"
```

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
@garagatyi @benoitf FYI

**Comment by garagatyi** [comment]
@sleshchenko should be fixed already

**Comment by sleshchenko** [comment]
@garagatyi I've tested it and you're right: Can't reproduce anymore.
