### ISSUE TITLE
Cannot create a factory for a workspace configured with wksp.next and ide.next

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#11948]
### Description
Impossible to create a factory from a workspace using wksp.next and ide.next from the dashboard.

### Reproduction Steps
1. Create a new workspace from the dashboard
2. Select "Che 7" stack and add in the project sample "web-java-spring"
3. Go onto the Factory on dashboard
4. Try to create a factory from the workspace you've just created.

![capture d ecran 2018-11-15 a 09 25 07](https://user-images.githubusercontent.com/1636769/48539881-c31ec400-e8b8-11e8-8b76-9ffb773289ca.png)

**OS and version:**    
6.13.0 on che.openshift.io

**Diagnostics:**

**Comment by sunix** [comment]
as a quick workaround while fixing it, replace
```
  "commands": [
    {
      "commandLine": "echo ${CHE_OSO_CLUSTER//api/console}",
      "name": "Get OpenShift Console URL",
      "attributes": {},
      "type": ""
    }
  ],
```
with
```
  "commands": [
  ],
```

**Comment by benoitf** [comment]
fixed by https://github.com/eclipse/che/pull/12051
