### ISSUE TITLE
Cannot initialize JDT.LS server

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#11947]
### Description
**Reproduction Steps:**
* Create the workspace with default project (e.g. _web-java-spring_)
* Open the IDE and wait the output in the console of the dev-machine

**Expected behavior:**
* jdt.ls should be initialized
 
**Observed behavior:**
* there is error message in the console:
_' - Can't initialize language server for 'org.eclipse.che.plugin.java.languageserver'_
* there are errors in the browser console
 
**Che version**: 6.15.0
**OS and version:** Fedora 28
**Che install:** ocp/docker
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Related selenium test: _all tests about refactoring_
* See the attachment:

_**screenshot:**_
![not-works-jdt-ls](https://user-images.githubusercontent.com/5408906/48536381-1a239980-e8b7-11e8-82e3-ac6c4c0bebfa.png)

**Comment by tsmaeder** [comment]
Yes, they updated the target platform, working on it.
