### ISSUE TITLE
[Che7] Output panel does not resize properly

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#11949]
### Description
With the new IDE provided with Che 7, it is very easy to adapt the layout of the IDE to make it convenient for a particular scenario.
All panels are properly resizing their content except the one for commands/tasks outputs.

### Reproduction Steps
1. Open the new IDE. 
2. Start a new Command/Task
3. try to resize the output panel

You can see that here, the panel for the terminal (where I'm running `top`) is resized properly.
![capture d ecran 2018-11-15 a 09 30 05](https://user-images.githubusercontent.com/1636769/48540281-fdd52c00-e8b9-11e8-906c-109c259e8a99.png)

![capture d ecran 2018-11-15 a 09 30 11](https://user-images.githubusercontent.com/1636769/48540325-16454680-e8ba-11e8-990f-486b4a0e88a6.png)

![capture d ecran 2018-11-15 a 11 35 50](https://user-images.githubusercontent.com/1636769/48547355-b3a87680-e8ca-11e8-94dc-c23e9e0545be.png)

**OS and version:**    

**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
text-reflaw feature was merged to the xterm.js https://github.com/xtermjs/xterm.js/pull/1864. After release newer xterm.js and update it in the Theia upstream this bug will be fixed.
