### ISSUE TITLE
Add a property in the `meta.yaml` of editor plugins to support resource pre-loading from CDNs

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#11943]
In the context of issue https://github.com/redhat-developer/rh-che/issues/1071, it seems that it could be necessary to introduce an additional information associated to editor plugins in the Che Plugin Registry.

This information would finally point to a list of URLs that could be pre-loaded by the workspace loader while the workspace containers are still starting, in order to make the overall start faster.

My idea was to add a new `preloadUrls` (or something similar) property in the `meta.yaml` file, that would point to a file stored somewhere (besides the plugin definition tgz file ?) and that would contain this list of urls.

One thing to keep in mind is that the URLs to pre-load (defined in this new file) might change while the plugin definition tgz itself would not have changed, since this list of URLs is mainly depending on the content of the editor docker image (for Theia at least).

It would be great if we could start discussing the various options available to provide such a feature, and the related model changes that they would require.

**Comment by davidfestal** [comment]
@l0rd @skabashnyuk your input is welcomed here :-)

**Comment by garagatyi** [comment]
@davidfestal could you add an example of a meta.yaml that you are suggesting?

**Comment by skabashnyuk** [comment]
We need to make sure that this would not make a good instrument to make Che as a good source of DDOS attack. I would say that this feature should be available only for authorized/checked/trusted plugins/editors.

**Comment by garagatyi** [comment]
Could you elaborate on how it can extent DDOS attack capabilities? We were talking about that with David and it seems that it doesn't differ much from what we are offering with custom editors in Che 7.

**Comment by l0rd** [comment]
Yes and also @davidfestal can you explain how the URL will be used? Weill the URL be used by the broker? By che-server? And offline startup of a container should be possible.

**Comment by garagatyi** [comment]
@skabashnyuk you are right, but it would be also possible with any custom editor. So there is no real difference as far as I understand.

**Comment by davidfestal** [comment]
Let me give a bit more details:

#### An example of the additional data
 
Let's take the example of the Theia editor, in the following [`meta.yaml` file](https://github.com/eclipse/che-plugin-registry/blob/master/plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml), we could add the following line:

```
preloading: https://github.com/ws-skeleton/che-editor-theia/releases/download/untagged-74eef382fad2636fda4f/chunks.json
```

And `chunks.json` (pushed or updated as an asset of the release, besides the `.tgz` file, as often as necessary => after each docker push of the related  docker image), would contain something like:
```
[
  {
    "chunk": "runtime.ad513d18f94de88a582b.js"
  },
  {
    "chunk": "vendors.b44cff575eff4347f7d9.js",
    "cdn": "https://cdn.jsdelivr.net/gh/davidfestal/che-theia-cdn/example-browser/vendors.b44cff575eff4347f7d9.js"
  },
  {
    "chunk": "main.c789d6cba62c705ed029.js",
    "cdn": "https://cdn.jsdelivr.net/gh/davidfestal/che-theia-cdn/example-browser/main.c789d6cba62c705ed029.js"
  }
]
```

This file will be generated and added into the `che-theia` image when it is built.

#### How it will be used
 
The workspace loader typescript application should be able to have access to this JSON definition from a workspace ID.
This seems possible to me by:
- retrieving the editor reference from the workspace configuration
- requesting the plugin registry to have access to its `preloading` value
- fetch the JSON from the preloading URL.

From the content of this JSON file, the workspace loader application would be able to add the following to its main html page:
```
<link rel="prefetch" href="https://cdn.jsdelivr.net/gh/davidfestal/che-theia-cdn/example-browser/vendors.b44cff575eff4347f7d9.js">
<link rel="prefetch" href="https://cdn.jsdelivr.net/gh/davidfestal/che-theia-cdn/example-browser/main.c789d6cba62c705ed029.js">
```

which would allow performing the client-side loading / caching of the main ID JS files concurrently while the workspace POD is still starting containers.

**Comment by garagatyi** [comment]
We discussed usage of CDN with Florent and Mario yesterday and realized that it would be cool to be able to prefetch resources even before workspace is created and editor is chosen. In that case, we would have the most rapid approach. This is especially helpful for a slow connection, such as mobile network or ADSL because starting prefetching of resources on the workspace loading with such a slow connection might not provide significantly better timing. And since we are going to decrease the time needed to pull images and start Theia machine we need to load resources earlier than a workspace start. 
We were considering extending Che master and plugin registry capabilities to be able to fetch resources of some IDEs whenever UD is opened. 
@l0rd should we work on this issue with extending `meta.yaml` model or try some another approach?

**Comment by garagatyi** [comment]
In OSIO case we know the IDE and should prefetch it way earlier - on the OSIO UI side. This would provide the best experience.

Regarding the need to add it to the meta.yaml model. If we would create broker service to evaluate and cache workspace sidecars configuration we would be able to move cache instructions to the editor definition and not extend meta.yaml that was supposed to be super simple and general for all the plugins and editors.

**Comment by garagatyi** [comment]
We would need to update something on each change of the image in any case. Either che-plugin.yaml or meta.yaml

**Comment by davidfestal** [comment]
> We would need to update something on each change of the image in any case. Either che-plugin.yaml or meta.yaml

well, not necessarily. If the broker service would extract the list of URLs from the editor image (see [my  comment above](https://github.com/eclipse/che/issues/11943#issuecomment-439350243)), then nothing more than the docker image would need to be updated (the docker image can be updated, and overwritten, to an existing image tag).
But in this case the broker service should regularly check whether the editor image was updated, and if it was the case, update the related cached list of URLs to preload.
