### ISSUE TITLE
Che7 stacks don't have a declared Tomcat server

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#11956]
### Description
[`Che7`](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L443) and [`Che7 Dev`](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L516) stacks don't have a Tomcat server declared for `ws/dev` machine.
It brokes Preview URL feature for a running task.

### Reproduction Steps
- create a workspace based on the Che7 stack with importing `web-java-spring` project
- execute task `build and run tomcat`
- open a preview URL

URL is wrong. Adding the following server declaration in ws config fixes the wrong URL:
```
"servers": {
   "tomcat8": {
      "attributes": {},
      "protocol": "http",
      "port": "8080"
   }
}
```

**Diagnostics:** 
che.openshift.io

**Comment by skabashnyuk** [comment]
I would not say that this is a bug. Since we need tomcat tool to be able to run web-java-spring application

**Comment by azatsarynnyy** [comment]
@slemeur do we still need this as a temporary solution while there's no Che Tomcat plugin?

**Comment by skabashnyuk** [comment]
@azatsarynnyy perheps you are right. this is a server in user application

**Comment by slemeur** [comment]
Yes the servers should be configured indeed.
