### ISSUE TITLE
Java language server listens to a wrong ProjectCreatedEvent

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#11960]
### Description
 
`WorkspaceSynchronizer` listens to `ProjectCreatedEvent` to add the project to java language server, witch is  fired when the project **clone is finished**:
https://github.com/eclipse/che/blob/58dc906339f7d502f0d298d967761329b1cddf2c/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java#L194-L195
then 
https://github.com/eclipse/che/blob/58dc906339f7d502f0d298d967761329b1cddf2c/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java#L210-L214 

This event should be fired directly after the project **has been registered** and we have a [Pull Request](https://github.com/eclipse/che/pull/10454) that makes firing `ProjectCreatedEvent` from single place by file-watcher, when the project folder is created and the project is registered.

The problem is that if the `ProjectCreatedEvent` works as it should, the project wouldn't be updated with java language server.
### Reproduction Steps

1. Build CHE from branch CHE-9924
2. Create a workspace with java language server
3. Create a java project e.g. `web-java-spring`

**Expected:**
java language server should update the project, config files should be generated:
![screenshot-172 17 0 1-8080-2018 11 15-16-23-54](https://user-images.githubusercontent.com/7668752/48558935-2594b600-e8f3-11e8-8dfc-904ea935090f.png)

**Wrong:**
![screenshot-172 17 0 1-8080-2018 11 13-17-48-43](https://user-images.githubusercontent.com/7668752/48425006-92ca0f00-e76c-11e8-931e-8e9074d4d1f7.png)
no config files are present in the project

**OS and version:**    

**Diagnostics:**

**Comment by vinokurig** [comment]
Proposal:
switch `WorkspaceSynchronizer` to `ProjectImportedEvent` witch will be fired from `ProjectImportManager.doImport()`
@tsmaeder WDYT?

**Comment by tsmaeder** [comment]
1. Eventually, jdt.ls is going to handle this themselves: https://github.com/eclipse/eclipse.jdt.ls/issues/144
2. What about all the other ways projects can come into existence? What about "samples"? What about project detection via the file system? We need an approach that works for all cases.
