### ISSUE TITLE
Command to trigger rest api services

### ISSUE THREAD

**Issue by 781227k** [eclipse-che/che#11963]
Hello,

I was wondering if it is possible to trigger a rest api service with a custom command. 

As an example; Creating a custom command called "che generate maven" and it will trigger the rest api for maven project type and a project will be created in the workspace.

-- Or at least to trigger che actions
Thanks in advance!

**Comment by 781227k** [comment]
@eivantsov  Thanks for the response!

As a last option i think i can go for that but what I really want is that extending the existing terminal so that it can response my custom CLI commands.

It is similar to what described here.  #4949

**Comment by skabashnyuk** [comment]
Closing. Feel free to reopen this issue if you think it's still relevant for you.
