### ISSUE TITLE
Workspace Agent produces an abnormal number of error logs during selenium testing

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11964]
### Description
It is needed to investigate why Workspace Agent produces an abnormal number of error logs during selenium testing.

Examples of such `ci-test` executions:
https://github.com/eclipse/che/pull/11920#issuecomment-439021314
https://github.com/eclipse/che/pull/11941#issuecomment-438825764
They are different PRs that are not related but have the same `ci-test` failure cause.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@sleshchenko can you confirm that this issue is still a blocker taking into account that it is open for more than a month?

**Comment by sleshchenko** [comment]
@garagatyi I agree that it is not blocker if it is not solved for more than a month. So, I changed severity to `P1` since it makes `ci-tests` job unstable.
@dmytro-ndp Are there any plans to investigate this issue?

**Comment by dmytro-ndp** [comment]
@sleshchenko: actually the problem hasn't occurred on CI since then, and logging of workspaces has been fixed, AFAIK.
So, it's not quite clear how to reproduce the issue.

**Comment by sleshchenko** [comment]
@dmytro-ndp Then WDYT about closing this issue until we will not face this again?

**Comment by dmytro-ndp** [comment]
There is [an issue about JSON-RPC messages is still in progress](https://github.com/eclipse/che/pull/12252), so problem could reproduce again if _java language server_ starts producing abnormal messages again.

**Comment by dmytro-ndp** [comment]
This issue is related to https://github.com/eclipse/che/issues/11961.
