### ISSUE TITLE
Create own AbstractNewResourceAction

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#11965]
Hi,

I would like to create my own event in order to create new resources such as create a new .java file.
In order to do, I guess that I need to create a piece of code similar like this one.

`  public NewClikeResourceAction(
      String title,
      String description,
      SVGResource svgIcon,
      DialogFactory dialogFactory,
      CoreLocalizationConstant coreLocalizationConstant,
      EventBus eventBus,
      AppContext appContext,
      NotificationManager notificationManager,
      Provider<EditorAgent> editorAgentProvider) {
    super(
        title,
        description,
        svgIcon,
        dialogFactory,
        coreLocalizationConstant,
        eventBus,
        appContext,
        notificationManager,
        editorAgentProvider);
    this.appContext = appContext;
  }`

I would like to write in a log files created by my new "new file event",  in order to do that I need to know the path and the file name to write it on the log file.
I would like to know if any of those above arguments are able to give me the path and also the file name.

**Comment by eivantsov** [comment]
@vparfonov @vzhukovskii @azatsarynnyy are most knowledgeable in this area

**Comment by mstavares** [comment]
Coudl this RevealResourceEvent help me?
`              @Override
              public void apply(File newFile) throws OperationException {
                editorAgentProvider.get().openEditor(newFile);
                eventBus.fireEvent(new RevealResourceEvent(newFile));
              }`

**Comment by vzhukovskii** [comment]
Hi @mstavares! Thanks for your question. Can you elaborate the details, what kind of log record do you want to write and where exactly? On the server side or on the client?

**Comment by mstavares** [comment]
Hi @vzhukovskii, sure!
I would like to invoke a web service in order to store it server side.
That log file will contains the workspace (I guess that I can fetch it from AppContext) and the path + file name of the created file.

**Comment by mstavares** [comment]
Hi,

I already have solved this issue through RevealResourceEvent.
Thanks.
