### ISSUE TITLE
Che 7 workspace creation fails on a new OpenShift cluster

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11967]
### Description

The first time I create a Che 7 workspace on a new minishift / minikube cluster, che-plugin-broker Pod creation fails with the following error: `Pod has unbound PersistentVolume`

![image](https://user-images.githubusercontent.com/606959/48581669-ba62d800-e922-11e8-9cfa-507c4808ec9f.png)

### Reproduction Steps

1. `minishift delete`
2. `minishift start --memory=4GB`
3. `minishift addons apply che` (this step needs the following fix to work https://github.com/minishift/minishift/pull/3011)

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/11920

**Comment by l0rd** [comment]
I've been able to test again and it's fixed indeed. Thank you @sleshchenko!
