### ISSUE TITLE
Getting Started - ARTIK IDE, not making sense

### ISSUE THREAD

**Issue by versamodule** [eclipse-che/che#1196]
I do not know where else to post this so if this is the wrong place sorry. 
I am using a PC for this. 
I started reading the Getting Started - ARTIK IDE here: 
https://eclipse-che.readme.io/v4.0/docs/samsung-artik-ide-getting-started

Is this setup for a Linux box or a PC?  I am assuming its for a Linux, because In step 2, they say "Shell"

So if this is true, there is no PC installation ?

**Comment by TylerJewell** [comment]
@versamodule The installation works for Linux, Mac or Windows.  Vagrant and VirtualBox installs on all of the platforms and provides a platform-neutral way for us to configure an environment to run the IDE.

**Comment by versamodule** [comment]
Yes, I have installed those. But in section 2 where it says "Shell" does not make any sense where it says

# Get the ARTIK IDE Vagrantfile

# Multiple locations:

https://github.com/codenvy/artik-ide/blob/master/Vagrantfile
http://install.codenvycorp.com/artik

**Comment by TylerJewell** [comment]
@versamodule I see the confusion.  The shell isn't really a shell - that is just a misnomer in the docs.  We'll fix that.  You just need to get the Vagrantfile from one of those two file locations and place it into an empty directory.  We'll fix the docs language.

**Comment by versamodule** [comment]
>  You just need to get the Vagrantfile from one of those two file locations

Those file locations are drastically different. In other words one is a 136 meg download, and the other is a single file.

**Comment by TylerJewell** [comment]
One was a directory - the Vagrantfile is inside of it.  We can make it an absolute path the file - but we are also likely to include nightly, latest, and build versions of the vagrantfile in the install.codenvycorp.com directory.

**Comment by versamodule** [comment]
ok, i'll keep checking back when the directions are clear. To be honest as it sits right now is not very clear at all.

**Comment by TylerJewell** [comment]
@versamodule I would just grab this Vagrantfile - https://github.com/codenvy/artik-ide/blob/master/Vagrantfile.  You will be ok with this one.   Sorry for the confusion in the docs.

**Comment by versamodule** [comment]
Thats part of the problem. I dont see a way to "grab" it.  Not to mention if i were to grab it what do i save it as and what extension, then where do it put it.

**Comment by ghost** [comment]
You save it as Vagrantfile. Any location.

**Comment by TylerJewell** [comment]
In the empty directory that you have created, create a file named, "Vagrantfile".  There is no extension.  You place the contents of that link into that file.  You can also just download the file as-is from here. https://install.codenvycorp.com/artik/Vagrantfile
