### ISSUE TITLE
Eclipse Che multi users install fails ont minishift 1.27 with: [ERROR] Keycloack deployment failed. Aborting.

### ISSUE THREAD

**Issue by KitioFofack** [eclipse-che/che#11976]
### Description

I 'm trying eclipse che install on MInishift 1.27 .
The scripts fails with message [ERROR] Keycloack deployment failed. Aborting
oc rollout status keycloak says: ERROR : the server don't have a resource type "keycloak"

### Reproduction Steps

Install Minishift cluster
run ./deploy_che.sh --multiuser

**OS and version:**    

Centos 7 on KVM nested on Xen

**Diagnostics:** 

Logs are empty.

**Comment by skabashnyuk** [comment]
is there anything else in the logs?

**Comment by skabashnyuk** [comment]
@KitioFofack I need more information to reproduce. otherwise, I'm going to close this issues as incomplete.
