### ISSUE TITLE
Feature Request : Show Java documantation as mouse-over

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#11988]
For now, Eclipse Che use ctrl+Q to trigger to show documentation in eclipse che.
It's just uncomfortable to use key binding for showing documentation.

I expect it to pop automatically as I mouse over on it.

**Comment by skabashnyuk** [comment]
@tsmaeder can you take a look?

**Comment by tsmaeder** [comment]
Current builds (6.14.1) uses hover for this. If that does not work, please reopen.
