### ISSUE TITLE
Feature Request : Quick Type Hierarchy

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#11987]
For Java development, there are "Quick Type Hierarchy" in context menu on eclipse for desktop usage (such as eclipse photon, oxygen, neon... ), but not on eclipse che.
It's important for java development to show type hierarchy of classes.

Is there any comparable features on eclipse che?
Is there any schedule for add feature "Quick Type Hierarchy" ?

**Comment by skabashnyuk** [comment]
@tsmaeder wdyt?

**Comment by gorkem** [comment]
closing as this is implemented on Che 7
