### ISSUE TITLE
Feature Request : Open Call Hierarchy

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#11986]
For Java development, there are "Open call Hierarchy" in context menu on eclipse for desktop usage (such as eclipse photon, oxygen, neon... ), but not on eclipse che.
It's important for java development to show call hierarchy of modules .

Is there any comparable features on eclipse che?
Is there any schedule for add feature  "Open call Hierarchy" ?

**Comment by skabashnyuk** [comment]
@tsmaeder wdyt?

**Comment by tsmaeder** [comment]
Call hierarchy is implemented in Theia (Che 7). There are no plans to implement this in Che 6
