### ISSUE TITLE
Can't upload files with Microsoft Edge.

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#11982]
### Description
We failed to upload files to workspace  using Microsoft Edge.
When we upload file with Edge, the names of uploaded files were full path name in my local PC and eclipse che cannot operate these files.
![failedtouploadfile](https://user-images.githubusercontent.com/43225784/48705105-ac22fd80-ec3b-11e8-8d6b-f8103e378355.png)

We could successflly uploaded files with Google Chrome.
![successtouploadfile](https://user-images.githubusercontent.com/43225784/48706525-e2627c00-ec3f-11e8-9297-024b9ff16892.png)

### Reproduction Steps
1. Install Eclipse Che 6.13.1 on CentOS 7.4
1. Access Eclipse Che with Edge on Windows 10.
1. Create Project via [Workspace] - [Create Project].
1. Select created project and upload file via [Project] - [Upload FIle...].

**OS and version:**    
 - Eclipse che execution environment： Docker 1.13.1 on CentOS 7.4
 - Operation environment：Microsoft Edge 42 on Windows 10 1803

**Comment by skabashnyuk** [comment]
@vparfonov can you take a look
