### ISSUE TITLE
Unable to build Theia image with CHE 7 dev stack, because yarn "unable to find lerna binary".

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#11996]
### Description
For Theia image was changed node_modules location to the "/node_modules",  but to build Theia uses script https://github.com/theia-ide/theia/blob/master/scripts/lerna.js:

And this script unable to find lerna binary in the external node_modules:
https://github.com/theia-ide/theia/blob/master/scripts/lerna.js#L19

**Comment by sunix** [comment]
we are not supposed to build theia inside theia-ide container but 'dev' container. at the moment it is not working but working on it
