### ISSUE TITLE
Projects with preview and after names displayed after rename project by context menu in IDE

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#12000]
### Reproduction Steps
 - Go to the dashboard and run default java stack with default  spring project
![stack](https://user-images.githubusercontent.com/22724619/48776075-86e3cd00-ecd7-11e8-8e85-41ff5d35a2b5.png)

 - Wait until workspace is run
 - Wait until language server is initialized 
 - Open context menu on the project folder in project explorer
 - Click on "Rename" item in context menu
 - In the opened dialog type new name and click "Ok" button
 - Pay attention that project is renamed
 - Wait several seconds and pay attention that folder with previous project name is also displayed
![rrrrrr](https://user-images.githubusercontent.com/22724619/48776268-16897b80-ecd8-11e8-935a-6405c668eb82.gif)

**Expected behavior:**
The project is renamed and displayed just one folder with new project name

**Observed behavior:**
The project is renamed, but folder with old project name also displayed

**OS and version:**    
Che 6.15.0-SNAPSHOT; Chrome 68 ; Fedora 28

**Failed selenium test:** 
RenameProjectTest

**Browser logs:**
![log](https://user-images.githubusercontent.com/22724619/48776382-68320600-ecd8-11e8-8bb6-9a9017218cc7.png)

**Comment by tsmaeder** [comment]
Why is this a P1?

**Comment by Ohrimenko1988** [comment]
Because this behavior looks very ugly and leads to mistakes and misunderstanding especially in case with multiple projects. Any suggestions?

**Comment by SkorikSergey** [comment]
There are some more problems after project renaming:
- project with old name still exists with ```bin``` folder in it(see screenshot);
- code validation feature doesn't work(see screencast) after renaming. It will start working after workspace restart.

**Screencast:**
![screencast-172 19 20 234-8080-2018 12 04-09-44-40](https://user-images.githubusercontent.com/7760565/49426824-5f4a3580-f7aa-11e8-9047-2b04fb0f003f.gif)

**Screenshot:**
![selection_172](https://user-images.githubusercontent.com/7760565/49426819-5b1e1800-f7aa-11e8-9d45-396c30286e6d.png)

**Comment by tsmaeder** [comment]
The left-over bin folder is very likely simply due to the fact that jdt.ls was building the project at the time of the rename. I see this as a mostly cosmetic problem
The fact that the new project is not picked up is a real problem. We'll have a look.
