### ISSUE TITLE
Change the name of temporary generated dockerfile

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#12009]
.Dockerfile is created when building a docker image. After breaking the build process this file is still exist. Git informs that this is a change and proposes to commit the file.

We have to change the name of generated file and add it to the .gitignore.

**Comment by garagatyi** [comment]
I think that .Dockerfile is generated by docker itself. Not sure whether we can change it. But +1 to add it to ignore rules

**Comment by sleshchenko** [comment]
> I think that .Dockerfile is generated by docker itself. Not sure whether we can change it. But +1 to add it to ignore rules

@garagatyi [build.include](https://github.com/eclipse/che/blob/master/dockerfiles/build.include#L131) is a script that produces `.Dockerfile`
