### ISSUE TITLE
Make branding depends of stack

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#12015]
Hi,

I would like to know if is possible to change the branding icons depending the stack.
For instance, I would like to show a Java icon instead of this Eclipse Che (https://ibb.co/j5zr0V) when my workspace is running a Java stack.

Thanks,

**Comment by skabashnyuk** [comment]
that is not possible at this moment.

**Comment by mstavares** [comment]
Ok, thanks a lot!
