### ISSUE TITLE
Add support of Golang projects to Che Theia

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12025]
### Description
I'm writing Golang code for Che plugin brokers and some other Che maintainers also write Golang code for different agents and stuff like that.
Unfortunately, we don't have code intellisense for Golang in Che Theia.
This doesn't allow us to dogfood Theia efficiently. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@AndrienkoAleksandr @sleshchenko @eivantsov @evidolob @ashumilova FYI

**Comment by AndrienkoAleksandr** [comment]
+1 000 000

**Comment by eivantsov** [comment]
Quick solution would be to include Go extension to Theia by default. However, that's a hack and, besides, we will need Goland (with around ~15 deps) and Nodejs for the language server to start.

I think once language plugin API is ready, it can be a VS Code plugin in the image with all the deps and language server as well.

We won't have debugger unfortunately, but code navigation + code completion is already smth to start with.

**Comment by garagatyi** [comment]
If we want to dogfood then even Theia extension with all the runtime dependencies it brings would be valuable

**Comment by tsmaeder** [comment]
Che 7 plugin is now in.
