### ISSUE TITLE
[Feature request] "Per-Workspace" persistent volume claim support.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12024]
#### background

Currently, Che has two PVC strategy, `common` and `unique`.
They are not fit to auto-provisioned PV that is provided cloud providers like AWS, Azure, GCP.

In these environment, PV is a 'managed disk' that is mounted as a block device by nodes.
Disks can't be shared by any pods. So we can't use `common` strategy.

The other hand, `unique` generates unique PVs per each mount point. It looks good.
But it have a pain point.
Virtual machines as nodes will have limitation in the number of mountable disks.
So we will get "out of resources" (can't mount) error by node VM when we run some workspaces.

Referring to the current code, the workspace in Kuberenetes is defined as `deployment` and all contaners in the workspace are in the same pod.
In Kubernetes, Containers in same pod can share the disk. So actually all workspaces require just only 1 PV.

#### solution plan

It's better to add new persistent volume claim like `PerWorkspacePVCStrategy.java` for 
 managed Kubernetes services.

**Comment by monaka** [comment]
I'm writing "PerWorkspacePVCStrategy.java". Is this acceptable for the master branch?

**Comment by sleshchenko** [comment]
@monaka Looks meaningful for me. I have no objections against having such strategy in master. Welcome to prepare PR. Will discuss implementations details there. 
Feel free to write here/email me/write to Eclipse MM if you have any issues/questions.

@ibuziuk @garagatyi WDYT?

**Comment by garagatyi** [comment]
I'm OK too

**Comment by david-martin** [comment]
@eivantsov I was about to create such an issue for a problem we'll have soon in integreatly clusters.
A strategy for a single claim per workspace would help solve mutli-AZ issues.
Currently with the 'unique' claim, the 2 claims (logs & projects) could end up in different AZ's, resulting in no satisfiable node for scheduling the workspace.
Sharing the same claim would avoid this issue.

+1 on this change from me

**Comment by eivantsov** [comment]
@david-martin yes, that's a very good PR.

**Comment by sleshchenko** [comment]
Merged into master and will be available in next 6.16.0 release.
