### ISSUE TITLE
How to change the encoding/locale of editing area

### ISSUE THREAD

**Issue by drtangsoverlinevisit** [eclipse-che/che#1203]

**Comment by ghost** [comment]
@drtangsoverlinevisit can you be more specific? What do you mean by `coding area`?

**Comment by TylerJewell** [comment]
I am guessing he means the editor.

**Comment by ghost** [comment]
Yeah, editor. Maybe an example will make the request clearer.

**Comment by drtangsoverlinevisit** [comment]
change the default encoding (utf-8)
