### ISSUE TITLE
Change About Eclipse Che

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#12039]
Hi,

Is it possible to change eclipse che logo which is on about menu?

`/** @author Vitaly Parfonov */
public interface Resources extends com.google.gwt.resources.client.ClientBundle {

  @Source("logo/che-logo.svg") // This logo
  SVGResource logo();

  @Source("logo/water-mark-logo.svg")
  SVGResource waterMarkLogo();

  @Source({"Styles.css", "org/eclipse/che/ide/api/ui/style.css"})
  Styles styles();
}`

If I replace it for another one I have this error during the compilation process

[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-8:compile (default-compile) on project che-ide-gwt-app: GWT exited with status 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :che-ide-gwt-app

Thanks,

**Comment by eivantsov** [comment]
Can you share more logs?

**Comment by mstavares** [comment]
Hi @eivantsov,

Maybe the issue is related with my SVG file

[INFO]             Creating assignment for waterMarkLogo()
[INFO]                [ERROR] Invalid SVG input @jar:file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-core-ide-ui/target/che-core-ide-ui-6.14.0-SNAPSHOT.jar!/org/eclipse/che/ide/ui/logo/water-mark-logo.svg L:21,C:23
[INFO] org.xml.sax.SAXParseException; systemId: jar:file:/home/mtavares/Projetos/PE/VF-OS/studio/ide/che-core-ide-ui/target/che-core-ide-ui-6.14.0-**SNAPSHOT.jar!/org/eclipse/che/ide/ui/logo/water-mark-logo.svg; lineNumber: 21; columnNumber: 23; cvc-complex-type.3.2.2: Attribute 'inkscape:version' is not allowed to appear in element 'svg'.**

**Comment by eivantsov** [comment]
Yeah, GWT may have own rules regarding svg format.
