### ISSUE TITLE
Regarding the Procedure used to Implement Syntax Highlighting Support to Eclipse Che for Existing Programming Languages (Java, Python, Ceylon etc.)

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#12038]
This issue is related to #11865, and is opened since I do not have permission to re-open the said issue.

I have learnt (from the above mentioned repo, as stated by @eivantsov ) that it is not possible to implement syntax highlighting through plugins or LS Sidecars in Che, as of yet. However, I was wondering whether there is _**any other way**_ (except Theia, since I still did not get a clear idea on how to extend Theia in Che) to have syntax highlighting implemented to a new language introduced to Eclipse Che by me (DSL). Can I not do it by implementing the necessary programs to Che and by building it? Or can I not do it by introducing the new language to Orion editor?

How are the existing programming languages implemented to Eclipse Che in a way that everything including syntax highlighting to error recognition are supported by it? Is it not possible to use the same procedure to have the same for my DSL, or is it too complex for me to do?

I would be really grateful if you would kindly let me know about the implementation procedure as I have mentioned above. 

Thank You!

**Comment by skabashnyuk** [comment]
@tsmaeder @tolusha can you take a look?

**Comment by SharkJ** [comment]
Can someone kindly explain this to me?

**Comment by l0rd** [comment]
@SharkJ you are raising few distincts problems here:

1. How can I extend Theia in Che?
2. How can I add syntax highlighting for a new language in a Che 6 (Orion GWT based) workspace?
3. How can I have more advanced language support in a Che 6 workspace? How complicated is that?

For 1. have a look at https://github.com/eclipse/che/wiki/Technical-FAQ#theia-ide--che-questions and https://github.com/eclipse/che/wiki/Contributing-to-Che7-and-Che-Theia
For 2. I don't know if there is an easy way to do that. Maybe @benoitf has an answer? 
For 3. have a look at https://www.eclipse.org/che/docs/che-6/language-servers.html

**Comment by SharkJ** [comment]
Hi,
Does Che 7 provide a solution to support syntax highlighting for custom languages?
