### ISSUE TITLE
Widespread use of bogus equals() Implementation

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12040]
In many places, we override ```equals()``` in a way that is simply wrong. Here's a snippet from ResourceNode.java:
``` 
public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof ResourceNode)) return false; >>>>>> Problem here!
    ResourceNode<?> that = (ResourceNode<?>) o;
    return Objects.equal(resource, that.resource);
  }
```
This code is not a correct because it does not correctly implement the contract for equals(), in particular it is not symmetric. For example, ```ContainerNode``` extends ```ResourceNode```, so you can have cases where resNode.equals(folderNode), but not folderNode.equals(resNode). 

This leads to all kinds of unexpected results, for example folder nodes not being correctly replaced with package nodes, in the project navigator because they are considered equal.

Depending on how collections are implemented, bogus equals implementations can lead to cases where we can have duplicate entries in sets or entries in maps not being found after being added with the same key.

**Comment by metlos** [comment]
Are you sure that is the problem? The `instanceof` check will pass for any instance of any class inheriting from `ResourceNode`.

If the check wasn't there, you could not do basically any kind of comparison, because you could not be sure of the type of the object being compared to.

**Comment by dkuleshov** [comment]
I don't see the problem as well. Can you please provide a unit test? [This](http://thefinestartist.com/effective-java/08) also might be helpfull.

**Comment by tsmaeder** [comment]
The check needs to be if (getClass() == other.getClass()), not instanceof.

**Comment by tsmaeder** [comment]
> Are you sure that is the problem? The `instanceof` check will pass for any instance of any class inheriting from `ResourceNode`.
> 
> If the check wasn't there, you could not do basically any kind of comparison, because you could not be sure of the type of the object being compared to.

**Comment by tsmaeder** [comment]
> I don't see the problem as well. Can you please provide a unit test? [This](http://thefinestartist.com/effective-java/08) also might be helpfull.

Thanks for the reference, it proves my point.

**Comment by dkuleshov** [comment]
I assume you mean this case? 
```java
class B {}
class A extends B {}

A a = new A();
B b = new B();
...
(a.equals(b).equals(b.equals(a))== false;
```

**Comment by tsmaeder** [comment]
yes

**Comment by l0rd** [comment]
@tsmaeder it would be interesting if you could provide a failing unit test. It would be particularly useful to identify other classes affected by the same problem.

**Comment by tsmaeder** [comment]
Actually, symmetry is given with the implementation in question, so I am wrong on that one :man_facepalming: 
, but the case that remains is that folder.equals(package), which IMO only makes sense in very particular cases.

**Comment by tsmaeder** [comment]
@metlos you're right. It's still bogus, though.

**Comment by gorkem** [comment]
I am closing this one as I am not sure if there is an action to take here. @tsmaeder reopen if you feel we still need to act on it
