### ISSUE TITLE
Node Stacks uses outdated way of procuring Yarn

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#12044]
### Description

Prior to Che moving to a Theia stack, the Node.js stack seems to have been overlooked - the `yarn` version in the stack is no longer supported, thus, I made a PR to the dockerfiles repo to reflect this.

**Comment by skabashnyuk** [comment]
@ashumilova @evidolob can you take a look?

**Comment by sr229** [comment]
Seems CentOS version had no Yarn installed, do I also add Yarn on the CentOS version?

**Comment by gorkem** [comment]
@sr229 Is this still valid, I am closing it now, feel free to reopen
