### ISSUE TITLE
Rename "Bayesian Language Server " to something more user friendly

### ISSUE THREAD

**Issue by tgrall** [eclipse-che/che#12048]
### Description

The **Bayesian Language Server** does not describe what this plugin/installer is about. We must provide a better name and description that helps the user to know what this plugin does, and why he should use it. (not "how it is done")

Proposal 
* Dependency Analytics Server
* Dependency Analytics LSP Server

The 'Dependency Analytics Server' is used by Eclipse Che to provide insights about your application dependencies such as:

* Flags a security vulnerability(CVE) and suggests a remedial version
* Shows Github popularity metrics along with latest version
* Suggests a project level license, check for conflicts between dependency licences
* AI based guidance for additional, alternative dependencies

### Reproduction Steps
Not a bug, just renaming

**Comment by slemeur** [comment]
Moved to https://github.com/redhat-developer/rh-che/issues/1098
