### ISSUE TITLE
Support for Swift Language via Sourcekit-LSP

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12045]
### Description
[SourceKit-LSP](https://github.com/apple/sourcekit-lsp)

Implementaton of Swift Support using Sourcekit-LSP

# SourceKit-LSP

SourceKit-LSP is an implementation of the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (LSP) for Swift and C-based languages. It provides features like code-completion and jump-to-definition to editors that support LSP. SourceKit-LSP is built on top of [sourcekitd](https://github.com/apple/swift/tree/master/tools/SourceKit) and [clangd](https://clang.llvm.org/extra/clangd.html) for high-fidelity language support, and provides a powerful source code index as well as cross-language support. SourceKit-LSP supports projects that use the Swift Package Manager.

**Comment by skabashnyuk** [comment]
@tsmaeder @tolusha can you take a look?

**Comment by tsmaeder** [comment]
This sounds like an opportunity for a Che 7 plugin. I don't see Swift as a high-priority target.

**Comment by ios3** [comment]
It would be better if we can develop Server-side Swift (Vaopor/Kitura) on Che 7

**Comment by slemeur** [comment]
Sounds good ! Would love that indeed. Thanks @ios3
