### ISSUE TITLE
`failed: HTTP Authentication failed; no valid credentials available` logs on my web browser.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12042]
### Description

Sometimes my Chrome shows a lot of `failed: HTTP Authentication failed; no valid credentials available` message.
Even though I'm using patched Che-server, I suspect it will be reproduced on the vanilla Che.

It looks the similar issue was [reported on the another project](https://github.com/keymetrics/pm2-io-js-api/issues/53) and [fixed there](https://github.com/keymetrics/pm2-io-js-api/commit/eb9d3336fd83283cd07a4a81ce96a8f38df8ff0f). 

Referring to the code tree, it seems they don't update their token applied.

### Reproduction Steps

Should be clarified.

**OS and version:**    

Che nightly build. Multi-user with Keycloak. Possibly all versions of OSes and browsers.

**Diagnostics:** 

```
app-fd93f77024.js:114795 WebSocket connection to 'wss://che-{censored}/api/websocket?token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMjNGc3kzRlI5dnRUZms3TGlkX1lQOGU0cDNoY0psM20wQTRnckIzNnJJIn0.eyJqdGkiOiJhNWE3YTQyMi1iYjU0LTQxYmItYTk2Yy04NDJjOTdhMjc0YzMiLCJleHAiOjE1NDMwMTg4MzgsIm5iZiI6MCwiaWF0IjoxNTQzMDE4MjM4LCJpc3MiOiJodHRwczovL2tleWNsb2FrLWNhbWluby5jLnBpenphZmFjdG9yeS5qcC9hdXRoL3JlYWxtcy9jaGUiLCJhdWQiOiJjaGUtcHVibGljIiwic3ViIjoiNjNjZTg2MDQtMmViNS00NmIwLWI0MWUtMTdiNjM3NmE5YjliIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY2hlLXB1YmxpYyIsIm5vbmNl...ybmFtZSI6ImNyeXB0Y29pbi1qdW5rZXkiLCJnaXZlbl9uYW1lIjoiQ3J5cHRvY29pbiIsImZhbWlseV9uYW1lIjoiSnVua2V5IiwiZW1haWwiOiJjcnlwdGNvaW4uanVua2V5QGdtYWlsLmNvbSJ9.TZ8nJYIaFiKIUhA5hkVCATgvK2YQcxxx-oSPeAWD0pDYD6M1sKamp3hnrvLqw4oleC69FZ2Le26AROct9d-SXZEgb-gzGShlYUlpKxEB35PZlmUbwkBYhssUbeCz-XJ-9mQSnvBhr05mpPp71oh1X5fnU2H0DOdRJzyWZjDiOzMtJW15p79es9hf0ODgjfnknPtYJjv0FsfTRFISIq9kt8Sm5uVn9iFrcxtG5M3Hdshj_TiP6qMKyGzJsvVrmBI8X2JedhWuHqJhwADfG8eourGzJNVzIXg1xEZ3PDxkdvJ8IaovxUnu3niI9SpnrO8mQ1ISjM1Q4CzDJBFSM-2F2Q&clientId=40835350' failed: HTTP Authentication failed; no valid credentials available
```

**Comment by skabashnyuk** [comment]
@monaka is this ```wss://che-{censored}``` . url to agent or master?

**Comment by monaka** [comment]
Master. I'm trying to fix this.

**Comment by monaka** [comment]
![screenshot 2019-01-30 at 17 47 52](https://user-images.githubusercontent.com/101795/51969432-bb35ef80-24b7-11e9-8614-122e57deea2a.png)

This is not fixed by #12421. I think this will be caused similar code to that. I've already found doubt code in IDE. I'll fix it within a week.

**Comment by rayh** [comment]
Any progress on this?  or recommended work-arounds?

**Comment by monaka** [comment]
@rayh I guess I've fixed this issue on my fork repository. But I've not separated the patch from it yet.

**Comment by rayh** [comment]
@monaka do you have a public che-server image i could test?  or can you point me to your fork?

**Comment by monaka** [comment]
@rayh My fork is at PizzaFactory/che. Even though my image is in the private docker repository, you can check its behavior as it is used in [PizzaFactory/Camino](https://camino.pizzafactory.jp/). The end point is https://che-banco.camino.pizzafactory.jp/. (Don't worry it runs under a freemium model)

**Comment by i524304** [comment]
Hi @monaka 

I am also getting same error and cognitive services speech option is not working for me. While using cognitive servcices speech options for web chat using this sample (https://github.com/microsoft/BotFramework-Samples/blob/master/docs-samples/web-chat-speech/index.html) i am getting this web sockect connection error

Error : WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=xxxxxxxxxxxxxxxxxxxxxxxxx-ConnectionId=2607EB6D18B74798BD56FAA15AE367A0' failed: HTTP Authentication failed; no valid credentials available

Hope you can help and hoping to hear from you soon.

Kind Regards
