### ISSUE TITLE
Deploy Prometheus in Che Helm Chart

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#12059]
### Description

With #11384 we're exposing metrics of the Che server to Prometheus. Our k8s deployment should therefore include a Prometheus server to consume them.

**Comment by sr229** [comment]
I think we should observe if the namespace its deploying has Prometheus deployed already?

**Comment by metlos** [comment]
@sr229 that is a nice suggestion, but IMHO our helm chart is meant for "illustration" purposes, it's not production ready. Therefore, I would not like to complicate the matters with such autodetection.

That said, if you happen to need it, please don't hesitate with a PR.

**Comment by metlos** [comment]
Since the Helm chart now has a way of deploying prometheus and activating metrics collection, I am closing this issue. If you want to change the way how it is done, please raise a new issue or provide a PR.
