### ISSUE TITLE
Make links to docs and support Configurable in Dashboard

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12052]
Currently, it is possible to override things like svg images, loaders, links to support, wish button, links to stacks and workspace docs.

However, some docs links are still hardcoded:

1. Links to Factory docs
2. Links to Stacks docs 
3. Links to Organization docs
4. Docs button in footer

**Comment by garagatyi** [comment]
@eivantsov do you mean rewriting by repacking sources or injecting that in some other way?
