### ISSUE TITLE
Eclipse che noVNC password

### ISSUE THREAD

**Issue by felahgs** [eclipse-che/che#12066]
I have created an android project in eclipse che but can't see the preview of the project. When I click in the link I am redirected to a page for the emulator but it asks for a password.

![image](https://user-images.githubusercontent.com/13948935/49151535-5c0d0080-f2f7-11e8-8ae4-929a64174cbd.png)

**Comment by eivantsov** [comment]
@felahgs it should be `vncpassword`

**Comment by felahgs** [comment]
@eivantsov It worked!! Thank you very much
