### ISSUE TITLE
On the go workspace config: detect if a service that is listening to a port and propose to expose it

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#12061]
### Description

- [ ] Detect process that is listening to some port
- [ ] Once process is detected and port is identified there should be an proposal from IDE to expose service + route for this process automatically.

**Comment by ibuziuk** [comment]
@slemeur @l0rd could you please provide more details

**Comment by garagatyi** [comment]
I discussed this topic with Florent and did some investigations. 
To get a list of listened ports we can call: `cat /proc/net/tcp | grep " 0A " | awk '{print $2}' | cut -d: -f2  | xargs -I %% printf "%d\n" 0x%%`. We can also do this with a simple binary to avoid depending on used linux commands. 
While this works fine for a single container option it doesn't for a multi-container and multi-pod approach.
K8s allows sharing net namespace ([docs](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/)) so we would be able to use a tiny sidecar in every pod, but this didn't work on openshift for me. Any ideas why?
We can also think about other techiques such as mounting binary of such a tool as secret to every container and then call it using the exec from another sidecar, but this is mess. Would be better avoiding it.

**Comment by garagatyi** [comment]
According to [this article](https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-ports-targetport-nodeport-service.html) we can expose a port without declaring it in a pod.
[x] We know how to find if a port is being listened with a command from comments above.
[x] We know how to create service/ingress/route to expose it on a running workspace.
[ ] We need to figure out how to deliver a binary of a tool that can do what that command does (config map, sidecar, etc)
[ ] We need to provide a REST API on Che master to open a port in a workspace
[ ] We need to create something that would periodically call exec sidecar to check if new ports are being listened and call Che master API to open a new port

In this case, a user starts an application and after some time we automatically detect this and open a port and can show a notification about it. 
To improve this we could add a menu item to theia called Ports which:
- would have Open port item
- add a command to open a port to command palette

We can start from a simple approach:
- add default plugin that adds the above-mentioned menu to Theia
- Che master API to open a new port in a workspace

**Comment by l0rd** [comment]
@garagatyi :+1:

**Comment by garagatyi** [comment]
@l0rd it is what I'm suggesting in the simple approach section
> We can start from a simple approach:
> 
> add default plugin that adds the above-mentioned menu to Theia
> Che master API to open a new port in a workspace

1. use Theia plugin and package it as default plugin in Che Theia
2.1. Provide API from master 
OR 
2.2. Implement Service, Ingress/Route creation in a plugin. I like this idea since we don't have to make Che master more complex. But there are security constraints like we have on OSIO. I do think that we can allow this on OSIO. But it seems that SAP guys are even more strict with the permissions to K8s API. We might consider using approach that we would be able to use in their case.

**Comment by benoitf** [comment]
UX could be this one: https://github.com/eclipse/che-theia/pull/51 :-)

**Comment by garagatyi** [comment]
It is an interesting solution that doesn't have issues that 2 suggested ones have. So +1

**Comment by ibuziuk** [comment]
@benoitf this UX looks really great ;-) Are you planning to take care of this issue ?

**Comment by benoitf** [comment]
@ibuziuk yes I think it will be addressed with https://github.com/eclipse/che-theia/pull/51

**Comment by slemeur** [comment]
Fixed by: https://github.com/eclipse/che-theia/pull/51

**Comment by benoitf** [comment]
@l0rd I will work on it (basically it doesn't work because the plug-in is not enabled by default ;-)

**Comment by l0rd** [comment]
Ok thanks @benoitf

**Comment by benoitf** [comment]
@l0rd done, it is now added by default

**Comment by garagatyi** [comment]
@benoitf cool! 
@l0rd can we close this issue?

**Comment by l0rd** [comment]
Yes it's working fine currently so let's close it
