### ISSUE TITLE
Clojure support

### ISSUE THREAD

**Issue by alza-bitz** [eclipse-che/che#1206]
Hi all,

Is there any plugin (paredit, autocomplete, repl, build, etc) for Clojure, either existing or planned?

It would be great to have Clojure support in Che.

Thanks!

**Comment by TylerJewell** [comment]
@alzadude At this time, we are not aware of anyone starting on Clojure support. The current language and related projects that we have seen include Scala, PHP, C/C++, JavaScript, xText.  Codenvy is doing a lot of work around Java including efforts on rewriting the maven plugin to be dynamic, gradle, dynamic Java classpaths, and Java intellisense.

Beyond these efforts, we really depend upon the community making contributions to the core platform. And we'd be happy to include anything Clojure related.  A great place to start would be to get a standard stack + template + commands added into the base assembly. This would allow for the basic edit / debug cycle.  And then more advanced features would probably require custom plugins.

**Comment by TylerJewell** [comment]
Consolidating two similar issues into #1484.

**Comment by staypufd** [comment]
Both this and it's referencing 1484 bug got closed.  So does that mean that there is no intent to add Clojure support?

**Comment by TylerJewell** [comment]
We are only adding in language server support for languages that have had a formal language server created for them. The language server protocol is fairly new and we are hoping that the languages fill out soon. You can see what has been done in the open source realm here - we are adding 1-2 of these / month.

There is no Clojure support, so we will wait for the community to get one packaged. Will close this in the mean time and include this link in the other issues for people who are going through history, and they will not have to scratch their head the way you did.

http://langserver.org/
