### ISSUE TITLE
Theia loses settings after restart workspace.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12069]
### Description
Theia loses settings after restart workspace. For our image Theia stores settings in the folder /home/theia/.theia we have not volume to store this settings, so we lose data after restart workspace.

### Reproduction Steps
1. Create new Theia-dev workspace.
2. Launch workspace.
3. Change some Theia preferences: for example activate multi-root workspace support: File -> Settings -> Open Preferences. In the preference tree open item Workspace and set up parameter "SupportMultiRootWorkspace=true".
4. Open terminal for  Theia container. Your changes should be stored by path: 
```
$ cat /home/theia/.theia/settings.json
{
   "workspace.supportMultiRootWorkspace": true
}
```
5. Stop workspace.
6. Start workspace again.
Expected result: settings.json should exists.
Actual result: we lost settings.json with theia preferences.

> Note: important for internal use.

**OS and version:**    

**Diagnostics:**

**Comment by mmorhun** [comment]
Also it loses state of UI: panels layout, sizes, etc.

**Comment by AndrienkoAleksandr** [comment]
Fixed by @mmorhun  https://github.com/eclipse/che-theia/pull/80
