### ISSUE TITLE
Allow setting the CHE_KEYCLOAK_REALM and CHE_KEYCLOAK_CLIENT__ID in the openshift template

### ISSUE THREAD

**Issue by maleck13** [eclipse-che/che#12065]
### Description
When doing an install from the OpenShift template it would be useful to be able to override this env vars via parameters passed to the template.
I am happy to contribute this change if it is something you guys are happy with having in the template.

**Comment by eivantsov** [comment]
@maleck13 yes, good point. However, currently, realm and client are created from jsons that are ADDed to an image, and some replacements are done there.

Hopefully, we'll replace that with an Operator where provisioning happens as part of a k8s job and container's entrypoint grabs vars with params like realm, client id, user, password etc.

**Comment by gorkem** [comment]
closing
