### ISSUE TITLE
Update support email from wish@codenvy.com to che-dev@eclipse.org

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#12076]
### Description
Currently, support email still points to wish@codenvy.com [1]. Probably it would be better to update it and point to che-dev@eclipse.org

This email is currently used for `Make a wish` functionality. 

![image](https://user-images.githubusercontent.com/1461122/49240838-7bdf1a00-f406-11e8-8e93-65267197b5eb.png)

[1] https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/product.json#L12

**Comment by ibuziuk** [comment]
@slemeur @l0rd @dneary wdyt ?

**Comment by slemeur** [comment]
Yes I think it's a good idea ! Will share the feedbacks to a broader audience!
