### ISSUE TITLE
event-stream-3.3.6.tgz not found in Yarnpkg.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12077]
### Description

See `Diagnostics:` below for more details.
Possibly related on [the recent security incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)

### Reproduction Steps

Build master branch.

**OS and version:**    

Independent

**Diagnostics:** 

```
[INFO] --- maven-antrun-plugin:1.8:run (build-dashboard) @ che-dashboard-war ---
[INFO] Executing tasks

main:
     [exec] yarn install v1.12.3
     [exec] [1/5] Validating package.json...
     [exec] [2/5] Resolving packages...
     [exec] [3/5] Fetching packages...
     [exec] error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
     [exec] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```
curl https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz
{"error":"Not found"}
```

**Comment by rickyduck** [comment]
I'm having the same issue as well

**Comment by wassafr** [comment]
Got it as well

**Comment by iuliust** [comment]
this is due to : [https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)

to solve the issue, add the following to your package.json file :
```
  ...
  ,
  "resolutions": {
    "**/event-stream": "^4.0.1"
  }
```

**Comment by benoitf** [comment]
should be fixed in master now with PR of @monaka https://github.com/eclipse/che/pull/12078

**Comment by wassafr** [comment]
Solved after deleting yarn.lock

**Comment by eddzmaciel** [comment]
if you want to keep the yarn.lock file, just change the name yarn.lockBKP and run yarn install again!

**Comment by SirSerje** [comment]
> it worked for me to delete yarn.lock in `yarn global dir`

and what to do, if I try to deploy it on Travis?

**Comment by monaka** [comment]
I think that just deleting `yarn.lock` will bring potential weakness. You should think how `event-stream` was contaminated.

**Comment by rodrigolopezguerra** [comment]
> Solved after deleting yarn.lock

this is the way to go. Thanks!

**Comment by BeardOfDan** [comment]
This worked for me. Thanks!
(Google brought me here for the same problem, but on a different project)
