### ISSUE TITLE
Start Che Theia on another than 3000 port by default

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#12074]
### Description
Currently we start Theia on 3000 port by default, but that port is often used by some applications. For example nodejs http server uses 3000 port by default. 

The proposal is to start Theia on some less popular port.

**Comment by benoitf** [comment]
+1000

**Comment by slemeur** [comment]
Nice!

**Comment by sunix** [comment]
ok but we are not supposed to run other apps in the theia container

**Comment by benoitf** [comment]
@sunix network is shared across containers
so if you spawn a nodejs app in for example `foo` container with port 3000 as well, it will collide with the process running inside `theia` container

**Comment by benoitf** [comment]
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

what are proposals so for the new 2 ports  number ?

**Comment by mmorhun** [comment]
What about 3100 and 3130 ?

**Comment by sunix** [comment]
i suggest 74314
- 7 for t
- 4 for h (see the h upsidedown)
- 3 for E
- 1 for I
- 4 for A

**Comment by sleshchenko** [comment]
FYI Che uses the following ports for its services in workspaces:
- `4403` - Ws Agent 
- `4411` - Terminal
- `4412` - Exec Agent

**Comment by mmorhun** [comment]
@sunix the maximum port number is 65535, but note, that ports above 32768 (at least for linux) are ephemeral and it is not so good idea to use them.

**Comment by mmorhun** [comment]
Done
