### ISSUE TITLE
"Error: Failed to run the workspace" When opening Che workspaces in Ubuntu VirtualBox

### ISSUE THREAD

**Issue by SharkJ** [eclipse-che/che#12083]
Hi,
I set up docker in an Ubuntu Virtual Box and tried to open a workspace in it. But I got the below output in the terminal: -

```
[DOCKER] latest: Pulling from wsskeleton/che-machine-exec 

[DOCKER] Digest: sha256:db75e01eda82733387ed0e825036762d5dbcc37877b91c97a5e7a35517c9250e 

[DOCKER] Status: Image is up to date for wsskeleton/che-machine-exec:latest 

[DOCKER] 0.3.16-6.14.2: Pulling from eclipse/che-theia 

[DOCKER] Digest: sha256:fc0829aadef52946d4e78ccffc1e748d41577d2e14f53998d32685e4b218b452 

[DOCKER] Status: Image is up to date for eclipse/che-theia:0.3.16-6.14.2 

2018/11/30 10:22:36 ⇩ Registered HTTPRoutes:

2018/11/30 10:22:36 Exec-Machine WebSocket routes:

2018/11/30 10:22:36 ✓ MachineExec api end point(websocket) .... GET    /connect

2018/11/30 10:22:36 ✓ Attach to exec(pure websocket) .......... GET    /attach/:id

2018/11/30 10:22:36 

2018/11/30 10:22:36 ⇩ Registered RPCRoutes:

2018/11/30 10:22:36 Json-rpc MachineExec Routes:

2018/11/30 10:22:36 ✓ create

2018/11/30 10:22:36 ✓ check

2018/11/30 10:22:36 ✓ resize

Error: Failed to run the workspace: "Error response from docker API, status: 400, message: OCI runtime create failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/projects\") set in config.json failed: permission denied": unknown
```

I'm working in an Ubuntu virtual box since it is hard for me to build che in Windows. Since I must turn off Hyper-V when using VirtualBox, I cannot run che in Windows since Docker is not working.

I would be grateful if you would help me overcome this error.

Thank you!

**Comment by skabashnyuk** [comment]
@SharkJ currently Che7 features like "Che machine-exec Service", are not adapted to work on docker. 
Can you try Che6 only workspace or try to run Che on k8s/OpenShift infrastructure.

**Comment by SharkJ** [comment]
I figured out this was due to a problem relate to user permission in the directory I used to store the che repo. When I moved it and the 'test' folder (for `:/data`) to `home` directory, it worked as expected. For anyone who encounters the same problem, I will include the command I used:
**`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che/:/projects -v ~/test/:/data eclipse/che start`**
