### ISSUE TITLE
Change the state of che editor programmatically 

### ISSUE THREAD

**Issue by Mirage20** [eclipse-che/che#1209]
I need to open an existing project file in the che editor and move the cursor to a specific line. How do I achieve this programmatically from an extension? What classes or objects are responsible for this?

Che version: 4.3.0-RC1-SNAPSHOT

Thanks.

**Comment by vparfonov** [comment]
Hello, for opening file you can fire event [FileEvent](https://github.com/eclipse/che/blob/master/core/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/event/FileEvent.java). About navigation to the specific line we do it by calling native JS of Orion Editor for details you cat look at built-codeEdit-amd.js (try fond line 35920 in this script)

**Comment by Mirage20** [comment]
Thanks a lot
