### ISSUE TITLE
[Plugin-registry] Convert icons to svg format

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12095]
### Description
To have better UX in plugin-registry viewer we need to have icons in meta.yaml in svg format.
- try to convert existed plugins/editors icons to svg.
- add validation that all next icons links would be in svg format.

**Comment by mshaposhnik** [comment]
Ok if we can use this Che logo 
 then we have only 1 problem with Theia svg logo. The rest are found:

Che https://www.eclipse.org/che/images/logo-eclipseche.svg
Ditigible https://www.dirigible.io/img/dirigible.svg
Eclipse https://cdn.freebiesupply.com/logos/large/2x/eclipse-11-logo-svg-vector.svg or https://www.advancedinstaller.com/svg/features/iconImportEclipse.svg
Jupyter https://jupyter.org/assets/main-logo.svg
