### ISSUE TITLE
Pushing Eclipse Che Workspace as docker image 

### ISSUE THREAD

**Issue by shubhasismathur** [eclipse-che/che#12108]
### Reproduction Steps
Unable to find the steps or from documentations if its possible to create a docker image out of workspace

**Comment by eivantsov** [comment]
@ShubhasisMathur you cannot do that in Che, however, you may use docker commit from command line on the host where you run Che.

**Comment by ShubhasisMathur** [comment]
So you mean if I have Che on my Local desktop, I can commit the workspace in Docker Repo?
I am working on the Che cloud. BTW, Could you please help me understand the difference between Factory and saving a stack in Che.

Thanks in advance!

**Comment by gorkem** [comment]
Closing as the original question is answered.
