### ISSUE TITLE
Is it possible to fold code or show code outline

### ISSUE THREAD

**Issue by drtangsoverlinevisit** [eclipse-che/che#1210]

**Comment by TylerJewell** [comment]
Yes, you can enable / disable these options in the IDE Profile > Preferences menu.

**Comment by drtangsoverlinevisit** [comment]
@TylerJewell There is no such options and Orion cant fold code just like Codemirror.

**Comment by TylerJewell** [comment]
Doh, you are correct.  I got my wires crossed on the switchover from codemirror into orion.

**Comment by ghost** [comment]
@TylerJewell @drtangsoverlinevisit Orion has code folding. Looks like a bug.

**Comment by drtangsoverlinevisit** [comment]
@eivantsov Orion cant fold code such as class,method,HTML tag or any other features inside a specific langurage.

**Comment by ghost** [comment]
@drtangsoverlinevisit we will soon update to the latest Orion build. If all embedded Orion features will be available in Orion editor in Che.
