### ISSUE TITLE
[Theia] Open in Terminal

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#12103]
Properly handle `Open in Terminal` Theia command in Eclipse CHE.

The feature is already implemented in Theia.
https://github.com/theia-ide/theia/issues/3710

![open in terminal](https://user-images.githubusercontent.com/1655894/49375257-7cc8c200-f70c-11e8-9d39-7e2dc126a375.png)

**Comment by siddu244** [comment]
Hey, iam intrested to work on JAVA tasks or bugs in this IDE project, Can you please assign me appropriate ones if found.

**Comment by AndrienkoAleksandr** [comment]
@siddu244 You can join to the mattermost channel https://mattermost.eclipse.org/eclipse/channels/eclipse-che and ask about tasks.

**Comment by gorkem** [comment]
@vitaliy-guliy Is this still valid?

**Comment by vitaliy-guliy** [comment]
@gorkem yew, we still don't have this feature
