### ISSUE TITLE
DB error when Che 7 plugins list in a workspace is too long

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12117]
### Description
When creating WS with attribute plugins with value `che-machine-exec-plugin:0.0.1,https://raw.githubusercontent.com/garagatyi/brokertest/master/plugins/theia-plugin-test:0.0.1,https://raw.githubusercontent.com/garagatyi/brokertest/master/plugins/theia-remote-plugin:0.0.1,https://raw.githubusercontent.com/garagatyi/brokertest/master/plugins/vscode-test:0.0.1` DB doesn’t allow it cause field is not long enough.
Error on UD:
```
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.0.v20170811-d680af5): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255) Error Code: 0 Call: INSERT INTO che_workspace_cfg_attributes (workspace_id, attributes, attributes_key) VALUES (?, ?, ?) bind => [3 parameters bound] Query: DataModifyQuery(sql="INSERT INTO che_workspace_cfg_attributes (workspace_id, attributes, attributes_key) VALUES (?, ?, ?)")
```

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@sleshchenko @skabashnyuk FYI

**Comment by skabashnyuk** [comment]
>@sleshchenko @skabashnyuk FYI

You reached the limit
```
--Workspace config attributes ---------------------------------------------------------
CREATE TABLE che_workspace_cfg_attributes (
    workspace_id    BIGINT,
    attributes      VARCHAR(255),
    attributes_key  VARCHAR(255)
);
```
Extending it quite a trivial task.

**Comment by garagatyi** [comment]
Yes, I see that the DB scheme doesn't allow big strings.  If this is simple fix may we hope that your team could fix it soon?

**Comment by skabashnyuk** [comment]
BTW you have big key or big value?

**Comment by ibuziuk** [comment]
I believe it would be a great issue to take for `osio` team to better understand internals of plugin brokers

**Comment by skabashnyuk** [comment]
Bug confirmed on che.openshift.io. 
However field ```attributes```
https://github.com/eclipse/che/blob/master/wsmaster/che-core-sql-schema/src/main/resources/che-schema/6.0.0/11__increase_workspace_attributes_values_length.sql#L12

**Comment by mshaposhnik** [comment]
That is for `workspace_attributes`. Need to do same for `che_workspace_cfg_attributes`

**Comment by mshaposhnik** [comment]
FYI https://github.com/eclipse/che/pull/12143 on ci-test

**Comment by mshaposhnik** [comment]
Merged
