### ISSUE TITLE
Add ability to provide own maven archetype in create project wizard

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#12118]
### Description
Lately, the question about generating project from custom maven archetype becomes actual and there is a need for this functionality.

Related issue: https://github.com/eclipse/che/issues/6724

**Comment by gazarenkov** [comment]
+1 for this improvement.
I'd say w/o ability to put archetype of your choice this feature is nearly useless.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/1)

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
