### ISSUE TITLE
Make easily available nightly Theia in Che

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#12119]
### Description
We need to have the newest version of Theia in Che with newest fixes and features to test and use.
We may do it via plugin (just another Theia editor with nightly label).

**Comment by benoitf** [comment]
hello,

current editor is giving current nightly of che-theia image

you're talking about using `next` version of theia instead of being based on the latest tag ?

**Comment by sunix** [comment]
yes next version of theia

**Comment by mmorhun** [comment]
The main idea is to have tomorrow today's changes from master.

**Comment by benoitf** [comment]
@mmorhun master of which project ? `theia`or `che-theia`
