### ISSUE TITLE
Uncaught exception when start eclipse-che.exe in win7 

### ISSUE THREAD

**Issue by cloorc** [eclipse-che/che#1212]
I've installed docker toolbox as [Usage Server](https://eclipse-che.readme.io/docs/usage) and download `eclipse-che-4.0.1` from https://www.eclipse.org/downloads/download.php?file=/che/eclipse-che-4.0.1.zip&r=1. Then I try to start `eclipse-che.exe` following https://eclipse-che.readme.io/docs/usage-windows . 

But I get following problems:
![1](https://cloud.githubusercontent.com/assets/13597105/15144285/0317f812-16e1-11e6-9c6a-fb92a00b7b4c.png)

And when I click `确定`, nothing appears.
![2](https://cloud.githubusercontent.com/assets/13597105/15144290/07602b7e-16e1-11e6-93e8-d0760f3f08d6.png)

My operating system information as following:
![3](https://cloud.githubusercontent.com/assets/13597105/15144388/a7bb3d3e-16e1-11e6-8a31-9429540928ab.png)

Computer name and product id have been erased on purpose, other information is real.

**Comment by TylerJewell** [comment]
@soiff It looks like you are trying to start too many different things.  After you installed Docker Toolbox on your system and unzipped Eclipse Che from the ZIP file, you need to start the Che server.  https://eclipse-che.readme.io/docs/usage#start.  Once you have done this, Che will be available in your browser.  The "eclipse-che.exe" file is not necessary here.  It is an electron client that simulates your browser.  So first get Che to work within your browser and then you can test the electron client.

To simplify this even further and to get a much more recent version of Eclipse Che, you may want to consider running the Vagrant version.  It's easier to setup.  https://eclipse-che.readme.io/docs/usage-vagrant

**Comment by cloorc** [comment]
@TylerJewell Thanks, it's my fault. I'm not doing what docs say exactly. The command should be `eclipse-che.exe . http://localhost:8080`, however, I just double clicked the executable.

But if `eclipse-che.exe` try to ask me for a server URL if I do not provide could be much more friendly.

By the way, what an extraordinary idea `eclipse-che` is.

**Comment by TylerJewell** [comment]
Eventually, when we get some more time, we'll look at having the electron clients automatically start a Che server in the background if it isn't started already.  We may get to that in a year or so.  Thanks for the support on the project!
