### ISSUE TITLE
Get rid of OSIO related code in E2E selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#12128]
### Description
We have OSIO-related legacy code in E2E selenium tests, like the follow [OsioKeycloakTestAuthServiceClient](https://github.com/eclipse/che/blob/6.15.0/selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/core/client/keycloak/OsioKeycloakTestAuthServiceClient.java).

We need to move it to downstream project.

**Comment by rhopp** [comment]
Damn... https://github.com/Katka92/ will work on that, but I cannot assign this issue to her.

**Comment by Katka92** [comment]
I'll work on it, I'll try to remove all login related stuff from upstream to Rh-che. I'll track it in this issue: https://github.com/redhat-developer/che-functional-tests/issues/418 
Once I'll be satisfied with the code, I'll create PR here. Is that OK for you?

**Comment by Katka92** [comment]
Hi, as far as there were other important issues I needed to handle, I have no time to solve that issue. I'm leaving for 3 weeks PTO. I can work on that when I come back (at the end of February) but if somebody wants/needs to fix that, feel free to do that. I have no progress to share there.

**Comment by dmytro-ndp** [comment]
Is not actual so as we are getting rid of all Java selenium tests.
