### ISSUE TITLE
Che Theia loses configuration after workspace stop

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#12131]
### Description
Che Theia doesn't persists config between workspace restarts.
It loses:
 - changes in Theia preferences. (`File` -> `Settings` -> `Open Preferences`)
 - state of Theia UI: panels layout, sizes, etc.

### Reproduction Steps
1. Start a workspace with Che Theia as an IDE.
2. Move, for example, `Files` panel from left to right, disable autosave from `File` -> `Auto Save`.
3. Restart workspace

Expected behaviour: The config is persisted
Actual behaviour: Changes in config are lost: Autosave is turned on again, Files panel is on left side.

**Comment by benoitf** [comment]
@mmorhun https://github.com/eclipse/che/issues/12069 ?

**Comment by mmorhun** [comment]
Closing as duplicate of https://github.com/eclipse/che/issues/12069
