### ISSUE TITLE
Unable to create a Server with UDP protocol

### ISSUE THREAD

**Issue by afonsolage** [eclipse-che/che#12134]
### Description
Adding a server with UDP port exposes a TCP port on docker.

### Reproduction Steps
Add a server on workspace with UDP protocol and check what ports were exposed on docker.

**OS and version:**    
Ubuntu 18.04
Che 6.14.2

**Diagnostics:** 
![image](https://user-images.githubusercontent.com/1176452/49582671-8896cd00-f934-11e8-86a0-ffb5b17bf157.png)

![image](https://user-images.githubusercontent.com/1176452/49582686-98aeac80-f934-11e8-923a-6ee365f89928.png)

**Comment by garagatyi** [comment]
UDP support is not implemented yet, unfortunately.

**Comment by garagatyi** [comment]
I don't think so

**Comment by sr229** [comment]
I think this merits a closure until someone can come up with a Pull Request for UDP support.
