### ISSUE TITLE
Container not starting after doing changes in the workspace

### ISSUE THREAD

**Issue by shubhasismathur** [eclipse-che/che#12130]
### Description
I have created a workspace  on openshift. The workspace is using the sample projects available there. But after the changes, the workspace never comes up... but keep displaying message "Starting" . I have tried adding the volume, Plugins, environment variables, and projects seperately but each time it is not coming up after the change. Please suggest. 
--> 

### Reproduction Steps
Create an account on openshift for eclipse che. Create a workspace after adding a project. Once the container is running, try doing some changes in the workspace. 
After the change, container never comes up

**Comment by skabashnyuk** [comment]
> try doing some changes in the workspace

this is a very broad description. can you describe exactly what you did? 
Like ```rm -r rf /``` ?

**Comment by sr229** [comment]
> `rm -rf /`

I am at loss for words for that.

**Comment by ShubhasisMathur** [comment]
Sorry for the late response. So when I tried doing the changes on the
workspace , the workspace wasn't starting. The changes were very minimal
like adding the environment variables, or updating some files in project
workspace. This happened when I was doing on the cloud account.
However when I have the eclipse che on my local host, i am not facing this
issue. Looks like only in the cloud ee are having this limitations while on
the local host it works absolutely fine.

Thanks
Shubhasis

**Comment by sr229** [comment]
@ShubasisMathur are you sure this only happens in OSO? I tried reproducing but the stacks work fine for me. No problems too in OSIO. Can you try doing the same in OSIO?

**Comment by ShubhasisMathur** [comment]
@sr229 Thanks for trying out. Let me try it and get back here. Thanks for looking at it!

**Comment by sr229** [comment]
@ShubhasisMathur while you're at it, have you used Monitoring in the OpenShift Online console to see if your pods are creating? It should return an error when a pod exec reaches timeout.

**Comment by ShubhasisMathur** [comment]
@sr229 no I havent tried that... so is that the same console in which we view the workspaces etc, or its some other url ?

**Comment by sr229** [comment]
@ShubhasisMathur I believe you have signed up to OSIO, check it on the [OSIO Dashbord](https://console.starter-us-east-2.openshift.com) and go to your che project, it should be named as `<username>-che`, go to monitoring once in the project, and make a project on the Che Dashboard, notice it makes a terminating pod per ws.

Now if your OKD local install or, your OpenShift cluster project is not showing a terminating job, there is something wrong happening.
