### ISSUE TITLE
Reconfigure CI jobs to release plugin brokers

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12140]
### Description
We have a job that releases https://github.com/eclipse/che-plugin-broker.
I a recent PR I changed the code structure, so CI job is outdated now. 
To build the same image that we were building previously in this job:
```shell
docker build -t eclipse/che-plugin-broker:TAG1 -f brokers/che-plugin-broker/Dockerfile .
```
We also need to build Theia broker from the same repo using:
```shell
docker build -t eclipse/che-theia-plugin-broker:TAG2 -f brokers/theia-plugin-broker/Dockerfile .
```
Note that tags are different because these are different implementations of che plugin broker.
Please, also release the following images from commit 94a9e3bca2db73ce520e5bfb12dac6fdde6fd762:
- eclipse/che-plugin-broker:v0.5.0
- eclipse/che-theia-plugin-broker:v0.1.0

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@riuvshin @eivantsov Please, address this issue.

**Comment by riuvshin** [comment]
done
https://hub.docker.com/r/eclipse/che-theia-plugin-broker/tags/
https://hub.docker.com/r/eclipse/che-plugin-broker/tags/

please note that CI pushes only tags based on commit ID
