### ISSUE TITLE
Publish Che Server logs if Eclipse Che deployment is failed on PR QA job

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#12155]
### Description
There is https://ci.codenvycorp.com/job/che-pullrequests-test-ocp job which serves _Eclipse Che E2E tests_ against changes in pull requests on CI.

The build stores Che server logs in archive linked to E2E tests report. It doesn't work if E2E tests hasn't run:
```
mv: cannot move ‘/home/codenvy/workspace/che-pullrequests-test-ocp/ocp_logs/che_server_logs.zip’ to ‘/home/codenvy/workspace/che-pullrequests-test-ocp/selenium/che-selenium-test/target/site/’: Not a directory
```

So, we need to find another way to publish Eclipse Che server logs in addition to storing them into the E2E test report.

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.
