### ISSUE TITLE
Unable to start workspace on codenvy

### ISSUE THREAD

**Issue by saleemepoch** [eclipse-che/che#12151]
### Description

I have no objects in my account. It's completely empty. I am trying to create a workspace and it keeps giving me the following error:

Unable to start workspace: [object Object]
 --- ERROR
Workspace

I am using chromebook/chrome browser.

**Comment by skabashnyuk** [comment]
Are you talking about codenvy.com? Is there anything I can help you to move to che.openshift.io?

**Comment by sr229** [comment]
Heya @saleemepoch, Codenvy is no longer maintained as of 2018, please move to [Che OpenShift.io](https://che.openshift.io).

**Comment by sr229** [comment]
@skabashnyuk I think ths is a Issue closed now, feel free to close it.
