### ISSUE TITLE
Move remote theia dockerfile from wsskeleton to che org

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12162]
### Description
We have a repo that contains code to build Theia slave that runs remote plugins. It also contains Dockerfile for creating an image that can be inherited to build plugins images.
It is hosted in ws-skeleton org https://github.com/ws-skeleton/che-theia-remote-extension
We need to move it to che-theia repo or incubator. I think it should be part of che-theia.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@benoitf FYI

**Comment by benoitf** [comment]
it's already part of moving stuff to che-theia repository. It was the goal of creating che-theia repo.

**Comment by garagatyi** [comment]
yes
