### ISSUE TITLE
Add support of upgrade policies for Che 7 plugins.editors in workspace

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12168]
### Description
Now we update the same version of Che plugins/editors when we want to do a change.
This is not the best approach and we were planning to cache brokering results which would require forbidding updates of existing versions of a plugin/editor.
Instead of that, we could implement versions modifiers with semiver like we do in Theia project since it JS world.
Example of workspace config:
```json
{
   "attributes": {
        "editor": "^org.eclipse.che.theia:0.1.0",
        "plugins":"=org.eclipse.che.plugin1:2.4.5,^org.eclipse.che.plugin2:0.3.0"
   }
}
```

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@l0rd @benoitf @slemeur @skabashnyuk WDYT?

**Comment by garagatyi** [comment]
As far as I understand usually version has its own field and it looks prettier

**Comment by slemeur** [comment]
Nice proposal. 

This sounds nice to me: https://michaelsoolee.com/npm-package-tilde-caret/

**Comment by slemeur** [comment]
It would be important for Beta but critical for GA. That seems also related to the work on the devfile.
