### ISSUE TITLE
[Dashboard]  A machine image path disappears if it has two characters ":"

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12167]
**Reproduction Steps:**
1. Create any workspace through **Dashboard** and open its workspace details page.
2. Open **Machines** tab.
3. Change image path to path with two ':' symbols in it(for example ```myregistryhost:5000/che-server:nightly```).
4. Click on the **Save** button.

**Expected result:**
The ```dev-machine``` image path changed and exists in workspace config.

**Actual result:**
The ```dev-machine``` image path disappeared.
 
**Che version**: 6.16.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_174](https://user-images.githubusercontent.com/7760565/49797132-3fd18080-fd47-11e8-9285-4d6c7488f144.png)

**Screencast:**
![screencast-172 19 20 234-8080-2018 12 11-13-16-34](https://user-images.githubusercontent.com/7760565/49797140-43650780-fd47-11e8-9b57-28cb2a211a4c.gif)

**Comment by BarryDrez** [comment]
@SkorikSergey, @ashumilova I tried with 6.17.0 and 6.18.0.SNAPSHOT, and I am still seeing the problem. Here is the link we use: server.eur.ad.sag:9999/design-server/xx:10.3.0.0

Logs from Chrome:

[che-che.worker-daeirnd06.k8s.eur.ad.zzz-1549033544229.log](https://github.com/eclipse/che/files/2822131/che-che.worker-daeirnd06.k8s.eur.ad.zzz-1549033544229.log)
