### ISSUE TITLE
Che Server is not able to clean up workspace resources if operation is not initialized by user

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12174]
### Description
Che Server is not able to clean up workspace resources if an operation is not initialized by a user (like stopping workspace by activity-manager, or getting rid resources of hanging workspaces after recoverting).
It leads to several issues:
1. A workspace is marked as stopped if inactivity timeout is reached but in fact workspaces resources (Pods, Services, Routes) still, exist and consume resources;
2. If Che Server is crashed while a workspace was in starting/stopping state, then new Che Server is not able to clean up workspace resources. As result the workpace hangs in STOPPING state and user is not able to fix a situation (has not an ability to stop/rerun workspace)

Needed to investigate whether it is possible to use workspace owner OAuth token and whether there is any potential risk with allowed usage token from OAuth provider when Anonymous subject is set.
#### The first scenario:
1. Deploy Che with OAuth provider configured and set inactivity timeout to 10 minutes (it may be done with env var `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT=60000`).
2. Login as user, create and start a workspace.
3. Close the browser tab with opened Che.
4. Check Che Server logs after 11 minutes.
Expected: Logs contain a message that the workspace is successfully stopped by activity manager. Workspace OpenShift resources are removed
Actual: Logs contain a message that there are errors during the workspace stopping. Workspace OpenShift resources are NOT removed.

<details>
<summary>Screenshots:</summary>

![screenshot_20181212_122319](https://user-images.githubusercontent.com/5887312/49863349-c732f880-fe08-11e8-9791-3ce47df15380.png)
![screenshot_20181212_122330](https://user-images.githubusercontent.com/5887312/49863350-c732f880-fe08-11e8-9feb-6fa058919be1.png)

</details>

#### The second scenario:
1. Deploy Che debug enabled.
2. Connect to Che Server with a debugger and set a breakpoint in the end of `KubernetesRuntime#internalStart` method.
3. Create a workspace and start it.
4. Wait until the breakpoint is activated.
5. Go to OpenShift console and force remove Che Server Pod.
6. Wait ~20 minutes (needed time for Che Server to detect hanging workspace and try to stop workspace with default workspace start timeout which is 8 minutes)
7. Check Che Server Logs
Expected: Logs contain a message that the workspace is successfully stopped because the workspace was hanged. Workspace OpenShift resources are removed
Actual: Logs contain a message that there are errors during the workspace stopping. Workspace OpenShift resources are NOT removed.
<details>
<summary>Screenshots:</summary>

![screenshot_20181212_115641](https://user-images.githubusercontent.com/5887312/49862294-8934d500-fe06-11e8-871d-f49b461f0bad.png)

![screenshot_20181212_121109](https://user-images.githubusercontent.com/5887312/49862526-05c7b380-fe07-11e8-94ca-522d5e21dd97.png)

</details>

8. Open dashboard and try to stop workspace
Expected: Workspace is STOPPED.
Actual: Workspace is STOPPING forever and there is no an ability to stop it forcibly. 

<details>
<summary>Screenshot:</summary>

![screenshot_20181212_120759](https://user-images.githubusercontent.com/5887312/49862330-9a7de180-fe06-11e8-892f-44dde28f587d.png)

</details>

**Comment by dmytro-ndp** [comment]
@sleshchenko: nice catch!
The questions:
- what is the default oAuth token expiration timeout?
- how can Che Server renew oAuth token?

**Comment by sleshchenko** [comment]
I don't know for both of questions =)

**Comment by sleshchenko** [comment]
I've added some debug logs to `IdentityProviderConfigFactory` and discovered that issue is caused by `Anonymous` subject BUT NOT expired token
![screenshot_20181217_160743](https://user-images.githubusercontent.com/5887312/50092223-27b1a380-0216-11e9-991b-c6a1a3179d79.png)
So, `activity-checker` and getting rid of hanging workspace functionalities are completely broken on OpenShift infrastructure with OAuth provider configured. Needed to investigate whether there is any potential risk with allowed usage token from OAuth provider when `Anonymous` subject is set.

cc @davidfestal
