### ISSUE TITLE
Eclipse CHE helps to build docker images

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#12175]
Hi,

I would like to know if Eclipse CHE supports build mechanisms in order to deploy docker images. For instance, if I create a Java application using Eclipse CHE, there is already a way to export my code in order to run as a docker container?

If this is not possible, am I able to add this feature adding a new build command in a stack?

Thanks

**Comment by sr229** [comment]
By default, Che does not mount `/var/run/docker.sock` on the containers, so no, you can't deploy images in Eclipse Che.

**Comment by mstavares** [comment]
@sr229 ok, thanks.

Still about docker's, since I have an eclipse che fork and I'm adding new stuff that makes sense for me.
How do I build a docker image of my eclipse che in order to deploy it in own server?

Right now I'm running it like this:

sudo docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v "my_repo_path":/repo -v ~/che:/data eclipse/che-cli:nightly start

Thanks,

**Comment by sr229** [comment]
Read the contribution guide: it should give something useful :wink:

**Comment by mstavares** [comment]
@sr229 Ok, thanks :)

**Comment by mstavares** [comment]
HI @sr229 I have already read the contribution guide, I'm sorry but I didn't found a way to build my own docker image in order to store it on my docker registry.

Could you help me please?

Thanks

**Comment by sr229** [comment]
@mstavares I'm pretty sure there's no Docker registry enabled by default on Docker, use DockerHub and push over there, then use the composefile layout to define your image.

**Comment by mstavares** [comment]
Hi,

I issue is not how should I push the image, but how to create it. As I said above, I'm running CHE passing the repo folder argument where my code is stored.
If I run a dockerfile like this:

FROM eclipse/che-cli:nightly

WORKDIR /repo
COPY source_code_path /repo/.
CMD ["start"] 

My image will not gonna work, and I don't know why. For sure this is not the way to create it.

**Comment by sr229** [comment]
@mstavares while I think your idea is nice, however, you have two fallacies in that:

- your code is stored in Docker volumes of your workspace so its completely uncessary to have a `/repo` folder.
   - Let alone creating it on the che-cli image where it won't be seen by the rest of the server.
- You're invoking the CLI incorrectly, check the CLI source on how it is invoked.

**Comment by l0rd** [comment]
@sr229 @mstavares you can build docker containers from a Che workspace using [buildah](https://github.com/containers/buildah).

@mstavares the CLI has an option to specify a custom che-server image

**Comment by mstavares** [comment]
Hi @l0rd 

I already have the image created, but when I start a workspace the terminal doesn't work neither the option that allows me to create projects.

https://ibb.co/GFJR8jM
https://ibb.co/yVF5VZm

`studio_1  | 2018-12-18 14:52:23,592[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-8080"]
studio_1  | 2018-12-18 14:52:23,633[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 32271 ms
studio_1  | 2018-12-18 14:52:31,207[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 469]    - Workspace 'che/wksp-0lgi' with id 'workspace7g6o38tnhcrm90fo' created by user 'che'
studio_1  | 2018-12-18 14:52:34,535[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 322]   - Starting workspace 'che/wksp-0lgi' with id 'workspace7g6o38tnhcrm90fo' by user 'che'
studio_1  | 2018-12-18 14:55:46,465[uestProcessor-5]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Class path contains multiple SLF4J bindings.` time=`2018-12-18T14:55:46.463494769Z`
studio_1  | 2018-12-18 14:55:46,471[uestProcessor-1]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Found binding in [jar:file:/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib/logback-classic-1.2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]` time=`2018-12-18T14:55:46.464491275Z`
studio_1  | 2018-12-18 14:55:46,481[uestProcessor-3]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Found binding in [jar:file:/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib/slf4j-simple-1.7.24.jar!/org/slf4j/impl/StaticLoggerBinder.class]` time=`2018-12-18T14:55:46.476233176Z`
studio_1  | 2018-12-18 14:55:46,481[uestProcessor-6]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.` time=`2018-12-18T14:55:46.476519985Z`
studio_1  | 2018-12-18 14:55:47,577[uestProcessor-6]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]` time=`2018-12-18T14:55:47.575860659Z`
studio_1  | 2018-12-18 14:56:02,726[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 364]   - Workspace 'che:wksp-0lgi' with id 'workspace7g6o38tnhcrm90fo' started by user 'che'
studio_1  | 2018-12-18 14:57:12,249[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 438]   - Workspace 'che/wksp-0lgi' with id 'workspace7g6o38tnhcrm90fo' is being stopped by user 'che'
studio_1  | 2018-12-18 14:57:21,413[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 478]   - Workspace 'che/wksp-0lgi' with id 'workspace7g6o38tnhcrm90fo' stopped by user 'che'
studio_1  | 2018-12-18 14:57:33,648[nio-8080-exec-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 322]   - Starting workspace 'che/wksp-0lgi' with id 'workspace7g6o38tnhcrm90fo' by user 'che'
studio_1  | 2018-12-18 14:58:10,567[estProcessor-13]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Class path contains multiple SLF4J bindings.` time=`2018-12-18T14:58:10.565473545Z`
studio_1  | 2018-12-18 14:58:10,568[estProcessor-11]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Found binding in [jar:file:/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib/logback-classic-1.2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]` time=`2018-12-18T14:58:10.56643787Z`
studio_1  | 2018-12-18 14:58:10,572[estProcessor-13]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Found binding in [jar:file:/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib/slf4j-simple-1.7.24.jar!/org/slf4j/impl/StaticLoggerBinder.class]` time=`2018-12-18T14:58:10.56671393Z`
studio_1  | 2018-12-18 14:58:10,582[estProcessor-13]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.` time=`2018-12-18T14:58:10.570827534Z`
studio_1  | 2018-12-18 14:58:11,390[estProcessor-13]  [ERROR] [l.ErrorInstallerLogEventLogger 43]   - Installer `org.eclipse.che.ws-agent` error from machine=`dev-machine` owner=`che` env=`default` workspace=`workspace7g6o38tnhcrm90fo` text=`SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]` time=`2018-12-18T14:58:11.387561642Z`
`

Could you help me please?

Thanks,

**Comment by gorkem** [comment]
I think this is not valid anymore, closing, reopen if you need more help
