### ISSUE TITLE
Creating workspace fails with waiting for ingress timeout

### ISSUE THREAD

**Issue by tarioch** [eclipse-che/che#12180]
### Description
I used the helm chart to install che from master. The dashboard starts fine. If I try to create/start a workspace I see the ingress created but che does not seem to see it and the times out after some time.
I'm running in single user mode and have my own domain.

This is running on a kubernetes cluster setup with kubeadm and uses the nginx ingress. It's kubernetes 1.13 running on a linux host.

**Comment by sleshchenko** [comment]
It may be related to https://github.com/eclipse/che/issues/10767

@tarioch Please check where loadBalancer IP is set for Ingresses by nginx ingress backend.

**Comment by sr229** [comment]
Triaged it, and it is indeed related to #10767

the current ingress provider seems need to be fixed for this

**Comment by tarioch** [comment]
I'm actually using nginx ingress without a loadbalancer in kubernetes (using the host network functionality) and this is working fine for everything else, also for the che dashboard. So this sounds like #10767 then, if that functionality is tied to loadbalancer object. I can close this issue and maybe add some comments on #10767
