### ISSUE TITLE
Autogenerate debugger configuration for CHE Theia with help Theia generator.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12193]
### Description
It would be nice to have ability  auto-generate valid debugger configuration for Theia inside CHE. This configuration should be stored to the .theia folder and it should contains in the arguments --port=3130, --hostname=0.0.0.0.
CHE Theia generator - https://github.com/ws-skeleton/che-theia-generator

**Comment by gorkem** [comment]
Sounds like https://github.com/theia-ide/theia/issues/4016

**Comment by tsmaeder** [comment]
Closing as duplicate of https://github.com/eclipse-theia/theia/issues/4016
