### ISSUE TITLE
Application preview url isn't correct for project samples in 'Nodejs and Postgres Stack' stack

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12194]
**Reproduction Steps:**
1. Create a workspace through **Dashboard** from ```Nodejs and Postgres Stack``` with "web-nodejs-simple" project sample.
2. Start the workspace and check that the IDE is fully initialized.
3. Start ```web-nodejs-simple:install dependencies``` command and wait it finished.
4. Start ```web-nodejs-simple:run``` command, click on **previewUrl** and check that application worked.

**Actual result:**
Preview url isn't correct - ```${server.9000/tcp}``` for this stack. 
 
**Che version**: 6.16.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_179](https://user-images.githubusercontent.com/7760565/49999877-984f8a80-ffa0-11e8-8d36-ac4f82c4d0af.png)

**Comment by ibuziuk** [comment]
@jarifibrahim could you please take a look at this issue and provide relevant samples for the new stack as was discussed in https://github.com/eclipse/che/pull/12104#issuecomment-444020997 ?

**Comment by jarifibrahim** [comment]
> @jarifibrahim could you please take a look at this issue and provide relevant samples for the new stack as was discussed in [#12104 (comment)](https://github.com/eclipse/che/pull/12104#issuecomment-444020997) ?

I've raised https://github.com/eclipse/che/pull/12198 to address this
