### ISSUE TITLE
Arm7 Git

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1219]
I am having trouble with the following error when I hit repo button. From the web I think it is from the cacerts file. I tried to fix this on both the host and machine/container. I ran update-ca-certificates on host and ca-certificates-cacert on arch linux container then saved image. I restarted che too after. I don't know if this is related but I cannot push changes to server. I get unauthorized message. I can do this manually from linux console though. I use the servers IP address instead of localhost because I was getting not found with localhost. [https://eclipse-che.readme.io/docs/git](url)

Which cacerts does che use? Host or machince/container? Does it use this location /etc/ssl/certs/java/cacerts?

![image](https://cloud.githubusercontent.com/assets/16562450/15148890/13f4d280-168d-11e6-8816-804d430f9cad.png)

java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

![image](https://cloud.githubusercontent.com/assets/16562450/15148747/488f878e-168c-11e6-8bfd-f31bebdf3647.png)
![image](https://cloud.githubusercontent.com/assets/16562450/15148794/7fe9aba6-168c-11e6-84e9-9fd1258fbdbe.png)

**Comment by ghost** [comment]
Have you gone through the procedure of trusting application after a redirect to GitHub? Also, what is Git version in the container?

**Comment by james10174** [comment]
@eivantsov I don't think I have gone through trusting application after redirect. When and how does this happen.
git version 2.8.2

**Comment by ghost** [comment]
What if you go to Profile > Preferences > SSH and click GitHub icon? It should redirect you to GitHub where you authorize the app.

**Comment by james10174** [comment]
@eivantsov So I finally figured it out. My fault. In your example document you might want to add host needs to be github.com or other url name when you add generate key under ssh->git . Also mention what you just stated to me which is to click the github icon there too. Works now for me. Thanks.
