### ISSUE TITLE
Release of 6.15.1

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12199]
### Description
We would like to have a 6.15.1 release with 
- Devfile local features implementation with schema validation and automated model build https://github.com/eclipse/che/pull/11998
- Add integrity validations for devfile service https://github.com/eclipse/che/pull/12173

**Comment by sbose78** [comment]
If this is something you were doing for the toolchain app creation team, we could defer this. 

We'll use the nightly build to start consuming devfile features.

Will let you know if we hit a wall. So for now, you could abort mission :)

**Comment by riuvshin** [comment]
thanks @sbose78 !
