### ISSUE TITLE
Custom stack not working when combined with the custom plugin

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#12202]
### Description

I have followed the instructions mentioned in the [#12153](https://github.com/eclipse/che/issues/12153) and created a custom stack and custom plugin using the given sample "che-plugin-wizard". The build was successful without any errors yet the stack is not appearing when in the IDE. 

### Reproduction Steps
Mentioned in the issue [#12153](https://github.com/eclipse/che/issues/12153)
Create the stack as mentioned in the issse.
1. Build stack
2. Build created assembly-wsmaster-war
3. Build assembly-main

Run using
`docker run -it --rm -v D:\plugin-wizard-stack-6.15.0\che-plugin-wizard:/repo -v D:\plugin-wizard-stack-6.15.0\che-plugin-wizard-data:/data -v D:\plugin-wizard-stack-6.15.0\che-plugin-wizard\assembly\assembly-main\target\eclipse-che-6.15.0\eclipse-che-6.15.0:/assembly -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.15.0 start --skip:scripts`

**OS and version:**    Windows 10

**Diagnostics:** 
Work space master log
[wsmaterlog.txt](https://github.com/eclipse/che/files/2684467/wsmaterlog.txt)

**Comment by l0rd** [comment]
Hi @LahiruT94!

For your custom stack: adding it to https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json and rebuild che is an option?

For the puglin: for your information we are switching to a new plugin model. We will continue supporting the old GWT based plugins but I suggest you to have a look at the new typescript based plugins. We are working to integrate the new documentation in https://www.eclipse.org/che/docs/. 

For the time beeing here are the resources available right now:

- High Level Architecture: [document](https://docs.google.com/document/d/1HVVzuMZO7qVxEm6FosAhL5XuUzrMe2ooAAsvmnIWB6k/edit#heading=h.muu3eif52lwq)
- Documentation on Plugin APIs on Theia: [documentation](https://github.com/theia-ide/theia/blob/master/packages/plugin/API.md)
- Workshop from Eclipse Con EU, introducing how to create a plug-in: [document](https://docs.google.com/document/d/1hFXTwzIU3MnqcciXH9E7xyUtEJRUeUuJ-e0JlEhTKjo/edit)

Video tutoriasl from CheConf:
- Eclipse Che - Introducing Plug-in API in Theia: [slides](https://docs.google.com/presentation/d/13_avQNaFX2FxTu2we5FVYM2pf56IuAGBCmrrc5b0-zQ/edit#slide=id.g462b0fd476_0_338), [video](https://www.youtube.com/watch?v=yf8_k-G_98U)
- Introducing new extensibility with Eclipse Che: [video](https://www.youtube.com/watch?v=86huMcgoKjk)
- Quick Video showing the hosted mode: [link](https://www.youtube.com/watch?v=1V1jLHqqsH4)

**Comment by LahiruT94** [comment]
I already add the custom stack into https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json and successfully created the stack.

My requirement is to create an ide extention with a inegrated stack. Even though i followed the steps i cannot get the stack into the stacks in the IDE. 

Thank you very much for the resources. I will look into alternative approach.
