### ISSUE TITLE
Is there a way to change dev-machine network ?

### ISSUE THREAD

**Issue by village-way** [eclipse-che/che#12200]
I want to change the dev-machine network from default bridge to host, so i change the stacks.json file and rebuild the source code.
i add this to the compose string
1. `network_mode:host`
2. networks: host

both of the can not take any effect, how can i change the dev-machine network, from the docs. it not support `network_mode` command and `networks`

**Comment by HiDevine** [comment]
@l0rd i want to publish some services in the containers, so the other outside machine can visit that.
if network breaks containers isolation should be avoided, can i fix the port mapping between the host and the container, i want to fix the host port to 4041 the same as the container port?

i do not want to the random port of the host. 

![image](https://user-images.githubusercontent.com/11625846/50193485-cd2d5a00-0371-11e9-9de5-ad85c9b97ca3.png)
