### ISSUE TITLE
Investigate e2e technologies for Thea

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#12204]
### Description
* After quick reviewing the Thea code base - we have 2 technologies around e2e testing.
- First one - based on Webdriverio http://webdriver.io/
- Second one - based on Cypress 
Also we have issues about considering of using Cypress like preferable UI test framework. We should investigate possibilities of the tools and make decision about this

**Comment by benoitf** [comment]
Please note that they might want to get rid of webdriver.io as well.
https://github.com/theia-ide/theia/issues/1118

**Comment by musienko-maxim** [comment]
@benoitf Tnx!

**Comment by l0rd** [comment]
I am sure they are already aware of this investigation but anyway cc @evidolob @ashumilova
