### ISSUE TITLE
Errors during build

### ISSUE THREAD

**Issue by alexVengrovsk** [eclipse-che/che#1220]
I started to see a build failure with errors during attempts to build `Building Che Plugin :: Java :: Extension Java Client`. Few days ago I had no such problems but now there are two errors^

```
               ^
  where T is a type-variable:
    T extends Object declared in method <T>newPromise(RequestCall<T>)
C:\Users\1\IdeaProjects\che_\plugins\plugin-java\che-plugin-java-ext-lang-client\src\main\java\org\eclipse\che\ide\ext\java\client\search\FindUsagesPresenter.java:99: error: getTitleImage() in FindUsagesPresenter cannot implement getTitleImage() in PartPresenter
    public SVGResource getTitleImage() {
                       ^
  return type SVGResource is not compatible with ImageResource
C:\Users\1\IdeaProjects\che_\plugins\plugin-java\che-plugin-java-ext-lang-client\src\main\java\org\eclipse\che\ide\ext\java\client\search\FindUsagesPresenter.java:98: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
```

I am not shure, but it seems to me that the cause of the promlem is [merged PR ](https://github.com/eclipse/che/pull/1201/files)

**Comment by TylerJewell** [comment]
@alexVengrovsk Master could be potentially unstable.  We are doing a lot of work that alters things in two big ways - we are separating out all of the client-side and server-side GWT code into different modules to be built in different ways.  It will dramatically speed incremental builds.  Also, there is a new maven plugin that has changed the nature of what we do with Java classpaths.

@evidolob @vparfonov - they will be the experts to comment here.

**Comment by benoitf** [comment]
@alexVengrovsk you should do a maven build by forcing to update dependencies "mvn -U clean install"

**Comment by benoitf** [comment]
@alexVengrovsk build is currently ok: http://ci.codenvy-dev.com/jenkins/job/che-ci-master/962/

**Comment by alexVengrovsk** [comment]
@benoitf @TylerJewell Thanks. You are right. Everything works fine. My fault. Sorry
