### ISSUE TITLE
Selenium: after creation command isn't exists in CommandsPallete

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12220]
### Description
Sometimes after command creation by ```TestCommandServiceClient```(https://github.com/eclipse/che/blob/029643104cb3b8555a068bc12082b583ebdbd565/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/testrunner/JavaTestPluginJunit4Test.java#L83)  the created command is not visible in Command Pallete(see screenshot). We should clarify reason and fix it.

**Failed selenium tests:** JavaTestPluginTestNgTest, JavaTestPluginJunit4CheckRunSuitesAndScopesTest, JavaTestPluginJunit4Test

**Screenshot:**
![org eclipse che selenium testrunner javatestplugintestngtest preparetestproject_time-1544721265452-millis](https://user-images.githubusercontent.com/7760565/50164127-8a746f00-02ea-11e9-8927-13d58c3eaf38.png)

**Comment by rhopp** [comment]
Not relevant anymore. Closing.
