### ISSUE TITLE
Workspace commands should be in Theia command palette

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12239]
### Description

Currently executing a command form Theia needs 3 steps:

1. Open the command palette
2. Select Run Task
![image](https://user-images.githubusercontent.com/606959/50239104-86675080-03c1-11e9-92f0-9b17c4ab781c.png)
3. Select the command

Instead we should be able to:

1. Open the command palette
2. Select the command

**Comment by vinokurig** [comment]
I'll do it in the vscode way: tasks will be shown by entering `task ` prefix:
 
![screenshot from 2019-01-04 09-34-05](https://user-images.githubusercontent.com/7668752/50677833-ae32f700-1004-11e9-9bfa-b76da636fd95.png)

**Comment by vinokurig** [comment]
It looks like it already works in this way in Theia as well. The other way of viewing task is: 
* enter `Ctrl + P`
* enter `task `

@l0rd @vparfonov can we close the issue?

**Comment by l0rd** [comment]
Thanks @vinokurig. It makes sense to close it for me. @slemeur ?

**Comment by slemeur** [comment]
Yes that's good for me.
Thanks @vinokurig
