### ISSUE TITLE
[che-theia] Ability to kill processes that have been started with a Che command (theia task)

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#12230]
### Description
User should be able to kill process started by a che command (theia task)
Could be
- giving the interactive mode to tasks. BTW this could be usefull when running commands with user interaction ( for instance, `git commit -s` would prompt the user to fill a comment ... etc ... ). To kill a task, user would type Ctrl-c.
- find a way to kill the process with its PID from the user interface: detect the pid that is attached to the `kubernetes exec` and kill it with `kill -9` 

cc @l0rd @AndrienkoAleksandr

**Comment by l0rd** [comment]
@AndreyChizhikov @mmorhun can you please provide more details about your concerns about this issue?

**Comment by AndrienkoAleksandr** [comment]
About kill:
Exec API doesn't provide for us PID to kill the process **inside container.** 
I think that information about exec PID inside container hidden inside API. And it would be nice if API provide for us method to kill exec(the best option), or at list some inspect exec method to get process ID. I think only API has all necessary information to CORRECTLY kill process and child processes, without any side effects(like zombie processes inside container or inside node for example).

Docker API could give for Us exec PID, but this PID is real PID on the system, not inside container.

About kill exec for docker:
Related issue: https://github.com/moby/moby/issues/35703
https://github.com/moby/moby/issues/18635
https://github.com/moby/moby/issues/9098

**Comment by l0rd** [comment]
Thanks for the info @AndrienkoAleksandr but I don't see anything about zombie processes in your link. 

What I mean is that if you start a process with a `docker exec` you can then use `docker exec ps aux | grep "<full_command>"` to find the PID and than `kill` to stop it in a clean way and `kill -9` to give it an hard stop. 

The `ps aux | grep` may not be 100% reliable (you need to filter out grep process itself, you may have false positives etc...) but should work ok for our usecase. At least as starting point.

But in a previous discussion you mentioned that the problem of this approach, in a container, is that some child processes may not be killed. Have I misunderstood? Do you have any example?

**Comment by mmorhun** [comment]
@l0rd I've faced problems with zombie processes, but in other circumstances, not with execs. However, I believe the problem might be still actual. Let me explain. When a process within container is started via exec it is not the main process there obviously. But this process may create child processes. If we kill the process started by exec its children might be still running. The only thing is changed for them - the parent PID. And this parent could be the main process in container (even if not, following might be true as well), and the new parent doesn't have an obligation to do await on its children (it might be not designed to have children process even) and as a result, after a child process finishes, it will become a zombie.
As a solution, in my case, I used supervisor as a main process inside container, which watched children processes and does await, so even if it gets new children it is capable of correct finishing of them. But this solution might be not suitable for out need in case of execs...
At least we need to set limit for number of processes inside container to prevent crash of whole node in the worst case.

**Comment by l0rd** [comment]
@mmorhun killing the child processes is a responsibility of the parent process, not Che's. Using `supervisor` is something that I would avoid in any case.

**Comment by l0rd** [comment]
@mmorhun agreed. And that's exactly what the commands `kill` and `kill -9` do.

**Comment by sunix** [comment]
yep, by default it would just behave like `kill`. If user can't kill it with it, he would use the terminal a `kill -9` himself.

**Comment by gorkem** [comment]
Why is this an enhancement? This is a bug. I can not stop a node express application that I have started with a Task. This sounds like a bug to me. If I close a task terminal window or If I issue a terminate Task command my Task should be killed. No need to over think this. Now I have to drop to command line and issue a `kill PID`. We need the same affect but when the task terminal is closed or when the Terminate Task command is issued.

**Comment by sunix** [comment]
`Ctrl c` works now.

**Comment by azatsarynnyy** [comment]
> Ctrl c works now

so, closing
