### ISSUE TITLE
Release new plugin broker and reconfigure CI

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12255]
### Description
[PR](https://github.com/eclipse/che-plugin-broker/pull/21) adds new broker. We need to release it and push to Dockerhub.
Build new broker with:
`docker build -t eclipse/init-plugin-broker:latest -f Dockerfile.ipb .`
It is called init plugin broker.
Tag v0.6.0

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by riuvshin** [comment]
done

https://ci.codenvycorp.com/view/release/job/release-che-plugin-broker/
