### ISSUE TITLE
Import on ws-agent does not work

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12267]
**Reproduction Steps:**
1. Create and start a workspace through **Dashboard** from any stack with project
2. Wait for the **IDE** is ready to use.

**Expected result:** 
The added project exists in **Project Explorer**.

**Actual result:**
The project is not exist in **Project Explorer**. 
There is error in browser console -
```
Access to XMLHttpRequest at 'http://172.19.20.234:32957/api/project-importers' from origin 'http://172.19.20.234:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
 
**Che version**: Docker 6.16.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshots:**
![selection_181](https://user-images.githubusercontent.com/7760565/50376160-169bd480-0612-11e9-817d-9ea312f8a181.png)

**Comment by mm-camelcase** [comment]
fsda
