### ISSUE TITLE
Update version of eclipse.jdt.ls

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#12263]
### Description
 
Need to update version of eclipse-jdt-ls to 0.30.0 in [che-ls-jdt](https://github.com/eclipse/che-ls-jdt) to avoid build failure.
`[ERROR] Failed to resolve target definition /home/vsvydenko/.m2/repository/org/eclipse/jdt/ls/org.eclipse.jdt.ls.tp/0.27.0.20181114223651/org.eclipse.jdt.ls.tp-0.27.0.20181114223651.target: Failed to load p2 metadata repository from location http://download.eclipse.org/eclipse/updates/4.10-I-builds/: No repository found at http://download.eclipse.org/eclipse/updates/4.10-I-builds. `

It depends on https://github.com/eclipse/che/issues/12262

**Comment by tsmaeder** [comment]
The build failure is due to the fact that builds of jdt.ls are not repeatable: i.e. they depend (necessarily) on integration builds of dependencies that go away after a while.

**Comment by tsmaeder** [comment]
@tsmaeder testing
