### ISSUE TITLE
Make Theia plugin state and workspace state persistent

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#12260]
### Description
We need to make persistent plugin `globalState` and `workspaceState` from the plugin context, so after workspace restart data shouldn't be lost.

**Comment by mmorhun** [comment]
At this moment we need to decide which way we want to go.

My proposal is to use volume for `~/.theia` directory which holds Theia data including all plugin's storage.
This way we'll persist all plugin's related information and Theia global configuration.
However, as far as I know, there is not ability with current Che API to have a volume which is shared between workspaces, so I am going to have a volume per workspaces for such data. @skabashnyuk @sleshchenko am I correct about shared between workspaces volumes?

About encryption. It is nice feature, but I thinks that this is more global problem and should be addressed on higher than Che-Theia level. For example, a flag which turns on encryption for specified volume on infrastructure level.

@l0rd @benoitf would like to see your opinion on this. Thanks.

**Comment by AndrienkoAleksandr** [comment]
> use volume for ~/.theia directory which holds Theia data including all plugin's storage

+1

**Comment by olexii4** [comment]
> use volume for `~/.theia` directory which holds Theia data including all plugin's storage

+1

**Comment by gorkem** [comment]
Would this mean an additional PV per workspace?

**Comment by skabashnyuk** [comment]
What for you want to encrypt this data?

**Comment by mmorhun** [comment]
@skabashnyuk that was request from previous discussion about this issue.
As I described above, I think that this is not Che-Theia component responsibility and should be handled in another issue and in more general way.

**Comment by skabashnyuk** [comment]
>@skabashnyuk that was request from previous discussion about this issue. 

Can you remind me of the motivation part in case if you are going to implement that?

**Comment by mmorhun** [comment]
@skabashnyuk the idea was to protect volume, so if someone access it without Che -  it's encrypted and data cannot be read. But now I realize that the volume is inside cluster, beside user it could be accessed by cluster admins only.

**Comment by mmorhun** [comment]
So, if no objections I am removing encryption section

**Comment by mmorhun** [comment]
@gorkem yes. It is the best solution I see for now form Che-Theia point of view.
I've tried to use symlink to projects volume, but it doesn't work and it will also add an extra directory in projects list, which is not good thing at all.

**Comment by sleshchenko** [comment]
@gorkem @mmorhun 

> Would this mean an additional PV per workspace?

It means using an additional Che Volume per workspace. And whether an additional PV will be used or not - depends on PVC strategy configured on Che Server. 
OSIO uses `common` PVC strategy, that means that all workspaces volumes use the same PVC that is bound to one PV, and multiple volumes are isolated in their own subfolders. 
In the case of `unique` PVC strategy, each Che Volume(projects, Theia storage) will get their own PVC that is bound to separate PV.

**Comment by mmorhun** [comment]
Thanks @sleshchenko for really good clarification.

**Comment by l0rd** [comment]
@mmorhun I understand that we still do not have a good solution for `globalState` right? Because if we don't have it we should probably wait for a solution that would work for both `globalState` and `workspaceState` (using postgre, configmaps, secrets, a che-server PV etc...).

**Comment by mmorhun** [comment]
@l0rd exactly, we do not have it, but for now we may do the state persistent, at least in scope of workspace, which is easy. [Here](https://github.com/eclipse/che-theia/pull/191) is the very simple fix.
