### ISSUE TITLE
Role "user" looks redundant in Eclipse Che keycloak

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#12261]
### Description
We have role **"user"** in keycloak with description _"Eclipse Che user"_:
![user-role](https://user-images.githubusercontent.com/1197777/50373057-4f6b8780-05d9-11e9-85a2-2d9d57290c52.png)

But admin user and user created from UI aren't assigned to role "user" by default, and they work correctly:
- admin user roles by default (Che was deployed by command `che/deploy/openshift/ocp.sh --run-ocp --deploy-che --multiuser`)
![admin-without-user-role](https://user-images.githubusercontent.com/1197777/50372860-504eea00-05d6-11e9-9e59-76e2e59da378.png)

- created from UI user roles by default
![created-test-user-without-user-role](https://user-images.githubusercontent.com/1197777/50372895-e1be5c00-05d6-11e9-82f2-e190f70bff7f.png)

The question: do we really need to have the role "user"?

**Comment by dmytro-ndp** [comment]
[E2E test report|https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1360//Selenium_20tests_20report/] shows no regression for test user without "user" role.

**Comment by dmytro-ndp** [comment]
Redundant keycloak role "user" has been removed.

**Comment by ibuziuk** [comment]
@davidfestal am I correct that rh-che should not be affected by this change ?

**Comment by davidfestal** [comment]
@ibuziuk I'd have to look a bit more into it before answering ...

**Comment by monaka** [comment]
IMO, this should be reverted and it should be added role checks in Che.
In case a user company has already using Keycloak with their realms, they will expect to access control by role. They won't want to create new realm.

**Comment by sleshchenko** [comment]
> IMO, this should be reverted and it should be added role checks in Che.
In case a user company has already using Keycloak with their realms, they will expect to access control by role. They won't want to create new realm.

cc @skabashnyuk @mshaposhnik

**Comment by skabashnyuk** [comment]
@monaka your idea probably makes sense. Can you create an issue to properly discuss and track it?
