### ISSUE TITLE
Language server not initializing with the file extension.

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#12274]
### Description
I have created an IDE extension using che-plugin-wizard for creating a new project and file type and integrated it with a xtext language server as a sidecar. When I run the recipe using swagger it comes to the stack and can be used to create the workspace. (Image also gets pulled and loaded into the workspace) But when I create a file with the extension language server won't start.

Note: If i use the same method for eclipse che without the extention it works.

Is there a way i can get it running in the IDE extension that i have created?abels.

**OS and version:**    Windows 10, EclipseChe tag-6.15.0

**Diagnostics:** 
![initializing](https://user-images.githubusercontent.com/34393074/50391191-edd92380-0766-11e9-9bd5-6e7887b6dc0c.PNG)
![inti 2](https://user-images.githubusercontent.com/34393074/50391192-edd92380-0766-11e9-9fcb-9dc3a65e6877.PNG)

**Comment by slemeur** [comment]
Won't fix in che 6
