### ISSUE TITLE
Groovy editor: How to do it. github che-tutorials/che-tutorial-editor-api or che website?

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#1227]
Hello,

I would like to add a groovy text editor extension to eclipse che. However, I'm quite confused in what basis I should take. Is https://github.com/codenvy/che-tutorials/tree/master/che-tutorial-editor-api the right entry point? Is it up to date? Because it differs from  https://eclipse-che.readme.io/v1.0/docs/editor instructions.
 If I use he last link, I don't understand what means adding groovy.js to the client bundle with @Source("groovy.js") TextResource groovyParserJS(); . In what class?
 And  what project this sentence refers to :"In this example it is located at src/main/resources/org/eclipse/che/ide/tutorial/editor/groovy.js."?

I tried to add the che-tutorial-editor-api to che by:
- adding the extension as a dependency to assembly-ide-war/pom.xml 
- adding it as a GWT inheritance to the Che IDE GWT definition at /che/assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml
- building che assembly
  Then I launch che but nothing has changed. I presume being totally missing the point.

**Comment by ghost** [comment]
This is an example compatible with a legacy system 3.x. 

https://github.com/codemirror/CodeMirror/blob/master/mode/groovy/groovy.js this is the JS file you refer to.

As to building a custom assembly, the steps you have taken are correct. How did you check that the extension is there? Have you created a `.groovy` file to see that syntax highlighting is there and it's the one defined in your css?

**Comment by agnesagnes** [comment]
You mean that the extension will not work with all the recent eclipse che versions, right? So only with 4.0.0-RCs (4.0.0-RC4-SNAPSHOT being the last commit on this repo) ? Are the releases versions synchronized?

**Comment by ghost** [comment]
I mean extensions in this repo are not yet certified for 4.x version.

**Comment by agnesagnes** [comment]
Ok, and the legacy system 3.x is not available? And the last question: do you have any idea of the progress? Maybe you are not the one I should ask, but the authors references in the project! Don't hesitate to tell me that.

**Comment by TylerJewell** [comment]
@slemeur - please ask EclipseSource team to take a look at this request and share @agnesagnes the draft of the new plugin resource center to see if the new examples answer his questions.

**Comment by slemeur** [comment]
Hi @agnesagnes 

We are still working on it, but would definitely appreciate your feedback on the new documentation resources which will be published about authoring Che extension.

The plugin resource center is written as a set of tutorials + sample code, each of them are covering different areas and possibilities for Che extensions.
I recommend you to start by the [introduction](https://eclipse-che.readme.io/v4.3/docs/introduction-1) to get a great overview of the documentation.
The source code of the tutorials are [here](https://github.com/eclipse/che/tree/master/samples).
You'll find instruction about how to setup your developer environment on the [following page](https://eclipse-che.readme.io/v4.3/docs/setup-che-workspace).

Your specific question, about creating a new project type, is covered by the following tutorial:
https://eclipse-che.readme.io/v4.3/docs/project-types

Let us know your feedback.

**Comment by lgas** [comment]
hi,

working with @agnesagnes, i try to implement a groovy editor for che.
Following the tutorial you provide, there are some odd things in section describing creation of CustomEditorProvider :
- Tutorial speaks about impl EditorProvider and method getEditor() when snippet shows impl of AbstractTextEditorProvider and getEditorConfiguration().
- Constructor of CustomEditorProvider need an EditorConfigurationFactory injection but nowhere it explains utility and impl of this class.  

Questions are : 
- Do I need to impl just getConfiguration() editor or impl also getEditor() ? Because I saw in sources that getEditor() is often reimpl.
- How does EditorConfigurationFactory works and do I need 1 ?
  - Why there is no impl of create() method ?

Thanks.

**Comment by TylerJewell** [comment]
@vparfonov @slemeur

**Comment by JonasHelming** [comment]
Hi,

thank you for reporting this. There was a recent change in the base class to simplify the registration of editors. I have just updated the tutorial and the code example. I hope this clarifies the current questions.
In fact, the code could be even simplyfied after introducing AbstractTextEditorProvider, see
https://github.com/eclipse/che/issues/1622

Best regards
Jonas
