### ISSUE TITLE
Devfile Spec documentation generator

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12272]
### Description

Ideally, we should have a way to generate Devfile Spec documentation from Json-schema https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json

So far I found such generators.

- https://github.com/bootprint/bootprint-json-schema
- https://github.com/interagent/prmd
- https://github.com/cloudflarearchive/json-schema-docs-generator
- https://github.com/cloudflare/json-schema-tools 

The goal of this task is to review possible options and decide which one to use or write documentation manually

**Comment by mshaposhnik** [comment]
Additional JSON schema 2 markdown tools:
https://github.com/adobe/jsonschema2md  (NodeJS, Apache 2.0)
https://github.com/AnalyticalGraphicsInc/wetzel (NodeJS, Apache 2.0 )
https://github.com/rdpickard/doctor_jsonschema_md (Python, BSD-3)

**Comment by l0rd** [comment]
@mshaposhnik +1 for the adobe jsonschema2md

**Comment by mshaposhnik** [comment]
OK i checked the all and here is the summary table:

Repository | Result Example | Building complexity
--------------  | --------------------- | -------------------------
https://github.com/bootprint/bootprint-json-schema | https://mshaposhnik.github.io/bootprint/index.html | Low
https://github.com/interagent/prmd | https://github.com/mshaposhnik/spec-docs/blob/master/prmd/schema.md | Low
https://github.com/cloudflare/json-schema-tools | https://mshaposhnik.github.io/cloudflare_json_schema_tools/build/index.html | High
https://github.com/adobe/jsonschema2md  | https://github.com/mshaposhnik/spec-docs/blob/master/adobe_jsonschema2md/devfile.md | High
https://github.com/AnalyticalGraphicsInc/wetzel  | Not working (unsupported schema version) | None
https://github.com/rdpickard/doctor_jsonschema_md  | Not working (unsupported schema version) | None

**Comment by mshaposhnik** [comment]
So the cloudflare & adobe one looks most preferrable, cloudflare lib is generating nice & pretty HTMl docs with ability to add navifation menu at the left etc.

**Comment by mshaposhnik** [comment]
So I propose to start with Adobe markdown tool (as a more widely used for the rest of our docs), but keep an eye on the HTML generator in case we will need more pretty version. @l0rd @skabashnyuk WDYT ?

**Comment by slemeur** [comment]
Nice work @mshaposhnik ! +1 to start with markdown

**Comment by l0rd** [comment]
@mshaposhnik thanks for generating all these samples. That helps :-) 

I agree markdown is the best option and the format we were looking for. Anyway I have a couple of questions:
- your cloudflare/json-schema-tools sample looks like it doesn't have the definitions of all the attributes of the devfile but only the top level ones. Is it a tool limitations?
- adobe/jsonschema2md is not easy to read, for instance [bootprint](https://mshaposhnik.github.io/bootprint/index.html) formatting is nicer. Is there any formatting option when you generate the markdown file?

**Comment by mshaposhnik** [comment]
Thanks for all your responces.
@l0rd yes, cloudflare allows to show all definitions, but default template requires to click on links to expand whole tree:  
![image](https://user-images.githubusercontent.com/1651062/51373806-b8c3b500-1b09-11e9-9c27-ea14a5dbdf0f.png)
BTW we have some fields definitions still missing in schema itself, need to write them.

As of  jsonschema2md, at first sight there is only default templates, need to investigate if there is any customisation options.

**Comment by l0rd** [comment]
@mshaposhnik what's the next step here? We should publish the documentation somewhere like http://redhat-developer.github.io/devfile to be able to share the devfile format with the community.

**Comment by mshaposhnik** [comment]
So, as a result of this issue, several doc generators were tried, and the final decision made is to continue using `adobe/jsonschema2md` library, based on:
- positive user experience working with it;
- resulting doc format (.md) and appearance;
- support and keeping up-to date with json-schema draft versions;
So i propose to close this issue and proceed with implemenation in #12524

**Comment by l0rd** [comment]
@mshaposhnik :+1:
