### ISSUE TITLE
Bad messages in startup log after changing CHE_HOST

### ISSUE THREAD

**Issue by nkolban** [eclipse-che/che#12285]
### Description
On a PC I run che using

```
docker run -e CHE_HOST=1.2.3.4 -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/che:/data eclipse/che start
```

I then stop the PC and start it again and now I have changed my IP address.  I restart Che using:

```
docker run -e CHE_HOST=9.8.7.6 -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/che:/data eclipse/che start
```

The following is logged:

```
WARN: Bound 'eclipse/che' to 'eclipse/che:6.15.0'
WARNING: No swap limit support
INFO: (che cli): 6.15.0 - using docker 18.09.0 / native
WARN: (che cli): 'CHE_HOST=9.8.7.6' from command line overriding 'CHE_HOST=1.2.3.4' from che.env
WARN: Newer version 'rc' available
INFO: (che start): Booted and reachable
INFO: (che start): Ver: 6.15.0
INFO: (che start): Use: http://1.2.3.4:8080
INFO: (che start): API: http://1.2.3.4:8080/swagger
```

The issue I am reporting is the last two lines of the startup log.  They refer to the original IP address used when Che was first initialized and not the current IP address.  Che is indeed working when I connect to http://9.8.7.6:8080.  My guess is that the log messages are pulling their data from the wrong store.

**Comment by slemeur** [comment]
Won't fix as we are deprecating the Docker support in favor of Kubernetes.
The Che 6 docker CLI is going to be replaced by github.com/che-incubator/chectl
