### ISSUE TITLE
Scheduled task can not be configured with `CHE_...` environment variables

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12282]
### Description
Scheduled task can not be configured with `CHE_...` environment variables

### Reproduction Steps
1. Deploy Che with the following environment variables enabled:
`CHE__WORKSPACE__ACTIVITY__CHECK__SCHEDULER__DELAY__S=360`
`CHE__WORKSPACE__ACTIVITY__CHECK__SCHEDULER__PERIOD__S=420`
`CHE_LOGGER_CONFIG=org.eclipse.che.commons.schedule=DEBUG`
2. Check Che Server Logs
**Expected**: WorkspaceActivityManager task is scheduled with delay `360` and period `420`.
**Actual**: WorkspaceActivityManager task is scheduled with defaults which are `180` for `initialDelay` and  `60` for delay (period).

![screenshot_20181226_171224](https://user-images.githubusercontent.com/5887312/50449672-76a3bb00-0931-11e9-8714-9cc831f49eea.png)
![screenshot_20181226_171154](https://user-images.githubusercontent.com/5887312/50449676-799eab80-0931-11e9-9bdd-1caf94688056.png)

**Comment by skabashnyuk** [comment]
can you try single ```CHE_WORKSPACE*``` instead of ```CHE__WORKSPACE*```?
