### ISSUE TITLE
Fix selenium tests from 'factory' package according to factory creation changes

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12295]
### Description
We need to adapt selenium tests from ```factory``` package according to factory creation changes(https://github.com/eclipse/che/pull/12232).
Selenium tests to fix:
- DirectUrlFactoryWithKeepDirectoryTest
- DirectUrlFactoryWithSpecificBranchTest
- DirectUrlFactoryWithRootFolderTest

**Comment by dmytro-ndp** [comment]
This issue duplicates #12278.

**Comment by SkorikSergey** [comment]
This issue adapts existed selenium tests.

**Comment by dmytro-ndp** [comment]
I see. Then it's better to add list of fixing tests in description of issue, to avoid misleading.
