### ISSUE TITLE
Request not respond from che plugin to che stack

### ISSUE THREAD

**Issue by towaish** [eclipse-che/che#12290]
### Description

We are creating a server on the che stack and a plugin with screen to access this server.
Usually, this plugin display screen as expected, but sometimes it can't display not reproducible.

The part of the cord is below.

In UiAction class (extends BaseAction), a URL is gotten from server definition of workspace,
and it is stored to singleton variable 'myUrl'.
This server's port (in stack is for example 4000) is port forwarded, and the value is for example `http://xxx:38999`.

```
macroProcessorProvider.get().expandMacros("${server.mynode}").then(url -> {
	myUrl.setUrl(url);
	editorAgent.openEditor(myVirtualFile, new OpenEditorCallback() {
```

In EditorView implementing class for viewer screen, the URL is gotten from above singleton variable, and it is set to Form constructor.

```
	Frame frame = new Frame(myUrl.getUrl());
	frame.setSize("100%", "100%");
	frame.getElement().getStyle().setBorderStyle(Style.BorderStyle.HIDDEN);
	flowPanel.add(frame);
```

When the viewer screen was nothing display, I checked by devtool of browser, 
the frame (iframe) requested to server (URL: `http://xxx:38999`) but it was  stalled and not respond.
But the server on stack is already running.

it is no reproducible, but when having just started workspace and several minutes, it often occurs.

In this case, what is this cause and measures?

**Comment by slemeur** [comment]
Won't fix in Che 6.
A new extensibility model has been introduced with Che 7
