### ISSUE TITLE
Remote Theia Plugins execute commands in Theia container instead of their own sidecar

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12292]
### Description
When VS Code extension is running as Theia remote plugin it can execute a command in a terminal. At least Kubernetes extension does it to call kubectl commands.
And it always opens terminal to Theia container whereas in our case kubectl is placed inside of a remote plugin container.
We need to figure out:
- how to make terminal be opened in a remote container instead of Theia's one
- how to differentiate cases when we need to execute terminal in a plugin's container and when not.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by tsmaeder** [comment]
Which plugin API is used to execute the command?

**Comment by garagatyi** [comment]
I'm not familiar with theia APIs but after discussions with @evidolob and @AndrienkoAleksandr I think it is createTerminal API (Don't know whether the name is correct or there is some better identifier of the API)

**Comment by l0rd** [comment]
Today we had a call to discuss this issue and here is a summary of what we have discussed :

- Theia plugin API that need localhost access should be modified: when the plugin runs in a sidecar all actions need to be executed in that sidecar.
- We are going to start with the plugin API needed by the k8s VS code extension. That won't fix all VS Code extensions but will help defining a pattern easy to apply to other APIs as well.
- The solution should consist in the the following 4 steps:
   1. Maintain a remote plugins metadata in Theia that contains the sidecar details for each remote plugin (this is tracked by #12392)
   2. Modify the API calls that access localhost to access the remote sidecar container instead when executed called by a remote plugin (this issue)
   3. Support running multiple VS Code extensions in the same sidecar (that's mainly to support jdt.ls extensions and tracked by #12395)
   4. Don't share the plugins folder anymore amongst all sidecars (this is mainly a cleanup step)
- @benoitf will work on the first 2 steps during next sprint, step 3 deserves a dedicated discussion and work should start the sprint after this one.

**Comment by benoitf** [comment]
merged there https://github.com/eclipse/che-theia/pull/42
