### ISSUE TITLE
Will che support additional parameters when it is going to create a new workspace container?

### ISSUE THREAD

**Issue by cloorc** [eclipse-che/che#1229]
In my location, network could be a little problem. And it's time-consuming for downloading all dependencies (also docker images). 

So I think if che support additional parameters when a new workspace container is going to be created, such as `-v /host/.m2:/home/user/.m2`, which can reuse my existing maven local repositories. That's could be so great.

**Comment by ghost** [comment]
You may add the following property to /conf/che.properties:

machine.server.extra.volume=/host/.m2:/home/user/.m2

This should mount your local Maven repo into the container.

**Comment by cloorc** [comment]
That's great. I'll try it tomorrow. Thanks!

**Comment by cloorc** [comment]
@eivantsov Hi, I'm using docker toolbox on win7 64bits. I found that virtual machine `che` already mounted `C:\Users` to `/c/Users`. So I tried to map `/c/Users/user/.m2:/home/user/.m2`, then my workspace could not be started, which status was always `starting`. So I tried to copy my local repository to virtual machine `che` at path `/root/m2` and then I map it as `/root/m2:/home/user/.m2`. This time my workspace could startup, however, when I open my workspace in IDE, it automatically tried to update my dependencies through maven and it told me `error occurs` immediately. Then I attached to my `workspace` container, I found my repository `/root/m2` was erased. Could `che` just use the existing repository instead of remove them first? Finally, I found it could be privilege problem, this folder's owner is `root` but container user is `user`. And I'm going to change the permission before opening my project in IDE.

**Comment by ghost** [comment]
It can be tricky for WIndows and Mac.

What you can do is:
1. SSH into a VM. Do not start any workspaces, just ssh into the machine.
2. Find your maven repo there. Check permissions.
3. Manually run smth like:

`docker run -ti -v $path/to/maven/repo:/home/user/.m2 codenvy/ubuntu_jdk8 bash`

You will get a shell into a container. Navigate to `/home/user/.m2`. Can you see your local maven repo there? If you can, there is probably issues with the host path in this mapping `/c/Users/user/.m2:/home/user/.m2`

I'll run some tests on Windows myself and let you know.

Interesting use case by the way - it's always good not to download half of the Internet each time you update deps.

**Comment by ghost** [comment]
@soiff  `machine.server.extra.volume=/c/Users/Eugene/.m2:/home/user/.m2` worked for me on Windows.

**Comment by cloorc** [comment]
It sounds like individual cases. Let me try it again and post my result.

**Comment by cloorc** [comment]
@eivantsov Hi, could I specify multi extra columns in che.property and how?

**Comment by ghost** [comment]
AFAIK, currently it is possible to specify one binding only
@garagatyi may have more details

**Comment by cloorc** [comment]
@eivantsov Thanks! I'm trying to mount `/c/Users/Giant:/home/user`, all works fine except reject the agent. Actually `che` deploy the agent at `c:\Users\Giant\che`, but it says agent start failed. So I want to specify multiple extra volumn, such as sharing `.ssh` also.

**Comment by ghost** [comment]
`/c/Users/Giant:/home/user` you should not mount the entire user directory. This directory is used to copy ws agent and launch it there.

**Comment by cloorc** [comment]
@eivantsov Yeah, you are right. I'll give it up.

**Comment by cloorc** [comment]
So the solution is specifying extra column at `che.properties` with key `machine.server.extra.volume=/c/Users/Giant/.m2:/home/user/.m2`. I'm going to close this issue.

BTW, this time I mount it success. And I dropped all existing workspaces and remove local `che_workspace*` docker images and reload `codenvy/ubuntu_jdk8`. `.m2` folder has not been erased again. All works great. Thanks a lot!

**Comment by garagatyi** [comment]
yes, it is possible to specify only one binding now

**Comment by cloorc** [comment]
@garagatyi Ok, got it. Thanks a lot!
