### ISSUE TITLE
Theia remote plugin runner should copy env vars when it starts plugin process

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12298]
### Description
Some plugins use environment variables to find information about the system. For example location of JRE by JAVA_HOME env var (as Sonarlint does).
But when we run a plugin as remote env vars are not copied to the plugin process, so a plugin cannot find its dependency and ask a user to install it or configure its value in IDE settings.
We would provide better UX if we allow plugins automatically detect needed values.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@evidolob are you planning to work on that or you are OK if we handle that to speed up delivery of Che 7?

**Comment by evidolob** [comment]
I'm OK to let you handle it

**Comment by garagatyi** [comment]
I figured out that env is not copied when a plugin is running in the main Theia container, not the remote runner. I'm closing the issue since it was a mistake.
BTW @tolusha already working on a solution for copying env for local plugins.
