### ISSUE TITLE
Fix configuration of qa-nightly jobs on CI to run flaky selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#12303]
### Description
There is [an issue](https://github.com/eclipse/che/issues/12129) about exclusion flaky selenium tests from execution by default.
After the corresponded [PR](https://github.com/eclipse/che/pull/12296) will be merged, we need to fix configuration of [che-integration-tests-multiuser-master-ocp-all-tests job](https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp-all-tests/) - to add parameter `--include-flaky-tests`:
```
bash selenium-tests.sh --threads=6 --host=che-eclipse-che.${SLAVE_IP}.${DNS_PROVIDER} --port=80 --multiuser --include-tests-under-repair --include-flaky-tests
```

**Comment by riuvshin** [comment]
done
