### ISSUE TITLE
How git local commits of multiple users are stored when a workspace is being shared by multiple users ?

### ISSUE THREAD

**Issue by vtawniya** [eclipse-che/che#12302]
### Description
If am a single user and I am working on a project using eclipse che with theia ide, I am mounting only the project directory for persistent project data and as the cloned github project when loaded into that directory will also store git related metadata like local commits etc.

So in case I am generating a SSH key for git and loading it into my account, I have following questions:

- Should I mount ~/.ssh for the theia container, so that my ssh key persists ? or is there any other way ?

- In case my workspace is being shared with multiple users, won't my ssh key be accessible to other users if I do the above ?

- And what about the git metadata(local commits and all made by me), as the git metadata is also stored in the same project directory, won't it be a problem if another user using same workspace will make some commits ?

- Your document (...docs/version-control.html) talks about some steps in version control section "SSH keys can be generated at Profile > Preferences > SSH > VCS" , but couldn't find any such thing.

Can we please have a list of paths which needs to be mounted to theia container specified somewhere to understand what paths can allow us to have persistent git data even if the container is recreated.
I couldn't find any such detail specified anywhere, please direct me to the right links if possible. I want to know the data persistence details of theia and other containers, like a list of paths for each container images eclipse che uses and which path is used to store and persist what kind of data.

**Comment by skabashnyuk** [comment]
@vtawniya to make sure we are talking about the same thing. Are you referring for Theia based ide, not GWT based? Right?

**Comment by vtawniya** [comment]
Right. Theia only

> @vtawniya to make sure we are talking about the same thing. Are you referring for Theia based ide, not GWT based? Right?

Yes. Theia only

**Comment by sunix** [comment]
At the moment (Target Che7 + Theia), we are not working on use cases where different users would work on the same workspace. This is what we plan for Che8 AFAIK.

But for futur design, I don't think we would use ssh for git but rather https and github token which would be easier to separate user preferences that would be associated with a user session.
I can imagine in that futur that command line git would inject git preferences through env variables: https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables .
If user would still use ssh we would enforce ssh keys with passphrase

**Comment by rsankarprgs** [comment]
Does che 6.x support user session/preferences as part of the workspace environment?
