### ISSUE TITLE
Simplify Docker Execution

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1230]
This is a tracking issue for a range of improvements that will make it simpler for people who want to run Che within a Docker container using `docker run` syntax.

The specification is:
1. Change the default location of JSON storage for defining workspaces, projects and other internal models from `che.conf.storage=${catalina.base}/temp/local-storage` to `che.conf.storage=${che.home}/storage`.  
2. Change the default Docker run syntax to volume mount the `${che.home}/storage` instead of the tomcat directory.
3. Change the Dockerfile for Che to have the Entrypoint be the Che script and removing some magic around copying library files to be mounted outside of the container.
4. Make it possible for every Che script configuration parameter to be set through an environment variable, so that they can be provided as part of `docker run` syntax with -e override.
5. Allow users to override the automatic determination of the location of $CHE_HOME within the Dockerfile to use a set of Che binaries that are mounted into the container instead of those contained within it.
6. Create a second default Vagrantfile that demonstrates the various usages of running Che in a Docker container.  
7.  Deprecate the `--image` syntax from within the che.sh script.  If you want to run Che as a docker image, you must do it manually with Docker run syntax.
8.  Add "Launch in Cloud" option for Che Docker container.
9.  Add in checks into `che.sh` script to detect if Docker for windows or mac is installed.  If it is installed, skip the `docker-machine` and virtualbox steps, which are unnecessary.

@garagatyi @eivantsov @riuvshin - FYI.  I'll work on issues for all of these.

**Comment by garagatyi** [comment]
2 user may need to read logs also
3 we allow usage of host's docker instead of DIND? Because we need some files on host to continue support of that feature.

**Comment by TylerJewell** [comment]
@garagatyi For reading log storage, I think it's starting to be seen as best practice to give user's the syntax for running a docker exec command to query the logs directly from outside the container.  This is what GitLab does.

@garagatyi Yes - all of these improvements will be using host's docker instead of DIND.  This already exists, but we are simplifying it further.

**Comment by TylerJewell** [comment]
I am closing this issue - most of these issues were resolved in other issues.
