### ISSUE TITLE
Factory with keep directory feature does not work

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12311]
**Reproduction Steps:**
1. Invoke a factory from a specific git repository (for more info see **Eclipse Che** documentation - https://www.eclipse.org/che/docs/che-6/factories-getting-started.html#invoke-factory-for-a-specific-git-repo) by using ```<your path to Che>/f?url=https://github.com/iedexmain1/multimodule-project/tree/master/my-lib``` link.

**Expected behavior:**
After workspace is started check that imported project has only **my-lib** folder.

**Observed behavior:**
All project folders were imported.

**OS and version:**
Che 6.17.0-SNAPSHOT, Openshift

**Failed test:** DirectUrlFactoryWithKeepDirectoryTest

**Additional information:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 12 29-14-08-35](https://user-images.githubusercontent.com/7760565/50538140-5c591f80-0b73-11e9-8cd2-7f087178cbab.gif)

**Comment by sunix** [comment]
@evidolob @slemeur @l0rd this is a che-theia issue, do we want to prioritize this

**Comment by sunix** [comment]
I cannot find/remember what was the git command/option used behind the scene in the GWT app

**Comment by SkorikSergey** [comment]
Not reproduced.
