### ISSUE TITLE
[Theia] Cannot create project by Yeoman wizard 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12315]
**Reproduction Steps:**
1. Create and start workspace from "**Che 7**" stack.
2. Wait for **Theia** started.
3. Click **F1** button and type "yeoman" in Proposal input field.
4. Select "**Yeoman Wizard**" proposal.

**Observed behavior:**
There is error notification(see screenshot).

**OS and version:**
Fedora 28.0, Theia

**Failed test:** TheiaBuildPluginTest

**Additional information:**
**Screenshot:**
![selection_183](https://user-images.githubusercontent.com/7760565/50538903-400faf80-0b80-11e9-9cbe-590164c4fc93.png)

**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2018 12 29-15-37-51](https://user-images.githubusercontent.com/7760565/50538890-ce376600-0b7f-11e9-9560-4cd981a1544f.gif)

**Comment by AndrienkoAleksandr** [comment]
Will be fixed after: https://github.com/eclipse/che-theia/issues/39

**Comment by AndrienkoAleksandr** [comment]
Fixed for che-theia 0.3.19
