### ISSUE TITLE
Why not all of my github repositories are shown in new project page?

### ISSUE THREAD

**Issue by cloorc** [eclipse-che/che#1232]
I cannot find some of my repositories.

![1](https://cloud.githubusercontent.com/assets/13597105/15184291/31cdb214-17c7-11e6-989d-5172df54725b.png)

There's not any of my organization repository showed. But:

![2](https://cloud.githubusercontent.com/assets/13597105/15184491/ff14af3e-17c7-11e6-928f-81257240ebf4.png)

What should I do?

**Comment by ghost** [comment]
@soiff You have got 15 repos. The screenshot shows 7 of them, and it looks like there's place for 8 more if you scroll down.

**Comment by cloorc** [comment]
@eivantsov Hi, I'm afraid it's not. At least none of my organization `soiff-spring` projects has been shown there. But actually I've got 17 repositories, could it some limitation of github?

**Comment by ghost** [comment]
Your screenshot says it's 15 :)

have you tried choosing a particular organization in the dropdown?

**Comment by cloorc** [comment]
There is only one organization `soiff` and nothing changes if I choose organization `soiff` in project creating page. Actually, I have an organization named `soiff-spring` but never showed in this page.

**Comment by ghost** [comment]
What is your role in `soiff-spring` organization?

**Comment by cloorc** [comment]
I'm the owner and my membership is private. I think I have got the reason. Organization in github is independent to owner himself. In other words, if application need to access this organization , it need another OAuth registration.

![1](https://cloud.githubusercontent.com/assets/13597105/15214317/e2b50e80-187e-11e6-92e7-9c371a933013.png)
