### ISSUE TITLE
Custom plugin build failure

### ISSUE THREAD

**Issue by lahirugayanga** [eclipse-che/che#12321]
### Description
I tried creating a custom plugin for Che 6 and when i run the server it gives the following error.
```
Failed to execute goal on project che-plugin-projection-lang-server: Could not resolve dependencies for project org.eclipse.che.plugin:che-plugin-projection-lang-server:jar:6.15.0: Failed to collect dependencies at org.eclipse.che.plugin:che-plugin-projection-lang-shared:jar:6.15.0: Failed to read artifact descriptor for org.eclipse.che.plugin:che-plugin-projection-lang-shared:jar:6.15.0: Could not find artifact org.eclipse.che.plugin:plugin-projection:pom:6.15.0 in ossrh (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project che-plugin-projection-lang-server: Could not resolve dependencies for project org.eclipse.che.plugin:che-plugin-projection-lang-server:jar:6.15.0: Failed to collect dependencies at org.eclipse.che.plugin:che-plugin-projection-lang-shared:jar:6.15.0
```

Folder structure
![pluginsonatype](https://user-images.githubusercontent.com/34393074/50584705-33989900-0e97-11e9-96a4-2addfdb32711.PNG)

**OS and version:**    Che 6 Windows 10

**Diagnostics:** 

Complete log --> [Log.txt](https://github.com/eclipse/che/files/2720205/Log.txt)

**Comment by skabashnyuk** [comment]
>Could not find artifact org.eclipse.che.plugin:plugin-projection:pom:6.15.0

Looks like this is your custom plugin. you forget to build/include ```org.eclipse.che.plugin:plugin-projection:pom``` please revise your pom(s) and build sequence.

**Comment by LahiruT94** [comment]
I did it and fixed it. Now i get `Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:analyze-only (analyze) on project che-plugin-projection-server: Dependency problems found -> [Help 1]`
Full log - 
[logplugin.txt](https://github.com/eclipse/che/files/2739481/logplugin.txt)

**Comment by skabashnyuk** [comment]
```
[INFO] --- maven-dependency-plugin:3.0.1:analyze-only (analyze) @ che-plugin-projection-server ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.eclipse.che.core:che-core-commons-inject:jar:6.15.0:compile
[INFO] ------------------------------------------------------------------------
```
 means that you should remove :che-core-commons-inject from che-plugin-projection-server  pom.xml

**Comment by LahiruT94** [comment]
Thanks it worked, but afterwards i build the plugin completely and then linked the `che-plugin-projection-lang-server` and `che-plugin-projection-lang-shared` into `assembly-wsagent-war` and then build the projetcs in the following order.

1. `plugin-projection`
2. `assembly-wsagent-war`
3. `assembly-main`

But when i run Che it doesnt appear in the IDE. Am I including dependencies in the correct modules? Or is it some other problem?

**Comment by LahiruT94** [comment]
These are my plugin sources
[plugin-projection.zip](https://github.com/eclipse/che/files/2744308/plugin-projection.zip)
