### ISSUE TITLE
Node.js App with TypeScript Debugging

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#12339]
This issue is related to #10669.
We need to debug application made by TypeScript with Node.js.

I saw the issue #12170 and I know TypeScript and Node.js debbugger will be included in Eclipse Che 7.

At the moment, however, I need to debug application using Eclipse Che 6.x.
Is there any plan for supporting TypeScript and Node.js debugger in Eclipse Che 6.x?

**Comment by eivantsov** [comment]
@hsgwd there are no such plans. Nodejs debugger is implemented for Che 7 in Theia IDE
