### ISSUE TITLE
Update list of Commands in Runtime without workspace restart

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12333]
### Description
It looks wired at the moment if I create new one or update existed command in WorkspaceRuntime it not updated. For getting actual state need to restart workspace

**Comment by l0rd** [comment]
That may be part of #12710 (as a new subtask: sync workspace config modifications in Theia tasks)

**Comment by skabashnyuk** [comment]
@metlos suggested also to send some event over websocket.
