### ISSUE TITLE
It is not possible to run several workspaces with remote plugins

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#12336]
### Reproduction Steps
Run several workspaces all workspace should have remote plugins

**OS and version:**    
```
16:47:23] tolusha@fractal ~ $ minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+d0a16e1-79)
DiskUsage:  44% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 1.445 GB (used by oc binary, ISO or cached images)
```

**Diagnostics:** 
![screenshot from 2018-12-29 15-14-40](https://user-images.githubusercontent.com/1640675/50693701-5d40f400-1040-11e9-88c0-55a84542594e.png)

**Comment by garagatyi** [comment]
Both #12238 and this issue are fixed
