### ISSUE TITLE
[Che 7] Cannot add new env variable, server or volume to Che 7 stack

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12337]
### Description
This issue reproduces only when all 3 machines("ws/theia-ide", "ws/che-machine-exec" and "ws/dev") exist in **Machines** list.

**Reproduction Steps:**
1. Create and start workspace from "**Che 7**" stack.
2. Open this workspace details page.
3. Click on **Env Variables** tab.
4. Select **ws/dev** machine from machines list.
5. Click on **Add Evn Variable** button.
6. Create a new variable in opened "**Add a new environment variable**" form and click on **Add** button.

**Expected behavior:**
"**Add a new environment variable**" form closed and the new variable added to variables list. **Save** changes button in visible and enabled.

**Observed behavior:**
"**Add a new environment variable**" form is still opened. New variable is visible in variables list but not added to workspace config.

**OS and version:**
CHE 6.17.0-SNAPSHOT, Fedora 28.0

**Additional information:**
**Screencast:**
![screencast-che-eclipse-che 172 19 20 234 nip io-2019 01 04-17-15-41](https://user-images.githubusercontent.com/7760565/50695152-8499c000-1044-11e9-8619-897cddb872eb.gif)

**Comment by AndrienkoAleksandr** [comment]
@ashumilova I guess it could be closed?
