### ISSUE TITLE
Is there a way to skip pull docker images if there is already existing the target?

### ISSUE THREAD

**Issue by cloorc** [eclipse-che/che#1234]
I'm using `Eclipse Che Server` with docker through docker toolbox on win7 64bits.

But I found each time I do start my workspace it will try to pull `codenvy/ubuntu_jdk8` from `docker.io`, which would be very time-consuming. Could I just skip that if it is already there?

By the way, I'm sure there are proper docker images existing. Command `docker images` showing like this:

`codenvy/ubuntu_jdk8                     latest              37a7da3b7edc        5 weeks ago         685 MB`

Both virtual machine `default` and `che` have this docker image already.

**Comment by ghost** [comment]
This is not how it's supposed to work. If there's the right docker image previously pulled, Docker should not download it from DockerHub.

What Che version is in question?

**Comment by cloorc** [comment]
@eivantsov My che version is `4.2.0`. Is there a possibility that command `docker pull codenvy/ubuntu_jdk8` will be executed before starting a workspace container? I'm new to `che` source and I'm not sure the logic about this.

**Comment by ghost** [comment]
Yes, by default we check if there's a newer image on Dockerhub. If the image hasn't changed (and it hasn't) then Docker will just continue. 

I'll test it myself on Windows. Odds are that this is a VM/VirtualBox issue, where the VM does not save its state.

What is the right succession of steps to take to be able to reproduce the issue?
1. Start Che. 
2. Start a workspace.
3. Stop a workspace.
4. Re-start a workspace?

Or do I have to stop and start Che server?

**Comment by cloorc** [comment]
@eivantsov I've saved the docker image `codenvy/ubuntu_jdk8` and load it in virtual machine `default` and `che`. Afterwards I try to create a new workspace and start it, then I found my `che` retry to pull it from `docker.io`.  But if my network fails, such as `SSL Handshake` failure, although it will tip for this error, but it will use local image and try to reject agent successfully. In other words, if network fails, `workspace` could be started up successfully. I've no idea how to reproduce this issue. I have loaded images yesterday but I found it's not ready this morning(maybe 10 hours later).

Actually, in my location, network could be a little problem. It's time-consuming at least.

Could `che` check the images version and only try to pull images if local is incompatible or it does not exist locally?

**Comment by ghost** [comment]
@soiff  yes, you may use this parameter in /conf/che.properties:

`machine.docker.pull_image=false` (by default it's true)

**Comment by cloorc** [comment]
It seems like great, I'll try this. Thanks a lot!

**Comment by cloorc** [comment]
Set `machine.docker.pull_image` to `false` is an ideal solution for this problem.
