### ISSUE TITLE
Add plugin menu to custom assembly

### ISSUE THREAD

**Issue by phuongtailtranminh** [eclipse-che/che#12351]
### Description
I'm trying to add the custom [plugin menu](https://github.com/che-samples/che-plugin-menu) to the Che source code che/plugins directory in order to build the custom assembly and to enable SDM (SuperDevMode) feature.

After I rebuilt the plugin, ide, assembly-ide and assembly-main module and re-mount it to the Docker, nothing happens.

I managed to run it as standalone (without the full Che source code). Not sure what step did I miss?

### Reproduction Steps
- Create new module in the che/plugins
- Add che-sample-plugin source code to it
- Add dependency to che-ide-full/pom.xml
- Add dependency to che/pom.xml
- Build plugins module
- Build ide module
- Build assembly-ide module
- Build assembly-main module
- Re-mount

Plugin structure
![image](https://user-images.githubusercontent.com/12473996/50818440-87085c80-1359-11e9-8d11-177a0985afac.png)

**OS and version:**    
MacOS and Che 6

**Diagnostics:** 
Build success without error

**Comment by mkuznyetsov** [comment]
@phuongtailtranminh Hello, can you please answer these questions to help narrow down the problem.

1) Can you make sure that you are running your Che with newly built assemblies, and not the one that comes from original Che's Docker image? 
You can check if that's the assembly that is build by you by going in Help -> About -> Build Details -> compare build date to build date of your assembly IDE

If you are mounting your Che installation by rebuilding the image, make sure you the right image tag to start Che.
If you are mounting your Che installation by using /repo or /assembly mounting, make sure it points to the correct path as well (unlike `/repo`, `/assembly` points to the longer path like `/home/user/che/assembly/assembly-main/target/eclipse-che-6.17.0-SNAPSHOT/eclipse-che-6.17.0-SNAPSHOT`) .


2) If it is indeed running Custom assembly, but the plugin is just not there, you may check the following:
in `/che/ide/che-ide-gwt-app/target/generated-sources/gen/org/eclipse/che/ide/client/inject/IDEInjector.java` file, see if there is your SampleMenuGinModule is listed.

**Comment by phuongtailtranminh** [comment]
@mkuznyetsov , Hi

Below is the build info from running IDE
![image](https://user-images.githubusercontent.com/12473996/50821353-925f8600-1361-11e9-9934-275b451f01da.png)


Command to run the custom assembly and its log

![image](https://user-images.githubusercontent.com/12473996/50821207-37c62a00-1361-11e9-97ce-d1c950810109.png)

There is no SampleMenuGinModule inside `/che/ide/che-ide-gwt-app/target/generated-sources/gen/org/eclipse/che/ide/client/inject/IDEInjector.java`

![image](https://user-images.githubusercontent.com/12473996/50821287-67753200-1361-11e9-916a-771b47411994.png)

**Comment by mkuznyetsov** [comment]
1) do you rebuild `che-ide-full` AND `che-ide-gwt-app` modules? first module is like a place to define all GWT modules, while second is where actual GWT compilation occurs.
2) does your `SampleMenuGinModule` have `@ExtensionGinModule` annotation?

**Comment by mkuznyetsov** [comment]
Thing is, I just did the same, copied plugins sources to che, and built `che-ide-full`, and `che-ide-gwt-app`, and after that, the plugin's extension had appeared in that generated class, that lists all GIN modules `/che/ide/che-ide-gwt-app/target/generated-sources/gen/org/eclipse/che/ide/client/inject/IDEInjector.java`

in `che-ide-full` do you have declared correct dependency, of `gwt-lib` type?
```
        <dependency>
            <groupId>org.eclipse.che.sample</groupId>
            <artifactId>plugin-menu-ide</artifactId>
            <type>gwt-lib</type>
        </dependency>
```

**Comment by phuongtailtranminh** [comment]
@mkuznyetsov , Hi

Below is my customized repo, could you please help to take a look?

https://github.com/phuongtailtranminh/eclipse-che

**Comment by mkuznyetsov** [comment]
@phuongtailtranminh oh, I get it now
`che-ide-full` and `che-ide-gwt-app` are not listed in `ide` pom.xml, and so they won't be built if `mvn clean install` is invoked from that directory

You'd have to build those modules individually,
or rebuild Che as a whole, as these modules are listed in Che's main pom.xml

As for the rest, your order of building modules is correct. 
`plugin-menu` -> `che-ide-full` -> `che-ide-gwt-app` -> `assembly-ide-war` -> `assembly-main`

**Comment by phuongtailtranminh** [comment]
It's worked!! Great thanks <3
