### ISSUE TITLE
Cannot publish_plugin if registry pod has completed

### ISSUE THREAD

**Issue by andrewazores** [eclipse-che/che#12355]
### Description
If the original registry pod has been completed - for example, if it has been evicted as happened in my case - then the publish_plugin command fails with an error message like:

```
error: cannot exec into a container in a completed pod; current phase is Failed
```

I was able to resolve this by visiting my OSO Console and deleting the first, completed Pod in my che-plugin-registry DC's first Deployment. There was already a second Pod in the Deployment with 1 running replica. After deleting the older inactive Pod, publish_plugin ran without issue.

Does something in the chain look for the "first" deployed Pod and need to reverse order them by age?

### Reproduction Steps
"Complete" the registry pod (unsure how to force this manually), then proceed to attempt publishing a plugin project to the local registry.

**Comment by garagatyi** [comment]
@mshaposhnik FYI

**Comment by slemeur** [comment]
Won't fix in Che 6 - as the extensibility model has been revamped in Che 7
