### ISSUE TITLE
Workspace Agents HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12350]
### Description
When running Eclipse Che (6.16.0 and nightly) using Docker for Windows 10 the workspace agents do not properly resolve the API and websocket resources. Running version 6.15.0 seems to work okay.

### Reproduction Steps

**OS and version:**    
Windows 10.0.17134 Build 17134
Docker Desktop Version 2.0.0.0-win81

**Reproduction steps:**
1. Launch eclipse che: `docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/che:/data eclipse/che:nightly start`
2. Browse to `http://localhost:8080/dashboard/#/diagnostic` and click `Run Diagnostic`
3. Browsing to the agent URI directly (in this case `http://localhost:32776/api`) shows that the server is running but not serving the proper content.

### Eclipse Che Diagnostic error

![image](https://user-images.githubusercontent.com/1326577/50789372-a8961500-1281-11e9-9148-1f21c7256a54.png)

### Missing resource when browsing directly to the Workspace Agent URI:

![image](https://user-images.githubusercontent.com/1326577/50789441-e4c97580-1281-11e9-9578-c2639f639d01.png)

**Diagnostics:** 
[che-win-workspace-agent-issue.txt](https://github.com/eclipse/che/files/2734045/che-win-workspace-agent-issue.txt)

**Comment by eivantsov** [comment]
If you open browser dev console, you will probably see failed requests to $host:$port where $port is a port from the ephemeral port range

**Comment by mmcparlane** [comment]
I gathered output for the nightly version and also the 6.15.0 version. Looks like the likely suspect is:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:32793/api/project-type. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

When I browse to the [Firefox document](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default) on this issue, seems like something needs to be enabled in Tomcat to permit access to this resource.

**From nightly**
![image](https://user-images.githubusercontent.com/1326577/51045850-388dd480-158a-11e9-8a3f-5b56b7e1573d.png)

**From 6.15.0**
![image](https://user-images.githubusercontent.com/1326577/51045916-607d3800-158a-11e9-85e8-7da2950f255e.png)

**Comment by mmcparlane** [comment]
This seems to be only an issue with local development environment; it has been  a bit puzzling since everything seemed to work with v6.15.0 but definitely not a show stopper. I'll try to see what I can come up with as a workaround.

**Comment by mkuznyetsov** [comment]
@mmcparlane yes, seems like "localhost" is not an allowed origin in mozilla/chrome, by default at least .
And your Che on Windows w/Docker seems to use "localhost" as api endpoint, which is then used as "origin". 

You may try running Che on Kubernetes, that comes with Docker on Windows, see if it works for you.

**Comment by diogoburgosr** [comment]
I've got a similar problem.

- Windows 10 Enterprise 2016 LTSB
- Docker For Windows CE - Version 18.06.1-ce-win73 (19507)
- Ran the command according to _Single-User: Installation on Docker_ page: 
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v <path>:/data eclipse/che start`

Output:
```
INFO: (che start): Ver: 7.0.0-beta-5.0
INFO: (che start): Use: http://localhost:8080
INFO: (che start): API: http://localhost:8080/swagger
```

Then I started using Che at localhost:8080 but It couldn't load a sample Java project. After struggling with corporate proxy for days, nothing worked. Noticed the CORS problem using Chrome console, specially `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:32793/api/project-type. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`  as pointed out by @mmcparlane .

Then I noticed that _che.env_ file sets CHE_HOST=10.0.75.2 so I started using this IP to access Che. The project finally loaded.

So, the INFO is misleading. Maybe improving the get_display_url() method at library.sh would help?
https://github.com/eclipse/che/blob/6ba43f00d8908b7f26f10497799e1847b652a698/dockerfiles/base/scripts/base/library.sh#L35-L49

**Comment by mmcparlane** [comment]
After playing around with Eclipse/Che using Docker for Windows and Kubernetes for Windows I found there were several issues with the underlying filesystem layer that are outside of Eclipse/Che control. I think with the following changes there will be much better Windows support built-in using [WSL 2](https://engineering.docker.com/2019/06/docker-hearts-wsl-2/).

**Comment by gorshkov-leonid** [comment]
😞

**Comment by gorshkov-leonid** [comment]
I've just tried to run under Ubuntu 19.04 - not WSL. Workspace has not started. 

For next  command with localhost I have error 403:
```
 sudo docker run -p 18080:8080 -e CHE_HOST=localhost --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/acer/1:/data eclipse/che-server:6.19.6   - 
```

For next  command with ip usage I have error 403:
```
 sudo docker run -p 18080:8080 -e CHE_HOST=172.18.0.1 --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/acer/1:/data eclipse/che-server:6.19.6   - 
```

For next  command with disabled CORS I have 200:
```
 sudo docker run -p 18080:8080 -e CHE_HOST=localhost -e CHE_CORS_ENABLED=false -e CHE_WSAGENT_CORS_ENABLED=false --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/acer/1:/data eclipse/che-server:6.19.6   - 
```
, but at the same time I can see error in console (Firefox):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows
reading the remote resource at https://some-url-here. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
In addition, I tried to use `CHE_CORS_ALLOWED__ORIGINS=*` and `CHE_CORS_ALLOW__CREDENTIALS=false` but It did not help me, but che-master did not run at all with an error that says that `supportsCredentials=true`  cannot be used with origin  `*`.

As a result, it does not matter which OS I is used and I have no way to run Eclipse Che 6.19.0 in single-mode under docker locally.
