### ISSUE TITLE
"We found a potential security vulnerability in one of your dependencies." warning at GitHub page

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#12354]
### Description
There is warning at [Eclipse Che github main page](https://github.com/eclipse/che):
> We found a potential security vulnerability in one of your dependencies.

![screenshot from 2019-01-08 14-30-57](https://user-images.githubusercontent.com/1197777/50833680-55d85e00-1352-11e9-92cd-d6b9a01850ae.png)

It was linked to the **react-dom**, opened recently in [dockerfiles/theia/e2e/src/package.json](https://github.com/eclipse/che/blob/master/dockerfiles/theia/e2e/src/package.json) file.

**Comment by benoitf** [comment]
report was
```
low severity
Vulnerable versions: = 16.0.0
Patched version: 16.0.1
React applications which rendered to HTML using the ReactDOMServer API were not escaping user-supplied attribute names at render-time. That lack of escaping could lead to a cross-site scripting vulnerability. This vulnerability can only affect some server-rendered React apps. Purely client-rendered apps are not affected.

This issue affected minor releases 16.0.x, 16.1.x, 16.2.x, 16.3.x, and 16.4.x. It was fixed in 16.0.1, 16.1.2, 16.2.1, 16.3.3, and 16.4.2.
```

but in package.json or yarn.lock we specify to use 16.7.0 version which is already including the fix so report is not accurate AFAIK.
