### ISSUE TITLE
Network connections fail even with setenforce 0 and latest docker version [kind/bug]

### ISSUE THREAD

**Issue by umenthum** [eclipse-che/che#12369]
### Description
Che fails to start on Centos 7 with latest version of Docker even with SELinux disabled (setenforce 0)

### Reproduction Steps
\> sudo setenforce 0
\> sudo systemctl start docker
\> docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v <omitted>:/data eclipse/che start
WARN: Bound 'eclipse/che' to 'eclipse/che:6.16.0'
INFO: (che cli): 6.16.0 - using docker 18.09.1 / native
WARN: Newer version 'rc' available
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]

ERROR: Try 'docker run <options> eclipse/che info --network' for more tests.

**OS and version:**    
CentOS Linux release 7.6.1810 (Core)
Kernel 3.10.0-957.1.3.el7.x86_64
Docker version 18.09.1, build 4c52b90 (newest I get from whatever default/standard yum repos I use)

**Diagnostics:** 
\> run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v <omitted>:/data eclipse/che info --network                                            
WARN: Bound 'eclipse/che' to 'eclipse/che:6.16.0'
INFO: (che cli): 6.16.0 - using docker 18.09.1 / native
WARN: Newer version 'rc' available
INFO: 
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: (che network): eclipse/che-ip:6.16.0: <omitted>
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (<omitted>): Connection failed
INFO: (che network): Server  => Workspace Agent (External IP): Connection failed
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded

Thanks in advance

**Comment by eivantsov** [comment]
@umenthum I'd check if the ephemeral port range isn't filtered

**Comment by umenthum** [comment]
How would I do that? I've tried various combinations of --expose=8080, -P, -p 8080:8080, -p with other port numbers combined with -e CHE_PORT (as described in https://www.eclipse.org/che/docs/che-6/docker-single-user.html#run-without-cli) and I get the same results or, specifically with -p 8080:8080 I get the following error:
         port 8080 (http):        [ALREADY IN USE] 

ERROR: Ports required to run che are used by another program.

This seems strange since I'm not using 8080 for anything else, it seems that merely publishing the port makes it unavailable to the che server.

**Comment by eivantsov** [comment]
The problem is that services cannot reach other from within their containers using an external IP:PORT.

Try to check if the empeheral port range is opened, and open it if it's not.

**Comment by umenthum** [comment]
I'm not clear on what you mean by the port range being open, is this a docker setting or something in my host OS? I'm just trying to run the server locally on the same machine that my web browser is running on so I shouldn't need to open the ports to the outside world right? How exactly would I check if the port range is opened? Thanks for the help.
