### ISSUE TITLE
Workspaces resources are not deleted after helm delete

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12360]
### Description

When I try to stop che server using the command `helm delete` as described in the [documentation](https://www.eclipse.org/che/docs/che-6/kubernetes-multi-user.html#delete-che-deployment) the running workspaces are not stopped: pod, services, ingress and other kubernetes resources aren't deleted.

### Reproduction Steps

- Start single user Che on minikube using helm
- Start a workspace
- Stop Che with `helm delete che`

Expected result: workspace pods, services and ingress should be deleted
Actual result: workspace kubernetes resources are still there

**Comment by rsankarprgs** [comment]
helm delete **--purge** che 
does the above command help?

**Comment by l0rd** [comment]
@rsankarprgs no `--purge` doesn't help.

**Comment by rsankarprgs** [comment]
Ok.. Sorry it dint help. We are using 6.14 and it is working fine for us. Could be an issue with 7.

**Comment by sleshchenko** [comment]
Probably hooks can do this work https://github.com/helm/helm/blob/master/docs/charts_hooks.md
