### ISSUE TITLE
Invalid workspace config with custom recipe address

### ISSUE THREAD

**Issue by vlko91** [eclipse-che/che#12378]
### Description
Can not start newly created workspace because of invalid recipe and content field is empty (no location tag present).

I have a an artifactory instance and docker repository running on the separate port (16010) and deployed artifact "test-che-workspace:latest" there. It is available through the UI and docker works fine.
Before workspace creation the stack's recipe content was like: 
"content": "artifactorycn.mycompany.com:16010/test-che-workspace:latest".
After creation content became empty and workspace can not be started.

But if there is no port (like "localhost/test-che-workspace:latest") in the address workspace created and
started successfully.

### Reproduction Steps
1. Run Che 6.14.0 instance in docker.
1. Use any (e.g. blank) stack and change it's recipe content to valid one like:
"some.address.com:8888/some-che-workspace:latest"
("some.address.com:8888/some-che-workspace:latest" should be available using docker pull).
2. Try to create and run workspace with this stack.

**Comment by slemeur** [comment]
Won't fix in Che 6.
Would be nice to open a new issue if that use case cannot be properly handled in Che 7
