### ISSUE TITLE
Add ability to configure ephemeral mode for workspaces from dashboard

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#12374]
There is attribute, that allows to configure workspace to be ephemeral with no PVC attached on K8S/OpenShift infrastructure, so the aim of the issue is to allow configure that attribute from UI of User Dashboard. 
Attribute name is **persistVolumes**, that shoud be set in workspace configuration.

**Comment by slemeur** [comment]
Can be on the workspace overview page.

**Comment by sleshchenko** [comment]
@ashumilova Should we close it since the corresponding PR is merged?

**Comment by ibuziuk** [comment]
@ashumilova @slemeur @l0rd is it planned to add ephemeral trigger to the `create-workspace` view ? currently IMO it is hidden

**Comment by slemeur** [comment]
@ibuziuk : I don't think it should be done in upstream. 
We should have a dedicated task to handle that for the case of che.openshift.io.

**Comment by ibuziuk** [comment]
hmm... but why not to add the toggle (disabled by default) in the upstream, and just enable it by default in downstream ? IMO it is really logical and I guess it was smth. we have discussed with @l0rd (or maybe I got wrong idea)
