### ISSUE TITLE
Dartlang support

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#12370]
### Description

Dart is a language created by Google that is standardized under ECMA TC52. It has gained traction recently because of a recent development named [Flutter](https://flutter.io).

There is a community LS for Dart support via a [Dart Analysis Server Shim](https://github.com/natebosch/dart_language_server).

**Comment by sr229** [comment]
Also, the official Dart extension for VSCode is worth looking as a baseline implementation for the Theia plugin.

**Comment by slemeur** [comment]
Thanks for bringing that @sr229 !
cc @tsmaeder

**Comment by tsmaeder** [comment]
Giving this one another lease on life: probably should use a VS Code extensions, though. Still, a P2 tasks and I would much more like a marketplace where folks can host their own plugins.

**Comment by sr229** [comment]
I think I'd appreciate we have a common Marketplace interface that both VSCode and Theia-based IDEs can use. Would be pretty neat.
