### ISSUE TITLE
Dart and Flutter Stacks

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#12385]
### Description

Goes hand in hand with #12370.

Default stacks for Dart would be:

- the Dart SDK only

- Dart SDK with Flutter with:
   - Android SDK

I will be writing the defualt stacks for such since they're gonna be needed for the referenced PR as well.

**Comment by slemeur** [comment]
Hi @sr229 : Is that something you would be interested to contribute as devfile in Che 7 ?

**Comment by sr229** [comment]
Sounds like a new area but I'll be happy to, tell me where to submit
