### ISSUE TITLE
Theia remote plugins metadata

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12392]
### Description

Theia should support loading a remote plugin without requiring the main process to scan of a local plugin.

**Comment by benoitf** [comment]
merged here https://github.com/eclipse/che-theia/pull/42

**Comment by garagatyi** [comment]
@benoitf what is the plan to change broker implementations to avoid copying files? We are about to start sprint, so if it should be tackled by OSIO-Che team would be great to know before the start of the sprint.

**Comment by benoitf** [comment]
@garagatyi I think you're talking about item 4 of https://github.com/eclipse/che/issues/12292#issuecomment-453547003

 AFAIK need to have item 3 working first before avoiding files copy

**Comment by garagatyi** [comment]
Got it, thanks for the clarification
