### ISSUE TITLE
Che 7 plugin: Nodejs debugger

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12409]
Build a che 7 plugin with the result of https://github.com/theia-ide/theia/issues/3766

**Comment by tsmaeder** [comment]
Remaining steps moved here from https://github.com/theia-ide/theia/issues/3766 (since che-specific)

- [ ] Release Theia v0.3.19 and build an image based on the changes above
temporary image: `abazko/che-theia:test`
- [ ] Update https://github.com/ws-skeleton/che-theia-remote-extension to use Theia v0.3.19
- [ ] Build a new image from https://github.com/ws-skeleton/che-theia-remote-extension/blob/master/Dockerfile
temporary image: `abazko/remote-plugin:test`
- [ ] Prepare images for node debug plugins
temporary images: `abazko/ms-vscode.node-debug` `abazko/ms-vscode.node-debug2`
- [ ] Merge https://github.com/eclipse/che-plugin-registry/pull/74 (add debug plugins to the registry)
- [ ] Build a new `che-plugin-registry` image based on changes above
temporary image: `abazko/che-plugin-registry:test`
- [x] Merge https://github.com/eclipse/che/pull/12149/files
- [x] Build a new `che-server` images based on changes above
temporary image: `abazko/che-server`

**Comment by tolusha** [comment]
https://github.com/eclipse/che-plugin-registry/pull/74
