### ISSUE TITLE
Update the readme.MD and customizing.MD with the new information about Che-in-Che

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12426]
Need for Che 7 Beta

**Comment by evidolob** [comment]
@slemeur What should include in that docks?

**Comment by slemeur** [comment]
**In the readme.md**
- We should be updating the customizing section. 
- We should update the screenshoot (see https://www.eclipse.org/che/extend/ which I rebuilt few months ago)
- A new section should be added to introduce the technology stack
- Update Getting started section
  - Add how to install Che
  - Add how to use an online instance of Eclipse Che to discover it

**In the customizing.md**
Customizing should be highlighting the different components of Che which can be customized/configured/extended (see https://www.eclipse.org/che/extend/ which I rebuilt few months ago). It should point to the docs on documentation website.
Introduce about adding new/other web IDEs.


(Note:We should probably have a documentation about how to create a Che 7 based stack)

**Development workflow**
We need to update this wiki page: https://github.com/eclipse/che/wiki/Development-Workflow with the new development workflow starting with Che 7.

**Comment by olexii4** [comment]
https://docs.google.com/document/d/15en1g6l0DmJoXcTcvbpVrSPBqoJPJhJfjk3YDT34Jhg/edit?usp=sharing

**Comment by sunix** [comment]
@slemeur @l0rd could we close this issue ? handled by the che-doc team ?

**Comment by benoitf** [comment]
probably done ?

**Comment by sunix** [comment]
I will review README.md and customizing.md
