### ISSUE TITLE
Write documentation on how to 'Creating Eclipse Theia Plug-ins with Eclipse Che'

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12425]
### Description
We need this documentation for Che 7 Beta
Should this be on che-docs repository? 

Here is a proposition for the outline:
**Creating Eclipse Theia Plug-ins with Eclipse Che**
- [ ]  Developing your first plug-in
- [ ] What is a Plug-in
  - [ ] Plug-in concept in details
  - [ ] Plug-in metadatas
  - [ ] Plug-in Lifecycle
- [ ] Embedded vs Remote Plug-in
  - [ ] Introduction of Embedded Plug-in (diagram)
  - [ ] Introduction of Remote Plug-in (diagram)
  - [ ] Comparison matrix
- [ ] Creating New Plug-ins
  - [ ] Explain how to scaffold a new plugin
  - [ ] List of plugin samples
  - [ ] Plugin generation
  - [ ] Links to “How-to” guides (how to add a new language, how to add a new debugger, how to package a VSCode plug-in for Eclipse Che)
- [ ] Developing Plug-ins
  - [ ] Explain what is the developer experience
  - [ ] Explain self hosting
  - [ ] Show code completion
- [ ] Testing Plug-ins
- [ ] Publishing Plug-ins
  - [ ] Plug-in registry
  - [ ] Adding a plug-in into a workspace
  - [ ] Sharing your plug-in with a Factory
- [ ] Plug-ins Contribution Points
  - [ ] List of all the contributions points
  - [ ] Link to API reference for developer

**Comment by evidolob** [comment]
@slemeur Can you provide more information on what we should cover in this documentation?

**Comment by slemeur** [comment]
Should this be on che-docs repository? 

Here is a proposition for the outline:
**Creating Eclipse Theia Plug-ins with Eclipse Che**
- Developing your first plug-in
- What is a Plug-in
  - Plug-in concept in details
  - Plug-in metadatas
  - Plug-in Lifecycle
- Embedded vs Remote Plug-in
  - Introduction of Embedded Plug-in (diagram)
  - Introduction of Remote Plug-in (diagram)
  - Comparison matrix
- Creating New Plug-ins
  - Explain how to scaffold a new plugin
  - List of plugin samples
  - Plugin generation
  - Links to “How-to” guides (how to add a new language, how to add a new debugger, how to package a VSCode plug-in for Eclipse Che)
- Developing Plug-ins
  - Explain what is the developer experience
  - Explain self hosting
  - Show code completion
- Testing Plug-ins
- Publishing Plug-ins
  - Plug-in registry
  - Adding a plug-in into a workspace
  - Sharing your plug-in with a Factory
- Plug-ins Contribution Points
  - List of all the contributions points
  - Link to API reference for developer

cc @rkratky

**Comment by dneary** [comment]
We should also have an API guide - including some idea of API calls from VS Code covered vs uncovered.

**Comment by sunix** [comment]
@slemeur @l0rd could we close this issue ? handled by the che-doc team ?

**Comment by benoitf** [comment]
done ?

**Comment by sunix** [comment]
Let's close it @slemeur @rkratky @evidolob you can reopen new issue if some part is missing
