### ISSUE TITLE
Red mark of failed workspace should show error on mouse hovering and user should be able to get error message somehow

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12429]
### Description
Currently, in 1 place (left-hand panel of recent workspaces) it shows just ERROR hint:
![image](https://user-images.githubusercontent.com/1851863/51189527-ea116a80-18e8-11e9-96fb-3b24a32e381f.png)

in the workspace list view, it shows no hint:
![image](https://user-images.githubusercontent.com/1851863/51189515-e1b92f80-18e8-11e9-98f3-4b6da40360ad.png)

on the workspace details view it doesn't show the hint either:
![image](https://user-images.githubusercontent.com/1851863/51189506-dd8d1200-18e8-11e9-909e-f89d81872cdb.png)
And there is no way to get the error message on UD. 
Apart from that error marker disappears when user goes on any other view from failed workspace details view. Including workspaces list view.

**Comment by garagatyi** [comment]
@slemeur @evidolob FYI

**Comment by garagatyi** [comment]
And here is workspace JSON that contains the error 
![image](https://user-images.githubusercontent.com/1851863/54928384-7b6e1000-4f1c-11e9-91f7-bad750b57149.png)

@slemeur @l0rd Should we somehow address this problem? It is very confusing actually if user went to another view while workspace was starting - he won't see any error message at all.
We do show warning from infrastructures when some part of workspace recipe is ignored. We could use it to also show that last workspace start failed and the reason.
![image](https://user-images.githubusercontent.com/1851863/54928632-df90d400-4f1c-11e9-918c-0964db08f64b.png)

Would be also interesting to have small red exclamation mark inside of grey cycle of stopped workspace when UD sees that last workspace start failed.

**Comment by slemeur** [comment]
I guess you should mention @ashumilova and @evidolob to handle that as an enhancement request.
