### ISSUE TITLE
Make VS Code extension broker support extension identifier from its marketplace page

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12424]
### Description
Now VS Code extension broker needs an extension identifier in a format such as `vscode:extension/SonarSource.sonarlint-vscode` but on the extension page on the marketplace user see it in the following format `SonarSource.sonarlint-vscode`.
![image](https://user-images.githubusercontent.com/1851863/51181753-af053c00-18d4-11e9-963e-7669c6bdd0e9.png)
There is no reason to make user add prefix `vscode:extension/` which can bring confusion.
Let's support both formats.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@slemeur WDYT?

**Comment by benoitf** [comment]
the `vscode:extension/SonarSource.sonarlint-vscode` can be retrieved when you click on "install button" and grab the link.

**Comment by benoitf** [comment]
![link](https://user-images.githubusercontent.com/436777/51479347-431c4b00-1d8e-11e9-8765-af3f79ad2871.gif)

**Comment by garagatyi** [comment]
But what should be a proper UX from our side? @benoitf @slemeur WDYT?

**Comment by benoitf** [comment]
drag and drop the install button ^^

**Comment by slemeur** [comment]
Most of the users will be adding a plugin to their workspace by directly being in the IDE or browsing the marketplace. 

From the IDE, the user should be able to see/search the list available plugins. We already have a panel for that. We should make that panel richer. Separately, we should also start building a list of plugins from VSCode which have been validated to be working properly in Che. 
There is also the ability to install a plugin, by providing its identifier. I would think that we could make it simpler by allowing the user to just drop the URL of the plugin page on the marketplace: `https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode`

From the marketplace, I agree with Florent. Drag and Drop the install button.

**Comment by garagatyi** [comment]
ok, closing as this seems not to improve the experience

**Comment by garagatyi** [comment]
@slemeur Since drag and drop provides ID with prefix I don't see much value in the feature suggested by this issue initially. If you want to proceed with drag and drop related functionality I would recommend opening another issue not to confuse  ppl with the discussion here
