### ISSUE TITLE
Che 7 plugin: vscode-xml

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12437]
Create a Che 7 plugin (following up on theia-ide/theia#3778) and add it to the plugin registry.

    create a base image (or reuse the one from https://github.com/eclipse/che/issues/12436) for the tooling
    make a PR against https://github.com/eclipse/che-plugin-registry with a che 7 plugin containing https://github.com/redhat-developer/vscode-xml

**Comment by apupier** [comment]
I think this issue https://github.com/eclipse/che/issues/12536 is a prerequisite
