### ISSUE TITLE
Add CI to build and push remote-plugin-runner-java8 image on dockerhub

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12430]
### Description
We have a dockerfile for Theia remote runner that provides java8 as a part of the runtime. It is useful for VS Code extensions used in Thiea that need java.
But we don't have image pushed and don't have a CI to update it.   This PR https://github.com/eclipse/che-plugin-registry/pull/76 uses the same image but pushed to my private account. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by l0rd** [comment]
@garagatyi where do you want to put the Dockerfile?

**Comment by garagatyi** [comment]
It is already in che-theia repo https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-runner-java8/Dockerfile

**Comment by l0rd** [comment]
@garagatyi 👍

**Comment by svor** [comment]
It is also needed for https://github.com/eclipse/che/issues/12436, https://github.com/eclipse/che/issues/12446

**Comment by tsmaeder** [comment]
Why Java 8 and not something more modern?

**Comment by riuvshin** [comment]
since it is moved to che-theia repo this is not managed by CHE CI anymore, so I can't help. Please assign someone who manages build system for https://github.com/eclipse/che-theia/
afaik they are using Travis

**Comment by benoitf** [comment]
@tsmaeder AFAIK sonarlint is not running with a Java version more recent than JDK8 (at least when I tried it this is why I stick with Java8)
But it doesn't mean that we could not provide more recent java versions as well

**Comment by benoitf** [comment]
@tsmaeder yes as I said, I don't see why we couldn't have an image for Java11 (for SonarLint it was really requiring Java8)

**Comment by sunix** [comment]
so Java8 image is 'just' for sonarLint. We would use a Java11+maven+gradle container image for JDT.ls 
VSCode extension.

**Comment by sunix** [comment]
So remote-plugin-runner-java8 is not on docker hub yet ?

**Comment by garagatyi** [comment]
@sunix 
yes - we need another image for the JDT.LS
no - java 8 image is not on docker hub yet

**Comment by garagatyi** [comment]
Assigned @riuvshin since he has permissions to do that

**Comment by sunix** [comment]
@garagatyi so ATM it is garagatyi/remotetheia:java ? right ?

**Comment by garagatyi** [comment]
Yes, but it might not be an up-to-date version of Theia libraries. So, check if it what you really can use.

**Comment by garagatyi** [comment]
Should be already implemented
