### ISSUE TITLE
Support addition of a VS Code extension using plugin broker to a main Theia container

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12431]
### Description
We have VS Code extension broker that runs extensions as Theia remote plugins. 
But some extensions would be fine running inside of Theia container (e.g. need only Node.Js).
Using a remote container for those extensions would burn workspace memory. 
Should we allow local mode for VS Code extensions delivered by a broker as we do for Theia plugins?

**Comment by garagatyi** [comment]
@slemeur @l0rd @benoitf @evidolob WDYT?

**Comment by benoitf** [comment]
@garagatyi I was assuming that if no specific image was declared then the VSCode extension broker was just dropping the extension in plug-ins folder (without adding env variables as there is no container) And then the extension is being loaded directly by the main theia instance

**Comment by garagatyi** [comment]
@benoitf no, this functionality wasn't added to that broker. But if we agree that it is needed (I wasn't sure that we agree) it would be easy to add it.

**Comment by benoitf** [comment]
I think it's little development and it will bring a broader value.
I let others to comment :)

**Comment by slemeur** [comment]
+1
