### ISSUE TITLE
Documentation about how to deploy custom plugin registry

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12444]
### Description
We need to document the way how to deploy custom plugin registry with Che and configure Che to use it.

**Comment by keithchong** [comment]
Hi @skabashnyuk , I'm trying to add a plugin registry as described here:

https://github.com/eclipse/che-plugin-registry

I was able to build the image.  But in che, when I try to add the registry, I get the message "Your registry is invalid".  (I'm not quite sure what to add for the URL)

Do you have tips/pointers or other detail, especially the steps starting from after the image is created.

**Comment by skabashnyuk** [comment]
@keithchong you need to override this property
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L580 ```che.workspace.plugin_registry_url=https://che-plugin-registry.openshift.io/v3``` you can do that for instance with env variable of che master
```CHE_WORKSPACE_PLUGIN__REGISTRY__URL=http://registry-route/v3```

**Comment by keithchong** [comment]
Hi @skabashnyuk,

Is there a way to get this to work without modifying Che code?  (presumption is that I'll have to modify that code and rebuild.)

I opened https://github.com/eclipse/che/issues/13710 for the other approach.  I verified that my local registry was actually up and running first.

**Comment by keithchong** [comment]
Hi @skabashnyuk , I can't get this to work.  Could you please elaborate on the steps to override?
I'm following this:  https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1
