### ISSUE TITLE
Investigate how to synchronise Theia global preferences between Che workspaces

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12442]
By default, if a user has change some preference in one workspace, we should reuse the configuration into other workspaces
If user changes the configuration options - then it would overload the defaults.
In the end we should have description how we can synchronise Theia preferences

**Comment by mmorhun** [comment]
API for work with Che preferences is added into workspace client: https://github.com/eclipse/che-workspace-client/pull/15

**Comment by mmorhun** [comment]
Done in https://github.com/eclipse/che-theia/pull/80
