### ISSUE TITLE
Is there a plan to support multiple extra column mapping in new workspace container creation?

### ISSUE THREAD

**Issue by cloorc** [eclipse-che/che#1244]
In my workspace, it's better to share `.m2` and `.ssh` with my workspace container. 

If I import project from git and I want to push my changes then I need the private key to continue. Although new key pairs can solve this problem, but it's never a good practice for generating key pairs each time when you restart workspace.

Please have a look. Thanks!

**Comment by ghost** [comment]
You do not need to generate new key pair each time. When in the IDE, go to Profile > Preferences > SSH, click on GitHub button and you should be all set. Che will generate a new key pair and upload it to your GitHub account.

However, your request on making it possible to have multiple mount binding does make sense. Labeling it as enhancement.

**Comment by TylerJewell** [comment]
@soiff - in 5.0.0-M1 - we added a capability so that you can mount multiple volumes to your workspaces. I believe @jamesdrummond has updated the docs with everything you need to know for this.  If you have further questions, we can help you out.

**Comment by cloorc** [comment]
@TylerJewell That's great! I'll try it later and post any information if I have.

**Comment by JamesDrummond** [comment]
@soiff Docs are currently being worked on and are private currently for 5.0.0-M3 which covers M1 changes. You can set/export  environment variable `CHE_EXTRA_VOLUME_MOUNT=~/.ssh:/home/user/.ssh;~/.m2:/home/user/.m2`.
