### ISSUE TITLE
User login whitelist with identity providers

### ISSUE THREAD

**Issue by sathibault** [eclipse-che/che#12459]
### Description
The behavior of keycloak is such that anyone with a login for a configured identity provider is able to login and use the Che environment.  The first time they log in, keycloak auto-registers them as a keycloak user and redirects them to Che with valid token.  Ideally, users that do not exist in keycloak would not be allowed to log in.  I've discussed this with the keycloak folks and it is apparently not possible out of the box.

Is there anything we can do from the Che side to prevent unknown users from logging in this way?

### Reproduction Steps

Configure a Google identity provider in Keycloak.  Without any existing users in Che or Keycloak, login with Google.  You will automatically be logged in to Che and able create and use workspaces.

Ubuntu/Che 6.13.0

**Diagnostics:**

**Comment by skabashnyuk** [comment]
Try to disable "User registration" in che realm . Realm settings-> Login. 
 https://www.keycloak.org/docs/3.0/server_admin/topics/login-settings/forgot-password.html

**Comment by sathibault** [comment]
Unfortunately, this does not prevent keycloak from auto-registering users logging in via an identity provider.

**Comment by sathibault** [comment]
How about having Che require that Keycloak users need to have the `user` role?  We can control what roles users have by default when created via an identity provider.  If we exclude that from the default roles, then we would have to assign new users the role through the admin console before they could login.

**Comment by mingfang** [comment]
Is there a solution to this problem?
