### ISSUE TITLE
Implement first component UI cypress test

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#12457]
In last sprint, there was done some investigation of possible technologies to use for UI testing Theia (and Che7) and an initial implementation of possible E2E test https://github.com/eclipse/che/issues/12364

To not repeat the same mistake with trying to cover **everything** by E2E tests, we should consider implementing UI tests on per-component basis (in theia-ide codebase, but also in our components). This is in line with [this coment from upstream issue](https://github.com/theia-ide/theia/issues/1118#issuecomment-381188586), with which I strongly agree ;-)

We need to gather input from devs to make a good decision what component would be the best for fist component to try this approach first (cc @evidolob, @ashumilova, ...). The component should be relatively simple for this kind of tasks, as we are still not very familiar with the tech.

**Comment by rhopp** [comment]
DoD:
* Right component is selected for this effort
* First simple UI tests are implemented & merged to the component repo

**Comment by sunix** [comment]
@rhopp @vkuznyetsov do we still want to work on this ?

**Comment by Ohrimenko1988** [comment]
Deprecated task
