### ISSUE TITLE
Uncaught (in promise) Error: Looks like the language server is talking to long to respond, prease try again in sometime.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12460]
### Description

Sometimes I got error  `Uncaught (in promise) Error: Looks like the language server is talking to long to respond, prease try again in sometime.`
I'm not sure whether it is reproductive on all environment. It is just for information.

### Reproduction Steps

Creates workspace with Che-in-Che.
Starts it.

**OS and version:**    

6.18.0-SNAPSHOT (with some my patches)
Azure AKS (B2s instance)

**Diagnostics:** 

![screenshot 2019-01-18 at 10 09 43](https://user-images.githubusercontent.com/101795/51360570-86b55180-1b0f-11e9-88fc-dcefbdae44ef.png)

**Comment by eivantsov** [comment]
@monaka can this be a random networking issue? Does it happen to any particular language server?

**Comment by monaka** [comment]
This may fixed after I changed my ingress to Traefik (refs #12645).
I close it for now. (might re-open if I could reproduce it.)

@eivantsov I agree Che 7 is the better choice for the future.
But I'm blocked by #12585 on GWT-IDE and waiting to be implemented GIt related features on Theia. :-)
