### ISSUE TITLE
Failed to start Che7 Dev stack

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12462]
### Description

Failed to start workspaces from Che 7 Dev stack.

### Reproduction Steps

1. Create workspace from Che 7 Dev stack.
2. Start it.

**OS and version:**    

6.18.0-SNAPSHOT

**Diagnostics:** 

```
$ kubectl logs --namespace=camino workspaceav2iih4dt3395scm.che-plugin-broker -c brokerovdqi5
2019/01/18 02:59:37 Broker configuration
2019/01/18 02:59:37   Push endpoint: wss://{...}/api/websocket
2019/01/18 02:59:37   Auth enabled: true
2019/01/18 02:59:37   Runtime ID:
2019/01/18 02:59:37     Workspace: workspaceav2iih4dt3395scm
2019/01/18 02:59:37     Environment: default
2019/01/18 02:59:37     OwnerId: fdd3c84d-2e22-4399-9dda-32c7db05db81
2019/01/18 02:59:37 Couldn't connect to endpoint 'wss://{...}/api/websocket', due to error 'x509: failed to load system roots and no roots provided'
```

**Comment by monaka** [comment]
Possibly the same issue in this blog post. https://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/

**Comment by monaka** [comment]
Kubernetes (managed by AKS), Multi-user, https by Ingress.

**Comment by sleshchenko** [comment]
@monaka Do Che 6 Workspaces works on your installation?

**Comment by eivantsov** [comment]
Self signed certs?

**Comment by monaka** [comment]
Che 6 Workspace works fine on my env.
The certificate is provided by Let's Encrypt (not self signed).
I guess Che 6 Workspace also doesn't work if the certificate is invalid.

**Comment by monaka** [comment]
And if we can trust the error message `x509: failed to load system roots and no roots provided`, the issue is not caused by the connection failure but loading `ca-certificates.crt` failure.

**Comment by sleshchenko** [comment]
@monaka I guess the following PR should fix the issue you faced https://github.com/eclipse/che-plugin-broker/pull/25
@garagatyi Can you confirm?

**Comment by monaka** [comment]
I checked on my Che and I confirm this was fixed.  Thanks!
