### ISSUE TITLE
Fail to Load Dashboard in Multi-user Mode after System Restart

### ISSUE THREAD

**Issue by nguyenbuiUCSD** [eclipse-che/che#12471]
### Description
Can not load dashboard for multi-user running on Docker  after system restart. http://${CHE_HOST}:8080/dashboard/ return:
`Internal server error occurs. API is not accessible Click here to reload page.`

### Reproduction Steps

1. Run Che on Docker in multiuser mode, following Che Docs: [Multi-user: Installation on Docker](https://www.eclipse.org/che/docs/che-6/docker-multi-user.html)
2. Restart OS
3. Access http://${CHE_HOST}:8080/dashboard/ will result:
`Internal server error occurs. API is not accessible Click here to reload page.`

**OS and version:**    
OS:
- Description:	Ubuntu 18.04.1 LTS
- Release:	18.04
- Codename:	bionic

Docker:
- Docker version 18.09.1, build 4c52b90

**Diagnostics:**
Logs:
`docker logs -a  ${che} > che.log` [che.log](https://github.com/eclipse/che/files/2775326/che.log)

Manually restart ${che} container will fix the problem:
`docker container restart ${che}`

**Comment by skabashnyuk** [comment]
your keycloak is not accessible 
```
1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://192.168.0.119:5050/auth/realms/che/.well-known/openid-configuration
```
I recommend using Kubernetes or OpenShift instead of Docker.
Or k8s on Docker https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1
