### ISSUE TITLE
Can't use Eclipse Che on macOS

### ISSUE THREAD

**Issue by m0nhawk** [eclipse-che/che#12475]
### Description
The single-user Docker installation is broken.

### Reproduction Steps
1. Run Eclipse Che:

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/data:/data eclipse/che:latest start
```
2. Create any stack.
3. Create project - no available templates and:

![screencapture-localhost-8080-dashboard-2019-01-21-01_26_00](https://user-images.githubusercontent.com/8220926/51458651-8f7a7300-1d1b-11e9-9a46-3f2a23a56414.png)

```
WebSocket connection to 'ws://localhost:32833/wsagent?token=' failed: Error during WebSocket handshake: Unexpected response code: 403
o4k @ _app-0.js:18001
```

**OS and version:**
macOS 10.14.2
Docker 2.0.0.2
Che 6.16

**Comment by skabashnyuk** [comment]
With chances, 99.99999%  docker 2.x  will not work on mac.
Try to use kubernetes https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1 or minishift.

**Comment by l0rd** [comment]
> With chances, 99.99999% docker 2.x will not work on mac.

@skabashnyuk what do you mean? Latest Che doesn't support latest Docker API (e.g. v1.39 distributed with Docker Desktop 2.0.1)?

**Comment by l0rd** [comment]
Issues do not seams related: in this case the workspace is started successfully whereas in #10213 the workspace cannot be started at all (cannot pull image) and there is [a workaround](https://gist.github.com/kastork/3d060691e9661064e894c2aa1893e0f4) for it.
 
Current issue looks related to #12463 instead. @skabashnyuk WDYT?

**Comment by skabashnyuk** [comment]
@l0rd you are right. @mkuznyetsov can you take a look?

**Comment by skabashnyuk** [comment]
@l0rd  Maybe. 
@m0nhawk can you show os Chrome developer console errors?

**Comment by m0nhawk** [comment]
@skabashnyuk I can successfully create the workspace (any amount and for any stack).

In the logs (`docker logs -f che`) I don't see any errors, only one warning:

```
2019-01-21 16:39:28,497[Thread-11]        [WARN ] [o.e.c.i.e.m.s.ssh.KeysInjector 147]  - Unable to inject workspace workspaceidz27uwoh6okj58k public keys. Error: java.net.ConnectException: Connection refused (Connection refused)
```

The Chrome Dev console:

<img width="1552" alt="screen shot 2019-01-21 at 10 40 23 am" src="https://user-images.githubusercontent.com/8220926/51487569-16a20800-1d69-11e9-80fc-c5731d7ca4cd.png">

**Comment by m0nhawk** [comment]
```docker ps
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                    NAMES
accf0642dbb0        eclipse-che/workspaceidz27uwoh6okj58k_null_che_dev-machine   "/home/user/entrypoi…"   2 hours ago         Up 2 hours          22/tcp, 4403/tcp, 0.0.0.0:32845->4401/tcp, 0.0.0.0:32844->4411/tcp, 0.0.0.0:32843->4412/tcp, 0.0.0.0:32842->8000/tcp, 0.0.0.0:32841->8080/tcp, 0.0.0.0:32840->9876/tcp   workspaceidz27uwoh6okj58k_null_che_dev-machine
4a09d6660567        eclipse/che-server:6.16.0                                    "/entrypoint.sh"         2 hours ago         Up 2 hours          8000/tcp, 0.0.0.0:8080->8080/tcp                                                                                                                                         che
```

The port is forward and I have no firewall or anything in between.

**Comment by m0nhawk** [comment]
Diagnostics:

```
REST Call on Workspace Agent
Unable to perform call on http://localhost:32846/api: Status -1, statusText:/null
Hint: Workspace Agent is running but browser is unable to connect to it. Please check CHE_HOST and CHE_DOCKER_IP_EXTERNAL in che.env and the firewall settings.

Websocket on Workspace Agent
No reply of websocket test after 5 seconds. Websocket is failing to connect to ws://localhost:32846/wsagent
```

**Comment by sttyerase** [comment]
I'm having what appears to be the same issue.  I will be watching for the PR.
Error: Failed to run the workspace: "Server 'wsagent/http' in machine 'dev-machine' not available."

Mac Rules>>docker ps
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS                              NAMES
9cf1189cffa3        eclipse/che-server:6.18.1   "/entrypoint.sh"    3 hours ago         Up 3 hours          8000/tcp, 0.0.0.0:8080->8080/tcp   che
Mac Rules>>
<img width="588" alt="screen shot 2019-02-20 at 2 34 05 pm" src="https://user-images.githubusercontent.com/25646282/53119278-1db16700-351d-11e9-837a-06031864f294.png">

**Comment by sttyerase** [comment]
I am not experiencing the issue on my Fedora server.  The Che versions on both are the latest, 6.18.1.

**Comment by sriramnanduri** [comment]
Experiencing the same issue on Mac with Che 6.18.1.
Docker version 

![screen shot 2019-02-22 at 1 43 29 am](https://user-images.githubusercontent.com/7016661/53233936-56e3f700-3643-11e9-8d56-197da7530850.png)

**Comment by skabashnyuk** [comment]
@sttyerase @sriramnanduri from what I can see your issue is not related to CORS

**Comment by qurben** [comment]
@skabashnyuk It seems to be related with #12476, before that CORS on wsagent was a bit more liberal.

When running the normal setup on Docker (the one described on the wiki and in this issue) and accessing Che via `http://localhost:8080` the following happens:

In [`CheWsAgentCorsAllowedOriginsProvider`](https://github.com/eclipse/che/blob/master/wsagent/che-wsagent-core/src/main/java/org/eclipse/che/wsagent/server/CheWsAgentCorsAllowedOriginsProvider.java#L47) the value of `apiExternal` is equal to `http://10.0.75.2:8080/api` (or whatever ip the container has on the Docker NAT). This sets `allowedOrigins` to `http://10.0.75.2:8080`. This causes the wsagent server to not respond with any CORS headers when a request is sent from `http://localhost:8080` or `http://127.0.0.1:8080` because the host does not match.

I am currently not well known enough with the code to propose a proper solution for this.

**Comment by skabashnyuk** [comment]
Due to the end of life of Docker infrastructure more likely this bug would not be fixed. My recommendation to use K8S/OpenShift on OSX https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1

**Comment by sttyerase** [comment]
@skabashnyuk I do understand why you want to build Che to run on K8s and have robust cluster support.  However, for the task I want to implement, a simple demonstration instance, this is like using a bulldozer when a shovel will do.  This K8s instance has overwhelmed my MBP.

<img width="853" alt="screen shot 2019-02-26 at 9 14 08 am" src="https://user-images.githubusercontent.com/25646282/53423002-80d44b00-39ae-11e9-8157-46bcd8cf10ae.png">

<img width="787" alt="screen shot 2019-02-26 at 9 14 51 am" src="https://user-images.githubusercontent.com/25646282/53423035-96e20b80-39ae-11e9-8e9f-72587b439300.png">

I do hope you will somehow find a way to continue Docker support for Che.

**Comment by sttyerase** [comment]
I finally found a version, 6.12.2, that will work with the latest Docker4Mac.  It still has some bugs with Git keys, but should be useable for demonstration purposes.  I'm "freezing" versions on both.
