### ISSUE TITLE
Which one stack should be predefined for user who wants develop Theia plugin

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12480]
### Description
For now we have two CHE stacks and one development plugin. Which one should be predefined for user plugin development:
- `CHE 7` stack contains all dependencies to build CHE in CHE: java, node and so on.
- `CHE 7 Dev`stack contains node(6 version), ocp tool... And defined to development `CHE plugins`.
- `Che Theia Dev Plugin` plugin  - contains all dependencies to build theia, che-theia, theia plugins.

So which one stack should be default for Theia plugin development?
Which one development flow should be for users who want develop Theia plugins?

P.S. As for me, I think We could create new stack `CHE 7 Theia Dev`, but without dev-container(to save RAM), but with applied `Che Theia Dev Plugin`. So in runtime user will get dev-container from  `Che Theia Dev Plugin`.

**Comment by l0rd** [comment]
I am +1 with your proposal @AndrienkoAleksandr
