### ISSUE TITLE
deployment on minikube failed due to che server not able to get keycloak configurations

### ISSUE THREAD

**Issue by hmangala** [eclipse-che/che#12491]
### Description
Deployment on minikube failed due to che server not able to get keycloak configurations

### Reproduction Steps
helm upgrade --install pg-che --namespace pg -f ./values/tls.yaml --set global.ingressDomain=192.168.99.100.nip.io  --set global.cheDomain=192.168.99.100.nip.io ./

**OS and version:**    
Windows 7
**Diagnostics:** 
[che_logs.txt](https://github.com/eclipse/che/files/2783016/che_logs.txt)

**Comment by eivantsov** [comment]
@hmangala is 192.168.99.100 your MiniKube IP?

**Comment by hmangala** [comment]
Yes that's correct, please see the attachment
![minikube](https://user-images.githubusercontent.com/20920370/51542291-e8afe700-1e80-11e9-9d49-d57816a2995b.png)

**Comment by eivantsov** [comment]
I can see you are using TLS. Self signed certs?

**Comment by hmangala** [comment]
I tried the steps provided in documentation like below
helm install --name pg-cert-manager stable/cert-manager

**Comment by eivantsov** [comment]
But can you verify that https ingresses are available?

**Comment by hmangala** [comment]
please tell me how to do it?

**Comment by hmangala** [comment]
This should provide me keycloak site according to the document which is not up
https://192.168.99.100.nip.io/auth/

**Comment by hmangala** [comment]
![pods](https://user-images.githubusercontent.com/20920370/51542825-25c8a900-1e82-11e9-8f17-57c4104f050d.png)

**Comment by eivantsov** [comment]
It is up.. but to be able to use secure endpoints and get certs from Letsencrypt you need a public IP which isn't the case with MiniKube. I recommend dropping tls option and trying without it.

**Comment by hmangala** [comment]
helm upgrade --install pg-che --namespace pg -f ./values/default-host.yaml --set global.ingressDomain=192.168.99.100.nip.io  --set global.cheDomain=192.168.99.100.nip.io ./

Same issue again
[che_logs.txt](https://github.com/eclipse/che/files/2783265/che_logs.txt)

**Comment by eivantsov** [comment]
This time you used default host strategy. .nip.io should not be required. But this strategy isn't tested well anyway. I recommend follow docs and use multi-host

**Comment by hmangala** [comment]
You mean multi-user strategy? like below 
helm upgrade --install pg-che --namespace pg -f ./values/multi-user.yaml ./

**Comment by eivantsov** [comment]
Yes

**Comment by hmangala** [comment]
Executed the same no luck still issue remains the same, please check che pod logs attached
[che_logs.txt](https://github.com/eclipse/che/files/2783327/che_logs.txt)

**Comment by eivantsov** [comment]
What do you see when you open `http://keycloak-pg.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration` in your browser?

Do you have ingress addon enabled?

**Comment by hmangala** [comment]
I believe no, can you please point me how to do it
Browser I am getting No Response
