### ISSUE TITLE
Kubernetes expose external IP - Question

### ISSUE THREAD

**Issue by gustaveherbst** [eclipse-che/che#12494]
More of a Kubernetes question, I run the helm install for che, it installs, question is, how to I expose this on one of the external IPs like my LoadBalancer or such.
NAME      TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)            AGE
che-host  ClusterIP  10.245.52.50  <none>       8080/TCP,8087/TCP  1s

I can see it is deployed but I need to access external from the cluster...

Thanks
DB

**Comment by eivantsov** [comment]
@DarkBlaez so, you have successfully deployed Che and can access ingresses from within the network? But you wonder how it can be access from outside the network?
