### ISSUE TITLE
Rename Che 7 model fields that don't follow camel case 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12501]
### Description
Rename Che 7 model fields that use dash instead of camel case.
che-plugin.yaml:
- memory-limit https://github.com/ws-skeleton/che-editor-theia/blob/master/etc/che-plugin.yaml
- container-image https://github.com/eclipse/che-plugin-registry/pull/76/files#diff-ad94a2097c65352548608f1fd95f4234R10
- working-dir
- workspace-env
- editor-commands

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by metlos** [comment]
Not sure if all of https://github.com/eclipse/che-plugin-broker/blob/master/model/model.go is used in che-plugin.yaml but there seem to be more such fields than just the 2 mentioned.

For example `workspace-env` is used for sure.

**Comment by garagatyi** [comment]
You are completely right. Thanks for noticing.

**Comment by garagatyi** [comment]
Added to the description of the issue

**Comment by garagatyi** [comment]
Issue fixed
