### ISSUE TITLE
Plugin broker fails to initialize vscode plugin

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#12505]
### Description
 
Plugin broker fails to initialize vscode plugin

### Reproduction Steps

**OS and version:**    
* minishift v1.27.0+707887e
* vscode plugin: https://raw.githubusercontent.com/eclipse/che-plugin-registry/ab/debug-vscode-plugins/plugins/ms-vscode.cpptools:0.20.1

**Diagnostics:** 
```
Starting Init Plugin Broker
Cleaning /plugins dir
Started Che Plugin Broker
List of plugins and editors to install
- che-machine-exec-plugin:0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- org.eclipse.che.editor.theia:1.0.0 - Eclipse Theia
Starting common Che plugins processing
All plugins have been successfully processed
Started Che Plugin Broker
List of plugins and editors to install
- ms-vscode.cpptools:0.20.1 - C/C++ IntelliSense, debugging, and code browsing https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
Starting common Che plugins processing
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspacej5on9wcytn8uftcu failed with error: Get : unsupported protocol scheme """
```

**Comment by garagatyi** [comment]
In @tolusha case, Che configuration was messed up and incorrect image of the broker was used. Actually, Theia broker was used for VS Code extension.

In @azatsarynnyy case (https://raw.githubusercontent.com/azatsarynnyy/che7-plugin-registry/master/org.eclipse.che.vscode.k8s/1.0.0/meta.yaml), meta.yaml contains incorrect plugin type for vscode extension - Theia plugin.

After correcting issue cannot be reproduced.

**Comment by tolusha** [comment]
@garagatyi
