### ISSUE TITLE
Codenvy Editor does not recognise source folders correctly

### ISSUE THREAD

**Issue by aghasemi** [eclipse-che/che#12507]
Hi,

I cloned an existing Heroku app (Maven+Spring Boot) into my workspace using the heroku CLI (Couldn't get Git SSH to work, so couldn't use the Import wizard). 

Then went to `Project > Update Project Configuration` and manually changed project type from Blank to Maven. ArtifactId was recognised correctly. 

However, I noticed in every single Java file, I get package name error in the first line, because Codenvy doesn't correctly recognise the Maven source directory structure. E.g. class `MyApp.java` in package `io.abc` is met with a red line, as Codenvy expects the package name to be `main.java.io.abc` (Maven default directory structure).

I could see in `Project > Configure Classpth` that the root folder `src` is somehow incorrectly counted as a source folder, but I cannot remove it there! I however remove the entry in `.che/classpath`, but it doesn't work, and after Maven Reimport the classpath is created again. Adding `<sourceDirectory>` entries to `pom.xml` also didn't work.

Any idea how to fix it? 

P.S. I don't have this issue with the same `console-java-app` in the same workspace. 

Thanks

**Comment by slemeur** [comment]
Won't fix in Che 6.
Would be interesting to reopen an issue if the following case in not working on Che 7
