### ISSUE TITLE
PHP Code Completion Not Working

### ISSUE THREAD

**Issue by swartjie** [eclipse-che/che#12509]
Hey Guys,

I setup a new workspace on a new Server (Linux Centos), Setup the workspace and added the project.
But uppon creating the project, I cannot see any trace of the Code Completion?

I did check the Workspace config has the code completion module enabled, but when I work with a file, it does not suggest anything to me...

Am I doing something wrong? Do I need to manually enable it or something?
How can we go about debugging and getting it resolved?

**Comment by eivantsov** [comment]
@swartjie currently, you have to hit ctrl + space to get autocompletion.
