### ISSUE TITLE
Che Authentification/Authorization

### ISSUE THREAD

**Issue by ukman** [eclipse-che/che#1250]
Hi,

We already have web-system based on NodeJS that manages users/credentials/permissions etc. Now we want to let users to work with Che. 

How can we authorize user for working with our instance of Che? Do we need to create our own plugin that would check current user and block users without credentials? Something else?

**Comment by TylerJewell** [comment]
@ukman This functionality is not provided within Eclipse Che today.  Each Che server has a single user identity.  Codenvy provides a multi-user, multi-tenant implementation with permissions controls. 

Multi-user controls and enforcement is tricky as the system is distributed, and each node and service needs to have enforcement of tokens.  So imagine a workspace, which itself is not part of the Che server, and that workspace has SSH, web terminal, and native processes.  All of these various services need to have user enforcement as a result.  Codenvy has an additional go router installed along with token enforcement to manage these rules.

Some customers run an nginx router with a Che farm, giving each user access to a single Che VM as a way to simulate multi user with Che.
