### ISSUE TITLE
[Proposal]Add ability create workspace without recipe for CHE 7, if plugins was defined

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12512]
### Description
It could be useful to add ability create workspace without recipe for CHE 7, if plugins was defined.
Potentially for CHE 7 workspace we could define dev machine like CHE plugin. But workspace api doesn't support workspace config without recipe. 

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
@AndrienkoAleksandr As far as I know Workspace API does not have such restriction anymore. Could you please test it via swagger on your Che installation? I guess it's Dashboard who doesn't allow you to create workspace without recipe.

**Comment by AndrienkoAleksandr** [comment]
Ok, such configuration works:
```
{
  "environments": {},
  "projects": [],
  "name": "CHE7TESt",
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1"
  },
  "commands": [],
  "links": []
} 
```
@sleshchenko thanks.
