### ISSUE TITLE
Test stack feature always load GWT IDE

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12511]
### Description
Test stack feature always load GWT IDE.

### Reproduction Steps
![a](https://user-images.githubusercontent.com/6873095/51704007-99a0b800-2020-11e9-82fa-6610a18144fe.gif)

**OS and version:**    
CHE:  6.18.0-SNAPSHOT
CHE on the Minikube

**Comment by olexii4** [comment]
duplicated

Discussed with @AndrienkoAleksandr  to close this one because it has less description.
