### ISSUE TITLE
Big delay of execution when using Commands Palette

### ISSUE THREAD

**Issue by mcouliba** [eclipse-che/che#12517]
### Description
When executing commands from the Commands Palette, I have to wait for 20+ seconds before starting

### Reproduction Steps
Define and execute a command from the Commands Palette

**OS and version:**    
che v.6.17.1

**Diagnostics:**

**Comment by eivantsov** [comment]
@mcouliba when using a che7 workspace?

**Comment by mcouliba** [comment]
@eivantsov no using a che6 workspace using a custom stack [1]

[1] https://github.com/mcouliba/che-jdk-recipes/blob/master/Dockerfile

**Comment by mcouliba** [comment]
Adding the Java Language Server fixes the issue.

"installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            **"org.eclipse.che.ls.java"**
          ]

I do not understand the link between the Command Palette and Java Language Server but so far, my problem is solved
