### ISSUE TITLE
Remote plugin doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#12526]
### Description
I've tried to run [Sonarlint VS Code extension](https://github.com/eclipse/che-plugin-registry/blob/c5222317e53037edf7b3a0debe1f3a6bcc5bba6c/plugins/org.eclipse.che.vscode-sonarlint/0.0.1/meta.yaml) as a remote plugin. When the workspace started I can see Sonarlint extension in Plugin view but it doesn't work and no logs in minikube dashboard. 
For running che I've used `eclipse/che-theia:0.3.18-nightly` image.
![screenshot from 2019-01-28 12-07-42](https://user-images.githubusercontent.com/1271546/51829884-2e443800-22f7-11e9-9cb6-4628dde214bb.png)
![screenshot from 2019-01-28 12-07-15](https://user-images.githubusercontent.com/1271546/51829890-313f2880-22f7-11e9-8d40-7da94b2f71e2.png)

Browser's console logs:
![screenshot from 2019-01-28 12-33-38](https://user-images.githubusercontent.com/1271546/51830652-0524a700-22f9-11e9-99f9-8caf443e29f1.png)

Attributes from the workspace config:
```json
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1,https://raw.githubusercontent.com/garagatyi/che-plugin-registry/vscodeExts/plugins/org.eclipse.che.vscode-sonarlint:0.0.1"
  }
```

### Reproduction Steps

https://www.youtube.com/watch?v=CMLsE3d9m6U&feature=youtu.be

**Comment by garagatyi** [comment]
Just tried and everything worked for me
