### ISSUE TITLE
Theia dev editor is not secure

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12530]
### Description
Theia dev editor placed [here](https://github.com/che-incubator/che-theia-dev-plugin/blob/master/etc/che-plugin.yaml) exposes child Theia with an insecure port. Which means that anybody on a public Che instance can access it if they can guess the link to it (or spy it from a screen).
Theia itself is protected, [see](https://github.com/ws-skeleton/che-editor-theia/blob/master/etc/che-plugin.yaml#L15-L16).

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@evidolob @ashumilova FYI

**Comment by benoitf** [comment]
I think it's partially linked that there is a proxy that is not so transparent using secured mode.

**Comment by garagatyi** [comment]
@benoitf can you elaborate on what is the problem with the proxy? I am not familiar with it.

**Comment by benoitf** [comment]
I don't remember but maybe it was when detecting that server is up remotely (on 'hosted mode')
Theia starts a process, and try to connect on the route to check when it's ready before opening tab

**Comment by garagatyi** [comment]
If theia start new instance locally isn't it check localhost?

**Comment by benoitf** [comment]
@garagatyi it doesn't. Here is why:
At some point it was just checking the new process but UX was not good. There is time for K8S route to be available. 
So even if the process is "ready" locally and listen on the right port, if client opens the tab in its browser it will see a nice (or not so nice) "Unavailable page".
So there is a need to really see if page is "ready to be loaded from browser" before opening the tab.

**Comment by sleshchenko** [comment]
@benoitf Can Theia use machine token while checking the availability of Theia Dev port?

**Comment by benoitf** [comment]
@sleshchenko well, on technical side I don't see why token can't be given.(it's code on server side)
For now it's using a URI

https://github.com/theia-ide/theia/blob/e3837bb22c73841af2dccbaffd7466a835d9de67/packages/plugin-ext/src/hosted/node/hosted-instance-manager.ts#L142

(so no extra header/token)

If token is given in URI it may work but probably browser tab will be opened with that URI field and then displayed in browser tab which may not be so good for security as well.
