### ISSUE TITLE
Release 6.17.2

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#12534]
This bugfix should contain fix for https://github.com/eclipse/che/issues/12521 (should be fixed by https://github.com/eclipse/che/commit/dda3bf28b9992d676d40aa0d2fe912e73b192769)

**Comment by rhopp** [comment]
cc @dmytro-ndp @eivantsov @nickboldt @slemeur

**Comment by ibuziuk** [comment]
@skabashnyuk probably we should also include https://github.com/eclipse/che/pull/12489

**Comment by ibuziuk** [comment]
@rhopp up to you, but the fix seems trivial and we would avoid hassle with two subsequent releases

**Comment by riuvshin** [comment]
@rhopp @sleshchenko cherry-pick of `dda3bf28b9992d676d40aa0d2fe912e73b192769` fails with conflicts...  so I can't backport only this fix.

**Comment by sleshchenko** [comment]
@riuvshin So, you have three options:
- cherry-pick all commits from the following PR https://github.com/eclipse/che/pull/12335;
- resolve conflicts during cherry-picking of `dda3bf28b9992d676d40aa0d2fe912e73b192769`;
- manually do the same changes as `dda3bf28b9992d676d40aa0d2fe912e73b192769` contains on top of 6.17.1;

**Comment by riuvshin** [comment]
yeah, but all of these options are potentially dangerous and require full QE cycle.

**Comment by riuvshin** [comment]
Im not sure which way to go, I would suggest for a merging whole chain of changes. But I can't make that decision.

**Comment by riuvshin** [comment]
AFAIK on last meeting was decided to not do quick release for CRW
