### ISSUE TITLE
Support custom environment variables for components in devfile

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#12555]
### Description
It would be great if users could specify custom environment variables to be pushed into containers running the components.

This would be especially useful for components of type `dockerImage` that could be "configured" this way.

Reference devfile example: https://github.com/redhat-developer/devfile/blob/master/Devfile.yaml

**Comment by metlos** [comment]
Note that this should honor also #12577

**Comment by skabashnyuk** [comment]
Implemented for ```dockerImage``` tool

**Comment by tolusha** [comment]
It is necessary to add ability to set env variables for `chePlugin` component. 
Currently I am working on redirection requests from a sidecar container to a dev container. 
And env variable is used to set a dev container name which will be used farther in the code.

**Comment by kameshsampath** [comment]
it will be nice to have this support on `type: kubernetes` e.g. https://gist.github.com/kameshsampath/33c4af002b9491ea57aa54e57d7fc3c6

**Comment by metlos** [comment]
So we have requests to support this in `kubernetes` components as well as `chePlugin` (also requested in https://github.com/eclipse/che/issues/14343). Given `cheEditor` is mostly `chePlugin` in disguise and `openshift` is `kubernetes` on steroids, we might as well support this everywhere (as the original description of this issue suggests :) ).

**Comment by skabashnyuk** [comment]
@metlos does it make sense to keep https://github.com/eclipse/che/issues/14343 or should we close it as "duplicate"?

**Comment by skabashnyuk** [comment]
After discussing this task with @l0rd  @metlos @sleshchenko  we decided to not to make things too complex that is why we want to populate environment variable to all containers that k8s/Openshift component provides.

**Comment by gorkem** [comment]
@skabashnyuk can you clarify? Does that mean that setting env variable on the k8s component will propagate to all the containers including editors and plugins?

**Comment by skabashnyuk** [comment]
@gorkem for all containers that k8s component provides(not all that defined in devfile). For example https://github.com/redhat-developer/devfile/blob/master/Devfile.yaml#L31-L37 it would be all containers provided petclinic.yaml and matched selector.

**Comment by skabashnyuk** [comment]
Covered by
- Support env for components of type kubernetes/openshift #15121
- Support env for components of type chePlugin and cheEditor #14343
