### ISSUE TITLE
Empty log file when project failed to create.

### ISSUE THREAD

**Issue by cloorc** [eclipse-che/che#1255]
Maybe the network a little problem result in import project from github failure. When I try to download the log file from `Problem? download logs` I found it was empty every time. Is there something wrong in my computer ?

OS: Win7 64
Start: `che run`

**Comment by TylerJewell** [comment]
@ashumilova

**Comment by cloorc** [comment]
@ashumilova Not always empty but failed to create a project from github.

**Comment by ghost** [comment]
Let's continue discussion in this issue - https://github.com/eclipse/che/issues/1260
