### ISSUE TITLE
Support clonePath in devfile

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#12557]
### Description

Currently, all projects are cloned into direct subdirectories of `CHE_PROJECTS_ROOT`. This can be problematic for some tooling. Go, for example, requires projects to be cloned in a specific location under the root that corresponds to the repository in which the code is hosted.

We can support this in devfile by  being able to specify a `clonePath` property that would be understood as a relative path.

The code would then be cloned to `$CHE_PROJECTS_ROOT/<clonePath>`.

**Comment by benoitf** [comment]
hello
is it checkoutPath or clonePath/cloneDir ?
AFAIK checkout in `git` is for switching branch

**Comment by metlos** [comment]
@benoitf I'm an old guy :) `clonePath` works equally well for me

**Comment by metlos** [comment]
I've changed `checkoutPath` to `clonePath` in the PR title and description. Thanks for the suggestion @benoitf !

**Comment by benoitf** [comment]
@metlos thanks.

**Comment by metlos** [comment]
Closing as this is now merged.
