### ISSUE TITLE
Dashboard does not update WorkspaceConfig after fixing JSON format

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12550]
### Description
Dashboard does not update WorkspaceConfig after fixing JSON format.

### Reproduction Steps
1. Create Che7 workspace.
2. Open newly created workspace on `Dashboard#Config`.
3. Paste 
```json
  "commands": [
    {
      "commandLine": "echo Hello From Exec Plugin",
      "name": "hello-plugin",
      "attributes": {
        "previewUrl": "",
        "goal": "Build",
        "plugin": "che-machine-exec-plugin:0.0.1"
      },
      "type": "mvn"
    }
  ]
```
instead of 
```
"commands": [],
```
4. Check that dashboard report an issue about invalid JSON:
```SyntaxError: Unexpected string in JSON at position 1185```
5. Fix JSON buy putting `,` after commands array.
6. Wait a few seconds to give Dashboard a chance to update WorkspaceConfig.
7. Reload `Dashboard#Config` page.
Expected: Workspace config contains updated commands list.
Actual: Workspace config contains empty commands list.

<details>
<summary>See screencast</summary>

![commandsinvalidjson](https://user-images.githubusercontent.com/5887312/51969538-59589400-247d-11e9-80b4-a1bbe46c72c9.gif)
</details>

**OS and version:**    
Multi-User Che 6.18.0-SNAPSHOT

**Diagnostics:**

**Comment by ashumilova** [comment]
> "commands": [],
