### ISSUE TITLE
Cleanup che-plugin.yaml fields left for backward compatibility

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12566]
### Description
Remove fields: 
- https://github.com/che-incubator/che-theia-dev-plugin/blob/master/etc/che-plugin.yaml#L19
- https://github.com/ws-skeleton/che-editor-theia/blob/master/etc/che-plugin.yaml#L41
- https://github.com/ws-skeleton/che-editor-jupyter/blob/master/etc/che-plugin.yaml#L26
- https://github.com/eclipse/che-editor-gwt-ide/blob/master/etc/che-plugin.yaml#L80
- https://github.com/ws-skeleton/che-editor-eclipseide/blob/master/etc/che-plugin.yaml#L23
- https://github.com/dirigiblelabs/dirigible-che-editor-plugin/blob/master/etc/che-plugin.yaml#L44
- https://github.com/eclipse/che-plugin-registry/blob/master/plugins/org.eclipse.che.vscode-sonarlint/0.0.1/meta.yaml#L10

Rename fields:
- https://github.com/ws-skeleton/che-service-plugin/blob/master/assembly/etc/che-plugin.yaml#L8
- https://github.com/ws-skeleton/che-service-plugin/blob/master/assembly/etc/che-plugin.yaml#L10

**Comment by ibuziuk** [comment]
@garagatyi  are you ok to close this issue in favour of https://github.com/eclipse/che/issues/12908 ?

**Comment by garagatyi** [comment]
Absolutely
