### ISSUE TITLE
Show a warning when starting an ephemeral workspace

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12565]
### Description

When a user starts an ephemeral workspace he should be informed that:

> Your are starting an ephemeral workspace. All changes to the source code will be lost when the workspace is stopped unless they are pushed to a source code repository.

and the status bar of the IDE should be different color and indicate that the workspace is in ephemeral mode.

**Comment by ibuziuk** [comment]
@ashumilova could you please clarify in which release this functionality is planned to be delivered

**Comment by ashumilova** [comment]
@ibuziuk message in dashboard can merge today - and it can go to current release, changes in Theia - not ready yet to be merged today.

**Comment by ashumilova** [comment]
you need it ASAP, right?

**Comment by ibuziuk** [comment]
well, not ASAP, but during the next #163 sprint

**Comment by ashumilova** [comment]
okay, understood - will do
