### ISSUE TITLE
Che-theia: progress in status bar when performing any git clone (factory, workspace sync, git clone command)

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#12564]
### Description
At the moment, no progress is shown when a Git clone is performed. This may be annoying for big progress where user doesn't know what is going on.

**Comment by vitaliy-guliy** [comment]
I would be a good improvement!

**Comment by benoitf** [comment]
I think I already read that improvement issue somewhere but I am not finding the issue anymore so maybe I dreamed

**Comment by benoitf** [comment]
https://github.com/theia-ide/theia/issues/759

**Comment by benoitf** [comment]
and https://github.com/theia-ide/theia/issues/3631
