### ISSUE TITLE
Wrong behavior with Testing Stack widget

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#12567]
### Description
Wrong behavior with Testing Stack widget.

### Reproduction Steps
1. Choose Stacks. Select the 'Che 7' stack
2. Open 'Che 7' Stack details. Click the 'Test' button
3. Skeep 'Import projects form'. Just click 'Test Workspace'
4. Wait until the test workspace have started 
![screenshot from 2019-01-31 12-20-36](https://user-images.githubusercontent.com/6310786/52050087-1a4b4100-2558-11e9-83f8-e31a6c2d73ea.png)
![screenshot from 2019-01-31 11-58-12](https://user-images.githubusercontent.com/6310786/52050096-1fa88b80-2558-11e9-85b1-cd25fd665410.png)

### Expected behavior:
Expected a Theia editor from the 'CHE 7' stack config

### Observed behavior:
Got the 'Eclipse GWT IDE' editor inside the testing workspace widget with the  'ws/theia-ide' container inside.
![screenshot from 2019-01-31 13-27-02](https://user-images.githubusercontent.com/6310786/52051498-6f895180-255c-11e9-9021-73f263f5372d.png)

### Che version:   [6.18.0]

**Comment by olexii4** [comment]
https://github.com/eclipse/che/issues/12511

**Comment by ashumilova** [comment]
Closing due to stack overall changes
