### ISSUE TITLE
che-theia: factory, theia plugins are not loaded sometimes

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#12581]
### Description
Sometimes, it looks like when running a factory (with theia editor - che7), theia plugins are not started.

### Reproduction Steps
- Minikube and chectl
- create and open the factory https://github.com/sunix/devfiles/blob/master/che-in-che/factory-che-theia-builder.json
- normally, once the theia editor has started, this factory should clone projects and perform few actions. But it doesn't. Refreshing the browser, theia is working as usual: factory plugin is running and projects are cloned. This may also affect other plugins

**Comment by slemeur** [comment]
super important, should be taken into next sprint cc @evidolob

**Comment by sunix** [comment]
Tried several time with che-theia master but seems to work fine now, I will try with multi-user mode but i think we can close it

**Comment by sunix** [comment]
Tested with multiuser + Theia editor:master it seems it works fine now
```
    "attributes": {
      "editor": "org.eclipse.che.editor.theia:master",
      "plugins": "che-machine-exec-plugin:0.0.1"
    },
```
