### ISSUE TITLE
How to give user only read permissions?

### ISSUE THREAD

**Issue by tsjfd** [eclipse-che/che#12603]
### Description

I want to give some users only read permissions to some workspaces without allowing them to create new workspaces, create / modify stacks etc.. Is this possible?

### Reproduction Steps

I have added a user via key cloak and I can log in as the new user but this user can create new stacks workspaces etc.. I could share workspaces but I have no idea how I can restrict permissions. I have fiddle around with the rest api but my user has still write permissions. 

**OS and version:**    

Che 6.17.1

**Comment by sleshchenko** [comment]
> without allowing them to create new workspaces

You can set allowed workspaces for them to 0.
The default limit is `-1`(non-limited). You can override the default limit by setting the corresponding environment variable for Che Server `CHE_LIMITS_USER_WORKSPACES_COUNT`.
Also, you can override system-wide limit for a particular user. Under system admin, do the following request
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer {TOKEN}' -d '{
  "resources": [
    {
      "type": "workspace",
      "amount": 0
    }
  ],
  "accountId": "b07e3a58-ed50-4a6e-be17-fcf49ff8b242"
}' 'http://che-eclipse-che.192.168.99.100.nip.io/api/resource/free'
```
Where `accoundId` is user identifier
The following swagger method [http://che-eclipse-che.192.168.99.100.nip.io/swagger/#!/resource-free/storeFreeResourcesLimit](http://che-eclipse-che.192.168.99.100.nip.io/swagger/#!/resource-free/storeFreeResourcesLimit)


> create stacks

There is no ability to deny users to create their own personal stacks. But they are not able to create public visible stacks by default.

> modify stacks

Non-admin users are able to modify only their personal stacks. It should not be an issue.

Feel free to ask if you faced any issue or need any additional information.
