### ISSUE TITLE
Browser tab crash after workspace start fail

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#12616]
### Description
Sometimes after workspace start fail many requests are produced which causes tab hung or crash or even browser freeze.

### Reproduction Steps
There is no clear steps to reproduce the bug it may occur sometimes.
It was faced after workspace start failure when user doesn't do anything after fail or switches to dashboard tab (`Workspaces` for example).
Number of requests grows with time. It starts from a dozen requests per second and rise with time up to 10000 requests per second.
![requests](https://user-images.githubusercontent.com/15607393/52355274-b84c7900-2a3a-11e9-8164-27c7f4a76701.gif)

## Screencast
Reproduced on `Workspaces` tab of dashboard after workspace start failure:
![start1](https://user-images.githubusercontent.com/15607393/52354484-30b23a80-2a39-11e9-8f98-0f6506627abf.gif)

Reproduced after workspace start failure (loader page):
![start2](https://user-images.githubusercontent.com/15607393/52354572-5e977f00-2a39-11e9-9b00-88cd506c23b7.gif)

I've seen some web socket related errors (do not know if related):
![ws-error](https://user-images.githubusercontent.com/15607393/52354715-9c94a300-2a39-11e9-8c48-5c908fbc0c26.png)

**Comment by sleshchenko** [comment]
I guess it duplicates the existing issue https://github.com/eclipse/che/issues/12063. @mmorhun Please verify and close this one, feel free to add any details which may be missing in existing issue.

**Comment by mmorhun** [comment]
@sleshchenko I cannot say for sure is it duplicate or not, but in that issue title is said that che server was unreachable. But when I reproduced the problem described in this issue the che server worked and was green in kubernetes dashboard. Also after tab crash I reopened dashboard without problems (which mean that the server reachable).

**Comment by sleshchenko** [comment]
@mmorhun You're right. In your example, workspaces servers are not reachable, so I guess issues is caused by the same component. I'm OK with leaving two issues opened since the issue is similar but reproduction steps are different.
