### ISSUE TITLE
authentication is required but no credentialsprovider has been registered

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#12618]
Hi the community,
    Wwe installed eclipse che, with gitlab and many others software for our platforms. When I create a private repository and set my username and email using the Eclipse che UI under` Preferences > Git > Commiter`, I got an error : `authentication is required but no credentialsprovider has been registered`.

  When I use the terminal, the terminal ask for my username and password, and that's fine. 
  How could I clone my private repository from Gitlab using che user interface ?

**Comment by KOSSOKO** [comment]
Please, how could we correct it ?

**Comment by sleshchenko** [comment]
I can't find a corresponding UI to provide user/password basic credentails, but API allows it 
![screenshot_20190221_150125](https://user-images.githubusercontent.com/5887312/53170809-b7464a80-35e9-11e9-979f-7ae1c7a4eef5.png)
Parameters should contain username and password 
https://github.com/eclipse/che/blob/8b1ffc51d969cf05294365ef88bc3f81f2f01863/wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java#L163-L168

@vparfonov @vinokurig Maybe you know if there is UI to specify git basic credentials?

**Comment by vinokurig** [comment]
As far as I know there is now way to setup basic authentication via UI, @KOSSOKO may be you could setup SSH keys for your gitlab repository?

**Comment by KOSSOKO** [comment]
@vinokurig I tried with ssh key but I got another issue, I will paste the issue tomorrow.
 In our platform, users are scientists developer. They don't want to generate token, then paste it in Gitlab...So we try to find a solution with username and password.

**Comment by KOSSOKO** [comment]
@sleshchenko , that is to say that we have to develop and build a new Eclipse che to hav ethe plug in GitProjectImporter ?

**Comment by sleshchenko** [comment]
@KOSSOKO I think the reason why basic git credentials are not supported by Che is that it is not secure to store bare users credentials.
The ideal solution here would be to implement GitLabOauth authentication, like github has https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/plugins/plugin-github/che-plugin-github-oauth2/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticator.java#L35
@vinokurig Am I correct that IDE will show Github login page if a private repository is specified?

And of course, you can have your own Che packaging with your own `GitImporter` or `BareCredentialsProvider` implementation.
