### ISSUE TITLE
Missing mapping between Theia plug-in endpoint port and exposed url from workspace information

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#12611]
### Description
when declaring inside a editor plug-in in Che7 workspaces:

```json
endpoints:
 -  name: "theia"
    public: true
    targetPort: 3100
```

at runtime I can grab some info at `/api/workspace/<id-of-workspace>`
which returns
```json
"theia": {
"url": "https://route-fbenoit-1-che.starter-us-east-2.openshiftapps.com",
"attributes": {
"cookiesAuthEnabled": "true",
"internal": "false",
"secure": "true",
"type": "ide"
```

What I would like is a way to grab from API that `theia` endpoint was for the port `3100` 
So I could see that theia is for port `3100` and grab the exposed URL.

It could be useful for clients to grab that information.
could be in the attributes
like:
```json
"targetPort": "3100"
```
 or
```json
"configPort": 3100
```
For Che6 workspace we had that mapping with `workspace.config`

**Comment by garagatyi** [comment]
makes sense to me. How important it for your flow? Is it essential for Che 7 beta, GA?

**Comment by benoitf** [comment]
thx for commenting the issue @garagatyi 

For now I was able to workaround that but it will be great to have (will make my code smaller ^^)
I didn't put any severity on it as I used workaround but it will be a great to have (so for GA or after)

BTW I don't think it's really hard to implement. I think ws-master has all the information

**Comment by garagatyi** [comment]
Yeah, I found the place, just need to check
