### ISSUE TITLE
Move all che CI out of eclipse public Travis CI 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12625]
### Description
We need to revise our CI configuration and make sure that we are not using eclipse public Travis CI. 
Waiting for more than a day for a CI job to start I think it's not acceptable.

**Comment by benoitf** [comment]
maybe use of a new eclipse-che github organization ? (so jobs are shared only for eclipse-che org)

**Comment by garagatyi** [comment]
AFAIK CircleCI provides jobs queue on a per-project basis. And Eclipse Hawkbit leverages CircleCI   https://github.com/eclipse/hawkbit/blob/master/.circleci/config.yml  
I created an issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=544013#c1 but haven't received a response even though a week has passed. 
@dneary Do you happen to know how it is possible to get someone from the foundation to comment on my issues?

**Comment by l0rd** [comment]
Both @benoitf and @garagatyi suggestions are valid. I would proceed in parallel.

**Comment by garagatyi** [comment]
:+1: to proceed with both - more options is better
