### ISSUE TITLE
New Che 7 Stacks

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12620]
### Description

For Che 7 we want to release some new stacks that use the new ws.next based model and theia as editor.

## Stacks guidelines

- User runtime components:
  - **Use official images**: instead of building and maintaining our own java, python, go etc...docker images we should rather leverage the official upstream ones (usually on the DockerHub). That has 2 advantages (1. we do not need to maintain them 2. we make sure that Che workspaces work with images built by the community and not only with images from che-dockerfiles) and one drawback (there may be some caveates like permissions and tools that we need to deal with).
  - **Override entrypoint**: usually the official images have a terminating entrypoint. To avoid that the container exits right away we have to override it:
    ```json
    "containerCommand": "['sleep']",
    "containerArgs": "['infinity']"
    ```
  - **Specify images versions** and ideally we should use image SHA1 hash
- Memory settings. Workspaces are composed by an editor (usually Theia), one or more language servers and other plugins and a user runtime. We should provide enough memory for all of these components but we should avoid to require more than 4GB (3GB is current che.openshift.io limit):
  - **Theia: 512MB** should be enough (`"sidecar.org.eclipse.che.editor.theia.memory_limit": "512Mi"`)
  - Language servers and other plugins: it depends on the particular plugin but every plugin should be tested to find the lower limit in the particular stack with the samples we provide. Once we have found the right value the memory limit should be set as a workspace configuration attribute: `"sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "1024Mi"`  
  - User runtimes: same as language servers and other plugins but the memory should be set as a container attribute: `"memoryLimitBytes": "512000000"`.
- Use **Theia version `next`**
- No default commands: it doesn't make sense to add default commands at the stack level. Commands should be defined at sample level.
- No servers: a Theia plugin is able to automatically figure out what ports need to be exposed, hence there is no need to spcify servers and preview urls anymore
- Tips to fix issues on OpenShift
  - Set `HOME=/home/user`: arbitrary users don't have a home folder defined in `/etc/passwd` hence we should define one and the convention is to set it to `/home/user`
  - Use volumes to bypass folders permissions: arbitrary users have restrictive access to some folders in runtime container. If the processes running in the container (e.g. `mvn`) need to access the folder a trick is to mount the folder as a volume:
  ```json
  "volumes": {
    "m2": {
      "path": "/home/user/.m2"
  }}
  ```
  - define PS1: to have a nicer terminal we can configure `PS1` environment variable
- Samples
  - Macro do not work on Theia (`${current.project.path}`): use environment variables instead and use the sample folder. For example: `cd ${PROJECTS_PATH}/java-web-simple`.
  - As for the user runtime components we should prefer samples that we do not need to maintain (i.e. vertx samples)

### Java

- [x] Java Maven stack
  - [x] the stack: [maven official image](https://hub.docker.com/_/maven) + [Java LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.vscode-redhat.java) (@l0rd)
  - [x] sample1: [Console Java Simple](https://github.com/che-samples/console-java-simple) (@l0rd)
  - [x] sample2: [Web Java Spring](https://github.com/che-samples/web-java-spring.git) (@l0rd)
  - [x] sample3: [OpenShift.io vert.x booster](https://github.com/openshiftio-vertx-boosters/vertx-http-booster) (@l0rd)
  - [ ] sample4: [The Game Of Life](https://rosettacode.org/wiki/Conway's_Game_of_Life#Java_10) (@l0rd)
  - [ ] sample5: [VertX Samples](https://github.com/vert-x3/vertx-examples) (@l0rd)
- [x] Java Gradle stack (@l0rd)
  - [x] the stack: [gradle official image](https://hub.docker.com/_/gradle) + [Java LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.vscode-redhat.java) @l0rd
  - [x] sample1: [Console Java Simple](https://github.com/che-samples/console-java-simple) @l0rd
  - [x] sample2: [Web Java Spring](https://github.com/che-samples/web-java-spring.git) @l0rd
- [ ] Java PostgreSQL stack (`maven` and `postgres` images as runtime and Java LS) @l0rd
  - [x] the stack: [maven official image](https://hub.docker.com/_/maven) + [postgres official image](https://hub.docker.com/_/postres) + [Java LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.vscode-redhat.java)
  - [ ] sample1: [Spring Boot Real World Example App](https://github.com/gothinkster/spring-boot-realworld-example-app) @l0rd
  - [ ] sample2: [PetClinic Multicontainers](https://github.com/che-samples/web-java-spring-petclinic/tree/) @l0rd
- [x] Apache Camel stack https://github.com/eclipse/che/issues/13182
  - [x] the stack: [maven official image](https://hub.docker.com/_/maven) + Camel LS + [Java LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.vscode-redhat.java)
  - [x] the sample: [Camel+SpringBoot](https://github.com/apache/camel/tree/master/examples/camel-example-spring-boot)
- [ ] Quarkus.io stack (quarkus.io image (**TBD**) as runtime and Java LS)
  - [ ] the stack: [quarkus official image?](https://quay.io/repository/quarkus/centos-quarkus-maven) + [Java LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.vscode-redhat.java)
  - [ ] the sample: [Quarkus.io example](https://github.com/quarkusio/quarkus-quickstarts.git)

### NodeJS

- [x] Node 11 stack
  - [ ] the stack: [node official image](https://hub.docker.com/_/node) + [Node Debug](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.node-debug2/1.31.6) + [TypeScript LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.typescript/1.30.2) @l0rd
  - [ ] sample1: [React real world example](https://github.com/gothinkster/react-redux-realworld-example-app) @l0rd
  - [ ] sample2: [VueJS Real World Example App](https://github.com/gothinkster/vue-realworld-example-app) @l0rd
  - [ ] sample3: [Angular Real World Example App](https://github.com/gothinkster/angular-realworld-example-app) @l0rd
- [ ] Node 11 Mongo stack
  - [ ] the stack: [node official image](https://hub.docker.com/_/node) + [mongo official image](https://hub.docker.com/_/mongo) + [Node DBA](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.node-debug2/1.31.6) + [TypeScript LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.typescript/1.30.2) @l0rd
  - [ ] the sample: [Node/Express/Mongo Real World Example App](https://github.com/gothinkster/node-express-realworld-example-app) @l0rd

### Python

- [x] Python 3 stack  #12944
  - [x] the stack: [python official image](https://hub.docker.com/_/python) + [Python LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-python.python/2019.2.5433) @tolusha
  - [x] sample1: [Python Hello World](https://github.com/che-samples/console-python3-simple.git) @tolusha
  - [x] sample2: [Django real world example](https://github.com/gothinkster/django-realworld-example-app)) @tolusha 

### .NET Core

- [x] .NET Core stack @svor 
  - [x] the stack: [.NET Core official image](https://hub.docker.com/_/microsoft-dotnet-core) + [OmniSharp](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/che-omnisharp-plugin/0.0.1)
  - [x] sample1: [C# Hello World](https://github.com/che-samples/dotnet-web-simple.git)
  - [x] sample2: [ASP.NET Core real world example App](https://github.com/gothinkster/aspnetcore-realworld-example-app)

### Go

- [x] Go stack https://github.com/eclipse/che/issues/13098
  - [x] the stack: [Golang official image](https://hub.docker.com/_/golang) + [Go LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.go)
  - [x] sample1: [Go Web Sample Application](https://github.com/golang/example/tree/master/outyet)
  - [ ] sample2: [Revel Chat samples](https://revel.github.io/examples/chat.html) seems to be broken, see https://github.com/eclipse/che/pull/13176
  - [ ] sample3: K8S Operator sample **TBD**
  - [x] sample4: [Go + Echo real world example app](https://github.com/xesina/golang-echo-realworld-example-app)

### PHP 
- [x] the stack: [PHP official image](https://hub.docker.com/_/php) + [PHP LS](https://github.com/eclipse/che/issues/12772)
  - [x] sample1: [Hello World](https://github.com/che-samples/web-php-simple)
  - [x] sample2: [Laravel Real World example App](https://github.com/gothinkster/laravel-realworld-example-app)
  - [x] sample3: [Symfony demo application](https://github.com/symfony/
  - [x] sample4: [Sample CRUD PHP+MySQL](https://github.com/taniarascia/pdo/tree/master)

### Che Development
- [ ] Che-Theia Developer stack (c.f. [sunix devfile](https://github.com/sunix/devfiles/blob/master/che-in-che/che-theia.devfile.yaml))
  - [ ] the stack: [che-theia-dev official image](https://hub.docker.com/r/eclipse/che-theia-dev:nightly) + [Node DBA](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.node-debug2) + [TypeScript LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.typescript/) + [YAML LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/redhat.vscode-yaml/)
  - [ ] the sample: [Che-Theia](https://github.com/eclipse/che-theia.git) + [Theia](https://github.com/theia-ide/theia.git) + [Theia Generator](https://github.com/ws-skeleton/che-theia-generator.git) + [Devfiles](https://github.com/sunix/devfiles.git)
- [ ] Che Server Developer stack (c.f. [official devfile](https://github.com/eclipse/che/blob/master/devfile.yaml))
  - [ ] the stack: [che-dev image](https://hub.docker.com/r/che-dev:nightly) + [Java LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.vscode-redhat.java)
  - [ ] the sample: [Che](https://github.com/eclipse/che)
- [ ] VS Code Extension developer stack
  - [ ] the stack: **TBD**
  - [ ] vs code extension sample: **TBD**
- [ ] Theia Plugin developer stack
  - [ ] the stack: : **TBD**
  - [ ] theia plugin sample: : **TBD**
- [ ] Che plugin brokers
  - [ ] the stack: [che-plugin-broker image](https://hub.docker.com/r/eclipse/che-plugin-broker) + [Go LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.go)
  - [ ] the sample: [Che Plugin broker](https://github.com/eclipse/che-plugin-broker)
- [ ] Che documentation
  - [ ] the stack: **TBD**
  - [ ] the sample: [Che documentation](https://github.com/eclipse/che-docs)
- [ ] chectl (c.f. [official devfile](https://github.com/che-incubator/chectl/blob/master/devfile.yaml))
  - [ ] the stack: [node official image](https://hub.docker.com/_/node) + [Node DBA](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.node-debug2/1.31.6) + [TypeScript LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.typescript/1.30.2)
  - [ ] the sample: [chectl](https://github.com/che-incubator/chectl)
- [ ] che operator
  - [ ] the stack: [che-plugin-broker image](https://hub.docker.com/r/eclipse/che-plugin-broker) + [Go LS](https://github.com/eclipse/che-plugin-registry/tree/master/plugins/ms-vscode.go)
  - [ ] the sample: [che-operator](https://github.com/eclipse/che-operator)

### Other misc

- [ ] Ansible stack https://github.com/eclipse/che/issues/11877#issuecomment-473233737
- [ ] Rails stack
  - [ ] [Rails real world example app](https://github.com/gothinkster/rails-realworld-example-app)
- [ ] Rust stack
  - [ ] [Rust real world example app](https://github.com/gothinkster/rust-realworld-example-app)

**Comment by l0rd** [comment]
cc @slemeur

**Comment by slemeur** [comment]
Updated with a more complete list to be targeted for GA

**Comment by tsmaeder** [comment]
@l0rd @slemeur no PHP stacks?

**Comment by tsmaeder** [comment]
@l0rd how can we have a camel stack if we don't have a camel plugin yet?

**Comment by tsmaeder** [comment]
About quarkus: if we are talking about building native programs, the target would be any image that has the necessary libraries. In the end, there is no "server" to be installed.

**Comment by tsmaeder** [comment]
Che server dev stack needs Golang, no?

**Comment by slemeur** [comment]
@l0rd + @tsmaeder : Added PHP.

**Comment by nickboldt** [comment]
So will we SUPPORT all these stacks, or will only a subset of these be Red Hat GA-level supported? Right now for CRW 1.x / Che 6 we only support Node8 and Java8, with the rest being community-supported. I've opened https://issues.jboss.org/browse/CRW-225 to track the downstream specs.

**Comment by nickboldt** [comment]
>> Che server dev stack needs Golang, no?

> I don't think so. I think Golang was only used for the exec agent but in Che 7 that's a separate plugin."

Not sure if it's relevant but the Che 6 operator (and the CRW 1.x operator) both rely on golang too:

https://github.com/eclipse/che-operator/blob/master/Dockerfile#L13

**Comment by l0rd** [comment]
@nickboldt good point. I have added a Che operator stack, it should not be part of the che-server stack though.

**Comment by tsmaeder** [comment]
@l0rd @slemeur golang chag example is broken, see https://github.com/eclipse/che/pull/13176. Ok to strike that one?

**Comment by l0rd** [comment]
@tsmaeder +1
