### ISSUE TITLE
Release of Che 7 Beta

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12621]
### Description

At the end of next sprint (in 3 weeks) we should release 2 versions/branches: `6.19.0`/`6.19.x` and `7.0.0-beta.1.0`/`7.0.0-beta.1.x`. Master branch should than use version `7.0.0-beta.2.0-SNAPSHOT` and in branch `6.19.x` we should only commit/cherry pick Che 6 fixes.

@riuvshin @benoitf @nickboldt what do you think?

**Comment by benoitf** [comment]
no issue on my side

**Comment by nickboldt** [comment]
What happens if we need to do a che 6.20 or other future 6.x maintenance between now and August 2019? Would that be done in the 6.19.x branch? Or... do we need a **6.x branch** in addition to 6.19.x and master branches.

Also, 7.0.x-Beta1 sounds like an odd way to branch - that implies the next build will be 7.0.1.Beta1. Should we have a **7.0.0.Beta1x** branch instead, in case we need to do a 7.0.0.Beta1-1 ?

**Comment by l0rd** [comment]
> What happens if we need to do a che 6.20 or other future 6.x maintenance between now and August 2019?

In what circumstances should we need a version `6.20.0`? Can't we just release patch versions when and if we need to do a new "patch" release (e.g. `6.19.1`, `6.19.2` etc...)?

> do we need a **6.x branch** in addition to 6.19.x and master branches.

Yes if we will need a `6.20.0` version we will need such a branch. But if we agree that we won't need it I assume we won't need a `6.x` branch neither.

> Also, 7.0.x-Beta1 sounds like an odd way to branch - that implies the next build will be 7.0.1.Beta1. Should we have a **7.0.0.Beta1x branch** instead, in case we need to do a 7.0.0.Beta1-1 ?

You are right. Calling the branch `7.0.0.Beta1x` is much better.

**Comment by l0rd** [comment]
After looking at https://semver.org/#spec-item-9 I think we should call the version `7.0.0-beta.1.0` (and the branch `7.0.0-beta.1.x`)

**Comment by nickboldt** [comment]
What about something simpler like `7.0-beta1.x`, with only 3 x.y.z version segments? Do you really need 5 segments?

**Comment by l0rd** [comment]
@nickboldt  I am ok with `7.0.0-beta1x` as well. Thanks for your feedbacks. 

@riuvshin I would apreciate if you could provide you opinion on this approach.

**Comment by riuvshin** [comment]
done
