### ISSUE TITLE
Unable to create a project 

### ISSUE THREAD

**Issue by dclong** [eclipse-che/che#12622]
### Description

I cannot create a project in a workspace. The `Create` button is grayed out. 

### Reproduction Steps

1. Pull the latest eclipse che image.
        sudo docker pull eclipse/che

2. Create a a folder and change its permission to 777
        sudo mkdir -p /workdir/che
        sudo chmod 777 /workdir/che

3. Start eclipse che using the command below. 
        sudo docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /workdir/che:/data eclipse/che start

4. Visit Eclipse Che in a browser at port 8080.

5. Create a new workspace (I tried both Java and Python).

6. Click "Create Project..." to create a new project.

**OS and version:**    
The Docker container is started on a Ubuntu 16.04 server. I visited the Eclipse Che service in both Firefox 65.0 and Chrome 72 on Mac Mojave 10.14.3.

**Comment by htjain** [comment]
I am also seeing same issue.

**Comment by johnnywiller** [comment]
I'm having the same issue, I'm using:
**Docker version 18.09.5, build e8ff056
Che 7.0.0-beta-3.0**

**Comment by pbanavara** [comment]
Seeing the same issue as well. Tried a Java+Mysql multi machine setup.
