### ISSUE TITLE
Blank page when clicked "Open in IDE"

### ISSUE THREAD

**Issue by dimircin** [eclipse-che/che#1262]
I've packaged eclipse che with mvn clean install under che/assembly from https://github.com/eclipse/che and no error occurred. Then I run just as described in readme.md
mvn clean install
che\assembly\assembly-main\target\eclipse-che-4.2.2.

Then, started che with ./che.sh start with no errors. 

> Could not find an existing docker machine named che.
> Creating docker machine named che... Please be patient, this takes a couple minutes the first time.
> Successfully started docker machine named che...
> Setting environment variables for machine che...
> Docker is configured to use docker-machine named che with IP 192.168.99.100...
> ###### ######## HOW TO CONNECT YOUR CHE CLIENT
> 
> After Che server has booted, you can connect your clients by:
> 1. Open browser to http://localhost:8080, or:
> 2. Open native chromium app.
> ###### 
> 
> Using CATALINA_BASE:   /Users/demircancoskun/smart-card-ide/eclipse-che-4.2.2/eclipse-che-4.2.2/tomcat
> Using CATALINA_HOME:   /Users/demircancoskun/smart-card-ide/eclipse-che-4.2.2/eclipse-che-4.2.2/tomcat
> Using CATALINA_TMPDIR: /Users/demircancoskun/smart-card-ide/eclipse-che-4.2.2/eclipse-che-4.2.2/tomcat/temp
> Using JRE_HOME:        /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
> Using CLASSPATH:       /Users/demircancoskun/smart-card-ide/eclipse-che-4.2.2/eclipse-che-4.2.2/tomcat/conf/:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/lib/tools.jar:/Users/demircancoskun/smart-card-ide/eclipse-che-4.2.2/eclipse-che-4.2.2/tomcat/bin/bootstrap.jar:/Users/demircancoskun/smart-card-ide/eclipse-che-4.2.2/eclipse-che-4.2.2/tomcat/bin/tomcat-juli.jar
> Tomcat started.

i have created workspace with ready-to-go stack for JAVA. Everything went well. However, when i clicked on "Open in IDE" blank page appears.

Here is the log file

> 127.0.0.1 - - [14/May/2016:19:24:35 +0300] "GET /ide/api/stack/aspnet-default/icon HTTP/1.1" 200 3370
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "POST /ide/api/recipe HTTP/1.1" 201 500
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "POST /ide/api/recipe HTTP/1.1" 201 500
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "POST /ide/api/workspace?account=&attribute=stackId:java-default HTTP/1.1" 201 -
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "POST /ide/api/workspace?account=&attribute=stackId:java-default HTTP/1.1" 201 -
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "GET /ide/api/workspace/workspaceogni7xeloydg0zs6 HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "GET /ide/api/workspace/workspaceogni7xeloydg0zs6 HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "GET /ide/api/ws/workspaceogni7xeloydg0zs6 HTTP/1.1" 101 -
> 127.0.0.1 - - [14/May/2016:19:24:39 +0300] "GET /ide/api/ws/workspaceogni7xeloydg0zs6 HTTP/1.1" 101 -
> 127.0.0.1 - - [14/May/2016:19:24:44 +0300] "POST /ide/api/workspace/workspaceogni7xeloydg0zs6/runtime?environment=default HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:24:44 +0300] "POST /ide/api/workspace/workspaceogni7xeloydg0zs6/runtime?environment=default HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:24:44 +0300] "GET /ide/api/recipe/recipelh6558oupe32miyf/script?token=dummy_token HTTP/1.1" 200 -
> 192.168.99.100 - - [14/May/2016:19:24:57 +0300] "GET /ide/api/workspace/workspaceogni7xeloydg0zs6 HTTP/1.1" 200 2231
> 127.0.0.1 - - [14/May/2016:19:24:57 +0300] "GET /ide/api/workspace HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:24:57 +0300] "GET /ide/api/workspace HTTP/1.1" 200 -
> 192.168.99.100 - - [14/May/2016:19:24:58 +0300] "GET /ide/api/ HTTP/1.1" 200 -
> 192.168.99.100 - - [14/May/2016:19:24:58 +0300] "GET /ide/api/eventbus/?token=dummy_token HTTP/1.1" 101 -
> 127.0.0.1 - - [14/May/2016:19:25:00 +0300] "GET /ide/api/workspace/workspaceogni7xeloydg0zs6 HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:25:00 +0300] "GET /ide/api/workspace/workspaceogni7xeloydg0zs6 HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:27:24 +0300] "GET /ide/default?uid=263534 HTTP/1.1" 200 -
> 127.0.0.1 - - [14/May/2016:19:27:24 +0300] "GET /ide/_app/IDE.css HTTP/1.1" 304 -
> 127.0.0.1 - - [14/May/2016:19:27:24 +0300] "GET /ide/_app/5728C7012EFA14D0C633AE2CA72DEEB1.cache.js HTTP/1.1" 404 1094

Che running on later Mac OS El Capitan.

Also tried the same scenario with Java Debian Stack Library.

Cheers

**Comment by dimircin** [comment]
after several (may be 100 :)) attempt now it is opened. Sorry for inconvenience.

**Comment by TylerJewell** [comment]
What was the resolution?

**Comment by dimircin** [comment]
Not sure. i have changed nothing! Just tried to delete workspace and created again and again. At the and i had the IDE view.

**Comment by TylerJewell** [comment]
Does this also happen when you run the vagrant or docker version?

**Comment by dimircin** [comment]
Just tried to run with vagrant and it works normally. Nowadays i am playing with installation on Mac OS, linux natively and AWS EC2 Ubuntu. Hope to share my experiences soon.
