### ISSUE TITLE
Unable to start a workspace if k8s/OS object are created in a different from Che namespace

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12626]
### Description
Unable to start a workspace if k8s/OS object are created in a different from Che namespace.

It happens because K8s API responds with an error that unable to create a resource in namespace workspace specific namespace because `che` namespace is predefined in object meta.

![screenshot from 2019-02-07 13-33-20](https://user-images.githubusercontent.com/5887312/52409362-f9499980-2add-11e9-8598-3be979ba4380.png)

I guess it is related with https://github.com/eclipse/che/pull/12583 because debugging shows that it is a line which set namespace che for recipe objects
https://github.com/eclipse/che/blob/26ce0947d9b00de16c55097e0c8fa264e7f6b509/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java#L103

![screenshot from 2019-02-07 13-34-22](https://user-images.githubusercontent.com/5887312/52409448-2f871900-2ade-11e9-93b2-29822d1a22e2.png)

### Reproduction Steps
1. Deploy Che with `CHE_INFRA_KUBERNETES_NAMESPACE=""` for k8s infra or `CHE_INFRA_OPENSHIFT_PROJECT=""` for OS infra.
2. Try to start workspace from Che 7 stack.

**OS and version:**    
Che 6.18.0-SNAPSHOT. I guess 6.17.0 has the same issue.

**Comment by garagatyi** [comment]
Shouldn't we have a provisioner that ensures that nothing gets created in a wrong namespace. It might be a security improvement.

**Comment by sleshchenko** [comment]
@garagatyi `KubernetesEnvironmentFactory` is a component which set `che` namespace, it's not provided by user. To avoid confusing I guess it would be better to set null values for namespace field in factory but not on provisioning step.
On the provisioning step, we could set workspace specific namespace to guarantee that there is no try to create a resource is a wrong workspace.

**Comment by garagatyi** [comment]
> On the provisioning step, we could set workspace specific namespace to guarantee that there is no try to create a resource is a wrong workspace.

It is exactly what I meant

**Comment by ibuziuk** [comment]
@rhopp @nickboldt please, comment if it's a blocker for CRW ?

**Comment by rhopp** [comment]
I just tried to reproduce this using latest CRW bits, but I'm having different error (starting normal "che6" workspace):
https://pastebin.com/17qUeKWx

I've deployed this to OSD with this config: 
`oc describe cm/che`: https://pastebin.com/2J7TWrP6

@sleshchenko Any idea why I might be having this error? Might be different bug, right?

**Comment by sleshchenko** [comment]
@rhopp This bug affects only workspaces with Kuberentes/OpenShift recipes.
And yes, it's another issue you faced. Something wrong with Che Server/Workspace service account.
