### ISSUE TITLE
Make dashboard e2e tests independent on GWT IDE

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#12628]
### Description
Once GWT IDE will move out of the product to separate repository, we should make sure our tests are separated enough to not depend on anything GWT IDE related. I guess most importantly the dashboard tests will remain, so we should make sure the dashboard tests are not dependent on that.

**Comment by dmytro-ndp** [comment]
FYI: update from Serhii Kabashnyuk:
>> Do we plan to move GWT IDE into separated repo?

> I would say "No" at this moment. GWT IDE in the sidecar is a nice concept, however, it's working only under certain conditions. 
Largest prerequisite is that Workspace/Project API has to be on workspace master in the state that we have at 6.x era.
I believe that would be changed soon.

**Comment by rhopp** [comment]
Closing as lot of this effort was done in #13827 and the remaining work will be done in the same issue.
