### ISSUE TITLE
Workspace stopping by idle timeout does not work on multiuser docker and openshift

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#12636]
### Description
**This issue is not reproduced on single openshift and docker**

**Reproduction Steps:**
1. Before deploying opendshift set timeout for idle workspace stopping - for example ```export CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS=60000```
2. Start workspace and wait for it stopped after set timeout

**Expected behavior:**
Workspace stopped after set timeout

**Observed behavior:**
Workspace is still running

**Failed selenium test:** CheckStoppingWsByTimeoutTest

**Report with reproduced problem:** https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/525/Selenium_20tests_20report/

**Browsers logs:** https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/525/Selenium_20tests_20report/webdriver-logs/org.eclipse.che.selenium.workspaces.CheckStoppingWsByTimeoutTest.checkStoppingByApi_time-1549589816362-millis.log

**Workspace logs:** https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/525/Selenium_20tests_20report/workspace-logs/org.eclipse.che.selenium.workspaces.CheckStoppingWsByTimeoutTest.checkStoppingByApi_time-1549589817199-millis.zip

**OS and version:**
CHE 6.19.0-SNAPSHOT, Fedora 28.0

**Comment by skabashnyuk** [comment]
What kind of workspace?

**Comment by SkorikSergey** [comment]
Simple workspace from Java stack.

**Comment by skabashnyuk** [comment]
When CheckStoppingWsByTimeoutTest start failing? Are you able to identify some range?

**Comment by SkorikSergey** [comment]
The first time the test failed on January 24th.
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/507/

**Comment by skabashnyuk** [comment]
Is this somehow related to infrastructure Docker/Kub/OS?

**Comment by SkorikSergey** [comment]
Workspace stopping works on single docker and openshift.

**Comment by ibuziuk** [comment]
I believe this is a blocker for promotion 6.18.0 to che.openshift.io

**Comment by skabashnyuk** [comment]
>Workspace stopping works on single docker and openshift.

What does this mean? It's not working on k8s?

**Comment by skabashnyuk** [comment]
Might be related to https://github.com/eclipse/che/pull/12387

**Comment by monaka** [comment]
Just FYI. I'm not sure if my case is same, because of my env is customized  (helm deployment with some my patches). But recently I've encountered similar issue.

**Comment by metlos** [comment]
@monaka it seems like you've encountered the same kind of problem. The workspaces were not timing out at all in the multiuser environment...

**Comment by amisevsk** [comment]
Are there any Che server logs?

**Comment by ScrewTSW** [comment]
I was able to confirm that the workspaces are being stopped after the timeout :+1:
