### ISSUE TITLE
Lot of workspaces (50+) (in one account) make dashboard unusable

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#12638]
### Description
When one user has a lot of created (don't have to be started), Eclipse Che starts to be really slow for him and for example he cannot even access newly created workspaces.

- When creating workspace from dashboard, clicking "Create & open" or "Create & continue editing" does absolutely nothing (in UI), but it seems, that the workspace is created.
- Second mouse press on the "Create" button results in message, that the workspace already exists.
- Because of https://github.com/eclipse/che/issues/4312 user cannot access his newly created workspace directly through UI
- Trying to access workspace by going to the right URL results again in message "Workspace does not exist"
- Trying to create another workspace with same name results in message "Workspace already exists"

Thus user is in state, where the workspace exists & does not exist at the same time :-D We call this state "Quantum workspace" and we are first product to ship such workspace :-D

Here's screencast of such behavior: https://youtu.be/VL1NVvhzdQ8

### Reproduction Steps
Run this script: https://gist.github.com/rhopp/2c3851f53f55714337367f650b546082
(don't forget to edit the script with your active token and your che-server url)
After those 70 workspaces are created, go to dashboard and try to create workspace.

**OS and version:**    
Reproduced on che.prod-preview.openshift.io and on CRW 1.0.1

**Comment by ibuziuk** [comment]
this currently affects e2e tests on che.openshift.io 
@ppitonak until the issue is fixed we need to make sure that accounts used for e2e tests do not have more than 10 - 20 workspaces

**Comment by sleshchenko** [comment]
> * Because of #4312 user cannot access his newly created workspace directly through UI

I think it happens because of https://github.com/eclipse/che/issues/9752. Because https://github.com/eclipse/che/issues/4312 is more related to Docker infrastructure.

**Comment by sleshchenko** [comment]
> * Trying to create another workspace with same name results in message "Workspace already exists"

I think this behavior is OK because as we can see on the screencast Workspace is successfully created (201 response code https://youtu.be/VL1NVvhzdQ8?t=18).
Also, we can see that get workspace requests returns 304 Not modified. It means that workspace list is not changed and because of that Dashboard is not able to open newly created workspace.
304 happens because dashboard always fetches the first page with 30 workspaces limit (default limit https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L234)
I think it's Dashboard who cause faced issues. Hope my quick investigation will be useful.

**Comment by rhopp** [comment]
@sleshchenko Yeah... Those were my thoughts too... I've put team/platform just to be sure ;-)

**Comment by l0rd** [comment]
@rhopp should we change the title to "...make **dashboard** unusable"

**Comment by ibuziuk** [comment]
@l0rd I would let @rhopp / @ppitonak to answer but AFAIK dashboard is not used for osio e2e tests (and AFAIK this issues was found after analyzing osio e2e test failures)

**Comment by rhopp** [comment]
That's correct assumption. Changing title now.

**Comment by ibuziuk** [comment]
@rhopp sorry, I do not understand - is it only dashboard issue e.g. creation / starting via API calls works fine ?

**Comment by jswordfish** [comment]
@sleshchenko Thought this may be a dashboard issue - I can't open workspaces beyond 30. I can create workspaces beyond 30 though - but what's the point if I can't use them.

I am using Eclipse Che 7.4.0 v over Kubernates.  Am using this url - https://che-namespace.domian/dashboard/#/ide/che/name to open work space. Is there any other url to be usedinstead of this?
