### ISSUE TITLE
Pre-authorize Git CLI when workspace is created

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#12632]
Some people would like to use Git CLI instead of the Git window for complex operations and out of preference, however the CLI is not pre-authorized with the VCS provider the projects came, which adds additional setup time for the users. This issue has been existing since Che 5 and it would be nice to have the CLI to be authorized on the project's folder context.

**Comment by l0rd** [comment]
@sr229 I agree that's something important. Are you experiencing this even when setting up SSH keys as described [in the doc](https://www.eclipse.org/che/docs/che-6/version-control.html#generateupload-ssh-keys)?

**Comment by sr229** [comment]
@l0rd as far as my experience was with 6.x and below, yes.
