### ISSUE TITLE
Having trouble connecting my github account

### ISSUE THREAD

**Issue by dneary** [eclipse-che/che#12643]
### Description

With 6.19.0 SNAPSHOT (pulled Feb 8 2019), I wanted to start a project using Che 7 dev stack + source code from che-theia-github-plugin, which I have forked to my github account. However, when I click  the "Connnnect to github" button, a pop-up appears, and disappears before I can read it, and I am still not connected to github. The browser is a recent Chrome on Fedora 27, if that makes a difference.

### Reproduction Steps

1. Install Eclipse Che on a local OKD cluster
2. Attempt to create a developer workspace, and connect Che to your github account

For me, this did not work.

**Comment by dneary** [comment]
I have also tried with Firefox. After creating a project and just using git rather than github, the editor says "Source control is not available" when I click on the git link on the left. 

When I open the workspace, I get an alert, saying that the git clone failed, but the message goes by too quickly for me to read all of it, and it is not logged as a problem with the workspace, so I have no idea what went wrong.

**Comment by eivantsov** [comment]
@dneary have you configured GitHub oAuth in your Che instance?

**Comment by l0rd** [comment]
@dneary here is the doc https://www.eclipse.org/che/docs/che-6/version-control.html#github-oauth

@slemeur upstream Che GitHub auth is still something painful we should address.
