### ISSUE TITLE
Use Traefik on helm depoyment.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12645]
### Description

Strictly this is not a bug report but closely it.

The current Helm chart expects Nginx ingress controller have already deployed to the K8s cluster.
But the Nginx ingress provided by Azure AKS have a poor performance, response.
It can't use with production purpose. (It was agreed by at least one engineer working Azure.)

Today I checked Traefik ingress provided by Helm/stable on AKS. And this works well.

AFAIK, Che on Docker multi-user is also using Traefik, not Nginx.
So I think it's strongly better to switch our ingress to Traefik.

**Comment by monaka** [comment]
This is the one-liner used in my deployment. 

```
helm upgrade --install traefik --set rbac.enabled=true,imageTag=1.7.8,kubernetes.ingressEndpoint.useDefaultPublishedService=true,ssl.enabled=true,externalTrafficPolicy=Local stable/traefik
```

And the part of ConfigMap. I'm not checked but annotations start with "nginx.*" may be removable.

```
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class":
    "traefik", "traefik.ingress.kubernetes.io/affinity": "true", "nginx.ingress.kubernetes.io/rewrite-target":
    "/","ingress.kubernetes.io/ssl-redirect": "true","nginx.ingress.kubernetes.io/proxy-connect-timeout":
    "3600","nginx.ingress.kubernetes.io/proxy-read-timeout": "3600"}'
```

**Comment by l0rd** [comment]
@monaka +1. That should be mainly a documentation issue. And maybe something to change on https://github.com/che-incubator/chectl. I mean is changing ingress annotations (the configmap) really required?

**Comment by monaka** [comment]
@l0rd It depends on the cluster configuration but generally "yes". At least `kubernetes.io/ingress.class: "traefik"` should be set. Because some managed K8s services provide their ingress controller by default.

**Comment by l0rd** [comment]
@monaka makes sense. Are you going to provide the PR?

**Comment by monaka** [comment]
@l0rd I'm working to fix another issues on Che. I'll start fixing this issue the first of next month or later.
