### ISSUE TITLE
Arm7 Remote Debug

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1264]
Not sure if I got all the debug setting right but it's not stopping at the markers. Trying a simple console java helloworld. The debugger attaches to host it seems.

java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y ${current.project.path}/target/*.jar
![image](https://cloud.githubusercontent.com/assets/16562450/15276239/039e3d62-1aa8-11e6-9c0d-72a3255f85d7.png)

![image](https://cloud.githubusercontent.com/assets/16562450/15276233/d5dc7542-1aa7-11e6-8da4-20e23e84cb8d.png)

pom file.

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.eclipse.che.examples</groupId>
    <artifactId>console-java-simple</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>hello-app</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>2.4</version>
            <configuration>
              <debug>true</debug>
              <debuglevel>source</debuglevel>
            </configuration>
          </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>org.eclipse.che.examples.HelloWorld</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by ghost** [comment]
@james10174 Can you try adding a threadsleep of 1-2 seconds before printing Hello World in your class? We do have have such an issue with a remote debug - the java gets executed quicker than the debugger manages to get breakpoints. It's a known issue and it will be fixed.

**Comment by james10174** [comment]
@eivantsov Didn't work. 

![image](https://cloud.githubusercontent.com/assets/16562450/15288277/003793f8-1b2f-11e6-8967-fcfb7d484e1b.png)

I also put the following into the terminal and re-ran without success.

echo "set remotetimeout 10" > ~/.gdbinit

![image](https://cloud.githubusercontent.com/assets/16562450/15303136/df2559f0-1b7b-11e6-98a8-0fc94e6d487c.png)

**Comment by ghost** [comment]
@james10174 I was able to reproduce it on my side with Java debugger. Investigating.

This is a known issue (current master). What version do you have?

**Comment by james10174** [comment]
@eivantsov I use the java debugger, jdk1.8.0_91 (container and host) and eclipse-che-4.3.0-RC1-SNAPSHOT.

**Comment by ghost** [comment]
If you use 4.2.2 there's no such an issue there. It's being fixed in master so if you grab the latest nightly in a couple of days, it should be ok.

**Comment by james10174** [comment]
@eivantsov I will wait for the new nightly. Just let me know when it's ready. Thanks.

**Comment by james10174** [comment]
@eivantsov Any progress on this issue?

**Comment by ghost** [comment]
@james10174 worked for me with the latest master. Give ti a shot with a nightly build

**Comment by james10174** [comment]
@eivantsov It works. Good job :)

![image](https://cloud.githubusercontent.com/assets/16562450/15594715/e12efddc-237d-11e6-86d4-c1491ed9d426.png)
