### ISSUE TITLE
Cant connect to che workspace because of CORS policy

### ISSUE THREAD

**Issue by Xachman** [eclipse-che/che#12644]
### Description
I'm getting this error when I connect using localhost.

from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Reproduction Steps
I get the above error when using localhost and no che.env changes with docker.

**OS and version:**    
Manjaro linux 

**Diagnostics:** 
OPTIONS http://172.17.0.1:32803/api/project-importers 403

Access to XMLHttpRequest at 'http://172.17.0.1:32803/api/project-importers' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by skabashnyuk** [comment]
Che version? Does it fresh install or upgrade?

**Comment by skabashnyuk** [comment]
CC @mkuznyetsov

**Comment by Xachman** [comment]
On startup the che version is 6.18.0.  This is a fresh install using docker.

**Comment by mmcparlane** [comment]
I had a similar problem see issue #12350; I haven't had a chance to check it on Kubernetes yet but I will be trying tomorrow.

**Comment by skabashnyuk** [comment]
@Xachman
- is this docker/k8s/openshift?
- Startup parameters?
- Logs from che-master?
- Logs from browser console?
- curl http://host/api/workspace/workspaceid  ?

**Comment by gorshkov-leonid** [comment]
I have the same problem and described it in #12350
