### ISSUE TITLE
Release Che 6.18.1

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#12647]
### Description
Need to release 6.18.1 which should include fixes for:
- https://github.com/eclipse/che/issues/12636
- https://github.com/eclipse/che/issues/12376

Related PRs
- https://github.com/eclipse/che/pull/12640
- https://github.com/eclipse/che/pull/12561

**Comment by ibuziuk** [comment]
@riuvshin will you be able to give a hand with this ?

**Comment by riuvshin** [comment]
done.
