### ISSUE TITLE
docker: 18.06 - eclipse che-server:6.13.0 [site can't be reached]

### ISSUE THREAD

**Issue by svlaskovic** [eclipse-che/che#12656]
Dear Team,

I have used the following tutorial in order to set up an eclipse che on a local docker:https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1
From the logs, everything seems perfectly fine:
.. Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war] has finished in [1,427] ms
2019-02-12 16:00:05,987[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-8080"]
2019-02-12 16:00:06,009[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 19320 ms

kind/**question**

.. NAMESPACE       NAME                                         STATUS
che             che-8689c8f8f5-s4dzj                         Running
docker          compose-7447646cf5-xcpnk                     Running
docker          compose-api-6fbc44c575-hv992                 Running

Slobodankas-MacBook-Air:che svlaskovic$ kubectl get pod --namespace che
NAME                   READY     STATUS    RESTARTS   AGE
che-8689c8f8f5-s4dzj   1/1       Running   0          6m

macOS Mojave: 10.14.3 (18D109)
Docker: per tutorial and in subject
Eclipse CHE: per tutorial and in subject  

open http://che-che.${CHE_DOMAIN}.nip.io
This site can’t be reached che-che.x.x.x.x.nip.io took too long to respond.
Go to http://nip.io/
Search Google for che 111 nip io
ERR_CONNECTION_TIMED_OUT

Thank you,
Slobodanka

**Comment by l0rd** [comment]
@svlaskovic the body of this issue is hard to decipher. Have you been able to connect to http://nip.io?

**Comment by svlaskovic** [comment]
@l0rd 
Hi Mario,

Yes I am able to connect to nip.io

**Comment by l0rd** [comment]
What is the value of variable ${CHE_DOMAIN}?

**Comment by svlaskovic** [comment]
http://che-che.10.111.52.56.nip.io/

Slobodankas-MacBook-Air:helloworld svlaskovic$ kubectl get services --namespace ingress-nginx
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx   LoadBalancer   10.111.52.56   localhost     80:31464/TCP,443:32433/TCP   6h
