### ISSUE TITLE
Workspace failing to start on kubernetes because of security context (Pod security Policy)

### ISSUE THREAD

**Issue by mmeliani** [eclipse-che/che#12661]
### Description
Workspace creation gets stuck because of Pod Security Policy set on the cluster and security context RunAsuser is set by default at 0 and also fsGroup, don't jnow how to change those values, 

so, it is needed to improve kubernetes Infrastucture to make those values configurable and change the pod spec of the workspace 

### Reproduction Steps

**OS and version:**    

**Diagnostics:** 
Error creating: pods "workspacesh358r00mlcb9b50.dockerimage-75d6b95f6-" is forbidden: unable to validate against any pod security policy: [fsGroup: Invalid value: []int64{0}: group 0 must be in the ranges: [{1 65535}] spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden]

**Comment by sleshchenko** [comment]
@mmeliani Are you able to set `CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER` and 
`CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP` which are `0` by default https://github.com/eclipse/che/blob/40131c332e3fbbb3e540fc466d4d15c3b834c28b/deploy/kubernetes/helm/che/templates/configmap.yaml#L57-L58?
Note that `NULL` should be set if you don't want Che Server to set any value.

**Comment by l0rd** [comment]
@sleshchenko @skabashnyuk what do you think about setting "non root" by default? And it would be even better if we could run as arbitrary users (not a user specified UID) as we do on openshift. Do you know if this is possible on kube?

**Comment by sleshchenko** [comment]
@l0rd Need to try. I set root by default some time ago because I faced issues on subpaths of PVC without it (don't remember details). Maybe it is not actual for newer version of Kubernetes(minikube)

**Comment by garagatyi** [comment]
@l0rd to accomplish that we need ensure that each time workspace restarts it gets THE SAME user and/or group ID. Otherwise users will have files permissions issues

**Comment by mmeliani** [comment]
@sleshchenko yeah problem solved thank you,
BR
