### ISSUE TITLE
Deploy single-user Che to Kubernetes on offline machine

### ISSUE THREAD

**Issue by xuchenhao001** [eclipse-che/che#12665]
### Description
I want single-user Che to be deployed on a k8s cluster. (kubeadm bootstraped, have no access to internet) What I can do is just copying all of the docker images to that machine. 

I found there are several steps for single-user che deployment on k8s:
* helm chart install che-server (need access internet to pull image: busybox, eclipse/che-server)
* open browser, create a new workspace and select stack as Go (Default Go Stack with Go 1.10.2, and it seems this step doesn't need to access of internet)
* che-server created a new namespace of k8s, create a new deployment. (need access internet to pull image: eclipse/ubuntu_go)
* bootstrap new workspace. (need access internet and Install packages, Install Golang LS)

So, how can I make all these steps work in a totally offline machine?

### Reproduction Steps
A totally offline k8s cluster (bootstrap with kubeadm)
Install nfs storage class and [label default](https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/) on it
Install [helm charts](https://docs.helm.sh/using_helm/#installing-helm)
Install Ingress with [helm](https://github.com/helm/charts/tree/master/stable/nginx-ingress)
Install eclipse-che with [helm](https://www.eclipse.org/che/docs/che-6/kubernetes-single-user.html):
```
helm upgrade --install che --namespace dev-ops --set cheImage=eclipse/che-server:6.16.0 --set global.ingressDomain=172.18.241.91.nip.io --set cheImagePullPolicy=Never ./
```

**OS and version:**    
Ubuntu 16.04 (have no access to internet)
Kubernetes v1.13.1 (bootstraped with kubeadm, offline, too)

**Diagnostics:**

**Comment by l0rd** [comment]
@xuchenhao001 this looks like a duplicate of #11793

**Comment by xuchenhao001** [comment]
So there is no solution yet?

**Comment by eivantsov** [comment]
@xuchenhao001 you need to go through all 3 deployments for Che to make sure it's Never pull policy, pre pull images and give it a go.

However, I suppose it will fails because init containers have entrypoints that install things - not ideal of course.

**Comment by l0rd** [comment]
> So there is no solution yet?

It means that it's technically possible but we haven't provided any documentation yet. What makes it harder is that, based on the stacks you are using, you may need to setup some extra services to be able to work properly (e.g. a docker registry or a maven repository).
