### ISSUE TITLE
Che with OpenShift oAuth: Not writable dirs with common and per-workspace pvc policies

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12670]
### Description

The error can be reproduced only if when logging in with OpenShift as a user with cluster admin privileges, and common or per-workspace pvc strategy. 

With such configuration a workspace cannot be started because /workspace_logs directory isn't writable, as a result bootstrapper cannot start, and master has no new from it for 5 mins (or whatever timeout is).

### Step to reproduce

1. Deploy Che with openshift oauth on and common or per-workspace pvc strategy
2. Create and start a workspace.

Bootstrapping never starts, although bootstrapper binary url is in tmp. However, /workspace_logs is not writable which I think is what causes the issue.

**Comment by dmytro-ndp** [comment]
Please, make sure that solution will work for Codeready Workspaces 1.x as well.

**Comment by eivantsov** [comment]
Fixed by https://github.com/eclipse/che/pull/12892
