### ISSUE TITLE
Legacy environment variables cleanup

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12679]
### Description

We have quite a lot of environment variable providers that was used in Che6 workspaces that making Che7 plugin configuration complex.
For example, it's very hard to override JAVA_OPTS or MAVEN_OPTS today.
I think we should remove these providers providers

- JavaOptsEnvVariableProvider
- MavenOptsEnvVariableProvider
- WorkspaceAgentCorsAllowCredentialsEnvVarProvider
- WorkspaceAgentCorsAllowedOriginsEnvVarProvider
- WorkspaceAgentCorsEnabledEnvVarProvider
- AgentAuthEnableEnvVarProvider
- WorkspaceAgentJavaOptsEnvVariableProvider

**Comment by svor** [comment]
Since jdt.ls should be run as a sidecar in Che 7, it would be useful to override JAVA_OPTS. 
Also it may help to solve the problem: https://github.com/eclipse/che/issues/12708

**Comment by skabashnyuk** [comment]
@slemeur @l0rd  are you sure we need this for GA? It will introduce some incompatibility with Che6 workspaces.

**Comment by l0rd** [comment]
@skabashnyuk I am not sure I understand your comment. With Che 7 we are going to break compatibility with Che 6 workspaces. I assumed that it was clear but it looks like it isn't?

**Comment by skabashnyuk** [comment]
When we decided to remove this classes
```
JavaOptsEnvVariableProvider
MavenOptsEnvVariableProvider
WorkspaceAgentCorsAllowCredentialsEnvVarProvider
WorkspaceAgentCorsAllowedOriginsEnvVarProvider
WorkspaceAgentCorsEnabledEnvVarProvider
AgentAuthEnableEnvVarProvider
WorkspaceAgentJavaOptsEnvVariableProvider
```
Che 6 workspaces a likely will not work. So my question is this should happen before or after GA

**Comment by l0rd** [comment]
I think we can do that as soon as we have removed all Che 6 stacks.

**Comment by ibuziuk** [comment]
@skabashnyuk looks like I'm facing this problem with `spring-rest-guide` devfile https://github.com/ibuziuk/my-che-devfiles/tree/master/spring-rest-guide#not-possible-to-override-java_opts-or-maven_opts-in-the-devfile Any ideas if it is possible to override the MAVEN_OPTS somehow?

**Comment by metlos** [comment]
There is a draft impl provided by @skabashnyuk: https://github.com/eclipse/che/pull/13612

**Comment by metlos** [comment]
#13612 is ready for review
