### ISSUE TITLE
Error response from docker API, status: 400, message: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by djpbessems** [eclipse-che/che#12678]
### Description
Receiving the following error:  
`Error response from docker API, status: 400, message: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`  
when running che-server with the following command on Docker for Windows (Enterprise Edition) on Windows Server 2019 (ltsc) using Linux Containers for Windows (LCOW):  
`docker run -d -p 8084:8084 --name che -e CHE_PORT=8084 -e CHE_HOST=subdomain.example.org -e DOCKER_HOST=tcp://192.168.1.10:2375 -v C:/path/to/che/conf:/data eclipse/che-server:6.18.1`

Whenever Che-server is trying to interact with the provided Dockerhost it receives the same error. I'm a bit confused where the client-binary is located, because when I enter an interactive shell in the container (`docker exec -it che sh`) I can only find /usr/bin/docker, which is only version 1.6.0:
```
$docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
FATA[0000] Error response from daemon: client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

For reference, the version of docker that I'm running:
```
docker version
Client:
 Version:           master-dockerproject-2018-11-29
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        504cecf2
 Built:             Thu Nov 29 23:50:48 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          master-dockerproject-2018-11-29
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.11.2
  Git commit:       baab736
  Built:            Thu Nov 29 23:59:33 2018
  OS/Arch:          windows/amd64
  Experimental:     true
```

### Reproduction Steps
See above

**OS and version:**    
See above

**Diagnostics:** 
See above

**Comment by l0rd** [comment]
Hi @djpbessems, we are about to deprecate the support of Docker as a deployment platform for Che. Is it an option for you to try Che on Kubernetes? You can do it easily install kubernetes locally using tools like minikube and minishift.

@skabashnyuk do you think that simply upgrading the docker version in che server image would work here?

**Comment by skabashnyuk** [comment]
>@skabashnyuk do you think that simply upgrading the docker version in che server image would work here? 
The simplest thing would use latest Docer CE for Windows with enabling Kubernetes infrastructure.

**Comment by djpbessems** [comment]
@l0rd I'm afraid I have no experience with kubernetes just yet; I should perhaps look into setting it up on my homelab (I've held off installing it because it felt like overkill for just one node).

I ran `apk add docker` in the container which did update docker to api-version 1.39; but the webinterface does not seem to pick up the upgrade. Is `docker-client-6.18.1.jar` the actual binary that is used and should I try replacing/upgrading that (http://central.maven.org/maven2/org/eclipse/che/infrastructure/docker/docker-client/6.18.2/docker-client-6.18.2.jar)?

**Comment by l0rd** [comment]
@djpbessems as @skabashnyuk suggested you can enable kubernetes if you are using Docker for Desktop (c.f. [our blog post](https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1) out it). The other option I was mentioning [minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/) that is a lightweight VM as Docker for Desktop.

**Comment by djpbessems** [comment]
Yeah, I was already reading into minikube; hopefully it can be made to work with Docker for Windows EE.

I guess regardless this issue can be closed (unless you want to use it to add depecration warnings to the documentation)?
