### ISSUE TITLE
Support workspace creating from repository if it contains `.devfile.yaml`/`devfile.yaml` file

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12675]
### Description
Now, Factory API supports only repositories with Devfile if file name is `.devfile`
https://github.com/eclipse/che/blob/7a9feef2b553fd20ffc85f2a53b8f38b2e75847f/plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GithubURLParser.java#L93
 But many editors do not enable YAML syntax highlighting if file name does not have format specified.
I think it is better to add support workspace creating from repository if it contains `.devfile.yaml` file.
<details>
<summary>See how it affects displaying by Github</summary>
Without format specified:

![screenshot_20190215_163708](https://user-images.githubusercontent.com/5887312/52863280-1d415680-3140-11e9-8d07-cdf7d95a7e87.png)

With format specified:

![screenshot_20190215_163725](https://user-images.githubusercontent.com/5887312/52863298-2b8f7280-3140-11e9-8ecd-78c9fc5811df.png)

</details>

<details>
<summary>See how it affects displaying by Atom editor</summary>

Without format specified:

![screenshot_20190215_164032](https://user-images.githubusercontent.com/5887312/52863413-77421c00-3140-11e9-9602-53859d0f5839.png)

With format specified:

![screenshot_20190215_164042](https://user-images.githubusercontent.com/5887312/52863418-7b6e3980-3140-11e9-9d2a-7731f0671b55.png)

</details>

Actually, a user may want not to hide Devfile file from file managers, and it would be good to give a user choice and name Devfile as he wants - with dot or without at the begigging of name.

**Comment by sleshchenko** [comment]
@l0rd @skabashnyuk WDYT?

**Comment by garagatyi** [comment]
:+1: YAML indentation can also be validated to avoid some basic mistakes

**Comment by l0rd** [comment]
@sleshchenko I amo :+1: for your proposal. But honestly the biggest issue for me is that no error is shown if a file `.devfile` is not found. At this stage it's ok to support only `.devfile` but if there is no such file is found (because the user has named it `devfile.yaml` for instance) an error should be shown: 

`No valid devfile hasn't been found in the github repository. There is no <URL>/.devfile`.

**Comment by mshaposhnik** [comment]
@lord That is because we still support this kind of factories which pointing to any GH repo, even without .devfile/factory.json/e.t.c.  In this case project will be cloned, and defaut plugins applied to the WS conf.

**Comment by l0rd** [comment]
Thank you for your explanation @mshaposhnik but I don't think we should support that. It's really misleading.

**Comment by mshaposhnik** [comment]
No problem, if it's will be approved by @slemeur

**Comment by slemeur** [comment]
I'm -1 to remove that.

In fact, that allows to import a project in Che with just a URL even if there is no devfile and factory. 

That allows flow like:
```{host}/f?{my_repo}```

We can't expect that the devfile will be define before the project gets imported in Che. 

It should be easy / simple to import in Che and requires the minimum of pre-requisities. Once the developer is in Che, we make the configuration of the workspace easy and allow the developer to version that with a devfile.

Also, Che should be able to analyze the project, detect the technologies used and propose to the user a workspace that fits with his needs.

**Comment by sleshchenko** [comment]
Is not actual after merge of https://github.com/eclipse/che/pull/12965
