### ISSUE TITLE
Make it possible for ApiInfoService to get project version from property

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12686]
### Description

Currently ApiInfoService gets Implementation-Version from a manifest file. When building a custom Che assembly with its own version there's no clean way to override upstream version that is displayed in Dashboard footer other than repackage war and api-core jar.

It would be nice to be able to override it in a more easy way, say, property or env.

**Comment by mshaposhnik** [comment]
Is ok for you it will be read from  war-file manifest instead of jar ?

**Comment by eivantsov** [comment]
That will make repackaging 1 level simpler :)

**Comment by nickboldt** [comment]
This request is motivated but the same concerns as reported in https://github.com/eclipse/che/issues/12664 and https://issues.jboss.org/browse/CRW-136

**Comment by mshaposhnik** [comment]
Merged, now version is read from war-s manifest, so you can set any during the packaging.
