### ISSUE TITLE
Does single user eclipse/che version on top of Windows Docker desktop exist ?

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#12685]
### Reproduction Steps

Attempt to run single-user eclipse/che on top of Docker desk top produces:
**OS and version:**    
Windows 10 fall release enterprise

Windows docker desktop , i.e. includes Hyper-v support and DockerNAT switch.

Docker Desktop configuration:
shared drivers: C;
DNS server: 8.8.8.8
proxies: none
enable kubernetes: false

CPUs: 2
memory:5120MG
Windows Defender and McAfee firewalls
**Diagnostics:** 
INFO: Welcome to Eclipse Che!
INFO:
INFO: You are missing a mandatory parameter:
INFO:    1. Mount 'docker.sock' for accessing Docker with unix sockets.
INFO:    2. Or, set DOCKER_HOST to Docker's location (unix or tcp).
INFO:
INFO: Mount Syntax:
INFO:    Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...
INFO:
INFO: DOCKER_HOST Syntax:
INFO:    Start with 'docker run -it --rm -e DOCKER_HOST=<daemon-location> ...'
INFO:
INFO: Possible root causes:
INFO:    1. Your admin has not granted permissions to /var/run/docker.sock.
INFO:    2. You passed '--user uid:gid' with bad values.
INFO:    3. Your firewall is blocking TCP ports for accessing Docker daemon. 

internal virtual switch: subnet address: 10.075.0

Inded, Docker desktop for Windows doesn't create docker.sock file because, according documentation it uses npipes instead of unix sockets.
DockerNAR switch eliminates need of Internal/External switch because provides DHCP function. this is default internal switch.
When Kubernetes is enabled in Docker desktop configuration it makes Kubernetes the orchestration engine.

**Comment by eivantsov** [comment]
@PavelSosin we'll be discontinuing Docker support after Che 7 release which is soon to happen.

I recommend looking at running Che on K8S/OpenShift.
