### ISSUE TITLE
Unable to start workspace with ' Theia IDE on docker' stack

### ISSUE THREAD

**Issue by sallyanna000** [eclipse-che/che#12684]
### Description
Hello:
While creating a workspace, I choose the 'Theia IDE on docker' stack, but when I start the workspace, I always get the Error: **Failed to run the workspace: "Workspace is going to be STOPPED. Reason: Container of machine 'machine-exec' unexpectedly stopped. Please, check that container is designed to run in non-interactive terminal."** Why? How can I solve this? 

Thanks.

che version: 6.17.1    
OS version: CentOS Linux release 7.5.1804 (Core)

![image](https://user-images.githubusercontent.com/13101902/52942822-b8d40080-33a6-11e9-8f15-f83fd826678d.png)

![image](https://user-images.githubusercontent.com/13101902/52942896-e1f49100-33a6-11e9-8c17-4e31fdcda707.png)

**Comment by sunix** [comment]
@AndrienkoAleksandr is the theia-ide stack for Docker a stack that we should maintain ? should we remove it ? of fix this problem ?

**Comment by AndrienkoAleksandr** [comment]
@sallyanna000 Hello. I see you use docker. Terminal for che 7 on the docker works only with docker.sock volume: https://github.com/eclipse/che-machine-exec#user-content-how-to-use-machine-exec-image-with-eclipse-che-workspace-on-the-docker-infrastructure.

**Comment by geiseri** [comment]
I also have this same problem even after setting the `CHE_WORKSPACE_VOLUME` value in my `che.env`.  Has anyone else seen this work?

**Comment by AndrienkoAleksandr** [comment]
@geiseri So Did you uncomment this property? And restart CHE?

**Comment by geiseri** [comment]
Yes, well I added the `CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock;` line in my `che.env` that is stored in my `/data` volume.  But then I stopped and started the che docker again.  I did check `docker inspect che-8081` (my che instance) and I didn't see it in the environment.  Could it be getting clobbered somewhere?

**Comment by AndrienkoAleksandr** [comment]
I will take a look with latest CHE version.

**Comment by AndrienkoAleksandr** [comment]
Sorry for big delay. It's really doesn't work, because seems property CHE_WORKSPACE_VOLUME was removed from Eclipse CHE.
