### ISSUE TITLE
Add traces/metrics relate to pulling images

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12698]
### Description
We would like to observe how images pulling are happening. If possible we should distinct cached and non-cached scenario.

Related issue https://github.com/openshiftio/openshift.io/issues/4730

**Comment by garagatyi** [comment]
I was playing with it, see https://github.com/eclipse/che/pull/12655/files#diff-5cac1af7ada92b7a5309db88b7f49d81R668

**Comment by garagatyi** [comment]
@skabashnyuk can you elaborate why you closed this issue?
