### ISSUE TITLE
Propagate traces as Prometheus metrics

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12697]
### Description
We want to be able to consume traces as Prometheus metrics. Instead of doubling code we can just reuse https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-micrometer to export existed traces as metrics 
CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19017

**Comment by metlos** [comment]
This might be more useful than the project mentioned in the issue description: https://github.com/opentracing-contrib/java-metrics
