### ISSUE TITLE
Add traces/metrics relate to routes

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12699]
### Description
We would like to observe how routes creation is happening. 
Related issue https://github.com/openshiftio/openshift.io/issues/4730

**Comment by garagatyi** [comment]
Can you clarify what do you mean by metrics for routes? 
BTW we already have traces for routes creation here https://github.com/eclipse/che/blob/master/infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntime.java#L176
Did you mean traces for routes availability?

**Comment by sleshchenko** [comment]
@garagatyi Do you happen to know how routes availability can be checked? I mean maybe status is not set for an unavailable route?

**Comment by skabashnyuk** [comment]
I need some time to clarify this task. Basically, I want to see some routes related metric that will mean something for the user. Not only API call. May be we need something that will ensure that route really created.

**Comment by garagatyi** [comment]
@sleshchenko we could add traces programatically when we ping servers. We could also try to use https://docs.openshift.com/container-platform/3.5/rest_api/openshift_v1.html#list-or-watch-objects-of-kind-route, but I'm not sure it shows flaky routes

**Comment by fche** [comment]
@skabashnyuk It sounds a little like what you need is some metric from the openshift infrastructure, in the form of latencies for a complete operation (route CRD creation through to actual operation).

**Comment by skabashnyuk** [comment]
closing in prefer of https://github.com/eclipse/che/issues/12740
