### ISSUE TITLE
JDT.LS process is killed in sidecar container

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#12708]
### Description
 
JDT.LS is running in remote CHE plugin and provided by vscode-java extension.
Memory limit was set in workspace configuration in `attributes` block:
`"sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "4000M"`

After some time, about 2 minutes, the process of jdt.ls is killed in sidecar container automatically. 

### Reproduction Steps

1. Create a workspace which based on Che 7 stack
2. Add into ws configuration [`meta.yaml`](https://raw.githubusercontent.com/eclipse/che-plugin-registry/5db78497ca335c4b2a6eb3f8e3caf2eced31dc86/plugins/org.eclipse.che.vscode-redhat.java/0.38.0/meta.yaml) which describes java remote plugin
3. Add memory limit into `attributes` to make it possible to run jdt.ls `"sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "4000M"`

My workspace configuration:
```json
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "ws/dev": {
          "attributes": {
            "memoryLimitBytes": "536870912"
          },
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {}
        }
      },
      "recipe": {
        "type": "kubernetes",
        "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: 'eclipse/che-dev:nightly'\n     name: dev\n     resources:\n      limits:\n       memory: 512Mi\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [],
  "name": "wksp-us1i",
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "4000M",
    "plugins": "che-machine-exec-plugin:0.0.1, https://raw.githubusercontent.com/eclipse/che-plugin-registry/java/plugins/org.eclipse.che.vscode-redhat.java:0.38.0"
  },
  "commands": [],
  "links": []
}
```

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
@garagatyi do we have an ability to specify  ```JAVA_OPTS``` for Jdt.ls sidecar defined as VS Code extension https://github.com/eclipse/che-plugin-registry/blob/master/plugins/org.eclipse.che.vscode-redhat.java/0.38.0/meta.yaml ?`

**Comment by garagatyi** [comment]
No, we don't such a functionality ATM

**Comment by garagatyi** [comment]
@skabashnyuk maybe we need to ensure that it contains everything needed to respect container RAM limits? It might not respect it and use host settings instead.

@svor Which project JDT.LS is running against in your case?

**Comment by skabashnyuk** [comment]
>@skabashnyuk maybe we need to ensure that it contains everything needed to respect container RAM limits? It might not respect it and use host settings instead.

How do you see that?

**Comment by skabashnyuk** [comment]
CC @l0rd @sleshchenko. I think we might need to extend meta.yaml format in the case of VS Code extension. Extension developer should be able to specify JAVA_OPTS what he want's or maybe another variable by his decision.

**Comment by garagatyi** [comment]
@skabashnyuk It was just a suggestion

**Comment by l0rd** [comment]
The more we the more it look like meta.yaml and che-plugin.yaml should be merged (i.e. no need for che-plugin.yaml anymore).

Anyway for this particular problem I was wondering if we can already set `JAVA_OPTS` (or any env variable) for a VS Code plugin running at devfile/workspaceconfig level?

**Comment by skabashnyuk** [comment]
We are setting JAVA_OPTS with JavaOptsEnvVariableProvider to every single container. All with the same value. I think this is error-prone. I would say we should remove it.https://github.com/eclipse/che/issues/12679

**Comment by svor** [comment]
This problem wasn't related to `JAVA_OPTS`. The problem was that the sidecar image used [BusyBox ps command](https://busybox.net/downloads/BusyBox.html#ps) and it isn't full (at least it doesn't support `-p` parameter). I've fixed it by installing `procps` into the image https://github.com/eclipse/che-theia/pull/83.
