### ISSUE TITLE
No Projects in Workspace

### ISSUE THREAD

**Issue by gpike** [eclipse-che/che#12701]
### Description
I've tried bring Che up in Docker on 3 different machines without luck. I can bring the container up and create a new workspace, with or without projects. When opening the workspace there are no projects and create or import brings up a dialog with no options.

### Reproduction Steps
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v ~/Documents/che:/data eclipse/che start

Create workspace, add project

Open workspace, no projects in explorer just options to Create or import.

The Create and Import Dialogs have no content in the left options area, you can edit the other fields but the buttons never become active.

**OS and version:**    
Mac with Docker 2.0.2.1

**Diagnostics:**

**Comment by qurben** [comment]
I had the same problem, a workaround that worked for me is to access Che by going to the local ip of the che host. This ip is printed when che is started for the first time (with) an empty data folder.

```
INFO: (che init):   CHE_HOST=10.0.xx.xx
```

This info is also in `<data>/instance/config/che/che.env`

**Comment by eivantsov** [comment]
@gpike you need to inspect exceptions in browser dev console. I bet there are failed requests there.

**Comment by Patricol** [comment]
I've had the same issue, combined with an immediate error upon trying to import, since 6.16.0.

The error is also present with every version between 6.16.0 and 6.17.1 (inclusive) as well as 6.19.0. (I didn't test 6.18.x or the 7.x beta.)

Switching to using an explicit IP instead of localhost fixes the issue, but I imagine it should still qualify as a bug.

Whatever causes it seems to have been introduced between 6.15.0 and 6.16.0.

**Comment by Patricol** [comment]
To clarify, the issue is something within che; not a user configuration issue.

I tested two completely fresh setups of 6.15.0 and 6.16.0 on the same machine; 6.15.0 works, 6.16.0 etc. doesn't.

**Comment by wgbeckmann** [comment]
Yes, I'm havin the same issue.
I wantet to upgrade from 6.7.0 to 6.19.0 with the issue descriped above.
So I recoverd to 6.7.0 startet to upgrade from Version to Version. On the step 6.15.0 to 6.16.0 the issue come back. So I stuck at 6.15.

We have a lot of Projects in Eclipse Che and are porting new Projects. But I need a hint for upgrading Eclipse Che!

**Comment by wgbeckmann** [comment]
qurben gave me the right direction:

You have to change the CHE_HOST setting in the che.env file.
In my case in the enf-file it was an IP but I started che always with the Server-Name.
After fixing that issue I was able to update to 6.15.0 and at least to 6.19.0
