### ISSUE TITLE
Can't mount PV on Che7 / multi-node k8s.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12703]
### Description

The detail of this issue is under inspection. I'll append detailed information later.

In case following, it looks deployed pods can't share PV.

* Using per-workspace PVC strategy
* Multi-node k8s cluster
* Pods (like `jwt-proxy` and `editor`) are deployed to another nodes.
* (may some additional condition...)

### Reproduction Steps

Create Che7 workspace and start on multi-host K8s cluster.

**OS and version:**    

* Kubernetes 1.12.4 (AKS)
* Che 6.18.0-SNAPSHOT

**Diagnostics:**

**Comment by garagatyi** [comment]
@monaka JWT proxy pod should not request mounting a PV. That's why it should be OK to have it on another k8s node. 
Can you elaborate on what is the issue you face?

**Comment by monaka** [comment]
I'm now inspecting this issue. I've not seen the root cause yet.
But generally, I guess it may be required to set `podAffinity` to run pods in the same node.
An example case, the environment is under per-workspace strategy and PV is an emulated hard drive (like AzureDisk).

**Comment by monaka** [comment]
I can't reproduce this issue now. So I close this.
