### ISSUE TITLE
Image In Self-Signed Cert Section, Shows Green 'Secure' Message - can this be right?

### ISSUE THREAD

**Issue by medined** [eclipse-che/che#12702]
### Description
When I followed the steps at https://www.eclipse.org/che/docs/che-6/openshift-config.html#https-mode---self-signed-certs, browser shows 'Insecure' instead of 'Secure'. Since I have not imported any certificates to my browser at this point in the process, how could the 'che-eclise-che' URL be secure?

### Reproduction Steps

The process that I followed is described at https://gist.github.com/medined/d6157da9266e7374d7ae8abd3dfddebf. The problem arises at the "Click on the 'Not Secure' message in your browser." step.

**Comment by sleshchenko** [comment]
cc @eivantsov

**Comment by eivantsov** [comment]
@medined can you check for which DNS has been the cert generated? I think you have hit https://github.com/openshift/origin/issues/20716

So, you have created a secret with cert body, this secret was consumed by Che master and propagated to a workspace, but it's generated for a different DNS.

What you can try is to curl Che TLS route using this cert and see how curl reacts.

Btw, you do not need to rebuild a stack image as the cert will be there automatically.
