### ISSUE TITLE
Preflight check not checking properly RAM size

### ISSUE THREAD

**Issue by benjnr** [eclipse-che/che#12715]
### Description

Preflight fails on 1.0 to 1.49 TiB (company) machine when starting Docker Multiuser version with che 6
(same docker command as in docs)

### Reproduction Steps

**OS and version:** 

RHEL7
Che v6

**Diagnostics:** 

I'm guessing it is coming from [this start script](
https://github.com/eclipse/che/blob/master/dockerfiles/base/scripts/base/commands/cmd_start.sh)

Preflight checks doesn't check if RAM is in TiB or GiB 
Thus when checking RAM on 1.0 to 1.5 TiB machine, it fails the preflight check on Memory available

on my machine : 

```sh
[user@host ~]$ docker info | grep "Total Memory:"
Total Memory: 1.476 TiB
[user@host ~]$ HOST_RAM=$(docker info | grep "Total Memory:")
[user@host ~]$ HOST_RAM=$(echo ${HOST_RAM#*:} | xargs)
[user@host ~]$ HOST_RAM=${HOST_RAM% *}
[user@host ~]$ echo $HOST_RAM
1.476
```

**Comment by bamj** [comment]
No option on pure docker in che 7.x, closing this issue
