### ISSUE TITLE
User defined Che launch commands should be exported in a launch.json file

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12711]
### Description

Currently, when a user defines a debug command (in a `devfile` or from the Che dashboard), he won't be able to run it from Theia Debug menu.

Solving this issue requires to solve #12710 first.

**Comment by vparfonov** [comment]
Look like for implement this task we need to change commands description in Eclipse Che API. It because in Che we just have command line but in Theia (VS Code) command launch procedure depends on Extension logic.

**Comment by l0rd** [comment]
> Look like for implement this task we need to change commands description in Eclipse Che API. It because in Che we just have command line but in Theia (VS Code) command launch procedure depends on Extension logic.

@vparfonov breaking the API for Che 7 is not a problem but we need to document the change and communicate it in che-dev. You don't provide much information about the solution ("we need to change commands description") but it's important to decouple the solution from Theia: I mean Theia is one editor, Che may have other editors. Che command abstraction should work with any editors.
