### ISSUE TITLE
User defined Che tasks commands should be exported in a tasks.json file

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12712]
### Description

Currently, when a user defines a command (in a `devfile` or from the Che dashboard), he won't be able to view/edit it from the `tasks.json` where `Theia` custom tasks should be defined.

**Comment by vparfonov** [comment]
@l0rd @slemeur 
We can provide this as basic function in Theia upstream. It will look like in VS Code https://code.visualstudio.com/docs/editor/tasks.
Che Commands from WS config are 'detected task' for Theia API, after user edit command we will store it in tasks.json. Stored command will have high priority. 
Is it ok for you?

**Comment by sunix** [comment]
problem is that if user edits the tasks.json. He would share the config through the factory or ws config but won't get the changes done in tasks.json. So what is the benefit ?

I can see 2 options:

- what about having a UI to edit che commands ?
- have a synchronization mechanism between che commands and tasks.json.

**Comment by l0rd** [comment]
@vparfonov yes that makes sense thanks

@sunix this issue is task n.3 of epic #12709 and syncro is part of task n.5

**Comment by RomanNikitenko** [comment]
As it was [suggested](https://github.com/eclipse/che/issues/12712#issuecomment-467394504) within this issue I added ability to configure Task from UI:
- 'Configure task' action was provided for each item of 'Run Task' menu
- 'Configure Tasks' menu action was added

'Configure Tasks' menu displays only detected tasks.
'Run Task' menu displays both: configured and filtered detected tasks. Detected tasks are filtered by label: for example, when we have configured and detected tasks with the same label - only configured task is displayed.
Both menus allow to copy task configuration to tasks.json file and provide ability to edit this one. 

So, Che Commands from WS config are 'detected task' for Theia API and are displayed as items of  'Configure Tasks' and 'Run Task' menus. Task configuration is copied to tasks.json and available for editing by clicking on appropriate item. After that che command is displayed as 'configured' in 'Run Task' menu and  has high priority at running. At the same time task configuration from WS config is still available from 'Configure Tasks' menu.
I would like to discuss  - do we need to copy all Che Commands from WS config to tasks.json file without user interaction?

**Comment by vparfonov** [comment]
I vision is no reason copy all commands during start WS.

**Comment by slemeur** [comment]
@RomanNikitenko : Can you attach a recording?

**Comment by RomanNikitenko** [comment]
@slemeur 
You can see the basic functionality [here](https://youtu.be/FKkSnWJy2ac) and some improvements for UI [here](https://youtu.be/Hhlls33wqmQ)

**Comment by slemeur** [comment]
@RomanNikitenko : I feel it quite confusing. I don't think a user will understand where the tasks are coming from.

From the video few feedbacks, as a user:
- "provided vs configured" is not understandable - I would not know what is the differences. All tasks are provided and configured in fact. 
- "Configure Tasks" in the command palette is then just filtering the "provided tasks", while in fact, as a user I would like to be able to configure all the tasks.
- It's very disturbing to see in the list of available tasks that there are 5 tasks, but then when you open the file "tasks.json" there are only 1 tasks defined there.

I think we should have a way to display **all** the tasks and commands. What about a dedicated view where we aggregate all of them? Similar to how preferences are handled?

**Comment by RomanNikitenko** [comment]
@slemeur thank you for your feedback!
I would like to make some comments about that:

> "provided vs configured" is not understandable - I would not know what is the differences. All tasks are provided and configured in fact.

OK, I see, but this is default behavior for VS Code https://code.visualstudio.com/docs/editor/tasks

> "Configure Tasks" in the command palette is then just filtering the "provided tasks", while in fact, as a user I would like to be able to configure all the tasks.

User **has** ability to configure all the tasks - 'Run Task' menu displays both: configured and detected tasks. 'Configure Tasks' menu displays only detected tasks(configured tasks are already placed in the tasks.json file and available for editing).

> It's very disturbing to see in the list of available tasks that there are 5 tasks, but then when you open the file "tasks.json" there are only 1 tasks defined there.

From other side you have ability to run any task and only overridden tasks are displayed in the tasks.json file. 
I think it is not consistent if we display all detected Che tasks in tasks.json file, but do not display another tasks, so we should display all detected tasks in tasks.json file, right?
For example, at the moment when I work with theia I have:
![configure](https://user-images.githubusercontent.com/5676062/55707180-a90e8b00-59eb-11e9-9a38-98413d3b26e1.gif)

Do we really need to display all detected tasks in tasks.json file? 

So, I guess we can not change default behavior of Theia and need some custom view for our goals. 
Anyway I believe we can provide the best solution for user when we have a few points of view and productive discussion, so thank you very much, Stevan!

**Comment by l0rd** [comment]
I suggest to discuss that tomorrow in Cherkasy during our meeting about Che commands. We will then report the outcome of the discussion here.

**Comment by sunix** [comment]
I think we should not compare to VSCode behaviour because it is another use case: these tasks are coming by default with plugins as I understood.
Our Che commands cannot be considered as commands by default to be configured ... but as Che user tasks. It is consistent that we see all the Che commands in tasks.json and not having to do any additional action.

We should see che commands as
- a way to persist tasks.json in the wsconfig (and maybe in the futur devfile)
- the ability to run the task on remote containers

But definitely not default commands you can customize.
My 2 cents...

**Comment by sunix** [comment]
@RomanNikitenko i tried to run a che task i have modified (configured ...), but changes are not applied ... is it expected ?

**Comment by RomanNikitenko** [comment]
@sunix We have regression after merge https://github.com/theia-ide/theia/pull/4847

**Comment by slemeur** [comment]
@RomanNikitenko + @vparfonov : Where are you tracking the bug and getting the fix? This is quite critical

**Comment by RomanNikitenko** [comment]
https://github.com/eclipse/che-theia/issues/184
https://github.com/theia-ide/theia/issues/4928
