### ISSUE TITLE
Develop discovery mechanism for launching remote plugins

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#12721]
### Description

As a developer of a remote plugin I would test it in my workspace which have dedicated containers for launching the remote plugin and for Theia.

To launch remote plugin (aka endpoint) I have to:
- have cloned and built `theia-endpoint-runtime` Theia extension
- open terminal for launching remote plugin
- go to `theia/che/che-theia/dockerfiles/theia-endpoint-runtime` directory
- set `THEIA_PLUGINS` and `THEIA_PLUGIN_ENDPOINT_PORT` environment variables
- launch `plugin-remote.js` with `node`

To launch Theia i have to
- have cloned and built Theia
- open terminal for launching Theia
- go to `theia/examples/assembly` directory
- get generated URI for the remote plugin from the workspace runtime
- set `THEIA_PLUGIN_REMOTE_ENDPOINT_.....` environment variable and specify ID of the endpoint and plugin URI
- run Theia

It's very inconvenient to do all of this by hands.
I would prefer to have a mechanism for running that by a command.

**Comment by vitaliy-guliy** [comment]
Sample plugin simplifies launching and developing of remote plugins https://github.com/eclipse/che-theia/issues/96

**Comment by garagatyi** [comment]
Seems relevant https://github.com/eclipse/che/issues/12395#issuecomment-470591054

**Comment by vitaliy-guliy** [comment]
It's not actual anymore.
