### ISSUE TITLE
Do not allow to save environment with containers that are not defined in recipe

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#12726]
### Description
Che single user allows to save environment with tooling containers - that exist in runtime, but are not defined in recipe. That should not be possible.

### Reproduction Steps
1. Create and run Che 7 workspace.
2. Go to Workspace Details -> Variables Tab and try to add the variable with name "Test" and "test" value
3. Go to Config Tab and see that environment now contains machines "ws/theia-ide", "che-jwtproxy", "ws/che-machine-exec", "ws/dev".
4. Click "Save" button.

**Expected behavior:** Error occurs, that workspace environment contains containers that are not defined in recipe.
**Actual behavior:** Workspace is successfully updated.

**Notes:** Multi-user works fine.
The bug on dashboard is fixed by this PR https://github.com/eclipse/che/pull/12725

**Comment by garagatyi** [comment]
@skabashnyuk FYI
