### ISSUE TITLE
Implement first E2E suite for Che 7

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#12727]
Outcome of this issue should be basic e2e test suite. The scenario for the tests could be gathered from https://hackmd.io/s/BkVyU6crN and comments in epic issue.

For the first implementation I think it should be enough to:
* Create Che 7 based workspace using dashboard
* The workspace should have some project in it (preferably java based)
* Open that workspace, check basic JDT.LS features.
* Stop workspace (again using dahsboard)
* Delete that workspace

Once this is implemented, we can look for best ways how to extend this scenario.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/12848
