### ISSUE TITLE
Sharing from the IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12722]
### Description
With Che 7, it should be possible to share the workspace directly from the IDE.
As an MVP, we could do the following:
- Add an menu entry item "Share"
- Clicking on this menu item will just redirect the user to the dashboard > workspace details > share page.

**Comment by akurinnoy** [comment]
@slemeur `Che` in single-user mode doesn't have Workspace Share page at all. Will it work for you if a user will be redirected to the Overview page, where it's possible to export a workspace configuration file?

Also, workspace's share pages on `che.openshift.io` and `codenvy.io` differs from each other.

<details>

<summary>Screenshots</summary>

*che.openshift.io*
![share - che openshift io](https://user-images.githubusercontent.com/16220722/55787509-1b03d480-5abf-11e9-826e-01506d68ef56.png)

*codenvy.io*
![share - codenvy io](https://user-images.githubusercontent.com/16220722/55787527-26570000-5abf-11e9-9620-28a4760d92b9.png)

*minikube single-user*
![share - single user](https://user-images.githubusercontent.com/16220722/55787568-3a9afd00-5abf-11e9-8e39-ee62eec800a7.png)

</details>

**Comment by slemeur** [comment]
The idea was to create the factory. Could we redirect to the factory creation page? (with current workspace selected)

**Comment by akurinnoy** [comment]
We can redirect to the factory creation page, but we can not select there anything (a tab (workspace, git, config, template) or a specific workspace).

**Comment by akurinnoy** [comment]
@slemeur hello, have a look at the comment above, please

**Comment by slemeur** [comment]
Let's start by redirecting to the "Share" page on the dashboard.

In the following iteration, could we have a popup in the IDE allowing the user to create the factory directly from there?

**Comment by akurinnoy** [comment]
@slemeur I'm not sure about popup, but we could provide kind of command for that. 

Shouldn't I worry about single-user mode (where no Share page)?

**Comment by slemeur** [comment]
If single-user mode, just point to the overview page.
