### ISSUE TITLE
Configure CI for new E2E test suite

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#12729]
Configure CI (jenkins job) (at least nightly builds) for test suite created as part of https://github.com/eclipse/che/issues/12727

I would prefer if the configuration of the job would be kept as a source (for example jenkins DSL/pipeline) together with the actual sourcecode.

**Comment by l0rd** [comment]
Related to #13229

**Comment by l0rd** [comment]
Duplicate of https://github.com/eclipse/che/issues/13229
