### ISSUE TITLE
[Traces] Machine create/start trace has to be more detailed

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12739]
### Description

It would be nice to see details such.
- waitRunningAsync method. The time when we waiting for a running pod
- bootstrap. Installers startup.
- checkServers - server response time.

**Comment by garagatyi** [comment]
Installers are not part of Che 7. We might consider not spending time on them.

**Comment by ibuziuk** [comment]
@amisevsk should we close this issue + downstream one? AFAIK no further work is planned
