### ISSUE TITLE
Inform users about what devifle was used to create a workspace with the factory

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12741]
### Description

Since we may support different devfile names like: .devfile , devfile, Devfile, devfile.yaml, and because if devfile does not exist in the repository we may use default one it would be nice to inform users about what devfile we used to create a workspace.

Maybe somethign like ```Loading workspace from .devfile``` on this page.
![12 28 58](https://user-images.githubusercontent.com/1614429/53236689-917a7d80-369d-11e9-9baf-69c4976c39f7.png)

Implementation can be separated into two phases.
- Put information about used devfile in workspaceConfig attributes.
- Display information in some places on UI.

**Comment by skabashnyuk** [comment]
CC @l0rd @slemeur

**Comment by l0rd** [comment]
What is most important is the case when no devfile is found in the repository. We should inform the user about it and that a generic development stack will be used.

**Comment by mshaposhnik** [comment]
Implemented as additional loading step:
Short demo with 2 cases - with and w/out devfile:
https://drive.google.com/drive/folders/1oPq4XDsu6PiCyNjqJW-ib2v3DZnsk3qi
@skabashnyuk @l0rd @slemeur wdyt ?

**Comment by l0rd** [comment]
@mshaposhnik that works fine for me thanks. I think you could improve it in 2 ways:

1. put the path of the devfile you are looking for (so that a dev will know how he need to call his devfile if it cannot be loaded)
2. if possible make the "not found sentence" more visible (i.e. using bold chars)

**Comment by mshaposhnik** [comment]
about the first - I'm added expected filename into message;
as for the second - i'm not sure it is possible with current dashb implenentation to set another text style for facory loading steps. The only avilable option yet is to fail step and make it bold red. If that strongly required we can make an separate issue.

**Comment by l0rd** [comment]
@mshaposhnik that's ok if we cannot make it bold.

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/12906
