### ISSUE TITLE
Command "Kubernetes: Delete Context" of Kubernetes Tolling don't work in Theia 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12745]
Kubernetes: Delete Context - Remove a cluster's configuration from the kubeconfig file - command don't work.
Probably problem comes form implementation  command 'vscode.previewHtml'  in Theia.
See: https://github.com/theia-ide/theia/issues/4051

**Comment by azatsarynnyy** [comment]
It depends on the context menu issue https://github.com/theia-ide/theia/issues/3882
The kube context, which is selected in the tree, isn't passed as an argument to the `Delete Context` command.
