### ISSUE TITLE
How long it will take to finalize Eclipse/Che 7 installation guide?

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#12742]
### Description
Finally, I have kubernetes cluster running on my laptop. No more minikube.
My software stack:
kubernetes cluster 
on top of Windows Docker Desktop (built-in)
on top of Hyper-V driver

What is missed to install Eclipse/Che 7 beta ?

**Comment by eivantsov** [comment]
@PavelSosin In fact Che 7 has been in master for a long time. There are two Che 7 stacks that you can try. Deploy Che as you'd normal do.

**Comment by PavelSosin** [comment]
Normally, I installed Che 6 on my personal computer for different goals more then 1 year ago. Today both the old goals and old Che architecture are irrelevant. I need Workspace.NEXT features implemented in Che 7. I would like to avoid usage of minikube due to llack of Hyper-V support and very negative experience. Anyway, minikube for windows, Ubuntu and Mac are obsolete and replaced by Docker desktop, Micro8s, etc. All these kubernetes components are built-in. It makes the old documentation obsolete too. From other hand, no separate documents are needed. Please, evaluate the option to utilize Operator framework to save developer's efforts.

**Comment by eivantsov** [comment]
@PavelSosin how will Operator framework solve infra problems?

And yes, Che operator is coming and will be available in OperatorHub.

**Comment by PavelSosin** [comment]
Hi Eugene, I think infra will take care on it. Windows, Mac, Ubuntu have kubernetes bundled. For AWS see [](https://aws.amazon.com/blogs/opensource/aws-service-operator-kubernetes-available/), In GCP you can install kubernetes using one short line command https://aws.amazon.com/blogs/opensource/aws-service-operator-kubernetes-available/

**Comment by eivantsov** [comment]
Eclipse Che Operator is going to be published on operatorhub.io soon
