### ISSUE TITLE
Is `AUTH_TYPE.CODENVY_SSO` still required ?

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12751]
### Description 

Just a question based on my code review.

https://github.com/eclipse/che/blob/0f8471014130c72b06c40b2b35137d72f3756dd9/dockerfiles/lib/src/api/wsmaster/auth/auth-data.ts#L208

Is `CODENVY_SSO` still required ?

**Comment by eivantsov** [comment]
@monaka it is not.

Btw, this is a che-lib image which is part of Docker infra support, that is dropped after Che 7 is released.

**Comment by monaka** [comment]
@eivantsov thanks for your information. I see. I leave that code as it is.
