### ISSUE TITLE
No progress status to check whether extension is install or not.

### ISSUE THREAD

**Issue by sudhirverma** [eclipse-che/che#12752]
I try to install VSCode extension on eclipse che after installing the extension it doesn't show any status whether it is installed or not.

**Comment by eivantsov** [comment]
@sudhirverma you can check it in Plugins panel which you need to enable in View (I might be wrong about the menu).

**Comment by invincibleJai** [comment]
@sudhirverma we can verify by checking `view -> plugin` and it should show up if you are trying to install the plugin by Id as @eivantsov suggested.

However, it should be intuitive like some notification has to be shown if the plugin has been successfully installed/failed.

**Comment by sudhirverma** [comment]
@eivantsov I would like to see the notification that plugin has been successfully installed/ failed on eclipse che. That would be great if we see the notification for installation.


rather than a `Kind/question` I think it's a `Kind/enhancement`.
