### ISSUE TITLE
Question: Is it possible to expose che service and workspace by nodeport in kubernetes?

### ISSUE THREAD

**Issue by zhashuyu** [eclipse-che/che#12754]
### Description
I currently install che 6.17.0 in kubernetes which does not have an ingress setup, so I can not access che service or che workspace by **domain name**.  

So is it possible to expose che service and workspace by NodePort ( kubernetes ) ?

kind/question

### Reproduction Steps
N/A

**OS and version:**    
kubernetes 1.13.3 with out ingress setup
che 6.17.0

**Diagnostics:** 
N/A

**Comment by garagatyi** [comment]
I do think that it is possible overall, but it is not yet implemented in Che. Now we rely on k8s ingress or openshift routes.
If you are willing to contribute this I can take a look and guide you on that.
