### ISSUE TITLE
Indicate in the list of plugins if the plugin is running in a sidecar or not

### ISSUE THREAD

**Issue by tgrall** [eclipse-che/che#12764]
Priority: Nice to have (low)

Since a user can configure the plugin to run in a sidecar or inside the theia container it could be interesting to show this information in the list of plugins.

Just a small information not critical but may be interesting when debugging or supporting the tool.

**Comment by garagatyi** [comment]
There were a fight regarding this feature in sprint review call comments. Who should validate whether we should implement it or not?
