### ISSUE TITLE
Che 7 plugin: Python 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12771]
Make a Che 7 plugin from the VS Code python plugin. Related Theia issue is here: https://github.com/theia-ide/theia/issues/3771

- [x] https://github.com/ws-skeleton/che-theia-generator/pull/18
- [x] https://github.com/eclipse/che-plugin-registry/pull/101
- [x] https://github.com/eclipse/che/issues/12845
- [x] https://github.com/theia-ide/theia/pull/4533
- [x] https://github.com/eclipse/che-theia/pull/107

https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by tolusha** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-python.python
