### ISSUE TITLE
Need to add ephemeral toggle (hidden by default) on the workspace creation view of UD 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#12776]
At the moment ephemeral toggle can be enabled only on the Workspace `Overview` view of the UD 
![image](https://user-images.githubusercontent.com/1461122/53492528-5c08d200-3a99-11e9-9271-536b5bb0d1dc.png)

The goal of this issue is to provide the ephemeral toggle on the workspace creation view. However, by default the toggle should not be visible and could only be enabled via property / env var e.g `SHOW_EPHEMERAL_TOGGLE`

**Comment by amisevsk** [comment]
@ibuziuk One issue with implementing this as configurable (in terms of visibility) is that I don't think we can handle properties in the UD code. I'm having trouble envisioning how the config flow would work.

**Comment by amisevsk** [comment]
Closed as outdated; it's simpler to implement this downstream at the moment and has been done in PR https://github.com/redhat-developer/rh-che/pull/1276
