### ISSUE TITLE
Eclipse Che and debugging large c++ project

### ISSUE THREAD

**Issue by saulide** [eclipse-che/che#12782]
### Description
`kind/question`
I wanted to use eclipse che as an IDE for not so sophisticated developers as entry point into a big project, so that they can develop some small chunks of code. The whole building of the project is made with help  of cmake files. Im aware that with cmake i can build a debug version and also use flag "Eclipse CDT4 - Unix Makefiles" to help some developers to run/debug the project in eclipse locally (then they need to add sources etc). But how can enable debugging in che? Any hints or examples?

**Comment by amisevsk** [comment]
Now that we are adding a C++ stack to the [sample devfiles](https://github.com/eclipse/che-devfile-registry/pull/73) we should document debugging if possible.

**Comment by amisevsk** [comment]
@saulide Sorry this one got stale; currently Che 7 has preliminary support for C++ debugging -- if you have Che 7 deployed, could you check if the current implementation suits your needs? 

You can test the devfile by passing it to a factory on your server: `https://<che-server-url>/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/ea8469eaf90192773e8cd47efacea4ceea7cb51d/devfiles/cpp/devfile.yaml`
