### ISSUE TITLE
Configuring Memory for Che 7 plugins

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12783]
We have some VS Code plugins that require more memory than the default amount for a sidecar. Technically, it is not a problem to change that in the textual workspace configuration. However, there are two things I would propose:

1. The default memory size for a plugin should be specified in the plugin metadata.
2. There should be an entry field on the UI item where you enable the plugin for the memory.

**Comment by benoitf** [comment]
related to https://github.com/eclipse/che/issues/11801

**Comment by garagatyi** [comment]
Do you suggest removing RAM limit from che-plugin.yaml spec?

**Comment by tsmaeder** [comment]
meta.yaml, che-plugin.yaml, what's the difference anyway?

**Comment by garagatyi** [comment]
The oldest plugin types `Che plugin` and `Che editor` are using `che-plugin.yaml` file hosted outside of the plugin registry to specify all the information about sidecars. Image, ports to expose, env vars, volumes and RAM. These plugins can also have several sidecars in their config, so single RAM limit might not be enough. 
But VS Code and Theia plugins don't use this, so can't specify RAM.  And they use a single sidecar, so single RAM limit is OK.

My question is whether you want to drop support of RAM limit in `che-plugin.yaml` or just add support of it to meta.yaml?

**Comment by sleshchenko** [comment]
Not sure if there is a plan to merge `che-plugin.yaml` and `meta.yaml` files but at least there is discussions and proposals to do it, like the following Mario's comment https://github.com/eclipse/che/issues/12708#issuecomment-466049910

**Comment by garagatyi** [comment]
I faced the situation to configure memory in workspace settings. It's awful UX. So, +1 to implement RAM limit support here ASAP.

**Comment by l0rd** [comment]
Will be fixed by #12908 that should be handled by @ibuziuk team in next sprinty

**Comment by l0rd** [comment]
The UI part should be fixed by https://github.com/eclipse/che/issues/11801
