### ISSUE TITLE
Theia plugin: .Net Debugger

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12790]
Since the VS Code extension for C# for Microsoft is licensed only for use with VS Code, we need to do what the Acute plugin for Eclipse did, namely create a Theia plugin using Samsung netcoredbg (https://github.com/Samsung/netcoredbg/releases)
Since this is similar to stuff like our VS Code extensions, I think the code should live in a repo under the Red Hat Developer org (https://github.com/redhat-developer/)
This plugin should be separate from any particular language support plugin (like C#), because multiple languages run on the .net platform.

**Comment by svor** [comment]
Plugin's location is https://github.com/redhat-developer/netcoredbg-theia-plugin
