### ISSUE TITLE
Theia plugin: C#

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12791]
Since the VS Code extension for C# for Microsoft is licensed only for use with VS Code, we need to create a Theia plugin  Omnisharp-Roslyn (https://github.com/OmniSharp/omnisharp-roslyn).
Since this is similar to stuff like our VS Code extensions, I think the code should live in a repo under the Red Hat Developer org (https://github.com/redhat-developer/)

**Comment by tsmaeder** [comment]
Omnipsharp has a mode where it works as a language server, there is a discussion about a bug that prevented this from working, which has since been fixed, I believe: https://github.com/OmniSharp/omnisharp-roslyn/issues/1269

**Comment by tsmaeder** [comment]
Theia already has a textmate grammar registered for C#, so no need to add one.

**Comment by svor** [comment]
Theia plugin Omnisharp-Roslyn is in https://github.com/che-incubator/omnisharp-theia-plugin.
Quick demo:
https://youtu.be/hox0hGDzWP8
