### ISSUE TITLE
Make current test suite more stable

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#12804]
### Description
_When the test suite is launched on CI (as daily run or in PR) we don't have 100% success rate. This fact don't allow to developer to understand that his changes nothing broke and require additional efforts from qe-team to analyze reports.
Need to note that number of failed test no too big and in general is a result complex infrastructure around E2E tests. As a rule when these tests run on to check on local machine, they are succcess._ 

To make the test suite moe reliability we can do next:
1) correct those of tests which perform redudant or duplicate actions, change some actions or steps (espesially actioins in project tree - expand, open file, in editor, etc.);

2) analyze test suite and remove the tests which are duplicate;

3) perform re-run of the failed tests in run time (it needs espesially for PR) to have full and readiable report by all launched tests.

**Che version**: 7.0.0-beta-2.0-SNAPSHOT
**Che install:** ocp/docker(single/multiuser)

**Comment by vkuznyetsov** [comment]
not actual
