### ISSUE TITLE
Custom Stack Not Being Used.

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1280]
Using custom stack over and over in develop sometimes it will not use my custom stack and will default to ready-to-go rails stack instead. Might have to run custom stack a couple of times to reproduce.

**Comment by ghost** [comment]
@james10174 I definitely need more details here.

**Comment by james10174** [comment]
Well now I cannot get it to reproduce error. If it happens again I will reopen this bug and put some screen captures.
