### ISSUE TITLE
How to config helm Chart values for Eclipse Che 7 beta on Windows docker desktop

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#12815]
To which Che version and platform Helm Chart in che/deploy/helm/che folder belong?

I'm trying to install Che7 beta in single user mode. When I look at values.yaml file i see some strange values for my landscape. values.yaml file is not documented at all and for my, very common use-case:
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   5d
I suppose a separate values file is needed.
How to config Helm values for Eclipse Che 7 beta on top of Windows Docker Desktop
**OS and version:**    
Windows 10 with Docker Desktop
As you can see Microsoft and Google assume that local users work via HTTPS but certificate based authentication in such scenario is obviously redundant

**Comment by eivantsov** [comment]
@PavelSosin I'm struggling to understand the question. Che version is actually an image tag used in Che deployment.
