### ISSUE TITLE
Documentation/Examples of server-side Extensions

### ISSUE THREAD

**Issue by kushgkh** [eclipse-che/che#12819]
### Description
I am trying a to build a server-side extension for Che 7 and I was wondering if there was any documentation for 7 for this, or if there was any good example extensions for 7 to look at. (Or if Che 6 server-side extensions are still relevant for my purposes)

**Comment by eivantsov** [comment]
@kushgkh Che 6 extensibility model is deprecated.

IN Che 7 a server side extension is a Theia plugin. I am not sure developer docs for Che 7 have been published already. @l0rd or @benoitf may know better.

**Comment by l0rd** [comment]
@kushgkh we do not have "official" documentation yet but:
- we have a few [examples here](https://github.com/eclipse/che-theia/tree/master/plugins) and some theia plugin documentation [here](https://www.theia-ide.org/doc/authoring_plugins)
- we offer compatibility with vscode extensions so you can write a [VS Code extension](https://github.com/Microsoft/vscode-extension-samples)
- you can reach out at https://mattermost.eclipse.org/eclipse/channels/eclipse-che-ide2-team
