### ISSUE TITLE
Feature request: storage class support for Kubernetes infra.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#12816]
### Description

Some infra admins may want to assign the specific storage class to Che.
One of the major case is: Their K8s cluster has already running for another services and the default storage class is not match to Che workspaces.

**OS and version:**    

CHE-7.0.0-beta-2.0-SNAPSHOT

**Comment by monaka** [comment]
I've already wrote this. I'll send the PR soon.

**Comment by amisevsk** [comment]
Thanks @monaka!
