### ISSUE TITLE
Using Docker in workspaces on Kubernetes

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12813]
### Description

Since access to the Docker socket is forbidden and YAML recipes restrict using volumes to mount /var/run/docker.sock

What is recommended way to use inside workspace tools like [skaffold](https://github.com/GoogleContainerTools/skaffold) which require docker and minikube to be available in a system?

Could someone provide Kubernetes YAML-based recipe?

Currently evaluating tools like Kaniko and Bazel that allows building images without docker daemon.

### References

- https://skaffold.dev/docs/how-tos/builders/
- https://stackoverflow.com/questions/51021874/building-docker-images-in-kuberentes-cluster
- https://applatix.com/case-docker-docker-kubernetes-part-2/

**Comment by monaka** [comment]
Just IMO, the better practice is to use builders outside your K8s cluster running your che.
 (like Azure ACR build, Google Container Build, ...)

The second suggestion is to run small instance (enough up to 1 core / 4GB RAM), `yum install docker-client` in your Che workspace,  and call it with `DOCKER_HOST=tcp://{the IP of the small instance}...`.

I tried Kaniko a few months ago. It was not still production level. I couldn't build some images from Dockefiles in `che/dockerfiles`. (I wish it is better than previous.)

**Comment by bohushvitali** [comment]
docker:dind container works as expected when specifying:
```
     securityContext:
      privileged: true
```

Unfortunately cannot get satisfiable results with running minikube or one of those solutions inside workspace:
https://github.com/kubernetes-sigs/kind
https://github.com/ubuntu/microk8s

It would be great to support release with comprehensive example of how to setup stack for development of large microservices applications inside Che workspase and provide reference Docker images and K8S recepies.

Example:
https://github.com/GoogleCloudPlatform/microservices-demo

Attaching containers at runtime and closer integration of Bazel and Skaffold would be also great.

**Comment by l0rd** [comment]
@bohushvitali that's a very good question. You won't be able to access the Docker socket when using Che: it's running in the cloud and if won't let user access the docker socket of the nodes that run the Kubernetes cluster.

That said we could still build containers from within a Che workspace with rootless build tools. There are some tools that should allow it currently (e.g. buildah and umoci).

And for minikube access you can inject kubeconfig and have access to it from within a Che workspace (c.f. `chectl workspace:inject --kubeconfig` https://github.com/che-incubator/chectl#chectl-workspaceinject).

These are just some ideas but I agree that we should investigate more on these scenarios.

**Comment by azatsarynnyy** [comment]
@bohushvitali I have some experience with building the images w/o Docker daemon in the rootless environment with [Buildah](https://github.com/containers/buildah) and I can confirm that's a great tool for using it in a Che Workspace.

One thing that wasn't so obvious when running Buildah in an unprivileged container is it requires setting `BUILDAH_ISOLATION=chroot` environment variable.

**Comment by sunix** [comment]
> @bohushvitali I have some experience with building the images w/o Docker daemon in the rootless environment with [Buildah](https://github.com/containers/buildah) and I can confirm that's a great tool for using it in a Che Workspace.
> 
> One thing that wasn't so obvious when running Buildah in an unprivileged container is it requires setting `BUILDAH_ISOLATION=chroot` environment variable.

@azatsarynnyy would you be able to write a devfile or instruction how to enable buildah in a Che workspace ?

**Comment by azatsarynnyy** [comment]
@sunix sure, I can share my Che Devfile with some of my experiments
https://github.com/azatsarynnyy/devfiles/blob/master/buildah-sidecar.yml
It runs a sidecar with Buildah where project image can be built with the `build` command

**Comment by l0rd** [comment]
For the records an updated buildah image is availabe here https://quay.io/repository/openshift-pipeline/buildah
