### ISSUE TITLE
Errors displayed while building Dashboard locally.

### ISSUE THREAD

**Issue by qurben** [eclipse-che/che#12825]
### Description
 

When trying to get the dashboard to build locally I stumbled upon some TypeScript errors generated when building. The build process seems to continue properly and a javascript file is generated just fine.

### Reproduction Steps

Run `mvn clean install` inside the dashboard. In the `build-image` image step, after running `npx yarn` in the docker image several errors about `Cannot find namespace 'che'.` are reported. 

**OS and version:** Version 7.0.0-beta-1.0. On Debian 9 in WSL and Win10. In native and docker profiles.

**Diagnostics:** 

See https://pastebin.com/hqdmC0km for the log. Starting at line 298 a total of 1127 errors are reported.

**Comment by qurben** [comment]
There are also some warnings, but these seem to be related with the version of webpack which is used.

**Comment by eivantsov** [comment]
@ashumilova is this smth easy to get rid of?

**Comment by qurben** [comment]
Fixed in #12826
