### ISSUE TITLE
How can I grant permissions to stack to all users except for admin?

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#12827]
### Description
I added a custom stack and granted permissions to all users in swagger page.
![image](https://user-images.githubusercontent.com/29850624/53721934-b34ae000-3ea7-11e9-9dc5-74fc9578164e.png)

But when admin goes to the stack page, There are two identical stacks.
![image](https://user-images.githubusercontent.com/29850624/53722914-e8f0c880-3ea9-11e9-918a-e1fcf2bdf7bf.png)

How can I grant permissions to stack to all users except for admin?

**Comment by sleshchenko** [comment]
@kellyhyomin There is no way to grant permissions to all users except specified.
Could you elaborate more, what are these two identical stacks? One is shared by you and another is admin personal? Or one is predefined, and another is shared by you?
Does non-admin user see only one test stack?

**Comment by kellyhyomin** [comment]
@sleshchenko 
Thank you for your help.
I am an admin. I made a stack which name is test and I granted the stack permission(search, read permissions) to all users. 
Even though there is already a stack(name is test) created by the admin, the same stack is created for the admin as well. (I think the admin is also one of the users)

**Comment by sleshchenko** [comment]
@kellyhyomin Could you provide a response of get stacks method (${CHE_HOST}/swagger/#!/stack/searchStacks). I assume that these two stacks are different.

**Comment by kellyhyomin** [comment]
@sleshchenko 
Thank you for your help.
I know that stacks are different. But I(admin) deleted one of two stacks, both are deleted.
I want the admin to have only one stack even if admin granted permissions to all users.

**Comment by sleshchenko** [comment]
@kellyhyomin I've checked your case locally and now I see that it is a bug. Because the same stack is displayed twice.Thanks for reporting.

**Comment by kellyhyomin** [comment]
@sleshchenko  Ok! Thank you

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/12833.
@kellyhyomin Feel free to reopen if it won't help you.
