### ISSUE TITLE
.devfile in Eclipse Che repo is not working

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12821]
### Description
.devfile in Eclipse Che repo is not working.
```
Error occurred during parsing list from file .che-dev.yaml for tool 'che-dev': An error has occurred.
```
![11 55 22](https://user-images.githubusercontent.com/1614429/53725336-774a5780-3e74-11e9-9b87-01e4aabab8d7.png)

### Reproduction Steps

- http://che-eclipse-che.192.168.64.50.nip.io/f?url=https://github.com/eclipse/che

**Comment by garagatyi** [comment]
As far as I can see error message clearly says that this case is not supported. Can you elaborate why this should be qualified as bug?

**Comment by skabashnyuk** [comment]
@garagatyi you referring to an old description of the issue. I've updated it some time ago with correct usage of .devfile in che repository. I and @sleshchenko are able to reproduce in on nightly images. Now we testing master.

**Comment by sleshchenko** [comment]
Works for me on my local Che installation that has Che built from https://github.com/eclipse/che/commit/f76cc4dae7ebff299fbe2490e04c651a63318536
Does not work for me with 
`
docker.io/eclipse/che-server                             nightly             e5adc787dedc        About an hour ago   335 MB
`
Debug shows that local url is specified as content.
![screenshot_20190304_121824](https://user-images.githubusercontent.com/5887312/53726993-da89b900-3e77-11e9-8f5e-b2ce391ffeb6.png)
Maybe it does not contain the following fix https://github.com/eclipse/che/commit/3cd3628adfd0d516716166b2d155cbd51c479abd

**Comment by sleshchenko** [comment]
Looks like a true. A nightly image does not contain the needed commit
![screenshot_20190304_122236](https://user-images.githubusercontent.com/5887312/53727188-453af480-3e78-11e9-91db-35266c14f92c.png)

**Comment by skabashnyuk** [comment]
Working on the latest images. Closing.
