### ISSUE TITLE
eclipse/che 7 helm gzip invalid zipped

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#12820]
### Description

COMMITTERS: please include labels on each issue. Labels are listed here: https://github.com/eclipse/che/wiki/Labels but at a minimum you should include `kind` and `status` labels.

--> 

### Reproduction Steps

**OS and version:**    
Docker desktop on Windows 10
**Diagnostics:** 
see helm issue https://github.com/helm/helm/issues/2916
the analyzes points on how zip is packed.

**Comment by PavelSosin** [comment]
I took master branch of Eclipse Che 7 beta project. I I didn't build Che by myself, only install. My gzip7 is fresh. I didn't find any difference in kubernetes deploy folders. No new version was submitted to helm repository. Which branch is stable? To Which chart version is stable?

**Comment by eivantsov** [comment]
@PavelSosin there were no changes in master when the version was switched to 7.x-BETA. Can this be Windows related?
