### ISSUE TITLE
[Che 7] Golang plugin doesn't work upon loading a Go project

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#12824]
### Description
I created a Che 7 workspace with nightly Theia (Although I can reproduce with Theia 1.0.0) and the Go plugin selected. Upon loading a .go file, the `package main` line will have an error marker on it saying: `/usr/local/go/pkg/tool/linux_amd64/link: signal killed`. 

Furthermore, none of the Go plugin features are available, intellisense and code highlighting are also missing.

Despite this, the Go plugin is listed under View -> Plugins in Theia. Looks like it crashed?

### Reproduction Steps
1. Create a Che 7 workspace with the Go plugin and nightly Theia
2. Import a Go project (such as https://github.com/che-samples/web-go-simple)
3. Open the main.go file. Syntax highlighting will be missing.
4. Open the task menu and search for Go, none of the usual Go commands (like Go fmt, build package, etc) will be there
5. The `package main` line in main.go should have an error marker on it and if you hover over it, it will say: `/usr/local/go/pkg/tool/linux_amd64/link: signal killed`

**OS and version:**    
1. Docker for Desktop with Kube. 
2. Kube 1.13
3. Latest Che

**Edit:** A screenshot showing the error 
![screen shot 2019-03-04 at 1 58 32 pm](https://user-images.githubusercontent.com/6880023/53755881-ab7a4400-3e85-11e9-90ca-02379d545b90.png)

**Comment by eivantsov** [comment]
@johnmcollier signal killed looks like an OOM issue to me. However, I can't be sure. How much RAM does your Docker VM have?

Missing syntax coloring is a known issue.

**Comment by johnmcollier** [comment]
@eivantsov Thanks, I'll try with more RAM.

**Comment by l0rd** [comment]
And I would add that you can try to increase the memory limit for the sidecar using the following workspace configuration attribute:

```json
"ms-vscode.go.memory_limit": "1024Mi"
```

**Comment by tsmaeder** [comment]
Also, it looks like GOPATH does not include anything in /projects, be default. See https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension
