### ISSUE TITLE
Permissions issues wtih anyuid and pre-create subpaths on

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#12847]
### Description

When anyuid is on, and `CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS` is set to true which is a default value, Che 6 workspace does not start. It happens for common pvc policy (i think it should happen for per workspace as well)

### Reproduction Steps

1. Deploy Che with pvc policy common and precreate subpaths true (both are default)
2. Configure your cluster to allow anyuid:

```
oc adm policy add-scc-to-group anyuid system:authenticated
```
3. Start a workspace.

Bootstrapper cannot start because it fails to write log file to /workspace_logs, which isn't writable for a current user in a container.

I think it happens because subpath isa created by a centos image by a root user.

**Comment by l0rd** [comment]
Once this issue is solved we should update minishift addon templates as well https://github.com/minishift/minishift/tree/master/addons/che/templates

**Comment by eivantsov** [comment]
Fixed by https://github.com/eclipse/che/pull/12892
