### ISSUE TITLE
OK for minikube but not for Docker Desktop

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#12857]
### Description
 Ok for minikube but it is recomended not to use minikube. for Windows/Mac/Ubuntu DockerDesktopsif you have KUBECONFIG=....\.kube\config you are running locally and get cluster IP via **kubectl get services** 
default context is assumed to be set correctly. Otherwise nothing works. Worming: if you have both,  minikube Docker Desktop and switch between minikube and Docker Desktop verify that the desired context is set as default. Due to strange glitch minikube and bundled kubernetes add junk to kubeconfig file during startup. I  recommend to erase  redundant contexts  from kubeconfig using text editor or kubectl config. Watch Docker Desktop icon on to taskbar to see which context is default. If you need some special docker daemon configuration (IPV6 is enabled by default!) the config.json file is available via link on the settings screen. 
I suppose, the Micro8s  has similar configuration.
Best wishes
**Diagnostics:**

**Comment by eivantsov** [comment]
@PavelSosin is this a bug report or an enhancement request?
