### ISSUE TITLE
code-server integration

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#12854]
### Description

`code-server` is a Project from the folks at [Coder](https://github.com/codercom/code-server) that runs a remote version of Visual Studio Code in a container. I think we can also enable this as a Cloud IDE option in Che for those who wants a VSCode environment.

**Comment by garagatyi** [comment]
Tried to use it as an Editor `https://raw.githubusercontent.com/garagatyi/che-coder-editor/master/org.eclipse.che.editor.codercom:0.1.0` but failed. Now it uses root user and I'm not sure we should add this to Che since Che is usually running in cloud environments where root/sudo is not allowed.

**Comment by sr229** [comment]
@garagatyi its possible to run it as a non-root. See `chinodesuuu/coder:latest`/ `chinodesuuu/coder:openshift`

**Comment by garagatyi** [comment]
Thanks, with this image it run on openshift. But Che editor loader coded adds query parameter to it (`?uid=123456798`) and codercom doesn't work because of this query parameter. So Che UD shows black screen instead of the IDE, but if I go to the IDE url exposed by Openshift route (which doesn't contain query parameter) then codercom works.

**Comment by garagatyi** [comment]
I have created an issue about that in codercom repo https://github.com/codercom/code-server/issues/220

**Comment by sr229** [comment]
I think this is how they handle their http server. I'll look into it as well.

**Comment by sr229** [comment]
@garagatyi give `web` branch a go. I made some [tarballs](https://github.com/sr229/cdr-web-lkgr) for them and they seem to be stable for now.

**Comment by gorkem** [comment]
@sr229 I do not thing @garagatyi is active on Che project anymore. Are you interested on completing this work an adding it as an alternate IDE to Che?

**Comment by sr229** [comment]
I'll try to add it around October and see if there's any major bumps from there.

**Comment by sr229** [comment]
Finished the Editor plugin, you can try it out [here](https://github.com/sr229/che-cdr).

**Comment by sr229** [comment]
Can anyone guide me how do I put this in on mainline since I can't find any reference on how to push it to the tree on the docs

**Comment by skabashnyuk** [comment]
@sr229 here https://github.com/eclipse/che-plugin-registry/search?q=Che+Editor&unscoped_q=Che+Editor is the list of all awailable ```Che Editor```. You can start with making pr to  https://github.com/eclipse/che-plugin-registry
