### ISSUE TITLE
Db traces too talkative

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12851]
### Description
Follow up discussion https://github.com/eclipse/che/pull/12843#discussion_r263500234

I've added db traces as an experiment since some times getting db logs can be complicated. It turns out that these traces don't provide a lot of value. As for me, it's better to get reports like this https://github.com/eclipse/che/issues/9099#issue-305453729 to be able to analyze how db subsystem behaves.

To reduce the load on jaeger I've proposed db traces

1. Disable. we can use Jaeger configuration https://www.jaegertracing.io/docs/1.10/sampling/#collector-sampling-configuration
2. Enable/Disable with named parameter
3. Remove it at all.

![54008080-f8cf0d80-4132-11e9-97d1-c568d5308aa2](https://user-images.githubusercontent.com/1614429/54085154-3efabb80-4343-11e9-9fe9-caebce0a8f62.png)

**Comment by skabashnyuk** [comment]
I vote for 3. ```Remove it at all.```

**Comment by ibuziuk** [comment]
I would rather opt for 2 `Enable/Disable with named parameter`

**Comment by garagatyi** [comment]
+1 for option 2 with disabled by default. Since Angel has already implemented this [here](https://github.com/eclipse/che/pull/12843) it would be also very cheap option that might be used for different cases

**Comment by skabashnyuk** [comment]
ok let's go with option two.

**Comment by skabashnyuk** [comment]
Done in https://github.com/eclipse/che/pull/12947
