### ISSUE TITLE
The workspace 'x' is currently running and cannot be removed.

### ISSUE THREAD

**Issue by bsatoriu** [eclipse-che/che#12862]
### Description
I have a user that was deleted and re-added to keycloak, but a workspace was created prior to user account deletion, and now the user is met with an error when trying to log in:

`org.eclipse.che.api.core.ServerException: The workspace 'workspace0bakw72x2e7boveo' is currently running and cannot be removed.`

I was able to remove the Kubernetes namespace associated with this workspace, which caused the associated Docker container to be removed. However, the same error is being raised on login. How can I permanently remove this workspace or get around this error?

`kind/question`

### Reproduction Steps
1. User creates a new workspace in Che
2. User is deleted from keycloak
3. User logs back in to Che.
Result: 500 error described above.

**Comment by bsatoriu** [comment]
Still working through this error but wanted to provide the full stack trace in case it is helpful. Evidently this error is being triggered during an account reregistration cleanup process. At this point I'm just trying to get past the error to login, but am somewhat new to Che and not sure what the right path is.

```
org.eclipse.che.api.core.ConflictException: The workspace 'workspace0bakw72x2e7boveo' is currently running and cannot be removed.
	org.eclipse.che.api.workspace.server.WorkspaceManager.removeWorkspace(WorkspaceManager.java:270)
	org.eclipse.che.api.workspace.server.jpa.JpaWorkspaceDao$RemoveWorkspaceBeforeAccountRemovedEventSubscriber.onCascadeEvent(JpaWorkspaceDao.java:287)
	org.eclipse.che.api.workspace.server.jpa.JpaWorkspaceDao$RemoveWorkspaceBeforeAccountRemovedEventSubscriber.onCascadeEvent(JpaWorkspaceDao.java:263)
	org.eclipse.che.core.db.cascade.CascadeEventSubscriber.onEvent(CascadeEventSubscriber.java:29)
	org.eclipse.che.core.db.cascade.CascadeEventSubscriber.onEvent(CascadeEventSubscriber.java:24)
	org.eclipse.che.api.core.notification.EventService.publish(EventService.java:108)
	org.eclipse.che.account.api.AccountManager.remove(AccountManager.java:110)
	org.eclipse.che.multiuser.api.account.personal.PersonalAccountUserManager.remove(PersonalAccountUserManager.java:81)
	com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:64)
	org.eclipse.che.multiuser.keycloak.server.KeycloakUserManager.getOrCreateUser(KeycloakUserManager.java:115)
	org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:128)
	org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:70)
	org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:114)
	org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
	org.eclipse.che.api.core.cors.CheCorsFilter.doFilter(CheCorsFilter.java:58)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
```

**Comment by eivantsov** [comment]
@bsatoriu do you get this error when a user logs in? No mistake here?

**Comment by bsatoriu** [comment]
@eivantsov that's correct. The error occurs after successful login, then instead of seeing the dashboard, it's this 500 page. I can still log in fine as admin, and other users can log in ok.

**Comment by eivantsov** [comment]
When you login, you must be redirected to a workspace page?  Try incognito mode  and Che URL as is.

**Comment by bsatoriu** [comment]
@eivantsov thanks for the suggestion--I am redirected a a workspace page. Any workspace page generates a 500 response. Incognito mode does not affect the outcome.

**Comment by bsatoriu** [comment]
I ended up working around this by changing the email address for my account in Keycloak, which essentially tricked the Che workspace manager into not recognizing me as a former user and loading the zombie workspace. I believe the original issue still stands, however, pending further verification.
