### ISSUE TITLE
Is there a way to keep keycloak-data when I deploy multi-user Che using helm?

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#12865]
### Description
I installed Che with helm on k8s.
But when I enter the 'helm delete ~' command, all keycloak pvs are also deleted.
Even if I delete che with helm, I want to keep keycloak users.
Is there a way to keep keycloak-data(pv) when I deploy multi-user Che using helm?

 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
@kellyhyomin helm delete purges everything. Can you elaborate on your use case? If you want to delete everything but keep database, you may delete object manually.

Out of curiosity why do you need to delete Che but keep this PV?

**Comment by kellyhyomin** [comment]
@eivantsov 
I have to keep my keycloak-data pv because I want to keep the keycloak user information even if we delete it.
You know, if I lose my keycloak user information, I can't log in to che.
In my use case, I have installed Che as helm in AWS EKS.
I am using it in conjunction with AWS RDS (Postgresql) for postgres-data.
So, in the case of postgres-data, helm delete does not delete it.
The way I currently maintain keycloak-data is using aws ebs as pv and connecting pvc.
As long as ebs is not deleted, keycloak data information can be maintained.
What I'm wondering is there is a way that eclipse che can suggest other than this.
Thank you for your help.
