### ISSUE TITLE
CHE go-lang plugin doesn't resolves imports in the go files.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12878]
### Description
CHE go-lang plugin doesn't resolves imports in the go files. I think it because vscode go-plugin doesn't contains `/projects` volume in the go path in the plugin tool container.

### Reproduction Steps
1. Create blanch workspace from such config:
```
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "ws/dev": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {
            "terminal-dev": {
              "attributes": {},
              "port": "4445",
              "protocol": "http"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {}
        }
      },
      "recipe": {
        "type": "kubernetes",
        "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: 'aandrienko/che-machine-exec-dev:latest'\n     name: dev\n     resources:\n      limits:\n       memory: 1024Mi\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [],
  "name": "go-lang",
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:next",
    "sidecar.ms-vscode.go.memory_limit": "2048Mi",
    "plugins": "che-machine-exec-plugin:0.0.1,ms-vscode.go:0.9.2"
  },
  "commands": [],
  "links": []
}

```

> Note this is workspace with installed go, dep, git, bash tools. Dockerfile(created for local Minikube, doesn't contains file permission fix for osio):
```
FROM golang:1.10.3-alpine

RUN apk add --update git bash && \
    # Todo install stable dep tool version.
    go get -u github.com/golang/dep/cmd/dep
RUN mkdir -p /projects/src

ENV GOPATH="/projects:${GOPATH}"

EXPOSE 4445 4445

CMD tail -f /dev/null
```

2. Open terminal ws/dev container.
3. Do command: 
`$go  get github.com/eclipse/che-machine-exec`.
4. Go to /projects/src/github.com/eclipse/che-machine-exec in the terminal and compile project:
`$ ./compile.sh`
5. > ?! Maybe this bug with remote plugin reconnection was already fixed, but if not:
in the theia editor container:
`$ ps ax`
find PID for theia process `node src-gen/backend/main.js /projects --hostname=0.0.0.0 --port=3100`
$ kill -9 PID
Refresh browser tab...
6. Open /projects/src/github.com/eclipse/che-machine-exec/main.go
Actual result:
![go-lang-plugin-dev-attampt](https://user-images.githubusercontent.com/6873095/54280228-a2812500-459f-11e9-98a6-0eb0633a38b1.png)

## Proposed solutions:
- Patch docker image go-lang plugin and apply "/projects" to the GO_PATH env. "/projects" is already  mounts like volume, so potentially it should work. Short term to try it.
- We could apply ability to set up env variables for CHE plugin tool container.  It could be useful not only to modify env Paths. Longer term to implement it.

**Comment by AndrienkoAleksandr** [comment]
@sleshchenko @garagatyi @eivantsov What do you think?

**Comment by garagatyi** [comment]
We should definitely set proper GO_PATH

**Comment by AndrienkoAleksandr** [comment]
@benoitf Maybe you know about status this one:
> ?! Maybe this bug with remote plugin reconnection was already fixed, but if not:
in the theia editor container:
`$ ps ax`
find PID for theia process `node src-gen/backend/main.js /projects --hostname=0.0.0.0 --port=3100`

**Comment by benoitf** [comment]
@AndrienkoAleksandr hello I'm not sure to understood your last comment ?

**Comment by benoitf** [comment]
@AndrienkoAleksandr which version are you using of che-theia ?

**Comment by AndrienkoAleksandr** [comment]
@benoitf In the config of the workspace was `org.eclipse.che.editor.theia:next`

**Comment by AndrienkoAleksandr** [comment]
Fix should be https://github.com/eclipse/che/issues/12878

**Comment by tsmaeder** [comment]
@AndrienkoAleksandr you need to tell the system where your GOPATH is: if we add "/projects" to the GOPATH, it's not going to work. When you check out a project form github, for example, it's going to be at /projects/<project_name>/.
The VS Code extension we are using has documentation on this: https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension

**Comment by eivantsov** [comment]
@tsmaeder tes, create the right scructure in /projects, so `/projects/src/blah-blah.com/yourProject`. I tried that and it works. Better than nothing.

**Comment by tsmaeder** [comment]
Yeah you're right.

**Comment by AndrienkoAleksandr** [comment]
Fixed after https://github.com/eclipse/che-theia/pull/122
