### ISSUE TITLE
Incorrect version of che exposed to UD for downstream projects

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#12872]
### Description

Incorrect version of che exposed to UD for downstream projects. e.g. `rh-che` updated to 7 beta 1 has the following version in UD:

![image](https://user-images.githubusercontent.com/1461122/54219049-ff70d280-44ee-11e9-8139-7fbe4fb3cf41.png)

downstream `pom.xml` looks the following way:

>     <parent>
>         <artifactId>che-parent</artifactId>
>         <groupId>org.eclipse.che</groupId>
>         <version>7.0.0-beta-1.0</version>
>     </parent>
>     <groupId>com.redhat.che</groupId>
>     <artifactId>fabric8-ide-parent</artifactId>
>     <version>1.0.0-SNAPSHOT</version>

Previously parent version was exposed to the downstream UD

Potential culprit - https://github.com/eclipse/che/pull/12691

**Comment by ibuziuk** [comment]
@skabashnyuk any thoughts how should we handle this issue? Will it be ok to revert #12691 in che 7 beta 2 cc: @rhopp @nickboldt

**Comment by nickboldt** [comment]
Works for me. See also https://github.com/eclipse/che/issues/12871

I'm still overriding the string by hand when building Che as part of the CRW assembly, so this change shouldn't impact CRW. 

Should this be pushed to to 6.19.x too?

**Comment by skabashnyuk** [comment]
@ibuziuk looks like in upstream we can't figure out which version or string downstream wants to show.
What I can suggest. Is to collect your and @nickboldt requirements about what and where you want to show. After that, we can figure out the way how to provide that information and embed it in different places.

**Comment by skabashnyuk** [comment]
I propose to close this issue in favor of https://github.com/eclipse/che/issues/12871
CC @eivantsov

**Comment by ibuziuk** [comment]
@skabashnyuk I'm ok to close, the only requirement from my side is to display upstream version in the UD footer (In 7 beta 1 it started to show downstream version, which we would like to avoid since we are not doing releases in downstream, but rather CI / CD):

![image](https://user-images.githubusercontent.com/1461122/54266895-8fa72a00-4578-11e9-9003-8b78567bb8f0.png)

**Comment by ibuziuk** [comment]
Closing as fixed. version of che server is correctly reported in che.openshift.io
