### ISSUE TITLE
Provide a way to push additional build-time information to the Che Help > About dialog

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#12871]
### Description

To better support QE and GSS in identifying which build of Che and CRW a user is using, we'd like to be able to add more metadata to the Help > About dialog in Che/CRW.

Ideally, this would be via a maven property set at build time, so we can define it using Jenkins properties and information parsed from github. 

### Reproduction Steps

Today, the Help > About dialog only contains 3 pieces of information:

```
Version: 1.1.0.GA
Build Time: 2019-02-28 12:49:42
Revision: 8c7d7b42abcdef00cafebabe
```

![wksp-build-info](https://user-images.githubusercontent.com/227597/54213980-c408e080-44bb-11e9-940a-996c78d9ed1d.png)

We'd like to be able to add these:

Che version: 6.19.0
Build ID: crw_stable-branch # 99
Branch: 6.19.x

Or if thats too many variables to set / too much UI to code, how about we just provide an overridable maven property called `CRWVersion` that could contain this string when invoking the build, as a replacement for the simpler Version string of `1.1.0.GA`:

```
mvn clean install -DCRWVersion='1.1.0.GA (Eclipse Che 6.19.0) :: crw_stable-branch # 99 @ cafeb00b / 6.19.x'
```

**Comment by nickboldt** [comment]
Downstream issue: https://issues.jboss.org/browse/CRW-168

Related issue: https://github.com/eclipse/che/pull/12691

**Comment by skabashnyuk** [comment]
@nickboldt this string suppose to be shown in GWT IDE only? What other places exist?

**Comment by skabashnyuk** [comment]
CC @ibuziuk

**Comment by nickboldt** [comment]
It would be useful in any IDE - Theia too. Whole point is to provide information to the user/customer. 

Does Theia UI not provide a similar Help > About > Build info panel?
