### ISSUE TITLE
Unable to forcibly stop , delete the Workspace in STOPPING state

### ISSUE THREAD

**Issue by dorinburcea** [eclipse-che/che#12884]
### Description
Environment used:
-che-server:6.9.0 in multiuser in k8s in AWS. 

Problem:
Assume this is first time the issue happens after two months using the che in this setup. 
I have one workspace that is **pending in STOPPING state**. I can't do anything to stop or delete it using dashboard functions. 
I checked in kubernetes there was a rm-pod with status Terminated (usually they do the job and then disappear from kubernetes) 
I removed the deployment from kubernetes for that specific workspace. I can't figure out how to force the workspace status . Your support is highly appreciated.

Thanks

**Comment by sleshchenko** [comment]
There is no ability to forcibly stop a workspace. But Che Server should get rid of such hanging workspace after Che Server restart (like after 10 minutes after new Che Server start).
@dorinburcea Are you able to trigger new deployment for Che?

**Comment by dorinburcea** [comment]
@sleshchenko  Thanks . I remove the che pod. A new pod was created automatically and is running . Wait now more than 10 mins , in dashboard the worspace status still STOPPING
Thanks

**Comment by sleshchenko** [comment]
@dorinburcea Could you please set the following env var for Che Server and rerun it
```
export CHE_LOGGER_CONFIG=org.eclipse.che.api.workspace.server=DEBUG,org.eclipse.che.workspace.infrastructure.kubernetes=DEBUG
```
It should show debug information of k8s infra, including a component that gets rid of hanging workspaces https://github.com/eclipse/che/blob/4758e5a45314864081159737b5c3d6682010656d/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/RuntimeHangingDetector.java#L78

**Comment by sleshchenko** [comment]
@dorinburcea I see that `RuntimeHangingDetector` is introduced in `6.13.0` while you're using `6.9.0`. I can suggest you to update your installation to the latest `6.x` version or at least to `6.13.0`?

**Comment by dorinburcea** [comment]
@sleshchenko then this feature is only available from version >= 6.13.0 ?. I installed the current che version using HELM charts . What is the recommended procedure for update to a newer version? . I guess just changing in the kubernetes che deployment the che image tag is not enougt , is it?

**Comment by sleshchenko** [comment]
It's a good question.
I think that you need to checkout helm chart to version you update to and set che image tag.

@eivantsov @l0rd You may know more about helm charts. Please correct me if I'm wrong

**Comment by dorinburcea** [comment]
@eivantsov @l0rd  according with each k8s deployment file the current situation is :
 -CHE eclipse/che-server:6.9.0
 -Keycloack: eclipse/che-keycloak:nightly
-Postgres: eclipse/che-postgres:nightly

**Comment by l0rd** [comment]
@dorinburcea what about https://helm.sh/docs/helm/#helm-upgrade: `helm upgrade che ${CHART_PATH}`
