### ISSUE TITLE
[TS-SELENIUM] Remove "WorkspaceCreationAndLanguageServerInitialization.spec.ts" 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#12888]
### Description

For now, the "WorkspaceCreationAndLanguageServerInitialization.spec.ts" is not used AFAIK. 
Goal of this issue is to verify it's not used and if not, remove it from codebase.

**Comment by sunix** [comment]
@Ohrimenko1988 @rhopp could you update the status of this ?
