### ISSUE TITLE
CHE dashboard unable to track the RUNNING state of workspace

### ISSUE THREAD

**Issue by dorinburcea** [eclipse-che/che#12886]
My environment : 
che-server:6.9.0 in multiuser in k8s in AWS. 
Here how I reproduced:
1)worspace based on stack image registry.centos.org/che-stacks/centos-jdk8
2) Click on start the workspace 
3) In kubernetes the nginx ingress are created almost immediate
4) The workspace container is created and then the pod is running
5) I am able to navigate via chrome browser the at the ingress host that points to the ws-agent address http(s)://serverdr4fd7p5-sbweb3j-dev-machine-server-4401.<mydomain> 
6) Inside the workspace pod the the bootstraper log appear like
![image](https://user-images.githubusercontent.com/21106256/54343578-142da180-467a-11e9-9c53-55f8394e4b5f.png)
7) The web browser console log looks like this 
![Capture_websocket_console](https://user-images.githubusercontent.com/21106256/54343721-666ec280-467a-11e9-9e79-e3eee0331b90.PNG)
8) After a while dashboard is still not able to capture the workspace statusChange and workspace start timeout. The CHE clean-up process starts and remove the pods and all ingress. 

Thanks in advance for support

_Originally posted by @dorinburcea in https://github.com/eclipse/che/issues/11147#issuecomment-472762833_

**Comment by eivantsov** [comment]
@dorinburcea there are a lot of improvements in workspace-server communications in the latest 6.19.x tags. Can you try 6.19.0?
