### ISSUE TITLE
minikube helm multiuser tutorial - workspace never opens

### ISSUE THREAD

**Issue by markns** [eclipse-che/che#12891]
### Description
After following the minikube helm multiuser tutorial, I've been trying to open a simple Python workspace with the `console-python3-simple` example, however the workspace never opens.

### Reproduction Steps
```
https://www.eclipse.org/che/docs/che-6/kubernetes-multi-user.html

helm upgrade --install che --namespace che -f ./values/multi-user.yaml --set global.ingressDomain=192.168.99.102.xip.io .
```
**OS and version:**    
```
minikube  ~  minikube version
minikube version: v0.35.0
minikube  ~  kc version                                                                                                                           
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Diagnostics:** 
Logs in console
```
Loading...
pulling image "eclipse/ubuntu_python:latest"
Successfully pulled image "eclipse/ubuntu_python:latest"
Created container
Started container
```

Workspace _is_ running, however there are no logs in the container.
```
workspaceuey8gjaezql5vbxn   workspaceuey8gjaezql5vbxn.dockerimage-58b6458767-qmw7r   1/1       Running   0          1m
```

Che server logs, also nothing interesting:
```
2019-03-14 19:56:03,787[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 511]    - Workspace 'admin/wksp-3g0h' with id 'workspaceuey8gjaezql5vbxn' created by user 'admin'
2019-03-14 19:56:05,051[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 383]   - Starting workspace 'admin/wksp-3g0h' with id 'workspaceuey8gjaezql5vbxn' by user 'admin'
```

Nothing in the kube events either. 

Finally the workspace times out. Chrome becomes unresponsive at the same time, so here's a screenshot rather than a c&p of the text
<img width="1066" alt="Screenshot 2019-03-14 at 21 08 53" src="https://user-images.githubusercontent.com/368384/54388327-c9be1c00-469d-11e9-871a-ce7a69967d1c.png">

**Comment by johnmcollier** [comment]
@markns A fix for multi-user workspace creation was just merged today https://github.com/eclipse/che/pull/12877, I'd try reinstalling Che with the fix to the Helm chart to see if it's fixed for you.

**Comment by markns** [comment]
Great, that fixed it 👍
