### ISSUE TITLE
Dashboard: starting and stopping a workspace doesn't update UI

### ISSUE THREAD

**Issue by ppitonak** [eclipse-che/che#12890]
### Description

Starting or stopping a workspace from `Workspaces` view doesn't update workspace's status. Refreshing the page fixes the problem.

![che_dashboard](https://user-images.githubusercontent.com/445100/54363595-7af78e80-466b-11e9-8df1-db75340d545e.gif)

### Reproduction Steps

1. start latest version backend and frontend
2. create a workspace
3. open `Workspaces` view
4. stop the workspace
5. start the workspace

**OS and version:**    

Fedora 29

**Diagnostics:**

**Comment by eivantsov** [comment]
@ppitonak can you consistently reproduce it? Also, if you open browser dev console, there must be some failed websocket connections.

**Comment by ppitonak** [comment]
@eivantsov you are right. I tried it on che.openshift.io and it **works** there.

However, when I start che using 
```
docker run -it --rm  -v /some/path/to/chedatanightly/:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:nightly start
```
and start the dashboard (latest commit) using `gulp serve` it is broken.

![che_network](https://user-images.githubusercontent.com/445100/54519275-6b778e80-4966-11e9-94e4-6436111c4e00.png)

**Comment by ppitonak** [comment]
Still reproducible on https://che.openshift.io

/remove-lifecycle stale

**Comment by ppitonak** [comment]
@ashumilova it seems that I cannot cancel teh stale label. Could you please do it for me?

**Comment by benoitf** [comment]
@pputonak Command needs to be a single comment

**Comment by sleshchenko** [comment]
Seems this issue was actual only for running local Che with docker.
@ppitonak feel free to reopen it if you still face the same behavior on the latest Che
