### ISSUE TITLE
A TLS packet with unexpected length was received.

### ISSUE THREAD

**Issue by dklesev** [eclipse-che/che#1290]
I'm getting this error if I try to start with just a blank project (or any other example):

> Error while creating the project
> Internal Server Error: fatal: unable to access 'https://github.com/che-samples/blank/': gnutls_handshake() failed: A TLS packet with unexpected length was received.

My spec:
- Running on OpenStack
- Ubuntu 15.10 with 4.2.0-36-generic Kernel
  - 16GB RAM
  - 8 Cores
- Docker version 1.11.1, build 5604cbe
- Che 4.2.0 (running from binary package)
- Tried to open all ports without success

Simple `apt-get update` doesn't work from within the container, but pinging is ok:

> user@b7bccccbe60c:/$ sudo apt-get update  
> Ign http://archive.ubuntu.com trusty InRelease  
> 10% [Waiting for headers] [Waiting for headers]

**Comment by dklesev** [comment]
Solved it by myself. It is the MTU issue in Docker 1.11.
Ref: https://github.com/docker/docker/issues/22028

I've just added --mtu=1454 (which refers to my eth0 configuration) in the systemd service definition.
(/lib/systemd/system/docker.service)

Don't forget:

```
$ sudo systemctl daemon-reload
$ sudo service docker restart
```

I hope this will help someone.

**Comment by TylerJewell** [comment]
@dklesev Good find.  Thanks for reporting the fix back.
