### ISSUE TITLE
JUnit 5 Support

### ISSUE THREAD

**Issue by adolinski** [eclipse-che/che#12915]
### Description
Not an issue, and not sure where I post questions or how to "make a wish". I was wondering if there would be Che support to run JUnit 5 tests via the UI (via Test -> Run Test)

**Comment by tolusha** [comment]
Hi.
We haven't tested against JUnit5. 
So, some some features might not work.

**Comment by amisevsk** [comment]
Reopening as JUnit 5 is used in Quarkus by default [1].

[1] - https://quarkus.io/guides/getting-started-testing

**Comment by amisevsk** [comment]
Reopening because I forgot to remove `lifecycle/stale`.
