### ISSUE TITLE
Dashboard: Display error mark about Che 6 workspaces

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12917]
### Description
Che 6 based workspaces are not going to remain compatible with Che 7. 
Dashboard will need to allow a user to know if the workspace is still working on not. 

In the list of workspaces:
- We should display a visual indicator to notify the user that the workspace will not work anymore. 
- We would provide a link on documentation explaining how to create a workspace in Che7. 
- We would remove the ability to start the workspace. 

In the workspace details:
- We will display a message (in the header) explaining that the workspace is not compatible and needs to be converted as a Che 7 workspaces. Including a link to the documentation on how to do that.

**Comment by olexii4** [comment]
@slemeur  Could you add some details, mockups?

**Comment by slemeur** [comment]
@olexii4 Unfortunetally I'll not have time to provide you mockups. What kind of details do you need?

cc @serenamarie125 FYI

**Comment by olexii4** [comment]
Ok. Thanks.
@slemeur You wrote, "We should display a visual indicator to notify the user that the workspace will not work anymore".  Could I reuse an existing one(add a black color and a tooltip)? WDYT?
![Screenshot from 2019-04-24 13-11-07](https://user-images.githubusercontent.com/6310786/56651899-b9349480-6692-11e9-940f-6d1fdc1b3dff.png)

**Comment by slemeur** [comment]
Try to find something more obivous and easier for the end-user. (maybe display the message "This workspaces is not compatible with this version of Che")

**Comment by olexii4** [comment]
@slemeur  Is this issue include creating documentation part about how to convert Che 6 as a Che 7 workspace? I cannot find it.

Could you help me with the needed links?

**Comment by olexii4** [comment]
@slemeur Should we remove CHE6 workspaces from the recent workspaces sections and factory workspace resources?
![Screenshot from 2019-04-26 11-49-39](https://user-images.githubusercontent.com/6310786/56795590-781abc80-6819-11e9-8601-4f9abcfc798d.png)
![Screenshot from 2019-04-26 11-49-19](https://user-images.githubusercontent.com/6310786/56795598-7cdf7080-6819-11e9-8034-d7a61126a2b6.png)

**Comment by olexii4** [comment]
https://youtu.be/KnbFbQaPAbo
@slemeur  WDYT?
