### ISSUE TITLE
Handle incompatible Factories between Che 6 and Che 7

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12918]
### Description
Not all the factories will be compatible between Che 6 and Che 7.
We need to handle that properly and provide a clear message to the end-user.

**When a user is starting a factory that is incompatible**
Display an error message on the loader, explaining the factory must be converted to Che 7 based factories and a link to the documentation.
We should also provide a way to the user to continue the process manually:
- We will preselect the project to be cloned
- We will redirect the user into the workspace creation page, where he'll be able to choose a stack and move forward. 

**In the list of factories on the dashboard**
We should display an indicator on the factories that are not compatible and include a link on how to move to the new definition.

**Comment by olexii4** [comment]
It depends on  [che#13381](https://github.com/eclipse/che/issues/13381)
