### ISSUE TITLE
Documentation: How to Add Support for a New Debugger

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12916]
Add a section on how to add a new debugger in Che 7 to the [Che 7 Docs:] (https://docs.google.com/document/d/1BH2oUq3gJhsNsKqdUOXpoe1Z9qf9ARTdxXyBNo10l20/edit?ts=5c90a775#bookmark=id.aecox7xya36q)

**Comment by tolusha** [comment]
https://che.eclipse.org/how-to-add-support-for-a-new-debugger-for-che-theia-f459ea806ff
