### ISSUE TITLE
Dashboard : Should not display the list of sample plugins

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12910]
### Description
While providing sample plugins is very nice to detail how to use each of the API - we should not be showing that by default to the end users.

When creating a new workspaces / or editing an existing ones, the users will want to configure real plugins only. 

When the user is creating a workspaces for Che in Che development or Plugin developemnt, we should be showing those plugins in the samples.

**Comment by l0rd** [comment]
We should remove the sample plugins from the registry and add them as samples for the che in che stack. Is it right @slemeur?

**Comment by slemeur** [comment]
Yes sounds good ! thank @l0rd
