### ISSUE TITLE
Allow building and running applications at workspace start with devfile v2 post start events

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12925]
### Description
We are now relying on devfile for the factory flow. 

Factories are providing extended capabilities, allowing post-loading actions to open file, start a command. 
We should be able to extend the devfile to allow a user to define those actions. 

We should also make sure that users will be able to define factories with a devfile (and extended meta-datas). JSON, even if used internally by WSMaster would not be exposed anymore to the end-user.

### User Stories
In the dashboard, when the user is editing the definition of a factory, it must be based on the devfile format.
- In the dashboard, a user should be able to create a factory by providing a devfile and defining the extended meta-datas.
- In the dashboard, a user should be able to create a factory from an existing workspace.

(In other words, whereever we are displaying the factory.json configuration in the dashboard, it should be replaced by devfile)

**Comment by skabashnyuk** [comment]
@slemeur is this issue still in our GA plan? Are we going to support persistent factories in Che7 era?

**Comment by skabashnyuk** [comment]
@l0rd wdyt? can we remove GA label?

**Comment by l0rd** [comment]
@skabashnyuk removed

**Comment by sleshchenko** [comment]
There is no progress and even no priorities for persistent factories with new Devfile format for quite a long period of time and at the same time, there is `Factories` page that is totally broken.
I propose at least remove that page from navigation bar to provide better UX.
@slemeur @l0rd WDYT?

**Comment by mingfang** [comment]
Also devfiles with components of `type: kubernetes` does not work with factories.
Here is my devfile https://github.com/mingfang/terraform-provider-k8s/blob/master/devfile.yaml#L66 that works find when the content is used to manually create a workspace, but fails when using with factory.

**Comment by skabashnyuk** [comment]
>Also devfiles with components of type: kubernetes does not work with factories.
Here is my devfile https://github.com/mingfang/terraform-provider-k8s/blob/master/devfile.yaml#L66 that works find when the content is used to manually create a workspace, but fails when using with factory.

@mingfang thanks for your feedback. I think it's worth a separate issue to address. From first glance, I can't see `terraform.yaml` on the same level as devfile.yaml. I can't see it anywhere in https://github.com/mingfang/

**Comment by mingfang** [comment]
@skabashnyuk I'm using `resourceContent` to embedded the content. https://github.com/mingfang/terraform-provider-k8s/blob/master/devfile.yaml#L30

**Comment by skabashnyuk** [comment]
@mingfang are you sure https://github.com/mingfang/terraform-provider-k8s/blob/master/devfile.yaml#L67 ?

**Comment by sleshchenko** [comment]
@skabashnyuk I'm sure ;)
Yaml editor has issue with heightening multi-strings blocks. I've described it in some of Che Dashboard issue.
@mingfang Please a register the dedicated issue bug/question with detailed info about your case: Che version, error message you see.

**Comment by sleshchenko** [comment]
Let's be honest, P1 issue can't be untouched for 1 year.

**Comment by sleshchenko** [comment]
I think it can be closed as won't fix in the flavor of https://github.com/eclipse/che/issues/16875
@l0rd WDYT?

**Comment by l0rd** [comment]
@sleshchenko I am not sure. This issue is about "post-loading actions" too and #16875 is only about persisting devfiles as factories.

**Comment by l0rd** [comment]
@sleshchenko I have changed the title to reflect that.

**Comment by matthewfisch** [comment]
What the heck team? Is this still broken? I just wasted over an hour trying to get factories working and then stumbled on this.

So .... users can't share workspaces any other way, only copy/paste devfiles right?

**Comment by sleshchenko** [comment]
@matthewfisch In addition to copying/pasting devfiles, there is available factory flow, where users are able to host devfile somewhere, like git repo, and then just provide a link to create a workspace, like
to github repo https://che.openshift.io/f?url=http://github.com/eclipse/che
or devfile content https://che.openshift.io/f?url=https://raw.githubusercontent.com/eclipse/che/master/devfile.yaml

There is also an issue where you can track adding new feature - users devfile, in a few words - Che will allow to host devfiles for further sharing https://github.com/eclipse/che/issues/16875.

**Comment by matthewfisch** [comment]
I am heartened that I can still use the factory flow using devfile.yaml .... but I don't understand why there's a broken factories screen. Is there any way it should work?

**Comment by veeramanikandanvv** [comment]
I am not able to create factories in eclipse che 7.17.0. I am not seeing any workspaces listed when we try to create factories out of of workspaces. Application displays error messages as - this factory is using old workspace definition. I am not able to see any documentation to update the factory runtime configuration. 
Eclipse che 7.17.0, multiuser, single host.
Installed via helm on kubernetes. Please help me on this issue

**Comment by skabashnyuk** [comment]
@veeramanikandanvv persisted factories are not implemented in Che7 . Similar logic would be implemented as User devfiles https://github.com/eclipse/che/issues/16875

**Comment by sunix** [comment]
setting back to p1.
So be able to add at least che-task or theia command to start automatically when the workspace is starting

**Comment by sleshchenko** [comment]
removing dashboard and controller since it's more about devfile/v1. Once it's implemented via spec - we can think how to use that in Che Theia and Dashboard.

**Comment by l0rd** [comment]
Should be fixed by https://github.com/devfile/devworkspace-operator/pull/659
