### ISSUE TITLE
Allow to specify 'latest' version of plugins in workspaces definitions

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12937]
### Description

Although it's important to be able to specify a particular version of a plugin/editor to be included in a workspace or stack, in most cases we just need latest version. 

This issue is to allow a definition of a workspace plugin without a specific version:

```yaml
id: che-machine-exec-plugin
```

and with version `latest`:

```yaml
id: che-machine-exec-plugin:latest
```

This should work for devfiles, workspaces json and stacks.

Subtasks created:

- [x]  redhat-developer/rh-che#1395
- [ ]  redhat-developer/rh-che#1396

**Comment by ibuziuk** [comment]
A potential solution is to create "latest" folder which would always duplicate the highest version of the plugin

**Comment by ibuziuk** [comment]
@l0rd am I correct that plugin without version e.g. `id: che-machine-exec-plugin` = `latest` ?

**Comment by l0rd** [comment]
Yes you are correct

**Comment by ibuziuk** [comment]
For me, it looks like a relatively simple issue that can be delivered in the 2 steps (and even split into two issues):
- [ ] `id: che-machine-exec-plugin:latest` case can be solved by the creation and a requirement for all `v2` plugin always having the `latest` folder with the dedicated content (chagnes) - estimate (1-2 sp.) 
- [ ] id: che-machine-exec-plugin case should be tackled on wsmaster / plugin broker side (when version is missing always fall back on the `latest`) - estimate (3p.)

@l0rd does this sounds like a good plan? If yes, I would create 2 dedicated rh-che issues for the next sprint planning.

**Comment by l0rd** [comment]
@ibuziuk yes that looks like a good plan. Another thing you need to take care of are the versions of the exec and theia that are automatically added by wsmaster (when a user do not specify them in a Devfile). You should probably use version 'latest' for both and it could be part of the first task.

**Comment by ibuziuk** [comment]
Subtasks created:
- [ ] https://github.com/redhat-developer/rh-che/issues/1395
- [ ] https://github.com/redhat-developer/rh-che/issues/1396

**Comment by amisevsk** [comment]
A PR for `latest` folders is here: https://github.com/eclipse/che-plugin-registry/pull/143, but I don't know if this is the direction we want to go in. Ideally the plugin registry is more than a httpd server and can return the latest version by itself -- manually maintaining latest dirs in the registry could be error-prone.

**Comment by amisevsk** [comment]
Closing as the core issue here is out of date.
