### ISSUE TITLE
Complete the `che-rest-apis` server with additional required APIs

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#12939]
### Description

Complete the `che-rest-apis` server (started as a side-car container in the workspace) with additional APIs required by the Che-Theia or other components.
Also include basic websocket endpoint to allow, for example, plugin brokers to report their status and have this status reflected in the workspace status.

**Comment by gorkem** [comment]
@davidfestal I am not sure I like the idea of starting an API server instance with every workspace. Should we still need to continue with this approach?
