### ISSUE TITLE
Customized Che6 migration Che7

### ISSUE THREAD

**Issue by 781227k** [eclipse-che/che#12931]
### Description

I've written multiple ws-agent and IDE(GWT) extension based Che-6 architecture with also customized Docker CLI in order to build and run my che.

I want to migrate them to Che 7 such out-of-box migration is possible? If not what is the way to do it?

**Comment by gorkem** [comment]
Che 6 and Che 7 IDE structures are very different, I do not think it would be possible to use the GWT based plugins directly.
