### ISSUE TITLE
How to custom a project template from a hosted ZIP archive

### ISSUE THREAD

**Issue by Madixin** [eclipse-che/che#1294]
I get the latest doc :https://eclipse-che.readme.io/docs/templates

The template lets the initial code tree to be instantiated from a git / URL or from a hosted ZIP archive.

I try to config a new template in "samples.json"  for che version 4.2.2 

`
 "source": {
      "type": "zip",
      "location": "/tutorials/client-new-project-wizard.zip",
      "parameters": {}
    },
`

it can not get the template........

**Comment by ddementieva** [comment]
It seems you've used some old configs. Right now it's possible to provide only an URL to a remotely hosted zip archive.

**Comment by Madixin** [comment]
I also have try a remote host zip archive ,it still not work

`
    "source": {
      "type": "zip",
      "location": "http://10.64.136.253/test/web-java-spring-master.zip",
      "parameters": {}
    },
`

**Comment by TylerJewell** [comment]
@42690727 The docs on the templates were recently rewritten, so maybe a mistake in there. @ddementieva @slemeur - can you please provide a complete example with a remote ZIP?

**Comment by ddementieva** [comment]
@42690727 Make sure the URL is publicly available. 

To check it you may want to try `wget` it in the Terminal, i.e from within the container. Perhaps, using eth0 or wlan0 IP is a good way to go.

**Comment by Madixin** [comment]
@ddementieva  
the URL is available.I have tested wget it in the Terminal in container

Can you give me a  complete example?  Or is there any debug info?  I have not found any debug info even I use "-d" parameter to start

**Comment by ghost** [comment]
@42690727 this should work for you, if you are able to `wget` this zip from within a workspace:

```
{
    "name": "spring-java",
    "displayName": "spring-java",
    "path": "/spring-java",
    "description": "Spring sample.",
    "projectType": "maven",
    "mixins": [],
    "attributes": {},
    "modules": [],
    "problems": [],
    "source": {
      "type": "zip",
      "location": "http://10.64.136.253/test/web-java-spring-master.zip",
      "parameters": {}
    },
    "commands": [],
    "links": [],
    "category": "Samples",
    "tags": [
      "java"
    ]
  }
```

**Comment by Madixin** [comment]
Thanks,the template code has download in workspace,and I can use this project in che.

But  the "create-project" view  always suspend in "Creating project Step",and no info in background .
Creating and initializing workspace ... completed
Starting workspace runtime ... completed
Starting workspace agent ... completed
Creating project

Is this a bug?I use  che version 4.2.2.

**Comment by ghost** [comment]
@42690727 can you repeatedly reproduce it? With any workspace, stack and sample?

**Comment by Madixin** [comment]
yes,I can  reproduce it. 

it can reproduce it both  in "Select existing workspace" and "Create new workspace from stack"

I just add your config in sample.json,  and choose "java-default stack" and the config sample

**Comment by ghost** [comment]
@42690727 did you try the latest nightly build?

**Comment by Madixin** [comment]
I have try the latest code to build the version eclipse-che-4.3.0-RC1-SNAPSHOT.  

The same problem.

**Comment by ghost** [comment]
@42690727 I cannot reproduce it on my side.

Do you see any errors in browser console? Maybe failed websocket connections etc?

**Comment by Madixin** [comment]
There is a  409 ajax call fail

Remote Address:10.93.61.32:32885
Request URL:http://10.93.61.32:32885/wsagent/ext/project/xxx
Request Method:PUT
Status Code:409 Conflict

Response
{"message":"pom.xml does not exist."}

but web-java-spring-master.zip is from same as the standard in github, it has pom.xml in it

**Comment by ghost** [comment]
@42690727 most probably when unpacked, there's a folder with source files. Can you make sure that when unzipped, source files are unpacked in the root, not to a directory.

**Comment by Madixin** [comment]
thank you , it  is ok now.

I want to make sure how can I turn on the debug info in the backend?    because there is not any info in backend

**Comment by ghost** [comment]
@42690727 you may run Che with `--log_level:debug`. In this case, standard logs will be printed into the console, but `tomcat/logs` catalina.out will have the detailed debug logs.

**Comment by ghost** [comment]
Closing the issue. Feel free to reopen if the problem is still there for you or you have some questions.

**Comment by Madixin** [comment]
ok , thank you
