### ISSUE TITLE
How to query user Keycloak profile from workspace agent

### ISSUE THREAD

**Issue by bsatoriu** [eclipse-che/che#12948]
### Description
I'm looking for the recommended approach to get the user's own name and attributes from within our JupyterLab workspace agent. The machine token doesn't seem to provide a pathway to accessing the REST API. 

This is the documentation I've been using to attempt retrieving one's own profile data: https://www.eclipse.org/che/docs/che-6/authentication.html

It makes reference to a DAO class, KeycloakProfileDao, but it's not clear how to reference this class from within a ws agent.

Thanks for your help.

**Comment by sleshchenko** [comment]
@bsatoriu There is a Profile Service[[1](https://github.com/eclipse/che/blob/57c43ac8cdd7111649414545a6ee9d156392d249/wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/ProfileService.java#L88)] which should retrieve and return Keycloak profile. But machine token has limited access and as far as I see profile serivce is not available for it [[2](https://github.com/eclipse/che/blob/e2991cd050dcd85625ac5393345685c6b6dae75b/multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java#L75)]. @mshaposhnik Am I right?
Machine token is JSON Web Token and already contains some information about user. What you do need from Keycloak profile? Maybe it is already present in machine token.

[1] https://github.com/eclipse/che/blob/57c43ac8cdd7111649414545a6ee9d156392d249/wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/ProfileService.java#L88
[2] https://github.com/eclipse/che/blob/e2991cd050dcd85625ac5393345685c6b6dae75b/multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java#L75

**Comment by bsatoriu** [comment]
@sleshchenko the machine token only includes the id for the user, but no other data related to the user, such as the information you would see in the account profile in the dashboard or, importantly for us, the user profile attributes.
