### ISSUE TITLE
Add basic management of  Workspace Status in the Workspace CRD controller

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#12940]
### Description

Add basic management of  Workspace Status in the Workspace CRD controller

The status should reflect the global state of the workspace, as well as the state of its containers.

**Comment by ibuziuk** [comment]
@davidfestal downstream issue is closed. Can we close this one also? 
Demo - https://youtu.be/MZdogrJfD6k

**Comment by davidfestal** [comment]
Yes, we can.
