### ISSUE TITLE
Config Editor has no "Save" Button

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12957]
1. Create a Che 7 workspace
2. "Save and continue editing"
3. Go to the "Config" tab of the workspace editor
4. Observe: there is no "Save" button for the editor.

All other tabs show a "Save" button at the bottom of the screen to save changes. This is inconsistent and confusing.

**Comment by tsmaeder** [comment]
When you make multiple changes, you get multiple dialogs saying "Workspace configuration has been updated", but you are not sure whether your latest changes have been saved or if the dialog comes from an older edit that has been saved. I find this behaviour extremely annoying when a simple "save" button that becomes enabled upon changes is a decades old, simple and clear UI for this.

**Comment by tsmaeder** [comment]
Or if autosave is really necessary, at least provide a clear indication of the dirty status of the editor?

**Comment by sttyerase** [comment]
Repeating my comments from Mattermost: at the *minimum* from a standpoint of consistency, the "save" button should appear there.  I have major challenges when UIs give inconsistent signals about behavior. Even the plugins selection UI engages the "save" button when a change is made.

**Comment by mhockelberg** [comment]
In workshops with customers using Che, we have had feedback that having a consistent indicator to make user aware that changes have been saved and adding a "Save" button would make the user experience better.  AND to consider making autosave an optional behavior/preference IDE setting for each user.

**Comment by mmorhun** [comment]
I think we may close this issue as `Save` button was added to workspace configuration page in https://github.com/eclipse/che/pull/14913
