### ISSUE TITLE
Error retrieving Che 7 plugins

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12953]
### Description

I got this error while starting a Che 7 workspace:

```
2019-03-21 10:40:00,086[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 242]  - Failed to start Kubernetes runtime of workspace workspaceyh3rf8kf8o3day3z. Cause: Error occurred on retrieval of plugin che-machine-exec-plugin:0.0.1. Error: che-plugin-registry.openshift.io
```

That happens on local minikube ~~and osio as well~~ whereas it works on minishift and osio.

**Comment by garagatyi** [comment]
I can not reproduce this on my local OCP and OSIO (ws doesn't start there because of routes, but it is way after the error you are describing can occur).
Have you seen it a couple of times or it is constantly reproducing? 
Have you seen it before?

**Comment by l0rd** [comment]
I had not seen that before. It fails consistently on minikube started with chectl. It works on minishift started with chectl as well. It works on openshift.io now. I will try to investigate more on that later.

**Comment by benoitf** [comment]
I'm using chectl/minikube and I don't reproduce it

**Comment by l0rd** [comment]
Fixed
