### ISSUE TITLE
Communication between workspace, master, and API

### ISSUE THREAD

**Issue by mayadebellis** [eclipse-che/che#12956]
### Description
Hi I am looking for some direction on working with the API - 

I want to have the ability to interact with the API inside a workspace. I understand that most of the API is not available in this context. (https://www.eclipse.org/che/docs/che-6/authentication.html) Is there a way to communicate through master to the API? Something that triggers the master to make an API call and send back the info? I'm not clear on where I can actually call the API from as I don't know how to access the master.

Alternatively, is there a way to extend master to inject more into the workspace environment? I have not seen any documentation on how to build extensions like this. The page for server [side extension documentation](https://www.eclipse.org/che/docs/che-6/server-side-extensions.html) is empty. 

Thank you!

**Comment by sleshchenko** [comment]
@mayadebellis You're able to call Che Server from workspace with machine token. Che Server API URL can be evaluated in a workspace using `CHE_API_INTERNAL` env var (there is also `CHE_API_EXTERNAL` for communication between brower and Che Server). Machine token is also stored in environment variable names `CHE_MACHINE_TOKEN`.

Here you can find APIs that can be called with machine token
https://github.com/eclipse/che/blob/e2991cd050dcd85625ac5393345685c6b6dae75b/multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java#L51-L75
The first parameter is a service name, further parameters are methods names.

I hope it can be useful for you. Let me know if available APIs is not enough in your case

**Comment by mayadebellis** [comment]
@sleshchenko Thanks! That gives me a clearer picture of what is possible. But there are things that I would like to do that aren't options.

For example, if I wanted to get information about a user's `/profile`, how could I do this? Could a call be made somewhere else and the information passed in as environment variables? Or where would I be able to make this call from?

I am also interested in how other `/workspace` features can be updated besides the methods for project shown above.

**Comment by sleshchenko** [comment]
> For example, if I wanted to get information about a user's /profile, how could I do this? Could a call be made somewhere else and the information passed in as environment variables? Or where would I be able to make this call from?
> I am also interested in how other /workspace features can be updated besides the methods for project shown above.

You're able to call other methods (/profile, update workspace) only with Keycloak token which can be retrieved only by client (Dashboard, GWT IDE) that is load from the same host where Che Server is.
Let me mentioned initial motivation why we limit machine token abilities: workspace is a thing that can be shared with other users, and where any plugins can be run (like with unknown logic), and in this case, we should protect workspace owners data as much as possible.
