### ISSUE TITLE
Java 8 cannot handle some SSL certificates

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#12959]
### Description
The Che server currently runs with Java 1.8.0_191. I've found out that Java in that version cannot handle SSL certificates issued by cloudflare with TLS 1.3 enabled.

When trying to use the standard Java mechanism for reading http(s) connections, the code errors out claiming that the server responded with status code 403.

This should be solved by upgrading to Java 9 or later.

This makes the workspace factory unreliable, because we can't be sure we will be able to handle the supplied URL.

### Reproduction Steps
Follow https://github.com/metlos/url-connection-tests

**OS and version:**    
Che7 beta 1

**Comment by skabashnyuk** [comment]
AFAIK

The major security enhancement introduced in JDK 11 is provided by JEP 332: Transport Layer Security (TLS) 1.3. This is the new version of the TLS protocol that provides a number of enhancements over the previous (1.2) version of the TLS specification. In addition more enhancements are made to the root certificates in the cacerts keystore (some root certificates are added and some removed).

That means that we are talking about an upgrade to Java 11 if we are TLS 1.3 is needed.

**Comment by skabashnyuk** [comment]
No longer relevant. We use java 11 in master at this moment.
