### ISSUE TITLE
Tweak ephemeral workspace warning

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#12960]
The warning created for [ephemeral workspace startup](https://github.com/eclipse/che/pull/12799) is good, but needs a couple of tweaks:

>You are starting an ephemeral workspace. All changes to the source code will be lost when the workspace is stopped unless they are pushed to a source code repository. You can create a persistent storage workspace by unselecting 'ephemeral mode' in the workspace configuration.

We should also have some kind of notice in the IDE UI itself - it probably makes sense in the bottom status bar where you have the git information. We can make the text orange and have it say: `Ephemeral mode, push to source code repo to save work`

**Comment by bmicklea** [comment]
@ashumilova please review

**Comment by ashumilova** [comment]
@bmicklea I will fix the warning message on workspace start. 
About IDE status bar: 
![image](https://user-images.githubusercontent.com/1611939/54911585-79de2100-4ef7-11e9-8578-3c59421ef2a5.png)
with tooltip on hover "All changes to the source code will be lost when the workspace is stopped unless they are pushed to a source code repository."

**Comment by ashumilova** [comment]
@vparfonov please, take a look at this one. Just the part - to have the same message in status bar in GWT IDE.

**Comment by vzhukovskii** [comment]
@ashumilova will take a look on it

**Comment by bmicklea** [comment]
Thanks!

**Comment by vzhukovskii** [comment]
@bmicklea @ashumilova wdyt?

![image](https://user-images.githubusercontent.com/1968177/54933252-f63b2900-4f24-11e9-8029-338797c5752b.png)

**Comment by bmicklea** [comment]
Can you make it yellow or orange so it sticks out a little more?
-- 
Brad Micklea // Group Lead, Developer Tools & Program // 416.707.0792

**Comment by vzhukovskii** [comment]
![image](https://user-images.githubusercontent.com/1968177/54935199-7e6efd80-4f28-11e9-9c50-eaa14908eae6.png)

**Comment by bmicklea** [comment]
Looks good to me!
-- 
Brad Micklea // Group Lead, Developer Tools & Program // 416.707.0792

**Comment by ibuziuk** [comment]
@vzhukovskii thank you for helping with GWT IDE customization. Am I correct that this change would be available in che 7 beta 3 release?

**Comment by vzhukovskii** [comment]
>Am I correct that this change would be available in che 7 beta 3 release?

Yep. That's correct.
