### ISSUE TITLE
Multiple reconnection to websocket (api/websocket) on creating workspaces

### ISSUE THREAD

**Issue by ankkumar-progress** [eclipse-che/che#12966]
### Description
This issue is hard to explain but will try my best to be precise and make it understandable.

Let me take a step back and explain why we are using eclipse che.
We are developing a web based IDE for which we are using [theia](https://www.theia-ide.org/).
And as EclipseChe has workspace concept using K8s , life is easy for us.

The issue will be more understandable to one who has idea on elcipse che and theia.

Coming to the issue,

When I am trying to create multiple workspace, it reconnects to the web socket (api/websocket) multiple times.
Due to which, theia frontend reconnects to theia backend web socket connection.

![image](https://user-images.githubusercontent.com/45970796/54926855-24c1ff80-4f37-11e9-8bf7-ffe6d4d98e80.png)

Can anyone please look into this issue?

**Comment by sleshchenko** [comment]
@ankkumar-progress The following issues may be related to this one https://github.com/eclipse/che/issues/9943, https://github.com/eclipse/che/issues/8675, https://github.com/eclipse/che/issues/12928

I see that in your K8s installation Nginx ingress backend is used, right? If yes, then the issue may be caused by nginx server reloading.

**Comment by ankkumar-progress** [comment]
@sleshchenko 
I checked the links given by you #9943, #8675, #12928 .
It seems ingress-nginx removed the option --enable-dynamic-configuration in the [later](https://github.com/kubernetes/ingress-nginx/pull/3198/files) version and made it default
But it is weird that it is not working.
And also I am not in favour of using worker-shutdown-timeout. 
Because it tries to connect after the timeout and using 24h is not a safe option.

**Comment by amisevsk** [comment]
@ankkumar-progress If you're still interested in this issue, could you please confirm that its still present with the current Che release (7.2.0)?

**Comment by ankkumar-progress** [comment]
I think we can close the issue.
I am no more working on the story related to this issue
Sorry for that

**Comment by amisevsk** [comment]
No worries, thanks.
