### ISSUE TITLE
Run Che and Che workspaces as a non-root user in a Kubernetes cluster

### ISSUE THREAD

**Issue by stnnguyen95** [eclipse-che/che#12969]
### Description

Che and Che workspaces are started as root when deployed in a Kubernetes cluster using the deployment here: che/deploy/kubernetes/helm/che
I would like to be able to specify a non-root user when deploying Che in a Kubernetes cluster.

### Reproduction Steps
Deploy Che using the Helm chart here: che/deploy/kubernetes/helm/che
Once Che is started, shell into the Che container and enter the id command.
It shows that root is the running shell.
Similarly, create a workspace, a blank workspace for instance and start it. Once it is up and running, shell into the container and run the id command. It shows that root is the owner of the running shell.

**OS and version:**    
Linux

**Comment by monaka** [comment]
I close this as #12970 was merged.
