### ISSUE TITLE
Confusing workspace menu items 

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#12962]
`Open Workspace`, `Open Recent Workspace` and `Close Workspace` menu items and commands are confusing in Che because the workspace concept of Theia and Che are not same. We need to override or remove these menu items to avoid future confusion. 

Ideally we should have a `Close Workspace` which stops the Che workspace and remove the remaining workspace related commands.

**Comment by azatsarynnyy** [comment]
done within https://github.com/eclipse/che/issues/17106
