### ISSUE TITLE
How to activate Che on Private Network

### ISSUE THREAD

**Issue by hsgwd** [eclipse-che/che#12976]
I'm trying to activate Eclipse Che on network configuration like below.  

![networking](https://user-images.githubusercontent.com/43225784/54987516-1687e800-4ff8-11e9-9694-2d349da0a275.png)

I think containers and browser should communicate via IP Address below.
- browser -> workspace container: Grobal IP Address
- browser -> che-server container: Grobal IP Address
- browser -> keycloak container:  Grobal IP Address
- che-server container -> workspace container: Private IP Address
- che-server container -> keycloak container: Private IP Address

I tried to run eclipse che by following command.

```
docker run -it -e CHE_MULTIUSER=true \
                    -e CHE_DOCKER_IP=$PRIVATE_IP \
                    -e CHE_DOCKER_IP_EXTERNAL=$GLOBAL_IP \
                    -e CHE_HOST=$GLOBAL_IP \
                    -e CHE_API=$GLOBAL_IP \
                    -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://$GLOBAL_IP:5050/auth \
                    --rm -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /var/test/data:/data eclipse/che:6.14.1 \
                    start
```
As a result of that, che-server container tried to communicate with keycloak via Global IP address and failed.  
(Because of our networking problem, the server cannnot communicate with itself via Global IP Address)  

In another case, I tried to run Che by command below.

```
docker run -it -e CHE_MULTIUSER=true \
                    -e CHE_DOCKER_IP=$PRIVATE_IP \
                    -e CHE_DOCKER_IP_EXTERNAL=$GLOBAL_IP \
                    -e CHE_HOST=$GLOBAL_IP \
                    -e CHE_API=$GLOBAL_IP \
                    -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://$PRIVATE_IP:5050/auth \
                    --rm -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /var/test/data:/data eclipse/che:6.14.1 \
                    start
```
As a result of that, che module in browser tried to communicate with keycloak via Private IP address and failed.

Which environment variable settings enable following communication ?
- browser -> keycloak: Global IP Address
- che-server -> keycloak:  Private IP Address

Thank you in advance.

**Comment by garagatyi** [comment]
Have you considered running Che on kubernetes instead of Docker (at least on kubernetes provided by Docker for Windows/Mac)? 
Running Che on Docker is an outdated variant of running Che since all the efforts of maintainers are focused on Che 7 (which runs on kubernetes/openshift only) at the moment.
