### ISSUE TITLE
Rename containers view

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#12984]
We should rename the containers view to `My Workspace`, calling it containers is misleading. It is a view of the containers, commands and endpoints on the currently running workspace. We should also change its logo to Che an appropriate Che logo.

**Comment by gorkem** [comment]
@slemeur FYI

**Comment by slemeur** [comment]
Yeah agree with that. Good point.

**Comment by evidolob** [comment]
Is it OK?
![Screen Shot 2019-04-02 at 15 36 25](https://user-images.githubusercontent.com/929743/55402891-34f06500-555d-11e9-8ceb-515e70336c5a.png)

**Comment by sunix** [comment]
What about just `Che` ?
We have already a subtab named `workspace` other subtab could be for user profile or anything else ...

**Comment by l0rd** [comment]
My devfiles, My preferences etc...should be part of another view

For `My Workspaces` view I think that we should rather have:

```
My Workspace
   |--User Runtimes
   |      '-- theia-end 
   '--Plugins
         '-- jdt ls
```

**Comment by slemeur** [comment]
Yes agreed with @l0rd proposal

**Comment by sunix** [comment]
So 
`My Workspace` (instead of `Containers`)
- `User Runtimes` (instead of `Workspace`)
- `Plugins` (a new group)

**Comment by sleshchenko** [comment]
Just a question: What is User Runtimes and Plugins in Devfile perspective? `User Runtimes` are container related to components with types `kubernetes`/`openshift`/`dockerimage` and `Plugins` are containers related to `chePlugin`/`cheEditor` components?

**Comment by slemeur** [comment]
yes

**Comment by mmorhun** [comment]
Done
