### ISSUE TITLE
JWT proxy doesn't preserve request path when redirects to WS master for authentication 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12988]
### Description
JWT proxy doesn't preserve request path when redirects to WS master for authentication.
See an example from HAR archive of requests taken from https://github.com/eclipse/che/issues/12971:
https://gist.github.com/garagatyi/0fb187810cd1c0145ed93af0584d4ad8

Related issue: https://github.com/eclipse/che/issues/12575 which is also a bug in a redirection code

**Comment by garagatyi** [comment]
@skabashnyuk @mshaposhnik @sleshchenko FYI

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/issues/14189, please track it instead
