### ISSUE TITLE
Workspace failed to start because of plugins installation process failed

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#12999]
### Description
Some times workspace failed to start because of plugins installation process failed. This is especially true for CI jobs (on CI jobs error reproduces more often). 

### Reproduction Steps
 - Deploy Che by "minikube" and "chectl"
 - Go to "New Workspace" page
 - Select "Che 7" stack
 - Add java project
 - Enable "Java Language Server" plugin
 - Click on "Create and Open" button
 - Wait until workspace is started

**Expected behavior**
Workspace is started and all selected plugins are installed

**Observer behavior**
Workspace failed to start

**Attachments:**
*screenshot*
![terminal](https://user-images.githubusercontent.com/22724619/55142298-ef8afc80-5144-11e9-8d57-e76165b061cb.png)

*text from screenshot:*
```
Press F5 or click here to try again.
Starting Init Plugin Broker
Cleaning /plugins dir
Unified Che Plugin Broker
Starting Che common plugins processing
List of plugins and editors to install
- che-machine-exec-plugin:0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- org.eclipse.che.vscode-redhat.java:0.38.0 - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
- org.eclipse.che.editor.theia:1.0.0 - Eclipse Theia
Starting VS Code plugins processing
Downloading VS Code extension for plugin 'org.eclipse.che.vscode-redhat.java:0.38.0'
Starting Theia plugins processing
stream error: stream ID 1; HTTP_1_1_REQUIRED
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspacewirxn0fza1vyf9ey failed with error: stream error: stream ID 1; HTTP_1_1_REQUIRED"
```

*che server logs:*
[logs-from-che-in-che-655bbd79d4-kk4dd.txt](https://github.com/eclipse/che/files/3016917/logs-from-che-in-che-655bbd79d4-kk4dd.txt)

*theia ide logs:*
[logs-from-theia-ide-in-workspacezmwud1a6w61z12qb.ws-86dbd8b6c6-wntqd.txt](https://github.com/eclipse/che/files/3016919/logs-from-theia-ide-in-workspacezmwud1a6w61z12qb.ws-86dbd8b6c6-wntqd.txt)

*plugins sidecar logs:*
[logs-from-pluginsidecarpkqjxn-in-workspacezmwud1a6w61z12qb.ws-86dbd8b6c6-wntqd.txt](https://github.com/eclipse/che/files/3016924/logs-from-pluginsidecarpkqjxn-in-workspacezmwud1a6w61z12qb.ws-86dbd8b6c6-wntqd.txt)

**OS and version:**    
 - Che 7.0.0-beta-3.0 ;
 - minikube v0.28.0 ;
 - chectl 0.0.2 linux-x64 node-v10.4.1

**Comment by l0rd** [comment]
This doesn't look like a `team/languages` issue but more a `team/ide2' or `team/osio` issue because it involves brokering and Theia plugin loading. 

@tsmaeder @ibuziuk @evidolob can you help triaging this issue?

**Comment by ibuziuk** [comment]
Taken into next sprint by Che OSIO team - https://github.com/redhat-developer/rh-che/issues/1356

**Comment by ibuziuk** [comment]
@garagatyi maybe you have some ideas about that issue - `stream error: stream ID 1; HTTP_1_1_REQUIRED"` ?

**Comment by garagatyi** [comment]
Might be somehow related with rate limiting. It will be tricky to fix since there is no way to reproduce it as far as I understand. @Ohrimenko1988 Am I correct that you don't know how to reproduce it?

**Comment by Ohrimenko1988** [comment]
@garagatyi Yes, it is a random reproduced issue

**Comment by ibuziuk** [comment]
@Ohrimenko1988 @vkuznyetsov without a strong reproducer we can not do much atm ¯\_(ツ)_/¯

**Comment by Ohrimenko1988** [comment]
@ibuziuk Maybe I can help you with this? What additional information do you need? I may catch it on CI jobs.

**Comment by ibuziuk** [comment]
@Ohrimenko1988 well we need a strong reproducer in order to repro locally

**Comment by Ohrimenko1988** [comment]
Anyway, bug is still actual.

**Comment by ibuziuk** [comment]
@Ohrimenko1988 so, no steps to repro locally?

**Comment by Ohrimenko1988** [comment]
Unfortunately, no updates

**Comment by ibuziuk** [comment]
@Ohrimenko1988 is this issue still reproducible ?
