### ISSUE TITLE
VSCode-Java does not have Java File Icons

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12990]
When running the VSCode-Java Che 7 plugin, the icons for *.java files are not there, only an empty box is shown in the file navigator.
![FileIcons](https://user-images.githubusercontent.com/13163770/55067885-d587e600-5080-11e9-9b6a-40e6003c3805.png)

**Comment by benoitf** [comment]
hello @tsmaeder , what is your browser ? I see some recent comments about some pbs around icons and Firefox

**Comment by tsmaeder** [comment]
I have firefox. May be related.

**Comment by tsmaeder** [comment]
I just tried to look at this again: when opening the workspace, the icons were again missing. I then did a browser refresh and the missing file icons appeared. I still have the messages like those, in the console: 

```
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;base64,PHN2ZyBmaWxsPS… (“img-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;base64,PCEtLUNvcHlyaW… (“img-src”).
TypeError: n.rules is undefined[Learn More] theia.65e13b72d5b0983c28de.js:1:1882620
    setRules https://assets.openshift.net/che/theia_artifacts/theia.65e13b72d5b0983c28de.js:1
    onLoad https://assets.openshift.net/che/theia_artifacts/theia.65e13b72d5b0983c28de.js:1
    o https://assets.openshift.net/che/theia_artifacts/theia.65e13b72d5b0983c28de.js:1
    loadTimeout https://assets.openshift.net/che/theia_artifacts/theia.65e13b72d5b0983c28de.js:1
```
The presence of the messages when the icons are visible makes me think this is not related ot he other issue.

**Comment by benoitf** [comment]
you can check with `security.csp.enable=false`

**Comment by tsmaeder** [comment]
Retargeted to team/ide2 as this is likely to be a general problem.
