### ISSUE TITLE
How to pass config when starting a machine?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#130]
In 4.x, when creating a workspace, we can select an image like `UBUNTU_JDK8`.

Since in China, it's quite slow to visit maven repository sometimes, so I want to bind the local `~/.m2` directory to the docker containers to reuse them jars across multi containers.

But I can't find a way to add such config, how to do it?

**Comment by benoitf** [comment]
Hello,

you may as well use Maven china central repository http://maven.oschina.net/help.html

**Comment by ghost** [comment]
As to mounting a local Maven repo, we're thinking about it internally. Once(if) done, we'll publish instructions in docs.

**Comment by freewind** [comment]
@benoitf  thanks, that's one possible option. But not sure how to ask the project to use the oschina repository, do I need to create a custom image based on "ubuntu_jdk8"? Or just do some simple settings in somewhere?

**Comment by freewind** [comment]
@eivantsov Looking forward of that, thanks. I think these features are very important for countries which have bad internet conditions

**Comment by ghost** [comment]
Closing the issue. There are no immediate plans to implement this feature.

Snapshotting images seems like a workaround for you.
