### ISSUE TITLE
How can I open a new browser tab from Python in Eclipse Che?

### ISSUE THREAD

**Issue by tony-bony** [eclipse-che/che#13008]
Please see [my question on SO](https://stackoverflow.com/questions/54882713/how-can-i-open-a-new-browser-tab-from-python-in-eclipse-che).

I am trying to open a new browser tab from within a Python code. I was told it is possible but I don't know how.

I run my Python code in Eclipse Che by clicking the command GUI triangle at the top of the IDE.
When my code is running I am able to click a Preview URL and a new tab is opened. The point is I want to avoid the second step and have the new tab window opened automatically when running the command. 

I was told it is possible to create a command that can be run from Python but I am missing explanation how to do it? Can somebody help me with this?

**System info:**
```
Python version      :  2.7.15 (default, Oct  4 2018, 22:42:40) 
node.js version     :  v10.15.1
npm version         :  6.7.0
```

```
OS: Mac OS X Yosemite 10.10.5
Browser: Google Chrome 72.0.3626.121 (Official Build) (64-bit)
```

```
Docker: 18.03.0-ce, build 0520e24
docker-machine: 0.14.0, build 89b8332
```

```
eclipse/che: 6.18.1
eclipse/che-action: 6.18.1
eclipse/che-test: 6.18.1
eclipse/che-dir: 6.18.1
eclipse/che-server: 6.18.1
```

**Comment by vparfonov** [comment]
@tony-bony Hello, this is impossible at the moment, to open new tab user interaction is required

**Comment by tony-bony** [comment]
OK. Thanks

**Comment by Divine1** [comment]
@vparfonov  how to open a open a new tab using user interaction?



on running the selenium script in laptop, a google chrome browser will open up and i will be able to view the scripts getting executed in the browser.

my eclipse che workspace will have a selenium script. on running the selenium script i expect container of google chrome browser to spawn up (its ok if user confirmation clicks are required)
