### ISSUE TITLE
wsagent doesn't exist (Che 7.0.0-beta-2.0)

### ISSUE THREAD

**Issue by ellalonge** [eclipse-che/che#13002]
### Description
Unable to open any workspaces or see any editors.
Provides the issue of: `com.google.web.bindery.event.shared.UmbrellaException: Exception caught: wsagent doesn't exist`

### Reproduction Steps
Try to create any workspace or run any existing workspaces with an editor plugin enabled

**OS and version:**    
Ubuntu 18.04.2
Docker 18.09.2 (API 1.39)
Che 7.0.0-beta-2.0

I am using Multi-user and single port

**Comment by eivantsov** [comment]
@gtesblue sorry for a delayed response. Che 7 drops Docker support, so you cannot create Che 7 workspaces (with plugins enabled).

**Comment by gtesblue** [comment]
How do I create/ugprade a workspace then?

**Comment by eivantsov** [comment]
You need to disable plugins/editors, and enable workspace api in Installers

**Comment by lamgibrcom** [comment]
Hi @eivantsov 
I'm facing the same problem running Che 7.0.0-RC-1.0.
I'm not able to start any Che7 (with Theia) workspaces provided ooo on the section "new Workspace", they fails with the same error or a generic message "Workspace Stopped".
Could you clarify better what's the reasons is and how to fix it?

**Comment by ivucica** [comment]
@ghost Can you clarify https://github.com/eclipse/che/issues/13002#issuecomment-479546434? Does this mean pure Docker is no longer supported, even if `eclipse/che-cli:7.0.0-RC-2.0` is willing to spin up containers based off of the `eclipse/che-server:7.0.0-RC-2.0`, `centos/postgres-96-centos7:9.6`, `jboss/keycloak-openshift:3.4.3.Final` images? And despite the possibility to have factories etc still create docker-based containers? I have containers `ivucica_dev-machine` and `ivucica_theia` created for me after randomly clicking around the UI.

And what about https://github.com/eclipse/che/issues/13002#issuecomment-479775043 ? I'm doing everything in GUI and I upgraded from an older Che. I'm not sure where to 'disable plugins/editors', where 'Installers' is (it doesn't appear anywhere in the UI for me) or how to enable the 'workspace API'.

This is going to run on exactly one machine in multiuser mode, but primarily with just one user (me). Do I need to nuke everything including Keycloak and start from scratch using Minikube?

I got Codenvy to work in the past, but I never got Che to work; mostly the workspaces simply didn't boot up, but now? Now I can't even get them created, or if I can, I get `wsagent doesn't exist`.

It would be really awesome to have one specific, supported set of instructions for 7.0.0 on how to go from a blank machine to 'you can log in with a Keycloak-managed account'. :-)

**Comment by NealBozeman** [comment]
@ivucica, here is what I've come to understand.

The former quickstart which previously relied on docker no longer works. The old docker commands will spin up the containers with the Che 7 images, but nothing will work, and you'll experience the behavior you are seeing. 

Per the [Che 7 Quickstart](https://www.eclipse.org/che/docs/che-7/che-quick-starts.html), Che 7 requires either
- a K8s environment, such as through minikube, or
- an OpenShift environment, such as through minishift.

You must also install `chectl` (instructions in the quickstart), and manage Che 7 through that. Do not use the previous docker commands that allowed you to manage Che 6. 

Regarding your old configurations: Workspaces no longer have installers, and instead use Plugins and Editors. If you want to use the new format, you need to remove the JSON attribute "Installers" from the workspace "config" tab. The functionality previously done through installers is now loaded as a sidecar container. This is actually pretty slick.

Not sure about your keycloak, if you can keep it or not. Good luck!

**Comment by ivucica** [comment]
Thanks! I'll give it a go and see what I can do. Thankfully I never got
Che6 working before, so completely giving up and starting from scratch with
Che7 is actually an option.

Also gives me an excuse to try setting up a Kubernetes environment again. :)
