### ISSUE TITLE
Quemu 80% CPU with Idle Che

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13000]
When I start Che on minishift, have two workspaces, but none of them running, I notice that my laptop fan is running: top outputs:

5570 qemu      20   0   10.8g  10.0g  21292 S  81.1  32.2 478:55.97 qemu-system-x86 

I have no VM's running except minishift. My expectation is that and idle minishift/Che consumes almost no CPU.

**Comment by garagatyi** [comment]
I have experienced something like this, but not sure whether it was openshift in minishift or on docker.
Another problem is that sometimes Che browser tab make huge load on the system when workspace is idled. 
@tsmaeder had you had Che browser tab opened when you experienced that? Was it on the Theia view? Was the workspace idled?

**Comment by tsmaeder** [comment]
I had the browser tab open in Firefox, but closing the Browser tab and waiting a couple of minutes does not reduce the load produced by "qemu".

**Comment by amisevsk** [comment]
I've also noticed this on occasion (but not always), as well as the extreme memory usage from the browser when workspaces are idled or che is restarted (it's hard to reproduce consistently).
