### ISSUE TITLE
Folder `/projects/?` is created when starting JDT LS in a sidecar on minishift

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13012]
### Description

![image](https://user-images.githubusercontent.com/606959/55167488-5f16e100-5171-11e9-8857-2e84cfcbccb6.png)

```shell
$ ls -la /projects/
total 0
drwxrwx---. 4 root       root  42 Mar 28 01:42 .
drwxr-xr-x. 1 root       root  67 Mar 28 01:42 ..
drwxr-xr-x. 4 1000150000 root  33 Mar 28 01:42 ?
drwxr-xr-x. 7 1000150000 root 174 Mar 28 01:45 console-java-simple
```

That may be a side-effect of running as an arbitrary user (no entry in `/etc/passwd/`) in image `theia-endpoint-runtime` and a possible fix would be to patch file `/etc/passwd` at startup as we do for image [che-theia](https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/src/entrypoint.sh#L17)

### Reproduction Steps

- Deploy Che on minishift
- Start a workspace using a Che 7 stack with the Java LS plugin

**Comment by benoitf** [comment]
should be fixed by https://github.com/eclipse/che-theia/pull/147

**Comment by garagatyi** [comment]
I recall us considering injecting Theia plugin runner inside any plugin runtime container. Would we be able to handle situations with /projects in that case?

**Comment by l0rd** [comment]
I have verified. Fixed.

@garagatyi not sure I understand your question
