### ISSUE TITLE
K8S:coordination

### ISSUE THREAD

**Issue by Hailongli88** [eclipse-che/che#13027]
Checked it works on K8S:
1. JGroups set connection between pods:
![kubernetes_jgroups](https://user-images.githubusercontent.com/1651062/37029010-936d17b2-213e-11e8-877a-bddae1c05d8a.png)
2. Cache propagation :
https://drive.google.com/file/d/1aXkfi7LxR0pkYsQhOson6OaCguri_-w6/view?usp=sharing

_Originally posted by @mshaposhnik in https://github.com/eclipse/che/pull/8982#issuecomment-370745501_

**Comment by eivantsov** [comment]
@Hailongli88 thanks for posting video, however, I have hard time understanding what your question is. It looks like you want to submit a bug report or think that the behavior you see is now the behavior you expect?

**Comment by Hailongli88** [comment]
@eivantsov I just think this record is useful.I will close it.
