### ISSUE TITLE
deprecate "che.workspace.default_memory_limit_mb" property

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13024]
### Description
According to the code comment che.workspace.default_memory_limit_mb is overriden by che.workspace.default_memory_request_mb

see:
https://github.com/eclipse/che/blob/26f21ebe2f2fdfef7002549d7b1998234b4107c1/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L101
and:
https://github.com/eclipse/che/blob/26f21ebe2f2fdfef7002549d7b1998234b4107c1/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L113-L119

We should simplify and remove the che.workspace.default_memory_limit_mb

**Comment by skabashnyuk** [comment]
CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB  CHE_WORKSPACE_DEFAULT__MEMORY__REQUEST__MB
Limit and request basically two different things for container
Requests and limits are the mechanisms Kubernetes uses to control resources such as CPU and memory. Requests are what the container is guaranteed to get. If a container requests a resource, Kubernetes will only schedule it on a node that can give it that resource. Limits, on the other hand, make sure a container never goes above a certain value. The container is only allowed to go up to the limit, and then it is restricted.
The limit can never be lower than the request. If you try this, Kubernetes will throw an error and won’t let you run the container.

**Comment by amisevsk** [comment]
To add to this after the fact, the limit is required in rh-che as the cluster we're deploying to denies pods without a limit and sets its own request.
