### ISSUE TITLE
Workspace loader does not react on STOPPED event if an error is absent

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13042]
### Description
Workspace loader does not react on a STOPPED event if an error is absent.

### Reproduction Steps
1. Rebuild your Che Assembly where NPE will happen on runtime start phase.
2. Try to start a workspace.
Actual: Workspace loader is displaying progress bar forever.
Expected: Workspace loader tells a user that workspace is failed to start.
![Screenshot_20190402_122217](https://user-images.githubusercontent.com/5887312/55392073-36149880-5543-11e9-8e23-d3129eba1372.png)
![Screenshot_20190402_122241](https://user-images.githubusercontent.com/5887312/55392076-37de5c00-5543-11e9-9f91-ab11d8ae26ff.png)

**Comment by sleshchenko** [comment]
The following PR should prevent sending event without message[1] but still Workspace Loader should be improved 
[1] https://github.com/eclipse/che/pull/13043

**Comment by AndrienkoAleksandr** [comment]
Done.
