### ISSUE TITLE
[Kubernetes/Multi-user] Unable to log in to Che with an account with no email associated with it

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#13050]
### Description
I've got multi-user Eclipse Che (latest) set up on IBM Cloud Private (ICP) 3.1.2 using ICP's OIDC provider (Open Liberty-based) with two users configured on the cluster:
1. `admin`
2. `<email>@ibm.com`

Both users have the exact same roles on the cluster. The second user is configured via an LDAP server and has an email (also `<email>@ibm.com`) associated with it.

I can log in to Che and access the dashboard just fine if I use the `<email>@ibm.com` user. But if I login with the `admin` user, I get the following error in the UI:

```
Unable to authenticate user because email address is not set in keycloak profile
Click here to reload page.
```

I've found some references in Che's code and on Github (such as https://github.com/eclipse/che/pull/11090) indicating that an email is expected to be associated with the account you login with. 

Are accounts without emails supported in Che? If not, is it something worth adding support for?

**Comment by eivantsov** [comment]
@skabashnyuk @mshaposhnik perhaps you can help? Is it solely Keycloak thing or we expect email in Keycloak profile?

**Comment by johnmcollier** [comment]
@mshaposhnik Ah, okay. If that's the case, then we can close this issue.
