### ISSUE TITLE
Create a CI job that builds che-operator docker image

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#13059]
## Description

There's a need for a CI job that will:

1. Build a Docker image eclipse/che-operator:$tag from https://github.com/eclipse/che-operator
2. Push it to DockerHub

`$tag` is a GitHub tag.

Temporarily, the first tag should not be tagged as latest.

A CI job should be triggered when a new tag is created in https://github.com/eclipse/che-operator (TODO: create a ticket to get a webhook). Since it's not possible at the moment, it should be possible to trigger a job manually, with tag as param.

**Comment by benoitf** [comment]
it can't be done by dockerhub ?

**Comment by eivantsov** [comment]
@benoitf are you doing it for Theia images? 

AFAIK, we cannot setup automated builds for eclipse repos after certain changes in DockerHub

**Comment by benoitf** [comment]
@eivantsov it was done on some wskeleton images and adding a hooks/post_push files in the repository to provide the custom tags

https://github.com/ws-skeleton/che-fortune-plugin/blob/master/hooks/post_push

**Comment by eivantsov** [comment]
Asking Eclipse webmaster to establish webhoocks and set things up on DockerHub side can take time. Besides, it's better to be in control of such a CI when changes are required.
