### ISSUE TITLE
Change default theme

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#13066]
### Description
Hi,

I would like to change the default theme from dark to light. I have made this changes in ThemeAgentImpl class, I have deleted CHE's data folder but the default theme keeps the same (dark)

I have changed this:
```
  @Inject
  public ThemeAgentImpl(Darktheme theme) {
    defaultTheme = theme;
    themes = new HashMap<>();
  }
```

To this:
```
  @Inject
  public ThemeAgentImpl(LightTheme theme) {
    defaultTheme = theme;
    themes = new HashMap<>();
  }
```

Could you help me please?

Thanks

**Comment by amisevsk** [comment]
Do you mean you want an entirely new theme, or just to use a light variant of the default? Both Theia and GWT-based workspaces support this out of the box via preferences:

- In Theia, you can go to `File > Settings > Change Color theme` and select light
- In the GWT-based editor, you can go to `Profile > Preferences > IDE > General` and there is a theme dropdown (refreshing may be required)

**Comment by mstavares** [comment]
Hi @amisevsk thanks for your reply,

Yes, I want to use the light variant by default and I'm using GWT-based editor.

> In the GWT-based editor, you can go to Profile > Preferences > IDE > General and there is a theme dropdown (refreshing may be required)

I'm generating a binary with a eclipse che docker image, so your solution won't fit in my case. I would like to know I can I set it by default on eclipse che's source code as I asked.
I was expecting that changing the defaultTheme variable from DarkTheme to LightTheme have the behavior that I was expecting, but the dark theme stills there by default.

Thanks,

**Comment by mstavares** [comment]
Hi,

I have testes in another browser and seems working. Maybe is related with caching.

Thanks.
