### ISSUE TITLE
Mounting docker in workspace problem Che-6.19.0

### ISSUE THREAD

**Issue by 781227k** [eclipse-che/che#13063]
I would like to use  docker functionality within the workspace, I've follwed your documentation [here](https://www.eclipse.org/che/docs/che-6/docker-config.html#accessing-logs-and-user-data) 

Basically che.env file should be updated with values below;
```
CHE_DOCKER_PRIVILEGED=true;
CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock; 
```

### Reproduction Steps

First I have tried to update the variable during the run of che image as following but che.env was not not updated..

```
docker run -it -e CHE_MULTIUSER=true -e CHE_DOCKER_PRIVILEGED=true 
-e CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock CHE_HOST=${EXTERNAL_IP} -v /var/run/docker.sock:/var/run/docker.sock 
-v ~/.che-multiuser:/data eclipse/che start
```

Then i have updated che.env manually and restart it from the command line.

However /var/run/docker.sock does not exist. 

Is this a bug or am i missing something, I would appreciate if you could take a look.

**Comment by eivantsov** [comment]
@781227k did you start a workspace after that? This env is about mounting files/dirs into workspace containers.

**Comment by fErten** [comment]
@eivantsov Yes, I start a new workspace after that but `/var/run/docker.sock does` not exist. And as far as know `-e CHE_ENV_NAME=value` should update the value automatically during the docker run, why do you think it has not been updated.

**Comment by 781227k** [comment]
@eivantsov  Yes I have created a new workspace but volume  `var/run/docker.sock` doesn't exist. And why do you think during the docker run passing -e` CHE_ENV_VALUE=value ` did not updated the che.env automatically.

**Comment by eivantsov** [comment]
The CLI should pick it up. Try editing che.env directly and restarting Che.

**Comment by 781227k** [comment]
Unfortunately no luck with that, restart does not solve the problem, I also tried other cli commands like init, config..

**Comment by 781227k** [comment]
@eivantsov can you reproduce the issue?
