### ISSUE TITLE
Add an ability to use Devfile as workspace configuration as alternative to WorkspaceConfig

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13079]
### Description
We need to be able
- Create workspace from Devfile
- Update Devfile in the existed workspace (devfile based only)
- Get Devfile from existed workspace (devfile based only)
 - Start Workspace that is configured with Devfile but not WorkspaceConfig

Also, we need.
- Keep the ability to create/edit/run Che6/GWT IDE based workspaces where WorkspaceConfig is used

**Comment by sleshchenko** [comment]
Now Che Server is able to handle the described scenario. There are separated issues for different parts of UI:
Dashboard: #13198
WorkspaceLoader #13201
Theia #13112
