### ISSUE TITLE
Please, share settings.xml for maven build

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-che/che#13088]
### Description

Please, share settings.xml used for maven build.

When I try to build eclipse che on my machine some non-desired maven plugins are invoked. Invocation of these plugins causes some issues and non-desired side effects, like special code format checks and changes. Settings.xml used on my computer which was installed centrally contains huge amount of redundant elements. I would like to run clean maven build.
It will help me greatly if you provide the correct goals and profiles used for maven build configuration.   
### Reproduction Steps

- 1. Create Maven build configuration in eclipse
- 2. Run Maven Build Configuration
Expected:Build according desired parameters compatible with docker packaging 

 Actual:
Error and warning messages unrelated to the build purposes,
Attempts to install eclipse/che on non-existing local infrastructure missed in company OS image, 
Unpredictable Eclipse behavior, 
Missed integration with existing company CI. 
etc. 
are very helpful. -->

**OS and version:**    
Windows 10, Eclipse oxygen
**Diagnostics:** 

Our company maven plugins repository contains altered of of plugins

**Comment by skabashnyuk** [comment]
Hello @PavelSosin 
Can you elaborate a bit more about:

>When I try to build eclipse che on my machine some non-desired maven plugins are invoked. Invocation of these plugins causes some issues and non-desired side effects, like special code format checks and changes.

Do you have some traces to share?

**Comment by nickboldt** [comment]
No feedback from reporter after more than 3 months, so closing. This sounds like an Eclipse Oxygen IDE issue, not Eclipse Che. 

If still a problem with Che 7, please open a new issue with more details.
