### ISSUE TITLE
Devfile should not prefix all the plugin runtime names with a user runtime name.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13095]
### Description
When using devfile to start a workspace, it is naming the plugin pods with one of the user runtime. This could be ok for some use cases but not for all use cases having that plugins may not be related to the user application.

### Reproduction Steps
Create a devfile from https://github.com/sunix/devfiles/blob/6f59533d7912a1d274b921d7b24867413eedfcb7/che-in-che/che-theia.devfile.yaml

Once the workspace is started, open the container view in che theia and expand the plugins folder. We can see that `git` (name of one of the user runtime) is prefixing all the plugin runtimes names.

![Selection_210](https://user-images.githubusercontent.com/650571/55780113-7c1fae00-5aa7-11e9-9fc6-f983b2d7758f.png)

**OS and version:**    
che7 with minikube started with chectl. single user mode.

**Diagnostics:**

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/13214
