### ISSUE TITLE
Eclipse che on TLS in OCP 

### ISSUE THREAD

**Issue by maskevikas** [eclipse-che/che#13091]
### Description
Trying to deploy Eclipse Che on OCP with Below command. But Che container is not coming UP. (TLS Support is not working. without "--secure" parameter is working absolutely Fine )

### Reproduction Steps
curl -fsSL https://raw.githubusercontent.com/eclipse/che/master/deploy/openshift/deploy_che.sh -o deploy_che.sh
 sh -x deploy_che.sh --multiuser -s -p=che

NAME               READY     STATUS        RESTARTS   AGE
che-2-2x64w        0/1       Terminating   1          13m
che-2-deploy       0/1       Error         0          13m
keycloak-1-xfs76   1/1       Running       0          15m
postgres-1-b8k7w   1/1       Running       0          17m

**OS and version:**    

Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Diagnostics:**

**Comment by amisevsk** [comment]
Looks like the deploy pod is failing -- could you get error logs from the pods?

**Comment by eivantsov** [comment]
@maskevikas is your OCP router configured with certificate signed by a public authority?

**Comment by maskevikas** [comment]
Yes. It's deployed with public authority certificate

**Comment by eivantsov** [comment]
Having Che logs will help
