### ISSUE TITLE
How can IDE  get JWT token for accessing che-host:8080/api under Multiuser/Multihost environtment? 

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13099]
I'm trying to run GWT-IDE with JWT-proxy under Multiuser/Multihost Che environment.
Already my web browser downloaded `https://serverxbz9mg3q-jwtproxy-server-4402.domain/_app/_app-0.js` and related files.

But it is failed with 401 error when it calls `https://serverxbz9mg3q-jwtproxy-server-4402.domain/api/project-template/all`.
It's an unexpected behavior for me but I see it is reasonable because the IDE have no bearer token generated by Keycloak.

So the question.
How can the IDE call `/api` endpoints from the IDE iframe under JWT-proxy environments?

One of the easiest way is to get Keycloak tokens from parent window. But this way was rejected by [the comment](https://github.com/eclipse/che/pull/13026#issuecomment-478455583). And I agree it should be avoided.

**Comment by skabashnyuk** [comment]
That is a good question @monaka . At this moment afaik we don't have a way to do that. I would start with https://istio.io/docs/concepts/security/ maybe they have some ideas/instruments/ to do that.

**Comment by sleshchenko** [comment]
@monaka I think that `ProjectTemplateService` have no sensitive information (at least for now), so I see the following ways to make `/api/project-template` available for sidecars:
1. Add an exception for this service here https://github.com/eclipse/che/blob/534a961e844049d5b4b84dd694176175eb367c97/multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakServletModule.java#L29.  Then this method will be available without any token.
2. Add methods of this service to `MachineAuthenticatedResource`. See https://github.com/eclipse/che/blob/e2991cd050dcd85625ac5393345685c6b6dae75b/multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java#L59-L67. It will make this service available with machine token only.

Note that the listed suggestion suit only this particular case and may be not relevant for other services that may be needed for GWT IDE, like update user preferences.

**Comment by monaka** [comment]
@skabashnyuk @sleshchenko Thanks for good hints. I'll consider the way to call APIs with machine token.
