### ISSUE TITLE
Git import style urls git://git@host:example.git

### ISSUE THREAD

**Issue by cucumobile** [eclipse-che/che#1309]
Hi, How clone or import from url style git://user@example.git without
pair key and without change at server? i.e git clone git
://git.kernel.org/pub/scm/git/git.git. 

Thanks

**Comment by ddementieva** [comment]
It's necessary to generate SSH key to be able to clone a repo using SSH URL. You can easily do that using `Profile > Preferences > Git > Generate Key` option.

If you have a public repository, you can clone it with HTTPS URL instead.

**Comment by cucumobile** [comment]
Hi,
1. Yes, I know the steps. The problem is that it can not perform
   imports on sites url only style 'git: //_@_.git' without the
   possibility https. EclipseChe 4.3 beta.
2. Upload my key pair or generate a Che Have new pair for each
   workspace-server. But I can not synchronize or import. Is there any
   type of especial user_anonymus ,credential or general user che?

i.e. $ cat ~/.ssh/id_rsa.pub
ssh-rsa
AAAAB3NzaC1yc2EAAAABIwAAAQEAklOUpkDHrfHY17SbrmTIpNLTGK9Tjom/BWDSU
GPl+nafzlHDTYW7hdI4yZ5ew18JH4JW9jbhUFrviQzM7xlELEVf4h9lFX5QVkbPppSwg0cd
a3Pbv7kOdJ/MTyBlWXFCR+HAo3FXRitBqxiX1nKhXpHAZsMciLq8V6RjsNAQwdsdMFvSlVK/7
XAt3FaoJoAsncM1Q9x5+3V0Ww68/eIFmb1zuUFljQJKprrX88XypNDvjYNby6vw/Pb0rwert/
EnmZ+AW4OZPnTPI89ZPmVMLuayrD2cE86Z/il8b+gw3r3+1nKatmIkjn2so1d01QraTlMqVSs
bxNrRFi9wrf+M7Q== browser@mylaptop.local

**Comment by ghost** [comment]
@cucumobile not sure I understand the problem now. You can generate one key which is saved to user prefs, and save public part of that key to your git hosting account settings.

As to format of the URl `git://user@example.git` isn't accepted indeed. I'll have someone from the dev team take a look.

**Comment by cucumobile** [comment]
This question is solved in 4.5.0-RC1-SNAPSHOT.  For gitolite user add the hostname in profile and import whit git@example.com:project.git whitout protocol.
1.- Profile > SSH > VCS > generate key  
2.- Add hostname server "example.com" and push key to gitolite server
3.- Refresh
4.- Workspace > Import Project > GIT > URL: git@example.com:project.git
5.- Import
