### ISSUE TITLE
Multi-user Opeshift 3.11. Not able to load workspace in iframe

### ISSUE THREAD

**Issue by jdcano-bpe** [eclipse-che/che#13090]
### Description

Hello all, 

I deployed Eclipse CHE using the official deployment script for multi-users and all was fine. The creation and configuration of a workspace is working fine as well.

The problem comes when I try to access to a workspace.
 I have been searching solutions for this error but I didn't find any solution. I have two different errors when I try to access to the the workspace (Theia IDE) from the dashboard, the errors are:

- `Access to XMLHttpRequest at 'https://api.npms.io/v2/search?q=keywords:theia-extension&size=50' from origin 'http://che-eclipse-che-multiuser.mydomain.ch' has been blocked by CORS policy: Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

- `Refused to display 'http://routeek2q4tqd-eclipse-che-multiuser.mydomain.ch/?uid=321146' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`
![eclipse-che_1](https://user-images.githubusercontent.com/49392580/55715144-6604e580-59f4-11e9-8e15-b8b473f0ca9b.png)
![eclipse-che_2](https://user-images.githubusercontent.com/49392580/55715160-73ba6b00-59f4-11e9-86bc-4728e4fe68ca.png)

Following the instructions and Eclipse CHE documentation, I disabled the CORS using environment variables, which are the following:

- CHE_CORS_ENABLED=false
- CHE_CORS_ALLOW__CREDENTIALS=false
- CHE_CORS_ALLOWED__ORIGINS=false
- CHE_WSAGENT_CORS_ENABLED=false
- CHE_WSAGENT_CORS_ALLOWED__ORIGINS=false
- CHE_WSAGENT_CORS_ALLOW__CREDENTIALS=false

![eclipse-che_3](https://user-images.githubusercontent.com/49392580/55715176-7917b580-59f4-11e9-8a77-37e354eb5e85.png)

The documentation I followed were:

- https://che.eclipse.org/eclipse-che-6-15-6-16-and-6-17-release-notes-362cff44dcc9
- https://www.eclipse.org/che/docs/che-6/openshift-multi-user.html
- https://www.eclipse.org/che/docs/che-6/che-6cors.html

But still can not access directly to the Theia within an iframe from the dashboard.

### Reproduction Steps

1. Install Eclipse-che multiuser in Openshift using the provided script and documentation.
2. Create a new workspace and configure it.
  - Go to the section **Workspaces** and click on **Add Workspace**
  - Create a Muti - Machine Java Theia workspace (Che development + Theia (openshift)), but it could be any other. 
  - Configure the workspace to use GIT, add environment variables to access properly to our GIT instance and add the URL to access to our che-plugin-registry. My configuration file for this workspace could be something as follow: 
```json
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "ws/machine-exec": {
          "attributes": {
            "memoryLimitBytes": "536870912"
          },
          "servers": {
            "machine-exec": {
              "attributes": {
                "type": "terminal"
              },
              "port": "4444",
              "protocol": "ws"
            }
          },
          "volumes": {},
          "installers": [],
          "env": {
            "GIT_SSL_NO_VERIFY": "true"
          }
        },
        "ws/theia": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {
            "theia": {
              "attributes": {
                "cookiesAuthEnabled": "true",
                "type": "ide",
                "secure": "true"
              },
              "port": "3100",
              "path": "/",
              "protocol": "http"
            },
            "theia-dev": {
              "attributes": {
                "type": "ide-dev"
              },
              "port": "3130",
              "protocol": "http"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {
            "HOSTED_PLUGIN_HOSTNAME": "0.0.0.0",
            "GIT_SSL_NO_VERIFY": "true"
          }
        },
        "ws/dev": {
          "attributes": {
            "memoryLimitBytes": "1610612736"
          },
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {
            "GIT_SSL_NO_VERIFY": "true"
          }
        }
      },
      "recipe": {
        "type": "openshift",
        "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: 'eclipse/che-theia:next'\n     name: theia\n     resources:\n      limits:\n       memory: 1024Mi\n    - \n     image: 'eclipse/che-dev:nightly'\n     name: dev\n     resources:\n      limits:\n       memory: 1536Mi\n    - \n     image: 'wsskeleton/che-machine-exec:latest'\n     name: machine-exec\n     resources:\n      limits:\n       memory: 512Mi\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [
    {
      "links": [],
      "name": "myproject",
      "attributes": {},
      "source": {
        "location": "https://bitbucket.mydomain.ch/scm/wor/myproject.git",
        "type": "git",
        "parameters": {}
      },
      "path": "/myproject",
      "description": "",
      "mixins": [],
      "problems": []
    }
  ],
  "name": "wksp-5q3j",
  "attributes": {},
  "commands": [],
  "links": []
}
```
  - Run the workspace and wait until is up.
3. Try to access to the workspace.
4. The access to the workspace is blocked due to CORS and iframe.

**OS and version:**    
I have tried with many Eclipse CHE versions but I have the same behavior in all of them:

- Eclipse CHE: 
  - 7.0.0-beta-2.0-SNAPSHOT
  - 6.19.2
  - 6.19.1
- Openshift 3.11
- OS: Red Hat 7.6
- Docker 1.13.1
- Docker images:
  - eclipse/che-server:nightly
  - eclipse/che-plugin-registry:latest
  - eclipse/che-keycloak:nightly
  - eclipse/che-postgres:nightly
- Browsers:
  - Google Chrome 70.0.3538.102
  - Mozilla Firefox 66.0.2
  - Internet Explorer 11.05 (NOT WORKING AT ALL)
**Diagnostics:** 
In the Eclipse-Che there are no logs regarding this error, but the console shows the following:

- `Access to XMLHttpRequest at 'https://api.npms.io/v2/search?q=keywords:theia-extension&size=50' from origin 'http://che-eclipse-che-multiuser.mydomain.ch' has been blocked by CORS policy: Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

- `Refused to display 'http://routeek2q4tqd-eclipse-che-multiuser.mydomain.ch/?uid=321146' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

I have solved this issue before with different options in Apache and Spring Boot applications adding headers, but I would like to use environment variables and create if needed a proper solution for this that is included in the Docker images of the project.

Thanks a lot in advance for your help.

Best regards, 
Daniel

**Comment by skabashnyuk** [comment]
Hello @jdcano-bpe thank you for this report.

Can you specify more information about this step?
>2. Create a new workspace and configure it.

**Comment by jdcano-bpe** [comment]
> Hello @jdcano-bpe thank you for this report.
> 
> Can you specify more information about this step?
> 
> > 1. Create a new workspace and configure it.

Hello @skabashnyuk , 

Thanks for your quick answer. I just update the description of the issue. If you need more information, just let me know.

Thanks again.

**Comment by jdcano-bpe** [comment]
Hello,

The problem was not related with Eclipse-CHE, our security team was including the header x-frame-options=SAMEORIGIN in every request and that was blocking the access to the workspace. 

Sorry for the noise.

Thanks a lot.
