### ISSUE TITLE
How to create a html+js project in 4.x

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#131]
With the built-in "ubuntu_jdk8" or "debian_jdk8", I can create Java projects successfully. But how can I create a normal html+js project?

I can create a blank project and create some html/js files, but not sure how to run the machine to give me a url to visit. 

I also tried to create a new workspace based on `FROM codenvy/javascript_html`, but I can't create any project in this workspace, there is no template, and the "Create" button is always disabled:

![image](https://cloud.githubusercontent.com/assets/333781/11898123/87229bbc-a5d0-11e5-92e1-924d062380e9.png)

---

Along with this question, I also want to know how to create a nodejs project

**Comment by TylerJewell** [comment]
The machine is already running for you.  We just do not simplify making it easy to find the hostname.  The io address for the machine you are running is in the machine perspective under the servers tab.  Switch perspectives on the upper right corner.
We will provide docs and examples for different project types like node in the upcoming beta.

-Tyler

On Fri, Dec 18, 2015 at 5:44 AM -0800, "freewind" notifications@github.com wrote:

With the built-in "ubuntu_jdk8" or "debian_jdk8", I can create Java projects successfully. But how can I create a normal html+js project?

I can create a blank project and create some html/js files, but not sure how to run the machine to give me a url to visit. 

I also tried to create a new workspace based on FROM codenvy/javascript_html, but I can't create any project in this workspace, there is no template, and the "Create" button is always disabled:

[Uploading image.png…]()

Beside the question, I also want to know how to create a nodejs project

**Comment by ghost** [comment]
Try FROM codenvy/php - there's Apache sever running in there. In this image, document root is pointed to /projects, which is where all the projects reside inside the container.

The navigate to servers tab, find the port 80 port is mapped to. You will see a directory of projects. Pick yours, and if there's index.html, you will see it.

We're in the process of documenting this and creating new non-java environments.

**Comment by ghost** [comment]
For node.js you may use:

FROM codenvy/node

**Comment by freewind** [comment]
@TylerJewell  If I understand you correctly, you mean there is a tomcat running which can be the "server" of any html or js files?

I just tried and have a new issue there: https://github.com/codenvy/che/issues/132

**Comment by freewind** [comment]
@eivantsov Thanks for the suggestion, I just created a new workspace based on `codenvy/node`, seems like it installed `nodejs` and many npm libraries.

I just want to confirm:  there is no started http server there, so based on this image, what I can do it running some node commands from the "terminal" tab manually, right?

**Comment by freewind** [comment]
@eivantsov `codenvy/php` is good for the work, the only issue is it doesn't expose the `80` port by default, so we need to do it manually when creating a `recipe`:

```
FROM codenvy/php
EXPOSE 80
```

**Comment by ghost** [comment]
Yeah, it's still 'under construction'. Updated the Dockerfile.

**Comment by freewind** [comment]
@eivantsov  :+1:
