### ISSUE TITLE
Add `libx11-dev`  and `libxkbfile-dev` libs for che-theia CI

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13116]
### Description
This [pull](https://github.com/theia-ide/theia/pull/4724) was merged in Theia upstream,
now Theia use [native-keymap](https://www.npmjs.com/package/native-keymap) which requires `libx11-dev libxkbfile-dev` on Debian based or `libx11-devel.x86_64 libxkbfile-devel.x86_64` on Red Hat-based Linux.
Without that libraries CI cannot build `che-theia` and we are blocked
### Reproduction Steps
See https://ci.codenvycorp.com/job/che-theia-pullrequests-build/127/ build log

**OS and version:**    

**Diagnostics:**

**Comment by riuvshin** [comment]
done.
