### ISSUE TITLE
Prepare yaml file for deploying test application (Nodejs+MongoDb) based on Kubernetes/Openshift infra

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13119]
### Description
According to 2.1 of [HappyPath](https://hackmd.io/s/BkVyU6crN) testing we should prepare[NodeJs   real world app.](https://github.com/gothinkster/node-express-realworld-example-app)., which can be deployed on openshift/kubernetes infra with chectl tool.

**Comment by l0rd** [comment]
Closing. We will use [petclinic_k8s.yaml file from our devfile](https://github.com/che-incubator/che-demos/blob/cfd39ea48798094ae4c6d5472f499df3570432b6/devfile/deploy_k8s.yaml) repository.
