### ISSUE TITLE
running che multi user in docker on subdomain

### ISSUE THREAD

**Issue by electron2302** [eclipse-che/che#13113]
### Description
I am trying to run a multi user version of che under my subdomain, using Docker.
The Problem is that i am running Traefik as my reverse proxy, witch gets the port 443 from the outside, and i would like know to start Che in such a way that it uses che.my.domain
I already found the single part feature, in another Issue, but i still haven't figured out how i should start che, so that it serves the content over http on a random (not 80 or 443) port but that i will be called by a https domain and not lokaly

### Reproduction Steps
Start a standalone Docker container of traffic and make it your entry point for HTTP and https and set it up your SSL encryption and http to https redirect. Then try to start che multiuser so that it is available on a subdomain.

**OS and version:**    
Docker version 17.05.0-ce

### The wish
Of Course it would be wonderful if someone could give me the start command with which everything would work but I would also be very grateful if I could be redirected to better / more detailed docs than the normal docs that don't have nearly every feature (like the singleport) explaint in it

**Comment by electron2302** [comment]
I am somehow unable to add labels :(
I would like to add the labels 'kind/question' & 'help wanted'

**Comment by sunix** [comment]
Hello, we won't be supporting Docker anymore in the new version of Che (only Kubernetes/Openshift infra).
I am closing it but feel free to reopen it if you feel it should.

**Comment by omdeshpande** [comment]
Why isn't Docker supported by Che 7?
