### ISSUE TITLE
Investigating new typescript related test framework

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13114]
### Description
We have implemented typescript related framework "Cypress". But using this framework faced us with problems:
 - It's hard to consume upstream tests in downstream
 - Memory problems
 - Hard conditional testing
 - No support for multiple tabs
 - Ignoring community
 - Lack of flexibility
 - Nightmare with async calls and rejecting all "canonical" ways to handle it
 - Unexpected browser hold
 - No "iframe" support

So we should find more reliable solutions, for example "Protractor", bare "Selenium" + "Jasmine" or something else.

DoD:
New solution core implemented and "Cypress" code base moved to it.

**Comment by rhopp** [comment]
@ljelinko is looking into `It's hard to consume upstream tests in downstream` how it works in javascript/typescript world, so expect some report of her in next one-two days.

**Comment by benoitf** [comment]
AFAIK selenium is not so reliable when you see all talks about its failures.
The same for Jasmine, Jest is used instead in most tools. (React is using jest)

> It's hard to consume upstream tests in downstream
what is 'upstream' ?

Also maybe it's related that when you think in a given framework you shouldn't think/write tests in the same way with another framework.

**Comment by Ohrimenko1988** [comment]
@benoitf Thank you for your response. I have tried all approaches described in the documentation. For "Cypress" reliable work we should disable all key features because of memory consumption. So in fact with "Cypress" we have framework with big restrictions and no one of declared advantages. At least for E2E tests.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/13200

**Comment by ndimer** [comment]
Try http://oxygenhq.org. Let me know if you need help with getting started.
