### ISSUE TITLE
Che Theia: Make task output support escape sequences

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13121]
### Description
Quite often build tools prints labels in different colors in terminal. If we use tasks to build a project it opens `output` widget which looks like terminal, but actually only simulates read only one. And if command sends escape sequences they incorrectly displayed in this widget.
![output](https://user-images.githubusercontent.com/15607393/55949646-c184dc80-5c5b-11e9-8c69-b76b1016485e.png)

### Reproduction Steps
Run a task which prints colored output (or any escape sequences)

**Comment by AndrienkoAleksandr** [comment]
Related to https://github.com/eclipse/che/issues/12609 , because task plugin could not use terminal widget with help plugin api.

**Comment by AndrienkoAleksandr** [comment]
Fixed by https://github.com/eclipse/che-theia/pull/223
