### ISSUE TITLE
404  /api/project/tree/commands?depth=1&includeFiles=true   

### ISSUE THREAD

**Issue by Hailongli88** [eclipse-che/che#13128]
Why is there such a request?  
1、This request will be reported 404 each time I create a command. 
     Error message:  "Can't find item /commands"
2、Error Log of dev-machine:
     Can not handle file operation:  Can't read file, it does not exsit: /commands/build……
     Can not handle file operation:  The file is not found by path  /commands/build………

But It does not affect normal use.
Is it possible to take this request off?   
@skabashnyuk  thanks

**Comment by skabashnyuk** [comment]
Hello @Hailongli88 thank you for your question. Can you provide a bit more information about the use case and environment what you are doing and what the issue is?
- Che version?
- Infrastructure
- What are you doing?
- What do you expect to see?
- What did you saw?
