### ISSUE TITLE
Java code assist is malfunctioning

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#13125]
### Description
After trying to confirm a fix introduced to Rh-Che factories ([link](https://github.com/redhat-developer/rh-che/issues/1341)), the `eclipse.che.ls.java` was added and enabled in the `vert.x` stack.
This change has rendered the editor to be virtually unusable as the language server keeps editing the file, jumping around and rewriting entire lines of code at times.
It also incorrectly responds to the key shortcuts and user input in general.

![vertx-lsp-strange-behavior](https://user-images.githubusercontent.com/16451875/55960924-10d40880-5c6e-11e9-97d7-c4461340a655.gif)

It can also be seen that the suggestions are being sorted incorrectly (not offering the exact method that's being typed in)

___

**EDIT:** The action suggestions (Alt + Return) are also behaving strange, they are skipping to every other option with a single key stroke

![maven-lsp-strange-behavior](https://user-images.githubusercontent.com/16451875/56023537-5b0cc680-5d0e-11e9-9d0c-1c17cabea15f.gif)

### Reproduction Steps
* Open any java based stack with the LSP enabled (GWT che6 based stacks)
* Try autocomplete on any java syntax

**OS and version:**    
docker based deployment on OpenShift 3.11
che 7 beta 2 build
revision: 2fa591ad2372308c

**Comment by tsmaeder** [comment]
> It also incorrectly responds to the key shortcuts and user input in general.

What is your input, what happens and what is your expectation of correct behaviour?

**Comment by ScrewTSW** [comment]
> > It also incorrectly responds to the key shortcuts and user input in general.
> 
> What is your input, what happens and what is your expectation of correct behaviour?

Hello, You can see the accurate input I'm providing in the gif and you can see the behavioural response from the LSP.

I was trying to get it to auto-complete my inputs.
The thing is that sometimes it just triggers on it's own while I'm typing, sometimes it doesn't get triggered by the `Ctrl + space` shortcut, sometimes it overwrites the entire line, or it just spits the correct method one line lower leaving the residue I was typing where it was and similar stuff.

**Comment by ScrewTSW** [comment]
Description updated, added an extra issue that I've discovered with the Java LSP
