### ISSUE TITLE
Adjust jsonrpc configuration

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13131]
### Description
The goal of this task is to follow the recommendation of https://github.com/redhat-developer/rh-che/pull/1323 study and adjust jsonrpc configuration to avoid any OOM on unexpected behavior.

**Comment by skabashnyuk** [comment]
At this moment I'm not able to reproduce OOM as shown ![Screenshot_20190328_144043](https://user-images.githubusercontent.com/16451875/55163010-4d314000-5169-11e9-9e37-e1b2378178fb.png)
However, in theoury, I agree that 10M is quite a big number

**Comment by ScrewTSW** [comment]
> At this moment I'm not able to reproduce OOM as shown ![Screenshot_20190328_144043](https://user-images.githubusercontent.com/16451875/55163010-4d314000-5169-11e9-9e37-e1b2378178fb.png)
> However, in theoury, I agree that 10M is quite a big number

Is that a crash that I can see? It seems that your pod has been restarted.

**Comment by skabashnyuk** [comment]
@ScrewTSW Sorry I wasn't clear enough. That was an image from your pr that I'm not able to reproduce at this moment.

**Comment by ScrewTSW** [comment]
> @ScrewTSW Sorry I wasn't clear enough. That was an image from your pr that I'm not able to reproduce at this moment.
> FYI https://github.com/skabashnyuk/json-rpc-loader framework that is reproducing 90% of real messages of GWT IDE load.

Which method did you use for reproduction?

**Comment by skabashnyuk** [comment]
@ScrewTSW -  Reverse engineering.
Recordings
https://github.com/skabashnyuk/json-rpc-loader/tree/master/logs
Reproduction
https://github.com/skabashnyuk/json-rpc-loader/blob/master/loader.go#L40-L165

**Comment by ScrewTSW** [comment]
So you didn't try it with my tool?

**Comment by skabashnyuk** [comment]
@ScrewTSW did that couple of weeks ago but failed. Want to try one more time.

**Comment by skabashnyuk** [comment]
I ran 6 containers like 
```
docker run --detach -p 8089:8089 \
-e "TOKEN=t1" \
-e "BASEURL=che-eclipse-che.192.168.64.71.nip.io" \
-e "PROTOCOL=http" \
-e "WEBSOCKET=websocket" \
quay.io/tdancs/rhche-locust-load-tests
```
with confuguration: 300 users / 5 hatch rate
And I have such figures

![Знімок екрана  о 16 58 30](https://user-images.githubusercontent.com/1614429/56042821-988c4680-5d44-11e9-9ca7-f5e0672e9a45.png)
![Знімок екрана  о 16 59 10](https://user-images.githubusercontent.com/1614429/56042822-9b873700-5d44-11e9-8b4f-26f881677db1.png)
That is basically telling.
- ```che.core.jsonrpc.processor_max_pool_size=50``` - are not use all in this test. Probably too high.
- ```che.core.jsonrpc.processor_core_pool_size=3``` - ok. May be can be slightly bigger.
- ```che.core.jsonrpc.processor_queue_capacity=10000000``` hard to say. OOM is not reproduced.  Need to be reduced. There is no need to keep such a big queue.
- ```che.core.jsonrpc.minor_processor_max_pool_size=100``` too big. since minor queue is low -  all pull used not on a full power. We see a lot of rejections.
- ```che.core.jsonrpc.minor_processor_core_pool_size=5``` ok. May be can be slightly bigger.
- ```che.core.jsonrpc.minor_processor_queue_capacity=100``` too low. Significantly bigger.

TODO take a look at The HTTP Connector configuration maybe we need to reduce the number of working threads in the default configuration. A number of timed-waiting thread is a bit bigger than expected.

**Comment by skabashnyuk** [comment]
Results on default che server configuration with json-rpc-loader
```
 docker run -e JSONRPCLOADER_CHE_HOST=che-eclipse-che.192.168.64.71.nip.io ksmster/json-rpc-loader
Unable to find image 'ksmster/json-rpc-loader:latest' locally
Trying to pull repository docker.io/ksmster/json-rpc-loader ...
latest: Pulling from docker.io/ksmster/json-rpc-loader
8e402f1a9c57: Already exists
e6802a6a38ef: Pull complete
bb5ea37d8f1b: Pull complete
fc6bce3eaf1c: Pull complete
Digest: sha256:6a0469f9ed340e96cd16cec39eee92a9f575e30f49f48cd93313cd3378bd5711
Status: Downloaded newer image for docker.io/ksmster/json-rpc-loader:latest
This application is configured via the environment. The following environment
variables can be used:

KEY                           TYPE             DEFAULT    REQUIRED    DESCRIPTION
JSONRPCLOADER_CHE_HOST        String                      true        Che Server host
JSONRPCLOADER_CHE_TOKEN       String                                  User token for multi-user che
JSONRPCLOADER_CLIENT          Integer          10                     Number of clients used to send messages
JSONRPCLOADER_WS_TIMEOUT      Duration         10s                    Websocket connection timeout
JSONRPCLOADER_SECURE          True or False    false                  Whatever secure websocket aka wss connection should be used
JSONRPCLOADER_MULTIPLEXING    True or False    false                  Whatever use single websocket connection by each client to send request
Configuration is set to:
CheHost: che-eclipse-che.192.168.64.71.nip.io
Token:
Threads: 10
Timeout: 10s
Secure: false
Multiplexing: false
```

![Знімок екрана  о 17 34 30](https://user-images.githubusercontent.com/1614429/56045227-87920400-5d49-11e9-974e-836c05dd9b6a.png)
![Знімок екрана  о 17 34 48](https://user-images.githubusercontent.com/1614429/56045233-8a8cf480-5d49-11e9-83fc-2bc3dbf9f423.png)

Observations
- A notable difference between the numbers of processed major and minor tasks.
- Both queues are working
- Minor queues size is too low. 100 threads are not enough to process that load.
- Minor load ~10x bigger in comparison to tdancs/rhche-locust-load-tests tests
- ```Major active max= 3 ``` means that with such a big queue 50 threads may not be needed.


At this moment my recomendation to set:
```
che.core.jsonrpc.processor_core_pool_size=5
che.core.jsonrpc.processor_queue_capacity=100000
che.core.jsonrpc.minor_processor_core_pool_size=15
che.core.jsonrpc.minor_processor_queue_capacity=10000
```

**Comment by skabashnyuk** [comment]
```
 docker run -e JSONRPCLOADER_CHE_HOST=che-eclipse-che.192.168.64.71.nip.io ksmster/json-rpc-loader
This application is configured via the environment. The following environment
variables can be used:

KEY                           TYPE             DEFAULT    REQUIRED    DESCRIPTION
JSONRPCLOADER_CHE_HOST        String                      true        Che Server host
JSONRPCLOADER_CHE_TOKEN       String                                  User token for multi-user che
JSONRPCLOADER_CLIENT          Integer          10                     Number of clients used to send messages
JSONRPCLOADER_WS_TIMEOUT      Duration         10s                    Websocket connection timeout
JSONRPCLOADER_SECURE          True or False    false                  Whatever secure websocket aka wss connection should be used
JSONRPCLOADER_MULTIPLEXING    True or False    false                  Whatever use single websocket connection by each client to send request
Configuration is set to:
CheHost: che-eclipse-che.192.168.64.71.nip.io
Token:
Threads: 10
Timeout: 10s
Secure: false
Multiplexing: false
```
and 
```
che.core.jsonrpc.processor_core_pool_size=5 (was 3)
che.core.jsonrpc.processor_queue_capacity=100000 (was 10 000 000)
che.core.jsonrpc.minor_processor_core_pool_size=15 (was 10)
che.core.jsonrpc.minor_processor_queue_capacity=10000 (was 100)
```
![Знімок екрана  о 17 52 32](https://user-images.githubusercontent.com/1614429/56046415-db055180-5d4b-11e9-89b4-2dfc709c11be.png)
as you can see we have maximum processed messages without rejections with minimal used threds

**Comment by ScrewTSW** [comment]
Interesting. It's strange that for you it's behaving differently than for me, but I did not try it with the latest upstream.

**Comment by skabashnyuk** [comment]
@ScrewTSW I think you were right. I received completely different figures on multi-user che. Later I'll put them here.

**Comment by skabashnyuk** [comment]
Results on default multi user che server configuration.
![Знімок екрана  о 10 03 22](https://user-images.githubusercontent.com/1614429/56639776-1ff98400-667a-11e9-9dd8-68ca42a21b58.png)
![Знімок екрана  о 10 03 43](https://user-images.githubusercontent.com/1614429/56639780-2425a180-667a-11e9-9511-f0f966610cd2.png)

A couple of observations, singe vs multu-user Che.
- queue saturation confirmed.
- maximum time of task execution increased from 3.5s to 150s
- the number of completed tasks/minute reduced. Major 1000 to 7-15, minor from 10000 to 100-300
