### ISSUE TITLE
Teach Che Server to understand application/yaml content type

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13133]
### Description
The goal of this issue to teach Che Server to understand `application/yaml` content type.

We started to use YAML format for Devfile and we plan to have the following method for creating a workspace from Devfile:
```java
  @POST
  @Path("/")
  @Consumes("application/yaml")
  @Produces(APPLICATION_JSON)
  @ApiOperation(value = "Create a new workspace based on the Devfile",
      response = WorkspaceDto.class,
      nickname = "createFromDevfile")
  })
  public Response create(
      @ApiParam(value = "The configuration to create the new workspace", required = true)
          DevfileDto devfile)
      throws ApiException {
 ...
}
```
This is needed for Devfile as part of workspace but can be implemented and merged to master separate. To check functionality tests may be used, like the following
https://github.com/eclipse/che/compare/master...sleshchenko:restYaml?expand=1
This Diff is here just as an example and should be rewritten in a better way to maybe covert all cased with different fields formats (string, int, boolean, Map, List, Object).
The Diff contains a sample with DTOs and it's a logical to have the same approach for JSON and YAML, but it is not final decision and YAML may be parsed directly to Implementation (like https://raw.githubusercontent.com/eclipse/che/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/devfile/DevfileImpl.java) if it is a easier/faster and good enough solution.

Note that we already have such method (with the same method POST, and with the same path `/`) but with different argument type in WorkspaceService. It is needed to find a way to configure Swagger to display such methods in a proper way. It may be done in a separate issue.

### Reproduction Steps
See https://github.com/eclipse/che/compare/master...sleshchenko:restYaml?expand=1

**Comment by sleshchenko** [comment]
I've figured out that Kubernetes/OpenShift uses `application/json` for REST API by default and clients (Dashboard[2], chectl, oc) do convert of JSON to YAML and vice versa. 
Before implementing this issue it is needed to investigate this topic more and maybe we should use JSON by default as well.
Kubernetes/OpenShift API is able to consume parse YAML as well [2].

<details>
<summary>[1] OpenShift console converts YAML to JSON</summary>

![Screenshot_20190418_162048](https://user-images.githubusercontent.com/5887312/56497012-85c3ff80-6504-11e9-9660-f1779a5a4bdd.png)


</details>

<details>

<summary>[2] YAML body with curl</summary>

![Screenshot_20190422_134036](https://user-images.githubusercontent.com/5887312/56497074-c4f25080-6504-11e9-9372-513483a869eb.png)

</details>

**Comment by skabashnyuk** [comment]
We do have that right now for ``` POST /api/workspace/devfile/```
