### ISSUE TITLE
Tooltip in workspace panel should be showing the complete command

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13149]
### Description

The workspace view allows the user to see all the commands predefined with a container.
The tooltip over the command is not informative enough, it should be displaying the content of the command. 
This will help to differentiate the commands between each other in certain cases.

![Capture d’écran 2019-04-15 à 12 07 33](https://user-images.githubusercontent.com/1636769/56124737-9b22b200-5f77-11e9-8f7b-5a585a134cd8.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by nickboldt** [comment]
See #13989 for a better solution -- being able to not just SEE but edit the command.
