### ISSUE TITLE
Java plugin not working in a Che 7 workspace with 2 other plugins on che.openshift.io (not respecting memory limit)

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13146]
### Description

When i try to activate the language Support by Java on a Che 7 workspace in che.openshift.io, there is a message stating that java server crashed 5 times and won't be restarted.

### Reproduction Steps

- go to che.openshift.io
- create a Che 7workspace
- modify workspace to include Language Support for java workspace
- restart workspce
- wait a bit...
--> check in Output -> language SSupport for java, there is 
```
[Info  - 09:11:38] Connection to server got closed. Server will restart.
[Info  - 09:11:52] Connection to server got closed. Server will restart.
[Info  - 09:12:15] Connection to server got closed. Server will restart.
[Info  - 09:12:32] Connection to server got closed. Server will restart.
[Error - 09:12:46] Connection to server got closed. Server will not be restarted.
```
**OS and version:**    

**Diagnostics:**

**Comment by l0rd** [comment]
@apupier you need to set memory as it's done [here](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L804). 

That should be solved once the new Che 7 stacks will be available on che.openshift.io (cc @ibuziuk).

**Comment by apupier** [comment]
Unfortunately, it is not possible to apply the workaround by default on che.openshift.io:

`Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspacelquowze86j7hfa5x.ws-56dd8dbc5c-fks26" is forbidden: [maximum cpu usage per Pod is 6, but limit is 7666m., maximum memory usage per Pod is 3Gi, but limit is 4117594112.]', 'workspacelquowze86j7hfa5x.ws-56dd8dbc5c'"`

**Comment by apupier** [comment]
I tried to increase the workspace RAm to 2G but it then fails with similar error:

`Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspacelquowze86j7hfa5x.ws-7844dd65ff-hwn7h" is forbidden: [maximum cpu usage per Pod is 6, but limit is 10666m., maximum memory usage per Pod is 3Gi, but limit is 5728206848.]', 'workspacelquowze86j7hfa5x.ws-7844dd65ff'"`

**Comment by apupier** [comment]
tried also with 3G which the max allowed per workspace, still same error

**Comment by l0rd** [comment]
You need to set Theia memory as well (and I am using version `next` of theia but this doesn't change much):

```json
  "attributes": {
    "plugins": "che-machine-exec-plugin:0.0.1,org.eclipse.che.vscode-redhat.java:0.38.0",
    "editor": "org.eclipse.che.editor.theia:next",
    "sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "1500Mi",
    "sidecar.org.eclipse.che.editor.theia.memory_limit": "512Mi"
  },
```

**Comment by apupier** [comment]
I tried with it, i still have the same error:

```
Cleaning /plugins dir
Starting Init Plugin Broker
Started Che Plugin Broker
List of plugins and editors to install
- che-machine-exec-plugin:0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- org.eclipse.che.editor.theia:1.0.0 - Eclipse Theia
Starting common Che plugins processing
All plugins have been successfully processed
Started VS Code Plugin Broker
Starting VS Code extensions processing
List of plugins and editors to install
- org.eclipse.che.vscode-redhat.java:0.38.0 - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
All plugins have been successfully processed
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspacelquowze86j7hfa5x.ws-59f65fb58f-tdqcp" is forbidden: [maximum memory usage per Pod is 3Gi, but limit is 5488246784., maximum cpu usage per Pod is 6, but limit is 10221m.]', 'workspacelquowze86j7hfa5x.ws-59f65fb58f'"
```

**Comment by apupier** [comment]
ah I need to have the 2 memory limits set and to not have the workspace RAM set too high (I switched back to 0.5G and it is working)

thanks for your help!

**Comment by l0rd** [comment]
@apupier I think you are facing https://github.com/redhat-developer/che-functional-tests/issues/473

**Comment by l0rd** [comment]
Eventually this should be done automatically after https://github.com/eclipse/che/issues/11801 get fixed

**Comment by ibuziuk** [comment]
@apupier as I understand you was able to run workspace eventually, right?

> apupier-demo-che     1/1       Running   0          5m     jwt-proxy  
> apupier-demo-che     6/6       Running   0          5m     workspace pod

**Comment by apupier** [comment]
the workspace is starting.
I was able to have java working if I have only it (at lerats no errro message but i must admit that i have not tested any completion)

if I have the 3 plugins, the workspace is starting but java language server is not working, I have the error [Error - 14:14:02] Connection to server got closed. Server will not be restarted. error

**Comment by apupier** [comment]
I was able to access the pod log, seems nothing interesting:

```
Plugins Endpoints are  [ 'ws://plqazfooow:6795',
--
  | 'ws://rkzvynozdc:9124',
  | 'ws://pdgejzuioe:7598' ]
  | Plugins Mapping Endpoints are  Map {
  | 'redhat_vscode_xml' => 'ws://plqazfooow:6795',
  | 'redhat_java' => 'ws://rkzvynozdc:9124',
  | 'camel_tooling_vscode_apache_camel' => 'ws://pdgejzuioe:7598' }
  | Starting the deployer with the list of resolvers [ LocalDirectoryPluginDeployerResolver {},
  | GithubPluginDeployerResolver { unpackedFolder: '/tmp/github-remote' },
  | HttpPluginDeployerResolver { unpackedFolder: '/tmp/http-remote' },
  | VsCodePluginDeployerResolver { unpackedFolder: '/tmp/vscode-extension-marketplace' } ]
  | Theia Endpoint 19/pid listening on port 9124
  | Found the list of default plugins ID on env: undefined
  | Found the list of plugins ID on env: undefined
  | Found the list of default plugins ID from CLI: undefined
  | PLUGIN_HOST(19): PluginManagerExtImpl/init()
  | PLUGIN_HOST(19): initializing(/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
  | PLUGIN_HOST(19): PluginManagerExtImpl/loadPlugin(/plugins/org.eclipse.che.vscode-redhat.java.0.38.0/extension/dist/extension)
```

![image](https://user-images.githubusercontent.com/1105127/56211563-6fc3c400-6058-11e9-92ac-5c0acb22a9b7.png)

**Comment by apupier** [comment]
the sidecar pod containing the Java LS is marked to have 150MiB available only:

![image](https://user-images.githubusercontent.com/1105127/56212495-6b98a600-605a-11e9-8360-00bb1a61b0e4.png)

although I mentioned "sidecar.org.eclipse.che.camel-tooling.vscode-redhat.java.memory_limit": "1280Mi"

Shouldn't be indicated 1280instead of 125 at this place?

**Comment by l0rd** [comment]
@apupier I think this may be a bug. Can you share your `attributes` section so that we can try to reproduce it?

**Comment by apupier** [comment]
> Can you share your `attributes` section so that we can try to reproduce it?

here is the latest that I tried:

```
"attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "sidecar.org.eclipse.che.redhat.vscode-xml.memory_limit": "128Mi",
    "sidecar.org.eclipse.che.camel-tooling.vscode-redhat.java.memory_limit": "1280Mi",
    "plugins": "che-machine-exec-plugin:0.0.1,https://raw.githubusercontent.com/apupier/che-plugin-registry/109-AddApacheCamelVSCodeExtension/plugins/camel-tooling.vscode-apache-camel:0.0.14,org.eclipse.che.vscode-redhat.java:0.38.0,redhat.vscode-xml:0.3.0",
    "sidecar.org.eclipse.che.editor.theia.memory_limit": "512Mi",
    "sidecar.org.eclipse.che.camel-tooling.vscode-apache-camel.memory_limit": "128Mi"
  }
```

**Comment by apupier** [comment]
OMG, rereading, the alue is wrong:
"sidecar.org.eclipse.che.camel-tooling.vscode-redhat.java.memory_limit": "1280Mi",
shoudl be 
"sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "1280Mi",

**Comment by apupier** [comment]
it is not working either:

```
 "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "sidecar.org.eclipse.che.redhat.vscode-xml.memory_limit": "128Mi",
    "sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "1280Mi",
    "plugins": "che-machine-exec-plugin:0.0.1,https://raw.githubusercontent.com/apupier/che-plugin-registry/109-AddApacheCamelVSCodeExtension/plugins/camel-tooling.vscode-apache-camel:0.0.14,org.eclipse.che.vscode-redhat.java:0.38.0,redhat.vscode-xml:0.3.0",
    "sidecar.org.eclipse.che.editor.theia.memory_limit": "512Mi",
    "sidecar.org.eclipse.che.camel-tooling.vscode-apache-camel.memory_limit": "128Mi"
  }
```

**Comment by l0rd** [comment]
The same error? Because we have https://github.com/redhat-developer/rh-che/issues/1371 as well on che.openshift.io

**Comment by apupier** [comment]
with the lastly provided attributes config, I had no error at all. Just no completion or hover or anything that seems related to Java. At the bottom it was blocked on "57% Java initialization" (or something like that)

In case, I increase the memory limits for the extension, I have the same kind of error pointed by redhat-developer/rh-che#1371

**Comment by ibuziuk** [comment]
also can repro quota issue with a few plugins enabled:

> pulling image "eclipse/che-remote-plugin-runner-java8:next"
> Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspaceo45z391nqghagzfs.che-jwtproxy-647c78c7df-s2dtw" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=292m,limits.memory=157286400, used: limits.cpu=5905m,limits.memory=3173875712, limited: limits.cpu=6,limits.memory=3Gi', 'workspaceo45z391nqghagzfs.che-jwtproxy-647c78c7df'"

**Comment by tsmaeder** [comment]
@apupier @l0rd @ibuziuk I don't really think this is a bug: if the limits on openshift.io are less than what we need, we can either not support this use case on openshift.io, increase the limits or create a special configuration that runs within those limitations.

What I am really saying is: what would be an action that would solve this case?

**Comment by apupier** [comment]
I think there are 2 slightly different issues:

- one is that, by default, when using several extensions, the memory available on che.openshift.io are not enough. I think it is the case that "the limits on openshift.io are less than what we need, we can either not support this use case on openshift.io, increase the limits or create a special configuration that runs within those limitations."
- the second is that even after setting memory limits for each sidecars, it is still not working as it seems that the memory limits are not respected. see https://github.com/eclipse/che/issues/13146#issuecomment-483654951

**Comment by l0rd** [comment]
@tsmaeder you are right for memory limits (there is not much we can do) but for the services limit we are creating more than 15 services and most of them are only for inter-container communications (i.e. we do not really need 15 services) hence there is still room for improvement.

@apupier isn't your second issue related to redhat-developer/rh-che#1371? In this case we may fix that when we fix https://github.com/eclipse/che/issues/11018 (@davidfestal task for next sprint)

**Comment by apupier** [comment]
> @apupier isn't your second issue related to [redhat-developer/rh-che#1371](https://github.com/redhat-developer/rh-che/issues/1371)?

I don't think that it is the same issue. In https://github.com/redhat-developer/rh-che/issues/1371 , it is a problem of number of services. here, i'm experiencing memory limit issues.

**Comment by apupier** [comment]
I tried again with theia:next and the camel extension which is no win official registry and i still hit the same problem. Here is the config attributes:

```
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:next",
    "sidecar.org.eclipse.che.redhat.vscode-xml.memory_limit": "128Mi",
    "sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "1280Mi",
    "plugins": "che-machine-exec-plugin:0.0.1,org.eclipse.che.vscode-redhat.java:0.38.0,camel-tooling.vscode-apache-camel:0.0.14,redhat.vscode-xml:0.5.1",
    "sidecar.org.eclipse.che.editor.theia.memory_limit": "512Mi",
    "sidecar.org.eclipse.che.camel-tooling.vscode-apache-camel.memory_limit": "128Mi"
  }
```

**Comment by tsmaeder** [comment]
@apupier with the recent changes in the plugin registry, you probably need to update the attributes to the new format of plugin id's: "sidecar.redhat/java.memory_limit": "1500Mi"

**Comment by apupier** [comment]
I tried with

```
 "attributes": {
    "editor": "org.eclipse.che.editor.theia:next",
    "sidecar.eclipse/che-theia.memory_limit": "512Mi",
    "sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "1280Mi",
    "plugins": "che-machine-exec-plugin:0.0.1,org.eclipse.che.vscode-redhat.java:0.43.0,camel-tooling.vscode-apache-camel:0.0.14,redhat.vscode-xml:0.5.1",
    "sidecar.redhat/java.memory_limit": "1500Mi",
    "sidecar.camel-tooling/vscode-apache-camel.memory_limit": "128Mi",
    "sidecar.org.eclipse.che.editor.theia.memory_limit": "512Mi",
    "sidecar.org.eclipse.che.redhat.vscode-xml.memory_limit": "128Mi",
    "sidecar.redhat/vscode-xml.memory_limit": "128Mi"
  },
```

the sidecar seems to use the 1280M that I assigned to it:
![image](https://user-images.githubusercontent.com/1105127/57689008-032feb00-763f-11e9-8788-854207254142.png)

and i finally have both 3 plugins working altogether!!! (after waiting for several mintutes that Java Language Server is ready)
Java completion:
![image](https://user-images.githubusercontent.com/1105127/57689120-3bcfc480-763f-11e9-94df-ce6ac64e72d7.png)
Camel URI completion for Java:
![image](https://user-images.githubusercontent.com/1105127/57689150-49854a00-763f-11e9-9e57-cdba8a165650.png)
Camel URI completion for XML:
![image](https://user-images.githubusercontent.com/1105127/57689186-5ace5680-763f-11e9-8592-1ab3b8f9d1c9.png)
XML completion:
![image](https://user-images.githubusercontent.com/1105127/57689211-6752af00-763f-11e9-9873-22e87af85002.png)

**Comment by apupier** [comment]
closing as it is working now (even if the availability of the Java Language Server is taking more than 10 minutes)
