### ISSUE TITLE
Commands coming with the code samples of stacks are not working

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13148]
### Description
The commands provided with the code samples of the out-of-the-box default stacks for Java are not working and raising an error message. 

### Reproduction Steps
1. Create workspace with stack Che7-Maven or Che7-Gradle
2. Select a code-sample (any of those)

![Capture d’écran 2019-04-15 à 11 47 19](https://user-images.githubusercontent.com/1636769/56124356-c5c03b00-5f76-11e9-8d08-db059e24ff0a.png)

3. Start the workspace, wait for it to be running.
4. Open the command palette and select the command "Maven Build"
5. IDE is asking in which container you want to execute the command, select "Maven-container"

![Capture d’écran 2019-04-15 à 11 54 10](https://user-images.githubusercontent.com/1636769/56124370-cc4eb280-5f76-11e9-932a-9304542258aa.png)

**OS and version:**    

**Diagnostics:**

**Comment by l0rd** [comment]
@slemeur I think that's related to https://github.com/eclipse/che-theia/issues/155 no?

**Comment by slemeur** [comment]
Fixed with the latest version
