### ISSUE TITLE
Cannot upgrade to 6.19.1 and later

### ISSUE THREAD

**Issue by djfjeff** [eclipse-che/che#13153]
### Description
I run Eclipse Che 6.19.0 but since then, I cannot upgrade to 6.19.1 and later. The reason is that the upgrade script does not find any newer images than 6.19.0.

Going to Docker Hub confirm that the latest image for 6.19 is 6.19.0 and there is no trace of 6.19.1, 6.19.2 or 6.19.3

Before that, running the upgrade command was always working fine.

### Reproduction Steps
Run Che 6.19.0 and try to upgrade to 6.19.3

**OS and version:**    
Fedora 29

**Diagnostics:** 
```
user@che ~ $ docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/eclipse:/data eclipse/che:6.19.3 upgrade
Unable to find image 'eclipse/che:6.19.3' locally
docker: Error response from daemon: manifest for eclipse/che:6.19.3 not found.
```

**Comment by eivantsov** [comment]
@djfjeff Docker support has been discontinued after 6.19. I recommend switching to OpenShift or k8s.

**Comment by djfjeff** [comment]
@eivantsov Thank you.

So 6.19.0 support Docker but not 6.19.1? It seems a weird choice to remove such support in a minor release, just before Che 7.

**Comment by Petrox** [comment]
https://www.eclipse.org/che/docs/che-6/quick-start.html still directs users to try (and fail) with che in docker.

`$ docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /local/path:/data eclipse/che start`

https://hub.docker.com/r/eclipse/che/ does not mention being not supported without orchestration anymore
