### ISSUE TITLE
How to define runtime configuration for editors/plugins in Che 7?

### ISSUE THREAD

**Issue by makandre** [eclipse-che/che#13157]
### Description
 

How do you define runtime env-vars, configuration and/or preferences to be passed to editor/plugins that are started via workspace configuration attributes? i.e.

```
"attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1"
}
```

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
Unfortunately, we can't override it at the moment. See https://github.com/eclipse/che/issues/12981 where we discuss a possibility to override RAM limit. And [my comment](https://github.com/eclipse/che/issues/12981#issuecomment-476863304) to make it also possible to override all the other parts in the same way as mem limit.

**Comment by garagatyi** [comment]
@l0rd @slemeur we need to proceed with the @gorkem 's issue on overriding configuration of a plugin. WDYT about suggested ways?

**Comment by l0rd** [comment]
@makandre can you provide a description of your use case? What do you need the env variables for?

I think it's a good point but I am wondering why we haven't considered that before.

**Comment by makandre** [comment]
My specific use case was I was creating my own welcome page plugin for the Che Theia editor, but the default Che welcome page was still showing up.  So I asked in https://github.com/eclipse/che-theia/issues/95 if there was some way to disable/hide/exclude the default welcome plugin, and one of the suggestion was I could set some env variable.  Hence I wanted to see how I can pass the variable to the editor

I asked the question more generally for editor and plugins because I'm thinking there may be similar use cases.

**Comment by l0rd** [comment]
@makandre that's a good question and thanks for asking. Your use case is a valid one and we will need to implement a way to set env variables for sidecars in the workspace definition. Probably we won't be able to include it in Che 7 GA.

Of course there are at least a couple of workaround you could use now (create your own image `FROM eclipse/che-theia:next` or publish your own che-theia che-plugin.yaml) but these are not straightforward.

**Comment by makandre** [comment]
@l0rd I also came across this issue https://github.com/eclipse/che-theia/issues/159 which seems related.
