### ISSUE TITLE
task ERROR Can't get task launch configuration for label: Get OpenShift Console URL

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13155]
### Description

trying to have more information on a sidecar which is not starting, i tried to click on the "Get OpenShift Console URL" but nothing is happening in UI. In Console log there is 

`task ERROR Can't get task launch configuration for label: Get OpenShift Console URL`

### Reproduction Steps

**OS and version:**    

using che.openshift.io

**Diagnostics:**

**Comment by apupier** [comment]
@monaka i don't understand why you added the label "kind/question". I think that a label "kind/bug" would be more suitable. Or am I missing something?

**Comment by apupier** [comment]
workaround to find the OpenShift console:
- open Terminal from menu
- enter command _echo ${CHE_OSO_CLUSTER//api/console}_

**Comment by monaka** [comment]
@apupier In this status, I don't determine what causes this issue. Not only by bugs in code.  Configurations in che.openshift.io, bugs in the code repository, and/or something will be possible.
So I added `kind/question` to this issue for now.
I'll re-assign to `kind/bug` after clarified this issue is caused by code.

**Comment by RomanNikitenko** [comment]
Maybe related to https://github.com/theia-ide/theia/issues/5064 or https://github.com/theia-ide/theia/issues/4928

**Comment by amisevsk** [comment]
I feel like I've seen similar and it was fixed by using `theia:next`. We'll be rolling out che 7 beta 4 to che.openshift.io *soon* which may also fix the issue.

**Comment by monaka** [comment]
It looks che.openshift.io was upgraded to che7.0.0-beta-4. Still this issue is reproduced? or closable?

**Comment by apupier** [comment]
I just tried on che.openshift.io and seems that it is still nto working but with a differen tbehavior.

BNow there is the tab "Get OpenSHift Console URl" opening but it stays empty.
there are 3 errors:

`Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;base64,BEGINNINGOFSOMETHINGLOOKINGLIKEATOKEN… (“img-src”).`
`Content Security Policy: The page’s settings blocked the loading of a resource at wss://routeoptpiv2r-apupier-demo-che.9a6d.starter-us-east-1a.openshiftapps.com/connect?token=AVERYVERYLONGTOKEN (“default-src”).`
`Error: Failed to create terminal server proxy. Cause: [Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: https://routeekfmo07r-apupier-demo-che.9a6d.starter-us-east-1a.openshiftapps.com/vendors.fb5f164f023b9bd66922.js :: w :: line 1" data: no]`

**Comment by monaka** [comment]
@apupier  Hmm, I'm not still sure but "Content Security Policy" is caused by settings in the server infrastructure side, a lower layer than Che. Did you contact to the support staff in `che.openshift.io` ?

**Comment by monaka** [comment]
@apupier Is this issue reproduced on your environment? Can I close this?

**Comment by apupier** [comment]
currently, I have no account working for testing on che.openshift.io :(

**Comment by amisevsk** [comment]
@apupier Which browser were you using? We've had issues with non-Chrome browsers in the past.

**Comment by apupier** [comment]
I was using Chrome
