### ISSUE TITLE
Duplication of what is typed in terminal view can happen

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13165]
### Description

when i type a letter in terminal view, it is displayed twice....

### Reproduction Steps

don't know. It is working for 2 terminal views, the 3rd one that i opened had this issue.
it was terminal view opened from right panel Containers -> Workspace -> ws/pluginsidecarXXXX -> new terminal

**OS and version:**    

Chrome
windows 10
che.openshift.io

**Diagnostics:** 

if I'm trying to write in an opened file, there is no duplication, neither on other terminal view

if I type my command "ps -edf" and hit enter, the command is well executed... twice

![image](https://user-images.githubusercontent.com/1105127/56200126-76ddd880-603e-11e9-9ad8-999bcd512d55.png)

**Comment by AndrienkoAleksandr** [comment]
@evidolob Could we get this one to the next sprint?
