### ISSUE TITLE
[nitpick] "Docker registries" -> "Container registries"

### ISSUE THREAD

**Issue by rkratky** [eclipse-che/che#13169]
**Description:**

The **Administration** screen in Che has a link titled **Docker Registries**. Suggest to use **Container registries** to make it clear that it can be any container registry, not just from Docker.

**Comment by nickboldt** [comment]
Is this still a thing in Che 7's user dashboard? Where is the **Administration** screen?

**Comment by amisevsk** [comment]
"Administration" is present in the left-hand sidebar in the dashboard:

![Screenshot from 2019-08-01 11-15-08](https://user-images.githubusercontent.com/16168279/62305332-bd204180-b44d-11e9-936a-3baa70550310.png)

**Comment by ibuziuk** [comment]
@rkratky please review -  https://github.com/eclipse/che/pull/14675

**Comment by ibuziuk** [comment]
Fixed in 7.3.0 Closing
