### ISSUE TITLE
Plugin broker should send plugins configuration with separated init container that downloads plugins

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#13163]
### Description
At the moment the plugin broker downloads a plugin binaries and put them in plugins volume `/plugins` in a sidecar or in the main theia container.
When we start ephemeral workspace this leads to running the broker twice which is error prone and not time effective.
Instead of that the broker should return a configuration of plugins with init containers and configuration on what needs to be downloaded and where to put that.

Additional info from [here](https://github.com/eclipse/che/issues/12908#issuecomment-474312103) and [here](https://github.com/eclipse/che/issues/12395#issuecomment-472527140):
Instead of sending brokering results as it is sent now [plugin-service-response-v1.yaml](https://gist.githubusercontent.com/garagatyi/0ae0f6a05b76e504c9152e6eef160917/raw/plugin-service-response-v1.yaml), send results in form which would allow implementing automatic plugins sidecar co-location [plugin-service-response-v2.yaml](https://gist.githubusercontent.com/garagatyi/0ae0f6a05b76e504c9152e6eef160917/raw/plugin-service-response-v2.yaml). See explanation [here](https://github.com/eclipse/che/issues/12395#issuecomment-472527140). Automatic plugins co-location feature would also affect ability of UD to get RAM limits for the whole workspace - we will need to find solution for that.  
Separate sidecar config evaluation and binaries delivering to workspace:
1. Do not support setting container image in Theia plugins using `engine.cheRuntimeContainer` in package.json. Container image has to go into meta.yaml starting from `apiVersion: 2`. This will help avoid confusion when image is set in both meta.yaml and package.json.
1. Rework theia remote sidecar connectivity approach on brokers side to avoid downloading VS Code extension archives to evaluate plugin name and publisher from package.json. This would help splitting sidecar configuration and binaries downloading phases and will speed up workspace start. See Florent’s comment about available options [here](https://github.com/eclipse/che/issues/12395#issuecomment-470591054)
1. Create new golang based tiny program that can download binaries and put it in specified locations. Let’s call it download container.
1. Rework broker to return download container config with plugin binaries location as part of sidecars definition. This should not involve any downloading on the sidecar definition evaluation stage.
1. Make ws master use download container as init container(s) in workspace. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@l0rd @ibuziuk

**Comment by l0rd** [comment]
@garagatyi I have tried to read this a couple of times but I struggle to understand it. We may need to do a call. @ibuziuk what do you think?

**Comment by garagatyi** [comment]
@l0rd I'll try to rephrase the description:
Now:
1.1 broker is started
1.2 broker generates sidecar config
1.3 broker downloads archives of plugins and put them in `/plugins` folder
1.4 if workspace is ephemeral steps 1.2, 1.3 are repeated in a broker running as init container of the workspace
We need to change it to:
2.1 broker is started
2.2 broker generates sidecar config and download config (but doesn't download plugins)
2.3 workspace is started with init containers and download config
2.4 init containers download/unpack/copy files according to download config

It effectively separates sidecar config evaluation and plugins downloading, so:
- allows making broker persistent micro service and reduce workspace start time by avoiding waiting for broker deployment to start
- allows removing second run of brokering for ephemeral workspaces which also cuts workspace start time
- allows caching sidecar configuration which speeds up workspace start

**Comment by l0rd** [comment]
Ok I see. That looks good to me.

**Comment by amisevsk** [comment]
Out of date; current plugin broker issue https://github.com/eclipse/che/issues/14494
