### ISSUE TITLE
After restart Eclipse CHE workspace che-theia should not open empty terminals

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#13167]
### Description
After restart workspace che-theia tries to restore empty terminals. We need store container name and after restart workspace use this info to create new one terminal for corresponding container. In case fail - collapse terminal widget.

### Reproduction Steps
1. Start workspace created from che-theia stack.
2. Create new terminal for dev container.
3. Stop workspace.
4. Start workspace again and open che-theia.

Actual result: Theia opens empty terminal widget.
Expected result: Theia should create new one terminal for dev container - "some kind of restore", or don't open empty terminal widgets at all.

**Comment by azatsarynnyy** [comment]
closing it as cannot reproduce
