### ISSUE TITLE
Add PR trigger for happy path job

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13173]
### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by musienko-maxim** [comment]
ci-test-che7

**Comment by musienko-maxim** [comment]
ci-test-che7

**Comment by musienko-maxim** [comment]
che7-test

**Comment by musienko-maxim** [comment]
che7-test

**Comment by musienko-maxim** [comment]
che7-test

**Comment by musienko-maxim** [comment]
che7-test-ci

**Comment by rhopp** [comment]
@musienko-maxim Some observations:
* The tests (Happy Path) are running in post-build step. Why? I would rather them to run as "main" step.
* Jenkins job is reporting results from unit tests - imo it should report results of happy path test
* We should switch the registry we are using before considering this issue as done - we could create an organization on quay.io for our needs. (I've already created one - if you PM me your quay account name I can add you as admin)
* In the future I would prefer to switch to our own image instead the `cypress` one. We can relatively easily build one on top of centos or UBI tailored for our needs  (Not required for this issue to be considered complete - could be done in some followup issue - in that case it's needed to create such issue)
* Server should be started using chectl with che-operator installer (`chectl server:start --installer=che-operator`)
