### ISSUE TITLE
"Find All references" is always disabled

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13183]
### Description

The "Find All references" action on right-click is greyed out on Camel files although it should be available.

![image](https://user-images.githubusercontent.com/1105127/56347495-ae768d00-61c4-11e9-981b-df64574ffea8.png)

it should even provides results when right-clicking on the "direct:name1" Find all references

it is working fine in VS Code:
![image](https://user-images.githubusercontent.com/1105127/56348633-2e9df200-61c7-11e9-91c9-7afd314d60e3.png)

![image](https://user-images.githubusercontent.com/1105127/56347824-6310ae80-61c5-11e9-862d-b5cfdca016a3.png)

### Reproduction Steps

- install Camel VS Code extension in Che
```
"attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1,https://raw.githubusercontent.com/apupier/che-plugin-registry/109-AddApacheCamelVSCodeExtension/plugins/camel-tooling.vscode-apache-camel:0.0.14"
  }
```
- create a camel.xml file

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd        http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">
    <camelContext id="cbr-example-context" xmlns="http://camel.apache.org/schema/spring">
        <route id="cbr-route">
            <from id="_from1" uri="timer:timerName?delay=1000"/>
            <to id="_to3" uri="direct:name1"/>
        </route>
         <route id="cbr-route">
            <from id="_from1" uri="direct:name1"/>
            <to id="_to3" uri="file:work/cbr/output/others"/>
        </route>
    </camelContext>
</beans>
```
- right-click on "direct:name1"

--> the "Find all references" is greyed out

**OS and version:**    

che.openshift.io
Windows 10
Chrome

**Diagnostics:**

**Comment by tsmaeder** [comment]
Does "find all references" work for other plugins?

**Comment by apupier** [comment]
> Does "find all references" work for other plugins?

that is a good question.
I know only the java plugin which is providing "Find all references" feature but I'm unable to install it on che.openshift.io today

**Comment by apupier** [comment]
I was able to install Python Language Server. it is not working neither with it. So looks alike a generic issue with "find references"

not working in Che
![image](https://user-images.githubusercontent.com/1105127/56882940-7d6c4700-6a65-11e9-9232-57fe8a182c7d.png)

working in VS Code:
![image](https://user-images.githubusercontent.com/1105127/56882950-852beb80-6a65-11e9-9b3d-5830a03b7de7.png)

**Comment by apupier** [comment]
finally able to install Java. And there is also the same problem:
![image](https://user-images.githubusercontent.com/1105127/56883247-624e0700-6a66-11e9-9ca1-57b380f1caff.png)

working in VS Code:
![image](https://user-images.githubusercontent.com/1105127/56883251-6bd76f00-6a66-11e9-89d1-5d1193c131f6.png)

**Comment by apupier** [comment]
I tested with Camel example and it is working fine in Theia.

**Comment by tsmaeder** [comment]
@apupier so are you saying this is fixed?

**Comment by apupier** [comment]
> @apupier so are you saying this is fixed?

no.
it is working in Theia but not in Che.

**Comment by tolusha** [comment]
Tested on minishift, workspace attributes:
```json
 "attributes": {
    "editor": "org.eclipse.che.editor.theia:next",
    "plugins": "che-machine-exec-plugin:0.0.1,https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/plugins/camel-tooling.vscode-apache-camel:0.0.14",
    "persistVolumes": "false"
  },
```
![Screenshot from 2019-05-06 13-07-37](https://user-images.githubusercontent.com/1640675/57219192-f50b1a80-6fff-11e9-972d-6bd9cd532a19.png)

**Comment by apupier** [comment]
tried again, it is working with org.eclipse.che.editor.theia:next and not working with org.eclipse.che.editor.theia:1.0.0 which is the one selected by default.

**Comment by tolusha** [comment]
`1.0.0` probably outdated version and `findAllReferences` weren't implemented there.
Can we close the issue?

**Comment by apupier** [comment]
> Can we close the issue?

I think it depends on the methodology used in Che.

suggestion:
- check that there is an automated test for this feature
-- if no, it would be better to write it before closing (or at least create a specific task for it before closing)
-- if yes, can be closed.

**Comment by tolusha** [comment]
What do you mean by "automated test" ?

**Comment by apupier** [comment]
> What do you mean by "automated test" ?

I mean a test which is executed on a Continuous Integration server on each build/Pull Request of Che or one of its components.

**Comment by tolusha** [comment]
Have you pulled the latest image?

**Comment by tolusha** [comment]
We have api tests https://github.com/theia-ide/theia/issues/4224
If we are talking about e2e test then it is question for QE team. 
There is nothing we can do here.

**Comment by apupier** [comment]
if there is unit test, we are in the case "if yes, can be closed" :-)
