### ISSUE TITLE
Add YAML syntaxcoloration by default

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13187]
### Description
The IDE should be getting the YAML syntax coloration by default.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by benoitf** [comment]
All these VS Code extensions should be integrated by default: https://github.com/Microsoft/vscode/tree/master/extensions

**Comment by tsmaeder** [comment]
@slemeur Marc Dumais is holding off on a CQ for the extensions @benoitf  mentions because we haven't told him how we want to handle the case of the LGPL code in the git extension. We could get the rest merged soon if we can exclude that one.

**Comment by slemeur** [comment]
any update on this?

**Comment by tsmaeder** [comment]
No, I'm not sure where we could consume those extensions from. Someone needs to find out.

**Comment by sunix** [comment]
could we just add our yaml extenshttps://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/redhat/vscode-yamlion  by default to che-theia ?
What is the problem ?

**Comment by benoitf** [comment]
I think it may related to https://github.com/eclipse/che/issues/14759

We should provide by default (in che-theia) all 'builtin VS Code extensions' that provides syntax highlights/grammars
It includes https://github.com/microsoft/vscode/tree/master/extensions/yaml

We don't need https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/redhat/vscode-yaml for syntax highlights (no language server is required just for syntax highlight)

**Comment by sunix** [comment]
@slemeur to me it would solve several problem at the same time and it would be simple to do:
1. simplify few dependency problems with other extensions like the kubernetes ext. user won't have to think about what to activate. until we figure out a better way to do.
2. it is simple to do: just add the ext in the che-theia default plugin to use.
3. in the future we may need to edit devfile.yaml file in any workspaces. it makes sences to have it by default.

**Comment by sunix** [comment]
@evidolob told me that the way we get dependencies will change in the next che version. So maybe forget my previous comment.

**Comment by tsmaeder** [comment]
@benoitf It would make sense to share the build and publish effort in the Theia community. At least the build scripts, etc. should be shared if not publishing the extensions once and consuming them from a common place.

**Comment by benoitf** [comment]
@tsmaeder AFAIK theia community is already publishing them on npmjs
https://www.npmjs.com/search?q=%40theia%20builtin

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse/che-theia/pull/618
VS Code YAML built-in extension is included in Che Theia by default.
