### ISSUE TITLE
Provide Camel stack for Che 7

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13182]
### Description

content:
- Camel plugin (requires https://github.com/eclipse/che-plugin-registry/issues/109 )
- XML plugin
- Java plugin
- same other configurations than what is available for a SpringBoot stack
- Sample project https://github.com/jboss-fuse/fuse-rest-http-booster

for reference see stack for Che 6 https://github.com/eclipse/che/blob/b8fa90c72b934030686cecc06c9366f44bc2f803/ide/che-core-ide-stacks/src/main/resources/stacks.json#L2532

**Comment by apupier** [comment]
blocked by https://github.com/eclipse/che/issues/13146 and merge of https://github.com/eclipse/che-plugin-registry/pull/110

**Comment by tsmaeder** [comment]
Make sure the stack is consistent with the one described in https://github.com/eclipse/che/issues/12620

**Comment by apupier** [comment]
started a branch for it https://github.com/apupier/che/pull/new/13182-ProvideCamelStackForChe7 but unable to test it for now due memory size issues.
Also:
- not understood what PS1 advice in https://github.com/eclipse/che/issues/12620 is for
- not understood in which case /home/users needs to be mounted.

**Comment by apupier** [comment]
memory limits will surely needs to be adjusted compared to what is currently put in the branch https://github.com/apupier/che/pull/new/13182-ProvideCamelStackForChe7 , see https://github.com/eclipse/che/issues/13146#issuecomment-492171279
