### ISSUE TITLE
Plugins page on workspace details does not show all the plugins

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13186]
### Description
List of plugins is incomplete and not showing all the plugins we have.

### Reproduction Steps

1. Create a workspace from the Gradle 
2. start the workspaces
3. go to the workspace details and in the plugin tabs

<img width="2032" alt="Capture d’écran 2019-04-18 à 16 37 10" src="https://user-images.githubusercontent.com/1636769/56368788-6d986b80-61f8-11e9-91ae-2a94852f0bac.png">

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
Seems already fixed 
![image](https://user-images.githubusercontent.com/1851863/56411850-d3353800-628a-11e9-997c-6aa962902be4.png)
Closing, but feel free to reopen if I misunderstood something
