### ISSUE TITLE
devfile unable to start workspace agent, ingress name too long

### ISSUE THREAD

**Issue by makandre** [eclipse-che/che#13189]
### Description
 

I'm using a devfile to create a workspace on Che on kubernetes, but it fails:

```
Unable to start workspace agent. Error when trying to start the workspace agent: Failure executing: POST at: https://10.0.0.1/apis/extensions/v1beta1/namespaces/workspacemc2a9uai66r4rq9j/ingresses. Message: Ingress.extensions "ingressh7vqrqnz" is invalid: metadata.labels: Invalid value: "server9lpo3qfa-che-workspace-pod-makandre-che-sidecar-server-8080": must be no more than 63 characters.
```

It appears the ingress name generated by Che (`server9lpo3qfa-che-workspace-pod-makandre-che-sidecar-server-8080`) exceeds kubernetes' 63 character limit.  When this happens the name should be trimmed

### Reproduction Steps

**OS and version:**    

Che7 beta3

**Diagnostics:**

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/13126
Feel free to reopen the issue if it still is reproducible for you.
