### ISSUE TITLE
Gradle stack, terminal does not open in '/projects' by default

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13184]
### Description
When using the Gradle stack and open a terminal, I'd like to directly open the terminal in the path `projects`

### Reproduction Steps
1. Create a Gradle Stack
2. in the ide, open a terminal (in the container gradle)
3. check the path

see:
<img width="2032" alt="Capture d’écran 2019-04-18 à 16 04 21" src="https://user-images.githubusercontent.com/1636769/56366705-04aef480-61f4-11e9-9c09-99e04a38b80d.png">

**OS and version:**    

**Diagnostics:**

**Comment by tsmaeder** [comment]
The terminal opens onto the "home" directory in the container. Why would you want to open "/projects" specifically in the gradle case?

**Comment by slemeur** [comment]
For consistency with the other stacks which are also opening in "/projects".

**Comment by amisevsk** [comment]
There's a fair bit of weirdness with the maven/gradle stacks if I recall. On che.openshift.io, they're totally broken.

**Comment by slemeur** [comment]
@tsmaeder : have you checked on che.openshift.io ?

**Comment by nickboldt** [comment]
Reproduced w/ Che 7 RC1 and the Grade 5.2.1 / OpenJDK 11 stack.

![image](https://user-images.githubusercontent.com/227597/59536011-776ce100-8ec0-11e9-8e5a-e180c4ec1e42.png)

**Comment by amisevsk** [comment]
Does not reproduce on 7.7.0-SNAPSHOT, I'm guessing this was fixed by the arbitrary user id patch.
