### ISSUE TITLE
Cannot start Eclipse Che workspace

### ISSUE THREAD

**Issue by AFEIJIAN** [eclipse-che/che#13193]
### Description
Error happens when I tried to run Eclipse Che, I also tried the HTTPS tutorial by using port 443 for Che, but it said that port is used, so I skipped and used port 8080 and 445, but the problem is same for both ports.

I don't think this is a firewall related issue, because I didn't enable firewall before and after I use the start command.

### Reproduction Steps
I tried command below to run the workspace:

**for port 445**
` sudo docker run -it CHE_HOST=dev.mydomain.com -e CHE_PORT=445 -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start`

**for port 8080**
` sudo docker run -it  -e CHE_PORT=8080 -e CHE_HOST=dev.mydomain.com -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start`

**other -e options I used:**
CHE_MULTIUSER=true
CHE_SINGLEPORT_WILDCARD__DOMAIN_HOST=dev.mydomain.com
CHE_HOST_PROTOCOL=https
CHE_SINGLE_PORT=true
CHE_SINGLEPORT_WILDCARD__DOMAIN_IPLESS=true
CHE_HTTPS_CERTIFICATE_PROVIDER=file

**OS and version:**    
Distro: Ubuntu 18.04.2 LTS
Docker version: 18.09.3
Che version: 7.0.0-beta-3.0

**Diagnostics:** 

**Output from `info --network`:**

WARN: Bound 'eclipse/che' to 'eclipse/che:7.0.0-beta-3.0'
WARNING: No swap limit support
INFO: (che cli): 7.0.0-beta-3.0 - using docker 18.09.3 / native
WARN: Newer version '7.0.0-beta-3.0' available
INFO:
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: (che network): eclipse/che-ip:7.0.0-beta-3.0: dev.mydomain.com
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (dev.mydomain.com): Connection failed
write /dev/stdout: broken pipe
INFO: (che network): Server  => Workspace Agent (External IP): Connection
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded

**Output from start command:**

WARN: Bound 'eclipse/che' to 'eclipse/che:7.0.0-beta-3.0'
WARNING: No swap limit support
INFO: (che cli): 7.0.0-beta-3.0 - using docker 18.09.3 / native
WARN: Newer version '7.0.0-beta-3.0' available
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
WARNING: No swap limit support
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 445 (http):        [AVAILABLE]
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]

ERROR: Try 'docker run <options> eclipse/che info --network' for more tests.

**Things I had tried:**

1. Change the ephemeral port to 8080-65535 via sysctl.conf (before it were 32768-65535)

`sudo sysctl -A| grep ip_local_port_range`
`net.ipv4.ip_local_port_range = 8080     65535`

2. Disabled firewall, via `sudo ufw disable`.

Thanks in advance.

**Comment by bryanxtong** [comment]
Have you tried the trace command and It will tell what happened once you have a error. 

sudo docker run -it -e CHE_PORT=8080 -e CHE_HOST=dev.mydomain.com -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start --trace

**Comment by amisevsk** [comment]
Che 7 is not designed to be run directly on docker, the supported platforms are Kubernetes (for local you can use `minikube`) and OpenShift (locally: `minishift`, `crc`)
