### ISSUE TITLE
workspace-loader doesn't recognize when workspace start fails immediately after start request is sent

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#13209]
### Description
When because of some reason workspace start request succeeds but start itself fails immediately after that wsmaster send event with error to subscribed websocket clients.
But workspace-loader doesn't receive it because it subscribes only after that message was already sent.
Which leads to a infinitely running loading screen with no error shown
![image](https://user-images.githubusercontent.com/1851863/56561007-a2b50d00-65ae-11e9-8583-bfa661977242.png)

It seems that workspace-loader subscribes to workspace status event after sending workspace start request, not before that.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@vitaliy-guliy FYI

**Comment by vitaliy-guliy** [comment]
Thanks!

**Comment by rhopp** [comment]
@akurinnoy Shouldn't this issue be reopened, as the commit was reverted?

**Comment by akurinnoy** [comment]
@rhopp sure, thanks!
