### ISSUE TITLE
Che plugin broker fails to find meta.yaml 

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13208]
### Description
When user wants to use an editor from custom registry and tries to refer to the editor metadata by link, Che plugin broker fails to download it despite correct url is specified.

### Reproduction Steps
1. Create custom plugin registry
2. Create a workspace and use link to custom editor in `attributes.editor` field of workspace config, for example:
`https://raw.githubusercontent.com/user/che-custom-plugins/master/plugins/org.eclipse.che.editor.theia:1.0.0`
3. Start the workspace

**Expected:** workspace is started with the custom editor
**Actual**: Workspace start fails by timeout. Logs from plugin broker pod:
```
Failed to download plugin metas: failed to fetch plugin meta.yaml for plugin 'org.eclipse.che.editor.theia:1.0.0' from registry 'https://raw.githubusercontent.com/user/che-custom-plugins/master/plugins': Downloading https://raw.githubusercontent.com/user/che-custom-plugins/master/plugins/plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml failed. Status code 404. Response body: 404: Not Found
```
Note double _plugins_ section in path.

After deleting of _plugins_ section from the uri path (which makes the uri invalid) it can find the metadata.

#### Environment
Minikube, Che multiuser

**Comment by garagatyi** [comment]
@amisevsk might be related to the latest changes in plugin brokers

**Comment by vitaliy-guliy** [comment]
This bug is blocking the development of Plugin management
https://github.com/eclipse/che/issues/12905

**Comment by amisevsk** [comment]
This looks to be related to the Che-side processing of registry URLs. I'll take a look.

**Comment by garagatyi** [comment]
@amisevsk I have already created a PR to tackle that https://github.com/eclipse/che-plugin-broker/pull/50#pullrequestreview-229531489
