### ISSUE TITLE
Stabilize api.workspace.server.hc.ServerCheckerTest

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13211]
### Description
From time to time ServerCheckerTest fails on ci during `ci-build` job execution with the following error
```
Wanted but not invoked:
testServerChecker.isAvailable();
-> at org.eclipse.che.api.workspace.server.hc.ServerCheckerTest.successfulCheckTest(ServerCheckerTest.java:75)

However, there were exactly 2 interactions with this mock:
testServerChecker.getReportCompFuture();
-> at org.eclipse.che.api.workspace.server.hc.ServerCheckerTest.successfulCheckTest(ServerCheckerTest.java:67)

testServerChecker.start();
-> at org.eclipse.che.api.workspace.server.hc.ServerCheckerTest.successfulCheckTest(ServerCheckerTest.java:73)
```
It is needed to investigate the possible cause of this test instability and fix it by rewriting a test or configure CI infrastructure. I guess the first way should be done since all other tests are quite stable.

**OS and version:**    
CI infra

**Diagnostics:** 
https://ci.codenvycorp.com/job/che-pullrequests-build/org.eclipse.che.core$che-core-api-workspace/6484/
https://ci.codenvycorp.com/job/che-pullrequests-build/org.eclipse.che.core$che-core-api-workspace/6484/testReport/junit/org.eclipse.che.api.workspace.server.hc/ServerCheckerTest/successfulCheckTest/

**Comment by rhopp** [comment]
Can we get this prioritized @l0rd @skabashnyuk? Having unstable build is not good I guess ;-)

**Comment by l0rd** [comment]
ok makes sense to prioritize that
