### ISSUE TITLE
Update vscode-java-debug to latest

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13216]
### Description
The current version of vscode-java-debug extension which we are using in Che plugin is 0.16.0. The reason why we don't use the latest version is because it doesn't work (launching a program does not seem to work).

So, need to update it to latest and test that everything works fine.
It is better to work on this issue when https://github.com/theia-ide/theia/pull/4743 will be merged

**Comment by tsmaeder** [comment]
Latest version is 0.18.

**Comment by svor** [comment]
was updated to 0.19.0
