### ISSUE TITLE
Release latest images for bugfix versions of plugin brokers

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#13213]
### Description
We have an ability to update plugin broker when a bug is found, but when we do a bugfix release of the broker we have to also update Che properties file or, at least, config map/deployment.
Instead of that we could release not only broker version `v0.15.2` but also `v0.15` which would be the latest release of the broker with fixes while still compatible with any other v0.15.x version.
This would basically require only CI improvement.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@riuvshin @ibuziuk @davidfestal @amisevsk WDYT?

**Comment by amisevsk** [comment]
I think it's a great idea, would be very useful rather than tracking down all the che.properties that need to be modified.
