### ISSUE TITLE
Unable to edit Openshift recipe machine in dashboard

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#13218]
### Description
Attempting to edit an OpenShift recipe-based machine fails, wiping out the recipe on edit.

### Reproduction Steps
1. Create Che 7 workspace
2. Go to config tab, change recipe type to "Openshift"
3. Go to machines tab, attempt to edit recipe (change image or memory, etc)
4. Upon save: "Failed: Environment should contain at least 1 pod or deployment"
   - This is because machine has disappeared from the workspace and so it cannot be saved.

On changing recipe in the edit machine dialog, console errors
```
TypeError: Recipe should contain at least one OpenShift object
EnvironmentManager: cannot add machine.
TypeError: Recipe should contain at least one OpenShift object
EnvironmentManager: cannot parse recipe.
TypeError: Recipe should contain at least one OpenShift object
EnvironmentManager: cannot parse recipe.
```
are shown.

**OS and version:**    
Present in `7.0.0-beta-3.0`

**See also:**
https://github.com/redhat-developer/rh-che/issues/1381

**Comment by ibuziuk** [comment]
@l0rd this issue was originally reported in rh-che - https://github.com/redhat-developer/rh-che/issues/1381
Which Che team do you think can take care of it?

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr are we putting this issue on hold since it is not a blocker or IDE 2 team is going to work on this?

**Comment by AndrienkoAleksandr** [comment]
I am ok with hold

**Comment by l0rd** [comment]
@ibuziuk we are replacing legacy stacks.json with their recipes with devfiles (Dashboard should be adapted as a consequence) hence this should be fixed in the process. cc @ashumilova @evidolob
