### ISSUE TITLE
Che plugin registry container image is not pushed to dockerhub

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#13222]
### Description
Currently dockerhub contains 3 month old image of Che plugin registry.
This 3-month old image is used when we start Che using ocp.sh script and option `--deploy-che-plugin-registry`.
We need to setup CI to push updates of the registry image to dockerhub.
We can use automated builds on Dockerhub.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@riuvshin could you configure CI for that?

**Comment by riuvshin** [comment]
che plugin registry is built on CICO [0] and pushed to quay [1]

[0] - https://ci.centos.org/view/Devtools/job/devtools-che-plugin-registry-build-master/
[1] - https://quay.io/repository/openshiftio/che-plugin-registry?tab=tags

we just need to switch to the images that are pushed to quay
