### ISSUE TITLE
Provide an image with Java 11 for remote plugins

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13225]
### Description
Add Dockerfile for an image that can run Theia plugin runner sidecar that depends on Java 11.
Currently we are using an image with Java 8 https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-runner-java8/Dockerfile

**Comment by tsmaeder** [comment]
Not only do we need to provide an image, but also use it in our Java related plugins.

**Comment by svor** [comment]
The image is `eclipse/che-remote-plugin-runner-java11`
