### ISSUE TITLE
Add theia-ide/theia PR check that tests against Developer Sandbox

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13258]
### Description

In [theia-ide/theia](https://github.com/theia-ide/theia) there are a few PR checks including a Gitpod check (see screenshot below). We should add an hosted Che (currently ~~che.openshift.io~~ [Red Hat Developer Sandbox](https://developers.redhat.com/developer-sandbox)) check. This check should:

- create a new `che-theia` image based on the PR source code
- push the image to a container registry
- generate a devfile that uses the PR `che-theia` image as `cheEditor`
- create and start a workspace on Developer Sandbox using the devfile
- run the happy path tests
 
![image](https://user-images.githubusercontent.com/606959/56888625-b6f87e80-6a74-11e9-9dde-643350c694f4.png)

cc @evidolob @benoitf FYI

**Comment by l0rd** [comment]
Changed that to target developer sandbox

cc @ibuziuk @azatsarynnyy

**Comment by l0rd** [comment]
@svor @tsmaeder what do we do with this?

**Comment by ibuziuk** [comment]
potentially related to the story https://github.com/eclipse/che/issues/20155
