### ISSUE TITLE
How to develop against a different Java version than the one in the Java tooling sidecar

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13250]
We include a jdk in the sidecar containin the Java tooling. How do we develop against a differen version of Java? Where do we pick up JDK sources when debugging, for example?

**Comment by tolusha** [comment]
> Where do we pick up JDK sources when debugging, for example?

JDK sources are always picked up from sidecar container even if process is run in another container.

**Comment by tolusha** [comment]
Language Server, Debugger use Java from sidecar container. Actually java from tooling sidecar isn't used except for compiling and running applications.

**Comment by tolusha** [comment]
So, here we need a command in terms of Theia to install another version of java and use it for LS.

**Comment by tsmaeder** [comment]
1. We don't have root, so "install" can only mean unzip somewhere
2. Where would we install the JDK's in order to keep them between restarts?
3. How do we tell the LS and debugger to use that JDK?

**Comment by l0rd** [comment]
You should look at https://github.com/eclipse/che/issues/13387

**Comment by tsmaeder** [comment]
@l0rd I'm not sure this is going to arrive in time for us to use it for GA (end of this sprint)

**Comment by l0rd** [comment]
@tsmaeder correct. @davidfestal should work on that issue but probably not during this current sprint. That was just FYI to be aware and track that work.

**Comment by tsmaeder** [comment]
T.b.h, I don't think that https://github.com/eclipse/che/issues/13387 is really the solution, here: we want to run the tooling on a fixed version of Java (we can test against) and use a different version of Java in the workspace. 
If we could mount a jdk directory (maybe from the dev container) into the tooling container, that would solve the problem, i.m.o.  @l0rd do you think this is possible somehow?

**Comment by tsmaeder** [comment]
VS Code-Java now offers the ability to work against a different JDK than the one that jdt.ls is running on. My idea would be to make init containers that copy a particular version of the JDK to a volume on Workspace creation and point VS Code-Java to that volume. We would only have to use a single plugin to run the language server and could mix and match target platforms.

**Comment by ericwill** [comment]
Duplicate of #16851
