### ISSUE TITLE
Eclipse Che Related Problem

### ISSUE THREAD

**Issue by alphabbet** [eclipse-che/che#13253]
### Eclipse Che related problem

1. For eclipse- che   how to disable downloading the external libraries?
2. How to personalize the custom interface？

**Comment by nickboldt** [comment]
This was opened more than 3 months ago and lacks important details like:

* Che version
* where you installed Che (minishift? minikube? ocp 3.11? 4.1?)
* what do you mean by custom interface?

I'm going to close this issue. Please open a new issue (or perhaps 2 issues) that describe the problem(s) you're having in more depth.
