### ISSUE TITLE
Che 7 workspace selenium test is outdated

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#13255]
### Description
Che 7 selenium test `org.eclipse.che.selenium.theia.Che7PreviewStackStartTest` expects element with ID `theia-app-shell` to be visible automatically after workspace start.
But now test fails. We need to update the test since it will fail all the time on CI.
Error from selenium report:
```
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.id: theia-app-shell' (tried for 240 second(s) with 500 MILLISECONDS interval) Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host: 'slave2.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144' Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
```

Here is how Theia looks when it is shown on a workspace start 
![image](https://user-images.githubusercontent.com/1851863/56860056-c5726780-699a-11e9-9a18-dd0e2f108e18.png)

Needed element in the page code 
![image](https://user-images.githubusercontent.com/1851863/56860139-ba6c0700-699b-11e9-82d5-b16d6c936777.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
I've updated description with more correct description. It is not related to terminal, but test still fails for some reason

**Comment by garagatyi** [comment]
Another error in the same test:
```
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //div[contains(@class, 'theia-app-left')]//ul[@class='p-TabBar-content']//li[@title='Files'] (tried for 10 second(s) with 500 MILLISECONDS interval) Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host: 'slave4.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_144' Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
```

**Comment by garagatyi** [comment]
@vkuznyetsov can @eclipse/eclipse-che-qa team plan to fix this issue? It is important to keep Che 7 in a meaningful state while platform and osio-che teams keep changing workspace interaction with k8s/openshift.

**Comment by garagatyi** [comment]
It can be related to the fact that previously our nightly tests were using 3-month old plugin registry. I've updated it with a new one, so Thiea behavior and/or HTML elements IDs might change.

**Comment by rhopp** [comment]
@garagatyi Hi Alex. We are working hard to write new and better tests for che7 using typescript - I'm hoping we will have something usable (and already better than we have right now in java/selenium) really soon. We decided to invest in java/selenium as little time as possible, but yeah... This might be worth looking at as this is only thing testing che 7 right now :-(

**Comment by rhopp** [comment]
Closing this one as we have first working version of new tests in master - https://github.com/eclipse/che/tree/master/e2e
