### ISSUE TITLE
Hide side panel in custom IDE

### ISSUE THREAD

**Issue by mayadebellis** [eclipse-che/che#13274]
### Description

I am using my own IDE in Che 6. I want to have the option to make the IDE go full screen, or in other words, hide the side panel. This feature exists in the default IDE with a little yellow arrow allowing you to hide/show the side panel. I can't find the code that is controlling this and how I would implement that in my own IDE. If someone could point me in the right direction that would be great. Thank you!

**OS and version:**    
Che 6.16.0

**Comment by fErten** [comment]
@mayadebellis You should just add the [che-plugin-ext-dashboard](https://github.com/eclipse/che/tree/master/plugins/plugin-dashboard) plugin as part of assembly-ide dependency. That should solve your problem.

**Comment by fErten** [comment]
@mayadebellis And I believe it would be better if this plugin can be part of [che-ide-core](https://github.com/eclipse/che/tree/master/ide/che-ide-core) assembly plugin.
