### ISSUE TITLE
Implement compatibility with the new automatic multicast discovery in plugin broker 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13272]
Placeholder for the issue described in comment https://github.com/eclipse/che/issues/12395#issuecomment-470591054

**Comment by ibuziuk** [comment]
@davidfestal could you please provide the description to the issue to identify the scope and share it with the languages team?

**Comment by davidfestal** [comment]
It seems the link to the comment had been lost in the issue description. let me add it back.

And quote @benoitf comment here as well for @tsmaeder : 

> there is now automatic multicast discovery and auto-port assignment for sidecar
so you should just copy plug-ins into /my-plug-ins folder and set THEIA_PLUGINS=local-dir:///my-plug-ins in each sidecar. Main instance of theia will detect endpoint and endpoint will take some random ports automatically

So in the plugin broker, there is no need to manage ports anymore. Only one environment variable should be added to each plugin container with the location where plugin files should be copied (`local-dir:///my-plug-ins`).
This should simplify the plugin broker very much.

**Comment by tsmaeder** [comment]
> This should simplify the plugin broker very much.

I understand this, but if it means self hosting gets broken, I am against using broadcast discovery. I think we should always use a "scope" if we're using auto-discovery.

**Comment by davidfestal** [comment]
@benoitf any idea about whether it might break self-hosting ?

**Comment by tsmaeder** [comment]
I don't really understand why this is a Che 7 GA issue. The current way of doing things works, no?

**Comment by amisevsk** [comment]
@davidfestal Can this issue be closed?

**Comment by ibuziuk** [comment]
Closing as done
