### ISSUE TITLE
Add option to turn off copy and paste

### ISSUE THREAD

**Issue by mpouttuclarke** [eclipse-che/che#1328]
For high security environments and also some education settings we need the ability to turn off copy and paste in the IDE.  Is there a way to do this?  If not, can you add this?

**Comment by james10174** [comment]
@mpouttuclarke Might want to look to see if you can do this in chrome with extension. I see a lot of extensions that can allow copy and pasting on sites that remove the ability. I would think that opposite of restricting copying and pasting would be possible with extensions.

**Comment by TylerJewell** [comment]
We have no plans to offer this customization - it would require modifications until underlying editors that we inherit from.
