### ISSUE TITLE
GWT IDE can't start a workspace created with a devfile

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#13293]
### Description
GWT IDE is not able to start a workspace created with a devfile.

### Reproduction Steps

See https://github.com/eclipse/che/issues/13201

**Comment by monaka** [comment]
Possibly related on #13142 (environment dependent). And it may be required some more patches still I've not published yet.

**Comment by skabashnyuk** [comment]
@akurinnoy Is this issue fixed?

**Comment by akurinnoy** [comment]
@skabashnyuk no, I believe this is the issue for platform team

**Comment by sleshchenko** [comment]
Seems it's outdated since workspaces with GWT IDE are not supported anymore.
