### ISSUE TITLE
[TS-SELENIUM] Create class for interaction with workspace API

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13291]
### Description
For avoiding extra using of UI we should create a class which will provide the next functions by interaction with workspace API:
 - createWorkspace
 - startWorkspace
 - stopWorkspace
 - deleteWorkspace
 - getName
 - getId
 - getIdeUrl

**Comment by sunix** [comment]
@vkuznyetsov @Ohrimenko1988 could you update the status of this issue ?

**Comment by Ohrimenko1988** [comment]
PR waits for CQ
But we change our approach so maybe we will not merge PR
@rhopp what do you think about that?

**Comment by rhopp** [comment]
@Ohrimenko1988 I would say this PR is a bit obsolete now... My opinion would be to close this issue&PR.
