### ISSUE TITLE
Add information about volumes in workspace runtime

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13290]
### Description
Frontend part of Che often uses information about running workspace components.
For example, we have workspace panel which shows information about current set of containers and their properties. Other services may use the information to correctly suggest options to choose for user.
Most of the described values above we have in workspace runtime configuration, but exception is volumes information.  We need to have volumes list of each container of the running workspace including volume name and mount point inside container.
It will be great to have a flag that shows if volume is added by user directly.

**Comment by AndrienkoAleksandr** [comment]
+1 For this feature. We want to use volume information for current working directory terminal feature.

**Comment by AndrienkoAleksandr** [comment]
I applied todo https://github.com/eclipse/che-theia/pull/115 to improve this feature when volume information become available from workspace#runtime

**Comment by mmorhun** [comment]
Also needed for https://github.com/eclipse/che/issues/13112

**Comment by skabashnyuk** [comment]
>Also needed for #13112


@mmorhun please explain why. I can't find any references to volumes in https://github.com/eclipse/che/issues/13112

**Comment by mmorhun** [comment]
@skabashnyuk https://github.com/eclipse/che/issues/13112 says that we need to support devfile as main source of workspace configuration. Which means we need to rework existing components to be able to use devfile and have the same user experience.
One of such components to rework is workspace panel which holds information about Che workspace including volumes for each container. When workspace config is used to create Che workspace the task is pretty easy: just get volumes records from it (yes, a bit of cheating). But in case of workspace which is created from devfile we cannot do it without really complicated logic, which I believe not client side task at all. Also relaying on raw workspace config to show runtime information is not a good practice. So, that's why we need information about volumes in runtime for that issue.

**Comment by skabashnyuk** [comment]
CC @l0rd is this something in our roadmap?

**Comment by l0rd** [comment]
With devworkspace engine this should not be required anymore.
