### ISSUE TITLE
Version prefixes in `package.json` should be `~` instead of `^` ?

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13298]
### Description
I noticed this on reviewing #13295.

Referring to [Contribution Questionnaire](https://wiki.eclipse.org/Development_Resources/Contribution_Questionnaire), patch releases are not required review.

> Per board resolution, service releases of third party libraries do not generally require review.

And referring to [the NPM official document](https://github.com/npm/node-semver#caret-ranges-123-025-004), `^` accepts their minor versions. So `npm` may add unapproved versions if the version range specification with `^`.

I think all version ranges in `package.json` should be prefixed by `~` ([refs](https://github.com/npm/node-semver#tilde-ranges-123-12-1)) instead of `^`. 

All package.json should be patched?

**Comment by gorkem** [comment]
@waynebeaton WDYT? I suppose this is a best practice we should add to project documentation.
