### ISSUE TITLE
Plugins installation process timed out with vscode-kubernetes-tools/0.1.17

### ISSUE THREAD

**Issue by disaster37** [eclipse-che/che#13299]
### Description
When I enable the plugins vscode-kubernetes-tools/0.1.17 on my workspace, I get the following error `Error: Failed to run the workspace: "Plugins installation process timed out"`.

I look the is take a long time to unzip the plugins (aka du -sh * on /tmp inside the plugins containers).

The are any parameters to increase the timeout to process plugins ?

### Reproduction Steps
Just enable the plugins vscode-kubernetes-tools/0.1.17 on little server

**OS and version:**    
Debian 9, with kubernetes 1.13.5 and che 7.0.0-beta-5.0-SNAPSHOT

**Diagnostics:** 

The plugins container have no time to finish to unzip the kubernetes vs code plugins.

**Comment by amisevsk** [comment]
Thanks for creating an issue. 

Timeout for plugin processing can be set by adding the env var `CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN` on the che-server pod (or via configmap -- depends on how you deployed Che).

However, the default of 3 minutes should be plenty (the plugin broker rarely goes for longer than 30 seconds when I run it), which makes me suspect there are other issues at play. What method did you use to deploy Che?

**Comment by disaster37** [comment]
Hi,
I deploy CHE on kubernetes (Rancher) from helm with the following settings:

```yaml
global:
  multiuser: true
  cheNamespace: che
  cheWorkspacesNamespace: che
  ingressDomain: XXX.XXX.XXX.XXX.nip.io
```

I also need to change configmap with the following value `CHE_INFRA_KUBERNETES_PVC_STRATE=unique` because of I use ceph RDB as storage provider (rook-ceph). It not support to mount the same PVC on multi pods as same time...

**Comment by amisevsk** [comment]
Hm, in that case, I'm stumped; I just tested it with `vscode-kubernetes-tools/0.1.17` on one of our clusters and brokering took ~30 seconds.

1. Does this only affect the `vscode-kubernetes-tools/0.1.17` plugin, or are others similarly impacted?
2. Could you share the full log printed to the screen when starting the workspace? It should start with 
   ```
   Cleaning /plugins dir
   Starting Init Plugin Broker
   Unified Che Plugin Broker
   Starting Che common plugins processing
   ```
3. Does it still occur if you use an `ephemeral` workspace? You can toggle ephemeral mode in the "Overview" page when configuring the workspace. This uses `emptyDir` volumes instead.

Apart from that I can't reproduce this. @eivantsov any ideas?

**Comment by disaster37** [comment]
Hi,

the following logs:
```
Starting Init Plugin Broker
Cleaning /plugins dir
Unified Che Plugin Broker
List of plugins and editors to install
- eclipse/che-machine-exec-plugin/0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- redhat/vscode-yaml/0.4.0 - Provides comprehensive YAML Language support to Visual Studio Code, via the yaml-language-server, with built-in Kubernetes and Kedge syntax support.
- ms-kubernetes-tools/vscode-kubernetes-tools/0.1.17 - Develop, deploy and debug Kubernetes applications
- eclipse/che-theia/1.0.0 - Eclipse Theia
Starting Che common plugins processing
Starting VS Code plugins processing
Downloading VS Code extension for plugin 'redhat/vscode-yaml/0.4.0'
Starting Theia plugins processing
Downloading VS Code extension for plugin 'ms-kubernetes-tools/vscode-kubernetes-tools/0.1.17'
Error: Failed to run the workspace: "Plugins installation process timed out"
```

For moment, the problem is only for vscode-kubernetes-tools/0.1.17. No problem with yaml plugins or golang plugins.

It's the same with ephemeral mode

**Comment by gorkem** [comment]
I have quickly compared the unzip times of the kubernetes extension and java extension on MacOS and it feels like java extension is much faster although it is a 3 times larger archive file.

**Comment by eivantsov** [comment]
Is there anything in broker pod logs? And yes, downloading k8s plugin binary takes longer for me too.

**Comment by gorkem** [comment]
Pinged the kubernetes extension committers. This is also something they have noticed. https://github.com/Azure/vscode-kubernetes-tools/issues/542

**Comment by amisevsk** [comment]
Upstream issue is still open.
