### ISSUE TITLE
How to delete a running workspace?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#133]
I want to delete a running workspace, but show this error:

> Failed! Can't remove running workspace workspace50isjk211hvsadni

How can I do it?

**Comment by TylerJewell** [comment]
Stop the workspace in the IDE and then delete from the dashboard.

-Tyler

On Sun, Dec 20, 2015 at 8:19 PM -0800, "freewind" notifications@github.com wrote:

I want to delete a running workspace, but show this error:

Failed! Can't remove running workspace workspace50isjk211hvsadni

How can I do it?

**Comment by ghost** [comment]
Closing the issue. The error Che gives is quite informative.
