### ISSUE TITLE
Terminal text overlap themself when more than 80 symbols in the row

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13306]
### Reproduction Steps
 - Go to workspace and launch workspace using "Che 7" stack
 - After workspace launched, open terminal and try to type in it
 - Pay attention that after reaching 80 symbols in the row text become overlap 

**Expected behavior:**
Typing will be proceed

**Observed behavior:**
After reaching 80 characters, text become overlap

**Attachment:**
![Peek 2019-05-10 16-43](https://user-images.githubusercontent.com/22724619/57531752-d3cd6580-7342-11e9-92f5-45ca64329ca0.gif)

**OS and version:**    
Che 7.0.0-beta-5.0-SNAPSHOT ; Fedora 20 ; Chrome 73

**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
@Ohrimenko1988 for such issues define, please, che-theia version from about dialog.

**Comment by Ohrimenko1988** [comment]
@AndrienkoAleksandr Thank you for feedback.
![Screenshot from 2019-05-24 15-55-44](https://user-images.githubusercontent.com/22724619/58329151-8b32a380-7e3c-11e9-9223-6086b1c57602.png)
