### ISSUE TITLE
Devfile validator is broken.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13302]
### Description

Devfiles can't start under ephemeral mode.

```
attributes:
  persistVolumes: false
```

Che accepts fixed devfiles like below. But this is not expected behavior.

```
attributes:
  persistVolumes: "false"
```

This issue is not critical for many users. But it will be a blocker for some kinds of users (like school, demonstration).
So I added severity/P2 tag.
 
### Reproduction Steps

Start `https://che-host/f?url={url-to-devfile}

The devfile contains the attribute below.
 
```
attributes:
  persistVolumes: false
```

**OS and version:**    

7.0.0-beta-4.0-SNAPSHOT

I can't check under 7.0.0-beta-3.0 or before. Since the spec devfile is changed. 

**Diagnostics:** 

![Screenshot 2019-05-10 at 16 40 57](https://user-images.githubusercontent.com/101795/57510985-12632000-7343-11e9-860d-b5725188ae3b.png)

**Comment by monaka** [comment]
I created a test case and inspected this line.

https://github.com/eclipse/che/blob/81f3613c3405641479447f1eede8afda94578e71/wsmaster/che-core-api-devfile/src/main/java/org/eclipse/che/api/devfile/server/validator/DevfileSchemaValidator.java#L63

The value of `jsonWriter.writeValueAsString(contentNode)`

```
{"specVersion":"0.0.1","name":"persistvolumes-should-be-typed-as-boolean","attributes":{"persistvolumes":false}}
```

Should be `"false"`. But actually `false` (without double quotes).
Looks a bug in `com.fasterxml.jackson.databind.ObjectMapper` ?

**Comment by monaka** [comment]
It looks the issue on Jackson is famous (refs https://stackoverflow.com/questions/19678340/how-to-serialize-boolean-to-json-as-strings-using-jackson ).
Yesterday I tried to patch but I couldn't fixed it.

And IMO, we should replace Jackson to Kwalify or Rx or something.
the currenct validator won't detect which the value of `persistentVolume` in YAML was `"false"` or `false`.

**Comment by skabashnyuk** [comment]
@mshaposhnik can you comment?

**Comment by mshaposhnik** [comment]
Hello @monaka. I have created test PR where I added new devfile example, which seems to run OK.
Can you modify it to reproduce the error? 
[1] https://github.com/eclipse/che/pull/13368/files

**Comment by mshaposhnik** [comment]
UPD-2: updated PR, it can accept now any of boolean or string attribute type.  When java object is created, it is implicitly converted to string. The only disadvantage of this apporach is that users may be suprised seeing his boolean property is converted to sting (but i don't think is is a big problem). @skabashnyuk WDYT, can we accept such a fix ?

**Comment by monaka** [comment]
@mshaposhnik I saw PR #13368. Does that modify to accept both `"false"` (string) and `false` (booolean) in YAML ?  If so, I agree it will pass tests. But ... does it fit to YAML style?

**Comment by monaka** [comment]
I close this and move to #14131.
