### ISSUE TITLE
Node server can't be launched inside of "Che-7" container

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13304]
### Reproduction Steps
 - Go to dashboard and create workspace by using "Che 7" stack and "nodejs-hello-world".
 - Launch workspace and wait until started
 - Open terminal
 - Go to "nodejs-hello-world" dir
 - Perform command "npm install && node . "

**Expected behavior:**
The server is launched and listen for a defined port.

**Observed behavior:**
Server launch failed because of unexposed port

**OS and version:**    
Che 7.0.0-beta-5.0-SNAPSHOT

**Attachment:**
![Screenshot from 2019-05-10 11-58-48](https://user-images.githubusercontent.com/22724619/57517728-2b0e0e80-7320-11e9-8710-a5dab72737ad.png)

**Comment by Ohrimenko1988** [comment]
If change "editor" to "eclipse/che-theia/next" in the workspace config, the node server launch works as expected. Thank @sunix for help.
![Screenshot from 2019-05-10 12-20-46](https://user-images.githubusercontent.com/22724619/57518044-dae37c00-7320-11e9-9618-29f676c2f982.png)

**Comment by sleshchenko** [comment]
@Ohrimenko1988 Now next should be default https://github.com/eclipse/che/pull/13235.
Should this issue be closed?

**Comment by Ohrimenko1988** [comment]
In my opinion, it may be closed.
