### ISSUE TITLE
PHP Stack

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13307]
Make a PHP stack with examples as described in #12620
- [x] the stack: [PHP official image](https://hub.docker.com/_/php) + [PHP LS](https://github.com/eclipse/che/issues/12772)
  - [x] sample1: [Hello World](https://github.com/che-samples/web-php-simple)
  - [x] sample2: [Laravel Real World example App](https://github.com/gothinkster/laravel-realworld-example-app)
  - [x] sample3: [Symfony demo application](https://github.com/symfony/
  - [x] sample4: [Sample CRUD PHP+MySQL](https://github.com/taniarascia/pdo/tree/master)

**Comment by svor** [comment]
As an image I've tried to use [php:7-apache](https://github.com/docker-library/php/blob/85b2af63546309c3c7b895524db10ef02aa4edba/7.3/stretch/apache/Dockerfile) which contains Apache Web server which is needed for samples ([Hello World](https://github.com/che-samples/web-php-simple)). 
I faced next problems:
1. Apache Server can not be started: Permission denied: make_sock: could not bind to address [::]:80. To solve this problem I need to edit the configuration in `/etc/apache2` folder, but I can't do that in minishift (have no permissions) 
2. Some of samples for example sample2 require to install some packages, at least I need to install [composer](https://getcomposer.org/)  which is Dependency Manager for PHP and I also can not do that because of permissions.

I think all these problems we can solve by creating new image to extend official and make all needed changes in our Dockerfile. 
@l0rd @tsmaeder Should I start to do that or we must use only official image?

**Comment by l0rd** [comment]
@svor your problem is the same problem we have faced for other stacks: the official images that we found on docker hub are not suited for development on an unprivileged kubernetes pod (i.e. the default on openshift). 

I would like to avoid to create and maintain a new PHP image and my recommendation would be to look at the official s2i image https://github.com/sclorg/s2i-php-container that are designed to be run on unprivileged pods. That image should be just fine to run the PHP LS.

Anyway it's not clear from your description but what we agreed with @tolusha is that you should use 2 separate containers: one for the LS and one for runtime container (aka the recipe). The image can be the same (i.e. the official s2i image) or, if your runtime container needs some prerequisites that are not in the LS image, you can create a custom image that use the LS image as it's base image (i.e. `FROM <php-s2i-image>`

**Comment by svor** [comment]
After my investigation I think we can't just reuse existing official image: https://hub.docker.com/r/centos/php-70-centos7 or https://hub.docker.com/_/php because of:
 - https://hub.docker.com/r/centos/php-70-centos7 - it requires to use source-to-image (S2I) toolkit to build and provide ready to run docker image, so, I don't think we can use this image for our runtime container
 - https://hub.docker.com/_/php - this image doesn't contain some utilities to build php applications (for example php composer) and also Apache configuration should be overridden to make it possible to preview samples and we can do that by extending this image. 
That's why I decided to create custom image that use https://hub.docker.com/_/php as it's base image - here we have an ability to reconfigure Apache server and install what we need

**Comment by l0rd** [comment]
@svor I don't see any other alternative so let's proceed this way

**Comment by svor** [comment]
@l0rd All samples except HelloWorld require database. As I understand the database should be run in a different container. In that case for me isn't clear how to create workspace config with two containers (dev-container and another one with db).  Do we already have some example or maybe some docks for that?

**Comment by l0rd** [comment]
@svor correct. But I would use 2 different stacks: `PHP` and `PHP with MySQL` (or whatever db you are going to use). For reference I was using the following recipe for Java Postgres:

```json
        "recipe": {
          "content": "apiVersion: v1\nkind: List\nitems:\n- apiVersion: apps/v1\n  kind: Deployment\n  metadata:\n    labels:\n      name: java-postgres-stack\n    name: java-postgres-stack\n  spec:\n    replicas: 1\n    selector:\n      matchLabels:\n        name: java-postgres-stack\n    template:\n      metadata:\n        labels:\n          name: java-postgres-stack\n        name: java-postgres-stack\n      spec:\n        containers:\n        - image: postgres\n          name: postgres\n          ports:\n          - name: postgres\n            containerPort: 5432\n            hostPort: 5432\n        - image: maven\n          command: ['sleep']\n          args: ['infinity']\n          name: maven\n          ports:\n          - containerPort: 8080\n            name: http-server\n",
          "type": "kubernetes",
          "contentType": "application/x-yaml"
        }
```
