### ISSUE TITLE
Dashboard menu items are not aligned

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13309]
### Description

In the left menu of the dashboard elements are not all left aligned anymore

![image](https://user-images.githubusercontent.com/606959/57534910-5fde8d80-7341-11e9-829a-7eb6afc68ec9.png)

cc @ashumilova @evidolob

**Comment by amisevsk** [comment]
Also seeing this. Can't see a reason for this to occur when inspecting the page, and it only occurs using Chrome (`Version 74.0.3729.131`), not Firefox.

**Comment by olexii4** [comment]
Cannot reproduce on Eclipse Che v7.0.0 and higher
