### ISSUE TITLE
Problem View (and Markers)

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-che/che#1330]
Errors in non-open editors should be shown on files in the project tree and in a dedicated problems view. AFAIU problems are only shown in open editors at the moment.

**Comment by svenefftinge** [comment]
Making this an LS ticket for now, as we have a concrete client that would produce these errors and warnings on non-open files.

**Comment by TylerJewell** [comment]
Closing for now - issue is valid, but it will be a longer term implementation item and we will open an epic once we have a good design for this.
