### ISSUE TITLE
How to create workspace into my organization by Devfile?

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13312]
### Description

This is just a question.
I want to create my workspace by `devfile.yaml` into the organization I belong.
How can I do?

**OS and version:**    

Che 7.0.0-beta-5.0-SNAPSHOT

**Comment by AndrienkoAleksandr** [comment]
@mshaposhnik could you help with this question?

**Comment by sleshchenko** [comment]
Now, it's only possible with Beta method in WorkspaceService [1] that is not stable yet.
But also I wonder why we do not have an ability to accept factory to an organizational but not to a personal account. If you use organizations and such feature may be useful for you, feel free to open an issue. Maybe we have such an ability, have you tried to accept factory with github repo? ->
1. Make sure you have is member of organization.
2. Push devfile.yaml to github repository, like Che repo has `https://github.com/eclipse/che/blob/master/devfile.yaml`
3. Open `CHE_HOST/f?url=http://github.com/eclipse/che`
Then I expect that dashboard asks where workspace should be created if the user is a member of any organization.

[1] https://github.com/eclipse/che/blob/e4e12df1be0faaa47fb1f16ab4f5207890523563/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L193

**Comment by monaka** [comment]
Yes, I'm using devfile.yaml on GitHub repo via `CHE_HOST/f?url=` endpoint.

> Then I expect that dashboard asks where workspace should be created if the user is a member of any organization.

Good design.
At the same time, `CHE_HOST/f?org={organization}&url=` may be considerable also.

**Comment by sleshchenko** [comment]
> Good design.
> At the same time, CHE_HOST/f?org={organization}&url= may be considerable also.

@monaka please create feature request. Also feel free to contribute it =)

**Comment by monaka** [comment]
@sleshchenko Thank you for your reply. I'll think about the function and the interface.
And I close this issue as I got the answer for my first question.
