### ISSUE TITLE
Add toleration provisioner to Kubernetes infrastructure.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13319]
### Description

they have a connector to managed container instance on some managed Kubernetes.
For example, Azure AKS have a connector to ACI. AWS also have a similar service.
 
It will provide high scalability to Che by supporting the connector.

AFAIK, such connectors is added as _tainted_ node to the cluster.
So Che needs to send `Deployment` request with `toleration:` for deploying pods to managed container instances.

At the same, some Che admins may avoid to use managed container services.
 Because, comparing to VM instances, such services will have some restrictions.

So this support should be configurable.

**Comment by davidwindell** [comment]
Yes please! Can we get this moved out of draft?

**Comment by monaka** [comment]
@davidwindell Thank you for heads up. I moved it out of draft just now.

**Comment by davidwindell** [comment]
@monaka why did you close this issue? We really would like to be able to set tolerations for our workspaces. Should I raise a new issue?

**Comment by amisevsk** [comment]
@davidwindell A late update here: https://github.com/eclipse/che/pull/18691

**Comment by davidwindell** [comment]
Awesome

**Comment by cccs-eric** [comment]
@davidwindell 
https://github.com/eclipse/che/pull/18691 has been merged into master.

**Comment by davidwindell** [comment]
Thanks for the update!
