### ISSUE TITLE
[k8s plugin] Kubernetes:Run command should work w/o Docker

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#13316]
The Kubernetes Tooling Che Plugin provides `Kubernetes: Run` command that does the following steps:
- builds a project image with `docker build`
- pushes the built image to an image registry with `docker push`
- creates a K8s deployment to run a pod with a container from the built image with `kubectl run`

Previously, the user should log into an image registry with `docker login`.

Since we can't use Docker daemon in a plugin sidecar, the goal of this task is to replace using Docker by the K8s Plugin with some rootless image build tool, e.g. Buildah.

**Comment by azatsarynnyy** [comment]
I've experimented with Buildah [here](https://github.com/eclipse/che-theia/compare/k8s-run) by wrapping its calls into `docker.sh` script placed under `/usr/local/bin` to make it accessible from `$PATH`.
So the K8s Plugin still calls `docker` but the script calls the corresponded `buildah` commands.

**Comment by azatsarynnyy** [comment]
`buildah login` command has been [added](https://github.com/containers/buildah/commit/59da11d4b4df6c9b51d06fc804f7a2e46be6c700) in the latest version - 1.8.2. But it's not available yet in CentOS (parent image for the K8s Plugin) app repos.
Likely, it will be published after the summit https://github.com/containers/buildah/issues/1557#issuecomment-490134818
I'll try with the containerized Buildah from https://quay.io/buildah/upstream

**Comment by gorkem** [comment]
@azatsarynnyy Can we change the extension itself to use buildah commands instead of the wrapper? I can discuss it with the extension owner if you think you can provide a PR for it.

**Comment by azatsarynnyy** [comment]
@gorkem it shouldn't take much time to add support for `buildah` as an alternative image builder in the VS Code K8s extension. So, if guys are interested in such a contribution, I can provide PR.

**Comment by gorkem** [comment]
@azatsarynnyy Can you provide a PR to upstream and ping me. Perhaps something that detects if buildah exists or docker not working and opts to the other.

**Comment by azatsarynnyy** [comment]
@gorkem ok, I'll tackle it next week

**Comment by azatsarynnyy** [comment]
Reopening it to work on adding Buildah support to VS Code Kubernetes Tools extension upstream project.

**Comment by azatsarynnyy** [comment]
Buildah support has been added to VS Code Kubernetes extension https://github.com/Azure/vscode-kubernetes-tools/pull/559

It's included to the recently published [v1.0.1](https://github.com/Azure/vscode-kubernetes-tools/pull/570/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR5)

The next steps are:
- [ ] add a new version of the [Kubernetes Tooling Che Plugin](https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools) based on the VS Code Kubernetes Tool v1.0.1
- [ ] get rid of the [wrapper script](https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-kubernetes-tooling-1.0.0/etc/docker.sh) in the plugin [Dockerfile](https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-kubernetes-tooling-1.0.0/Dockerfile#L18)
- [ ] update the plugin's [README](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/README.md) file with the info how to switch image build tool from Docker to Buildah

**Comment by azatsarynnyy** [comment]
Fixed for K8s in https://github.com/eclipse/che-theia/pull/510
For OpenShift, will be a separate issue if needed.
