### ISSUE TITLE
Console font letters get cut

### ISSUE THREAD

**Issue by krequena** [eclipse-che/che#13317]
### Description
After importing a project whose name contains a lower-case "F", I have seen it gets cut on the topmost pixel - or so it seems. Happens with more letters, too.

### Reproduction Steps
1. Import this GitHub project: https://github.com/krequena/eamodeltransfer.git
2. Open the console.
3. cd eamodeltransfer
4. mvn clean install

The output of the console shows several occurences of "cutted" letters. Please see attached screenshot.
[http://imgbox.com/RrEfhvX6](http://imgbox.com/RrEfhvX6)

**OS and version:**    
Linux - Gentoo x64.
Eclipse Che 7.0.0-beta-4.0
Firefox 60.6.2esr 73.0.3683.75 x64.
Chromium x64.

**Diagnostics:**

**Comment by evidolob** [comment]
Can we close this? As we do not support of Che6.
