### ISSUE TITLE
Single-user deploy on OCP 4 fails to create workspaces

### ISSUE THREAD

**Issue by siamaksade** [eclipse-che/che#13328]
When deploying a single-user Che on OCP 4 using the [deploy_che.sh](https://github.com/eclipse/che/blob/master/deploy/openshift/deploy_che.sh) script, it deploys successfully but fails to create workspaces:

```
Press F5 or click here to try again.
Error: Failed to run the workspace: "Waiting for persistent volume claim 'claim-che-workspacem6chwsb4' reached timeout"
```

Che logs doesn't show anything specific:
```
2019-05-13 14:33:52,361[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 605]    - Workspace 'che/wksp-x3c4' with id 'workspace52yg1ly9b5mn919y' created by user 'che'
2019-05-13 14:33:54,851[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 366]   - Starting workspace 'che/wksp-x3c4' with id 'workspace52yg1ly9b5mn919y' by user 'che'
```

And the project contains these events:
```
105s        Normal    WaitForFirstConsumer             persistentvolumeclaim/claim-che-workspace0aga7f93   waiting for first consumer to be created before binding
105s        Normal    WaitForFirstConsumer             persistentvolumeclaim/claim-che-workspacebc0o1e3b   waiting for first consumer to be created before binding
105s        Normal    WaitForFirstConsumer             persistentvolumeclaim/claim-che-workspacehwlknr0y   waiting for first consumer to be created before binding
105s        Normal    WaitForFirstConsumer             persistentvolumeclaim/claim-che-workspacem6chwsb4   waiting for first consumer to be created before binding
```

Che version is 7.0.0-beta-5.0-SNAPSHOT

**Comment by l0rd** [comment]
@siamaksade the default way to install Che on OpenShift 4.0 is through an Operator. You should be able to do it from the marketplace once [this PR](https://github.com/operator-framework/community-operators/pull/280) get merged. In the meantime this [script](https://github.com/eclipse/che-operator/blob/master/deploy.sh) should help.

**Comment by siamaksade** [comment]
How can I install Che in single-user mode via the operator?

**Comment by bryantson** [comment]
Encountered the same issue, and the event on PVC shows the same "waiting for first consumer to be created before binding" and the status is pending.

**Comment by amisevsk** [comment]
"Waiting for first consumer" should be fixed in the next release: https://github.com/eclipse/che/pull/13409

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/14239. If no - please register a new issue.
