### ISSUE TITLE
Run E2E Happy path tests as PR check on che-theia repository

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13326]
### Description
We should create PR check job on https://github.com/eclipse/che-theia running happy path test with che-theia from PR.

HowTo build che-theia:
https://github.com/eclipse/che-theia/blob/master/build.sh --pr

Nightly build job https://ci.codenvycorp.com/job/che-theia-master-ci as an example.

**Comment by musienko-maxim** [comment]
PR checker was implemented in the https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PR-check-on-CHE-Theia-experemental/  - job. But for correct building of the Che-Theia images we need merging of the PR: https://github.com/ws-skeleton/che-theia-generator/pull/26

**Comment by l0rd** [comment]
@musienko-maxim @rhopp just to confirm: you want to set the PR check on master branch, even if `7.0.0` work on che-theia is happening on branch `7.0.0` right? I am ok with that (if we protect `master` branch we will protect branch `7.0.0` as well) but I just wanted to double check it.

**Comment by musienko-maxim** [comment]
On this moment the job is set up for checking `master` branch

**Comment by nickboldt** [comment]
Partially complete for 7.0; slip completion of issue to milestone 7.1

**Comment by rhopp** [comment]
Job is ready. https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved 
@dmytro-ndp Please create a followup issue for transforming this job into pipeline (and include it into current sprint). Thx ;-)
