### ISSUE TITLE
Multi-user Che on kubernetes fails on postgres container creation: '/var/lib/pgsql/data/userdata': Permission denied

### ISSUE THREAD

**Issue by mikekuzak** [eclipse-che/che#13344]
I still have the same problem when deploying Che to K8s. 

`Initial call to run-postgresql...
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
pg_ctl: directory "/var/lib/pgsql/data/userdata" does not exist
Initializing Che user...
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Warning: Failed initializing the Che user and database
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
pg_ctl: directory "/var/lib/pgsql/data/userdata" does not exist
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied`

Used helm chart from master:
helm upgrade --install che-eclipse --namespace che-eclipse -f ./values/multi-user.yaml ./

postgres-data PVC has been bound

_Originally posted by @mikekuzak in https://github.com/eclipse/che/issues/11831#issuecomment-492705750_

**Comment by mikekuzak** [comment]
The underlying OS did not have UID 26 write permission to the mounted folder

**Comment by SDAdham** [comment]
I think I am also experiencing similar issue but with permissions for postgres (shall I create a new issue?):
```
Initial call to run-postgresql...
chmod: changing permissions of '/var/lib/pgsql/data/userdata': Operation not permitted
pg_ctl: could not open PID file "/var/lib/pgsql/data/userdata/postmaster.pid": Permission denied
Initializing Che user...
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Warning: Failed initializing the Che user and database
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
pg_ctl: could not open PID file "/var/lib/pgsql/data/userdata/postmaster.pid": Permission denied
chmod: changing permissions of '/var/lib/pgsql/data/userdata': Operation not permitted
```
