### ISSUE TITLE
Initial setup of Che Defvile registry

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13353]
### Description
- [x] Create a repository in che-incubator until we will have eclipse/che-devfile-registry in place
- [x] Setup images build
- [x] Adjust Che deployment scripts in the same way as we have with plugin registry.
- [x] Add ability to get devfile registry from API.
- [x] Add Che7 stacks to this registry from stacks.json

**Comment by gorkem** [comment]
@deboer-tim I think you had some ideas on how to organize stacks in a registry. This is the moment to voice them :)

**Comment by deboer-tim** [comment]
Gorkem - Sorry for the delayed response, was on vacation when the notification came and it got buried. Mario setup a call on Friday, we'll discuss there.
