### ISSUE TITLE
Preview URL not displayed while accessible

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13357]
### Description
While I've been able to access the previewURL and it is accessible. The preview panel is not rendering the URL properly.
See attached screenshot:

![Capture d’écran 2019-05-17 à 11 57 35](https://user-images.githubusercontent.com/1636769/57920395-340c5c00-789b-11e9-9d8a-1db93c6c98cd.png)

### Reproduction Steps
1. Java-Maven Stack + vertx-http-booster
2. run task "run"

**OS and version:**    

**Diagnostics:**

**Comment by akurinnoy** [comment]
hello @slemeur 
I'm confused a bit with the description. 
Could you please elaborate on it? Where is the bug? What is expected behavior?

**Comment by slemeur** [comment]
Check in the previewURLs panel. 
It seems that  `${server.8080}/tcp` which is not compute properly.

**Comment by akurinnoy** [comment]
I thought the same. But yesterday I discussed this with @RomanNikitenko and found out that it was done deliberately. The reason was to not show there the whole URL which may be too long to fit the panel.

**Comment by slemeur** [comment]
Then what's the benefit to the end-user to see that information? 
Let's just display the proper URL, make it clickable and truncate it if it's too long. Consider displaying the full URL on hover in a tooltip.

**Comment by akurinnoy** [comment]
yes, that makes sense to me
thanks!

**Comment by RomanNikitenko** [comment]
The behavior came from task extension when I was reworking this one to plugin.
But I think the point was to match server defined from dashboard
![server](https://user-images.githubusercontent.com/5676062/59831390-60a80d80-934a-11e9-8725-4d0196aaee76.png)
So user define some server in a config and can see it on the panel

**Comment by slemeur** [comment]
I think it's going to be confusing for the end-user. He might even not understand where this is coming from and there is no way to edit/configure that information. 

As a user, when I run a task that is starting a process with a previewURL associated, I'm intending to find a place where I can see the previewURL (and all the ones started). 
Also, as a user, seeing the panel for PreviewURLs, I'm intending to see the previewURLs, not the servers. 
Also, as a user, I'd also be interested to find information about the task and the server related to the previewURLs - but those are secondary information.

**Comment by sleshchenko** [comment]
@slemeur Looks like it's a good time to raise the issue that commands in Devfile do not support preview URLs. So, the described issue may be not actual for Che 7 with Devfiles or maybe it's needed to create an issue to support previewURL in commands of devfile.

**Comment by RomanNikitenko** [comment]
@slemeur I don't mind, I just explained the history of this question...
