### ISSUE TITLE
Deploy and use public che devfile registry on https://che.openshift.io infrastructure

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13355]
### Description
As part of this epic https://github.com/eclipse/che/issues/12924 we are going to introduce new devfile registry https://github.com/eclipse/che/issues/13353.
The goal of this task would be to deploy and use public che devfile registry on https://che.openshift.io infrastructure similar to the plugin registry.

**Comment by sleshchenko** [comment]
PR for deploying Che Devfile Registry on OpenShift.io https://github.com/openshiftio/saas-openshiftio/pull/1285
PR for making che-devfile-registry available publicly on OSIO https://gitlab.cee.redhat.com/service/app-interface/merge_requests/652

**Comment by sleshchenko** [comment]
Blocked by job on CentOS CI that is not run yet https://ci.centos.org/job/devtools-che-devfile-registry-build-master/. Asked SD team to help find a cause.
