### ISSUE TITLE
Important consumtion of resources by the browser when using Theia

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13360]
### Description
When using Che, with Theia, the resources consumed by the browser are getting really high.

When doing a maven build:
![Capture d’écran 2019-05-17 à 12 06 04](https://user-images.githubusercontent.com/1636769/57924518-95392d00-78a5-11e9-9dd8-191c1f9d5667.png)

After the build ended:
![Capture d’écran 2019-05-17 à 12 08 52](https://user-images.githubusercontent.com/1636769/57924538-a3874900-78a5-11e9-921b-21b4a79ee357.png)

### Reproduction Steps
1. Create a workspace with stack Java-Maven, add vertx sample
2. Start a build from the terminal with the cmd `mvn clean install` 
3. Check browser resources used
4. Start a build using the pre-defined tasks
5. Check browser resources used
6. Once build done, check again the resources.

**OS and version:**    
MAC OS X 10.14.5
Chrome Version 74.0.3729.157
**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
Should be fixed after https://github.com/eclipse/che-theia/pull/223

**Comment by AndrienkoAleksandr** [comment]
I checked with reproduction steps. Fixed.
