### ISSUE TITLE
Application preview URL becomes unavailable

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13362]
### Description
**Preconditions:**
*Clone ecllipse-che project and run Openshift cluster locally (go to the just cloned project) and launch command like: `[your_path]/che/deploy/openshift/ocp.sh --run-ocp --deploy-che -p=che`
### Reproduction Steps
* We should create workspace with chectl and dev. file. Download `chectl` tool binary file with comannd:  `https://github.com/che-incubator/chectl/releases/latest/download/chectl-linux`
* Export 2 variables: 
**export CHE_WORKSPACE_JAVA__OPTIONS="-Xmx1500m"**
**export CHE_WORKSPACE_MAVEN__OPTIONS="-Xmx1500m"**
I need like workaround for the known bug: https://github.com/eclipse/che/issues/13340
* Save the **DevFile** (in attachment),  and create workspace using command like `./chectl-linux workspace:start --devfile=devfile.yaml`
* Consume just created link after creating the wokkspace and launch terminal for the petclinic container. (**Terminal** -> **Open Terminal in specific container** -> select `petclinic-server`).
* Run command in the terminal: `java -jar /spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar --spring.profiles.active=mysql`. for avoiding problem with the issue: https://github.com/eclipse/che-theia/issues/192
* Confirm notification with label ***A new process is now listening on port 8080 but this port is not exposed in the workspace as a server.
Would you want to add a redirect for this port so it becomes available ?*** open link.
* Go to app with link do some changes, for instance add a new owner in the application
**Expected results:** The application should works and should be avaliable
**Actual results:** We get Application is not available page. See also screencast with steps to reproduce

* Launch command in the terminal for avoiding issue:
**OS and version:**    Fedora 29, Docker 17, with enabled **userland-proxy**

**Diagnostics:**

**Comment by sleshchenko** [comment]
@benoitf Do you think it's a bug or expected behavior? If it's expected then can we improve UX, like show a pop up that your port is not proxied anymore?

**Comment by metlos** [comment]
Note that this is also reproducible on minishift.
