### ISSUE TITLE
Selfthosted - Docker + Traefik + HTTPS + Single User+Port

### ISSUE THREAD

**Issue by gdomod** [eclipse-che/che#13367]
### Description

i want to start my own IDE behind traefik reverse proxy. 
Dashboard ist load, workspace is creating but no access

**`Request URL: https://EXAMPLE.com14355/api/keycloak/settings
Request Method: GET
Status Code: 404 
Referrer Policy: no-referrer-when-downgrade`**

2nd Optional: at this time i have no luck to change the path of /dashboard url 
"traefik.frontend.rule=Host:EXAMPLE.COM; PathPrefix: /che"
proxyed to EXAMPLE.COM/che/dashboard
but che is always to rewrite to EXAMPLE.COM/dashboard

### MyConfig
`version: "3.6"
networks:
  internal:
    internal: true
    external:
      name: internal

services:
  che:
    image: "eclipse/che-server:6.19.0"
    container_name: "che"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/config/che:/data
    restart: always
    environment:
      - CHE_HOST=che.EXAMPLE.COM
      - CHE_HOST_PROTOCOL=https
      - CHE_SINGLE_PORT=true
      - CHE_DOCKER_IP_EXTERNAL=che.EXAMPLE.COM
      - CHE_PORT=9000
      - CHE_API=http://che.EXAMPLE.COM:14355/api
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.backend=che"
      - "traefik.frontend.rule=Host:che.EXAMPLE.COM"
      - "traefik.port=9000"
      - "traefik.docker.network=internal"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=EXAMPLE.COM"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false`

**Has anybody got traefik + che to work and can share with me the conf ?**

**Comment by Mbd06b** [comment]
I've been attempting to get a self-hosted setup using a FQDN, on and off since Fall 2018. 
I've tried getting establishing https connections with Apache and Nginx with SSL terminating proxies in front of the following che installations: 

Docker single user
Docker multi-user
Kubernetes(minikube) single-user
Kubernetes(minikube) multi-user 

I've probably fought with each of these configs for at least a couple of days each without ultimate success. 

Closest I've ever gotten to a working environment is running Che(multi-user) in default_host mode unsecured over http.

**Comment by mstavares** [comment]
Hi,
I'm interested on this too. I have the same issue about traefik.

**Comment by Mbd06b** [comment]
> Hi,
> I'm interested on this too. I have the same issue about traefik.

@mstavares
I was able to get eclipse che to work with an nginx reverse proxy to a kubernetes(microk8s) install, you might find something that helps you with your traefik case.  I put all my notes on this issue. https://github.com/eclipse/che/issues/14788

**Comment by mstavares** [comment]
Hi @Mbd06b 

I'm using eclipse che version 6.14 with docker :(
Seems that I'm no way out of this. Right now I'm able to access to the dashboard, I'm able to create a workspace but I get stuck on starting it.
