### ISSUE TITLE
Investigate how to report metrics from workspaces

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#13375]
It is needed to figure out the approach on how to collect and observe metrics from workspace agent/editor/language servers, such as "The % of workspaces projects cloned successfully" and "The % of Language Servers requests that get a successful response"

related to https://github.com/eclipse/che/issues/13270

**Comment by tsmaeder** [comment]
Duplicate of Investigate Language server metrics #14017 ?

**Comment by skabashnyuk** [comment]
I think they can be distinct.
https://github.com/eclipse/che/issues/14017 - can be limited to providing metrics in  Prometheus format to some endpoint.
https://github.com/eclipse/che/issues/13375 - this can be about how to collect LSP and other metrics from the workspace and deliver them to Prometheus server

**Comment by tsmaeder** [comment]
So we need to wait now until this issue here is solved?

**Comment by skabashnyuk** [comment]
I think you can start working https://github.com/eclipse/che/issues/14017

**Comment by tsmaeder** [comment]
We're going to have metrics from theia plugins soon. Any progress on this issue?

**Comment by skabashnyuk** [comment]
>Any progress on this issue?

No. No progress.
The only known to me reasonable variant is to relay on prometheus-operator. However, for hosted Che it can be a complicated dependency. 
CC @l0rd

**Comment by skabashnyuk** [comment]
closing with prefer to :
-  [MVP] Collecting Che Workspace metrics in single cluster mode with Prometheus https://github.com/eclipse/che/issues/14888
-  Collecting Che Workspace metrics in multiple cluster mode with help of Prometheus Federation mechanism https://github.com/eclipse/che/issues/14889
-  Test Prometheus federation in simplified mode. https://github.com/eclipse/che/issues/15030
- Investigate alternative possibilities to reduce Prometheus's permissions required to monitor workspaces https://github.com/eclipse/che/issues/15031
