### ISSUE TITLE
Docker Volumes.

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1338]
I cannot mount a volume using the dockerfile/stacks. Is there a way to set command line arguments thru che? I know this breaks platform independence provided by a dockerfile but I think it would be useful to have the command line options for docker thru che's interface as an option. I need something like "docker run -v /host/directory:/container/directory ..." . Can you do this thru stacks.json file?

This link explains the issue a little better. [http://container-solutions.com/understanding-volumes-docker/](url)
![image](https://cloud.githubusercontent.com/assets/16562450/15485959/fe800a2a-2107-11e6-91b2-387de4f6e214.png)

**Comment by ghost** [comment]
@james10174 you can mount an extra volume in `/conf/che.properties`:

`machine.server.extra.volume=/host/dir:/container/dir`

Currently this is a global property and you can mount just one file/directory at a time.

Hope it helps.

**Comment by james10174** [comment]
Thanks. I will try to get this to work as a temporary solution for me. Can we label this as enhancement. I think it would be nice to have the ability to use different volume per workspace and to have two workspaces/containers exchange data/information too. I can see teams possibly working in teams on different workspaces that would integrate together using volume-from or volume.

**Comment by james10174** [comment]
OK so I temporary work around is to attach the volume to the workspace after it starts. It requires you to run a script I modified on host computer terminal. The following is the script which I got from [https://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/](url) before modifying. There is actually a youtube video from dockercon on it as well. Copy and paste the following to create the script. At end it runs "./mountVolume.sh $(docker ps -l -q) /home/ /mnt/hostFS"  which will create a directory on workspace container at /mnt/hostFS containing the /home directory of host on the last container created which should be the last workspace started in che. 

cat << EOT >>  mountVolume.sh
#!/bin/sh
set -e
if [ "\${3}" = "" ]; then
    exit 1
fi
CONTAINER=\$1
HOSTPATH=\$2
CONTPATH=\$3

REALPATH=\$(readlink --canonicalize \$HOSTPATH)
FILESYS=\$(df -P \$REALPATH | tail -n 1 | awk '{print \$6}')

while read DEV MOUNT JUNK
do [ \$MOUNT = \$FILESYS ] && break
done </proc/mounts
[ \$MOUNT = \$FILESYS ] # Sanity check!

while read A B C SUBROOT MOUNT JUNK
do [ \$MOUNT = \$FILESYS ] && break
done < /proc/self/mountinfo
[ \$MOUNT = \$FILESYS ] # Moar sanity check!

SUBPATH=\$(echo \$REALPATH | sed s,^\$FILESYS,,)
DEVDEC=\$(printf "%d %d" \$(stat --format "0x%t 0x%T" \$DEV))

docker-enter \$CONTAINER sudo sh -c "[ -b \$DEV ] || sudo mknod --mode 0600 \$DEV b \$DEVDEC"
docker-enter \$CONTAINER sudo mkdir /tmpmnt
docker-enter \$CONTAINER sudo mount \$DEV /tmpmnt
docker-enter \$CONTAINER sudo mkdir -p \$CONTPATH
docker-enter \$CONTAINER sudo mount -o bind /tmpmnt/\$SUBPATH \$CONTPATH
docker-enter \$CONTAINER sudo umount /tmpmnt
docker-enter \$CONTAINER sudo rmdir /tmpmnt
EOT
chmod 770 mountVolume.sh
./mountVolume.sh $(docker ps -l -q) /home/ /mnt/hostFS


![image](https://cloud.githubusercontent.com/assets/16562450/15525767/45dbc3a6-21f2-11e6-9363-eb099f41a2fd.png)

**Comment by ghost** [comment]
@james10174 attaching volumes in a runtime is definitely a fun thing to do. :) Thanks for sharing it!

**Comment by james10174** [comment]
@eivantsov Once it's labelled enhancement do I close the issue?

**Comment by TylerJewell** [comment]
Hi!  It is customary to leave the ticket open until the issue is fully resolved and merged into a releasable version.

**Comment by TylerJewell** [comment]
Resolved in 4.7.2 - you can now reference volumes.
