### ISSUE TITLE
Che 7 java-maven stack is not fully functional on che.openshift.io

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13383]
### Description
The following PR adds che 7 java-maven stack to che.openshift.io https://github.com/redhat-developer/rh-che/pull/1420

However, stack itself is not fully functional. It works with basic `console-java` sample, but not with `vertx-http-booster`. Basically, the build command works just fine, but run command fails with the following error:

```
[INFO] SEVERE: Failed to create the vert.x instance
[INFO] java.lang.IllegalStateException: Failed to create cache dir
[INFO] at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:333)
[INFO] at io.vertx.core.file.impl.FileResolver.(FileResolver.java:88)
[INFO] at io.vertx.core.impl.VertxImpl.(VertxImpl.java:168)
[INFO] at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
[INFO] at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
[INFO] at io.vertx.core.Vertx.vertx(Vertx.java:85)
[INFO] at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
[INFO] at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:276)
[INFO] at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:191)
[INFO] at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
[INFO] at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
[INFO] at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
[INFO] at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
[INFO] at io.vertx.core.Launcher.main(Launcher.java:45)
```

### Reproduction Steps
- create and start workspace on che.openshift.io using che 7 java-maven stack with `vertx-http-booster`
- execute build command - all works just fine
- execute run command
ERROR:

![image](https://user-images.githubusercontent.com/1461122/58117231-651fc000-7bfe-11e9-9184-2987f49b8aaf.png)

**OS and version:**    
`che.openshift.io`  7 Beta4

**Diagnostics:**

**Comment by ibuziuk** [comment]
Health Check Booster seems to work fine on che.openshift.io:
![image](https://user-images.githubusercontent.com/1461122/58162380-5d096400-7c82-11e9-8f96-38107eb78525.png)

**Comment by tsmaeder** [comment]
Maybe user.home is not set up correctly in the image we're using?

**Comment by ibuziuk** [comment]
should be closed once Hosted Che is updated to Che 7 GA - https://github.com/redhat-developer/rh-che/issues/1490

**Comment by ibuziuk** [comment]
`7.1.0` is running on production. Closing
