### ISSUE TITLE
Workspace startup logs display 2 times the download of plugins

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13388]
See attached screenshot.

<img width="1788" alt="Capture d’écran 2019-05-22 à 11 45 22" src="https://user-images.githubusercontent.com/1636769/58165021-339f0700-7c87-11e9-82bd-fdf435d80bfe.png">

**Comment by sleshchenko** [comment]
Please note that it may be an issue of plugin broker but not workspace loader.

**Comment by slemeur** [comment]
Thanks @sleshchenko. Who can handle it?

**Comment by benoitf** [comment]
maybe that it is first downloading java extension and then java debug extension ?

**Comment by benoitf** [comment]
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/0.43.0/meta.yaml#L17 and then https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/0.43.0/meta.yaml#L18

**Comment by sleshchenko** [comment]
> Who can handle it?

@slemeur I think OSIO team is the main contributor to `che-plugin-broker`, but the platform team is able to handle it as well.

**Comment by sleshchenko** [comment]
Is already fixed by https://github.com/eclipse/che-plugin-broker/pull/66
