### ISSUE TITLE
GitHub oAuth authorization does not work with Red Hat SSO 7.3

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#13380]
### Description
It's impossible to authorize with GitHub oAuth using Red Hat SSO registry.access.redhat.com/redhat-sso-7/sso73-openshift:1.0-11
  
### Reproduction Steps
Steps to reproduce:
- deploy Eclipse Che using Red Hat SSO 7.3 from registry.access.redhat.com/redhat-sso-7/sso73-openshift:1.0-11
- add Github identity provider to Red Hat SSO
- create new user
- create workspace and open IDE
- go to **Profile -> Preferences -> VCS**
- click on the button **Generate Key** and try to upload ssh key by clicking on OK button

#### Expected behavior:
- there is GitHub authorization page with correct content opened, for example:
![Screenshot from 2019-05-16 19-38-37](https://user-images.githubusercontent.com/1197777/58110463-40284e80-7bf8-11e9-9268-c1d10d498895.png)

#### Observed behavior:
- there was _Invalid Request_ error page appeared:
![github-oauth-invalid-request](https://user-images.githubusercontent.com/1197777/58110459-3dc5f480-7bf8-11e9-80f7-0c7ab917f8f0.png)

**Downstream issue:**
https://issues.jboss.org/browse/CRW-281

**OS and version:**    
Eclipse Che 6.19.3 deployed to OpenShift 3.11 with Keycloak 

**Diagnostics:**

**Comment by skabashnyuk** [comment]
@dmytro-ndp to be able to identify this issue is a bug - can you confirm that redhat-sso-7/sso73-openshift:1.0-11 is based on jboss/keycloak-openshift:3.4.3.Final that is certified in upstream?

**Comment by dmytro-ndp** [comment]
According to [fixed issues list](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.3/html/release_notes/red_hat_single_sign_on_7_3#fixed_issues) SSO 7.3 based on Keycloak of up to 4.8.0 version `jboss/keycloak-openshift:4.8.0.Final`.

**Comment by dmytro-ndp** [comment]
Commit 239d93e333e5fb88ba6d2476d660cf5d36f3ae4a is fixing downstream issue https://issues.jboss.org/browse/CRW-281
