### ISSUE TITLE
Resizing of panels in Che 7 IDE is buggy

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13389]
### Description
Buggy behavior when resizing the side panels (especially the che workspace one on the right), it's impossible to free the cursor from "resize operation", so the only way the user can get out of this, is by refreshing the browser.

**Comment by AndrienkoAleksandr** [comment]
@slemeur I believe that you described this one issue https://github.com/eclipse/che-theia/issues/151

**Comment by slemeur** [comment]
Yes that's the issue I faced indeed.
Thanks

**Comment by evidolob** [comment]
It should be fixed by eclipse/che-theia#151
