### ISSUE TITLE
Interaction with Tasks when running multiple ones

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13396]
### Description
When the user is starting multiple tasks, those could be running concurrently and the user might close the outputs tabs from few of those.
How the user can then come back to the outputs of currently running tasks?

**Comment by azatsarynnyy** [comment]
Theia provides `Terminal > Attach Task...` command for that purpose. But [looks like](https://github.com/theia-ide/theia/blob/2a1c24973ed9833c54b5b2838f52b184f3343be2/packages/task/src/browser/quick-open-task.ts#L139) it works with Theia's `shell` type tasks only.

I think it requires some investigation on how that command could be integrated with the functionality provided by the [che-machine-exec](https://github.com/eclipse/che-machine-exec) server.

**Comment by evidolob** [comment]
@slemeur Are you OK with Artem proposal?

**Comment by slemeur** [comment]
As a user, I would like to know all the tasks that are currently running.
Should we list those somewhere ?
