### ISSUE TITLE
Release of 6.19.5 to fix #12889 and https://issues.jboss.org/browse/CRW-206

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#13407]
Release of 6.19.5 to fix #12889 and https://issues.jboss.org/browse/CRW-206

**Comment by dmytro-ndp** [comment]
@riuvshin: please, wait for test results before releasing.

**Comment by dmytro-ndp** [comment]
@riuvshin: it was tested in CRW, and is ready for release 6.19.5.
Nick has already cherry-picked all required commits into 6.19.x branch.

**Comment by riuvshin** [comment]
done

**Comment by nickboldt** [comment]
Thanks, @riuvshin !
