### ISSUE TITLE
Release 6.19.4

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#13402]
### Description
Release of 6.19.4 with commit 1bb6e096cf1d3366a118d17d62e19dbb6d2e813d to fix downstream issue https://issues.jboss.org/browse/CRW-281

**Comment by dmytro-ndp** [comment]
PR Iae6a95f45b0e38e2d86d35e48f13e8dc1301d721 should be included as well to fix build of Dashboard

**Comment by riuvshin** [comment]
@dmytro-ndp I don't think we have to upgrade version of the base image as we don't know the possible impact of this. I've applied a [workaround](https://github.com/eclipse/che/commit/77ed66fd8e7dab94a8d760a77c361eebd07ac968) to fix the build it was very trivial one.
So this way we don't need to retest everything.

**Comment by dmytro-ndp** [comment]
Please, don't release 6.19.4 until we ensure fixup works correctly in CRW 1.2.

**Comment by riuvshin** [comment]
I have started release a while ago, next time please make it clear in the issue description that release should be delayed before fix tested.

**Comment by dmytro-ndp** [comment]
Sorry for that.

**Comment by dmytro-ndp** [comment]
No need to interrupt release, because actually, releasing comiit commit 1bb6e096cf1d3366a118d17d62e19dbb6d2e813d is fixing downsrteam issue  https://issues.jboss.org/browse/CRW-281

**Comment by nickboldt** [comment]
If we're releasing 6.19.4, please also include fix for https://github.com/eclipse/che/issues/12889 in the release.

**Comment by nickboldt** [comment]
I don't see 6.19.4 in https://repo.maven.apache.org/maven2/org/eclipse/che/multiuser/che-multiuser-keycloak-server/6.19.4 yet. Has it been held back pending a fix for #12889, or will we instead do a 6.19.5 release for that one?

**Comment by riuvshin** [comment]
6.19.4 is released already, I do not see any fix for https://github.com/eclipse/che/issues/12889 so when fix will be in place we could release another bugfix.
@nickboldt it takes 3-4h to distribute artifacts across central mirrors, so it will be there soon.

**Comment by nickboldt** [comment]
Great, I'll open a new issue for 6.19.5 release then.
