### ISSUE TITLE
[openshift plugin] fix 'Log in' command

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#13405]
[OpenShift Connector Che Plugin](https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/redhat/vscode-openshift-connector) provides `OpenShift: Log in to cluster` command that stopped working in v0.0.21.

**Diagnostics**
The error is reported in a notification:
`Cannot read property 'readText' of undefined`

Should be fixed by https://github.com/theia-ide/theia/issues/5519

**Comment by AndrienkoAleksandr** [comment]
Still reproducible. 
Agly workaround: 
open new terminal for openshift connector container and login with help oc tool.

**Comment by AndrienkoAleksandr** [comment]
Looks like a bug plugin api.

**Comment by azatsarynnyy** [comment]
VS Code OpenShift Connector extension [relies on](https://github.com/redhat-developer/vscode-openshift-tools/blob/59f145cfe242639c2ac607844865d0bdbd8547f4/src/openshift/cluster.ts#L193) VS Code extension [Clipboard API](https://github.com/microsoft/vscode/blob/466c132f5b4362b3be485a1f7a624b3a7316ddb8/src/vs/vscode.d.ts#L5977-L5993) which isn't implemented in Theia yet.

**Comment by azatsarynnyy** [comment]
There's PR https://github.com/theia-ide/theia/pull/5527 in Theia opened 2 months ago which fixes two issues including adding Clipboard API support.
I've tested the OpenShift plugin with the patch proposed in that PR and `Log in` command works well.
I'm going to extract the Clipboard API related code to a separate PR.

**Comment by azatsarynnyy** [comment]
waiting for https://github.com/theia-ide/theia/pull/5994

**Comment by azatsarynnyy** [comment]
Looks like the `Log in` command works on secure (https) connections only. That prevents using it in Che running on minishift on insecure connection (http).

`Log in` command utilizes Theia Plugin Clipboard API that relies on browser's Async Clipboard API which works on secure connections only.

Reopening it to investigate the possible solution.

**Comment by azatsarynnyy** [comment]
For now, I don't see a way how to allow the clipboard access on http.
So 'Log in' command won't work on minishift.
