### ISSUE TITLE
[FEATURE_REQUEST] Expose granular metrics regarding workspace startup

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#13411]
### Description
Related to #12740

We are in desperate need to have access to start times of separate components inside a workspace itself:
* Plugin broker start
* Plugin broker processing
* Marked as starting
* Pull eclipse/che-dev:nightly
* Pull wsskeleton/che-machine-exec
* Pull wsskeleton/che-hello
* Pull eclipse/che-theia:plugin-id-nightly
* Workspace containers all running
* Theia start

Quote @amisevsk :
```
My perspective: I see two relatively easy ways to get the internal
timing data out of Che.

1. The approach I used to get somewhat fine-grained (but perhaps
difficult to interpret) data when timing workspace starts was to add
some simple code that listens to every event emitted during workspace
start. A somewhat outdated branch is available at [1].

This approach would require either a) recompiling Che with some
modifications every time or b) figuring out a generally useful way to
integrate it into upstream Che (at which point it likely becomes a part
of our typical logging/metrics).

The upsides:
   - it's very simple to implement (although it's hard to do any
*automatic* reasoning about what the events mean).

The downsides:
   - it requires some care in how the information is processed after the
fact -- you're getting events that mean either a phase is beginning or
ending and have to infer duration yourself (with other events in between
potentially). Could potentially be done with some regex parsing though.

A sample output from workspace startup is available at [2].


2. The second approach would be to try and extend the tracing/metrics
functionality we already have. There were a few outstanding issues to do
something similar (e.g. [3]) that could be rounded up into this.

I have some ideas about how to do this and it shouldn't be terribly
difficult to implement (in probably a similar way to the approach in 1.)
but haven't actually gotten down into the code to figure out the details.

The upsides:
   - since Che would be putting in more work (getting event durations
and sending those directly rather than event timestamps) it's a lot
easier to interpret the data coming out -- it's easier to get start and
stop times for phases / components at the source than after the fact
   - It's maybe easier, from a OSS Che perspective, to integrate into
upstream, as everyone is going to love improved tracing and metrics.
   - It's perhaps the better approach from a code design perspective
(than somewhat clumsy logging)

The downsides:
   - While it is possible to get json out of Jaeger, I don't know if it
is easy to handle the tracing data without basically reimplementing
jaeger -- It might be hard to get the metrics we want in an easy to
process way.
   - I haven't tried and seen if there are any significant roadblocks to
implementing the metrics we'd require. I don't *think* it would be too
difficult but I'm not actually sure yet.

I think approach 1 is probably more useful as a way of implementing the
requirements for approach 2.
```

[1] ????
[2] ???? 
[3] ????

I myself have found another alternate solution, which in my own opinion could be really useful for us, and that is implementing SSE (server-sent events)

There is a springboot library available for this exact purpose:
https://www.baeldung.com/spring-server-sent-events

My point here is that the way these events behave and are sent is a universal thing and the communication is uni-directional.

What do you guys think? We are open for ideas and opinions. Please help us discuss and resolve this issue.

**Comment by amisevsk** [comment]
My main concern would me how access to this endpoint is managed -- how do we control which *specific* accounts can get a stream of events across the entire Che server?

**Comment by skabashnyuk** [comment]
@ScrewTSW  can you specify a use case why you need this information and why existed tracing/metrics/logs functionality aren't suitable for you?

**Comment by skabashnyuk** [comment]
@ScrewTSW any updates?

**Comment by ScrewTSW** [comment]
@skabashnyuk Hello. This topic should be discussed on the F2F happening right now. Hope that Katka and Radim can provide more info. We need to have a discussion together with @l0rd on this topic and decide the way we will collect this data.

currently the idea was that we would take care of collecting project pull, project build and IDE load times while you would take care of the workspace pod startup granularity via tracing, or whatever enables you to gather this data. It's still an open topic that's very likely to change.
