### ISSUE TITLE
Che operator should support single-user Che

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13420]
### Description

Currently Che operator supports only multi-user Che. To avoid maintaining both the operator and the legacy DeploymentConfig we should update the operator to support single-user Che and deprecate the DeploymentConfig.

@davidfestal can you have a look at this issue when you have merged https://github.com/operator-framework/community-operators/pull/384 and https://github.com/operator-framework/community-operators/pull/383

cc @nickboldt @ibuziuk

**Comment by ibuziuk** [comment]
@l0rd hmm, interesting - I thought we were going to deprecate single-user [1] in general, so not really following why having single-user based operator-driven deployment is a GA priority 

[1] https://github.com/eclipse/che/issues/10996

**Comment by l0rd** [comment]
I am ok to close this issue if we can deprecate single user before GA. But I am not aware of a solution for deprecating single user yet. What I know is that we can deprecate `che_deploy.sh` if we can use the operator for single-user. That should be easy to implement and would mean one less installer to maintain...Does that make sense?

**Comment by ibuziuk** [comment]
this makes sense. Am I correct that operator based deployment would support both OpenShift 4 and OpenShift 3.11 ?

**Comment by davidfestal** [comment]
yes afaik

**Comment by nickboldt** [comment]
AFAIU, there is no support for operators or OLM in openshift 3.11. If there
was we would not need to maintain deploy.sh script.

N

**Comment by l0rd** [comment]
OLM is included as a component of OS 4.x
OLM is not included but can be installed on OpenShift 3.11 (c.f. [the doc](https://docs.openshift.com/container-platform/3.11/install_config/installing-operator-framework.html))
