### ISSUE TITLE
Deprecate storing of workspaces converted from Devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13423]
### Description
Since we have an ability to create a workspace directly from Devfile, it's needed to deprecate the old method that converts Devfile to Workspace Config and store a workspace with it.
There are two places that use such an approach:
1. DevfileService#createFromConfig. <- this should be deprecated and removed later.
2. Accepting factory from Github repository URL. <- this should be reworked to create workspaces directly with Devfile.

**Comment by skabashnyuk** [comment]
@l0rd I found this task important to do before GA since this API uses workspace config(aka Che6) as a backend to store devfile. That might be a bit confusing.

**Comment by l0rd** [comment]
@skabashnyuk agreed
