### ISSUE TITLE
Incomplete docs - Installing on Kubernetes

### ISSUE THREAD

**Issue by trobert2** [eclipse-che/che#13421]
### Description
The documentation that describes how to install Che on Kubernetes does not tell us where the helm chart should be fetched from.
https://www.eclipse.org/che/docs/che-6/kubernetes-single-user.html

### Reproduction Steps
There is nothing before this command that tells us where the chart is.
```
helm upgrade --install <my-che-installation> --namespace <my-che-namespace> ./
```

**Comment by nickboldt** [comment]
If this is still an issue in the Che 7 docs, then we should fix it. If it's only a Che 6 problem, then we can close this as "fixed in Che 7". See also https://github.com/eclipse/che/issues/12815 re: helm charts and docs.

**Comment by slemeur** [comment]
Does this answer your question @trobert2 ?
On Che 7, the documentation is here: https://www.eclipse.org/che/docs/che-7/che-quick-starts.html
