### ISSUE TITLE
Helm install validation failed

### ISSUE THREAD

**Issue by pasmon** [eclipse-che/che#13431]
### Description
Not sure what happened, Helm installation worked last week and now it doesn't:
```
helm upgrade --install che --namespace che -f ./values/multi-user.yaml ./
Release "che" does not exist. Installing it now.
Error: validation failed: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.CHE_INFRA_KUBERNETES_NAMESPACE, unknown object type "nil" in ConfigMap.data.CHE_LOGGER_CONFIG, unknown object type "nil" in ConfigMap.data.CHE_OAUTH_GITHUB_CLIENTID, unknown object type "nil" in ConfigMap.data.CHE_OAUTH_GITHUB_CLIENTSECRET, unknown object type "nil" in ConfigMap.data.CHE_WORKSPACE_HTTPS__PROXY, unknown object type "nil" in ConfigMap.data.CHE_WORKSPACE_HTTP__PROXY, unknown object type "nil" in ConfigMap.data.CHE_WORKSPACE_NO__PROXY]
```

I'm using default `values.yaml` straight from the repository. I don't want to use anything GitHub related in my Che installation.

### Reproduction Steps
```
git clone https://github.com/eclipse/che.git
cd che/deploy/kubernetes/helm/che
git checkout 6.19.4

```
Install Helm and Tiller according to: https://www.eclipse.org/che/docs/che-6/kubernetes-multi-user.html and then:

```
helm dependency update
helm upgrade --install che --namespace che -f ./values/multi-user.yaml ./

```
**OS and version:**    
Helm client and server: v2.14.0
Eclipse Che tag 6.19.4

**Diagnostics:**

**Comment by sleshchenko** [comment]
@pasmon This PR should fix the issue you faced https://github.com/eclipse/che/pull/13425

**Comment by benoitf** [comment]
@pasmon it's related to https://github.com/helm/helm/issues/5750 . (helm 2.13.1 --> 2.14.0)
it's fixed in master (just merged my PR)

**Comment by pasmon** [comment]
Well that was fast, thanks guys!

**Comment by pasmon** [comment]
Ahem :disappointed: 
```
helm upgrade --install che --namespace che -f ./values/multi-user.yaml ./                                                                               
Release "che" does not exist. Installing it now.
Error: validation failed: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.CHE_INFRA_KUBERNETES_NAMESPACE
```
I modified `cheWorkspacesNamespace` in `values.yaml`, and then I get this:
```
helm upgrade --install che --namespace che -f ./values/multi-user.yaml ./
Release "che" does not exist. Installing it now.
Error: validation failed: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "test" in io.k8s.api.extensions.v1beta1.DeploymentSpec
```

**Comment by benoitf** [comment]
@

**Comment by pasmon** [comment]
@benoitf Yes, I'm using Rancher deployed Kubernetes on top of OpenStack, no `chectl` used anywhere.

**Comment by benoitf** [comment]
@pasmon https://github.com/eclipse/che/pull/13432

**Comment by pasmon** [comment]
That fixes the first issue, so no need to define `cheWorkspacesNamespace` anymore. Second issue still exists.

**Comment by pasmon** [comment]
After `helm dependency update` I didn't get the second issue, installation was successful.
