### ISSUE TITLE
Do not wait for PV state bound if we got a message "waiting for the first consumer to be created before binding"

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13437]
### Description
Do not wait for PV state bound if we got a message "waiting for the first consumer to be created before binding"
Follow up https://github.com/eclipse/che/issues/12889#issuecomment-496558203

**Comment by nickboldt** [comment]
Downstream issue: https://issues.jboss.org/browse/CRW-294

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/14239

**Comment by sleshchenko** [comment]
@sparkoo I've just noticed a comment from Nick

> Note: the fix for this must be backported to 6.19.x (and a new release is required) in order to be included in CRW 1.2.3.

@nickboldt Can you confirm that it's still needed to backport this fix to 6.19.x?

**Comment by nickboldt** [comment]
Yes, we need this in 1.2.x, based on 6.19.6. Stevan confirmed this a couple weeks ago.

**Comment by sparkoo** [comment]
here's the backport to `6.19.x` branch https://github.com/eclipse/che/pull/14269

**Comment by slemeur** [comment]
Thanks @sparkoo !
