### ISSUE TITLE
bright fonts are not set on dark theme on Firefox

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#13442]
### Description

Bright fonts are not set on dark theme on Firefox

### Reproduction Steps

Minishift  v1.34.0+f5db7cb, Che 7.0.0-beta-4.0 installed as minishift addon, Workspace with Che 7

Browsing with Firefox 67.0:

![Eclipse Che   wksp p66d](https://user-images.githubusercontent.com/243761/58559980-8139e780-8224-11e9-9324-5f1ec4e915d5.png)

Browsing with Chromium Version 73.0.3683.86 is fine.

**Comment by amisevsk** [comment]
Also seeing this consistently, thanks for opening an issue @themr0c -- I've been meaning to.

For clarity, the entire font is not loaded and the default serif font is shown. Errors in browser console:

```
root ERROR v32//f</n.prototype.onStart/<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:4258050
phsZ/c</e.prototype[Symbol.iterator]/</<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:3910059
phsZ/c</e.prototype.invoke@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:3910277
phsZ/l</e.prototype.fire@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:3911602
set@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:934057
set@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2965702
gKTU/w</e.prototype.refresh/</<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2967675
s/</<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2963372
s/<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2963477
a@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2962223
theia.09b410fd1dcaf79e0404.js:1:4502604
    log https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    get https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    getLog https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    log https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1

TypeError: n.rules is undefined theia.09b410fd1dcaf79e0404.js:1:2055632
    setRules https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    onLoad https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    o https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    setHTML https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1

Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;base64,PHN2ZyBmaWxsPS… (“img-src”).

root ERROR v32//f</n.prototype.onStart/<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:4258050
phsZ/c</e.prototype[Symbol.iterator]/</<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:3910059
phsZ/c</e.prototype.invoke@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:3910277
phsZ/l</e.prototype.fire@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:3911602
set@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:934057
set@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2965702
gKTU/w</e.prototype.refresh/</<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2967675
s/</<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2963372
s/<@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2963477
a@https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1:2962223
theia.09b410fd1dcaf79e0404.js:1:4502604
    log https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    get https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    getLog https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1
    log https://static.developers.redhat.com/che/theia_artifacts/theia.09b410fd1dcaf79e0404.js:1

Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;base64,PCEtLUNvcHlyaW… (“img-src”).

Content Security Policy: The page’s settings blocked the loading of a resource at https://static.developers.redhat.com/che/theia_artifacts/af7ae505a9eed503f8b8e6982036873e.woff2 (“font-src”).

Content Security Policy: The page’s settings blocked the loading of a resource at https://static.developers.redhat.com/che/theia_artifacts/e817279537a0417d042f62fbb1b99eea.gif (“img-src”).
```

**Comment by AndrienkoAleksandr** [comment]
@slemeur I worked on reproducing this issue and I see - issue is reproducible on the Firefox **67**, but is not reproducible since Firefox **68.0.1**. Do we have any strategy about minimal Firefox version support? I mean when we confirm that we are going to fix some bug, because it is reproducible for some supported Firefox version, if it is reproducible for older version we apply recommendation for users to use newer Firefox. Because it's really time consuming trying to figure out issue is actual or not, and there a lot of Firefox versions: https://ftp.mozilla.org/pub/firefox/releases/ . **What do you think?** Example of the browser support note https://github.com/xtermjs/xterm.js#browser-support

**Comment by amisevsk** [comment]
I think as long as things work on the latest stable version of Firefox that's commonly available, it's fine. What's concerning is that we don't know what changed between firefox 67 and 68 that fixed this -- we don't link to a bug that explains the issue. Is Che doing something wrong and it just happens to work with a new Firefox, or was it a legitimate Firefox bug that caused the css loading issue? IMO unless there's a bug we can point to in Firefox that causes the issue, there's something wrong with Che.

I don't like issues that resolve themselves without explanation.

**Comment by AndrienkoAleksandr** [comment]
Issue progress update:

For such kind errors:
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.developers.redhat.com/che/theia_artifacts/af7ae505a9eed503f8b8e6982036873e.woff2 (“font-src”).
```
 I created pr https://github.com/eclipse/che-theia/pull/551 . Also I found that font exception could spawn side effect: not all che-theia icons is loading, especially for  project tree view.

**Comment by AndrienkoAleksandr** [comment]
Issue progress update:
I created pr to fix one more exception from webview: https://github.com/eclipse-theia/theia/pull/6581
After merge both pr's che-theia log in the firefox should be clean.

**Comment by AndrienkoAleksandr** [comment]
Related pr from upsteam theia: 
https://github.com/eclipse-theia/theia/pull/6465

**Comment by AndrienkoAleksandr** [comment]
Faced with bug. Webview with https doesn't work for Firefox in the incognito mode. https://bugzilla.mozilla.org/show_bug.cgi?id=1601916

**Comment by AndrienkoAleksandr** [comment]
Reworked webview work with https and with latest Firefox, but doesn't work with latest long term Firefox esr 68.3.0esr.

**Comment by AndrienkoAleksandr** [comment]
See more about service worker on the est https://bugzilla.mozilla.org/show_bug.cgi?id=1547023 Task is not completed, so issue in the Firefox side.

**Comment by AndrienkoAleksandr** [comment]
With latest Firefox,  welcome plugins looks like:

<img width="960" alt="welcome-dark" src="https://user-images.githubusercontent.com/6873095/70323958-e9523180-1836-11ea-8f11-3b0b089e4900.png">
<img width="960" alt="welcome-light" src="https://user-images.githubusercontent.com/6873095/70323961-e9523180-1836-11ea-9a38-13cab6450e64.png">

Yes we don't have logo but it's another one issue https://github.com/eclipse/che/issues/15324

**Comment by AndrienkoAleksandr** [comment]
Info: https://github.com/eclipse-theia/theia/pull/6581 was closed on favour upsteam pr https://github.com/eclipse-theia/theia/pull/6465

And pr https://github.com/eclipse/che-theia/pull/551 was closed on favour https://github.com/eclipse/che-theia/pull/570
