### ISSUE TITLE
Error trying to start wsagent when loading a devfile

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13448]
### Description

Loading a devfile as a factory in che.openshift.io

![image](https://user-images.githubusercontent.com/606959/58628132-3e861700-82d9-11e9-9223-869c14bc9b66.png)

The workspace creation fails because there are not enough resources. And that's normal. But the message talks about the **workspace agent** and this is misleading since it should be a Che 7 sidecar workspace without the agents.

### Reproduction Steps

https://che.openshift.io/f?url=https://pastebin.com/raw/kwhdvQQ9

**Comment by skabashnyuk** [comment]
CC @ashumilova 
This is a code responsible for this message https://github.com/eclipse/che/blob/master/dashboard/src/app/factories/load-factory/load-factory.controller.ts#L423-L425
```typescript
            .title('Error when starting agent')
            .content('Unable to start workspace agent. Error when trying to start the workspace agent: ' + message.error)
            .ariaLabel('Workspace agent start')
```
Any suggestions about how to rephrase?

**Comment by l0rd** [comment]
@skabashnyuk :+1: for the rephrasing that you are proposing
