### ISSUE TITLE
Stabilize org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoTest

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13458]
### Description
org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoTest is quite often failing when building che (PR check build job).
Few examples:
* https://ci.codenvycorp.com/job/che-pullrequests-build/6774/#showFailuresLink
* https://ci.codenvycorp.com/job/che-pullrequests-build/6773/#showFailuresLink
* https://ci.codenvycorp.com/job/che-pullrequests-build/6772/
* https://ci.codenvycorp.com/job/che-pullrequests-build/6768/
* https://ci.codenvycorp.com/job/che-pullrequests-build/6750/

**Comment by metlos** [comment]
Hi, this is temporary and caused by merging of https://github.com/eclipse/che-parent/pull/117. This is needed for https://github.com/eclipse/che/pull/13417 which will fix the tests once merged.

**Comment by rhopp** [comment]
Thx for info.

**Comment by metlos** [comment]
Yep, sorry for the false alarm. We didn't fully anticipate the effect the merge of the che-parent would have.

**Comment by skabashnyuk** [comment]
Will be fixed by https://github.com/eclipse/che/pull/13417

**Comment by metlos** [comment]
#13417 is now merged, so the tests should stabilize on the next master build. If not, please raise the alarm! :)
