### ISSUE TITLE
Plugin broker should only make necessary changes to plugins

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#13452]
### Description
Currently, the plugin broker functions as follows:

1. Delete all plugins (clear the `/plugins` directory) -- `che-plugin-init-broker`
2. Download plugins specified in workspace attributes.

This means that every time a workspace is started without being modified, we do a lot of unnecessary work. This is especially a problem when preparing some plugins can take significant time. For a non-ephemeral workspace, if it hasn't been modified, the broker only needs to process the relevant configuration and return it to the server.

This issue will get worse as more plugins are added to workspaces.

### Reproduction Steps
Start any Che 7 workspace with plugins installed:
```
Starting Init Plugin Broker
Cleaning /plugins dir
Unified Che Plugin Broker
List of plugins and editors to install
- eclipse/che-machine-exec-plugin/0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- redhat/java/0.38.0 - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
- eclipse/che-theia/next - Eclipse Theia, get the latest release each day.
```

**Comment by nickboldt** [comment]
If the gist here is "don't delete every time, only delete if we have new stuff" then +1.

Question. There's a "my lang server has died" workaround which is to simply refresh the browser (*cough*: https://github.com/eclipse/che/issues/13427 */cough*) ... how would changing this behaviour impact the ability to force a workspace refresh via F5 ? Would we need a mechanism to force delete, if we're no longer deleting everything every time?

**Comment by amisevsk** [comment]
@nickboldt The deletion happens only once, before workspace startup. My goal with this issue is to have the plugin broker resolve workspace state at startup, by e.g.

1. Check which plugins are installed in the workspace currently (in `/plugins`)
2. Check which plugins are included in the devfile
3. Reconcile the two (delete installed plugins not in the devfile, install plugins in devfile but not `/plugins`)

The only roadblock currently is that the plugin broker doesn't know or care which plugins are already installed, it just wipes the directory blindly. Implementing this *could* be as simple as just storing some `json` in `/plugins` but I haven't looked into it too much.

As for a running workspace, nothing changes (refreshing the workspace behaves identically)

**Comment by nickboldt** [comment]
+1 for this solution as it'd be one less container I have to migrate to UBI8 and productize. ;) and then one less to support (CVE fixes, CEE questions, docs, etc.)

**Comment by nickboldt** [comment]
Setting need-triage and milestone 7.1 so we can discuss when/if this can be done.

**Comment by ibuziuk** [comment]
Moving to 7.2.0 for now, this issue is going to be discussed during the pre-planning for the next sprint

**Comment by ibuziuk** [comment]
Closing. in favour of plugin broker refactoring - #14494
