### ISSUE TITLE
[Q] Syntax error in `7.0.0-beta5.0/mysql/1__devfile_command_reference.sql` ?

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13461]
### Description

I got an error from Codacy when I tried to merge the master branch to my fork.
The link to details is https://app.codacy.com/app/monaka/che_2/pullRequest?prid=3658599
Indeed I've never seen `MODIFY COLUMN column_name` syntax before.
Is this a new syntax for MySQL? 

### Reproduction Steps

Check by Codacy

**OS and version:**    

**Diagnostics:**

**Comment by metlos** [comment]
Codacy doesn't seem to understand MySQL syntax here. The `ALTER COLUMN` construct does exist in MySQL but it cannot actually modify the type of the column. See https://dev.mysql.com/doc/refman/5.7/en/alter-table.html.

As such, I'm closing this as a false positive.
