### ISSUE TITLE
Che 6 workspaces warning: improvements

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13476]
### Description

Currently (since beta5 release) a `Not compatible` message is shown in the workspaces list for every Che 6 workspaces:

![che7-dashboard-issue](https://user-images.githubusercontent.com/606959/58898257-7b4b7700-86fa-11e9-8ec7-be5856b3f46c.png)

But it looks like we didn't complete yet this task do we? I think that the remaining goals for RC2 would be:

- [x] Provide migration documentation
- [x] Add a link in the pop up warning message to the documentation
- [x] Users should not be able to start a workspace (i.e. in the configuration page the open button should be disabled): *I have tested on the nightly build and it looks like it has been done already :smiley:* 
- [x] Users should be able to access the workspace configuration (i.e. the cog sign should be still visible)
- [x] The question mark `?` should be replaced with a warning `⚠️`
- [x] The top of the popup is not visible (c.f. the screenshot)

**Comment by l0rd** [comment]
cc @ibuziuk @olexii4 @ashumilova

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/13506#issue-286738731
