### ISSUE TITLE
Missed dashboard stacks list in the "eclipseche/che-server:13469" image

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13471]
### Reproduction Steps
 - Deploy che using "eclipseche/che-server:13469" che-server image on minikube
 - Open dashboard in browser
 - Go to "Workspaces" -> "Add workspace"
 - Pay attention that page "New Workspace" displayed without stacks list

**Expected behavior:**
The "New Workspace" page displayed with all elements include stacks

**Observed behavior:**
Stacks section is missed

**OS and version:**
Che on Kudernetes, che-server image - "eclipseche/che-server:13469"

**Server logs:**
```
2019-06-04 09:42:48,365[ost-startStop-1]  [WARN ] [o.e.c.a.w.s.stack.StackLoader 134]   - No configured image found for stack che-in-che
```
[logs-from-che-in-che-5c7ddffdfd-kzwpx.txt](https://github.com/eclipse/che/files/3251666/logs-from-che-in-che-5c7ddffdfd-kzwpx.txt)

**Screenshot:**
![Screenshot from 2019-06-04 12-43-27](https://user-images.githubusercontent.com/22724619/58869646-4d990a80-86c7-11e9-8061-ef6742e20372.png)

**Comment by l0rd** [comment]
cc @ashumilova

**Comment by ashumilova** [comment]
@Ohrimenko1988 where this image comes from?

**Comment by ashumilova** [comment]
I see it here https://github.com/eclipse/che/pull/13469#issuecomment-498270121
and have a question - why we create issue on WIP PR?

**Comment by l0rd** [comment]
@ashumilova that's a fair point :smiley: I thought that those images were nightly build of the master branch. But it look like those correspond to PR branches. @Ohrimenko1988 were you aware of it?

**Comment by Ohrimenko1988** [comment]
Yes, it looks like this is my fault, I used "eclipseche" repo instead "eclipse".
Issue closed.

**Comment by ashumilova** [comment]
Thank you
