### ISSUE TITLE
Add schema for che plugins meta.yaml

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13470]
### Description

At the moment we do not have any docs which describe structure of che plugin. So, to add a new plugin, developer should provide `meta.yaml` file, structure of which is not clear and the only way to write own is to look at existing plugins. It still doesn't show all possible / valid values of the plugin's`meta.yaml` structure.

The goal of this issue is to have `meta.yaml` scheme or docs for it or both.

**Comment by monaka** [comment]
@mmorhun This issue was fixed by https://github.com/eclipse/che-plugin-registry/pull/205 ?

**Comment by monaka** [comment]
I inspected the schema file I introduced above.
Hmm, it's better to improved.
I opened https://github.com/eclipse/che-plugin-registry/pull/241 .

**Comment by ericwill** [comment]
I believe what we have in the `README` is sufficient for now, further improvements can be handled in a separate issue.
