### ISSUE TITLE
[TS Selenium] Improve existing "e2e" code-base

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13486]
### Description
    In the process of PR #13479 reviewing was found several moments which may be improved:
 - Incapsulate editor suggestions methods to the more intelligent methods
 - Incapsulate click on editor tab and wait result of this action to the "setFocus" method
 - Extract suggestion methods to the separated pageobject
 - Split "Ide" pageobject to several pageobjects as: "TopMenu", "LeftSidebar", "StatusBar" ...
 - Review methods and encapsulate they to the more intelligent methods
 - Refactor "Editor" for create an instance for each editor tab.

**Comment by rhopp** [comment]
@Ohrimenko1988 Could you please break down this issue into more smaller ones (maybe transform this one into epic?)
