### ISSUE TITLE
[TS-SELENIUM] Implement workaround for avoiding #13427 bug

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13489]
### Description
We have described in the issue #13427 bug with "Java" language server. This bug may be workarounded in the "HappyPath" test by refreshing page. This workaround will increase stability of the "HappyPath" test. But it may be a reason of not detected bugs related to "Java" language server, which may arise in the future and will not be detected because of page refresh.

@l0rd What is your opinion about that?

**Comment by l0rd** [comment]
I am ok with that for the time being. @benoitf @tsmaeder do you see any other solution?

**Comment by vkuznyetsov** [comment]
Do we really need to implement this workaround or let's wait for bug fix? Because it may hide other possible bugs.

**Comment by dmytro-ndp** [comment]
It might make sense to report known bug occurrence and then let Happy Path Tests go further by applying temporary well documented workaround inside the test.

**Comment by Ohrimenko1988** [comment]
Outdated issue
