### ISSUE TITLE
Workspace created by a user who is logged in Che7 by Openshift oAuth still exists after removing the Che7 project.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#13487]
### Reproduction Steps

1. Deploy **Che7** by ``` ./ocp.sh``` script with ```--setup-ocp-oauth``` option(register OCP oauth client and setup Keycloak and Che to use OpenShift Identity Provider)
2. Log into **Che7** by ```Openshift v3``` oAuth
3. Create and start any workspace. This workspace was created in separate project with workspace id name.
![Selection_220](https://user-images.githubusercontent.com/7760565/59036309-b0c99f00-8877-11e9-938c-974dab379ad8.png)

4. Delete ```eclipse-che``` project.

**Expected behavior:**
```Eclipse-che``` project and workspace project deleted.

**Observed behavior:**
The workspace project still exists.
![Selection_221](https://user-images.githubusercontent.com/7760565/59036323-b626e980-8877-11e9-838f-1c38dadf8684.png)

**Attachment:**
![screencast-10 33 177 143-8443-2019 06 06-16-04-30](https://user-images.githubusercontent.com/7760565/59036328-ba530700-8877-11e9-9fa0-b0ae9345b21f.gif)

**OS and version:**    
Che 7.0.0-RC-2.0-SNAPSHOT; Fedora 28; Chrome 74

**Diagnostics:**

**Comment by sleshchenko** [comment]
There is a similar issue for Che deployed on Kubernetes with Helm Chart https://github.com/eclipse/che/issues/12360

**Comment by sleshchenko** [comment]
Probably you must not remove Eclipse Che project manually but should use `chectl server:delete` for it. So, this use-case should be checked with chectl
