### ISSUE TITLE
Add ability to have local Che Theia plugin which brings sidecar

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13483]
### Description

For now it is impossible to have a local (in Theia IDE container) Che Theia plugin which adds a sidecar into workspace. Plugin broker should be able to handle such situation and allow such behaviour.

**Comment by mmorhun** [comment]
Seems we had such ability before: https://github.com/eclipse/che-plugin-registry/blob/master/plugins/che-service-plugin/0.0.1/meta.yaml

**Comment by tsmaeder** [comment]
@mmorhun can you give a use case for this? I don't understand why we would need a sidecar if the plugun runs on the theia container?

**Comment by mmorhun** [comment]
Well, I have created image with some tools which should be controlled via Theia UI. To use that tools, I've written plugin which simple creates UI in Theia and communicates with backend in dedicated (for the tools) container.

**Comment by mmorhun** [comment]
Can we consider taking this issue? Because it's a blocker for case when a plugin should bring a sidecar which is not based on endpoint runtime image (actually I tried to put plugin binary into main Theia container or bring another sidecar with it (based on endpoint runtime), but both are not possible now).

**Comment by tsmaeder** [comment]
@mmorhun yes, but what is the concrete use case for such a plugin?

**Comment by mmorhun** [comment]
Concrete example is my `Git UI Tools` plugin. It has sidecar with the git tools and based on another than endpoint runtime image. Also I have UI for it, which is simple Che-Theia plugin (no dependencies except the sidecar with backend) and it is not that important where the UI will be run (of course, running in Theia IDE container would be better because we'll avoid unneeded sidecar for UI part).

**Comment by sunix** [comment]
It is not clear what this is about.

**Comment by mmorhun** [comment]
@sunix please elaborate more what isn't clear for you

**Comment by sunix** [comment]
It's hard to elaborate when it is not clear at all...
> Add ability to have local Che Theia plugin which brings sidecar 

Ability for who? What is local?
Are you describing a problem or a solution to a problem? If this is the solution, what is the problem?

**Comment by mmorhun** [comment]
It's hard to explain everything in issue title, so the explanation is in the issue description. I though it was clear, but if it isn't, let me elaborate a bit more.

The goal of this issue is to add new functionality into Che + Theia plugin model (probably broker part), to Eclipse Che be able to handle a plugin which consists from a sidecar and Theia plugin _or_ VS Code extension, but the plugin itself (\*.theia / \*.vsix) is not the part of the sidecar and uses the sidecar as backend.
By local I meant that the plugin (\*.theia / \*.vsix) don't have to be remote and may be run inside main Theia IDE container, i.e. locally (not remote in separate sidecar).

@sunix please let me know if something is still unclear to you and I'll try to explain.

**Comment by sunix** [comment]
When defining a che plugin we should be able defined the vscode ext/theia plugins and where each of them are going to be executed:
- in the a specific side car container
- in the main theia ide container

**Comment by mmorhun** [comment]
Not exactly. The main goal of this issue is to add support for Che + Theia plugin model to consume (be able to run) a plugin which has a sidecar but the actual plugin binary (*.theia / *.vsix) is not part of the sidecar. For now this scenario is not possible.
Having ability to choose sidecar for plugin binaries would be a good bonus.

**Comment by tsmaeder** [comment]
Unless you want to combine different tooling containers with the same Theia plugins we could just add a Theia endpoint to the image containing the tooling (and we would not have to change anything). 
To me this still looks like a solution looking for a problem.

**Comment by gorkem** [comment]
This does not sound like a bug.

**Comment by gorkem** [comment]
I am unsure about this case. This will allow a plugin to live on the Theia container with dependencies to a sidecar which sounds fragile and I am not sure about the added benefit to current sidecar model.
