### ISSUE TITLE
Edited tasks in Theia does not work

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13508]
### Description
After editing a task in theia, I'm not able to run it anymore.

### Reproduction Steps
* Start workspace with some default tasks.
* Run `Tasks: Configure tasks..."
* Select a task -> tasks.json should be opened in editor
* Edit the task
* Run `Tasks: Run task..." -> Select your edited task
* EXPECTATION: Output view is shown & task is run
* FAIL: Nothing happens

Screencast of the behavior: https://youtu.be/ay2CE1x0ffc

**OS and version:**    

**Diagnostics:** 
Che-Theia@c657809 using Theia@c657809
Che - 7.0.0-RC-2.0-SNAPSHOT

**Comment by rhopp** [comment]
Already reported upstream: https://github.com/theia-ide/theia/issues/5064

**Comment by RomanNikitenko** [comment]
Should be fixed by https://github.com/eclipse/che-theia/pull/355 for 7.0.0 and by https://github.com/eclipse/che-theia/pull/295 for master branch

**Comment by azatsarynnyy** [comment]
@RomanNikitenko could you please check if it's already fixed and we close that issue

**Comment by RomanNikitenko** [comment]
Fixed by https://github.com/eclipse/che-theia/pull/295 for master branch, so I'm closing the issue
