### ISSUE TITLE
Do not allow workspace start with workspace config

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13517]
### Description
Since we are moving forward in devfile-based workspaces it would be logical to turn off the ability to start workspace configured with help of wsconfig. We can do that after
- [x] Create workspace from devfile https://github.com/eclipse/che/pull/13469
- [x] Deprecate storing of workspaces converted from Devfile https://github.com/eclipse/che/issues/13423

**Comment by dneary** [comment]
This task also depends on providing documentation for people with existing workspace configs on how to create an equivalent Devfile.
