### ISSUE TITLE
Not enough default memory limit  for typescript remote plugin 

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#13512]
### Description
Not enough default memory limit  for typescript remote plugin. We have default sidecar container memory limit https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L105. **But typescript sidecar plugin need more RAM value.**

### Reproduction Steps
1. Create workspace from devfile:
https://github.com/eclipse/che/blob/caae00e21b2fd316560a406f2e1d8ad98edf1dad/workspace-loader/devfile.yaml
</details>
2. Start workspace.

Actual result: workspace started, but che-theia is not avaliable. Instead of IDE editor, we see an error:
**503 Service Temporarily Unavailable
nginx/1.15.9**

**If I apply memory lmit 340M in the devfile - workspace became working again.**
Expected result: workspace should starts and open IDE editor.

**OS and version:**    
Kubuntu 19.04 che-server 7.0.0-RC-2.0-SNAPSHOT

**Comment by tsmaeder** [comment]
@AndrienkoAleksandr wasn't the limit 512m until recently?

**Comment by AndrienkoAleksandr** [comment]
@tsmaeder 512Mb really was, some time ago... https://github.com/eclipse/che/commit/a0a722f650afcdaf58f5d1d9f02652ed506dcf21

**Comment by sleshchenko** [comment]
@slemeur @tsmaeder looks like it's still actual.
![Screenshot_20190621_143025](https://user-images.githubusercontent.com/5887312/59919813-21a0b780-9431-11e9-93a8-e9c1b67c3d9b.png)
You can use the following sample app to test https://github.com/sleshchenko/NodeJS-Sample-App

Can we prioritize this issue and find a proper default memory limit for typescript LS?

**Comment by tsmaeder** [comment]
As I've written in my message to the che-dev mailing list a week ago , my team (in particular @tolusha) is addressing default memory sizing in this sprint. 
We will use the examples from the stacks to set the default memory sizes for the sidecars.
