### ISSUE TITLE
Devfile not validated on workspace update

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#13526]
### Description
When a workspace is updated and contains an updated version of the backing devfile, the content of the devfile is not validated. This can lead to failed workspace startup once such workspace is restarted after the update.

### Reproduction Steps
1) Create a devfile-backed workspace using a valid devfile. 
1) Send an update request containing an invalid devfile.
1) Observe the update succeeding.
1) Restart the workspace.
1) Observe the startup errors stemming from the wsmaster trying to interpret the invalid devfile (it might even be syntactically valid but internally inconsistent).

https://github.com/eclipse/che/issues/13527 is most probably a prerequisite for this to work reliably.

**Comment by sleshchenko** [comment]
I think this is a quite important issue it's why I added `need-triage` label.
People from time to time ask me why some behavior does not work, and the reason for it is that devfile is incorrect but Che Server neither Dashboard do not tell the user about it.

**Comment by tolusha** [comment]
I've just tried to set env variables for a sidecar container. 
It was very hard to understand why it didn't work, because there were no validation :(

**Comment by mmorhun** [comment]
My +1 to fix it.
We encourage users to write devfiles and so we should provide good UX for this. But now when a user copy-paste some part of devfile which is yaml-valid, but has some logical mistakes (for example reference for non-existing component) it will be accepted.

**Comment by ibuziuk** [comment]
@skabashnyuk @metlos could you please put the milestone based on the team priorities ?

**Comment by mshaposhnik** [comment]
Done & merged;
