### ISSUE TITLE
SSH key generation should happen workspace side

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#13522]
### Description
At the moment Theia SSH Plugin depends on ws-master. Need to get rid this dependency instead use native `ssh-keygen` tool for key generation and store directly in preferences in case upload existed key. 

Part of #13494

**Comment by vinokurig** [comment]
Is it really important to generate key on che-theia side rather than ws-master, if we steel need to store the keys in the ws-master db?

**Comment by sunix** [comment]
can't we keep the keys in user pref ?

**Comment by sunix** [comment]
generation and storage are 2 different things right ?
It doesn't make sense to have ssh key generation logic in ws-master.
