### ISSUE TITLE
Error occurred during creation a workspace from devfile

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13533]
### Description
@rkratky told me that when he was reviewing samples from documentation https://redhat-developer.github.io/devfile/ he has

such error 

> 
Error occurred during creation a workspace from devfile located at `https://raw.githubusercontent.com/redhat-developer/devfile/master/samples/web-nodejs-sample/devfile.yaml`. Cause: Devfile schema validation failed. Error: (/apiVersion):The object must not have a property whose name is "apiVersion".(/metadata):The object must not have a property whose name is "metadata".(/components/0/id):The string value must match the pattern "^((https?://)[a-zA-Z0-9_\-./]+/)?[a-z0-9_\-.]+/[a-z0-9_\-.]+/[a-z0-9_\-.]+$".(/components/1/id):The string value must match the pattern "^((https?://)[a-zA-Z0-9_\-./]+/)?[a-z0-9_\-.]+/[a-z0-9_\-.]+/[a-z0-9_\-.]+$".The object must have a property whose name is "specVersion".The object must have a property whose name is "name".

The goal of this task is to review our documentation and check that our samples are working.

**Comment by metlos** [comment]
This is probably caused by the samples already being upgraded to the latest version of the devfile schema, while the server to which @rkratky tried to deploy them to wasn't. 

@rkratky can you please confirm that the error persists if you use the examples with Che 7 RC2?

**Comment by skabashnyuk** [comment]
can't reproduce
