### ISSUE TITLE
Guidance for a user who wants to create their own workspace using a Devfile

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13538]
### Description
 We have an overview, we have reference (component types, command, attributres), and we have existing examples. But we don't have a step-by-step tutorial for a user who wants to create their own Devfile.

Have a look at, for example, the "Developing Che-Theia plug-ins using Che" section at https://www.eclipse.org/che/docs/che-7/extending-che.html#developing-che-theia-plug-ins-using-che_developing-che-theia-plug-ins -- there are a few typical, step-by-step procedures.

Here is proposed outline
https://docs.google.com/document/d/1CEgtZVd5Y1P4IKutpxiHkrgUS3258xZY0Yp0PZs950M/edit

**Comment by skabashnyuk** [comment]
@metlos what is the state of this task?

**Comment by metlos** [comment]
@skabashnyuk I've filled in what I could in the google doc and informed @rkratky about it last Friday evening. The only unfinished thing in the doc is the section about dockerimage endpoints where @sleshchenko promised to fill in the details.

**Comment by metlos** [comment]
note that the above mentioned document is kinda completed from the platform team perspective. Please reach out if you need any further information, explanation or you'd need to fill in something.

**Comment by skabashnyuk** [comment]
CC @l0rd @rkratky
