### ISSUE TITLE
Don't block workspaces based on old model if Che is still able to run them

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13534]
### Description
Right now Che is still available to run the workspaces which are based on the old model (GWT IDE and agents). But if a user has created one of those workspaces (from a stack or from a workspace definition), he'll be block with it, not being able to open it anymore.

The current behavior introduced by #13284 would be good, only when we would have remove completely the compatibility with the old model of workspaces. 
(Should this be parameterized? or enabled only when a flag will be present?)

Until those workspaces can still run, we should not prevent the user from running them.

### Reproduction Steps
- Create a workspace using a definition which will rely on the GTW IDE and Che 6 model 
- Stop it
- See that you can't run it anymore

**Comment by ibuziuk** [comment]
@slemeur I think we can close this now since `7.0.0-RC-1.1` has been released
