### ISSUE TITLE
[TS-SELENIUM] Cover "devfile" stacks by E2E tests

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13531]
### Description
According to changes in the stacks config approach(switching to using devfiles #12924 #13517) we should validate behavior of stacks introduced on dashboard.

**Comment by rhopp** [comment]
@Katka92 I know you were already working on this one. Could you please add the issues/PRs you were working on to this epic?

**Comment by Katka92** [comment]
@rhopp sure, I've create test for Java Vert.x. I don't have issue for that, PR is here: https://github.com/eclipse/che/pull/14558 . More information about this test can be found in PR description.

**Comment by Katka92** [comment]
We have covered Vert.x stack too, Python Django stack is in progress.
