### ISSUE TITLE
Show relevant kubernetes events in IDE

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13543]
It is not uncommon for che 7 plugin sidecars to fail at startup, for example because they don't have enough memory.
We should detect such common conditions and alert the user in a way that he can understand and take action.

**Comment by tsmaeder** [comment]
While a lot of info is available form the container logs, we should not expect a Che user  to understand them.

**Comment by amisevsk** [comment]
Related: https://github.com/eclipse/che/issues/13511
