### ISSUE TITLE
Unable to create workspace in che Artik Ide

### ISSUE THREAD

**Issue by yogeshg39** [eclipse-che/che#1354]
Hello,

I am trying to create new workspace in artik ide. I am selecting ARTIK from ready-to-go-stacks. But everyone time i try to create workspace it gives me this error:

Type docker of machine ws-machine in environment wksp-4hvs is not supported. Supported values: ssh, artik.

What am I doing wrong?

**Comment by ghost** [comment]
@yogeshg39 what version did you download? Did you run Artik IDE natively or in Vagrant?

**Comment by yogeshg39** [comment]
I have downloaded the latest version. And i am running it Vagrant.

**Comment by yogeshg39** [comment]
@eivantsov I have downloaded the latest version. And i am running it Vagrant.

**Comment by ghost** [comment]
@yogeshg39 issue confirmed. working on it. We will update the docker image with the latest stable version.

**Comment by ghost** [comment]
`vagrant destroy`
`vagrant up` should fix it. I have updated artik Docker image.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
