### ISSUE TITLE
[E2E] Update typescript tests according to workspace creation changes

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#13540]
### Description
According to workspace creation changes by [Create workspace from devfile](https://github.com/eclipse/che/pull/13469) we need to update existed typescript tests that create workspace from **Dashboard**.

New stacks list
![Selection_230](https://user-images.githubusercontent.com/7760565/59437850-01527680-8dfb-11e9-82f6-aa476142f4ef.png)

**Comment by Ohrimenko1988** [comment]
Done - https://github.com/eclipse/che/pull/13544
