### ISSUE TITLE
Single-user Che cannot create workspaces

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#13541]
### Description
It's no longer possible to create workspaces when running single-user Che. Clicking "Create workspace" just leads to a blank page with a loading bar across the top.

It seems to be related to devfile support on the UD; checking the browser console shows multiple error logs:
```
VM1151 app-5eab2342e7.js:110 GET http://che-eclipse-che.192.168.42.44.nip.io/dashboard/undefined/devfiles/ 404
```

### Reproduction Steps
1. Deploy Che built off current master in single-user mode
2. Attempt to create a workspace.

**Comment by sleshchenko** [comment]
@amisevsk Can you elaborate how do you deploy Che? `chectl`, `helm`, `operator`, k8s, os?

**Comment by amisevsk** [comment]
This is a two-week old minishift deployment; I'll delete and see if I can reproduce.

**Comment by amisevsk** [comment]
Looks like there was a config issue somewhere; I can't reproduce redeploying Che (using `chectl`). Closing.
