### ISSUE TITLE
Need to release RC 1.1 with a fix for unclickable  Che 6 run buttons

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13553]
### Description
In the Che 7 RC 1 release, it is still possible to create and run Che 6 workspace, but not possible to start an existing Che 6 workspace:

![image](https://user-images.githubusercontent.com/1461122/59587897-a49ad880-90e6-11e9-9a0f-074b7e44057b.png)

![image](https://user-images.githubusercontent.com/1461122/59587945-bbd9c600-90e6-11e9-9125-00a214bac7d1.png)

Basically, this creates UX inconsistency. Even though, "run" buttons are disabled navigation to the direct workspace links will start the existing workspace (links are available when hovering over the buttons):

![che 6 workspace stratup](https://user-images.githubusercontent.com/1461122/59588096-1c690300-90e7-11e9-8a72-512f5f9bb8e3.gif)

We need to release RC 1.1 with the following UX improvements:

- Change the UD message from "Not Compatible" to "Deprecated" / "To Be Deprecated" and change the wording a bit e.g. "This workspace is using old definition format which will be soon deprecated. Please follow the documentation to update the definition of the workspace and benefits from the latest capabilities."
- Make "Run" buttons clickable - both from workspace details / overview and "recent workspaces" section

**Comment by ibuziuk** [comment]
Draft PR - https://github.com/eclipse/che/pull/13556

**Comment by slemeur** [comment]
Will fix https://github.com/eclipse/che/issues/13534

**Comment by ibuziuk** [comment]
`7.0.0-RC-1.1` has been released. Closing
