### ISSUE TITLE
Remove mentions of `che.infra.kubernetes.machine_startup_timeout_min`

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13559]
### Description
On February 2018 was property `CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN` replaced by `CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN` and `CHE_INFRA_KUBERNETES_INGRESS__START__TIMEOUT__MIN` in [this commit](https://github.com/eclipse/che/commit/806a6da184c069e8cc0f6953c7af97e82994132a
), but the old property is still being used in multiple places.
For example [helm chart](https://github.com/eclipse/che/blob/7d91284af0611e45f222708e7d930bebcfd46b71/deploy/kubernetes/helm/che/templates/configmap.yaml#L32), [openshift template](https://github.com/eclipse/che/blob/master/deploy/openshift/templates/che-server-template.yaml#L107) etc.

**Comment by amisevsk** [comment]
I'll remove as part of https://github.com/eclipse/che/issues/14633

**Comment by amisevsk** [comment]
Just double checked, and this issue was fixed awhile ago.
