### ISSUE TITLE
Unable to install via helm with default values.yaml.

### ISSUE THREAD

**Issue by hhellyer** [eclipse-che/che#13558]
### Description

Che fails to install using helm with a template error. This seems to be because after: https://github.com/eclipse/che/pull/13455/files
there aren't default values for `che.workspace.pluginRegistryUrl` and `che.workspace. devfileRegistryUrl ` set.

### Reproduction Steps

Che fails to install into kubernetes using helm:
```
helm upgrade --install che --namespace che --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace="che" --set global.ingressDomain=${CHE_DOMAIN}.nip.io ./
```
I'm basing my command from the installation instructions for Docker for desktop here:
https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1

**OS and version:**    
Docker is:
Version 2.0.0.3 (31259)
Helm Version:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Diagnostics:** 

The error is:
```
Release "che" does not exist. Installing it now.
Error: render error in "che/templates/configmap.yaml": template: che/templates/configmap.yaml:87:14: executing "che/templates/configmap.yaml" at <.Values.che.workspac...>: can't evaluate field workspace in type interface {}
```

This seems to be caused by the new values:
`che.workspace.pluginRegistryUrl` and `che.workspace. devfileRegistryUrl `
here:
https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/configmap.yaml#L87

There are no values for these by default but if I uncomment:
https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml#L70
then I am able to install successfully.

**Comment by sleshchenko** [comment]
@monaka Can you take a look?

**Comment by monaka** [comment]
I saw #13560 and it will work as a hot-fix. But it's not good idea to override Che's default values by the default value in `values.yaml`, IMO.
I'll send the another PR within a couple of days.
