### ISSUE TITLE
mono not found

### ISSUE THREAD

**Issue by mercuriete** [eclipse-che/che#1356]
Description:
Shomehow mono is not in the path when you are using the mono workspace.

Steps to reproduce:
1- go to beta.codenvy.com
2- create new mono web-aspnet-simple
3- try to update dependencies

Output:
cd /projects/web-aspnet-simple && dnu restore
/opt/dnx/runtimes/dnx-mono.1.0.0-rc1-final/bin/dnx: line 14: exec: mono: not found

Reproducible always.

Solution: Provide a docker image with mono working.

**Comment by ghost** [comment]
@mercuriete the image has been fixed. For some reason, dnu and dnx disappeared from PATH.

It should be ok now. Let me know if it worked for you.

**Comment by mercuriete** [comment]
Yes it works!

Thank you for your work. eclipse che is amazing. :+1:
