### ISSUE TITLE
Provide clear naming for containers associated to plugins

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13586]
### Description
Righ now, some plugins are running in a specific container, but the name of the container is auto-magically generated and doesn’t provide any meaning to the end-user.

![Capture d’écran 2019-06-20 à 10 34 33](https://user-images.githubusercontent.com/1636769/59839180-8d5f2380-9350-11e9-8fd5-85346b16a744.png)
Here the container `0d2` is running the extension Java, but the user has no way to know it.

We should be providing a meaningfull name for the container, which could be based on the plugin(s) running in it. So when interacting with the « Che Workspaces » view, the user is not confused by the name of the « plugins » 

### Reproduction Steps
Create a workspace from java-maven stack and add a default project sample "spring-boot-http-booster"

**OS and version:**    
Che 7 RC 2 on OCP 4.1

**Comment by l0rd** [comment]
@amisevsk can we close it now after https://github.com/eclipse/che-plugin-registry/pull/168 ?

**Comment by l0rd** [comment]
I have tested the nightly and it's fixed

**Comment by slemeur** [comment]
Why the names are getting things like:
- theia-ide*8pz*
- vscode-typescript*2cz*
- che-machine-exec*t3y*

What is this "identifier"? What it is used for? What is the meaning to the end-user? 
Can we hide it?
Or at least do something like:
- theia-ide-*8pz*
- vscode-typescript-*2cz*
- che-machine-exec-*t3y*
(which will make it more readable)

**Comment by slemeur** [comment]
cc @amisevsk

**Comment by amisevsk** [comment]
@slemeur I agree, adding a dash would be helpful. IIRC the random chars were added by Alex G to avoid name collisions. 

WDYT about opening a new issue and leaving it to normal 7.0.0 triage?
