### ISSUE TITLE
Unconsistent error message displayed when error(s) in the devfile

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13582]
### Description
When starting a workspace from a devfile using the factory URL:
{che-host}/f?url={repo}

If the devfile is getting some errors, then the error is displayed in the notification popup, but there is another warning displayed.

![Capture d’écran 2019-06-19 à 12 05 15](https://user-images.githubusercontent.com/1636769/59771919-0efc7600-92ab-11e9-98c0-af10aa74bf09.png)

We should make sure that the error displayed in the screen (not the notification) is displaying the proper message so it helps the user to understand what is going on and how to overcome the situation.

### Reproduction Steps
Use the devfile from this version of the quarkus demo:
https://github.com/sunix/che-quarkus-demo/tree/c61aff32303e74d817bb81d9f28dde41a07db213

**OS and version:**    
Che 7 RC2

**Comment by amisevsk** [comment]
Also neither error presented is actually illustrative. Looking at the devfile in the [quarkus demo repo](https://raw.githubusercontent.com/sunix/che-quarkus-demo/c61aff32303e74d817bb81d9f28dde41a07db213/devfile.yaml), the message shown should mention that 
```yaml
specVersion: 0.0.1
name: quarkus-che-demo
```
is not valid; when I start a workspace using the old devfile format the message I get is more illustrative, as it mentions that the devfile needs an `apiVersion` field and `metadata.name`.
