### ISSUE TITLE
Show a confirmation dialog when Ctrl+W is pressed in the terminal

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13580]
### Description
`ctrl`+`w` is the standard "kill word" (aka werase) hotkey in terminal, and it's weird to see Che Theia tab closed after trying to erase the last word. This issue is a feature request to show a confirmation dialog when Ctrl+W is pressed in the terminal.

### Reproduction Steps
1. Start Che 7 Workspace.
2. Open terminal.
3. Press `ctrl`+`w`.
**Actual**: Che Theia browser tab is closed.
**Expected:** Ideal behavior would be the same as in native terminal - last word is erased, but I afraid whether it is possible to override such browser hotkey. So, at least a confirmation dialog should be shown before closing, because it's a typical thing when user press `ctrl`+`w` in terminal and does not to close tab.

**Comment by amisevsk** [comment]
This one has been bothering me for awhile as well -- I've closed a Che tab so many times :)

**Comment by azatsarynnyy** [comment]
Have you tried `confirmExit` preference?

![image](https://user-images.githubusercontent.com/1636395/59829353-e7a6b700-9345-11e9-980f-ed5acd9c426d.png)

**Comment by azatsarynnyy** [comment]
In Che Theia, the setting prevents reloading the page accidentally but doesn't prevent closing it.
In bare Theia, it works in both cases.

**Comment by slemeur** [comment]
so it sounds more like a bug @azatsarynnyy

**Comment by sleshchenko** [comment]
The setting of `Always ask` preference affects dashboard also even after workspace stopping.
@azatsarynnyy Do you think we need a bug for that?
![always_ask](https://user-images.githubusercontent.com/5887312/59906083-77189c80-9410-11e9-8e30-a5f1cde22ea3.gif)

**Comment by azatsarynnyy** [comment]
> Do you think we need a bug for that?

I think it is a bug. At least, that setting shouldn't affect the dasboard behavior.

**Comment by amisevsk** [comment]
Reopening this issue since I still hit this daily; capturing `ctrl+w` or at least popping a dialog should be the default -- we already catch `F5` and other browser hotkeys. Anyone who has muscle memory for using `ctrl+w` in a terminal will be affected by this issue.

**Comment by amisevsk** [comment]
I'll fight che-bot if I have to.

**Comment by benoitf** [comment]
@amisevsk you need to remove stale as well

**Comment by amisevsk** [comment]
Thanks @benoitf :)
