### ISSUE TITLE
Che-theia - My workspace view: if available, show the che commands/task that are available in a plugin side car

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13587]
### Description
If the devfile has commands defined for a plugin side car, it make sense to display them by default in the my workspace view

either:
- expand `plugins` if some che commands (task) available inside a plugin sidecar
- display a plugin side car with checommands ... inside the user runtimes

![Selection_301](https://user-images.githubusercontent.com/650571/59593554-715e4680-90f2-11e9-86aa-bbbc60a38e9b.png)

**Comment by sunix** [comment]
@l0rd @slemeur @tsmaeder @rhopp @nickboldt could we priotize that one ?

**Comment by slemeur** [comment]
+1 for  7.1.0 for me

**Comment by nickboldt** [comment]
Sure, 7.1

**Comment by slemeur** [comment]
Do you have an example plugin and how it would look in the devfile @sunix ?

**Comment by sunix** [comment]
@slemeur I was thinking that we would not change anything in the devfile

I was more thinking, in the workspace view, expanding all the container items that contains commands and collapse all the containers that doesn't contain any commands. whether these containers are user containers or plugin containers.

**Comment by slemeur** [comment]
ok pure UI/ux improvement

**Comment by mmorhun** [comment]
Done

**Comment by sunix** [comment]
@mmorhun so this is not doing what I had suggested in https://github.com/eclipse/che/issues/13587#issuecomment-519147581
