### ISSUE TITLE
Running terminal process can't be opened or terminated by IDE top menu

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13590]
### Reproduction Steps
 - Create and launch workspace from devfile <https://gist.github.com/Ohrimenko1988/93f5426f4ebc1705c55feb8ff0396a49>
 - Open workspace and launch "build" command
 - After a successful build, launch "run" command
 - Confirm notification and open application in preview widget
 - Close "run" tab in the terminal
 - Ensure that application still running
 - Click on "Show Running Tasks..." -> "run"
 - Pay attention that terminal tab is not opened
 - Click on "Terminate Tasks..." -> "run"
 - Pay attention that application is still available

**Expected behavior:**
After clicking "Show Running Tasks..." -> "run" sequence, the "run" tab of the terminal is opened.
After clicking "Terminate Tasks..." -> "run" sequence, the application is terminated.

**Observed behavior:**
After clicking "Show Running Tasks..." -> "run" sequence, the "run" tab of the terminal is not opened.
After clicking "Terminate Tasks..." -> "run" sequence, the application is still available.

### Attachments:

**Error logs anfter clicking "Terminate Tasks..." -> "run" sequence:**
![Screenshot from 2019-06-20 11-54-50](https://user-images.githubusercontent.com/22724619/59836433-293e5e80-9354-11e9-933e-33a5b950975c.png)

**Screencast:**
![Peek 2019-06-20 11-37](https://user-images.githubusercontent.com/22724619/59836478-3eb38880-9354-11e9-9dce-37e79483f395.gif)

**OS and version:**    
Che 7.0.0-SNAPSHOT

**Comment by slemeur** [comment]
Link to https://github.com/eclipse/che/issues/13584
