### ISSUE TITLE
Quickstart error!!!

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse-che/che#13606]
Quickstart way in windows:
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v D:/Eclipse/GitSpace:/data eclipse/che start
E:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid mode: /data.
See 'E:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by slemeur** [comment]
Hi @xinsuinizhuan,

The proper instruction to get started with Che on your local machine are here:
https://www.eclipse.org/che/docs/che-7/che-quick-starts.html

Where did you found information about the quick-start pointing to Docker?

**Comment by xinsuinizhuan** [comment]
I am so puzzle, i read the method in https://www.eclipse.org/che/docs/che-6/quick-start.html. I am a newer，and i am familiar with C/C++ with VS2015. But i want to user Eclipse che now，so i want to configurate the C/C++ in Eclipse che. I only find the way in below:
![Uploading 1561110680(1).jpg…]()

**Comment by xinsuinizhuan** [comment]
how i can run eclipse che in right way in windows? I  first install DockerToolbox.exe ,then run eclipse-che-4.0.0-RC11\bin\che.bat， but i only download the eclipse-che-4.0.0-RC11.zip，can not download newest。but the old not support stack c/C++，so i want use the che-7.0+。
