### ISSUE TITLE
Provide logs/outputs when Java LS is importing dependencies

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13601]
### Description
As a user, I'd like to be able to see the logs of the Java tooling when it is doing the first import of the dependencies. This would provide me feedback that the tool is still working and retrieving datas, instead of showing a progress stuck at "57%" .

![Capture d’écran 2019-06-21 à 08 28 38](https://user-images.githubusercontent.com/1636769/59902620-0ddc5d80-93ff-11e9-9458-df1346cb3267.png)

### Reproduction Steps
- Start a new workspace
- Select project spring-boot-http-booster.

**OS and version:**    
Che 7 RC 2

**Diagnostics:**

**Comment by tsmaeder** [comment]
This is beyond the control of Che and needs to be addressed in vscode-java or even jdt.ls

**Comment by gorkem** [comment]
Related to https://github.com/eclipse/eclipse.jdt.ls/issues/1121
