### ISSUE TITLE
Compatibility matrix

### ISSUE THREAD

**Issue by mlannan** [eclipse-che/che#1360]
I apologize if this is not the correct spot. I guess technically it is an issue with support. Is there a compatibility matrix for Eclipse Che? I am specifically looking for any known compatibility issues with older Docker versions e.g. Docker 1.6.

**Comment by ghost** [comment]
Docker 1.6 has issues with mounting prefixes `:Z` that we use.

**Comment by mlannan** [comment]
Ok. Thanks for the quick response!
