### ISSUE TITLE
Java tooling not starting (or taking long time) with default stacks

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13600]
### Description
Starting a workspace from the default stack is taking a while. The Java tooling seems to never end initializing.

[default-stack-java.mp4.zip](https://github.com/eclipse/che/files/3313206/default-stack-java.mp4.zip)

### Reproduction Steps
Create a workspace from the stack "java-maven". add project springboot-http-booster

**OS and version:**    
Minikube 1.0.0 + chectl
Mac OS 10.14.5

**Diagnostics:**

**Comment by tsmaeder** [comment]
Spring boot stuff (see, for example also the happy path test) can take > 5 mins to download dependencies. That's just the way jdt.ls handles things. There are other issues asking for better logging during startup. Nothign my team can do here. Closingè
