### ISSUE TITLE
how to  create project that in C/C++ with Eclipse che?

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse-che/che#13604]
I am a newer, I want to use Eclipse che to compile projects with C/C++, how to configure the C/C++ environment on Eclipse che?

**Comment by AndrienkoAleksandr** [comment]
@tolusha Could you help?

**Comment by xinsuinizhuan** [comment]
Could you help me? I want user the newest Eclipse che to compile project with c/C++?how shoud i do?

**Comment by tolusha** [comment]
@xinsuinizhuan 
Hello.
Sorry for the delay and thank you for the question.

If we are talking about development environment in Che 7 it is all about dev files [1]
Regarding C/C++ there is already a very good example how to cook a dev file for it [2] 
You can also find other examples of dev files in the registry [3]. 
You are welcome to contribute.

[1] https://redhat-developer.github.io/devfile/
[2] https://github.com/dneary/hello-world/blob/master/Tutorial.md
[3] https://github.com/eclipse/che-devfile-registry/tree/master/devfiles

**Comment by tsmaeder** [comment]
C++ Che 7 plugin coming soon.
