### ISSUE TITLE
che factory: should be able to override the name, source.repo, source.branch of the workspace that will be created in the url

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13617]
### Description
At the moment when creating a workpace from a devfile, we can use the factory url

For instance: https://che.openshift.io/f?url=https://github.com/eclipse/che-website will create a workspace from the devfile.yaml located in the repo and the workspace name will be generated from the one in the devfile: `che-website`.

If a workspace name already exists, it will suffix it with `_1`, `_2`, etc ... these name would become unusable for the user who would have to deal with dozen of workspace with the same name.

The goal of the issue is to add a new parameter in the query `name`:
https://che.openshift.io/f?url=https://github.com/eclipse/che-website&metadata.name=website-work-on-technology-section
would create a new workspace and name it `website-work-on-technology-section`

We could also add parameters like `projects.projectname.source.location` and `projects.projectname.source.branch` to override git location and branch

**Comment by benoitf** [comment]
@skabashnyuk Do you have feedback/thoughts on this improvement ?

**Comment by skabashnyuk** [comment]
Nice new feature. Why it's set only as p2 and set to 7.3.0?

**Comment by benoitf** [comment]
@skabashnyuk no previous triagers looked at this issue before so I was thinking it was not so important.
I think scope of `7.1.0` has lot of issues so I was thinking `7.2.0` or `7.3.0`

About severity I used P2 as it's an advanced usecase. 

@skabashnyuk do you have empty room for `7.2.0` and then we move it for `7.2.0` ?

**Comment by sunix** [comment]
To me this is very important, for example if you want to share a link to a PR: could provide the default devfile.yaml but override the branch.

**Comment by mshaposhnik** [comment]
Both code & docs PR merged, happy using.
