### ISSUE TITLE
Applications started with a che-commands (task) stop running on OpenShift

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13620]
### Description
This is likely happening for any kind of application.

- I could not reproduce on minikube
- I could reproduce on che.openshift.io.
- Not tried on minishift

When I start a user application  with che-commands (task) get down after some time

### Reproduction Steps
1. Start the factory https://che.openshift.io/f?url=https://github.com/eclipse/che-website
2. Run the command `start che-website`
3. Accept to expose the port 80 and open the link in a separate tab
4. Navigate through the running site
5. after navigating some time, the site becomes unavailable, it is also not possible to restart a task ...
![Eclipse Che | che-site-docs - Google Chrome_305](https://user-images.githubusercontent.com/650571/59955041-3d837800-9488-11e9-8512-9b75620c312f.png)

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
It may be related to https://github.com/eclipse/che/issues/13362

**Comment by sunix** [comment]
@l0rd @slemeur could we prioritize this ? for GA ?

**Comment by ibuziuk** [comment]
@sunix am I correct that it is not che.openshift.io specific? if so, I believe the title should be updated

**Comment by evidolob** [comment]
It seems after https://github.com/eclipse/che-theia/pull/315 and https://github.com/theia-ide/theia/pull/5695 problem was solved(I test it on che.openshift.io, and now it's work).
@sunix Can you verify?

**Comment by sunix** [comment]
> It seems after [eclipse/che-theia#315](https://github.com/eclipse/che-theia/pull/315) and [theia-ide/theia#5695](https://github.com/theia-ide/theia/pull/5695) problem was solved(I test it on che.openshift.io, and now it's work).
> @sunix Can you verify?

This is great, I will give a try. Thanks!

**Comment by sunix** [comment]
@evidolob it works great. Have these PR also been cherry picked on 7.0.0 branch ?

**Comment by evidolob** [comment]
No, to get it for 7.0.0 we need to change Theia version, we decided to do that on next release(on sprint end)

**Comment by l0rd** [comment]
@evidolob what does "change Theia version" mean? Move to next stable version of Theia? 
And "do that on next release(on sprint end)" means that you want to move to next Theia version right before the release of Che 7?

**Comment by sunix** [comment]
to me this is not fixed as long as it doesn't work on 7.0.0. 
I tried to use che-theia on che.openshift.io with that https://che.openshift.io/f?url=https://gist.githubusercontent.com/sunix/ee40b10e313b847143505d121d81348d/raw/2714a1ae971404d1635355545a1d96786102f163/devfile.yaml
and it seems that the issue is still here 
(devfile: https://gist.github.com/sunix/ee40b10e313b847143505d121d81348d#file-devfile-yaml)

**Comment by slemeur** [comment]
ping @evidolob

**Comment by sunix** [comment]
works will now with `eclipse/che-theia/7.0.0-next`
tested with https://che.openshift.io/f?url=https://gist.githubusercontent.com/sunix/ee40b10e313b847143505d121d81348d/raw/4ee7f796aca539350293e1a8a119299a2d84ad10/devfile.yaml
