### ISSUE TITLE
Support for https in eclipse che through external nginx

### ISSUE THREAD

**Issue by ankkumar-progress** [eclipse-che/che#13626]
### Description
We are in the process of deploying eclipse che.
The high priority task is to use https(SSL) connection.

After doing my research, it seems eclipse che doesn't support https.
Correct me if I am wrong.

We have an nginx server which redirects all the http calls to eclipse che.
I am trying to have https for the external server (nginx hosted) and internal communication of eclipse che can be http.

Below is my nginx.conf file:

![image](https://user-images.githubusercontent.com/45970796/60109615-488c2000-9788-11e9-908b-ddd7a22dc1cf.png)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests

But even after making the changes, I am getting the below error:

![image](https://user-images.githubusercontent.com/45970796/60109771-9143d900-9788-11e9-8d91-18fbf7888e8f.png)

We are running eclipse che in K8s environment.

**OS and version:**    
K8s cluster : 2 node and 1 master 

Master config:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

Node:

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Can anyone please help me out here?

**Comment by monaka** [comment]
Hmm? My Che have been running with SSL. https://che-banco.camino.pizzafactory.jp/
That is on Azure Kubernetes.
Actually my Che deployment is customized to use Traefik-ingress.
But it should be worked with Nginx-ingress even if you use the genuine Helm chart.

**Comment by ankkumar-progress** [comment]
Apart from https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values/tls.yaml , 
is there any other changes required to enable TLS.
Because the che container is not starting, readiness and liveness probe are failing.

While enbaling TLS, the [doc](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values/tls.yaml) says it is supported in single-host only.
But for single host we need the domain and not ip address.
Presently our app is running on ip address.
Can I use default-host instead of single-host?

**Comment by dmpe** [comment]
> Hmm? My Che have been running with SSL. https://che-banco.camino.pizzafactory.jp/
> That is on Azure Kubernetes.
> Actually my Che deployment is customized to use Traefik-ingress.
> But it should be worked with Nginx-ingress even if you use [the genuine Helm chart](https://github.com/eclipse/che/blob/44595cc8e19c73165033a66cc0bcc050bbff9c1e/deploy/kubernetes/helm/che/templates/ingress.yaml#L27-L32).

@monaka Would you be please so kind and share the code ? I also very much looking into this variante and would really appreciate it. If not possible, you can contact me over the email too. :)

**Comment by monaka** [comment]
@dmpe I want to release my configuration in public. But I'm recently swaped ...
And I'm going to add technical support options to PizzaFactory/Camino.
I'll be able to disclose the configuration to you earlier than my pull request.
