### ISSUE TITLE
Chectl uses deprecated method for creating workspaces from devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13623]
### Description
After merging of the following issue the method that checlt uses (POST -> /api/devfile) for workspace creating from Devfile is going to be deprecated https://github.com/eclipse/che/pull/13588
This method convert Devfile to WorkspaceConfig and then create a workspace with that.
It's needed to use new method in chectl `POST -> /api/workspace/devfile/`

### Reproduction Steps
1. Create a worspace with devfile via chectl.
2. Open its configuration in dashboard.
**Expected**: It's possible to edit workspace configuration in Devfile format.
**Actual**: It's not possible to edit Devfile since workspace is actually created with converted workspace config.

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
cc @l0rd @slemeur I think it's critical for GA otherwise chectl would continue to create workspaces that will stop work later.

**Comment by l0rd** [comment]
👍
