### ISSUE TITLE
Che 7 openshift cloud platform only saves files and folders temporarily.

### ISSUE THREAD

**Issue by tomevision** [eclipse-che/che#13628]
Hello, I am using Che 7 openshift cloud platform, i have created a project and different plugins and save them on a folder but after logging out and in again i can't find them on my folder. i think it only saves files temporarily.

**Comment by sleshchenko** [comment]
You told that you used [che.openshift.io](https://che.openshift.io) and there is enabled `ephemeral` mode by default (not sure if it's correctly displayed by UD).
More about this mode you can find in Che 7 Docs https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html#attribute-persistvolumes-ephemeral-mode
To solve the issue you can disable this mode. 
@tomevision Please free an issue if no additional info is needed.
