### ISSUE TITLE
Find a lighter sample for apache camel devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13639]
### Description
The sample project that is used in Apache Camel devfile needs ~26minutes for the first time buiild
![screenshot_20190614_140101](https://user-images.githubusercontent.com/5887312/60264946-16480300-98ed-11e9-8ac1-db25a2601a1a.png)

I think it's too much and it would be better to find a lighter sample for apache camel devfile.

**Comment by apupier** [comment]
the example is one of the lighter one for Apache Camel :-(

**Comment by benoitf** [comment]
could some of maven dependencies be cached in the image ?

**Comment by apupier** [comment]
> could some of maven dependencies be cached in the image ?

i think we can cache the dependencies related to the version of Fuse that is used for the example yes; it will be a great improvement.

**Comment by apupier** [comment]
@benoitf any example available to cache maven dependencies for a Maven stack?

What I imagine is to provide a DockerFile based on quay.io/eclipse/che-java8-maven:nightly adding a m2 repository for the example provided try to get inspiration from instructions here https://medium.com/@nieldw/caching-maven-dependencies-in-a-docker-build-dca6ca7ad612

Where should I put this DockerFile? In one of the Che repository? Or it is better to have it elsewhere?

if I write in the /home/user/.m2 , it will be automatically available?

**Comment by amisevsk** [comment]
Caching dependencies will be tricky since we're trying to move away from custom-built images. I don't know a good solution here. I'm not sure we should maintain a docker image for a specific version of Fuse, but I'm open to persuasion.
