### ISSUE TITLE
Please add support for Tomcat 9 / HTTP 2.0

### ISSUE THREAD

**Issue by mpouttuclarke** [eclipse-che/che#1364]
It would be nice to have HTTP 2.0 support so we can multiplex multiple parallel API requests.  This requires Tomcat 9.
https://tomcat.apache.org/tomcat-9.0-doc/apr.html  
https://http2.akamai.com/

**Comment by TylerJewell** [comment]
Hi @mpouttuclarke - These are items that would be considered after Tomcat 9 makes a GA release.  It's still alpha.

**Comment by mpouttuclarke** [comment]
Agreed, the HTTP 2.0 might be a little ways out, but the APR support goes way back.  
https://tomcat.apache.org/tomcat-8.0-doc/apr.html

I'll add a separate issue for APR support.  It will make a huge difference even without HTTP 2.0
