### ISSUE TITLE
chectl workspace:start -f devfile.yaml should create a `devfile` workspace 

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13642]
### Description
At the moment, when we create a workspace from chectl, the created workspace should be based on a a devfile (a show the devfile tab) and not a classic workspace config.

**OS and version:**    
Minikube che7 with chectl

**Comment by sunix** [comment]
@l0rd @slemeur good for GA ?

**Comment by sleshchenko** [comment]
Looks like it duplicates https://github.com/eclipse/che/issues/13623

**Comment by sunix** [comment]
yes duplicates
