### ISSUE TITLE
Using IP address instead of .nip.io by setting isHostBased = false doesnt work

### ISSUE THREAD

**Issue by mpxp** [eclipse-che/che#13647]
### Description
Trying to run che-server on minikube using helm.
As the URLs ending with nip.io is blocked by our network, using IP address to access the che-server running on AWS ubuntu machine and opening the dashboard doesnt seem to work.
I would like to see examples or documentation regarding this.

### Reproduction Steps
Here is how che-server is run:
`helm upgrade --install che --force --namespace che --set isHostBased=false --set cheImage=eclipse/che-server:nightly ./`

`http://che-che.<ip-address>.nip.io` does not work.
`http://<ipaddress>:<portno>` also doesnt seem to work.

**OS and version:**    
Ubuntu 18
Minikube

**Diagnostics:** 
Here is the output from helm upgrade:

$ helm upgrade --install che --force --namespace che --set isHostBased=false --set cheImage=eclipse/che-server:nightly ./
Release "che" does not exist. Installing it now.
NAME:   che
LAST DEPLOYED: Sun Jun 30 19:08:04 2019
NAMESPACE: che
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME  DATA  AGE
che   52    2s

==> v1/PersistentVolumeClaim
NAME             STATUS   VOLUME    CAPACITY  ACCESS MODES  STORAGECLASS  AGE
che-data-volume  Pending  hostpath  2s

==> v1/Pod(related)
NAME                  READY  STATUS    RESTARTS  AGE
che-654b786456-sdkvx  0/1    Init:0/1  0         1s

==> v1/Service
NAME      TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)            AGE
che-host  ClusterIP  9.55.133.185  <none>       8080/TCP,8087/TCP  2s

==> v1/ServiceAccount
NAME  SECRETS  AGE
che   1        2s

==> v1beta1/ClusterRoleBinding
NAME                         AGE
che-che-clusterrole-binding  2s

==> v1beta1/Deployment
NAME  READY  UP-TO-DATE  AVAILABLE  AGE
che   0/1    1           0          2s

==> v1beta1/Ingress
NAME         HOSTS                          ADDRESS  PORTS  AGE
che-ingress  che-che.192.168.99.100.nip.io  80       2s

**Comment by jglick** [comment]
Had a similar problem using Microk8s on Ubuntu. `sudo systemd-resolve --status` confirms that `192.168.*.*` are blocked for DNSSEC NTA. So I could only work around by adding to `/etc/hosts`

```
192.168.86.25 che-che.192.168.86.25.nip.io devfile-registry-che.192.168.86.25.nip.io keycloak-che.192.168.86.25.nip.io plugin-registry-che.192.168.86.25.nip.io
```

Not sure why Che is not simply using 127.0.0.1, which works fine with nip.io and Microk8s ingress.

**Comment by sleshchenko** [comment]
cc @metlos

**Comment by sparkoo** [comment]
@mpxp I can see 2 issues:

1] I can see that you have ingress host `che-che.192.168.99.100.nip.io`, which is default hardcoded ip, but almost certainly wrong one. You'll have to set `global.ingressDomain` to minikube's ip `--set global.ingressDomain=$(minikube ip).nip.io`. Now `http://che-che.<minikube-ip>.nip.io` should work.

2] `isHostBased` is no longer valid option. If you want to use IP address instead `.nip.io`, you'll have to set serverStrategy to default-host `--set global.serverStrategy=default-host`. With this option, `http://<minikube-ip>` should work.

**Comment by sparkoo** [comment]
I've filled 3 issues.
1] #14881 to fix helm deployment of registries for default-host. This can be workarounded by setting registries url to some registries instances (e.g. deploying them manually).
2] #14883 to fix loading of web resources. This is not a critical issue. Workspace is working in general. Some images or styles are not loaded. It affect UX.
3] #14886 Ingress is created for postgress service with invalid host. It is not needed at all for Postgres. 

Other than that, I didn't find any issues to work with default-host. I've tested both single and multi user mode.

I was using this helm command to deploy:
```
helm upgrade --install che --force --namespace che \
--set global.ingressDomain=$(minikube ip) --set global.serverStrategy=default-host --set cheImage=eclipse/che-server:nightly \
--set cheDevfileRegistry.deploy=false --set che.workspace.devfileRegistryUrl=${DEVFILE_REGISTRY_URL} \
--set chePluginRegistry.deploy=false --set che.workspace.pluginRegistryUrl=${PLUGIN_REGISTRY_URL} \
/deploy/kubernetes/helm/che/
```

**Comment by sparkoo** [comment]
@skabashnyuk I've answered that running Che with only minikube IP is possible(https://github.com/eclipse/che/issues/13647#issuecomment-537456994). It has some issues and I've created separate issues(https://github.com/eclipse/che/issues/13647#issuecomment-541772081) for that. Do you think we can close this one?

**Comment by skabashnyuk** [comment]
I think we did our part of the investigation, however, I would keep this issue open to see what other participants are thinking about

**Comment by sparkoo** [comment]
I'm not sure there are any other active participants.
