### ISSUE TITLE
Search/Filter in command palette mis behaving

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13650]
### Description
The search / Filter in the command palette is not properly working.

![search-command-palette](https://user-images.githubusercontent.com/1636769/60416939-653cb380-9bdf-11e9-8354-4d22be3d0d99.gif)

### Reproduction Steps
- Open a workspace
- Search for "git"
-> You don't have the command "Git: Clone..."
- Search for "clone"
-> You can now find the command "Git: Clone..."

**OS and version:**    
Che 7 RC 2 on minikube started with chectl.

**Comment by olexii4** [comment]
fixed in https://github.com/eclipse-theia/theia/pull/6225
