### ISSUE TITLE
Che Plugins panel is mentioning that the registry is invalid

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13669]
### Description
Che Plugins panel is mentioning that the registry is invalid
I don't understand how this is even possible, as I have been able to start a workspace with some plugins that are coming from a registry...

<img width="623" alt="Capture d’écran 2019-07-02 à 13 48 52" src="https://user-images.githubusercontent.com/1636769/60510620-25a1c480-9cd0-11e9-83b9-d743fa7219ff.png">

### Reproduction Steps
- Create a workspace from nodejs stack and add a sample project
- Start the workspace
- Open the "Che plugins" view from the menu "View"
--> You have a message saying "Your registry is invalid"

**OS and version:**    
Che 7 RC3
chectl/0.0.2-6631177 darwin-x64 node-v10.15.3

**Comment by vitaliy-guliy** [comment]
Fixed
