### ISSUE TITLE
Admin guide for user authentication and authorization

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13668]
### Description
We need to review our Admin guide for user authentication and authorization and make sure it's up to date and Che7 compatible.

**Comment by mshaposhnik** [comment]
So i think it's mostly about [this](https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-6/user-management/authentication.adoc) doc, i'm reviewed it, it looks almost ok for the Che server auth part, but still has Che 7  irrelevant info about ws-agent authentication, and has nothing about JWTProxy stuff on secure servers etc. 
So first question is where the renewed document should be placed, probably somewhere under the che-7  section, so @rkratky would you like to suggest a path for this new doc ?

**Comment by skabashnyuk** [comment]
@mshaposhnik https://docs.google.com/document/d/1gvki1dXWtq0Pha4Nv6yAVmuZfVx8U_MIHgv8C59t_3A/edit

**Comment by l0rd** [comment]
We are tracking `7.0.0` documentation issues on the endgame issue directly. I am ok with keeping this issue opened for planning purposes but I am removing it from `7.0.0` to make it consistent with the endgame issue.
