### ISSUE TITLE
Remove the view "Plugins" since we have "Che Plugins"

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13670]
### Description
While we've done a nice "Che Plugins" panel which is richer than the original "Plugins" panel from a plain Theia, I would think that we can remove the "Plugins" panel.

I would rename the panel "Plugins" instead of "Che Plugins".

<img width="601" alt="Capture d’écran 2019-07-02 à 13 45 01" src="https://user-images.githubusercontent.com/1636769/60510840-bbd5ea80-9cd0-11e9-9a30-4218d775a37d.png">

**Comment by vitaliy-guliy** [comment]
Need to be fixed. Sometimes two `Plugins` menu items are displayed

![Screenshot from 2019-09-02 16-31-40](https://user-images.githubusercontent.com/1655894/64123918-ecf09b00-cda5-11e9-8120-4e3a5f05ffb4.png)

**Comment by vitaliy-guliy** [comment]
Done
