### ISSUE TITLE
required root privilege to install packages using the Terminal on a containers

### ISSUE THREAD

**Issue by tomevision** [eclipse-che/che#13674]
I have an eclipse che 7 installed on my machine and i want to develop a new plugins using different packages and i need root privileges in-order to install this packages can you give me the password for the root user ?

**Comment by metlos** [comment]
Could you explain what you're trying to achieve in more detail? There is no root password I know of, nor have I ever needed one to create a plugin. If I knew more about your use-case maybe I could point you to some concrete examples.

**Comment by tomevision** [comment]
I want to install npm packages in order to add more functionalities to my Plugins and to do that i have to be a root user, that is why i need the root privileges

**Comment by metlos** [comment]
So Che 7 plugins are implemented as sidecar containers. So basically you define your docker image with everything you need for your plugin to work and then install it into Che (by listing it in a custom plugin registry).

The docs are being built for all this at the moment so the details are a little bit sketchy but you can take a look at https://github.com/eclipse/che-docs/ an see what you can figure out from there...

**Comment by monaka** [comment]
@tomevision I guess it will be resolved to change the global npm storage location where the plugin can write if you just want to execute `npm -g`.
