### ISSUE TITLE
Can't update Che 7 in Minishift to use newer devfile registry

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#13676]
### Description

Out of the box latest Che 7 RC2+ (`eclipse/che-server:nightly`) references a devfile registry without default projects, in https://che-devfile-registry.openshift.io/devfiles/

Supposedly this is fixed in master (and in prod preview):

https://che-devfile-registry.prod-preview.openshift.io/devfiles/angular/devfile.yaml

But even if I change my Che's config map to use:

```
CHE_WORKSPACE_DEVFILE__REGISTRY__URL: 'https://che-devfile-registry.prod-preview.openshift.io/'
```

I still get workspaces created from stacks w/o projects in them.

So... I tried building the devfile registry from source as per 

https://github.com/eclipse/che-devfile-registry/blob/master/README.md#build-eclipse-che-devfile-registry-docker-image

and deployed to my minishift, then updated the config to use the locally deployed registry: 

```
CHE_WORKSPACE_DEVFILE__REGISTRY__URL: 'http://che-devfile-registry-che.192.168.99.112.nip.io/'
```
But I still can't get stacks w/ projects in them OOTB.

### Reproduction Steps

Follow these steps:

https://github.com/redhat-developer/codeready-workspaces/blob/master/devdoc/building/che7-minishift-deployment.adoc

Then switch to a different devfile registry as noted above.

**OS and version:**    

Minishift 1.34
Che 7 nightly deployed w/ chectl

**Diagnostics:**

**Comment by nickboldt** [comment]
This might be a dupe / related to https://github.com/eclipse/che/issues/13665

**Comment by slemeur** [comment]
Yes this is going to be fixed by #13665

**Comment by nickboldt** [comment]
I think I was seeing this behaviour because of #13678 -- if we fix that one, this will likely be fixed too.

**Comment by ashumilova** [comment]
@nickboldt was this fixed by merging this PR - https://github.com/eclipse/che/pull/13825
can we close this one as well?

**Comment by nickboldt** [comment]
Yes, this is no longer a problem using this version of che-server:

```
eclipse/che-server                             nightly             f895d15ed0b1        20 hours ago        362MB
```
