### ISSUE TITLE
[TS_SELENIUM] Increase logging of tests steps

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13686]
For now we have tests output which reports just for failed or passed tests and stack trace.
![Screenshot from 2019-07-01 15-21-16](https://user-images.githubusercontent.com/22724619/60597840-50654900-9db4-11e9-9455-1205fba33e57.png)

It will be helpful to have more information about processes which happen in the tests. It will simplify debugging and searching a root reason in the case of failure.
Also it will give relevant information for the person who  launches tests locally, because it will show what test doing at that moment.

**Comment by Ohrimenko1988** [comment]
First of all, let's decide **WHAT** we should have. After that, we may decide **HOW** we will do that.
I suggest having something like that:
![Screenshot from 2019-09-06 12-03-34](https://user-images.githubusercontent.com/22724619/64416027-11e35780-d09f-11e9-8f81-c54e86571137.png)

Logs marked by "      -->" and "        ---->" should be spread to different layers and handled by environment variables, besides I suppose to have separated "log.txt" file with full log output.

**Comment by dmytro-ndp** [comment]
That logs look better. And currently there are primarily substeps need to be logged, to make it possible to localize particular failing operation:
```
        await driverHelper.navigateToUrl(workspaceUrl);
        await loginPage.login();
```

And it would be nice to write implementation specific info like `DriverHelper.waitVisibility(...`  into dedicated file. An example of such approach http://www.sulhome.com/blog/9/restify-project-seed-with-typescript-and-unit-test.
https://www.npmjs.com/package/log4js could be used to log into the file.

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp 
Here I mentioned that we should write a full log to the dedicated file.
https://github.com/eclipse/che/issues/13686#issuecomment-528777700

Also I am -1 for using something like "got to workspaceUrl" and etc instead of methods name because it will complicate debugging

**Comment by rhopp** [comment]
I was thinking we could implement something like four basic levels.
ERROR - for loging errors.
INFO - (default level) - This would print what we have now - suite and test names + duration...
DEBUG - something like "functional" level - logs on this level would be describing >what< is the test doing without any excessive boilerplate (like specific selectors etc. - kind of what Dmytro is suggesting in his comment).
TRACE - this is the finest level - here should be all the waits, clicks, and lowest level operation with all the selectors etc.

When executing tests, one should be able to select which logging level he want (by env var?).

Maybe a plus would be, if the log messages were prepended by filename & method name from where they were called, but I have no idea how easy/complicated that would be.

**Comment by Ohrimenko1988** [comment]
@rhopp @dmytro-ndp 
I have implemented some changes and output looks like:

**DEBUG**
![Screenshot from 2019-09-23 16-42-17](https://user-images.githubusercontent.com/22724619/65430905-5867de80-de21-11e9-9a84-32e2436db8aa.png)

**TRACE**
![Screenshot from 2019-09-23 16-34-29](https://user-images.githubusercontent.com/22724619/65430941-6453a080-de21-11e9-853a-2dc3e4fd1a0a.png)

What do you think about this?

**Comment by Ohrimenko1988** [comment]
What about adding xpath to the "DEBUG" level
For example:
```ProjectTree.expandItem <xpath>``` instead of ```ProjectTree.expandItem```

**Comment by rhopp** [comment]
I would say, that as a general rule of thumb, on the `debug` level I would like to know "What's happening", on the `trace` level I would like to know "how exactly is it happening". So - I would put selector to "debug" only in some certain cases, where it really matters (and the selector is not very long, etc.)

**Comment by Ohrimenko1988** [comment]
@rhopp 
What about this version?
![Screenshot from 2019-09-23 17-04-39](https://user-images.githubusercontent.com/22724619/65432732-679c5b80-de24-11e9-809e-2bbbb6b86497.png)

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: [newer variant](https://github.com/eclipse/che/issues/13686#issuecomment-534114876) mush closer to what was asked [here](https://github.com/eclipse/che/issues/13686#issuecomment-528790931).
Could this approach be spread to other methods like:
```
- Ide.waitRightToolbarButtonSelection "Login"
- Ide.waitAndClickRightToolbarButton "Login"
...
```

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp Of course, this is just a draft

**Comment by rhopp** [comment]
Nice ;-) I like that ;-)

**Comment by Ohrimenko1988** [comment]
Done
