### ISSUE TITLE
At the launch of the workspace, the IDE "GWT" is loaded instead of "Theia" IDE

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#13681]
### Reproduction Steps
 - Create the workspace by devfile with defined "Theia" IDE or by stack which defined on dashboard
 - Wait until workspace is started
 - Pay attention that "GWT" IDE has been loaded
 - If go to dashboard and load workspace again the "Theia" IDE will be loaded

**Expected behavior:**
The "Theia" IDE is loaded

**Observed behavior:**
The "GWT" IDE is loaded

**Attachment:**
![Screenshot from 2019-07-03 10-22-34](https://user-images.githubusercontent.com/22724619/60572516-707a1580-9d7e-11e9-9320-6244a6961b5e.png)

**OS and version:**    
Che 7.0.0-rc-3.0-SNAPSHOT

**Comment by slemeur** [comment]
In order to reproduce this issue, could you provide the devfile and the stack you have been selecting?

**Comment by sunix** [comment]
I can reproduce when i start a new workspace from a devfile with chectl

![Selection_312](https://user-images.githubusercontent.com/650571/60579611-bf767980-9d83-11e9-85e4-04aeb84309c5.png)

**Comment by rhopp** [comment]
@slemeur It's happening with devfile we are using for happy path as well as with devfiles from registry (I've just tried maven & .NET and it's reproducible on both, so I'm guessing it's general issue not tied to any specific devfile)

Possible cause of this issue:
https://github.com/eclipse/che/commit/edfda1398c657c407a69dbc0e71e3b394932f23c

**Comment by slemeur** [comment]
ok thanks. 
added the proper labels then.

**Comment by sunix** [comment]
FYI the plan is to revert https://github.com/eclipse/che/commit/edfda1398c657c407a69dbc0e71e3b394932f23c

**Comment by akurinnoy** [comment]
PR to revert bad commit: https://github.com/eclipse/che/pull/13699

**Comment by SkorikSergey** [comment]
Fixed
