### ISSUE TITLE
It is possible to create factory/workspace with invalid API version, but not start it

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#13687]
It is possible to create a factory with any API version, but it will be validated only at the start of the workspace by this method
https://github.com/eclipse/che/blob/caae00e21b2fd316560a406f2e1d8ad98edf1dad/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/DevfileConverter.java#L184

It is proposed to redo this so that schema validation would take care of it

**Comment by tsmaeder** [comment]
What is the scenario here? How would a user create such a factory?

**Comment by tsmaeder** [comment]
@mkuznyetsov ?

**Comment by mkuznyetsov** [comment]
could be typo in a devfile, or someone may use outdated devfiles (e.g. with 0.0.1 instead of 1.0.0 version)

**Comment by skabashnyuk** [comment]
@tsmaeder  I think this is a task more about the ability to create a workspace with REST API call from devfile where version is not 1.0.0 .

**Comment by mkuznyetsov** [comment]
Reproduction steps:
- Create a workspace from devfile, or edit existing workspace with invalid (for ex. `0.0.1`) API version
- Workspace will be saved, as it will pass all the schema validations. 
- But attempting to start such workspace would cause an exception during workspace startup, because of the separate validating method described in the issue.

So it was proposed to consider to have schema validation to take care of the invalid version instead, and so, not allow to devfiles to persist with invalid versions

**Comment by skabashnyuk** [comment]
Not reproduced 
![Знімок екрана 2020-03-04 о 10 46 41](https://user-images.githubusercontent.com/1614429/75866544-7a6c8080-5e05-11ea-92db-bd956d3a586e.png)
