### ISSUE TITLE
Add ability to import project with sparse checkout feature

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#13688]
When user defines the project's source, there should be ability to set the directory, which should be cloned as the only one from whole pointed repository, and this value should be properly handled.

Here is the example of project's source:
```
"source": {
      "type": "git",
      "location": "https://github.com/eclipse/che.git",
      "parameters": {
        "keepDir":"dashboard",
        "keepVcs": "false",
        "convertToTopLevelProject": "true"
      }
    }
```
**keepDir** - parameter contains the name of the directory,
**convertToTopLevelProject** - whether keep the directory as part of main project structure or bring it to top level.

**Comment by benoitf** [comment]
FYI I moved the issue through github from che-theia repository to try (so it's quite old issue)
