### ISSUE TITLE
GitHub identity is persisted locally after log-out

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#13694]
### Description
_It seems logout from CHE doesn't include logout from GitHub.
The problem was detected in the beginning in the CRW (https://issues.jboss.org/browse/CRW-323)_

**Reproduction Steps**
* _User1_ logs into CHE, performs authorization on his GitHub account, gets list of his projects and logs out from CHE
* _User2_ logs into CHE in the same browser window
* _User2_ can see and use the projects from _User1_ GitHub account

**OS and version:** 
Environment: _Openshift_   
7.0.0-rc-3.0-SNAPSHOT

**Additional information:**
* See video record:

![che-eclipse-github-persist](https://user-images.githubusercontent.com/5408906/60650739-670bae80-9e4d-11e9-8e69-a61294a4c488.gif)

**Comment by slemeur** [comment]
cc @vparfonov

**Comment by skabashnyuk** [comment]
@artaleks9 can you update the issue with the information about the environment that was used?

**Comment by skabashnyuk** [comment]
@ashumilova can you remind me what service dashboard is using to get a token? is this something from Che master side or it's communicating with Github directly?

**Comment by ashumilova** [comment]
@skabashnyuk  It uses our API method `/api/oauth/token?oauth_provider=github`

**Comment by skabashnyuk** [comment]
@ashumilova As I can see GitHub token is cached in LocalStorage.
![Знімок екрана  о 15 41 40](https://user-images.githubusercontent.com/1614429/61462281-a4565d00-a972-11e9-89d1-118f0a72068a.png)
From your POV how this usecase should be handled?

**Comment by skabashnyuk** [comment]
BTW any manipulation of user with github link to his kyecloak account will not be visible until this item exists in cache I think.

**Comment by gorkem** [comment]
@ashumilova shouldn't logout clear all the LocalStorage?

**Comment by ashumilova** [comment]
It's whether not storing token in local storage(trying session storage), that is shared between user sessions, or adding additional data to differ user tokens. Not sure logout could be tracked in all use cases (expiration for example).
