### ISSUE TITLE
che plugins view should have proper icons for each plugins/extensions

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13692]
@sunix commented on [Wed Jun 05 2019](https://github.com/eclipse/che-theia/issues/261)

### Description
At the moment all the plugins are shown with the eclipse che logo. We have to make the right changes (registry or picking from vscode marketplace) to display the right icons
![Selection_275](https://user-images.githubusercontent.com/650571/58944494-3e2ac780-8782-11e9-91b2-f9bed10f8c46.png)

**Comment by benoitf** [comment]
there is an existing issue no ?

**Comment by sunix** [comment]
just moved from che-theia

**Comment by sunix** [comment]
ok wrong manipulation ...

**Comment by benoitf** [comment]
@sunix you should click on 'transfer the issue' from che-theia issue (top right bottom)
https://github.com/eclipse/che-theia/issues/261

so it will keep history and github will manage redirect
