### ISSUE TITLE
che plugins view should have proper icons for each plugins/extensions

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13693]
### Description
At the moment all the plugins are shown with the eclipse che logo. We have to make the right changes (registry or picking from vscode marketplace) to display the right icons
![Selection_275](https://user-images.githubusercontent.com/650571/58944494-3e2ac780-8782-11e9-91b2-f9bed10f8c46.png)

**Comment by vitaliy-guliy** [comment]
There is a proposal pull request to plugin registry with icons for each plugin https://github.com/eclipse/che-plugin-registry/pull/221
But it's only first a step and have to be finished.

**Comment by nickboldt** [comment]
Closing dupe of https://github.com/eclipse/che/issues/14510
