### ISSUE TITLE
Prepare e2e test for Vscode GitHub Plugin

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13691]
### Description
On this moment VS code plugin is not merged in the Theia but already has all UI parts and works properly. According to the step 5 of the HappyPath scenario: https://github.com/eclipse/che/issues/12728  we can start implementing Page Objects, methods for interaction with widget and add some steps from the scenario.
After merging Vs code plugin we will have working skeleton of the step 5 which can be added quickly to main scenario.

**OS and version:**   CHE 7, upstream, VS code plugin

**Comment by musienko-maxim** [comment]
After implementing steps for adding authorization token (it activates Github PR plugin). i've got unexpected problem for the test: for creating PR we need obtain repo with ssh link. Currently - it just one way for creating PR's with PullReq. plugin. In this case -  we should have ssh keys in the workspace. If we try to clone the project with ssh link which in the dev file - we won't get cloned project and any warning/error messages like permission denied or something like that.
So, as possible workaround - i think we have 2 options:
* Add the ssh keys in the ws. before test and after that, clone the Petclinic project by ssh link. And make PR workflaw
* Waiting for implementation of authorization with GitHub oAugh and use this option. I need advise

**Comment by rhopp** [comment]
@musienko-maxim Do you know what is the current situation with Github Pullrequest plugin? Does it work? How is the experience (UX)?
