### ISSUE TITLE
Proposal optimize UX of Dashboard

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13701]
### Description
ATM, when user is landing to the dashboard, he can create a workspace from one of the samples (devfile) and can just `create and open`.
He can also change the projects to clone and than it will do some magical stuff ( removing the commands, etc ...)
It is hard for the user to actually make some changes on the language to use, the container image to load, the commands to run because once you click on `Create and open`, you will need to stop the workspace, make your ajustment and restart the workspace.

#### allow devfile edit in an optional step of the workspace creation
- By default user chooses the sample. (we are removing the `import project section`)
- We add a button called `create and edit` or `advanced editing`. It would land to a workspace with these tabs or sections prefiled with the sample devfile but you could edit (or not):
   - projects (the previous import project section)
   - components (language, che vscode plugin, dockerimage, etc ...)
   - commands
   - devfile (sources)
 
#### do not allow import project from Dashboard
1. Or we just allow the user to make everything in the IDE and synchronize the devfile properly. But in that case, we should remove the import file section.
There are things that the user won't be able to change (AFAIK) without restarting the pod: changing the components (adding a container image or a changing the vscode extension to use). How would the UX to add/edit a container image inside Theia ... maybe from the `my workspace` view.

2. And/or we should have a devfile view to edit the current workspace devfile.

**Comment by l0rd** [comment]
Don't we already have the "create and continue editing" button?

**Comment by sunix** [comment]
![Selection_322](https://user-images.githubusercontent.com/650571/60682517-da381380-9e93-11e9-8844-a489394fb72a.png)

Woow you are right, it is there ... but I couldn't see it before ...

What about making it more visible: 2 buttons side by side rather then the drop down arrow button. + a tab to edit the commands.
