### ISSUE TITLE
Failed to deploy by Helm

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13704]
### Description

I couldn't deploy che-devfile-registry by Helm.
I guess `rollingParams` is not provided on the vanilla K8s.

### Reproduction Steps

```
helm upgrade --install --namespace=camino che-devfile-registry --values=values.yaml .
```

**OS and version:**    

the master branch commit 5a64991361242e6e

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Diagnostics:**

```
helm upgrade --install --namespace=camino che-devfile-registry --values=values.yaml .
Release "che-devfile-registry" does not exist. Installing it now.
Error: validation failed: error validating "": error validating data: ValidationError(Deployment.spec.strategy): unknown field "rollingParams" in io.k8s.api.extensions.v1beta1.DeploymentStrategy
```

**Comment by monaka** [comment]
@benoitf I presume this is a bug. AFAIK, no `rollingParams` available on K8s. I googled and I got it is available on Openshift.

**Comment by skabashnyuk** [comment]
afaik our helm has no devfile registry definition and we are going to solve that here https://github.com/eclipse/che/issues/13633. @monaka am I miss something?

**Comment by sparkoo** [comment]
@monaka Hi, can you please try it now, after https://github.com/eclipse/che/pull/13890 was merged?

**Comment by monaka** [comment]
@skabashnyuk My mistake. I should open this issue on `eclipse/che-devfile-repository`. And I see this issue was fixed by https://github.com/eclipse/che-devfile-registry/commit/91f5b9bc220ceb6105ba17aaa7b6a7361367e880

@sparkoo Thank you for pointing it out. I read #13890 and it will fix this issue.

I close this as fixed.
