### ISSUE TITLE
Include vscode-wsdl2rest VS Code extension

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13707]
https://marketplace.visualstudio.com/items?itemName=camel-tooling.vscode-wsdl2rest

@bfitzpat already tested to install it in Theia and it is working. next step is to have it in Che :-)

**Comment by bfitzpat** [comment]
Tested this PR https://github.com/eclipse/che-plugin-registry/pull/136 - and it worked on che.openshift.io with the v3 version of the plug-in metadata.
