### ISSUE TITLE
VS Code plugin is not activated when installed in its own container

### ISSUE THREAD

**Issue by keithchong** [eclipse-che/che#13710]
I'm using 7.0.0-beta-5.0

Steps to reproduce

1. Select View->Che Plugins
2. From the more options drop down menu (three dots), select Add Registry
3. Follow the prompts to provide a name and the URL
--> I get a "Your registry is invalid" message in white text and red background

![Screen Shot 2019-07-04 at 3 33 58 PM](https://user-images.githubusercontent.com/7726022/60685460-32a9e980-9e71-11e9-87aa-405d2d429d1e.png)

My registry is local and is up.  I compared it to the openshift registry.   See screen caps.

URL: http://localhost:8080/v3/

![Screen Shot 2019-07-04 at 3 17 12 PM](https://user-images.githubusercontent.com/7726022/60685270-21141200-9e70-11e9-9fd9-a5d47eaec65c.png)

URL:  https://che-plugin-registry.openshift.io/v3/

![Screen Shot 2019-07-04 at 3 17 38 PM](https://user-images.githubusercontent.com/7726022/60685275-296c4d00-9e70-11e9-96ec-645381e463b3.png)

Perhaps related? https://github.com/eclipse/che/issues/9208

Unrelated issue is how do you remove unwanted registries?  (There is no action for it)

**Comment by slemeur** [comment]
cc @vitaliy-guliy 
Related to: https://github.com/eclipse/che/issues/13669

**Comment by tsmaeder** [comment]
@keithchong when you say "localhost", you mean your Mac, right? My suspicion is that Theia resolves localhost inside it's own container,  where no registry is running. When you run the registry at a publicly available address, does it work?

**Comment by evidolob** [comment]
@tsmaeder Are right, @keithchong you should use public IP, `localhost` is not available from Theia container.

**Comment by tsmaeder** [comment]
@evidolob is there a better diagnostic available somewhere ("http://localhost:8080 is not reacheable" or some such thing? 
But definitely not a 7.0 bug.

**Comment by skabashnyuk** [comment]
@keithchong how did you run Che? With k8s or OpenShift?

**Comment by vitaliy-guliy** [comment]
@keithchong your registry mush be accessible from Theia container.
I prefer to use github. Try this one to test https://raw.githubusercontent.com/vitaliy-guliy/che-theia-plugin-registry/master/plugins/plugins.json
Just point a json file as a custom registry.

**Comment by keithchong** [comment]
> @keithchong how did you run Che? With k8s or OpenShift?

Hi @skabashnyuk , I was running Kubernetes in Docker Desktop.  I followed the instructions here:
https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1

**Comment by keithchong** [comment]
> @keithchong your registry must be accessible from Theia container.
> I prefer to use github. Try this one to test https://raw.githubusercontent.com/vitaliy-guliy/che-theia-plugin-registry/master/plugins/plugins.json
> Just point a json file as a custom registry.

Hi @vitaliy-guliy , I was able to add your registry and install the Hello-World front-end plugin.

**Comment by keithchong** [comment]
Good news.  I made more progress and did not see that error message, and I can see the list of the plugins in my registry.  However, after I installed the plugin, and restarted the workspace, I got a 502 Bad Gateway.  Do you have any guidance on this?

![Screen Shot 2019-07-08 at 12 57 50 PM](https://user-images.githubusercontent.com/7726022/60828410-51b1bf80-a180-11e9-8b04-fb1b42882bc9.png)

**Comment by keithchong** [comment]
> cc @vitaliy-guliy
> Related to: #13669

I moved up to 7.0.0 RC2 and I can reproduce that issue.  It's for the two default registries too.

**Comment by keithchong** [comment]
Hi @skabashnyuk , as mentioned, I'm blocked using RC2 (and RC1) due to #13669, but, I got the extension to install using 7.0.0 Beta 5 (See my screenshots).  However, my 'OpenAPI' commands do not show up in the command palette.   How do you check if the extension actually got extracted?   I checked the logs in the workspace container/pod, but I didn't see anything unusual.  The install-time messages seemed ok too:

![Screen Shot 2019-07-09 at 6 31 18 PM](https://user-images.githubusercontent.com/7726022/60937213-8d8e7700-a29d-11e9-9a91-e9806a66aee8.png)

My registry is located here if you want to try it out? 
https://raw.githubusercontent.com/keithchong/registry/master/plugins.json
Install the 'latest' version of the extension.

**Comment by skabashnyuk** [comment]
> How do you check if the extension actually got extracted?

@keithchong that is something that plugin brokers are doing. @ibuziuk @davidfestal am I right? Can you suggest something how to enable logs on brokers?

**Comment by keithchong** [comment]
Good news.  I see my commands in the palette now.  The issue was with the link as referenced in the meta.yaml file.  I think the extension vsix package was never extracted. 

It will be good if we could check the logs regardless.

**Comment by keithchong** [comment]
Hi @skabashnyuk , I looked at https://github.com/eclipse/che/issues/12447 and https://github.com/eclipse/che-plugin-registry/  and both help.  I noticed that the VS Code extension is run (I believe by default) in the che-theia container.    How do you set it up so that the extension is run in a different container?   The reason for this is that I'd like to customize the container because the VS Code extension needs docker, and I want docker installed in the container.  (The che-theia container does not have docker installed)

In the meta.yaml file, I had this:

spec:
  containers:
  - image: keithchong/codewind-openapi-server
    name: ibm_codewind_openapi_latest
  extensions:
  - https://github.com/keithchong/registry/raw/master/codewind-openapi-tools-0.2.1_2019-07-11-1259.vsix

The image mentioned above that currently is Dockerhub, contains Docker and a node server which is run so that the container does not exit.

After I installed the extension, I see this container running, but the VS Code extension does not appear to be running.  (However, I see the vsix file in the plugins folder in the che-theia container).

Is this the correct approach?   If not, what should it be?

**Comment by slemeur** [comment]
ping @skabashnyuk

**Comment by skabashnyuk** [comment]
@keithchong This issues is missing some context. To be able to reproduce it can you add some information according to the latest "bugs" template



### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by slemeur** [comment]
cc @l0rd

**Comment by l0rd** [comment]
@keithchong there are 2 documents that explain:
- [How to use VS Code extensions in Che workspaces](https://docs.google.com/document/d/1gZHKXe1GEduY48RgntMUrqjSs9llq8WpCmgqssY5Ikw/edit#heading=h.s7tesxgcl8k3)  
- [How to retrieve logs](https://docs.google.com/document/d/182PBN5LBNTlbhsqqsb5QHg9t5HNK3rSLrnIMPSGjyN0/edit#heading=h.12z5y7kdgm0z) (in particular workspace logs)

This are google docs that are being moved to https://www.eclipse.org/che/docs/

If you don't have access to the google docs I can provide it for you.

As a side note please update the title of the issue or close this one and create a new one if you don't have problems with the registry anymore.

**Comment by slemeur** [comment]
@keithchong : Does the docs helped you? Wondering to triage the issue differently? Also if you can just check the boxes from @skabashnyuk comments that will help us to reproduce the issue: https://github.com/eclipse/che/issues/13710#issuecomment-514083068

**Comment by vitaliy-guliy** [comment]
@keithchong is it better to create another issue related to activating the VS Code extension and close this one? Giving a look at the issue description I still have feeling that you are solving a problem with plugin registry.
