### ISSUE TITLE
Old identityProvider and postgres container images not updated to latest defaults on Operator update.

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#13714]
When the Che operator is updated (for example from `beta-5.0` to `rc-2.0`), and a Che server CR was previously started with the default Keycloak docker image (empty string), the Che server is not upgraded with the new default keycloak image after operator upgrade, but stays on the effective Keycloak version that was initially deployed.

**Comment by nickboldt** [comment]
We've seen this in downstream CRW 1.2 too. And it's not just the identity provider (Keycloak/SSO) image but also the postgres db that remains on the image:tag of the initial deployment.

WORKAROUND is to patch the deployment, as we do here:

https://github.com/redhat-developer/codeready-workspaces-deprecated/blob/6.19.x/operator-installer/migrate_1.1_to_1.2.sh#L280-L306

But a better solution would be ... um, better. :)

**Comment by ibuziuk** [comment]
@davidfestal can we close this one ?

**Comment by davidfestal** [comment]
I assume yes, even though it is not *in production* of course.

**Comment by ibuziuk** [comment]
Fixed in https://github.com/eclipse/che-operator/pull/72 and operator nightly builds
