### ISSUE TITLE
Shared workspaces

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#1371]
Yesterday we had one meeting related to sharing workspace feature and
Major feature what we've discussed was url format in ide.
Now it looks like http://codenvy.com/ws/workspacename

Since we decided to move from workspace owner's model to permission-based model
we think it would be logical to move to another url schema. 

Our proposal is to make url to looks like this 
http://codenvy.com/ws/namespace/workspacename

To make it possible to reference workspace with "readable" URL (as requested) 
and keep workspace name meaningful  (not make user to invent some name for the sake of
uniqueness) we need some prefix - a namespace for it.

Apparently this namespace (same as workspace name itself) should be URL
path friendly to not to encode (making unreadable) it.
This namespace can be bound to:
- username (the simplest way we start with)
- account (organization or personal) which "owns" the workspace 
  (strictly speaking which owns resources this workspace uses) - will be implemented 
  along with organization/account things  
  And should be a standalone field "Namespace" to be filled in Account profile.

**Comment by TylerJewell** [comment]
-1 on the format.  

It is confusing to have `/ws/namespace`.  The user will expect that after `/ws` that they have a name of a workspace, not a namespace.

**Comment by skabashnyuk** [comment]
http://codenvy.com/ide/namespace/workspacename
your variant?

**Comment by slemeur** [comment]
-1 on the format too.

Would go with http://codenvy.com/namespace/ws/workspacename

**Comment by TylerJewell** [comment]
-1.  That is equally confusing.  We need to explore possibility of: 
http://eclipseche.com/namespace/workspace, or http://eclipseche.com/workspace

**Comment by skabashnyuk** [comment]
We already made it once. It brings a lot of problems with codenvy corporate site. 
If we want to do like this http://eclipseche.com/namespace/workspace we should create a list of 
ALL first level pages. And this list should not be very big and can't be easy changed.

**Comment by gazarenkov** [comment]
I guess the topic of discussion is not a /ws prefix, we decided a long time
ago that is the prefix for IDE application and we use it like this all the
time
It can be easily changed to /ide for example if needed.

But changing the URL template (like removing it for IDE app) impacts the
infrastructure (the site in particular, as Sergey mentioned) so it should
be decided carefully and double checked separately as dedicated topic.

Gennady Azarenkov - CTO @ codenvy.com

On Fri, May 27, 2016 at 4:55 PM, Sergii Kabashniuk <notifications@github.com

**Comment by TylerJewell** [comment]
Also, I think we should not take as much care here for codenvy.com.  Today
we have this situation where codenvy.com runs both the product and the
corporate web site.  Let's go ahead and separate those and have the
corporate site be codenvy.com.  We can move the product to codenvy.io.
This will allow the corporate site to maintain its web app structure and
the product will no longer need to accommodate any rules for the corporate
site.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

On Sat, May 28, 2016 at 7:48 AM, Gennady Azarenkov <notifications@github.com
