### ISSUE TITLE
Plugins don't start the first time

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13724]
Just noticed, but almost each time I start a workspace (with chectl and a devfile), plugins are not loaded. I have to refresh the page.

Environment:
- minikube
- che single user mode started with `chectl`

When i start a workspace with the devfile https://github.com/sunix/devfiles/blob/master/che-in-che/che-theia-remote.devfile.yaml , accessing to the workspace is opening theia but plugins are not loaded: 

- no container view
- projects not being cloned
- no welcome page

Refreshing the page works

**Comment by AndrienkoAleksandr** [comment]
We could not reproduce this issue. Fill free to reopen if it's reproducible
