### ISSUE TITLE
Workspace does not start

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#13720]
### Description
_There is a deployed Eclipse CHE and_ 
_workspace does not start:_

![ci-codenvycorp-com-view-qa-nightly-job-che-integration-tests-multiuser-master-ocp](https://user-images.githubusercontent.com/5408906/60705491-ebbf0100-9f0f-11e9-80d5-548af7d3ec09.png)

It is detected on _qa-nigtly_ job:
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/configure

**OS and version:**    
7.0.0-rc-3.0-SNAPSHOT

**Comment by vparfonov** [comment]
I will fix it

**Comment by tsmaeder** [comment]
We need some more context here: how is this workspace started? How is the registry configured? It seems it's trying to resolve plugins against a registry deployed together with the workspace?

**Comment by sunix** [comment]
I can reproduce it with chectl server:start,
Create a new workspace from the dashboard choosing any of the `stacks` it fails

**Comment by tsmaeder** [comment]
@sunix I'm not sure that is the same failure: @artaleks9 is not pointing to the registry at che.openshift.io.

**Comment by SkorikSergey** [comment]
This issue is fixed by https://github.com/eclipse/che-plugin-registry/commit/d1a542bc8517c5ac5b04b4a7096e2f3f1d288e99 and workspace start works with local plugin registry.

**Comment by sunix** [comment]
> This issue is fixed by [eclipse/che-plugin-registry@d1a542b](https://github.com/eclipse/che-plugin-registry/commit/d1a542bc8517c5ac5b04b4a7096e2f3f1d288e99) and workspace start works with local plugin registry. But https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/ still doesn't have `che-theia` plugin `7.0.0-rc-3.0` version and workspace starting fail.

https://github.com/eclipse/che/pull/13776#issuecomment-508710924
updating is not enough

**Comment by artaleks9** [comment]
@tsmaeder Sorry for not enough info when I created issue, I was a bit in a hurry to sound problem before my 'standup'.. and then had active conversation with @vparfonov  about it. 
@SkorikSergey Thanks for your timely comment.

**Comment by l0rd** [comment]
@artaleks9 can we close this issue?

**Comment by artaleks9** [comment]
Now it works as expected as to local as to external `che-plugin-registry`.
