### ISSUE TITLE
How to use eclipse-che-theia-terminal extension in a project 

### ISSUE THREAD

**Issue by ankkumar-progress** [eclipse-che/che#13726]
In our project, we are trying   to use eclipse-che-theia-terminal. As it is not released to npm , we are downloading from [github](https://codeload.github.com/eclipse/che-theia/zip/v0.4.0) on the fly and just keeping the folder eclipse-che-theia-terminal.
When I am trying to build eclipse-che-theia-terminal I am getting errors. I tried some steps to remove the errors and in fact, I succeeded in removing  few of them

1. You are using concurrently without including the npm package in package.json
![image](https://user-images.githubusercontent.com/45970796/54359891-95d8fb80-4689-11e9-9867-46a9c4e6cfb7.png)

So I installed the npm pakcage globally and it worked. Maybe you should consider putting the package in depedency tag in package.json.

2. Later on I recognized that the extension is also depedent on ../../configs/* folder. Just to make it work in my case I replaced the script with the below one 
![image](https://user-images.githubusercontent.com/45970796/54360336-b0f83b00-468a-11e9-8326-1119f3b85217.png)
But still after building it, I am getting the below error

![image](https://user-images.githubusercontent.com/45970796/54361006-1d276e80-468c-11e9-8f87-2f1a3bea7606.png)

Is there any simple way to use this extension  which should work out of the box?

cc @AndrienkoAleksandr

**Comment by benoitf** [comment]
already done
