### ISSUE TITLE
Stop running task

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13737]
### Description
We should have a functionality to stop/cancel running tasks.
For example if some task executes a process `sleep infinity` there are should be a way to cancel this process without using a terminal.

**Comment by sunix** [comment]
By the way, now we can `Ctrl-c` to stop a running task as tasks are interactive.
But would be nicer to `Ctrl-c` when you close the tab right ?

**Comment by vparfonov** [comment]
depends on #13722

**Comment by RomanNikitenko** [comment]
depends on https://github.com/eclipse/che/issues/14659

**Comment by RomanNikitenko** [comment]
I implemented stopping `che` tasks by sending `ctrl+c` to corresponding terminal widget, but unfortunately, I faced with the issue https://github.com/eclipse/che/issues/14887
