### ISSUE TITLE
Add support for cloning svn repository

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13733]
### Description
Currently we support only git repositories in Factory plug-in which is responsible for cloning projects according to workspace configuration. But some projects use snv repsitories and it would be good to have support for them.

**Comment by azatsarynnyy** [comment]
relabeled to `area/plugins` as it's related to https://github.com/eclipse/che-theia/tree/master/plugins/workspace-plugin

**Comment by ibuziuk** [comment]
putting P2 for now, but feel free to update the severity based on the team/product priorities

**Comment by nickboldt** [comment]
Opened nearly 20 months ago, no progress. Going out on a limb and closing this one.
