### ISSUE TITLE
Terminal is empty on Firefox

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13736]
![Eclipse Che | cheTheia-in-che - Mozilla Firefox_194](https://user-images.githubusercontent.com/650571/54520645-7384fd80-4969-11e9-947a-0f0beebd5671.png)

```
TypeError: n.rules is undefined[Learn More] theia.db35f996195e938bb4b2.js:1:1937593
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml;base64,PHN2ZyBmaWxsPS… (“img-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at ws://server6pjgqy1m-ws-che-machine-exec-server-4444.192.168.99.100.nip.io/connect (“default-src”).
Error: Failed to create terminal server proxy. Cause: [Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: https://assets.openshift.net/che/theia_artifacts/vendors.49255968b10295ada657.js :: w :: line 1"  data: no]
```

**Comment by johnmcollier** [comment]
I can reproduce on Firefox 67.0.4. Seems to also affect the CSS on the Che-Theia welcome page:
<img width="1086" alt="Screen Shot 2019-07-08 at 5 26 40 PM" src="https://user-images.githubusercontent.com/6880023/60843780-969c1d00-a1a5-11e9-9223-423004b93b9d.png">

**Comment by esubah1989** [comment]
I also got this error in Chrome.

**Comment by sunix** [comment]
still have the issue @davidfestal 

![Selection_391](https://user-images.githubusercontent.com/650571/63013579-ce753f00-be8c-11e9-9a89-ce1b3e2381bb.png)

**Comment by ibuziuk** [comment]
moving to 7.2.0 according to the firefox related epic - https://github.com/eclipse/che/issues/14015

**Comment by kameshsampath** [comment]
I was able open the terminal in FF 69, but i do see some errors in the developer console

![image](https://user-images.githubusercontent.com/947745/64219520-5b457280-cef8-11e9-8acc-b62d5390fa03.png)

**Comment by sunix** [comment]
guys,
Looks like i can now open a terminal magically with firefox
![Eclipse Che | raffle-k972n - Mozilla Firefox_430](https://user-images.githubusercontent.com/650571/67787167-62a87880-fa70-11e9-8fc6-a673bf914806.png)

**Comment by kameshsampath** [comment]
yes it has been @sunix with firefox latest.

**Comment by AndrienkoAleksandr** [comment]
It is working with che 7.3.0. For che 7.2.0 and 7.2.1 issue is reproducible.

**Comment by AndrienkoAleksandr** [comment]
Che 7.3.0 I tested with 56, 60.4esr, 68.2esr(latest esr) and latest firefox 70.0, forks fine, so I close issue. Feel free to reopen if it is reproducible with latest Che.
