### ISSUE TITLE
che:theia init should have an option to use local sources instead of cloning the che-theia repo

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13738]
### Description
Following the work done in https://github.com/eclipse/che-theia/issues/45 , when running the command `che:theia init`, it would be nice to set a local folder to be used instead of cloning the che-theia repo:

```
che:theia init --alias:github.com/eclipse/che-theia=../che-theia
```
It would solve the problem some developer are having with CI where they run a build on a PR but the changes are not taken in account because the build is fetching master branch of the same repo

It would also solve some issue when working locally and developer would like to use a local cloned che-theia repo

**Comment by l0rd** [comment]
@evidolob now that https://github.com/eclipse/che-theia/pull/369 has been merged can we close this issue or is there something missing?

**Comment by benoitf** [comment]
PR was merged during the move
