### ISSUE TITLE
Theia Omnisharp Plugin doesn't detect new projects 

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13739]
### Description
Theia Omnisharp Plugin [1] doesn't detect projects which were cloned after Omnisharp LS initialization.
For correct work need to update project's dependencies by `dotnet restore` command and restart the workspace.

[1] - https://github.com/redhat-developer/omnisharp-theia-plugin

**Comment by tsmaeder** [comment]
@svor does omnisharp support multiroot workspaces?

**Comment by svor** [comment]
@tsmaeder I'm not sure about full functionality but code completion, hovers, diagnostics work well

**Comment by l0rd** [comment]
That's similar to https://github.com/eclipse/che/issues/13427

Should we consider that for 7.0.0? @tsmaeder @slemeur @rhopp @nickboldt

**Comment by nickboldt** [comment]
I'd say this is OK for 7.1 or later as long as it's fixed by Sept 25.

**Comment by svor** [comment]
fixed by https://github.com/eclipse/che-plugin-registry/pull/199
