### ISSUE TITLE
Add ability to disable/remove default plug-ins in Che Theia

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13734]
### Description
For now default plug-ins in Che Theia are build-in the Che Theia image. The goal of this issue is to allow disabling or removing some of them.
It might be helpful if some of default plug-ins are collided with functionality which is needed to be tested or developed. For example, development of one of the default plug-ins.

**Comment by sunix** [comment]
I don't think this is wanted for the end user.
But maybe a more generic https://github.com/eclipse/che-theia/blob/master/che-theia-init-sources.yml kind of file that would also include binaries of plugins/ext to download and include in the final assembly package ?

**Comment by mmorhun** [comment]
I think it is still actual. For example, sometimes I want to disable ports plugin to avoid notification for known servers. But I cannot do it as for now.

**Comment by sunix** [comment]
@mmorhun could you create an issue describing the flow that is wrong from the end user perspective ? Describe what is wrong with the notifications, in which use case, etc ...
The problem with the current issue is that it may be only one solution for a problem. Maybe we could fix it in another way. Describing the problem would also help us to prioritize.
Thanks.

**Comment by mmorhun** [comment]
@sunix I am afraid we do not have other solution. If we have a plugin which does something a user doesn't want, the only way to fix it is just disable/remove the plugin.
As about specific use cases. I think it is up to specific user and I cannot describe all the use cases here.
Personally for me, ports plugin is annoying with its notifications and for most cases I would like to have it disabled. But it is only me. Another user may found it extremely useful. It is more matter of needs and taste. What we should do is to make users comfortable, give them a choice.

**Comment by sunix** [comment]
https://github.com/eclipse/che/issues/13964 may be an example of improvement without having  the user to remove plugins. We don't want the end user to disable a plug-in because it is 'annoying' but suggest him to create issues to improve the UX.

**Comment by mmorhun** [comment]
In the issue you mentioned we have problem of different kind: the link is not correct, which should be fixed. Here I talk about correct (from formal point of view) behaviour which not always desired by user.
So, to me it is better to have things configurable than trying to make them comfortable for everyone.

**Comment by vitaliy-guliy** [comment]
@sunix I would like to have an ability to disable (don't remove) default plugins. Why you don't allow me to do that?

**Comment by sunix** [comment]
@vitaliy-guliy please create an issue explaining the value for the end user through a real case scenario. And let the triage team decide if this is to be done or not and when.

**Comment by vitaliy-guliy** [comment]
Why do we need another issue? Is this one not good?

**Comment by sunix** [comment]
This one solution to a problem. but the problem could have multiple ways to be solve. Please create an issue...

**Comment by vitaliy-guliy** [comment]
I don't understand why do we need several issues on one thing. Is not that enough?
Could you explain why you insist on not giving the user to have this feature.
Having a `welcome` plugin always turned on, how can I build it from sources and run hosted Theia to test?

**Comment by sunix** [comment]
I will give you only one because we are all busy for the release....
--> You have to test our product ... not a product without this or that. If it is wrong to display the welcome plugin all the time. please open an issue about that and explain how painful it is. and triage team will prioritize.
