### ISSUE TITLE
che-theia should have autosave activated by default

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13740]
che-theia should have autosave activated by default

**Comment by sunix** [comment]
@slemeur @tsmaeder @nickboldt @l0rd @rhopp for GA ?

**Comment by l0rd** [comment]
@evidolob both @slemeur and myself think that we should have autosave activated by default on che-theia. Now there a couple of things that need to be analyzed to understand what is the milestion of this issue:

- How much work it requires to switch back che-theia to autosave?
- Is there a risk of unexpected side-effects? In other workds: upstream theia choice to disable autosave was related to a better/safer behavior or only for VSCode/Theia parity ?

**Comment by evidolob** [comment]
> How much work it requires to switch back che-theia to autosave?
It a matter of changing default settings(false-> true), but, AFAIK, Theia doesn't have API to override the default values. 
cc @akurinnoy 
> Is there a risk of unexpected side-effects? 
No
>In other words: upstream theia choice to disable autosave was related to a better/safer behavior or only for VSCode/Theia parity ?
Yes, it's pretty clear that the only reason is VSCode compatibility: 
https://github.com/theia-ide/theia/issues/4776

**Comment by benoitf** [comment]
override is in package.json
https://github.com/theia-ide/theia/commit/9eb7f4e4fb38268f207ab7f8bd7adea45c6a97ed see chagelog

**Comment by evidolob** [comment]
Then, OK.
@l0rd If you want to have this done for GA, please add proper labels.

**Comment by tsmaeder** [comment]
Is there a real reason to enable autosave by default except "it's what Che 6 did"? It seems a pretty rare default as far as IDE's go. Personally, I don't like the behaviour.

**Comment by sunix** [comment]
> Is there a real reason to enable autosave by default except "it's what Che 6 did"? It seems a pretty rare default as far as IDE's go. Personally, I don't like the behaviour.

Most of the developers are expecting auto save and like the behaviour. We can make any survey any time, it will have the same result: https://twitter.com/sunsengdavidtan/status/1131142032582356993

**Comment by tsmaeder** [comment]
But we're not writing an Web App, we're writing an IDE and IDE's don't typically have this behaviour. Also: not to cast aspersions on your twitter followerd, but I hardly think that's a representative sample.

**Comment by sunix** [comment]
> But we're not writing an Web App, we're writing an IDE and IDE's don't typically have this behaviour. Also: not to cast aspersions on your twitter followers, but I hardly think that's a representative sample.

...
Google was writting a word processor and word processors typically didn't have this behaviour.
Google was writting a email client and email client typically didn't have this behaviour

Not representative ? at least it is more representative then your own opinion.

Let's close this debate as it's been decided by our decision makers to do it. By the way this would be the default option it doesn't mean you could not disabling it.

**Comment by l0rd** [comment]
No discussion has ever happened to disable autosave on Che. It has been disabled a couple of months ago without any notice or approval. That's something that we need to fix.

If a proper discussion happens in the future I am +1 to disable autosave but for the time being let's be consistent with previous version of Che.

**Comment by slemeur** [comment]
We are doing cloud tools since quite a lot of time and we learnt from users that there is one thing they hate: loosing their datas. That is a big concern regarding how users will fell confident to use our tool.

As such, it's reasonable to turn on auto-save by default to avoid loosing source code changes. If the user doesn't like this behavior, he'll go into his preferences and explicitly change the preference and agreed with/understand the risks.

**Comment by sunix** [comment]
https://github.com/eclipse/che-theia/pull/342 is not merged yet

**Comment by akurinnoy** [comment]
https://github.com/eclipse/che-theia/pull/342 is merged
