### ISSUE TITLE
Tasks of remote plugins are not redirected to corresponding container

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#13741]
### Description
We have remotes plugins. I turned on the typescript plugin for my workspace and tried to run 'build' and 'watch' tasks for che-theia project, but they failed.
[ProcessTaskRunner](https://github.com/theia-ide/theia/blob/d19682560698585f325a48ff05afd86bca90306d/packages/task/src/node/process/process-task-runner.ts#L58) is used for running typescript task configurations, so tasks for remote plugins are not redirected to container of the plugin at the moment.

### Reproduction Steps
1. Create workspace using Che 7 Theia dev stack
2. Turned on typescript plugin
3. Start workspace and clone che-theia project
4. Run 'detected' 'build' or 'watch' task using 'Terminal' => 'Run Tasks' menu

**Comment by tsmaeder** [comment]
So which container are the tasks executed in and which container would you expect them to be executed in?

**Comment by RomanNikitenko** [comment]
Tasks provided by remote plugins are executed in theia-ide container. I expect that they should be executed in a plugin container.

**Comment by tsmaeder** [comment]
@ericwill this is one of the more serious problems we have mapping VS Code stuff to our workspace model: where do we run things like tasks, etc.
In the end, we can't know where to run tasks: for example, we might want to run a maven build on the dev machine, not the java plugin sidecar. I believe we should implement two things:
1. Extend the theia task system to include a "target component" for every task. This will be a complicated undertaking
2. Allow for che plugins to annotate the tasks contributed by vs code extensions with a hint where they should run.

**Comment by ericwill** [comment]
> @ericwill this is one of the more serious problems we have mapping VS Code stuff to our workspace model: where do we run things like tasks, etc.
> In the end, we can't know where to run tasks: for example, we might want to run a maven build on the dev machine, not the java plugin sidecar. I believe we should implement two things:
> 
>     1. Extend the theia task system to include a "target component" for every task. This will be a complicated undertaking
> 
>     2. Allow for che plugins to annotate the tasks contributed by vs code extensions with a hint where they should run.

Thanks for the context, we should probably provide this feature sometime soon-ish.
