### ISSUE TITLE
SSH plugin doesn't show generated keys

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13742]
### Reproduction Steps

1. F1 -> Ssh: Generate key pair...
2. Input `github.com`
3. Chose `VCS`
4. Press the `View` button when the notification asks to show the key
Expected: The key must be viewed in the editor.
Actual: Nothing happens

**OS and version:**    

**Diagnostics:**

**Comment by tsmaeder** [comment]
@vinokurig what are the consequences of this bug? Does something not work or is it just a display problem? Is there a workaround?

**Comment by vinokurig** [comment]
@tsmaeder It is just a display problem, the workaround is to view the keys by via user preferences API
