### ISSUE TITLE
Che Plugins panel is broken on minishift

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13747]
#### Description 
`Che Plugins` panel always shows `Your registry is invalid` message, even for default Che plugins registry.
![registry-invalid](https://user-images.githubusercontent.com/15607393/59760754-be315100-929b-11e9-857b-9731cdb708a1.png)

From pod logs:
```
root ERROR Request getWorkspacePlugins failed with error:   
root ERROR Request getWorkspacePlugins failed with error:   
root ERROR Request getWorkspacePlugins failed with error:   
```

#### Reproduction Steps
Create a workspace from a devfile, open `Che Plugins` panel

**Comment by vitaliy-guliy** [comment]
Plugins panel is broken for workspaces that has been created from a devfile due to workspace configuration is not exist. We have to adapt Plugins panel to that kind of workpsaces.

**Comment by apupier** [comment]
I also have this issue.
Local instance of Che 7 installed through chectl and operator on Windows10 with minikube
The stack that I used is the Camel one: https://github.com/eclipse/che-devfile-registry/blob/916fee5c82c8dd6c5d0e20234a3b53de9fa5ff4b/devfiles/apache-camel-springboot/devfile.yaml#L75

**Comment by vitaliy-guliy** [comment]
Fixed. It must work now.

**Comment by vitaliy-guliy** [comment]
Still is not working on `minishift` due to network issues https://github.com/eclipse/che/issues/13928

**Comment by vitaliy-guliy** [comment]
Is not actual anymore.
