### ISSUE TITLE
Display built-in plugins

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#13758]
### Description
 

Display built-in (default) plugins in the list of installed plugins. We have to indicate somehow that plugin is default ( provided by Theia editor docker image ).
Default plugins are always present on the file system and cannot be removed.

**Comment by sunix** [comment]
@benoitf yes, just displaying them would be fine. It would be bad to give to much power to the enduser ... and break his workspace easily.

**Comment by vitaliy-guliy** [comment]
Is already implemented
