### ISSUE TITLE
Icons aren't displayed on a contributed view container

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#13750]
If Theia Plugin, running in a sidecar, contributes a view container with the icons they are not displayed anymore.

For example, [Kubernetes Tooling Che Plugin](https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools) contributes view container that was looking like that
![57142979-7f683a00-6dc6-11e9-95d9-1fa0e436ff90](https://user-images.githubusercontent.com/1636395/59369021-289c3b80-8d48-11e9-98fc-63f71ce5e6eb.png)

But now there are no icons. Neither for view container nor for the tree items

![image](https://user-images.githubusercontent.com/1636395/59369150-6e590400-8d48-11e9-99ff-1f6bde3c818e.png)

I noticed that icons are displayed correctly if I install VS Code extension from the marketplace with the `Deploy Plugin by Id` command directly into the Theia container.

**Comment by evidolob** [comment]
It looks like we don't configure express application and don't follow `BackendApplicationContribution` Theia contribution. Theia has [REST service for plugin resources ](https://github.com/theia-ide/theia/blob/1dc36a02855681f0c0cc11916551dddc26ac703f/packages/plugin-ext/src/hosted/node/plugin-reader.ts#L45) but in `theia-remout` we not initialize it.

**Comment by vparfonov** [comment]
@slemeur Can you take a lock on this issue and prioritize it

**Comment by mmorhun** [comment]
Done
