### ISSUE TITLE
Add support for APR in Tomcat 8

### ISSUE THREAD

**Issue by mpouttuclarke** [eclipse-che/che#1376]
Right now Che isn't using the performance benefits offered by Apache Portable Runtime (APR). These reduce the max latency during TLS negotiation dramatically and improve overall latency by at least two orders of magnitude.  Most of the performance gain is due to native AES intrinsics and use of native Unix select():
https://tomcat.apache.org/tomcat-8.0-doc/apr.html
http://linux.die.net/man/2/select

**Comment by mpouttuclarke** [comment]
This involves a change to the server.xml to remove the hard coded nio processing in the server.xml.

Tomcat will always automatically choose APR processing if it is installed in the docker file, or default to nio if APR is not present.  There is no need to hard code the nio connection handler. To install APR it is sudo apt-get -y install libapr1

**Comment by mpouttuclarke** [comment]
Also, I have not tested the Nio2 protocol: Http11Nio2Protocol

This may be even better than APR due to having more non-blocking features:
https://tomcat.apache.org/tomcat-8.0-doc/config/http.html#Connector_Comparison

**Comment by mpouttuclarke** [comment]
For the most hardcore webserver testing, I use the Apache Benchmark (ab) on 127.0.0.1 
https://httpd.apache.org/docs/2.4/programs/ab.html 

This tests raw loopback performance without giving the server a break due to interconnect latency.

**Comment by mpouttuclarke** [comment]
ab test with current Tomcat config:
root@ip-172-31-14-45:/opt/tomcat8/logs# ab -c 250 -n 10000 https://127.0.0.1:8443/
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        Apache-Coyote/1.1
Server Hostname:        127.0.0.1
Server Port:            8443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-DES-CBC3-SHA,2048,168

Document Path:          /
Document Length:        11230 bytes

Concurrency Level:      250
Time taken for tests:   166.305 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      113710000 bytes
HTML transferred:       112300000 bytes
Requests per second:    60.13 [#/sec](mean)
Time per request:       4157.613 [ms](mean)
Time per request:       16.630 [ms](mean, across all concurrent requests)
Transfer rate:          667.72 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       91 3864 1859.7   3465   35903
Processing:     2  250 283.5    154    2262
Waiting:        0  154 205.9     77    1851
Total:        195 4114 1901.8   3738   36145

Percentage of the requests served within a certain time (ms)
  50%   3738
  66%   4277
  75%   4728
  80%   5068
  90%   6037
  95%   7094
  98%   9601
  99%  10442
 100%  36145 (longest request)

**Comment by mpouttuclarke** [comment]
With Http11Nio2Protocol:
root@ip-172-31-14-45:/opt/tomcat8/logs# ab -c 250 -n 10000 https://127.0.0.1:8443/
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        Apache-Coyote/1.1
Server Hostname:        127.0.0.1
Server Port:            8443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-DES-CBC3-SHA,2048,168

Document Path:          /
Document Length:        11230 bytes

Concurrency Level:      250
Time taken for tests:   164.861 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      113710000 bytes
HTML transferred:       112300000 bytes
Requests per second:    60.66 [#/sec](mean)
Time per request:       4121.519 [ms](mean)
Time per request:       16.486 [ms](mean, across all concurrent requests)
Transfer rate:          673.57 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:      281 3924 2939.2   3138   34742
Processing:     2  108 152.1     46    1205
Waiting:        1   77 123.1     24    1159
Total:        362 4032 2943.8   3274   34812

Percentage of the requests served within a certain time (ms)
  50%   3274
  66%   3720
  75%   4047
  80%   4444
  90%   5988
  95%   9574
  98%  11258
  99%  17943
 100%  34812 (longest request)

**Comment by TylerJewell** [comment]
Looks like the comparison doesn't offer any indication that one approach is statistically better than another.

**Comment by mpouttuclarke** [comment]
Just adding native now.  I was comparing the two java options

**Comment by mpouttuclarke** [comment]
With libapr1:
root@ip-172-31-14-45:/opt/tomcat8/logs# ab -c 250 -n 10000 https://127.0.0.1:8443/
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        Apache-Coyote/1.1
Server Hostname:        127.0.0.1
Server Port:            8443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256

Document Path:          /
Document Length:        11230 bytes

Concurrency Level:      250
Time taken for tests:   16.834 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      113710000 bytes
HTML transferred:       112300000 bytes
Requests per second:    594.03 [#/sec](mean)
Time per request:       420.852 [ms](mean)
Time per request:       1.683 [ms](mean, across all concurrent requests)
Transfer rate:          6596.43 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        9  249 135.8    231    1520
Processing:     1  167 122.6    144     978
Waiting:        0   51  78.5     21     627
Total:         37  416 179.7    397    1667

Percentage of the requests served within a certain time (ms)
  50%    397
  66%    461
  75%    503
  80%    525
  90%    625
  95%    734
  98%    897
  99%   1008
 100%   1667 (longest request)

**Comment by mpouttuclarke** [comment]
Two orders of magnitude, baby

**Comment by mpouttuclarke** [comment]
```
<!-- Define a SSL/TLS HTTP/1.1 Connector on port 8443
     This connector uses the NIO implementation that requires the JSSE
     style configuration. When using the APR/native implementation, the
     OpenSSL style configuration is required as described in the APR/native
     documentation -->
<Connector port="8443" maxHttpHeaderSize="8192"
             maxThreads="150"
             enableLookups="false" disableUploadTimeout="true"
             acceptCount="100" scheme="https" secure="true"
             SSLEnabled="true" SSLProtocol="TLSv1.2"
           SSLCertificateFile="/root/keys/certificate.pem"
           SSLCertificateKeyFile="/root/keys/key.pem" 
            SSLPassword="secret"/>
```

**Comment by mpouttuclarke** [comment]
Recipe changes:
sudo add-apt-repository ppa:pharmgkb/trusty
sudo apt-get update
sudo apt-get upgrade libtcnative-1
sudo apt-get install libapr1

**Comment by mpouttuclarke** [comment]
Cert generation:
openssl genrsa -out key.pem 2048
openssl req -new -key key.pem -out csr.pem
openssl req -x509 -days 365 -key key.pem -in csr.pem -out certificate.pem

**Comment by mpouttuclarke** [comment]
And people say Jetty is the fastest Java web server, what a laugh.  If you can't use httpd, use the APR friends

**Comment by TylerJewell** [comment]
@mpouttuclarke Can you write more fully on the risk factors of the change.  Is this technology released?  Is it supported by a community?  What scenarios where does it start to fail?

**Comment by mpouttuclarke** [comment]
Actually it's more of a risk to run Tomcat _without_ APR.  It's kind of like running Hadoop without the native support.  That's why if you start Tomcat without APR you get a warning message in the logs: 

> The APR based Apache Tomcat Native library was not found

However, in the case of Che where you are not running APR by default you will have to deploy a slightly different server.xml file in the case that APR is installed because the SSL configuration in APR is based on OpenSSL rather than JSSE.  APR is the heart and soul of Apache httpd and the chance of the stable version breaking is about the probability of the IRS forgetting to collect taxes.

> Tomcat can use the Apache Portable Runtime to provide superior scalability, performance, and better integration with native server technologies. The Apache Portable Runtime is a highly portable library that is at the heart of Apache HTTP Server 2.x. APR has many uses, including access to advanced IO functionality (such as sendfile, epoll and OpenSSL), OS level functionality (random number generation, system status, etc), and native process handling (shared memory, NT pipes and Unix sockets).

**Comment by TylerJewell** [comment]
Is the technology fully released.  Is it supported by a broad community.   And what are the license implications.  We have to check all of these things for Che before we get into a test mode.

But the good news is that you can provide your own custom Dockerfiles which use this configuration inside.  So you can use it without it being part of the mainstream until it's tested.

**Comment by mpouttuclarke** [comment]
Totally understand the testing impacts.  Apache HTTP server is the first ever Apache project.  APR is the shared lib powering Apache HTTP server.  If you ship Tomcat, same difference it's all APL 2.0.  APR has been production stable since Tomcat v5.

You guys should not be controlling the Tomcat config anyway in my perspective.

**Comment by mpouttuclarke** [comment]
Also, here is the sub-project page.  It's been production stable since 2008:
http://tomcat.apache.org/native-doc/

**Comment by skabashnyuk** [comment]
Hello @mpouttuclarke 

> You guys should not be controlling the Tomcat config anyway in my perspective.

Yes. You are right. That is not our goal.
The idea was very simple. We want to provide basic server.xml that fit to most of the users. And in the same time provide ability (at least not to block) to advanced users to configure tomcat as they want.

We chose Http11NioProtocol as default because 85% of heavy  communications  we are doing over Websockets. And it seems is to be a good solution for our needs. 

About Http11Nio2Protocol. http://permalink.gmane.org/gmane.comp.jakarta.tomcat.user/242254 Looks like has no profits over Http11NioProtocol.

**Comment by mpouttuclarke** [comment]
So I am going to be dropping potentially thousands of users into this framework with the expectation that performance is going to be stellar.  When you say the server.xml you provide "fits most of the users", honestly 99.9% of the users _don't care_ which configuration of Tomcat Che uses under the covers.  I am proposing an alternate server.xml configuration which I have _reproducibly proven_ reduces latency dramatically in a TLS pipeline, regardless of the transport protocol.  I am committed to providing the absolute highest quality of experience to my users, which is why I suggested the change.  If Che did not push it's own server.xml I could easily push my own config and allow my users the benefits.  

Please read my previous comments, I _am not_ proposing the Http11Nio2Protocol, and my ab testing confirms that it has no benefits.  However, APR incontestably provides a superior user experience as noted above.  I've been deploying Tomcat in large scale production since it first came out 17 years ago, and for the last 8 years I have used APR for Tomcat successfully to dramatically reduce latency.  

If it is not your goal to push the server.xml then either do not do so at all, or provide some means to override that "feature" please.  This will allow you to mitigate the perceived risk and also allow me to take Che's latency and performance to the next level for my user base.

**Comment by TylerJewell** [comment]
What are the best practices for products that want to provide a default server.xml, while allowing others to override it?  

Out of curiosity, I think the default assembly ships with an unpacked Tomcat, so it should be possible to create a custom assembly that overrides the server.xml today. It would be configuration through the assembly descriptors instead of something that is set in a configuration file, though.

@skabashnyuk - are there any reasons that APR as a default configuration should not be considered if the performance is better.

@mpouttuclarke - keep in mind that of the 70 or so contributors to the project, more than 60 of them has English as a second language - so it can difficult for the groups to communicate clearly and have to ask many questions to understand items.

**Comment by gazarenkov** [comment]
Matt, thanks for info, APR results are cool, definitely need to try it for
master conf in beta and on-prem.

As I understand it requires some native libraries to make it work (3
components listed in tomcat's apr page), correct?
So, probably making APR as "default" config for the local Che installation
is overkill but can be considered for SaaS/on-prem conf.

In any case, IMO, it can be offered as an option for better performance,
provided as assembly descriptor or properties conf (ideally, if we manage
to create it for this case) or documentation.

Gennady Azarenkov - CTO @ codenvy.com

**Comment by skabashnyuk** [comment]
@mpouttuclarke 
would it be enough if we enable
`
<Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
`
or we need some other changes in server.xml

**Comment by mpouttuclarke** [comment]
I have a solution that should allow both full flexibility to the Tomcat host configuration for your Tomcat host _and_ ensure you guys have a stable configuration for clients not using custom config like APR:
1. The host defines an existing <Service name="Che" **then** do nothing as the host has a custom config
2. Tomcat allows multiple <Connector stanzas and one of them might conflict on the 4401 port you are expecting.  This can happen in the below cases, handled respectively:
    - The case where the port is not bound **then** create a <Service name="Che" with your default config
    - The case where the host already has the port bound for a different purpose, and does not have a <Service name="Che" in the server.xml **then** install fails with an fatal error

The above can be handled with simple sed stanzas

**Comment by mpouttuclarke** [comment]
In addition to the solution above, you may want to have a brief doc or readme describing the minimum requirements for customized Tomcat config.  i.e. port 4401 TLS etc.

**Comment by mpouttuclarke** [comment]
Oh yes, and remove this file from your distribution as it is no longer needed with the solution above:
https://github.com/eclipse/che/blob/master/assembly/assembly-wsagent-server/src/assembly/server.xml

**Comment by TylerJewell** [comment]
@mpouttuclarke - Matt, will you issue a PR for this request.  It may help see the code changes required and then we can get QA team to do a battery of integration tests against the branch, too.

**Comment by mpouttuclarke** [comment]
Just remember that if the default assembly server.xml for Che is modified,
then _all_ docker files must be updated to install the tomcat native.

That’s why I recommended the solution to use sed to modify the server.xml
as preferred.  Then you can transition your user base as quickly or slowly
as is required to fit your deployment schedules and priorities.

**Comment by TylerJewell** [comment]
@mpouttuclarke FYI, we are locking down 4.3 release now - it's going into bug fix only mode. We anticipate that 4.4 release will be a short release (<4 weeks) and any PR for this could be incorporated at that time.

**Comment by mpouttuclarke** [comment]
That’s fine, I won’t have any time to work on this for a week or more.
Thanks for the update!

On June 4, 2016 at 8:08:22 AM, Tyler Jewell (notifications@github.com)
wrote:

@mpouttuclarke https://github.com/mpouttuclarke FYI, we are locking down
4.3 release now - it's going into bug fix only mode. We anticipate that 4.4
release will be a short release (<4 weeks) and any PR for this could be
incorporated at that time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/eclipse/che/issues/1376#issuecomment-223760584, or mute
the thread
https://github.com/notifications/unsubscribe/AAVjZS97qTJHaJQY2RjF4i3MoD04pD8nks5qIZTlgaJpZM4IozfR
.
