### ISSUE TITLE
che-theia-terminal-extension be made available as a release

### ISSUE THREAD

**Issue by htirunag** [eclipse-che/che#13769]
We are working on a project(briefed as below) and we want to enable terminal-access for containers in our workspace. We download this extension and add it to our package.json, while building our docker image. This works well for us. However, we want to download a tagged/release of che-theia-terminal-extension. So, would like to know, if a release will be made in sometime.

Usecase:
Workspace comprises of a theia ide wherein a web project is created and another container of the workspace builds the webproject and deploys to tomcat. We limited our project, wherein a user will run commands in the terminal to build and deploy the webproject.

Thanks.

**Comment by monaka** [comment]
I guess this issue is obsolete as `extensions/eclipse-che-theia-terminal` is available in the master branch. 
Or is `che-theia-terminal-extension` an another packages?
