### ISSUE TITLE
Workspace Commands Import

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1377]
Is there any way to import or execute commands(clean install, etc) from each project? Maybe have a json file that can be imported to list of available execute commands. Placed in the correct folder maybe it could be detected and loaded automatically after asking user of course.

**Comment by ghost** [comment]
@james10174 right now commands come with samples https://eclipse-che.readme.io/v4.3/docs/templates#section-commands

However, we're working on making it possible to associate a set of commands with a workspace. Work in progress.
