### ISSUE TITLE
How to custom IDE with che, like below picture?

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse-che/che#13778]
![1562322431(1)](https://user-images.githubusercontent.com/40679769/60716722-aff95b00-9f52-11e9-8c2d-faa468c3e0ef.jpg)

**Comment by monaka** [comment]
I can't show the step by step document now. But I've integrated Theia-sprotty based editor to Che-Theia. Just I can say it's not hard after you got the background mechanism around Theia. So yes, this issue should be Theia-IDE. Not here.

**Comment by xinsuinizhuan** [comment]
thank you.this is a good message to me, it is a direction to begin my work. your this project is open source or you own project, i just to study it, then to begin my work.
