### ISSUE TITLE
eclipse/che-theia/next is broken: no projects cloned, empty my workspace view, etc ...

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13779]
### Description
With the very latest version of che-theia (eclipse/che-theia/next), everything seems to be broken:
- Projects are not cloned
- My workspace view is empty

### Reproduction Steps
Start a workspace with some projects and the eclipse/che-theia/next editor. For instance:

```
$ chectl workspace:start -f <(chectl devfile:generate --editor=theia-next --name=test-che-theia-next --git-repo=https://github.com/sunix/devfiles)
  ✔ Retrieving Che Server URL...http://che-che.192.168.39.13.nip.io
  ✔ Verify if Che server is running
  ✔ Create workspace from Devfile /dev/fd/63

Workspace IDE URL:
http://che-che.192.168.39.13.nip.io/dashboard/#/ide/che/test-che-theia-next
```
Open the workpace, no project is cloned and my workspace view is empty

![Selection_326](https://user-images.githubusercontent.com/650571/60719674-b83ca080-9f28-11e9-8b01-19e825ac7c2c.png)

**Comment by sunix** [comment]
@nickboldt, @l0rd, @slemeur, @tsmaeder and @rhopp
This is a candidate for che7ga

**Comment by tomevision** [comment]
Even Yeoman plugin generator is not working

**Comment by slemeur** [comment]
@evidolob please give a look at this problem.

**Comment by benoitf** [comment]
theia next is not included in Che 7 GA so why fixVersion is 7.0.0 ?

**Comment by tsmaeder** [comment]
@sunix is this a duplicate of https://github.com/eclipse/che/issues/13678?

**Comment by tsmaeder** [comment]
I believe the issue with the activation events and the issue with the missing projects might be two different things.

**Comment by tsmaeder** [comment]
I've moved this to the 7.1 milestone because this is an issue with che-theia master and not 7.0 branch

**Comment by sunix** [comment]
Fixed

**Comment by sunix** [comment]
BTW this was affecting che.openshift.io
