### ISSUE TITLE
Is any example,to custom che IDE UI ?

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse-che/che#13775]
I want custom my own IDE，the i shoud add or change menu che menu， and  add Graphical interface controls to editor that docked in workspace right. Is che support ?

**Comment by tsmaeder** [comment]
I think there are two parts you need to attack:
1. Build a Theia extension that implements your graphical UI. Head over to github.com/theia-ide/theia for how to do that.
2. Build your own Theia che editor based on github.com/eclipse/che-theia and set that as your editor plugin in a che workspace. A good start would be to read through the code and to ask questions on the Che mattermost chat.

**Comment by xinsuinizhuan** [comment]
thank you! Then to make a graphical UI must by Theia, and make own Theia che editor must by che-theia ?where is the che mattermost chat? I am comparing the che and theia，which is good to achieve my custom IDE function, now i realize that it is possible by theia to achieve my customed IDE，but i don’t know whethet the che could?
