### ISSUE TITLE
Gracefully ignore the error when trying to delete an unexisting OAuthClient

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#13783]
### Description

When trying to delete the previous `OAuthClient`, and it already doesn't exist, we should gracefully ignore the error instead of failing. 

### Detail

When the Che operator starts reconciliating a `CheCluster` custom resource, there might be a number of cases when it would first try to do some cleaning at start, and try cleaning a previously created `OAuthClient` resource. However it might happen, for any reason, that this `OAuthClient` resource is not there anymore (previous CR start that didn't go until the end, etc ...). In this case, the Che operator fails to reconciliate the Custom resource, and restart. This starts an endless loop that makes it very hard to work with it without manually removing the `CheCluster` resource (which might itself prove quite hard due to some other side-effects of this corner-case situation).

### Reproduction Steps

- Install the Che operator,
- Create a `CheCluster` CR with `openshiftOAuth` field set to true
- Wait for everything to be started
- Manually delete the new `OAuthClient` that was created by the Che Operator
- Try to delete the `CheCluster` CR you initially created.
- This should have created the error.

**OS and version:**    

OpenShift 3.11 or OpenShift 4.1 with the Eclipse `7.0.0-rc-2.0` Che operator.

**Comment by tsmaeder** [comment]
@davidfestal I don't see that user impact that would warrant inclusion of this in the 7.0 milestone.

**Comment by davidfestal** [comment]
Since the overall robustness of the Che operator is not high (which cannot be fixed until GA obviously) , mainly in regard to how Openshift OAuth is managed, the situation described in this issue can happen quite easily, and though the unexpected situation (non-existing OAuthClient) should be simply ignored, it currently becomes a blocking error that fully prevents the operator to work until the user, with the help of support, would clean his whole environment (and loose his current Che server definition).

It's a 2-line fix that would save us (and users) much time and unnecessary troubleshooting burden.

@l0rd wdyt about it ?

**Comment by tsmaeder** [comment]
If it's a data-loss bug, it's a 7.0.0 issue, IMO.

**Comment by l0rd** [comment]
Makes sense to have it in the 7.0.0 milestone

**Comment by slemeur** [comment]
Hi @davidfestal - can we mark this issue as solved, as the PR been merged?

**Comment by davidfestal** [comment]
Yes, I think so.
