### ISSUE TITLE
Can't install eclipse on Mac OS X "El Capitan"

### ISSUE THREAD

**Issue by supuflounder** [eclipse-che/che#1378]
I decided to install Eclipse on my Macbook Air.  So I do the download, get the Eclipse installer, and get the warning that JVM 1.6.0_065 is unsuitable.  Well, OK, I didn't install Java first.  So I do this.  I download the very-latest-as-of-today JDK for Java SE.  So now, I should have everything I need. Nope, same error.  I follow the instructions of how to uninstall Java, and do what they tell me.  I then reinstall the JDK for Java.  Nope, same error.  I search for jvm, jre, etc. and discover nothing that seems to refer to these installations.  While I am a gray-bearded programmer (53+ years in the profession), I haven't used Eclipse in many years, and I didn't do the installation myself, and it was on a Windows machine.  And the wench is dead.  Or something like that.  What do I have to do to install a Java development environment on my Macbook Air?  I'm using the "El Capitan" release of OS X.

**Comment by TylerJewell** [comment]
Hi:

I think you may have the wrong forum.  If you are talking about the Eclipse installer, that is the installer for the classic IDE.   Eclipse Che is a next generation product and is installed by docker, vagrant, or optionally as a server on tomcat.

But when someone says Eclipse installer with unsuitable JVM that sounds like the traditional IDE.

Can you confirm which one you grabbed?

**Comment by supuflounder** [comment]
> Hi:
> 
> I think you may have the wrong forum.  If you are talking about the
> Eclipse installer, that is the installer for the classic IDE.   Eclipse
> Che is a next generation product and is installed by docker, vagrant, or
> optionally as a server on tomcat.
> 
> But when someone says Eclipse installer with unsuitable JVM that sounds
> like the traditional IDE.
> 
> Can you confirm which one you grabbed?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eclipse/che/issues/1378#issuecomment-222287068

Yes, it is the traditional IDE.  Whar forum should I have been in?
       joe
