### ISSUE TITLE
Provides a nightly image for che-theia image on branch 7.0.0

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13782]
### Description
There is a `7.0.0` branch in che-theia for stabilizing che/theia used for 7.0.0 GA

but AFAIK there is no nightly image built from that branch so any new commit to `7.0.0` is not used on che master branch (7.0.0 branch)

So if the tag is only occurring at the end it might not work at all and people are not using the latest state.

Before che:master was using che-theia:next but it can't be the case anymore as process it to have something as stable as possible.

**Comment by tsmaeder** [comment]
Tagging this 7.0 because it's necessary for testing our work for 7.0

**Comment by evidolob** [comment]
che-theia 7.0.0 branch builded on each commit.
After this pull https://github.com/eclipse/che-theia/pull/347
che-theia docker image has `7.0.0-rc-4.0-SNAPSHOT` version

**Comment by benoitf** [comment]
should it be `7.0.0-next` to match the other kind of master version which is `next` ?

**Comment by evidolob** [comment]
It can be, but I want to alight che-theai image version with Che version

**Comment by benoitf** [comment]
but che version images are 'nightly' (there is no SNAPSHOT in all other che images)

**Comment by evidolob** [comment]
OK, so version should be `7.0.0-nightly` ?

**Comment by benoitf** [comment]
if you name it `nightly` but it's built at each commit there is something wrong, this is why it ended it up with `next`

`latest` and `next` are

**Comment by evidolob** [comment]
@benoitf It seems your comment not full, can you  write what version you think would be better?

**Comment by benoitf** [comment]
@evidolob 

`7.0.0-nightly` if it is built every night
`7.0.0-next` if it is built at each commit

Now, it means that plugin-registry is updated a lot so if you're able to give a word to 7.0.0 it may be better.

For example some products have channels like `edge`, `stable`, `testing`, `unstable`, etc

so you could say:
`next` is from master branch
`testing`or another keyword is from the master branch or from the current code freeze branch (if there is one at a time)
`latest` is the latest stable version

etc


so we have `channels` instead of `versions`

**Comment by evidolob** [comment]
OK, it would be `7.0.0-next` I'm going to create PR

**Comment by vparfonov** [comment]
> @evidolob
> 
> `7.0.0-nightly` if it is built every night
> `7.0.0-next` if it is built at each commit
> 
> Now, it means that plugin-registry is updated a lot so if you're able to give a word to 7.0.0 it may be better.
> 
> For example some products have channels like `edge`, `stable`, `testing`, `unstable`, etc
> 
> so you could say:
> `next` is from master branch
> `testing`or another keyword is from the master branch or from the current code freeze branch (if there is one at a time)
> `latest` is the latest stable version
> 
> etc
> 
> so we have `channels` instead of `versions`

So in this case 'latest' will be the same for each Che backend for 7.0.0-rc-4.0 and for 7.0.0 and probably won't work in some cases.

**Comment by benoitf** [comment]
@vparfonov for tagged versions we replace aliases by the real versions so latest inside 7.0.0 will still have 7.0.0 everywhere ( a tag is a fixed name)
but SNAPSHOT, nightlies, etc, all are for development purpose.

> the backend for 7.0.0-rc-4.0 and for 7.0.0 
if you use che latest at some point you'll get 7.0.0-RC4 and then 7.0.0 but you'll never have a mix.

if you use 'latest' then you've the latest stable version of che, latest stable version of theia, etc
and for testing you would have the testing version of che, etc
if you use nightly then you should have nightlies everywhere, etc.

**Comment by evidolob** [comment]
I think we can close this issue, `che-theia:7.0.0-next` is updated on each commit in che-theia 7.0.0 branch, so we don't need to have `nightly` image.
