### ISSUE TITLE
GitHub plugin doesn't work

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13789]
### Description
 
GitHub plugin doesn't work. It caused by latest changes from Theia repository (https://github.com/theia-ide/theia/commit/906c4febfe2f9bab4342ae323dd68c68af9b07ae).
### Reproduction Steps

1. Enable github plugin in the plugins list of the workspace.
2. Start the workspace

Wrong: Git and Github don't work
**OS and version:**    
latest
**Diagnostics:**

**Comment by benoitf** [comment]
note: it's for che-theia:next, not che-theia:7.0.0 , correct ?

**Comment by vinokurig** [comment]
> it's for che-theia:next, not che-theia:7.0.0 , correct ?

Yes, it is reproduced in the latest version

**Comment by l0rd** [comment]
@vinokurig so it doesn't impact Che 7.0.0. FYI we will considered less a priority then others issues (with milestone 7.0.0) like #13784 that should be addressed as soon as possible.

**Comment by vinokurig** [comment]
Is fixed by https://github.com/theia-ide/theia/pull/5661
