### ISSUE TITLE
Project cloned to undefined if initial dialog to select a repository location was discarded

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#13787]
### Description
Project failed to clone if user discarded the initial dialog to select a repository location.

### Reproduction Steps

1. Start a workspace with some project
2. Click `Close` on the initial dialog to select a repository location
3. `project cloned to undefined` message appears
4.  Project isn't cloned

**OS and version:**    
Che 7.0.0-rc-3.0-SNAPSHOT

**Diagnostics:** 

![screencast-routeicwtc7qp-che 192 168 99 100 nip io-2019 07 08-04-08-12](https://user-images.githubusercontent.com/1640675/60776728-eb547f00-a136-11e9-95b3-8118fee08810.gif)

### Related issue
https://github.com/eclipse/che/issues/13784

**Comment by l0rd** [comment]
@tolusha I have added the information that if selecting `Cancel` the project cloning fails to the description of #13784. Closing this one.
