### ISSUE TITLE
Confusing dialogs are shown when a project is cloned

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13784]
### Description
With new git vscode extension, che-theia is not behaving as expected during initial clone of project. The project should be cloned without any prompt for the user but currently a couple of prompt dialogs are shown to the user.

Maybe we shouldn't use that theia command and invoke git directly (https://github.com/eclipse/che-theia/blob/master/plugins/factory-plugin/src/theia-commands.ts#L74). Or maybe there are some default options to set.

### Reproduction Steps
Started the workspace with project to clone, like:

```
chectl workspace:start -f <(chectl devfile:generate -name=che7-readme-update-stable --git-repo=https://github.com/eclipse/che --dockerimage=sunix/git-devtools)
  ✔ Retrieving Che Server URL...http://che-che.192.168.39.13.nip.io
  ✔ Verify if Che server is running
  ✔ Create workspace from Devfile /dev/fd/63

Workspace IDE URL:
http://che-che.192.168.39.13.nip.io/dashboard/#/ide/che/che7-readme-update-stable
```
Theia starts successfully but ask to select a (git) repository:
![Eclipse Che | che7-readme-update - Google Chrome_327](https://user-images.githubusercontent.com/650571/60734559-a5d65d00-9f50-11e9-8d3a-d618bf8fc552.png) 

It shouldn't ask anything as it was before. Moreover selecting `Cancel` abort project cloning and that should not happen neither.

Anyway selecting folder `/projects/` works and the project is cloned successfully (and a nice spinner is shown indicating that the cloning is happening).

After the project is cloned a couple of dialogs are shown to the user: 

![Eclipse Che | che7-readme-update-2 - Google Chrome_329](https://user-images.githubusercontent.com/650571/60734594-c30b2b80-9f50-11e9-8db3-c3983a01d902.png)

And if you do not make the right choice, we end up with strange folders in the explorer

![Selection_330](https://user-images.githubusercontent.com/650571/60734868-a28fa100-9f51-11e9-9729-50a6244adedc.png)

**OS and version:**    
rhel, chectl and minikube

**Comment by ibuziuk** [comment]
have the same issue on prod-preview after update to '7.0.0-rc-3.0-SNAPSHOT'  - https://github.com/redhat-developer/rh-che/pull/1474

**Comment by vparfonov** [comment]
@ibuziuk Maybe 7.0.0-rc-**4.0**-SNAPSHOT ?

**Comment by ibuziuk** [comment]
@vparfonov nope, was able to repro against stable `7.0.0-rc-3.0` upstream release

**Comment by vparfonov** [comment]
hm, ok thanks

**Comment by rhopp** [comment]
@vinokurig @vparfonov When can we expect solution to this issue? I'm asking because it's currently breaking happy path tests and I'm trying to decide whether it's worth it to implement workaround in Happy Path tests.

**Comment by vparfonov** [comment]
@rhopp, we work on it just now, will ping you soon

**Comment by sunix** [comment]
@vinokurig maybe quick way to fix it is to invoke git directly instead of using the vscode command 'git.clone'

https://github.com/eclipse/che-theia/blob/master/plugins/factory-plugin/src/git.ts#L57

to replace

https://github.com/eclipse/che-theia/blob/master/plugins/factory-plugin/src/theia-commands.ts#L74

**Comment by vinokurig** [comment]
@sunix Right now I am preparing a new binary of vscode git that solves this problem.

**Comment by johnmcollier** [comment]
I should also note that this shows up every time the Che workspace is accessed (rather that just the first time). Also, when you reload the workspace in the browser, if you select the same folder as before, it reclones the projects, creating duplicates in the workspace.

**Comment by vinokurig** [comment]
`eclipse/che-theia:7.0.0-rc-3.0` image is rebuilt with the patched vscode git extension

**Comment by sunix** [comment]
@vinokurig are you saying that you are forking vscode git ?

**Comment by vinokurig** [comment]
Yes, it's a kind of a fork https://github.com/che-incubator/vscode-git

**Comment by johnmcollier** [comment]
Will the fix for this be pushed/merged to `eclipse/che-server:nightly`?

**Comment by johnmcollier** [comment]
@sunix @vinokurig I'm still seeing duplicate clones when refreshing/reloading a Che workspace with `eclipse/che-theia:7.0.0-rc-3.0`, so I've opened https://github.com/eclipse/che/issues/13796

**Comment by sunix** [comment]
> @sunix @vinokurig I'm still seeing duplicate clones when refreshing/reloading a Che workspace with `eclipse/che-theia:7.0.0-rc-3.0`, so I've opened #13796

Thanks
