### ISSUE TITLE
Can't deploy Keycloak by Helm.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13797]
### Description

This is a tether of some pull requests about deployments error on Keycloak by Helm (and possible Openshift).
I'll close this after all issues are fixed.

**Comment by benoitf** [comment]
hello I think it's a duplicate of https://github.com/eclipse/che/issues/13625

**Comment by l0rd** [comment]
@monaka do you mind closing this issue since it's a duplicate of #13625?

**Comment by monaka** [comment]
@benoitf @l0rd I agree. I close this and relink related PRs to #13625.

**Comment by l0rd** [comment]
Thank you @monaka
