### ISSUE TITLE
Tree nodes don't expand in the GitHub plugin

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13790]
### Description
 

Tree nodes don't expand in the GitHub plugin

### Reproduction Steps

1. Enable Github PR plugin in the plugins list of the workspace
2. Open a workspace with Github project with pull requests
3. Try to expand a PR node

**Wrong:** Node is not expanded:
![screenshot-localhost-3030-2019 07 08-12-15-42](https://user-images.githubusercontent.com/7668752/60798605-24faa980-a17a-11e9-9eb8-665549a93127.png)
Error is occurred:
```
root ERROR [hosted-plugin: 27890] (node:27890) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.replyOK (/home/ivinokur/projects/theia/packages/plugin-ext/lib/api/rpc-protocol.js:280:103)
    at /home/ivinokur/projects/theia/packages/plugin-ext/lib/api/rpc-protocol.js:158:51
root ERROR [hosted-plugin: 27890] (node:27890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```
**OS and version:**    
7.0.0-rc-3.0
**Diagnostics:**

**Comment by l0rd** [comment]
I don't consider that as a blocker for GA. I have put 7.1.0 as milestone. cc @slemeur

**Comment by vinokurig** [comment]
Is actual for 7.0.0-next tag

**Comment by l0rd** [comment]
@vinokurig can we close that now since it was fixed in theia master branch right?

**Comment by vinokurig** [comment]
Yes
