### ISSUE TITLE
Use the user's roles for Kubernetes roles in Che workspaces

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#13795]
### Description
I'm from the Eclipse Codewind project, and we have a plugin for its integration with Che (https://github.com/eclipse/codewind-che-plugin). On Che, Codewind allows users to create Kubernetes deployments and services for their application. However, the default roles given to the Che workspace aren't enough for that, and we currently tell users to set `cheWorkspaceClusterRole` (https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L28) when installing Che, so that Codewind can function properly.

It'd be nice if we had a way for workspaces (maybe via the devfile?), to specify and link to a Kubernetes role that can be used for the workspace. Then, when the workspace was created, a role binding would be created linking to that cluster role. That way, workspaces that require increased cluster roles (such as Codewind), could then be created from a default installation of Che, without additional work needed by the user.

I suppose if this was done, we'd also want something in the UI to tell the user that the workspace they're creating requires hightened roles.

**Comment by l0rd** [comment]
@johnmcollier I think it may be related to this issue https://github.com/eclipse/che/issues/13488

In other words the best way to solve this problem is to use the current user privileges instead of an hardcoded role that it's set as a che-server property. If we let user define their role in a devfile it would result in a privilege escalation.

**Comment by johnmcollier** [comment]
@l0rd That's a good point. I'm good with using the current user privileges, instead of some arbitrary role that users (or plugins) define.
