### ISSUE TITLE
creating containers from local dockerfiles

### ISSUE THREAD

**Issue by nischal62019** [eclipse-che/che#1379]
Hi,

How can i create docker containers from docker files sitting in my local machine.

I was able to create my custom stack and updated the "stacks/predefined-stacks.json" with an entry for my custom stack and gave docker file source as a dockerfile from docker hub:

"source": {
      "type": "image",
      "origin": "nisc/customerDockerFIle"
},

i want to create my container from docker file sitting in my local host, and i was not able to find much about what values these attributes take.

What should be the values for "type" and "origin" to pick docker file from my local system.

also if i want to create templates from my local machine rather than git.

Are these parameters documented somewhere?

Thanks,
Nischal Y

**Comment by TylerJewell** [comment]
@nischal62019 - very unusual timing for this request.  See this pull request which has been in development by @benoitf for a few weeks and about to be merged.  It will be part of Che in 4.3, which is now in ramp down mode.  This pull request introduces different types of references including inline Dockerfile for stacks.

https://github.com/eclipse/che/pull/1366

**Comment by ghost** [comment]
@TylerJewell this PR does not let use a local dockerfile. It's either a remote one or recipe content.

@nischal62019 you mentioned a Dockerfile from a DockerHub? How do you reference a `recipe` from a dockerhub? Your syntax looks like referencing a base image to me.

**Comment by TylerJewell** [comment]
Provided by Chedir capability - closing this long lived support ticket.
