### ISSUE TITLE
project-template API missing on Swagger

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#13792]
### Description
`/api/project-template` is missing on `/swagger`. Service is defined here https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-project-templates/src/main/java/org/eclipse/che/api/project/server/template/ProjectTemplateService.java
This is current list of documented apis:
```
devfile
factory
installer
logger
preferences
profile
ssh
stack
system
user
workspace
```

I believe this api should be included here. Maybe we're missing some more?

### Reproduction Steps
deploy che and go to `<che-url>/swagger` . `project-template` is not there.

**OS and version:**    
latest
**Diagnostics:**

**Comment by skabashnyuk** [comment]
we might need to revisit the whole ProjectTemplateService  because of quite a lot of it functionality are Che6 oriented

**Comment by sparkoo** [comment]
maybe @ashumilova is using this API for her dashboard work

**Comment by sleshchenko** [comment]
I believe `project-template API` should be deprecated and removed in flavor of Devfile Registry.
I believe there should be some issue for Dashboard not to use it anymore.

**Comment by ashumilova** [comment]
We recently removed usage of this service on dashboard, so can be deprecated.

**Comment by sparkoo** [comment]
issue #13903 to remove the API was created. Closing this one.
