### ISSUE TITLE
Chectl server:start doesn't work on secured k8s

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13800]
### Description
When using a remote k8s (like running on EC2), when `chectl` is grabbing the status it may fail due to `Unauthorized` error.
It's because it is trying to perform http call without token

https://github.com/che-incubator/chectl/blob/d3ff3100b3da737f6bd9267f69d7e5800bdcf6a4/src/api/kube.ts#L566-L576

`${currentCluster.server}/healthz` is secured

So, installing che on these k8s installs is not possible with chectl

**Comment by l0rd** [comment]
This is a P1 but we don't have to support it for GA so setting milestone 7.1.0

**Comment by benoitf** [comment]
so it means basically chectl can't install che on EC2 for example for GA (as status is the first check)

**Comment by l0rd** [comment]
@benoitf is the token something that we already get with the KubeConfig or is something that the user should provide as a separate parameter?

**Comment by benoitf** [comment]
I'm able to grab it with default service account / secrets

**Comment by benoitf** [comment]
so basically user shouldn't do something

**Comment by l0rd** [comment]
ok so it looks that this hasn't impact on the UX and should be pretty easy to implement. Set milestone 7.0.0.
