### ISSUE TITLE
“Dependency problems found” when `mvn clean install` a che plugin project

### ISSUE THREAD

**Issue by xienaoban** [eclipse-che/che#13807]
### Description

I downloaded the che plugin project example [che-ide-server-extension](https://github.com/che-samples/che-ide-server-extension). It works when `mvn clean install`. But when I add a dependency in

```
che-ide-server-extension/plugins/plugin-serverservice/plugin-serverservice-ide/pom.xml
```

, it fails to install.

The dependency I added is

```xml
<dependency>
    <groupId>org.eclipse.che.core</groupId>
    <artifactId>che-core-ide-ui</artifactId>
</dependency>
```

And the error message of `mvn clean install -e -X` is:
```

...
[WARNING] Unused declared dependencies found:
[WARNING]    org.eclipse.che.core:che-core-ide-ui:jar:6.16.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Plugin ServerService :: Parent pom ................. SUCCESS [  2.174 s]
[INFO] Plugin ServerService :: Plugins ::  Parent ......... SUCCESS [  0.064 s]
[INFO] Plugin ServerService :: Plugin :: Parent ........... SUCCESS [  1.382 s]
[INFO] Plugin ServerService :: Plugin :: Server ........... SUCCESS [  3.827 s]
[INFO] Plugin ServerService :: Plugin :: IDE .............. FAILURE [  4.870 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Parent SKIPPED
[INFO] Plugin ServerService :: Che Assembly :: Workspace Agent Assembly SKIPPED
[INFO] Plugin ServerService :: Che Assembly :: Workspace Agent Tomcat Assembly SKIPPED
[INFO] Plugin ServerService :: Che Assembly :: IDE Assembly SKIPPED
[INFO] Plugin ServerService :: Che Assembly :: Assemblies Tomcat SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.925 s
[INFO] Finished at: 2019-07-10T10:48:43+08:00
[INFO] Final Memory: 75M/1321M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:analyze-only (analyze) on project plugin-serverservice-ide: Dependency problems found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:analyze-only (analyze) on project plugin-serverservice-ide: Dependency problems found
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Dependency problems found
    at org.apache.maven.plugins.dependency.analyze.AbstractAnalyzeMojo.execute(AbstractAnalyzeMojo.java:261)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :plugin-serverservice-ide
```

I don't think I added a wrong dependency. Because when I

```java
import org.eclipse.che.ide.ui.dialogs.DialogFactory;
```

in my java code, che says

```
The import org.eclipse.che.ide.ui.dialogs cannot be resolved.
```

But after I added the dependency, che can recognize it.

I don't know why this happens... The error message says Dependency problems found, but it didn't point out the real problem...

### Reproduction Steps

**OS and version:** 
Ubuntu 16.04
Docker 18.09.7
Che 6.16.0

**Comment by slemeur** [comment]
Hi @XieNaoban . 

Is there a particular reason you are interested in Che 6, compared to Che 7? 
We are getting close to the new version of Eclipse Che, version 7. It is currently in RC and already available to you if you want to test and use it.

https://www.eclipse.org/che/docs/che-7/che-quick-starts.html

There is a new default web IDE and a complete new extensibility model with Che 7, I would really encourage you to start your plugin on that newer version.
You can learn more about it here: https://www.eclipse.org/che/docs/che-7/extending-che.html

**Comment by XieNaoban** [comment]
@slemeur 
Of course I'm very willing to try Che 7 if I'm working for myself! I have to say I fell in love with this ide when I first saw it.

But as you said, because of the requirement of a project, I have to use 6.16.0 (not 6.17.0, not 6.15.0, but 6.16.0). So do you know why this error happens? I just did nothing except simply add a dependency.

By the way, there are some mistakes in [Eclipse Che Documentation :: Developer Guides :: IDE UI: Parts](https://www.eclipse.org/che/docs/che-6/index.html). For example, there isn't a constructor that satisfy `super(resources);` in `BaseView`. And 'user' was misspelled to 'usder'.

And there is no doc for [Server Side Extensions](https://www.eclipse.org/che/docs/che-6/server-side-extensions.html).

Given that Che 7 is being developed, are you guys no longer supporting the doc for Che 6 now?

**Comment by slemeur** [comment]
Thanks for the clarification @XieNaoban ! That's really interesting. 

You might be able to get some help from @vparfonov on this specific question and he might be able to give you an example of a server side extension as well.

Our target right now is mainly on Che 7 and there are many differences, especially in its extensibility which is getting simpler and richer. 
Once we have Che 7 out and generally available, we are planing to remove the documentation on Che 6, but it will still be available on the https://github.com/eclipse/che-docs repository, in the history.

**Comment by XieNaoban** [comment]
OK. Thank you @slemeur .

**Comment by XieNaoban** [comment]
Forgot to say, here is **Reproduction Steps**:

```bash
git clone https://github.com/che-samples/che-ide-server-extension
cd che-ide-server-extension
git checkout 6.16.0
vim plugins/plugin-serverservice/plugin-serverservice-ide/pom.xml    # add dependency
mvn clean install
```

**Comment by slemeur** [comment]
cc @vparfonov

**Comment by vparfonov** [comment]
@XieNaoban, try please:
`wget https://gist.githubusercontent.com/vparfonov/055dfe30a4ab1b235549a31f8e21dc7c/raw/ce828eab707ff7dc42d9c08f82268b2d6e44d69d/xyz.patch`
`git apply xyz.patch`
`mvn clean install`

Work well on my side

**Comment by XieNaoban** [comment]
In fact I found that it was because the maven version installed from apt-get was too old. I updated maven and finally it can tell the solution. After adding another dependency that new maven told me to add, it works. Anyway thank u @vparfonov . Sorry for wasting your time.
