### ISSUE TITLE
Unable to start a workspace on che.openshift.io

### ISSUE THREAD

**Issue by tomevision** [eclipse-che/che#13805]
### Description

> i can't start a workspace on che.openshift.io it displays the following error 
Failure executing: POST at: https://...../configmaps. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
"I tried to change my password but i didn't work"

**Comment by jmatsushita** [comment]
Getting the same error when starting a workspace. POST Url is:
```
https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/jmatsushita-che/configmaps
```

**Comment by ibuziuk** [comment]
@jmatsushita @tomevision hello, this issue should be fixed now on che.openshift.io (there was a cluster token update on `us-east-2` which resulted in workspace startup failure with `Unauthorized` errors). Could you please confirm that workspace startup works now without issue? Thanks!

**Comment by tomevision** [comment]
@jmatsushita it is working now!

**Comment by benoitf** [comment]
@ibuziuk should the issue be elsewhere than here ? It's the upstream project there

**Comment by ibuziuk** [comment]
@benoitf yeah, but che.openshift.io is promoted on https://www.eclipse.org/che/getting-started/ and we can not prohibit reporting issues directly in the upstream since very few people are aware of https://github.com/redhat-developer/rh-che

**Comment by l0rd** [comment]
@ibuziuk can we close this issue now?

**Comment by ibuziuk** [comment]
Closed based on reporter confirmation https://github.com/eclipse/che/issues/13805#issuecomment-509651503
