### ISSUE TITLE
chectl issues with tls option using helm

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13801]
### Description
When installing Che on top of k8s with helm and when we want to use certificates there are several errors

1. cheDomain is never set (so helm templates are failing)
2. multiUser is set to true so we can't use TLS without multi-user (and there is an issue for now on multi-user https://github.com/eclipse/che/issues/13625)
3. an email is required for let's encrypt/cert-manager option and the email can't be given (there is a default one which is not authorized with (`@example.com` suffix)
4. there is no check on a `che-tls` secret (if it's not there then it should not possible to proceed further)

**Comment by l0rd** [comment]
@benoitf from a severity point of view that looks like a SEV1 and needed for GA. But I am not able to understand the amount of work that is needed to fix that. In particular point n.3. The other points looks easy to fix.

**Comment by benoitf** [comment]
for 3. I would say: --tls-email option as quick workaround

**Comment by l0rd** [comment]
Ok this is a P1 and it's pretty easy to fix. Milestone 7.0.0.

**Comment by benoitf** [comment]
fixed now
