### ISSUE TITLE
[keycloak] Creating user page has invalid title

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13818]
### Description
When I launch che with keycloak and when I register a new user
I have the following screenshot
![image](https://user-images.githubusercontent.com/436777/61057513-c5103700-a3f5-11e9-898e-41df25ce6755.png)

looks like it displays a variable instead of the title

### Reproduction Steps
che-operator:nightly (multi-user)

**Comment by tsmaeder** [comment]
Not a 7.0.0 for me, but this sounds like it might be trivial to fix.
