### ISSUE TITLE
Create Jenkins job for checking custom PRs for che-theia repo

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13810]
### Description
According to **end game plan** https://github.com/eclipse/che/issues/13637 we should create Jenkins Job for the PR check from the che-theia repo.
For beginning steps we should:
* Build the Theia images accroding to **How to build own che-theia image** [topic](https://github.com/eclipse/che-theia).
* Launch OpenShift OKD and consumed the built image from PR
* Run E2E tests on this assembly

**Comment by dmytro-ndp** [comment]
The issue duplicates https://github.com/eclipse/che/issues/13326
