### ISSUE TITLE
It isn't possible to debug Python Django application

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#13816]
### Description
 
It isn't possible to debug Python Django application. When Python debug adapter starts debug session for Django application it sends `runInTerminal` request which starts a django server in side-car container. Since there aren't needed dependencies in the container it fails to start and debug session isn't initialized.

Actually this is a common problem and many debug adapter will face it.

### Reproduction Steps

1. Create workspace from python-django dev file [1]
2. Run commands to install dependencies, patch resources and migration
3. Create debug configuration (see below)
4. Try to start debug session
5. Debug failed

[1] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/python-django/devfile.yaml

**OS and version:**    
Che-7.0.0-rc-4-snapshot

**Diagnostics:** 

```
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "django": true
        }
```

**Comment by tsmaeder** [comment]
@tolusha the "runInTerminal" request is part of the DAP, right? Am I correct that this goes to the theia container and is then routed to the container running the python extension?

**Comment by tsmaeder** [comment]
@tolusha can you start a remote debug session?

**Comment by tsmaeder** [comment]
This would be 7.0.0 for me if we cannot debug at all. If we have a workaround, 7.1.0

**Comment by tolusha** [comment]
@tsmaeder 

> the "runInTerminal" request is part of the DAP, right? Am I correct that this goes to the theia container and is then routed to the container running the python extension

correct

> I think that routing is wrong, conceptually: the tooling container should contain stuff to run the tooling, nothing more.

That's arguable. Sidecar container doesn't know anything about other containers.

 > can you start a remote debug session?

No, I wasn't able.

**Comment by tolusha** [comment]
So, It is possible establish a remote debug session.
At least I can do it in VS Code and Theia IDE, but with Che Theia I got:
- Uncaught (in promise) Error: It is not possible to provide debug adapter executable for 'python'. (version: next)
- Uncaught (in promise) Error: Unknown method $activateByEvent on actor PluginManagerExt (version: 7.0.0-rc-3.0)

**Comment by tsmaeder** [comment]
$activateByEvent is related to activation events being implemented in theia master. It's not in the 
theia che-7.0.0 branch.

If we don't have a workaround, we need to escalate.

**Comment by tolusha** [comment]
We need the latest Theia version

**Comment by l0rd** [comment]
Why aren't we defining the launch config in the devfile as described [here](https://github.com/eclipse/che/issues/13057#issuecomment-489999146). 

@metlos and @RomanNikitenko have worked on handling that (transforming a che command in a vscode launch or task config). We should use that right?

**Comment by l0rd** [comment]
Oh that's already in [Che documentation as well](https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html#editor-specific-commands).

**Comment by tolusha** [comment]
@l0rd 
Cool, make sense. I haven't noticed this feature

**Comment by tolusha** [comment]
I am working on workaround and I will prepare a PR soon.

**Comment by tsmaeder** [comment]
The issue is still there, even if we have a workaound.

**Comment by tsmaeder** [comment]
Retargeting to 7.1.0

**Comment by l0rd** [comment]
@tolusha @tsmaeder can one of you describe the workaround here to help those that have the same issue?

**Comment by tolusha** [comment]
Currently I am working on redirection `runInTerminal` request to a dev container. The request above is used to run an application to debug. Current impediments are:
- using an env variable which will point to the dev container [1]. The env variables might be configured in a devfile [2]
- both dev and sidecar containers should use the same version of python
- debug configuration must be adjusted by adding a `pythonPath` attribute which points to a 
python in the dev container:
```json
{
        "name": "Python: Django",
        "pythonPath": "/usr/bin/python",
        "type": "python",
        "request": "launch",
        "program": "${workspaceFolder}/django-realworld-example-app/manage.py",
        "args": [
            "runserver",
            "--noreload"
        ],
        "django": true
    },
```
- It is necessary to share `/tmp/vscode-unpacked` folder files between sidecar and dev containers since it is used to run the application:

![error](https://user-images.githubusercontent.com/1640675/63153947-3906b600-c018-11e9-849c-bd48ffbc3f36.png)

[1] https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-remote/src/node/terminal-container-aware.ts#L59
[2] https://github.com/eclipse/che/issues/12555

**Comment by tsmaeder** [comment]
> debug configuration must be adjusted by adding a pythonPath attribute which points to a
python in the dev container:

Shouldn't this be an attribute of the python dev container somehow? 

> It is necessary to share /tmp/vscode-unpacked folder files between sidecar and dev containers since it is used to run the application:

No, we should use the version of python that is installed in the dev container, IMO.

**Comment by tolusha** [comment]
> No, we should use the version of python that is installed in the dev container, IMO.

It isn't a problem. The problem is that python is used some files from `/tm/vscod-unpacked` to run the application. These files comes with extensions.

**Comment by tsmaeder** [comment]
@tolusha you'd have to be more concrete here: what exactly is going on here? I don't understand.

**Comment by tolusha** [comment]
Have a look at screenshot. That is the command is run in dev container to start the app.
https://github.com/eclipse/che/issues/13816#issuecomment-521931270

**Comment by tsmaeder** [comment]
@benoitf @evidolob this would bring us back to the state where plugins are installed in a folder shared by all containers (kind of).

**Comment by amisevsk** [comment]
@tolusha As a test, is this issue resolved if you add a `/tmp/vscode-unpacked/` volume to the workspace devfile? 

Currently the only folder shared between theia and sidecars in the `/plugins` folder. If we also need `vscode-unpacked` then that's a fairly significant change.
