### ISSUE TITLE
Can not create a new pull request from GitHub plugin

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13814]
### Description
 
Can not create a new pull request from GitHub plugin
### Reproduction Steps

1. Add GitHub pull-request plugin
2. Open a workspace with a project cloned from GitHub
3. Checkout to a new branch and commit some changes.
4. Call `Create Pull Request` command

**WRONG:** Create process freezes, error occurred:
```root ERROR [hosted-plugin: 11878] (node:11878) UnhandledPromiseRejectionWarning: TypeError: s.window.createInputBox is not a function```

**OS and version:**    
7.0.0
**Diagnostics:**

**Comment by slemeur** [comment]
@vparfonov : Could you please give an estimate on this issue. Would **really** prefer to have that for 7.0.0

**Comment by vinokurig** [comment]
@slemeur There is a PR that fixes the bug: https://github.com/theia-ide/theia/pull/5187 AFAIK @JPinkney is working om it's comments

**Comment by JPinkney** [comment]
Yes, I'm still working on fixing up the comments. The reason its taking so long is I have to go back and re-do the way the createQuickPick api works (QuickInput/InputBox API's are all directly related) before I can start some of the improvements requested. The way that createQuickPick api was originally implemented doesn't allow for InputBox to be completed

**Comment by slemeur** [comment]
@l0rd + @rhopp + @tsmaeder + @nickboldt : This issue is making a lot of sense to be in 7.0.0. Having github plugin working with the ability of doing a PR is a must have.

**Comment by rhopp** [comment]
> This issue is making a lot of sense to be in 7.0.0. Having github plugin working with the ability of doing a PR is a must have.

Agree.

**Comment by JPinkney** [comment]
@vinokurig and I have agreed to split the work for the last few fix-ups on the QuickInput/InputBox/QuickPick API's so we can get this in for 7.0.0

**Comment by slemeur** [comment]
Thanks @JPinkney and @vinokurig !

**Comment by tsmaeder** [comment]
@slemeur I have to disagree that this is a must have: there is a very simple workaround: open the PR on github.com.  Not every bug and missing feature is 7.0.0-worthy.

**Comment by sunix** [comment]
@slemeur to me, before pushing a PR, you have to go through `git commit` ... so https://github.com/eclipse/che/issues/13874 is a must have

**Comment by l0rd** [comment]
For me this is a '7.0.0' but not a `severity/blocker`. Rather a `severity/P2`.

**Comment by slemeur** [comment]
The value added by the ability to automate the creation of a PR and provide the reviewer link is key to Che. It highlights a big promise of Che in how it can help developers being more efficient. 

If we don't have it, it'll be a functional gap from the targeted scope of the release. Something we have not been able to deliver.

**Comment by tsmaeder** [comment]
@slemeur time-quality-features, pick any two.

**Comment by slemeur** [comment]
@vparfonov What is the update on this?

**Comment by vinokurig** [comment]
fixed by theia-ide/theia#5187

**Comment by vinokurig** [comment]
fixed by theia-ide/theia#5187

**Comment by sunix** [comment]
Is it fixed in Che-theia 7.0.0-next ?

**Comment by vinokurig** [comment]
Yes, but the docker image is not built yet.

**Comment by sunix** [comment]
it is not merged yet ... https://github.com/theia-ide/theia/pull/5890

**Comment by vinokurig** [comment]
Now it is merged :)
