### ISSUE TITLE
Adapt "Stacks" in UD to Che 7

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#13811]
As far as we introduce the Che 7 with new devfile registry for the stacks - there is need to clean up the old views that contain Stacks management:

![Screenshot from 2019-07-10 14-55-13](https://user-images.githubusercontent.com/1611939/60967232-d63c4380-a322-11e9-9388-97ec2caa2ea6.png)

**Comment by slemeur** [comment]
Stacks should still be present, but we would display the devfile from the registry. 
User should be able to see where the devfile registry is and what is its source.

There would be no action possible on the stacks from the dashboard.
