### ISSUE TITLE
[Helm] warnings on booting keycloak

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13821]
### Description

This is not critical but I suspect it is one of the reason that causes #10300,  #13791.

### Reproduction Steps

0. Deploy Keycloak with Helm
0. Watch log by `kubecl logs`

**OS and version:**    

the HEAD of the master branch.

**Diagnostics:** 

```
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
-b 0.0.0.0
WARNING: POSTGRES_ADDR variable name is DEPRECATED replace with DB_ADDR
WARNING: POSTGRES_DATABASE variable name is DEPRECATED replace with DB_DATABASE
WARNING: POSTGRES_USER variable name is DEPRECATED replace with DB_USER
WARNING: POSTGRES_PASSWORD variable name is DEPRECATED replace with DB_PASSWORD
WARNING: POSTGRES_PORT variable name is DEPRECATED replace with DB_PORT
=========================================================================

  Using PostgreSQL database

=========================================================================
```

**Comment by monaka** [comment]
It may be too strict to tag `kind/bug` for just warning messages.
But it is related on the `POSTGRESS_PORT` issue. So I tagged it.

**Comment by rhopp** [comment]
@skabashnyuk I've assigned team/platform for analysis and severity estimation. If you think somebody else should take care of this, please tag them.

I've tried this using operator and keycloak image I built today from https://github.com/eclipse/che/pull/13798 and I don't see these warning in keycloak pod logs., even though I'm using the "old" variable names:
![image](https://user-images.githubusercontent.com/1215011/61140378-a67c6f80-a4cb-11e9-8049-680074ee6464.png)

**Comment by monaka** [comment]
@rhopp I'm no idea why it isn't reproduced on your environment. At least `POSTGRES_` style is obsolete. https://github.com/jboss-dockerfiles/keycloak/blob/master/server/README.md#database

**Comment by monaka** [comment]
@rhopp And one more issue. It looks `POSTGRES_PORT` on your container is `5432`, but it may be set to `tcp://{host}:5432` on multi-node K8s. It will be showstopper.

**Comment by monaka** [comment]
For now, I close this issue as warnings won't be shown in the normal deployment. I'll create the another issue after reproducing `POSTGRES_PORT` issue.
