### ISSUE TITLE
Empty Warning displayed

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13826]
### Description

![image](https://user-images.githubusercontent.com/1105127/61115435-bf1c6380-a492-11e9-8609-092686284ccd.png)

### Reproduction Steps

don't know. it often appears with my local installation with chectl, operator, minikube, Hyper-V and windows 10 

**OS and version:**    
 7.0.0.rc-4.0-SNAPSHOT

**Diagnostics:**

**Comment by rhopp** [comment]
@apupier Could you please provide more info, like browser console logs, server logs, ... next time this happens?

**Comment by apupier** [comment]
> Does this happen randomly, or are there any steps to reproduce?

I'm unable to determine steps to reproduce.

> Could you please provide more info, like browser console logs, server logs, ... next time this happens?

just occurred again:
I have 4 errors in console log:
 http://che-che.192.168.1.22.nip.io/api/oauth/ 403
http://che-che.192.168.1.22.nip.io/api/permissions/system 404
GET http://che-che.192.168.1.22.nip.io/api/organization/find?name=apupier 404
GET https://api.github.com/user 401 (Unauthorized)

can you precise which server log you want?
I tried to have a look to che-operator, che-xxx-xx, workspacexxxs but found no errors
