### ISSUE TITLE
Decouple Java selenium E2E tests from GWT-code

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#13827]
### Description
There is a plan to remove GWT-related code from Che https://github.com/eclipse/che/pull/13788, and [Java E2E selenium tests](https://github.com/eclipse/che/tree/master/selenium) should be aligned with this changes:

- [x] **step 1**: fix build of Java E2E selenium tests: there are outdated dependencies:
* org.eclipse.che.plugin:**che-plugin-github-shared**
* org.eclipse.che.plugin:**che-plugin-github-server** 
* org.eclipse.che.core:**che-core-api-debug-shared**

- [x] **step 2**: remove the tests which aimed to verify GWT-editor functionality:
* org.eclipse.che.selenium.assistant.*
* org.eclipse.che.selenium.languageserver.*
* org.eclipse.che.selenium.debugger.*
* org.eclipse.che.selenium.editor.*
* org.eclipse.che.selenium.filewatcher.*
* org.eclipse.che.selenium.git.*
* org.eclipse.che.selenium.intelligencecommand.*
* org.eclipse.che.selenium.mavenplugin.*
* org.eclipse.che.selenium.miscellaneous.*
* org.eclipse.che.selenium.opendeclaration.*
* org.eclipse.che.selenium.plainjava.*
* org.eclipse.che.selenium.testrunner.*
* org.eclipse.che.selenium.projectexplorer.*
* org.eclipse.che.selenium.refactor.*
* org.eclipse.che.selenium.stack.*
* org.eclipse.che.selenium.workspaces.CheckStopStartWsTest

- [x] **step 3**: rewrite next Dashboard tests which use GWT-editor to check changes in Dashboard, sorted by priority:
  - [x] org.eclipse.che.selenium.site.ocpoauth.LoginExistedUserWithOpenShiftOAuthTest
  - [x] org.eclipse.che.selenium.site.ocpoauth.LoginNewUserWithOpenShiftOAuthTest
  - [x] org.eclipse.che.selenium.git.AuthorizeOnGithubFromDashboardTest
  - [x] org.eclipse.che.selenium.dashboard.DeleteRunningWorkspaceTest
  - [x] org.eclipse.che.selenium.dashboard.DeleteStoppingWorkspaceTest
  - [x] org.eclipse.che.selenium.dashboard.RenameWorkspaceTest
  - [x] org.eclipse.che.selenium.dashboard.organization.ShareWorkspaceMemberTest
  - [x] org.eclipse.che.selenium.dashboard.workspaces.details.WorkspaceDetailsOverviewTest
  - [x] org.eclipse.che.selenium.workspaces.CheckStoppingWsByTimeoutTest
  - [x] org.eclipse.che.selenium.workspaces.ProjectStateAfterRefreshTest
  - [x] org.eclipse.che.selenium.workspaces.ProjectStateAfterWorkspaceRestartTest
  - [x] org.eclipse.che.selenium.workspaces.ProjectStateAfterRenameWorkspaceTest
  - [x] org.eclipse.che.selenium.hotupdate.recreate.RecreateUpdateStrategyTest
  - [x] org.eclipse.che.selenium.hotupdate.rolling.RollingUpdateStrategyWithEditorTest
  - [x] org.eclipse.che.selenium.hotupdate.rolling.RollingUpdateStrategyWithStartedWorkspaceTest
  - [x] org.eclipse.che.selenium.dashboard.workspaces.WorkspacesListTest
  - [x] org.eclipse.che.selenium.dashboard.workspaces.details.WorkspaceDetailsProjectsTest
  - [x] org.eclipse.che.selenium.hotupdate.rolling.RollingUpdateStrategyWithWorkspacesStartStopTest

**Comment by l0rd** [comment]
How much work is required by "rewrite Dashboard tests which use GWT-editor to check changes in Dashboard."? It's more than half a day can we postpone it after GA?

**Comment by rhopp** [comment]
I was thinking in this issue just in scope of Che 7 release - basically making the code "compilable" (that's why the che7GA target). I don't care much about the old tests and if something can be saved from existing tests with minimal amount of work, it should be done as part of different issue. I'll edit the description of this one and create another one for possible followup work.
Sorry for the confusion.

**Comment by rhopp** [comment]
Thinking again about this... For Che7GA, disabling whole `selenium` module should be enough (which is already done as part of https://github.com/eclipse/che/pull/13788) and this issue can be left as is, but postpone it post-GA.

**Comment by dmytro-ndp** [comment]
@rhopp: if we disable Java selenium e2e tests, we will stop testing IDE Dashboard on regular basis.

**Comment by dmytro-ndp** [comment]
We can clean up and enable Java selenium tests, but disable particular tests which we are going to re-write. It's about several days of work, IMHO.

**Comment by rhopp** [comment]
Right now I'm most interested in amount of test-cases which would work without any refactoring (after the build-time dependencies are removed).

**Comment by dmytro-ndp** [comment]
@SkorikSergey: FYI: rollout updating docs https://www.eclipse.org/che/docs/che-6/kubernetes-admin-guide.html#updating-che-without-stopping-active-workspaces
