### ISSUE TITLE
Need to periodically build `arbitrary-users-patch` images as part of the nightly che-devfile-registry ci job

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13837]
a nightly CI for devfile registry has been created as part of https://github.com/eclipse/che/issues/13813
https://ci.centos.org/job/devtools-che-devfile-registry-nightly/

Need to extend this CI to build and push not only `che-devfile-registry`, but also all patched language runtime images from https://github.com/ibuziuk/che-devfile-registry/tree/che-13813/arbitrary-users-patch which should also be pushed to https://quay.io/repository/eclipse/

This should be pretty straight forward - one just need to add execution of `build_images.sh` to the `cico_build_nightly.sh`

**Comment by ibuziuk** [comment]
@amisevsk hope you will be able to take a look at this one once you back
@l0rd please consider adding this issue to the Che 7 GA end game plan

**Comment by amisevsk** [comment]
Closing as nightly images are available (there are still a few devfiles that need testing and updating)
