### ISSUE TITLE
dashboard: incorrect handling of Enter button at workspace removing

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#13843]
### Describe the bug
I tried to use Enter button to confirm removing of a workspace from dashboard. 
The workspace was removed but two additional dialogs are came up to ask me to confirm workspace removing. Then two messages informed me that `undefined has been removed`
### Steps to reproduce
1. Select a workspace on dashboard
2. Click `Delete` button
3. You can see confirmation dialog:
![remove_workspace_dialog](https://user-images.githubusercontent.com/5676062/61186960-47a62a00-a674-11e9-86f5-8b12bb6629c4.png)
4. Confirm the action by pressing Enter button.

Please see the short video: https://youtu.be/-U2oOQaysww

**Comment by nickboldt** [comment]
How did you install Che? What version are you running?
I've never seen this with Che 7 RC3 on minishift. Is it possible that calling your workspace `che/che` instead of something like `wksp-java` confused some back end process?

**Comment by RomanNikitenko** [comment]
Hello!
I use  `minikube v1.0.0 on linux (amd64)`, `7.0.0-rc-4.0-SNAPSHOT`

> What's in the workspace that you're trying to delete? Maybe you generated a workspace with something incompatible in it?

I can reproduce it for workspace that I create using stacks from dashboard.

> Is it possible that calling your workspace che/che instead of something like wksp-java confused some back end process?

I don't think that is the cause of the issue.
Did you try to use `Enter` button (not mouse click) to confirm a workspace removing?

Please see the video: https://youtu.be/ucCQCSoFYSc
