### ISSUE TITLE
Document how to analyse Theia support for a given VS Code extension

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13849]
We are currently tracking [VS Code and Theia compability with regards to the support of the VS Code extension APIs](https://github.com/che-incubator/vscode-theia-comparator/).

It would be nice to help users to understand if a VS Code extension is expected to run properly in Theia (because the API it calls are already implemented in Theia) or if, in the contrary it may behave incorrectly (because some API are not or partially implemented).

These manual steps could be added in che-docs, in section "Using a Visual Studio Code extension in Che".

**Comment by nickboldt** [comment]
I'm guessing this isn't urgent for 7.0 or 7.1, but might be nice for 7.2?

**Comment by tsmaeder** [comment]
This issue should be on the theia repo, not here.
