### ISSUE TITLE
Workspace loader does not show that workspace failed to start if it happens too fast

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13846]
### Describe the bug
Workspace loader does not show that workspace failed to start if it happens too fast.

### Che version

 - [ ] latest
 - [x] nightly (7.0.0-rc-4.0-SNAPSHOT)
 - [ ] other: please specify

### Expected behavior
Workspace loader report that workspace failed to start and there is no Loader anymore.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![wsloader](https://user-images.githubusercontent.com/5887312/61215957-e2eedc00-a714-11e9-99bd-25d56825e5e6.gif)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
It was initially found because of the issue that is described here https://github.com/eclipse/che/issues/13842
Reproduction steps can be unactual after fixing it, to reproduce it please use the following docker image `sleshchenko/che-server:issue-13846`

**Comment by nickboldt** [comment]
Assuming the workaround is "refresh browser tab" this is non blocking. Assuming to 7.1.0

**Comment by akurinnoy** [comment]
I suppose this is the same issue as https://github.com/eclipse/che/issues/13209 ([pull request](https://github.com/eclipse/che/pull/13804))

**Comment by sleshchenko** [comment]
@akurinnoy You're right. Thanks for sharing.

Closing issue since it duplicates https://github.com/eclipse/che/issues/13209
