### ISSUE TITLE
Unable to connect ARTIK device 

### ISSUE THREAD

**Issue by yogeshg39** [eclipse-che/che#1385]
Hi,

I am unable to connect the ARTIK device with the ide. I followed the directions given in the https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started . When I enter the ip address, username and password and try to connect the device I get the following error:

**Failed to connect to device artik_device_1 due to an error
Ssh machine creation failed because ssh of machine is inaccessible. Error:timeout: socket is not established**

What am I doing wrong? How to make ssh of machine accessible?

**Comment by ghost** [comment]
@yogeshg39 can you connect to the device using the same IP, username and password? The error says that IP cannot be reached.

**Comment by yogeshg39** [comment]
@eivantsov I am able to connect to the device using terminal using same username and password.

**Comment by ghost** [comment]
@yogeshg39 what you can do is to run a Docker container manually, and try to ssh into the device from within a container:

`docker run -ti codenvy/artik bash`
`ssh username@IP`

You may also want to try the same from within the VM, in case you're on Mac or Windows (not running Artik IDE natively)

**Comment by yogeshg39** [comment]
@eivantsov I am using the vagrant file for running the ide. So how do I ssh into the device.

**Comment by benoitf** [comment]
`$ vagrant ssh `
(where the Vagrantfile is)

**Comment by ghost** [comment]
@yogeshg39 when in a directory with a Vagrantfile run:

`vagrant ssh`

**Comment by yogeshg39** [comment]
@eivantsov  Ok now I am able to ssh into the device but how it doesn't make it discover able.

**Comment by ghost** [comment]
@yogeshg39 when in the VM, can you ssh into the device using the IP that worked for you locally?

Next thing to try is to:

`docker run -ti codenvy/artik bash`

and then ssh into the device

**Comment by yogeshg39** [comment]
@eivantsov I am able to ssh into the device by doping vagrant ssh in the directory which had vagrant file.. I am not understanding what do you mean ssh into the device using the IP. 

 I did docker run -ti codenvy/artik bash but after that I am not getting what has to be done.

What has to put in host while connecting to device. IP of board?

**Comment by ghost** [comment]
@yogeshg39 yes, IP of board. Have you configured LAN or WLAN for your device?

Can you ssh into the device from within a container?

`docker run -ti codenvy/artik bash`
`ssh username@IP`

Also, can you share the command line you use to ssh into your device from a local terminal (that you say works for you).

**Comment by TylerJewell** [comment]
Old issue - should have been archived.
