### ISSUE TITLE
SSH plugin doesn't show if the generation has been successful or not

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13857]
### Describe the bug
The SSH plugin is not show the generate key.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Command palette and generate key pair
2. Select first option "VCS"
3. See the message asking if we want to view the SSH key. Click "View"

Result-> nothing happens

### Expected behavior
User should be prompt a message that the ssh key has been generated and it should be possible to open it.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Capture d’écran 2019-07-16 à 11 44 33](https://user-images.githubusercontent.com/1636769/61284730-dc696e80-a7bf-11e9-9c28-466d73f47bf9.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by slemeur** [comment]
cc @vparfonov

**Comment by vinokurig** [comment]
Was fixed by https://github.com/eclipse/che-theia/pull/352 and https://github.com/eclipse/che-theia/pull/360
