### ISSUE TITLE
Fix selenium tests after last dashboard changes

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#13856]
### Description
_After the last changes on the dashboard, there needs to adapt the E2E selenium tests which check some functionality from it._

**OS and version:**    
Che 7.0.0-rc-4.0-SNAPSHOT   

**Additional information:**
* Related PR: https://github.com/eclipse/che/pull/13825
* Related selenium test: _CreateAndDeleteProjectsTest_, _CreateWorkspaceTest_

**Comment by l0rd** [comment]
Looks like a 7.0.0 as part of https://github.com/eclipse/che/issues/13665
