### ISSUE TITLE
plugin eclipse/che-theia/latest is not using the right definition

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13859]
### Describe the bug
[eclipse/che-theia/latest/meta.yaml](https://github.com/eclipse/che-plugin-registry/blob/c9138fe8be2980897873bd0caf3c341ff78ea45d/v3/plugins/eclipse/che-theia/latest/meta.yaml)

and 

[eclipse/che-theia/7.0.0-rc-3.0/meta.yaml](https://github.com/eclipse/che-plugin-registry/blob/c9138fe8be2980897873bd0caf3c341ff78ea45d/v3/plugins/eclipse/che-theia/7.0.0-rc-3.0/meta.yaml)

are different (for instance see the exposed ports and endpoints)
latest should be using one the tagged version.

The result of this is that `eclipse/che-theia/latest` cannot use the theia port plugin and user have to add port to expose manually in the devfile.

`latest` should be the same as one of the released versions at least.

**Comment by l0rd** [comment]
It looks to me that
- `next`: che-theia latest commit
- `latest`: che-theia latest stable version
- `x.y.z`: che-theia specific stable version

So yes I think you are right @sunix. The fix here should to update `eclipse/che-theia/latest` to match `clipse/che-theia/7.0.0-rc-3.0`? That's something that may be addressed in https://github.com/eclipse/che-plugin-registry/pull/183.

cc @benoitf @evidolob @vparfonov

**Comment by sunix** [comment]
@vparfonov @l0rd so has been merged and the problem is still here
https://github.com/eclipse/che-plugin-registry/blob/649e6ce378d13d93e662887e473b13e144349ee9/v3/plugins/eclipse/che-theia/latest/meta.yaml
and
https://github.com/eclipse/che-plugin-registry/blob/649e6ce378d13d93e662887e473b13e144349ee9/v3/plugins/eclipse/che-theia/7.0.0-rc-3.0/meta.yaml

should be identical

**Comment by amisevsk** [comment]
Also from the `./scripts/setup_latest_dirs.sh` script:

```
Working on directory: v3/plugins/eclipse/che-theia
  WARN: Found newer meta.yaml in  v3/plugins/eclipse/che-theia/next/meta.yaml
        No changes are made, but ensure the correct version is in 'latest'
Working on directory: v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools
  WARN: Found newer meta.yaml in  v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/meta.yaml
        No changes are made, but ensure the correct version is in 'latest'
Working on directory: v3/plugins/redhat/vscode-openshift-connector
  WARN: Found newer meta.yaml in  v3/plugins/redhat/vscode-openshift-connector/0.0.21/meta.yaml
        No changes are made, but ensure the correct version is in 'latest'
Working on directory: v3/plugins/redhat/vscode-xml
  WARN: Found newer meta.yaml in  v3/plugins/redhat/vscode-xml/0.7.0/meta.yaml
        No changes are made, but ensure the correct version is in 'latest'
```
Double checking these there are a few small differences from `latest` (e.g. `vscode-kubernetes-tools` does not specify a memory limit in `latest`); the script may also be slightly out of date in how it does comparison.

**Comment by amisevsk** [comment]
(Most of these inconsistencies are due to `firstPublicationDate` not matching.

**Comment by sunix** [comment]
would symbolic links work with the registry ?

**Comment by l0rd** [comment]
@sunix we have discussed with @vparfonov about this earlier today. You are right and we have updated the release procedure with a new step to fix this problem. But that's really not a big deal: who is using `che-theia:latest`?.

**Comment by sunix** [comment]
Well I use that one on che.openshift.io to test the stable release and not having to change the version at each release.

**Comment by amisevsk** [comment]
@sunix regarding symbolic links:

I tried that initially in implementing latest versions, but it comes with a few issues (most notable of which is that it results in the `latest` version being shown twice since there are two metas with that version).

There is more discussion in the original PR: https://github.com/eclipse/che-plugin-registry/pull/143

**Comment by amisevsk** [comment]
Issue is out of date.
