### ISSUE TITLE
Can not start /debug hosted plugin in the dev container

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13854]
### Describe the bug

Can not start /debug hosted plugin in the dev container

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a workspace from [dev-file](https://github.com/sunix/devfiles/blob/master/che-in-che/che-theia.devfile.yaml)
2. Open dev container's terminal `ctrl + ~` => `che-dev`
3. Execute `cd /projects/theia && che:theia init && yarn && cd /projects/theia/examples/assembly && yarn start --hostname=0.0.0.0 --port=3010`
4. A notification will appear, click `Open Link`: 
![screenshot-che-eclipse-che 192 168 42 143 nip io-2019 07 16-10-26-02](https://user-images.githubusercontent.com/7668752/61275875-842e6e80-a7b7-11e9-86c7-99da5b083c9f.png)
5. A Preview Tab will open, click the url:
![screenshot-che-eclipse-che 192 168 42 143 nip io-2019 07 16-10-52-55](https://user-images.githubusercontent.com/7668752/61276123-10d92c80-a7b8-11e9-9d21-e0f39e637cd6.png)
6. In the new tab open workspace with plugin: File => Open Workspace..
7. Start Hosted Plugin: F1 => Hosted Plugin: Start Instance...
8. Go to the first tab and do the same as described in step 4 and 5

**WRONG:** Plugin starts but fails very soon. 
Error in the output: `Hosted instance has been terminated` 
Error in the dev terminal: ```root ERROR Request runHostedPluginInstance failed with error: Unable to ping the remote server Error: Unable to ping the remote server
    at NodeHostedPluginRunner.<anonymous> (/projects/theia/packages/plugin-dev/lib/node/hosted-instance-manager.js:246:40)
    at step (/projects/theia/packages/plugin-dev/lib/node/hosted-instance-manager.js:80:23)
    at Object.next (/projects/theia/packages/plugin-dev/lib/node/hosted-instance-manager.js:61:53)
    at fulfilled (/projects/theia/packages/plugin-dev/lib/node/hosted-instance-manager.js:52:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sunix** [comment]
Could you describe what you are expecting ? It is hard to understand your steps and what you are trying to do. Why are you openning 2 tabs ?

**Comment by vinokurig** [comment]
I want to debug existed che-theia plugin e.g. ssh plugin, so I start clean theia in a dev container and then run the plugin from that instance

**Comment by sunix** [comment]
why `open workspace` ?

**Comment by sunix** [comment]
i don't understand why you mix hosted mode and execution of commands to run a dev theia ....

**Comment by sunix** [comment]
FYI now the devfile is in che-theia/devfiles. See https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md

**Comment by vinokurig** [comment]
> why open workspace ?

To not to edit path to the plugin when starting hosted instance

> i don't understand why you mix hosted mode and execution of commands to run a dev theia ....

Could you please explain your question

**Comment by sunix** [comment]
maybe you shouldn't use hosted mode ...

**Comment by l0rd** [comment]
@sunix the doc to setup the Theia Plugin environment for development are [here](https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md#devfile-for-contributing-to-theia-or-che-theia-extensions-or-che-plugins) right?

**Comment by vinokurig** [comment]
@sunix 
> maybe you shouldn't use hosted mode ...

How to debug the plugin? it is not clear from the documentation

**Comment by sunix** [comment]
> @sunix the doc to setup the Theia Plugin environment for development are [here](https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md#devfile-for-contributing-to-theia-or-che-theia-extensions-or-che-plugins) right?
> 
> And if @vinokurig follows this documentation everything should work fine right?

yes it is here, but I personnally never had to debug and always find a way to reproduce things and testing things with unit tests.
However it could be worth it to add that part in the doc.
