### ISSUE TITLE
After running command, preview link does not show website

### ISSUE THREAD

**Issue by dneary** [eclipse-che/che#13855]
After running the command, I get a message that an application is listening on port 80, and asking if I would like to redirect so that I can access it. I clicked yes, and after a few seconds, the link showed https://routeflsy1t2z-dneary-che.b542.starter-us-east-2a.openshiftapps.com/ - an Apache index with /che-website and /che in it. I clicked on /che and saw a preview of the website. I was expecting to have the preview link show the website directly. If it's possible to have the preview link include "/che", it would make it easier to get to the preview.

**Comment by apupier** [comment]
I transferred the issue to the main repository (using the [new Github functionality](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) available at the bottom left)

**Comment by sunix** [comment]
@dneary it should be fixed now with https://github.com/eclipse/che-website/commit/e717f4b236abf0c79e53485bc9c58fc466bddf92

**Comment by dneary** [comment]
Verified, thanks.

**Comment by dneary** [comment]
> hello @dneary
> issues need to be created on the main che repository (as explained when trying to use new issue button and inside the templates)

Thanks @benoitf - the template may have been new, I did not see it.
