### ISSUE TITLE
Workspace created by `/api/devfile` endpoint doesn't show containers in "My Workspace" panel

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13860]
### Describe the bug
Creating workspace using `/api/devfile`  endpoint results in errorneous workspace -> no containers are shown in "My Workspace" panel:
![image](https://user-images.githubusercontent.com/1215011/61292046-7df8bc00-a7d0-11e9-8dd9-fe28ed641d0f.png)

Starting the same workspace using `/api/workspace/devfile` works fine, but this endpoint is marked as deprecated in favor of `/api/devfile`.

I was able to reproduce this in 100% cases with https://github.com/eclipse/che/blob/master/e2e/files/happy-path/happy-path-workspace.yaml (devfile used for Happy Path test).

This behavior is **not reproducible** with https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/devfile.yaml for example.

### Che version

 - [ ] latest
 - [ x ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create workspace using `/api/devfile` endpoint:
`curl -X POST -H "Authorization: Bearer $ACTIVE_TOKEN" -H 'Content-Type: text/yaml' --data-binary @/home/rhopp/git/che/e2e/files/happy-path/happy-path-workspace.yaml http://che-che.192.168.39.242.nip.io/api/devfile`
2. Start the workspace
3. Open "My Workspace" panel on the right.
4. See, that the panel is empty - it should show all the containers in my workspace.

### Expected behavior
My Workspace panel should show all containers in the worspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ x ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)
k8s - 1.15
minikube - 1.2

### Screenshots
See description.

### Installation method
   - [ x] chectl - from master - latest commit d510045 (`chectl server:start -m -a helm`)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ x ] my computer 
       - [ ] Windows
       - [ x ] Linux (F30)
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
@rhopp 

> Starting the same workspace using /api/workspace/devfile works fine, but this endpoint is marked as deprecated in favor of /api/devfile.

Should not it be vice versa https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/DevfileService.java#L101 ?

**Comment by rhopp** [comment]
@sleshchenko Yeah... you are right... I got confused by the message in /workspace/devfile:
`This method is in beta phase. It's strongly recommended to use POST /devfile instead to get a workspace from Devfile. Workspaces created with this method are not stable yet.`
After reading this I considered this endpoint as "deprecated" (even though it's clearly stating it's "beta and might be unstable" - I'm dumb :-D).
Sorry for the confusion.
Do you thing it would be beneficial to change this issue to issue about changing the descriptions of the endpoints? And maybe remove /devfile endpoint before GA?

**Comment by sleshchenko** [comment]
@rhopp If it's true

> Creating workspace using /api/devfile endpoint results in errorneous workspace -> no containers are shown in "My Workspace" panel:

Then this issue for IDE2 team to fix machines tab. Is it?

Also, I tried to reproduce it on my side with `swagger` and found another issue, it's impossible to create a workspace and error message is so strange. I'm registering a new issue for that.

**Comment by l0rd** [comment]
I looks like this issue is a duplicate of #13867 so flagging it as such. If that's the case please close one of these 2 issues.

**Comment by rhopp** [comment]
Yep... In the end it's the duplicate. Closing this one.
