### ISSUE TITLE
Add postload actions in devfile

### ISSUE THREAD

**Issue by jmatsushita** [eclipse-che/che#13862]
Reposting https://github.com/redhat-developer/devfile/issues/33

Hi there,

I'm trying to run a post startup macro in che, in order to reconfigure multiple containers with the route urls assigned by https://che.openshift.io (7.0.0-RC-1.1)

In order to avoid user intervention I was hoping to use something like Chefile's workspace.postload.actions[1].script. Is this something that could be part of devfiles ? Or is there another approach to launching commands after the workspace is loaded? IIUC this is the only moment in the lifecycle of a workspace where route urls will be available. Should this be more of a che upstream issue?

Thanks,

Jun

**Comment by amisevsk** [comment]
Hi Jun,

As far as I know, this is something that is being discussed for after the Che 7 release (but I cannot find the issue I'm thinking of at the moment). It's currently not possible in the version running on che.openshift.io, sadly.

Could you be more precise in the post startup configuration you are trying to do?
