### ISSUE TITLE
Retest and unify all devfiles with samples

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#13863]
### Is your task related to a problem? Please describe.
We have ~20 devfiles with samples and it is the first thing that new user will probably try and see in Che, thus user experience here is critical. Along the way of creating these devfiles, several issues were created and fixed (#13796, #13823, #13592, and probably more). These might cause new issues in already merged devfiles.

### Describe the solution you'd like
After all agreed devfiles are merged #13529, we should retest them all, unify them (names, descriptions, tasks) and address all user experience issues. User experience must be as smooth as possible.

### Describe alternatives you've considered
do nothing

### Additional context
this is follow-up of #13529

**Comment by l0rd** [comment]
This issue doesn't look like a "new issue" but rather as a subtask of  https://github.com/eclipse/che/issues/13529 that you would like to include in 7.0.0. Is it correct @sparkoo?

**Comment by sparkoo** [comment]
@l0rd I thought of it as a follow-up task. But might be a subtask as well.
I'd like to include this to 7.0.0 as I believe user experience here is critical. However, I'd like to hear yours and others opinion, whether it is really needed to do.

**Comment by sparkoo** [comment]
I've identified several issues.
- Hit already reported issues #13862, #13739, #13964
- Reported few generic ones #14006, #14000 
- java-mysql https://github.com/eclipse/che/issues/13938#issuecomment-514679881
- java apache camel - https://github.com/eclipse/che/issues/14003 and JLS https://github.com/eclipse/che/issues/14004
- Go https://github.com/eclipse/che/issues/14007
- Nodejs mongo https://github.com/eclipse/che/issues/14009
- php-laravel https://github.com/eclipse/che/issues/14010
- php apache https://github.com/eclipse/che/issues/14011

I'm closing this task, problems should be solved in particular issues.
