### ISSUE TITLE
Improve SSH plugin to be able to execute git commands via ssh

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13866]
### Is your enhancement related to a problem? Please describe.

Currently SSH plugin stores ssh keys only in the user preferences. The keys are not visible for Git in the theia's container.
### Describe the solution you'd like

Need to store SSH private keys as files in the `~/.ssh` directory and manage them with the help of [config](https://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/) file
### Additional context

Part of #13494

**Comment by l0rd** [comment]
Setting milestone 7.0.0 as this is a subtask of the part of https://github.com/eclipse/che/issues/13494 that it's already in the endgame.
