### ISSUE TITLE
Button to go back to dashboard in factory screen does not work

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13875]
### Describe the bug
It is not possible to click on the button "Back to dashboard" when starting a workspace from a devfile. The loading screen seems broken

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start from devfile http://che-che.192.168.99.108.nip.io/f?url=https://github.com/sunix/che-quarkus-demo 
2. Wait for the failure
3. Once you have the timeout error, click on "Back to dahsboad" button.

<img width="1758" alt="Capture d’écran 2019-07-17 à 09 58 51" src="https://user-images.githubusercontent.com/1636769/61358076-d20bab00-a879-11e9-9183-575280232725.png">

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sunix** [comment]
looks like it is fixed
