### ISSUE TITLE
Terminal widget is not displayed for theia tasks

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#13876]
### Describe the bug
Terminal widget works well for che tasks, but it is not displayed for theia tasks, so user can not see output for tasks with `shell` type, for example.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: 7.0.0-rc-4.0-SNAPSHOT

### Steps to reproduce
1. Create workspace using any stack from dashboard
2. Create `tasks.json` file in `/projects/.theia` directory
3. Add the content:
```
{
    "tasks": [
        {
            "label": "Run my test task",
            "type": "shell",
            "command": "./task-long-running"
        }
    ]
}
```
4. Create file `task-long-running` in `/projects` directory with content:
```
#!/bin/bash

for i in {1..5}
do
   sleep 1
   echo "tasking... $i"
done

```
5. Go to the terminal: `chmod +x task-long-running`
6. Go to `Terminal` => `Run Task` and run the task
7. You can see:
- message that task has been started
- the process is running (from terminal)
- in 5 sec message that task has exited
- but output is absent - terminal widget is not displayed
- error in browser console at creating terminal widget

Please see the video: https://youtu.be/hPgVKivYsoo

### Expected behavior
Please see the video how it works for theia project: https://youtu.be/GiwqXal3Knc

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (minikube v1.0.0 on linux (amd64))
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![terminal_widget_error](https://user-images.githubusercontent.com/5676062/61359865-f66d8480-a885-11e9-91fd-3937d2844226.png)

### Installation method
   - [x] chectl (chectl/0.0.2-6d3894f linux-x64 node-v10.4.1)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by vparfonov** [comment]
Will we cherry-pick https://github.com/eclipse/che-theia/pull/365 to the 7.0.0 branch ?

**Comment by evidolob** [comment]
Yes https://github.com/eclipse/che-theia/pull/368
