### ISSUE TITLE
configmaps "sshconfigmap" already exists.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13873]
### Describe the bug

I try to spin up two workspaces on the same wsmaster.
I got an error same as the title of this issue.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

0. Spin up your workspace.
1. Spin up your another workspace.

### Expected behavior

Two workspaces run.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-21T13:09:06Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
### Screenshots

![Screenshot 2019-07-17 at 15 30 08](https://user-images.githubusercontent.com/101795/61352549-a05e0880-a8a8-11e9-8744-3b5aadb56941.png)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] ~~I don't know~~ Helm charts customized by me.

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] ~~Linux~~ ChromeOS
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [x] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

```
workspace-loader.ts:48 Error: Failed to run the workspace: "Failure executing: POST at: https://camino-wus-2-4c0ff018.hcp.westus2.azmk8s.io/api/v1/namespaces/banco/configmaps. Message: configmaps "sshconfigmap" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=sshconfigmap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "sshconfigmap" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
    at workspace-loader.ts:209
    at che-json-rpc-master-api.ts:202
    at json-rpc-client.ts:196
    at Array.forEach (<anonymous>)
    at e.processNotification (json-rpc-client.ts:195)
    at e.processResponse (json-rpc-client.ts:182)
    at json-rpc-client.ts:99
    at websocket-client.ts:121
    at Array.forEach (<anonymous>)
    at e.callHandlers (websocket-client.ts:121)
```

**Comment by sleshchenko** [comment]
cc @vparfonov

**Comment by l0rd** [comment]
@slemeur I am tagging it as 7.0.0 because it looks like a blocker
