### ISSUE TITLE
Preconfigure git user information from Che user's profile/preferences

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13874]
### Is your enhancement related to a problem? Please describe.

When the user is performing a `git commit` through a terminal on a container or through the vscode extension, email and name are not configured.
At the moment, the user has to run these commands on the right git containers each time a new workspace is started.

```bash
git config --global user.name "John Doe" && git config --global user.email "john.doe@acme.com"
```

### Describe the solution you'd like

If it was resolved in Che-theia, it will be good to get them from `/api/preferences`.

Few ideas for fixing it:
1. Retrieve defaults one from the che user api.
2. Store name/email in preferences. 
3. Execute the previous commands on each containers (hard to predict where git is available or not, commands may fail)
4. Add these env variables on each containers (don't need git to be present, won't crash) https://git-scm.com/book/pl/v2/Git-Internals-Environment-Variables
   > GIT_AUTHOR_NAME is the human-readable name in the “author” field.
   > GIT_AUTHOR_EMAIL is the email for the “author” field.
   > GIT_COMMITTER_NAME sets the human name for the “committer” field.
   > GIT_COMMITTER_EMAIL is the email address for the “committer” field.
5. Use EMAIL env variable
   > EMAIL is the fallback email address in case the user.email configuration value isn’t set. If this isn’t set, Git falls back to the system user and host names.
6. Store/mount ~/.gitconfig in preferences (but where to mount them ? as `$HOME` maybe different is moving from one container to another)

### Describe alternatives you've considered

If it was resolved in deployments, it will be good to create configmap and to mount `/etc/gitconfig`.

### Additional context

![Screenshot 2019-07-17 at 15 07 52](https://user-images.githubusercontent.com/101795/61357988-4f541180-a8b4-11e9-9ee6-ca285d31c5cc.png)

**Comment by slemeur** [comment]
Hi @monaka ! Thanks for raising this issue. 
@sunix also raised the same concern here: https://github.com/eclipse/che/issues/13880. I'm going to close the issue https://github.com/eclipse/che/issues/13880 and add the information from the issue in this enhancement request.

**Comment by slemeur** [comment]
This sounds like a must have IMO and I can understand why it was labelled as a bug in #13880. 
Unfortunately, I don't think we can afford for 7.0 GA but most probably in 7.1

**Comment by monaka** [comment]
> Store/mount ~/.gitconfig in preferences (but where to mount them ? as $HOME maybe different is moving from one container to another)

`/etc/gitconfig` is a placeholder for all users (see [the official book](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup)).
This will be a reasonable place since ssh private keys are mounted under `/etc/ssh`.

**Comment by vzhukovskii** [comment]
I can propose such solution:

* create mechanism, which will provision values of `user.name` and `user.email` at workspace startup, based on profile info (username and email in profile attributes). If there is no any attributes in profile, then only user name and email will be picked up.
* on second iteration, to create plugin in che-theia, which adds file watchers to local and global `.gitconfig`. So if there is any modifications occurred with git configuration, plug-in will parse data and put necessary information into user profile attributes, so on the second workspace provision, system git config will be updated with new values.

wdyt?

**Comment by sunix** [comment]
> * create mechanism, which will provision values of `user.name` and `user.email` at workspace startup, based on profile info (username and email in profile attributes). If there is no any attributes in profile, then only user name and email will be picked up.

So this similar to 1. from the description: *1. Retrieve defaults one from the che user api.*
What is the difference between user api and profile api ?


> * on second iteration, to create plugin in che-theia, which adds file watchers to local and global `.gitconfig`. So if there is any modifications occurred with git configuration, plug-in will parse data and put necessary information into user profile attributes, so on the second workspace provision, system git config will be updated with new values.

I am not sure which use case it is solving. And it sounds too complicated.

**Comment by vzhukovskii** [comment]
>What is the difference between user api and profile api ?
Technically, there's no difference. I mean, first, look for a preconfigured attributes in profile, if there is no attributes, then took user name and email.

>I am not sure which use case it is solving.
User can execute command git config and set up `user.name` and `user.email` from the terminal. When workspace will restart, user will lose configured configuration in `~/.gitconfig`. This need to preserve user configuration.

**Comment by sunix** [comment]
This issue is about having the git config `user.name` and `user.email` set up by default somehow on all containers before doing the first commit. We are looking for a simple flow for the user.

Your use case involves a workspace restart, synchronizations and user manual configuration which sound too complicated.

**Comment by vzhukovskii** [comment]
Okay, then I'm going to reopen this issue: https://github.com/eclipse/che/issues/13959

**Comment by gorkem** [comment]
@vzhukovskii I like the approach. Let' s implement the `create mechanism, which will provision values of `user.name` and `user.email` at workspace startup` first and do the full `git config --global` synchronization as the next step.  When we implement this we should be careful to replace only the `user.name` and `user.email` for global config and nothing else.

**Comment by sunix** [comment]
Ok this is a first step this is good but... i am confused.
The title of this issue says `Preconfigure ... from Che user's profile/preferences` but we are not preconfiguring this as I see from the video. So let's say that a user has setup Che and configured a Che user and started a workspace with it. Could we `Preconfigure` the git username and git email with the Che user information ?
I am reopening this issue as it is not completely fixed.

**Comment by vzhukovskii** [comment]
>Could we Preconfigure the git username and git email with the Che user information (if empty)?

Yes, there is a dedicated issue for that: https://github.com/eclipse/che/issues/14416

**Comment by sunix** [comment]
@vzhukovskii sorry i removed my comments because i wanted to double check first
