### ISSUE TITLE
Git user email and name not configured.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13880]
### Describe the bug
When the user is performing a `git commit` through a terminal on a container or through the vscode extension, email and name are not configured.
At the moment, the user has to run these commands on the right git containers each time a new workspace is started.

```bash
git config --global user.name "John Doe" && git config --global user.email "john.doe@acme.com"
```
Few ideas for fixing it:
1. Retrieve defaults one from the che user api.
2. Store name/email in preferences. 
3. Execute the previous commands on each containers (hard to predict where git is available or not, commands may fail)
4. Add these env variables on each containers (don't need git to be present, won't crash) https://git-scm.com/book/pl/v2/Git-Internals-Environment-Variables
   > GIT_AUTHOR_NAME is the human-readable name in the “author” field.
   > GIT_AUTHOR_EMAIL is the email for the “author” field.
   > GIT_COMMITTER_NAME sets the human name for the “committer” field.
   > GIT_COMMITTER_EMAIL is the email address for the “committer” field.
5. Use EMAIL env variable
   > EMAIL is the fallback email address in case the user.email configuration value isn’t set. If this isn’t set, Git falls back to the system user and host names.
6. Store/mount ~/.gitconfig in preferences (but where to mount them ? as `$HOME` maybe different is moving from one container to another)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

**Comment by slemeur** [comment]
Closing this issue in favor of #13874.
(Content of this issue merged with #13874)
