### ISSUE TITLE
[docs] Document All fields of the CheCluster CR in che-docs and CRD

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#13886]
### Is your task related to a problem? Please describe.

Update - https://github.com/eclipse/che/issues/13886#issuecomment-534171945

Today, there is no clear example of the CR file required to do a full deployment override of the 6 images in Che 7, eg., for a customer air gap scenario where they can't see quay/RHCC/dockerhub.

Images to be overridden in the custom resource are:

* cheImage
* postgresImage
* identityProviderImage
* pvcJobsImage
* devfileRegistryImage
* pluginRegistryImage

### Describe the solution you'd like

So, we should document how to use `chectl  --che-operator-cr-yaml=internal.yaml` with a concrete example.

### Describe alternatives you've considered

I might start down this road w/ a [blog post](https://divby0.blogspot.com/), which can then later become a contribution to che-docs and chectl.

### Additional context

Also requested in mattermost: https://mattermost.eclipse.org/eclipse/pl/dub6mhx5kb8zpgauixz8yyogow

**Comment by nickboldt** [comment]
Related task/doc is to document (with examples) how to use `--plugin-registry-url=plugin-registry-url` and `--devfile-registry-url=devfile-registry-url` inside airgap env.

**Comment by nickboldt** [comment]
Initial blog post:

http://divby0.blogspot.com/2019/07/deploying-che-7-with-custom-images.html

Also posted here:

https://github.com/redhat-developer/codeready-workspaces/blob/master/devdoc/building/che7-custom-resource-airgap.adoc

@l0rd @slemeur WDYT? 

@rkratky I can refactor this into a PR for che-docs, or you can take it as is and reskin it to your liking.

**Comment by benoitf** [comment]
Shouldn't it use operatorhub with openshift v4 / codeready containers instead of end-of-life minishift ?

**Comment by nickboldt** [comment]
Yes, I should also be testing with CRC/OSv4 but we will still be supporting minishift/OSv3.11 for the forseeable future so that's not going away any time soon. :) 

Also CRC in its alpha state doesn't have a windows flavour I can use yet, which makes it challenging. They plan to add support for Windows 10 with HyperV soon, and hopefully Virtualbox in October.

**Comment by nickboldt** [comment]
Also there's some followup work to be done here: https://github.com/eclipse/che/issues/14088

**Comment by nickboldt** [comment]
Depends on #14635 which changes the scope of what can be done in the cr.yaml file (adds more control).

**Comment by davidfestal** [comment]
We should document more than only how to override images.

- All fields of the `CheCluster` should be documented:
  - In the CRD YAML itelf (through automatic Go->OpenApi schema generation), so that the documentation of each field will be available automatically in the OpenShift 4.2 console.
  - In the Che 7 documentation, and refer to it from within Chectl documentation (where the `--che-operator-cr-yaml` is described).

**Comment by ibuziuk** [comment]
@rkratky I removed `osio` team from this issue since docs team can handle this one without our involvement. Feel free to ask for any details

**Comment by rkratky** [comment]
Fixed by https://github.com/eclipse/che-docs/pull/916
