### ISSUE TITLE
Mark not yet supported chectl commands as such in Readme documentation

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13899]
### Is your enhancement related to a problem? Please describe.

I read the documentation and found a command to "update", I was thinking that it is exactly what i'm searching for at this moment!
Unfortunately, I hit an error when trying it:
`"Warning: Not implemented yet"`

**Comment by benoitf** [comment]
I think it's working if you're using the distribution and not the single binary ?

**Comment by tsmaeder** [comment]
> if you're using the distribution 

what's the distribution? Also: why would that contain different capabilities than the binary?

**Comment by tsmaeder** [comment]
IMO, "not yet implemented" should not appear in a release. But not a critical issue.
