### ISSUE TITLE
Unable to delete worskpace from Organization workspaces list, workspace name is missed

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#13893]
### Reproduction Steps
1. Create an organization
2. Create a new workspace for this organization
3. Open Organization workspaces list(see screencast №1)

**Expected behavior:**
Created workspace exists is workspaces list and can be deleted

**Observed behavior:**
Workspace name in list is missed(see screencast 1) and there is ```Cannot read property 'environments' of undefined``` error in browser console when trying to delete it(see screencast 2).

**Screenshot:**
![Selection_237](https://user-images.githubusercontent.com/7760565/61452746-2770b680-a965-11e9-91ce-d7f513db7479.png)

**Screencast:**
screencast №1
![screencast-che-eclipse-che 10 33 177 143 nip io-2019 07 18-12_51_14](https://user-images.githubusercontent.com/7760565/61448704-0f486980-a95c-11e9-974b-0f709d56afaf.gif)

screencast №2
![screencast-che-eclipse-che 10 33 177 143 nip io-2019 07 18-12_52_16](https://user-images.githubusercontent.com/7760565/61448712-13748700-a95c-11e9-95a6-5da0e48e971f.gif)

**OS and version:**    
Che 7.0.0-RC-4.0-SNAPSHOT; Fedora 28; Chrome 75

**Comment by tsmaeder** [comment]
@SkorikSergey can you open and use the workspace?

**Comment by SkorikSergey** [comment]
> @SkorikSergey can you open and use the workspace?

Yes, workspace works as expected. This issue reproduces only on Organization worskpaces list.
