### ISSUE TITLE
Automate tests for LSP and DAP Support in Che

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13897]
### Is your enhancement related to a problem? Please describe.
Provide automation testing for the Language Servers and Debug Adapters we package with Che.

**Comment by tsmaeder** [comment]
@slemeur not sure what you expect here.

**Comment by slemeur** [comment]
Linking to: https://github.com/eclipse/che/issues/13892 as it's a good illustration of why we need automated tests

**Comment by tsmaeder** [comment]
@slemeur still not clear to me what you want here: tests for the language support plugins in che-plugin-registry? End-to-end?

**Comment by slemeur** [comment]
We are packaging LS and DAG inside of Che and in the plugin-registry. We are running them in a different fashion and have mechanisms in place to make them running. 

Let's say you have a LS that support 100% of the LSP and running without bugs:
- How do you ensure that, the LS capabilities are all working when the LS is running in the context of Che? 

How much of this can we get automated?

**Comment by slemeur** [comment]
And if you look at this issue: https://github.com/eclipse/che/issues/13892 it is exactly the type of issues we would like to catch. IE: LS works properly in VSCode but not in Che

**Comment by tsmaeder** [comment]
Actually, #13892 is broken in Theia, not Che.

**Comment by sunix** [comment]
To me the goal in the description is pretty clear. Catch issues that we could have with the integration of LSP/DAP in Che.... which is different from Theia. You could have many ways to run LSP or DAP in Theia depends on the product. Things may work on Gitpod but not in Che, etc ...

**Comment by sunix** [comment]
about  #13892, do we have the same issues in Gitpod ?

**Comment by gorkem** [comment]
@tsmaeder we can not continue to manually test the LS and DAP implementations that we ship manually. Let's think of a solution so that this is no longer taking developer time.

**Comment by tsmaeder** [comment]
What I 100% don't want is to do a series of UI tests for this: that was a disaster in Che 6 in that it never reliably forecast the quality of the software. We're going to investigate doing tests at the VS Code API level.

**Comment by gorkem** [comment]
Agreed, I was thinking that debugging with test projects and`launch.json` files should be possible without UI.
