### ISSUE TITLE
Default location for "git clone" should be /projects

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13894]
### Is your enhancement related to a problem? Please describe.
Everytime  user runs "Git: clone" command, he is prompted for location where to clone the project. The problem is, that the default location in this dialog is everytime $HOME (`/home/theia`), which is most probably not the location the user want's to clone the repo to.

### Describe the solution you'd like
Having `/projects/` as default location for the clone dialog would solve this problem.
I'm not sure if devfile could be configured in a way, where the default project location is different than `/projects/`, but if it is, theia should be clever enough to select that location as the default one.

**Comment by tsmaeder** [comment]
This kind of sucks, but in the end, it's an inconvenience. Also, we're expecting the users to add projects to their devfiles, right?
