### ISSUE TITLE
 [omnisharp-plugin] Format Document doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13907]
### Describe the bug

Format Document feature doesn't work in [omnisharp-plugin](https://github.com/redhat-developer/omnisharp-theia-plugin). After trying to format some document from the editor I see an info message in  the browser console:
<details>
<summary>Message</summary>

```
root INFO There is no document formatter for 'csharp'-files installed.
```
</details>

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
You can follow steps in the video: https://youtu.be/Zkm513MgBl8

**Comment by rhopp** [comment]
Triaging the issue the same as it's parent issue. If you think this issue should be triaged for Che 7 GA, speak up ;-)

**Comment by svor** [comment]
should be fixed by https://github.com/eclipse/che-plugin-registry/pull/199

**Comment by svor** [comment]
fixed by https://github.com/eclipse/che-plugin-registry/pull/199
