### ISSUE TITLE
[omnisharp-plugin] Markdowns are not displayed in the editor 

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13908]
### Describe the bug

Markdowns are not displayed in the editor for C# files.  And if move the cursor to the place where an icon should be I see next error in the browser console:
<details>
<summary>Exception</summary>

```
Uncaught Error: Cannot read property 'language' of null
TypeError: Cannot read property 'language' of null
    at e.asMarkdownString (vendors.795ac5958e7158cc3edd.js:1)
    at vendors.795ac5958e7158cc3edd.js:1
    at Array.map (<anonymous>)
    at e.asHoverContent (vendors.795ac5958e7158cc3edd.js:1)
    at e.asHover (vendors.795ac5958e7158cc3edd.js:1)
    at vendors.795ac5958e7158cc3edd.js:19
    at async Promise.all (/dashboard/index 0)
    at errors.ts:81
```
</details>

omnisharp plug-in, which provides the functionality of omnisharp language server is here https://github.com/redhat-developer/omnisharp-theia-plugin

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
You can follow steps in the video: https://youtu.be/Zkm513MgBl8

**Comment by rhopp** [comment]
Triaging the issue the same as it's parent issue. If you think this issue should be triaged for Che 7 GA, speak up ;-)

**Comment by slemeur** [comment]
@svor Can you precise what markdowns cannot be displayed and where ?
The issue is a bit obscur to me :)

**Comment by svor** [comment]
@slemeur for example QuickFixe icons:
![screenshot-localhost_3000-2019 08 06-16_55_42](https://user-images.githubusercontent.com/1271546/62546024-6eb6dc80-b86b-11e9-8bab-e99162ad1fbc.png)

**Comment by svor** [comment]
should be fixed by https://github.com/eclipse/che-plugin-registry/pull/199

**Comment by svor** [comment]
fixed by https://github.com/eclipse/che-plugin-registry/pull/199
