### ISSUE TITLE
Project-template API decommissioning

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13903]
### Is your task related to a problem? Please describe.
Based on the discussion here https://github.com/eclipse/che/issues/13792.
It turns out that we are no longer using this api anymore.  In general, the replacement of
the project-templates is the devfile registry, where templates come within devfile.

### Describe the solution you'd like
remove project -template api and template.json.

### Describe alternatives you've considered
none

**Comment by tsmaeder** [comment]
@skabashnyuk Could you explain why this needs to be in 7.0.0?

**Comment by skabashnyuk** [comment]
It can be removed any time after.
