### ISSUE TITLE
Remove all workspace-related command from Theia File menu

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#13909]
Theia File menu has items to open and close the workspace. But the workspace in Theia is something else that workspace in Che. In Theia it's a directory with projects.
Che works with predefined `/projects` directory which is never changed.
In that case it makes no sense to have Theia workspace related commands in file menu.
We can always load Theia and open `/projects` directory.

![workspace](https://user-images.githubusercontent.com/1655894/61466053-82aca400-a979-11e9-86d7-b0896400e0ba.png)

The solution could be to remove or hide Workspace* command from Theia File menu.
It will not confuse the user when dashboard sidebar is opened.

**Comment by rhopp** [comment]
+1 for removing "workspace" references from Theia.

**Comment by benoitf** [comment]
I think at F2F it was discussed that for example `close workspace` should be `stop workspace` instead

**Comment by rhopp** [comment]
@benoitf Couldn't we do this in two steps? For GA, just remove these entries and for some future release bring them back with reimplemented functionality?

**Comment by tsmaeder** [comment]
I'm doing this as part of changing to using projects workspace roots. See my message to che-dev 2 weeks ago. Propose to close this as a duplicate.

**Comment by l0rd** [comment]
@tsmaeder duplicate of #13427 ?

**Comment by akurinnoy** [comment]
@tsmaeder Hello, maybe you need some help getting rid of commands related to Theia workspaces?

**Comment by tsmaeder** [comment]
Duplicate of duplicate of #13427

**Comment by vitaliy-guliy** [comment]
@tsmaeder why did you close the issue? We still have a duplicate in the Theia File menu that has a different meaning.

**Comment by tsmaeder** [comment]
Because this will be fixed when we move to a workspace root-based system as a fix for #13427, so this is a duplicate.
