### ISSUE TITLE
Workspaces created from dashboard (devfile) do not respect clonePath

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13902]
# Describe the bug
Currently, devfile for GO available from devfile registry has clonePath defined (to clone under `$GOPATH/src/github.com/golang/example`) - https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/go/devfile.yaml#L11. This is required for proper functioning of the example (and default tasks).

Creating workspace from this devfile using API results in correct workspace (project is cloned under `/projects/src/github.com/golang/example/`:
![image](https://user-images.githubusercontent.com/1215011/61457572-e11d5680-a968-11e9-8266-86fa17800e43.png)

Creating workspace from the same devfile, using Dashboard results in the repo being cloned directly into `/project/example`:
![image](https://user-images.githubusercontent.com/1215011/61457824-702a6e80-a969-11e9-9a7d-db864fa7ccd6.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Have che started & pointing to latest devfile registry
2. Create workspace from Go stack (devfile). Default example should be pre-selected
3. Start workspace
4. EXPECT: Project is cloned in `/projects/src/github.com/golang/example/`, as defined in the devfile
5. FAIL: Project is cloned in `/projects/example/`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by tsmaeder** [comment]
Marking 7.0 examples are supposed to work.

**Comment by sunix** [comment]
created workspace from dashboard, how does the devfile finally looks like (in `workspaces` section > `<your workspace>` > `Devfile` tab)   looks like ?

**Comment by ashumilova** [comment]
it's missing, so it's the problem of workspace creation. Theia processes the clonePath well.
