### ISSUE TITLE
[multiuser] Signup with thin scopes for GitHub.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13916]
### Is your enhancement related to a problem? Please describe.

Currently, user must accept to give scopes `repo,user,write:public_key` to Che.
IMO, this is too strong (or risky) for entry users who don't use full functions.

### Describe the solution you'd like

The bast is to enable no scope on their signup/login. (`read:user`, `read:email` may be safe.)

And Che asks adding more scope permission to the user logged in when it was required.

I guess it can be implemented by calling `add_scopes` via `PATCH /authorizations/:authorization_id` provided by GitHub API.

**Comment by skabashnyuk** [comment]
@monaka do you know what kind of auth/authorization is required to call ```PATCH /authorizations/:authorization_id``` ?

**Comment by monaka** [comment]
@skabashnyuk I checked [the official document](You can only access this API via Basic Authentication using your username and password, not tokens.) and ...

> You can only access this API via Basic Authentication using your username and password, not tokens.

Hmm, my approach won't fit to Che.
But I believe there will be the another way because GitPod did.
After I approved more scopes, GitHub send me the mail like this.

![Screenshot 2019-07-19 at 15 19 51](https://user-images.githubusercontent.com/101795/61513682-e0ec8c00-aa38-11e9-873b-85edbcef93cd.png)

**Comment by monaka** [comment]
I inspected Gitpod in shallow. It looks just calling `https://github.com/login/oauth/authorize` with newly required scopes, `redirect_url`, and some more parameters.

**Comment by rhopp** [comment]
@skabashnyuk Do you think we should trigger something like this for GA? To me it seems like nice enhancement, but I'm not sure we add another enhancement into GA.
Maring this one as sev2 & Che 7.1 milestone for now.

**Comment by skabashnyuk** [comment]
> Do you think we should trigger something like this for GA

No, because we need to figure out if that possible at all. I mean manipulation of token scopes on Kyecloak side.

**Comment by monaka** [comment]
I agree. It's enough to be realized on 7.1.0 or later.

**Comment by slemeur** [comment]
Downgrading the priority. This is a very good enhancement request which will need to get prioritized - but regarding the other areas that needs hardening, this seems lower right now.
