### ISSUE TITLE
Keycloak uses H2 database in Che on Helm Kubernetes deployment

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#13919]
### Describe the bug
Currently Multiuser Che, deployed via Helm charts, will be using H2 database, and ignore the database configuration provided in the chart (which should make it to use PostgreSQL DB). 
We should look into our entrypoint to see the fix for that
https://github.com/eclipse/che/blob/331a63cd06be6df3501118e6150c42e0de85db82/dockerfiles/keycloak/kc_realm_user.sh#L39
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Deploy Che through Helm charts (manually, or through chectl using `--installer=helm`)
2. Check startup logs on Keycloak pod, as it should give notes that it's using Postgres DB, Drivers, etc.

### Expected behavior
Keycloak uses PostgreSQL database 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
Issues and PRs hinting to this problem: 
https://github.com/eclipse/che/pull/13791
https://github.com/eclipse/che/issues/13821

**Comment by mkuznyetsov** [comment]
CC @monaka @l0rd

**Comment by skabashnyuk** [comment]
@l0rd @slemeur since this issue was already met by Che users and since it's quite hard to migrate h2 to postgresql database afterwise. I think it makes sense to include this task in 7.0 release plan.  wdyt?

**Comment by l0rd** [comment]
@skabashnyuk +1

**Comment by monaka** [comment]
For new users, this issue will be fixed by the part of PR #11761 (un-merged).
(I didn't notice as I applied #11761 equivalent to my environment and am running Che with Postgres)

And as @skabashnyuk said, the migration way will be required by current users.

**Comment by monaka** [comment]
I added the patch from #11761 into PR #13791.

**Comment by mkuznyetsov** [comment]
PR merged, so PostgreSQL DB should be used from now on in Helm.

In case somebody would need to perform a migration from existing H2 DB to Postgres, there is a guide:
https://gist.github.com/mkuznyetsov/457567a1bdaad0b843e088ba0b664ea5
