### ISSUE TITLE
che-theia/contributing.md does not explain branches

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13918]
Contributing.md does no explain how to work with branches, for example, do I have to put my branch into https://github.com/eclipse/che-theia/blob/master/che-theia-init-sources.yml?

**Comment by rhopp** [comment]
Agree having dev process not documented properly is big bummer, but this is not blocking Che 7 GA release.

**Comment by l0rd** [comment]
@evidolob @benoitf @sunix it looks like that, to do a build of che-theia PR check we need to:

1. checkout the branch locally
2. change the value of `checkoutTo` with the name of the PR branch
3. commit the change in 2 and push it to the remote repo

This looks weird? Do you confirm?

**Comment by benoitf** [comment]
@l0rd there is a pending PR https://github.com/ws-skeleton/che-theia-generator/pull/26

**Comment by benoitf** [comment]
and related issue is https://github.com/eclipse/che/issues/13738

**Comment by evidolob** [comment]
Closing, as now there are no need to change anything to build che-theia images with your changes

**Comment by sunix** [comment]
We still need to adapt the devfile to use that mechanism
