### ISSUE TITLE
[Keycloak] The body of the email-verification was broken.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13917]
### Describe the bug

The body of the mail from Keycloak was broken.

### Che version

 - [x] nightly

### Steps to reproduce

0. Registrer your account on Keycloak.
0. Read the confirmation mail from Keycloak.
0. You'll got a broken HTML mail. 

### Expected behavior

A valid HTML mail arrival.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-21T13:09:06Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots

![Screenshot 2019-07-19 at 14 35 44](https://user-images.githubusercontent.com/101795/61511704-87815e80-aa32-11e9-9c17-7e1136242098.png)

![Screenshot 2019-07-19 at 14 38 18](https://user-images.githubusercontent.com/101795/61511804-e34be780-aa32-11e9-9236-695dbad8aee4.png)

### Installation method
   - [x] ~~I don't know~~ Customized Helm Charts

### Environment
   - [x] my computer 
       - [x] ~~Linux~~ ChromeOS
   - [x] Cloud
       - [x] Azure

### Additional context

Looks HTML content was escaped by `msg()` in FTL template.

**Comment by monaka** [comment]
The similar issue to https://github.com/keycloak/keycloak/pull/4988 ?

**Comment by rhopp** [comment]
@monaka Do you think this bug is important enought to be prioritized into Che 7 GA release?
cc @slemeur

**Comment by monaka** [comment]
The viewpoint of functionality, this is not critical. Users who want to registration can click the link (or at least can copy/paste it to their web browser). 

IMO, it's not blocker and just better to apply if someone could make patches before Che 7 GA release.

**Comment by slemeur** [comment]
I think this should be landing in 7.1.0 cc @l0rd

**Comment by skabashnyuk** [comment]
We can handle that.

**Comment by slemeur** [comment]
Thank you @skabashnyuk . You can handle it for 7.0?

**Comment by rhopp** [comment]
I've just had instance running, so I tried this. Indeed adding `?no_esc` to few places solves this issue (I've tried that on running instance changing this inside container, thus no PR).

**Comment by skabashnyuk** [comment]
>Thank you @skabashnyuk . You can handle it for 7.0?

I think we can.
