### ISSUE TITLE
[omnisharp-plugin] Code lenses with references are not clickable

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13910]
### Describe the bug

The number of references are displayed as code lenses in the editor but they are not clickable.  `Find All References` feature works fine. 

The issue is about [omnisharp plug-in]( https://github.com/redhat-developer/omnisharp-theia-plugin ), which provides the functionality of omnisharp language server. 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

You can follow steps in the video: https://youtu.be/Zkm513MgBl8

**Comment by rhopp** [comment]
Triaging the issue the same as it's parent issue. If you think this issue should be triaged for Che 7 GA, speak up ;-)

**Comment by svor** [comment]
should be fixed by https://github.com/eclipse/che-plugin-registry/pull/199

**Comment by svor** [comment]
fixed by https://github.com/eclipse/che-plugin-registry/pull/199
