### ISSUE TITLE
Move to assemblies of che-ctl instead of single-binary

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13911]
### Is your task related to a problem? Please describe.
chectl was distributed at first with a single binary.
for self-update mechanism, oclif framework is providing the feature on top of 'oclif assemblies'

These assemblies are now distributed in release section of chectl.

The single binary distribution of chectl should be removed and only the 'oclif packaging' should be distributed as it provides the self-update/update command

### Describe the solution you'd like
Ensure that these new assemblies are working on all operating system and remove the generation of single binaries from release page.

### Describe alternatives you've considered
none

**Comment by rhopp** [comment]
Is this about https://oclif.io/docs/releasing.html#autoupdater? This does seem like nice feature, but I would vote for postponing this post GA.

**Comment by benoitf** [comment]
yes it is (in fact the assemblies are there since one month) and update site as well

**Comment by slemeur** [comment]
@benoitf : As you are currently working on this and expecting it for 7.0, I'm applying the 7.0 milestone

**Comment by benoitf** [comment]
ok

**Comment by benoitf** [comment]
done
