### ISSUE TITLE
plugin panel: Plugin view shouldn't show all the version of the plugin

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13913]
### Is your enhancement related to a problem? Please describe.
The plugin panel displays too many items and user usually will not be interested to install a old version of a plugin so why showing them ?

In the bellow example, we are showing 3 version of che-omnisharp-plugin ... user would never know the difference between all of them and would just take latest.

![Selection_345](https://user-images.githubusercontent.com/650571/61472957-bee60180-a985-11e9-960d-69124ca822f6.png)

### Describe the solution you'd like
- Display 1 item in the list per plugin.
- The install button should have a additional arrow drop down button to propose other installation options
- The default installation version should be `latest`

**Comment by rhopp** [comment]
Do we really need multiple versions of plugins? If those plugins provide different functionality, we could separate them (as it is right now with java... we have plugins for different versions of java for example).
WDYT about this issue @slemeur @l0rd ?

**Comment by slemeur** [comment]
It needs to be consistent with https://github.com/eclipse/che/pull/13942
