### ISSUE TITLE
Dashboard doesn't respect referenceContent attribute

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#13925]
### Describe the bug
Dashboard removes `referenceContent` attribute of the commands.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create any workspace
2. Select `Devfile` tab in workspace configuration
3. Try to add a command that contains `referenceContent`
```
  -
    name: debug
    actions:
    - type: vscode-launch
      referenceContent: >
        {
        "version": "0.2.0",
        "configurations": [
          {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "0.0.0.0",
            "pathMappings": [
              {
                  "localRoot": "${workspaceFolder}",
                  "remoteRoot": "${workspaceFolder}"
              }
            ]
          }]
        }
```
4. Once workspace is updated `referenceContent` disappears:
```
    name: debug
    actions:
    - type: vscode-launch
``` 

### Expected behavior
Dashboard shouldn't remove `referenceContent` from the command.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2019-07-19 14-31-44](https://user-images.githubusercontent.com/1640675/61532252-f5795600-aa31-11e9-9c91-2bdba54d0dde.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
What is "referenceContent" used for?

**Comment by tolusha** [comment]
It allows to specify launch configuration
https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html#editor-specific-commands

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/13957.
@tolusha feel free to reopen if it still actual for you.
