### ISSUE TITLE
Create Jenkins job to automate installation Che by using OperatorHub UI on OCP 4.x

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#13929]
### Description
_Create the Jenkins job to automate and checking installation Eclipse Che by using the OperatorHub UI on OCP 4.x_

The related known iisue: https://github.com/eclipse/che/issues/13878
The related job: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Eclipse-Che7-install-by-operatorhub/

**Environment of install Che:** OCP 4.x | by OperatorHub UI

**Comment by rhopp** [comment]
How does this differ form https://github.com/eclipse/che/issues/13878?

**Comment by artaleks9** [comment]
The https://github.com/eclipse/che/issues/13878 is  about e2e test which covers the installation Eclipse Che from OperatorHub UI on OCP 4.x.. And this issue about the job on Jenkins which performs and checks this and includes this e2e test as part of process.
