### ISSUE TITLE
[che-operator] missing argument in build_deploy_local.sh

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13920]
### Is your enhancement related to a problem? Please describe.
Executing `build_deploy_local.sh` result in errors like namespace `''` not found
it's because this script is expecting a parameter but there is no check on that parameter (if given or not) and there is no default

### Describe the solution you'd like
Report error if parameter is missing or assume a default value
Also if we provide a namespace that is not yet existing, it fails, probably script could create it.

### Describe alternatives you've considered
none

**Comment by rhopp** [comment]
As this is about local dev script and it shouldn't affect Che7, I'm setting milestone 7.1.

**Comment by ibuziuk** [comment]
Moving to 7.x

**Comment by tolusha** [comment]
The missing parameter check has been added  since then.
