### ISSUE TITLE
Upgrade VS Code Camel plugin in registry to version 0.0.16

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13921]
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-apache-camel

the publisher has changed from camel-tooling to redhat, and so the id.

so I guess https://github.com/eclipse/che-plugin-registry/blame/master/README.md#L78-L80 needs to be used

```
deprecate:             # optional; section for deprecating plugins in favor of others
  autoMigrate:         # boolean
  migrateTo:           # new plugin id
```

**Comment by rhopp** [comment]
@apupier Is there any functionality change? Will the original plugin (published by camel-tooling) disappear? I'm trying to understand if we need change before Che 7 GA or not.

**Comment by apupier** [comment]
> @apupier Is there any functionality change? Will the original plugin (published by camel-tooling) disappear? I'm trying to understand if we need change before Che 7 GA or not.

missed this comment, sorry.

There are little improvements https://marketplace.visualstudio.com/items/redhat.vscode-apache-camel/changelog

it is not mandatory for GA (I would say as there is a publisher update, it might even be better to wait after GA to have time to check correctly everything)

the original published by camel-tooling has been migrated. VS Code marketplace is redirecting all requests automatically
