### ISSUE TITLE
Potential security vulnerabilities in Dashboard and Workspace-loader

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#13924]
Github alerts for security issues in some of dependencies in Dashboard and Workspace-loader. We need to bump up versions of those dependencies.

Recommendations:

- Upgrade handlebars to version 4.0.14 or later (high severity)
- Upgrade lodash to version 4.17.13 or later (high severity)
- Upgrade angular to version 1.6.0 or later (moderate severity)

**Comment by akurinnoy** [comment]
@l0rd @slemeur  

Angular 1.6.x brings a breaking change which affects Dashboard. 
Changes in bindings initialization mechanism break lots of directives and 82 unit tests as well.

Maybe, milestone should be revised for this issue?

**Comment by l0rd** [comment]
@akurinnoy setting to `7.1.0` cc @nickboldt
