### ISSUE TITLE
Replace devfile editor with monaco and YAML LSP

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#13939]
When editing a devfile on the dashboard there is not content assist. 
### Describe the solution you'd like
Use the monaco editor with embedded YAML LSP instead of current editor and provide the JSON Schema for devfiles to provide content assist. See [this example](https://github.com/gorkem/yaml-server-browser-example).

/cc @JPinkney

**Comment by tsmaeder** [comment]
@JPinkney has worked on something similar for the OpenShift console. I'm sure he can provide guidance, at least.
