### ISSUE TITLE
[operator] nightly version of che-operator should use nightly for other components as default

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13931]
### Is your enhancement related to a problem? Please describe.
When using `eclipse/che-operator:nightly` image, it's deploying che by using right now eclipse/che-server 7.0.0-RC2.0

### Describe the solution you'd like
I would say that using `che-operator:7.0.0-RC2.0` deploys as default che 7.0.0-RC2.0 but `eclipse/che-operator:nightly` should deploy `che-server`, `che-keycloak`, `che-postgres`, `che-devfile-registry`, `che-plugin-registry`, etc with their nightly version
so it's easy to have the latest changes on all components at once

### Describe alternatives you've considered
none

**Comment by l0rd** [comment]
That should be fixed by https://github.com/eclipse/che-operator/pull/53 as well.
