### ISSUE TITLE
Che sync failing with fatal error

### ISSUE THREAD

**Issue by dmg3** [eclipse-che/che#13937]
## Summary
The Che sync command is failing with message "Fatal error occurred".  The last thing it says before the failure is "read: Connection reset by peer"
## Relevant information
I'm running Ubuntu 14.04 LTS on Virtual box
Che 6.19.0
Docker version 18.06.1-ce, build e68fc7a
The workspace I'm using is the Java default stack with SSH installer enabled

Che server start command:
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/workspace/che:/data eclipse/che:6.19.0 start`

Sync command which fails:
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/asg/chedata:/data -v /home/asg/chetest:/sync  eclipse/che:6.19.0 sync wksp-taro`

Output:

    asg@asg-VirtualBox:~$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v 
    /home/asg/chedata:/data -v /home/asg/chetest:/sync  eclipse/che:6.19.0 sync wksp-taro
    WARNING: No swap limit support
    INFO: (che cli): 6.19.0 - using docker 18.06.1-ce / native
    WARN: Newer version 'rc' available
    INFO: (che mount): Starting sync process to /home/asg/chetest
    mkdir: can't create directory '/root/.ssh': File exists
    INFO: INFO: (che mount): Mounting root@/10.0.2.15:/projects with SSHFS
    read: Connection reset by peer
    ---------------------------------------
    !!!
    !!! ERROR: Fatal error occurred (1)
    !!!
    ---------------------------------------

List workspaces output shows the workspace is running:

    asg@asg-VirtualBox:~$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v 
    /home/asg/chedata:/data -v /home/asg/chetest:/sync  eclipse/che:6.19.0 action list- 
    workspaces
    WARNING: No swap limit support
    INFO: (che cli): 6.19.0 - using docker 18.06.1-ce / native
    WARN: Newer version 'rc' available
    NAME       ID                         STATUS   
    wksp-taro  workspacekpqh53a43i043j4r  RUNNING 

Also, I have SSH enabled for the machine;  as a control, if I disable it, the output from sync complains that the workspace needs to have SSH enabled, e.g., 

    asg@asg-VirtualBox:~$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v 
    /home/asg/chedata:/data -v /home/asg/chetest:/sync  eclipse/che:6.19.0 sync wksp-taro
    WARNING: No swap limit support
    INFO: (che cli): 6.19.0 - using docker 18.06.1-ce / native
    WARN: Newer version 'rc' available
    INFO: (che mount): Starting sync process to /home/asg/chetest
    The SSH agent (org.eclipse.che.ssh) has been disabled for this workspace.
    ---------------------------------------
    !!!
    !!! ERROR: Error when trying to get workspace data for workspace named wksp-taro
    !!!
    ---------------------------------------
    List of workspaces are:
    NAME       ID                         STATUS   
    wksp-taro  workspacekpqh53a43i043j4r  RUNNING  

If I run curl against the workspace container and its' ssh port I get the following output:

    asg@asg-VirtualBox:~$ curl 10.0.2.15:32858
    SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
    Protocol mismatch.
    curl: (56) Recv failure: Connection reset by peer

Any ideas or thoughts on what i'm doing wrong?

**Comment by l0rd** [comment]
@benoitf any idea of what's going wrong here? @dmg3 is using v6.19 and the CLI should still be working there right?

@dmg3 we are releasing a new version of Che and dropping the CLI and Docker support. We may implement something similar to che sync in the future but I am afraid we are not going to fix `che sync` for version 6.19.

**Comment by dmg3** [comment]
> @benoitf any idea of what's going wrong here? @dmg3 is using v6.19 and the CLI should still be working there right?
> 
> @dmg3 we are releasing a new version of Che and dropping the CLI and Docker support. We may implement something similar to che sync in the future but I am afraid we are not going to fix `che sync` for version 6.19.

Ok, makes sense, thanks for the info!

**Comment by davidwindell** [comment]
@l0rd could you clarify something quickly for me, there is currently no way to SSH in to a workspace on Che 7 remotely?

**Comment by l0rd** [comment]
@davidwindell the following documentation sections explains how you can access to a remote Che 7 workspace from your command line https://www.eclipse.org/che/docs/che-7/remotely-accessing-che-workspaces/

**Comment by davidwindell** [comment]
Thanks, we have relied up till now on having the SSH agent as that meant we could use Unison (which che sync also used) to sync workspaces files to the local IDE. I doubt that would work with kubectl
