### ISSUE TITLE
Chectl add new platform - CodeReady Containers

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13940]
### Is your enhancement related to a problem? Please describe.
I want to use ```chectl``` with CodeReady Containers to run Che on OpenShift 4.x locally

### Describe the solution you'd like
value  ```crc``` for ```platform``` paramter.

### Describe alternatives you've considered
```
16:46:23]skabashn:darwin-amd64[master]#: chectl server:start --installer=operator --platform=minishift
  ❯ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✖ Verify if minishift is running
      → E_PLATFORM_NOT_READY
      Retrieving minishift IP and domain for routes URLs
 ›   Error: E_PLATFORM_NOT_READY
[16:47:07]skabashn:darwin-amd64[master]#: chectl server:start --installer=operator --platform=openshift
  ❯ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
    ✖ Verify domain is set
      → E_MISSING_ARGUMENT: the domain parameter needs to be defined.
 ›   Error: E_MISSING_ARGUMENT: the domain parameter needs to be defined.
```
### Additional context
```
 crc version
version: 0.88.0-alpha-4.1.3+6a9f758
```

**Comment by benoitf** [comment]
@skabashnyuk do you have given the parameter `--domain=yourdomain.com` for openshift installation as specified in the error ?

**Comment by skabashnyuk** [comment]
@benoitf no. I expect that it will ask me the same things as it asking for minishift. Do you think it should be different?

**Comment by benoitf** [comment]
@skabashnyuk yes on minishift there is `$ minishift ip` command but on OpenShift instances there is no such tool/command.

`minikube` and `minikube` have these kind of helpers that `oc` or `kubectl` haven't

**Comment by skabashnyuk** [comment]
Ok. So what should I put in ```--domain=yourdomain.com``` parameter?

**Comment by benoitf** [comment]
@skabashnyuk it depends on kubernetes/openshift installation. It's how you can reach it


here an extract of the remote che doc:
```
A domain needs to be given to chectl, it’s the remote hostname that will be accessible. If it’s unknown, let’s grab it with a new project

$ oc new-project hello-world
$ oc new-app centos/httpd-24-centos7~https://github.com/openshift/httpd-ex
$ oc expose svc/httpd-ex
$ oc get route httpd-ex
NAME       HOST/PORT                                                  PATH      SERVICES   PORT       TERMINATION   WILDCARD
httpd-ex   httpd-ex-hello-world.apps.rhpds311.openshift.opentlc.com             httpd-ex   8080-tcp                 None

Domain can be extracted from httpd-ex-hello-world.apps.rhpds311.openshift.opentlc.com, it’s the right part after the first name: apps.rhpds311.openshift.opentlc.com

Now the project can be safely removed
$ oc delete project hello-world
```

**Comment by skabashnyuk** [comment]
@benoitf `crc` has the same ```ip``` commands as `minishift` have.

```
[ 8:35:20]skabashn:~#: minishift ip
192.168.64.17
[ 8:35:25]skabashn:~#: crc ip
192.168.64.16
```
WDYT can we reuse it to not to ask user additional questions and provide better UX?

**Comment by benoitf** [comment]
yes, I was only saying that you can use for now `openshift`as workaround for now and then provides 192.168.64.16.nip.io with `domain` flag.

**Comment by skabashnyuk** [comment]
will try.

**Comment by benoitf** [comment]
@skabashnyuk BTW AFAIK `crc` is only available within Red Hat (the system bundle is not yet public)

**Comment by skabashnyuk** [comment]
That is temporary I guess.
