### ISSUE TITLE
[helm] deployment url of che

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13941]
### Is your enhancement related to a problem? Please describe.
When I deploy che using helm, it's using multi-host server strategy, but at the end I have URL with
`https://che-che.my-domain.com`

### Describe the solution you'd like
I would expect to have che deployed by default without this double `che-che` but more like
`https://che.my-domain.com`

**Comment by l0rd** [comment]
@skabashnyuk why is that P1? What are the impact for users? And is that related somehow with https://github.com/eclipse/che/pull/13946?

**Comment by sleshchenko** [comment]
Also, it makes sense to improve URLs of plugin and devfile registries
![Screenshot_20190722_155617](https://user-images.githubusercontent.com/5887312/61692686-c5ce9480-ad36-11e9-854c-e0dec7a82393.png)

**Comment by skabashnyuk** [comment]
>@skabashnyuk why is that P1? What are the impact for users? And is that related somehow with #13946?

Better to ask @benoitf .

**Comment by benoitf** [comment]
Hello, it's a nice to have but I can live with ugly/not user-friendly URLs
I agree with @sleshchenko 
Maybe more P2 but it looks like it can be an easy fix
