### ISSUE TITLE
Add a chectl server:start flag to specify if using external registries

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13949]
### Describe the solution you'd like

Currently a user cannot specify external registries when starting Che using chectl. This issue is to address that.

Related to `Che registries (plugin+devfile) should be part of Che deployment` #13557

**Comment by benoitf** [comment]
https://github.com/che-incubator/chectl/pull/228 ?

**Comment by davidfestal** [comment]
Currently, if you specify the `--plugin-registry-url` or `--devfile-registry-url` parameters, then the corresponding registry will not be deployed.
What is still missing is the ability to drive the non-deployment of registries with a *distinct* parameter (something like a boolean `externalDevfileRegistry`)
@l0rd do you confirm ?
