### ISSUE TITLE
Tutorial: How to setup multiuser Eclipse Che with TLS enabled on GCP  running on K8s 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13952]
### Is your task related to a problem? Please describe.
Follow up of https://github.com/eclipse/che/issues/13869#issuecomment-513751078 (comment)
It would be nice to write a tutorial ( similar to this https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-lemp-nginx-mariadb-and-php-on-debian-10
for example) that describes how to set up multiuser Eclipse Che with TLS enabled on GCP

**Comment by benoitf** [comment]
isn't it the goal of https://docs.google.com/document/d/1BAnjIZgBLjkUu_7RG9EgSDMQ1MbzWRbC0yVqfU18IcM/edit ?

**Comment by skabashnyuk** [comment]
@benoitf good question. I don't know.

**Comment by l0rd** [comment]
@benoitf @skabashnyuk if you don't mind I would close this issue as duplicate since we have already the item in the endgame (doc section).

**Comment by skabashnyuk** [comment]
Ok

пн, 22 лип. 2019, 19:52 користувач Mario Loriedo <notifications@github.com>
пише:
