### ISSUE TITLE
CHE 7 workspaces are disappeared after filtering

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#13950]
### Describe the bug

There is an empty workspace list after any trying with CHE 7 workspace filtering.
### Che version

7.0.0-rc-4.0-SNAPSHOT

### Steps to reproduce
1. Create several CHE7  workspaces.
2. Open " workspaces"
3. Try "search"

https://youtu.be/fERyEEk5dD8

### Screenshots

![Screenshot from 2019-07-22 16-01-58](https://user-images.githubusercontent.com/6310786/61634837-e6491100-ac9a-11e9-87ee-96bdd929acc3.png)
### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: localhost

**Comment by sleshchenko** [comment]
can't reproduce. @olexii4 Feel free to reopen if you still can reproduce it.
