### ISSUE TITLE
All UD searches are using only one column for filtering

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#13958]
### Is your enhancement related to a problem? Please describe.

All UD searches are using only one column for filtering. It is not obvious for the user.  
```
https://github.com/eclipse/che/blob/master/dashboard/src/app/workspaces/list-workspaces/list-workspaces.controller.ts#L102
https://github.com/eclipse/che/blob/master/dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.controller.ts#L108
https://github.com/eclipse/che/blob/master/dashboard/src/app/factories/list-factories/list-factories.controller.ts#L92
https://github.com/eclipse/che/blob/master/dashboard/src/app/admin/user-management/user-management.controller.ts#L109
...
```

### Describe the solution you'd like

It will be more comfortable to have several important or all columns for filtering.

**Comment by sunix** [comment]
1. Let's use the word `filtering` rather than `searching`
2. I don't think it is confusing ... but filtering through all the columns would be better
