### ISSUE TITLE
Need to release registries (devfile + plugin) automatically via dedicated centos ci job

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13953]
The idea is to have a dedicated release branch in registries (devfile + plugin)  and setup CI so that after pushing to this branch image with the correct tag e.g. `7.0.0-rc-4.0` would be pushed to the dedicated repository of the https://quay.io/organization/eclipse

The release branch could contain a  `VERSION` / `RELEASE` file which would contain a dedicated version of the registry which would be used for tagging during CI / CD

**Comment by ibuziuk** [comment]
@l0rd I have not added processing of the `latest` tag as part of this issue since currently, it is not clear what exactly the `latest` is. Basically, if we have `7.1.0` and bug fix `7.0.1` which one should be treated as latest? (I suppose we could technically tag only major releases as `latest` while bug-fix releases would be only version tagged).

**Comment by l0rd** [comment]
I would say that in your example latest is `7.1.0`. But a patch release may be `latest` as well. For instance if we release a `7.1.1` (before releasing `7.2.0`) we should tag it as latest.

Anyway since this looks like a complicated problem I would take care of it in a second step after Che 7 GA: we can add the tag manually for the time being.

**Comment by ibuziuk** [comment]
@l0rd ok, sounds good. Just to clarify - we are putting on hold only the `latest` tag processing but the release / tag process e.g. `7.0.0-rc-4.0` via CI should be automated for Che 7 GA. Or the whole issue could be postponed and we are ok with the manual tagging for the time being?

**Comment by l0rd** [comment]
We should create a job to release / tag and putting on hold tagging as `latest` (something that can be done manually)

**Comment by ibuziuk** [comment]
@l0rd sent a PR with a simple mechanism to automatically release devfile registry using the existing 'build-master' CI

**Comment by l0rd** [comment]
@ibuziuk @vparfonov we should do that for plugin registry as well

**Comment by ibuziuk** [comment]
sure, in my TODO list, but plugin registry automatic release process is planned to be done after the RC 4 since we still need some time to automate it

**Comment by l0rd** [comment]
Well yes I was hoping that we could semi-automate the release for plugin registry because that's identical to the devfile registry. But we can wait for it

**Comment by ibuziuk** [comment]
devfile regitry `7.0.0-rc-4.0` has been released via the new automatic CI CD process:
- https://ci.centos.org/job/devtools-che-devfile-registry-release/5/
- https://quay.io/repository/eclipse/che-devfile-registry?tab=tags
- arbitary-user-patched  images were also release e.g. https://quay.io/repository/eclipse/che-java11-maven?tab=tags

**Comment by l0rd** [comment]
plugin registry has it's own CI CD release process as well:

- [cico job](https://ci.centos.org/job/devtools-che-plugin-registry-release/)
- [`7.0.0-rc-4.0` image build automatically](https://quay.io/repository/eclipse/che-plugin-registry/manifest/sha256:66e2d9d86bd161b83929a44076dbf3b74b2c0523c561da4a3204581f3900094d)

closing the issue
