### ISSUE TITLE
Tutorial: How to setup multiuser Eclipse Che with TLS enabled on AWS running on K8s

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13954]
### Is your task related to a problem? Please describe.

It would be nice to write a tutorial ( similar to this https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-lemp-nginx-mariadb-and-php-on-debian-10
for example) that describes how to set up multiuser Eclipse Che with TLS enabled on AWS running on K8s

### Additional context
https://github.com/eclipse/che/issues/13952

**Comment by benoitf** [comment]
https://docs.google.com/document/d/1BAnjIZgBLjkUu_7RG9EgSDMQ1MbzWRbC0yVqfU18IcM/edit#heading=h.6kx51b7l0tjm ?
