### ISSUE TITLE
Allow multiple devfile registries to be added to che

### ISSUE THREAD

**Issue by tobespc** [eclipse-che/che#13961]
### Is your enhancement related to a problem? Please describe.
At the moment, the dashboard references a single location from where it gets it devfiles from.  In our case, we would like to add additional devfile registries so that we can can deploy che with the blessed set and also our additional set.

### Describe the solution you'd like
In che.properties, the current implementation sets 

```
che.workspace.devfile_registry_url=https://che-devfile-registry.openshift.io/
```
This could be enhanced to take multiple urls which would then be processed in devfile-registry.factory.js when fetching the devfile

### Describe alternatives you've considered
Another option could be having the existing https://che-devfile-registry.openshift.io/ pull in other repositories but this would be clumsy imo and hard to maintain

**Comment by tobespc** [comment]
This is something my team is working on and, providing you agree with the enhancement, will put a PR asap with a solution

**Comment by nickboldt** [comment]
FYI @slemeur @l0rd this is the contribution from IBM we talked about a couple weeks ago. PR coming soon! Setting fixversion of 7.1 for now but if you feel this is urgent for 7.0, feel free to change. 

cc: @rhopp @tsmaeder re: triage.

**Comment by slemeur** [comment]
@skabashnyuk : Please check the PR as soon as 7.0 is released

**Comment by skabashnyuk** [comment]
@slemeur pr looks ok for me. However, since changes are only on the dashboard side it's better that is someone familiar with it can approve it.

**Comment by slemeur** [comment]
@evidolob + @benoitf : Could you please review?

**Comment by nickboldt** [comment]
seems the above pr was replaced by https://github.com/appsody/stacks/pull/163 which is merged but not sure if we're done here.
