### ISSUE TITLE
Fix samples endpoint issues

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13964]
### Is your enhancement related to a problem? Please describe

For some of the samples projects in the devfile registry, the preview URL proposed by Theia port plugin is not the correct application URL. Even if the workspace sample starts properly users won't be able to open the application in the preview panel. That's definitely a bad UX.

### Describe the solution you'd like

The short term solution is to:
-  [ ] identify the samples that have this problem
-  [ ] fix the samples (and fork them if needed)

The long term solution is to add a new previewURL attribute to the devfiles commands https://github.com/eclipse/che/issues/13945

**Comment by ibuziuk** [comment]
@l0rd if you do not mind I will put this issue to the End Game Plan as a subtask for `Need to make sure that all devfiles from registry work on che.openshift.io`

**Comment by l0rd** [comment]
@ibuziuk of course that's perfect. 

One thing though: this can also be a multi-team effort as it has been the case for https://github.com/eclipse/che/issues/13529#issuecomment-501746114. You coordinate that but others teams can help as well. I think it worked pretty well for #13529

**Comment by amisevsk** [comment]
From what I've seen, the current endpoint issues are:

- NodeJS + Mongo is a backend app, hard to interact with in browser: https://github.com/eclipse/che/issues/14009
    - e.g. navigating to `/api/user` requires an authorization token
- PHP-MySQL: Application serves app at `/crud-php/public`, opening the endpoint (to `/`) gives just a directory structure
- PHP Simple: Same as above; opens to "Index of `/`" page. Need to navigate to `/php-web-simple` to get actual app.

**Comment by amisevsk** [comment]
I've opened PR https://github.com/eclipse/che-devfile-registry/pull/77 to work around the php devfile issues. The NodeJS + Mongo devfile is (I think) just a bad sample application; it's hard to interact with a REST backend from the browser.

**Comment by ibuziuk** [comment]
@slemeur @l0rd, in general, I believe we need to reconsider the samples we are using and get rid of / deprecate https://github.com/che-samples . IMO we should use vendor samples for all the devfiles like https://github.com/spring-projects/spring-petclinic

**Comment by ibuziuk** [comment]
Closing:
 - preview url should be soon supported in devfile
 - samples should be k8s based samples (samples should be kube-native for Eclipse Che )
