### ISSUE TITLE
Welcome page opens every time I start my workspace

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13962]
### Describe the bug
Every time I restart my workspace, the welcome page is opened. My expectation is that this would only happen when I open the workspace for the first time. Once I've closed the welcome page, I want it to stay closed.

### Che version

 - [ ] latest
 - [x ] nightly
 - [ ] other: please specify

### Runtime
   - [x] minishift (include output of `minishift version` and `oc version`)
 

### Installation method
   - [ ] chectl -p operator 

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x ] Linux
       - [ ] macOS

**Comment by benoitf** [comment]
is it related to https://github.com/eclipse/che-theia/pull/168 ?

**Comment by tsmaeder** [comment]
Not really: I want the welcome page once and when I close it to stay closed. I don't want to have to configure this anywhere.

**Comment by vitaliy-guliy** [comment]
@benoitf It has been implemented in non-friendly way for the user. To disable appearing the Welcome page I have to configure preferences by hands. But why? I just want to uncheck 'Show this page on startup' checkbox on the welcome page, close and forget.

**Comment by amisevsk** [comment]
To add to this issue, I also do not need to see the README.md pop up over my open files every time a workspace is started.

**Comment by azatsarynnyy** [comment]
relabeled to `area/plugins` as it's related to https://github.com/eclipse/che-theia/tree/master/plugins/welcome-plugin

**Comment by vitaliy-guliy** [comment]
I suppose this bug is appeared after merging this PR https://github.com/eclipse/che-theia/pull/605

**Comment by benoitf** [comment]
linking https://github.com/eclipse/che/issues/16352

**Comment by ericwill** [comment]
@vitaliy-guliy you fixed this awhile ago, right? If so please close this ticket.

**Comment by vitaliy-guliy** [comment]
Yes, it has been already fixed.
