### ISSUE TITLE
Some devfiles are not compatible with Hosted Che (che.openshift.io) due to 3 GB quota limitations

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#13969]
Current Hosted Che "Terms of service" allows using only 3GB of RAM for workspace. At the same time some of the devfiles from the registry like `java-web-spring` are failing with the quota issue:

![image](https://user-images.githubusercontent.com/1461122/61707817-9d04ca00-ad4b-11e9-91b6-d9c456bd9140.png)

![image](https://user-images.githubusercontent.com/1461122/61708241-a2164900-ad4c-11e9-90ae-0f945f3d9d4f.png)

NOTE: event though `globalMemoryLimit: 2674Mi` is set in the meta.yaml, I suspect it does not take into account the jwt-proxy pod

We need to:
- [x] identify the list of problematic devfiles that would fail with the quota issue https://github.com/eclipse/che/issues/13969#issuecomment-514207340
- [x] try to update defviles to make them compatible with Hosted Che resources (if not possible need to decide if those devfiles should be in the registry )
   - [x] apache-camel-springboot https://github.com/eclipse/che-devfile-registry/pull/46
   - [x] java-mysql https://github.com/eclipse/che-devfile-registry/pull/61
   - [x] java-web-spring https://github.com/eclipse/che-devfile-registry/pull/62
 
[1] https://www.eclipse.org/che/docs/che-7/hosted-che.html#terms-of-service_{context}

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW could you please provide a list of Hosted Che quota incompatible devfiles  from - https://github.com/eclipse/che-devfile-registry/tree/master/devfiles ?

This could be simply tested on prod-preview  `?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/java-web-spring/devfile.yaml` (import via factory) e.g.  https://che.prod-preview.openshift.io/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/java-web-spring/devfile.yaml

**Comment by ScrewTSW** [comment]
Devfiles failing because of quota issues:
* Apache Camel based on Spring Boot
* Java with Spring Boot and MySQL
* Java Spring Boot

All the other devfiles started correctly for me when I was doing the testing (19.7.2019)

**Comment by ibuziuk** [comment]
@sleshchenko any comments on this issue. Do you happen to know if we could shrink RAM for those devfiles or current memory settings reflect the absolute minimum ?

**Comment by apupier** [comment]
in previous version of Che 7, the Apache Camel stack was working. it was using smaller memory values, see https://github.com/eclipse/che/issues/13832#issuecomment-514148086

**Comment by amisevsk** [comment]
Related: https://github.com/eclipse/che/issues/11801

**Comment by ScrewTSW** [comment]
[23.07.2019]
Check for worksapce startup quotes with the latest version of devfile registry at prod-preview:
* ✓ angular
* ✘ apache-camel-springboot
* ✓ dotnet
* ✓ golang
* ✓ java-gradle
* ✓ ✘
* ✓ ✘
* ✓ ✘
* ✓ ✘
* ✓ ✘
* ✓ ✘

**Comment by sunix** [comment]
I don't know if this is the place but we should concider having 5GB quota limitations (and having less users capacity)

**Comment by ibuziuk** [comment]
@sunix you could add this proposal to the upcoming briefs for Q3, but this is definitely not smth we are going to address by GA

**Comment by l0rd** [comment]
@ibuziuk that doesn't look like a blocker right? Setting it as P1. I mean if we cannot reduce the amount of memory we can remove the devfiles from the openshift.io registry.

**Comment by ibuziuk** [comment]
yeah, not a blocker indeed

**Comment by apupier** [comment]
> I mean if we cannot reduce the amount of memory we can remove the devfiles from the openshift.io registry.

for Apache Camel stack, we can reduce the memory, see https://github.com/eclipse/che-devfile-registry/pull/46 and https://github.com/eclipse/che/issues/13832

so nto having Apache Camel stack on che.openshift.io is not blocker?
an alternate solution if there is a different registry to use is to set back the working memory values only in the rh-che repository?

**Comment by ibuziuk** [comment]
@apupier if it works we would merge it and make available ;-)

**Comment by apupier** [comment]
> @apupier if it works we would merge it and make available ;-)

my last manual tests on preprod are working https://github.com/eclipse/che-devfile-registry/pull/46#issuecomment-514515189

**Comment by ibuziuk** [comment]
created a separate issue for UD improvement that should be tackled after GA - https://github.com/eclipse/che/issues/14001

**Comment by ibuziuk** [comment]
All PRs have been merged. Closing
