### ISSUE TITLE
Preview URL not generated in OpenShift

### ISSUE THREAD

**Issue by talk2starGit** [eclipse-che/che#13966]
## Relevant information

Hello,
I am facing the same issue as of issue  'Preview URL not Generated in OpenShift #8456' but somehow not able to get it working in my case. How do I add the 'servers' section to workspace config ? What will be the content of the section ? 
Thanks in anticipation.

**Comment by amisevsk** [comment]
@talk2starGit Which version of Che are you using? Which version of theia? Could you share the devfile you are using to create a workspace?

**Comment by talk2starGit** [comment]
Thanks a lot @amisevsk . I figured out the issue today. Some configs were missing. Btw , my version is 
7.0.0-RC-1.1
