### ISSUE TITLE
[happy-path] Sometimes the Pet Clinic test application unavailable after getting url

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13979]
### Describe the bug
Sometimes the PetClinic test application is unavailable after getting URL and default refresh 
attempts. 

### Che version

 - [x] latest

### Steps to reproduce
Daily job: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che7-pr-happy-path-test-OKD/

### Runtime
 OKD 3.11 on the Up Shift infra

### Installation method
   `ocp.sh` script

### Environment
   `Up Shift`
![unavailable-application](https://user-images.githubusercontent.com/1640058/61722140-6e4e1a00-ad72-11e9-8242-13f08c5580fa.png)

**Comment by musienko-maxim** [comment]
We should get more info from Openshift for clarify reasons of this failure

**Comment by rhopp** [comment]
I would say we need more data:
* all routes 
* Processes from the container
* curl to the application from within the container (localhost:8080)

**Comment by nickboldt** [comment]
Smells a little like #13973 - could be same cause / dupe issue.

**Comment by rhopp** [comment]
@nickboldt The cause may be simmilar/same, but until proven, I would like to treat with these two failures as distinct ones.
