### ISSUE TITLE
Redundant dialog appears on git checkout from status bar

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13974]
### Describe the bug

vscode Git SCM extension provides branch indicator to status bar. The branch indicator has a checkout action. The checkout action must view branches of the selected SCM repository to checkout, but currently it asks to select a repository before viewing the branch list.
### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open a workspace with several projects with initialized Git
2. Click the branch indicator in the status bar: 
![screenshot-che-che 192 168 39 229 nip io-2019 07 23-15-15-00](https://user-images.githubusercontent.com/7668752/61711470-ced25c80-ad5c-11e9-8b2f-ade91ccbf089.png)

**WRONG:** A dialog with repository list appears:
![screenshot-che-che 192 168 39 229 nip io-2019 07 23-15-20-12](https://user-images.githubusercontent.com/7668752/61711754-764f8f00-ad5d-11e9-9814-d675902696dd.png)

 

### Expected behavior

A dialog with brunch list must be shown without selecting the repository, It must detect selected repository from the SCM.
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by nickboldt** [comment]
+1, usability should be improved here. But no function is blocked, so punting to P2/7.2.
