### ISSUE TITLE
Weird Login flow when Che is installed from the Operator with Openshift OAuth

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#13975]
### Describe the bug

When Che is installed with the Openshift OAuth option (which is the default) on Openshift v4, The Che login page still propose to register a new Keycloak user, instead of  redirecting to the Openshift login page directly.
When the Che user is created through the Keycloak registration page, this  brings a bug because the Keycloak `read-token` broker persmission is not added by users created this way.
Finally workspaces cannot be started

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to the Che Login page
2. Register a new user
3. Try to create a new workspace
4. You will get an error:
```
Failed to start workspace: "Client [che-public] not authorized to retrieve tokens from identity provider [openshift-v4]"
```
See this video:

![error-oauth-what we have](https://user-images.githubusercontent.com/686586/61780923-b701e380-ae03-11e9-9fb2-b99edfba2562.gif)

### Expected behavior

When the Openshift OAuth is enabled, the user should be able to link his user to an Openshift user even if he first logs through Keycloak. 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
is the issue report complete ? I don't see any description

**Comment by davidfestal** [comment]
@benoitf I completed the issue description.

**Comment by davidfestal** [comment]
The main problem is that, though there is a workaround for next logins with other users, **error recovery for a user that had this error at first is quite hard and requires Keycloak admin privileges**:

As that as soon as the user has been created through Keycloak registration (which is not the recommended logjn method), it should be either changed in Keycloak (by an Admin) to have additional `read-token` permissions, or deleted first (also by an admin), so that the user would be created again by by logging directly to the Openshift login.

It seems to me that it makes this issue a blocker since Openshift OAuth is enabled by default on OperatorHub-based installations.

**Comment by nickboldt** [comment]
if the workaround is "contact an administrator to fix your login" then yeah, it's blockish. 

But there *IS* a workaround so I'd mark this as a P1 for 7.1, not blocker for 7.0.

**Comment by davidfestal** [comment]
@nickboldt @l0rd and  @rhopp @slemeur : The fix is already available in PR https://github.com/eclipse/che-operator/pull/56

Do you think it is sufficiently critical to add it in the Endgame plan and merge the PR ?

**Comment by nickboldt** [comment]
well, if there's an existing solution that's been tested to your satisfaction, then it's a question for QE and PM/Arch to decide. 

But I'd be +1 to include it if the QE/doc burden is manageable and it can be merged in the next 16hrs for the RC4 deadline.

**Comment by davidfestal** [comment]
Done and merged
