### ISSUE TITLE
machine-exec endpoint is not secure

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13970]
### Describe the bug
machine-exec endpoint is not secure
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/eclipse/che-machine-exec-plugin/latest/meta.yaml#L17

It means that anyone is able to get access to containers terminal if he knows URL.

It's needed to make `machine-exec` endpoint secure as Theia 
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/eclipse/che-theia/latest/meta.yaml#L21
and check if everything works as expected.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

**Comment by sleshchenko** [comment]
@l0rd @slemeur I think it should be included into Endgame plan

**Comment by l0rd** [comment]
@sleshchenko makes sense. Thanks for reporting this.

**Comment by l0rd** [comment]
cc @nickboldt that should be today curator of the triage

**Comment by l0rd** [comment]
@AndrienkoAleksandr @evidolob please add the label in-progress if you start working on this issue.

**Comment by nickboldt** [comment]
"cc @nickboldt that should be today curator of the triage"
Sorry, I thought we were changing the dates/triageurs ? 

My thought was that since I'm not a team lead for Che stuff, nor deep in the Che dev, that having to triage 3 days of new issues was possibly better suited to someone with more Ch'expertise. :D

**Comment by AndrienkoAleksandr** [comment]
Will be closed after merge https://github.com/eclipse/che/pull/14061
