### ISSUE TITLE
[happy-path] Invalid url after running Pet clinic application during Happy Path scenario

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#13973]
### Describe the bug
Sometimes after launching Happy Path scenario on Kubernetes (minikube) and Openshift(OKD) infrastructures we got invalid url to the application URL. See screenshot 

### Che version

 - [x] latest
 
### Steps to reproduce
It is reproduced periodically during daily launching HAppy Path scenario on the job with OKD infrastructure: 
* [OKD](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che7-pr-happy-path-test-OKD)
* [Minikube Codenvy corp](https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-mini/)
 * [Minikibe UpShift](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Happy-Path-Tests/446)
### Screenshots
![screenshot-Check_the_running_application](https://user-images.githubusercontent.com/1640058/61712798-ce879080-ad5f-11e9-8174-8159577376d0.png)

**Comment by rhopp** [comment]
I would say we need more data:

* all routes
* Processes from the container
* curl to the application from within the container (localhost:8080)

**Comment by musienko-maxim** [comment]
after implementation latest changes in the test this problem is not repeoduced
