### ISSUE TITLE
Open terminal with non-patched images on OCP 4 fails

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13977]
### Is your enhancement related to a problem? Please describe.

"CRI-O now has support for adding the entry of the user to the /etc/password if it does not exists in /etc/passwd".

The problem is that it creates an entry like this one on /etc/passwd:

```
1001360000:x:1001360000:0:1001360000 user:/project:/sbin/nologin
```

Hence Theia exec plugin uses the login shell `/sbin/nologin` to open a terminal and fails as described [here](https://github.com/eclipse/che/issues/13584#issuecomment-514150764).

### Describe the solution you'd like

When the default login shell is `/sbin/nologin` use `sh` instead.

**Comment by benoitf** [comment]
hello, is that the issue template is no longer working ?

**Comment by sunix** [comment]
> hello, is that the issue template is no longer working ?

I guess you can go bypass with https://github.com/eclipse/che/issues/new

**Comment by sunix** [comment]
@AndrienkoAleksandr how hard would that be to fix that ? (use `/bin/sh` instead of `/sbin/nologin`) ?

**Comment by sunix** [comment]
@l0rd @rhopp @tsmaeder @slemeur @nickboldt 

This has to be 7.0.0 GA:
- We will have many users who will run Che on ocp4
- They will try to go beyond the samples and try their own containers
- This should be an easy fix without to much risk

It would be a shame to loose these users with that bug.

**Comment by sunix** [comment]
estimation from @AndrienkoAleksandr : 1 day to fix that

**Comment by l0rd** [comment]
That's a P1 but I have set `7.0.0`. That means that @AndrienkoAleksandr should work on it only if he has no blockers assigned.

**Comment by AndrienkoAleksandr** [comment]
Should be fixed by https://github.com/eclipse/che-machine-exec/pull/39
