### ISSUE TITLE
Apply styles for scrollbars in Welcome Page

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#13972]
### Is your enhancement related to a problem? Please describe.

Scrollbars in Welcome page looks weird

![Screenshot from 2019-07-23 11-39-25](https://user-images.githubusercontent.com/1655894/61711971-93805f80-ad55-11e9-8f74-0fa2047e44ec.png)

### Describe the solution you'd like

By easily adding a couple of styles we can make it better

![Screenshot from 2019-07-23 11-38-57](https://user-images.githubusercontent.com/1655894/61712037-bb6fc300-ad55-11e9-9591-4d4f77819126.png)

**Comment by sunix** [comment]
@l0rd @slemeur @nickboldt @tsmaeder @rhopp 
@vitaliy-guliy has merged that on che-theia/next. Would that be interested for 7.0.0 ?

**Comment by nickboldt** [comment]
Style changes sound like non-blocker. Push to 7.1 or even 7.2.

**Comment by slemeur** [comment]
I see the PR being merged. Can this issue be closed @vitaliy-guliy ?

**Comment by vitaliy-guliy** [comment]
Yes it is.
