### ISSUE TITLE
Provide a message when a terminal fails to open

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13980]
### Is your enhancement related to a problem? Please describe.

We have multiple issues related to terminal creation. For example because the workspace service account doesn't have the right privileges or because of a bad default login.

That can happen and can be a consequence of a misconfiguration of the che server or a bad workspace container.

The problem is that we do not provide any feedback to the user. We fail silently as if everything was ok.

The problem is also described in the is comment https://github.com/eclipse/che/issues/13584#issuecomment-513202954

### Describe the solution you'd like

I would like that an error pop-up message is shown when the terminal fail to do an exec. Possibly with an meaningful message.

**Comment by l0rd** [comment]
cc @AndrienkoAleksandr I don't see it as a Che 7.0.0 issue but rather as a P2 with target 7.x.

**Comment by nickboldt** [comment]
Throwing this into 7.2 as not blocker for 7.0, not overflow criticals for 7.1, but usability fixes for 7.2 (or later)
