### ISSUE TITLE
Task editor should properly handle the che commands syntax

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#13984]
### Describe the bug

Error reported for provided tasks in stack "Value is not accepted. Valid values: "process", "shell"."

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify https://che.prod-preview.openshift.io

Che-Theia@4ef1d89 using Theia@4ef1d89

### Steps to reproduce

1. Create a workspace from Apache Camel stack for isntance
2. Click on Terminal -> Configure Tasks... -> select "che: run the services"
3. an error is mentioned on the type "che"

### Expected behavior
no error on provided tasks

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify) https://che.prod-preview.openshift.io

### Screenshots
![image](https://user-images.githubusercontent.com/1105127/61774429-1efdfd00-adf7-11e9-9e57-4228f8eecd8a.png)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by apupier** [comment]
please note that the command is working well when executed

**Comment by amisevsk** [comment]
It appears that the "type" field is filled when getting the command from the devfile. Issue is present in all devfiles I've checked.

**Comment by slemeur** [comment]
Yes I reported to the team the same problem today as well.
It is defined here: https://github.com/theia-ide/theia/blob/master/packages/task/src/browser/task-schema-updater.ts#L123
But not extended for the sake of che-theia.

**Comment by RomanNikitenko** [comment]
I added schema for `che` tasks within https://github.com/eclipse/che-theia/pull/550
Now content assistant should work for `che` tasks
