### ISSUE TITLE
[chectl] On minishift, `che` namespace must exist before executing server:start

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#13981]
### Describe the bug
Running `chectl server:start` as `system:admin` results in a `che` namespace that cannot be read by regular users. This is because chectl creates the namespace using the currently logged in user.

Working around this requires a user to create the `che` namespace as their regular user *before* running the chectl command (in which case resources are created in the existing namespace).

### Che*ctl* version
chectl/0.0.2-4f9931d linux-x64 node-v10.4.1

### Steps to reproduce
1. Start minishift
2. `oc delete project che` (ensure project does not exist yet)
3. `oc login -u system:admin`
2. `chectl server:start -p minishift -a operator`
3. Project `che` is created by `system:admin`, regular users do not have access
    - e.g. via `oc describe rolebinding.rbac -n che`:
        ```
        Name:         admin
        Labels:       <none>
        Annotations:  <none>
        Role:
          Kind:  ClusterRole
          Name:  admin
        Subjects:
          Kind  Name          Namespace
          ----  ----          ---------
          User  system:admin  
        ```

### Expected behavior
`chectl` should ensure default user (`developer`) has access to `che` namespace, e.g. via something like
```
oc policy add-role-to-user admin developer
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
only in case of minishift, correct ?

**Comment by benoitf** [comment]
to add this extra permission

**Comment by amisevsk** [comment]
I've only tested minishift thus far, but assuming the flow is similar I'd expect this issue to be present on minikube as well.

**Comment by nickboldt** [comment]
Given simple workaround, not an urgent task.

But what if chectl (when talking to minishift) could use the logged in user to do `oc adm policy --as=system:admin add-cluster-role-to-user cluster-admin YOUR_USER` or whatever the minikube equivalent is?

**Comment by amisevsk** [comment]
I don't know about granting cluster-admin to the regular user; it could make the experience a whole lot more confusing (as it would give access to all projects on the 'cluster' for a regular user). Ideally the only difference after installing Che is a new project, called `eclipse-che` or whatever.
