### ISSUE TITLE
Usability: Right-click Should not Execute Commands

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13988]
The workspace view on the right side shows the various containers and the commands available for them. When I right-click on a command, it starts executing. 

This is unexpected: right-click opens a context menu in the vast majority of cases. It should not execute the command

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

**Comment by vitaliy-guliy** [comment]
We know about that and ready to find a solution.

Having a look at the [Plugin API](https://github.com/theia-ide/theia/blob/master/packages/plugin/src/theia.d.ts#L3623) we can see that plugin writer can specify a command which will be executed when the tree item is selected. We use that field to handle clicking on the tree item.

In Theia right click leads to changing the selection, firing corresponding events with following execution of commands.
That's a main problem.

**Comment by nickboldt** [comment]
Also related are #13989 and #13149 since a user would expect to be able to Run or Configure from a right-click context menu, not have the command execute.

**Comment by azatsarynnyy** [comment]
cannot reproduce
looks like already fixed
