### ISSUE TITLE
Edit the current workspace devfile from the workspace.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13983]
### Is your enhancement related to a problem? Please describe.
Be able to edit the current workspace devfile from che-theia.
Avoid having to switch from the dashboard to/from the workspace for updating a devfile.

### Describe the solution you'd like
Che-theia should copy the devfile to /projects/.devfile.yaml and synchronize any change to workspace devfile.

### Alternative solution
Add devfile item before all containers in `my workspace` view. Double click should open the editor with the devfile. and save should save the devfile of the workspace config.
Bonus:
- action to compare current devfile and a devfile.yaml (should detect devfiles maybe) of the project

**Comment by nickboldt** [comment]
Related to #13982. I'd move it to the same priority: usability fixes in 7.2.

**Comment by slemeur** [comment]
This is a great enhancement indeed. Thinking more broadly, we need to consolidate the way devfile is getting used in the workspace. We have different sources for the workspace configuration (devfile, tasks.json, launch.json) and none of them are aligned of synchronize. 
That worth getting an epic on this for future release as the impacts will be important: https://github.com/eclipse/che/issues/14014

**Comment by ibuziuk** [comment]
@sunix putting P2 for now
