### ISSUE TITLE
Usability: No Way to Inspect Commands

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13989]
In the "My Workspace"-view on the right side, there are commands shown. There is no obvious way to know what the commands are doing.

I would expect there to be a context menu on the commands that allows to inspect the commands somehow.

**Comment by vitaliy-guliy** [comment]
As an option could be displaying a pretty wide tooltip with command details.

**Comment by sunix** [comment]
this is a duplicate of https://github.com/eclipse/che/issues/13149 right ? could we close this one ?

**Comment by amisevsk** [comment]
Personally I would prefer a `Run` and `Configure` button on the sidebar; adding the full command could clutter the view too much. Currently the only way I know to configure/view the content of a command is to go through the Theia menus.

**Comment by nickboldt** [comment]
-1 for "big ass tooltip"
+1 for ability to configure/edit the thing (but then you need to be sure you're synching it back into the .devfile.yaml (see #13983) if that gets implemented.

**Comment by sunix** [comment]
I personally like the tooltip that would be something like giving a previe of what the command is going to run without having to click and open something and close it.
I think we should have both (ability to edit + tooltip)

**Comment by azatsarynnyy** [comment]
Closing it since we have tooltips now.
