### ISSUE TITLE
Cannot create workspace with new project on Dashboard

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#13991]
### Steps to reproduce
1. Open **NewWorkspace** page on **Dashboard**.
2. Click on ```Add or Import Project``` button and add a new project.
3. Click on ```Create & Open``` button to start this workspace

### Expected behavior
The workspace is started and added project is imported.

### Actual behavior
There is ```Devfile schema validation failed``` error notification(see screenshot) on **Dashboard**. It looks like it happens because of https://github.com/eclipse/che/pull/13923 PR changes.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screencast
![screencast-che-eclipse-che 10 33 177 143 nip io-2019 07 24-13_55_11](https://user-images.githubusercontent.com/7760565/61788883-e7557c00-ae1b-11e9-8156-0042ad2adb7e.gif)

### Screenshots
![Selection_240](https://user-images.githubusercontent.com/7760565/61788871-dc025080-ae1b-11e9-9760-d4413b32fff5.png)

![Selection_241](https://user-images.githubusercontent.com/7760565/61790132-1ae5d580-ae1f-11e9-90b5-e4b9ab62515c.png)

### Che version
**7.0.0-rc-4.0-SNAPSHOT**

**Comment by l0rd** [comment]
That's a P1, not a blocker. That's because that's about importing 2 projects. Not the most common use case.
