### ISSUE TITLE
Add ability to disable services detection for ports plugin 

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13990]
Edited according to discussions in the issue.

### Is your enhancement related to a problem? Please describe.
Sometimes Ports plugin suggests to open services which are not supposed to be opened. It might be Hosted Plugin Instance or just a server from integration tests or debug port of application which Theia will consume immediately. Obviously we cannot blacklist such ports because we do not know which application is started and we cannnot not know the port range.

### Describe the solution you'd like
Add ability to stop discovering of new services in ports plugin. It might be a command to turn on/off monitoring. Would be nice to have default value in preferences.
Also would be useful to have ignored port ranges which also could be changed in settings.

### Steps to reproduce
1. Open a Theia plugin and compile it
2. Try to debug the plugin using `Hosted Plugin: Debug Instance` command

Another way to reproduce the issue is to build Che in Che. A lot of suggestion will appear.
![ports-plugin-build-che](https://user-images.githubusercontent.com/15607393/62923361-386ee500-bdb6-11e9-8eb9-eb23e610d289.png)

Try to debug an application. The Ports plugin will suggest to open debugger port.

**Comment by amisevsk** [comment]
Slightly related: a similar behavior can interfere with debugging on the apache-camel devfile (ports plugin prompts to open 5005, when I did this I could no longer connect a remote debugger)

**Comment by slemeur** [comment]
@amisevsk : your issue seems more like a bug. Could you fill an issue for it? 

@mmorhun : I think the plugin port is made to be agnostic to any application starting a process - does not matter if it's for hosted mode or not. Instead of having the plugin understanding if it's hosted mode, I would suggest a solution where the user can turn off the detection of new services by the ports plugin. WDYT?

**Comment by amisevsk** [comment]
@slemeur Must have been a transient issue; I can no longer reproduce this.

**Comment by mmorhun** [comment]
@slemeur makes sense. Also would be nice if I could disable the detectiong by default and then turn it on when needed. Or maybe even disable the plugin at all and use only for workspaces where I want to experiment with servers. But I think this is matter of taste...

**Comment by amisevsk** [comment]
Another option would be to provide a way to configure an 'ignored' range, per devfile/workspace. You could specify endpoints as type "debug"/"internal" or something, and then the endpoint plugin would ignore those for the purpose of exposing. That may be a lot of work for a minor issue, though.

**Comment by slemeur** [comment]
@amisevsk that's a fair point too. At some point, we'll need to be able to bring plugin's metadata to "enrich"/"set"/"configure" the plugins that are running in the workspace.

**Comment by mmorhun** [comment]
I've found another reason why we should add disabling. Just build Che in Che:
![ports-plugin-build-che](https://user-images.githubusercontent.com/15607393/62923361-386ee500-bdb6-11e9-8eb9-eb23e610d289.png)

**Comment by slemeur** [comment]
@mmorhun : I think the issue should be edited to reflect the different improvements suggested. Would you mind taking care of that?

**Comment by mmorhun** [comment]
@slemeur I've updated the issue title and description.

**Comment by gorkem** [comment]
Can we just disable offering forwarding by default with a preference and/or command to enable it?

**Comment by mmorhun** [comment]
I think we can. But maybe we should add some item in status bar to be able to turn it on/off quickly (rather to show the feature for new users).

**Comment by gorkem** [comment]
No need to add it to the status bar, a preference should suffice. 

@slemeur We probably need documentation added for the plugins that we provide, at least the built-in ones.

**Comment by sunix** [comment]
I really like the feature, it is very useful but maybe the way it is presented has the bad UX (with notification)
Why not showing up a dedicated view with all the details of ports that could be forwarded and action to forward and access to urls ?
Or integrate this in the existing `my workspace` view ?
it could be a status bar icon that would show (on click) all the ports that could be forwarded and urls  ...

**Comment by mmorhun** [comment]
cc @ericwill
