### ISSUE TITLE
chectl raise timeout error on server:start command but che is running

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14008]
### Describe the bug
When try to deploy Che on Minikube using chectl, the chectl tool fails with timeout error in `Post installation checklist` section.
However, Che server is deployed and seems work. At least, I was able to start Java Maven workspace from the template.

### Che version
latest

### Steps to reproduce

1. Start minikube with command `minikube start --cpus 2 --memory 10240 --extra-config=apiserver.authorization-mode=RBAC`
2. Run `chectl server:start`
3. Look at output. It will hung on `Post installation checklist`.`Devfile registry pod bootstrap`.`scheduling` and then fail with timeout error (see screenshot below)

### Expected behavior
Everything finishes without errors.

### Runtime
Minikube
minikube version: v1.2.0
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots
![chectl-hungs](https://user-images.githubusercontent.com/15607393/61805426-6f4c7d80-ae3e-11e9-9283-e1c4175494fe.jpg)

### Installation method
`chectl server:start`

### Environment
Fedora 30
Minikube 1.2
chectl (newest on issue creation time: `bb52fbb38d33fce54395e0a4bb9745731cc59e3a`)

**Comment by vitaliy-guliy** [comment]
Link with https://github.com/eclipse/che/issues/13881

**Comment by l0rd** [comment]
@mmorhun was che already running when you tried to start it? I mean if Che was running when you `minikube stop` that it gets re-provisioned silently when you `minikube start`.

**Comment by mmorhun** [comment]
@l0rd I started from scratch. Created Minikube VM (minikube start with args), then ran chectl to provision Che. It failed with the described error.
