### ISSUE TITLE
nodejs-mongo devfile sample issues

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14009]
### Describe the bug
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs-mongo
3 issues
- `run the web app` task opens URL that returns 404 (#13964, #13945)
- "create test user" task gives no output and it's not clear whether it works
- when running `run the web app` task for a while, this Error happens
```
/projects/nodejs-mongodb-app/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ETIMEDOUT 10.109.232.241:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Emitted 'error' event at:
    at NativeConnection.Connection.error (/projects/nodejs-mongodb-app/node_modules/mongoose/lib/connection.js:443:8)
    at /projects/nodejs-mongodb-app/node_modules/mongoose/lib/connection.js:472:15
    at /projects/nodejs-mongodb-app/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:59:21
    at /projects/nodejs-mongodb-app/node_modules/mongodb/lib/db.js:232:14
    at Server.<anonymous> (/projects/nodejs-mongodb-app/node_modules/mongodb/lib/server.js:240:9)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at Pool.<anonymous> (/projects/nodejs-mongodb-app/node_modules/mongodb-core/lib/topologies/server.js:308:68)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/projects/nodejs-mongodb-app/node_modules/mongodb-core/lib/connection/pool.js:115:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/projects/nodejs-mongodb-app/node_modules/mongodb-core/lib/connection/connection.js:144:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
[nodemon] app crashed - waiting for file changes before starting...
```

### Che version
 - [x] nightly

### Steps to reproduce
1. import devfile https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs-mongo
1. run `run the web app` task
1. ! page with URL getting 404 appears
1. wait for some time doing nothing
1. ! see Error in terminal
1. run `create test user`
1. ! nothing visible happens

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by amisevsk** [comment]
This is tricky as the sample app here is a backend app; the main interaction would be via `curl/wget`. 

@sparkoo Do you think adding tasks for "test [x] API path" would resolve this issue?

**Comment by slemeur** [comment]
Adding it to 7.1.0 as related to https://github.com/eclipse/che/issues/13945

**Comment by mkuznyetsov** [comment]
the issue with this sample, that it doesn't work on minikube/minishift instances without `userland-proxy=false`, which is not enforced anymore in chectl/docs.
that's why application cannot connect to mongodb container and fails (2 & 3 points of the issue)
@benoitf @davidfestal could you suggest something on this?

as for `run the web app task opens URL that returns 404`, this would be solved by Preview URL feature (https://github.com/eclipse/che/issues/13945) , as default preview path `/` indeed points to 404, where it should be `/api/articles`

**Comment by amisevsk** [comment]
I think the main issue here is that the sample app used is a *bad* example. It's meant to be a backend API; the way to test it would be via something like postman. 

Even if we redirect to `/api/articles`, the user cannot do anything with that web page, it just shows the json response that the server would give if you used `curl`. There's no way to post data, except by tasks.

I'm working on updating some of the config to make this smoother for 7.0, but even with workarounds, Che is ill-suited to working on this app without additional software. Some endpoints require JWT auth.

**Comment by l0rd** [comment]
I have opened #14392 to completely replace the nodejs + mongodb sample
