### ISSUE TITLE
Theia tasks are listed in random order

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14000]
### Describe the bug
Each time workspace is started, tasks in right panel are displayed in random order. This might be confusing for the user.

### Che version

 - [x] nightly

### Steps to reproduce
 

1. Start workspace with multiple tasks (e.g. https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-laravel/devfile.yaml)
2. check tasks order in right panel
3. stop workspace and start again
4. check tasks order in right panel

![task_order1](https://user-images.githubusercontent.com/1160903/61796920-aa42b700-ae26-11e9-8a10-3f11789b0a67.png)
![task_order2](https://user-images.githubusercontent.com/1160903/61796926-ad3da780-ae26-11e9-86c5-257e327df9e1.png)

### Expected behavior
tasks order is always the same (probably preserved same as in devfile)

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by vitaliy-guliy** [comment]
I would display them sorted by name.

**Comment by nickboldt** [comment]
Setting to 7.2 but with P1 because OMG this should be like one line of code to provide a sorted list.

**Comment by sparkoo** [comment]
I would prefer to preserve order from devfile.

**Comment by tsmaeder** [comment]
If the order from the devfile is easily available, we will preserve it, otherwise we'll sort by name.
