### ISSUE TITLE
[happy-path] Somethimes "Happy Path" test fails on validation of autocomplete

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14018]
### Describe the bug
Somethimes "Happy Path" test fails on validation of autocomplete

### Che version

Che 7.0.0-rc-4.0-SNAPSHOT
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Run workspace by devfile <https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/happy-path-workspace.yaml>
 - Open any java class and pay attention to the status bar
 - Open any java class
 - Wait until initialization LS text is absent in the IDE status bar
 - Invoke autocomplete for any java element of the opened file
 - Pay attention that time to time autocomplete displays without any java suggestions

### Expected behavior
After invoking, autocomplete container displays with java suggestions

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Autocomplete](https://user-images.githubusercontent.com/22724619/61861876-825e5c80-aed5-11e9-9a9d-0eb33724f940.png)

### HTML dump
[pagesource-Autocomplete.zip](https://github.com/eclipse/che/files/3430721/pagesource-Autocomplete.zip)

### Browser logs
[browserlogs-Autocomplete.txt](https://github.com/eclipse/che/files/3430722/browserlogs-Autocomplete.txt)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
Not quite sure about this one: does this fail when you do it by hand or does it fail when you run it in the test? If by hand, does it succeed first and then fail some time afterwards? Any exceptions in any of the outputs?

**Comment by rhopp** [comment]
We weren't able to reproduce this by hand. This failure is happening only when running automated test. It's happening few times a day (we are running the test every hour on different infras (minishift,minikube)).
This issue is about investigation of this test failure. If we find out it's possible LS bug, or any other bug, we'll open another issue. (It still can be some timing issue in test - that would need to be resolved on the test side)
Triaging this for 7.0, as this is prerequisite of having stable Happy Path test.

**Comment by dmytro-ndp** [comment]
The issue is still actual:
- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che7-e2e-tests/job/CHE-7-Happy-Path-Tests/639/artifact/e2e/report/Language_server_validation_Autocomplete/screenshot-Autocomplete.png

**Comment by dmytro-ndp** [comment]
There was wrong branch [investigate-13973](https://github.com/eclipse/che/tree/investigate-13973) used in the job where issue happened.
It didn't reproduce on `master` branch.
