### ISSUE TITLE
php-laravel devfile sample should be simplified

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14010]
### Is your task related to a problem? Please describe.
php-laravel devfile (https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/php-laravel) has 6 tasks. To properly run the project, user has to go through README and map individual install steps to tasks and run them one by one.

### Describe the solution you'd like
Workflow should be simplified by only one task that prepares project regarding to README instructions. And second task that will run the project.

**Comment by amisevsk** [comment]
+1 for this, when testing this devfile it took more reasoning than it should to prepare the project; it makes more sense to have one "prepare" task. Additionally, running tasks in the wrong order often results in error.

**Comment by slemeur** [comment]
Good improvement to add!
