### ISSUE TITLE
When Openshift OAuth is enabled login directly with the Openshift login 

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#14012]
### Is your enhancement related to a problem? Please describe.

The problem is that when Openshift OAuth is enabled, which is the default when Che installed by the Operator through OperatorHub, a user that logs into Che is still proposed the Keycloak registration page to login, instead of being directly brought to the Openshift login page.

When a user has created his account through the Keycloak registration page, and has accessed the dashboard, later he will have to link his Che user with with his Openshift user to be able to start a workspace.

This is shown on the following video:
![not-user-friendly-openshift-oaut](https://user-images.githubusercontent.com/686586/61813526-2ac4e000-ae46-11e9-9fc3-ea4755d27839.gif)

This is not a very good user experience.

### Describe the solution you'd like

We should login into Che through the Openshift login page directly.

**Comment by slemeur** [comment]
linking to: https://github.com/eclipse/che/issues/13975

**Comment by slemeur** [comment]
After discussing with @davidfestal , this issue is going to be addressed along with https://github.com/eclipse/che/issues/14013

**Comment by slemeur** [comment]
setting 7.1.0 milestone
