### ISSUE TITLE
Investigate testing DAP features

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14025]
Investigate writing automated tests as requested in https://github.com/eclipse/che/issues/13897

The goal of this issue is to come up with a way to write tests for VS Code extensions that provide debug adapters.

We'd have to be able to script 
1. Setting up a workspace
2. Creating debug configurations and launching debuggees (and connecting to them)
3. Exceute debug protocol actions
3. Intercepting and verifying results of those debug actions

I would prefer to write the scripts based on a API, not based on UI interactions

**Comment by tolusha** [comment]
It is possible to initialize and control debug session using Theia frontend API [1]
Here is the testing workspace [2]

[1] https://github.com/theia-ide/theia/blob/ab/api-tests/packages/apt-tests/src/browser/debug-tests.ts
[2] https://github.com/theia-ide/theia/tree/ab/api-tests/packages/apt-tests/testWorkspace

The next step is to create a test suite like VS Code does [3] and run it using launch configuration [4]

[3] https://github.com/microsoft/vscode/tree/master/extensions/vscode-api-tests
[4] https://github.com/theia-ide/theia/issues/4224#issuecomment-459752557

**Comment by tolusha** [comment]
The work is done here [1]
The workflow is the following: 
1. Start Theia
2. Open Theia project
3. Run the configuration below

```json
{
      "name": "Launch Theia Tests",
      "type": "node",
      "request": "launch",
      "args": [
        "${workspaceFolder}/examples/browser/src-gen/backend/main.js",
        "${workspaceFolder}/packages/theia-tests/testWorkspace",
        "--port",
        "3030",
        "--hostname",
        "0.0.0.0"
      ],
      "env": {
        "THEIA_DEFAULT_PLUGINS": "local-dir:${workspaceFolder}/plugins"
      },
      "stopOnEntry": false,
      "sourceMaps": true,
      "outFiles": [
        "${workspaceFolder}/../.js"
      ]
    }
```

4. Opens browser:
`http://localhost:3030/?runTests`
`?runTests` is a crucial think which tells `TestRunner` to start tests.

5. Wait until tests are finished

```
root INFO -------------------------------------------------------------
root INFO Results:
root INFO Test run: 2 Passed: 2 Failures: 0
root INFO -------------------------------------------------------------
```

![screencast-localhost_3000-2019 08 23-14_45_09](https://user-images.githubusercontent.com/1640675/63590520-c025d200-c5b4-11e9-8cb4-4463db85ef13.gif)


[1] https://github.com/theia-ide/theia/tree/ab/theia-tests/packages/theia-tests
