### ISSUE TITLE
[happy-path] Investigate why sometimes notifications don't close after clicking to "yes" or "cancel" button

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14022]
### Is your task related to a problem? Please describe.

We should investigate a root reason why sometimes notifications stay opened after clicking on it
Related to issue https://github.com/eclipse/che/issues/13864

**Comment by rhopp** [comment]
Triaging for 7.x. We've implemented a workaround for tests (in #13864 ) and the original issue is quite impossible to reproduce by hand (at least we weren't able to do so) - thus not affecting users.

**Comment by rhopp** [comment]
We need to investigate, if this workaround (https://github.com/eclipse/che/blob/master/e2e/pageobjects/ide/Ide.ts#L58) is still executing. We should remove it (or throw exception with link to original issue - sign of regression)

**Comment by rhopp** [comment]
@Ohrimenko1988 Have you seen this one recently? If not, please close this issue.

**Comment by rhopp** [comment]
@Ohrimenko1988 ping
