### ISSUE TITLE
[happy-path] Make npm task configurable in che-e2e container image

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14027]
### Is your task related to a problem? Please describe.
Currently we have hard-coded `npm run test` as a command to execute tests in `che-e2e` container image: https://github.com/eclipse/che/blob/master/dockerfiles/e2e/docker-entrypoint.sh#L30 

### Describe the solution you'd like
I would like to be able to run any npm target I want (for example `npm run test-happy-path`)

**Comment by tsmaeder** [comment]
@rhopp what is this needed for? Don't know how to triage this.

**Comment by rhopp** [comment]
Container image we are using for running Happy Path test has hardcoded specfile which it should run in it's entrypoint. This issue is about parameterizing this - enabling running different specfiles (different test scenarios).
Triaged for 7.1
