### ISSUE TITLE
Exception in the che-theia log output from preferences extension[Minor]

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14021]
### Describe the bug
When we start hosted instance of the che-theia without opened any project, we can find in the log console errors:
```
root ERROR Could not start contribution Error: Failed to get Theia workspace.
    at e.<anonymous> (http://routeqg7jf287-workspacec8t7gh9emfaun22j.192.168.99.100.nip.io/bundle.js:114:2525312)
    at http://routeqg7jf287-workspacec8t7gh9emfaun22j.192.168.99.100.nip.io/bundle.js:114:2523454
    at Object.next (http://routeqg7jf287-workspacec8t7gh9emfaun22j.192.168.99.100.nip.io/bundle.js:114:2523559)
    at a (http://routeqg7jf287-workspacec8t7gh9emfaun22j.192.168.99.100.nip.io/bundle.js:114:2522305)
```
This error come from https://github.com/eclipse/che-theia/tree/master/extensions/eclipse-che-theia-preferences-provider-extension extension. But we should not throw this error, it's ok if we have che-theia without opened any project(without "theia workspace").
P.S.:
https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-preferences-provider-extension/src/browser/prefs-provider.ts#L82

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
How do you provoke this bug? Do you just not pass an argument?
