### ISSUE TITLE
Unexpected yaml structure in UD devfile editor can cause internal server error

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14032]
### Describe the bug
When editing a workspace's devfile in the UD, certain errors in the yaml cause internal server error notifications and a stacktrace to be logged to console, e.g.:
```
2019-07-25 21:52:43,678[nio-8080-exec-1]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2019-07-25 21:52:43
  | com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2136 path $.devfile.attributes[0]
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
  | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
  | at com.google.gson.Gson.fromJson(Gson.java:927)
```

This occurs when entering an object in place of an array or vice-versa

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Open workspace configuration to the devfile editor tab. Append the yaml
```yaml
attributes:
  - persistVolumes: 'false'
```
(an array instead of an object), and the error appears.

### Expected behavior
This type of error should at least not print a stacktrace.

**Comment by sleshchenko** [comment]
I think it duplicates the following issue https://github.com/eclipse/che/issues/3334

**Comment by rhopp** [comment]
@sleshchenko What do you think about keeping this one opened and closing the old one as duplicate? The old one doesn't have much more info in in and this one is at least more actual (using devfile, ...)

**Comment by amisevsk** [comment]
@sleshchenko I didn't look that far back in history :)

**Comment by sleshchenko** [comment]
@rhopp I'm OK with closing one, but after updating current. Because now it describes that only Devfile has such problem but it's a common issue of our REST APIs.

**Comment by sleshchenko** [comment]
it can be handled on Dashboard side within https://github.com/eclipse/che/issues/15654
