### ISSUE TITLE
Add support for project type auto-detection

### ISSUE THREAD

**Issue by mpouttuclarke** [eclipse-che/che#1403]
The project hierarchy for a maven Java project no longer rolls up the package directories into one dir for java packages.  This makes navigation more difficult due to having to navigate package names.
<img width="1280" alt="screen shot 2016-05-31 at 8 03 02 pm" src="https://cloud.githubusercontent.com/assets/353125/15697036/16894302-276b-11e6-8746-0411d09b02f7.png">

**Comment by mpouttuclarke** [comment]
However, when the workspace is first created this issue occurs.  This is the work around: Select the root project and go to Project -> Configuration and select Next  and then Save.  This forces the Maven configuration to be updated and fixes the issue.  
<img width="1280" alt="screen shot 2016-05-31 at 8 09 18 pm" src="https://cloud.githubusercontent.com/assets/353125/15697118/10c7e13e-276c-11e6-9d90-7167379883bf.png">

**Comment by mpouttuclarke** [comment]
Another symptom of this is that when right clicking on a Java package folder the New -> Java Class and New -> Java Package are greyed out

**Comment by ghost** [comment]
@mpouttuclarke are you certain that the project has been configured as a Maven project before? Are using a factory or is it an existing project in your workspace?

As to grayed out Class and package menu items, it's best to take a look at the project itself. Is it publicly available on GitHub?

**Comment by mpouttuclarke** [comment]
Nope it wasn't configured as a maven project.  I thought Che recognized the project type automatically.  If that's not the case then this is an enhancement request rather than an issue.

**Comment by ddementieva** [comment]
There is no autodetection of a project type right now, so a user should choose it manually when importing a project. 

Also can you send a screenshot of a problem with classes and packages?

**Comment by ddementieva** [comment]
@mpouttuclarke, any update on the problem?
