### ISSUE TITLE
Add target="_blank" to the link for "Make a wish" button.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#14036]
### Is your enhancement related to a problem? Please describe.

At least on ChromeOS, when you press a `Make a wish` button, it will transition the window showing IDE to the Gmail page.

This is trivial and easy to fix. It is no need to add 7.0.0 end game, IMO.
 
### Describe the solution you'd like

This will be fixed by adding `target="_blank"` to the `<a>` element.
 
### Describe alternatives you've considered

No.

### Additional context

![gmail](https://user-images.githubusercontent.com/101795/61936488-d2b5e700-afc7-11e9-9eb0-d1c43737a3af.gif)

**Comment by rhopp** [comment]
Thanks for the PR. I'm triaging this for 7.1, as the PR is already existing.

**Comment by slemeur** [comment]
@evidolob : To merge as soon as 7.0 is released.
