### ISSUE TITLE
Include Red Hat Project Initializer in Apache Camel stack

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#14043]
### Is your enhancement related to a problem? Please describe.

To create a new Camel/fuse project, the project initializer is very convenient

### Describe the solution you'd like

having the Project initializer in the Apache Camel stack

### Describe alternatives you've considered

it i spossible to install it afterwise by a user.

### Additional context

currently the memory required by Apache Camel stack has reached its limits in a constrained environment like che.openshift.io (3G) We might need to reduce size of the others first or to have different stacks for hosted environments and "professional sized" environments.

**Comment by gorkem** [comment]
How is the memory requirements are related to initializer?

**Comment by apupier** [comment]
> How is the memory requirements are related to initializer?

the actual Camel stack has reached the maximum of memory available on hosted che.openshift.io. If we want to add any other extensions in the Camel stack, we need to investigate either:
- to reduce memory taken by one of the 3 other extensions (Java, xml, camel)
- to increase amount of memory available by default on che.openshift.io
- or be ready to provide different stacks on pure Che 7 and che.openshift.io with one on che.openshift.io which is capable of less things.

**Comment by ericwill** [comment]
@apupier if you'd like to contribute this, I'd be happy to review the PR.

**Comment by apupier** [comment]
no plan to work on that on short term:
- heard that project Initializer is no more an active project
- remains the problem of memory https://github.com/eclipse/che/issues/14043#issuecomment-515916005

**Comment by apupier** [comment]
closing. The Red Hat Project initializer is going to be replaced some other stuff around odo
