### ISSUE TITLE
Editor with web server backend running in extension sidecar

### ISSUE THREAD

**Issue by johnsteele** [eclipse-che/che#14045]
## Summary

I have a VSCode extension that provides a graphical HTML/JS editor. The editor is served from, and communicates with (using REST and web-sockets), an embedded web server that I start from within the extension.

You can see the server being started here:

- https://github.com/windup/rhamt-vscode-extension/blob/master/src/editor/configurationEditorServer.ts#L33

The graphical editor is rendered using an iFrame that points to the host/ip/port of the embedded web server:

- https://github.com/windup/rhamt-vscode-extension/blob/master/src/editor/configurationEditor.ts#L50

The editor works as expected when running VSCode on localhost.

I am now trying to get the VSCode extension running within the Che7 env.

In Che, I have the extension running within a sidecar, which is where the webserver is started I presume, and I now need to resolve the URL to that webserver, so that I can point the iFrame to it. This implies the URL endpoint would need to be somehow exposed and accessible to the outside (from the client's browser). 

I understand I might need to expose the servers' port from the sidecar container, but how do I resolve the URL to that server?

I've logged below the machine server's URLs:

<img width="1169" alt="urls" src="https://user-images.githubusercontent.com/407192/61952376-af684900-af81-11e9-8410-f6b856958b0d.png">

**Comment by l0rd** [comment]
@johnsteele you need to expose using the endpoint of the [che-plugin meta.yaml](https://github.com/eclipse/che-plugin-registry/tree/master/#plugin-meta-yaml-structure). The endpoint should then be available in che-theia container view. I am not sure I understand where you to embed the `iframe` though.
