### ISSUE TITLE
How to extend a new project type that contains a new perspective

### ISSUE THREAD

**Issue by wn092943** [eclipse-che/che#1404]
hi,
    I have read docs about how to extend Eclipse Che  from  `https://eclipse-che.readme.io/v4.3`, but I can not get information that I need.
    I wanted to extend a new project type. Once this new project is created, workspace should show me a new perspective with new functions that doesn't work for coding or compiling, not a IDE. As developing a RCP program based on Eclipse, I hope develop a new program based on Che. 
    I hope I can get some tips, it is better if you can provide tutorials.
    By the way, whether Eclipse che support GEF?

**Comment by TylerJewell** [comment]
@slemeur Will get you a response.  The plugin resource center is going to be published soon.  This will be a good test to see if we have covered all of the scenarios.

**Comment by slemeur** [comment]
Hello @wn092943

We are still working on it, but would definitely appreciate your feedback on the new documentation resources that we will publish about authoring Che extension.

The plugin resource center is written as a set of tutorials + sample code, each of them are covering different areas and possibilities for Che extensions.
I recommend you to start by the [introduction](https://eclipse-che.readme.io/v4.3/docs/introduction-1).
The source code of the tutorials are [here](https://github.com/eclipse/che/tree/master/samples).

Your specific question, about creating a new project type, is covered by the following tutorial:
https://eclipse-che.readme.io/v4.3/docs/project-types

For your particular use case, you might need to create a custom assembly and remove all the plugins that are not needed for your use case.

At this moment, there is no support of GEF inside of Che - even if we would love to get that (along with GMF and EMF). We are exploring and considering some options on this particular area.

**Comment by ghost** [comment]
@wn092943 can you perhaps share some ideas on what you are trying to achieve and what you have already done?

**Comment by ddementieva** [comment]
@wn092943 Any update on this issue? 

We've updated docs on how to build an extension. You may want to take a look at them at https://eclipse-che.readme.io/docs/create-and-build-extensions
