### ISSUE TITLE
Synchronize commands from "Workspace panel" with tasks.json

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14041]
### Is your enhancement related to a problem? Please describe.
At the moment we display commands from devfile in My Workspace panel area.
But user has ability to add new commands to tasks.json file, remove existed commands or edit label for a command. My Workspace panel doesn't display this changes.
If I understand correctly the panel is updated at start workspace and page refreshing from devfile.  
Would be nice to improve this behavior.

**Comment by sunix** [comment]
@RomanNikitenko to me this should be part of the implementation of 'ability to add new commands to tasks.json file, remove existed commands or edit label for a command.'

**Comment by RomanNikitenko** [comment]
@sunix 
thank you, Sun, I appreciate your opinion!
maybe I was focused on running tasks from Terminal -> Run Tasks menu only and didn't tested it for this panel.
I provide 'How to test' section with images for my PRs, so everybody has ability to review/test it.

**Comment by rhopp** [comment]
As this is pretty big inconvience for users I still think we should triage this one for 7.1, as there is relatively simple workaround -> use command `Task: Run Task...`, This command is reflecting all the changes in tasks.json.

**Comment by sunix** [comment]
> @sunix
> thank you, Sun, I appreciate your opinion!
> maybe I was focused on running tasks from Terminal -> Run Tasks menu only and didn't tested it for this panel.
> I provide 'How to test' section with images for my PRs, so everybody has ability to review/test it.

It is your responsibility to try giving the best quality possible. You cannot ask other people to do your job. Other people can help you and give you feedback but you have to be proactive. This is good that you have reported this issue but it would have been better to handle that before. It would save time for everyone and we would have a better product.

**Comment by RomanNikitenko** [comment]
@sunix 
thank you very much, Sun, you help me to become more responsible!

**Comment by RomanNikitenko** [comment]
> It is your responsibility to try giving the best quality possible on your contributions. You cannot ask other people to do your job. Other people can help you and give you feedback but you have to be proactive. 

You can see a lot of bugs in the issues section. Do you really think our coworkers are not responsible?

I think there are a lot of other causes of the problem.
Our product is growing rapidly and only one person can not know everything, can not take in account all details, can not test all possible use cases. Finally man - is not machine and everyone has the right to a mistake.

I believe that strength of the community is ability to look at the same problem from different perspectives. Somebody creates a PR and everybody can look at the problem from own angle, test own use cases, make a point, propose better solution and so on.

That's why when I do code review I try to test the all possible cases, describe the potential problems and so on.
You can see that for example here 
- https://github.com/theia-ide/theia/ pull/5777#issuecomment-514629414 (please remove the space, I don't want to link the issue to not related PR) 
- here I have to create the sample plugin to test the changes https://github.com/theia-ide/theia/ pull/5312#issuecomment-508732775 

It gives ability to identify the potential problem before merge, find the best solution together.
For my PRs I start to provide 'How to test' section to give opportunity to get my changes in a minute and test it, try to broke it and so on.

Sure I try giving the best quality possible for my code but I also try to help my coworkers to identify the potential problem where I can do it.

Well, never mind all my talking, Sun...

**Comment by sunix** [comment]
OK let's close this discussion it has nothing to do with the below bug, if you want we can continue in another more appropriate channel. Of course it can stay public open.
Last week, I have found 2 issues related to the tasks/che commands ... I am not hunting to find these issues, I am just facing them while using Che basic features. Don't forget that you are part of a Che team ... not Theia team. It is good that you test others PR, but we are releasing soon ... please focus on Che and Che-theia.
About this issue you have filled, workspace panel is where our users will mostly run their che commands/tasks. It is one of the central UI you have to test when you playing/contributing to any improvement related to tasks and che commands.

**Comment by RomanNikitenko** [comment]
>  Don't forget that you are part of a Che team ... not Theia team. It is good that you test others PR, but we are releasing soon ... please focus on Che and Che-theia.

Sure, one of the references - is ide2 team's PR, but in theia project - isn't it? I created sample plugin 
 and tested it to avoid regression in master branch before merge. 
Another reference - `align "configure task" and "task quick open" with vs code` will impact on our project when we align with theia master after release.  

I believe you know that we depend on theia project, the changes in theia repo impact on our project immediately. 
Somebody should track the changes, test these ones for our goals, adapt our code, discuss and to advance the interests of our project and so on (examples: 
- https://github.com/theia-ide/theia/ issues/5679#issuecomment-510074230
- https://github.com/theia-ide/theia/ issues/5747).
 
Let's close this discussion. 
thank you for understanding

**Comment by sunix** [comment]
I am not sure we want the users to edit tasks.json ... but we want the users to edit from the devfile ...

**Comment by tsmaeder** [comment]
I think the correct thing to do would be to make the "my workspace" to get all tasks of type "che" and display those under their respective components. That way it would be ensured that "Run Task..." and the view are always showing the same thing. Also, changes would be picked up via the normal task change notifications.
