### ISSUE TITLE
Import existing users from keyclock to eclipse che

### ISSUE THREAD

**Issue by rajeshm9** [eclipse-che/che#14049]
## Summary

Hi
I have Keycloak setup which have multiple users already registered.Now we have configured eclipse che and want to import existing users and create workspace through api.

We have tried with two api of eclipse che for existing user in keycloak
1. **Find User**
http://192.168.1.6:8080/api/user/find?email=rajesh%40localhost.in
Response:
{
    "message": "User with email 'rajesh@localhost.in' doesn't exist"
}

When user "rajesh" login to eclipse we are getting success response and get user details.
**Question**:  Is this mandatory for user to login to eclipse or is there are other workaround for this though API

2. **Add User** 
API not working and getting below response
"{
  "message": "User email required"
}"
[Screenshot of API  Call
![che_issue](https://user-images.githubusercontent.com/6657995/61999592-6b408a00-b0e2-11e9-8540-4747bacad843.png)
](https://drive.google.com/file/d/1Bi2woOX_rwxO6s638yNDkXgFgB5UncL0/view)

We are running eclipse che multiuser mode with following version:

INFO: (che cli): 6.0.0 - using docker 19.03.0-rc3 / native
WARN: Newer version 'rc' available
INFO: (che init): Installing configuration and bootstrap variables:
INFO: (che init):   CHE_HOST=192.168.1.6
INFO: (che init):   CHE_VERSION=6.0.0

**Comment by sunix** [comment]
@skabashnyuk could you help ?

**Comment by skabashnyuk** [comment]
My guess would be.

1. Import users.
2. Get the user token.
3. Create a workspace with the user token.

On a step 3 user would be added to che database automatically.

**Comment by rajeshm9** [comment]
@skabashnyuk Thanks for your reply. 
Users are already in keyclock database. 
We need to import or populate same users in eclipse che without first time login in che though browser. Is there way by using admin token from keyclock we can import users though api and create user workspace.

**Comment by l0rd** [comment]
@rajeshm9 did @skabashnyuk answer help? 

It looks like you are using a pretty old version of Che. If are just setting up a Che installation you should use a more recent one.

**Comment by skabashnyuk** [comment]
>Is there way by using admin token from keyclock we can import users though api and create user workspace.

@rajeshm9  the way that is working -no. However we aren't that far. 
There is a method in UserService that allows creating a user.
```
  @POST
  @Consumes(APPLICATION_JSON)
  @Produces(APPLICATION_JSON)
  @GenerateLink(rel = LINK_REL_USER)
  @ApiOperation(value = "Create a new user", response = UserDto.class)
  @ApiResponses({
    @ApiResponse(
        code = 201,
        message = "User successfully created, response contains created entity"),
    @ApiResponse(code = 400, message = "Missed required parameters, parameters are not valid"),
    @ApiResponse(code = 401, message = "Missed token parameter"),
    @ApiResponse(code = 500, message = "Couldn't create user due to internal server error")
  })
  public Response create(
      @ApiParam("New user") UserDto userDto,
      @ApiParam("Authentication token") @QueryParam("token") String token,
      @ApiParam("User type") @QueryParam("temporary") @DefaultValue("false") Boolean isTemporary)
      throws BadRequestException, UnauthorizedException, ConflictException, ServerException {

```
There is a https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/multiuser/permission/che-multiuser-permission-user/src/main/java/org/eclipse/che/multiuser/permission/user/UserServicePermissionsFilter.java#L65 that controls authorization on this method. Only users that have permission ```manageUsers``` can call this method. However, KeycloakProfileDao is blocking all ```create/update/remove``` methods. If you could experiment with KeycloakProfileDao and contribute results back I would be really grateful.

**Comment by rajeshm9** [comment]
Is there any way we can use "impersonation" api of keyclock do that task.
I am using impersonation api of keyclock and using admin token but getting 403 Forbidden error.

**http://192.168.1.7:5050/auth/admin/realms/che/users/61c0d26d-87a8-43c7-9c1b-2b203cc3fab3/impersonation**

Response:  HTTP/1.1 403 Forbidden

**Comment by skabashnyuk** [comment]
Do you get 503 on a call to keycloak?

**Comment by rajeshm9** [comment]
Hi,

Above problem is solved by creating a client having access type confidential and Service account enabled and user given relam-management role access

Now following API is working fine. USER_ID is user for which i try to impersonation

curl -v -c ${COOKIE_FILE}  -X POST "http://${IP}/auth/admin/realms/che/users/${USER_ID}/impersonation" -H "${HEADER}"

**Cookie File:**
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_192.168.1.7   FALSE   /auth/realms/che        FALSE   0       KEYCLOAK_IDENTITY       eyJhbGciOiJIUzI1NiIsImtpZCIgOiAiNTEyNzZkNGItNWI5Yi00NmJiLWE4ZjUtZmI5MzQ4NTVlMjBjIn0.eyJqdGkiOiJhNTdjODc5Yy0yODYwLTRkZjMtOTE0NS1iNWZhODRhMjdhZGUiLCJleHAiOjE1NjU2NDI2NDYsIm5iZiI6MCwiaWF0IjoxNTY1NjA2NjQ2LCJpc3MiOiJodHRwOi8vMTkyLjE2OC4xLjc6NTA1MC9hdXRoL3JlYWxtcy9jaGUiLCJzdWIiOiIzMTJlYWZmZC0wZGFjLTRiZTktYTYyZC1hNWMxYjBiOGI0MWUiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiI3YjgzY2YxZi1kOWU3LTQxMjEtYTRlZC03MTg5NzJlZWY1ZmEiLCJyZXNvdXJjZV9hY2Nlc3MiOnt9fQ.RRNLFXjlYjTWhIOu0kqdTqghxaocjjzl5VlcwXIgtlw
192.168.1.7     FALSE   /auth/realms/che        FALSE   1565642646      KEYCLOAK_SESSION        che/312eaffd-0dac-4be9-a62d-a5c1b0b8b41e/7b83cf1f-d9e7-4121-a4ed-718972eef5fa
#HttpOnly_192.168.1.7   FALSE   /auth/realms/che        FALSE   1565606646      KEYCLOAK_REMEMBER_ME

**Response:**
{"redirect":"http://192.168.1.7:5050/auth/realms/che/account/applications","sameRealm":true}

Now when i try to call next api to get imperonate user token and getting 

**Request:**
curl -v -b ${COOKIE_FILE} http://192.168.1.7:5050/auth/admin/realms/che/protocol/openid-connect/auth?response_mode=fragment&response_type=token&client_id=mytest&redirect_uri=http://192.168.1.7:5050/auth/realms/che/account/applications

**Response:**

HTTP/1.1 401 Unauthorized
