### ISSUE TITLE
When deploying che, it would make sense to select sizing

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#14051]
### Describe the solution you'd like

It would be nice if `chectl` or any other method of deployment would have a deployment size, i.e rather than setting up the PV on kubernetes not knowing which one really needs space and how much?

I'm not sure if this is relevant https://www.eclipse.org/che/docs/che-7/hosted-che.html but similar type of concept.
For example:
Small: minimum requirements 2 GB storage, 4 memory, 2 CPU for up to 2 workspaces
Medium: minimum requirements 4 GB storage, etc... for up to 6 workspaces
etc...

### Describe alternatives you've considered

I just setup 50G of storage for regardless pod that needs to be created but that's wrong and doesn't make any sense

**Comment by l0rd** [comment]
@SDAdham are you talking about configuring the size of the workspaces persistent volume? Have you tried to configure it through the che server [property `che.infra.kubernetes.pvc.quantity`](https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L449) (or the environment variable `CHE_INFRA_KUBERNETES_PVC_QUANTITY`)?

**Comment by SDAdham** [comment]
I don't know about this >> `CHE_INFRA_KUBERNETES_PVC_QUANTITY` as I'm not sure if this is documented, but my advise is that we allow users to select the sizing depending on their needs, i.e small che's environment, medium, large or xlarge for example. And depending on their selection, a deployment of che's with needed CPU cores and disk storage would be selected accordingly

**Comment by SDAdham** [comment]
This is nothing more or less than just an enhance and suggestion btw
