### ISSUE TITLE
Don't use deploy.sh&ocp.sh in test jobs on CI

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14069]
### Is your task related to a problem? Please describe.
As deploy.sh & ocp.sh will be deprecated in near future and removed, we should change our jobs to not use this.

### Describe the solution you'd like
* For openshift deployment, `oc cluster up` should be used.
* For che deployment, operator (chectl) should be used.

This is a followup of 
https://github.com/eclipse/che/issues/13888

**Comment by dmytro-ndp** [comment]
It requires creation of Multi-user Happy path tests https://github.com/eclipse/che/issues/14234

**Comment by skabashnyuk** [comment]
@rhopp I see quite a lot of users that occasionally used deploy.sh and fail.  
Is there something left that is use deploy.ch? I think it's totally outdated and error-prone. Can I create a pr and remove it?

**Comment by musienko-maxim** [comment]
I do not mind. I do not see any reasons to avoid sh. As for me we've already had all parts for adapting our tests for launching tests.

**Comment by skabashnyuk** [comment]
@rhopp where we are with this task?

CC @tolusha

**Comment by rhopp** [comment]
@SkorikSergey  ^^ ?

**Comment by SkorikSergey** [comment]
We still use `deploy.sh&ocp.sh` on https://ci.codenvycorp.com/view/qa-nightly/ jobs.

**Comment by skabashnyuk** [comment]
> deploy.sh&ocp.sh

That is unsupported tools. They didn't test CRW installation. When do you plan no use something more up to date?

**Comment by SkorikSergey** [comment]
> > deploy.sh&ocp.sh
> 
> That is unsupported tools. They didn't test CRW installation. When do you plan no use something more up to date?

After moving `qa-nightly` jobs to CentOS CI.

**Comment by rhopp** [comment]
This depends on https://github.com/eclipse/che/issues/15517 (will be done as part of this)

**Comment by tolusha** [comment]
@rhopp @musienko-maxim @dmytro-ndp 
Is there any missed functionality that you need from `deploy.sh`

**Comment by rhopp** [comment]
We are now officially not using this anymore! Woohooo!

**Comment by skabashnyuk** [comment]
![4860186](https://user-images.githubusercontent.com/1614429/74959055-37c0a680-540a-11ea-9dbf-dcb2f6b580e9.jpg)
