### ISSUE TITLE
Enable email listener in Keycloak

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#14060]
With earlier versions of Keycloak, it would listen and send emails for events such as failed login attempt, user password change, etc.
While we still have the templates for emails in our Keycloak image, they're not used anymore, since this event listener must be enabled in Realm settings

**Comment by l0rd** [comment]
@skabashnyuk @mkuznyetsov I am ok with `P1` but how hard is to fix? Is there any risk of regression if we put that in `7.0.0`? Is that reasonable to target Che `7.0.0`?

**Comment by mkuznyetsov** [comment]
@l0rd the fixiis here for realm template, although this will apply only for the "newer" Keycloak deployments, i.e. if realm has not been initialized:
https://github.com/eclipse/che/pull/14064

For already existing installations of Keycloak it could be set manually either in Administration console -> Events -> Config -> Events Listeners -> add "email" listener, or through admin CLI on Keycloak pod `./opt/jboss/keycloak/binkcadm.sh update events/config -r che -s 'eventsListeners=["jboss-logging", "email"]'`

**Comment by skabashnyuk** [comment]
@l0rd I would say that is a bug and it should be fixed in 7.0.0
