### ISSUE TITLE
Add eslint to Typescript language support plugins

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14070]
When building theia, there are numerous rules from tslint being enforced, however, even though there is a vs code extensions for tslint, it's not included in our typescript support (https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin)
This leads to many cases where we only find build problems when running the command line build.

We should find a way to offer tslint support for Che.

**Comment by tsmaeder** [comment]
Since there is no vsix in the release, we need to host the file somewhere (in redhat-developer or so).

**Comment by tsmaeder** [comment]
Turns out this one is blocked by: Plugins should have ability to spawn processes #15087

**Comment by RickJWagner** [comment]
Thank you for working on this issue.  
I'd like to add a '+1' to the request for TSLint, we are hearing from CRW users that have the same request.

**Comment by benoitf** [comment]
just a FYI but tslint is deprecated over eslint now

**Comment by ericwill** [comment]
I've renamed the issue, instead of tslint we will be providing the eslint extension: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by vitaliy-guliy** [comment]
ES Lint is already introduced to built-ins plugin with PR https://github.com/eclipse/che-theia/pull/902
To test how it works see https://github.com/eclipse/che-plugin-registry/pull/687#issuecomment-726183847

**Comment by benoitf** [comment]
it should be a built-in extension
it needs to be removed by default and added as separate extension

**Comment by ericwill** [comment]
It's a built-in in theia, why remove it in che-theia and make more work for ourselves to have it as a separate plugin?

**Comment by azatsarynnyy** [comment]
I propose to look at it from a bit different perspective :slightly_smiling_face: :
why do we need to launch JavaScript linting extension with every Che Workspace no matter what stack it's based on - Java, go, Python, PHP, etc.?

**Comment by ericwill** [comment]
Fair enough. @vitaliy-guliy, this one is back on your plate.

**Comment by vitaliy-guliy** [comment]
ES Lint 2.1.1 was added to Che plugin registry with https://github.com/eclipse/che-plugin-registry/pull/687
