### ISSUE TITLE
Java support: Java refactoring rename doesn't work.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14072]
### Describe the bug
Java support: Java refactoring rename doesn't work.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create new workspace from maven devfile
2. Open HelloWorld.java file in the editor.
3. Select java class name HelloWorld type shortcut to rename F2, type new name for class and click Enter.

### Actual behavior
Java class and file HelloWorld was not renamed.

### Expected behavior
Java class HelloWorld and file HelloWorld.java should be renamed

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by slemeur** [comment]
@tolusha : Can you check please ?

**Comment by svor** [comment]
The problem is related to Theia-Monaco where changes should be applied. 
https://github.com/theia-ide/theia/issues/5841

**Comment by tsmaeder** [comment]
Removing 7.0 label because we don't control the timeline here: Monaco update is work in progress on the theia side.
