### ISSUE TITLE
Python plugin randomly crashes

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14074]
### Describe the bug
When using both the `python-simple` and `python-django` devfiles, I get random crashes for the python language server container (disappears, OpenShift says exit code 1). In the container logs, I see

```

Info Python Extension: 2019-07-30 16:54:55: Get language server folder name, Class name = f, completed in 2ms, Arg 1: <Uri:/projects>, Return Value: "languageServer.0.3.43"
--
  | events.js:174
  | throw er; // Unhandled 'error' event
  | ^
  |  
  | Error: spawn /tmp/vscode-unpacked/ms-python.python.latest.tlnvuvjhxp.ms-python-release.vsix/extension/languageServer.0.3.43/Microsoft.Python.LanguageServer ENOENT
  | at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
  | at onErrorNT (internal/child_process.js:415:16)
  | at process._tickCallback (internal/process/next_tick.js:63:19)
  | Emitted 'error' event at:
  | at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
  | at onErrorNT (internal/child_process.js:415:16)
  | at process._tickCallback (internal/process/next_tick.js:63:19)
```

Additionally, sometimes I see a prompt at the top:

> Try out Preview of our new Python Language Server to get richer and faster IntelliSense completions, and syntax errors as you type.

which I assume is inappropriate for Che.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

I don't have a consistent reproducer; it occurs within 50 seconds of workspace start, on every start.

### Expected behavior
Working python language features

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
      - (OSIO)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (OSIO) 

   - [ ] other: please specify

**Comment by amisevsk** [comment]
Additionally, I get a prompt

> A new process is now listening on port 2503 but this port is not exposed in the workspace as a server.
Would you want to add a redirect for this port so it becomes available ?

At the top of the window; exposing this port just leads to a webpage that says "Upgrade required"

**Comment by ibuziuk** [comment]
@svor could you please take a look ?

**Comment by svor** [comment]
Is this something related to https://github.com/eclipse/che/issues/13599?

**Comment by amisevsk** [comment]
@svor The issue is not with the server trying to start AFAICT, but rather that it's trying to update itself like it would on vscode. The python language server was working for me last week, but I was getting prompts to "update the plugin" in theia. I suspect the issue is that it's forcing the update now.

I see that #13599 has been reopened so it may be reproducing the same issue now, but the initial description and discussion do not match as far as I can tell.

**Comment by amisevsk** [comment]
It appears that this issue is caused by clicking the "Try it now!" on the prompt that appears when starting a workspace:

![Screenshot from 2019-08-13 13-39-36](https://user-images.githubusercontent.com/16168279/62963951-00749b80-bdd0-11e9-9f5f-c475f716f626.png)

This creates the entry `   "python.jediEnabled": false` in the user preferences, which causes the crashing. As a workaround, the setting can be removed and the workspace restarted.

From an end-user perspective, pressing the "Try it now!" button is a normal thing to do, and the resulting error is very hard to diagnose.

**Comment by tolusha** [comment]
My assumption is that some package is missed in the container.
Docker file [1] for python is huge. We have to start with refactoring here:
1. Find appropriate base image in the registry
2. Installed required packages `ptsvd`, `pylint`, `python-language-server[all]`, `jedi` 
3. Find and installed missed ones

[1] https://github.com/eclipse/che-theia/blob/ab/scc/dockerfiles/remote-plugin-python-3.7.3/Dockerfile#L122
[2] https://hub.docker.com/_/python
