### ISSUE TITLE
VPN + eclipse che :  workspace agent unable to ping the Che server

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#1408]
Hello, I tried to run eclipse che behind a VPN (Cisco AnyConnect on Ubuntu by launching /opt/cisco/anyconnect/bin/vpn). But as soon as I connect and relaunch che the workspace agent cannot ping the Che server at http://che-host:8080/ide/api/. Then, I disconnect and have the same error. Do you have any idea of what could break? What is needed to access this address?

[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2016-06-01 10:13:47,108[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.29
[STDOUT] 2016-06-01 10:13:47,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Nov 20 2015 09:18:00 UTC
[STDOUT] 2016-06-01 10:13:47,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.29.0
[STDOUT] 2016-06-01 10:13:47,112[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2016-06-01 10:13:47,113[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.13.0-74-generic
[STDOUT] 2016-06-01 10:13:47,113[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2016-06-01 10:13:47,113[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_45/jre
[STDOUT] 2016-06-01 10:13:47,113[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_45-b14
[STDOUT] 2016-06-01 10:13:47,114[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2016-06-01 10:13:47,114[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2016-06-01 10:13:47,114[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2016-06-01 10:13:47,115[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2016-06-01 10:13:47,115[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2016-06-01 10:13:47,116[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2016-06-01 10:13:47,116[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx1024m
[STDOUT] 2016-06-01 10:13:47,116[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2016-06-01 10:13:47,117[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2016-06-01 10:13:47,117[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2016-06-01 10:13:47,118[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2016-06-01 10:13:47,118[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2016-06-01 10:13:47,118[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2016-06-01 10:13:47,119[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2016-06-01 10:13:47,119[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2016-06-01 10:13:47,119[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2016-06-01 10:13:47,120[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2016-06-01 10:13:47,120[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2016-06-01 10:13:47,263[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-06-01 10:13:47,277[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2016-06-01 10:13:47,279[main]             [INFO ] [o.a.catalina.startup.Catalina 587]   - Initialization processed in 375 ms
[STDOUT] 2016-06-01 10:13:47,324[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2016-06-01 10:13:47,324[main]             [INFO ] [o.a.c.core.StandardService 433]      - Starting service Catalina
[STDOUT] 2016-06-01 10:13:47,325[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.29
[STDOUT] 2016-06-01 10:13:47,374[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[STDOUT] 2016-06-01 10:13:53,828[ost-startStop-1]  [ERROR] [piEndpointAccessibilityChecker 62]   - connect timed out
[STDOUT] java.net.SocketTimeoutException: connect timed out
[STDOUT]    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_45]
[STDOUT]    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_45]
[STDOUT]    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_45]
[STDOUT]    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_45]
[STDOUT]    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_45]
[STDOUT]    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_45]
[STDOUT]    at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[na:1.8.0_45]
[STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_45]
[STDOUT]    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_45]
[STDOUT]    at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:239) ~[che-core-api-core-4.0.0-RC11.jar:4.0.0-RC11]
[STDOUT]    at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:145) ~[che-core-api-core-4.0.0-RC11.jar:4.0.0-RC11]
[STDOUT]    at org.eclipse.che.wsagent.server.ApiEndpointAccessibilityChecker.start(ApiEndpointAccessibilityChecker.java:57) ~[classes/:4.0.0-RC11]
[STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
[STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
[STDOUT]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
[STDOUT]    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
[STDOUT]    at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44) [che-core-commons-inject-4.0.0-RC11.jar:4.0.0-RC11]
[STDOUT]    at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) [guice-4.0.jar:na]
[STDOUT]    at com.google.inject.Guice.createInjector(Guice.java:96) [guice-4.0.jar:na]
[STDOUT]    at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137) [everrest-integration-guice-1.12.1.jar:na]
[STDOUT]    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) [guice-servlet-4.0.jar:na]
[STDOUT]    at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:84) [everrest-integration-guice-1.12.1.jar:na]
[STDOUT]    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4793) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.29]
[STDOUT]    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795) [catalina.jar:8.0.29]
[STDOUT]    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
[STDOUT]    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
[STDOUT]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
[STDOUT]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
[STDOUT]    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
[STDOUT] 2016-06-01 10:13:53,829[ost-startStop-1]  [ERROR] [piEndpointAccessibilityChecker 65]   - The workspace agent has attempted to start, but it is unable to ping the Che server at http://che-host:8080/ide/api/
[STDOUT] 2016-06-01 10:13:53,829[ost-startStop-1]  [ERROR] [piEndpointAccessibilityChecker 66]   - The workspace agent has been forcefully stopped. This error happens when the agent cannot resolve the location of the Che server. This error can usually be fixed with additional configuration settings in /conf/che.properties. The Che server will stop this workspace after a short timeout. You can get help by posting your config, stacktrace and workspace /etc/hosts below as a GitHub issue.
[STDOUT] 2016-06-01 10:13:53,829[ost-startStop-1]  [INFO ] [piEndpointAccessibilityChecker 74]   - Workspace /etc/hosts: 127.0.0.1  localhost
[STDOUT] ::1    localhost ip6-localhost ip6-loopback
[STDOUT] fe00::0    ip6-localnet
[STDOUT] ff00::0    ip6-mcastprefix
[STDOUT] ff02::1    ip6-allnodes
[STDOUT] ff02::2    ip6-allrouters
[STDOUT] 172.17.0.1 che-host
[STDOUT] 172.17.0.2 b6fb74589ed4
[STDOUT]

**Comment by ghost** [comment]
@agnesagnes workspaces agent is trying to ping workspace master 172.17.0.1

You may need to override this IP in /conf/che.properties, so that 

`machine.docker.che_api.endpoint=http://che-host:${SERVER_PORT}/wsmaster/api`

becomes

`machine.docker.che_api.endpoint=$IP:${SERVER_PORT}/wsmaster/api`

where $IP is the server IP where Che is launched. Note that 8080 port has to be opened.

**Comment by agnesagnes** [comment]
Hello, 
I did as you said but I still have the same error (with the server IP replacing che-host of course). 
When I curl http://$IP:8080/ide/api/ in the workspace container, it says "Failed to connect to $IP port 8080: No route to host". 

I run che with:
docker run -ti -e CHE_DOCKER_MACHINE_HOST=$IP --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage che

**Comment by james10174** [comment]
@agnesagnes 
You are also getting the following error.

[STDOUT] 2016-06-01 10:13:47,374[ost-startStop-1] [INFO ] [o.a.c.startup.HostConfig 916] - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[STDOUT] 2016-06-01 10:13:53,828[ost-startStop-1] [ERROR] [piEndpointAccessibilityChecker 62] - connect timed out
[STDOUT] java.net.SocketTimeoutException: connect timed out

Try increasing your timeout time. in che.conf change machine.ws_agent.max_start_time_ms=60000 to machine.ws_agent.max_start_time_ms=600000. The ide.war takes the most time to load. On slower machines this can sometimes take longer than 1 minute which would cause the error. Also it looks like it only took 6 seconds to reach the timeout. Is your machine.ws_agent.max_start_time_ms=6000?

If above doesn't work change che to codenvy/che. Take a look at "RUN CHE ON PUBLIC IP ADDRESS" at [https://eclipse-che.readme.io/v4.3/docs/usage-docker](url). Try the following. Make sure to put che.conf back to machine.docker.che_api.endpoint=http://che-host:${SERVER_PORT}/wsmaster/api  before running command.

docker run --net=host --name che -v /var/run/docker.sock:/var/run/docker.sock  -v /home/user/che/lib:/home/user/che/lib-copy  -v /home/user/che/workspaces:/home/user/che/workspaces  -v /home/user/che/storage:/home/user/che/storage  codenvy/che --remote:$IP

**Comment by agnesagnes** [comment]
@james10174 , this was exactly my previous configuration and it was not working. Yes I also tried  increasing my timeout.

**Comment by james10174** [comment]
@agnesagnes  Seems like firewall or network issue. Can you run on localhost without issues by removing --remote?

**Comment by ghost** [comment]
@agnesagnes can you try disabling iptables and give it a try again? This is a Docker + local networking issue. For some reason, a container cannot reach the server it's launched at.

There's a simple test that you can do:
1. `docker run -d --net=host nginx` This will launch nginx container and you should see a starting page on port 80.
2. `docker run -ti nginx bash` This want you launch yet another container and get a shell into in. When in the container try to curl $publicIP:80 i.e. get the starting nginx page.

By the way, have you tried running Che natively as a server?

**Comment by agnesagnes** [comment]
Hello, I think we can close the issue as it was not Che related! I just installed a diferent VPN client and it worked. So I think my previous installation was messing with the network, for a reason I absolutely ignore...
Thank you for your help, and sorry for the "non che problem"!
