### ISSUE TITLE
In hosted mode, browser tab has 'undefined' title

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14085]
### Describe the bug
I use Che in Che development and get `undefined` title for browser tab of the second instance of Che.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.0.0-rc-4.0

### Steps to reproduce
1. Start Che, clone theia and che-theia projects
2. Run `che:theia init -d` command in the root of theia repo
3. build theia project
4. Go to `/projects/theia/examples/assembly` and run `yarn theia start --hostname=0.0.0.0 --port=3130 --plugins=local-dir:../../../che-theia/plugins` command
5. Go to `My workspace` panel and open in a new tab the reference for `theia-dev`.
6. You can see that the tab has `undefined` title.
7. Open some project or workspace - the title is changed to `theia-undefined`

### Expected behavior
The tab has more valuable title. 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (v1.0.0)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
Please see the video: https://youtu.be/75wqNzfKays 

### Installation method
   - [x] chectl chectl/0.0.2-6d3894f linux-x64 node-v10.4.1
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by slemeur** [comment]
should be an easy fix to get prioritized @evidolob
