### ISSUE TITLE
node.js sample from node devfile contains node_modules in the source code

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14080]
### Describe the bug
node.js sample from node devfile(https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/nodejs/devfile.yaml#L10) contains node_modules folder in the source code  It's looks strange . In most case node developers exclude such folder from source code and use package.lock.json or yarn.lock to freeze transitive dependencies, or to use transitive dependencies without security vulnerabilities.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create new workspace from node devfile "NodeJS Express Web Application"
2. Open source code project nodejs-web-app

### Expected behavior
Sample should has node_modules excluded in the .gitignore file and we should have a command in the devfile to get node dependencies ('npm install') or 'npm install' should be embedded to the application start devfile command.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by slemeur** [comment]
@AndrienkoAleksandr : Would you recommand another sample nodejs project to provide?

**Comment by amisevsk** [comment]
@slemeur I believe we could remove `node_modules` since we own the repo, I was planning on opening a PR for that and other changes to sample projects at some point (e.g. the [web-java-spring](https://github.com/che-samples/web-java-spring) sample project readme is out of date.

Do you think cleaning up sample projects is something useful for 7.0.0?

**Comment by AndrienkoAleksandr** [comment]
+1 To clean sample projects.

**Comment by slemeur** [comment]
It is useful, but I don't think it is high priority, but as it's something fairly quick to handle we could take it.

**Comment by amisevsk** [comment]
@slemeur @AndrienkoAleksandr I've created a few cleanup pull requests for our sample projects:
- https://github.com/che-samples/web-nodejs-sample/pull/3
- https://github.com/che-samples/web-java-vertx/pull/2
- https://github.com/che-samples/dotnet-web-simple/pull/1
- https://github.com/che-samples/console-java-simple/pull/10

Most are minor cleanup to smooth user experience when playing around with them (correct .gitignore, etc). I don't have access to these repos, so someone else would have to approve + merge them.

**Comment by AndrienkoAleksandr** [comment]
@amisevsk @sleshchenko Take a look, please https://github.com/eclipse/che/issues/14080 . node_modules was removed , but devfile was not improved according to this change.

**Comment by sleshchenko** [comment]
@AndrienkoAleksandr @amisevsk Can it be closed now?
