### ISSUE TITLE
Disable self registration of users by default

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14083]
### Is your enhancement related to a problem? Please describe.
When setting-up remotely a che instance, this instance allows self-registration by default

### Describe the solution you'd like
Would be nice that user is aware or that it is turned off by default by chectl or something else

**Comment by l0rd** [comment]
@benoitf I guess that this issue is not for openshift (where OpenShift OAuth is automatically setup) right? And if we turn off self-registration Keycloak, how a user will be added to Che?

**Comment by benoitf** [comment]
@l0rd it's when you use default option of chectl to install Eclipse Che on a remote instance: anyone can register on this instance by having the che server URL.
It should be opposite by default and admin user having random password.

**Comment by tolusha** [comment]
To disable registration we need to set it to false
https://github.com/eclipse/che-operator/blob/master/templates/keycloak_provision#L13

**Comment by tolusha** [comment]
Self registration is disabled by default.
To enable it is needed to set `User registration` on `login` page to `On`

![Screenshot from 2020-09-17 13-41-41](https://user-images.githubusercontent.com/1640675/93460198-8a543980-f8eb-11ea-92ed-dd5c48425248.png)
