### ISSUE TITLE
Get rid of 'machine' related terms 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14081]
### Is your enhancement related to a problem? Please describe.
"Machine" has been deprecated and should not be used anywhere in Che anymore.
So we should review our code and use another terms for that. 

For example, at the moment task plugin gets info about target container by API as attribute of command `machineName` and provides this one for machine exec. So at least for task-plugin, machine exec and for che objects changes are required.
 
Although we display that field as `containerName` for user, we still use terms `machineName` and `machine` in our code. Would be nice to replace these ones with more appropriate terms.

We decided not to do such refactoring before GA, but we should consider to do it after.

**Comment by slemeur** [comment]
Compatibility will need to be handled.
