### ISSUE TITLE
[docs] Documentation for overriding all the involved images for the airgap scenario

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14088]
### Is your enhancement related to a problem? Please describe.

As noted in https://github.com/eclipse/che/issues/13886 we can override many of the Che images at deploy time via a custom resource yaml.

- cheImage
- postgresImage
- identityProviderImage
- pvcJobsImage
- devfileRegistryImage
- pluginRegistryImage

But this does not include ALL the images. The following are missing:

- Che Theia image
- Che plugin broker image
- Che JWT proxy
- Che Theia endpoint runtime image
- Che remote plugins (eg., openshift connector, kubernetes tooling, java8, java11)

### Describe the solution you'd like

Add more fields to the CR, and have those supported when using chectl to deploy Che.

### Additional context

This is in support of offline/airgap scenarios, where we can't just pull random container images from quay/rhcc, but need to set specific ones within an organization (or specific productized ones). 

See also 

- https://issues.jboss.org/browse/CRW-318 
- https://issues.jboss.org/browse/CRW-240

**Comment by davidfestal** [comment]
In a number of cases, I assume that for now you can change them by simply adding the corresponding environment variable in the `custom` config map.
I did it just today for the plugin-broker docker image.
But sure, this is not integrated with chectl, and is not really easy to use

**Comment by slemeur** [comment]
Installations that is concerned by this issue are: from chectl and from operatorhub

**Comment by ibuziuk** [comment]
@nickboldt please clarify why it is P1, moved to 7.x atm

**Comment by nickboldt** [comment]
Need this for offline / airgap, so P1/blocker.

**Comment by davidfestal** [comment]
After issue https://github.com/eclipse/che/issues/13886#issuecomment-534171945 is fixed, this issue should mainly consist in providing some scenario-oriented documentation, dedicated to the offline / airgap mode.
Do you agree @nickboldt ?

**Comment by nickboldt** [comment]
Yes, that would be great for Che 7 and would work as the baseline from which to create CRW 2 docs too.

Related downstream issues:
* https://issues.jboss.org/browse/CRW-303 migration 1.2 -> 2.0
* https://issues.jboss.org/browse/CRW-240 offline scenarios

**Comment by nickboldt** [comment]
Related issues:
* https://github.com/eclipse/che/issues/14589
* https://github.com/eclipse/che/issues/14186

**Comment by ibuziuk** [comment]
@nickboldt I'm going to close this one in favor of https://github.com/eclipse/che/issues/14866
Are you ok with that ?
