### ISSUE TITLE
References to commits are broken in Help -> About dialog

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14092]
### Describe the bug
Help -> About dialog contains references for commits to theia and che-theia projects
The references are broken at the moment for master branch assembly (eclipse/che-theia:next)

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: eclipse/che-theia:next

### Steps to reproduce
1. Add to a devfile the section:
```
- 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
    type: cheEditor
```
2. Start a workspace from the devfile
3. Go to Help -> About dialog and try references to theia and che-theia projects
4. You can see `https://github.com/theia-ide/theia/commit/N/A` in an address line of a browser and error: 404 Page not found

### Expected behavior
The references link to relevant commits

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube v1.0.0
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![page_not_found](https://user-images.githubusercontent.com/5676062/62281101-d200d300-b455-11e9-918c-99ebe48ee1e0.png)

### Installation method
   - [x] chectl chectl/0.0.2-6d3894f linux-x64 node-v10.4.1
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@RomanNikitenko are you planning to work on this issue for Che 7 GA ?

**Comment by RomanNikitenko** [comment]
The issue is relevant for eclipse/che-theia:next, so for master branch assembly, I don't think we need it for GA.

**Comment by ibuziuk** [comment]
moving to `7.1.0` milestone

**Comment by mmorhun** [comment]
Fixed

**Comment by RomanNikitenko** [comment]
I can reproduce it again for `che-theia` commit reference: https://youtu.be/u3ZM5biGC_M

@mmorhun  could you take a look?

**Comment by mmorhun** [comment]
I think this is fixed again by https://github.com/eclipse/che-theia/pull/487
