### ISSUE TITLE
Dashboard is incorrectly representing devfile sizes if defined in GiB

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#14096]
### Describe the bug
When using the latest version of the devfile registry, the images which are using `GiB` in their meta.yaml instead of `MiB` are being rounded up to 0GiB by the frontend.

### Che version

 - [x] latest
 - [ ] nightly
 - [x] other: Che7.0.0-rc-4.0

### Steps to reproduce

Open create-workspace tab
Look for Java Springboot or Java MySQL
The required size is 0Gi

### Expected behavior
Dashboard will correctly represent the devfile required size

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: Hosted Che @ che.prod-preview.OSIO

### Screenshots
![image](https://user-images.githubusercontent.com/16451875/62295845-434c8000-b46e-11e9-817e-1e9e86ed93d6.png)

### Installation method
   - [x] chectl --platform minishift
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other OSIO SAAS
   - [ ] other: please specify

**Comment by amisevsk** [comment]
Workaround PR: https://github.com/eclipse/che-devfile-registry/pull/70

**Comment by ibuziuk** [comment]
PR with workaround was merged - https://github.com/eclipse/che-devfile-registry/pull/70
moving to `7.1.0`

**Comment by ibuziuk** [comment]
Pointer to the UD code that does conversion https://github.com/eclipse/che/blob/0e06a2b57fff4b55d8a38c300cf8a8a910dfae23/dashboard/src/app/workspaces/create-workspace/devfile-selector/devfile-selector.html#L59

**Comment by ScrewTSW** [comment]
Confirmed fixed. closing.
