### ISSUE TITLE
Registries MemoryLimit is too low and deployment fails on OpenShift

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14093]
### Describe the bug

Currently the memory max limits for the plugin and devfile pods are set to 32Mi. On some OpenShift clusters that is not allowed: the minimum is 256Mi.

### Che version

`7.0.0-rc-4.0`

### Steps to reproduce

Use the operatorhub to deploy Che on openshift online

### Expected behavior

Che is deployed

### Runtime

OS 4

### Installation method

OperatorHub

### Environment

Cloud: openshiftworkshop.com

**Comment by skabashnyuk** [comment]
Can we set a limit to 0? WDYT?

**Comment by l0rd** [comment]
Discussing with @davidfestal that has debugged the problem it looks like the solution would be to set memory request to 16Mi and limit to 256Mi. 

@skabashnyuk I am not sure that this should be fixed Helm side as well (since it's an OpenShift specific problem) but it maybe worth be consistent on both platforms.

**Comment by davidfestal** [comment]
More precisely the idea is the keep the memory request (= min memory) to 16Mi, but increase the memory limit (= max memory) to 256Mi to satisfy a common Openshift cluster configuration.

**Comment by davidfestal** [comment]
So +1 to do that for Openshift only at first.

**Comment by skabashnyuk** [comment]
Removed team/platform since helm is not in the scope

**Comment by l0rd** [comment]
@skabashnyuk as I said in the comment above helm and operator should be consistent. Helm is in scope by the helm part is not a blocker. You can create a new issue about that or use this one and re-apply your team label

**Comment by ibuziuk** [comment]
PR merged - https://github.com/eclipse/che-operator/pull/64
Should be fixed with the next operator release
