### ISSUE TITLE
Adaptation for tasks is required

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14098]
The bug is relevant for **eclipse/che-theia:next**, so for **master** branch assembly.

### Describe the bug
After alignment theia tasks with vs code behavior we need some adaptation on our side.

 I still can run che tasks, but at least:
- configure task action is not working
- detected tasks are displayed in different way
- after page refreshing `Terminal` -> `Run Task` menu action is triggered only on second click
Please see the video:  https://youtu.be/DXe_R-ubxa8

I tested it on theia side and it works well.
Looks like some changes for task definitions are required on our side. 

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: eclipse/che-theia:next

### Steps to reproduce
1. Add to a devfile the section:
```
- 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
    type: cheEditor
```
2. Start a workspace from the devfile
3. Go to Terminal -> Run task 
You can see that for `detected` tasks the `type` of the task is used, not `source` (for example, `shell` instead of `npm` )
4. Try to configure a `detected` task - click on `cog` icon - the configuration should be copied to `tasks.json` file, but nothing is happen.

### Expected behavior
- ability to configure a `detected` tasks
- `source` field is used for displaying of `detected` tasks
- after page refreshing `Terminal` -> `Run Task` menu action is triggered on first click 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube v1.0.0
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
Actual displaying
![actual](https://user-images.githubusercontent.com/5676062/62298629-07201c00-b47c-11e9-847a-ba9bd145c7fc.png)

Expected displaying
![expected](https://user-images.githubusercontent.com/5676062/62299017-cbd21d00-b47c-11e9-9dd3-7e6c6913c4c2.png)

### Installation method
   - [x] chectl chectl/0.0.2-6d3894f linux-x64 node-v10.4.1
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by vparfonov** [comment]
cc @slemeur I think we need to take it for 7.1 
WDYT?

**Comment by ibuziuk** [comment]
@slemeur moved to `7.1.0` for now

**Comment by RomanNikitenko** [comment]
I added in the description of the issue one more use case related to `Terminal` -> `Run Task` menu.
The video for the case is available as well.

The bug was caused by last changes on theia repo. I can not reproduce it for theia project, so some changes are required on che-theia side.

**Comment by RomanNikitenko** [comment]
I investigated the issue: the bugs related to `detected` tasks are caused by using `7.0.0-next` version of `eclipse/che-theia-endpoint-runtime` for remote plugins. `7.0.0-next` version doesn't contain `activateByEvent` logic.

So the issue is fixed by using `next` version of `eclipse/che-theia-endpoint-runtime` for remote plugins.
