### ISSUE TITLE
Bring to order build scripts in eclipse/che-theia

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14094]
### Is your enhancement related to a problem? Please describe.

We have a mess with build scripts in eclipse/che-theia repository. It's not clear which script is responsible for what. There is `build.sh` in the root, in the `dockerfiles` directory and the same script for each dockerfile. Readme in `dockerfiles/che-theia` describes only how to build Che-Theia, but should be placed in `dockerfiles` directory and describe how to build all the dockerfiles.

### Describe the solution you'd like

- [ ] remove unused `/build_and_push_docker_images.sh` from the root
- [ ] remove unised `/dockerfiles/build.sh`
- [ ] include `/docker_image_build.include` in `/build.sh`
- [ ] move `/dockerfiles/theia/README.md` readme to `/dockerfiles/README.md`
- [ ] update the `README.md`, add a few worlds describing each docker image.

**Comment by ibuziuk** [comment]
@vitaliy-guliy I put `7.x` for now please discuss the issue with team lead and prioritize accordingy

**Comment by benoitf** [comment]
@vitaliy-guliy 
>  remove unised /dockerfiles/build.sh


I think it's odd. I expect that if I need to build all docker images to run a command from the directory that is there.
Rebuild the full project: build from root/top directory
Rebuild only the images: build from `dockerfiles` directory

etc.
