### ISSUE TITLE
chectl: --domain is ignored if minikube/minishift platform is enabled

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14095]
### Describe the bug
I configured domain on DNS server to point to my virtual box IP, but `chectl` ignores --domain and use `minishift/minikube ip` + `nip.io`

### Che version

 - [ ] latest
 - [X] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Execute
```bash
chectl server:start --installer=operator --platform=minikube --tls --multiuser --domain=test.com
```
2. Check the logs that chectl computes domain automatically and overrides user-defined.

### Expected behavior
test.com is used as ingress domain

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot_20190801_154956](https://user-images.githubusercontent.com/5887312/62294613-071c1e00-b474-11e9-86bc-4b8a56bb7159.png)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@sleshchenko this looks like not crutial for GA, moving to `7.1.0`

**Comment by ibuziuk** [comment]
oh, I see PR already sent - https://github.com/che-incubator/chectl/pull/239

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/che-incubator/chectl/pull/239
