### ISSUE TITLE
Workspace Not Loaded On Che Start

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1410]
The workspaces in the <che directory>/workspaces/ are not loading after restarting che server. It is not available in the workspaces list. Workspace wksp-48cm that I created before I restarted is not available.

![image](https://cloud.githubusercontent.com/assets/16562450/15713625/ceaf3984-27dc-11e6-82f3-ff138d954dac.png)
![image](https://cloud.githubusercontent.com/assets/16562450/15713648/e0ff1d20-27dc-11e6-8b94-d9bfa762b4d9.png)

Also I am not sure what import an existing workspace configuration does but it does not seem to be working. I am using the nightly from yesterday.

![image](https://cloud.githubusercontent.com/assets/16562450/15713747/4a1cdcc0-27dd-11e6-8458-e639a5b305ac.png)

**Comment by ghost** [comment]
@james10174 

Difficult to say why that happened. Workspaces are stored in `/storage/workspaces.json` while `/workspaces` folder stores projects that are then mounted into `/projects` into a container.

As to importing a workspace, you need a json with a workspace definition. You may want to take a look at `/storage/workspaces.json`

You may change this default location by overriding `che.conf.storage` property.

**Comment by ghost** [comment]
@james10174 it is generated after Che starts for the first time. I cannot reproduce this one.

Do you perhaps have CHE_LOCAL_CONF_DIR exported?

**Comment by james10174** [comment]
@eivantsov I created a normal user and everything works now. I think the problem is running as root. Problem not a good idea to run as root anyways.
