### ISSUE TITLE
Jenkins job is green but in pull request it displayes in the "Pending status"

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14108]
### Describe the bug
Jenkins job is green but in pull request, it displayes in the "Pending status"

![Screenshot from 2019-08-02 17-42-30](https://user-images.githubusercontent.com/22724619/62378310-36eb2480-b54d-11e9-9602-edb67a83f40f.png)

![Screenshot from 2019-08-02 17-43-19](https://user-images.githubusercontent.com/22724619/62378320-39e61500-b54d-11e9-8512-1b5c72a072b7.png)

**Comment by dmytro-ndp** [comment]
That is known problem. The reason that API rate limit exceeded personal GitHub account which we uses for the job which check PR.

**Comment by dmytro-ndp** [comment]
This issue is related to #14068.

**Comment by benoitf** [comment]
@dmytro-ndp BTW I don't see why `che-bot` would help. it's still a github issue and the same limit will apply. che-bot should only be used when write access is used, for read operations you should use other tokens to lower the rate API limit.

**Comment by dmytro-ndp** [comment]
It requires write access as well - to set PR check status and to leave comment. That was a reason to request `che-bot` for Codenvy CI https://bugs.eclipse.org/bugs/show_bug.cgi?id=536913 , and here, on CRW CI we are having the same task.

**Comment by dmytro-ndp** [comment]
[Jenkins job](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9) has been switched to use `che-bot`.

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp could you close this issue if bug not reproduce

**Comment by dmytro-ndp** [comment]
PR check Jenkins job hasn't run into that problem during the day after switching to `che-bot` account, so I am closing the issue as resolved.
