### ISSUE TITLE
chectl: Che server is not configured properly if tls is enabled and operator is used for k8s platform

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14102]
### Describe the bug
Che server is not configured properly if tls is enabled and operator is used for k8s platform

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che on K8s cluster with chectl with tls and operator configured.
2. Check that ingresses use self-signed certificates instead of pre-created `che-tls` secret.

### Expected behavior
Ingresses use pre-created `che-tls` secret for TLS.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
Fix is already under Draft phase https://github.com/che-incubator/chectl/pull/241

**Comment by rhopp** [comment]
To me, this issue doesn't seem too critical, as users should be able to configure everything by CheCluster CR yaml (chectl switch `--che-operator-cr-yaml`). 
Is this really the approach we want to take? I think mixing switches like `--tls` and `--che-operator-cr-yaml` is not the best idea.
@l0rd @benoitf WDYT?

**Comment by sleshchenko** [comment]
> Is this really the approach we want to take? I think mixing switches like --tls and --che-operator-cr-yaml is not the best idea.

@rhopp I agree with you but the current implementation allows you to run
```
chectl server:start --platform=kubernetes --installer=operator --tls
``` 
And you won't get any hint that it supposed by fail because of incorrect parameters propagation by chectl.

I would merge quick fix https://github.com/che-incubator/chectl/pull/241
and then improve and maybe deny mixing installing parameters and provided `cr-yaml` 
or deny specifying parameters when an operator is used - which I guess makes harder to start with the installer because you have to know CR structure and prepare Che.

**Comment by sleshchenko** [comment]
@rhopp Do you think we can assign 7.1.0 milestone for this issue?
