### ISSUE TITLE
Make devfile feature to be overridden

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#14117]
### Usage Scenario
Please consider the following usage scenario for eclipse/che:
1.Every user will need one workspace - it would be created when the user logs in and gets destroyed when the user logs-out/inactive.
2.If there are 50 users logged in, there would be 50 workspaces (one per user). All these workspaces shall be created using the same devfile (i.e., editor/tools are same)
3.but projects that the individual users see would be different - the projects shall come from database based on user login.
4.Guest users can also open the ide without logging in (and login later after opening the ide)

### The solution I'd like
I shall set CHE_LIMITS_USER_WORKSPACES_RUN_COUNT to '1' and this would allow having only one running workspace per user => This, I believe, would result in an error (saying that only one workspace can be opened per user).

In order to achieve the above behavior, the https://github.com/eclipse/che/tree/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile needs to be modified. But, I believe that the above devfile feature is not meant to be overridden.

### Alternatives
None. I would prefer it to be overridden instead of forking the entire codebase and modify the behavior.

### Additional context
Thank you, @ibuziuk for advise.

**Comment by benoitf** [comment]
@skabashnyuk @ibuziuk are you missing some details on this issue ?

**Comment by ibuziuk** [comment]
>  3. but projects that the individual users see would be different - the projects shall come from database based on user login.

I personally do not understand the last part of the flow:
- if devfiles are the same why the projects need to be different?
- why it is required to store projects in db instead of  cvs?
- how "individual users see would be different" is planned to be achived? There is some mapping between user and project. 

In general, the use-case is really specific and I personally do not see it as part of the upstream.

> Every user will need one workspace - it would be created when the user logs in and gets destroyed when the user logs-out/inactive.
> If there are 50 users logged in, there would be 50 workspaces (one per user). All these workspaces shall be created using the same devfile (i.e., editor/tools are same)

Similar functionality can be achieved by using the combination of:

- `CHE_LIMITS_USER_WORKSPACES_RUN_COUNT` - 1 running workspace per user
- `CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS` - workspace will be shutdown after some inactivity period

**Comment by skabashnyuk** [comment]
@svkr2k can you take a look https://github.com/eclipse/che/issues/13617 it will allow to override project location. Will it work for you?

**Comment by svkr2k** [comment]
@ibuziuk , @skabashnyuk . Thank you for suggestions. I shall try my best to clarify :-)

>if devfiles are the same why the projects need to be different?
i'm thinking of a system, using which, several users can:

Login->Create or Work on created projects (using custom editor & toolset)->Save their projects->Logout->Come back later and ... (cycle repeats)

None of the users would work on the same projects and they all develop independently. So, each user would have a set of projects that he/she created (needs mapping between user and projects he/she created)

**Comment by skabashnyuk** [comment]
@svkr2k did you tried to play with ```CHE_LIMITS_USER_WORKSPACES_RUN_COUNT``` variable?

**Comment by svkr2k** [comment]
> @svkr2k did you tried to play with `CHE_LIMITS_USER_WORKSPACES_RUN_COUNT` variable?

@skabashnyuk, I havent tried this yet. i shall try this soon.

**Comment by svkr2k** [comment]
Updated usage scenario (added #4) to the original comment.

**Comment by skabashnyuk** [comment]
@svkr2k 
Usecase 1-3 should be possible to do at this moment. 
4. unlikely would happen

**Comment by svkr2k** [comment]
> @svkr2k
> Usecase 1-3 should be possible to do at this moment.

Thank you @skabashnyuk, Are usecases 1-3 already supported in 7.4.0 ?

**Comment by skabashnyuk** [comment]
1. It can be stopped by timeout not deleted by logout.
2. Default configuration option 1 workspace per user.
3. Projects will come from the git server. Github for example.
