### ISSUE TITLE
Improve chectl Travis CI jobs 

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14114]
### Is your enhancement related to a problem? Please describe.

Current chectl CI has 4 major problems:

1. NO RELEASE JOB: There is no automated job to do chectl releases (but there are 2 CIs job)
2. FAIL TO BUILD WINDOWS TAR: Jenkins CI job cannot build chectl tar package for windows
3. GH RELEASES AND AUTOUPDATE ARE NOT COMPATIBLE: Travis CI job publishes tar artefacts on GitHub release pages but oclif autoupdater isn't compatible with such publishing platform.
4. DOC DOESN'T MENTION TAR ARTIFACTS AND AUTOUPDATER: We have setup chectl tar packaging and publishing on download.jboss with autoupdater enabled but documentation still refers to the single binary packaging. 

### Describe the solution you'd like

- [x] CREATE A TRAVIS CI RELEASE JOB
A new CI job should be triggered by every commit on a branch named `release`. On that branch we should push commits once for every new Che release. The CI job should parse the chectl version from a file named `VERSION` and chectl on that branch should be configured to use a specific Che release (for example `v7.0.0-rc-4.0`) whereas on master branch it is configured to use the nightly version of Che.

- [x] TRAVIS CI JOBS SHOULD PUBLISH ARTIFACTS to download.jboss.org
Travis CI master branch build should upload tar artefacts to download.jboss.org and it should correspond to the an edge (or `unstable` or `next`) autoupdater channel
Travis CI release branch build should upload tar artefacts to download.jboss.org  as well but as the default autoupdater channel.

- [x] UPDATE README AND DOC
Chectl installation doc should refer to the instructions to download and install the tar version of chectl.

- [x] DEPRECATE THE JENKINS JOB
It doesn't make sense to have 2 CI jobs that do the same build. And among those 2 jobs, the Jenkins one should be deprecated because it cannot be used to build windows artifacts.

- [x] DEPRECATE THE SINGLE BINARY ARTEFACT
The tar package of chectl should be the default one. We should deprecate the single binary to avoid maintaining and documenting how to use the single binary.

**Comment by l0rd** [comment]
That's needed for the `7.0.0` endgame to setup chectl release process.

**Comment by l0rd** [comment]
@nickboldt confirmed that it should be possible to upload artifacts to https://download.jboss.org/jbosstools/che-incubator/chectl/dist from a Travis job.

He has provided a sample:

https://github.com/jbosstools/jbosstools-website/blob/master/.travis.yml 
--> https://travis-ci.org/jbosstools/jbosstools-website 
--> production branch 
--> https://tools.jboss.org/ 

https://github.com/jbosstools/jbosstools-website/blob/master/Rakefile#L297-L321

**Comment by nickboldt** [comment]
For CI purposes, it would be handy to continue to release unversioned "latest" versions of chectl, as we had up to and including https://github.com/che-incubator/chectl/releases/tag/20190802065601

This makes it easier to link to the latest binary, without having to unpack a tarball. (Admittedly it's just one extra step, but :man_shrugging: )

**Comment by benoitf** [comment]
I'm not sure to understand the `unversioned latest`
The binary that is inside the tgz is not the same that the one that was in releases/ section.

`chectl-linux.tgz/bin/chectl` !== `chectl-linux`

we're not just putting a binary inside a tgz just for the fun :-)
