### ISSUE TITLE
OC-connector remote plugin: not enough permissions to get list cluster service classes

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14116]
### Describe the bug
Oc-connector plugin: when I try to apply service to the application, I have an error:
```
✗  unable to list services because Service Catalog is not enabled in your cluster: unable to get cluster serviceClassExternalName: unable to get cluster service classes: unable to list cluster service classes: the server could not find the requested resource (get clusterserviceclasses.servicecatalog.k8s.io)
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create new workspace from devfile:
https://gist.github.com/AndrienkoAleksandr/7c698719736b90294d8dfe38c5046ee2
2. Open workspace.
3. oc-connector login command palette command doesn't work, because https://github.com/eclipse/che/issues/13405 . So login with help of terminal:
`Terminal` menu -> `New terminal for specific container` -> `Ctrl + P` to show list plugin containers, select and create new terminal for container with name starts with wscode-oc-connector. Then login using oc tool:
oc login https://kubernetes.default.svc ---insecure-skip-tls-verify=false
4. Open oc-connector plugin view.
5. In the application cluster explorer select current cluster.
6. With help of right mouse click open context menu and click on the option:
`New project`, type new project name, for example oc-connector-test, type Enter, than you should get notification about successfully creation new project.
7. Select created project.
8. Open context menu with help of right mouse click and click new Application, type new application name: oc-test.
8. Select application oc-test and open context menu using right mouse click, select `New service` and type Enter and you see an error defined above.

### Expected behavior
Plugin should not fail on the service creation step.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
@AndrienkoAleksandr Hello, what's the difference between this issue and https://github.com/eclipse/che/issues/13405 ?

**Comment by AndrienkoAleksandr** [comment]
@AndrienkoAleksandr Hello, what's the difference between this issue and #13405 ?

difference that I want to create new service, I did login, but with help of terminal and want to create new service to deploy project.

**Comment by azatsarynnyy** [comment]
It should work with enabled service catalog:
```
$ minishift openshift component add service-catalog
$ minishift openshift component add automation-service-broker
$ minishift openshift component add template-service-broker
```
