### ISSUE TITLE
Enable filtering of old plugin versions from registry

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14112]
Right now, the plugin registry contains multiple versions of plugins, and I wonder if that's intentional (because some versions are needed for some stacks/devfiles, but newer ones are needed for newer stacks/devfiles) or if that's what happens when no one is comparing the plugins to ensure that older plugin meta.yaml files are updated to the latest.

If we look in the v3/plugins/ folder of the che-plugin-registry master branch, we will find these multiples:

download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.38.0-1373.vsix
download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.43.0-1473.vsix
download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.45.0-1523.vsix
download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.46.0-1549.vsix

github.com/Azure/vscode-kubernetes-tools/releases/download/0.1.17/vscode-kubernetes-tools-0.1.17.vsix
github.com/Azure/vscode-kubernetes-tools/releases/download/1.0.0/vscode-kubernetes-tools-1.0.0.vsix

github.com/che-incubator/ms-code.typescript/releases/download/v1.30.2/che-typescript-language.vsix
github.com/che-incubator/ms-code.typescript/releases/download/v1.35.1/che-typescript-language-1.35.1.vsix

github.com/microsoft/vscode-go/releases/download/0.11.0/Go-0.11.0.vsix
github.com/Microsoft/vscode-go/releases/download/0.9.2/Go-0.9.2.vsix

github.com/microsoft/vscode-java-debug/releases/download/0.16.0/vscode-java-debug-0.16.0.vsix
github.com/microsoft/vscode-java-debug/releases/download/0.19.0/vscode-java-debug-0.19.0.vsix

github.com/Microsoft/vscode-python/releases/download/2019.3.6558/ms-python-release.vsix
github.com/Microsoft/vscode-python/releases/download/2019.5.18875/ms-python-release.vsix

github.com/redhat-developer/vscode-openshift-tools/releases/download/v0.0.17/openshift-connector-0.0.17-127.vsix
github.com/redhat-developer/vscode-openshift-tools/releases/download/v0.0.19/openshift-connector-0.0.19-183.vsix
github.com/redhat-developer/vscode-openshift-tools/releases/download/v0.0.21/openshift-connector-0.0.21-228.vsix

github.com/redhat-developer/vscode-xml/releases/download/0.3.0/redhat.vscode-xml-0.3.0.vsix
github.com/redhat-developer/vscode-xml/releases/download/0.5.1/redhat.vscode-xml-0.5.1.vsix
github.com/redhat-developer/vscode-xml/releases/download/0.7.0/vscode-xml-0.7.0-3205.vsix

github.com/redhat-developer/vscode-yaml/releases/download/0.3.0/redhat.vscode-yaml-0.3.0.vsix
github.com/redhat-developer/vscode-yaml/releases/download/0.4.0/redhat.vscode-yaml-0.4.0.vsix

**Comment by amisevsk** [comment]
The idea behind plugin "releases" is that if a workspace requests e.g. `redhat/vscode-yaml/0.4.0`, they always get the extension from `github.com/redhat-developer/vscode-yaml/releases/download/0.4.0/redhat.vscode-yaml-0.4.0.vsix`. Whether that's a useful feature or not, I'm not sure, but in the case that a new release of vscode-yaml is broken for some reason, existing workspaces won't stop working.

Removing this functionality at this point would require modifying plugin references in all workspaces though, as any plugin that doesn't specify `latest` as version will fail to find its plugin on startup.

**Comment by nickboldt** [comment]
Fair point. So maybe when we productize we can filter out the old versions and just keep the latest/supported ones.

**Comment by nickboldt** [comment]
Fix for this idea in https://github.com/eclipse/che-plugin-registry/pull/232

**Comment by nickboldt** [comment]
Another way to make this work is using the new deprecate method in the plugin meta.yaml:

```
deprecate:             # optional; section for deprecating plugins in favor of others
  autoMigrate:         # boolean
  migrateTo:           # new org/plugin-id/version, e.g. redhat/vscode-apache-camel/latest
``` -- https://github.com/eclipse/che-plugin-registry/blob/master/README.md#plugin-meta-yaml-structure

So this can be closed.
