### ISSUE TITLE
Stuck at 'Starting workspace agent' when Che server, Docker and browser are on the same machine

### ISSUE THREAD

**Issue by GuSuku** [eclipse-che/che#1412]
I am running an Amazon t2.micro instance (1GB RAM + 2GB swap) with 
Headless Ubuntu `14.04` with lubuntu-desktop that I can access through tightVNC
Che version: `4.2.0`
Che dir: `~/Applications/eclipse-che-4.2.0`
Started Che by: `~/Applications/eclipse-che-4.2.0/bin/che.sh run --remote:ip`
Accessed on Firefox
Log since starting Che server: https://gist.github.com/GuSuku/5b40928f08742f2b2fd6c76fbde54bae
Log since creating workspace through browser: https://gist.github.com/GuSuku/d05034100f5b389a9741af053a6fb772

Also tried with no luck:
- adding `-r:<publicIP>` flag when starting Che
- opened up ports 32768 - 65535 for incoming TCP (is this required when running on same machine?)
- Increased timeout by a factor of 10 (to 60000)

docker version:

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

docker info:

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-87-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-blah-blah
ID: AMIF:NZY5:DFBT:4PUG:HSEL:74UI:ATOP:W733:2YCC:NYGC:5F7H:LUID
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

java -version

```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

**Comment by TylerJewell** [comment]
@GuSuku - First, thank you for taking the time to provide a thorough ticket. It helps with the diagnosis, tremendously.

The error message is indicating that either the Che server is unable to connect to the workspace agent, or vice versa. There is an error in the Che server that says, `[ERROR] [.c.a.m.s.w.WsAgentLauncherImpl 111]  - Fail pinging ws agent. Url:http://ip:32780/api/ext/.`  So, if you look at the networking docs, we provide the algorithm for how Che is attempting to establish a connection to a new workspace.
1. It'll use the value of `machine.docker.local_node_host` in your che.properties.  This will be the host where your docker containers are running.  You could hard code the IP address.
2. It also will then look at the value of CHE_DOCKER_MACHINE_HOST environment variable. You could set this optionally instead.  If these values are not set, then Che either uses DOCKER_HOST or localhost.  Which at times can cause problems.

Separately, it also seems that agent in the workspace failed to connect back to the Che server.  The algorithm for this is:
1. `machine.docker.che_api.endpoint` which has a default value of `http://che-host:${SERVER_PORT}/ide/api`.  We derive the che-host value.  But you could replace this with the known IP address where the Che server is running.  IF you do not override this, we use the value of `docker0` interface. 
1. If `docker0` is unreachable, then we use `172.17.42.1`.

Can you identify the IP address of the server itself and consider setting it with these properties to see what happens?

**Comment by james10174** [comment]
@GuSuku Seems like a firewall issue via t2.micro instance. Read the following link on possible solution to opening up ports. [http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_SecurityGroups.html](url). The container will forward all ports to host network device. This maybe the issue if network device on host cannot create port. Try running the following in t2.micro instance.

`
Terminal 1
nc -l 35000
#can also do nc -l <external ipaddress> 35000

Terminal 2
netstat -tulpen | grep  nc
#write down port number  (ie 0.0.0.0:<port assigned>)
nc localhost <port assigned>
#can also do nc <external ipaddress> <port assigned>

Terminal 1
invalid connection to [127.0.0.1] from (UNKNOWN) [127.0.0.1] <number>
#<ctrl-c> to exit

Terminal
#Run this command with che server running after trying to start workspace. Let us know result.
netstat -tulpen | grep  /java
`

Below are results I get using scaleways cloud server.
![image](https://cloud.githubusercontent.com/assets/16562450/15729829/506765aa-282d-11e6-8e63-1d6c3f5949f2.png)
![image](https://cloud.githubusercontent.com/assets/16562450/15729836/59a6174c-282d-11e6-8e4c-a25314b79751.png)
![image](https://cloud.githubusercontent.com/assets/16562450/15729607/5b49bf1a-282b-11e6-9943-3015750d3aec.png)

**Comment by ghost** [comment]
@TylerJewell CHE_DOCKER_MACHINE_HOST is set by `-r` so, it's all good here.

I think @james10174 is right about firewall and ports. Since Che server uses an external IP in this case rather than localhost, it cannot reach workspace agent.

Things to try:
1. Keep the timeout increased.
2. Start a workspace.
3. Run `docker ps` on the host
4. Find the port that is mapped to 4401. It starts with 32...
5. From your local machine run:

`curl -v http://$IP:$PORT/api/ext/`

If you get no response, then something blocks this port. nmap can also help:

`nmap $IP -Pn -p $PORT`

I think we may need to add instructions on opening ports on Amazon in this doc https://eclipse-che.readme.io/docs/configuration-che-on-ec2

**Comment by GuSuku** [comment]
Oddly, I rebooted and everything works fine now! Thanks for taking the time to respond!

In any case, before trying that out, I had drafted the below response. In case it is useful in any way....

@TylerJewell I am quite ignorant regarding server admin and networking. How can I find the che-ip:port, docker-ip:port and workspace-ip:port? If they are in the logs, then I think missed them.

@james10174 
Terminal1:
`ubuntu@ip-172-31-xx-xxx:~$ nc -l 35000`

Terminal2:

```
ubuntu@ip-172-31-xx-xxx:~$ netstat -tulpen | grep nc
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      1000       16064       2419/Xtightvnc  
tcp        0      0 0.0.0.0:35000           0.0.0.0:*               LISTEN      1000       150362      16382/nc        
tcp        0      0 127.0.0.1:5901          0.0.0.0:*               LISTEN      1000       16066       2419/Xtightvnc  
ubuntu@ip-172-31-xx-xxx:~$ nc localhost 35000
```

So, unlike your case, I did not see any reaction on terminal 1

Then, after starting Che:

```
ubuntu@ip-172-31-xx-xxx:~$ netstat -tulpen | grep /java
tcp6       0      0 :::8080                 :::*                    LISTEN      1000       156839      17116/java      
tcp6       0      0 :::32001                :::*                    LISTEN      1000       156841      17116/java      
tcp6       0      0 :::58883                :::*                    LISTEN      1000       156838      17116/java      
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      1000       156852      17116/java      
tcp6       0      0 :::32101                :::*                    LISTEN      1000       156842      17116/java  
```

@eivantsov 
docker ps:

```
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                         NAMES
a4e19d56045e        eclipse-che/che_workspacetyb56aabheij7vum_ws-machine_n4jdv   "/bin/sh -c 'sudo /us"   20 seconds ago      Up 19 seconds       0.0.0.0:32788->22/tcp, 0.0.0.0:32787->4401/tcp, 0.0.0.0:32786->4403/tcp, 0.0.0.0:32785->4411/tcp, 0.0.0.0:32784->8000/tcp, 0.0.0.0:32783->8080/tcp, 0.0.0.0:32782->9876/tcp   che_workspacetyb56aabheij7vum_ws-machine_n4jdv
```

But I didn't get any response on 32787
