### ISSUE TITLE
Confusing notification when task is complete

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#14125]
### Describe the bug
When running a task, the notification saying `Task <task_name> has been started` [1] but when it finishes, it says `Task <number> exited with code 0.` [2] which is quite confusing. 

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify
Testing on RH-Che prod-preview with 7.0.0-rc-4.0

### Steps to reproduce

1. Start `Java Maven` stack with default project
2. Click Terminal -> Run task... 
3. Choose any task (e.g. `che: maven build`)

### Expected behaviour
The identifier of a terminal window in a notification should be same for start and stop of a task - either the name of a task or a serial number of terminal window. 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
[1] 
![Screenshot from 2019-08-05 13-11-13](https://user-images.githubusercontent.com/29278800/62460756-2ae8a800-b783-11e9-8167-59a37e951b01.png)

[2]
![Screenshot from 2019-08-05 13-11-20](https://user-images.githubusercontent.com/29278800/62460763-2f14c580-b783-11e9-8431-8efd76404f6d.png)

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: please specify
RH-Che deployed on prod-preview

**Comment by benoitf** [comment]
@RomanNikitenko @slemeur I think you already talked about that ?

**Comment by slemeur** [comment]
discussed here: https://github.com/eclipse/che/issues/13394
@vparfonov is that a regression?

**Comment by vparfonov** [comment]
> discussed here: #13394
> @vparfonov is that a regression?
@slemeur 
Looks like it was not fully implemented for Che Task.
For `master` branch fixed here https://github.com/eclipse/che-theia/pull/399, should we port it to the `7.0.0` branch?

**Comment by slemeur** [comment]
7.1.0 please
