### ISSUE TITLE
Can't build che-theia-dev image.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#14120]
### Describe the bug

Failed to build `eclipse/che-theia-dev` image.
I've already fixed this. I'll send PR soon.

### Che version

 - [x] latest

### Steps to reproduce

0. Clone `eclipse/che-theia`.
1.  `cd dockerfiles/theia-dev`
2. `./build.sh --build-arg:GITHUB_TOKEN=$(github_token) --organization:$(organization) --tag:$(tag) --prefix:$(prefix)`

### Expected behavior

Done with no error.

### Environment
   - [x] my computer 
       - [x] Linux

### Additional context

https://dev.azure.com/pizzafactory/camino/_build/results?buildId=1162&view=logs&jobId=ca395085-040a-526b-2ce8-bdc85f692774&taskId=e32f6c0c-095d-5644-3d3c-8457b0141736&lineStart=252&lineEnd=290&colStart=1&colEnd=1

**Comment by benoitf** [comment]
I flagged it 7.1.0 as theia master is not used in che 7.0.0 but it's still required as soon as possible
