### ISSUE TITLE
Make https://github.com/redhat-developer/devfile/blob/master/devfile_next.png diagram up to date.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14123]
### Is your task related to a problem? Please describe.
Yes. https://github.com/redhat-developer/devfile/blob/master/devfile_next.png is not up to date
Looks like it is not up to date. At least ChePlugin, CheEditor now have registryURL, reference field.
K8s, OS have memoryLimit. CommandAction: reference and referenceContent fields.
Maybe even more fields are not listed.
Also startPoint, tag, commitId in ProjectSource, clonePath in Project

### Describe the solution you'd like
Make diagram up to date.

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by benoitf** [comment]
nice if it fit for `7.0.0` but not blocker
