### ISSUE TITLE
doc: have more contribute flow for each of our components with a devfile, to be updated in CONTRIBUTING.md files of each projects Ws master Chectl Plugin Broker Etc …

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#14126]
### Is your task related to a problem? Please describe.
We are trying to promote devfile flow for code contribution in Che. But at the moment, we only have few devfile and flows documented.

- Dashboard: https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#dashboard
- Che-theia: https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md

### Describe the solution you'd like
Have more projects with CONTRIBUTING.md describing how to contribute with a provided devfile.

**Comment by benoitf** [comment]
I set `7.1.0` as it's not a blocker to release 7.0.0

**Comment by mmorhun** [comment]
Issue for Che in Che flow: https://github.com/eclipse/che/issues/14183.

**Comment by l0rd** [comment]
Changed the milestone from `7.0.0` to `7.1.0`.

@sunix can you help providing the status here? Would be nice if we could have a table with the list of projects that have or have not a a CONTRIBUTING.md file and a devfile.

**Comment by AndrienkoAleksandr** [comment]
@l0rd @sunix in PTO. I think we covered most components:

Component | Devfile | Contributing.md
--- | --- | ---
[workspace-loader](https://github.com/eclipse/che/tree/master/workspace-loader) | [devfile](https://github.com/eclipse/che/blob/master/workspace-loader/devfile.yaml) | [doc](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#workspace-loader)
[user dashboard](https://github.com/eclipse/che/tree/master/dashboard) | [devfile](https://github.com/eclipse/che/blob/master/dashboard/devfile.yaml) | [doc](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#dashboard)
[che server](https://github.com/eclipse/che) | [devfile ](https://github.com/eclipse/che/blob/master/devfile.yaml) | [doc](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#che-server-aka-ws-master)
[che-machine-exec](https://github.com/eclipse/che-machine-exec) | [devfile](https://github.com/eclipse/che-machine-exec/blob/master/devfile.yaml) | [doc](https://github.com/eclipse/che-machine-exec/blob/master/CONTRIBUTING.md)
[che-plugin-broker](https://github.com/eclipse/che-plugin-broker) | [devfile](https://github.com/eclipse/che-plugin-broker/blob/master/devfile.yaml) | [doc](https://github.com/eclipse/che-plugin-broker/blob/master/CONTRIBUTING.md)
[chectl](https://github.com/che-incubator/chectl) | [devfile](https://github.com/che-incubator/chectl/blob/master/devfile.yaml) | [doc](https://github.com/che-incubator/chectl/blob/master/CONTRIBUTING.md)
[che-theia](https://github.com/eclipse/che-theia) | [devfile](https://github.com/eclipse/che-theia/blob/master/devfiles/che-theia-all.devfile.yaml) | [doc](https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md)
[che-operator](https://github.com/eclipse/che-operator) | nope | nope
[che-theia/generator](https://github.com/eclipse/che-theia/tree/master/generator) | nope(do we need it?) | [doc](https://github.com/eclipse/che-theia/blob/master/generator/CONTRIBUTING.md)

**Comment by l0rd** [comment]
Thanks @AndrienkoAleksandr from my point of view it's ok if we don't have it for che-theia/generator. So let's close this issue as soon as che-operator has its devfile and `CONTRIBUTING`.

**Comment by sunix** [comment]
@davidfestal could you help us to write a CONTRIBUTING.md file on how to contribute/setup env on che-operator ? with a devfile in ideal case ?

**Comment by nickboldt** [comment]
7.20 is done. Is this issue complete? If so, please close. If not, please move to backlog or appropriate milestone.

**Comment by mmorhun** [comment]
I think it is done, as we even have the check in PR template

**Comment by AndrienkoAleksandr** [comment]
+1 for done.

**Comment by nickboldt** [comment]
If done, then close.
