### ISSUE TITLE
Support flow of application moving into Kubernetes / Openshift cluster

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14122]
I would like Che to support the following user scenario:
_A user has an application (say Spring Boot) which runs on a server. The user wants to move that application into Kubernetes or Openshift cluster and be able to develop and rollout it from Che._

User steps:
1. Create Che environment (write devfile)
2. Containerize the application (write dockerfile(s) and build image(s) ) from within Che workspace (I think buildah plugin will be suitable). Also ability to push into user's registry would be a plus.
3. Run the application, test, debug it.
4. Deploy the application on the cluster from within Che workspace (using Kubernetes or VS Code Openshift extension or oc connector plugin).

For now we have covered steps _1_ and _3_.

I tried to use buildah plugin, but it didn't work for me. Maybe some part of configuration was missed, but I failed to find any docs about that on Che side.
Also Kubernetes plugin didn't work properly. Again, no docs how to make it work with Openshift, which I could find.

Subtasks:
 - [ ] Add Kubernetes native Java + Maven sample and describe flow of the application development in Che  https://github.com/eclipse/che/issues/14358

**Comment by mmorhun** [comment]
@l0rd @slemeur WDYT ?

**Comment by l0rd** [comment]
Building an image within a container running on OpenShift (i.e. rootless build) can be tricky. You cannot achieve that with buildah. Maybe using S2I but that's OpenShift specific and has limitations as well.

I don't think that OpenShift / buildah are ready yet for that kind of scenario.

**Comment by kfox1111** [comment]
A couple more options.

I've had good luck in my k8s clusters building containers with Kaniko (https://github.com/GoogleContainerTools/kaniko)

A second option is kpack. I have not used it much, and has its own qwerks, so maybe not the best primary option, but its still useful for some use cases: https://github.com/pivotal/kpack

**Comment by ericwill** [comment]
Thanks to the latest dogfooding efforts, item 2 from that list is now done. I think the only thing left is to test item 4.
