### ISSUE TITLE
[e2e] Do not push che-server to personal repository in PR check job

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14128]
### Is your task related to a problem? Please describe.
I've just noticed, that PR check job is pushing che-server it builds to docker.io/maxura, which is @musienko-maxim personal repository.

### Describe the solution you'd like
We should either push to docker.io/eclipse, or even better quay.io/eclipse

**Comment by dmytro-ndp** [comment]
It's related to https://github.com/eclipse/che/issues/14068
