### ISSUE TITLE
default online plugin registry is not up-to-date for minishift addon

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14138]
### Describe the bug
Following https://github.com/eclipse/che-plugin-registry/pull/194 and https://github.com/eclipse/che/pull/14061 now machine exec plugin is retrieved with `next`

but if I start Eclipse Che with minishift addon (and no local registries by default)

I've the following error in Che:
```
The requested URL /v3/plugins/eclipse/che-machine-exec-plugin/next/meta.yaml was not found on this server.



Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceamcl0k0sjjta7vby failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/next/meta.yaml': Downloading https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/next/meta.yaml failed. Status code 404. Response body: 
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Install Eclipse Che with minishift-addon

### Expected behavior
Workspace should start fine  (https://che-plugin-registry.openshift.io/plugins/ should include the next version)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/436777/62530731-647fe880-b841-11e9-8e19-9479b3f2c876.png)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
I thought minishift addon was retired since nobody support it.

**Comment by benoitf** [comment]
@skabashnyuk I guess it is not retired as I need to provide it as part of chectl for `7.0.0`:
https://github.com/eclipse/che/issues/13889

**Comment by slemeur** [comment]
needed for #13889 -> milestone `7.0.0`

**Comment by lemaral** [comment]
Same issue with minikube
Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/next/meta.yaml': Downloading https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/next/meta.yaml failed. Status code 404. Response body: 
Not Found
The requested URL /v3/plugins/eclipse/che-machine-exec-plugin/next/meta.yaml was not found on this server.

**Comment by benoitf** [comment]
@lemaral could you tell me how you setup che on minikube ? (helm/operator, etc)
