### ISSUE TITLE
Timeout wait on minishift addon for che-server

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14137]
### Describe the bug
Chectl is waiting for a che pod with name 'component=che, app=che' but the pod name has no component so it wait for ever

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Starts chectl with remote URLs for registries with minishift/minishift-addon

### Expected behavior
chectl should run fine

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift 1.34.1
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by slemeur** [comment]
needed for #13889 -> milestone `7.0.0`
