### ISSUE TITLE
Timeout wait on chectl when deploying Che with Minishift addon

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14136]
### Describe the bug
Chectl is waiting for a `Devfile registry pod` but there is no such pod with minishift-addon.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

```
$ chectl server:start --installer=minishift-addon --platform=minishift
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
    ✔ Retrieving minishift IP and domain for routes URLs...192.168.99.130.nip.io.
  ❯ 🏃‍  Running the Che minishift-addon
    ✔ Check minishift version...done.
  ✔ 🏃‍  Running the Che minishift-addon
    ✔ Check minishift version...done.
    ✔ Check logged...done.
    ✔ Check che addon is available
    ✔ Apply Che addon...done.
  ❯ ✅  Post installation checklist
    ❯ Devfile registry pod bootstrap
      ⠏ scheduling
        downloading images
        starting
      Plugin registry pod bootstrap
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check
```

### Expected behavior
startup should be fine

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift 1.34.1
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
Introduced by https://github.com/che-incubator/chectl/pull/228 and https://github.com/che-incubator/chectl/pull/189

**Comment by slemeur** [comment]
needed for #13889 -> milestone `7.0.0`
