### ISSUE TITLE
Mark in the task widget title when task is exited.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14132]
### Is your enhancement related to a problem? Please describe.
We need better notify user when task is completed.

### Describe the solution you'd like
We could mark completed task with help task widget title. For example in the task title we can apply text: `Exited` after task name when task is completed.

**Comment by benoitf** [comment]
looks a dup of https://github.com/eclipse/che/issues/14125

**Comment by AndrienkoAleksandr** [comment]
@benoitf I don't mind notification about task exited.  I think notification - it's not enough. I think task notification it's temporary marks widget, but when user opens a lot of tasks and he don't want to close all widgets, he should remember which one notifications marked some widget, like exited. But it's confusing. I think the best way for such cases ->  display information about exited task in the task output widget, for example in the title.

**Comment by sunix** [comment]
dups of https://github.com/eclipse/che/issues/13853
