### ISSUE TITLE
Fix security alerts in che-theia repository

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#14142]
### Is your task related to a problem? Please describe.
Currently we have `Security Alerts` from github in [che-theia repository](https://github.com/eclipse/che-theia)

### Describe the solution you'd like

We need to upgrade dependencies: 
- `js-yaml` in `generator/package.json` and `eclipse-che-theia-plugin-ext/package.json`
- `axios` in `generator/package.json` and `eclipse-che-theia-plugin-ext/package.json`
- `lodash` in `dockerfiles/theia/e2e/src/package.json`
- `xterm` in `eclipse-che-theia-terminal/package.json`
- `jquery` in `dockerfiles/theia/e2e/src/package.json`

**Comment by evidolob** [comment]
I think it can be for 7.1.0 milestone

**Comment by monaka** [comment]
`js-yaml` and `lodash` will be fixed by eclipse/che-thaia#404. Others need Eclipse CQ approvement.
