### ISSUE TITLE
Revamp Che 7 administration guide

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14147]
### Goal
The goal of this issue is to revamp the administration guidelines of Che 7.
Outline will need to be rework and explanations needs to be adapted/reviewed/reworked

## Subtask:

- [x] [docs] Document All fields of the CheCluster CR in che-docs and CRD - https://github.com/eclipse/che/issues/13886
- [ ] [docs] Document the various places where Che can be configured (Che Custom resource definition; it could be in the Config Map; or in the `che.env`) - https://issues.redhat.com/browse/RHDEVDOCS-1581

**Comment by slemeur** [comment]
cc #13886

**Comment by slemeur** [comment]
cc #14088

**Comment by nickboldt** [comment]
Closing in favour of https://issues.redhat.com/browse/RHDEVDOCS-1581
