### ISSUE TITLE
[Happy Path] Sometimes the "Happy path" test fails when click on "Start debug" button

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14141]
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1) Create workspace from devfile <https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/happy-path-workspace.yaml>
2) Launch created workspace
3) Open workspace
4) Build application by command "che: build"
5) Open codebase and set breakpoint
6) Launch command "che: run-debug"
7) Open debug explorer
8) Click on "Run debug" button
9) Pay attention that application has been crushed

### Expected behavior
Debug session is run

### Observed behavior
Application is failed

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@rhopp moving to `7.1.0` for now since it is P2 and not crucial (but, nice to have) for GA

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/14180
