### ISSUE TITLE
In some case, generated paths to each ssh private key in `/etc/ssh/config` will be mismatch to mount paths.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#14151]
### Describe the bug

I couldn't `git push` via SSH. I inspected and It is caused by invalid path to SSH key.

### Che version

 - [x] HEAD ~~other: please specify~~

### Steps to reproduce

As currently I'm not sure  how to reproduce, I show my step.

1. Open terminal
2. `ssh -vvv git@ssh.dev.azure.com`
3. Press `Ctrl-C` after SSL auth was failed.
4. `ls /etc/ssh/`

### Expected behavior

The goal is "`git push` is done with no error.".
In the viewpoint of "Steps to reproduce", SSL auth is succeeded.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
But It won't depend on runtime.

### Additional context

ssh tryes to find the secret in `/etc/ssh/ssh-dev-azure-com/ssh-privatekey`.

```
debug1: Trying private key: /etc/ssh/ssh-dev-azure-com/ssh-privatekey
debug3: no such identity: /etc/ssh/ssh-dev-azure-com/ssh-privatekey: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
git@ssh.dev.azure.com's password: 
```

But it mounted on the another path /etc/ssh/ssh.dev.azure.com/ssh-privatekey.

```
$ ls /etc/ssh
github.com  sshd_config        ssh_host_dsa_key.pub    ssh_host_ed25519_key      ssh_host_rsa_key.pub
moduli      ssh.dev.azure.com  ssh_host_ecdsa_key      ssh_host_ed25519_key.pub  ssh_import_id
ssh_config  ssh_host_dsa_key   ssh_host_ecdsa_key.pub  ssh_host_rsa_key
```

**Comment by monaka** [comment]
Looks caused by here: https://github.com/eclipse/che/blob/1af529cc4bf1ad9cbad6ad9b527bf8a27d3fe7b9/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java#L239

My suggestion is to remove getValidNameForSecret() because it doesn't any help for creating valid path string.

https://github.com/eclipse/che/blob/1af529cc4bf1ad9cbad6ad9b527bf8a27d3fe7b9/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/VcsSshKeysProvisioner.java#L245-L248

**Comment by ibuziuk** [comment]
> As currently I'm not sure how to reproduce, I show my step.

@monaka could you clarify how the keys were generated. There is a known issue that workspace must be restarted to have the keys available form all containers - https://github.com/eclipse/che/issues/14073 ? is it smth. you are facing atm?

**Comment by ibuziuk** [comment]
@vparfonov @vinokurig there is a PR sent with a potential fix - https://github.com/eclipse/che/issues/14151
Could you please review?

**Comment by monaka** [comment]
@ibuziuk In my case, the key was generated before (in Che6). So it looks this issue is not related on #14073.

The background of this issue is "The private key was generated and stored to DB with no trouble. The provisioner for Kubernetes created `secret` object and mounted to the workspace container. But the content of the generated config file `/etc/ssh` is broken. So ssh is failed."

**Comment by ibuziuk** [comment]
I do not know if the keys generated in Che 6 are compatible with Che 7 (@vparfonov @vinokurig could you please shed some light on it?). Basically, in Che 7 one needs to generate keys via `SSH plugin` https://github.com/eclipse/che-theia/tree/master/plugins/ssh-plugin 
There is also a demo video https://youtu.be/72MDoJT05cY

@monaka could you update the issue description / title and specify that the problem you are facing is related to the SSH keys generated for Che 6?

**Comment by monaka** [comment]
The endpoint `/api/ssh` is not changed Che 6 to 7. I can get ssh keys even though I've generated no keypair on Che7. So it is beyond suspicious.

This issue doesn't depend on how generate key pair. This issue will be reproduced even if the key pair is generated via Che-Theia 7.

![Screenshot 2019-08-08 at 17 27 10](https://user-images.githubusercontent.com/101795/62687554-f6ceea80-ba01-11e9-9791-14274da18088.png)

**Comment by vparfonov** [comment]
@monaka Thanks for fix, I will check it. But it strange because I remember that got exception if try to mount keys with `.` in name. Thats way I add this method.

**Comment by vparfonov** [comment]
> I do not know if the keys generated in Che 6 are compatible with Che 7 (@vparfonov @vinokurig could you please shed some light on it?). Basically, in Che 7 one needs to generate keys via `SSH plugin` https://github.com/eclipse/che-theia/tree/master/plugins/ssh-plugin
> There is also a demo video https://youtu.be/72MDoJT05cY

Yes it doesn't meter are keys generated in Che6 or Che7, should work both 



> @monaka could you update the issue description / title and specify that the problem you are facing is related to the SSH keys generated for Che 6?

**Comment by monaka** [comment]
@vparfonov If my understanding is collect, the name of secret object must be matched `[A-Za-z_][A-Za-z0-9_]*`. But the mount path for it can be loose strict. Sometimes I'm also getting mixed up.
