### ISSUE TITLE
Cannot initialise workspace using factory

### ISSUE THREAD

**Issue by wtrocki** [eclipse-che/che#14154]
# Description

Factories from github url stopped working, while using the same factory directly in UI creates workspace successfully.

# Steps to reproduce

Login to Console and don’t create a workspace just yet.
Modify the url to by appending path /f?url=https://github.com/aerogear/ionic-showcase.git and eclipse che will automatically set up a new workspace for you.

What is happening is that 
Workspace will stuck in `Initializing workspace` mode. 
There is no information logs.

### Che version

1.2.0.GA :: crw_stable-branch/270 :: che-dev @ ea65 (20) :: che-parent @ e12b (6.19.0) :: che-lib @ e717 (6.19.0) :: che-ls-jdt @ 288b (0.0.3) :: che @ 46909 (6.19.5) :: codeready-workspaces @ d04f (1.2.0.GA)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot 2019-08-08 at 12 30 41](https://user-images.githubusercontent.com/981838/62699884-6f20b600-b9d8-11e9-9556-fa1ee0ebbff1.png)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

**Comment by ibuziuk** [comment]
> 1.2.0.GA :: crw_stable-branch/270 :: che-dev @ ea65 (20) :: che-parent @ e12b (6.19.0) :: che-lib @ e717 (6.19.0) :: che-ls-jdt @ 288b (0.0.3) :: che @ 46909 (6.19.5) :: codeready-workspaces @ d04f (1.2.0.GA)

@wtrocki is it CRW specific issue (1.2.0 GA) ? cc: @nickboldt

**Comment by wtrocki** [comment]
Yes.

**Comment by ibuziuk** [comment]
@wtrocki I can not reproduce on the latest upstream `7.0.0-rc-4.0`. You can try smth. like - https://github.com/ibuziuk/my-che-devfiles/blob/master/vaadin-addressbook/factory.json

**Comment by ibuziuk** [comment]
@nickboldt it might make sense to close this issue and open CRW specicif jira wdyt?
