### ISSUE TITLE
Image pull-backoff for Plugin Registry when deploying Che via Operator

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#14150]
### Describe the bug

When deploying the Che operator on OpenShift from the che-operator repo, the Che-Plugin-Registry container fails with an ImagePullBackOff error. Looking into the error further, it seems that the `quay.io/eclipse/che-plugin-registry` image doesn't exist

### Che version
Che 7 nightly
Latest version of the operator from https://github.com/eclipse/che-operator/

### Steps to reproduce
- Git clone https://github.com/eclipse/che-operator/
- Run deploy.sh
- Che-Plugin-Registry will error out with an ImagePullBackOff error:
   ```
      Warning  Failed     20s (x3 over 68s)  kubelet, 10.188.170.151  Failed to pull image
      "quay.io/eclipse/che-plugin-registry:nighlty": rpc error: code = Unknown desc = Error reading
      manifest nighlty in quay.io/eclipse/che-plugin-registry: manifest unknown: manifest unknown
   ```

There also seems to be a typo in the tag in `quay.io/eclipse/che-plugin-registry:nighlty`, which is causing the error. `quay.io/eclipse/che-plugin-registry:nightly` does exist.

### Expected behavior

The Che operator deploys fine with the deploy.sh script

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
johns-mbp-3:wtptestfix johncollier$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth
```

### Installation method
   - [ ] chectl 
   - [x] che-operator Latest from che-operator repo
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by johnmcollier** [comment]
Looks to be the `nighlty` typo in the Che operator code, I can put up a PR to fix this

**Comment by johnmcollier** [comment]
Opened https://github.com/eclipse/che-operator/pull/65

**Comment by johnmcollier** [comment]
@ibuziuk Yes, this can be closed now. Thanks.

**Comment by kushalg-1212** [comment]
can we open this again 

Command server:deploy failed with the error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image
    "quay.io/eclipse/che-plugin-registry:7.53.0" 

deploying with minikube 

che@CHE1:~$ chectl server:deploy --platform minikube
Enable CLI usage data to be sent to Red Hat online services. More info: https://developers.redhat.com/article/tool-data-collection [y/n]: y
› Current Kubernetes context: 'minikube'
  ✔ Verify Kubernetes API...[OK]
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...[Not Found]
  ↓ Check if OIDC Provider installed [skipped]
    → Dex will be automatically installed as OIDC Identity Provider
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Check Kubernetes version: [Found v1.24.3]
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...[192.168.59.101.nip.io]
    ✔ Checking minikube version...[1.26.1]
  ✔ Following Eclipse Che logs
    ✔ Start following logs...[OK]
  ✔ Cert Manager v1.8.2
    ✔ Install Cert Manager...[OK]
    ✔ Wait for Cert Manager...[OK]
  ✔ Create Namespace eclipse-che...[OK]
  ✔ Deploy Dex
    ✔ Create namespace: dex...[OK]
    ✔ Create issuer dex-selfsigned...[OK]
    ✔ Create certificate: dex-selfsigned...[OK]
    ✔ Create issuer dex...[OK]
    ✔ Create certificate: dex...[OK]
    ✔ Save Dex certificate...[OK: /tmp/dex-ca.crt]
    ✔ Add Dex certificate to Eclipse Che certificates bundle...[OK]
    ✔ Create Dex service account...[OK]
    ✔ Create Dex cluster role...[OK]
    ✔ Create Dex cluster role binding...[OK]
    ✔ Create Dex service...[OK]
    ✔ Create Dex ingress...[OK]
    ✔ Generate Dex username and password...[OK: admin:admin]
    ✔ Create Dex configmap...[OK]
    ✔ Create Dex deployment...[OK]
    ✔ Wait for Dex is ready...[OK]
    ✔ Configure API server
      ✔ Create /etc/ca-certificates directory...[OK]
      ✔ Copy Dex certificate into Minikube...[OK]
      ✔ Configure Minikube API server...[OK]
      ✔ Wait for Minikube API server...[OK]
  ✔ Deploy Eclipse Che
    ✔ Create ServiceAccount che-operator in namespace eclipse-che...[OK: created]
    ✔ Role and RoleBindings...[OK]
      ✔ Create Role che-operator...[OK: created]
      ✔ Create RoleBinding che-operator...[OK: created]
      ✔ Create ClusterRole che-operator...[OK: created]
      ✔ Create ClusterRoleBinding che-operator...[OK: created]
    ✔ Create Certificate che-operator-serving-cert...[OK: created]
    ✔ Create Issuer che-operator-selfsigned-issuer...[OK: created]
    ✔ Create Service che-operator-service...[OK: created]
    ✔ Create CRD checlusters.org.eclipse.che...[OK: created]
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...[OK]
    ✔ Create deployment che-operator in namespace eclipse-che...[OK: created]
    ✔ Operator pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ✔ Create CheCluster Custom Resource...[Created]
  ❯ Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ✔ Devfile Registry pod bootstrap
      ✔ Scheduling...[OK]
      ✔ Downloading images...[OK]
      ✔ Starting...[OK]
    ❯ Plug-in Registry pod bootstrap
      ✔ Scheduling...[OK]
      ✖ Downloading images
        → Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-plugin-registry:7.53.0".
        Starting
      Eclipse Che Dashboard pod bootstrap
      Eclipse Che Gateway pod bootstrap
      Eclipse Che Server pod bootstrap
      Eclipse Che status check
    Create DevWorkspaceOperatorConfig
    Retrieving Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed with the error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image
    "quay.io/eclipse/che-plugin-registry:7.53.0". See details: /home/che/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1662628585053.

**Comment by WoxFi** [comment]
any thoughts here 

> > can we open this again
> 
> > 
> 
> > Command server:deploy failed with the error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-plugin-registry:7.53.0"
> 
> > 
> 
> > deploying with minikube
> 
> > 
> 
> > che@CHE1:~$ chectl server:deploy --platform minikube Enable CLI usage data to be sent to Red Hat online services. More info: https://developers.redhat.com/article/tool-data-collection [y/n]: y › Current Kubernetes context: 'minikube' ✔ Verify Kubernetes API...[OK] ✔ 👀 Looking for an already existing Eclipse Che instance ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...[Not Found] ↓ Check if OIDC Provider installed [skipped] → Dex will be automatically installed as OIDC Identity Provider ✔ ✈️ Minikube preflight checklist ✔ Verify if kubectl is installed ✔ Verify if minikube is installed ✔ Verify if minikube is running ↓ Start minikube [skipped] → Minikube is already running. ✔ Check Kubernetes version: [Found v1.24.3] ✔ Verify if minikube ingress addon is enabled ↓ Enable minikube ingress addon [skipped] → Ingress addon is already enabled. ✔ Retrieving minikube IP and domain for ingress URLs...[192.168.59.101.nip.io] ✔ Checking minikube version...[1.26.1] ✔ Following Eclipse Che logs ✔ Start following logs...[OK] ✔ Cert Manager v1.8.2 ✔ Install Cert Manager...[OK] ✔ Wait for Cert Manager...[OK] ✔ Create Namespace eclipse-che...[OK] ✔ Deploy Dex ✔ Create namespace: dex...[OK] ✔ Create issuer dex-selfsigned...[OK] ✔ Create certificate: dex-selfsigned...[OK] ✔ Create issuer dex...[OK] ✔ Create certificate: dex...[OK] ✔ Save Dex certificate...[OK: /tmp/dex-ca.crt] ✔ Add Dex certificate to Eclipse Che certificates bundle...[OK] ✔ Create Dex service account...[OK] ✔ Create Dex cluster role...[OK] ✔ Create Dex cluster role binding...[OK] ✔ Create Dex service...[OK] ✔ Create Dex ingress...[OK] ✔ Generate Dex username and password...[OK: admin:admin] ✔ Create Dex configmap...[OK] ✔ Create Dex deployment...[OK] ✔ Wait for Dex is ready...[OK] ✔ Configure API server ✔ Create /etc/ca-certificates directory...[OK] ✔ Copy Dex certificate into Minikube...[OK] ✔ Configure Minikube API server...[OK] ✔ Wait for Minikube API server...[OK] ✔ Deploy Eclipse Che ✔ Create ServiceAccount che-operator in namespace eclipse-che...[OK: created] ✔ Role and RoleBindings...[OK] ✔ Create Role che-operator...[OK: created] ✔ Create RoleBinding che-operator...[OK: created] ✔ Create ClusterRole che-operator...[OK: created] ✔ Create ClusterRoleBinding che-operator...[OK: created] ✔ Create Certificate che-operator-serving-cert...[OK: created] ✔ Create Issuer che-operator-selfsigned-issuer...[OK: created] ✔ Create Service che-operator-service...[OK: created] ✔ Create CRD checlusters.org.eclipse.che...[OK: created] ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...[OK] ✔ Create deployment che-operator in namespace eclipse-che...[OK: created] ✔ Operator pod bootstrap ✔ Scheduling...[OK] ✔ Downloading images...[OK] ✔ Starting...[OK] ✔ Create CheCluster Custom Resource...[Created] ❯ Post installation checklist ✔ PostgreSQL pod bootstrap ✔ Scheduling...[OK] ✔ Downloading images...[OK] ✔ Starting...[OK] ✔ Devfile Registry pod bootstrap ✔ Scheduling...[OK] ✔ Downloading images...[OK] ✔ Starting...[OK] ❯ Plug-in Registry pod bootstrap ✔ Scheduling...[OK] ✖ Downloading images → Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-plugin-registry:7.53.0". Starting Eclipse Che Dashboard pod bootstrap Eclipse Che Gateway pod bootstrap Eclipse Che Server pod bootstrap Eclipse Che status check Create DevWorkspaceOperatorConfig Retrieving Che self-signed CA certificate Prepare post installation output Error: Command server:deploy failed with the error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-plugin-registry:7.53.0". See details: /home/che/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1662628585053.
> 
> 
> 
> Tried to delete and re deploy multiple with same error

**Comment by RealYHD** [comment]
I've also been having this issue specifically, with `quay.io/eclipse/che-plugin-registry:7.53.0`.

**Comment by sandeep89** [comment]
Adding more details 
✔ Configure Minikube API server...[OK]
 ESC:...skipping...
      ✔ Wait for Minikube API server...[OK]
  ❯ Deploy Eclipse Che
    ✔ Create ServiceAccount che-operator in namespace eclipse-che...[Exists]
    ✔ Role and RoleBindings...[OK]
      ✔ Create Role che-operator...[Exists]
      ✔ Create RoleBinding che-operator...[Exists]
      ✔ Create ClusterRole che-operator...[Exists]
      ✔ Create ClusterRoleBinding che-operator...[Exists]
    ✔ Create Certificate che-operator-serving-cert...[Exists]
    ✔ Create Issuer che-operator-selfsigned-issuer...[Exists]
    ✔ Create Service che-operator-service...[Exists]
    ✔ Create CRD checlusters.org.eclipse.che...[Exists]
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...[OK]
    ✔ Create deployment che-operator in namespace eclipse-che...[Exists]
    ❯ Operator pod bootstrap
      ✔ Scheduling...[OK]
      ✖ Downloading images
        → Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-operator:next".
        Starting
      Create ValidatingWebhookConfiguration org.eclipse.che
      Create CheCluster Custom Resource
    Error: Command server:deploy failed with the error: Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "quay.io/eclipse/che-operator:next". See details:
    /Users/Sandeep/Library/Caches/chectl/error.log. Eclipse Che logs: /var/folders/6h/1wx_gj4s7_3g_l2pvlzytmhc0000gp/T/chectl-logs/1662951406882.
      

The events file has below information 

LAST SEEN   TYPE      REASON              OBJECT                                               MESSAGE
7h45m       Normal    Scheduled           pod/che-operator-647dc65997-k6l99                    Successfully assigned eclipse-che/che-operator-647dc65997-k6l99 to minikube
7h43m       Normal    Pulling             pod/che-operator-647dc65997-k6l99                    Pulling image "quay.io/eclipse/che-operator:next"
7h43m       Warning   Failed              pod/che-operator-647dc65997-k6l99                    Failed to pull image "quay.io/eclipse/che-operator:next": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
7h43m       Warning   Failed              pod/che-operator-647dc65997-k6l99                    Error: ErrImagePull
4h34m       Normal    BackOff             pod/che-operator-647dc65997-k6l99                    Back-off pulling image "quay.io/eclipse/che-operator:next"
7h43m       Warning   Failed              pod/che-operator-647dc65997-k6l99                    Error: ImagePullBackOff
7h45m       Normal    SuccessfulCreate    replicaset/che-operator-647dc65997                   Created pod: che-operator-647dc65997-k6l99
7h45m       Warning   BadConfig           certificaterequest/che-operator-serving-cert-vhnnp   Certificate will be issued with an empty Issuer DN, which contravenes RFC 5280 and could break some strict clients
7h45m       Normal    CertificateIssued   certificaterequest/che-operator-serving-cert-vhnnp   Certificate fetched from issuer successfully
7h45m       Normal    cert-manager.io     certificaterequest/che-operator-serving-cert-vhnnp   Certificate request has been approved by cert-manager.io
7h45m       Normal    Issuing             certificate/che-operator-serving-cert                Issuing certificate as Secret does not exist
7h45m       Normal    Generated           certificate/che-operator-serving-cert                Stored new private key in temporary Secret resource "che-operator-serving-cert-797fr"
7h45m       Normal    Requested           certificate/che-operator-serving-cert                Created new CertificateRequest resource "che-operator-serving-cert-vhnnp"
7h45m       Normal    Issuing             certificate/che-operator-serving-cert                The certificate has been successfully issued
7h45m       Normal    ScalingReplicaSet   deployment/che-operator                              Scaled up replica set che-operator-647dc65997 to 1

**Comment by Addlai** [comment]
I've had the same problem, currently with
chectl/0.0.20220923-next.029f6ac win32-x64 node-v16.13.2
but I've been trying to get che to start for about a month now, so far with no success, on 4 different platforms: macOS Monterey M1, macOS Monterey Intel, Ubuntu Linux 22, and Windows 11 Pro. I believe I've probably issued the command
chectl server:deploy --platform minikube
about 50 times now.

Another odd aspect is that when I run che, I'm getting the message
>  √ Cert Manager v1.8.2
>    √ Install Cert Manager...[Exists]

repeated about 50 times, followed by 
>  √ Cert Manager v1.8.2
>     √ Install Cert Manager...[Exists]
>     √ Wait for Cert Manager...[OK]
>   √ Install Dev Workspace operator
>     √ Create Namespace devworkspace-controller...[OK]

repeated several hundred times, before it finally gets to the bit about ImagePullBackOff and fails.

I'm about to give up, as it seems che is probably not stable enough for me to use (given the time and resources I have), but I'd like to see che start at least once before I do.

Does anyone know of a combination of versions of che, minikube, OS, etc. that is known to start?

**Comment by LukasGreven** [comment]
Hello there,

I had the same problem as Addlai. I solved this issue by changing the version of my minikube to v1.24.0 and also used the latest stable version of chectl (7.54.0). As your minikube will also inform you while starting it you may have to change the version of kubectl which you are using too.

**Comment by Jinjeok** [comment]
> Hello there,
> 
> I had the same problem as Addlai. I solved this issue by changing the version of my minikube to v1.24.0 and also used the latest stable version of chectl (7.54.0). As your minikube will also inform you while starting it you may have to change the version of kubectl which you are using too.

I had same issue at minikube version 1.27.0. But as you said, after downgrading to version 1.24.0 and re-deploying, it worked normally. thank you!

**Comment by lvl162** [comment]
I've encountered the same problem with Minikube v1.28.0.
I resolved it by 
`docker pull quay.io/eclipse/che-plugin-registry:7.77.0`
then 
`minikube image load quay.io/eclipse/che-plugin-registry:7.77.0`
