### ISSUE TITLE
Grafana dashboards "Number of Users" / "Number of Workspaces" should contain date and № on x and y axis

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14155]
Grafana dashboards "Number of Users" / "Number of Workspaces" should contain date and № on x and y axis respectively to improve readability.

![image](https://user-images.githubusercontent.com/1461122/62706479-e9a90000-b9ef-11e9-882b-28d769758c5c.png)

It would be great to have date and № info on  on x and y axis similar to what already presents on other dashboards:

![image](https://user-images.githubusercontent.com/1461122/62706517-fd546680-b9ef-11e9-8ee7-aaa32f07330e.png)

**Comment by tomgeorge** [comment]
![Screenshot from 2019-09-18 10-23-01](https://user-images.githubusercontent.com/1291508/65162092-5acfd000-d9fe-11e9-8158-54d241ecd934.png)

@ibuziuk how does that look?

**Comment by ibuziuk** [comment]
@tomgeorge could we possibly add current / min / masx values?

**Comment by ibuziuk** [comment]
PR has been merged - https://github.com/eclipse/che/issues/14155. Closing
