### ISSUE TITLE
Devfile: Support for .tar.gz archives

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#14167]
## Summary
I see that the devfile spec supports .zip archives for projects currently, but not other types of archives, such as .tar.gz. We (the Eclipse Codewind) project are looking at some work where we'd like to support .tar.gz project archives in devfiles for Codewind running on Eclipse Che, if possible. Is that something we'd be able to contribute?

## Relevant information
- Devfile spec: https://redhat-developer.github.io/devfile/devfile
- Relevant section on project locations: https://redhat-developer.github.io/devfile/devfile#location

**Comment by ibuziuk** [comment]
@johnmcollier contributions are most welcome cc: @skabashnyuk

**Comment by skabashnyuk** [comment]
CC @evidolob @sunix

**Comment by sunix** [comment]
yes this something to implement in che-theia part. I don't think we handle zip files neither. then ...

> Project’s source location address. Should be URL for git and github located projects, or file:// for zip.

shouldn't it be a zip or tar.gz file located somewhere accessible through http ?
where would the files `file://` be located ?
