### ISSUE TITLE
Deprecate che-lib Github repository

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14161]
### Is your enhancement related to a problem? Please describe.
After merging this pr https://github.com/eclipse/che-lib/pull/141 only two modules will be left in che-lib. I don't see a big value to keep them separate.

### Describe the solution you'd like
move tomcat and swagger assembly to che repository.

### Describe alternatives you've considered
- do not repackage tomcat at all and use tomcat community image tomcat:8.5-jdk-8 (I have some doubts about this since community may think that it would be possible to run it on any J2EE server. I would like to avoid this type of messaging)
- build uber jar(embedded jetty or embedded tomcat) and use java community image openjdk:8
### Additional context
n/a

**Comment by skabashnyuk** [comment]
@nickboldt @vparfonov thoughts?

**Comment by ibuziuk** [comment]
`build uber jar and use java community image openjdk:8` :+1: 
would be really cool to build and start che-server via java -jar IMO

**Comment by ibuziuk** [comment]
@skabashnyuk I moved to `7.2.0` for now, feel free to re-prioritize
