### ISSUE TITLE
Che Operator should use "Rolling" strategy instead of  "Recreate" for postgres deployment

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14166]
Che Operator should use "Rolling" strategy instead of  "Recreate" [1] for postgres deployment

[1] https://github.com/eclipse/che-operator/blob/d16dd077d14b3112e8b6ae44cf712fd8694b7013/pkg/deploy/deployment_postgres.go#L45

**Comment by amisevsk** [comment]
I have concerns that a rolling strategy is not appropriate for `postgres`. Additionally, is it even possible to use `rolling` for pods that mount a RWO volume?

**Comment by gorkem** [comment]
RWO for a PV determines the node attach so technically if a second pod is scheduled to the same node, it can attach to a PV with RWO access mode.

**Comment by ibuziuk** [comment]
My main concern here is the situation with transactions. Wondering if rolling update strategy for db pod guarantees that no transactions will be lost

**Comment by amisevsk** [comment]
Then again, I just tested a rolling update to postgres on the dev cluster and didn't encounter issues.

**Comment by ibuziuk** [comment]
Looks like helm does not specify the deployment strategy and most likely fall back on "Rolling" - https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-postgres/templates/deployment.yaml

**Comment by tomgeorge** [comment]
After doing some research, and reading [kubernetes/kubernetes/26567](https://github.com/kubernetes/kubernetes/issues/26567), there doesn't seem to be a canonical way to protect from corruption in the case where the postgres pod is terminated and restarted.  The update strategy of a deployment provides no guarantees about the data of an application.  It seems like you _could_ protect yourself if you add a [`PreStop` hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) to [quiesce postgres](https://dba.stackexchange.com/questions/183982/make-postgres-database-temporarily-read-only-for-performing-volume-snapshots) (which is hacky in it's own right).

Also, if we use the `Rolling` update strategy, and the pod is scheduled on a different node than where the PV is, it will get stuck in a Multi-Attach loop and end up being unscheduleable until someone manually kills the old postgres pod.  If you get lucky, and the new postgres pod is scheduled on the node that the PV is already attached to, then the rolling update _should_ succeed.

Do we still want to go ahead with the `Rolling` update strategy?  It seems like `Recreate` would at least eliminate the possibility of postgres becoming unscheduleable until manual intervention.

**Comment by gorkem** [comment]
@tomgeorge it would be interesting to see what options exists on postgress operators. Using an operator may have other advantages such as backup and restore support which we do not give at the moment.

**Comment by tomgeorge** [comment]
I've been looking at the [crunchydata postgres operator](https://access.crunchydata.com/documentation/postgres-operator/4.0.0/gettingstarted/design/designoverview/), which seems to be the de facto option for Postgres on Kubernetes, and is listed on operatorhub.io.

It can do automatic failover, backups, restores, and replication. Standing up the operator was a bit of an involved process, and I wonder how badly we need replicated, HA postgres for Che.  It was relatively easy to configure che and keycloak to talk to the external postgres cluster provisioned by the operator.

**Comment by ibuziuk** [comment]
PR merged https://github.com/eclipse/che/pull/14664
Clsosing
