### ISSUE TITLE
Theia should not notify that an app is listening on an endpoint when that app restarts

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14160]
### Is your enhancement related to a problem? Please describe.
Theia pops up a fullscreen notification whenever an application starts listening on an exposed endpoint:

![Screenshot from 2019-08-08 09-55-45](https://user-images.githubusercontent.com/16168279/62709154-d0d62580-b9c2-11e9-8b47-65a4c3d446c1.png)

This is useful when first launching an app, but since this notification pops up *every* time an app starts listening on that port, it can be incredibly annoying at times. Examples:

1. Some workflows (e.g. `nodemon`-based ones) rebuild changes continually. When a syntax error is saved, the build fails and the service restarts when it is resolved, meaning that the notification can appear continually while editing files. This is made worse by autosave.

2. If you stop and restart a server the notification appears again. This can be mildly annoying if you're just rebuilding or restarting for some simple reason.

### Describe the solution you'd like
Theia should show the notification only the first time an application listens on each port. Subsequent notifications should be at most a drop notification from the top, and could in many cases be hidden entirely.

### Describe alternatives you've considered
None, really.

**Comment by ibuziuk** [comment]
moving to `7.2.0` for now @benoitf maybe we could have some checkmark on the pop-up e.g. `always expose / remember my decision` ?

**Comment by Katka92** [comment]
This pop-up seems quite useless for me, because if I have a preview opened and the pop-up is shown, I can select `Open Link`, but it does basically nothing - I need to manually refresh the preview anyway.
