### ISSUE TITLE
Refresh the documentation "Installing the chectl management tool" to current reality.

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14162]
In https://www.eclipse.org/che/docs/che-7/che-quick-starts.html the "Installing the `chectl` management tool" section is pointing to an old version of `chectl`  from the month of march, https://github.com/che-incubator/chectl/releases/tag/20190314232124

Since then multiple releases of `chectl`  occurred, and the latest releases are not anymore in a single binary for all Linux versions, but in a compressed archive depending on the architecture.

We should update the documentation to the reality of the latest release.
We should also not hard code the version of `chectl` in the documentation.

**Comment by themr0c** [comment]
@rkratky would you please add the label 'area/doc', I do not have the necessary rights in this repository.

**Comment by themr0c** [comment]
@l0rd Can we assume that the latest released version of `chectl` is and will stay the preferred version of `chectl` that should be used to deploy Che?

**Comment by ibuziuk** [comment]
@themr0c this one is for GA, right ?

**Comment by themr0c** [comment]
@ibuziuk This one need to be fixed soon most probably. The version that should be used need to be defined first.

**Comment by nickboldt** [comment]
I would think once 7.0.0.GA is out we can point people at the 7.0.0.GA tagged version of chectl, right?

**Comment by l0rd** [comment]
Thanks @themr0c for opening this issue. I think that we can:
- **right now**: update the doc with a link to latest released version (even if unstable)
- **as part of https://github.com/eclipse/che/issues/14114**: update the doc using a permanent link to the latest stable chectl

**Comment by themr0c** [comment]
Which installation method is preferred? The documentation in https://github.com/che-incubator/chectl needs clarification also :

* For Linux and MacOS, running script downloaded from  https://www.eclipse.org/che/chectl/
 seems the preferred method as downloading the archive is flagged as "manual". Is that still the intention now?

* For Windows, we need to document how to download the archive anyway.
