### ISSUE TITLE
Plugin Broker should support relative paths

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14163]
### Is your enhancement related to a problem? Please describe.
To support offline plugin brokering, it's necessary for the plugin registry to know its own route. Since extension urls are set at build time, caching extensions locally within the registry (or elsewhere on the cluster) would require updating every `meta.yaml`'s extensions field at startup.

### Describe the solution you'd like
The Che plugin broker currently supports downloading extensions via URL or [reference to a vscode extension](https://github.com/eclipse/che-plugin-broker/blob/master/brokers/unified/vscode/broker.go#L241). 

To support https://github.com/eclipse/che/issues/14115, the broker should also support relative links. E.g. the reference:
```
extensions:
  - relative:/path/to/resource.vsix
```
would resolve to `${CHE_WORKSPACE_PLUGIN__REGISTRY__URL}/path/to/resource.vsix`.

This would avoid having to update links at runtime in the offline case.

### Describe alternatives you've considered
The main alternative is as suggested in https://github.com/eclipse/che/issues/14115: 
> Implement a bash script that updates vsix and svg URLs hostnames in meta.yaml files. The new hostname value should be `${CHE_WORKSPACE_PLUGIN__REGISTRY__URL}`

### Additional context
This shouldn't be very difficult to implement, so even if it's a temporary solution I think it's important.

**Comment by nickboldt** [comment]
will this change work for icons (.svg files) and theia extension (.theia files) too ? Need that as well as .vsix files for the air gap / offline / plugin-registry-all-in-one container solution planned for CRW 2.0

**Comment by amisevsk** [comment]
It should be workable for `.theia` files without problem but I'm less sure on icons. As far as I can tell icons are ignored everywhere at the moment.

**Comment by nickboldt** [comment]
if this is a hard target of 7.1.0 I'd raise it to P1 or even blocker. "enhancement" sounds like "when I have time and all my P0, P1, and P2 work is done and my doc updates are done and I still have time left in the sprint" ... or am I reading too much into a label? :D

**Comment by amisevsk** [comment]
@nickboldt Currently the plan is to pull it into our next sprint, it'll probably be the first thing I work on ;)

**Comment by ibuziuk** [comment]
@amisevsk can we close this one ?
