### ISSUE TITLE
chectl fails to request Che Server if it's deployed with self-signed-cert flag

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14179]
### Describe the bug
Chectl fails to request Che Server if it's deployed with self-signed-cert flag.
As a result it's not possible to perform any operation where chectl requests Che Server: server:stop, workspace:list, workspace:start.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che with self-signed-cert enabled. Detailed instructions on how to do it can be found here https://github.com/eclipse/che/issues/14035#issuecomment-519822676
2. Try to do server:stop or workspace:start.

### Expected behavior
chectl performs the specified operation.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot_20190809_143348](https://user-images.githubusercontent.com/5887312/62776511-78328580-bab3-11e9-8733-fd2fe6c5ca5e.png)
![Screenshot_20190809_143413](https://user-images.githubusercontent.com/5887312/62776512-78cb1c00-bab3-11e9-9783-27013df9ad73.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
I think the solution here is the following: chectl should check Che Server deployment is self-signed certificate is configured, if yes - grap the configured secret with self-signed-cert and use it for requests to Che Server.

**Comment by tolusha** [comment]
Can't reproduce anymore
