### ISSUE TITLE
chectl server:start does not expose all images for override

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14186]
### Describe the bug

As of today, there are 2 images that can be overriden via [commandline flags with chectl](https://github.com/che-incubator/chectl#chectl-serverstart):

```
  -i, --cheimage=cheimage                      [default: eclipse/che-server:nightly] Che server container image
  --che-operator-image=che-operator-image      [default: quay.io/eclipse/che-operator:nightly] Container image of the operator. This parameter is used only when the installer is the operator
```

If a user wants to override ALL the images, they must use a custom resource yaml file.

```
  --che-operator-cr-yaml=che-operator-cr-yaml  Path to a yaml file that defines a CheCluster used by the operator. This parameter is used only when the installer is the operator.
```

But this is inconsistent behaviour. Why are only 2 of the 7 images available as commandline flags? This requires that airgap deployments use a CR file, and that users understand WHY they have to use a CR file instead of just passing in overrides via commandline.

The complete list of images (7):

* quay.io/eclipse/che-operator:nightly
* eclipse/che-server:nightly
* eclipse/che-keycloak:nightly
* quay.io/eclipse/che-devfile-registry:nightly
* quay.io/eclipse/che-plugin-registry:nightly
* centos/postgresql-96-centos7:latest
* registry.access.redhat.com/ubi8-minimal:8.0

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. `chectl server:start --help`

```
  -i, --cheimage=cheimage                      [default: eclipse/che-server:nightly] Che server container image
  --che-operator-image=che-operator-image      [default: quay.io/eclipse/che-operator:nightly] Container image of the operator. This parameter is used only when the installer is the operator
```

### Expected behavior

One might argue that all 7 images could be passed via commandline, not just server and operator.

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by benoitf** [comment]
side note: I don't know if `oclif` allow custom flags based on a given choice
b/c for example we have parameters that should be specific to some platforms/installers (for example domain is only for kubernetes but we can see it for all platforms)

**Comment by nickboldt** [comment]
Related to #14589

**Comment by tolusha** [comment]
This PR allows to override any property in cr file
https://github.com/che-incubator/chectl/pull/508
