### ISSUE TITLE
Che Theia images are built with different versions of Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#14187]
### Describe the bug

[Build script](https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia-endpoint-runtime/build.sh) for `theia-endpoint-runtime` image doesn't respect `--branch` argument.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Building Che Theia images with the command
```
./build.sh --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=${THEIA_VERSION} --tag:${IMAGE_TAG} --branch:${THEIA_BRANCH} --git-ref:${THEIA_GIT_REFS} --skip-tests
```
where `--branch` argument points to [che-7.0.0](https://github.com/theia-ide/theia/tree/che-7.0.0) Theia branch,
leads to the different versions of the [`plugin-ext`](https://github.com/theia-ide/theia/tree/master/packages/plugin-ext) package included into [`che-theia`](https://hub.docker.com/r/eclipse/che-theia) and [`che-theia-endpoint-runtime`](https://hub.docker.com/r/eclipse/che-theia-endpoint-runtime) images:
- `che-theia` image consumes `plugin-ext` package from the Theia sources
- `che-theia-endpoint-runtime` image consumes `plugin-ext` package from npm registry

### Expected behavior

`che-theia` and `che-theia-endpoint-runtime` images must be based on the same Theia version, depending on the specified `--branch` argument.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by RomanNikitenko** [comment]
I faced with the same problem.
Do we have some workaround?

**Comment by evidolob** [comment]
No we don't have, I'm working on it

**Comment by sunix** [comment]
@evidolob what do we do with this ?
