### ISSUE TITLE
Support single-host/default-host in multi-user server mode

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#14189]
### Is your task related to a problem? Please describe.
During the spike https://github.com/eclipse/che/issues/14002, we've identified the issues with single-host mode (where workspaces are exposed using the host name of the Che server on unique subpaths) on Kubernetes (we don't support this mode at all on Openshift).

PR https://github.com/eclipse/che/pull/14134, developed during the spike investigation, fixes the support for single-host and default-host exposure strategies in the single-user mode.

We need to support single-host also in multi-user mode but that is unfortunately more complex.

There seems to be a problem with exposing the servers in the multiuser mode. Both secured (proxied by jwt proxy) and non-secured servers (e.g. exposed components) seem to be created or at least queried incorrectly, resulting in failed startup with the message:

```
Error: Workspace doesn't have a server which matches with URL: http://192.168.99.121.nip.io/?uid=558503
```

Notice the URL that doesn't really make sense.

### Referenced Issues
This issue stems from the spike https://github.com/eclipse/che/issues/14002 and blocks https://github.com/eclipse/che/issues/12971.

**Comment by sleshchenko** [comment]
I think closing if this issue also mean solving https://github.com/eclipse/che/issues/14189
@metlos Can you confirm?

**Comment by metlos** [comment]
> I think closing if this issue also mean solving #12971
> @metlos Can you confirm?

Yes, that issue exactly describes the problems that we're solving here.

**Comment by metlos** [comment]
https://github.com/eclipse/che/pull/14335 is merged.
