### ISSUE TITLE
[chectl] install.sh should provide switch for selecting installation path

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14184]
### Is your enhancement related to a problem? Please describe.
Currently,  `bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next` installs chectl into `/usr/local/bin/chectl`

For the purposes of CI usage, this might not be perfect and having option `--install-path` would be nice.

### Describe the solution you'd like
Adding switch allowing user to install chectl to any directory:
`bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next --install-path=/home/user/bin` for example

**Comment by benoitf** [comment]
at the end, the script execute the binary, so it will check that in your case
`/home/user/bin` was added to the `PATH`

is it OK ?

**Comment by rhopp** [comment]
I'm not sure if modifying user's `PATH` is something this script should do... Couldn't it instead of `chectl version` it could call `${INSTALL_PATH}/chectl version`? 

And if we would like to be really fancy, we could print some message if we found out, chectl is not on PATH like:
"Chectl is not on your PATH. If you want to add it, please execute `PATH=${INSTALL_PATH}:$PATH`"
