### ISSUE TITLE
Debugging nodejs projects seems to be impossible

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14190]
### Describe the bug
Debugging the sample projects included in the NodeJS Angular, Mongo, and React devfiles seems to not be possible currently. 

I was able to work around these issues for the simple Node Express [devfile](https://github.com/eclipse/che-devfile-registry/pull/69) but cannot figure it out for the others.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Start e.g. the NodeJS Angular devfile in Che and attempt to debug. 

### Expected behavior
It is clear how to debug the application, or clear that debugging is not possible for some reason.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

**Comment by benoitf** [comment]
@amisevsk is area is che-theia or che-languages ?

I mean, the issue that you're facing is how to see breakpoints menu, etc or that you're not able to use the typescript debugger ?

**Comment by amisevsk** [comment]
@benoitf The issue is that connecting a debugger to the application is impossible; none of the options in Theia work. As far as I understand, the nodejs debug configurations come built-in to Theia, but I'm not sure what the best area is for this, it's likely a combination of a devfile issue and a debugger issue.

As a user, I could not get debugging to work in those three devfiles.

**Comment by tsmaeder** [comment]
@amisevsk trying to find out what you're doing exatly, here: are you using a launching configuration or are you running the application in the dev or runtime container and trying to do remote debugging?

**Comment by amisevsk** [comment]
@tsmaeder It has been awhile and I know the Theia side has reworked the nodejs debugging options, but I tried every debug config autocompletion and could not get it to work. I haven't tested in a month though, so it may be resolved -- I'll double check when I have a moment.
