### ISSUE TITLE
Support private Github repo to get Vscode extension (.vsix) file

### ISSUE THREAD

**Issue by PrasangAPrajapati** [eclipse-che/che#14191]
### Describe the bug
In `che-plugin-registry`, allow users to pass login credentials for Github to the plugin broker so it can authenticate with Github to pull a `.vsix` file

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
We should allow user to pull down a `.vsix` from a private Github or allow user to pass credentials for any `https/ftp` support  to test it out first before publishing it to the Vscode MarketPlace. I see strong reason for doing this because every time when we update a Vscode extension version release we want to test it on che as well to confirm if it works well and then if everything works well then we can go ahead and release a new version in marketplace so it won't break user's workspace because we pull latest build of vscode extension nightly in che.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by nickboldt** [comment]
This might be a feature that helps with airgap customers who use GitHub Enterprise or private repos outside their org. +1 for getting this into Che 7.x. @l0rd @slemeur @benoitf  WDYT?

**Comment by phaumer** [comment]
What makes this also critical is the reason that Microsoft does not allow you setting in-house Marketplace servers.

**Comment by PrasangAPrajapati** [comment]
@nickboldt @l0rd @slemeur @benoitf  any update on this ?

**Comment by l0rd** [comment]
@PrasangAPrajapati we haven't been able to work on this. That's something that has lower priority currently.

**Comment by l0rd** [comment]
@PrasangAPrajapati but yes that is a useful use case. If you are willing to contribute a PR we will be happy to support.
