### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wu560130911** [eclipse-che/che#142]
git log
commit d2ab49ad09e9f42e874872dfe1884e4ddc06ec14
Merge: 2815a83 1a5ee0d
Author: Alexander Garagatyi agaragatyi@codenvy.com
Date:   Fri Dec 25 16:37:40 2015 +0200

```
Merge pull request #141 from codenvy/IDEX-3726

IDEX-3726: adopt ws agent to run it as common machine process
```

[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ assembly-ide-war ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /home/wu560130911/projects/che/assembly-ide-war/target/classes
warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.7'
/home/wu560130911/projects/che/assembly-ide-war/src/main/java/org/eclipse/che/api/deploy/ApiModule.java:116: error: cannot find symbol
        bindConstant().annotatedWith(Names.named(DockerMachineExtServerLauncher.WS_AGENT_PROCESS_START_COMMAND))
                                                                               ^
  symbol:   variable WS_AGENT_PROCESS_START_COMMAND
  location: class DockerMachineExtServerLauncher
1 error
1 warning

**Comment by garagatyi** [comment]
try to recompile it with `mvn clean install -U`

**Comment by wu560130911** [comment]
it's  still like this.
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ assembly-ide-war ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /home/wu560130911/projects/che/assembly-ide-war/target/classes
warning: Supported source version 'RELEASE_6' from annotation processor 'org.jvnet.hudson.annotation_indexer.AnnotationProcessorImpl' less than -source '1.7'
/home/wu560130911/projects/che/assembly-ide-war/src/main/java/org/eclipse/che/api/deploy/ApiModule.java:116: error: cannot find symbol
        bindConstant().annotatedWith(Names.named(DockerMachineExtServerLauncher.WS_AGENT_PROCESS_START_COMMAND))
                                                                               ^
  symbol:   variable WS_AGENT_PROCESS_START_COMMAND
  location: class DockerMachineExtServerLauncher
1 error
1 warning

**Comment by ghost** [comment]
Same story using the latest code from master?

**Comment by TylerJewell** [comment]
Closing issue due to no response / feedback.  Unable to reproduce.  Please re-open if still exists and can document.
