### ISSUE TITLE
Mark old quay repo eclipse-che/che-operator deprecated in favour of eclipse/che-operator; delete old tags

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14205]
New repo: https://quay.io/repository/eclipse/che-operator?tag=nightly&tab=tags
Old repo: https://quay.io/repository/eclipse-che/che-operator?tag=nightly&tab=tags 

We should purge the old tags from `eclipse-che/che-operator` so no one thinks this is the state of the art latest stuff:

* 7.0.0-RC-2.0
* 7.0.0-beta-5.0

And these from new repo `eclipse/che-operator`:

* 7.0.0-beta-3.0

We could also consider simply deleting the old repo:

![image](https://user-images.githubusercontent.com/227597/62879304-d43a1b80-bcf8-11e9-9502-17bad17dfe6c.png)

**Comment by nickboldt** [comment]
Per @benoitf 's suggestion:

![image](https://user-images.githubusercontent.com/227597/62879469-2e3ae100-bcf9-11e9-8e80-074984c6d44e.png)

**Comment by ibuziuk** [comment]
@nickboldt are you going to work on this one?

**Comment by nickboldt** [comment]
I've added the deprecation note. 

If someone agrees we should delete the old tags, I can do so. 

If we'd also like to delete the old repo, we can do that too, but that might break some people so the deprecation warning is probably better.

Let me know which tags (or all the pre 7.0.0.GA ones?) should be deleted and I can spend the 30 seconds to do so :)

**Comment by benoitf** [comment]
+1 to delete

**Comment by ibuziuk** [comment]
+1 to delete cc: @davidfestal are you ok ?

**Comment by davidfestal** [comment]
Yes

**Comment by nickboldt** [comment]
I've also marked these deprecated as their last tags are >1mo old:

https://quay.io/organization/eclipse-che
* https://quay.io/repository/eclipse-che/che-devfile-registry
* https://quay.io/repository/eclipse-che/che7-java11-maven
* https://quay.io/repository/eclipse-che/che7-java8-maven

New repos:

https://quay.io/organization/eclipse
* https://quay.io/repository/eclipse/che-devfile-registry
* https://quay.io/repository/eclipse/che7-java11-maven
* https://quay.io/repository/eclipse/che7-java8-maven
