### ISSUE TITLE
Impossible to start Che 7 on certain OS 4 due to expired liveness probe

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14209]
### Describe the bug
On certain OCP 4.1, it not possible to start Che 7. 

The problem comes from the Che start which could be quite long, and liveness probe is expired before the expiration of the readiness probe, which cause the Che POD to be constantly restart.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Following: https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-4-from-operatorhub/

### Expected behavior

Che is up and running.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other: RHPDS
   - [ ] other: please specify

**Comment by nickboldt** [comment]
If this can be committed before EOD, it can be included in 7.0. If not, it slips back to 7.1 / P1.

**Comment by davidfestal** [comment]
The PR has been merged to master.

**Comment by amisevsk** [comment]
Closing issue to clean up the milestone, reopen if it's still present :)
