### ISSUE TITLE
bug(regression): starting a task from `my workspace` view is not starting it ...

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#14204]
### Describe the bug
Having some commands available in the `my workspace` view, when clicking on one of them, instead of running the task, che-theia is popping up the command palette with the list of task.

### Che-theia version

 - [x] 7.0.0-next

### Steps to reproduce
1. Start a workspace from this devfile: https://github.com/sunix/che-quarkus-demo/blob/master/devfile.yaml
2. once the workspace is started, run one of the task from the `my workspace` view.

### Expected behavior
The task is supposed to be starting. But instead it is showing a command palette with a list of available tasks ... 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift 4 (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Eclipse Che | quarkus-che-demo - Google Chrome_381](https://user-images.githubusercontent.com/650571/62878031-9654eb80-bd28-11e9-89ed-42681c5cb825.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by RomanNikitenko** [comment]
@sunix 
did you tried to start terminal from the same panel?
did you tried to open a link for any endpoint?
could you confirm that only tasks are broken for the panel?

why I am asking - terminals and endpoints are not working for me as well, but I tested on minikube... 

thank you!

**Comment by RomanNikitenko** [comment]
I investigated the issue, the cause of the problem that [here](https://github.com/theia-ide/theia/blob/252cffdc79574b6d7a505b71e728d0319d281345/packages/plugin-ext/src/plugin/tree/tree-views.ts#L245-L247) arguments for commands are overridden by `id`.

So at least all actions from `My workspace` view are broken.
We need clarify why it was done to fix `My workspace` view and do not broke another behavior.

**Comment by RomanNikitenko** [comment]
@sunix 
I think we should change the title for the issue - all actions from `My workspace` view are broken

**Comment by gorkem** [comment]
@RomanNikitenko Does this affect the open terminal too? Opening a terminal from 'My Workspace' fails for me. I was about to open an issue but if it is the same cause I will just add a note here.

**Comment by RomanNikitenko** [comment]
@gorkem 
Opening a terminal and opening a link for any endpoint from  `My Workspace` panel is not working for me. 
The cause of the problem [the same](https://github.com/eclipse/che/issues/14204#issuecomment-520590519)

**Comment by vinokurig** [comment]
> I investigated the issue, the cause of the problem that [here](https://github.com/theia-ide/theia/blob/252cffdc79574b6d7a505b71e728d0319d281345/packages/plugin-ext/src/plugin/tree/tree-views.ts#L245-L247) arguments for commands are overridden by id.

This was done in the vscode way: https://github.com/theia-ide/theia/pull/5661

**Comment by sunix** [comment]
I still can't have it working ... has the build failed ?
