### ISSUE TITLE
Impossible to scroll in plugin list on dashboard

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14211]
### Describe the bug
Impossible to scroll down into the list of plugins from the dashboard.
![Capture d’écran 2019-08-13 à 13 56 52](https://user-images.githubusercontent.com/1636769/62939819-695d1300-bdd2-11e9-933e-b10e02b42058.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace, go to the workspace configuration
2. Select plugin, try to scroll down

### Expected behavior
User can scroll in the list of plugins

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
see above

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other: RHPDS
   - [ ] other: please specify

**Comment by slemeur** [comment]
Chrome MAC OS X Version 76.0.3809.100

**Comment by slemeur** [comment]
Refreshing fixed the problem

**Comment by amisevsk** [comment]
I also experience this from time to time, on Fedora + Chrome Version 76.0.3809.100

**Comment by gorkem** [comment]
Work on this after https://github.com/eclipse/che/pull/13942 is merged.
