### ISSUE TITLE
Allow overriding of all images used in Che deployment when using operator

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14216]
### Describe the bug

Today, the references to the plugin brokers (both of them? are both still needed/used?) are in 

https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L571-L574

Which means to update that to a new version, or to use a productized version, or a path-to-my-organization's-airgapped-artifactory version, a user/customer has to hardcode new defaults and rebuild the Che server. This is awkward as it means literally forking the codebase just to point to a new container image.

### Proposed solutuon 

A better solution would be to have these values stored as env vars, as we do for other deployments like the devfile and plugin registries, so that they can be changed after deployment but before starting the first workspace. 

And this decouples the versioning too, so that the same Che server can be used with a newer plugin broker, should a fix be needed in one but not the other.

We should also expose these env vars to the operator so that it can assign them via a custom resource.yaml file (as we do when deploying Che with `chectl`).

**Comment by davidfestal** [comment]
@nickboldt For all Che properties that are not set (in the `che` config map) and kept in sync by the Che operator, you can add them (with the right upper-case-based format) to the `custom` config map.
You can even create the `custom` config map before/at the same time as the `CheCluster` custom resource.

**Comment by nickboldt** [comment]
So we can set these env vars after deploying Che server?

* CHE_WORKSPACE_PLUGIN__BROKER_INIT_IMAGE
* CHE_WORKSPACE_PLUGIN__BROKER_UNIFIED_IMAGE

**Comment by davidfestal** [comment]
Yes, you add them to the `custom` config map, and restart the POD.

**Comment by davidfestal** [comment]
This should be fixed by fixing issue https://github.com/eclipse/che/issues/14635 and the linked documentation issues.
Do you agree @nickboldt ?

**Comment by l0rd** [comment]
@nickboldt `CHE_WORKSPACE_PLUGIN__BROKER_INIT_IMAGE` `CHE_WORKSPACE_PLUGIN__BROKER_UNIFIED_IMAGE` are the only 2 images that are left out?

We need to be able to configure all of these ones:
- che-server
- jwt-proxy
- machine-exec
- che-theia
- che-keycloak
- postgresql-96-centos7
- che-operator
- che-devfile-registry
- che-plugin-registry
- ubi8-minimal (for the pvc)

**Comment by l0rd** [comment]
@davidfestal @ibuziuk I have added this issue to 7.3.0 milestone because it will be addressed by https://github.com/eclipse/che/issues/14635 and it's mandatory for CRW 2.0

**Comment by amisevsk** [comment]
Updated title to reflect expanded scope (not just plugin brokers)
