### ISSUE TITLE
bug: Kubernetes plugin is failing to start

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#14210]
### Describe the bug
The kubernetes plugin is failing to start.
The workspace sometime is running fine and sometimes not
I got 

### Che version

 - [ ] latest
 - [x] nightly, che-theia 7.0.0-next
 - [ ] other: please specify

### Steps to reproduce
create a workspace, save and edit, and add the kubernetes plugin (latest version) from the plugin tab of the dashboard and start the workspace:
The kubernetes side car container is failing to start

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Eclipse Che | che7-readme-update-e - Google Chrome_386](https://user-images.githubusercontent.com/650571/62936629-9efdfe00-bdca-11e9-9d96-548a750c2c6e.png)

![Eclipse Che | che7-readme-update-e - Google Chrome_387](https://user-images.githubusercontent.com/650571/62936614-986f8680-bdca-11e9-91b4-f8bd31360bea.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
The issue is due to not enough memory for plugin sidecar:
```
State:          Waiting
      Reason:       CrashLoopBackOff
      Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```
Patch has been proposed in the PR https://github.com/eclipse/che-plugin-registry/pull/202

**Comment by sunix** [comment]
I have to test again ... it looks like it works with https://raw.githubusercontent.com/azatsarynnyy/devfiles/master/k8s-devfile.yml
So I will investigate what is the difference with my other devfiles

**Comment by sunix** [comment]
@azatsarynnyy thanks. I tried the 1.0.0 version and it was working as it has enough memory on this one. But i am confused what is the difference between `1.0.0` and `0.1.17` ? should we remove 1.0.0 ?

**Comment by azatsarynnyy** [comment]
@sunix `1.0.0` and `0.1.17` correspond to different versions of VS Code Kubernetes extension. Maybe it should be mentioned in the `description` field of the plugin's meta.yml.

I agree that it makes sense removing the previous versions of Che Plugins but w/o surprising the user :slightly_smiling_face: 
I think we should have kindof Plugin version deprecation policy.

**Comment by sunix** [comment]
This is good. I had just been confused that 1.0.0 and latest were based on the same 1.0.0 but had not the same memory settings
