### ISSUE TITLE
SSH Create key empty input

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#14218]
`SSH: Create key pair...` command allows private key and public key inputs to be empty. We either should not allow those inputs to be empty or fail at the end with the creation of the key pair with empty keys. 
Also check if the entered values are valid. For instance if I mistakenly enter something like `*.mydomain.com` as the domain name during generation because this is converted into a volume mount, it would break all the workspaces completely.

**Comment by monaka** [comment]
As I reported in #14272, we should validate `name` in `/api/ssh/generate`. So I added `team/platform` label.

**Comment by monaka** [comment]
the parameter `name` should be used after hashed (similar to https://github.com/eclipse/che/pull/14243).
Because the length of FQDN name may be more than 63 (the limit of name for Kubernetes objects).
