### ISSUE TITLE
Debugging with the python plugin behaves strangely

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14219]
### Describe the bug
There are numerous issues with trying to debug in the `python-simple` devfile. 

- It's only possible to use code completion to generate debug configs if `launch.json` does not already exist
- Debug > Add configuration does not work.
- Many of the suggested generate options seem to do nothing when clicked.
- Once created, I can't get any of the debug configurations to work.

### Che version
Server: `eclipse/che-server:nightly-centos`
Python Plugin: `ms-python/python/latest`
Workspace: `quay.io/eclipse/che-python-3.6:nightly`, `eclipse/che-theia:7.0.0-next`, `eclipse/che-remote-plugin-python-3.7.3:7.0.0-next`

### Steps to reproduce
1. Start python-simple devfile
2. Open hello-world.py and set breakpoint on print statment
3. Navigate `Debug > Open Configurations`
   - Instead of opening debug configurations, Che shows a dropdown with options: (Only "Python File" does anything)
   ![python-debug-options](https://user-images.githubusercontent.com/16168279/62973952-25273e00-bde5-11e9-9068-65af26882f63.png)

4. Create "Python File" debug config and try to launch
   - > Timeout waiting for debugger connection
5. Attempt to add different debug configuration
   - Completion just shows "Python" entry that does nothing:
    ![python-debug-autocompletes](https://user-images.githubusercontent.com/16168279/62973980-34a68700-bde5-11e9-8914-64b80fa26045.png)

   - It's no longer possible to add debug configurations via completion until `launch.json` is **deleted**

### Expected behavior
Something simpler than the above

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by amisevsk** [comment]
Potentially related: https://github.com/eclipse/che/issues/13816, although this issue applies to a simple "hello world" application.

**Comment by tsmaeder** [comment]
Suspicion from @tolusha is that some VS Code API is missing in Theia that is used here.

**Comment by tolusha** [comment]
Investigation shows Theia  seems to misbehave. Theia collects configurations snippets and shows them during completion in `launch.json`. But python plugin doesn't have any configurations snippets. The only way to request configurations is to invoke `provideDebugConfiguations` method when use select `Python` entry. But it never happens.

There is particular case when  `provideDebugConfiguations` is invoked [1]. It happens when there is no `launch.json` and any python file is opened in the editor. 

[1] https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-configuration-manager.ts#L274

**Comment by tolusha** [comment]
![Screenshot from 2019-09-03 17-27-37](https://user-images.githubusercontent.com/1640675/64182055-3efdf300-ce70-11e9-92ea-415feb79607a.png)
![Screenshot from 2019-09-03 17-27-31](https://user-images.githubusercontent.com/1640675/64182057-3efdf300-ce70-11e9-94e5-39c042e14716.png)
