### ISSUE TITLE
SSH View public key

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#14215]
If I invoke the `SSH View public key` command before generating an SSH key it does nothing and feels like the command did not work. In this case we should instead show a warning that no SSH keys exists.

**Comment by gorkem** [comment]
Same issue with delete key as well. It would be great to state that if there are no keys to delete instead of displaying an empty box.

**Comment by vinokurig** [comment]
fixed by https://github.com/eclipse/che-theia/pull/448
