### ISSUE TITLE
Stabilize E2E Happy path tests as on openshift (OKD 3.11) infra in CentralCI

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14227]
### Description
Currently, we are running Happy path test as PR check in this repository on Che deployed on openshift infrastructure. We should stabilize it and get rid of flakyness.

**OS and version:**    

**Diagnostics:**

**Comment by rhopp** [comment]
Subissue: https://github.com/eclipse/che/issues/13979

**Comment by SkorikSergey** [comment]
Jenkins job for HappyPath test on OKD - https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che7-pr-happy-path-test-OKD/.
