### ISSUE TITLE
che-docs: yaml on che-docs site have broken formatting

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14220]
### Describe the bug
che-docs: yaml on che-docs site have broken formatting.
For example the following page https://www.eclipse.org/che/docs/che-7/installing-che-on-google-cloud-platform/ has:
![Screenshot_20190814_104243](https://user-images.githubusercontent.com/5887312/63003242-70daf580-be80-11e9-9791-38b8470a04b1.png)

**Comment by slemeur** [comment]
Is that something you can look at @rkratky ?

**Comment by sleshchenko** [comment]
Is fixed by https://github.com/eclipse/che-docs/pull/785
