### ISSUE TITLE
Investigate Support for multi-root workspaces with PHP plugins

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14225]
We need to investigate how our PHP support works with multi-root workspaces. In particular, what happens when we start with an empty workspace, then "add folder to workspace", then add a second workspace root.

**Comment by tsmaeder** [comment]
Also, inspecting the code would be a good idea.

**Comment by tsmaeder** [comment]
Steps to test would be:
1. Create an empty workspace in Theia (I know how, it's simple)
2. Add a php project as a workspace root
3. Ensure language features (code assist, etc.) work (filing issues for stuff that does not)
4. Add a second project as a workspace root 
5. Test language features work

**Comment by vrubezhny** [comment]
I've tested the multi-root workspace support with PHP Intelephense, using v.1.0.13 of the extension by setting the value `workspace.supportMultiRootWorkspace` preference to `true` and going through the following the steps: https://github.com/eclipse/che/issues/14225#issuecomment-521644862

For all the projects added by `Add Folder to Workspace` command I was able to see the hovers, invoke content assistant and edit the contents of the php-sources in every added project.

open terminals for each of the projects as well as for the initially opened folder.

Also I've followed the list of requirements described in https://github.com/theia-ide/theia/issues/1660. The most of them are seem to be met (those I could spot visually while working with projects), like:
* Search shows the results for all the projects with occurrences, separating the results by project roots.
* Workspace name is displayed at the header of the Project Explorer
* A previously saved (into a `*.theia-workspace` file) can be opened with `Open Workspace` command.
* `Open Terminal` command suggests to open a terminal view from the list consisting of  the workspace folder as well as the every project-root folder added to the workspace.
* When making `Drag&Drop` on a folder between two projects in a milti-root workspace, the folder gets moved into a destination project and removed from the target project. LS is functional on the files of the moved folder.
* Editor filename tooltip as well as Project explorer filename tooltip shows the full filename.

**Comment by tsmaeder** [comment]
@vrubezhny what about document symbols and hover, as mentioned in https://github.com/eclipse/che/issues/13427#issuecomment-520501345 ?

**Comment by JPinkney** [comment]
@tsmaeder I think it was actually my misunderstanding of PHP for those issues. I believe everything is working as expected as documented in https://github.com/eclipse/che-theia/pull/408. 

The PHP plugin doesn't show document symbols and hover for super basic elements like echo "Hello World" but when you actually make a PHP class everything was working as expected (I found this out after that comment was posted)
