### ISSUE TITLE
Align development flow for vscode extensions

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14228]
### Is your task related to a problem? Please describe.
Align development flow for vscode extensions. Should be useful for docs: https://github.com/eclipse/che/issues/14119

### Describe the solution you'd like
We can:
- [x] apply yeoman vscode extension generator in the eclipse/che-theia-dev image.
- [x] activate ability generate vscode extension using https://github.com/eclipse/theia-yeoman-plugin

**Comment by benoitf** [comment]
VS Code generator is also already in Theia image: https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/Dockerfile#L146

**Comment by sunix** [comment]
for packaging: https://github.com/Rijul5/vscode-teletype/blob/master/devfile.yaml#L60

**Comment by AndrienkoAleksandr** [comment]
@vitaliy-guliy https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia-dev/Dockerfile#L47

**Comment by vinokurig** [comment]
Depends on https://github.com/eclipse/che/issues/15443
