### ISSUE TITLE
Welcome plugin uses absolute paths to reference page elements

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#14233]
The welcome plugin generates links to the elements on the page using an absolute path (for example here: https://github.com/eclipse/che-theia/blob/master/plugins/welcome-plugin/src/welcome-page.ts#L30).

This leads to the page being broken in the single-host or default-host server strategy where such URLs become invalid (because the workspace itself is deployed on a subpath instead of in the root path of a subdomain).

**Comment by slemeur** [comment]
needed for: https://github.com/eclipse/che/issues/14189

**Comment by mmorhun** [comment]
@metlos could you please elaborate a bit more on the problem, because I've checked the logo image from issue title and the path to it is relative:
![image-path](https://user-images.githubusercontent.com/15607393/64687872-f65bc080-d493-11e9-8240-7405bbb91a69.png)

**Comment by metlos** [comment]
@mmorhun, yep, it is now relative. Not sure what caused the change.

**Comment by mmorhun** [comment]
I've checked other resources (which I could found in the plugin) including css and js: all of them have relative path.
@metlos can we resolve this issue?
