### ISSUE TITLE
Run Happy Path tests nightly on multiuser installation

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14234]
Currently, we are running happy path tests only on single-user installations of Che.

We should create jobs for running Happy Path tests also against multiuser installations.

**Comment by slemeur** [comment]
@rhopp : When are you planning this one?

**Comment by rhopp** [comment]
We should also use TLS if possible (if it's not easily possible, we should create a new issue for this)

**Comment by dmytro-ndp** [comment]
Usage of TLS in Eclipse Che is not easily possible in version 7.6.0 https://github.com/eclipse/che/issues/15301 
Jenkins job to run Happy Path and Vert.x tests nightly on multiuser installation is available [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/MultiUser-Che-nightly-check-e2e-tests-against-k8s/).
