### ISSUE TITLE
Dashboard: improve workspace creation from devfile content

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14235]
### Is your enhancement related to a problem? Please describe.
Currently if I have content of the devfile and I want to create new workspace only by this content(without chectl or swagger...) I need to do a lot of extra steps in the user dashboard:
Select `Workspace` => click 'Add workspace' button => select some random devfile stack => click `Create and Proceed Editing` button, select Devfile section and replace devfile content by mine content... . But it's not user friendly at all...

### Describe the solution you'd like
It would be nice to have some button in the `New Workspace`page. Click on this button, then dashboard render textbox, you paste your devfile content and create workspace.

**Comment by slemeur** [comment]
closing as duplicated of https://github.com/eclipse/che/issues/13591
