### ISSUE TITLE
Write docs how to deploy Eclipse CHE with code ready workspaces

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14231]
### Is your task related to a problem? Please describe.
It would be nice to write docs how to deploy Eclipse CHE with code ready workspaces.

**Comment by slemeur** [comment]
Documentation about CodeReady Workspaces is available here: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.2/html/administration_guide/index

BTW: this is wrong place to create issues related to CodeReady Workspaces.
