### ISSUE TITLE
Backup and Disaster Recovery documentation

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#14240]
### Is your enhancement related to a problem? Please describe.

Che users may need to recover their Enterprise IDE environment after some disaster has occurred.  

### Describe the solution you'd like

Please document the processes to backup and restore:

- Che server data
- Che workspaces data

### Additional context

This RFE would make for a more resilient product.  Thank you for considering it.
Leverage some existing Kubernetes backup solution as [Velero](https://github.com/vmware-tanzu/velero) would be a nice to have.

**Comment by gorkem** [comment]
Alternately we can enhance the operator to do the backups and recovery https://github.com/eclipse/che/issues/14241

**Comment by skabashnyuk** [comment]
@ibuziuk you have more experience in maintaining hosted Che. Can you provide some guidance?

**Comment by ibuziuk** [comment]
@RickJWagner am I correct that you are interested in two aspects: 
- db recovery (Postgre)
- user PV recovery (unpushed code)

**Comment by ibuziuk** [comment]
Recommendations after prioritization:
- do not overthink
- keep it simple
- feedback from SRE team cc @skryzhny 
- take inspiration from Codenvy disaster recovery - https://codenvy.io/docs/admin-guide/managing/index.html#disaster-recovery
- investigate disaster recovery for other products / projects e.g. https://thenewstack.io/how-to-make-up-for-kubernetes-disaster-recovery-shortfalls/

**Comment by ibuziuk** [comment]
PR sent - https://github.com/eclipse/che-docs/pull/1094

**Comment by ibuziuk** [comment]
PR merged. Closing
