### ISSUE TITLE
Can I add a member to organization through the API?

### ISSUE THREAD

**Issue by mayadebellis** [eclipse-che/che#14242]
Is there any way to add a user to an organization through the API? I would like to do this programmatically and not through the interface.

I have looked through the swagger and played around with the `/organization` endpoints and the `/user` endpoints but cannot find a way to do this. I assumed the `POST /organization/{id}` that allows for the updating of organizations would be the correct endpoint but I have not found a way to get this work. I can't find a way to list the members of an organization to update it.

Is this possible? Any advice or examples is appreciated.

**Comment by sleshchenko** [comment]
@mayadebellis Hello. Members of the organization are managed by permissions service. More info you can find here https://www.eclipse.org/che/docs/che-6/permissions.html#organization-permissions

Feel free to ask more questions if some info is still needed or close issue if it works for you. Thanks!
