### ISSUE TITLE
Can not invoke Task if source is che

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#14254]
If I have a task defined on `tasks.json` with `source` defined as `che`, it can not be started from Command palette. I can see a message printed on JS Console as `ERROR Can't get task launch configuration for label: echo me` 

If I remove the source property from the following example task I can start the task without issues.
```json
 {
            "label": "echo me",
            "source": "che",
            "type": "process",
            "command": "echo test",
            "target": {
                "machineName": "theia-idemh5"
            }
   }
```

**Comment by tsmaeder** [comment]
P2, because easy workaround.

**Comment by RomanNikitenko** [comment]
Should be fixed by https://github.com/eclipse/che-theia/pull/295

**Comment by RomanNikitenko** [comment]
- Theia runs tasks using the runner registered for the specified [Task type](https://github.com/theia-ide/theia/blob/f718cb3461eaf1a7de90c679d31cdbeafe485708/packages/task/src/node/task-server.ts#L82) or a default Task Runner [if runner is not found for the task type](https://github.com/theia-ide/theia/blob/f718cb3461eaf1a7de90c679d31cdbeafe485708/packages/task/src/node/task-runner.ts#L64).
We register own runner to have ability to run tasks with type `che`. Our runner can run a task in a defined container.
-  `source` - [according to the doc](https://github.com/theia-ide/theia/blob/f718cb3461eaf1a7de90c679d31cdbeafe485708/packages/task/src/common/task-protocol.ts#L46) - for a configured task it is the name of the root folder, while for a detected task, it is the name of the provider.

So for the task which we want to run using our runner in the specific container we should use `"type": "che"` and don't define `source` - the configuration is placed in config file, so `source` - is the name of the root folder and theia add `source` when [reads](https://github.com/theia-ide/theia/blob/f718cb3461eaf1a7de90c679d31cdbeafe485708/packages/task/src/browser/task-configurations.ts#L331) the configuration from `tasks.json` file.  

I added `sleep 2` to the `command` as workaround for [the issue](https://github.com/theia-ide/theia/issues/2961). Please replace `machineName` for the correct value to test it. I saw your idea about mapping `component` to a container - thank you very much - I'll try it.

```
        {
            "label": "echo me",
            "type": "che",
            "command": "sleep 2 && echo test",
            "target": {
                "machineName": "theia-ide77o"
            }
        }
```

**Comment by gorkem** [comment]
@RomanNikitenko Is there a way we can omit `source` property when we carry a che provided task to task.json when we do a `Configure Task` command?

**Comment by RomanNikitenko** [comment]
For 7.0.0 we consider `che` tasks as 'configured', not as 'detected': 
- we convert `che` commands from devfile to theia tasks format and copy them to `tasks.json` file of current workspace folder.
So user doesn't need to use `Configure task` action  for `che` tasks.  User can find all `che` tasks in 
`tasks.json` file, edit them or add a new task.

`tasks.json` file can be open:
- manually 
- by clicking cog icon (configure task action) from the `Terminal` >  `Run Task` menu option
- from the `Terminal` >  `Configure Tasks` menu 

For `detected` task it opens `tasks.json` file and copies the configuration, but for `configured` one - just opens `tasks.json` file (config file already contains the configuration).

For master branch we have the [corresponding PR](https://github.com/eclipse/che-theia/pull/295). After merge the PR the behavior is the same as I described for 7.0.0.

**Comment by azatsarynnyy** [comment]
@RomanNikitenko could you please check if it's already fixed and we close that issue

**Comment by RomanNikitenko** [comment]
Since the PR https://github.com/eclipse/che-theia/pull/295 was merged we consider `che` tasks as `configured`, not as `detected`.
User doesn't need to use `Configure task` action for `che` tasks: we convert che commands from devfile to theia tasks format and copy them to tasks.json file.

So I'm closing the issue.
