### ISSUE TITLE
Edit the project in a docker container by stop showing create workspace and add workspace for user

### ISSUE THREAD

**Issue by sundar1195** [eclipse-che/che#14257]
We had deployed eclipse che as single user docker container. Is there any possible way that i can stop user from creating multiple workspace by stop user from clicking over create Workspace and Add Workspace button, But cannot edit an html file inside a docker container as it is only listing ts files inside a component module. So can i know any other possible way to restrict user from creating workspace & Add Workspace access to a user or the reason why html and styl files not listing in war extracted files in tomcat/webapps/dashboard.

**Comment by sleshchenko** [comment]
@sundar1195 Sorry for the late response, you should be able to configure user's allowed number workspaces. 
Related issue to document it https://github.com/eclipse/che/issues/16746, the parameter you should configure CHE_LIMITS_USER_WORKSPACES_RAM
