### ISSUE TITLE
Chectl spawns dozens of node processes

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#14252]
* Steps to reproduce: 
**Preconditions:**
Prepare latest version of `chectl` in next way:
-  `curl -sL  https://www.eclipse.org/che/chectl/ > install_chectl.sh`
-  `chmod +x install_chectl.sh`
-  `sudo PATH=$PATH ./install_chectl.sh -channel=stable`
-  `sudo chmod +x /usr/local/bin/chectl`

1) Launch Minikube with next parameters: 
`minikube start --memory 12288 --docker-opt userland-proxy=false`
2) Clone **Eclipse-Che** project. Start Che server with `chectl` like this: `chectl server:start -t ~/che-projects/che/deploy`
3) After starting CHE create workspace with chectl in next way: `chectl server:start -t ~/che-projects/che/deploy/`
4) Open just created workspace

**Expected result**: The workspace should be started without problems.
**Actual result** we have a lot of generated node processes (more than 1000) it consumes all memory from the System

**Env.** OS.: Fedora v.30
Minikube v0.27.0 (VitualBox 6); 
chect/0.0.20190814-next.d78ef53.d78ef53 linux-x64 node-v10.16.2; 
kubectl: Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}.

The log of node processes:
[chectl.log](https://github.com/che-incubator/chectl/files/3505694/chectl.log)

**Comment by tsmaeder** [comment]
@musienko-maxim questions:

1.  does this happens when you do not pass the "-t" parameter? Why are you passing the "-t" parameter?
2. Is this in master of chectl or a released version?

**Comment by musienko-maxim** [comment]
1. I've not tried without -t parameter yet. I  passed -t parameter because i used changes for me in helm charts (i added some variables in the ConfigMap)
2. It was released version

**Comment by rhopp** [comment]
@l0rd @benoitf Something worth looking at...

**Comment by l0rd** [comment]
@musienko-maxim your step 3 ("create workspace with chectl in next way: chectl server:start -t ~/che-projects/che/deploy/") doesn't look good. Do you mean `chectl workspace:start`?

**Comment by tolusha** [comment]
Can't reproduce it. 
chectl 7.10.0
