### ISSUE TITLE
Put `nightly` che-plugin-registry back to the helm charts

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14253]
Fixed version of che-plugin-registry has been configured as part of this PR: https://github.com/eclipse/che/pull/14249

We need to make sure, `nightly` is back there, once the latest nightly image (which would contain che-theia:7.0.0) is built.

**Comment by l0rd** [comment]
@rhopp can we close this one?

**Comment by vparfonov** [comment]
@rhopp ?
