### ISSUE TITLE
Deprecate quay.io/eclipse/che-golang-1.10 in favor of quay.io/eclipse/che-golang-1.12

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14265]
### Is your task related to a problem? Please describe.
We're currently maintaining two patched Go images, each used for only one devfile:

- `quay.io/eclipse/che-golang-1.10` - Used in the Go devfile
- `quay.io/eclipse/che-golang-1.12` - Used for the plugin broker devfile

### Describe the solution you'd like
We should verify that the Go devfile is compatible with Go 1.12, and if so, delete the old image from our repository.

### Describe alternatives you've considered
Maintain both images, although that may be confusing and increase testing requirements.

**Comment by amisevsk** [comment]
Pull request: https://github.com/eclipse/che-devfile-registry/pull/126

**Comment by ibuziuk** [comment]
@amisevsk could you please add deprecation note to the https://quay.io/repository/eclipse/che-golang-1.10 and I believe we can close the issue

**Comment by amisevsk** [comment]
Note added.
