### ISSUE TITLE
Using OpenShift.io for che plugin/devfile registry going forward

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14266]
## Summary
Currently, Che uses [openshift.io](https://github.com/eclipse/che/blob/c3b0abbe5dd8bffff197705e0803dd57da1fe82c/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L586) for default plugin and devfile registries. This will likely cause issues going forward, as those plugin registries are updated independently from the [plugin](https://quay.io/repository/eclipse/che-plugin-registry) and [devfile](https://quay.io/repository/eclipse/che-devfile-registry) registry images. In particular, these registries will likely have to be updated alongside releases of Che in order to maintain compatibility.

We need to define clear expectations on the update schedule for the production registries, and accommodate defaults in Che to work with these expecatations. I think that upstream Che should not use production deployments for `SNAPSHOT` builds.

## Relevant information
Today, we ran into an issue where all Che deployments from the current snapshot version fail to start workspaces. This is because
- Che was updated to use `eclipse/che-theia/7.0.0` instead of `eclipse/che-theia/7.0.0-next`: https://github.com/eclipse/che/commit/f50d13337536d2ff5fd3cd26236a1ac6921dc5bd#diff-2de0b0a873741f8e0d0879a46f8d5266L651
- The plugin registry was updated to **remove** `eclipse/che-theia/7.0.0-next` and replace it with `eclipse/che-theia/7.0.0`: https://github.com/eclipse/che-plugin-registry/commit/191df1e76efdc1db993947d66a23f8aaff8b5eec#diff-81a58be1dc1db6f64c386b8e5b5b2057L4
- The registry deployed on che.openshift.io is not automatically updated, so it does not contain `eclipse/che-theia/7.0.0`

Updating the production registries would mean breaking any workspaces that reference `eclipse/che-theia/7.0.0-next` directly or use it as a default. Further, since there's a manual update process for production deployments, we can't in general expect nightly releases to be available on production.

**Comment by amisevsk** [comment]
cc: @l0rd @rhopp @slemeur @nickboldt

**Comment by amisevsk** [comment]
Opened PR https://github.com/eclipse/che/pull/14267 to point current Che to prod-preview registries, which currently get nightly updates.

**Comment by amisevsk** [comment]
Additional context from the last time we updated the plugin registry: https://github.com/openshiftio/saas-openshiftio/pull/1323#issuecomment-520965403

**Comment by l0rd** [comment]
@amisevsk currently the default is to use local registries (deployed alongside the che-server when using helm or the operator) and not to use osio. But that's not clear reading this issue's description. 

Anyway I think using prod-preview is a step forward. Not sure if it will be the definitive solution: hosted che and upstream che stacks and plugins may need to be different at some point.

**Comment by rhopp** [comment]
Agree... Any nightly-snapshot che instances should use its own-deployed registries. From what I'm aware, only minishift addon installation method doesn't deploy its own registries (do we still want to support that?)

**Comment by gorkem** [comment]
@l0rd My installation over the weekend with chectl to minishift was using the hosted registries which means it is broken. We need a plan to adjust chectl on minishift.

**Comment by ibuziuk** [comment]
as I recall previously the plan was:
- have an alternative lightweight OIDC provider https://github.com/eclipse/che/issues/10998
- deprecate single-user mode (together with minishift addon)

**Comment by l0rd** [comment]
@gorkem agreed. I did not understand the problem at first. I think the description/title should be updated because that's a minishift add-on specific issue. Anyway using prod-preview registries is a good workaround but that's not ideal. Other options would be:
- update the minishift addon to deploy the registries (but minishift is close to EOL)
- update the che-operator to support deploying che single user and deprecating the minishift addon once and for all.

**Comment by johnmcollier** [comment]
Note that Che deployed via `./deploy_che.sh` will also use the hosted registries.

**Comment by amisevsk** [comment]
Part of the reason I opened this issue is that we're still using hosted Che registries as default values in che.properties; any Che deployment that doesn't override those in a configmap or environment variable will hit this same problem.

My plan was to use prod-preview until all supported deployment methods come with a registry, and then set the values in che.properties to `NULL`. At least in that case, Che will fail to start, rather than failing in a more cryptic way (only some plugins don't work).

**Comment by amisevsk** [comment]
This issue is out of date as Che gets deployed with compatible registries by all supported deployment methods.
