### ISSUE TITLE
Incorrect path - https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/7.0.0/meta.yaml

### ISSUE THREAD

**Issue by manishpython** [eclipse-che/che#14261]
While deploying Nodejs app in workspace, but getting below error:
```
The requested URL /v3/plugins/eclipse/che-theia/7.0.0/meta.yaml was not found on this server.

```
<details>

<summary>Full Workspace Start Logs</summary>

```
Cleaning /plugins dir
Starting Init Plugin Broker
Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/7.0.0/meta.yaml': Downloading https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/7.0.0/meta.yaml failed. Status code 404. Response body: 

Not Found

The requested URL /v3/plugins/eclipse/che-theia/7.0.0/meta.yaml was not found on this server.

Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspacewm7o9ae2ceq9bnwg failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/7.0.0/meta.yaml': Downloading https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/7.0.0/meta.yaml failed. Status code 404. Response body: 

Not Found

The requested URL /v3/plugins/eclipse/che-theia/7.0.0/meta.yaml was not found on this server.
```

</details>

Observed that it should be as per below 

Incorrect path - https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/7.0.0/meta.yaml
Correct path - https://che-plugin-registry.openshift.io/v3/plugins/eclipse/che-theia/7.0.0-next/meta.yaml 

Kindly fix it.

**Comment by sleshchenko** [comment]
cc @vparfonov @ibuziuk 
Looks like Plugin Registry on OpenShift.io should be updated

**Comment by sleshchenko** [comment]
@manishpython How did you deploy your Che? `chectl`, `helm`, ...?

**Comment by amisevsk** [comment]
I'll open a PR to update the registry, but it's worth noting that https://github.com/eclipse/che-plugin-registry/commit/191df1e76efdc1db993947d66a23f8aaff8b5eec#diff-81a58be1dc1db6f64c386b8e5b5b2057L4 is a breaking change -- any workspaces that explicitly reference `eclipse/che-theia/7.0.0-next` will no longer work

**Comment by manishpython** [comment]
I depoyed Che on Openshift 3.11 successfully, but when working on nodejs
app in workspace then face that issue.

Thanks
MS

**Comment by amisevsk** [comment]
@manishpython As a workaround while we get this resolved, you can update the configmap `che` on your OpenShift cluster. Adding the keys:
```
CHE_WORKSPACE_PLUGIN__REGISTRY__URL: https://che-plugin-registry.prod-preview.openshift.io/
CHE_WORKSPACE_DEVFILE__REGISTRY__URL: https://che-devfile-registry.prod-preview.openshift.io/
```

**Comment by ibuziuk** [comment]
@manishpython have you deployed against minishift? Could you please provide the info about how exactly you deployed Che? AFAIK minishift is the only flavour of che that still uses openshift.io registries

**Comment by rhopp** [comment]
If we want to continue supporting minishift addon, I guess it should take care about deploying registries as well... We cannot ensure, that registries versions on production openshift.io deployments are inline with Che addon version.

**Comment by ibuziuk** [comment]
I would rather deprecate minishift addon and focus on https://github.com/eclipse/che/issues/10998

**Comment by manishpython** [comment]
> @manishpython As a workaround while we get this resolved, you can update the configmap `che` on your OpenShift cluster. Adding the keys:
> 
> ```
> CHE_WORKSPACE_PLUGIN__REGISTRY__URL: https://che-plugin-registry.prod-preview.openshift.io/
> CHE_WORKSPACE_DEVFILE__REGISTRY__URL: https://che-devfile-registry.prod-preview.openshift.io/
> ```
> 
> should fix the issue.

Thanks, It works now.

**Comment by manishpython** [comment]
> @manishpython have you deployed against minishift? Could you please provide the info about how exactly you deployed Che? AFAIK minishift is the only flavour of che that still uses openshift.io registries

No minishift, only used openshift container platform 3.11.

**Comment by johnmcollier** [comment]
FWIW, I'm seeing this issue too with `eclipse/che-theia:7.0.0` on OpenShift 3.11. I deployed Che with `./deploy-che.sh` and no plugin/devfile registry was deployed by default, so the OpenShift.io plugin registry was used instead, where `eclipse/che-theia:7.0.0` doesn't exist.

**Comment by manishpython** [comment]
Closing
