### ISSUE TITLE
chectl does not stop Che Server deployed with minishift-addon installer

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14260]
### Describe the bug
chectl does not stop Che Server deployed with minishift-addon installer.
It happens because of different default labels that are used by different platform.
It's possible to workaround this issue by specifying `che-selector` parameter for `server:stop` command, but it would be better to make it working by default.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [x] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
cc @l0rd @@benoitf The fix is already provided as PR to Che minishift-addon https://github.com/minishift/minishift/pull/3320

**Comment by l0rd** [comment]
@sleshchenko makes sense

**Comment by sleshchenko** [comment]
should be fixed https://github.com/minishift/minishift/pull/3333
