### ISSUE TITLE
[languageserver] Ensure order of events

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-che/che#1426]
It is critical that the order of read and write messages/notifications is kept when invoking the language server. Currently if the client sends a read and write request to the agent the order might be changed and as a consequence the read operation would be executed on the wrong state.

I think to preserve that we need to communicate document version ids with every REST call.

See also :  https://github.com/Microsoft/vscode-languageserver-protocol/issues/12

**Comment by TylerJewell** [comment]
Covered by the LSP epic.

**Comment by gorkem** [comment]
@svenefftinge is this something built into LSP4J now?
