### ISSUE TITLE
`/api/ssh/generate` should validate `name`.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#14272]
### Describe the bug

After creating SSH keypair via API with unsuitable parameter, all workspaces can't boot up.

### Che version

 - [x] nightly

### Steps to reproduce

1. Open swagger.
2. Call `/api/ssh/generate` with paramter `{ "name": "Non FQDN string as you like", "service": "vcs" }`
3. Boot up your workspace. It will be failed by naming issue on the K8s secret object.

### Expected behavior

Unsuitable `name`s should be rejected by `/api/ssh/generate`.

### Runtime
   - [ ] ~~other: (please specify)~~ Runtime independent.

### Installation method
   - [ ] ~~I don't know~~ Installation independent

### Environment
   - [ ] ~~other: please specify~~ Environment independent.

### Additional context

Related on #14243.

**Comment by monaka** [comment]
I think it will be showstopper if the user set it. But it will be a rare case. So it isn't urgent (enough to be fixed after 7.0.0 released).

**Comment by gorkem** [comment]
@monaka is this also related to https://github.com/eclipse/che/issues/14218

**Comment by monaka** [comment]
@gorkem Yes. I close this and move to #14218.
