### ISSUE TITLE
 ERR_TIMEOUT: Timeout set to pod ready timeout 130000

### ISSUE THREAD

**Issue by Pixxelcrasher** [eclipse-che/che#14271]
### Che version

 - [ ] latest
 - [*] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [*] minikube (include output of `minikube version: v1.3.1` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [*] chectl chectl server:start --multiuser 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [*] my computer 
       - [ ] Windows
       - [*] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
Hello,
when I want to install Eclipse Che 7.0 I got this Error:

✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.178.124.nip.io.
  ✔ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exist.
    ✔ Create ServiceAccount che-operator in namespace che...It already exist.
    ✔ Create Role che-operator in namespace che...It already exist.
    ✔ Create RoleBinding che-operator in namespace che...It already exist.
    ✔ Create CRD checlusters.org.eclipse.che...It already exist.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...It already exist.
    ✔ Create Che Cluster eclipse-che in namespace che...It already exist.
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Keycloak pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✖ starting
        → ERR_TIMEOUT: Timeout set to pod ready timeout 130000
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod ready timeout 130000
    at KubeHelper.<anonymous> (/usr/local/lib/chectl/lib/api/kube.js:541:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:107:62)

Does it give any way to fix it ?

Thanks for help

**Comment by rhopp** [comment]
Could you please provide output of following commands, right after the failure happens?
`kubectl get all -n che`
`kubectl get events -n che`
Thanks!

**Comment by bryantson** [comment]
@rhopp 

I encountered the same issue, and here are the outputs:

**Running kubectl get all -n che**

`
NAME                                   READY   STATUS    RESTARTS   AGE
pod/che-f5bb68d-qdsvn                  0/1     Running   2          12m
pod/che-operator-77d8f8bbc8-5h2t2      1/1     Running   0          15m
pod/devfile-registry-7cd76dcf5-gs5l2   1/1     Running   0          14m
pod/keycloak-55bc7857c9-4wn9p          1/1     Running   0          14m
pod/plugin-registry-7b4cf6d657-v549j   1/1     Running   0          15m
pod/postgres-649679b5b6-gvhml          1/1     Running   0          15m


NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/che-host           ClusterIP   172.30.150.137   <none>        8080/TCP,8087/TCP   14m
service/devfile-registry   ClusterIP   172.30.164.6     <none>        8080/TCP            14m
service/keycloak           ClusterIP   172.30.141.223   <none>        8080/TCP            14m
service/plugin-registry    ClusterIP   172.30.11.51     <none>        8080/TCP            15m
service/postgres           ClusterIP   172.30.155.130   <none>        5432/TCP            15m


NAME                               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/che                1         1         1            0           12m
deployment.apps/che-operator       1         1         1            1           15m
deployment.apps/devfile-registry   1         1         1            1           14m
deployment.apps/keycloak           1         1         1            1           14m
deployment.apps/plugin-registry    1         1         1            1           15m
deployment.apps/postgres           1         1         1            1           15m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/che-f5bb68d                  1         1         0       12m
replicaset.apps/che-operator-77d8f8bbc8      1         1         1       15m
replicaset.apps/devfile-registry-7cd76dcf5   1         1         1       14m
replicaset.apps/keycloak-55bc7857c9          1         1         1       14m
replicaset.apps/plugin-registry-7b4cf6d657   1         1         1       15m
replicaset.apps/postgres-649679b5b6          1         1         1       15m









NAME                                        HOST/PORT                                  PATH   SERVICES           PORT   TERMINATION     WILDCARD
route.route.openshift.io/che                che-che.192.168.64.4.nip.io                       che-host           8080   edge/Redirect   None
route.route.openshift.io/devfile-registry   devfile-registry-che.192.168.64.4.nip.io          devfile-registry   8080   edge/Redirect   None
route.route.openshift.io/keycloak           keycloak-che.192.168.64.4.nip.io                  keycloak           8080   edge/Redirect   None
route.route.openshift.io/plugin-registry    plugin-registry-che.192.168.64.4.nip.io           plugin-registry    8080   edge/Redirect   None

`


**Running kubectl get events -n che**

`LAST SEEN   FIRST SEEN   COUNT   NAME                                                KIND         SUBOBJECT                               TYPE      REASON              SOURCE                  MESSAGE
16m         16m          1       che-operator.15bc62d67f0e0db3                       Deployment                                           Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set che-operator-77d8f8bbc8 to 1
16m         16m          1       che-operator-77d8f8bbc8.15bc62d6810ddaa7            ReplicaSet                                           Normal    SuccessfulCreate    replicaset-controller   Created pod: che-operator-77d8f8bbc8-5h2t2
16m         16m          1       che-operator-77d8f8bbc8-5h2t2.15bc62d6819f7846      Pod                                                  Normal    Scheduled           default-scheduler       Successfully assigned che/che-operator-77d8f8bbc8-5h2t2 to localhost
16m         16m          1       che-operator-77d8f8bbc8-5h2t2.15bc62d6a66355b1      Pod          spec.containers{che-operator}           Normal    Pulling             kubelet, localhost      pulling image "quay.io/eclipse/che-operator:7.0.0"
16m         16m          1       che-operator-77d8f8bbc8-5h2t2.15bc62d8ec0d4dbe      Pod          spec.containers{che-operator}           Normal    Pulled              kubelet, localhost      Successfully pulled image "quay.io/eclipse/che-operator:7.0.0"
16m         16m          1       che-operator-77d8f8bbc8-5h2t2.15bc62d8f94cba8c      Pod          spec.containers{che-operator}           Normal    Started             kubelet, localhost      Started container
16m         16m          1       che-operator-77d8f8bbc8-5h2t2.15bc62d8edd32c73      Pod          spec.containers{che-operator}           Normal    Created             kubelet, localhost      Created container
16m         16m          1       postgres-649679b5b6.15bc62d95a7cf687                ReplicaSet                                           Normal    SuccessfulCreate    replicaset-controller   Created pod: postgres-649679b5b6-gvhml
16m         16m          1       postgres-649679b5b6-gvhml.15bc62d97d0b72b5          Pod          spec.containers{postgres}               Normal    Pulling             kubelet, localhost      pulling image "centos/postgresql-96-centos7:9.6"
16m         16m          1       postgres-649679b5b6-gvhml.15bc62d95b3c25df          Pod                                                  Normal    Scheduled           default-scheduler       Successfully assigned che/postgres-649679b5b6-gvhml to localhost
16m         16m          1       postgres.15bc62d95915926f                           Deployment                                           Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set postgres-649679b5b6 to 1
16m         16m          1       postgres-649679b5b6-gvhml.15bc62db93864c92          Pod          spec.containers{postgres}               Normal    Pulled              kubelet, localhost      Successfully pulled image "centos/postgresql-96-centos7:9.6"
16m         16m          1       postgres-649679b5b6-gvhml.15bc62db95a799d4          Pod          spec.containers{postgres}               Normal    Created             kubelet, localhost      Created container
16m         16m          1       postgres-649679b5b6-gvhml.15bc62dba057310c          Pod          spec.containers{postgres}               Normal    Started             kubelet, localhost      Started container
16m         16m          1       plugin-registry-7b4cf6d657.15bc62e0b1afce10         ReplicaSet                                           Normal    SuccessfulCreate    replicaset-controller   Created pod: plugin-registry-7b4cf6d657-v549j
16m         16m          1       plugin-registry.15bc62e0b08bfd8f                    Deployment                                           Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set plugin-registry-7b4cf6d657 to 1
16m         16m          1       plugin-registry-7b4cf6d657-v549j.15bc62e0b237d141   Pod                                                  Normal    Scheduled           default-scheduler       Successfully assigned che/plugin-registry-7b4cf6d657-v549j to localhost
16m         16m          1       plugin-registry-7b4cf6d657-v549j.15bc62e0d644b2ba   Pod          spec.containers{che-plugin-registry}    Normal    Pulling             kubelet, localhost      pulling image "quay.io/eclipse/che-plugin-registry:7.0.0"
15m         15m          1       plugin-registry-7b4cf6d657-v549j.15bc62e867e8ef03   Pod          spec.containers{che-plugin-registry}    Normal    Started             kubelet, localhost      Started container
15m         15m          1       plugin-registry-7b4cf6d657-v549j.15bc62e85d288664   Pod          spec.containers{che-plugin-registry}    Normal    Created             kubelet, localhost      Created container
15m         15m          1       plugin-registry-7b4cf6d657-v549j.15bc62e85a82ccb3   Pod          spec.containers{che-plugin-registry}    Normal    Pulled              kubelet, localhost      Successfully pulled image "quay.io/eclipse/che-plugin-registry:7.0.0"
15m         15m          1       devfile-registry.15bc62e91170b90c                   Deployment                                           Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set devfile-registry-7cd76dcf5 to 1
15m         15m          1       devfile-registry-7cd76dcf5.15bc62e91302d00e         ReplicaSet                                           Normal    SuccessfulCreate    replicaset-controller   Created pod: devfile-registry-7cd76dcf5-gs5l2
15m         15m          1       devfile-registry-7cd76dcf5-gs5l2.15bc62e913c12cc6   Pod                                                  Normal    Scheduled           default-scheduler       Successfully assigned che/devfile-registry-7cd76dcf5-gs5l2 to localhost
15m         15m          1       devfile-registry-7cd76dcf5-gs5l2.15bc62e936b392c1   Pod          spec.containers{che-devfile-registry}   Normal    Pulling             kubelet, localhost      pulling image "quay.io/eclipse/che-devfile-registry:7.0.0"
15m         15m          1       devfile-registry-7cd76dcf5-gs5l2.15bc62e980d14578   Pod          spec.containers{che-devfile-registry}   Normal    Pulled              kubelet, localhost      Successfully pulled image "quay.io/eclipse/che-devfile-registry:7.0.0"
15m         15m          1       devfile-registry-7cd76dcf5-gs5l2.15bc62e982d293b1   Pod          spec.containers{che-devfile-registry}   Normal    Created             kubelet, localhost      Created container
15m         15m          1       devfile-registry-7cd76dcf5-gs5l2.15bc62e98c6d255e   Pod          spec.containers{che-devfile-registry}   Normal    Started             kubelet, localhost      Started container
15m         15m          1       keycloak.15bc62eb26375294                           Deployment                                           Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set keycloak-55bc7857c9 to 1
15m         15m          1       keycloak-55bc7857c9-4wn9p.15bc62eb2adae72a          Pod                                                  Normal    Scheduled           default-scheduler       Successfully assigned che/keycloak-55bc7857c9-4wn9p to localhost
15m         15m          1       keycloak-55bc7857c9.15bc62eb294fa1d4                ReplicaSet                                           Normal    SuccessfulCreate    replicaset-controller   Created pod: keycloak-55bc7857c9-4wn9p
15m         15m          1       keycloak-55bc7857c9-4wn9p.15bc62eb4d497e2e          Pod          spec.containers{keycloak}               Normal    Pulling             kubelet, localhost      pulling image "eclipse/che-keycloak:7.0.0"
14m         14m          1       keycloak-55bc7857c9-4wn9p.15bc62fc39bcf8c0          Pod          spec.containers{keycloak}               Normal    Started             kubelet, localhost      Started container
14m         14m          1       keycloak-55bc7857c9-4wn9p.15bc62fc2ecde896          Pod          spec.containers{keycloak}               Normal    Created             kubelet, localhost      Created container
14m         14m          1       keycloak-55bc7857c9-4wn9p.15bc62fc2cb31915          Pod          spec.containers{keycloak}               Normal    Pulled              kubelet, localhost      Successfully pulled image "eclipse/che-keycloak:7.0.0"
13m         13m          1       keycloak-55bc7857c9-4wn9p.15bc63044226528d          Pod          spec.containers{keycloak}               Warning   Unhealthy           kubelet, localhost      Readiness probe failed: Get http://172.17.0.13:8080/auth/js/keycloak.js: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
13m         13m          1       che-f5bb68d.15bc63092888297c                        ReplicaSet                                           Normal    SuccessfulCreate    replicaset-controller   Created pod: che-f5bb68d-qdsvn
13m         13m          1       che.15bc630925e02410                                Deployment                                           Normal    ScalingReplicaSet   deployment-controller   Scaled up replica set che-f5bb68d to 1
13m         13m          1       che-f5bb68d-qdsvn.15bc63092928e23f                  Pod                                                  Normal    Scheduled           default-scheduler       Successfully assigned che/che-f5bb68d-qdsvn to localhost
13m         13m          1       che-f5bb68d-qdsvn.15bc630983453088                  Pod          spec.containers{che}                    Normal    Started             kubelet, localhost      Started container
13m         13m          1       che-f5bb68d-qdsvn.15bc630973d276b2                  Pod          spec.containers{che}                    Normal    Created             kubelet, localhost      Created container
13m         13m          1       che-f5bb68d-qdsvn.15bc6309712efd09                  Pod          spec.containers{che}                    Normal    Pulled              kubelet, localhost      Successfully pulled image "eclipse/che-server:7.0.0"
13m         13m          1       che-f5bb68d-qdsvn.15bc630954734d7a                  Pod          spec.containers{che}                    Normal    Pulling             kubelet, localhost      pulling image "eclipse/che-server:7.0.0"
12m         12m          1       che-f5bb68d-qdsvn.15bc6311a9900c99                  Pod          spec.containers{che}                    Warning   Unhealthy           kubelet, localhost      Readiness probe failed: Get http://172.17.0.14:8080/api/system/state: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
9m          9m           2       che-f5bb68d-qdsvn.15bc633822a8dfc5                  Pod          spec.containers{che}                    Warning   Unhealthy           kubelet, localhost      Liveness probe failed: HTTP probe failed with statuscode: 500
3m          12m          45      che-f5bb68d-qdsvn.15bc6313ac747a8b                  Pod          spec.containers{che}                    Warning   Unhealthy           kubelet, localhost      Readiness probe failed: HTTP probe failed with statuscode: 500`

**Comment by bryantson** [comment]
Seems related to this as inspecting pods show the same error:

https://github.com/eclipse/che/issues/13935

**Comment by Pixxelcrasher** [comment]
yes but does it give a way to fix it ?
Sorry for my late answer

**Comment by redeagle84** [comment]
Possible related problem here:  
[chectl throwing "ERR_TIMEOUT: Timeout set to pod ready timeout 130000" for --multiuser ](https://github.com/eclipse/che/issues/16559)

**Comment by hari1992-web** [comment]
Readiness probe failed: HTTP probe failed with statuscode: 500
Back-off restarting failed container

**Comment by hari1992-web** [comment]
Does any way fix it ?????

**Comment by tolusha** [comment]
@Pixxelcrasher 
Pls try with the latest version of chectl
We've implemented a lot of improvements to work this tls mode.

**Comment by CannyDuck** [comment]
I tried the latest version. Eclipse Che pod bootstrap fails starting.

I see the following errors in the log. Please help me to get it run up.

```
 [ERROR] [o.a.c.c.C.[.[localhost].[/api] 175]  - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: https://keycloak-che.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:71)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:54)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.<init>(KeycloakServiceClient.java:73)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.class(KeycloakServiceClient.java:66)

Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching keycloak-che.192.168.99.100.nip.io found.
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:96)
	... 45 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching keycloak-che.192.168.99.100.nip.io found.
	at java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)
	at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 64 more
```

**Comment by khanzzirfan** [comment]
same issue on Windows 10 docker desktop.
> chectl version
chectl/0.0.20200302-next.3fb4dc7 win32-x64 node-v10.19.0
 
> kubectl get all -n che

NAME                                    READY   STATUS             RESTARTS   AGE
pod/che-64848b745f-mhcln                0/1     CrashLoopBackOff   7          15m
pod/devfile-registry-765497fc98-js5zn   1/1     Running            0          15m
pod/plugin-registry-6f77f45f6b-hvqn5    1/1     Running            0          15m


NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/che-host           ClusterIP   10.98.171.184    <none>        8080/TCP,8087/TCP   15m
service/devfile-registry   ClusterIP   10.100.203.145   <none>        8080/TCP            15m
service/plugin-registry    ClusterIP   10.103.145.206   <none>        8080/TCP            15m


NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/che                0/1     1            0           15m
deployment.apps/devfile-registry   1/1     1            1           15m
deployment.apps/plugin-registry    1/1     1            1           15m

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/che-64848b745f                1         1         0       15m
replicaset.apps/devfile-registry-765497fc98   1         1         1       15m
replicaset.apps/plugin-registry-6f77f45f6b    1         1         1       15m


                                                                                                                                                                                                               
> kubectl get events -n che                                                                                                                                                            

LAST SEEN   TYPE      REASON                  OBJECT                                          MESSAGE                                                                                                          
16m         Warning   FailedScheduling        pod/che-64848b745f-mhcln                        pod has unbound immediate PersistentVolumeClaims                                                                 
16m         Normal    Scheduled               pod/che-64848b745f-mhcln                        Successfully assigned che/che-64848b745f-mhcln to docker-desktop                                                 
16m         Normal    Pulling                 pod/che-64848b745f-mhcln                        Pulling image "busybox"                                                                                          
16m         Normal    Pulled                  pod/che-64848b745f-mhcln                        Successfully pulled image "busybox"                                                                              
16m         Normal    Created                 pod/che-64848b745f-mhcln                        Created container fmp-volume-permission                                                                          
16m         Normal    Started                 pod/che-64848b745f-mhcln                        Started container fmp-volume-permission                                                                          
13m         Normal    Pulling                 pod/che-64848b745f-mhcln                        Pulling image "quay.io/eclipse/che-server:nightly"                                                               
13m         Normal    Pulled                  pod/che-64848b745f-mhcln                        Successfully pulled image "quay.io/eclipse/che-server:nightly"                                                   
13m         Normal    Created                 pod/che-64848b745f-mhcln                        Created container che                                                                                            
14m         Normal    Started                 pod/che-64848b745f-mhcln                        Started container che                                                                                            
85s         Warning   BackOff                 pod/che-64848b745f-mhcln                        Back-off restarting failed container                                                                             
16m         Normal    SuccessfulCreate        replicaset/che-64848b745f                       Created pod: che-64848b745f-mhcln                                                                                
16m         Normal    CertificateIssued       certificaterequest/che-certificate-3675287812   Certificate fetched from issuer successfully                                                                     
16m         Normal    GeneratedKey            certificate/che-certificate                     Generated a new private key                                                                                      
16m         Normal    Requested               certificate/che-certificate                     Created new CertificateRequest resource "che-certificate-3675287812"                                             
16m         Normal    Issued                  certificate/che-certificate                     Certificate issued successfully                                                                                  
16m         Normal    ExternalProvisioning    persistentvolumeclaim/che-data-volume           waiting for a volume to be created, either by external provisioner "docker.io/hostpath" or manually created by sy
em administrator                                                                                                                                                                                               
<invalid>   Normal    Provisioning            persistentvolumeclaim/che-data-volume           External provisioner is provisioning volume for claim "che/che-data-volume"                                      
<invalid>   Normal    ProvisioningSucceeded   persistentvolumeclaim/che-data-volume           Successfully provisioned volume pvc-8c618c1f-2af7-4fd4-b4d0-188bccec3894                                         
16m         Normal    CREATE                  ingress/che-ingress                             Ingress che/che-ingress                                                                                          
16m         Normal    UPDATE                  ingress/che-ingress                             Ingress che/che-ingress                                                                                          
16m         Normal    ScalingReplicaSet       deployment/che                                  Scaled up replica set che-64848b745f to 1                                                                        
16m         Normal    Scheduled               pod/devfile-registry-765497fc98-js5zn           Successfully assigned che/devfile-registry-765497fc98-js5zn to docker-desktop                                    
16m         Normal    Pulling                 pod/devfile-registry-765497fc98-js5zn           Pulling image "quay.io/eclipse/che-devfile-registry:nightly"                                                     
16m         Normal    Pulled                  pod/devfile-registry-765497fc98-js5zn           Successfully pulled image "quay.io/eclipse/che-devfile-registry:nightly"                                         
16m         Normal    Created                 pod/devfile-registry-765497fc98-js5zn           Created container che-devfile-registry                                                                           
16m         Normal    Started                 pod/devfile-registry-765497fc98-js5zn           Started container che-devfile-registry                                                                           
16m         Normal    SuccessfulCreate        replicaset/devfile-registry-765497fc98          Created pod: devfile-registry-765497fc98-js5zn                                                                   
16m         Normal    ScalingReplicaSet       deployment/devfile-registry                     Scaled up replica set devfile-registry-765497fc98 to 1                                                           
16m         Normal    CREATE                  ingress/devfile-registry                        Ingress che/devfile-registry                                                                                     
16m         Normal    UPDATE                  ingress/devfile-registry                        Ingress che/devfile-registry                                                                                     
16m         Normal    Scheduled               pod/plugin-registry-6f77f45f6b-hvqn5            Successfully assigned che/plugin-registry-6f77f45f6b-hvqn5 to docker-desktop                                     
16m         Normal    Pulling                 pod/plugin-registry-6f77f45f6b-hvqn5            Pulling image "quay.io/eclipse/che-plugin-registry:nightly"                                                      
16m         Normal    Pulled                  pod/plugin-registry-6f77f45f6b-hvqn5            Successfully pulled image "quay.io/eclipse/che-plugin-registry:nightly"                                          
16m         Normal    Created                 pod/plugin-registry-6f77f45f6b-hvqn5            Created container che-plugin-registry                                                                            
16m         Normal    Started                 pod/plugin-registry-6f77f45f6b-hvqn5            Started container che-plugin-registry                                                                            
16m         Normal    SuccessfulCreate        replicaset/plugin-registry-6f77f45f6b           Created pod: plugin-registry-6f77f45f6b-hvqn5                                                                    
16m         Normal    ScalingReplicaSet       deployment/plugin-registry                      Scaled up replica set plugin-registry-6f77f45f6b to 1                                                            
16m         Normal    CREATE                  ingress/plugin-registry                         Ingress che/plugin-registry                                                                                      
16m         Normal    UPDATE                  ingress/plugin-registry                         Ingress che/plugin-registry

**Comment by tolusha** [comment]
@CannyDuck 
@khanzzirfan 
Could you pls submit dedicates issues pls?

**Comment by khanzzirfan** [comment]
sorry, what do you mean dedicates issues.? @tolusha

**Comment by tolusha** [comment]
@khanzzirfan 
Could you create an issue and provide relevant information how to reproduce it?

**Comment by khanzzirfan** [comment]
I posted everything above all the errors im receiving.  How to reproduce and show you on my PC? do you want to do zoom call for a video chat to see live is it?

**Comment by chaitu454** [comment]
I am trying to do a custom build and getting the same issue. I have checked out che-server 7.16.x code and doing a local build which generates nightly version of image. When I am trying to use it chectl is throwing this same error at the same time if I wont mention custom image it works fine. Any idea why

**Comment by khanzzirfan** [comment]
@tolusha I have followed the blog as is and started setting up Eclipseche on windows 10. but no luck. 
https://medium.com/modern-mainframe/vs-code-experience-on-mainframe-with-eclipse-che-an-easy-install-recipe-9fbebe34a516

**Comment by tolusha** [comment]
@khanzzirfan 
```
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
This kind of error  was fixed https://github.com/eclipse/che/issues/17169 (7.16.0 version)
Could you provide a full command line which you used to deploy Eclipse Che ?

**Comment by khanzzirfan** [comment]
Hi I ran the commmand `chectl server:start --platform=docker-desktop --installer=helm` 
This time che server started. But I cant access on browser.  when I checked the status here what I get 

![image](https://user-images.githubusercontent.com/8625166/90329379-aa8c9200-dfe7-11ea-939b-4dbfe4417b87.png)

Below are kubernete pods
![image](https://user-images.githubusercontent.com/8625166/90329351-73b67c00-dfe7-11ea-90b1-46c1c3aa5385.png)

**Comment by tolusha** [comment]
Unfortunately `chectl server:start` isnot supported for `--installer=helm`
But your error means that che-server isn't accessible. 
1. check logs in che pod
2. open che in browser.

**Comment by khanzzirfan** [comment]
Hi @tolusha  I cannot open che in browser. Its not working. 
Also, can you see that in my screenshot. external-iP is not associated with anything.  is that the right thing? 

Also its the same issue.. if i start che as 
chectl server:start --platform=docker-desktop
