### ISSUE TITLE
Deploy eclipse che (single user) from forked change using Dockers

### ISSUE THREAD

**Issue by sundar1195** [eclipse-che/che#14279]
Hi Folks,
Is there any possible way or any steps by which I can deploy eclipse che single user with respect to some forked changes. Please provide docs URL if any way that I can change some source code and deploy them with docker.

Thanks in Advance!!

**Comment by rhopp** [comment]
Hi, @sundar1195 !
It depends on which part of che you want to modify. For example for che server, you can do something like this:
* Build sources: `mvn clean install -f <PathToCheRepo>/pom.xml `
* And then build docker image: `<PathToCheRepo>/dockerfiles/che/build.sh --dockerfile:Dockerfile`
This should build you a docker image of che-server, which you can push and use the same way, as regular che-server image.

If you want to deploy che directly on docker infrastructure, this is sadly not possible anymore, as this project is targeting cloud native development.
If you want to deploy che 7 (current version, possibly with your changes) locally, I suggest you to use minikube or minishift to run local k8s cluster and then you can use chectl https://github.com/che-incubator/chectl to deploy che there.
