### ISSUE TITLE
Importing a Kubernetes application documentation link to 404

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14275]
### Describe the bug
https://www.eclipse.org/che/docs/che-7/importing-a-kubernetes-application-into-a-che-workspace
Goes to a 404

**Comment by themr0c** [comment]
fix in https://github.com/eclipse/che-docs/pull/789

**Comment by slemeur** [comment]
thanks @themr0c !

**Comment by rkratky** [comment]
Fixed by https://github.com/eclipse/che-docs/pull/789
