### ISSUE TITLE
Add sample devfiles to the documentation on devfile

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14274]
### Describe the solution you'd like
This page about devfile should be providing samples devfile link:
https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/

https://github.com/eclipse/che-devfile-registry/tree/master/devfiles
and
https://github.com/redhat-developer/devfile/tree/master/samples

**Comment by themr0c** [comment]
Hi @slemeur: you mean just add the links to both repositories, not integrating a comprehensive list, is that correct?

**Comment by slemeur** [comment]
@themr0c : yes correct!

**Comment by themr0c** [comment]
@rkratky @slemeur eclipse/che-docs#793 should be sufficient to address the issue.
