### ISSUE TITLE
Bad error message if invalid URL given to factory

### ISSUE THREAD

**Issue by tetchel** [eclipse-che/che#14286]
### Describe the bug

The "devfile is out of date" message appears in too many user error scenarios, such as if the URL is invalid or inaccessible. There should be a better error message.
![image](https://user-images.githubusercontent.com/8888438/63278672-b9762280-c275-11e9-8517-0cdf68451fd6.png)

### Che version

7.0.0-rc-5.0-SNAPSHOT

### Steps to reproduce

1. Use the factory endpoint to create a new workspace.
2. Provide an invalid URL in the query, eg:
`http://che-default.<domain>/f?url=asdf`
3. The error is as above.

### Expected behavior
The error message should be more informative. Che should handle common user errors such as:
- The URL is invalid
- The URL is valid but unreachable by the Che instance
- The URL is valid and reachable but does not point to a yaml file
- The URL is a non-raw GitHub/GitLab/Bitbucket URL
  - ie https://github.com/eclipse/codewind-che-plugin/blob/master/devfiles/latest/devfile.yaml instead of https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml
- The URL is valid, reachable, and a yaml file, but does not look anything like a devfile.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)
```
[ /tim/programs/codewind ] 29 $ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://c100-e.us-east.containers.cloud.ibm.com:30387
openshift v3.11.129
kubernetes v1.11.0+d4cacc0
```

**Comment by ibuziuk** [comment]
@tetchel any plans to provide a PR for that ;-)

**Comment by shubhampandey16** [comment]
@tetchel adn @ibuziuk I can take a look at it.

**Comment by tetchel** [comment]
this was not safe to close! :(
