### ISSUE TITLE
User behavior for setting up Java Debugger is not clear

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#14282]
Precondition:
* Launch Che with Theia next version on the OpenShift  or Kubernetes infra with chectl
Steps to reproduce:
* Create workspace with chectl using configuration from CHE project: 
`chectl workspace:start --devfile=che/e2e/files/happy-path/happy-path-workspace.yaml`
* Open the workspace, wait for finish of cloning the project
* After cloning try to set Debugger configuration Debug -> Open Configurations

The debugger configuration does not apply for the petclinic  project. For correct applying of Debugger configuration we should open the project in the separate workspace:
`File -> Open Workspace -> Select Petclinic project`. But after that the project context form the previous browser tab will be lost. More over after that all plugins will be initialized again. It is not obviously for a user and can confuse. As for it like a bug.
Also it behavior influences on the current e2e test for che-theia, because we should implement extra steps for the opening project in the separated workspace 
The related issues: https://github.com/eclipse/che/issues/12728

![screencast-server8uz3c3yh](https://user-images.githubusercontent.com/1640058/63266119-e20f1400-c297-11e9-8442-f2118b7e7bf1.gif)

**Comment by vparfonov** [comment]
@slemeur We need to here your thoughts, on my opinion this is very strange behavior and I would consider it as bug

**Comment by rhopp** [comment]
@tsmaeder Are we doing something wrong here?

**Comment by dmytro-ndp** [comment]
This issue is probably kind of blocker for https://github.com/eclipse/che/issues/14248

**Comment by tsmaeder** [comment]
> The debugger configuration does not apply for the petclinic project. For correct applying of Debugger configuration we should open the project in the separate workspace:

@musienko-maxim Could you explain what you mean by "the debugger configuration does not apply"? 
Does it work if you refresh the browser in the first window?

**Comment by ibuziuk** [comment]
@musienko-maxim the issue is assigned, so please put a milestone based on the team priorities

**Comment by tsmaeder** [comment]
I assigned it because I'm waiting for feedback.

**Comment by tsmaeder** [comment]
@musienko-maxim ping?

**Comment by musienko-maxim** [comment]
The root cause as was mentioned by @amisevsk it is which behavior should be if a cloned project already have .vscode folder.  Lets see on this with more simple sample: a user has created a workspace based on maven stack without projects. He already had .theia folder with debug config (`launch.json`) file. After that he cloned the petclinic project: https://github.com/spring-projects/spring-petclinic, with .vscode folder which also has `launch.json file`. In this case not exacly clear which configuration should be applyed.
