### ISSUE TITLE
Update remote-plugin-openshift-connector to odo 1.0 and oc 4.1

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14287]
### Is your enhancement related to a problem? Please describe.

Looking at https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-openshift-connector-0.0.21/Dockerfile#L26-L29 ... 

### Describe the solution you'd like

Should we update https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-openshift-connector-0.0.21/Dockerfile to a newer version of `odo`, and the v4.1 version of `oc`?

### Describe alternatives you've considered

Not updating anything and testing to see if openshift connector plugin works with OCP4/OSD4 first?

### Additional context

Productized Che 7 (CRW 2) has to support OCP 4.2 and OSD 4.2 as a deployment environment, but I don't know if that also means supporting interacting w. Openshift 4 from WITHIN Che/CRW via this plugin.

Seems like a logical next step, but maybe that's a goal for 2.1 (Che 7.7?), not 2.0 (Che 7.3?) ?

cc: @l0rd @slemeur @benoitf

**Comment by nickboldt** [comment]
Note:

latest odo: https://github.com/openshift/odo/releases (1.0.0-beta4)
latest oc: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/ (4.1.12)

**Comment by ibuziuk** [comment]
@l0rd @evidolob I have removed the `need-triage` label since we just need to decide in which milestone are we planning to update the odo and oc binaries

**Comment by vparfonov** [comment]
will be fixed in https://github.com/eclipse/che/issues/14287

**Comment by azatsarynnyy** [comment]
I've tested the current version of OpenShift Connector Che Plugin with OCP 4 and looks like it works well, at first glance...
![image](https://user-images.githubusercontent.com/1636395/65975488-5c29df80-e477-11e9-89eb-ad03ba72ee4f.png)

But during some operations, I've got the messages about incompatibility, e.g.
![image](https://user-images.githubusercontent.com/1636395/65976445-ca22d680-e478-11e9-9dcd-3c8de246f0a1.png)

Also, looks like the current Che Plugin creates the cluster resources in OpenSHift 3.x format. When connecting to the OCP 4 cluster with the latest version of OpenShift Connector extension from VS Code, it notifies:
> Some of the resources in cluster must be updated to work with latest release of OpenShift Connector Extension.

So, I'm going to update the Che Plugin to the latest version of the corresponded VS Code extension + its dependencies.

**Comment by azatsarynnyy** [comment]
The latest version of OpenShift Connector VS Code extension [requires](https://github.com/redhat-developer/vscode-openshift-tools/blob/v0.1.0/src/tools.json#L38) oc version >= 3.11.0 and < 4.0.0.
With oc > 4.0.0  extension proposes to downgrade it
![os-oc](https://user-images.githubusercontent.com/1636395/66132352-97561b00-e5fd-11e9-83ac-9e4e89c2fbb3.png)

So, I'll keep oc v3.11.0
See https://github.com/eclipse/che-theia/pull/465

**Comment by azatsarynnyy** [comment]
Done in https://github.com/eclipse/che-theia/pull/465 + https://github.com/eclipse/che-plugin-registry/pull/238
