### ISSUE TITLE
Can't clone projects from git@github.com

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#14288]
### Describe the bug

I tried to clone via `Git Clone...` link in the Welcome page.
And I couldn't clone my project on GitHub with the SSH URL.
Che-Theia popped-up `Git: Host key verification failed`.

But there is the private key for my GitHub account in the container.
And I could clone my project via the console panel.

### Che version

 - [x] latest

### Steps to reproduce

0. (SSH key has been stored.)
1. Open the workspace.
2. Click `Git Clone...` on the Welcome page.
3. Enter the `git@github.com:...` style URL to the text box.
4. The error dialog was popped-up.

### Expected behavior

Clones the repository with no error.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T17:09:13Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots

![Screenshot 2019-08-20 at 13 45 15](https://user-images.githubusercontent.com/101795/63318385-46da7500-c351-11e9-8fc8-1432283ce1b1.png)

![Screenshot 2019-08-20 at 14 01 15](https://user-images.githubusercontent.com/101795/63318879-054ac980-c353-11e9-832b-83a807c628b3.png)

### Installation method
   - [x] I don't know

### Environment
   - [x] my computer 
       - [x] Linux
   - [x] Cloud
       - [x] Azure

**Comment by gorkem** [comment]
This is because known_hosts is missing the entry for github and che/theia does not handle it like the git client does when doing the cloning from the IDE.
