### ISSUE TITLE
Provide ability to map component to containerName

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14280]
### Is your task related to a problem? Please describe.
We have opportunity to define a `component` for `che` commands in devfile.
In runtime we get something like:

![tasks_question](https://user-images.githubusercontent.com/5676062/63256209-c435b500-c27f-11e9-8190-6692f6df3bd3.png)

So we have info about `component` and target `containerName` in attributes for a command.

But I don't know way how we can map `component` and `containerName` using `machines` object in runtime. For example, if user changes the label for a task or defines in `task.json` `component` for a new task  - how we can map it to corresponding `containerName`? 

### Describe the solution you'd like
It would be great to have some attributes for `machines` object in runtime to have ability to map 
`component` and corresponding `containerName`.

### Additional context
I need it to improve the behavior related to https://github.com/eclipse/che/issues/13993#issuecomment-521794918

**Comment by sleshchenko** [comment]
Is triaged in the same way as depending issue https://github.com/eclipse/che/issues/13993#issuecomment-521794918
