### ISSUE TITLE
Commands not loading from new workspace.

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1428]
Edited the default java stack. I know it's loading the modification because I changed the description name to make sure. Should these commands be loaded when I start the workspace?

```
  "commands": [
    {
      "commandLine": "mvn clean install -f ${current.project.path}",
      "name": "Clean Install",
      "type": "custom"
    },
    {
      "commandLine": "mvn compile -f ${current.project.path}",
      "name": "Compile",
      "type": "custom"
    },
    {
      "commandLine": "mvnDebug jetty:run -f ${current.project.path}",
      "name": "Jetty Debug",
      "type": "custom",
      "attributes": {
            "previewUrl": "http://${server.port.8080}/${current.project.relpath}"
      }
    }
  ]
```

**Comment by ghost** [comment]
@james10174 right now commands come with sample projects and are saved into workspace config after a workspace is created.

However, an engineer is working on makes it possible to associate a set of commands with stacks.

This is a bug and it will be fixed in this sprint.

**Comment by james10174** [comment]
@eivantsov What does "this sprint" mean?

**Comment by ghost** [comment]
@james10174 it means that it's almost merged in master :)

**Comment by ghost** [comment]
@james10174 this pull request is a fix for the bug - https://github.com/eclipse/che/pull/1455

I'm closing the issue, feel free to reopen if it does not work for you or there are further questions you have about commands.

**Comment by james10174** [comment]
@eivantsov Will this be in the current nightly download yet?

**Comment by james10174** [comment]
@eivantsov Nevermind I cloned latest from github and built with maven. It works!
