### ISSUE TITLE
che-docs: it's not possible to scroll navigation bar

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14294]
### Describe the bug
che-docs: it's not possible to scroll navigation bar as a result I'm not able to reach some of last items without rescaling the browser page.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Go to https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/
2. Click `Expand all`
3. Try to open the last item - `Che extensibility reference`

### Expected behavior
It's possible to choose any of navigation bar item without scaling (scale = 100%)

### Screenshots
![che-docs](https://user-images.githubusercontent.com/5887312/63351241-8d3ace80-c367-11e9-817c-3a5a54d1957d.gif)

**Comment by sleshchenko** [comment]
cc @rkratky

**Comment by themr0c** [comment]
The JavaScript that make the menu foldable (CDNJS (Cloudflare) jQuery v2.1.4) is the cause of trouble. I used Decentraleyes until very shortly: this browser plugin is blocking the incriminated JavaScript. Menu are not foldable anymore, but are scrollable.

**Comment by ibuziuk** [comment]
@themr0c @rkratky removed `need-triage` label, please set a milestone based on the doc team priorities

**Comment by themr0c** [comment]
@ibuziuk I don't have that power :)

**Comment by themr0c** [comment]
I investigated a little about the issue: it appear to be related to the usage of bootstrap (3.3.7). The Latest version of bootstrap (4.3.1) would break the multi-level menus (https://www.komposta.net/article/navgoco) which has no available upgrade candidate. The issue is still present with latest version of bootstrap in the 3.x series (3.4.1).

**Comment by derol01** [comment]
Hi Team,

Experiencing the same issue with the Eclipse Che4z part of the docs. I would like to increase the priority as this has a direct impact on customer experience and affects the ability to navigate.

**Comment by rkratky** [comment]
I believe I've been able to fix the problem in https://github.com/eclipse/che-docs/pull/874 -- test, please.

**Comment by themr0c** [comment]
I tested eclipse/che-docs#874 and I confirm I found the issue fixed.
