### ISSUE TITLE
Merge plugin brokers (init, unified) into a single container image build

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14296]
### Is your enhancement related to a problem? Please describe.

Having two tiny containers to delete the /projects folder and then populate means 2x the number of containers to maintain, build, release to Quay or RHCC, and 2x the number to have to pull when supporting offline/airgap scenarios.

### Describe the solution you'd like

We could consider merging these two tiny containers into a single one. 

See also:
* https://github.com/eclipse/che/issues/12398
* https://github.com/eclipse/che/issues/13452
* https://github.com/eclipse/che-plugin-broker/pull/68#issuecomment-522516628

**Comment by amisevsk** [comment]
I'd probably do this as a part of https://github.com/eclipse/che/issues/13452 since it resolving workspace differences would bring the brokers closer together.

**Comment by ibuziuk** [comment]
moving to 7.2.0 for now and adding to the prioritization doc for the next sprint discussion

**Comment by ibuziuk** [comment]
Note, that once implemented docs should be updated accordingly - https://www.eclipse.org/che/docs/che-7/che-workspaces-architecture/#che-plug-in-broker_che-workspace-components

**Comment by ibuziuk** [comment]
Closing. it was decided not to merge 2 images in one, but rather focus on refactoring - https://github.com/eclipse/che/issues/14494
