### ISSUE TITLE
Chectl starts Che components in the wrong order

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#14305]
### Describe the bug

When using `chectl` to deploy Che on OKD 3.11, using the operator, I'm finding that the Che operator deploys some Che components in the wrong order compared to what Chectl is expecting (devfile and plugin registry before keycloak, rather than the other way around). This ends up causing the keycloak operation to time out, and Che being unable to be deployed.

 What happens is while chectl is waiting for Keycloak to be deployed, the operator actually deploys the devfile and plugin registries first, then keycloak. This ends up taking so much time that chectl thinks the keycloak deployment failed and times out, preventing the deployment of Che.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Download the latest version of chectl
2. Start Che with `chectl server:start --domain=<domain> --platform=openshift`
3. Wait for chectl to start deploying Che. It will deploy Postgres, then the devfile/plugin registries, then keycloak, and usually timing out eventually. Rather than deploying postgres, then keycloak, then the devfile/plugin registries and not timing out.

### Expected behavior

Che can be deployed using chectl without timing out

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
Johns-MacBook-Pro-3:~ johncollier$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server <server>
openshift v3.11.0+f8b6451-269
kubernetes v1.11.0+d4cacc0
```
### Installation method
   - [x] chectl  `chectl server:start --domain=<domain> --platform=openshift`
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Additional context

Chectl:
```
johns-mbp-3:~ johncollier$ chectl server:start --domain=9.21.109.190.nip.io --che-operator-cr-yaml=Desktop/eclipse-che.yaml --platform=openshift
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
  ✔ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Create ServiceAccount che-operator in namespace che...It already exists.
    ✔ Create Role che-operator in namespace che...done.
    ✔ Create RoleBinding che-operator in namespace che...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...done.
    ✔ Create Che Cluster eclipse-che in namespace che...done.
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Keycloak pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✖ starting
        → ERR_TIMEOUT: Timeout set to pod ready timeout 130000
      Devfile registry pod bootstrap
      Plugin registry pod bootstrap
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check

```

Che operator logs: 
[che_operator.log](https://github.com/eclipse/che/files/3527941/che_operator.log)

**Comment by tolusha** [comment]
I am not sure if order is wrong. Maybe someone has a better vision, but in case of timeout you can try `k8spodreadytimeout`:

```
--k8spodreadytimeout=k8spodreadytimeout      [default: 130000] Waiting time for Pod Ready Kubernetes (in milliseconds)
```

https://github.com/che-incubator/chectl

**Comment by sleshchenko** [comment]
@johnmcollier Thanks for reporting it. The order is really inconsistent:
From che-operator logs:
```
time="2019-08-21T22:26:31Z" level=info msg="Creating a new object: Deployment, name: postgres" 
time="2019-08-21T22:26:32Z" level=info msg="Waiting for deployment postgres. Default timeout: 420 seconds" 
time="2019-08-21T22:28:38Z" level=info msg="Deployment 'postgres' successfully scaled to 1" 
...
time="2019-08-21T22:28:58Z" level=info msg="Creating a new object: Deployment, name: plugin-registry" 
time="2019-08-21T22:28:59Z" level=info msg="Waiting for deployment plugin-registry. Default timeout: 420 seconds" 
time="2019-08-21T22:29:07Z" level=info msg="Deployment 'plugin-registry' successfully scaled to 1" 
...
time="2019-08-21T22:29:07Z" level=info msg="Creating a new object: Deployment, name: devfile-registry" 
time="2019-08-21T22:29:08Z" level=info msg="Waiting for deployment devfile-registry. Default timeout: 420 seconds" 
time="2019-08-21T22:29:20Z" level=info msg="Deployment 'devfile-registry' successfully scaled to 1" 
...
time="2019-08-21T22:29:20Z" level=info msg="Creating a new object: Deployment, name: keycloak" 
time="2019-08-21T22:29:21Z" level=info msg="Waiting for deployment keycloak. Default timeout: 420 seconds" 
time="2019-08-21T22:32:07Z" level=info msg="Deployment 'keycloak' successfully scaled to 1" 
...
time="2019-08-21T22:32:38Z" level=info msg="Creating a new object: Deployment, name: che" 
time="2019-08-21T22:32:39Z" level=info msg="Updating codewind-che CR with status: Che API: Unavailable" 
time="2019-08-21T22:32:39Z" level=info msg="Waiting for deployment che. Default timeout: 420 seconds" 
time="2019-08-21T22:34:26Z" level=info msg="Deployment 'che' successfully scaled to 1" 
...
time="2019-08-21T22:34:26Z" level=info msg="Updating codewind-che CR with Keycloak URL status: http://keycloak-che.9.21.109.190.nip.io" 
time="2019-08-21T22:34:26Z" level=info msg="Custom resource codewind-che updated" 
time="2019-08-21T22:34:26Z" level=info msg="Updating codewind-che CR with status: Eclipse Che server: Available" 
time="2019-08-21T22:34:26Z" level=info msg="Custom resource codewind-che updated" 
time="2019-08-21T22:34:26Z" level=info msg="Updating codewind-che CR with Eclipse Che server URL: http://che-che.9.21.109.190.nip.io" 
time="2019-08-21T22:34:26Z" level=info msg="Custom resource codewind-che updated" 
time="2019-08-21T22:34:26Z" level=info msg="Eclipse Che is now available at: http://che-che.9.21.109.190.nip.io" 
```

**Comment by ibuziuk** [comment]
@davidfestal could you please take a look and comment?
@johnmcollier would you be interested in providing PR for fixing this?

**Comment by ibuziuk** [comment]
@johnmcollier I believe it is done on the operator side, @davidfestal could you please point out where exactly ?

**Comment by sleshchenko** [comment]
> Does chectl need to be updated to represent the proper order of deployment that the Che operator does?

I believe that che-operator and chectl order should be the same.
Chectl related code is here https://github.com/che-incubator/chectl/blob/master/src/commands/server/start.ts#L282

**Comment by davidfestal** [comment]
On the Che operator side, the fix would mainly consist in installing the Keyckoak server before the registries, which means, moving [these lines](https://github.com/eclipse/che-operator/blob/09a90beea6502f970cb0e3713b4f6e3ed955e728/pkg/controller/che/che_controller.go#L643-L677) before [this line](https://github.com/eclipse/che-operator/blob/09a90beea6502f970cb0e3713b4f6e3ed955e728/pkg/controller/che/che_controller.go#L405)

However, as @sleshchenko pointed, we could also simply update chectl so that it would wait for the components in the order they are installed by the Che operator:
- Postgres
- Registries
- Keycloak
- Che

@l0rd do you have a preference about the side where we should fix this (operator or chectl) ?

**Comment by l0rd** [comment]
I would say that doing the change operator side is easier. chectl currently use the same code in the case of any installer (operator and helm). 

A more robust solution would be that chectl spawns 5 threads that wait asynchronously for the different pods (registries, keycloak, postgres, che) to be available. That would work for both helm and the operator. But at this point, with only 2 installers that we control completely, I don't think it's worth implementing this more robust solution.

**Comment by ibuziuk** [comment]
@davidfestal PR got merged. Can we close the issue ?

**Comment by davidfestal** [comment]
Sure.

**Comment by johnmcollier** [comment]
@davidfestal @ibuziuk Just tried with the new chectl binary, works great. Thanks a ton!
