### ISSUE TITLE
Che 6 -> Che7 workspace migration warnings on UD point to the wrong content

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14308]
Currently "documentation" links point to https://www.eclipse.org/che/docs/che-6/what-are-workspaces.html which does not have any migration content:

![image](https://user-images.githubusercontent.com/1461122/63365697-66d15f00-c378-11e9-876a-95101ce77606.png)

![image](https://user-images.githubusercontent.com/1461122/63365724-7650a800-c378-11e9-91f1-09822ecae72b.png)

Those links should point to the official "Converting a Che 6 workspace to a Che 7 devfile" - https://www.eclipse.org/che/docs/che-7/converting-a-che-6-workspace-to-a-che-7-devfile/

**Comment by vparfonov** [comment]
lets fix it in 7.1.0

**Comment by ibuziuk** [comment]
@evidolob @olexii4 could you please take a look ?

**Comment by ibuziuk** [comment]
PR with workaround https://github.com/eclipse/che-docs/pull/794

**Comment by olexii4** [comment]
@ibuziuk Something with docs URL redirections
![Screenshot from 2019-08-28 20-31-30](https://user-images.githubusercontent.com/6310786/63879191-d75d2900-c9d3-11e9-96bb-5666e4fa3947.png)
https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/product.json#L27

And when I try to find a doc by URL
http://che-che.192.168.99.100.nip.io/docs/what-are-workspaces.html
it redirects me to 
http://che-che.192.168.99.100.nip.io/che/docs/che-6/what-are-workspaces.html

Then, if I remove '/che/' by my hands
http://che-che.192.168.99.100.nip.io/docs/che-6/what-are-workspaces.html

It returns me a target doc page

**Comment by l0rd** [comment]
@olexii4 can you just use the direct link https://www.eclipse.org/che/docs/che-7/converting-a-che-6-workspace-to-a-che-7-devfile/ and open a separate issue for the redirect issue?

**Comment by olexii4** [comment]
@l0rd  I have done
 https://github.com/eclipse/che/pull/14377

**Comment by l0rd** [comment]
Thanks @olexii4

**Comment by l0rd** [comment]
@ibuziuk we should be able to close this issue now

**Comment by sunix** [comment]
@ibuziuk I am closing it. Feel free to reopen it if needed.

**Comment by nickboldt** [comment]
Reopening. I'd like some clarification on how hard it'll be to override the link to https://www.eclipse.org/che/docs/che-7/converting-a-che-6-workspace-to-a-che-7-devfile/ in the dashboard so we can link to http://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/ instead.

Do I need to do anything more than just updating the CRW 2.0 product.json file?

![image](https://user-images.githubusercontent.com/227597/65435103-ef1aa800-dded-11e9-8d4e-85a1374b7fc3.png)

**Comment by ibuziuk** [comment]
@olexii4 could you please comment ^ ?

**Comment by olexii4** [comment]
@nickboldt It is very easy to override the link. I will make a fix in the dashboard(fix the hardcoded link and remove TODO marker). 20min

**Comment by olexii4** [comment]
Sorry. I closed it accidentally when adding a comment.

**Comment by olexii4** [comment]
By the way, we still have problems with our CHE and che-docks routings:
![Screenshot from 2019-09-24 16-45-03](https://user-images.githubusercontent.com/6310786/65521580-21153280-def2-11e9-891f-73997a133d98.png)
We have a link ```<a href="/che/docs/che-6">Che 6 documentation</a>``` and in the case, when we are  using this che-docs inside our CHE - a link will be  ``` <che-host>/che/docs/che-6>```.  It is very bad because the route  ``` <che-host>/che/...>``` is reserved for the workspace starting. 
![Screenshot from 2019-09-24 16-48-17](https://user-images.githubusercontent.com/6310786/65522277-38085480-def3-11e9-9eb5-572fb20d2ea4.png)

https://github.com/eclipse/che-docs/blob/master/src/main/_config-war.yml#L6

And as I can saw in the commit 
616bd35f80b373975ba98c8083269af3d0d8ab1d

``` "/docs/" ```  ->   ``` "/che/docs/" ```

**Comment by ibuziuk** [comment]
> when we are using this che-docs inside our CHE 

@olexii4 you mean when che workspace is started with the docs repo in it (using che for docs creation) ? It looks like this bug would prevent dogfooding on hosted che. Could you please create a separate issue for this cc @rkratky

**Comment by olexii4** [comment]
@ibuziuk I have already created one  https://github.com/eclipse/che/issues/14386
