### ISSUE TITLE
chectl Install process is strange

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14302]
### Describe the bug
Using the instructions provided under https://github.com/che-incubator/chectl#installation on Linux has strange results:
1. `chectl-install.log` is created with `root` ownership: 
    ```
    -rw-r--r--. 1 root     root          480 Aug 21 10:22 chectl-install.log
    ```
2. The installed artifacts have `uid` `501` and group `games` (`gid` `20`):
    ```
    -rwxr-xr-x. 1 501 games     1590 Aug 14 11:55 chectl
    ```

### Che version
Fedora 30
```
$ chectl version
chectl/0.0.20190814-next.d78ef53.d78ef53 linux-x64 node-v10.16.2
```

### Steps to reproduce
1. Install `chectl` as described in the ["Installation" section](https://github.com/che-incubator/chectl#installation)
    ```
    bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
    ```
2. Look at installed files: `ls /usr/local/lib/chectl`

### Expected behavior
Files added while sudo have owner `uid` and `gid` of `0`

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux (Fedora 30
       - [ ] macOS

**Comment by benoitf** [comment]
I think uid/gid are the one in travis-ci uid/gid ( as when we untar a tar archive)

**Comment by ibuziuk** [comment]
@l0rd I put it to `7.1.0` for now, please change the milestone if this is not crucial for the upcoming release

**Comment by l0rd** [comment]
@amisevsk what are the consequences for the end user? Does he need to `chmod` to be able to execute `chectl`?
