### ISSUE TITLE
mvn install failed when dashboard build

### ISSUE THREAD

**Issue by hjbbjh** [eclipse-che/che#14317]
### Describe the bug
when i run mvn install，gulp not found error。

### Che version
7.0.0

### Steps to reproduce

run command：
mvn -e install -DskipTests -Dlicense.skip=true -Dskip-enforce -Dskip-validate-sources -Dfindbugs.skip -DskipIntegrationTests=true -Dmdep.analyze.skip=true -Dmaven.test.skip=true
in the root dir

### Screenshots
![图片](https://user-images.githubusercontent.com/18327687/63570079-7f2abf00-c5ae-11e9-963a-6f9da7bfc8c6.png)

### Environment
Windows

**Comment by tolusha** [comment]
Try to install it and rebuild the project.
`npm install --global gulp`

**Comment by hjbbjh** [comment]
@tolusha 
![图片](https://user-images.githubusercontent.com/18327687/63571951-3fff6c80-c5b4-11e9-9ff0-d691537fb73e.png)
![图片](https://user-images.githubusercontent.com/18327687/63571965-4aba0180-c5b4-11e9-8cd4-eb185b261b50.png)

**Comment by ibuziuk** [comment]
@hjbbjh are you still facing this issue? e.g. it is not possible to build che on Windows ?

**Comment by olexii4** [comment]
We have had another image in the Dockerfile. It shouldn't happen. I am going to close this issue.

@hjbbjh  You can reopen this issue If you still have the same problems.
