### ISSUE TITLE
Factory with space `%20` character in url always fails

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14312]
### Describe the bug

When creating workspace by factory, passing link with space character `%20` or `%2520` will always fail.

Second issue here is that the error message on factory screen is:
_"This factory is using old workspace definition format which is not compatible anymore. Please follow the documentation to update the definition of the workspace and benefits from the latest capabilities."_
which is very misleading.

Minimal devfile url to test here https://gist.githubusercontent.com/sparkoo/39f6cfd28bf7daf53004ff0ae7c08806/raw/c4692bbb82ff404c1e40c0b88e817aa5d1af09ef/space%2520here
(from my public gist https://gist.github.com/sparkoo/39f6cfd28bf7daf53004ff0ae7c08806)

### Che version

 - [x] latest

### Steps to reproduce

- go to url `[che_instance]/f?url=https://gist.githubusercontent.com/sparkoo/39f6cfd28bf7daf53004ff0ae7c08806/raw/c4692bbb82ff404c1e40c0b88e817aa5d1af09ef/space%2520here`
- see it failed
  - Internal Server Error occurred, error time: 2019-08-22 15:11:08

### Expected behavior

create valid workspace

### Runtime
   - [x] minikube

### Screenshots

![20190822_171419_645x579_scrot](https://user-images.githubusercontent.com/1160903/63526844-577d1d80-c500-11e9-971e-5626d12de80e.png)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by skabashnyuk** [comment]
url ```[che_instance]/f?url=https://gist.githubusercontent.com/sparkoo/39f6cfd28bf7daf53004ff0ae7c08806/raw/c4692bbb82ff404c1e40c0b88e817aa5d1af09ef/space%2520here``` is double encoded. Correct one 
is  ```https://gist.githubusercontent.com/sparkoo/39f6cfd28bf7daf53004ff0ae7c08806/raw/c4692bbb82ff404c1e40c0b88e817aa5d1af09ef/space%20here```
