### ISSUE TITLE
In unit tests, no classes were found

### ISSUE THREAD

**Issue by hjbbjh** [eclipse-che/che#14318]
### Describe the bug
In unit tests, no classes were found

### Che version
7.0.0

### Screenshots
![图片](https://user-images.githubusercontent.com/18327687/63570344-6078f800-c5af-11e9-93c5-3f99c699175a.png)
![图片](https://user-images.githubusercontent.com/18327687/63570389-94541d80-c5af-11e9-8bda-968817a7006e.png)

**Comment by skabashnyuk** [comment]
@hjbbjh thank you for this issue. Can you explain your expectation? Is the problem exists if you are not using IntelijIdea?

**Comment by hjbbjh** [comment]
no，i wish you can check all the project and fix them

**Comment by skabashnyuk** [comment]
```org.eclipse.che.api.core.server.dto.DtoServerImpls.ServiceErrorImpl``` is generated file. 

![Знімок екрана  о 10 25 09](https://user-images.githubusercontent.com/1614429/63578230-4f6cbe80-c590-11e9-8f40-a39e1f209cf7.png)
To fix this error you just need to run ```mvn clean install``` and allow Intelij to index generated files.

**Comment by hjbbjh** [comment]
ok，thanks

**Comment by sleshchenko** [comment]
@skabashnyuk You're right but I do not really understand why DtoImpls are used there. I've done a quick look and create a fix for that https://github.com/eclipse/che/pull/14320

**Comment by sleshchenko** [comment]
cc @hjbbjh Now DTOImpls is not used in the referenced places
