### ISSUE TITLE
Implement methods in TestWorkspaceUtil.ts

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#14316]
Implement unimplemented methods in `TestWorkspaceUtil.ts`:
- [ ] getIdOfRunningWorkspace
- [ ] removeWorkspaceById
- [ ] stopWorkspaceById

Those methods should contain a logic of switching between single/multi user.

### Describe the solution you'd like
The way we are doing that in Rh-Che is that we have environmental variable for TOKEN. If there would be such variable in upstream, the switch can be something like that:
- if TOKEN variable is set, add header with authentication to the request
- if TOKEN is not set, use single user approach

You can get inspired in Rh-Che approach here: https://github.com/redhat-developer/rh-che/pull/1563/files#diff-e5037b450f3f25a654585fa8d0080bafR18

**Comment by ibuziuk** [comment]
@Katka92 I put `7.2.0` milestone. Are you going to work on this issue ?

**Comment by Katka92** [comment]
Well, it can be me or anybody else from Che QE. I don't think it is a high priority issue as in upstream they don't need to use those methods yet. Maybe @rhopp input would be nice there.
