### ISSUE TITLE
Improve the Che 6 -> Che 7 migration doc

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#14315]
### Is your task related to a problem? Please describe.
I tried to migrate Che 6 workspace to Che 7 using this documentation: https://www.eclipse.org/che/docs/che-7/converting-a-che-6-workspace-to-a-che-7-devfile/ and I have a few issues.

The first problem is accessing a documentation. There is already issue for that https://github.com/eclipse/che/issues/14308

The procedure of migration Che 6 workspace to Che 7:
**1. Open an old Che 6 configuration file.**
There are steps how to access configuration file, but those steps are placed at the end of a document. I think it would be more useful to have them right in this step. I didn't expect those steps to be at the end so I found them when I was done.

**2. Create a new workspace from the similar Che 7 devfile**
There are not all old stack types listed in a `Table 1`, e.g. vert.x is missing.

**3. Add the required number of blank projects.**
I'm not sure if I was supposed to create a workspace first and then go to the Workspace configuration to the `Projects` window to add a blank project or add a blank project before I create a workspace. If the second option is correct, this step should be a part of a second step.
Anyway, I was not able to find out how to add blank project trying both ways:
- adding project to already created workspace
![Screenshot from 2019-08-22 16-55-20](https://user-images.githubusercontent.com/29278800/63525430-fce2c200-c4fd-11e9-8162-31b45117e011.png)

- adding project when creating a workspace
![Screenshot from 2019-08-22 16-58-49](https://user-images.githubusercontent.com/29278800/63525534-26035280-c4fe-11e9-9845-f2a15cad8d28.png)

**4. Change the required devfile fields.**
I don't understand what a screenshot at this section is trying to say me:
![Screenshot from 2019-08-22 17-00-11](https://user-images.githubusercontent.com/29278800/63525745-7b3f6400-c4fe-11e9-8c86-69ad7c42e782.png)

There is no info where to find a devfile fields. I think it would be useful to have there some example on how to change a devfile or even a link to a devfile specification, so user can see what are the parameters he/she can set up. 

### Describe the solution you'd like
Update obsolete information - user is not able to create blank project anymore. Replace that with the guide how can then import a project, which is used in Che 6 workspace (e.g. change a devfile, import project when creating Che 7 worksapce, import project from Theia UI).
Make the documentation clearer even for users who are not much familiar with devfile or does not have much experiences with a Dashboard e.g. by including some screenshots or more precise steps.

**Comment by ibuziuk** [comment]
@Katka92 will you be able to provide a PR to https://github.com/eclipse/che-docs with the doc improvements listed in the issue description ?

**Comment by Katka92** [comment]
@ibuziuk I can try :D I'm not good at writing docs, so I will write some "draft" and ask you for a review then :)

**Comment by Katka92** [comment]
@ibuziuk Can you help me please?

| Che 6        | Che 7           |
| ------------- | ------------- | 
| Apache camel based projects, Apache Camel based projects on Che 7    | Apache Camel based on **Spring Boot** ~~projects on Che 7~~ | 
| .NET, . NET Core with Theia IDE    | .NET Core ~~with Theia IDE~~  |  
| Go, CentOS Go, Go with Theia IDE | GO ~~with Theia IDE~~ |  
| Java Gradle | Java Gradle |
| Blank, Java, Java-MySQL, Eclipse Che, **Java CentOS** | Java Maven |
| Node, CentOS nodejs | NodeJS Express Web Application |
| Python, Python with Theia IDE | Python ~~with Theia IDE~~ |
| **Android** | |
| **CentOS Wildfly Swarm** | |
| **Eclipse Vert.x** | **Java Vert.x** |
| **PHP** | **PHP Simple** |
| **Rails** | | 
| **Spring Boot** | **Java Spring Boot** | 
| **Ceylon with Java JavaScript Dart on CentOS** | | 

I have a few questions on you:
1) Can you help me with filling the missing spaces in a table?
2) I would recommend to remove the ~~strikethroug~~ words and I've added the **bold** ones. Can you please check those changes (e.g. if stacks are compatible)?
3) There are some stacks in a table that were not in a RhChe on production (version `7.0.0-RC-1.1`) e.g. ` Go with Theia IDE`, should I leave them there?

**Comment by ibuziuk** [comment]
> Can you help me with filling the missing spaces in a table?

I believe there are no Android, Rails & Ceylon devfiles, so let's not include them in the table. 

> I would recommend to remove the strikethroug words and I've added the bold ones. Can you please check those changes (e.g. if stacks are compatible)?

lgtm, but we would double-check this during PR review

> here are some stacks in a table that were not in a RhChe on production (version 7.0.0-RC-1.1) e.g. Go with Theia IDE, should I leave them there?

this doc is not hosted che specific, so let's leave them there

**Comment by Katka92** [comment]
@ibuziuk @l0rd @pdaverh I've created a PR with my changes. Looking forward to see your ideas! 
https://github.com/eclipse/che-docs/pull/796

**Comment by olexii4** [comment]
@Katka92 @l0rd  I have prepared another variant. I think it is enough:
https://docs.google.com/document/d/1qrHg4F2FvTpafJAvgqgzeYTu6M0UA1mSjm_UCoQNFHc/edit#
WDYT?

**Comment by ibuziuk** [comment]
@olexii4 those are great improvements, but eclipse/che-docs#796 is ready to be merged and this is currently a blocker for Che 7 promotion to Hosted Che. Will it be possible to provide another docs PR with the improvements based on the gdoc once we would merge the original PR?

**Comment by Katka92** [comment]
The PR with changes in migration docs was merged and documentation is currently up-to-date. I'll close this issue. @olexii4 If you find some areas that are not described enough or you want to enhance the docs, please feel free to create another PR to https://github.com/eclipse/che-docs. Thank you!
