### ISSUE TITLE
add a devfile in che-samples/console-java-simple 

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14310]
A brand new user discovering Che would probably navigate to https://www.eclipse.org/che/getting-started/cloud/, look at the section "Create a workspace from your GitHub or GitLab repo", navigate to the proposed repository https://github.com/che-samples/console-java-simple, and try to find in that repository a nice example devfile.

But currently  https://github.com/che-samples/console-java-simple does not contain a `devfile.yaml`. It contains a `.codenvy.json`file, though, which is probably the previous form of a devfile.

I believe this `.codenvy.json`file should be converted to a proper `devfile.yaml`.

**Comment by amisevsk** [comment]
Apart from maintaining updates, there seems to be no reason to not just include the `console-java-simple` devfile in the devfile registry repo, right?

**Comment by themr0c** [comment]
Maybe it's the https://www.eclipse.org/che/getting-started/cloud/ page that should not propose a link to  this repository?

**Comment by ibuziuk** [comment]
Closing. All devfiles for https://www.eclipse.org/che/getting-started/cloud/ are planned to be stored in https://github.com/redhat-developer/devfile/tree/master/getting-started 
Also, I believe it is a good idea to deprecate all https://github.com/che-samples in general and use real-world examples in the devfiles (both for 'getting-started' and devfile registry)
