### ISSUE TITLE
Fix Java selenium tests to run against Che with next version for default plugins

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14325]
### Is your task related to a problem? Please describe.
After Che master has been switched to Che Theia `next` which based on Theia `master` branch, we need to adapt Java selenium test to be executed against Theia from master branch:
- org.eclipse.che.selenium.dashboard.CreateAndDeleteProjectsTest.deleteProjectsFromDashboardTest
- org.eclipse.che.selenium.dashboard.CreateAndDeleteProjectsTest.createProjectTest
- org.eclipse.che.selenium.dashboard.ImportMavenProjectFromGitTest.checkAbilityImportMavenProjectTest
- org.eclipse.che.selenium.dashboard.ImportProjectFromGitHubTest.checkAbilityImportProjectFromGithub

- org.eclipse.che.selenium.factory.DirectUrlFactoryWithSpecificBranchTest.factoryWithDirectUrlWithSpecificBranch
- org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolderTest.factoryWithDirectUrlWithRootFolder

Java selenium tests report with regression: https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/2088/Selenium_20tests_20report/

### Describe the solution you'd like
There is fixup https://github.com/eclipse/che/issues/14248 which could be reused for Java selenium tests.

**Comment by ibuziuk** [comment]
@dmytro-ndp @SkorikSergey the issue is assigned, please put a milestone based on the team priorities
