### ISSUE TITLE
Outdated chectl version is installed via 'next' release channel

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#14322]
### Describe the bug

`chectl` `next` release channel brings an outdated version although the [doc](https://github.com/che-incubator/chectl#installation) says:
> Next is updated after each commit/Pull Request being merged in master branch

### Steps to reproduce

Install `chectl` using `next` release channel as described in the README:
`bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next`

[chectl `0.0.20190814-next.d78ef53`](https://github.com/che-incubator/chectl/releases/tag/20190814155403) is installed which has been released 9 days ago and 3 newer versions were released later.

### Expected behavior

[chectl `0.0.20190822-next.5c5f553`](https://github.com/che-incubator/chectl/releases/tag/20190822122043) should be installed which is the latest one ATM

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux, Fedora 30
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@l0rd could you please take a look?

**Comment by benoitf** [comment]
Fixed
