### ISSUE TITLE
[Selenium] Sometimes Theia IDE does not open after starting workspace

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#14321]
### Describe the bug

Sometimes **Theia IDE** does not open after starting workspace. This issue reproduces randomly by selenium tests. 

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create and start workspace from any stack or from factory.
2. Wait for the workspace is started and **Theia IDE** is opened.

### Expected behavior
**Theia IDE** is opened.

### Actual behavior
Workspace has ```RUNNING``` status but **Theia IDE** is not opened.
![org eclipse che selenium factory DirectUrlFactoryWithRootFolderTest factoryWithDirectUrlWithRootFolder_time-1566491081705-millis](https://user-images.githubusercontent.com/7760565/63589005-9b2f6000-c5b0-11e9-8899-c8ddd3bf7f65.png)

### Selenium test report
https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/2080//Selenium_20tests_20report/

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

**Comment by ibuziuk** [comment]
@evidolob @rhopp moving to `7.x` for now, please set milestone based on the team 's priorities

**Comment by dmytro-ndp** [comment]
Is not reproduced.
