### ISSUE TITLE
can't start workspace because related pods not created

### ISSUE THREAD

**Issue by leader-us** [eclipse-che/che#14324]
Version Elipse Che 7.0  on kubernetes V 1.15 
![err0](https://user-images.githubusercontent.com/5953348/63595969-c20b8780-c5ec-11e9-9bb7-419f025d4473.PNG)

on my notebook ,with nginx gateway controller ,nodeport  & hostnetwork controller pod

tried many times ,but workspace can't be started success 
![err1](https://user-images.githubusercontent.com/5953348/63596120-1ca4e380-c5ed-11e9-9a9f-4a3e26c9adde.PNG)

the following is browser console &   ingress pod's log 
 
![err2](https://user-images.githubusercontent.com/5953348/63596224-5249cc80-c5ed-11e9-9184-d22f4386d668.PNG)
![err3](https://user-images.githubusercontent.com/5953348/63596234-57a71700-c5ed-11e9-9a18-243d1178822c.PNG)

It seems never created workspace related deployment's or any pod ,so websocket no any response (timeout)
maybe a bug ?

**Comment by skabashnyuk** [comment]
@leader-us thank you for this report. Can you please provide additional information:
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by leader-us** [comment]
Thanks.
Che version is 7.0   ,image "eclipse/che-server:7.0.0"
helm source file from  https://github.com/eclipse/che/tree/7.0.x/deploy/kubernetes/helm/che
deployed by Helm ,ingress domain is mychedomain (by core dns to resolve those domains to centos 7 VM )
helm upgrade --install myche     -f ./values/default-host.yaml  --set global.ingressDomain=mychedomain ./
default-host.yaml content is following
global:
  multiuser: true
  ingressDomain: mychedomain
  serverStrategy: default-host


platform is kubernetes on centos 7 VM by VMware workstation on windows 10 
centos 7 vm's ip is 192.168.18.3 . 
[root@k8s_lab ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

I'm Using nginx ingress controller to route ,
[root@k8s_lab che]# kubectl  describe svc  -n ingress-nginx   ingress-nginx
Name:                     ingress-nginx
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/part-of=ingress-nginx
Annotations:              <none>
Selector:                 app.kubernetes.io/name=ingress-nginx,app.kubernetes.io/part-of=ingress-nginx
Type:                     LoadBalancer
IP:                       169.169.225.135
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  22795/TCP
Endpoints:                192.168.18.3:80
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  62220/TCP
Endpoints:                192.168.18.3:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

I tried  NodePort and LoadBalancer type of Ingress Service ,the result same ,no che workspace related pod created 
W0824 07:17:48.342075       6 controller.go:878] Service "workspaceah452uhwmt71s5yz/serverp1tt3f8q-theia-ide0yh" does not have any active Endpoint.
W0824 07:17:48.342123       6 controller.go:878] Service "workspaceah452uhwmt71s5yz/serverp1tt3f8q-theia-ide0yh" does not have any active Endpoint.
W0824 07:17:48.342142       6 controller.go:878] Service "workspaceah452uhwmt71s5yz/serverp1tt3f8q-theia-ide0yh" does not have any active Endpoint.
W0824 07:17:48.342162       6 controller.go:878] Service "workspaceah452uhwmt71s5yz/serverva7udx8k-jwtproxy" does not have any active Endpoint.
W0824 07:17:48.342179       6 controller.go:878] Service "workspaceah452uhwmt71s5yz/serverp1tt3f8q-theia-ide0yh" does not have any active Endpoint.

**Comment by leader-us** [comment]
I'm not sure the follow Debug error message 
![err111](https://user-images.githubusercontent.com/5953348/63634195-a0121380-c685-11e9-9b8e-8721baed5fb1.PNG)
![err1112](https://user-images.githubusercontent.com/5953348/63634196-a902e500-c685-11e9-9595-2d7eb39c7499.PNG)

**Comment by leader-us** [comment]
login from github ,so my test user account is from github and auto added into che 
![image](https://user-images.githubusercontent.com/5953348/63634249-478f4600-c686-11e9-9edf-94f49c8626fd.png)
![image](https://user-images.githubusercontent.com/5953348/63634258-71e10380-c686-11e9-992c-1515ba85a577.png)
![image](https://user-images.githubusercontent.com/5953348/63634266-87eec400-c686-11e9-837b-188e681547ee.png)

When click workspace , some error ocured in browser console 
![image](https://user-images.githubusercontent.com/5953348/63634279-c71d1500-c686-11e9-9282-34756010e23e.png)

**Comment by sleshchenko** [comment]
I suppose it duplicates the following issue https://github.com/eclipse/che/issues/10767

K8s infrastructure creates pods only when loader IP is assigned to ingress, but for some installations, it is never assigned and actually, there is no need to wait for it.

**Comment by leader-us** [comment]
> I suppose it duplicates the following issue #10767
> 
> K8s infrastructure creates pods only when loader IP is assigned to ingress, but for some installations, it is never assigned and actually, there is no need to wait for it.

This is a bug of eclipse che ? and not fixed yet ?   no any resolve method ?

**Comment by leader-us** [comment]
after I use helm installed ngix ingress from https://github.com/helm/charts/tree/master/stable/nginx-ingress (with hostnetwork  param set to true)
it's seems containers created and ready 
![12](https://user-images.githubusercontent.com/5953348/63860598-fb246d00-c9db-11e9-8781-77a8ba2bde23.PNG)

But an nother problem occured !



![14](https://user-images.githubusercontent.com/5953348/63861081-c6fd7c00-c9dc-11e9-8724-708d64be6ef2.PNG)

**Comment by leader-us** [comment]
related system log :  Aug 28 21:53:17 k8s_lab kubelet: E0828 21:53:17.481132    8932 kuberuntime_container.go:71] Can't make a ref to pod "workspaceah452uhwmt71s5yz.python-588d66bf97-fnsn4_workspaceah452uhwmt71s5yz(6644ada2-8737-4f7b-8353-62ce1770ddb6)", container python: selfLink was empty, can't make reference
