### ISSUE TITLE
Java language server does not start with che-remote-plugin-runner-java8:next

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14328]
### Describe the bug
The Java language server fails to start when the workspace is started pointing at the current nightly release of the plugin registry. I suspect this is related to https://github.com/eclipse/che-plugin-registry/commit/f0eb1f0568d8e9a129f18ed15faecf1eba16b052

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start java workspace, using `quay.io/eclipse/che-plugin-registry:nightly` as the plugin registry. 
2. No output from java plugin, only basic code completion, no "thumbs up" icon in bottom.

### Expected behavior
Java language server starts.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2019-08-23 11-39-53](https://user-images.githubusercontent.com/16168279/63605066-33bae580-c59b-11e9-82bf-076cb0083fe4.png)

### Installation method
   - [x] `deploy_che.sh` (necessary because operator requires cluster-admin)

### Environment
   - [x] Cloud
       - [x] OpenShift dev cluster

**Comment by amisevsk** [comment]
cc: @vparfonov

**Comment by ibuziuk** [comment]
@tsmaeder could you please take a look - seems important so I put `7.1.0` milestone

**Comment by tsmaeder** [comment]
@amisevsk how are you running Che? Why are you pointing it at a non-default registry?

**Comment by amisevsk** [comment]
@tsmaeder This is on the OpenShift dev cluster we use. I don't think it's a cluster issue as it's pretty consistently reproducible.

What do you mean by "default" registry? We're currently moving away from having Che provide default registries of any kind, since the che.openshift.io registries are for prod/prod-preview only -- https://github.com/eclipse/che/issues/14266.

I've tested:
- Che-server `7.0.0` + devfile registry `7.0.0` + plugin-registry `7.0.0`: Works
- Che-server `nightly` + devfile registry `7.0.0` + plugin-registry `7.0.0`: Works
- Che-server `7.0.0` + devfile registry `nightly` + plugin-registry `7.0.0`: Works
- Che-server `nightly` + devfile registry `nightly` + plugin-registry `7.0.0`: Works
- Che-server `nightly` + devfile registry `nightly` + plugin-registry `nightly`: **Does not work**

**Comment by tsmaeder** [comment]
I'm closing this one: since we're now deploying the plugin registry with che, we should always get the correct one. Running nightly of che works for me.
