### ISSUE TITLE
Impossible to start workspace

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14336]
### Describe the bug

After restarting the minikube with existing Che workspace I was not able to continue my work.
Che server was failing with the following error

![Screenshot from 2019-08-27 10-20-37](https://user-images.githubusercontent.com/1655894/63759638-2022be00-c8be-11e9-9edb-0be18a8b4b37.png)

Then I
- stopped and deleted running `minikube` by commands `minikube stop` and `minikube delete`
- deleted all local docker images/containers
- updated `chectl` to the latest version
- started `minikube` with a command `minikube start --memory=10240 --cpus=4 --disk-size=20g`
- started Che server by `chectl server:start`
- created a workspace from `NodeJS Express Web Application` stack (tried also to use devfile)

My workspace always fails

![Screenshot from 2019-08-27 11-19-14](https://user-images.githubusercontent.com/1655894/63760299-5c0a5300-c8bf-11e9-80ee-996e8f108333.png)

![Screenshot from 2019-08-27 11-21-44](https://user-images.githubusercontent.com/1655894/63760309-60cf0700-c8bf-11e9-9c45-19b810b24703.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Described in the issue description

### Expected behavior

Running workspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

This is blocker for IDE2 team as we are using Che for daily work.

**Comment by metlos** [comment]
As a workaround, please add this env var to the configuration of the che server:
```
CHE_INFRA_KUBERNETES_INGRESS_PATH__TRANSFORM=%s
```

The fix will follow rather quickly...

**Comment by metlos** [comment]
Note that if `chectl` used the latest helm chart, you shouldn't have seen this issue (https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/configmap.yaml#L75)
