### ISSUE TITLE
if cluster is rebooted, postgres won't be able to reclaim the same PV or at least it would experience permissions issue

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#14331]
#14299 # Describe the bug
I did some investigation and I found this: https://medium.com/faun/digitalocean-kubernetes-and-volume-permissions-820f46598965 where it describes the exact issue of the postgres
I don't know how to use mountOptions as it says:
```
mountOptions:
- dir_mode=0777
- file_mode=0777
```
however, for the alternative method, it seems that i need to modify the yaml of the pod of which i can't do so since i'm using `chectl`.
That is the output of the `postgres` pod after k8s cluster reboot:
```

Initial call to run-postgresql...
chmod: changing permissions of '/var/lib/pgsql/data/userdata': Operation not permitted
pg_ctl: could not open PID file "/var/lib/pgsql/data/userdata/postmaster.pid": Permission denied
Initializing Che user...
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Warning: Failed initializing the Che user and database
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
pg_ctl: could not open PID file "/var/lib/pgsql/data/userdata/postmaster.pid": Permission denied
chmod: changing permissions of '/var/lib/pgsql/data/userdata': Operation not permitted
```
And because of the log entry above, postgres never starts `Readiness probe failed: psql: FATAL: could not open relation mapping file "global/pg_filenode.map": Permission denied`

Do we have a suggested/recommended PV yaml for k8s deployment?

**Comment by SDAdham** [comment]
A new update, I deployed another che instance last night, I didn't touch it at all, just made a simple configuration (it was working as I created workspaces just fine), however today I cannot create workspaces, checking up on the pods, I see `postgres` is coming up with this issue here, i don't know why (even though there was no reboot)

**Comment by SDAdham** [comment]
From postgres pod:
```
bash-4.2$ ls -al /var/lib/pgsql/data/userdata/global/
ls: cannot access /var/lib/pgsql/data/userdata/global/: Permission denied
```

**Comment by ibuziuk** [comment]
@SDAdham could you please all the details in the issue description? how did you deploy Che, which version? on which infrastructure? There is a template for the issue creation:

### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by SDAdham** [comment]
### Describe the bug

already provided

### Che version

 - [ ] latest
 - [ ] nightly
 - [X] other: please specify
```
Che-Theia@e358e2f using Theia@e358e2f
Built 8/14/2019, 7:53:02 AM
List of extensions:
@theia/core 0.8.0
@theia/output 0.8.0
@theia/process 0.8.0
@theia/filesystem 0.8.0
@theia/variable-resolver 0.8.0
@theia/workspace 0.8.0
@theia/languages 0.8.0
@theia/editor 0.8.0
@theia/callhierarchy 0.8.0
@theia/console 0.8.0
@theia/json 0.8.0
@theia/userstorage 0.8.0
@theia/preferences 0.8.0
@theia/navigator 0.8.0
@theia/markers 0.8.0
@theia/terminal 0.8.0
@theia/task 0.8.0
@theia/cpp 0.8.0
@theia/debug 0.8.0
@theia/debug-nodejs 0.8.0
@theia/editorconfig 0.8.0
@theia/file-search 0.8.0
@theia/keymaps 0.8.0
@theia/merge-conflicts 0.8.0
@theia/messages 0.8.0
@theia/mini-browser 0.8.0
@theia/outline-view 0.8.0
@theia/scm 0.8.0
@theia/search-in-workspace 0.8.0
@theia/plugin-ext 0.8.0
@theia/plugin-dev 0.8.0
@theia/plugin-ext-vscode 0.8.0
@theia/preview 0.8.0
@theia/textmate-grammars 0.8.0
@eclipse-che/theia-remote 0.0.1
@eclipse-che/theia-plugin-ext 0.0.1
@eclipse-che/theia-terminal 0.0.1
@eclipse-che/theia-user-preferences-synchronizer 0.0.1
@eclipse-che/che-theia-hosted-plugin-manager-extension 0.0.1
@eclipse-che/theia-dashboard-extension 0.0.1
@eclipse-che/theia-activity-tracker 1.0.0
@eclipse-che/theia-about 0.0.1
@eclipse-che/theia-preferences-provider-extension 0.0.1
```

### Steps to reproduce

A newly deployed che environment today
followed the steps of https://www.eclipse.org/che/docs/che-7/version-control/
>ssh: delete key pair (nothing happens clicking it)

### Expected behavior


### Runtime
   - [X] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T17:06:39Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots


### Installation method
   - [X] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
```
chectl/7.0.0 linux-x64 node-v10.16.2
```

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [X] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [X] other (please specify) 
   - [ ] other: please specify

Private cloud

**Comment by SDAdham** [comment]
> > From postgres pod:
> > ```
> > bash-4.2$ ls -al /var/lib/pgsql/data/userdata/global/
> > ls: cannot access /var/lib/pgsql/data/userdata/global/: Permission denied
> > ```
> 
> Well that is curious. Can you also provide the output of `id` and `ls -al` for the tree down to `/var/lib/pgsql/data/userdata/global/` -- i.e. `ls -al /` `ls -al /var` ...

permission is denied

**Comment by SDAdham** [comment]
i can exec into it but i get permission denied when i try to access any of those files

**Comment by SDAdham** [comment]
BTW, this is how I create the PV:
```
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      volume: pv01
    name: pv01
  spec:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
    capacity:
      storage: 50Gi
    hostPath:
      path: /var/lib/kubernetes_containers
    persistentVolumeReclaimPolicy: Recycle
```
I wanted to use *mountOptions*:
```
#    mountOptions:
#    - dir_mode=0777
#    - file_mode=0777
```
but I couldn't, seems that i need at least either ceph or nfs so that's why i'll try after configuring storage as previously mentioned in the comment above. And I believe it's the PV setup that's the issue

**Comment by amisevsk** [comment]
@SDAdham could you provide additional details about the Che install that had this issue?

- What the backing storage for PVs on the cluster?
- What `chectl` command did you use to install Che? I.e. did you use the helm chart or the operator

**Comment by SDAdham** [comment]
@amisevsk 
* Not sure about this question, the PV has been already provided in my previous comment
* Same deployment as https://github.com/eclipse/che/issues/14050#issue-473706673

**Comment by SDAdham** [comment]
Hi All,

After configuring https://jaas.ai/docs/storage , i'm not experiencing this issue anymore. The server was rebooted so many times, shutdown and back up and yet Che gets back up and running just fine.

Thanks!
