### ISSUE TITLE
[chectl] chectl workspace verb `start` is misleading

### ISSUE THREAD

**Issue by kameshsampath** [eclipse-che/che#14344]
When you want to create a workspace using `chectl` you issue a command `chectl workspace:start` as the verb `start` indicates the command will create an start workspace ( so is its description) but the workspace is not started until the user clicks the url.

So IMHO - the verb should be renamed as `workspace:create` or allow to start the workspace asynchronously

**Comment by l0rd** [comment]
Makes sense @kameshsampath, thanks for raising it.

**Comment by l0rd** [comment]
We can keep `workspace:start` but update the behavior so that it starts the workspace (`start-after-create=true`). And can add `--create-only` flag for users that only want to create the workspace.

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/14874

**Comment by mmorhun** [comment]
Fixed.
New command `chectl workspace:create` is introduced. It has `--start` flag which will start the workspace right after creation. Also added support for devfile in current directory, so `-f` flag is not mandatory any more.
Old `chectl workspace:start` command is deprecated and acting now as `chectl workspace:create --start`
