### ISSUE TITLE
Add VNC server to the "eclipse/che-e2e" docker image

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14341]
### Is your task related to a problem? Please describe.
The "VNC" server is a helpful tool for debugging and monitoring of remote desktop.
It should be added to the "eclipse/che-e2e" docker image

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: there is example of setting up VNC server within the container image: https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChromeDebug/Dockerfile

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/14730
