### ISSUE TITLE
The list of Editors of a minimal workspace is empty

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14340]
### Describe the bug

We can create a new workspace using the following devfile:

```
metadata:
  name: wksp-test
apiVersion: 1.0.0
```  

But then the editors list in Editor tab of the workspace configuration is empty. The problem get fixed if we add any component to the devfile.

### Che version
 - [x] nightly
 
### Steps to reproduce

1. Create a new workspace from the devfile

```
metadata:
  name: wksp-test
apiVersion: 1.0.0
```

2. Open 'Editors' tab

### Expected behavior

A full editors list.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)

### Screenshots

![Screenshot from 2019-08-27 13-30-38](https://user-images.githubusercontent.com/6310786/63767928-94b62680-c8d7-11e9-95e7-8972d7871276.png)

### Installation method
   - [x] chectl

**Comment by l0rd** [comment]
@olexii4 I have updated the title and description of this issue to make it clearer. Please have a look and confirm that my modifications are correct.

**Comment by olexii4** [comment]
@l0rd Your modifications are correct. Thanks a lot.

**Comment by sunix** [comment]
@olexii4 if you work on this, could you have a quick look at https://github.com/eclipse/che/issues/14407 and see if it is related. If it is easy to fix both issues at the same time, go ahead.

**Comment by olexii4** [comment]
@sunix Ok
