### ISSUE TITLE
Create 'master', 'nightly', 'release' CI for 'che-machine-exec' plugin and move images to quay.io

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14357]
### Is your task related to a problem? Please describe.
Create 'master', 'nightly', 'release' CI for 'che-machine-exec' plugin and move images to quay.io. 
This is already done for plugin and devfile registries - https://quay.io/organization/eclipse 

Currently, for `machine-exec` there is only codenvy 'release' CI that should be decommissioned - https://ci.codenvycorp.com/view/release/job/release-che-machine-exec-plugin/

**Comment by ibuziuk** [comment]
cc: @vparfonov @AndrienkoAleksandr are you ok with this approach? Might be wrong, but AFAIK there is no other CI that https://ci.codenvycorp.com/view/release/job/release-che-machine-exec-plugin/ for the `machine-exec` plugin

**Comment by AndrienkoAleksandr** [comment]
@ibuziuk I am OK with this approach.

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr am I correct that  https://ci.codenvycorp.com/view/release/job/release-che-machine-exec-plugin/ is the only CI for machine-exec atm ?

**Comment by AndrienkoAleksandr** [comment]
> @AndrienkoAleksandr am I correct that https://ci.codenvycorp.com/view/release/job/release-che-machine-exec-plugin/ is the only CI for machine-exec atm ?

Yes, you are right.

**Comment by ibuziuk** [comment]
I would propose the following CI / tags:
-  `master` - CI is triggered on `master` commits and tags based on the git commit hash & pushes to quay.io
- `nightly` - CI is triggered from the `master` branch on a daily basis and pushes `nightly` images to quay.io
- `release` - CI is triggered from the `release` branch, tags images based on the `VERSION` file  e.g
`7.2.0` and pushes images to `quay.io`

@vparfonov @AndrienkoAleksandr I do not think other tags are needed like e.g. `next` `7.0.0-next` that present in https://hub.docker.com/r/eclipse/che-machine-exec/tags
If those are needed please clarify the use-case.

**Comment by ibuziuk** [comment]
PR for creating CI jobs - https://github.com/openshiftio/openshiftio-cico-jobs/pull/1073
quay.io repo - https://quay.io/repository/eclipse/che-machine-exec

**Comment by ibuziuk** [comment]
@vparfonov @l0rd I would propose to use quay.io for `7.2.0` release and deprecate the docker one

**Comment by ibuziuk** [comment]
PR sent - https://github.com/eclipse/che-machine-exec/pull/45

**Comment by ibuziuk** [comment]
PRs are merged. Clsosing
