### ISSUE TITLE
Internal Server Error/DB error occurs when Devfile has invalid format on updating

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14350]
### Describe the bug

Internal Server Error/DB error occurs when Devfile has invalid format on updating.
It's needed to tell user that actually Devfile must be updated and it's not Che Server error at all.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a new workspace from the devfile

```
metadata:
  name: wksp-test
apiVersion: 1.0.0
```

2. Open 'Devfile' tab

3. Try to add update devfile with the following content:
```
apiVersion: 1.0.0
metadata:
  name: wksp-test
components:
  -
```
or 
```
apiVersion: 1.0.0
metadata:
  name: wksp-test
components:
  - type:
```

### Expected behavior

A user is notified that Devfile has an invalid format.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2019-08-28 16-05-37](https://user-images.githubusercontent.com/6310786/63858616-7c650b00-c9ae-11e9-88f1-6cbcc0ca8c68.png)
![Screenshot from 2019-08-28 16-03-48](https://user-images.githubusercontent.com/6310786/63858619-7ec76500-c9ae-11e9-8816-8e77c73fcbe0.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
It's related to https://github.com/eclipse/che/issues/13526 but I'm not sure that it fully duplicates it.
@olexii4 Could you take a look on the updated issue and confirm that it's what you wanted to report?

**Comment by olexii4** [comment]
@sleshchenko Yes. It is exactly what I wanted to report. Many thanks

**Comment by skabashnyuk** [comment]
Duplicates https://github.com/eclipse/che/issues/13526
