### ISSUE TITLE
[Doc] Installation guide

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14362]
In the Administration Guide, please provide more content for the Installation Guide.

The Quick starts are covering a short version of the installation, but we need a more in depth guide.

Here is the expected outline:

  * [ ] Installation Guide
      * [ ] Che installation overview
        * [ ] Target platforms
        * [ ] Deployment architecture diagram
      * [ ] Che installation prerequisites
        * [ ] Storage
        * [ ] Networking
        * [ ] Identity
      * [ ] Installing Che on different Kubernetes distributions
      * [ ] Updating Che
      * [ ] Advanced configuration options
        * [ ] Che configMaps and their behavior (concept)
        * [ ] Che configuration reference table
        * [ ] Deploying Che with HTTPS mode
        * [ ] Deploying Che without authentication
        * [ ] Configuring Che Persistent Volumes strategy
        * [ ] Configuring Che using already existent instances of Keycloak and Postgres
        * [ ] Configuring private Docker registries
        * [ ] Configuring email notifications
        * [ ] Configuring namespace strategies
        * [ ] Configuring workspace memory settings
        * [ ] Configuring Che with OpenShift OAuth
      * [ ] Troubleshooting Che installation

**Comment by l0rd** [comment]
@themr0c sections `Deploying Che without Keycloak` and `Configuring Che with and without Keycloak` looks identical. Maybe we meant `Deploying Che without authentication` and `Using already existent instances of Keycloak and Postgres`?

Anyway your SME here is @benoitf

**Comment by themr0c** [comment]
@l0rd My bet is there will be serious rework of the outline during the writing process, that's why I kept all chapters in one issue here. We surely have to rename it to "Advanced installation guide" or something like that, as the "Quick starts" are already covering common scenarios for installation.

**Comment by themr0c** [comment]
"Configuring namespace strategies" has been done: https://github.com/eclipse/che-docs/pull/825/
Still has to be activated in the side menu.
