### ISSUE TITLE
How about supporting Mercurial as a version control tool ?

### ISSUE THREAD

**Issue by mrjoops** [eclipse-che/che#1436]
Hi all,

Mercurial have strong supporters among the developer community (me, at least, but you can found some of them at Mozilla, Facebook or in the Java community too), so how about writing a plugin for it ?
For the moment it's the only issue that prevent my company to use Che instead of our "IDE/Fat client over NX" solution.
I'd be glad to help but it has been more than 10 years since I wrote anything in Java, so for the sake of us all, it's better if I don't write it.
I previously saw this feature as wanted somewhere on a suggestion page on the web (maybe on the codenvy website, I don't remember) but I don't see anything on GitHub, so here it is !

Anyway Che is a pretty impressive tool, so keep up the good work and thank you !

**Comment by TylerJewell** [comment]
@mrjoops - first, you have a very cool handle identity.

As for your request - we have not gotten many requests for mercurial. We've maybe seen <6 over the past three years. You are the first request we have seen this year. We have gotten some requests for perforce.  Codenvy may consider adding in a Mercurial plugin if there was a commercial relationship with a vendor.  The challenge is not implementing such extensions, but it's the ongoing maintenance and support. There needs to be a wide array of unit tests built, test infrastructure created, and then run as part of Eclipse integration systems continuously.

**Comment by mrjoops** [comment]
Thank you @ddementieva, i'll try this quickly (I always preferred the CLI anyway).

@TylerJewell I'd be very interested in knowing what are your expectations towards a commercial relationship. Maybe you could PM me about this ? (eventually interested in being that vendor)

**Comment by TylerJewell** [comment]
@mrjoops - sure happy to discuss.  Github doesn't publish email identities. But you can contact me: tyler [at] codenvy [dot] com.

**Comment by TylerJewell** [comment]
Closing this for now as it was treated as more of a support ticket instead of a long term implementation issue.
