### ISSUE TITLE
[Doc] Configuring your VCS credentials for your workspaces

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14361]
In the *End-User Guide*, please provide more content for *Configuring your VCS credentials for your workspaces*.

Probably we need to differentiate some "using the Dashboard" and some "using a devfile" version.

**Comment by l0rd** [comment]
@themr0c: you can work with @azatsarynnyy that is comfortable writing and works on the team that is responsible for the VCS credentials injection in workspaces
