### ISSUE TITLE
[Doc] API reference

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14367]
In the *Administration Guide*, please provide more content for *API reference*.

Expected outline:

   * [ ] API reference
        * [ ] Access to Swagger
        * [ ] Workspace API
        * [ ] Permissions API
        * [ ] Factory API
        * [ ] Resources API
        * [ ] IDE macros

**Comment by l0rd** [comment]
@themr0c: @skabashnyuk is your SME here
