### ISSUE TITLE
[Doc] Viewing plug-in broker logs

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14363]
In the *Administration Guide/ Retrieving Che logs*, please provide more content for *Viewing plug-in broker logs*.

**Comment by l0rd** [comment]
@themr0c: @amisevsk is your SME here

**Comment by amisevsk** [comment]
Getting workspace logs in general is kind of tricky; for the broker, there's really only what's displayed to the user while the workspace is starting. The pod itself is deleted very quickly.

I've created issue https://github.com/eclipse/che/issues/14412 to track this.

Looking at our current *View workspace logs* section in the documentation, there's really only a reference to events; this is another issue as the deletion of the plugin broker means events will in most cases be unavailable.

**Comment by themr0c** [comment]
Thanks @amisevsk. I believe this is already sufficient information to document what is available right away. When something new gets implemented in #14412, would you be kind enough to create a [Doc] issue afterwards so that we can update the documentation?

**Comment by amisevsk** [comment]
:+1: Will do, thanks @themr0c.

**Comment by themr0c** [comment]
@amisevsk I can write the stuff if you like. It will be a short one, some rephrasing around following. Thanks a lot for your input, it is very valuable.

```
Viewing  plug-in broker logs 

* there's really only what's displayed to the user while the workspace is starting. 
* The logs from the plug-in broker are not persisted. As the pod itself is deleted very quickly, events will in most cases be unavailable.
```

**Comment by MichalMaler** [comment]
My update was merged. Please, mark this box as done
