### ISSUE TITLE
[Doc] Defining workspaces using the dashboard

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14360]
In the *End-User Guide*/*Using developer workspaces*, please provide more content for *Defining workspaces using the dashboard*.

Here is the expected outline:

    * [ ] Defining workspaces using the dashboard
      * [ ] Configuring runtimes
      * [ ] Exposing services
      * [ ] Mounting specific volumes into workspaces
      * [ ] Setting environment variables
      * [ ] Configuring projects

**Comment by l0rd** [comment]
@themr0c: @nickboldt that has already written a brilliant doc on the creating workspaces from the dashboard can help you here
