### ISSUE TITLE
Ability to set up Eclipse Che in  single-host/default-host mode with operator

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14374]
### Is your task related to a problem? Please describe.
It this moment its possible to setup Eclipse Che in  single-host/default-host mode only with Helm

### Describe the solution you'd like
Allow configuring parameter ```che.infra.kubernetes.server_strategy``` (and other related if needed) from operator CR.

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/14189

**Comment by tolusha** [comment]
@skabashnyuk 
It is possible to properties via `spec.server.customCheProperties`
Is this issue still relevant?

**Comment by tolusha** [comment]
Feel free to open if

**Comment by nickboldt** [comment]
in which milestone was this work completed?

**Comment by tolusha** [comment]
@nickboldt 
The issue is closed as "Already implemented"
a long long time ago...
