### ISSUE TITLE
[Doc] Debug Adapter Protocol reference

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14372]
In the *Contributor Guide/Che extensibility reference*, please provide more content for *Debug Adapter Protocol*.

**Comment by tsmaeder** [comment]
Do you have a link, so we're sure we're talking about the same thing?

**Comment by l0rd** [comment]
@themr0c: @tsmaeder is your SME here

**Comment by themr0c** [comment]
Hi @tsmaeder this piece of documentation was planned in https://github.com/eclipse/che-docs/issues/712 (Che extensibility reference) but has been skipped for Che 7.0 GA. Now it's about time to create it. Are we in the same situation as #14371 and this documentation should be a pointer to https://microsoft.github.io/debug-adapter-protocol/ ?
