### ISSUE TITLE
Ability to set up Eclipse Che in single-host/default-host mode with chectl

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14375]
### Is your task related to a problem? Please describe.
It this moment its possible to setup Eclipse Che in single-host/default-host mode only with Helm

### Describe the solution you'd like
Allow configuring parameter che.infra.kubernetes.server_strategy (and other related if needed) with chectl parameter

### Describe alternatives you've considered
n/a

### Additional context
https://github.com/eclipse/che/issues/14189
https://github.com/eclipse/che/issues/14374

**Comment by tolusha** [comment]
Done in PR https://github.com/che-incubator/chectl/pull/508
