### ISSUE TITLE
[Doc] Language Server Protocol reference

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14371]
In the *Contributor Guide/Che extensibility reference *, please provide more content for *Language Server Protocol*.

It should be a pointer to https://microsoft.github.io/language-server-protocol/

**Comment by tsmaeder** [comment]
@themr0c same question: can you provide a link?

**Comment by l0rd** [comment]
@themr0c: @tsmaeder is your SME here

**Comment by tsmaeder** [comment]
@themr0c I dont' think we should add documentation on the Language server protocol, the LSP is a third party protocol that is very well documented by Microsoft. If we include a copy of that documentation, it only creates work and make the doc potentially out of date. So IMO, we should _reference_ that documentation in an appropriate way.

**Comment by themr0c** [comment]
Hi @tsmaeder , that is very valuable information. What would make more sense: point to the landing page  https://microsoft.github.io/language-server-protocol/  or directly to the specification  https://microsoft.github.io/language-server-protocol/specification ?

**Comment by tsmaeder** [comment]
The landing page: if folks get there the first time, you can get some background.

**Comment by tsmaeder** [comment]
Are you "testing" the doc? How are you doing that?

**Comment by themr0c** [comment]
Great. That will  be an easy one then :)

To test the doc there is a `run.sh` script at the root of the `che-docs` repository.

**Comment by tsmaeder** [comment]
I was not thinking of a technical test, but to find out what it's worth to a newcomer. We're all too close to really serve as test subjects.

**Comment by themr0c** [comment]
OK, in that sense! At the moment, learning to the doc team to install and use Che is our main test. We are trying out what we read in the docs and try to clarify anything unclear. By the end of the month I will also give a workshop presenting Che at http://www.educode.be/ and I hope to learn from the questions the audience will be asking there. Not sure I am addressing your concern though...
