### ISSUE TITLE
Two plugins menu items 

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#14388]
### Describe the bug
When I open the workspace for the first time I see 2 `Plugins` menu items on the Views menu. One of them disappears when I open either one. 

### Che version
Che-Theia@a2cdb33 using Theia@a2cdb33
@theia/core 0.9.0
@theia/output 0.9.0
@theia/process 0.9.0
@theia/filesystem 0.9.0
@theia/variable-resolver 0.9.0
@theia/workspace 0.9.0
@theia/languages 0.9.0
@theia/editor 0.9.0
@theia/callhierarchy 0.9.0
@theia/console 0.9.0
@theia/json 0.9.0
@theia/userstorage 0.9.0
@theia/preferences 0.9.0
@theia/navigator 0.9.0
@theia/markers 0.9.0
@theia/terminal 0.9.0
@theia/task 0.9.0
@theia/cpp 0.9.0
@theia/debug 0.9.0
@theia/debug-nodejs 0.9.0
@theia/editorconfig 0.9.0
@theia/file-search 0.9.0
@theia/keymaps 0.9.0
@theia/merge-conflicts 0.9.0
@theia/messages 0.9.0
@theia/mini-browser 0.9.0
@theia/outline-view 0.9.0
@theia/scm 0.9.0
@theia/search-in-workspace 0.9.0
@theia/plugin-ext 0.9.0
@theia/plugin-dev 0.9.0
@theia/plugin-ext-vscode 0.9.0
@theia/preview 0.9.0
@theia/textmate-grammars 0.9.0
@eclipse-che/theia-remote 0.0.1
@eclipse-che/theia-plugin-ext 0.0.1
@eclipse-che/theia-about 0.0.1
@eclipse-che/theia-user-preferences-synchronizer 0.0.1
@eclipse-che/che-theia-hosted-plugin-manager-extension 0.0.1
@eclipse-che/theia-terminal 0.0.1
@eclipse-che/theia-preferences-provider-extension 0.0.1
@eclipse-che/theia-dashboard-extension 0.0.1
@eclipse-che/theia-activity-tracker 1.0.0
Built 8/29/2019, 8:08:53 AM

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/82738/63964022-35395180-ca64-11e9-8887-a63a000d26b2.png)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by gorkem** [comment]
@vitaliy-guliy looks like https://github.com/eclipse/che-theia/pull/322 is not working as expected.

**Comment by vitaliy-guliy** [comment]
Has already fixed https://github.com/eclipse/che-theia/pull/425
