### ISSUE TITLE
Dashboard Links `Learn more` to the embedded doc site are broken

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14386]
### Describe the bug

Che dashboard UI contains `Learn more` links to an embedded Che documentation site. However, some changes on the Jekyll Che doc site are breaking the redirections to access to the embedded doc site.

The doc section works well on the public documentation site https://eclipse.org/che/docs. 

Problem occurs since:
https://github.com/eclipse/che-docs/blob/master/src/main/_config-war.yml#L6

``` "/docs/" ```  ->   ``` "/che/docs/" ```

### Che version

 - [x] latest

### Steps to reproduce
1. Try to find a docs link with UD(open workspaces tab and click the 'Learn more')
![Screenshot from 2019-10-03 12-29-05](https://user-images.githubusercontent.com/6310786/66115623-de321980-e5d9-11e9-9378-a0313ea8bfe6.png)

or by URL

``` <che-host>/docs/what-are-workspaces.html```

It redirects to
``` <che-host>/che/docs/che-6/what-are-workspaces.html```

![Screenshot from 2019-08-30 10-29-57](https://user-images.githubusercontent.com/6310786/64001818-4ab88500-cb11-11e9-905c-34db1655bbde.png)

Then, if I remove '/che/' by my hands
``` <che-host>/docs/che-6/what-are-workspaces.html```
It returns a doc page
![Screenshot from 2019-08-30 10-30-31](https://user-images.githubusercontent.com/6310786/64001789-3e342c80-cb11-11e9-98fb-e3ebe086fdc3.png)

### Expected behavior

Dashboard link returns the docs page
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

https://youtu.be/1KN494cB-ZE

**Comment by olexii4** [comment]
we still have problems with our CHE and che-docks routings:
Screenshot from 2019-09-24 16-45-03
We have a link <a href="/che/docs/che-6">Che 6 documentation</a> and in the case, when we are using this che-docs inside our CHE - a link will be <che-host>/che/docs/che-6>. It is very bad because the route <che-host>/che/...> is reserved for the workspace starting.
Screenshot from 2019-09-24 16-48-17

https://github.com/eclipse/che-docs/blob/master/src/main/_config-war.yml#L6

And as I can saw in the commit
616bd35f80b373975ba98c8083269af3d0d8ab1d

"/docs/" -> "/che/docs/"

**Comment by ibuziuk** [comment]
@rkratky looks like this one might be a blocker for che-docs on che dogfooding

**Comment by rkratky** [comment]
@olexii4,

>  `We have a link <a href="/che/docs/che-6">Che 6 documentation</a> and in the case, when we are using this che-docs inside our CHE - a link will be <che-host>/che/docs/che-6>. It is very bad because the route <che-host>/che/...> is reserved for the workspace starting.`

We needed to have the `/che/docs/` path there because of the directory structure on eclipse.org/che/docs -- internal links would not resolve correctly without the `/che/` part.

If I understand this correctly, docs accessed from running instances of Che are expected to be found at `/docs/`, not at `/che/docs/`, which is what is causing this problem.

We should be able to fix it by supplying the correct path prefix (`/docs/`) to the build. A quick and dirty solution would be to create one more Jekyll config file that would be used when building docs for the website. So, we would have:
```
$ cat src/main/_config-war.yml
asciidoctor:
  attributes:
    imagesdir: /docs/images
    site-baseurl: /docs/

baseurl: "/docs/"
```
and
```
$ cat src/main/_config-web.yml
asciidoctor:
  attributes:
    imagesdir: /che/docs/images
    site-baseurl: /che/docs/

baseurl: "/che/docs/"
 
```
Not sure if there's a way to test this without rebuilding Che.

**Comment by rkratky** [comment]
@ibuziuk, @olexii4, could you please let me know if you agree with the proposed solution?

**Comment by olexii4** [comment]
@rkratky It is ok for me. 

@skabashnyuk WDYT? Could we have another solution?

**Comment by olexii4** [comment]
@l0rd I am thinking about removing docs from the CHE as default. Then change branding JSON  links 
 to the public one  "https://www.eclipse.org/che/docs/". WDYT?

**Comment by sunix** [comment]
@olexii4 i would keep it simple and add the jekyll config for embedded doc
