### ISSUE TITLE
Create script for provisioning required test workspace

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14385]
### Is your task related to a problem? Please describe.
Now for launching the "happy-path" test we should manually provision the workspace

### Describe the solution you'd like
Automate these steps by script

**Comment by dmytro-ndp** [comment]
It's actually a requirement of Happy path test scenario to run test workspace using **chectl** https://github.com/eclipse/che/issues/12728:
![Screenshot from 2019-08-29 17-15-00](https://user-images.githubusercontent.com/1197777/63948080-bdc5eb00-ca80-11e9-9dc2-c21ffaf7b6ec.png)

**Comment by dmytro-ndp** [comment]
There is an ability to run shell command from typescript https://stackoverflow.com/a/49701572/2556329
It could be used to run `chectl start:workspace` command.
