### ISSUE TITLE
API: Provide a way to test if there are resources name conflicts that may happen during workspace creation/start

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14382]
### Is your task related to a problem? Please describe.
There is a high probability of resource name conflicts in case if a user wants to create more than one workspace in the same namespace. Essentially if he uses custom k8s/openshift tools 
that heavily relays on service/route names.

### Describe the solution you'd like
Dedicated REST API or the part of the response of existed(create/start workspace) API.

### Describe alternatives you've considered
none

### Additional context
 - Dashboard: provide target k8s namespace information https://github.com/eclipse/che/issues/13484
-  API: List of available k8s namespaces for the workspace creation | https://github.com/eclipse/che/issues/14376
-  API: Ability to specify k8s namespace where a user wants to create/start his workspace | https://github.com/eclipse/che/issues/14379

**Comment by l0rd** [comment]
Related to https://github.com/eclipse/che/issues/14263
