### ISSUE TITLE
Allow injecting maven settings in JDT LS sidecar

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14391]
### Is your enhancement related to a problem? Please describe.

The problem has been originally described by #14343. It's currently not possible to specify, in a devfile, maven settings that would be taken into account by the LS.

### Describe the solution you'd like

We can implement a mechanism that would:
- generate a custom `settings.xml` in the sidecar
- specify the settings.xml path in the LS preferences `java.configuration.maven.userSettings`

That maybe done by a plugin init container (mechanism that should be introduced by https://github.com/eclipse/che/issues/13387) that would look for `MAVEN_OPTS` environment variable (https://github.com/eclipse/che/issues/14343 should be addressed first) and generate the settings.xml.

### Describe alternatives you've considered

Another simpler solution that may work would be to pre-package the JDT.LS sidecar image with a settings.xml file:

```
  <mirrors>
    <mirror>
      <url>${env.MAVEN_MIRROR_URL}</url>
    </mirror>
  </mirrors>
```

Settings the environment variable `MAVEN_MIRROR_URL` for the ChePlugin would do the trick then (https://github.com/eclipse/che/issues/14343 need to be fixed first).

**Comment by l0rd** [comment]
cc @kameshsampath

**Comment by fbricon** [comment]
indeed, starting the container with a custom settings.xml, defining a mirror (or not) and the local repository with something like `<localRepository>${env.MAVEN_LOCAL_REPO}</localRepository>` would work. The script starting the container needs to ensure to set the environment variables with default values (same as Maven) or bad things might happen.

cc @tsmaeder

**Comment by kameshsampath** [comment]
We can default to maven central for the variable?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fbricon** [comment]
if MAVEN_MIRROR_URL is not present, the settings.xml should not define the mirror

**Comment by kameshsampath** [comment]
yeah thats what we do currently in most . of the openshift images via entrypoint scripts

**Comment by tolusha** [comment]
The resulted `settings.xml`
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <mirrors>
    <mirror>
      <url>${env.MAVEN_MIRROR_URL}</url>
      <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
</settings>
```

**Comment by tolusha** [comment]
@fbricon I am wonder if `<mirrorOf>central</mirrorOf>` won't break anything.

**Comment by kameshsampath** [comment]
IMHO no but we can make like <mirrorOf>external:*</mirrorOf> to make it better for all external repos as the current one will work only for maven central, WDYT @fbricon?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
