### ISSUE TITLE
Keycloak token exchange support

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14390]
### Is your enhancement related to a problem? Please describe.

When deploying Che on OpenShift using the operator, by default, Keycloak is configured to use OpenShift OAuth. OpenShift users are authenticated then. But, given an OpenShift token, it's not possible to programmatically request a Keycloak. This feature is called token exchange and Keycloak can be configured to support it. That would help to write batch scripts that need access to Che API.

### Describe the solution you'd like

Update Keycloak config to support the token exchange.

**Comment by l0rd** [comment]
cc @kameshsampath

**Comment by ibuziuk** [comment]
Waiting for 7.2.0 and doc PR merge before closing https://github.com/eclipse/che-docs/pull/826

**Comment by themr0c** [comment]
eclipse/che-docs#826 merged.

**Comment by davidfestal** [comment]
Thanks @themr0c !
