### ISSUE TITLE
[Doc] Clarify using a devfile / creating a devfile

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14400]
Please make sure that "Configuring a workspace using a devfile" is focused on how to use a devfile, and "Making a workspace portable using a Devfile" is focused on how to create a devfile. Use links to the other document instead of rewriting it in a shorter way.

**Comment by boczkowska** [comment]
Is this still relevant? https://github.com/eclipse/che-docs/pull/841 seems to have addressed this issue.

**Comment by themr0c** [comment]
You are right.
