### ISSUE TITLE
Simple LSP test suite for Java

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14409]
Create a simple test suite for testing language features with the Che 7 Java support. I should consist of
1. A test suite based on the investigation in https://github.com/eclipse/che/issues/14023
2. A devfile that can run the test suite inside a Che 7 environment 

One of the qualitative goals would be to make it easy to write test suites specific to different language plugins, so we're looking for a kind of framework that can be used to test content assist (and other features) in Java, Python, etc.

**Comment by tsmaeder** [comment]
Reminder that we have some code already here: https://github.com/eclipse-theia/theia/tree/ab/theia-tests/packages/theia-tests. Our testing related code should live in the theia-tests extension

The next steps are:
1. Override LanguagesMain with code that records which language service providers come from which plugin ids. Offer and API that allows tests to query existence of providers (like completion provider) and invoke them for a given plugin id
2. Make it possible to dynamically load a test suite from a file and initialized it with a DI container so that it can access services (like the API written in Step 1
3. Make a first test for vscode java covering basic functionality

**Comment by tsmaeder** [comment]
Open question: should we propose this as a theia PR or start it in che-theia first?

**Comment by JPinkney** [comment]
Here is the basic idea of how it work will with Che:
![Basic idea](https://user-images.githubusercontent.com/8839537/70726903-ca3b2000-1ccc-11ea-9991-8dfad39545cb.png)

At this point in time, the api-test-loader is implemented [1] and a theia extension for the testing api has been implemented [2] [3] but none of it has been put into che-theia itself.

Next steps would include putting the theia extension and the test-loader into che-theia

[1] - https://github.com/JPinkney/api-test-loader
[2] - https://github.com/JPinkney/theia/tree/vscode-extension-testing/packages/test-service-ext
[3] - https://github.com/JPinkney/theia/tree/vscode-extension-testing/packages/test-service

**Comment by tsmaeder** [comment]
@ericwill this is useful work that is sitting there gathering dust.

**Comment by svor** [comment]
Theia plugin with LSP tests for Java is located here: https://github.com/che-incubator/che-java-tests
It also contains a devfile to run tests.
