### ISSUE TITLE
[chectl] Be more specific in the help about the --domain option

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14404]
Context:

After the installation of Code-Ready containers, the user has knowledge of these two URLs:

```
crc start
...
INFO To access the cluster using 'oc', run 'eval $(crc oc-env) && oc login -u kubeadmin -p XXXXX-XXXXX-XXXXX-XXXXX https://api.crc.testing:6443' 
INFO Access the OpenShift web-console here: https://console-openshift-console.apps-crc.testing 
```

Then he needs to fill in a domain option to start a Che server. 
The current documentation of the `--domain` option when using `chectl --help` is not specific enough to help the user choose the right domain.

```
chectl --help
...
--domain=domain                          Domain of the Kubernetes/OpenShift cluster (e.g. 
                                               starter-us-east-2.openshiftapps.com or <local-ip>.nip.io)
```

For a crc, instance, correct value would be `--domain=.apps-crc.testing`.

In other usecases, the user should be helped to decide which domain would be the right one.

Thanks @benoitf fot all the hints.

**Comment by sleshchenko** [comment]
The latest info about --domain parameter is the following:
```
 -b, --domain=domain: 
  Domain of the Kubernetes cluster (e.g. example.k8s-cluster.com or <local-ip>.nip.io)
```

Actually, you do not have to specify a domain for OpenShift installation since it's totally ignored.

But I think it makes sense to keep this issue and maybe UX even better and make it clear that it's unneeded for OpenShift.

cc @benoitf

**Comment by themr0c** [comment]
In the `stable` release, the `domain` option is mandatory: my first run failed because I had not specified the `--domain` parameter.

Is there a way to install latest (unreleased) version of che-incubator/chectl to install the released versions of eclipse/che?

The README.md for chectl is not absolutely clear: "Next is updated after each commit/Pull Request being merged in master branch." Could it be specified if it is the master branch of eclipse/che or of che-incubator/chectl?

**Comment by benoitf** [comment]
@themr0c domain is mandatory for k8s/openshift but it's not for minikube/minishift.
I think we can make it optional for crc as well (computing it)

> Is there a way to install latest (unreleased) version of che-incubator/chectl to install the released versions of eclipse/che?

By default, unreleased version of `chectl` are deploying `nightlies` of `che`
but by providing some flag you can give the che-server image that you want (and use there latest/7.0.0/7.1.0 tags)

>The README.md for chectl is not absolutely clear: "Next is updated after each commit/Pull Request being merged in master branch." Could it be specified if it is the master branch of eclipse/che or of che-incubator/chectl?

thx for reporting. It's updated after each commit inside chectl. Do you want to propose a PR to improve it ?

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/16121

**Comment by mmorhun** [comment]
Added extended description into `chectl` help and readme.
