### ISSUE TITLE
Ominsharp remote plugin doesn't work.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14405]
### Describe the bug
Ominsharp remote plugin doesn't work at all. Seems it's related with merged in the upstream theia "support activation events"

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create new workspace from devfile ".netcore"
2. Await while project will be cloning.
3. Open some ".dotnet" file, for example: Startup.cs
3. Await message from omni-sharp remote plugin:
```
There are unresolved dependencies. Please execute the restore command to continue.
```

Expected result: should appear messages to update dependencies in the .net project, you can click restore button. Than language support should be activated.
Actual result: message never appear. In the View -> Output doesn't appear plugin logs. It's mean plugin doesn't work or didn't activated.

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by AndrienkoAleksandr** [comment]
We have a fix https://github.com/eclipse/che-plugin-registry/pull/199

**Comment by l0rd** [comment]
Closing since eclipse/che-plugin-registry#199 has been merged
