### ISSUE TITLE
Plugins / Editor selection in workspace configuration is confusing

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#14407]
When configuring a workspace, you can select plugins on one tab and the editor to be used on another. Currently, those tabs have no interdependencies. As an example, you can select Jupyter as an editor but also add plugins which only make sense when using Theia. So it would be nice to have some indication in the UI.
Suggestions:

- Mark plugins, which have no dependency to an editor an those which have a dependency
Show a warning if you select a plugin for an editor, that is currently not selected and vice versa a warning if you select another editor, but have plugins which do not make sense then.
- allow to filter plugins by this criterium (either noe ditor dependency or matching the current one)
- Select the Theia editor by default. It seems to be the default anyways, and it is confusing that it works without being selected
- Move the editor tab in front of the plugin tab, as the second kind of depends on the first

**Comment by l0rd** [comment]
That's great feedback @JonasHelming 

@evidolob @olexii4 @sunix we need to take these tasks into next sprint (7.3.0)

**Comment by sunix** [comment]
Hey yep it is still confusing and also
- if you select chePlugins with a non che-theia editor, the workspace is failing to start.
- projects are not cloned (this is done in Che-theia), we should have a way to clone whatever the editor
- we should have a way to access to a kind of "my workspace view" that is not bind to theia: available in the dashboard side panel maybe ... so user could run a terminal on a container or access to an endpoint.
