### ISSUE TITLE
Provision user name and email into git configuration from user profile when newly workspace is created

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#14416]
### Is your enhancement related to a problem? Please describe.
There is a need to provide user name and email into git configuration on workspace creation step in case if user preferences doesn't have git configuration. This means that git configuration should be taken from user profile.

### Describe the solution you'd like
When workspace starts up, we check if we have preference related to `git.user.name` and `git.config.name`. If properties exist, then we configure git config with the last ones, otherwise, we take user name and email from user profile instead.

### Describe alternatives you've considered
--

### Additional context
--

**Comment by azatsarynnyy** [comment]
@l0rd this one is based on your feedback. Could you set a priority, please

**Comment by sunix** [comment]
to me this should have been implemented in #13874 ... so should have the same priority and milestone

**Comment by sunix** [comment]
So let's say that a user has setup Che and configured a Che user and started a workspace with it. Could we, if these have not been set previously, preconfigure/set the git username and git email with the Che user information?

**Comment by vzhukovskii** [comment]
It was decided in comments to the demo video to implement this enhancement in 7.2.0

**Comment by vzhukovskii** [comment]
>Could we, if these have not been set previously, preconfigure/set the git username and git email with the Che user information?

That is the point of this enhancement. To provide user name and email into git configuration if user' preferences don't have anything related to git.
