### ISSUE TITLE
chectl must make sure that objects(like che-operator clusterrole) are up-to-date

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14419]
### Describe the bug
chectl must make sure that objects(like che-operator clusterrole) are up-to-date.
Currently, chectl only checks if che-operator clusterrole, clusterrolebinding exist and does not update them.
But it's possible that such resources are modified and should be updated on cluster as well to keep Che working (like the following PR https://github.com/eclipse/che-operator/pull/66).
So, it's needed to make sure that `chectl` makes sure that resources are current, not just that they exist.
The minimal scope of this issue is `che-operator` role, rolebinding, clusterrole, clusterrolebidings but there can be other resources that must be kept up-to-date as well.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
It's pretty clear but if feel free to ask me to add detailed steps if needed.

### Expected behavior
Che Resources are actual and Che works.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
https://issues.redhat.com/browse/CRW-987
https://issues.redhat.com/browse/CRW-967
https://issues.redhat.com/browse/CRW-1039
https://github.com/eclipse/che/issues/14474

**Comment by tsmaeder** [comment]
@sleshchenko I had some trouble understanding the issue, so I tried to clarify the language.

**Comment by sleshchenko** [comment]
Here are non-tested changes that should fix the described issue https://github.com/sleshchenko/chectl/commit/a776c8fb4379b3c8a4444c5277eb9a874fa3e559

**Comment by dmytro-ndp** [comment]
Downstream issue: https://github.com/eclipse/che/issues/14419

**Comment by tolusha** [comment]
Fixed by https://github.com/che-incubator/chectl/commit/2fca1377fd9835075007c38f57bdb198ae71d0ea

We allows to deploy several Eclipse Che on a single cluster using `--installer operator`.
Every deployment will have it's own clusterrole and clusterrolebinding objects.
Besides this we check if CRD object is the same and throws an error if not.
