### ISSUE TITLE
Init broker failure causes workspace startup to hang

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14414]
### Describe the bug
There are various exit points in Che plugin broker that cause the broker to exit without notifying Che of failure. When this occurs, workspace startup hangs without logs until timeout.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Was reproducible yesterday on the dev cluster, where the [`init` broker](https://github.com/eclipse/che-plugin-broker/blob/1fa7ee8a3c33a3774e770749be5404e8be7d5331/brokers/init/cmd/main.go#L39) would fail [to connect](https://github.com/eclipse/che-plugin-broker/blob/1fa7ee8a3c33a3774e770749be5404e8be7d5331/common/connect.go) to the Che server for pushing events. This would cause the init broker to fail to run and the main broker pod to never enter a starting state. The only way to debug this was to get logs from the init container specifically, via the commandline.

### Expected behavior
In all cases of failure, the existing [`pubFailed`](https://github.com/eclipse/che-plugin-broker/blob/master/common/events.go#L32) method should be used.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Additional Context
Tangentially related to issue https://github.com/eclipse/che/issues/14412.

**Comment by sleshchenko** [comment]
> Expected behavior
> In all cases of failure, the existing pubFailed method should be used.

Sorry, but it does not help in case of plugin broker fails to connect to Che Server, does it?
Maybe Che Server should print init container logs(and maybe containers as well) if no any event is published during some timeout.

**Comment by amisevsk** [comment]
> does not help in case of plugin broker fails to connect to Che Server, does it?

Right, of course that makes sense -- my mistake. I suppose there's no way around this issue via the init broker itself. 

The `log.Fatalf()` is logged correctly but those logs aren't saved anywhere. I suppose this can be closed as a duplicate of #14412.
