### ISSUE TITLE
[OCP4] Che deployment fails due to permission denied in Postgres

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#14426]
### Describe the bug

I installed a basic OCP 4 cluster on AWS. The default `aws-ebs` storage is used. I tried to install Che from the OperatorHub marketplace and the install failed because Postgres entered a `CrashLoopBackOff` state.

The Postgres container's logs show the following error:
```
johns-mbp-3:.odo johncollier$ oc logs postgres-cc6b567f-fc9hj
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Deploy OpenShift 4 on AWS
2. Make sure `aws-ebs` is used for default strorage (should be for new installs on AWS)
3. Install the Che operator from OperatorHub
4. Create a CheCluster custom resource to install Che
5. The Che deployment will fail because Postgres will report the following error:
<img width="1792" alt="Screen Shot 2019-09-04 at 5 53 17 PM" src="https://user-images.githubusercontent.com/6880023/64294532-0ed05600-cf3d-11e9-969d-0ae2175dd6ef.png">

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
johns-mbp-3:.odo johncollier$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://<url>:6443
kubernetes v1.14.0+573d946

```
### Installation method
   - [ ] chectl 
   - [x] che-operator 7.0.0
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
From my understanding it duplicates the https://github.com/eclipse/che/issues/14427

**Comment by amisevsk** [comment]
It does look like an instance of #14331 (at least, in terms of error), but I have no idea what's causing the issue. Maybe @davidfestal can help as he works on the Che operator.

**Comment by davidfestal** [comment]
I don't have much more ideas. If we would need to add some more options in some k8s resources (deployments or PVs, possibly according to what is proposed in issue #14331), we might be able to implement the changes in the operator Go code, build and push a distinct operator docker image, and override it in the installed CSV + operator deployment, to test a possible solution.

**Comment by johnmcollier** [comment]
@davidfestal I can deploy the operator manually on OCP4 if you're able to get me a debug image to use.

**Comment by davidfestal** [comment]
@johnmcollier It wouldn't be possible tomorrow for me, but possibly on Monday.

**Comment by johnmcollier** [comment]
@davidfestal Yeah, no worries and no rush!

**Comment by RickJWagner** [comment]
Hi Guys,
Thanks for working this issue.  There is a support case for the same problem, so please continue to make notes here as progress is made.  
(Also, can we please amend the 'no rush' to be 'there is a small rush, please work as time allows.  :)   )
Thanks,
Rick

**Comment by benoitf** [comment]
bumping severity

**Comment by davidfestal** [comment]
> @davidfestal I can deploy the operator manually on OCP4 if you're able to get me a debug image to use.

@johnmcollier It would be great. I would start working on it on next Monday. And we could sync as soon as you're available.

**Comment by davidfestal** [comment]
@johnmcollier it seems yo installed Che through the operator in the `default` namespace. That might be the underlying reason of the error.
Could you try installing the Che operator in a dedicated namespace you create and check if the problem is still there ?

**Comment by amisevsk** [comment]
@johnmcollier Could you also provide the OpenShift events for the postgres deployment, if you have a chance?

**Comment by johnmcollier** [comment]
@davidfestal @amisevsk Sure thing, I'll install in a non-default namespace and provide the postgres events.

Might be a little bit, I need to reinstall OCP4 first.

**Comment by johnmcollier** [comment]
I reinstalled the Che operator in the `che` namespace and it started working!

Curious: Why does the `default` namespace fail?

**Comment by l0rd** [comment]
Talked with @davidfestal and we should investigate this further to better understand the root cause: how is the Postgres operator behaving? does the che server pod has the same problem?

**Comment by gattytto** [comment]
I'm having the exact same in a fresh install inside a Ubuntu 19 KVM guest with minikube.

`root@ubuntu:~# kubectl get events -n che
LAST SEEN   TYPE      REASON                  OBJECT                                MESSAGE
<unknown>   Normal    Scheduled               pod/che-operator-85465fb857-dql5m     Successfully assigned che/che-operator-85465fb857-dql5m to minikube
66m         Normal    Pulling                 pod/che-operator-85465fb857-dql5m     Pulling image "quay.io/eclipse/che-operator:7.2.0"
59m         Normal    Pulled                  pod/che-operator-85465fb857-dql5m     Successfully pulled image "quay.io/eclipse/che-operator:7.2.0"
59m         Normal    Created                 pod/che-operator-85465fb857-dql5m     Created container che-operator
59m         Normal    Started                 pod/che-operator-85465fb857-dql5m     Started container che-operator
54m         Warning   FailedMount             pod/che-operator-85465fb857-dql5m     MountVolume.SetUp failed for volume "che-operator-token-dhrdd" : failed to sync secret cache: timed out waiting for the condition
54m         Normal    SandboxChanged          pod/che-operator-85465fb857-dql5m     Pod sandbox changed, it will be killed and re-created.
54m         Normal    Pulling                 pod/che-operator-85465fb857-dql5m     Pulling image "quay.io/eclipse/che-operator:7.2.0"
54m         Normal    Pulled                  pod/che-operator-85465fb857-dql5m     Successfully pulled image "quay.io/eclipse/che-operator:7.2.0"
54m         Normal    Created                 pod/che-operator-85465fb857-dql5m     Created container che-operator
54m         Normal    Started                 pod/che-operator-85465fb857-dql5m     Started container che-operator
66m         Normal    SuccessfulCreate        replicaset/che-operator-85465fb857    Created pod: che-operator-85465fb857-dql5m
66m         Normal    ScalingReplicaSet       deployment/che-operator               Scaled up replica set che-operator-85465fb857 to 1
<unknown>   Normal    Scheduled               pod/postgres-54784f4f6f-89xnq         Successfully assigned che/postgres-54784f4f6f-89xnq to minikube
59m         Normal    Pulling                 pod/postgres-54784f4f6f-89xnq         Pulling image "centos/postgresql-96-centos7:9.6"
55m         Warning   FailedMount             pod/postgres-54784f4f6f-89xnq         Unable to attach or mount volumes: unmounted volumes=[default-token-qfdk5 postgres-data], unattached volumes=[default-token-qfdk5 postgres-data]: error processing PVC che/postgres-data: failed to fetch PVC from API server: persistentvolumeclaims "postgres-data" is forbidden: User "system:node:minikube" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "che": no relationship found between node "minikube" and this object
54m         Normal    Pulling                 pod/postgres-54784f4f6f-89xnq         Pulling image "centos/postgresql-96-centos7:9.6"
51m         Normal    Pulled                  pod/postgres-54784f4f6f-89xnq         Successfully pulled image "centos/postgresql-96-centos7:9.6"
50m         Normal    Created                 pod/postgres-54784f4f6f-89xnq         Created container postgres
50m         Normal    Started                 pod/postgres-54784f4f6f-89xnq         Started container postgres
50m         Normal    Pulled                  pod/postgres-54784f4f6f-89xnq         Container image "centos/postgresql-96-centos7:9.6" already present on machine
4m46s       Warning   BackOff                 pod/postgres-54784f4f6f-89xnq         Back-off restarting failed container
59m         Normal    SuccessfulCreate        replicaset/postgres-54784f4f6f        Created pod: postgres-54784f4f6f-89xnq
59m         Normal    ExternalProvisioning    persistentvolumeclaim/postgres-data   waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manually created by system administrator
59m         Normal    Provisioning            persistentvolumeclaim/postgres-data   External provisioner is provisioning volume for claim "che/postgres-data"
59m         Normal    ProvisioningSucceeded   persistentvolumeclaim/postgres-data   Successfully provisioned volume pvc-5b9353ef-5ec3-4ded-aec0-92bfb17f11f2
59m         Normal    ScalingReplicaSet       deployment/postgres                   Scaled up replica set postgres-54784f4f6f to 1
`

`root@ubuntu:~# kubectl get all -n che
NAME                                READY   STATUS             RESTARTS   AGE
pod/che-operator-85465fb857-dql5m   1/1     Running            1          67m
pod/postgres-54784f4f6f-89xnq       0/1     CrashLoopBackOff   15         60m

NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/postgres   ClusterIP   10.99.97.248   <none>        5432/TCP   60m

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/che-operator   1/1     1            1           67m
deployment.apps/postgres       0/1     1            0           60m

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/che-operator-85465fb857   1         1         1       67m
replicaset.apps/postgres-54784f4f6f       1         1         0       60m
`
`root@ubuntu:~# kubectl logs -p  postgres-54784f4f6f-89xnq --namespace che
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
`

**Comment by tomgeorge** [comment]
Comparing che installed in the `che` namespace compared to the `default` namespace reveals that the `securityContext` gets set to `{}` in default, and is properly set in the `che` namespace:

```yaml
  securityContext:
    seLinuxOptions:
      level: 's0:c22,c9'
    fsGroup: 1000480000
```

**Comment by tomgeorge** [comment]
As I'm investigating this more, it seems like `default` does not respect any of the security context constraints by default that are present in openshift... If I make a new user and give them create access to pods and deployments, and they run a pod, it will run as root/the default UID present in that images `Dockerfile`.  When I run the same pod in another namespace it is runs in a security context.  `default` seems to have annotations regarding security contexts, but does not respect them:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c6,c5
    openshift.io/sa.scc.supplemental-groups: 1000040000/10000
    openshift.io/sa.scc.uid-range: 1000040000/10000
  creationTimestamp: "2019-10-28T20:25:55Z"
  name: default
  resourceVersion: "7335"
  selfLink: /api/v1/namespaces/default
  uid: 2515d6e5-f9c1-11e9-9124-028754979780
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

```
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c6,c5
    openshift.io/sa.scc.supplemental-groups: 1000040000/10000
    openshift.io/sa.scc.uid-range: 1000040000/10000
  creationTimestamp: "2019-10-28T20:25:55Z"
  name: default
  resourceVersion: "7335"
  selfLink: /apis/project.openshift.io/v1/projects/default
  uid: 2515d6e5-f9c1-11e9-9124-028754979780
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

I'm starting to think this is just a documentation issue that we will need to point out as @l0rd and @davidfestal have suggested.  I reached out on the aos-devel slack channel but haven't had a reply yet.

**Comment by tomgeorge** [comment]
Last update I think.  There are two problems contributing to this issue:

+ The above comment about random uids not getting correctly assigned in the `default` namespace
+ The default permissions in an ebs volume are 755, which is not group writeable.  In the entrypoint script, it does some commands to change ownership of `/var/lib/pgsql`: https://github.com/sclorg/postgresql-container/blob/1cbbb075fc005e01dad2e4a5abb6d85213b90600/src/root/usr/libexec/fix-permissions#L36

Since by default the ebs volume is only user root writeable, and there is no security context `fsGroup`, the command fails.  

To mitigate this we could change the operator to check if we are in the default namespace and set the security context, or we can document that che should not be run in the default namespace because it won't set the appropriate security context.  We could also advise people that they could use a statically-provisioned PV with appropriate permissions, and back the postgres deployment with that, but I don't know if the operator works that way.

**Comment by tomgeorge** [comment]
There is a known issue for this in the documentation.  Should we open another GH issue to discuss possible code fixes for this?

**Comment by ibuziuk** [comment]
@tomgeorge thanks, I believe we can close the issue since it is documented case and continue the discussion in the https://github.com/eclipse/che/issues/15092

**Comment by tomgeorge** [comment]
I'm unable to close this, can someone please close?
