### ISSUE TITLE
It isn't possible to build che-theia image

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#14437]
### Describe the bug

Build of the `che-theia` image fails.
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Go to /che-theia/dockerfiles/theia
2. Run `./build.sh --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=master --tag:next --branch:master --git-ref:refs\\/heads\\/master`

**WRONG** Error appears: 
```
error /home/theia-dev/theia-source-code/node_modules/@theia/debug-nodejs: Command failed.
Exit code: 1
Command: download-debug-adapters
Arguments: 
Directory: /home/theia-dev/theia-source-code/node_modules/@theia/debug-nodejs
Output:
node-debug: downloading from https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/node-debug/1.35.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
node-debug2: downloading from https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/node-debug2/1.33.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: Not a valid zip file
    at UnzipStream.processDataChunk (/home/theia-dev/theia-source-code/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/home/theia-dev/theia-source-code/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/home/theia-dev/theia-source-code/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at UnzipStream.Writable.write (_stream_writable.js:299:11)
    at Extract._transform (/home/theia-dev/theia-source-code/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
@vinokurig 
Have you tried to build it again?

**Comment by vinokurig** [comment]
I tried 2 times, but know it is not reproduced

**Comment by tolusha** [comment]
I do believe  it is related to build of Theia itself. When it tries to download artifacts for the Marketplace.

**Comment by vinokurig** [comment]
Reopening because the same error is found on CI https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/68/console

**Comment by tolusha** [comment]
Will be fixed by https://github.com/theia-ide/theia/pull/6113

**Comment by tolusha** [comment]
https://github.com/theia-ide/theia/pull/6120

**Comment by tolusha** [comment]
@vinokurig 
It should be ok now, could you check?

**Comment by vinokurig** [comment]
Couldn't reproduce locally, @dmytro-ndp @musienko-maxim Please reopen the issue if you see the error on CI again.
