### ISSUE TITLE
Fail to deploy Che using Che 6 QuickStart instructions

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14447]
### Describe the bug

[Che 6 QuickStart ](https://www.eclipse.org/che/docs/che-6/quick-start.html) fails because image `eclipse/che:latest` doesn't exist.

### Che version

Che 6

### Steps to reproduce

Try to start Che as described in the Che 6 QuickStart:

```
$ docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /local/path:/data eclipse/che start
(...)
/usr/bin/docker-current: manifest for docker.io/eclipse/che:latest not found.
```

### Expected behavior

The command in the QuickStart should work. We have 2 options: 
- Update the Che 6 QuickStart to use an existing image (e.g. `eclipse/che:6.19.0`)
- Tag `eclipse/che:6.19.0` as latest (currently there is [no latest but a rc version](https://hub.docker.com/r/eclipse/che/tags))

### Runtime

Docker (as this is Che 6)

### Installation method

Che CLI

### Environment

my computer / Linux

**Comment by benoitf** [comment]
it was part of Endgame to remove latest and only let tags for the old CLI

**Comment by l0rd** [comment]
@benoitf I think the solution here is to update the Che 6 Quickstart to use a specific version of the `eclipse/che` image (6.19.x).

**Comment by benoitf** [comment]
Provided a PR

**Comment by benoitf** [comment]
PR merged
