### ISSUE TITLE
Failed to load plugins error message

### ISSUE THREAD

**Issue by mayadebellis** [eclipse-che/che#14443]
## Summary

A `failed to load plugins` message appears every time I go to a workspace's administration tabs. I think it relates to this console error about mixed content. If it is, I am not sure where to change the endpoint protocol to https.
<img width="1601" alt="Screen Shot 2019-09-04 at 3 53 03 PM" src="https://user-images.githubusercontent.com/19802975/64368265-c3ff1e80-cfce-11e9-82fe-6947db441fff.png">
The workspace functions totally fine besides this error message. If I go to the plugins tab, it says `There are no editors.` `There are no plugins.` - I am not using any plugins, but I think this makes sense as it was not able to populate this list of plugins from the openshift registry. When I click on the registry link in the error message, it loads a page of plugins correctly, but the protocol just won't allow it to load in che.

Has anyone seen this error before?

## Relevant information
Che Version 6.17.0

**Comment by sleshchenko** [comment]
@fErten @mayadebellis Please share detailed steps how did you deploy Che? Chectl? Which version? Which parameters?

**Comment by fErten** [comment]
@sleshchenko It is an installation based on che 6.x with docker multiuser and eclipse/che-server:6.19.0 image has been used to build server.

**Comment by sleshchenko** [comment]
@fErten Docker infrastructure is deprecated and it's like expected that it does not work.
Are you able to use K8s or OpenShift?

**Comment by fErten** [comment]
@sleshchenko Currently no open shift or any other support. I see that could happen with 7.x related versions since the architecture is changed but how 6 based images are affected by that?

**Comment by sleshchenko** [comment]
Actually - editor/plugins functionality - is actually Che 7 functionality. It won't work on Docker infra.
I guess old Che 6 with installer workspaces should work for you

**Comment by fErten** [comment]
Workspaces work just fine, there is just a notification says "Failed to load plugins" every time when I want to create a new one.

![image](https://user-images.githubusercontent.com/31271774/64849033-cc7cd800-d612-11e9-9aee-0796178d1d03.png)

**Comment by skabashnyuk** [comment]
@fErten I have a doubt that we can help to remove this message is there a way for you to upgrade to Che7 or provide a patch for Che 6.17 dashboard?

**Comment by fErten** [comment]
@skabashnyuk I believe I can provide a patch for dashboard however I am not clear what causes the problem and what should be removed

**Comment by fErten** [comment]
@skabashnyuk any chance you can share your insight with me in order to fix the issue?

**Comment by skabashnyuk** [comment]
@fErten you want to patch che master or 6.17?

**Comment by fErten** [comment]
@fErten 6.17 would be a better option for me
