### ISSUE TITLE
Create Jenkins pipeline to run E2E Happy path tests against che-theia repo

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14449]
### Is your enhancement related to a problem? Please describe.
There is [Jenkins job to run E2E Happy path tests as PR check on che-theia repository](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved), which is based on shell script and so it's hard to configure and hard to analyze build result.

### Describe the solution you'd like
Create Jenkins pipeline and put it into the che-theia repo.

### Related issue
#13326

**Comment by rhopp** [comment]
Blocked by https://issues.jboss.org/browse/CRW-425.
