### ISSUE TITLE
The default doc should be Che 7

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14446]
### Is your enhancement related to a problem? Please describe.

Currently when accessing https://www.eclipse.org/che/docs/quick-start.html we get redirected to https://www.eclipse.org/che/docs/che-6/quick-start.html

As a consequence clicking `Local Install` from the [Che website](https://www.eclipse.org/che/) [redirects to the Che 6](https://github.com/eclipse/che-website/blob/1f144887359984ef638ee4274cb07310af552564/che/index.php#L33). 

### Describe the solution you'd like

Users should be redirected to the Che 7 documentation instead: https://www.eclipse.org/che/docs/che-7/quick-start.html

### Describe alternatives you've considered

An alternative would be to remove the Che 6 doc that contains deprecated instructions (i.e. the Che 6 QuickStart, as described in the doc, doesn't work currently).

**Comment by l0rd** [comment]
@rkratky @themr0c @slemeur that's critical. We should not have new users pointed to Che 6 docs today.

**Comment by themr0c** [comment]
@l0rd I don't know if I have the power to change something. Currently investigating.

**Comment by rkratky** [comment]
@l0rd I believe I can fix this. Will work on this now.

**Comment by themr0c** [comment]
fixed by https://github.com/eclipse/che-docs/pull/811

**Comment by l0rd** [comment]
I have verified on the website and the problem has been fixed. Thanks @rkratky and @themr0c.
