### ISSUE TITLE
[Doc] Be specific about preferred / supported browsers.

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14440]
Hi, I have read that Chrome / Chromium based browsers are preferred to access the dashboard. We should probably be specific about this in the documentation.

* What wording would be the most relevant: could we create categories like: preferred browser / supported browser / untested browser?
* Once we have these categories, could we rate some browser according to the categories?

**Comment by ibuziuk** [comment]
not only dashboard, but theia-ide also
Need some input from IDE 2 team

**Comment by ibuziuk** [comment]
@themr0c could you search and link all the known browser specific issue ? e.g. https://github.com/eclipse/che/issues/14015

**Comment by themr0c** [comment]
che.openshift.io does not start on Safari Version 12.0 (14606.1.36.1.9) #11817

**Comment by themr0c** [comment]
so only one issue about safari, #14015 is covering firefox issues, no issues about vivaldi or internet explorer.

What browsers are tested? (How are they tested?)

**Comment by ibuziuk** [comment]
@rhopp any input on that, AFAIK latest Chrome is the only browser we support (there is no browser compatibility table right)?

**Comment by boczkowska** [comment]
For now, only Google Chrome was confirmed as a supported browser. We added a note about it where appropriate. Feel free to re-open the issue in the future if something changes.
