### ISSUE TITLE
Che operator needlessly restarts the server after updating the devfile registry image

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#14450]
### Is your enhancement related to a problem? Please describe.
Updating the image of a devfile or plugin registry doesn't affect the che server (apart from it seeing different plugins and devfiles). When the devfile or plugin registry is updated, the che server shouldn't have to.

### Describe the solution you'd like
Che deployment shouldn't be restarted after updating the image of devfile or plugin registry.

**Comment by sleshchenko** [comment]
@metlos Could you describe how did you change plugin/devfile registry image? Is it via Che Cluster CR?
After when writing a question, paid attention to area/operator label, so the answer is yes )
Please add a mentioning of Che Cluster/Operator CR in the issue description.
