### ISSUE TITLE
Improvement for building the che-theia docker image

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14452]
## Summary
Every time when we build a the che-theia docker image we are downloaded a lod of npm dependencies. I try to understand how it can be cashed as a docker layer. The first idea was to use the last archived relize as an archive package. Unpack it and install dependencies.  And use it as a cashed layer before the next release.

Something like this:
```
# Define the last upstream version of Theia to use
ARG THEIA_VERSION=0.9.0

RUN wget https://github.com/theia-ide/theia/archive/v${THEIA_VERSION}.zip && \
    unzip v${THEIA_VERSION}.zip && mv ./theia-${THEIA_VERSION} theia && yarn --cwd theia

```
(we could use this layer until the next  release version)

Then - git init. Create the needed patch to the needed upstream point and apply it.

Then rebuild.

WDYT?

**Comment by sr229** [comment]
The problem is its hard to version a moving target like this as a tarball. Theia pulls quite a chonk of packages so its best that we should raise it to Theia to allow their bundles to be packaged in a way to allow this.
