### ISSUE TITLE
chectl workspace:start --devfile=devfile.yaml not working

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14457]
From chectl created by [ye1984](https://github.com/ye1984): che-incubator/chectl#126  

Hello,

An error is occured when I run this command  `chectl workspace:start --devfile=devfile.yaml`

> Error: workspace:start command is expecting a devfile or workspace configuration 
 ›   parameter.

And the source (start.ts):
`if (!flags.devfile && !flags.workspaceconfig) {
      this.error('workspace:start command is expecting a devfile or workspace configuration parameter.')
    }`

I don't understand why the workspace config is necessary ?

Stack: `chectl/0.0.2-254bc44 darwin-x64 node-v10.15.3`

**Comment by benoitf** [comment]
Hello,
it's either the devfile or the workspace config that is mandatory, not the both


```
./bin/run workspace:start --devfile=/tmp/foo
  ✔ Retrieving Che Server URL...http://che-che.192.168.99.125.nip.io
  ✔ Verify if Che server is running
  ✔ Create workspace from Devfile /tmp/foo
```

**Comment by ibuziuk** [comment]
@ye1984 please,  let us know if you are still facing the issue with chectl devfile on Che7
