### ISSUE TITLE
Improve devfile:generate command

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14460]
From chectl created by [l0rd](https://github.com/l0rd): che-incubator/chectl#100  

- [ ] Support config maps
- [ ] Better input sanity check: verify that a plugin provided as a parameter has a valid format
- [ ] Find a better way to generate src/api/devfile.ts (currently done via quicktype.io)
- [ ] complete devfile/generate.test.ts
  - [ ] make `nock` work
  - [ ] parse yaml output and verifies, for each kind, the number of items and the fields that should exist and those that should not.
- [ ] Add an e2e test:
   ```bash
   kubectl create namespace prod
   kubens prod
   kubectl apply -f https://raw.githubusercontent.com/sleshchenko/NodeJS-Sample-App/dockerCon/deploy_k8s.yaml
   chectl devfile:generate \
           --selector="app.kubernetes.io/name=employee-manager" \
           --language=typescript \
           --git-repo='https://github.com/sleshchenko/NodeJS-Sample-App.git'
  kubectl delete services --all -n prod
  kubectl delete deployment --all -n prod
  ```
- [ ] Support specifying multiple selectors (e.g. `--selector="name=springboot" --selector="name=mysql"`)
- [ ] Support specifying multiple languages (e.g. `--language=java --language=go`)
- [ ] Support specifying multiple plugins
- [ ] Support `--file` as an alternative to `--namespace` as a source for k8s resources

**Comment by benoitf** [comment]
@l0rd I think it makes sense to support generating a devfile from a file as well. For example, for this Demo project https://github.com/sleshchenko/NodeJS-Sample-App it would look like the following
```
chectl devfile:generate \
        --file=deploy_k8s.yaml
        --language=typescript \
        --git-repo='https://github.com/sleshchenko/NodeJS-Sample-App.git'
```
And then generated Devfile may reference this file instead of inlining content.
WDYT?

**Comment by benoitf** [comment]
Good idea @sleshchenko I have updated the description

**Comment by l0rd** [comment]
@benoitf @sleshchenko looks like a good idea indeed
