### ISSUE TITLE
How to create and register a custom viewpart in Che workspace?

### ISSUE THREAD

**Issue by IcyLemon** [eclipse-che/che#1446]
Hi,
I want to create my own viewpart and show it in Che workspace, In desktop eclipse, this can be done through writing a subclass of ViewPart and defining related extension point, but how can I do it in Che?
Thanks.

**Comment by ghost** [comment]
@IcyLemon can you perhaps ask a more specific question or attach a screenshot of what you are trying to achieve?

Meanwhile you may check out docs here - https://eclipse-che.readme.io/v4.3/docs/introduction-1

**Comment by ddementieva** [comment]
@IcyLemon, any update? Can you elaborate a bit on what you are trying to do - an engineer will help you.

**Comment by TylerJewell** [comment]
@IcyLemon - closing the issue as we have published a new plugin development resource center in the docs with long tutorials on how to build extensions and customize the UI.
