### ISSUE TITLE
Remove option for different install types on minishift

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14467]
From chectl created by [tsmaeder](https://github.com/tsmaeder): che-incubator/chectl#60  

There is a parameter to use different ways to install che when using "chectl server:start" (operator, helm and something more I forget).

I don't see a reason to have more than one option there. My proposal is to always use the same method to install che.

**Comment by benoitf** [comment]
A user can already avoid to specify the installer (you can `chectl server:start --platform minishift` for instance) so I am not sure I understand your request. I am assuming that you are suggesting to always use the same installer for an easier maintenance but that's not possible yet. Let me try to explain why I think so.

Currently the installer option accepts the values `helm`, `operator` and `minishift-addon`. If I understand correctly you are suggesting to remove option `--installer` and always use the same installer. 

We could for instance always use the `operator` installer. But it doesn't support single user Che and it's the best option for local development.

We could use always use `helm`. But it doesn't support OpenShift.

As a consequence if we want to support both OpenShift and single user Che we can't always use the same installer (yet). That may change when if the Che operator will support single user Che.

**Comment by benoitf** [comment]
I see, so we need multiple implementations of the installer. But which installer to use is not something the user wants to decide. If the best installer to use is determined by other factors (OpenShift or Kubernetes, single- or multi-user), it should be inferred from those other parameters. We're just giving the user an opportunity to screw up (by specifying operator with single user, for example)

**Comment by ibuziuk** [comment]
@tsmaeder any comment on that one ?

**Comment by tsmaeder** [comment]
I still don't think we need multiple versions of the installer, or at least not different technologies.
