### ISSUE TITLE
Deploying custom devfile registry doesn't produce ingress resource

### ISSUE THREAD

**Issue by tomcec** [eclipse-che/che#14487]
hi, I have question regarding custom devfile registry.
When I follow documentation (https://www.eclipse.org/che/docs/che-7/customizing-registries.html#deploying-registries-in-kubernetes_deploying-the-registries) and deploy registry, I don’t see ingress resource created. According to documentation, there should be 3 resources created (pod, service, ingress):
$ kubectl get -o custom-columns=TYPE:.kind,NAME:.metadata.name \
  -l app=che-plugin-registry pod,svc,ingress
TYPE      NAME
Pod       che-plugin-registry-5c7cd8d5c9-zlqlz
Service   che-plugin-registry
Ingress   che-plugin-registry

But I see only Pod and Service created, without Ingress:
# kubectl get -o custom-columns=TYPE:.kind,NAME:.metadata.name -l app=che-devfile-registry pod,svc,ingress  --all-namespaces
TYPE      NAME
Pod       che-devfile-registry-67b7b75fbf-jskvk
Service   che-devfile-registry

Checking Ingress URL, returns only string “URL”:
kubectl get -o 'custom-columns=URL:.spec.rules[0].host'  -l app=che-devfile-registry ingress 
URL

When I update ConfigMap to point to new registry, che will not start:
❯ Devfile registry pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Plugin registry pod bootstrap
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:107:62)

I suppose there’s missing sth with Ingress. When I reinstall ingress, it doesn’t help.

**Comment by ibuziuk** [comment]
@themr0c @rkratky do you happen to know who is the author of the dedicated doc? Could you please check if the instructions are correct?

**Comment by themr0c** [comment]
I am afraid I did the gdocs to asciidoc conversion during the last week of GA rush without testing the documentation itself.

**Comment by tomascechatbroadcomcom** [comment]
Hi, can you advise what else needs to be done or what I am missing to have custom devfile registry working?
Thank you.

**Comment by tomascechatbroadcomcom** [comment]
issue fixed and can be closed. I pass the devfile registry as argument when starting che and that works fine.
