### ISSUE TITLE
Create workspace page loads its bottom, not start

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#14485]
### Describe the bug
When accessing `create-workspace` page, the bottom of a page is viewed instead of top. It can lead user to miss the opportunity to set the name of a workspace, because he/she needs to accidentally scroll up to find out that there is an input for workspace name.
If the content fits to the page, user will not have a problem, but as RH-Che adds `EPHEMERAL MODE` toggle, there is higher possibility that the input for setting workspace name will be hidden.

### Che version
7.2.0-SNAPSHOT

### Steps to reproduce

1. If you have high resolution, make your browser window smaller to see the behaviour when all content doesn't fit to the page.
2. Click on `Create Workspace`
3. See that the bottom of page is shown.

### Expected behavior
The top of a page should be shown.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
What it does:
 ![Screenshot from 2019-09-09 12-53-10](https://user-images.githubusercontent.com/29278800/64525322-db0c7c00-d300-11e9-9cfa-d7976cf463b9.png)

What it should do:
![Screenshot from 2019-09-09 12-53-24](https://user-images.githubusercontent.com/29278800/64525324-df389980-d300-11e9-9e51-79524e2e3a7b.png)

Rh-Che problem:
![Screenshot from 2019-09-09 12-55-42](https://user-images.githubusercontent.com/29278800/64525455-33437e00-d301-11e9-9430-97c3a1994418.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
It should be fixed by https://github.com/eclipse/che/pull/15818#issuecomment-579139933.
Feel free to reopen if you face the same issue
