### ISSUE TITLE
CHe Plugin Registry master is broken due to missing category in asciidoctor extension

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#14483]
### Describe the bug
master broken!!!

https://circleci.com/gh/eclipse/che-plugin-registry/657

```
Checking plugin 'joaompinto/vscode-asciidoctor/2.7.6'
	u'category' is a required property
Checking plugin 'joaompinto/vscode-asciidoctor/latest'
	u'category' is a required property
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
PR is merged - https://github.com/eclipse/che-plugin-registry/pull/220
build is green - https://ci.centos.org/job/devtools-che-plugin-registry-build-master/
Thanks @apupier Closing as Fixed
