### ISSUE TITLE
[chectl] support branding/productization via alternate default image names/tags

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14489]
### Is your enhancement related to a problem? Please describe.

The che-operator repo is used for both Che and CRW operator code, but it has the ability to set different defaults depending on the cheFlavour = che or codeready.

For chectl, a similar ability would be super handy to support branding/productization.

### Describe the solution you'd like

Here's how branding support is implemented in che-operator:

https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults.go#L33-L34
https://github.com/eclipse/che-operator/blob/master/pkg/apis/org/v1/che_types.go#L40-L41
then
https://github.com/eclipse/che-operator/blob/master/pkg/controller/che/che_controller.go#L273-L275
etc.

Could we do something similar in chectl? 

Would it be possible to use this cheFlavor to also disable some features of chectl, eg., support for kubernetes deployment (CRW only supports OpenShift deployment) ?

### Describe alternatives you've considered

I could also provide a **downstream** deploy.sh + cr.yaml which overrides all the chectl defaults and sets the correct context for deployment (openshift only).

**Comment by benoitf** [comment]
to me hat is in che-operator repository is not called branding but hardcoded values no ?

I mean, branding is when you can add new flavours easily, not changing a toggle.

**Comment by ibuziuk** [comment]
@davidfestal could you please take a look and comment?

**Comment by nickboldt** [comment]
In theory one could add a new flavour, but yes, in practice, we support 2 flavours only. 

So my alternative idea in https://issues.jboss.org/browse/CRW-369 might end up being better ... rather than hardcode defaults UPstream, we hardcode defaults DOWNstream and provide a shell script wrapper that does `chectl server:start -a operator -p openshift -n workspaces \
  --che-operator-cr-yaml=custom-resource.yaml --che-operator-image=registry.redhat.io/codeready-workspaces/operator-rhel8:2.0`

**Comment by benoitf** [comment]
@nickboldt yes, upstream should be as configurable as possible (allowing flavours easily) but it's downstream as you said that need to configure it.

all available options = upstream, pre-configured/one flavor = downstream

**Comment by ibuziuk** [comment]
@nickboldt so, can we close this issue e.g. downstream values will be harcoded ?

**Comment by nickboldt** [comment]
Dupe of https://github.com/eclipse/che/issues/14963
