### ISSUE TITLE
versions 7.0.0 and 7.1.0  needed on https://projects.eclipse.org/projects/ecd.che 

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14482]
versions 7.0.0 and 7.1.0 should probably be added to the list of latest releases on that page: https://projects.eclipse.org/projects/ecd.che

**Comment by sunix** [comment]
Maybe a bot should update that page automatically ?

**Comment by ibuziuk** [comment]
@sunix do you happen to know how this page is updated and who owns it atm ?

**Comment by gorkem** [comment]
I have added `7.0.0`. Normally, we should schedule a formal release review for the project.
