### ISSUE TITLE
Single host mode: error starting workspace

### ISSUE THREAD

**Issue by leader-us** [eclipse-che/che#14496]
## Che version 

7.0 And 7.2 snapshot (using latest che-server image)

## Steps to reproduce

- install with helm
- create workspace and project

## Expected behavior

should see IDE

## Runtime

kubernetes (include output of kubectl version)
```
[root@k8s_lab ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

## Installation method
helm install using single-host mode

## Environment
Windows + VMWare VM

## Additional context

helm install che 7.0 in notebook in wmare workstation VM on windows 10

```
global:
  multiuser: true
  ingressDomain: mychedomain
  serverStrategy: single-host
```
  
workspace started successful 

```
[root@k8s_lab che]# kubectl get pods --all-namespaces
NAMESPACE       NAME                                                       READY   STATUS    RESTARTS   AGE
che-workspace   workspace5km0dnswcmkbo85i.che-jwtproxy-689c4fd7b8-gqlbf    1/1     Running   0          3d15h
che-workspace   workspace5km0dnswcmkbo85i.maven-74c5c7d78c-qt9tf           4/4     Running   0          3d15h
default         che-545f75d787-8v5bm                                       1/1     Running   0          3d16h
default         devfile-registry-5dd598f5b-ccn2h                           1/1     Running   0          3d16h
default         keycloak-75697bcf67-r6z95                                  1/1     Running   0          3d16h
default         myingress-nginx-ingress-controller-84bd985c9d-n7mvn        1/1     Running   0          6d14h
default         myingress-nginx-ingress-default-backend-5d8fdb67ff-zm2pw   1/1     Running   2          12d
default         plugin-registry-77bd486f58-7vjlx                           1/1     Running   0          3d16h
default         postgres-6cd55dcd98-cd26s                                  1/1     Running   0          3d16h
kube-system     calico-kube-controllers-8578c8767f-45klr                   1/1     Running   2          17d
kube-system     calico-node-6sz6k                                          1/1     Running   2          17d
kube-system     coredns-855ddf9dd4-zh4w5                                   1/1     Running   0          4d23h
kube-system     tiller-deploy-5cd86d8fcd-vzt4n                             1/1     Running   2          17d
```

ingress also ready 

```
[root@k8s_lab che]#  kubectl get ingress --all-namespaces
NAMESPACE       NAME               HOSTS                                  ADDRESS   PORTS   AGE
che-workspace   ingress4lk9vy3a    mychedomain                                      80      3d15h
che-workspace   ingress5pktpa1j    mychedomain                                      80      3d15h
che-workspace   ingressckahk4fo    mychedomain                                      80      3d15h
che-workspace   ingresspdmmks94    mychedomain                                      80      3d15h
che-workspace   ingressto3g3nvb    mychedomain                                      80      3d15h
che-workspace   ingressxxsm05n8    mychedomain                                      80      3d15h
default         che-ingress        mychedomain                                      80      3d16h
default         devfile-registry   devfile-registry-default.mychedomain             80      3d16h
default         keycloak-ingress   mychedomain                                      80      3d16h
default         plugin-registry    plugin-registry-default.mychedomain              80      3d16h
```

workspace  related server also ok 

![1](https://user-images.githubusercontent.com/5953348/64577756-ed91be80-d3af-11e9-95ae-9cac3839f4a2.png)

but browser show error:

```
Error: Workspace doesn't have a server which matches with URL: http://mychedomain/?uid=568464
```

![2](https://user-images.githubusercontent.com/5953348/64577834-26ca2e80-d3b0-11e9-9966-d28e8317a8db.PNG)

**Comment by skabashnyuk** [comment]
@leader-us thank you for this report. Can you please provide some additional context.



### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by leader-us** [comment]
related with issue  https://github.com/eclipse/che/issues/14324    which is multi-host

**Comment by skabashnyuk** [comment]
@leader-us ok.
Could you please next time use the original template of the bug report. Thanks.

**Comment by leader-us** [comment]
Describe the bug
Che version  7.0 And 7.2 snapshot (using latest che-server image)
Steps to reproduce 
  install with helm 
  create workspace and project
Expected behavior
 should see IDE
Runtime
  kubernetes (include output of kubectl version)
[root@k8s_lab ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Screenshots
Installation method
   helm install  using single-host mode
Environment
 Windows + VMWare VM
Additional context
  I tried 7.0 and latest version ,but single host mode can't successful launched
browser show error:

Error: Workspace doesn't have a server which matches with URL: http://mychedomain/?uid=568464

**Comment by l0rd** [comment]
@leader-us are you deploying Kubernetes in a public cloud (AWS, GCP, Azure), locally on your machine, on prem? And what kind of [ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) are you using? 

@skabashnyuk @metlos this is supposed to work on 7.2-SNAPASHOT right?

**Comment by leader-us** [comment]
> @leader-us are you deploying Kubernetes in a public cloud (AWS, GCP, Azure), locally on your machine, on prem? And what kind of [ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) are you using?
> 
> @skabashnyuk @metlos this is supposed to work on 7.2-SNAPASHOT right?

Deployed on my local machine  ,ingress controller is nginx   and mutli-host mode works but single-host mode can't work

**Comment by metlos** [comment]
This should work also with single-host mode on master newer than https://github.com/eclipse/che/commit/154d668505cc86763f16ad8868e0a1fcf4bccc28. Since the original report was done yesterday and the commit was also done yesterday, I suppose the nightly image from yesterday didn't yet contain the support for single-host mode.

@leader-us how did you build the che server images or where did you obtain the 7.2-SNAPSHOT version from?

**Comment by leader-us** [comment]
> This should work also with single-host mode on master newer than [154d668](https://github.com/eclipse/che/commit/154d668505cc86763f16ad8868e0a1fcf4bccc28). Since the original report was done yesterday and the commit was also done yesterday, I suppose the nightly image from yesterday didn't yet contain the support for single-host mode.
> 
> @leader-us how did you build the che server images or where did you obtain the 7.2-SNAPSHOT version from?

from https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm    
and I found a little mistake spell in   values.yaml   :
  heImage: eclipse/che-server:nigthly -->nightly   .

**Comment by skabashnyuk** [comment]
@leader-us FYI https://github.com/eclipse/che/pull/14396

**Comment by metlos** [comment]
@leader-us ok, so you just ran the helm chart, which would mean you were getting the nightly image. So I suppose it was the case that you tried it before the fix for single-host mode made it into the image.

Make sure the `cheImagePullPolicy` is set to `Always` in your installed che chart and try issuing:
```
kubectl rollout restart deployment/che -n <NAMESPACE_WHERE_CHE_IS_INSTALLED>
```

**Comment by metlos** [comment]
Also, if you're seeing the spelling mistake in the che image, you might not be on the latest version. Please make sure your checkout is up-to-date with the master.

**Comment by leader-us** [comment]
Thanks for help . I tried pull latest nightly image and restarted che-server pod. and now single host mode successfully started 
![4](https://user-images.githubusercontent.com/5953348/64704008-20d36b00-d4e0-11e9-9eda-40bfdef7057e.PNG)

but there are some error msg in browser .
![5](https://user-images.githubusercontent.com/5953348/64704145-6132e900-d4e0-11e9-8bbd-99102426e574.PNG)

**Comment by metlos** [comment]
I can't comment on the errors in the console. @sunix, could you?
