### ISSUE TITLE
Add note about "Multiple workspaces fail to run at the same time" in the "How the Che server uses PVCs and PVs for storage" section

### ISSUE THREAD

**Issue by supriya-bharadwaj** [eclipse-che/che#14495]
### Is your enhancement related to a problem? Please describe.

A user can run multiple workspaces simultaneously only if a couple of conditions are met.

### Describe the solution you'd like

Add an admonition about steps to take to run multiple workspaces in the section at https://www.eclipse.org/che/docs/che-6/kubernetes-admin-guide.html#how-the-che-server-uses-PVCs-and-PVs-for-storage.

**Comment by l0rd** [comment]
@supriya-bharadwaj what about Che 7?

**Comment by supriya-bharadwaj** [comment]
Hi, @l0rd . I looked through the existing structure and could not find a place for this admonition. After they are ready, maybe, in one of the following sections: Admin guide > Installing Che on different Kubernetes distributions or Admin guide > Advanced configuration options > Configuring Che Persistent Volumes strategy (https://hackmd.io/c0nqIQK2Rki1u95h9h1X1Q?)

**Comment by l0rd** [comment]
`Admin guide > Advanced configuration options > Configuring Che Persistent Volumes strategy` looks like the good place to add that. Thanks @supriya-bharadwaj
