### ISSUE TITLE
chectl-win` cannot find `minishift.exe` even if its location added to `PATH` environment variable

### ISSUE THREAD

**Issue by dgolovin** [eclipse-che/che#14503]
### Describe the bug
`chectl-win` cannot find `minishift.exe` even if its location added to `PATH` environment variable. 

### Che version
7.1

### Steps to reproduce
```
>where minishift
C:\Users\u1\bin\minishift.exe
C:\Users\u1\bin\minishift-1.34.1-windows-amd64\minishift.exe

> minishift version
minishift v1.34.1+c2ff9cb

>oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO
Server https://192.168.83.30:8443
kubernetes v1.11.0+d4cacc0

> chectl-win server:start --platform minishift --domain=httpd-ex-myproject.192.168.83.30.nip.io
  > ✈️  Minishift preflight checklist
    √ Verify if oc is installed...done.
    × Verify if minishift is installed
      → E_REQUISITE_NOT_FOUND
      Verify if minishift is running
      Retrieving minishift IP and domain for routes URLs
 »   Error: E_REQUISITE_NOT_FOUND
```
### Expected behavior
minishift 

### Runtime
   - minishift (include output of `minishift version` and `oc version`)

### Screenshots
N/A

### Installation method
   - [ ] chectl 

### Environment
   - my computer 
       - Windows

### Additional context
I am installing che following https://www.eclipse.org/che/docs/che-7/che-quick-starts.html#running-che-locally_che-quick-starts

**Comment by l0rd** [comment]
@dgolovin I am afraid that the chectl-win download link in the doc is outdated and you have 6 months old chectl. Can you please provide the output of `chectl version`? 

And you may want to follow the installations instructions that are [here](https://github.com/che-incubator/chectl/#installation)

**Comment by themr0c** [comment]
https://www.eclipse.org/che/docs/che-7/che-quick-starts.html is an outdated version of the documentation that should be replaced by redirection to the current https://www.eclipse.org/che/docs/che-7/che-quick-starts/ -- For some reason old files are not removed when the documentation is published.

The updated version of chectl installation is there:
https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/

**Comment by themr0c** [comment]
@dgolovin can you please check that following the updated version of the documentation your problem is solved: https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/#installing-the-chectl-management-tool-on-windows_installing-the-chectl-management-tool
 
@l0rd @rkratky what is the plan for the old documentation files that are still published: make sure proper redirection exist,  or simply delete them?

**Comment by l0rd** [comment]
@themr0c thanks for taking care of this! The documentation is outdated and we need to remove it in any case. Do we need to redirect requests to the old page or not? It depends where this page was linked. @dgolovin where have you found the link to that page?

**Comment by dgolovin** [comment]
@themr0c same problem with new documentation. When running from powershell
```
PS C:\ProgramData\chectl> chectl server:start -p minishift
  > ✈️  Minishift preflight checklist
    × Verify if oc is installed
      → E_REQUISITE_NOT_FOUND
      Verify if minishift is installed
      Verify if minishift is running
 »   Error: E_REQUISITE_NOT_FOUND

PS C:\ProgramData> (get-command minishift.exe).Path
C:\Users\dgoo\bin\minishift.exe
```

Then I tried again in new `cmd` session and it got past minishift check
```
C:\Users\dgolo>where minishift
C:\Users\dgolo\bin\minishift.exe
C:\Users\dgolo\bin\minishift-1.34.1-windows-amd64\minishift.exe

C:\Users\dgolo> chectl server:start -p minishift
  √ ✈️  Minishift preflight checklist
    √ Verify if oc is installed...done.
    √ Verify if minishift is installed...done.
    √ Verify if minishift is running...done.
  > 🏃‍  Running the Che minishift-addon
    √ Check minishift version...done.
    - Check logged
      Copying addon resources
      Check che addon is available
      Apply Che addon

C:\ProgramData\chectl\chectl\lib\installers\minishift-addon.js:168
                throw err;
                ^
Error: ENOENT: no such file or directory, lstat 'C:\Users\dgolo\templates\minishift-addon'

C:\Users\dgolo>chectl version
chectl/0.0.20190909-next.3ab07dc win32-x64 node-v10.16.3
```

**Comment by dgolovin** [comment]
@l0rd I searched for 'che 7.1' in google and hit first link.
