### ISSUE TITLE
doc: admin guide is missing how to change some che-server values like che workspace/pod startup timeout.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#14509]
### Is your enhancement related to a problem? Please describe.
I have been through this same issue https://github.com/eclipse/che/issues/13597 and I have not been able to find a way in increase the timeout value of pod/workspace startup.
Looking at the documentation I have found anything.

### Describe the solution you'd like
Admin guide should tell the user how to setup these value for the different installation flavor (operator, helm, ocp4, etc ...)

### Describe alternatives you've considered
We may also increase the timeout value by default. Seems like 2 minutes is too short!

**Comment by themr0c** [comment]
Probably this will be addressed by the Installation Guide which need to be written https://github.com/eclipse/che/issues/14362?
