### ISSUE TITLE
Allow to use PNG icons in plugin registry

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14502]
### Is your enhancement related to a problem? Please describe.

Now in the plugin registry when describing a plugin metadata we cannot use PNG image format. But this format is most commonly used in VS Code extensions. Just download any .vsix extension file, unpack in and open `package.json`. Icon field will point on PNG.

Now the icon `https://www.eclipse.org/che/images/logo-eclipseche.svg` is used for each plugin. On the UI it looks, to be honest, not pretty good

![Screenshot from 2019-09-10 15-57-47](https://user-images.githubusercontent.com/1655894/64621717-74fa2480-d3e6-11e9-9c5f-a3b40b117c0c.png)

### Describe the solution you'd like

Allow to use PNG for the plugin icons.

![64438384-add98700-d0d0-11e9-8a5f-22c6b7714477](https://user-images.githubusercontent.com/1655894/64620543-585ced00-d3e4-11e9-99a7-8763257ebf05.png)

**Comment by skabashnyuk** [comment]
AFAIK svg was requested by authors of plugin-viewer application.
CC @l0rd @slemeur

**Comment by l0rd** [comment]
@skabashnyuk I don't see any issue with that

**Comment by l0rd** [comment]
cc @amisevsk @ibuziuk

**Comment by amisevsk** [comment]
If the plugin viewer supports it, disabling the `.svg` check is a one-line fix on the plugin registry.

**Comment by vitaliy-guliy** [comment]
Is plugin-viewer application alive?
Where can I see/test it?

**Comment by amisevsk** [comment]
I was assuming the plugin viewer refers to the plugins sidebar in theia (`ctrl`+`shift`+`j`)

**Comment by skabashnyuk** [comment]
>plugin viewer 

It is a separate app https://github.com/eclipse/che-plugin-registry/pull/72

**Comment by vitaliy-guliy** [comment]
> It is a separate app [eclipse/che-plugin-registry#72](https://github.com/eclipse/che-plugin-registry/pull/72)

It looks it has been moved here https://github.com/che-incubator/che-plugin-viewer/pull/1/files
But there is more than 7 month of inactivity.

**Comment by amisevsk** [comment]
Is there any verdict on this issue? Can we support `png` icons?

**Comment by vitaliy-guliy** [comment]
Now it's possible to use any URI referencing an image
