### ISSUE TITLE
Quarkus support

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14506]
## Goals
The goal of this epic is to integrate Quarkus tooling into Eclipse Che.

We should be providing:
- A default devfile for a Quarkus stack with a sample.
- The VSCode extension https://github.com/redhat-developer/vscode-quarkus

## Linked resources
We have a quarkus devfile which has been built here:
https://github.com/sunix/che-quarkus-demo

## Sub-tasks
- Add the vscode-quarkus extension to Che - https://github.com/eclipse/che/issues/15118

**Comment by nickboldt** [comment]
This affects downstream issue https://issues.jboss.org/browse/CRW-329 ... see also https://developers.redhat.com/blog/2019/09/23/how-the-new-quarkus-extension-for-visual-studio-code-improves-the-development-experience/

**Comment by nickboldt** [comment]
@slemeur is this still a requirement for productization? pushing it down to P2 seems like no.

**Comment by tsmaeder** [comment]
Since we need to add the plugin to the Java Plugin we have right now, we need to keep track of the increase in memory consumption: we still need to be able to run in the 3Gb restriction on openshift.io.

**Comment by slemeur** [comment]
Please add the new issues you've been creating as subtasks of the epic. so we can follow the work and issues that are connected to this epic.

**Comment by nickboldt** [comment]
Is there more to do here? Or can we close this one?
