### ISSUE TITLE
[Plugin Registry] [airgap] Each plugin should display proper icon

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14510]
### Is your enhancement related to a problem? Please describe.

On the plugin registry each plugin refers on the same default icon. When displaying them on the UI, it looks not pretty nice

![Screenshot from 2019-09-10 15-57-47](https://user-images.githubusercontent.com/1655894/64701483-25c8f800-d4a9-11e9-8c79-3407476fcdb5.png)

### Describe the solution you'd like

We can apply the proper icons for each plugin.
Most of the plugins are VS Code extensions. Most of them are opensource with repository on GitHub. Each extension has `package.json` contains `icon` field which refers on the image hosted on that repository. We can easily refers on that images.

In result we may have the following

![Screenshot from 2019-09-10 15-37-55](https://user-images.githubusercontent.com/1655894/64702523-003cee00-d4ab-11e9-9938-13e04b91e4e2.png)

![Screenshot from 2019-09-10 15-38-24](https://user-images.githubusercontent.com/1655894/64702533-03d07500-d4ab-11e9-9523-189af6ffdd4d.png)

**Comment by tolusha** [comment]
What about licensing?

**Comment by vitaliy-guliy** [comment]
Licensing of what?

**Comment by tolusha** [comment]
@vitaliy-guliy 
Are we going to store them somewhere?

**Comment by slemeur** [comment]
@vitaliy-guliy : I guess question from @tolusha is more about are we authorized to pull the images this way. I guess that if we are pulling from the repository it is fine.

Another aspect is how this would work if you are behind a proxy and can't reach github? Would it not be better to have that in the meta.yaml and directly in the plugin registry?

**Comment by nickboldt** [comment]
See also https://github.com/eclipse/che/issues/15581 re: icons in devfiles

**Comment by nickboldt** [comment]
> Another aspect is how this would work if you are behind a proxy and can't reach github? Would it not be better to have that in the meta.yaml and directly in the plugin registry?

Yes, icons should be cacheable inside the registry, just like .vsix files.

**Comment by sunix** [comment]
hello @vitaliy-guliy do you have any plans to implement that ?

**Comment by sunix** [comment]
Hello, first step, let's have the icons in the plugin registry like we do for devfile registry https://github.com/eclipse/che-devfile-registry/tree/master/images.
We will figure out later about a way to get that from the package.json.

**Comment by amisevsk** [comment]
The blocker issue for this is in how these images are retrieved; unless we want to ensure relative links are supported everywhere a plugin icon might be displayed, https://github.com/eclipse/che/issues/15091 needs to be resolved before we throw icons into the registry.

**Comment by vitaliy-guliy** [comment]
@sunix why not to point on the image on plugin repository on GitHub?
Something like this
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.9/meta.yaml#L9

For each plugin we specify its source repository, which almost always contains the plugin logo.

**Comment by sunix** [comment]
@vitaliy-guliy  ok what ever, as long as this is working :)

**Comment by ericwill** [comment]
This was fixed in 7.18 but was never closed.

**Comment by vitaliy-guliy** [comment]
Thanks
