### ISSUE TITLE
How to use code snippets with the Java Plug-in

### ISSUE THREAD

**Issue by wgbeckmann** [eclipse-che/che#14513]
Hi, I want to create my own code snippets for auto completion in Java.

In the VSCode Documentaition I can read:
`
Create your own snippets
You can easily define your own snippets without any extension. To create or edit your own snippets, select User Snippets under File > Preferences (Code > Preferences on macOS), and then select the language (by language identifier) for which the snippets should appear, or the New Global Snippets file option if they should appear for all languages. VS Code manages the creation and refreshing of the underlying snippets file(s) for you.
`
[https://code.visualstudio.com/docs/editor/userdefinedsnippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

But I cannot find a similar thing in Theia. How do I create code snippets?

Thanks!

**Comment by slemeur** [comment]
cc @tolusha and @tsmaeder : This is a question for you.
