### ISSUE TITLE
After updating Monaco Editor some Keybindings has collision for Java LS

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#14520]
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
* Create a  workspace based on Java Maven stack. Open HelloWorld.java class
* Set cursor in 6:18 position (on `.out`) and invoke `Ctrl+F12` shortcut
**Expected result:** The `Go to the definition` command should be invoked. The System class should be opened.
**Actual result:** Looks like instead of `Go to definition` command is invoked `Go to implementation` command 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![go-defenition-key-map](https://user-images.githubusercontent.com/1640058/64776202-6e8fb800-d560-11e9-8d20-a3b4e33e72cb.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
This problem can be depended on the Keybinding map, which has some duplicated Keybindings. See on screenshot. Also i supposed that this problem can be reproduced for other language servers because the KeyMap has other duplications.

**Comment by tsmaeder** [comment]
FWIW: I tried reproducing this but was not able to get che to work on minishift

**Comment by svor** [comment]
Default keybinding was changed, so for now:
- `ctrl+f12` - **Go to Implementation**
- `ctrl+f11` - **Go to Definition**
