### ISSUE TITLE
Unable to cleanup temporary workspace workspaceqe1y1ilmiup489gj

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14525]
### Describe the bug
Error on che server startup
```
Unable to cleanup temporary workspace workspaceqe1y1ilmiup489gj. Reason is 
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "workspace" violates foreign key constraint "che_fk_worker_workspace_id" on table "che_worker"
  Detail: Key (id)=(workspaceqe1y1ilmiup489gj) is still referenced from table "che_worker".
Error Code: 0
Call: DELETE FROM workspace WHERE (id = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery(WorkspaceImpl{id='workspaceqe1y1ilmiup489gj', namespace='cleberfx', name='test-wksp-bz5k', config=WorkspaceConfigImpl{id=39526617, name='test-wksp-bz5k', description='null', defaultEnv='default', commands=[CommandImpl{id=39526618, name='build', commandLine='mvn clean install -f ${current.project.path}', type='mvn', attributes={goal=Build, previewUrl=}}], projects=[], environments={default=EnvironmentImpl{id=39526619, recipe=RecipeImpl{type='openshift', contentType='application/x-yaml', content='kind: List

```
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: 7.1

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] other

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/14561
