### ISSUE TITLE
Potential inconsistency between 'che_workspace_activity' and 'che_k8s_runtime' for STOPPING / STARTING workspaces

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14536]
### Describe the bug
Related downstream issue - https://github.com/redhat-developer/rh-che/issues/1612
Basically there could be a situation when `che_workspace_activity` has "STOPPING" / "STARTING" status, but there actual status of the workspace is "status": "STOPPED" (I assume this means no entry in the 'che_k8s_runtime' table)

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

N/A

### Expected behavior
Consistency for workspace status between `che_workspace_activity` & `che_k8s_runtime`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] Hosted Che

**Comment by ibuziuk** [comment]
https://github.com/eclipse/che/issues/14536

**Comment by metlos** [comment]
Implemented in #14574
