### ISSUE TITLE
Dashboard docker build is broken

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14532]
### Describe the bug
Seems like Dashboard docker build is broken
![Screenshot_20190913_095639](https://user-images.githubusercontent.com/5887312/64843119-e9aea800-d60c-11e9-9556-13a3b4e14c56.png)

**Comment by olexii4** [comment]
@sleshchenko 
Very interesting.  I saw 'upgrade yarn@1.13.0'. 
Then 'Expected version "^1.13.0". Got "1.12.3" '
It is something with a cached layer.

Do you try to delete an old image and rebuild?

BTW I cannot reproduce it )

**Comment by olexii4** [comment]
I am going to update this Dockerfile soon.

Try this (without yarn upgrade):
```
FROM node:8.16.0

RUN apt-get update && \
    apt-get install -y git \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*
COPY package.json /dashboard/
COPY yarn.lock /dashboard/
COPY typings.json /dashboard/
WORKDIR /dashboard
RUN yarn install --ignore-optional
COPY . /dashboard/
RUN yarn build && yarn test
RUN cd /dashboard/target/ && tar zcf /tmp/dashboard.tar.gz dist/

CMD zcat /tmp/dashboard.tar.gz
```
