### ISSUE TITLE
chectl: k8s health check fails if logged in user does not have cluster admin rights

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14534]
### Describe the bug
chectl: k8s health check fails if logged in user does not have cluster admin rights
See more https://github.com/che-incubator/chectl/pull/257#discussion_r322772354

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start minishift.
2. Log in as developer.
3. Try to deploy Che with chectl and minishift addon as installer.

### Actual behavior
Chectl failed to check cluster status:
![Screenshot_20190910_135245](https://user-images.githubusercontent.com/5887312/64624567-8bf34380-d3f3-11e9-818c-d0904afa8c38.png)

### Expected behavior
Che is deployed.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl (minishift-addon as installer)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by rhopp** [comment]
I'm bit puzzled...
You are saying you encounter this problem, when installing on minishift as the default user `developer` using minishift-addon installer, yet the error message you have in the screenshot is (in the chectl source code) used only when stopping or deleting server (AFAIK).
So I've gone and tried ti by myself and indeed `chectl server:start` failed, but on something different -> `Get pods by selector "app=che" returned 3 pods (1 was expected)` (chectl expects the selector to return just one pod, instead it gets three (server+2 registries))

Could you tell me what I've been doing wrong to reproduce this issue?

**Comment by sleshchenko** [comment]
> So I've gone and tried ti by myself and indeed chectl server:start failed, but on something different -> Get pods by selector "app=che" returned 3 pods (1 was expected) (chectl expects the selector to return just one pod, instead it gets three (server+2 registries))

It's another issue I wanted to report but have not done it yet, will create it soon.

> Could you tell me what I've been doing wrong to reproduce this issue?

To easily reproduce this issue - please start from a scratch - remote existing Che namespace, log in as developer and try to deploy Che, for example with minishift-addon. There are other scenarios when you can face the same issue, but I think it's should be the simplest. Let me know if you still is not able to reproduce it.

**Comment by sleshchenko** [comment]
@rhopp here is a quick fix for the issue you faced https://github.com/che-incubator/chectl/pull/322

**Comment by sleshchenko** [comment]
@rhopp I reproduced this issue on the latest chectl from next channel.
And also registered an issue that I mentioned when chectl fails to start Che because of 2 pods while 1 is expected https://github.com/eclipse/che/issues/14595

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/pull/524/ merged
Error messages are improved.
