### ISSUE TITLE
chectl: error occurs when trying to install chectl from next channel

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14538]
### Describe the bug
Error occurs when trying to install chectl from next channel
![Screenshot_20190913_140543](https://user-images.githubusercontent.com/5887312/64858292-9ef25780-d62f-11e9-89c6-3a98597003fc.png)

### Steps to reproduce
Try to install next chectl with the command that is specified in README.md
`bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next`

Seems that updating stable version to next does not work but without any error message:
![Screenshot_20190913_140946](https://user-images.githubusercontent.com/5887312/64858512-4a9ba780-d630-11e9-9c7d-6dd77587f129.png)

### Expected behavior
next chectl is installed.

**Comment by benoitf** [comment]
fixed
