### ISSUE TITLE
Mismatched versions of JDK 11 between che-java11-maven:7.1.0 and che-remote-plugin-runner-java11:7.1.0; also for JDK 8

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14545]
### Describe the bug

https://quay.io/repository/eclipse/che-java11-maven?tab=tags

:7.1.0 and :nightly tags are all JDK 11.0.3

```
$➔ docker run -it  --entrypoint /bin/sh quay.io/eclipse/che-java11-maven:7.1.0 -c "java -version" | head -2

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+1-Debian-1bpo91)
```

But in the remote plugin runner:

https://hub.docker.com/r/eclipse/che-remote-plugin-runner-java11/tags?page=1&ordering=last_updated

:7.1.0, :next and :latest tags are all JDK 11.0.4

```
$➔ docker run -it  --entrypoint /bin/sh docker.io/eclipse/che-remote-plugin-runner-java11:7.1.0 -c "java -version" | head -2
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-alpine-r0)
```

The result is a mismatch between debugger and debuggee:

![image](https://user-images.githubusercontent.com/227597/64880888-5040bf80-d627-11e9-8089-5b47abc2283b.png)

### Che version

 - [x] latest
 - [x] nightly
 - [x] 7.1.0

### Steps to reproduce

1. User ran the command option “Debug”.

![image](https://user-images.githubusercontent.com/227597/64882638-8b44f200-d62b-11e9-9b59-70150b695fdb.png)

2. Select “Open Configurations” under “Debug”

![image](https://user-images.githubusercontent.com/227597/64882700-a7e12a00-d62b-11e9-9476-e2fa42271e80.png)

3. Select “Attach”

![image](https://user-images.githubusercontent.com/227597/64882717-b29bbf00-d62b-11e9-9501-c3454f6dbcd0.png)

4. Update port to 8000 where I define in the devfile command JDWP port 8000:

![image](https://user-images.githubusercontent.com/227597/64882763-ca734300-d62b-11e9-90aa-99e909b0672d.png)

5. Select “Start Debugging” under “debug”

![image](https://user-images.githubusercontent.com/227597/64882789-d3641480-d62b-11e9-8b1e-7a60d36a74be.png)

6. It will take a while to attach the JVM

7. Then, the debug console will complain about the mismatching versions.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`) 3.11
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by nickboldt** [comment]
Aside: 

I found the source for https://hub.docker.com/r/eclipse/che-remote-plugin-runner-java11 -> https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-java11/Dockerfile

but I can't find the source for https://quay.io/repository/eclipse/che-java11-maven ... where is it?

**Comment by rhopp** [comment]
Not sure who should take a look at this one? Maybe your team, @skabashnyuk?

**Comment by nickboldt** [comment]
User also tried to enable debugger using che-java8-maven:7.1.0 and che-remote-plugin-runner-java8:7.1.0 and got a similar mismatch result:

![image](https://user-images.githubusercontent.com/227597/64891585-52634800-d640-11e9-8bd4-e85d06a81406.png)
