### ISSUE TITLE
Devfile editor does not persist some fields

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#14542]
When I modify a devfile on Dashboard for a workspace and add ` registryUrl:` to a chePlugin the value is not persisted and the value is not used when I start the workspace again. 

Step. 
1. create a workspace 
2. stop the workspace 
3. modify workspace and on devfile tab add  registryUrl: to a plugin
4. start the workspace and observe that the new registryUrl is in effect
5. stop the workspace 
6. start workspace and observe that it is back to the original default registry.

**Comment by sleshchenko** [comment]
Che Server seems to be that sneaky guy:
![Screenshot_20200326_151249](https://user-images.githubusercontent.com/5887312/77650604-69321200-6f74-11ea-8eca-ab44b65ff2b0.png)
![Screenshot_20200326_151300](https://user-images.githubusercontent.com/5887312/77650609-69caa880-6f74-11ea-8acb-893f0f75c620.png)
