### ISSUE TITLE
[Doc] documentation for "magic" `$(CHE_PROJECTS_ROOT)` environment variables ?

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#14549]
https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#environment mentions `$(CHE_PROJECTS_ROOT)` 

Where are these "magic" environment variables documented ?

**Comment by ibuziuk** [comment]
@themr0c will you be able to document this part cc: @rkratky

**Comment by themr0c** [comment]
I would assume these variables should get documented in the Installation Guide? WDYT @ibuziuk @benoitf

**Comment by ibuziuk** [comment]
> I would assume these variables should get documented in the Installation Guide
@themr0c how come ? `$(CHE_PROJECTS_ROOT)` is a devfile specific env var AFAIK

**Comment by ibuziuk** [comment]
@maxandersen actually, it is documented already ;-) Can we close the issue ?

> CHE_PROJECTS_ROOT: The location of the projects directory (note that if the component does not mount the sources, the projects will not be accessible).

https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#environment

**Comment by maxandersen** [comment]
I missed that - dammit :) All good then.
