### ISSUE TITLE
During che-server rollout update from  `6.x.x` -> `7.x.x` all running Che 6 workspaces should be stopped gracefully and not recovered

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14544]
### Is your task related to a problem? Please describe.
During che-server rollout update from Che 6 -> Che 7 all Running Che 6 workspaces should be stopped gracefully and not recovered in order to avoid any side-effect. Basically, it is not possible to start[1] old Che 6 workpaces in Che `7.0.0` and above. So, in case of updates between the major releases, it makes sense to gracefully stop all running Che 6 workspaces

### Describe the solution you'd like
During the rollout update from `6.x.x` -> `7.x.x` all Che 6 workspaces would be stopped gracefully

### Describe alternatives you've considered
Che Admin with `CHE_SYSTEM_SUPERPRIVILEGEDMODE` stops all the Che 6 workspaces manually  or executes prepare to shut down request that explicitly stops all running workspaces

[1] https://www.eclipse.org/che/docs/che-6/what-are-workspaces.html

**Comment by ibuziuk** [comment]
@nickboldt noteworthy case for CRW 1.2 -> 2.0 update

**Comment by ibuziuk** [comment]
@nickboldt @l0rd adding `need-triage` back since this issue is related to https://github.com/eclipse/che/issues/14865

**Comment by tsmaeder** [comment]
Sorry, but what do you want triage to do with this? I thought we killed the ide of stopping all workspaces?

**Comment by sleshchenko** [comment]
Seems this issue is outdated.
We agreed that Che Admin is not able to stop all users workspaces. 
It's OK to update without stopping workspaces and them users should stop their Che 6 workspaces, but they won't be able to start them again. UX you can take a look in this demo Che6.19.6 to Che7.0.0 update https://youtu.be/7Jqfxi8NvyU

cc @l0rd @davidfestal Can you confirm that we are not going to stop workspaces anymore?

**Comment by davidfestal** [comment]
Sure, *not stopping* the workspaces is the simplest and best upgrade solution.

**Comment by ibuziuk** [comment]
@sleshchenko thanks for an update with the recording - https://youtu.be/7Jqfxi8NvyU
The 6.x - > 7.x. update flow is clear now. Closing
