### ISSUE TITLE
[Doc] document devfile.yaml branch support

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#14546]
https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/ and others does not mention anything that I could see about the fact you can tell che to use a repo from a github branch.

Like: https://che.openshift.io/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che

That would be useful to let users know.

**Comment by ibuziuk** [comment]
@themr0c will you be able to document the use-case ? cc: @rkratky

**Comment by themr0c** [comment]
Oh that's nice indeed.

**Comment by MichalMaler** [comment]
Can take a look at it.
