### ISSUE TITLE
[Java] Delayed Resolution of Method Argument Name in Code Completion with Vertx Sample

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#14556]
### Describe the bug
When accessing suggestions in Java Vert.x example workspace with default settings and example project, the LS behaves inconsistently. When file is opened, LS starts to initialise. Once it is initialised, it shows `arg0` in suggestions instead of `id` [1]. After a while, `id` is shown in suggestion [2]. This issue seems to be not reproducible in Java Maven and Java Spring example workspaces. 

[1]
![Screenshot from 2019-09-16 08-13-17](https://user-images.githubusercontent.com/29278800/64937574-050ef280-d85b-11e9-8414-1dd674cda045.png)

[2]
![Screenshot from 2019-09-16 08-14-32](https://user-images.githubusercontent.com/29278800/64937582-093b1000-d85b-11e9-8d2a-cfa2b16ec826.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Create Java Vert.x workspace with default setting and with example project. Open file java-web-vertx/src/main/java/io/vertx/examples/spring/SpringExampleRunner.java. Wait until LS is initialized, then open suggestion on 20 line 11 col. Wait a while, open it again.

### Expected behavior
The `id` should be shown from the beginning.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

minikube version: v1.0.1
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by fbricon** [comment]
looks like it's because initially the sources are not available, so the arg names are just inferred from the bytecode. After a while, once the sources have been downloaded, the param names are available.

**Comment by tsmaeder** [comment]
So it seems this works as intended.
