### ISSUE TITLE
import/focus on one project from a url 

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#14550]
Quickstarts repos like `https://github.com/quarkusio/quarkus-quickstarts` have multiple sub projects and would be awesome to either:

A) have one devfile.yaml in root to define a shared workspace setup, but then be able to tell che to just import lets say `https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started` folder  - *without* having to use absolute folder names/urls.

B) allow referring to folder like `che.openshift.io/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che/getting-started` and have it locate *nearest* `devfile.yaml` rather than listen to `/devfile.yaml` in root directly.

Ultimately having the project explorer or similar "focused" on `getting-started` to avoid polluting the UI.

**Comment by skabashnyuk** [comment]
related to https://github.com/eclipse/che/issues/13671

**Comment by maxandersen** [comment]
#13671 seem to be about sparse checkout which is useful but separate feature IMO.

In this I'm talking about being able to checkout a github repo but then only import part of it and be able to focus on that.

Limiting import is more about saving resources in a limited cloud environment but also to avoid polluting the UI with potentially hundreds of other projects. When I use emacs, eclipse, vscode, intellij or any other desktop IDE I can think of I highly rely on being able to focus on a specific area.

That is useful not only when doing quickstart like projects for newbies, but also for normal development work of just focusing on one area - while still being able to navigate to other parts of the larger project.

**Comment by skabashnyuk** [comment]
>In this I'm talking about being able to checkout a github repo but then only import part of it and be able to focus on that.

Am I understand you correctly. You want to check out all soure code, but Theia should open only one subfolder?

**Comment by maxandersen** [comment]
Yes, or at least be able to "focus" on it. 
Two different usecases with slightly different wanted behaviors:

1. A quickstart repo like https://github.com/quarkusio/quarkus-quickstarts/ you would be ok just doing a spare checkout and focus on lets say `getting-started` folder. Since there is no shared parent pom all is good.

2. in quickstart repo like https://github.com/jboss-developer/jboss-eap-quickstarts you would like a full checkout as each quickstart refer to the parent pom and possibly other modules next to it - but be able to "focus" us just importing i.e. hello-world + parent project.

3. with more "traditional" multi-module project like https://github.com/quarkusio/quarkus you want to checkout everything but at least have a way to limit how much of the project gets imported to avoid using all available memory and/or at least be able to "focus' the selected projects.

For now using che for mainly smaller projects and quickstarts #1 and #2 would be a great help.

**Comment by maxandersen** [comment]
![2019-09-19_11-10-29 (1)](https://user-images.githubusercontent.com/54129/65230539-5377f780-dace-11e9-9a75-443b80844e0d.gif)

here is video of my running wizard and not getting validation before editing the value.

**Comment by skabashnyuk** [comment]
@l0rd @slemeur @sunix @tsmaeder  can you comment? look like it will require some changes on IDE side.

**Comment by sunix** [comment]
I commented [here](https://github.com/eclipse/che/issues/13671#issuecomment-533060116)
I would like to explore theia workspace root to solve that problem.

**Comment by sunix** [comment]
another clean fix: https://github.com/eclipse/che/issues/15540
