### ISSUE TITLE
Load-factory flow wrong behavior

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14554]
### Describe the bug

Create a new workspace from a devfile with policies.create=peruser flow doesn't redirect to the workspace in the case when this workspace is already running.   
  In other cases(workspace with the same 'factoryurl' is stopped or doesn't exist) all work good.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a new workspace with the devfile ```https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml```.
```
http://<your-che-host>/f?url=https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml&policies.create=peruser
```
2. Try to repeat 1 (```http://<your-che-host>/f?url=https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml&policies.create=peruser```)

Then we can see the load-factory page with a console error. Without any redirection after.

### Expected behavior

The target workspace should be opened.
### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2019-09-15 19-44-11](https://user-images.githubusercontent.com/6310786/64925173-6d2aed80-d7f5-11e9-88e8-4d09f0e51dc3.png)
### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by olexii4** [comment]
As we are discussed with  @skabashnyuk: 
Workspace attribute **factoryurl** should contain **url** and others params.

For example:
In the case with
```http://<your-che-host>/f?url=https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml&policies.create=peruser```
we should have
```
factoryurl: "https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml&policies.create=peruser"
```

**Comment by sleshchenko** [comment]
One more issue that I faced during `policies.create=peruser` scenario: Dashboard should handle case when there is already STARTING workspace. Now it's trying to run it the second time and gets error `You are not allowed to run more workspaces`

![Screenshot_20191008_141251](https://user-images.githubusercontent.com/5887312/66392971-01920580-e9da-11e9-9d91-0603efa4d249.png)

**Comment by l0rd** [comment]
Setting `severity/P1` since it affects #14745

**Comment by nickboldt** [comment]
Added to 7.3 milestone per CRW Cabal / Che SOS discussions this week
