### ISSUE TITLE
How can I give user permission for each stack in che7?

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#14559]
## Che version
7.1.0

## Description 
In che6, I could give the user permissions to the stack with the api as shown below. 
![image2018-12-5_16-23-21](https://user-images.githubusercontent.com/29850624/64946572-24833b00-d8ae-11e9-83fb-1e042268621e.png)

How can I give user permission for each stack in che7?
I want to create a stack that only a specific user can use.

**Comment by ibuziuk** [comment]
@kellyhyomin Could you please clarify the use-case a bit? Currently, stacks are devfile based that are coming from https://github.com/eclipse/che-devfile-registry which are already available for all users. If you create a custom stack (aka devfile) you will be able to share it with anyone via https://www.eclipse.org/che/docs/che-7/configuring-a-workspace-using-a-devfile/#creating-a-workspace-from-a-devfile

**Comment by kellyhyomin** [comment]
@ibuziuk 
Thank you for your help.
I(admin) want to make my stack available only to specific users.
I was wondering if this feature was supported in the previous 6 version but not in 7 version.
If you don't support version 7, do you have a support plan?

**Comment by skabashnyuk** [comment]
We have no support of that in che7 and no plans in close future to do that.

**Comment by skabashnyuk** [comment]
Closing. There is no stack concept in Che7
