### ISSUE TITLE
Plugin runtime crashed unexpectedly

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14551]
### Describe the bug

Plugin runtime is crashed after starting a workspace.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a new workspace with a devfile
```
http://host/f?url=https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml
```
Or from a stack. 

Theia will be open with an error:  'Plugin runtime crashed unexpectedly'

### Expected behavior

Theia will be open with working plugins.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2019-09-14 15-46-23](https://user-images.githubusercontent.com/6310786/64910948-8f086f80-d724-11e9-8c16-6097c24c6c35.png)
### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by mmorhun** [comment]
I have investigated the problem and the only reason of fails I could see is OOM.
The error message was changed: the hint about out of memory was added.
