### ISSUE TITLE
Support nodeSelectors for Workspace pods

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#14562]
It should be possible to define a `nodeSelector` value that will be used by Che when creating workspace deployments to allow Che to use certain kinds of workspaces only. The initial request is to be able to have a single `nodeSelector` for all Che workspaces on a Che instance.  A way to have per workspace `nodeSelector`s is not part of this enhancement and can be considered in the future.

**Comment by mingfang** [comment]
related to https://github.com/eclipse/che/issues/16426

**Comment by skabashnyuk** [comment]
I think we can introduce such property for the node selector.
```
che.workspace.pod.node_selector=disktype=ssd,cpu=xlarge
```
Node affinity is way more complex and I don't see a simple and easy way how we can configure it with properties/env variable. I may suggest such a way:
```
che.workspace.pod.affinity.node_affinity=base64 of configuration json
```
or 
```
che.workspace.pod.affinity.node_affinity_config_map_name=name of configuration map with configuration json
```
where configuration json something like that:
```json
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
```
CC @l0rd @davidfestal 


Or we can move node affinity into the individual issue and introduce it a bit later.
