### ISSUE TITLE
Need quickstart documentation to install Eclipse Che on EKS

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#14563]
### Describe the solution you'd like
It would be nice if we can get quickstart documentation for installing eclipse che on EKS.

### Additional context
Documentation similar to this https://www.eclipse.org/che/docs/che-7/che-quick-starts.html#deploying-che-on-kubernetes-on-aws_che-quick-starts would be very helpful.

Thank you very much !

**Comment by l0rd** [comment]
Thank you @svkr2k for raising this and indeed that's something interesting for us as well. I am not sure that we currently have the capacity to test it and update the doc though. Would you be interested in creating a PR? 

cc @benoitf

**Comment by svkr2k** [comment]
Thank you @10rd. I would like to check if we can get any help with setting up eclipse che on EKS?

**Comment by baseinfo123** [comment]
It would really help if there is a guide or an cloud formation template for eclipse che for EKS ,  have tried installing kubernetes on AWS via the documentation provided .. but could not succeed.
