### ISSUE TITLE
Devfile and Plugin Registries define its own domain even when default/single mode is configured

### ISSUE THREAD

**Issue by leader-us** [eclipse-che/che#14564]
With the latest master version , I can deploy single-host mode successfully . 
Can I deploy Che using ingress gateway's IP address instead of domain ?  for example ,set global.ingressDomain=192.168.18.30 instead of mychedomain

**Comment by leader-us** [comment]
![test](https://user-images.githubusercontent.com/5953348/65024666-e1859e00-d967-11e9-892d-50ff448562f1.PNG)

obviously  devfile-registry-default.192.168.18.3 is not a valid IP

**Comment by l0rd** [comment]
@leader-us I guess that it should be possible but @sleshchenko can be more precise. 

Anyway it looks like in your screenshot you are not using single-host. Can you provide more information about how you have deployed Che (chectl, helm chart, operator, minishift-addon?) and what's the versions of kubernetes .

**Comment by sleshchenko** [comment]
Adding @metlos since he worked on Single/Default host mode support.

**Comment by leader-us** [comment]
@metlos @l0rd  I use Helm to deploy Che on kubernetes v1.15.2  .  I saw ingress yarn file of devfile-registry and plugin-registry , the host name is prefix+ingressdomain .

**Comment by leader-us** [comment]
https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/ingress.yaml

![3](https://user-images.githubusercontent.com/5953348/65150150-0fe1a700-da56-11e9-889a-a7025a98ffd3.png)

**Comment by leader-us** [comment]
@l0rd @sleshchenko @Fabs @metlos 
I try to modify devfile-registry's ingress yaml ,so I can use ingress gateway's ip and subpath to access it ,for example 
![image](https://user-images.githubusercontent.com/5953348/65250688-8a7af700-db28-11e9-9016-171fcb33e1c4.png)

so I can access  devfile-registry as following 

![image](https://user-images.githubusercontent.com/5953348/65250521-40921100-db28-11e9-83cc-65d2e3568588.png)


but when i access che from browser ,I find it use https instead of http ,so some error occurred !
![image](https://user-images.githubusercontent.com/5953348/65250342-00cb2980-db28-11e9-8a08-2779ecc270c1.png)

**Comment by sleshchenko** [comment]
you're not able to just modify ingress since some certificate is already assigned to it...
Could you share full helm command that you run to get Che deployed? I guess it may be a bug...

**Comment by sleshchenko** [comment]
Seems that [Plugin Registry](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates/ingress.yaml#L18) and [Devfile Registry](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/ingress.yaml#L18) helm charts do not respect in the same way as [Che](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/ingress.yaml#L31) and [Keycloak](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/ingress.yaml#L31) do

**Comment by leader-us** [comment]
helm install -n  myche     -f ./values/default-host.yaml  .
global:
  multiuser: true
  ingressDomain: 192.168.18.3
  serverStrategy: single-host


[root@k8s_lab che]# helm install -n  myche     -f ./values/default-host.yaml  .
Error: release myche failed: Ingress.extensions "keycloak-ingress" is invalid: spec.rules[0].host: Invalid value: "192.168.18.3": must be a DNS name, not an IP address

so I try modified some yarm files to install and  Plugin Registry and Devfile Registry helm  ingress can't work properly

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/17149

**Comment by tolusha** [comment]
Issue is fixed by:
https://github.com/eclipse/che/pull/17392
https://github.com/eclipse/che-operator/pull/341

We still have problem with starting workspaces in single-host mode https://github.com/eclipse/che/issues/17396
