### ISSUE TITLE
che 7.1.0 status shows "57% Java Language Server - import Maven properties" for more than 10 minutes 

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#14577]
Is it normal to see the message "57% Java Language Server - import Maven properties"  shows on the status bar more than 10 minutes?

I am running che behinds the firewall and I do have Maven settings.xml for download the maven  dependencies.

Does it mean that Java Language Server needs to the proxy in order to access the outside Maven repository to download plugins?

**Comment by l0rd** [comment]
@tsmaeder @tolusha any suggestion?

**Comment by tolusha** [comment]
If LS can't download dependencies then the message  `"57% Java Language Server - import Maven properties"` shows forever

**Comment by tsmaeder** [comment]
@tolusha shouldn't the maven download time out after a while?

**Comment by tolusha** [comment]
maybe nobody hide the message after timeout...

**Comment by fbricon** [comment]
@snjeza can you please check?

**Comment by snjeza** [comment]
Related issue - https://github.com/eclipse/eclipse.jdt.ls/issues/1121

**Comment by rbcminghou** [comment]
So, is it a way to increase memory so that vscode-java won't OOMKilled?

**Comment by tolusha** [comment]
@rbcminghou 
Add `memoryLimit` attribute to a component:

```
memoryLimit: 512Mi
```

https://redhat-developer.github.io/devfile/

**Comment by rbcminghou** [comment]
Check my devfile, and I am already on 512Mi memoryLimit.  Should I make 1024Mi?

**Comment by tolusha** [comment]
yes, increase it to 1024Mi

**Comment by rbcminghou** [comment]
It took more than 5 minutes to make the change from 57% to 88%, then the Java LS went away from the status bar.

**Comment by snjeza** [comment]
Related PR - https://github.com/eclipse/eclipse.jdt.ls/pull/1184

**Comment by rbcminghou** [comment]
@snjeza, where I can apply the following entry? And, the following entry is good for "java-0.50.0.vsix"? 

"java.jdt.ls.vmargs": "-Daether.connector.requestTimeout=10000 -Daether.connector.connectTimeout=10000 -noverify -Xmx1G -XX:+UseG1GC
 -XX:+UseStringDeduplication"

**Comment by tsmaeder** [comment]
@rbcminghou there is a preference in theia for the vm args.

**Comment by rbcminghou** [comment]
So far, I did the similar message shows on the version 7.2.0.  close this ticket for now.
