### ISSUE TITLE
Keycloak doesn't upgrade from che-keycloak:6.19.0 to che-keycloak:7.1.0 on operator upgrade.

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#14575]
### Describe the bug
When trying to upgrade a Che cluster created using the che operator (equivalent to crw 1.x), the operator doesn't upgrade the keycloak deployment even though the new version of the operator should use a new image version.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] che operarator from the 1.2.2.GA tag

### Steps to reproduce
1. Install che operator 1.2.2.GA
1. install che cluster
1. do rolling update of the operator to version 7.1.0

### Expected behavior
The keycloak deployment should use the `che-keycloak:7.1.0`  image.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by l0rd** [comment]
@davidfestal are you already aware of this problem?

**Comment by davidfestal** [comment]
Well, it's the same as https://github.com/eclipse/che/issues/13714 but applied the scenario of an upgrade from Che 6 (CRW1.2) to Che 7.1.0, instead of the upgrade of 7.0.0 to 7.1.0, which was fixed.

More details in the initial issue: https://github.com/eclipse/che/issues/14200#issuecomment-532384111

**Comment by l0rd** [comment]
@metlos we can close this one since we have decided to solve it as a doc issue (and [doc pr has been merged](https://github.com/eclipse/che-docs/pull/837))?
