### ISSUE TITLE
Question: port range to open in amazon instance

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#1457]
Hello, I have a short question:
on your website you say that we need to open ports 32768-65535.
Nethertheless I've encountered some discussions on the net that say that we only need ports 32768-32788. What is the good answer (the idea would be to expose the less ports possible)

And another question: is it possible to only open port 8080? I know it is possible locally by doing this:
# Create a copy of `/conf/che.properties` file and modify:

machine.docker.che_api.endpoint=http://172.17.0.1:8080/ide/api
# Launch Che with modified Docker command

docker run -ti 
           -p 8080:8080 
           -v /var/run/docker.sock:/var/run/docker.sock 
           -v /home/user/che/lib:/home/user/che/lib-copy 
           -v /home/user/che/workspaces:/home/user/che/workspaces 
           -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage 
           -v $(pwd)/che.properties:/home/user/.che/che.properties 
           -e CHE_DOCKER_MACHINE_HOST=172.17.0.1
           codenvy/che

But this is not applicable when che must be reached by remote clients, right?

**Comment by TylerJewell** [comment]
The browser needs to get to the port of the Che server and the Docker ephemeral port range.  However, the Che server and the Docker containers have additional ports that need to be opened for their communication back and forth between each other.

https://eclipse-che.readme.io/docs/networking

On the full range of Docker ports - you can open a shorter range.  Docker does start from the beginning of the range. So as you open up additional servers and expose them from within the workspaces, the number of ports required increases.

**Comment by james10174** [comment]
@agnesagnes You can check out the recent issue [.](https://github.com/eclipse/che/issues/1438) Might be a little overwhelming though if you are just starting out with Che. codenvy.com might be a better solution for you if you are just trying to use eclipse che remotely or in the cloud.

**Comment by ghost** [comment]
@agnesagnes this is the ephemeral port range. For a few workspace that you simultaneously run in Che, you'd need, say 30-40 ports. However, it's Docker that picks them and I cannot guarantee that it'll pick the ones from the range you have opened, but can guarantee it's the ones from the ephemeral port range.

**Comment by agnesagnes** [comment]
Thank you for the answer! So for the moment I take for granted the fact that docker picks them in order. Now I have a lot of other question but I will ask them in another issue (quite related to #1475). 
Thank you so much answering my dumb questions by the way.
