### ISSUE TITLE
[plugin registry] Do not reference marketplace.visualstudio.com in plugin registry meta.yaml

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14573]
### Describe the bug

Microsoft says marketplace.visualstudio.com is for VS Code users ONLY.

Therefore we can't point from the plugin registry to marketplace.visualstudio.com anymore.

Example:

https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/node-debug/1.32.1/meta.yaml (last line)
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/node-debug/latest/meta.yaml#L20

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Expected behavior

We should instead either:
* pre-pull the artifacts and host them in the plugin registry container, or
* host the artifacts on a redhat.com server (or download.jboss.org), or 
* pull files from github releases

And:
* validate the meta.yaml files don't container any refs to marketplace.visualstudio.com (new test script)

### Affected files

```
./v3/plugins/joaompinto/vscode-asciidoctor/2.7.6/meta.yaml 
./v3/plugins/joaompinto/vscode-asciidoctor/latest/meta.yaml 
./v3/plugins/ms-python/python/2019.2.5433/meta.yaml << fixed
./v3/plugins/ms-vscode/node-debug/1.32.1/meta.yaml 
./v3/plugins/ms-vscode/node-debug/1.35.2/meta.yaml 
./v3/plugins/ms-vscode/node-debug2/1.31.6/meta.yaml 
./v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml 
./v3/plugins/ms-vscode/node-debug2/latest/meta.yaml 
./v3/plugins/ms-vscode/node-debug/latest/meta.yaml 
```

cc: @gorkem @slemeur @benoitf

**Comment by nickboldt** [comment]
joaompinto/vscode-asciidoctor does not publish its built vsix file to github, but only to marketplace.visualstudio.com -- opened https://github.com/asciidoctor/asciidoctor-vscode/issues/221

**Comment by nickboldt** [comment]
node-debug and node-debug2 projects don't publish vsix files to github either.

* https://github.com/microsoft/vscode-node-debug/releases/tag/v1.35.3
* https://github.com/microsoft/vscode-node-debug2/releases/tag/v1.33.0

Since we need an offline/airgap plugin registry solution anyway, and since I have to pull sources to make our Open Source Lawyers happy, perhaps it'd be worth rearchitecting the plugin registry build process so that it:

* pulls all sources for all plugins
* builds all vsix files locally
* references the local files with `relative:extension/resources/*.vsix` (see https://github.com/eclipse/che-plugin-registry/pull/211 )
* creates container image
* creates a tarball of all the 3rd party sources

**Comment by mkuznyetsov** [comment]
ATM I have Jenkins jobs that would perform a packaging of all desired extension .vsix files into tarball

Now it needs to replace the links to the relative location of extensions and provide those extensions from the tarball mentioned above.
This will be done via one of sh scripts for building plugin-registry, which I'm working on right now. I expect it would take 1-2 more days for a PR to review.
Then I expect there still will be a need to make sure about the whole build process, as well as how the tarball could be stored outside of Jenkins build job

**Comment by nickboldt** [comment]
Just got confirmation from Stevan that since the old node-debug extension is ONLY for Node <8 and the node-debug2 one is for Node 8+, we don't need to worry about building the old one for CRW 2.

Still trying to convince him that we should also remove the old one (Node 6 debug support? really?) from Che 7'4's plugin registry.

**Comment by nickboldt** [comment]
Making progress in https://docs.google.com/spreadsheets/d/1TllnofYIlA7yTn7hIa8-LojGpHR1ACk1hVP-7fg_wsY/edit#gid=1935159288 but still not done. Slip to 7.7.0

**Comment by nickboldt** [comment]
Followup work for CRW 2.1 (based on Che 7.9) to be done in https://issues.redhat.com/browse/CRW-578.

We can close this tracker once https://github.com/eclipse/che/issues/14677 is complete
