### ISSUE TITLE
Install Eclipse-Che 7 on Kubernetes on AWS

### ISSUE THREAD

**Issue by mby-che** [eclipse-che/che#14584]
Hi Everyone, 

I was trying to follow the official documentation for eclipse che 7 on AWS : https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/

All steps were applied succesfully without any error, until i get to the task 13 : 
"Check if the issuerRef name is the same as the ClusterIssuer. A new DNS challenge is being added to the DNS zone for Let’s encrypt." 

I did not found any DNS entry added as shown in the picture "_acme......".
When logs displayed, the first part says : 

I0917 18:55:03.979487       1 conditions.go:91] Setting lastTransitionTime for Issuer "cert-manager-webhook-selfsign" condition "Ready" to 2019-09-17 18:55:03.979482327 +0000 UTC m=+0.946670382
I0917 18:55:03.980151       1 controller.go:153] cert-manager/controller/issuers "level"=0 "msg"="syncing item" "key"="cert-manager/cert-manager-webhook-ca" 
E0917 18:55:03.980222       1 pki.go:75] cert-manager/controller/issuers "msg"="failed to retrieve secret" "error"="secret \"cert-manager-webhook-ca\" not found" "related_resource_kind"="Secret" "related_resource_name"="cert-manager-webhook-ca" "related_resource_namespace"="cert-manager" "resource_kind"="Issuer" "resource_name"="cert-manager-webhook-ca" "resource_namespace"="cert-manager" 
E0917 18:55:03.980245       1 setup.go:47] cert-manager/controller/issuers/setup "msg"="error getting signing CA TLS certificate" "error"="secret \"cert-manager-webhook-ca\" not found" "resource_kind"="Issuer" "resource_name"="cert-manager-webhook-ca" "resource_namespace"="cert-manager" 
I0917 18:55:03.980268       1 conditions.go:91] Setting lastTransitionTime for Issuer "cert-manager-webhook-ca" condition "Ready" to 2019-09-17 18:55:03.980264411 +0000 UTC m=+0.947452610
I0917 18:55:03.980294       1 sync.go:76] cert-manager/controller/issuers "level"=0 "msg"="Error initializing issuer: secret \"cert-manager-webhook-ca\" not found" "resource_kind"="Issuer" "resource_name"="cert-manager-webhook-ca" "resource_namespace"="cert-manager" 

In the final part of logs , it says : 
E0918 10:23:20.357011       1 controller.go:200] cert-manager/controller/orders "msg"="re-queuing item  due to error processing" "error"="error creating new order: acme: urn:ietf:params:acme:error:rejectedIdentifier: Error creating new order :: Cannot issue for \".awscloud.video-dev.com\": DNS label is too short" "key"="che/che-tls-58559884" 

please find all logs attached. 
It is the most important step before launching eclipse che 7 , please help to proceed to the final step.

Thanks

**Comment by mby-che** [comment]
File for all Logs : 
[LOGS CHE.pdf](https://github.com/eclipse/che/files/3626001/LOGS.CHE.pdf)

File for ClusterIssuer & issuerRef : 
[issuerRef.pdf](https://github.com/eclipse/che/files/3626010/issuerRef.pdf)
[ClusterIssuer.pdf](https://github.com/eclipse/che/files/3626011/ClusterIssuer.pdf)

Thanks for investigating the error !

**Comment by sleshchenko** [comment]
I assume that `*` is missing in domain and DNS names. See https://www.eclipse.org/che/docs/che-7/installing-che-on-google-cloud-platform/#installing-cert-manager-on-kubernetes_preparing-google-cloud-platform-for-installing-che
@mby-che Could you try to recreate your certificate with `*` included?

**Comment by mby-che** [comment]
Problem solved with * @sleshchenko , thank you so much.
Documentation must be updated to correct this issue on their website ... there is no (*) over there.

Thanks guys
