### ISSUE TITLE
chectl: --devfile-registry-url and --che-operator-cr-yaml do not play well together

### ISSUE THREAD

**Issue by makandre** [eclipse-che/che#14589]
### Describe the bug

I'm using `chectl` to deploy a customized version of Che (using `--che-operator-cr-yaml`).  

I also want to use an external devfile registry.

- I assumed that specifying `--devfile-registry-url=<url>` will work, but it ends up still using the default online devfile registry
- Turns out I need to add `devfileRegistryUrl` property to my yaml; but I still need `--devfile-registry-url` otherwise it still deploys a devfile registry pod (I think #13949 may address this?)

So the gist of it is that I need to specify the devfile registry url **both** in my yaml and on the `chectl` command line which is not ideal

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)

```
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://makandre-master.fyre.ibm.com:8443
openshift v3.11.0+739ab57-285
kubernetes v1.11.0+d4cacc0
```

   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by rhopp** [comment]
I agree, that when chectl is using operator to install Che, it's really confusing how checluster CR yaml and chectl flags play together.

For the specific problem you are having, there is should be boolean property in checluster CR `externalPluginRegistry`.

**Comment by nickboldt** [comment]
Since the cr.yaml now includes the option to override 9 Che images [1] including the two registries... maybe we should remove the plugin/devfile registry CLI options?

[1] https://github.com/redhat-developer/codeready-workspaces-deprecated/blob/master/operator-installer/custom-resource.yaml#L12-L14

**Comment by tolusha** [comment]
`--devfile-registry-url` is ignored when  `--che-operator-cr-yaml` is used.
External devfile registry can be configured in cr yaml file
