### ISSUE TITLE
<workspaceid> placeholder for workspace namespace/project

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14585]
~~### Is your enhancement related to a problem? Please describe.~~
~~namespace/project can have placeholders now (https://github.com/eclipse/che/issues/13488). Empty value would mean that `workspace.id` will be used as a namespace/project. It would now make sense to have `<workspace.id>` placeholder.~~

~~### Describe the solution you'd like~~
~~`<workspace.id>` placeholder for namespace/project.
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L375
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L581~~

~~### Additional context~~
~~Namespace placeholders was introduced as a fix for this https://github.com/eclipse/che/issues/13488. Work on this after PR is merged https://github.com/eclipse/che/pull/14524~~

As a consequence, PR #14828 is adding support for `<workspaceid>` in the namespace configuration. This issue is for updating the docs with the new information.

**Comment by l0rd** [comment]
Setting P1 to this issue because it looks necessary if we want to continue supporting one namespace per workspace strategy (even if the default is one namespace per user).

**Comment by sparkoo** [comment]
I think it is already part of PR #14828 -> https://github.com/eclipse/che/pull/14828/files#diff-4eed0e9903e80a21758bbe991eee8c37R66
@metlos ?

**Comment by metlos** [comment]
> I think it is already part of PR #14828 -> https://github.com/eclipse/che/pull/14828/files#diff-4eed0e9903e80a21758bbe991eee8c37R66
> @metlos ?

Yes, #14828 is adding this functionality. I've updated the description of this issue to be basically docs-only.
