### ISSUE TITLE
617 pods created by che and increasing

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#14598]
### Describe the bug

617 pods created by che and increasing

### Che version

 - [ ] latest
 - [ ] nightly
 - [X] other: please specify
7.1.0

### Steps to reproduce

I have no idea how it happened, all I have are about 3 workspaces (they are running just fine)
All i remember, at some point, I was trying dev and reported some bug about it https://github.com/eclipse/che/issues/14590

I tried creating multiple test workspaces but eventually I would delete them

I went to office, got back home finding che's pod is instable and `549` which 1 hour later became `617`

I have k8s cluster deployed with worker that is 32 GB memory, 6 CPU and 1TB NFS storage that are impossible to be 100% consumed by Che a lone!!! And I have almost nothing but Che on that cluster, see screenshot below for more insights.

I do not upload videos, maximum storage i need for my dev environment is at best 3 GB, I am using 2.3 GB at the moment, the entire cluster has almost nothing but che (screenshots will show)

I did check https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/ but please keep in mind about this >> https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#best-practices
> Operator wants to evict Pods at 95% memory utilization to reduce incidence of system OOM.

### Runtime
   - [X] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:23:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
### Screenshots

Che unstable:
![image](https://user-images.githubusercontent.com/11182824/65243829-8650d880-db2c-11e9-9791-c4b9068db361.png)
Nodes allocated resources:
![image](https://user-images.githubusercontent.com/11182824/65243991-e778ac00-db2c-11e9-8080-695cca7461dd.png)
![image](https://user-images.githubusercontent.com/11182824/65244024-fa8b7c00-db2c-11e9-8ec7-f75acdf5c0c4.png)
Consumed storage out of 1TB:
![image](https://user-images.githubusercontent.com/11182824/65244062-0c6d1f00-db2d-11e9-9249-4736dea55648.png)
Running workspaces just fine (I believe that those are the 3 that all I have):
![image](https://user-images.githubusercontent.com/11182824/65244144-33c3ec00-db2d-11e9-9760-ed5e0f18f734.png)
Rest of the world of `617` pods:
![image](https://user-images.githubusercontent.com/11182824/65244170-40e0db00-db2d-11e9-9793-dc71428413c7.png)
Pods:
![image](https://user-images.githubusercontent.com/11182824/65244930-f6605e00-db2e-11e9-92a2-83fd8055139f.png)

### Installation method
   - [X] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
```
chectl server:start --installer=helm --domain=MyDomain.com --multiuser --platform=k8s --tls
```

### Environment
   - [X] my computer 
       - [ ] Windows
       - [X] Linux
       - [ ] macOS
   - [X] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [X] other (please specify) 
   - [X] other: please specify
[Canonical deployment of Kubernetes](https://jaas.ai/kubernetes-core)

**Comment by skabashnyuk** [comment]
@SDAdham thank you for this report. Can you explain what action do you expect? Can you reproduce that on new clear k8s environment?

**Comment by SDAdham** [comment]
I have no clue tbh, is there an infinite loop for che to keep creating that much of pods
See this >>
![image](https://user-images.githubusercontent.com/11182824/65245025-2576cf80-db2f-11e9-8235-7d1f0860b92e.png)
These are all 3 workspaces i have, but why 617? Why che keeps creating more workspaces and yet till now?

**Comment by SDAdham** [comment]
btw, those 3 are running just fine till now:
![image](https://user-images.githubusercontent.com/11182824/65245128-5951f500-db2f-11e9-8975-038f6d63ebc5.png)
Look at their age too

**Comment by SDAdham** [comment]
`651` now, the good question is why that much when all i have are 3 workspaces and they are running?

**Comment by skabashnyuk** [comment]
That is strange. I never saw that someone reported the same behavior. is that possible that you forget some tooling running outside? Do you use multiuser che? Can you change your password?

**Comment by SDAdham** [comment]
Events are too many to see from the beginning, and in such issue, i think the best to tackle only if we were able to get the beginning, the best we will see is `ephemeral-storage` which please keep in mind, this is none-billable storage, so maybe from too many load on kubelet, this is now what we see

Events log file: [Che-Events.log](https://github.com/eclipse/che/files/3631302/Che-Events.log)

**Comment by SDAdham** [comment]
> is that possible that you forget some tooling running outside? Do you use multiuser che? Can you change your password?

I don't have any tools connected to Che, my password is too complex, this is almost 1.5 week environment, and yes it's multiuser che

**Comment by SDAdham** [comment]
Few leads maybe:

- I was trying to use dev files
- I was trying to create new workspaces using https://che.mydomain.com/f?url=https://path/to/your/raw/devfile

Sometimes the link would fail, sometimes it would work, but won't create the expected environment

At the beginning, when i used the link, it was going to a login page, I moved the dev files to a public repo, not sure at which point it can be reproduced?
* When the link was redirection to a login
* When the link given was the home page of the repo that didn't have a yaml
* When the link given was to an invalid dev file content
* When the link given was to a valid dev file but workspace created wasn't the expected outcome (see https://github.com/eclipse/che/issues/14590 )

**Comment by sleshchenko** [comment]
It's a really strange behavior and I guess it's K8s who did things wrong (I may be wrong here as well) or maybe some things are misconfigured.
At this stage looks like Deployments do not clean evicted pods that were produced by `DiskPressure`, we should be able to reproduce it. If it can be easily reproduced - then Che would be able to clean up pods additionally to cleaning up deployments.
But it does not really clear why `DiskPressure` started happen if you have PVCs which require 12 Gi  and you have configured storage 1TB. I don't have any clear idea about it.
BTW Thanks for reporting an issue, it definitely needs attention and investigation.

**Comment by SDAdham** [comment]
Based on our investigation @sleshchenko & I:

Long story short, the pods were reaching out their own limit from storage perspective as the limits of the workspaces created by Che was always 1Gi while I was trying to clone project that's > 1Gi.

@sleshchenko were able to pin the parts were the 1Gi limit is assigned:

* https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/resources/schema/devfile.json#L732
* https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L38

**Workaround:**

Setting **CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE** & **CHE_INFRA_KUBERNETES_PVC_QUANTITY** to **10Gi** in the `che`'s **ConfigMap** then restarting `Che`'s server allowed `Che` to create future workspaces with sufficient storage size.

**Suggestion:**

When creating a new workspace, as much as get to set memory, maybe we should also be able to set storage size?
