### ISSUE TITLE
[chectl] Failed to check running status if previous deployment is not cleaned up yet

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14595]
### Describe the bug
chectl failed to check running status if previous deployment is not cleaned up yet.

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che with chectl (I did `chectl server:start --installer=minishift-addon --platform=minishift-` but any other should be fine as well).
2. Restart Che Server with `chectl server:stop && chectl server:start`

### Expected behavior
Che is stopped and started again.

### Actual behavior
Che is stopped and started again but chectl report an issue since it's not able to check Che Server status. You can use `kubectl` or `oc` to make sure that Che is starting and will be available soon
![Screenshot_20190919_111711](https://user-images.githubusercontent.com/5887312/65226209-20823380-dacf-11e9-81c5-0c7881b58cd9.png)

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
It caused by that fact that chectl has [waitUntilPodIsDeleted](https://github.com/che-incubator/chectl/blob/master/src/api/kube.ts#L489) that actually waits until pod is not available.
And then when chectl tries to find starting pod - it fails because it finds 2 pods ( terminating and starting ). It must be reworked.
Fixing of this issue would allow adding E2E test for startStopStart scenario https://github.com/sleshchenko/chectl/commit/90cd4c9d8869c1f08feb0b8900bcce6586241789

**Comment by tolusha** [comment]
Fixed in https://github.com/che-incubator/chectl/commit/86e0f65e81f68938bb2fe3ad89e538ce5ae15c07
