### ISSUE TITLE
Che Server http sessions leak

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14599]
### Describe the bug
During my test https://github.com/eclipse/che/pull/13034
![64536243-0bf8ab00-d319-11e9-9a3f-ae83bac5001f](https://user-images.githubusercontent.com/1614429/65244994-6b627200-daf4-11e9-8ea8-18400d18550a.png)
I've noticed that if we are not using browser client as we do for brockers, chectl, etc  we 
create an individual http session on tomcat side that may because of memory leak.
The goal of this task is to use a single http session after we identified the actual user. We can reuse parts of Codenvy SSO code to do that.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
multiple requests like ``` curl http://localhost/api/user``` with keycloak token.

### Expected behavior
Tomcat will use the same http session for all request processing.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
<img width="1605" alt="Знімок екрана  о 11 52 59" src="https://user-images.githubusercontent.com/1614429/66642806-b7996180-ec1d-11e9-871c-82b0a88e5a10.png">
12 http sessions just to open one workspace

**Comment by mshaposhnik** [comment]
Merged in #15000
