### ISSUE TITLE
[Openshift Connector]Update Che Openshift Connector plugin

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#14607]
Since [VSCode Openshift connector](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector)  was released to 0.1.0 version, we have to update [Che Openshift Connector plugin](https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/redhat/vscode-openshift-connector).

**Comment by vparfonov** [comment]
duplicate https://github.com/eclipse/che/issues/14605
