### ISSUE TITLE
Update VS Code OpenShift Connector to v0.1.0

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14605]
### Is your enhancement related to a problem? Please describe.

The new version of VS Code OpenShift Connector has been released https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector with the support for OS 4 clusters.

We currently publish version [0.0.12](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/vscode-openshift-connector/latest/meta.yaml#L16) in the plugin registry.

### Describe the solution you'd like

Add the new version in the plugin registry and update latest

**Comment by azatsarynnyy** [comment]
Done in https://github.com/eclipse/che-theia/pull/465 + https://github.com/eclipse/che-plugin-registry/pull/238
