### ISSUE TITLE
[Openshift Connector] Can't login into k8s cluster 

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#14609]
### Describe the bug

It is not possible to login into Openshift cluster throw the UI.

### Che version

 - [x] latest

### Steps to reproduce
- Create and start a workspace with Openshift connector plugin
- Try to login into k8s cluster. Use one of the login command:
![Screenshot from 2019-09-20 11-46-17](https://user-images.githubusercontent.com/1271546/65313267-c354b380-db9c-11e9-8017-46af8130a38a.png)

  As a result I see:
![screenshot-che-che 192 168 99 146 nip io-2019 09 20-11_51_59](https://user-images.githubusercontent.com/1271546/65313503-21819680-db9d-11e9-8060-d616e392b2d5.png)

### Runtime
   - [x] minishift

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

### Additional context
Che Openshift Connector plugin's version is 0.0.21

**Comment by azatsarynnyy** [comment]
Thanks for reporting it!
I've reopened the original issue to find a solution.

duplicates https://github.com/eclipse/che/issues/13405
