### ISSUE TITLE
[Openshift Connector] Open URL doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#14608]
### Describe the bug

Open URL button in Openshift Application Explorer doesn't work

### Che version

 - [x] latest

### Steps to reproduce
Create new Openshift application:

- Create and start a workspace with Openshift connector plugin and clone https://github.com/che-samples/nodejs-mongodb-sample
- Open a terminal from vscode-openshift-connector container
- Login into your Kubernetes cluster via `oc login https://<IP>:<PORT> --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
- Create a new project in Openshift application explorer
- Create New application in your project in Openshift application explorer
- Create New URL for your application in Openshift application explorer
- Click on the URL button

### Runtime
   - [x] minishift

### Screenshots
![screenshot-che-che 192 168 99 146 nip io-2019 09 20-11_31_30](https://user-images.githubusercontent.com/1271546/65311996-46283f00-db9a-11e9-9da5-37be4cdf55e8.png)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

### Additional context
Che Openshift Connector plugin's version is 0.0.21

**Comment by vparfonov** [comment]
duplicate https://github.com/eclipse/che/issues/13406
