### ISSUE TITLE
[Openshift Connector] OpenShift Connector is not available after first workspace starting

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#14611]
### Describe the bug

Just after starting the workspace Openshift Connector and Kubernetes Tools plugins are not available from the IDE. 

### Che version

 - [x] latest

### Steps to reproduce
- Create and start a workspace with Openshift connector plugin

How to reproduce video recording: https://youtu.be/RVN3mb0Wxw0

After refreshing all plugins are available.
### Runtime
   - [x] minishift

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

### Additional context
Che Openshift Connector plugin's version is 0.0.21

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che-theia/pull/490
