### ISSUE TITLE
[Docs] Workspaces RAM and CPU requirements

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14612]
### Is your enhancement related to a problem? Please describe.

Users don't know how much RAM and CPU a workspace will need. They don't know if a workspace will fail to start or not in their cluster because of the memory or cpu limits.

We pre-calculate the memory limits for the defaults stacks (e.g. [for angular it's 2686Mi](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/angular/meta.yaml#L6)). But we haven't documented how to calculate these limit for a custom stack.

### Describe the solution you'd like

Write a document (under `Using developer workspaces -> Workspaces memory and CPU requirements`) that should answer the following question:

- Given a devfile, how much RAM the corresponding workspace will need (the memory limit)?
- Given a existing k8s cluster [resource quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/) and [limit ranges](https://kubernetes.io/docs/concepts/policy/limit-range/) policies how can I figure out if my workspace will be scheduled or not?

Write a document (under `Administration Guide -> Cluster memory and CPU requirements`) that answer the following question:

- Given a sample workspace, and a number of users that should be able to use the workspace concurrently, what should be the cluster capacity and the suggested suggested resource quotas and limit ranges?

**Comment by slemeur** [comment]
Linking to downstream issue: https://issues.jboss.org/browse/CRW-228

**Comment by nickboldt** [comment]
@l0rd @rkratky is this something we might get done for Che 7.9 / CRW 2.1? I know at least one customer who's looking for guidance ...

**Comment by l0rd** [comment]
@nickboldt @themr0c @rkratky [I have created the doc](https://docs.google.com/document/d/1AlU-rYfELazYSLgXR8Gf5tfO5GyGnitVvLRqG_yaQ-c/edit#), I will seek for some reviews by TLs (and of course yours as well) and then I will transform it in asciidoc and publish it. Anyway it should be definately ready for 2.1.

**Comment by themr0c** [comment]
fixed by https://github.com/eclipse/che-docs/pull/1107
