### ISSUE TITLE
Che Theia build is broken

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14618]
### Is your task related to a problem? Please describe.
After changes in upstream Eclipse Theia project build of Che Theia is broken.

From CI build log:

```
lerna ERR! [compile] src/node/plugin-remote-init.ts(214,52): error TS2339: Property 'stopContext' does not exist on type 'PluginHostRPC'.
lerna ERR! [compile] error Command failed with exit code 2.
lerna ERR! [compile] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! [compile] yarn compile exited with code 2
```

### Additional context
Commit in Eclipse Theia which brought breaking changes: [50beaee]( https://github.com/eclipse-theia/theia/pull/6159/commits/50beaee18aaf92268802e09bf5f0044484439b98)

**Comment by mmorhun** [comment]
https://github.com/eclipse-theia/theia/pull/6159

**Comment by dmytro-ndp** [comment]
Link to broken build log: https://ci.codenvycorp.com/job/che-theia-pullrequests-build/683/console

**Comment by nickboldt** [comment]
79 files changed, one reviewer with unresolved feedback, merged on a Friday == BROKEN ALL WEEKEND. *slow clap for deploying on a Friday* :(

**Comment by gorkem** [comment]
+1 to take a Theia before that commit. I think that change has much more consequences than just a couple of renamed API. We should not release it on 7.2
