### ISSUE TITLE
Load test Che on real cluster

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#14629]
Target: 50-100 concurrent workspaces.
Descritpion TBD

**Comment by l0rd** [comment]
cc @kameshsampath

**Comment by Katka92** [comment]
I'm working on that issue for three weeks now. Currently, we can run load tests for multiple users. Each test is run with 1 user in 1 pod, using the same docker image as e2e tests with some changes (tests added, entrypoint changed). Results are sent to one specific pod via FTP and saved on PVC.
The test is written in typescript and is saved in e2e repo. This test starts workspace via factory URL and uses selenium to check that the workspace is started and IDE is loaded correctly. Currently, I'm facing problems with starting workspaces on OCP 4 with the `FailedSchedulling` error event and reaching limits.
TODO:
- find appropriate memory/CPU limits for one test pod (for now seems like 700Mi memory and 400m CPU)
- test logs processing part of tests (needs to have some passing tests)
- consider having load tests as a separate image, differences to e2e image:
  - include FTP client
  - changed privileges for adding/changing files
  - a lot of logic added in entrypoint

**Comment by Katka92** [comment]
The tests are done, PR with tests and README to show how to use it is merged. Closing.

**Comment by l0rd** [comment]
@rhopp @Katka92 we need to write down a document that help users to plan how many resources the wsmaster needs to support N concurrent workspaces. Is this something you can help with?

**Comment by slemeur** [comment]
opened: https://github.com/eclipse/che/issues/15641
