### ISSUE TITLE
Document how to use one namespace per user strategy (che.osio like)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14624]
### Is your task related to a problem? Please describe.
In this pr https://github.com/eclipse/che/pull/14524 we introduced some features that give more control over https://github.com/eclipse/che/issues/13488 one namespace per user strategy (che.osio like). As discussed here https://github.com/eclipse/che/issues/13488#issuecomment-527169293 we need 
- We need to update documentation explaining how to do that and what is the benefits from that.
- add a note to the documentation that compatible PVC strategies are: unique, common and perWorkspace

### Describe the solution you'd like
PR in che-docs

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by sparkoo** [comment]
here's global che docs overview task https://github.com/eclipse/che-docs/issues/712. "Configuring namespace strategies" is blocker for this.

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che-docs/pull/825
