### ISSUE TITLE
Collect server logs if Happy path tests fail on PR check on CRW CI

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14625]
### Is your enhancement related to a problem? Please describe.
There is sometimes lack of server logs after Happy path tests PR check failed on CRW CI, e.g. in case when chectl doesn't start Che, or workspace.

### Describe the solution you'd like
We need to modify PR check job to collect and to save server logs of certain build.

**Comment by tsmaeder** [comment]
And by "server logs", I guess you mean everything relevant, including the relevant output for using https://github.com/eclipse/che/wiki/Language-support-troubleshooting-document, right?

**Comment by dmytro-ndp** [comment]
@tsmaeder: you are right - it's about all logs we can grab from Che pods and kubernetes itself.
