### ISSUE TITLE
Updates to Hosted Che ConfigMaps

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14633]
### Is your enhancement related to a problem? Please describe.

Reviewing che.osio config maps I have noticed some that may be outdated.

### Describe the solution you'd like

The following ones

```
CHE_WORKSPACE_DEFAULT__MEMORY__MB
CHE_LIMITS_WORKSPACE_ENV_RAM
CHE_PREDEFINED_STACKS_RELOAD__ON__START
```

look like old (che 6) properties and the following one should be used instead

```
CHE_WORKSPACE_DEFAULT__MEMORY_LIMIT__MB
CHE_WORKSPACE_DEFAULT__MEMORY_REQUEST__MB
```

UPDATE: Check that no obsolete env vars are used in the Operator (mailing thread - Deprecated properties && environment variables) - redhat-developer/rh-che#1477

**Comment by ibuziuk** [comment]
Related to https://github.com/redhat-developer/rh-che/issues/1477

**Comment by ibuziuk** [comment]
@amisevsk can we close it now taken into account that https://github.com/redhat-developer/rh-che/pull/1673 is merged?

**Comment by amisevsk** [comment]
Yeah, I think I caught them all.
