### ISSUE TITLE
Grafana "Workspace failures" metric includes workspaces that are cancelled.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14639]
### Describe the bug
The current "Workspace failures" metric in grafana includes workspaces that "fail" because their startup is cancelled.

### Che version
 - [x] latest

### Steps to reproduce
1. Create workspace
2. Start workspace
3. While workspace is `STARTING`, click stop button
4. Observe climbing "failure" count.

### Expected behavior
Cancelled workspace starts should not be included in a "failed" metric, since they are user-driven.

**Comment by gazarenkov** [comment]
@amisevsk @skabashnyuk still actual or can be closed?

**Comment by skabashnyuk** [comment]
Closing since these metrics are no longer relevant for devworkspaces.
