### ISSUE TITLE
Search for Documentation Site Responds With 404 File not Found

### ISSUE THREAD

**Issue by danielhelfand** [eclipse-che/che#14647]
When searching for something on the [Eclipse Che Documentation site](https://www.eclipse.org/che/docs/), you will receive a `404 File not Found` no matter what you search for. This appears to be related to the fact the following is being added to the url for each search `introduction-to-eclipse-che/che-7` for che-7 docs. 

For instance, if you try searching for OpenShift 4 installation instructions, you will get the following url: https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/che-7installing-che-on-openshift-4-from-operatorhub

The actual url for the page is as follows: https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-4-from-operatorhub

This is possibly related to the site navigation.

### Steps to reproduce

Search for anything via the search bar.

**Comment by danielhelfand** [comment]
area/doc

**Comment by l0rd** [comment]
@danielhelfand thanks for opening this. Looking at it more closely I have spotted 2 issues:

1) there is no slash in the result URL after che-7
2) the result is appended to the current URL (you were probably on  https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che when you searched for OpenShift 4 installation)

@danielhelfand if you are willing to help you can open a pull request on https://github.com/eclipse/che-docs/

cc @rkratky @themr0c

**Comment by danielhelfand** [comment]
@l0rd Sure, I think the issue was this line in [`search.json`](https://github.com/eclipse/che-docs/blob/ad83f2ad3772b7de783c597976bdde3b40f384d7/src/main/search.json#L14). Also on line 27. Appears to fix it locally for me.
