### ISSUE TITLE
Unexpected list of suggestions when use Java languageserver

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14660]
### Describe the bug
Unexpected list of suggestions when use Java languageserver

### Che version
7.2.0-SNAPSHOT

### Steps to reproduce

 - Create workspace with Java languageserver
 - Go to any Java class
 - Type ```String example = new String()
                example.```
 - Place cursor after the dot of (example.)
 - Perform "ctrl + space combination"
 - Pay attention to the suggestion list

### Expected behavior
    Suggestion list displays a list with methods of "String" class

#### Observed dehavior
    Suggestion list displays extra suggestions
    
![Screenshot from 2019-09-25 17-31-17](https://user-images.githubusercontent.com/22724619/65610888-acf29180-dfba-11e9-8df2-4b882a8f1846.png)
![Screenshot from 2019-09-25 17-31-26](https://user-images.githubusercontent.com/22724619/65610892-aebc5500-dfba-11e9-8967-6ef17aa7a386.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ x ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ x ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
This looks like you don't have any java language support at all: it seems it's just the fallback "text only" support. How exactly are you runnign this? There is no such thing as "7.2.0-SNAPSHOT". Are you running a nightly image? Which devfile and which example project are you using?

**Comment by Ohrimenko1988** [comment]
@tsmaeder If I understood correctly on the second screenshot we can see methods from "String" class. So I suppose that language server initialized. Am I right?

**Comment by dmytro-ndp** [comment]
@tsmaeder: devfile could be found here: https://github.com/eclipse/che/blob/master/e2e/files/happy-path/happy-path-workspace.yaml
There was Java8 plugin of next version used.
The problem has being reproducing constantly.

**Comment by Ohrimenko1988** [comment]
@tsmaeder On these screenshots you may see that buttons "Run" and "Debug" didn't appear but status bar shows that initialization completed.
![screenshot-Suggestion](https://user-images.githubusercontent.com/22724619/65676042-e2998800-e057-11e9-8982-a9dc915e69cf.png)

Here how it should look like:
![Screenshot from 2019-09-26 12-08-29](https://user-images.githubusercontent.com/22724619/65676117-fc3acf80-e057-11e9-82bf-e958665c9df6.png)

This screencast confirmes that LS initialization was started and completed (according to status bar)
![screencast](https://user-images.githubusercontent.com/22724619/65676600-dc57db80-e058-11e9-8371-547b24784410.gif)

### Browser log
[browserlogs-Suggestion.txt](https://github.com/eclipse/che/files/3657039/browserlogs-Suggestion.txt)

### Other possible logs
[logs-and-configs.zip](https://github.com/eclipse/che/files/3657043/logs-and-configs.zip)

**Comment by tsmaeder** [comment]
Sorry, but I cannot reproduce this issue: I cannot make che on minishift work, and I don't have the necessary resources (memory) on my che.openshift.io account.
When I try the scenario on a smaller workspace (java-maven), the "unexpected" suggestions go away when the project is fully analysed by the language server.

**Comment by tsmaeder** [comment]
The video (please don't use animated gifs, I cannot skip over the irrelevant parts) seem to indicate that the system is under high load. One possiblity I can guess at is that the system is under high load and the language server calls are timing out. Can you reproduce this under normal load?

**Comment by tsmaeder** [comment]
I tried this on my minshift, and once the projects are imported and the workspace is built, everything works just fine. Had to use che-theia 7.1.0, since this seems the only image that works right now.
That the suggestions are not what you might expect while the system is being initialized is the nature of the beast. Unless someone can give me an indication that this is more than just the system being under too much load, I'm going to close this one.
Newer builds of jdt.ls consume less resources and work more in parallel during startup. We have a task in this sprint to integrate the newest vscode-java.

**Comment by tsmaeder** [comment]
Btw: when building the petclinic sample in the maven container for the first time, maven spends ~6 minutes just downloading stuff. Maybe we should consider something a bit lighter for a "happy path test" (sprint boot is a pig :-))

**Comment by tsmaeder** [comment]
@Ohrimenko1988 We have no way of reproducing this and the info we have does not help in pinpointing the problem. Unless we have more info, I'll have to close this as "cannot reproduce".

**Comment by Ohrimenko1988** [comment]
@tsmaeder I also can't confirm that this problem is actual. Thank you for your investigation.
