### ISSUE TITLE
[TS_SELENIUM] Create a devfile with selenium server inside

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14663]
### Is your enhancement related to a problem? Please describe.
In case when e2e tests develop in the che for launching changes they should be delivered to the local machine or to the CI. For now, it is not possible to launch tests inside workspace.

### Describe the solution you'd like
Create a devfile with selenium server inside

**Comment by rhopp** [comment]
Needed for dogfooding of Che for developing e2e tests.
