### ISSUE TITLE
Error messages are not clear when chectl failed to start che-server

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#14665]
### Is your enhancement related to a problem? Please describe.
Errors messages should be clear.
I faced the following cases:
1. oc content is not set
```bash
  ✖ Verify Kubernetes API
    → Failed to connect to Kubernetes API. Failed to get current Kubernetes cluster: returned null
    👀  Looking for an already existing Che instance
 ›   Error: Failed to connect to Kubernetes API. Failed to get current Kubernetes cluster: returned null
```
2. The current user in context is not an admin and does not have any projects
```bash
$ chectl server:start --platform=minishift  --installer=operator --k8spodreadytimeout=500000
  ✖ Verify Kubernetes API
    → Failed to connect to Kubernetes API. [object Object]
    👀  Looking for an already existing Che instance
 ›   Error: Failed to connect to Kubernetes API. [object Object]
```

So, chectl requires the current context to be set, and the current user should have cluster admin rights. And there is no clue about it in error messages.

**Comment by tsmaeder** [comment]
I'm treating this as a P1: we need to improve error analysis.

**Comment by tsmaeder** [comment]
Closing as duplicate of #14665

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/pull/524/ merged
Error messages are improved.
