### ISSUE TITLE
Document how to set up Gitlab as OpenId Provider in Keycloak for Che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14674]
### Is your task related to a problem? Please describe.
@SDAdham successfully set up Gitlab as OpenId Provider in Keycloak for Che and kindly agreed to contribute such document into Che Docs.

**Comment by sleshchenko** [comment]
cc @rkratky It would be nice if you could point the best place in Che 7 Docs for such information.

**Comment by SDAdham** [comment]
I'll work on it

**Comment by SDAdham** [comment]
I made the changed and committed in https://github.com/eclipse/che-docs/pull/830 , need assistance in reverting a commit that's been done with signed-off with a different email.

**Comment by SDAdham** [comment]
Done
