### ISSUE TITLE
Reset to defaults

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1467]
I was having some issues getting certain things to work on eclipse che server. Workspaces were not loading, IDE would not load project from git, and others I cannot remember. I decided to remove the untarred folder I was running the server from and put a fresh copy from the same tar file. Now everything works again. Not sure what saved data/preferences were causing all these issues but I was wondering if there would be some way to reset che server by deleting all user created data. I know there is a way to do this from the terminal but it would be nice to be able to do this within che IDE running on the web browser. This might also make it easier to track down problem other are having by just telling them to first reset che server back to default. They would lose their workspace(s) though. Wish the was a way to import/restore a workspace. Maybe a feature to export/import workspaces  to dockerhub or other storage service. Will open another issue to ask for this separate.

**Comment by ghost** [comment]
@james10174 by default user data is stored at:

`/storage` - workspaces, user prefs, stacks etc
`/workspaces` - project files

You may take these out of Tomcat to a persistent directory so that updates do not erase them.

**Comment by james10174** [comment]
@eivantsov The persistent is functional but if the information in /storage or /workspace becomes corrupt I think this may cause issues which may be what happen to me. I can manually delete everything from these folders but it would be nice to have this feature built into web browser interface.
