### ISSUE TITLE
Setup a CI to build 3rd party vscode extensions

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14677]
### Is your enhancement related to a problem? Please describe.

Those extensions are only available on the marketplace but we cannot download the vs code extensions directly from the marketplace (https://github.com/eclipse/che/issues/14573)

### Describe the solution you'd like

Setup a build to generate the vsix files and publish them on https://download.jboss.org/jbosstools/vscode/3rdparty/ to make them available for any Che workspace.

**Comment by benoitf** [comment]
related to Theia as well: https://github.com/eclipse-theia/theia/issues/6183

BTW there is not only these 2 extensions AFAIK. We should provide all vscode builtin extensions. (https://github.com/microsoft/vscode/tree/master/extensions)

**Comment by nickboldt** [comment]
@benoitf are you saying we should be building everything from source? If so, ok, yes, that's ultimately better for product support, but ouch, that's a lot of work ;)

@mkuznyetsov this one's for you. could be implemented via Jenkinsfile in a subfolder of https://github.com/redhat-developer/codeready-workspaces/tree/master/dependencies/che-plugin-registry and built in a job in https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/

**Comment by nickboldt** [comment]
WIP in https://issues.jboss.org/browse/CRW-491 

Still missing is that the vsix files we can't ref from MS should be built and published on https://download.jboss.org/jbosstools/vscode/3rdparty/ along with the others we have in https://download.jboss.org/jbosstools/vscode/stable/ that RH builds

**Comment by nickboldt** [comment]
CI now exists. Jenkins job is https://github.com/redhat-developer/codeready-workspaces/blob/master/dependencies/che-plugin-registry/Jenkinsfile-single -> https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging/ (and https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging-experimental/)

But until Che 7.7 plugin registry is updated to use these new files, we should leave this open.

@mkuznyetsov when you have the PR ready for https://github.com/eclipse/che-plugin-registry/pulls please link it from this issue. When it's merged, please close this issue.

**Comment by nickboldt** [comment]
https://github.com/eclipse/che-plugin-registry/pull/334/files merged to update Che 7.7 plugin reg to use dl.jb.o locations for newly built plugins. We can close this now.
