### ISSUE TITLE
Che allows to use URL as id field of cheEditor/chePlugin component in devfile

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14671]
### Describe the bug
https://redhat-developer.github.io/devfile/ documentation says that URL to meta.yaml with Che plugin description should be put into `reference` field. At the same time there was workspace successfully created with URLs to meta.yaml's put into **id** field.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Try to create workspace from next [devfile](https://gist.github.com/dmytro-ndp/7eeccfebc4deeb2fdbdfb27cc8b31170) using chectl:next.

### Expected behavior
There is an error on workspace start.

### Actual behaviour
Workspace had been successfully created with required plugins
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/176/console

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by tsmaeder** [comment]
Why do we care about this being possible if it works?

**Comment by dmytro-ndp** [comment]
@tsmaeder:
1) it shouldn't work according to documentation
2) workspace doesn't work properly if URL is set in **id** field of **cheEditor** components

**Comment by sleshchenko** [comment]
@tsmaeder It indicates that there is some valiation issue on Che Server side.
Che Server does not expect `id` to contain URL and all consequences are not known. I believe it must be fixed.
