### ISSUE TITLE
Update registries RHEL images

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14678]
### Is your enhancement related to a problem? 

RHEL images of the plugin and devfile registries are not been updated to UBI8

### Describe the solution you'd like

Update 
- https://github.com/eclipse/che-plugin-registry/blob/master/Dockerfile.rhel
- https://github.com/eclipse/che-devfile-registry/blob/master/build/dockerfiles/Dockerfile.rhel

**Comment by nickboldt** [comment]
As part of this I'll be renaming the files to rhel.Dockerfile so that they get correct lang server support in vscode and Che/CRW.

**Comment by nickboldt** [comment]
Updated to include rhel.* files 2 months ago:

https://github.com/eclipse/che-plugin-registry/tree/master/build/dockerfiles
https://github.com/eclipse/che-devfile-registry/tree/master/build/dockerfiles
