### ISSUE TITLE
Workspace import/export

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1468]
Would like to be able to export/import workspaces to dockerhub or other storage service from che server.

**Comment by ghost** [comment]
@james10174 we're working on making it possible to store workspace snapshots on DockerHub or any other Docker registry. This will be regulated in Che configuration.

**Comment by james10174** [comment]
@eivantsov Will there be an interface accessible from web browser to do this without having to modify server configuration files such as che.conf?

**Comment by TylerJewell** [comment]
No plans to add it.  We do accept pull requests.

There is a large number of system-related configuration items that could be added into the dashboard.  It is a substantial project - but it needs to eventually be there.

Some of the aspects related to pushing snapshots into a registry are outside of Che's control, such as dealing with configuration of your Docker daemon. We would only be able to control the items that are in the configuration file.

I don't see us working on any dashboard-related configuration of che.properties for awhile. We want to see what are the most common usages and then we can look at incorporating those over time.

**Comment by james10174** [comment]
@eivantsov Let me know if you have any work done on this already. I want to try to add this but don't want to repeat any work already done. My plan is to have an environment variable in che.properties that will enable/disable a button or label in dashboard to allow saving the workspace. This would let the feature only be available by enabling it(not default) and would make things easier having most configuration for repository done in the che.properties file not the IDE.
Really thinking of a simple save and restore local repository at first.

**Comment by TylerJewell** [comment]
This capability was added in 4.3.
