### ISSUE TITLE
[TS_SELENIUM] Update logger for automatically log class name and method

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#14689]
### Is your task related to a problem? Please describe.
For now, for log class name and method we should type they manually, for example: ```"Logger.debug('OcpLoginPage.openLoginPageOpenShift');"```

### Describe the solution you'd like
Use solution described in the comment https://github.com/eclipse/che/pull/14686#pullrequestreview-294217772

**Comment by tolusha** [comment]
@Ohrimenko1988 
Should be closed?

**Comment by Ohrimenko1988** [comment]
@tolusha No, I am working on it.

**Comment by Ohrimenko1988** [comment]
I have investigated this task and here results:
It is not possible to get called method name, we have a possibility to obtain just class name by providing ```"this"``` to the arguments and call ```this.constructor.name``` from inside of the Logger. 

So as I see, for now, the most possibility for updating are next:
1) Make "Logger" as a regular class instead of an abstract which uses now.
2) Create instances of the ```Logger``` class in the each pageobject constructors and provide ```this`` inside
3) Rework the ```Logger``` methods output by using ```this.constructor.name``` for automatically class name logging.

As a result, we will have the next signature inside of pageobjects:
```logger('methodName', 'text')```
