### ISSUE TITLE
Workspace ram

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1469]
I would like to be able to adjust workspace ram after it has been created while workspace is stopped.

**Comment by TylerJewell** [comment]
This was discussed over at https://github.com/eclipse/che/issues/1088.  I'd like to think about providing a range of Docker RAM configuration items within the dashboard where configuring workspaces.

#1088

**Comment by ghost** [comment]
@james10174 closing this one, let's track https://github.com/eclipse/che/issues/1088
