### ISSUE TITLE
Tab with Che Theia crashed

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14692]
### Describe the bug
Editors ```docker.io/eclipse/che-theia:next ``` and ```docker.io/eclipse/che-theia:latest``` crashing my browser tab. ````docker.io/eclipse/che-theia:7.1.0```` is working
![Знімок екрана  о 15 21 56](https://user-images.githubusercontent.com/1614429/65773399-8bb9ae80-e13c-11e9-9ba5-a60407be8397.png)
![Знімок екрана  о 15 05 09](https://user-images.githubusercontent.com/1614429/65773403-8e1c0880-e13c-11e9-9400-ca0e270e5e4c.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
- Deploy latest Che
- Start workspace from GO or from TypeScript/Mongo stack
- Wait for Theia to loading
### Expected behavior
Theia loaded

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
CC @ibuziuk @l0rd

**Comment by benoitf** [comment]
Tried with fresh minishift
I don't reproduce

with go stack:
![image](https://user-images.githubusercontent.com/436777/65775751-11d7f400-e141-11e9-82b4-33e784ef7ef1.png)


with java stack:
![image](https://user-images.githubusercontent.com/436777/65775723-0389d800-e141-11e9-897b-2d6f9a151b41.png)

**Comment by skabashnyuk** [comment]
I confirm it's working on crc. After login as kubeadmin
```
oc login -u kubeadmin -p BMLkR-NjA28-v7exC-8bwAk https://api.crc.testing:6443
```
and chrctl setup ```chectl server:start  -p crc```
```
chectl --version                                                                                                   
chectl/0.0.20190927-next.56ed3cc darwin-x64 node-v10.16.3```

**Comment by benoitf** [comment]
it seems some ppl have issues but currently I have no idea on what is blocking

**Comment by skabashnyuk** [comment]
@benoitf I think on my side the issue was in the fact that I've used
```
CHE_WORKSPACE_PLUGIN__REGISTRY__URL=https://che-plugin-registry.openshift.io/v3
CHE_WORKSPACE_DEVFILE__REGISTRY__URL=https://che-devfile-registry.openshift.io/
```
instead of deploying the latest versions.

**Comment by tsmaeder** [comment]
I still have this issue. How do I update my che instance to fix this without losing my workspaces?

**Comment by skabashnyuk** [comment]
@tsmaeder what is the value of CHE_WORKSPACE_PLUGIN__REGISTRY__URL and CHE_WORKSPACE_DEVFILE__REGISTRY__URL ?
 If you are running plugin and devfile registries you should make sure they are up to date.

**Comment by benoitf** [comment]
@tsmaeder I think it's because che-theia image and the `plugin's images` are not using the same theia codebase

like using che-theia:next with a vscode-java plugin image using under the hood che-theia:7.0.0 for example.

As the protocol has changed in theia upstream for plugins, I suspect the main instance can't communicate anymore with sidecar containers.

**Comment by tsmaeder** [comment]
@benoitf I understand the problem, but not how to fix it without data loss.

**Comment by benoitf** [comment]
@tsmaeder please provide the devfile of the workspace or ensure that it's using next/next everywhere or (latest/latest) (and that there is a theia editor inside the devfile as well)

**Comment by skabashnyuk** [comment]
>@benoitf I understand the problem, but not how to fix it without data loss.

you need to redeploy your plugin and devfile registry with a fresh one.

**Comment by tsmaeder** [comment]
But I haven't deployed any registries. Is there a chectl incantation that will fix the problem?

**Comment by skabashnyuk** [comment]
>But I haven't deployed any registries. Is there a chectl incantation that will fix the problem?

I think the only solution for that is just to redeploy the whole che. What was my way to fix this issue.

**Comment by skabashnyuk** [comment]
not reproduced for me.
