### ISSUE TITLE
Review chectl dependencies licenses

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14696]
### Is your enhancement related to a problem? Please describe.

chectl is still a che-incubator project and has a some third party dependencies for which we haven't checked the licenses yet and that prevents us from:
- include the git repo in the eclipse github organisation
- consider it for productization

### Describe the solution you'd like

We should review the licenses of the third party dependencies and list those that are not compatible:

- GNU GPL 2.0
- GNU LGPL
- Sun Binary Code License Agreement

This issue is only about reviewing the licenses. If there are some third party dependencies that do not have valid licenses we should open separate issues to address that.

**Comment by tolusha** [comment]
It would be nice if you set the severity as well.

**Comment by benoitf** [comment]
Hello,

I did a deep review on all dependencies (and transitive dependencies)


install synp tool, convert yarn.lock to package-lock.json
drag and drop file on https://clearlydefined.io/workspace
use 'sort by license'

licenses are compliant with EPL : BSD, Apache 2.0, ISC, MIT

![image](https://user-images.githubusercontent.com/436777/66032356-904be180-e505-11e9-952e-83a4fcd17197.png)

**Comment by l0rd** [comment]
@benoitf you mean that every dependency has a license and that none has GPL or LGPL?

**Comment by l0rd** [comment]
Is it possible to export/share the result?

**Comment by benoitf** [comment]
@l0rd yes every dependency is compliant (no GPL/LGPL/unknown license)

about sharing I don't know (this is why I added steps to reproduce)
What I can do is to share the package-lock.json so it's just a simple drag and drop to do on https://clearlydefined.io/workspace

**Comment by benoitf** [comment]
[package-lock.json.zip](https://github.com/eclipse/che/files/3680505/package-lock.json.zip)

I've added zipped file of package-lock.json (can't add .json directly)

Sharing URL from clearlydefined doesn't work as the URL is too long

**Comment by l0rd** [comment]
ok cool thanks @benoitf I am closing this issue since the dependencies licenses have been analysed and no further action seems necessary.

cc @nickboldt

**Comment by sleshchenko** [comment]
@l0rd Should we make sure that all dependencies have CQs?

**Comment by l0rd** [comment]
@sleshchenko yes that's next step. But we do not have to do changes in code. It's just paperwork now.

**Comment by nickboldt** [comment]
Paperwork that blocks doing a release of an Eclipse.org project, if you want to be technical. :)

If you're an Eclipse.org project, and your CQs are not all submitted and approved, you won't pass the release review.

And you might jeopardize the ability to use that code in a downstream product... even if the license terms are all happy ASL/MIT/EPL stuff.

**Comment by nickboldt** [comment]
Reopening. Added second part of this requirement to the title:

"... & verify all deps have matching CQs in Eclipse IPzilla"

**Comment by benoitf** [comment]
I wouldn't hijack this issue. It's done. Another one for CQ should be opened

**Comment by benoitf** [comment]
this issue is closed. If another item, please open a new one, not changing title. thx.

**Comment by l0rd** [comment]
CQ created https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20971
