### ISSUE TITLE
Cannot build che-theia generator from master branch

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14706]
### Describe the bug

As part of #https://github.com/eclipse/che/issues/13765 I'm trying to make it possible to build the che-theia generator decoupled from the overall che-theia + theia + theia-dev + all the other containers.

To that end, I'm updating the build.sh script in the theia-dev dockerfile folder so that instead of assuming generator is already built, I can build it myself.

However, it seems that there are missing yarn/npm deps when I try to build it locally.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.2.0

### Steps to reproduce

```
base_dir=/tmp
LOCAL_ASSEMBLY_DIR="${base_dir}"/generator
mkdir -p ${LOCAL_ASSEMBLY_DIR}

CHE_THEIA_GENERATOR_PACKAGE_NAME=eclipse-che-theia-generator.tgz
CHE_THEIA_GENERATOR_PACKAGE="${LOCAL_ASSEMBLY_DIR}/${CHE_THEIA_GENERATOR_PACKAGE_NAME}"

CHE_THEIA_GIT_BRANCH_NAME=7.2.0
CHE_THEIA_GITHUB_REPO=eclipse/che-theia
if [[ -d theia-source-code/che-theia ]]; then rm -fr theia-source-code/che-theia; fi; mkdir -p theia-source-code
echo "Check out https://github.com/${CHE_THEIA_GITHUB_REPO} from branch ${CHE_THEIA_GIT_BRANCH_NAME} to ./theia-source-code/che-theia ..."
git clone -q --branch ${CHE_THEIA_GIT_BRANCH_NAME} --single-branch --depth 1 https://github.com/${CHE_THEIA_GITHUB_REPO} theia-source-code/che-theia
mv theia-source-code/che-theia/generator/* ${LOCAL_ASSEMBLY_DIR}/ && \
rm -fr theia-source-code/che-theia

cd "${LOCAL_ASSEMBLY_DIR}" && echo "Build Che Theia generator in ${LOCAL_ASSEMBLY_DIR} ..."
```

Now if I do `yarn prepare` as noted in https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia-dev/build.sh#L38

I get this error:

https://paste.fedoraproject.org/paste/OCWC3pfUFzggz17UQhpgIg

But this compiles fine:

`yarn && yarn pack --filename $CHE_THEIA_GENERATOR_PACKAGE_NAME`

```
Test Suites: 15 passed, 15 total
Tests:       72 passed, 72 total
Snapshots:   0 total
Time:        11.812s
Ran all test suites.
Done in 23.22s.
Done in 39.34s.
yarn pack v1.16.0
success Wrote tarball to "eclipse-che-theia-generator.tgz".
```

**Comment by tolusha** [comment]
@nickboldt 
```bash
git co 7.2.0
cd generator
yarn prepare

...
Test Suites: 15 passed, 15 total
Tests:       72 passed, 72 total
Snapshots:   0 total
Time:        8.356s
Ran all test suites.
Done in 18.45s.
```

**Comment by tolusha** [comment]
I see at first it requires to build project with yarn.

**Comment by evidolob** [comment]
@nickboldt Can we close this? Assuming that you can build generator.

**Comment by nickboldt** [comment]
out of date.
