### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#1470]
Does github require oauth? I have been having trouble getting push(you are not authorized error) and import with ssh to work. Wh I switched to bitbucket.org and everything works fine. I get the following trying to setup github. Do I have to modify che.conf to get this to work?

![image](https://cloud.githubusercontent.com/assets/16562450/15899645/0ecf5726-2d62-11e6-8711-2949c7aed63a.png)

**Comment by ghost** [comment]
@james10174 You need to provide client ID and client secret in che.properties which you get from a registered application on GitHub

**Comment by james10174** [comment]
@eivantsov Is this a github requirement or eclipse che requirement? Bitbucket I do not need to modify github che.properties at all.

**Comment by james10174** [comment]
@eivantsov OK adding clientid and clientsecret to che.properties fixed it. Still not able to use the bithub icon circled in image above. This did work on codenvy though.

**Comment by ghost** [comment]
@james10174 after adding client and secret to che.properties, same error?

**Comment by james10174** [comment]
@eivantsov Sorry thought I had checked that. It works now that the che.properties has clientid and clientsecret.
