### ISSUE TITLE
Fix Java selenium E2E tests which check integration with GitHub

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14711]
There are two Java selenium tests constantly failing :
- ImportProjectFromGitHubTest
- AuthorizeOnGithubFromDashboardTest

For example: https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/2461/Selenium_20tests_20report/

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] ocp.sh script

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [X] other: Codenvy CI

### Related issue
https://github.com/eclipse/che/issues/7899

**Comment by artaleks9** [comment]
It was created new GitHub test account and registered needed OAuth applications. New Client/Secret IDs were added to the qa-slaves on the https://ci.codenvycorp.com/view/qa-nightly/.
Now it works as expected.
