### ISSUE TITLE
[chectl] Server start not working on Docker Desktop on Windows 10

### ISSUE THREAD

**Issue by Boereck** [eclipse-che/che#14718]
### Describe the bug
Starting che via chectl on Docker Desktop (version 2.1.0.3, Kubernetes version 1.14.6) on Windows 10, via command `chectl server:start -p docker-desktop` leads to the following output:

```
  √ Verify Kubernetes API...OK
  √ 👀  Looking for an already existing Che instance
    √ Verify if Che is deployed into namespace "che"...it is not
  > ✈️  Docker Desktop preflight checklist
    √ Verify if kubectl is installed
    × Verify if kubectl context is Docker Desktop
      → E_PLATFORM_NOT_READY: current kube context is not Docker Desktop context. Found docker-desktop
      Verify remote kubernetes status
      Verify if nginx ingress is installed
      Installing nginx ingress
      Verify domain is set
 »   Error: E_PLATFORM_NOT_READY: current kube context is not Docker Desktop context. Found docker-desktop
```

### Che version
Latest version of chectl. `chectl --version` prints `chectl/0.0.20190927-next.56ed3cc win32-x64 node-v10.16.3`

### Steps to reproduce
Call `chectl server:start -p docker-desktop` running Docker Desktop on Windows 10

### Expected behavior
Startup of the che server.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Output of `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
Thanks for the report @Boereck 
it seems docker has a different kubernetes context on some installations.

A pull request has been provided
