### ISSUE TITLE
Opened in the Editor files tabs are not restored after workspace restarting

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#14717]
### Describe the bug
After workspace restarting files tabs opened in the **Editor** are not restored.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create and start a workspace from any devfile with a project.
2. Click on **Projects** tab.
3. Open in the **Editor** any file.
4. On the **Dashboard** open **Workspaces** page and stop/start the workspace in **Workspaces list** page.
5. Open the workspace and check files tabs in the **Editor**.

### Expected behavior
Opened previously files tabs are opened in the **Editor**. 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screencasts
![screencast-che-eclipse-che 10 33 177 124 nip io-2019 09 30-17_24_13 (1)](https://user-images.githubusercontent.com/7760565/65888577-7052db80-e3a8-11e9-8eaf-2d6f0438d092.gif)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] ocp.sh
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
The question is where Theia stores opened editors and if it is kept when workspace is stopped.

[1] https://spectrum.chat/theia?tab=posts

**Comment by l0rd** [comment]
It doesn't look like a bug (has that ever worked on Che with theia?) but an enhancement with severity/p2.

**Comment by vzhukovskii** [comment]
@tolusha theia stores the application state in browser local storage, but in che-theia there is our own implementation of storage service that stores application state on file system. I suppose, that this configuration files don't serialize and don't store somewhere. And we need to provide mechanism to provision them into theia container.

**Comment by SkorikSergey** [comment]
This feature works well on Eclipse Che 7.44.0.
