### ISSUE TITLE
Fix Happy path tests on minikube on CRW CCI instances due to "plugin runtime crashed unexpectedly" error

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14714]
### Describe the bug
There was an error "Plugin runtime crashed unexpectedly" in time of running Happy path tests on minikube within CRW CCI instances with 16Gb RAM / 8 CPUs:
- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-master-check-E2E-Happy-path-tests-against-K8S/155
- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/2066/
```
  Validation of workspace build and run
    ✓ Build application (37424ms)
After clicking to the "Terminal" -> "Run Task ..." the "Quick Open Container" has not been displayed, one more try
    1) Run application


  9 passing (15m)
  1 pending
  1 failing

  1) Validation of workspace build and run
       Run application:
     TimeoutError: Waiting until element is visible
Wait timed out after 300173ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: Waiting until element is visible
      at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at DriverHelper.<anonymous> (/tmp/e2e/utils/DriverHelper.ts:100:61)
      at Generator.next (<anonymous>)
      at fulfilled (/tmp/e2e/dist/utils/DriverHelper.js:17:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

![screenshot-Run_application](https://user-images.githubusercontent.com/1197777/65872741-f3b10480-e389-11e9-9e09-60527ecde205.png)

The issue is related to https://github.com/eclipse/che/issues/14551

The problem was not reproduced on instance 32 GB RAM / 16 CPUs.

### Workspace devfile
https://github.com/eclipse/che/blob/78e35343504ee33e6aa5ed0c3a35d07b601db62e/e2e/files/happy-path/happy-path-workspace.yaml#L30

### Server logs
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-master-check-E2E-Happy-path-tests-against-K8S/155/artifact/logs-and-configs/

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Happy path E2E tests scenario.

### Runtime
   - [x] minikube 1.1.1:
```
/usr/local/bin/minikube start \
      --vm-driver=none \
      --cpus 4 \
      --memory 12288 \
      --logtostderr
```

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other: CRW CCI
   - [ ] other: please specify

**Comment by tolusha** [comment]
@dmytro-ndp 
Could you clarify the status? Are you working on fixing the error in question or fixing happy-path tests?

**Comment by tolusha** [comment]
I personally don't think it is related with resources allocated for tests.

**Comment by mmorhun** [comment]
I've taken a look at Che Theia logs and can say, that essential for the crash is only one line:
```
root ERROR [hosted-plugin: 133] IPC exited, with signal: SIGKILL, and exit code: null
```
Which actually means that NodeJS instance with plugins have got `sigkill` signal.

Taking into account, that Che Theia with plugins node is running in a separate container, the only source of the `sigkill` signal is Linux system (unless a user does it manually, which is not the case for our tests on CI). Based on the above, seems we reached some resources limit, probably OOM.

**Comment by dmytro-ndp** [comment]
@tolusha: I am trying to work around resources to start minikube/workspace, to find better solution than to use more powerful instance of 32GB RAM/16 CPUs.

**Comment by tolusha** [comment]
@mmorhun 
good assumption
@dmytro-ndp 
Could you try to increase a memory limit for a theia container? I suppose the default value is 512Mi

**Comment by dmytro-ndp** [comment]
There is 4Gi

**Comment by tolusha** [comment]
I mean
```
  - id: eclipse/che-theia/latest
    type: cheEditor
    memoryLimit: 768Mi
```

**Comment by dmytro-ndp** [comment]
Error was reproduced on machine with 32 GB RAM / 16 CPUs https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/206/

**Comment by dmytro-ndp** [comment]
The issue was closed accidentally.

**Comment by mmorhun** [comment]
@dmytro-ndp could you please share the devfile from which that workspace was created?

**Comment by dmytro-ndp** [comment]
It's on description of issue: https://github.com/eclipse/che/blob/78e35343504ee33e6aa5ed0c3a35d07b601db62e/e2e/files/happy-path/happy-path-workspace.yaml

**Comment by mmorhun** [comment]
@dmytro-ndp sorry I wasn't clear enough... I meant the one with increased memory limits...
