### ISSUE TITLE
Allow to configure CHE_LIMITS_USER_WORKSPACES_RUN_COUNT and namespace via CheCluster CRD

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14710]
### Is your task related to a problem? Please describe.
Follow up of https://github.com/eclipse/che/issues/13488#issuecomment-527702807

### Describe the solution you'd like
```CHE_LIMITS_USER_WORKSPACES_RUN_COUNT``` and namespace configurable via CheCluster CRD

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by tolusha** [comment]
I set severity `P1` accordingly to #13488

**Comment by skabashnyuk** [comment]
This is already possible to do.
