### ISSUE TITLE
[Happy Path] Mount predownloaded dependencies also into java sidecar container

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14723]
The petclinic sample used in the happy path tests is very heavy on dependencies. Using a lighter sample would put less load on our systems and produce less false failures.

**Comment by l0rd** [comment]
@tsmaeder do you think that's only about the dependencies? If that's the case one alternative would be to use a stack image with the dependencies for that particular project included.
@rhopp @dmytro-ndp what do you think? If you are ok with @tsmaeder analysis (a smaller project == less false positives) let's go for it.

**Comment by tsmaeder** [comment]
I did a mvn clean install and on my 1gb symmetric line, it took ~6 mins to just download all the dependencies. As long as we don't have some prepopulated .m2 volume on the language support container, we _will_ need to download everything when first starting the workspace.

**Comment by Ohrimenko1988** [comment]
The "petclinik" sample was choose for checking of application with database behavior.
All required dependencies already has been packed into maven image
```
  - type: dockerimage
    alias: maven-container
    image: quay.io/eclipse/happy-path:nightly
    env:
```
Here is devfile: https://github.com/eclipse/che/blob/master/e2e/files/happy-path/happy-path-workspace.yaml
Please use it for testing and you will avoid download delays

**Comment by tsmaeder** [comment]
What you describe may work for the maven container, but the ~/.m2 in the java tooling sidecar is still empty: When you start the java language server, it will still download the dependencies.

**Comment by rhopp** [comment]
Thanks @tsmaeder , what you are saying makes sense.
Somebody from our team will take a look at that and we will modify the devfile to mount predownloaded dependencies also into ~/.m2 in java tooling sidecar.

**Comment by rhopp** [comment]
Relevant issue to not use predownloaded bits at all (only in nightly runs) - #15454
