### ISSUE TITLE
Include yarn in default nodejs stack

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14720]
### Is your enhancement related to a problem? Please describe.
Include yarn in default nodejs stack

### Additional context
https://github.com/eclipse/che/issues/13806

**Comment by slemeur** [comment]
cc @tsmaeder

**Comment by l0rd** [comment]
cc @tsmaeder

**Comment by tsmaeder** [comment]
@l0rd @slemeur the dev image is supposed to be able to run the example. As I understand it, that example does not require yarn, so for me we should not include yarn.

**Comment by tsmaeder** [comment]
After discussing this with @slemeur & @l0rd, we have decided to include an example based on yarn.

**Comment by svor** [comment]
The devfile is here https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/nodejs-yarn/devfile.yaml
