### ISSUE TITLE
Workspace fails to start/open. Caused by `Unknown error` during websocket connection establishing

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14726]
### Describe the bug
When try to open/start a workspace, it fails with `Unknown error has happened, try to reload page` message. Reload of the page doesn't help.

### Che version
nightly

### Steps to reproduce
1. Open a workspace
2. Work in it some time
3. Stop the workspace
4. Try to start it again

### Expected behavior
Workspace is started as usual

### Runtime
minishift

### Screenshots
![unknown-error](https://user-images.githubusercontent.com/15607393/65960275-cc773780-e45c-11e9-8b13-80ed10e0f5b3.png)

Screen cast

![unknown-error](https://user-images.githubusercontent.com/15607393/65960756-d51c3d80-e45d-11e9-8621-3cfbac972a81.gif)

### Additional context
No error logs on Che master side.

**Comment by akurinnoy** [comment]
@mmorhun, I have just faced same issue on minikube on single-user Che.

**Comment by mmorhun** [comment]
Yes, seems keycloak token is not the problem, because relogin didn't help...

**Comment by mmorhun** [comment]
But closing and opening browser again helped.

**Comment by sleshchenko** [comment]
Something is wrong in cookies or local cache since the incognito window helped in @akurinnoy case.

**Comment by l0rd** [comment]
@evidolob @olexii4 @benoitf any idea? Is this a regression?

**Comment by olexii4** [comment]
@mmorhun, I have the same issue on minikube on single-user CHE. 
I tried to clean cookies and local cache - didn't help.

**Comment by evidolob** [comment]
I faced same problem with Che-Theia IDE, for some reasons browser cannot establish websocket connection with Theia backend. See screenshot:
<img width="1440" alt="Screen Shot 2019-10-07 at 14 18 52" src="https://user-images.githubusercontent.com/929743/66307767-f8d3fd80-e90d-11e9-9bd3-e79533f52ce2.png">

**Comment by AndrienkoAleksandr** [comment]
+1 Faced with this issue.

**Comment by tsmaeder** [comment]
I might have filed a duplicate: https://github.com/eclipse/che/issues/15041

**Comment by l0rd** [comment]
If it can help I've faced this issue as well and when I've switched into chrome incognito mode and I could start the workspace.
