### ISSUE TITLE
Happy path test maven image does not have real user

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14722]
The maven image used in the happy path tests (https://github.com/eclipse/che/blob/master/e2e/files/happy-path/happy-path-workspace.yaml) does not have the workaround needed to work with arbitrary users. This can lead to all kinds of unexpected results.

**Comment by l0rd** [comment]
That's a really good catch and something we need to fix asap. 

@rhopp @dmytro-ndp where is the Dockerfile for `bujhtr5555/maven-with-artifacts:latest`? Is it possible to use `quay.io/eclipse/che-java11-maven` or to use it as a base image?

**Comment by Ohrimenko1988** [comment]
@l0rd Yes, we can use ```quay.io/eclipse/che-java11-maven``` as a base image.  In the ```maven-with-artifacts``` image we add maven artifacts for reducing tests execution time. So we may get the ```quay.io/eclipse/che-java11-maven``` image, add necessary artifacts and build our own image.

 I have created issue for this task https://github.com/eclipse/che/issues/14737

**Comment by rhopp** [comment]
Done as part of https://github.com/eclipse/che/issues/14737
