### ISSUE TITLE
Provide fully equipped release candidate of chectl and che-operator for pre-release testing

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14725]
### Is your enhancement related to a problem? Please describe.
During pre-release testing of Eclipse Che, QE team is usually testing `eclipse/che-server:rc` image being installed by the command of **chectl** from `--channel=next`:
```
./install_chectl.sh --channel=next
  /usr/local/bin/chectl server:start \
    --platform=minikube \
    --cheimage=eclipse/che-server:rc
```
In this case only **che-server** is of pre-release version. 
Other artifacts like **chectl**, **che-theia**, **che plugins** are of **next**/**latest** versions, instead of release candidates.

### Describe the solution you'd like
We can have `--channel=rc` of **chectl**, which will install Eclipse Che, and start workspaces by using release candidates of **che-server**, **che-theia**, **che plugins** etc by default.

### References
https://github.com/eclipse/che/issues/14650

**Comment by benoitf** [comment]
AFAIK you can provide list of some versions/images for helm ?

**Comment by dmytro-ndp** [comment]
You are right.
The issue is also about providing pre-release version of helm, which points to **rc** tags of che-theia, che plugins images. It will require having such images as well.

**Comment by l0rd** [comment]
I am not sure I understand the goal. Is it for the day of the Che release?

**Comment by dmytro-ndp** [comment]
Indeed, it's needed for pre-release testing of Eclipse Che: there is actually `che-server:rc` image tested with `chectl` installed from *next* channel. `latest` images of `che-theia` and `plugins` images are used.
The point is to test *final* bits of Che images/chectl (kinda release candidates) before publishing it as a release versions.

**Comment by nickboldt** [comment]
I'm setting this as a milestone 7.11 target since it would be great to have it in place for the next release (next week). @tolusha do you think you can rework the make-release scripts for chectl and operator so they can push RC versions?

**Comment by nickboldt** [comment]
I can make sure the release process is documented / assigned correctly for the 7.11 release issue if we make this change for 7.11.

**Comment by tolusha** [comment]
@dmytro-ndp @mkuznyetsov 
To be able to prepare `che-operator` and `chectl` RC it is needed to have a corresponding branch in `che`. 
For instance, in case of 7.11.0 release I will need 7.11.0 branch in che. Is it possible?

**Comment by tolusha** [comment]
@nickboldt 
We don't need RC anymore, right?

**Comment by nickboldt** [comment]
Correct -- with the new plan for Che 7.12 automated release (go directly to R, do not pass RC QE gate, do not collect $200) we don't need this.

But having a tool to generate PRs for community operatorhub via a single commit would be great.
Whatever information you need in that PR would be pushed to some file in the new che-release repo, in which we plan to have also the code to orchestrate the 9 steps in the release pipeline

**Comment by nickboldt** [comment]
From @tolusha :+1: 

> There is misunderstanding.
> We already have script to generate PR for operator hub
> https://github.com/eclipse/che-operator/blob/master/olm/prepare-community-operators-update.sh
