### ISSUE TITLE
[plugin registry] Improvements to build process

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14736]
### Is your enhancement related to a problem? Please describe.

Based on feedback in https://github.com/eclipse/che-plugin-registry/pull/232 there are some things we can do to to improve the build process.

### Describe the solution you'd like

* move dockerfiles and related meta files (*.repo) into `build/dockerfiles/`
* remove `Listen 80,Listen 8080` replacement instruction
* probably not needed: `    chmod a+rwX /etc/httpd/conf /run/httpd`
* For the non-rhel dockerfile, this could be implemented as an `ARG` (`ONLY_LATEST=true`) to avoid having to edit the dockerfile for specific builds.

**Comment by benoitf** [comment]
you'll use build scripts to copy some content to have access to other files (like Che) or you'll keep root docker context

also I would suggest `build/dockerfile/rhel/` so you've dedicated files for rhel there and you can name the Dockerfile `Dockerfile` for your vscode extension

**Comment by nickboldt** [comment]
This was all done some time ago. 

https://github.com/eclipse/che-plugin-registry/tree/master/build/dockerfiles
