### ISSUE TITLE
[plugin registry] Improve the way che-theia and che-machine-exec latest folders are maintained

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14735]
The Che Machine Exec plugin for 7.2.0 is not the same as the one for Latest, despite the fact that v7.2.0 is the latest.

![image](https://user-images.githubusercontent.com/227597/65992231-d00abe80-e45c-11e9-8c56-01181cc1b877.png)

This suggests that someone is manually updating 7.2.0 and latest SEPARATELY and because humans gonn' hume, someone forgot to update the latest with the changes in 7.2.0.

Suggested better solutions:

a) get a bot that does copies changes in the largest versioned folders for:

* `v3/plugins/eclipse/che-theia/7.x.0`
* `v3/plugins/eclipse/che-machine-exec-plugin/7.x.0`

into 

* `v3/plugins/eclipse/che-theia/latest`
* `v3/plugins/eclipse/che-machine-exec-plugin/latest`

b) remove the `/latest/` folders entirely, and instead during the build of the plugin registry, figure out the version that is latest (eg., from timestamp on the file or firstPublicationDate in the meta.yaml) and GENERATE the `/latest/meta.yaml` right then and there.

This would allow a :next or :nightly to be the latest, if you're doing a CI build rather than a 7.x.0 release.

**Comment by nickboldt** [comment]
Related issue #14732

**Comment by amisevsk** [comment]
Closing as this should be resolved with https://github.com/eclipse/che-plugin-registry/pull/260
