### ISSUE TITLE
[regression] Ephemeral workspaces cannot load plugins

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14749]
### Describe the bug
When running a workspace in ephemeral mode on Che 7.2, no plugins can be loaded.

This appears to be due to a change in how volumes are mounted. In non-ephemeral mode, we have
```
plugins, subpath workspaceyo32yti5y6vqno7a/plugins/ → /plugins
```
whereas in ephemeral mode, the mount is
```
plugins → /plugins
```
which causes the plugin artifacts to be stored at `/plugins/<workspace-id>/plugins/sidecars/redhat_java_latest` instead of `/plugins/sidecars/redhat_java_latest`

### Che version

 - [x] latest 7.2

### Steps to reproduce
Create a workspace, toggle the "ephemeral mode" toggle on the overview page, and start it.

### Expected behavior
Plugins volume is mounted with a subpath.

**Comment by amisevsk** [comment]
This is a blocker for rolling Che 7.2 out to production.

**Comment by benoitf** [comment]
@amisevsk what is the team that is handling the workspace mounts part ? osio or platform ?
to make assignee

**Comment by amisevsk** [comment]
@benoitf The issue is caused by https://github.com/eclipse/che/pull/14539 I believe, but I'm currently taking a look.

**Comment by AndrienkoAleksandr** [comment]
https://github.com/eclipse/che/pull/14539 I think so too.

**Comment by l0rd** [comment]
@amisevsk are you able work on this (without compromising the other tasks for this sprint)?

**Comment by amisevsk** [comment]
@l0rd PR open: https://github.com/eclipse/che/pull/14768

**Comment by amisevsk** [comment]
Fix available in master.

**Comment by dmytro-ndp** [comment]
The issue wasn't reproduced on Single Che 7.4.0 RC installed on minikube.
