### ISSUE TITLE
[chectl] chectl didn't respect k8spodreadytimeout in case it failed to check Che status

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14743]
### Describe the bug
Next command:
```
/usr/local/bin/chectl server:start --k8spodreadytimeout=180000 \
  -t=/mnt/hudson_workspace/workspace/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/deploy/ \
  --platform=minikube \
  --listr-renderer=verbose \
  --cheimage=maxura/che-server:master
```
failed because of error:
```
14:39:06 [07:39:06] Verify Kubernetes API [started]
14:39:06 [07:39:06] Verify Kubernetes API...OK [title changed]
14:39:06 [07:39:06] Verify Kubernetes API...OK [completed]
14:39:06 [07:39:06] 👀  Looking for an already existing Che instance [started]
14:39:06 [07:39:06] Verify if Che is deployed into namespace "che" [started]
14:39:06 [07:39:06] Found running che deployment [started]
14:39:06 [07:39:06] Found running che deployment [completed]
14:39:06 [07:39:06] Found running plugin registry deployment [started]
14:39:06 [07:39:06] Found running plugin registry deployment [completed]
14:39:06 [07:39:06] Found running devfile registry deployment [started]
14:39:06 [07:39:06] Found running devfile registry deployment [completed]
14:39:06 [07:39:06] Verify if Che is deployed into namespace "che" [completed]
14:39:06 [07:39:06] Check Che server status [started]
14:39:06 [07:39:07] Check Che server status [failed]
14:39:06 [07:39:07] → E_CHECK_CHE_STATUS_FAIL - Failed to check Che status (URL: http://che-che.10.0.100.48.nip.io). E_CHE_API_UNKNOWN_ERROR - Endpoint: http://che-che.10.0.100.48.nip.io/api/system/state -Status: 404
14:39:06 [07:39:07] 👀  Looking for an already existing Che instance [failed]
14:39:06 [07:39:07] → E_CHECK_CHE_STATUS_FAIL - Failed to check Che status (URL: http://che-che.10.0.100.48.nip.io). E_CHE_API_UNKNOWN_ERROR - Endpoint: http://che-che.10.0.100.48.nip.io/api/system/state -Status: 404
14:39:06  ›   Error: E_CHECK_CHE_STATUS_FAIL - Failed to check Che status (URL: 
14:39:06  ›   http://che-che.10.0.100.48.nip.io). E_CHE_API_UNKNOWN_ERROR - Endpoint: 
14:39:06  ›   http://che-che.10.0.100.48.nip.io/api/system/state -Status: 404
14:39:06  ›   Error: E_CHECK_CHE_STATUS_FAIL - Failed to check Che status (URL: 
14:39:06  ›   http://che-che.10.0.100.48.nip.io). E_CHE_API_UNKNOWN_ERROR - Endpoint: 
14:39:06  ›   http://che-che.10.0.100.48.nip.io/api/system/state -Status: 404
```
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/2117/console

In fact, Eclipse Che was started successfully according to the logs https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/2117/

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl from next channel
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other: CRW CCI
   - [ ] other: please specify

**Comment by benoitf** [comment]
@dmytro-ndp could you please avoid to assign issue to me ? There is area/chectl and devex team as well.

**Comment by benoitf** [comment]
could you please provide data that are externally available ?
