### ISSUE TITLE
Verify Devconsole integration

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14745]
### Is your enhancement related to a problem?

OCP 4.2 DevConsole has integration with Che:
- A Che Console Link
- A link to a factory URL to create the 

### Describe the solution you'd like

We should test that when a Che 7.2 or higher (with TLS enabled) is installed on OCP 4.2:
- Che console link is created
- A factory link in the DevConsole topology triggers the successful creation of a workspace
- Clicking a second time on the factory link opens the existing workspace

**Comment by skabashnyuk** [comment]
Integration functionality was added in this pr
-  DevConsole  https://github.com/openshift/console/pull/2536
- Che Operator https://github.com/eclipse/che-operator/pull/71
CC @mshaposhnik

**Comment by l0rd** [comment]
Please verify that [policies.create=peruser](https://github.com/eclipse/che/issues/14355) works as expected as well.

**Comment by l0rd** [comment]
As discussed with the team this issue is assigned to `team/platform` and should be included in 7.3 milestone. Of course QE team can add a corresponding automated test but that's not what this issue is about and we can close this issue as soon as platform team as finished its verification.

**Comment by sleshchenko** [comment]
I successfully verified that Che link appeared on Dev Console and there is an ability to edit source code, but I failed to run workspace because of my laptop performance issues.
Previously I run OpenShift 4.x with 10Gi and it was enough for Che with 1 workspace, now seems it's not enough.
Tried with 14Gi - but it leads to issue with Linux which causes VM crashing.
Trying with 12Gi... If it fails - I will try to request AWS resources.

**Comment by davidfestal** [comment]
How would be the CRW case managed in terms of ConsoleLink ?
does this issue also cover this question ?

Afaict, the [mentioned PR](https://github.com/eclipse/che-operator/pull/71/files#diff-39f90903a052a49913a612fe89e5637eR71) doesn't seem to provide a way to override the name, display name and icon of the provided `ConsoleLink`.

Is it expected that Che branding is always shown from the devConsole even though CRW is installed ?

cc @l0rd @nickboldt

**Comment by sleshchenko** [comment]
Successfully requested OpenShift 4.2 on AWS and tested ConsoleLink workflow.
Faced the following issue https://github.com/eclipse/che/issues/14554 
cc @l0rd it might need to be prioritized

**Comment by sleshchenko** [comment]
Rested Che integration into Devconsole after https://github.com/eclipse/che/issues/14554 is closed:

| Subject |    | Comment |
|------------|---|---------------|
| Red Hat Applications | :heavy_check_mark: | Che appears in `Red Hat Applications` tab |
| Click `Edit Source Code` when no any workspace is running | :heavy_check_mark: | The wanted workspace is started and opened | 
| Click `Edit Source Code` when there is **running** workspace for this requested project  | :heavy_check_mark: | The wanted workspace is opened | 
| Click `Edit Source Code` when there is **starting** workspace for this requested project | :heavy_check_mark: | The wanted workspace is opened and dashboard shows start process | 
| Click `Edit Source Code` when there is **running** workspace for another project | :heavy_check_mark: | Dashboard shows error message `You are not allowed to start more workspaces.` |
