### ISSUE TITLE
Golang debugger is broken

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14741]
### Describe the bug
We have remote plugin for golang support. Currently debugger for this remote plugin is broken. For debugger we are installing dlv inside image:https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-go-1.10.7/Dockerfile#L65. But go get command **always downloads latest version dlv**. In the latest dlv debugger version was dropped support golang 0.10.7, that why debugger doesn't work.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
![screencast-che-che 192 168 99 100 nip io-2019 09 02-16_09_05](https://user-images.githubusercontent.com/6873095/66035290-85984900-e513-11e9-884e-fab70381bb01.gif)

1. Create workspace from golang stack
2. See video:

### Expected behavior
Debugger should work.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by AndrienkoAleksandr** [comment]
Proposed solutions: we have plugin with version name 0.11: https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/go/0.11.0/meta.yaml#L15 , but actually was used image with golang 0.10.7. We need to use newer golang in the image and debugger will be fixed

**Comment by tsmaeder** [comment]
But aren't users of the plugin getting an image that was built when the debugger _did_ support that version? Not saying we shouldn't fix the dockerfile, but I don't think this problem should surface to the user, so for me P2, no P1.

**Comment by AndrienkoAleksandr** [comment]
@tsmaeder no, we build all images every day. @evidolob Am I right?

**Comment by tsmaeder** [comment]
I would expect us to rebuild nightly or next, but not versioned (aka released) images.

**Comment by tolusha** [comment]
The latest version of the plugin works well with the current sample:

https://raw.githubusercontent.com/eclipse/che-plugin-registry/11ea1728310fd8ed6b26e904d4652d7aa14f166b/v3/plugins/ms-vscode/go/0.11.4/meta.yaml
