### ISSUE TITLE
Impossible to build @eclipse-che/api

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14756]
### Describe the bug
build script in https://github.com/eclipse/che/tree/master/typescript-dto is failing

dto-maven.xml is referencing project API which has been removed

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
run build.sh, the generated file is corrupted (error message)

### Expected behavior
`d.ts` file is correctly generated

**Comment by tsmaeder** [comment]
We seem to rely on this internally: https://www.npmjs.com/package/@eclipse-che/api

**Comment by benoitf** [comment]
well the build script is publishing to this npmjs registry

**Comment by tsmaeder** [comment]
The "dependents" all look like internal stuff, and no-one raised an issue, so I'm thinking the number of external users is 0.

**Comment by benoitf** [comment]
che-theia is using it (if che-theia is internal)
