### ISSUE TITLE
Add maintainer field in plugin meta.yaml

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#14751]
### Is your enhancement related to a problem? Please describe.

In some cases, the maintainer of che-plugin may not be same as the code author.
For example, [PizzaFactory provides che-plugin that supports Move smart contract language](https://github.com/PizzaFactory/che-plugin-registry/tree/azure-pipelines/v3/plugins/pizzafactory/vscode-libra-move). It contains [the VSIX package from  SDKBox](https://github.com/sdkbox/vscode-libra-move/).

I want to express "this plugin contains the artifact by SDKBox" clarify. But there is no tag in plugin/meta.yaml

### Describe the solution you'd like

I want to add some information like follows to plugin's meta.yaml .

* `project` : information for the code author. (match to SDKBox above)
* `maintainer` : information for the plugin author / packager. (match to PizzaFactory above)

### Additional context

The name `project` and `maintainer` is inspired by  [Alpine APK package repository](https://pkgs.alpinelinux.org/packages).

**Comment by monaka** [comment]
Partly my misunderstanding.
meta.yaml provides `repository`. This can be used similar to  `project` in Alpine APK.
And `publisher` in meta.yaml is close to `maintainer`

... But still I suggest to add `maintainer`.
It will be more third party plugins available near the future.
It's useful to provide technical/sales contact information, IMO.

**Comment by l0rd** [comment]
@monaka you want to distinguish the publisher (in this case `sdkbox`) and the maintainer (`pizzafactory`) right?

**Comment by monaka** [comment]
@l0rd close to.
I prefer to add (a) reachable address(es) like `monaka@pizzafactory.jp`, `https://camino.pizzafactory.jp/`, or something as the value of `maintainer`
Users may recognize one plugin was published by `pizzafactory` as it is defined in `meta.yaml`.
But they can't see the way to contact for getting helps without `maintainer`.

I suppose `maintainer` can be optional.
Everyone know who is the maintainer if the value of `publisher` was `redhat`, `eclipse`, or somebody famous.
