### ISSUE TITLE
Outdated typescript types of @eclipse-che/api

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#14755]
### Describe the bug
The latest publication date is 5 months old with 7.0.0-beta-4.0
https://www.npmjs.com/package/@eclipse-che/api

Che-theia is using this API so it may lead to errors in they were changed in the API model.

### Expected behavior
At each Eclipse Che release, it should be published.

**Comment by tsmaeder** [comment]
Yes, but I doubt we have external customers. Internally, we consume it directly, right?

**Comment by tsmaeder** [comment]
Assigning to ide team. Please forward if not correct.
