### ISSUE TITLE
Use specific version of images in helm charts

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#14750]
At the moment, all helm deployments utilise the `nightly` tag on images. I.e.

`image: quay.io/eclipse/che-plugin-registry:nightly`

Would it be possible to fix these versions on each tag in the eclipse/che repository?

Alternatively, I noticed that the Openshift deploy files give the option to specify `IMAGE_TAG` to control which version of Che is deployed. Would it be possible to bring this option over as a customisable value in the chart?

**Comment by benoitf** [comment]
Hello @davidwindell 
Could you use chectl as well ?

You want to provide a set of images for all deployments ?

https://github.com/eclipse/che/issues/14725 might be related by setting tags of different images
 https://github.com/eclipse/che/issues/14699 is related as well

**Comment by davidwindell** [comment]
@benoitf I'm going to close this as it looks like you already do this for image tags, https://github.com/eclipse/che/commit/bb3939a2a6b45ccc2211117b4f3d87600afc4cff sorry, my bad!
