### ISSUE TITLE
[Doc] Add Apache license to Che4z documentation

### ISSUE THREAD

**Issue by zeibura** [eclipse-che/che#14764]
The Apache 2.0 license needs to be added to the TPSRs for the Che4z documentation.

**Comment by tsmaeder** [comment]
What is a TPSR? What is Che4z?

**Comment by benoitf** [comment]
cc @rkratky @themr0c

**Comment by benoitf** [comment]
@tsmaeder https://github.com/eclipse/che-docs/pull/813

**Comment by zeibura** [comment]
TPSR = third party software requirement, i.e. a content licence, and Eclipse Che4z is a plugin developed by Broadcom whose documentation is currently hosted on Che Docs v7

https://www.eclipse.org/che/docs/che-7/che4z-release-information/

I only submitted this issue because of the advice in an email from Robert Kratky that every pull request made to the che-docs repo needs to be accompanied by an issue in this repo.

**Comment by themr0c** [comment]
https://github.com/eclipse/che/issues/14764 is merged
