### ISSUE TITLE
Branding JSON for UD includes old CHE-6 links

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14763]
### Describe the bug

Branding JSON for UD includes old CHE-6 links.

We have the next links in our [product.json](https://raw.githubusercontent.com/eclipse/che/master/dashboard/src/assets/branding/product.json) file:
```
  "docs" : {
    "devfile" : "/docs/che-7/using-developer-environments-workspaces.html#making-a-workspace-portable-using-a-devfile_using-developer-environments-workspaces",
    "workspace" : "/docs/what-are-workspaces.html",
    "factory" : "/docs/factories-getting-started.html",
    "organization": "/docs/organizations.html",
    "converting": "/docs/che-7/converting-a-che-6-workspace-to-a-che-7-devfile/",
    "general": "/docs"
  }
```
If we try those links, we will see the next **che-6** redirections:
 "/docs/organizations.html" -> "/che/docs/che-6/organizations.html"
 "/docs/factories-getting-started.html" -> "/che/docs/che-6/factories-getting-started.html"
 "/docs/what-are-workspaces.html" ->  "/che/docs/che-6/what-are-workspaces.html"

We should provide the **che-7** docs link at least for our **docs.workspace**.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open workspaces tab and click the 'Learn more':
![Screenshot from 2019-10-03 12-29-05](https://user-images.githubusercontent.com/6310786/66115623-de321980-e5d9-11e9-9378-a0313ea8bfe6.png)
It redirects to
![Screenshot from 2019-10-03 14-00-25](https://user-images.githubusercontent.com/6310786/66121592-3707af00-e5e6-11e9-9ddb-bf28b0c3dff7.png)

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

https://youtu.be/1veuVPTV40E

**Comment by olexii4** [comment]
@slemeur WDYT?

**Comment by tsmaeder** [comment]
P2 because this seems a low hanging fruit and it's a "doh!".

**Comment by akurinnoy** [comment]
@slemeur @rkratky 
Are you OK to change 
`"workspace" : "/docs/what-are-workspaces.html"` to point to `/docs/che-7/workspaces-overview/` 
and `"general": "/docs"` to point to `/docs/che-7` ?

Also, I don't see any docs for organizations and factories for Che-7. Maybe, you know whether they are available?

**Comment by slemeur** [comment]
@rkratky : I would think that now, the default docs should be che-7. Is that something you are planning soon?
