### ISSUE TITLE
Allow endpoints section for VSCode extension sidecars in plugin meta.yaml

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14766]
### Is your enhancement related to a problem? Please describe.
As for now we do not allow for Che plugins of VSCode extension (Che Theia plugin) type to have endpoints. But sometimes VSCode extension might have additional service which should be accessible from outside of workspace. To handle such situations I suggest to remove this artificial limitation.

### Describe the solution you'd like
Allow for VSCode extension sidecar to have endpoints

**Comment by mmorhun** [comment]
My own example: I've written Che plugin which has its backend in sidecar container and exposes some service to end user. The plugin also has UI which is implemented as Che Theia plugin. But there is no way to bring such a plugin into Che. From one side it is denied for VSCode extension (or Che Theia plugin) to bring two sidecars, from the other one (if put the service and UI into the same container) we have this endpoint limitation.

@l0rd @ibuziuk WDYT?

**Comment by AndrienkoAleksandr** [comment]
+1 to remote limitation:

https://github.com/eclipse/che-plugin-broker/blob/master/brokers/unified/broker.go#L253

**Comment by l0rd** [comment]
@mmorhun @AndrienkoAleksandr makes sense to me
