### ISSUE TITLE
Install Che 7 operator on OpenShift cluster

### ISSUE THREAD

**Issue by spaparaju** [eclipse-che/che#14769]
### Describe the bug

Either for 4.1 / 4.2 (kubeadmin login) , I have followed instructions (total of 3) under 'Install button' at https://operatorhub.io/operator/eclipse-che , could not see the operator / any resources show up under the namespace 'my-eclipse-che'. Anything I am missing ?

### Che version

 - [ ] latest
 - [ ] nightly
 - [X] other: Che 7.2 thru operator at https://operatorhub.io/operator/eclipse-che

### Expected behavior

Che resources would show up under the namespace 'my-eclipse-che'

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [X] Openshift (include output of `oc version`) 4.2.0-rc.0
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [X] che-operator  quay.io/eclipse/che-operator:7.2.0CopyCopy to Clipboard
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [X] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by davidfestal** [comment]
You should not install che7 on Openshift 4 from the OperatorHub.io website site : this is for Upstream K8S. Please use the operator provided by the OperatorHub embedded into the OpenShift console.
