### ISSUE TITLE
E2E Happy path tests failed on reading of build-output.txt

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14771]
### Describe the bug
E2E Happy path tests started failing on step "1) Validation of workspace build and run > Build application":
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/234/
```
11:20:46     ✓ Open workspace (1102ms)
11:23:11     ✓ Wait workspace running state (144648ms)
11:23:22     ✓ Wait until project is imported (11011ms)
11:23:22 
11:23:22   Language server validation
11:26:23     ✓ Java LS initialization (180531ms)
11:26:32     ✓ Error highlighting (8950ms)
11:26:41     ✓ Autocomplete (9115ms)
11:26:51     ✓ Suggestion (10376ms)
11:27:01     ✓ Codenavigation (9739ms)
11:27:01     - Yaml LS initialization
11:27:01 
11:27:01   Validation of workspace build and run
11:30:50     1) Build application
11:30:50 
11:30:50 
11:30:50   8 passing (10m)
11:30:50   1 pending
11:30:50   1 failing
11:30:50 
11:30:50   1) Validation of workspace build and run
11:30:50        Build application:
11:30:50      TimeoutError: Wait timed out after 220388ms
11:30:50       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
11:30:50       at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
11:30:50       at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
11:30:50       at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
11:30:50       at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
11:30:50       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
11:30:50       at <anonymous>
11:30:50   From: Task: <anonymous wait>
11:30:50       at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)
11:30:50       at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)
11:30:50       at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
11:30:50       at Editor.<anonymous> (/tmp/e2e/pageobjects/ide/Editor.ts:234:45)
11:30:50       at Generator.next (<anonymous>)
11:30:50       at fulfilled (/tmp/e2e/dist/pageobjects/ide/Editor.js:17:58)
11:30:50       at <anonymous>
11:30:50       at process._tickCallback (internal/process/next_tick.js:188:7)
```
![screenshot-Build_application (1)](https://user-images.githubusercontent.com/1197777/66198648-895bd500-e6a5-11e9-9f26-2a5b80ccf19c.png)

#### Possible solution
Get rid of reading build-output.txt, by approaching terminal log from Dom canvas  #14772.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
https://github.com/eclipse/che/blob/master/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by musienko-maxim** [comment]
Looks like this problem  come from the latest changes from Theia. This conversation with describing the [problem: ]( https://spectrum.chat/theia/dev/mutual-exclusion-in-api-calls~9bd83415-ffda-4eb2-8b58-3d35427c701e?m=MTU2NDQ4OTE2MzkzMQ==)
and dependent  issue around that: 
https://github.com/eclipse-theia/theia/issues/5820
Before resolving this one we should implement a workaround (Possible solutions switch off autosave option)
