### ISSUE TITLE
Missing Proxy Configuration?

### ISSUE THREAD

**Issue by Numblesix** [eclipse-che/che#14776]
## Summary
I try to setup Che7 on Openshift 3.11 everything starts fine until  i check out a sample project from github.com as i can see there is no proxy configured. How do i configure one ? 
## Relevant information
oc version
oc v3.11.98
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://****:8443
openshift v3.11.98
kubernetes v1.11.0+d4cacc0

➜  bin ./chectl version       
chectl/7.2.0 linux-x64 node-v10.16.3

./chectl server:start --platform=openshift --installer=operator --domain=*****.de

**Comment by rhopp** [comment]
@rkratky @themr0c Do we have any documentation for setting up a proxy? I know we have something for Codeready Workspaces, but that can be a bit obsolete, as CRW is based on Che 6.

@skabashnyuk cc.

**Comment by Numblesix** [comment]
CRW1 has it in the Doc.

If you push me to the right code i might be able to open a Pull Request for a Doc Enhancment :)

**Comment by skabashnyuk** [comment]
I would suggest starting from reviewing
- https://github.com/eclipse/che-docs/blob/ae669c67e1109024e23e3ad323ead67796044189/src/main/pages/che-6/setup-docker/docker-config.adoc#installing-che-behind-a-proxy
- https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties  | grep proxy

**Comment by Numblesix** [comment]
If i see it correct that means that CHE is supporting Proxy but chectl is missing this option ?

**Comment by tolusha** [comment]
It is possible to specific proxy settings directly into CR [1] file and use it with `--che-operator-cr-yaml` flag.

`chectl server:start .... --che-operator-cr-yaml=<PATH_TO_CR_YAML>`

[1]  https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml
