### ISSUE TITLE
Project delete button in dashboard is invisible

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14773]
### Describe the bug

In the Create Workspace panel, the delete button is not visible even if it's active (and works fine by the way 😃 ).

### Che version

nightly

### Runtime

```shell
$ minikube version
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:48:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots

![image](https://user-images.githubusercontent.com/606959/66202080-266a3e00-e6a5-11e9-91f2-70c623e543d4.png)

### Installation method

``` 
$ chectl server:start --platform minikube --installer helm
```

### Environment

my computer / macOS

**Comment by l0rd** [comment]
cc @olexii4

**Comment by olexii4** [comment]
@l0rd  Regression after the version upgrade. Like this one(invisible '+' on the 'Add Project' button)
![Screenshot from 2019-10-04 14-06-48](https://user-images.githubusercontent.com/6310786/66203229-78649100-e6b0-11e9-94e9-7fb5ad854d68.png)
It will be a quick fix:
![Screenshot from 2019-10-04 14-00-27](https://user-images.githubusercontent.com/6310786/66203247-83b7bc80-e6b0-11e9-8d2f-6c9576ea9e35.png)

**Comment by l0rd** [comment]
@olexii4 👍

**Comment by olexii4** [comment]
Already fixed in https://github.com/eclipse/che/pull/14707
