### ISSUE TITLE
Apply ability to select render for terminal

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14772]
### Describe the solution you'd like
It would be nice to apply ability to select render for terminal widget. It should be useful for qa, because currently we are using canvas render for terminal and qa can not read content from widget. QA could use dom renderer and read content from terminal widget without problems. VSCode has such feature, so we can apply it to the upstream theia to align with VScode:

<img width="960" alt="Screenshot_20191004_130529" src="https://user-images.githubusercontent.com/6873095/66200517-f1141f00-e6a9-11e9-96c7-266a0d462d81.png">

VSCode has options: dom renderer and canvas(faster)

**Comment by rhopp** [comment]
This would be SUPER helpful! Didn't know, that something like this is possible!

**Comment by mmorhun** [comment]
Fixed in https://github.com/eclipse-theia/theia/pull/6471
