### ISSUE TITLE
Two different versions of webpack are used in the che-theia build

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14786]
Two different versions of webpack are used in the che-theia build - 4.41.0:

```
@eclipse-che/theia-plugin-ext: Version: webpack 4.41.0
```

and 4.21.0:

```
@eclipse-che/theia-assembly: Version: webpack 4.21.0

@theia/example-browser: Version: webpack 4.21.0

@theia/example-electron: Version: webpack 4.21.0
```

Now, ah say, I might not be a [big-city](https://tvtropes.org/pmwiki/pmwiki.php/Main/SimpleCountryLawyer) node developer, but it don't seem right to me to not be a'using the same version in all places here.

**Comment by benoitf** [comment]
it's not like in java where you compile with one lib and execute with another
Heure, each module has it's version at runtime as well
So it can be nice to reduce but it's something quite impossible to do in all dependencies of dependencies ( as we don't maintain them)

**Comment by tolusha** [comment]
@nickboldt 
Could close the issue if answer is ok

**Comment by benoitf** [comment]
closing for now
