### ISSUE TITLE
The engine "theiaPlugin" (or "vscode") appears to be invalid

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14787]
This warning appears 45 times in the che-theia build log when building theia:

`The engine "theiaPlugin" appears to be invalid.` (41 times)
or
`The engine "vscode" appears to be invalid.` (4 times)

Can these be suppressed? Are they as meaningless as I think?

**Comment by benoitf** [comment]
it can be skipt with special yarnrc file. I think I patched some of them
` --ignore-engines`
They are useless warnings ( it's just that theia is unknown for yarn)
