### ISSUE TITLE
Source Action: How to give options

### ISSUE THREAD

**Issue by wgbeckmann** [eclipse-che/che#14783]
Hi,
I use Eclipse Che with Theia 
![image](https://user-images.githubusercontent.com/18114426/66255687-ef6c5900-e786-11e9-888b-dc22d0f33690.png)

When I want to use the Source Actions "Generate Getters and Setters", "Genetare toString()" or "Generate Constructor" and I have multiple Variables, I have to give Options, but I dont know ho to give the Options:

![Peek 2019-10-05 15-53](https://user-images.githubusercontent.com/18114426/66255792-50486100-e788-11e9-9d05-0cadc471e599.gif)

When I Click on one of the Otions nothing happens, even thow if i chose one with the cursor and press enter.

How do I use it?

Thanks,
Wolf

**Comment by tolusha** [comment]
Hi. @wgbeckmann 
It is turned out to be a pure Theia issue.  I've created a related one:
https://github.com/eclipse-theia/theia/issues/6336
