### ISSUE TITLE
`operator-sdk generate k8s` strips license out of generated files

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#14782]
### Is your task related to a problem? Please describe.

The generated type files in the Che Operator have a header referencing the Apache License.  `operator-sdk generate k8s` deletes this header.  

### Describe the solution you'd like

Figure out how to add that license header back in the code-generation process.

**Comment by tolusha** [comment]
I don't know if it is a real issue.
@davidfestal @nickboldt ?

**Comment by tomgeorge** [comment]
I think it is probably a low priority issue, but it's an issue. You shouldn't have to manually edit a generated file every time you change it.

**Comment by tolusha** [comment]
I've added script that generates cr/crd files, removes `required` and restores license header
https://github.com/eclipse/che-operator/pull/180
