### ISSUE TITLE
Provide tests for Camel Che stack and their plugins

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#14780]
test with following cases are important:
- Start Camel Che stack
- can have completion on Camel java files
- can have completion on Camel URIs
- can launch the build task successfully

nice to have:
- validation on Camel URI
- outline of Camel elements
- navigation between "direct" Camel component in 2 different files opened

**Comment by rhopp** [comment]
@apupier Do you think you would be able to contrubute those tests? We can guide you and help you create them ;-)

If not, please try to provide more detailed instructions (or screencast ;-) )

**Comment by apupier** [comment]
> Do you think you would be able to contrubute those tests? We can guide you and help you create them ;-)

interested in providing them.
I noticed 2 places for tests:
https://github.com/eclipse/che/tree/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium
https://github.com/eclipse/che/tree/master/e2e/tests

Not sure from which one I should start with.

How to launch these tests? What is the recommended way to develop tests?

**Comment by rhopp** [comment]
https://github.com/eclipse/che/tree/master/e2e/tests is the correct place.

You can create another spec.ts file for the devfile/stack you want as this one: https://github.com/eclipse/che/blob/master/e2e/tests/e2e/JavaVertx.spec.ts

Instructions of how to run the tests are in the readme file: https://github.com/eclipse/che/blob/master/e2e/README.md

If you need any info, feel free to contact us in our eclipse mattermost channel: https://mattermost.eclipse.org/eclipse/channels/eclipse-che-qe

**Comment by apupier** [comment]
> interested in providing them.

already a long time on standby. I fear I won't have time to work on that in near future

**Comment by rhopp** [comment]
Seems like to implement this (mostly the last step - `can launch the build task successfully`) we need a running Camel K instance. This is already being discussed in https://github.com/eclipse/che/issues/17015 and https://github.com/eclipse/che/issues/15391, so I'm putting this issue on-hold until #17015 and #15391 are resolved.

**Comment by apupier** [comment]
in the test infrastructure we can add a Camel K instance.

We are doing it for VS Code Camel K test for instance: https://github.com/camel-tooling/vscode-camelk/blob/3a49334ab30ea338d4c497bcd0d0995b84928a38/.travis.yml#L26-L46

The other issues are currently blocked for a very long-time due to Che limitations. I don't think that we should wait for them. To use the stack currently, the requirement is that there is a Camel K isntance deployed somewhere and accessible. it sounds like a reqyuirement that needs to be fulfilled by the test infrastructure.

**Comment by rhopp** [comment]
Out of curiosity - what's the compute requirements (ram/cpu) for running camel K instance needed for tests?

**Comment by apupier** [comment]
> Out of curiosity - what's the compute requirements (ram/cpu) for running camel K instance needed for tests?

i don't have this information.
it is running fine on Travis which has 7.5Gb https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system  . it includes a minikube instance and Camel K deployed on it (and the VS Code instance). I think most of the place is taken by minikube. If you already have a container it should be really small.

**Comment by ericwill** [comment]
cc @Ohrimenko1988

**Comment by apupier** [comment]
Plugin tests seem to have been moved too https://github.com/eclipse/che/tree/main/tests/e2e/tests/plugins

**Comment by nallikaea** [comment]
Outdated
