### ISSUE TITLE
[solved] Deploy Che-multiuser behind Nginx proxy with https using only FQDN

### ISSUE THREAD

**Issue by Mbd06b** [eclipse-che/che#14788]
I've been trying to install Eclipse Che on and off for about a year and a half now on a private Ubuntu(18-LTS) Server that I can access with a domain name using a Dynamic DNS record. Before I jump down this rabbit hole again.  With the release of Eclipse Che 7, is it reasonable to:

Strategy 1. Deploy Che-multiuser behind a (non-ingress) Nginx proxy with https termination using a wildcard FQDN.  

Strategy 2. Deploy Che-mulituser alongside a (non-ingress) Nginx with https termination occurring at the Che server on minikube. 

Strategy 3. Deploy an accessible Che-single user with https and some other password protection/login strategy(non-VPN)?? 

Strategy 1 makes the most logical sense to me at this point, if anyone has a working sample Nginx config for this, and what arguments they are using, I'd appreciate you sharing it, before I light into this next release attempt.

Edit: Noticed that docker install is being deprecated from eclipse 7. I'm narrowing my focus to minikube.   (Update:  Minikube seems tailored for Windows/Mac users, I ultimately focused on Microk8s, because it doesn't require the VM overhead, and it's snap package is directly supported by Canonical, seemed to be a better choice for my target Ubuntu environment).  

The purpose of this is to have a https/login (keycloak) secured private instance of Eclipse Che that will continuously run on a single server(node) that I can access anywhere and share with others. I develop heavily on local IDEs, but would like migrate more traditional developer workspaces/workflows to a self-hosted cloud, while increasing the overall utilization efficiency of my own running bare-metal server I use to DevOps those projects. The idea being purchasing PaaS or IaaS resources soley to run Che would theoretically be redundant and wasteful to this goal.

**Comment by Mbd06b** [comment]
I'm currently trying to install eclispe che multi-user with che and am going with snap installs of microk8s and helm.

sudo chectl server:start --platform=microk8s --mulituser --chenamespace=che --installer=helm

I get a successful launch with nip.io, but I'm struggling now to figure out an external nginx proxy to handle my virtualhost routing for che running on the microk8s cloud.  

sudo chectl server:start --platform=microk8s --multiuser --domain=code.example.com --chenamespace=che 
// che pod fails to start because it cannot find  /auth using the FQDN code.example.com/auth ...

**Comment by Mbd06b** [comment]
All my pods are launching and running, except for the che-host because it can't verify the endpoint requirement from keycloak. 
http://keycloak-che.code.example.com/auth/realms/che/.well-known/openid-configuration

Here's what I have so far for my Nginx proxy.  I'm hitting my Microk8s ingress nginx, but everything lands on 404.

Any ideas for these headers are set correctly? 
proxy_set_header Host            $http_host;
proxy_set_header X-Forwarded-For $remote_addr;

`upstream sslchekubeingress {
    server 127.0.0.1:444;  #microk8s ingress flag --https-port=444
}

upstream chekubeingress {
    server 127.0.0.1:8880; #microk8s ingress flag --http-port=8880
}

server {

     listen 80;
     server_name code.example.com *.code.example.com;
     access_log /var/log/nginx/che_proxy_access.log;
     error_log /var/log/nginx/che_proxy_error.log error;

     location / {

            proxy_pass https://chekubeingress;
            proxy_http_version 1.1;                 #required to handle websocket ws:// 
            proxy_set_header Upgrade $http_upgrade; #required to handle websocket ws:// 
            proxy_set_header Connection "upgrade";  #required to handle websocket ws:// 
            
			proxy_set_header Host            $http_host;
            proxy_set_header X-Forwarded-For $remote_addr;
    }

}

server {

    listen 443 ssl; # managed by Certbot
    server_name code.example.com *.code.example.com;
	
	#manually generated wildcard domain, NOTE: you must include the root domain case -d code.worscipe.com
	#sudo certbot --server https://acme-v02.api.letsencrypt.org/directory -d code.worscipe.com -d *.code.worscipe.com --manual --preferred-challenges dns-01 certonly
    ssl_certificate /etc/letsencrypt/live/code.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/code.example.com/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
          proxy_pass https://sslchekubeingress;
          proxy_http_version 1.1;                 #required to handle secure websocket wss:// 
          proxy_set_header Upgrade $http_upgrade; #required to handle secure websocket wss://
          proxy_set_header Connection "upgrade";  #required to handle secure websocket wss://
          
		  proxy_set_header Host            $http_host;
          proxy_set_header X-Forwarded-For $remote_addr;
   }
}`

**Comment by Mbd06b** [comment]
Side note, ingress nginx > 0.25.0 will fail to run on CPUs that don't support SSE4 instructions due to a dependency,

See:  https://github.com/kubernetes/ingress-nginx/issues/4311


I was able to get mine to run on my Xeon E5310 by editing the deployed image version manually to  0.24.1 
`kubectl edit -n ingress daemonset.apps/nginx-ingress-microk8s-controller`

**Comment by Mbd06b** [comment]
I also had to follow this workaround to get chectl to work with microk8s context https://github.com/eclipse/che/issues/14455#issuecomment-561439019

**Comment by Mbd06b** [comment]
Status:  I can hit the individual ingresses of each server through my nginx, by proxy directly to each service's Cluster IP. 

 But I'm struggling to find a single target IP address or Port for Che that will allow kubernetes to vhost route to each of the ingresses to enable the dynamic connections to the workspaces and other on demand resources.

**Comment by Mbd06b** [comment]
This works to proxy each of the core ingresses. So I can load the dashboard, dev registry, plugins, and keycloak.  But it doesn't address the issue of dynamic routing to load the work-spaces or other resources that might be added.  
What am I missing??   What is the target for routing ALL traffic over to microk8s and have it handle the v-host routing internally? 

`upstream chekubeingress {
    server 10.152.183.153:8080;
}
upstream keycloak {
    server 10.152.183.82:5050;
}
upstream devfiles {
   server 10.152.183.117:8080;
}

upstream plugins {
    server 10.152.183.185:8080;
}

server {

     listen 80;
     server_name code.example.com *.code.example.com;
     access_log /var/log/nginx/che_proxy_access.log;
     error_log /var/log/nginx/che_proxy_error.log error;

     location / {
        proxy_pass http://chekubeingress;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host              $host;
    }

    location /auth {
         proxy_pass http://keycloak;
         proxy_set_header Host            $http_host;
         proxy_set_header X-Forwarded-For $remote_addr;
    }
    location /devfiles {
         proxy_pass http://devfiles;
    }
    location /v3/plugins {
         proxy_pass http://plugins;
    }

}`

**Comment by Mbd06b** [comment]
My nginx logs indicate that I have a redirect loop in my config.  I need some way of proxying back to my ingresses using a non-standard localhost or port.  Listing the ingresses from my install, 

# HOW TO CHANGE THESE IP ADDRESSES OR PORTS?
kubectl get ingress --all-namespaces
che         che-ingress        che-che.code.example.com                127.0.0.1   80      2d11h
che         devfile-registry   devfile-registry-che.code.example.com   127.0.0.1   80      2d11h
che         keycloak-ingress   keycloak-che.code.example.com           127.0.0.1   80      2d11h
che         plugin-registry    plugin-registry-che.code.example.com    127.0.0.1   80      2d11h

**Comment by Mbd06b** [comment]
This seems to be working. 

> upstream chekubeingress {
>     server 127.0.0.2:8880; #ingress daemonset.app http port arg
> }
> 
> upstream sslcheingress{
>    server 127.0.0.2:4443; #ingress daemonset.app https-port port arg
> }
> 
> server {
> 
>      listen 80;
>      server_name code.worscipe.com *.code.worscipe.com;
> 	 
>      location / {
> 
>        proxy_pass http://chekubeingress;
>        proxy_set_header Upgrade $http_upgrade;
>        proxy_set_header Connection "upgrade";
>        proxy_http_version 1.1;
>        proxy_connect_timeout 7d;
>        proxy_send_timeout 7d;
>        proxy_read_timeout 7d;
>        proxy_set_header Host              $host;
> 	   proxy_pass http://chekubeingress;
> 
>      }
> }
> 
> server {
> 
>     listen 443 ssl; # managed by Certbot
>     server_name code.worscipe.com *.code.worscipe.com;
> 	
>     ssl on;
> 
>     #manually generated wildcard domain, NOTE: you must include the root domain case -d code.worscipe.com
>     #sudo certbot --server https://acme-v02.api.letsencrypt.org/directory -d code.worscipe.com -d *.code.worscipe.com --manual --preferred-challenges dns-01 certonly
> 
>     ssl_certificate /etc/letsencrypt/live/code.worscipe.com/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/code.worscipe.com/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
>     location / {
> 	
> 		  #For wss:// websocket connections
>           proxy_http_version 1.1;
>           proxy_set_header Upgrade $http_upgrade;
>           proxy_set_header Connection "upgrade";
>           proxy_connect_timeout 7d;
>           proxy_send_timeout 7d;
>           proxy_read_timeout 7d;
> 
> 		  #for upstream ingress routing in kubernetes
>           proxy_set_header X-Forwarded-For $remote_addr;
>           proxy_set_header Host              $host;
>           proxy_pass https://sslcheingress;
>     }
> }

**Comment by Mbd06b** [comment]
> This seems to be working for Theia-based editor workspaces. I'm getting errors trying to launch an Eclipse IDE workspaces.
> 
> Any recommendations on cleaning up this nginx config would be appreciated.
> 
> NGINX CONFIG
> 
> > upstream chekubeingress {
> > **server 127.0.0.2:8880;** #ingress daemonset.app http port arg
> > }
> > upstream sslcheingress{
> > **server 127.0.0.2:4443**; #ingress daemonset.app https-port port arg
> > }
> > server {
> > ```
> >  listen 80;
> >  server_name code.example.com *.code.example.com;
> > 
> >  location / {
> > 
> >    proxy_pass http://chekubeingress;
> >    proxy_set_header Upgrade $http_upgrade;
> >    proxy_set_header Connection "upgrade";
> >    proxy_http_version 1.1;
> >    proxy_connect_timeout 7d;
> >    proxy_send_timeout 7d;
> >    proxy_read_timeout 7d;
> >    proxy_set_header Host              $host;
> >  proxy_pass http://chekubeingress;
> > 
> >  }
> > ```
> > 
> > 
> > }
> > server {
> > ```
> > listen 443 ssl; # managed by Certbot
> > server_name code.example.com *.code.example.com;
> > 
> > ssl on;
> > 
> > #manually generated wildcard domain, NOTE: you must include the root domain case -d code.example.com
> > #sudo certbot --server https://acme-v02.api.letsencrypt.org/directory -d code.example.com -d *.code.example.com --manual --preferred-challenges dns-01 certonly
> > 
> > ssl_certificate /etc/letsencrypt/live/code.example.com/fullchain.pem; # managed by Certbot
> > ssl_certificate_key /etc/letsencrypt/live/code.example.com/privkey.pem; # managed by Certbot
> > include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
> > ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> > 
> > location / {
> > 
> >     **#For wss:// websocket connections
> >       proxy_http_version 1.1;
> >       proxy_set_header Upgrade $http_upgrade;
> >       proxy_set_header Connection "upgrade";
> >       proxy_connect_timeout 7d;
> >       proxy_send_timeout 7d;
> >       proxy_read_timeout 7d;**
> > 
> >     #for upstream ingress routing in kubernetes
> >       proxy_set_header X-Forwarded-For $remote_addr;
> >       proxy_set_header Host              $host;
> >       proxy_pass https://sslcheingress;
> > }
> > ```
> > 
> > 
> > }
> 
> The trick was to edit the ingress controller args to listen on a non-standard ip address and ports....
> `kubectl edit daemonset.apps/nginx-ingress-microk8s-controller -n ingress`
> 
> > apiVersion: apps/v1
> > kind: DaemonSet
> > metadata:
> > annotations:
> > deprecated.daemonset.template.generation: "3"
> > generation: 3
> > labels:
> > microk8s-application: nginx-ingress-microk8s
> > name: nginx-ingress-microk8s-controller
> > namespace: ingress
> > resourceVersion: "19117"
> > selfLink: /apis/apps/v1/namespaces/ingress/daemonsets/nginx-ingress-microk8s-controller
> > uid: ead1ea64-a5e5-4a5f-ac52-0a1a419c0bbc
> > spec:
> > revisionHistoryLimit: 10
> > selector:
> > matchLabels:
> > name: nginx-ingress-microk8s
> > template:
> > metadata:
> > creationTimestamp: null
> > labels:
> > name: nginx-ingress-microk8s
> > spec:
> > containers:
> > - args:
> > - /nginx-ingress-controller
> > - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-microk8s-conf
> > **- --publish-status-address=127.0.0.2
> > - --http-port=8880
> > - --https-port=4443**
> > env:
> > - name: POD_NAME
> > valueFrom:
> > fieldRef:

**Comment by tolusha** [comment]
@Mbd06b 
Thank you for detailed instruction.
