### ISSUE TITLE
[selenium: CSharp projects]: obj-folders should be excluded in .gitignore

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#14784]
### Is your enhancement related to a problem? Please describe.

The che repo .gitignore file should exclude "obj" folders.
The selenium section contains .NET (Core) projects for which "obj" folders are created that contain temporary object files.

### Describe the solution you'd like

Add "obj/" to the .gitignore file.

### Additional context

When opening the che repo in VS Code the .NET tooling generates files and folders that should be kept locally only and so for being excluded from git.

**Comment by tolusha** [comment]
As a workaround it is possible to add `obj` to your global exclude file.
