### ISSUE TITLE
Release Che 7.2.1

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14796]
### Is your task related to a problem? Please describe.
This bugfix should cherry-pick https://github.com/eclipse/che/commit/027f2f8b0aabfe92ce09790bd2de1aa4454b5091 and https://github.com/eclipse/che/commit/5be73fff4a8e43dba1c2dd8b0dcd068c7fe0c809 (forgot to squash before merging :/ ) to resolve issue https://github.com/eclipse/che/issues/14749 in the 7.2 version.

**Comment by tsmaeder** [comment]
@amisevsk  Didn't your message yesterday indicate there would be no 7.2.1?

**Comment by amisevsk** [comment]
@tsmaeder I opened the issue for completeness, since the regression breaks ephemeral workspaces on upstream Che 7.2.0, but 7.2.x won't be rolled out to che.openshift.io so it's not a priority for me. If we're fine with 7.2.x release containing the regression then 7.2.1 does not need to be released.

**Comment by ibuziuk** [comment]
Closing since 7.2.1 is not going to happen
