### ISSUE TITLE
Manually verify that git+SSH with devfile works flawlessly

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14794]
#### This issue about testing that you can create a devfile pointing to ssh repo and making sure that it works properly:

- [ ] workspace is created
- [ ] source code is cloned
- [ ] user can push

#### And the corner cases: Improve error message during git push/clone #14615
- [ ] if user is not authorized to clone, it raises an error message
- [ ] if user does not have an ssh key configured, it raises an error

**Comment by vparfonov** [comment]
At the moment if user have well configured SSH settings:
- have generated/uploaded SSH keys in Che;
- put public part to the Git provider

**Comment by tolusha** [comment]
@vparfonov 
Not clear, are talking project url? like this `git@github.com:eclipse/che.git` ?

**Comment by vparfonov** [comment]
> @vparfonov
> Not clear, are talking project url? like this `git@github.com:eclipse/che.git` ?

Yes

**Comment by musienko-maxim** [comment]
@vparfonov, @l0rd For implementing the test for this workflow we need to clarity:
When should launch the ci- job (every day, every release, every PR ) on which repos (che, che-theia) and infra (k8s, openshift).

**Comment by l0rd** [comment]
I don't think that the goal was to create an automated test but just a task for IDE1 team to validate that the whole git+ssh flow works fine cc @slemeur 

But I think that it's actually a good idea @musienko-maxim to use git+ssh in the happy path PR check cc @rhopp

**Comment by nickboldt** [comment]
Latest news from our airgap tester using Che 7.2. The following workflow works.

1. start empty workspace. generate ssh key pair...
2. upload new key to `private airgapped github instance` for each user
3. open devfile w/ ref to `private airgapped github instance` project, using `git@repo:username/project.git` format
4. project code loads! user can pull and push to `private airgapped github instance`

Devfile:

![image](https://user-images.githubusercontent.com/227597/66845909-eb86c680-ef3e-11e9-9e24-8eb3fe2a12a6.png)

Initial load of workspace + readme file:

![image](https://user-images.githubusercontent.com/227597/66845960-022d1d80-ef3f-11e9-809a-480211c468d6.png)

After pushing a change in the workspace to the repo, new workspace loads with change applied:

![image](https://user-images.githubusercontent.com/227597/66845976-0c4f1c00-ef3f-11e9-8a0c-f9ff053e96bf.png)

**Comment by vparfonov** [comment]
If user already has SSh key:
- workspace is created
- source code is cloned
- user can push

If not:
- workspace is created
- source code **NOT** cloned, it raises an error message (#14615)
- user **CAN'T** push, it raises an error (#14615)
