### ISSUE TITLE
[samples] nodejs-mongodb-sample sample has no license or copyright

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14799]
In https://github.com/eclipse/che-devfile-registry/commit/26951be304f0b4da40dbb393623557ae8696cf2e#diff-9338ea1beceb3f2957d95768b599300c we switched over to a new mongodb nodejs sample.

However, https://github.com/che-samples/nodejs-mongodb-sample lacks a LICENSE file and has no copyright information.

I do see that [line 11 of the package.json](https://github.com/che-samples/nodejs-mongodb-sample/blob/master/package.json#L11) says this project is under MIT license, but that's not sufficient.

Since Red Hat owns this content and this repo, we need to have a correct copyright statement in all files where it makes sense to include one. 

(If copying boilerplate from another Che file, please make sure the copyright year starts with 2019, not an earlier year.)

Some files that ought to bear a copyright (c) 2019 Red Hat, Inc.:

* app.js
* package.json
* Dockerfile
* ...

## Affected projects

- [ ] https://github.com/che-samples/nodejs-mongodb-sample
- [ ] https://github.com/che-samples/dotnet-web-simple
- [ ] https://github.com/che-samples/console-java-simple
- [ ] https://github.com/che-samples/kitchensink-example

(if you find more please add them to this list and get them fixed.)

**Comment by svor** [comment]
@nickboldt does it mean that we need add license to another samples like https://github.com/che-samples/dotnet-web-simple ?

**Comment by svor** [comment]
it was done in
https://github.com/che-samples/dotnet-web-simple/pull/3
https://github.com/che-samples/console-java-simple/pull/13
https://github.com/che-samples/console-java-simple/pull/14
https://github.com/che-samples/kitchensink-example/pull/1
https://github.com/che-samples/cpp-hello-world/pull/2
https://github.com/che-samples/python-hello-world/pull/1
https://github.com/che-samples/nodejs-mongodb-sample/pull/1

**Comment by tsmaeder** [comment]
@svor you changed the copyright statement, for example in the kitchensink example from 
> Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

to just 
> Copyright (c) Red Hat, Inc. All rights reserved.

If there are third parties having copyright in some of the files, we cannot just say it's Red Hat code. Do you have information that makes doing this ok? 
Also: no year mentioned in the copyright comment.

**Comment by svor** [comment]
@tsmaeder year is mentioned in LICENSE file which is in the root of project and license headers are referenced to it.

about kitchensink example - it was just one place where I saw the license  (in pom.xml) so i've decided to change it and use the license which I added to another files (btw it was Red Hat license header).
About the question 

> Do you have information that makes doing this ok?

The answer  is: no, I don't

**Comment by tolusha** [comment]
There is no license header
https://github.com/openshift-vertx-examples/vertx-http-example/blob/master/src/main/java/io/openshift/example/HttpApplication.java
There is a license file
https://github.com/openshift-vertx-examples/vertx-http-example/blob/master/LICENSE

**Comment by nickboldt** [comment]
Copyright statement in code has to have a year or year range. 

If you have a project with multiple license requirements you can state those requirements like this:

https://github.com/eclipse/che-lib/tree/master/che-tomcat8-slf4j-logback/src/assembly
and this:
https://github.com/eclipse/che-lib/blob/master/che-tomcat8-slf4j-logback/src/main/java/App.java
and
https://github.com/eclipse/che-lib/blob/master/LICENSE (there's a note at the bottom about other licenses)

Looks like a lot of our licenses generically say Red Hat (and leave out the "and others"):

https://github.com/eclipse/che/commit/07263f1e30089689d71b057f747a44a29283e3c4

**Comment by nickboldt** [comment]
> So these 4 projects are OK for productization (but might not be OK in Eclipse.org CQs due to a lack of attribution/copyright). 

If you're concerned please feel free to check ipzilla.eclipse.org for existing CQs and make sure that IF we redistribute or run-with any of this sample code, there is a CQ for the code base.

If we only LINK to it as sample code, we are PROBABLY fine here as attribution can be seen from the commit log in the project, with implied (?) copyright.

**Comment by nickboldt** [comment]
Nope, if we plan to have an offline devfile registry then we're REDISTRIBUTING these inside the image. If we're redistributing, we need correct copyrights and licenses.

**Comment by nickboldt** [comment]
Going to assume this is complete since it's now 3 years later ...
