### ISSUE TITLE
Rework che-theia remote plugin images

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#14797]
### This is sub task of  #13387
To complete #13387 we need to rewrite current, alpine based, images. And also provide new optional UBI based images for each of remote plugin. Name of the UBI based docker file will be: `Dockerfile.ubi`

All work on rewriting images are doing in https://github.com/eclipse/che-theia/tree/reworkImages  branch

Current state:

|  Image name |  Current(Alpine) | RHCC based  | Rewriter  |  Req CRW 2 | Req CRW 2+
|---|---|---|---|---|---|
| eclipse/che-remote-plugin-runner-java8 | ✅ | ✅ | | ✅ |  | 
| eclipse/che-remote-plugin-runner-java11 | ✅ | ✅ |  |  |✅  | 
| eclipse/che-remote-plugin-php7 | ✅ | ❌ | Oleksandr | ✅|
| eclipse/che-remote-plugin-go-1.10.7 | ✅ | ❌ | 
| eclipse/che-remote-plugin-go-1.11.5 | ❌ | ❌ | (RHCC has 1.11.5) | ✅|
| eclipse/che-remote-plugin-go-1.12.9 | ✅ | ❌ | Oleksandr |
| eclipse/che-remote-plugin-clang-8 | ✅ | ❌ | | ✅|
| eclipse/che-remote-plugin-python-3.7.3 | ✅ | ✅ | 
| eclipse/che-remote-plugin-python-3.7.4 | ✅ | ✅ | | ✅|
| eclipse/che-remote-plugin-dotnet-2.1.509 | ❌ | ❌ |  (RHCC has 2.1.509) | ✅|
| eclipse/che-remote-plugin-dotnet-2.2.105 | ✅ | ❌ | 
| eclipse/che-remote-plugin-kubernetes-tooling-0.1.17 | ✅ | ✅ |   |
| eclipse/che-remote-plugin-kubernetes-tooling-1.0.0 | ✅ | ✅ |  |✅|
| [eclipse/che-remote-plugin-kubernetes-tooling-1.0.4](https://github.com/eclipse/che-plugin-registry/pull/256) | ? | ? |  |?|
| eclipse/che-remote-plugin-openshift-connector-0.0.17 | ✅ | ✅ |   |
| eclipse/che-remote-plugin-openshift-connector-0.0.21 | ✅ | ✅ |   |
|eclipse/che-remote-plugin-openshift-connector-0.1.0 | ✅ | ✅ | | ✅|
| eclipse/che-remote-plugin-dependency-analytics-0.0.12 | ✅ | ❌ |
| eclipse/che-remote-plugin-dependency-analytics-0.0.13 | ✅| ❌ | | ✅|
| eclipse/che-remote-node(new for typescript) | ✅ | ✅ | @AndrienkoAleksandr | ✅|
| eclipse/che-remote-plugin-camelk-0.0.9 | ✅ | ❌ | |

**Comment by evidolob** [comment]
cc @l0rd , @AndrienkoAleksandr

**Comment by benoitf** [comment]
I think we can handle it differently as I've added templating for base images on top of ubi8

It'll be easy to provide other images

**Comment by benoitf** [comment]
BTW what would be a rewrite of image `eclipse/che-remote-plugin-runner-java8` while there are on Red Hat registries
`openjdk/openjdk-11-rhel8`  && `openjdk/openjdk-8-rhel8` ?

**Comment by evidolob** [comment]
I think we can use `openjdk/openjdk-11-rhel8` && `openjdk/openjdk-8-rhel8` directly from Red Hat registries, but we need to test them

**Comment by nickboldt** [comment]
If you can't just use bare images from RHCC without having to patch them, consider reusing & updating as needed these:

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-cpp-rhel8/images/latest

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-dotnet-rhel8/images/latest

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-golang-rhel8/images/latest

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-java-rhel8/images/latest

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-node-rhel8/images/latest (Node 10 on RHEL8)

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-php-rhel8/images/latest

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-python-rhel8/images/latest

* https://access.redhat.com/containers/?architecture=AMD64&tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-node/images/latest (Node 8 on RHEL7)

**Comment by nickboldt** [comment]
Ah, I see the WIP is in https://github.com/eclipse/che-theia/tree/reworkImages/dockerfiles/ rather than master branch.

I also see that we're not following the existing convention of using `rhel.Dockerfile` or Dockerfile.rhel, but have created another convention for Dockerfile.rh.

Can I suggest refactoring those to `rhel.Dockerfile` for two reasons?

a) consistency with other builds like the plugin/devfile registries
b) using .Dockerfile suffix means you can get linting and code completion in VSCode automatically.

@benoitf WDYT?

**Comment by evidolob** [comment]
Yes we can try to use images from RHCC, at least we can make sure that they work, if they work @nickboldt you need just replace it in Che plugin registry plugin `meta.yaml`
For those which need to be patched we will use `rhel.Dockerfile` name

**Comment by evidolob** [comment]
@nickboldt I try to use `registry.access.redhat.com/codeready-workspaces/stacks-java-rhel8` as image for java8 vscode extension image and got error:

```
Activating extension Language Support for Java(TM) by Red Hat failed: EACCES: permission denied, mkdir '/home/theia/.theia/'.
```

Java extension doesn't work, it seems that for remote plugin we need to have `/home/theia/' and permissions for remote plugin binary to write in that folder.

**Comment by tsmaeder** [comment]
@evidolob we need a writeable location to put the plugin state. It looks like the path /home/theia is hardcoded somewhere instead of using $HOME

**Comment by evidolob** [comment]
For that error `Activating extension Language Support for Java(TM) by Red Hat failed: EACCES: permission denied, mkdir '/home/theia/.theia/'.` it's a bug, I'm now trying to fix it, after that we will be able to use any RHCC image for remote plugin, if no new bug get out

**Comment by evidolob** [comment]
@tsmaeder it's not hardcoded, remote plugin trying to use value passed from main Theia image, where `/home/theia/` exist. I now fixing that.

**Comment by AndrienkoAleksandr** [comment]
@tsmaeder @evidolob I prepared draft doc https://docs.google.com/document/d/1eoSJ4IeQ13GOhDd6AxkkN9H4zJoYF9lKyl9MJFkIw3E/edit

**Comment by tsmaeder** [comment]
@AndrienkoAleksandr  "Access denied"

**Comment by AndrienkoAleksandr** [comment]
@tsmaeder @benoitf @evidolob  try again this link https://docs.google.com/document/d/1jL7GX5DpDVkaSfrGlP3iJtD8W0WRVtZLMudR67zpZBU

**Comment by evidolob** [comment]
We are done with this issue.

> Note: We decided  to delete `rhel.Dockerfile` files as some of them was based on non public images (RHCC). It is not match sense to have it it OSS project.
