### ISSUE TITLE
The default workspaces namespace/project should be `<username>-che`

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14795]
### Is your task related to a problem? Please describe.
The default workspaces namespace/project should be `<username>-che`

### Describe the solution you'd like
We do not store any info about existing workspaces' namespaces and reconfiguring this value means that every existing workspace would lose their data - it's why we are not able just to change the default value.

Here is a plan of how we could change the default workflow without losing datas for existing workspaces:
1. We introduce new property `che.infra.kubernetes.namespace.default` with default value `<username>-che`. It will be reused for a user's ability to specify any available namespace later.
2. We deprecate existing `che.infra.kubernetes.namespace` but the value MUST NOT BE updated or removed.
3. On workspace start Che Server:
  -  checks if the workspace has target namespaces stored (by default for every workspace it's not)
    - yes (stored): use it for workspace start;
    - no (is absent): checks if namespace with `che.infra.kubernetes.namespace` exist:
      - yes (exists): store this value into workspace and use during start, for example, it may be `workspacefh3642` if workspace was created before our changes
      - no (does not exist): store namespace with name `che.infra.kubernetes.namespace.default` into the workspace and use it for workspace start. Default value is `<username>-che`;

**Comment by skabashnyuk** [comment]
There is no guarantee that it would be fixed for 7.3. We are investigating pitfalls to understand what would be the target release.

**Comment by l0rd** [comment]
@sleshchenko @skabashnyuk this flow looks complicated and involves some extra calls to the k8s API during workspaces creations that I would like to avoid. What about:
- support old behavior using `che.infra.kubernetes.namespace.default=<workspace-id>`
- `<workspace-id>` is the default for 7.3
- `che-<username>` becomes the default on 7.4

By the way I don't consider that a blocker for 7.3 or CRW 2.0 hence let's consider all the pros and cons and make the right choice.

**Comment by nickboldt** [comment]
can we override the prefix/suffix? might want crw-* or *-crw instead of che. Because, ya know, branding reasons. :)

**Comment by metlos** [comment]
Note that this has been worked on in PR https://github.com/eclipse/che/pull/14828.

**Comment by sleshchenko** [comment]
The most of the needed changes are done (che server, helm charts) but this issue is not closed because of che-operator side changes https://github.com/eclipse/che-operator/pull/92
Which we are not able to merge before CRW2.0 is released. (More about why we are not able to merge it can be found in the following David's comment https://github.com/eclipse/che-operator/pull/92#issuecomment-548307265)

This issue is marked as blocked and the remaining work (merge che-operator PR) will be done after CRW2.0 is released.
