### ISSUE TITLE
Can't connect to ws://che-host:8080 when creating new project

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#148]
I started a new che by `docker run -it --privileged -p 8080:8080 codenvy/che:nightly`, then open the dashboard: `http://myip:8080/dashboard`, and create the first project.

But it fails:

![image](http://i.imgur.com/4NA7I5k.png)

The error information is:

> [STDOUT] 2016-01-01 03:21:42,614[rrest.WSClient8]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/che/api/eventbus/?token=dummy_token. 
> [STDOUT] 2016-01-01 03:21:44,608[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/che/api/eventbus/?token=dummy_token because Connection timeout. Retrying

**Comment by TylerJewell** [comment]
I think you need to have this environment variable exposed in the ws agent.
export DOCKER_MACHINE_HOST="yourRemoteIP"
You get this by passing this on the docker command line with -e.

-Tyler

On Thu, Dec 31, 2015 at 7:30 PM -0800, "freewind" notifications@github.com wrote:

I started a new che by docker run -it --privileged -p 8080:8080 codenvy/che:nightly, then open the dashboard: http://myip:8080/dashboard, and create the first project.

But it fails:

The error information is:

[STDOUT] 2016-01-01 03:21:42,614[rrest.WSClient8]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/che/api/eventbus/?token=dummy_token. 

[STDOUT] 2016-01-01 03:21:44,608[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/che/api/eventbus/?token=dummy_token because Connection timeout. Retrying

**Comment by freewind** [comment]
This is the command I use now:

```
docker run -it --privileged -e DOCKER_MACHINE_HOST="159.203.222.119" -p 8080:8080 codenvy/che:nightly
```

The `159.203.222.119` is the ip of my server (which starts the `codenvy/che:nightly`, but the same error is shown

The ip `159.203.222.119` is the real IP I'm using, you can even visit it `http://159.203.222.119:8080/` to have a check

**Comment by ghost** [comment]
Can you actually see DOCKER_MACHINE_HOST if you exec into this container and run `export`?

I have checked your instance of Che, and connections are made to localhost which means the env is not there. 

This is how env argument should look like  -e "DOCKER_MACHINE_HOST=159.203.222.119" 

You seemed to have used " " in the wrong place.

**Comment by freewind** [comment]
@eivantsov thanks! Now after using `-e "DOCKER_MACHINE_HOST=159.203.222.119"`, it's there in `export`:

```
user@75d1c2ee3c6f:/$ export
declare -x CHE_LOCAL_CONF_DIR="/home/user/.che"
declare -x DOCKER_MACHINE_HOST="159.203.222.119"
declare -x HOME="/home/user"
declare -x HOSTNAME="75d1c2ee3c6f"
declare -x JAVA_HOME="/opt/jre1.8.0_65"
declare -x JAVA_VERSION="8u65"
declare -x JAVA_VERSION_PREFIX="1.8.0_65"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
```

I'm still trying and waiting to see the result

**Comment by ghost** [comment]
I have noticed that you did not map ports for workspace agent.

-p 32768-32788:32768-32788 is a must! Alternatively, you may skip port mapping, but use --net=host instead.

When ports aren't mapped, client cannot connect to a workspace agent which is running in a container.

**Comment by freewind** [comment]
@eivantsov Thanks for your shiny eyes :+1:

Yes, I have to add `-p 32768-32788:32768-32788`, now the workspace can be created successfully and I can create project and run them now.

But the issue is still there: when I create a workspace, there are still such errors in the log:

```
[STDOUT] 2016-01-01 15:34:53,937[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/che/api/eventbus/?token=dummy_token because Connection timeout. Retrying 
```

The difference is they are ignored at last, and the workspace is created successfully. 

See the log:

```
[STDOUT] 2016-01-01 15:35:21,971[rest.WSClient16]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/che/api/eventbus/?token=dummy_token. 
[STDOUT] 2016-01-01 15:35:23,966[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/che/api/eventbus/?token=dummy_token because Connection timeout. Retrying 
[STDOUT] 2016-01-01 15:35:27,981[rest.WSClient17]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/che/api/eventbus/?token=dummy_token. 
[STDOUT] 2016-01-01 15:35:29,972[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/che/api/eventbus/?token=dummy_token because Connection timeout. Retrying 
[STDOUT] 2016-01-01 15:35:33,161[ost-startStop-1]  [INFO ] [o.a.c.u.SessionIdGeneratorBase 241]  - Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [100,846] milliseconds.
[STDOUT] 2016-01-01 15:35:33,320[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/user/che/ext-server/webapps/che.war has finished in 111,039 ms
[STDOUT] 2016-01-01 15:35:33,331[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 469]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-01-01 15:35:33,338[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 111338 ms
[STDOUT] 2016-01-01 15:35:33,983[rrest.WSClient6]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/che/api/eventbus/?token=dummy_token. 
[STDOUT] 2016-01-01 15:35:36,303[nio-4401-exec-2]  [INFO ] [o.e.c.a.c.u.ContentTypeGuesser 55]   - Successfully load content types from jar:file:/home/user/che/ext-server/webapps/che/WEB-INF/lib/che-core-api-core-4.0.0-beta-3-SNAPSHOT.jar!/content-types.properties
[STDOUT] 2016-01-01 15:35:36,709[nio-4401-exec-2]  [INFO ] [o.e.c.a.p.s.ProjectService 1348]     - EVENT#project-created# PROJECT#javascript-geyn# TYPE#blank# WS#null# USER#codenvy# PAAS#default#
```

The `export` of the container:

```
user@edd05bd55c01:/$ export
declare -x CHE_LOCAL_CONF_DIR="/home/user/.che"
declare -x DOCKER_MACHINE_HOST="159.203.222.119"
declare -x HOME="/home/user"
```

**Comment by ghost** [comment]
It took a while for the workspace agent to start. Can you repeatedly reproduce such behavior?

**Comment by freewind** [comment]
@eivantsov  yes, I can see such "Not able to connect to" information when creating a workspace every time

**Comment by ghost** [comment]
But the workspace eventually starts?

Exec into a container and run:

cat /etc/hosts

This way we'll see where che-host points to. Then try to manually ping this IP from inside a container.

Out of curiosity where do you launch remote machines?

**Comment by freewind** [comment]
@eivantsov I need to do some other things the next two days, I will try and response then. But thanks ~

**Comment by freewind** [comment]
The workspace is eventually starts and working well, so I'm not sure if that's really an error or just a reminder, because the log level is `WARN`:

```
[STDOUT] 2016-01-05 07:04:43,300[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/che/api/eventbus/?token=dummy_token because Connection timeout. Retrying 
```

But it has tried 54 times before giving up, and then we can open the workspace in IDE, and working on it.

My `export` in its container: 

```
twer@ubuntu-4gb-sfo1-01:~$ docker exec -it 11ef753f2018 bash

user@11ef753f2018:/$ export
declare -x CHE_LOCAL_CONF_DIR="/home/user/.che"
declare -x DOCKER_MACHINE_HOST="159.203.222.119"
```

and I even added `che-host` into `/etc/hosts` before creating a workspace:

```
user@11ef753f2018:/$ cat /etc/hosts
172.17.0.2  11ef753f2018
127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
159.203.222.119 che-host
```

And it's pingable:

```
user@11ef753f2018:/$ ping che-host
PING che-host (159.203.222.119) 56(84) bytes of data.
64 bytes from che-host (159.203.222.119): icmp_seq=1 ttl=64 time=0.270 ms
64 bytes from che-host (159.203.222.119): icmp_seq=2 ttl=64 time=0.137 ms
64 bytes from che-host (159.203.222.119): icmp_seq=3 ttl=64 time=0.146 ms
```

**Comment by TylerJewell** [comment]
@eivantsov This log seems fairly interesting.  Let's capture this for analysis in our backlog.  I think we could ask engineers to support the investigation after we complete beta release.

**Comment by ghost** [comment]
che-host should be automatically added to /etc/hosts

I cannot reproduce this behavior locally with Docker

**Comment by freewind** [comment]
@eivantsov `che-host` doesn't added to `/etc/hosts` in my try. I will record a video about this later

**Comment by ghost** [comment]
I am talking about hosts file in a container that is running in Che server container.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/5337267/12149888/9041d822-b4a6-11e5-8dc0-81b55839bf51.png)

Docker in Docker

Just started a machine, here's my /etc/hosts

**Comment by ghost** [comment]
This should be fixed by https://github.com/codenvy/che-core/pull/625

**Comment by freewind** [comment]
@eivantsov This issue appear again with latest "nightly" build (I use https://eclipse-che.readme.io/docs/usage-docker#using-docker-syntax way to start che)

It doesn't always appear, but more often than the OK ones.

Today I started a che server and tried to created two projects with separate workspace, and first one is OK, but the second one is failed (even retried several times).

The successful log for the first project is:

```
[STDOUT] 2016-02-15 07:44:18,224[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[STDOUT] Mon Feb 15 07:44:27 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2016-02-15 07:44:27,597[rrest.WSClient1]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/ide/api/eventbus/?token=dummy_token.
[STDOUT] 2016-02-15 07:44:27,861[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 980]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ide.war has finished in 9,636 ms
[STDOUT] 2016-02-15 07:44:27,870[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-02-15 07:44:27,876[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 9975 ms
```

The failed log for the second project:

```
[STDOUT] 2016-02-15 08:12:56,994[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.29
[STDOUT] 2016-02-15 08:12:57,092[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 916]        - Deploying web application archive /home/user/che/ws-agent/webapps/ide.war
[STDOUT] Mon Feb 15 08:13:06 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2016-02-15 08:13:06,839[rrest.WSClient1]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/ide/api/eventbus/?token=dummy_token.
[STDOUT] 2016-02-15 08:13:08,684[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/ide/api/eventbus/?token=dummy_token because Connection timeout. Retrying
[STDOUT] 2016-02-15 08:13:12,700[rrest.WSClient2]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://che-host:8080/ide/api/eventbus/?token=dummy_token.
[STDOUT] 2016-02-15 08:13:14,689[ventBusClient-0]  [WARN ] [.c.a.c.n.WSocketEventBusClient 256]  - Not able to connect to ws://che-host:8080/ide/api/eventbus/?token=dummy_token because Connection timeout. Retrying
```

I didn't do anything else between the two operations. I had `docker exec -it xxx bash` to the failed container, and can see the correct definition of `che-host` in `/etc/hosts`

**Comment by freewind** [comment]
@eivantsov I also have some questions about this log since I'm debugging on it now. 

Where does this `Open connection to ...` operation happen? I found two possible locations, but not sure which one is correct:
1. From the che server (not in workspace container or machine), it will ping the agent webapp inside the workspace container, to check if it's working
2. From the workspace container (or machine, if they are the same thing here), it will ping the che server to check if itself working

I guess it should be the 2nd one, but can't find enough clue to make sure. Could you provide me some information about how this process works?

**Comment by ghost** [comment]
In fact, server and ws-agent ping each other. In this case, it's ws-agent that tries to connect to server.

I have shared some info in another issue - it's related to Java security features. `urandom` should do the trick. This happens to Digital Ocean VMs - Azure, RackSpace, Amazon - are all good and Che-friendly.

I think you have found a solution already.

**Comment by freewind** [comment]
@eivantsov Yes, thanks for your help!

**Comment by hongweiyi** [comment]
`export DOCKER_MACHINE_HOST="yourRemoteIP"`

LGTM

**Comment by freewind** [comment]
@hongweiyi The reason is actually because of another issue https://github.com/eclipse/che/issues/176

**Comment by hongweiyi** [comment]
@freewind Ah, I see. Thanks!
