### ISSUE TITLE
Theia shows two dialogues when previewUrl is defined in command

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14802]
### Is your enhancement related to a problem? Please describe.
When command has defined `previewUrl` attribute and command is executed, theia shows 2 dialogues, one for PreviewUrl and second is pop-up from port-plugin. This might be confusing to the user.

![theia-previewurl](https://user-images.githubusercontent.com/1160903/66355922-50ec1d80-e969-11e9-8e3e-37c11e588cb8.png)

### Describe the solution you'd like
We should probably show just PreviewUrl when it is defined. Or it should be at least more visible than port-plugin popup.

### Additional context
Preview url in devfile is implemented here https://github.com/eclipse/che/issues/13945

**Comment by l0rd** [comment]
+1 to show previewUrl only

**Comment by l0rd** [comment]
I have assigned this issue to `team/platform` but it can be `team/ide2` as well.

**Comment by sparkoo** [comment]
@l0rd I'm not sure we have any Theia hackers in the team. Nothing to do with this issue on the server I guess.

**Comment by l0rd** [comment]
Ok assigned to IDE2

**Comment by mmorhun** [comment]
So, to resolve this problem we have to improve ports plugin to ignore already exposed routes.
@benoitf are you ok with such solution?

**Comment by mmorhun** [comment]
Fixed by changing Ports plugin to not to show its dialog if an exposed port has a preview url.
