### ISSUE TITLE
Fix typo "retreive" -> retrieve when unable to stop workspace with chectl

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#14808]
### Describe the bug
```
[apupier@linux ~]$ chectl server:stop
  ✔ Verify Kubernetes API...OK
  ✔ Verify if Che is deployed into namespace "che"
    ✔ Found running che deployment
    ✔ Found running postgres deployment
    ✔ Found running keycloak deployment
    ✔ Found running plugin registry deployment
    ✔ Found running devfile registry deployment
  ✔ Check Che server status...RUNNING (auth enabled)
  ✖ Stop Che server and wait until it's ready to shutdown
    → For instructions to retreive a valid access token refer to https://www.eclipse.org/che/docs/che-6/authentication.html
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
maybe nice to point to Che 7 documentation if there is any (in the same error message)

**Comment by l0rd** [comment]
Thanks @apupier for catching this
