### ISSUE TITLE
Enable branding on the ConsoleLink elements created by the che operator

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#14809]
### Is your enhancement related to a problem? Please describe.

Currently `ConsoleLink` object created by the Che operator has fixed upstream Che branding.

### Describe the solution you'd like

it should be possible to override the name, display name and icon of the `ConsoleLink` object created by the operator.

### Additional context

This is related to this issue comment: https://github.com/eclipse/che/issues/14745#issuecomment-539469236

**Comment by davidfestal** [comment]
cc @nickboldt @l0rd

**Comment by l0rd** [comment]
I am setting it as `severity/P2` as it doesn't have a major impact on UX but I am ok to bring it to 7.3.0 if the fix is easy: how could we override name/display name/icon for CRW build only?

**Comment by ibuziuk** [comment]
PR https://github.com/eclipse/che-operator/pull/101 merged, Closing
