### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by snorthov** [eclipse-che/che#14811]
## Summary

Imagine I am a naive user and wish to kick the tires of Che to understand whether I might want to use it for development in my company.  I do not want to start by installing Che on a Kubernetes cluster.  I google "Che 7 getting started"

![image](https://user-images.githubusercontent.com/11139850/66407462-3e023900-e9bb-11e9-9ab2-184f5c1301dd.png)

Eventually this leads me to this link: https://www.eclipse.org/che/getting-started/cloud/
I run the Node example:

![image](https://user-images.githubusercontent.com/11139850/66407621-81f53e00-e9bb-11e9-83a8-8672fc1a9ba1.png)

Eventually I get an environment, but the README.md is not helpful in telling me what I should do.

![image](https://user-images.githubusercontent.com/11139850/66408107-558df180-e9bc-11e9-84a1-d3324dfa77f9.png)

When I run the "bring your own code" example, the experience isn't much better.  It would be cool if Che sniffed my repo and did something, but given that it doesn't, where is the documentation that tells me what to do build and run my code?

![image](https://user-images.githubusercontent.com/11139850/66408286-b3223e00-e9bc-11e9-954c-9036e261290f.png)

**How is a novice expected to get started and evaluate Che for use by their company?**

**Comment by l0rd** [comment]
@snorthov thank you for raising this. The README file of this sample hasn't been updated since a long time. The file is [here](https://github.com/che-samples/web-nodejs-sample/blob/master/README.md) if you are interested in becoming a contributor to the project.

**Comment by snorthov** [comment]
> The file is here if you are interested in becoming a contributor to the project.

Thanks for the link, however, I'd need to know how to get started before I could contribute to the example code that is supposed to show how people get started.  ;-)

Where is the getting started link / documentation for Che?

**Comment by tolusha** [comment]
@snorthov 
https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/
https://www.eclipse.org/che/docs/che-7/running-che-locally/

**Comment by imrahul361** [comment]
how can i contribute i don't have any idea how to setup codebase and work on it.can anyone guide me through it?like what and how to do?

**Comment by tolusha** [comment]
@imrahul361 
That's a good question.

Here is a codebase [1]. 
You can start reading REAMDE [2] and contributing guide [3]
For sure it is needed to read che doc in general [4]
And you always welcome to ask question in the public channel [5] 

[1] https://github.com/eclipse/che
[2] https://github.com/eclipse/che/blob/master/README.md
[3] https://github.com/eclipse/che/blob/master/CONTRIBUTING.md
[4] https://www.eclipse.org/che/docs/che-7
[5] https://mattermost.eclipse.org/eclipse/channels/eclipse-che

**Comment by imrahul361** [comment]
Press F5 or click here to try again.
Starting Init Plugin Broker
Cleaning /plugins dir
Unified Che Plugin Broker
Starting Che plugins and editor processing
List of plugins and editors to install
- che-incubator/typescript/1.30.2 - Typescript language features
- eclipse/che-machine-exec-plugin/7.3.2 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
- eclipse/che-theia/7.3.2 - Eclipse Theia
Starting VS Code and Theia plugins processing
Downloading VS Code extension for plugin 'che-incubator/typescript/1.30.2'
All plugins have been successfully processed
pulling image "quay.io/eclipse/che-jwtproxy:dbd0578"
Successfully pulled image "quay.io/eclipse/che-jwtproxy:dbd0578"
Created container
Started container
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspaceyxy0ou99y1xkjyuk.dash-dev-d5f5654b8-8wnxg" is forbidden: [maximum cpu usage per Pod is 6, but limit is 8245m., maximum memory usage per Pod is 3Gi, but limit is 4427382784.]', 'workspaceyxy0ou99y1xkjyuk.dash-dev-d5f5654b8'"


how to setup eclipse che in openshift
@tolusha

**Comment by tolusha** [comment]
@imrahul361 
The error might confuse.
The workspace is being created requests 4427382784 but available only 3Gi
I am not aware how openshift is created, but in case of minishift/minikube I can set maxim values from cli:
`minikube start --docker-opt userland-proxy=false --memory 12GB --vm-driver virtualbox --cpus 4`

**Comment by imrahul361** [comment]
how else can i setup the codebase and work on the issues?? @tolusha

**Comment by PranayChauhan2516** [comment]
What can I do to solve this question? As now the documentation has been improved now and one can refer this https://www.eclipse.org/che/docs/che-7/running-che-locally/
