### ISSUE TITLE
Handle CRLF line endings in plugin meta.yamls

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14827]
### Is your enhancement related to a problem? Please describe.
Currently the plugin registry build expects plugin metas to have linux line endings (`LF`). This can cause problems building the registry on Windows, where line endings may be converted automatically. We should improve our scripts to accommodate `CRLF` line endings as well. 

### Additional info
https://github.com/eclipse/che/issues/14807#issuecomment-539976839

**Comment by benoitf** [comment]
can it be solved also by setting the git config line endings ?

**Comment by amisevsk** [comment]
@benoitf I believe so, that's a good point.

**Comment by ibuziuk** [comment]
@ericwill might be interesting for the plugins team ;)

**Comment by ericwill** [comment]
This is no longer a problem -- we no longer let users write their own meta.yamls, they are generated automatically.
