### ISSUE TITLE
Happy path tests failed on "Run debug and check application stop in the breakpoint" step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14822]
### Describe the bug
Happy path tests fails sometimes on the step "_Run debug and check application stop in the breakpoint_", for example https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/294/consoleFull:
```
    ✓ Add debug configuration options (7430ms)
        ▼ Editor.selectTab "PetClinicApplication.java"
        ▼ Ide.closeAllNotifications
        ▼ Editor.waitTab "PetClinicApplication.java"
        ▼ Editor.clickOnTab "PetClinicApplication.java"
        ▼ Ide.closeAllNotifications
        ▼ Editor.waitTabFocused "PetClinicApplication.java"
        ▼ TopMenu.selectOption "View"
        ▼ TopMenu.clickOnTopMenuButton "View"
        ▼ Ide.closeAllNotifications
        ▼ TopMenu.clickOnSubmenuItem "Debug"
        ▼ Ide.waitRightToolbarButton
        ▼ DebugView.clickOnDebugConfigurationDropDown
        ▼ DebugView.clickOnDebugConfigurationItem "Debug (Launch) - Current File"
        ▼ Ide.performKeyCombination ""
        ▼ DebugView.clickOnRunDebugButton
        ▼ PreviewWidget.refreshPage
        ▼ Editor.waitStoppedDebugBreakpoint title: "PetClinicApplication.java" line: "32"
        ▼ Editor.getLineYCoordinates line: "32"
        ▼ PreviewWidget.refreshPage
        ▼ Editor.waitStoppedDebugBreakpoint title: "PetClinicApplication.java" line: "32"
        ▼ Editor.getLineYCoordinates line: "32"
    1) Run debug and check application stop in the breakpoint
```
There was start web application error:
![screenshot-Run_debug_and_check_application_stop_in_the_breakpoint](https://user-images.githubusercontent.com/1197777/66471204-99075f00-ea93-11e9-9149-4893664bf07d.png)
![Screenshot from 2019-10-09 11-27-49](https://user-images.githubusercontent.com/1197777/66471339-d4a22900-ea93-11e9-8f9c-43cab18bc542.png)

### Screencast
https://youtu.be/-0WHCVvHBHU

### Logs
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/294/artifact/logs-and-configs/

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
https://github.com/eclipse/che/blob/master/e2e/tests/e2e_happy_path/HappyPath.spec.ts#L264

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by musienko-maxim** [comment]
This problem was not reprodused lat 3 days. I am observing couple days if it is not reproduced i will close the issue

**Comment by rhopp** [comment]
This has not been reproduced for some time.
