### ISSUE TITLE
Please add native Avro schema json editing to Che

### ISSUE THREAD

**Issue by mpouttuclarke** [eclipse-che/che#1483]
Avro and ParquetAvro are the dominant serialization formats in big data.  ParquetAvro uses the Avro metadata for Parquet storage, so they share a common JSON schema.  Since Che is natively JavaScript on the front end, editing JSON Avro schemas with Che will perform better than alternatives, and also has the potential to be more feature-rich.  
http://avro.apache.org/docs/current/spec.html 
https://github.com/Parquet/parquet-mr/tree/master/parquet-avro 

It is important to support the core schema as well as allowing user-defined annotations.

**Comment by TylerJewell** [comment]
I think the requirement needs more detail. You can edit files of any type in the editor today.   This also may need to be a requirement for the Orion editor, if there are specific functionality that they need to provide to have it inherited within Che.  Can you elaborate on the scenarios.

**Comment by TylerJewell** [comment]
@skabashnyuk @vparfonov - do you have any technical observations on this request?

**Comment by TylerJewell** [comment]
Closing issue - this is not something we plan in the near term.
