### ISSUE TITLE
Completion and hover are cropped if expanding over another view

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#14838]
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. move th eoutput view to the right of the editor
2. call hover or completion so that it goes over the output view

a simplr line missing if Browser window has the focus:
![Screenshot from 2019-10-10 09-15-11](https://user-images.githubusercontent.com/1105127/66547131-d4129c80-eb3e-11e9-8f95-76eec87c9117.png)

For hover, with the whole end missing if the window doesn't have the focus:
![completelyCroppedWithoutFocusAndCroppedLineWithFocus](https://user-images.githubusercontent.com/1105127/66547440-88142780-eb3f-11e9-940a-8a0fa3ac9358.gif)

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux Fedora 30
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
using Chrome

**Comment by RomanNikitenko** [comment]
related issues for `Theia`:
https://github.com/eclipse-theia/theia/issues/2417
https://github.com/eclipse-theia/theia/issues/6272
