### ISSUE TITLE
Some plugins don't load from first time with remote runtime binary

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14833]
### Describe the bug
Some plugin doesn't loads from first time with remote runtime binary. After refresh browser page such plugins begin work.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create workspace from devfile https://gist.github.com/AndrienkoAleksandr/635da21bb8f409ce9e86d9faa4066df8
Expected result: after workspace starting: oc connector should work.
Actual result: oc connector works after refresh browser page.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr PR has been merged, can we close the issue now ?
