### ISSUE TITLE
[Hosted Che] Forbidden!Configured service account doesn't have access. Service account may have been revoked.

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14830]
### Describe the bug

After generating an ssh key for use with a private github repo, I restarted my che.openshift.io workspace. And it broke as in https://github.com/eclipse/che/issues/12366

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify che.openshift.io (7.1.0)

![image](https://user-images.githubusercontent.com/227597/66490813-bf230400-ea7f-11e9-9eb3-5c92368b2198.png)

### Steps to reproduce

1. import a devfile into che.openshift.io such as https://che.openshift.io/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/php-web-simple/devfile.yaml

2. when the workspace loads, hit F1 then type "ssh" to find ssh commands.

3. generate a SSH key. Upload it to github. Note the message that appears in the bottom right corner of the Theia editor:

```
Che Git plugin can leverage the generated keys now. To make them available in every workspace containers please restart your workspace.
```

4. shutdown workspace as directed. Restart it.

5. Wonder what cloud gods have forsaken you when you see this:

```
Error: Failed to run the workspace: "Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/nickboldt2-che/secrets. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. secrets "workspaceqqsx7krkwhp1b06s-github-com" is forbidden: exceeded quota: object-counts, requested: secrets=1, used: secrets=20, limited: secrets=20. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password."
```

![image](https://user-images.githubusercontent.com/227597/66491728-3b6a1700-ea81-11e9-8516-798b64eb68aa.png)

### Environment
   - [x] Hosted Che

**Comment by amisevsk** [comment]
@nickboldt Could you list the secrets in your namespace? Is the issue a quota issue in general or are we creating secrets that aren't getting deleted?

**Comment by vparfonov** [comment]
should be fixed by https://github.com/eclipse/che/pull/14950
