### ISSUE TITLE
Allow to display images instead of product name

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14845]
### Is your enhancement related to a problem? Please describe.

For CodeReady Workspaces it's better to display images next to the logo.
Displaying `Red Hat CodeReady Workspaces` looks not good.

The solution is to make it possible to display images next to the logo to be able to display images

https://github.com/redhat-developer/codeready-workspaces/blob/master/product/branding/CRW_SaaS_Wordmark_black.svg

It should be theme dependent.

Subtask for https://github.com/eclipse/che/issues/14110

**Comment by tsmaeder** [comment]
@vitaliy-guliy why is this an upstream issue and now in the crw jira? Also, do I understand correctly, that you just want to replace the image with a different one?

**Comment by vitaliy-guliy** [comment]
@tsmaeder actually it's a subtask for this https://github.com/eclipse/che/issues/14110

**Comment by vitaliy-guliy** [comment]
It has to be fixed in the current sprint.
