### ISSUE TITLE
Please add Clojure support to Eclipse Che

### ISSUE THREAD

**Issue by mpouttuclarke** [eclipse-che/che#1484]
I have added a similar ticket on the CCW issue list:
https://github.com/laurentpetit/ccw/issues/871 

I am currently building expert systems in Clojure and would love to use Che rather than Eclipse.

**Comment by TylerJewell** [comment]
@mpouttuclarke - we will be adding in Q3 support for a common programming language server protocol that will allow different language services to implement a common protocol for intellisense.  If the CCW system can provide its intellisense as a server over that protocol, then it will have drop-in functionality into Che.  

You can see more here.
https://github.com/Microsoft/vscode-languageserver-protocol/issues/8

**Comment by TylerJewell** [comment]
Cross-linking and closing the other issue: #1206.

**Comment by staypufd** [comment]
Any update on adding Clojure support?

**Comment by staypufd** [comment]
Both this and it's referencing 1206 bug got closed. So does that mean that there is no intent to add Clojure support?

**Comment by TylerJewell** [comment]
We are only adding in language server support for languages that have had a formal language server created for them. The language server protocol is fairly new and we are hoping that the languages fill out soon. You can see what has been done in the open source realm here - we are adding 1-2 of these / month.

There is no Clojure support, so we will wait for the community to get one packaged. Will close this in the mean time and include this link in the other issues for people who are going through history, and they will not have to scratch their head the way you did.

http://langserver.org/
