### ISSUE TITLE
Investigate failed Java selenium E2E test 'DirectUrlFactoryWithSpecificBranchTest'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#14842]
There are one Java selenium test constantly failing :
- DirectUrlFactoryWithSpecificBranchTest

For example: https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-master-ocp/828/Selenium_20tests_20report/

### Runtime
   - [x] Openshift (include output of `oc version`)

### Installation method
 - [x] ocp.sh script

### Environment
  - [X] other: Codenvy CI

**Comment by artaleks9** [comment]
The reason of it is described in the https://github.com/eclipse/che/issues/14846

**Comment by dmytro-ndp** [comment]
The issue has been fixed at the che-theia level.
