### ISSUE TITLE
Devfile Registry Should Serve Pictures

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14844]
We currently have no place to serve the images from that represent the devfiles in the meta.yaml in the devfile registry.
Since these svg files are often developed together, we should find a way to serve those files from the devfile registry and we should be able to reference them in a non-absolute way from the meta.yaml file.
Currently, we reference the images at their github location, but abusing Github as a content delivery network seems asking for trouble.
See here for examples: https://github.com/redhat-developer/codeready-workspaces/tree/master/dependencies/che-devfile-registry/devfiles (PR's pending)

**Comment by tsmaeder** [comment]
cc @nickboldt as this is probably crw 2.0-relevant.

**Comment by amisevsk** [comment]
If there's any info on how Theia would handle a relative path, I can implement this no problem. My main issue is knowing what to put for the icon/picture path so that Theia will be able to process it.

**Comment by tsmaeder** [comment]
P1, because crw 2.0-relevant

**Comment by amisevsk** [comment]
> I don't think theia handle devfile images, that would be more the dashboard, right? I think it would make sense to do the same "relative url" syntax as in html?

AFAICT the only place images listed in devfiles (the icons) are used is in Theia; the dashboard doesn't show images for plugins currently. 

The concern with relative URLs is that I don't think the workspace is pulling from the devfile registry directly, and is instead being fed config from Che itself -- what does a relative URL refer to in this case?

**Comment by amisevsk** [comment]
@tsmaeder I don't think there's a good way to get the devfile registry to serve pictures currently, since every time it's deployed it can be with a different URL. A prerequisite for this would be some way to handle the relative links we'd be putting in the devfile registry (e.g. if I put `./my-icon` for an icon, the dashboard tries to get the image from `eclipse-che-url.com/dashboard/my-icon`). I think the dashboard would need to handle it as a special case.

WDYT?

**Comment by tsmaeder** [comment]
@amisevsk I agree that there is no short-term fix here: the underlying problem is that the plugin registry is just passively serving files which are interpreted 100% by the consumer. If we ever want to scale the registry (to thousands of plugins), we'll need to have a proper API (for example, to search).
Since we control both ends of the communication, I don't see a problem with asking consumers to interpret relative url's for the time being.

**Comment by amisevsk** [comment]
@tsmaeder I created issue https://github.com/eclipse/che/issues/15091 for provisioning a registry's public endpoint as an env var to support this; if we could rely on knowing what our URL is, I could implement this without much trouble, even without a proper API (we already do it for the devfile registry, for cached project zips).

The issue with consumers interpreting relative URLs is that we would still need to pass the registry URL around -- Theia gets a devfile from Che; does it know where that devfile came from?

**Comment by sleshchenko** [comment]
It seems to be fixed now https://github.com/eclipse/che-devfile-registry/tree/master/images
