### ISSUE TITLE
Move all Che Theia docker images from DockerHub to the quay.io 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14849]
This is allow as to have ability to manage CRUD operation much more easier than on the DockerHub Eclipse  Organization

**Comment by ibuziuk** [comment]
@vparfonov should this issue be part of the CI migration to centosCI for Che theia ?

**Comment by evidolob** [comment]
@ibuziuk Yes, I have plan to move on centos CI and to quay.io in same time
