### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#14848]
## Summary

I wonder if che7 supports IPv6 configuration in workspace. 
If so, please let me know how to set it up.

**Comment by tolusha** [comment]
@kellyhyomin 
What kind of configuration do you mean?

**Comment by kellyhyomin** [comment]
I am wondering if I need to configure IPv6 separately in the configmap.yaml file to apply IPv6 to the workspace container.

**Comment by skabashnyuk** [comment]
I'm not aware of any tests/usage of Eclipse Che on IPv6. @kellyhyomin did you try it? Did you mat any issues?

**Comment by Xhelliom** [comment]
I does not seem to have IPv6 connectivity.
bash-5.0$ curl -6 google.com
curl: (7) Couldn't connect to server
