### ISSUE TITLE
Missing Eclipse licenses in che-schema files

### ISSUE THREAD

**Issue by anselmov** [eclipse-che/che#14852]
Some .sql files are missing Eclipse Public License v1.0
- wsmaster/che-core-sql-schema/src/main/resources/che-schema/5.8.0/1__add_foreigh_key_indexes.sql
- wsmaster/che-core-sql-schema/src/main/resources/che-schema/5.11.0/1__optimize_user_search.sql
- wsmaster/che-core-sql-schema/src/main/resources/che-schema/5.11.0/postgresql/1__optimize_user_search.sql
- wsmaster/che-core-sql-schema/src/main/resources/che-schema/5.7.0/2__remove_match_policy.sql

and (like in https://github.com/eclipse/che/issues/5891) the copyright owner should be Red Hat.

Desired header:
```
--
-- Copyright (c) 2012-2019 Red Hat, Inc.
-- All rights reserved. This program and the accompanying materials
-- are made available under the terms of the Eclipse Public License v1.0
-- which accompanies this distribution, and is available at
-- http://www.eclipse.org/legal/epl-v10.html
--
-- Contributors:
--   Red Hat, Inc. - initial API and implementation
--
```

**Comment by skabashnyuk** [comment]
This is task can't be fixed since it will chance CRC sum of sql scripts recorded in existed installation and will make an upgrade to the new version impossible.
