### ISSUE TITLE
Error when trying to install custom plugin

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#14853]
### Describe the bug

I have a custom plugin registry added in my che workspace.
When I try to install my plugin, I get the following error:
````
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspacetqg779x0yx5o61tt failed with error: Plugin '' is invalid. Field 'apiVersion' contains invalid version 'v3'"
````

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: I'm using chectl; I don't know which version of che it uses

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
````
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
````
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
````
chectl server:start -p minikube
````
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
@anthonma
Could you provide meta.yaml of the plugin also?

**Comment by anthonma** [comment]
I've solved it. I changed the value of the apiVersion field in my meta.yaml to v2.
The readme of the che-plugin-registry says v2 and v1 are accepted and this guide https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/
says its v3, so I assume that it is a misstake.

**Comment by tolusha** [comment]
@anthonma
Thank you for noticing. We will fix that.

**Comment by anthonma** [comment]
I have a new problem now. I changed the plugin registry to my custom one and now I can't start a workspace.
It failes with the following error:
````
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceytbkkqobvv6mzvgw failed with error: Downloading http://che-plugin-registry-che.192.168.99.101.nip.io/resources/github.com/che-incubator/ms-code.typescript/releases/download/v1.35.1/che-typescript-language-1.35.1.vsix failed. Status code 404"
````

**Comment by tolusha** [comment]
Does your custom plugin registry contain typescript plugin?

**Comment by anthonma** [comment]
Do you mean che-incubator/typescript? If so, the registry contains it.

**Comment by anthonma** [comment]
The problem above is solved. I think it's because I rebuilt and redeployed the custom plugin registry.
Unfortunately I have another Error:
````
Failed to apply default image tag "eclipse/che-theia-endpoint-runtime:next .": couldn't parse image reference "eclipse/che-theia-endpoint-runtime:next .": invalid reference format
Error: InvalidImageName
````

**Comment by anthonma** [comment]
I'm getting two types of Errors now.
They both occure, when I try to install a plugin. Che shows that the plugin has been installed and the workspace has to be restarted.
While restarting the errors occure.
If the plugin was installed via the default registry it says:
````
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedScheduling', '0/1 nodes are available: 1 Insufficient memory.', 'workspacepp8sg686ouz6pngf.maven-64c786579c-h8ml9'"
````
and when it was installed via my custom registry it says:
````
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspace1tvewkp2t97z0o2w failed with error: Downloading http://plugin-registry-che.192.168.99.103.nip.io/resources/github.com/che-incubator/ms-code.typescript/releases/download/v1.35.1/che-typescript-language-1.35.1.vsix failed. Status code 404"
````

**Comment by thisHermit** [comment]
Hey @anthonma,
Could you please help me out in finding these logs? 

I am unable to see any error messages and I am unable to find the way to find the logs and as I am working on a similar issue #14871, I was hoping you could help.

**Comment by anthonma** [comment]
Hey @thisHermit I get these logs automaticaly, when I restart a workspace after installing a plugin.
I'm doing this via the che dashboard.
And the error messages are shown at the bottom of the screen.

If you are using minikube to run your kubernetes cluster you can follow that video https://www.youtube.com/watch?v=ZRHwo3694-w&feature=youtu.be
to get the theia backend.
