### ISSUE TITLE
`Find All references` doesn't exist for typescript plugin

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#14856]
### Describe the bug
`Find All references` doesn't work for typescript plugin. This feature works fine for VsCode, but doesn't work for che-theia.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Open some typescript file and select some method or class name.
2. Click right mouse to open context menu.

### Expected behavior
In the context menu should be item `Find all references` like in the VsCode:
<img width="960" alt="Screenshot_20191011_144845" src="https://user-images.githubusercontent.com/6873095/66649454-dfe18a00-ec36-11e9-9bfb-bceab07953c0.png">

### Actual behavior
 `Find all references` is absent.
<img width="960" alt="Screenshot_20191011_144836" src="https://user-images.githubusercontent.com/6873095/66649509-09021a80-ec37-11e9-994f-c31adb88667b.png">

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by AndrienkoAleksandr** [comment]
Hmm... I removed P2, because I see we have feature 'Peek References' which is close to 'Find All references'

**Comment by tolusha** [comment]
It is interesting to check if latest version fixes the problem

**Comment by tsmaeder** [comment]
I don't think the out-of-line references view is implemented at all in Theia. We should open an issue over there. But yes, it's a PITA when browsing large lists of references.

**Comment by tsmaeder** [comment]
And here it is: https://github.com/eclipse-theia/theia/issues/4784.

**Comment by tsmaeder** [comment]
Note that plugins are added to che-theia inside the docker build of the theia image.
