### ISSUE TITLE
Verify Che 6 to Che 7 upgrade using operator works for all updated containers

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14864]
Followup from https://github.com/eclipse/che/issues/14200

### Is your task related to a problem? Please describe.

Goal here is to verify that an old Che 6.x install using old containers can be updated to new 7.3 using newer containers, via an operator-based update as discussed in https://github.com/eclipse/che/issues/14200#issuecomment-540124798 (and below).

* PVC: registry.access.redhat.com/ubi8-minimal:8.0-159 -> registry.access.redhat.com/ubi8-minimal:8.0-213
* Postgres: centos/postgresql-96-centos7:20190912-81b8a3a to centos/postgresql-96-centos7:9.6
* Che Server eclipse/che-server:6.19.0 to eclipse/che-server:7.2.0
* keycloak eclipse/che-keycloak:6.19.0 to eclipse/che-keycloak:7.2.0

### Describe the solution you'd like

Automated test that will:

* install old Che 6.19 via operator, with custom image versions noted above
* cause update to occur to update to newer 7.x operator, with default images set

**Comment by tolusha** [comment]
@nickboldt 
Is it still relevant?
