### ISSUE TITLE
Left side menu of docs site is not fully accesible

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14861]
### Describe the bug
Che docs site has left side menu with docs content. But when menu is longer than screen size of browser it is not possible to access 

### Expected behavior
When user scrolls the page, the menu be scrolled too

### Screenshots
![Screenshot from 2019-10-11 16-44-08](https://user-images.githubusercontent.com/15607393/66656280-5d60c680-ec46-11e9-8b2d-b4446c9c509a.png)
![Screenshot from 2019-10-11 15-53-46](https://user-images.githubusercontent.com/15607393/66656295-62257a80-ec46-11e9-97d9-ebba4d6d8bf4.png)

![docs-site-bug](https://user-images.githubusercontent.com/15607393/66656692-2a6b0280-ec47-11e9-87e3-5c23cde0fe3d.gif)

### Additional context
It is possible to access other items if zoom out the page (see screenshots)

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/14294
