### ISSUE TITLE
Remove the docker source repository for che.server.secure_exposer.jwtproxy.image

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#14863]
Please remove "quay.io" for the following property @ 7.2.0:

https://github.com/eclipse/che/blob/7.2.0/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties:

che.server.secure_exposer.jwtproxy.image=quay.io/eclipse/che-jwtproxy:dbd0578

changed to 

che.server.secure_exposer.jwtproxy.image=eclipse/che-jwtproxy:dbd0578

**Comment by nickboldt** [comment]
No can do.

The image only exists on the Quay repo:

https://quay.io/repository/eclipse/che-jwtproxy?tag=dbd0578&tab=tags (1 month old, with latest build 18 hrs old)

On Docker, only older ones are present:

https://hub.docker.com/r/eclipse/che-jwtproxy/tags (1yr old)

**Comment by nickboldt** [comment]
Also we can't re-release 7.2.0 :)

**Comment by rbcminghou** [comment]
Can we make the change in the next release?
