### ISSUE TITLE
che-machine-exec image being published to BOTH quay.io and docker.io? 

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14860]
Why is che-machine-exec`:next` hosted at docker.io [1] but che-machine-exec`:7.2.0` and `:nightly` are on quay.io [2] ?

Should `:next` move over too? Or is it no longer in play (deprecated, not used) now that we're past 7.0.0? I'm asking because it was last updated 14 days ago, the same time that 7.2.0 was released.

[1] https://hub.docker.com/r/eclipse/che-machine-exec/tags?page=1&ordering=last_updated
[2] https://quay.io/repository/eclipse/che-machine-exec?tab=tags

May be a followup to https://github.com/eclipse/che/issues/14357

**Comment by tolusha** [comment]
/cc @amisevsk 
Could you help with this question?

**Comment by amisevsk** [comment]
I believe the dockerhub version is left for compatability with old deploys of Che, `docker.io/eclipse/che-machine-exec:nightly` hasn't updated in two weeks. 

But I also have no familiarity with the che-machine-exec release process.

**Comment by AndrienkoAleksandr** [comment]
We clean up release cycle of the che-machine-exec and for now we use only images from quay.io registry and Centos CI. @ibuziuk knows about release cycle che-machine-exec more.
