### ISSUE TITLE
Namespace name had disappeared from command prefix in task popup

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14862]
### Describe the bug
Happy path tests are permanently failing on step "_Validation of workspace build and run_", for example:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/2355/console
```
  Validation of workspace build and run
        ▼ TopMenu.selectOption "Terminal"
        ▼ TopMenu.clickOnTopMenuButton "Terminal"
        ▼ Ide.closeAllNotifications
        ▼ TopMenu.clickOnSubmenuItem "Run Task..."
        ▼ QuickOpenContainer.waitContainer
        ▼ QuickOpenContainer.clickOnContainerItem "che: build-file-output"
        ▼ QuickOpenContainer.waitContainer
    1) Build application


  8 passing (11m)
  1 pending
  1 failing

  1) Validation of workspace build and run
       Build application:
     TimeoutError: Waiting for element to be located By(xpath, //div[@class='quick-open-entry']//span[text()='che: build-file-output'])
Wait timed out after 300009ms
```
![screenshot-Build_application (1)](https://user-images.githubusercontent.com/1197777/66658532-5936a800-ec4a-11e9-8ab2-8d6c35ecbf98.png)

### Screencast
https://youtu.be/2Vy1SMSeg5I

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
[Happy path tests scenario](https://github.com/eclipse/che/blob/master/e2e/tests/e2e_happy_path/HappyPath.spec.ts).

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by Ohrimenko1988** [comment]
Commands display without namespaces.
And in the locator which uses in the test command names expected with namespaces.
doesn't work:
```//div[@class='quick-open-entry']//span[text()='che: build-file-output']```
works:
```//div[@class='quick-open-entry']//span[text()='build-file-output']```

**Comment by dmytro-ndp** [comment]
@benoitf, @azatsarynnyy: could you, please, take a look at screenshot in description of issue: there was `che:` command prefix disappeared in task popup on Friday Oct 11.
Do you happened to know if it was expected changes ?

**Comment by RomanNikitenko** [comment]
I think it's expected behavior after merge https://github.com/eclipse-theia/theia/pull/6247

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
Should we close the issue considering the comment above?

**Comment by azatsarynnyy** [comment]
labeled as `area/plugins` as related to https://github.com/eclipse/che-theia/tree/master/plugins/task-plugin

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: IMO it's unexpected result of changes https://github.com/eclipse-theia/theia/pull/6247

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
fyi: https://github.com/eclipse-theia/theia/pull/6247#discussion_r333326008
