### ISSUE TITLE
Verify CRW 1.2 to 2.0 upgrade using operator works for all updated containers

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14865]
Followup from https://github.com/eclipse/che/issues/14200

### Is your task related to a problem? Please describe.

Goal here is to verify that an old CRW 1.2 (based on Che 6.x) install using old containers can be updated to new 2.9 (based on 7.2 or 7.3) using newer containers, via an operator-based update as discussed in https://github.com/eclipse/che/issues/14200#issuecomment-540124798 (and below).

* PVC: registry.access.redhat.com/ubi8-minimal:8.0-159 -> registry.access.redhat.com/ubi8-minimal:8.0-213
* Postgres: registry.redhat.io/rhscl/postgresql-96-rhel7:1-46 to registry.redhat.io/rhscl/postgresql-96-rhel7:1-47
* Che Server registry.redhat.io/codeready-workspaces/server-rhel8:1.2 to quay.io/crw/server-rhel8:2.0
* keycloak/sso registry.redhat.io/redhat-sso-7/sso73-openshift:1.0-13 to registry.redhat.io/redhat-sso-7/sso73-openshift:1.0-13.1567588155

### Describe the solution you'd like

Automated test that will:

* install old CRW 1.2 via operator, with custom image versions noted above
* cause update to occur to update to newer 2.0 operator, with override images set (CRW 2.0 images don't yet exist in default locations, so need to use Quay locations instead for testing).

**Comment by ibuziuk** [comment]
@nickboldt who is expected to work on this issue ?

**Comment by nickboldt** [comment]
Given QE has signed off on https://issues.jboss.org/browse/CRW-304 and https://issues.jboss.org/browse/CRW-305 as being done, I guess this is done too.
