### ISSUE TITLE
Support local devfile references in chectl workspace:start

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14874]
### Is your enhancement related to a problem?

The following devfile references a local file (`petclinic.yaml`): 

```yaml
  components:
    - alias: mysql
      type: kubernetes
      reference: petclinic.yaml
```

Starting a workspace using this devfile locally with `chectl workspace:start` currently fails:

```log
chectl workspace:start -f devfile.yaml
  ✔ Retrieving Che Server URL...http://che-che.192.168.64.166.nip.io
  ✔ Verify if Che server is running...RUNNING (auth disabled)
  ✖ Create workspace from Devfile devfile.yaml
    → E_BAD_DEVFILE_FORMAT - Message: Failed to validate content reference
…
Error: E_BAD_DEVFILE_FORMAT - Message: Failed to validate content reference of component 'tools' of type 'kubernetes': It is unable to fetch a file petclinic.yaml as relative to devfile, since devfile location is unknown. Try specifying absolute URL.
    at CheHelper.<anonymous> (~/.local/share/chectl/client/7.2.0/lib/api/che.js:237:27)
    at Generator.throw (<anonymous>)
    at rejected (~/.local/share/chectl/client/7.2.0/node_modules/tslib/tslib.js:108:69)
```

### Describe the solution you'd like

The previous example should work. 

I can see 2 ways to implement that:

1. `chectl workspace:start` parses the devfile and replace `reference` attributes that point to local files with `referenceContent` attributes with the inline yaml content.
2. we introduce a "che workspace context" similar to the docker build context: the content of the devfile folder is sent to the che server that has then access to local files as well.

**Comment by l0rd** [comment]
cc @kameshsampath

**Comment by ibuziuk** [comment]
@l0rd what would be the priority for that one?

**Comment by ibuziuk** [comment]
putting P2 for now

**Comment by l0rd** [comment]
@ibuziuk I have set P1 because that makes some devfiles unusable with chectl and the fix seams relatively easy.
