### ISSUE TITLE
chectl workspace:start without options should look for a local devfile.yaml

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14873]
### Is your enhancement related to a problem? Please describe.

If I have a devfile.yaml in the current directory the following commands do not work:

```bash
$ chectl workspace:start
 ›   Error: workspace:start command is expecting a devfile or workspace configuration
 ›   parameter.
$ chectl workspace:start .
 ›   Error: Unexpected argument: .
 ›   See more help with --help
```

### Describe the solution you'd like

`chectl workspace:start`: look for a devfile in the current directory, fail if it cannot find one.
`chectl workspace:start <directory>` look for a devfile in `<directory>`, fail if it cannot find one.
`chectl workspace:start -f my-devfile.yaml <directory>` look for a `my-devfile.yaml` in `<directory>`, fail if it cannot find it.

**Comment by ibuziuk** [comment]
@l0rd what is the priority for that one ?

**Comment by ibuziuk** [comment]
putting P2 for now

**Comment by l0rd** [comment]
@ibuziuk yes P2 seams reasonable
