### ISSUE TITLE
Improve kubeconfig injection with chectl

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14877]
### Is your enhancement related to a problem? Please describe.

A working Kubernetes config is something that users will expect in a Che workspace but the UX is still not perfect:

- A user cannot specify the particular kubernetes context (cluster, namespace and user) should be injectected.
- Starting a workspace with the local kubeconfig requires to run 2 commands (workspace start+inject) when it could be one command only. 
- If a workspace is stopped and restarted the injected local kubeconfig will get lost.

### Describe the solution you'd like

- [x] Add the parameter `--context` to the `workspace:inject` command. It will be used to specify the context to be injected. If no `--context` parameter is provided only the current context will be injected.
- [ ] Add two new parameter `--inject-context <>` and `--inject-current-context` to the `workspace:start` command. Since the `workspace:start` command currently doesn't start a workspace (it only creates it), to inject the we should probably add init containers that will generate the kube config, create a secret with the user token and a config map with the other context details.
- [ ] Modify `workspace:inject` to use the init container approach mentioned above.

**Comment by l0rd** [comment]
cc @kameshsampath

**Comment by ibuziuk** [comment]
@l0rd not sure about priority, but I put P1 for now, since having a neat kubeconfig support looks pretty important for kubenative IDE

**Comment by l0rd** [comment]
I confirm this should be a P1

**Comment by azatsarynnyy** [comment]
PR for `--context` parameter https://github.com/che-incubator/chectl/pull/430

**Comment by l0rd** [comment]
Closing this issue as today we have [a mechanism to pre-create secrets](https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/) that will be automatically mounted in workspaces containers.
