### ISSUE TITLE
Allow using the Devfile registry in offline mode in the Che Operator

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#14880]
### Description

Update the Che operator in order to add the `CHE_DEVFILE_HTTPS_ENDPOINT` environment variable to the devfile registry deployment when airGap mode is enabled.

This is the operator side of the work done in this PR: https://github.com/eclipse/che-devfile-registry/pull/112#discussion_r333884149

**Comment by tomgeorge** [comment]
I think the devfile registry works in offline mode now since https://github.com/eclipse/che-devfile-registry/pull/131

**Comment by ibuziuk** [comment]
Closing as done
