### ISSUE TITLE
Sending Ctrl+C to one terminal widget kills all terminals 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14887]
### Describe the bug

I have faced issue from time to time when I'm developing che in che.

So I have one running instance of che and I run another instance from `theia/examples/assembly`.
After stopping a task by pressing `Ctrl+C` for one terminal widget all open terminals are killed. 

### Che version

Latest
 
### Steps to reproduce

1. Start workspace for che-in-che development
2. Open few terminals for first instance of che
3. Open few terminals for second instance of che
4. Start any task (build of che-theia for example)
5. Terminate the task by pressing `Ctrl+C`

You can see that all terminals (for first and second instance of che) are killed.

I didn't catch the cause of the problem and can not reproduce it permanently, but I have faced the issue from time to time when I'm developing che in che.
  
Please see the video: https://youtu.be/zvuwqC9bdAU

### Expected behavior

Task is stopped after pressing `Ctrl+C`, other terminals are working.

### Runtime
minikube (minikube version: v1.0.0)

### Screenshots

https://youtu.be/zvuwqC9bdAU

### Installation method

chectl chectl/0.0.2-5ab0061 linux-x64 node-v10.4.1

### Environment

Linux

**Comment by RomanNikitenko** [comment]
I played a lot with it and found how we can reproduce it: the issue is reproduced permanently if you send `Ctrl+C` twice for the same terminal widget of a task.

**Comment by amisevsk** [comment]
I've been able to reproduce this in the past, and it looks like the `che-machine-exec` container is being killed by the `ctrl-c`.

**Comment by AndrienkoAleksandr** [comment]
I reopen, because we found that we have two dockerfiles for che-machine-exec in the repo for two different CI. And one of them we should removed. I need to move fix to the correctly dockerfile...

**Comment by AndrienkoAleksandr** [comment]
Prepared pr's: https://github.com/eclipse/che/pull/15144 https://github.com/eclipse/che-plugin-registry/pull/290 https://github.com/eclipse/che-machine-exec/pull/56

**Comment by AndrienkoAleksandr** [comment]
Done.
