### ISSUE TITLE
Helm with multi-user - Don't create Ingress for Postgres service

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14886]
### Describe the bug
When deploying Che with Helm charts, with **multi-user**, Ingress is created for Postgres service with `postgres-che.192.168.99.110.nip.io` as host URL. This is default value from `values.yaml` (https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml#L34) and it is not valid IP address. Anyway, for postgress, it does not make much sense to have external route at all.

deploy command:
```
helm upgrade --install che --force --namespace che \
--set global.ingressDomain=$(minikube ip) --set cheImage=eclipse/che-server:nightly \
--set global.multiuser=true \
--set cheDevfileRegistry.deploy=false --set chePluginRegistry.deploy=false \
deploy/kubernetes/helm/che/
```

### Che version
 - [x] nightly

### Steps to reproduce
1. run minikube and create `che` namespace
1. go to dir with che sources on your local filesystem
1. run deploy command from the description
1. run `kubectl get ingresses -n che` and see that postgress has `postgres-che.192.168.99.110.nip.io` host

### Expected behavior
Do not create Ingress for postgres.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] helm

### Environment
   - [x] my computer
       - [x] Linux

### Additional context
discovered during https://github.com/eclipse/che/issues/13647 but not related only to default-host

**Comment by tolusha** [comment]
I don't this it is the issue anymore.
`chectl server:start --platform minikube --installer helm  -m` doesn't create any ingress for Postgres
