### ISSUE TITLE
[docs] "Running Che locally" documentation does not cover CRC (CodeReady Containers) installation

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14891]
### Is your task related to a problem? Please describe.
"Running Che locally" documentation https://www.eclipse.org/che/docs/che-7/running-che-locally/ does not cover CodeReady Containers (OpenShift 4.x) setup and only focus on minishift (OpenShift 3.x )

From the minishift docs:

> Minishift runs OpenShift 3.x clusters. Due to different installation methods, OpenShift 4.x clusters are not supported. To run OpenShift 4.x locally, use CodeReady Containers.

Need to contribute CodeReady Containers installation method for "Setting up a local Kubernetes or OpenShift cluster" in order to cover local OpenShift 4.x  setup- 
 https://www.eclipse.org/che/docs/che-7/running-che-locally/#setting-up-a-local-kubernetes-or-openshift-cluster

**Comment by ibuziuk** [comment]
cc: @rkratky

**Comment by themr0c** [comment]
I believe this issue is fixed, see: 
https://www.eclipse.org/che/docs/che-7/running-che-locally/#using-codeready-containers-to-set-up-openshift-4_running-che-locally
https://www.eclipse.org/che/docs/che-7/running-che-locally/#installing-che-on-codeready-containers-using-chectl_running-che-locally
