### ISSUE TITLE
Fix licensing issues in CRW examples

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14890]
There are a couple of licensing issues we need to fix for CRW 2.0: https://issues.jboss.org/browse/CRW-317?focusedCommentId=13797873&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13797873

Here's what we need to do:

1. Add a license file to all referenced examples on github.com/che-examples
2. Add "copyright by Red Hat and others to nodejs/mongodb CRW example
3. Fix copyright headers to say "Copyright by Red Hat and others" in kitchensink example

**Comment by l0rd** [comment]
Labeling it as P1 but @tsmaeder if that's a CRW specific issue it should live [in JBoss Jira](https://issues.jboss.org/projects/CRW/)

**Comment by tsmaeder** [comment]
The broader issue (also including the che-nodejs/mongodb sampel is https://github.com/eclipse/che/issues/14799
