### ISSUE TITLE
Include Vert.x test in nightly tests

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#14894]
### Is your task related to a problem? Please describe.
There is a test file for Java Vert.x default stack that is not run as a part of any job. All tests in e2e folder should be run to verify that they'll be working once released. Regarding that, add Vert.x test to a job that runs nightly.
Test file: https://github.com/eclipse/che/blob/master/e2e/tests/e2e/JavaVertx.spec.ts

There is another test file that is not used anymore. It can be deleted as a part of this issue.
Test file to be deleted: https://github.com/eclipse/che/blob/master/e2e/tests/e2e/WorkspaceCreationAndLsInitialization.spec.ts

### Describe the solution you'd like
Add Java Vert.x test to a suite that is running nightly. 

### Describe alternatives you've considered
If there is no suitable job for that, create a new one.

### Additional context
All tests that are included in e2e tests should be working correctly when released so they can be reused e.g. on Hosted Che side.

**Comment by dmytro-ndp** [comment]
Jenkins job to run Vert.x tests nightly on multiuser installation is available [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/MultiUser-Che-nightly-check-e2e-tests-against-k8s/).
