### ISSUE TITLE
Prepare the epic(s) for the future workspace CRD controller work

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14906]
### Description

- Formalize the content / current status / conclusions of discussions that already happened (especially in the last F2F) and shaped the future directions of the Workspace CRD controller work.
- Prepare one or several EPICs that will summarize this 
- Decompose those EPICs into tasks / issues that can be assigned to appropriate teams.

**Comment by sleshchenko** [comment]
I guess it's kind of done and epic is created https://github.com/eclipse/che/issues/15425
