### ISSUE TITLE
Error in starting Eclipse Che using chectl and helm in Windows

### ISSUE THREAD

**Issue by sandeepsai39** [eclipse-che/che#14907]
## Summary

I am trying to install eclipse che on Google cloud as per the instructions provided in
[link](https://www.eclipse.org/che/docs/che-7/installing-che-on-google-cloud-platform/.)
I am facing issue when starting che using chectl with below command.

`chectl server:start --platform=k8s --tls --domain=gcp.my-ide.cloud --multiuser` with below error.
 >  √ Verify Kubernetes API...OK
  √ 👀  Looking for an already existing Che instance
    √ Verify if Che is deployed into namespace "che"...it is not
  √ ✈️  Kubernetes preflight checklist
    √ Verify if kubectl is installed
    √ Verify remote kubernetes status...done.
    √ Verify domain is set...set to gcp.my-ide.cloud.
  🏃‍  Running Helm to install Che
    √ Verify if helm is installed
    √ Check for TLS secret prerequisites...self-signed-cert secret found.
    √ Create Tiller Role Binding...it already exists.
    √ Create Tiller Service Account...it already exists.
    √ Create Tiller RBAC
    × Create Tiller Service
      → error: E_COMMAND_FAILED
      Preparing Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Che Helm Chart
Error: Command "helm init --service-account tiller --wait" failed with return code 1
stderr: Error: unknown flag: --service-account
stdout:
error: E_COMMAND_FAILED
    at HelmTasks.<anonymous> (C:/ProgramData/chectl/chectl/lib/tasks/installers/helm.js:213:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:107:62)

The error a bit different if  i run same command in power shell.
> √ Verify Kubernetes API...OK
  √ 👀  Looking for an already existing Che instance
    √ Verify if Che is deployed into namespace "che"...it is not
  √ ✈️  Kubernetes preflight checklist
    √ Verify if kubectl is installed
    √ Verify remote kubernetes status...done.
    √ Verify domain is set...set to gcp.che-ide.cloud.
   🏃‍  Running Helm to install Che
    √ Verify if helm is installed
    √ Check for TLS secret prerequisites...self-signed-cert secret found.
    √ Create Tiller Role Binding...it already exists.
    √ Create Tiller Service Account...it already exists.
    × Create Tiller RBAC
      → ENOENT: no such file or directory, open 'templates\kubernetes\helm\che\tiller-rbac.yaml'
      Create Tiller Service
      Preparing Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Che Helm Chart
Error: ENOENT: no such file or directory, open 'templates/kubernetes/helm/che/tiller-rbac.yaml'
    at HelmTasks.<anonymous> (C:/ProgramData/chectl/chectl/lib/tasks/installers/helm.js:187:36)
    at Generator.next (<anonymous>)
    at C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:106:16)
    at HelmTasks.createTillerRBAC (C:/ProgramData/chectl/chectl/lib/tasks/installers/helm.js:185:24)
    at HelmTasks.<anonymous> (C:/ProgramData/chectl/chectl/lib/tasks/installers/helm.js:96:96)
    at Generator.next (<anonymous>)

## Relevant information

Below are version of , helm and checctl.
kubectl version:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
chectl version
chectl/0.0.20191011-next.7cfccb7 win32-x64 node-v10.16.3

helm version
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

**Comment by tolusha** [comment]
Additional context
https://github.com/helm/helm/issues/7052

**Comment by tolusha** [comment]
```
→ ENOENT: no such file or directory, open 'templates\kubernetes\helm\che\tiller-rbac.yaml'
```
This kind of error has been fixed in recent version of `chectl`
