### ISSUE TITLE
SSH Key upload in Che 7

### ISSUE THREAD

**Issue by rguskov** [eclipse-che/che#14911]
How do I upload SSH Key into workspace or for a user running several workspaces in Che 7. Che 6 had this option in the 
Preferences->SSH->VCS. Can't see how to properly organise it with Che 7.

**Comment by slemeur** [comment]
cc @vparfonov

**Comment by slemeur** [comment]
Hi @rguskov What is the version of Che you are using?

**Comment by rguskov** [comment]
Che 7.1.0

**Comment by vzhukovskii** [comment]
@rguskov there is an additional command in command palette, where you can upload a private key. See demo in following PR: https://github.com/eclipse/che-theia/pull/547
