### ISSUE TITLE
Document how to use private git repos with ssh key workaround

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14917]
1. Updating the [Git HTTPS section](https://www.eclipse.org/che/docs/che-7/version-control/#accessing-a-git-repository-via-https_version-control)  with a big warning that says that self signed certs are not supported and, in that case, use Git SSH instead
2. Updating the [Git SSH section](https://www.eclipse.org/che/docs/che-7/version-control/#accessing-a-git-repository-via-ssh_version-control) because user don't need to generate the key anymore
3a. Improve the error message a user sees when he hasn't uploaded the pub key 
3b. (If 3a is not possible by the end of next week) document the error: what is displayed, what it means, how to fix it in the Git SSH section

**Comment by vinokurig** [comment]
fixed by https://github.com/eclipse/che-docs/pull/861
