### ISSUE TITLE
[plugin-registry] Consider dropping support for Node < 8

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14927]
The node-debug extension from MS says:

```
description: Node debug (legacy) is the debugger for Node.js versions < 8.0. Together
  with Node Debug forms the Node.js debugging experience. https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug
```

And the node-debug2 extension:

```
description: Node Debug is the debugger for Node.js versions >= 8.0. Together with
  Node Debug (legacy) forms the Node.js debugging experience. https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2
```

So since Node 10 is the LTS version and Node 12 is the Current version, maybe we don't need to keep supporting Node 6 and under?

Could we (should we) drop the node-debug vsix from the Che Plugin Registry for 7.4?

**Comment by nickboldt** [comment]
PR to make this happen https://github.com/eclipse/che-plugin-registry/pull/264

**Comment by nickboldt** [comment]
*cough* @slemeur any thoughts on this, a sprint later? */cough*

**Comment by slemeur** [comment]
LTS for NodeJS: https://nodejs.org/en/about/releases/

I'm +1 to remove it.

**Comment by nickboldt** [comment]
(Edit: added EOL date for Node 8 to Stevan't comment above.)
