### ISSUE TITLE
Che Theia IDE is reloaded spontaneously

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14933]
### Describe the bug
Sometimes Che Theia IDE page is reloaded on its own without asking the user.

### Che version
multiuser, nightly

### Steps to reproduce

1. Open dashboard, start a workspace with Che Theia IDE
2. Work in the Che Theia IDE and it happens from time to time. Or just leave the IDE for a half an hour and then switch focus the tab.

### Expected behavior
The editor page is not reloaded unless user does it explicitly

### Runtime
minishift v1.34.1+c2ff9cb

### Additional context
Looks like it happens on timer and initiated from dashboard. Might be related to Keycloak token refresh, but not sure.

**Comment by tsmaeder** [comment]
Yes, I've seen this, too.

**Comment by azatsarynnyy** [comment]
+1
