### ISSUE TITLE
Sometimes It is necessary to have same HOME for plugin and dev containers

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#14938]
In some cases it is necessary to have the same value of HOME env for both containers: dev container and plugin container. 

For example it is necessary for dotnet workspace, which uses omnisharp remote plugin. In this case both containers want to build the project (or sample) and the build process rewrites project's configuration which describes where dependency packages are located. And usually for dotnet the folder with that packages locates in `$HOME/.nuget` directory. It means that the value of dependency is different for these containers.

Probably it makes sense to have the same value of $HOME variable (maybe also for some another ENVs)  for all containers.

**Comment by tsmaeder** [comment]
Another instance of the "plugins assume they are on the same machine" problem. @svor can we get the two tools to use the $HOME variable instead of a fixed path?

**Comment by svor** [comment]
@tsmaeder at the moment I don't know how to do that in case with dotnet, maybe it is possible to provide some parameter for build command...

**Comment by tsmaeder** [comment]
lifecycle/frozen
