### ISSUE TITLE
Che does not run on RHT 1.9.1 docker daemon

### ISSUE THREAD

**Issue by jeffmaury** [eclipse-che/che#1493]
RedHat CDK is based on Docker 1.9.1. If we want to run Che inside CDK's docker (for Che/Openshift demos), then it is not possible because container creation are being rejected because of wrong SHM size. Seems related to https://github.com/kubernetes/kubernetes/issues/24588

**Comment by TylerJewell** [comment]
@agaragatyi: FYI.

**Comment by TylerJewell** [comment]
@garagatyi - we had run Che on docker 1.8 and 1.7 for an extended period of time without this issue.  The kubernetes issue seemed to suggest that usage of the cli made it ok but direct to docker engine failed.   Any thoughts?

**Comment by jeffmaury** [comment]
Using a 1.8.0 cli allowed me to reproduce the issue. But Eclipse Docker Tooling does not have this problem

**Comment by garagatyi** [comment]
We don't handle that field right now, so it is up to docker API how it treats default value of the field. Docker had similar bugs several times and swarm had similar bugs too (separately from docker). So what is the expected behavior of Che in such cases?

**Comment by jeffmaury** [comment]
As Eclipse Docker Tooling does not have the problem, you may check your Docker API provider

**Comment by l0rd** [comment]
@garagatyi @TylerJewell I can have a look at that issue. I know the Docker API and I can look how Eclipse Docker Tooling is using it compared to Che.

**Comment by jeffmaury** [comment]
For the record, Eclipse Tooling is using the Spotify Java Docker API

**Comment by l0rd** [comment]
Yes that's the same API I've used in [doclipser](https://github.com/domeide/doclipser)

**Comment by l0rd** [comment]
@jeffmaury I can't reproduce it on fresh install of Docker 1.9.1 on Ubuntu. In my case Che is able to create containers with no errors. Can you please provide more details to help me reproduce the scenario that failed?

**Comment by ghost** [comment]
@jeffmaury I have run Openshift assembly on RHEL and Docker 1.9.1 today. @joshuawilson is my witness.

What's the issue? Can you share more details?

**Comment by jeffmaury** [comment]
Things are weird are they seem to be related to the CDK used.

Here is what I did:

1) Official CDK (2.0);
 eval "$(VAGRANT_NO_COLOR=1 vagrant service-manager env docker | tr -d '\r')"
docker version

```
Client:
 Version:      1.10.3
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   78ee77d/1.9.1
 Built:
 OS/Arch:      linux/amd64
```

docker run -d codenvy/ubuntu-jdk8

```
docker: Error response from daemon: SHM size must be greater then 0.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

2) Latest CDK 2.1RC2

 eval "$(VAGRANT_NO_COLOR=1 vagrant service-manager env docker | tr -d '\r')"
docker version

```
Client:
 Version:      1.10.3
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   ab77bde/1.9.1
 Built:
 OS/Arch:      linux/amd64
```

docker run -d codenvy/ubuntu_jdk8

```
027207957a7713607b14a64c561181238ae9abfb06a2cb0d3162865b7e87eb53
```

So it looks that both claim to be 1.9.1 for Docker but the commit is different. So the error comes with the CDK 2.0

**Comment by ghost** [comment]
@jeffmaury does it happen to codenvy images only?

**Comment by jeffmaury** [comment]
1) On CDK 2.0

docker run docker/whalesay cowsay boo

```
docker: Error response from daemon: SHM size must be greater then 0.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

2) Latest CDK 2.1RC2

 docker run docker/whalesay cowsay boo

```
 _____
< boo >
 -----
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

**Comment by TylerJewell** [comment]
@garagatyi - i believe this was resolved.  can you confirm, please?

**Comment by garagatyi** [comment]
No, it wasn't

**Comment by TylerJewell** [comment]
Labeling a blocker for now so that we can take a peak during our next sprint planning session.

**Comment by mmorhun** [comment]
Seems that it was problem inside docker and it was fixed in later versions.
@jeffmaury do you still have this problem on latest version of CDK?

**Comment by TylerJewell** [comment]
Changed the label to kind/question and removed bug / blocker issue.  If the solution is to upgrade the CDK to new docker daemon version to fix issues in Docker, then that is suitable work around.  Waiting for @jeffmaury to finalize.

**Comment by TylerJewell** [comment]
@jeffmaury - just checking back in here.  Is this a documentation issue?  If you can confirm it, we'll get docs updated and then can close this from backlog.

**Comment by TylerJewell** [comment]
Closing this issue as we are now declaring Che going to require a 1.11+ daemons going forward.
