### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#14932]
### Describe the bug

I'm trying to install a plugin via a custom plugin registry.
When I try to do so, after pressing the install button of the plugin, when the workspace restarts it stucks at:
````
Starting Init Plugin Broker
Unified Che Plugin Broker
````
When I try to realode the page I get the following error:
````
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspacel4bfie9fhjfpwpwj failed with error: Downloading http://che-plugin-registry-che.192.168.99.100.nip.io/resources/github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix failed. Status code 404"
````

The plugin I try to install is cpptools, which is also contained in the default plugin registry. 
I'm doing that to test if my custom registry works properly, which seems not to be the case.

Since I'm having this problem for some days now, I would appreciate any kind of help.
I have opened already an issue about this problem some days ago, but I didn't get an answer there, so I will close that one.
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.4.0 (with chectl)

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
````
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
````
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@anthonma could you please clarify how have you deployed the custom plugin registry? Have you followed the official docs - https://www.eclipse.org/che/docs/che-7/customizing-the-devfile-and-plug-in-registries/ ?

**Comment by anthonma** [comment]
I did follow the offical docs (https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/). I have deployed the custom registry via the helm command given there:
````
NAMESPACE=<namespace-name> 
DOMAIN=<kubernetes-cluster-domain>
IMAGE="my-plugin-registry"
helm upgrade --install che-plugin-registry \
 --debug \
 --namespace $\{NAMESPACE} \
 --set global.ingressDomain=$\{DOMAIN} \
 --set chePluginRegistryImage=$\{IMAGE} \
 --set chePluginRegistryImagePullPolicy="IfNotPresent" \
 ./kubernetes/che-plugin-registry/
````
I had to change it a little. $\{...} didn't work (command not found), so I changed it to ${...} without the \

**Comment by anthonma** [comment]
I have seen that the content of the plugin registry has changed, so I wanted to test if my problem is solved by using the new version, but unfortunately I can't even build the new version, because the file meta.yaml.schema is not found.

**Comment by anthonma** [comment]
I can build the new version now, but don't deploy it. When I try to do so I get this error:
````
Error: YAML parse error on che-plugin-registry-service/templates/configmap.yaml: error converting YAML to JSON: yaml: line 16: did not find expected node cntent
````

I'm using this command to deploy:
````
NAMESPACE="kube-che"
DOMAIN="$(minikube ip).nip.io"
helm upgrade --install che-plugin-registry \
    --debug \
    --namespace ${NAMESPACE} \
    --set global.ingressDomain=${DOMAIN} \
    ./kubernetes/che-plugin-registry/
````

**Comment by anthonma** [comment]
I have put the things I wrote above in a new issue for better readability and understanding (#14994)
So I will close this one.
