### ISSUE TITLE
Error during loading go stack

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14931]
### Describe the bug
Not able to load Che Theia from go stack.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy che on crc version: 1.0.0+2aa3143 OpenShift version: 4.2.0 (embedded in binary)
2. create a workspace from go stack.
3. Sometimes the workspace is not loaded. If you press F5 everything work

### Expected behavior
Loaded workspace from go stack

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [X] other:   crc version: 1.0.0+2aa3143 OpenShift version: 4.2.0 (embedded in binary)
    
### Screenshots
<img width="1118" alt="Знімок екрана  о 19 17 14" src="https://user-images.githubusercontent.com/1614429/67163374-618b9300-f36e-11e9-98d2-844f71b48854.png">
<img width="1106" alt="Знімок екрана  о 19 17 22" src="https://user-images.githubusercontent.com/1614429/67163375-63555680-f36e-11e9-8994-cef614477e89.png">

### Installation method
   - [x] chectl/0.0.20191011-next.7cfccb7 darwin-x64 node-v10.16.3
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
none

**Comment by skabashnyuk** [comment]
I don't think that it's somehow related to LanguageServers. I tent to think that it's related to loader page. @akurinnoy wdyt?

**Comment by akurinnoy** [comment]
@skabashnyuk you're right, I'm adding IDE2 team label.

**Comment by mmorhun** [comment]
I've tried to reproduce this issue, but it is very hard to do (at least for me).
So, after code analyzation I prepared these PRs: https://github.com/eclipse/che/pull/15154 and https://github.com/eclipse/che/pull/15147 which, I think, may resolve the problem.
Now I am going to close this issue, but if someone be able to reproduce it again - fell free to reopen it.
