### ISSUE TITLE
Some properties are only present in che.properties

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14946]
### Is your task related to a problem? Please describe.
While working on https://github.com/eclipse/che/issues/14633 I came across a number of properties that are only mentioned in `che.properties` and used nowhere in the code (that I can see):

- `che.websocket.endpoint_minor`
- `che.workspace.maven_server_java_options`
- `che.workspace.terminal_linux_amd64`
- `che.workspace.terminal_linux_arm7`
- `che.workspace.exec_linux_amd64`
- `che.installer.registry.remote`
- `che.template.storage`
- `che.docker.enable_container_stop_detector`
- `notification.server.propagate_events`
- `org.everrest.asynchronous.pool.size`
- `org.everrest.asynchronous.queue.size`
- `org.everrest.asynchronous.job.timeout`
- `org.everrest.asynchronous.cache.size`
- `org.everrest.asynchronous.service.path`
- `che.singleport.wildcard_domain.port`
- `che.singleport.wildcard_domain.ipless`

If these properties are actually unused in Che 7, they should be removed.

**Comment by benoitf** [comment]
everest properties are consumed there no ? https://github.com/codenvy/everrest

**Comment by amisevsk** [comment]
@benoitf Yes, the everrest properties are used -- this is just the output of a script to review. I think some properties are left over from the Che 6 workspaces deprecation.

**Comment by l0rd** [comment]
@amisevsk that is just a small list of unused property right? For instance we still have a lot of `che.docker.*` properties that should be removed.

**Comment by amisevsk** [comment]
@l0rd The list is just a list of the properties whose only mention in the Che server codebase is in `che.properties`. While the `che.docker.*` properties should also probably be removed, they're not listed since they're still injected in a file somewhere.
