### ISSUE TITLE
Add an information about cpp into Language support troubleshooting document

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#14943]
Since we've registered a [new plugin](https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/che-incubator/cpptools) to support cpp tools, we need to provide related information  into [Language support troubleshooting document](https://github.com/eclipse/che/wiki/Language-support-troubleshooting-document).

**Comment by tolusha** [comment]
It is here  [1]. We just need to move it to the wiki page

[1] https://docs.google.com/document/d/182PBN5LBNTlbhsqqsb5QHg9t5HNK3rSLrnIMPSGjyN0/edit#heading=h.dm46uakse4mn

**Comment by tsmaeder** [comment]
Just need to move the infor to the wiki, then.

**Comment by tsmaeder** [comment]
Done.
