### ISSUE TITLE
Allow use of 'Organizational CA'

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#14949]
### Is your enhancement related to a problem? Please describe.
Some institutions use a self-provided Certificate Authority ('Organizational CA').  They will have use cases like "wildcard cert signed by our internal CA on the ingress controller".
Please ensure Che works effectively in such an environment.

### Describe the solution you'd like
Wish List #1:  Everything just works after proper installation
Wish list #2 (if #1 is not possible):  Clear log entries that provide guidance when Certs are rejected, clear documentation on procedures to fix things when it happens

### Additional context
Please test this scenario (Organizational CA, OpenShift 4)

**Comment by l0rd** [comment]
We have already done some work https://github.com/eclipse/che/issues/13869#issuecomment-518946736 but I don't think we have documented it yet (cc @skabashnyuk @sleshchenko).  

This is related to https://github.com/eclipse/che/issues/14742 and @vparfonov team's is also working git + tls https://github.com/eclipse/che/issues/14527

**Comment by sleshchenko** [comment]
I think we can close now this issue as implemented. https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/
