### ISSUE TITLE
Build of Eclipse Che is unstable on Codenvy CI

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14955]
### Describe the bug
Eclipse Che build failed on unit test `org.eclipse.che.api.workspace.server.hc.ServersCheckerTest` because timeout succeeded:
https://ci.codenvycorp.com/job/che-pullrequests-build/8142/

> Error Message
> Method org.testng.internal.TestNGMethod.awaitShouldReturnOnFirstUnavailability() didn't finish within the time-out 1000
>
>Stacktrace
>org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.awaitShouldReturnOnFirstUnavailability() didn't finish within the time-out 1000
>	at org.eclipse.che.api.workspace.server.hc.ServersCheckerTest.awaitShouldReturnOnFirstUnavailability(ServersCheckerTest.java:169)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

**Comment by l0rd** [comment]
@dmytro-ndp how frequent is the error? I am setting P1 assuming that it's something new that is happening quite frequently.

**Comment by skabashnyuk** [comment]
Fixed in https://github.com/eclipse/che/pull/14975
