### ISSUE TITLE
[refactoring] Improve consistency in defaults.go variables

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14957]
In `defaults.go` at [L23-L26](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults.go#L23-L26) we use "CodeReady" as if it's a product to differentiate from "Che".

But at [L36-L52](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults.go#L36-L52) we use the "Upstream" convention to differentiate Che from CRW config.

This is bad code smell but not technically a problem, so should be dealt with when we're bored in the future and ready for some refactoring.

**Comment by tolusha** [comment]
https://github.com/eclipse/che-operator/pull/172
It n't relevant any more
