### ISSUE TITLE
[Doc] Che 7 Doc - Updated Che4Z install page to include full install instructions

### ISSUE THREAD

**Issue by DStatWriter** [eclipse-che/che#14967]
Updated Che 7 doc - Che4z install page to include full install instructions

**Comment by rkratky** [comment]
@DStatWriter, could you please file more descriptive issues, so that they can be reviewed by other members of the team, too? A good start would be to use the templates prepared at https://github.com/eclipse/che/issues/new/choose

**Comment by themr0c** [comment]
Hi @DStatWriter , current installation pages is stating following:

> For instructions on how to install the Eclipse Che4z stack, see the Che4z Git repository

Is that what you want to change, or is that the expected behaviour?
