### ISSUE TITLE
[che-theia] build failed because of disappearance of quay.io/buildah/stable:v1.11.3 image

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14965]
### Describe the bug
Build of "eclipse/che-remote-plugin-kubernetes-tooling-1.0.4:next" image failed
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-master-check-E2E-Happy-path-tests-against-K8S/388/consoleFull
```
Building image in dockerfiles/remote-plugin-kubernetes-tooling-1.0.4
Building Docker Image eclipse/che-remote-plugin-kubernetes-tooling-1.0.4:next (target alpine) from /mnt/hudson_workspace/workspace/Che-Theia-master-check-E2E-Happy-path-tests-against-K8S/dockerfiles/remote-plugin-kubernetes-tooling-1.0.4 directory with tag next
Sending build context to Docker daemon  6.144kB

Step 1/13 : FROM eclipse/che-theia-endpoint-runtime:next as endpoint
 ---> a4ed4ac324b4
Step 2/13 : FROM quay.io/buildah/stable:v1.11.3
unknown: Tag v1.11.3 was deleted or has expired. To pull, revive via time machine
```

There is no image `quay.io/buildah/stable:v1.11.3` in https://quay.io/repository/buildah/stable?tab=tags
![Screenshot from 2019-10-23 17-13-31](https://user-images.githubusercontent.com/1197777/67401967-8a06cd80-f5b8-11e9-99c8-5e3de5134539.png)

### Steps to reproduce
```
/build.sh --skip-tests --dockerfile:Dockerfile.alpine
```

**Comment by azatsarynnyy** [comment]
The PR has been proposed https://github.com/eclipse/che-theia/pull/509

**Comment by azatsarynnyy** [comment]
`buildah/stable:v1.11.3` is on quay.io now. :tada: 
See https://github.com/containers/buildah/issues/1943#issuecomment-545504729
