### ISSUE TITLE
How to open the default workspace after user logs in

### ISSUE THREAD

**Issue by sudheerherle** [eclipse-che/che#14962]
## Relevant information
I would like to know if there is a way to open the workspace by default when user logs in instead of having user to select the woerkspace and clicking on "Open".

**Comment by benoitf** [comment]
Hello, If you use factory/devfile link, then a workspace is always created every time the user is clicking on the link

if you bookmark the link of a workspace, every time you go to the workspace it will load and if you disconnect you'll login and be redirected to this workspace

**Comment by sleshchenko** [comment]
Just to share there is policies.create = perClick, perUser not to create a workspace each time:
Like https://che.openshift.io/f?url=https://github.com/eclipse/che&policies.create=peruser
