### ISSUE TITLE
Updating installation when installed using helm

### ISSUE THREAD

**Issue by richardmward** [eclipse-che/che#14966]
## Summary
Hi. I am running my own installation of che on AWS having followed the instructions at https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/.

Now that there is a newer version of che available, I'd like to update. To do this, I tried running `chectl server:update -a helm` given the aws installation uses helm. Sadly this responds with "Error: 🛑 The specified installer helm does not support updating yet.".

Given this, could you give me direction as to what the process for updating is until such time as `chectl` supports updating helm based installations? (It's probably obvious to those that have more experience with Kubernetes / Helm - but this is my first expose to them, so any pointers gratefully received!)

**Comment by skabashnyuk** [comment]
@sleshchenko @monaka any ideas about that?

**Comment by sleshchenko** [comment]
@richardmward Chectl just set needed arguments for helm chart according to specified arguments.
Can you confirm that you use `chectl server:start --platform=k8s --installer=helm --domain=aws.my-ide.cloud --multiuser --tls` to deploy your Che? Then I'll provide a helm command with the right arguments to do update to new version. Also, which Che version you'll like to use? 7.3.0?

**Comment by sleshchenko** [comment]
@richardmward 
1. Checkout to https://github.com/eclipse/che/commit/2663460287286f2e04c6d50af7817dd0aa2de553 <- 7.3.0 release
2. Execute: 
```bash
CHE_REPO=/home/serg/projects/che
CHE_TEMPLATES=${CHE_REPO}/deploy

helm dependencies update --skip-refresh ${CHE_TEMPLATES}/kubernetes/helm/che/

helm upgrade --install che --force --namespace che \
  --debug \
  --set global.cheDomain=aws.my-ide.cloud \
  --set global.tls.useSelfSignedCerts=true \
  --set global.ingressDomain=aws.my-ide.cloud \
  --set cheImage=eclipse/che-server:7.3.0 \
  --set che-plugin-registry.chePluginRegistry.image=quay.io/eclipse/che-plugin-registry:7.3.0 \
  --set che-devfile-registry.cheDevfileRegistry.image=quay.io/eclipse/che-devfile-registry:7.3.0 \
  --set che-postgres.image=eclipse/che-postgres:7.3.0 \
  --set che-keycloak.image=eclipse/che-keycloak:7.3.0 \
  --set global.cheWorkspacesNamespace=che \
  -f ${CHE_TEMPLATES}/kubernetes/helm/che/values/multi-user.yaml \
  -f ${CHE_TEMPLATES}/kubernetes/helm/che/values/tls.yaml \
  ${CHE_TEMPLATES}/kubernetes/helm/che/
```
^ set your repo path into CHE_REPO
Also I assume you should use your own domain instead of example one `aws.my-ide.cloud`

**Comment by richardmward** [comment]
To the best of my knowledge, that seems to have worked. Certainly I see a version `7.3.0` in the bottom left of the che interface. Is there anything else you would like me to look at to confirm it is all correct?

**Comment by sleshchenko** [comment]
@richardmward you can also execute the following command to make sure that all right images are run (keycloak, postgres, etc.)
```
kubectl get deployment -n che -o go-template='{{range .items}}Deployment: {{.metadata.name}} | Image: {{range .spec.template.spec.containers}}{{.image}}{{end}};{{end}}' | tr ';' '\n'
```

**Comment by richardmward** [comment]
Yes, they all state as being at 7.3.0.

I notice within a workspace (created from the `nodejs-web-app` sample) I am getting an error on the plugins tab "Your registry is invalid". If i go to the URL that is defined as being the registry, it returns the registry listing. 

I don't know if this error was present before the upgrade or not - so could well be completely unrelated, and am happy to raise as a separate ticket if that'd be preferable?

**Comment by sleshchenko** [comment]
@richardmward Could you please check Developer Tools of browser? Are there failed requests from Dashboard to plugin-registry?

P.S. Also, could you please take a look here https://github.com/che-incubator/chectl/pull/340#issuecomment-546254174 I need your help and it should be easy to do.

**Comment by richardmward** [comment]
I see no failed requests from the dashboard to plugin-registry in the browser. I can see a number of INFO logs about it succesfully loading what I assume are the default plugins (ports-plugin, theia-containers-plugin, task-plugin, and many more).

In terms of error logs, I have

- `GET https://che-che.che.intechnology-plc.co.uk/api/permissions/system 404`
- `VM1749:1 GET https://che-che.che.intechnology-plc.co.uk/api/organization/find?name=<username> 404`
- `root ERROR TypeError: Cannot read property 'contentWindow' of undefined
    at t.onBeforeHide (https://static.developers.redhat.com/che/theia_artifacts/theia.f27c3030a09e7d53997f.js:1:2215287)`

---
With regard to che-incubator/chectl#340, you'll forgive me for being unable to download an archive from a random host and execute it in my environment - albeit well-intentioned, I hope you can understand why I can't do that.

**Comment by sleshchenko** [comment]
> With regard to che-incubator/chectl#340, you'll forgive me for being unable to download an archive from a random host and execute it in my environment - albeit well-intentioned, I hope you can understand why I can't do that.

Sure! It's fine. 
Do you think I can send somehow binaries safety or maybe you run chectl code from my brach, not much is required, maybe you already have dependencies like nodejs, yarn?

@richardmward Could you do share `kubectl get configmap che -n che | grep CHE_WORKSPACE_PLUGIN__REGISTRY__URL`

**Comment by richardmward** [comment]
I get no output from that command. If i remove the piped grep I only see:

```
NAME   DATA   AGE
che    59     22d
```

---
If you gave me the instructions to build / run from the branch, I think that would be fine.

**Comment by sleshchenko** [comment]
> I get no output from that command. If i remove the piped grep I only see:

Sorry, it's really my fault. -o=yaml is missing. So, the following should be better
```
kubectl get configmap che -n che -o=yaml | grep CHE_WORKSPACE_PLUGIN__REGISTRY__URL
```

**Comment by richardmward** [comment]
`  CHE_WORKSPACE_PLUGIN__REGISTRY__URL: https://plugin-registry-che.<aws.my-ide.cloud>/v3`.

**Comment by sleshchenko** [comment]
Seems just fine. Can you confirm that if you open `https://plugin-registry-che.<aws.my-ide.cloud>/v3/plugins` you get index.json with plugins list?

**Comment by richardmward** [comment]
Yes, I do. I guess if this isn't an issue others are seeing, the most likely difference to most setups will be the fact I am using a self signed cert. Perhaps that hasn't be set somewhere it needs to be.

**Comment by sleshchenko** [comment]
Did you import your self-signed CA into the browser?

**Comment by richardmward** [comment]
Yeah. Am using chrome, and che opens without any certificate warnings.

![image](https://user-images.githubusercontent.com/688465/67572348-f2c38680-f72d-11e9-8368-b8ccf188d76c.png)

**Comment by sleshchenko** [comment]
@richardmward The certificate for che-plugin registry is marked by Chrome secure as well?

**Comment by richardmward** [comment]
Yes

**Comment by sleshchenko** [comment]
Then I don't have an idea why `Your registry is invalid` may happen.
let's close this issue since seems the described issue is solved and feel free to open a new one with detailed description, maybe exported HAR from Chrome
