### ISSUE TITLE
chectl is not compliant with the codeready deployment flavor / stucks at the  PostgreSQL pod bootstrap (Post installation checklist)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14963]
chectl stucks at the  PostgreSQL pod bootstrap (Post installation checklist)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. start crc
2.  chectl server:start -a operator -p crc -b console-openshift-console.apps-crc.testing -n crw --che-operator-image=quay.io/ibuziuk/che-operator:che-14809 --che-operator-cr-yaml=crw.yaml
3. ERROR:
```
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "crw"...it is not
  ✔ ✈️  CodeReady Containers preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if crc is installed...done.
    ✔ Verify if CodeReady Containers is running...done.
    ✔ Retrieving CodeReady Containers IP and domain for routes URLs...192.168.130.11.nip.io.
 ›   Warning: Che will be deployed in Multi-User mode since Configured 'operator' installer which support only such.
  ✔ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (crw)...done.
    ✔ Create ServiceAccount che-operator in namespace crw...done.
    ✔ Create Role che-operator in namespace crw...done.
    ✔ Create ClusterRole che-operator...It already exists.
    ✔ Create RoleBinding che-operator in namespace crw...done.
    ✔ Create ClusterRoleBinding che-operator...It already exists.
    ✔ Create CRD checlusters.org.eclipse.che...It already exists.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace crw...done.
    ✔ Create Che Cluster eclipse-che in namespace crw...done.
  ❯ ✅  Post installation checklist
    ❯ PostgreSQL pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Keycloak pod bootstrap
      Devfile registry pod bootstrap
      Plugin registry pod bootstrap
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
    at KubeHelper.<anonymous> (~/.local/share/chectl/client/7.3.0/lib/api/kube.js:598:19)
    at Generator.next (<anonymous>)
    at fulfilled (~/.local/share/chectl/client/7.3.0/node_modules/tslib/tslib.js:107:62)
```
But in reality the pod started:

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/67396569-1f4d9600-f5a8-11e9-8ee1-bad04d5f611a.png)

Also, there is hardcoded route names
https://github.com/che-incubator/chectl/blob/master/src/api/che.ts#L111 which fails start of workspace in CRW.

![Screenshot from 2019-10-25 10-11-06](https://user-images.githubusercontent.com/1197777/67561649-e9ceb700-f725-11e9-9ee5-9c92ec5720a6.png)

### Runtime
   - [x] crc

### Expected behavior
che is started against crc without errors - all checks in the checklist should pass

### Runtime
   - [x] crc

### Installation method
   - [x] chectl 

### Environment
   - [x] Fedora 30

**Comment by sleshchenko** [comment]
@ibuziuk thanks for reporting it. It happens because of labels mismatching: chectl expects 'app=che,component=postgres' while crc postgres has `'app=codeready,component=postgres'`
https://github.com/che-incubator/chectl/blob/master/src/tasks/che.ts#L38

**Comment by ibuziuk** [comment]
@sleshchenko ah, ok  - so looks like chectl is not compliant with the codeready deployment flavour

**Comment by benoitf** [comment]
hello, is someone already working on a fix ?

**Comment by ibuziuk** [comment]
no, I just build a custom binary by replacing che labels with codeready, but I can take care of this issue

**Comment by rhopp** [comment]
Downstream issue: https://issues.jboss.org/browse/CRW-437

**Comment by benoitf** [comment]
@ibuziuk OK so I should assign osio team backlog ?

**Comment by nickboldt** [comment]
See also https://issues.jboss.org/browse/CRW-328 re: productized chectl.

**Comment by ibuziuk** [comment]
@nickboldt @benoitf che/osio can prioritize this issue for the next sprint
@l0rd wdyt? I believe we do not need to cretate specific `codeready-workspaces-chectl` (vanilla chectl can handle both falvours )

**Comment by ibuziuk** [comment]
```
    ✔ Keycloak pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Retrieving Che Server URL...https://codeready-eclipse-che.apps-crc.testing
    ✔ Che status check
Command server:start has completed successfully.
```

Changes required for making chectl compatible with `codereaady` - https://github.com/che-incubator/chectl/compare/master...ibuziuk:che-14963?expand=1

**Comment by ibuziuk** [comment]
Closing, the initial implementation of CRW specific chectl (crwctl is available) in https://github.com/redhat-developer/codeready-workspaces-chectl

**Comment by dmytro-ndp** [comment]
Downstream issue: https://issues.jboss.org/browse/CRW-463
