### ISSUE TITLE
Che two Cluster setup

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#14961]
## Summary
Is it possible to set up che on two clusters, so that the one cluster is used for the che-server and the other one for the workspaces?
If so, I would appreciate some instructions in how to accomplish this.
## Relevant information
The cluster where the server should run is an openshift cluster.
For the other cluster it is not important if it is a openshift, a kubernetes or whatever cluster, as long the workspaces can be run on it.

**Comment by ibuziuk** [comment]
@anthonma unfortunately, Eclipse Che does not support this functionality - both che-server and workspaces should run on the same cluster. However,  rh-che [1] (SaaS /  Eclipse Che hosted by Red Hat) does support this functionality. If you think that this is a valuable functionality for upstream, please open a feature request and we will prioritize it accordingly. It would be also great to understand more the use-case and why would you like to have the two cluster setup in place. A detailed description would be much appreciated.

[1] https://github.com/redhat-developer/rh-che
[2] https://www.eclipse.org/che/docs/che-7/hosted-che/#about-hosted-che_hosted-che

**Comment by anthonma** [comment]
Thank you for your response. I will take a look at rh-che, if it fits my requirements. If not I will think about opening a feature request.

**Comment by anthonma** [comment]
I've reopened this issue, because I would like to know why it ist not possible to set-up Che the way I have eplained at the beginning of this issue. When I asked in october it was enough to know that Che doesn't support it, but now I would like to know why.

**Comment by gorkem** [comment]
There are not too many reasons to separate Che server and workspace clusters, it would be interesting to understand yours. I guess such a set up requires user and/or service account tokens to be shared between clusters which is not desirable. 

Also in the future Che will move to using kubernetes controllers to manage workspaces which will make such setup even harder to support.

**Comment by anthonma** [comment]
Thanks for your reply, but I will close this Issue again, because it is no longer relevant to me.
