### ISSUE TITLE
Remove Che 6 specific doc from eclipse.org/che/docs

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14971]
### Is your task related to a problem? Please describe.

Users are still reading and following Che 6 documentation and are opening issues about features that don't work anymore or that we do not support.

### Describe the solution you'd like

In eclipse.org/che/docs we should only have the latest Che documentation.

### Describe alternatives you've considered

Move Che 6 documentation on a branch in the github repository

**Comment by l0rd** [comment]
cc @themr0c @MichalMaler @rkratky

**Comment by rkratky** [comment]
@l0rd, fixed in https://github.com/eclipse/che-docs/pull/874

**Comment by themr0c** [comment]
Removed from the codebase, but as the deployment does not remove old files, it is still possible to access che-6 documentation on the website.

**Comment by l0rd** [comment]
> Removed from the codebase, but as the deployment does not remove old files, it is still possible to access che-6 documentation on the website.

@themr0c +1 to fix that but it's not a big problem so I am closing this issue. 

Something I would like to discuss with you is about moving the content of the `pages/che-7/` to `pages/`.

There a couple of reasons for that:
1. Links like the getting started currently contain the `che-7` string but I want this link to continue to be valid even after che-7 
2. When we release a Che 8 we are hopefully not going to create a separate tree as we have done for Che 7 but we want to progressively update the existing tree

Do you think that it's worth it?

**Comment by themr0c** [comment]
I believe that it would be a great idea to switch to a system where versioning the documentation is possible, and where default entry point is latest documentation (see for example https://docs.ansible.com/ansible/latest/index.html or https://docs.antora.org/antora/2.1/features/). Then, as always, it will be a question of choosing priorities.

**Comment by l0rd** [comment]
@themr0c yes that would be even better: every time we do a release, we do a documentation release as well. Even if from my experience it may not work well with google searches (i.e. the links to a specific old version comes up in the top results). 

Anyway for now we may just move `/pages/che7/` to `/pages/latest` and have any request to `/pages/che7/` redirected to `/pages/latest/`?

**Comment by themr0c** [comment]
IMHO we should list somewhere all the things that we want to change in the way the documentation look like and is published:

* multiversioning: 
  * default to latest released version.
  * old versions are accessible (with warning: "this is not the latest stable version")
  * master is accessible (with warning: "this is the development version")
* (accept) new style / css.
  * get rid of all these old javascripts
  * proposal for a new style (who?)
* challenge build system:
  * ensure old files are removed
  * update versions of build libraries (asciidoctor, jekyll, etc.)
  * get rid of docker (replace with podman)
  * investigate antora as a replacement for jekyll

I would be very happy to work on it after the release of CRW, if we can prioritize it accurately.
