### ISSUE TITLE
chectl: server:update should provide an ability to update Che Server configuration

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14974]
### Is your enhancement related to a problem? Please describe.
Currently, server:update only applied installer resources and update images version.
It would be nice if it also allows user to update Che Server configuration with different arguments that user is able to use for `server:start`, like `--multiuser`, `--tls`, `--self-signed-cert`, etc.

**Comment by tsmaeder** [comment]
Does updating those properties now require an uninstall/install of che or can they be changed in the kubernetes config?

**Comment by sleshchenko** [comment]
> Does updating those properties now require an uninstall/install of che or can they be changed in the kubernetes config?

I believe changing kubernetes objects is enough. The only config we should not allow to reconfigure - `--multiuser` since data will be lost and it may be not something a user expects to see.
