### ISSUE TITLE
[chectl] Support helm installer for server:update command 

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14973]
### Is your enhancement related to a problem? Please describe.
Support helm installer for server:update command.

### Describe the solution you'd like
Support helm installer for server:update command.
The difficulty I see here: it's not clear how to handle values. 
The easiest solution I see: user must specify exactly the same arguments that they specified during for `server:start`, like `server:start --domain=myk8s.com --tls --multiuser`.
Or maybe chectl is able to read values of deployed Che from deployed Helm Chart as application, maybe try to guess smart according to created k8s objects, like postgresq, TLS cert, etc.

**Comment by anortef** [comment]
Any news on this? because in the docs helm is the default for some platforms and this would be something nice to have.

**Comment by tolusha** [comment]
chectl doesn't support `--installer helm` anymore.
We introduced another Helm Charts [1] in [2]

[1] https://github.com/eclipse-che/che-operator/tree/main/helmcharts
[2] https://github.com/eclipse-che/che-operator/pull/1184
