### ISSUE TITLE
chectl: released chectl deploy some nightly images when helm is used as installer

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14977]
### Describe the bug
Released chectl from stable channel deploys some nightly images (plugin-registry/devfile-registry/keycloak/postgres) when helm is used as installer.
Missing arguments for helm chart:
```
  --set che-plugin-registry.chePluginRegistry.image=quay.io/eclipse/che-plugin-registry:7.3.0 \
  --set che-devfile-registry.cheDevfileRegistry.image=quay.io/eclipse/che-devfile-registry:7.3.0 \
  --set che-postgres.image=eclipse/che-postgres:7.3.0 \
  --set che-keycloak.image=eclipse/che-keycloak:7.3.0 \
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Download released chectl from stable channel like [7.3.0](https://github.com/che-incubator/chectl/releases/tag/20191019081631).
2. Deploy Che with helm as installer.

### Expected behavior
All che-components have the same version as downloaded chectl

### Actual behavior
Che Server has the same version as downloaded chectl but others components (plugin-registry/devfile-registry/keycloak/postgres) have nightly version since they are default in helm chart, like https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml#L11

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by tsmaeder** [comment]
The release cycle of chectl is different from che itself: https://github.com/che-incubator/chectl/releases

Default is "nightly" even for using the operator, if that hasn't changed recently.

**Comment by sleshchenko** [comment]
@tsmaeder nightly is the default for `next` channel, but in case of stable channel like [7.3.0](https://github.com/che-incubator/chectl/releases/tag/20191019081631) the operator will have 7.3.0 images. Updated description to make it clear.

**Comment by tolusha** [comment]
Not the case anymore.
`chectl` from the stable channel does not use `nightly` images 

```bash
chectl server:start --platform minikube --installer helm  -m
```

**Comment by tolusha** [comment]
![Screenshot from 2020-04-12 15-23-06](https://user-images.githubusercontent.com/1640675/79068703-86cfdd00-7cd1-11ea-9cae-3ed04fc8f6e1.png)
