### ISSUE TITLE
chectl: add an ability to debug Che Server

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#14976]
### Is your enhancement related to a problem? Please describe.
Debugging of Che Server requires additional settings:
1. `CHE_DEBUG_SERVER` env vars.
2. Tuning of readiness/liveness probes to avoid container killing when breakpoint is set.

So, it makes me think that chectl could have `--debug` argument for `server:start`, `server:update` commands.
Also, as an additional sugar we could implement `server:debug` that will find right Che Pod and do port-forward.

**Comment by tsmaeder** [comment]
Why not make the liveness probes, etc. respect the CHE_DEBUG_SERVER env var? Sounds like a simpler proposition.

**Comment by sleshchenko** [comment]
> Why not make the liveness probes, etc. respect the CHE_DEBUG_SERVER env var?

I'm not aware about such an ability in the out-of-box k8s probes mechanism. Could you share more about it?

**Comment by skabashnyuk** [comment]
Rising to p1 since it's related to UX (https://github.com/eclipse/che/issues/14997) and dogfooding.

**Comment by tolusha** [comment]
https://github.com/eclipse/che-operator/pull/151
