### ISSUE TITLE
Inconsistent devfile selection in dashboard; no way to specify preferred devfile

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14986]
### Describe the bug
In Che 6 we had functionality to specify, through config, the default stack that is selected when creating a workspace. In Che 7, this appears to work in a much more strange way:

- Devfiles in the dashboard are sorted alphabetically
- The default selected devfile when entering the page is the first devfile in the `index.json`, which ends up being the [first subdirectory in `devfiles`](https://github.com/eclipse/che-devfile-registry/tree/master/devfiles)

This results in the selected devfile being in a semi-random spot on the list (in current nightlies, it's near the middle).

### Che version
- [x] nightly

### Expected behavior
At minimum, the default selected devfile would be the top one on the sorted list (e.g. angular, currently).

**Comment by sleshchenko** [comment]
I believe it's not actual anymore since UI is reworked in a way where there is no selected devfile by default and you need to click on the cards to create a workspace from that
![Screenshot_20201001_161817](https://user-images.githubusercontent.com/5887312/94814234-bac6c800-0401-11eb-9f67-2cf8eb271b14.png)

**Comment by amisevsk** [comment]
I agree that this is pretty much resolved.

@nickboldt Just wanted to double check your opinion here -- I created this issue after our discussion on ordering devfiles in CRW, where we wanted devfiles to appear in a certain order and have a specific devfile selected by default (which is there reason CRW still uses the [`00_foldername`](https://github.com/redhat-developer/codeready-workspaces/tree/crw-2.5-rhel-8/dependencies/che-devfile-registry/devfiles) naming scheme).

**Comment by sleshchenko** [comment]
> where we wanted devfiles to appear in a certain order and have a specific devfile selected by default 

We had a dedicated issue for that on Dashboard side which was closed by inactivity and I even did not find it ) So, if it's a case - a new issue should be created for that.
