### ISSUE TITLE
[che-theia] build of che-theia image is unstable on `node-gyp install` step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14983]
### Describe the bug
che-theia build sometimes fails on `node-gyp install` command, for example:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/417/console:
<details>
 <summary>CRW CCI build log</summary>
 <pre>
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
10.16.3
gyp info ok 
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.10.2: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.3.0-next.6: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning "workspace-aggregator-9faddb37-a853-4bf3-82f8-3bb532c860ca > @eclipse-che/theia-assembly > html-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /home/theia-dev/theia-source-code/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/theia-dev/theia-source-code/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.4
gyp info using node@10.16.3 | linux | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/home/theia-dev/theia-source-code/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/theia-dev/theia-source-code/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/theia-dev/theia-source-code/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/theia-dev/.cache/node-gyp/10.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/theia-dev/.cache/node-gyp/10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/theia-dev/theia-source-code/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/theia-dev/.cache/node-gyp/10.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/theia-dev/theia-source-code/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/theia-dev/theia-source-code/node_modules/native-keymap/build'
  CXX(target) Release/obj.target/keymapping/src/string_conversion.o
  CXX(target) Release/obj.target/keymapping/src/keymapping.o
In file included from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:63,
                 from ../src/keymapping.cc:6:
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8.h:8878:3: error: unterminated comment
   /**
   ^
In file included from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:63,
                 from ../src/keymapping.cc:6:
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8.h:15: error: unterminated #ifndef
 #ifndef INCLUDE_V8_H_
 
In file included from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8-platform.h:10,
                 from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:64,
                 from ../src/keymapping.cc:6:
/usr/include/c++/8.3.0/stdlib.h:38:12: error: using-declaration for non-member at class scope
 using std::abort;
            ^~~~~
/usr/include/c++/8.3.0/stdlib.h:39:12: error: using-declaration for non-member at class scope
 using std::atexit;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:40:12: error: using-declaration for non-member at class scope
 using std::exit;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:43:14: error: using-declaration for non-member at class scope
   using std::at_quick_exit;
              ^~~~~~~~~~~~~
/usr/include/c++/8.3.0/stdlib.h:46:14: error: using-declaration for non-member at class scope
   using std::quick_exit;
              ^~~~~~~~~~
/usr/include/c++/8.3.0/stdlib.h:51:12: error: using-declaration for non-member at class scope
 using std::div_t;
            ^~~~~
/usr/include/c++/8.3.0/stdlib.h:52:12: error: using-declaration for non-member at class scope
 using std::ldiv_t;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:54:12: error: using-declaration for non-member at class scope
 using std::abs;
            ^~~
/usr/include/c++/8.3.0/stdlib.h:55:12: error: using-declaration for non-member at class scope
 using std::atof;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:56:12: error: using-declaration for non-member at class scope
 using std::atoi;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:57:12: error: using-declaration for non-member at class scope
 using std::atol;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:58:12: error: using-declaration for non-member at class scope
 using std::bsearch;
            ^~~~~~~
/usr/include/c++/8.3.0/stdlib.h:59:12: error: using-declaration for non-member at class scope
 using std::calloc;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:60:12: error: using-declaration for non-member at class scope
 using std::div;
            ^~~
/usr/include/c++/8.3.0/stdlib.h:61:12: error: using-declaration for non-member at class scope
 using std::free;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:62:12: error: using-declaration for non-member at class scope
 using std::getenv;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:63:12: error: using-declaration for non-member at class scope
 using std::labs;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:64:12: error: using-declaration for non-member at class scope
 using std::ldiv;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:65:12: error: using-declaration for non-member at class scope
 using std::malloc;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:67:12: error: using-declaration for non-member at class scope
 using std::mblen;
            ^~~~~
/usr/include/c++/8.3.0/stdlib.h:68:12: error: using-declaration for non-member at class scope
 using std::mbstowcs;
            ^~~~~~~~
/usr/include/c++/8.3.0/stdlib.h:69:12: error: using-declaration for non-member at class scope
 using std::mbtowc;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:71:12: error: using-declaration for non-member at class scope
 using std::qsort;
            ^~~~~
/usr/include/c++/8.3.0/stdlib.h:72:12: error: using-declaration for non-member at class scope
 using std::rand;
            ^~~~
/usr/include/c++/8.3.0/stdlib.h:73:12: error: using-declaration for non-member at class scope
 using std::realloc;
            ^~~~~~~
/usr/include/c++/8.3.0/stdlib.h:74:12: error: using-declaration for non-member at class scope
 using std::srand;
            ^~~~~
/usr/include/c++/8.3.0/stdlib.h:75:12: error: using-declaration for non-member at class scope
 using std::strtod;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:76:12: error: using-declaration for non-member at class scope
 using std::strtol;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:77:12: error: using-declaration for non-member at class scope
 using std::strtoul;
            ^~~~~~~
/usr/include/c++/8.3.0/stdlib.h:78:12: error: using-declaration for non-member at class scope
 using std::system;
            ^~~~~~
/usr/include/c++/8.3.0/stdlib.h:80:12: error: using-declaration for non-member at class scope
 using std::wcstombs;
            ^~~~~~~~
/usr/include/c++/8.3.0/stdlib.h:81:12: error: using-declaration for non-member at class scope
 using std::wctomb;
            ^~~~~~
In file included from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:64,
                 from ../src/keymapping.cc:6:
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8-platform.h:16:1: error: expected unqualified-id before 'namespace'
 namespace v8 {
 ^~~~~~~~~
In file included from ../src/keymapping.cc:6:
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:105:1: error: expected unqualified-id before 'namespace'
 namespace node {
 ^~~~~~~~~
In file included from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:186,
                 from ../src/keymapping.cc:6:
/usr/include/assert.h:16:8: error: expected unqualified-id before string constant
 extern "C" {
        ^~~
In file included from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:201,
                 from ../src/keymapping.cc:6:
/usr/include/sys/types.h:4:8: error: expected unqualified-id before string constant
 extern "C" {
        ^~~
In file included from ../src/keymapping.cc:6:
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:205:1: error: expected unqualified-id before 'namespace'
 namespace node {
 ^~~~~~~~~
In file included from /usr/include/c++/8.3.0/map:60,
                 from ../src/keymapping.cc:7:
/usr/include/c++/8.3.0/bits/stl_tree.h:75:1: error: expected unqualified-id before 'namespace'
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
In file included from /usr/include/c++/8.3.0/map:61,
                 from ../src/keymapping.cc:7:
/usr/include/c++/8.3.0/bits/stl_map.h:66:1: error: expected unqualified-id before 'namespace'
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
In file included from /usr/include/c++/8.3.0/map:62,
                 from ../src/keymapping.cc:7:
/usr/include/c++/8.3.0/bits/stl_multimap.h:64:1: error: expected unqualified-id before 'namespace'
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
In file included from ../src/keymapping.h:10,
                 from ../src/keymapping.cc:9:
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/uv.h:27:8: error: expected unqualified-id before string constant
 extern "C" {
        ^~~
In file included from ../src/keymapping.cc:9:
../src/keymapping.h:15:1: error: expected unqualified-id before 'namespace'
 namespace vscode_keyboard {
 ^~~~~~~~~
../src/keymapping.cc:11:1: error: expected unqualified-id before 'namespace'
 namespace vscode_keyboard {
 ^~~~~~~~~
../src/keymapping.cc:30:1: error: expected '}' at end of input
 } // namespace vscode_keyboard
 ^
In file included from /home/theia-dev/.cache/node-gyp/10.16.3/include/node/node.h:63,
                 from ../src/keymapping.cc:6:
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8.h:8708:25: note: to match this '{'
 class V8_EXPORT Context {
                         ^
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8.h:8800:59: error: expected unqualified-id at end of input
       MaybeLocal<Value> global_object = MaybeLocal<Value>());
                                                           ^
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8.h:8800:59: error: expected '}' at end of input
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8.h:64:14: note: to match this '{'
 namespace v8 {
              ^
/home/theia-dev/.cache/node-gyp/10.16.3/include/node/v8.h:3489:19: warning: inline function 'void* v8::Object::GetAlignedPointerFromInternalField(int)' used but never defined
   V8_INLINE void* GetAlignedPointerFromInternalField(int index);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [keymapping.target.mk:102: Release/obj.target/keymapping/src/keymapping.o] Error 1
make: Leaving directory '/home/theia-dev/theia-source-code/node_modules/native-keymap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/theia-dev/theia-source-code/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/home/theia-dev/theia-source-code/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/theia-dev/theia-source-code/node_modules/native-keymap
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.4
gyp ERR! not ok
 </pre>
</details>

There was the same failure on Codenvy CI: https://ci.codenvycorp.com/view/pr-builds/job/che-theia-pullrequests-build/869/consoleFull

### Reference
https://github.com/eclipse/che/issues/13748

### Che-theia version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
`<che-theia>/build.sh --skip-tests --dockerfile:Dockerfile.alpine`

### Environment
- Codenvy CI
- CRW CCI

**Comment by benoitf** [comment]
AFAIK it's not fully fixed as it can be reproduced by QA

**Comment by nickboldt** [comment]
"Not fully fixed" = "we should reopen this".

See also #15480 15480

**Comment by benoitf** [comment]
do not see it again on all builds from github/ci.centos builds
