### ISSUE TITLE
Devfile and plugin registry image regex doesn't recognize registry URLs that have a colon

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#14990]
### Describe the bug

When running the devfile and plugin registries in offline mode, and the image registry you are using has a port e.g. `myhost.registry:5000`, the regex to update the image references will not substitute everything properly, causing the offline che installation to try to pull images from the wrong spot.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.3.0

### Expected behavior

The devfile and plugin registries should references images in the correct spots

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 7.3.0
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by amisevsk** [comment]
PRs open

**Comment by ibuziuk** [comment]
PRs are merged @amisevsk @tomgeorge can we close the issue now?

**Comment by tomgeorge** [comment]
yes, this can be closed
