### ISSUE TITLE
How to launch Che (eclipse-che-7.0.0-rc-4.0) and debug?

### ISSUE THREAD

**Issue by PointerTan** [eclipse-che/che#14997]
I read the document: https://github.com/eclipse/che/wiki/Development-Workflow,-Che-7
But I can't start the assembly from "assembly/assembly-main/target/eclipse-che-7.0.0-rc-4.0/eclipse-che-7.0.0-rc-4.0"  
And I also didn't find a way to launch che-server locally and how to run it in a debug mode . I already launch Dashbroad project.
Is there any newer document?

**Comment by skabashnyuk** [comment]
At this moment  ```chectl``` way to install che doesn't provide an ability to run che-server in debug mode. The issue to track https://github.com/eclipse/che/issues/14976

**Comment by tolusha** [comment]
The issue https://github.com/eclipse/che/issues/14976 has been resolved. To debug Eclipse Che Server locally:
- update `chectl`: 
```bash
$ checlt update
```

- redeploy che with `--debug` flag.
```bash
$ chectl server:start --debug ....
```
- forward `8000` port
```bash
$ chectl server:debug
```
