### ISSUE TITLE
Che preferences are not displayed after page refreshing

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15001]
### Describe the bug
`File` -> `Settings` -> `Open Preferences` displays preferences, `Che` preferences are displayed as well, but after page refreshing `Che` preferences are absent.

### Che version
latest

### Steps to reproduce

1. Go to `File` -> `Settings` -> `Open Preferences`
You can find `Che` preferences in the widget
2. Refresh page
You can see that the `Preferences` are restored, but `Che` preferences are absent.

### Expected behavior
the `Preferences` contain `Che` preferences after refreshing page

### Runtime
   minikube version: v1.0.0
   
### Screenshots
https://youtu.be/DZf0J-md84U

### Installation method
   chectl/0.0.2-5ab0061 linux-x64 node-v10.4.1
### Environment
   - [x] my computer: Linux

**Comment by tsmaeder** [comment]
If we save in this state, I suspect we would lose data? I think this is with the remit if IDE1 team, please forward if not appropriate.
