### ISSUE TITLE
Profiling Che startup times and possible optimisations

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#15002]
## Summary

I was trying to understand and profile Che workspace startup times. 

Using the Jaeger deployment I could get a chart of the time spent on different activities while bringing up a single workspace. Below is the screenshot:

![Screenshot 2019-10-28 at 4 29 25 PM](https://user-images.githubusercontent.com/16825130/67673829-032f6780-f9a1-11e9-9228-91b0bdc0edb4.png)

Few questions/clarifications I am trying to get are:

1. Why is CommonPVCStrategy#prepare being done twice? Is this necessary given I believe it is the same PVC?
2. What is the broker doing during a workspace start? 
3. Are there any optimisations anybody is aware of to decrease startup time of a workspace? I'm looking at a sub 1 minute number optimistically.

Thanks in advance.

## Relevant information

Version: Che 7.3.0
Infrastructure: Kubernetes
Platform: GKE

**Comment by tsmaeder** [comment]
Workspace startup is a roadmap item.
