### ISSUE TITLE
Plugin Broker failed to start if userID contains :

### ISSUE THREAD

**Issue by filipkroupa** [eclipse-che/che#15013]
### Describe the bug
When starting workspace, workspace fails with error message: 
`Error: Failed to run the workspace: "Plugins installation process timed out"`

In minikube cluster, che-plugin-broker is seen in status Init:Error.
Logs from container eclipse-che-init-plugin-broker-v0-22 say: 
`2019/10/29 12:12:46 Expected runtime id to be in format 'workspace:env:ownerId'`

che-plugin-broker pod description shows this: 
`-runtime-id workspace9sf22yxtjmr71u75:default:f:a78d3304-d12b-4c40-ab27-b54ec3a4f143:fk633080`
which obviously does not conform to the mentioned expected format

### Che version

 - [x] other: 7.3.0

### Steps to reproduce

See additional context

### Expected behavior

Expected is normal workspace startup.

### Runtime
 - minikube (include output of `minikube version` and `kubectl version`)
 
```
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - chectl

```
$ chectl server:start --multiuser --platform=minikube`
$ chectl version
chectl/7.3.0 linux-x64 node-v10.16.3
```

### Environment

Custom server running on VM - CentOS Linux release 7.7.1908 (Core)

### Additional context

Problem started to appear after adding new custom devfile stack into devfile-registry following [this guide](https://www.eclipse.org/che/docs/che-7/editing-a-devfile-and-plug-in-at-runtime/#adding-a-devfile-at-runtime_editing-a-devfile-and-plug-in-at-runtime).
Since this moment, no workspace can be started, does not matter if it comes from predefined stacks of using external devfile with factory.

**Comment by filipkroupa** [comment]
Error message shown in UI when starting using factory gives more details on runtimeID contents, seems the issue is ownerId containing colons:
```
Error when starting workspace
Unable to start workspace. Error when trying to start the workspace: Runtime start for identity 'workspace: workspaceuvkpzvh2ckns08x2, environment: default, ownerId: f:a78d3304-d12b-4c40-ab27-b54ec3a4f143:fk633080' is interrupted
```

**Comment by l0rd** [comment]
@filipkroupa It would also be interesting if you could provide the `devfile.yaml` that you have added to the registry with it's `meta.yaml` and the registry `index.html`.  You can copy/paste the files here or use pastebin, it's how you prefer. 

If you stop and restart the devfile registry all you changes should be resetted and you may be able to come back to the initial status. Would you mind trying that as well?

**Comment by filipkroupa** [comment]
It was just a coincidence the problem first manifested after updating the devfile. I investigated more and the issue emerges in multiuser config with Keycloak configured to use LDAP federation.

**Steps to reproduce:**
- deploy Che 7.3.0 on minikube in multiuser mode
- configure Keycloak to provide user accounts from LDAP server using User Federation
- login to Che using credentials of LDAP user
- create and start workspace
- you'll see Kubernetes pod `che-plugin-broker` in status `Init:Error`

If I do not configure Keycloak and use default user admin/admin, everything works just fine. The `che-plugin-broker` pod is started with parameter `-runtime-id workspacem96e6c2hiwgmir8r:default:116f6b67-066e-4221-8a80-7d75734d643c` which is ok. But after configuring Keycloak and using LDAP user credentials, `che-plugin-broker` pod is started with parameter `-runtime-id workspacete1prvrydnhsnvc2:default:f:65d2c280-a3c8-4b89-b00b-ca99b82e488b:fk633080` which cannot be parsed, since the userid part contains the separator (':').

**Comment by sleshchenko** [comment]
@filipkroupa `2019/10/29 12:12:46 Expected runtime id to be in format 'workspace:env:ownerId'` should not happen anymore, if so - feel free to reopen this one.
Note I haven't tested the whole workflow with LDAP integration, so if there is another place which does not allow to start workspace because of `:` in the userID, feel free to register a new issue.

**Comment by filipkroupa** [comment]
Will test this in LDAP environment as soon as che-plugin-metadata-broker version is bumped to 3.1.2 in che-operator.

**Comment by filipkroupa** [comment]
I have now Keycloak with LDAP setup on two minikube based Che instances, since plugin broker 3.1.2 everything works as expected. Thank you.
