### ISSUE TITLE
Start analyze using local tools connected to Che workspace 

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#15016]
### We need to analyze different tools which we can use to connect Che workspace to local environment

We may use various tools to synchronize project files between Che workspace and local PC:

- SFTP(SSH FS)
- WebDav
- Rsync
- FTP
- KSync
- [kubectl-warp](https://github.com/ernoaapa/kubectl-warp)
...

**Comment by evidolob** [comment]
cc @slemeur

**Comment by l0rd** [comment]
Please look at KSync for files syncing

**Comment by tsmaeder** [comment]
@l0rd Is there a roadmap item this connects to?

**Comment by l0rd** [comment]
@tsmaeder I don't know where this issue come from honestly. Will discuss that tomorrow during priorisation with @slemeur

**Comment by AndrienkoAleksandr** [comment]
During investigation ksync usage found that ksync doesn't work with volumes such like `/projects`

**Comment by l0rd** [comment]
We should look at https://github.com/ernoaapa/kubectl-warp as well

**Comment by benoitf** [comment]
We now have two blog posts:
- https://che.eclipse.org/working-offline-with-eclipse-che-ee5cdb29d0ec
- https://che.eclipse.org/work-on-my-laptops-project-from-a-remote-eclipse-che-workspace-b42c68a77e1

**Comment by l0rd** [comment]
@benoitf in order to close this issue we should have, in Che documentation, a reference to the blog posts.

**Comment by sympatheticmoose** [comment]
@l0rd so is this just waiting on a doc update? Do we have a corresponding issue to add those links?

**Comment by l0rd** [comment]
@sympatheticmoose no we do not have a specific issue. We can use this one or close it and open a new one.

**Comment by sympatheticmoose** [comment]
cc @rkratky - thoughts on adding links vs incorporating somehow in Che docs?
