### ISSUE TITLE
.NET Core applications cannot be debugged

### ISSUE THREAD

**Issue by tmds** [eclipse-che/che#15017]
### Describe the bug

.NET Core applications cannot be debugged.

### Che version

https://che.openshift.io

### Steps to reproduce

- Add default .NET Core stack (2.2).
- Start the debugger

### Expected behavior

Project can be debugged

### Actual behavior

The debugger fails to launch the application.
Debug console shows:
```
...
No executable found matching command "dotnet-/projects/dotnet-web-simple/bin/Debug/netcoreapp2.2/web.dll"
```

**Comment by svor** [comment]
before running the debug need to build the project by executing build command:
![screenshot-che openshift io-2019 10 30-10_13_39](https://user-images.githubusercontent.com/1271546/67840204-fd02cd80-fafd-11e9-9792-117cb7a9914a.png)

There is an issue to make it automatically: https://github.com/eclipse/che/issues/15025

**Comment by tmds** [comment]
> before running the debug need to build the project by executing build command:

I'll give that a try.

> There is an issue to make it automatically: #15025

👍 this will match vscode behavior.

**Comment by tsmaeder** [comment]
Closing in favor of https://github.com/eclipse/che/issues/15025
