### ISSUE TITLE
[regression] Whitelabel support in Che 7 requires specific image names, where in Che 6 we could override with json

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15015]
### Describe the bug

In Che 6, we could use a product.json to override branding elements, like this:

https://github.com/redhat-developer/codeready-workspaces/blob/1.2.2.GA/assembly/assembly-dashboard-war/src/main/webapp/assets/branding/product.json.template

But with Che 7, we had to rename the images to use the Che 7 defaults:

https://github.com/redhat-developer/codeready-workspaces/commit/32c3ef4b46be4fc4f1b02233741f375172094424

### Che version

 - [x] 7.3.0

**Comment by nickboldt** [comment]
Note: not a blocker for CRW 2.

**Comment by nickboldt** [comment]
This might actually be a blocker if it turns out I'm right and this is also causing https://issues.jboss.org/browse/CRW-451 cc: @rhopp @evidolob

**Comment by olexii4** [comment]
cannot reproduce
