### ISSUE TITLE
Factory for editing the web site is missing "start che-website" command

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#15029]
I wanted to fix a few typos and broken links on the Che website and tried to use the factory offered on the GitHub repo for modifying the website (https://github.com/eclipse/che-website).
I am able to launch the workspace via the factory (https://che.openshift.io/f?url=https://github.com/eclipse/che-website) and the web site sources are checked out correctly. However, the command to "run" the website seems not available, i.e. if I press f1 and type "start che-website", there is no command.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: as defined by the factory

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: openshift.io

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] openhift.io
   - [ ] other: please specify

**Comment by JonasHelming** [comment]
Wonderful! Thanks! I will enhance the Readme to clarify that...

**Comment by benoitf** [comment]
@JonasHelming yes if it is not clear, please report/fix it 👍
