### ISSUE TITLE
devfile schema validation failed. 

### ISSUE THREAD

**Issue by ctday** [eclipse-che/che#15022]
devfile schema validation failed. Error: (/metadata/generateName):The object must not have a property whose name is "generateName".

running: che RC-2.0
trying to create workspace: NodeJS Angular Web Application
with project: nodejs-hello-world

Any help would be appreciated

**Comment by tolusha** [comment]
@ctday 
for RC-2.0 it is supposed to be `name` instead of `generateName`

**Comment by sparkoo** [comment]
@ctday `generateName` was introduced in 7.1.0

**Comment by skabashnyuk** [comment]
@ctday you can follow Quickstarts https://www.eclipse.org/che/docs/che-7/che-quick-starts/ to get latest-greatest version of Che.
