### ISSUE TITLE
Specify max RAM and CPU for workspaces

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#15026]
## Summary
Is it possible to specify, how much RAM and CPU a che workspace maximal can use?

**Comment by sparkoo** [comment]
@anthonma 
 - there is `globalMemoryLimit` in `meta.yaml` https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/meta.yaml
 - then you can set `memoryLimit` on individual components https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#specifying-container-memory-limit-for-components (the docs should be fixed, you can set `memoryLimit` on `dockerimage` as well)
 - You can set in k8s or OpenShift components as specified by k8s https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
 - I don't think you can set CPU in `meta.yaml` or devfile.

**Comment by anthonma** [comment]
Thanks for your fast reply. I'll close this issue now.

**Comment by sleshchenko** [comment]
@anthonma From Che Admin perspective - there are properties to configure RAM that can be used by workspaces of one user https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties#L51
https://www.eclipse.org/che/docs/che-6/resource-management.html#configuring-workspaces-and-resources
