### ISSUE TITLE
Describe in a documentation current state and different usacases of usage name and generatedName in Devfile

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15020]
### Is your task related to a problem? Please describe.
There are some confusing https://github.com/eclipse/che/issues/14695 in the usage of  ```name``` and ```generatedName``` in Devfile. 

### Describe the solution you'd like
The goal of this task is to describe where we know in different use-cases (factory, workspace API). That could be a good starting point for the future improvement of these two concepts. 

### Describe alternatives you've considered
n/a
### Additional context
no docs about generatedName

**Comment by sparkoo** [comment]
there's just this field description in devfile spec https://redhat-developer.github.io/devfile/devfile#metadata

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che-docs/pull/892
