### ISSUE TITLE
Get rid of terminal workarounds in the "e2e" tests 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#15038]
### Is your enhancement related to a problem? Please describe.
Previously, the "Theia" had a terminal based on "canvas", it made interaction with the terminal impossible by selenium. That's why was implemented workarounds which were sending terminal output to the text file.
 This problem was described in the issue https://github.com/eclipse/che/issues/14772

### Describe the solution you'd like
The issue https://github.com/eclipse/che/issues/14772
was fixed by PR https://github.com/eclipse-theia/theia/pull/6471
It makes possible switching between the terminal render types. 

We should get rid of workarounds and interact with the terminal directly.

**Comment by Katka92** [comment]
The workaround for testing build command is still present. Instead of checking the terminal, output is written to te file and the file is checked. Affected methods are `Build application` and `Build application with changes`.
