### ISSUE TITLE
Welcome page when opening workspace becomes blank if "toggle maximized"

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15037]
### Describe the bug
blank page for welcome page when using "toggle maximized"

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Open workspace
2. Right-Click on "Eclipse Che" tab fo the welcome page then "toggle maximized" or double-click on the tab
3. See error

note that when setting back the window to normal size, it stays blank

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2019-10-30 16-30-11](https://user-images.githubusercontent.com/1105127/67872678-9c41b800-fb32-11e9-9e14-0fbeb934e958.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

in browser log
`root ERROR TypeError: Cannot read property 'contentWindow' of undefined`

**Comment by azatsarynnyy** [comment]
Closing it as can not reproduce on Hosted Che, 7.9.1.
Feel free to reopen if it is reproducible.
