### ISSUE TITLE
[Doc] Che7 - Che4z installation doc improvements

### ISSUE THREAD

**Issue by DStatWriter** [eclipse-che/che#15057]
This relates to the following page in the Che 7 docs:
https://www.eclipse.org/che/docs/che-7/che4z-installing/

The link previously/currently in place is:
https://projects.eclipse.org/projects/ecd.che.che4z/downloads

This led the user to click through to another page which held the download / install instructions. As we found many equivalent pages held the install instructions on the same page as we had placed the link, we agreed to streamline the process by relocating the installation instructions to the main page.

Pull request: eclipse/che-docs#884

Thanks,

Dan

**Comment by ibuziuk** [comment]
@DStatWriter hello, I saw the initial PR that was closed. Are you going to work on this issue?

**Comment by DStatWriter** [comment]
Hi @ibuziuk 

This was resolved by the following merged PR:

https://github.com/eclipse/che-docs/pull/895

Let me know if you believe that any issues remain, or have any other feedback.

Thanks,

Dan
