### ISSUE TITLE
Remove vscode marketplace support from plugin broker

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15054]
### Is your task related to a problem? Please describe.
The plugin broker allows plugins to specify `vsix` extensions directly from the vscode marketplace, via e.g.
```
extensions:
  - vscode:extension/ms-kubernetes-tools.vscode-kubernetes-tools
```

Since we 1) do not use this functionality currently, and 2) should not be pulling directly from the vscode marketplace for plugins, this functionality should be deprecated/removed.

The code for resolving these links and trying them ends up increasing the complexity in plugin broker, and it could be a lot simpler without it.

**Comment by ibuziuk** [comment]
We should take into account - https://github.com/eclipse/che/issues/15322

**Comment by amisevsk** [comment]
@ibuziuk #15322 is related but separate from this issue, as even if we remove `vscode:extension` support, direct links to the market place will still work. The fixes are different:
- For this issue, remove plugin broker logic to resolve `vscode:extension` references
- For #15322, the registry needs to be updated to not point at the marketplace; the broker doesn't care what the URL is as long as it spits out a vsix.

**Comment by amisevsk** [comment]
Refactor PR https://github.com/eclipse/che-plugin-broker/pull/80 includes this change.

**Comment by nickboldt** [comment]
Closing as this appears to have been done in Che 7.8 as part of the broker refactoring. \o/
