### ISSUE TITLE
Confusing message in default crud-php project in PHP with MySQL stack

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15051]
### Describe the bug
When default stack `PHP with MySQL` is started with a default project, the project is then built and web site is opened. If you put invalid parameters there, the messages that are shown are confusing.

### Che version
 - [x] latest - 7.3.1
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start `PHP with MySQL` stack with the default project.
2. Run Commands to get application running (Configure database, Configure Apache Web Server DocumentRoot, Start Apache Web Server).
3. Insert invalida value and click Submit:
![Screenshot from 2019-10-31 16-12-59](https://user-images.githubusercontent.com/29278800/67960081-05d8c980-fbfa-11e9-82de-cbc5209a9c59.png)
4. Confusing messages are shown:
![Screenshot from 2019-10-31 16-18-34](https://user-images.githubusercontent.com/29278800/67960187-2dc82d00-fbfa-11e9-8dc7-51d5ce8fd7cd.png)

### Expected behavior
The message saying that user was added is confusing. User was not added to database.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
`server:start --platform minikube -i eclipse/che-server:7.3.1 -t ${WORKSPACE}/deploy --k8spodreadytimeout=180000  --listr-renderer=verbose` where the ${WORKSPACE} is a path to Che with 7.3.1 tag checkouted.
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
It's a stupid "hello world", but that's not really a che bug. Closing.
