### ISSUE TITLE
[che-operator][chectl] Using versioned operator when starting server (e.g. 7.3.1) deploys nightly server

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#15056]
### Describe the bug
Deploying che using chectl like this `chectl server:start -a operator -p openshift --che-operator-image=quay.io/eclipse/che-operator:7.3.1` uses che-operator version 7.3.1, but all other components (server, registries, ...) are using nightly tag.

This is because chectl is using https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml for creating checluster CR and this checluster CR yaml contains hard coded nightly version (even in tagged released commits: https://github.com/eclipse/che-operator/blob/7.3.1/deploy/crds/org_v1_che_cr.yaml).

I would expect this "default" checluster CR yaml would have empty values in the places specifying versions - thus values from `defaults.go` will be used: https://github.com/eclipse/che-operator/blob/7.3.1/pkg/deploy/defaults.go (these are the correct versions for the particular release).

This would allow us easily and reproducibly start specific version of che by just specifying correct version of operator.

### Steps to reproduce

Run `chectl server:start -a operator -p openshift --che-operator-image=quay.io/eclipse/che-operator:7.3.1`
Expected - Che 7.3.1 is deployed
Actual - Che nightly is deployed

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
Not the case anymore.
All references to images are in `operator.yaml` [1] with the same tag.

[1] https://github.com/eclipse/che-operator/blob/master/deploy/operator.yaml
