### ISSUE TITLE
Cannot start workspaces with custom plugin registry

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#15055]
### Describe the bug

I can't start a workspace, if I use a custom Plugin registry. If I try to do so, I get this error:
````
Error: Failed to run the workspace: "Server 'theia' in container 'theia-ide4ig' not available."
````

I have done the following steps:
1. build and deploy the custom plugin registry
2. changed CHE_WORKSPACE_PLUGIN__REGISTR__URL in the configmap to the address of the custom plugin registry
3. restartet the che pod via kubectl scale command
4. tried to create and start a workspace
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.4.0

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
````
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
````
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl (chectl server:start -p minikube)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sparkoo** [comment]
What value you've set to `CHE_WORKSPACE_PLUGIN__REGISTR__URL` ? Does it end with `/v3` (e.g. `http://plugin-registry-che.192.168.39.91.nip.io/v3`).

**Comment by sparkoo** [comment]
do you use tls?

**Comment by anthonma** [comment]
@sparkoo I've set it to the address the command kubectl get ingres che-plugin-registry gives me and that is without /v3 at the end.
And I don't think I'm using tls. Can I see it anywhere if it is used?

**Comment by sparkoo** [comment]
try to set it in format I've wrote, `http://<ingress_host>/v3`.
You're probably not using tls, you would have to explicitly specify tls parameter to helm and you then you would see https in the browser.

**Comment by sparkoo** [comment]
I'm asking about tls because there might be an issue with certificate in communication with plugin registry. However, if you're not using it, this is definitely not cause of your problem.

**Comment by anthonma** [comment]
I've tried it now with ``http://<ingressDomain>/v3``, but I'm still getting the error.

**Comment by sparkoo** [comment]
Is registry url accessible when you put it into the browser? Do you see anything useful in che pod logs. Anythin useful in browser devconsole (f12) logs or network?

**Comment by anthonma** [comment]
The registry url is accessible via browser. The browser devconsole logs and network doesn't show something, which seems related to this issue. The only things it shows are related to keycloak and theat's because I run che in single-user I guess. The logs of the pod show this:
````
root WARN Failed to resolve module: @types/body-parser
root WARN Failed to resolve module: @types/bunyan
root WARN Failed to resolve module: @types/express
root WARN Failed to resolve module: @types/fs-extra
root WARN Failed to resolve module: @types/lodash.debounce
root WARN Failed to resolve module: @types/lodash.throttle
root WARN Failed to resolve module: @types/react
root WARN Failed to resolve module: @types/react-dom
root WARN Failed to resolve module: @types/react-virtualized
root WARN Failed to resolve module: @types/route-parser
root WARN Failed to resolve module: @types/ws
root WARN Failed to resolve module: @types/yargs
root WARN Failed to resolve module: font-awesome
root WARN Failed to resolve module: react
root WARN Failed to resolve module: react-dom
root WARN Failed to resolve module: react-virtualized
root WARN Failed to resolve module: @types/rimraf
root WARN Failed to resolve module: @types/tar-fs
root WARN Failed to resolve module: @types/touch
root WARN Failed to resolve module: @types/uuid
root WARN Failed to resolve module: @typefox/monaco-editor-core
root WARN Failed to resolve module: @types/base64-arraybuffer
root WARN Failed to resolve module: @theia/monaco
root WARN Failed to resolve module: @types/p-debounce
root WARN Failed to resolve module: @types/mime-types
root WARN Failed to resolve module: @types/diff
root WARN Failed to resolve module: @types/request
root WARN Failed to resolve module: @types/highlight.js
root WARN Failed to resolve module: @types/markdown-it
root WARN Failed to resolve module: @types/markdown-it-anchor
root INFO Theia app listening on http://0.0.0.0:3100.
root INFO unzipping the plug-in 'eclipse_che_ports_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_ports_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_containers_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_factory_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_ssh_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_ssh_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_welcome_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_welcome_plugin.theia
root INFO unzipping the plug-in 'task_plugin.theia' to directory: /tmp/theia-unpacked/task_plugin.theia
root INFO unzipping the plug-in 'theia_yeoman_plugin.theia' to directory: /tmp/theia-unpacked/theia_yeoman_plugin.theia
root INFO unzipping the VS Code extension 'vscode-git-1.3.0.1.vsix' to directory: /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix
````

**Comment by sparkoo** [comment]
anything useful in kube events `kubectl get events -n <che-namespace>` ?
How much memory do you use for your minikube?

**Comment by anthonma** [comment]
I don't know why, but I can start workspaces now. It starts with the default plugin registry and I can switch to my custom one without problems, but when I trie to install a plugin, I get this error when the workspace tries to restart:
````
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedScheduling', '0/1 nodes are available: 1 Insufficient memory.', 'workspace1nrb2bcd7yn2g812.maven-6c86bb5dc4-twjl9'"
````
I assume it is because of the minikube vm running out of RAM. I start minikube with 5GB RAM shouldn't this be enough?

**Comment by sparkoo** [comment]
Good it's working.
It's obviously not enough if it's failing on `Insufficient memory` :) I usually go with 6GB as a minimum for one workspace. Depends on the devfile though.
Can we close this issue?

**Comment by anthonma** [comment]
Thank you for your help. I'll close this issue now.
