### ISSUE TITLE
How to stop che in multi-user mode with chectl

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#15062]
## Summary
When I try to stop che via chectl server:stop in multi-user mode it demands a token.
It provides an link(https://www.eclipse.org/che/docs/che-6/authentication.html) on how to do this, but I don't quite understand it.

I assume I have to use that command:
````
curl
    --data "grant_type=password&client_id=<client_name>&username=<username>&password=<password>"
     http://<keyckloak_host>:5050/auth/realms/<realm_name>/protocol/openid-connect/token
````
But I don't now what I have to specify for ``<client_name>`` and for ``<realm_name>``

Please tell me what I have to fill in there, or if it is not the correct way to get a token, tell me how to do this.

**Comment by sleshchenko** [comment]
@anthonma Your assumption is pretty right. I have the following bash function to get access token
```bash
getCheAcessToken() {
  CHE_USER=xxxx
  CHE_PASSWORD=xxxx
  KEYCLOAK_HOSTNAME=keycloak-che.192.168.99.100.nip.io
  TOKEN_ENDPOINT="http://${KEYCLOAK_HOSTNAME}/auth/realms/che/protocol/openid-connect/token"

  echo "Retrieving 'admin' user's token from http://${KEYCLOAK_HOSTNAME}"
  export CHE_ACCESS_TOKEN=$(curl -sfSL --data "grant_type=password&client_id=che-public&username=${CHE_USER}&password=${CHE_PASSWORD}" ${TOKEN_ENDPOINT} | jq -r .access_token)
}
```

Hopefully, this issue will be solved by chectl and it will ask credentials and solve this exercise for you.

**Comment by anthonma** [comment]
I have managed to get a token via the command from my first post, but if I try to stop the server via chectl server:stop --access-token=token.txt I get an unauthorized error and when I try to pass the token directly to the command I get a input too long message.

**Comment by sleshchenko** [comment]
AFAIK `--access-token=token.txt` is should be token content but not file path, like `--access-token=sdjDMsjahdyaNasduyasdnkDYHs`

**Comment by anthonma** [comment]
@sleshchenko I've tried to do so but than I get input too long

**Comment by sleshchenko** [comment]
@anthonma Then you should be able to put it's to `CHE_ACCESS_TOKEN` env var before executing a command.

**Comment by anthonma** [comment]
@sleshchenko How do I set the env var. I tried it with the ``set`` command, but I get input too long as well. (I'm on windows 7)

**Comment by skabashnyuk** [comment]
```export CHE_ACCESS_TOKEN=dddd```

**Comment by anthonma** [comment]
The export command doesn't work, because I'm on windows.
I tried it with ``set`` in two ways: first I tried to copy the token and paste it to ``set [CHE_ACCESS_TOKEN=token`` but I get input too long. Secondly I tried ``set [CHE_ACCESS_TOKEN=curl ...]`` the ``set`` comand works, but when I try ``chectl server:stop`` I get E_AUTH_REQUIRED error.

Btw. the response of the curl command is something like: {"access_token":"...","token_type":"bearer",...} do I have to specify this complete block or only the string after "access_token" ?

**Comment by svkr2k** [comment]
> ```shell
> getCheAcessToken() {
>   CHE_USER=xxxx
>   CHE_PASSWORD=xxxx
>   KEYCLOAK_HOSTNAME=keycloak-che.192.168.99.100.nip.io
>   TOKEN_ENDPOINT="http://${KEYCLOAK_HOSTNAME}/auth/realms/che/protocol/openid-connect/token"
> 
>   echo "Retrieving 'admin' user's token from http://${KEYCLOAK_HOSTNAME}"
>   export CHE_ACCESS_TOKEN=$(curl -sfSL --data "grant_type=password&client_id=che-public&username=${CHE_USER}&password=${CHE_PASSWORD}" ${TOKEN_ENDPOINT} | jq -r .access_token)
> }
> ```

I used the above script with :
CHE_USER=admin
CHE_PASSWORD=admin
KEYCLOAK_HOSTNAME=keycloak-che.mydomain.com

Error shown was `curl: (22) The requested URL returned error: 400 Bad Request`
Please help.

**Comment by olberger** [comment]
@svkr2k I guess the http protocol in the TOKEN_ENDPOINT ought to be replaced by https ?

**Comment by tolusha** [comment]
We introduce `auth:login` commands to work with authentication not to provide `CHE_ACCESS_TOKEN` manually.
So:
- `chectl auth:login -u <user> -p <password>`
- `checlt server:stop`
