### ISSUE TITLE
Can't remove commands / update component aliases in devfile editor

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15066]
### Describe the bug
There's some strange behavior around commands in the devfile editor on the dashboard.

- Removing commands section from devfile does not prompt user to "save"
- Reloading devfile or making any other modifications after removing commands will cause commands to be reinserted into devfile
- Removing commands and updating a component's alias (that was referred to by a command) will cause saving to fail.

### Che version

 - [x] nightly

### Steps to reproduce
1. Create a workspace from the java-maven devfile
2. Delete `commands` section in devfile editor (note no option to save changes)
3. Update unrelated field in devfile (e.g. `name` or an env var), click save button
    - Commands are added back into devfile
4. Delete `commands` again, update `maven` alias (e.g. to `maven2`)
    - Saving fails with error `Failed
Command 'maven build' has action that refers to a component with unknown alias 'maven'`
    - Commands are reinserted into devfile.

### Expected behavior
I should be able to remove commands from a devfile.

### Runtime
   - [x] Openshift 3.11

**Comment by sleshchenko** [comment]
I guess it duplicates https://github.com/eclipse/che/issues/15036

**Comment by ibuziuk** [comment]
@mmorhun could you please confirm that this is a duplicate of  #15036

**Comment by amisevsk** [comment]
I think it does; closing in favor of #15036 

Sorry, I missed it in my search.

**Comment by tsmaeder** [comment]
Let's not work on this until we have the new editor in. Might be fixed.
