### ISSUE TITLE
Need to access Codenvy for Coding bootcamp work

### ISSUE THREAD

**Issue by jchurchwell2000** [eclipse-che/che#15068]
Hello, I

**Comment by jchurchwell2000** [comment]
I need to have access to Codenvy to work through projects in coding bootcamp but I cannot sign into Codenvy because I always go to Eclipse Che. I need rails and that is not there please help

**Comment by skryzhny** [comment]
codenvy.io scheduled for shutdown and has disabled self-registration.
Consider using new service based on actual Che 7: https://che.openshift.io
Sorry if messages on condenvy.io signup/login pages aren't clear enough.
