### ISSUE TITLE
Need to test the airgap deployment against OpenShift 4.2 restricted networks 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15079]
### Is your task related to a problem? Please describe.
Need to test the airgap deployment against OpenShift 4.2 restricted networks - https://docs.openshift.com/container-platform/4.2/operators/olm-restricted-networks.html

Documentation for airgap deployment - https://github.com/eclipse/che-docs/pull/868

Follow up email:

> Most operator container images use tags. Our documented process for mirroring operator images in a disconnected environment will only work for images that use digests and NOT tags.
> https://docs.openshift.com/container-platform/4.2/operators/olm-restricted-networks.html
> So, if your operator uses tag image references instead of digests (90% of all operators use tags in their container images) then they will not successfully mirror following our disconnected instructions.
> I don't yet know if this restriction will apply to the operand images as well. But I wouldn't be surprised if it does.

**Comment by nickboldt** [comment]
Aren't we making a distinction between "disconnected environment" (offline) and "restricted environment" (air gap) ?

The former is not supported in CRW 2 (yet). The latter should work (with some setup required, eg., prepulling container images to an internal registry).

**Comment by ibuziuk** [comment]
Done and demo is shown during the sprint review
