### ISSUE TITLE
[Doc] che7 - Che4z - Insert link to installer download

### ISSUE THREAD

**Issue by DStatWriter** [eclipse-che/che#15075]
Inserting link to installer download at step 4 of install process

**Comment by ibuziuk** [comment]
@DStatWriter could you provide a meaningful description? are you going to work on this issue?

**Comment by DStatWriter** [comment]
Hi @ibuziuk, i had thought the description wassufficient. I created this issue as part of the required step for the creation of the related Pull Request which does address this issue.

Can you perhaps provide me with an example of an "ideal" issue that i might use as a guideline for future issues?

Thanks,

Dan

**Comment by rkratky** [comment]
@DStatWriter, I suppose this has been fixed by https://github.com/eclipse/che-docs/pull/898/, right?
