### ISSUE TITLE
Stop Workspace settings documentation

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#15074]
## Summary
Is it possible to specify conditions for a workspace to stop automaticaly, like idle for some time or something like that?

**Comment by ibuziuk** [comment]
yeah, sure there is a `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT` env var that would gracefully terminate a workspace after a period of inactivity (no interactions with IDE)

@themr0c @rkratky do you happen to know if this is documented in the latest che 7 docs ?

- https://github.com/eclipse/che/issues/8951
-https://github.com/eclipse/che/blob/1c5c92147f7886ec4c7cd1a2348815d1198876d7/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties#L35-L36

**Comment by anthonma** [comment]
@ibuziuk How can I set ``CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT``

**Comment by ibuziuk** [comment]
@anthonma you should simply add this env var to `che` cm and rollout new deployment
