### ISSUE TITLE
Add Git-Repo to workspace

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#15076]
## Summary
Is it possible to add a second git repo to the workspace?

If I create a workspace via a stack, che pulls the sourcecode of the project defined with the stack. Now I want to add another git repo to push my changes to it. Is that possible?

**Comment by ibuziuk** [comment]
yeah, sure you can `git clone` by opening a terminal

**Comment by anthonma** [comment]
@ibuziuk I tried it, but I can't achive what I want.

I want to use a git repo as a template for projects. This repo is linked in the devfile used by a custom stack to create a workspace. After the workspace is created and some changes were made to the sourcecode I want to push it to another repo, so that the contents of the template repo are not changed. How can I achieve this?
