### ISSUE TITLE
[chectl] chectl didn't take into account '--domain' option with operator installer and custom resource yaml on minikube

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15072]
### Describe the bug
Chectl failed to install multiuser che on minikube 1.1.1 with `--domain` option used:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/1054/console
> chectl server:start --k8spodreadytimeout=180000 --installer=operator --listr-renderer=verbose --platform=minikube --che-operator-cr-yaml=org_v1_che_cr.yaml --domain=10.0.100.104.nip.io

### org_v1_che_cr.yaml
<details>
 <summary>Custom resource</summary>
 <pre>
#
#  Copyright (c) 2012-2019 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation

apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    # server image used in Che deployment
    cheImage: 'maxura/che-server'
    # tag of an image used in Che deployment
    cheImageTag: '15064'
    # image:tag used in Devfile registry deployment
    devfileRegistryImage: 'quay.io/eclipse/che-devfile-registry:nightly'
    # image:tag used in plugin registry deployment
    pluginRegistryImage: 'quay.io/eclipse/che-plugin-registry:nightly'
    # defaults to `che`. When set to `codeready`, CodeReady Workspaces is deployed
    # the difference is in images, labels, exec commands
    cheFlavor: ''
    # specifies a custom cluster role to user for the Che workspaces
    # Uses the default roles if left blank.
    cheWorkspaceClusterRole: ''
    # when set to true the operator will attempt to get a secret in OpenShift router namespace
    # to add it to Java trust store of Che server. Requires cluster-admin privileges for operator service account
    selfSignedCert: false
    # TLS mode for Che. Make sure you either have public cert, or set selfSignedCert to true
    tlsSupport: false
    # protocol+hostname of a proxy server. Automatically added as JAVA_OPTS and https(s)_proxy
    # to Che server and workspaces containers
    proxyURL: ''
    # port of a proxy server
    proxyPort: ''
    # username for a proxy server
    proxyUser: ''
    # password for a proxy user
    proxyPassword: ''
    # a list of non-proxy hosts. Use | as delimiter, eg localhost|my.host.com|123.42.12.32
    nonProxyHosts: ''
    # sets mem request for server deployment. Defaults to 512Mi
    serverMemoryRequest: ''
    # sets mem limit for server deployment. Defaults to 1Gi
    serverMemoryLimit: ''
  database:
    # when set to true, the operator skips deploying Postgres, and passes connection details of existing DB to Che server
    # otherwise a Postgres deployment is created
    externalDb: false
    # Postgres Database hostname that Che server uses to connect to. Defaults to postgres
    chePostgresHostName: ''
    # Postgres Database port that Che server uses to connect to. Defaults to 5432
    chePostgresPort: ''
    # Postgres user that Che server when making a db connection. Defaults to pgche
    chePostgresUser: ''
    # password of a postgres user. Auto-generated when left blank
    chePostgresPassword: ''
    # Postgres database name that Che server uses to connect to. Defaults to dbche
    chePostgresDb: ''
    # Postgres deployment in format image:tag. Defaults to registry.redhat.io/rhscl/postgresql-96-rhel7 (see pkg/deploy/defaults.go for latest tag)
    postgresImage: ''
  storage:
    # persistent volume claim strategy for Che server. Can be common (all workspaces PVCs in one volume),
    # per-workspace (one PVC per workspace for all declared volumes) and unique (one PVC per declared volume). Defaults to common
    pvcStrategy: 'per-workspace'
    # size of a persistent volume claim for workspaces. Defaults to 1Gi
    pvcClaimSize: '1Gi'
    # instruct Che server to launch a special pod to precreate a subpath in a PV
    preCreateSubPaths: true
    # image:tag for preCreateSubPaths jobs
    pvcJobsImage: ''
    # keep blank unless you need to use a non default storage class for Postgres PVC
    postgresPVCStorageClassName: ''
    # keep blank unless you need to use a non default storage class for workspace PVC(s)
    workspacePVCStorageClassName: ''

  auth:
    # instructs operator on whether or not to deploy Keycloak/RH SSO instance. When set to true provision connection details
    externalIdentityProvider: false
    # retrieved from respective route/ingress unless explicitly specified in CR (when ExternalKeycloak is true)
    identityProviderURL: ''
    # password for keycloak database user. Auto generated if left blank
    keycloakPostgresPassword: ''
    # desired admin username of Keycloak admin user (applicable only when externalIdentityProvider is false)
    identityProviderAdminUserName: ''
    # desired password of Keycloak admin user (applicable only when externalIdentityProvider is false)
    identityProviderPassword: 'admin'
    # name of a keycloak realm. This realm will be created, when externalIdentityProvider is true, otherwise passed to Che server
    identityProviderRealm: ''
    # id of a keycloak client. This client will be created, when externalIdentityProvider is false, otherwise passed to Che server
    identityProviderClientId: ''
    # instructs an Operator to enable OpenShift v3 identity provider in Keycloak,
    # as well as create respective oAuthClient and configure Che configMap accordingly
    openShiftoAuth: false
    # name of oAuthClient used in OpenShift v3 identity provider in Keycloak realm. Auto generated if left blank
    oAuthClientName: ''
    # secret used in oAuthClient. Auto generated if left blank
    oAuthSecret: ''
    # image:tag used in Keycloak deployment
    identityProviderImage: 'eclipse/che-keycloak:nightly'
  k8s:
    # your global ingress domain
    ingressDomain: '192.168.99.101.nip.io'
    # kubernetes.io/ingress.class, defaults to nginx
    ingressClass: ''
    # IngressStrategy is the way ingresses are created.
    # Can be multi-host (host is explicitly provided in ingress, <ingress-name>-<namespace>.<global-ingress-domain>),
    # single-host (host is provided, path based rules, <ingress-domain>/path) and default-host *(no host is provided, path based rules)
    ingressStrategy: ''
    # secret name used for tls termination
    tlsSecretName: ''
    # FSGroup the Che POD and Workspace pod containers should run in  
    securityContextFsGroup: '' 
    # User the Che POD and Workspace pod containers should run as  
    securityContextRunAsUser: '' 
 </pre>
</details>

### checluster
<details>
 <summary>checluster</summary>
 <pre>
apiVersion: v1
items:
- apiVersion: org.eclipse.che/v1
  kind: CheCluster
  metadata:
    creationTimestamp: "2019-11-04T01:04:24Z"
    generation: 15
    name: eclipse-che
    namespace: che
    resourceVersion: "957"
    selfLink: /apis/org.eclipse.che/v1/namespaces/che/checlusters/eclipse-che
    uid: 0a8cd444-fe9f-11e9-bc91-fa163e09d2e8
  spec:
    auth:
      externalIdentityProvider: false
      identityProviderAdminUserName: admin
      identityProviderClientId: che-public
      identityProviderImage: eclipse/che-keycloak:nightly
      identityProviderPassword: admin
      identityProviderPostgresPassword: E8K8YdkFwsow
      identityProviderRealm: che
      identityProviderURL: http://keycloak-che.192.168.99.101.nip.io
      openShiftoAuth: false
      updateAdminPassword: false
    database:
      chePostgresDb: dbche
      chePostgresHostName: postgres
      chePostgresPassword: RorohTeNhevy
      chePostgresPort: "5432"
      chePostgresUser: pgche
      externalDb: false
    k8s:
      ingressDomain: 192.168.99.101.nip.io
    server:
      cheDebug: "false"
      cheFlavor: che
      cheHost: che-che.192.168.99.101.nip.io
      cheImage: maxura/che-server
      cheImageTag: "15064"
      cheLogLevel: INFO
      devfileRegistryImage: quay.io/eclipse/che-devfile-registry:nightly
      externalDevfileRegistry: false
      externalPluginRegistry: false
      pluginRegistryImage: quay.io/eclipse/che-plugin-registry:nightly
      selfSignedCert: false
      tlsSupport: false
    storage:
      preCreateSubPaths: true
      pvcClaimSize: 1Gi
      pvcStrategy: per-workspace
  status:
    cheClusterRunning: Unavailable
    cheURL: ""
    cheVersion: ""
    dbProvisioned: true
    devfileRegistryURL: http://devfile-registry-che.192.168.99.101.nip.io
    keycloakProvisioned: true
    keycloakURL: ""
    openShiftoAuthProvisioned: false
    pluginRegistryURL: http://plugin-registry-che.192.168.99.101.nip.io/v3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
 </pre>
</details>

### Che operator log
[che-operator-6d4d9bb5d8-m8985.pod.log](https://github.com/eclipse/che/files/3802455/che-operator-6d4d9bb5d8-m8985.pod.log)

### Che server log
[che-7f698f6dff-2s7nr.pod.log](https://github.com/eclipse/che/files/3802453/che-7f698f6dff-2s7nr.pod.log)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

It works correctly on OpenShift infrastructure.

### Installation method
   - [x] chectl:next 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by tolusha** [comment]
When yaml file is specified then some other flags are ignored. It is done on purpose.
We added warning if unused flags were set.
