### ISSUE TITLE
No verification of socat presence for chectl server:start invocation

### ISSUE THREAD

**Issue by andrejusc** [eclipse-che/che#15070]
chectl version in use: 7.3.1
OS: Xubuntu 18.04.3 LTS with minikube

While invoking such command:
sudo chectl server:start --platform minikube

Part of output is such:
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed

and then such error:
      Preparing Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Che Helm Chart
Error: Command "helm init --service-account tiller --wait" timed out after 120000ms
stderr: E1102 23:06:23.657848   19672 portforward.go:400] an error occurred forwarding 35337 -> 44134: error forwarding port 44134 to pod 

b15110fa8b57a08c9f95cd814ae5773378d854bb83f70b29b68d81a02768cce1, uid : unable to do port forwarding: socat not found

Quick fix - install socat and repeat:
sudo apt install socat

Better fix - have/introduce better preflight check for Helm/Tiller part, so it could fail faster.

**Comment by ibuziuk** [comment]
@andrejusc thanks for reporting, will you be interested in contributing a fix

**Comment by andrejusc** [comment]
@ibuziuk - I could try to provide a fix if you could point me to some other verification check code to follow.

**Comment by tolusha** [comment]
It is interesting to know the helm version in question
