### ISSUE TITLE
Provide ability to select dedicated segment of Preview URL using mouse

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15077]
### Describe the bug
It's possible to select a dedicated segment of URL using **keyboard**, but whole URL is selected when user selects a dedicated segment of URL using **mouse**

### Che version
 latest

### Steps to reproduce

1. Start any workspace
2. Go to `F1 => Preview: Open URL`
3. Set any URL
4. Try to select dedicated segment of URL using mouse

### Expected behavior
User has opportunity to select a dedicated segment of URL using **mouse**

### Runtime
  minikube version: v1.0.0 
  
### Screenshots
please see https://youtu.be/8Z2dlflL9OY

### Installation method
chectl/0.0.2-5ab0061 linux-x64 node-v10.4.1

### Environment
   Linux

**Comment by azatsarynnyy** [comment]
labeled as `area/plugins` as related to https://github.com/eclipse/che-theia/tree/master/plugins/task-plugin
