### ISSUE TITLE
Devfile Registry resets to default

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#15081]
### Describe the bug

I have a custom devfileregistry, but when I change the configmap entry CHE_WORKSPACE_DEVFILE__REGISTRY__URL to the url of my custom registry it gets rested to default registry shortly after.
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.4.0

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
````
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
````
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl chectl server:start -p minikube -m
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@anthonma thanks for reporting the issue. Could you please clarify how exactly are you updating the registry? what is the value of env var `CHE_WORKSPACE_DEVFILE__REGISTRY__URL` inside the che pod?

**Comment by anthonma** [comment]
@ibuziuk I'm updating it via the command ``kubectl edit cm/che`` and afterwards I restart the che pod with ``kubectl scale --replicas=0 deployment/che`` and ``kubectl scale --replicas=1 deployment/che``.

How do I read the value of ``CHE_WORKSPACE_DEVFILE__REGISTRY__URL'' of the che pod?

**Comment by davidfestal** [comment]
@skabashnyuk why did you add `area/operator` ? According to description this is installed through `chectl server:start -p minikube -m` which doesn't seem to involve the operator afaik. Isn't the default installer for minikube the `helm` installer ? If that's the case, then the issue is more related to `chectl` or `helm charts` I suppose.

@l0rd @benoitf wdyt ?
