### ISSUE TITLE
Use top-level readme if available when opening workspace

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15080]
### Is your enhancement related to a problem? Please describe.

currently it is taking one readme that can be in subfolders.

### Describe the solution you'd like

Preference to take the top-level readme

### Additional context

when using Camel K examples subfolder from the stack in preparation https://github.com/eclipse/che/issues/14831 , it is opening https://github.com/apache/camel-k/blob/master/examples/tekton/README.md instead of top-level one of examples folder https://github.com/apache/camel-k/blob/master/examples/Readme.md

**Comment by benoitf** [comment]
I think it's because at the beginning VS Code API implementation of search was not implemented so had to use workarounds. (thus leading to invalid expected behaviour)

**Comment by apupier** [comment]
wondering also if it is because it is case sensitive for the readme file https://github.com/eclipse/che-theia/blob/846f13e2a139f24a2f9361cfefc084d8843efb37/plugins/welcome-plugin/src/welcome-plugin.ts#L59

**Comment by azatsarynnyy** [comment]
labeled as `area/plugins` as related to https://github.com/eclipse/che-theia/tree/master/plugins/welcome-plugin

**Comment by guydog28** [comment]
This is a problem for us.  Developers are taken to a README.md located in a sub folder that was the "pre-che" workspace set up and use instructions, instead of the new Che-based setup and use instructions at the ROOT, which is quite confusing.
