### ISSUE TITLE
Dashboard should use default icon for devfiles when actual icon is inaccessible

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15089]
### Is your enhancement related to a problem? Please describe.
Currently, when a dashboard's icon cannot be retrieved, the dashboard shows the 'image not found" thumbnail: 

![Screenshot from 2019-11-04 11-31-06](https://user-images.githubusercontent.com/16168279/68138490-aaa71f80-fef6-11e9-94e1-9e1533c0e7ed.png)

### Describe the solution you'd like
Che should have a fallback icon that is displayed when images cannot be found.

### Additional context
Useful for airgap/offline deployments, where images may not be available.

Related to: https://github.com/eclipse/che/issues/15090

**Comment by ibuziuk** [comment]
@evidolob could you please take this issue as a priority for the next sprint since it is CRW related ?

**Comment by amisevsk** [comment]
Also worth noting that if #15090 is implemented, this shouldn't be a problem for CRW. I think #15090 is easier to implement so it's not essential that this one gets done.

**Comment by benoitf** [comment]
What devfile registry in offline mode is providing links to online images ?

**Comment by evidolob** [comment]
Same question.

**Comment by amisevsk** [comment]
Because I missed that those icons were actually used anywhere (they're all the exact same link). Hence https://github.com/eclipse/che/issues/15090.
