### ISSUE TITLE
[Regression]Master build failing when pushing openshift connector plugin docker image

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15095]
### Describe the bug

```
Publishing image eclipse/che-remote-plugin-openshift-connector-0.1.1...
The push refers to repository [docker.io/eclipse/che-remote-plugin-openshift-connector-0.1.1]
96dd5aef2b7b: Preparing
7a6e272fedf8: Preparing
5eb9f892e9ff: Preparing
03901b4a2ea8: Preparing
denied: requested access to the resource is denied
```

introduced with this commit: https://github.com/eclipse/che-theia/commit/bcf1c25f5cf4619dda0bed114bb372336507b7da

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by apupier** [comment]
@vparfonov when I hit the same [kind of issue](https://github.com/eclipse/che-theia/pull/479) few weeks ago, Florent pinged you, so pinging you. hope you can help.

**Comment by azatsarynnyy** [comment]
Thanks @apupier for the issue! I'm trying to figure out what's the cause.

**Comment by azatsarynnyy** [comment]
@apupier `next` tag is on the dockerhub now
https://hub.docker.com/r/eclipse/che-remote-plugin-openshift-connector-0.1.1/tags

**Comment by apupier** [comment]
@azatsarynnyy have you figured out what is the cause? is it happening for all new dockerfiles?

**Comment by azatsarynnyy** [comment]
@apupier I believe @vparfonov knows the cause

**Comment by apupier** [comment]
seems to occur on each new Docker File.. https://github.com/eclipse/che/issues/15102
