### ISSUE TITLE
7.3.1 version uses obsolete version of the plugin-broker (v0.22 instead of v0.24) 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15099]
### Describe the bug
7.3.1 version uses obsolete version of the plugin-broker (v0.22 instead of v0.24) which results in the following bugs:
- https://github.com/eclipse/che/pull/14969
- The ? maven issue is caused by using plugin broker v0.22 instead of v0.24; v0.22 overrides container command so the entrypoint script that sets user does not run

### Che version
- 7.3.1

### Expected behavior
latest `v0.24` plugin broker is used by default

**Comment by dmytro-ndp** [comment]
@ibuziuk: there is plugin broker of v.0.24 in 7.4.0 RC: https://github.com/eclipse/che/blob/7.4.x/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L482-L483

**Comment by ibuziuk** [comment]
@AndrienkoAleksandr I guess PR https://github.com/eclipse/che/pull/15178 fixes this issue

**Comment by AndrienkoAleksandr** [comment]
> @AndrienkoAleksandr I guess PR #15178 fixes this issue

Yes, I referenced issue.

**Comment by ibuziuk** [comment]
PR merged. Closing
