### ISSUE TITLE
Redundant dialog appears on git repository related commands

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#15097]
### Describe the bug

When having several git repositories in the workspace and executing any git command related to repository e.g. `git commit` from the SCM panel a redundant dialog appears and asks to select a repository. We don't need this dialog because SCM knows selected repository and it should be passed to the command.
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace with several git repositories.
2. Got to the SCM panel and click the `...` button and click `stash`:
![screenshot-che-che 192 168 39 28 nip io-2019 11 05-16_36_33](https://user-images.githubusercontent.com/7668752/68217140-c390fd00-ffea-11e9-92bf-2220dbd06020.png)
**WRONG** A dialog with select repository appears: 
![screenshot-che-che 192 168 39 28 nip io-2019 11 05-16_39_25](https://user-images.githubusercontent.com/7668752/68217262-fe933080-ffea-11e9-9257-41d407f8b8b4.png)

### Expected behavior

The stash command must fetch the selected repository automatically.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by evidolob** [comment]
@vinokurig Can you verify that upstream Theia behaves as you expected? And it's a bug in che-theia.

**Comment by vinokurig** [comment]
@evidolob Upstream Theia uses it's own git extension but Che-theia uses built-in vscode git extension. If I disable the native Theia git extension and add the vscode-git-extension it behaves the same. The problem is in the upstream Theia, but I think this issue is relevant to che-theia because it can be reproduced there.

**Comment by evidolob** [comment]
But fix should be done in upstream? Or in che-theia?

**Comment by vinokurig** [comment]
> But fix should be done in upstream? Or in che-theia?

The fix should be done in Theia.
> And maybe this issue for IDE1 team ?

I also think so.
