### ISSUE TITLE
Not able to see my workspace after 30 workspaces

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15098]
### Describe the bug
I often delete previous workspaces but when I've more than 30 workspaces I can no longer see my running workspace.
The workspace is running but it is not displayed in dashboard short list and dashboard only list 30 workspaces (not more)
calling `/api/workspace` also list only 30 workspaces (`pagination`)

with direct link I can open my workspace but not good :-)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Create more than 30 workspaces
Use a factory to create & open a workspace for example
if you go in dashboard you don't see it running.

### Expected behavior
My current running workspace should always be available in the left column
also it should be listed when I go to 'all workspaces' screen

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify) che.openshift.io

### Screenshots
![che-workspace-30-limit](https://user-images.githubusercontent.com/436777/68217367-c4259580-ffe2-11e9-9937-db30dbdf02df.gif)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: che.openshift.io

**Comment by benoitf** [comment]
related to https://github.com/eclipse/che/issues/9752

**Comment by jswordfish** [comment]
@benoitf Think I face the same issue as yours but with a difference - I can't even open my workspace (beyond 30) where as u said u can open with a direct link.

Can u please specify the format of the direct link you use?

**Comment by skabashnyuk** [comment]
@jswordfish 
>Can u please specify the format of the direct link you use?

It should be like this : `https://{domain}/{namespace aka username}/{workspace name}`

**Comment by skabashnyuk** [comment]
@jswordfish with sadness I have to admit that direct link is not working at this moment https://github.com/eclipse/che/issues/15733

**Comment by benoitf** [comment]
@jswordfish I was doing the following, grab link in left column of dashboard with the existing workspaces

then replace from this link workspace name by the expected workspace name that you want to open

Another way is to cleanup for example old workspaces to have less than 30 total workspaces

**Comment by sleshchenko** [comment]
It should be fixed by https://github.com/eclipse/che/pull/15784.
Feel free to reopen if it's still actual
