### ISSUE TITLE
Support for "--tls" flag for helm install/update

### ISSUE THREAD

**Issue by denis111** [eclipse-che/che#15096]
### Is your enhancement related to a problem? Please describe.
Can't install Che via chectl with already installed helm in tls mode https://helm.sh/docs/using_helm/#enabling-tls

### Describe the solution you'd like
Provide the option to chectl to add "--tls" flag to helm install/update commands

### Describe alternatives you've considered
Copy-paste helm command after chectl server:start failure.

**Comment by l0rd** [comment]
Hi @denis111 

You would like that when `chectl server:start` is invoked with option `--tls` we then:
- [ ] Add option `--tiller-tls-verify` to  the command `helm init` that creates the Tiller service
- [ ] Add option `-tls` to any consequent `helm` command like `helm upgrade` and `helm dependencies update` 

Is that correct?

**Comment by denis111** [comment]
Yes but not exactly. I think current chectl's --tls option has nothing to do with helm's --tls option, maybe it should be another flag for chectl like --helm-tls

**Comment by FessAectan** [comment]
Hi there!
Any updates?
