### ISSUE TITLE
Support installing che in default namespace, or gracefully prevent it

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#15092]
### Is your enhancement related to a problem? Please describe.

Related to the discussion around https://github.com/eclipse/che/issues/14426, it would be nice if the Che operator could:

- Install che properly in the `default` namespace
- gracefully indicate that it cannot install in that namespace, suggest another namespace to install, or move the installation to another namespace automatically

### Describe the solution you'd like

Be able to install che properly in the `default` namespace every time without depending on different PVC volume permissions, security context settings, etc.

+ Set the security context information (specifically `fsGroup` and `runAsUser` if we are deploying to OpenShift in the `default` namespace

**Comment by sroe007** [comment]
Hi....while I see this ticket has been closed by the bot.....the behaviour is as originally described in #14426 - so I am just at this point wondering if there had bee a resolution I missed out on....

The behaviour is exactly as described in the abovementioned ticket - I am using OKD 4.5 and the Eclipse-Che Community Operator 7.28.0-128.nightly. The environment runs on aws. 

The installation of the operator as well as configuration of the PVCs/PVs appears good 
<img width="1113" alt="Screenshot 2021-03-25 at 12 53 41" src="https://user-images.githubusercontent.com/57169144/112474602-23b74900-8d70-11eb-98d4-4b6975936553.png">
<img width="1648" alt="Screenshot 2021-03-25 at 13 02 19" src="https://user-images.githubusercontent.com/57169144/112474679-3893dc80-8d70-11eb-95d4-00ba8b8c7eda.png">

 Any suggestions or has a solution been found in the meantime?
