### ISSUE TITLE
Run E2E Happy path nightly with "ephemeral workspaces" 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15101]
### Is your task related to a problem? Please describe.
Right now, Happy Path tests are running only with "normal" workspaces. We need to crete suite to run Happy Path tests also with ephemeral workspaces (workspaces which doesn't need persistent storage), as this is one of the main usecase in hosted Che.

### Related issues
https://github.com/eclipse/che/issues/14749

**Comment by rhopp** [comment]
This could be implemented either by using different devfile, which would have ephemeral workspace enabled by default. 
Or we could do it through dashboard UI.

**Comment by Katka92** [comment]
We are running devfile tests nightly (for now with persistent volume). Maybe we can incorporate this into those tests - it should be really easy as we are already using the dashboard `Get Started` page where the toggle is present.
Another benefit of adding that to the nightly devfile test suite is that we don't have to create new job/suite that will need extra maintenance.
