### ISSUE TITLE
Move out all non theia images from che-theia repository

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15109]
### Is your task related to a problem? Please describe.

Today, che-theia repository contains lot of images definition.
Historically it was because all plug-ins runtime need to had the endpoint-image as parent image (or to have it by composition)
But now, as we're using endpoint dynamically added, we no longer need to have this inheritance

### Describe the solution you'd like
Move all images to separate repositories. So each image can have its own lifecycle.
For example instead of having
`remote-plugin-openshift-connector-0.0.21` `remote-plugin-openshift-connector-0.0.22` etc folders
we can have `che-remote-plugin-openshift-connector` repository with 0.0.21 tag
So if there is a change needed we just modify current image and add a new tag

This will drastically reduce the time of CI to check PR on che-theia repository and then, avoid to rebuild images that are not changing at all

### Describe alternatives you've considered
None

**Comment by evidolob** [comment]
I can remove all non theia images from che-theia during #14849 
But who will be responsible for creating of separate repositories and lifecycle (CI, releases)?
I assuming that it should be authors/maintainers. @tsmaeder WDYT?

**Comment by benoitf** [comment]
I will work on it

**Comment by tsmaeder** [comment]
I think this is a good idea, but where would they go instead and are the dockerfiles and build scripts referenced anywhere, for example when building CRW?

**Comment by benoitf** [comment]
done
