### ISSUE TITLE
Welcome page logo appears very big for a short time

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15100]
### Describe the bug
When opening a workspace, welcome page displays Eclipse Che logo

It is being displayed for a couple of seconds in a very big layout/format before stretching it down

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Open a workspace and see logo

### Expected behavior
Logo shouldn't shrink

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: che.openshift.io

### Screenshots
![big-logo](https://user-images.githubusercontent.com/436777/68222681-ac064400-ffeb-11e9-99b9-aaeff625d09e.gif)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: che.openshift.io

**Comment by vitaliy-guliy** [comment]
Connected with https://github.com/eclipse/che/issues/15197
