### ISSUE TITLE
Enable "Copy on Selection" for terminal

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15106]
### Is your enhancement related to a problem? 

Modern shells automatically copy to the clipboard selected text. That allows to copy some text quickly. VS Code provide this option for example.

### Describe the solution you'd like

Add a preference to "Copy on Selection" for the terminal as in VS Code:

![image](https://user-images.githubusercontent.com/606959/68244651-8ee66b00-0015-11ea-80a4-6feea432ac25.png)

"Copy on Selection" should be enabled by default.

**Comment by AndrienkoAleksandr** [comment]
I create pr for theia, but under firefox copy on selection doesn't work. Seems an issue: https://bugs.webkit.org/show_bug.cgi?id=156529
