### ISSUE TITLE
Release 7.4.0

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#15111]
- [x] che-theia @evidolob `eclipse/che-theia:7.4.0`
- [x] che-machine-exec @ibuziuk `quay.io/eclipse/che-machine-exec:7.4.0`
  - [x] https://github.com/eclipse/che-machine-exec/pull/52
  - [x] version bump in master https://github.com/eclipse/che-machine-exec/pull/53
- [x] che-plugin-registry @ibuziuk `quay.io/eclipse/che-plugin-registry:7.4.0`
   - [x] https://github.com/eclipse/che-plugin-registry/pull/287
   - [x] version bump in master https://github.com/eclipse/che-plugin-registry/pull/288
- [x] che-devfile-registry @ibuziuk `quay.io/eclipse/che-devfile-registry:7.4.0`
   - [x] https://github.com/eclipse/che-devfile-registry/pull/138
   - [x] version bump in master https://github.com/eclipse/che-devfile-registry/pull/139
- [x] che @vparfonov 
   - [x] che-parent
   - [x] che-docs 
   - [x] che 
- [x] che-operator @davidfestal
   - https://github.com/operator-framework/community-operators/pull/859
   - https://github.com/operator-framework/community-operators/pull/862
- [x] chectl @l0rd

**Comment by evidolob** [comment]
We need https://github.com/eclipse/che/pull/15112 merged in che to be able to build dashboard for 7.4.0

**Comment by ibuziuk** [comment]
I believe we can close this one
