### ISSUE TITLE
Support `endpoints` for components of type chePlugin

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15126]
### Is your task related to a problem? Please describe.
No support for `endpoints` on the `chePlugin`/`cheEditor` components makes it impossible to expose a port defined in the component.

### Describe the solution you'd like
This is very similar to #15124 and ideally we should consider reusing the code that applies the endpoint to the kubernetes environment.

**Comment by sparkoo** [comment]
fixed by #16669
