### ISSUE TITLE
Support `volumes` for components of type kubernetes/openshift

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15122]
### Is your task related to a problem? Please describe.
To be able to share storage between different components of the devfile, it would be beneficial to be able to specify `volumes` on the `kubernetes`/`openshift` components the same way it is possible on the `dockerimage` components.

### Describe alternatives you've considered
There are two possible solutions how to apply volumes:
1. Apply the volumes to all containers (matching the selector of the component). This might be dangerous because we might overwrite files that we don't want to in certain containers.
1. Use the same mechanism as for `entrypoints` of k8s/openshift components, e.g. have a `parentSelector` + `containerName` on the volume to limit where the volume should be applied on potentially per-container basis.

**Comment by mshaposhnik** [comment]
So there might be not very user-friendly message when volume defined in devfile matches any of the volumes defined in K8S/OS recipe (see below). So we cah either break workspace startup with more meaningful message, or just merge equal volumes to avoid messages at all. @metlos @l0rd WDYT?
![volume_duplicate](https://user-images.githubusercontent.com/1651062/78003697-c1d12880-7341-11ea-9d6b-f7b4c32d98b1.png)

**Comment by mshaposhnik** [comment]
So as for me, adding volume into devfile is an easy way to add volume into all containers without editing original recipe (when it's big or inaccessible for edit), so it looks logical just to add volume into all containers which did not containing it, and simply ignoring the ones which are already do contain.
