### ISSUE TITLE
Pass variable argument to docker run

### ISSUE THREAD

**Issue by echyam** [eclipse-che/che#15139]
## Summary
When a user starts a new workspace, I want to pass user-specific arguments to the `docker run` command.

## Relevant information
Example: 
I have a folder `/userfiles` I use to keep persistent files across workspaces.  I can mount `/userfiles` using the `CHE_WORKSPACE_VOLUME` variable in `che/dockerfiles/init/manifests/che.env`.

However, I want each user's data to be separated within `/userfiles`, so I give them subfolders: `/userfiles/user1`, `/userfiles/user2`, etc...  
How do I only mount `/userfiles/user1` for `user1`'s workspaces and not the whole `/userfiles` folder?  

Che should be aware of who the user is, so is it possible to have Che do something like this?
`docker run ${image} --mount source=/userfiles/${che_user},target=/home/${user}`

**Comment by tolusha** [comment]
@echyam 
Could you specify the Che version you are talking about?

**Comment by echyam** [comment]
We're using Che version 6.19.0

**Comment by rof20004** [comment]
@echyam Did you tried?

`
CHE_WORKSPACE_VOLUME=/userfiles/user1
`

**Comment by echyam** [comment]
@rof20004  That works for mounting `/userfiles/user1` for every workspace, but what I am looking for is 
`/userfiles/user1` in user1's workspace, and 
`/userfiles/user2` in user2's workspace. 

I don't want to mount `/userfiles/user1` for user2. Instead, I am looking for a way to substitute a username variable in the mount command.

**Comment by echyam** [comment]
Theoretically, Che should know the user who is launching the workspace, so it should be able to substitute that as a variable into the docker run command. Should I assume this isn't possible yet?

**Comment by tolusha** [comment]
Che 6.x is not supported anymore
