### ISSUE TITLE
Workspace Snapshots

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#15132]
## Summary
Could you please explain to me, what workspace snapshots are and how to use it?
I can't find any information about it in the che docs.

**Comment by benoitf** [comment]
Hello,

at some point in old eclipse Che versions, workspace was being able to be snapshotted : ie the state of the container was persisted

but it was not making possible the ability to share easily and to replicate the workspaces, thus it is no longer available

**Comment by anthonma** [comment]
Thank you for your quick response.
