### ISSUE TITLE
Bug during CRW update from 1.2 to 2.0 with registry URL 

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15133]
### Describe the problem

When upgrading from CRW 1.2 to 2.0, we encouter a new problem with the old 1.2 custom resource containing obsolete field values that make the update fail. It's the `PluginRegistryUrl` which was by default set at `www.openshift.io`.

We have to decide if we also manage by documenting an additional manual upgrade step, or simply fix that in the operator code (on the upcoming `crw-2.0 branch`), specifically in the case of an upgrade from 1.2 to 2.0 `cheImageTag` with the `codeready flavor`.
That would also allow resetting the dockerimages to empty string, which would finally provide a smooth upgrade path without any required manual fix of the custom resource..

**Comment by ibuziuk** [comment]
@davidfestal what is out current plan with this issue? I suppose it would be docs update, right?

**Comment by davidfestal** [comment]
Oh, I fixed it last week. I assumed I linked the PR to the Jira issue, but missed this issue.
I think it was https://github.com/eclipse/che-operator/pull/120
