### ISSUE TITLE
CheCtl start should *not* fix the docker images in the CR by default

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15131]
### Describe the bug

Currently, when using the `operator` installer, `chectl server:start` overrides the docker images of the identity provider, and registries in the Custor Resource yaml, *in all cases*.
It should not do it when no `cheImage` argument is provided (but instead reste docker images to empty string.

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

**Comment by tomgeorge** [comment]
@davidfestal is this OK to be closed?

**Comment by davidfestal** [comment]
I think so
