### ISSUE TITLE
Not able to run task in che-theia

### ISSUE THREAD

**Issue by aaqaishtyaq** [eclipse-che/che#15146]
### Describe the bug
 
Running che task from `Terminal` -> `Run Task` gives this error and failed to execute task.
```
Error launching task '<TASK>': Request run failed with message: Can't run a task when 'cwd' is not provided by the client
```
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: `7.3.0`

### Runtime
   - [ ] kubernetes (`v1.16.0`) 
   - [ ] Openshift 
   - [ ] minikube 
   - [ ] minishift 
   - [x] docker-desktop + K8S (Docker: `19.03.4` and kubectl: `v1.14.7` )
   - [ ] other: (please specify)

### Screenshots

![Screenshot 2019-11-08 at 1 46 45 AM](https://user-images.githubusercontent.com/22131756/68424950-11645b80-01cb-11ea-876c-70d823c56247.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

Here is the output from console log 
```
task ERROR Error launching task 'build ... factory-plugin': Request run failed with message: Can't run a task when 'cwd' is not provided by the client
```

Theia version -> `0.12.0`
Che-Theia -> `next`

**Comment by RomanNikitenko** [comment]
@aaqaishtyaq 
Hello!
What I can see from the screenshot, that task-plugin is not installed: `Previews` item is absent on your screenshot

![task_plugin](https://user-images.githubusercontent.com/5676062/68458168-c9fdbf80-020a-11ea-8db2-d228851e9eca.png)

The [error](https://github.com/eclipse-theia/theia/blob/65ffea53952a98b72ecfacce6daba239ea7e1eeb/packages/task/src/node/process/process-task-runner.ts#L137 ) message tells me the same: default  `theia` runner, not `che` runner is used for running tasks. 

Could you check your logs for `theia-ide `to be sure that your workspace started properly and plugins was installed
![logs](https://user-images.githubusercontent.com/5676062/68458844-68d6eb80-020c-11ea-9690-839e8a9c47d9.png)
