### ISSUE TITLE
Avoid breaking master on each new dockerfile added in che-theia

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15150]
### Is your task related to a problem? Please describe.
Each time a new Dockerfile is added, the master is then broken

### Describe the solution you'd like
- not broke the master

### Describe alternatives you've considered
as a first iteration, knowing what to do in this case would be useful

### Additional context

see https://github.com/eclipse/che/issues/15095 and https://github.com/eclipse/che-theia/pull/479 and https://github.com/eclipse/che/issues/15102

**Comment by tolusha** [comment]
/cc @vparfonov 
Could you explain what to do in this case?

**Comment by vparfonov** [comment]
we just need to create new repository on dockerhub before add new dockerfile

**Comment by apupier** [comment]
Who has rights to do so? All Eclipse Che committers?

**Comment by azatsarynnyy** [comment]
closing it as all dockerfiles for the plugins sidecars are moved to https://github.com/che-dockerfiles and not affect che-theia build anymore
