### ISSUE TITLE
Can not create a  new terminal

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15153]
### Describe the bug
Can not create new terminal
Please see video from `screenshots` section

### Che version
`theia`:  [2f3b2c353931c0040bd6a662c2c57d4cfb86f92c](https://github.com/eclipse-theia/theia/commit/2f3b2c353931c0040bd6a662c2c57d4cfb86f92c)
`che-theia`: [dd0f1b6ac38b75f3af29eb057600c28064d7a3b0](https://github.com/eclipse/che-theia/commit/dd0f1b6ac38b75f3af29eb057600c28064d7a3b0)

### Steps to reproduce
1. Start any workspace using defined above versions
2. `Terminal => Open terminal in specific container` or hotkey ctrl+`
3. Try to use the terminal
You can see that terminal widget is open, but it's broken 

### Expected behavior
Terminal works correctly

### Runtime
  minikube version: v1.0.0 

### Screenshots
Please see https://youtu.be/DePgkypUDtU

![terminal_error](https://user-images.githubusercontent.com/5676062/68480398-5d4fe880-023d-11ea-8308-ca87f2ba360a.png)

### Installation method
chectl/0.0.2-5ab0061 linux-x64 node-v10.4.1

### Environment
   Linux

**Comment by mmorhun** [comment]
Fixed
