### ISSUE TITLE
Helm chart: workspaces fail to start in the default <username>-che namespace

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15159]
### Describe the bug
Workspaces fail to start in the default <username>-che namespace.
It happens because of workspace SA lack:
```
Press F5 or click here to try again.
Error: Failed to run the workspace: "Failure executing: POST at:
 https://10.96.0.1/api/v1/namespaces/che/pods. Message: Forbidden!
Configured service account doesn't have access. Service account 
may have been revoked. pods "workspace0ku4mf5927nduu9z.che-plugin-broker"
 is forbidden: error looking up service account che/che-workspace: 
serviceaccount "che-workspace" not found. The error may be 
caused by an expired token or changed password. 
Update Che server deployment with a new token or password."
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che with the following command:
```
helm upgrade --install che --force --namespace che --set global.ingressDomain=$(minikube ip).nip.io --set cheImage=eclipse/che-server:nightly .
```
2. Try to start any workspace.

### Expected behavior
The workspace is started.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2019-11-11 10-50-54](https://user-images.githubusercontent.com/5887312/68575293-6b3b7e80-0474-11ea-9330-fc411f60b917.png)

### Installation method
   - [ ] chectl 
   - [x] helm
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
@sleshchenko 
Is it `helm` specific problem?

**Comment by sleshchenko** [comment]
@tolusha I hope so. Some changes may be needed on Che Server side and it may affect other installation methods.

**Comment by tolusha** [comment]
It works for `checlt`

**Comment by sleshchenko** [comment]
@tolusha Could you clarify arguments you used with chectl?

**Comment by tolusha** [comment]
`chectl server:start --platform=minikube  --installer=operator --k8spodreadytimeout=500000
`

**Comment by metlos** [comment]
We have a theory that this happens only after `helm upgrade` from some yet to be identified older version of Che. Investigation is still in progress.

The reason for that theory is that once you `helm delete --purge` the che installation and re-install it, the problem disappears.
