### ISSUE TITLE
The `token-exchange` setup during Keycloak configuration fails on CRW 

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15152]
### Describe the bug

When OpenShift OAuth is enabled in the `CheCluster` custom resource, some configuration steps (which use the `jq` utility) are run by the operator in the Keycloak / RHSSO POD in order to enable the token-exchange feature.
However this step fails in the CRW case, since the underlying image in the official RHSSO one, instead of the dedicated `che-keycloak` one.
And the RHSSO docker image doesn't have `jq` installed

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Deploy CRW with a `CheCluster` custom resource with openshift oauth enabled.
You should see errors regularly coming in the operator logs about a missing jq utility when trying to setup the keycloak `token-exchange` feature.

### Expected behavior

It should work out-of-the-box

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by davidfestal** [comment]
NB this bug impact CRW, and probably the CRW 2.0 release as well.

**Comment by tolusha** [comment]
@nickboldt 
How important this issue is for you?

**Comment by davidfestal** [comment]
@tolusha not sure we should wait for @nickboldt return before prioritizing this issue and probably put it as a blocker for CRW 2.0 release.

This mainly triggers a non-blocking but still endless loop in the che operator in order to try applying this step that can only fail. I think this can only bring problems and lower overall robustness of the operator.
@l0rd wdyt ?

**Comment by davidfestal** [comment]
In the absence of @nickboldt , could you please given you feeling about the priority of this issue @dmytro-ndp and @rhopp ?

In fact maybe I should have created a JIRA issue since it's a downstream-only issue ?

**Comment by davidfestal** [comment]
Changing to blocker since it had been added by @l0rd into 7.3.2 tasks.
Anyway it's fixed already on the operator `crw-2.0` branch.

**Comment by davidfestal** [comment]
Closing since it was fixed by PR https://github.com/eclipse/che-operator/pull/122, (also cherry picked on `master`) whose squashed commit will be present on the 7.3.2 upcoming release.
