### ISSUE TITLE
Chectl Windows Build should not use tar.gz

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15163]
The distribution of chectl is compressed as a .tar.gz file. Windows cannot handle this without installing additional software. We should use a .zip file instead.

**Comment by tolusha** [comment]
Why do you think that additional software is a problem?

**Comment by tsmaeder** [comment]
Because it's extra work for the user. Let's be nice to our users.

**Comment by benoitf** [comment]
AFAIK there is a windows install script for Windows users so you shouldn't even see a tgz

**Comment by benoitf** [comment]
https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/#installing-the-chectl-management-tool-on-windows_installing-the-chectl-management-tool

**Comment by tsmaeder** [comment]
> AFAIK there is a windows install script for Windows users so you shouldn't even see a tgz

Yes, but a couple of lines further down, we're pointing to "manual install". I'm not saying this is a huge problem we need to run and fix, but for Windows users, zip would be more convenient.

**Comment by benoitf** [comment]
yes I kind of disagree. think that tgz is an internal format.

Windows users are using mostly .exe or install commands so I'm unsure providing .zip would be better.

We could provide .exe installers as oclif may generate them

**Comment by nickboldt** [comment]
Almost 2 years old and no love here from prod or deploy team. @tsmaeder looks like if you want this you'll have to contribute the fix yourself. Code in anger! 

Otherwise, closing.

**Comment by tsmaeder** [comment]
@nickboldt in my copious free time :-)
