### ISSUE TITLE
Che monitoring installation fails on k8s version 1.16

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15168]
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.3.0
### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
           kubectl 1.16.2
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/29850624/68648963-f5fba680-0564-11ea-8105-0fa80a8c5abe.png)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
   - [x] helm

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

When I set the metricsEnabled value I get an apiVersion error.

**Comment by kellyhyomin** [comment]
@skabashnyuk 

I solved this issue.
I have updated the prometheus and grafana chart versions as shown in the screenshot below to use grafana and prometheus in kubernetes 1.16.2.

deploy/kubernetes/helm/che/requirements.yaml
prometheus version ^7.4.5 to ^9.3.1
![image](https://user-images.githubusercontent.com/29850624/69118301-47acaf80-0ad6-11ea-85e1-fbfdc33664eb.png)
grafana version ^1.19.0 to ^4.0.3
![image](https://user-images.githubusercontent.com/29850624/69118309-51361780-0ad6-11ea-9231-e25fc3d1eb56.png)

Probably related to this issue -> https://github.com/helm/charts/issues/17267

**Comment by skabashnyuk** [comment]
@kellyhyomin thank you for this report. Can you offer a pr?

**Comment by kellyhyomin** [comment]
@skabashnyuk  yes i'll.

**Comment by skabashnyuk** [comment]
@kellyhyomin can we close this issue?

**Comment by kellyhyomin** [comment]
@skabashnyuk  okay!
