### ISSUE TITLE
git fetch --help does not work in self-hosting

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15161]
When doing 'git fetch --help' in the theia-dev container following che-theia/Contributing.md, I get an error:
```
git fetch --help
warning: failed to exec 'man': No such file or directory
fatal: no man viewer handled the request
```

I would expect help to work for installed commands.

**Comment by tsmaeder** [comment]
This might be trivial for developers running on linux, but if you work on Windows, it's a PITA.

**Comment by tsmaeder** [comment]
This is on che.openshift.io

**Comment by tolusha** [comment]
@tsmaeder 
Where did you find 'git fetch --help' ?
https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md

**Comment by tolusha** [comment]
BTW there is no `man` in the theia-dev container

**Comment by tsmaeder** [comment]
@tolusha  It's not in contributing.md, but git is broken ("--help" does not work). If that is because man is not installed, we need to have man on this container.

**Comment by benoitf** [comment]
it's far better with man installed ^^

```
docker run --rm -it --entrypoint=sh eclipse/che-theia-dev:next
# git fetch --help
warning: failed to exec 'man': No such file or directory
fatal: no man viewer handled the request
# apk add man
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/2) Installing mdocml (1.14.3-r0)
(2/2) Installing man (1.14.3-r0)
Executing busybox-1.29.3-r10.trigger
OK: 241 MiB in 74 packages
/projects # git fetch --help
man: No entry for git-fetch in the manual.

```

well just kidding we need as well `git-doc` package

**Comment by tsmaeder** [comment]
While we're at it, can we get the auto-complete for git branches working? That would be awesome.

**Comment by benoitf** [comment]
@tsmaeder please file another issue
