### ISSUE TITLE
Codenvy beta installs the entire OS after container stopped, causing huge startup delays

### ISSUE THREAD

**Issue by mpouttuclarke** [eclipse-che/che#1516]
It is taking 10+ minutes to start an existing workspace on the Codenvy Beta while it only takes a couple of seconds to start Che on a local machine after first install.  This is unacceptable as Che should have better performance on a server class machine than on a local host.  It appears that perhaps the caching features of Docker aren't being used properly or are being bypassed by the Codenvy infrastructure.

For caching best practices:
https://www.ctl.io/developers/blog/post/more-docker-image-cache-tips/ 

There are also documented issues with Vagrant and Docker, and led to the development of vagrant-cachier.  It is actually guaranteed to reduce the amount of coffee consumed while waiting for docker images to load on Vagrant:
http://fgrehm.viewdocs.io/vagrant-cachier/

Also, an apt-cache proxy would help speed the initial installation for any Debian clones:
https://help.ubuntu.com/community/AptProxy

**Comment by TylerJewell** [comment]
@mpouttuclarke Caching is enabled on codenvy.  The beta system had a major refresh and caches were wiped.  Since this would be a codenvy issue, going to close it on the che repository.

**Comment by TylerJewell** [comment]
You can open an issue on the codenvy repository if you want /codenvy/codenvy.  But with caching enabled, the issue would need to get into more of the specifics of what aspects of caching could be better improved.  Have you tested the scenarios on an on-prem infrastructure - the first workspaces until the cache is built up is always a bit slower.
