### ISSUE TITLE
Plugin installation fails from che-theila plugin view on Openshift 4 with enabled OAuth

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15169]
### Describe the bug
Plugin installation fails che-theila plugin view with Openshift 4 with enabled OAuth:

<img width="816" alt="Знімок екрана  о 16 20 49" src="https://user-images.githubusercontent.com/1614429/68598539-4f010700-049f-11ea-9d43-c412e4913195.png">

### Che version
 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

![Peek 2019-11-04 20-25](https://user-images.githubusercontent.com/1461122/68151242-9b00f880-ff41-11e9-8f22-30781885ba48.gif)

1. Start Che Server on Openshift 4 with enabled OAuth
2. Start a workspace
3. Open plugin view and install any plugin
4. ERROR: Workspace fails to restart / workspace deployment are not cleared

### Expected behavior
Plugin installations works as expected (workspace is restarted with a newly installed plugin availbale)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by vitaliy-guliy** [comment]
@ibuziuk for feature, could you record videos displaying the mouse cursor? ^^

**Comment by ibuziuk** [comment]
> @ibuziuk for feature, could you record videos displaying the mouse cursor? ^^

ack. strange I had `capture mouse cursor` enabled. Anyway, the recording is pretty straight forward even without the cursor

**Comment by ibuziuk** [comment]
@rhopp @dmytro-ndp could you please verify (this affects CRW 2.0)

**Comment by skabashnyuk** [comment]
>@rhopp @dmytro-ndp could you please verify (this affects CRW 2.0)

With(prefered) and without OAuth enabled, please.

**Comment by vitaliy-guliy** [comment]
At the moment we ask the dashboard to restart the workpsace, which is working fine.
There are two PRs to che 7.3.x and che-theia 7.3.2 solving the problem.
https://github.com/eclipse/che/pull/15194
https://github.com/eclipse/che-theia/pull/542
