### ISSUE TITLE
Do not allow to stop workspace with machine token if known that this operation will fail

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15164]
### Is your task related to a problem? Please describe.
In some edge cases like OAuth enabled on openshift or hosted che (that is has to be clarified) stop operation may fail. The reason for that is that che-server might not have enough permission by itself to delete objects in a namespace where workspace created.  If that can be tests with che-server we need to remove permission to delete workspace with machine token.

### Describe the solution you'd like
- test and identify configuration where workspace deletes with machine token is not possible.
- document or add the code that will not allow this operation.

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/15006

**Comment by skabashnyuk** [comment]
Reproduced on Openshift 4 with enabled OAuth

<img width="816" alt="Знімок екрана  о 16 20 49" src="https://user-images.githubusercontent.com/1614429/68598539-4f010700-049f-11ea-9d43-c412e4913195.png">

**Comment by skabashnyuk** [comment]
After start/stop/start switching from dashboard workspace become operational again.

**Comment by vitaliy-guliy** [comment]
How can we detect whether operation is allowed or not?

**Comment by skabashnyuk** [comment]
@vitaliy-guliy at this moment I think it's not allowed on Hosted Che and che on openshift with OAuth. Other configurations should not be affected. Let me know if you are aware of other possibilities I'll try to reproduce them.

**Comment by ibuziuk** [comment]
I think this was reproducible on crc with CRW without oath cc: @dmytro-ndp

**Comment by skabashnyuk** [comment]
@ibuziuk I saw that @artaleks9 confirm that https://github.com/eclipse/che/issues/15006 exist on CRW but that is because of incorrect UI work. I didn't see that he had an issue with k8s objects. So I assume that is similar to this https://github.com/eclipse/che/issues/15006#issuecomment-549875018 and not to this https://github.com/eclipse/che/issues/15006#issuecomment-550189980. That is a different issues in the same use-case.

**Comment by davidfestal** [comment]
Did you really test this on Hosted Che ? afair it's quite a specific case since we use the fabric8-proxy specific token that provides the rights on the user namespace without needing the keycloak token.

**Comment by skabashnyuk** [comment]
@davidfestal yes. I did testing on Hosted Che  https://github.com/eclipse/che/issues/15006#issuecomment-549875018 some problems exists such as
- https://github.com/redhat-developer/rh-che/issues/1689  Unclear exception during workspace stop with machine token
- Problems with start and stop of workspacepjez6q055p649mz6  https://github.com/redhat-developer/rh-che/issues/1691
- Untracked workspace deployments https://github.com/redhat-developer/rh-che/issues/1690

**Comment by vitaliy-guliy** [comment]
@skabashnyuk what's wrong with UI on CRW?

**Comment by skabashnyuk** [comment]
@vitaliy-guliy issues like https://github.com/eclipse/che/issues/15006#issuecomment-552766480 and https://github.com/eclipse/che/issues/15006#issuecomment-549875018

**Comment by davidfestal** [comment]
> @davidfestal yes. I did testing on Hosted Che [#15006 (comment)](https://github.com/eclipse/che/issues/15006#issuecomment-549875018) some problems exists such as
> 
> * [redhat-developer/rh-che#1689](https://github.com/redhat-developer/rh-che/issues/1689)  Unclear exception during workspace stop with machine token
> * Problems with start and stop of workspacepjez6q055p649mz6  [redhat-developer/rh-che#1691](https://github.com/redhat-developer/rh-che/issues/1691)
> * Untracked workspace deployments [redhat-developer/rh-che#1690](https://github.com/redhat-developer/rh-che/issues/1690)

Couldn't this be related to the last changes in the Che server regarding the namespace name defaults ? Some of the issues seem related to the fact that the Che server fails when managing the name of the namespace in which the workspace should be deleted.

**Comment by skabashnyuk** [comment]
>Couldn't this be related to the last changes. 

By this, you mean what?

>Some of the issues seem related to the fact that the Che server fails when managing the name of the namespace in which the workspace should be deleted.

Why do you think it's related? Do you see any evidence of that?  What changes in 7.3.1 you are referring?
