### ISSUE TITLE
Workspaces list filtering doesn't work

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#15171]
### Describe the bug

Filtering in the list of workspaces doesn't work.

### Che version

 - [ ] latest
 - [x] nightly
 - [x] other: 7.3.1

### Steps to reproduce

1. Create several workspaces
2. Click on "Workspaces" in the left navbar
3. Set focus into search field and start typing the name of one of available workspaces 

### Expected behavior

Workspaces which name partially matches to search string are shown.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: che.openshift.io

### Screenshots

![workspace-search-broken](https://user-images.githubusercontent.com/16220722/68660784-8379cf00-0542-11ea-8cf2-8db1726438e6.gif)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
It should be fixed by https://github.com/eclipse/che/pull/15642/files#diff-1a7164941c9e5d00b66080ca93f25a82L88
