### ISSUE TITLE
How to install linux packages to che workspace runtime

### ISSUE THREAD

**Issue by Aayush04** [eclipse-che/che#15177]
## Summary
I am using che version 7.2 . I want to install Linux packages in my workspace or workspace runtime. But the "user" does not have permission to install any packages. 

## Relevant information
I also tried che 6.19.6 but there I could install packages. As "user" can switch to root and do whatever installation he wants. But it seems like this is removed from in version 7. 
Is there any way to do in che 7 ?

<img width="1440" alt="Screen Shot 2019-11-13 at 2 43 32 PM" src="https://user-images.githubusercontent.com/4752354/68749306-02930400-0624-11ea-9e5b-9fd319ddb89c.png">

**Comment by tolusha** [comment]
The solution is to use a container with preinstalled packages.

**Comment by benoitf** [comment]
Depending on some configuration like with basic K8S you can have sudo installed in the Docker image. But with containers, restarting it will remove anything you might have installed.

So as suggested by @tolusha you should add you required tools in a Docker image, and add this image as part of your workspace definition.
Then, all tools that you want will be there, already installed. And anytime you create a workspace from this definition, tools will always be there
