### ISSUE TITLE
Dark theme for new Monaco devfile editor

### ISSUE THREAD

**Issue by beaumorley** [eclipse-che/che#15175]
### Problem

The new Monaco devfile editor is a nice improvement for editing devfiles for Che. However, the editor has a light theme. This editor can also have a dark theme. User research shows that a dark theme is preferred by developers. 

### Suggested change

If only one theme can be specified, from a UX perspective, it is recommended that the Che Monaco devfile editor be changed to dark. 

Alternatively, if this could be an option that is set up by the developer, that would be acceptable as well.

### Additional context
Example of the Monaco editor used as YAML editor with a dark theme.

![image](https://user-images.githubusercontent.com/52013984/68715674-855a8700-0570-11ea-9f90-38910de86f4b.png)

**Comment by l0rd** [comment]
Thank you @beaumorley for creating this

**Comment by tsmaeder** [comment]
I have to disagree here: there seems to be research that says dark theme is bad, especially for folks like me who need glasses. Here's a guy explaining why: https://www.quora.com/Is-a-dark-mode-light-text-on-dark-background-really-better-for-the-eyes

**Comment by beaumorley** [comment]
I've been asking users and most prefer dark. It is definitely somewhat of a developer preference, though. The best in class experience would allow the user to pick. Ideally, they could set their theme for the whole Che experience.

**Comment by l0rd** [comment]
Something else that I would like to mention is that currently che-theia default theme is dark and it make sense to be consistent with that. But we can configure the theme in che-theia so +1 to make it configurable on the dashboard monaco editor.

**Comment by l0rd** [comment]
@beaumorley any suggestion about how we could make the theme easily configurable from a UX point of view?

**Comment by beaumorley** [comment]
I believe the best option would be some kind of global setting that is tied to the account. The implementation I have seen that I like the best is what Cloud 9 is doing (see attached). However, the Cloud 9 setting as at the environment level (create the workspace first). I would consider having it at at the account level of the UI so the setting is applicable to everything inside and outside the workspaces. I'd suggest a settings area under the user's account that has an option similar to Cloud 9's "Configure AWS Cloud".

Here is the Cloud 9 UI:
![Competitor Screens](https://user-images.githubusercontent.com/52013984/69168106-090df980-0ac4-11ea-8039-012c9e8add63.png)

Here is where I might consider putting something in Che:
<img width="1366" alt="Screen Shot 2019-11-19 at 12 03 03 PM" src="https://user-images.githubusercontent.com/52013984/69168478-c0a30b80-0ac4-11ea-98de-db02ef1b5de0.png">
