### ISSUE TITLE
Open Link doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15172]
### Describe the bug
**Open Link** action doesn't work
![screenshot-che-che 192 168 99 104 nip io-2019 11 12-12_47_32](https://user-images.githubusercontent.com/1271546/68665377-9f816e80-054a-11ea-9157-a7f50d14c128.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace which can run web application for example Java Vert.x
2. Build and Run project by using commands
3. Try to open Application by clicking Open Link on popup window:

### Expected behavior
The view with application should be opened

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by musienko-maxim** [comment]
duplicated: https://github.com/eclipse/che/issues/15173
