### ISSUE TITLE
[che-operator] che operator should stop che server gracefully

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#15186]
### Describe the bug
Right now, when checluster CR is deleted, operator deletes all resources of che deployment, except for k8s/openshift resources of currently running workspaces, which remain on the cluster as some kind of orphans.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
* Install che using operator
* Start workspace
* Delete checluster CR
* Wait for operator to finish reconciliation 
* See, that workspace pods/deployments are not deleted

### Expected behavior
Operator should call  `/system/stop` API endpoint to shutdown gracefully (is this the correct endpoint, @skabashnyuk ?) all the workspaces, then wait for `/api/system/state` returning `READY_TO_SHUTDOWN` and just then, delete the server deployment (and all the others)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
@rhopp `/system/stop?shutdown=true` is a right call to do. But there might be difficulty in cleaning K8s/OS resources by Che Server without user token... It needs to be investigated carefully.
If the che-operator is able to provide `cluster-admin` k8s/os token - then it might work but I guess some changes should be done on the Che Server side.
