### ISSUE TITLE
UX: State of tasks not visible

### ISSUE THREAD

**Issue by FlorianLudwig** [eclipse-che/che#15185]
### Is your enhancement related to a problem? Please describe.
It is not possible to see if a task is already running or a started task is done. This resulted in multiple issues for me:

- First time i wanted to start a task I clicked on it - nothing happened so i tried double clicking.  A few seconds later I had the task running three times.
- I waited for a task to finish but didn't notice it was already finished since it there is no indication if a task is still running (I seem to have missed the notification)

### Describe the solution you'd like

- Make it visible on the right pane where tasks can be started if the task is already running
- Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side.
- Make the task status visible in the tabbed bar itself, mockup:
![UX-che](https://user-images.githubusercontent.com/432263/68787064-21ec5a00-0641-11ea-900b-8329c1be1b8e.gif)

### Describe alternatives you've considered

- Make it possible to declare tasks to be not possible to run concurrently (e.g. "install dependencies")

### Environment / Steps to reproduce

 * Login to https://che.openshift.io/
 * Create new workspace
 * Use "Python Django" template
 * Wait
 * Click on the right side "box" icon: "My Workspace"
 * Click "install dependencies" (If it works after some delay a terminal opens - or if you clicked something else since you thought it didn't work, several terminals.)

**Comment by benoitf** [comment]
cc @RomanNikitenko

**Comment by RomanNikitenko** [comment]
@FlorianLudwig 
is it some vs code extension on your screenshot?
could you share the reference for it, if so

thanks in advance!

**Comment by FlorianLudwig** [comment]
@RomanNikitenko I used https://che.openshift.io/ and used an example/template there.  I don't know if they have some special extensions there by default.

I updated the description with steps how to reproduce the issue.

**Comment by RomanNikitenko** [comment]
@FlorianLudwig 
Sorry, I asked you about the solution you'd like.

You provided this gif
![UX-che](https://user-images.githubusercontent.com/432263/68787064-21ec5a00-0641-11ea-900b-8329c1be1b8e.gif)

and I thought that you used some vs code extension for it.

**Comment by FlorianLudwig** [comment]
@RomanNikitenko that was done using gimp ;)

**Comment by slemeur** [comment]
Thanks @FlorianLudwig for the proposal, it's a really good idea.

There are two sub-tasks for this issue:
1. Displaying a small visual indicator about the state of a tasks. For this, I think proposal from @FlorianLudwig is perfect. I would just add that we could also add a tooltip on hover on the tasks output's tab saying the state of the tasks (ex: "{task_name} : RUNNING" or "{task_name} : COMPLETED")

2. The delay between "the user clicks on the task" and "the output terminal is getting shown". This is the biggest issue IMO. The user doesn't really know if the action (clicking on the task) has been taken into account. When the connectivity is not great, this lead to very inconvenient UX. We should look at how we can first open the terminal output, so it gives a visual feedback to the end-user, display an indicator inside of it (ex: "Task "{task-name}" - Connecting....") and then do the necessary background connection between the task running in the container and the output displayed in the IDE

**Comment by vzhukovskii** [comment]
@slemeur there is a proposal to improve UX by adding information about flow which user perform to run task. Especially, when user clicks on the task in _My Workspace_ - Che shows information in status bar that process preparing. Then, when terminal waits for the websocket connection show the loader in terminal tab. After that, when task finished Che will update icon in terminal tab to a success mark:

![ux-openshift-io](https://user-images.githubusercontent.com/1968177/70426404-aa60ed80-1a7b-11ea-8fdf-72afa4c59bde.gif)

**Comment by azatsarynnyy** [comment]
relabeled to `area/plugins` as the issue is related to https://github.com/eclipse/che-theia/tree/master/plugins/containers-plugin and https://github.com/eclipse/che-theia/tree/master/plugins/task-plugin
