### ISSUE TITLE
Che plugin registry use wrong redirect url

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#15189]
### Describe the bug
When Che deployed with self signet certificates, che-theia use `https://plugin-registry-aleks-crw2-operatorhub-tls.apps.crw.codereadyqe.com/v3/plugins/` URl  to get all plugins.
che plugin registry server returns:
```json
{
    "description": "Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.",
    "displayName": "Che machine-exec Service",
    "id": "eclipse/che-machine-exec-plugin/7.3.1",
    "links": {
      "self": "/v3/plugins/eclipse/che-machine-exec-plugin/7.3.1"
    },
    "name": "che-machine-exec-plugin",
    "publisher": "eclipse",
    "type": "Che Plugin",
    "version": "7.3.1"
  },
  {
    "description": "Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.",
    "displayName": "Che machine-exec Service",
    "id": "eclipse/che-machine-exec-plugin/latest",
    "links": {
      "self": "/v3/plugins/eclipse/che-machine-exec-plugin/latest"
    },
    "name": "che-machine-exec-plugin",
    "publisher": "eclipse",
    "type": "Che Plugin",
    "version": "latest"
  },
  {
    "description": "Eclipse Theia",
    "displayName": "theia-ide",
    "id": "eclipse/che-theia/7.3.1",
    "links": {
      "self": "/v3/plugins/eclipse/che-theia/7.3.1"
    },
    "name": "che-theia",
    "publisher": "eclipse",
    "type": "Che Editor",
    "version": "7.3.1"
  },
  {
    "description": "Eclipse Theia",
    "displayName": "theia-ide",
    "id": "eclipse/che-theia/latest",
    "links": {
      "self": "/v3/plugins/eclipse/che-theia/latest"
    },
    "name": "che-theia",
    "publisher": "eclipse",
    "type": "Che Editor",
    "version": "latest"
  }
``` 
Then che-theia use `self` field value to get plugin `meta.yaml` file:
URL: `https://plugin-registry-aleks-crw2-operatorhub-tls.apps.crw.codereadyqe.com/v3/plugins/eclipse/che-theia/latest`
but plugin registry return redirect response:
```
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 13 Nov 2019 18:25:43 GMT
< Server: Apache/2.4.34 (Red Hat) OpenSSL/1.0.2k-fips
< Location: http://plugin-registry-aleks-crw2-operatorhub-tls.apps.crw.codereadyqe.com/v3/plugins/eclipse/che-theia/latest/
< Content-Length: 319
< Content-Type: text/html; charset=iso-8859-1
< Set-Cookie: e69940bb5c8217f1bc84038298ef29c3=88b0cf0f6604605b7be5a7a48fc1d5b5; path=/; HttpOnly; Secure
< Cache-control: private
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://plugin-registry-aleks-crw2-operatorhub-tls.apps.crw.codereadyqe.com/v3/plugins/eclipse/che-theia/latest/">here</a>.</p>
</body></html>
```
but `Location` header has `http` protocol instead of `https`.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: CRW-2.0

### Expected behavior
plugin registry should provide proper link in `self` field and do not redirect to `http` if it running on `https` protocol

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: CRW2.0 test cluster

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
merged workaround to master and 7.3.x https://github.com/eclipse/che-plugin-registry/pull/296
