### ISSUE TITLE
Closing the ws-machine SSH console produce zombies

### ISSUE THREAD

**Issue by dhuebner** [eclipse-che/che#1518]
Closing the SSH console to ws-agent in che leaves a zombi process in docker container:

 132 root      20   0       0      0      0 Z  0.0  0.0   0:00.00 [bash] <defunct>  
  174 root      20   0       0      0      0 Z  0.0  0.0   0:00.00 [bash] <defunct>

**Comment by garagatyi** [comment]
Hi. Do you mean terminal in the IDE or direct SSH from your machine?

**Comment by dhuebner** [comment]
@garagatyi In IDE = "Consoles" view

**Comment by garagatyi** [comment]
Can you make a video to help with investigation. It would help a lot.

**Comment by dhuebner** [comment]
@garagatyi 

[Bildschirmaufnahme.mov.zip](https://github.com/eclipse/che/files/320238/Bildschirmaufnahme.mov.zip)

This could also help to get inspired:
https://youtu.be/56216UK41Yw

**Comment by garagatyi** [comment]
many thanks for both! And for the blazing fast response.

**Comment by garagatyi** [comment]
Yep, it's definitely a bug in che golang terminal. Thanks that you found it.

**Comment by dhuebner** [comment]
Thank you for investigating :)

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-1352

**Comment by bmicklea** [comment]
@AndrienkoAleksandr this issue is being addressed by a PR in the codenvy repo, is that correct? Should there be a PR for the che repo as well?

**Comment by TylerJewell** [comment]
We have a pending pull request that fixes the go bug.  https://github.com/eclipse/che-lib/pull/11.  We will include these fixes for M6.  Thank you @dhuebner for finding this.

**Comment by bmicklea** [comment]
Updating the milestone to match the associated PR (https://github.com/codenvy/codenvy/issues/570)

**Comment by bmicklea** [comment]
mistakenly hit the close button...
