### ISSUE TITLE
dead links on homepage to codenvy

### ISSUE THREAD

**Issue by FlorianLudwig** [eclipse-che/che#15184]
### Describe the bug

The "learn more" links on https://www.eclipse.org/che/extend/codenvy/ are dead.

**Comment by sunix** [comment]
I see Eclipse source https://eclipsesource.com/technology/eclipse-che/ and Serli who could provide such services at the moment.

**Comment by sunix** [comment]
So the fix would be to replace this page with a dedicated page for companies that could offer commercial services.
Would list
- Eclipse source https://eclipsesource.com/technology/eclipse-che/
- Serli ?

![Selection_685](https://user-images.githubusercontent.com/650571/77522817-23e2e700-6e85-11ea-805c-ca7c24906655.png)
