### ISSUE TITLE
Upgrade Kubernetes Che plugin with Helm 3 support

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15190]
### Is your task related to a problem? Please describe.

To enable Helm 3 support in Kubernetes Tooling Che plugin we need to upgrade its dependencies to:
- Helm 3 https://github.com/helm/helm/releases/tag/v3.0.0
- Kubernetes Tools VS Code extension v. 1.0.7 with Helm 3 support https://github.com/Azure/vscode-kubernetes-tools/releases/tag/1.0.7

**Comment by ericwill** [comment]
I don't have the permissions, but I think this one can be closed now (all PRs were merged).
