### ISSUE TITLE
Cors issue 

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15196]
### Describe the bug
List stacks on is empty on the tab `ready to go stack` for minikube multiuser. In logs - CORS issue.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open che-user dashboard. 
2. Select tab `ready to go-stack`

### Expected behavior
 - Tab with `ready to go stack` should display stack list.

### Logs:
https://gist.github.com/AndrienkoAleksandr/5d527bb383fb372c279512a2c0f5948a

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
can you show the response from ```http://devfile-registry-che.192.168.99.100.nip.io/devfiles/index.json```
are you sure it's not a service unavailable page from OpenShift?

**Comment by AndrienkoAleksandr** [comment]
@skabashnyuk, yes seems page is not available.
