### ISSUE TITLE
Don't show two product logo on start

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15197]
### Describe the bug

Two product logo are displayed in Welcome page on start.
The bug does not depend on environment and deploy method.
The problem is that on remote Che styles for welcome page are loaded with a little delay.
This delay is normal behavior, but we need to handle it.
The best solution here is does not show product logo at all until styles has been loaded.

![Screenshot from 2019-11-14 15-32-49](https://user-images.githubusercontent.com/1655894/68861427-376e8c00-06f4-11ea-9aa1-a62b17d279ea.png)

### Che version

 - [x] nightly

### Steps to reproduce

1. Open Che-Theia.

### Expected behavior

One product logo must be displayed on the start. No blinking.

### Runtime
To test use remote Che, not local. On local it goes very fast, bug is not reproducible.

**Comment by tsmaeder** [comment]
It's purely cosmetic, but since it's the first thing a use sees when opening a workpspace, I'm giving this one a P1.
