### ISSUE TITLE
[docs] Cannot find Che configuration options

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15191]
In https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/, the doc describes a process for setting "advanced configuration options". However, there is no list of all possible options with proper values and what their effect is.

**Comment by tsmaeder** [comment]
If the list is somewhere else, we need to add a link to that section.

**Comment by amisevsk** [comment]
Ideally it would be nice to have an automatic conversion from `che.properties` and `multiuser.properties`, as they already have some documentation attached (though it could be improved).

**Comment by tolusha** [comment]
As @amisevsk mentioned, properties and documentation can be find here:
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties

**Comment by tsmaeder** [comment]
@tolusha this information needs to in the doc or it needs to be pointed to in the doc.

**Comment by rkratky** [comment]
@tsmaeder, please, see https://github.com/eclipse/che-docs/pull/1232
