### ISSUE TITLE
Some icons on plugin view panel are not rendered correctly

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15193]
### Is your task related to a problem? Please describe.
Some icons on plugin view panel are not rendered correctly
![Знімок екрана  о 10 13 02](https://user-images.githubusercontent.com/1614429/68847258-a6d18500-06ce-11ea-926f-d904feec4c2c.png)

### Describe the solution you'd like
icons rendered correctly.

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by tsmaeder** [comment]
P2, as this is purely visual.
