### ISSUE TITLE
[Doc] Che7 - Prepared Explorer for Endevor Docs for open sourcing

### ISSUE THREAD

**Issue by DStatWriter** [eclipse-che/che#15199]
PR contains re-formatted and prepared docs relating to Open Sourcing of Explorer for Endevor

This supports the re-purposing of Explorer for Endevor from proprietary code to open sourced che extension.

Docs serve as user guide

**Comment by benoitf** [comment]
Hello, could you please update description so it can be understood by all people, not only by the one who is submitting or work on the issue ?
