### ISSUE TITLE
Wrong example for che custom properties

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15192]
In this doc: https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/, the following example
```
customCheProperties:
      CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB: 2048
```
is wrong: the correct syntax has double quotes around the number, as in `"2048"`

![image](https://user-images.githubusercontent.com/13163770/68847019-39255900-06ce-11ea-824d-7b46bce836f0.png)

**Comment by tsmaeder** [comment]
Also, the error message is very verbose and incorrect: `5000` is totally an integer.

**Comment by ibuziuk** [comment]
PR sent  - https://github.com/eclipse/che-docs/pull/914

**Comment by ibuziuk** [comment]
> Also, the error message is very verbose and incorrect: 5000 is totally an integer.

It is, the error message says `body must be of type string`. I think we can close the issue. docs are update - https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/
