### ISSUE TITLE
[doc] Document support of the private registries

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15209]
## Summary
- che version : 7.3.0
- runtime : kubernetes
- installer : helm
I uncommented the registry part in values.yaml file.
I got registry-pull-secret but it couldn't pull the image in private docker registry.

![image](https://user-images.githubusercontent.com/29850624/69023892-c71d7e80-0a03-11ea-81e8-530026ba29b1.png)

![image](https://user-images.githubusercontent.com/29850624/69024407-f8974980-0a05-11ea-9e31-af3b2ed38975.png)

![image](https://user-images.githubusercontent.com/29850624/69023926-e4eae380-0a03-11ea-85ea-7c1b3d3c05d1.png)

I want to set up a private docker registry in the yaml file, not on che's administration page.

**Comment by skabashnyuk** [comment]
@kellyhyomin thank you for this report.
AFAIK the single way how to set up credentials to private docker registry - with help of  che's administration page. Did you try this way?

**Comment by ibuziuk** [comment]
@rkratky I can not find the docs related to the private registry setup. is it going to be backported?

**Comment by ibuziuk** [comment]
@kellyhyomin you should be able to setup it via the UD:

![registry](https://user-images.githubusercontent.com/1461122/69034519-b3612080-09e1-11ea-9af6-0f860e315aba.gif)

**Comment by kellyhyomin** [comment]
@skabashnyuk  @ibuziuk 
Thank you for reply. 
I already know how to do it on the administration page you gave me.
I was wondering if it is possible to set private registry in https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml file.
Because I want to make certain people use images in company's private docker registry.

**Comment by kellyhyomin** [comment]
@skabashnyuk @ibuziuk 
Thank you for reply.
I already know how to do it on the administration page you gave me.
I was wondering if it is possible to set private registry in https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml file.
Because I want to make certain people use images in company's private docker registry.

**Comment by ibuziuk** [comment]
> I was wondering if it is possible to set private registry in https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml file.

no, I believe there is no such feature. @kellyhyomin so, you would like to create some secrets with private registry info + credentials and then refer to it from the deployment via env var e.g `CHE_PRIVATE_REGISTRY_ADDRESS`?

**Comment by kellyhyomin** [comment]
@ibuziuk 
yes. What I want is the same as what you said.
I know the env you provided are CHE_DOCKER_REGISTRY_AUTH_REGISTRY1_URL, CHE_DOCKER_REGISTRY_AUTH_REGISTRY1_USERNAME and CHE_DOCKER_REGISTRY_AUTH_REGISTRY1_PASSWORD but those settings don't work.

**Comment by ibuziuk** [comment]
@kellyhyomin can you please create a feature request for it? Maybe you will also be interested in contributing ;-)

**Comment by l0rd** [comment]
If I understand correctly @kellyhyomin you are able deploy Che using images from a private registry. And you expect that the secret `values.yaml` is used when a user is starting a workspace.

Deploying Che and starting a workspace are usually done by different users. The first by an admin that is responsible to deploy/maintain the Che server in a Kubernetes cluster. The second by a developer that wants to start a Che workspace for coding. I suppose that this is the reason why those configurations were separated.
