### ISSUE TITLE
Non-localhost plugin sidecar brokering will fail with modern plugins

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15204]
### Describe the bug
The plugin broker supports a flag `--use-localhost-in-plugin-urls`, which is designed to allow running plugins in separate pods from Theia (if set to false). However, the code that does this only handles plugins that do not have additional endpoints defined:
- The plugin broker does not validate that there are no endpoints defined, and instead [blindly adds an endpoint for Theia](https://github.com/eclipse/che-plugin-broker/blob/0adb6c9c1e4a32f5c76343066944f9a11faa0cde/brokers/unified/vscode/sidecar.go#L39).
- It then adds an [env var to correspond to that endpoint](https://github.com/eclipse/che-plugin-broker/blob/0adb6c9c1e4a32f5c76343066944f9a11faa0cde/brokers/unified/vscode/sidecar.go#L64).

However, since https://github.com/eclipse/che/issues/14766 added the capability to define endpoints for VS Code plugins, the above functionality will fail for any plugin that defines endpoints.

### Che version

 - [x] latest
 - [x] nightly

### Additional info
By default, the flag is disabled, so this issue should not present in normal use of Che.

**Comment by ibuziuk** [comment]
@amisevsk I suspect this also affects 7.3.1 / 7.3.2 right ?

**Comment by amisevsk** [comment]
@ibuziuk At the end of the day, no release of Che is affected, since the config setting (`use-localhost-in-plugin-urls`) is awlway
