### ISSUE TITLE
Use a maven sample for the maven stack

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15216]
### Is your enhancement related to a problem? Please describe.
We use the java sample [1] with a Grandle build-system by default for the java-maven stack [2].
It confuses and leads to such quesitons [3]

[1] https://github.com/che-samples/console-java-simple
[2] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/devfile.yaml
[3] https://stackoverflow.com/questions/58863192/eclipse-che-workspace-wont-recognize-new-maven-dependencies

### Describe the solution you'd like
Use a sample with maven build-system for the java-maven stack.

**Comment by tsmaeder** [comment]
I don't mind the sample, but we need a way to force VS Code Java to use maven. Find out if we can use a preference in the devfile for this. Otherwise, remove the gradle support from the sample. Make sure console-simple is not used in our gradle stack

**Comment by JPinkney** [comment]
I wonder if we could just separate the maven and gradle parts into two different branches in the console-java-simple repo?

I've gone with this idea in:
https://github.com/JPinkney/console-java-simple/tree/gradle-java1.11
https://github.com/JPinkney/console-java-simple/tree/maven-java1.11

and then the corresponding update in the devfile registry:
https://github.com/JPinkney/che-devfile-registry/tree/seperate-maven-gradle

The only reason I'm advocating this way is that I personally always use this stack as a go-to if I'm ever doing something simple with java and it serves as a super easy starter template. Plus its rarely touched so the maintenance is almost non-existent

**Comment by tsmaeder** [comment]
I would advocate against using branches: branches are for different development paths of the same thing. A maven and a console sample would warrant a different repo, IMO. Think of it this way: what would master contain? Maven or Gradle?

**Comment by JPinkney** [comment]
My idea was to be similiar to the che-sidecars where master would just be a readme that points to the maven/gradle branches but I know thats not ideal. But there's also a few other ways:

1. Have console-java-maven and console-java-gradle repos
2. Pick a different gradle stack and delete build.gradle from console-java-simple
3. Pick a different maven stack and delete pom.xml from console-java-simple
4. See if setting `java.import.gradle.enabled: false` in the devfile forces the language server to use maven. IMO it's probably confusing for the user to see both pom.xml and build.gradle in the same project

@tsmaeder Which one do you think we should go with?

**Comment by tsmaeder** [comment]
I would go with 1. Repos are cheap, right?

**Comment by ibuziuk** [comment]
Closing as obsolete
