### ISSUE TITLE
Error 404 on download page

### ISSUE THREAD

**Issue by Mikolaj98p** [eclipse-che/che#15219]
## Summary
Hello.
My question is about error 404 on download page.
How can I host Eclipse Che on my own server or how can I setup on CentOS?
Thanks.

**Comment by tolusha** [comment]
You can install Eclips Che using chectl [1] on minishift [2] or minikube [3] environment

[1] https://github.com/che-incubator/chectl
[2] https://docs.okd.io/latest/minishift/getting-started/installing.html
[3] https://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by ibuziuk** [comment]
My question is about error 404 on download page.

@Mikolaj98p could you please clarify which URL do you mean?

**Comment by monaka** [comment]
I found a same question on [Twitter](https://twitter.com/mehdirazag/status/1199233170778066944). 

https://www.eclipse.org/che/docs/quick-start.html in https://www.eclipse.org/che/getting-started/ returns 404

**Comment by ibuziuk** [comment]
@rkratky could you please take care about the redirect from https://www.eclipse.org/che/docs/quick-start.html ?

**Comment by ibuziuk** [comment]
Fixed https://github.com/eclipse/che-docs/pull/1091
Closing
