### ISSUE TITLE
Update year in license headers of files for 2019

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15222]
### Is your task related to a problem? Please describe.
As 2019 draws to a close, we should probably [update the year in our license headers](https://github.com/eclipse/che-parent/blob/master/pom.xml#L84).

**Comment by ibuziuk** [comment]
@skabashnyuk @vparfonov could you please clarify who is normally doing the year update thingy across the repos ?

**Comment by skabashnyuk** [comment]
it can be anybody

**Comment by skabashnyuk** [comment]
Duplicated https://github.com/eclipse/che/issues/14531
