### ISSUE TITLE
Multiple Broken Documentation Links

### ISSUE THREAD

**Issue by rbkaspr** [eclipse-che/che#15224]
### Is your task related to a problem? Please describe.
Multiple documentation links in the README link back to 404'd pages on the Eclipse website. This includes documentation for running Che on your own K8s cluster.

### Describe the solution you'd like
Documentation should either be restored on the Eclipse website or else hosted elsewhere and the link in the README should be updated with their proper location.

Appears similar to #5030 and #9945

**Comment by l0rd** [comment]
@sunix can you have a look?

**Comment by sunix** [comment]
yes

**Comment by sunix** [comment]
I have updated the links. Thanks @rbkaspr

**Comment by rbkaspr** [comment]
Looks like a few more are still broken, basically everything in the Using Eclipse Che section

https://github.com/eclipse/che/blob/master/README.md#using-eclipse-che

**Comment by sunix** [comment]
you are right, I have missed that ones... thanks

**Comment by sunix** [comment]
@rbkaspr should be fine now. Thanks again

**Comment by gravypod** [comment]
@sunix sorry to poke but it looks like this page has some broken links as well: 

https://github.com/eclipse/che/tree/master/deploy/kubernetes

This page links to:

- https://www.eclipse.org/che/docs/kubernetes-multi-user.html
- https://www.eclipse.org/che/docs/kubernetes-single-user.html

These both 404.
