### ISSUE TITLE
Che REST APIs link 404

### ISSUE THREAD

**Issue by FlorianLudwig** [eclipse-che/che#15229]
# steps to reproduce

 * open page: https://www.eclipse.org/che/extend/
 * Scroll down
 * click "Che REST APIs"

Additionally all links in the footer under "Extend" are dead as well.

**Comment by l0rd** [comment]
cc @rkratky @themr0c

**Comment by FlorianLudwig** [comment]
bug persists, still 404

cc @rkratky @themr0c

/remove-lifecycle stale

**Comment by l0rd** [comment]
The quick solution is to link to che.osio swagger instead.

**Comment by ibuziuk** [comment]
works for me - https://che.openshift.io/swagger/
