### ISSUE TITLE
UX: Unclear error message: See more in "Output".

### ISSUE THREAD

**Issue by FlorianLudwig** [eclipse-che/che#15228]
### Is your enhancement related to a problem? Please describe.
While reproducing steps of #15185 it didn't work at all to run my code:

![image](https://user-images.githubusercontent.com/432263/69147172-acb1d680-0ad1-11ea-920c-8448dd28c500.png)

The message `See more in "Output"` is not helpful. What output? Where is "output"?

### Describe the solution you'd like

ideas: 

 * Include details directly in notification
 * or make "Output" clickable and navigate to output.

### Environment / Steps to reproduce

 * Login to https://che.openshift.io/
 * Create new workspace
 * Use "Python Django" template
 * Wait
 * Click on the right side "box" icon: "My Workspace"
 * Click "install dependencies" (sometimes works, sometimes does nothing, sometimes the error as described above)

P.S. after finding "output" I probably should report the issue itself as well but this ticket is just about the error message itself being not helpful.

**Comment by l0rd** [comment]
Thanks @FlorianLudwig for reporting this. I think "Output" refers to the task output (@RomanNikitenko can correct me if I am wrong). Do you something suspicious in the the command output? If we rephrase it "Task output" would that help?

**Comment by FlorianLudwig** [comment]
@l0rd do I get this right: the error is that the terminal couldn't be connected - which means I would not see the task output and the advice is to look at the task output?

**Comment by RomanNikitenko** [comment]
I think this notification was provided within https://github.com/eclipse/che/issues/13980
So, user should open `View=>Output` for more details, not task output.
@akurinnoy please correct me if I'm wrong

**Comment by akurinnoy** [comment]
@RomanNikitenko you're right, 
this message refers to `Output` view where you also should pick `remote-terminal` channel in top right corner of panel. User can find there at least an error stack trace in case of remote terminal couldn't be connected.
