### ISSUE TITLE
Environment variable support of the private registries in k8s

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15234]
### Is your enhancement related to a problem? Please describe.

#15209 
For now, if I use a private docker registry image when creating a workspace, I can only set the secret on the administration page.
This approach is difficult when several people use a stack containing private docker registry images.
### Describe the solution you'd like

I would like to create some secrets with private docker registry info + credentials and then refer to it whenever I deploy a workspace from the deployment via env var.
This allows people to pull an image from the private docker registry when creating a workspace without any configuration on the administration page.(http://che-url/dashboard/#/administration).

**Comment by l0rd** [comment]
@kellyhyomin I need more information to triage this issue. There are 2 distinct use cases in Che where you need to setup a secret to with a private registry details.

1) When a user starts a Che workspace and the images of the workspace are in a private registry. In this case a user has to configure the private registry details in the dashboard. This is not an admin task but a user task. Every user can setup his list of private registries in the dashboard. Che will take care of creating the secrets and use them when starting workspaces pods.

2) When an admin deploys the Che server: he needs to setup the secret to pull the che-server image (as well as other images needed to deploy Che). This is a one time operation done by the administrator that deploys Che server and is unrelated to the creation of the Che workspaces. This looks like the scenario that you described in #15209.

What of the 2 scenarios are you interested in? What's your issue with using the user dashboard to configure a private registry to pull the images needed in a Che workspace?
