### ISSUE TITLE
Usability: Allow to Edit Workspace Commands

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15239]
In the context of adjusting the self-hosting devfiles to my concrete needs, I'd like to adjust the devfile commands, for example to use different directories.
Currently, I have to stop the workspace, change the command and restart the workspace for each change (which can be tedious especially if my changes don't immediately work)

I would propose a way to edit the commands from within the IDE. We could restrict editing in a way that makes it less likely that we break something in the devfile.

**Comment by tsmaeder** [comment]
Related: https://github.com/eclipse/che/issues/13989

**Comment by benoitf** [comment]
@tsmaeder devfile commands are transformed into tasks and you can edit tasks ?

**Comment by tsmaeder** [comment]
@benoitf 
1. will that be persisted in the devfile?
2. That link is not obvious.

**Comment by benoitf** [comment]
@tsmaeder 
for 1. no

I think this issue is already handled by wider epic issue: https://github.com/eclipse/che/issues/12709

**Comment by azatsarynnyy** [comment]
relabeled to `area/plugins` as it's related to https://github.com/eclipse/che-theia/tree/master/plugins/task-plugin
