### ISSUE TITLE
[che-theia] build of che-theia is failing in master branch

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15230]
### Describe the bug
Build of **che-theia** is failing in master branch:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-master-check-E2E-Happy-path-tests-against-K8S/698/console
Command to builds: `build.sh --skip-tests --dockerfile:Dockerfile.alpine`

Build log:
> go: finding golang.org/x/tools v0.0.0-20191108194844-46f05828f2fe
https fetch failed: Get https://honnef.co/go/tools?go-get=1: x509: certificate is valid for *.netlify.com, netlify.com, not honnef.co
> go: honnef.co/go/tools@v0.0.1-2019.2.3: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: x509: certificate is valid for *.netlify.com, netlify.com, not honnef.co)
> go: error loading module requirements
> The command '/bin/sh -c set -e 	&& 	apk add --update --no-cache  --virtual .build-deps 		bash 		gcc 		musl-dev 		openssl 		go         git     && 	export 		GOROOT_BOOTSTRAP="$(go env GOROOT)" 		GOOS="$(go env GOOS)" 		GOARCH="$(go env GOARCH)" 		GOHOSTOS="$(go env GOHOSTOS)" 		GOHOSTARCH="$(go env GOHOSTARCH)"     && 	apkArch="$(apk --print-arch)" 	&& 	case "$apkArch" in 		armhf) export GOARM='6' ;; 		x86) export GO386='387' ;; 	esac 	&&     wget -qO- https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz | tar xvz -C /usr/local && 	cd /usr/local/go/src &&	./make.bash && 	rm -rf /usr/local/go/pkg/bootstrap /usr/local/go/pkg/obj &&     export GOPATH="/go" &&     mkdir -p "$GOPATH/src" "$GOPATH/bin" "$GOPATH/pkg" &&     export PATH="$GOPATH/bin:/usr/local/go/bin:$PATH" &&     go get -u -v github.com/ramya-rao-a/go-outline &&     go get -u -v github.com/acroca/go-symbols &&      go get -u -v github.com/stamblerre/gocode &&      go get -u -v github.com/rogpeppe/godef &&     go get -u -v golang.org/x/tools/cmd/godoc &&     go get -u -v github.com/zmb3/gogetdoc &&     go get -u -v golang.org/x/lint/golint &&     go get -u -v github.com/fatih/gomodifytags &&      go get -u -v golang.org/x/tools/cmd/gorename &&     go get -u -v sourcegraph.com/sqs/goreturns &&     go get -u -v golang.org/x/tools/cmd/goimports &&     go get -u -v github.com/cweill/gotests/... &&     go get -u -v golang.org/x/tools/cmd/guru &&     go get -u -v github.com/josharian/impl &&     go get -u -v github.com/haya14busa/goplay/cmd/goplay &&     go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct &&     go get -u -v github.com/alecthomas/gometalinter &&     go get -u -v github.com/go-delve/delve/cmd/dlv && 	go get -u -v github.com/rogpeppe/godef && 	go get -u -v github.com/uudashr/gopkgs/cmd/gopkgs && 	go get -u -v golang.org/x/tools/cmd/gotype && 	GO111MODULE=on go get -v golang.org/x/tools/gopls@latest && 	go build -o /go/bin/gocode-gomod github.com/stamblerre/gocode &&     gometalinter --install && 	chmod -R 777 "$GOPATH" && 	apk del .build-deps && 	mkdir /.cache && chmod -R 777 /.cache &&     apk add gcc g++ git' returned a non-zero code: 1

### Che-theia version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

**Comment by tolusha** [comment]
@dmytro-ndp 
I can't reproduce it on the master branch
```
Build of eclipse/che-remote-plugin-go-1.12.9:next [OK]
Script run successfully: eclipse/che-remote-plugin-go-1.12.9:next
```

**Comment by tolusha** [comment]
The build is green https://ci.codenvycorp.com/job/che-theia-next/

**Comment by RomanNikitenko** [comment]
I faced with the same issue today at building images locally 
![ci_error](https://user-images.githubusercontent.com/5676062/69185517-97fc2f80-0b1f-11ea-8552-36f65f6e8292.png)

**Comment by benoitf** [comment]
Its fixed in https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/573/console
