### ISSUE TITLE
Che with a local Eclipse IDE

### ISSUE THREAD

**Issue by gee4vee** [eclipse-che/che#15233]
So this is reported to be possible in the feature descriptions of Eclipse Che, but I can't seem to find any docs. Specifically, I'd like to continue using traditional Eclipse desktop IDE with Che workspaces. Also, to be able to use VS Code in the same fashion would be a plus.

**Comment by l0rd** [comment]
@gee4vee can you add a link/reference of where it is said that it is possible to use Che with local Eclipse IDE? As far as I know that's not possible and there is this issue https://github.com/eclipse/che/issues/15016 that mention that but we are not ready to start working on it yet.

**Comment by gee4vee** [comment]
https://www.eclipse.org/che/features/#any-ide

> Start working from any device without installing software by using the built-in Eclipse Che IDE. Or stick with the desktop IDE you love by mounting into the Che workspace. Your choice.
