### ISSUE TITLE
missing/incorrect peer dependencies when building theia extensions

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15232]
### Is your enhancement related to a problem? Please describe.

CRW 2.0 Theia builds currently complain about missing/incorrect peer dependencies. Presumably the same is true upstream in Che 7.3.2.

```
[3/4] Linking dependencies...
warning " > ts-jest@22.4.3" has incorrect peer dependency "typescript@2.x".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-af9b45c7-8c6b-426f-a5a2-676f5dc99b98 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-af9b45c7-8c6b-426f-a5a2-676f5dc99b98 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-af9b45c7-8c6b-426f-a5a2-676f5dc99b98 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-af9b45c7-8c6b-426f-a5a2-676f5dc99b98 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-ext > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning Workspaces can only be enabled in private projects.
```
-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/403/parsed_console/

### Describe the solution you'd like

Fix the `package.json` files to resolve these conflicts.

### Describe alternatives you've considered

I can ignore them but they might turn into errors in future. :)

**Comment by l0rd** [comment]
@evidolob @benoitf are those warning in upstream build of che-theia as well?

**Comment by benoitf** [comment]
Yes, and basically I would avoid to have 500 issues created by Nick for these warnings.
It's an automate warning, not an error. Thus it doesn't mean that there is a problem as some tools may lead to invalid report as well.

**Comment by benoitf** [comment]
if it becomes an error, in any case it would be solved.
But it can't becomes an error right now as we pinned down the dependencies through yarn.lock file

**Comment by nickboldt** [comment]
> Yes, and basically I would avoid to have 500 issues created by Nick for these warnings.

![image](https://user-images.githubusercontent.com/227597/69382520-3fdf3d80-0c85-11ea-93d9-5c51f01a2fdf.png)

:P fine I won't try to make upstream builds better and less noisy. :P
