### ISSUE TITLE
The links to factories on Che homepage don't work anymore

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15238]
### Describe the bug
Clicking on any of the workspace links on the Che homepage gives an error.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: che.openshift.io as of 20th Nov 2019

### Steps to reproduce

1. Navigate to https://www.eclipse.org/che/
1. Click on one of the links in the "Start working with Che" section, e.g. https://che.openshift.io/f?id=factoryqn54y270f4eh4d00 for the Vert.x example.
1. che.openshift.io is not able to start the workspace from the provided link giving the error "Factory has no compatible workspace config or devfile."

### Expected behavior
The workspaces should start.

### Screenshots

![image](https://user-images.githubusercontent.com/19999/69225469-c3facd80-0b7e-11ea-8b67-93ed4649f2dd.png)

**Comment by ibuziuk** [comment]
PR sent - https://github.com/eclipse/che-website/pull/30

**Comment by ibuziuk** [comment]
PR merged. Closing

**Comment by benoitf** [comment]
thx @ibuziuk
