### ISSUE TITLE
Implement "getting started" devfiles test suite - 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15244]
### Is your task related to a problem? Please describe.
Need to add test suite with integration tests for "getting-started' devfiles - https://www.eclipse.org/che/getting-started/cloud/

Getting started devfiles - https://github.com/redhat-developer/devfile/tree/master/getting-started

![image](https://user-images.githubusercontent.com/1461122/63963151-b01a6080-ca94-11e9-8d0c-d5bf5b12b092.png)

**Comment by ScrewTSW** [comment]
@ibuziuk Shouldn't this issue be in `redhat-developer/rh-che`?
As far as I know, there are no "getting started" devfiles or factories for upstream che

**Comment by ibuziuk** [comment]
No, this is part of the website, so let's track it upstream

**Comment by rhopp** [comment]
@ibuziuk Do we have any metrics of usage of the devfiles? To properly prioritize which devfiles should be covered first.

Are these devfiles much different from the default ones in devfile-registry? Wouldn't make sense to unify that somehow?

**Comment by ScrewTSW** [comment]
Still in progress.
