### ISSUE TITLE
Remove legacy workspace config code from Che Theia

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#15249]
Now some components of Che-Theia still have code which handles old Che 6 workspace config format. That code is unused and outdated for Che 7. We should clean it up.

**Comment by benoitf** [comment]
related to https://github.com/eclipse/che/issues/15249

**Comment by benoitf** [comment]
@mmorhun could you tell what are the difference with https://github.com/eclipse/che/issues/15237 ?

**Comment by mmorhun** [comment]
@benoitf they are two different issues. Sorry if it wasn't clear in description, but I meant to make changes in our source code. This issue doesn't suppose to do anything with docs.

**Comment by mmorhun** [comment]
We should clean up old unneeded code.

**Comment by mmorhun** [comment]
@azatsarynnyy have this issue been completed?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy have this issue been completed?

I don't think so. As I remember, there are a couple of obsolete parts that should be reviewed. Reopening.

**Comment by RomanNikitenko** [comment]
Moving additional context from https://github.com/eclipse/che/issues/19082

### Additional context
- [handleWorkspaceProjects](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L26)
- [WorkspaceProjectsManager](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L36)
- [WorkspaceConfigProjectsManager](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L166)
- [startSyncWorkspaceProjects](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L71) is not async actually

**Comment by benoitf** [comment]
this 'workspaceConfig' code should disappear with the ongoing work to use dev workspaces with che-theia
