### ISSUE TITLE
Integration tests for workspace idling

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15240]
### Is your task related to a problem? Please describe.
Workspace idling is the crucial functionality for Hosted Che and currently, there are no Integration tests for it.

### Describe the solution you'd like
The scenario is the following:
- Che server is deployed with `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT` set to 1 minute
- Workspace is started
- After 1 minute being in the `RUNNING` state workspace is stopped automatically

**Comment by rhopp** [comment]
Seems like we already have this in place. https://ci.codenvycorp.com/view/qa-rc/job/che-integration-tests-ocp-rc/32/testReport/org.eclipse.che.selenium.workspaces/CheckStoppingWsByTimeoutTest/
@SkorikSergey Can you confirm this? Or is the test testing something else?

**Comment by ibuziuk** [comment]
@rhopp @Katka92 if this is in place we need to enable it for Hosted Che PR verification / periodic tests

**Comment by SkorikSergey** [comment]
> Seems like we already have this in place. https://ci.codenvycorp.com/view/qa-rc/job/che-integration-tests-ocp-rc/32/testReport/org.eclipse.che.selenium.workspaces/CheckStoppingWsByTimeoutTest/
> @SkorikSergey Can you confirm this? Or is the test testing something else?

Yes. CheckStoppingWsByTimeoutTest selenium test checks workspace stopping after 420000 ms inactivity.

**Comment by ibuziuk** [comment]
@SkorikSergey could you please clarify as part of which test suite it is running ?

**Comment by SkorikSergey** [comment]
> @SkorikSergey could you please clarify as part of which test suite it is running ?

**CheckStoppingWsByTimeoutTest** is running  in [CheSuite.xml](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/resources/suites/CheSuite.xml) tests suite. And CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS properties sets to 420000.

**Comment by Katka92** [comment]
Thank you @SkorikSergey for information. I see it is part of Java test suite, which is not used on Hosted Che. I would go rather for reimplementing this test to a typescript test suite and use that on downstream easily then adopting the upstream Java tests just for this one simple test. 
cc @ibuziuk @rhopp
