### ISSUE TITLE
Refactoring: clean up che-machine-exec model

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15243]
### Is your enhancement related to a problem? Please describe.
che-machine-exec model should define only model types, but currently we have in this package business logic also.

### Describe the solution you'd like
Refactor code.

**Comment by benoitf** [comment]
is it more a technical debt kind issue ?

**Comment by AndrienkoAleksandr** [comment]
> is it more a technical debt kind issue ?

Yes, it is
