### ISSUE TITLE
Workspace is not restarted after installing a plugin

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15253]
### Describe the bug

After installing a plugin and restarting the workspace dashboard switches to the Workspace Loader very fast and does not wait until workspace status has been changes from RUNNING to STOPPING.
It leads to opening Workpace Loader page which displays a loader with infinity loop. 

### Che version

 - [x] nightly

### Steps to reproduce
Open Theia, install a plugin and click `Reload` button on the top of the Plugins view.

### Expected behavior
Workspace must be reloaded.

**Comment by dmytro-ndp** [comment]
The issue affects CRW 2.0.0.RC3
