### ISSUE TITLE
Sometimes Che is failing to restart an existing workspace

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15259]
### Describe the bug
Sometimes, restarting the workspace is failling with the error:

```
Error: Failed to run the workspace: "Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/user1-che/configmaps. Message: configmaps "workspaceuau5qdg0zx61zse2-sshconfigmap" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=workspaceuau5qdg0zx61zse2-sshconfigmap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "workspaceuau5qdg0zx61zse2-sshconfigmap" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
```

refreshing the page works

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift 4.2
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_460](https://user-images.githubusercontent.com/650571/69262154-3e4d4100-0bc3-11ea-906d-3c2f4202b5ab.png)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [x] Linux
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
If I'm not mistaken - I already saw a similar issue. It happens because previously workspace was not stopped correctly.
To prevent such error - we could do `createOrReplace` instead of just `create` or remove everything (services, configmap, pods) related to starting workspace before the start.

**Comment by skabashnyuk** [comment]
@l0rd @davidfestal are you ok  with @sleshchenko proposal https://github.com/eclipse/che/issues/15259#issuecomment-556977394 ?

**Comment by skabashnyuk** [comment]
Duplicate https://github.com/eclipse/che/issues/15904
