### ISSUE TITLE
Refactor and unify namespace/project handling for k8s and openshift infras 

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15250]
Currently there is an awful lot of code and testsuite duplication between `KubernetesNamespaceFactory` and `OpenShiftProjectFactory` and `KubernetesNamespace` and `OpenShiftProject` respectively.

We should think about bringing these closer together (including the testsuite). Currently it is very error prone to try updating them and keeping them in sync.

**Comment by benoitf** [comment]
is that CRD controller will solve this issue ?

**Comment by davidfestal** [comment]
That might still be useful I assume.
