### ISSUE TITLE
Move the dashboard and loader to its own github repository

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#15266]
### Describe the solution you'd like
Move the dashboard and loader  to its own github repository. It allows us decrease build time.

**Comment by vparfonov** [comment]
According to this https://github.com/eclipse/che/issues/15294, we will postpone this issue

**Comment by sparkoo** [comment]
by any chance, is this going to happen anytime soon ?

**Comment by nickboldt** [comment]
Please do not do any major refactoring/reorganizing of Che, or breaking/updating build processes until AFTER 7.9.0 is live. Can be scheduled for 7.10  or 7.11 so it's at the start of the next quarter.

Need a stable 7.9.x release process for CRW 2.1.

**Comment by skabashnyuk** [comment]
@nickboldt to make it double safe, let's plan it for 7.11. Not earlier. So it means `month +`

CC @sleshchenko

**Comment by skabashnyuk** [comment]
Request for new Github repositories has been sent https://bugs.eclipse.org/bugs/show_bug.cgi?id=560008
