### ISSUE TITLE
regression: my workspace view tooltip on Che commands is not showing up anymore

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15260]
### Describe the bug
The feature describe here https://github.com/eclipse/che-theia/pull/431 was working in 7.2.0 But not working anymore.

### Che version

 - [x] latest

### Steps to reproduce
1. Open a workspace with commands
2. Move the mouse to my workspace view on top of a command
3. a tooltip should show up with the command script but it does not.

**Comment by vitaliy-guliy** [comment]
Already fixed in Theia upstream.
