### ISSUE TITLE
Openshift connector and Che: the openshift connector should detect projects with .odo folder already created.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15271]
### Describe the bug
When I create a component with the openshift connector, it is suggesting which project i should use. But I cannot see the one I have previously created with the connector or the one I have created from the odo cli.
When I try to reuse a existing project with .odo folder, the connector do not allow it.

The workaround is to remove the .odo folder and recreate the component

### Che version

 - [x] latest

### Runtime
   - [x] Openshift 4.2

### Installation method
   - [ ] che-operator

**Comment by azatsarynnyy** [comment]
As I remember, it's an upstream issue. @sunix could you check in VS Code, please?

**Comment by sunix** [comment]
maybe could be fixed with https://github.com/eclipse/che/issues/15347

**Comment by sunix** [comment]
it is maybe related to the fact that we do not keep state of the extension after restart.

**Comment by ericwill** [comment]
> it is maybe related to the fact that we do not keep state of the extension after restart.

Should be fixed now as we have `.kube` volume, no?
