### ISSUE TITLE
[che-operator] - enable support git clone for repositories with self-signed SSL certs

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#15285]
### Is your enhancement related to a problem? Please describe.
In #15218 was introduced ability support git operations for self signed SSL certificates.   
For now, we need to provide ability setup this feature via che-operator.

**Comment by tsmaeder** [comment]
Why only the operator? We have other ways to install che, right?

**Comment by vparfonov** [comment]
@tsmaeder for Helm chart docs already in PR https://github.com/eclipse/che-docs/pull/936

**Comment by slemeur** [comment]
@vparfonov : I don't think we should close the epic if this has not been handled yet. It should have been listed as subtask of the epic: https://github.com/eclipse/che/issues/14527

**Comment by tolusha** [comment]
/cc @azatsarynnyy 
Are you going to work on it?
