### ISSUE TITLE
MySQL TCK might hang

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15287]
### Is your task related to a problem? Please describe.
On my local machine, the MySQL TCK hangs.

### Describe the solution you'd like
The detection made by the docker maven plugin for "readiness" of the image seems to be the culprit.

Currently, it is configured as:
```xml
<wait>
  <log>ready for connections</log>
  <time>60000</time>
</wait>
```
while the log message appears in the output of my running container and the docker maven plugin correctly catches the message and lets the build continue, it seems that the testsuite is started before the tests actually can make any connection to the server and the testsuite hangs right after the start without executing a single test.

If I change the docker maven plugin configuration to:
```xml
<wait>
  <tcp>
    <ports>
      <port>3306</port>
    </ports>
  </tcp>
  <time>60000</time>
</wait>
```

It seems that the docker maven plugin waits a little bit longer and the testsuite is able to actually establish the connection and run the tests successfully.

However there is apparently some kind of issue with the above code on MacOS, which I **think** is resolved by changing it to:

```xml
<wait>
  <tcp>
    <mode>mapped</mode>
    <ports>
      <port>3306</port>
    </ports>
  </tcp>
  <time>60000</time>
</wait>
```

### Additional context
This obviously is specific to my machine, because our CI runs the tests just fine. This seems to be a kind of race condition rather than a hard bug.

We've changed the detection a couple of times in the past already, but each time, it was bundled within a larger commit without actually explaining why this change was made. I assume each configuration has its own deal of problems on different platforms. We should settle on a configuration that works on all platforms used by devs (Linux, MacOS) and the CI as well.

**Comment by skabashnyuk** [comment]
Duplicate https://github.com/eclipse/che/issues/14939
