### ISSUE TITLE
Setting `CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN` does not work

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#15289]
### Describe the bug

I have a Che devfile that downloads a relatively large VS Code extension from http://download.eclipse.org/. I'm finding that it takes long enough to cause the workspace startup to occasionally timeout. I saw that there is a `CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN` property and I set that in the `cheCustomProperties` field in the CheCluster yaml. However, I'm still finding that the workspace still times out at around 2 minutes, regardless of the value I set in there. 

Is there another field that I need to be setting, or is there an issue with the `CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN` property not working?

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Given that this relies upon a slow network connection, it may be hard to reproduce but:

1. Set `CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN` to some value, such as "5" or "10"
2. Create a workspace from some devfile which requires a lot of downloads.
3. If the workspace creation is still going at around the 2 minute mark, it will fail, despite the property being set

### Expected behavior

The timeout for workspace start gets set to the proper value

### Runtime
   - [] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
❯ oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.14-201908291507+ec04ac2-dirty", GitCommit:"ec04ac2", GitTreeState:"dirty", BuildDate:"2019-08-29T23:30:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```
### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
```
chectl server:start ----che-operator-cr-yaml=<devfile>
```

**Comment by skabashnyuk** [comment]
Hello @johnmcollier . thank you for this report.  Can you take a look in che-master container and ensure that exactly value is set for `CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN` with `env|grep CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN`.  Because default is 8 minutes https://github.com/eclipse/che/blob/e3bc0a0bdab5df5b0da7ed49fc0371ee2e015852/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L268-L269

**Comment by johnmcollier** [comment]
@skabashnyuk Thanks for replying!

It returns the proper value for me, which tells me it's at least being set properly by the operator when I install Che.

I looked through Che.properties further and found another property, this time for the plugin broker: `che.workspace.plugin_broker.wait_timeout_min`
https://github.com/eclipse/che/blob/e3bc0a0bdab5df5b0da7ed49fc0371ee2e015852/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L490

That would align with the timeouts I'm seeing (roughly 2-3 minutes), and during the plugin broker stage.

I'll test with increasing this property and close this issue if it works for me.

**Comment by johnmcollier** [comment]
This worked, closing out. Thanks!
