### ISSUE TITLE
Self-signed certificate mode does not work

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15295]
### Describe the bug
Self-signed certificate mode does not work.

Che Server pod crashed with the following error message
```
Using embedded assembly.
Found a custom cert. Adding it to java trust store based on /usr/local/openjdk-8/jre/lib/security/cacerts
cp: cannot stat '/usr/local/openjdk-8/jre/lib/security/cacerts': No such file or directory
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy nightly Che with self-signed tls, `chectl server:start --platform=openshift --installer=operator --tls --self-signed-cert`

### Expected behavior
Che is successfully deployed.

### Expected behavior
Che container crashes.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by slemeur** [comment]
What is the version(s) concerned by this bug?
