### ISSUE TITLE
Move Che release job from Codenvy CI to the CentOS CI 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#15294]
### Is your task related to a problem? Please describe.
Codenvy CI not support well at the moment, so we need to move to other toll.

**Comment by skabashnyuk** [comment]
- Have you considered Github Actions?
- Does CentOS CI mean Eclipse CI https://ci.eclipse.org/che/?
- What are the level of publicity of it? Is there a way for non-RedHat Eclipse Che committer to release something?

**Comment by vparfonov** [comment]
> * Have you considered Github Actions?
> * Does CentOS CI mean Eclipse CI https://ci.eclipse.org/che/?
No, CentOS CI means https://ci.centos.org/, like it done for che-machine-exec
> * What are the level of publicity of it? Is there a way for non-RedHat Eclipse Che committer to release something?
For sure, it will be not public

**Comment by benoitf** [comment]
Using Eclipse CI will allow any Eclipse Che committer to trigger jobs.

**Comment by ibuziuk** [comment]
@vparfonov can we close the issue?
