### ISSUE TITLE
Add debug action to devfile used in Happy Path tests

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#15297]
### Is your task related to a problem? Please describe.
Happy Path test is currently adding launch/debug configuration by directly editing `launch.json` file.
We should modify the devfile to add that configuration directly (so no further edition of `launch.json` file is needed in the running workspace).

### Describe the solution you'd like
Here is example of how this can be achieved: https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-web-spring/devfile.yaml#L54

### Additional context
This is followup of https://github.com/eclipse/che/issues/15183

**Comment by ibuziuk** [comment]
@rhopp why this is considered to be a blocker?

**Comment by rhopp** [comment]
@ibuziuk TL;DR version - Happy Path test is failing and this is to workaround the problem (and after discussion with @l0rd it's preferred way anyway). Anything that breaks Happy Path should be considered as blocker and should have top priority for fixing.

Longer version:
Current implementaition of Happy Path is using LS capabilities to populate `launch.json` with debug config. This is broken right now (che issue: https://github.com/eclipse/che/issues/15183, upstream theia issue: https://github.com/eclipse-theia/theia/issues/6542). As it appeared, that fix will take a bit longer, I've created (after discussion with Mario) this issue. Now I can see, that fix for the root cause is on the way - when it lands in our lands, we could lower the severity of this issue, as Happy Paths should not fail on this anymore.

**Comment by dmytro-ndp** [comment]
Looks like the issue https://github.com/eclipse/che/issues/15183 has been fixed https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/3398/

**Comment by dmytro-ndp** [comment]
Happy path tests are unstable on reading config from json:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/593/consoleFull
```
 ✓ Launch debug (20340ms)
        ▼ PreviewWidget.waitAndSwitchToWidgetFrame
        ▼ PreviewWidget.waitAndClick By(css selector, button[data-target='#main-navbar'])
        ▼ PreviewWidget.waitAndClick By(xpath, //div[@id='main-navbar']//span[text()='Error'])
        ▼ PreviewWidget.waitVisibility By(xpath, //p[text()='Expected: controller used to showcase what happens when an exception is thrownHHHHHHHHHHHHH'])
        ▼ Ide.waitAndSwitchToIdeFrame
    ✓ Check content of the launched application (1340ms)
        ▼ TopMenu.selectOption "Debug"
        ▼ TopMenu.clickOnTopMenuButton "Debug"
        ▼ Ide.closeAllNotifications
        ▼ TopMenu.clickOnSubmenuItem "Open Configurations"
        ▼ Editor.waitEditorAvailable "launch.json"
        ▼ Editor.waitTab "launch.json"

    1) Open debug configuration file
  22 passing (16m)
  1 pending
  1 failing
  1) Validation of debug functionality
       Open debug configuration file:
     TimeoutError: Waiting for element to be located By(xpath, //li[contains(@class, 'p-TabBar-tab')]//div[text()='launch.json'])
Wait timed out after 300012ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: Waiting for element to be located By(xpath, //li[contains(@class, 'p-TabBar-tab')]//div[text()='launch.json'])
```
![screenshot-Open_debug_configuration_file](https://user-images.githubusercontent.com/1197777/69621807-71bb2000-1048-11ea-8fc3-19057bd712a6.png)

**Comment by Katka92** [comment]
I was not able to get it running correctly. My changes are in my branch `fix_debug_config`. https://github.com/eclipse/che/compare/master...Katka92:fix_debug_config?expand=1

**Comment by rhopp** [comment]
This was done some time ago. Debug is now part of Happy Path.
