### ISSUE TITLE
Show hidden files in project explorer

### ISSUE THREAD

**Issue by jlewi** [eclipse-che/che#1529]
The project explorer doesn't appear to show hidden files like .gitignore. Is there an option to enable showing hidden files?

**Comment by TylerJewell** [comment]
Show and hide hidden files is an option in the ide menu.

**Comment by jlewi** [comment]
Thanks for the response. Where's the IDE menu? When I open the IDE the menus I see are

Workspace
Project
Machine
Edit
Assistant
Run
Profile
Git
Subversion
Help

Profile > Preferences is where I would have expected it but I didn't see an option to show hidden files.
Under Preferences there is an IDE tab which has Editor and Appearance. 

I'm using Eclipse Che 4.3.2

**Comment by TylerJewell** [comment]
Hidden files would be considered a project-level attribute, so you should see it in Project or Edit menu.  If it's not there, then something else is going wrong.  Have you set the project type to something other than blank?

**Comment by jlewi** [comment]
I see it now under the Project menu. Thank you.
