### ISSUE TITLE
cache_images.sh will be failed in case the registry have multiple icons.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#15293]
### Describe the bug

`cache_images.sh` will be failed when  `meta.yaml` by third party was added.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Add new `meta.yaml` with `icon:` not pointing `https://www.eclipse.org/che/images/logo-eclipseche.svg`
2. Build image.

The build failure of my forked devfile-registry. 
https://dev.azure.com/pizzafactory/camino/_build/results?buildId=1476&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b&lineStart=517&lineEnd=518&colStart=1&colEnd=1

### Expected behavior

Finishing the build with success.

### Additional context

I've already fixed this issue. I'm going to send PR.

**Comment by ibuziuk** [comment]
@amisevsk could you please take a look and comment?

**Comment by amisevsk** [comment]
Fixed for 7.6.0 and 7.3.3
