### ISSUE TITLE
Provide information about available/used resources for the user's namespace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15305]
### Is your task related to a problem? Please describe.

Now when we have the ability to provide a list of namespaces available for the user to create a workspace, it would be nice
to provide also information about available/used resources for the user's namespace.

### Describe the solution you'd like
Namespace API should provide information about available/used resources
 - CPU
 - Memory
 - PV
 - Secrets   

### Describe alternatives you've considered
n/a
### Additional context
```bash
 oc describe quota object-counts                                                                          
Name:                   object-counts
Namespace:              skabashn-che
Resource                Used  Hard
--------                ----  ----
persistentvolumeclaims  1     2
replicationcontrollers  0     20
secrets                 18    20
services                0     15
```
```bash
Name:       compute-resources
Namespace:  skabashn-che
Scopes:     NotTerminating
 * Matches all pods that do not have an active deadline. These pods usually include long running pods whose container command is not expected to terminate.
Resource       Used  Hard
--------       ----  ----
limits.cpu     0     16
limits.memory  0     8Gi
```

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/13504
