### ISSUE TITLE
Client has aborted connection. Response writing omitted.Help! 

### ISSUE THREAD

**Issue by stoneqsl** [eclipse-che/che#1530]
STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2016-06-20 07:44:07,394[main] [INFO] [o.a.c.s.VersionLoggerListener 89] - Server version: Apache Tomcat/8.0.32
[STDOUT] 2016-06-20 07:44:07,400[main] [INFO] [o.a.c.s.VersionLoggerListener 91] - Server built: Feb 2 2016 19:34:53 UTC
[STDOUT] 2016-06-20 07:44:07,403[main] [INFO] [o.a.c.s.VersionLoggerListener 93] - Server number: 8.0.32.0
[STDOUT] 2016-06-20 07:44:07,403[main] [INFO] [o.a.c.s.VersionLoggerListener 95] - OS Name: Linux
[STDOUT] 2016-06-20 07:44:07,404[main] [INFO] [o.a.c.s.VersionLoggerListener 97] - OS Version: 3.10.0-327.18.2.el7.x86_64
[STDOUT] 2016-06-20 07:44:07,405[main] [INFO] [o.a.c.s.VersionLoggerListener 99] - Architecture: amd64
[STDOUT] 2016-06-20 07:44:07,407[main] [INFO] [o.a.c.s.VersionLoggerListener 101] - Java Home: /opt/jdk1.8.0_45/jre
[STDOUT] 2016-06-20 07:44:07,409[main] [INFO] [o.a.c.s.VersionLoggerListener 103] - JVM Version: 1.8.0_45-b14
[STDOUT] 2016-06-20 07:44:07,410[main] [INFO] [o.a.c.s.VersionLoggerListener 105] - JVM Vendor: Oracle Corporation
[STDOUT] 2016-06-20 07:44:07,413[main] [INFO] [o.a.c.s.VersionLoggerListener 107] - CATALINA_BASE: /home/user/che/ws-agent
[STDOUT] 2016-06-20 07:44:07,417[main] [INFO] [o.a.c.s.VersionLoggerListener 109] - CATALINA_HOME: /home/user/che/ws-agent
[STDOUT] 2016-06-20 07:44:07,421[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2016-06-20 07:44:07,422[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2016-06-20 07:44:07,428[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Xms256m
[STDOUT] 2016-06-20 07:44:07,428[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Xmx1024m
[STDOUT] 2016-06-20 07:44:07,429[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2016-06-20 07:44:07,433[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2016-06-20 07:44:07,434[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2016-06-20 07:44:07,435[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2016-06-20 07:44:07,444[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2016-06-20 07:44:07,444[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2016-06-20 07:44:07,444[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2016-06-20 07:44:07,444[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2016-06-20 07:44:07,444[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2016-06-20 07:44:07,445[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2016-06-20 07:44:07,455[main] [INFO] [o.a.c.s.VersionLoggerListener 115] - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2016-06-20 07:44:07,911[main] [INFO] [o.a.c.http11.Http11NioProtocol 425] - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-06-20 07:44:07,941[main] [INFO] [o.a.t.util.net.NioSelectorPool 72] - Using a shared selector for servlet write/read
[STDOUT] 2016-06-20 07:44:07,944[main] [INFO] [o.a.catalina.startup.Catalina 591] - Initialization processed in 909 ms
[STDOUT] 2016-06-20 07:44:07,973[main] [INFO] [c.m.JmxRemoteLifecycleListener 332] - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2016-06-20 07:44:07,974[main] [INFO] [o.a.c.core.StandardService 435] - Starting service Catalina
[STDOUT] 2016-06-20 07:44:07,974[main] [INFO] [o.a.c.core.StandardEngine 259] - Starting Servlet Engine: Apache Tomcat/8.0.32
[STDOUT] 2016-06-20 07:44:08,033[ost-startStop-1] [INFO] [o.a.c.startup.HostConfig 910] - Deploying web application archive /home/user/che/ws-agent/webapps/wsagent.war
[STDOUT] 2016-06-20 07:44:12,825[s polled Thread] [INFO] [o.e.c.p.m.server.rmi.RmiClient 130] - Port/Name:5882/MavenRemoteServerImplcdf40f81
[STDOUT] 
[STDOUT] Mon Jun 20 07:44:14 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2016-06-20 07:44:15,259[rrest.WSClient1] [INFO] [.c.a.c.n.WSocketEventBusClient 223] - Open connection to ws://che-host:8080/wsmaster/api/eventbus/?token=dummy_token. 
[STDOUT] 2016-06-20 07:44:15,618[ost-startStop-1] [INFO] [o.a.c.startup.HostConfig 974] - Deployment of web application archive /home/user/che/ws-agent/webapps/wsagent.war has finished in 7,585 ms
[STDOUT] 2016-06-20 07:44:15,620[ost-startStop-1] [INFO] [o.a.c.startup.HostConfig 1030] - Deploying web application directory /home/user/che/ws-agent/webapps/ROOT
[STDOUT] 2016-06-20 07:44:15,718[ost-startStop-1] [INFO] [o.a.c.startup.HostConfig 1142] - Deployment of web application directory /home/user/che/ws-agent/webapps/ROOT has finished in 98 ms
[STDOUT] 2016-06-20 07:44:15,736[main] [INFO] [o.a.c.http11.Http11NioProtocol 470] - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-06-20 07:44:15,755[main] [INFO] [o.a.catalina.startup.Catalina 642] - Server startup in 7809 ms
[STDOUT] 2016-06-20 07:44:16,303[nio-4401-exec-2] [WARN ] [i.ContainerResponse$BodyWriter 90] - Client has aborted connection. Response writing omitted.
[STDOUT] 2016-06-20 07:44:16,303[nio-4401-exec-1] [WARN ] [i.ContainerResponse$BodyWriter 90] - Client has aborted connection. Response writing omitted.
[STDOUT] 2016-06-20 07:44:16,985[nio-4401-exec-7] [ERROR] [c.s.o.RemoteOAuthTokenProvider 72] - Exception on token retrieval, message : Unsupported OAuth provider github
[STDOUT] 2016-06-20 07:44:21,418[nio-4401-exec-7] [ERROR] [c.s.o.RemoteOAuthTokenProvider 72] - Exception on token retrieval, message : Unsupported OAuth provider github

I use the 14.3.0 che. I cann't fix this problem

**Comment by TylerJewell** [comment]
@stoneqsl - closing the issue.  To keep things sane and manageable, we are asking all issues to be posted following the reporting issues guidelines.  You can open a new issue that follows these guidelines.
https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#reporting-issues
