### ISSUE TITLE
"404 Not found" for welcome page

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15318]
### Che version

 - [x] latest Che-Theia@8f867f2 using Theia@98ac397 Built 11/26/2019, 9:40:08 AM
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace (tried with a custom one and with java-maven)

workaround: refresh browser

### Expected behavior
have the correct welcome page since the beginning

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2019-11-26 13-34-48](https://user-images.githubusercontent.com/1105127/69633981-94056b80-1051-11ea-8c62-4daa12b604dd.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by RomanNikitenko** [comment]
Looks like it's related to https://github.com/eclipse/che/issues/15283
@mmorhun

**Comment by mmorhun** [comment]
I think it is a different problem, because in case of the https://github.com/eclipse/che/issues/15283 simple refresh won't help.

**Comment by RomanNikitenko** [comment]
For me refreshing a page doesn't help to restore welcome page

**Comment by l0rd** [comment]
I am assuming that after @apupier refreshes, the readme.md is loaded, not the welcome page. That's why he says that it works but it's just a different tab. 

I am keeping it open anyway until we fix #15283.

**Comment by apupier** [comment]
> I am assuming that after @apupier refreshes, the readme.md is loaded, not the welcome page. That's why he says that it works but it's just a different tab.

right...
my bad, so it is really a duplicate
