### ISSUE TITLE
Helm chart always deploys nightly versions of devfile and plugin registries

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15310]
### Describe the bug
Helm chart obtained from the `7.3.2` tag correctly deploys the `7.3.2` image of the che server, but the it deploys nightly versions of devfile and plugin registry.

### Che version
latest

### Steps to reproduce
1. `cd <CHE_CLONE_DIR>`
1. `git checkout 7.3.2`
1. `helm upgrade --install che --namespace che --set global.ingressDomain=$(minikube ip).nip.io deploy/kubernetes/helm/che`
1. `kubectl get deployments -n che -o wide`

### Expected behavior
The versions should be `quay.io/eclipse/che-devfile-registry:7.3.2` for the `devfile-registry` deployment and `quay.io/eclipse/che-plugin-registry:7.3.2` for the `plugin-registry`.

### Runtime
   - kubernetes (include output of `kubectl version`) 
```
$ kubectl version                                       
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
   - minikube (include output of `minikube version` and `kubectl version`)
```
$ minikube version                                                                      
minikube version: v1.5.1
commit: 4df684c4cc2bd9dc9979cd5dbb44bdfa410850b4
```

**Comment by tolusha** [comment]
Not the case anymore.
chectl 7.11.0

![Screenshot from 2020-04-12 15-23-06](https://user-images.githubusercontent.com/1640675/79068945-322d6180-7cd3-11ea-88b1-09fa0a351881.png)
