### ISSUE TITLE
Update vert.x default sample

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#15314]
### Is your task related to a problem? Please describe.
The sample project is based on an older version version of Vert.x that likely has several CVEs, but most importantly it is essentially a Spring application with Vert.x inside with many wrong usages: blocking operations because of Spring Data, raw HTTP dispatch rather than using a router, etc.

### Describe the solution you'd like
Replace the default vert.x sample by:  https://github.com/openshiftio-vertx-boosters/vertx-http-booster 

### Additional context
Raised by vert.x team.

**Comment by tsmaeder** [comment]
According to @slemeur we have a better example in CRW. It uses this repo: https://github.com/openshiftio-vertx-boosters/vertx-http-booster
We can take over that example, but make sure we don't have any dependencies on Red Hat products.

**Comment by tsmaeder** [comment]
The new sample should replace the Java-Web-Vertx sample, as far as I'm concerned.

**Comment by ibuziuk** [comment]
There is also https://github.com/openshift-vertx-examples/vertx-http-example.git which is used in the https://github.com/redhat-developer/devfile/tree/master/getting-started/vertx for "getting-started" devfiles. Please, consider updating this one also
