### ISSUE TITLE
Unreadable black on black text for 404 when accessing missing logs of Kubernetes

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15316]
### Describe the bug

black text on black background in some cases

workaround: use the light theme

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace with Kubernetes extension available
2. Access log of a pod which is unreachable (don't know in which cases it happens exactly :-()
3. The loaded page is a 404 Not Found with black text written on a black background

### Expected behavior

have something readable wit the default theme

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2019-11-26 11-37-26](https://user-images.githubusercontent.com/1105127/69622400-294c3400-1041-11ea-910d-ceca1480ee46.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by apupier** [comment]
there is the sameeisseu when the Che welcome page is returning a 404

**Comment by ericwill** [comment]
Do you still experience this @apupier ?
