### ISSUE TITLE
Update memoryLimit of plugin registry to use Gi format instead of G

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15326]
### Is your task related to a problem? Please describe.

for instance on the VS Code Camel K extension:  https://github.com/eclipse/che-plugin-registry/pull/284#discussion_r350832822

**Comment by l0rd** [comment]
@apupier why is this a problem? Is this now required starting from a given version of Kubernetes or OpenShift? Are you going to provide the fix?

**Comment by apupier** [comment]
> why is this a problem? Is this now required starting from a given version of Kubernetes or OpenShift?

no idea.
it is a suggestion from @amisevsk , so I forward the question to you :-)

**Comment by amisevsk** [comment]
I was mostly specifying in a PR review that many of our existing plugins use `Gi` and suggested using that instead of `G` for consistency.
