### ISSUE TITLE
Rework che-theia branding to provide logo icon for plugin webview

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15324]
### Is your task related to a problem? Please describe.
After change web-view https://github.com/eclipse-theia/theia/pull/6465, webview doesn't have access to the resources outside plugin.

![image](https://user-images.githubusercontent.com/1636395/72801616-8a177780-3c52-11ea-94a7-9c08a47608a9.png)

### Describe the solution you'd like
We need to rework che-theia branding to provide logo icon for plugin web-view.

**Comment by AndrienkoAleksandr** [comment]
Related to https://github.com/eclipse/che/issues/15324

**Comment by AndrienkoAleksandr** [comment]
Hello, @benoitf we taked about fix for this issue on the planing. Proposed solution: we apply method to the che plugin api which should return logo content encoded in base64 and than we can easily display this icon in the welcome plugin. @benoitf Such solution is ok for you?

**Comment by benoitf** [comment]
yes

**Comment by benoitf** [comment]
do you have ETA of the size of the logo encoded in base64 ?

**Comment by AndrienkoAleksandr** [comment]
> @benoitf do you have ETA of the size of the logo encoded in base64 ?

~ 12K

**Comment by vitaliy-guliy** [comment]
@l0rd could we assign it to Plugins team?

**Comment by nickboldt** [comment]
This is a blocker for CodeReady Workspaces 2.1 and a regression over 2.0. 

Please escalate this so we can get it into 7.9.1, as this is a terrible OOTB visual experience. 

Alternatively, please provide a way to suppress the icon entirely as it's really not that meaningful or needed. 

BTW I thought 7.9.0 was supposed to be about hardening and UX fixes. How did this obvious UX problem fall through the cracks for 3 months?

**Comment by scela** [comment]
@nickboldt how exactly is this a blocker? I don't really want to hear people's own opinion and musings but we have an agreement that blocker means 'Causes system to crash and be non-recoverable or prevents Che developers from working on Che code'. If we all start barging in with our ideal 'blocker' definition it will get pretty crowded.

And it didn't fall through any crack - it was just not prioritized. If you think it should have been you are most welcome to join us when we prioritize as we are good listeners.
