### ISSUE TITLE
non workspace machines don't have project code

### ISSUE THREAD

**Issue by jlewi** [eclipse-che/che#1533]
I'd like to create a custom recipe in which I use to create runtimes to execute my code. (I need to install a bunch of python dependencies like Tensorflow).

I created a custom recipe and create a machine from that recipe. 
However, when I start a terminal in that machine my code isn't sync'd into /projects.

I tried this with the debian8_jdk recipe to make sure it wasn't my recipe.

Is it possible to have multiple machines running that are syncing the project code?

Thanks
J

**Comment by TylerJewell** [comment]
This is not possible today.  Only a single machine designated the dev machine gets the project sync.  In the future when we support compose like syntax for defining workspaces we will reconsider providing a mapping of source to different machines.

**Comment by jlewi** [comment]
Thanks.
Any chance there's any easy way to mount host volumes into a machine's container?

Current use case is as follows:
- My code uses [TensorFlow](https://www.tensorflow.org/)
- My code is triggering a bug in TensorFlow
- I'd like to build a debug version of TensorFlow 
- Build a docker image with my debug version of TensorFlow
- Try my code in that container

It would be really nice if I could just do this by 
- Having a separate workspace/project for modifying/building TensorFlow
- A separate machine in my WS to test my code using the new version of TensorFlow.

I'd rather not have to replace the WS machine.

**Comment by TylerJewell** [comment]
@james10174 - James Drummond has been doing a lot with mounting host volumes into machines. He may have the quickest answer.

**Comment by james10174** [comment]
@jlewi You can make use of adding machine.server.extra.volume=/host/dir:/container/dir in conf/che.properties. This is global for any workspace created and is limited to one mount.

Also, you could also use my script to sshfs mount into workspace. Make sure you set privileged to true in conf/che.properties then start che server. 

```
##From machine you that has folder you want to mount on che workspace.
git clone https://bitbucket.org/james10174/usefulscripts.git
cd usefulscripts/SSH\ Mount\ Artik\ or\ Raspberry\ PI\ or\ Beaglebone\ to\ Server/
##Make sure scp and sshpass are installed.


#./sshServer.sh <server user> <server ipaddress> <device folder to share/mount> <server mount folder> <host user> <server ssh port> <server port forwarded>
###Example###
./sshServer.sh root  <server ipaddress> / /mnt/remoteDevice/ user  <server ssh port> 2000 new &


#After the first time using sshServer.sh use the following without new at end to speed things up
./sshServer.sh root  <server ipaddress> / /mnt/remoteDevice/ user  <server ssh port> 2000 &
```

```
Get <server ipaddress> and <server ssh port> from the following.
```

![image](https://cloud.githubusercontent.com/assets/16562450/16275804/403a5f76-3871-11e6-859a-b3954081b459.png)

**Comment by jlewi** [comment]
@james10174  Thanks James.  machine.server.extra.volume only mounted the volume inside my workspace machine. I really want to mount it in additional machines not the workspace machine. I want to be able to change the machine configuration but I don't want to mess with the workspace machine because if I make a mistake misconfigure the container I don't want to hose my workspace.

**Comment by ghost** [comment]
@jlewi right now it is possible to provide one additional volume for a workspace machine only. 

I have labeled this issue an enhancement.

**Comment by jlewi** [comment]
@eivantsov  SGTM. Thank you.

**Comment by james10174** [comment]
@jlewi Sorry I am not following where the different machines are. Are you creating an addition container on your host machine that is running the che server or inside the workspaces? What command line are you using to start che.

**Comment by jlewi** [comment]
@james10174  I create additional machines(docker containers) in my Che workspace. Specifically I go the machines view and create a new machine from some recipe. In the create menu I don't click the button to replace my dev machine.

**Comment by TylerJewell** [comment]
@jlewi - sorry about the long delay.  A number of improvements are now part of 5.0.0-M1 release. It's tagged and available for download, but we have not shipped it with broad support yet.
1. We now support compose file syntax for workspaces with multiple machines.
2. You can now mount multiple volumes into a workspace.
3. We also package up our "dev services" which are things like terminal and intellisense into agents, which can be deployed into multiple machines.

Our docs are still coming along, but they are moving quickly. Also, we have good docs in each of the pull requests where this was merged (look at all PRs for the M1 milestone).

**Comment by jlewi** [comment]
Thank you very much.
