### ISSUE TITLE
Rework welcome plugin to don't use styles from theia DOM

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15334]
### Is your task related to a problem? Please describe.
Welcome plugin used some styles from theia dom, but after rework theia webview, this plugin don't have access any more to the theia DOM styles.

### Describe the solution you'd like
We need rework welcome plugin styles to save previous look.

**Comment by benoitf** [comment]
Hello @beaumorley 

Following a change in upstream product, our welcome page rendering is now:
![image](https://user-images.githubusercontent.com/436777/69650534-09336980-106f-11ea-8082-48f370037f94.png)

while it was before:
![image](https://user-images.githubusercontent.com/436777/69651369-43513b00-1070-11ea-8733-1ac40296cf33.png)

as we need to work again on it, do you have ideas on how to make this welcome page better ?

**Comment by azatsarynnyy** [comment]
Setting label `area/plugins` as it's related to https://github.com/eclipse/che-theia/tree/master/plugins/welcome-plugin

**Comment by AndrienkoAleksandr** [comment]
Maybe we can close this issue, since previous  welcome plugin look was recovered ?
