### ISSUE TITLE
Define and document backup and restore procedure

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15349]
### Is your enhancement related to a problem

There is no documentation about how users can backup and then restore
- Che server data
- Che workspaces data

### Describe the solution you'd like

It would be recommended to leverage some existing Kubernetes backup solution as [Velero](https://github.com/vmware-tanzu/velero)

**Comment by ibuziuk** [comment]
@l0rd can we merge this issue with https://github.com/eclipse/che/issues/14240 ?

**Comment by l0rd** [comment]
Merged with https://github.com/eclipse/che/issues/14240
