### ISSUE TITLE
Provide decent error message when the operator is missing cluster permissions 

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15345]
### Is your enhancement related to a problem? Please describe.

The problem is that, in some tricky use-cases, a deployed Che operator might miss the cluster role bindings that are required for Openshift OAuth integration to work correctly.

In such a case, the operator simply does nothng and doesn't react correctly to custom resources, but without issuing any error message either in the logs or on the `CheCluster` custom resource.   

### Describe the solution you'd like

Such abnormal situations hsould be detected by the operator when reconciling a custom resource, and an appropriate error message + possible link to troubleshooting docs should be added in the custom resource status. 

### Additional context

https://issues.jboss.org/browse/CRW-505?focusedCommentId=13816159&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13816159

**Comment by tolusha** [comment]
@davidfestal 
Is it in progress?

**Comment by davidfestal** [comment]
> @davidfestal
> Is it in progress?

No, we did not have time to start working on it until now.

**Comment by AndrienkoAleksandr** [comment]
Merget Add error status if operator hasn't got permission to count users.
