### ISSUE TITLE
How can I make my project type  extension  to extends MAVEN project type ??

### ISSUE THREAD

**Issue by Madixin** [eclipse-che/che#1535]
I am working on Eclipse che recently ,and I have to say this is a great project.But I have an issue for project type extension.

I have built a new project type extension and had it deployed in the che server. After create a new project with my new project type wizzard,  I have to configure the project type to java or maven project type, so it can have JAVA feature .

How can I make my project type  extension  to extends MAVEN project type ??

**Comment by vparfonov** [comment]
Hi, for just extending Maven Project Type you just need to add  addParent(MAVEN); in you project type descriptor. 

If you need some additional modification with wizard so please lock here this simple example taht illustrate how to add new project type with wizard in Che 

https://github.com/vparfonov/plugin-sample-wizard

**Comment by ghost** [comment]
@42690727 please let us know if it helps. Do not hesitate to elaborate on your particular use case and goals.

**Comment by Madixin** [comment]
The project type I extended needs both maven feature and java feature. I followed your advice, added addParent(MavenAttributes.MAVEN_ID) in my ProjectTypeDef class. 
But I got this error message after I added addParent(MavenAttributes.MAVEN_ID) while the wsagent is booted:

**Attribute name conflict. Project type XXXX could not be registered as attribute declaration java.source.folder is duplicated in its ancestor(s).**

But I did not add attribute java.source.folder to my ProjectTypeDef.
However I just try to added addParent(JAVA_ID) in my ProjectTypeDef class, the extension can run properly without throwing error message.

Then I checked out the source code of che \wsagent\che-core-api-project\src\main\java\org\eclipse\che\api\project\server\type\ProjectTypeRegistry.java ,changed the parameter "old.getId()" to "old.getProjectType() "in line 270, then my project type extension can run properly.(old.getId() in AbstractAttribute.class returns a string "projectType + ':' + name" rather than a project type)

```
myType.attributes.put(old.getName(), new Variable(old.getId(),old.getName(), old.getDescription(), old.isRequired(), entry.getValue()));
TO myType.attributes.put(old.getName(), new Variable(old.getProjectType(), old.getName(),old.getDescription(),old.isRequired(),entry.getValue()));
```

So do I addParent(MavenAttributes.MAVEN_ID) in the right way? Or there is a bug in ProjectTypeRegistry.java

**Comment by Madixin** [comment]
@eivantsov     @vparfonov

**Comment by vparfonov** [comment]
Hi sorry for delay can you share you code? I want to try it

**Comment by Madixin** [comment]
``` java
public class SwaggerProjectTypeDef extends ProjectTypeDef {

    @Inject
    public SwaggerProjectTypeDef(MavenValueProviderFactory mavenValueProviderFactory) {
        super(Constants.SWAGGER_PROJECT_TYPE_ID, Constants.SWAGGER_PROJECT, true, false,true);
//      addConstantDefinition(Constants.LANGUAGE,  Constants.SWAGGER_PROJECT,Constants.SWAGGER_PROJECT_TYPE_ID);
        addVariableDefinition(Constants.PROJECT_TYPE, "", /*required*/ true);
        addVariableDefinition(Constants.INTERFACE_MATE, "", /*required*/ false);
        addVariableDefinition(Constants.PACKAGE_NAME, "", /*required*/ false);



         setValueProviderFactory(SOURCE_FOLDER, mavenValueProviderFactory);
         setValueProviderFactory(OUTPUT_FOLDER, mavenValueProviderFactory);

        addParent(MavenAttributes.MAVEN_ID);

//      addParent(JAVA_ID);


    }

}
```

**Comment by ghost** [comment]
@42690727 looks like there's nothing wrong with your code - no exceptions

**Comment by TylerJewell** [comment]
I just tried this as well - I think this is not a bug. Going to close the issue to clean up the old comments, but if you have further questions ok to post them here.
