### ISSUE TITLE
Local Install Download Button - link returns 404

### ISSUE THREAD

**Issue by intltechventures** [eclipse-che/che#15361]
### Describe the bug
On the main web site: https://www.eclipse.org/che/
The "Local Install" Download button ("Install Eclipse Che on localhost or shared K8S cluster.")
returns a "404 File not found" for this URL:
https://www.eclipse.org/che/docs/quick-start.html

### Che version
 - [ ] latest
 - [ ] nightly
 - [ X] other: please specify

### Expected behavior
Link should work for Local download, should not return a 404.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x ] other: (please specify) - Bad link on main web site
https://www.eclipse.org/che/

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [X ] other: please specify
https://www.eclipse.org/che/

**Comment by slemeur** [comment]
Thanks for reporting the issue @intltechventures
