### ISSUE TITLE
Document che-theia preferences system

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#15362]
We need to document and explain how to use Che-Theia preferences.

**Comment by rkratky** [comment]
@azatsarynnyy, could you please have a look at this? Will your team be in a position to provide some initial docs for this?

**Comment by themr0c** [comment]
Referenced in  https://issues.redhat.com/browse/RHDEVDOCS-2272

**Comment by azatsarynnyy** [comment]
I'm closing it as not relevant anymore.
