### ISSUE TITLE
Can't run as root

### ISSUE THREAD

**Issue by filips123** [eclipse-che/che#15371]
### Describe the bug

I can't run commands as `root` or use `su`.

On default PHP simple stack, this happens:

```bash
bash-4.4 /projects $ sudo su
bash: sudo: command not found
bash-4.4 /projects $ su
su: must be run from a terminal
```

On default Python stack, I can run `su`, but I can't use it because I don't know the password:

```bash
bash-5.0 /projects $ sudo su
bash: sudo: command not found
bash-5.0 /projects $ su
Password: 
su: Authentication failure
```

### Expected behavior

I should be able to run commands as `root` or use `su`.

### Runtime

* Simple PHP stack
* Python stack

### Environment

[Openshift Eclipse Che](https://che.openshift.io/)

### Che version

Che-Theia@ad8e4f4 using Theia@f255f5a8

**Comment by tolusha** [comment]
It isn't supposed to run anything in behalf of root user.
If you need something you have to use a dockerimage with preinstalled software and add it to your workspace configuration (or replace).

```yaml
components:
  - mountSources: true
    type: dockerimage
    alias: dev
    image: '<YOUR_IMAGE>'
```

**Comment by filips123** [comment]
> It isn't supposed to run anything in behalf of root user.

Why? It is useful if you want to quickly install some packages, change some configuration, run other commands...

**Comment by amisevsk** [comment]
Since containers are immutable, installing packages into a container is a strange use-case -- you would have to redo it on every startup. The recommended flow in docker is to configure your container to have all required packages installed in the image itself.

Further, containers as root is a significant security risk, so it is generally not supported by default in Che (it's not even possible to do on OpenShift, and advised against in Kubernetes).

**Comment by filips123** [comment]
How can I configure a container to install packages in the image itself?

Is the only solution (that works on OpenShift) to create an image and publish it to Docker Hub? Ot is there any other solution which doesn't require to publish images to Docker Hub?

**Comment by amisevsk** [comment]
The typical way to include packages in an image is to install them at image build time, e.g. the plugin registry requires a [few packages](https://github.com/eclipse/che-plugin-registry/blob/1e59dfa65a5283d49a6f4eeeb50428468f66642b/build/dockerfiles/Dockerfile#L15).

For running on a cluster (be it k8s or OpenShift), you'll in general need to make an image available *somewhere* -- it doesn't have to be dockerhub; you can always deploy your own container regiistry or use e.g. quay.io. In some cases, you can use the cluster's internal registry, but that is more error prone in general. If you are concerned about publicly sharing your images, dockerhub allows one private repository.

> Publically releasing new image version each time you want to change/add some system package isn't the best solution...

You don't need to release a completely new image, tags on containers are mutable; for instance, image `quay.io/eclipse/che-machine-exec:nightly` is updated every day and devfiles in the nightly builds of the Che devfile registry also reference nightly builds of images. One of the main benefits of containers is that they can independently -- if you and I both pull the machine-exec image, we'll be running the same environment. For example, I use the [`amisevsk/che-server:dev`](https://hub.docker.com/layers/amisevsk/che-server/dev/images/sha256-04bab7b9d26015d42e2a9fb17f405079a5acafe42e50055b2d31c63ac3f39932) for all of my development in Eclipse Che.

**Comment by mingfang** [comment]
we need to be able to run as root.

**Comment by sushant08** [comment]
> we need to be able to run as root.
> Setting `CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER=0` works

How did you implemented it? Can you kindly let me know?

**Comment by sushant08** [comment]
> we need to be able to run as root.
> Setting `CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER=0` works

@mingfang Can you please let me know how you achieved this?

**Comment by sleshchenko** [comment]
@sushant08 Hope the following doc will help you https://www.eclipse.org/che/docs/che-7/advanced-configuration-options-for-the-che-server-component/

**Comment by mingfang** [comment]
@sushant08 
I deploy Eclipse Che using my own Terraform plugin and module.
Here is the specific lines that configures it to run workspaces as root.
https://github.com/mingfang/terraform-k8s-modules/blob/master/examples/eclipse-che/main.tf#L51

**Comment by Kreijstal** [comment]
I think I'm confused, so eclipse-che is not useful for tinkering with systems before you make them docker images?
