### ISSUE TITLE
Failed to start a workspace when deployed Che with minishift addon installer

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15380]
### Describe the bug
Can't start a workspace in Minishift
![screenshot-che-che 192 168 99 118 nip io-2019 12](https://user-images.githubusercontent.com/1271546/69966322-cb2abf80-151e-11ea-8f79-d6fee2aed842.png) 

```log
2019-12-02 14:08:08,958[nio-8080-exec-7]  [ERROR] [o.e.c.w.i.o.p.OpenShiftProject 178]  - Unable to create new OpenShift project due to lack of permissions.HINT: When using workspace project name placeholders, os-oauth or service account with more lenient permissions (cluster-admin) must be used.
--
  | 2019-12-02 14:08:08,961[nio-8080-exec-7]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 481]   - Failure executing: POST at: https://172.30.0.1/apis/project.openshift.io/v1/projectrequests . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:che:che" cannot create projectrequests.project.openshift.io at the cluster scope: no RBAC policy matched. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
  | org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInfrastructureException: Failure executing: POST at: https://172.30.0.1/apis/project.openshift.io/v1/projectrequests . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:che:che" cannot create projectrequests.project.openshift.io at the cluster scope: no RBAC policy matched. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.create(OpenShiftProject.java:182)
  | at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.prepare(OpenShiftProject.java:112)
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. start Minishift `minishift start --profile minishift --cpus 4 --memory 10240 --docker-opt userland-proxy=false`
2. Deploy Che via chectl `chectl server:start -p minishift`
3. Try to create and start a workspace

### Runtime
   - [x] minishift (v1.34.1+c2ff9cb)

### Installation method
   - [x] chectl (chectl/0.0.20191028-next.e762c88 linux-x64 node-v10.17.0)

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
@svor can you try a fresh version of chectl?

**Comment by vparfonov** [comment]
@skabashnyuk I've tried latest one got the same error.
@musienko-maxim also checked and confirm the such behavior

**Comment by svor** [comment]
@skabashnyuk the same result wit `chectl/0.0.20191127-next.97b31fb linux-x64 node-v10.17.0`

**Comment by ibuziuk** [comment]
it might be realated to the fact that chectl 7.5.0 was not released and it was decided to proceed with 7.5.1 respin - https://github.com/eclipse/che/issues/15372

**Comment by skabashnyuk** [comment]
@svor I might suggest you as a workaround to use `--installer=operator` or `-a operator`

**Comment by skabashnyuk** [comment]
at this moment we think that it's related to minishift-addon configuration.

**Comment by svor** [comment]
I used to use single user, with `--installer=operator` I have multiuser - but it isn't a problem for me. So, 
 workaround works for me. Thanks @skabashnyuk

**Comment by sleshchenko** [comment]
It should be fixed by https://github.com/eclipse/che/issues/15380 but I did not test it yet.
So, I believe that this issue can be closed when the PR is merged and newer chectl is tested.
