### ISSUE TITLE
Adapt Hosted Che 'k8s-image-puller' to the upstream needs

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15385]
### Is your enhancement related to a problem?

Image pulling is usually the workspace startup task that takes more time. And a typical Che workspace needs > 7 images to be pulled.

### Describe the solution you'd like

We can pre-pull the default images used by Che workspaces on every node of the Kubernetes cluster where Che is going to run. This is something that we have implemented for the Hosted version of che (che.openshift.io) with the [kubernetes-image-puller](https://github.com/redhat-developer/kubernetes-image-puller).

This issue is to adapt the k8s-img-puller to upstream che (if needed) and add the documentation to use in che-docs.

**Comment by l0rd** [comment]
Related to https://github.com/redhat-developer/rh-che/issues/1428

**Comment by amisevsk** [comment]
This may require some work on the k8s-image-puller side as well, as the default case is designed to support impersonating multiple users through fabric8-oso-proxy. There is a 'local testing' option which is more in line with a common use case, but it should be improved to be more usable.

**Comment by ibuziuk** [comment]
The upstream repo under che-incubator - https://github.com/che-incubator/kubernetes-image-puller

**Comment by ibuziuk** [comment]
I believe we should close the issue once the doc PR is merged

**Comment by ibuziuk** [comment]
@rkratky @themr0c closing this issue - please review the docs PR  eclipse/che-docs#1085
