### ISSUE TITLE
[docs] Some code blocks have syntax highlighting enabled incorrectly.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15387]
## Describe the bug
Some sections of the Che documentation show 'error' highlights if the code contained is technically syntactically incorrect (e.g. no quotes on json fields). 

For example, the Che-Theia plugin metadata section, https://www.eclipse.org/che/docs/che-7/what-is-a-che-theia-plug-in/#che-theia-plug-in-metadata_what-is-a-che-theia-plug-in, shows

![Screenshot from 2019-12-03 02-03-56](https://user-images.githubusercontent.com/16168279/70027909-43ba6c00-1571-11ea-9874-7b8cbe683b83.png)

on both Firefox and Chrome.

I see a similar issue further down the page, in the yaml for

> che-plugin.yaml file for the che-machine-exec plug-in

**Comment by themr0c** [comment]
Indeed, it is confusing to see `json` syntax highlight in a context which is about `meta.yaml`. The provided content is not valid yaml though. I assume it would make sense to update the content with something based upon 2 examples, like:

For a Che-Theia plug-in:
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/eclipse/che-machine-exec-plugin/7.5.1/meta.yaml

For a VS Code plug-in:
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/joaompinto/vscode-asciidoctor/2.7.7/meta.yaml

**Comment by themr0c** [comment]
NB: related to https://github.com/eclipse/che-docs/pull/879/files
