### ISSUE TITLE
Start workspace with Language Support for Java 8 plugin failed

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15398]
### Describe the bug
The workspace can't be started if it contains **Language Support for Java 8** or **Language Support for Java(TM)** plugin.

Error message:
```log
Error: failed to start container "vscode-javacoy": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/entrypoint.sh\": permission denied"
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Create a workspace from Java Maven stack and activate `Language Support for Java 8` or `Language Support for Java(TM)` instead of `Language Support for Java 11`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-che-che 192 168 99 121 nip io-2019 12](https://user-images.githubusercontent.com/1271546/70130051-8884f680-1688-11ea-9df9-56d1f1627cdf.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
confirm. it sounds a blocker

**Comment by tolusha** [comment]
@AndrienkoAleksandr @benoitf

**Comment by svor** [comment]
close as it is duplicated with https://github.com/eclipse/che/issues/15402
