### ISSUE TITLE
Check extensions of VS Code extension pack are running smoothly

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15390]
### Is your task related to a problem? Please describe.
https://github.com/eclipse/che/issues/15272 would bring support of Extension pack
But each extension should be running properly when support will be there.
This issue is to ensure that all API/features are available in Che-Theia to make sure that these extensions are running properly.

### Describe the solution you'd like
Check that all extensions of the packs are able to run smoothly on Eclipse Che.
It includes:
- [ ] Git Extension pack: https://marketplace.visualstudio.com/items?itemName=donjayamanne.git-extension-pack
- [ ] Java Extension pack: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack
- [ ] Php Extension pack: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-pack
- [ ] Python Extension pack: https://marketplace.visualstudio.com/items?itemName=donjayamanne.python-extension-pack
- [ ] NodeJS pack: https://marketplace.visualstudio.com/items?itemName=waderyan.nodejs-extension-pack

Of course, some "non-open-source" extensions shouldn't be checked

### Additional context
As it's for test/checking if it's working, all extensions can be used in a single Che plugin meta.yaml.

**Comment by sunix** [comment]
for the git extension pack:
- [ ] Git History (git log) - PR in progress https://github.com/eclipse/che-plugin-registry/pull/805
- [ ] Project Manager
- [x] GitLens - already in the plugin registry
- [ ] gitignore
- [ ] Open in GitHub / Bitbucket / VisualStudio.com

**Comment by l0rd** [comment]
Closing as we are [sunsetting che-theia](https://github.com/eclipse/che/issues/21771)
