### ISSUE TITLE
How to Debug Java Project on Eclipse/Che:6.15.0

### ISSUE THREAD

**Issue by nogisun** [eclipse-che/che#15407]
## Summary
I want to debug java project. So run custom debug command. But, After debugger connecting localhost:8000 , it doesn't stop at the breakpoint, and it immediately disconnects.

### custom debug command( named JavaDebug-Issue )
`
cd ${current.project.path}/src && javac ${current.class.fqn}.java && java -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y -classpath ${current.project.path}/src ${current.class.fqn}
`
### Che Version
6.15.0

![Q1](https://user-images.githubusercontent.com/49777987/70194012-59cc5600-1744-11ea-8a38-3b51159e8ca0.png)

**Comment by benoitf** [comment]
Hello @nogisun 
You should try Che 7.0 with a better debug support.

About your question, I suppose there is a mismatch between source and compiled class.
