### ISSUE TITLE
Document/support private SSH key

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1540]
Especially for Docker users, please document how to setup the SSH key that Che would use when trying to access Git repositories.

**Comment by TylerJewell** [comment]
We have some docs here:
https://eclipse-che.readme.io/docs/git#ssh-key-management

Are there issues and more elaborate documentation that is needed?
@ddementieva - fyi.

**Comment by wernight** [comment]
Thanks. That document could be improved indeed: It's only focused on GitHub which I think is too restrictive for a self hosted solution.

It's also not explaining how to get the SSH public key generated by Che that should be registered. I'm referring here to the last paragraph (which should be another section and probably even the main section before GitHub-specific stuff):

> For other Git hosting providers a key should be generated and manually saved to Git hosting provider account.

**Comment by james10174** [comment]
@wernight Feel free to use the "suggest edit" link on the docs page. Were you able to get it to work. Profile->Preferences->SSH->VCS->Generate Key, then hit View to copy public key to paste to your repository of choice.

**Comment by ghost** [comment]
@wernight https://eclipse-che.readme.io/v4.3/docs/git#section-other-git-hosting-providers

Closing the issue for now. Feel free to reopen if you face problems with establishing a secure SSH connection with your git hosting provider.

**Comment by wernight** [comment]
I'll try again once other issues are fixed. I didn't see any Profile or Preferences from the initial dialog (the dialog shown when you've no workspace).

**Comment by ddementieva** [comment]
You will find `Profile > Preferences` menu directly in the IDE:
1. Create a new workspace at Dashboard > Workspaces tab.
2. Open it in the IDE.
3. Find `Profile` menu on the top of the IDE. Click it and open Preferences. 
4. Generate SSH key, copy it and paste to your Git hosting provider account.
5. Import your repository with `Workspace > Import Project...` option.

**Comment by wernight** [comment]
The issue here is that I wanted to create a workspace from a Git repo, so it's a chicken and egg issue.

Knowing this, I could create an empty project/workspace, then change my settings, then create my actual project/workspace, then delete my original blank project/workspace. For new users, the main button is "New Project", and there is no profile/settings visible.

**Comment by TylerJewell** [comment]
We have been discussing this use case a bit internally but want to make sure we understand the scenario.  

When you want to create a workspace from a git repo do you mean that you want the stack recipe files to be located in a repo?  Or are you wanting the hidden configuration and meta files for a workspace to be available in a git repo?

Both require some form of git access with ssh before the workspace is generated.  Projects are not added in our world until after the workspace is created and running.

**Comment by ghost** [comment]
@TylerJewell I think what's meant here is that it is impossible to import a project over SSH in UD. You have to start a workspace with a sample app or a publicly available git repo, and add a key in the IDE.

SSH key management in UD is a solution here

**Comment by wernight** [comment]
I think elvantsov is correct (not sure what UD means, I guess it's this screen: ![](https://codenvy.com/images/img-home-product@2x.png) but without the Account part as that is only Codenvy.

**Comment by ghost** [comment]
User Dashboard is what I mean

**Comment by TylerJewell** [comment]
Ok, so seems then that we need a few things to be configurable within the system properties of che (which would be in UD):
1. Proxy / no proxy configuration to be injected into workspaces generated.
2. User SSH key upload, which allows you to import a project over SSH.
3. User SSH key upload, which could allow you to source ws recipe definition from a git repo.

**Comment by wernight** [comment]
Doesn't need to be uploaded. One issue with upload is that it requires a safe terminal to generate them which isn't ideal for a cloud solution. I'd recommend generating them and showing only the public key.

Extra: The private key should be well encrypted locally ideally. If not allowing to mount the key would be a great addition (talking about Docker here especially Kubernetes secret volumes).

**Comment by TylerJewell** [comment]
@eivantsov - so does this mean we would need to extend key management to two levels.  With Eclipse Che there are keys managed per user (which is the same as per system), and then also per workspace?  

Would the keys for each workspace also be configured in the UD?  Or, should those only be in the IDE the way it is now.
