### ISSUE TITLE
Failed to started Eclipse Che on MicroK8s

### ISSUE THREAD

**Issue by chenjianxin** [eclipse-che/che#15408]
**microk8s.kubectl proxy --accept-hosts=.* --address=127.0.0.1  --port=8080
Starting to serve on 127.0.0.1:8080**

sudo chectl server:start --platform=microk8s --installer=helm
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ❯ ✈️  MicroK8s preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if microk8s is installed
    ✔ Verify if microk8s is running
    ✖ Start microk8s
      **→ MicroK8s is not running.**
      Verify if microk8s ingress and storage addons is enabled
      Enable microk8s ingress addon
      Enable microk8s storage addon
      Retrieving microk8s IP and domain for ingress URLs
 **›   Error: MicroK8s is not running.**

WHY??

**Comment by benoitf** [comment]
it is launching command `microk8s.status` and is expecting the exit code is 0

**Comment by chenjianxin** [comment]
> 
> 
> it is launching command `microk8s.status` and is expecting the exit code is 0

sudo microk8s.status
microk8s is running
addons:
cilium: disabled
dashboard: disabled
dns: enabled
fluentd: disabled
gpu: disabled
helm: enabled
ingress: enabled
istio: disabled
jaeger: disabled
juju: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
prometheus: disabled
rbac: enabled
registry: enabled
storage: enabled

**Comment by benoitf** [comment]
could you try:
```
$ sudo su -
# chectl server:start --platform=microk8s --installer=helm
```

**Comment by chenjianxin** [comment]
> 
> 
> could you try:
> 
> ```
> $ sudo su -
> # chectl server:start --platform=microk8s --installer=helm
> ```

root@DESKTOP-F5H2JQL:~# chectl server:start --platform=microk8s --installer=helm
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ❯ ✈️  MicroK8s preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if microk8s is installed
    ✔ Verify if microk8s is running
    ✖ Start microk8s
      → MicroK8s is not running.
      Verify if microk8s ingress and storage addons is enabled
      Enable microk8s ingress addon
      Enable microk8s storage addon
      Retrieving microk8s IP and domain for ingress URLs
 ›   Error: MicroK8s is not running.

**Comment by benoitf** [comment]
and when you're root

```
# microk8s.status
```

is working ?

**Comment by benoitf** [comment]
I would say there is missing PATH entry for root user

**Comment by chenjianxin** [comment]
> 
> 
> and when you're root
> 
> ```
> # microk8s.status
> ```
> 
> is working ?

root@DESKTOP-F5H2JQL:~# microk8s.status
microk8s is running
addons:
cilium: disabled
dashboard: disabled
dns: enabled
fluentd: disabled
gpu: disabled
helm: enabled
ingress: enabled
istio: disabled
jaeger: disabled
juju: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
prometheus: disabled
rbac: enabled
registry: enabled
storage: enabled

**Comment by benoitf** [comment]
and the exit code is 0 ?

```
# microk8s.status
# echo $?
```

**Comment by chenjianxin** [comment]
> 
> 
> and the exit code is 0 ?
> 
> ```
> # microk8s.status
> # echo $?
> ```

yes

**Comment by chenjianxin** [comment]
by the way 
my os environment  is WSL2 (ubuntu 18.04)

**Comment by benoitf** [comment]
you might investigate by:

cloning chectl repository: git clone https://github.com/che-incubator/chectl

then run yarn inside `chectl`

and then `./chectl/bin/run server:start --platform=microk8s --installer=helm`

https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L45-#L54
https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L99-#L102

**Comment by chenjianxin** [comment]
> 
> 
> you might investigate by:
> 
> cloning chectl repository: git clone https://github.com/che-incubator/chectl
> 
> then run yarn inside `chectl`
> 
> and then `./chectl/bin/run server:start --platform=microk8s --installer=helm`
> 
> https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L45-#L54
> https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L99-#L102

elecbuggy@DESKTOP-F5H2JQL:~/chectl/bin$ ./run server:start --platform=microk8s --installer=helm
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ❯ ✈️  MicroK8s preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if microk8s is installed
    ✔ Verify if microk8s is running
    ✖ Start microk8s
      → MicroK8s is not running.
      Verify if microk8s ingress and storage addons is enabled
      Enable microk8s ingress addon
      Enable microk8s storage addon
      Retrieving microk8s IP and domain for ingress URLs
 ›   Error: MicroK8s is not running.

**Comment by chenjianxin** [comment]
> 
> 
> you might investigate by:
> 
> cloning chectl repository: git clone https://github.com/che-incubator/chectl
> 
> then run yarn inside `chectl`
> 
> and then `./chectl/bin/run server:start --platform=microk8s --installer=helm`
> 
> https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L45-#L54
> https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L99-#L102

situation 2:

elecbuggy@DESKTOP-F5H2JQL:~/chectl/bin$ sudo ./run server:start --platform=microk8s --installer=helm
[sudo] password for elecbuggy:
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ❯ ✈️  MicroK8s preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if microk8s is installed
    ✖ Verify if microk8s is running
      → util.getSystemErrorName is not a function
      Start microk8s
      Verify if microk8s ingress and storage addons is enabled
      Enable microk8s ingress addon
      Enable microk8s storage addon
      Retrieving microk8s IP and domain for ingress URLs
TypeError: util.getSystemErrorName is not a function
    at getCode (~/chectl/node_modules/execa/lib/error.js:11:16)
    at makeError (~/chectl/node_modules/execa/lib/error.js:50:35)
    at handlePromise (~/chectl/node_modules/execa/index.js:112:26)
    at <anonymous>

**Comment by chenjianxin** [comment]
> 
> 
> you might investigate by:
> 
> cloning chectl repository: git clone https://github.com/che-incubator/chectl
> 
> then run yarn inside `chectl`
> 
> and then `./chectl/bin/run server:start --platform=microk8s --installer=helm`
> 
> https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L45-#L54
> https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/microk8s.ts#L99-#L102

I re-install WSL2 Ubuntu OS  then it work ....
