### ISSUE TITLE
Sidecar container images fails to start

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15402]
### Describe the bug
Sidecar container images fails to start.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
On the minikube:
1. Create new workspace from golang stack.
2. Start workspace
3. See error:
```
Created container che-machine-execpbr

Started container che-machine-execpbr

Pulling image "docker.io/eclipse/che-theia:next"

Successfully pulled image "docker.io/eclipse/che-theia:next"

Created container theia-idek6l

Started container theia-idek6l

Pulling image "quay.io/eclipse/che-sidecar-go:1.12.9-3414491"

Successfully pulled image "quay.io/eclipse/che-sidecar-go:1.12.9-3414491"

Created container vscode-gogtv

Error: failed to start container "vscode-gogtv": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown
```

### Expected behavior
Workspace should be launched.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by svor** [comment]
The same problem with workspaces which include Java plugin with Java 8
```log
Error: failed to start container "vscode-javacoy": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/entrypoint.sh\": permission denied"
```

**Comment by benoitf** [comment]
it can be closed ?

**Comment by mmorhun** [comment]
I suppose yes, I just wanted to test this morning.

**Comment by mmorhun** [comment]
Tested with Java LS - works for me.

**Comment by AndrienkoAleksandr** [comment]
We missing to update some images.
