### ISSUE TITLE
E2E Happy path tests failed on starting workspace when pull image from quay.io/eclipse/che-sidecar-java:8-fac2415

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15404]
### Describe the bug
Test workspace startup stuck on pulling image from :
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/3590/
![screenshot-Wait_workspace_running_state (1)](https://user-images.githubusercontent.com/1197777/70139642-9132f800-169b-11ea-87fc-cf8ae8698451.png)
```
07:51:18.333 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session e8900d991446e4f26eb6dbe243611c37 (org.openqa.selenium.chrome.ChromeDriverService)
        ▼ MultiUserLoginPage.login
        ▼ MultiUserLoginPage.waitEclipseCheLoginFormPage
        ▼ MultiUserLoginPage.inputUserNameEclipseCheLoginPage username: "admin"
        ▼ MultiUserLoginPage.inputPaswordEclipseCheLoginPage password: "admin"
        ▼ MultiUserLoginPage.clickEclipseCheLoginButton
    ✓ Open workspace (3250ms)
        ▼ Ide.waitWorkspaceAndIde
        ▼ Ide.waitAndSwitchToIdeFrame
        ▼ Ide.waitIde
    1) Wait workspace running state


  1 passing (4m)
  1 failing

  1) Validation of workspace start
       Wait workspace running state:
     TimeoutError: Waiting for element to be located By(css selector, #theia-app-shell #theia-top-panel .p-MenuBar-content)
```
Kubernetes events:
```
3m11s       Normal   Pulling                 pod/workspacemrdbzetcyih6axq6.workspace-69f5544444-mzxcj    Pulling image "quay.io/eclipse/che-sidecar-java:8-fac2415"
3m45s       Normal   SuccessfulCreate        replicaset/workspacemrdbzetcyih6axq6.workspace-69f5544444   Created pod: workspacemrdbzetcyih6axq6.workspace-69f5544444-mzxcj
3m45s       Normal   ScalingReplicaSet       deployment/workspacemrdbzetcyih6axq6.workspace              Scaled up replica set workspacemrdbzetcyih6axq6.workspace-69f5544444 to 1
```
Che server log:
```
2019-12-04 10:26:45,086[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 607]    - Workspace 'admin/petclinic-dev-environment' with id 'workspacev0mfjv13188rro56' created by user 'admin'
2019-12-04 10:27:38,863[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 466]   - Starting workspace 'admin/petclinic-dev-environment' with id 'workspacev0mfjv13188rro56' by user 'admin'
2019-12-04 10:27:52,518[aceSharedPool-0]  [WARN ] [i.f.k.c.i.VersionUsageUtils 55]      - The client is using resource type 'ingresses' with unstable version 'v1beta1'
2019-12-04 10:32:01,631[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 252]  - Failed to start Kubernetes runtime of workspace workspacev0mfjv13188rro56. Cause: Server 'theia' in container 'theia-idele1' not available.
2019-12-04 10:32:02,737[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 889]   - Workspace 'admin:petclinic-dev-environment' with id 'workspacev0mfjv13188rro56' start failed
```

Local pull log:
```
[ndp@localhost ~]$ docker pull quay.io/eclipse/che-sidecar-java:8-fac2415
8-fac2415: Pulling from eclipse/che-sidecar-java
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption.
9d48c3bd43c5: Already exists 
84b1737f33e7: Pull complete 
d0f7428816c3: Pull complete 
2a7ccc8a5ed5: Pull complete 
8efdf0ca18c4: Pull complete 
Digest: sha256:bcf4c2932f684d46915e37cdd2f14f5b06c3fc50fe40b225de1770ac0b202ddd
Status: Downloaded newer image for quay.io/eclipse/che-sidecar-java:8-fac2415
quay.io/eclipse/che-sidecar-java:8-fac2415
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Start Java workspace.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.11
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

### Additional context
Related PR: https://github.com/eclipse/che-theia/pull/568

**Comment by evidolob** [comment]
It related to https://github.com/eclipse/che/issues/15402

**Comment by benoitf** [comment]
should be fixed now

**Comment by RomanNikitenko** [comment]
I updated my PR and reran tests 1 hour ago 
but looks like the tests failed
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/633/

**Comment by dmytro-ndp** [comment]
The issue has been finally fixed after rebuild of nightly images:
![Screenshot from 2019-12-06 08-30-10](https://user-images.githubusercontent.com/1197777/70301390-e89fa800-1802-11ea-9db2-dac7b4266376.png)
