### ISSUE TITLE
Export current workspace definition as devfile

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#15400]
## Goal

The goal of this epic is to allow the user (developers using Eclipse Che) to export the current configuration of his workspace has a devfile. 

As a user, I should be able to export my workspace as a devfile, so the workspace becomes reproducible and easy to share with other developers working on the same project than me. 

### Problems

Today, the workspace can get configured in many different ways. 
- It can be done from the IDE, to add tasks, commands, launch configs or plugins 
- It can be done from the dashboard, to add plugins or other settings

The problem is that none of those changes are easy to share and export in a devfile. The user has to go into the dashboard, on the devfile subtab for the workspace and then do a copy/paste somewhere, remove some fields and then he can finally add it to the project source code. 

### Proposed Solutions

**Ability for the user to generate devfile from the editor**
As a user in the editor, I want to get a menu action to allow exporting the current workspace configuration as a devfile. The devfile will be added to the project source code. If the devfile was already there, we will need to notify the user and inform that the current devfile will be overwritten. 
This action should also be available from the command palette.

**Ability for the user to sync the devfile from workspace pane**
As a user, the workspace pane gives me a way to interact with the workspace components. I should be able to export the devfile from this panel as well. 

**Ability to export the devfile from the dashboard**
As a user, I can go to the dashboard and see the workspace's configuration. It's a devfile, but a specific one, that I can't share to other users. We should allow to export the devfile to the user's clipboard, so he can easily share it. 

### Sub-tasks

- [ ] `/projects/.devfile.yaml` synchronized with the current workspace devfile #13983

**Comment by benoitf** [comment]
hello, it looks like https://github.com/eclipse/che/issues/12709
