### ISSUE TITLE
User is redirected on dashboard after devfile editing 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15403]
### Describe the bug
User is redirected on dashboard after `devfile` editing
Please see steps to reproduce and the attached video 

### Che version
 - [x] latest

### Steps to reproduce
1. Start a workspace
2. Go to dashboard and edit something in devfile
3. Click `Save` -> `Apply` -> `Open` buttons
4. You can see logs that the workspace is starting
5. You are redirected on dashboard when the workspace is started

### Expected behavior
I click `Open` button and I expect that IDE is open when the workspace has started, not dashboard.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   
### Screenshots
https://youtu.be/mqvxxCf22bA

### Installation method
   - [x] chectl 
   
### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
@RomanNikitenko could you confirm that it's actual for a new dashboard?

**Comment by sleshchenko** [comment]
I believe it's not actual for a new dashboard. If somebody face the same behavior - please reopen this or create a new issue
