### ISSUE TITLE
GitHub plugin fails when starting a new workspace

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#15416]
### Describe the bug

GitHub plugin is not initialised when starting a new workspace. Restarting existed workspace or even page refresh makes the plugin initialized. 
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a new workspace in the dashboard.
2. Go to the plugins list of the new workspace and enable GitHub plugin.
3. start the workspace.
See: The GitHub plugin is not initialised: no GitHub commands are present in the command palette.
### Expected behaviour

The plugin must be initialised.
### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
Could you be more specific in term of `initialized` ? What does it mean?

**Comment by vinokurig** [comment]
@tolusha It means that that there are no contributed commands from the plugin, and the plugin panel shows a message that there are no  GitHub repositories are present in the workspace in spite of some projects cloned from GitHub in the `projects` directory.

**Comment by ericwill** [comment]
@vinokurig is this still reproducible?

**Comment by vinokurig** [comment]
Can not reproduce in 7.15.0
