### ISSUE TITLE
Persist plugin and editors `home` folder to keep configuration after workspace restart.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15421]
### Is your enhancement related to a problem? Please describe.
Many vscode extension and editors are storing some settings in /home/theia.
At the moment, some settings like workspace roots, kubernetes context are lost after restart.

### Describe the solution you'd like
Maybe have a volume for /home/theia.

**Comment by tolusha** [comment]
All plugins have a dedicated path to persist theirs state. [1]

@evidolob 
Is it `/home/theia` ?

[1] https://github.com/microsoft/vscode/blob/1.40.2/src/vs/vscode.d.ts#L4972-L4989

**Comment by sunix** [comment]
I don't think we need more info to prioritize this ... this is to the assignee to make an analysis and see what would be needed.

**Comment by PirateBread** [comment]
I would also add that persisting a users $HOME directory would make a lot of sense. Many CLI tools will store various configuration items, for example various .dotfiles and folders. Wondering if anyone has attempted to configure a container with Eclipse Che to work this way?

Lots of virtual terminal offerings do this, for example if you use GCP/Azure CLI, it will store your home directory in a persistent way and for users it works as they expect. For example if they update a .bashrc or .zshrc configuration or store your kubectl config.

**Comment by l0rd** [comment]
@AObuchow yes let's close this one as we are already tracking the same problem in the most up to date #22102
