### ISSUE TITLE
 Prompt to Terminate or Restart the task  

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15428]
### Is your task related to a problem? Please describe.
At the moment user has ability to run identical `che` tasks at the same time.

Recently `theia` provided the functionality for tasks execution which prompts to `Terminate` or `Restart` a task if the same task is running at the moment.

You can see, for example, how it works for test `shell` task
![restart_new_behavior](https://user-images.githubusercontent.com/5676062/70425114-42110c80-1a79-11ea-97a4-ebb22d8c207e.gif)

For `Terminate Task` action:
- the task is terminated
- the terminal widget is open after terminating the task  

For `Restart Task` action:
- the task is terminated
- the terminal widget is open after terminating the task
- the task is started
- the new terminal is used for the output   

But the functionality doesn't work for `che` tasks, so we need to investigate what adaptation is required on `che-theia` side if we would like to have this functionality for `che` tasks.

Also within the same PR `theia` started to provide info about  workspace folder in task notifications:
![shell_notification](https://user-images.githubusercontent.com/5676062/70735999-08116600-1d18-11ea-8f32-30959a201c71.png)

It can be useful for multi root workspace when tasks come from different workspace folders.

But for `che` tasks `plugin` is displayed instead:
![notification_tasks](https://user-images.githubusercontent.com/5676062/70736039-1cedf980-1d18-11ea-8a63-fa8acd58f9cc.png)

So, I think we should align the behavior for `che` tasks

**Comment by azatsarynnyy** [comment]
Setting label `area/plugins` as it's related to https://github.com/eclipse/che-theia/tree/master/plugins/task-plugin
