### ISSUE TITLE
pip install of large modules crashes quay.io/eclipse/che-machine-exec:7.5.1

### ISSUE THREAD

**Issue by mingfang** [eclipse-che/che#15423]
To create:
1- create new workspace with the python stack
2- open a terminal
3- run pip install mindmeld
4- the install will crash quay.io/eclipse/che-machine-exec:7.5.1 when it tries to install the tensorflow modules which is 400+ MB

The workaround is the increase the resources.limits.memory from the default 1024MB to say 4096MB.

Question is
1-why does pip install consume memory? is this a bug or a feature?
2-how can I change the default memory limit?

**Comment by mingfang** [comment]
I figured out the answer to my question #2; I changed the default memory limit by setting CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB to 256.
After restarting everything, I was able to successfully run `pip install mindmeld`

It's still strange that the sidecar memory limit effects the pip command.
Can someone please explain that?

**Comment by tolusha** [comment]
@mingfang 
Accordingly to the doc:
`RAM limit default for each sidecar that has no RAM settings in Che plugin configuration.`
The default value (which is 128Mi ) wasn't enough for pip.

**Comment by mingfang** [comment]
> @mingfang
> Accordingly to the doc:
> `RAM limit default for each sidecar that has no RAM settings in Che plugin configuration.`
> The default value (which is 128Mi ) wasn't enough for pip.

@tolusha Why does the memory affect running the pip command?
