### ISSUE TITLE
Support single-host mode on OpenShift

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15422]
### Is your enhancement related to a problem? 

We currently only support Kubernetes but [it looks like this should be possible on OpenShift too](https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#path-based-routes...so) and anyway Ingress are supported on OpenShift as well.

**Comment by sleshchenko** [comment]
Just more context, AFAIU on OpenShift it's possible in two cases:
1. Che Server and workspaces are run in the same OpenShift project. It seems to be not a secure solution at all.
2. Namespace ownership check is disabled on OpenShift cluster https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#disable-namespace-ownership-check. Not sure it's acceptable for production as well.

So, maybe it does not make sense to support single-host mode on OpenShift if there is no production-ready solution. But I did not investigate this question deep enough and maybe there are some alternatives.

**Comment by skabashnyuk** [comment]
This issue would be made as part of https://github.com/eclipse/che/issues/12914. @l0rd does it make sense to keep it separate?

**Comment by l0rd** [comment]
I think this issue is about single host without going through an external reverse proxy. Something that should be possible on OCP 4.6 and only if namespace ownership check is disabled.

Is there something to do on our side to be able to use OpenShift 4.6 routes path rewrite?

**Comment by benoitf** [comment]
@l0rd this is what I wanted to test, I think there might have stuff (to see if we can have the same level of feature than when using that on kubernetes)

**Comment by tolusha** [comment]
@l0rd @benoitf 
Can we mark this issue as solved?

**Comment by l0rd** [comment]
I would say that yes. Closing
