### ISSUE TITLE
Document running che on kind

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#15438]
### Is your enhancement related to a problem? Please describe.

Document running che on [kind](https://kind.sigs.k8s.io/#installation-and-usage).

**Comment by l0rd** [comment]
@tomgeorge that would be great. Have you already been able to run Che on kind? I am asking to understand if that's only about documenting something that we know is currently possible or if we need an analysis and eventually some coding (in particular because of the networking part).

**Comment by tomgeorge** [comment]
@l0rd I have been able to run Che on kind.  It has dependencies on the nginx ingress controller, metallb, and the csi hostpath driver, but it runs.  See [this gist](https://gist.github.com/tomgeorge/1428b3fab75d9f67fee242d8df8e9d6f) or the PR above.

I think we could even implement it in Chectl, side-loading the images into the kind cluster or pulling them if they are not in the user's local machine.

**Comment by l0rd** [comment]
@tomgeorge fantastic. I will try to test that this week. That can be interesting for QE as well cc @rhopp

**Comment by ibuziuk** [comment]
PR merged. Closing
