### ISSUE TITLE
Can't install Eclipse-che 7 on either Kubernetes or Openshift 3

### ISSUE THREAD

**Issue by svrajasekar** [eclipse-che/che#15433]

**Comment by svrajasekar** [comment]
I tried installing Eclipse-che  on Kubernetes first and then on Openshift 3. In either case, the installed failed. The reason: Che pod bootstrap hangs for ever. Can someone help me out?

**Comment by ibuziuk** [comment]
@svrajasekar please follow the official docs - https://www.eclipse.org/che/docs/che-7/running-che-locally/ 
if you would still have an issue for some reason, please provide description to the issue with all the details

**Comment by svrajasekar** [comment]
Actually I followed the above link to try. First I started with Minikube on Windows. I faced a lot of issues with it. I then tried to install Eclipe-Che on Kubernetes. Here again I could not. The reason being it gets stuck when starting che-server pod. The same issue with Openshift 3. I don't know why it gets stuck.

**Comment by tolusha** [comment]
Closed in favor of https://github.com/eclipse/che/issues/15481
