### ISSUE TITLE
Provide plugin's icons

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#15437]
### Is your task related to a problem? Please describe.
Most of the plugins packaged with eclipse che have a icon defined, but in eclipse che, we are always showing the placeholder "eclipseche" icon.

### Describe the solution you'd like
Bring icons that are available (and licence compliant) to be used inside of Che.

### Example
Java LS: https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by amisevsk** [comment]
Duplicates https://github.com/eclipse/che/issues/14510

**Comment by slemeur** [comment]
CLosing in favor of: https://github.com/eclipse/che/issues/14510
