### ISSUE TITLE
If the plugin version is not specified the 'latest' version should be used

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15447]
### Is your task related to a problem? Please describe.
This will allow specifying plugins without version: e.g. 

`id: che-machine-exec-plugin` - in this case, the `latest` version of the plugin should be used.

the case should be tackled on wsmaster / plugin broker side (when the version is missing always fall back on the latest).

Another thing we need to take care of is the versions of the `exec` and `theia` that are automatically added by wsmaster (when a user do not specify them in a Devfile). 

### Describe the solution you'd like
a possibility to specify plugins without version which fall back on latest

**Comment by l0rd** [comment]
Makes sense @ibuziuk. I thought we had already implemented it.
