### ISSUE TITLE
Camel K stack is no more working with "Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown"

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15455]
### Describe the bug
Camel K stack is no more working with "Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown"

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. use "next" version of Che
2. Start Apache Camel K stack
3. See error

### Expected behavior

working Apache Camel K stack

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

Camel K stack relies on Camel K plugins which is using a DockerFile that is extending the Kubernetes one.

It seems that the Kubernetes Docker file has been modifed to match new state of Che but that the Cmael K Dockerfile was not rebuilt

```
Pulling image "quay.io/eclipse/che-sidecar-camelk:0.0.10-966607d"
Successfully pulled image "quay.io/eclipse/che-sidecar-camelk:0.0.10-966607d"
Created container vscode-camelksm7
Error: failed to start container "vscode-camelksm7": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown
Pulling image "quay.io/eclipse/che-sidecar-camelk:0.0.10-966607d"
```

**Comment by apupier** [comment]
how to trigger a new build of the Docker image?
for the future, how to ensure that a new build is triggered when a dependent image is rebuilt?

**Comment by benoitf** [comment]
images have been rebuilt but seems like it was not updated on che plugin registry
will fix

**Comment by benoitf** [comment]
https://quay.io/repository/eclipse/che-sidecar-camelk?tag=latest&tab=tags
