### ISSUE TITLE
Improve error messaging when plugin broker failed to start

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15456]
### Is your task related to a problem? Please describe.
When plugin broker failed to start - a user sees an error message that plugin brokering reached timeout  
```
Pulling image "eclipse/che-init-plugin-broker:v0.24"
Successfully pulled image "eclipse/che-init-plugin-broker:v0.24"
Created container che-init-plugin-broker-v0-24
Started container che-init-plugin-broker-v0-24
Error: Failed to run the workspace: "Plugins installation process timed out"``
```
It's possible and would be nice if we check container status before proceeding to waiting plugin broker event via WebSocket.
Ideally, except earlier failure with an error like `plugin broker pod exited with code 1` it would be nice if we publish plugin broker pod logs or at least print them to Che Server logs, the same we do with [PVCSubPathHelper](https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java#L170)

### Steps to reproduce
The easiest way to reproduce it - misconfigure WebSocket endpoint for plugin broker pod 
https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java#L94

It would be similar to a real user-faced issue when plugin broker failed to connect to Che Server WebSocket endpoint because of self-signed TLS issues https://mattermost.eclipse.org/eclipse/pl/aw5yt8zdd78zbpgfk3xx3y6j4h

### Additional context
Container status checking is implemented in https://github.com/eclipse/che/pull/15449 but not used during plugin brokering phase

**Comment by amisevsk** [comment]
:+1: I faced this issue when trying to deploy Che on an offline cluster with proxy, a fix for this would've helped greatly in debugging https://github.com/eclipse/che/issues/15265

**Comment by amisevsk** [comment]
Looks like this issue is enclosed in https://github.com/eclipse/che/issues/15490

**Comment by sleshchenko** [comment]
@amisevsk Well, they are overlapping (since artifacts plugin broker is run as an init container) but the scope of this issue is a bit wider... I mean there is still a metadata plugin broker that is run as separate Pod and its containers statuses are not tracked.

**Comment by amisevsk** [comment]
My understanding for this issue was that it was only a problem for init containers (e.g. the if the init broker (v0.24) fails then that isn't tracked). I didn't realize it was a general broker issue.

**Comment by hari1992-web** [comment]
same issue 
![Screenshot from 2020-04-12 16-10-24](https://user-images.githubusercontent.com/62592574/79069183-dcb07f00-7ce9-11ea-8c78-2484c59be13c.png)    

plugins installation process timed out
