### ISSUE TITLE
Sometimes when there are dependencies between VS Code extensions, the dependency is not activated

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15463]
### Describe the bug

Camel K and Kubernetes extension are not loading, complaining that Yaml extension is not available.

### Che version

 - [x] latest 7.6.0-SNAPSHOT
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start Apache Camel K stack
2. Sometimes a little popup mentioning that Kubernetes plugin cannot start because yaml extension is not available
3. See error

### Expected behavior

all extensions always starting successfully

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

[apupier@linux browser]$ minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
[apupier@linux browser]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

### Installation method
   - [x] chectl  chectl server:start -p minikube
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux Fedora 31
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

it happened only 2 times for me in something like 50-70 tries. Unfortunately, it was both during demonstration to other group of people so I wasn't able to dig into it, like looking to log and providing the exact error message :-(

**Comment by bryantson** [comment]
I have the same issue. I tried to modify the plugin meta.yaml through Openshift Plugin container and restarted the workspace, but this issue seems to persist.

**Comment by ericwill** [comment]
The workaround here is to explicitly add the dependency in the `meta.yaml`. I believe this is still needed.
