### ISSUE TITLE
Enable autoMigrate for plugins

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15461]
### Is your enhancement related to a problem? Please describe.
Plugin metas currently support an autoMigrate field, e.g. for the [camel plugin](https://github.com/eclipse/che-plugin-registry/blob/4a6723d2a9bf6a07cfd0e04d02d2c758249ad682/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml#L13-L15). However, it seems that automatic updating of devfiles to use a different plugin is never done; this interferes with a deprecation procedure, as plugins that have been deprecated still cannot be removed from the plugin registry without the risk of breaking workspaces.

### Describe the solution you'd like
On loading workspaces for a user, any plugins that have the autoMigrate flag set are rewritten to use the `migrateTo`. This would allow a procedure as described by @l0rd, where
1. release `x.x.x`: Plugin deprecate flag is set, with autoMigrate false, to warn users that their plugin is deprecated
2. release `x.x.x+1`: `autoMigrate` flag can be set, to auto-update anyone who hasn't seen the notification
3. release `x.x.x+3`: plugin can be removed from repo.

### Describe alternatives you've considered
There is an issue for similar functionality in the broker: https://github.com/eclipse/che/issues/13022. However, it doesn't make sense in terms of deprecation, as the devfile will still depend on the deprecated plugin being in the registry.

### Additional context
![Screenshot from 2019-12-11 11-25-22](https://user-images.githubusercontent.com/16168279/70640403-e45ffa00-1c09-11ea-97d3-97538f202264.png)

**Comment by sleshchenko** [comment]
that's too old to be P1

**Comment by ericwill** [comment]
I think P2 is also fine because I am contemplating whether we even want multiple plugin versions in the registry. We release Che so often, it might be worth it only to keep the latest version of each plugin in the registry.

**Comment by amisevsk** [comment]
@ericwill :+1: the fabled simple registry :)

The only concern would be it would require some UI changes -- we don't want users selecting e.g. `redhat/vscode-java/7.18.2` instead of `redhat/vscode-java/latest` because any update would break existing workspaces. We'd basically have to force `latest` as the version for all plugins.

**Comment by nickboldt** [comment]
Since plugin reg now only includes latest version... is this obsolete?
