### ISSUE TITLE
Jaeger installation failure on k8s 1.16.2

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15472]
### Describe the bug

When installing che using helm on k8s 1.16.2, I got the following error:
```
Release "che" does not exist. Installing it now.
Error: release che failed: Deployment.apps "jaeger" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"jaeger", "jaeger-infra":"jaeger-pod"}: `selector` does not match template `labels`]
```
Since apiVersion is apps/v1, I fixed the problem by adding the following entry below the spec:
https://github.com/eclipse/che/blob/e3999fcc8b040a537c11300de178358acaef4396/deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/deployment.yaml#L17
``` yaml
  selector:
    matchLabels:
      app: jaeger
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
![image](https://user-images.githubusercontent.com/29850624/70777399-05b81600-1dc3-11ea-848e-d471c3eabad1.png)

   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
   - [x] helm

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
Could you try to install Eclipse Che using checlt [1] ?
[1] https://github.com/che-incubator/chectl

**Comment by kellyhyomin** [comment]
@tolusha 
I fixed the problem by adding the following entry below the spec:
https://github.com/eclipse/che/blob/e3999fcc8b040a537c11300de178358acaef4396/deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/deployment.yaml#L17
``` yaml
  selector:
    matchLabels:
      app: jaeger
```

**Comment by tolusha** [comment]
@kellyhyomin 
Thank you for information!

**Comment by sleshchenko** [comment]
@kellyhyomin It would be awesome if you are able to create a PR with changes you posted

**Comment by kellyhyomin** [comment]
@sleshchenko  Ok I will!
