### ISSUE TITLE
Can't build the offline-registry image of che-devfile-registry / offline-registry.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#15483]
### Describe the bug

Docker builds ware stopped in the `offline-builder` phase.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Run `docker build --no-cache -t quay.io/eclipse/che-devfile-registry:nightly -f build/dockerfiles/Dockerfile .`
2. See error

```
Caching project files for devfile devfiles/java-mysql/devfile.yaml
yq: Error running jq: ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "devfiles/java-mysql/devfile.yaml", line 21, column 27.
The command '/bin/sh -c ./cache_projects.sh devfiles resources &&     ./cache_images.sh devfiles resources &&     chmod -R g+rwX /build' returned a non-zero code: 1
```

### Expected behavior

Builds finished with no error.

### Additional context

I've already fixed it. I'm going to send PR.

**Comment by monaka** [comment]
I suppose it's better to try building offline images on CI.

**Comment by ibuziuk** [comment]
@amisevsk could you please take a look ?

**Comment by amisevsk** [comment]
The tab chars slipped past us in PR https://github.com/eclipse/che-devfile-registry/pull/160/

I'll have to look into the `yq` error we're seeing here, as this build should not fail for something so simple.

The reason we're not building the offline registry in CI at the moment is that some of the projects referenced in devfiles do not have any license attached, so redistributing this code is a little problematic. See https://github.com/eclipse/che/issues/14790 for more discussion.

**Comment by amisevsk** [comment]
There is still an outstanding issue to add CircleCI for the devfile registry (https://github.com/eclipse/che/issues/14867) as we have for plugin registry; I haven't had time to set it up yet.

**Comment by amisevsk** [comment]
To follow up on this, `PyYAML` as an open bug where trailing tab characters on a line fail to parse: https://github.com/yaml/pyyaml/issues/306

**Comment by amisevsk** [comment]
Opened https://github.com/eclipse/che/issues/15507 to track the trailing whitespace issue.
