### ISSUE TITLE
Collect logs during installation of  Eclipse Che

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15485]
### Is your task related to a problem? Please describe.
When the deployment is failing it is challenging to get the logs of what was going on. Admin (who is doing the deployment) will need to investigate and use ‘oc’ or ‘kubectl’ and in certain cases the logs are even not accessible once the installation failed.

### Describe the solution you'd like
If installation failed it is needed to have all necessary logs right away.

### Additional context
https://www.eclipse.org/che/docs/che-7/retrieving-che-logs/

**Comment by dmytro-ndp** [comment]
@tolusha: in PR check Jenkins jobs we are taking all workspace containers logs, and putting them into build artifacts, for example, https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/666/artifact/logs-and-configs/workspace-logs/
11:02 AM
The command to do it:
```
mkdir -p $LOGS_AND_CONFIGS/workspace-logs
export WS_POD=$(kubectl get pod --namespace=che | grep  workspace | awk '{print $1}')
for c in $(kubectl get pod --namespace=che $WS_POD -o jsonpath="{.spec.containers[*].name}") ; do kubectl logs $(kubectl get pod --namespace=che | grep  workspace | awk '{print $1}') "${c}" -n che > $LOGS_AND_CONFIGS/workspace-logs/"${c}"-container.log || true; done
```

**Comment by sparkoo** [comment]
@tolusha can we please move automatically collected logs into `/tmp` or something? I don't want to care about CWD where I run `chectl`, but now it would lead to `logs/` dirs all over the filesystem. I understand why it is important, but having `./logs/` default is annoying.

**Comment by tolusha** [comment]
@sparkoo 
Ok. It make sense.
