### ISSUE TITLE
Cannot install Eclipse Che following docker instructions

### ISSUE THREAD

**Issue by redeagle84** [eclipse-che/che#15487]
On the official Eclipse Docker account there is instructions about how to install Eclipse Che over Docker that is: [https://hub.docker.com/r/eclipse/che/](https://hub.docker.com/r/eclipse/che/)   but once you follow the instructions all you get is:   
`manifest for eclipse/che:latest not found`

**Comment by tolusha** [comment]
Docker isn't supported anymore.
Pls, follow the guide to install Eclipse Che 7.x locally:
https://www.eclipse.org/che/docs/che-7/running-che-locally/

**Comment by ibuziuk** [comment]
@redeagle84  closing feel free to reopen if there are any questions regarding the installation guide https://www.eclipse.org/che/docs/che-7/running-che-locally/

**Comment by redeagle84** [comment]
As Eclipse is the owner of the the Docker account would be great if Eclipse Che consider at least change the description on [https://hub.docker.com/r/eclipse/che/](https://hub.docker.com/r/eclipse/che/) because there is:  

**"Eclipse Che is a fully extensible IDE and developer workspace server that allows anyone to contribute to a project without having to install software."**

Would be great something like this: "This Docker entry is not more supported, see this link to a local instalation.... "

Anyway, thanks for the answer.
