### ISSUE TITLE
Unable to setup eclipse che in AWS EC2(ubuntu 18.4) Minikube

### ISSUE THREAD

**Issue by lsureddy** [eclipse-che/che#15482]
I am facing the problem to setup Eclipse che in minikube

**Comment by lsureddy** [comment]
![Eclipse che error](https://user-images.githubusercontent.com/49941990/70852377-0aeb9280-1ea1-11ea-8940-50fdcb0369db.png)

**Comment by tolusha** [comment]
@lsureddy 
`chectl version` ?

My guess you have something similar to https://github.com/eclipse/che/issues/15225
As workaround could you run `chectl` from the directory it is installed.

**Comment by lsureddy** [comment]
Hi thank you so much and it installed.

i am totally new to eclipse che and want to know how to use, i have tried to use the url which was given by che server below one and i am unable to reache, could please help me
    ✔ Retrieving Che Server URL...http://che-che.172.31.44.175.nip.io
    ✔ Che status check
Command server:start has completed successfully.

**Comment by tolusha** [comment]
1. check `minikube status`
2. ensure you use the latest `chectl` and run `chectl server:logs` to get some logs...

**Comment by sslnreddy** [comment]
> 1. check `minikube status`
> 2. ensure you use the latest `chectl` and run `chectl server:logs` to get some logs...

I have updated the chectl and also downloaded the server logs

I am getting below error message when i tried from the browser


Verbindungsfehler / Network Error (tcp_error)
--
A communication error occured.Possible cause could be a wrong URL, or a busy webserver.Please try again after a few minutes.Please contact the central hotline for help ( or Tel. 25000).

**Comment by sslnreddy** [comment]
root@ip-172-31-44-175:/usr/local/bin# chectl server:start --platform minikube
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"
      ✔ Found running che deployment
      ✔ Found running plugin registry deployment
      ✔ Found running devfile registry deployment
    ✔ Check Che server status...RUNNING (auth disabled)
  ✔ ✅  Post installation checklist
    ✔ Retrieving Che Server URL...http://che-che.172.31.44.175.nip.io
    ✔ Che status check
Command server:start has completed successfully.

**Comment by sslnreddy** [comment]
could you please guide how can i access from browser

**Comment by sslnreddy** [comment]
> 1. check `minikube status`
> 2. ensure you use the latest `chectl` and run `chectl server:logs` to get some logs...

Hi I am getting below error message

Verbindungsfehler / Network Error (tcp_error)
A communication error occured.Possible cause could be a wrong URL, or a busy webserver.Please try again after a few minutes.Please contact the central hotline for help ( or Tel. 25000).

xxx@ip-172-31-44-175:/usr/local/bin/che-devfile-registry/devfiles/python# chectl workspace:start -f devfile.yaml
  ✔ Retrieving Che Server URL...http://che-che.172.31.44.175.nip.io
  ✔ Verify if Che server is running...RUNNING (auth disabled)
  ✔ Create workspace from Devfile devfile.yaml

Workspace IDE URL:
http://che-che.172.31.44.175.nip.io/dashboard/#/ide/che/python-un9qv
To start collecting logs run 'chectl workspace:logs --follow'

**Comment by lsureddy** [comment]
I am able to access and its working
