### ISSUE TITLE
Cannot delete all commands from the devfile tab in UD

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#15489]
### Describe the bug

Cannot delete all commands from the devfile in UD.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a new workspace which includes commands
2. Try to delete all commands
(these changes have not detected)
3. Refresh the page after

### Expected behavior

The defile without commands
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2019-12-16 19-40-17](https://user-images.githubusercontent.com/6310786/70930144-2c818100-203d-11ea-82b6-9f262db6cfba.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

   **7.6.0-SNAPSHOT**

**Comment by RomanNikitenko** [comment]
Looks like it's related to https://github.com/eclipse/che/issues/15066 and https://github.com/eclipse/che/issues/15036

**Comment by olexii4** [comment]
@RomanNikitenko 
You are right). Thanks.
I skipped them in my search because the first was close and the second described in a different way

**Comment by olexii4** [comment]
fixed in https://github.com/eclipse/che/pull/15555
