### ISSUE TITLE
Add support for using existing keycloak/postgre in chectl

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#15496]
### Describe the bug
Installation of `Eclipse Che` with external keycloak fails with timeout error "ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false". 

Codeready issue - https://issues.redhat.com/browse/CRW-481.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Change `custom-resources.yaml` file to install **Eclipse Che** with external keycloak:
```
externalIdentityProvider: true
identityProviderURL: 'url to che'
identityProviderRealm: 'keycloak realm'
identityProviderClientId: 'client id in realm'
```
2. Install **Eclipse Che** by chectl.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Chectl log
```
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Keycloak pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, 
…
        downloading images
        starting
      Devfile registry pod bootstrap
      Plugin registry pod bootstrap
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
    at KubeHelper.<anonymous> (~/.local/share/chectl/client/0.0.20191217-next.925734b/lib/api/kube.js:599:19)
    at Generator.next (<anonymous>)
    at fulfilled (~/.local/share/chectl/client/0.0.20191217-next.925734b/node_modules/tslib/tslib.js:107:62)
```

**Comment by l0rd** [comment]
More then a bug that's an enhancement and a subtask of #13888

**Comment by ibuziuk** [comment]
@l0rd @tolusha FYI this issue is marked as major for CRW - https://issues.redhat.com/browse/CRW-481

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/pull/514

**Comment by SkorikSergey** [comment]
Fixed
