### ISSUE TITLE
Projects don't open from "Open IDE" link in Dashboard

### ISSUE THREAD

**Issue by beaumorley** [eclipse-che/che#15495]
### Describe the bug

IDE does not open when the Open IDE button is pressed in the Projects View of the Dashboard.

### Che version
Che Version 7.4.0 using chectl to run

### Steps to reproduce

1. Start an existing workspace from the Dashboard or Workspaces screen
2. Click on the workspace name to get the details screen
3. Choose the Projects tab item in the subnavigation
4. Click on the Open IDE (>) icon under the Action heading 

### Expected behavior
5. This should launch the IDE but instead it brings you back to the Workspaces screen

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

<img width="1218" alt="Screen Shot 2019-12-16 at 2 49 37 PM" src="https://user-images.githubusercontent.com/52013984/70938902-1fe93280-2015-11ea-9cd2-aeb3608ae905.png">

### Installation method
   - [x ] chectl  with minikube platform
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by l0rd** [comment]
cc @olexii4
