### ISSUE TITLE
Implement a way to add / override devfile attributes via URL parameters 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15500]
### Is your enhancement related to a problem? Please describe.
This issue is a logical continuation of the https://github.com/eclipse/che/issues/13617
It would be great to have the possibility to add/override `devfile` attributes via URL parameters. This would allow starting ephemeral workspaces using the default files from the devfile registry. 
Currently, for [getting-started](https://www.eclipse.org/che/getting-started/cloud/) devfiles we have to add `persistVolumes: 'false'` to make them ephemeral by default e.g.

> attributes:
>   persistVolumes: 'false'

It would be great to simply specify `persistVolumes: 'false'` in the URL instead of doing it on the devfile level.

### Describe the solution you'd like
Possibility to add / override devfile attributes via URL parameters 

### Describe alternatives you've considered
Alternatively, `attributes` will need to be always specified on the devfile level

### Additional context
Would allow getting rid of the most https://github.com/redhat-developer/devfile/tree/master/getting-started devfiles and reuse default devfiles from the registry.

**Comment by amisevsk** [comment]
This would also be very useful for testing devfile registry PRs on che.openshift.io, where running in ephemeral mode is often required.
