### ISSUE TITLE
Document Airgap Setup for Maven

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15503]
Test and document the process of setting up an airgap solution for Maven. In particular, configure a workspace based on our default maven devfile to use a Maven repository that uses a self-signed certificate.

The following issues are related and we need to document how to solve them manuall in this issue:
 
* Why it downloads Gradle when I open a single java file redhat-developer/vscode-java#901
* [Airgap] maven could not calculate build plan - settings.xml not used #14857

**Comment by sunix** [comment]
Here, I am describing how we could setup Maven to use a private Artifact repository in the case where Che could not access the internet and Maven Central.

There are several options:
- Artifact repositories are defined in a pom.xml file (parent or not) of the project.
- Artifact repositories are defined in settings.xml: in traditional desktop installation it would be ~/.m2/settings.xml
- Private repos with https and self-signed certificate

## Setup Nexus
Here, I will describe how I install Nexus to test my configuration. The Nexus will be installed through an operator in Openshift 4.2.

### Install the operator
From the the openshift 4.2 console, as an admin, 

- Create a airgap project,
- install nexus3 operator from the operatorhub
  ![image](https://user-images.githubusercontent.com/650571/73340197-961abf00-427a-11ea-835d-1b580b8a105a.png)
- `Create Nexus` by going to `Installed Operators` and the `Nexus` tab
  ![image](https://user-images.githubusercontent.com/650571/73340281-bcd8f580-427a-11ea-918b-6ac2e7ff4271.png)
- Once nexus is started, access to nexus
  ![image](https://user-images.githubusercontent.com/650571/73340338-d712d380-427a-11ea-9686-ade607148ccc.png)
- Login as `admin`, you can get to the generated admin password which is located in `/nexus-data/admin.password` of the nexus pod
- Change the admin password from nexus profile.

### Upload artifacts of our project.
- Download https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app/releases/download/20191216-local/local.zip that contains all the artifacts for our project.
- Go to the folder `m2repo`
- Run the the command (replacing <ADMINPASSWORD> and <URL> with the right values). Run the command 1 time for maven-snapshot and another time for maven-release. The URLs could be retrieve from Nexus console:
  ![image](https://user-images.githubusercontent.com/650571/73340462-0d505300-427b-11ea-80d0-63f987940abb.png)
  ```
  find . -type f -not -path '*/\.*' -not -path '*/\^archetype\-catalog\.xml*' -not -path '*/\^maven\-metadata\-local*\.xml' -not -path '*/\^maven\-metadata\-deployment*\.xml' | sed "s|^\./||" | xargs -I '{}' curl -u "admin:<ADMINPASSWORD>" -X PUT -v -T {} <URL>{} ;
  ```

## Start the test workspace
Start a workspace from this devfile: https://gist.githubusercontent.com/sunix/4bcef770db4985b5b768a6c81ab9f82c/raw/devfile.yaml

This devfile will set user.home to /project for the quarkus-backend-dev container.

## Disconnect from central.
My cluster is connected to the internet, to fake disconnection from the internet, I am disabling central repo in the project pom.xml.

Edit the pom.xml and add:

```xml
    [...]
    </profile>
  </profiles>
  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <url>http://nowhere</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
  <repositories>
    <repository>
       <id>central</id>
       <releases>
         <enabled>false</enabled>
       </releases>
       <snapshots>
         <enabled>false</enabled>
       </snapshots>
       <url>http://nowhere</url>
    </repository>
  </repositories>
</project>
```
That will disable central

Clean the folder /project/.m2/repository from the quarkus-backend-dev container:

    rm /project/.m2/repository -rf

Now if you run the command `build JVM quarkus-backend`, it should fail.

Same opening `Post.java` file should start the language server then, shows errors in  `pom.xml`.
![image](https://user-images.githubusercontent.com/650571/73340939-ed6d5f00-427b-11ea-9565-4582bd82d363.png)

![image](https://user-images.githubusercontent.com/650571/73340957-f4946d00-427b-11ea-8a99-35c650e5485d.png)


## Define repositories in pom.xml

The first way to setup our internal nexus repo to be used by our project is to set the repo in the pom.xml file (could also be a parent pom.xml).


Copy the `maven-releases` and `maven-snapshots` URLs and add the repositories with the right URLs:
![image](https://user-images.githubusercontent.com/650571/73341024-17268600-427c-11ea-8023-cb43f7adb4fe.png)

```xml
  </profiles>
  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <url>http://nowhere</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
    <pluginRepository>
       <id>my-nexus-snapshots</id>
       <releases>
         <enabled>false</enabled>
       </releases>
       <snapshots>
         <enabled>true</enabled>
       </snapshots>
       <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-snapshots/</url>
    </pluginRepository>
    <pluginRepository>
       <id>my-nexus-releases</id>
       <releases>
         <enabled>true</enabled>
       </releases>
       <snapshots>
         <enabled>false</enabled>
       </snapshots>
       <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-releases/</url>
    </pluginRepository>
  </pluginRepositories>
  <repositories>
    <repository>
       <id>central</id>
       <releases>
         <enabled>false</enabled>
       </releases>
       <snapshots>
         <enabled>false</enabled>
       </snapshots>
       <url>http://nowhere</url>
    </repository>
    <repository>
       <id>my-nexus-snapshots</id>
       <releases>
         <enabled>false</enabled>
       </releases>
       <snapshots>
         <enabled>true</enabled>
       </snapshots>
       <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-snapshots/</url>
    </repository>
    <repository>
       <id>my-nexus-releases</id>
       <releases>
         <enabled>true</enabled>
       </releases>
       <snapshots>
         <enabled>false</enabled>
       </snapshots>
       <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-releases/</url>
    </repository>
  </repositories>
</project>
```

### Checking Language Server
Adding these lines to the `pom.xml` should fix the errors of the `pom.xml`.


### Checking Maven command line
Clean the folder `/project/.m2/repository` from the `quarkus-backend-dev` container:

```
rm /project/.m2/repository -rf
```

Now if you run the command `package JVM quarkus-backend` should succeed.

## Define repositories in settings.xml
The second way to setup our internal nexus repo to be used by our project is to set the repo in the `HOME/.m2/settings.xml` file. Unfortunately, this is not something we can inject from the devfile (see Injecting `settings.xml`). However it works, if you create it after the first workspace loading and still painful to recreate it each time a workspace is recreated.


Revert the changes done in the previous section (keep the override of maven central).


Clean the folder `/project/.m2/repository` from the `quarkus-backend-dev` container:

```
rm /project/.m2/repository -rf
```

Make sure errors appears again when running the package command or openning the `pom.xml`


Create a `settings.xml` file from the `quarkus-backend-dev` container (change the URLs):
```xml
cat <<EOF > /project/.m2/settings.xml
<settings>
  <profiles>
    <profile>
      <id>my-nexus</id>
      <pluginRepositories>
        <pluginRepository>
           <id>my-nexus-snapshots</id>
           <releases>
             <enabled>false</enabled>
           </releases>
           <snapshots>
             <enabled>true</enabled>
           </snapshots>
           <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-snapshots/</url>
        </pluginRepository>
        <pluginRepository>
           <id>my-nexus-releases</id>
           <releases>
             <enabled>true</enabled>
           </releases>
           <snapshots>
             <enabled>false</enabled>
           </snapshots>
           <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-releases/</url>
        </pluginRepository>
      </pluginRepositories>
      <repositories>
        <repository>
           <id>my-nexus-snapshots</id>
           <releases>
             <enabled>false</enabled>
           </releases>
           <snapshots>
             <enabled>true</enabled>
           </snapshots>
           <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-snapshots/</url>
        </repository>
        <repository>
           <id>my-nexus-releases</id>
           <releases>
             <enabled>true</enabled>
           </releases>
           <snapshots>
             <enabled>false</enabled>
           </snapshots>
           <url>http://nexus3-airgap.apps.cluster-acme.com/repository/maven-releases/</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>my-nexus</activeProfile>
  </activeProfiles>
</settings>
EOF
```
### Checking Language Server
Clean the folder `/project/.m2/repository` from the `quarkus-backend-dev` container:

    rm /project/.m2/repository -rf

Open `Post.java` should start the language server (if not restart, make a change in `pom.xml` to trigger the build). No error should appear.


### Checking Maven command line
Clean the folder `/project/.m2/repository` from the `quarkus-backend-dev` container:

    rm /project/.m2/repository -rf


Now if you run the command `package JVM quarkus-backend` should succeed.

## TLS with self signed certificate for Nexus
### Configure Nexus with TLS and self-signed certificate

We are going to add a new route with tls and a self signed certificate that we create:


Create the certificate (adapt the CN with your hostname)


    openssl req -x509 -newkey rsa:4096 -sha256 -nodes -keyout tls.key -out tls.crt -subj "/CN=*.acme.com" -days 365


Create a new route in the project where the nexus operator cluster is deployed:

```bash
$ oc project airgap
$ oc create route edge snexus --service=nexus3 --cert=tls.crt --key=tls.key
$ oc describe Route snexus

Name:                        snexus
Namespace:                airgap
Created:                3 hours ago
Labels:                        app=nexus3
Annotations:                openshift.io/host.generated=true
Requested Host:                snexus-airgap.apps.cluster-acme.com
                          exposed on router default (host apps.cluster-acme.com) 3 hours ago
Path:                        <none>
TLS Termination:        edge
Insecure Policy:        <none>
Endpoint Port:                http
Service:        nexus3
Weight:                100 (100%)
Endpoints:        10.131.0.182:8081
```

Change in `settings.xml` all the URLs and use https://snexus-airgap.apps.cluster-acme.com as a base host of each URLs.

Executing a build after having cleaned up the repo should fail:

![image](https://user-images.githubusercontent.com/650571/73342724-6fab5280-427f-11ea-9738-f69c3d73b65b.png)

## Create, Upload truststore and setup
Steps to configure maven to trust our certificate:

- Create a Java truststore with the certificate
- Upload it so it is available in the containers
- Tell Maven to use it

### Create truststore
```
$ keytool -import -file tls.crt -alias nexus -keystore truststore.jks -storepass changeit

Owner: CN=*.acme.com
Issuer: CN=*.acme.com
Serial number: a2a3c33767e4a67f
Valid from: Tue Jan 28 11:28:00 CET 2020 until: Wed Jan 27 11:28:00 CET 2021
Certificate fingerprints:
         MD5:  B5:3B:4A:C6:11:EA:29:47:09:59:0D:3E:71:85:5C:AE
         SHA1: 93:BF:0D:4B:9D:81:F4:36:EB:EE:E3:89:BB:16:51:FD:31:EF:53:5E
         SHA256: 19:87:B0:C2:8E:78:6D:47:EB:FE:D1:D3:4C:04:2B:A2:28:02:42:E4:01:FD:1A:22:08:03:C0:C2:7C:C2:E8:A6
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 4096-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 52 F3 95 35 E6 82 AC D3   F3 57 74 54 4F FB FE 88  R..5.....WtTO...
0010: B4 8A E0 EA                                        ....
]
]

#2: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 52 F3 95 35 E6 82 AC D3   F3 57 74 54 4F FB FE 88  R..5.....WtTO...
0010: B4 8A E0 EA                                        ....
]
]
Trust this certificate? [no]:  yes
Certificate was added to keystore
```
Once created upload it in `/projects` (so it is available to all the containers)
![image](https://user-images.githubusercontent.com/650571/73345069-af743900-4283-11ea-8ce2-22b663192dbb.png)

### Checking command line
To have it working from our `build JVM quarkus-backend` (that would actually perform a `mvn package`), we need to tell maven where to find the certificate. In the devfile, I have added to the environment variable MAVEN_OPTS:
![image](https://user-images.githubusercontent.com/650571/73345100-c4e96300-4283-11ea-8ac4-c8613cd1c11b.png)
And restarting the workspace, it works:
![image](https://user-images.githubusercontent.com/650571/73345150-d7fc3300-4283-11ea-9c7b-6661eb6f9cfd.png)

### Checking Language Server
The embedded maven does not seem to rely on MAVEN_OPTS. I have tried to add the option in the preferences: `File > Settings > Open Preferences > Java > jdt.ls.vmargs`
![image](https://user-images.githubusercontent.com/650571/73345205-f2cea780-4283-11ea-848b-3b06b64e6d8b.png)

But it doesn’t work ...

Related issue:

https://github.com/redhat-developer/vscode-java/issues/455

## Concerns and issues
To summarize:

- Private repos defined in project (or parent) pom.xml: OK
- Private repos defined in settings.xml: OK but need additional manual steps
- Private repos accessible through HTTPS with self signed certificate
  - Maven CLI (in runtime container): OK  but need additional manual steps (to inject the truststore file)
  - JDT.ls KO

### Injecting settings.xml
Unfortunately, there is no way to inject a settings.xml file from the devfile.

https://github.com/eclipse/che-theia/pull/429 is not usable: it only deals with one external mirror where most of the customers may have more than just mirrors to configure their airgap in settings.xml:

- user/password to access to internal server (repositories)
- Several private repos and configurations
- Several  mirrors

Che should allow injecting such files or environment variable through the devfile with secrets maybe. This kind of config files may need to be shared across an organisation (team, BU). Some other files would be more personal

Related issue that may need to be reprioritized:

- https://github.com/eclipse/che/issues/14680

### Self signed certificate
At some point we would need to inject the truststore. Maybe https://github.com/eclipse/che/pull/15218 and/or kubernetes secrets https://github.com/eclipse/che/issues/14680 are good starting points.

Also I could not manage to configure the embedded m2e/JDT.ls maven to work with my truststore. Following https://github.com/redhat-developer/vscode-java/issues/455 

https://github.com/eclipse/che/issues/14680 would be nice. It could also be secrets that would be shared by several users of the same organisation. But I would not recommend adding the file contents in the devfile (though it would be useful for testing purposes). These files would generally contain token, password, sensitive information that should not be shared in a git repo. So a devfile is not appropriate.

**Comment by snjeza** [comment]
@sunix see https://github.com/redhat-developer/vscode-java/issues/455#issuecomment-580660715

**Comment by sunix** [comment]
> @sunix see [redhat-developer/vscode-java#455 (comment)](https://github.com/redhat-developer/vscode-java/issues/455#issuecomment-580660715)

Thanks, I have updated the previous doc

**Comment by slemeur** [comment]
@rkratky : We need to put this into the documentation. Would you be able to take that into account for 7.9 ?

**Comment by slemeur** [comment]
@rhopp and @dmytro-ndp : This is important capabilities. we should have automated tests for this. Is that something you can work on?
