### ISSUE TITLE
Overriding memory limits in devfiles can cause workspaces to break when rolling out new versions of Che

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15509]
### Describe the bug
Some of our devfiles (e.g. [camel-springboot](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/apache-camel-springboot/devfile.yaml#L15)) require memory limits to be overridden to run on che.openshift.io (where the default quota is `3Gi`). This can however cause issues if a later update to a plugin increases memory requirements, since the memory limit in the devfile will not automatically be updated for existing workspaces

### Steps to reproduce
1. Deploy Che 7.3.2, create workspace using camel-springboot devfile
    - This workspace will be configured to use `redhat/vscode-apache-camel/latest` with an overridden memory limit of `200Mi`.
2. Build plugin registry off PR https://github.com/eclipse/che-plugin-registry/pull/325 and roll it out to your deployment
    - (this simulates what would happen if this PR is merged for 7.6.0 and you update Che to 7.6.0)
3. Restart your camel-springboot workspace, potentially hitting an OOM error.

### Expected behavior
I honestly don't have a good solution in mind here, this is a tricky problem.

- If we avoid overriding memory limits in devfiles, the issue does not occur (`latest` will always have an appropriate memory limit).
- On the other hand, going this way means that devfiles can go over `3Gi` after an update and so not be startable on che.openshift.io.

With one option, we risk breaking existing workspaces on update, with the other, we risk making workspaces not runnable on che.openshift.io.

### Additional context
https://github.com/eclipse/che-plugin-registry/pull/325

**Comment by l0rd** [comment]
Maybe we should just show a warning toaster when starting theia if:
- the memory limit is overwritten in the devfile
- the devfile memory limit < the plugin memory limit

**Comment by tsmaeder** [comment]
I think it's sufficient if we make it easy for the user to realize that out of memory has occurred and what to do to fix that. We cannot prevent all OOM for every case, so it's something the user needs to deal with anyway, so if we make that case easy to handle, it works for the described scenario, as well.

**Comment by amisevsk** [comment]
The only problem is that "what to do to fix that" is a confusing proposition as it stands; memory limits for plugins can be set in two places:
1. In the plugin meta.yaml, as a default that's used when no override is defined
2. In each devfile individually, which needs to be done for some devfiles since the limits in 1. are generally on the generous side. Setting a limit here might mean that on your next rollout of Che, you have to repeat the process, though.

Additionally, dialing in a suitable limit can be very tricky, since once a workspace starts, memory pressure can cause silent errors (sometimes processes are killed, sometimes the pod is killed and you have to look into cluster events). 

I've created https://github.com/eclipse/che/issues/15532 for additional UX improvements on this.
