### ISSUE TITLE
Provide RELEASE.md files with the release instructions to all the related repositories

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15506]
### Is your task related to a problem? Please describe.
List of components / repositories where the `RELEASE.md` files should be created:

- [x] che-theia https://github.com/eclipse/che-theia/blob/master/RELEASE.md
- [x] che-machine-exec - https://github.com/eclipse/che-machine-exec/pull/68 + https://github.com/eclipse/che-machine-exec/pull/71 (make-release.sh script)
- [x] che-plugin-registry https://github.com/eclipse/che-plugin-registry/pull/361 (make-release.sh script)
- [x] che-devfile-registry - https://github.com/eclipse/che-devfile-registry/pull/176 + https://github.com/eclipse/che-devfile-registry/pull/180 (RELEASE.sh script)
- [x] che https://github.com/eclipse/che/pull/15668 PR merged but followup work required to provide more details in order to make this vague process scriptable
   - [x] che-parent
   - [x] che-docs 
   - [x] che 
- [x] che-operator  https://github.com/eclipse/che-operator/pull/152
- [x] chectl - https://github.com/che-incubator/chectl/pull/443
- [x] che-plugin-broker https://github.com/eclipse/che-plugin-broker/pull/90

The `RELEASE.md` should contain a clear set of instructions required for both general and bugfix releases.

**Comment by ibuziuk** [comment]
PR for for che-machine-exec - eclipse/che-machine-exec#68

**Comment by nickboldt** [comment]
To better track work in progress i've started this sheet:

https://docs.google.com/spreadsheets/d/1CnFjcwJeNgAahMv4EQq6-uGHpU09EeheeZO7kt4UMtg/edit?folder=0ALk9kk_xmhjNUk9PVA#gid=0

**Comment by ibuziuk** [comment]
@nickboldt why do we need yet another gdoc? the point of this issue is to move from gdoc to RELEASE.md

**Comment by davidfestal** [comment]
@tolusha do you confirm you're finally planning to work on the operator side of this ?

**Comment by tolusha** [comment]
@davidfestal 
confirm

**Comment by tolusha** [comment]
PR for `che-operator`
https://github.com/eclipse/che-operator/pull/152

**Comment by gazarenkov** [comment]
Who's working on che-plugin-registry?

**Comment by nickboldt** [comment]
I believe that one is owned by @ibuziuk but ... afaict it's basically the same as the README/script for che-machine-exec or devfile registry, except with one additional step: generating the latest 2 plugins meta.yaml for che-machine-exec and che-theia.

So for $VERSION = 7.8.0 I could be talked into taking that one over and scripting it:

* copy https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml into new folder $VERSION/; sed replace three lines:
- `firstPublicationDate` moves to today
- `version: nightly` becomes `version: $VERSION`
- `image: ...:nightly` becomes `image: ...:$VERSION`

* Then repeat for che-theia, but using `:next` instead of `:nightly` because for some reason they're not  using the same euphemism for 'latest'. 

* Then tag/branch as for che-devfile-registry * che-machine-exec releases.

**Comment by ibuziuk** [comment]
PR for plugin-registry has been sent - https://github.com/eclipse/che-plugin-registry/pull/360
@vparfonov could you please finalize the docs for parent, docs, che and I believe we will be able to close the issue after that :crossed_fingers:

**Comment by nickboldt** [comment]
PR for plugin reg merged. Followup (copy tweaks and new make-release.sh script): 

https://github.com/eclipse/che-plugin-registry/pull/361

Similar tweaks for consistency in devfile reg:

https://github.com/eclipse/che-devfile-registry/pull/187

**Comment by ibuziuk** [comment]
@nickboldt is there anything else expected from Hosted Che team regarding the release instructions or can we close the issue ?

**Comment by nickboldt** [comment]
Waiting on content from @vparfonov and @mkuznyetsov  -- the release.md for che is incomplete and we're missing equivalent instructions for che-dev, che-lib, che-parent, che-docs.

**Comment by ibuziuk** [comment]
Just for the record `che-lib` cease to exist

**Comment by nickboldt** [comment]
Yes, we only need che-parent, che-doc, and che pushed to maven central now. Hooray for simplified releases. (Meanwhile, >20 sidecar images...) :|

**Comment by amisevsk** [comment]
PR for che-plugin-broker merged: https://github.com/eclipse/che-plugin-broker/pull/90

**Comment by nickboldt** [comment]
Instructions exist for che-parent, docs and che, but they're in dire need of more details.

https://github.com/eclipse/che-parent/blob/master/RELEASE.md#4-closerelease-staging-repository-on-nexus
* who has permission?
* what is required to be done?
* can we automate this like we did for JBoss Tools releases to JBoss Nexus ? 

https://github.com/eclipse/che-parent/blob/master/RELEASE.md#1-create-branch-for-release-preparation-and-next-bugfixes
* don't you create a tag in the branch as well?

Same questions for docs and che.

^^ @vparfonov @mkuznyetsov ^^

**Comment by nickboldt** [comment]
Resolving. Followup work in the 2 linked issues.
