### ISSUE TITLE
Document Airgap Setup for C#

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15511]
Test and document the process of setting up an airgap solution for C# with nuget. In particular, configure a workspace based on our default C# devfile to use a nuget repository that uses a self-signed certificate.

**Comment by svor** [comment]
The way to set up AirGap solution for C# was documented in https://docs.google.com/document/d/1netzMrXRMhdC7CKJXofhYFQOgIAmfgkanBXdOjOctqk/edit#bookmark=id.daxp582dhyuy
