### ISSUE TITLE
Document Airgap Setup for Gradle

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15510]
Test and document the process of setting up an airgap solution for Gradle. In particular, configure a workspace based on our default gradle devfile to use a repository that uses a self-signed certificate.

This will probably involve the use of a maven init script. Documentation in this issue, for the moment.

**Comment by svor** [comment]
The document with AirGap solution is here: https://docs.google.com/document/d/1t34uXwIfbRn1u6aDidj2iFRzxXtwdWORRyEWeYotVFE/edit?usp=sharing

**Comment by tsmaeder** [comment]
I commented on the doc. The general "problem" seems to be that the approach to air-gapping is based on changing files inside the project. Did you investigate an approach that can work for any project you check out? For example, changing ~/.m2/settings.xml overrides repos for all project we checkout into the workspace.

**Comment by svor** [comment]
It is also possible to configure it globally, I've added how to do that here https://docs.google.com/document/d/1t34uXwIfbRn1u6aDidj2iFRzxXtwdWORRyEWeYotVFE/edit#bookmark=id.rsxt9icf51jc
