### ISSUE TITLE
Move QE jobs from codenvy CI to Centos CI

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#15517]
### Is your task related to a problem? Please describe.
Need to add our jobs to ci.centos.org as ci.codenvycorp.com will be decomissioned.
More info: https://hackmd.io/BGMTro5tTNqWNc3oVRqK0g?both

**Comment by musienko-maxim** [comment]
On this moment we finished creating working skeletons for the moving of the legacy jobs and created base shell script which install dependencies and launch test-infrastructure  with CHE. We finished the first nightly job for launching  the happy-path  scenario: https://ci.centos.org/view/Devtools/job/devtools-che-nightly-test-master-happy-path/ on centos ci. This job related on https://ci.centos.org/view/Devtools/job/devtools-che-che-nightly/ and triggered if it has passed successfully.  
Currently we split  the tasks between next participations:


 **Moving nightly jobs:**
 - Move Happy path (P2) job - done
 - Move Devfile tests (P2)- not started

**Move jobs with Java selenium tests:**
- with OAuth - not started (have issues)
- Hot update -  not started (have issues)
- Multiuser stable - in progress
- Multiuser all - in progress


**Moving PR-checks jobs:**
- Move che-pullrequests-test-ocp job - in progress

**Moving Java selenium releases jobs:**
     - Move Multiuser stable - in progress
     - Setup jobs to be triggered by push to some "qe" branch - in progress
     - Move Multiuser all - not started 
     - Move Hot update - not started

**Moving other releases jobs:**
Happy Path - not started (it's on crw jenkins)
Devfiles tests - not started (it's on crw jenkins)
OCP OAuth - not started (it's on crw jenkins)
    
At this point we are defining the common parts from all jobs and move out to the utils-script for avoiding code duplication and improving some actions for the test execution.

**Comment by dmytro-ndp** [comment]
It was decided that in PR check on ci.centos we can push testing che-server image to quay.io as following: `quay.io/eclipse/che-server:pr-12345`, where **12345** is an example of PR id.

**Comment by nickboldt** [comment]
We have completely moved only two jobs as for now:
* https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/
* https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-build/

**Comment by rhopp** [comment]
AFAIK every QE job from codenvy CI was moved to Centos CI... I believe this issue can be closed. 
Right, @SkorikSergey @musienko-maxim @artaleks9?

**Comment by SkorikSergey** [comment]
> AFAIK every QE job from codenvy CI was moved to Centos CI... I believe this issue can be closed.
> Right, @SkorikSergey @musienko-maxim @artaleks9?

We still need to check working of `rc` jobs. And merge `rc` scripts to master branch.

**Comment by rhopp** [comment]
Last PR merged: https://github.com/eclipse/che/pull/16039
