### ISSUE TITLE
Make sure hosted che  can work with default namespace strategy <username>-che

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15519]
### Is your task related to a problem? Please describe.
We need to make sure that the behavior of che.openshift.io remains the same after
upgrade of Che >=7.4 
In this version, we introduced a new default namespace strategy   '<username-che>`. However, hosted che
has a custom namespace project factory that may handle this use-case.
We need to figure out what the actual state for now.

- https://github.com/redhat-developer/rh-che/blob/master/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8OpenShiftProjectFactory.java
- https://github.com/redhat-developer/rh-che/blob/master/plugins/fabric8-multi-tenant-manager/src/main/java/com/redhat/che/multitenant/Fabric8WorkspaceEnvironmentProvider.java

### Describe the solution you'd like
dig and research

### Describe alternatives you've considered
n/a
### Additional context
- Invalid default namespace name https://github.com/eclipse/che/issues/15323

**Comment by ibuziuk** [comment]
@skabashnyuk I have tested the workspace startup against devcluster with rh-che updated to the latest 7.6.0 upstream. A dedicated user has been provisioned with `test.username` 

![image](https://user-images.githubusercontent.com/1461122/71241007-d0538100-230a-11ea-98d1-3a650c2761cf.png)

workspace startup for this user works just fine. Note that for this user the following namespaces were provisioned on Hosted Che:

![image](https://user-images.githubusercontent.com/1461122/71240957-b1ed8580-230a-11ea-9c44-d4e6d58031fe.png)
