### ISSUE TITLE
Implement Language filter on Get Started page of dashboard

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15525]
### Is your task related to a problem? Please describe.
This is about implementing Language Filters for Get Started page:
![68426915-2b744e80-0177-11ea-8a6c-8e9e056dbc10](https://user-images.githubusercontent.com/5887312/71086202-ebef4800-21a1-11ea-86e0-c80dfd05ae73.png)

Currently, Che Devfile Registry provides the following metadata:
```
displayName: Go
description: Stack with Go 1.12.10
tags: ["Debian", "Go"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 1686Mi
```

Where `Go` is related to language and `debian` to technology (I guess but not sure =) ).
To provide Language filter in dashboard, we could hard-code languages and every non-known tags - propagate as Technology.
But it would be more straightforward and reliable if we rework devfile metadata to provide dashboard needed info, like:
```
displayName: Java Web
description: Stack with Tomcat 8
languages: ["Java"]
tags: ["Fedora", "Tomcat"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 1686Mi
```

So, the scope of this issue to develop a way to go with Language filters and implement it.

**Comment by sleshchenko** [comment]
Controller team discussed this issue and agreed that it's an easier option to go with Language filter only since it's not really clear what `technologies` list should include. 
And since we have a few devfiles per each language - it should not be an issue for a user to find the needed sample.
The biggest I found - java
![Screenshot_20191218_164423](https://user-images.githubusercontent.com/5887312/71103999-cb37ea00-21c3-11ea-8dac-95e30e65674f.png)

@beaumorley WDYT? Are you OK with such an option to go?

**Comment by beaumorley** [comment]
Agree with you all. One field for the filter sounds right. However, I'm curious what the filter is filtering on? If the name of the field was not "Language" but was more ambiguous like just "Search", could it filter on both language and technology?

This also begs asking the question as to how many devfiles there will ever be in the list. A while back I was told it is about 14 now? I would say that if the list could grow we may want to support a more open filter. If not, sticking to just language may be fine..

**Comment by sleshchenko** [comment]
> This also begs asking the question as to how many devfiles there will ever be in the list. A while back I was told it is about 14 now? I 

Now on production(che.openshift.io), we have 19, in the master branch 25.

> If the name of the field was not "Language" but was more ambiguous like just "Search", could it filter on both language and technology?

Exactly! But then user should type request but not choose from list. We're going to implement common search input as a first step, it will be full-text search by Tags, Name, Description. You can try it on https://che.openshift.io/dashboard/#/stacks or see gif below:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5887312/71153342-8f436a00-2241-11ea-80f1-d7efde678f28.gif)

If it's good enough for time being - we can just close this issue and reopen later if needed.

@beaumorley

**Comment by sleshchenko** [comment]
Decided that full-text search implemented in https://github.com/eclipse/che/pull/15642 is good enough for the time being
