### ISSUE TITLE
[Quarkus] tasks.json file is overridden by quarkus extension

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15523]
VS Code Quarkus extension contributes new task into tasks.json, it happens when user executes `Quarkus: Debug current Quarkus project `command. As a result `.theia/.tasks.json` is updated and loses all previous tasks.

**Comment by svor** [comment]
After quick investigation I see that the extension checks if `.vscode/tasks.json` exists and if it doesn't, it calls the API to update tasks configuration
```typescript
workspace.getConfiguration('tasks', this.workspaceFolder.uri).update('tasks', []);
```
this code writes empty list of tasks into `.theia/.tasks.json` and removes all existed tasks in `.theia/.tasks.json`.

**Comment by tsmaeder** [comment]
@svor that sounds like a bug in VS Code-Quarkus, though: I don't think the existence of the fiel tasks.json in official API. Shouldn't they go through API to check for preexisting tasks?

**Comment by svor** [comment]
@tsmaeder I agree that changes should be provided into VS Code Quarkus extension, because it doesn't use API to check for preexisting tasks, they just check if `/.vscode/launch.json` file exists 
```typescript
fs.existsSync(workspaceFolder/.vscode/launch.json)
```
and it works for vscode but doesn't work for theia.
