### ISSUE TITLE
[chectl] Installation of Eclipse Che on minikube using helm failed because of parse error in che/templates/configmap.yaml

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15534]
### Describe the bug
Installation of _SingleUser Che_ on minikube 1.11 using **helm** failed because of error:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/master/job/Che-Theia-master-check-E2E-Happy-path-tests-against-K8S/1053/console
```
[10:48:55] 🏃‍  Running Helm to install Che [failed]
[10:48:55] → Unable to execute helm command helm upgrade --install che --force --namespace che --set global.ingressDomain=10.0.100.234.nip.io --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace=che   /home/hudson/.cache/chectl/templates/kubernetes/helm/che/ / Error: parse error in "che/templates/configmap.yaml": template: che/templates/configmap.yaml:136: unexpected EOF
Error: Unable to execute helm command helm upgrade --install che --force --namespace che --set global.ingressDomain=10.0.100.234.nip.io --set cheImage=eclipse/che-server:nightly --set global.cheWorkspacesNamespace=che   /home/hudson/.cache/chectl/templates/kubernetes/helm/che/ / Error: parse error in "che/templates/configmap.yaml": template: che/templates/configmap.yaml:136: unexpected EOF
    at HelmTasks.<anonymous> (/usr/local/lib/chectl/lib/tasks/installers/helm.js:370:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:107:62)
```

### Che version

 - [ ] latest
 - [x] nightly
 - [x] other: 7.6.0 RC

### Steps to reproduce
Try to install che on minikube 1.11 using the next command of _chectl:next_:
> /usr/local/bin/chectl server:start --k8spodreadytimeout=180000 --templates=che/deploy/ --platform=minikube --listr-renderer=verbose

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.11 (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next using helm 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by l0rd** [comment]
Doesn't look like a chectl problem but rather a `{{end}}` tag missing in the helm template. C.f. this commit by @monaka https://github.com/eclipse/che/commit/b06e062e4d94b7af5f682fcd415a34ed7b3e110d#diff-7e81184b59cb2730e14842271ecf4261
