### ISSUE TITLE
unzip package not included in che-golang base image breaks protoc pipeline

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#15533]
### Describe the bug

google protobuff compiler protoc is released in zip, che-golang base image is debian stretch and doesn't come with unzip package installed, gunzip and zcat give "unknown suffix" error when trying to decompress the files.
error:
bash-4.4 ~ $ gunzip protoc-3.11.2-linux-x86_64.zip 
gzip: protoc-3.11.2-linux-x86_64.zip: unknown suffix -- ignored

### Che version

 - [ ] latest
 - [ *] nightly
 - [ ] other: please specify

### Steps to reproduce
from within che workspace with golang plugin included, open a golang cli console and input:
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip

### Expected behavior

Archive:  protoc-3.11.2-linux-x86_64.zip
   creating: include/
   creating: include/google/
   creating: include/google/protobuf/
  inflating: include/google/protobuf/type.proto
  inflating: include/google/protobuf/duration.proto
  inflating: include/google/protobuf/empty.proto
  inflating: include/google/protobuf/wrappers.proto
  inflating: include/google/protobuf/field_mask.proto
   creating: include/google/protobuf/compiler/
  inflating: include/google/protobuf/compiler/plugin.proto
  inflating: include/google/protobuf/struct.proto
  inflating: include/google/protobuf/any.proto
  inflating: include/google/protobuf/descriptor.proto
  inflating: include/google/protobuf/source_context.proto
  inflating: include/google/protobuf/timestamp.proto
  inflating: include/google/protobuf/api.proto
  inflating: bin/protoc
  inflating: readme.txt

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ *] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ *] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ *] LXC 
   - [ ] other: please specify

**Comment by gattytto** [comment]
https://github.com/docker-library/golang/pull/312

**Comment by gattytto** [comment]
as stated by the maintainer in the mentioned issue https://github.com/docker-library/golang/pull/312 this will require additional work over the base image. 

I will close this and open a gRPC specific issue, it involves the languages capable of producing native binaries that include gRPC and protobuf implementations like Node, Quarkus, Golang, C, etc.

**Comment by linquize** [comment]
You should use `unzip` to decompress `*.zip` file, but not `gunzip`
