### ISSUE TITLE
Detect OOMs in plugins and notify user on steps to remediation

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15532]
### Is your enhancement related to a problem? Please describe.
Currently, with https://github.com/eclipse/che/pull/15449 merged, Che can detect a container stopping due to OOM during start up, but the message is not very helpful to the user:

![Screenshot from 2019-12-18 09-08-12](https://user-images.githubusercontent.com/16168279/71097764-29d67700-2176-11ea-8c68-ce8a6353bb70.png)

Getting plugin memory limits right is one of the most frustrating things about designing your own devfile, and it can be confusing figuring out how much memory is required for each plugin.

### Describe the solution you'd like
1. Che should look for OOMKilled container stops specifically and show a notification to the user explaining
    a. How to resolve the issue (if it's overridden in the devfile, increase the limit there; otherwise open a GH issue)
    b. (maybe) Suggest the user revert to a known-working version if they are using latest (in case a rollout deployed a new version of the plugin that takes more memory

2. (Potentially a separate issue) Che / Che Theia should be able to see if any container in a workspace stopped due to OOMKilled or is under memory pressure, and suggest to the user that the current limit is not enough.

### Describe alternatives you've considered
As it stands (and as some of our plugin contributors can surely attest to), it is currently very difficult to set an accurate memory limit for plugins. For some plugins, memory use will depend directly on the project imported into the workspace, so even setting a suitable limit for one project may not work if a more complicated project is imported into the same devfile. With this additional info, it should be easier to configure both plugins and devfiles that use them to avoid problems.

**Comment by gazarenkov** [comment]
@amisevsk still actual?

**Comment by amisevsk** [comment]
This issue can probably be closed; once DWO is used as default detecting failure events will be the job of DWO, not Che server.

**Comment by amisevsk** [comment]
If a similar problem arises, a new issue should be created in github.com/devfile/devworkspace-operator.
