### ISSUE TITLE
pod devfile-registry goes in crashloopbackoff after

### ISSUE THREAD

**Issue by gaord** [eclipse-che/che#15547]
### Describe the bug

After setting up airGapContainerRegistryOrganization and airGapContainerRegistryHostname, all pods get recreated except for devfile-registry, that logs read as below:
```
Checking devfile /var/www/html/devfiles/apache-camel-springboot/devfile.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to openshift
Checking devfile /var/www/html/devfiles/python-django/devfile.yaml
    Updating image registry to image-registry.openshift-image-registry.svc:5000
    Updating image organization to openshift
Updating devfiles to point at internal project zip files
sed: couldn't open temporary file /var/www/html/devfiles/sedTjeMyG: Permission denied`
```

### Che version
che 7.5.1 on OpenShift 4.2.7 installed from operator hub

### Steps to reproduce

1. Do configuration on cheCluster for addition of so-called airgap
2. check pods recreated
3. See the error logs with pod devfile-registry

### Expected behavior
devfile-registry pod should be recreated as usual

**Comment by amisevsk** [comment]
I'm able to reproduce this issue, both on 7.5.1 and nightly; looks like the `/var/www/html/devfiles` directory has bad permissions.

**Comment by amisevsk** [comment]
PR with fix: https://github.com/eclipse/che-devfile-registry/pull/181

**Comment by nickboldt** [comment]
In CRW 2.0 dockerfile, we do:

```
RUN chmod -R g+rwX /build/devfiles
```
(same in https://github.com/eclipse/che-devfile-registry/blob/master/build/dockerfiles/Dockerfile#L28 )
and
```
COPY --from=builder /build/devfiles /var/www/html/devfiles
```
(same in https://github.com/eclipse/che-devfile-registry/blob/master/build/dockerfiles/Dockerfile#L33 )

Isn't that enough to set perms and then copy over files?

You even do an extra chmod after caching projects and images:

```
RUN ./cache_projects.sh devfiles resources && \
    ./cache_images.sh devfiles resources && \
    chmod -R g+rwX /build
```
https://github.com/eclipse/che-devfile-registry/blob/master/build/dockerfiles/Dockerfile#L43

**Comment by amisevsk** [comment]
The issue is that the directory is created in the `registry` stage and has 755 permissions. No idea why I couldn't reproduce this in CRW though.

**Comment by nickboldt** [comment]
Different user/group setup maybe? 755 might be OK if the user doing the sed is in the correct group. 

Or it's because we're not doing the offline devfile reg in 2.0:

```
# Offline devfile registry build
# FROM builder AS offline-builder
# DO NOT USE FOR CRW (not tested yet)
# Does not work in brew; need to run this online, cache in tarball and add to Brew
# RUN ./cache_projects.sh devfiles resources && \
#     ./cache_images.sh devfiles resources && \
#     chmod -R g+rwX /build
# DO NOT USE FOR CRW (not tested yet)

# FROM registry AS offline-registry
# COPY --from=offline-builder /build/devfiles /var/www/html/devfiles
# COPY --from=offline-builder /build/resources /var/www/html/resources
```
