### ISSUE TITLE
add cpu limits to che-plugin-broker 

### ISSUE THREAD

**Issue by anselmov** [eclipse-che/che#15543]
### Is your enhancement related to a problem? Please describe.
I run che-server 7.5.1 on a corporate k8s cluster where it is required to specify resource limits for every deployment. The workspace creation process fails because there are no cpu limits for workspaceXXXX.che-plugin-broker.

### Describe the solution you'd like
So I tried a dirty fix on [Containers.java](https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Containers.java) which resolves the issue. Now I wonder what would be a clean way to add this cpu limit ? Maybe we can already add it without patching existing code ?

**Comment by anselmov** [comment]
Any update? Thanks.

**Comment by sleshchenko** [comment]
Seems it duplicates https://github.com/eclipse/che/issues/13709.

There already a PR that should fix the described issue https://github.com/eclipse/che/pull/15977
