### ISSUE TITLE
Cannot connect Agent when creating workspace: cannot find or open /mnt/che/ws-agent.zip

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1554]
Running: `docker run -p 80:8080 -p 8000:8000 -p 49152-49162:49152-49162 -v /var/run/
docker.sock:/var/run/docker.sock codenvy/che` on a GCE and trying to create a new workspace shows an error in the web UI of Che:

```
[STDERR] unzip: cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP.
```

The log shows:

```
2016-06-22 14:40:15,953[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 549]    - Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
```

Which port is the agent using? Must it be accessible from the internet?

**Comment by TylerJewell** [comment]
Your docker run syntax is incomplete.
https://eclipse-che.readme.io/docs/usage-docker

The /lib-copy part of the syntax is mandatory.  We take certain assets that are inside of the Che container and move them outside of the container to the docker host with a volume mount that is missing.

**Comment by wernight** [comment]
Ah ok!

**Comment by wernight** [comment]
Perfect! Seems to be getting further but cannot connect: `The workspace agent has been forcefully stopped. This error happens when the agent cannot resolve the location of the Che server. This error can usually be fixed with additional configuration settings in /conf/che.properties.`. Looking at https://eclipse-che.readme.io/docs/networking it seems like I need to expose a port range which is [_not_ supported by Kubernetes](https://github.com/kubernetes/kubernetes/issues/23864). Meaning need to expose ports `32768-65535`!!

PS: I added a 3 comments on https://hub.docker.com/r/codenvy/che/; might we worthwile checking them.

PS 2: Can close this issue. I think all pointer are included here.
