### ISSUE TITLE
Sometimes, Terminal Windows Suddenly Close

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15541]
While doing self-hosting using the process in che-theia/Contributing.md, all terminal windows I have open suddenly close.

### Che version
 nightly (Built 12/19/2019, 12:36:09 AM)

### Runtime
   - [x] minishift (include output of `minishift version` and `oc version`)

### Installation method
  chectl -p minshift -a operator

### Additional context
I haven't been able to reproduce this reliably, but it seems to happen more often when there is a lot of load on the system, like doing `/projects/theia$ yarn`, for example

**Comment by tsmaeder** [comment]
Not sure this is relevant, but right now the terminal disappeared right around the time the following appeard in the log of the theia container:

```
root INFO >>> Storing the layout...
root INFO <<< The layout has been successfully stored.
```

**Comment by tsmaeder** [comment]
I haven't been able to finish a single 'yarn' this morning, so this is really impacting my work.

**Comment by tolusha** [comment]
Try to start minishift/minikube with 4 CPU

**Comment by tsmaeder** [comment]
So you're saying this is a timeout situation?

**Comment by tsmaeder** [comment]
Unfortunately, using 4 cpu's does not help

**Comment by tsmaeder** [comment]
The workaround is to run the build in the openshift console.

**Comment by tolusha** [comment]
@AndrienkoAleksandr 
Do you have any clues?

**Comment by tolusha** [comment]
@tsmaeder 
Just to be sure. How did you set 4cpu?

**Comment by AndrienkoAleksandr** [comment]
Maybe you launched very heave processes and kubernetes api was in down. Our terminal loses connection if kubernetes api is not responsive.

**Comment by tsmaeder** [comment]
> Our terminal loses connection if kubernetes api is not responsive.

That is a problem, in my opinion. High load must not lead to closing the window.

**Comment by tsmaeder** [comment]
@tolusha 
```
C:\Users\thomas\code\chedev\theia\examples\browser>minishift config view
- cpus                               : 6
- disk-size                          : 28GB
- memory                             : 12000
- vm-driver                          : virtualbox
```

**Comment by AndrienkoAleksandr** [comment]
> That is a problem, in my opinion. High load must not lead to closing the window.

Yes, but exec terminal depends on kubernetes api. I think Eclipse Che workspaces doesn't have cpu limit and could grab all cpu resources and make kubernetes api unresponsive.

**Comment by tolusha** [comment]
I am wondering which team should take responsibility for.

**Comment by tsmaeder** [comment]
> I think Eclipse Che workspaces doesn't have cpu limit and could grab all cpu resources and make kubernetes api unresponsive.

I understand that 100%, but it just does not matter: we are actively closing the terminal window instead of waiting for the kubernetes API to become responsive again. Unless there is an overwhelming reason to close that window, it's not what the user wants or expects. That I cannot execute a command is fine, but that I lose the terminal window and all my terminal history and all the output of commands in that window is _not_ what I want.

**Comment by AndrienkoAleksandr** [comment]
> I understand that 100%, but it just does not matter: we are actively closing the terminal window instead of waiting for the kubernetes API to become responsive again. Unless there is an overwhelming reason to close that window, it's not what the user wants or expects. That I cannot execute a command is fine, but that I lose the terminal window and all my terminal history and all the output of commands in that window is not what I want.

Sorry, but if k8s api in down - it's mean you lost exec session. k8s api doesn't provide a way how to restore it, and it doesn't has re-connection feature. So it's mainly issue for k8s api. I don't think, that we can resolve it on our side. Issue should be propagated upper to k8s api... 
P.S.: a bit more information: Eclipse Che machine exec it's a kind of k8s exec "proxy". In the our "proxy", we implemented re-connection and restore previous output. But k8s api itself doesn't provide such features.
