### ISSUE TITLE
che-docs devfile doesn't include runtime container that can run docker, podman, or mvn

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15546]
### Describe the bug
When I load the che-docs devfile, I can see sources, but I can't run any of the build scripts.

So we need to improve the che-docs runtime so it's got more than just jekyll in it:

![image](https://user-images.githubusercontent.com/227597/71203532-21606800-226c-11ea-97df-9e45e2f1e708.png)

### Che version

 - [x] 7.3.2 che.openshift.io

### Steps to reproduce

Load this devfile:

https://che.openshift.io/dashboard/#/load-factory/?url=https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml

When I loaded it the second time, I got commands I could run but the jekyll based `build che-docs` [1] command failed:

![image](https://user-images.githubusercontent.com/227597/71204010-19ed8e80-226d-11ea-8e7d-f787a6be039c.png)

[1] https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml

**Comment by themr0c** [comment]
Looking into it. 

Seems we forgot to update the devfile when updating the image for  quay.io/eclipse/che-docs.
