### ISSUE TITLE
Investigate and get rid new instability in the Happy Path Test for checking PRs

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#15562]
- [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
More details in the failed job: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/1497/console

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by rhopp** [comment]
Closing as not relevant anymore.
