### ISSUE TITLE
Update Debugger for Java and Language support for Java to latest

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15560]
Need to update all Che plugins which contain  Debugger for Java and  Language support for Java extensions to the latest version and test that everything works fine.

**Comment by ibuziuk** [comment]
@svor I put P1 but feel free to change the priority

**Comment by nickboldt** [comment]
Rationale for updating was so that the versions used for both quarkus and non-quarkus containers/devfiles would be consistent... Fewer versions = fewer tests needed to run ;)

**Comment by apupier** [comment]
in first comment it is mentioned  "Language support for Java is 0.54.2.", will you use this specific version? or the latest as indicated in the title?
asking as we require Java 0.55+ for one feature for Apache Camel K

**Comment by svor** [comment]
@apupier the latest, I've updated the description

**Comment by svor** [comment]
It is blocked by https://github.com/eclipse-theia/theia/issues/3765
This [PR]( https://github.com/eclipse-theia/theia/pull/4146) must be finished before continue working on this issue
