### ISSUE TITLE
As Admin I want to grant members of an organization additional cluster roles

### ISSUE THREAD

**Issue by mingfang** [eclipse-che/che#15572]
Currently users can be configured to receive an additional cluster role via this property https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L251

However this setting is applied to all users.
I want to be able to add a list of cluster roles to members of organizations using the dashboard.

**Comment by mingfang** [comment]
Related to https://github.com/eclipse/che/pull/13178

**Comment by skabashnyuk** [comment]
related to https://github.com/eclipse/che/issues/15304#issuecomment-558880903
