### ISSUE TITLE
`chectl workspace:start` command stucks

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15578]
### Describe the bug
chectl had stuck when executed `workspace:start` the command:
```
chectl workspace:start --devfile=test-workspace-devfile.yaml --access-token 
```
where test-workspace-devfile.yaml is from [here](https://github.com/eclipse/che/blob/master/tests/e2e/files/happy-path/happy-path-workspace.yaml)

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/495/console
```
08:15:26 [01:15:25] Retrieving Che Server URL [started]
08:15:26 [01:15:25] Retrieving Che Server URL...http://che-che.10.0.100.185.nip.io [title changed]
08:15:26 [01:15:25] Retrieving Che Server URL...http://che-che.10.0.100.185.nip.io [completed]
08:15:26 [01:15:25] Verify if Che server is running [started]
08:15:26 [01:15:25] Verify if Che server is running...RUNNING (auth enabled) [title changed]
08:15:26 [01:15:25] Verify if Che server is running...RUNNING (auth enabled) [completed]
08:15:26 [01:15:25] Start following workspace logs [started]
08:15:26 [01:15:25] Start following workspace logs...done [title changed]
08:15:26 [01:15:25] Start following workspace logs...done [completed]
08:15:26 [01:15:25] Create workspace from Devfile /mnt/hudson_workspace/workspace/basic-MultiUser-Che-check-e2e-tests-against-k8s/test-workspace-devfile.yaml [started]
08:15:28 [01:15:27] Create workspace from Devfile /mnt/hudson_workspace/workspace/basic-MultiUser-Che-check-e2e-tests-against-k8s/test-workspace-devfile.yaml [completed]
08:15:28 
08:15:28 Workspace IDE URL:
08:15:28 http://che-che.10.0.100.185.nip.io/dashboard/#/ide/admin/petclinic-dev-environment
08:15:28 Eclipse Che logs will be available in '/mnt/hudson_workspace/workspace/basic-MultiUser-Che-check-e2e-tests-against-k8s/logs'
09:02:50 Cancelling nested steps due to timeout
```

### Reference
The root cause of issue could be commit https://github.com/che-incubator/chectl/commit/fbe392883a289228fbf30ad6c89956134e1965fb

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.11 (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by tolusha** [comment]
@dmytro-ndp 
I see the problem. I will provide the PR soon
