### ISSUE TITLE
CRW2.0 Java Language Server hangs at 57% for Java/Maven workspace behind the firewall

### ISSUE THREAD

**Issue by ming-ddtechcg** [eclipse-che/che#15583]
I am testing RedHat CodeReady Workspaces 2.0 Java/Maven behind the cooperate firewall.  I understand that Maven needs to download the dependencies and I have placed my settings.xml under /home/jboss/.m2 with the cooperate proxy settings.

However, I guess JLS hangs because there is an issue to reach out the outside internet shown below:

![image](https://user-images.githubusercontent.com/39844031/71520698-57fd3a80-288b-11ea-80d1-90ffe2630c1f.png)

My pom.xml:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0&nbsphttp://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <name>Helloworld</name>
  <description>The&nbspproject&nbspfor&nbsptesting</description>  
  <groupId>com.rbccm.app</groupId>
  <artifactId>Helloworld</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>
  <build>
      <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
                <debug>true</debug>
                <debuglevel>lines,vars,source</debuglevel> 
            </configuration>
          </plugin>
      </plugins>
  </build>
  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
</project>
```

My settings.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<settings
xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>${user.name}/.m2/repository</localRepository>
  <interactiveMode/>
  <usePluginRegistry/>
  <offline>false</offline>
  <pluginGroups/>
  <servers/>
  <mirrors/>
    <proxy>
      <id>http-proxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>...</host>
      <port>...</port>
      <username></username>
      <password></password>
      <nonProxyHosts>localhost|127.0.0.1</nonProxyHosts>
    </proxy>
    <proxy>
      <id>https-proxy</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>...</host>
      <port>...</port>
      <username></username>
      <password></password>
      <nonProxyHosts>localhost|127.0.0.1</nonProxyHosts>
    </proxy>
</proxies>
<activeProfiles/>
</settings>
```

Any suggestion?

**Comment by ming-ddtechcg** [comment]
I am also wondering that the proxy entries in the customer resource YAML:

    # protocol+hostname of a proxy server. Automatically added as JAVA_OPTS and https(s)_proxy
    # to Che server and workspaces containers
    proxyURL: ''
    # port of a proxy server
    proxyPort: ''
    # username for a proxy server
    proxyUser: ''
    # password for a proxy user
    proxyPassword: ''

Will it help to resolve my issue?

**Comment by tolusha** [comment]
Try to configure Java LS to point to your `settings.xml`:
`"java.configuration.maven.userSettings": "/path/to/settings/xml"`

**Comment by ming-ddtechcg** [comment]
Thanks and it does work.  But, is there a way to integrate to devfile (or somewhere) so that developers do not need to worry about this setting?

**Comment by gorkem** [comment]
You can pass preferences to plugins from devfile see https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#tuning-cheplugin-component-configuration
