### ISSUE TITLE
Che-colors improvement for UD

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#15582]
### Is your enhancement related to a problem? Please describe.

We have several gulp tasks to prepare Che-colors from the several JSON files( [che-colors.json](https://github.com/eclipse/che/tree/master/dashboard/src/app/colors/che-colors.json), [che-output-colors.json](https://github.com/eclipse/che/tree/master/dashboard/src/app/colors/che-output-colors.json) ). And one of the resulted files is already committed ([che-color.constant.ts](https://github.com/eclipse/che/tree/master/dashboard/src/app/colors/che-color.constant.ts)).
These tasks are needed to be clarified and improved because we need to move away from the gulp at all.
   Move  Che-colors to the  [product.json](https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/product.json) as a second step.

**Comment by akurinnoy** [comment]
+1
AFAIK if it will be needed custom theming could be provided using branding
