### ISSUE TITLE
Eclipse che workspace fails to start on Openshift 3.11

### ISSUE THREAD

**Issue by svrajasekar** [eclipse-che/che#15589]
I successfully installed Eclipse Che 7.7.0-SNAPSHOT in Openshift 3.11.0 on AWS VM

When I launched che in the browser and tried to create a workspace, it gives me the below error:

Successfully pulled image "eclipse/che-init-plugin-broker:v0.24"
Created container
Started container
Error: Failed to run the workspace: "Plugins installation process timed out"

Upon inspecting the workspace log when it was being created, I got this message and finally it gives up.

oc logs workspaceznq7y58rtlpovsz5.che-plugin-broker
Error from server (BadRequest): container "che-unified-plugin-broker-v0-24" in pod "workspaceznq7y58rtlpovsz5.che-plugin-broker" is waiting to start: PodInitializing

When I inspected the docker logs for the workspace, I see the below message:

docker logs 2ac3dd173a77
2020/01/01 14:06:22 Broker configuration
2020/01/01 14:06:22   Push endpoint: ws://che-host.che.svc.cluster.local/api/websocket
2020/01/01 14:06:22   Auth enabled: true
2020/01/01 14:06:22   Runtime ID:
2020/01/01 14:06:22     Workspace: workspaceznq7y58rtlpovsz5
2020/01/01 14:06:22     Environment: default
2020/01/01 14:06:22     OwnerId: 3d5836ba-ba9a-4a53-8732-c6e5db1b6e25

Please note that I edited deployment configuration of the che server to update the websocket endpoint to the cluster url and not the url of the published route. Because it was throwing connection error.

I created the local image of the che-devfile-registry and che-plugin-registry using the --offline flag and using the same.

I hosted Keycloak outside the cluster and pointing the url when installing che server. 

VM Details:
========
AWS Ubuntu 18.04
32gig RAM
8 vCPUS
80 gig hard disk

Platform Openshift 3.11
===============

Docker version:
==========
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Installation method:
=============
Cloned github/eclipse/che master locally
Moved in to deploy/openshift/templates folder and executed the below commands

oc new-app che
oc new-app -f multi/postgres-template.yaml
oc new-app -f che-devfile-registry.yml -p IMAGE=quay.io/eclipse/che-devfile-registry -p IMAGE_TAG=nightly
oc new-app -f che-plugin-registry.yml -p IMAGE=quay.io/eclipse/che-plugin-registry -p IMAGE_TAG=nightly
oc apply -f pvc/che-server-pvc.yaml
oc new-app -f che-server-template.yaml \
	-p CHE_MULTIUSER=true \
	-p ROUTING_SUFFIX=nnn.nnn.nnn.nn.nip.io \
	-p CHE_KEYCLOAK_REALM=maantt \
	-p CHE_KEYCLOAK_CLIENT__ID=maantt-internal \
	-p CHE_KEYCLOAK_AUTH__SERVER__URL=http://nnn.nnn.nnn.nnn:5050/auth \
	-p CHE_WORKSPACE_DEVFILE__REGISTRY__URL=http://che-devfile-registry-che.nnn.nnn.nnn.nnn.nip.io \
	-p CHE_WORKSPACE_PLUGIN__REGISTRY__URL=http://che-plugin-registry-che.nnn.nnn.nnn.nnn.nip.io/v3
oc set volume dc/che --add -m /data --name=che-data-volume --claim-name=che-data-volume

Can someone help me solve the problem please?

**Comment by IveJ** [comment]
Hi Raja,

I wonder your version and custom script of config you run ws in cluster and
your own image devfile/plugin.

Better option that follow the guide include current version  for successful
deployment.
Any adjustment need testing.

Thank for sharing.

**Comment by svrajasekar** [comment]
You choose any type of deployment (chectl, che-operator) on openshift 3. You will for sure hit the stonewall. Nothing will work. I followed all the instructions, But nothing worked. It was then I decided to get to this forum for help.

Do you have any idea how to fix my problem?.

Anybody can build custom devfile and plugin registry by cloning the repositories. It's not rocket science.

The issue I am facing is with workspace creation. I need a solution to this problem.

**Comment by svrajasekar** [comment]
Atlast after 3 weeks of hard work, I could successfully install Eclipse Che on Ubuntu 18.04

Workspace starts successfully and everything looks good.

I will open another issue detailing steps to be followed to successfully install Eclipse Che on Ubuntu for folks that are facing issues. These steps are the same for Kubernetes as well.

Regards
Rajasekar S V

**Comment by sslnreddy** [comment]
Hi Rajasekar,

I am unable to start eclipse che workspace  In aws Minikube ( Ubuntu 18.04)

**Comment by ke-liu** [comment]
Installed the eclipse Che recently, unfortunately keep losing my workspace every day…
Installed via chectl with docker desktop (latest version 2.2.0.3) on my Mac (with v1.15.5 Kubernetes: tried both minikube and docker-desktop). The eclipse Che installed successful, created workspace with no issue. But each day I log back in my Mac, I lost the URL connection: http://che-che.x.x.x.x.nip.io/ Try to stop and start server: 

chectl server:start --platform=docker-desktop

    ✖ Check Eclipse Che server status
…
 ›   Error: E_CHECK_CHE_STATUS_FAIL - Failed to check Eclipse Che status (URL: http://che-che.x.x.x.x.nip.io). E_CHE_API_NO_RESPONSE - Endpoint: http://che-che.x.x.x.x.nip.io/api/system/state - Error message:
 ›   connect EHOSTUNREACH x.x.x.x:80 - Local (x.x.y.y:50622)

Nothing works since in terms of chectl, restarting dockers and Kubernetes would not help at all. I have to reset Kubernetes cluster, then start the Che server agin.. Lost all workspace and work.
