### ISSUE TITLE
INTERNAL_IP Connection successful but EXTERNAL_IP fails

### ISSUE THREAD

**Issue by arg3t** [eclipse-che/che#15584]
## Summary
Hi I am Yeet(Yeah, it really is pronounced "yeet").
Anyways, I have a  self-hosted server that I use for storage and development purposes. For a long time I had theia installed as my ide but now I am trying to switch to che because it serves better to my purposes. However, I usually work outside my home and I need to use my domain name as the CHE_HOST or else the api requests are made to my server's LAN ip which obviously fails. However, once I change the CHE_HOST to my domain name, The browser starts sending requests to the `172.17.0.1` which still doesn't work for me. I need the che server to send the api requests to my domain name as well. And I have no idea how to achieve this. I have been working on this for way too long and trust me, I wouldn't have asked for your help if I didn't absolutely have to. 
Thanks in advance.
## Relevant information

Here is the start output:
```
[yigitcolakoglu@yigitcolakoglu ~]$ sudo docker run --dns=192.168.1.3 -it --rm -v /var/che/data:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:5.17.0 start

INFO: (che cli): 5.17.0 - using docker 1.13.1 / native
WARN: (che cli): 'CHE_HOST=yigitcolakoglu.com' is != discovered IP '192.168.1.3'
WARN: Newer version 'rc' available
INFO: (che start): Booted and reachable
INFO: (che start): Ver: 5.17.0
INFO: (che start): Use: http://yigitcolakoglu.com:8080
INFO: (che start): API: http://yigitcolakoglu.com:8080/swagger

```
Here is the network-info output:
```
[yigitcolakoglu@yigitcolakoglu ~]$ sudo docker run --dns=192.168.1.3 -it --rm -v /var/che/data:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:5.17.0 info --network 

INFO: (che cli): 5.17.0 - using docker 1.13.1 / native
WARN: (che cli): 'CHE_HOST=yigitcolakoglu.com' is != discovered IP '192.168.1.3'
WARN: Newer version 'rc' available
INFO: 
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: (che network): eclipse/che-ip:5.17.0: yigitcolakoglu.com
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (yigitcolakoglu.com): Connection succeeded
INFO: (che network): Server  => Workspace Agent (External IP): Connection failed
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded
```
Here is my che.env (Without the comments):
```
CHE_HOST=yigitcolakoglu.com

CHE_WORKSPACE_HOSTS=yigitcolakoglu.com:192.168.1.3

DOCKER_HOST=tcp://localhost:2375

CHE_DOCKER_SERVER__EVALUATION__STRATEGY=docker-local

CHE_SINGLE_PORT=false

```

**Comment by sleshchenko** [comment]
@yigitcolakoglu AFAIS you run `eclipse/che:5.17.0` where we use GWT IDE. Would you like to install the latest Che 7 where we use Theia as IDE? (in such case you need to run some k8s or OpenShift cluster, for as easier options to try may be minikube or minishift)

**Comment by yigitcolakoglu** [comment]
I get this error message when I run:

```
[yigitcolakoglu@yigitcolakoglu ~]$ sudo docker run --dns=192.168.1.3 -e CHE_HOST=yigitcolakoglu.com -it --rm -v /var/che/data:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:rc start
INFO: (che cli): rc - using docker 1.13.1 / native
INFO: (che init): Installing configuration and bootstrap variables:
INFO: (che init):   CHE_HOST=yigitcolakoglu.com
INFO: (che init):   CHE_VERSION=rc
INFO: (che init):   CHE_CONFIG=/var/che/data
INFO: (che init):   CHE_INSTANCE=/var/che/data/instance
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [OK]
container_linux.go:235: starting container process caused "exec: \"curl\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "
exec: \"curl\": executable file not found in $PATH".
/scripts/base/library.sh: line 333: 1: unbound variable
```

**Comment by tolusha** [comment]
Che 6.x is out of support. 
Pls try Che 7.x
https://www.eclipse.org/che/docs/che-7/running-che-locally/

**Comment by BillLucky** [comment]
As of today, the latest rc version is still not available.
[latest：rc](https://hub.docker.com/layers/eclipse/che/rc/images/sha256-3a3ac33dbbe8fee2ca25f3a8196af4d0e57497edd2500b282a6112d5600de4c1?context=explore)

![image](https://user-images.githubusercontent.com/8528590/83750558-0ce81e80-a698-11ea-9a9b-70cabe74a0cf.png)
