### ISSUE TITLE
Upgrade vscode-java plugin to 0.55+

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15593]
### Is your enhancement related to a problem? Please describe.

it includes _java.project.referencedLibraries_ feature which is required for VS Code Camel K 0.11+ to have Java language support on standlaone Camel K files

### Describe the solution you'd like

upgrade vscode java to 0.55+

**Comment by tsmaeder** [comment]
Closing as duplicate of https://github.com/eclipse/che/issues/15560
