### ISSUE TITLE
How to use the provided tomcat8 in workspace image "codenvy/ubuntu_jdk8"?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#156]
I see in the provided "codenvy/ubuntu_jdk8", it has provided a tomcat8, and also exposes the port `8080`.

But I'm not sure how to use it, do I have to start it manually? Or do I have to modify `pom.xml` and use it from some maven plugins?

Is there any example for a web application?

**Comment by TylerJewell** [comment]
In the beta release there will be a concept of a preview URL that is provided when a command is run.  It will have the context of the machine and any internal processes like a web app inside of tomcat.

We will provide example templates for both web apps and console command line applications with commands that are populated with preview objects.

In the meantime all commands have to be written manually.  So you will need to start and stop the tomcat using a command or in the terminal.

**Comment by freewind** [comment]
@TylerJewell Thanks, looking forward to the feature :+1:
