### ISSUE TITLE
Bump up third-party dependency version to fix security vulnerability

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#15605]
### Is your enhancement related to a problem? Please describe.

We are using third-party vulnerable dependency **handlebars** v4.0.12. Need to upgrade.
### Describe the solution you'd like

Upgrade and fix **handlebars** to version 4.3.0 or later

### Additional context
https://github.com/eclipse/che/network/alerts

**Comment by sleshchenko** [comment]
It does not seem to be actual https://github.com/eclipse/che-dashboard/security/advisories
@olexii4 feel free to reopen if you think it's still actual
