### ISSUE TITLE
Support for Ruby and RoR with Che Theia

### ISSUE THREAD

**Issue by aaqaishtyaq** [eclipse-che/che#15606]
Hi, currently there is no LSP support for Ruby language. Is there any way to run vscode solargraph extension in the sidecar container as a plugin with Eclipse Che 7.x?

**Comment by aaqaishtyaq** [comment]
I tried `vscode-solargraph` extension in a sidecar container with ruby runtime and `solargraph` gem but it was not able to find the solargraph gem. Ruby syntax highlighting works with `vscode-ruby` extension but no LSP.

**Comment by mairin** [comment]
Just putting it out there that ruby support would be nice. It seems an odd omission

**Comment by ericwill** [comment]
Thanks for the input, this is something we can look at in a few sprints.

**Comment by liningpan** [comment]
It is possible to change `solargraph`  path in che workspace, and this fixed my problem. You may also try my plugin and sidecar docker image, if you have a self-hosted plugin registry. 
You can find my docker image, plugin configuration, and workspace settings in my repository. [https://github.com/liningpan/che-ruby-plugin](https://github.com/liningpan/che-ruby-plugin)

**Comment by ericwill** [comment]
> It is possible to change `solargraph` path in che workspace, and this fixed my problem. You may also try my plugin and sidecar docker image, if you have a self-hosted plugin registry.
> You can find my docker image, plugin configuration, and workspace settings in my repository. https://github.com/liningpan/che-ruby-plugin

That's awesome! Do you want to contribute your sidecar + plugin configuration to Che? I can create a repo for you in the [che-dockerfiles org](https://github.com/che-dockerfiles), where all the other sidecars are located. I'd also be happy to review your PR to add the plugin into the che-plugin-registry.

**Comment by liningpan** [comment]
Yes, I would like to contribute my sidecar and plugin.

**Comment by ericwill** [comment]
> Yes, I would like to contribute my sidecar and plugin.

Nice! Please open a PR for your sidecar container here: https://github.com/che-dockerfiles/che-sidecar-ruby

You can look at the [che-sidecar-node repo](https://github.com/che-dockerfiles/che-sidecar-node) for an idea of what's needed, I've already set up most of the files (automatic build + push to quay.io, PR check, etc.), all that's needed is your Dockerfile, and a VERSION file specifying the version of the extension.

After that, you can open a PR to the [che-plugin-registry](https://github.com/eclipse/che-plugin-registry) with your `meta.yaml`. I'll make sure both PR's get reviewed either by me or someone on my team.

**Comment by ericwill** [comment]
A big thanks to @liningpan for his contribution -- we now have the Ruby plugin in Che 7.19.
