### ISSUE TITLE
chectl --devfile/plugin-registry-url should override cr.yaml plugin/devfileRegistryUrl:

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#15600]
### Describe the bug

chectl server:start -m -p minikube --plugin-registry-url=something --devfile-registry-url=something

che-operator still deploys both pods to the cluster, even if no image url is set for them in the cr.yaml (magic)

### Che version

 - [ ] latest
 - [ *] nightly
 - [ ] other: please specify

### Expected behavior

che-plugin-registry and che-devfile-registry are deployed externally so they should not be deployed by che-operator

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [* ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/407397/71704704-b611ac80-2dba-11ea-999c-3a07780d874b.png)

### Installation method
   - [ *] chectl 
                   -m -p minikube --plugin-registry-url=something --devfile-registry-url=something
   - [ *] che-operator (nightly) 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ *] my computer 
       - [ ] Windows
       - [ *] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ *] other: inside LXC

**Comment by gattytto** [comment]
![image](https://user-images.githubusercontent.com/407397/71705169-fffb9200-2dbc-11ea-9e86-516932f8a507.png)
![image](https://user-images.githubusercontent.com/407397/71705181-0f7adb00-2dbd-11ea-8ca6-7760d46674ed.png)
![image](https://user-images.githubusercontent.com/407397/71705193-27eaf580-2dbd-11ea-8164-eb4d79bd96aa.png)

**Comment by gattytto** [comment]
this is produced when using --che-operator-cr-yaml=someCR.yaml and using the --devfile-registry-url at the same time. Also I referenced this issue from other related issue where chectl does not check the CR values and fails waiting for the devfile/plugin-registry pods deployments.

**Comment by tolusha** [comment]
@gattytto 
when you use `--che-operator-cr-yaml=cr.yaml` then you can set everything in `cr.yaml` and that's why `--plugin-registry-url` and `--devfile-registry-url` flags aren't used.
And it is possible to set `externalPluginRegistry: true` and `externalDevfileRegistry: true` in cr.yaml accordingly to crd: https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml#L320-L333
