### ISSUE TITLE
chectl not checking externalPlugin/DevfileRegistry:true nor plugin/devfileRegistryUrl: in cr.yaml

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#15601]
### Describe the bug

chectl does not take account of the following properties in cr.yaml:
devfileRegistryUrl: 'http://some-url'
    pluginRegistryUrl: 'http://some-url '
    externalPluginRegistry: true
    externalDevfileRegistry: true

so when running chectl with the argument --che-operator-cr-yaml=someCR.yaml the chectl progress indicator fails waiting for those deployments

### Che version

 - [ ] latest
 - [ *] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ *] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/407397/71705586-494ce100-2dbf-11ea-9a2b-0378e9a60197.png)

### Installation method
   - [ *] chectl 
   - [ *] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ *] my computer 
       - [ ] Windows
       - [ *] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ *] other: LXC

### Additional context

related to https://github.com/eclipse/che/issues/15600

**Comment by gattytto** [comment]
![image](https://user-images.githubusercontent.com/407397/71705779-c5472900-2dbf-11ea-8dea-c9831f18014a.png)

**Comment by gattytto** [comment]
in this scenario the che server works as expected even after the chectl progress reporting failure

**Comment by tolusha** [comment]
`plugin-registry-url` and `devfile-registry-url` are not taken into account on purpose when `che-operator-cr-yaml` is used. We added warning indicating that.
If it is needed to set external devfile/plugin registries it is possible to do in cr file.
