### ISSUE TITLE
Ci: container image `eclipse/che-machine-exec:latest` should not point to the nightly tag

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15603]
### Describe the bug
Ci: the tag `latest` of the container image `eclipse/che-machine-exec` is pointing to the nightly tag.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
 It should points to the latest stable release tag.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
@dmytro-ndp

**Comment by rhopp** [comment]
@tolusha @AndrienkoAleksandr Can you please put more info into this issue? What is it about and how is it related to QE team?

**Comment by rhopp** [comment]
@tolusha @AndrienkoAleksandr I'm afraid we cannot do anything here, as we don't know what this issue is about.
