### ISSUE TITLE
Can not start a workspace

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15602]
### Describe the bug
Starting a workspace is failing with the error: `The following containers have terminated: che-machine-exec`

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Try to start a workspace from dashboard or devfile

### Expected behavior
A workspace has started

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube v1.0.0
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![workspace](https://user-images.githubusercontent.com/5676062/71714936-5813b200-2e18-11ea-98d4-1d1d798d8e4f.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by RomanNikitenko** [comment]
As a workaround user can define `7.6.0` version for `che-machine-exec`

![machine-exes](https://user-images.githubusercontent.com/5676062/71716015-0e2ccb00-2e1c-11ea-979d-24fab7b388bf.png)

thanks @AndrienkoAleksandr  for the advice!

**Comment by AndrienkoAleksandr** [comment]
Detected one more issue https://github.com/eclipse/che/issues/15603
