### ISSUE TITLE
The workspace stops due to idle timeout setting while the workspace is in use.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15614]
### Describe the bug

I set the workspace idle timeout to 1 minute to test the workspace idle timeout and create a workspace with the code-server editor.
At that time, the workspace stops even though I am using the terminal and editor.
If I set the workspace idle timeout, is it normal to stop the workspace while in use?
If this is an abnormal operation, I wonder what setting is necessary for normal operation.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.4.0

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![idle_timeout_error](https://user-images.githubusercontent.com/29850624/71958927-da471080-3234-11ea-8656-ce6a289b1788.gif)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] helm 
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
Hello, what is the browser ?

**Comment by benoitf** [comment]
I'm asking because we fixed that issue https://github.com/eclipse/che/issues/15354 on firefox

**Comment by kellyhyomin** [comment]
@benoitf 
Hello, the browser is chrome and no errors in the browser console.

**Comment by sleshchenko** [comment]
@kellyhyomin Could you confirm that this issue is fixed/not fixed on the latest Che version?

**Comment by kellyhyomin** [comment]
@sleshchenko 
When I change the existing working workspace to code-server editor to test in the latest version, the following error occurs.

![image](https://user-images.githubusercontent.com/29850624/88881048-52286700-d269-11ea-9201-2a11cee7e3ef.png)
![image](https://user-images.githubusercontent.com/29850624/88880866-d1696b00-d268-11ea-9c81-ae708c7a91f2.png)

**Comment by sleshchenko** [comment]
@kellyhyomin At the center there should be proposal to restart workspace in debug mode, if no - there is context menu that allows you to start in debug mode. See https://www.eclipse.org/che/docs/che-7/troubleshooting-for-che-end-users/#restarting-a-che-workspace-in-debug-mode-after-start-failure_troubleshooting-for-che-end-users

Maybe it'll show the real reason. 
I assume typescript needs theia to start... So, please disable all plugins that fail to start, test workspace idling - if it works - close this issue.
If you need a help with code-server and theia plugin - please open a new issue. Thanks.

**Comment by kellyhyomin** [comment]
@sleshchenko 
Thank you for your help.
Tested on the latest version, the timeout does not work the same as the previous version.
![che_7 16 2_code_server_idle_timeout_error](https://user-images.githubusercontent.com/29850624/88905786-a5161480-d291-11ea-84b6-b5d19f7721db.gif)
