### ISSUE TITLE
Is Postgres database (userdata directory) reusable?

### ISSUE THREAD

**Issue by ming-ddtechcg** [eclipse-che/che#15612]
just wondering that can I reuse the Postgres userdata for the next Che deployment?

**Comment by tolusha** [comment]
@ming-ddtechcg 
Could you elaborate more?

**Comment by ming-ddtechcg** [comment]
For example, if I need to reinstall my che server but I would like to user information on my postgres pv and sc to be used again after the another installation.

Can I set the postgres persistentVolume and storageClasss policy claim as "Retain"?
