### ISSUE TITLE
Happy Path test is broken due to reformatting in PetClinic application source code.

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#15613]
### Describe the bug
PetclinicApp was reformatted recently in this commit: https://github.com/spring-projects/spring-petclinic/commit/4e1f87407d80cdb4a5a293de89d62034fdcbb847

This causes code completion to trigger on wrong place and thus failing the test like this - https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/1533/artifact/tests/e2e/report/Language_server_validation_Suggestion/screenshot-Suggestion.png

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
can we use a specific tag of petclinic in our happy test ? instead of using the master branch ?

**Comment by rhopp** [comment]
This issue is fixed by https://github.com/eclipse/che/pull/15620
