### ISSUE TITLE
Need to create a CI for pre-release testing 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15626]
### Is your task related to a problem? Please describe.
Need to create a CI for pre-release testing

**Comment by ibuziuk** [comment]
@dmytro-ndp @rhopp any input on this one? What set of tests is expected to be run as part of the pre-release CI?

**Comment by rhopp** [comment]
I'm closing this one in favor of https://github.com/eclipse/che/issues/15701 (contains more info)
