### ISSUE TITLE
Add Native Compilation Commands to Quarkus Devfile

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15630]
The current Quarkus devfile does not contain any commands to native-compile the example application. This is because on che.openshift.io, we only have 3Gb per workspace available. 
This task consists of adding the necessary commands for native compilation to that devfile in a way that graciously fails if there is not enough memory available. In particular, we don't want the workspace or any containers to be OOM-killed by the platform.
Ideally, native compilation could be started, but would fail with a nice error message when it runs out of memory.

**Comment by amisevsk** [comment]
From my experience, it's hard to know whether a process or the whole container will be killed in an OOM situation.

**Comment by tsmaeder** [comment]
We don't need a 100% solution: if the behaviour is good 99% of the time, I'm fine with that.

**Comment by ericwill** [comment]
This has been implemented for awhile now.
