### ISSUE TITLE
Unable to configure CORS origins in multi-user Che

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#15631]
### Describe the bug

Api requests to Che multi-user server from Che client side fail due to CORS error:
```
Access to XMLHttpRequest at 'http://che-che.192.168.99.194.nip.io/api/user&token=***' from origin 'http://serveru8v0e6p6-che-dev-server-3010.192.168.99.194.nip.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
There is no `CHE_CORS_ALLOWED__ORIGINS` item in the `che` config-map
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

build and launch a simple che-theia plugin that does:
`che.github.uploadPublicSshKey('publicKey');`

See CORS errors in the browser console
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
you can't upload from nodejs ? (instead of doing it from client side)

**Comment by vinokurig** [comment]
No, the request is called in the client side. the code described in the steps to reproduse is just an example the calls the request to che server from client side

**Comment by benoitf** [comment]
@vinokurig yes but client can't call server side to do the operation ?

**Comment by vinokurig** [comment]
@benoitf Why not? It is possible in the single user Che.

**Comment by skabashnyuk** [comment]
CC @l0rd

**Comment by skabashnyuk** [comment]
@vinokurig we need to carefully discuss this topic with architects before we go any forward with CORS

**Comment by vinokurig** [comment]
Closing as expected behaviour

**Comment by IveJ** [comment]
Hi All,

https://che.eclipse.org/eclipse-che-6-15-6-16-and-6-17-release-notes-362cff44dcc9

https://developer.chrome.com/extensions/xhr

Wish to helpful.
