### ISSUE TITLE
CSS is broken for all Theia plugins on Che 7.6.0

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#15635]
### Describe the bug

It seems that some of Che-Theia's CSS is broken on Che 7.6.0, as the CSS is not loading for any of the Theia plugins:
<img width="1263" alt="Screen Shot 2020-01-08 at 1 33 48 PM" src="https://user-images.githubusercontent.com/6880023/72005535-cf33b680-321b-11ea-98d6-9ed5f218ce99.png">

I also see the following in my browser's logs:
```
root ERROR Failed to enable webview caching:  l</e.prototype.resolveCache/</<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:34:814133
s/</<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:34:813670
s/<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:34:813775
o</<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:34:812687
o<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:34:812461
l</e.prototype.resolveCache@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:34:813976
e@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:34:813911
t.resolveInstance@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:25919
l/<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:25069
t.resolveInstance/c<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:25768
t.resolveInstance@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:25860
l/<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:25069
t.resolve@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:25332
y</e.prototype._planAndResolve/<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:16433
y</e.prototype._get@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:16199
y</e.prototype.get@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:56:14911
createWidget/</<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:125:47760
s/</<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:125:43206
s/<@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:125:43311
a@http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/bundle.js:125:42054
logger-protocol.ts:112:15
    log logger-protocol.ts:112
    get logger-frontend-module.ts:41
    getLog logger.ts:312
    log logger.ts:304
Service Workers are not enabled. Webviews will not work properly host.js:56:21
The resource from “http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/…d/eclipse_che_welcome_plugin.theia/resources/welcome-page.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
index.html
The resource from “http://route5a84z3jw-che.apps.codewind-ceph.os.fyre.ibm.com/…/eclipse_che_welcome_plugin.theia/resources/welcome-page.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

There's similar errors complaining about type mismatch for any of my Theia plugins as well.

### Che version
Che 7.6.0

### Steps to reproduce

1. Create a Che workspace on Che 7.6.0
2. Open the workspace in a browser (I can reproduce on Chrome and Firefox minimally)
3. The CSS for any Theia plugin will have not loaded. There will be errors in the Browser log similar to what I posted above.

### Expected behavior
The CSS loads properly for all plugins.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.14-201908291507+ec04ac2-dirty", GitCommit:"ec04ac2", GitTreeState:"dirty", BuildDate:"2019-08-29T23:30:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots

<img width="1029" alt="Screen Shot 2020-01-08 at 1 39 09 PM" src="https://user-images.githubusercontent.com/6880023/72005754-53863980-321c-11ea-8049-f80a16bf926a.png">
<img width="1029" alt="Screen Shot 2020-01-08 at 1 39 27 PM" src="https://user-images.githubusercontent.com/6880023/72005755-53863980-321c-11ea-8505-4be233dc4d2b.png">

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by johnmcollier** [comment]
I should note that I cannot reproduce on Che 7.5.1 or Che 7.3.1

**Comment by tolusha** [comment]
@azatsarynnyy 
do we support Chrome minimal?

**Comment by azatsarynnyy** [comment]
Recently, Theia has introduced the PR https://github.com/eclipse-theia/theia/pull/6465#issuecomment-557494879 which makes WebViews are secure. That means that the WebViews are working in secure contexts only: https, localhost.

From the screenshot, I see that http is used. That's why WebView doesn't work.

**Comment by azatsarynnyy** [comment]
Closing it as it's expected behavior of WebView within insecure context (http).
