### ISSUE TITLE
Project in "web-nodejs-with-db-sample" devfile sample is not compatible with node.

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#15649]
### Describe the bug
Since [this commit](https://github.com/ijason/NodeJS-Sample-App/commit/5c0f700d4418c5aabd85f5d6bfd31efec395383d), the sample cannot be run in workspace created from this [sample devfile](https://github.com/redhat-developer/devfile/blob/master/samples/web-nodejs-with-db-sample/devfile.yaml).

Trying to run the sample ends up with 
```
/projects/nodejs-mongo-app/EmployeeDB/app.js:30
app.use((req, res, next) => {
                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```
Seems like the node version we are using in this devfile does not support `() => {}` notation of inline functions.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create workspace from https://github.com/redhat-developer/devfile/blob/master/samples/web-nodejs-with-db-sample/devfile.yaml
2. Try to run the example
3. Observe failure.

### Expected behavior
Example should be albe to run.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: Codeready Workspaces 2.0

**Comment by sunix** [comment]
OK @rhopp so what do we want to do with that ?
The application is just not compiling in Che or any environment since the upgrade to node 4 in package.json

**Comment by sunix** [comment]
So several problems:
- the applications is not compiling, running as it is. Moved to Express 4 but the code is still express 3. See https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x.
- the `run` command is not working as it is because of arbitrary user issue with the container used. a quick workaround is to set the env variable HOME to /projects. In the `run` command in devfile.yaml for instance: `export HOME=/projects/ ; cd ...`
- after having disabled some feature, I have the app that is partially working.
- maybe the easier fix is to fork and have a branch to the changeset before the express upgrade

**Comment by sunix** [comment]
in the PR https://github.com/redhat-developer/devfile/pull/67 I have reset the project to be clone to the commitid before it breaks.
