### ISSUE TITLE
Spinner icon when loading java language server spins off-center

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15645]
### Describe the bug
The spinner that shows up in the Theia bottom bar while the Java language server is starting spins off center and looks strange (on Fedora, at least):

Chrome (79.0.3945.88):
![chrome-spinner](https://user-images.githubusercontent.com/16168279/72079105-4e7ec400-32c8-11ea-8205-477a1e19a45e.gif)

Firefox (71.0)
![firefox-spinner](https://user-images.githubusercontent.com/16168279/72079132-59395900-32c8-11ea-8995-94114a9c954a.gif)

### Che version
 - [x] nightly

### Steps to reproduce
Start workspace with java language server and open a `.java` file.

### Environment
Fedora 31 and 30

**Comment by tsmaeder** [comment]
This seems indeed specific to Java...the Typescript startup spinner is centered.

**Comment by sparkoo** [comment]
That's great, I like it. I would keep it as a feature :))

**Comment by sleshchenko** [comment]
!!offtop
People like seeing:
1. Burning fire
2. Water is flowing
3. Uncentered spinner is rotating.

**Comment by danidoedel** [comment]
It‘s the same for PHP (Intelephense)

**Comment by amisevsk** [comment]
It's also still present in `7.16.0` for Java.

**Comment by ericwill** [comment]
No longer reproducible on Che 7.25.
