### ISSUE TITLE
Search and replace in multiple files

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1564]
Could you add support to search & replace in all files below a directory, or all open files, allowing regex. Basically the current find and replace but for mutliple files (like Sublime Text allows).

**Comment by wernight** [comment]
I heard from some people that it's actually possible (but couldn't say how). Can anyone confirm or refute?

**Comment by slemeur** [comment]
Hi @wernight.

Currently, you can:
- find&replace in the current file
- find in all files below a directory
- find usages of a java class

See the gif:
![find](https://cloud.githubusercontent.com/assets/1636769/16307961/8137f568-3963-11e6-9d2c-c58d50dbdcba.gif)

Your request is a bit different from what is provided in Che for now. So it is considered as an enhancement.

**Comment by davidwindell** [comment]
Bulk find and replace saves *a lot* of time in Netbeans, this feature is what our dev's miss most.

**Comment by wernight** [comment]
@slemeur I'm aware of the search. As you pointed out, there is no **replace** in multiple files.

**Comment by slemeur** [comment]
@wernight. You are right, the replace is available only in the current file. 

Along with a bigger work on the UI, we are considering to replace the current search capabilities.
Once we'll have a specification drafted, it will be shared here and your comments will be helpful (as the ones you gave for git ;) ).

**Comment by wernight** [comment]
I'd suggest to work like Sublime Text (and most modern text editors):

![image](https://cloud.githubusercontent.com/assets/145667/26309015/b3224184-3efb-11e7-83d0-aa6f12c291e8.png)

**Comment by davidwindell** [comment]
Netbeans is nice too, especially how it shows all the replaces done afterwards in a list and their line numbers (although that's a bigger feature needed with Che's search at the moment).

![screenshot from 2017-05-22 13-35-16](https://cloud.githubusercontent.com/assets/1720090/26309104/9b002e5c-3ef3-11e7-9bbc-b01e101ff350.png)

Here's the best part of it, you can select exactly which files you want to replace

![screenshot from 2017-05-25 13-35-49](https://cloud.githubusercontent.com/assets/1720090/26450545/deacf906-414f-11e7-9b4f-e880fdece5b0.png)

**Comment by slemeur** [comment]
Thank you guys. 
Similarly to what we did for the [Git panel](https://github.com/eclipse/che/issues/5128), we will consider to use a left panel for the search/replace. 
Hopefully, I'll have a spec on that soon.

**Comment by wernight** [comment]
I feel this isn't like Git. This is about editing locally so it's what you're doing already.

A dialog here, like for Git, would be good for a one time complex action.

Having a side bar is also good, just I'd make it as close as possible to the simple find in file. Having few visual differences makes the UI simpler to understand. Since the in-file search (and replace) are in the top-left, I'd probably just have the search & replace there as well if going for an inline option (like the side bar).

**Comment by slemeur** [comment]
Fixed in Che 7
