### ISSUE TITLE
 Document how many workspaces a single wsmaster is able to handle 

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#15641]
### Task Description
Based on the analyze here https://github.com/eclipse/che/issues/14629 , we need to write down a document that help users to plan how many resources the wsmaster needs to support N concurrent workspaces.

**Comment by nickboldt** [comment]
Assuming this wasn't done for 7.11 so slip to 7.12

**Comment by nickboldt** [comment]
@rkratky @themr0c should this be assigned to docs team rather than QE? 

Also assuming it has slipped to 7.13.

**Comment by anilgulecha** [comment]
Are there any numbers on this? We've been able to do 50-75 per che master at a lot of churn, but recommendations and bench-marked data from the core team would also help.

**Comment by rhopp** [comment]
Hello. 
As for the sizing guidelines we already have section in docs about this: https://www.eclipse.org/che/docs/che-7/calculating-che-resource-requirements/

We are pretty much allways running latest Che on che.openshift.io, where we have pretty steady workload and che-server is behaving correctly.

Also we are conducting some targetted tests with our downstream product based on Che (Codeready Workspaces). You can see the latest results of this in attached pdf:
[Load test results for CRW 2.1.pdf](https://github.com/eclipse/che/files/4666438/Load.test.results.for.CRW.2.1.pdf)

Based on this I think we can close this issue. 
If you still have some concerns or questions, please open new one ;-)

**Comment by anilgulecha** [comment]
@rhopp These are missing, and something we're actively using Che for:
- How many concurrent sessions can be run on a single Che cluster for continued good performance.
- How many sessions can be brought up every minute or so.

We see 50-75 and 1-2 for the above. is this inline with what you're seeing? Are there anything we're missing in terms of optmizing to increase these

**Comment by rhopp** [comment]
@anilgulecha 50-75 is what our testing environment allows us to do... And with this workload we are pretty confident, that che-server behaves correctly.
We would like to perform our testing with higher workloads, but we currently don't have bigger infrastructure right now. I can inform you if that changes.

**Comment by anilgulecha** [comment]
> We would like to perform our testing with higher workloads, but we currently don't have bigger infrastructure right now. 

If you'd like, we're (hackerrank) happy to sponsor infrastructure to do the load test.

Or, if you can point me to the load test scripts you use (and any documentation to setting things up for load tests), I'm happy to go run larger tests, and come back to you with the data.

**Comment by Katka92** [comment]
Hi guys, I can share how to run the load tests with you. There is a documentation with the scripts: https://github.com/eclipse/che/tree/master/tests/performance 
And if that helps, there is Jenkinsfile that allows you to use Jenkins to trigger the tests and gather the data https://github.com/eclipse/che/blob/master/tests/.infra/crw-ci/load-tests/Jenkinsfile 
In the documentation, you should have all the clues on how to set up the parameters. For an image `-i` you should use `quay.io/eclipse/che-e2e:<tag>` where `<tag>` is a version of Che that you're testing (e.g. `quay.io/eclipse/che-e2e:7.13.1`).
The tests run in INFO mode. If you want to set the more verbose output for the tests, you can use `-l` switch and set ti to `DEBUG` or `TRACE`. 
If you need more help, don't hesitate to ask.
