### ISSUE TITLE
Git: provide ability to add a remote repository

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#15644]
### Is your enhancement related to a problem? Please describe.
From the UI in the IDE, it's not possible to register a new remote repository. One would have to do that from the CLI.

### Describe the solution you'd like
Add an option to add a remote repository in the command palette and in the menu from the git UI.

When the user is doing a "Git: push to..." it would be nice to also have an option to add a new remote repository at that time.

**Comment by l0rd** [comment]
Both options are now available in the default Eclipse Che editor: 

<img width="594" alt="image" src="https://user-images.githubusercontent.com/606959/213999378-27b67ea1-3413-44d3-a7e8-09ba658f46b1.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/606959/213999536-d50eae3c-d3a0-4a46-9aae-27146359f736.png">
