### ISSUE TITLE
che-sidecar-camelk used in 0.0.10-4 is not based on the image corresponding to the correct kubernetes image version

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15655]
# Describe the bug

see https://github.com/eclipse/che-plugin-registry/pull/340#issuecomment-573057652

I think the eclipse/che-sidecar-camelk needs to be rebuilt and updated because there is a new one for kubernetes and the Camel K one is based on the Kubernetes one. The kubernetes one has been upgraded

https://github.com/eclipse/che-plugin-registry/blob/96f96bb417ee42e3c04bb5657f0272e7222e614e/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/meta.yaml#L18

https://github.com/eclipse/che-plugin-registry/blob/96f96bb417ee42e3c04bb5657f0272e7222e614e/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml#L15

I don't remember where the images are now built

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
@apupier pls fix the title

**Comment by apupier** [comment]
> I don't remember where the images are now built

https://github.com/che-dockerfiles/che-sidecar-camelk

**Comment by apupier** [comment]
created PR to update the sidecar https://github.com/che-dockerfiles/che-sidecar-camelk/pull/2
