### ISSUE TITLE
Instructions for branding Che dashboard?

### ISSUE THREAD

**Issue by bmboucher** [eclipse-che/che#15650]
I've attempted multiple times to replace the contents of the dashboard/src/assets/branding folder, rebuilding the dashboard in docker and then creating and deploying a new image. I've been able to drop into those running containers on my cluster and verify that my modified files end up in the tomcat folder as well. But none of the branding in the dashboard seems affected.

I see instructions for rebranding che-theia but I don't see anything specifically on the dashboard, is there a step I'm missing?

**Comment by amisevsk** [comment]
You could try clearing your cache; if you've previously deployed unbranded Che, your browser is likely caching icons, etc.

I was able to modify Che branding by
```
mvn clean install -Pfast -pl ':che-dashboard-war' --amd
./dockerfiles/che/build.sh --dockerfile:Dockerfile
```
and deploying the resulting dockerfile.

**Comment by sleshchenko** [comment]
@bmboucher Is this still actual? Does https://github.com/eclipse/che-dashboard#configurability help or not much?
