### ISSUE TITLE
Not able to launch the workspace in ARO (Azure RedHat OpenShift) eclipse CHE

### ISSUE THREAD

**Issue by echvsg** [eclipse-che/che#15659]
## Summary

I have followed the instructions mentioned in the github repository as mentioned below.
https://github.com/eclipse/che/tree/master/deploy/openshift/templates[ option: Deploy multi user Che with bundled Keycloak and Postgres (https)]
The installation is successful and able to launch the eclipse CHE in the browser. I can see the technology stack that i can select to launch a particular choice of my selection as well. However, when i try to launch any work space irrespective of the technology stack, even the sample examples that comes out of the box in eclipse CHE projects are not loading into the workspace.

## Relevant information

Error:
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedMount', 'Unable to mount volumes for pod "workspace6gorcd2rtxfg29uh.gradle-7b49575fff-dh2qg_dev-ops(4abf608b-3412-11ea-b015-000d3a8c1b5c)": timeout expired waiting for volumes to attach or mount for pod "dev-ops"/"workspace6gorcd2rtxfg29uh.gradle-7b49575fff-dh2qg". list of unmounted volumes=[plugins m2 claim-che-workspacegzabvrjq claim-che-workspaceo713qixl]. list of unattached volumes=[remote-endpoint plugins m2 claim-che-workspacegzabvrjq claim-che-workspaceo713qixl claim-che-workspaceaooshum6 workspace6gorcd2rtxfg29uh-sshprivatekeys ssshkeyconfigvolume gitconfigvolume default-token-dwnkt]', 'workspace6gorcd2rtxfg29uh.gradle-7b49575fff-dh2qg'"

### Che version

 - [x] latest
 - [ ] nightly
 - [x] other: please specify
          Tried to launch the workspace with nightly latest and 7.1.0, 7.2.0 etc. Same result with all of them.
### Expected behavior

The workspsace should have launched and able to access the projects from git repository.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify)
           Azure RedHat Openshift (ARO)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
   - [ X] Installed from yaml files with OC commands

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) 
   - [x] other: ARO

**Comment by echvsg** [comment]
@tolusha : should i create any defect/bug so that the "team/deploy" can prioritize this one?

**Comment by tolusha** [comment]
@echvsg 
Pls update the description of the issue.
I've already changed to a bug.

**Comment by IveJ** [comment]
Hi Echvsg,

If nomore details, here plz review some info, for your bugs.

https://github.com/Microsoft/openshift-container-platform/tree/azurestack-release-3.9


https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/

**Comment by tolusha** [comment]
@echvsg 
Install `chectl` [1] and launch `chectl server:logs` to see of there are any errors.

[1] https://github.com/che-incubator/chectl
