### ISSUE TITLE
Redesign "Import Devfile" page

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15661]
### Is your enhancement related to a problem? Please describe.
We need "Import Devfile" option on Getting Started page and it could be existing functionality "Import Devfile" but we need to redesign it.

Here are examples of the current behavior we have (unfortunately it's not available on Hosted Che yet):
1. Use GitHub repository URL that contains devfile.yaml file inside:
![github-with-devfile](https://user-images.githubusercontent.com/5887312/72205160-977d7680-3488-11ea-9d04-0dcc4480100f.gif)

2. Use GitHub repository URL that does not contain devfile.yaml file inside:
![github-without-devfile](https://user-images.githubusercontent.com/5887312/72205169-baa82600-3488-11ea-873c-e966f8d4240e.gif)

3. Use url to devfile raw content:
![raw-content-url](https://user-images.githubusercontent.com/5887312/72205186-d90e2180-3488-11ea-83de-25beb5070556.gif)

4. Use raw devfile content:
![use-raw-content](https://user-images.githubusercontent.com/5887312/72205192-f04d0f00-3488-11ea-842d-22149577298d.gif)

### Describe the solution you'd like
Will be provided later

**Comment by gazarenkov** [comment]
"Import Devfile" from GitHub repository that does not contain devfile sounds a bit contradictory, no? :)

**Comment by sleshchenko** [comment]
> "Import Devfile" from GitHub repository that does not contain devfile sounds a bit contradictory, no? :)

Yes, it's why error message is shown. Nobody can prevent users from using invalid URL or URL without devfile content inside =)

**Comment by sleshchenko** [comment]
The functionality will be a part of Create Custom page implemented in https://github.com/eclipse/che/issues/15662
