### ISSUE TITLE
Document Airgap Setup for Python

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15664]
Test and document the process of setting up an airgap solution for python. In particular, configure a workspace based on our default python devfile to use a repository that uses a self-signed certificate.

**Comment by svor** [comment]
The instructions were described here https://docs.google.com/document/d/1RGfczUA44LzkiiZ0PRqAJZmBpX_yVH6i7uidbIa-pBo/edit?usp=sharing

**Comment by ericwill** [comment]
@svor is there anything left to do here?

**Comment by svor** [comment]
@ericwill we can close it
