### ISSUE TITLE
Can't set `CHE_API_INTERNAL`.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#15663]
### Describe the bug

After fixed #9323, `che.api.external` should be usable for web accesses.
But `infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/KubernetesCheApiInternalEnvVarProvider.java` refers `che.api` instead of `che.api.external`.
So I can't get `CHE_API_EXTERNAL` in containers. 

### Che version

 - [x] nightly

### Steps to reproduce

1. start Che with `CHE_API_EXTERNAL` (or `che.api.external`)
2. start any workspace.
3. open the terminal.
4. run `export` shell command.

### Expected behavior

`CHE_API_EXTERNAL` have the value that set at "Steps to reproduce" above.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 

But it will be same even if you use OpenShift.

**Comment by monaka** [comment]
I see this issue is caused by there.

https://github.com/eclipse/che/blob/6bf6ed1b243c8221bcc74be22646e73352249592/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/KubernetesCheApiExternalEnvVarProvider.java#L31

I'm checking if there is no side-effect by fixing it.

**Comment by skabashnyuk** [comment]
@monaka  `CHE_API_EXTERNAL` and `CHE_API_INTERNAL` is a set of the variables for workspaces that were added    https://github.com/eclipse/che/pull/9475  `Add internal and external API URL environment variables for workspaces ` the main intention of it is a difference in behavior in docker world, k8s uses mainly `CHE_API` .  This is a quite sensitive topic and changing it might be quite complicated.  Can you explain what kind of functionality is not working on workspaces? Or if we talking about the ability of how it is set or configured probably it should be considered as a new feature/enhancement.

**Comment by monaka** [comment]
@skabashnyuk IMO, providing both CHE_API_EXTERNAL and CHE_API_INTERNAL is reasonable even if it was in K8s/OpenShift world.

Workspace containers will connect to the ingress (or external endpoint that have external IP) if CHE_API contains public domain name.
On the other hand, URLs with `http://che-server:8080/api` will be resolved as the local IP address by the local DNS.

At the viewpoint of functionality, some ingresses like Nginx does't handle websockets well.
So I want to avoid connections via Ingresses if it was possible. 

I can't say with absolute certainly since implementation of Ingresses are so many, but I just can say it's better to suppress traffic to  Ingress.
It will give us some stability and quick response.

**Comment by monaka** [comment]
After checking code, I suppose it's better to modify rules of properties to environment variables like below.

```
che.api -> CHE_API and CHE_API_EXTERNAL
che.api.internal -> CHE_API_INTERNAL
```

The current rule `che.api ->  KubernetesCheApiInternalEnvVarProvider -> CHE_API and CHE_API_INTERNAL` is not fit to the current use-case.

Wsmaster won't use both `che.api.internal` and `CHE_API_INTERNAL`. It's just for workspace containers.

The default value of `che.api.internal` should be `http://${CHE_HOST}:${CHE_PORT}/api`. It will be no need to overwrite the value of `che.api.internal`.

It might `CHE_API_EXTERNAL` is redundant but we can't remove it immediately because it is shown in Che-Theia repository.

I've already wrote a patch based on above and testing it now.
