### ISSUE TITLE
HTML preview and extra plugins

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1566]
May be this goes into plugins but I found some important (to us) HTML features to be missing:
- [ ] Emmet
- [ ] HTML entities encode/decode
- [x] HTML preview of current file (not the most important if a good Docker server can run in the cloud and expose for example port 8080 but depends when that would be available)

**Comment by wernight** [comment]
I see there is already a decent support for [preview using commands](https://eclipse-che.readme.io/docs/previews) so marking that one as done or not so important.

**Comment by slemeur** [comment]
Closing as fixed in Che 7
