### ISSUE TITLE
[Hosted Che] Workspaces are not idling on prod-preview after 7.7.0 update 

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15667]
### Describe the bug
The workspace remains running for ~7 hours (at time I'm writing this report). 
Kibana logs screenshot attached.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
A workspace should be stopped after 15 minutes (idling timeout set to 15 minutes on Hosted Che).

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: Hosted Che

### Screenshots

![Screenshot from 2020-01-13 10-46-12](https://user-images.githubusercontent.com/29278800/72246515-2b6b5180-35f3-11ea-8cd4-979ab72b2466.png)

**Comment by ibuziuk** [comment]
Should be fixed by - https://github.com/redhat-developer/rh-che/pull/1757

**Comment by ibuziuk** [comment]
Actually, jgroups is not a culprit here - Activity Checker is failing with 
 org.eclipse.che.api.workspace.activity.WorkspaceActivityChecker

![image](https://user-images.githubusercontent.com/1461122/72275608-8b331e00-362e-11ea-84d5-13dceb24aef8.png)

**Comment by ibuziuk** [comment]
Updating priority since this issue is a showstopper for Hosted Che update to the latest version - https://github.com/eclipse/che/issues/15625 
We would probably need to request a `7.7.1` bug-fix release
