### ISSUE TITLE
Make it possible to get OpenShift oauth token from theia IDE container

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#15670]
### Is your task related to a problem? Please describe.

We need an OpenShift authentication token to inject it to Openshift connector plugin if Che is started on OpenShift.

**Comment by ibuziuk** [comment]
@vinokurig please add the right priority according to the plugins team planning

**Comment by skabashnyuk** [comment]
I think we should be really careful with OS token. It provides to much power. 
It makes sense to wait for https://github.com/eclipse/che/issues/15651 first after that provide token only in a workspace that is not shared until we have some clarification from https://github.com/eclipse/che/issues/15304. Or ideally, that should not be an automated process that adding something by default, instead the user has to do some explicit actions that confirm his intention to inject OS tokens into his workspace.

**Comment by vinokurig** [comment]
@ibuziuk I think this issue is not in the scope of the plugins team responsibilities. The issue is about providing authorisation token. @l0rd @benoitf WDYT?

**Comment by vinokurig** [comment]
I think adding an [OAuthAuthenticator](https://github.com/eclipse/che/blob/5b259b2b31f4f39e32c9cafa4007133928d88735/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java) implementation for Open-Shift will help @skabashnyuk WDYT?
