### ISSUE TITLE
Upgrade VS Code Camel K extension to version 0.0.11

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15676]
### Is your enhancement related to a problem? Please describe.

this version is coming with published sources that are needed by CodeReady Workspaces, see https://issues.redhat.com/browse/FUSETOOLS2-80

The Camel K CLI default has been upgraded. It requires then to update the base image too.
It also comes with new features when VS Code Java 0.55+ is installed. Would be nice to check if it is working.

**Comment by apupier** [comment]
the sidecar image is here https://github.com/che-dockerfiles/che-sidecar-camelk

**Comment by nickboldt** [comment]
You may also want to move up to https://github.com/apache/camel-k/releases/tag/1.0.0-RC1 from 1.0.0-M4

**Comment by apupier** [comment]
yes, it is the case: https://github.com/apupier/che-sidecar-camelk/blob/c970de14a67f5a2f1863783a32c249db157ddbc7/Dockerfile#L12

this is what I meant in 
> The Camel K CLI default has been upgraded. It requires then to update the base image too.

**Comment by apupier** [comment]
done but cannot test yet for Java standalone as Language support for Java is blocked on 0.50 and we require 0.55+
