### ISSUE TITLE
Provide information from which sources the images on quay.io are built

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15685]
### Is your task related to a problem? Please describe.

when searching for sidecar images, I wasnt able to find where the source code is.
I'm not alone in [this case](https://issues.redhat.com/browse/CRW-544?focusedCommentId=13947671&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13947671)

### Describe the solution you'd like

on quay.io, it would be nice to have the information where are the sources from which the image was built
For instance for Camel K sidecar: https://quay.io/repository/eclipse/che-sidecar-camelk

### Additional context

quoting Sun:

> also some image are rebuilt/patched here, if you can't find the sources in gh: https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/base_images

**Comment by gattytto** [comment]
the file https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/build_images.sh is executed from within github workflows and the images mentioned in arbitrary_users_patch/base_images are used as base, with some permissions changed to build and publish the final built images to quay.io/eclipse/eclipse-dockerimage_file-version

**Comment by gattytto** [comment]
there are 2 kind of images:
CLI images, and sidecar images.

- CLI images are the ones you run the devfile(workspace) TASK in

- SIDECAR images are the ones that extensions use to execute their commands

CLI images are built from devfile-registry/arbitrary-users-patch/base_images using the script defined in https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/build_images.sh . This script takes the base_images from the second column and does some permission changes to the image, then builds the image and publishes it to quay.io/eclipse/che-language-version:nightly package which is then referenced in devfiles.

SIDECAR images are built directly from the Dockerfiles in the mentioned github.com/eclipse/che-dockerfiles repo using a branch specific to a version so the resulting image is of the type:
quay.io/eclipse/che-sidecar-go:1.12.9-304cd66

**Comment by l0rd** [comment]
Assigning this to  `team/languages` for the language sidecar images and `team/plugins` for others sidecars (camelk included).

cc @tsmaeder @ericwill

**Comment by ericwill** [comment]
Is this something we should put on quay.io? Or somewhere else (like a comment in a plugin's meta.yaml, for example)?

**Comment by apupier** [comment]
> Is this something we should put on quay.io? Or somewhere else (like a comment in a plugin's meta.yaml, for example)?

Personally, I searched in both of these places initially. So I would say both can fulfill the requirements.
With a comment inside the plugin's meta.yaml, I think it might become more easily unsynchronized and can be forgotten for new plugins.

**Comment by benoitf** [comment]
I've added link on quay.io
