### ISSUE TITLE
chectl add ability to override Eclipse Che custom resources definitions

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15684]
### Is your enhancement related to a problem? Please describe. 
In the chectl we have an option `--che-operator-cr-yaml` to set up Eclipse Che custom resources yaml. But to change few properties  in the custom resources user should COPY-PASTE all yaml file. And before that user should somehow find this operator-cr-yaml compatible with desired Eclipse Che version installation.
It is not user friendly and this option hard to use to define configuration changes in the documentation. For example you want to provide some properties which user should modify, but before that you need to explain that user should find somewhere yaml, search needed fields from pretty big list, and edit target properties. It looks not trivial and requires to much actions from user.

### Describe alternatives you've considered
It would be nice to have some argument to apply file with overrides Eclipse Che custom resources, where is user can define only desired properties list to override.

As an example if users wants to override PVCs class name then they executes: `chectl server:start --che-cluster-patch-path ./checluster-cr-overrides.yaml` where `checluster-cr-overrides.yaml` has the following content:
```yaml
spec:
  storage:
    postgresPVCStorageClassName: "my-custom"
    workspacePVCStorageClassName: "my-custom"
```
P.S. The similar argument could be considered to be implemented to provide values overrides for helm chart. But definitely in a scope if new issue.

**Comment by sleshchenko** [comment]
It totally makes sense! I think it's really great an ability to customize everything within chectl command without an endless list of command arguments.
The same argument could be used later for server:update command.

**Comment by gattytto** [comment]
is this related? https://github.com/eclipse/che/issues/15600

**Comment by l0rd** [comment]
@AndrienkoAleksandr it makes sense, that's a good idea. To be consistent with the existing `--che-operator-cr-yaml` flag I would name the new flag `--che-operator-cr-patch`.

**Comment by l0rd** [comment]
@gattytto that's a good point. When fixing this one we may fix the 2 issues you are mentioning too.
