### ISSUE TITLE
Error 403 and CORS Blocked Requests in configuration: Docker(single-mode)+localhost

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#15687]
I researched this article [Eclipse Che 6.15, 6.16, and 6.17 Release Notes](https://che.eclipse.org/eclipse-che-6-15-6-16-and-6-17-release-notes-362cff44dcc9) and these issues #12644 , #12350 and decided that what about I want to report is bug. Fix me If I am wrong.

### Steps to reproduce
* Run Che as described in the documentation to version 6.19.6
```
sudo docker run -p 18080:8080 -e CHE_HOST=localhost --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/user:/data eclipse/che-server:6.19.6
```
there is  `CHE_HOST=localhost` was added on demand of cli, but I also used ip instead of host.
* Create workspace from some type, for instance Java
* Try to run it. 

*AR:*
First request to ws-agent will be failed with error 403 and message in console `Access to XMLHttpRequest at 'http://localhost:32848/api/project-type' from origin 'http://localhost:18080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` (if you use Chrome, in Firefox message will be similar). 

I tried to use some flags: CHE_CORS_ENABLED, CHE_WSAGENT_CORS_ENABLED ant etc. But It did not help me. Error 403 has gone but the error about the blocked request is left.
See comment https://github.com/eclipse/che/issues/12350#issuecomment-574062557.

### Che version
 - [] 6.19.6

### Runtime
   - [ ] Docker under Linux
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
   - [ ] Docker under Windows
``` Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
### Environment
   - [ ] Linux Ubuntu 19.04
   - [ ] Windows 10 + Ubuntu WSL1 18.04
       
Problem is not depended on OS and can be reproduced in Windows and Linux.

**Comment by gattytto** [comment]
this issue is not related to the ip/host part of the url, it is related to the :port slice of it. 
if you entered a url from the first time (localhost:8080 is the actuall full URL, not only the host part) you can not then just use javascript to fetch resources from localhost:31723 or whatever, then CORS occurs.

In the case of minikube/kubernetes/cloud-native an ingress controller is used, it then filters the url to know which container at which port is listening for requests at that url path. 

To reproduce this issue one can set up a Che 7 minikube setup and use external devfile and plugin registries. Even if they are hosted in the same host/ip than the che server, CORS will occur. 
Then, running the same setup but with the devfile and plugin registries insidethe minikube cluster, it will work without problems.

**Comment by gattytto** [comment]
I can't find the exact dates, but CORS was "configurable" in browsers for a time span and then became an enforced default in all browsers later. That might explain why it started happening after browsers went auto-updated. 
Now even if you configure the browser to allow CORS the setting will not take effect and it won't be allowed

**Comment by gattytto** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by l0rd** [comment]
@gorshkov-leonid we are not maintaining Che 6.x anymore, please try Che 7.x

**Comment by gorshkov-leonid** [comment]
```
CHE_IP=$(docker run --net=host eclipse/che-ip:6.19.0)
docker run -p 18080:18080 -e CHE_HOST=localhost -e CHE_IP=$CHE_IP -e CHE_PORT=18080 --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/me:/data eclipse/che-server:6.19.6 
```
