### ISSUE TITLE
How to hide the left navigation menu items?

### ISSUE THREAD

**Issue by ming-ddtechcg** [eclipse-che/che#15681]
Are there options to hide the individual selections from the left navigation panel through devfile?  The selections can be "Administration", "Organization", or "Factories"... etc?

**Comment by monaka** [comment]
Usually, you can close by clicking the tab colored yellow.

![ink (4)](https://user-images.githubusercontent.com/101795/72316493-adce4100-36d9-11ea-95d5-bb95c5868765.png)

**Comment by ming-ddtechcg** [comment]
Users can click the yellow ">" to show the menu back.

**Comment by l0rd** [comment]
@ming-ddtechcg there is no way to hide those sections. What's the user case? Why would you want those to be hidden?

**Comment by ming-ddtechcg** [comment]
Just hide the features from a group of developers if they do not need to know about.
