### ISSUE TITLE
Add e2e selenium tests for Getting Started Page for UD

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#15703]
### Is your enhancement related to a problem? Please describe.

Add e2e selenium tests for Getting Started Page for UD.

### Describe the solution you'd like

We should cover the next steps:

1. If the user doesn't have any workspaces and clicks on the Dashboard(navbar menu), Get Started page will be opened. 

2. Templates should be selectable. If we have a selected template, the 'Create and Open' buttons will be enabled(and the opposite).

3. We should lose the selection If the template becomes invisible after filtering.

4. Check how 'Create and Open' buttons(both) work including 'Create & Proceed Editing' mode. 

5. Check how the template filtering works. Check the numbers of items after each filtering.

6. Check redirection to './create-workspace' after clicking the 'Create a Custom Workspace' button.

Details:

![out-3](https://user-images.githubusercontent.com/6310786/72423649-4d004080-378d-11ea-9954-a361159b03fd.gif)

**Comment by rhopp** [comment]
Hello @olexii4 ,
I don't think, that e2e tests (nor integration tests) are a good place for such kind of tests you are requesting here.
The proper place for this kind of tests should be UI tests of dashboard itself (which are [here](https://github.com/eclipse/che/tree/master/dashboard/e2e), if I'm not mistaken).

What we can do on our side is really small subset of what you are requesting - We have (or will have) e2e scenarios for each default stack. We could make sure, that we are creating workspaces in this scenarios using this new dashboard page, but it wouldn't contain any deep testing of filtering functionalities etc. These tests should be done on "component level" as I wrote before.

**Comment by sleshchenko** [comment]
@rhopp 

> What we can do on our side is really small subset of what you are requesting - We have (or will have) e2e scenarios for each default stack. We could make sure, that we are creating workspaces in this scenarios using this new dashboard page, but it wouldn't contain any deep testing of filtering functionalities etc. These tests should be done on "component level" as I wrote before.

As we discussed during call, it sounds good. More detailed testing should be implemented on e2e dashboard side after they are restored https://github.com/eclipse/che/issues/15891

**Comment by rhopp** [comment]
I've created a followup issue for E2E tests of whole Che - https://github.com/eclipse/che/issues/15931

**Comment by olexii4** [comment]
@rhopp Sorry. I was on a long vacation. and couldn't write the answer.
