### ISSUE TITLE
add shortcut for Quick Fix to editor

### ISSUE THREAD

**Issue by torzsmokus** [eclipse-che/che#1570]
**_1 Upvote**_ I’m using beta.codenvy.com. The Quick Fix feature is buried in the menu without a shortcut and thus a PITA to use. The normal Eclipse shortcut {Cmd,Ctrl}+1 does not apply in Codenvy.

Version: 4.3.4
Revision: 5cb83bdceb9aae28

**Comment by slemeur** [comment]
Hi @torzsmokus 

The existing shorcut is {alt + enter}.

**Comment by TylerJewell** [comment]
@slemeur Should we include the shortcut codes in the menu - so you can see them next to the entry?

**Comment by slemeur** [comment]
+1 asked @vzhukovskii to add it.

**Comment by vzhukovs** [comment]
PR is pending for merge https://github.com/eclipse/che/pull/1573

**Comment by vzhukovs** [comment]
Implemented
