### ISSUE TITLE
[Dogfooding] Increase idle timeout for workspaces on che.openshift.io

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15708]
### Is your task related to a problem? Please describe.

For comfortable dogfooding on che.openshift.io we need to increase idle timeout. Let's say, two hours will be enough to have a small break and then continue working without loosing some data.

Having around ten minutes or five as we have now, is not enough.
My workspace is stopped after switching to another window for quick reading a doc.

**Comment by ibuziuk** [comment]
this should be a PM decision cc: @slemeur

**Comment by benoitf** [comment]
could it be a per user setting as well ?

**Comment by sleshchenko** [comment]
> could it be a per user setting as well ?

Che Resource API allows such an ability.

**Comment by neuharthr** [comment]
Is this being considered to have a 2 hour timeout configuration per user or workspace? The 10 minute is just too short for.
