### ISSUE TITLE
Move pre-release test jobs to ci.centos

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#15701]
### Is your task related to a problem? Please describe.
On codenvy.ci we were triggering these jobs manually.
We need to find a way how to perform pre-release testing on ci.centos.org (as manual trigger is not an option there) and move the jobs there.

List of jobs:
https://ci.codenvycorp.com/view/qa-rc/

**Comment by rhopp** [comment]
We've discussed the possible approach with Vitalli today and this is the suggested outcome:
### Testing of RC artifacts

* Vitalli (or whoever is doing the release of Che) will ping QE, that rc images (quay.io/eclipse/che-server:rc-7.9.0, quay.io/eclipse/che-keycloak:rc-7.9.0, ...(images built from che repo)) are ready.
    * che-theia, registries etc. are already released (a.k.a. quay.io/che-plugin-registry:7.9.0, ...)
* QA engineer will merge the release branch to our rc-testing branch (`cico-rc-test`).
    * This will trigger the testing jobs on ci.centos which:
        * Extract the current version from pom.xml (mvn help:evaluate -Dexpression=project.version -q -DforceStdout).
        * Do all necessary changes for correct deployment using chectl (customresource.yaml, ...)
        * Installs che & runs the tests against it.

**Comment by artaleks9** [comment]
#15701
Moving releases jobs:
Java selenium:
- Move Multiuser stable - in progress
- Setup jobs to be triggered by push to some "qe" branch - in progress
- Move Multiuser all - not started
- Move Hot update - not started

- Happy Path - not started (it's on crw jenkins)
- Devfiles tests - not started (it's on crw jenkins)
- OCP OAuth - not started (it's on crw jenkins)

**Comment by artaleks9** [comment]
**Moving releases jobs:**
(Java selenium on ci.codenvycorp):

* _che-integration-tests-multiuser-ocp-rc_ - Done => [che-rc-multiuser-integration-tests](https://ci.centos.org/view/Devtools/job/devtools-che-rc-multiuser-integration-tests/)
* _che-multiuser-ocp-oauth-test-rc_ - Done => [che-rc-ocp-oauth-test](https://ci.centos.org/view/Devtools/job/devtools-che-rc-ocp-oauth-test/)
* _che-multiuser-ocp-rolling-strategy-test-rc_ - Done => [che-rc-rolling-strategy-test](https://ci.centos.org/view/Devtools/job/devtools-che-rc-rolling-strategy-test/)
* setup jobs to be triggered by push to some "qe" branch - Done
----
* _che-integration-tests-multiuser-ocp-rc_ - Not Started (this task has a low priority and will be done later).
* _che-multiuser-ocp-recreate-strategy-test-rc_ => Now this functionality is switched off, so the job is always failure. See more details:  https://github.com/eclipse/che/issues/15915. So the job will be updated or renamed.

-----

**Comment by rhopp** [comment]
Done by this: https://github.com/eclipse/che/pull/16039
