### ISSUE TITLE
git and github checkout not behaving consistently

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15719]
### Describe the bug
using git checkout with a url, i.e. https://github.com/maxandersen/jbang gives me a project named `jbang`. As expected.

Using github checkout of same repo gives me a project named `maxandersen-jbang`

This should be `jbang` in both cases imo.

**Comment by tsmaeder** [comment]
@maxandersen you mean adding a project to the workspace via the dashboard on the "github" vs the "git" tab?

**Comment by maxandersen** [comment]
correct @tsmaeder !

**Comment by sleshchenko** [comment]
The described UI is not present on the new Dashboard
