### ISSUE TITLE
repeatedly asked for login on che.openshift.io - low timeout ? 

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15714]
### Is your enhancement related to a problem? Please describe.
I don't know why but when accessing che.openshift.io I seem to get asked very often about red hat developer login. What feels like 3-4 times daily. Other online services don't ask me about login for days; or at least just what feels once a day the first time I enter.

### Describe the solution you'd like
Don't ask me about my username/password constantly or make the login a single page rather than multiple steps.

**Comment by ibuziuk** [comment]
@alexeykazakov can we do smth with that on auth side ?

**Comment by alexeykazakov** [comment]
Auth issues a user token and a refresh token. Both are valid for 30 days.
And with having a refresh token available you don’t really need to ask user to re-login at all if the user uses Che.openshift.io at least once in 30 days.
Not sure why Che keeps re-logging users.

**Comment by slemeur** [comment]
sounds more like a bug then.

**Comment by ibuziuk** [comment]
@Katka92 @ScrewTSW is it the cause of https://github.com/redhat-developer/rh-che/issues/1678  ?

**Comment by Katka92** [comment]
@ibuziuk I don't think so, this is not asking us to log in again, sometimes tests just do a refresh of a page and it works again. Sometimes it lasts longer and even the refresh does not help. But it never pushes us back to the login page.

**Comment by piyushpatel2005** [comment]
It does take long time to login and also it displays weird pages. Since the time Red Hat acquired it, it has been working really bad. CodeEnvy.io was much better.
