### ISSUE TITLE
Add ms-vscode Bazel extension to che-plugin-registry

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#15712]
### Is your enhancement related to a problem? Please describe.

No

### Describe the solution you'd like

Add the Starlark language ms-vscode extension which also enables the Bazel open source build system (related to protoc and gRPC)

### Additional context

The open source build system “Bazel” is anagram for Blaze, Google’s closed source and patented (https://patents.google.com/patent/US20030163783) suite of tools (like the rules editor called Blaze Advisor/Innovator Workbench (TM)) created to produce what they call “expert systems”.

Bazel build system is language agnostic and uses the Starlark https://github.com/bazelbuild/starlark/  language for its configuration and macro files (WORKSPACE and .bzl files).

https://github.com/bazelbuild/vscode-bazel

https://github.com/bazelbuild/vscode-bazel/releases/download/0.3.0/vscode-bazel-0.3.0.vsix

**Comment by tsmaeder** [comment]
We _really_ need a way for the community to create and maintain their own ecosystem of plugins.

**Comment by gattytto** [comment]
> We _really_ need a way for the community to create and maintain their own ecosystem of plugins.

I forked plugin registry and created a systemd unit that updates and restarts it upon reboot. then I just add new plugins to my registry. 

But some things are not as straightforward like plugin preferences (see https://github.com/eclipse/che/issues/15577#issuecomment-573911215) or ms-vscode builtins (see https://github.com/eclipse/che/issues/13672).

**Comment by gattytto** [comment]
so far using the clang Dockerfile base image and adding:
`
RUN cd /tmp && wget https://github.com/bazelbuild/buildtools/releases/download/0.29.0/buildifier && chmod 777 buildifier && mv buildifier /usr/bin/

RUN cd /tmp && wget https://github.com/bazelbuild/buildtools/releases/download/0.29.0/buildozer && chmod 777 buildozer && mv buildozer /usr/bin/

RUN cd /tmp && wget https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-linux-x86_64 && chmod 777 bazel-2.0.0-linux-x86_64 && mv bazel-2.0.0-linux-x86_64 /usr/bin/bazel

`
and using the following meta.yaml for the plugin:
`
apiVersion: v2
publisher: ms-vscode
name: bazel
version: 0.3.0
type: VS Code extension
displayName: Bazel
title: Starlark files and bazel build support
description: This extension adds rich language support for Starlark
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/bazelbuild/vscode-bazel
category: Language
firstPublicationDate: '2019-09-19'
spec:
  containers:
    - image: "quay.io/gattytto/che-sidecar-bazel:latest"
      name: vscode-bazel
      memoryLimit: '256Mi'
  extensions:
    - https://github.com/bazelbuild/vscode-bazel/releases/download/0.3.0/vscode-bazel-0.3.0.vsix
`
works out of the box. 

![image](https://user-images.githubusercontent.com/407397/72645937-9c906900-3953-11ea-92a2-61d39af7c80c.png)

Only thing that doesn't seem to work is the BUILD TARGETS window (see screenshot).

**Comment by gattytto** [comment]
for BAZEL build targets window to get populated one has to press F1)> "Add folder to workspace" and add the root folder that contains WORKSPACE and BUILD.bzl files. then hit reload in targets window

**Comment by JessicaMan** [comment]
Hi, I would like to add the bazel vscode extension to Eclipse Che which is hosted on GKE, I have the meta.yaml using the content above, could you guide us how to add the meta.yaml to the default che plugin registry without having to build a custom registry in order to add the plugin please?

**Comment by gattytto** [comment]
@InterestedInTechAndCake in https://redhat-developer.github.io/devfile/ you can go to the cheplugin "reference" preferences property, it can be a link to a meta.yaml. Then in that meta.yaml file you can either reference a plugin container image built by you from a base image or just any other pre-built image like the ones google provides at https://cloud.google.com/cloud-build/docs/cloud-builders

keep in mind that once built, che plugin containers are rootless so you can either make a custom image with all the tools you need or find an image that ships with a non-root package manager to add other tools or compile them manually, using the posStart and preStop properties (which I assume must be shell commands that will be run inside the container accordingly). 

I hope this helps propagate your doubts on this subject
