### ISSUE TITLE
Find a better way than putting "M" on all folders when I modify a file

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15715]
### Is your enhancement related to a problem? Please describe.
The `M` indicator that gets added on every folder to mark something is modified feels very clunky/noisy.

![2020-01-16_11-26-01](https://user-images.githubusercontent.com/54129/72517053-fcebb180-3852-11ea-86fc-a7984846f368.png)

### Describe the solution you'd like
Its 2020 and a browser can use graphics/styles :)

vscode's approach is visually less noisy and more appealing + you can see whats *actually* changed as only the files have a `M`.

![2020-01-16_11-27-13](https://user-images.githubusercontent.com/54129/72517229-476d2e00-3853-11ea-831d-bd7d8dc42745.png)

**Comment by ibuziuk** [comment]
I think the corresponding issue should be opened on theia side cc: @azatsarynnyy

**Comment by azatsarynnyy** [comment]
Filed upstream https://github.com/eclipse-theia/theia/issues/6904
