### ISSUE TITLE
Best way to reference secret data in a plug-in's environment

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#15711]
## Summary

Can I reference a secret to fill in an environment variable in a che plugin or a devfile (like you can in a podSpec)?  For hosted che we are trying to add a telemetry plugin, and the container needs an API key to be passed into the environment.  I don't want to pass this in plain text in the `env` section of the plugin's `meta.yaml`.  Is there a recommended way to do this?

**Comment by davidfestal** [comment]
That shouldn't be necessary, at least for telemetry, since the Woopra telemetry backend only uses env variables when it cannot fetch the values from the related central Che server API endpoints.

@tomgeorge do you think it still makes sense to keep this issue opened ?

**Comment by tomgeorge** [comment]
I'm more wondering if this feature exists, irrespective of the telemetry plugin.
