### ISSUE TITLE
Github selection/filtering is very slow and hard to use

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15718]
### Is your enhancement related to a problem? Please describe.
When I connect github the wait is very long (I assume because che are attempting to load *all* my repositories which are in several hundreds)

![2020-01-16_11-33-58 (1)](https://user-images.githubusercontent.com/54129/72518029-b7c87f00-3854-11ea-8d30-6de3fc3467b9.gif)

 and once loaded the filtering text field is very clunky.

![2020-01-16_11-33-58 (1)](https://user-images.githubusercontent.com/54129/72518176-ff4f0b00-3854-11ea-821b-47dd22a7f248.gif)

Hard to see on the video but the characters don't show up even thouhg i'm typing from the start. 
sometimes the field stays blank but the dialog below does get filtered...sometimes it duplicates the text as if not properly listening to the typing.
  
### Describe the solution you'd like
Load the repositories incrementally, don't have the textfield block when filtering.

**Comment by slemeur** [comment]
cc @beaumorley.
@maxandersen : In general the overall experience creating a workspace, importing a source code repo needs to be completely revisited. We've started to collect thoughts on thiss.

**Comment by sleshchenko** [comment]
It's still an issue for Workspace Details page

**Comment by sleshchenko** [comment]
The described UI is not present on the new dashboard.
