### ISSUE TITLE
dont add sample project when I'm adding my own project 

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15722]
when creating a workspace and you add your own git/github project the sample project always gets added and its tedious to actually remove it afterwards.

suggestion: still add it by default but as soon as I click + to add my own remove it so it doesn't show up next to my actual project.

**Comment by slemeur** [comment]
This one is along with the comment on https://github.com/eclipse/che/issues/15718#issuecomment-575571605

cc @beaumorley

**Comment by sleshchenko** [comment]
It references the removed UI. @maxandersen Feel free to open a new issue if new Create Custom Workspace does not provide good UX in your opinion.
