### ISSUE TITLE
when container runs out of disk space the UI becomes fully unresponsive

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15729]
### Describe the bug
create a project, i.e. cloning https://github.com/maxandersen/jbang and run ./gradlew in a terminal.

when using ephemeral on che.openshift.io it will run out of disk space very quickly with no warning and after that the workspace/UI is just dead.

Only way out afaicis was to kill the workspace meaning I would have lost my changes.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: che.openshift.io

che should not freeze or if it will freeze on out of disk should protect user from taking up the disk space.

**Comment by tsmaeder** [comment]
Not sure what area this should be.

**Comment by skabashnyuk** [comment]
As I can see this is about UI. Reassigning to Che - Theia.

**Comment by maxandersen** [comment]
i don't think it’s an UI issue - the UI stops responding because the backend gets stuck/crashes when it shouldn't ?

**Comment by skabashnyuk** [comment]
Yes. Make sense. Che - Theia backend should react to that possibility more user-friendly.

**Comment by ScrewTSW** [comment]
Still present on 7.23.1 in ephemeral moce

**Comment by ScrewTSW** [comment]
Still present in 7.25.2
