### ISSUE TITLE
Can't create more than 30 work spaces on Che v7.4.0

### ISSUE THREAD

**Issue by jswordfish** [eclipse-che/che#15724]
We have build a wrapper around Che and are using Api's to create workspaces on cHE.

Beyond 30, We can't create more workspaces either through API's or through Eclipse Che dashboard.

Just wondering is this a magic no that can be controlled by some configuration?

**Comment by skabashnyuk** [comment]
Can be related to https://github.com/eclipse/che/issues/15098

**Comment by jswordfish** [comment]
@skabashnyuk In #15098 The issue creator can open workspaces with a direct link. 
Mine is different as I can't even open the workspace. May be its different:)

Othe specific - Using 7.4.0 over Kubernates.

**Comment by skabashnyuk** [comment]
@jswordfish can you provide more details



### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context



One more thing. 
You can create 31'st workspaces? you can start 31'st workspace? you can't open 31'st workspace in browser? you can't open 31'st workspace in the dashboard? What exactly is not working ?

**Comment by jswordfish** [comment]
@skabashnyuk 
<b>Describe the bug</b>
We have build a wrapper around Eclipse Che through which we create workspaces via api and then allocate the links to different users. Users are able to open the link through https://{domain}/dashboard/#/ide/{namespace aka username}/{workspacename}
<b>https://{domain}/{namespace aka username}/{workspace name} has never worked for us - though it may be a subject for a different discussion. </b>
This works well for 30 requests - meaning we can create workspaces through api's as well as open workspaces in browser tabs using above url format - https://{domain}/dashboard/#/ide/che/{workspacename}
Beyond 30, work spaces get created but can't be open in browser tabs as we get a 'Workspace doesn't exist, unable to open IDE.' on the browser
<b>Che version</b>
7.4.0

<b>Steps to reproduce</b>
1. Create more than 30 workspaces through api
2. Try opening the 31st url - https://{domain}/dashboard/#/ide/{namespace aka username}/{workspacename} 

<b>Expected behavior</b>
The 31st Workspace should open as it opens for the 30 workspaces before that. (Not too concerned now about 31st and more workspaces getting displayed now)

<b>Runtime</b>
 kubernetes

<b>Screenshots</b>
![image](https://user-images.githubusercontent.com/1023534/72595495-eebf9300-392f-11ea-8f20-65a57a9fb5cd.png)


<b>Installation method</b>

 I don't know

<b>Environment</b>
Ubuntu on Amazon Cloud

<b>Additional context</b>
One more thing.
<b>You can create 31'st workspaces?</b>
Can create through api
<b> you can start 31'st workspace? you can't open 31'st workspace in browser?</b>
Since I can't see these workspaces on dashboard, I can't start from there. But guessing When I use https://{domain}/dashboard/#/ide/{namespace aka username}/{workspacename} on a browser, it should start first and then open in that order at the same time. The message indicates it can neither be started nor be opened.
<b> you can't open 31'st workspace in the dashboard? What exactly is not working ?</b>
Can't see the workspace in dashboard but can't open the workspace url got through api in a browser tab

Hope above is sufficient enough to figure out a rc?

**Comment by jswordfish** [comment]
@skabashnyuk  / @tsmaeder 
Sorry this is out of place - just wondering is there any commercial support model or any support partner  who can help us in custom implementations? Once again my apologies of writing this here.

**Comment by skabashnyuk** [comment]
CC @sleshchenko @akurinnoy  Wdyt is this a loader thing https://github.com/eclipse/che/issues/15098 ?

**Comment by sleshchenko** [comment]
@jswordfish It should be fixed by https://github.com/eclipse/che/pull/15784
So, please check it on the nightly images or next released images that should be available in about week.
Feel free to open it if it's still actual.

**Comment by jswordfish** [comment]
@sleshchenko Can't open a workspace beyond 30. The steps, I outlined earlier (13 days back or so) - pls see above , still holds as of to reproduce the problem. Kindly reopen this?

**Comment by sleshchenko** [comment]
@jswordfish Could you provide Che Server image version you use?

**Comment by sleshchenko** [comment]
@jswordfish Please reopen if you face the same issue on the latest released Che
