### ISSUE TITLE
Add Gradle 6 support

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15723]
Gradle is now at version 6, stack in che is at 5.

**Comment by tsmaeder** [comment]
@maxandersen does gradle project usually just work with "latest" or do the use fixed, older versions? Our current plan is just to replace gradle 5 with gradle 6 in the stack.

**Comment by maxandersen** [comment]
gradle projects will mainly use gradle wrappers and yes they would stick to major even minor versions as there are more agressive deprecations/api differences than i.e. maven does.
