### ISSUE TITLE
che 7 - add stack button is missing

### ISSUE THREAD

**Issue by mcapello** [eclipse-che/che#15732]
Hi, i am new to che, 7 and I am trying it on a local microk8s cluster.
I intalled de miltiuser version with chectl.
I found same tutos saying to add custom stacks with a buttom , but I can not find it at all.
I need to provide my custom docker image to a workspace to run and build my project.
thanks fon any help.

**Comment by gattytto** [comment]
in the dashboard click "create workspace", then you have 2 options use existing stacks or upload (or link refrence) the devfile.
![image](https://user-images.githubusercontent.com/407397/72636622-30573a80-393e-11ea-8e30-67aa3873da1a.png)

**Comment by mcapello** [comment]
thanks !!  
that options where hidden, I have to scroll up to show them.

**Comment by veeramanikandanvv** [comment]
I have deployed eclipse che 7 multiuser mode with single host strategy on kubernetes cluster using helm. I am not able to see the updated stacks for che7.
