### ISSUE TITLE
Docs are not available within deployed Che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15737]
### Describe the bug
We used to have docs.war deployed with Che Server 
https://github.com/eclipse/che/blob/master/assembly/assembly-main/src/assembly/assembly.xml#L29
It allows the user to see the documentation that is actual for the Deployed version of Che.
For some reasons, `docs/che-7` is not available anymore
![Screenshot_20200117_144720](https://user-images.githubusercontent.com/5887312/72618679-4bc54400-3944-11ea-9650-08605b6ece94.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che
2. Open Dashboard.
3. Click Docs link that is located in the footer of `Workspaces page`.

### Expected behavior
Local Docs site is opened.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
confirm on crc against 7.7.0

**Comment by skabashnyuk** [comment]
There is an error during che-docs war build 
```
     [exec] Digest: sha256:b89288e31f679afd9569d9f759e9b6497a4d7e1867ac4a1e3eda94e713fa65e2
     [exec] Status: Downloaded newer image for eclipse/che-docs:latest
     [exec] chown: unknown user/group jekyll:jekyll
     [exec] /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find concurrent-ruby-1.1.5 in any of the sources (Bundler::GemNotFound)
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `map!'
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `materialize'
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:170:in `specs'
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:237:in `specs_for'
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:226:in `requested_specs'
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:108:in `block in definition_method'
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:20:in `setup'
     [exec] 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler.rb:107:in `setup'
     [exec] 	from /usr/local/bundle/gems/jekyll-3.7.4/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
     [exec] 	from /usr/local/bundle/gems/jekyll-3.7.4/exe/jekyll:11:in `<top (required)>'
     [exec] 	from /usr/local/bundle/bin/jekyll:23:in `load'
     [exec] 	from /usr/local/bundle/bin/jekyll:23:in `<main>'
     [exec] Result: 1
[INFO] Executed tasks
[INFO]

**Comment by skabashnyuk** [comment]
CC @themr0c @rkratky

**Comment by ibuziuk** [comment]
@vparfonov are we still building the che-docs as part of the release? which CI is used for it?

**Comment by skabashnyuk** [comment]
https://repo1.maven.org/maven2/org/eclipse/che/docs/che-docs/7.7.0/
https://repo1.maven.org/maven2/org/eclipse/che/docs/che-docs/7.6.0/
docs war has a significant difference in size.

**Comment by skabashnyuk** [comment]
Might be related to https://github.com/eclipse/che-docs/pull/912

**Comment by skabashnyuk** [comment]
@themr0c @rkratky 
Is this commands to build che-docs war correct 
https://github.com/eclipse/che-docs/blob/master/pom.xml#L99
https://github.com/eclipse/che-docs/blob/master/pom.xml#L127-L142
?

**Comment by themr0c** [comment]
@skabashnyuk It doesn't look good indeed.

Why not run ```run.sh -war```?

**Comment by vparfonov** [comment]
> @vparfonov are we still building the che-docs as part of the release? which CI is used for it?

https://ci.centos.org/

**Comment by vparfonov** [comment]
default profile is docker https://github.com/eclipse/che-docs/blob/master/pom.xml#L81
