### ISSUE TITLE
Implement Python Django test

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#15735]
tracking issue for https://github.com/redhat-developer/rh-che/issues/1764

**Comment by dmytro-ndp** [comment]
@Tibor Dancs: this issue looks incomplete https://github.com/eclipse/che/issues/15735:
- it links to closed issue
- it's not clear what kind of test and it should implement
- there is not test scenario which should be implemented

**Comment by ScrewTSW** [comment]
the implementation has been finished. Sorry for not replying Dmytro. Closing.
