### ISSUE TITLE
CHE 7 - devfile - image credentials

### ISSUE THREAD

**Issue by mcapello** [eclipse-che/che#15739]
Hi,
I am trying che 7.7 and want to create a workspace from a devfile.
I am having problems when the cration try to pull de image from docker hub.
Where I supposed to set user / password to do this pull ?

Example:
components:
  - alias: dev
    type: dockerimage
    image: hub.docker.com/repository/docker/xxxxx
    mountSources: true

**Comment by tolusha** [comment]
@mcapello 
Could you provide the exact error you have?

**Comment by tolusha** [comment]
The credentials to the private docker registry can be set on `Administration` page

**Comment by mcapello** [comment]
Thanks.
I try to use docker hub to pull a runtime container in the devfile.yaml
Where shoul I put my dockerhub credentials ??

components:
  - alias: dev
    type: dockerimage
    image: caperiver/repo:tomcat_base
    mountSources: true 

Also I try creating a secret in the che namespace in k8s, but no luck.

The error is:
Error: Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "caperiver/repo:tomcat_base": rpc error: code = Unknown desc = failed to resolve image "docker.io/caperiver/repo:tomcat_base": no available registry endpoint: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed',

**Comment by tolusha** [comment]
![screencast-che openshift io-2020 01 18-15_28_18](https://user-images.githubusercontent.com/1640675/72664501-585ea080-3a07-11ea-97f6-b39314a73ebf.gif)

**Comment by mcapello** [comment]
Thanks,  setting docker.io  did the trick.
