### ISSUE TITLE
Not able to open workspace with direct link

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15733]
### Describe the bug
I was no able  to open workspace with a direct like this `https://che-che.apps-crc.testing/admin/gogo`
<img width="1134" alt="Знімок екрана  о 08 41 26" src="https://user-images.githubusercontent.com/1614429/72593472-56acb400-3905-11ea-8fa6-dbc1f8626a8a.png">
<img width="1677" alt="Знімок екрана  о 08 40 33" src="https://user-images.githubusercontent.com/1614429/72593477-590f0e00-3905-11ea-8ea0-6851f6898179.png">
<img width="1250" alt="Знімок екрана  о 08 39 38" src="https://user-images.githubusercontent.com/1614429/72593483-5e6c5880-3905-11ea-8ead-40ca54f11225.png">

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace.
2. Open a direct link in a separate tab of the browser.
3. The workspace is not loaded correctly.

### Expected behavior
Workspace loaded correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
This is an error that comes from https://github.com/eclipse/che/blob/79c6ec0703fb5c00458e2fa00b4df9f586c0c5a9/assembly/assembly-root-war/src/main/webapp/_app/IDE.html#L210

**Comment by skabashnyuk** [comment]
@sleshchenko do you have an idea how to fix it?

**Comment by akurinnoy** [comment]
@skabashnyuk it fails there because String doesn't have the `contains` method (was remove some time ago AFAIK). The best way is to use `indexOf()` which is supported by all browsers.

**Comment by skabashnyuk** [comment]
>it fails there because String doesn't have the contains method

![giphy](https://user-images.githubusercontent.com/1614429/73022114-39a64280-3e29-11ea-9987-340553582f34.gif)

**Comment by olexii4** [comment]
@skabashnyuk I am going to remove this old GWT IDE code. You should use a 'https://che-che.apps-crc.testing/workspace-loader/admin/gogo' link instead.

**Comment by sleshchenko** [comment]
I suppose we're able easily to configure tomcat to redirect `${namespace}/${workspaceName}` -> `workspace-loader/${namespace}/${workspaceName}`, but not sure if we need it. @skabashnyuk WDYT?

**Comment by skabashnyuk** [comment]
>I suppose we're able easily to configure tomcat to redirect ${namespace}/${workspaceName} -> workspace-loader/${namespace}/${workspaceName}, but not sure if we need it. @skabashnyuk

We could try. I assume that might be some edge cases. It's for sure will take more time then  https://github.com/eclipse/che/pull/16127. Thanks, guys for this pr.
