### ISSUE TITLE
Propose to terminate a task at closing it's tab

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15743]
### Is your enhancement related to a problem? Please describe.
We terminate a task at closing it's tab.
Maybe it makes sense to ask user about it.

### Describe the solution you'd like
We could display an notification to ask user about terminating a task at closing a terminal tab and provide the opportunity to save user's choice to preferences.

### Additional context
this is proposal from @sunix https://github.com/eclipse/che-theia/pull/594#issuecomment-575208550

**Comment by maxandersen** [comment]
suggest to mimick what vscode does and something like closing tab ask you, but there is also a "garbage" icon that just kills it. 

This let me be explicit to just terminate in one click and if I by accident click the X on tab i'm warned.
