### ISSUE TITLE
Apply design suggestion to Header on Get Started Page

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#15749]
### Is your enhancement related to a problem? Please describe.

**Header**
- [x] Move `subtitle`, `instructions text` and `items count` up so that it is under the title (see design mockup below) on a white background
![Screenshot_20200128_163310](https://user-images.githubusercontent.com/5887312/73272957-e3038480-41eb-11ea-84f6-aca7220d6569.png)

**Comment by beaumorley** [comment]
There should be a hover over the card. When the user clicks the card the workspace is created and opened. So there is no need for the button on the top right. The hover should let the user know that clicking will do something. This design is to help achieve the requirement that the samples are simple and start in several minutes. 

Here is a design requirements for this:
When hovering over a card, the card’s shadow shall turns from small to large. On click, the workspace shall be created and opened. Note: The visual treatment of the card on click shall not change (remove the blue border on click).
	
	Example of hover shadow:
![image](https://user-images.githubusercontent.com/52013984/72993122-d7b2f200-3dc2-11ea-89d9-f4d4d93a7f66.png)

**Comment by sleshchenko** [comment]
The work is done but not merged yet.
It's closed in the flavor of https://github.com/eclipse/che/issues/16241
