### ISSUE TITLE
Improve che:theia production command to correct repack theia dependencies

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#15748]
### Is your task related to a problem? Please describe.
After latest build failure (related issue: https://github.com/eclipse/che/issues/15695) there was provided temporary solution, that adds missing dependency to the theia generator [assembly-package.mst#L73](https://github.com/eclipse/che-theia/blob/master/generator/src/templates/assembly-package.mst#L73). As a temporary solution it works fine, but there is a need to review the `che:theia production` command ([production.ts](https://github.com/eclipse/che-theia/blob/master/generator/src/production.ts)) to be able to repack correct dependencies in case if upstream project provide more than one dependency that have two versions.

### Describe the solution you'd like
Filter dependencies and look for the one dependency with more than one version and took the latest one into che-theia image assembly.

### Describe alternatives you've considered
Not yet discussed.

### Additional context
None

**Comment by TheRealChssAddct** [comment]
Yarn as of version 1.21.1 no longer allows colons in symlink names.  Therefore che:theia should no longer be the name of the command.  It should probably be changed to che-theia.

(The problematic issue is yarn 1.21.1 will no longer validate the "bin" symlink with a colon in it (currently line is line 8 the bin https://github.com/eclipse/che-theia/blob/master/generator/package.json)
