### ISSUE TITLE
[Chectl] support exported kubeconfigs when installing

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#15741]
### Is your enhancement related to a problem? Please describe.

I'm currently trying to run Che on IBM Kubernetes Service (IKS). When you authenticate against the cluster, IKS gives you the following command to run:
```
export KUBECONFIG=/Users/johncollier/.bluemix/plugins/container-service/clusters/<some-cluster>/kube-config.yml
```

When that command is run, your current terminal session will then be configured against that cluster. 

An entry under `~/.kube/config` is **not** created however when you configure the cluster. 

When I go to run `chectl server:start --platform=k8s --installer=operator --domain=<domain>`, the command fails with the following error:
```
johns-mbp-3:~ johncollier$ chectl server:start --platform=k8s --installer=operator --domain=<domain>
  ✖ Verify Kubernetes API
    → Failed to connect to Kubernetes API. serviceaccounts is forbidden: User "s
…
    👀  Looking for an already existing Che instance
Eclipse Che logs will be available in '/var/folders/68/4ts5xvrx067bb614t74jpb9c0000gn/T/chectl-logs/1579277503234'
 ›   Error: Failed to connect to Kubernetes API. serviceaccounts is forbidden: 
 ›   User "system:anonymous" cannot list resource "serviceaccounts" in API 
 ›   group "" in the namespace "default"
```

This is because Che doesn't see the exported Kube config in `$KUBECONFIG` and is trying to install into a different cluster (whose context has long since expired).

### Describe the solution you'd like

It would be nice if Chectl supported scenarios where the kube config was exported under the `KUBECONFIG` environment variable. This would allow Chectl to work against Kubernetes platforms like IKS that only provide the user with a Kube config file to export in their terminal. It would also be nice, as it could also mean users wouldn't have to reconfigure their default Kubernetes context if they wanted to quickly install Che on another cluster.

### Describe alternatives you've considered
Manually creating the kube config entry in `~/.kube/config` works, but it's a hassle and the certificates for the config expire every 12 or so hours, so I have re-do that step whenever I reconfigure against the cluster.

Manually installing the Che operator from operatorhub works fine too.

**Comment by tolusha** [comment]
@johnmcollier 
While working on the issue I realized that underlying library takes into account `KUBECONFIG` environment variable. In the latest version of chectl I've just added logging the current context on chectl start.
I would be nice if you check if it works on your side now.
