### ISSUE TITLE
Doc Navigation does not show State of Navigation

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15759]
1. Got to the Che 7 documentation (https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/#) 
2. Expand the "Che quickstarts" section
3. Select "Running Che Locally"
4. Observe: the selected page gets loaded
5. Observe: the "Che quickstarts" section in the sidebar gets closed. There is no indication of where in the navigation the current page resides

IMO, this is a serious usability problem: first, you have to remember where in the navigation you were if you want to navigate to the next section, and second, if you have a direct link into the doc, you have idea where this section resides: you have to rummage around the doc to find out.

**Comment by l0rd** [comment]
cc @themr0c

**Comment by themr0c** [comment]
To add in the list of reasons why we should do some work to switch to Antora.

**Comment by rkratky** [comment]
This will be fixed by https://github.com/eclipse/che/issues/16286, which is WIP. Closing.
