### ISSUE TITLE
Theia hotkeys aren't handled when a WebView is in focus

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15763]
### Describe the bug

Theia hotkeys aren't handled when a WebView is in focus.
It may be related to the recent changes upstream https://github.com/eclipse-theia/theia/pull/6465

### Steps to reproduce

1. Click on WebView with Eclipse Che Welcome page.
2. Use F1, for example.

Google Chrome Help page is opened.

### Expected behavior

Theia hotkey has to be handled properly - Command Palette should be opened.

**Comment by RomanNikitenko** [comment]
Faced with the same issue.
My use case is: try to create a new terminal when ```Eclipse Che Welcome page``` is in focus.
Usually it's my first action when a workspace is started.

**Comment by azatsarynnyy** [comment]
The current status:
- The patch has been proposed and merged upstream https://github.com/eclipse-theia/theia/pull/7216
- It turned out that the provided patch causes the issue with input field https://github.com/eclipse-theia/theia/issues/7232
- The patch was reverted https://github.com/eclipse-theia/theia/pull/7233 to fix the input
- The upstream issue has been opened https://github.com/eclipse-theia/theia/issues/7235 to find a proper solution
- There was a proposal to fix it in Che Theia https://github.com/eclipse/che-theia/pull/664. But it doesn't look well as it done by patching the source file from upstream Theia

**Comment by azatsarynnyy** [comment]
fixed upstream
