### ISSUE TITLE
Theia Color theme switching works improperly

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15764]
### Describe the bug

After switching color theme Theia asks to save some changes.
Related upstream issue https://github.com/eclipse-theia/theia/issues/6786
Looks like it's appeared after the upstream changes https://github.com/eclipse-theia/theia/pull/6475

### Steps to reproduce
Switch color theme in Che Theia.

### Expected behavior

Color theme should be applied immediately without any additional questions.

### Screenshots

![theme](https://user-images.githubusercontent.com/1636395/72803782-889c7e00-3c57-11ea-9a26-b1fa728bee5a.gif)

**Comment by benoitf** [comment]
dup of https://github.com/eclipse-theia/theia/issues/6786

**Comment by azatsarynnyy** [comment]
Thanks @benoitf 
mentioned it in the description

**Comment by azatsarynnyy** [comment]
fixed upstream by https://github.com/eclipse-theia/theia/pull/7110
