### ISSUE TITLE
Task runs sometimes don't produce a notification with exit code after they finish running.

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#15769]
### Describe the bug
When you run a task in workspace e.g.: build, the tasks sometimes don't produce a notification.

This notification is not visible both as a Toast message, either as a notification in the Notification Centre

@musienko-maxim was speculating, that it could be an issue in events and I'm inclining this way as well.

### Che version
Current screenshot is from Che 7.7.1 installed by chectl on OCP 4.2 using operator
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Open a workspace of preference that has some tasks to execute which are terminating and return exit code
2. Run task
3. Wait for it to finish
4. Check notifications and clear them out
5. Repeat until the notification is not seen when expected

### Expected behavior
Notification about exit status code will be displayed every single time when a task ends and returns an exit code.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`) : `kubernetes v1.14.6+32dc4a0`
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot_20200121_162810](https://user-images.githubusercontent.com/16451875/72819880-4df21000-3c6e-11ea-977a-1edb689da9d9.png)

### Installation method
   - [x] chectl  : `chectl server:start -a operator -p openshift -n tdancs-che`
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) : unsure - devcluster OCP4.2 on OpenStack
   - [ ] other: please specify

**Comment by RomanNikitenko** [comment]
Looks like the same issue was reported today: https://github.com/eclipse/che/issues/15761
