### ISSUE TITLE
Workspace Loader stops with "Unauthorized" if the access token needs a refresh

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#15772]
We are using access tokens with quite a short lifetime currently (1min) and while starting workspaces I frequently do get:
`Error: Failed to get the workspace: "Unauthorized"`

This comes along with two error messages in the console:
- `GET https://webide7.dev.bosch-cloudia.com/api/workspace/cks2si@bosch.com/wksp-ibfd 401 (Unauthorized)` (from workspace-loader.ts:99)
- `Uncaught (in promise) DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.`  (from workspace-loader.ts:312)

I think this is a small defect in setAuthorizationHeader(..). 
- The problem is that, setAuthorizationHeader creates a Promise to perform "updateToken", but immediately resolve the promise (line 321). So it actually always returns the already resolved promise without waiting for keycloak.updateToken to complete.
- In the aftermath, the request get's carried out and if the token is expired returns a 401
- at some point later keycloak updateToken is done and tries to set the xhr.setRequestHeader, which fails since at that time the request is already done.

Setup:
-  Che 7.7.1
- Kubernetes on Azure
- Keycloak 

From workspace-loader.ts:
```ts
    async setAuthorizationHeader(xhr: XMLHttpRequest): Promise<XMLHttpRequest> {
        return new Promise((resolve, reject) => {
            if (this.keycloak && this.keycloak.token) {
                this.keycloak.updateToken(5).success(() => {
                    xhr.setRequestHeader('Authorization', 'Bearer ' + this.keycloak.token);
                    resolve(xhr);
                }).error(() => {
                    window.sessionStorage.setItem('oidcIdeRedirectUrl', location.href);
                    this.keycloak.login();
                    reject(new Error('Failed to refresh token'));
                });
            }

            resolve(xhr);  ///  <-------------- DON'T -------<
        });
```

**Comment by sleshchenko** [comment]
@ChristianSchenk711 Thanks for the detailed info provided. And sorry for a bit late fix https://github.com/eclipse/che/pull/16332
