### ISSUE TITLE
Footer is not displayed on Get Started page

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15776]
### Describe the bug
Footer is not displayed on Get Started page.
It's not relevant to every browser.
It's not displayed on Google Chrome (79.0.3945.88 Linux 64 Bit)
![Screenshot_20200121_170059](https://user-images.githubusercontent.com/5887312/72880137-f653b300-3d06-11ea-8414-e4c1b970b671.png)
But it's displayed well on Google Chrome (78 Linux 64 Bit) and Firefox
![Screenshot_20200121_175948](https://user-images.githubusercontent.com/5887312/72880166-04093880-3d07-11ea-858d-a92ca74f5cce.png)

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/pull/15784

**Comment by sleshchenko** [comment]
It's still reproducible on google-chrome-stable/stable 79.0.3945.130-1 amd64

**Comment by olexii4** [comment]
I am going to fix **Footer** with changing the implementation with angular-patternfly v.5.0.3

Needed CQs  were created:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21569
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21565
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21566

**Comment by olexii4** [comment]
We have the same problem with stacks.
![Screenshot from 2020-02-25 14-05-11](https://user-images.githubusercontent.com/6310786/75246348-41665780-57d8-11ea-974c-e8d4f4a1fe4e.png)

**Comment by olexii4** [comment]
fixed https://github.com/eclipse/che/pull/16163/files#diff-8a14d47103eb64b90950b89aaa182849L103
