### ISSUE TITLE
Python plugin doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15779]
[Che Python plugin](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-python/python/2019.5.18875/meta.yaml) doesn't work in [Python devfile](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/python/devfile.yaml#L14). 
The problem is that the [plugin .vsx](https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-python/python-2019.5.4.vsix) is broken, it doesn't contain `python-2019.5.4.vsix/extension/out` folder. 
Probably it was built in wrong way.
### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace from Python devfile
2. Open hello-world.py
3. Go to View --> Output --> Extension host (vscode-pythonrhm) log

### Screenshots
![screenshot-che openshift io-2020 01 (1)](https://user-images.githubusercontent.com/1271546/72885308-5569f580-3d10-11ea-91c1-e265080bd040.png)

**Comment by nickboldt** [comment]
We'll need to figure out what's missing in the build job [1] then trigger a new run [2].

[1] https://github.com/redhat-developer/codeready-workspaces/blob/master/dependencies/che-plugin-registry/Jenkinsfile-single
[2] https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/vscode-extensions-packaging/141/parameters/

cc: @mkuznyetsov @tsmaeder

**Comment by mkuznyetsov** [comment]
@svor please try the newly built extension: 
https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-python/python-2019.5.18875.vsix

it if works, I'll update the plugin registry with it

**Comment by svor** [comment]
@mkuznyetsov tested new extension on che.openshift.io and it works good. Pls update plugin registries

**Comment by nickboldt** [comment]
registries updated for che and crw.
