### ISSUE TITLE
Add Custom Env Variable 

### ISSUE THREAD

**Issue by mstavares** [eclipse-che/che#15785]
Hi,

I'm sorry for opening an issue like this, but I'm completely stuck right now. I would like to add a custom env variable to my own Eclipse CHE as you do with CHE_PORT. Lets assume that my variable is called MY_VAR and I would like to set it as default the false value (as you do with CHE_HOST=8080).

sudo docker run -it -e MY_VAR=true (...)

I don't know if I'm on the right way, but I added this line on che.properties file:

my.variable=${MY_VAR)

Now, I'm expecting to fetch the variable value through:

  @Inject
  public WorkspaceService(
      **@Named("my.var") boolean myVar,**
      @Named("che.api") String apiEndpoint,

However, I don't know how to set a default value to this env variable and the value that I'm collecting on myVar is null.

I would appreciate if you could give me some help. Thank you.

**Comment by benoitf** [comment]
Hello @mstavares could you specify the version of che that you're using ?

I assume it's che 6 with docker support.

there is an automated binding for properties starting with `che.` prefix

like @named('che.my.var') you can use CHE_MY_VAR as environment variable

**Comment by mstavares** [comment]
Oh, sorry, yes I'm supporting 6.14.
Thank you, I will test it.

**Comment by mstavares** [comment]
Hi,

Seems working but, how do I set a default value? for instance, for the CHE_PORT by default is already 8080, I don't need to set it.

Caused by: org.eclipse.che.inject.ConfigurationException: Property CHE_MY_VAR is not found as system property or environment variable.

If I set it to true or false its working, however, if I ommit the -e CHE_MY_VAR=... I got that error.

Thanks for your help.

**Comment by benoitf** [comment]
in che, usually default values are set in `che.properties` file

like https://github.com/eclipse/che/blob/d13f9d3ecbf59a1129ee319d70dc5aa234a89a36/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L526

**Comment by mstavares** [comment]
Yes, but I'm using an env var like this

# API service. Browsers initiate REST communications to Che server with this URL
che.api=http://${CHE_HOST}:${CHE_PORT}/api

in my case:

che.my.var=${CHE_MY_VAR}

I need to find a way to set this env variable with a default value

Thank you

**Comment by skabashnyuk** [comment]
@mstavares you question is unclear, could you please reformulate.
