### ISSUE TITLE
Multiple endpoint URLs?

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#15781]
Is it possible to have multiple endpoint URL for the same port somehow?

For some projects we need to be able to access subdomains to trigger a certain version of a site to load, for example, instead of just:

`server2v9s4dxq-web-80.che.cluster.com`

We'd like to have the option to visit:

`company1.server2v9s4dxq-web-80.che.cluster.com`
`company2.server2v9s4dxq-web-80.che.cluster.com`

or if that causes TLS problems, a hyphen would work: 

`company1-server2v9s4dxq-web-80.che.cluster.com`

**Comment by skabashnyuk** [comment]
@davidwindell  yes we are working on this for CheEditor in https://github.com/eclipse/che/issues/15410

**Comment by davidwindell** [comment]
@skabashnyuk thanks for linking that one in - I hadn't seen it. Do you think a wildcard subdomain might be an option at some point?

**Comment by skabashnyuk** [comment]
can you please rephrase your last question?

**Comment by davidwindell** [comment]
@skabashnyuk sorry, I mean would it be possible to allow connections to:

`*.endpointurl`

We often build web apps where each user has their own subdomain prefix.

**Comment by davidwindell** [comment]
Mind you, that does raise problems with TLS I think, because we'd have to have a sub sub-domain cert for every workspace. 

Feel free to close this issue if the issue covers the rest. Thanks!

**Comment by skabashnyuk** [comment]
@davidwindell I'm sorry I still not fully understand your request.

**Comment by davidwindell** [comment]
@skabashnyuk so for example, we have a workspace that has a web server running on port 80. Che will generate an endpoint/ingress like:

`server2v9s4dxq-web-80.che.cluster.com`

In our case, the web server running on port 80 is hosting more than one website (and uses a regex match on the URL to see which site to display), so we need some way to be able to reach website 2, 3, 4 etc by a different URL but connect to the same workspace.

**Comment by davidwindell** [comment]
But how would we use different routes for our own workspace URLs?

**Comment by skabashnyuk** [comment]
>But how would we use different routes for our own workspace URLs?

@davidwindell I'm sorry. I didn't understand your question.
