### ISSUE TITLE
CDN support for Che-theia completely disabled in the last Che releases

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15791]
### Describe the bug

When the Che-theia editor is loaded in the browser after a Che workspace is started, it doesn't try to retrieve biggest resource files from the CDN before retreving them from the Theia express server.

This can greatly slow down the loading of the workspace on the client-side if the client is far (in terms of network distance or latency) from the location where the Che workspace is effectively running.    

### Che version

 - [x] latest (7.7.0, 7.7.1)
 - [x] nightly
 - [x] other: possibly 7.6.0 as well

### Steps to reproduce

- Login to `che.openshift.io` in Chrome,
- Open the `Chrome Developer Tools`,
- In the developer tools, go to the `Network` task, and enable the `Preserve Log` check box
- Start a workspace
- When the workspace is started, look into the Network tab and see that no access to any URL starting with `https://static.developers.redhat.com/che/theia_artifacts/`

### Expected behavior

For a number of big resources such as JS files, images, etc ..., Che-theia should first try to load them from CDN locations, before fetching them from the workspace Theia Express server.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by benoitf** [comment]
maybe linked to the move from codenvy ci to centos ci
@vparfonov  ?

**Comment by metlos** [comment]
maybe support for airgap mode plays a role here?

**Comment by davidfestal** [comment]
Seems not. The problem is even more than that. No CDN-related logic is activated at all, which is typically a build problem.

**Comment by nickboldt** [comment]
Resolved back in Jan/Feb.
