### ISSUE TITLE
Implement OLM operator tests on PRs 

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#15803]
### Is your enhancement related to a problem? Please describe.

Currently there is no way to test OLM files and especially OLM operator update without merging the changes to master.

### Describe the solution you'd like

After implementing issue https://github.com/eclipse/che/issues/15802, we should setup scripts to test the OLM changes in OLM (and OLM updates) in a way that doesn't change the preview Quay.io applications.

**Comment by flacatus** [comment]
After implemention of https://github.com/eclipse/che/issues/15802 the next step is to create a job on ci.centos.org for olm PR check.

**Comment by flacatus** [comment]
Pending to setup to run the scripts in CI.

**Comment by flacatus** [comment]
Done! Olm tests files run now on every Pr.
