### ISSUE TITLE
Please have Che server log (at INFO level) workspace startup times

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#15805]
### Is your enhancement related to a problem? Please describe.
Workspace startup times are of interest to several kinds of stakeholders:
- Users can study WS startup metrics, perhaps leading to more efficient stack choices
- Administrators can compare WS startup times across clusters, perhaps leading to better understanding of environmental factors
- Che stakeholders can use the information to guard against performance regressions in future releases

### Describe the solution you'd like
Log entries in the Che server log for every workspace startup.  The log entry should specify the name of the workspace, the time it took to start and the stack used (if possible).

### Describe alternatives you've considered
Benchmarking workspace startup times with observed changes in the browser, but this is inefficient, time-consuming and frustrating.

### Additional context
Thank you for considering this important use case.  Please embellish this suggestion with improvements I may not have considered.

**Comment by nickboldt** [comment]
I've guessed at the areas that might be impacted by this. 
* chectl downloads operator image
* operator downloads Che server, postgres, ubi8-minimal (PVC), keycloak/RHSSO, registries
* then once a workspace is started, theia, machine-exec, jwtproxy, and lang server runtime/sidecar images are loaded

So I suspect this logging will affect a number of areas. I'd love to see the load times in chectl (for everything up to the workspaces) and the rest logged in one central place for ease-of-debugging and ease-of-reporting.

**Comment by tsmaeder** [comment]
@RickJWagner the user does not have access to Che server logs. How would she see the numbers?
As for administrators, I believe we're already collection metrics about server startup times. @ibuziuk can you chime in on this?

**Comment by RickJWagner** [comment]
You're right, @tsmaeder.  A plain user (without access to internals) would not see the logs.  But an admin could use the information to react to user inquiries.

**Comment by nickboldt** [comment]
Removed some area labels as this is restricted to workspace startup times / logs.

**Comment by tsmaeder** [comment]
@ibuziuk ?

**Comment by skabashnyuk** [comment]
>Users can study WS startup metrics, perhaps leading to more efficient stack choices
Administrators can compare WS startup times across clusters, perhaps leading to better understanding of environmental factors
Che stakeholders can use the information to guard against performance regressions in future releases

@RickJWagner  A big part of what you want is already there 
```
2020-01-25 19:44:22,934[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 469]   - Starting workspace 'admin/golang-pt2xs' with id 'workspace3dpz64y5em37wjiw' by user 'admin'
2020-01-25 19:45:46,481[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 878]   - Workspace 'admin:golang-pt2xs' with id 'workspace3dpz64y5em37wjiw' started by user 'admin'
```
I have to admit that analyzing che server log is not the ideal UX that we want to provide for che admins/stakeholders. Can we think in a direction on improving our monitoring stack/Grafana dashboards which, in my opinion, provide better visibility and understanding of what is going on.

**Comment by RickJWagner** [comment]
Thanks for that tip, @skabashnyuk.  You are right, use of the Che server log is useful for this purpose.  I have an observation, though.  
Often times, the workspace will start (and be logged in the Che server log as described) but the IDE will have timed out and be disconnected.  Looking at the dashboard, the left-side nav bar will have a green dot for the workspace, hinting that the workspace is started and healthy, while the center pane shows a message telling the user to hit F5 to reload.  
The user must 'reconnect' the IDE to the workspace (either by using F5 or clicking the green dot, or maybe through the nav bar 'workspaces' section).  Only after reconnecting the IDE to the running workspace does it become useful for the user, and this can be a few minutes even after the Che server reports "Workspace xyz started by user.."
This is the metric I seek to gather-- from request of workspace until the IDE actually shows the workspace (and is useful).  It is a more realistic picture of what the user thinks.  
Is there some way to accomplish this?

**Comment by sleshchenko** [comment]
> Looking at the dashboard, the left-side nav bar will have a green dot for the workspace, hinting that the workspace is started and healthy, while the center pane shows a message telling the user to hit F5 to reload.
The user must 'reconnect' the IDE to the workspace (either by using F5 or clicking the green dot, or maybe through the nav bar 'workspaces' section). 

@RickJWagner FYI It was a bug fixed by https://github.com/eclipse/che/pull/16332, so now once a workspace is started - an user should get Theia opened

**Comment by RickJWagner** [comment]
Super.  Thank you, Sergii.

**Comment by sleshchenko** [comment]
`workspace-loader` just displays logs published by `wsmaster` as runtime logs, so adding wsmaster area as well.

**Comment by skabashnyuk** [comment]
Closing. https://github.com/eclipse/che/issues/15805#issuecomment-578437319 information already exists. In case you need something different please reopen and change the scope/goal of this task .
