### ISSUE TITLE
Remove redundunt self-signed-cert secret

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#15810]
### Is your task related to a problem? Please describe.
For now, in case of using self-signed certificate user [must provide](https://github.com/che-incubator/chectl/blame/c6ea8362e4a02f0be2af14f81a88e9bbefee88fe/README.md#L290-L292) precreated one.
But internally we use `che-tls` secret for securing routes and also use `self-signed-cert` for propagating CA certificate to Che components to trust the self-signed certificate. This is redundant and we can use only one secret `che-tls` which must have `ca.crt` field in case of self-signed certificate.

### Describe the solution you'd like
Remove `self-signed-cert` secret and use `che-tls` instead. In case of manually generated by a user  self-signed certificate and putting precreated secret, we should require `ca.crt` field in it.

### Additional context
Cert Manager puts `ca.crt` in its secrets automatically.

**Comment by tolusha** [comment]
@mmorhun 
How is important this task is for TLS by default?

**Comment by mmorhun** [comment]
@tolusha I found this problem while I was working on https://github.com/eclipse/che/issues/15313. This issue doesn't block TLS by default but brings need for additional effort in implementation. Also may ran into it later, so I would like to resolve it to have code clean and clear to understand.

**Comment by mmorhun** [comment]
I think, I will handle this issue now, because the cost for workaround roughly equal to the cost of the fix...

**Comment by mmorhun** [comment]
Done
