### ISSUE TITLE
Automate testing `che-operator` updates

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15814]
### Is your task related to a problem? Please describe.
This PR [1] introduces an automation of releasing of `che-operator` and also describes manual steps to test updates. (see `RELEASE.md`)

### Describe the solution you'd like
Every release PR is checked if `che-operator` update tests are executed.

### Additional context

[1] https://github.com/eclipse/che-operator/pull/152

**Comment by rhopp** [comment]
Testing on minishift & minikube is done (automated). Testing on OCP 4.x will be implemented in followup issue: https://github.com/eclipse/che/issues/17073
