### ISSUE TITLE
[helm] Improve ConfigMap generation templates.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#15824]
### Is your enhancement related to a problem? Please describe.

The Current template for ConfigMap in Helm is not fully updated to the current `che.properties`.
And the value set of `che.properties` will be changed and won't be fixed.

### Describe the solution you'd like

Providing helper templates to generate the name of the environment variable from the key of `values.yaml`.

### Describe alternatives you've considered

Freezing the key set of `che.properties`. (I know this is a bad idea.)

### Additional context

I've already written the template. I'll send a draft PR soon.

**Comment by monaka** [comment]
I sent my pull request.
The pull request itself will be harmless for current users that installed Che with Helm.
But it will be a hard configuration breakage for them if we decided completely migrate to the new mechanism.
So it might be better to provide migration scripts or something.

**Comment by ibuziuk** [comment]
@tolusha please take a look at issue / PR and provide some input

**Comment by tolusha** [comment]
@ibuziuk 
I will take it in the next sprint to review.
