### ISSUE TITLE
Refactor upstream tests to allow easier devfile implementations

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#15829]
### Is your task related to a problem? Please describe.
Currently implementing devfiles is a little cumbersome task to do.
In this PR I plan to extend the `testLibrary` classes with new methods and fix existing bugs in the existing classes.

### Describe the solution you'd like
* fixing methods that don't work or are not properly implemented
* extending `testLibrary` classes
* use the new abstraction method in existing tests

**Comment by rhopp** [comment]
Done.
