### ISSUE TITLE
[che-docs] Automatically generate documentation with the list of supported plugins after each Che release

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15838]
### Is your task related to a problem? Please describe.
The issue is inspired by https://github.com/eclipse/che-docs/pull/1041
Currently, it is not straight forward to get information about supported plugins, languages, debuggers supported in Che. This info is located in the che-plugin-registry - https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins and currently docs do not contain any information about the supported plugins.

### Describe the solution you'd like / User Stories 
- As a user, I want to have **up-to-date** information about the supported plugins 
- As a developer, I want to have the adoc with supported plugins automatically generated 

### Describe alternatives you've considered
Manual creation of the doc which is error-prone and get obsolete really fast 

### Additional context
Potential implementation details
- adoc is generated from the https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins
- meta.yaml for each plugin has a relevant `category` e.g. Language / Debugger

**Comment by tsmaeder** [comment]
Let's not call it "supported" because it implies that we will take care of these plugins. What about stuff that is contributed by third parties?

**Comment by ibuziuk** [comment]
@tsmaeder how would you call it in this case ? (e.g available or smth. else)?

**Comment by ericwill** [comment]
One thing we can do is run the automated report as a build step. It outputs an MD file with the tabulated list of all plugins and their versions, at that time. We can put it this MD file somewhere as part of the release. Then when someone looks at `x` version of the registry, they can easily check this list.

For master, I'd say we can include a link to the daily report in the README.

**Comment by ibuziuk** [comment]
@ericwill the idea was to have smth similar to https://github.com/eclipse/che-docs/pull/1041 - list of the plugins is available in the official docs https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/

**Comment by ericwill** [comment]
We can do both!

**Comment by themr0c** [comment]
To have something future proof, it would be really awesome if we could have a documentation built by antora, like what exists for devfile. See https://github.com/devfile/docs

**Comment by ericwill** [comment]
We have an automated report that lists all plugins in the registry, as well as what version is in the registry and what version is available upstream. The report is updated every time a change is merged.

https://eclipse.github.io/che-plugin-registry/

**Comment by themr0c** [comment]
What would be good for integration into the documentation would be an *AsciiDoc* or *CSV* file available to download for each *released* version. Would it be possible to generate such a document @ericwill?
