### ISSUE TITLE
Disable plugin-vscode-resolver in Theia

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15844]
### Describe the bug
Eclipse Theia includes [functionality](https://github.com/eclipse-theia/theia/blob/1ca3ec37c079a6b316278cf292609653e57b8151/packages/plugin-ext-vscode/src/node/plugin-vscode-resolver.ts#L57) for automatically downloading plugin dependencies, defined in `package.json`, at startup. This process should be disabled in che-theia, as it causes issues like https://github.com/eclipse/che/issues/15794.

### Che version
 - [x] nightly

### Additional information
We are currently relying on this functionality for a number of plugins in the registry; this issue depends on at least https://github.com/eclipse/che-plugin-registry/pull/355 being merged, but preferably also includes something along the lines of https://github.com/eclipse/che/issues/15376

**Comment by ibuziuk** [comment]
@azatsarynnyy please, take a look

**Comment by benoitf** [comment]
It's handled by https://github.com/eclipse/che-theia/pull/645
