### ISSUE TITLE
Align styles in Plugins view

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15840]
### Describe the bug

After updates in Theia upstream, elements in Che Plugins view become unreadable or got inappropriate styles.
We need to fix styles of those elements for both dark and white themes.

![Screenshot from 2020-01-27 15-51-09](https://user-images.githubusercontent.com/1655894/73180103-47a3de00-411d-11ea-9316-e40675d8d23b.png)

### Steps to reproduce
1. Build Che-Theia from sources
2. Launch and open Plugins view

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by azatsarynnyy** [comment]
It's fixed by https://github.com/eclipse-theia/theia/pull/6475 and https://github.com/eclipse/che-theia/pull/656
The styles now are adaptable to any Theme
![themes](https://user-images.githubusercontent.com/1636395/76290253-8d72cb00-62b3-11ea-82ac-1eff3d10c604.gif)
