### ISSUE TITLE
Build latest php intelephense 1.0.14 vsix and publish to dl.jb.o

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15845]
Build the following 3rd party plugins for use in CRW (and also in Che 7.8):

    - https://github.com/che-incubator/vscode-intelephense/releases/download/v1.0.14/bmewburn.vscode-intelephense-client-1.0.14.vsix

Once built, need PRs for updating Che 7.x and CRW 2.1 registries. 

I've got a new idea for how to streamline PR generation. See https://issues.redhat.com/browse/CRW-598?focusedCommentId=13957722&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13957722

**Comment by ibuziuk** [comment]
@nickboldt should this be moved to 7.9.0 ?

**Comment by nickboldt** [comment]
yes, obviously, since 7.8 is done :) when in doubt, just move it

**Comment by nickboldt** [comment]
PRs:
https://github.com/redhat-developer/codeready-workspaces/pull/236#event-3047688572
https://github.com/eclipse/che-plugin-registry/pull/382

Merged and done.

@mkuznyetsov please close your issues when they're complete.
