### ISSUE TITLE
Update the kube tools version referenced in camelk meta.yaml

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15846]
There's a v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.9/meta.yaml

But the latest [v3/plugins/redhat/vscode-camelk/0.0.11/meta.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/vscode-camelk/0.0.11/meta.yaml#L20) contains the older 1.0.4.

Should that be updated to 1.0.9? Can we just change it, or do we need a 0.0.11-9 re-release, since these are in theory static once added? Should the newer one deprecate the older one?

And do we need a README in the k8s tools folder so we are reminded to update camelk at the same time when we do a new k8s release?

@apupier @ericwill

**Comment by apupier** [comment]
> Should that be updated to 1.0.9?

it is possible 

> Can we just change it, or do we need a 0.0.11-9 re-release, since these are in theory static once added?

cannot just change it.
A new image needs to be provided as https://github.com/che-dockerfiles/che-sidecar-camelk/blob/01afea610fc9fe460b37bfbc7424c9feae36246f/Dockerfile#L10 is relying on 1.0.4

> Should the newer one deprecate the older one?

I would say yes.

**Comment by apupier** [comment]
> And do we need a README in the k8s tools folder so we are reminded to update camelk at the same time when we do a new k8s release?

good idea

**Comment by ericwill** [comment]
> > And do we need a README in the k8s tools folder so we are reminded to update camelk at the same time when we do a new k8s release?
> 
> good idea. But maybe we should wait for automated test for that?

Yes -- there are ongoing discussions about plugin dependencies, so it might be beneficial to wait until that's resolved.

One thing to make a note of (and I don't know that this is an issue), but the 1.0.9 version of Kubernetes tools uses helm 3, whereas 1.0.4 used helm 2. IIRC there are some API differences between the two so it's worth checking to make sure nothing is broken.

**Comment by ericwill** [comment]
This ticket is no longer relevant as we have 0.0.15 with K8s tooling 1.2.0.
