### ISSUE TITLE
Build in ASP .NET stack can not be run

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15849]
### Describe the bug
When a user creates a default workspace with ASP .NET Core Web Application, the project can not be build because of ` Disk quota exceeded`. It seems that this is reproducible only with Ephemeral storage.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: please specify **7.7.1b**

### Steps to reproduce
1. Login to che.openshift.io
2. Go to Worksapce -> Add Workspace
3. Choose ASP .NET Core Web Application stack
4. Create workspace without doing any changes
5. Run task `install Cake`
6. Run task `build`

### Expected behavior
The project should be build.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify) **https://che.openshift.io**

### Screenshots

![Screenshot from 2020-01-28 12-59-52](https://user-images.githubusercontent.com/29278800/73262340-35ce4380-41ce-11ea-934c-d45522bc93ad.png)

**Comment by l0rd** [comment]
@Katka92 that looks like a known issue on openshift.io: disk quota is not guarantee when using ephemeral storage and the workspace becomes quickly unusable. I am closing this issue as duplicated of https://github.com/eclipse/che/issues/15729.  Please reopen if you don't think it's a duplicate.

cc @ibuziuk

**Comment by ScrewTSW** [comment]
Still present in 7.21.2

**Comment by ibuziuk** [comment]
@ScrewTSW are you going to reopen this one?

**Comment by ScrewTSW** [comment]
@ibuziuk I think we can just track it as https://github.com/eclipse/che/issues/15729 as it indeed seems to be related.
