### ISSUE TITLE
Refactor `Ide.waitWorkspaceAndIde` method removing unused arguments

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#15841]
### Is your enhancement related to a problem? Please describe.
It is not a problem, but it's cleaning up of code that influences all the tests that use this method

### Describe the solution you'd like
In `pageobjects/ide/Ide.ts` method `waitWorkspaceAndIde` still contains two arguments which have been previously used for creating a locator for workspace status indentificator in the left panel of Che

![Screenshot_20200127_170524](https://user-images.githubusercontent.com/16451875/73191130-4d9ebc80-4127-11ea-96e0-c8f1e48fa819.png)

The method was removed, but the arguments it used remained behind.

I would like to go through the classes and tests and remove those unused variables.

**Comment by ibuziuk** [comment]
@ScrewTSW assigning to you, please reassign if someone else from QA is expected to work on this issue

**Comment by Ohrimenko1988** [comment]
According to the history 
https://github.com/eclipse/che/blob/master/tests/e2e/pageobjects/ide/PreviewWidget.ts#L44-L59
looks like that method logic has been changed and variables became unnecessary but were not deleted. If you don't mind it would be great in the frame of this issue add to the tslint configuration a rule about unused arguments.
 Here is an explanation with example: <https://palantir.github.io/tslint/rules/no-unused-variable/>

**Comment by rhopp** [comment]
@Ohrimenko1988 Good idea ;-) Definitely nice linter rule ;-)

**Comment by Katka92** [comment]
The code change has been merged, but the linter rule is still not in place.
https://github.com/eclipse/che/pull/16922
