### ISSUE TITLE
[helm] Add options for un-deploying Postgres and Keycloak

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#15848]
### Is your enhancement related to a problem? Please describe.

Some Kuberenetes specialists may have their Postgres and/or Keycloak instance already.
And some may want to use a managed Postgres provided by cloud vendors.

### Describe the solution you'd like

Adds some switches like `postgres.enable: true` to `values.yaml`.

### Describe alternatives you've considered

None.

### Additional context

I'm creating some patches for fixing this and will raise the pull request soon.

**Comment by l0rd** [comment]
Thanks @monaka that's useful
