### ISSUE TITLE
Add Temporary Storage toggle button on Get Started page

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15855]
### Is your task related to a problem? Please describe.
Add Temporary Storage toggle button on Get Started page:
![image](https://user-images.githubusercontent.com/52013984/73021514-bdded280-3df5-11ea-9740-7e4dcf93c4e3.png)

**Comment by ibuziuk** [comment]
@sleshchenko thank you for following up on that. Could we expect a fix in 7.9.0 ?

**Comment by sleshchenko** [comment]
@ibuziuk The proposed design in the issue description depends on the redesigned header of Get Started Page. And it depends on the new library we're introducing on Dashboard side.

So, don't expect the shown picture to be implemented in 7.9.0 BUT if you think this part is quite critical for updating HostedChe to 7.9.0 then @akurinnoy can add that toggle on the existing design.

**Comment by ibuziuk** [comment]
> BUT if you think this part is quite critical for updating HostedChe to 7.9.0 then @akurinnoy can add that toggle on the existing design.

@sleshchenko yeah, getting-started is a pretty important flow IMO that is promoted, so it would great to get a hot-fix in 7.9.0
