### ISSUE TITLE
Task prepare database fails on Java with MySQL

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15852]
### Describe the bug

The command `prepare database` does not work in a `Java with Spring Boot and MySQL` workspace. There is an error in terminal: `ERROR 1046 (3D000) at line 1: No database selected`.

### Che version

**7.7.1b**

### Steps to reproduce

1. Log in to che.openshift.io
2. Go to Workspaces -> Add Workspace
3. Select Java with Spring Boot and MySQL stack
4. Run the workspace with the default setting
5. Run task `prepare database`

### Expected behavior

The task should end successfully.

### Runtime

**https://che.openshift.io**

### Screenshots
![Screenshot from 2020-01-28 14-35-51](https://user-images.githubusercontent.com/29278800/73268599-8009f180-41db-11ea-8a7f-e8319670b90e.png)

**Comment by tsmaeder** [comment]
Sounds like someone in the example (not under our control) broke the command. We should never rely on the master branch for examples.
