### ISSUE TITLE
Tasks fails for NodeJS Angular

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15853]
### Describe the bug

Task `yarn install` for NodeJS Angular workspace fails so no other task can be executed. The task fails with `Could not write file "/projects/angular-realworld-example-app/yarn-error.log`.

### Che version

**7.7.1b**

### Steps to reproduce

1. Log in to che.openshift.io
2. Go to Workspaces -> Add Worksapce
3. Create NodeJS Angular Web Application
4. Run the workspace with default settings
5. Run task `yarn install`

### Expected behavior
The command should install all required dependencies.

### Runtime

**https://che.openshift.io**

### Screenshots
![Screenshot from 2020-01-28 14-41-28](https://user-images.githubusercontent.com/29278800/73269372-fce99b00-41dc-11ea-86a9-74f64e49b0d5.png)

**Comment by tsmaeder** [comment]
Is this with ephemeral=false? I know we have issues with yarn and git with persistent volumes on openshift.io.

**Comment by JPinkney** [comment]
Just tried this out on an ephemeral workspace and it failed. After investigating this a little more I wonder if its a disk quota issue on che.openshift.io.

When I tried starting an ephemeral workspace and running `yarn install`, after the `yarn install` failure occurred any attempt to create a new file through the terminal fails with `Disk quota exceeded`:
```
bash-4.4 /projects/angular-realworld-example-app $ touch test.txt
touch: cannot touch 'test.txt': Disk quota exceeded
``` 

Out of curiosity I also tried getting the size of the folder:
```
bash-4.4 /projects/angular-realworld-example-app $ du -sh /projects/angular-realworld-example-app
407M    /projects/angular-realworld-example-app
```
but that folder size does not seem unreasonable.

Furthermore, I tried cloning the project on my machine locally and `yarn install` worked successfully. `yarn install` worked successfully on local che as well.

**Comment by Katka92** [comment]
@tsmaeder Hi, the description in the issue is for ephemeral=true. I tried today with ephemeral=false and I got a different error [1]. 

[1]
![Screenshot from 2020-01-30 18-55-45](https://user-images.githubusercontent.com/29278800/73476322-4b8c6600-4392-11ea-865b-b47eae6f9172.png)

**Comment by tsmaeder** [comment]
@Katka92 yes, we know that persistent workspaces are broken for many dev tools (git, yarn, etc.). @JPinkney can you reproduce this on a local install of Che?

**Comment by JPinkney** [comment]
@tsmaeder On local che (7.9.0-snapshot) running on minikube everything is working as expected and `yarn install` completes successfully

**Comment by JPinkney** [comment]
@Katka92 Do you mind trying again? I'm not sure if something changed on che.openshift.io recently but when I tried `yarn install` today everything is now working

**Comment by Katka92** [comment]
Hi @JPinkney, thank you for reminding me of this issue. I've tried on che.openshift.io and it works. I see that this issue was reported for 7.7.1b and currently we have 7.8.0 on che.openshift.io. I'll close this issue and reopen it if needed. Thanks all for collaboration
