### ISSUE TITLE
Add Vale vscode plugin to the plugin registry

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15856]
### Is your enhancement related to a problem? Please describe.
To support the case of building Che docs in a Che workspaces, it would be very helpful to have the [Vale vscode plugin](https://github.com/testthedocs/vscode-vale) available in the plugin registry.

**Comment by nickboldt** [comment]
@mkuznyetsov another 3rd party candidate for building https://github.com/testthedocs/vscode-vale/releases/download/0.9.0/vale-0.9.0.vsix (but not needed in CRW yet, so only if you need another test case for your user doc)

**Comment by ericwill** [comment]
I think this is a good candidate for our next sprint.

**Comment by ericwill** [comment]
@themr0c do you have any specific configuration preferences for Vale? Should I add the config files from https://github.com/eclipse/che-docs/pull/1057 into the Vale config in the sidecar container?

**Comment by amisevsk** [comment]
Fixed by https://github.com/eclipse/che-plugin-registry/pull/375

**Comment by ericwill** [comment]
I think this one can be closed now.

**Comment by themr0c** [comment]
@ericwill I believe the config for vale should always be defined by the project you are checking.
