### ISSUE TITLE
Task `install dependencies` failing in PHP Symfony

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15854]
### Describe the bug

The task `Install dependencies` is failing in PHP Symfony workspace. The error is:
```
 Fatal Error: composer.lock was created for PHP version 7.2.9 or higher but the current PHP version is 7.1.29.
```

### Che version

**7.7.1b**

### Steps to reproduce

1. Log in to che.openshift.io
2. Go to Workspace -> Add Workspace
3. Select PHP Symfony stack
4. Run workspace with the default settings
5. Run task `Install dependencies`

### Expected behavior

The dependencies should be installed.

### Runtime

https://che.openshift.io

### Screenshots
![Screenshot from 2020-01-28 14-55-13](https://user-images.githubusercontent.com/29278800/73270029-38389980-41de-11ea-947a-a49781059f72.png)

**Comment by tsmaeder** [comment]
I guess this is a case where we use "master" of the example and the prereqs no longer fit our stack.

**Comment by tsmaeder** [comment]
The quick fix is to find an older commit where the build still works. We ran into problems updating the PHP tooling in the past.

**Comment by tsmaeder** [comment]
The quick fix is to find an older commit where the build still works. We ran into problems updating the PHP tooling in the past.

**Comment by JPinkney** [comment]
From my investigations pinning it to the last commit before the project requires a newer version of PHP doesn't work because symphony will report security errors and refuses to build?/finish correctly.

There is a [PR on che-dockerfiles open](https://github.com/eclipse/che-dockerfiles/pull/252) to update to PHP 7.4 but the user still has to sign the eclipse contributor agreement.

I've built the image from that PR and tried it out and was able to successfully get `install dependencies` working

**Comment by JPinkney** [comment]
We've merged the PHP 7.4 update: https://github.com/eclipse/che-dockerfiles/pull/253 but I can't find who's responsible for that repo so that we can get it released

**Comment by ericwill** [comment]
> We've merged the PHP 7.4 update: [eclipse/che-dockerfiles#253](https://github.com/eclipse/che-dockerfiles/pull/253) but I can't find who's responsible for that repo so that we can get it released

It seems that repo is no longer used. The [base image for the PHP devfile](https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/base_images#L10) needs to be updated. Ideally it should use the [upstream](https://hub.docker.com/_/php) image as a base.

**Comment by JPinkney** [comment]
IIRC @amisevsk said we aren't using the upstream php image because there was some incompatibilities or something like that. Otherwise it would have been updated a long time ago

**Comment by ericwill** [comment]
Okay, I'll investigate.

**Comment by ericwill** [comment]
Closing this, the PHP devfile uses a different base image now which has the updated version of PHP 7.
