### ISSUE TITLE
When I set up Cluster Autoscaler on Amazon EKS, the workspace does not wait for node to be ready.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15864]
## Summary
Error when starting workspace:
```
Starting Init Plugin Broker
Cleaning /plugins dir
Unified Che Plugin Broker
List of plugins and editors to install
- popcornsar/kea-edu-cpp-ap/latest - C/C++ intelliSense, debugging and code browsing
Starting VS Code and Theia plugins processing
All plugins have been successfully processed
Starting Che plugins and editor processing
pod triggered scale-up: [{eks-7ab7896f-88d7-604f-f20a-fe078e84fe2d 1->2 (max: 30)}]
0/2 nodes are available: 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedScheduling', '0/2 nodes are available: 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.', 'workspace6h7nokjytqlbkqo4.che-workspace-pod-6cff6fb556-4zwgb'"
```

When I set up Cluster Autoscaler on Amazon EKS, the workspace pod stops without waiting for the node to finish scaling up.
I want the workspace to be created after waiting for the node to scale up.
I wonder what settings are required for this to work.
The che version I use is 7.3.0.

**Comment by monaka** [comment]
The reason and simple.
Under the default setting, Che7 treats `FailedScheduling` event as unrecoverable.

https://github.com/eclipse/che/blob/6e941bdd932e4783fd5bbed02c3c0098ccce90cd/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L260

So you need to overwrite it, @kellyhyomin 

I'm running Che7 on Azure AKS with Cluster Autoscaler.
It have been working well after changed that.

**Comment by kellyhyomin** [comment]
@monaka Thanks to you, I solved the issue.
