### ISSUE TITLE
[dogfooding] wrong redirection in serve che-docs task

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#15865]
When running che-docs on Hosted Che, the task “serve che-docs” is running OK, but redirection to http://0.0.0.0:4000 makes the service unusable.

Problem reported in https://github.com/eclipse/che-docs/pull/1050

Warning: we have to fix it without breaking `run.sh` launched from a workstation.

**Comment by benoitf** [comment]
P1 for dogfooding

**Comment by themr0c** [comment]
This is fixed.
