### ISSUE TITLE
Mount GitHub token to theia-ide container

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#15873]
### Is your enhancement related to a problem? Please describe.

We have vscode GitHub pull-request plugin in the che plugin-registry. Each time a workspace starts the plugin asks to authenticate, even if the token was provided previously. 
### Describe the solution you'd like

We can mount the GitHub token to the `settings.json` file in the `theia-ide` container so that the vscode GitHub pull-request plugin would fetch it on start step. Once the GitHub PR plugin is started it removes the token from the `settings.json` file.
### Additional context

cc @l0rd

**Comment by monaka** [comment]
@vinokurig Hello.  I'm getting the same issue. How do you manage your GitHub token ?
I guess I can set GH token via devfile.yaml (by #12992 ). But I want to avoid to write my token to the plain yaml if I could did it.
I'm thinking about planning to resolve this issue if you don't have an workaround.

**Comment by vinokurig** [comment]
@monaka As for the [vscode GitHub pull-request plugin](https://github.com/microsoft/vscode-pull-request-github), the authentication plugin that fetches the GitHub token via oAuth and injects it to the GitHub pr plugin was added, see: https://www.eclipse.org/che/docs/che-7/end-user-guide/version-control/#_using_the_github_pull_requests_plug_in

**Comment by monaka** [comment]
@vinokurig Thank you for your information.  I see there is no need to implement the enhancement.  I close here.
