### ISSUE TITLE
Update devfile editor with code assist from data from registries

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#15876]
devfile editor should use the new [defaultSnippets](https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas) support to provide code assist for things like chePlugins. It can retrieve the list of plugins from registry and provide them as code assist through defaultSnippets. This can be similar to https://github.com/redhat-developer/vscode-tekton/pull/138

**Comment by tsmaeder** [comment]
In related news, the schema we're using for providing content assist could be improved: https://github.com/eclipse/che/issues/15611.
