### ISSUE TITLE
Cover GO devfile

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15872]
### Is your task related to a problem? Please describe.
Add test for a GO stack. Place this test to /devfiles folder so it will be included in nightly checks.

The test should cover:
- [ ] workspace starts successfully
- [ ] LS works correctly
- [ ] commands work correctly
- [ ] Make sure this test is running nightly together with other stacks tests

### Describe the solution you'd like
The test should have the same structure as other tests in tests/e2e/test/devfiles.

**Comment by ScrewTSW** [comment]
Me wanna

**Comment by ScrewTSW** [comment]
danke

**Comment by ibuziuk** [comment]
@ScrewTSW moving to 7.10.0
