### ISSUE TITLE
Add possibility to change the bindings in downstream

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15881]
### Is your task related to a problem? Please describe.
Previously, there was ContainerInitializer in e2e tests that allow changing bindings in e2eContainer, so then the tests could be executed directly from upstream. This way no classes expect of the one that needed to be overwritten has to be copied in downstream.
There was a change [1] done trying to get rid of ContainerInitializer due to which this functionality is now missing. It is a major requirement for Hosted Che tests.

[1] https://github.com/eclipse/che/pull/15827

### Describe the solution you'd like
Investigate if there is a better and cleaner solution on how to get this functionality back.

### Describe alternatives you've considered
If no other way is found, switch the approach back to ContainerInitializer.

**Comment by Ohrimenko1988** [comment]
I have found one of the probable solutions
 - create a file:
```
import { inversifyConfig } from 'e2e';
import { Container } from 'inversify';
import { codereadyContainer } from './inversify.config';

const container: Container = codereadyContainer;

suite('Init container', async () => {
    test('Init', async () => {
        // initialization
    });
});

```
and add it to the launch configuration (on the downstream side)
```
--timeout 1200000
-u tdd
--bail
--full-trace
--reporter 'node_modules/e2e/dist/driver/CheReporter.js'
--spec ./dist/init-test.spec.js
--spec ./node_modules/e2e/dist/tests/login/Login.spec.js
```
in this case the next changes will work (in this case the "ICheLoginPage" successfully rebinded from multi-user to single-user implementation):
```
inversifyConfig.e2eContainer.rebind<ICheLoginPage>(TYPES.CheLogin).to(SingleUserLoginPage).inSingletonScope();

const codereadyContainer: Container = inversifyConfig.e2eContainer;

codereadyContainer.bind(CODEREADY_CLASSES.ApplicationReadinessUtil).to(ApplicationReadinessUtil).inSingletonScope();

export { codereadyContainer };
```
I'll continue playing with this and try to minimize initialization file or maybe find another solution.

**Comment by Katka92** [comment]
So the last code snippet should be placed in the first one instead of `//initialization` part?

**Comment by Ohrimenko1988** [comment]
Done. 
Changes in the upstream code: <https://github.com/eclipse/che/pull/16155>
Instruction how to reuse them in the downstream: <https://github.com/eclipse/che/issues/15881#issuecomment-580273205>
