### ISSUE TITLE
@eclipse-che/theia-generator is not published

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15887]
### Describe the bug

**@eclipse-che/theia-generator** node package must be published to npmjs on each change.

The last publishing of the package was a month ago, but sources of the generator was changed few days ago in this PR https://github.com/eclipse/che-theia/pull/609

To check, go to the package on npmjs https://www.npmjs.com/package/@eclipse-che/theia-generator

**Comment by tolusha** [comment]
@vitaliy-guliy 
What issues does it cause exactly?

**Comment by vitaliy-guliy** [comment]
@tolusha 
You cannot init and build your Che-Theia without building the yeoman generator from sources.

**Comment by azatsarynnyy** [comment]
There's the PR https://github.com/eclipse/che-theia/pull/617 which should fix the issue.
But the proposed patch breaks the build of Che Theia on CI https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-nightly/60/consoleFull
So, it has been reverted by https://github.com/eclipse/che-theia/pull/620
Need to investigate why it fails.

**Comment by azatsarynnyy** [comment]
Fixed in https://github.com/eclipse/che-theia/pull/679
