### ISSUE TITLE
Proactively deal with dependencies when unresponsive (?)

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#15884]
### Is your enhancement related to a problem? Please describe.
A Che demonstration was jeopardized because of a slow workspace dependency.  (The dependency was 'bayesian', an analytics tool.)  Because it wasn't responding, Che would spin up extra web sockets.  The system became swamped and very slow to respond. 

### Describe the solution you'd like
If possible, have Che react with intelligence to this scenario.  Perhaps let Che warn the user, then disable the balky dependency for future workspaces.

### Describe alternatives you've considered
This request is a suggestion only, meant to stir constructive exploration of the problem area.  

### Additional context
At least two Che demo scenarios were 'saved' when administrators edited Che workspace options so they no longer required the balky dependency.  (But after some rushed diagnostics.  Not all users might be lucky enough to find the problem and solution in a timely manner.)

**Comment by tolusha** [comment]
Che 6.x is out of support.
