### ISSUE TITLE
Happy path E2E tests failed on validation of debug functionality

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15882]
### Describe the bug
Happy path E2E tests failed being run against _Single User Eclipse Che 7.8.0.RC_ on _minikube 1.1.1_:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/pre-release/job/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/55/console
```
16:30:45     1) Run debug and check application stop in the breakpoint
16:30:45 
16:30:45 
16:30:45   22 passing (34m)
16:30:45   1 pending
16:30:45   1 failing
16:30:45 
16:30:45   1) Validation of debug functionality
16:30:45        Run debug and check application stop in the breakpoint:
16:30:45      TimeoutError: Exceeded maximum clicking attempts, the 'By(css selector, .theia-mini-browser .theia-mini-browser-refresh)' element is not clickable
16:30:45       at DriverHelper.<anonymous> (/tmp/e2e/utils/DriverHelper.ts:237:15)
16:30:45       at Generator.next (<anonymous>)
16:30:45       at fulfilled (/tmp/e2e/dist/utils/DriverHelper.js:17:58)
16:30:45       at <anonymous>
```
![screenshot-Run_debug_and_check_application_stop_in_the_breakpoint](https://user-images.githubusercontent.com/1197777/73462977-3eb54580-4385-11ea-8a1a-e4923d1be7e8.png)

There issue wasn't reproduced against [Multi User Che assembly](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/pre-release/job/MultiUser-Che-release-check-e2e-tests-against-k8s/21/).

### Screencast
https://youtu.be/PJmYeBTJ1m8

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: Eclipse Che 7.8.0.RC

### Steps to reproduce
https://github.com/eclipse/che/blob/7.8.x/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
Based on the  screenshot, the Application stopped on the breakpoint, didn't it?
