### ISSUE TITLE
Restore e2e tests in User Dashboard

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#15891]
### Is your task related to a problem? Please describe.

Currently e2e tests for UD unable to run.

### Describe the solution you'd like

Look into how to restore e2e test workability and run them to test the Dashboard.

**Comment by tolusha** [comment]
@akurinnoy 
Is it for QE team, right?

**Comment by akurinnoy** [comment]
@tolusha no, it's for Controller Team

**Comment by akurinnoy** [comment]
It's not going to be fixed since these tests are outdated and it's not relevant to restore them.
Instead - e2e tests will be implemented for pages on Dashboard Next in the scope of https://github.com/eclipse/che/issues/16910 and https://github.com/eclipse/che/issues/16911
