### ISSUE TITLE
Intercept Ctrl + W in terminal

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1589]
Ctrl + W in terminal commonly deleted previous word, but it also commonly closes current tab (without warning).

Solutions:
- Show a warning
- Create a Chrome App so that it can intercept Ctrl + W.

**Comment by ghost** [comment]
Indeed, some shortcuts are reserved by a browser. Labeling it an enhancement.

**Comment by TylerJewell** [comment]
Part of xterm.js migration which is going to ship in 5.3
