### ISSUE TITLE
Can't even initialize Dashboard with first log in

### ISSUE THREAD

**Issue by stkachyk** [eclipse-che/che#15901]
I just signed up to Eclipse Che and got notifications that my services were created. I clicked the Get Started button to enter Eclipse, and have been seeing the following message:
![image](https://user-images.githubusercontent.com/46636473/73581587-e6467c80-4446-11ea-9f40-99f81049b208.png)
Reloading the dashboard doesn't change anything, and there are no options available. How do I set up the environment for use?

Thank you

**Comment by tolusha** [comment]
@stkachyk 
Try to empty cache or open in an anonymous tab

**Comment by sleshchenko** [comment]
@stkachyk Could you clarify which Eclipse Che you just signed up? Is it che.openshift.io or some other installation(if yes do you know how it was deployed)?
