### ISSUE TITLE
chectl client takes more time to install and fails with too many open files from RHEL 7.6  client

### ISSUE THREAD

**Issue by jagraj** [eclipse-che/che#15908]
### Describe the bug

I tried to install "che" from chectl and it is taking forever to complete the installation on OpenShift 4.3 cluster. I took more than 2 hours and it completed with all the errors at my client saying too many open files. After chectl timed out I see all pods up and running but client side I see bunch of errors. 

Here is my install command.

`chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=setup/install_che/che-operator/codewind-checluster.yaml --che-operator-image=quay.i                                                                                                              o/eclipse/che-operator:7.5.1`

```
Error: EMFILE: too many open files, open '/tmp/chectl-logs/1580699176591/che/plugin-registry-5c744d4f-lqn8v/che-plugin-registry.log'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.appendFileSync (fs.js:1240:6)
    at Writable.stream._write (/usr/local/lib/chectl/lib/api/kube.js:1402:24)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Writable.write (_stream_writable.js:299:11)
    at Request.ondata (internal/streams/legacy.js:15:31)
    at Request.emit (events.js:203:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/chectl/node_modules/request/request.js:1080:12)
```

 

### Che version

 - [ ] latest
 - [ ] nightly
 - [* ] other: 7.5.1

Chectl version - chectl/7.7.1 linux-x64 node-v10.18.1

### Steps to reproduce

1. Install OpenShift 4.3
2. Install Che 7.5.1 from chectl client installed on OS RHEL 7.6
3. After more than 2hrs install command fails with above error.
4. But install succeeds on OCP 4.3 if I look at the pods on che namespace.
5. User thinks the install failed and also it takes more than 2 hrs. 

### Runtime
   - [ *] kubernetes (include output of `kubectl version`) 
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"4320e48", GitTreeState:"clean", BuildDate:"2020-01-21T19:50:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```
   - [ *] Openshift (include output of `oc version`)

```
 oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ *] chectl 

```chectl/7.7.1 linux-x64 node-v10.18.1```

   - [* ] che-operator 

```7.5.1```

   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [* ] Linux
```
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@tolusha FYI

**Comment by tolusha** [comment]
@jagraj 
Could you check the project structure `tmp/chectl-logs/1580699176591` ? How many created files do you have?

**Comment by tolusha** [comment]
Some bugs have been fixed, 
Could you update checlt and try again?

**Comment by jagraj** [comment]
This issue has been fixed with latest chectl release and worked fine in couple of my clusters.  Thanks for the fix.

**Comment by tolusha** [comment]
@jagraj 
It is good to know.  Thank you for the response.
