### ISSUE TITLE
Ability to specify repo at building che-theia image 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15914]
### Is your enhancement related to a problem? Please describe.
At the moment it's possible to specify [a branch](https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/README.md#theia-branch) at building che-theia image.
It would be nice to have ability to specify a repo as well.

### Describe the solution you'd like
Add the corresponding parameter to build arguments.

### Additional context
The improvement can be useful for https://github.com/eclipse/che/issues/15912
`theia` repo can have PRs from fork, so to check a PR changes for `che` and build `che-theia` image we need the corresponding parameter among build arguments.

**Comment by azatsarynnyy** [comment]
There's a build-time argument [`THEIA_GITHUB_REPO`](https://github.com/eclipse/che-theia/blob/5f5fd52664d87e62a2427ba57ebf458a0bb1f88f/dockerfiles/theia/Dockerfile#L21) which allows specifying Theia repository.
E.g. `./build.sh ... --build-arg:THEIA_GITHUB_REPO=fork/theia`

**Comment by RomanNikitenko** [comment]
I think it makes sense to update [README](https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/README.md#build-arguments)
