### ISSUE TITLE
placeholder for preview URL

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1591]
Menu "Run" > "Edit Commands...", the "Preview URL" input field should have a placeholder text like `http://${server.port.8080}`. I'd be useful to avoid having to go to the documentation to understand a common standard valid field.

**Comment by ghost** [comment]
Do you suggest smth like a tooltip with explanation on what a preview URL is?

**Comment by wernight** [comment]
I was thinking about a simple placeholder text but anything more would be welcome.

![image](https://cloud.githubusercontent.com/assets/145667/16407492/4e48f7ce-3d14-11e6-85ab-a6893fb8719a.png)

**Comment by TylerJewell** [comment]
I think this is a great idea.  There are two other issues around macro management.  @slemeur please link the issues together.  The other issues are related to expanding the macro syntax.

**Comment by TylerJewell** [comment]
@wernight - this is going to appear in the 4.7 release along with a new batch of macro improvements.
