### ISSUE TITLE
Update helm chart to use RollingUpdate strategy

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15915]
### Is your task related to a problem? Please describe.
It's possible to setup _Recreate_ update strategy of _Che Server_ deployment using **deploy_che.sh** script. This strategy is default in the [deploy_che.sh](https://github.com/eclipse/che/blob/master/deploy/openshift/deploy_che.sh#L56) and it has `--rolling` option to setup _Rolling_ update strategy. 

At the same time:
- there are no neither `--rolling` or `--recreate` options in chectl;
- [che-operator](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/deployment_che.go#L100) configures **che-server** to use `Rolling` update strategy by default, and **che-operator** seems doesn't have an option to setup `Recreate` update strategy.

**Comment by l0rd** [comment]
@dmytro-ndp can you please clarify why this is important for you? I have set `severity/P2` because I am considering that `RollingUpdate` `StrategyType` should be fine for every scenario but I am missing what's the scenario you have in mind so I may be wrong.

**Comment by dmytro-ndp** [comment]
@l0rd: we are officially supporting _recreate_ update strategy for che6/CRW 1.x. 
Recreate strategy is also default for Che 7 deployed to minikube by [using helm charts](https://github.com/eclipse/che/blob/84cbaecfb1e2ea0cb96463d010c7c81b1dd21dbb/deploy/kubernetes/helm/che/templates/deployment.yaml#L24), which is inconsistent with operator installer.
Anyway, feel free to close the issue with `won't fix` resolution.

**Comment by l0rd** [comment]
@dmytro-ndp we should fix the inconsistency. We should **not** add the `--rolling/--recreate` option if `RollingUpdate` works for every user scenario. 

@skabashnyuk is there a reason why we use `Recreate` strategy for wsmaster by default on helm chart and deploy.sh but not on the operator? Would it be an issue if we set `RollingUpdate` by default everywhere?

**Comment by dmytro-ndp** [comment]
@l0rd: well, I didn't mention [deploy_che.sh](https://github.com/eclipse/che/blob/master/deploy/openshift/deploy_che.sh) so as we are getting rid of it https://github.com/eclipse/che/issues/13888.

**Comment by skabashnyuk** [comment]
@l0rd 
>Is there a reason why we use Recreate strategy for wsmaster by default on helm chart and deploy.sh but not on the operator?

I'm not aware of that.

> Would it be an issue if we set RollingUpdate by default everywhere?

It should not.

**Comment by tolusha** [comment]
@dmytro-ndp 
Do we still need this?

**Comment by l0rd** [comment]
@tolusha we still have to fix the inconsistency between the deployment strategies of Che helm chart (recreate) and Che operator (rollingUpdate). RollingUpdate should be the default for both.
