### ISSUE TITLE
Fix root-compilation.tsconfig.json file

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15916]
### Describe the bug

References

```
   {
      "path": "../examples/assembly/compile.tsconfig.json"
    }
```
are added to `root-compilation.tsconfig.json` file every build che-theia project 

### Che version

 - [x] latest

### Steps to reproduce

1. Clone `che-theia` repo and try to build it. 
2. Go to `root-compilation.tsconfig.json` file
3. You can see that extra references was added

### Expected behavior

extra references are not added at building `che-theia` project

### Screenshots
![extra_references](https://user-images.githubusercontent.com/5676062/73734387-3d4d9980-4746-11ea-8e16-bc7dbd3f672a.png)

### Environment
   - [x] Linux

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che-theia/pull/655
