### ISSUE TITLE
Java language support not working in Apache Camel K worskpace

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15910]
### Describe the bug

The Java language support is not working in default Apache Camel K workspace. Functions like `Ctrl + click` to e.g. open a class or go to the definition does not work, error highlighting does not work.

### Che version

 - [x] latest 7.9.0
 - [x] other: 7.8.0

### Steps to reproduce

1. Go to Workspace -> Add Workspace
2. Choose Apache Camel K workspace
3. Create and run the workspace with default settings
4. Open any Java file (e.g. polyglot -> JavaRoute.java)
5. Try `Ctrl + click` on `info` on line 23 - nothing happens
6. Insert new line 24, type `error` - no error highlighting

### Expected behavior

Error highlighting and code navigation should work.

### Runtime

- [x] other: Che version 7.9.0 on openshift, https://che.prod-preview.openshift.io with version 7.8.0

### Screenshots

![Screenshot from 2020-02-04 08-40-47](https://user-images.githubusercontent.com/29278800/73723747-15503d00-472a-11ea-888c-d479b6c97088.png)

### Installation method

- [x] chectl for 7.9.0

### Environment
- [x] Cloud
  - [x] Amazon for Che with 7.9.0 version
- [x] other: for che.prod-preview.openshift.io

**Comment by tolusha** [comment]
I believe these kind of issues must contain workspace logs.
Currently it is easy to get them using `checlt workspace:logs -w <id> -n <namespace>` command.

**Comment by Katka92** [comment]
@tolusha So this is the output of the command you've sent.

[events.txt](https://github.com/eclipse/che/files/4152281/events.txt)
[verifier.log](https://github.com/eclipse/che/files/4152285/verifier.log)
[che-machine-exec2jx.log](https://github.com/eclipse/che/files/4152287/che-machine-exec2jx.log)
[mysql.log](https://github.com/eclipse/che/files/4152288/mysql.log)
[theia-idepvi.log](https://github.com/eclipse/che/files/4152289/theia-idepvi.log)
[vscode-javae9k.log](https://github.com/eclipse/che/files/4152290/vscode-javae9k.log)

**Comment by tolusha** [comment]
Probably Java ls in't initialized. 
Could you refresh the tab to check if it helps?

**Comment by Katka92** [comment]
I tried to reopen file and nothing changed, but after the refresh, I saw this pop-up.
![Screenshot from 2020-02-04 10-41-30](https://user-images.githubusercontent.com/29278800/73732747-01610700-473b-11ea-9e09-539563ed7b87.png)

**Comment by l0rd** [comment]
It looks like the Camel K plugin doesn't work with the version of Kube you are running on. @Katka92 what's exactly the OpenShift version? cc @apupier @bfitzpat

**Comment by apupier** [comment]
In the Camel K Dev file, Java language support is not provided https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/apache-camel-k/devfile.yaml . We will surely need to play with memory to fit in the 3G memory limits of che.openshift.io as the Kubernetes side is already taking [1G](https://github.com/eclipse/che-plugin-registry/blob/ca82ea9b5584b4235464babc7eaaa52c386fb164/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml#L17) 

The Java language support is really limited currently in the absolute. Even if the Java language support is activated, as it is a standalone file you will have only syntax validation. VS Code Java 0.55+ is required to have proper Java support which is a version not yet available in Che.

What Camel K is providing is Camel URI completion in Camel K Standalone files.

For the kubectl error, seems effectively that the kubectl version is not compatible with the Kubernetes/OpenShift version you are trying to connect to.
The kubectl version is coming from Kubernetes sidecar https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/blob/1.0.4/Dockerfile#L13

**Comment by apupier** [comment]
created for including Java in Camel K stack https://github.com/eclipse/che/issues/16018

**Comment by apupier** [comment]
ok to use #16018
