### ISSUE TITLE
Can't find REST API about auth.

### ISSUE THREAD

**Issue by wn092943** [eclipse-che/che#1592]
hi,
I find the `auth` REST API in `https://eclipse-che.readme.io/docs/rest-api`. However, when I visit `http://localhost:8080/swagger/`, I can't find  `auth` item.  
The version of Che is 4.3.4.
In addition, I don‘t understand the content of `https://eclipse-che.readme.io/docs/authentication`,can you give me some advice or more docs about authentication management?

How to achieve user management? For example, showing specific workspaces based on which account was logined, like visiting `http://beta.codenvy.com/`. I find REST API in `http://beta.codenvy.com/swagger` are much more than `http://localhost:8080/swagger/`.Where can I read relevant sources about these services?

**Comment by TylerJewell** [comment]
Hi:  we have a lot of core engineers on holiday so give us a little bit and we will get a response soon.

**Comment by TylerJewell** [comment]
@wn092943 - The authentication API is part of Codenvy, but not currently part of Che.  It was previously in the 3.x generation of Che to provide certain types of in-workspace authentication.  So this is a documentation error.

We will remove it out of the documentation of Che and put it into the Codenvy documentation to make the separation clearer.

A little bit later this year, we will release a new version of Che that has a lightweight built-in authentication & user management mechanism.  We get this request frequently.

**Comment by TylerJewell** [comment]
@ddementieva - please update docs to remove this wrong reference and then close this issue.

**Comment by JamesDrummond** [comment]
@ddementieva What's the status on this?

**Comment by ddementieva** [comment]
Docs updated: http://codenvy.readme.io/v4.4/docs/rest-api#section-authentication 

Closing the issue.
