### ISSUE TITLE
Theia container log is spammed with errors about not set CHE_WORKSPACE_TELEMETRY_BACKEND_PORT

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#15923]
### Describe the bug

theia-ide container is spammed with 
```
root ERROR Unable to create Che API REST Client: "CHE_WORKSPACE_TELEMETRY_BACKEND_PORT" is not set.
```

I guess it is doing something repeatedly, which should be done just once at the beginning. In any case, it should not spam the log like this.

### Che version

 - [x] latest

### Steps to reproduce

1. start any workspace
1. watch theia container log `kubectl logs -f <workspace_pod> -c <theia_container>  -n <workspace_namespace>`
1. open some file in the workspace and type anything
1. see lot of `root ERROR Unable to create Che API REST Client: "CHE_WORKSPACE_TELEMETRY_BACKEND_PORT" is not set.` in theia logs

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![theia_log](https://user-images.githubusercontent.com/1160903/73755382-39ca0a80-4766-11ea-8bd3-7e83d6d571a2.png)

### Installation method
   - [x] chectl  helm

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by ibuziuk** [comment]
PR merged - https://github.com/eclipse/che-theia/pull/621
