### ISSUE TITLE
How can external applications consume the rest api exposed by cheEditor component ?

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#15928]
Hi all, I would like to get some ideas on the following scenario... I would like to add rest api to theia IDE component (which resides inside the workspace pod) so that an external web application can access it. Can anyone please help? thanks in advance.

I'm planning to build another web application hosted in aws that will be the client for the rest api in theia ide container within a workspace. The challenge is how to make this rest api (in theia ide container) available for external apps.

Also, can we define 'public = true' for exposed port of a cheEditor component? Can we add this to the cheEditor's plugin yaml ?

**Comment by benoitf** [comment]
hello, if you do change theia IDE to add REST API there, it means you're changing the editor (like patching che-theia) so you can use what you want to your plugin's definition.

BTW I'm not sure not follow why you need to have REST API in all theia instances and access it externally but as you do your own customisation you're free to operate in the way you want
