### ISSUE TITLE
Disable "Download" menu item for che-theia editor

### ISSUE THREAD

**Issue by polkaudio124** [eclipse-che/che#15927]
Hello,

May i check, if there is any configuration / plugin to disable to download menu for che-theia editor?
Could some one point to any guide on this topic?

Thanks a bunch!

**Comment by benoitf** [comment]
Hello @polkaudio124 

If it's to disable Theia download contribution
https://github.com/eclipse-theia/theia/blob/248775060d2e4815306ac025b18f67364ff5d62a/packages/filesystem/src/browser/download/file-download-frontend-module.ts


you can just unbind it in one of your Che-theia extension being loaded after theia extensions (to be sure to unbind something already bound)

**Comment by polkaudio124** [comment]
@benoitf  Thank you for the prompt response. 
I am very new to eclipseche. Would you kindly point me to guide or sample to build and deploy a che-theia extension?

**Comment by rminchev1** [comment]
Hey @polkaudio124,  you may have a look at the contributors guide - more specifically: [Developing Che-Theia plugins](https://www.eclipse.org/che/docs/che-7/developing-che-theia-plug-ins/ )

Hope this helps,
Rado
