### ISSUE TITLE
Getting started page does not consume che.workspace.persist_volumes.default

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15921]
### Describe the bug
The new getting started page is not affected by the `che.workspace.persist_volumes.default` setting.

### Che version
 - [x] latest
 - [x] nightly
 - [x] Hosted Che

### Steps to reproduce
1. Start che server with `che.workspace.persist_volumes.default=false`
2. Create workspace through "Getting started" page

### Expected behavior
If `che.workspace.persist_volumes.default=false`, workspace should have temporary storage enabled.

**Comment by amisevsk** [comment]
cc: @ibuziuk

**Comment by ibuziuk** [comment]
@sleshchenko could you please take care of this for 7.9.0 ?

**Comment by sleshchenko** [comment]
@amisevsk I think it kind of duplicates https://github.com/eclipse/che/issues/15855

> @sleshchenko could you please take care of this for 7.9.0 ?

Will try, seems we have P2 issues in the current sprint we can postpone a bit.
