### ISSUE TITLE
Error: Failed to get the workspace: "Unknown error"

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15922]
### Describe the bug

I was not able to load my go based workspace.

### Che version

 - [X] latest

### Steps to reproduce
Unknown.
I just create a go based workspace and try to start it.

### Expected behavior

The workspace should load correctly.

### Runtime

   - [X] Openshift (include output of `oc version`)

### Screenshots

![](https://user-images.githubusercontent.com/1614429/73753932-cde6a280-4763-11ea-857f-e3b30dccb561.png)

### Installation method
   - [X] chectl 
``` chectl server:start --platform=crc --installer=operator --os-oauth --tls --self-signed-cert```

### Environment

- [X] macOS

### Additional context

https://github.com/eclipse/che/issues/14931

**Comment by ibuziuk** [comment]
confirm having this kind of issue on crc

**Comment by l0rd** [comment]
@skabashnyuk that's nightly right? cc @olexii4

**Comment by skabashnyuk** [comment]
>@skabashnyuk that's nightly right?

yes

**Comment by olexii4** [comment]
@l0rd 
It is a workspace-loader error. It can depend on self-signed-cert. I didn't see this error.

We have an issue about self-signed-cert errors 
[Dashboard messages should be more accurate when self-signed cert issue happens](https://github.com/eclipse/che/issues/15298), but it is not cover a possible error in the workspace-loader.

@akurinnoy What do you think about this workspace-loader error? Do you have a similar problem with your macOS?

**Comment by skabashnyuk** [comment]
@olexii4  self-signed-cert added to macOS trust store. The browser thinks it's valid.

![Знімок екрана  о 10 16 10](https://user-images.githubusercontent.com/1614429/73827919-abef2d80-4800-11ea-8896-468c52f95353.png)
![Знімок екрана  о 10 16 01](https://user-images.githubusercontent.com/1614429/73827926-adb8f100-4800-11ea-9479-462fa325f6b4.png)
![Знімок екрана  о 10 17 50](https://user-images.githubusercontent.com/1614429/73827990-ca552900-4800-11ea-89a0-b2e8553cfecc.png)
![Знімок екрана  о 10 17 39](https://user-images.githubusercontent.com/1614429/73827995-ccb78300-4800-11ea-9866-f8b4a595020e.png)

**Comment by olexii4** [comment]
@skabashnyuk Thanks. I see.

**Comment by skabashnyuk** [comment]
Reproduced for me on new crc cluster with a first starting workspace.
![Знімок екрана 2020-02-17 о 15 42 16](https://user-images.githubusercontent.com/1614429/74663536-3e49e680-519c-11ea-92bd-82df996b17fb.png)

Failed request
```
curl 'https://che-che.apps-crc.testing/api/workspace/workspaceyht1t42gstrzts92' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36' -H 'Sec-Fetch-Dest: empty' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://che-che.apps-crc.testing/workspace-loader/skabashn/golang-zwj7o?uid=211051' -H 'Accept-Language: uk-UA,uk;q=0.9,ru-UA;q=0.8,ru;q=0.7,en-US;q=0.6,en;q=0.5' -H 'Cookie: 0f443a2a27de429b7964dbc8f3c18ef4=1298ba066292e063f01a89a71b711f9a' --compressed

```

**Comment by skabashnyuk** [comment]
![Знімок екрана 2020-02-17 о 15 46 49](https://user-images.githubusercontent.com/1614429/74663788-badcc500-519c-11ea-8b92-ed4046634cab.png)

**Comment by sleshchenko** [comment]
@skabashnyuk Thanks for sharing details...
Seems that token is expired, the token is refreshed, the request is made with the expired token, the token is refreshed.

Not sure how workspace loader use keycloak script, maybe there is way to ask keycloak to make sure that token is valid before doing request. @akurinnoy Do you remember that area?

I wonder if you face the same issue during switching tabs in Dashboard.

**Comment by akurinnoy** [comment]
@sleshchenko yes, workspace loader asks keycloak to update token before doing any requests, otherwise it redirects to login. Same as @skabashnyuk I faced this issue on new CRC cluster while starting the first workspace for the first time and couldn't reproduce it more.

**Comment by Katka92** [comment]
I can see that issue too from time to time on a nightly Che deployed on OpenShift cluster. I'm using chectl for installation, also using tls and self-signed certs.

**Comment by akurinnoy** [comment]
@skabashnyuk I'm not able to reproduce this bug anymore. Could you please confirm or deny same on your side?

**Comment by skabashnyuk** [comment]
No longer reproduced.
