### ISSUE TITLE
Continue where you left off

### ISSUE THREAD

**Issue by broopdias** [eclipse-che/che#15934]
I was wondering if it is possible to save what files are opened?

Something like "Continue where you left off" so next time we open Che, we have all opened pages ready.

**Comment by benoitf** [comment]
@azatsarynnyy you've implemented persistence on browser tabs no ?

**Comment by davidwindell** [comment]
:+1: At the moment, it only seems to work on refresh not when workspace restarts.

**Comment by azatsarynnyy** [comment]
It works on between the page refreshing - has been fixed recently https://github.com/eclipse/che/issues/15317
Also, it should work between workspace restarts since the tabs state is stored in `~/.theia` folder.
@vzhukovskii correct me if I'm wrong, please

**Comment by vzhukovskii** [comment]
@azatsarynnyy, @davidwindell said right, as far as I know, persistence between workspace restart has not been implemented yet, there is an issue for that https://github.com/eclipse/che/issues/14717

**Comment by azatsarynnyy** [comment]
@broopdias stay tuned for https://github.com/eclipse/che/issues/14717 :wink:
