### ISSUE TITLE
Authentication to OpenShift OAuth Server

### ISSUE THREAD

**Issue by david-martin** [eclipse-che/che#15936]
### Is your enhancement related to a problem? Please describe.

When running Che in OpenShift, I'd like to allow OpenShift users to login and use Che in multi-user mode. This is currently possible, but it requires the use of Keycloak (or similar auth server) as a proxy between Che and OpenShift.  The requirement of Keycloak in this setup has a few knock on effects that leading me to request this change:

* the login flow includes an extra step in the auth flow. This increase complexity when debugging misconfiguration issues. 
* the Keycloak instance takes up extra resources in the OpenShift cluster. The intent is to deploy Che (actually Red Hat CodeReady Workspaces, but sticking with Che for simplicity here) in a managed environment for users. There will be a lot of clusters created and managed, each with their own instance of Che. The overhead of the Keycloak instance reduces the economies of scale we can take advantage of.
* the Che deployment will be managed with an SLA. To ensure we can offer a reasonable SLA, we need to run Che (and all other components in the managed cluser) in a Highly Available manner. This further increases the resource usage for Keycloak. 

### Describe the solution you'd like

Che can be configured to use OpenShift (via a cluster scoped OAuthClient) as it's identity provider without the use of a Keycloak instance.
In addition, Che can be configured to use GitHub (via a GitHub OAuth App) for users to manage their own repos in Che without the use of a Keycloak Instance.

### Describe alternatives you've considered

Using Keycloak as a proxy for authentication to OpenShift & Github. 

### Additional context

The reason resource usage in a cluster is a concern is because each managed cluster includes a number of other Red Hat products in addition to CRW. The ratio of resources for SRE managed services to a user/customer's resources is something we need to keep a close handle on.

cc @RickJWagner (discussed on a separate channel)

**Comment by skabashnyuk** [comment]
>Che can be configured to use OpenShift (via a cluster scoped OAuthClient) as it's identity provider without the use of a Keycloak instance.

@david-martin can you elaborate more about that? How do you see that?
- Is there a javascript library that Che Dashboard can use to obtain tokens?
- is there java library so che-server can validated that tokens and obtain identities from that tokens?

**Comment by david-martin** [comment]
> * Is there a javascript library that Che Dashboard can use to obtain tokens?

https://www.npmjs.com/package/client-oauth2 has been used successfully.
Here's an example of it being used https://github.com/integr8ly/tutorial-web-app/blob/b4de7e051b5ef9e563a443ae54b398bb98bc7cb4/src/services/openshiftServices.js#L2



> * is there java library so che-server can validated that tokens and obtain identities from that tokens?

I'm a little out of the loop in the world of Java, but I can't see why there wouldn't be libraries that support it.

Another option is using https://github.com/openshift/oauth-proxy, which can sit in front of the Console/Dashboard and pass down user information to the che-server.
However, that wouldn't solve the auth to Github without keycloak.

**Comment by RickJWagner** [comment]
Associated CodeReady Workspaces RFE is CRW-620.
