### ISSUE TITLE
Change Ctrl+Shift+A into Ctrl+Shift+P

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1594]
Ctrl+Shift+P can be used in websites and it has become a pretty standard shortcut for the command panel used by:
- Sublime Text
- Atomic
- Codiad
- ...

**Comment by wernight** [comment]
Why closed? Wouldn't it be nice to use the "standard" shortcut?

**Comment by TylerJewell** [comment]
I am doing bulk closing of older issues to reduce open enhancement requests from 250 down to 150 along with moving all related issues from Codenvy over to Che, and then further consolidating related issues into unified ones for easier tacking.

In this particular case, asking PM to think through a range of issues as it relates to specific key bindings, binding overrides, and so forth.  It's a much bigger overall epic that needs to be considered.
