### ISSUE TITLE
Bad english in chectl/crwctl when deploying in multi-user mode

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15943]
```
Warning: CodeReady Workspaces will be deployed in Multi-User mode 
since Configured 'operator' installer which support only such.
```

This message is confusing. Perhaps a better statement would be:

```
Warning: CodeReady Workspaces operator has been configured to deploy 
in Multi-User mode. To change this [call to action / link to docs if multi-user 
mode is not desired].
```

Version of crwctl used is from this download https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/crwctl_master/24974/artifact/codeready-workspaces-chectl/dist/channels/next/

So it's based on chectl 7.8.0

https://github.com/redhat-developer/codeready-workspaces-chectl/commits/master

**Comment by tsmaeder** [comment]
@nickboldt I think you're statement is not a correct rendering of the original: as I understand it, the operator can only install Che in multi-user mode (so it's not being configured to do so). If you pass "-a operator" to chectl, you'll end up with a multi-user installation. Maybe...
```
Warning: the CRW operator will install CRW in multi-user mode. To install in single-user mode, use a different installation method!
```

**Comment by nickboldt** [comment]
yeah but "`operator`" is the only viable `crwctl` option. And single-user mode is not supported in CRW yet. So... maybe we need to refactor this out of shared code so it gets excluded from crwctl when we sync/fork it from chectl. cc: @sleshchenko 

maybe we can label chunks of code in upstream chectl with a comment like 

```
/* che only block start */
```
and 
```
/* che only block end */
```

**Comment by benoitf** [comment]
I think we have nodejs language permitting more stuff than using comments block to include/exclude

**Comment by nickboldt** [comment]
well if you have a better idea, I'm open. I just want a way to clearly mark excluded blocks from sync to downstream crwctl cc: @mkuznyetsov

**Comment by benoitf** [comment]
Forgot to comment idea:

For errors, error codes (that we can map to different error messages)
For 'messages', externalize to file/constants so it can be replaced

We should include constants for the product name (based on package.json fields as well)

**Comment by nickboldt** [comment]
Thanks, I've opened https://github.com/eclipse/che/issues/16032 to capture the larger exercise for a future chectl release.

**Comment by nickboldt** [comment]
Fix for chectl:

https://github.com/che-incubator/chectl/pull/511

Fix for crwctl:

https://github.com/redhat-developer/codeready-workspaces-chectl/commit/3f33c7cf672f14a58df1f462eb157ef8720ef19d

Maybe they should be the same message for easier sync, but since CRW only has operator install mode, it's kinda of dumb to say "CRW will be deployed in Multi-User mode as 'operator' installer supports only that mode."

**Comment by tolusha** [comment]
Since https://github.com/che-incubator/chectl/pull/511 is merged I close the issue
