### ISSUE TITLE
Chectl debug mode doesn't work for minishift

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#15945]
### Describe the bug

An error occurs when starting debug on minishift.
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start minishift: `minishift start --cpus 4 --memory 10240 --vm-driver=virtualbox`
2. Start che server in debug mode: `chectl server:start -p=minishift --debug`
3. Start debug: `chectl server:debug`
See: an error occurs:
```
chectl server:debug
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ Verify if namespace che exists
  ✔ Find Che Server pod...done
  ✖ Check if debug mode is enabled
    → Che Server should be redeployed with '--debug' flag
    Forward port '8000'
Error: Che Server should be redeployed with '--debug' flag
    at CheTasks.<anonymous> (~/.local/share/chectl/client/0.0.20200204-next.370a015/lib/tasks/che.js:544:31)
    at Generator.next (<anonymous>)
    at fulfilled (~/.local/share/chectl/client/0.0.20200204-next.370a015/node_modules/tslib/tslib.js:107:62)
```
### Expected behavior

Debug must start.
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
I've just tried and it works
```
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ Verify if namespace che exists
  ✔ Find Che Server pod...done
  ✔ Check if debug mode is enabled
  ✔ Forward port '8000'...done
Eclipse Che Server debug is available on localhost:8000.
The program keeps running to enable port forwarding.
```

**Comment by vinokurig** [comment]
Still doesn't work for me
```
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
minishift v1.34.2+83ebaab
chectl/0.0.20200205-next.fa60592 linux-x64 node-v10.18.1
```

**Comment by tolusha** [comment]
I see, by default `minishift-addon` is used.
Pls, use operator.
