### ISSUE TITLE
User can create login account in Che/CRW which is unable to produce workspaces (invalid chars in namespace)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15954]
### Describe the bug

This might be a flaw in Keycloak, not Che... but I wanted to raise it here first. 

It's possible to log in to Che / Workspaces with a new user that will be unable to create workspaces due to invalid characters in the username. 

### Steps to reproduce

1. Deploy CRW 2 onto OCP 4.3.
2. Log in like this, eg., use your email address as your login name:

![image](https://user-images.githubusercontent.com/227597/73999592-3b94f900-4933-11ea-9a48-d7fd61ed4958.png)

3. Now when you try to start a workspace, you get an error like this:

![image](https://user-images.githubusercontent.com/227597/73999608-4bacd880-4933-11ea-9641-b538f6b269df.png)

"The specified namespace nickboldt@gmail.com-che is invalid."

4. So ... why is Keycloak letting me register a username in Che 7.8 / CRW 2.1 that I can't use to create workspaces? Surely we should either:

* prevent users from creating a username that won't comply with DNS-1123 label rules, or

* adjust invalid usernames so they CAN be used under the covers to create a namespace.

### Che version
 - 7.8

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

```
crwctl server:start -n nb-crw21lx --che-operator-image=quay.io/crw/operator-rhel8:latest --che-operator-cr-yaml=custom-resource.yaml
```

(for custom-resource.yaml = https://github.com/redhat-developer/codeready-workspaces-chectl/blob/master/docs/custom-resource.yaml or https://github.com/nickboldt/codeready-workspaces-chectl/blob/2.1-x/docs/custom-resource.yaml )

### Environment
   - [ ] my computer 
       - [X] Windows
       - [X] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [X] other: CRW QE OCP 4.3 cluster
   - [ ] other: please specify

**Comment by tolusha** [comment]
@skabashnyuk 
Is it the same?
https://github.com/eclipse/che/issues/15323
