### ISSUE TITLE
Async PV for workspace: server pod (in user namespace) to provide access to PVC

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15957]
### Introduce new pod to serve files to user workspaces
subtask of https://github.com/eclipse/che/issues/15384 

The pod should boot first without PVC at first to serve requests as fast as possible and do not block requests if new workspace (no persistent data) 

#### impl note:
for obvious reason, do not keep list of managed workspaces into a PVC (as we need to reply as soon as possible if there is no persistent data for a given workspace)
--> config-map
--> deployment / annotation
--> custom resource

#### configuration/enhancements
- allow shutdown after idle
- allow to wake up when user access to the dashboard

### investigate how this pod could `wake up` on demand
automatic / wake up scale to zero knative

**Comment by ibuziuk** [comment]
@benoitf in user namespace = in the namespace where workspace are created, right?

**Comment by benoitf** [comment]
@ibuziuk yes
