### ISSUE TITLE
Async PV for workspace: client container (in workspace pod) to restore/sync files

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15958]
### Develop container discussing with the service/datasync pod
subtask of https://github.com/eclipse/che/issues/15384 

This container will communicate with the server part of the Async PVC service and then:

##### upon start
check some exclusion list, etc and if data to restore, restore them

#### when workspace is running
keep data up-to-date continuously

#### after workspace is stopped
send back all the data to datasync/pod
if the data are not sent back after 'closing the workspace' it can't be started again as well

**Comment by ibuziuk** [comment]
@vparfonov can we close this one?
