### ISSUE TITLE
Image is broken on welcome page

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#15952]
#15861 # Describe the bug
The logo is broken on hosted che fails with the following message

Mixed Content: The page at 'https://che.openshift.io/' was loaded over HTTPS, but requested an insecure image 'theia-resource:/home/theia/node_modules/%40eclipse-che/theia-plugin-ext/src/resource/che-logo-dark.svg'. This content should also be served over HTTPS.
![Screen Shot 2020-02-06 at 11 19 20 AM](https://user-images.githubusercontent.com/82738/73956217-a104cd80-48d2-11ea-9329-c49a4064d0e3.png)

**Comment by benoitf** [comment]
hello, it's a dup of https://github.com/eclipse/che/issues/15324
