### ISSUE TITLE
unzip:  cannot find or open /mnt/che/ws-agent.zip, /mnt/che/ws-agent.zip.zip or /mnt/che/ws-agent.zip.ZIP.

### ISSUE THREAD

**Issue by zgc** [eclipse-che/che#1595]
docker shell:docker run --net=host --restart always --name che -d -v /var/run/docker.sock:/var/run/docker.sock -v /home/it/che/lib:/home/user/che/lib-copy -v /home/it/che/workspaces:/home/user/che/workspaces -v /home/it/che/storage:/home/user/che/storage -v /home/it/che/conf/che.properties:/home/user/che/conf/che.properties codenvy/che:nightly

docker version:
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

**Comment by ghost** [comment]
Can you check if you have `/home/it/che/lib/ws-agent.zip` on your host?

Also, what is your OS? There are known issues with mounting on CentOS, Fedora and RHEL. Do you have Selinux enabled on your system?

**Comment by zgc** [comment]
OS:ubuntu server 16.04
Selinux: no enabled
/home/it/che/lib/ws-agent.zip:exists

**Comment by zgc** [comment]
@eivantsov 
![2016-06-29 17-50-27](https://cloud.githubusercontent.com/assets/4143433/16448102/4d3bf4ee-3e22-11e6-8b20-690044085007.png)
![2016-06-29 17-51-24](https://cloud.githubusercontent.com/assets/4143433/16448103/4d603f84-3e22-11e6-9231-32990c7b3a75.png)

**Comment by ddementieva** [comment]
Che server is looking for ws-agent and Terminal in the ${che.home} directory, which is /home/user/che by default: https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L84 and https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L153

To make it work you can either change /home/it/che to home/user/che in your mount or change the above mentioned properties path from ${che.home} to /home/it/che in your che.properties.

**Comment by tobiasbaehr** [comment]
@ddementieva 
The local path is here /home/it/che. (On mac /Users/myuser/che) And the local directory /home/it/che/lib is mounted here as /home/user/che/lib-copy. Therefore is should find the file.

**Comment by ghost** [comment]
@tobiasbaehr it should be /user/home/che. Change your mount syntax and the problem is gone. Or update che.properties with a new path. When a workspace starts it is looking to mount $(che-home) which is `/home/user/che` and this path does not exist on your localhost. It should either exist or the server should know where to look for ws-agent and terminal on your local filesystem.

**Comment by tobiasbaehr** [comment]
@eivantsov 
Ok I understand. I change it and it works. + the workaround #1482 I can play now with che. /o/

**Comment by TylerJewell** [comment]
Excellent!  What do you think of the product?
