### ISSUE TITLE
Async PV for workspace: events provided by container doing the sync inside the workspace

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15959]
### Publish events on the startup of a workspace:
subtask of https://github.com/eclipse/che/issues/15384 

Eclipse Theia will be able to listen to these events:
Note: if easier, it could be a service that Theia will call/listen when loading.

It should provide information like: 
- restore-status event : it will include if there is a need to restore something or not ? (like if we have a fresh workspace)

- restore event (pre/post) : there was something that needs to be recovered from a previous state. In that case, needs to wait that restoration is finished in the IDE (display progress, etc)

**Comment by vparfonov** [comment]
Depends on: https://github.com/eclipse/che/issues/16464

**Comment by ibuziuk** [comment]
UX demo - https://youtu.be/UHzH66Hz6G4

**Comment by ibuziuk** [comment]
@vparfonov can we close this one?
