### ISSUE TITLE
About dialog is broken 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15962]
### Describe the bug
About dialog looks strange, please see the screenshot.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to `Help` => `About` menu
2. Pay attention how the dialog looks.  
3. Try to refresh a page and go to `Help` => `About` menu again.
4. Pay attention how the dialog looks.  

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![help_about](https://user-images.githubusercontent.com/5676062/74032063-bf92c380-49bb-11ea-9062-efbb01f3dec8.png)
![help_about2](https://user-images.githubusercontent.com/5676062/74032234-1d271000-49bc-11ea-81a6-a7e1ba108235.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
funny thing: closing/reopening about menu is fixing space issue.

**Comment by RomanNikitenko** [comment]
The issue can be related to the changes in `theia` repo https://github.com/eclipse-theia/theia/commit/5034fbe0e64959722027df517f42ce5d443d0f9f

**Comment by nickboldt** [comment]
This is even worse when whitelabelled as CRW:

![image](https://user-images.githubusercontent.com/227597/75682619-b2d45900-5c63-11ea-8d76-0f28e6d2feed.png)

**Comment by nickboldt** [comment]
Escalating to blocker. Something this obviously broken/ugly cannot slip into product.

Please fix for 7.9.1 if possible.

**Comment by nickboldt** [comment]
To be clear there are 3 issues here but one of them might be downstream (not sure if it's a whitelabel coding problem or a missing image in downstream):

* 2 lists of extensions (one empty ABOVE the logo, one populated BELOW the logo)
* 2 "Ok" buttons (left one does nothing, right one closes the dialog as expected) 
* broken CRW icon

**Comment by nickboldt** [comment]
I've been told to not call this a blocker so removing that label. But it's still a priority/P1 if not a severity/S1.

**Comment by nickboldt** [comment]
This appears to be commit in 7.9.x that fixes the same problem in 7.9.0 / master:

https://github.com/eclipse/che-theia/commit/13070ca81030fbcc7f6678eeb6c66d8f49b5b62c
https://github.com/eclipse/che-theia/pull/649/files

(It's fun when the commit messages don't line up.) :D

**Comment by nickboldt** [comment]
Dmytro reports problem not fixed in downstream issue:

https://issues.redhat.com/browse/CRW-674?focusedCommentId=14001032&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14001032

So reopening.

**Comment by benoitf** [comment]
It's already fixed upstream so I don't see why it needs to be opened there
![Uploading image.png…]()
