### ISSUE TITLE
Not able to open Workspace in Chrome. Stuck in Loading. 

### ISSUE THREAD

**Issue by srinikoganti** [eclipse-che/che#1596]
Hi All, 

I am unable to open a workspace in Chrome.

 Chef Server URL-> Dashboard->Recent Workspaces->Open in IDE I get following error.

Error: Can't load project types: Error
    at Object.window.IDE.eventHandlers.initializationFailed (http://x.x.x.x:8080/ide/che/wksp-odt1?uid=740979:39:27)
    at hsb (_app-0.js:1969:166)
    at usb (_app-0.js:1974:454)
    at _.gp (_app-0.js:4236:317)
    at eval (_app-0.js:935:130)

A blank Workspace opens up with "Loading ...."  but it never finished.  

I have run Chef Server in Docker container on a _REMOTE_ Ubuntu server. I am trying to open workspace in a browser on my mac laptop.

I can see that creating a new workspace in dashboard is spawning in new container on the Linux server. I can also telnet to ports that workspace container is using.

I would appreciate if someone can help me past this issue.

Sincerely,
Srini

**Comment by srinikoganti** [comment]
Hi All, 

Issue is resolved. I missed passing the public IP of Che Server with   "--remote:X.X.X.X " option while starting Che server. 

Since the Linux server that Che Server is running has private and public IPs,  Che IDE running on my laptop, doesn't know the public IP to use when reaching out to workspace container running on remote server.

I had to pass that while starting Docker container of Che Server on remote server.

 docker run --net=host \
          --name che \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /home/user/che/lib:/home/user/che/lib-copy \
          -v /home/user/che/workspaces:/home/user/che/workspaces \
          -v /home/user/che/storage:/home/user/che/storage \
          codenvy/che --remote:X.X.X.X

**Comment by TylerJewell** [comment]
Cool! Thanks for self diagnosing.   Hope you enjoy the product.

**Comment by manasmohanty123** [comment]
How can i lunch chrome driver in eclipse che.
