### ISSUE TITLE
Unable to start using chectl 

### ISSUE THREAD

**Issue by chakraborty-slx** [eclipse-che/che#15970]
I am not able to start the Eclipse Che using minikube and chectl

chakraborty@precision7530:~minikube start --memory=16192 --cpus 4
😄  minikube v1.7.1 on Ubuntu 18.04
✨  Automatically selected the virtualbox driver. Other choices: none, docker (experimental)
🔥  Creating virtualbox VM (CPUs=4, Memory=16192MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.17.2 on Docker '19.03.5' ...
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
🌟  Enabling addons: default-storageclass, storage-provisioner
⌛  Waiting for cluster to come online ...
🏄  Done! kubectl is now configured to use "minikube"
chakraborty@precision7530:~$ chectl server:start --platform=minikube
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify if minikube ingress addon is enabled
    ✔ Enable minikube ingress addon
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.100.nip.io.
Eclipse Che logs will be available in '/tmp/chectl-logs/1581062361262'
  ✔ Start following logs
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
  ✔ 🏃  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v2.16.1+gbbdfe5e
    ✔ Create Namespace (che)...done.
    ✔ Create Tiller Role Binding...done.
    ✔ Create Tiller Service Account...done.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...done.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Che Helm Chart...done.
  ❯ ✅  Post installation checklist
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Eclipse Che pod bootstrap
      ✔ scheduling...done.
      ✖ downloading images
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
        starting
      Retrieving Eclipse Che Server URL
      Eclipse Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000
    at KubeHelper.<anonymous> (~/.local/share/chectl/client/7.8.0/lib/api/kube.js:582:19)
    at Generator.next (<anonymous>)
    at fulfilled (~/.local/share/chectl/client/7.8.0/node_modules/tslib/tslib.js:107:62)

**Comment by chakraborty-slx** [comment]
gattytto
5:57 PM



10
..192.168.99.100.nip.io.

5:57 PM
is this right for your case? does the minikube instance have that ip assigned to any interface?   


name: che-devfile-registry
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2020-02-07T10:32:11Z"
    hostIP: 192.168.99.100

**Comment by tolusha** [comment]
Pls, attach logs from the directory `'/tmp/chectl-logs/1581062361262` 
Let's check what went wrong.

**Comment by chakraborty-slx** [comment]
[che_log.zip](https://github.com/eclipse/che/files/4180007/che_log.zip)

**Comment by tolusha** [comment]
```
0s          Normal    ExternalProvisioning   persistentvolumeclaim/che-data-volume    waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manually created by system administrator
<unknown>   Warning   FailedScheduling       pod/che-5f874594c-5pjtg                  error while running "VolumeBinding" filter plugin for pod "che-5f874594c-5pjtg": pod has unbound immediate PersistentVolumeClaims
```

Could you try
```bash
kubectl logs  storage-provisioner storage-provisioner -n kube-system
```

**Comment by chakraborty-slx** [comment]
e-system:storage-provisioner" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
E0210 10:55:22.297007       1 leaderelection.go:331] error retrieving resource lock kube-system/k8s.io-minikube-hostpath: endpoints "k8s.io-minikube-hostpath" is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
E0210 10:55:24.861247       1 leaderelection.go:331] error retrieving resource lock kube-system/k8s.io-minikube-hostpath: endpoints "k8s.io-minikube-hostpath" is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
E0210 10:55:28.199223       1 leaderelection.go:331] error retrieving resource lock kube-system/k8s.io-minikube-hostpath: endpoints "k8s.io-minikube-hostpath" is forbidden: User "system:serviceaccount:kube-system:storage-provisioner" cannot get resource "endpoints" in API group "" in the namespace "kube-system"

**Comment by chakraborty-slx** [comment]
[chelog.log](https://github.com/eclipse/che/files/4180372/chelog.log)

**Comment by tolusha** [comment]
I see, this is the exact error we faced before 
https://github.com/eclipse/che/issues/15944
https://github.com/kubernetes/minikube/issues/6523#issuecomment-582853342

```bash
minikube delete
rm -rf ~/.minkube 
```
start minikube again.

**Comment by chakraborty-slx** [comment]
Yes it works now!!!.
