### ISSUE TITLE
[UD] Create button component styled as PatternFly 4 Secondary button

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#15978]
### Is your task related to a problem? Please describe.

The design of Get Started page was developed using PatternFly 4 components, styles and typography.
Currently "Create a Custom Workspace" button doesn't look and feel as PatternFly 4 Secondary button. 

*Current button*
<img width="1254" alt="Screenshot 2020-02-10 at 18 56 41" src="https://user-images.githubusercontent.com/16220722/74171494-53bc8f00-4c37-11ea-90ba-700b9873ee78.png">

*Original design button*
<img width="1254" alt="Screenshot 2020-02-10 at 18 47 18" src="https://user-images.githubusercontent.com/16220722/74170723-0ab80b00-4c36-11ea-9e97-f2ab85f5797d.png">

### Describe the solution you'd like

Create new button component based on PatternFly 4 Secondary button.

### Describe alternatives you've considered

Apply PF4 styles to existing `che-button` widget. 
Applying correct styles on top of existing widgets is tiresome and error-prone process. This will result in mess of PatternFly, MaterialDesign and other styles.

**Comment by sleshchenko** [comment]
The work is done but not merged yet.
It's closed in the flavor of https://github.com/eclipse/che/issues/16241
