### ISSUE TITLE
Che plugin container security spec

### ISSUE THREAD

**Issue by MarkAckert** [eclipse-che/che#15979]
### Summary

Hi, I am currently looking into creating a chePlugin which requires a custom container with the IPC_LOCK security context set. The current[ chePlugin specification](https://github.com/eclipse/che-plugin-registry#plugin-meta-yaml-structure) does not expose any container security configuration. I think we can work around the current state by instead using a `type: kubernetes` component block in the our stack's devfile, however, handling this in the `chePlugin` YAML spec would be ideal. 

Are there any plans to add container security configuration to the chePlugin YAML spec?

**Comment by ibuziuk** [comment]
@benoitf @l0rd @davidfestal could you please take a look?

**Comment by l0rd** [comment]
@MarkAckert the Che master has a couple of `securityContext` related properties. You can [find them here](https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/#k8s-configuration-settings-specific-to-che-installations-on-kubernetes) but those do not allow to set the `IPC_LOCK` capability.

I am not sure if letting plugins authors (authors of the meta.yaml files) specify containers `securitycontext` attributes is a good idea. That would be a security threat. Think about a plugins that could specify to run as a privileged root user: that may violate the cluster security policies, only admins of a cluster should be able to decide that.

**Comment by MarkAckert** [comment]
I agree generalized privileged escalation is a security risk. 

I didn't specify this well in my initial question, but I'm interested in specific security capabilities, not general privilege escalation. I don't know enough about Linux capabilities to determine if they're an equal security risk to the general escalation case, or if some subset would be allowable. 

And to bring my question to the real use case - we have a plugin which stores encrypted credentials, and we use `keytar` for that. The gnome-keyring daemon underpinning keytar requires `IPC_LOCK` to prevent credentials being paged off to disk.

**Comment by l0rd** [comment]
I see. I would use a component of type `kubernetes` as you mentioned above instead of doing that in a plugin. Why is that less ideal for you? If plugins could set their security contexts they would become less portable: for example your plugin would run in a cluster where`IPC_LOCK` is allowed but won't in an arbitrary cluster. That's true for a devfile as well but I am less concerned about devfiles portability.

**Comment by tjohnsonBCM** [comment]
I've tried modifying a `chePlugin` that requires `IPC_LOCK` as suggested, to instead run as a separate `container` in the K8s pod. This works, but the container name is added to the list of terminals in the "Open Terminal" quickpick.

I don't want it to show there, as there's no reason for someone to launch a terminal in the plugin container. Is there a way in Che to hide the plugin container from the list of developer terminals?

**Comment by zdmullen** [comment]
Any follow-up to @tjohnsonBCM 's question above? Thanks.

**Comment by l0rd** [comment]
@zdmullen @MarkAckert I am trying to understand the use case. You want to use `keytar` in a container and in order for that to work the container needs to be started with `IPC_LOCK` **AND** there should be a `gnome-keyring` daemon running on the Kubernetes node where the container will be scheduled? This is about this keytar: https://github.com/atom/node-keytar?
