### ISSUE TITLE
chectl inject should support oc CLI

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15987]
### Is your enhancement related to a problem? Please describe.

Currently, [`chectl workspace inject -k`](https://github.com/che-incubator/chectl#chectl-workspaceinject) command uses `kubectl` to copy a `kubeconfig` file from local machine to the plugin sidecar. It was introduced in the PR https://github.com/che-incubator/chectl/pull/33 and supposed to be used with Che deployed on minikube, with Che Kubernetes Plugin.

`chectl workspace inject -k` command may be also helpful with Che deployed on minishift. For that, it has be improved to use `oc` CLI as well.

### Describe the solution you'd like

chectl may detect which platform is currently used (minikube/minishift) and use `kubectl` or `oc` CLI.

### Describe alternatives you've considered

From Mario's comment:

> An alternative is to check if kubectl is installed locally and if it's not check for oc. kubectl and oc are interchangeable so it doesn't matter if the platform is openshift or kubernetes: kubectl works on an openshift cluster and oc works on a kubernetes cluster.

### Additional context

`kubectl cp` command usage in chectl sources https://github.com/che-incubator/chectl/blob/1744186acbf0b78404cb1fd267e8ce1a9985144e/src/commands/workspace/inject.ts#L173

**Comment by azatsarynnyy** [comment]
cc/ @nickboldt

**Comment by nickboldt** [comment]
Will this be done in time for Che 7.9? I'm hoping so since we need this functionality for the camel-k devfile.

**Comment by azatsarynnyy** [comment]
> Will this be done in time for Che 7.9? I'm hoping so since we need this functionality for the camel-k devfile.

@tolusha FYI

**Comment by l0rd** [comment]
> chectl may detect which platform is currently used (minikube/minishift) and use kubectl or oc CLI.

An alternative to check if `kubectl` is installed locally and if it's not check for `oc`. `kubectl` and `oc` are interchangeable so it doesn't matter if the platform is openshift or kubernetes: `kubectl` works on an openshift cluster and `oc` works on a kubernetes cluster.

**Comment by tolusha** [comment]
@azatsarynnyy 
So, the purpose of this issue is to detect oc/kubectl for `inject` command? right?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy
> So, the purpose of this issue is to detect oc/kubectl for `inject` command? right?

correct

**Comment by tsmaeder** [comment]
> 
> 
> Will this be done in time for Che 7.9? I'm hoping so since we need this functionality for the camel-k devfile.

How can we need this for a devfile? Che/CRW-ctl might not even be present if Che is installed via operator, no?

**Comment by nickboldt** [comment]
> may be also helpful with Che deployed on minishift. For that, it has be improved to use oc CLI as well.

I don't think we support minishift anymore -- especially not for use with crwctl, which is officially supported ONLY for deploying to OCP 3.1 and airgapped/offline 4.x. 

> How can we need this for a devfile?

The camelk devfile's sidecar contains helm, kubectl and kamel. Can a user just run kubectl directly from within the workspace's sidecar's terminal?

**Comment by azatsarynnyy** [comment]
> Can a user just run kubectl directly from within the workspace's sidecar's terminal?

Sure, just open a Theia terminal into the sidecar and use CLI

**Comment by mmorhun** [comment]
Also need to implement the command for Openshift case.
