### ISSUE TITLE
[UD] Create a toolbar component

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#15981]
### Is your task related to a problem? Please describe.

In accordance to the design of Get Started page we need to have a toolbar component that re-uses PatternFly 4 toolbar styles and capabilities.

<img width="1156" alt="Screenshot 2020-02-10 at 19 33 35" src="https://user-images.githubusercontent.com/16220722/74175154-e6602c80-4c3d-11ea-857a-955df3bc2190.png">

### Describe the solution you'd like

Create new toolbar component based on PatternFly 4 toolbar component.

### Describe alternatives you've considered

N/A

**Comment by sleshchenko** [comment]
The work is done but not merged yet.
It's closed in the flavor of https://github.com/eclipse/che/issues/16241
