### ISSUE TITLE
[UD] Create masthead component 

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#15980]
### Is your task related to a problem? Please describe.

The design of Get Started page was developed using PatternFly 4 components, styles and typography.
But existing `che-toolbar` component on this page differs from masthead provided in original design doc. Correct spacing and typography should be used in page toolbar.

### Describe the solution you'd like

Create new masthead component that follows PatternFly 4 guidelines. 

### Describe alternatives you've considered

Apply PF4 styles to existing `che-toolbar` component.
Applying correct styles on top of existing components is tiresome and error-prone process. This will result in mess of PatternFly, MaterialDesign and other styles.

**Comment by sleshchenko** [comment]
The work is done but not merged yet.
It's closed in the flavor of https://github.com/eclipse/che/issues/16241
