### ISSUE TITLE
[UD] Create content section component

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#15985]
### Is your task related to a problem? Please describe.

Since the design of Get Started page was developed using PatternFly 4 components, styles and typography, we need to provide a new component to handle a page content in accordance to PF4 guidelines.

### Describe the solution you'd like

Create new content section component.

### Describe alternatives you've considered

Apply PF4 styles to the material design `md-content` component.
Applying correct styles on top of existing widgets is tiresome and error-prone process. This will result in mess of PatternFly, MaterialDesign and other styles.

**Comment by sleshchenko** [comment]
The work is done but not merged yet.
It's closed in the flavor of https://github.com/eclipse/che/issues/16241
