### ISSUE TITLE
Use watch utility to monitor newly created pods

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15986]
### Is your enhancement related to a problem? Please describe.
We constantly make request to get new created pods.
https://github.com/che-incubator/chectl/blob/master/src/api/che.ts#L337
It eventually leads to JS Heap out of memory

### Describe the solution you'd like
It is needed to use  k8s watch utility which creates a only one connection to server.

### A quick-fix solution
Introduce `--no-logs` flags to skip following logs.

### Describe alternatives you've considered
None

**Comment by nickboldt** [comment]
Assuming this is a quick fix, I'm hoping we can get this done for 7.9 as it directly impacts CRW 2.1.

crwctl logs are something that the support team uses heavily so having logging break the ability to use crwctl is a blocker IMHO.
