### ISSUE TITLE
How to get auth token like machineToken

### ISSUE THREAD

**Issue by Alnyli07** [eclipse-che/che#15989]
We want to use che-api so we need to retrieve keycloak.token into the iframe of che-theia.
Is there any way to get auth token into the che-theia ide ?

Thanks

**Comment by skabashnyuk** [comment]
@Alnyli07 thank you for this question.

>Retrieve keycloak.token into the iframe of che-theia 

There is no way to do that.

>We want to use che-api .....
Is there any way to get auth token into the che-theia ide ?

You can use `MACHINE` token that is mounted inside of che-theia container. With that token, you can query `che-api`. See more https://www.eclipse.org/che/docs/che-7/authenticating-users/#machine-token-validation_authenticating-in-a-che-workspace

**Comment by Alnyli07** [comment]
@skabashnyuk  thank you for quick reply.

Some "che-api"s is not permitted with CHE_MACHINE_TOKEN.
For example:
We want to use following organization api;
**GET /organization/find** 

Is there any way to call this api with CHE_MACHINE_TOKEN ?
