### ISSUE TITLE
Dashboard does not displays default editor/plugins state

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15993]
### Describe the bug
At creating a workspace from a stack from dashboard `Che Theia` and `Che machine-exec service` is displayed as disabled. 
But they are provisioned automatically on workspace start phase and it may be a bit surprising.

So, dashboard must somehow displays automatically enabled editor and plugins `Editors`/`Plugins` section.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace from a stack
2. Go to `Plugins` section of dashboard 
3. Pay attention on state of `Che machine-exec` service - it looks like disabled by default
4. Go to IDE and try to create a terminal for a container - it works. 

### Expected behavior
`Plugins` section of dashboard correctly displays state and version of `Che machine-exec` service 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![machine-exec](https://user-images.githubusercontent.com/5676062/74318318-a7d58980-4d85-11ea-87b7-d8d1eccfef5f.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
`Editors`/`Plugins` tabs displays components configured in devfile, while Che Theia and terminal may be provisioned by Che Server. Rephrased the issue a bit

**Comment by sleshchenko** [comment]
This UI is not available on the new dashboard
