### ISSUE TITLE
About dialog in che-theia seems to be broken

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15992]
### Describe the bug

When asking for help/about menu in che-theia:next :

![image](https://user-images.githubusercontent.com/436777/74316090-1cee9200-4d79-11ea-89bd-c252eb85aacd.png)

- lot of spaces
- two OK buttons

something strange is that if you close the dialog and display it again, there is no more extra space.
![image](https://user-images.githubusercontent.com/436777/74317979-a18edf80-4d7c-11ea-8c39-edcd7b8a39ea.png)
but still two OK buttons

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

che.openshift.io with theia next

### Steps to reproduce

Go in about window

### Expected behavior
No empty space + only a single OK button (or one with cancel)

**Comment by skabashnyuk** [comment]
Duplicate https://github.com/eclipse/che/issues/15962 ?

**Comment by benoitf** [comment]
yes sure :)
