### ISSUE TITLE
Devfile editor must be fullscreen

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15996]
### Describe the bug

Devfile editor in dashboard is not resizable. It must change his size when resizing the window.

### Steps to reproduce
1. Open dashboard, go to devfile section
2. Resize browser window

Video demonstrating the problem
https://www.youtube.com/watch?v=ftFG4f7lrtM

**Comment by sleshchenko** [comment]
from https://github.com/eclipse/che/issues/16270
> @SDAdham: Also the devfile editor is also small in the registry when there is a very nice huge white empty space around it!
![image](https://user-images.githubusercontent.com/11182824/76092642-da387680-6013-11ea-9864-87d0568a6ba3.png)

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/14683
