### ISSUE TITLE
Che-theia doesn't inform che-master about activity in workspace when https with self-signed cert is used

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15991]
### Describe the bug
Che-theia doesn't inform che-master about activity in the workspace when https with self-signed cert is used.
I assume the reason is that https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-activity-tracker/src/node/activity-tracker-service.ts#L68-L90 is not covering usecase with a self-signed cert.

### Che version

 - [X] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Setup Che `chectl server:start --platform=crc --installer=operator  --tls --self-signed-cert`
2. Start workspace.
3.  Workspace would be stopped with default timeout no matter what you are doing inside of it.

### Expected behavior
Che-theia should send activity reports to che-master

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl `chectl/0.0.20200211-next.1744186 darwin-x64 node-v10.19.0`
   - [X] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [X] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
 - https://github.com/eclipse/che/issues/15614
 - https://github.com/eclipse/che/issues/15354

**Comment by tsmaeder** [comment]
Not sure how the referenced code relates to self-signed certs. Wouldn't that involve manipulating the trust store of the API client somehow?

**Comment by skabashnyuk** [comment]
@tsmaeder I'm not an expert. I would expect something like this https://github.com/eclipse/che-theia/blob/b5a868dc78a1d94e59810addc20e461a05d832b0/extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts#L330

**Comment by l0rd** [comment]
@azatsarynnyy what's the status of this? You had included it in last sprint but not in current one. That looks critical since most of the install are with https and self signed certs now.

**Comment by azatsarynnyy** [comment]
@l0rd last sprint we investigated it a bit with @skabashnyuk 
We will take it to the next sprint.

**Comment by vitaliy-guliy** [comment]
It's very annoying issue.
