### ISSUE TITLE
[workspace-operator] Adapt controller to support unique ingresses

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15990]
### Describe the bug
To work with Che 7.8 components, the che-workspace operator needs to support creating one ingress per plugin endpoint (even when they point at the same place). Currently, the welcome page in the workspace simply reports a 502 error.

### See also:
Che issue: https://github.com/eclipse/che/issues/15410 and PR: https://github.com/eclipse/che/pull/15432

**Comment by benoitf** [comment]
setting P1 as it's breaking all webviews (when using VS Code extensions) (not only welcome page)

**Comment by amisevsk** [comment]
With the current state of the controller (post-refactoring), this issue is resolved. However, we cannot move to using e.g. webviews, as deploying 7.9.0 and up is blocked by https://github.com/eclipse/che/issues/16568 and oauth-proxy issues.
