### ISSUE TITLE
Error after refreshing the dashboard with active devfile section

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15998]
### Describe the bug

After refreshing the dashboard with opened devfile section I got an error message informing me that my workspace does not exist. But on the background I see another exclamation, informing me that my workpace uses old definition format, which is not compatible anymore. 

### Steps to reproduce

1. Open dashboard, go to workspace sevfile section
2. Refresh the browser

Video demonstrating the problem
https://youtu.be/aRd1ZgJ8eZ8

**Comment by tsmaeder** [comment]
@vitaliy-guliy it is perfectly possible to refresh the browser, it just leads to an error. Can you describe the error, please? I can't really see it well in the video.

**Comment by vitaliy-guliy** [comment]
@tsmaeder done, have updated title and description

**Comment by akurinnoy** [comment]
Fixed in https://github.com/eclipse/che-dashboard/pull/7
