### ISSUE TITLE
`crwctl server:delete` might make openshift instance unusable

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16000]
I've run `crwctl` having in mind that kube context points to my local minishift instance, but is started remove Che Server from public OpenShift 4.3 instance:

```bash
$ crwctl server:delete
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ Delete the CR eclipse-che of type checlusters.org.eclipse.che...CR not found
  ✔ Delete CRD checlusters.org.eclipse.che...OK
  ✔ Delete role binding che-operator...OK
  ✔ Delete role che-operator...OK
  ✔ Delete cluster role binding che-operator...OK
  ⠦ Delete cluster role che-operator
    Delete server and workspace rolebindings
    Delete service accounts che-operator
    Delete PVC che-operator
```

CRD `checlusters.org.eclipse.che` started to be in terminating state and it isn't possible to deploy che anymore
```
TerminatingTrue
Feb 12, 2020 12:02 am
InstanceDeletionInProgressCustomResource deletion is in progress
```

```bash
 ✔ Verify OpenShift API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing CodeReady Workspaces instance
    ✔ Verify if CodeReady Workspaces is deployed into namespace "abcrw5"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
Eclipse Che logs will be available in '/tmp/crwctl-logs/1581502912228'
 ›   Warning: CodeReady Workspaces will be deployed in Multi-User mode since Configured 'operator' installer which support only such.
  ❯ 🏃  Running the CodeReady Workspaces Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (abcrw5)...done.
    ✔ Create ServiceAccount codeready-operator in namespace abcrw5...done.
    ✔ Create Role codeready-operator in namespace abcrw5...done.
    ✔ Create ClusterRole codeready-operator...It already exists.
    ✔ Create RoleBinding codeready-operator in namespace abcrw5...done.
    ✔ Create ClusterRoleBinding codeready-operator...It already exists.
    ✔ Create CRD checlusters.org.eclipse.che...It already exists.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment codeready-operator in namespace abcrw5...done.
    ✖ Create CodeReady Workspaces Cluster codeready-workspaces in namespace abcrw5
      → create not allowed while custom resource definition is terminating
Error: create not allowed while custom resource definition is terminating
    at KubeHelper.wrapK8sClientError (~/projects/codeready-workspaces-chectl/src/api/kube.ts:1319:74)
    at KubeHelper.<anonymous> (~/projects/codeready-workspaces-chectl/src/api/kube.ts:1004:18)
    at Generator.throw (<anonymous>)
    at rejected (~/projects/codeready-workspaces-chectl/src/api/kube.ts:15:65)
```

**Comment by sleshchenko** [comment]
1.

> having in mind that kube context points to my local minishift instance, but is started remove Che Server from public OpenShift 4.3 instance

I would suggest asking user confirmation before removing Server. It's what I already used in chectl during update. It would then looks like the following:
```
You're going to remove Che/CodeReady Workspace resources on kubectxName (kubectxURL). If you want to continue - press Y
```

2. 
```
    ✖ Create CodeReady Workspaces Cluster codeready-workspaces in namespace abcrw5
      → create not allowed while custom resource definition is terminating
Error: create not allowed while custom resource definition is terminating
```
It's not an issue of crwctl but it's OpenShift cluster issue... I face the same on minishift sometimes.
I do `oc delete project` and project is terminating forever...
Something block project deletion. Last time I faced it on public OpenShift cluster and as in your case, my Che fails to start because of permissions lack (we already investigated)... Maybe Che operator pod blocks namespace deletion in that case? 
But I believe it definitely is not chectl/crwctl issue.

**Comment by dmytro-ndp** [comment]
Next command removes terminating CRD:
```
oc patch customresourcedefinition/checlusters.org.eclipse.che -p '{ "metadata": { "finalizers": null }}' --type merge
```
@rkratky: it may worth to be documented, IMHO

**Comment by tolusha** [comment]
I've added a confirmation to delete Che Server, that's why I set priority to p2

**Comment by sleshchenko** [comment]
> I've added a confirmation to delete Che Server, that's why I set priority to p2

I faced the same issue and confirmation in my case does not help at all. I wanted to delete my Che Server but was not expecting that I won't be redeployed it anymore... I believe the situation with a finalizer that hangs forever should be investigated more.

> oc patch customresourcedefinition/checlusters.org.eclipse.che -p '{ "metadata": { "finalizers": null }}' --type merge

helps me to fix OpenShift instance, but it's only I know about it for most of users it's not clear at all

**Comment by tolusha** [comment]
Fixed by https://github.com/che-incubator/chectl/pull/828
