### ISSUE TITLE
Change default pvcStrategy using chectl with operator

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16007]
### Describe the bug
Che installed by chectl using the operator in default configuration uses `pvcStrategy: common`, but the PV has access mode set to `ReadWriteOnce`. This combination results in problems when multiple workspaces are started. It can happen that one workspace starts on one node, another workspace starts in another node - and then, because of ReadWriteOnce access, only the first one can access the PV. The solution could be to change the default `pvcStrategy` from `common` to `per-workspace`. 

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Deploy Che by chectl using operator, e.g. `chectl server:start -a operator -p openshift `
2. Create two users
3. Start workspace with one user
4. Start workspace with the second user

### Expected behavior
From time to time workspace starts, but usually, it fails with the message `Multi-Attach error for volume <pvc> Volume is already used by pod(s) <pod_id>`.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

**Comment by tolusha** [comment]
Will be done as part of 
https://github.com/eclipse/che/issues/15684

**Comment by tolusha** [comment]
@Katka92 
Pls check the description of PR.
https://github.com/che-incubator/chectl/pull/508
