### ISSUE TITLE
Add an ability to add public key certificate to Java trust store

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#16002]
### Is your task related to a problem? Please describe.

When handling an HTTP request from resources which root certificate authority is not recognised, error occurs:
```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
### Describe the solution you'd like

We need to have an ability to configure public key certificates. See http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html
### Additional context

Is needed for https://github.com/eclipse/che/pull/15963. In this PR a request from OpenShift is received to `<api url>/oauth/callback`. It is possible to configure such certificate with the help of `CHE_SELF__SIGNED__CERT` but it can be used for configuring self signed certificates.

**Comment by tsmaeder** [comment]
This is the trust store of WS master, right @vinokurig ?

**Comment by vinokurig** [comment]
Yes

**Comment by ericwill** [comment]
Is this one fixed @vinokurig? If so please close it.
