### ISSUE TITLE
I want set a login

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#1601]
I want set a login

Login to attach the set to the root(/) of the Tomcat server.xml, web.xml and tomcat-user.xml .
but error load.(can not load api)

So set in the web.xml to the '/dashboard' but does not work.

Login using tomcat want to know how to operate the che.

**Comment by TylerJewell** [comment]
Hi!  This is not a configuration that is currently supported and not advised as it would not be secure.  We are considering adding in proper filters in a future release.
