### ISSUE TITLE
[chectl] workspace:inject no more finding default workspace pod

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#16019]
### Describe the bug
```
[apupier@linux ~]$ chectl workspace:inject -k
  ✔ Verify if namespace che exists
  ✖ Verify if the workspaces is running
    → No workspace pod is found
    Injecting configurations
 ›   Error: No workspace pod is found
```

### Che version

 - [x] latest 7.9.0-SNASPHOT
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace and wait that it has been started
2. call chectl workspace:inject -k from host
3. See error

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tolusha** [comment]
@apupier 
In which namespace the workspace is run?

**Comment by apupier** [comment]
> In which namespace the workspace is run?

it should be in `che` namespace as I installed with `chectl server:start -p minikube`

**Comment by tolusha** [comment]
yeap, but could you double check pls?

**Comment by apupier** [comment]
I have 2 namespaces available:
che and che-che

in deployments, there is a "workspacexxxx"  for `che-che`, looks alike the `che` is containing "only" `devfile-registry-xxx`, `plugin-registry-xxx` and a `che-xxxx`

**Comment by apupier** [comment]
```
[apupier@linux ~]$ chectl workspace:inject -k -n che-che
  ✔ Verify if namespace che-che exists
  ✔ Verify if the workspaces is running
  ✔ Injecting configurations
```

looks alike now the namespace by defautl to look at has changed and is `che-che` instead of `che`

**Comment by tolusha** [comment]
yes, workspace goes in a different namspace.
Can we close the issue?

**Comment by apupier** [comment]
I think we need to keep it open and adjust the behavior of chectl workspace:inject to match the new default behavior

**Comment by tolusha** [comment]
In general way `chectl` doesn't know where workspace is created

**Comment by tolusha** [comment]
But I do agree the `chectl` might be smarter

**Comment by apupier** [comment]
why the severity is only P2 although it is a regression?

**Comment by tolusha** [comment]
https://issues.redhat.com/browse/CRW-803
