### ISSUE TITLE
E2E tests failed on "Language server validation" step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16017]
### Describe the bug
1. Happy path E2E tests failed on "_Java LS initialization_" step:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/904/console
```
        ▼ Ide.waitStatusBarContains "Starting Java Language Server"
Known flakiness has occurred https://github.com/eclipse/che/issues/14944
        ▼ DriverHelper.reloadPage
        ▼ Ide.waitStatusBarContains "Starting Java Language Server"
    1) Java LS initialization

  3 passing (6m)
  1 failing

  1) Language server validation
       Java LS initialization:
     TimeoutError: Waiting for element to be located By(css selector, div[id='theia-statusBar'])
Wait timed out after 180002ms
```
![screenshot-Java_LS_initialization](https://user-images.githubusercontent.com/1197777/74417797-049d7680-4e50-11ea-8b33-4b92c45bd49e.png)

Screencast: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/904/artifact/tests/e2e/report/executionScreencast/

2. Devfile E2E tests failed on "_LS initialization_" and "_Suggestion invoking_" steps: 
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/905/console

- Vert.x "_LS initialization_" screenshot
![screenshot-LS_initialization](https://user-images.githubusercontent.com/1197777/74427295-7b8e3b80-4e5f-11ea-967d-6c2c1a926779.png)

- Vert.x "_Suggestion invoking_" screenshot
![screenshot-Suggestion_invoking](https://user-images.githubusercontent.com/1197777/74427492-e3448680-4e5f-11ea-8636-fa079320c0b7.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
- [Happy path tests script](https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts)
- [Devfile E2E tests scripts](https://github.com/eclipse/che/tree/master/tests/e2e/tests/devfiles)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next with operator installer 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by tsmaeder** [comment]
For what it's worth, Java support seems to start just fine on nightly.

**Comment by dmytro-ndp** [comment]
The possible reason are changes in [che-plugin-registry](https://github.com/eclipse/che-plugin-registry/commit/7dc054c5527c0eb9ae9696c890bd619f6710d1df).

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/16031
