### ISSUE TITLE
download size

### ISSUE THREAD

**Issue by bardware** [eclipse-che/che#1602]
Hi,

the  [instruction](https://eclipse-che.readme.io/docs/usage-vagrant) says: `Vagrant will download a Linux image that contains Docker, download the Che Docker image` 
Can you say how big that download will be? More like 100 MB; more like 1 GB or more?

**Comment by ddementieva** [comment]
Vagrant script will pull two images about 500+ MB each: boxcutter/centos72-docker and codenvy/che.

**Comment by ghost** [comment]
@bardware codenvy/che is a Docker image, boxcutter/centos72-docker is a VBox image.

**Comment by bardware** [comment]
thanks alot
