### ISSUE TITLE
Dashboard should warn the user if he has chosen unstable version of Che-Theia editor

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16028]
### Is your task related to a problem? Please describe.

On che.openshift.io the developer might choose unstable ( che-theia:next ) version of the editor.
Sometimes this can cause his editor to work with errors.

Today i encountered the problem that the plugins in my che-theia didn't work at all. The reasoun could be that I used the newest version of Che-Theia, but Che-server and other services still have older versions.

This screenshot demonstrates how che-theia:next looks on che.openshift.io

![Screenshot from 2020-02-13 12-28-24](https://user-images.githubusercontent.com/1655894/74442377-1431b500-4e7a-11ea-88ee-e461c027151d.png)

### Describe the solution you'd like

Display a warning message on top of the dashboard when the next version of che-theia is selected.

**Comment by tsmaeder** [comment]
Change kind to "enhancement". It's really a feature request to be planned.

**Comment by RomanNikitenko** [comment]
I faced with the same issue: I select `next` version of `theia-ide` editor on `che.openshift.io`, but it looks like not working at all:
- tasks are absent
- the `Workspace` panel is empty
- language support for typescript is absent
