### ISSUE TITLE
Version of theia-ide editor is displayed incorrectly

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#16022]
### Describe the bug
I think `Editors` section of dashboard displays incorrect version of `theia-ide` editor.
Please see steps to reproduce and screenshots.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create and start a workspace from dashboard (I used `NodeJS Express Web Application` stack)
2. Go to `Help` => `About` dialog, see the versions of `theia` and `che-theia`
3. Come back to dashboard to `Editors` section. It displays that version of `theia-ide` is `latest`.

For my case `che-theia:latest` was built 14 days ago 
At the same time my assembly contains the latest changes from `theia` and `che-theia` repo, so I guess the actual version is `next` and `Editors` section of dashboard displays version of `theia-ide` editor incorrectly.

### Expected behavior
`Editors` section of dashboard displays version of `theia-ide` editor correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![theia-ide_vers](https://user-images.githubusercontent.com/5676062/74430197-1c332a00-4e65-11ea-85c4-a48f1eac1df8.png)

![еее](https://user-images.githubusercontent.com/5676062/74430223-27865580-4e65-11ea-9d02-dc0449ba1cf6.png)

![che-theia_vers](https://user-images.githubusercontent.com/5676062/74429447-a5e1f800-4e63-11ea-9f5c-54e23e054798.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
@RomanNikitenko what would the correct way to display the version be, in your opinion?

**Comment by RomanNikitenko** [comment]
For my case `Editors` section of dashboard displays `latest` version of `theia-ide` editor.
But actually `next` version of `theia-ide` editor is used.

So,  `Editors` section should display **next** instead of **latest**

**Comment by tsmaeder** [comment]
To rephrase: the drop down in the first screenshot next to enabled  "theia-ide" item displays "latest", but it should display "next".
How do you know you're running the image tagged "next"?

**Comment by tsmaeder** [comment]
Tagging this P1 because it might be a support nightmare trying to debug the wrong version of the IDE.

**Comment by RomanNikitenko** [comment]
@tsmaeder 
> To rephrase: the drop down in the first screenshot next to enabled "theia-ide" item displays "latest", but it should display "next".

Exactly!

> How do you know you're running the image tagged "next"?

I think so, because:
- `che-theia:latest` was built 14 days ago
- but my assembly contains the latest commits from `theia` and `che-theia` repo
