### ISSUE TITLE
Dynamic web application

### ISSUE THREAD

**Issue by betarella** [eclipse-che/che#16038]
Hi, i don't understand how I can create a dynamic web project for a simple web application.

I have founded only example based on Springboot framework.

 Can you help me?

**Comment by ibuziuk** [comment]
@betarella hi, wdym by `dynamic web project`? Please, also take a look at the getting-started templates - https://www.eclipse.org/che/getting-started/cloud/

**Comment by l0rd** [comment]
Closing this issue since with the available information there is not much we can do about it. @betarella feel free to reopen if you can provide more details on the kind of application you would like to see supported.
