### ISSUE TITLE
Automate pushing Che releases to Maven Central

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16043]
### Is your enhancement related to a problem? Please describe.
Today, releases to Maven Central require manual steps to approve/release content.

But there's a nexus mojo that can automate this, as we did for JBoss Tools pushing into the JBoss Nexus repo.

### Describe the solution you'd like

Use a Jenkins job to orchestrate the build & release to Maven Central.

```
pom=${WORKSPACE}/sources/parent/pom.xml

pomVersion=$(grep "<version>" ${pom} | head -1 | sed -e "s#.*<version>\(.\+\)</version>.*#\1#")
MVN="${COMMON_TOOLS}${SEP}maven-3.5.2/bin/mvn -Dmaven.repo.local=${WORKSPACE}/.repository/"
if [[ ${pomVersion} == *"-SNAPSHOT" ]]; then 
  ${MVN} deploy -U -B -f ${pom}
else
  ${MVN} clean deploy -DskipRemoteStaging=true -U -B -f ${pom} \
    -DstagingDescription="[${JOB_NAME} ${BUILD_TIMESTAMP} ${BUILD_NUMBER}] :: ${pomVersion} :: deploy to local" 
  ${MVN} nexus-staging:deploy-staged -f ${pom} \
    -DstagingDescription="[${JOB_NAME} ${BUILD_TIMESTAMP} ${BUILD_NUMBER}] :: ${pomVersion} :: deploy to stage + close"
  ${MVN} nexus-staging:release -f ${pom} \
    -DstagingDescription="[${JOB_NAME} ${BUILD_TIMESTAMP} ${BUILD_NUMBER}] :: ${pomVersion} :: release"
fi
```  

(full job here: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jbosstools-releng/job/jbosstools-build.parent_master/configure-readonly/)

This requires setting up the nexus-staging plugin in the parent pom, as was done here:

https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L520-L532

There may also be some Jenkins master configuration (`settings.xml`) required to authenticate with the repo  as an approved user -- not sure what's required there. But at the very least, if we can't do a `nexus-staging:release`, we should be able to `nexus-staging:deploy-staged` to get the bits up into Maven automatically, then only need to do one manual step in Nexus's UI.

### Additional context

This is a followup exercise pursuant to streamlining and automating the full Che release process. The first step was [getting RELEASE.md files for all the repos](https://github.com/eclipse/che/issues/15506).

See also:

* https://github.com/eclipse/che/blob/master/RELEASE.md

**Comment by nickboldt** [comment]
Too busy in 7.10. Did not get information from @vparfonov about how to get access to pushing to Maven Central. Need that before we can proceed.

**Comment by nickboldt** [comment]
After discussion today, looks like we can improve https://github.com/eclipse/che/blob/master/.ci/cico_common.sh#L87-L96 to add the "if not snapshot then deploy, nexus-staging:deploy-staged, nexus-staging:release into the mvn_deploy() step.

We should also fix https://github.com/eclipse/che/blob/master/.ci/cico_common.sh#L107-L110 to use the devstudio-release bot with email address crw-bots@redhat.com

And we need to stick this block https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L520-L532 into the Che parent pom:

```
			<plugin>
				<groupId>org.sonatype.plugins</groupId>
				<artifactId>nexus-staging-maven-plugin</artifactId>
				<version>1.6.7</version>
				<extensions>true</extensions>
				<configuration>
					<!-- The Base URL of Nexus instance where we want to stage -->
					<nexusUrl>https://oss.sonatype.org/</nexusUrl>
					<!-- The server "id" element from settings to use authentication from -->
					<serverId>ossrh</serverId>
				</configuration>
			</plugin>
		</plugins>
```

into https://github.com/eclipse/che-parent/blob/master/pom.xml

**Comment by mkuznyetsov** [comment]
the nexus-staging plugin is now in use. Now automatic closure of repository is enabled (but not automatic release), which would be done soon, probably by 13.0 release

**Comment by nickboldt** [comment]
Slip turning on the automated release to MC to the 7.14 release.

**Comment by nickboldt** [comment]
From Mykhailo:

> After each rework of the script flow, to avoid committing bad artifacts to nexus
> even though I know how to do a respin in that case
> it feels like it takes more time to trigger and wait for the whole respin, than to go on nexus, verify and push 2 buttons
> Like, I'd personally prefer to not do it AGAIN for 7.15, since I'll release parent again, and there will be some changes related to version bumping again

So we slip to 7.16.

**Comment by mkuznyetsov** [comment]
Automated release on nexus for Che Server artifacts has been implemented

**Comment by nickboldt** [comment]
```
# if true, automatically release che-server on Nexus. If false, must be released manually on Nexus interface 
AUTORELEASE_ON_NEXUS=false
```
 -- https://github.com/eclipse/che-release/blob/release/VERSION#L5-L6

And yet, it's still disabled. Reopening issue. Why aren't we using the automation?

**Comment by benoitf** [comment]
@nickboldt you should move the milestone version

**Comment by mkuznyetsov** [comment]
Autorelease on nexus is being used by default now
