### ISSUE TITLE
microk8s kubectl E_REQUISITE_NOT_FOUND

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#16048]
### Describe the bug
chectl fails `✖ Verify if kubectl is installed` with E_REQUISITE_NOT_FOUND

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

**chectl/7.8.0 linux-x64 node-v10.18.1**

### Steps to reproduce

- Install microk8s via snap store `sudo snap install microk8s --classic --channel=1.17/stable`
- Install chectl as instructed on the [documents](https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/) `bash <(curl -sL  https://www.eclipse.org/che/chectl/)`
- Implement workaround 1 from [here](https://github.com/eclipse/che/issues/14455#issuecomment-561439019) `microk8s.config | cat - > $HOME/.kube/config` After encountering connection refused
- `chectl server:start -m -p microk8s -a helm`

### Expected behavior
Chectl uses the microk8s.kubectl kubectl.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ x ] other: microk8s *v1.17.2*

### Installation method
   - [ x ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

It looks like chectl uses a repository called `[command-exists](https://github.com/mathisonian/command-exists/blob/master/lib/command-exists.js). Looking at the code, it looks like command-exists simply sends commands to the command line. Chectl's [implementation](https://github.com/che-incubator/chectl/blob/72402037ae802e794c03a12c778932b798a29ab5/src/tasks/platforms/microk8s.ts#L27) seems to only use command-exists.

So, I looked up how to use bash-aliases in a npm script and came across this stackoverflow solution https://askubuntu.com/a/98791 and implemented it like in my .bashrc : 

EDIT: This was the original. Probably led to some of my problems. Look below for the correct addition to .bashrc

```bash
kubectl(){
    minikube.kubectl "$@"
}
export -f kubectl
````

which still did not work

Edit: Should have been

```bash
kubectl(){
    microk8s.kubectl "$@"
}
export -f kubectl
```

**Comment by gnoejuan** [comment]
Update: installed kubectl through snap: `snap install kubectl --classic`

Now I'm ran into a missing helm requirement, even though microk8s has it. 

![image](https://user-images.githubusercontent.com/4656027/74614215-9d93f200-50db-11ea-95ea-119b1bd8c6e3.png)

**Comment by tolusha** [comment]
@gnoejuan 
1. Install helm on machine where `chectl` is installed
or
2. Use `--installer=operator`

**Comment by gnoejuan** [comment]
-a operator did the fix. Thank you very much!

hmmm after rebooting, i had to "reimplement workaround 1".

**Comment by gnoejuan** [comment]
In case somebody came across this thread from google: 

```bash
kubectl(){
    minikube.kubectl "$@"
}
export -f kubectl
```

should actually be: 

```bash
kubectl(){
    microk8s.kubectl "$@"
}
export -f kubectl
```

Not sure if I would have ran into the `helm` issue, but this fixed a issue where chectl was hanging on 

```
    ✔ Eclipse Che pod bootstrap
      -> scheduling...done.
```
