### ISSUE TITLE
[UD] "Dashboard" menu item is not needed and should be removed

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16040]
### Is your enhancement related to a problem? Please describe.
"Dashboard" menu item should be removed since it does not have any real value. All it does is redirection to "Get Started" if there are no workspaces or to "Workspaces" if there are some workspaces

![image](https://user-images.githubusercontent.com/1461122/74530434-4c90cc00-4f2a-11ea-86d2-7e65d86299be.png)

### Describe the solution you'd like
Removal of the "Dashboard" menu item - default page should be "Get Started"

**Comment by akurinnoy** [comment]
>  All it does is redirection [...] to "Workspaces" if there are some workspaces

@ibuziuk I guess it was the Dashboard page. If there are a few workspaces it looks similar to the Workspaces page, but only up to five recent are listed there. 

I'm +1 for getting rid of Dashboard page in favour of Get Started, however.

**Comment by ibuziuk** [comment]
> guess it was the Dashboard page. If there are a few workspaces it looks similar to the Workspaces page, but only up to five recent are listed there.

Thanks for clarification, for me it still sounds like the "Dashboard" page is not needed and maybe we could simply enable user-friendly filtering / pagination on the "Workspaces" page

**Comment by sleshchenko** [comment]
Will be done in the scope of https://github.com/eclipse/che/issues/15662 after implementing new workflow described there
