### ISSUE TITLE
Script release of che-parent, che-doc, che-server

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16045]
### Is your task related to a problem? Please describe.

Releasing che-parent to RC (and release) is [done manually](https://github.com/eclipse/che-parent/blob/master/RELEASE.md) today.

But the steps are [documented](https://github.com/eclipse/che-parent/blob/master/RELEASE.md), so we should be able to adapt a script like these:

* https://github.com/eclipse/che-plugin-broker/blob/master/make-release.sh
* https://github.com/eclipse/che-devfile-registry/blob/master/make-release.sh

such that we can use if for the release of che-parent 7.9.0.

### Describe the solution you'd like
* Script the release. 
* [Perform the release](https://github.com/eclipse/che/issues/16008) using the script.
* Update the [release issue template](https://raw.githubusercontent.com/eclipse/che/master/RELEASE.md).

Later we can attempt to [script the nexus release steps](https://github.com/eclipse/che/issues/16043) too. 

### Additional context

This is a followup task to https://github.com/eclipse/che/issues/15506

**Comment by nickboldt** [comment]
PRs:

https://github.com/eclipse/che-parent/pull/154 
https://github.com/eclipse/che-docs/pull/1087
https://github.com/eclipse/che/pulls/ ?

once those are merged we can update https://github.com/eclipse/che/pull/16037 to add links to those new scripts.

**Comment by nickboldt** [comment]
What's left to do here, @mkuznyetsov ? please list remaining TODOs so we can track 'em.

**Comment by mkuznyetsov** [comment]
I'm making some fixes rn to the script, as some parts of it didn't really work with the "bugfix" release usecase (like upgrading image tags), should be done by tomorrow in eclipse/che PR

**Comment by skabashnyuk** [comment]
FYI. New repositories has been added.
 - https://github.com/eclipse/che-workspace-loader
- https://github.com/eclipse/che-dashboard

**Comment by nickboldt** [comment]
Closing since we've now done 2 releases with it. @mkuznyetsov please close your issues when they're done, or comment on them at least once a week with status.
