### ISSUE TITLE
Upgrade forked vscode-git to the latest version

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16041]
### Is your task related to a problem? Please describe.
We are currently using a forked version of vs-code git that lives [here](https://github.com/che-incubator/vscode-git). It's out of date and should be updated so we can get some features and updates for free.

### Describe the solution you'd like
Rebase on the latest release of vs-code git.

**Comment by vinokurig** [comment]
Depends on https://github.com/eclipse-theia/theia/issues/7683

**Comment by vinokurig** [comment]
Depends on https://github.com/eclipse-theia/theia/issues/7577

**Comment by vinokurig** [comment]
Depends on https://github.com/eclipse-theia/theia/issues/7946

**Comment by ericwill** [comment]
Fixed by eclipse/che-theia#857
