### ISSUE TITLE
org.eclipse.che.ide.websocket.WebSocketException: WebSocket is not opened.

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#1604]
I installed Eclipse Che locally using Virtual Box and Vagrant according the tutorial. It goes OK, but when I try to run some command from IDE, I have the following error in browser console: 
`ERROR        (org.eclipse.che.ide.extension.machine.client.outputspanel.console.CommandOutputConsolePresenter): 
       org.eclipse.che.ide.websocket.WebSocketException: WebSocket is not opened.
           at Unknown.Yj(_app-0.js)
             at Unknown.qw(_app-0.js)
           at Unknown.uw(_app-0.js)
             at Unknown.DEc(_app-0.js)
    at Unknown.X8(_app-0.js)
    at Unknown.W4(_app-0.js)
    at Unknown.pdc(_app-0.js)
    at Unknown.kac(_app-0.js)
    at Unknown.gp(_app-0.js)
    at Unknown.Pz/<(_app-0.js)
    at Unknown.anonymous(Unknown)`
and nothing happened after it. Moreover there are some troubles during creation the new project within the new workspace: the process freezes at "Starting workspace runtime".

**Comment by ddementieva** [comment]
Are you trying to run commands created in the CMD drop-down? 

Also what browser do you use?

**Comment by zatsepinvl** [comment]
1) Yes
2) I have the same behavior in both Mozilla and Chrome (latest ver.). In console only: "command: mvn -f clean install" if it's default build command (within "console-java-sample" project)

**Comment by ghost** [comment]
@zatsepinvl what is your browser?

**Comment by zatsepinvl** [comment]
I have the same behavior in both Mozilla and Chrome (latest ver.)

**Comment by ddementieva** [comment]
Are you behind a firewall? Can you try to reproduce this problem with a different connection?

**Comment by zatsepinvl** [comment]
Problem described above appears only on the office computer and nothing wrong at home. Yes, I guess I'm behind the firewall, but is it important when Che was installed locally?

**Comment by TylerJewell** [comment]
Che depends upon Docker images to create the workspaces.  You can use docker pull <image-name> to get those images from dockerhub locally onto your computer first, and then che will be ok.

**Comment by zatsepinvl** [comment]
I have the same problem on http://beta.codenvy.com . Thus, I think, the main reason in the network configuration/connection, but I can not find out what is wrong.

**Comment by ghost** [comment]
Can you run some websocket tests like https://websocketstest.com/?

**Comment by zatsepinvl** [comment]
I've run (https://websocketstest.com and  https://www.websocket.org/echo.html), everything is OK.

**Comment by ghost** [comment]
Can you see errors in browser dev console? Network - > WS tab. Maybe you can see the error code.

**Comment by zatsepinvl** [comment]
Everything look good in WS tab and there are no errors there. Only one error from JavaScript described above.

**Comment by ghost** [comment]
Can you perhaps ask your office sysadmin on network restrictions that you have?

**Comment by zatsepinvl** [comment]
I've done it firstly and now it's in process. I hope you can say me what the possible network restrictions are? The same problem appears locally and on remote demo and it's confused me. Moreover, antivirus firewalls' log is clean.

**Comment by ghost** [comment]
Every network setup is individual, so there are hardly any recommendations here. Are you certain there are no hints in browser dev console?

I'll pass this over to our admin team.

**Comment by zatsepinvl** [comment]
I'am certain there are no hints in browser dev console.

**Comment by ghost** [comment]
@zatsepinvl can you remove logs at /tomcat/logs/ and then run Che with `-l:DEBUG`. Share new logs, maybe there are some hints there.

**Comment by zatsepinvl** [comment]
There is nothing there. Only the same error in the browser console. Can it be connected with the debug problem (using 192.168.99.*) from here: https://github.com/eclipse/che/issues/1880

**Comment by ghost** [comment]
@zatsepinvl logs should be at `/tomcat/logs`.

Yes, these issues can be related since there are some network restrictions that prevent Che from properly working.

**Comment by zatsepinvl** [comment]
Problem was detected and solved by adding "locahost/*" into Kaspersky's (Endpoint Security) Web Anti-Virus Trusted URLs list. But I can't understand it. Can you give some explanation or theory?

**Comment by TylerJewell** [comment]
That entry into your anti virus is probably a type of no-proxy entry which tells the virus router to ignore certain traffic flowing over that host name.  When it was ignoring it, it may have been blocking essential traffic we depend upon.
