### ISSUE TITLE
It's not possible to start workspace in Single-User Che anymore

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16053]
### Describe the bug
It's not possible to start workspace in Single-User Che anymore

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy the nightly Che where Theia and machine exec are reconfigured not to listen to public network interface https://github.com/eclipse/che-plugin-registry/pull/378.
2. Create and start any workspace with Theia.
**Expected**: Workspace is started and it's possible to open a terminal
**Actual**: Workspace fails to start because of Theia unavailability:
![Screenshot_20200217_133632](https://user-images.githubusercontent.com/5887312/74650494-8bbd5800-518a-11ea-8026-1029d7aa728a.png)

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] I've specified where I tested but in fact it should not matter

### Installation method
   - [x] chectl (`chectl server:start --installer=helm --platform=minikube`)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by nickboldt** [comment]
I thought this was a known not-to-be-fixed issue in 7.9.0, but the thing that caused it will be reverted in master branch so it's not broken there.

See https://github.com/eclipse/che/issues/15651 and https://issues.redhat.com/browse/CRW-587?focusedCommentId=13975218&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13975218

**Comment by skabashnyuk** [comment]
@nickboldt you are right. Is there anything wrong?

**Comment by metlos** [comment]
#16227, https://github.com/eclipse/che-plugin-registry/pull/417 and https://github.com/eclipse/che-jwtproxy/pull/22 are merged so this should be complete.
