### ISSUE TITLE
About dialog is broken

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16059]
### Describe the bug
In dialog About there is a weird description and two OK buttons.

![Screenshot from 2020-02-18 09-28-55](https://user-images.githubusercontent.com/29278800/74717719-2bcdbc80-5231-11ea-99b9-de81d0083d0d.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create and open any workspace (I've tried with Java Maven)
2. Go to Help -> About

### Expected behavior
The dialog About should look like this:
![Screenshot from 2020-02-18 09-11-17](https://user-images.githubusercontent.com/29278800/74717711-27a19f00-5231-11ea-9325-c9fa4fd04f8f.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
chectl server:start -a operator -p openshift -n rhopp-che -s --self-signed-cert
chectl version: chectl/0.0.20200214-next.75e7903 linux-x64 node-v10.19.0
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
dup of https://github.com/eclipse/che/issues/15962
