### ISSUE TITLE
Improve Git workflow

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#1605]
I can hardly commit via the command line because my user/email and SSH keys are not set.

Using the web interface of Che I'm constantly committing without including all the files or changes.

Current:
- Git > Add to Index... only marks for addition without adding changes
- Git > Commit... no matter what I check there it seems to also no add new/changed files or it's weird and I've no idea what it'll actually commit.

Expected:
- Git > Commit... shows a list of files to commit with a checkbox next to each. Should check by default all modified or deleted files. Pretty much like SmartGit or Git Extensions.

**Comment by wernight** [comment]
I'd suggest the **commit** UI to look like:

![image](https://cloud.githubusercontent.com/assets/145667/19237670/6d464fb4-8efe-11e6-964f-a3b77a82ffab.png)

or 

![image](https://cloud.githubusercontent.com/assets/145667/19237629/3a4863b8-8efe-11e6-974d-b4b13d367be9.png)

And a simple **sync** button doing basically:

```
$ git pull --rebase && git push
```

This would cover the basic uses and make it really simple. More advanced users (myself included) would prefer the CLI, but the UI is really critical for less technical people.

**Comment by wernight** [comment]
Noting also that [Codebox](https://github.com/CodeboxIDE/codebox) (open source) does have a UI pretty close to my suggestions here:

![image](https://cloud.githubusercontent.com/assets/145667/19237792/df72dc06-8efe-11e6-8f63-5b3f35f1ee0b.png)

![image](https://cloud.githubusercontent.com/assets/145667/19237796/e6f73bd4-8efe-11e6-811b-548d0e2f4a29.png)

**Comment by wernight** [comment]
## Current steps to perform a single commit:

 1. For each file you changed, click menu Git > Add to Index... (why `...` on this menu item?! it shows no popup)
 2. Click menu Git > Status because of course you forgot to add some files (I don't even know how to add "deleted" fiels)
 3. Menu Git > Commit selected... (which seems to possibly in a weird world commit the currently opened file with some options)
 4. Check "Commit all files in the project" (yea because you added them to the index you still need this else it'll unstage them WTF?!)
 5. If you checked "Amend previous commit" cancel, retrieve the previous commit message and repeat.
 6. Click menu Git > Remote > Pull...
 7. Click Pull (if you even want to rebase, which many people do, you cannot)
 8. Click menu Git > Remove > Push...
 9. Click Push

Nearly all options are confusing and `...` are inconsistent with the behavior.

People want to commit all their changes by default, and review them before doing so. The UI of other tools (suggested above) provides that. Most users are completely confused by the "staging" aspect of Git, so that should clearly be more a hidden part (like the GitHub Git tool for Windows does in its pretty good UI).

The UI should be good at doing common operations simply. CLI would be used by advanced users (even though it requires re-creating credentials). So this should be like:

 1. Git > Commit > Uncheck files you don't want to commit.
 2. Git > Sync (doing a `git pull --rebase && git push`)

## Confusing "current" file(s?)

The other very confusing part is that most operations like Git > History work on the currently selected file which isn't a single thing. If you selected FOO file in the explorer it's set to that. If you then select the tab of file BAR, even though the file explorer still has FOO selected, the Git operations will act on file BAR. So it may be the active tab **or** the selected item in the file explorer. Some options like Git > Status aren't dependent on the "current" file.

As a result I don't even know what I'm committing.

It'd change the behavior so that:

 - Right clicks from file explorer > Git acts only on those file (as current)
 - Right click on an opened file tab content > Git acts only on those file (as current)
 - Ctrl + Shift + A may have a "Git history of current tab"
 - Menu Git should act on the entire repository

**Comment by TylerJewell** [comment]
@slemeur - *bump*

**Comment by slemeur** [comment]
I agree with the overall UX problems with the git plugin. We are oftenly discussing this issue but have not prioritized a real revamp of the plugin. 

We are starting in the current sprint to improve the git commit window:  https://github.com/eclipse/che/issues/3614

**Comment by iamslite** [comment]
Having a consistent interface in which you know exactly what is going to be committed (rather than the pot luck you get at the moment) should be the highest priority, over any redesigned UX. Specifically, unless something is actually checked in the "Commit to repository" window changes should not be being made to the index. You have options to add updates, add any files you have selected and commit all, which allow you to quickly add things to the index, so these should be being respected. If none of these are checked then just commit the changes currently in the index.

**Comment by slemeur** [comment]
Hi @wernight and @iamslite. As discussed we have published a specification for a better Git integration in the next version of Che.
Please give a look at the issue #5128 and share your feedbacks.
