### ISSUE TITLE
promote builtin-related issues on plugins to P1

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#16057]
as mentioned in the last call 
https://docs.google.com/document/d/1duuavOXVAJNbzU8nIltraDKx5YH2Z34Qwx7AeLnhhzU/edit

this issue is to request the P1 priority to issues about new ms-vscode plugins to plug-registry when their implementation requieres a missing (due to being conflicting or unimplemented) builtin in theia.

the process of adding ms-vscode plugins to the plugin registry has been improved a lot and the only blocker I can see so far (that I can't overcome myself by editing the dockerfiles/.vsix sources) is this.

for example: 
issue for adding vueJS plugin to che: https://github.com/eclipse/che/issues/13672
the extension gives an error because of the following issue:
https://github.com/eclipse-theia/theia/issues/6623#issue-528064453

so for conclussion, promoting this issues when the builtin situation arrives would shorten the times in which the users can keep contributing to the new plugins implementations

**Comment by ibuziuk** [comment]
@gattytto I was not able to attend the last call, so do not know the outcome of the discussion atm. However, the biggest question for me is who is expected to work on those P1s? Does the community members ready to kick on and contribute the missing bits to theia and own the newly contributed plugins?

**Comment by tsmaeder** [comment]
@gattytto not sure what you mean by "built-in". Do you mean VS Code API or a built-in extension?

**Comment by sunix** [comment]
@ibuziuk last call @gattytto had a mic problem. We postponed discussion to next monday.

**Comment by gattytto** [comment]
@tsmaeder what I mean with "builtins" is the vs-code built-in extensions as of this: https://github.com/eclipse/che/issues/14759

@ibuziuk what I mean is that there is more complexity to the theia API and builtin extensions so users may encounter known issues with builtins while trying to add a .vsix extensions to the plugin registry.

In the case of html-language-features (which is a built-in required by the vuejs extension) it was enough just by adding the html-language-features.vsix prior to the loading of the plug-in but there may be cases in which built-ins conflict with each-other or .vsix versions of the ms-vscode builtins are outdated.

So this represents a blocker for a user trying to just make a sidecar container (and maybe a cli one too), and some extension's meta.yaml to add a ms-vscode extension to che. In this case maybe it would be nice to have P1 on this case to get help from che devs around it so users can continue their work

**Comment by gattytto** [comment]
> @ibuziuk last call @gattytto had a mic problem. We postponed discussion to next monday.

yes I was unable to speak to the mic so I just added the subject to the topics and it was postponed to the next session. Gladly I have fixed my mic problems now and I'll be able to speak with you all next time

**Comment by gattytto** [comment]
https://github.com/eclipse/che/issues/16283

**Comment by gattytto** [comment]
https://github.com/eclipse/che/issues/16341

**Comment by ericwill** [comment]
We are working on upgrading all plugins (built-ins and vsix's) to the latest version. Theia API needed for those will be handled on a case by case basis.

I'm going to close this, and we can handle the specific problems in their own issues.
