### ISSUE TITLE
[kubernetes-image-puller] Initial implementation of the operator for kubernetes-image-puller (without OLM support)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16067]
### Is your task related to a problem? Please describe.
Currently, it is possible to install the puller via helm or openshift template. We need to have an option for installing the puller via operator. Once done we can embed [k8s-image-puller](https://github.com/che-incubator/kubernetes-image-puller) to chectl / crwctl as an optional dependency

### Describe the solution you'd like
operator for k8s-image-puller

### Describe alternatives you've considered
N/A

### Additional context
this task does not contains things like OLM support and contribution of the operator to the operatorhub

**Comment by ibuziuk** [comment]
@tomgeorge can we close this issue now?

**Comment by tomgeorge** [comment]
yeah this can be closed
