### ISSUE TITLE
[dashboard] - make it possible to download all workspace startup logs

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#16063]
### Is your enhancement related to a problem? Please describe.
In https://github.com/eclipse/che/issues/15983, we'll add option to watch workspace pod logs. Current workspace startup screen is not user friendly with downloading/copying the logs. It would be really useful to have an option to download all the logs so users can easily provide us better debug info in case of workspace startup failure.

### Describe the solution you'd like
Have some link/button on workspace startup screen that will download all logs. It can be shown only in case of failure, if we can realiably detect it.
![20200218_140812_1681x929_scrot](https://user-images.githubusercontent.com/1160903/74739098-7c0c4500-5258-11ea-8447-ad9b3afac0a9.png)

Don't forget to add docs to troubleshooting https://www.eclipse.org/che/docs/che-7/troubleshooting-for-che-end-users/

### Describe alternatives you've considered
Button could copy the logs to the clipboard. Or we can have both :)

### Additional context
https://github.com/eclipse/che/issues/15983
epic: https://github.com/eclipse/che/issues/15047

**Comment by sleshchenko** [comment]
Is implemented in https://github.com/eclipse/che-workspace-loader/pull/6
