### ISSUE TITLE
new metrics related to workspace startup log watch

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#16062]
### Is your enhancement related to a problem? Please describe.
In the scope of https://github.com/eclipse/che/issues/15047, we're watching the workspace pod logs. That means that we're using one extra connection and thread per container at a workspace startup. This has an impact on performance and the number of parallel threads/connections can become a bottleneck. Because of that, we should introduce new metrics.

### Describe the solution you'd like
Create new metrics for Prometheus and their graphs to Grafana dashboard. We're interested in:
 - [x] ~number of connections to k8s api (https://github.com/eclipse/che/pull/16201 ?)~
 - [x] ~number of threads (I believe we have that already)~
 - [x] number of generated messages (https://github.com/eclipse/che/pull/16263)
 - [x] the number of characters send/bytes. (https://github.com/eclipse/che/pull/16263)
 - [x] the number of debugging attempts. (in this way we can estimate how widely used this feature.) (https://github.com/eclipse/che/pull/16210)
 - [x] current container log watchers (#16285 )

### Describe alternatives you've considered
n/a

### Additional context
epic: #15047

**Comment by skabashnyuk** [comment]
- number of generated messages 
- the number of characters send/bytes.
- the number of debugging attempts.  (in this way we can estimate how widely used this feature.)

**Comment by sparkoo** [comment]
@skabashnyuk please, feel free to edit the description and add your ideas there so it won't get lost in the comments.

**Comment by sparkoo** [comment]
@skabashnyuk please review the list of proposed metrics in the description. Are you ok with it as a scope of this task?

**Comment by skabashnyuk** [comment]
>current and max container log watchers

The current numbers is enough. Maximum we can count on Prometheus/Grafana side.
Others look good.

**Comment by sparkoo** [comment]
everything merged, closing this one
