### ISSUE TITLE
CloudShell workspace does not work in multiuser mode anymore

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16060]
### Describe the bug
CloudShell workspace does not work in multiuser mode anymore.
It's caused by the fact that JWTProxy now tries to connect to machine-exec via 127.0.0.1 but che-machine-exec is not configured in that way.

It's quite easy to prepare to fix for it by reconfiguring cloud-shell editor in plugin-registry as it's done for terminal plugin https://github.com/eclipse/che-plugin-registry/pull/378 but then it won't work in SingleUser Che

JWTProxy is reconfigured in https://github.com/eclipse/che/pull/15890

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Just try to create and start a workspace with cloud-shell editor on MultiUser Che.

### Runtime
   **Does not matter**

### Installation method
   **Does not matter**

### Environment
  **Does not matter**

**Comment by sleshchenko** [comment]
@rhopp Do you think we could create a small test in our selenium test-suite to prevent bugs in the future?

**Comment by AndrienkoAleksandr** [comment]
Closed can't reproduce.
