### ISSUE TITLE
Che-Theia housekeeping - code smells found by SonarQube

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#16070]
Scanning [che-theia](https://github.com/eclipse/che-theia) repository (revision: [8a3ec09efc24b293ae259fa1ddb90796e2993514](https://github.com/eclipse/che-theia/tree/8a3ec09efc24b293ae259fa1ddb90796e2993514)) for possible vulnerabilities and bugs with SonarQube found the following code smells:

- [ ]  [dockerfiles/theia/e2e/src/snapshots.js#L10](https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/e2e/src/snapshots.js#L10)
**Empty block statement.**
5min effort

- [ ]  [extensions/eclipse-che-theia-about/scripts/generate-about-details.js#L30](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-about/scripts/generate-about-details.js#L30)
**'theiaDir' is already declared in the upper scope.**
5min effort

- [ ]  [extensions/eclipse-che-theia-about/scripts/generate-about-details.js#L68](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-about/scripts/generate-about-details.js#L68)
**Add the "let", "const" or "var" keyword to this declaration of "sha1InsideCheTheia" to make it explicit.**
2min effort

- [ ]  [extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts#L78](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts#L78)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts#L53](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts#L53)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/browser/che-variables-main.ts#L34-L40](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/browser/che-variables-main.ts#L34-L40)
**Refactor this redundant 'await' on a non-promise.**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins-caching.css#L21-L22](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins-caching.css#L21-L22)
**Unexpected empty block**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins-caching.css#L37-L39](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins-caching.css#L37-L39)
**Unexpected empty block**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/browser/task-status-handler.ts#L63](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/browser/task-status-handler.ts#L63)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts#L386-L416](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts#L386-L416)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort (~22 messages)

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts#L332](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts#L332)
**Refactor this redundant 'await' on a non-promise.**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts#L185](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts#L185)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts#L405](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts#L405)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts#L175](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts#L175)
**'error' is already declared in the upper scope.**
5min effort

- [ ]  [extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts#L367](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts#L367)
**Either use this collection's contents or remove the collection.**
2min effort

- [ ]  [extensions/eclipse-che-theia-plugin-remote/src/node/websocket.ts#L67](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-remote/src/node/websocket.ts#L67)
**"switch" statements should have at least 3 "case" clauses**
5min effort

- [ ]  [extensions/eclipse-che-theia-plugin-remote/src/node/websocket.ts#L79](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-remote/src/node/websocket.ts#L79)
**"switch" statements should have at least 3 "case" clauses**
5min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L62](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L62)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L98](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L98)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L100-L107](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L100-L107)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L165](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L165)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L194](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L194)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L116](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L116)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L148](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L148)
**Refactor this redundant 'await' on a non-promise.**
1min effort

- [ ]  [extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts#L34](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts#L34)
**Refactor this redundant 'await' on a non-promise.**
1min effort

- [ ]  [generator/src/cdn/base.ts#L74](https://github.com/eclipse/che-theia/blob/master/generator/src/cdn/base.ts#L74)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [generator/src/init.ts#L35](https://github.com/eclipse/che-theia/blob/master/generator/src/init.ts#L35)
**Replace this "String" wrapper object with primitive type "string".**
1min effort

- [ ]  [generator/src/yargs.ts#L90](https://github.com/eclipse/che-theia/blob/master/generator/src/yargs.ts#L90)
**Refactor this redundant 'await' on a non-promise.**
1min effort

- [ ]  [generator/src/yarn.ts#L86](https://github.com/eclipse/che-theia/blob/master/generator/src/yarn.ts#L86)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [plugins/ports-plugin/src/workspace-handler.ts#L37](https://github.com/eclipse/che-theia/blob/master/plugins/ports-plugin/src/workspace-handler.ts#L37)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [plugins/ssh-plugin/src/ssh-plugin-backend.ts#L273](https://github.com/eclipse/che-theia/blob/master/plugins/ssh-plugin/src/ssh-plugin-backend.ts#L273)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [plugins/task-plugin/src/machine/websocket.ts#L60](https://github.com/eclipse/che-theia/blob/master/plugins/task-plugin/src/machine/websocket.ts#L60)
**"switch" statements should have at least 3 "case" clauses**
5min effort

- [ ]  [plugins/task-plugin/src/machine/websocket.ts#L72](https://github.com/eclipse/che-theia/blob/master/plugins/task-plugin/src/machine/websocket.ts#L72)
**"switch" statements should have at least 3 "case" clauses**
5min effort

- [ ]  [plugins/task-plugin/src/preview/tasks-preview-manager.ts#L120](https://github.com/eclipse/che-theia/blob/master/plugins/task-plugin/src/preview/tasks-preview-manager.ts#L120)
**Refactor this redundant 'await' on a non-promise.**
1min effort

- [ ]  [plugins/task-plugin/src/task/backward-compatibility.ts#L60](https://github.com/eclipse/che-theia/blob/master/plugins/task-plugin/src/task/backward-compatibility.ts#L60) & [L88](https://github.com/eclipse/che-theia/blob/master/plugins/task-plugin/src/task/backward-compatibility.ts#L88)
**Refactor this function to not always return the same value.**
4min effort

- [ ]  [plugins/task-plugin/src/task/che-task-provider.ts#L58](https://github.com/eclipse/che-theia/blob/master/plugins/task-plugin/src/task/che-task-provider.ts#L58)
**This assertion is unnecessary since it does not change the type of the expression.**
1min effort

- [ ]  [plugins/workspace-plugin/src/theia-commands.ts#L65-L68](https://github.com/eclipse/che-theia/blob/master/plugins/workspace-plugin/src/theia-commands.ts#L65-L68)
**Consider removing 'undefined' type or '?' specifier, one of them is redundant.**
1min effort (~4 messages)

**Comment by benoitf** [comment]
@vzhukovskii is there a way to enforce that with eslint rules ? (for now we're using tslint but as upstream theia switched to eslint, we should switch as well)

**Comment by vzhukovskii** [comment]
>is there a way to enforce that with eslint rules ?

I think, there isn't any problem to migrate to eslint and configure such checks.
