### ISSUE TITLE
Add extra check to ensure that PR contains all necessary changes

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16077]
### Is your task related to a problem? Please describe.
Every commit in `che-operator` code sometimes implies adding some extra changes in the same PR that committer might not be aware of.

1. If `https://github.com/eclipse/che-operator/blob/master/pkg/apis/org/v1/che_types.go` updated, then the committer must follow the guide:
```
// Important: You should regenerate some generated code after modifying this file. At the root o fthe project:
// - Run "operator-sdk generate k8s": this will perform required changes in the "pkg/apis/org/v1/zz_generatedxxx" files
// - Run "operator-sdk generate openapi": this will generate the "deploy/crds/org_v1_checluster_crd.yaml" file
// - In the updated "deploy/crds/org_v1_checluster_crd.yaml": Delete all the `required:` openAPI rules in the CRD OpenApi schema.
// - Rename the new "deploy/crds/org_v1_checluster_crd.yaml" to "deploy/crds/org_v1_che_crd.yaml" to override it.
// IMPORTANT These 2 last steps are important to ensure backward compatibility with already existing `CheCluster` CRs that were created when no schema was provided.
```

2. If something changed in 
- https://github.com/eclipse/che-operator/tree/master/deploy
then PR should contain a new version of the CSV files and this is done with the script update-nightly-olm-files.sh that creates a new version in the nightly channel of both the eclipse-che-preview-openshift and eclipse-che-preview-kubernetes packages and updates them to maintain consistency with the basic operator deployment yaml files (operator.yaml, rile.yaml, etc...)

### Describe the solution you'd like
PR check should fail if
1. There are changes in `che_types.go` and there aren't  changes in crd files.
2. There are changes in `deploy/*` and there aren't new nightly olm files.

/cc @davidfestal

**Comment by davidfestal** [comment]
That's would be really helpful !

**Comment by flacatus** [comment]
@rhopp assign me this issue !

**Comment by flacatus** [comment]
Done.
