### ISSUE TITLE
Rename `devtools-che-che-pullrequests-test-temporary` job - remove the "temporary" from name.

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#16075]
### Is your task related to a problem? Please describe.
I believe it's time to remove the "temporary" from name of this job: https://ci.centos.org/job/devtools-che-che-pullrequests-test-temporary/

**Comment by flacatus** [comment]
On it!

**Comment by flacatus** [comment]
On it!

**Comment by rhopp** [comment]
Done. Closing.
