### ISSUE TITLE
theia git extension [publish branch] "permission denied" in askpass.sh

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#16084]
clicking "publish branch" in git extension gives the following FATAL error:
Git: fatal: cannot exec '/default-theia-plugins/vscode-git/extension/out/askpass.sh': Permission denied

.sh file does not have +x mod set.

**Comment by ericwill** [comment]
I think this is something that can be handled as part of #16041

**Comment by gattytto** [comment]
@benoitf :
I have a situation where publishing the branch actually works:
First of all I use "view public ssh key" option in theia, and add it to my github account
2)I git clone the project using git:/ and not https: method. It then uses ssh auth instead.
3)within the theia git section I first click 
![image](https://user-images.githubusercontent.com/407397/76150406-e3aff600-6088-11ea-9de8-5693ca26e6c3.png) the branch name and select "create a new branch" and give it a name.
4)I then go again to the git section of the ide and select the 3 dots and click "publish branch", branch publishes.

I can see some "only absolute URL's allowed" warnings popping up but it just works.

**Comment by ibuziuk** [comment]
@nickboldt I believe this should be fixed for 7.9.2 to land in CRW 2.1
