### ISSUE TITLE
Workspace fails to open

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16088]
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Launch Che
2. Create a simple workspace (I used the pre-made Python one)
3. Observe that the workspace fails to start with the error `Error: Failed to run the workspace: "Server 'theia' in container 'theia-idettr' not available."`

### Expected behavior
The workspace should start.

### Runtime
   - [x] kubernetes 1.17.0

### Installation method
   - [x] chectl (version: nightly/next)

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS

**Comment by azatsarynnyy** [comment]
@ericwill if you're running single-user Che I guess it duplicates https://github.com/eclipse/che/issues/16053

**Comment by ericwill** [comment]
Yup it's a duplicate! Thanks @azatsarynnyy
