### ISSUE TITLE
Example showing syntax highlighting

### ISSUE THREAD

**Issue by objectiser** [eclipse-che/che#1608]
I am trying to implement an IDE plugin for a DSL..

In the documentation (https://eclipse-che.readme.io/docs/code-editors#section-syntax-highlighting) it says to refer to the Orion documentation (https://wiki.eclipse.org/Orion/Documentation/Developer_Guide/Plugging_into_the_editor#orion.edit.highlighter) which provides some example javascript.

Do you have an example (or plan to write one) that shows how such javascript can be included with the IDE plugin?

**Comment by TylerJewell** [comment]
@slemeur, @ddementieva - please address.

**Comment by ghost** [comment]
@objectiser we'll have an engineer respond. Meanwhile, can you elaborate on your particular use case? Syntax highlighting for java script is available out of the box. Do you want to plug in a custom one?

**Comment by objectiser** [comment]
Yes I want to have syntax highlighting for my own language.

**Comment by TylerJewell** [comment]
Have you considered xtext?  We are working on having a full implementation of the language server protocol shippable soon.  Typefox built an xtext integration to the language server protocol.  They just demo'ed a scenario where you can write your own custom DSL and it immediately has syntax coloring and intellisense in Eclipse Che.  It will take a bit before this ships, but it's another option to consider.

**Comment by objectiser** [comment]
Happy to look at any options. Do you mean this will be available and shipped with Che, or is it a separate project/product?

**Comment by TylerJewell** [comment]
@svenefftinge has more details - but yes, it will be part of the core che system.  We demoed language servers for Java + C# running in the same che workspace, both with intellisense at Red Hat's developer conference this week.

**Comment by objectiser** [comment]
Ok great - I'll keep an eye out, but if possible can links be posted here when docs/examples are available.

**Comment by TylerJewell** [comment]
@eivantsov - will you still have engineers provide more detailed answer on adding new syntax highlighting?

@objectiser - we also had a technical blog post provided by an engineer on a general purpose way to add JavaScript logic into any of our plugins.  Maybe not perfectly what you are looking for.  If you have specific types of features you are trying to implement that are not currently documented in the extension development guide in the docs, please be more specific in this thread and we'll see about the right docs.

http://che.eclipse.org/hands-eclipse-che-javascript-plugin-api/

**Comment by ashumilova** [comment]
@objectiser You have two options: 
1. Add the highlighting of content type, supported by Orion, but not by IDE yet.
Add extension with mime type to [File Extension Registry](https://github.com/eclipse/che/blob/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor/filetype/ExtensionFileTypeIdentifier.java)
`this.mappings.put("ino", makeList("text/x-c++src"));`
2. Introduce you own highlighting - take a look at this [sample](https://github.com/eclipse/che/pull/1392)

**Comment by TylerJewell** [comment]
@ddementieva  - please capture this issue and add any additional thoughts + sample to this page on the docs: https://eclipse-che.readme.io/docs/code-editors.

**Comment by TylerJewell** [comment]
@ddementieva - please comment on status

**Comment by ddementieva** [comment]
Added to the docs: https://eclipse-che.readme.io/docs/code-editors#section-add-syntax-highlighting-for-your-own-language
