### ISSUE TITLE
Use 80.0 Chrome driver in typescript selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16090]
### Is your enhancement related to a problem? Please describe.
We are running E2E typescript selenium tests (Happy path tests, devfile tests) locally using [outdated chrome driver of 76.0.0 version](https://github.com/eclipse/che/blob/c37275677c29b8022d108157b9daf174742d6552/tests/e2e/package-lock.json#L328).
At the same time chromedriver is latest when we run E2E tests in docker container of quay.io/eclipse/che-e2e:nightly.

### Describe the solution you'd like
We need to update the chromedriver version to latest one https://registry.npmjs.org/chromedriver/ (it's 80.0.1 as for now),

**Comment by ScrewTSW** [comment]
I would switch it over to the latest stable version. I wouldn't go straight for the `80.0.1`

**Comment by Ohrimenko1988** [comment]
@ScrewTSW Could you clarify what do you mean? Use something like "stable" or "latest" version instead of using a direct version?

**Comment by Ohrimenko1988** [comment]
@ScrewTSW Could you answer, please?

**Comment by ScrewTSW** [comment]
@Ohrimenko1988 
We are running CentOS as a base system for our tests, correct?

I believe CentOS has a specific google repository for chrome-stable. We should be running the chromedriver with the same version as well.

Or are our tests running the latest build of google-chrome as well?

**Comment by Ohrimenko1988** [comment]
@ScrewTSW Let me explain. Local run and run inside docker container are different things. Docker launching (uses for CI testing) uses special "e2e" image with all necessary dependencies and based on the latest selenium-chrome image. Inside docker container runs embeded latest selenium server and tests connect to it.
For local run uses npm dependency from "e2e" project.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/16116
