### ISSUE TITLE
Vert.x devfile E2E tests failed being run against Eclipse Che 7.9.0.RC

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16092]
### Describe the bug
Vert.x devfile E2E tests failed on Eclipse Che 7.9.0.RC:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/960/artifact/tests/e2e/report/
```
11) Java Vert.x test
       Validation of project build
         Run command 'maven build':
     TimeoutError: Waiting for element to be located By(xpath, //div[@class='theia-notification-message']/span[contains(.,'has exited with code 0.')])
Wait timed out after 120097ms
```
Che logs: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/960/artifact/logs-and-configs/che-logs/

### Screenshots
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/960/artifact/tests/e2e/report/
- Autocomplete
![screenshot-Autocomplete (1)](https://user-images.githubusercontent.com/1197777/74928239-cd940b80-53e1-11ea-8551-b48a059690f2.png)
- Codenavigation
![screenshot-Codenavigation](https://user-images.githubusercontent.com/1197777/74928273-ddabeb00-53e1-11ea-85b8-59842743b56e.png)
- Error highlighting
![screenshot-Error_highlighting](https://user-images.githubusercontent.com/1197777/74928281-e00e4500-53e1-11ea-8366-f52f49f2d36b.png)
- LS initialization
![screenshot-LS_initialization (1)](https://user-images.githubusercontent.com/1197777/74928289-e3a1cc00-53e1-11ea-9984-2e0c633c40c8.png)
- Suggestion invoking
![screenshot-Suggestion_invoking (1)](https://user-images.githubusercontent.com/1197777/74928293-e6042600-53e1-11ea-8256-767c28da9cc3.png)
- Run command 'maven build'
![screenshot-Run_command_'maven_build'](https://user-images.githubusercontent.com/1197777/74928304-eac8da00-53e1-11ea-8c9c-43e0545e5b26.png)

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.9.0.RC

### Steps to reproduce
Vert.x devfile E2E test script is [here](https://github.com/eclipse/che/blob/7.9.x/tests/e2e/tests/devfiles/JavaVertx.spec.ts0.

### Runtime
   - [x] kubernetes 1.1.1
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl :next with operator instasller
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

Command to deploy Eclipse Che:
```
chectl server:start \
  --k8spodreadytimeout=180000 \
  --installer=operator \
  --listr-renderer=verbose \
  --platform=minikube \
  --che-operator-cr-yaml=custom-resource.yaml
```
<details>
 <summary>custom-resource.yaml</summary>
 <pre>
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    # server image used in Che deployment
    cheImage: 'eclipse/che-server'
    # tag of an image used in Che deployment
    cheImageTag: 'rc'
    # image:tag used in Devfile registry deployment
    devfileRegistryImage: 'quay.io/eclipse/che-devfile-registry:7.9.0'
    # image:tag used in plugin registry deployment
    pluginRegistryImage: 'quay.io/eclipse/che-plugin-registry:7.9.0'
    # defaults to `che`. When set to `codeready`, CodeReady Workspaces is deployed
    # the difference is in images, labels, exec commands
    cheFlavor: ''
    # specifies a custom cluster role to user for the Che workspaces
    # Uses the default roles if left blank.
    cheWorkspaceClusterRole: ''
    # when set to true the operator will attempt to get a secret in OpenShift router namespace
    # to add it to Java trust store of Che server. Requires cluster-admin privileges for operator service account
    selfSignedCert: false
    ## If enabled then the certificate from `che-git-self-signed-cert` config map
    ## will be propagated to the Che components and provide particular configuration for Git.
    gitSelfSignedCert: false
    # TLS mode for Che. Make sure you either have public cert, or set selfSignedCert to true
    tlsSupport: false
    # protocol+hostname of a proxy server. Automatically added as JAVA_OPTS and https(s)_proxy
    # to Che server and workspaces containers
    proxyURL: ''
    # port of a proxy server
    proxyPort: ''
    # username for a proxy server
    proxyUser: ''
    # password for a proxy user
    proxyPassword: ''
    # a list of non-proxy hosts. Use | as delimiter, eg localhost|my.host.com|123.42.12.32
    nonProxyHosts: ''
    # sets mem request for server deployment. Defaults to 512Mi
    serverMemoryRequest: ''
    # sets mem limit for server deployment. Defaults to 1Gi
    serverMemoryLimit: ''
    # sets default namespace where new workspaces will be created
    workspaceNamespaceDefault: ''
    # defines if user is able to specify namespace different from the default
    allowUserDefinedWorkspaceNamespaces: false
  database:
    # when set to true, the operator skips deploying Postgres, and passes connection details of existing DB to Che server
    # otherwise a Postgres deployment is created
    externalDb: false
    # Postgres Database hostname that Che server uses to connect to. Defaults to postgres
    chePostgresHostName: ''
    # Postgres Database port that Che server uses to connect to. Defaults to 5432
    chePostgresPort: ''
    # Postgres user that Che server when making a db connection. Defaults to pgche
    chePostgresUser: ''
    # password of a postgres user. Auto-generated when left blank
    chePostgresPassword: ''
    # Postgres database name that Che server uses to connect to. Defaults to dbche
    chePostgresDb: ''
    # Postgres deployment in format image:tag. Defaults to registry.redhat.io/rhscl/postgresql-96-rhel7 (see pkg/deploy/defaults.go for latest tag)
    postgresImage: ''
  storage:
    # persistent volume claim strategy for Che server. Can be common (all workspaces PVCs in one volume),
    # per-workspace (one PVC per workspace for all declared volumes) and unique (one PVC per declared volume). Defaults to common
    pvcStrategy: 'common'
    # size of a persistent volume claim for workspaces. Defaults to 1Gi
    pvcClaimSize: '1Gi'
    # instruct Che server to launch a special pod to precreate a subpath in a PV
    preCreateSubPaths: true
    # image:tag for preCreateSubPaths jobs
    pvcJobsImage: ''
    # keep blank unless you need to use a non default storage class for Postgres PVC
    postgresPVCStorageClassName: ''
    # keep blank unless you need to use a non default storage class for workspace PVC(s)
    workspacePVCStorageClassName: ''
​
  auth:
    # instructs operator on whether or not to deploy Keycloak/RH SSO instance. When set to true provision connection details
    externalIdentityProvider: false
    # retrieved from respective route/ingress unless explicitly specified in CR (when ExternalKeycloak is true)
    identityProviderURL: ''
    # password for keycloak database user. Auto generated if left blank
    keycloakPostgresPassword: ''
    # desired admin username of Keycloak admin user (applicable only when externalIdentityProvider is false)
    identityProviderAdminUserName: ''
    # desired password of Keycloak admin user (applicable only when externalIdentityProvider is false)
    identityProviderPassword: 'admin'
    # name of a keycloak realm. This realm will be created, when externalIdentityProvider is true, otherwise passed to Che server
    identityProviderRealm: ''
    # id of a keycloak client. This client will be created, when externalIdentityProvider is false, otherwise passed to Che server
    identityProviderClientId: ''
    # instructs an Operator to enable OpenShift v3 identity provider in Keycloak,
    # as well as create respective oAuthClient and configure Che configMap accordingly
    openShiftoAuth: false
    # name of oAuthClient used in OpenShift v3 identity provider in Keycloak realm. Auto generated if left blank
    oAuthClientName: ''
    # secret used in oAuthClient. Auto generated if left blank
    oAuthSecret: ''
    # image:tag used in Keycloak deployment
    identityProviderImage: 'quay.io/eclipse/che-keycloak:rc'
  k8s:
    # your global ingress domain
    ingressDomain: '10.0.101.60.nip.io'
    # kubernetes.io/ingress.class, defaults to nginx
    ingressClass: ''
    # IngressStrategy is the way ingresses are created.
    # Can be multi-host (host is explicitly provided in ingress, <ingress-name>-<namespace>.<global-ingress-domain>),
    # single-host (host is provided, path based rules, <ingress-domain>/path) and default-host *(no host is provided, path based rules)
    ingressStrategy: ''
    # secret name used for tls termination
    tlsSecretName: ''
    # FSGroup the Che POD and Workspace pod containers should run in
    securityContextFsGroup: ''
    # User the Che POD and Workspace pod containers should run as
    securityContextRunAsUser: ''
  metrics:
    # Enables '/metrics' endpoint of Che server.
    enable: false
 </pre>
</details>

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by Katka92** [comment]
@dmytro-ndp The build test failed as a result of failed `error highlighting` test - the erroneous text remained in a file, so the code was not able to build.

**Comment by dmytro-ndp** [comment]
It turned out, that there was outdated **eclipse/che-server:rc** image used for testing.
The issue hasn't been reproduced with **quay.io/eclipse/che-server:rc** image: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/963/artifact/tests/e2e/report/
