### ISSUE TITLE
Chectl cannot inject config to running workspace

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16098]
### Describe the bug

Chectl does not inject config file to the workspace running in Che deployed by operator.

```
vitaliy@vitaliy-ThinkPad-P50:~/.kube$ chectl workspace:inject -k -c vscode-kubernetes-toolslp9 -w workspace9wsi7eism1r6h6z9
  ✔ Verify if namespace che exists
  ✖ Verify if the workspaces is running
    → No workspace pod is found
    Verify if container vscode-kubernetes-toolslp9 exists
    Injecting configurations
 ›   Error: No workspace pod is found
```

Commands used to deploy Che
```
$ minikube start --memory=10240 --cpus=4 --disk-size=20g
$ chectl server:start --platform=minikube
```

After opening kubernetes dashboard, I noticed that there are two `che` and `che-che` namespaces, which is confusing. Why do we need `che-che`?

![Screenshot from 2020-02-21 11-31-18](https://user-images.githubusercontent.com/1655894/75023559-ae0fe800-54a0-11ea-8925-784d2c8e8ddb.png)

The reason why `chectl` cannot inject the config, is that my workspace appears to be in `che-che` namespace.
After hardcoding `che-che` in `chectl` sources, It managed to inject the config.

![Screenshot from 2020-02-20 18-06-32](https://user-images.githubusercontent.com/1655894/75024288-d1876280-54a1-11ea-97fb-2e64bd5d74b0.png)
 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Deploy `che` using operator.
2. Inject the config by `chectl`.

### Expected behavior

Config must be injected.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by tolusha** [comment]
Duplicates
https://github.com/eclipse/che/issues/16019
