### ISSUE TITLE
[che-operator] A little mistake in 'oc create secret command'

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#16097]
Fix a little mistake in eclipse/che-operator:
```
oc create secret self-signed-certificate generic --from-file=/path/to/certificate/ca.crt -n=$codeReadyNamespace
```
should be 
```
oc create secret generic self-signed-certificate  --from-file=/path/to/certificate/ca.crt -n=$codeReadyNamespace
```

**Comment by tolusha** [comment]
Could you have a look pls
@mmorhun

**Comment by ibuziuk** [comment]
@gorshkov-leonid thanks for reporting, not sure what the issue is, but maybe you can sent a PR with a fix to continue the discussion closer to the source-code?
