### ISSUE TITLE
Where can I find the git hash from a che docker image?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#161]
When I use the latest `codenvy/che:nightly`, I found there is something wrong (not sure if it's code issues or just my wrong usage), but I have already tagged a previous good image as a backup.

Now I want to see what't the git hash of the code in that docker image, so I can checkout the code and do something, but not sure how to do it. Is there any file recorded the git hash in the image? Or is there any other way I can find it?

**Comment by benoitf** [comment]
https://registry.hub.docker.com/v1/repositories/codenvy/che/tags

**Comment by freewind** [comment]
```
[
{
"layer": "057d4fb8",
"name": "latest"
},
{
"layer": "057d4fb8",
"name": "4.0.0-beta-5"
},
{
"layer": "0ccd7e22",
"name": "nightly"
}
]
```

Do you mean the layer (e.g. `0ccd7e22`) is the same as the git hash?

**Comment by ghost** [comment]
Yes, latest and tag are the same

**Comment by freewind** [comment]
Sorry for my unclear question.

The "layer" hash seems not what I'm looking for, it's not the **git** hash I can search from the codebase. 

I want to find which **GIT** hash of an image, so I can check out the code and switch to that hash. Is it possible?

**Comment by ghost** [comment]
Not sure I understand the question. Can you elaborate?

**Comment by freewind** [comment]
Sorry, I mean if I see there is a che docker image, how can I know which git commit the image is built based on? Like the `93093323ea5409f3232a2418056bcebd277675e2` in `https://github.com/codenvy/che/commit/93093323ea5409f3232a2418056bcebd277675e2`

**Comment by TylerJewell** [comment]
This is an interesting question.  Makes sense.  If you use the labeled images based upon a release the Che install inside the image will match commit if for the same release provided on our github release page.  https://github.com/codenvy/che/releases

I need to ask about how we would do that for the nightly images.

**Comment by freewind** [comment]
@TylerJewell  Thanks! I have this request because a previous nightly build image is working well on my server, but another day it fails. I don't have enough time to find the reason, so I think if I know the git commit hash of an image, I can record it somewhere that I can build it myself in the future if needed

**Comment by TylerJewell** [comment]
Well for day to day development shouldn't you stick to using the releases versions?  We have a beta 5 release candidate now and should have a full beta release within a couple weeks.  Those releases are both stable and increasingly functionally complete.   Then there will not be any issues with chasing the git hash.  

Should we close this issue for now on the expectation that you will not need the nightly build much in the future?

**Comment by freewind** [comment]
@TylerJewell Thanks, I'm fine to close it
