### ISSUE TITLE
License info for che-operator and che-jwtproxy code repositories

### ISSUE THREAD

**Issue by shahidhs-ibm** [eclipse-che/che#16104]
## Summary
There is no License file present for [che-operator](https://github.com/eclipse/che-operator) and [che-jwtproxy](https://github.com/eclipse/che-jwtproxy) code repositories. This is not consistent across other eclipse/che code repositories which have License file present. For e.g. [che-plugin-broker](https://github.com/eclipse/che-plugin-broker), [che-devfile-registry](https://github.com/eclipse/che-devfile-registry) etc.
Is this a miss? Kindly confirm that the mentioned code repositories falls under Eclipse Public License v2.0 or if that is not the case.

## Relevant information
N.A.

**Comment by tolusha** [comment]
@benoitf 
Do you have any ideas?

**Comment by ibuziuk** [comment]
nice catch, I believe we need to add EPL 2.0 license files to the repo

**Comment by ibuziuk** [comment]
PRs have been sent:
- https://github.com/eclipse/che-jwtproxy/pull/17
- https://github.com/eclipse/che-operator/pull/178

**Comment by ibuziuk** [comment]
Fixed. Closing
