### ISSUE TITLE
[telemetry] Track a list of plugins installed in the workspace

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16105]
### Is your task related to a problem? Please describe.
We would like to understand which plugins are most used by developers and have the possibility to track a list of plugins installed in each workspace. 
 
### Describe the solution you'd like
Send a list of plugins with telemetry events during workspace startup

**Comment by johnmcollier** [comment]
@ibuziuk Just curious, will telemetry just be for workspaces running on che.openshift.io, or all Che installs? 

I work on some Che plugins that don't currently run on che.openshift.io, but would still love to get some telemetry for them.

**Comment by ibuziuk** [comment]
@johnmcollier we would like to add the plugin tracking mechanism to the AbstractAnaliticManager [1], which means that only Hosted Che but also other adopters will be able to manage 
the telemetry configuration for their needs 

[1] https://github.com/che-incubator/che-workspace-telemetry-client/blob/master/backend-base/src/main/java/org/eclipse/che/incubator/workspace/telemetry/base/AbstractAnalyticsManager.java

**Comment by pdaverh** [comment]
Can we add these actions to che.openshift.io telemetry database on segment so we can create a report to view the results?

**Comment by tomgeorge** [comment]
@pdaverh @ibuziuk do you know what that entails/do you know of any documentation for that so we can get started on it?

**Comment by ibuziuk** [comment]
@pdaverh I believe we should track the report creation separately.
@tomgeorge am I correct that all the data should already be in place? in this case we should probably close the issue

**Comment by tomgeorge** [comment]
@pdaverh  @ibuziuk that makes sense to me.  Opened https://github.com/eclipse/che/issues/16806
