### ISSUE TITLE
[plugin registry] invalid name field not caught by validation checkers when name is valid (but for a different plugin)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16107]
### Describe the bug

The problem is that `name:java` IS valid but for a different plugin; should have been `name:java8` and `name:java11` ... and no check caught that afaict. or at least nothing in GH complained about the [PR that introduced the 0.57.0](https://github.com/eclipse/che-plugin-registry/pull/387/files) versions of java8 and java11 plugins

So, we need to check that the PATH defined by the meta.yaml is the same as the PATH to the meta.yaml file.

Or better yet, ignore what's in the meta.yaml file, and regenerate the `name:` field when you're creating latest and doing other manipulations.

### Che version

 - [x] latest 7.9.0 / 7.10.0
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by nickboldt** [comment]
Slip to next milestone

**Comment by amisevsk** [comment]
@nickboldt This issue was actually due to an error in how the CI build was set up (failed checks weren't failing the build).

The reported problem is correctly caught by the `check_plugins_location.sh` script:
```
!!! Location mismatch in plugin 'redhat/java/0.57.0':
!!!   Expected location: './v3/plugins/redhat/java/0.57.0/meta.yaml'
!!!   Actual location: './v3/plugins/redhat/java11/0.57.0/meta.yaml' 
```

**Comment by amisevsk** [comment]
Was fixed in https://github.com/eclipse/che-plugin-registry/pull/393/files
