### ISSUE TITLE
Ensure plugin registry name field in meta.yaml matches folder path (generate code / check validity when building)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16102]
### Is your enhancement related to a problem? Please describe.

Problem: it's possible to put the wrong name field in a plugin's meta.yaml, resulting in strange behaviour.

Fix:

https://github.com/eclipse/che-plugin-registry/pull/390
https://github.com/eclipse/che-plugin-registry/pull/391

### Describe the solution you'd like

When plugin registry is building, a check should be done that the path segment in which the meta.yaml resides matches the value of the name field in that meta.yaml.

Even better, if could be generated from the path segment so it always matches. Why force humans to type stuff over and over when a machine can do it for us?

### Describe alternatives you've considered

Could also add a new PR check after the fact but breaking the build or generating valid code seems a better approach (more automated, less after-the-fact human process).

### Additional context

Follows up on https://github.com/eclipse/che/issues/16051

**Comment by nickboldt** [comment]
See also https://github.com/eclipse/che/issues/16107 (might be a dupe)

**Comment by tolusha** [comment]
@nickboldt 
Is it done since fixes have been merged?

**Comment by nickboldt** [comment]
Was fixed in https://github.com/eclipse/che-plugin-registry/pull/393/files
