### ISSUE TITLE
Devfile not found when factory constructed with .git suffix

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#16109]
### Describe the bug

When factory url is constructed with `.git` suffix, e.g. `https://che.openshift.io/f?url=https://github.com/jchraibi/nodejs-ex.git&policies.create=peruser`  there is 2 problems appears:

1) Devfile is not found by che server, despite the fact it is present in repo;
2) As a consequence of 1),  default project source is constructed and has double suffix `.git.git`

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@l0rd @nickboldt AFAIK, this is a must-have for 7.9.1
