### ISSUE TITLE
Add new image to Che release process: endpoint-watcher

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16101]
Source repo for container:

https://github.com/eclipse/che/tree/master/dockerfiles/endpoint-watcher

New quay builds:

https://quay.io/repository/eclipse/che-endpoint-watcher?tab=tags

Files to update:

https://raw.githubusercontent.com/eclipse/che/master/RELEASE.md

Need a new make-release.sh and RELEASE.md for this container, too.

**Comment by nickboldt** [comment]
@tolusha will we be releasing the endpoint watcher as part of Che 7.10?

**Comment by tolusha** [comment]
@nickboldt 
I have no idea. I have never released that.

**Comment by nickboldt** [comment]
You set this as a P1, but no one worked on it... so slip to 7.11

**Comment by nickboldt** [comment]
Done for 7.9.2 and 7.10.

https://quay.io/repository/eclipse/che-endpoint-watcher?tab=tags

Released as part of the che server make-release.sh process.
