### ISSUE TITLE
Intellisense not work

### ISSUE THREAD

**Issue by hozen** [eclipse-che/che#1610]
I just started using Eclipse Che by Vagrant, and while editing in Chrome IDE, there is no code highlight, no intellisense, so what did I miss? I looked up the online document, no where said that need an additional setup/plugin for the feature.

![image](https://cloud.githubusercontent.com/assets/5065868/16474289/0ebf10f8-3ea8-11e6-97d0-61fa1fe6df4d.png)

**Comment by TylerJewell** [comment]
Interesting.   What is your OS?  And all of the assistant menu commands are not working?  What happens with ctrl - space?

**Comment by ghost** [comment]
@hozen I can see that code validation works in your case. Hitting Ctrl+Space should do the trick.

**Comment by ghost** [comment]
@hozen any update on the issue?

**Comment by ghost** [comment]
Closing the issue. @hozen feel free to reopen if you think it's still there.
