### ISSUE TITLE
Bluetooth over USB on OSX 10.11.4 - VirtualBox Settings

### ISSUE THREAD

**Issue by Custom-Built** [eclipse-che/che#1611]
This is past my level of expertise and I need some help form the experts now. - Thanks in advance

After a standard install on OSX the USB Bluetooth device is no longer available as soon as VirtualBox Loads. ( resulting in no keyboard or mouse on MacMini )

Any efforts to change settings within VirtualBox requires Vagrant to be destroyed and rebuilt and default setting return in VirtualBox.

How reproducible: Standard Install on 2014 MacMini OSX 10.11
Steps to Reproduce:
1. [ vagrant up           ] - As soon as VM boots USB Bluetooth is no longer available
2. [ vagrant suspend ] - As soon as VM closes USB Bluetooth is is returned

Results from [ VBoxManage showvminfo artik-ide-vm ]

USB Device Filters:

Index:            0
Active:           yes
Name:             Artik
VendorId:  
ProductId:  
Revision:  
Manufacturer:  
Product:  
Remote:  
Serial Number:    

Available remote USB devices:

<none>

Currently Attached USB Devices:

UUID:               b6071282-6252-4752-8259-e51b2d47199b
VendorId:           0x05ac (05AC)
ProductId:          0x8242 (8242)
Revision:           1.0 (0100)
Manufacturer:       Apple, Inc.
Product:            IR Receiver
Address:            p=0x8242;v=0x05ac;s=0x0000037aa1a786d9;l=0x14400000

Bandwidth groups:  <none>

**Comment by ghost** [comment]
@Custom-Built you may need to install an extension pack for VBox - http://www.htpcbeginner.com/install-virtualbox-extension-pack-on-linux-windows so that the virtual machine can actually see USB devices connected to the host system.

**Comment by Custom-Built** [comment]
Hi

The extension box for VBox has already been installed as detailed in install instructions here: https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started.

I have provided some screen shots of the default setting generated in VBox -  Any further advice will be appreciated.

Regards

Nick

———————————————————————  Terminal Vagrant up   ———————————————————————

Nicholass-Mac-mini:artik MacMini$ vagrant up
ARTIK IDE: VAGRANT INSTALLER
ARTIK IDE: REQUIRED: VIRTUALBOX 5.x
ARTIK IDE: REQUIRED: VAGRANT 1.8.x

Bringing machine 'artik' up with 'virtualbox' provider...
==> artik: Checking if box 'boxcutter/centos72-docker' is up to date...
==> artik: Resuming suspended VM...
==> artik: Booting VM...
==> artik: Waiting for machine to boot. This may take a few minutes...
    artik: SSH address: 127.0.0.1:2222
    artik: SSH username: vagrant
    artik: SSH auth method: private key
==> artik: Machine booted and ready!
==> artik: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> artik: flag to force provisioning. Provisioners marked to run always will still run.
==> artik: Running provisioner: shell...
    artik: Running: inline script
==> artik: #
==> artik: ----------------------------------------
==> artik: ARTIK IDE: BOOTED AND REACHABLE
==> artik: ARTIK IDE: http://192.168.28.200:9000  
==> artik: ----------------------------------------
Nicholass-Mac-mini:artik MacMini$ vagrant suspend
ARTIK IDE: VAGRANT INSTALLER
ARTIK IDE: REQUIRED: VIRTUALBOX 5.x
ARTIK IDE: REQUIRED: VAGRANT 1.8.x

==> artik: Saving VM state and suspending execution...
Nicholass-Mac-mini:artik MacMini$ 

———————————————————————             END             ———————————————————————

**Comment by ghost** [comment]
@Custom-Built can you see other USB devices in when in the VM? You may connect your phone or any other device and run `lsusb`

**Comment by Custom-Built** [comment]
The USB Device tree as connected to the MacMini - Connection to Artik is highlighted.

The default Artik usb settings create a blank filter that is meant to capture all USB devices:
I retain control of usb keyboard with the default settings.
Refer this post for more information: https://forums.virtualbox.org/viewtopic.php?f=8&t=75844 https://forums.virtualbox.org/viewtopic.php?f=8&t=75844

Results from lsusb with default Artik filter settings.
[root@9473527ba622 projects]# lsusb  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub  
Bus 002 Device 016: ID 05ac:8242 Apple, Inc. Built-in IR Receiver  
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

I have been able to regain control of Bluetooth by making changes in VBox: Settings: Ports: USB.

Results from lsusb with new filter settings.
[root@9473527ba622 projects]# lsusb  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub  
Bus 002 Device 015: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC  
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub   

At this point OSX is no longer able to see the Artik, however a the device cannot be added in the IDE

Any further assistance will be greatly appreciated 

Regards

Nick

**Comment by ghost** [comment]
@Custom-Built you can manually add IP of your devices when connecting to it. We use adb for auto discovery so that should not block you from using Artik IDE.

I'd recommend you reach out to VBox communities with this issue, since it's not Che specific. It's VBox being unable to see multiple USB devices. I mean you may get far more efficient support at specialized VBox forum.

Btw, you mentioned changing USB settings - can you elaborate?

**Comment by ghost** [comment]
I am going to close this one as thise doe snot seem to be Che issue.
