### ISSUE TITLE
Proper labeling - `Che Cluster` should be renamed to `Che instance`

### ISSUE THREAD

**Issue by MichalMaler** [eclipse-che/che#16115]
### Is your enhancement related to a problem? Please describe.
In the Che GUI and documentation, you can find various mentions about the Eclipse Che cluster, which should be renamed to Che instance, since the word cluster doesn't make much sense in those contexts.

Please take a look at those two examples:
1) https://www.eclipse.org/che/docs/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.html

- here you can see the use of the word `cluster` which doesn't sound right, but it is correct when compared to the Che code (example 2)

2) https://github.com/eclipse/che-operator/blob/master/olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.8.0/eclipse-che-preview-openshift.v7.8.0.clusterserviceversion.yaml#L61

![image](https://user-images.githubusercontent.com/48474054/75160578-8b890380-571a-11ea-95ee-7e64b237e5db.png)

### Describe the solution you'd like
Eclipse Che Cluster, Eclipse Che cluster and CheCluster (CR), should be renamed to Eclipse Che instance, or its variation.
* I know that CheCluster (CR) could be a little bit more problematic, but it could also be mentioned in this naming issue.

### Coda
It's not a problem to fix the documentation, I am doing this in https://github.com/eclipse/che-docs/pull/1096/files , but Che/CRW representation in OpenShift web console GUI should be modified, and those old names on Che code changed to something meaningful, like `Che instance.`

**Comment by tsmaeder** [comment]
"Che cluster" would be the cluster Che is running on. That might make sense in some contexts.

**Comment by ibuziuk** [comment]
@MichalMaler will let @davidfestal to comment, but I do not think we can change the name of CR at this point of time

**Comment by beaumorley** [comment]
I recently went through the installation of the CodeReady Workspaces operator for the first time. For CodeReady Workspaces, it says "CodeReady Workspaces Cluster". I found this somewhat confusing. I don't think you need the word "Instance" or "Cluster" in the title. Ideally, it would say:

**Eclipse Che**
Eclipse Che instance with DB and Auth Server.
 +Create Instance

I talked to my OpenShift UX expert and they also said the CR is not easy to change.  But wanted to give this feedback regardless.

**Comment by MichalMaler** [comment]
Yes, my point was to point to this terminology which can cause trouble to newcomers.

* OpenShift/K8s cluster
* Eclipse Che installation or instance or deployment -- but not Eclipse Che cluster (or even `Cluster`)

Unless, as Thomas said, we're using Eclipse Che to specify an OpenShift cluster -- as in Che cluster (the OpenShift cluster in which Che is deployed).

The same goes for: `Eclipse Che Cluster URL` when people trying to get this URL to enter their product's instance. :)

**Comment by davidfestal** [comment]
The name `CheCluster` for the Che server custom resource has been chosen long ago by the `che-operator` initial contributor, and I have no idea if it was really discussed at this time.

The fact is that now we have to keep backward compatibility with this choice, and afaict by a way or another the `CheCluster` name will finally leak into some places in the documentation and UX.

So maybe the best approach would be to give a clear Che-specific meaning to the `CheCluster` name.
After all a `CheCluster` defines a group of components (Che server, identity provider, database, and a number of workspaces it will manage). It's not a *cluster* is the *K8S* meaning, but it somehow defines a cluster of components that, taken as a whole, centrally manages a cluster of Che workspaces.

Maybe the whole point is to find a clear, understandable and official meaning for this `CheCluster` name, explain it in the documentation, and then use it everywhere consistently.

@l0rd wdyt ?
