### ISSUE TITLE
PHP highlighting broken since 7.9.0

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#16114]
The PHP highlighting is broken since Che 7.9.0. Switching back che-theia to 7.8.0 in the plugin settings enables it again.

Reason might be that php is missing in that list:
https://github.com/eclipse/che-theia/blob/master/generator/src/templates/theiaPlugins.json

**Comment by tsmaeder** [comment]
The quickfix is to add the php syntax contribution. The long fix would be to investigate what the php-language-features vsix offers.

**Comment by tsmaeder** [comment]
https://github.com/eclipse/che-theia/commit/7967aa2e3835793761aa47f4c6f140544b42872b#diff-76c7c9ec4f2d7ab8816ac0aab7ec3a84 removed @theia/textmate-grammars from the dependencies. Need to look at the diff of what's defined in the theia module and what's included in the built-ins.

**Comment by tsmaeder** [comment]
@vzhukovskii any reason you did not include all built-ins that are grammar-only?

**Comment by azatsarynnyy** [comment]
> @vzhukovskii any reason you did not include all built-ins that are grammar-only?

We got the subset of the VS Code built-ins from Eclipse Theia https://github.com/eclipse-theia/theia/blob/c1bd96f7e10f8d5d2c0be2ba07dd9f918329df7f/package.json#L82-L145
and added only the grammar related ones to Che Theia.

**Comment by vzhukovskii** [comment]
And AFAIK there is also some problems with adapting php builtin extension: https://github.com/eclipse-theia/theia/issues/6672

**Comment by ex-q** [comment]
As of Today it works again with che-theia:next. Thanks a lot!
