### ISSUE TITLE
[ TS_SELENIUM ] Create a wrapper for the "axios" library 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#16122]
### Is your enhancement related to a problem? Please describe.
Currently, we use the "axios" library directly and configure it for call dependently in all proper place.
If we need to change a configuration we should rewrite it in all places

### Describe the solution you'd like
Create a wrapper for the "axios" library. It will allow configuring calls in one place. 

On variant how to do that:
We have constant ```TS_SELENIUM_VALUE_TLS_SUPPORT```
we may create an interface
``IRequestMaker``
and 2 implementation
```HttpRequestMaker```
and
```HttpsRequestMaker```

and bind proper implementation according to the constant value
using an "inversify" library advantages.

### Describe alternatives you've considered
Open to discussion

**Comment by Ohrimenko1988** [comment]
@ScrewTSW @Katka92 @musienko-maxim @dmytro-ndp @SkorikSergey @artaleks9 @rhopp 
Please, join the discussion.

**Comment by ScrewTSW** [comment]
I definitely support the idea of having an interface that would bind an appropriate implementation based on whether the TLS is enabled or not.

It is very likely that we might have to call an URL directly in the future and I would prefer to have a universal tool/util library in our tests that would be consistent across all the devfile tests and pageobjects :+1:

**Comment by flacatus** [comment]
@ScrewTSW I'm agree with you. We can define an `axios instance` for example like [here](https://github.com/axios/axios#axioscreateconfig) and could be used like a universal tool.

**Comment by Katka92** [comment]
Thank you for creating this issue. I like the idea of having that approach centralized. 
I suppose that there will be no other implementation than Http/Https, so I'm not sure if using inversify is needed there - three classes and inversify binding seems a little bit like an over-engineering to me. 
Maybe we can solve that just with one class, e.g. `AxiosHandler` that would have one method `getAxiosInstance(url, ...)` and will just return http or https instance based on TLS variable, as you proposed.

**Comment by ScrewTSW** [comment]
> Thank you for creating this issue. I like the idea of having that approach centralized.
> I suppose that there will be no other implementation than Http/Https, so I'm not sure if using inversify is needed there - three classes and inversify binding seems a little bit like an over-engineering to me.
> Maybe we can solve that just with one class, e.g. `AxiosHandler` that would have one method `getAxiosInstance(url, ...)` and will just return http or https instance based on TLS variable, as you proposed.

I would rather write it as a singleton class and call the `getInstance` on it. I would want to keep the `getUrl` or `sendPostRequest` methods inside the class and based on the singleton instance it would either use http or https agent

**Comment by flacatus** [comment]
`const axios = require('axios'),
    Request_Instance = axios.create();

const Request = ({baseURL, method, url, httpAgent}) => Request_Instance({
    baseURL:baseURL,
    url:url,
    method : method,
    httpAgent:httpAgent
});

const GetSomething = async () => {
    try {
        // Example to skip SSl Verification, also could speicify in the https agent
        // the CAs etc
        const agent = new https.Agent({
            rejectUnauthorized: false
          });
        const {data:result} = await Request({baseURL: 'https://host',url:"/api",httpAgent:agent })
        console.log(result);
    } catch (error) {
        console.log(error);
    }
}`

Sometimes in NodeJS I created instances for large project. Here is an example

**Comment by flacatus** [comment]
```javascript
const axios = require('axios'),
    Request_Instance = axios.create();

const Request = ({baseURL, method, url, httpAgent}) => Request_Instance({
    baseURL:baseURL,
    url:url,
    method : method,
    httpAgent:httpAgent
});

const GetSomething = async () => {
    try {
        // Example to skip SSl Verification, also could speicify in the https agent
        // the CAs etc
        const agent = new https.Agent({  
            rejectUnauthorized: false
          });
        const algo = await Request({baseURL: 'http://someurl',url:"/api",httpAgent:agent })
        console.log(algo);
    } catch (error) {
        console.log(error);
    }
}
```

**Comment by rhopp** [comment]
I would like to back up a bit with a few questions:
What problem are we trying to solve here?
Is there even a problem to solve?
