### ISSUE TITLE
Impossible to open a terminal in the latest (next) Che-Theia build

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16124]
### Describe the bug

It looks like this commit affected on the terminal in Che-Theia https://github.com/eclipse-theia/theia/commit/4467ef4

### Che version

 - [x] nightly

### Steps to reproduce

1. Run workspace with the latest (next) Che-Theia editor.
2. Open a terminal in any container or run a command from `My Workspace` view.

### Expected behavior

Running terminal.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![Screenshot from 2020-02-25 11-43-46](https://user-images.githubusercontent.com/1655894/75235379-ce071a80-57c4-11ea-94b4-79e900ad78b6.png)

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by RomanNikitenko** [comment]
the issue will be fixed by merging https://github.com/eclipse/che-theia/pull/635

**Comment by RomanNikitenko** [comment]
the PR  https://github.com/eclipse/che-theia/pull/635 was merged, so I'm closing the issue, feel free to reopen if you can still reproduce it.
