### ISSUE TITLE
[workspace-operator] `operator-sdk generate openapi` is broken.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16120]
### Describe the bug
Something is amiss in the https://github.com/che-incubator/che-workspace-operator repo:

With operator-sdk v0.12.0, `operator-sdk generate openapi` fails:
```
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [workspace:[v1alpha1], ] 
Error: error generating CRD for Group workspace Version v1alpha1 Kind DevFileSpec
Usage:
  operator-sdk generate openapi [flags]
```

The first commit in which this is broken is [`7a3d45c`](https://github.com/che-incubator/che-workspace-operator/commit/7a3d45c9121ba7079fd3d8c8dea19bbc4a8942bc).

**Comment by tolusha** [comment]
We use v0.10.0 for `che-operator` why we use a different version for `workspace-operator` ?

**Comment by sleshchenko** [comment]
@tolusha We use the same version as devworkspace-api use https://github.com/che-incubator/devworkspace-api
The most significant change v0.12.0 operator-sdk use go modules by default.
Maybe it's time to move Che Operator to Go modules as well and upgrade OperatorSDK version? )
