### ISSUE TITLE
Replace deprecated extensions with VS Code builtins

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#16133]
### Is your task related to a problem? Please describe.
According to the upcoming changes in Theia upstream (https://github.com/eclipse-theia/theia/pull/6933) there is a need to remove from Che-Theia assembly deprecated extensions and use VS Code builtins instead.

List of deprecated extensions:
- **`@theia/debug-nodejs` - used in `@eclipse-che/theia-assembly`**
- **`@theia/editorconfig` - used in `@eclipse-che/theia-assembly`**
- `@theia/java` - not used
- `@theia/java-debug` - not used
- **`@theia/merge-conflicts` - used in `@eclipse-che/theia-assembly`**
- `@theia/python` - not used
- `@theia/textmate-grammars` - not used
- **`@theia/tslint`  - used in `@eclipse-che/theia-assembly`**
- `@theia/typescript` - not used

**Comment by benoitf** [comment]
note that for some extensions, we're already not using them.

**Comment by vzhukovskii** [comment]
@benoitf updated description and added information about used extensions

**Comment by benoitf** [comment]
thanks

**Comment by azatsarynnyy** [comment]
closed in https://github.com/eclipse/che-theia/pull/643
