### ISSUE TITLE
Helm binary is missing when using OpenShift Connector extension

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#16130]
### Describe the bug

When using the OpenShift connector, the helm binary is not provided

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify 7.8.0 on che.openshift.io

### Steps to reproduce

1. Create a workspace with OpenShift Connector
2. Click on Kubernetes perspective
3. Click on helm repos
4. "Unable to lst Helm repos" and popup mentioing missing depdencies

### Expected behavior

in Che I would expect all dependencies to be pre-installed

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2020-02-25 15-03-25](https://user-images.githubusercontent.com/1105127/75255023-95296e80-57e1-11ea-8ae6-a2c0822c3975.png)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: please specify che.openshift.io

### Additional context

The OpenShift Connector extension has a dependency on the Kubernetes.
The [OpenShift Connector sidecar](https://github.com/che-dockerfiles/che-sidecar-openshift-connector/blob/0.1.2/Dockerfile) doesn't inherit from the [Kubernetes sidecar ](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/blob/804f9a54ecc5b321574ace98644ebd21012d105d/Dockerfile#L28)and it is missing the helm binary.
Also:
- it has a different version of Kubectl.
- the OpenShift image doesn't ensure that which and nodejs are installed which seems [prerequisites for soem actions](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/blob/804f9a54ecc5b321574ace98644ebd21012d105d/Dockerfile#L31)

To ensure that all depdencies are available and up to date i think that the OpenShift Connector sidecar should inherit from the Kubernetes sidecar

**Comment by ericwill** [comment]
Is this something you plan to work on? If not we can take it in the next sprint.

**Comment by apupier** [comment]
If you can take it in next sprint that will be great. thanks!
