### ISSUE TITLE
Go tasks not terminating

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16141]
### Describe the bug
When you run tasks like `test outyet` within the golang example project, the test is executed and finished, but there is no exit code returned and the task stays in the running state indefinitely, therefore preventing us from running any other tasks.

When the `test outyet` is executed, it's impossible to terminate the task.

This bug also causes other tasks to not start at all.

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: 7.8.0

### Steps to reproduce
* Chose `Go` example in the getting started dashboard
* Run `test outyet` task
* Wait for it to finish, but the task remains running
* Try to run the task again and choose Terminate - nothing happens
* Try to execute any other task - won't start

### Expected behavior
* `test outyet` should return an exit code and terminate
* running a go task shouldn't prevent us from running other tasks

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`) 4.2, 4.3
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl  -a operator -p openshift [--tls --self-signed-cert] <- these are optional
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: ocp42.codereadyqe.com, rhopp-ocp43.devcluster.openshift.com

**Comment by RomanNikitenko** [comment]
@ScrewTSW 
thank you for reporting the issue!

I tried it on che.openshift.io 
![version](https://user-images.githubusercontent.com/5676062/75388614-f76f9580-58ed-11ea-903a-56ce93f057c4.png)

and can not reproduce the issue.

I did it like:
https://youtu.be/5xBTQHh6vsg

![go_bug](https://user-images.githubusercontent.com/5676062/75389053-9a281400-58ee-11ea-9535-ab0f48f71b4d.gif)

Maybe some additional steps?
Can you reproduce it permanently?

thanks in advance!

**Comment by ScrewTSW** [comment]
@RomanNikitenko Hello.
Yesterday we have been trying it with @rhopp on 7.10.0 snapshot and the behavior was flaky. Sometimes the exit code was returned and the task terminated correctly, sometimes it didn't but at least in 7.10.0 it didn't prevent me from executing different tasks, or restarting the same task.

I am currently implementing a periodic test for Go devfile, so I would get back to you once we have more data collected from running the same operation on the go devfile in tests and seeing how often the issue appears.

**Comment by vitaliy-guliy** [comment]
It looks like the issue is not relevant anymore, works fine with latest Che 7.15.1.
It was tested on local minikube and on che.openshift.io.

![Screenshot from 2020-07-16 16-25-51](https://user-images.githubusercontent.com/1655894/87677965-082c8500-c783-11ea-8ea6-b8bde0017557.png)
