### ISSUE TITLE
unable to close multiple tabs with repeated presses of keyboard shortcut

### ISSUE THREAD

**Issue by digiltd** [eclipse-che/che#16140]
### Describe the bug
When you have multiple tabs open in Theia and the focus on one tab, then try to close tabs one by one by pressing `option` + `w`, you end up closing terminal, explorer, source control etc rather than the next tab. 

You have to click into each tab before pressing the shortcut, which does mean the "shortcut" ends up taking more actions than simply closing the tab with the mouse with one click :) 

### Che version

Che-Theia@caefb8b using Theia@e1d08d00

### Steps to reproduce

Open multiple files in the IDE, press `option` + `w` to close the first, and repeat the shortcut to close the others.

### Expected behavior

Each file open in a tab is closed one after the other with each press of the shortcut.

### Screenshots

https://vimeo.com/393469169/9044019480

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ x] macOS
   - [ ] Cloud
       - [ x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
@vzhukovskii can you check it on Mac, and file a corresponding issue in upstream Theia if it's reproducible. Thanks!

**Comment by vzhukovskii** [comment]
At this moment in che 7.18.0 this hotkey works as expected. It closes the next editor tab after pressing it sequentially.

**Comment by azatsarynnyy** [comment]
Most likely, it has been fixed upstream. Thank you @vzhukovskii for verifying it!
