### ISSUE TITLE
I can't install - alternative to Eclipse CHE

### ISSUE THREAD

**Issue by wictrix** [eclipse-che/che#16156]
For weeks I have been trying to install EClipse CHE on a Centos 7 server. I tried with Minikube, Minishift and Virtualbox, they all fail to timeout when trying to run the "Che POD" image.
I checked all the issues on the subject and who had the same problem had no answer.
My question now is, is there an alternative IDE with the same characteristics?

**Comment by tolusha** [comment]
Could you provide some details of your issues?
Do you have some logs, How did you deploy Che ?

**Comment by wictrix** [comment]
Order:
1. Installed minikube using native package management for CentOS: https://kubernetes.io/docs/tasks/tools/install-kubectl/

2. Installed chctl according to:
https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/

3. Started minikube in root:
#minikube start --memory = 8192 --vm-driver = none

4. Started chectl rm root:
#chectl server: start --platform minikube --multiuser

/ * Result:
Eclipse Che pod bootstrap
      ✔ scheduling ... done.
      ✔ downloading images ... done.
      ✖ starting
        → ERR_TIMEOUT: Timeout set to pod ready timeout 130000
/ * LOGs
== events.txt
che-854fdddf65-42hrb.15f743308fa3adb8 Pod spec.containers {che} Warning Unhealthy kubelet, minikube Readiness probe failed: Get http://172.17.0.9:8080/api/system/state: net / http: request canceled (Client.Timeout exceeded while awaiting headers)

 che-854fdddf65-42hrb.15f743340dd7ca3a Pod spec.containers {che} Warning Unhealthy kubelet, minikube Readiness probe failed: HTTP probe failed with statuscode: 500

== che.log
[ost-startStop-1] [ERROR] [o.a.c.c.C. [. [localhost]. [/ api] 182] - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheB
ootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://keycloak-che.10.25.30.5.nip.io/auth/realms/che/.well-known/openid-configuration

== keyloak.log
================================================== =======================

  Using PostgreSQL database

 WARN [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost

**Comment by tolusha** [comment]
@wictrix 
Thank you for reporting. We are working on this right now.

**Comment by tolusha** [comment]
@wictrix 
Could you try pls
```bash
chectl update
chectl server:start --platform=minikube --installer=operator
```

**Comment by wictrix** [comment]
Order:
1. # chectl update
chectl: Updating CLI ... already on latest version: 7.9.0

2. # chectl server: start --platform = minikube --installer = operator
   ✔ Keycloak pod bootstrap
       ✔ scheduling ... done.
       ✔ downloading images ... done.
       ✔ starting ... done.
     ❯ Devfile registry pod bootstrap
       ✖ scheduling
         → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
         downloading images
         starting
       Registry pod bootstrap plugin
       Eclipse Che pod bootstrap
       Retrieving Eclipse Che Server URL
       Eclipse Che status check
  ›Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined

/ * LOGs:
== events.txt
events.txt:25m         3h           47        che-854fdddf65-42hrb.15f743308fa3adb8                Pod       spec.containers{che}                    Warning   Unhealthy   kubelet, minikube   Readiness probe failed: Get http://172.17.0.9:8080/api/system/state: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
events.txt:6m          3h           614       che-854fdddf65-42hrb.15f743340dd7ca3a                Pod       spec.containers{che}                    Warning   Unhealthy   kubelet, minikube   Readiness probe failed: HTTP probe failed with statuscode: 500
events.txt:36m         3h           86        che-854fdddf65-42hrb.15f7435df68cb479                Pod       spec.containers{che}                    Warning   Unhealthy   kubelet, minikube   Readiness probe failed: Get http://172.17.0.9:8080/api/system/state: dial tcp 172.17.0.9:8080: connect: connection refused
events.txt:1m          3h           337       che-854fdddf65-42hrb.15f7450327c8f223                Pod       spec.containers{che}                    Warning   BackOff     kubelet, minikube   Back-off restarting failed container
events.txt:16s         16s          1         plugin-registry-6d94b964db-ddf7c.15f74ef18d54b0c6    Pod       spec.containers{che-plugin-registry}    Warning   Unhealthy   kubelet, minikube   Readiness probe failed: Get http://172.17.0.8:8080/plugins/: dial tcp 172.17.0.8:8080: connect: connection refused
events.txt:5s          15s          2         postgres-798dd98846-hczc8.15f74ef1d9fd6337           Pod       spec.containers{postgres}               Warning   Unhealthy   kubelet, minikube   Readiness probe failed: sh: cannot set terminal process group (-1): Inappropriate ioctl for device
events.txt:0s        20s       3         postgres-798dd98846-hczc8.15f74ef1d9fd6337   Pod       spec.containers{postgres}   Warning   Unhealthy   kubelet, minikube   Readiness probe failed: sh: cannot set terminal process group (-1): Inappropriate ioctl for device
events.txt:<unknown>   <unknown>   0         postgres-745bff8bcb-s94x4.15f74ef7642edb18   Pod                 Warning   FailedScheduling   default-scheduler   persistentvolumeclaim "postgres-data" is being deleted
events.txt:<unknown>   <unknown>   0         postgres-745bff8bcb-s94x4.15f74efb2eafac90   Pod                 Warning   FailedScheduling   default-scheduler   persistentvolumeclaim "postgres-data" is being deleted
events.txt:<unknown>   <unknown>   0         postgres-745bff8bcb-s94x4.15f74efb2eafac90   Pod                 Warning   FailedScheduling   default-scheduler   persistentvolumeclaim "postgres-data" is being deleted
events.txt:<unknown>   <unknown>   0         postgres-745bff8bcb-s94x4.15f74f0d3724e182   Pod                 Warning   FailedScheduling   default-scheduler   persistentvolumeclaim "postgres-data" not found
events.txt:<unknown>   <unknown>   0         postgres-745bff8bcb-s94x4.15f74f0d3724e182   Pod                 Warning   FailedScheduling   default-scheduler   persistentvolumeclaim "postgres-data" not found
events.txt:0s        0s        1         keycloak-b566577f6-lvr6s.15f74f67711d0fdf   Pod       spec.containers{keycloak}   Warning   Unhealthy   kubelet, minikube   Readiness probe failed: Get http://172.17.0.6:8080/auth/js/keycloak.js: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
events.txt:0s        0s        1         che-85bbd945db-ctr8m.15f74f79df7c93b8   Pod       spec.containers{che}   Warning   Unhealthy   kubelet, minikube   Readiness probe failed: Get http://172.17.0.9:8080/api/system/state: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
events.txt:0s        0s        1         che-85bbd945db-ctr8m.15f74f7b09a790de   Pod       spec.containers{che}   Warning   Unhealthy   kubelet, minikube   Readiness probe failed: HTTP probe failed with statuscode: 500
events.txt:0s        0s        1         che-85bbd945db-ctr8m.15f74fa0f56c6594   Pod       spec.containers{che}   Warning   Unhealthy   kubelet, minikube   Liveness probe failed: HTTP probe failed with statuscode: 500
events.txt:<unknown>   <unknown>   0         postgres-745bff8bcb-s94x4.15f74f0d3724e182   Pod                 Warning   FailedScheduling   default-scheduler   persistentvolumeclaim "postgres-data" not found
events.txt:0s        9m        44        che-85bbd945db-ctr8m.15f74f7b09a790de   Pod       spec.containers{che}   Warning   Unhealthy   kubelet, minikube   Readiness probe failed: HTTP probe failed with statuscode: 500

== keyloak.log
13:01:07,854 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
WARNING: POSTGRES_DATABASE variable name is DEPRECATED replace with DB_DATABASE
WARNING: POSTGRES_USER variable name is DEPRECATED replace with DB_USER
WARNING: POSTGRES_PASSWORD variable name is DEPRECATED replace with DB_PASSWORD
WARNING: POSTGRES_PORT variable name is DEPRECATED replace with DB_PORT
13:01:14,542 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
13:01:19,343 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
13:01:23,393 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 52) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments running multiple servers. Please make sure the attribute value is unique.
13:01:24,212 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
13:01:24,680 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.openshift4-extension-6.0.1.jar" is using a private module ("org.keycloak.keycloak-server-spi-private") which may be changed or removed in future versions without notice.
13:01:24,681 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.openshift4-extension-6.0.1.jar" is using a private module ("org.keycloak.keycloak-services") which may be changed or removed in future versions without notice.
13:01:24,740 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-2) WFLYSRV0018: Deployment "deployment.keycloak-server.war" is using a private module ("org.kie") which may be changed or removed in future versions without notice.
13:01:25,841 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0273: Excluded subsystem weld via jboss-deployment-structure.xml does not exist.
13:01:25,841 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0273: Excluded subsystem webservices via jboss-deployment-structure.xml does not exist.
13:01:35,478 WARN  [org.keycloak.services] (ServerService Thread Pool -- 65) KC-SERVICES0104: Not creating user admin. It already exists.

**Comment by wictrix** [comment]
/* Complement
Accessing https://10.25.30.5:8443/  return:

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

**Comment by tolusha** [comment]
unfortunately I can't reproduce the issue
Could you try from the scratch?
1. minikube delete
2. minikube start --cpus 4 --memory 10240 --disk-size=50GB --vm-driver=virtualbox
3. chectl server:start --platform minikube --multiuser

**Comment by wictrix** [comment]
Using this configuration with Virtualbox the installation returned "Command server: start has completed successfully."

Retrieving Eclipse Che Server URL ... http: //che-che.192.168.99.102.nip.io

However the URL points to an IP that is probably internal to the VM, as I don't know VIrtualbox is there a tutorial that explains how to release access to the network?

**Comment by wictrix** [comment]
I appreciate the help attempts.

But unfortunately as we were unable to deploy Eclipse / CHE for use by the team on an internal network, we opted not to use Eclipse / CHE as an IDE in our company.
