### ISSUE TITLE
Single User Eclipse Che returns "308 Permanent Redirect" response

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16159]
### Describe the bug
Single User Eclipse Che on minikube returns "308 Permanent Redirect" error:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/889/console
```
curl che-che.10.0.100.182.nip.io -v
* About to connect() to che-che.10.0.100.182.nip.io port 80 (#0)
*   Trying 10.0.100.182...
* Connected to che-che.10.0.100.182.nip.io (10.0.100.182) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: che-che.10.0.100.182.nip.io
> Accept: */*
> 
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.15.9
< Date: Thu, 27 Feb 2020 13:30:27 GMT
< Content-Type: text/html
< Content-Length: 171
< Connection: keep-alive
< Location: https://che-che.10.0.100.182.nip.io/
< 
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
* Connection #0 to host che-che.10.0.100.182.nip.io left intact
```
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Install minikube 1.1.1.
2. Download chectl.
3. Install Eclipse Che by command 
> chectl server:start --k8spodreadytimeout=360000 --platform=minikube --listr-renderer=verbose --skip-version-check

4.Go to Eclipse Che main page

### Expected behavior
Eclipse Che Dashboard has been opened.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1

> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] [chectl:next](https://github.com/che-incubator/chectl/releases/tag/20200227121612) with Helm installer
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

### Eclipse Che Logs
- [All logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/889/artifact/logs-and-configs/che-logs/)
- [Che server logs](https://gist.github.com/dmytro-ndp/17afc6c51b9890631507bc55483db64e)

**Comment by mshaposhnik** [comment]
It seems that something making redirect to `https` protocol while che deployed as `http`

**Comment by tolusha** [comment]
https is a default in case of installation using helm

**Comment by dmytro-ndp** [comment]
Thanks for explanation, @mshaposhnik, @tolusha.

**Comment by dmytro-ndp** [comment]
It turned out that it was expected behavior after chectl had started installing Eclipse Che in TLS mode by default using Helm.
