### ISSUE TITLE
chectl failed to install Che on ROKS cluster due to namespace creation failure

### ISSUE THREAD

**Issue by jagraj** [eclipse-che/che#16150]
### Describe the bug
`chectl` failed to create namespace when installing Che. As a user I can create with out any problem with the same user that I logged in but chectl failed to create namespace and exits installation with the following error.

```
chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=setup/install_che/che-operator/codewind-checluster.yaml --che-operator-image=quay.io/eclipse/che-operator:7.5.1 -n che2
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che2"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
    ✔ Check OpenShift version: Unknown.
    ✔ Check Kubernetes version: Unknown.
Eclipse Che logs will be available in '/var/folders/0r/qzqvjrx918x9255mf_c53h7w0000gn/T/chectl-logs/1582288986532'
  ✔ Start following logs
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Eclipse Che will be deployed in Multi-User mode as 'operator' installer supports only that mode.
  ❯ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✖ Create Namespace (che2)
      → Unable to connect to the server: net/http: TLS handshake timeout
      Create ServiceAccount che-operator in namespace che2
      Create Role che-operator in namespace che2
      Create ClusterRole che-operator
      Create RoleBinding che-operator in namespace che2
      Create ClusterRoleBinding che-operator
      Create CRD checlusters.org.eclipse.che
      Waiting 5 seconds for the new Kubernetes resources to get flushed
      Create deployment che-operator in namespace che2
      Create Eclipse Che Cluster eclipse-che in namespace che2
 ›   Error: Error: Command failed with exit code 1: oc new-project che2
 ›   Unable to connect to the server: net/http: TLS handshake timeout
 ›   Installation failed, check logs in '/var/folders/0r/qzqvjrx918x9255mf_c53h7w0000gn/T/chectl-logs/1582288986532'
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [x ] other: 7.5.1

### Expected behavior
`chectl` should create project/namespace if one does not exist if the user has access to create one on cluster.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ x] Openshift (include output of `oc version`)
```
Client Version: 4.3.0-0.nightly-2020-02-17-110952
Kubernetes Version: v1.16.2
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x ] chectl 
```
chectl/0.0.20200219-next.3776510 darwin-x64 node-v10.19.0
```
   - [ X] che-operator 
7.5.1
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [X ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ X] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [X ] IBM Cloud 
   - [ ] other: please specify

**Comment by tolusha** [comment]
Could you run the command from the terminal?
```bash
oc new-project che2
```

**Comment by jagraj** [comment]
@tolusha 
My workaround was to create project first and then run `chectl` to install che. Some how chectl does not create project if one does not exist any more.

**Comment by tolusha** [comment]
it is weird, 
```
Unable to connect to the server: net/http: TLS handshake timeout
```
It is more connection issue.
