### ISSUE TITLE
Git extension: cannot exec askpass.sh

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16152]
### Describe the bug

When I try to push my changes to a remote git repository for the first time using "Publish Branch" on the git extension menu I get an error message:

```
Git: fatal: cannot exec '/default-theia-plugins/vscode-git/extension/out/askpass.sh': Permission denied
```

And if I look at askpass.sh attributes it's indeed not executable and own by root:

```
bash-4.4$ ls -l /default-theia-plugins/vscode-git/extension/out/askpass.sh
-rw-rw-r--    1 0        root           207 Feb 26 00:52 /default-theia-plugins/vscode-git/extension/out/askpass.sh
``` 

### Che version

Nightly (9.10-SNAPSHOT)

### Steps to reproduce

- Install single user Che with chectl (platform=minikube, installer=helm)
- Start a workspace using chectl (`chectl workspace:start --devfile=https://github.com/eclipse/che-docs`)
- Changes some files
- Open the SCM view and select "Publish Branch" 

### Runtime
kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

minikube
```
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff
```

### Screenshots

![image](https://user-images.githubusercontent.com/606959/75415069-ceb9c100-592a-11ea-9ffc-ead0e4dfc689.png)

![image](https://user-images.githubusercontent.com/606959/75414955-7387ce80-592a-11ea-981c-d94daa2ea1f3.png)

### Installation method

`chectl server:start --platform=minikube --installer=helm`

### Environment

my computer /  macOS

**Comment by l0rd** [comment]
cc @vinokurig

**Comment by benoitf** [comment]
it's a dup of https://github.com/eclipse/che/issues/16084
