### ISSUE TITLE
[chectl] server:start installed Single User Eclipse Che without TLS mode by default on minikube using helm installer

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16168]
### Describe the bug
server:start installed Single User Eclipse Che without TLS mode by default on minikube using helm installer
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/898/console

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Install minikube 1.1.1.
2. Download chectl.
3. Install Eclipse Che by command 
> chectl server:start --k8spodreadytimeout=360000 --platform=minikube --listr-renderer=verbose --skip-version-check

4.Go to Eclipse Che main page using https protocol
5.Go to Eclipse Che main page using http protocol

### Expected behavior
4. Eclipse Che Dashboard has been opened by https protocol.
5. Eclipse Che Dashboard returns "404 Not Found" error by http protocol

### Current unexpected behavior
4. Eclipse Che Dashboard returns "404 Not Found" error by https protocol.
```
curl -k -sL -I https://che-che.10.0.101.94.nip.io -v
* About to connect() to che-che.10.0.101.94.nip.io port 443 (#0)
*   Trying 10.0.101.94...
* Connected to che-che.10.0.101.94.nip.io (10.0.101.94) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=Kubernetes Ingress Controller Fake Certificate,O=Acme Co
* 	start date: лют 28 07:20:14 2020 GMT
* 	expire date: лют 27 07:20:14 2021 GMT
* 	common name: Kubernetes Ingress Controller Fake Certificate
* 	issuer: CN=Kubernetes Ingress Controller Fake Certificate,O=Acme Co
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: che-che.10.0.101.94.nip.io
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.15.9
< Date: Fri, 28 Feb 2020 07:26:17 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 21
< Connection: keep-alive
< 
* Connection #0 to host che-che.10.0.101.94.nip.io left intact
```
5. Eclipse Che Dashboard has been opened by http protocol

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1

> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] [chectl:next](https://github.com/che-incubator/chectl/releases/tag/20200227160618) with Helm installer
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

### Reference
https://github.com/che-incubator/chectl/commit/065ae1d54cb0938ecd393d106acf075188c32ce8

**Comment by mmorhun** [comment]
@dmytro-ndp could you please test it again but using `run` command instead of `chectl` ?

**Comment by tolusha** [comment]
@dmytro-ndp How did you install `chectl` ?

**Comment by dmytro-ndp** [comment]
@tolusha: chectl had been downloaded from [here](https://github.com/che-incubator/chectl/releases/download/20200227160618/chectl-linux-x64.tar.gz)

**Comment by tolusha** [comment]
Use `./chectl` instead of `chectl` in this case if you under bin folder

**Comment by dmytro-ndp** [comment]
@tolusha: full used command is:
```
  /usr/local/bin/chectl server:start \
   --k8spodreadytimeout=360000 \
   --platform=minikube \
   --listr-renderer=verbose \
   --skip-version-check
```

**Comment by tolusha** [comment]
`/usr/local/bin/chectl version` ?

**Comment by dmytro-ndp** [comment]
@tolusha: you can find version in the [build logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/898/console):
```
SUCCESS: installation log written in /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/chectl-install.log
chectl/0.0.20200227-next.065ae1d linux-x64 node-v10.19.0
```
That is output of [install_chectl.sh](https://www.eclipse.org/che/chectl/) which downloads and installs chectl, and call `chectl version` command during execution.

**Comment by tolusha** [comment]
@dmytro-ndp 
thank you. we got it!
