### ISSUE TITLE
UD debug doesn't work in the case with CA certificate

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#16160]
### Describe the bug

UD debug doesn't work in the case with CA certificate.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1.
```sh
$ git clone git@github.com:eclipse/che.git
```
2.
```sh
cd che/dashboard
$ mvn -Pnative clean install
```
3.
```sh
$ gulp serve
```

The error is: "...has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2020-02-27 15-56-44](https://user-images.githubusercontent.com/6310786/75451821-d81e4a00-5979-11ea-9262-17a55665f260.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
The was this is reported it sounds like a development time issue and therefore P2.
