### ISSUE TITLE
Dashboard.waitPage should not depend on menu

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16165]
### Is your task related to a problem? Please describe.
The Dashboard.waitPage method waits for the specific items in a left menu. This menu can be configured, so we should change the logic of this method to prevent the test to fail.

### Describe the solution you'd like
Replace waiting for menu items by waiting for some other element, that is not configurable.

### Describe alternatives you've considered
Another possible solution is to check just `Workspaces` as this item should be there every time. But I would prefer more the first solution.

**Comment by ibuziuk** [comment]
PR with workaround on Hosted Che side - #1814 (should be removed once the issue is fixed in the upstream)
