### ISSUE TITLE
[DOCS] Document "Deploy Che with self signed TLS certificates on Kubernetes" provide misleading information about secret name

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16169]
### Describe the bug

According to our documentation https://www.eclipse.org/che/docs/che-7/setup-che-in-tls-mode-with-self-signed-certificate/#deploy-che-with-self-signed-tls-on-kubernetes_setup-che-in-tls-mode-with-self-signed-certificate
it has to be `self-signed-cert` . But in code we have 

- https://github.com/eclipse/che-operator/blob/master/pkg/deploy/deployment_che.go#L49 `self-signed-certificate`
- https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values/tls.yaml#L13 `che-tls`
- https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml#L46 `che-tls`

### Che version

 - [X] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
- Follow the doc https://www.eclipse.org/che/docs/che-7/setup-che-in-tls-mode-with-self-signed-certificate/#deploy-che-with-self-signed-tls-on-kubernetes_setup-che-in-tls-mode-with-self-signed-certificate
 - Che failed to start

### Expected behavior
Che working

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [X] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)
```
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff
```
```
chectl/0.0.20200227-next.065ae1d darwin-x64 node-v10.19.0
```

### Installation method
   - [X] chectl  `chectl server:start --platform=minikube --installer=operator --tls --self-signed-cert`
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tolusha** [comment]
https://github.com/eclipse/che-docs/pull/1137/files
