### ISSUE TITLE
Google Eclipse Plugin - is or will there be a GWT plugin for Che ?

### ISSUE THREAD

**Issue by biancashouse** [eclipse-che/che#1617]
My GWT + Appengine maven project builds fine outside of Eclipse, but of course editing GWT java is much more convenient inside Eclipse. 

Is there something available yet that is GWT classpath aware etc ?

**Comment by TylerJewell** [comment]
@biancashouse - yes, there is.  We have a GWT plugin also with GWT-specific commands to enable super dev mode.  Eclipse Che's IDE was written entirely in GWT, so we have extensive use of it internally and needed this plugin so that we could build che in che.

**Comment by ghost** [comment]
@biancashouse if you elaborate on your use case, perhaps share your app and how you work with it locally, I can help you with authoring the right commands and setting up super dev mode.

**Comment by biancashouse** [comment]
So are there plans to make your GWT plugin available to us ?
I'll stick with Mars until something arrives.
Thanks.

**Comment by ghost** [comment]
@biancashouse what @TylerJewell meant is a command line approach to GWT. So, it's about running commands.

**Comment by TylerJewell** [comment]
@biancashouse - the GWT plugin for Che ships within the product.

**Comment by biancashouse** [comment]
Hi Tyler, the GWT plugin is not mentioned on page:
https://eclipse-che.readme.io/docs/plug-ins

Are you saying that if I move my existing maven appengine GWT project into
Che it will recognise my *Service.java and generate the .Async.java like
the Google Plugin for Eclipse does etc etc ?

Ian

**Comment by TylerJewell** [comment]
@biancashouse - it was not our goal to copy the Eclipse GWT plugin directly.  But we have full support for GWT command line options and dynamic classpath generation.  Your project, if configured correctly, should work within Che.

**Comment by biancashouse** [comment]
Sounds good. I'm looking fwd to giving it a try... Will let you know...
Thanks, Ian
