### ISSUE TITLE
[workspace-loader] After workspace startup, fails to redirect with "Failed to get the workspace: "Unknown error""

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#16170]
### Describe the bug
Sometimes, probably when token expires during the workspace startup, workspace-loader fails to redirect to Theia with error:
```
Error: Failed to get the workspace: "Unknown error"
```
![image](https://user-images.githubusercontent.com/1215011/75550551-6e15ab80-5a32-11ea-8a46-7d7856451207.png)

Note, that the workspace is really running and refreshing browser/opening the workspace again works fine.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

This bug is intermittent and happens during workspace startup. Just create workspace using dashboard and open it (without starting previously)

### Expected behavior
Theia is successfully opened after workspace startup

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other - Openshift on Openstack
   - [ ] other: please specify

#### Browser logs:
```
[KEYCLOAK] Estimated time difference between browser and server is 1 seconds
keycloak.js:456 [KEYCLOAK] Refreshing token: token expired
keycloak.js:484 [KEYCLOAK] Token refreshed
keycloak.js:831 [KEYCLOAK] Estimated time difference between browser and server is 1 seconds
VM891:1 POST https://che-rhopp-che.apps.ocp43.codereadyqe.com/api/workspace/workspace9ayeq8nn1xsdp31g/runtime 500
keycloak.js:456 [KEYCLOAK] Refreshing token: token expired
keycloak.js:456 [KEYCLOAK] Refreshing token: token expired
VM908:1 GET https://che-rhopp-che.apps.ocp43.codereadyqe.com/api/workspace/workspacemkw2dh3oz8dy2uzz 401
keycloak.js:484 [KEYCLOAK] Token refreshed
keycloak.js:831 [KEYCLOAK] Estimated time difference between browser and server is 1 seconds
```

**Comment by tolusha** [comment]
duplicates 
https://github.com/eclipse/che/issues/15922
