### ISSUE TITLE
Timeline for multi-cursor visuals?

### ISSUE THREAD

**Issue by shadowcodex** [eclipse-che/che#1618]
Wondering when the multi-cursor visuals feature will be implemented?

**Comment by TylerJewell** [comment]
Soonish - hard to know exact timeline as there hasn't been a pull request issued for it. All work has been done in a side branch.  @sunix may have more details.

**Comment by TylerJewell** [comment]
@sunix - any update on timing?

**Comment by TylerJewell** [comment]
There is a pull request open on this.
https://github.com/eclipse/che/pull/2131

**Comment by TylerJewell** [comment]
Closing this issue so that the PR can be tracked instead.
