### ISSUE TITLE
python needs to be updated to 2020.9.111407

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16183]
A new version of the python plugin is available upstream at:
https://github.com/Microsoft/vscode-python

**Comment by ericwill** [comment]
Looks like the upstream Theia PR (https://github.com/eclipse-theia/theia/pull/7718) has been merged, we should probably check to see if we are still missing anything.

**Comment by svor** [comment]
@ericwill should it be updated to 2020.4.76186 or to the latest one?

**Comment by ericwill** [comment]
> @ericwill should it be updated to 2020.4.76186 or to the latest one?

Latest if it works.

**Comment by svor** [comment]
Latest ms-python extension doesn't work with Theia. The issue described the problem is here https://github.com/eclipse-theia/theia/issues/8022

**Comment by ericwill** [comment]
A note, for whenever this issue gets worked on: the sidecar needs to be updated, and laid out using the new repo format.

**Comment by tsmaeder** [comment]
@ericwill  what is "the new repo layout" for sidecar images? We're talking about github.com/che-dockerfiles/che-sidecar-python?

**Comment by benoitf** [comment]
new repo layout is the structure content of the repo https://github.com/che-dockerfiles/che-sidecar-python that is using branches per versions while now we introduced 'master branch' for upcoming version + VERSION + PLATFORMS files etc

example of new layout:
https://github.com/che-dockerfiles/che-sidecar-java
