### ISSUE TITLE
.devfile.yml not picked up 

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#16193]
### Describe the bug

IDE configuration files should not be forced visible into users project.
`.devfile.yml` is mentioned in places as it should work but when I put `.devfile.yml` che.openshift.io always ignores it.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: che.openshift.io 2020-03-01
### Steps to reproduce
add .devfile.yml and see it be ignored.

### Expected behavior

che should honor both devfile.yml and .devfile.yml

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
@maxandersen duplicate https://github.com/eclipse/che/issues/14548?

**Comment by ibuziuk** [comment]
Closing as duplicate - https://github.com/eclipse/che/issues/14548
