### ISSUE TITLE
Autosave + formatter misbehavior in default stacks

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16194]
### Describe the bug
Linter is too fast and editing a Java file in this example devfile is uncomfortable. The linter e.g. removes default indention when the user wants to add a new line and type some code to it.

This behavior is reproducible in `NodeJS Angular Web Application` and `java with Spring Boot and MySQL` default stacks.

### Che version

 - [x] latest 7.9.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Go to Workspace -> Add Worksapce
 - Create and open `Java with Spring Boot and MySQL` workspace with default configuration
 - Open src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java
 - Wait for language server to be ready
 - Go to end of a line 32
 - Press Enter
 - The cursor is set to the correct indention but it is moved to the beginning of a line very fast.

### Expected behavior
The automatic linter will be turned off or will have a longer delay (the file will remain longer unsaved).

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) Hosted Che
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![lint](https://user-images.githubusercontent.com/29278800/75666622-6ba39380-5c76-11ea-8b90-5e9d7d73ca0e.gif)

**Comment by tsmaeder** [comment]
The formatter is doing the right thing here: it is formatting the file on save. The fact that autosave is on and the autosave timeout is not language specific IMO.

**Comment by ibuziuk** [comment]
Looks like a perfect example of the UX issue - both autosave & formatter do the right things providing a poor UX to the end-user :/

It looks like the autosave should be not time-based, but rather focus based (e.g. a file is saved when the focus lost). Hot-fix might be increasing the autosave time.

**Comment by tsmaeder** [comment]
IMO autosave is a misfeature when editing structured content like program code. We turned it off in the devfile editor because it was so annoying and I'm very happy about it.

**Comment by azatsarynnyy** [comment]
see https://github.com/eclipse/che/issues/18096#issuecomment-722593141
