### ISSUE TITLE
[Dashboard / Getting Started / UX] rectangular icons are truncated

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16204]
### Is your enhancement related to a problem? Please describe.

Square icons look fine. Rectangular ones (eg., php, quarkus, .net) are truncated.

![image](https://user-images.githubusercontent.com/227597/75701961-a8758780-5c82-11ea-9f56-4c39fca27745.png)

### Describe the solution you'd like

Could the viewable area of the icons be widened to allow for rectangular icons?

![image](https://user-images.githubusercontent.com/227597/75702090-d2c74500-5c82-11ea-8775-48e00c1d89f5.png)

Or is this something that ought to be handled downstream via whitelabel / CSS changes? If so please explain how/where to apply such a change. 

### Describe alternatives you've considered

* Downstream override to resize images
* Downstream override to widen viewable areas

### Additional context

See also https://issues.redhat.com/browse/CRW-677

**Comment by sleshchenko** [comment]
@nickboldt Could we update icons in CRW plugin registry? They seem to be outdated. 
See 
https://github.com/eclipse/che-devfile-registry/blob/master/images/quarkus.svg
https://github.com/eclipse/che-devfile-registry/blob/master/images/dotnetcore.svg

**Comment by sleshchenko** [comment]
P.S. @olexii4 will prepare fix on dashboard side as well.
