### ISSUE TITLE
Create "Get Started" page object in E2E typescript selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16208]
### Is your task related to a problem? Please describe.
Eclipse Che 7.9.0 had introduced "**Get Started**" page as a new entry point. So, we need to have functionality to test this page in our typescript selenium tests (both upstream and downstream).
![Screenshot from 2020-03-03 11-18-16](https://user-images.githubusercontent.com/1197777/75762431-52b4e400-5d43-11ea-9050-85ec8dab7df1.png)

### Describe the solution you'd like
Create "**Get Started**" page object in E2E typescript selenium tests.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/16213
