### ISSUE TITLE
Switch workspace creation tests to Get Started page

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16209]
### Is your task related to a problem? Please describe.
The preferred way of creating workspaces from default stacks is using `Get Started` page instead of `Workspaces` page. The e2e tests should reflect this.

### Describe the solution you'd like
All devfile tests should use `Get Started` page for workspace creation instead of `Worksapces` page.

### Describe alternatives you've considered
There can be some workspace still created via `Workspaces` page to test that this functionality works as expected.

### Additional context
This issue depends on https://github.com/eclipse/che/issues/16208

**Comment by ibuziuk** [comment]
I think the creation of workspace from both "Getting Started" & "Workspaces" tabs should be covered by the tests

**Comment by rhopp** [comment]
@l0rd What are the plans in this front? Will we have two redundant pages for workspace creation, or do we want to deprecate the "old one"?

**Comment by tsmaeder** [comment]
@Katka92 I took the liberty to update the title, as I found it confusing.

**Comment by Katka92** [comment]
Devfile tests in upstream and Hosted Che are using `Get Started` page. Closing.
