### ISSUE TITLE
Workspace stop time increased sufficiently in the 7.9.0 version

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16200]
### Describe the bug
Workspace stop time increased sufficiently after the 7.9.0 update from 2 to 40 seconds

![image](https://user-images.githubusercontent.com/1461122/75686160-10849780-5c9c-11ea-86ec-1bfdafd6f04f.png)

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

- Start workspace
- Wait until started
- Stop Workspace
- Error: workspace will be marked as stopped only after 40 seconds

### Additional context
The current suspect is  `che.infra.kubernetes.pod.termination_grace_period_sec=0` that might not be set in the pod spec. By default `terminationGracePeriodSeconds` is `30` on k8s

https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L405

**Comment by amisevsk** [comment]
I checked the yaml for a deployment directly and it does contain `terminationGracePeriodSeconds: 30` whereas 7.8.0 had `terminationGracePeriodSeconds: 0`

**Comment by ibuziuk** [comment]
@amisevsk thanks, that was the main suspect ;)
