### ISSUE TITLE
Create a Deb/Rpm package to facilitate installation and configuration out of the box

### ISSUE THREAD

**Issue by carlosrodfern** [eclipse-che/che#1620]
I've been trying to setup the server and I see that it is very difficult to do. It requires a lot of steps before you can actually run the server successfully.

It would be nice if this project creates a self-contained deb/rpm package, like other open source projects (see gitlab or elasticsearch) that makes eclipse-che work out of the box.

**Comment by TylerJewell** [comment]
@carofe82 - thanks for getting in touch.  Could you comment on some thoughts we have had?

We have worked very hard to make our docker container installation of Che simple and repeatable.  We have been working towards a structure where we ask everyone including devs on their laptop to launch Che as a docker container.  The Che image is managed with tags at dockerhub.

Are there reasons that a deb or rpm package is better suited?

**Comment by carlosrodfern** [comment]
I think docker itself may be the problem. I'll explain my experience, and please excuse me for my inexperience with dockers.

1) Tried to run the che docker container from docker hub
Error: are you trying to run without the TLS support
Miss-leading error because if you run it as sudo it works.
2) sudo docker ....
some weird permission errors on /var/.../docker.sock
Gave permission, then the file doesn't exist, then there is a container already named "che" so I have to run it with a different name. Tried to delete the images and the container, and tried again... with the -net=host parameter that I missed. The /var/.../docker.sock error went away when I use the --net param. Again, error message very miss-leading.

...
3) At some point, don't remember if from the docker hub or from the bin/che.sh (installed with the self-installer jar) it was telling me that the current user UID must be 1000. Weird requirement, anyway, I tried --skip:uid (just want to get it to run)

4) Finally I got a messages from docker about version differences so I gave up.

@TylerJewell, thank you for the quick response!

**Comment by skabashnyuk** [comment]
Hello @carofe82 
To be able to better understand your problem
can you give us an output from this two simple commands?

```
docker version
docker run ubuntu /bin/echo 'Hello world'
```

Also some info about your operation system can be helpful.

**Comment by carlosrodfern** [comment]
``` sh
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

``` sh
$ docker run ubuntu /bin/echo 'Hello world'
Unable to find image 'ubuntu:latest' locally
latest: Pulling from ubuntu
143997bb556a: Pull complete 
1ee92674a984: Pull complete 
0bb1d07e4d6b: Pull complete 
7bc86777be5f: Pull complete 
2fc17c1f5db4: Pull complete 
Digest: sha256:fb6902b217019d49d0c94f0bd86ef473407d5b5182a6c5166cb84eba847b4d68
Status: Downloaded newer image for ubuntu:latest
Hello world
```

Thank you @skabashnyuk for your help. I wasn't really expecting you guys to spend time to troubleshoot this problem, I understand that part of the problem is my inexperience with dockers. I just wanted to bring the idea of creating a deb/rpm package since I think it would be easier for a user to setup.

**Comment by ghost** [comment]
@carofe82 if you feel like solving your Docker problem, do open a new issue and we'll sort things out pretty fast.

**Comment by TylerJewell** [comment]
@carofe82 - we appreciate you bringing this to our attention.  We are debating on our slack channels whether this is something we should do or not. We are debating whether a deb/rpm packaging would have eliminated your particular issue, as in all cases Docker and its proper configuration for your system is required.  It was our hope and expectation that running che as a docker container would be simple enough for most systems, but we understand that people may have the wrong docker version installed and may not understand how to setup the right docker group and `/var/run/docker.sock` permissions simply.

We have worked with Bitnami to provide servers that are ready for deployment on cloud hosting solutions.  We are going to ask them about whether they produce deb / rpm packages of those.

**Comment by carlosrodfern** [comment]
Folks, thank you for your help.

**Comment by TylerJewell** [comment]
We are moving to a pure Docker launcher for Che. This will be the equivalent of deb / rpm for most admins. We will also allow Che to run as root to eliminate some unnecessary Docker configuration.
