### ISSUE TITLE
Bump version of Xtermjs

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#16212]
### Is your task related to a problem? Please describe.
Version of `Xtermjs` for `theia` is going to be updated very soon: https://github.com/eclipse-theia/theia/pull/7121
It will bring the breaking changes to `che-theia` as our `RemoteTerminalWidget` extends `TerminalWidgetImpl` of `theia`.
I checked it using che-in-che development and got the compilation errors, like:

![remote_term_widg](https://user-images.githubusercontent.com/5676062/75783866-f3b69580-5d69-11ea-8ab9-1f4146c095c8.png)
 

### Describe the solution you'd like
Update the version of `Xtermjs` for `che-theia`

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che-theia/pull/652
