### ISSUE TITLE
[Hosted che] Not able to run workspace via devfile link ('f?url' parameter) 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16218]
### Describe the bug
I was not able to use che factory on hosted che.
- https://che.openshift.io/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/go/devfile.yaml
- https://che.openshift.io/f?url=https://github.com/eclipse/che

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.9.0

### Steps to reproduce
1. Open browser
2. Paste link
3. Hit enter.
4. At the end, I get the dashboard instead of the workspace.

### Expected behavior
The workspace should be loaded.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![devfile_factory](https://user-images.githubusercontent.com/1614429/75864622-9b7fa200-5e02-11ea-8043-dd2063bdfaa1.gif)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
n/a
### Additional context
n/a

**Comment by skabashnyuk** [comment]
Tested locally on crc, 7.10-x  - working

**Comment by ibuziuk** [comment]
Could you please clarify what is the browser versio ? works fine on Fedora against Chrome 76.0.3809.100-1

**Comment by skabashnyuk** [comment]
Google Chrome
Версія 80.0.3987.122 (Розробка) (64-розрядна версія)

**Comment by ibuziuk** [comment]
Was able to reproduce in incognito (I suspect that some of the UD files has been cached).
@sleshchenko I suspect this might be related to the fact that we do UD customization via product.json now

**Comment by skabashnyuk** [comment]
`Версія 80.0.3987.132 (Розробка) (64-розрядна версія)` - same thing

**Comment by ibuziuk** [comment]
The workaround is to use the "Import Devfile" flow:
![image](https://user-images.githubusercontent.com/1461122/75866905-10081000-5e06-11ea-8551-30d2f00ac364.png)

**Comment by ibuziuk** [comment]
PR with workaround - https://github.com/redhat-developer/rh-che/pull/1817
real fix for 7.9.1 - https://github.com/eclipse/che/pull/16223

**Comment by ibuziuk** [comment]
Fixed on production. Closing
also fixed in 7.9.1 and there is a pending PR for master - https://github.com/eclipse/che/pull/16222

**Comment by sleshchenko** [comment]
Seems, it's actual again =(

**Comment by ibuziuk** [comment]
Hosted Che specific PR with a workaround for `7.10.0` https://github.com/redhat-developer/rh-che/pull/1849

**Comment by ibuziuk** [comment]
PR with prod update - https://github.com/openshiftio/saas-openshiftio/pull/1402

**Comment by ibuziuk** [comment]
Closing. Fixed on production
