### ISSUE TITLE
Create e2e test for workspace creation via devfile url (`f?url=` parameter )

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16219]
### Is your task related to a problem? Please describe.
Currently, there is no test coverage for workspace creation via the `f?url=` flow which is highly promoted. 

### Describe the solution you'd like
e2e test for workspace creation via `f?url=` e.g.:

- https://che.openshift.io/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/go/devfile.yaml
- https://che.openshift.io/f?url=https://github.com/eclipse/che

### Additional context
Will help to identify issues like https://github.com/eclipse/che/issues/16218

**Comment by rhopp** [comment]
I would be also interested what's the reason of #16218 and why this wasn't caught by some tests on the component level?
e2e tests are not a silver bullet for everything ;-)

**Comment by rhopp** [comment]
To put it another way... Coverage of e2e tests should be last resort - for scenarios, which (for some reason) *cannot* be covered for example by unit tests.

**Comment by ibuziuk** [comment]
@rhopp this looks like a subtle issue that might be Hosted Che specific. I suspected that it would be reproducible when `product.json` is overridden, but this might not be the case.
I doubt that this flow could be properly tested with unit tests only since multiple components are involved + fancy redirect logic. So, this flow deserves an e2e test IMO

**Comment by dmytro-ndp** [comment]
@ibuziuk, @rhopp: we have already had [CreateFactoryFromDevfileUrl](https://github.com/eclipse/che/blob/master/tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CreateFactoryFromDevfileUrl.java#L33  ) E2E java selenium test.
We are running it nightly and it have passed recently https://ci.centos.org/job/devtools-che-nightly-multiuser-stable-test/25/

**Comment by ibuziuk** [comment]
@dmytro-ndp I guess we can close the issue in this case, just a suggestion that this test should be enabled for downstream (CRW and Hosted Che) cc: @Katka92
