### ISSUE TITLE
Compatibility CI with Hosted Che does not work

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16211]
### Describe the bug
Compatibility CI with Hosted Che does not work - https://ci.centos.org/view/Devtools/job/devtools-rh-che-build-master/ 
Basically, it always uses the version of upstream defined in the Hosted Che (not the latest available)

### Expected behavior
Compatibility CI with Hosted Che will use the latest version of upstream from master
Ideally, CI should be triggered on every commit to upstream (not downstream). Easier option would be triggering the CI nightly.

**Comment by tomgeorge** [comment]
It looks like the job is using the correct version of upstream che.

**Comment by ibuziuk** [comment]
@vparfonov do you think we can close it after https://github.com/redhat-developer/rh-che/pull/1867 ?
or some further work is expected?
