### ISSUE TITLE
Update JsonExampleEditorProvider Code Example

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#1622]
https://github.com/eclipse/che/blob/80ae9417866fa61bb6be59b07d0ea77d5167f90d/samples/sample-plugin-json/che-sample-plugin-json-ide/src/main/java/org/eclipse/che/plugin/jsonexample/ide/editor/JsonExampleEditorProvider.java

It can be simplified after introducing the AbstractTextEditorProvider, it must only implement #getEditorConfiguration, now

Update the docu as well...

**Comment by bmicklea** [comment]
@JonasHelming are you taking care of this?

**Comment by JonasHelming** [comment]
Unfortunately, we do not have time for this at the moment

**Comment by slemeur** [comment]
@ashumilova + @vparfonov : could you please give a look on this?

**Comment by TylerJewell** [comment]
Elevating this to a blocker for discussion. This should be a quick, easy fix to make for someone on team/ide team.
