### ISSUE TITLE
We should not declare that Che works with any desktop IDE

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16220]
### Describe the bug

In the https://www.eclipse.org/che/features/#any-ide we declare that

> Start working from any device without installing software by using the built-in Eclipse Che IDE. Or stick with the desktop IDE you love by mounting into the Che workspace. Your choice.

and 

> SSH Access
> Mount-and-Sync Workspace
> Electron Client

That's not true. We do not provide SSH Access, Mount-and-Sync or an electron client.

### Additional context

Users are puzzled https://github.com/eclipse/che/issues/15233

**Comment by l0rd** [comment]
@themr0c does the doc team own https://www.eclipse.org/che (source code at https://github.com/eclipse/che-website)?

**Comment by themr0c** [comment]
@l0rd I don't believe so.  I have never worked on it. 

@sunix is the historical main contributor and it seems that @benoitf took over https://github.com/eclipse/che-website/graphs/contributors

Looks like the file to edit is plain HTML inside a PHP file: https://github.com/eclipse/che-website/blob/master/che/features/index.php 

Do you want that we take a look anyway?

**Comment by l0rd** [comment]
> Do you want that we take a look anyway?

@themr0c Yes I would appreciate that.

@sunix, @benoitf and @bmicklea: who do you think should be considered the owner of eclipse.org/che website (responsible for issue tracking, PRs review etc...)?

**Comment by bmicklea** [comment]
The electron client is definitely wrong. However with a kubernetes setup that allows it you can use r-sync can't you? I don't want us to remove the statement of being able to use a Che workspace from any desktop IDE unless it's actually impossible.

**Comment by sunix** [comment]
I remember we wanted to investigate ksync: https://github.com/eclipse/che/issues/15016

**Comment by l0rd** [comment]
> The electron client is definitely wrong. However with a kubernetes setup that allows it you can use r-sync can't you? I don't want us to remove the statement of being able to use a Che workspace from any desktop IDE unless it's actually impossible.

@bmicklea in theory that's feasible but in practice we do not have doc about it and we never tested it. If a customer or user reads that statement he will ask how. But we currently do not have an answer and we haven't even ever tried it. How do we inject a rsync server in a Che workspace? Does `oc rsync` works for us? What about k8s? How do we setup an rsync client on a desktop (mac, linux, windows) so that it can monitor the workspace source code folder? What if the cluster is behind a proxy? Is the rsync networking protocol working through OpenShift routes?
@benoitf is currently looking at it and will write a blog post about his findings.

**Comment by bmicklea** [comment]
Thanks - that helps. Considering that this is a common question and can limit adoption, I'd like us to work on an answer. Once @benoitf has something let's review and if it needs more work, then we can add it to a team's sprint goals.

So I'm reopening this until we have a new issue that tracks the work we're doing here. If one exists already please link then close this.

**Comment by l0rd** [comment]
@bmicklea that's the issue https://github.com/eclipse/che/issues/15016

**Comment by bmicklea** [comment]
Closing - refer to #15016 for technical details and progress.
