### ISSUE TITLE
E2E Happy path tests had failed on "Run application" against Eclipse Che with TLS support

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16230]
### Describe the bug
E2E Happy path tests on "Run application" against Eclipse Che with TLS support:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/955/console
```
        ▼ Ide.waitNotification "Redirect is now enabled on port 8080"
        ▼ Ide.getApplicationUrlFromNotification Redirect is now enabled on port 8080
        ▼ Ide.waitApllicationIsReady https://serverpecnzo51-theia-ide0zu-server-13131.10.0.101.40.nip.io/
    1) Run application

  9 passing (8m)
  1 pending
  1 failing

  1) Validation of workspace build and run
       Run application:
     TimeoutError: Wait timed out after 120127ms
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Install minikube 1.1.1
2. Install Eclipse Che using helm:
```
chectl server:start --k8spodreadytimeout=360000 --platform=minikube --listr-renderer=verbose --skip-version-check
```
3. Run E2E Happy path tests:
```
docker run --shm-size=256m --net=host --ipc=host -p 5920:5920 -e TS_SELENIUM_HEADLESS=true -e TS_SELENIUM_DEFAULT_TIMEOUT=300000 -e TS_SELENIUM_LOAD_PAGE_TIMEOUT=240000 -e TS_SELENIUM_WORKSPACE_STATUS_POLLING=20000 -e TS_SELENIUM_BASE_URL=https:che-che.10.0.101.40.nip.io -e TS_SELENIUM_LOG_LEVEL=DEBUG -v /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/che/tests/e2e:/tmp/e2e:Z quay.io/eclipse/che-e2e:nightly
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Run_application](https://user-images.githubusercontent.com/1197777/75922236-49bf3200-5e6b-11ea-8136-8c8d5fe762b7.png)

### Installation method
   - [x] chectl:next with helm installer
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRw CCI

**Comment by rhopp** [comment]
Quick solution could be just settitn env variable `NODE_TLS_REJECT_UNAUTHORIZED=0`.
