### ISSUE TITLE
creating a Custom Stack with JDK8 and Gradle 3.1 to carryout development on my project.

### ISSUE THREAD

**Issue by YasithaSandeep** [eclipse-che/che#16235]
I tried editing Devfile with a self created Docker image to be pulled while creating the workspace.
The container was created but at the end gradle ontainer terminated throwing up an error.

Following is the Dev File Configuration

> "metadata:
>   name: java-gradle-stack
> components:
>   - id: redhat/java/latest
>     type: chePlugin
>   - mountSources: true
>     memoryLimit: 512Mi
>     type: dockerimage
>     volumes:
>       - name: gradle
>         containerPath: /home/gradle/.gradle
>     alias: gradle
>     image: 'quay.io/rezg/gradle'
>     env:
>       - value: /home/gradle/.gradle
>         name: GRADLE_USER_HOME
>       - value: >-
>           -XX:MaxRAMPercentage=40 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
>           -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
>           -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
>           -Xms20m -Djava.security.egd=file:/dev/./urandom
>         name: JAVA_OPTS
>       - value: >-
>           -XX:MaxRAMPercentage=40 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
>           -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
>           -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
>           -Xms20m -Djava.security.egd=file:/dev/./urandom
>         name: JAVA_TOOL_OPTIONS
>       - value: /home/gradle
>         name: HOME
> apiVersion: 1.0.0
> commands:
>   - name: gradle build
>     actions:
>       - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
>         type: exec
>         command: gradle build
>         component: gradle
>   - name: gradle run
>     actions:
>       - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
>         type: exec
>         command: gradle run
>         component: gradle"

Error from the workspace

> Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.1.1"
> Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.1.1"
> Created container che-plugin-metadata-broker-v3-1-1
> Starting plugin metadata broker
> List of plugins and editors to install
> - redhat/java/latest - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
> - eclipse/che-machine-exec-plugin/7.9.0 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
> - eclipse/che-theia/7.9.0 - Eclipse Theia
> All plugin metadata has been successfully processed
> Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.9.0"
> Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.9.0"
> Created container remote-runtime-injectorzvr
> Started container remote-runtime-injectorzvr
> Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.1.1"
> Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.1.1"
> Created container che-plugin-artifacts-broker-v3-1-1
> Starting plugin artifacts broker
> Saving log of installed plugins
> All plugin artifacts have been successfully downloaded
> Processing plugin redhat/java/latest
>   Installing plugin extension 1/2
>     Plugin already downloaded
>   Installing plugin extension 2/2
>     Plugin already downloaded
> Started container che-plugin-artifacts-broker-v3-1-1
> Pulling image "quay.io/eclipse/che-jwtproxy:dbd0578"
> Successfully pulled image "quay.io/eclipse/che-jwtproxy:dbd0578"
> Created container che-jwtproxy5g3ge9pd
> Started container che-jwtproxy5g3ge9pd
> Pulling image "quay.io/rezg/gradle"
> Successfully pulled image "quay.io/rezg/gradle"
> Created container gradle
> Started container gradle
> Pulling image "quay.io/eclipse/che-sidecar-java:8-0cfbacb"
> Successfully pulled image "quay.io/eclipse/che-sidecar-java:8-0cfbacb"
> Created container vscode-javawph
> Started container vscode-javawph
> Pulling image "quay.io/eclipse/che-machine-exec:7.9.0"
> Successfully pulled image "quay.io/eclipse/che-machine-exec:7.9.0"
> Created container che-machine-execdou
> Started container che-machine-execdou
> Pulling image "quay.io/eclipse/che-theia:7.9.0"
**> Error: Failed to run the workspace: "The following containers have terminated:
> gradle: reason = 'Completed', exit code = 0, message = 'null'**"

**Comment by metlos** [comment]
The components need to be non-terminating. The usual way is to override their entry points like:

```yaml
- type: dockerimage
  alias: gradle
  ...
  command: ['tail', '-f', '/dev/null']
```

**Comment by YasithaSandeep** [comment]
> The components need to be non-terminating. The usual way is to override their entry point command like:
> 
> ```yaml
> - type: dockerimage
>   alias: gradle
>   ...
>   command: ['tail', '-f', '/dev/null']
> ```

@metlos  Where should I make this change?
is it on docker file or is it on the Dev File????

**Comment by tolusha** [comment]
@YasithaSandeep 
The similar question and answer is here
https://github.com/eclipse/che/issues/16171#issuecomment-594633774

**Comment by metlos** [comment]
@YasithaSandeep my example is for the devfile - you can redefine the entrypoint command of a dockerimage component there.

It can be done also in the Dockerfile of the image as @tolusha pointed out. That way the users of the image don't have to override the entrypoint command for it to work inside Che. If have the chance to publish such modified image, it would make the lives of the devfile users simpler. If on the other hand you want to use official gradle images for example, you would need to use the entrypoint command override in the devfile.

**Comment by YasithaSandeep** [comment]
Got it Thanks.
im closing this issue

**Comment by gilbeckers** [comment]
The fact that components need to be non-terminating, isn't that something that may be explicitly stated in the documentation? Maybe under [Defining specific container images](https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-and-configuring-a-new-workspace/#_defining_specific_container_images) ?
