### ISSUE TITLE
Some docs article has `{title}` as title

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16234]
### Describe the bug
I believe this screenshot tells more than enough

![Screenshot_20200305_102708](https://user-images.githubusercontent.com/5887312/75962184-f6c99700-5ecb-11ea-84de-b4a8262d1840.png)

**Comment by tolusha** [comment]
That's very annoying.

**Comment by themr0c** [comment]
The pages with {title} are the topics pages, not part of the navigation, that are annoyingly produced by the Jekyll build system. (And AFAIK inavoidable). The documentation team would be very happy to work on the replacement of this build system with a better one, Antora, that would produce only the necessary HTML output.

**Comment by themr0c** [comment]
Closing this issue as we will take care of this with #16286.
