### ISSUE TITLE
Recipe type error when creating a workspace with a factory

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#16233]
### Describe the bug

I created a factory with a source template provided by che by default.
`"recipe": {
          "content": "eclipse/ubuntu_jdk8",
          "type": "dockerimage"
        }`
However, when I create it, I get a recipe type error like the screenshot below.
What should I do for normal operation?
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.4.0

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/29850624/75959360-6d34bc00-5f01-11ea-935f-75abe08d4316.png)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
   - [x] helm 

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
Persisted factories are not supported anymore. 
To create a workspace with factory flow you can use github repo URL, or URL to devfile content, like https://che.openshift.io/f?urlhttps://github.com/eclipse/che

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/issues/12925

@kellyhyomin let me know if you still need some help

**Comment by kellyhyomin** [comment]
@sleshchenko 
Thank you for your help. 

The url you told me is getting the following error.
![image](https://user-images.githubusercontent.com/29850624/76041017-6acf7200-5f94-11ea-8e24-564d33c0cab5.png)

When I use url like https://che.openshift.io/f?urlhttps://github.com/AutoSARioDeveloper/popcornsar-cpp-ap/devfile.yaml, The result is the same. 
Is there a way to fix it?
