### ISSUE TITLE
Add workspace:delete command to delete user's workspace

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16236]
### Is your task related to a problem? Please describe.
User might work and then go which make his workspaces abandoned. Admins needs a tool to cleanup user's resources.

### Describe the solution you'd like
Add `workspace:delete` command to delete user's workspaces.

### Additional context
Check how it works with `per-namespace` strategy.
downstream issue https://issues.redhat.com/browse/CRW-538

**Comment by sleshchenko** [comment]
@tolusha Could you clarify more about this command?
Is it going to have different flags like
```
chectl workspace:delete // non-valid
chectl workspace:delete --all-workspaces //delete all available workspaces of the current user
chectl workspace:delete user/java-mysql //delete all available workspaces of the current user
chectl workspace:delete --all-users //delete all workspaces on the Che cluster. Available only for Che Admin
```

**Comment by tolusha** [comment]
<pre>[16:49:30] tolusha@fractal <font color="#4D9A05">~/projects/chectl/bin</font><font color="#C3A000"> (ab/delete)</font> $ ./run workspace:list -n abazkoche --access-token=$CHE_ACCESS_TOKEN
  <font color="#4D9A05">✔</font> Verify Kubernetes API...OK (it&apos;s OpenShift)
  <font color="#4D9A05">✔</font> Verify if namespace &apos;abazkoche&apos; exists
  <font color="#4D9A05">✔</font> Retrieving Eclipse Che server URL... http://che-abazkoche.apps.ocp43.codereadyqe.com
  <font color="#4D9A05">✔</font> Eclipse Che status check
  <font color="#4D9A05">✔</font> Get workspaces... done
<b>Id                        Name                 Namespace Status  Created                  Updated </b>
workspace55z6ay05muvv3wk1 apache-camel-k-qwn6g admin-che STOPPED 2020-03-18T14:45:55.177Z         
[16:49:42] tolusha@fractal <font color="#4D9A05">~/projects/chectl/bin</font><font color="#C3A000"> (ab/delete)</font> $ ./run workspace:delete -n abazkoche --access-token=$CHE_ACCESS_TOKEN -w workspace55z6ay05muvv3wk1
  <font color="#4D9A05">✔</font> Verify Kubernetes API...OK (it&apos;s OpenShift)
  <font color="#4D9A05">✔</font> Verify if namespace &apos;abazkoche&apos; exists
  <font color="#4D9A05">✔</font> Retrieving Eclipse Che server URL... http://che-abazkoche.apps.ocp43.codereadyqe.com
  <font color="#4D9A05">✔</font> Eclipse Che status check
  <font color="#4D9A05">✔</font> Get workspace with id &apos;workspace55z6ay05muvv3wk1&apos;... done
  <font color="#4D9A05">✔</font> Delete workspace with id &apos;workspace55z6ay05muvv3wk1&apos;... done
  <font color="#4D9A05">✔</font> Verify if user namespace exists &apos;admin-che&apos;... not found
  <font color="#C3A000">↓</font> Delete user namespace [skipped]
</pre>
