### ISSUE TITLE
Can't add projects to custom stack in UI.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#16232]
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.4.0

When I create a workspace with a custom stack, I want to add projects.
But I can't go to the next step with an error. Attach an error screen below.
![image](https://user-images.githubusercontent.com/29850624/75952453-1f648780-5ef2-11ea-989c-16419fb06820.png)

How can I create a workspace normally after adding projects?

**Comment by sleshchenko** [comment]
@kellyhyomin I assume you have not projects in your Devfile. As a workaround, I can suggest you to try to add empty projects field into your devfile.

**Comment by kellyhyomin** [comment]
@sleshchenko 

Thank you for your help.
After adding projects to the devfile, the workspace is created but the project is not cloned.
Are there any related theia extensions or eclipse che extensions added?
My custom stack is not che-theia based.

**Comment by tolusha** [comment]
@sleshchenko 
Could you set priority for the issue?

**Comment by sleshchenko** [comment]
> Are there any related theia extensions or eclipse che extensions added?

@kellyhyomin I think yet. @azatsarynnyy Can tell you more, I guess you need at least 
https://github.com/eclipse/che-theia/tree/master/plugins/workspace-plugin
https://github.com/eclipse/che-theia/tree/master/extensions/eclipse-che-theia-activity-tracker
to make your Custom Theia work properly with Che.

**Comment by azatsarynnyy** [comment]
Hello @kellyhyomin 
> My custom stack is not che-theia based

in this case, an editor that is used in your Che Workspace should provide the functionality of cloning a project.
In Che Theia based stacks, Che Theia is responsible for cloning the projects with help of [Workspace Plugin](https://github.com/eclipse/che-theia/tree/master/plugins/workspace-plugin).

**Comment by olexii4** [comment]
@kellyhyomin  I cannot reproduce it with CHE 7.11.0. I am sure we already fixed it. Just try CHE 7.11.0

**Comment by olexii4** [comment]
@kellyhyomin  It seems fixed a long time ago - [fix](https://github.com/eclipse/che-dashboard/commit/b497ebbd9f8a17f9205970883ef1f8462ac9b5f5#diff-313cf84156916e3f3e0ca455b485aa51R133).

Let me know if you still face the same bug.

Thanks!
