### ISSUE TITLE
Cloud shell must propagate error when it failed to initialize terminal

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16249]
### Is your enhancement related to a problem? Please describe.
Currently, when the cloud shell failed to initialize terminal - it shows nothing.
It's needed to display an error when happened.

![Screenshot_20200303_174223](https://user-images.githubusercontent.com/5887312/75792314-71809e00-5d76-11ea-95f2-ff35e91869a4.png)

**Comment by sleshchenko** [comment]
I've just tested the nightly build and it does not seem to be fixed. Maybe I did something wrong

![Screenshot_20200408_120516](https://user-images.githubusercontent.com/5887312/78765992-66321b00-7991-11ea-821c-e4074082257e.png)
![Screenshot_20200408_120526](https://user-images.githubusercontent.com/5887312/78765994-66cab180-7991-11ea-9a75-ca31b39996ba.png)

**Comment by AndrienkoAleksandr** [comment]
> I've just tested the nightly build and it does not seem to be fixed. Maybe I did something wrong

@sleshchenko Yes, sorry, it is really doesn't work, I tested my previous pr with another errors flow. I created one pr, it should work and I tested it with che-workspace-operator https://github.com/eclipse/che-machine-exec/pull/91 . Thanks for good testing and feedback.

**Comment by sleshchenko** [comment]
Now it works :tada: 
but still some fix is needed to process \n in the right way
![Screenshot_20200409_145534](https://user-images.githubusercontent.com/5887312/78906858-914b6600-7a88-11ea-8aa4-443aa212a283.png)
