### ISSUE TITLE
[e2e] Add more log levels into Logger

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#16246]
### Is your enhancement related to a problem? Please describe.
Currently, we have only `debug` and `trace` log levels in [Logger](https://github.com/eclipse/che/blob/master/tests/e2e/utils/Logger.ts)

### Describe the solution you'd like
We should add at least ERROR and WARN log levels.

**Comment by ScrewTSW** [comment]
working on it

**Comment by rhopp** [comment]
Done in https://github.com/eclipse/che/pull/16297
