### ISSUE TITLE
[hosted-che] Deploy swagger UI on hosted che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16240]
### Is your task related to a problem? Please describe.
Che UI (Dashboard + Theia) does not expose all Che API capabilities, like Resources API, some internals of Resource API.
I don't have strong need but from time to time I need quickly access Che REST API to answer some users' questions or to understand the default settings of Che cluster.

So, it's a proposal to deploy swagger UI that we have in upstream Che on hosted Che.
If there is any reason not to do it - I'm OK with that, but I don't know such.

P.S. Swagger UI is also available in CRW 2.1.0:latest

**Comment by ibuziuk** [comment]
@l0rd @davidfestal @benoitf wdyt?

**Comment by ibuziuk** [comment]
just for the record, swagger was enabled for codenvy.io

**Comment by l0rd** [comment]
I am ok with that.

**Comment by ibuziuk** [comment]
PR sent - https://github.com/redhat-developer/rh-che/pull/1847

**Comment by ibuziuk** [comment]
Done. Closing
