### ISSUE TITLE
Docs: Devfile Structure link broken

### ISSUE THREAD

**Issue by rajivnathan** [eclipse-che/che#16248]
### Describe the bug

The link takes you to
https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html#making-a-workspace-portable-using-a-devfile_using-developer-environments-workspaces
which gives you a 404.

The correct link appears to be
https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/

### Che version

7.9.0

### Steps to reproduce

1. Navigate to the IMPORT DEVFILE page
2. Select the YAML source option
3. Click the link `Docs: Devfile Structure`

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: OKD 3.11

**Comment by tolusha** [comment]
@rkratky 
Could you have a look pls

**Comment by tsmaeder** [comment]
Hmh...maybe we need some "persistent link" facility for links in the code that reference doc? That would allow to point to new locations for existing doc? That way, we would know which locations are referenced from the code and it would be easy to update the location.

**Comment by sleshchenko** [comment]
It should be fixed by https://github.com/eclipse/che-dashboard/pull/33
