### ISSUE TITLE
[Hosted Che] [Dogfooding] Provide devfiles and "developer workspace" button in README

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16247]
### Is your task related to a problem? Please describe.
Provide devfiles and "developer workspace" button in README for each repository for coding on che.openshift.io:

List of repositories:

- [x] https://github.com/redhat-developer/rh-che
  -  https://github.com/redhat-developer/rh-che/blob/master/devfile.yaml |  [![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/redhat-developer/rh-che)
- [x] https://github.com/redhat-developer/che-monitoring
   - https://github.com/redhat-developer/che-monitoring/pull/28 | [![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/redhat-developer/che-monitoring)
- [x] https://github.com/openshiftio/saas-openshiftio
   - https://github.com/openshiftio/saas-openshiftio/pull/1440 | [![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/openshiftio/saas-openshiftio)
- [x] https://github.com/redhat-developer/devfile/tree/master/getting-started
   - https://github.com/redhat-developer/devfile/pull/62 | [![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/redhat-developer/devfile)
- [x] https://github.com/che-incubator/che-workspace-telemetry-client
  - https://github.com/che-incubator/che-workspace-telemetry-client/blob/master/devfile.yaml  |  [![Contribute](https://camo.githubusercontent.com/7ca4f6be43fb5eb61a73ba6d40b3481d93ef5813/68747470733a2f2f6368652e6f70656e73686966742e696f2f666163746f72792f7265736f75726365732f666163746f72792d636f6e747269627574652e737667)](https://che.openshift.io/f?url=https://github.com/che-incubator/che-workspace-telemetry-client)
- [x] https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend
   - https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend/blob/master/devfile.yaml | [![Contribute](https://camo.githubusercontent.com/7ca4f6be43fb5eb61a73ba6d40b3481d93ef5813/68747470733a2f2f6368652e6f70656e73686966742e696f2f666163746f72792f7265736f75726365732f666163746f72792d636f6e747269627574652e737667)](https://che.openshift.io/f?url=https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend)
- [x] https://github.com/redhat-developer/kubernetes-image-puller
https://github.com/redhat-developer/kubernetes-image-puller/blob/master/devfile.yaml  | [![Contribute](https://camo.githubusercontent.com/7ca4f6be43fb5eb61a73ba6d40b3481d93ef5813/68747470733a2f2f6368652e6f70656e73686966742e696f2f666163746f72792f7265736f75726365732f666163746f72792d636f6e747269627574652e737667)](https://che.openshift.io/f?url=https://github.com/redhat-developer/kubernetes-image-puller)
- [x] https://github.com/che-incubator/kubernetes-image-puller-operator
  https://github.com/che-incubator/kubernetes-image-puller-operator/blob/master/devfile.yaml | [![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/che-incubator/kubernetes-image-puller-operator)
- [x] https://github.com/che-incubator/kubernetes-image-puller
https://github.com/che-incubator/kubernetes-image-puller/blob/master/devfile.yaml | [![Contribute](https://camo.githubusercontent.com/7ca4f6be43fb5eb61a73ba6d40b3481d93ef5813/68747470733a2f2f6368652e6f70656e73686966742e696f2f666163746f72792f7265736f75726365732f666163746f72792d636f6e747269627574652e737667)](https://che.openshift.io/f?url=https://github.com/che-incubator/kubernetes-image-puller)

### Additional context
Example of a "developer workspace" button:

[![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/redhat-developer/rh-che)

**Comment by tomgeorge** [comment]
che-incubator/kubernetes-image-puller and che-incubator/kubernetes-image-puller-operator are done as well.

**Comment by ibuziuk** [comment]
Closing since devfiles + Readme.md have been created / updated.
@tomgeorge could you please review the dogfooding scoreboard and updated accordingly if needed

**Comment by tomgeorge** [comment]
Reviewed
