### ISSUE TITLE
[Communications Training] Json-RPC

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16255]
### Is your task related to a problem? Please describe.
This is about preparing a training video about the flows and communications amongst the different distributed components.
The topic of this issue is JSON-RPC. 

### Describe the solution you'd like
Proposed agenda.
 - Introduction. What is Json-RPC, websocket
 - Connecting to che server with  Json-RPC over websocket.
 - What is endpointId, method, dto,dtoClass
 - How to subscribe for workspace events.
 - How to subscribe containers debug logs

Initial content. https://github.com/eclipse/che-docs/blob/7.1.x/src/main/pages/che-6/dev_essentials/json-rpc.adoc

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by sparkoo** [comment]
Done. If the videos will be publicly available, I'll try to update it here.
