### ISSUE TITLE
CloudShell should provide an option to use users token instead of SA's one

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16250]
### Is your enhancement related to a problem? Please describe.
Currently, CloudShell uses mount SA's token to perform all operations with K8s/OS cluster. It was kind of OK in case of Che Server, but with workspace-controller where we use OpenShift OAuth proxy instead of JWTProxy it would be much secure if CloudShell would use token from Header/QueryParam instead of SA's one.
So, CloudShell should provide an option to use users token instead of SA's one.

At this moment, not the whole workflow is clear but it's known enough to start working on that and learn more in process.

**Comment by metlos** [comment]
> it would be much secure if CloudShell would use token from Header/QueryParam instead of SA's one.

How is running arbitrary code with user privs more secure than running it with a predefined SA?

**Comment by sleshchenko** [comment]
@metlos Not sure I fully understand your question...
Instead of mounting SA with needed permissions into workspace and do authorization(check user should be able to use that SA) on web app level we:
still has authorization on web app level (OpenShift OAuth) but let K8s API to decide if user has needed permissions or not. So, each user access K8s API with their own tokens and we don't impersonate everyone as SA.
Let me know if the question is still unanswered.
