### ISSUE TITLE
Allow preferences per workspace in addition user

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16268]
### Is your enhancement related to a problem? Please describe.

I want to be able to define special settings for a specific workspace

### Describe the solution you'd like

Like in VS Code, please do support this functionality

### Describe alternatives you've considered

Just manually switch settings as I change/switch workspace

### Additional context

![image](https://user-images.githubusercontent.com/11182824/76092132-fb4c9780-6012-11ea-959a-f9c54e545702.png)

**Comment by skabashnyuk** [comment]
Not sure for 100% you may try this approche https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#tuning-cheplugin-component-configuration for `theia editor`

**Comment by tolusha** [comment]
I am wondering if we support it already
@azatsarynnyy

**Comment by azatsarynnyy** [comment]
Synchronizing Theia preferences across the user's Workspaces was done intentionally in the PR https://github.com/eclipse/che-theia/pull/80 to allow the user not to care about updating the preferences in each Workspace.

**Comment by SDAdham** [comment]
@azatsarynnyy:
> user not to care about updating the preferences in each Workspace
that is essential for sure. Here is an example:
![image](https://user-images.githubusercontent.com/11182824/76473539-e2961480-644c-11ea-9ea3-851d83079806.png)
