### ISSUE TITLE
Add download devfile from theia ide for factory feature usage

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16262]
### Is your enhancement related to a problem? Please describe.

Allow automated reconstruction of devfile like it was done in the past see https://developers.redhat.com/che/creating-factories/

### Describe the solution you'd like

Creating a snapshot of a workspace would greatly save time and efforts in replicating environments very easy

### Describe alternatives you've considered

Manually update devfile from devfile tab in workspace config then later export it manually

### Additional context

This is nothing new, it used to exist before, see https://developers.redhat.com/che/creating-factories/

**Comment by skabashnyuk** [comment]
@SDAdham thanks for this issue. Just to clarify. Do you want to get devfile.yaml from an existing workspace?

**Comment by SDAdham** [comment]
Yes so it can be reused by factory

**Comment by pdaverh** [comment]
This will be a good feature to bring back. The idea is that someone should be able to export their workspace as a devfile that can then be shared with someone else to import into Che and get a workspace.

**Comment by azatsarynnyy** [comment]
It should be covered by https://github.com/eclipse/che/issues/16875

**Comment by SDAdham** [comment]
Thanks @azatsarynnyy Seen it now. I think we can close this issue then.
