### ISSUE TITLE
Support 'inputs' for che tasks

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#16264]
### Is your enhancement related to a problem? Please describe.
VS Code and Theia support `input variables` for tasks.
Please see more details https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

It would be nice to have it working for `che` tasks.

### Describe the solution you'd like
Support `input variables` for `che` tasks.

### Additional context
Che user asked about it in mattermost channel.

**Comment by tsmaeder** [comment]
@RomanNikitenko are you sure this doesn't just work? We're translating che commands to tasks, after all.

**Comment by RomanNikitenko** [comment]
It didn't work when I created the issue.

I didn't try it recently...
