### ISSUE TITLE
Add extra environment variables that would specify the generated preview url, loggedin username, first & lastname of the user 

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16265]
### Is your enhancement related to a problem? Please describe.

When running printenv, I see port and many variables are added, but what's missing is:
* Username
* Email
* Name, and/or;
* First name
* Last name

And instead of having variables like this: `SERVERI19WW3P5_JWTPROXY_PORT_4400_TCP_PROTO`, it'd be better to be like this:
* SERVER=I19WW3P5
* JWTPROXY_PORT=4400

### Describe the solution you'd like

Explained the issue and solution above

### Describe alternatives you've considered

Currently, I am manually requesting for this information

### Additional context

In theia ide workspace environment

**Comment by skabashnyuk** [comment]
@SDAdham I think alternative for you would be to query `${CHE_API}/api/user` or `${CHE_API}/api/preferences` with `MACHINE_TOKEN` as Authorization header.

**Comment by SDAdham** [comment]
Sorry, i missed the most important variable: the preview url
