### ISSUE TITLE
allow download devfile

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16260]
### Is your enhancement related to a problem? Please describe.

Please allow devfiles to be downloaded
![image](https://user-images.githubusercontent.com/11182824/76089943-be7ea180-600e-11ea-9649-20f5ada18a57.png)

### Describe the solution you'd like

Also add download button to extract the devfile for Factory feature usage purposes

### Additional context

Go to Workspaces, click on the gear icon to go into it's config then navigate to the devfile tab

**Comment by sleshchenko** [comment]
@SDAdham 
![Screenshot_20200310_114303](https://user-images.githubusercontent.com/5887312/76299774-50630480-62c4-11ea-8cca-459c34fae957.png)
Some code completion already present, you just need to invoke it with ctrl+space.

**Comment by SDAdham** [comment]
Since https://github.com/eclipse/che/issues/15996 already mentions the size of the screen, we keep this issue for the `download`?

**Comment by sleshchenko** [comment]
https://www.strava.com/activities/3173367979

**Comment by sleshchenko** [comment]
@SDAdham Thanks! It's easier to manage one purpose issues

**Comment by sleshchenko** [comment]
Spoiler: it's going to appear on Dashboard Next some day
![Screenshot_20200730_144535](https://user-images.githubusercontent.com/5887312/88919178-58bbdc00-d273-11ea-91d2-03ef8b5b4160.png)

**Comment by SDAdham** [comment]
Thanks a lot @sleshchenko

**Comment by sleshchenko** [comment]
now it's implemented on the new dashboard withing Devfile page
![Screenshot_20210204_145245](https://user-images.githubusercontent.com/5887312/106895281-ae78b180-66f8-11eb-94f1-c2800b3475b7.png)
