### ISSUE TITLE
Allow changing admin username to another username other than "admin"

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16272]
### Is your enhancement related to a problem? Please describe.

I cannot use organization feature

### Describe the solution you'd like

It would be nice if we can categories workspaces based on the organization and this feature is blocked unless I use `admin` and every time I need to add a user, I have to use `admin` again!

### Describe alternatives you've considered

Unusable

### Additional context

![image](https://user-images.githubusercontent.com/11182824/76093304-d9541480-6014-11ea-9b83-caab2cb8d619.png)

**Comment by skabashnyuk** [comment]
That is configurable with hhttps://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties#L26    or `CHE_SYSTEM_ADMIN__NAME ` see https://www.eclipse.org/che/docs/pages/che-7/administration-guide/examples/system-variables.html

**Comment by tolusha** [comment]
@SDAdham 
Does it work for you?

**Comment by karstengresch** [comment]
Joining in: Both approaches, either _multiuser.properties_ as well as  ``CHE_SYSTEM_ADMIN__NAME``env variable don't seem to work when installing with the operator?

At least the documentation could be enhanced: Instead of only describing which permissions are needed to create an organization, as an end user I'd rather expect getting step-by-step instructions from the beginning to creating organizations.

**Comment by skabashnyuk** [comment]
>Joining in: Both approaches, either multiuser.properties as well as CHE_SYSTEM_ADMIN__NAMEenv variable don't seem to work when installing with the operator?

@kameshsampath  what exactly part is not working? Can you please give more details or step by step instructions?

**Comment by SDAdham** [comment]
The implementation of this was never completed, there was a PR for it https://github.com/eclipse/che/pull/13013

**Comment by SDAdham** [comment]
But we need to have the ability to change admin in the run time!

**Comment by skabashnyuk** [comment]
This can be done in runtime. See https://www.eclipse.org/che/docs/che-7/authorizing-users/

**Comment by SDAdham** [comment]
Is there a user friendly UI for this?

**Comment by sleshchenko** [comment]
@SDAdham It's not really user-friendly but you can try to use swagger UI that should be available by `CHE_HOST/swagger`
