### ISSUE TITLE
Simplify adding stacks

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16270]
### Is your task related to a problem? Please describe.

There is no add button for adding stacks adding stacks doesn't seem easy

### Describe the solution you'd like

Provide an easy way via the UI would be great and allow us to be able to create our own builds from images via hub.docker and also use our own private registries

### Describe alternatives you've considered

Not able to use the feature

### Additional context

![image](https://user-images.githubusercontent.com/11182824/76092633-d3a9ff00-6013-11ea-804c-a74cfc17a2a6.png)

**Comment by gorkem** [comment]
@beaumorley this has to be related to some of the designs that you are working on

**Comment by sleshchenko** [comment]
The part related to the bigger Devfile editor is collapsed with https://github.com/eclipse/che/issues/15996. So, I've removed it here and let this issue be for adding stacks.

**Comment by sleshchenko** [comment]
I think it can be closed in favor of https://github.com/eclipse/che/issues/16875
please reopen if you still see the sense in having this issue opened.
