### ISSUE TITLE
Allow adding factory devfile templates into factory and list them to everyone in the organization

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16273]
### Is your enhancement related to a problem? Please describe.

For login required kind of repository (private repos), we cannot link che to the devfile that's available in the main repo, instead we have to share links manually

### Describe the solution you'd like

It would be nice if we can upload the devfiles there and add description then make it available with everyone or specific teams based on organization

### Describe alternatives you've considered

We share manually for now

### Additional context

![image](https://user-images.githubusercontent.com/11182824/76093508-2df78f80-6015-11ea-9d4d-c87103266a22.png)

**Comment by skabashnyuk** [comment]
@SDAdham I think this one https://github.com/eclipse/che/issues/12925 is what you are looking for.

**Comment by tolusha** [comment]
duplicates?

**Comment by SDAdham** [comment]
No, mine is explicity from the IDE itself (workspace)

**Comment by skabashnyuk** [comment]
>For login required kind of repository (private repos), we cannot link che to the devfile that's available in the main repo, instead we have to share links manually

@SDAdham  can you please rephrase and add some step by step examples. I don't fully understand you.

**Comment by SDAdham** [comment]
Sorry, i wrote my last comment while i was very tired
You can mix both issues but the only difference here:
* some repos require login so we cant really leave the devfile in the repo, alternatively the factory page would be nice to host it there (it does that already if u create factory but what it doesnt do is show them based on your organization membership)
* lets say we create eclipse org in organisation page and there are 5 members there then all of them should be able to see their own factories
