### ISSUE TITLE
chectl must duplicate required manual actions after deploying

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16277]
### Is your task related to a problem? Please describe.
Currently, chectl asks user to import CA into browser, but it does it as soon as CA is imported. So, there may be cases when users just miss this info, like because terminal is not big enough:
![Screenshot_20200306_165824](https://user-images.githubusercontent.com/5887312/76099034-2b744600-5fd3-11ea-89b1-9f364adab993.png)

So, it would be better if chectl duplicates all required manual actions after deploying:
![Screenshot_20200306_165835](https://user-images.githubusercontent.com/5887312/76099168-64acb600-5fd3-11ea-9a8c-e43ac96ead12.png)

It may help to prevent users from open Che before the browser is configured properly.

**Comment by mmorhun** [comment]
Done
