### ISSUE TITLE
Allow adding private container registry that doesn't require credentials

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16271]
### Is your enhancement related to a problem? Please describe.

I cannot add private registry that is only limited to the same network as che and doesn't have a password

### Describe the solution you'd like

Please allow adding private registry that doesn't require password

### Describe alternatives you've considered

Unable to use

### Additional context

![image](https://user-images.githubusercontent.com/11182824/76093088-867a5d00-6014-11ea-8f67-d49521b4cba1.png)

**Comment by tsmaeder** [comment]
@SDAdham I updated the title to make it clear it's not plugin registries or devfile registries.

**Comment by sleshchenko** [comment]
> private container registry that doesn't require password 

@SDAdham does such registry require username?

**Comment by SDAdham** [comment]
@sleshchenko nope, neither username or password

**Comment by sleshchenko** [comment]
@SDAdham If I'm not mistaking, the purpose of that private registries - configure [pullImageSecrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) for your workspace. AFAIU your private registry does not need image pull secret to be set up. So, what if you try to use an image from a private registry without configuring them on Dashboard, doesn't it work, what the error?

**Comment by SDAdham** [comment]
ahhh OK, it makes sense. Pls ignore. I was trying to explore and use the features in Che. I'll close this case considering that your comment makes sense.
