### ISSUE TITLE
Add whose online from organizational team

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16275]
### Is your enhancement related to a problem? Please describe.

It would be nice if we can include whose online from organization team in the left pane underneath recent workspaces

Allowing rocket chat integration (empedding) that'll be WOW 

### Describe the solution you'd like

Explained above

### Additional context

![image](https://user-images.githubusercontent.com/11182824/76093840-c2fa8880-6015-11ea-9641-0f88f1bdb7a3.png)

**Comment by skabashnyuk** [comment]
>we can include whose online from organization team in the left pane underneath

@SDAdham can you add more details, please.

**Comment by tsmaeder** [comment]
@SDAdham so in brief, you want a chat client integrated?

**Comment by SDAdham** [comment]
@tsmaeder : it would be nice to have. For example, you can embed rocket.chat:
https://rocket.chat/docs/developer-guides/embedded-layout/

**Comment by sleshchenko** [comment]
organizations are not a part of the new dashboard anymore.
If we'll restore it - we'll take into account the proposed functionality
