### ISSUE TITLE
pull requests extension upgrade from 0.8 to 0.14" _gitAPI.onDidChangeState is not a function"

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#16283]
trying to upgrade the github pull requests ms-vscode extension in my plugin-registry I get the following from the extension:

"Activating extension GitHub Pull Requests failed: this._gitAPI.onDidChangeState is not a function."
![image](https://user-images.githubusercontent.com/407397/76151920-ace1dc00-6098-11ea-96cc-3b2f83892fb5.png)

referenced vsix is:
https://github.com/microsoft/vscode-pull-request-github/releases/download/0.14.0/vscode-pull-request-github-0.14.0.vsix

**Comment by gattytto** [comment]
https://github.com/microsoft/vscode-pull-request-github/blob/7ddf57e525cebb4157f28bdd1b2e741d288a7ade/src/gitProviders/builtinGit.ts#L24

**Comment by ibuziuk** [comment]
@gattytto could you please provide steps to reproduce? Basically, GH PR plugin is part of che-theia out of the box and not expected to be updated - https://github.com/eclipse/che-theia/tree/master/plugins/github-auth-plugin

**Comment by ibuziuk** [comment]
cc: @ericwill

**Comment by ericwill** [comment]
Yes please provide steps to reproduce the issue, specifically how you are "upgrading" the plugin.

**Comment by gattytto** [comment]
> @gattytto could you please provide steps to reproduce? Basically, GH PR plugin is part of che-theia out of the box and not expected to be updated - https://github.com/eclipse/che-theia/tree/master/plugins/github-auth-plugin

I think you are referring to the git builtin which is the one the pull requests extension seems to rely on, but some function from newest ms-vscode builtin is not yet present in theia. The extension I am referring to is this one:
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/vscode-github-pullrequest/0.8.0/meta.yaml

And this is the version I am trying to use:
https://github.com/gattytto/che-plugin-registry/blob/gopos/v3/plugins/ms-vscode/vscode-github-pullrequest/0.14.0/meta.yaml

**Comment by gattytto** [comment]
> Yes please provide steps to reproduce the issue, specifically how you are "upgrading" the plugin.

Above comment has the meta.yaml I added to my plugin registry

**Comment by gattytto** [comment]
@ibuziuk I have edited my previous comment with a mention to you.

Can this be checked?
