### ISSUE TITLE
[Enhancement] Extending Eclipse Che CI infrastructure support to s390x

### ISSUE THREAD

**Issue by shahidhs-ibm** [eclipse-che/che#16287]
### Is your enhancement related to a problem? Please describe.
This is a feature request to add support of s390x architecture to Eclipse Che CI infrastructure (`https://ci.codenvycorp.com/job/che-master-ci/` and `https://ci.centos.org/job/<pkg>`)

### Describe the solution you'd like
We have Open Source Labs hosted Jenkins service at  [https://osuosl.org/services/ibm-z/](https://osuosl.org/services/ibm-z/). We will take the responsibility for all development, support and maintenance tasks for Jenkins jobs which will run for s390x arch. 

### Describe alternatives you've considered
Kindly suggest alternatives in case above feature proposal have any issue(s).

### Additional context
We will like to publish the generated build artifacts (binaries / docker images etc) for s390x in the Eclipse Che releases and `quay.io` docker repository as well.

Kindly let us know if any additional information is required.

**Comment by ibuziuk** [comment]
CI on mainframes \o/ 
@l0rd assigning to devex team for analysis

**Comment by shahidhs-ibm** [comment]
@ibuziuk Thanks for the positive response. Along with extending support to s390x, we would also like to publish the s390x docker images to Eclipse Che docker repository i.e. `quay.io`. We understand that `quay.io` does not support multiarch images so we would like to publish our images appending `-s390x` to the image name.
This feature will need some code modifications to read architecture specific `.yaml`, `.properties` and `Dockerfile`. We are currently working on same and will create a PR once we are done.

**Comment by shahidhs-ibm** [comment]
@ibuziuk I have created a Jenkins project to build [che-machine-exe](https://ibmz-ci.osuosl.org/job/che-machine-exec_IBMZ_CI/) on the OSU/OSL Jenkins service for s390x. Kindly check and let me know your comments. Looking forward to extend this CI similar for other Eclipse Che repositories.

**Comment by l0rd** [comment]
@shahidhs-ibm what do you expect from us? What changes?

**Comment by shahidhs-ibm** [comment]
@l0rd We are looking for two main support from your side:
1. Adding links for s390x Jenkins builds to reflect the IBM Z support
2. Publishing the built docker images for s390x on `quay.io`.

For e.g. Tensorflow is one of the communities which supports IBM Z builds. Please refer to [link](https://github.com/tensorflow/tensorflow#community-supported-builds) for more details.

Please let us know your thoughts/comments.

**Comment by l0rd** [comment]
Ok I see and I am +1 for that.

For 1. a link to the s390 build status badge in our repositories README files is what you are thinking about? In that case the simpler would be to directly open the corresponding PRs.

For 2. I think the simpler would be to create a quay.io bot if you don't have one yet and we grant the privileges to add push new images on our repos.

Do that sounds like a good plan?

**Comment by shahidhs-ibm** [comment]
Sounds like a good plan to me.

For 1. We will create a PR to update README files to display s390x build status batch.
For 2. We will create a bot user with an account on Quay.io and will share its details with you (for granting the repository write access).

**Comment by shahidhs-ibm** [comment]
@l0rd Could you please add the GitHub hook URL (https://ibmz-ci.osuosl.org/github-webhook/) of Jenkins server into [che-machine-exec](https://github.com/eclipse/che-machine-exec) GitHub repository for us to get the build triggers?

**Comment by shahidhs-ibm** [comment]
@l0rd Any updates?

**Comment by ibuziuk** [comment]
@shahidhs-ibm I belive we will need to ask eclipse webmaster to do this, since we do not have an admin access 
@skabashnyuk will you be able to give a hand with this?

**Comment by shahidhs-ibm** [comment]
@skabashnyuk Could you please add a GitHub webhook to our Jenkins pipeline as per above discussion?

**Comment by benoitf** [comment]
Hello, AFAIk with buildx we don't need other CI infrastructure as we can build for arm, z, power, etc.

Besides, 
> We understand that quay.io does not support multiarch images so we would like to publish our images appending -s390x to the image name.

is not correct as we can publish multi-arch images on quay.
So I'm not sure what is all about.

**Comment by benoitf** [comment]
so, it would be nicer to have compliant Dockerfiles/build scripts to be multi-arch aware and provide multi-arch images by default (including Z)

**Comment by shahidhs-ibm** [comment]
@benoitf From [comment](https://github.com/eclipse/che/issues/16287#issuecomment-605948656) point#2 is invalid now. This was based on some past info we had which is obsolete now.

For point#1, we want to display s390x build status badge in README files similar to the batch which displays build status from `ci.centos.org`. Let us know if this is possible.

About [comment](https://github.com/eclipse/che/issues/16287#issuecomment-623487679), we are working on this analysis and keep you posted.

**Comment by shahidhs-ibm** [comment]
Do you have any plans to switch to github actions/ travis from `ci.centos.org` for building docker images? For `ci.centos.org` which is Jenkins, how we can extend support to s390x? Can we use our own Jenkins server to build and push images as mentioned in [comment](https://github.com/eclipse/che/issues/16287#issue-578007702)? Any suggestions?

**Comment by benoitf** [comment]
Hello,

by using buildx we can publish new multi-arch images so we may not require external jenkins server.

**Comment by shahidhs-ibm** [comment]
Thank you @benoitf 
We will work on adding `docker buildx` in the Jenkins scripts for enabling multi-arch support.
