### ISSUE TITLE
Ports not exposed when using Docker for Mac

### ISSUE THREAD

**Issue by Blacktiger** [eclipse-che/che#1629]
I tried to run che using the Docker instructions, but I can't access che after it starts on port 8080.

```
$ docker run --net=host --name=che \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  -v /home/user/che/lib:/home/user/che/lib-copy \
                  -v /home/user/che/workspaces:/home/user/che/workspaces \
                  -v /home/user/che/storage:/home/user/che/storage \
                  codenvy/che

############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
#############################################################
...
2016-07-01 17:16:24,305[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/wsmaster.war has finished in 4,479 ms
2016-07-01 17:16:24,313[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/tomcat/webapps/dashboard.war
2016-07-01 17:16:24,594[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/tomcat/webapps/dashboard.war has finished in 281 ms
2016-07-01 17:16:24,597[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory /home/user/che/tomcat/webapps/ROOT
2016-07-01 17:16:24,674[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory /home/user/che/tomcat/webapps/ROOT has finished in 78 ms
2016-07-01 17:16:24,688[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-8080"]
2016-07-01 17:16:24,711[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 6313 ms
```

I attempted to start the container with -p to control the port mapping as well.

```
$ docker run --net=host --name=che -d -p 8080:8080 \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  -v /home/user/che/lib:/home/user/che/lib-copy \
                  -v /home/user/che/workspaces:/home/user/che/workspaces \
                  -v /home/user/che/storage:/home/user/che/storage \
                  codenvy/che
```

In both cases, if I run `docker port che` I get nothing in the output. I have no idea if this is a problem with Docker for Mac or they way che is trying to set things up.

**Comment by TylerJewell** [comment]
Hi @Blacktiger - we have a long running set of pull requests going on to fix these issues for Docker for Mac.  Docker for Windows is supported, but improvements needed for Mac as it's a different system.  Please see this pull request.  May I close this issue so that you can track the other one?

https://github.com/eclipse/che/issues/1482

**Comment by Blacktiger** [comment]
Sure, I saw that issue but didn't realize it was a catch-all for Mac docker
issues.

On Friday, July 1, 2016, Tyler Jewell notifications@github.com wrote:

> Hi @Blacktiger https://github.com/Blacktiger - we have a long running
> set of pull requests going on to fix these issues for Docker for Mac.
> Docker for Windows is supported, but improvements needed for Mac as it's a
> different system. Please see this pull request. May I close this issue so
> that you can track the other one?
> 
> #1482 https://github.com/eclipse/che/issues/1482
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/eclipse/che/issues/1629#issuecomment-230002258, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAFTm5tHwyMBIkMAgk-KWJ5aIvCGh13Pks5qRUyygaJpZM4JDVGg
> .

## 

Concentrate on the solution, not the problem.

**Comment by TylerJewell** [comment]
Yeah, the xhyve VM has its own IP address and port mapping system.  So it's on a different IP address, and it's rather challenging to discover the right IP.  We had to make some internal changes to Che in order for it to properly segment certain handlers.  Those changes have been merged.  You should be able to test the new syntax, which was provided at the bottom of the page.  We are just waiting for QA or the community to confirm that it works.  If you can comment in that threat on whether it works for you or not, we may be able to finish the issue quicker.

**Comment by TylerJewell** [comment]
@Blacktiger - FYI, we have confirmed that Docker for Mac is now working.  We have stood up a documentation page explaining the changes that you need.  Make sure you have the latest image for this to work.

https://eclipse-che.readme.io/docs/usage-docker-for-mac

**Comment by Blacktiger** [comment]
Thanks Tyler, I. Was able to follow the new instructions and get Che up
 and running for Docker for Mac this time.

On Friday, July 1, 2016, Tyler Jewell notifications@github.com wrote:

> @Blacktiger https://github.com/Blacktiger - FYI, we have confirmed that
> Docker for Mac is now working. We have stood up a documentation page
> explaining the changes that you need. Make sure you have the latest image
> for this to work.
> 
> https://eclipse-che.readme.io/docs/usage-docker-for-mac
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/eclipse/che/issues/1629#issuecomment-230069372, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAFTmx8SX1hPB8ZHxTqPl3k6Ak1j5qBtks5qRabtgaJpZM4JDVGg
> .

## 

Concentrate on the solution, not the problem.

**Comment by TylerJewell** [comment]
Cool.  What are your impressions of the product so far?

**Comment by Blacktiger** [comment]
I like the idea of starting up docker containers to run everything so that
(in theory) it should be really easy to share workspaces between
developers. There is one thing I'm not currently clear about though, is
Java 8 required for the workspace? I have a legacy product I'm hoping to
get working in che, but it requires Java 6, Ant, and Maven 3.0 to build and
run. Looks like I can define a custom recipe to make sure that everything I
need is installed in the workspace, but if I swap out Tomcat and Java for
older versions will everything still work?

On Sat, Jul 2, 2016 at 6:59 PM, Tyler Jewell notifications@github.com
wrote:

> Cool. What are your impressions of the product so far?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/eclipse/che/issues/1629#issuecomment-230127903, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAFTm-Qh5PjD9-VRloGpjQ76uzGbv1j4ks5qRvt1gaJpZM4JDVGg
> .

## 

Concentrate on the solution, not the problem.

**Comment by TylerJewell** [comment]
We require Java 8 inside the workspace for us to run our agents.  But you can install a Java 6 JVM inside of it with a custom recipe and the two should not conflict.  You'll have to manage the PATH and JAVA_HOME variables properly to avoid conflicts, but no reason they both cannot co-exist.

We are also running an older version of Tomcat in there - so you will have to avoid the conflicts at that level, too.
