### ISSUE TITLE
Could cheFlavor be an env var like all the other settings moved from defaults.go ?

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16305]
### Is your enhancement related to a problem? Please describe.

If we could externalize cheFlavour maybe we could make che-operator even MORE generic between che and crw versions.
 
### Describe the solution you'd like

Following the path of https://github.com/eclipse/che-operator/commit/e9c5d3f312f07d73187075fcdd36423aae374edc and https://github.com/eclipse/che/issues/15874 we could externalize cheFlavor.

cc: @davidfestal

**Comment by davidfestal** [comment]
Yes, that would be helpful to make upstream / downstream flow cleaner

**Comment by tolusha** [comment]
Fixed in https://github.com/eclipse/che-operator/pull/247
