### ISSUE TITLE
run che on eclipse with tomcat

### ISSUE THREAD

**Issue by alexmarques** [eclipse-che/che#1630]
Just want to know if there is any possibility to run che on eclipse with tomcat... Im trying to do it... but still no success. Thanks!

**Comment by TylerJewell** [comment]
Not sure I understand.  The default Che assembly includes its own tomcat.  Can you elaborate the steps you take?

**Comment by alexmarques** [comment]
I downloaded che, ran the che.bat inside bin directory, but it show a message that i must run docker... which i cannot download here at the company... so I opened eclipse neon... imported the four wars inside the tomcat tha came with che... I run tomcat... when I try to access the url it just show a never ending spinning image...

**Comment by TylerJewell** [comment]
Che requires docker.  The workspaces generated by Che are done inside of workspaces.  It is what makes them portable.

I recommend that you run Che inside of our vagrantfile using the vagrant launcher.  This will run a VM that has everything inside you need.

**Comment by alexmarques** [comment]
I'll try it out then.. thanks!
