### ISSUE TITLE
Ability to build docker images from Che

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16307]
### Is your enhancement related to a problem? Please describe.

Considering how che is super relying on images and containers, I'd say it's very important if we can easily build images while in Che.

**Comment by vitaliy-guliy** [comment]
With this PR ( https://github.com/eclipse/che-plugin-registry/pull/422 ) you will be able to build a docker image with `buildah`. Just to add the kubernetes plugin to your workspace. After starting, open a terminal in `vscode-kubertetes-tools` container, go to the directory with a dockerfile and run `buildah bud .`

We can close this issue after merging the PR.

Btw, there is a video demonstrating how the `buildah` works
https://www.youtube.com/watch?v=pNjTmjhnGJw
