### ISSUE TITLE
Che workspace name doesn't allow underscores but error message says its fine?

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#16303]
### Describe the bug

I went to go and create a workspace with the name `test_workspace`, and Che gave me the following error:
```
The name should not contain special characters like space, dollar, etc. and should start and end only with digits, latin letters or underscores.
```

The `should start and end only with digits, latin letters or underscores` part in the error message leads me to believe that underscores would be fine in the workspace name, but it won't allow me to create the workspace. 

Is the validation correct in this case and the error message just needs to be updated to be more clear or does the validation need to be updated to support workspace names with underscores?

### Che version

7.9.0

### Steps to reproduce
1. Deploy Che
2. Try to create a workspace with an underscore in the name

### Expected behavior

Either Che lets me create a workspace with underscores in its name or the error message is clear and says that underscores aren't allowed.

### Screenshots
<img width="1476" alt="Screen Shot 2020-03-10 at 12 29 36 PM" src="https://user-images.githubusercontent.com/6880023/76335434-e732bf80-62ca-11ea-954b-d65ceae3e32e.png">

**Comment by l0rd** [comment]
I think that's just the message that should be updated (underscores are not allowed, even at the start/end of string) cc @olexii4 @akurinnoy

**Comment by sleshchenko** [comment]
According to Che API, underscores should be allowed in the middle of workspace name https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java#L50
BTW error message does not seem to be clear and right, it must be revised.

**Comment by olexii4** [comment]
@l0rd It is an old bug. We have improved the 'Get Started' page and now we have:
![Screenshot from 2020-05-28 15-25-39](https://user-images.githubusercontent.com/6310786/83141286-130a5800-a0f8-11ea-9c21-e7417f471e21.png)
![Screenshot from 2020-05-28 15-26-55](https://user-images.githubusercontent.com/6310786/83141289-14d41b80-a0f8-11ea-8763-0aed74a6e9cb.png)

**Comment by sleshchenko** [comment]
It seems to be still actual because `asd_` says that `it's not valid because it should start and end only with ..., underscores` :exploding_head:

**Comment by akurinnoy** [comment]
I'm going to update the message in following way:
`The name should not contain special characters like space, dollar, etc. It should start and end only with digit or latin letter.`

**Comment by olexii4** [comment]
client-side regex:  ['^[A-Za-z0-9][A-Za-z0-9_\\-\\.]+[A-Za-z0-9]$'](https://github.com/eclipse/che-dashboard/blob/0951545e101ef298204fd661d8f63a1a68f9cf10/src/app/get-started/custom-workspace-tab/workspace-name-row/workspace-name-row.controller.ts#L58)
server-side regex: ["[a-zA-Z0-9][-_.a-zA-Z0-9]{1,98}[a-zA-Z0-9]"](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java#L50)

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che-dashboard/pull/53
