### ISSUE TITLE
Setup devfile to work with github.com/redhat-developer/devfile

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16317]
### Is your task related to a problem? Please describe.
Setup devfile to work with github.com/redhat-developer/devfile repository

### Describe the solution you'd like
if you manually edit the files and do PRs a devfile would be useful here. Even if it's just markdown and yaml support.

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by ibuziuk** [comment]
Done https://github.com/redhat-developer/devfile/pull/62
Closing
