### ISSUE TITLE
Custom docker image based Work space doesn't have a user in Terminal

### ISSUE THREAD

**Issue by YasithaSandeep** [eclipse-che/che#16315]
I have created a docker image from java 8 and gradle 3.3. Workspace starts without any issue but when i click on gradle terminal. only the $ will appear. so i have to manuall type bash and enter other commands. what am I doing wrong here??

![image](https://user-images.githubusercontent.com/48114694/76408817-90ed7b80-63b3-11ea-968b-e46dce33b8f7.png)

![image](https://user-images.githubusercontent.com/48114694/76409086-ede93180-63b3-11ea-8306-975fe31f2bdb.png)

**Comment by sleshchenko** [comment]
@YasithaSandeep The default shell is detected using /etc/passwd file. To initialize shell you want you to need to update that file after container is started.
here you can find how we do it https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/centos/entrypoint.sh#L17
https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/centos/Dockerfile#L51

probably you don't need anything... Let us know if you still have issues with your image or close the issue if it helps you
