### ISSUE TITLE
When I click the Edit button on Che's user account page, a blank page appears.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#16326]
## Summary

I want to edit my account information. 
When I click the Edit button on Che's user account page, a blank page appears.
In keycloak page, I checked that the account client ID is enabled.
I am wondering if this error is only from me or from Che. Also I want to know how to solve it.

### Che version
7.4.0

### Screenshots

![image](https://user-images.githubusercontent.com/29850624/76487251-2e54b800-6465-11ea-920b-83dabc3b9efc.png)

### Installation method
helm

### Environment
Amazon EKS

**Comment by tolusha** [comment]
@kellyhyomin 
Have you tried the latest 7.9.0 version?

**Comment by sleshchenko** [comment]
In the fresher versions, you should be redirected to keycloak page where you're able to edit profile info.
@kellyhyomin Feel free to reopen if it does not work in the described way.
