### ISSUE TITLE
Prepare Eclipse Che release testing Jenkins jobs to check Eclipse Che 7.10

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16323]
We are usually testing Eclipse Che release candidate using testing Jenkins jobs which check Eclipse Che in HTTP mode being deployed to minishift/minikube using operator installer.

Actually, Eclipse Che 7.10 is installed in TLS mode by default, and it doesn't work being installed by operator installer because of problem with TLS certificate https://github.com/eclipse/che/issues/16280 

So, we need to work around it: 
- to disable TLS mode while testing Eclipse Che with operator installer on Centos Jenkins CI;
- to setup CRW CCI testing jobs to check Eclipse Che on minikube with helm installer in TLS mode.

**Comment by mmorhun** [comment]
@dmytro-ndp FYI #16280 is done.

**Comment by rhopp** [comment]
Referenced issue is closed. Nothing to do here.
