### ISSUE TITLE
[chectl] Installation of Eclipse Che 7.10.0.RC with custom templates folder using helm chart installer failed on minikube

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16338]
### Describe the bug
Installation of Eclipse Che 7.10.0.RC with helm chart installer failed on minikube
> /usr/local/bin/chectl server:start --k8spodreadytimeout=180000 -t=/mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/deploy/ --platform=minikube --listr-renderer=verbose --skip-version-check --self-signed-cert --cheimage=eclipse/che-server:rc

```
14:09:23 [08:09:23] Deploy cert-manager [started]
14:09:23 [08:09:23] Deploy cert-manager [failed]
14:09:23 [08:09:23] → Command failed with exit code 1: kubectl apply -f /mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/installers/cert-manager.yml --validate=false
14:09:23 error: the path "/mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/installers/cert-manager.yml" does not exist
14:09:23 [08:09:23] Check Eclipse Che TLS certificate...going to generate self-signed one [failed]
14:09:23 [08:09:23] → Command failed with exit code 1: kubectl apply -f /mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/installers/cert-manager.yml --validate=false
14:09:23 error: the path "/mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/installers/cert-manager.yml" does not exist
14:09:23 [08:09:23] 🏃‍  Running Helm to install Eclipse Che [failed]
14:09:23 [08:09:23] → Command failed with exit code 1: kubectl apply -f /mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/installers/cert-manager.yml --validate=false
14:09:23 error: the path "/mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-path-tests-against-K8S/installers/cert-manager.yml" does not exist
14:09:23  ›   Error: Error: Command failed with exit code 1: kubectl apply -f 
14:09:23  ›   /mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-pat
14:09:23  ›   h-tests-against-K8S/installers/cert-manager.yml --validate=false
14:09:23  ›   error: the path 
14:09:23  ›   "/mnt/hudson_workspace/workspace/Single-Che-pre-release-check-E2E-Happy-pa
14:09:23  ›   th-tests-against-K8S/installers/cert-manager.yml" does not exist
14:09:23  ›   Installation failed, check logs in '/tmp/chectl-logs/1584014962469'
14:09:23 Build step 'Execute shell' marked build as failure
14:09:24 Run condition [Always] enabling perform for step [[Execute Scripts]]
14:09:24 [PostBuildScript] - Executing post build scripts.
```

### Possible reason
there are wrong container image tags (empty or 7.11.0) in Eclipse Che 7.10.0.RC helm charts: https://github.com/eclipse/che/commit/1eaeb833296b723f1a2671eb1e62a0e954d729a0#diff-38275c40bc918188a5eedbe0d3940b8d

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.10.0.RC

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] [chectl:0.0.20200311-next.938b592](https://github.com/che-incubator/chectl/releases/tag/20200311080209) with helm installer  
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

**Comment by mmorhun** [comment]
To workaround the issue create directory `installers` near `templates` folder (on the same level) and put file `cert-manager.yml` in it. (You may find this file in chectl repository under `installers` directory).
I think I will be able to fix this problem after next cert-manager release.

**Comment by dmytro-ndp** [comment]
@mmorhun: thanks for explanation.
Did you mean to put **cert-manager.yaml** file into **deploy/kubernetes/installers** directory?

**Comment by dmytro-ndp** [comment]
[Workaround](https://github.com/eclipse/che/issues/16338#issuecomment-598210618) does work.
