### ISSUE TITLE
Can't load Theia IDE on Safari because since CORS error happened

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16335]
### Describe the bug
Can't load Theia IDE on Safari.

Actually, it's caused by error of setting cookies for Theia host (loader.html+JTWProxy workflow)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open Che on Safari.
2. Try to start any workspace.

### Expected behavior
Workspace is stared and theia is loaded.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
<img width="1440" alt="Screenshot 2020-03-12 at 11 13 14" src="https://user-images.githubusercontent.com/5887312/76521343-5516ec80-646d-11ea-93fa-517c5ecc82c4.png">
<img width="1440" alt="Screenshot 2020-03-12 at 11 17 36" src="https://user-images.githubusercontent.com/5887312/76521346-55af8300-646d-11ea-8a0f-6357063f97fa.png">

### Installation method
   - [x] chectl server:start --multiuser --installer=helm --platform=minikube
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
Nothing special

### Workarounds

from @mingfang 
> To workaround #16335 I added this to my nginx proxy
> ```
> add_header 'Access-Control-Allow-Origin' '*';
> ```

from @btannous 
> Open developers tools and disable CORS checks

**Comment by btannous** [comment]
+1 also effects me on both iOS on the iPad Pro and Safari on OS X. My environment is crc v1.7.0.

Will try to look a little deeper, but logging in works! =) Thanks for that @sleshchenko and @ibuziuk and team =)
