### ISSUE TITLE
Theia IDE and Webview servers shares the same host

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16330]
### Describe the bug
Che Server seems to ignore `unique` attribute of webview server:
![Screenshot_20200312_120253](https://user-images.githubusercontent.com/5887312/76510070-acab5d00-6459-11ea-8192-c8fe16a7a830.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che with `chectl server:start --multiuser --installer=helm --platform=minikube`
2. Start any Theia based workspace.
3. Check if Theia and Webview have the same host.

### Expected behavior
Theia and Webview have different hosts.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl server:start --multiuser --installer=helm --platform=minikube
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
I don't think it does matter, if yes - let me know

**Comment by tolusha** [comment]
@sleshchenko 
What does this bug cause? any issue with that?

**Comment by sleshchenko** [comment]
@tolusha A little security issue ) Webview is supposed to run on a different host to avoid Theia cookies to be compromised... It's just little security issue but not more ;)

**Comment by sparkoo** [comment]
fixed by #16692
