### ISSUE TITLE
NullPointerException in KubernetesDeployments

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16349]
### Describe the bug
```
2020-03-13 08:23:59,973[.39.32:8443/...]  [WARN ] [k.c.d.i.WatchConnectionManager 201]  - Exec Failure
java.lang.NullPointerException: Both parameters are null
	at com.google.common.base.MoreObjects.firstNonNull(MoreObjects.java:61)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.eventReceived(KubernetesDeployments.java:540)
```

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
 just started new workspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
n/a
### Additional context
n/a

**Comment by sparkoo** [comment]
I couldn't reproduce it again. There is probably some precondition for it. Will comment if I see it again.
