### ISSUE TITLE
GitHub PR plugin is not updated after providing an authentication token

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#16344]
### Describe the bug

A GitHub token input does not affects the GitHub plugin until the browser page is not reloaded.
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a workspace with GitHub projects and enabled GitHub PR plugin
2. Go to `GitHub Pull Requests: Manually Provide Authentication Response` and input the GitHub token.
See: nothing happens until the browser page is relaoded:
![video-convert](https://user-images.githubusercontent.com/7668752/76539268-37f01700-6489-11ea-9be4-6fb8bdb6042d.gif)

### Expected behavior

The pull request view should be updated automatically after providing the token.
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ericwill** [comment]
@vinokurig is this one still relevant given we use a different authentication scheme now and newer plugin version?

**Comment by vinokurig** [comment]
@ericwill You are right, it is fixed by https://github.com/eclipse/che-plugin-registry/pull/640 and https://github.com/eclipse/che-theia/pull/841
