### ISSUE TITLE
Che-Theia does not include the latest version of @theia/yeoman-plugin containing important fixes

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16354]
### Describe the bug

Che-Theia still use `0.0.1-1562576566` version of `@theia/yeoman-plugin`.
But there is a new `0.0.1-1578930705` version of the plugin with important fixes of the yeoman wizard, giving the ability to generate VS Code extensions.

https://www.npmjs.com/package/@theia/yeoman-plugin?activeTab=versions

### Che version

 - [x] latest
 - [x] nightly

**Comment by tsmaeder** [comment]
Since we're mostly promoting VS Code extensions, wouldn't it make more sense to rely on their tooling to create template plugins? One less thing we need to take care of.

**Comment by benoitf** [comment]
@tsmaeder the yeoman plug-in is not a Theia template.
