### ISSUE TITLE
new welcome page every time when I refresh my workspace

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16352]
### Describe the bug

Che-Theia always open a new Welcome page when refreshing the workspace.
It looks like the bug is appeared after merging this PR https://github.com/eclipse/che-theia/pull/605
I have a strong opinion that we have to revert that branch.
We don't need to store the Welcome page, let the welcome plugin decide whether it should be opened or not (depends on config in preferences).
BTW, on restored welcome page, hyperlinks with commands does not work.

Screencast with the bug https://youtu.be/Ija0oU-i2AY

### Che version

 - [x] latest
 - [x] nightly

### Steps to reproduce

1. Create and open a workspace.
2. Refresh the browser.
3. Refresh the browser.
4. ...

### Expected behavior

One welcome page with working hyperlinks.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Environment
   - [x] my computer
       - [x] Linux

**Comment by vitaliy-guliy** [comment]
To solve this issue need to be merge
- [ ] https://github.com/eclipse-theia/theia/pull/8473
- [ ] https://github.com/eclipse/che-theia/pull/848

**Comment by azatsarynnyy** [comment]
FYI: Che Theia is already aligned with upstream Theia https://github.com/eclipse/che-theia/pull/823
So, you can check if the issue is solved.
