### ISSUE TITLE
Theia cannot reach the API server with both TLS and proxy enabled

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#16356]
### Describe the bug

When both TLS and http proxy are enabled, it seems that Theia cannot reach the Che server API endpoint by its external URL.

This becomes critical now that TLS is enabled by default to have webviews working.

This might be related to this Axios bug: https://github.com/axios/axios/issues/925#issuecomment-574617787

### Che version
 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Configure a Che server installation with a proxy and without TLS: Che-theia workspace should be able to start correctly (with webview problems though)
2. Configure a Che server installation with a proxy and with TLS: You should see some errors in the Che-theia logs and Che-theia would be able to fetch the workspace definition from the Che API server

### Expected behavior

http proxy configuration should work even when TLS is enabled (which is the default case now)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context

This might be critical for CRW 2.1 and possibly to include into the [7.9.2](https://github.com/eclipse/che/issues/16229) release

**Comment by davidfestal** [comment]
One possible way to fix it might be to use the solution proposed here: https://github.com/axios/axios/issues/925#issuecomment-513028175 in the `che-workspace-client`, in case `https_proxy` env variable is set *and* TLS mode is enabled (API URL starts with `https`)
cc @vinokurig

**Comment by davidfestal** [comment]
@dmytro-ndp  @RickJWagner seemed to think it should be considered as a blocker for CRW 2.1

@rhopp @l0rd do you confirm ?

**Comment by rhopp** [comment]
I tend to agree... Running without tls or without proxy is imo no-go for lot of production environments.

**Comment by davidfestal** [comment]
I assigned it me since I'm currently investigating it in the context of the restricted environment tests (required to continue the tests until the end), and @ivinokur (who knows this codebase) kindly proposed his help to implement a potential fix in a temporary 7.9.x-based che-teia docker image (already available). So as soon as I've tested this image and confirmed it can fix the issue, I assume we would propose a PR for the controller team to review, in order to possibly finally update the generated NPM package in the `7.9.x` branch of che-theia

**Comment by vinokurig** [comment]
@davidfestal Did my fix helped?

**Comment by davidfestal** [comment]
I tested the docker image provided by @vinokurig based on this proposed fix: https://github.com/axios/axios/issues/925#issuecomment-513028175 But it doesn't seem to fix the problem.

**Comment by davidfestal** [comment]
After a bunch of tests done with the `axios` library *inside the `che-theia` container of a `Che` workspace* running in a disconnected environment behind a proxy*, here is the current analysis of the problem:
The error was coming from the fact that `axios` implementation of `https` requests through a `http` proxy is limited. In particular, it seems it doesn't correctly use the CONNECT method that allows tunneling a `https` request inside a `http` proxy.
A consequence of this is that the underlying socket connection opened to finally reach the target endpoint is not a ssl socket. This finally results in an error from the Proxy, especially with self-signed certificates.

The good news of this is that Axios is configurable / customizable enough, so that, when a https request needs a http proxy,  we should be able to override the request config to change the `httpsAgent` and use one created by the [`tunnel`](https://github.com/koichik/node-tunnel) module.

I already tested the [`tunnel` module](https://github.com/koichik/node-tunnel) solution and was able to reach the Che API server through the proxy even with TLS and self-signed certificates.

I'll further propose a PR to include this into the existing `che-workspae-client` package.

**Comment by davidfestal** [comment]
The possible fix mentioned in previous comment has been implemented and tested with the help of @ivinokur and it seems to correctly fix the bug on a disconnected environment cluster with a proxy.
I was able to start a workspace and use a terminal as shown in the screen capture.

![image](https://user-images.githubusercontent.com/686586/76991602-2788e200-694a-11ea-9f4c-51f5adaa15cd.png)

Only remaining problem is the loading of the project zip through the proxy by wget . That a completely different problem though.

**Comment by davidfestal** [comment]
Main bug will be fixed by PR https://github.com/eclipse/che-workspace-client/pull/28 as soon as the built MPN package is updated in `che-theia`.

**Comment by disaster37** [comment]
Hi, I have started che 7.17.0 and I have the same matter when deploy it with tls and use enterprise proxy.
All start right on kubernetes, and my browser access to teiga, but all is blank and nothing work.

How I can mitigate this ?

Best Regards
