### ISSUE TITLE
How can I run theia/examples/assembly on my localhost?

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#16359]
I follow the instructions of https://www.npmjs.com/package/@eclipse-che/theia-generator but It doesn't run.

1. che:theia init -c config.yml // success
2. yarn // success
3. cd examples/assembly 
4. yarn start // fail 
or yarn // memory error

**Comment by ibuziuk** [comment]
@azatsarynnyy could you please take a look?

**Comment by azatsarynnyy** [comment]
> or yarn // memory error

Hello @cenkce
try with setting `export NODE_OPTIONS=--max_old_space_size=4096`

**Comment by cenkce** [comment]
@azatsarynnyy, There is just `yarn start` command in the instructions. Must we run `yarn` command before?

**Comment by cenkce** [comment]
Isn't it enough to run `yarn` command at the root of Theia?

**Comment by cenkce** [comment]
`yarn` command at the root can't build che packages and there is no lib folder inside of them. Therefore  che modules can't be resolved.

**Comment by azatsarynnyy** [comment]
The latest version of `@eclipse-che/theia-generator` package has been updated on https://www.npmjs.com/package/@eclipse-che/theia-generator.
@cenkce please try and let us know if you have any problems with it.

**Comment by cenkce** [comment]
Hi @azatsarynnyy, 
if I don't delete yarn.lock then I constantly received this error:
```
'Failed to resolve module: @primer/octicons-react\nFailed to resolve module: react-virtualized\n(node:11959) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead\n\nError: webpack exited with an unexpected code: 2.\n    at ChildProcess.<anonymous> (/Users/cenkce/Desktop/theia-dev/theia/dev-packages/application-manager/lib/application-process.js:66:28)\n    at ChildProcess.emit (events.js:193:13)\n    at maybeClose (internal/child_process.js:999:16)\n    at Socket.stream.socket.on (internal/child_process.js:403:11)\n    at Socket.emit (events.js:193:13)\n    at Pipe._handle.close (net.js:614:12)\nerror Command failed with exit code 1.\nerror Command failed with exit code 1.\n',
```

**Comment by cenkce** [comment]
It built che packages but it can't create src-gen in assembly folder and gives error : 

```
% yarn start
yarn run v1.22.1
$ theia start
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/Users/cenkce/Desktop/theia-dev/theia/examples/assembly/src-gen/backend/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
✨  Done in 1.33s.
```

**Comment by azatsarynnyy** [comment]
I've just tried the following steps:
```
git clone git@github.com:eclipse-theia/theia.git && cd theia
che-theia init && yarn
cd examples/assembly/ && yarn start
```
And Che Theia has successfully started.

@cenkce please, verify what `che-theia --version` is installed. It has to be the latest one - `0.0.1-1584989953`. Did you run `che-theia init` on a freshly cloned Eclipse Theia sources?

**Comment by cenkce** [comment]
Yes, when I use fresh versions and it solved. Thanks
