### ISSUE TITLE
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#1636]
Docker container requires newer version of Docker daemon than described at [Prereq](https://eclipse-che.readme.io/docs/install-pre-reqs)

> Make sure your OS distribution has a kernel that supports Docker 1.8.

**Reproduction Steps:**
1. Run `docker run` same as description on [Usage: Docker](https://eclipse-che.readme.io/docs/usage-docker)

**Expected behavior:**

The container runs.

**Observed behavior:**

che.sh failed with this message.

```
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
```

[Describe observed behavior here]

**Che version:**   4.4.0. Image digest is  sha256:740fe2bd7a325588031882bcee517d49baac9c68e2d4d2e92397cf386985e6c0.

**OS and version:** CoreOS 1010.6.0 (MoreOS)
**Docker version:** 10.0.3
**Che install:**   Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Unknown
- Problem can be reliably reproduced, doesn't happen randomly: 100% reproduction.

**Comment by ghost** [comment]
@monaka this error is caused by difference in versions of Docker in Che base image and your local Docker. Solution - either downgrade Docker in Che container or upgrade Docker on your CoreOS instance. I think option #2 is easier.

**Comment by monaka** [comment]
Yes. I know the reason why this issue is caused. There have an inconsistent requirement between [the official document (>=1.8)](https://eclipse-che.readme.io/docs/install-pre-reqs) and the official docker image (== latest). It's a point for me.

IMO,the better way is to fix description in `install-pre-req` or to add the special notice about  the version requirement for official Docker images.
Users can figure out easier if it was documented.

**Comment by ghost** [comment]
@monaka Those requirements are to run Che as a server. Indeed, running it as a Docker container may cause such issues with host and container Docker versions incompatibility. I'll add some notes to docs.

**Comment by ghost** [comment]
@monaka you may try the new installer https://eclipse-che.readme.io/docs/usage-docker-launcher?

**Comment by TylerJewell** [comment]
@monaka - we look forward to your feedback on the new installer. One of the things this does is to launch Che from within a container. So it lets us standardize the client that is invoking Che into a container that works the same on everyone's computer.  So this issue should go away.  We are still making some improvements, but it is largely stabilized now.

**Comment by monaka** [comment]
@eivantsov @TylerJewell , I checked your new installer. My first impression is :+1: :sushi:.
It runs on my CoreOS 1010.6.0 (MoreOS).

**Comment by TylerJewell** [comment]
Thanks for the feedback!
