### ISSUE TITLE
Failed to add github repository.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#16364]
## Summary

I want to add github to projects.
When I click the connect your github account button on Che's new workspace page, a blank page appears.
I tried to refer to this page(https://www.eclipse.org/che/docs/che-7/configuring-github-oauth/), but it doesn't work.
I would like to know how to fix it.

### Che version
7.4.0, multi-user

### Screenshots

![projects_github_error](https://user-images.githubusercontent.com/29850624/76722383-bd740f80-6786-11ea-91a7-11ad9295a41f.gif)

### Installation method
helm

### Environment
Amazon EKS

**Comment by IveJ** [comment]
Dear Kelly,

Plz try to check your setting org/repo in account setting and find out sth
like like enable 3rd app authenticate on git.

**Comment by kellyhyomin** [comment]
@IveJ 
Thank you for your help.
I solved it with the keycloak setting.

**Comment by mingfang** [comment]
> I solved it with the keycloak setting.
@kellyhyomin Can you please tell me how you fix this?

**Comment by kellyhyomin** [comment]
@mingfang 
1. In the github page
- https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/
- Homepage URL, Application description -> Che IP
- The Redirect URI field, copy the Redirect URI from the Keycloak github identity provider window and paste them.

2. For multi-user Che
- Go to the keycloak page
- Login as admin
- Click Identity Providers.
- In the Add provider drop-down list, click GitHub. The Add identity provider window is displayed.

3. In the Add identity provider window
- The Redirect URI field, depending on your Eclipse Che installation, type the Authorization callback URL. 
- Copy the client ID and the client secret from GitHub and paste them in the Client ID and the Client Secret fields, respectively.
- In the Homepage URL and the Authorization callback URL field, depending on your Eclipse Che installation, type the two URLS.
- In the Default Scopes field, type repo, user, write:publick_key.
- Set Store Tokens and Stored Tokens Readable to ON.
- Click Save.

4. Select Client Roles-> broker → read token on each user's Role Mappings page and add it to Assigned Roles

**Comment by mingfang** [comment]
@kellyhyomin 
Thanks; This is really helpful.
Using your instructions I was able to get further but I'm now seeing this problem.
https://github.com/eclipse/che/issues/3523
It looks like Che needs it's own Github Oauth setup, in addition to the Keycloak Github setup.

**Comment by mingfang** [comment]
As a followup to @kellyhyomin 
1- go to GitHub to create another oauth application. But this time use the Che callback URL instead of the Keycloak callback URL. e.g. https://che.legionx.com/api/oauth/callback

2-set the Client ID and Client Secret in the respective env variables before starting Che
CHE_OAUTH_GITHUB_CLIENTID=<client id>
CHE_OAUTH_GITHUB_CLIENTSECRET=<client secret>

This works.

Can someone confirm that we really need two different Github Oauth apps, one for Keycloak and another for Che?
