### ISSUE TITLE
nexe fails to create `plugin-remote-endpoint` executable with error `Error: spawn python ENOENT`

### ISSUE THREAD

**Issue by abhay1722** [eclipse-che/che#16365]
### Describe the bug
While building the `eclipse/che-theia-endpoint-runtime-binary:7.9.0` image, nexe gives the below issue:-
```
RUN nexe node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote.js -b alpine-s390x-10.16.0 --python $(which python2) -o ${HOME}/plugin-remote-endpoint
 ---> Running in 976eb0749aad
3.3.2
- Starting...
ℹ nexe 3.3.2
- nexe 3.3.2
- Node source extracted to: /home/theia/.nexe/10.16.3
✔ Configuring node build: --dest-cpu=s390x
- Finished in 261.301s
✔ Finished in 261.301s
Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.9.0

### Steps to reproduce
```
git clone https://github.com/eclipse/che-theia.git
cd che-theia
./build.sh --build-args:THEIA_VERSION=${THEIA_VERSION} --tag:"7.9.0" --branch:"master"  --skip-tests
```

### Expected behavior
Build must complete successfully with the following 3 images:-
```
eclipse/che-theia:7.9.0
eclipse/che-theia-dev:7.9.0
eclipse/che-theia-endpoint-runtime-binary:7.9.0
```

**Comment by ibuziuk** [comment]
@artem could you please take a look?

**Comment by benoitf** [comment]
Hello @abhay1722, I think that there some missing context there
It seems you're trying to use a different architecture like `s390x`

**Comment by abhay1722** [comment]
@benoitf Yes, I am trying to build it on `s390x` architecture. The same command works fine on the host, where I am able to produce the `plugin-remote-endpoint` executable. However, while building the docker image, the above issue is observed.
