### ISSUE TITLE
Handle large amount of debug log in workspace loader

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#16368]
### Is your task related to a problem? Please describe.

#15983 introduced ability to restart a workspace with debug mode enabled. In some cases, when amount of logs will be rather large to show by workspace loader, this may cause memory performance issues because of large number of DOM nodes to manipulate. 

### Describe the solution you'd like

Keep in DOM certain amount of latest lines of logs, but allow users to download all logs at once.

**Comment by olexii4** [comment]
Fixed in https://github.com/eclipse/che-workspace-loader/pull/6/files#diff-291b63e7e93f33e96bd0d0184764cb64R78
