### ISSUE TITLE
Git clone with https fails

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#16362]
### Describe the bug
Cloning using a https url from Github fails with the following error
```
Cloning into '/projects/'...
fatal: cannot exec '/default-theia-plugins/vscode-git/extension/out/askpass.sh': Permission denied
fatal: could not read Username for 'https://github.com': No such device or address
```

### Che version

 - [x] latest (7.9.1)
 - [ ] nightly
 - [ ] other: please specify

**Comment by benoitf** [comment]
Seems to duplicate https://github.com/eclipse/che/issues/16084

**Comment by ibuziuk** [comment]
@ericwill should we close it as a duplicate of #16084

**Comment by ericwill** [comment]
Yes it's a duplicate.

**Comment by benoitf** [comment]
I think priority is quite high as well

**Comment by ibuziuk** [comment]
Closing in favor of #16084
