### ISSUE TITLE
Update vulnerable dependencies in workspace loader

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16372]
### Is your task related to a problem? Please describe.
It's needed to update vulnerable dependencies in workspace loader:

The minimal version for new dependencies which must be updated:
```
acorn@^6.4.1:
  version "6.4.1"

serialize-javascript@^2.1.1:
  version "2.1.1"

js-yaml@^3.13.1:
  version "3.13.1"

minimist@^1.2.2:
  version "1.2.2"
```

**Comment by ibuziuk** [comment]
@sleshchenko I put P1 for now, but feel free to change the severity

**Comment by olexii4** [comment]
Fixed in https://github.com/eclipse/che-workspace-loader/commit/a9878b750158f4403e204a4456baa1e973ad7048#diff-8ee2343978836a779dc9f8d6b794c3b2R3743
