### ISSUE TITLE
node debug is broken for che-theia:next

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#16379]
### Describe the bug
The debug session type "node" is not supported.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create new application with node from stack
'NodeJS Express Web Application'
2. Run application with enabled debugger: task with name `run the web app (debugging enabled)`
3. Open debug panel select 'Attach to remote' debug config and click on run button:

### Expected behavior
Debugger should attach to the application using remote debug protocol. **I assume that for che-theia:7.9.1 debugger forks fine, but for che-theia:next it doesn't work.**

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
I added node-debug2 Che Plugin but `node` debug type is still not recognized.
![image](https://user-images.githubusercontent.com/1636395/76902834-7cbee800-68a5-11ea-935a-1cc734d1180b.png)

I'm labeling it as a blocker as the user isn't able to debug node application.

**Comment by tolusha** [comment]
It is needed to have both node and node2 debuggers

**Comment by AndrienkoAleksandr** [comment]
> It is needed to have both node and node2 debuggers

I tried too. It doesn't work.

**Comment by azatsarynnyy** [comment]
@tolusha there's only Node Debug plugin
![image](https://user-images.githubusercontent.com/1636395/76935750-52e3e080-68fa-11ea-8998-bb5047578296.png)

which is actually node-debug2
https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/ms-vscode

**Comment by tolusha** [comment]
@tsmaeder @svor 
That's strange.
Some times ago it was needed to have both node and node2 debug extensions since they work in conjunction. `node` debugger is a legacy debugger and is used for node <= 8.0, but it automatically changes the `type` to `node2` when version is greater then 8.0.

@azatsarynnyy 
As workaround we can try to set `"type": "node2"`

**Comment by tolusha** [comment]
I like it)

https://github.com/eclipse/che-plugin-registry/commit/d0c25951a639d734e8bd91e1e325ded3294fc1f7#diff-5af2a440713580ab0b0c110c4a30c9b0

**Comment by tolusha** [comment]
We have to update [1] to add node-debug extension as well

[1] https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml

/cc @ericwill

**Comment by azatsarynnyy** [comment]
Thanks @tolusha for investigating it.
I'm changing area as plugins and lower the severity to P1 as there's a workaround: one needs to add node-debug2 che plugin and set a debug configuration type `node2`.

**Comment by tolusha** [comment]
I would say there are two options:

1. change debug types to `node2` (it is needed to check)
2. add vsix extension  [1] to [2]

[1] https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug
[2] https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml

**Comment by azatsarynnyy** [comment]
> change debug types to node2 (it is needed to check)

@tolusha I've already checked - it works

**Comment by ericwill** [comment]
This has been fixed with #16728.
