### ISSUE TITLE
Re-creating a project with the same name as a deleted one in same workspace fails on Codenvy

### ISSUE THREAD

**Issue by mathiasconradt** [eclipse-che/che#1637]
Deleting a project in a workspace, deleting the project, then trying to a create a new project with the same name as the previously deleted one fails with the message 

`Error while creating the project - Conflict: Project de.conradt.core already exists`

Seems that the deletion of the project, not everything got really cleaned up in the background.

**Reproduction Steps:**
1. Create a project with name de.conradt.core
2. Delete the project de.conradt.core
3. In the same workspace, create a new project with the same name de.conradt.core again

**Expected behavior:**

The project should be created because it should not exist anymore after the deletion.

**Observed behavior:**

Project creation fails with: 

`Error while creating the project - Conflict: Project de.conradt.core already exists`

Screenshot: https://snag.gy/fO6Xh3.jpg

even though no project exists (as can be seen in the screenshot).

**Additional information:**

Codenvy
Version :4.4.0
Revision :cb26c3591432422c
Build Time :2016-06-29 12:06:31

**Comment by ddementieva** [comment]
I've failed to reproduce this issue. 

Can you reproduce it repeatedly? Have you tried it in an incognito mode? Can you send some short screencast with a problem?

**Comment by ghost** [comment]
@mathiasconradt can you try it with the latest master please?

**Comment by TylerJewell** [comment]
Closing the issue as it's been open for awhile. Feel free to reopen if its reproduced.
