### ISSUE TITLE
[release process] Ensure operator yamls and test defaults are updated for each release

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16371]
### Is your task related to a problem? Please describe.

Recently I noted that several files in che-operator are not updated on each release. See https://github.com/eclipse/che-operator/pull/197

* deploy/operator-local.yaml
* deploy/operator.yaml
* pkg/deploy/defaults_test.go

### Describe the solution you'd like

So, the [make-release.sh](https://github.com/eclipse/che-operator/blob/master/make-release.sh) script for che-operator should be updated to modify these files for every 7.x.0 and 7.x.z release.

**Comment by tolusha** [comment]
@nickboldt 
I am wondering where I can get the latest value for `IMAGE_default_pvc_jobs` ?

**Comment by tolusha** [comment]
Included into https://github.com/eclipse/che-operator/pull/215
