### ISSUE TITLE
Asciidoc export to pdf fails

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#16370]
### Describe the bug
When I invoke the `Asciidoc: Export document to pdf` command it fails 

If I have the settings as`"asciidoc.use_asciidoctorpdf": false` the extension fails with 
```
Error installing wkhtmltopdf, TypeError: Cannot read property 'trim' of undefined
```
When `"asciidoc.use_asciidoctorpdf"`is set to `true` the extension fails with 

```
/bin/sh: asciidoctor-pdf: not found command: asciidoctor-pdf -q - -B "/projects/Documents/AppStak" -o "/projects/Documents/test.pdf" If the asciidoctor-pdf binary is not in your PATH, you can set the full path.Go to File -> Preferences -> User settings and adjust the asciidoc.asciidoctorpdf_command
```

**Comment by ibuziuk** [comment]
@ericwill @JPinkney I put `P2` for now but feel free to update the priority
