### ISSUE TITLE
che tls self signed setup instructions since 7.9.1 ?

### ISSUE THREAD

**Issue by anselmov** [eclipse-che/che#16382]
Hello,

Is there any instructions yet on how to run che on k8s with self signed certificates since 7.9.1 ?

There is a new config map name for certs: 

> cheGitSelfSignedCertConfigMapName: che-git-self-signed-cert

How do I create it?

Thanks.

**Comment by l0rd** [comment]
@anselmov [this documentation section](https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/#deploying-che-with-support-for-git-repositories-with-self-signed-certificates_advanced-configuration-options) should answer your question.

**Comment by l0rd** [comment]
Feel free to reopen the issue if the doc doesn't answer your question.
