### ISSUE TITLE
Loop during 'Loading runtime token' on Hosted Che

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#16384]
While trying to open a workspace I see this.
![2acluster](https://user-images.githubusercontent.com/829239/76881782-f17c2d00-6879-11ea-825a-f9c8c7a94ce7.gif)

Basically the progress bar and label keep appearing/disappearing for a while until it fails with unknown error after about 5 minutes.

Here's a snapshot of the network tab of developer options in Chrome during this looping.
![image](https://user-images.githubusercontent.com/829239/76881904-238d8f00-687a-11ea-851e-97e494f73ec1.png)

User: scela

**Comment by ibuziuk** [comment]
@scela I can not repro, does it happen every now and then for you? could you try incognito?

**Comment by scela** [comment]
I originally tried 'cognito' and I saw that. Tried incognito to see if it's fixed but it wasn't. Just tried now again after 15 mins and I see it again so it's consistent.

**Comment by ibuziuk** [comment]
@ericwill could you please confirm that this very issue is reproducible in the upstream - https://github.com/eclipse/che-theia/pull/669#issuecomment-600190514

**Comment by l0rd** [comment]
@ibuziuk I experience this issue on che.openshift.io since 10 days now on chrome (incognito or not) but not on firefox. I do not experience it on upstream che.

**Comment by ericwill** [comment]
I can reproduce it by clicking the happy path test link in the PR: eclipse/che-theia#669 (comment)

It worked the first time but ever since then it's been reproducing the issue.

**Comment by scela** [comment]
I tried on Firefox, it wasn't flashing but the progress bar scrolled by a couple of times and I see a black screen for the last 3 minutes or so:

![image](https://user-images.githubusercontent.com/829239/76883964-381f5680-687d-11ea-9ff1-cc71fbdb991a.png)

**Comment by ibuziuk** [comment]
Could you add the browser versions.
Works fine for me against Chrome 76.0.3809.100-1

@sleshchenko maybe someone from the controller team could provide some input? looks like loader traps in a loop at some point

**Comment by benoitf** [comment]
works on my side with Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by IveJ** [comment]
Dear SCale,

Plz scrutinize in sth like quantity of running workspace at the
same time(like initiator metric in pics).

**Comment by l0rd** [comment]
> Could you add the browser versions.
> Works fine for me against Chrome 76.0.3809.100-1

Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by azatsarynnyy** [comment]
I can reproduce it with Chrome 80.0.3987.132 with any Workspace.
But it's not reproducible on FireFox 74.

**Comment by tomgeorge** [comment]
Able to reproduce on Version 80.0.3987.149 (Official Build) (64-bit) on Windows.  Will try Fedora tomorrow

**Comment by patrickm-rh** [comment]
CoreOS8 with Chrome Version 79.0.3945.88 (Official Build) (64B-bit) works fine, same results as tom on similar Windows config.

**Comment by sparkoo** [comment]
reproducible with Chrome `Version 80.0.3987.132 (Official Build) (64-bit)`. The console shows this message 
```
A cookie associated with a cross-site resource at https://routeje0c2lod-mvalarh-che.8a09.starter-us-east-2.openshiftapps.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

Works fine on Firefox 74.0

**Comment by sleshchenko** [comment]
@sparkoo thanks for useful input. 
From Chrome 80, a default value for SameSite is Lax. So on jwtproxy side we need to specify None explicitly.

**Comment by skabashnyuk** [comment]
<img width="1680" alt="Знімок екрана 2020-03-18 о 08 49 33" src="https://user-images.githubusercontent.com/1614429/76937627-6fc9e500-68f5-11ea-87c0-ead0c22fc624.png">
work withot problem

**Comment by benoitf** [comment]
I'm unsure if the issue is only related to Chrome as for example it works fine for me using latest Chrome  80.0.3987.149/macOS while it doesn't work for others.

I've also tested  with incognito and it's still working.

I'm on cluster `starter-us-east-2.openshift.com`

**Comment by sparkoo** [comment]
looks like Chrome `80.0.3987.132` on Linux...

**Comment by sleshchenko** [comment]
> I'm unsure if the issue is only related to Chrome as for example it works fine for me using latest Chrome 80.0.3987.149/macOS while it doesn't work for others.

BTW Including `SameSite` explicitly and not relying on browser default seems to be good thing to do.

**Comment by scela** [comment]
Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by sleshchenko** [comment]
Can't reproduce on upstream deployed on https://che-sleshche.apps.ocp44.codereadyqe.com/dashboard/

Probably it's caused by fact that Che and workspace live on the same domain:  `apps.ocp44.codereadyqe.com` and in case of OSIO they're different.

@ibuziuk Are you able to test my custom JTWProxy image `sleshchenko/che-jwtproxy:samesite` built from https://github.com/sleshchenko/che-jwtproxy/commit/85e19d12a8f5fd6ada637b6bf0fc210acdeb7ea8
Maybe on prod preview... The env var to set jwtproxy for Che Server: `CHE_SERVER_SECURE__EXPOSER_JWTPROXY_IMAGE`
In case you have edit access to your `-che` namespace it would be really easy just to edit already deployed workspace, do you have it?

**Comment by ibuziuk** [comment]
@sleshchenko yeah, the thing is that I still can reproduce this issue neither on prod nor on prod-preview and it is not clear against which version of the browser the issue is reproducible 100%.

**Comment by skabashnyuk** [comment]
@mshaposhnik was able to reproduce after enabling experimental  flags
<img width="1249" alt="Знімок екрана 2020-03-18 о 11 40 20" src="https://user-images.githubusercontent.com/1614429/76952389-50d74d00-690d-11ea-9151-4cf4e3aa5b5b.png">

See https://digiday.com/media/what-is-chrome-samesite/

**Comment by ibuziuk** [comment]
@scela @l0rd @Katka92  the fix has been promoted to production. Could you please verify?
As I understand upstream / CRW are not affected, so not sure if we need to include the jwt-proxy fixup to the 7.9.x cc: @nickboldt

**Comment by sleshchenko** [comment]
> As I understand upstream / CRW are not affected, so not sure if we need to include the jwt-proxy fixup to the 7.9.x cc: @nickboldt

It's not needed in case Server and Workspaces share the same domain, but if there is a chance that someone needs different one - like OSIO case, it makes sense to consider and include it.

**Comment by ibuziuk** [comment]
> but if there is a chance that someone needs different one - like OSIO case, it makes sense to consider and include it.

AFAIK, this config is not possible for upstream / CRW case

**Comment by Katka92** [comment]
@ibuziuk I can't reproduce it on production. :)

**Comment by l0rd** [comment]
@ibuziuk problem fixed for me as well.

**Comment by scela** [comment]
I can not reproduce the issue anymore.

**Comment by ibuziuk** [comment]
thanks, so we just need to decide if backport to 7.9.x is needed and close the issue afterward

**Comment by ibuziuk** [comment]
@nickboldt @l0rd closing this issue since looks there is no need to backport the change to 7.9.x (CRW does not support the use-case when che-server and workspaces are located on different clusters)

**Comment by olberger** [comment]
FWIW, this still happens for che.openshift.io. The web console displays : 
Request to access cookie or storage on “https://routekvgs5da4-obergix-che.b542.starter-us-east-2a.openshiftapps.com/?uid=757302” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

Request to access cookie or storage on “https://routekvgs5da4-obergix-che.b542.starter-us-east-2a.openshiftapps.com/jwt/auth” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

Firefox 75.0 (64-bit) on Linux
