### ISSUE TITLE
Che is using a wrong external URL in the preview tab when detecting a exposed port of a webapp

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16381]
### Describe the bug
Che is displaying a wrong external URL in the preview tab when detecting a exposed port: when starting an web application within the workspace and using a declared port in the devfile, Che is using to the wrong URL in the preview tab: internal URL instead of than the external URL.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
- Start a workspace from this devfile: ~https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app/blob/master/devfile.yaml~
  - the devfile in master was "fixed" (https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app/commit/3ff1d7e771963e1b8d0df35328402c9843e00d19) this is the old one that should reproduce the issue https://raw.githubusercontent.com/redhat-developer-demos/quarkus-reactjs-postit-app/e5237c1dfaa24af5ba0a6c68990675c3c8de5db1/devfile.yaml
- Start the task `Start DEVMODE quarkus-backend`
- A popup is showing up `A process is now listening on port 8080. External URL is ...`

### Expected behavior
We expect to have the external URL, but we have the internal URL

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift 4.3 with Che operator
   - [x] minikube v1.4.0

### Screenshots
![Eclipse Che | postit-app-zcqb5 - Google Chrome_680](https://user-images.githubusercontent.com/650571/76866468-7b210000-6864-11ea-9c3b-fa824046307c.png)

![Eclipse Che | postit-app-zcqb5 - Google Chrome_681](https://user-images.githubusercontent.com/650571/76866493-807e4a80-6864-11ea-9905-d5a2eea1812c.png)

### Installation method
   - [x] chectl 
   - [x] che-operator 

### Additional context
Notice that in `My workspace view` we have 2 exposed URL icons: `quarkus/dev` and `quarkus-dev`.
- `quarkus-dev` redirects to the external URL.
- `quarkus/dev` redirects to the internal URL.

It maybe a bug when handling the `/` character in the endpoint name.

```yaml
  - alias: quarkus-backend-dev
    type: dockerimage
    [...]
    endpoints:
      - name: 'quarkus/dev'
        port: 8080
```

**Comment by sunix** [comment]
discussion during the community call:

> - Angel: may be related to jwt-proxy internal/localhost only listening
> - David/Nick: affecting CRW as well - see CRW-717
> - Related concern: we need a 7.9.x branch or 7.9.2 tag in  https://github.com/eclipse/che-jwtproxy/ to avoid accidental 7.10/7.11 leakage into CRW 2.1

**Comment by l0rd** [comment]
Setting `severity/P2` as it only affect endpoints that include a slash (`/`) in their name.

As a side note @sunix why don't you specify `internal` and `external` in your devfile endpoints names (i.e. `quarkus-dev/internal` vs `quarkus-dev/external`)? This would make it easier to understand the difference among the endpoints.

**Comment by sunix** [comment]
@l0rd this quite critical for users who won't notice there is a problem because of the endpoint name.

**Comment by sunix** [comment]
@l0rd there are too many examples there and there using `/` in endpoint names And many users are taking these devfiles as a starting example to write their own. Users would just face the bug without knowing how to fix it. This is very bad UX.

Randomly search result: 
- https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/go/devfile.yaml#L39
- https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-mysql/devfile.yaml#L33
- https://github.com/redhat-developer/devfile/blob/master/getting-started/vertx/devfile.yaml#L33
- https://github.com/redhat-developer/devfile/blob/master/getting-started/java-maven/devfile.yaml#L39

**Comment by sunix** [comment]
> As a side note @sunix why don't you specify internal and external in your devfile endpoints names (i.e. quarkus-dev/internal vs quarkus-dev/external)? This would make it easier to understand the difference among the endpoints.

@l0rd I don't understand. All my endpoints are supposed to be external. (I don't have the expose the internal ones ... as it is in the same pod)

**Comment by sunix** [comment]
@l0rd I change to `severity/P1`, let me know if it works for you.

**Comment by l0rd** [comment]
@sunix ok

**Comment by sparkoo** [comment]
here's the workspace config wsmaster is sending to the client https://gist.github.com/sparkoo/9ed9e4bc62c740aa7d8a65ac9d8b072e

IMO wrong part is that it's trying to make dns valid server name (https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ExternalServerExposer.java#L86) and as a result, it's sending it as both valid and invalid servers, which is wrong
```
"quarkus-backend-dev": {
          "attributes": {
            "component": "quarkus-backend-dev",
            "memoryRequestBytes": "209715200",
            "memoryLimitBytes": "5368709120",
            "source": "recipe",
            "cpuLimitCores": "2.0",
            "cpuRequestCores": "0.125"
          },
          "servers": {
            "quarkus/dev": {
              "url": "http://serverzea4x9wb-quarkus-backend-dev:8080",
              "attributes": {
                "serverName": "quarkus/dev",
                "port": "8080"
              },
              "status": "UNKNOWN"
            },
            "quarkus-dev": {
              "url": "https://route8u7v4ddq-che-che.apps-crc.testing",
              "attributes": {
                "serverName": "quarkus/dev",
                "port": "8080"
              },
              "status": "UNKNOWN"
            }
          },
          "status": "RUNNING"
        },
```
