### ISSUE TITLE
How to install and Run Mongodb 

### ISSUE THREAD

**Issue by lopster568** [eclipse-che/che#16385]
Hi, 
I'm a beginner and I'm trying to install and run mongodb on Eclipse Che. I'm using express and nodejs.
I've tried several methods but they are not working.
The course that I'm following used ./monogod command to run the mongodb but I can't seem to do the same.
I tried https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/
this manual but I cannot create /etc/yum.repos.d/mongodb-org-4.2.repo  as it returns an error that access is denied.
Please Help!!!

**Comment by tolusha** [comment]
@Aarav568 
It is needed to create a container with mongodb.
Have a look at our samples: nodejs + mongo [1], java + mongo [2]

[1] https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs-mongo
[2] https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/java-mongo

**Comment by Aarav568** [comment]
> @Aarav568
> It is needed to create a container with mongodb.
> Have a look at our samples: nodejs + mongo [1], java + mongo [2]
> 
> [1] https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs-mongo
> [2] https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/java-mongo

Sorry, I didn't get it. I'm using nodejs. I've never worked with containers.

**Comment by tolusha** [comment]
I guess there is misunderstanding somewhere
Could you elaborate more on
>  I'm trying to install and run mongodb on Eclipse Che

What do you mean?

**Comment by Aarav568** [comment]
> What do you mean?
I just want to run a mongodb server and create a database.
I'm following a course in which the mongo server is installed on Cloud9.io but sadly, it no longer works so I'm using Eclipse Che and I cannot run Mongo server by using the same method.

I want a running server, that looks something like this:
https://www.dropbox.com/s/ikruef1dfcznazf/git.png?dl=0

**Comment by tolusha** [comment]
Where did you Eclipse Che?
Have you installed it locally? 
https://www.eclipse.org/che/docs/che-7/running-che-locally/

**Comment by Aarav568** [comment]
No. It's online. https://che.openshift.io/dashboard/

**Comment by tolusha** [comment]
https://che.openshift.io/dashboard/#/getstarted
And create a sample with mongo.

It is basically all about devfiles https://redhat-developer.github.io/devfile/
I would like to recommend read this first to understand to conception

**Comment by soyjne** [comment]
Hi @Aarav568  

Could you connect your https://che.openshift.io/dashboard/ to MongoDB? I tried with the devfile guide but I couldn't. I think we are taking the same course online, cause in mine's the profesor uses C9 too!

Thanks!
