### ISSUE TITLE
Set up happy path test to be run on workspace-loader PRs

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16395]
### Is your task related to a problem? Please describe.
Workspace loader is moved to a separate repo where there is no happy path test as PR check, for example https://github.com/eclipse/che-workspace-loader/pull/4.

But Happy Path scenario includes using it, chectl provide link that will open Dashboard with workspace loader as iframe...
P.S. From time to time workspace-loader PR depends on changes in Che repo, like again
https://github.com/eclipse/che-workspace-loader/pull/4 depends on https://github.com/eclipse/che/pull/16327
So, as we had previously with CI tests, it makes sense to make happy path make build not master branch in different repositories, like if there are the branches with the same name, like run Che Server and workspace loader have `CHE-16050` branches and happy path test could build 
workspace loader#CHE-16050
Che#CHE-16050 <- depending on the build result of workspace loader
Let me know if it's not clearly described.

P.S. I also use Che image built by happy path tests job to do manual testing. So, it's one more +1 to set up happy path test for repo even if not much component functionality is covered.

**Comment by dmytro-ndp** [comment]
@sleshchenko: thank you for an idea!
Which command should we use to build workspace-loader artifact?

**Comment by dmytro-ndp** [comment]
@davidfestal, @tolusha: installation of Multiuse User Eclipse Che 7.9.2.RC on minikube 1.1.1 using chectl:next and che-operator:nightly [had failed](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1374/console).

Could you, please, say which version of **chectl** and **che-operator** we should use to check installation of Eclipse Che 7.9.2.RC?

**Comment by sleshchenko** [comment]
@dmytro-ndp I believe similar to Che Server, something like `mvn clean install -Pnative`

**Comment by dmytro-ndp** [comment]
@sleshchenko: thank you!

**Comment by rhopp** [comment]
Isn't workspace-loader bundled together with che-server&dashboard in one image? For this to work we need to have mechanism how to create the whole image to test.
Can your team help with this? Or can you at least point us to the place, where this assembly is happening (for example for nightly builds?)

**Comment by dmytro-ndp** [comment]
@rhopp: we can reuse [existed Eclipse Che Happy path tests PR check pipeline](https://github.com/eclipse/che/blob/master/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile) with simple modification for this propose:
1) build workspace loader artifact on slave
2) build eclipse che from master or from issue branch on the same slave 
3) push che-server to maxura repo
4) ...

**Comment by rhopp** [comment]
Please... No `maxura` repo. I don't get how come we didn't move from there yet :-D

@sleshchenko Can't we just create new dockerfile, which would use nightly che-server image and just replace the artifact in tomcat deployment folder? I would like to avoid building whole che again...

**Comment by dmytro-ndp** [comment]
@rhopp: well - if it will be done on ci.centos - we will be able to push che-server image to `quay.io/eclipse/che-server:${pr_id}`
Anyway, we require to push patched che-server image somewhere for the sake of installation.
And one of requested cases doesn't allow to you `che-server:nightly`:
>  as we had previously with CI tests, it makes sense to make happy path make build not master branch in different repositories, like if there are the branches with the same name, like run Che Server and workspace loader have CHE-16050 branches and happy path test could build
workspace loader#CHE-16050
Che#CHE-16050 <- depending on the build result of workspace loader

**Comment by dmytro-ndp** [comment]
@rhopp: if you don't like maxura repo, let's move of Happy path Eclipse Che PR check from CRW CCI to ci.centos ASAP.

**Comment by dmytro-ndp** [comment]
@mkuznyetsov, @nickboldt, @davidfestal: 
We have managed to run E2E tests against Eclipse Che 7.9.2.RC:
- quay.io/eclipse/che-server:rc
- quay.io/eclipse/che-keycloak:rc
- quay.io/eclipse/che-theia:7.9.2
- quay.io/eclipse/che-theia-endpoint-runtime-binary:7.9.2
- quay.io/eclipse/che-devfile-registry:7.9.2
- quay.io/eclipse/che-plugin-registry:7.9.2
- quay.io/eclipse/che-plugin-artifacts-broker:v3.1.1
- [chectl:7.9.1](https://github.com/che-incubator/chectl/releases/tag/20200309102927)
- quay.io/dfestal/che-operator:fix-devfile-registry-public-url ([it should have required changes](https://github.com/eclipse/che/issues/16229#issuecomment-601212850))
- centos/postgresql-96-centos7:9.6

Current result against Multiuser Eclipse Che 7.9.2.RC without TLS support:
1. Java selenium tests passed on minishift 3.11 https://ci.centos.org/view/Devtools/job/devtools-che-rc-multiuser-integration-tests/27/
2. OS OAuth integration tests passed on minishift 3.11 https://ci.centos.org/view/Devtools/job/devtools-che-rc-ocp-oauth-test/28/
3. Rolling update tests passed on minishift 3.11 https://ci.centos.org/view/Devtools/job/devtools-che-rc-rolling-strategy-test/28/

Also, @dfestal reported that he had successfully tested fixes related to che-operator:7.9.x on a disconnected OS 4.3 cluster, installed with the restricted environment procedure, with proxies + TLS + selfsigned certificates enabled. Result was a successfully started Java Gradle workspace, with working basic services like terminal, JDTLS, outlines, and commands.

Next tests are in-progress:
1. Happy path tests, Vert.x, Java Maven and Python devfile tests passed on minikube 1.1.1
2. GitHub integration tests.
3. Testing of Eclipse Che with TLS support.

**Comment by sleshchenko** [comment]
> @sleshchenko Can't we just create new dockerfile, which would use nightly che-server image and just replace the artifact in tomcat deployment folder? I would like to avoid building whole che again...

I believe we can't. At least in 100% cases. As I described in the issue description, there can be a cases when workspace-loader, dashboard and che repos could have depending PRs...
But in case depending PR is not found - we rebuild in Che repo only that modules which update workspace-loader, like `mvn clean install -pl assembly-main`...
