### ISSUE TITLE
Why the exposed port range is 32768-65535, which is not the same as the range in che.properties?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#164]
In the [Dockerfile](https://github.com/codenvy/che/blob/8a3faf7baaffbbf4044137676bfe4af884b71f56/Dockerfile#L24):

```
# expose 8080 port and a range of ports for runners

EXPOSE 8080 32768-65535
```

But in [/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties`](https://github.com/codenvy/che/blob/8a3faf7baaffbbf4044137676bfe4af884b71f56/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L14-L16)

```
# range of available service ports
sys.resources.min_port=49152
sys.resources.max_port=65535
```

I wonder why the start port is different? And what's usage of the ports between `32768` and `49152`?

**Comment by TylerJewell** [comment]
We narrow the range of what is exposed so that docker will start in a reasonable time.  There is significant overhead for each expert port exposed.

**Comment by freewind** [comment]
Is the `32768-65535` in Dockerfile still right? Shall we make the two ranges the same?

**Comment by freewind** [comment]
I'm not sure when I start docker image, which range of port shall I use. e.g.
1. `docker run -it --privileged -e DOCKER_MACHINE_HOST=159.203.201.197 -p 8080:8080 -p 49152-49752:49152-49752 codenvy/che:4.0.0-beta-5`
2. `docker run -it --privileged -e DOCKER_MACHINE_HOST=159.203.201.197 -p 8080:8080 -p 32768-32788:32768-32788 codenvy/che:4.0.0-beta-5`

Shall I start with `49152` or `32768`? Or either one is OK?

**Comment by TylerJewell** [comment]
No the internal structure is correct.  The better answer is to use the --net option.  We need to do more testing on that option and its performance before we make that the primary configuration.

**Comment by TylerJewell** [comment]
Start with the 32768 but both should be ok.

**Comment by freewind** [comment]
@TylerJewell Not quite understand why it's `32768`, since it's only exposed in Dockerfile. Does the che program running inside the container have a way to know it? I thought it should get the `sys.resources.min_port` from `che.properties` and use `49152`

**Comment by TylerJewell** [comment]
@eivantsov?

**Comment by TylerJewell** [comment]
This should explain it.
https://eclipse-che.readme.io/v4.0/docs/usage-docker#ports

**Comment by ghost** [comment]
# range of available service ports

sys.resources.min_port=49152
sys.resources.max_port=65535 

deprecated. we'll remove it from conf
