### ISSUE TITLE
microk8s just broke chectl -p microk8s

### ISSUE THREAD

**Issue by TheRealChssAddct** [eclipse-che/che#16408]
Microk8s team decided to 'pretty up' the output of microk8s.status. It released today (2020-03-19) on the latest/edge channel with v1.17.4 rev: 1278.

The PR is here: [here](https://github.com/ubuntu/microk8s/pull/876)

Their changes break the ingress and storage enabled checks in chectl/src/tasks/platforms/microk8s.ts lines 112 and 113.
```
      ingress: stdout.includes('ingress: enabled'),
      storage: stdout.includes('storage: enabled')
```

With their change it is less simple to get the array of enabled addons. There is the option to get yaml output which is still parsable, but less simply than currently done in the code above.  e.g.: 
`microk8s status -o yaml`

They also added a --addon tag, for querying the status of an individual addon and returns either "enabled" or "disabled". e.g.:
`microk8s.status --addon ingress`
`microk8s.status --addon storage`

For now, I can switch to another channel such as latest/stable, latest/candidate, or latest/beta.  But this breaking change is coming fast. (latest/stable is dated 1020-03-09).

I submit a bug to microk8s [https://github.com/ubuntu/microk8s/issues/1041](https://github.com/ubuntu/microk8s/issues/1041) complaining and suggesting they keep the old format as default and provide the new format with a new switch such as `--pretty` or `-o pretty`  But no guarantees they would accomodate.

**Comment by gattytto** [comment]
it's: 
/usr/local/lib/chectl/templates/che-operator/crds/org_v1_che_cr.yaml

tlsSupport comes on by default with selfSignedCerts: false as default, error prone.

To fix change tlsSupport to false

**Comment by tolusha** [comment]
@TheRealChssAddct 
Thank you for reporting

**Comment by ktsakalozos** [comment]
@tolusha @TheRealChssAddct we have taken corrective action in MicroK8s in order not to change the CLI and output format. The PR with the fix is merged and the edge channel should be updated within a few hours. Thank you for reporting this, apologies for any inconvenience.

**Comment by TheRealChssAddct** [comment]
Problem resolved by microk8s team.

**Comment by tolusha** [comment]
@ktsakalozos Cool, thank you!

**Comment by TheRealChssAddct** [comment]
Reopening, because the microk8s team has decided (https://github.com/ubuntu/microk8s/issues/1041#issuecomment-678251907) to have the default of microk8s.status be 'pretty'.  This is a breaking change for chectl.  It is unfortunate that it will in fact break everyone who is using an older version of chectl as well.  Anyone who uses older versions of chectl from before this is fixed, will have to manually be an a previous version of microk8s (or use something other than microk8s which chectl supports, such as minikube, etc.)

**Comment by tolusha** [comment]
@TheRealChssAddct 
Thank you for reporting. 
Do you think you can submit a PR ?
