### ISSUE TITLE
E2E Happy path tests failed because unexpected alert opened during Java LS initialization

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16403]
### Describe the bug
E2E Happy path tests failed being run against Single User Eclipse Che with TLS support on minikube 1.1.1 because unexpected alert with unknown text opened during Java LS initialization: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1055/console
```
         ▼ Editor.waitTabFocused "PetClinicApplication.java"
          ▼ Ide.checkLsInitializationStart
          ▼ Ide.waitStatusBarContains "Activating Language Support for Java"
Known flakiness has occurred https://github.com/eclipse/che/issues/14944
          ▼ DriverHelper.reloadPage
          ▼ Ide.waitStatusBarContains "Activating Language Support for Java"
    1) Java LS initialization


  3 passing (2m)
  1 failing

  1) Language server validation
       Java LS initialization:
     UnexpectedAlertOpenError: unexpected alert open: {Alert text : }
```

Workspace devfile: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-676/happy-path-workspace.yaml

The alert appeared after refresh browser workaround to issue https://github.com/eclipse/che/issues/14944 had been applied.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Java_LS_initialization (1)](https://user-images.githubusercontent.com/1197777/77090901-7d27c200-6a10-11ea-8388-0ffbfb030fa3.png)

### Screencast
https://youtu.be/Is1KEz8nO5s

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by Katka92** [comment]
It seems that due to workaround, the test is trying to refresh the page. At this moment, pop-up shows up asking for confirmation to leave the page. That should be fixed by setting preferences before the test run - which seems to be broken.

**Comment by dmytro-ndp** [comment]
The issue has affected Eclipse Che E2E nightly tests https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/nightly/job/MultiUser-Che-nightly-check-e2e-tests-against-k8s/179/

**Comment by dmytro-ndp** [comment]
Not a blocker after https://github.com/eclipse/che/issues/14944 has been fixed.

**Comment by rhopp** [comment]
Resolved by setting preference to `AskForConfirmationType.never`.
