### ISSUE TITLE
Question about google super dev.

### ISSUE THREAD

**Issue by wn092943** [eclipse-che/che#1640]
I run che by using google super dev model.When clicking `dev model on`, I get a tip that can't find any GWT model.

**Reproduction Steps:**

1.run che in Eclipse by using google super dev model.
2.start che sever and visit `localhost:8080`
3.click `dev model on`

**Observed behavior:**

![4](https://cloud.githubusercontent.com/assets/19187922/16557024/eefc3942-420f-11e6-8623-daee493eb794.PNG)

**Che version:**    4.3.4
**OS and version:** win7
**Eclipse version:**    Mars

**Additional information:**
1. Firstly, I only try to run che without any other plugins.
2. Then I try to run che which adding my plugin, like 
   ![5](https://cloud.githubusercontent.com/assets/19187922/16557481/ae5383c0-4212-11e6-8338-9e4bd2cb3e1a.PNG)

I get the same result.

**Comment by ghost** [comment]
@wn092943 IDE is loaded in an iframe. You need a direct link which is `localhost:8080/che/$workspaceName`

**Comment by wn092943** [comment]
@eivantsov -- I visit `localhost:8080/che/test` that `test` is the name of my workspace, then I get this info
![7](https://cloud.githubusercontent.com/assets/19187922/16571697/6cfbe9ae-4293-11e6-8d27-75f1d86c9fe0.PNG)
I visit `localhost:8080/dashboard/#/ide/test` and click `dev mode on`, I am told that can't find any GWT Modules.
![6](https://cloud.githubusercontent.com/assets/19187922/16571710/b604ce68-4293-11e6-8807-e67cf072bfa0.PNG)

**Comment by ghost** [comment]
It must be different in 4.3 version. Try `localhost:8080/ide/test`

**Comment by wn092943** [comment]
@eivantsov -- Thanks. It works successfully. 
Now I have other question.I add arguments `-src {my-plugin-path}/src/main/java` to run che, but IDE page doesn't show my elements. What steps I missed? Whether I should add the dependency in `assemble-ide-war/pom.xml`? Whether I modify `IDE.gwt.xml`?

PS: I assure that my plugin is correct. I rebuild che with my plugin and run the new assemble, IDE page shows my elements.
![7 1](https://cloud.githubusercontent.com/assets/19187922/16576627/06654872-42c3-11e6-9396-2e4979177483.PNG)

**Comment by TylerJewell** [comment]
@wn092943 - going through old support tickets. Did your questions get resolved?  I'm going to close this for now, but we can continue the thread if you have specific follow on questions.
