### ISSUE TITLE
Importing devfile with private repo fails

### ISSUE THREAD

**Issue by triceam** [eclipse-che/che#16401]
### Description
Attempting to import a defile that contains a reference to a private git repo (that has not been previously configured with an access token) ends up in a bad state, leaving the user with an empty workspace, and no clear way to edit the project that the user intended. 

For example, here I am importing a devfile using the url query paramter, and that defile has a project reference that uses a private git repo:
`https://che.openshift.io/f?url=https://pastebin.com/raw/HQgeDZTU` 

_You can see the defile contents directly here: https://pastebin.com/raw/HQgeDZTU_

When that defvile is imported, I can see the workspace being setup like so:

![image](https://user-images.githubusercontent.com/974294/77077045-0fa57280-69cb-11ea-8291-2cf48f6f8eba.png)

However, when the workspace is created, I end up in this state: 

![image](https://user-images.githubusercontent.com/974294/77077076-1b913480-69cb-11ea-9770-c7485504a972.png)

Notice that there is no project/repo that was imported, and there's an error message:

> Couldn't clone https://us-south.git.cloud.ibm.com/amtrice/Andy-OpenShift-Test-App: Cloning into '/projects/Andy-OpenShift-Test-App'... fatal: could not read Username for 'https://us-south.git.cloud.ibm.com': No such device or address 

If you go to the "git" panel, you'll just see that no repo is configured, thus there is no path to authenticate the repo and finish importing the source code:

![image](https://user-images.githubusercontent.com/974294/77077207-4c716980-69cb-11ea-9015-c5997b3623be.png)

There should be a workflow that requests credentials for repos that require authentication, so that the user is not left in a bad/invalid state.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other:`Che-Theia@64f044b using Theia@1eaecd5c` running on openshift.io

### Expected behavior
There should be a workflow that requests credentials for repos that require authentication, so that the user is not left in a bad/invalid state.

**Comment by triceam** [comment]
From a previous Slack conversation with @l0rd, these may be related, but will require validation:

> This issue may be related https://github.com/eclipse/che/issues/16084
> We have a PR to address that issue that we will merge this week https://github.com/che-incubator/vscode-git/pull/3

**Comment by l0rd** [comment]
cc @benoitf

**Comment by svor** [comment]
@triceam I can't reproduce this problem by using the factory which you provided, could you please confirm that it works for you.

**Comment by triceam** [comment]
@svor I'm still seeing it with this url:
`https://che.openshift.io/f?url=https://pastebin.com/raw/HQgeDZTU`

I had left that repo public for some tests, and you don't see the error if the repo is public.  However, I switched it back to being private, and can now reliably and consistently recreate it.
