### ISSUE TITLE
[chectl] Add `server:login` command 

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16415]
### Is your task related to a problem? Please describe.
In multi-user installation every chectl commands require access-token.
It is better to get it once, store it and use.

### Describe the solution you'd like
Add `server:login` command to login into Eclipse Che, retrieve token as store it.

**Comment by sleshchenko** [comment]
Also, please consider the ability to have different contexts, like kubectl, oc have.
For example, 
```bash
> chectl server:start --platform=kubernetes --installer=helm --multiuser -n che-helm
...
Started and accessible https://che-helm...
> chectl context
K8s                                                           Che                              User
192.168.0.101(minikube)#che-helm         https://che-helm...        -
> chectl server:stop
https://che-helm... is suspended # Note the namespace is got from context
> oc login https://my-openshift.com
> chectl server:start --platform=openshift --installer=operator --multiuser
...
Started and accessible https://che-che...
> chectl login -u admin -p admin
> chectl context
K8s                                                           Che                              User
192.168.0.101(minikube)#che-helm         https://che-helm...        -
* my-openshift.com#che                           https://che-che...          Admin
```

**Comment by tolusha** [comment]
@sleshchenko 
the only problem is that a token does not live long

**Comment by sleshchenko** [comment]
you're are talking about accessToken, right? Don't refresh token has longer lifetime?

BTW asking a user to type username and password is better than fails with requiring set environment variable with token and retry.
