### ISSUE TITLE
Che on microk8s: Failed to load devfiles meta list.

### ISSUE THREAD

**Issue by mgiammarco** [eclipse-che/che#16410]
Hello,
I have just installed Eclipse Che on microk8s.
Installation finished without errors.
Web interface works.
But when I go in "get started" I get an error "failed to load devfiles meta list" and I then have no templates and I cannot proceed.
I have entered in pod shell and checked internet connection: all is good.
What can I do now?
Thanks,
Mario

**Comment by tolusha** [comment]
@mgiammarco 
How did you install Eclipse Che? Do you have any logs?

**Comment by mgiammarco** [comment]
Hello,
I gave the standard command:

chectl server:start --platform=microk8s --installer=helm

I have seen output on console. I have read it it was ok. No file log.

**Comment by gnoejuan** [comment]
I also encountered this while trying to install on my laptop. **After** receiving help here :https://github.com/eclipse/che/issues/16048

**Comment by twolastnames** [comment]
I have the same problem.

Also, if I try to start a container I've made custom, I get the errors:
Failed to load editors.
Failed to load plugins.

Is there a container serving the user HTML that's not getting data from behind it?  I'm not trying to hijack this issue, but I may have gotten further in it into it.

**Comment by tolusha** [comment]
That would be nice if someone provide PR

**Comment by sleshchenko** [comment]
@mgiammarco Are you able to check why plugin/devfile registry is not accessible from your browser... Three options to do it:
1. `kubectl get ingress -n che`, find needed URL and check what is actual error in browser.
2. `kubectl get configmap che -n che | grep URL`, find plugin or devfile registry URL and try to open it in browser.
3. Open Developers tools in chrome, refresh Che dashboard, click export HAR, attach it here and let us take a deeper look (before sending it - make sure that all data are not supposed to be private, like your Che URL, I don't know)

**Comment by mgiammarco** [comment]
Ok I have tried reinstalling che using -a operator and not -a helm (btw: how many installers can I try?)
But now with "operator" installer installation fails on last step.
In the pod called "che-xxxxxxxxxxxxxxxxxxxxxx" I see in logs this error:
aused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching keycloak-che.10.1.10.12.nip.io

I had no possibility to add a valid certificate, I do not understand why the java framework check certificate validity to start, can I disable it?

**Comment by twolastnames** [comment]
```
al@cougar:/usr/local/bin$ kubectl get ingress -n che
NAME               HOSTS                                        ADDRESS          PORTS     AGE
che-ingress        che-che.192.168.99.100.nip.io                192.168.99.100   80, 443   45h
devfile-registry   devfile-registry-che.192.168.99.100.nip.io   192.168.99.100   80, 443   45h
plugin-registry    plugin-registry-che.192.168.99.100.nip.io    192.168.99.100   80, 443   45h
al@cougar:/usr/local/bin$ kubectl get configmap che -n che | grep URL
al@cougar:/usr/local/bin$ kubectl get configmap che -n che 
NAME   DATA   AGE
che    58     46h
al@cougar:/usr/local/bin$ 
```

I also noticed, I'm on minikube, not microk8s

HAR...
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2020-03-23T13:46:12.243Z",
        "id": "page_2",
        "title": "https://che-che.192.168.99.100.nip.io/dashboard/",
        "pageTimings": {
          "onContentLoad": 2947.175999986939,
          "onLoad": 3162.1349999913946
        }
      }
    ],
    "entries": [
      {
        "startedDateTime": "2020-03-23T13:46:28.280Z",
        "time": 10.707000008551404,
        "request": {
          "method": "GET",
          "url": "https://che-che.192.168.99.100.nip.io/api/workspace/settings",
          "httpVersion": "http/2.0",
          "headers": [
            {
              "name": ":method",
              "value": "GET"
            },
            {
              "name": ":authority",
              "value": "che-che.192.168.99.100.nip.io"
            },
            {
              "name": ":scheme",
              "value": "https"
            },
            {
              "name": ":path",
              "value": "/api/workspace/settings"
            },
            {
              "name": "accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "sec-fetch-dest",
              "value": "empty"
            },
            {
              "name": "user-agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
            },
            {
              "name": "sec-fetch-site",
              "value": "same-origin"
            },
            {
              "name": "sec-fetch-mode",
              "value": "cors"
            },
            {
              "name": "referer",
              "value": "https://che-che.192.168.99.100.nip.io/dashboard/"
            },
            {
              "name": "accept-encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "accept-language",
              "value": "en-US,en;q=0.9"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "",
          "httpVersion": "http/2.0",
          "headers": [
            {
              "name": "status",
              "value": "200"
            },
            {
              "name": "server",
              "value": "openresty/1.15.8.2"
            },
            {
              "name": "date",
              "value": "Mon, 23 Mar 2020 13:46:28 GMT"
            },
            {
              "name": "content-type",
              "value": "application/json"
            },
            {
              "name": "cache-control",
              "value": "public, no-cache, no-store, no-transform"
            },
            {
              "name": "vary",
              "value": "accept-encoding"
            },
            {
              "name": "content-encoding",
              "value": "gzip"
            }
          ],
          "cookies": [],
          "content": {
            "size": 306,
            "mimeType": "application/json",
            "text": "{\"supportedRecipeTypes\":\"kubernetes,no-environment\",\"che.workspace.auto_start\":\"true\",\"cheWorkspacePluginRegistryUrl\":\"https://plugin-registry-che.192.168.99.100.nip.io/v3\",\"cheWorkspaceDevfileRegistryUrl\":\"https://devfile-registry-che.192.168.99.100.nip.io\",\"che.workspace.persist_volumes.default\":\"true\"}"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 366
        },
        "cache": {},
        "timings": {
          "blocked": 2.955000014828518,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0.259,
          "wait": 5.936000012319535,
          "receive": 1.5569999814033508,
          "_blocked_queueing": 2.322000014828518
        },
        "serverIPAddress": "192.168.99.100",
        "_initiator": {
          "type": "script",
          "stack": {
            "callFrames": [
              {
                "functionName": "",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 28008
              },
              {
                "functionName": "w",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 25482
              },
              {
                "functionName": "l",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 23154
              },
              {
                "functionName": "c",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 10243
              },
              {
                "functionName": "",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 10689
              },
              {
                "functionName": "$digest",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 16548
              },
              {
                "functionName": "",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 3021
              },
              {
                "functionName": "",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2390,
                "columnNumber": 25432
              },
              {
                "functionName": "o",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2390,
                "columnNumber": 1198
              },
              {
                "functionName": "c",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2390,
                "columnNumber": 25416
              },
              {
                "functionName": "a",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2390,
                "columnNumber": 25295
              },
              {
                "functionName": "dispatch",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 266,
                "columnNumber": 2939
              },
              {
                "functionName": "g.handle",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 266,
                "columnNumber": 938
              }
            ]
          }
        },
        "_priority": "High",
        "_resourceType": "xhr",
        "connection": "914",
        "pageref": "page_2"
      },
      {
        "startedDateTime": "2020-03-23T13:46:28.478Z",
        "time": 0.5880339999857824,
        "request": {
          "method": "GET",
          "url": "https://devfile-registry-che.192.168.99.100.nip.io/devfiles/index.json",
          "httpVersion": "",
          "headers": [
            {
              "name": "Accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "Referer",
              "value": "https://che-che.192.168.99.100.nip.io/dashboard/"
            },
            {
              "name": "Origin",
              "value": "https://che-che.192.168.99.100.nip.io"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "empty"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_NAME_NOT_RESOLVED"
        },
        "cache": {},
        "timings": {
          "blocked": 0.5880339999857824,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": -1
        },
        "serverIPAddress": "",
        "_initiator": {
          "type": "script",
          "stack": {
            "callFrames": [
              {
                "functionName": "",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 28008
              },
              {
                "functionName": "w",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 25482
              },
              {
                "functionName": "l",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 23154
              },
              {
                "functionName": "c",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 10243
              },
              {
                "functionName": "",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 10689
              },
              {
                "functionName": "$digest",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 16548
              },
              {
                "functionName": "$apply",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2392,
                "columnNumber": 18542
              },
              {
                "functionName": "a",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 24601
              },
              {
                "functionName": "v",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 27170
              },
              {
                "functionName": "w.onload",
                "scriptId": "124",
                "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                "lineNumber": 2391,
                "columnNumber": 27594
              }
            ],
            "parent": {
              "description": "load",
              "callFrames": [
                {
                  "functionName": "",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2391,
                  "columnNumber": 27438
                },
                {
                  "functionName": "w",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2391,
                  "columnNumber": 25482
                },
                {
                  "functionName": "l",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2391,
                  "columnNumber": 23154
                },
                {
                  "functionName": "c",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2392,
                  "columnNumber": 10243
                },
                {
                  "functionName": "",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2392,
                  "columnNumber": 10689
                },
                {
                  "functionName": "$digest",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2392,
                  "columnNumber": 16548
                },
                {
                  "functionName": "",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2392,
                  "columnNumber": 3021
                },
                {
                  "functionName": "",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2390,
                  "columnNumber": 25432
                },
                {
                  "functionName": "o",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2390,
                  "columnNumber": 1198
                },
                {
                  "functionName": "c",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2390,
                  "columnNumber": 25416
                },
                {
                  "functionName": "a",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 2390,
                  "columnNumber": 25295
                },
                {
                  "functionName": "dispatch",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 266,
                  "columnNumber": 2939
                },
                {
                  "functionName": "g.handle",
                  "scriptId": "124",
                  "url": "https://che-che.192.168.99.100.nip.io/dashboard/scripts/app-33a84c37c4.js",
                  "lineNumber": 266,
                  "columnNumber": 938
                }
              ]
            }
          }
        },
        "_priority": "High",
        "_resourceType": "xhr",
        "pageref": "page_2"
      }
    ]
  }
}

**Comment by adriendelsalle** [comment]
Maybe related to https://github.com/eclipse/che/issues/16483#issuecomment-607091646 ?

**Comment by MatthiasPopp** [comment]
I got the same error message right now.
This might be a really dumb to ask but the following solved it for me:
Did you add the certificate produced by the chectl command?
The installer clearly states that you have to do that manually. 
If I open the URL of the che server without adding the certificat beforehand, I get the issue. After adding the URL everything works, even if I delete the certificat afterwards! Looks to me like some first time initialising stuff going on.
I hope that helps because I do not have any clue what I am doing here :)
> matthias@hp:~$ chectl server:start -p minikube
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Check Kubernetes version: Found v1.18.0.
    ✔ Verify if minikube ingress addon is enabled
    ✔ Enable minikube ingress addon
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.39.183.nip.io.
Eclipse Che logs will be available in '/tmp/chectl-logs/1585743168811'
  ✔ Start following logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
  ✔ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.1.2+gd878d4d
    ✔ Create Namespace (che)...done.
    ✔ Check Eclipse Che TLS certificate...going to generate self-signed one
      ✔ Check Cert Manager deployment...not deployed
      ✔ Deploy cert-manager...done
      ✔ Wait for cert-manager...ready
      ✔ Check Cert Manager CA certificate...generating new one
      ✔ Set up Eclipse Che certificates issuer...done
      ✔ Request self-signed certificate...done
      ✔ Wait for self-signed certificate...ready
      ✔ ❗[MANUAL ACTION REQUIRED] Please add local Eclipse Che CA certificate into your browser: /home/matthias/cheCA.crt
    ✔ Check Cluster Role Binding...does not exists.
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Eclipse Che Helm Chart...done.
  ✔ ✅  Post installation checklist
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Eclipse Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Retrieving Eclipse Che server URL... https://che-che.192.168.39.183.nip.io
    ✔ Eclipse Che status check
Command server:start has completed successfully.

**Comment by adriendelsalle** [comment]
@mgiammarco could you confirm you added the certificate in your browser or test this solution please?
Thanks!

**Comment by mgiammarco** [comment]
Yes I confirm. Thank you very much.
I could not imagine that a missing certificate was the problem.
I hope I do not need to add to every browser I use I will now do some tests.
Thanks again!

Il giorno ven 3 apr 2020 alle ore 18:34 Adrien Delsalle <
notifications@github.com> ha scritto:

**Comment by adriendelsalle** [comment]
Hi @mgiammarco ! You're welcome.
Could you please consider closing this issue after testing? Thanks a lot.
