### ISSUE TITLE
Autocomplete for python?

### ISSUE THREAD

**Issue by alex-marinov** [eclipse-che/che#1642]
Are there any plans for autocomplete feature for python please?

I couldn't see anything regarding this on the Roadmap, and wondering if/when autocomplete feature will be available for python.

Thanks,
Alex

**Comment by TylerJewell** [comment]
Last Monday, we announced in a press release with Microsoft and Red Hat support for the language server protocol.  It's a way for language servers to consistently integrate with any IDE.  Che and VS Code are the first two protocol implementers. We'll be releasing our formal support for it in a few more weeks.

Python is one of the languages that the community is converting into a language server.  It's not yet listed on the wiki page - but we've seen activity for it.  This will give all sorts of intellisense capabilities for python. Hard to offer a concrete timeframe yet as the python community hasn't committed one yet.  But once they ship one, it will be discoverable automatically from within Che.

http://www.eweek.com/developer/codenvys-new-language-server-protocol-reduces-programmer-envy.html

https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations

http://che.eclipse.org/press-release-red-hat-codenvy-microsoft-collaborate-language-server-protocol/

**Comment by alex-marinov** [comment]
Fantastic, thanks for the info.
