### ISSUE TITLE
Github integration using a deprecated method 

### ISSUE THREAD

**Issue by mingfang** [eclipse-che/che#16425]
### Is your enhancement related to a problem? Please describe.
I received this email from Github

```
Hello there!

On March 23rd, 2020 at 13:39 (UTC) your application (che-legionx-com) used an access token (with the User-Agent Java/1.8.0_232) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

**Comment by ibuziuk** [comment]
@mingfang could you please update the issue according to the template? Also please provide the steps to reproduce

**Comment by mingfang** [comment]
1- go to GitHub to create another oauth application. But this time use the Che callback URL instead of the Keycloak callback URL. e.g. `https://che.legionx.com/api/oauth/callback`

2-set the Client ID and Client Secret in the respective env variables before starting Che
```
CHE_OAUTH_GITHUB_CLIENTID=<Client ID>
CHE_OAUTH_GITHUB_CLIENTSECRET=<Client Secret>
```
3-Edit any workspace and add a project using the GitHub integration.  Github will ask for your permission as expected. Afterwards Github will send that email I posted above.

**Comment by ericwill** [comment]
@vinokurig is this one still relevant?

**Comment by vinokurig** [comment]
It is still relevant. According to https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters, `access_token` query parameter is deprecated but we still using it.

**Comment by nickboldt** [comment]
Backported to 2.5.1 (Che 7.20.x)
