### ISSUE TITLE
Go stack is not completed...

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#16427]
### Describe the bug
Currently when I use golang dev-stack and open go file from project sample I see error markers in the import, because go tool reconfigured to use go modules. But our sample  do not use go modules... Also go tool auto-generates go.mod and go.sum files, but we don't need them for non go-modules project. And our sample located in /projects/src/github.com/golang/example directory go tools can not do correct analyze in this location when go mod enabled...
So we have two option:
1. Disable go mod in the configuration go tool.
2. Use newer sample project with modern go modules, and than we even don't need ugly location /projects/src/github.com/golang/example, caused $GOPATH  

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create project from go dev stack
2. Open file from sample /projects/src/github.com/golang/example
3. See errors in the imports... Wait a bit. Go tool auto-generate in the project go.mod and go.sum...

### Expected behavior
None error markers, none auto-generated files... 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by AndrienkoAleksandr** [comment]
Issue detected with https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/ms-vscode/go/0.11.4

**Comment by ericwill** [comment]
Maybe we can just remove it from the sidecar container? https://github.com/che-dockerfiles/che-sidecar-go/blob/1.12.9/Dockerfile#L82

**Comment by AndrienkoAleksandr** [comment]
> Maybe we can just remove it from the sidecar container?

I don't think so. I think it's a good to have this option like default, because go modules is a new technology and old way with long location $GOPATH/src/org/project is deprecated. All go projects should migrate to the go-modules...

**Comment by ericwill** [comment]
Okay. I had trouble running the sample Go workspace if I build my own sidecar image. When I use this change it works again -- I think rebuilding the sidecar image updates some of the dependencies that need this environment variable turned off.

**Comment by ericwill** [comment]
Is there anything left to do here?

**Comment by AndrienkoAleksandr** [comment]
> Is there anything left to do here?

Thanks, I think issue resolved.
