### ISSUE TITLE
`chectl update next` does not work as expected

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16423]
### Describe the bug
It is not possible to update chectl from next channel anymore, since
when I execute `chectl update next`, chectl is updated from next channel but then instantly is updated from stable...
Actually it's possible to break the process just after chectl is update from next by pressing Ctrl+C, but it seems to be a workaround but not feature ;)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. chectl update next
2. chectl version

### Expected behavior
chectl is updated from next channel

### Actual behavior
chectl is updated from next channel but then instantly is updated from stable...

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5887312/77301016-a89ffa80-6cf7-11ea-966f-5e5b30504e01.gif)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/pull/620
