### ISSUE TITLE
Move dashboard contribution guide from CONTRIBUTING.md in che main repo to dashboard repo.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16431]
### Is your task related to a problem? Please describe.

Following that discussion https://github.com/eclipse/che/pull/16430#discussion_r396977130

**Comment by sunix** [comment]
@sleshchenko could someone from your team take it ?

**Comment by sleshchenko** [comment]
Sorry for delaying such a quick change. PRs are created but note that contributing flow will be still broken. It has dedicated issues created
