### ISSUE TITLE
Unable to update single-user Che deployed with Operator

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16437]
### Describe the bug
Che fails to restart after updating CheCluster CR. It's caused by RollingUpdate which is not supported for SingleUser Che

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Single User Che with Operator on OpenShift 4.x
2. Update CheCluster CR
3. Check is pod is successfully started:
![Screenshot_20200325_091530](https://user-images.githubusercontent.com/5887312/77511331-8a620800-6e79-11ea-8a4c-2294109540f5.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] `chectl server:start --installer=operator --platform=openshift --che-operator-cr-patch-yaml=/home/serg/che-single-user.yaml`
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse/che-operator/pull/432
