### ISSUE TITLE
Build and publish Che server DTO types on npm on each Che release

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#16436]
### Is your task related to a problem? Please describe.
We have [`@eclipse-che/api`](https://www.npmjs.com/package/@eclipse-che/api) npm package which contains typescript declarations of Che server DTOs. But that package is not updated automatically, despite [we have scripts](https://github.com/eclipse/che/tree/master/typescript-dto) to build and publish the package.
These types are used in `chectl` and in Che Theia plugins which need interaction with Che master API.
But as of now we have `7.5.0-SNAPHOST` version as `latest`.

### Describe the solution you'd like
Update the npm package on each Che release

**Comment by sleshchenko** [comment]
@mkuznyetsov isn't it something already fixed?

**Comment by nickboldt** [comment]
Seems something broke 7mo ago, as we're no longer publishing updates here. 

![image](https://user-images.githubusercontent.com/227597/115022219-167f0d00-9e8b-11eb-8ea4-b818cd650f0a.png)

**Comment by nickboldt** [comment]
https://www.npmjs.com/package/@eclipse-che/api still shows latest as 7.18.1 

So it appears that https://github.com/eclipse/che/commit/378f5c197fb852f19eeea1a6ee462412afd332ab didn't work.

**Comment by nickboldt** [comment]
https://www.npmjs.com/package/@eclipse-che/api now showing 7.29.1

However https://github.com/eclipse/che/pull/19635 remains unmerged in master branch because blocked by required (failing) tests. 

Anyone know an override for that?

**Comment by nickboldt** [comment]
Rebasing PR to latest from master allowed tests to pass, so https://github.com/eclipse/che/pull/19635 is merged now. Props to @skabashnyuk for the life hack :D
