### ISSUE TITLE
Make server check phase more transparent

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16451]
### Is your task related to a problem? Please describe.
We often have created issues with `Server theia in container theia-ide not available` title, and it says actually nothing, it makes sense to:
1. For example, when we do half server checks attempts: start printing logs: `Waiting server theia be available via https://theia-server.mynamespace.192.168.0.100.nip.io/ but got 409 response`
2. The last try should print even more info (maybe previous should as well), like request failed because of error `SSL handshake failed since SAN missing for host theia-server.mynamespace.192.168.0.100.nip.io` (this error message I invent and actually it may be different in case of self-signed cert issue) or `host 192.168.0.100.nip.io is not resolved with IP adrress` (I assume something like that will appear if there is a network configuration issue in k8s/OS cluster).

So, then we get two profits:
1. While workspace is starting, user is able to check if theia is really unavailable or it's CheServer<>Workspace connectivity issue while user is able to open Theia from Browser.
2. Workspace start output contains more info and probably cause of error.

**Comment by strongit** [comment]
same issue，Is there a way to solve it？Urgently needed solutions！

**Comment by skabashnyuk** [comment]
>same issue，Is there a way to solve it？Urgently needed solutions！

We don't have a solution. My assumption it is related to `SSL` and installation. 
You can try a different installation method.  For example operator instead of a helm.

**Comment by strongit** [comment]
> > same issue，Is there a way to solve it？Urgently needed solutions！
> 
> We don't have a solution. My assumption it is related to `SSL` and installation.
> You can try a different installation method. For example operator instead of a helm.

OK，we have a try

**Comment by skabashnyuk** [comment]
According to the information from @tolusha  they made multiple
improvements in installation with tls that might fix this problem.
Our suggestion would be to try to test the latest release and let us know if this problem is still reproducible. In case if it
is reproducible please follow up the whole Github bug template
and let us know the necessary information on how to reproduce it.

**Comment by strongit** [comment]
> > > same issue，Is there a way to solve it？Urgently needed solutions！
> > 
> > 
> > We don't have a solution. My assumption it is related to `SSL` and installation.
> > You can try a different installation method. For example operator instead of a helm.
> 
> OK，we have a try

we use operator install the che success,thank you.
![image](https://user-images.githubusercontent.com/11691213/88038076-4efdee80-cb78-11ea-8dde-4869710872e2.png)
