### ISSUE TITLE
New Workspace Loading Page

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16458]
Current workspace loading page looks like this:

![image](https://user-images.githubusercontent.com/606959/77647200-4ac51a00-6f66-11ea-8e18-f8b7f8d07ac9.png)

The progress bar that doesn't provide any information about progress
The logs provide an idea of the progress but are shown on a small part of the screen and only someone that is familiar with Che architecture can understand what's going on (in terms of where we are in the workspace startup process) 

A proposal is to:
- Replace the progress bar with a list of the "high level steps" of a workspace startup updated with their status (NOT STARTED / IN PROGRESS / COMPLETED)
- Show to detailed logs only if a user clicks on a `logs` tab or button 

cc @beaumorley

**Comment by amisevsk** [comment]
There's actually already a fairly reasonable internal representation of the high-level steps in starting workspace in our tracing:
![Screenshot_2020-03-27 Jaeger UI](https://user-images.githubusercontent.com/16168279/77766479-15780500-7016-11ea-8d5c-90aef3830f6c.png)

With that in mind, I might suggest phases like
1. Processing workspace plugins
    a. Downloading plugin metadata from plugin registry
2. Preparing to create workspace objects (elements?)
3. Waiting for workspace to be ready
    a. Pulling images
    b. Running initialization tasks (init containers)
    c. Starting workspace containers
    d. Waiting for workspace servers

**Comment by l0rd** [comment]
@amisevsk thanks for providing these details. I think they will be useful when @beaumorley will work on it. 

For phase 2. I would use devfile terminology "Preparing to create workspace components".
And for 3d. as well "Waiting for workspace components readiness" ("workspace server" terminology).

Something important for the design is that, the 4 steps of phase 3, are run multiple times (once for each workspace container) and in parallel (one container can be ready while another one stuck at phase a).

@amisevsk in what phase does the volume mount happen?

**Comment by amisevsk** [comment]
> @amisevsk in what phase does the volume mount happen?
Volume mounting happens when the pod is created (before image pulls) IIRC. That would be a *very* useful progress bullet point to include. Another pain point we might try to address down the line is route exposure time.

**Comment by l0rd** [comment]
Volume mounting can also happen asynchronously in the future https://github.com/eclipse/che/issues/15384.

**Comment by sleshchenko** [comment]
I believe this epic can be closed since Dashboard Next already is based on the new Loading Workspace design.
It still does not have too detailed steps but it's going to be implemented later when we switched to DevWorkspace CRs.
