### ISSUE TITLE
Prepare devfile for `che-operator` repository

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16454]
It is needed to prepare a devfile for che-operator [1] repository with build, run and debug tasks.

[1] https://github.com/eclipse/che-operator/

**Comment by sunix** [comment]
needed for https://github.com/eclipse/che/issues/14126#issuecomment-527833101

**Comment by sunix** [comment]
If we could add a dedicated CONTRIBUTING.md, would be awesome
