### ISSUE TITLE
Dashboard doesn't show an error that happens during factory acceptance

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16453]
### Describe the bug
Dashboard hangs on `Workspace Initializing` phase when an error occurs on workspace creation during factory accepting.

### Che version

 - [ ] latest
 - [ ] nightly
 - [X] other: 7.9.2

### Steps to reproduce
1. Try to create the workspace which is going to fail to be created, like http://che.openshift.io/f?url=https://gist.githubusercontent.com/skabashnyuk/141076d10fb7ba932f8d48457bcc1dea/raw/2594c641c34612fc0da5e4ea90084785d421ac62/gistfile1.txt
2. Check browser console

### Actual behavior
Dashboard hangs on `Workspace Initializing` phase.

### Expected behavior
Dashboard reports an error that happens during workspace creation.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
<img width="1674" alt="Знімок екрана 2020-03-26 о 08 59 23" src="https://user-images.githubusercontent.com/1614429/77625539-0de82b80-6f44-11ea-8209-7430cb0ee75d.png">

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [X] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
n/a

### Additional context
https://github.com/eclipse/che/issues/16450

**Comment by sleshchenko** [comment]
The 409 error is not expected during shared factory acceptance, so it's an important issue that should be fixed but it's not critical, it's why I put P2.

**Comment by sleshchenko** [comment]
it seems to be fixed, at least the shared link in the issue description now is properly handled 
![Screenshot_20201001_154803](https://user-images.githubusercontent.com/5887312/94811037-82bd8600-03fd-11eb-9848-c608afcb2e73.png)
