### ISSUE TITLE
Plugins view is empty in Che Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16452]
### Describe the bug

`Plugins` view is empty in Che Theia.

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Open Plugins view, `View > Open View... > Plugins`

### Expected behavior
The VS Code/Theia extensions should be listed.

### Screenshots
![image](https://user-images.githubusercontent.com/1636395/77627282-578a4380-6f4f-11ea-853b-358b726ac348.png)

**Comment by vitaliy-guliy** [comment]
It's not right the Plugins view, it's old one.
We just need to remove it from the list in `Open View...`
