### ISSUE TITLE
[Metric] Ensure that the total number of records in the activity table is identical to the workspace table

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16466]
### Is your enhancement related to a problem? Please describe.

As described here https://github.com/eclipse/che/issues/16465 we track the activity of workspaces in separate
tables and  due to the event-based nature of activity tracking, it is recorded
in a separate database transaction, distinct from the transaction that adds records to the workspace table.
That is way exists the potential risk of inconsistencies. 

### Describe the solution you'd like
Two ways.

1. 1-to-1 record relation (foreign key) between activity and workspace tables.
2. Reconciler job that periodically checks consistency between these two tables.

### Describe alternatives you've considered
n/a
### Additional context
 https://github.com/eclipse/che/issues/16465
https://github.com/eclipse/che/issues/13226

**Comment by sparkoo** [comment]
We could even merge the activity table into the workspace table. The activity table creates an illusion that we have any kind of workspace activity history, but in reality it's one entry per workspace that is constantly updated.

**Comment by skabashnyuk** [comment]
won't fix
