### ISSUE TITLE
Review e2e testing mechanism during che-theia-dev image build

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#16463]
### Is your task related to a problem? Please describe.
As we know, our images mainly build on ci service and the e2e mechanism is odd when che-theia-dev image builds. 

During the build of [e2e/Dockerfile](https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia-dev/e2e/Dockerfile) theia is cloned and built just to check whether server can start. Then, on next stage, che-theia image builds with the repetitive operation, e.g. theia clone and build. We can rely only on happy path testing and push `che-theia-dev` and `che-theia` images on quay.io only when the report indicates success.

### Describe alternatives you've considered
N/A

### Additional context
This approach may save up 15-20 minutes.

**Comment by benoitf** [comment]
hello, I'm not sure to follow the problem

theia is cloned but not to ensure server can start but to ensure that theia can be compiled as a project on che-theia-dev image

**Comment by vzhukovskii** [comment]
@benoitf yep, you're right. But when we take into account the flow, performed on pr jobs, there are some steps:

- build _che-theia-dev:alpine_ 
- build _che-theia-dev:ubi8_ 
- build _e2e-dev_ image with theia clone and build **(*)**
- build _che-theia:alpine_ with theia clone and build 
- build _che-theia:ubi8_ with theia clone and build 
- build _e2e_ image

**(*)** build is useless, when the next step will build the same sources

**Comment by benoitf** [comment]
@vzhukovskii why is it useless ?

**Comment by benoitf** [comment]
I think here you could save more time by compiling in one job `alpine` and with another job `ubi8` (in parallel instead of sequential)

**Comment by vzhukovskii** [comment]
> it's because che-theia is built ?

I guess only because of this

> I think here you could save more time by compiling in one job alpine and with another job ubi8 (in parallel instead of sequential)

Also was thinking of this approach, it will allow us to reduce general build time in two times, I hope

**Comment by benoitf** [comment]
also https://github.com/eclipse/che-theia/pull/662 should help in reusing a previous image when building a new one (allow to reuse docker layers)

other ideas: disable linters in builds (only keep linter of first yarn call)
- your idea: download plug-ins if not changed instead of rebuilding them

**Comment by vzhukovskii** [comment]
> also eclipse/che-theia#662 should help in reusing a previous image when building a new one (allow to reuse docker layers)

Hmm, will take a look on how it realized. As for download plug-ins, make sense, there isn't a need to build them each time, when there aren't any changes inside.

**Comment by benoitf** [comment]
ok the basic idea of my PR is that che-theia-dev should be only rebuild if there is a change in generator or in the base system (which is happening at a very low rate)

so, by using `docker build --from-image (existing-theia-dev-image)` it will reuse layers from existing image and then we can speed up both build of the image and the e2e of theia-dev as it won't build anything as it's already in cache
