### ISSUE TITLE
License headers update to 2020 year

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16470]
### Is your task related to a problem? Please describe.
Need to update license headers to 2020. Currently, 2018 is still used e.g. - https://github.com/eclipse/che/blob/master/multiuser/permission/che-multiuser-permission-devfile/src/main/java/org/eclipse/che/multiuser/permission/devfile/DevfilePermissionsFilter.java#L2

**Comment by tolusha** [comment]
@ibuziuk I would say it is P2, right?

**Comment by sleshchenko** [comment]
@tolusha I even maybe P3, we successfully have not updated license to the 2019 year https://github.com/eclipse/che/issues/15222 ) Since 2020 is a leap year - it has even less chances.
