### ISSUE TITLE
[workspace-loader] Implement an ability to run workspace-loader as workspace server

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16472]
### Is your task related to a problem? Please describe.
Currently, we have a command in the devfile for WorkspaceLoader to run nodejs server and it works fine in terms of process is launched but it's not possible to test that WorkspaceLoader.
It basically happens because WorkspaceLoader is designed to use Keycloak token and to get it, the loader must be served from Che Server host but not generated one for workspace server (it's expected that Keyclock does send user's token to every host, only trusted ones).

So, Workspace Loader could use machine token BUT it's per workspace, it's valid until workspace is RUNNING, it has limited rights, like reading workspace configuration. So, we're not able to test Workspace start workflow with WorkspaceLoader run as workspace server.

### Describe the solution you'd like
We could separate WsLoader functionalities:
- Token retrieving
- Start/Open workspace

And for Token retrieving part, additionally to keycloak script, we could also support `Manually provided token`... Just before doing things - full-screen input is shown where developer must paste their keycloak token.

On one hand it would unblock us in testing workspace loader withing workspace
On another hand, it would require supporting additional functionality and in case of keycloak script token retrieving changes - we still are not able to test it withing workspace, the only way to test - rebuild Che and run it locally.

### Describe alternatives you've considered
Do not develop Workspace Loader in Che =(

**Comment by olexii4** [comment]
@sleshchenko Yes. Keycloak does send the user's token to every host, only trusted ones. But it is easy to add an exclusion.
The easiest way: start dev-mode, then add an exclusion to the Keycloak and that is it.

In the case with https://che.openshift.io  Keycloak rules are not very strict and no need to add exclusions.

As for me, I am using the next snippet for testing workspace-loader:

```
        function test (devfile) {
            const xhr = new XMLHttpRequest();
            xhr.open('POST', '/api/workspace/devfile');
            xhr.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
            xhr.setRequestHeader('Authorization', 'Bearer ' + _keycloak.token);
            xhr.send(JSON.stringify(Object.assign({apiVersion: '1.0.0', components: [], projects: [], metadata: {name: 'wksp-test'}}, devfile||{})));
            xhr.onreadystatechange = () => {
                if (xhr.readyState === 4 && xhr.status === 201) {
                    const {namespace, devfile: {metadata: {name}}} = JSON.parse(xhr.response);
                    location.replace('/workspace-loader/' + namespace + '/' + name);
                }
            };
        }

        test();
```
This script creates a new workspace from the custom devfile or from the default one. Then redirects on it. 

Just paste this script in the console when the workspace-loader window will be opened in dev mode. It creates a new workspace from the custom devfile. Then change the location for testing.

**Comment by sleshchenko** [comment]
That's not actual since workspace loader is going to be deprecated soon
