### ISSUE TITLE
Warning when using Go plugin: update formatTool to `goimports`

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16480]
### Is your enhancement related to a problem? Please describe.
When using the go plugin *without the experimental language server activated*, a warning is shown to the user:

![Screenshot from 2020-03-27 17-30-58](https://user-images.githubusercontent.com/16168279/77802245-d74c0700-7050-11ea-9e03-66856e8f5dd4.png)

Note: `goimports` is [already installed in the sidecar container](https://github.com/che-dockerfiles/che-sidecar-go/blob/1.12.9/Dockerfile#L63)

### Describe the solution you'd like
Remove `goreturns` from the [go-sidecar](https://github.com/che-dockerfiles/che-sidecar-go/blob/1.12.9/Dockerfile#L62). This should force the plugin to use `goimports` instead (but this should be confirmed).

### Describe alternatives you've considered
Figure out a way to set this setting by default on start

### Additional context
It's easy to workaround this issue the "update" button will update settings without issue.

**Comment by ericwill** [comment]
@svor / @vitaliy-guliy can you check and see if this is still an issue?

**Comment by amisevsk** [comment]
I believe this is no longer an issue since we moved to enabling `gopls` (tested briefly on che.openshift.io (`7.18.2`) and didn't see the message). 

I do get the message 
> New version of gopls (0.5.0) is available. Please update for an improved experience.

but clicking the update button works fine.

**Comment by ericwill** [comment]
Thanks @amisevsk, I'm going to close this one then.
