### ISSUE TITLE
Collect detailed workspace activity metrics for Hosted Che

### ISSUE THREAD

**Issue by pdaverh** [eclipse-che/che#16485]
To enhance the value delivered by Hosted Che, we would like to gather detailed usage related metrics.

We would like to learn about the following usage patterns:

Percentage of projects not using sample code provided by the stacks
Average time gap between starting first workspace to adding a project with external Git repo
Top features used by developers
Top plug-ins used by developers
Frequency of usage of plug-ins v/s frequency of workspace starts

**Comment by gorkem** [comment]
> To enhance the value delivered by Hosted Che, we would like to gather detailed usage related metrics.
> 
> We would like to learn about the following usage patterns:
> 
> Percentage of projects not using sample code provided by the stacks
> Average time gap between starting first workspace to adding a project with external Git repo

I am not sure if this requires collection of new data. There is enough data collected to determine if a workspace has been used for editing files and git operations (commit and push).

> Top features used by developers
> Top plug-ins used by developers
> Frequency of usage of plug-ins v/s frequency of workspace starts

+1 for the plugin usage.  Perhaps something similar to the stack usage data makes sense.

**Comment by ibuziuk** [comment]
there is a separate issue for plugin usage - https://github.com/eclipse/che/issues/16105
and there is a separate issue for custom devfile usage - https://github.com/redhat-developer/rh-che/issues/1804
are you ok to close this issue in favor of those two ?
