### ISSUE TITLE
Always createOrReplace workspace role bindings

### ISSUE THREAD

**Issue by mingfang** [eclipse-che/che#16484]
### Is your enhancement related to a problem? Please describe.
Currently workspace role bindings are not updated after the service account has already be created.  This is due to the `else` cause there
https://github.com/eclipse/che/blob/279768c8daa9ce1e65c3ae41d79752ed1571e1f5/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccount.java#L71
As a result any changes to the role binding is not effective.

### Describe the solution you'd like
The solution is to simply remove the `else` clause so that the code can flow the the role binding creation code.

### Describe alternatives you've considered
I have to manually apply any role binding changes.

**Comment by ibuziuk** [comment]
@mingfang could you please open a PR for that?
