### ISSUE TITLE
[helm] Che deployment fails with kubeadm v1.18.0

### ISSUE THREAD

**Issue by CyborTronik** [eclipse-che/che#16491]
Installed fresh version of `chectl` on Ubuntu 18.04.04 LTS with kubeadm v1.18.0

This is what I get:
```
chectl server:start -a helm
  ✖ Verify Kubernetes API
    → Failed to connect to Kubernetes API. E_K8S_API_NO_RESPONSE - Endpoint: https://10.0.0.14:6443/healthz - Error message: connect ETIMEDOUT 10.0.0.14:6443
    👀  Looking for an already existing Eclipse Che instance
 ›   Error: Error: Failed to connect to Kubernetes API. E_K8S_API_NO_RESPONSE - Endpoint: https://10.0.0.14:6443/healthz - Error message: connect ETIMEDOUT 10.0.0.14:6443
 ›   Installation failed, check logs in '/tmp/chectl-logs/1585591401505'

```
The kubernates operates normally and I'm able to run necessary containers

**Comment by tolusha** [comment]
Could you open `https://10.0.0.14:6443/healthz` in browser?

**Comment by tolusha** [comment]
@CyborTronik 
In recent version of chectl we added `--skip-kubernetes-health-check` flag to skip Kubernetes health check. Pls use it if you're sure that your Kubernetes cluster is health
