### ISSUE TITLE
Verify that plugin images referenced in the plugin registry actually exist in Quay

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16501]
### Describe the solution you'd like

we should have better tests in the plugin registry publishing process (and its build too!) to validate that when we add a new plugin 7.9.2 or 7.11.0 for machine-exec and che-theia that the plugins **actually exist in quay** 

This probably requires nothing more than a quick skopeo check:

```
skopeo inspect docker://quay.io/eclipse/che-*:${VERSION} | grep "${VERSION}"
```
If found, contrinue the release/build. If not, wait 5 mins and try again... then fail if not found.

TBH I'm not 100% what workflow we want here for if-not-found-then. I guess it will depend on if this is a temporary state (upstream publishing job not yet done; quay.io temporarily down) or a permanent state (we forgot to add the plugin).

This could be as simple as checking ONLY the che-machine-exec and che-theia images, or it could be extended to validate that ALL image references are valid.

See also #16499

**Comment by ericwill** [comment]
I think this one can be partially solved by PR checks on the plugin registry, so that non-existent images don't get placed in the registry `meta.yaml` files. Though I suppose those images could be deleted between merge and release time, so double checking is probably required.

**Comment by nickboldt** [comment]
@ericwill have you implemented anything in the plugin or devfile registries that verify all references images exist?

**Comment by ericwill** [comment]
> @ericwill have you implemented anything in the plugin or devfile registries that verify all references images exist?

The plugin registry has some checks, but nothing comprehensive. It's still a TODO.

**Comment by nickboldt** [comment]
Plugin registry now includes digests, so we check that the ref'd images exist in order to fetch digest from tag. 

TODO: add digests to devfile registry too?
