### ISSUE TITLE
Callback mechanism when a new workspace is created via the API

### ISSUE THREAD

**Issue by triceam** [eclipse-che/che#16504]
I can create a new Che workspace by passing a devfile to the Che instance as described here:
https://redhat-developer.github.io/devfile/#getting-started

For example: 
```
curl -X POST \
  -H "Authorization: <TOKEN>" \
  -H "Content-Type: application/yaml" \
  -d <devlile_content> \
  https://<your-che-host>/api/devfile
```

However, it doesn't appear that there is a mechanism to let an external system know that the workspace was created.   Imagine that I have an application that manages applications and services, and I want to generate a devfile, pass it off to Che to create a development environment/workspace.  

I propose the addition of an additional mechanism when passing a devfile into a Che instance that instructs Che to make a request to the system of origin (submitter of the post request) once a workspace has been created.  This could be either a query parameter, or something in the devfile itself.  

With this addition the following workflow will be possible: 
- the system of origin can generate a devfile, pass it off to a Che instance
- Che creates a workspace
- Che notifies the system of origin that the workspace exists (and passes back a workspace name/id and any additional metadata).  

This will allow the system of origin to deep link into the already created workspace in subsequent interactions.

**Comment by skabashnyuk** [comment]
Such a mechanism already exists. It's Json-RPC over webscocket. Soon we are going to publish training video that explains more about this topic https://github.com/eclipse/che/issues/16255 
At this moment you can take a look at the dashboard and see how it reacts to different events(started/stopped) related to the workspace. All of them are made over Json-RPC

**Comment by triceam** [comment]
@skabashnyuk do you have to be authenticated to use the websocket?  The use case i'm envisioning is a backend that is unaware of the user state on Eclipse Che.  In this case, the system of origin passes of the devfile to Che, and may not necessarily have any knowledge whether a user is logged into Che.  I'm also imagining this as a multi-tenant service that would be handing off to Che as the IDE/editor, would this work if I have user A and user B passing over to the same Che instance at the same time? I imagined something more like a formal API call.  

I know that if you use the GET request version of the POST I described above, you'll automatically be redirected to a login flow.  I *assume* the POST request does something similar, but I've not tested it yet.

**Comment by skabashnyuk** [comment]
>@skabashnyuk do you have to be authenticated to use the websocket?

yes.
