### ISSUE TITLE
F1 is not handled as Find a command action when focus is on Welcome Page

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16506]
### Describe the bug
F1 is not handled as `Find a command` action when focus is on Welcome Page.
The fact 

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] 7.10.0

### Steps to reproduce
1. Create and start new Theia based workspace.
2. Click on a welcome page
3. Click F1 once workspace is started and Theia is loaded.

### Expected behavior
Find a command widget is opened

### Expected behavior
Browser support tab is opened.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5887312/78124176-fb746300-7417-11ea-9a61-cb3123351a37.gif)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by benoitf** [comment]
looks like a dup of https://github.com/eclipse/che/issues/15763

**Comment by azatsarynnyy** [comment]
closing it as a dup of https://github.com/eclipse/che/issues/15763 since 15763 is more general one
