### ISSUE TITLE
[Doc] Update links on the Che4z extension page on the Che 7 docs 

### ISSUE THREAD

**Issue by zeibura** [eclipse-che/che#16514]
The links to the CA Brightside documentation on https://www.eclipse.org/che/docs/che-7/eclipse-che4z/ need to be updated from version 2.0 to version 3.0

**Comment by themr0c** [comment]
I don't see any mention of `CA Brightside` in that page. I believe this issue is not relevant anymore. Please reopen if that's not the case.
