### ISSUE TITLE
Create a new Typeahea widget for UD

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#16518]
### Is your task related to a problem? Please describe.

Create a new Typeahead widget for the "Create Custom Workspace" page(https://github.com/eclipse/che/issues/15662).

### Describe the solution you'd like

Implement the same functionality which we have for the react + patternfly sample 
https://www.patternfly.org/v4/documentation/react/components/select#typeahead
Typeahead

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/16524
