### ISSUE TITLE
Developer Use Case: Reduce GWT compilation time

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#1651]
Recompiling the whole IDE GWT file each time a file is modified is hurting people. OK we may have super dev mode, but the first time we hit that.
1. Option 1 : having server side GWT with Vaadin:
   - 1a modular gwt modules
     - We may plug new Extension point. Then user-plugin can use these extension points (he still do java)
     - Also debugging component as most of the part of component is running server-side, it’s classical Java debugging
   - 1b : Vaadin is compliant with OSGi, so components could come with OSGi bundles as well. Then we could use Eclipse Equinox (OSGi platform of Eclipse IDE) to deploy Che components.
2. Option 2: Javascript extension point.
   - Register extension point
   - Plug-ins plugs into these extension-points
   - Each plug-in is built as a standalone unit. No need to recompile a whole

**Comment by TylerJewell** [comment]
@skabashnyuk - I believe this is what you were discussing in your email.  I am going to link this to you for now, so that any work that is proposed is from a single issue and that we don't have fractured issues.

**Comment by janScheible** [comment]
The talk [Turducken - Divide and Conquer large GWT apps with multiple teams](https://de.slideshare.net/RobertKeane1/turducken-divide-and-conquer-large-gwt-apps-with-multiple-teams) targets the second option.
It involves multiple independent GWT modules coupled together via a native JavaScript event mechanism.
Could perhaps be a source of inspiration...

**Comment by skabashnyuk** [comment]
won't fix
