### ISSUE TITLE
Theia Plugin Manager does not work properly with a minimal devfile

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#16519]
### Describe the bug

Theia Plugin Manager does not work properly with a minimal devfile.
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify
### Steps to reproduce
1. Create a custom workspace.
![Screenshot from 2020-03-31 16-49-28](https://user-images.githubusercontent.com/6310786/78167268-e23ed700-7456-11ea-9a20-20fa993c306a.png)
2. Import Devfile > YAML. Create & Open from the default devfile.
![Screenshot from 2020-04-01 18-32-01](https://user-images.githubusercontent.com/6310786/78167509-4497d780-7457-11ea-80b0-76df82f72750.png)
3. Open View > Plugins and the error will be shown.
![Screenshot from 2020-04-01 18-25-29](https://user-images.githubusercontent.com/6310786/78167681-84f75580-7457-11ea-8c46-31371668993c.png)

It is reproduced locally on single-user and multi-user CHE v7.11.0 and on https://che.openshift.io v7.10.0 .

### Expected behavior

Plugins should be loaded without any errors.
### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by vitaliy-guliy** [comment]
It seems I faced this problem earlier and investigated the code a bit. The reason could be that Plugin service (Che-Theia extension) tries to read the components, which is empty.
It should be one-line fix.
