### ISSUE TITLE
Investigate kube-rbac-proxy as an alternative for openshift-oauth proxy

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16520]
### Is your task related to a problem? Please describe.
Investigate whether https://github.com/brancz/kube-rbac-proxy is a useful alternative to the openshift oauth proxy currently used in the che-workspace-controller.

Current drawbacks of openshift-oauth proxy:
- Cloudshell specific:
    - We cannot obtain the user's full token when using the proxy with a service account; the user's token is necessary to enable using cloud shell in its intended way
- More general:
     - The proxy only supports one listen port, whereas securing a full che workspace means proxying multiple ports (at least Theia and terminal)

From a cursory look at the kube-rbac-proxy, it appears that the same limitations are present there.

### Additional info
Subtask of https://github.com/eclipse/che/issues/15782, which covers implementation of an eventual solution.

**Comment by sleshchenko** [comment]
I believe it can be closed in favor of https://github.com/eclipse/che/issues/17856
