### ISSUE TITLE
Developer Use Case: Hot (un)deploy of server components

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#1652]
If I’ve a new component, like a rest service component, I should be able to add it dynamically on the workspace master or the workspace agent

My workspace agent is running, I could be able to use IDE or UD admin view, select a jar, click on update and then my rest component is available. Or to be able to disable dynamically my component. OSGi is a candidate with Eclipse Equinox.

**Comment by skabashnyuk** [comment]
won't fix
