### ISSUE TITLE
Create Che Devfile for Eclipse Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16522]
### Is your task related to a problem? Please describe.

To work on Eclipse Theia in Che we need Che Devfile.

### Describe the solution you'd like

Che Devfile should describe all the required tools and commands. It should be placed in upstream repo.

### Describe alternatives you've considered

In case it's not possible to place it upstream, then place it in Che Theia repo.

**Comment by vitaliy-guliy** [comment]
If you want to place the devfile in upstream repository, then it means that everybody should be able to create a Che repository from this devfile. What Che deployment are you going to use? Local Che is not a good option for that. Then only hosted Che, right?
It would be nice also to have a button somewhere in readme to quick create a workspace with a factory.
