### ISSUE TITLE
Che docs "in this article" section cannot be scrolled

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16533]
### Describe the bug
Some of our articles in the Che docs are quite long, with many sections. It's possible for the "in this article" section to become longer than the window, in which case the bottom headers are inaccessible:

Note on the highlighting the current header `in this article` section
![che-docs-sidebar-scroll](https://user-images.githubusercontent.com/16168279/78271474-2f17c180-74da-11ea-8108-f36bbf12a6bd.gif)

Note when we zoom out the page - additional items appear
![docs-scrolling-in-this-arcticle](https://user-images.githubusercontent.com/5887312/78330458-ac037380-758c-11ea-93da-c957dd9d83b1.gif)

### Che version
 - [x] latest

### Steps to reproduce
See page https://www.eclipse.org/che/docs/che-7/running-che-locally/#installing-che-on-kind-using-chectl_running-che-locally

### Expected behavior
It's possible to scroll the "in this article" sidebar

**Comment by themr0c** [comment]
Jekyll bug. We are moving to Antora soon, it will fix that behavior.

**Comment by themr0c** [comment]
Closing because Antora fixed the issue.
