### ISSUE TITLE
Dashboard and Workspace loader fail to connect via websocket if user uses a proxy server from Firefox browser

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#16537]
### Describe the bug
If a user works behind a proxy it is impossible to open start /open workspace via dashbaord / UI

### Che version
nightly, multiuser

### Steps to reproduce

1. Connect to a proxy server from your browser
2. Open Che dashboard
3. Try to create and open or just open existing workspace
4. After some delay, workspace loader shows error: `Unknown error has happened, try to reload page`. This repeats on each page refresh. Workspace is not changing its state from `STOPPED`.
Debug mode doesn't show any additional logs. Only the error message in downloaded file.

### Expected behavior
Workspace is started and opened as usual.

### Runtime
 - Che in local network
 - che.openshift.io

### Screenshots
![Screenshot from 2020-04-03 12-45-08](https://user-images.githubusercontent.com/15607393/78347514-48d40a00-75a9-11ea-8380-d78d72f74d50.png)

### Installation method
chectl 

### Additional context
It is possible to start workspace via API (and Swagger).

**Comment by sleshchenko** [comment]
> Connect to a proxy server from your browser

@mmorhun Could you please elaborate a bit more? Honestly, I'm not sure I understand how to reproduce this issue, so more detailed instructions are welcome.

**Comment by mmorhun** [comment]
@sleshchenko sorry if it wasn't clear. I meant that user accesses Che via a proxy server.
So to reproduce the issue just connect to a proxy server and try to use Che.
I used Squid 3 proxy server, which is configured just for proxying traffic without any modifications. But I think it doesn't matter which proxy server is used.

**Comment by mmorhun** [comment]
I've tried third party proxy and the result is the same.
In both cases I used Firefox browser.

The reason of failure is that dashboard/workspace-loader cannot open websocket connection and I see in browser logs:
```
Firefox can't establish a connection to the server at wss://che.openshift.io/api/websocket?token=<TOKEN>
```

**Comment by mmorhun** [comment]
Seems this is Firefox related issue as everything is working in Google Chrome.

**Comment by sleshchenko** [comment]
I think it can be closed after https://github.com/eclipse/che-dashboard/pull/72 is merged. @mmorhun WDYT?

**Comment by mmorhun** [comment]
Do not mind to close it after reasonable error message fix is merged.
