### ISSUE TITLE
Update instruction on how to deploy Che with self-signed cert

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16535]
### Is your task related to a problem? Please describe.
It seems that instruction on how to deploy Che with self-signed cert should be updated:
1. First of all installer Helm does not require secrets to be created since it's generated by chectl.
2. When you deploy with Operator on Kubernetes, chectl fails with a preflight check - 
```
kubectl create secret generic self-signed-certificate --from-file=ca.crt -n che
```
from https://www.eclipse.org/che/docs/che-7/setup-che-in-tls-mode-with-self-signed-certificate/#procedure-2
seems to be out-dated.
Here are commands which may be useful used by me to solve the issue
```
kubectl -n che create secret tls che-tls \
    --cert ./domain.crt \
    --key ./domain.key
CA_BASE_64_CONTENT="$(openssl base64 -A <"./ca.crt")" 
kubectl patch -n che secret che-tls -p="{\"data\":{\"ca.crt\": \"${CA_BASE_64_CONTENT}\"}}"
```

### Describe the solution you'd like
It's possible to deploy Che with the instruction provided in the documentation.

**Comment by mmorhun** [comment]
The issue with installer flag is fixed in https://github.com/eclipse/che-docs/pull/1175

**Comment by sleshchenko** [comment]
@mmorhun the first item in the addressed in the referenced PR
I faced the second issue because of outdated chectl version
