### ISSUE TITLE
Developer Use Case: Unlink/decouple IDE client from the runtime server

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#1653]
Like for User dashboard, we should have a mode to select a remote server
If I have “no” modification to do on a server, why should I regenerate or update my assembly

Let say a new server API is implemented and available on acceptanceserver.eclipse-che-acceptance.com I may want to deploy che IDE on a server and then connect websocket/APi to this remote server.

**Comment by gazarenkov** [comment]
Are you talking about Ws Agent or Ws Master or both?

**Comment by benoitf** [comment]
I was referencing IDE part of wsmaster (the client side war part)

**Comment by skabashnyuk** [comment]
won't fix
