### ISSUE TITLE
Create Che plugin providing a dev container with `buildah` tool to build docker images

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16538]
### Is your enhancement related to a problem? Please describe.

To develop many projects inside Che we need to be able to build the image inside a running container.

Buildah is a tool, which can be launched inside a running container and which can be used for building if images and pushing them to [docker.io](https://www.docker.com/) / [quay.io](https://quay.io/).  

### Describe the solution you'd like

Create a new plugin which will bring a new container with built and properly configured `buildah` tool.

We can reuse/copy the Dockerfile which is used for Kubernetes plugin https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/blob/1.1.0/Dockerfile

---

Buildah Git repository - https://github.com/containers/buildah

Buildah images on quay.io - https://quay.io/repository/buildah/stable?tag=latest&tab=tags

**Comment by amisevsk** [comment]
I believe the `quay.io/eclipse/che-sidecar-kubernetes-tooling` has buildah included:
```
$ docker run --rm quay.io/eclipse/che-sidecar-kubernetes-tooling:1.1.0 which buildah    
/usr/bin/buildah
```

**Comment by vitaliy-guliy** [comment]
Yes, the idea is to extract it to the dedicated plugin with its image to be able to use the buildah without kubernetes plugin.

**Comment by ericwill** [comment]
I believe this has been fixed in https://github.com/eclipse/che-plugin-registry/pull/448
