### ISSUE TITLE
Potentially necessary to upgrade fabric8.io.kubernetes-client for some versions of kubernetes or openshift

### ISSUE THREAD

**Issue by m-hu** [eclipse-che/che#16544]
### Is your task related to a problem? Please describe.
After deploying eclipse-che 7.10.0 on a corporate owned kubernetes cluster of version 1.14.4, the following error messages have been encountered during workspace request after ruling out all the issues related to unresolvable urls of docker images.

`java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### Describe the solution you'd like
upgrade fabric8.io.kubernetes-client to a version compatible with kubernetes 1.14.2 onwards.

### Describe alternatives you've considered
As the exception is about a 403, it could be either due to a wrong endpoint/url/parameters which responds 403 or permission is not granted for the account used for deployment. Hence, it could be good to activate the debug trace of fabric8.io.kubernetes-client as an alternative so as to see exactly the request so as to either extend the permission or upgrade the library.  I have retested the deployment with a fabric8.io.kubernetes-client upgraded package, the issue seems to be resolved accordingly. 

### Additional context
You may find the fabric8.io.kubernetes-client compatibility matrix following the link below
https://github.com/fabric8io/kubernetes-client#compatibility-matrix

**Comment by skabashnyuk** [comment]
duplicate https://github.com/eclipse/che/issues/11981 ?

**Comment by pptime** [comment]
Shall I test 7.11.0 instead then?
@skabashnyuk

**Comment by skabashnyuk** [comment]
>Shall I test 7.11.0 instead then?

yes.
