### ISSUE TITLE
[helm] Deployment failed on minikube with vm-driver=none

### ISSUE THREAD

**Issue by redeagle84** [eclipse-che/che#16559]
Having problems installing by chectl, following the doc where I found one.   
Did a checkpoint just before run the chectl comand to test with and without the "--multiuser" flag, 
the script works fine for non multiuser but crash when add "--multiuser" after restoring to the proper checkpoint.
The script is the folowing:

(surelly there is a better way to format the script below but i cant find nothing better than the code template, if someone know how to format it then it would improve the readability)

`
========================================================================
>>cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
========================================================================
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
========================================================================
uname -a
Linux ubuntu18x64 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
========================================================================
sudo apt-get install socat netcat openssl nmap zenmap 
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo usermod -aG docker myuser
========================================================================
sudo apt-get update && sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get -o Acquire::Check-Valid-Until=false update
sudo apt-get install -y kubectl
========================================================================
cd /usr/bin
sudo curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo chmod +x minikube
cd ~  
sudo apt-get install conntrack
sudo minikube start --vm-driver=none 
sudo systemctl enable kubelet.service
sudo minikube status
========================================================================
sudo snap install helm --classic
========================================================================
sudo snap install lxd
lxd init
lxc network set lxdbr0 ipv6.address none
========================================================================
sudo minikube status
sudo minikube update-context
curl -fsSL https://www.eclipse.org/che/chectl/ -o getchectl.sh
sudo bash getchectl.sh
which chectl
sudo chectl --version
>>chectl/7.10.0 linux-x64 node-v10.19.0
sudo chectl update
sudo minikube status
sudo minikube update-context
sudo minikube start --vm-driver=none 
sudo minikube addons enable ingress
ls
clear
========================================================================
sudo chectl server:start --platform minikube --installer helm --multiuser
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Check Kubernetes version: Found v1.18.0.
    ✔ Verify if minikube ingress addon is enabled
    ✔ Enable minikube ingress addon
    ✔ Retrieving minikube IP and domain for ingress URLs...172.17.18.153.nip.io.
Eclipse Che logs will be available in '/tmp/chectl-logs/1586222698544'
  ✔ Start following logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
  ❯ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.1.2+gd878d4d
    ✔ Create Namespace (che)...done.
    ❯ Check Eclipse Che TLS certificate...going to generate self-signed one
      ✔ Check Cert Manager deployment...not deployed
      ✔ Deploy cert-manager...done
      ✖ Wait for cert-manager
        → ERR_TIMEOUT: Timeout set to pod ready timeout 130000
        Check Cert Manager CA certificate
        Set up Eclipse Che certificates issuer
        Request self-signed certificate
        Wait for self-signed certificate
        Add local Eclipse Che CA certificate into browser
      Check Cluster Role Binding
      Preparing Eclipse Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Eclipse Che Helm Chart
 ›   Error: Error: ERR_TIMEOUT: Timeout set to pod ready timeout 130000
 ›   Installation failed, check logs in '/tmp/chectl-logs/1586222698544'
========================================================================
sudo kubectl get all -n che
No resources found in che namespace.
========================================================================
sudo kubectl get events -n che
No resources found in che namespace.
========================================================================
find /tmp/chectl-logs/
/tmp/chectl-logs/
/tmp/chectl-logs/1586222698544
/tmp/chectl-logs/1586222698544/che
/tmp/chectl-logs/1586222698544/che/events.txt <<= Zero bytes (empty)
========================================================================
`

**Comment by azatsarynnyy** [comment]
@tolusha please, take a look

**Comment by tolusha** [comment]
@redeagle84 
Is there any specific reason to use `--vm-driver=none` flag ?
Could you try with `--vm-driver=virtualbox` ?

**Comment by redeagle84** [comment]
@tolusha 

Sorry for my delay, last day being so painfull I can barely go out of bed, better enought to type now, doctor told probably will survive.

Thanks for you attention.


Im on a already virtualized env. and nest another level here would be very very slow, its a common laptop here.
Anyway I did what you told me but even this way receiving an error plus and advice to use driver=none because im runing all above one vm (HyperV) as you can read below:


>>========================================================================
sudo su
echo '#manualEntry' >> /etc/apt/sources.list
echo 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib' >> /etc/apt/sources.list 
apt-get update
apt-get install virtualbox
exit
========================================================================
sudo minikube delete
sudo minikube start --vm-driver=virtualbox
😄  minikube v1.9.0 on Ubuntu 18.04
✨  Using the virtualbox driver based on user configuration

>>❗  'virtualbox' driver reported an issue: /usr/bin/VBoxManage list hostinfo failed:

>>💡  Suggestion: Install the latest version of VirtualBox
>>📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

>>🛑  The "virtualbox" driver should not be used with root privileges.
>>💡  **_If you are running minikube within a VM, consider using --driver=none:_**
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
========================================================================

**Comment by RomanNikitenko** [comment]
Sometimes I see the same error. Restarting resolves issue for me

![chectl_error](https://user-images.githubusercontent.com/5676062/79307347-6dac7380-7eff-11ea-8f8c-2f94892df735.png)

**Comment by hari1992-web** [comment]
> Sometimes I see the same error. Restarting resolves issue for me

Its not working for me i also tried restarted  but nothing will be happened same issue 
![Screenshot from 2020-04-16 13-19-15](https://user-images.githubusercontent.com/62592574/79430438-8f345a80-7fe6-11ea-99d5-ea5aa13f64e6.png)

**Comment by tolusha** [comment]
Regarding `vm-driver=none`
```
[11:14:48] tolusha@fractal ~ $ sudo kubectl logs cert-manager-cainjector-6659d6844d-djncd -n cert-manager
I0521 08:13:26.415847       1 start.go:82] starting ca-injector v0.12.0 (revision 0e384f5d0)
E0521 08:13:27.434799       1 manager.go:238] cert-manager/controller-runtime/manager "msg"="Failed to get API Group-Resources" "error"="Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: connect: no route to host"  
F0521 08:13:27.434854       1 start.go:142] error creating core-only manager: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: connect: no route to host
``````

**Comment by CannyDuck** [comment]
I get the same error. Eclipse Che pod bootstrap fails starting.

I see the following errors in the log. Please help me to get it run up.

```
 [ERROR] [o.a.c.c.C.[.[localhost].[/api] 175]  - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: https://keycloak-che.192.168.99.100.nip.io/auth/realms/che/.well-known/openid-configuration
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:71)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.class(KeycloakSettings.java:54)
  while locating org.eclipse.che.multiuser.keycloak.server.KeycloakSettings
    for the 1st parameter of org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.<init>(KeycloakServiceClient.java:73)
  at org.eclipse.che.multiuser.keycloak.server.KeycloakServiceClient.class(KeycloakServiceClient.java:66)

Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching keycloak-che.192.168.99.100.nip.io found.
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:96)
	... 45 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching keycloak-che.192.168.99.100.nip.io found.
	at java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)
	at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 64 more
```

**Comment by redeagle84** [comment]
After all this time its still don't work, install this tool from zero is like send a rocket to moon.

Here are awesome alternatives to this complicated locked software that is EclipseChe: 

https://github.com/styfle/awesome-online-ide
