### ISSUE TITLE
Developer Use Case: Ease super dev mode with existing IDEs

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#1655]
super-dev mode is not working out of the box on all IDEs.
While with Intellij it’s mainly working, with Eclipse IDE the super dev mode configuration needs manual steps and download some jars.
1. Option 1 : add maven dependency so that required jars are available in the maven repository, add run configuration ?
2. Option 2 : Che in Che or Che in Codenvy : add super dev mode / development extension plugin

**Comment by vparfonov** [comment]
@benoitf can you explain more detail about Option 1.

**Comment by benoitf** [comment]
On Eclipse, people were required to add some jars
https://www.eclipse.org/che/docs/plugins/setup-che-workspace/#setup-run-configuration
gwt-codeserver.jar and gwt-server.jar
It would be nice if user can find these jars in m2 repository

**Comment by benoitf** [comment]
and in Eclipse, we can store Run configuration inside the project, so ppl that checkout che could already find a ready to use run GWT configuration

**Comment by ghost** [comment]
This has been labeled as P1 but looks like the issue has been forgotten ever since. 

@benoitf do you propose to include some hidden dir with Eclipse meta info so that when Che is imported, SDM config gets imported as well?

**Comment by TylerJewell** [comment]
I dropped the severity tag since it is not a bug anymore.

**Comment by benoitf** [comment]
@eivantsov yes some Eclipse IDE metadata (that could include modules, formatter options, SDM config, java remote debug  launchers, etc)

**Comment by skabashnyuk** [comment]
won't fix
