### ISSUE TITLE
Install and use SVN in eclipse che

### ISSUE THREAD

**Issue by deepthiseshabattar** [eclipse-che/che#16550]
How can we install SVN plugin and use it in eclipse che? Are there any clear steps? Found this https://github.com/eclipse/che-plugin-svn link but could not understand how to install. Kindly help.

**Comment by azatsarynnyy** [comment]
Hello @deepthiseshabattar 
The plugin you referred to is for Che 5 version which isn't maintained anymore.

The current version is Che 7. To get familiar with it, I'd recommend starting with [Introduction to Eclipse Che](https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/).

In short, with the new Workspace and Plugin models, Eclipse Che 7 functionality can be extended with VS Code extensions packed as Che Plugins.
So, it's possible to run some SVN extension for VS Code, e.g. https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm in Eclipse Che 7.

Here's a nice doc how a Workspace can be customized with the Plugins https://www.eclipse.org/che/docs/che-7/customizing-developer-environments/

Also, feel free to ask your questions in Eclipse Che Mattermost channel https://mattermost.eclipse.org/eclipse/channels/eclipse-che
