### ISSUE TITLE
Editor tabs are not restored after refreshing browser tab

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#16563]
### Describe the bug
Editor tabs are not restored after refreshing browser tab. **It reproduces only for first web page refreshing.**

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create and start workspace from any devfile.
2. Wait for ```Theia IDE``` is ready to use and open any file in the Editor.
3. Refresh browser page and check that opened file tab is restored.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screencast
![screencast-che-sskroy-che-rc apps ocp311 crw-2020 04 03-18_11_14](https://user-images.githubusercontent.com/7760565/78670370-4db8f680-78e6-11ea-90be-354b8dbe5631.gif)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by nickboldt** [comment]
Given no news, assuming slipped to 7.13.

**Comment by SkorikSergey** [comment]
Not reproduced in 7.14.0.

**Comment by SkorikSergey** [comment]
This issue starts to reproduce in ```Che 7.19.0-SNAPSHOT``` on September 17th.

**Comment by vzhukovskii** [comment]
Could be related: https://github.com/eclipse/che-theia/commit/bb61966635aea68bf12a1cf994e387de8757171f

**Comment by azatsarynnyy** [comment]
It should be already fixed by https://github.com/eclipse/che-theia/pull/864 that reverts https://github.com/eclipse/che-theia/pull/848 which re-introduced this bug.
