### ISSUE TITLE
Developer Use Case:  Allow to generate Eclipse Che package with all required dependencies with Docker

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#1656]
It should be “easy” for the user and no need to read documentation.
For now it requires some tools to be installed on the environment (like patch for maven-patch-plugin, bower or npm for dashboard, etc)
1. Option 1: build could be done with a docker container
2. Option 2: For Che in Codenvy or Che in Che we need this docker image as well

**Comment by TylerJewell** [comment]
I think this is basically done.
