### ISSUE TITLE
How to set the docker_privilege_mode in che7?

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#16569]
I remember that docker_privilege_mode was available in che 6 version.
It was possible by setting the `CHE_DOCKER_PRIVILEGED = true` in the `che.env` file.

Is it possible to run the workspace by setting docker_privilege_mode on che7 like the che6 version?
If so, what should I do?

**Comment by tolusha** [comment]
@wonjooncho 
It isn't possible anymore.

What is the problem you need to solve?

**Comment by wonjooncho** [comment]
@tolusha I am trying to use btctl inside a workspace.
It requires privilege mode.

Is there any other way to solve this issue?
