### ISSUE TITLE
[Selenium] Run java selenium tests against Eclipse Che deployed to OCP with Openshift OAuth option enabled

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#16570]
### Is your task related to a problem? Please describe.
We need to run all java selenium tests against Eclipse Che deployed to OCP with Openshift OAuth option enabled.

**Comment by nickboldt** [comment]
Slip to 7.18

**Comment by nickboldt** [comment]
This P1 issue has been untended for 29 days. Is it done? in progress?

**Comment by SkorikSergey** [comment]
This issue duplicate of https://github.com/eclipse/che/issues/17125.
