### ISSUE TITLE
spec.Server.WorkspaceNamespaceDefault is ignored in case of OpenShift with oAuth enabled

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16574]
## Summary
In the custom resource we have `spec.Server.WorkspaceNamespaceDefault` which is default namespace for user's workspaces [1] but it is completely ignored [2] in case of OpenShift infrastructure with oAuth enabled. I am wondering if it is a real bug and by design. 

## Relevant information

[1] https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml#L454
[2] https://github.com/eclipse/che-operator/blob/master/pkg/deploy/che_configmap.go#L96

/cc @nickboldt @l0rd @davidfestal

**Comment by davidfestal** [comment]
I assume it is a bug.

In case of `openshift-auth` enabled, `<username>-<flavor>` should be the default if nothing is mentioned in the CR, but we should still take the CR field into account.

**Comment by dmytro-ndp** [comment]
Related changes are [here](https://github.com/eclipse/che-operator/pull/136).
