### ISSUE TITLE
Welcome page has incorrect style for scroll on Firefox 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#16573]
### Describe the bug
Please see the screenshot 

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a workspace on Firefox
2. Use dark theme
3. Pay attention on scroll for Welcome page 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![welcome_page](https://user-images.githubusercontent.com/5676062/78771621-266f3180-7999-11ea-8efe-56cbed1b1001.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
related upstream issue https://github.com/eclipse-theia/theia/issues/5040

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
thanks, Artem!

I thought that the problem on `che-theia` side, that's  why I created the issue for `che`.
But `theia` has the same problem...
