### ISSUE TITLE
Wrong memory limit leads to Java-mongo and Java-mysql workspace failure

### ISSUE THREAD

**Issue by mingfang** [eclipse-che/che#16572]
https://github.com/eclipse/che-devfile-registry/blob/9dfe7de0cbd23c8bc89a1c565833396e25118695/devfiles/java-mongo/devfile.yaml#L15

`memoryLimit: 1280MiB` should be `memoryLimit: 1280Mi`

**Comment by ibuziuk** [comment]
@sleshchenko this affects Hosted Che after update - https://github.com/eclipse/che/issues/16583

**Comment by sleshchenko** [comment]
Fixed by https://github.com/eclipse/che-devfile-registry/pull/224 :tada:
