### ISSUE TITLE
Some yamls in che-workspace-operator deploy dir are out of date

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16584]
### Is your task related to a problem? Please describe.
Some of the generated files in [`./deploy`](https://github.com/che-incubator/che-workspace-operator/tree/master/deploy) are out of date and need to be re-generated.

- `deploy/crds/example-crs`: out of date with current spec; missing component example cr
- `deploy/flatten`: out of date, needs to be regenerated via `operator-courier`, I get a traceback when running it due to file names.

I've tried poking at it but couldn't get all commands to work correctly.

**Comment by sleshchenko** [comment]
OLM part should be covered in a dedicated issue for OLM https://github.com/eclipse/che/issues/16311

**Comment by sleshchenko** [comment]
I believe it's already kind of fixed

**Comment by amisevsk** [comment]
Yeah, I should've closed this awhile ago when I removed all the OLM-related files from that repo in preparation for web-terminal-operator.
