### ISSUE TITLE
Che 7.11.1 Release

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16585]
### List of pending issues / PRs

- [x] Restart workspace fail (OpenShift Dedicated, minishift) #16512 / PR to `7.11.x` https://github.com/eclipse/che/pull/16586
- [x] java + mysql / java + mongo devfiles are failing on Hosted Che with quota issue #16583 (already part of `7.11.x` of che-devfile-registry and promoted to prod)
- [x] Use 20.0.0-java8 tag of centos-quarkus-maven https://github.com/eclipse/che-devfile-registry/pull/220
- [x] Che4z-1.2.0 https://github.com/eclipse/che-devfile-registry/pull/204

Technically we need for Hosted Che only `7.11.1` artifacts for #16512, but if we want to proceed with a full release cycle this would also work

**Comment by ibuziuk** [comment]
@skabashnyuk will you be able to cherry-pick the fix for  #16512 to `7.11.x` ?

**Comment by sunix** [comment]
Hello, could we include these ones ?
- https://github.com/eclipse/che-devfile-registry/pull/220
- https://github.com/eclipse/che-devfile-registry/pull/204

**Comment by ibuziuk** [comment]
@sunix I would say yes if you cherry-pick the PRs to `7.11.x` - feel free to update the list in the description

**Comment by sunix** [comment]
added to the list and done cherry-picks on 7.11.x branch
https://github.com/eclipse/che-devfile-registry/commits/7.11.x

**Comment by ibuziuk** [comment]
@nickboldt @mkuznyetsov going to close this issue since this week we are waitng for 7.12.0 and there is no urgent need in the 7.11.1
