### ISSUE TITLE
[Che 6.x] Workspace fail to start if the project folder contains many files.

### ISSUE THREAD

**Issue by dorinburcea** [eclipse-che/che#16590]
CHE version 6.19.X but new version have same issue
Scenario is when inside the /projects directory there is a project with many files inside the node_module

I checked the installer sh script for installer  "org.eclipse.che.ws-agent" and remover recursive "**chown -R /projects**" command

It seems there maybe is another recursive applied to /projects directory inside of Workspace API binaries, which makes the WS API takes too long to start. 

How can I understand if there is such a thing in the binary code and that I may fix it?

Many thanks for the support

**Comment by vparfonov** [comment]
@dorinburcea Can you provide more information about infrastructure?   
What runtime do you use? Is it local installation or cloud?

**Comment by vparfonov** [comment]
@dorinburcea BWT, we  recommend switching to our last version like 7.11.0 you will get much better support in this case

**Comment by tolusha** [comment]
@dorinburcea  6.x is not supported anymore

**Comment by dorinburcea** [comment]
> @dorinburcea Can you provide more information about infrastructure?
> What runtime do you use? Is it local installation or cloud?

Hello @tolusha thanks for answer,

The Workspace API time out is independent of CHE version in my case.
My che infra is in cloud and the project volume Is in glusterfs (i tried before with AWS efs was worse for thousands of small files )
It is known the NFS IO filesystem operations is slow when thousands of small files, like those in the node projects in node_module, have to be write, delete or change attributes.

For this reason I am asking where I can find the workspace API source code (that is downloaded and executed when workspace starts) . I suspect there is recursie permissions that is done on the /projects directory that takes too long and the tumour is reached before.
