### ISSUE TITLE
Impossible to set an array as value for preferences via devfile

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#16594]
### Describe the bug
For now devfile supports only string, number or boolean as a value of preferences in components. Some preferences require having an array of strings as a value, for example  `go.lintFlags` https://github.com/microsoft/vscode-go#linter.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Add preferences into devfile in the dashboard
```yaml
    preferences:
      go.lintFlags: ["--fast"]
```
2. Try to save changes
4. See an error
```log
Devfile schema validation failed. Error: (/components/0/preferences/go.lintFlags):The value must be of type in [boolean, number, string], but actual type is array.
```

### Expected behavior
Expected array of string as a value for a preference.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by metlos** [comment]
This has been discovered while investigating https://github.com/redhat-developer/codeready-workspaces/pull/263.
