### ISSUE TITLE
Workspace creation via factory url does not consume `che.workspace.persist_volumes.default`

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#16596]
### Describe the bug

A workspace created via https://che.openshift.io/f?url=https://github.com/eclipse/che has the Temporary Storage toggle switched off while it should be switched on in accordance to `che.workspace.persist_volumes.default` provided by server.

### Steps to reproduce

1. Open this link https://che.openshift.io/f?url=https://github.com/eclipse/che
2. Wait until workspace is created and open workspace details
3. See temporary storage state.

### Expected behavior

Temporary Storage toggle should be switched on and workspace devfile should be populated with 
```yaml
attributes:
  persistVolumes: 'false'
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: che.openshift.io

**Comment by sleshchenko** [comment]
@ibuziuk Could you confirm that temporary storage is expected by default for factory flow when the value is not specified in the Devfile explicitly?
