### ISSUE TITLE
Che 7 running on GCP - Classpath is Imcomplete

### ISSUE THREAD

**Issue by Les-Linux** [eclipse-che/che#16591]
I have a new installation of Che 7 running on GCP. I deployed a java gradle project from the stack and imported a simple java project from GIT too.

When I run the imported project from GIT the following is thrown: 

1. cannot read property 'scheme' of undefined
2. Classpath is incomplete

I have also added two new sections for gradle build/run for my imported GIt project. Am I missing something obvious here?

Les

**Comment by vparfonov** [comment]
I guess it's from language area also can be related to installation on GCP. It looks like a P1.

**Comment by Les-Linux** [comment]
Is there anything else I can provide in order to assist with this issue?

**Comment by Les-Linux** [comment]
I had a quick look at logs but couldn’t see anything obvious 🙁.
