### ISSUE TITLE
Nightly Che tests failing on workspace deletion

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16592]
### Describe the bug
Nightly Che tests are deleting workspace using UI. The behavior of this test step was recently changed because of changes in a UI. Now, the test is sometimes failing on error:
```
  Stopping and deleting the workspace
    Delete workspace:
TimeoutError: Waiting for element to be located By(css selector, #add-item-button)
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Expected behavior
The deletion of a workspace works correctly in Che, the test should not fail on that.

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/79195944-6f0e6b00-7e2f-11ea-8382-6e7d3a325265.png)

**Comment by ibuziuk** [comment]
@Katka92 is it the reason of failures for Hosted Che update - https://github.com/redhat-developer/rh-che/pull/1861

**Comment by Katka92** [comment]
@ibuziuk No, it is not that case. From a first glance, I don't know why Hosted Che update tests are failing. I need more time to investigate. I'll try to take a look at that today.

**Comment by Katka92** [comment]
The fix was merged. I'll wait for test results and if the problem is solved, I'll close this issue tomorrow.

**Comment by Katka92** [comment]
Tests are passing. Issue was fixed.
