### ISSUE TITLE
API for updating project files

### ISSUE THREAD

**Issue by varunkumar** [eclipse-che/che#166]
I started a Che instance on my Mac. I am able to use IDE and all its basic features. However, I see that APIs exposed don't match with the [documented ones](https://eclipse-che.readme.io/docs/rest-api). I couldn't find any API for updating project files. Endpoint mentioned in the docs also seems to be incorrect.

Output: http://localhost:8080/api
{"rootResources":[{"path":"project-template","regex":"/project-template(/._)?","fqn":"org.eclipse.che.api.project.server.ProjectTemplateService"},{"path":"event-bus","regex":"/event-bus(/._)?","fqn":"org.eclipse.che.api.core.notification.WSocketEventBusServer"},{"path":"/workspace","regex":"/workspace(/._)?","fqn":"org.eclipse.che.api.workspace.server.WorkspaceService"},{"path":"/machine","regex":"/machine(/._)?","fqn":"org.eclipse.che.api.machine.server.MachineService"},{"path":"/profile","regex":"/profile(/._)?","fqn":"org.eclipse.che.api.user.server.UserProfileService"},{"path":"/async/{ws-id}","regex":"/async/([^/]+?)(/._)?","fqn":"org.everrest.core.impl.async.AsynchronousJobService"},{"path":"/recipe","regex":"/recipe(/._)?","fqn":"org.eclipse.che.api.machine.server.recipe.RecipeService"},{"path":"oauth","regex":"/oauth(/._)?","fqn":"org.eclipse.che.security.oauth.OAuthAuthenticationService"},{"path":"/auth","regex":"/auth(/._)?","fqn":"org.eclipse.che.api.auth.AuthenticationService"},{"path":"/user","regex":"/user(/._)?","fqn":"org.eclipse.che.api.user.server.UserService"},{"path":"/ssh","regex":"/ssh(/._)?","fqn":"org.eclipse.che.api.ssh.server.SshService"},{"path":"/","regex":"(/._)?","fqn":"org.eclipse.che.api.core.rest.ApiInfoService"}]}

Is there any configuration to be enabled to get all APIs?

**Comment by benoitf** [comment]
Hello, documentation is referring 3.x stable release while latest version (master branch) is for 4.x beta version

What is the operation you wanted for 'updating project files' ?
there is some config change on project there 
https://github.com/codenvy/che-core/blob/master/platform-api/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java

and https://github.com/codenvy/che-core/blob/master/platform-api/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java

(project API is available with che at /api/ext/project/<workspace-id>/

**Comment by varunkumar** [comment]
I am looking for updateFile operation in ProjectService. What is the endpoint for that? http://localhost:8080/che/api/ext/project doesn't seem to be available.

**Comment by benoitf** [comment]
project API is at http://localhost:8080/api/ext/project/<workspace-id>
something like http://localhost:8080/api/ext/project/workspace0ci732agk6euloik

In order to know workspace-id
http://localhost:8080/api/workspace

**Comment by TylerJewell** [comment]
Hi. We now embed Swagger service in the Che server and export swagger configuration from any workspace agents. We are updating the how-tos on using the REST API this week, but in the meantime you can use the embedded Swagger utilities to navigate the (fairly well documented) REST APIs.

https://eclipse-che.readme.io/docs/rest-api
