### ISSUE TITLE
che-plugin-registry won't start

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#16605]
### Describe the bug
che-plugin-registry won't start. 

### Che version

 - [x] nightly

### Steps to reproduce
1. install che with `chectl server:start --platform=minikube --installer=helm`
1. plugin registry will timeout and won't start
1. other pods starts ok

### Expected behavior
plugin registry should start

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer
       - [x] Linux

### che-plugin-registry logs

```
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 15 06:44:58.288288 2020] [mpm_event:notice] [pid 1:tid 139964788927816] AH00489: Apache/2.4.43 (Unix) configured -- resuming normal operations
[Wed Apr 15 06:44:58.288329 2020] [core:notice] [pid 1:tid 139964788927816] AH00094: Command line: 'httpd -D FOREGROUND'
[Wed Apr 15 06:45:54.637415 2020] [mpm_event:notice] [pid 1:tid 139964788927816] AH00492: caught SIGWINCH, shutting down gracefully
```
### Additional context

most probably caused by this PR https://github.com/eclipse/che-plugin-registry/pull/444

**Comment by rhopp** [comment]
Yep... seeing that in our nightly jobs as well. (in fact you were just a few minutes quicker in creating this issue :-D)

**Comment by benoitf** [comment]
I've pushed previous tag to `:nightly` tag it will unblock users

**Comment by benoitf** [comment]
fixed by https://github.com/eclipse/che-plugin-registry/pull/445

**Comment by sparkoo** [comment]
works now, thanks
