### ISSUE TITLE
Using or create a bare Ubuntu 18.04 workspace.

### ISSUE THREAD

**Issue by ultrafab** [eclipse-che/che#16602]
Hello, i'm probably (surely) missing the point, but i'm trying to describe my situation:
I'm spawn a workspace (Java8 / Spring) to test writing some Micronaut services.

Micronaut CLI requires SDKMAN, SDKMAN requires unzip/zip, unzip/zip requires a root account to install, i miss the root password.

Using Docker i'll probably start a Ubuntu vanilla container and then install any needed tool to understand how to proceed at first.

What's the correct way to approach this kind of situations with Che? I read about custom devfiles but i was unable to find a sample of a base empty image.

Thanks!

**Comment by metlos** [comment]
I would probably approach this by building a custom docker image with all the tools you require, e.g. write a `Dockerfile` based on Ubuntu and install into it all the tooling you require. You would then push this docker image somewhere and in your devfile reference this image as a `dockerimage` component. If you then start a terminal in this component, you will have all the tooling available.
