### ISSUE TITLE
Can not start a terminal 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#16601]
### Describe the bug
Sometimes I can not start a terminal.
I can not reproduce it permanently.
Please see a screenshot.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create and start a workspace from dashboard
2. Go to `Terminal` -> `Open Terminal in specific container`

Expected behavior: list of containers is displayed to select the corresponding container for starting a terminal.

Actual behavior: a terminal widget is displayed, but a terminal is not started. There is an error in browser console.
```
Uncaught (in promise) Error: Failed to start terminal. Cause: Error: Couldn't parse params
    at n.<anonymous> (theia.0fdc8ed05bd4da17210d.js:1)
    at theia.0fdc8ed05bd4da17210d.js:1
    at Object.throw (theia.0fdc8ed05bd4da17210d.js:1)
    at s (theia.0fdc8ed05bd4da17210d.js:1)
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![terminal_error](https://user-images.githubusercontent.com/5676062/79259972-39509d00-7e96-11ea-8c2a-a852bf8d8475.gif)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by metlos** [comment]
Possibly related to https://github.com/eclipse/che/issues/15870 ?

**Comment by sparkoo** [comment]
@RomanNikitenko can you please write here the error message from the browser console you've mentioned ?

**Comment by RomanNikitenko** [comment]
@sparkoo 
Done!

**Comment by tolusha** [comment]
@RomanNikitenko 
Do you still reproduce the issue?

**Comment by RomanNikitenko** [comment]
@tolusha 
I tried a few times today and could not reproduce it.

So, maybe the problem is gone...
Please feel free to close the issue if you can not reproduce it.

**Comment by vparfonov** [comment]
Reproduced on my side, with OSD and `che-theia:next`

`Error: Failed to start terminal. Cause: Error: Couldn't parse params`

**Comment by vitaliy-guliy** [comment]
My terminal become not working after appearing the message, that the new process is listening 4444 port.
![Screenshot from 2020-04-20 15-00-46](https://user-images.githubusercontent.com/1655894/79875959-145aad80-83f3-11ea-88f4-6c0a58a7377c.png)

**Comment by amisevsk** [comment]
> My terminal become not working after appearing the message, that the new process is listening 4444 port.

That indicates that the machine exec container restarted -- do you see any restarts in the workspace pod?

**Comment by vitaliy-guliy** [comment]
I didn't check the logs, will do it next time when I face the error.

**Comment by AndrienkoAleksandr** [comment]
OK, Stable steps to reproduce:
1. Open terminal widget.
2. Launch some `not endless` che task.
3.  When task done click on the task widget and type some character. 
4. Await few seconds. Select terminal widget and try to type something.

Actual result: opened terminal stopped work.

@RomanNikitenko thanks for reporting issue. @vitaliy-guliy thanks a lot too, your screenshot is relevant too.

@vparfonov Sorry, about this one https://github.com/eclipse/che/issues/16601#issuecomment-617080360 I am not sure. I didn't faced with such behavior.
