### ISSUE TITLE
Unable to remove SSH key when including invalid characters

### ISSUE THREAD

**Issue by Blacktiger** [eclipse-che/che#1661]
In che, a user can create a VCS SSH key that cannot be deleted.

**Reproduction Steps:**
1. Open Preferences > SSH > VCS
2. Click Generate Key or Upload Key
3. Enter a hostname including the protocol (https://github.com or similar)
4. Try to delete the key

**Expected behavior:**

There are two possibilities here:
- The host name of the key is not accepted if it contains bad characters (colon, slash, etc)
- The key is properly deleted

**Observed behavior:**

The key is not deleted.

**Che version:**    All versions up to 4.4

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

This looks to me like a simple mismatch between user expectations and system requirements. The field for the hostname is called "Host (w/o port)". For me at least, because it mentions that the port should be excluded - that causes me to think of urls with the protocol on the front even though that is not what the field is for. Perhaps the field should be called Hostname instead of host to be less confusing. Regardless, the hostname should probably be rejected if it was entered with invalid characters since the rest api doesn't allow using those invalid characters to delete the key later.

**Comment by ddementieva** [comment]
It's a known bug. Thanks for reporting it.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-816

**Comment by raafaar** [comment]
I'm having the same issue. While it is solved, **Is there a way to manually delete the key?** For example, using the CLI. I'm asking because I need to sync my project and it seems to fail because of the existing wrong hostname.

**Comment by ddementieva** [comment]
@raafaar This is API problem, not purely the client one.

**Comment by raafaar** [comment]
@ddementieva the problem for me is that although I deleted and recreated the workspace, (using the same recipe) the key is still there. I need to find a way to delete it. And that is because I can't connect to the git service and may be is for the wrong key.

**Comment by ghost** [comment]
@Blacktiger if you go to `/storage` you will find a handful of jsons, `preferences.json` being one of them. You may try deleting this key directly there.

**Comment by bmicklea** [comment]
@skabashnyuk can you take this in the next sprint please?

**Comment by michealharrington** [comment]
I'm using the hosted eclipse che by red hat and I have run into this issue. I delete all my workspaces and can longer create or run any workspace. It keeps complaining about my bad ssh key. I'm not sure how to get rid of the key.

**Comment by bmicklea** [comment]
@michealharrington can you open a new issue and reference this one please? It's not clear if this issue (which is 3 years old) is at the root of the behaviour you're seeing.
