### ISSUE TITLE
Adapt Che Theia to the latest Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16611]
### Describe the bug

Theia commit https://github.com/eclipse-theia/theia/commit/acfc08656303ba32a28365f2e1e8b8fc7daba32a breaks Che Theia build on CI. See https://ci.centos.org/job/devtools-che-theia-pullrequests-build/275/consoleFull

**Comment by benoitf** [comment]
should be fixed now

**Comment by azatsarynnyy** [comment]
thx @benoitf
