### ISSUE TITLE
[devworkspace] Make workspace operator reuse devworkspace-api

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16626]
### Is your task related to a problem? Please describe.
This issue is about making workspace operator reuse [devworkspace-api](https://github.com/che-incubator/devworkspace-api) instead of having its own API objects and CRDs(at least it's related to Workspace and WorkspaceRouting CRDs).

There is already some work done https://github.com/che-incubator/che-workspace-operator/commits/Support-devworkspace-api

**Comment by amisevsk** [comment]
Opened issue https://github.com/devfile/kubernetes-api/issues/44 to support the current status fields we use in the operator.

Will we replace our current workspace CR with devworkspace, or work to support both (e.g. v1/workspace, v2/workspace)?

**Comment by sleshchenko** [comment]
Should be already done in https://github.com/che-incubator/che-workspace-operator/pull/92
if something is missing - feel free to reopen the issue and add items or fill in a new issue
