### ISSUE TITLE
Opening che-doc repository in Che

### ISSUE THREAD

**Issue by mp21-org** [eclipse-che/che#16624]
## Summary

When trying to open the che-doc repository with the devfile provided by the project + adding the git repository to it, I don't get a workspace that I can run the jekyll serve command in.

## Relevant information

It seems that the CMD line of the image quay.io/eclipse/che-docs:latest automatically starts jekyll in a path /che-docs/ which is not where Che normally locates the projects. Hence, when I open the webbrowser on that container, I get an empty directory listing.

I would propose to change the CMD line in the Dockerfile to:
`CMD ["tail", "-f", "/dev/null"]`

And let the IDE handle the starting of jekyll within the correct workingdir.

**Comment by amisevsk** [comment]
I can reproduce various issues on che.openshift.io (using the factory URL: https://che.openshift.io/f?url=https://github.com/eclipse/che-docs):

- `che-docs-livereload-server` endpoint does not work, showing only the plaintext message `This port only serves livereload.js over HTTP.` (endpoints are all https, as of 
- `che-docs-web-server` shows an "index of /" page.
- `serve che-docs` command fails with 
	```
	#<Thread:0x000055d9a9ce4f90@/usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/serve/live_reload_reactor.rb:41 run> terminated with exception (report_on_exception is true):
	Traceback (most recent call last):
		5: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
		4: from /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
		3: from /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
		2: from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/commands/serve/live_reload_reactor.rb:47:in `block (2 levels) in start'
		1: from /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_server'
	/usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
	jekyll 3.8.5 | Error:  no acceptor (port is in use or requires root privileges)
	```

I tried changing the command (by adding to the devfile) as suggested but it did not resolve the problem in my case

**Comment by themr0c** [comment]
This is fixed now.
