### ISSUE TITLE
[workspace-controller] Set up CI for che-api-sidecar

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16636]
### Is your task related to a problem? Please describe.
Currently, the workspace operator depends on [che-rest-apis](https://github.com/che-incubator/che-api-sidecar) when running regular Che workspaces. I'm managing 'releases' manually, and the operator refers to images in my docker registry (e.g. `amisevsk/che-rest-apis:latest`).

This makes merging breaking changes to che-rest-apis (e.g. https://github.com/che-incubator/che-api-sidecar/pull/2) complicated, as versioning has to to managed manually.

### Describe the solution you'd like
Set up nightly/release CI for che-rest-apis.

**Comment by sleshchenko** [comment]
This PR introduces built for che-rest-api:next dockerimage https://github.com/che-incubator/che-api-sidecar/pull/3
There is another PR to set up release process but it's not critical https://github.com/eclipse/che/issues/17672
