### ISSUE TITLE
oauth-utils error

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#16630]
### Describe the bug
Every start workspace / page refresh I see the error in browser console:
```
oauth-utils.ts:38 Uncaught TypeError: e.data.startsWith is not a function
    at oauth-utils.ts:38
(anonymous) @ oauth-utils.ts:38
postMessage (async)
postMessage @ VM1969 host.js:46
```
I think we should investigate what's the problem and fix it.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. See logs in browser console when a workspace is started 
2. Try to refresh a page

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![errors](https://user-images.githubusercontent.com/5676062/79450285-6e233800-7fed-11ea-91b9-6f5f7e4f3562.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
@RomanNikitenko Does it happen after Theia is opened? I wonder if you supposed it's dashboard/wsloader/theia part?

**Comment by RomanNikitenko** [comment]
I guess the error comes from [the event](https://github.com/eclipse/che-theia/blob/287faa2566b8d7b9da8c335c580d8956054dfe22/extensions/eclipse-che-theia-plugin-ext/src/browser/oauth-utils.ts#L38)
So, maybe @vinokurig knows more about this problem.

@vinokurig could you take a look?

**Comment by vinokurig** [comment]
Yes, will take a look ASAP
