### ISSUE TITLE
[new UD] Implement the 'create a workspace with URL' flow

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#16644]
### Is your task related to a problem? Please describe.

1. We need to implement  'create a workspace with URL' flow for the new UD. 
 {CHE  host}f?url=(Github repo or direct URL to devfile YAML content)
For example
```
 http://che-che.192.168.99.100.nip.io/f?url=https://raw.githubusercontent.com/eclipse/che-docs/master/devfile.yaml
```
2. Revise an existing page for this flow from the current UD.
### Describe the solution you'd like

An implementation should cover all functionality as we have in the current UD.

### Additional context

A screenshot from the existing UD:
![Screenshot from 2020-04-17 15-28-42](https://user-images.githubusercontent.com/6310786/79569372-26211580-80c0-11ea-81bc-11f38c04dfa5.png)

**Comment by sleshchenko** [comment]
The provided UI mockup
![Screenshot_20201001_163342](https://user-images.githubusercontent.com/5887312/94816020-e5198500-0403-11eb-99a8-2ff0e0dfefd6.png)

**Comment by parvathyvr** [comment]
Hi @olexii4 and @sleshchenko , I had worked with Sunil to provide the spacing specs of workspace details/loading pages. Sunil also updated the 'Starting' icon in the loading page-You can refer the new design of the above UI mockup for loading in this Marvel link and the associated spacing details( Page 5 & 6)  https://marvelapp.com/prototype/6ba6g03/screen/73494294
