### ISSUE TITLE
[devworkpace] Add an ability to generate some secrets for workspace

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16647]
### Is your enhancement related to a problem? Please describe.
Currently, the reconcile loop works in the following way:
1. evaluate objects according to status of the devfile (no communication with cluster)
2. flush them onto cluster

And if the devfile is not changed then the first part should always have the same result.
We already have some piece which must be regenerated for each workspace, or even on each workspace start - it's cookies_secret for oauth-proxy container https://github.com/che-incubator/che-workspace-operator/blob/master/pkg/controller/workspacerouting/solvers/oauth_proxy_container.go#L85

Also, oauthclient is comming.

### Describe the solution 1
1. evaluate objects according to status of the devfile. Generate some values with rand (no communication with cluster)
2. flush them onto cluster, but before flushing - override randomized values with cluster ones

### Describe the solution 2
1. evaluate objects according to status of the devfile. Generate some values with rand if missing on the cluster or fill in with the already existing
2. flush them onto cluster

**Comment by JPinkney** [comment]
If I'm understanding everything in this issue correctly:
Can't we do something like generate the rand values (for cookie secret for example), store them in a secret then use [SyncObjects](https://github.com/che-incubator/che-workspace-operator/blob/master/pkg/controller/workspace/provision/object.go#L56) which only creates the object if it doesn't exist on the cluster?

It looks like it satisfies
> Generate some values with rand if missing on the cluster or fill in with the already existing

If we do those changes in the workspace routing controller before creating the oauth_proxy_container we can re-use the cookie-secret as an env var when creating the oauth proxy container. That way cookie-secret is randomly generated.

I'm not sure if I'm missing anything though

@sleshchenko @amisevsk

**Comment by amisevsk** [comment]
@JPinkney That approach makes sense to me, I think the main concern is that another user could read the secret, but I also don't see a better way to implement this.

**Comment by JPinkney** [comment]
Just for added reference this is what that would look like: https://github.com/che-incubator/che-workspace-operator/compare/master...JPinkney:create-secrets?expand=1

**Comment by sleshchenko** [comment]
The propose solution looks good to me, just one comment about shared diff, probably you plan to change it:
now generated secret has listed hardcoded values, I think it would be better if we provide a common approach to generate-get any secret item by a unique key provided by client: `secretStore.provision('openshift-oauth-cookie-secret')`, `secretStore.provision('oauth-client-secret')`

**Comment by sleshchenko** [comment]
Theoretically, that's still important but at this point we are not set that we'll continue with openshift-oauth and there is no clear usage for that feature. So, postponing a bit until it finds it real usage again.

**Comment by amisevsk** [comment]
Isn't this feature implemented by https://github.com/devfile/devworkspace-operator/pull/159 (and its follow-up PR to do the same for https ingresses on k8s)?

**Comment by sleshchenko** [comment]
This feature is about generating some secrets like for OauthClient secret that will have the same value after reconcile if it's not removed https://github.com/devfile/devworkspace-operator/pull/68

**Comment by sleshchenko** [comment]
is moved on DWO repo https://github.com/devfile/devworkspace-operator/issues/434
