### ISSUE TITLE
[new UD] Implement Overview of the Workspace Details page

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#16645]
### Is your task related to a problem? Please describe.
Workspace Details Overview page is not implemented.

### Describe the solution you'd like

Implement Workspace Details Overview page.

### Additional context

DESIRED DESIGNS
![image1](https://user-images.githubusercontent.com/5887312/94409314-acb54500-017e-11eb-9855-9f8fa7152acc.png)

Edit workspace name
![image9](https://user-images.githubusercontent.com/5887312/94409429-d2dae500-017e-11eb-8d20-0a1f94253543.png)
![image3](https://user-images.githubusercontent.com/5887312/94409388-c48cc900-017e-11eb-8130-c8190f00a73a.png)
![image6](https://user-images.githubusercontent.com/5887312/94409391-c5255f80-017e-11eb-8384-ae5ddc01e0fa.png)

Change storage type
![image8](https://user-images.githubusercontent.com/5887312/94409461-dff7d400-017e-11eb-8bea-603de950c5e2.png)
![image15](https://user-images.githubusercontent.com/5887312/94409466-e0906a80-017e-11eb-8794-3f40c90dd071.png)

Depends on https://github.com/eclipse/che/issues/17899

**Comment by parvathyvr** [comment]
@olexii4 Some of the screens of workspace details attached in the GH issue has been updated (eg:editing workspace names has been changed to inline edit)....Please refer the updated design screens under 'Workspace details' section in this [design doc](https://docs.google.com/document/d/1Ao0mfcqA41dv_h8SVgsVV7sPbO57opSuplL0331_xwM/edit?ts=5f185cf5#heading=h.1pw0yt6uj4i6).If you have any questions about the design changes,please let me know.
CC @sleshchenko

**Comment by sleshchenko** [comment]
Should be implemented in https://github.com/che-incubator/che-dashboard-next/pull/68
