### ISSUE TITLE
[new UD] Develop layout of Dashboard Next 

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#16643]
### Is your task related to a problem? Please describe.

Develop layouts for the left-navigation bar, header and footer. 
### Describe the solution you'd like

Current layouts for existing UD vs next UD are not consistent. We should revise them in general. 

#### Existing UD screenshots:
footer
<img src="https://user-images.githubusercontent.com/6310786/79582926-1c55dd00-80d5-11ea-8b56-a53cc66b2c6f.png" width="300">
header
<img src="https://user-images.githubusercontent.com/6310786/79582865-07794980-80d5-11ea-98ee-d7f37bd2129f.png" width="300">
left-navigation bar
<img src="https://user-images.githubusercontent.com/6310786/79584381-fb8e8700-80d6-11ea-83c4-012e3bfc2a19.png" width="100">
all 
<img src="https://user-images.githubusercontent.com/6310786/79584371-f92c2d00-80d6-11ea-9d86-0ea8b20aa977.png" width="300">

#### New UD  screenshots:

left-navigation bar
<img src="https://user-images.githubusercontent.com/6310786/79581987-d5b3b300-80d3-11ea-865d-47c23a2305d4.png" width="100">
header
<img src="https://user-images.githubusercontent.com/6310786/79579822-c4b57280-80d0-11ea-98c0-86a0b79e0f90.png" width="300">
all
<img src="https://user-images.githubusercontent.com/6310786/79584611-4c05e480-80d7-11ea-8649-7904f8cfb79f.png" width="300">

**Comment by sleshchenko** [comment]
new layout design ![Screenshot_20200917_120954](https://user-images.githubusercontent.com/5887312/93450491-b74e1f80-f8de-11ea-8437-68bed5a961fb.png)

**Comment by sleshchenko** [comment]
The new layout design is mostly implemented. Some minor stuff should be fixed as dedicated issues.
