### ISSUE TITLE
Finalize kubernetes-image-puller operator and contribute it to OperatorHub

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16642]
### Is your task related to a problem? Please describe.
Initial implementation of the kubernetes-image-puller has been done as part of the https://github.com/eclipse/che/issues/16067 / https://github.com/che-incubator/kubernetes-image-puller-operator

The next step would be adding OLM support and contributing the operator to https://operatorhub.io/

**Comment by tomgeorge** [comment]
Opened https://github.com/operator-framework/community-operators/pulls/1661 and https://github.com/operator-framework/community-operators/pulls/1662

**Comment by ibuziuk** [comment]
@tomgeorge Great job! I believe the issue can be closed \o/
