### ISSUE TITLE
Che Theia: Move all 'build' stuff from make-release.sh to build.sh

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16654]
### Is your task related to a problem? Please describe.

It would be great to move all 'build' related code from Che Theia's make-release.sh to build.sh

### Additional context

@benoitf suggestion:
```
script should do 'release' stuff and move all 'build' stuff to build.sh script

because we could want to do custom builds by using nice stuff of this script but it's not related to making releases
```

**Comment by benoitf** [comment]
FYI https://github.com/che-incubator/chectl/blob/e747a60e2f46a39f38a739e10d9c7a5410fed2e2/make-release.sh#L29-L36
