### ISSUE TITLE
Make Che Theia release script working on macOS

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16653]
### Is your task related to a problem? Please describe.

It would be great to make Che Theia release [script](https://github.com/eclipse/che-theia/blob/master/make-release.sh) working on macOS as well.

### Additional context

Reported by @benoitf 
```
sed: -i may not be used with stdin
sed: -i may not be used with stdin
sed: 1: "./extensions/eclipse-ch ...": invalid command code .
sed: 1: "./plugins/github-auth-p ...": invalid command code .
sed: -i may not be used with stdin
sed: -i may not be used with stdin
sed: -i may not be used with stdin
```

**Comment by benoitf** [comment]
FYI https://github.com/che-incubator/chectl/blob/e747a60e2f46a39f38a739e10d9c7a5410fed2e2/make-release.sh#L29-L36
