### ISSUE TITLE
Provide quickstart for bare metal k8s?

### ISSUE THREAD

**Issue by adriendelsalle** [eclipse-che/che#16668]
### Is your enhancement related to a problem? Please describe.
There is currently no quick-start documentation for bare metal k8s. The only supported local kube deployments at https://www.eclipse.org/che/docs/che-7/running-che-locally/ are test-like kube deployments: minikube/minishift/codeready/docker.

### Describe the solution you'd like
Define a policy of what are the kube deployments tutorials maintained in this repo to support Che deployment.
See the how [JupyterHub](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/593) handled this question.

### Additional context
I have tested Che on a local kube deployed using kubespray and I would like to share this experience with a tutorial since it offers more scalability than minikube/etc.
I'm wondering how to contribute: PR on this repo, provide link to a tuto hosted in my account, other.

Thanks!

**Comment by sparkoo** [comment]
@adriendelsalle https://github.com/eclipse/che-docs is probably repo for this. There is  **quick-starts** category https://www.eclipse.org/che/docs/che-7/che-quick-starts/

Just create a PR there, even draft one, and discuss the details in the PR itself.

**Comment by adriendelsalle** [comment]
Thanks @sparkoo !
Could you please transfer this issue in the che-docs project?

**Comment by sparkoo** [comment]
@adriendelsalle we track all Che issues here so this is the correct place for the issue.

**Comment by sparkoo** [comment]
@adriendelsalle and this would be very valuable contribution, so thank you for doing this!

**Comment by adriendelsalle** [comment]
Hi @sparkoo !

I have written an article about using Che on a bare metal cluster with Kubespray.
It does not well integrate with the documentation since the `quick-starts` are at this time a bunch of cloud-hosted solutions and a *running Che locally* article with multiple sections focusing on a single-node test/personal dev cluster. 

I think we could distinguish `quick-starts` on a *cloud-hosted* infrastructure from ones on a *self-hosted* infrastructure, which is not necessarily a *local* single-node infra.

Do you think I can propose in the same PR on che-docs repo this re-ordering or it would feel better to do it in a separate PR?

**Comment by sparkoo** [comment]
@adriendelsalle I'm not sure, please ask our docs guys at mattermost https://mattermost.eclipse.org/eclipse/channels/che-docs 
cc: @themr0c @rkratky @MichalMaler @boczkowska

**Comment by l0rd** [comment]
- public cloud: AWS, GCP, Azure
- private cloud: Kubernetes with kubespray, OpenShift 3, OpenShift 4
- local: minikube, kind, minishift, codeready containers, docker for desktop, microK8s

@adriendelsalle is that what you have in mind?

**Comment by adriendelsalle** [comment]
Thank you @l0rd !

Yes it's almost that. In think `on-premise` better suites the second and last cases:
- it's often more a `private-cluster` than a `private-cloud`
  - solutions such as OpenShift or kube with Kubespray are tooling capable of `production capable` clusters. It's not `production grade` or `production ready` since you still can build single node or not HA clusters with them if you want
- `single-node only` better than `local`: you can deploy and access these clusters remotely
  - we could aldo have warnings about running single node only for testing/personal use, not for organizations or developer teams

OpenShift Dedicated (=`hosted Che` in the current doc) and OpenShift Developer Perspective should maybe also in the public cloud category?

It gives multiple `quick-starts`:
- `with a cloud provider` or `on a public cloud`: AWS, GCP, Azure, OpenShift Dedicated, OpenShift Developer Perspective
- `on-premise`:
  - `single-node only`: minikube, kind, minishift, codeready containers, docker for desktop, microK8s
  - `production capable` : Kubernetes with kubespray, OpenShift 3, OpenShift 4

What do you think of that?

**Comment by l0rd** [comment]
I would focus more on the distinction of these 3 options:
- run Che on a local laptop or desktop machine
- run Che on an intranet or private network 
- run Che on a public cloud service

Hosted Che is NOT OpenShift Dedicated. Hosted Che is a SaaS. It's a managed instance of Che for users to try out Che without the need to install it and manage it.

**Comment by adriendelsalle** [comment]
Thanks for the explanations!

It's ok, let's do that! I've made a PR for the kubernetes with Kubespray article, would you like to first review this part or continue the PR with refactoring?

**Comment by l0rd** [comment]
Sounds good

**Comment by adriendelsalle** [comment]
@l0rd sorry I didn't understood if you prefer:
- review and close this [PR about kube with Kubespray article](https://github.com/eclipse/che-docs/pull/1252) and create a new one for refactoring
- extend the opened [PR about kube with Kubespray article](https://github.com/eclipse/che-docs/pull/1252) with refactoring

Thanks

**Comment by l0rd** [comment]
@adriendelsalle sorry. I think it's better if you do that in 2 separate steps, it's easier for review. You can do that in 2 PRs or can also use the same PR with 2 separate commits. It's up to you.

**Comment by adriendelsalle** [comment]
No problem thank you @l0rd !
I will wait for this first PR to be reviewed and merged then I will open another one.

**Comment by adriendelsalle** [comment]
Resolved with this [PR](https://github.com/eclipse/che-docs/pull/1252) on the Che docs repo

**Comment by adriendelsalle** [comment]
Refactoring on quickstarts was made in these 2 PRs: https://github.com/eclipse/che-docs/pull/1265 and https://github.com/eclipse/che-docs/pull/1330
