### ISSUE TITLE
CloudShell Happy Path Test

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16667]
### Is your enhancement related to a problem? Please describe.

Implement a CloudShell "happy path" e2e test that deploys the operator, creates a cloud-shell devworkspace, inject the user token, use kubectl (or oc) and is scaled to zero after a period of inactivity.

Part of Epic https://github.com/eclipse/che/issues/15434

**Comment by sleshchenko** [comment]
It can be closed since https://github.com/devfile/devworkspace-operator/pull/90 is merged.
Other improvements will be made out of the scope of this issue
