### ISSUE TITLE
facing this issue 

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16660]
![Screenshot from 2020-04-18 16-24-44](https://user-images.githubusercontent.com/62592574/79636384-e2e4a680-8194-11ea-9b29-6641a815c8e3.png)

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [x] other: please specify

**Comment by hari1992-web** [comment]
any body know thanks  in advance

**Comment by tolusha** [comment]
@hari1992-web 
Pls update the template to provide more detials

**Comment by ericwill** [comment]
Closing as a duplicate, let's use #16664.
