### ISSUE TITLE
Unable to open newly created workspaces

### ISSUE THREAD

**Issue by traugdor** [eclipse-che/che#1666]
I just updated to the newest version of Che available for release. I downloaded the unsigned .zip so I could `curl` and `unzip` it on my headless server over ssh. I copied everything from the .zip into my existing che directory which wiped out all my projects. That's not why I'm here. When I create my workspaces with the same names as the ones I had, I cannot open them.

**Reproduction Steps:**
1. Downloaded Che
2. Unzipped it into existing Che directory
3. Booted Che and attempted to recreate workspaces and projects.

**Expected behavior:**

Empty workspace with new and empty projects.

**Observed behavior:**

....this: 

![image](https://cloud.githubusercontent.com/assets/6344355/16606420/7d7796ce-42fd-11e6-89e8-06e0cf9e7a16.png)

**Che version:**    [4.4.0]  
**OS and version:** [Ubuntu Server Xenial 16.04]  
**Docker version:** [1.11.2]  
**Che install:**    [server (zip)]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Server Log Output:**

![image](https://cloud.githubusercontent.com/assets/6344355/16606412/6e8ec736-42fd-11e6-824c-62326efa3500.png)

**Web Browser Console Output:**

![image](https://cloud.githubusercontent.com/assets/6344355/16606491/04f01298-42fe-11e6-8765-bb767dcbe9d0.png)

**Comment by ghost** [comment]
@traugdor when updating Che, you probably deleted local storage with recipes while the old workspace need it.
Another thing you may want to try is to clear browser cache or try it in an incognito window. We had some changes in workspace URL formats.

Do you start a workspace from Dashboard?

**Comment by traugdor** [comment]
That seems to have fixed it. That also explains the lack of errors in my program output window.

Thanks. Now to recreate my workspace and projects.
