### ISSUE TITLE
Che-Theia UI components should not mention Eclipse Theia but Eclipse Che

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16677]
### Describe the bug
In many places in the Eclipse Che-Theia UI components, Theia is mentionned. But users would expect to see Eclipse Che as the "product name".

### Che version

 - [x] latest
 - [x] nightly
 - [x] 7.11.0

### Screenshots
![image](https://user-images.githubusercontent.com/650571/79776507-26c2e180-8336-11ea-931b-5739eb7e02f1.png)

![image](https://user-images.githubusercontent.com/650571/79776472-16126b80-8336-11ea-85f8-53a541d74df9.png)

![image](https://user-images.githubusercontent.com/650571/79776335-e1061900-8335-11ea-8df7-d34f2fae1cd6.png)

https://github.com/eclipse-theia/theia/blob/33590a9a8fc9899fdd0f0ed57cb3ea4871adf6e1/packages/core/src/node/application-server.ts#L34-L42

https://github.com/eclipse-theia/theia/blob/da4154be95b22029677c439086840f08a4975cbe/packages/plugin-ext/src/plugin/env.ts#L31

https://github.com/redhat-developer/vscode-quarkus/blob/5b9fdb6a4e1c95dcbf6cac3b4a0d2f208da41eb2/src/webviews/WelcomeWebview.ts#L55

**Comment by tsmaeder** [comment]
The code references you give are theia or vs code extensions source code, not che-theia. @sunix what are you suggesting concretely?

**Comment by benoitf** [comment]
This is me who gave the reference links, this is to show from where comes the application's name and how to override it in che-theia. (BTW we can't provide a link inside che-theia as we don't override)

- one is for extension product name
- one is for plugin's env.appName

**Comment by tsmaeder** [comment]
@benoitf does upstream Theia support branding to override the product name? Otherwise, this could be a long, uphill battle ☹️

**Comment by benoitf** [comment]
@tsmaeder yes for extension it's already there,
for plugin it could be nice if we could reuse same name that product name but even if it's not approved/possible we can override constant on our own.
