### ISSUE TITLE
Modify che url 

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#16670]
Hi all, currently the url to open che needs to be like `https://che-che.mydomain.com`.
Instead of the above url, if I would like the url to be like `https://myapp.mydomain.com`, what is the best way to accomplish this?

Please note that `serverStrategy = "multi-host"`.

Pls refer to the file `deploy/kubernetes/helm/che/templates/_hostHelper.tpl`.

Can the following line in the template be customized to achieve that ? :
`{{- printf "che-%s.%s" .Release.Namespace .Values.global.ingressDomain }}`

Changing the above line to:
`{{- printf "helloWorld.%s" .Values.global.ingressDomain }}` ? will it work ?

Do we have any (security or networking or cluster or any other) issues if we change it like shown above? 

Thanks in advance for your help.

**Comment by svkr2k** [comment]
In file `deploy/kubernetes/helm/che/templates/_hostHelper.tpl` changing host template to `{{- printf "helloWorld.%s" .Values.global.ingressDomain }}` seems to work fine.
Are there any known issues (either technical or license)? Has anyone tried this ?

**Comment by sleshchenko** [comment]
> In file deploy/kubernetes/helm/che/templates/_hostHelper.tpl changing host template to {{- printf "helloWorld.%s" .Values.global.ingressDomain }} seems to work fine.
Are there any known issues (either technical or license)? Has anyone tried this ?

the only technical issue I have in mind - you're not able to deploy multiple Che instances on that cluster, but I believe it's not critical for you at all. So, feel free to use it if it works for you fine.

**Comment by tolusha** [comment]
@svkr2k 
Fixed by https://github.com/eclipse/che/pull/17538/commits
