### ISSUE TITLE
E2E selenium Git SSH flow tests failed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16678]
### Describe the bug
E2E selenium Git SSH flow tests failed on [nightly testing Jenkins job](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1614/consoleFull):
![screenshot-Change_commit_and_push (1)](https://user-images.githubusercontent.com/1197777/79838602-f02faa00-83bb-11ea-8f90-f536b36f2143.png)

<details>
 <summary>Git SSH tests log</summary>
 <pre>
04:36:25 Starting ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}) on port 19531
04:36:25 Only local connections are allowed.
04:36:25 Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
04:36:26           ▼ DriverHelper.navigateToUrl http://che-che.10.0.102.126.nip.io/dashboard/#/ide/admin/checkGeneraringSsh
04:36:26 01:36:25.788 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
04:36:26 01:36:25.835 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 2f881851844c9142491c6bcf14030ac4 (org.openqa.selenium.chrome.ChromeDriverService)
04:36:26 [1587346586.061][SEVERE]: Timed out receiving message from renderer: 0.100
04:36:26 [1587346586.164][SEVERE]: Timed out receiving message from renderer: 0.100
04:36:26 [1587346586.361][SEVERE]: Timed out receiving message from renderer: 0.100
04:36:26 [1587346586.463][SEVERE]: Timed out receiving message from renderer: 0.100
04:36:27 [1587346586.565][SEVERE]: Timed out receiving message from renderer: 0.100
04:36:27           ▼ MultiUserLoginPage.login
04:36:27           ▼ CheLoginPage.waitEclipseCheLoginFormPage
04:36:28 [1587346587.805][SEVERE]: Timed out receiving message from renderer: 0.100
04:36:28           ▼ CheLoginPage.inputUserNameEclipseCheLoginPage username: "admin"
04:36:29           ▼ CheLoginPage.inputPaswordEclipseCheLoginPage password: "admin"
04:36:29           ▼ CheLoginPage.clickEclipseCheLoginButton
04:36:30 [1587346589.744][SEVERE]: Timed out receiving message from renderer: 0.100
04:36:30           ▼ Ide.waitWorkspaceAndIde
04:36:30           ▼ Ide.waitAndSwitchToIdeFrame
04:36:32           ▼ Ide.waitIde
04:37:53 [1587346664.766][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346664.953][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346665.055][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346665.158][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346665.285][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346665.388][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346665.490][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346666.631][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346666.734][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346666.836][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346666.938][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.040][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.142][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.244][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.346][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.450][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.553][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.656][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:53 [1587346667.837][SEVERE]: Timed out receiving message from renderer: 0.100
04:37:54           ▼ ProjectTree.openProjectTreeContainer
04:37:54           ▼ Ide.waitRightToolbarButton
04:38:00           ▼ Ide.waitAndClickRightToolbarButton
04:38:00           ▼ ProjectTree.waitProjectTreeContainer
04:38:00     ✓ Login into workspace and open tree container (93788ms)
04:38:00           ▼ TopMenu.selectOption "View"
04:38:00           ▼ TopMenu.clickOnTopMenuButton "View"
04:38:00           ▼ Ide.closeAllNotifications
04:38:00           ▼ NotificationCenter.open
04:38:00           ▼ NotificationCenter.clickIconOnStatusBar
04:38:00           ▼ NotificationCenter.waitOpening
04:38:00           ▼ NotificationCenter.closeAll
04:38:00           ▼ NotificationCenter.clickCloseAllNotificationsButton
04:38:00           ▼ NotificationCenter.waitClearNotificationsList
04:38:00           ▼ TopMenu.clickOnSubmenuItem "Find Command..."
04:38:00           ▼ QuickOpenContainer.typeAndSelectSuggestion
04:38:01           ▼ QuickOpenContainer.clickOnContainerItem "SSH: generate key pair..."
04:38:01           ▼ QuickOpenContainer.waitContainer
04:38:01           ▼ QuickOpenContainer.waitContainerDisappearance
04:38:02           ▼ Ide.waitNotificationAndClickOnButton "Key pair successfully generated, do you want to view the public key" buttonText: "View"
04:38:02           ▼ Ide.waitNotification "Key pair successfully generated, do you want to view the public key"
04:38:02           ▼ Ide.clickOnNotificationButton "Key pair successfully generated, do you want to view the public key" buttonText: "View"
04:38:02           ▼ Ide.waitNotificationDisappearance "Key pair successfully generated, do you want to view the public key"
04:38:02           ▼ Editor.waitEditorOpened "Untitled-0"
04:38:02           ▼ Editor.waitText "Untitled-0"
04:38:02           ▼ Editor.getEditorVisibleText "Untitled-0"
04:38:02     ✓ Generate a SSH key (2984ms)
04:38:03           ▼ TopMenu.selectOption "View"
04:38:03           ▼ TopMenu.clickOnTopMenuButton "View"
04:38:03           ▼ Ide.closeAllNotifications
04:38:03           ▼ NotificationCenter.open
04:38:03           ▼ NotificationCenter.clickIconOnStatusBar
04:38:03           ▼ NotificationCenter.waitOpening
04:38:03           ▼ NotificationCenter.closeAll
04:38:03           ▼ NotificationCenter.clickCloseAllNotificationsButton
04:38:04           ▼ NotificationCenter.waitClearNotificationsList
04:38:04           ▼ TopMenu.clickOnSubmenuItem "Find Command..."
04:38:04           ▼ QuickOpenContainer.typeAndSelectSuggestion
04:38:04           ▼ QuickOpenContainer.clickOnContainerItem "Git: Clone"
04:38:04           ▼ QuickOpenContainer.waitContainer
04:38:05           ▼ QuickOpenContainer.waitContainerDisappearance
04:38:06           ▼ QuickOpenContainer.typeAndSelectSuggestion
04:38:07           ▼ QuickOpenContainer.clickOnContainerItem "Repository URL (Press 'Enter' to confirm your input or 'Escape' to cancel)"
04:38:07           ▼ QuickOpenContainer.waitContainer
04:38:08           ▼ QuickOpenContainer.waitContainerDisappearance
04:38:08     ✓ Add a SSH key to GitHub side and clone by ssh link (5333ms)
04:38:08           ▼ ProjectTree.expandPathAndOpenFile "Spoon-Knife" filename: README.md
04:38:08           ▼ ProjectTree.expandPath "Spoon-Knife"
04:38:08           ▼ ProjectTree.expandItem "Spoon-Knife"
04:38:08           ▼ ProjectTree.waitItemExpanded "Spoon-Knife"
04:38:08           ▼ ProjectTree.clickOnItem "Spoon-Knife/README.md"
04:38:09           ▼ ProjectTree.waitItemSelected "Spoon-Knife/README.md"
04:38:10           ▼ Editor.waitEditorOpened "README.md"
04:38:10           ▼ Editor.waitTab "README.md"
04:38:10           ▼ Editor.type title: "README.md" text: "1587346687702
04:38:10           "
04:38:10           ▼ Editor.selectTab "README.md"
04:38:10           ▼ Ide.closeAllNotifications
04:38:10           ▼ NotificationCenter.open
04:38:10           ▼ NotificationCenter.clickIconOnStatusBar
04:38:10           ▼ NotificationCenter.waitOpening
04:38:10           ▼ NotificationCenter.closeAll
04:38:10           ▼ NotificationCenter.clickCloseAllNotificationsButton
04:38:10           ▼ NotificationCenter.waitClearNotificationsList
04:38:10           ▼ Editor.waitTab "README.md"
04:38:10           ▼ Editor.clickOnTab "README.md"
04:38:10           ▼ Ide.closeAllNotifications
04:38:10           ▼ NotificationCenter.open
04:38:10           ▼ NotificationCenter.clickIconOnStatusBar
04:38:10           ▼ NotificationCenter.waitOpening
04:38:11           ▼ NotificationCenter.closeAll
04:38:11           ▼ NotificationCenter.clickCloseAllNotificationsButton
04:38:11           ▼ NotificationCenter.waitClearNotificationsList
04:38:11           ▼ Editor.waitTabFocused "README.md"
04:38:11           ▼ Editor.moveCursorToLineAndChar title: "README.md" line: "1" char: "1"
04:38:11           ▼ Editor.performKeyCombination title: "README.md" text: ""
04:38:11           ▼ Editor.performKeyCombination title: "README.md" text: "1587346687702
04:38:11           "
04:38:12           ▼ GitPlugin.openGitPluginContainer
04:38:12           ▼ GitPlugin.waitViewOfContainer
04:38:12           ▼ GitPlugin.waitChangedFileInChagesList
04:38:14           ▼ GitPlugin.stageAllChanges
04:38:14           ▼ GitPlugin.waitStagedFileInStagedChanges
04:38:14           ▼ GitPlugin.waitChangedFileInChagesList
04:38:15           ▼ GitPlugin.typeCommitMessage
04:38:15           ▼ GitPlugin.waitCommitMessageTextArea
04:38:16           ▼ GitPlugin.commitFromScmView
04:38:16           ▼ GitPlugin.selectCommandInMoreActionsMenu
04:38:16           ▼ GitPlugin.clickOnMoreActions
04:43:22     1) Change commit and push
04:43:22 
04:43:22 
04:43:22   3 passing (7m)
04:43:22   1 failing
04:43:22 
04:43:22   1) Git with ssh workflow
04:43:22        Change commit and push:
04:43:22      TimeoutError: Waiting for element to be located By(xpath, //li[@data-command]/div[text()='Push'])
04:43:22 Wait timed out after 300008ms
04:43:22       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
04:43:22       at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
04:43:22       at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
04:43:22       at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
04:43:22       at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
04:43:22       at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
04:43:22       at <anonymous>
04:43:22       at process._tickCallback (internal/process/next_tick.js:188:7)
 </pre>
</details>

Test command:
> docker run --shm-size=1g --net=host --ipc=host -p 5920:5920 -e TS_SELENIUM_DEFAULT_TIMEOUT=300000 -e TS_SELENIUM_LOAD_PAGE_TIMEOUT=420000 -e TS_SELENIUM_WORKSPACE_STATUS_POLLING=20000 -e TS_SELENIUM_BASE_URL=http://che-che.10.0.102.126.nip.io -e TS_SELENIUM_LOG_LEVEL=DEBUG -e TS_SELENIUM_MULTIUSER=true -e TS_SELENIUM_USERNAME=admin -e TS_SELENIUM_PASSWORD=admin -e TEST_SUITE=test-git-ssh -e TS_GITHUB_TEST_REPO_ACCESS_TOKEN=*** -e TS_GITHUB_TEST_REPO=chepullreq4/Spoon-Knife -e NODE_TLS_REJECT_UNAUTHORIZED=0 -e NODE_TLS_REJECT_UNAUTHORIZED=0 -v /mnt/hudson_workspace/workspace/basic-MultiUser-Che-check-e2e-tests-against-k8s/tests/e2e:/tmp/e2e:Z quay.io/eclipse/che-e2e:nightly

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify

**Comment by musienko-maxim** [comment]
Was fixed in the https://github.com/eclipse/che/pull/16979
