### ISSUE TITLE
Copy/paste not working in command configuration dialog (Chrome only)

### ISSUE THREAD

**Issue by mathiasconradt** [eclipse-che/che#1667]
In Chrome (51.0.2704.103 (64-bit)) on Mac OS X its not possible to copy the value from the command configuration dialog fields (i.e. "command line" field) into the clipboard via Command+c or otherwise in order to paste it again.

Pressing Command+c does not copy the value into the clipboard.

It works fine in Firefox, does not work in Chrome. Haven't tested it in Chrome on Windows yet.

Screenshot:

![Screensho](https://snag.gy/KY0JVr.jpg)

(Originally posted at https://github.com/codenvy/codenvy/issues/354#issuecomment-230658396)

**Comment by ghost** [comment]
Confirmed. Will be scheduled in one of the upcoming sprints.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-1457

**Comment by Anid4u2c** [comment]
Ah... use Ctrl+Shift+V
https://superuser.com/questions/421463/why-does-ctrl-v-not-paste-in-bash-linux-shell?answertab=votes#tab-top

**Comment by TylerJewell** [comment]
Yes, it's in a branch and just merged.  I think it will appear in next week's 5.5 release.

See this whole epic that has been engineered over the past 6 months.
https://github.com/eclipse/che/issues/2681

**Comment by musienko-maxim** [comment]
In version 5.6.0 the Command widget was removed
