### ISSUE TITLE
Migrate workspace startup jobs and mount volume jobs to Prometheus

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16671]
### Is your task related to a problem? Please describe.
This task is a reminder for us to finish the migration once SD-App-SRE finishes migration over to OSD 4

### Describe the solution you'd like
All our jobs should be using Prometheus pushgateway to store any long-term metrics

### Describe alternatives you've considered
N/A

### Additional context
Service delivery team is working on updating OSIO deployment to new OSD4 clusters. As part of this migration the team will be deploying Prometheus instances, setting up prometheus push gateway and we will be given service account access using app-interface.

**Comment by Katka92** [comment]
Also, the route tests should push data to the new Prometheus instance.

**Comment by Katka92** [comment]
As there is still no update to OSD4. We decided to use the Prometheus on a dev cluster for now.

**Comment by Katka92** [comment]
After discussing this issue with devs we decided to postpone this issue and wait for OSD4 update.

**Comment by ScrewTSW** [comment]
Due to migration to Devtool Sandbox this feature is no longer required. Closing as won't implement
