### ISSUE TITLE
Opening a project directly through the url

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#16687]
Can che open a project directly from github i.e., does che support accepting a github project url to open a project,something similar to `https://che-che.mydomain.com/api/project/<github repo url>` ? I believe that it is not supported currently? Thanks for your guidance.

In my case, there is only one stack and would like che to automatically open a workspace with the specified github project if the user types in the url `https://che-che.mydomain.com/api/project/<github repo url>` in a browser. 

When the user enters that url che should open the login screen, and after user login, it should create a workspace and open the project automatically.

Can anyone provide details on how that can be accomplished? Thanks in advance for the help.

**Comment by vzhukovskii** [comment]
Hello @svkr2k! You should be able to open project from git using the following url factory: `https://che-che.mydomain.com/f?url=<github_repo_url>`

**Comment by svkr2k** [comment]
Thank you very much !

**Comment by vzhukovskii** [comment]
If you have any other questions, feel free to open new issue. Going to close this one as solution was found.
