### ISSUE TITLE
Investigate an ability for workspace SA rolebindings depending on components

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16686]
### Is your task related to a problem? Please describe.
Now we create Workspace SA and minimal rolebindings workspace may needs:
- view cluster role;
- create execs;

They're basically rolebindings needed for che-machine-exec plugin from Theia and CloudShell with basic workspace routing (no OAuth Proxy, is really only development case).

I wonder if components are able to define needed permissions and then they would be provisioned depending on the configured components.

**Comment by amisevsk** [comment]
One issue with components requesting additional privileges is that it would open up a fairly large surface for privilege escalation; it would mean that the workspace controller is responsible for ensuring that a user is not gaining permissions by creating a custom component.

**Comment by amisevsk** [comment]
PR https://github.com/che-incubator/che-workspace-operator/pull/64 limits the scope of both the controller permissions and workspace SA permissions. Currently, the workspace serviceaccount has the role
```
  Resources               Non-Resource URLs  Resource Names  Verbs
  ---------               -----------------  --------------  -----
  pods/exec               []                 []              [create]
  pods                    []                 []              [get list watch]
  deployments.apps        []                 []              [get list watch]
  replicasets.apps        []                 []              [get list watch]
  deployments.extensions  []                 []              [get list watch]
  replicasets.extensions  []                 []              [get list watch]
```
This could be further restricted to refer to the relevant objects more directly (e.g. get only the workspace deployment), potentially.

The SA binding is still namespace wide, which means a workspace can view all other deployments in its namespace.

The main change in the PR above on the controller side is that we no longer grant the cluster-view permission. This limits what permissions can even be granted to a workspace (as you cannot grant permissions you do not have).
