### ISSUE TITLE
Setup Che in TLS mode docs page has invalid links

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#16682]
The original issue is created by @olberger [here](https://github.com/che-incubator/chectl/issues/654) in chectl repo:

> The instrutions provided by chectl point to  https://www.eclipse.org/che/docs/che-7/setup-che-in-tls-mode-with-self-signed-certificate/ which is now 404.

>I believed this could be changed to https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/
Hth

**Comment by mmorhun** [comment]
This is really nasty bug as users who want to install Eclipse Che might not find pre-requirements instructions by the broken links.

**Comment by sleshchenko** [comment]
The same issue was fixed on Dashboard side https://github.com/eclipse/che-dashboard/pull/20/files
It's important to make sure that docs URLs are not changed often without fixing in other places or at least announcements

**Comment by rkratky** [comment]
@mmorhun, what are _"The instrutions provided by chectl"_? Can they be updated? If not, I'll set up a redirect in the docs, so that the old address will work again.

**Comment by olberger** [comment]
@rkratky cf. https://github.com/che-incubator/chectl/search?q=https%3A%2F%2Fwww.eclipse.org%2Fche%2Fdocs%2Fche-7%2Fsetup-che-in-tls-mode-with-self-signed-certificate%2F&unscoped_q=https%3A%2F%2Fwww.eclipse.org%2Fche%2Fdocs%2Fche-7%2Fsetup-che-in-tls-mode-with-self-signed-certificate%2F (which is why I filed the issue in that repo in the first place ;)

**Comment by mmorhun** [comment]
@rkratky we will fix the link, it's easy

**Comment by rkratky** [comment]
@mmorhun, ok. Let me know in case a docs redirect would still be needed. It's also easy :)

**Comment by mmorhun** [comment]
I've merged the links fix into `chectl`.
