### ISSUE TITLE
Quarkus should default to Java 11

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#16697]
Quarkus since v1.3 defaults to Java 11 but the quarkus setup by Che is Java 8. 

Quarkus does support Java 8 but we do want to move people to use Java 11 by default.

**Comment by benoitf** [comment]
fix is there https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml#L15

**Comment by ericwill** [comment]
Fixed in https://github.com/eclipse/che-devfile-registry/pull/269
