### ISSUE TITLE
extremely easy to kick of 2-4 different short cuts dev mode

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#16699]
When double clicking the short cuts I end up with 2 sometimes 3 tabs saying its starting dev mode.

Only one wins (it seems) but it is super confusing which one is the real one.

expecation: only *one* tab shows up when you double click on a short cut.

**Comment by benoitf** [comment]
@maxandersen could you indicate which shortcut ? or a screenshot and against which version of che ? is it on che.openshift.io ?

**Comment by maxandersen** [comment]
yes, che.openshift.io

these "shortcuts" are what I double click on - and you might say you shouldn't double click but since it takes several seconds for it to react I end up doing that anyway even if I just click once everytime to see a reaction.

![2020-04-22_17-33-47](https://user-images.githubusercontent.com/54129/80002058-6f59d680-84bf-11ea-846e-58f051c27b25.png)

**Comment by azatsarynnyy** [comment]
should be fixed by https://github.com/eclipse/che/issues/15277
