### ISSUE TITLE
Move to RHEL 8 version of postgresql-96 ? 

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16695]
### Is your enhancement related to a problem? Please describe.

Today we use `registry.redhat.io/rhscl/postgresql-96-rhel7:1-47` and `centos/postgresql-96-centos7:9.6` in CRW and Che, respectively.

Yet there's a RHEL 8 version which would be faster, more stable, etc. because its' RHEL 8 vs. 7.

https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhel8/postgresql-96

Could we use that instead? I mean Centos ~ RHEL

But... here's the catch...

we would need to tweak build processes to allow us to use authenticated registry.redhat.io instead of the unauthenticated one.

https://access.redhat.com/containers/?tab=images&get-method=unauthenticated#/registry.access.redhat.com/rhel8/postgresql-96

Is that a non-starter? Or would the community be open to moving to RHEL8-based postgresql-96? 

Sure it's one extra hoop to jump through when setting up Che, but authentication is free... and then we get all the RHEL 8 benefits.

**Comment by nickboldt** [comment]
What info would you like?

**Comment by skabashnyuk** [comment]
@nickboldt what if we reuse the same strategy as we have for brokers (https://github.com/eclipse/che-plugin-broker/tree/master/build/artifacts) and jwt-proxy (https://github.com/eclipse/che-jwtproxy/tree/master/build/dockerfiles) images. 
Community or alpine based images for upstream and rhel.* based images for downstream?

**Comment by sparkoo** [comment]
imho that auth wall is big no-no for upstream. I'd like to see RHEL/CentOS/Fedora based image as well, but it must be accessible to community without any manual actions
