### ISSUE TITLE
default  app in quarkus does not have application.properties

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#16700]
`application.properties` are expected to be there in default quarkus app.

how is this app actually generated ?

**Comment by davidfestal** [comment]
Could precise a bit what you mean by 
> how is this app actually generated ?

If you're using the Quarkus Che stack, I assume it uses a project specified in the devfile.
Maybe the file is simply missing from the related project ?

**Comment by JPinkney** [comment]
It looks like the [project specified](https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started) in the [devfile](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml#L10) indeed does not have application.properties

**Comment by maxandersen** [comment]
any plans on allowing to use a command or even remote service to get a more dynamic uptodate version ?

**Comment by maxandersen** [comment]
i've opened https://github.com/quarkusio/quarkus-quickstarts/pull/539 as it does make sense to have it in the quickstarts - especially when che uses it as defaults.
