### ISSUE TITLE
❗[MANUAL ACTION REQUIRED] Please add local Eclipse Che CA certificate into your browser: /root/cheCA.crt

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16708]
hi iam facing this error any body know please 
Thanks for advance 
![Screenshot from 2020-04-22 16-07-23](https://user-images.githubusercontent.com/62592574/79972397-84c90380-84b3-11ea-8892-036ad10c309b.png)

![Screenshot from 2020-04-22 16-07-23](https://user-images.githubusercontent.com/62592574/79972312-6236ea80-84b3-11ea-968c-8978dcc943c6.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by hari1992-web** [comment]
THIS ISSUE IS FACING SO MANY DAYS

**Comment by sleshchenko** [comment]
@hari1992-web Are you able to provide Network tab screenshot? There should be failed keycloak script, what is the error?

**Comment by hari1992-web** [comment]
![Screenshot from 2020-04-22 16-19-51](https://user-images.githubusercontent.com/62592574/79973411-27ce4d00-84b5-11ea-8b2d-2ae1b0a67f8a.png)

**Comment by hari1992-web** [comment]
![Screenshot from 2020-04-22 16-21-46](https://user-images.githubusercontent.com/62592574/79973564-68c66180-84b5-11ea-9909-531d8274567c.png)

**Comment by hari1992-web** [comment]
Iam facing this issues

**Comment by hari1992-web** [comment]
![Screenshot from 2020-04-22 16-28-35](https://user-images.githubusercontent.com/62592574/79974103-5567c600-84b6-11ea-8726-e6aa69689d66.png)

**Comment by hari1992-web** [comment]
its showing ca certificates installation but iam umable to install in browser

**Comment by sleshchenko** [comment]
> its showing ca certificates installation but iam umable to install in browser

Could you elaborate more which issues do you have with importing this CA into browser?

**Comment by tolusha** [comment]
@hari1992-web 
pls read the following doc
https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-che-with-tls_installing-che-in-tls-mode-with-self-signed-certificates

**Comment by hari1992-web** [comment]
> > its showing ca certificates installation but iam umable to install in browser
> 
> Could you elaborate more which issues do you have with importing this CA into browser?

Thanku so much

**Comment by hari1992-web** [comment]
> @hari1992-web
> pls read the following doc
> https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-che-with-tls_installing-che-in-tls-mode-with-self-signed-certificates

Working fine  Thanks

**Comment by sleshchenko** [comment]
@tolusha If that documentation helped to solve the issue, should not it be mentioned by chectl after deploying Che?

**Comment by hari1992-web** [comment]
ok
