### ISSUE TITLE
quarkus dev:mode should not be refered to as development server

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#16701]
The shortcut panel talks about "Start Development Server"  - is that a generic term in che ? 

for quarkus I would have expected it to be called developer mode or just devmode for short as you don't necessarily get a server (i.e. when developing a command mode app)

**Comment by benoitf** [comment]
source is there: https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml#L50

so we can define the name you want

**Comment by maxandersen** [comment]
I've opened #229 to fix this and that its jusing `mvn`  instead of safer and uptodate `./mvnw`
