### ISSUE TITLE
[object Object] in Preferences -> ChePlugins 

### ISSUE THREAD

**Issue by ia3andy** [eclipse-che/che#16718]
### Describe the bug
![image](https://user-images.githubusercontent.com/2223984/80001739-02ded780-84bf-11ea-8c6c-e17f5a3ee7b6.png)

### Che version
Che-Theia@62718c1 using Theia@9481af8e

Using che.openshift.io

**Comment by ibuziuk** [comment]
@ericwill @azatsarynnyy  this sounds like upstream issue? any pointers?

**Comment by benoitf** [comment]
related to https://github.com/eclipse/che/issues/16594 ?

**Comment by azatsarynnyy** [comment]
#16594 is more about passing the preferences through a Devfile
This one looks like upstream Theia preferences widget issue https://github.com/eclipse-theia/theia/issues/2698

**Comment by JPinkney** [comment]
Just wanted to add there's also a WIP preferences widget PR on theia side that makes preferences widget to be more VSCode like and shouldn't have this issue: https://github.com/eclipse-theia/theia/pull/7105

**Comment by azatsarynnyy** [comment]
Thanks @JPinkney for the link! Looks like soon Theia will have the same Preferences widget as in VS Code.
We'll keep an eye on it and once the upstream PR is merged we update Che Theia to consume the new widget.

**Comment by azatsarynnyy** [comment]
The upstream PR https://github.com/eclipse-theia/theia/pull/7105 is merged.
Now, Che Theia has the same Preferences widget as in VS Code.
![image](https://user-images.githubusercontent.com/1636395/81200491-b28e6c00-8fcc-11ea-9509-5487b4eee700.png)

It will be released in Che 7.13
