### ISSUE TITLE
Create workspace using a devfile

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#16722]
Hi all, please refer to the web page: https://www.eclipse.org/che/docs/che-7/configuring-a-workspace-using-a-devfile/

The above documentation shows an example of how to override the branch for the project:
```
https://che.openshift.io/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&override.projects.web-java-spring-petclinic.source.branch=1.0.x
```

Question #1: How can I override both location and branch of the project ?
Question #2: Also, do we need to use override for both adding or overriding devfile parameters ?
Question #3: How do we use tag instead of branch?

**Comment by mshaposhnik** [comment]
Hello,
>Question #1: How can I override both location and branch of the project ?
Just use 2 params:
```
&override.projects.web-java-spring-petclinic.source.branch=1.0.x
&override.projects.web-java-spring-petclinic.source.location=http://github.com/.../...
```
>Question #2: Also, do we need to use override for both adding or overriding devfile parameters ?
Yes, both working the same way.

>Question #3: How do we use tag instead of branch?
`override.projects.web-java-spring-petclinic.source.tag=1.0.x` should work.

Let me know if something is not working for you.

**Comment by svkr2k** [comment]
Thank you, @mshaposhnik , I shall try.
