### ISSUE TITLE
Failed to connect to Kubernetes API. E_K8S_API_NO_RESPONSE

### ISSUE THREAD

**Issue by josefredohd** [eclipse-che/che#16734]
I use the command chectl server: start but I get this error, I don't know what to do I'm a beginner in this.
![Captura de pantalla (36)](https://user-images.githubusercontent.com/22134405/80149202-1b0c3080-856b-11ea-871e-f0a0df9cd34e.png)

**Comment by tolusha** [comment]
@josefredohd 
Is `loaded-context` correct?
It points to `localhost`

**Comment by josefredohd** [comment]
@tolusha I do not know

**Comment by ibuziuk** [comment]
@josefredohd please take a looks at the official docs - https://www.eclipse.org/che/docs/che-7/running-che-locally/ and update the description with clear steps to reproduce based on the issue template
