### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16736]
![Screenshot from 2020-04-24 09-26-29](https://user-images.githubusercontent.com/62592574/80173596-f321d900-860d-11ea-83f5-87f61161ad16.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [ ] other: please specify

**Comment by hari1992-web** [comment]
> ![Screenshot from 2020-04-24 09-26-29](https://user-images.githubusercontent.com/62592574/80173596-f321d900-860d-11ea-83f5-87f61161ad16.png)
> 
> ### Describe the bug
> ### Che version
> * [x]  latest
> * [ ]  nightly
> * [ ]  other: please specify
> 
> ### Steps to reproduce
> ### Expected behavior
> ### Runtime
> * [x]  kubernetes (include output of `kubectl version`)
> * [ ]  Openshift (include output of `oc version`)
> * [ ]  minikube (include output of `minikube version` and `kubectl version`)
> * [ ]  minishift (include output of `minishift version` and `oc version`)
> * [ ]  docker-desktop + K8S (include output of `docker version` and `kubectl version`)
> * [ ]  other: (please specify)
> 
> ### Screenshots
> ### Installation method
> * [x]  chectl
> * [ ]  che-operator
> * [ ]  minishift-addon
> * [ ]  I don't know
> 
> ### Environment
> * [ ]  my computer
>   
>   * [ ]  Windows
>   * [x]  Linux
>   * [ ]  macOS
> * [ ]  Cloud
>   
>   * [ ]  Amazon
>   * [ ]  Azure
>   * [ ]  GCE
>   * [x]  other (please specify)
> * [ ]  other: please specify
> 
> ### Eclipse Che Logs
> ### Additional context

Iam facing certificate error

**Comment by tolusha** [comment]
It is not an error.
Pls import the certificate into a browser.

**Comment by hari1992-web** [comment]
whenever I imported ca certificate i am unable to import the certificate

**Comment by hari1992-web** [comment]
Thanks its working fine now
