### ISSUE TITLE
Wrong error message when referencing invalid content

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#16737]
I would like our validation of uri's when referencing a che plugin from a devfile to be less restrictive. Currently, when I try to test an update to an existing che plugin, the following:
```
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/tsmaeder/che-plugin-registry/16728_add_nodedebug2/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml
```
fails with this error message:
```
Error: Failed to start the workspace: "Plugin reference URL 'https://raw.githubusercontent.com/tsmaeder/che-plugin-registry/16728_add_nodedebug2/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml' is invalid."
```
There are two things I think need to be improved here:
1. We should allow this uri: working on a branch of the plugin registry is the normal way of creating PR's. It's helps prevent copy/paste errors if we can just test the new plugin from the branch we will create the PR from
2. If we say the URI is invalide, we need to say what the problem was. I suspect it doesn't like the fact that there is a branch name in that URI ('1628_add_nodedebug2') but there is no way to know for sure.

**Comment by tsmaeder** [comment]
I know that we're using some parts of the plugin uri to populate the plugin metadata, but let's be as permissive as we can beyond that: otherwise we're just putting roadblocks in people's way.

**Comment by benoitf** [comment]
I'm using gist and it works 

looking at your yaml it seems to be invalid
```yaml
- "http://open-vsx.org/api/ms-vscode/node-debug/1.44.2/file/ms-vscode.node-debug-1.44.2.vsix",
```
there is a comma

**Comment by tsmaeder** [comment]
Turns out that what is wrong is indeed an error in the referenced meta.yml. I updated the title of the issue accordingly.

**Comment by tsmaeder** [comment]
The error message is wrong here: it says explicitly the the URI is wrong, when the URI is perfectly fine, but the content that is referenced has a problem.
Additionally, there is no indication of _what_ is wrong in the content. Please fix this error message, I just wasted two hours hunting down the wrong problem.

**Comment by tsmaeder** [comment]
Btw: the offending meta.yml simply referenced a vs code extension from open-vsx.org that did not exist (404 error). Why that is even checked at this point is not clear to me.

**Comment by sleshchenko** [comment]
won't be fixed I belive
