### ISSUE TITLE
Remove the dashboard menu item

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16747]
### Is your enhancement related to a problem? Please describe.
Remove the dashboard menu item and page as:
- it is duplicating to the workspaces page ... more or less
- getting started page is more sexy and useful
- it makes sense to start with "getting started"

To remove:
![image](https://user-images.githubusercontent.com/650571/80277027-96492000-86ec-11ea-8bef-9542bddd8638.png)

**Comment by sleshchenko** [comment]
it's going to be fixed in the scope of #15662. More see https://github.com/eclipse/che/issues/15662#issuecomment-604798409
