### ISSUE TITLE
In the dashboard, have a factory page that shows the last factory being run by the user

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16749]
### Is your enhancement related to a problem? Please describe.

In the dashboard, have a factory page that shows the last factories being run by the user and allow the user to start any of them.

**Comment by ibuziuk** [comment]
IMO `factory` wording should be prohibited in Che 7 (recent devfiles might be a good option)

**Comment by sunix** [comment]
I am closing this one in favor of https://github.com/eclipse/che/issues/16875
