### ISSUE TITLE
che-theia build is downloading electron binary

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#16742]
### Describe the bug
when building che-theia docker images it downloads electron zip file but that's something wrong because we're building browser version.
It's mainly due to the post-install script of electron being a dependency of theia project.

We should workaround that to avoid to download this huge binary
Also this binary is not available on all platforms

Good news, there is a new flag in latest electron releases to avoid the download of this binary.
https://github.com/electron/electron/blob/master/docs/tutorial/installation.md#skip-binary-download

The bad news is that theia is not compliant with these new releases.

**Comment by ibuziuk** [comment]
@benoitf I put P1 since image size affects first workspace startup

**Comment by benoitf** [comment]
already merged
