### ISSUE TITLE
Document how to configure allowed running workspaces count

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16746]
![Screenshot from 2020-04-25 10-45-48](https://user-images.githubusercontent.com/62592574/80271853-f8505800-86e1-11ea-93ac-2b37e7104b17.png)
![Screenshot from 2020-04-25 10-45-48](https://user-images.githubusercontent.com/62592574/80271857-02725680-86e2-11ea-992b-75dc33bd348a.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify

**Comment by skabashnyuk** [comment]
@hari1992-web that is not an error. That is default system behavior. With such configuration, you are only able to run 1 workspace simultaneously.

**Comment by hari1992-web** [comment]
Can i increase that number CHE_LIMITS_USER_WORKSPACES_RUN_COUNT ???

**Comment by hari1992-web** [comment]
i am using only chectl tool , How can i assign where can i assign CHE_LIMITS_USER_WORKSPACES_RUN_COUNT ???

**Comment by hari1992-web** [comment]
But How can I start multiple workspaces on eclipse che 7 ???
Any body knows please help 
Thanks in advance

**Comment by sleshchenko** [comment]
@hari1992-web  the way how you configure it depends on the way you deployed Che:
**Helm**
```
kubectl patch configmap che --patch "{\"spec\":{\"data\":{\"CHE_LIMITS_USER_WORKSPACES_RUN_COUNT\": \"-1\"}}}" --type=merge -n che
kubectl rollout restart deployment/che -n che
```
**Operator:**
```
kubectl patch checluster/eclipse-che --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_LIMITS_USER_WORKSPACES_RUN_COUNT\": \"-1\"}}}}" --type=merge -n che
```

P.S. There is -1 - not limited, but feel free to assign any value.

It must be documented!

**Comment by hari1992-web** [comment]
> @hari1992-web  the way how you configure it depends on the way you deployed Che:
> Helm
> kubectl patch configmap che --patch "{\"spec\":{\"data\":{\"CHE_LIMITS_USER_WORKSPACES_RUN_COUNT\": \"-1\"}}}" --type=merge -n che
> kubectl rollout restart deployment/che -n che
> 
> Operator:
> kubectl patch checluster/eclipse-che --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_LIMITS_USER_WORKSPACES_RUN_COUNT\": \"-1\"}}}}" --type=merge -n che
> 
> P.S. There is -1 - not limited, but feel free to assign any value.
> It must be documented!

Thanku so much Its working fine
