### ISSUE TITLE
Changing shortcuts for che-theia is not persisted

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16753]
### Describe the bug
Changing short cuts for che-theia is not persisted for other workspaces or the same workspace after restarts.

### Che version

 - [x] latest

### Steps to reproduce
In che.openshift.io

1. open the Java stack
2. in Theia menu > `File` > `Settings` > `Open Keyboard Shortcuts` > change the `Format Document` short cut to `ctrlcmd+alt+f`
3. open a Java file, unformat the content and try the short cut:
4. it works .... code is formatted
5. restart the workspace or open new one
6. open a Java file, unformat the content and try the short cut:
7. it doesn't format my code :(

**Comment by ibuziuk** [comment]
@sunix is it Hosted Che specific, or the same story happens in the upstream?

**Comment by sunix** [comment]
I think this is upstread

**Comment by sunix** [comment]
moving to p1 as it is a very annoying issue (having to reset shortcuts 10times a day)

**Comment by sunix** [comment]
I think short cuts should be persisted in the user preferences: any workspaces opened by the same user should have keep the same shortcuts.
