### ISSUE TITLE
Java 17 stack

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16765]
### Is your enhancement related to a problem? Please describe.
Having Java 17 and 11 stacks, in getting started page in the default

edit: 14,15 -> 17

### Describe the solution you'd like
Something close to https://github.com/sunix/record-preview-feature-java15 but with maven available.

This important to let Java developers getting interested into Che and try it ...

**Comment by ibuziuk** [comment]
@ericwill setting P2, feel free to change the severity based on the team priorities

**Comment by ericwill** [comment]
Depends on #17924, we are not creating plugins per Java version any more.

**Comment by sunix** [comment]
@ericwill for Che, i think we should just keep
- the latest LTS: Java 11
- the latest: Java 15 for now, switch to 16
- drop Java 8

**Comment by ericwill** [comment]
> @ericwill for Che, i think we should just keep
> 
>     * the latest LTS: Java 11
> 
>     * the latest: Java 15 for now, switch to 16 once available
> 

I really would like to explore a better way to support new Java versions, like #17924. Creating new sidecars/plugins per Java version is tedious and ends up as a maintenance burden both upstream and downstream.

>     * drop Java 8

I'll look into it. We can probably do it upstream, the only plugin that seems to still require Java 8 (apart from Quarkus/Java tooling) is: https://github.com/camel-tooling/vscode-wsdl2rest

**Comment by sunix** [comment]
I have edited this to be java 17,
I think we can keep supporting the plugins for java 8 but we should remove it from the default stacks
