### ISSUE TITLE
DialogWindow methods inaccurate with 7.13.x update

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16768]
### Describe the bug
Theia IDE DOM has been updated and the changes have broken some methods in `tests/e2e/pageobjects/ide/DialogWindow` class.

The contents of the dialog window are currently displayed inside of a `<pre>` element instead of a `<span>` that has been used previously.
https://github.com/eclipse/che/blob/master/tests/e2e/pageobjects/ide/DialogWindow.ts#L68

We should make sure no other parts of the pageobjects have been influenced.

The issue has been reproduced in `Python Django` E2E nightly tests https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1636/consoleFull

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
* deploy nightly che
* run mocha tests for PythonDjango (or run the entire suite using `npm run test-all-devfiles`)
* wait for the `run server` command to execute
* the tests get stuck on being unable to locate the expected dialog window

### Expected behavior
* tests locate the correct dialog window and close it

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift
```
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-04-27 12-12-56](https://user-images.githubusercontent.com/16451875/80362097-52881f00-8882-11ea-9496-bc8984bab901.png)

### Installation method
   - [x] chectl `-a operator -p openshift --self-signed-cert -n tdancs-che-nightly`
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other `codereadyqe OCP4.3 cluster: apps.ocp43.codereadyqe.com`
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@ScrewTSW what is the priority for this issue? does it affected Hosted Che tests? 
My understanding that this issue only affects the internals of the typescript test

**Comment by dmytro-ndp** [comment]
It affects e2e nightly tests of Eclipse Che. So, P1 is more suitable here.

**Comment by ScrewTSW** [comment]
@ibuziuk once we would update to 7.13.x we would be facing the same issues

**Comment by ScrewTSW** [comment]
The main issue was fixed and PR is merged. We decided to close this issue and open a new one if DOM related test failures appear.
