### ISSUE TITLE
Support for WTP server launching

### ISSUE THREAD

**Issue by jfrantzius** [eclipse-che/che#1676]
[Feature suggestion for Java web application development]

One of the great features of Eclipse + M2E + WTP is that Eclipse' incremental build will always provide a consistent build state for my Java web application (WAR), no matter within which Maven module deep down in my dependencies I change a Java class (as long as it is within my Eclipse workspace).

That means after any change I can simply restart my Tomcat server from within Eclipse using WTP, without requiring a full Maven build (which could otherwise take multiple minutes to complete).

This cuts down turn turnaround-times a lot!

In [the documentation on running Web Apps](https://eclipse-che.readme.io/docs/run#web-apps) I couldn't find any hints on WTP server launches being supported.

**Comment by TylerJewell** [comment]
Not sure this is an enhancement.  @ddementieva, this is probably just a docs issue.  The wtp project does not provide instructions on how to run this server.  We will need someone to provide those then it would be simple to add it to a ws.

**Comment by ghost** [comment]
@TylerJewell the project page says it's installed as a plugin for Eclipse. It is can be run as a standalone app, then yes, it's a docs issue, otherwise, this is an enhancement.

**Comment by TylerJewell** [comment]
All those plugins have underlying servers I just don't think they document them.  But yes let's remove the enhancement label and make this just a docs issue.  Someone from the wtp team should comment on how to run underlying services stand alone

**Comment by JamesDrummond** [comment]
@jfrantzius Have you personally been able to figure out how to use WTP with Eclipse Che yet?

**Comment by TylerJewell** [comment]
My understanding is that this has been added into docs.
