### ISSUE TITLE
Che self-signed certificate secret created by Che operator contains more than one key on Openshift infrastructure

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#16773]
### Is your task related to a problem? Please describe.
When Che is deployed by operator, the operator creates `self-signed-certificate` secret. That secret contains single field `ca.crt` which in turn contains certificate chain (including CA).
Such behaviour is wrong. We should have a secret or part of a secret which contains CA certificate only. We still may keep certificate chain under another key or even in different secret. The point is to have CA certificate easy to access / read.

### Describe the solution you'd like
Revise operator code and remove or move other keys from `ca.crt` field of `self-signed-caertificate` secret.

### Describe alternatives you've considered
As of now this issue brings problems into retrieving CA certificate. `chectl` will fetch both certificates and will save into single file. Note, it is not trivial (but possible) to determine which certificate is CA as they are stored in PEM format. However it is task of `chectl` to analyze and separate TLS certificates and/or keys.

### Additional context
Happens on Openshift family platforms when deploy Che with operator.
https://issues.redhat.com/browse/CRW-848

**Comment by sleshchenko** [comment]
It makes impossible importing exported with `chectl cacert:export` into firefox https://github.com/eclipse/che/issues/16926

**Comment by AndrienkoAleksandr** [comment]
For me it's looks like P1, because it affects very first user experience.

**Comment by mmorhun** [comment]
Fixed on chectl side by filtering the certificate chain to have only CA certificates
