### ISSUE TITLE
Remove docs from che-server build

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16779]
### Is your task related to a problem? Please describe.
Reduce time to release che.

### Describe the solution you'd like
There is an idea raised on the last community call to remove docs from che-server build and do not release docs as maven artifacts.

**Comment by nickboldt** [comment]
Simplest solution here would be to simply remove the dependency on che-docs when building che-server.

```
```

But maybe part of this would would also be to switch the build over to being a container build instead of a maven build?

**Comment by nickboldt** [comment]
Can this be done for 7.13.x?

**Comment by themr0c** [comment]
This meaning that we can remove from che-docs the maven build that was only used to build che-server? That's great!
