### ISSUE TITLE
[Hosted Che] Can not build project in NodeJS Angular example stack

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16777]
### Describe the bug
Can not run build command (and all that requires that) in `NodeJS Angular Web Application` stack.

### Che version

 - [x] latest 7.12.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
 - Go to Worksapces
 - click `Add Workspace` button
 - select `NodeJS Angular Web Application` example stack 
 - click `CREATE & OPEN` button
 - run `yarn install` predefined command 
 - run `build` command

### Expected behavior
The project should be built correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) Hosted Che
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-04-27 12-13-54](https://user-images.githubusercontent.com/29278800/80361390-21f3b580-8881-11ea-8c72-4357234efb08.png)

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify Hosted Che

**Comment by ibuziuk** [comment]
@Katka92 is it Hosted Che specific? does it reproducible against both ephemeral / non-ephemeral modes?

**Comment by Katka92** [comment]
I've tried that on https://che.openshift.io with ephemeral mode and I could reproduce that. I also tried with non-ephemeral mode and I didn't get even `yarn install` working [1]. I've tried on upstream Che 7.12.0 and it works for both ephemeral and non-ephemeral mode.

[1] 
![Screenshot from 2020-04-29 14-11-32](https://user-images.githubusercontent.com/29278800/80594611-9b2b0e00-8a23-11ea-85a5-e9c45a913e7f.png)

**Comment by ericwill** [comment]
I cannot reproduce this on 7.15.1 Hosted Che -- all tasks (`yarn install`, `build`, `run`) work as expected.
