### ISSUE TITLE
Che 7.12.x release templates contain nightly tags of images

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16770]
### Describe the bug
7.12.x helm charts contains "nightly" tags which went to [chectl:7.12.0 tar ball](https://github.com/che-incubator/chectl/releases/tag/20200424063811):
- [devfile registry](https://github.com/eclipse/che/blob/7.12.x/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml#L11);
- [plugin regisrty](https://github.com/eclipse/che/blob/7.12.x/deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml#L11)
...

As a result, next command installs inconsistent Eclipse Che 7.12.0 on minikube with helm installer:
```
chectl/bin/chectl server:start --k8spodreadytimeout=180000 \
  --platform=minikube \
  --listr-renderer=verbose \
  --self-signed-cert \
  --skip-version-check
```
with:
- quay.io/eclipse/che-server:**7.12.0**
- quay.io/eclipse/che-devfile-registry:**nightly**
- quay.io/eclipse/che-plugin-registry:**nightly**

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.12.0

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [x] kubernetes
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by mkuznyetsov** [comment]
7.12.x branch has been updated
