### ISSUE TITLE
the debug session type "java" is not supported. in eclipse che 7 ide 

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16771]
### Che version

 - [
![Screenshot from 2020-04-27 16-16-54](https://user-images.githubusercontent.com/62592574/80364778-19f93d00-88a4-11ea-8f35-0a8af109b882.png)
 ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify

### Additional context

In eclipse che 7 ide iam unable to run any program 
![Screenshot from 2020-04-27 16-33-41](https://user-images.githubusercontent.com/62592574/80365224-e0750180-88a4-11ea-9d88-7a17775bb4ce.png)

**Comment by hari1992-web** [comment]
And also iam unable to enable debug mode also

**Comment by hari1992-web** [comment]
any body know in this issue 
Thanks in advance

**Comment by ibuziuk** [comment]
@hari1992-web the issue has literally no description. Can you please provide a clear description + steps to reproduce based on the GH issue template
