### ISSUE TITLE
Prepare demo about available persistent volume strategies

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16788]
### Is your task related to a problem? Please describe.
Prepare demo about available persistent volume strategies for the docs team explaining in a nutshell available options.

### Describe the solution you'd like
Source of information
 - https://github.com/eclipse/che-docs/blob/eab43f8cd751fa64dc9ae0d536d0588dc7ae230a/src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
- https://github.com/eclipse/che-docs/blob/aa50620c41cfdd0b6d9d2315cabfd7b041046f6a/src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
- https://github.com/eclipse/che-docs/blob/973bbb0edd90e3a7cd97253b5eb5052ff6d83a06/src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
- https://github.com/eclipse/che-docs/blob/20e6dd2f292e555e46b785fe1e08ab04016c4910/src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
- https://github.com/eclipse/che-docs/blob/ee86b9e16b92b29aa36383578760d09fdc8a5ca8/src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
- https://github.com/eclipse/che-docs/blob/15fae723eb737bbb650188ffd1ab4f337bc3c645/src/main/pages/che-7/administration-guide/examples/system-variables.adoc

**Comment by MichalMaler** [comment]
Thank you for the effort Sergii! +1 @skabashnyuk

**Comment by mshaposhnik** [comment]
General feedbasck is ok, but there is few thing recommended to add into demo:

- what happens with auth
- the drawbacks of common strategy
- the strategy on che.osio

**Comment by mshaposhnik** [comment]
Latest updated version is at:
https://drive.google.com/file/d/1J9qurXnr684VXz3Gw0atF9YX3Bi7dEmb/view?usp=sharing
