### ISSUE TITLE
Improve patternfly select component

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#16787]
### Is your task related to a problem? Please describe.

Currently the list of available items in select component is cut. Since list of items has absolute positioning it doesn't stretch the parent component and is partially hidden or off-screen, there is no chance to scroll and see all items. 

![](https://user-images.githubusercontent.com/5887312/80479567-dfe97300-8957-11ea-9536-01721c816c29.png)

### Describe the solution you'd like

Add ability to provide `maxHeight ` property to the select component. Show the scrollbar if items list is larger than `maxHeight`.

### Describe alternatives you've considered

N/a

### Additional context

https://github.com/eclipse/che-dashboard/pull/22#pullrequestreview-401731334

**Comment by sleshchenko** [comment]
Should be already addressed withing https://github.com/eclipse/che-dashboard/pull/22
