### ISSUE TITLE
Typo in kubernetes image puller docs

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#16789]
### Describe the bug

In https://www.eclipse.org/che/docs/che-7/caching-images-for-faster-workspace-start/, the command ` oc process -f deploy/openshift/app.yaml | oc apply -f --` is incorrect.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by rkratky** [comment]
Fixed
