### ISSUE TITLE
Move dependency management pom to che repo

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16780]
### Is your task related to a problem? Please describe.
Reduce the time that is needed to have a maven release of che.

### Describe the solution you'd like
Move dependency management pom to che repo. 
Do not release che-parent that often.

### Additional context
we can't deprecate che-parent because che-dashboard and che-loader are continuing to be as maven artifacts and uses it for maven plugin configuration.

**Comment by nickboldt** [comment]
Can this be done for 7.13.x?

**Comment by nickboldt** [comment]
Note from @dmytro-ndp:  
> java selenium tests are depending on some Eclipse Che maven modules as well https://github.com/eclipse/che/blob/master/tests/legacy-e2e/che-selenium-core/pom.xml#L58-L105
