### ISSUE TITLE
[doc] Fix external IP in examples for "Installing Che on kind using chectl"

### ISSUE THREAD

**Issue by olberger** [eclipse-che/che#16794]
In "Installing Che on kind using chectl" documentation (https://www.eclipse.org/che/docs/che-7/running-che-locally/#installing-che-on-kind-using-chectl_running-che-locally), the external IP seems to be mistyped, if one checks steps 7 and 8 :
```
    The ingress-nginx service now has an external IP:

    $ kubectl get svc -n ingress-nginx
    NAME            TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
    ingress-nginx   LoadBalancer   10.107.194.26   172.17.255.1   80:32033/TCP,443:30428/TCP   19h

    Run chectl, using the external IP of the ingress-nginx Service as an nip.io URL:

    $ chectl server:start --installer operator --platform k8s --domain 172.17.250.1.nip.io
```
In the above, it seems to me that the EXTERNAL IP reported for the ingress-nginx service should be the same as the IP passed in the domain... however, one is 172.17.255.1 and the other 172.17.250.1

I'm not sure though which is supposed to be the right one (the one in the IP range, i.e. 172.17.250 ?)

Hth,

**Comment by mmorhun** [comment]
Probably should be handled together with https://github.com/eclipse/che/issues/16792
