### ISSUE TITLE
[doc] Ingress instructions in "Installing Che on kind using chectl" fail

### ISSUE THREAD

**Issue by olberger** [eclipse-che/che#16792]
The docs in https://www.eclipse.org/che/docs/che-7/running-che-locally/#installing-che-on-kind-using-chectl_running-che-locally mention :
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
```
However, this is 404.

I guess the instructions are still in https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/overview/proc_installing-ingress-on-kubernetes.adoc too

Dunno yet how this is fixed

**Comment by mmorhun** [comment]
I think the links should be updated to the latest version and fixed to commit, but as a workarond one may look at `chectl` code: https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/docker-desktop.ts#L108
