### ISSUE TITLE
use Java 11 for quarkus stack as Java 8 is deprecated

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16790]
### Is your task related to a problem? Please describe.
Java 8 is deprecated https://quarkus.io/blog/quarkus-1-4-final-released/#whats-new

### Describe the solution you'd like
Use Java 11 images (for runtime and plugin)

**Comment by sunix** [comment]
This is quite critical ... I don't know when the samples (used by our stacks) will be updated and stop working with java8, so the sooner we fix that the better if we want to avoid a bad surprise seeing our stacks broken.

**Comment by sunix** [comment]
still the quarkus plugin to upgrade to Java11

**Comment by ericwill** [comment]
@sunix if I provide a PR, can you test it against your flow?

**Comment by sunix** [comment]
@ericwill yes

**Comment by sunix** [comment]
reopening as the Quarkus stacks have to be updated

**Comment by sunix** [comment]
reopening again

**Comment by ericwill** [comment]
@sunix am I to understand that we shouldn't offer Quarkus + Java 8 at all then?

**Comment by sunix** [comment]
yes we shouldn't offer java 8 : https://quarkus.io/blog/quarkus-1-4-final-released/#java-8-deprecated

**Comment by ericwill** [comment]
> yes we shouldn't offer java 8 : https://quarkus.io/blog/quarkus-1-4-final-released/#java-8-deprecated

Okay, I'll do the removal next sprint (187).
