### ISSUE TITLE
Update devfile spec repo - remove samples, link to live ones, etc.

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16793]
### Is your task related to a problem? Please describe.

@sparkoo  said:

> the repo is [devfile specification](https://github.com/redhat-developer/devfile) and it's not very up to date.

### Describe the solution you'd like

Then he said:

>  I didn't even know the [devfile samples](https://github.com/redhat-developer/devfile/tree/master/getting-started) were there. It looks like it was the base for what is now devfile-registry. I would remove them and link to devfile-registry to avoid confusion.

I would also add that:

* the repo description is missing, 
* there are no references to the https://github.com/eclipse/che-devfile-registry/
* there is no redirect in place to create new issues in https://github.com/eclipse/che/issues/new/choose (see set up in https://github.com/eclipse/che-plugin-registry/tree/master/.github )
* and, perhaps these outdated issues can be closed https://github.com/redhat-developer/devfile/issues ?

**Comment by nickboldt** [comment]
Is https://github.com/che-incubator/devworkspace-api the replacement for the above repo?

If so then maybe the above problems will be solved with https://github.com/che-incubator/devworkspace-api/issues/15 ?

**Comment by sparkoo** [comment]
I'm not sure if it is currently decided how we'll do transition to devfile 2.0. If we will support both forever / deprecate 1.0 and remove later / completely switch 1.0 to 2.0 at one day / something else. So we could assume that 1.0 will be with us for some time. IMHO we should either explicitly abandon that repo or fix it. As I like that devfile schema page, I'll try to fix it.
