### ISSUE TITLE
Che Deployment on GCP - Debugging Failing to Run

### ISSUE THREAD

**Issue by Les-Linux** [eclipse-che/che#16805]
### Describe the bug
Debugging Java Gradle deployed from the stack (Java Stack with OpenJDK 11 and Gradle 6.2.1) fails. 

The Java Debug Console opens but then the following exception is thrown:
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException

The deployment in GCP is a vanilla instance, which I only completed configuring this morning.

### Che version
Che-Theia@181d383 using Theia@9bc52ad1  v7.12
Built 4/23/2020, 4:58:50 PM

### Steps to reproduce
1. Deploy Java Gradle from Stack 
2. Set a Break-Point
3. F5 for Debugging
4. Wait on Language Support for Java 11 to Activate
5. Check Notifications

### Expected behavior
To reach breakpoint

### Runtime
Cube Cluster 1.15.11-gke.9

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.9", GitCommit:"e1af17fd873e15a48769e2c7b9851405f89e3d0d", GitTreeState:"clean", BuildDate:"2020-04-06T20:56:54Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

### Installation method
   - chectl/7.12.0 linux-x64 node-v10.20.1 (operator)

### Environment
   - [ ] my computer
       - [X] macOS
   - [ ] Cloud
       - [ X] GCE

[1588176702505.tar.gz](https://github.com/eclipse/che/files/4553077/1588176702505.tar.gz)

**Comment by Les-Linux** [comment]
I have noticed that if I add "console":"internalConsole" to the launch.json file, a 'Debug Console' window will open and the breakpoint is hit. If I omit the entry from the launch.json file, a '>_Java Debug Console ' window is opened and the error is thrown. The launch.json file was empty by the way, on creation of the project.
![Screenshot 2020-04-30 at 09 30 26](https://user-images.githubusercontent.com/1759713/80689438-4344e380-8ac5-11ea-9ca3-8b7426bd8f33.png)

**Comment by svor** [comment]
@Les-Linux looks like the problem because Java language server wasn't completely initialized when you start your debug session.
If we start the workspace, open some java file and wait when Java language server will be activated, then by clicking F5 debug configuration should be auto generated and another click F5 will run the debugger.

**Comment by Les-Linux** [comment]
I tried that too but the outcome was the same. Even with the Java language server activated, without the entry in the launch.json file it would fail. In the screen shot you see two different types of consoles opening, the first with the launch.json configuration attribute included, the second if it is removed from the launch.json file. Should the terminals not be identical if the java language server is active?

Thanks very much for your feedback.

Les

**Comment by svor** [comment]
I can't reproduce it on my local Minishift deployment. Could you please provide a log from 
View-->Output-->Extension Host (vscode-java) log
and it would be nice if you record the video with this problem

**Comment by Les-Linux** [comment]
sure, let me see what I can do.

**Comment by Les-Linux** [comment]
Extension Host Output
![Screenshot 2020-04-30 at 10 53 23](https://user-images.githubusercontent.com/1759713/80697422-d5061e00-8ad0-11ea-9432-ae13e6f01053.png)

**Comment by Les-Linux** [comment]
Recording Available [Here](https://drive.google.com/open?id=1AEKZMozK6RZ2oCMt6YXk-_MAfF6O5zvZ)

**Comment by svor** [comment]
And another log:
  View --> Find Command (F1) --> Java: Open Java language server log file

**Comment by Les-Linux** [comment]
Language Support for Java Log
![Screenshot 2020-04-30 at 12 07 46](https://user-images.githubusercontent.com/1759713/80703736-3fbc5700-8adb-11ea-94ca-aed920517111.png)

**Comment by Les-Linux** [comment]
When I selected Java: Open Java language server log file 'No log file available' was initially thrown, just as an FYI.

**Comment by svor** [comment]
> When I selected Java: Open Java language server log file 'No log file available' was initially thrown, just as an FYI.

hmm..and i don't see **Run | Debug** labels in HelloWorld.java in your video
![screenshot-che-che 192 168 99 133 nip io-2020 04 30-14_24_52](https://user-images.githubusercontent.com/1271546/80706111-689b1700-8af0-11ea-99b1-f27771b0fa17.png)

Looks like Java language server wasn't fully initialized. 
Could you please start another Java Gradle workspace, open HelloWorld.java and wait when Java LS will be activated after that execute **Java: Open Java language server log file** command

**Comment by svor** [comment]
I can reproduce it on GCP. 
Probably it could be related to this platform. Also there was a similar issue in vscode-java-debug, as a workaround you can try https://github.com/microsoft/vscode-java-debug/issues/637#issuecomment-525121005

**Comment by Les-Linux** [comment]
I have been looking at this all day, without becoming any wiser :). Changing the terminal to internalConsole get's you around the breakpoint matter, however if you want to read from stdin, then this will not be possible with the internalConsole.

**Comment by Les-Linux** [comment]
I dropped over to codeenvy to see if the issue was reproducible outside of my GCP environment. I even want as far as to tether with my phone to eliminate my network as a problem. I deployed the gradle java stack and tried to debug, receiving the same error.

**Comment by Les-Linux** [comment]
![Screenshot from 2020-05-02 09-37-23](https://user-images.githubusercontent.com/1759713/80859395-956a3e00-8c58-11ea-9340-f7ad1a6504c4.png)
![Uploading Screenshot from 2020-05-02 09-37-01.png…]()

**Comment by Les-Linux** [comment]
I decided to install vscode on my Mac just to see if there are any issues with the debugger and reading from stdin. Everything works as expected with the mac native app and I can debug and input text as expected.

**Comment by svor** [comment]
Can see this problem on che.openshift.io (in both cases: Ephemeral/not Ephemeral mode). Also there are logs from the browser console:
```log
theia.579ea14b81530b612778.js:1 Uncaught (in promise) Error: Request 'getProcessInfo' failed
    at Proxy.<anonymous> (theia.579ea14b81530b612778.js:1)
    at n.get [as processInfo] (theia.579ea14b81530b612778.js:1)
    at n.<anonymous> (theia.579ea14b81530b612778.js:1)
    at theia.579ea14b81530b612778.js:1
    at Object.next (theia.579ea14b81530b612778.js:1)
    at theia.579ea14b81530b612778.js:1
    at new Promise (<anonymous>)
    at s (theia.579ea14b81530b612778.js:1)
    at n.t.executeCommand (theia.579ea14b81530b612778.js:1)
    at t.<anonymous> (theia.579ea14b81530b612778.js:1)
```

**Comment by svor** [comment]
logs form theia-ide container 
```log

2020-05-13 07:29:31.992 root ERROR Request getProcessInfo failed with error: terminal "1" does not exist Params: Error: terminal "1" does not exist
--
  | at ShellTerminalServer.<anonymous> (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:118:27)
  | at step (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:59:23)
  | at Object.next (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:40:53)
  | at /home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:34:71
  | at new Promise (<anonymous>)
  | at __awaiter (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:30:12)
  | at ShellTerminalServer.BaseTerminalServer.getProcessInfo (/home/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:113:16)
  | at JsonRpcProxyFactory.<anonymous> (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:218:73)
  | at step (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:47:23)
  | at Object.next (/home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:28:53)
```
