### ISSUE TITLE
[workspace-loader & dashboard] .github actions or centos CI .ci scripts?

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16817]
### Is your task related to a problem? Please describe.

There are a number of unused boilerplate files in the new .ci folder of the workspace-loader project. If we're not building this via cico, we should remove these. 

https://github.com/eclipse/che-workspace-loader/tree/master/.ci

Similarly we have a GH action AND cico scripts configured for che-dashboard:

https://github.com/eclipse/che-dashboard/blob/master/.github/workflows/ci.yaml
https://github.com/eclipse/che-dashboard/tree/master/.ci

Should we use two different ways to build CI and release bits? Which is better? 

Discuss.

**Comment by benoitf** [comment]
IMHO GH actions will replace ci.centos
Just transitioning period I would say

**Comment by nickboldt** [comment]
> IMHO GH actions will replace ci.centos

so we would commit a change to master --> CI build or release branch -> release build?

**Comment by Prabhav-Thali** [comment]
For che-workspace-loader and che-dashboard, [ci.centos](https://ci.centos.org/view/Devtools/job/devtools-che-dashboard-che-build-master/37/console) is being used to build and push war file, could you please provide some info on whether war file is being pushed to oss.sonatype/maven repository?

Also, I have observed that war file for 7.13.x is not present on [maven repository](https://mvnrepository.com/artifact/org.eclipse.che.dashboard/che-dashboard-war). Are there any plans to discontinue the use of WAR files and use only docker images?

**Comment by skabashnyuk** [comment]
@Prabhav-Thali war files **content** replaced with docker images. See https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile#L14-L15

**Comment by Prabhav-Thali** [comment]
@skabashnyuk Thanks for the quick response.
