### ISSUE TITLE
Theia goes to offline mode after 15 mins

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16814]
![Screenshot from 2020-04-30 18-35-28](https://user-images.githubusercontent.com/62592574/80713652-71e8ab80-8b11-11ea-9cfa-801a9679ed46.png)
![Screenshot from 2020-04-30 17-15-24](https://user-images.githubusercontent.com/62592574/80706988-dd794b80-8b06-11ea-8408-276d66ddeda5.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
@hari1992-web more info is needed about your Che installation? Where do you run it, how deploy?
