### ISSUE TITLE
[chectl] Support helm as an installer for OpenShift (OSD) platform 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16812]
### Is your task related to a problem? Please describe.
As a developer, I want to have an opportunity to deploy Eclipse Che on OpenShift platform via chectl & helm as an installer:

`chectl server:start -p openshift --installer=helm --multiuser`

Currently, helm installer is only supported against k8s, minikube, microk8s, docker-desktop. However, in some cases when permissions are not enough for using operatorHub or creation of arbitary CRDs it should be possible to install Eclipse Che via helm installer. 

### Describe the solution you'd like
Changes that need to be made:
- `--domain` should be detected automatically for helm when platform is openshift
- `cert-manager deploy and requests for self-signed certificate` should be skipped for openshift
- Eclipse Che helm chart are compatible with v3 version and tiller is not required. For openshift platform we can skip `Tiller Role Binding`, RBAC, SA, SVC and target only helm 3.
- We should not grant `cluster-admin` to the Che SA in helm chart (`self-provisioner` should be enough) https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/cluster-role-binding.yaml#L16 
- on OSD we should not specify `securitycontext` in the charts

![image](https://user-images.githubusercontent.com/1461122/80694883-66778f00-8ad5-11ea-8afb-35c9aff94aba.png)

**Comment by gorkem** [comment]
Sounds like this will bring another level of installation testing. What is the advantage over operator? What is the advantage?

**Comment by ibuziuk** [comment]
@gorkem helm on OpenShift could be an alternative installation on the clusters where there is not enough permissions for using operator / operatorhub

**Comment by sleshchenko** [comment]
@ibuziuk I think operator is able to use the same permissions as helm might request but here is a question of the Che configuration - it would be Che that starts workspaces in the same namespace where it lives.
So, here is a question do we want just to have an ability to deploy Che without cluster-admin or we want:
- the operator always needs cluster-admin rights;
- helm chart support cluster-admin rights and shared namespace strategy without cluster-admin rights;

**Comment by ibuziuk** [comment]
This issue mainly targeted OSD v4 deployment but it looks like with `extended-dedicated-admin` [1] it is possible to deploy Eclipse Che on the operatorHub. So, I believe the issue can be closed as wont fix

[1] https://github.com/openshift/ops-sop/blob/master/v4/howto/extended-dedicated-admin.md
