### ISSUE TITLE
eclipse che pod bootstarp download images is not download 

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16811]
![Screenshot from 2020-04-30 13-20-22](https://user-images.githubusercontent.com/62592574/80686080-ca09b880-8ae5-11ea-9d8a-6d0df2344ea4.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify

**Comment by sleshchenko** [comment]
@hari1992-web are you able to check k8s event in the `che` namespace?
