### ISSUE TITLE
Error when starting workspace

### ISSUE THREAD

**Issue by rnavagamuwa** [eclipse-che/che#1681]
I'm developing an extension for eclipse che. This worked with 4.4 and now I'm getting this error when creating the workspace with 4.5-rci

**Observed behavior:**
I'm getting the following exception when creating a workspace
[Complete exception can be found in here](https://gist.github.com/rnavagamuwa/41b03270efad594f340036e5f4b1de2e.js)

> Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CheBootstrap
> com.google.inject.CreationException: Unable to create injector, see the following errors:
> 
> 1) Invocation error of method public void org.eclipse.jdt.internal.ui.JavaPlugin.start() on org.eclipse.jdt.internal.ui.JavaPlugin@333e9211
>   at org.eclipse.che.plugin.java.server.inject.JdtGuiceModule.configure(JdtGuiceModule.java:51)
>   while locating org.eclipse.jdt.internal.ui.JavaPlugin
> 
> 1 error
>     at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[guice-4.1.0.jar:na]
>     at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:na]
>     at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137) ~[everrest-integration-guice-1.12.3.jar:na]
>     at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) ~[guice-servlet-4.1.0.jar:na]
>     at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:84) ~[everrest-integration-guice-1.12.3.jar:na]
>     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [catalina.jar:8.0.32]
>     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [catalina.jar:8.0.32]
>     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [catalina.jar:8.0.32]
>     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.32]
>     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.32]
>     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.32]
>     at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939) [catalina.jar:8.0.32]
>     at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812) [catalina.jar:8.0.32]
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
>     at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
> Caused by: java.lang.SecurityException: class "org.eclipse.core.runtime.Plugin"'s signer information does not match signer information of other classes in the same package
>     at java.lang.ClassLoader.checkCerts(ClassLoader.java:895) ~[na:1.8.0_45]
>     at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665) ~[na:1.8.0_45]
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:758) ~[na:1.8.0_45]
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_45]
>     at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2469) ~[catalina.jar:8.0.32]
>     at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:835) ~[catalina.jar:8.0.32]
>     at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1277) ~[catalina.jar:8.0.32]
>     at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142) ~[catalina.jar:8.0.32]
>     at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_45]
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_45]
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_45]
>     at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2469) ~[catalina.jar:8.0.32]
>     at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:835) ~[catalina.jar:8.0.32]
>     at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1277) ~[catalina.jar:8.0.32]
>     at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142) ~[catalina.jar:8.0.32]
>     at org.eclipse.jdt.internal.ui.JavaPlugin.start(JavaPlugin.java:210) ~[org.eclipse.jdt.ui-4.5.0-RC1-SNAPSHOT.jar:4.5.0-RC1-SNAPSHOT]
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
>     at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
>     at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44) ~[che-core-commons-inject-4.5.0-RC1-SNAPSHOT.jar:4.5.0-RC1-SNAPSHOT]
>     at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:121) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) ~[guice-4.1.0.jar:na]
>     at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) ~[guice-4.1.0.jar:na]
>     ... 18 common frames omitted

**Che version:**    4.5-RC1  
**OS and version:** Linux 16.04  
**Docker version:**  1.11.2, build b9f10c9     

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by benoitf** [comment]
should be fixed by https://github.com/eclipse/che-dependencies/pull/12

**Comment by rnavagamuwa** [comment]
It's fixed now
