### ISSUE TITLE
[dashboard] build the yarn bits and fixup the apache config in the same dockerfile; update readme and remove pom

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16816]
### Describe the bug

To make building the dashboard [one-step (instead of 6)](https://github.com/eclipse/che-dashboard/blob/master/.github/workflows/ci.yaml#L37-L46) we should combine building the project and updating apache into a single Dockerfile.

We should also remove the [pom.xml](https://github.com/eclipse/che-dashboard/blob/master/pom.xml) and update the [readme](https://github.com/eclipse/che-dashboard/blob/master/README.md#quick-start) (depmgt pom no longer exists and readme is now incorrect as we don't use maven to build).

### Che version

 - [x] 7.13.0-SNAPSHOT

Related to https://www.eclipse.org/lists/che-dev/msg03720.html

**Comment by sleshchenko** [comment]
I believe it's already addressed. If no - feel free to reopen that issue.
