### ISSUE TITLE
https://che-che.172.17.250.1.nip.io/  i opened url in  node systems and master in kubernetes but i cant browse in outside why 

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16823]

**Comment by hari1992-web** [comment]
please any body  know ????????

**Comment by sleshchenko** [comment]
@hari1992-web probably somebody will be able to help you if you provide more info about your installation, what is a platform? K8s/OS run where? How did you deploy Che? Which arguments if it's chectl?...

**Comment by hari1992-web** [comment]
Hi , i am using kubernetes vesion  v1.18.2 on local environment 
We , deployed eclipse che using chectl command line tool 

sudo chectl server:start --installer=helm --multiuser --platform=k8s --self-signed-cert --domain=172.17.250.2.nip.io --cheimage=eclipse/che-server:nightly --k8spodreadytimeout=300000 --k8spodwaittimeout=3000000  --workspace-pvc-storage-class-name=csi-hostpath-sc


Here I shared my kubernetes dashboard version screenshots please check once 

![Screenshot from 2020-05-04 16-23-27](https://user-images.githubusercontent.com/62592574/80959036-a1562b80-8e23-11ea-81c0-dc63f655cc4b.png)


![Screenshot from 2020-05-04 16-18-27](https://user-images.githubusercontent.com/62592574/80958677-04938e00-8e23-11ea-9f36-8527c684f237.png)

**Comment by hari1992-web** [comment]
> @hari1992-web probably somebody will be able to help you if you provide more info about your installation, what is a platform? K8s/OS run where? How did you deploy Che? Which arguments if it's chectl?...

**Comment by hari1992-web** [comment]
> Hi , i am using kubernetes vesion v1.18.2 on local environment
> We , deployed eclipse che using chectl command line tool
> 
> sudo chectl server:start --installer=helm --multiuser --platform=k8s --self-signed-cert --domain=172.17.250.2.nip.io --cheimage=eclipse/che-server:nightly --k8spodreadytimeout=300000 --k8spodwaittimeout=3000000 --workspace-pvc-storage-class-name=csi-hostpath-sc
> 
> Now iam using eclipse che inside cluster but how can i access eclipse che from outside cluster ?????
> 
> Here I shared my kubernetes dashboard version screenshots please check once
> 
> ![Screenshot from 2020-05-04 16-23-27](https://user-images.githubusercontent.com/62592574/80959036-a1562b80-8e23-11ea-81c0-dc63f655cc4b.png)
> 
> ![Screenshot from 2020-05-04 16-18-27](https://user-images.githubusercontent.com/62592574/80958677-04938e00-8e23-11ea-9f36-8527c684f237.png)

please any body help ???

**Comment by sleshchenko** [comment]
Is `172.17.250.2.nip.io` available publicly?
If no - then choose another domain to use...
Probably you need some DNS server + publicly available domain, then you need to configure them properly and after once you made sure your Ingress Controller is available publicly - you're able to redeploy Che with right domain.

So, my advice is - search for info how to expose your local K8s cluster, it's not really Che specific issue,

**Comment by tolusha** [comment]
@sleshchenko 
Thank you for provided answer.

@hari1992-web 
Pls, respect the issue bug template.
