### ISSUE TITLE
E2E Happy path tests failed on "Validation of workspace build and run" step

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16828]
### Describe the bug
E2E Happy path tests failed on "Validation of workspace build and run" step when run [against Eclipse Che nightly version on minikube without TLS support](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1664/):
```
          ▼ Ide.waitNotification "A new process is now listening on port 8080"
    1) Run application


  9 passing (8m)
  1 pending
  1 failing

  1) Validation of workspace build and run
       Run application:
     TimeoutError: Waiting for element to be located By(xpath, //div[@class='theia-notification-message']/span[contains(.,'A new process is now listening on port 8080')])
Wait timed out after 120004ms
```
### Che version
 - [ ] latest
 - [x] nightly, 7.12.1
 - [ ] other: please specify

### Steps to reproduce
https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Run_application (3)](https://user-images.githubusercontent.com/1197777/80930004-0f193d80-8db9-11ea-9003-b291091cc232.png)

### Screencast
https://youtu.be/ZU2SDaCKwhU

### Installation method
   - [x] chectl:next
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/16831
