### ISSUE TITLE
Factory: querystring parameters that contain encoded '&' character are wrongly passed to the factory service after redirections

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16827]
Factory: querystring parameters that contains encoded '&' character are wrongly passed to the factory service after redirections

Try to run this factory:
https://che.openshift.io/f?url=https://github.com/sunix/code-quarkus-devfile&override.projects.quarkus-quickstarts.source.location=https%3A%2F%2Fcode.quarkus.io%2Fd%3Fg%3Dorg.sunix%26a%3Dsunix-youpi%26v%3D1.0.0-SNAPSHOT%26b%3DMAVEN%26c%3Dorg.sunix.ExampleResource%26s%3DbarD.Bqi%26cn%3Drouteqrgetcva-developer-che.apps-crc.testing

the `override.projects.quarkus-quickstarts.source.location` parameter contains an encoded URL
```
https://code.quarkus.io/d?g=org.sunix&a=sunix-youpi&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.sunix.ExampleResource&s=barD.Bqi&cn=routeqrgetcva-developer-che.apps-crc.testing
```

The first redirection is wrong:
![image](https://user-images.githubusercontent.com/650571/80920373-bd989080-8d6f-11ea-82ce-243592b4c6f3.png)
We can see that the & character is not encoded
location
```
/dashboard/#/load-factory/?url=https://github.com/sunix/code-quarkus-devfile&override.projects.quarkus-quickstarts.source.location=https://code.quarkus.io/d?g=org.sunix&a=sunix-youpi&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.sunix.ExampleResource&s=barD.Bqi&cn=routeqrgetcva-developer-che.apps-crc.testing
```
should be
```
/dashboard/#/load-factory/?url=https%3A%2F%2Fgithub.com%2Fsunix%2Fcode-quarkus-devfile&override.projects.quarkus-quickstarts.source.location=https%3A%2F%2Fcode.quarkus.io%2Fd%3Fg%3Dorg.sunix%26a%3Dsunix-youpi%26v%3D1.0.0-SNAPSHOT%26b%3DMAVEN%26c%3Dorg.sunix.ExampleResource%26s%3DbarD.Bqi%26cn%3Drouteqrgetcva-developer-che.apps-crc.testing
```
The problem is that finally the  `override.projects.quarkus-quickstarts.source.location` parameter is set to 
```
https://code.quarkus.io/d?g=org.sunix
```
instead of 
```
https://code.quarkus.io/d?g=org.sunix&a=sunix-youpi&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.sunix.ExampleResource&s=barD.Bqi&cn=routeqrgetcva-developer-che.apps-crc.testing
```

Trying to reach directly `/dashboard#load-factory/` to avoid that redirection and the problem is still there but this time, there is something wrong when getting through the keycloak redirection.

Using the url https://che.openshift.io/dashboard/#/load-factory/?url=https%3A%2F%2Fgithub.com%2Fsunix%2Fcode-quarkus-devfile&override.projects.quarkus-quickstarts.source.location=https%3A%2F%2Fcode.quarkus.io%2Fd%3Fg%3Dorg.sunix%26a%3Dsunix-youpi%26v%3D1.0.0-SNAPSHOT%26b%3DMAVEN%26c%3Dorg.sunix.ExampleResource%26s%3D%26cn%3Drouteqrgetcva-developer-che.apps-crc.testing:

the final URI after redirection is still wrong:
![image](https://user-images.githubusercontent.com/650571/80920980-9643c280-8d73-11ea-9507-1f4ca7e43db5.png)

![image](https://user-images.githubusercontent.com/650571/80921032-ea4ea700-8d73-11ea-84c1-839222fdf3c6.png)

**Comment by sunix** [comment]
FYI I got this issue when trying to make that working: https://twitter.com/__sunix_/status/1256897541448310796

**Comment by sunix** [comment]
it looks like most of the issues are coming from the sso used in che.openshift.io.
Using the last URL on an internal instance works fine ... :/

**Comment by sleshchenko** [comment]
According to Sun's comment - it comes from sso used on che.openshift.io. So, changed labels accordingly
cc @ibuziuk

**Comment by ibuziuk** [comment]
is it reproducible against workspaces.openshift.com?
if not, I believe we should close it

**Comment by sunix** [comment]
@ibuziuk i will give a try soon :)

**Comment by sleshchenko** [comment]
@sunix please do )

**Comment by sunix** [comment]
@ibuziuk and @sleshchenko 
Still a problem

https://workspaces.openshift.com/f?url=https://github.com/sunix/code-quarkus-devfile&override.projects.quarkus-quickstarts.source.location=https%3A%2F%2Fcode.quarkus.io%2Fd%3Fg%3Dorg.sunix%26a%3Dsunix-youpi%26v%3D1.0.0-SNAPSHOT%26b%3DMAVEN%26c%3Dorg.sunix.ExampleResource%26s%3DbarD.Bqi%26cn%3Drouteqrgetcva-developer-che.apps-crc.testing

![image](https://user-images.githubusercontent.com/650571/112313433-1f275d80-8ca8-11eb-91b8-6144bc83b95e.png)

**Comment by sleshchenko** [comment]
reproduced on workspace.openshift.com, works fine on nightly Che

**Comment by sleshchenko** [comment]
But that's the magic how it works in upstream.
I've added another query param: override.metadata.name, but after Che Server sends redirect, encoding is lost and it's unclear where are location params and where are factory params, but it works.
![Screenshot_20210326_092036](https://user-images.githubusercontent.com/5887312/112596477-8b26d480-8e14-11eb-9b1e-3eb4c4f984ce.png)
![Screenshot_20210326_092025](https://user-images.githubusercontent.com/5887312/112596489-8e21c500-8e14-11eb-8d3d-539ae84c10e5.png)

Hope CRW 2.8 will get this issue solved.

**Comment by sunix** [comment]
I am wondering if there is a workaround. Can the factory service accept POST request with the same parameters ?

**Comment by sleshchenko** [comment]
> Can the factory service accept POST request with the same parameters ?

it's already a case, but the faced issue is caused not by factory service, but query which is encoded and decoded back incorrectly.

**Comment by sunix** [comment]
Yes but maybe it works if we don't pass these parameters as query strings in the url.

**Comment by sleshchenko** [comment]
How we can avoid it, since it's factory URL? )

**Comment by sunix** [comment]
The usecase here is that factory url could be used in generators like https://code.quarkus.io/ See demo https://twitter.com/__sunix_/status/1256897541448310796
I think the sso issue is out of our control, so pass the values as POST content it could work. The call(s) would be performed by  https://code.quarkus.io/

**Comment by sleshchenko** [comment]
the shared flow already can work with POST, it just needs to create a workspace, and open URL which points to it, instead of factory URL
