### ISSUE TITLE
how can i access outside on this eclipse che url https://che-che.172.17.250.1.nip.io/ 

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16824]
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by hari1992-web** [comment]
![Screenshot from 2020-04-28 13-11-07](https://user-images.githubusercontent.com/62592574/80861602-2b1fc080-8c8d-11ea-96d0-bb9e4abab507.png)

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/16823
