### ISSUE TITLE
Check if an OAuth identity provider exist instead of looking for OpenShift users

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16837]
### Is your enhancement related to a problem? Please describe.

Che deployment on OpenShift using OpenShift OAuth fails if users have not logged in OpenShift yet.

### Describe the solution you'd like

To figure out if at least one user exist we check for valid OpenShift users. We should check for valid identity providers instead.

**Comment by AndrienkoAleksandr** [comment]
Done https://github.com/eclipse/che-operator/pull/248

**Comment by l0rd** [comment]
@tolusha @AndrienkoAleksandr we want to make a CRW 2.1.2 release that includes this fix. How hard is it to cherry pick the fixes for this and #16836 to branch 7.9.x?

**Comment by tolusha** [comment]
@l0rd 
We will try
