### ISSUE TITLE
Update the "DialogWindow.waitDialog" method

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#16830]
### Is your task related to a problem? Please describe.
Update the "DialogWindow.waitDialog" method, because it doesn't compatible with all necessary cases.

### Describe the solution you'd like
Update xpath uses in the method
```
pre[contains(text(), '${dialogTest}')]
```
to
```
*[contains(text(), '${dialogTest}')]
```

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/16831

**Comment by dmytro-ndp** [comment]
Reopening an issue, because [getApplicationUrlFromDialog() method](https://github.com/eclipse/che/blob/master/tests/e2e/pageobjects/ide/DialogWindow.ts#L90) should be fixed as well

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/16847
