### ISSUE TITLE
Share large set of files between all containers in all workspaces

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#16846]
I would like to share a large set of files (approx 10GB of files) among all workspaces and containers within those workspaces.

Here are the quesitons:
1. Could you please let me know how I can achieve this in che. Does this support exists in che?
2. If the support currently doesnt exist, can I help implement it ? (but, I will be needing technical guidance on this)

Thank you all in advance. It would be very helpful if someone can help me on this.

**Comment by RomanNikitenko** [comment]
@svkr2k 
I think [we have an ability](https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#persistent-storage) to share a volume across all components, but I'm not sure that it's possible to share a volume among all workspaces.

@benoitf @skabashnyuk  could you take a look

**Comment by svkr2k** [comment]
Hi @RomanNikitenko , @benoitf , @skabashnyuk .

My use case is that I will have a large set of files (executables & text files). I would like to share these files with all workspaces (that are created by different users). The containers inside these workspaces should be able to access those files. The containers inside the workspaces either run the executables OR access text files whenever needed. For example, some propreitory compilers can be part of those shared files.

So, any container (in any workspace) will be accessing those files asynchronously.

If I dont share these files, then, I need to add all those files into the workspace containers thereby potentially increasing the workspaces container sizes to 20GB (per workspace).

Kindly suggest. Thanks in advance.

**Comment by svkr2k** [comment]
Can we make use of the technique similar to what is mentioned here : https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by l0rd** [comment]
@svkr2k there is a fundamental problem with your suggestion: most of the [persistent volumes plugins only support ReadWriteOnce (RWO) access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes). That's true particular those PV plugins that use block based storage, and that's the only distributed storage type that works decently for software development (intense I/O throughput when cloning, building etc...). That means that only one Pod can be attached to the PV at a time.

**Comment by svkr2k** [comment]
Thank you, @l0rd .
I believe that I will be needing only Read-Only access to the shared storage.
Is 'ReadOnlyMany' access feasible in this case? As you mentioned I will be needing intense I/O throughput too.

**Comment by amisevsk** [comment]
Related: https://github.com/eclipse/che/issues/15652

**Comment by davidwindell** [comment]
I think this should be closed in favour of #15652. The usage of EFS/NFS is the perfect example for this requirement.

**Comment by amisevsk** [comment]
@davidwindell Good point. Closing in favor of https://github.com/eclipse/che/issues/15652, which has more discussion.
