### ISSUE TITLE
Che doesn't use the configured DNS server

### ISSUE THREAD

**Issue by rolurq** [eclipse-che/che#1684]
When i try to create a new project, i get a 'Could not resolve host' error while cloning the project template from github. I access the docker container running che and i tried to access any host using its hostname and obtained the same result, i guess that che isn't using my network confugured dns server.

**Comment by ghost** [comment]
@rolurq are you running che in a Docker container on a remote host?

**Comment by rolurq** [comment]
I'm currently running che in a Docker container.

**Comment by ghost** [comment]
Can you run:

`docker run -ti codenvy/ubuntu_jdk8 bash`
`git clone https://github.com/che-samples/console-java-simple.git`

This way we take Che out of the game for a while and check if you have local Docker issues.

**Comment by ghost** [comment]
@rolurq any update on this issue?

**Comment by ghost** [comment]
@rolurq I am closing the issue. Feel free to reopen if the problem persists.
