### ISSUE TITLE
Invalid Yarn Command

### ISSUE THREAD

**Issue by mrjonleek** [eclipse-che/che#16845]
The command for installing the `yo @theia/generator-plugin` is invalid. [Source](https://www.eclipse.org/che/docs/che-7/developing-che-theia-plug-ins/#installing-the-plug-in-generator_developing-che-theia-plug-ins)

The instructions specify `$ yarn add global yo @theia/generator-plugin` however this does not result in the global installation of `yo`.

Instead, the accurate command is `$ yarn global add yo @theia/generator-plugin`. The only difference being the `add` and `global` arguments are out of order.

Node version 10.17.0
NPM version 6.11.3

**Comment by RomanNikitenko** [comment]
@mrjonleek 
thank you for reporting!
