### ISSUE TITLE
Workspace start up logs is prefixed with one of the container name for all of them

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16848]
In this screenshot, `openjdk--9-jdk` is prefixed for all the containers ... but it is the alias of only one of them.
![image](https://user-images.githubusercontent.com/650571/81045011-a1067080-8eb5-11ea-9691-c6cd99678dfc.png)

## Reproducable steps:
Start a factory with several containers (type dockerimage)

**Comment by skabashnyuk** [comment]
@sunix can you please provide your devfile?
