### ISSUE TITLE
'Run' / 'Debug' codelens does not work 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16856]
### Is your task related to a problem? Please describe.
Steps to reproduce:

- Create a workspace from spring boot devile
- Open `PetClinicApplication`
- Press `Run|Debug` codelense
- ERROR: nothing happens, Debug is failing with

![image](https://user-images.githubusercontent.com/1461122/81201107-2cbaf280-8fc5-11ea-80c9-0aa82175a51c.png)

Reproduced on Hosted Che `7.12.1`

Workaround:
1.  Add debug task

```
{
            "type": "che",
            "label": "Debug application locally",
            "command": "mvn spring-boot:run -Dspring-boot.run.jvmArguments='-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005'",
            "target": {
                "workingDir": "/${CHE_PROJECTS_ROOT}/summit-lab-spring-music",
                "component": "spring-music"
            }
        }
```
2. Run the task
3. menu Debug -> Start Debugging 

![debug-spring-boot](https://user-images.githubusercontent.com/1461122/81208385-3fd2c000-8fcf-11ea-9fb5-dcd8b5f9645e.gif)

**Comment by l0rd** [comment]
I am setting a P1 assuming that this doesn't work for any workspace, not just the given example. Otherwise it should be a P2.

**Comment by ibuziuk** [comment]
@l0rd looks like broken for every workspace - was able repro against simple hello world java maven devfile

**Comment by azatsarynnyy** [comment]
should be fixed by https://github.com/eclipse/che-theia/pull/750
