### ISSUE TITLE
In the Operator Go code, remove remaining default values that require overriding in downstream

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#16868]
### Is your enhancement related to a problem? Please describe.

The Operator Go code should be shared between upstream and downstream releases of the Che operator. That's one of the reasons why most of the default values that finally are different between upstream and downstream (like default docker images or CHE_VERSION) have been extracted from the GO code and included as environment variables in the operator deployment files that are specific to either downstream or upstream flavors.
However there are still a few default values that should be extracted this way, for example:
- the [default flavor](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults.go#L45),
- the [default console link display name](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults.go#L98),
- The [way the test of default values is started](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults_test.go): here either the defaults should be set by environment variables in the build according to the upstream / downstream user-case, or the hard-coded docker images should be made confirgurable themselves. Anyway for now this file requires some changes downstream to have the test passing afair.   

Maybe there are others places to consider.

### Describe the solution you'd like

Allow the downstreaming process to import the code form an upstream release branch without having to change anything to it.

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/16305

**Comment by tolusha** [comment]
@davidfestal 
I don't think default values for tests make have any effects on downstream projects.
In [defaults_test.go](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults_test.go) we just set the env var and then read default values to ensure the are initialized correctly.

@nickboldt 
Could you have a look at [defaults.go](https://github.com/eclipse/che-operator/blob/master/pkg/deploy/defaults.go#L45) and say what else you would like to move to env var ?

**Comment by tolusha** [comment]
corresponding PR
https://github.com/eclipse/che-operator/pull/247

**Comment by nickboldt** [comment]
PR looks ok, left a comment about 3 more vars we could override/expose.

Also wondering if you saw https://github.com/eclipse/che/issues/16815
