### ISSUE TITLE
`CheCluster` custom resource completion and docs are not available anymore on OpenShift 4.3 +

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#16860]
### Describe the bug

In OpenShift 4.3 and later, the completion and documentation services provided in the console on custom resource YAML is broken for the `CheCluster` custom resource.

This is quite impacting since those services are very valuable for customers to have a quick and immediate knowledge of the various available Che installation options, as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/686586/81268065-bb705380-9047-11ea-9147-4a82e2459ce4.png)

Without the services, the user has no idea of the available options, apart from diving deep into the documentation.

This is broken because from OpenShift 4.3 version and later, the OpenApi schema of Custom Resource Definitions is expected to be valid according to constraints that are now stricter than in previous OpenShift versions.

Following changes to the latest `CheCluster` CRD file would be required to enable YAML language services again on the `CheCluster` custom resource:
- Add the `type: object` field at the root of the OpenApi schema
- Set the `preserveUnknownFields` CRD field to `false`. This should not hurt since we don't use fields that are not specified in the schema, and keep backward compatibility of existing fields when updating the CRD.

The above screenshot show the restored services on a OS 4.3 cluster as soon as these 2 changes are applied to the CRD.

This will allow getting back language services (completion / docs) on the `CheCluster` custom resource in the OpenShift Console for OpenShift 4.3 +

This bug has already been fixed in the `CheCluster` CRD included in CRW 2.1.1 release by this PR: https://github.com/redhat-developer/codeready-workspaces-operator/pull/19

However the upstream Che general use-case is a bit trickier since we have to ensure compatibility of the CRD for OpenShift 3.11 when installing from chectl as well. So CRD generation scripts should take in account the fact that CRD in the raw `deploy` yaml will be slightly different (one compatible with 3.11 up to 4.2 the other one with OS 4.x.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Create a `CheCluster` custom resource in OpenShift 4.3 console after installing The Che operator, and you will miss yaml completion and documentation.

### Expected behavior

Create a `CheCluster` custom resource in OpenShift 4.3 console after installing The Che operator, and you should get yaml completion and documentation.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

**Comment by tolusha** [comment]
@davidfestal 
My proposal: 
- Add `type: object`
  * it is enough to have completion and docs in OpenShift 4.x 
  * it is fully compatible with OpenShift 3.11
- Not to add `preserveUnknownFields: false` since
  * it is not needed to restore docs
  * not compatible with OpenShift 3.11
  * we have field [keycloakPostgresPassword](https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L99) which is not defined in crd (I don't know why)

**Comment by davidfestal** [comment]
@tolusha did you really try in OpenShift 4.3 + ? Afaik `preserveUnknownFields: false` is required for completion to work starting with OpenShift 4.3.
I'm also surprised that `type: object` is compatible with OpenShift 3.11/ There was precisely an issue that at some point forced us to remove it to ensure 3.11 compatibility.

> we have field keycloakPostgresPassword which is not defined in crd (I don't know why)

That seems like a bug, no ?

**Comment by tolusha** [comment]
For openshift 4.3, crd with `type: object`, autocomplition and docs work:
https://console-openshift-console.apps.ocp43.codereadyqe.com/k8s/ns/abazko/test.org.eclipse.che~v1~TestCheCluster/example/yaml

I tested on minikube for openshift 3.11.
I was able to create crd with `type: object`

**Comment by davidfestal** [comment]
@tolusha could you please update the issue with the result of the tests we did again today, and the updated proposed plan ?

**Comment by tolusha** [comment]
@davidfestal 
To have all functional working it is needed to add both `type: object` and `preserveUnknownFields: false` fields. Since these changes aren't compatible for OpenShift 3.11 we've decided to set those fields only in csv file (since installation from OperatorHub isn't supported for OpenShift 3.11 and we won't break anything)

**Comment by tolusha** [comment]
Postponed to 7.13.1 release

**Comment by tolusha** [comment]
https://github.com/eclipse/che-operator/commit/b205e92a79c40670ab20c73f8add6bb40bbc79f6

**Comment by davidfestal** [comment]
@tolusha @nickboldt 

It seems this has been fixed *only* in the `7.13.1` bugfix release, but never cherry-picked on `master` in nightlies, at least it never came into to the `7.14.1` and higher releases.
- Fixed on `7.13.2`: [required `preserveUnknownFields: false` is there](https://github.com/eclipse/che-operator/blob/v7.14.1/olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.13.2/eclipse-che-preview-openshift.crd.yaml#L25)
- Not fixed on `7.14.1`: [required `preserveUnknownFields: false` is **not** there](https://github.com/eclipse/che-operator/blob/v7.14.1/olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.14.1/eclipse-che-preview-openshift.crd.yaml#L27)

So as a result, it has been integrated in the downstream manifests only in the CRW `2.1.1` release, but disappeared since the `2.2.0` and higher CRW releases:
- Fixed on the `2.1.1` release: [required `preserveUnknownFields: false` is there](https://github.com/redhat-developer/codeready-workspaces-operator/blob/master/controller-manifests/v2.1.1/codeready-workspaces.crd.yaml#L25)
- Not fixed on `7.14.1`: [required `preserveUnknownFields: false` is **not** there](https://github.com/redhat-developer/codeready-workspaces-operator/blob/master/controller-manifests/v2.2.0/codeready-workspaces.crd.yaml#L27)

What I would suggest is:
- **FIRST** On the CRW side, possibly before CRW 2.5.0 release (cc @nickboldt)  :
  - Fix it back immediately for the upcoming `2.5.0` CRW release in the new bundle format here: https://github.com/redhat-developer/codeready-workspaces-operator/blob/crw-2.5-rhel-8/manifests/codeready-workspaces.crd.yaml#L26
  - Maybe fix it back in the older releases in new bundle format index: here: https://github.com/redhat-developer/codeready-workspaces-operator/blob/2.3.0.GA/manifests/codeready-workspaces.crd.yaml ? Not sure if it is possible
- **THEN** On the upstream che operator side (cc @tolusha) :
  - Fix it also in the OperatorHub CRD on the main branch of the `che-operator` repo, in order to have the next upstream (and downstream)  releases correctly integrate the change.

**Comment by davidfestal** [comment]
@tolusha As you mentioned it in a slack comment, I didn't see it was at a distinct place in the newer released versions in upstream Che operator repository.

However the problem is that the new nightly bundle doesn't have it: https://github.com/redhat-developer/codeready-workspaces-operator/blob/crw-2.5-rhel-8/manifests/codeready-workspaces.crd.yaml
Only release OLM packages have it, and the downstreaming is based on the nightly bundle.

**Comment by davidfestal** [comment]
A fix has already been proposed by @tolusha in PR https://github.com/eclipse/che-operator/pull/509
