### ISSUE TITLE
Make the new `olm` chectl installer easier to use downstream

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#16862]
### Is your enhancement related to a problem? Please describe.

The new chectl `olm` instalation method is expected to come to the next downstream release.
The downstream product doesn't use the same OLM catalog, not the same operatorSource.

### Describe the solution you'd like
We should check the default operator source used by chectl can be easily switched through downsrteaming process.

**Comment by AndrienkoAleksandr** [comment]
Done by https://github.com/che-incubator/chectl/pull/724
