### ISSUE TITLE
Cannot start a new workspace

### ISSUE THREAD

**Issue by ywg1990** [eclipse-che/che#1686]
When I try to run a new workspace, I get a 'Failed,certificates are required for https connection'.

Reproduction Steps:

1.run che.
![22](https://cloud.githubusercontent.com/assets/20349254/16677446/9e9c365e-4508-11e6-8be7-bd5479b6426d.PNG)

2.run workspace

![33](https://cloud.githubusercontent.com/assets/20349254/16677456/af24c716-4508-11e6-9560-caaea18073e2.PNG)

3.run stop

![11](https://cloud.githubusercontent.com/assets/20349254/16677457/b6fe5e84-4508-11e6-8dc8-ab621daa7f7a.PNG)

Observed behavior:

Che version: 4.3.4
OS and version: win7
Eclipse version: Mars

**Comment by ghost** [comment]
@ywg1990 Looks like VirtualBox issues.

Can you click on Docker QuickStart icon that you should have on your desktop after installing Docker Toolbox?

You will see a new terminal with docker-machine starting a new VM. Can you then successfully run docker commands, like `docker ps`?

**Comment by thyeun** [comment]
@ywg1990, i think you need to regenerate the cert for the docker-machine "Che" by using the command "docker-machine regenerate-certs Che", before you run the "Che run".

hope it help you up.

**Comment by TylerJewell** [comment]
Yes, @ywg1990 - was going to also suggest the cert regeneration issue with
docker-machine posted by Thomas.  Can you give that a shot?

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by ghost** [comment]
@ywg1990 any update on this one? Were you able to get past this error?

**Comment by ywg1990** [comment]
@eivantsov I execute the command docker ps, then I get this. 
![default](https://cloud.githubusercontent.com/assets/20349254/17127862/67e79450-533b-11e6-89b0-c7be90b626a5.PNG)

**Comment by ywg1990** [comment]
@thyeun I execute the command "docker-machine regenerate-certs Che", then I get this. 
![1](https://cloud.githubusercontent.com/assets/20349254/17127937/c8d97076-533b-11e6-99ce-889d7bff2bb6.PNG)

**Comment by thyeun** [comment]
@ywg1990 after you regenerate, can you manage to start machine che, with "Che run"?

**Comment by ywg1990** [comment]
@thyeun I execute the command "docker-machine regenerate-certs Che". It always stay on "Detecting the provisioner...".

**Comment by ghost** [comment]
@ywg1990 Can you remove all docker-machines, and then remove host only adapters in virtual box Settings > Network. So far, this is a Docker-Machine/Virtual box problem.

**Comment by thyeun** [comment]
@ywg1990 it look like you have more than one docker-machine, the best way to make it work is to remove all and re-do.

**Comment by ywg1990** [comment]
@eivantsov @thyeun   It WORKS! Thanks a lot! I remove all and re-do.

**Comment by ghost** [comment]
@ywg1990 Good to know!
