### ISSUE TITLE
k8s-image-puller should be used in workspace controller to provide better performance

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16866]
### Is your enhancement related to a problem? Please describe.
k8s-image-puller should be used in workspace controller to provide better performance.
It's quite critical for OpenShift Console Terminal.
I'm not sure about the way how k8s-image-puller should be delivered:
- OLM
- the controller should create `k8s-image-puller` resources by itself as it does with webhooks configuration.

**Comment by ibuziuk** [comment]
@sleshchenko FYI we already have the operator - https://operatorhub.io/operator/kubernetes-imagepuller-operator
