### ISSUE TITLE
In EKS, The service pauses as the che pod changes to the evicted state and restarts.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#16885]
## Summary
As shown in the screenshot below, the che is changed to the evicted state, and the service is temporarily paused during the time when the che is restarted.
This phenomenon appears not only in che, but also in keycloak, plugin-registry, etc. How to prevent the pod from restarting?

### Che version

7.4.0

### Runtime
kubernetes v1.15.10

### Screenshots

![KakaoTalk_Photo_2020-05-11-22-02-03](https://user-images.githubusercontent.com/29850624/81566957-93317d80-93d6-11ea-87fd-33310fed49e8.png)
![KakaoTalk_Photo_2020-05-11-22-01-56](https://user-images.githubusercontent.com/29850624/81566915-83b23480-93d6-11ea-8483-74a6e593d27a.png)

### Environment
Amazon EKS

**Comment by ibuziuk** [comment]
@kellyhyomin could you try to reproduce with the latest version of Eclipse Che - 7.12.2.
Also, please provide details based on the issue template about the installation method
cc: @tolusha any ideas here?

**Comment by tolusha** [comment]
Accordingly to the docs: `not sufficient resource on the node`
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods

To be honest, I've not seen such an error before.

**Comment by kellyhyomin** [comment]
@ibuziuk @tolusha 

This is due to the lack of volume (ebs) of ec2.
I really appreciate the help.
