### ISSUE TITLE
Implement devfile tests for Quarkus

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16882]
### Describe the solution you'd like
Just like with any other devfile test, we want to cover the basic functionality of the devfile, verify language server and test devfile commands

### Additional context
quarkus https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/quarkus

**Comment by ibuziuk** [comment]
Please, make sure that the test could be re-used as-is for Hosted Che without extra modifications

**Comment by ScrewTSW** [comment]
Tests are a little unstable, so @rhopp decided to skip them for now ([PR](https://github.com/eclipse/che/pull/17137)), but they are implemented, so I'm closing this issue.

**Comment by rhopp** [comment]
@ScrewTSW Please open a followup issue for fixing that.
