### ISSUE TITLE
Implement NodeJS devfile test

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16881]
### Describe the solution you'd like
Just like with any other devfile test, we want to cover the basic functionality of the devfile, verify language server and test devfile commands

### Additional context
nodejs-simple https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs

**Comment by ibuziuk** [comment]
Please, make sure that the test could be re-used as-is for Hosted Che without extra modifications
