### ISSUE TITLE
[Selenium] Update java selenium tests according to removing 'New Workspace' page

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#16899]
### Is your task related to a problem? Please describe.
After [Redesign "Create Custom Workspace" page](https://github.com/eclipse/che/issues/15662) changes for Dashboard all java selenium tests, that check workspaces creation, [fail](http://artifacts.ci.centos.org/devtools/che/che-nigthly-multiuser-stable-test/94/report/site/failsafe-report.html) (except tests from ```organization``` package). 

### Describe the solution you'd like
We need to update java selenium tests to create workspaces from "Create Custom Workspace" page.
Also according to ```New Workspaces``` page removing several tests need to deleted:
1. **NewWorkspacePageTest** - page was deleted;
2. **CreateWorkspaceTest** - page was deleted;
3. **CreateAndDeleteProjectsTest** - not possible to create workspace with projects;
4. **ImportMavenProjectFromGitTest** - not possible to create workspace with projects;
5. **ImportProjectFromGitHubTest** - not possible to create workspace with projects;
6. **AuthorizeOnGithubFromDashboardTest** - not possible to create workspace with projects.
7. **WorkspaceDetailsProjectsTest** - not possible to create workspace with projects;
8. **RecreateUpdateStrategyWithStartedWorkspaceTest** - operator doesn't support recreate strategy;
9. **RenameWorkspaceTest** - workspace renaming already checked by WorkspaceDetailsOverviewTest test.

**Comment by dmytro-ndp** [comment]
There is a plan to cover _Get Started Tab_ with **unit tests** in Dashboard https://github.com/eclipse/che/issues/16909
