### ISSUE TITLE
Terminal does not accept Input anymore

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#16891]
### Describe the bug
In the last two days, I've noticed that it happens in a self-hosting workspace for che-theia that terminal instances stop accepting keyboard input. The editor still works fine, I can open a new terminal and that works, but the first terminal seems dead.

### Che version
nightly on CRC (-a operator)

```
Che-Theia@1879602 using Theia@e2739410
Built 5/6/2020, 5:50:44 PM

### Steps to reproduce
None available.

### Environment
  Firefox on Windows

### Eclipse Che Logs
<!-- https://www.eclipse.org/che/docs/che-7/collecting-logs-using-chectl -->

### Additional context
<!-- Add any other context about the problem here. -->

**Comment by tsmaeder** [comment]
Unfortunately, there are not relevant logs.

**Comment by tsmaeder** [comment]
Maybe it's related: I just had an instance where input was going to the wrong editor: I had two editor tabs open: when I typed, input was not going to the editor in front, but to the editor that was hidden.
Could it be that keyboard focus is broken somehow?

**Comment by davidwindell** [comment]
We see a similar thing happening quite often. Sometimes pressing enter will re-activate the terminal but not always.

**Comment by tsmaeder** [comment]
I have now had a case that looked exactly like originally described, but once I pressed `<ctrl-c>` (which works again in Theia master), the terminal became responsive again. So it looks like the terminal is still channeling the input to a process that might not be there anymore.
@davidwindell if you ever see this again, could you test my theory?
