### ISSUE TITLE
Can't start machine dev-machine. Connection timed out

### ISSUE THREAD

**Issue by wiredwizardsCoach** [eclipse-che/che#169]
I am trying to run che on an Amazon EC2 instance running Ubuntu 14.04 (also tried Amazon AMI) and have trouble creating workspaces.  I get the following error:

2016-01-08 18:55:52,613[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 615]    - Can't start machine dev-machine. Connection timed out
org.eclipse.che.api.machine.server.exception.MachineException: Can't start machine dev-machine. Connection timed out
        at org.eclipse.che.api.machine.server.MachineManager.getRecipeByLocation(MachineManager.java:981) ~[che-core-api-machine-4.0.0-beta-5.jar:4.0.0-beta-5]
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:292) ~[che-core-api-machine-4.0.0-beta-5.jar:4.0.0-beta-5]
...

Everything I'm doing so far seems pretty boilerplate. The one exception of course is that my client browser is remote. Same thing happens if I launch it in a docker container vs. locally. Any idea what I'm doing wrong?

**Comment by TylerJewell** [comment]
Hi.

Couple questions:
1. Which version is installed?
2. This may be running into the DOCKER_MACHINE_HOST environment variable described here.
https://eclipse-che.readme.io/docs/configuration

Did you start Che with the --remote: option?

**Comment by wiredwizardsCoach** [comment]
I have used several versions:

1) Downloaded 4.0.0-beta5
2) Built 4.0.0-beta7
3) Ran docker with codenvy/che:latest and nightly

I did use -e "DOCKER_MACHINE_HOST=&lt;ip&gt;" on the `docker run` call as well as the --remote option (and also directly set it in che.sh).

This is what I ran to launch docker:
`$ docker run --privileged -e "DOCKER_MACHINE_HOST=10.0.0.103" -it --net=host codenvy/che:latest`

Local run (with configuration hard coded into the script)
`/opt/che/bin$ ./che.sh`

DOCKER_MACHINE_HOST=10.0.0.103
USE_DOCKER=false
CHE_DOCKER_TAG=latest
CHE_PORT=8080
CHE_IP=54.88.162.104
USE_HELP=false
CHE_SERVER_ACTION=run
VM=${CHE_DOCKER_MACHINE_NAME:-default}
USE_DEBUG=true

**Comment by TylerJewell** [comment]
Ahhh, well you shouldn't be changing anything in the script :)

Are you up for a live debugging session?  This use case is quite interesting.  We can do a google hangout, but I'd like to see the terminal of your EC2 node.

**Comment by wiredwizardsCoach** [comment]
Yeah, that would be easiest.

**Comment by TylerJewell** [comment]
https://plus.google.com/hangouts/_/codenvy.com/chris-lucian-tj?authuser=0

**Comment by garagatyi** [comment]
How do you create your workspace? Looks like Che was unable to download machine recipe.

**Comment by TylerJewell** [comment]
Some diagnostic information:
1. They created EC2 instance of Ubuntu on AMI.
2. Verified good version of Docker.
3. Running the instance on their VPN and it had both a publicly reachable IP & private one.
4. Workspace was never started - looked like image never got to be downloaded.
5. Binding Che to the private IP address was more successful - could create workspace & launch workspace agent.  Could only then connect using a browser that was behind their firewall.  However, in this configuration, was never able to create a project - got weird "project already exists" errors in IDE and dashboard when creating project.

**Comment by wiredwizardsCoach** [comment]
On a different topic we discovered, the issue with being unable to create a project was indeed the user permissions on the projects directory.  Red Hat makes new users have an ID starting at 500 while debian/ubuntu starts at 1000.  As a result, the permissions on the /project folder was 500 but the user "user" is ID 1000.  Changing that let me create a project no problem.

Back to the inability to launch a machine.  My suspicion at the moment is that it is due to NAT. The IP of my server is 10.0.0.68 but the IP I access it on is a public IP. This seems to wreck some havoc on the IPs that the system is using to communicate with (either with the web server or something else).  When I connect via a browser on the same internal network using the internal IP (the actual IP of the machine), everything is fine.

**Comment by TylerJewell** [comment]
Hi:  I have a pull request pending. These updates would have detected that
the Che server was either not in the docker group or not running in
UID=1000.

For now we will have to mandate Che can only run as UID=1000.  The internal
workspaces launched by Che have a docker container whose internal user is
UID=1000. If the Che server UID and the internal workspace UID do not
match, then write permissions will not exist for projects. We will need to
explore a more secure approach that allows admins to run Che under a
different UID and then propagate the same credentials into the workspace
machine.

https://github.com/codenvy/che/pull/168​

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by TylerJewell** [comment]
We have published a networking page that describes the various flows of communications and how admins can configure the product when different services are distributed.  Going to close this issue. Please create new issue if there is a new aspect to this that needs discussion.

https://eclipse-che.readme.io/docs/networking
