### ISSUE TITLE
Provide VS Code Extension "Atlassian for VS Code" in plug-in registry

### ISSUE THREAD

**Issue by pdaverh** [eclipse-che/che#16902]
### Is your enhancement related to a problem? Please describe.

Atlassian for VS Code is a popular plug-in and provides integration capabilities with JIRA and BitBucket. Supporting this plug-in would offer good value to developers on Eclipse Che.

### Describe the solution you'd like

Support the extension in Eclipse Che plug-in registry

**Comment by ericwill** [comment]
Fixed in https://github.com/eclipse/che-plugin-registry/pull/475
