### ISSUE TITLE
Revise using of rejectUnauthorized 

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#16906]
### Is your task related to a problem? Please describe.
At the moment in `chectl` we use `rejectUnauthorized: false` option when `AxiosInstance` makes requests to Che API.

### Describe the solution you'd like
Current approach works fine, but the right way is to use specific CA certificate for such requests.
We've [implemented](https://github.com/che-incubator/chectl/pull/669) retrieving of Che self-signed CA certificate which can be used to get the cert and pass to Axis to be able to connect to Che API without `rejectUnauthorized: fasle` option.
However, retrieving the cert each time chectl is run will add a few seconds to command execution time (at this point we need to make sure, that self-signed certificate is using, which could be done by checking for `self-signed-certificate` secret in Che's namespace). To reduce this time we may try to cache the cert in `tmp` directory (it will not bring a security risk as we export only public part of Che root CA certificate).

**Comment by tolusha** [comment]
Add some preflight chekcs, if cert is not valid, ask user to trust the server.

**Comment by tolusha** [comment]
Having [1] and [2] the necessity of this issue is quite low.
So I've decided not to spend time on this.

[1] https://github.com/eclipse/che/issues/20010
[2] https://github.com/eclipse/che/issues/19182
