### ISSUE TITLE
[chectl] Failed to deploy Eclipse Che using olm installer: Catalog Source not found

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16913]
### Describe the bug

Try to deploy with `chectl`, observe the error in ` catalog-operator` pod:
`failed: {eclipse-che stable  {community-operators olm}} not found: CatalogSource {community-operators olm} not found`

If update subscription from `catalogSourceNamespace: olm` to `catalogSourceNamespace: openshift-marketplace` then installation is continues successfully. 

### Che version

 - [x] nightly

### Expected behavior
Eclipse Che is deployed

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots
![Screenshot from 2020-05-13 14-37-29](https://user-images.githubusercontent.com/1640675/81811951-19aca300-952e-11ea-946d-12f2c910404f.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
`chectl server:start --platform openshift --installer olm -n abazko --self-signed-cert`

### Environment
   - [x] Cloud

**Comment by davidfestal** [comment]
@tolusha afaik using the `olm` catalog source namespace is for Kubernetes, and using the `openshift-marketplace` is for Openshift 4

**Comment by AndrienkoAleksandr** [comment]
Maybe we can try to determine namespace with catalog, at least for openshift 4:
kubectl get packagemanifest eclipse-che -o yaml
apiVersion: packages.operators.coreos.com/v1
kind: PackageManifest
metadata:
  creationTimestamp: "2020-02-14T06:49:48Z"
  labels:
    catalog: community-operators
    catalog-namespace: openshift-marketplace
    olm-visibility: hidden
    openshift-marketplace: "true"
    opsrc-datastore: "true"
    opsrc-owner-name: community-operators
    opsrc-owner-namespace: openshift-marketplace
    opsrc-provider: community
    provider: Eclipse Foundation
    provider-url: ""
  name: eclipse-che
  namespace: default
  selfLink: /apis/packages.operators.coreos.com/v1/namespaces/default/packagemanifests/eclipse-che
spec: {}
status:
  catalogSource: community-operators
  catalogSourceDisplayName: Community Operators
  **catalogSourceNamespace: openshift-marketplace**
  catalogSourcePublisher: Red Hat
