### ISSUE TITLE
Cover Get Started Tab with e2e tests in dashboard-next

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#16911]
The Get Started Tab is going to be [finalized soon](https://github.com/eclipse/che/issues/16709) and we need to be sure that the whole page which consists of multiple parts works as expected.

Depends on #16709, https://github.com/eclipse/che/issues/16910

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/18428
