### ISSUE TITLE
[devworkspace] controller must make sure that workspace is created after webhooks

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16914]
### Is your task related to a problem? Please describe.
This issue is about covering corner case where privileged escalation is possible:
- a controller is not installed, and there are no webhooks as well;
- "tiny admin" (not the whole cluster but has like CRD creation permission) registers Workspace CRDs, creates Workspace CR with victims uid as creator annotation;
- the cluster-admin set's up Workspace Controller;
- workspace with the fake creator annotation and the specified configuration is running and victims potentially could send there their personal token with OpenShift Console Proxy;

So, a controller must make sure that workspace is created after webhooks are created if webhooks are enabled.

**Comment by amisevsk** [comment]
Open questions here: is it possible for the "tiny admin" to create webhooks before they create a workspace/will the controller just reuse existing webhooks on start? How do we make sure this functionality doesn't fail all running workspaces if webhooks are recreated?

It's a longer-term issue, but if we're relying on PVCs, failing a workspace could be an issue where work is lost, as deletion of the workspace would mean deletion of the stored data.

**Comment by sleshchenko** [comment]
> Open questions here: is it possible for the "tiny admin" to create webhooks before they create a workspace/will the controller just reuse existing webhooks on start?

I hope no, if tiny admin is able to modify webhooks - then I think we all agreed that we can't not secure other users' tokens from such admin, since they are able to like set another failure policy or remove webhooks at all.

> How do we make sure this functionality doesn't fail all running workspaces if webhooks are recreated?

Good point. I don't have an idea of how we can handle webhooks recreation... But what could be an alternative solution for the described security issue:
- make Kubernetes/OpenShift by itself provide info about object's creator. Ideal solution but not much we can do with that quickly.

> It's a longer-term issue, but if we're relying on PVCs, failing a workspace could be an issue where work is lost, as deletion of the workspace would mean deletion of the stored data.

We can propose instructions on how to reuse existing PVCs for new workspace: like create a new workspace, get its id, update PVC with new workspace id label, manually migrate files to new workspace id subfolder, delete old workspace. 
Sounds not really well, but it could be one command of chectl - `workspace:migrate/recreate existing`

**Comment by amisevsk** [comment]
From discussion in standup today: this issue may be irrelevant, since only a cluster-admin can grant rights to create workspaces.

**Comment by sleshchenko** [comment]
We must take a deeper look on that.
Probably implementing this issue - would make our solution even more secure but it has a pretty big drawback: if webhook configurations are removed occasionally - we need a recovery procedure that will allow restoring workspace which became broken. For typically webterminal use-case without PVC the answer is just to recreate a workspace but if PVC is configured in workspace then I don't have a good idea of what we can propose here.

**Comment by amisevsk** [comment]
Agreed -- it should be fairly simple to implement the mainline case (compare creationTimestamps, for example) but edge cases are a problem. If we can decide that this issue isn't crucial at the moment, it may make sense to implement a mechanism for distinguishing "sensitive" workspaces from regular as we work on full devworkspace support -- most regular workspaces might not need to have a user's access token stored inside them. 

Alternatively, if it *is* crucial for the moment, we could use the fact that we're only supporting web terminals initially to implement a web-terminal-specific solution (compare timestamps) and then adapt it to support the edge cases down the line (don't apply restriction to regular workspaces).
