### ISSUE TITLE
Have a common place for QE scripts used in multiple repositories (to avoid duplication)

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#16923]
Currently we use a lot of duplicated code for running CI jobs with tests on "ci.centos.org" for different repo which Che dependent for (devfile registry, plugin registry ...). For avoiding duplication it would be great to have common methods in one place. It will simplify managing of the existing jobs and creation of the new.  Also in this way we will avoid a lot of duplications.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/17103
