### ISSUE TITLE
Code navigation inconsistencies

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16929]
### Describe the bug
Ctrl+F12 doesn't behave the same as Ctrl+click compared to VS Code where the result of the actions is exactly the same

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: 7.12.x

### Steps to reproduce
* Open Golang example devfile
* go into outyet/main.go or any other go file
* set your cursor over a method call
* hit ctrl+F12 - a small tooltip will appear saying that there is no implementation for the method
* hit ctrl + click on the method - you will be taken to it's implementation

### Expected behavior
* both actions have the same result

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift
```
Client Version: 4.3.9
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
Ctrl+click
![Screenshot_20200514_095249](https://user-images.githubusercontent.com/16451875/81925459-df500e00-95e0-11ea-92ac-51d4352f242e.png)
Ctrl+F12
![Screenshot_20200514_095226](https://user-images.githubusercontent.com/16451875/81925476-e4ad5880-95e0-11ea-9f68-d44a1917906e.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che `chectl server:start -a operator -p openshift --self-signed-cert -n <namespace>`
     * provide an output of `chectl version` command `chectl/7.12.2 linux-x64 node-v10.20.1`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other - coredeady.qe OCP 4.3 cluster
   - [ ] other: please specify

**Comment by ScrewTSW** [comment]
I'm extending this issue to be general, the same behaviour was observed in NodeJS devfile as well.

**Comment by ScrewTSW** [comment]
Same issue found with .NET Core stack

**Comment by ScrewTSW** [comment]
same issue found with C/C++ devfile
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/cpp

**Comment by ScrewTSW** [comment]
same issue found with NodeJS Mongo devfile
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs-mongo

**Comment by Katka92** [comment]
Seen also in a `NodeJS Web Application based on Yarn` devfile.
https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/nodejs-yarn

**Comment by Katka92** [comment]
Seen also in a `PHP Symphony` stack.
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/php-symfony

**Comment by ScrewTSW** [comment]
Also seen in `PHP MySQL` devfile.
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/php-mysql

**Comment by gattytto** [comment]
I found the error it's in the golang sidecar, it needs an update to[ entrypoint.sh](https://github.com/gattytto-dockerfiles/che-sidecar-go/blob/master/etc/entrypoint.sh) that fixes ownership of /.cache and also the [dockerfile](https://github.com/gattytto-dockerfiles/che-sidecar-go/blob/master/Dockerfile) has to pre-create it and chmod 777 to it.

![image](https://user-images.githubusercontent.com/407397/87234306-fd9a7600-c3a5-11ea-8647-9c4d82553fa8.png)

https://github.com/golang/go/issues/40139#issuecomment-657133819

**Comment by ericwill** [comment]
Sounds like this was happening in more than one place, so re-opening the ticket. Thanks for the golang fix @gattytto!

**Comment by tsmaeder** [comment]
@Katka92 @ScrewTSW it would help if you described the failures for nodejs, etc. a bit more: which files are you opening, does it give the exact same error message, do other operations work (ctrl-space, for example).  There are many failure modes, trying to see if this is the same kind of problem.

**Comment by ScrewTSW** [comment]
@tsmaeder The issue appears once LS is fully initialized. Other actions as Ctrl + Space work as intended. The problem is that while Ctrl + click opens the implementation file, Ctrl + F12 just says that there is no implementation for that method. 

There are two failure modes:
* Tooltip window with a same message (no implementation found).
* Empty peek window
![Screenshot_20200716_093842](https://user-images.githubusercontent.com/16451875/87641413-5a03e980-c748-11ea-9310-73f493aed5a1.png)

NodeJS Express Web Application:
* open app/app.js
* head over to line 22 - app.listen()
* Press Ctrl + F12
* Empty peek window is displayed

.NET Core:
* Open Program.cs
* Update dependencies
* Head over to line 21 - BuildWebHost(args).Run()
* Press Ctrl + F12
* No implementation found for Run tooltip appears
Ctrl + click opens the file successfully

Rest of the stacks follow these failure modes.

**Comment by tsmaeder** [comment]
Thanks, @ScrewTSW that is a very helpful reproducer :-)

**Comment by ScrewTSW** [comment]
After some discussion with plugins team, it seems that this is a feature and not a bug.
What shortcuts for `Go to Implementation` and `Do to Definition` are exposed to the user is entirely dependant on the language server used.
@tsmaeder
