### ISSUE TITLE
Switch to the new Operator Bundle Format

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16928]
### Is your enhancement related to a problem? Please describe.
We should switch to the new format to:
* Leverage the benefits of the new way (no manage all the versions in a single Git branch for example)
* Be ready in time for when the old format disappears

### Additional context
https://github.com/operator-framework/community-operators/issues/1680

**Comment by AndrienkoAleksandr** [comment]
Related doc https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md

**Comment by AndrienkoAleksandr** [comment]
Current changes in the branch 'opmBundle'

**Comment by AndrienkoAleksandr** [comment]
Faced with https://github.com/operator-framework/operator-registry/issues/385#issuecomment-658158307

**Comment by nickboldt** [comment]
CRW is moving to new format in 2.3 so we can be ready before the OCP 4.6 code freeze later this month (in case we discover a problem). Might be wise to try to do the same for upstream Che, if possible. Che 7.17.0 is on Aug 5, which might be too late to get changes into OCP 4.6.

**Comment by nickboldt** [comment]
> Faced with operator-framework/operator-registry#385 (comment)

```
ime="2020-07-14T11:42:57Z" level=info msg="Reading file" file=/bundle/manifests/eclipse-che-preview-kubernetes.crd.yaml
time="2020-07-14T11:42:57Z" level=info msg="Reading file" file=/bundle/manifests/eclipse-che-preview-kubernetes.package.yaml
time="2020-07-14T11:42:57Z" level=info msg="Reading file" file=/bundle/manifests/eclipse-che-preview-kubernetes.v7.0.0-beta-5.0.clusterserviceversion.yaml
time="2020-07-14T11:42:57Z" level=info msg="Reading file" file=/bundle/manifests/eclipse-che-preview-kubernetes.v7.0.0-rc-2.0.clusterserviceversion.yaml
time="2020-07-14T11:42:57Z" level=info msg="Reading file" file=/bundle/manifests/eclipse-che-preview-kubernetes.v7.0.0-rc-
```

Maybe it's time to trash the old unsupported CVS versions? At this point there should be nothing in there earlier than, say, Che 7.12, since anything earlier than that will NEVER get a z-stream bug fix.

**Comment by tolusha** [comment]
We need to answer the following questions:
1. When https://github.com/operator-framework/community-operators/ repository is ready to accept PR with the new operator bundle format.
2. Should we replace old format on a new one in the very first PR ?
3. Will users be able update to a newer version of Eclipse Che on OpenShift < 4.6 ?

@nickboldt  Do you know answers for some of these questions?

**Comment by AndrienkoAleksandr** [comment]
> Will users be able update to a newer version of Eclipse Che on OpenShift < 4.6 ?

I tested Che catalog index image with openshit 4.2 - 4.6, technically installation works fine. But on the openshift 4.2 - 4.5 used catalog source based on the application registry. So even if we will merge some new Che versions in the new bundle format to the community catalog, on the openshift 4.2 - 4.5 these version won't appears. For enterprise operators, operator maintainers can apply label in the catalogsource Dockerfile "backport" and their operators will be backported and pushed to the application registry. But I don't think that it is working for community operators.

**Comment by AndrienkoAleksandr** [comment]
In the community meeting, olm developers shared information: community operators will be auto-migrated to the new bundle format to make them working with openshfit >= 4.6. And they will care about auto-update application registry with new operator versions for older Openshift < 4.6

**Comment by tolusha** [comment]
This issue is postponed until community operators migrate to the new bundle format.
