### ISSUE TITLE
As a developer using a che java image, I should be able to add a TLS certificate to my trust store

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#16920]
### Is your enhancement related to a problem? Please describe.

I encountered this problem when working on the che telemetry system in che using the java8-maven image, but I assume it has happened in other use cases.  

The telemetry system needs to send and receive messages from the Che API that is secured with TLS.  These calls fail with PKIX errors, and when you try to use `keytool` to add a certificate to `$JAVA_HOME/jre/lib/security/cacerts`, the `user` user does not have enough permissions to add something to that file.

### Describe the solution you'd like

I would like to be able to add a TLS certificate to `cacerts` in the `che-java8-maven` and `che-java11-maven` images.

### Describe alternatives you've considered

The only alternative is to extend `quay.io/eclipse/che-java8-maven:nightly` and do the `chmod` yourself.

**Comment by tolusha** [comment]
@tomgeorge 

Does it solve the problem?
https://www.eclipse.org/che/docs/che-7/using-maven-artifact-repositories/#using-self-signed-certificates-in-java-projects_using-maven-artifact-repositories

**Comment by tomgeorge** [comment]
I didn't know about this, but this looks like what I'm looking for.  I'll try and report back.

**Comment by tomgeorge** [comment]
This works for me, thank you!  Closing
