### ISSUE TITLE
[workspace-controller] Can't switch running workspace from basic routing to openshift-oauth

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16935]
### Describe the bug
Switching an already created workspace from `routingClass: basic` to `routingClass: openshift-oauth` will cause the updated deployment to fail to initialize with
```
MountVolume.SetUp failed for volume "workspace1c9887398ca54617-proxy-tls" : secret "workspace1c9887398ca54617-proxy-tls" not found
```

This is because the service does not get updated, since we ignore metadata in checking for changes.

**Comment by sleshchenko** [comment]
I suppose it should be fixed by https://github.com/che-incubator/che-workspace-operator/pull/81/commits/209a7bf8ee7f0f1b0193218d645a1bb826c5c7fb

**Comment by sleshchenko** [comment]
I remember I was able to switch created workspace from basic to openshift-oauth and it seems to work then.
