### ISSUE TITLE
Openshift autologin should help the user if the browser blocking popups

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16930]
### Is your enhancement related to a problem? Please describe.
https://github.com/eclipse/che/issues/15261 was implemented to automatically connect the user with his openshift account without any additional action.
However, the plugin opens a popup window which would be blocked by the browser the first time.
The plugin is then spining forever

![image](https://user-images.githubusercontent.com/650571/81931575-a026ba80-95ea-11ea-8d3a-5c9db080522a.png)

The enhancement for this issue would be to add a warning Che notification telling the user that the popup window is blocked and that restarting the workspace would be needed to have the autologin working.

**Comment by nickboldt** [comment]
is this on track for Che 7.16? We'd like this to work OOTB in CRW 2.3.

**Comment by sunix** [comment]
@vinokurig Could you add screenshots on how it looks like?

**Comment by vinokurig** [comment]
@sunix 
![screenshot-server59f74m1p-che-dev-server-3010 192 168 99 254 nip io-2020 07 28-15_00_38](https://user-images.githubusercontent.com/7668752/88662809-2d09ec00-d0e3-11ea-8e9f-b3ef195fe449.png)
