### ISSUE TITLE
Prepare WebTerminal tooling image

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16938]
### Is your enhancement related to a problem? Please describe.

The OpenShift Command Line Terminal should provide some tooling out of the box including:
- [x] bash
- [x] oc 
- [x] odo
- [x] kubectl
- [x] kubens
- [x] kubectx
- [x] helm
- [x] [tkn](https://github.com/tektoncd/cli)
- [x] [kn](https://github.com/knative/client)
- [ ] istioctl
- [ ] crwctl
- [x] curl
- [x] git
- [ ] https://kislyuk.github.io/yq/
- [x] jq
- [x] watch

**Comment by amisevsk** [comment]
To add: the default shell in most of the plugin containers (including `registry.redhat.io/codeready-workspaces/plugin-openshift-rhel8:2.1`, which is currently used) is set to `/bin/sh` even though bash is installed.

**Comment by nickboldt** [comment]
we can switch the default shell to bash if you throw me a PR... 

http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces-plugin-openshift/tree/?h=crw-2.2-rhel-8

Similarly if we need to install more tools there, PRs welcome.

**Comment by nickboldt** [comment]
seems unlikely we would have `crwctl` in the openshift container though... why would we need that if it's only supported for OCP 3.11 installation, and the oc/odo/kubectl alternatives are already present in the image?

**Comment by sleshchenko** [comment]
@nickboldt Are we going to override existing 2.1 tag or we'll get 2.2 after PR are merged and CRW 2.2 is released?
It's critical for OpenShift Console to get right image before code freeze because this image is in front-end source code.

**Comment by nickboldt** [comment]
if you need something in 2.1.2 release, please ping Martha or Mario to escalate. 

otherwise the next CRW release is 2.2.0, in late June.

**Comment by nickboldt** [comment]
it's also possible to create a new sidecar image that extends the crw plugin-openshift-rhel8:2.1 container to add all the other stuff you need. then for 2.3 we could deprecate it in favour of plugin-openshift-rhel8:2.3, if all the features you need are pushed upstream from Terminal into CRW.

**Comment by sleshchenko** [comment]
I would add `jq` and `yq` in the proposed list if it's not already there.

**Comment by sleshchenko** [comment]
Create new repo:
- redhat-developers/openshift-terminal: OLM manifests + command-line-terminal dev container Dockerfile
^ should be sync with devel

Existing
- che-incubator/che-workspace-operator
TODO Sync with Nick if che-incubator repo + devel is enough for controller image

**Comment by nickboldt** [comment]
can you link to `che-openshift-plugin`  sources and quay image? It would be handy to know what we're talking about here and why we don't want to reuse the quay.io/crw/plugin-openshift-rhel8 one (or registry.redhat.io/codeready-workspaces/plugin-openshift-rhel8 if quay is still down)

* http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces-plugin-openshift/tree/?h=crw-2.0-rhel-8

**Comment by ericwill** [comment]
Sidecar sources for the OpenShift connector plugin sidecar are [here](https://github.com/che-dockerfiles/che-sidecar-openshift-connector/blob/master/Dockerfile). The images live [here](https://quay.io/repository/eclipse/che-sidecar-openshift-connector?tag=latest&tab=tags).

My understanding is that the CRW images are separate from upstream, so if this is a downstream only change it should probably go there. That said if it's needed upstream I have no objection to it landing in the upstream plugin sidecar.

**Comment by sleshchenko** [comment]
One more tool to consider to add - watch

**Comment by l0rd** [comment]
I have renamed the repo and provided [a first draft of the Dockerfile with a few of the above tools](https://github.com/redhat-developer/web-terminal-tooling/blob/master/Dockerfile).

**Comment by sspeiche** [comment]
Not sure why we'd ship all these things. What's the justification for a bunch of binaries that there may not be an operator. I'd rather find a way that operators can ship binaries and register them or make them available to the web terminal. Web terminal shouldn't be in the business of shipping "all the binaries". We need to push on https://github.com/openshift/enhancements/pull/137 instead

**Comment by davidfestal** [comment]
> We need to push on openshift/enhancements#137 instead

I imagine that being compatible with this enhancement, and thus being able to reduce the number of tools embedded inside the web terminal container image, should certainly be a long-term goal.

But does it prevent us starting with embedding the tools as a short-term solution ?
It seems to be mainly an implementation question on the web terminal side, no ?

**Comment by l0rd** [comment]
@sspeiche that's an interesting idea that we may consider in the future.

**Comment by nickboldt** [comment]
Not done in 7.14, and won't be done in 7.15 (sprint ends in 2 days) so punting to backlog.

**Comment by sleshchenko** [comment]
The initial implementation is done in https://github.com/redhat-developer/web-terminal-tooling/pull/1
