### ISSUE TITLE
Strange error message during account provisioning on OSIO

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#16937]
### Describe the bug
My OSIO account was accidentally suspended. So i requested creation of the new one,  and during provisioning performed in parallel tab,  such error appeared.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Create new account on che.opehsnift.io

### Expected behavior
Account provisioned, user is entered dashboard

### Screenshots
![object_object](https://user-images.githubusercontent.com/1651062/81973131-5b237800-962c-11ea-8f02-570114693dc1.png)

**Comment by skabashnyuk** [comment]
Duplicate https://github.com/eclipse/che/issues/16719 ?

**Comment by mshaposhnik** [comment]
Yes, co may be closed.
