### ISSUE TITLE
[devworkspace] Plugin registry should be created inside of che-workspace-controller

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#16946]
### Is your task related to a problem? Please describe.

In order to get OLM working with the che-workspace-controller we need to move the creation of the che plugin registry inside of the controller itself, instead of using the YAMLs to deploy it. This task includes creating the deployment, the service, and the route/ingress depending on the platform.

### Describe the solution you'd like

Creation of che plugin registry deployment, service, and route/ingress should be done inside of che-workspace-controller

**Comment by amisevsk** [comment]
@sleshchenko Bumped this to P1 since it blocks OLM

**Comment by JPinkney** [comment]
@amisevsk I think the reason why it was put at p2 was because if we're just using cloud shell we technically don't need it since we can just get by with the internal registry. But if we do a release of the operator where we want to use theia, etc then we'd need it

**Comment by amisevsk** [comment]
Ahh good point, I forgot about that.

**Comment by l0rd** [comment]
We shouldn't need that anymore. Closing.
