### ISSUE TITLE
Can't authenticate on github

### ISSUE THREAD

**Issue by AugustoEMoreira** [eclipse-che/che#1694]
When i tried to authenticate i recive this menssage: {"message":"Unsupported OAuth provider github"}

**Reproduction Steps:**

1 - Menu Profile
2 - Preferences
3 - VCS
4 - github button 
5 - A dialog box show: "Eclipse Che requests authorization through OAuth2 protocol" - i clicked in OK
6 - A new page goes up with the menssage {"message":"Unsupported OAuth provider github"}

**Che version:**  4.4.2
**OS and version:** Ubuntu 14.04(the che docker)  
**Docker version:** 1.11.2
**Che install:** https://hub.docker.com/r/codenvy/che/

I think this can be a big mistake from my side, but i do know what

Thanks for help

sorry for my poor english

**Comment by TylerJewell** [comment]
Hi @AugustoEMoreira Did you try adding an SSH key in the IDE preferences?  You may need to upload one.

**Comment by AugustoEMoreira** [comment]
no, how can i do this for github?

**Comment by ghost** [comment]
@AugustoEMoreira 
https://eclipse-che.readme.io/docs/usage-docker#section-configure-che
https://eclipse-che.readme.io/docs/git#section-github

**Comment by rwallinterset** [comment]
@eivantsov If you are doing GitHub you shouldn't have to upload a key should you?  It should redirect you to GitHub to allow access assuming oauth is properly added to che.properties.

This sounds similar to the issue I had, oAuth settings in che.properties not getting picked up #1696

Actually I see from the steps this isn't the same issue as I was clicking to import existing project from new Project Wizard.

**Comment by thyeun** [comment]
For me it working fine. i done it with the below step

First, go to the Github "setting", and create a new auth key as show from the below pic
![gitauth1](https://cloud.githubusercontent.com/assets/1939446/16737954/3981f9be-47c6-11e6-962f-8613537ffd98.JPG)

![gitauth2](https://cloud.githubusercontent.com/assets/1939446/16737983/5ae34b08-47c6-11e6-97ae-b0ffc152226c.JPG)

Second, once you created the auth from github and have the key, then you have to set it on your "che.properties".as show from the below pic (remember to change the key from your created at github auth)
![gitauth](https://cloud.githubusercontent.com/assets/1939446/16738074/bf3622f6-47c6-11e6-9d0f-65c6c56b75db.JPG)

3rd, once che.properties are setting up, you can go into your localhost:8080 and look for the "VCS" and click the "github octocat" icon and grant access

4th, the final successful will be look like the below pic
![gitauth3](https://cloud.githubusercontent.com/assets/1939446/16738200/4d885e0c-47c7-11e6-880e-9770c4ea888f.JPG)

hope it help you

p/s : i'm using eclipse che 4.4.0

**Comment by ghost** [comment]
@AugustoEMoreira @rwallinterset any update on this issue? Were you able to configure GitHub oAuth?

**Comment by ddementieva** [comment]
Docs updated: https://eclipse-che.readme.io/v4.4/docs/git#section-github

**Comment by ghost** [comment]
I'm closing this issue - instructions posted both here and in docs. Feel free to reopen if you face problems with GitHub oAuth in Che.

**Comment by stianlagstad** [comment]
I'm trying to clone a private Github repository while using Eclipse Che locally with Docker, and I'm struggling to find a guide with steps to follow. The docs at https://eclipse-che.readme.io/ are no longer available. The "OAuth applications" menu item (ref https://github.com/eclipse/che/issues/1694#issuecomment-231787509) in Github settings is no longer available. I've figured that I need to set up these environment variables:
```
CHE_OAUTH_GITHUB_CLIENTID=your_github_client_id
CHE_OAUTH_GITHUB_CLIENTSECRET=your_github_client_secret
CHE_OAUTH_GITHUB_AUTHURI=https://github.com/login/oauth/authorize
CHE_OAUTH_GITHUB_TOKENURI=https://github.com/login/oauth/access_token
```
But I don't know where and how to get values for these. Is there an up to date guide somewhere?

**Comment by hXtreme** [comment]
I'm having the same issue and the provided links don't work.
