### ISSUE TITLE
Failed to create workspace minikube with che-operator 7.13.0

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16944]
### Describe the bug
Failed to create workspace minikube with che-operator 7.13.0

### Che version

 - [x] other: 7.13.0

### Steps to reproduce
`chectl server:start --che-operator-image quay.io/eclipse/che-operator:7.13.0  --platform minikube`

### Runtime
   - [x] minikube 1.8.2 (include output of `minikube version` and `kubectl version`)

### Screenshots
![Screenshot from 2020-05-15 16-31-36](https://user-images.githubusercontent.com/1640675/82055701-932cc880-96c9-11ea-9b43-ab2351ba12b1.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command 
`chectl/0.0.20200515-next.50a4b41 linux-x64 node-v10.20.1`

### Environment
   - [ ] my computer
       - [x] Linux

### Eclipse Che Logs
https://gist.github.com/tolusha/46586614386fc6c3c2c79d59ac46f377

**Comment by tolusha** [comment]
In conjunction with che-server 7.12.2 it works.

**Comment by skabashnyuk** [comment]
Probably related to  JDK 8u252 https://github.com/fabric8io/kubernetes-client/issues/2212#issuecomment-628434995

**Comment by skabashnyuk** [comment]
workaround
```yaml
    customCheProperties:
      HTTP2_DISABLE: 'true'
```

**Comment by skabashnyuk** [comment]
backported to 7.13.x https://github.com/eclipse/che/commit/93e47da15aaaf636fcfa2c5d81488962ca97e5aa
