### ISSUE TITLE
Add required VS Code commands for vscode-didact extension

### ISSUE THREAD

**Issue by bfitzpat** [eclipse-che/che#16940]
Working to add Didact support in Che

https://marketplace.visualstudio.com/items?itemName=redhat.vscode-didact

Identified missing VS Code commands implementation in Che-Theia:
- [x] explorer.newFolder (PR: https://github.com/eclipse-theia/theia/pull/7843)
- [x] workbench.view.explorer (PR: https://github.com/eclipse-theia/theia/pull/7965)
- [x] workbench.action.terminal.sendSequence (PR: https://github.com/eclipse-theia/theia/pull/7906)
- [x] workbench.action.terminal.kill (PR: https://github.com/eclipse-theia/theia/pull/7906)
- [x] copyFilePath (PR: https://github.com/eclipse-theia/theia/pull/7934)

Epic for missing VS Code commands here https://github.com/eclipse-theia/theia/issues/4050

**Comment by apupier** [comment]
related draft PR https://github.com/eclipse/che-plugin-registry/pull/459

**Comment by apupier** [comment]
@ericwill do you have an idea when the mentioned commands will be available in Che? (seems latest release of Eclipse Theia doesn't contain all of them: https://github.com/eclipse-theia/theia/releases/tag/v1.2.0 ) If I understand well, it mean sa new release of Eclipse Theia, then to Che to pick the new release.

**Comment by azatsarynnyy** [comment]
Hello @apupier 
all of the implemented commands will be available in Che 7.15, which is going to be released this week

**Comment by azatsarynnyy** [comment]
BTW it can be tested with Che Theia next

**Comment by azatsarynnyy** [comment]
I'm closing it as all of the required commands support were added in upstream Theia.

**Comment by apupier** [comment]
renamed the issue as the VS Code Didact extension has not been added. Only the missing commands has been implemented. And created a specific follow-up task
