### ISSUE TITLE
Cannot edit user account within Account Page in Dashboard

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#16957]
### Describe the bug
There is ```An internal server error has occurred```error message when try to edit user account in Keycloak. 
And there is ```ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-1) Uncaught server error: java.lang.IllegalArgumentException: Invalid URL syntax: Illegal character in fragment at index 69: https://che-dashboard-che.apps.ocp311.crw/dashboard/#/account?tab=Get  Started``` error in Keycloak pod.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. From **Dashboard** open **Account** page(see screencast).
2. Click on Edit button and wait for Keycloak Edit Account page.
3. Click on Password tab.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_117](https://user-images.githubusercontent.com/7760565/82116277-48ff2200-9771-11ea-8cf2-0e02e30e52bc.png)

### Screencast
![screencast-console ocp311 crw_8443-2020 05 16-12_29_36](https://user-images.githubusercontent.com/7760565/82116271-3dabf680-9771-11ea-81c6-aad86756484c.gif)

### Installation method
   - [x] chectl
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Keycloak Logs
```
09:25:59,700 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-1) Uncaught server error: java.lang.IllegalArgumentException: Invalid URL syntax: Illegal character in fragment at index 69: https://che-dashboard-che.apps.ocp311.crw/dashboard/#/account?tab=Get  Started
--
  | at org.keycloak.protocol.oidc.utils.RedirectUtils.normalizeUrl(RedirectUtils.java:185)
  | at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:83)
  | at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:52)
  | at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:47)
  | at 
```
All Keycloak log is at the end of build report - https://ci.centos.org/job/devtools-che-pullrequests-java-selenium-tests/247/console.

**Comment by SkorikSergey** [comment]
@olexii4 @sleshchenko Can you check this issue?

**Comment by dmytro-ndp** [comment]
@SkorikSergey: did you try to change password from login page?

**Comment by SkorikSergey** [comment]
> @SkorikSergey: did you try to change password from login page?

I will check it

**Comment by SkorikSergey** [comment]
@dmytro-ndp ```Forgot Password``` feature works as expected.

**Comment by dmytro-ndp** [comment]
@SkorikSergey: thank you for investigation!
