### ISSUE TITLE
che-theia 7.11+ depends on custom nodejs alpine image with no rhel equivalent [prod'tzn regression]

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16951]
In Che 7.11, this change happened in the endpoint runtime build:

```
FROM quay.io/eclipse/che-custom-nodejs-deasync:10.19.0-latest as custom-nodejs
...
ENV NEXE_FLAGS="--asset ${HOME}/pre-assembly-nodejs-static"
COPY --from=custom-nodejs /pre-assembly-nodejs-static ${HOME}/pre-assembly-nodejs-static
```
-- https://github.com/eclipse/che-theia/commit/06ef7ee00cbb4724c0541e232a11418e0559e35a

So now, even though the che-theia build is theoretically able to run against alpine OR ubi, it has a hard dependency on https://github.com/che-dockerfiles/che-custom-nodejs-deasync/blob/master/Dockerfile which of course has no rhel/ubi analogue.

The result is that the crw theia-endpoint-rhel8 container cannot be built in Brew because:

```
Dockerfile: '\''quay.io/eclipse/che-custom-nodejs-deasync:10.20.1'\''; expected registry: '\''registry-proxy.engineering.redhat.com'\'''
```

This means we either need to 

* add yet another intermediate docker build stage to the already many-step theia-dev, theia, theia-endpoint build process (which is at least 6 docker builds and a dozen docker run commands to extract artifacts)
* or remove this dependency on `quay.io/eclipse/che-custom-nodejs-deasync` 

This is feature something that we really need in Che, and if so, is there any other way to build it into the endpoint runtime binary?

**Comment by nickboldt** [comment]
I have marked this blocker until we figure out how we can inject this into the rhel8-based endpoint runtime image, or decide that along with the `theia-dev-rhel8` container, we need an actual new image to be published via Comet to RHCC.

**Comment by benoitf** [comment]
not a blocker for Che it works perfectly

**Comment by nickboldt** [comment]
As I said, I was marking it a blocker because I need help determining how to proceed w/ downstreaming this. You've effectively prevented che-theia from being built in a pure rhel-based approach, which while not a blocker for Che or Hosted Che, is certainly a regression from how things were in 7.9 and 7.10.

**Comment by nickboldt** [comment]
PR: https://github.com/eclipse/che-theia/pull/748

**Comment by benoitf** [comment]
fixed
