### ISSUE TITLE
Unable to get custom attributes from keycloak through the api Profile.getAttributes()

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#16956]
Hi all,
For che, I have customized keycloak to use an external idp to login. Login works fine.
I have defined custom attribute mappers for translating saml fields into user attributes as shown in the picture: https://raw.githubusercontent.com/cherxp/shared-files/master/idp-attribute-mappers.png
Those Attribute mappers are `test-mapper-1` & `test-mapper-2`.

Using che api, i'm trying to get the attributes like the following:
```
Profile profile = profileManager.getById(userId);
Map<String, String> attributes = profile.getAttributes();

// Test to check if we get all attributes
for (Entry<String, String> entry : attributes.entrySet()) {
        System.out.println(entry);
}
```
But, all attributes are not returned. i.e., the custom attributes like `test-mapper-1` and `test-mapper-2` are not returned. Please refer to the attached image for mappers.

Can anyone help me get all the attributes, please?

che version used : 7.5.1
keycloak image: eclipse/che-keycloak:7.5.1

also, `cheWorkspacesNamespace: "che"`
`.Values.global.serverStrategy` = `multi-host`

also, in _hostHelper.tpl, i changed the folllwing code:
```
{{- define "cheHost" }}
{{- if or (eq .Values.global.serverStrategy "default-host") (eq .Values.global.serverStrategy "single-host") }}
{{- printf "%s" .Values.global.ingressDomain }}
{{- else }}
{{- printf "che-%s.%s" .Release.Namespace .Values.global.ingressDomain }}
{{- end }}
{{- end }}
```

CHANGED IT AS:
```
{{- define "cheHost" }}
{{- if or (eq .Values.global.serverStrategy "default-host") (eq .Values.global.serverStrategy "single-host") }}
{{- printf "%s" .Values.global.ingressDomain }}
{{- else }}
{{- printf "myapp.%s" .Values.global.ingressDomain }}
{{- end }}
{{- end }}
```

**Comment by sleshchenko** [comment]
@svkr2k Please take a look https://github.com/eclipse/che/blob/998c413ab70d20d67b5f0a4462d25b97e6812d7f/multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakProfileRetriever.java#L31
There is used URL returned by keycloak info, which is formed in https://github.com/eclipse/che/blob/998c413ab70d20d67b5f0a4462d25b97e6812d7f/multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakSettings.java#L51

Please check is ProfileRetriever has the right URL and if you request keycloak manually - does it return profile properties?

**Comment by svkr2k** [comment]
Thank you, @sleshchenko .
I figured out that the Client Protocol Mappers in che-public were missing. After i added those, i was able to get all the attributes through profile api.
Thank you very much !
