### ISSUE TITLE
chectl should use current namespace if no namespace is specified

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16958]
Currently, if the users doesn't specifies a namespace, chectl deploys che in the default namespace (che). For consistency with other command line tools the current user namespace should be used instead. That is true for `chectl server:delete` as well: if no namespace is specified the current one should be considered, not the default (`che`).

**Comment by sleshchenko** [comment]
I would like to see user's confirmation `you're going install Che on cluster XXX in namespace XXX. Press Y to continue` before proceeding to install into the current namespace.
@l0rd Do you think such confirmation would be useful or redundant?

**Comment by l0rd** [comment]
Ok but for consistency it should be interactive in every case then (even when flag `--namespace` is provided). And there should be another flag (`--batch`) for non interactive mode.

**Comment by tolusha** [comment]
The priority of choosing the namespace is the following:
1. use the namespace from the `--chenamespace` flag
2. use the namespace defined in the current context
3. use the `default` namespace name

**Comment by tolusha** [comment]
@l0rd 
I have some concerns. Changing the default behavior will cause issues.
I believe many bash scripts rely on the fact that `che` is the default namespace.
Is it better just to mention in the doc that it is necessary to update the current context [1] to have access to Eclipse Che namespace by default?

[1] `kubectl config set-context --current --namespace=che`

**Comment by l0rd** [comment]
@tolusha yeah I was thinking that this issue won't be relevant as soon as #17187 will be implemented so...closing the issue.
