### ISSUE TITLE
Che install failing with the latest chectl version on OpenShift 4.3.18 cluster

### ISSUE THREAD

**Issue by jagraj** [eclipse-che/che#16966]
### Describe the bug

With the latest Chectl version ```(chectl/7.13.0 linux-x64 node-v10.20.1)``` and OC version (4.3.19 client, OCP 4.3.18 server) Che install is failing with the following error. But even with this failure, I do see all pods up and running. But install reporting as failure with this error message.

```
  ✖ Retrieving Keycloak admin credentials
    → Cannot read property 'spec' of undefined
 ›   Error: TypeError: Cannot read property 'spec' of undefined
 ›   Installation failed, check logs in '/tmp/chectl-logs/1589819387710'

```

### Che version

 - [* ] latest
```chectl/7.13.0 linux-x64 node-v10.20.1```
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Install Che 7.9.2 version  on OCP 4.3.18 version using OC client 4.3.19.
You will get this error from console.

```
  ✖ Retrieving Keycloak admin credentials
    → Cannot read property 'spec' of undefined
 ›   Error: TypeError: Cannot read property 'spec' of undefined
 ›   Installation failed, check logs in '/tmp/chectl-logs/1589819387710'

```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [* ] Openshift (include output of `oc version`)

```
Client Version: 4.3.19
Server Version: 4.3.18
Kubernetes Version: v1.16.2

```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ *] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
```chectl/7.13.0 linux-x64 node-v10.20.1```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [* ] Linux
```
Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs

Install Logs:
[che-install.zip](https://github.com/eclipse/che/files/4646124/che-install.zip)

After Che Install from `chectl server:logs` command
[che.zip](https://github.com/eclipse/che/files/4646085/che.zip)

**Comment by tolusha** [comment]
@jagraj 
Thank you for reporting.
Pls provide a full command that was used to deploy Eclipse Che (including the output)
Just to clarify, if you use chectl 7.13.0 it means you were trying to deploy Eclipse Che 7.13.0 version.

**Comment by jagraj** [comment]
@tolusha 
Thanks for looking into this. We are overriding Che version that we want to install. We are installing 7.9.2 version.

Here are instructions we are following to bring up Codewind workspace. 
https://www.eclipse.org/codewind/che-installinfo.html#installing-eclipse-che-for-codewind

```
chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=setup/install_che/che-operator/codewind-checluster.yaml --che-operator-image=quay.io/eclipse/che-operator:7.9.2
```

**Comment by tolusha** [comment]
@jagraj 
I got the problem and provide a fix soon.

**Comment by tolusha** [comment]
The problem came from the fact, that CR name is `codewind-che` but not the default one `eclipse-che`

Update chectl to the latest version:
`chectl update next`
