### ISSUE TITLE
postgres-storage storage class missing when starting Che on Minikube

### ISSUE THREAD

**Issue by gtuz** [eclipse-che/che#16960]
## Summary
While following the official guide to start eclipse che on minikube by using chectl [https://www.eclipse.org/che/docs/che-7/running-che-locally/#installing-che-on-minikube-using-chectl_running-che-locally](url) I had issues with the postgres pod not starting up. I the logs the postgres pod was crushing because it `has unbound immediate PersistentVolumeClaims`.

After investigation I found that the storage class **postgres-storage** was missing in minikube. After adding it myself with the following configuration:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
```
then I have postgres and keycloak pods started correctly and everything works. I have 2 questions:

- Is it normal that I had to add the storage class myself? If so maybe it should be better documented
- Since I have started the che server without `--multiuser` flag I would expect to not have keycloak and postgres pods started, since according to the [documentation](https://www.eclipse.org/che/docs/che-7/che-workspace-controller/) (and also logically) both are needed only in multiuser configuration - am I missing something here?

Although it is supposed to be a single-user installation I am able to log into keycloak and create multiple users, and for each of them I am able to log into Che and create workspaces.

## Relevant information

- minikube version: 1.9.2
- kubectl version: 1.16.0
- chectl version: 7.12.2
- OS: Ubuntu 18.04
- command used: `chectl server:start --platform=minikube --installer=operator`

**Comment by tolusha** [comment]
Closed as duplicate 
https://github.com/eclipse/che/issues/16936
