### ISSUE TITLE
Create workflow for daily reports in slack

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16963]
### Is your enhancement related to a problem? Please describe.
Create a workflow in a slack channel `forum-hosted-che` channel to have a template of a periodic tests report in place. 

### Describe the solution you'd like
The template should look like:
```
@osioche
_Periodic tests status summary_

*production us-east-2*  :green_jenkins_circle: /6 failures

*production us-east-2a* :green_jenkins_circle: /6 failures

*production us-east-1a* :green_jenkins_circle: /6 failures

*production us-east-1b* :green_jenkins_circle: /6 failures

*prod-preview us-east-2a* :green_jenkins_circle: /6 failures
```

### Describe alternatives you've considered
Maybe it would be worth to create two templates - one for common days and one for Mondays, where `/6` would be replaced by `/18`.

### Additional context
We are trying to make daily reporting as much user-friendly as possible.

**Comment by Katka92** [comment]
The slack seems to have a strict format of `question` and `answer`, which doesn't allow us to create a report as we are used to. If we would like to use a slack workflow, we would need to change the report structure to something like:
```
Periodic test report
production us-east-2
<custom text containing Jenkins icon, failures rate and issues report>
production us-east-2a
<custom text containing Jenkins icon, failures rate and issues report>
...
```
To be honest, I don't see much value in this type of workflow. Maybe we should come up with something else.

**Comment by tsmaeder** [comment]
@Katka92 you've already set all the proper labels on this issue, but not "priority". I have no idea how important this issue is in the context of your work.

**Comment by Katka92** [comment]
There is no easy way how to implement that. The reporting as is now will be gone by the end of the year. Closing.
