### ISSUE TITLE
oAuth settings in che.properties not getting picked up

### ISSUE THREAD

**Issue by rwallinterset** [eclipse-che/che#1696]
Trying to import existing project through the Dashboard wizard.  Told that the oAuth properties need to be set in che.properties.  After I add the settings as indicated here, https://eclipse-che.readme.io/docs/git I get the same error again.  Even if I restart the CHE, docker instance I still get the same dialog.

**Reproduction Steps:**
1. From the dashboard click new project.
2. Click Select Source->Import from existing location->Github
3. Dialog appears indicating that oAuth settings need to be added/updated in che.properties.
4. Connect to the MobyLinuxVM and change the che.properties in ~/che/conf/che.properties
5. Restart the che docker instance.
6. Retry steps 1 & 2.  Get the same result.

**Expected behavior:**

When I click Github option I expect to see a list of repositories in my GitHub account. 

**Observed behavior:**

[Describe observed behavior here]

**Che version:**    How do I tell the version?  Running latest docker container but not sure how I extract the version.  
**OS and version:** Windows 10 - Docker using HyperV 
**Docker version:**  1.12.0-rc3  
**Che install:**   Docker Container   

**Additional information:**
If I try this with codenvy I get a wizard setting up oAuth with github and everything works as expected afterwards.
- Problem started happening recently, didn't happen in an older version of Che: Unknown
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ghost** [comment]
@rwallinterset if you run Che as a docker container, you need to mount your custom properties file as per https://eclipse-che.readme.io/docs/usage-docker#section-configure-che

If you made changes in the runtime, then you need to restart a container rather then re-run the image. How did you restart Che?

**Comment by wallrick** [comment]
@eivantsov Thanks for responding.  I reread the instructions that you referenced and now I have it working.  Not exactly sure why but one guess is that I originally tried adding the oauth after I had already created the CHE container.  Maybe you have to do this before you create the container for the first time?

**Comment by ghost** [comment]
@wallrick probably when you have restarted Che, your changes vanished as you have started a new container.

Good to know it works now. I am closing the issue then.
