### ISSUE TITLE
Missing link to API documentation

### ISSUE THREAD

**Issue by nfode** [eclipse-che/che#16974]
## Summary

Missin link to API documentation

## Relevant information

I was searching for API-Documentation on how to add Projects to an existing Workspace. I found a link to a Rest-Api documentation on the Extend-Page (https://www.eclipse.org/che/extend/) but when I click on the link (https://www.eclipse.org/che/docs/rest-api.html) it says 404. I did some research in the docs repo and there is also no API documentation. 

So my question is if this is a bug and if someone can point me to some documentation/other sources where I can get information about the Rest-Api.

Thanks in advance.

**Comment by azatsarynnyy** [comment]
Hello @nfode 
a project can be added to Che Devfile https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#writing-a-devfile-for-your-project_making-a-workspace-portable-using-a-devfile
AFAIK there's no specific API.

**Comment by tsmaeder** [comment]
@azatsarynnyy while the question is answered, there is still a broken link on the Eclipse page (https://www.eclipse.org/che/extend/) we need to fix.

**Comment by azatsarynnyy** [comment]
You're right @tsmaeder :+1: I overlooked it.
Not sure who is it for, maybe @rkratky or @themr0c

**Comment by themr0c** [comment]
https://www.eclipse.org/che/extend/: The "Che REST APIs" link is now pointoing to https://che.openshift.io/swagger/
