### ISSUE TITLE
Openshift failing to pull image

### ISSUE THREAD

**Issue by goldcakes** [eclipse-che/che#16971]
### Describe the bug
When I try starting Openshift.io it fails at pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.1.2"
### Che version
Che version is 7.12.2 latest
### Steps to reproduce
-Go to the openshift.io url
-Log in
-Go to workspaces
-Open a workspace
-Error is during start up
### Expected behavior
Expected it to open the workspace in the php-simple start page
### Screenshots
![errorImagePull](https://user-images.githubusercontent.com/65596846/82313166-57686a80-9a0b-11ea-807c-81459fba4e56.PNG)

### Installation method
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows

### Eclipse Che Logs
pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.1.2"
Error: ErrImagePull
Error: Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'Failed', 'Error: ErrImagePull', 'workspacemlywc2fliee3ktsc.che-plugin-broker'"

### Additional context
A friend of mine is also experiencing the same issue at their house.
I don't really know much about this, I'm using it to learn html at uni.

**Comment by tolusha** [comment]
@goldcakes 
We are experiencing a problem with quay.io
https://status.quay.io/incidents/kw2627bsdwd9

**Comment by goldcakes** [comment]
Ok, thanks for the reply. Is there anyway to download my files without it or something. I need to submit my assignment before midnight.

**Comment by danidoedel** [comment]
@tolusha is there any reason why it has to be pulled for every workspace start? Can't it be cached? Almost the whole day Che was unusable because of the quay.io issues...

**Comment by AndrienkoAleksandr** [comment]
I see we have an issue with pull **devfile registry image**:

```
Error: error pulling image "quay.io/eclipse/che-devfile-registry:7.12.2": unable to pull quay.io/eclipse/che-devfile-registry:7.12.2: unable to pull image: Error initializing source docker://quay.io/eclipse/che-devfile-registry:7.12.2: Requesting bear token: invalid status code from registry 500 (Internal Server Error)
```
With nightly image the same.

**Comment by goldcakes** [comment]
Fortunately, they managed to get it running in read-only mode. I would recommend you download your files now, as they are still working on the issue. This [page](https://status.quay.io/incidents/kw2627bsdwd9) shows regular updates about the issue. 
I'll keep this open for now(unless asked to close) and when the issue is solved I will comment so.

**Comment by goldcakes** [comment]
Ok, issue is currently resolved and stable.

**Comment by tolusha** [comment]
@danidoedel 
It is possible not to pull images by modify eclipse-che CR:
```
spec:
  server:
    customCheProperties:
      CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY: IfNotPresent
      CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: IfNotPresent
      CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY: IfNotPresent
```
corresponding issue https://github.com/eclipse/che/issues/14698
