### ISSUE TITLE
Hide organization UI on dashboard

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16973]
### Is your task related to a problem? Please describe.
There was discovered functional regression https://github.com/eclipse/che/issues/16916 that it's not possible to create workspace under the organization anymore.

So, the question was raised if we should restore that functionality or should we totally hide/remove organization UI since organizations were designed to docker infrastructure and the main purpose was limiting users' RAM usage, but on K8s/OpenShift infrastructure Che RAM Resource API model does not work correctly anymore. The tip of the iceberg is #11424, but then Che Resource API should be probably redesigned to be consistent with OpenShift Resource Quotas model.

In addition, some time ago we disabled the functionality of sharing workspaces to avoid the leak of user's personal data, like ssh keys. AFAIS with the organization this functionality is available without proper message for users that it's not really safe thing to do.

One more inconsistency - once user is added to the organization - they are not able to create a workspace in their personal space anymore.

Despite the fact that something works - like limit organization workspaces, running workspaces numbers, an ability for admin to see all members workspaces (possibly removing and stopping them but not sure). It's better to disable this feature which is partially working for a long time with a lot of inconsistency.

**Comment by mingfang** [comment]
Is this temporary? what is the plan for organizations?

**Comment by sleshchenko** [comment]
@mingfang If you depend on the existing half-working organization, you still are able to enable them in product.json of dashboard.
As about reviewing organizations and make them fully working again - there is an epic but not a particular priority or plans https://github.com/eclipse/che/issues/15304

**Comment by akurinnoy** [comment]
hello @mingfang,
Look at **Note** in [che-dashboard#configurability](https://github.com/eclipse/che-dashboard#configurability) to know how to enable organizations.
