### ISSUE TITLE
Browser warning Box should be closable

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#16978]
### Is your enhancement related to a problem? Please describe.
When using a "non-supported" browser, we now get a box warning that "You're using a web browser we don't support. Please consider using Chrome or Firefox instead.". 

### Describe the solution you'd like
I would like that warning to be closable and not to reappear in the current session.

**Comment by ibuziuk** [comment]
why should we have a banner closable? if you, for example, have outdated / unsupported version of Chrome you will not be able to just close the notification. e.g. Safari is simply not supported at this point of time and IMO we should just make it super clear and always show the banner

**Comment by tsmaeder** [comment]
Because I once Che has (wrongly) told me I'm using an unsupported browser, I'm well aware of it and I'd like to have my screen real estate back. It's like the kids in the back seat going "are we there yet? are we there yet?"

**Comment by ibuziuk** [comment]
> Because I once Che has (wrongly) told me I'm using an unsupported browser

So, that is the real issue - wrong detection of the supported / unsupported browser. 
From UX perspective if smth is not supported IMO we should not allow simply closing the notification - the message is that one must consider a different browser to work with Eclipse Che

**Comment by tsmaeder** [comment]
No, one might be happy to continue to work with the unsupported browser. And anyway...once you've told me, the message is just an annoyance.
