### ISSUE TITLE
 Build Che-dashboard on linux/s390x architecture

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16987]
### Is your task related to a problem? Please describe.
 Build Che-dashboard on linux/s390x architecture is failing right now on `install` dependency phase
```
#12 199.6 PhantomJS not found on PATH
#12 199.6 Unexpected platform or architecture: linux/s390x
```

Context https://github.com/eclipse/che/issues/16983

**Comment by skabashnyuk** [comment]
CC @shahidhs-ibm

**Comment by sleshchenko** [comment]
It seems to be already fixed by https://github.com/eclipse/che-dashboard/pull/51
if no - please reopen this issue
