### ISSUE TITLE
Keycloak scheduling step failing with timeout.

### ISSUE THREAD

**Issue by sushant08** [eclipse-che/che#16984]
## Summary
I am trying to launch eclipse che on aws eks. After creating cert-manager i am trying to deploy che using commnd: chectl server:start --platform=k8s --installer=operator --domain=aws.test-ide.cloud --multiuser --k8spodreadytimeout=1000000

But it failing with timeout at keycloak scheduling. Logs are below:
[events.txt](https://github.com/eclipse/che/files/4661585/events.txt)
[che-operator.log](https://github.com/eclipse/che/files/4661588/che-operator.log)
[postgres.log](https://github.com/eclipse/che/files/4661589/postgres.log)

## Relevant information
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify remote kubernetes status...done.
    ✔ Check Kubernetes version: Found v1.13.12-eks-eb1860.
    ✔ Verify domain is set...set to aws.test-ide.cloud.
    ↓ Check if cluster accessible [skipped]
Eclipse Che logs will be available in '/var/folders/b_/knc25xx9159_h693ljnwb_mdd__nh8/T/chectl-logs/1590045699303'
  ✔ Start following logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
  ❯ 🏃‍  Running the Eclipse Che operator
    ✔ Copying operator resources...done.
  ✔ 🏃‍  Running the Eclipse Che operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Checking for pre-created TLS secret... "che-tls" secret found
    ✔ Checking certificate
    ✔ Create ServiceAccount che-operator in namespace che...done.
    ✔ Create Role che-operator in namespace che...done.
    ✔ Create ClusterRole che-operator...done.
    ✔ Create RoleBinding che-operator in namespace che...done.
    ✔ Create ClusterRoleBinding che-operator...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...done.
    ✔ Create Eclipse Che cluster eclipse-che in namespace che...done.
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Keycloak pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
        downloading images
        starting
      Devfile registry pod bootstrap
      Plugin registry pod bootstrap
      Eclipse Che pod bootstrap
      Retrieving Eclipse Che server URL
      Eclipse Che status check
 ›   Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined
 ›   Installation failed, check logs in '/var/folders/b_/knc25xx9159_h693ljnwb_mdd__nh8/T/chectl-logs/1590045699303'

**Comment by tolusha** [comment]
@sushant08 
pls attach installation logs
```
› Installation failed, check logs in '/var/folders/b_/knc25xx9159_h693ljnwb_mdd__nh8/T/chectl-logs/1590045699303'
```

**Comment by sushant08** [comment]
> @sushant08
> pls attach installation logs
> 
> ```
> › Installation failed, check logs in '/var/folders/b_/knc25xx9159_h693ljnwb_mdd__nh8/T/chectl-logs/1590045699303'
> ```

Attached logs

**Comment by tolusha** [comment]
Operator logs contains:

```
time="2020-05-21T07:22:44Z" level=info msg="Waiting on ingress 'che-host' to be ready"
time="2020-05-21T07:22:47Z" level=error msg="Internal error occurred: failed calling webhook \"validate.nginx.ingress.kubernetes.io\": Post https://ingress-nginx-controller-admission.ingress-nginx.svc:443/extensions/v1beta1/ingresses?timeout=30s: no endpoints available for service \"ingress-nginx-controller-admission\""

```
`nginx` misconfigured  ?

@amisevsk 
Have you seen such an error before ?

@sushant08 
I would recommend troubleshooting
https://kubernetes.github.io/ingress-nginx/troubleshooting/

**Comment by sushant08** [comment]
The issue was because of ingress-controller. Thanks for assistance @tolusha
