### ISSUE TITLE
Organization RAM Limit and Workspace Cap do not appear to function

### ISSUE THREAD

**Issue by donenocode** [eclipse-che/che#16989]
### Describe the bug
After setting 'Workspace Cap', 'Running Workspace Cap' and 'Workspace RAM Cap' on an organization the 'Workspace RAM Cap' does not appear to limit RAM allocation.
With no running workspaces the TOTAL RAM and AVAILABLE RAM columns are the same value (for instance 4GB).
When starting 1 workspace (PHP Simple) the AVAILABLE RAM column show a drop of the correct amount (it drops by around ~2.5G) this is as expected.
When starting a second workspace (PHP Simple) the AVAILABLE RAM column shows 'not limited' and allows the workspace to start. The workspace should NOT be able to start.

I am also able to create more workspaces than the 'Workspace Cap' should allow.

For reference the 'Running Workspace Cap' functions correctly and does prevent starting more workspaces than allocated.

### Che version
 - [x] other: 7.13.0

### Steps to reproduce
1. Create an organization
2. Set a limit on 'Workspace Cap' and 'Workspace RAM Cap'
3. Create more workspaces than the cap should allow
4. Start workspaces with a higher RAM limit than the cap should allow

### Expected behavior
Workspace Cap: Once the cap is reached no more workspaces should be created
Workspace RAM Cap: Once the cap is reached no more workspaces should be able to start

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", Platform:"linux/amd64"}
```
### Installation method
   - [x] chectl
`chectl server:start --platform=k8s -m -s --chenamespace=che-test --installer=helm --domain=<DOMAIN HERE>`

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: Ubuntu 18.04 vSphere VM's

### Additional context
I have this exact setup working on a production Che 6.19 installation and it works as expected.

Thanks.

**Comment by skabashnyuk** [comment]
@donenocode thank you for this report. There is a tendency to remove organizations please take a look https://github.com/eclipse/che/issues/15304 and  https://github.com/eclipse/che-workspace-loader/pull/24

**Comment by donenocode** [comment]
Thank you for this, it does appear that this function may be removed then..
The issue I have is using this in a teaching environment, I used the organization permissions and CHE_LIMTS_USER_WORKSPACES to prevent users from creating workspaces outside of organizations and only allowing them to start the pre-defined workspaces in the organization.

However CHE_LIMTS_USER_WORKSPACES does not function either (I have raised a separate issue regarding this)

**Comment by l0rd** [comment]
We do NOT want to remove organizations, we want to fix them. But until then we are going to disable organization to avoid confusions.

To limit the amount of resources users can use per workspace you can:

1. pre-create a Kubernetes namespace named `<username>-che` for every user
2. configure the namespaces create at step 1 with [memory](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/) and [cpu](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/) constraints of your choice (e.g. limits of 8 GB and 4 cores)
3. deploy Che with `che.infra.kubernetes.namespace.default=<username>-che` 

Then users won't be able to user more then the resources configured for their namespaces.

**Comment by donenocode** [comment]
Thanks for the update, very useful.
I will configure workspaces as above.

Once again thanks for a fantastic product and the hard work you all do.
