### ISSUE TITLE
[Doc] Update to Che4z extension page in Che 7 docs

### ISSUE THREAD

**Issue by zeibura** [eclipse-che/che#16990]
The Che4z page on Che 7 docs - https://www.eclipse.org/che/docs/che-7/eclipse-che4z/ - needs an update to reflect new features in COBOL Language Support and Zowe Explorer. 
The two links in the Zowe Explorer links section are also incorrect and need to be fixed to point to the Zowe Blog rather than the VS Code marketplace.

**Comment by themr0c** [comment]
The links look fine now. Closing.
