### ISSUE TITLE
Development Workflow is out of date (dashboard and workspace loader are now in separate repos)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16991]
### Is your task related to a problem? Please describe.

Since the Che dashboard and ws-loader are now separate images and separate repos, the Che 7 workflow doc needs updating.

https://github.com/eclipse/che/wiki/Development-Workflow,-Che-7

### Describe the solution you'd like

Updated doc! 

Since it's 7.14 (a hardening sprint) this is a perfect time to clean up doc that is now outdated with the updated repo/build structure.

**Comment by skabashnyuk** [comment]
Development-Workflow has been updated https://github.com/eclipse/che/wiki/Development-Workflow,-Che-7/_compare/76e3726a1914e66f79ccabd35bbe4e8df782323a...4e857bca0f4c8800ff4ce0005aa9381bc4b5e80c
