### ISSUE TITLE
Remove PR check from ci.centos for che-theia

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17008]
### Is your enhancement related to a problem? Please describe.
PR check on che-theia is not parallel and takes a very long time.
It should be removed now that we have counter part on github actions

### Describe the solution you'd like
- [x] Remove the check being mandatory before merge
- [x] Add GH checks as being mandatory
- [ ] Remove PR check from ci.centos

### Describe alternatives you've considered
Remove all mandatory checks (no-one being mandatory)

**Comment by benoitf** [comment]
asked removal here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563549

**Comment by azatsarynnyy** [comment]
Cool!
![image](https://user-images.githubusercontent.com/1636395/82988764-55516d80-a002-11ea-9960-dd50fa5d4e05.png)
Thx!

**Comment by ericwill** [comment]
Looks like this can be closed now?
