### ISSUE TITLE
Che shows the incorrect view aftering rebuild /dashboard

### ISSUE THREAD

**Issue by wn092943** [eclipse-che/che#1700]
**Reproduction Steps:**
1. I add some simple contents to the file `dashboard/../src/app/navbar/navbar.html`
   ![53](https://cloud.githubusercontent.com/assets/19187922/16722338/6eb51164-4778-11e6-9792-cb6540f61007.PNG)
2. Rebuild `/dashboard`, then rebuild `/assemble`
3. Start che, the view is incorrect
   ![54](https://cloud.githubusercontent.com/assets/19187922/16722378/b7f85bec-4778-11e6-9306-f94c639aced5.PNG)
4. I delete contents that I added in step 1.
5. Rebuild `/dashboard`, then rebuild `/assemble`
6. Start che, the view is still incorrect
   ![52](https://cloud.githubusercontent.com/assets/19187922/16722398/e7cdaf5c-4778-11e6-8e84-c49376e90c6b.PNG)

**Che version:**   4.4.2
**OS and version:** win7

**Comment by TylerJewell** [comment]
@ashumilova

**Comment by wn092943** [comment]
Additional information:
I execute the command `gulp serve`, then I get the same incorrect view when visiting `localhost:3000`, and this is the log:
[log.txt](https://github.com/eclipse/che/files/356727/log.txt)

**Comment by ashumilova** [comment]
@wn092943 can you show, please, the browser console logs?

**Comment by wn092943** [comment]
@ashumilova -- This is the browser console logs:
![60](https://cloud.githubusercontent.com/assets/19187922/16754057/9c329248-4821-11e6-8214-afc73147e232.PNG)
[localhost-1468292785516.txt](https://github.com/eclipse/che/files/358513/localhost-1468292785516.txt)

**Comment by ashumilova** [comment]
@wn092943 seems that the cause of the problem is in the styles gulp task execution:
In your attached logs $.sourcemaps.write() - fails with "Path must be a string. Received undefined"
Can be cause by node v6
What version of node and gulp do you have:
`node --version`
`gulp --version`
Can you, please, try same operations with 4.x Node version?

**Comment by wn092943** [comment]
@ashumilova -- Thanks. Your advice is very useful. I solve this problem through changing the 6.3 Node to the 4.4 Node.
