### ISSUE TITLE
Golang stop-outyet command throws out status code 143

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#17005]
### Describe the bug
When running the stop command for golang devfile, the running application throws exit code `143`

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
* Start Go example devfile
* Execute `run outyet` task
* Wait for Go application to be running
* Execute `stop outyet` task
* Exit code != 0 notification will be displayed

### Expected behavior
* Go application is stopped and non-zero exit code is suppressed

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift 
```
Client Version: 4.3.5
Server Version: 4.4.4
Kubernetes Version: v1.17.1
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot_20200525_094851](https://user-images.githubusercontent.com/16451875/82791383-f4912c00-9e6d-11ea-925e-6da196cf0161.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che `chectl server:start -a operator -p openshift --self-signed-cert -n <namespace>`
     * provide an output of `chectl version` command `chectl/7.13.0 linux-x64 node-v10.20.1`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other OCP 4.4 on crw-qe.com
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by ibuziuk** [comment]
@ericwill could you please take a look ?

**Comment by vitaliy-guliy** [comment]
Exit codes above 127 typically mean the process was stopped because of a Signal.

Go process is getting SIGTERM (15) signal, so exit code is 128+15.

If it's critical for you and you want to see exitcode 0, just add `exit 0` at the end of the command which starts the `outyet`.

```
commands:
-
  name: run outyet
  actions:
  - type: exec
    component: go-cli
    command: go get -d && go run main.go ; exit 0
    workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
```
