### ISSUE TITLE
Extend plugin meta model to include health check endpoint

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17002]
### Is your enhancement related to a problem? Please describe.
One of the steps in workspace startup is waiting for any servers to be ready. It would be convenient if plugin specs could define an endpoint which can be pinged to check for server readiness/health.

### Describe the solution you'd like
Add health check endpoints to plugin meta model. Potentially a liveness and readiness definition, parallel to what exists in Kubernetes.

### Describe alternatives you've considered
Rely on communicating with a port defined for the plugin.

### Additional context
The Che workspace operator needs to be able to check for server readiness before marking a workspace as 'Running', to avoid 503 errors. See PR https://github.com/che-incubator/che-workspace-operator/pull/78 for details.

**Comment by ibuziuk** [comment]
I believe we have similar issues on Hosted Che when for example theia route is not yet available

**Comment by ibuziuk** [comment]
@ericwill I put P1, but feel free to update the priority based on the team priorities

**Comment by amisevsk** [comment]
Not sure which area this one actually falls under -- there's a plugin side change somewhere, but the plugin spec changes would mostly be handled by infra/plugin broker. @ibuziuk @ericwill WDYT about:
- Step 1: add to plugin meta.yaml, etc. spec, and implement handling in wsmaster
- Step 2: try to add support to actual plugins (machine-exec, theia, etc.)

**Comment by sleshchenko** [comment]
Is it something that should be addressed in Devfile 2.x format? @l0rd @davidfestal WDYT?

**Comment by amisevsk** [comment]
I think this issue should just be closed; likely this functionality, if useful, would be implemented in devfile 2.0
