### ISSUE TITLE
Command not working in Apache Camel K

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17015]
### Describe the bug
There is just one command in Apache Camel K devfile. It is displayed only in `Terminal -> Run task...` view, it is not displayed in the right panel in section My Workspace. 
When the user runs the command, it fails.

### Che version

 - [x] latest 7.13.1
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
 - go to `Get Started` page
 - click on `Apache Camel K` 
 - wait for workspace to start
 - click `Terminal -> Run Task...`
 - select the only command here
 - select `Continue without scanning the task output` option

### Expected behavior
If the command should work correctly or be removed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) 
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-05-26 10-43-41](https://user-images.githubusercontent.com/29278800/82882817-e3195400-9f41-11ea-8f56-f0d09c4bd2ce.png)
![Screenshot from 2020-05-26 10-41-41](https://user-images.githubusercontent.com/29278800/82882819-e44a8100-9f41-11ea-8407-5bffa1e831d7.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
Log from theia-ide container:
```
2020-05-26 09:18:03.891 task INFO Created new task, id: 1, process id: 5, OS PID: 126, context: file:///projects 
2020-05-26 09:18:04.300 terminal ERROR Couldn't attach - can't find terminal with id: 5  
2020-05-26 09:18:04.315 root INFO Failed to set task status: the corresponding terminal is not found 
2020-05-26 09:18:04.447 root ERROR Couldn't resize terminal -1, because it doesn't exist. 
2020-05-26 09:18:04.448 terminal ERROR Error attaching to terminal id 5, the terminal is most likely gone. Starting up a new terminal instead. 
```

**Comment by ericwill** [comment]
@apupier can you take a look?

**Comment by apupier** [comment]
do you have the Camel K integration file opened in editor when launching the command?

**Comment by Katka92** [comment]
@apupier Could you please explain where can I find `Camel K integration file`?

**Comment by apupier** [comment]
When using the Apache Camel K defautl stack, there are several Camel K integration files. For instance, the file named _Sample.java_ inside _examples_ folder

**Comment by Katka92** [comment]
I've tried to open the file but the command is still failing on exit code 127.
![Screenshot from 2020-08-27 10-57-47](https://user-images.githubusercontent.com/29278800/91419847-2bebec00-e854-11ea-895f-b29c81b48017.png)

**Comment by apupier** [comment]
that's not very nice not having more information :-(

have you configured an access to a Camel K instance?
Is it working when you open a terminal in vscode-camelkxxx container and call the `kamel run <thepathtoSample.java>`?

**Comment by Katka92** [comment]
> have you configured an access to a Camel K instance?

@apupier So there are some extra steps I need to do to configure Camel K instance? Could you please provide me those steps? 

> Is it working when you open a terminal in vscode-camelkxxx container and call the kamel run <thepathtoSample.java>?

![Screenshot from 2020-09-14 08-20-22](https://user-images.githubusercontent.com/29278800/93050431-2c152580-f663-11ea-8c0b-ca14f53c619c.png)

**Comment by apupier** [comment]
> So there are some extra steps I need to do to configure Camel K instance?

yes, due to Che limitations https://github.com/eclipse/che/issues/15391

>  Could you please provide me those steps?

it depends on your version and how you are used to configure the Kubernetes connection in your Eclipse Che workspace.

Some possibilities described here:
* https://issues.redhat.com/browse/CRW-609?focusedCommentId=13990929&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13990929
* https://developers.redhat.com/blog/2020/01/24/apache-camel-k-development-inside-eclipse-che-iteration-1/

**Comment by apupier** [comment]
> > Is it working when you open a terminal in vscode-camelkxxx container and call the kamel run <thepathtoSample.java>?
> 
> ![Screenshot from 2020-09-14 08-20-22](https://user-images.githubusercontent.com/29278800/93050431-2c152580-f663-11ea-8c0b-ca14f53c619c.png)

so this error means that the Camel K instance is not available. This is up to the user to do it due to Che limitation #15391

**Comment by Katka92** [comment]
Thank you for your answer, I'll try that. :+1:
