### ISSUE TITLE
Deprecate non-TLS deployments

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17012]
### Is your enhancement related to a problem? Please describe.

Latest Theia webview requires TLS. Hence Che workspaces exposing unsecured http endpoint to Theia won't work properly and the UX will be awful.

### Describe the solution you'd like

We should progressively remove the support for deployments of Che that do not use TLS:

1. Remove the option to deploy Che with no TLS but do not break existing installations. Http  endpoints are still possible but deprecated. Remove no TLS option from:
    - chectl parameters
    - helm values
    - operator CSV
    - documentation
2. Automatically switch to TLS-enabled when upgrading to newer version of Che and do not support http endpoints anymore #17090
3. Remove any reference to `tlsSupport` and `.Values.global.tls.enabled` from CheCluster CRD and Helm Chart

⚠️ User defined endpoints in workspaces and user applications automatically exposed ports should still be possible without TLS.

**Comment by nickboldt** [comment]
Deprecation was announced on Che-dev list on Jul 2:

```
We are going to deprecate non-TLS deployments soon.

What does it mean?
1. There won't be ability to deploy Eclipse Che with TLS disabled anymore
2. All existing non-TLS deployments will continue working.
3. Deployments will be automatically switched to TLS-enabled when upgrading to a newer version.
```

Therefore this could be done in sprint 189 for Che 7.19.

**Comment by tolusha** [comment]
There is no way to deploy Eclipse Che with tls disabled since 7.43.0
