### ISSUE TITLE
Rework che-workspace-operator YAMLs so that we don't have seperate k8s/openshift deployment yamls

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#17010]
### Is your task related to a problem? Please describe.

Currently in the che-workspace-operator deployment yamls are separated into k8s/openshift specific folders because cert generation for openshift is done automatically in the operator but k8s cert generation is not (you have to run cert generation manually then patch the deployment). This makes generating the csv's a bit painful as `operator-sdk generate csv` will pick up the k8s deployment, os deployment, and the registry deployment.

### Describe the solution you'd like

Find a way to make it so that we have one deployment file for k8s and openshift

### Describe alternatives you've considered

Leave it as is and just do workarounds inside of our Makefile

**Comment by amisevsk** [comment]
We could potentially use kustomize, or use a sparse checkout in web-terminal-operator

**Comment by sleshchenko** [comment]
I think it should be fixed by https://github.com/eclipse/che/issues/17855
