### ISSUE TITLE
Clicking on Add Workspace does nothing

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17018]
### Describe the bug

Selecting Workspaces on the main User Dashboard menu and then clicking on "Add Workspace" does not open a page to add a new workspace.

### Che version

7.13.1

### Environment

che.openshift.io

![May-26-2020 12-52-02](https://user-images.githubusercontent.com/606959/82892462-c7b54580-9f4f-11ea-8e33-370a3802dffc.gif)

**Comment by ibuziuk** [comment]
@olexii4 @sleshchenko could you please take a look?

**Comment by ibuziuk** [comment]
@Katka92 good candidate for `pre-release` test suite btw

**Comment by Katka92** [comment]
@ibuziuk I verified that in 7.13.1 Che on OCP 4.4 and works correctly. I verified on che.openshift.io and works OK for me - I'm redirected to `Get Started` page `Custom Workspace` tab the same way as in upstream Che.

**Comment by ibuziuk** [comment]
seems to be chrome specific (works fine against Firefox)

**Comment by Katka92** [comment]
I'm using Chrome Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by ibuziuk** [comment]
I can repro against Chrome  `80.0.3987.149-1`

**Comment by l0rd** [comment]
I am using chrome as well. Opening it in an incognito window fixes the problem. Hard reloading fixed the problem finally.

**Comment by sleshchenko** [comment]
> I am using chrome as well. Opening it in an incognito window fixes the problem. Hard reloading fixed the problem finally.

It seems like cache issues... I often face cache issues on dashboard and now it seems to be a good time to investigate it more!
