### ISSUE TITLE
Che Plugin Registry VSX Daily Check

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17014]
### Is your enhancement related to a problem? Please describe.

We do not have any report of how many VS Code Extensions are supported by Che, their list and how fresh they are (che registry version vs msft marketplace version). These information are useful and would encourage contribution.

### Describe the solution you'd like

Generate a VSX daily report (on gh pages for example) with the list of extensions that are supported (included in our registry) and for each one provide:

ITERATION N.1
- id
- github repo
- version in che plugin registry
- version in vscode marketplace

ITERATION N.2
- version in gh master branch package.json
- sidecar container image

ITERATION N.3
- % of API call supported in Che Theia
- smoke test (enable / disable) result (pass/fail)

Included in epic #15819

**Comment by gorkem** [comment]
This is not so much about the report but automation of the intake of the extensions. Basically we need to automate the intake to the level that we keep a list of github repositories and branches. An automated job goes through this list at least once a day. Builds the vsx, runs automated checks in Che context and if all checks pass, issues an update to plugin registry.

**Comment by l0rd** [comment]
We already have an [epic](https://github.com/eclipse/che/issues/15819) about plugin update automation and we [have a script too](https://github.com/eclipse/che-plugin-registry/blob/master/tools/plugin_checker/plugin_checker.py) that 1) checks if there is a new version of a vsx 2) files a gh issue if the plugin is not updated. 

Hence I have updated the original epic with the following subtasks to improve current script and make it easier to contribute a new vs code extension to our registry:

1. Run the script daily and provide a report --> this issue
1. Automatically submit PR (instead of opening issue)
1. PR check to validate new/updated vs code extensions #17027
1. In plugin-checker fall back to repo/branch `package.json` when there are no GH releases
1. Automatically generate `meta.yaml` given a vsx repo+branch+dockerfile #17029
1. Build and publish a vsx when there is no corresponding GH release

**Comment by ericwill** [comment]
Apart from % API calls and smoke test coverage, the report iterations are done. [Plugin registry](https://eclipse.github.io/che-plugin-registry/) and [che-theia](https://eclipse.github.io/che-theia/) reports are generated nightly. We are working on testing API (#15797) to start providing PR checks and smoke tests.

**Comment by ericwill** [comment]
I'm going to close this. We can handle the API display in a separate issue.
