### ISSUE TITLE
Che fails to deploy on minikube

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#17013]
### Describe the bug
Che fails to deploy on minikube due to timeout errors.

### Che version
 - [x] latest: chectl/7.13.0 linux-x64 node-v10.20.1

### Steps to reproduce

1. Start minikube: `minikube start --memory=10240 --cpus=4 --disk-size=20g --driver=kvm2`
2. Try to deploy Che: `chectl server:start --platform=minikube`
3. See that Che has failed to deploy. The first time it fails with `ERR_TIMEOUT: Timeout set to pod wait timeout 300000`. If I try to deploy it again it fails with `ERR_TIMEOUT: Timeout set to pod wait timeout 300000. podExist: false, currentPhase: undefined`

### Expected behavior
Che should deploy.

### Runtime
   - [x] minikube 1.9.0 and kubectl 1.18.0

### Screenshots
![che_timeout_1](https://user-images.githubusercontent.com/6290632/82840468-ba8d4d80-9ea0-11ea-81ca-88f429b409ce.png)
![che_timeout_2](https://user-images.githubusercontent.com/6290632/82840470-bc571100-9ea0-11ea-9fe5-3f80dcf3c704.png)

### Installation method
   - [x] chectl
     * `chectl server:start --platform=minikube`
     * version 7.13.0 linux-x64 node-v10.20.1

### Environment
   - [x] my computer
       - [x] Linux (Fedora 31)

### Additional context
I tried deleting my minikube (`minikube delete && rm -rf ~/.minikube && rm -rf ~/.kube`) as well as deleting the che namespace before trying again, but no success.

**Comment by tolusha** [comment]
Closed as duplicate 
https://github.com/eclipse/che/issues/16936

See https://github.com/eclipse/che/issues/16936#issuecomment-629029833 for details
