### ISSUE TITLE
Update vscode-java to the latest version (0.61.0)

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#17025]
vscode-java in Che is currently out of date, as the newest version is 0.61.0 and we have 0.57.0.

I tried adding vscode-java 0.61.0 to Che and the extension fails to activate with the following message:

`Activating extension Language Support for Java(TM) by Red Hat failed: Cannot read property 'join' of null.`

**Comment by tsmaeder** [comment]
Newest version has become 0.62, since

**Comment by tsmaeder** [comment]
0.62 starts fine in theia master

**Comment by tsmaeder** [comment]
0.62 seems to start fine in a che workspace on che.openshift.io, as well

**Comment by tsmaeder** [comment]
Java debug 0.26 does not start because of missing vscode.env.UIKind API. Having a quick look how hard this would be.

**Comment by benoitf** [comment]
linking https://github.com/eclipse-theia/theia/issues/8007
