### ISSUE TITLE
Add plugin-registry PR check to validate new/updated vsx

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17027]
### Is your enhancement related to a problem? Please describe.

We do not have an automated check that validates a vs code extension in the plugin-registry

### Describe the solution you'd like

We should have a PR check (gh action) that does some basic checks on any new or updated meta.yaml:
- URLs in the meta.yaml are not broken: repository, icon, extensions
- Images in the containers section of the meta.yaml exist
- Extension can be started successfully in its sidecar container (or in nightly che-theia container)

Tests should be run ONLY if the PR includes the creation of a new `meta.yaml` file (for a new extension or for a new version of an existing extension).

### Additional context

The plugin registry has already [a PR check](https://github.com/eclipse/che-plugin-registry/blob/master/.ci/cico-happy-path-pr-test.sh) that currently verifies that the [happy path test workspace](https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/happy-path-workspace.yaml) starts and [e2e test flow](https://github.com/eclipse/che/tree/master/tests/e2e#the-happy-path-scenario-launching) doesn't get broken. This issue instead is about running a functional test (not e2e) for new or updated extensions.

Included in epic #15819

**Comment by ericwill** [comment]
This has been done now that we have generated `meta.yaml`
