### ISSUE TITLE
Annoying auto-linter rendering workspaces unusable

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#17023]
### Describe the bug
Affected devfiles:
* Java Spring Boot https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/java-web-spring
* Java with Spring Boot and MySQL https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/java-mysql
EDIT:
* NodeJS Angula Web Application https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/angular

Cursor is being spastically moved around during use, rendering the devfiles unusable (super irritating, rewrites what you're typing, messes with code)

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: 7.13.x

### Steps to reproduce
* Start any of the two workspaces
* Open any file and wait for the LS to initialize
* Try to write any code

### Expected behavior
* Linting doesn't happen automatically on it's own, especially not while typing

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift
```
Client Version: 4.3.9
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![simple_screen_recorder-2020-05-25_16 34 53](https://user-images.githubusercontent.com/16451875/82904048-2f748c00-9f62-11ea-92bc-619b26675918.gif)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output): `chectl server:start -a operator -p openshift --self-signed-cert -n <namespace>`
     * provide an output of `chectl version` command: `chectl/7.12.2 linux-x64 node-v10.20.1`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other Codeready workspaces OCP 4.4 at crw-qe.com
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by ScrewTSW** [comment]
Unless this is an intended feature, I was still able to reproduce this on both workspaces
@skabashnyuk @l0rd

**Comment by ScrewTSW** [comment]
Still true for 7.16.0

**Comment by ScrewTSW** [comment]
The issue is newly present on the NodeJS Angular Web Application stack as well ([link](https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/angular))

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che-theia/pull/912
