### ISSUE TITLE
Is adding a self-signed certificate to the wsmaster trustore useful?

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17039]
## Summary

The documentation section [Adding custom public SSL certificates to Che trust-store](https://www.eclipse.org/che/docs/che-7/mounting-custom-tls-certificates-to-che-workspace-pods/) provides the procedure to add a certificate to the trustore available to the che server pod. 

The only valid use case I see is for this is: single user Che deployment (no keycloak), OpenShift is using a self-signed certificate and the (single-)user wants his OpenShift token to be injected in his workspaces automatically. But for this use case, for the user, it should be better to provide his OpenShift token in his preferences rather then:
1. retrieving the self-signed cert 
2. creating a secret 
3. paching the che server config

cc @rkratky @vinokurig @benoitf

**Comment by vinokurig** [comment]
I am not sure that it is a good idea to store tokens in user preferences

**Comment by tolusha** [comment]
Custom certificates are also provisioned into all pods for the namespace.
It might be useful for some cases.
For instance in this request https://issues.redhat.com/browse/CRW-640

**Comment by l0rd** [comment]
Adding a certificate of an untrusted CA in the che server trustore is useful in at least the following scenarios:
- the TLS cert used by Keycloak is signed by an untrusted CA
- Keycloak is behind a proxy that uses an untrusted CA

Closing this issue
