### ISSUE TITLE
How to send workspace runtime logs to browser/theia?

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#17037]
Our workspace runtimes mostly consist of a single Docker image running PHP & nGinx. The containers output logs that our developers would like to be able to see to `stderr`.

For example, our supervisors config is set to:

```
[program:php-fpm]
command=php-fpm7
redirect_stderr=true
stdout_logfile=/dev/stdout
```

At the moment, the only way I can see of accessing the output is for an admin to directly view the container logs (i.e. kubectl logs..).

Is there a way to redirect this to the IDE/Output/Problems tab? I can't see anything in the docs about this.

**Comment by ericwill** [comment]
cc @skabashnyuk, is this something your team would be responsible for?

**Comment by skabashnyuk** [comment]
@ericwill looks like a nice plugin feature.
