### ISSUE TITLE
How to change default ingress url

### ISSUE THREAD

**Issue by sushant08** [eclipse-che/che#17036]
## Summary

I am running eclipse che on eks using chectl how i can change url prefix. By default it comes like che-che. Any help much appreciated.

**Comment by tolusha** [comment]
It is hardcoded to
`DEPLOYMENT_NAME + "-" + NAMEPSACE + "." + DOMAIN`

**Comment by sushant08** [comment]
> It is hardcoded to
> `DEPLOYMENT_NAME + "-" + NAMEPSACE + "." + DOMAIN`

So no way to change it right?

**Comment by tolusha** [comment]
No way

**Comment by sushant08** [comment]
Okay thanks for letting me know.
