### ISSUE TITLE
workspace creation fail due to server check (che version 7.12.1)

### ISSUE THREAD

**Issue by insoo67park** [eclipse-che/che#17035]
## Summary
I installed che (version 7.12.1) with single user, multi-host using heml into my private k8s cluster.
But when I try to create workspace (simple python environment), che show me  message:  "Server 'theia' in container 'theia-ideqm8' not available" at org.eclipse.che.api.workspace.server.hc.ServerChecker$ServerCheckingTask.run(ServerChecker.java: 122) 
But workspace was created successfully (I check it web browser with direct url-I put into another browser tab url from ingress and it showed me theia ide, even thought it was disconnected about 5 minute later)

## Relevant information
The source code for line number 122 of ServerChecker class is below
public void run() {
      if (isTimedOut()) {
        reportFuture.completeExceptionally(
            new InfrastructureException(  // --> This line number is 122
                String.format(
                    "Server '%s' in container '%s' not available.", serverRef, machineName)));
      } else if (isAvailable()) {
        currentNumberOfSequentialSuccessfulPings++;
        if (currentNumberOfSequentialSuccessfulPings == successThreshold) {
          reportFuture.complete(serverRef);
        } else {
          timer.schedule(new ServerCheckingTask(currentNumberOfSequentialSuccessfulPings), period);
        }
      } else {
        timer.schedule(new ServerCheckingTask(0), period);
      }
    }

I checked che server log and found only che-theia failed to check servers

Performing servers check for machine 'vscode-python7dr' in workspace 'workspaceb7ksdauw4iu1fiw4'
Performing servers check for machine 'python' in workspace 'workspaceb7ksdauw4iu1fiw4'
Performing servers check for machine 'che-machine-execqaq' in workspace 'workspaceb7ksdauw4iu1fiw4'
Performing servers check for machine 'che-jwtproxy' in workspace 'workspaceb7ksdauw4iu1fiw4'
Performing servers check for machine 'theia-ideqm8' in workspace 'workspaceb7ksdauw4iu1fiw4'
Servers check done for machine 'che-machine-execqaq' in workspace 'workspaceb7ksdauw4iu1fiw4'
Servers check done for machine 'python' in workspace 'workspaceb7ksdauw4iu1fiw4'
Servers check done for machine 'vscode-python7dr' in workspace 'workspaceb7ksdauw4iu1fiw4'
Servers check done for machine 'che-jwtproxy' in workspace 'workspaceb7ksdauw4iu1fiw4'

But no servers check done for theia-ideqm8 machine message showed forever.
(About 4 ~ 5 minutes later, my workspace stopped and disappeared)

So I checked how che check for k8s environment and I found that it extract machines and servers information from k8s services/ingresses (in KubernetesServersResolver.java)

And in case of k8s services 

private void fillServiceServers(Service service, Map<String, ServerImpl> servers) {
    Annotations.newDeserializer(service.getMetadata().getAnnotations())
        .servers()
        .forEach(
            (name, config) ->
                servers.put(
                    name,
                    new RuntimeServerBuilder()
                        .protocol(config.getProtocol())
                        .host(service.getMetadata().getName())
                        .port(config.getPort())
                        .path(config.getPath())
                        .attributes(config.getAttributes())
                        .targetPort(config.getPort())
                        .build()));
  }

Above code say that host and port are extracted from k8s service's metadata' name and metadata -> annotation for each

In my case, metadata name is serverm581wjdy-theia-ideus3 and ports are 3130. 13131, 13132, 13133 (http protocol)

I think if che server checker try to check for url (http://serverm581wjdy-theia-ideus3:3130, serverm581wjdy-theia-ideus3:13131, serverm581wjdy-theia-ideus3:13132, serverm581wjdy-theia-ideus3:13133), che could not connect.

In case of ingress, I think, I can make che find right url using my dns setting (like address=/*.domain/ip_address)

1. Is my guessing right? or I have something missed?.
2. Is Server check using data extracted from metadata of k8s' services meaningful?
   - I think, we can check all server's url using ingress information
3. Ports for che theia are 3100, 3130, 13131, 13132, 13133 (at plugin-registry-> /htdoc/v3/plugin/eclipse/che-theia/7.12.1/meta.yaml)
   - But I cannot find ports used by che-theia except 3100 (http://localhost:3100 worked but other ports not worked)
   - Could you explain me what are they mean for each?
   - Actually, when I try to connect with url which showed in ingress, my nginx controller show me 502 bad gateway error ( this is due to no opened port at the che theia server)

I guess I cannot create my workspace with my k8s cluster unless che source code is changed.
Is my thinking right? or I have a big mis-understanding?
If I have something wrong, teach me please.

Thanks for all your team members always.

**Comment by insoo67park** [comment]
Oh. I think if more log at the che-server we can get, I could find cause more easily.
Could you change source code to write more log at debug level (especially for che-theia-> I can see many issues for che-theia, which not solved)

**Comment by insoo67park** [comment]
Could anyone inform me of how my question is going? Should I give up making my workspace in eclipse che?

Thanks a lot.

**Comment by strongit** [comment]
same issue here。
#17391
Is there a solve way？

**Comment by skabashnyuk** [comment]
Closing as duplicate in favor of https://github.com/eclipse/che/issues/16439 and https://github.com/eclipse/che/issues/16451

**Comment by skabashnyuk** [comment]
According to the information from @tolusha  they made multiple
improvements in installation with tls that might fix this problem.
Our suggestion would be to try to test the latest release and let us know if this problem is still reproducible. In case if it
is reproducible please follow up the whole Github bug template
and let us know the necessary information on how to reproduce it.
