### ISSUE TITLE
Image Puller Caching CPU limits/request

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17049]
### Is your enhancement related to a problem? Please describe.

[It is currently possible to specify the memory limit and request](https://www.eclipse.org/che/docs/che-7/caching-images-for-faster-workspace-start/#image-puller-overview_caching-images-for-faster-workspace-start) for the puller caching containers using `CACHING_MEMORY_REQUEST` and `CACHING_MEMORY_LIMIT`. But it's not possible to specify the equivalent parameters for CPU resources. The consequence is that the default CPU values will be used and the pod may fail to start.

### Describe the solution you'd like

Add `CACHING_CPU_REQUEST` (defaults to 0.05) and `CACHING_CPU_LIMIT` (defaults to 0.2)

**Comment by ibuziuk** [comment]
@l0rd should this issue be a part of the upcoming sprint?

**Comment by l0rd** [comment]
Yes please @ibuziuk. Otherwise it's really hard to use the image puller.

**Comment by ibuziuk** [comment]
@tomgeorge I believe we can close the issue now?
