### ISSUE TITLE
[devworkspace] Create logo for Che Workspace Operator/Openshift Terminal

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#17043]
### Is your task related to a problem? Please describe.

Currently as it stands the csvs for the workspace operator/openshift terminal do not have any logo associated with them and we probably need one before we release openshift terminal operator for openshift 4.5.x

### Describe the solution you'd like

A logo created for Openshift Terminal operator

**Comment by beaumorley** [comment]
I have a visual designer who can create a logo. Do we have any brand in place right now? For example, do we have any documentation that uses iconography or brand elements we want to be consistent with? 

Often a logo is a metaphor for something or represents something about the product/feature. We have an icon that appears in the masthead of ODC when the terminal operator is installed. I believe it is something like this (<). Wondering if we could riff off of that?

@l0rd  Anyone else I could bring into this conversation?

**Comment by l0rd** [comment]
@beaumorley I think we should be consistent with OpenShift logo rather than Che.
cc @sspeiche @pdaverh @gorkem

**Comment by sspeiche** [comment]
It would be fine to use default operator logo for now
