### ISSUE TITLE
Che-Theia failed with error 'Refused a WebSocket connection'

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#17047]
### Describe the bug

Running of another Che-Theia instance in a running container appeared to be broken.
Che-Theia could not be initialized properly because of errors when handsnake of WebSocket requests.

### Che version

 - [x] latest
 - [x] nightly

### Steps to reproduce

1. Create workspace from the devfile https://github.com/eclipse/che-theia/blob/master/devfiles/hosted-che-dogfooding.devfile.yaml
2. Build and run Che-Theia

### Runtime
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![error](https://user-images.githubusercontent.com/1655894/83261710-7a8dd980-a1c4-11ea-8a23-eb8cd601e7dd.png)

**Comment by azatsarynnyy** [comment]
FYI `eclipse/che-theia:next` image has been updated on quay.io, with the fix applied
