### ISSUE TITLE
.NET Core 3.1 shows lots of Problems

### ISSUE THREAD

**Issue by tmds** [eclipse-che/che#17045]
I've created an a .NET Core app on che.openshift.io using https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/2.1.x/dependencies/che-devfile-registry/devfiles/05_dotnet/devfile.yaml.

The applications list a bunch of Problems.

![lots-of-problems](https://user-images.githubusercontent.com/1025424/83257756-4a8b0a00-a1b5-11ea-97f8-9116527f9c96.png)

I'm not sure how I can get rid of these. I tried clicking the 'Restore' button at the bottom right. I'm not sure that actually did something. I application builds successfully (using the gear). Even when running the application, the problem view remains unchanged.

The OmniSharp log has this at the end:
```
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: web
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        web: Did not find 'Microsoft.NETCore.App' in lock file.
```

May be related to https://github.com/OmniSharp/omnisharp-vscode/issues/3314.

cc @nickboldt @svor

**Comment by tmds** [comment]
Is this being worked on?

**Comment by nickboldt** [comment]
I'm not sure. please look for an existing JIRA (CRW issues are in JIRA, not GH issues).

https://issues.redhat.com/browse/CRW-1023?jql=project%20%3D%20CRW%20AND%20(text%20~%20dotnet%20OR%20text%20~%20.net)%20ORDER%20BY%20key%20DESC
or
https://issues.redhat.com/browse/CRW-798?jql=project%20%3D%20CRW%20AND%20(text%20~%20dotnet)%20and%20fixversion%20in%20(2.2.0.GA)

If none found, feel free to open a new one and assign to the Plugins team (@ericwill or @svor )

**Comment by ericwill** [comment]
We have added this issue into our sprint plan and hope to work on it in the upcoming weeks.

**Comment by ericwill** [comment]
Looks like the work here is done, thanks @svor!

**Comment by svor** [comment]
The problem should be fixed if you update plugin-registry with latest changes
