### ISSUE TITLE
Enable singlehost strategy to not be ingress-bound

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#17059]
Che server needs to be updated to support single host strategy on OpenShift. 
Because this implementation will not be based on ingresses (or routes) we need to insert another layer of indirection in our workspace provisioning code that will hide the details of how workspace is exposed from the "upper layers".

Currently the `ExternalServerExposer` is directly involved in creating ingresses/routes but this will no longer be the case. The API of the exposer probably need not change but it will have to delegate to yet another layer of provisioning code.

This is a subtask of #12914.

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che/pull/17430
