### ISSUE TITLE
Fix `scl: command not found` issue on periodic tests

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17052]
We have been trying to fix the issue for a while. Now we got an advice (from 
Fabian Arrotin <arrfab@centos.org>) which should fix the problem:
```
Haven't parsed you whole .sh script but you point only to
centos-release-scl in [2] while in your log [1] you try to call scl
without having even installed scl-utils ?
```

Investigate if we need to install both `centos-release-scl` and `scl-utils`.

**Comment by ScrewTSW** [comment]
Issue seems to be fixed, thank you Fabian. Closing.
