### ISSUE TITLE
[devworkspace] How to handle branding of the Che Workspace Operator

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#17057]
### Is your task related to a problem? Please describe.

Currently as it stands the che workspace operator creates deployments, configmaps, etc with the name che-workspace-controller as its defaults. But, when an admin installs a branded version of the che workspace operator such as the Openshift Terminal operator for example, they would expect to see an Openshift Terminal deployment, Openshift Terminal configmap etc and not che-workspace-controller.

This kind of makes it confusing for the admin who might not understand why che-workspace-controller will all of a sudden be on their cluster. I think we should find a way to be able to brand Che Workspace Operator such that it creates correctly named deployments, configmaps, etc.

### Describe the solution you'd like

Find a way to handle branding of the che workspace operator such that you can change one value and it propogates that name to deployments, configmaps, etc

### Describe alternatives you've considered

Keep it the same and just write in the description of the Openshift Terminal operator that it utilizes the che-workspace-controller under the hood and that's why those files are there

### Additional context

@davidfestal @l0rd WDYT?

**Comment by l0rd** [comment]
Currently (first iteration) the only name that should be visible to final users should be "OpenShift Terminal". The operator should be named the OpenShift Terminal Operator.

On a second iteration we should split it in 2 distinct operators: OpenShift Terminal Operator and DevWorkspace Operator. The latter should be a dependency of the former. When a user enables OpenShift Terminal he enalbes DevWorkspace too.

Finally the last step would be to make Che and CodeReady Workspaces operators dependent on the DevWorkspace operator. If DevWorkspace operator is not enabled, deploying Che or CRW would enables it automatically.

**Comment by sleshchenko** [comment]
So, I think that can be closed with the summary: the only thing we care about now - WebTerminal operator and visible description. All k8s objects (webhooks, deployments, ...) could be named with `devworkspace.devfile.io`|`devworkspace`|`controller.devfile.io` whichever makes more sense for concrete object. And then eventually that objects will be migrated from WebTerminal Operator ownerships to DevWorkspace Operator.

Feel free to reopen it if there are some things that should be figured out.
