### ISSUE TITLE
Struggling working with Japanese filenames. 

### ISSUE THREAD

**Issue by Leward** [eclipse-che/che#1706]
Eclipse Che (I use it via codenvy.com) seems not to work very well with Japanese filenames. 

**Reproduction Steps:**
1. Use the "code" button on this repo : https://github.com/Leward/leward-blog 
2. Try to rename a japanese filename via the UI (remove the first character of the filename)
3. Try to rename a japanse filename through the command line (using the `mv` command, remove the first character of the filename)

**Expected behavior:**

The filename with Japanese characters should be an acceptable value.
Renaming via command line should rename the file with the expected value. 

**Observed behavior:**

The filename is not accepted in the UI : 
![rename_jp_file_ui](https://cloud.githubusercontent.com/assets/1108235/16732091/ae98f6f8-477b-11e6-90f6-b80690384bed.png)

Though command line it does not rename the file as expected: 

```
$ ls -l
drwxr-xr-x 2 user user 138 Jul 11 13:20 ./
drwxr-xr-x 3 user user  37 Jul 11 12:54 ../
-rw-r--r-- 1 user user 244 Jul 11 12:45 201-JPブログ.markdown

$ mv 201-JPブログ.markdown 01-JPブログ.markdown
$ ll                                                                                                                                                                                        
drwxr-xr-x 2 user user 137 Jul 11 13:26 ./
drwxr-xr-x 3 user user  37 Jul 11 12:54 ../
-rw-r--r-- 1 user user 244 Jul 11 12:45 201JPブログ.markdown
```

Filenames: 

```
201-JPブログ.markdown # original
01-JPブログ.markdown # expected
201JPブログ.markdown # actual
```

**Che version:**    Codenvy 4.4.2
**OS and version:** Don't know
**Docker version:** Don't know  
**Che install:**    Codenvy 

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: I cannot tell
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by thyeun** [comment]
i have the same issue also for created a Chinese/Korean character name for a new file. 

Che version : 4.4.0
OS and version : windows 10 build 10240

**Comment by TylerJewell** [comment]
Yes - just double checked.  Issue confirmed.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-1485

**Comment by musienko-maxim** [comment]
Cannot reproduce
