### ISSUE TITLE
Update to latest clangd 0.1.5 and cdt-gdb-vscode 0.0.91

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17067]
Due to a recent update to jsonschema, `che-incubator/cpptools/0.1` is now failing schema validation, which I've fixed like this:

https://github.com/redhat-developer/codeready-workspaces/commit/b97b8b3e4a5afc819d8a71f9f68c0cf1e976dce8

But this reminded me that we could also move away from this ancient version and pull the latest bits from:

- [ ] 0.0.91 https://github.com/eclipse-cdt/cdt-gdb-vscode/commit/2cbbb857a2acf0b2e46bab30e0cbbfb547514856
- [ ] 0.1.5 https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd

With new vsix builds on dl.jb.org, we could then create a new `che-incubator/cpptools/0.1.5` that would avoid the above schema validation problem, and would get us newer content. 

@mkuznyetsov can you include this new plugin in the 7.14.0 release?

**Comment by nickboldt** [comment]
If this is done, please close it.

Can you also contribute the same fix to downstream CRW 2.2?

**Comment by ericwill** [comment]
Upstream is done: https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml#L78-L80
