### ISSUE TITLE
Dashboard, cannot scroll the first time

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17068]
### Describe the bug
Scroll bar is not available the first time accessing the dashboard

### Steps to reproduce
1. open a new window and go to https://che.openshift.io/dashboard/#/getstarted

### Expected behavior
The scrollbar should be available but it is not.
The workaround is to click again to the get started menu item

![image](https://user-images.githubusercontent.com/650571/83493568-3b59d400-a4b5-11ea-8172-19418dd57ecf.png)

**Comment by priyamara** [comment]
I see the scroll bar when accessing the link.

**Comment by sunix** [comment]
Thanks looks like it has auto-magically been fixed :)
