### ISSUE TITLE
Che 7.14.1 Release (respin of 7.14.0 due to release process error)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17066]
### List of pending issues / PRs
* [x] Update to latest clangd 0.1.5 and cdt-gdb-vscode 0.0.91 #17067
* [x] Improve Che Release process cico_release.sh script #16732
* [ ] (add items)

### Release status

In series, the following will be released via [che-release](https://github.com/eclipse/che-release/blob/master/cico_release.sh):

* che-theia, che-machine-exec, che-devfile registry, 
* che-plugin-registry (once che-theia and machine-exec are done)
* che-parent, che-dashboard, che-workspace-loader, and che (server assembly)

Then **automatically**:

* release che server in Maven Central 

Then by script:

* che-operator
* generation of OperatorHub PRs
* chectl

- [x] che-theia, che-machine-exec, che-devfile-registry, che-plugin-registry
- [x] che-parent, che-dashboard, che-workspace-loader, che
- [x] che-operator _(depends on all of the above)_
  - [x] https://github.com/operator-framework/community-operators/pull/1830 
  - [x] https://github.com/operator-framework/community-operators/pull/1829 
- [x] chectl _(depends on all of the above)_

If this is a .0 release:

- [ ] complete current milestone
  - [ ] move incomplete *deferred* issues to backlog
  - [ ] move incomplete *WIP* issues to next milestone
  - [ ] close completed issues
  - [ ] close milestone

| Owner | Process | Script | CI | Artifact(s) + Container(s) |
| --- | --- | --- | --- | --- |
| @mkuznyetsov  | [che-theia](https://github.com/eclipse/che-theia/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-theia-che-release/) | [`eclipse/che-theia`](https://quay.io/eclipse/che-theia) |
| @mkuznyetsov  | [che-machine-exec](https://github.com/eclipse/che-machine-exec/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-machine-exec-release/) | [`eclipse/che-machine-exec`](https://quay.io/eclipse/che-machine-exec)| 
| @mkuznyetsov  | [che-plugin-registry](https://github.com/eclipse/che-plugin-registry/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-plugin-registry-release/) | [`eclipse/che-plugin-registry`](https://quay.io/eclipse/che-plugin-registry)| 
| @mkuznyetsov  | [che-devfile-registry](https://github.com/eclipse/che-devfile-registry/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-devfile-registry-release/) | [`eclipse/che-devfile-registry`](https://quay.io/eclipse/che-devfile-registry)| 
| @mkuznyetsov  | [che-parent](https://github.com/eclipse/che/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-release-che-release) | [che-parent](https://search.maven.org/search?q=a:che-parent) |
| @mkuznyetsov  | [che-dashboard](https://github.com/eclipse/che-dashboard/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-release-che-release/) | [`che-dashboard`](https://quay.io/repository/eclipse/che-dashboard?tag=next&tab=tags) |
| @mkuznyetsov  | [che-workspace-loader](https://github.com/eclipse/che-workspace-loader/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-release-che-release) | [`che-workspace-loader`](https://quay.io/repository/eclipse/che-workspace-loader?tag=next&tab=tags) |
| @mkuznyetsov  | [che](https://github.com/eclipse/che/blob/master/RELEASE.md) | [cico_release.sh](https://github.com/eclipse/che-release/blob/master/cico_release.sh) | [centos](https://ci.centos.org/job/devtools-che-release-che-release) | [che.core](https://search.maven.org/search?q=che.core),<br/> [`eclipse/che-server`](https://quay.io/eclipse/che-server),<br/>[`eclipse/che-endpoint-watcher`](https://quay.io/eclipse/che-endpoint-watcher),<br/> [`eclipse/che-keycloak`](https://quay.io/eclipse/che-keycloak),<br/> [`eclipse/che-postgres`](https://quay.io/eclipse/che-postgres),<br/> [`eclipse/che-server`](https://quay.io/eclipse/che-server),<br/> [`eclipse/che-e2e`](https://quay.io/eclipse/che-e2e) |
| @tolusha| [che-operator](https://github.com/eclipse/che-operator/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-operator/blob/master/make-release.sh) | ? | [`eclipse/che-operator`](https://quay.io/eclipse/che-operator)| 
| @tolusha| [chectl](https://github.com/che-incubator/chectl/blob/master/RELEASE.md) | [make-release.sh](https://github.com/che-incubator/chectl/blob/master/make-release.sh) | [travis](https://travis-ci.org/che-incubator/chectl) | [chectl releases](https://github.com/che-incubator/chectl/releases)

**Comment by nickboldt** [comment]
A mistake was made during release of 7.14.0.

Maven artifacts of 7.14.0 were pushed to Nexus, before but they reference che-parent of 7.14.0-SNAPSHOT version rather than 7.14.0 release version.

So we need to roll out a new 7.14.1 release today to fix that error

**Comment by mkuznyetsov** [comment]
7.14.1 release complete, community operator PRs are created

**Comment by dmytro-ndp** [comment]
Release tests of MultiUser Eclipse Che 7.14.1 with TLS intalled by operator installer on different infrastructure:
1) E2E tests on **minishift 3.11**
:ok_hand: [E2E dashboard/factory tests on minishift](https://ci.centos.org/view/Devtools/job/devtools-che-release-devfiles-test/2/) - **have passed**
:ok_hand: [Happy path tests](https://ci.centos.org/view/Devtools/job/devtools-che-release-multiuser-happy-path-test/3/) - **have passed**
:ok_hand: [ocp oauth tests](https://ci.centos.org/view/Devtools/job/devtools-che-release-ocp-oauth-test/3/) - **have passed**
:ok_hand: [rolling strategy test](https://ci.centos.org/view/Devtools/job/devtools-che-release-rolling-strategy-test/3/) - **have passed**

2) E2E tests on minikube 1.1.1
:running: [Happy path tests, devfiles tests, git ssh flow tests](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/release/job/MultiUser-Che-release-check-e2e-tests-against-k8s/76/) - _in progress_

3) E2E tests on QE OCP
:running: [dashboard/factory tests, devfile tests, git ssh flow tests **on OCP 4.5**](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/nightly/job/che-chectl-tls-no-oauth/9/) - _in progress_
:running: [devfile tests, git ssh flow tests of Eclipse Che **with OS OAuth support** on **OCP 4.4**](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/nightly/job/che-chectl-tls-oauth/32/) - _in progress_

Eclipse Che 7.14.1 **wasn't** tested on minikube with HELM and OLM installers.

**Comment by tolusha** [comment]
PRs are merged
