### ISSUE TITLE
Implement gateway-based singlehost strategy for Kubernetes

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#17060]
We currently have an implementation of the singlehost strategy for Kubernetes. This implementation is based on ingresses.

To unify the approach between Kubernetes and OpenShift we should be able to deploy Che with singlehost strategy also using the gateway.

We need to figure out whether the gateway approach is going to replace the ingress-based one or
whether we offer it as an option to the administrator.

Once OpenShift starts supporting path rewriting in routes (https://github.com/openshift/router/pull/129) we may think of having both ingress/route based impls and gateway-based impls for both Kubernetes and OpenShift. This would enable the user to pick a solution that is more appropriate for their environment.

This is a subtask of #12914.

This issue depends on #17059 and should implemented after or alongside with #17061.

**Comment by sparkoo** [comment]
> Once OpenShift starts supporting path rewriting in routes (openshift/router#129) we may think of having both ingress/route based impls and gateway-based impls for both Kubernetes and OpenShift.

OpenShift in default configuration still can't have routes with same host in multiple namespaces. It can be enabled by some cluster-wide config option, but we don't want that.

And I'm not sure if openshift/router#129 has any chance to get into 3.11.
