### ISSUE TITLE
Run smoke test in Prow with latest Openshift

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#17070]
### Is your task related to a problem? Please describe.

Would be nice to have some smoke suite running in Prow with latest Openshift. 
This suite should at least install Che and start workspace. If possible, measumeremnts of che-server startup and workspace startup should be measured (sending & gathering of these data will be done as part of different issue).

**Comment by flacatus** [comment]
Let's create another issue about sending and gathering the data
