### ISSUE TITLE
Fix CVE issues in chectl/crwctl dependencies

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17075]
Dependabot reports three problems in crwctl:

https://github.com/redhat-developer/codeready-workspaces-chectl/network/alerts

![image](https://user-images.githubusercontent.com/227597/83542509-0eafb780-a4c9-11ea-989e-5e9f9a0d6031.png)

Do we just have to update yarn.lock from the latest in chectl master branch? Or are these problems also present in chectl?

**Comment by tolusha** [comment]
We don't CVE issues anymore
https://github.com/che-incubator/chectl/security/dependabot
