### ISSUE TITLE
'Che in TLS mode with self-signed certificates' doc should explain how to import CA certificate to Chrome on Windows

### ISSUE THREAD

**Issue by dgolovin** [eclipse-che/che#17077]
### Is your task related to a problem? Please describe.
Instruction for [Installing Che in TLS mode with self-signed certificates](https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-che-with-tls_installing-che-in-tls-mode-with-self-signed-certificates) has Chrome CA certificate import only for Linux or macOS (hard to tell from screen-shots). Certificate management related UI looks different on Windows 10. 
It just a link to call `Certirficates` dialog (see below).

![image](https://user-images.githubusercontent.com/620330/83569204-f9db2000-a4d8-11ea-9dba-ed3ffb754bf5.png)

Then certificate should be imported as trusted root CA and more importantly browser should be restarted to pick it up (needs a confirmation).

### Describe the solution you'd like

Documentation how to import Root CA Certificate in Chrome browser should have Linux, macOS and Windows specific steps.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by l0rd** [comment]
I see that there are instructions for windows as well now. Closing.
