### ISSUE TITLE
E2E account tests are failing being run against Eclipse Che on QE OCP

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17071]
### Is your task related to a problem? Please describe.
Java selenium E2E **[AccountTest](https://github.com/eclipse/che/blob/master/tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/AccountTest.java)** has failed being run against Eclipse Che with TLS support on QE OCP https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/java-tests/781/E2E_20tests_20report/

#### AccountTest.shouldChangeEmailFirstAndLastName()
> Expected condition failed: waiting for visibility of element located by By.xpath: //div[@id='tabs-menu']//a[text()='Federated Identity'] (tried for 10 second(s) with 500 MILLISECONDS interval) Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host: 'rhel7-8gb-16217', ip: '10.0.103.155', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.el7.x86_64', java.version: '1.8.0_242' Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver

#### AccountTest.shouldChangePasswordAndCheckIt()
> Expected condition failed: waiting for visibility of element located by By.id: user-name (tried for 10 second(s) with 500 MILLISECONDS interval) Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host: 'rhel7-8gb-16217', ip: '10.0.103.155', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.el7.x86_64', java.version: '1.8.0_242' Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver

![org eclipse che selenium dashboard AccountTest shouldChangeEmailFirstAndLastName_time-1591074174865-millis](https://user-images.githubusercontent.com/1197777/83498401-8c24f900-a4c4-11ea-9873-359b67571cf0.png)

![org eclipse che selenium dashboard AccountTest shouldChangeEmailFirstAndLastName_time-1591074173441-millis](https://user-images.githubusercontent.com/1197777/83498411-8f1fe980-a4c4-11ea-8285-f5717555a041.png)

**Comment by SkorikSergey** [comment]
@dmytro-ndp The test fails because github identity provider not exist in Keycloak(usually we add this after Che deployment by [createIndentityProvider](https://github.com/eclipse/che/blob/faadff6b9791b6d41425feff3318f91f9ac31e87/tests/.infra/centos-ci/functional_tests_utils.sh#L423)  ).

**Comment by dmytro-ndp** [comment]
Thanks for explanation, @SkorikSergey. So, we need to fix testing pipeline.

**Comment by nickboldt** [comment]
Slip to 7.18

**Comment by rhopp** [comment]
Should be fixed by https://github.com/eclipse/che/pull/17757/files#diff-0cffe78415de54b24f502ef72f91e613L93
