### ISSUE TITLE
Create Prow CI Job for cloud shell e2e tests

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#17089]
### Describe the solution you'd like

After merging https://github.com/che-incubator/che-workspace-operator/pull/90 should create a new job in PROW CI to run those tests in different openshift versions(Openshift 4.4 and Openshift nightly). We should open a PR [here](https://github.com/openshift/release/tree/master/ci-operator) following this guide:https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4/edit .

**Comment by sleshchenko** [comment]
I believe it's fixed and can be closed. @flacatus ?

**Comment by flacatus** [comment]
Closed!
