### ISSUE TITLE
che-docs devfile is not working anymore and factory link has been removed from README.md

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17087]
1. Che-docs devfile is not working anymore. `serve che-docs` command is broken:
![image](https://user-images.githubusercontent.com/650571/83663111-b2cc5800-a5c8-11ea-8210-feee29286650.png)

2. Factory link has been removed from README.md https://github.com/eclipse/che-docs/commit/991c82e93a6dead296b0e424b1a86142106dac45#diff-04c6e90faac2675aa89e2176d2eec7d8L10

**Comment by ibuziuk** [comment]
@rkratky @themr0c should be P1 IMO

**Comment by rkratky** [comment]
There's an issue for this at @ #15866.

Closing as a duplicate.
