### ISSUE TITLE
[devworkspace-api] Propagate devfile 2.0 and related changes to console 

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17097]
### Is your task related to a problem? Please describe.
We need to make sure changes in the [che-workspace-operator](https://github.com/che-incubator/che-workspace-operator/) repo are synced to the OpenShift console.

1. Updated devfile2.0 CRDs (once PR https://github.com/che-incubator/che-workspace-operator/pull/92 is merged)
2. Webhook names will be updated in https://github.com/che-incubator/che-workspace-operator/pull/92 and need to be reflected in console backend.
3. Rename `immutable` annotation to `restricted-access`

**Comment by sleshchenko** [comment]
https://github.com/openshift/console/compare/master...sleshchenko:devworkpsace-crd?expand=1 is addressing 1. and 2.
When we'll have 3. - the following PR will be created on OpenShift Console side

**Comment by amisevsk** [comment]
3. is done in https://github.com/che-incubator/che-workspace-operator/pull/97

**Comment by sleshchenko** [comment]
The PR on OpenShift Console is merged https://github.com/openshift/console/pull/5687 so it's should be done now.
