### ISSUE TITLE
Force TLS support when upgrading

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17090]
### Is your enhancement related to a problem? Please describe.

Che Theia without TLS doesn't work properly hence we should avoid Che installations without TLS. However old installers deployed Che without TLS and upgrading to newer Che doesn't switch to TLS-enabled. 

### Describe the solution you'd like

Set TLS support to true when upgrading Che.

🤙   Is included in epic #17012 

⚠️ Depends on the [work to automatically set selfSignedCert](https://github.com/eclipse/che/issues/16764).

**Comment by dmytro-ndp** [comment]
IMHO we should warn or may be ask user before setting up TLS support during upgrading by using the `chectl server:update` command.
And I don't know if it's even possible to notife/ask user when update goes through **OperatorHub**.

**Comment by l0rd** [comment]
@dmytro-ndp I agree that we should notify the user when it's possible. Like when whatsapp enabled e2e encryption:

![image](https://user-images.githubusercontent.com/606959/83812437-d623ff80-a6bb-11ea-8f1d-4a4e2a38d6ab.png)

But we should not ask the user. There is no point for a user to use insecure http: beyond being insecure it's not working with latest Che! Asking the user if he wants to enable TLS is making it easy for him to make a mistake. That's exactly what we want to avoid: it should be easy to make the right choice and hard to make mistakes.

**Comment by mmorhun** [comment]
@l0rd should we proceed with this issue now/in the near future?

**Comment by tolusha** [comment]
There is no way to deploy Eclipse Che with TLS disabled since 7.43.0
All existed deployments will be automatically upgraded to use TLS
