### ISSUE TITLE
[devworkspace-api] Controller deployment namespace should be customizable.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17098]
### Is your enhancement related to a problem? Please describe.
Various parts of the che-workspace-controller depend on running in the `che-workspace-controller` namespace. These values are hard-coded, which makes renaming some fields tricky.

### Describe the solution you'd like
Should be able to set `NAMESPACE` var in Makefile and deploy controller to any namespace

### Additional information
May be addressed in https://github.com/che-incubator/che-workspace-operator/pull/83

**Comment by amisevsk** [comment]
cc: @JPinkney in case this is addressed by your PR.

**Comment by JPinkney** [comment]
It's not covered in that PR. Technically everything still works when installing with OLM but yeah we should probably make that configurable

**Comment by JPinkney** [comment]
I ended up looking into this and it _looks_ like the only thing that references the che-workspace-controller namespace when deploying via OLM  is the webhooks so I've opened a PR for that: https://github.com/che-incubator/che-workspace-operator/pull/95
