### ISSUE TITLE
"che-plugin-registry" repo Happy path PR check is triggered by comment without trigger phrase

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17105]
### Describe the bug
Happy path tests has been triggered by regular comment in PR of https://github.com/eclipse/che-plugin-registry repo doesn't matter if it contains trigger phrase `[ci-test]` (`[ci-test-happy-path]`) or doesn't, for example:
- https://github.com/eclipse/che-plugin-registry/pull/371#issuecomment-639107331
- https://github.com/eclipse/che-plugin-registry/pull/185#issuecomment-639606442

It seems [trigger phrase is incorrect](https://coreos.slack.com/archives/CRUQDU2BH/p1591303628224400): `.*\[ci-test\].*|.*\[ci-test-happy-path\].*`. 
`|` symbol may need to be back-slashed as well. 

### Steps to reproduce
Enter some comment without trigger phrase `[ci-test]` (`[ci-test-happy-path]`) into some PR requests of https://github.com/eclipse/che-plugin-registry/pulls

**Comment by ericwill** [comment]
che-plugin-registry HP tests are run via GitHub action now.
