### ISSUE TITLE
Idle workspace clean up and admin control over user's workspace.

### ISSUE THREAD

**Issue by puneetshukla-siemens** [eclipse-che/che#17107]
As a admin I want to see all the workspaces created by different users. As user is owner of his workspace, there shoud be a way for admin to see all the owners and workspace created by them.
Also there should be a option for admin to remove any workspace created by different users. This gives more control over releasing bounded pvc for idle workspace.

**Comment by l0rd** [comment]
@skabashnyuk, from a Che API point of view, is there a (super) user that has the privileges to get all the users workspaces?

**Comment by skabashnyuk** [comment]
>@skabashnyuk, from a Che API point of view, is there a (super) user that has the privileges to get all the users workspaces?

That is not possible at this moment.  He can get the details of the workspaces if he knows their name / id

**Comment by puneetshukla-siemens** [comment]
@skabashnyuk Is there a way for admin to get all the users or owners of workspace. The problem I want to solve is, users create a workspace the pvc is bound to that. As a owner I should be able to remove idle workspace to clear my cloud resources.
Admin can remove resources from AWS but when user open the workspace in Eclipse Che it will give error.
What I want is to give user a notification about idle workspace and if user doesn't want to use it further,  as a admin I can clear the workspace and resources created with it.

**Comment by skabashnyuk** [comment]
@puneetshukla-siemens when we are talking about saving resources, have you evaluate workspace idling capability of Eclipse Che? It allows us to stop workspaces that are not used. 

About pvc - So you want to destroy all persisted data(pvcs and all k8s objects associated with workspace) and workspace by itself?

**Comment by puneetshukla-siemens** [comment]
@skabashnyuk Yes that is exactly what I need. Idling capability allows to stop the workspace but I want to removed all data associated with workspace and workspace itself.
For that I would need the workspace user/owner information (eg. Dates and time of creation, idle period). Then remove resources assigned with the user.
Can you suggest any alternative way of getting this done?

**Comment by puneetshukla-siemens** [comment]
Any updates or suggestions on the same.? 😊

**Comment by skabashnyuk** [comment]
you may try to extend an `idling` code and propose a patch that stopping&& removing inactive workspaces for example.
