### ISSUE TITLE
Allow secrets mount as a file beside already existing files

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17113]
### Is your enhancement related to a problem? Please describe.
Current implementation of mounting secrets as a file is using kubernetes volume mount. This brings limitation when we try to mount file into directory that already contains some files. In this case, all files are gone and only our secret remains. Another limitation is that we can't mount secret into another volume.

### Describe the solution you'd like
Mount all secrets to some common place (`/tmp/secrets` ?) and copy them into desired. We may use init container or exec to do the job. Consider performance and implementation difficulty to choose the one.

### Describe alternatives you've considered
Ideas for other solutions?
 - create links instead of full copies
   - some software might have issues with links
 - include also file permissions ?
   - e.g. ssh keys requires some permission

### Additional context
https://github.com/eclipse/che/issues/14680

**Comment by gorkem** [comment]
+1 for using`symlinks`. Copying is always additional moving parts.

**Comment by sparkoo** [comment]
We've found out it is possible to achieve this with using `subPath` in `VolumeMount`. PR is ready

**Comment by sparkoo** [comment]
fixed by #17168
