### ISSUE TITLE
Docker LS not working in Quarkus stack

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17123]
### Describe the bug
In a Quarkus example stack, the Docker language support is not present. 

### Che version

 - [x] latest 7.14.1
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to `Get Started` page
2. Click on `Quarkus Tools` stack
3. Wait for the workspace to start
4. Open a file: `quarkus-quickstarts - getting-started- src - main - docker - Dockerfile.jvm`
5. The plain text is displayed, even without coloring.

### Expected behavior
There should be at least some basic LS support for Dockerfile.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) 4.5
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-06-09 17-05-59](https://user-images.githubusercontent.com/29278800/84165062-835b9680-aa73-11ea-8446-3d62fd188520.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ScrewTSW** [comment]
Confirmed, syntax highlight still not present on Che 7.15.1

**Comment by ericwill** [comment]
> Confirmed, syntax highlight still not present on Che 7.15.1

Confirmed on che.openshift.io as well. It seems the "Language Mode" is set to Plain Text, when it really should be Dockerfile. When I change the language to Dockerfile it works fine.

I'm guessing it has something to do with the extension (i.e. `.jvm` or `.native`). If I create a file just named "Dockerfile" in the same folder the language is detected correctly.

**Comment by vitaliy-guliy** [comment]
Should be fixed by https://github.com/microsoft/vscode/pull/103553

**Comment by vitaliy-guliy** [comment]
The fix is already in vscode master branch. There is a corresponding issue describing the problem https://github.com/microsoft/vscode/issues/102897

Will be working soon after
- releasing a new version of vscode ( the latest release is 1.47.3 )
- publishing of [vscode-docker](https://github.com/microsoft/vscode/tree/master/extensions/docker) extension to Open VSX Registry
- updating reference of the `vscode-builtin-docker` in https://github.com/eclipse/che-theia/blob/master/generator/src/templates/theiaPlugins.json

**Comment by vitaliy-guliy** [comment]
Reopened just to not be forgotten

**Comment by vitaliy-guliy** [comment]
Link with https://github.com/eclipse/che/issues/17524

**Comment by ericwill** [comment]
Adjusted the milestone to reflect that the issue will be fixed at a later time.
