### ISSUE TITLE
In Quarkus stack, the "Package Native" command is doing an Out Of Memory

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#17138]
# Describe the bug

The default stack is providing a command which is not working.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a "Quarkus Tools stack"
2. Launch command "package native"
3. --> out of memory

### Expected behavior

All commands working out of the box fro Quarkus Tools stack

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify) che.openshift.io

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context

it seems to be since Quarkus has been upgraded from 1.4.2 to 1.5.0 in the example. It requires more memory.

a PR has been merged on master to increase the memory https://github.com/eclipse/che-devfile-registry/pull/249 but it means that the stack doesn't work on che.openshift.io with default account.

**Comment by sunix** [comment]
I have tested https://github.com/eclipse/che-devfile-registry/pull/249 with a "normal account" and managed to start the workspace. Could someone else try? or help @apupier to understand why the workspace couldn't be started on his side?

**Comment by apupier** [comment]
I tried again and can start the workspace.
When calling "Package native", i got another error:

```
[INFO] --- quarkus-maven-plugin:1.5.1.Final:native-image (default) @ getting-started ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:36 min
[INFO] Finished at: 2020-06-15T07:30:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.5.1.Final:native-image (default) on project getting-started: Failed to generate native image: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildNativeImageJar threw an exception: java.lang.IllegalStateException: java.io.IOException: Failed to create a new filesystem for jar:file:/projects/quarkus-quickstarts/getting-started/target/getting-started-1.0-SNAPSHOT-native-image-source-jar/getting-started-1.0-SNAPSHOT-runner.jar
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:941)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.io.IOException: Failed to create a new filesystem for jar:file:/projects/quarkus-quickstarts/getting-started/target/getting-started-1.0-SNAPSHOT-native-image-source-jar/getting-started-1.0-SNAPSHOT-runner.jar
[ERROR]         at io.quarkus.bootstrap.util.ZipUtils.newFileSystem(ZipUtils.java:167)
[ERROR]         at io.quarkus.bootstrap.util.ZipUtils.newZip(ZipUtils.java:116)
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildNativeImageJar(JarResultBuildStep.java:522)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
[ERROR]         ... 7 more
[ERROR] Caused by: java.util.zip.ZipException: zip END header not found
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1715)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1037)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1046)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:128)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:109)
[ERROR]         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
[ERROR]         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
[ERROR]         at io.quarkus.bootstrap.util.ZipUtils.newFileSystem(ZipUtils.java:160)
[ERROR]         ... 14 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by sunix** [comment]
we can add the native build with the option  `-Dquarkus.native.native-image-xmx=2G` and unsure that we don't reach the limit.

**Comment by sunix** [comment]
@apupier any chance you give a try with 
- Command mode: https://che.openshift.io/factory?url=https://github.com/sunix/che-devfile-registry/raw/limitMemoryUsageForNativeBuild/devfiles/quarkus-command-mode/devfile.yaml
- Rest API: https://che.openshift.io/factory?url=https://github.com/sunix/che-devfile-registry/raw/limitMemoryUsageForNativeBuild/devfiles/quarkus/devfile.yaml
? (from the PR https://github.com/eclipse/che-devfile-registry/pull/314)

**Comment by apupier** [comment]
currently trying

**Comment by sunix** [comment]
could you also try the same command but using `mvn` instead of `./mvnw` ?

**Comment by ibuziuk** [comment]
should be fixed on workspaces.openshift.com. Closing
