### ISSUE TITLE
Changing keybindings settings are not persisted and gone once workspace refreshed or restarted

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#17134]
As title mentions, reproducible and happens on `7.14.1` on k8s deployment.

Also, `alt`+`w` have conflict with another key binding. I'd suggest setting the default to `ctrl`+`w` instead.

**Comment by sunix** [comment]
duplicates https://github.com/eclipse/che/issues/16753

**Comment by SDAdham** [comment]
Thx @sunix
