### ISSUE TITLE
chectl server:start with minikube is failling

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17142]
### Describe the bug
Installing che with chectl on minikube (with default option) is failling.
Environment Linux and using the minikube driver kvm2

Here the steps:
- install che in minikube
![image](https://user-images.githubusercontent.com/650571/84399528-432a1e80-ac01-11ea-943d-a14c1f907ae0.png)

- got stuck at this step (will eventually fail with timeout)
![image](https://user-images.githubusercontent.com/650571/84399589-5210d100-ac01-11ea-811d-d1346e17dc32.png)

- running the describe command
![image](https://user-images.githubusercontent.com/650571/84399684-6e147280-ac01-11ea-953f-58d25116aacd.png)

- showing the error
![image](https://user-images.githubusercontent.com/650571/84399734-7cfb2500-ac01-11ea-8bdf-ff137086a5b7.png)

**Comment by sunix** [comment]
Setting blocker as it is stopping new user onbording with Che ... first time installation.

**Comment by dmytro-ndp** [comment]
In Eclipse Che nightly tests the minikube has been started in no-driver mode:
```minikube start --vm-driver=none --cpus 4 --memory 13000 ```

**Comment by sunix** [comment]
@dmytro-ndp 
ok but I don't have docker and don't want to install it.

**Comment by gattytto** [comment]
here's a workaround:
in /usr/local/lib/chectl/templates/che-operator/crds/org_v1_che_cr.yaml
MUST set:
tlsSupport: false 
ingressDomain: 'your-local-ip.nip.io'



https://github.com/eclipse/che/issues/16545#issuecomment-611363921

**Comment by l0rd** [comment]
@mmorhun are you looking at this?

**Comment by mmorhun** [comment]
@sunix could you please provide minikube version ?

**Comment by sunix** [comment]
@mmorhun 
```
$minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```

**Comment by gattytto** [comment]
this will keep happening until:
1) temporary workaround is added to chectl consisted of:
     precreate storageclasses for postgres and workspaces and set them as settings in cr
2) minikube upstream issue is fixed https://github.com/kubernetes/minikube/issues/7218

**Comment by gattytto** [comment]
https://github.com/eclipse/che/issues/16409

**Comment by gattytto** [comment]
with mentioned workarounds in https://github.com/eclipse/che/issues/16545#issuecomment-611363921:
![image](https://user-images.githubusercontent.com/407397/84651604-9db4ca80-aee0-11ea-8b4b-4ebfa2eb1db6.png)

![image](https://user-images.githubusercontent.com/407397/84651750-d8b6fe00-aee0-11ea-9d35-f680db0ebdcc.png)

**Comment by mmorhun** [comment]
> set tlsenabled: false as default

@gattytto could you please elaborate more on this. Why is this required?

**Comment by gattytto** [comment]
> > set tlsenabled: false as default
> 
> @gattytto could you please elaborate more on this. Why is this required?

last time I tried with its default value, selfSignedCert: false is a default and tlsEnabled: true is default at the same time, which breaks.

**Comment by gattytto** [comment]
when setting up in macOS using minikube and chectl + che-operator, there is the need of "minikube ssh" and "su", then "mkdir -p /data/wksp" and "chmod -R 777 /data", then chectl start command from macOS will work (after using the storageclass and cr.yaml workaround)

**Comment by mmorhun** [comment]
@gattytto I think problem with TLS will be gone after https://github.com/eclipse/che/issues/16764 is fixed.

**Comment by gattytto** [comment]
timeout is also another blocker in this situation, because most of the times if no images are present in the vm, timeout won't be enough unless a very fast pc and a very fast internet is being used. Because of this first attempt of starting che will fail, making it needed to cleanup the postgres /userdata and recreating the storageclasses and volumes.

**Comment by mmorhun** [comment]
Our team is going to handle this issue in the next sprint. We already have similar issues/requests.

**Comment by mmorhun** [comment]
@gattytto thank you for deep investigations.
As about timeouts, I think that should be another issue....

**Comment by gattytto** [comment]
I think imagepulls should not be counted as part of the timeout

**Comment by gattytto** [comment]
@mmorhun it seems like this is going to be fixed very soon upstream (check [this commit](https://github.com/codebutler/minikube/commit/5c2bc19183ad265a889f5d7905e09b85cca3f650) as mentioned in https://github.com/kubernetes/minikube/issues/7218

**Comment by mmorhun** [comment]
@gattytto I've seen `priority/important-soon` label, but thanks anyway for notifying.
I am working on workaround thought. It is useful in case if someone still wants to use Minikube from 1.9 to at least 1.11

**Comment by sunix** [comment]
@mmorhun why changing the severity?

**Comment by l0rd** [comment]
@mkuznyetsov @nickboldt please wait for a fix for this issue before releasing 7.15.0.

**Comment by mmorhun** [comment]
Fixed

**Comment by l0rd** [comment]
@flacatus @rhopp I was thinking about this and was wondering if we have any test for that. There were some e2e tests for chectl at some point, are they running? Aren't we testing minikube?

**Comment by sunix** [comment]
@l0rd I think it is tested with `-vm-driver=none` option (using the docker engine of the host)

**Comment by gattytto** [comment]
minikube defaults to docker driver which uses docker-machine and a premade .iso. 
minikube can also be run using driver=none and "--network-plugin=cni --enable-default-cni --container-runtime=cri-o" so it won't require docker and cri-o can be used, providing the cni binaries in /opt/cni/bin.
