### ISSUE TITLE
Installing package on eclipse che terminal

### ISSUE THREAD

**Issue by sushant30** [eclipse-che/che#17152]
## Summary
I want to install needful packages on my che terminal. Please let me know how can i achieve it.

**Comment by sleshchenko** [comment]
@sushant30 Do you mean installing something in runtime that requires sudo rights?
I think the answer here - prepare devfile with everything needed for you and then just use it. 
Typically K8s/OS infrastructures do not grant users sudo rights in containers.

Here https://github.com/che-dockerfiles  you can find some samples that we build.
Here are predefined devfiles we have https://github.com/eclipse/che-devfile-registry/tree/master/devfiles

**Comment by sushant30** [comment]
> @sushant30 Do you mean installing something in runtime that requires sudo rights?
> I think the answer here - prepare devfile with everything needed for you and then just use it.
> Typically K8s/OS infrastructures do not grant users sudo rights in containers.
> 
> Here https://github.com/che-dockerfiles you can find some samples that we build.
> Here are predefined devfiles we have https://github.com/eclipse/che-devfile-registry/tree/master/devfiles

Yes something like runtime installation with sudo rights. In case of using devfile i tried of installing jq using below devfile but i don't see it jq being installed. Am i doing something wrong. Please suggest.
`metadata:
  name: che-test
projects:
  - name: sushant-test
    source:
      location: 'https://github.com/sushant08/terraform.git'
      type: git
components:
  - id: redhat/project-initializer/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'docker.io/sushant08/terraform:aws'
    alias: awscli
apiVersion: 1.0.0
commands:
  - name: install dependencies
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/terraform'
        type: exec
        command: apt update && apt install jq -y
        component: awscli`

**Comment by sleshchenko** [comment]
@sushant30 Could you point a Dockerfile you use for 'docker.io/sushant08/terraform:aws'? Have you tried to install jq there?

**Comment by sushant30** [comment]
``

> @sushant30 Could you point a Dockerfile you use for 'docker.io/sushant08/terraform:aws'? Have you tried to install jq there?

No i haven't installed jq in docker image. I am trying to install using command part of devfile.

Dockerfile is as below:

`
FROM ubuntu

USER root

RUN apt update \
&& apt install wget -y \
&& apt install curl -y \
&& apt install zip -y \
&& mkdir ~/bin \
&& wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip \
&& unzip terraform_0.12.24_linux_amd64.zip \
&& mv terraform /usr/local/bin/ \
&& curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
&& unzip awscliv2.zip \
&& ./aws/install

CMD tail -f /dev/null 
`

**Comment by sleshchenko** [comment]
```
FROM ubuntu

USER root

RUN apt update \
&& apt install wget -y \
&& apt install curl -y \
&& apt install zip -y \
&& mkdir ~/bin \
&& wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip \
&& unzip terraform_0.12.24_linux_amd64.zip \
&& mv terraform /usr/local/bin/ \
&& curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
&& unzip awscliv2.zip \
&& ./aws/install

CMD tail -f /dev/null 
```
@sushant30 Don't you mind to install it? )
Please close the issue if it works for you.

**Comment by sushant30** [comment]
> ```
> FROM ubuntu
> 
> USER root
> 
> RUN apt update \
> && apt install wget -y \
> && apt install curl -y \
> && apt install jq -y \
> && apt install zip -y \
> && mkdir ~/bin \
> && wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip \
> && unzip terraform_0.12.24_linux_amd64.zip \
> && mv terraform /usr/local/bin/ \
> && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
> && unzip awscliv2.zip \
> && ./aws/install
> 
> CMD tail -f /dev/null 
> ```
> 
> @sushant30 Don't you mind to install it? )
> Please close the issue if it works for you.

I know that will work but i am trying to find a way to install packages without updating image everything. Can you let me know if that is achievable.

**Comment by tsmaeder** [comment]
@sushant30 OpenShift does not allow you to have root privileges in containers. This is not a limitation of Che itself, but of the underlying technology. So no, it's not going to work.
