### ISSUE TITLE
GWT superdevmode in Intellij - Error on running the run configuration - java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Connector

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#17157]
Configure Intellij to run superdevmode.
Run the run configuration
Result:

![image](https://user-images.githubusercontent.com/66947851/84647363-a2d74100-af03-11ea-9e13-5646bf6b3fc3.png)

**Comment by lisa9999** [comment]
Can anybody help please? What can I do to start my app with gtw superdev mode?
