### ISSUE TITLE
[Question] is Android stack now removed ?

### ISSUE THREAD

**Issue by Hax4us** [eclipse-che/che#17151]

**Comment by sleshchenko** [comment]
@Hax4us I suppose you mean Android VNC stack we had a long time ago.
I think it's not removed but not migrated. The actual list of pre-defined devfiles (aka stacks) are available in https://github.com/eclipse/che-devfile-registry/tree/master/devfiles
Welcome to contribute Android devfile, there seems to be VSCode extensions to that which hopefully is compatible with Theia as well https://marketplace.visualstudio.com/items?itemName=adelphes.android-dev-ext

@azatsarynnyy Do you happen to know if we have any guidelines for trying new extensions?

**Comment by Hax4us** [comment]
this https://hub.docker.com/r/eclipse/ubuntu_android/

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy Do you happen to know if we have any guidelines for trying new extensions?

This doc can help https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/
