### ISSUE TITLE
Happy path tests failed on "Run application" step because test application was unable to access spring-petclinic-2.3.0.BUILD_SNAPSHOT.jar

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17155]
### Describe the bug
E2E Happy path tests [are failing on "Run application" step](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1859/):
```
04:42:10     ✓ Build application (35474ms)
04:42:10           ▼ TopMenu.selectOption "Terminal"
04:42:10           ▼ TopMenu.clickOnTopMenuButton "Terminal"
04:42:10           ▼ Ide.closeAllNotifications
04:42:10           ▼ NotificationCenter.open
04:42:10           ▼ NotificationCenter.clickIconOnStatusBar
04:42:10           ▼ NotificationCenter.waitOpening
04:42:10           ▼ NotificationCenter.closeAll
04:42:10           ▼ NotificationCenter.clickCloseAllNotificationsButton
04:42:10           ▼ NotificationCenter.waitClearNotificationsList
04:42:10           ▼ TopMenu.clickOnSubmenuItem "Run Task..."
04:42:10           ▼ QuickOpenContainer.waitContainer
04:42:10           ▼ QuickOpenContainer.clickOnContainerItem "run"
04:42:10           ▼ QuickOpenContainer.waitContainer
04:42:10           ▼ QuickOpenContainer.waitContainerDisappearance
04:42:10           ▼ QuickOpenContainer.clickOnContainerItem "Continue without scanning the task output"
04:42:10           ▼ QuickOpenContainer.waitContainer
04:42:10           ▼ QuickOpenContainer.waitContainerDisappearance
04:42:10           ▼ Ide.waitNotificationAndConfirm "A new process is now listening on port 8080"
04:42:10           ▼ Ide.waitNotificationAndClickOnButton "A new process is now listening on port 8080" buttonText: "yes"
04:42:10           ▼ Ide.waitNotification "A new process is now listening on port 8080"
04:44:21     1) Run application
04:44:21 
04:44:21 
04:44:21   9 passing (8m)
04:44:21   1 pending
04:44:21   1 failing
04:44:21 
04:44:21   1) Validation of workspace build and run
04:44:21        Run application:
04:44:21      TimeoutError: Waiting for element to be located By(xpath, //div[@class='theia-notification-message']/span[contains(.,'A new process is now listening on port 8080')])
04:44:21 Wait timed out after 120002ms
```
![screenshot-Run_application (5)](https://user-images.githubusercontent.com/1197777/84634033-e927a280-aef9-11ea-927a-c30677bf7401.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1859/artifact/tests/e2e/report/output.mp4

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl/0.0.20200527-next.07f741a linux-x64 node-v10.20.1
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/17158
