### ISSUE TITLE
Dashboard does not expand 401 error from Che Server

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17154]
### Describe the bug
When dashboard gets 401 from Che Server is shows `[object Object]` error message while there is a browser log 
```
Can't GET "/api". Error:  
Object { status: 401, response: "{\"errors\":[{\"code\":\"unauthorized_error\",\"detail\":\"oauth2: cannot fetch token: 400 Bad Request\\nResponse: {\\\"error\\\":\\\"invalid_grant\\\",\\\"error_description\\\":\\\"Code not valid\\\"}\",\"status\":\"401\",\"title\":\"Unauthorized error\"}]}\n" }
app-852e1d423a.js:319781:17
    <anonymous> app-852e1d423a.js:319781
uncaught exception: Object
```

So, it would be much better to display the actual error message
```
oauth2: cannot fetch token: 400 Bad Request\\nResponse: {\\\"error\\\":\\\"invalid_grant\\\",\\\"error_description\\\":\\\"Code not valid\\\"}\",\"status\":\"401\",\"title\":\"Unauthorized error\"}]}
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Can't be reproduced stable, but there are issues when people face that on hosted-che. See
https://github.com/eclipse/che/issues/17153 
https://github.com/eclipse/che/issues/16719

**Comment by ibuziuk** [comment]
@sleshchenko could we also add some link for the login once this error occurs?

**Comment by sleshchenko** [comment]
@ibuziuk Not logged in users should be forwarded to login page, no?
Or do you mean link to logout and start log process from the beginning? Do we have such a link? Should it be configured in product.json?

**Comment by sunix** [comment]
Hello,
I am moving this issue to Blocker:
- We have many users in che.openshift.io who are giving up using Che before even reaching the IDE ....
- I could reproduce many time this WE and this morning ... :( a `shift + refresh` worked but not just refresh (in chrome + linux)
- I had many people having troubles this WE.

Here are some suggestions:
- Have a error message for the user describing the error and the origin and ask to try again (refresh? shift f5?)
    > we are experiencing some technical difficulties from our SSO: <detail coming from SSO error>. Please try Shift+Refresh.
- Consider an alternative SSO: eclipse foundation one?
- Maybe have an automatic retry.

**Comment by l0rd** [comment]
@sleshchenko can we have @olexii4 or @akurinnoy working on this issue this week?

**Comment by sleshchenko** [comment]
@l0rd @akurinnoy will handle that

**Comment by l0rd** [comment]
@sleshchenko cool thanks

**Comment by akurinnoy** [comment]
Hi @l0rd @sleshchenko @sunix 

For debug purpose I tried to to initialize Keycloak with empty `cliendId`. The text in red are `error` and `error_description` from Keycloak.

<img width="1154" alt="Screenshot 2020-06-30 at 15 51 05" src="https://user-images.githubusercontent.com/16220722/86128080-8d5c3c80-bae9-11ea-96db-3ab584265130.png">

**Comment by sunix** [comment]
super looks great to me

**Comment by akurinnoy** [comment]
preparing pull request!
