### ISSUE TITLE
Can't have multiple instances of Che container connected to same GitHub account

### ISSUE THREAD

**Issue by wallrick** [eclipse-che/che#1716]
When I try and run multiple instances of Che and connect it to the same GitHub account the "Connect Your GitHub Account" wizard flashes up but then immediately returns.  No errors shown. 

**Reproduction Steps:**
1. Run Che in a Docker container and connect it to GitHub using the "Connect Your GitHub Account" when creating a new Project.
2. Launch a second instance, create a new project and import from existing location, click the "Connect Your GitHub Account"
3. The wizard flashes up and immediately disappears and user is back at the New Project window with no git repositories and "Connect Your GitHub Account" still active.

**Expected behavior:**

I was expecting that I could have multiple instances of Che connected to the same GitHub account so that I can work with the latest Che release and also try out the Nightly builds.  

**Observed behavior:**

When an oAuth application for Che already exists in GitHub it appears Che doesn't know how to handle this behavior.

**Che version:**    [Enter Che version here]  
**OS and version:** Windows Docker HyperV  
**Docker version:**    1.12.0-rc3
**Che install:**   Windows Docker HyperV  

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Unsure
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ddementieva** [comment]
How do you run multiple instances? Can you share your docker run syntax?

**Comment by wallrick** [comment]
I run them like this,
**NIGHTLY BUILDS**
PS C:\Program Files\Docker\Kitematic-Windows> docker run --net=bridge --name=cheNightly --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/cheNightly/lib:/home/user/che/lib-copy -v /c/Users/rwall/cheNightly/workspaces:/home/user/che/workspaces -v /c/Users/rwall/cheNightly/storage:/home/user/che/storage -v /c/Users/rwall/cheNightly/confoverride:/home/user/che/confoverride -e DOCKER_MACHINE_HOST=172.17.0.1 -e CHE_LOCAL_CONF_DIR=/home/user/che/confoverride -e "DOCKER_HOST=tcp://10.0.75.2:2375" -p8002:8001 -p8082:8080 codenvy/che:nightly --remote:10.10.11.53

**Stable Builds**
PS C:\Program Files\Docker\Kitematic-Windows> docker run --net=bridge --name=che --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /c/Users/rwall/che/workspaces:/home/user/che/workspaces -v /c/Users/rwall/che/storage:/home/user/che/storage -v /c/Users/rwall/che/confoverride:/home/user/che/confoverride -e DOCKER_MACHINE_HOST=172.17.0.1 -e CHE_LOCAL_CONF_DIR=/home/user/che/confoverride -e "DOCKER_HOST=tcp://10.0.75.2:2375" -p8001:8001 -p8080:8080 codenvy/che --remote:10.10.11.53

**Comment by ddementieva** [comment]
@wallrick How did you configure oAuth for both Che instances? Did you create two applications on Github? What callback URLs did you use?

**Comment by wallrick** [comment]
So that was the issue.  I was mistakenly using the same oauth credentials for both instances.  I created a second oatuh credentials, with proper callback url and now it works as expected.  I am having other issues with the nightly build but that's another case.  Thanks for the help.

**Comment by ddementieva** [comment]
I'm closing this issue. Feel free to open a new one.
