### ISSUE TITLE
UI inconsistency in My Workspace display

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#17164]
### Is your enhancement related to a problem? Please describe.

In the *My Workspace* panel, the UI is not consistent and mixes capitalized text and all-lowercase text.

Example: 

![Screenshot from 2020-06-16 15-29-17](https://user-images.githubusercontent.com/243761/84780717-3123f380-afe6-11ea-9c4c-284fedd6f681.png)

### Describe the solution you'd like

Consistent UI. Same display rule for all items.

### Describe alternatives you've considered

Application UI sets: *User Runtimes* and *Plugins*.

Follow the same naming convention in a devfile?

It is not possible because visible entities are following different rules:

* `component` `alias`: lower case alphanumeric characters.
* `command` `name`: alphanumeric characters, spaces allowed.
* `endpoints` `name`: alphanumeric characters, no spaces allowed.

**Comment by sunix** [comment]
To me, this view is displaying different types of items. Having a label with first letter in uppercase and a container name with all lowercase is very fine.

**Comment by tsmaeder** [comment]
+1 on what @sunix says: the lowercase container names are user data not under programmatic control by che. For me this is not a bug.
