### ISSUE TITLE
Unable to start che nightly with chectl server:start with minikube/helm

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17169]
### Describe the bug
Starting minikube and then using chectl/next
```
$ chectl server:start --platform=minikube --installer=helm
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl/next

### Environment
   - [x] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS

### Eclipse Che Logs

```
$ kubectl logs -f pod/che-56646b7b6f-6nrxj -n che

Using embedded assembly.
Found a custom cert. Adding it to java trust store /home/user/cacerts based on /usr/local/openjdk-11/lib/security/cacerts
Trust this certificate? [no]:  Certificate was added to keystore
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
OpenJDK 64-Bit Server VM warning: Option MaxRAMFraction was deprecated in version 10.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by benoitf** [comment]
cc @skabashnyuk

**Comment by skabashnyuk** [comment]
Helm chart has been updated in this pr https://github.com/eclipse/che/pull/16649
@benoitf @tolusha  can you trigger the chectl build to use the latest version?

**Comment by benoitf** [comment]
Triggering a new build of chectl https://travis-ci.org/github/che-incubator/chectl/builds/699224837 as helm charts were updated

**Comment by tolusha** [comment]
@benoitf 
Can we close it?

**Comment by benoitf** [comment]
sure !
