### ISSUE TITLE
Align Get Started and Create Custom Workspace pages in propagating persistVolumes attribute

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#17170]
### Describe the bug
In settings had : 
```
{
...
"che.workspace.persist_volumes.default":"false"
...
}
```
This is means that default behavior should be "Ephemeral Mode" so not needed add any attributes to workspace config related to the storage type.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Go to the `Get Started`
2. Keep `Temporary Storage` turn on
3. Create workspace with any sample
4. No attribute should be added but got : 
```
attributes:
  persistVolumes: 'false'
```
If create workspace form custom workspace tab all work as expected.

### Expected behavior

No attribute should be added if create workspace in Ephemeral Mode

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
@vparfonov Just to clarify that workspace start there is no unexpected behavior and issue is only that attribute appears when it's not needed?

`che.workspace.persist_volumes.default` is not expected to be changed frequently on Che Server side but still, I wonder if it makes even more sense to always set `devfile.persistVolumes` explicitly to avoid unexpected data lose - when user created workspace with default `persistVolumes: true` and then default is changed to `persistVolumes: false`.
@skabashnyuk Do you think it would be better to set the value explicitly or omit if it's the same as default provided by Che Server?

**Comment by vparfonov** [comment]
@sleshchenko Yes workspace starts well, problem only in attribute. I worry because work on issue 
https://github.com/eclipse/che/issues/15960 and here my PR https://github.com/eclipse/che-dashboard/pull/58. During testing, I met this strange behavior and think we need to align behavior.

**Comment by sleshchenko** [comment]
I've found a bit more discussion here https://github.com/eclipse/che/pull/15713#discussion_r369090742

So, seems there is a bug on Create Custom Workspace Page but Get started page works as expected.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/17230 (UD changes for new storage type)
