### ISSUE TITLE
Should Che releases be GH releases (and thus update the 'latest release' metadata) ?

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17177]
### Describe the bug
on github repo page https://github.com/eclipse/che , the latest release is `Eclipse CHE 5.15.0`. I guess since then, we only do tags, but did not properly marked as a release on github.

### Che version
all of them

### Steps to reproduce
go to https://github.com/eclipse/che

### Expected behavior
latest release should be latest release

### Screenshots

![20200617_170226_1498x687_scrot](https://user-images.githubusercontent.com/1160903/84915211-cdb8c500-b0bc-11ea-89f2-e556ff1976f4.png)

**Comment by l0rd** [comment]
@sparkoo that makes sense but I am not able to see the `About` panel that you have in your screenshot. This is what I see:

![image](https://user-images.githubusercontent.com/606959/84961291-2f505200-b104-11ea-8041-926c89e5451f.png)

And if I click on releases:

![image](https://user-images.githubusercontent.com/606959/84961322-40995e80-b104-11ea-9cb0-e00421647eab.png)

**Comment by sparkoo** [comment]
Yes, I have some new beta github repo page, which you have to opt-in now. I guess we all get it sooner or later without option to opt-out.

Another issue with this is alias link to latest release `/releases/latest`, which may be used to some automation https://github.com/eclipse/che/releases/latest

**Comment by benoitf** [comment]
I manually created a more recent release but I guess the release script should do this automation
cc @mkuznyetsov @nickboldt

**Comment by nickboldt** [comment]
Renamed and added to current list of improvements to the Che release process so that @mkuznyetsov sees this and can comment on its usefulness. See https://github.com/eclipse/che/issues/17101

**Comment by nickboldt** [comment]
Do we need "actual releases" or are tags w/ source tarballs good enough for now?

![image](https://user-images.githubusercontent.com/227597/91560428-da049e00-e907-11ea-8c51-7242a00b5c72.png)

**Comment by nickboldt** [comment]
Are the current releases generated or manually created by @sparkoo  ? 

![image](https://user-images.githubusercontent.com/227597/107244309-e1be8780-69fb-11eb-8147-73a9fdeb6a4e.png)

Unclear what the value is of having a "release" vs. a "tag". @sparkoo can you explain if this is still something we need to do in Che release process?

**Comment by sparkoo** [comment]
@nickboldt yes, I'm doing those manually on very random basis. `/latest` is one feature. You can also watch for releases on the repo. Me personally I like to look at main repo page and see what's the latest version (see the screenshot in issue description https://github.com/eclipse/che/issues/17177#issue-640518929). I'd like to see it automated, but looks like I'm the only one...

**Comment by nickboldt** [comment]
what do you DO with those releases? is it for knowing when to update to newer Che ? 

Or just to know when release is done? If the latter, see https://github.com/eclipse/che/issues/17579 -- maybe you just want timely notifications of release status ?

**Comment by benoitf** [comment]
it should be a post-action of the release script

It's to tell the world that we've release a new version of Che (and include release notes)

**Comment by nickboldt** [comment]
include release notes?? I don't think we've been doing that for over a year. 

How will we generate release notes? will it be a raw dump of "all issues closed in this milestone" ? or a live query to "all issues closed for milestone ___" so that those not closed at the time of the release can be added into the notes when closed?

What about 7.yy.z releases? should those also have release notes and if so, how do we track/record what's fixed in those, as we don't use milestone field for .z releases? 

Release note generation is not in scope for this issue, as there are too many questions to answer first about how/what/how many involved in that. If you think the community would benefit from snapshots of issues lists taken at the time of release (vs. having live queries) then could you open a new issue for that?

**Comment by benoitf** [comment]
@nickboldt release notes is a separate issue. But generating github release is part of the release script (or the github action that creates the tag on che repository)

**Comment by sparkoo** [comment]
> what do you DO with those releases? is it for knowing when to update to newer Che ?
> 
> Or just to know when release is done? If the latter, see #17579 -- maybe you just want timely notifications of release status ?

I don't do anything with those releases. I personally use it mostly to take a quick look what's the latest Che released version. Github main repo is convenient place for it as I have it open all the time. I don't need any reporting or anything like that.

From outsider's perspective, I use releases in other projects on github very often. Just go to the project repo and see the latest version or see when some exact version was released. If there is an older version than latest, I would never know. If I'm interested in seeing newer releases, I can subscribe to releases only on github.

There is simple GH action to create a release from tag https://github.com/actions/create-release so we could just add it as a next step in the release action. If there is some big resistance to have releases on github, I would vote to remove all the releases, so it is clear we're not using them. But this half-way state is not good for anybody.

**Comment by nickboldt** [comment]
Well, if it was that simple... why not just contribute the fix?

https://github.com/eclipse/che/pull/19211

Voila!

**Comment by nickboldt** [comment]
I'm marking this done, even though the changelog we're now generating for releases has alots of dupe content.
