### ISSUE TITLE
No Changelog provided for Eclipse Che releases

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17178]
### Describe the bug
CHANGELOG.md ends with version 7.4.0 https://github.com/eclipse/che/blob/master/CHANGELOG.md

### Steps to reproduce
https://github.com/eclipse/che/blob/master/CHANGELOG.md

### Expected behavior
I would either:
 - properly update the changelog (this should be automated of course) with either
   - full commit list
   - links to github diff (e.g. https://github.com/eclipse/che/compare/7.14.2...7.14.3)
 - remove it completely or just single link to https://github.com/eclipse/che/compare

**Comment by nickboldt** [comment]
WIP to add changelog data to releases, eg., here:

* https://github.com/eclipse/che/releases/tag/7.27.0
* https://github.com/eclipse/che/releases/tag/7.27.1

However, the changelog generator is not firing automatically for 7.yy.* releases:

* https://github.com/eclipse/che/blob/master/.github/workflows/release-changelog.yml

And it contains WAY too much information -- needs to be higher level and with less duplication.

**Comment by nickboldt** [comment]
Much better output in latest 7.28.2 release:

![image](https://user-images.githubusercontent.com/227597/113930722-a5bb5f00-97bf-11eb-9a1b-038458a9c29d.png)

**Comment by nickboldt** [comment]
No complaints or feedback for 5 months! closing.
