### ISSUE TITLE
che-operator does not clean old ConsoleLink on changeName/update/uninstall

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17185]
### Describe the bug
ConsoleLink name is now in che-operator Deployment environment variable `CONSOLE_LINK_NAME`. When changing this value, the new ConsoleLink is created, but old one is not removed, so we end up with 2 ConsoleLinks.

:exclamation:  This will cause issue in next CRW release, where the hardcoded ConsoleLink name `che` will be renamed into `workspaces` https://github.com/redhat-developer/codeready-workspaces-operator/blob/master/deploy/operator.yaml#L69. So all CRW installations will get 2nd ConsoleLink. (cc: @tolusha @mmorhun @nickboldt )

Another effect of this cleanup issue is, that when we uninstall che (remove CheCluster CR), the ConsoleLink is still there, but not working.

### Che version
 - [x] latest

### Steps to reproduce
1. Install che with operator on OS4.2+
1. see there is 1 ConsoleLink `oc get ConsoleLinks`
1. change che-operator deployment env `CONSOLE_LINK_NAME` to something else
1. see there are now 2 ConsoleLinks `oc get ConsoleLinks`

### Expected behavior
old console link should be removed

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots

![20200618_121235_1486x305_scrot](https://user-images.githubusercontent.com/1160903/85009164-4885ec80-b15e-11ea-8701-a2136aa309e3.png)

### Installation method
   - [x] chectl
`chectl server:start --installer=operator --platform=crc`

### Environment
   - [x] my computer
       - [x] Linux

### Additional context
Issue discovered during analyzing this https://github.com/eclipse/che/issues/17159

**Comment by nickboldt** [comment]
What happens with `--installer=olm` ? The operator installer is deprecated in favour of the olm one for OCP 4.x (and CRC)

**Comment by nickboldt** [comment]
Also is there an easy way to run `oc ...` to patch/remove the old console link? If so we could at least add that to the Known Issues

**Comment by sparkoo** [comment]
> What happens with `--installer=olm` ? The operator installer is deprecated in favour of the olm one for OCP 4.x (and CRC)

I haven't tested that, but I assume the same behavior. Operator code is creating ConsoleLink.

> Also is there an easy way to run `oc ...` to patch/remove the old console link? If so we could at least add that to the Known Issues

yes, simply remove the old one with `oc delete consolelink che`

**Comment by tolusha** [comment]
@nickboldt @davidfestal 

Actually it is bad thing that we allow to modify console link name.
Once it is changed we can't find the previous one to update (maybe filtering by che host name).

I suggest:
1. Remove CONSOLE_LINK_NAME from env vars (not allow to modify)
2. Stick to template <che_flavor>-<namespace>

It allows to update display name if necessary. Also every Eclipse Che deployment will have its own console link.
User can update display name to distinguish one deployment from another one.

Implementation should take into account existed console links for the the same host name and delete them and create a new one.

**Comment by tolusha** [comment]
Closed in favor of https://github.com/eclipse/che/issues/18501
