### ISSUE TITLE
[operator] Metrics should be enabled by default during the Eclipse Che installation

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17186]
### Is your enhancement related to a problem? Please describe.
 Metrics should be enabled by default during the Eclipse Che installation: 

```
spec:
  metrics:
    enable: true
```

### Describe the solution you'd like
metrics exposure is enabled by default
 
### Describe alternatives you've considered
N/A

### Additional context
The list of metrics exposed in the Prometheus format - https://gist.github.com/ibuziuk/1859a134bb7575cecd7f7669100a14f4

**Comment by sparkoo** [comment]
@ibuziuk I'm not sure if it is related, but some time ago, we were analyzing option to install and setup full monitoring/tracing stack using che-operator. Unfortunately we've so far didn't get priority to actually implement it. Here's the epic with issues and implementation so you may take a look https://github.com/eclipse/che/issues/15046

**Comment by ibuziuk** [comment]
@sparkoo this issue is just about the fact that by default metrics should be exposed - https://github.com/eclipse/che-operator/pull/322

**Comment by sparkoo** [comment]
> @sparkoo this issue is just about the fact that by default metrics should be exposed - [eclipse/che-operator#322](https://github.com/eclipse/che-operator/pull/322)

ok, it will change a bit original idea of "install everything when global metrics.enable=true" https://github.com/eclipse/che/issues/15302 But it's a long time since this was analyzed, so I'm ok with that. It's only different default.

**Comment by ibuziuk** [comment]
correct, the goal is that if che is installed via operatorhub default CR would have:
`spec:
  metrics:
    enable: true`

**Comment by skabashnyuk** [comment]
@ibuziuk can you explain the motivational part of this issue? What is the point to expose additional port with additional components that nobody is using?

**Comment by ibuziuk** [comment]
the point is that for product we plan to enable OpenShift Cluster Monitoring by default and the very same config will be applied in upstream first

**Comment by skabashnyuk** [comment]
>the point is that for product we plan to enable OpenShift Cluster Monitoring by default and the very same config will be applied in upstream first

I'm sorry. Didn't get how that connected. In upstream in 99.9% of the time, it would be unused. I think it's a good practice to turn off non-critical parts so default installation is using as minimal as possible resources. Is there any problem to enable it in CR when it is used with `OpenShift Cluster Monitoring`?

**Comment by ibuziuk** [comment]
I will let @l0rd comment ^  but the idea is the unification of the configuration between project and product

**Comment by ibuziuk** [comment]
PR merged. Closing
metrics are going to be enabled by default in 7.16.0

**Comment by ibuziuk** [comment]
Docs PR https://github.com/eclipse/che-docs/pull/1366
