### ISSUE TITLE
In OpenShift 4, add a *Self-Signed Certificate* switch next to *TLS Mode* switch

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#17199]
As a user, I would expect that when enabling *TLS Mode*, no additional action is required.

However, depending on the certificates provisionned in the OpenShift instance, it may be necessary to enable the `selfSignedCert` option.

We can probably assume that any first time user will be using a self-signed certificate.

In current state, it requires editing the `CheCluster` CustomResource. 

Editing this CustomResource can probably be considered as an advanced usage of the application, as opposed to clicking on a switch button in OpenShift UI.

In that context, I believe that it would be a great improvement for the user experience to have a *Self-Signed Certificate* switch next to the *TLS Mode* switch.

(As a dreamer, I would even like the *TLS Mode* switch discover this for me.)

**Comment by themr0c** [comment]
I would even expect the Operator to propose me to download the `ca.crt` that will be used to generate the self-signed certificate, as it will be necessary to go further.

**Comment by tolusha** [comment]
@themr0c 
We have recently closed  the issue [1] where `selfSignedCert` field is set automatically. 

[1] https://github.com/eclipse/che/issues/16764

I am not sure if I understood the second statement

> I would even expect the Operator to propose me to download the ca.crt that will be used to generate the self-signed certificate, as it will be necessary to go further.

**Comment by tolusha** [comment]
Since `selfSignedCert` is deprecated and is autodiscoverable I mark this issue as resolved.
