### ISSUE TITLE
Raw link for extensions in meta.yaml spec

### ISSUE THREAD

**Issue by sainirijul** [eclipse-che/che#17197]
### Describe the bug
To add a vs code extension using the workspace configuration, I link the component in my devfile to meta.yaml file hosted on GitHub using the dedicated reference field. In mera.yaml file, I use the raw link for vsix file. After launching the workspace, the vs code extension is not added in the workspace.  

### Che version
 - latest

### Steps to reproduce
1. Create meta.yaml file
2. Add the raw link of vsix file under spec/extensions
3. Use this meta.yaml link in reference field in your workspace devfile
4. Open the workspace
5. Check for the extension.

### Expected behavior
When you restart the workspace, the vs code extension and its associated commands should show up.

### Runtime
   - minikube

<img src="https://user-images.githubusercontent.com/32622151/85137786-bb02d500-b20f-11ea-83b6-108c58502605.png">

<img src="https://user-images.githubusercontent.com/32622151/85137735-a9213200-b20f-11ea-9d6c-764b42cd333c.png">

### Installation method
   - chectl

### Environment
   - my computer
       - Linux

### Workaround
I discovered that when using ?raw=true notation in meta.yaml file, it does not work. However, if we remove ?raw=true notation then it works. For example, I changed the below link
https://github.com/Rijul5/vscode-teletype-guest/blob/master/vscode-teletype-0.0.1.vsix?raw=true
TO
https://github.com/che-incubator/vscode-teletype-guest/raw/master/vscode-teletype-0.0.1.vsix
and then the vs code extension started working in the workspace.

**Comment by tsmaeder** [comment]
I wouldn't really classify this as a bug: it's just that the code reading the vsix is not handling the http 302 code redirect.

**Comment by skabashnyuk** [comment]
@Rijul5 can you please provide examples of devfile and meta.yam?

**Comment by Rijul5** [comment]
> @Rijul5 can you please provide examples of devfile and meta.yam?

@skabashnyuk - Please find below the link for meta.yaml file
https://github.com/Rijul5/che-plugin-registry/blob/master/v3/plugins/ms-vscode/vscode-teletype/0.1.0/meta.yaml

Also, there is no specific devfile which I am using. I can give you a simple example of devfile where I am using the above meta.yaml file.

metadata:
  name: vscode-teletype
components:
  - id: eclipse/che-theia/next
    type: cheEditor
    alias: che-theia
  - type: chePlugin
    reference: https://raw.githubusercontent.com/Rijul5/che-plugin-registry/master/v3/plugins/ms-vscode/vscode-teletype/0.1.0/meta.yaml
apiVersion: 1.0.0

**Comment by ericwill** [comment]
> I wouldn't really classify this as a bug: it's just that the code reading the vsix is not handling the http 302 code redirect.

Agreed, the link should be direct.
