### ISSUE TITLE
[Q] Exposed ports in Dockerfile

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#1719]
Regarding to [Configuration: Networking](https://eclipse-che.readme.io/docs/networking), it looks that Che Docker Container requires port 8080 only.
But in [Dockerfile](https://hub.docker.com/r/codenvy/che/~/dockerfile/), more ports are exposed.
The official Docker image has additional services? What is "runners"?

```
# expose 8080 port and a range of ports for runners
EXPOSE 8080 8000 49152-49162
```

**Comment by TylerJewell** [comment]
Dockerhub has some issues right now and the actual dockerfile for the Che server is not the one that you see on their site.  It is challenging to update it.   For the actual dockerfile please the dockerfile in our github repo located at github.com/eclipse/che.

While the Che server only exposes a single port (well another for the debug of the Che server) keep in mind that Che launches each workspace as its own separate container and those workspace containers require more ports to be open.

**Comment by monaka** [comment]
I see. The dockerfile on Dockerhub is obsolete now. (but automated builds are working well, right?)
And thank you for noticing about workspace-ip. I close this issue.
