### ISSUE TITLE
[UX] [chectl] add -y flags to skip "are you sure?" prompts

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17192]
### Is your enhancement related to a problem? Please describe.

Rather than `--multi-word-long-flags`, which are the antithesis of UX and speed, we should provide `-y` flags to skip over "Are you sure?" checks like the one that's raised for `chectl server:delete`.

```
You're going to remove CodeReady Workspaces server in namespace 'nboldt-minioso' on server 'https://api.ocp45.crw-qe.com:6443'. If you want to continue - press Y: y
```

I mean it's great to have a long flag spelled out when you're writing scripts that you want to be well documented, but when I just want to delete something, less typing is better.

Thus in script:

```
chectl server:delete --skip-deletion-check --chenamespace=myproject
```

But as a user:

```
chectl server:delete -y -n myproject
```

### Describe the solution you'd like

Add `-y` flags to chectl operations that prompt for user input.

### Describe alternatives you've considered

Learning to type faster and more accurately, and also memorizing arcane options. :D

**Comment by nickboldt** [comment]
Also, this might be a small issue but in terms of accessibility, asking for an uppercase Y and then accepting a lowercase one is just inaccurate. If you don't need to force people to hit shift, then don't ask for the uppercase.

**Comment by tolusha** [comment]
Add '-y/--yes` flag for `server:delete` and `server:update` tasks
