### ISSUE TITLE
Please describe how to add use Che with self-signed certificates on Firefox

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#17198]
Please describe how to add use Che with self-signed certificates on Firefox.

Current documentation is containing explanations for Google Chrome only:
https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-che-with-tls_installing-che-in-tls-mode-with-self-signed-certificates

**Comment by l0rd** [comment]
@themr0c I think that can be closed now
