### ISSUE TITLE
Can't create maven command with the name "newMaven"

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#172]
It's a strange issue, when the name if "newMaven", it can't be created. The "Save" button is disabled.

![maven](https://cdn.pbrd.co/images/FjNbUXV.png)

There is no other existing task has the same name.

PS: Base on the commit `9e4369517e4308593fce0895d4700e77ecba12f8`

**Comment by TylerJewell** [comment]
Any chance you created a task of that name before, deleted it, and now trying to create it again?  Like it is remembering a ghost?

**Comment by freewind** [comment]
This che is started in a new docker container and everything is new (no volume mapping).

Just log it and see if I will come across more

**Comment by ghost** [comment]
Are you using the latest version? What if you delete newMaven22 copy?

**Comment by freewind** [comment]
@eivantsov Yes, the latest source code by the day I posted the issue. I will try to resolve it myself later if I see the same problem.

**Comment by ddementieva** [comment]
It's an expected behavior. The command is actually created, you can find it in the list with a default newMaven name. Save button is activated after changing the name or the command itself.
