### ISSUE TITLE
DASHBOARD: workspace settings: plugins list out of window scope

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17204]
I have to zoom out to 67% to see the bottom of the list, the main window does not have a scrollbar
![image](https://user-images.githubusercontent.com/407397/85234557-78462600-b3e4-11ea-8add-d4a703904f3d.png)

this is the list fully scrolled down, I don't see the latest item of it:
![image](https://user-images.githubusercontent.com/407397/85234574-9dd32f80-b3e4-11ea-9098-c34ae89b430e.png)

then I have to zoom out to 6x% to see all of it:
![image](https://user-images.githubusercontent.com/407397/85234655-44b7cb80-b3e5-11ea-8b4e-36d1d59f5cba.png)

**Comment by ibuziuk** [comment]
@olexii4 FYI
@gattytto could you please add the browser info?

**Comment by gattytto** [comment]
> @olexii4 FYI
> @gattytto could you please add the browser info?

brave browser both osx and win10, and chrome win10

**Comment by sleshchenko** [comment]
7.26 will have new React Based Dashboard which does not have the described UI at all
