### ISSUE TITLE
Go 1.11 modules support

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17208]
### Is your task related to a problem? Please describe.
Today, when using che workspaces, we're missing some intellisense like code completion when editing go projects using go modules. They're workarounds, like adding the cloned project to the current workspace.

### Describe the solution you'd like
It should work out of the box.
When we open such workspaces, code completion should work by having a workspace-root associated to the cloned directory of the project

Besides, as we're moving to multiple workspace roots, projects should directory be opened like that

- [ ] : update go plug-in https://github.com/eclipse/che/issues/17665

**Comment by gattytto** [comment]
there's another workaround needed for private repos:
in /theia/.gitconfig
````bash
[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
````

**Comment by ericwill** [comment]
cc @svor is there anything left to do here?

**Comment by svor** [comment]
@ericwill  go plug-in is already outdated: we have 0.16.1 but the latest is [0.22.1](https://github.com/golang/vscode-go/releases/tag/v0.22.1). It would be nice to update che-plugin and test the functionality described in the description again.

**Comment by gattytto** [comment]
current go in che supports go mods using gopls, so this one should be closed

**Comment by ericwill** [comment]
> current go in che supports go mods using gopls, so this one should be closed

Seems we only need to update the plugin then, which will be handled in #19154
