### ISSUE TITLE
[devworkspace] Airgap mode for web-terminal

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17201]
### Is your enhancement related to a problem? Please describe.
Since we have limited numbers of containers we should consider implementing Airgap mode for web-terminal which means replacing tags with docker images digests and then propagating them to operator CSV files.

**Comment by gorkem** [comment]
How about testing for it?

**Comment by rhopp** [comment]
If it's about "one time" verification of functionality/fixes, we can help controller team with installing their own disconnected cluster on AWS.
If it's about automated periodic/regression testing, then I can just say it's on the roadmap, but without any due date right now. (in general I would like us to move from long-running clusters to pipelines of "create OCP -> run tests -> tear down OCP" - both for connected and disconnected clusters).

**Comment by gorkem** [comment]
@rhopp Can you forward me where this item about automated test is recorded and followed?
