### ISSUE TITLE
Use che's deployed registry for che needed images

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#17215]
When installing Che on Kubernetes, the deployment comes with plugin-registry which gives an advantage of ability to have `che`'s required images to be automatically pulled by this registry and stored in this registry.

This can give a strong advantage to not be impacted or affected by when the services are down in Quay.io: https://status.quay.io/
Such plugins like this:
![image](https://user-images.githubusercontent.com/11182824/85399182-bafd2f00-b599-11ea-82f9-f845a43e3988.png)
```
Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0"
Failed to pull image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0": failed to resolve reference "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0": failed to do request: Head https://quay.io/v2/eclipse/che-plugin-metadata-broker/manifests/v3.2.0: EOF
Error: Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'Failed', 'Failed to pull image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0": failed to resolve reference "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0": failed to do request: Head https://quay.io/v2/eclipse/che-plugin-metadata-broker/manifests/v3.2.0: EOF', 'workspacejswym3fm78hni1pr.che-plugin-broker'"
```
And this:
```
Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.14.3"
Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.14.3"
Created container remote-runtime-injector5dw
Started container remote-runtime-injector5dw
Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0"
Failed to pull image "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0": failed to resolve reference "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0": unexpected status code [manifests v3.2.0]: 502 Bad Gateway
Error: ErrImagePull
Error: Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0": failed to resolve reference "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0": unexpected status code [manifests v3.2.0]: 502 Bad Gateway', 'workspacejswym3fm78hni1pr.workspace-79f9dddc6b-6d5sl'"
```

Could've been better pulled by the private registry deployed by che, right?

**Comment by sparkoo** [comment]
looks like big feature possibly affecting multiple teams. I've marked it as epic with p2 severity as it does not affect usability on normal (quay.io working) situation.

**Comment by ibuziuk** [comment]
@sparkoo I believe the main point here is that Eclipse Che is highly dependable on the image registry and we do need to come up with a solution for making it more loosely coupled e.g. 
 - switch between image registries via toggle / env var
 - mirror all our dependencies to the internal registry and use a mutating webhook 
 -  switch via toggle / env var to  airgap approach or smth. else

**Comment by l0rd** [comment]
I think there is some confusion: this issue description is talking about using the plugin registry but that's not a container registry!

Anyway there are ongoing efforts to run [Che on clusters with restricted network (airgap) on OpenShift](https://github.com/eclipse/che/issues/15350) and to [run Che offline](https://github.com/eclipse/che/issues/14699). I don't believe that this issue will be addressed by those features but at least there are some options not to depend on quay.io.
