### ISSUE TITLE
[che-release] Latest 7.y.z OLM files not present in master

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17210]
Not sure if this is intentional, but for the 7.14.3 release, I see the OLM bits in 7.14.x branch:

![image](https://user-images.githubusercontent.com/227597/85331099-7f803900-b4a3-11ea-90f6-63912b52ea33.png)

https://github.com/eclipse/che-operator/tree/7.14.x/olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/7.14.3

But not in master:

https://github.com/eclipse/che-operator/tree/master/olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift

**Comment by sparkoo** [comment]
@nickboldt what are consequences of this? Does it break deploy?

**Comment by nickboldt** [comment]
I honestly don't know. Question for @mkuznyetsov and the deploy team... @tolusha @mmorhun etc

**Comment by mkuznyetsov** [comment]
OLM files were not pushed to quay application, and PR wasn't merged to master (as well as no community operator PRs created for that release) because of some concerns with reg
It was noted in the Che 7.14.3 closing comment too 
https://github.com/eclipse/che/issues/17143#issuecomment-646594445

**Comment by l0rd** [comment]
@mkuznyetsov @tolusha can we close this issue then?
