### ISSUE TITLE
Add VS Code Didact extension in registry

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#17211]
### Additional context

now that required commands have been implemented https://github.com/eclipse/che/issues/16940 , it should work. See https://github.com/eclipse/che-plugin-registry/pull/459 for initial draft

**Comment by bfitzpat** [comment]
Updated  https://github.com/eclipse/che-plugin-registry/pull/459

**Comment by ericwill** [comment]
This has been fixed in eclipse/che-plugin-registry#459
