### ISSUE TITLE
Documentation technical review

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17226]
### Is your task related to a problem? Please describe.

We need to review Admin Guide and End-User Guide
and make sure it's up to date.

## Admin Guide
2. Retrieving CodeReady Workspaces logs
2.1. Accessing OpenShift events on OpenShift
2.2. Viewing CodeReady Workspaces server logs
2.3. Viewing external service logs
2.4. Viewing CodeReady Workspaces workspaces logs

3. Monitoring CodeReady Workspaces
3.1. Enabling and exposing CodeReady Workspaces metrics
3.2. Collecting CodeReady Workspaces metrics with Prometheus
3.3. Extending CodeReady Workspaces monitoring metrics
4. Tracing CodeReady Workspaces
4.1. Tracing API
4.2. Tracing back end
4.3. Installing the Jaeger tracing tool
4.4. Enabling CodeReady Workspaces metrics collections
4.5. Viewing CodeReady Workspaces traces in Jaeger UI
4.6. CodeReady Workspaces tracing codebase overview and extension guide

5. Managing users
5.1. Configuring authorization
5.3. Removing user data
6. Securing CodeReady Workspaces
6.1. Authenticating users
6.2. Authorizing users
		

## End-User Guide

3. Workspaces overview
3.1. Configuring a workspace using a devfile
3.2. Making a workspace portable using a devfile
3.3. Converting a CodeReady Workspaces 2.1 workspace to a CodeReady Workspaces 2.2 devfile
3.4. Creating and configuring a new CodeReady Workspaces 2.2 workspace
3.5. Importing a OpenShift application into a workspace
3.6. Remotely accessing workspaces
3.7. Creating a workspace from code sample
3.8. Creating a workspace by importing the source code of a project
3.9. Configuring workspace exposure strategies
3.10. Mounting a secret as a file or an environment variable into a workspace container

**Comment by AndrienkoAleksandr** [comment]
P1, because related to CodeReady

**Comment by sparkoo** [comment]
@AndrienkoAleksandr relation to downstream product should not matter when setting severity of upstream Che issue. IMHO this issue does not belong here and it should be tracked in CodeReady Workspaces issue tracker.
