### ISSUE TITLE
[devworkspace-operator] Need to find location for che-rest-apis image

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17225]
### Is your task related to a problem? Please describe.
I'm currently maintaining the che-rest-apis image manually (see https://github.com/eclipse/che/issues/16636). We need to decide  what we're going to do about this image for the release of the web terminal operator.

If we remove it from the configmap, the controller will function as normal but will fail to start any workspaces that require che-rest-apis (anything Theia-based). This could be an issue as we move forward with integrating the controller with Che.

**Comment by l0rd** [comment]
Apologies to use this issue to ask a question that may be out of scope here but is the idea to transform the che-rest-apis into a real API that will replace the workspace-wsmaster communications? cc @davidfestal @sleshchenko

**Comment by sleshchenko** [comment]
This topic needs better investigation... Are we making Che Operator depending on DevWorkspace Operator but not vise versa, right? If yes - do we want DevWorkspace operator runs Theia based workspaces without Che installed?

**Comment by l0rd** [comment]
Yes Che wsmaster will depend on DevWorkspace operator and no we do not want DevWorkspace to depend on Che. Hence the DevWorkspace operator should be able to start a Theia based workspace yes without Che. That's not top priority but we should consider this.

**Comment by amisevsk** [comment]
> is the idea to transform the che-rest-apis into a real API that will replace the workspace-wsmaster communications?

@l0rd the che-rest-apis container is currently required for providing the devfile and additional configuration to che-theia at runtime, and it just implements a few Che APIs. Once we invest more heavily into reusing the DevWorkspace Operator for managing workspace k8s resources, I could see it being unnecessary, but it's required as long as we're using the current iteration of che-theia. In short, it depends on how the re-use of the devworkspace-operator is designed.

One way to avoid its need would be to enable che-theia to read the required configuration from a file; that's all the current che-rest-apis does.

**Comment by l0rd** [comment]
@amisevsk makes sense.

**Comment by amisevsk** [comment]
We left this issue for long enough that it's not needed anymore -- the current plan is to remove che-rest-apis in the near future.
