### ISSUE TITLE
Export Che Workspace definition to Devfile from Che Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17239]
### Is your enhancement related to a problem? Please describe.
It should be possible to export Che Workspace definition to Devfile from Che Theia.

### Describe the solution you'd like
`File - Save Workspace As...` command should propose to export Che Workspace definition to Devfile to save it in one of the project root folders.
The existing `File - Save Workspace As...` command should be renamed to `File - Save Workspace Roots As...`.

### Additional context
https://github.com/eclipse/che/issues/17106

**Comment by pdaverh** [comment]
Is this similar to https://github.com/eclipse/che/issues/16262?

**Comment by azatsarynnyy** [comment]
https://github.com/eclipse/che/issues/16262 is more about Factory functionality. That should be handled by https://github.com/eclipse/che/issues/16875
With this one, the user should be able to quickly get a Workspace Devfile content in Che Theia without going to Dashboard.
Devfile can be opened in an editor with an option to save it to a file within one of the project's sources.

**Comment by azatsarynnyy** [comment]
closed by https://github.com/eclipse/che-theia/pull/839
