### ISSUE TITLE
Consider deprecating CloudShell editor

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17234]
### Is your task related to a problem? Please describe.
Initially, CloudShell was supposed to be used for WebTerminal embedded to OpenShift Console. But at this time we know that it's not possible to reuse CloudShell there and OpenShift Console has its own front-end that communicates with machine-exec backend.

### Describe the solution you'd like
It's needed to decide the future of https://github.com/eclipse/che-machine-exec/tree/master/cloud-shell front-end.
Can it find it's usage in Eclipse Che scope? 
If yes - what are user stories? Should we create devfile in devfile registry for that workspace? 
If no - then probably we just need to remove it. BTW it's always will be in our memory and VCS let us restore it whenever we find a use-case for that.

**Comment by nickboldt** [comment]
Given cloudshell (or clouds-hell) has already been removed in June 2020, not sure we need to worry about deprecating it 10 months later.

**Comment by nickboldt** [comment]
But looks like I spoke too soon...

Merged: https://github.com/eclipse-che/che-plugin-registry/pull/507

But still exists: https://github.com/eclipse/che-machine-exec/tree/master/cloud-shell front-end.
