### ISSUE TITLE
Finalize Storage Type switcher

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17230]
### Is your task related to a problem? Please describe.
There is a PR for initial implementation for storage switcher https://github.com/eclipse/che-dashboard/pull/58
Thank Vitaliy for providing it :+1: 

**Get Started:**
![Screenshot_20200624_122413](https://user-images.githubusercontent.com/5887312/85530678-cb072400-b616-11ea-989e-6af8c7938583.png)
- Missing Storage Type title

**Create Custom Workspace**
![Screenshot_20200624_122635](https://user-images.githubusercontent.com/5887312/85530853-eeca6a00-b616-11ea-88a2-7e26bc3a1a03.png)

**Workspace Details:**
![Screenshot_20200624_122707](https://user-images.githubusercontent.com/5887312/85531049-1588a080-b617-11ea-94ce-0b4450f959f3.png)
- Dropdown has different style as for other pages.

The detailed info about storage types should be reworked. Possible solutions could be:
- to use tooltip on question icon and show there description of all available descriptions for storage type (this may make the tooltip a bit cumbersome):
  <img width="154" alt="Screenshot 2020-06-24 at 15 37 26" src="https://user-images.githubusercontent.com/16220722/85557743-bafc3e00-b630-11ea-9e7f-808fe118fa6c.png">
- to have a link-button that opens pop-up or modal window with storage type descriptions:
  <img width="409" alt="Screenshot 2020-06-24 at 15 49 30" src="https://user-images.githubusercontent.com/16220722/85559642-91441680-b632-11ea-9d11-e106d84d494b.png">

Also, it's needed to align persistent storage-related devfile attributes. Different pages must: remove persistent storage-related attributes if Persisted is configured. If any other is configured - attributes must be set. More https://github.com/eclipse/che/issues/17170

**Comment by vparfonov** [comment]
@sleshchenko 
UPD: 
This feature should be enabled only for `common` strategy.
