### ISSUE TITLE
As the admin, I would like to have a possibility to setup a maximum time for the running workspaces 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17231]
### Is your task related to a problem? Please describe.
Currently, we have a possibility to idle workspaces after a certain period of inactivity - https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties#L36-L41

```
# The length of time that a user is idle with their workspace when the system will
# suspend the workspace and then stopping it. Idleness is the
# length of time that the user has not interacted with the workspace, meaning that
# one of our agents has not received interaction. Leaving a browser window open
# counts toward idleness.
che.limits.workspace.idle.timeout=1800000
```
As the admin, I would also like to have a possibility to setup a maximum time for the running workspaces. e.g. `che.limits.workspace.idle.hard.timeout`

### Describe the solution you'd like
Adding a property for the hard timeout e.g. `che.limits.workspace.idle.hard.timeout`
```
# The maximum length of time for a running workspace before the system will suspend and stop it.
che.limits.workspace.idle.hard.timeout=3h`

```
Could be unlimited (set to 0) by default

### Describe alternatives you've considered
N/A

### Additional context
Potentially we could enable it on Hosted Che and update the terms of service - https://www.eclipse.org/che/docs/che-7/hosted-che/#terms-of-service_hosted-che

**Comment by sleshchenko** [comment]
@ibuziuk Do I understand correctly that `idle.hard.timeout`  is supposed to stop workspace even if it's not idling (is in actively using)? If yes - what about naming like `che.limits.workspace.run.timeout` ( we already have `che.limits.user.workspaces.run.count`)

**Comment by ibuziuk** [comment]
@sleshchenko property naming was never an easy thingy, but yes the idea is that if after n hours workspace is running even if the checker detects activity - workspace will be idled inany case

**Comment by ibuziuk** [comment]
@tomgeorge based on Sergey's comment I believe the better property name will be - `che.limits.workspace.run.timeout`

**Comment by ibuziuk** [comment]
PR merged. Closing
