### ISSUE TITLE
Che Theia build is failed

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17235]
### Describe the bug
Che Theia build is failed within the [release job](https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-release/30/console) with the following error:
```
...
Step 11/45 : RUN cd /root && tar zcf /root/theia-source-code.tgz theia-source-code
 ---> Running in cb20b3033417
tar: theia-source-code: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
The command '/bin/sh -c cd /root && tar zcf /root/theia-source-code.tgz theia-source-code' returned a non-zero code: 2

```

**Comment by nickboldt** [comment]
Sounds like this blocks the 7.15 release today (awesome finding a build blocker on release day) :( so I've set the milestone to 7.15.
