### ISSUE TITLE
Wildcard DNS and mandatory DNS entries

### ISSUE THREAD

**Issue by adriendelsalle** [eclipse-che/che#17244]
Hi, thanks again for Che!

I'm deploying Che on a company network with strict rules about DNS entries. DNS wildcards are forbidden.

Given that, I would like to know : 
- Is the multi user mode requiring a wildcard to work (dynamic routes created for each user user-che.foo.bar?) ?
- what are the mandatory DNS entries to run Che in both single and multi user modes. I think about che-che, keycloak-che, but I didn't found in the docs (or missed) a full description about that.

I was also surprised that Che install fails on k8s without a correct domain due to bad requests between che and keycloak. Why such requests are not using cluster internal DNS instead? Is it only for liveness/readiness probes? I would have only expected fails trying to connect che server or keycloak from my browser.

It would be my pleasure to write a proc in che-docs repo based on your responses!

Thanks

**Comment by sleshchenko** [comment]
@metlos @sparkoo I think you're best people to take a look at that.

**Comment by l0rd** [comment]
> Is the multi user mode requiring a wildcard to work (dynamic routes created for each user user-che.foo.bar?) ?

If you are using Kubernetes default ingress (nginx) you can avoid wild cards and have single-host urls if you configure Che to use the [single-host exposure strategy](https://www.eclipse.org/che/docs/che-7/configuring-workspace-exposure-strategies/#single-host-strategy). If you are deploying on Kubernetes cluster with an ingress controller that doesn't support path rewrite (OpenShift) you currently cannot use single-host URLs. 

For your information we are we are working on removing this requirement at all through https://github.com/eclipse/che/issues/12914 and making single-host exposure the default.

> what are the mandatory DNS entries to run Che in both single and multi user modes. I think about che-che, keycloak-che, but I didn't found in the docs (or missed) a full description about that.

I am not sure I understand your question: if your Che URL is `che-che-server.my.domain.com` you should only care about `my.domain.com` from a DNS point of view and the Kubernetes gateway should take care of the rest.

> I was also surprised that Che install fails on k8s without a correct domain due to bad requests between che and keycloak. Why such requests are not using cluster internal DNS instead? Is it only for liveness/readiness probes? I would have only expected fails trying to connect che server or keycloak from my browser.

This looks like an improvement. But the current behavior must be related to the fact that we support using a pre-existing instance of Keycloak (that we do not control) and thus requiring an external URL. Nonetheless, in the case we are deploying and managing keycloak, it make sense to use the kubernetes internal URL instead. Feel free to create an issue about that @adriendelsalle

**Comment by adriendelsalle** [comment]
Hi @l0rd, thank's for this response!

I'm a beginner on that topic, my questions/answers will perhaps be naive:
> I am not sure I understand your question: if your Che URL is `che-che-server.my.domain.com` you should only care about `my.domain.com` from a DNS point of view and the Kubernetes gateway should take care of the rest.

I'm not able to add a wildcard DNS entry `*.my.domain.com` so I have to add namely each entry. What I understand is:
- using `multi-host` strategy, I will be only able to connect keycloak or Che server UI that way by adding DNS entries such as `che-che.my.domain.com`, `keycloak-che.my.domain.com` and maybe others (for postgres?) pointing on the same endpoint
    - It will hopefully solve the Che server creation currently stuck when trying to connect Keycloak with external URL
    - But I won't be able to reach any workspace since routes are dynamically created/added using a new subdomain
    - It's definetely not a solution for my case
- using `single-host` strategy, I will use path rewrite instead of subdomains for routing (+dynamically added routes in ingress in both cases)
    - It will be a good wordaround for my case
    - I will encounter some limitations well described in the documentation for app exposure etc.

> This looks like an improvement. But the current behavior must be related to the fact that we support using a pre-existing instance of Keycloak (that we do not control) and thus requiring an external URL. Nonetheless, in the case we are deploying and managing keycloak, it make sense to use the kubernetes internal URL instead. Feel free to create an issue about that @adriendelsalle

I better understand why it works that way thanks!
It seems that when th Keycloak instance is running on the same k8s or openshift cluster, we could/should use internal URL while the use of an external URL is reserved for external (to the cluster) Keycloak instances.
Does it extends to external postgres database? I will definetely open another issue labelled  as improvement.

Thanks!

**Comment by adriendelsalle** [comment]
Hi @l0rd , could you please give me some advice before closing? Thanks!

**Comment by metlos** [comment]
Note that https://github.com/eclipse/che/issues/12914 has been now implemented.
