### ISSUE TITLE
Impossible to get workspace list with machine token

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#17246]
### Describe the bug
Due to filtering restrictions for some REST service methods it is impossible to retrieve workspace list using workspace-client library with machine token.

Workspace service is configured for blocking some requests that comes with machine token: [getByKey](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L307-L328) and [getWorkspaces](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L341-L362) and the following filter: https://github.com/eclipse/che/blob/master/multiuser/machine-auth/che-multiuser-machine-authentication/src/main/java/org/eclipse/che/multiuser/machine/authentication/server/MachineAuthModule.java#L55-L56

[che-workspace-client](https://github.com/eclipse/che-workspace-client) library's [methods](https://github.com/eclipse/che-workspace-client/blob/master/src/rest/remote-api.ts#L74-L75) require **user token**, not machine. And on the other hand, che-theia doesn't have fully functional mechanism, which allow developer obtain user token without any workaround. So by obtaining user token means communication with keycloak authorization mechanism. Theia editor locates in iframe and there is only way to get user token is to make some "bridge" between Theia and parent inframe (Dashboard). This is the first way which can be made as a workaround, discussed with Platform Team. As for the second workaround, we may update filters by removing those two methods from filtering (`getByKey` and `getWorkspaces`), but this is not convenient, because it breaks the conception of workspace sharing. cc @skabashnyuk 

In terms of Che-Theia (editor as a subject) there should be some API, which allow developer to get user token like it has been done for machine token to allow make such requests.

On the other hand, it requires modification API in [che-workspace-client](https://github.com/eclipse/che-workspace-client) which will allow pass user token as parameter for such type of call.

Dependent issue: https://github.com/eclipse/che/issues/17034

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
<img width="486" alt="Eclipse Che hosted by Red Hat | workspacel7dkn 2020-06-25 11-42-59" src="https://user-images.githubusercontent.com/1968177/85686945-141fac80-b6d9-11ea-8c1e-8c1c70b59e07.png">

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
it's not a bug. It's by design. use keycalok token instead

**Comment by vzhukovskii** [comment]
>I don't think that it is a possible workaround. When you share one folder with someone you don't expect to give access to all your folders for reading.

Yep, think so.

>it's not a bug.

I mean, it's a bug only in terms of che-workspace-client library, because it tries to make a request using machine-token, which is wrong. It should respect filtering and make request using user token. Using keycloak is the only painless way I see.
