### ISSUE TITLE
Update exsisting workspace's "factoryurl" attribute

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#17258]
Hi all, please help me understand workspace update api using swagger:
Here is the json i got from `GET /workspace` api:

<details>
  <summary>"GET /workspace" response : </summary>

```
[
  {
    "attributes": {
      "org.eclipse.che.runtimes_id": "runtimeslyrdmennnlkch8i7",
      "infrastructureNamespace": "che",
      "factoryurl": "https://raw.githubusercontent.com/myrepo/my-devfile-registry/master/mydevfile.yaml?override.projects.projectname.source.location=https://github.com/myrepo/myproject.git",
      "updated": "1593151818108",
      "created": "1593149297768"
    },
    "namespace": "che",
    "temporary": false,
    "id": "workspacekq0owihkjgo9iojr",
    "status": "RUNNING",
    "devfile": {
      "metadata": {
        "name": "test2i7ad"
      },
      "projects": [
        {
          "name": "projectname",
          "source": {
            "location": "https://mylocation.com/exampleproject.git",
            "type": "git"
          }
        }
      ],
      "components": [
        {
          "type": "cheEditor",
          "reference": "https://raw.githubusercontent.com/myrepo/my-plugin-registry/master/meta-editor.yaml"
        }
      ],
      "apiVersion": "1.0.0"
    }
  }
]
```  

</details>

I would like to replace the `factoryurl` shown above with an empty string, so I tried to update using `PUT /workspace/{id}` api and passed the following json:
<details>
  <summary>JSON input to "PUT /workspace/{id}" : </summary>

```
[
  {
    "attributes": {
      "org.eclipse.che.runtimes_id": "runtimeslyrdmennnlkch8i7",
      "infrastructureNamespace": "che",
      "factoryurl": "",
      "updated": "1593151818108",
      "created": "1593149297768"
    },
    "namespace": "che",
    "temporary": false,
    "id": "workspacekq0owihkjgo9iojr",
    "status": "RUNNING",
    "devfile": {
      "metadata": {
        "name": "test2i7ad"
      },
      "projects": [
        {
          "name": "projectname",
          "source": {
            "location": "https://mylocation.com/exampleproject.git",
            "type": "git"
          }
        }
      ],
      "components": [
        {
          "type": "cheEditor",
          "reference": "https://raw.githubusercontent.com/myrepo/my-plugin-registry/master/meta-editor.yaml"
        }
      ],
      "apiVersion": "1.0.0"
    }
  }
]
```

</details>

Please note that there is change only in the `factoryurl` above. But the response code of `PUT /workspace/{id}` is always 500 with the following message:

```
{
  "message": "Internal Server Error occurred, error time: 2020-06-26 06:17:14"
}
```

Please help me change only the factory url of the current workspace.

**Comment by skabashnyuk** [comment]
hello @svkr2k `factoryurl` is a `service` level attribute that tracks the factory url frow wich workspace was created. Like some of the other attributes,  for example `created`, it doesn't expect to be updated by end-user. I agree that that message `Internal Server Error occurred ` is not self-explaining, we can take a look and improve it.  Can you elaborate on why do you want to change it?

**Comment by svkr2k** [comment]
Thank you, @skabashnyuk .

I was testing a scenario... After creating a workspace, the custom theia editor does additional processing using the factory url. As it is detecting the presence of factory url, whenever the current workspace in theia changes (which inturn causes a reload of the theia editor), the editor again does the processing. This happens for every workspace reload. To avoid that, i thought i can check if i can set the factory url to empty immediately after creation of workspace as it is no longer needed. 

Hope that makes sense.

Additional note: I tried setting the workspace attributes through a theia plugin & che api.
`che.workspace.update(workspaceId, workspace);` seems to work fine ! Hope my observetion is correct ?

**Comment by skabashnyuk** [comment]
>I was testing a scenario... After creating a workspace, the custom theia editor does additional processing using the factory url. As it is detecting the presence of factory url, whenever the current workspace in theia changes (which inturn causes a reload of the theia editor), the editor again does the processing. This happens for every workspace reload. To avoid that, i thought i can check if i can set the factory url to empty immediately after creation of workspace as it is no longer needed.

Sounds like a complication on the theia-plugin side.

>i.e., after calling the above api from theia plugin, i checked the facroty url in swagger using GET /workspace. The json that it returned had factoryurl set to "". Kindly confirm.

That  I would consider as a bug.

**Comment by svkr2k** [comment]
> i.e., after calling the above api from theia plugin, i checked the facroty url in swagger using GET /workspace. The json that it returned had factoryurl set to "". Kindly confirm.

>That I would consider as a bug.

I believe that a custom theia editor in a workspace that was created using a factory may need to do further processing on the project that was cloned during workspace creation (like opening the workspace for the cloned project, sync the other sub systems with the opened project etc.).

In order to know this information, it might rely on factory-plugin to tell when it clones a project.
As factory-plugin is reloaded everytime the "theia workspace" reloads, theia would again get an indication that the project from factory has been cloned ... 
Hope it makes sense :-D

I would be happy if we allow `factoryurl` to be set to `""` :-)

**Comment by skabashnyuk** [comment]
>In order to know this information, it might rely on factory-plugin to tell when it clones a project.
As factory-plugin is reloaded everytime the "theia workspace" reloads, theia would again get an indication that the project from factory has been cloned ...

I don't think that deleting the information is a proper way to exit this loop. I assume it can be :
 - another attribute
 - fact that there is already existed folder.
- etc.
