### ISSUE TITLE
In docs specify that certificate format should be base 64

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17250]
### Is your enhancement related to a problem? Please describe.

In documentation we describe how to export X.509 certificates as ConfigMaps (for example in [Deploying Che with support for Git repositories with self-signed certificates](https://www.eclipse.org/che/docs/che-7/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/). Certificates files are usually Base64 ASCII files (.pem, .crt, .ca-bundle etc...) but can be also encoded in binary format (.cer). In the doc we should make it clear that certificates exported as ConfigMaps should be in Base64 format.

**Comment by tomgeorge** [comment]
Merged
