### ISSUE TITLE
Classpath resolution fails with Maven

### ISSUE THREAD

**Issue by gzsombor** [eclipse-che/che#1725]
I've tried to import a maven project into Che, it seems that all the files appear in the IDE, but in every java source file it complains about the missing types - because it couldn't locate the dependencies/jars. I can build the app from the IDE - so it seems, that maven is properly installed. However under Project > Configure Classpath I couldn't modify anything, and under org.eclipse.che.MAVEN2_CLASSPATH there isn't anything showing up.
If I click on the Maven > Reimport menu item, then nothing happens on the UI - only an exception appears in one of the log files:

```
STDOUT] java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[STDOUT]        at java.lang.String.substring(String.java:1919) ~[na:1.8.0_45]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.addSourcePathFromConfiguration(MavenWorkspace.java:218) ~[che-plugin-maven-server-4.4.2.jar:4.4.
2]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.addSourcesFromBuildHelperPlugin(MavenWorkspace.java:200) ~[che-plugin-maven-server-4.4.2.jar:4.4
.2]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.lambda$runResolve$2(MavenWorkspace.java:158) ~[che-plugin-maven-server-4.4.2.jar:4.4.2]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenWorkspace$$Lambda$88/947264938.run(Unknown Source) ~[na:na]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenProjectResolveTask.perform(MavenProjectResolveTask.java:34) ~[che-plugin-maven-server-4.4.2.jar:4.4.2]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor.doRunTasks(MavenTaskExecutor.java:81) [che-plugin-maven-server-4.4.2.jar:4.4.2]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor.lambda$runTask$0(MavenTaskExecutor.java:66) [che-plugin-maven-server-4.4.2.jar:4.4.2]
[STDOUT]        at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor$$Lambda$89/168032488.run(Unknown Source) [che-plugin-maven-server-4.4.2.jar:4.4.2]
[STDOUT]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
[STDOUT]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
[STDOUT]        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

```

**Reproduction Steps:**
1. Import a maven project from git
2. Open a java file
3. Notice, that everything is red, and it has a tons of missing class files
   4, Nothing happens, when the Maven Reimport menuitem is clicked. Even an error message would be very helpful.

**Expected behavior:**

It should detect the maven dependencies. It should show an error message, if the maven import is failed.

**Che version:**    4.4.2
**OS and version:** Ubuntu 16.04
**Docker version:** 1.10.3
**Che install:**    server

**Comment by TylerJewell** [comment]
After the git clone did you set the project type to maven?  You need to do this in the project configuration dialog.  

If you did a project import as opposed to a git clone you get an additional dialog box that lets you set the type during the import sequence.

**Comment by gzsombor** [comment]
Yes, I've clicked on the Maven project type, clicked on the next, it shows the correct groupId/artifactId/version/packaging and clicked on save.

**Comment by ghost** [comment]
@gzsombor Is this a public project? Can you share it?

**Comment by gzsombor** [comment]
I can't share the project, however I can reproduce it with a barebone project, which I've pushed here : 
https://notabug.org/zsombor/che-test

I can't see the exception, but the error message about the missing classes are there.

**Comment by thyeun** [comment]
@gzsombor, are you having the new version of maven 3.3.9 (maven version 3) on your ubuntu? instead of using the maven version 2.  (check your maven version with "mvn -version")

if you replace the maven version 2 to maven version 3, you have to modify the maven.sh file, according to your M2_path.

**Comment by gzsombor** [comment]
Yes, I have. But as I understand the editor lives in docker image - which is managed by che - so it shouldn't count.

**Comment by gzsombor** [comment]
In fact, in the IDE's console I can run the maven build successfully

**Comment by TylerJewell** [comment]
@gzsombor - we are taking this into our next sprint for development and resolution.

**Comment by mmjordan** [comment]
Hello~I just start to use eclipse che for serval days, and I got the same problem with @gzsombor . 
It seems that, this problem has no matter with the project. I just created a new maven project, and the problem reproduced. Under Project->Configure Classpath, the "Add JAR" and "Add Folder" buttons are disabled, and the "org.eclipse.che.MAVEN2_CLASSPATH" node is and empty folder in the build path tree.
@svor , my i know that have you got the cause of this issue. Thank you very much.

**Comment by zakkriel** [comment]
Guys, same behavior here...
I've imported a maven project (from an SVN repo) but when you open a file on the editor every import is red and cannot be resolved.

* mvn clean install runs successfully from IDE's terminal.
* I've make sure to try #2805 but it didn't solve the issue.

any news regarding this ticket?

**Comment by TylerJewell** [comment]
It is still open for development.  It looks like it is a confirmed bug, but waiting for an engineer to take it into a sprint or a community member to help us with a fix.  @vparfonov ?

**Comment by AndrienkoAleksandr** [comment]
I localized problem. Dependency will be resolved if you delete this plugin from pom.xml https://notabug.org/zsombor/che-test:

`<plugin>`
`<groupId>org.codehaus.mojo</groupId>`
`<artifactId>build-helper-maven-plugin</artifactId>`
`<executions>`
`<execution>`
`<id>add-source</id>`
`<phase>generate-sources</phase>`
`<goals>`
`<goal>add-source</goal>`
`</goals>`
`<configuration>`
`<sources>`
`<source>target/metamodel</source>`
`</sources>`
`</configuration>`
`</execution>`
`</executions>`
`</plugin>`

I think we should investigate how such maven constructions brokes normal resolving in our Maven plugin. @vparfonov what do you think?

**Comment by AndrienkoAleksandr** [comment]
I localized that the main reason this is existing "source" in the "execution" block: 
`<sources>`
`<source>target/metamodel</source>`
`</sources>`

**Comment by mmjordan** [comment]
I got the same problem. What's more, there's an exception in the ws-agent log:

2016-11-29 12:34:04,718[en Executor - 0]  [ERROR] [o.e.c.p.m.s.c.MavenWorkspace 211]    - Can't update Java project classpath with Maven build helper plugin configuration
org.eclipse.jdt.core.JavaModelException: Core exception
        at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.addSourcesFromBuildHelperPlugin(MavenWorkspace.java:201) [che-plugin-maven-server-5.0.0-M7.jar:5.0.0-M7]
        at org.eclipse.che.plugin.maven.server.core.MavenWorkspace.lambda$runResolve$10(MavenWorkspace.java:160) [che-plugin-maven-server-5.0.0-M7.jar:5.0.0-M7]
        at org.eclipse.che.plugin.maven.server.core.MavenWorkspace$$Lambda$159/68302655.run(Unknown Source) [che-plugin-maven-server-5.0.0-M7.jar:5.0.0-M7]
        at org.eclipse.che.plugin.maven.server.core.MavenProjectResolveTask.perform(MavenProjectResolveTask.java:39) [che-plugin-maven-server-5.0.0-M7.jar:5.0.0-M7]
        at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor.doRunTasks(MavenTaskExecutor.java:81) [che-plugin-maven-server-5.0.0-M7.jar:5.0.0-M7]
        at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor.lambda$runTask$29(MavenTaskExecutor.java:66) [che-plugin-maven-server-5.0.0-M7.jar:5.0.0-M7]
        at org.eclipse.che.plugin.maven.server.core.MavenTaskExecutor$$Lambda$160/1206818011.run(Unknown Source) [che-plugin-maven-server-5.0.0-M7.jar:5.0.0-M7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
2016-11-29 12:34:04,723[en Executor - 0]  [ERROR] [o.e.c.r.ResourcesPlugin 243]         - Can't find project: /web-java-spring

My project is web-java-spring, which is a che sample project cloned from Github. The content of pom.xml is simple:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.eclipse.che.examples</groupId>
    <artifactId>web-java-spring</artifactId>
    <packaging>war</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>SpringDemo</name>
    <properties>
        <maven.compiler.source>1.6</maven.compiler.source>
        <maven.compiler.target>1.6</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
            <version>2.5</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>3.0.5.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>`

**Comment by ghost** [comment]
@mmjordan can you still reproduce the issue?
