### ISSUE TITLE
Can't build the master branch with che-dev:nightly container image.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#17259]
### Describe the bug

The master branch of Che requires Java11. But quay.io/eclipse/che-dev:nightly has Java8.

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Run this script and see the error.

```
      docker run --name che-dev -v $(pwd):/projects --net=host -e MAVEN_OPTS=-Xmx4096m \
        quay.io/eclipse/che-dev:nightly \
        mvn -DskipTests -Pnative -Dmaven.repo.local=/home/user/.m2/repository -Dhttp.keepAlive=false clean install
```

### Expected behavior

Build finished with success.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify)

My build env is Azure DevOps Pipeline. But this will be environment independent.

**Comment by monaka** [comment]
Workaround: Using `quay.io/eclipse/che-java11-maven:nightly` instead of `che-dev`.

**Comment by skabashnyuk** [comment]
I don't see a reason to keep `che-dev` image anymore. What if we just delete it?

**Comment by monaka** [comment]
It's ok for me to delete `che-dev`.
At the same time, I think Che6  maintainers may require it (if still exists).

There needs some more patches to remove `che-dev` dependencies if delete it
I just run `git grep eclipse/che-dev` on the master branch. I found some dependencies.

**Comment by l0rd** [comment]
+1 to remove `che-dev`

**Comment by monaka** [comment]
Today I grepped the master branch again. There is no `eclipse/che-dev` dependencies.
(Strictly, it is shown in the example of JSON schema and tests. They are harmless.)
So I close this as resolved.
