### ISSUE TITLE
Fail to start a workspace if storage hasn't been configured on the cluster

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17253]
### Is your enhancement related to a problem? Please describe.

We should check if dynamic storage and extra persistent volumes have been configured on a cluster before letting the user create a workspace. And propose to start the workspace in ephemeral mode.

**Comment by skabashnyuk** [comment]
@l0rd can you give a few examples of expected from the che-server activity. I'm not fully understand this request.

**Comment by ibuziuk** [comment]
e.g. PVC quota in the use nameaspace

**Comment by skabashnyuk** [comment]
OC 3.11
```
oc  describe quota object-counts  -n skabashn-che
Name:                   object-counts
Namespace:              skabashn-che
Resource                Used  Hard
--------                ----  ----
persistentvolumeclaims  1     2
replicationcontrollers  0     20
secrets                 18    20
services                0     15
```

**Comment by ibuziuk** [comment]
so, this ^ means if a user is not allowed to create PVC  workspace startup should be prohibited in the non-ephemeral mode.

**Comment by l0rd** [comment]
This should be fixed with devworkspace as workspace engine. I beleive that's a check that dashbord should do. Changing the area label accordingly and setting devworkspace STEP 3 as milestone. cc @sleshchenko

**Comment by l0rd** [comment]
After discussion at latest dw cabal we decided to remove this issue from the scope of milestone "DevWorkspace Integration - STEP3".

**Comment by ibuziuk** [comment]
lifecycle/frozen
