### ISSUE TITLE
[chectl] document the fact that workspace:delete can only work on non-running workspaces

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17256]
### Is your enhancement related to a problem? Please describe.

In https://github.com/che-incubator/chectl#chectl-workspacedelete-workspace we should explain that you can only delete a non-running workspace, and that if you need to make a running workspace non-running, you can simply run https://github.com/che-incubator/chectl#chectl-workspacestop-workspace before deleting it.

See also [CRW-1027](https://issues.redhat.com/browse/CRW-1017) where someone thought it was a bug that they couldn't delete a running workspace. This seems like an intentional design choice since if the workspace is running, it might contain unsaved changes that a user needs to preserve.

**Comment by nickboldt** [comment]
PR: https://github.com/che-incubator/chectl/pull/761

**Comment by l0rd** [comment]
I have created https://github.com/eclipse/che/issues/17270 to avoid that we get an error when trying to stop a running workspace.
