### ISSUE TITLE
Lag of Toggle to Enable/Disable Plugins

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17252]
### Is your enhancement related to a problem? Please describe.

It may take a few seconds to get a visual feedback when the toggle is selected. And double clicking it makes it enabled/disabled without any visual feedback.

![image](https://media.giphy.com/media/j3W14qhyeDxj5h2hCc/giphy.gif)

### Describe the solution you'd like

The toggle should be switched as soon as it is clicked.

**Comment by sympatheticmoose** [comment]
@l0rd perhaps we close this in favour of dashboard-next?

**Comment by l0rd** [comment]
@sympatheticmoose yep let's close it.
