### ISSUE TITLE
Remove implementation details from Admin Guide

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17266]
### Is your task related to a problem? Please describe.

These details didn't help much in the admin's daily work.
They are more like guides for Che developers and perhaps their place is better to move closer to original code.

- http://jenkinscat.gsslab.pnq.redhat.com:8080/view/Devtools/job/doc-CodeReady-Workspaces_Admin-Guide/lastSuccessfulBuild/artifact/index.html#authenticating-to-the-codeready-workspaces-server-using-openid_authenticating-to-the-codeready-workspaces-server -

- http://jenkinscat.gsslab.pnq.redhat.com:8080/view/Devtools/job/doc-CodeReady-Workspaces_Admin-Guide/lastSuccessfulBuild/artifact/index.html#extending-codeready-workspaces-monitoring-metrics_monitoring-codeready-workspaces 

### Describe the solution you'd like
Remove or move it to the che server code.

**Comment by rkratky** [comment]
@skabashnyuk, thanks for identifying these. Do we need PM or other confirmation, or can we go ahead a remove the content.

Also, you're linking CRW docs. Am I correct in assuming that the content can also be removed from Che docs?

**Comment by skabashnyuk** [comment]
>Do we need PM or other confirmation, or can we go ahead a remove the content.

I think that is not necessary since it has no impact on end-user. Only for Eclipse Che committers. CC @l0rd 

> Am I correct in assuming that the content can also be removed from Che docs?

Yes, I was planning to involve platform team for that. They precisely know what to do. If you don't mind.

**Comment by rkratky** [comment]
> Yes, I was planning to involve platform team for that. They precisely know what to do. If you don't mind.

OK, thanks. Re-adding the team/platform label.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2539
