### ISSUE TITLE
Ensure that the service-oriented attributes of Workspace object are not editable

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17261]
### Is your task related to a problem? Please describe.
There are some attributes that provide additional information about the workspace.
Such as:
 - `created`
 - `updated`
 - `stack`
 - `factoryUrl`

We need to ensure that the end-user is not able to edit them. That can break some functionality that relies on that.

### Describe the solution you'd like
400 BadRequest

### Describe alternatives you've considered
do nothing 

### Additional context
https://github.com/eclipse/che/issues/17258

**Comment by svkr2k** [comment]
Can we allow setting `factoryUrl` to `""` ?

**Comment by skabashnyuk** [comment]
@svkr2k It can be  `unset` during workspace creation, but I would say once it there it should not be removed because it can break the logic that relies on it.

 If I properly understand your use case you need some flag that explained that sources are already cloned? Am I right?

**Comment by skabashnyuk** [comment]
won't fix
