### ISSUE TITLE
Cannot load compilation mapping error after 401 (unauthorized) in jwtproxy

### ISSUE THREAD

**Issue by creatica-soft** [eclipse-che/che#17262]
### Describe the bug
When starting the workspace, after the workspace started, the browser gets 401 when it gets https://che/api/workspace/serverxpecw0mc-jwtproxy/server-4402/
There is no Authorization: Bearer header in this request but this header is present in all previous requests to https://che/api/workspace/workspacedayxjfkzy8bppclc
Next requests to https://che/_app/compilation-mappings.txt?1593165007586 returns 404.
So the workspace is not loaded in the browser and gets stopped after a timeout.

### Che version
 - latest and all previous versions, basically it has never worked!

### Steps to reproduce

Installed in k8s 1.17 using config map:

  CHE_DEBUG_SERVER: "false"
  CHE_HOST: che
  CHE_INFRA_KUBERNETES_INGRESS__START__TIMEOUT__MIN: "10"
  CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: ""
  CHE_INFRA_KUBERNETES_INGRESS_PATH__TRANSFORM: '%s(.*)'
  CHE_INFRA_KUBERNETES_NAMESPACE_ALLOW__USER__DEFINED: "false"
  CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: default
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "1724"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "1724"
  CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE: centos:7.6.1810
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "true"
  CHE_INFRA_KUBERNETES_PVC_QUANTITY: 1Gi
  CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME: cinder
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: per-workspace
  CHE_INFRA_KUBERNETES_RUNTIMES__CONSISTENCY__CHECK__PERIOD__MIN: "-1"
  CHE_INFRA_KUBERNETES_SERVER__STRATEGY: single-host
  CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME: che-workspace
  CHE_INFRA_KUBERNETES_TLS__ENABLED: "true"
  CHE_INFRA_KUBERNETES_TLS__SECRET: che-ssl-cert
  CHE_INFRA_KUBERNETES_TRUST__CERTS: ""
  CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "15"
  CHE_INFRASTRUCTURE_ACTIVE: kubernetes
  CHE_JDBC_PASSWORD: ***
  CHE_JDBC_URL: jdbc:postgresql://postgres-0.postgres.default.svc.cluster.local:5432/che
  CHE_JDBC_USERNAME: che
  CHE_KEYCLOAK_AUTH__SERVER__URL: https://keycloak/auth
  CHE_KEYCLOAK_CLIENT__ID: che
  CHE_KEYCLOAK_REALM: master
  CHE_LIMITS_USER_WORKSPACES_COUNT: "3"
  CHE_LIMITS_USER_WORKSPACES_RAM: "-1"
  CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "1"
  CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "604800"
  CHE_LOG_LEVEL: INFO
  CHE_MAIL_FROM__EMAIL__ADDRESS: che@che
  CHE_METRICS_ENABLED: "false"
  CHE_MULTIUSER: "true"
  CHE_PORT: "8080"
  CHE_SERVER_SECURE__EXPOSER: default
  CHE_SERVER_SECURE__EXPOSER_JWTPROXY_IMAGE: quay.io/eclipse/che-jwtproxy:49c7223
  CHE_WEBSOCKET_ENDPOINT: ws://che:8080/api/websocket
  CHE_WEBSOCKET_ENDPOINT__MINOR: ws://che:8080/api/websocket-minor
  CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: "1"
  CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: 100m
  CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB: "1024"
  CHE_WORKSPACE_DEFAULT__MEMORY__REQUEST__MB: "512"
  CHE_WORKSPACE_DEVFILE__REGISTRY__URL: http://devfile-registry-che
  CHE_WORKSPACE_HTTP__PROXY: ""
  CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS: ""
  CHE_WORKSPACE_HTTPS__PROXY: ""
  CHE_WORKSPACE_JAVA__OPTIONS: '-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC
    -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
    -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom '
  CHE_WORKSPACE_MAVEN__OPTIONS: '-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC
    -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
    -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom '
  CHE_WORKSPACE_NO__PROXY: ""
  CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE: quay.io/eclipse/che-plugin-artifacts-broker:9ffcb27
  CHE_WORKSPACE_PLUGIN__BROKER_METADATA_IMAGE: quay.io/eclipse/che-plugin-metadata-broker:9ffcb27
  CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY: IfNotPresent
  CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN: "5"
  CHE_WORKSPACE_PLUGIN__REGISTRY__URL: http://plugin-registry-che/v3
  CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: IfNotPresent
  JAVA_OPTS: '-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
    -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m '
  KUBERNETES_LABELS: app=che,component=che

### Expected behavior
Expected it to work! To load a workspace!

### Runtime
   - [ ] kubernetes 1.17

### Installation method
Custom using config map above

### Eclipse Che Logs
nothing specific in the logs

**Comment by sleshchenko** [comment]
@mmorhun @metlos Do you have any ideas what might be wrong with that single-host configuration? What info is needed to figure out the cause?

**Comment by abhsange** [comment]
@creatica-soft found any solution/ workaround for this issue ? I'm also facing same issue using single host configuration with Che on kubernetes deployed using Operator.

**Comment by mmorhun** [comment]
cc @skabashnyuk

**Comment by pgirishibm** [comment]
@skabashnyuk I am facing the exact same issue reported by @creatica-soft . For me,  che is a single-host setup on kubernetes which I deployed using Operator.

**Comment by skabashnyuk** [comment]
@pgirishibm I may suggest switching to multi-host mode until https://github.com/eclipse/che/issues/12914 would be implemented
