### ISSUE TITLE
how can I install a LaTeX distribution in my workspace?

### ISSUE THREAD

**Issue by rholland** [eclipse-che/che#17279]
I am using the Python devfile (image).

Thanks.

**Comment by azatsarynnyy** [comment]
Hello @rholland 
I guess you need to include an image with LaTeX tools into your Workspace.
See Che Devfile docs https://redhat-developer.github.io/devfile. Look for `type: dockerimage`.

**Comment by rholland** [comment]
Thanks.  I have looked for one but not found anything that works with che. Do you have a suggestion where to find one?

**Comment by azatsarynnyy** [comment]
@rholland I saw some images on Dockerhub, e.g. https://hub.docker.com/r/aergus/latex. But I've never used it.

**Comment by rholland** [comment]
Thanks. I tried that and a couple of others but they fail.

------------------
`
Successfully assigned rhholland-che/workspacejuvs4vfibetoz1qw.che-plugin-broker to ip-172-31-65-80.us-east-2.compute.internal
pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0"
Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0"
Created container
Started container
Starting plugin metadata broker
List of plugins and editors to install
- redhat-developer/che-workspace-telemetry-woopra-backend/0.0.1 - Telemetry plugin to send information to Woopra
- eclipse/che-machine-exec-plugin/7.14.3 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse Che workspace containers.
- eclipse/che-theia/7.14.3 - Eclipse Theia

All plugin metadata has been successfully processed
pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.14.3"
Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.14.3"
Created container
Started container
pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0"
Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0"
Created container
Started container
Starting plugin artifacts broker
Saving log of installed plugins
All plugin artifacts have been successfully downloaded
pulling image "quay.io/eclipse/che-jwtproxy:fd94e60"
Successfully pulled image "quay.io/eclipse/che-jwtproxy:fd94e60"
Created container
Started container
pulling image "quay.io/eclipse/che-python-3.7:7.14.3"
Successfully pulled image "quay.io/eclipse/che-python-3.7:7.14.3"
Created container
Started container
pulling image "aergus/latex"
Successfully pulled image "aergus/latex"
Created container
Started container
pulling image "quay.io/openshiftio/che-workspace-telemetry-woopra-backend:latest"
Successfully pulled image "quay.io/openshiftio/che-workspace-telemetry-woopra-backend:latest"
Created container
Started container
pulling image "quay.io/eclipse/che-machine-exec:7.14.3"
Error: Failed to run the workspace: "The following containers have terminated:
latex: reason = 'Completed', exit code = 0, message = 'null'"
`

**Comment by azatsarynnyy** [comment]
@rholland that's because the container is terminated immediately after running.
You need to make it non-terminated by calling `tail -f /dev/null`
The following directives can be added to the Devfile:
```yaml
command: ['tail']
     args: ['-f', '/dev/null']
```

For more details, see Che Devfile docs https://redhat-developer.github.io/devfile, look for `type: dockerimage`.

**Comment by rholland** [comment]
Thanks.
