### ISSUE TITLE
chectl should verify if a workspace is stopped before trying to delete it

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17270]
### Is your enhancement related to a problem? Please describe.

This is related to #17256: if a user tries `chectl workspace:delete` and the workspace is running it gets an error.

### Describe the solution you'd like

We should verify if the workspace is already stopped and if it's not provide a meaningful message to the user: "Cannot delete a running workspace. Please stop it using the command `workspace:stop` and try again."

**Comment by tolusha** [comment]
Fixed by https://github.com/che-incubator/chectl/pull/806/commits/3429a53531e5be0e985a62d9afb3b6c9648b73c1
