### ISSUE TITLE
Unable to find single-host documentation

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17271]
### Describe the bug

I was looking for this documentation article from the : [Configuring workspace exposure strategy](https://www.eclipse.org/che/docs/che-7/configuring-workspace-exposure-strategies) but I wasn't able to from the menu and search bar.

### Steps to reproduce

Go to https://www.eclipse.org/che/docs/che-7 and spend 5 minutes navigating in the menu bar to try to find some article that explains how to configure Che in single-host mode.

### Expected behavior

I would expect:

1. To find the article under `Installation Guide / Configuring Che`
2. To find the article if searching for `single-host` in 

Some screenshots:

![image](https://user-images.githubusercontent.com/606959/85994231-d207ab00-b9f7-11ea-8006-b7cdab018f97.png)

and 

![image](https://user-images.githubusercontent.com/606959/85994616-55c19780-b9f8-11ea-825a-ff708c8ef40f.png)

**Comment by sparkoo** [comment]
top 2 results after searching `single host` 
https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-workspace-exposure-strategies/
https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-the-che-installation/

it's imho ok no, with google search

**Comment by l0rd** [comment]
@sparkoo agreed

**Comment by mshaposhnik** [comment]
Moved into istallation part and added into navigation menu
