### ISSUE TITLE
[Hosted Che] Failed to load signature keys for ws

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17273]
### Describe the bug
Multiple events: 

Failed to load signature keys for ws
Cause: Unable to create signature key pair because referenced workspace with id

### Che version
 - [ ] 7.14.3

### Additional context
Kibana query - ```kubernetes.labels.app:"rhche" AND kubernetes.namespace_name:"dsaas-production"  AND  kubernetes.container_name:"rhche"  AND level:"err" AND message: "Failed to " ```

Might be related to https://github.com/eclipse/che/issues/15801

**Comment by skabashnyuk** [comment]
it might happen if workspace removed from che server-side but pod for some reason stay live and pinging or requesting some data. Or in some other way, machine token was used.

**Comment by ibuziuk** [comment]
@skabashnyuk there are ~2K hits for the last week, this does not seem to be expected:

```kubernetes.labels.app:"rhche" AND kubernetes.namespace_name:"dsaas-production"  AND level:"err" AND "Failed to load signature keys for ws"```

**Comment by skabashnyuk** [comment]
@ibuziuk what is your expectation? remove the error or make it warn instead of error?

**Comment by ibuziuk** [comment]
the expectation is to not having this error unless there is smth broken on the che server end.

> it might happen if workspace removed from che server-side but pod for some reason stay live and pinging or requesting some data.

this does not look like the case according to the metrics ^

> Or in some other way, machine token was used.

what this could be?

**Comment by skabashnyuk** [comment]
>it might happen if workspace removed from che server-side but pod for some reason stay live and pinging or requesting some data.

I was probably wrong here. This is stopped workspace but someone trying to make a request with machine token and che server is not able to validate signature because keys only exist for the running workspaces.
