### ISSUE TITLE
how do I save and load a custom keymap json file when using Theia in Eclipse Che on openstack?

### ISSUE THREAD

**Issue by rholland** [eclipse-che/che#17277]
I noticed that changes are not automatically saved between sessions.  Should I save to a new workspace within Theia?  Is there a better way to retain keymap settings between sessions?

Thanks.

**Comment by rholland** [comment]
If I save a workspace in Theia it does not save it to persistant storage.  How can I save a workspace and reopen it after Theia launches?  The dialog box does not offer the option of saving it in "projects"

**Comment by azatsarynnyy** [comment]
@rholland `/projects` folder is not the default folder in the dialog box. Try to choose it manually.

**Comment by rholland** [comment]
If I manually save it in Theia folder it is not  there on restart.

**Comment by azatsarynnyy** [comment]
1) make sure you have a persistent volume enabled in your Devfile:
```yaml
attributes:
  persistVolumes: 'true'

```
2) choose `/projects` folder, not `/home/theia`
see the dropdown at the bottom:
![image](https://user-images.githubusercontent.com/1636395/86136551-e5e50700-baf4-11ea-903b-0e2d57c05c8f.png)

**Comment by rholland** [comment]
Thanks.  I saved the workspace as you suggested with my modified key bindings and the file persisted after I restarted.  I double clicked on it and it reloaded the workspace.  But the key bindings are still back at  the defaults.  How can I save my key bindings and reload them to my workspace?

**Comment by rholland** [comment]
I think the problem has been flagged here a couple of weeks ago #16753

**Comment by azatsarynnyy** [comment]
you're right, this is the related issue
