### ISSUE TITLE
As the admin, I want to deploy Eclipse Che via the operatorhub with external DB (RDS) and internal keycloak 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17274]
### Is your task related to a problem? Please describe.
As the admin, I want to deploy Eclipse Che via operatorhub with external DB (RDS) and internal keycloak. Currently, according to the documentation, it is not possible https://www.eclipse.org/che/docs/che-7/external-database-setup/

```When using an external PostgreSQL database, it is also necessary to use an external Keycloak.```

### Describe the solution you'd like
possibility to deploy Eclipse Che via operatorhub with external DB (RDS) and internal keycloak 

### Describe alternatives you've considered
N/A

### Downstream issue
https://issues.redhat.com/browse/CRW-801

**Comment by tolusha** [comment]
Actually I don't remember why we are limited by this.

**Comment by tolusha** [comment]
@ibuziuk 
Just to clarify. 
External DB means the DB provisioned outside the k8s cluster.

**Comment by ibuziuk** [comment]
> External DB means the DB provisioned outside the k8s cluster.

@tolusha yeah, RDS for instance

**Comment by ibuziuk** [comment]
@tolusha so at the end of the day, this issue is about documenting the right procedure which allows using internal keykloak & external db?

**Comment by tolusha** [comment]
@ibuziuk 
Not exactly. I am about to provide a PR to fix operator code as well.

**Comment by ibuziuk** [comment]
@tolusha wondering if we can consider including a fix for CRW 2.3 or it is for CRW 2.4 ? Asking since this is a dependency for Hosted Toolchain

**Comment by tolusha** [comment]
@ibuziuk 
It depends how important it is.
The changes are quite simple and can be merged into 7.16.x branch
