### ISSUE TITLE
Event handler on user login in eclipse che

### ISSUE THREAD

**Issue by ankkumar-progress** [eclipse-che/che#17275]
## Summary
Background: We are using Eclipse che for a language ABL.

Requirement: Is there a way to attach an event handler to the user login?

Motivation: We want to automate the process of the creation of workspace on user login. 
If there is already a workspace in his account we skip or else create a workspace.
So basically I want to run a script when a user login to eclipse che.

## Relevant information

Che version: 6.14.0
Environment: Kubernetes

**Comment by gorkem** [comment]
Have you looked at creating workspaces from devfiles? 
You can directly refer to a devfile on a che URL that will create the workspace as defined by the devfile. Check out[ this article](https://www.eclipse.org/che/docs/che-7/configuring-a-workspace-using-a-devfile/#creating-a-workspace-from-a-publicly-accessible-standalone-devfile-using-http_configuring-a-workspace-using-a-devfile) and see if it does the trick for you?
