### ISSUE TITLE
Create test for check git with self sign certs

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#17288]
We had customer issue where used self sign certs. On this moment we are checking git features using third part service (github). We can create deployment with git service.  For this good fit  **gogs** git (https://gogs.io/) with add self-sign cert. 
Also it can improve existed test for checking git + ssh flow. We can avoid the third part service and make test more reliable and productive.

**Comment by SkorikSergey** [comment]
Done.
