### ISSUE TITLE
Create automation test for checking  of custom .vsix plugin

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#17286]
We need to automate this workflow
As variant we can implement next positive scenario:
* Create a workspace with predefined `yaml` metafile: https://gist.githubusercontent.com/azatsarynnyy/cfefb12b04d41bdcb2fa1a74c6080fe1/raw/9741d718d56f5155f12cb2c39c479b7b2e3b0033/meta.yaml
* Add section this to workspace configuration:
`- type: chePlugin
    reference: https://gist.githubusercontent.com/azatsarynnyy/cfefb12b04d41bdcb2fa1a74c6080fe1/raw/9741d718d56f5155f12cb2c39c479b7b2e3b0033/meta.yaml`
* Check UI parts of plugin in the workspace

**Comment by ericwill** [comment]
This will be handled as part of #18219 and #15819
