### ISSUE TITLE
Web terminal operator OLM manifests cannot refer to variable image tags

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17285]
### Is your task related to a problem? Please describe.
The current OLM manifests refer to the nightly image of `devworkspace-operator`. This won't work going forward, as any PR that changes the controller's `deployment.yaml` will break the operator when the new image is pulled.

### Describe the solution you'd like
We need to build and push images tagged with commit hash between releases and refer to those in the operator. Likely it makes sense to do this in the https://github.com/devfile/devworkspace-operator CI, so that that image can be reused in https://github.com/redhat-developer/web-terminal-operator (for releases we would still need to use a reg.rh.io image).

**Comment by sleshchenko** [comment]
> The current OLM manifests refer to the nightly image of devworkspace-operator. This won't work going forward, as any PR that changes the controller's deployment.yaml will break the operator when the new image is pulled.

The proposed solution has its own pros and cons:
**pros:**
- not released WebTerminal Operator is going to be stable

**cons:**
- WebTerminal Operator is not going to have latest controller even if it should be compatible. So, we manually should continuously update WebTerminal Operator CSV to test it.

What if we just get an agreement that - if somebody change devworkspace deploy manifests - they must make sure that it works with WebTerminal Operator and provide PR if needed?
Then we may have a nightly test run on WebTerminal to alert us that we got a not-working controller image. And in theory, no manual testing of WebTerminal is needed.

BTW it's easy to get commit hash built container https://github.com/docker/build-push-action#tag_with_sha if we decide that it's way to go.

**Comment by sleshchenko** [comment]
At this point, we agreed to require WebTerminal Operator CSV files update when there is PR in devworkspace operator repo with deployment files changes.

Later we can revise it, start using git-sha and automate pulling fresh image into WebTerminal Operator.
