### ISSUE TITLE
Add non-Red Hat commiters into admin list for PR checks in ci.centos.org

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#17282]
## Summary
Curently, only Red Hat employees were allowed to be in admin list in our jobs in ci.centos.org.
Recently this changes and we can finally add non Red Hat commiters into admin list.
But as this list is managed by another Red Hat team, we need to provide "sponsors" for those people (quote from the Red Hat internal team managing this: "can speak for him in case something comes up?").
 This is how user schema looks like in the code used for generation the jobs:
```
---
$schema: /access/external-user-1.yml

labels: {}

name: Masaki Muranaka
github_username: monaka

sponsors:
- $ref: /teams/che/users/mloriedo.yml
- $ref: /teams/che/users/rhopp.yml
```

@l0rd Should I proceed and add all Eclipse Che commiters to admin list (so they can trigger PR checks for example)?
@l0rd If yes, can I put your name as a "sponsor", as you are Eclipse Che project lead (and Red Hatter)?

**Comment by l0rd** [comment]
Ok
