### ISSUE TITLE
Actions do not seem to stop (QuickPerf examples)

### ISSUE THREAD

**Issue by jeanbisutti** [eclipse-che/che#17284]
Thanks for developing Eclipse Che!

We created an Eclipse Che workspace from [this dev file](https://github.com/quick-perf/quickperf-examples/blob/master/devfile.yaml). 

Running the devfile on che.openshift.io, https://che.openshift.io/f?url=https://github.com/quick-perf/quickperf-examples, 
When we execute an action (che command), most of the time, it seems to never end.

![image](https://user-images.githubusercontent.com/650571/86137784-f180ff80-baed-11ea-9345-b1560654ff7c.png)

**Comment by azatsarynnyy** [comment]
Hello @jeanbisutti 
could you clarify please what exactly do you mean by executing an action

**Comment by sunix** [comment]
a che command yes

**Comment by jeanbisutti** [comment]
For example `JvmAnnotationsJunit4Test.java / @MeasureHeapAllocation`:

![image](https://user-images.githubusercontent.com/14811066/86138822-3bb6b080-baef-11ea-9c31-ddde321fffcf.png)

**Comment by azatsarynnyy** [comment]
There's no project in the provided Devfile.

**Comment by sunix** [comment]
@azatsarynnyy the project is automatically populated with the one setted in url parameter: https://che.openshift.io/f?url=https://github.com/quick-perf/quickperf-examples
it's a quite new feature

**Comment by azatsarynnyy** [comment]
Thanks @sunix 
I've just run the command and it's finished correctly
![image](https://user-images.githubusercontent.com/1636395/86142368-ca312f00-bafb-11ea-8529-800245e2d302.png)

**Comment by jeanbisutti** [comment]
On my side, I have a message saying that the task is already active if I execute the action a second time:
![image](https://user-images.githubusercontent.com/14811066/86143412-ae765a80-baf4-11ea-97be-b891408d34e5.png)

**Comment by azatsarynnyy** [comment]
@jeanbisutti are you running on https://che.openshift.io ?

**Comment by jeanbisutti** [comment]
> @jeanbisutti are you running on https://che.openshift.io ?

I confirm

**Comment by jeanbisutti** [comment]
@azatsarynnyy
> @jeanbisutti are you running on https://che.openshift.io ?

I confirm

**Comment by sunix** [comment]
I also get through this issue from time to time. It's quite random but it happens.

**Comment by sunix** [comment]
Not sure I could reproduce that one recently, I am closing for now. Feel free to reopen if it happens again.
