### ISSUE TITLE
We should mention ephemeral mode / async storage mode in the documentation

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17294]
### Is your enhancement related to a problem? Please describe.

We should mention what's ephemeral mode (and later [async mode](https://github.com/eclipse/che/issues/15384)) is and when/why it can be useful.

### Describe the solution you'd like

I would add a "Troubleshooting storage problems" section in the [troubleshooting for end users](https://www.eclipse.org/che/docs/che-7/troubleshooting-for-che-end-users/).

**Comment by ibuziuk** [comment]
looks like at the moment the only mention about the ephemeral storage is the Hosted Che terms of service - https://www.eclipse.org/che/docs/che-7/hosted-che/#terms-of-service_hosted-che

**Comment by ibuziuk** [comment]
@vparfonov might be good to close https://github.com/eclipse/che/issues/17409 in favour of this one
