### ISSUE TITLE
Che on GCP deployment guide is outdated 

### ISSUE THREAD

**Issue by ismailyenigul** [eclipse-che/che#17296]
I am trying to deploy che on GKE  from https://www.eclipse.org/che/docs/che-7/installing-che-on-google-cloud-platform/
but there are some issues
* nginx deployment is old
I used the following url to deploy it 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.29.0/deploy/static/mandatory.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.29.0/deploy/static/provider/cloud-generic.yaml
```
cert-manager yml links are broken and deployment of cert manager yml files are also out dated.

Please update instructions with the latest version of packages (ingress nginx, cert-manager, che

**Comment by benoitf** [comment]
linking https://github.com/eclipse/che/issues/17295

**Comment by ismailyenigul** [comment]
It seems that I have to create  self-signed-certificate to make it work on GKE.  This part is also missing in the guide

![image](https://user-images.githubusercontent.com/2566232/86397331-4e2a1900-bcac-11ea-97fd-3b2fae47a62c.png)

**Comment by benoitf** [comment]
fixed by https://github.com/eclipse/che-docs/pull/1434
