### ISSUE TITLE
How can I know if a file is in git index or not, from IDE?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#173]
I'm trying the git feature provided by che. But I have a problem that I can't figure out which of the files are in git index just from IDE.

You can see there are three files:

![image](https://cloud.githubusercontent.com/assets/333781/12220838/84d67366-b7bd-11e5-83e9-648a2c1c04a1.png)

and they have the same icons.

I tried to click on the "status" option from "git" menu:

![image](https://cloud.githubusercontent.com/assets/333781/12220860/456d410e-b7be-11e5-8ca3-93788d70c6f1.png)

But it reports an error:

![image](https://cloud.githubusercontent.com/assets/333781/12220851/0a6e5584-b7be-11e5-8fdc-0b6cc54e54b0.png)

So I have to open the terminal tab, use `git status` command:

![image](https://cloud.githubusercontent.com/assets/333781/12220848/d7e2aa70-b7bd-11e5-8165-5c4f62ccccce.png)

I wonder if we can know this information just from IDE and menus, without typing commands?

**Comment by ghost** [comment]
We're currently working on Git improvements. This is most certainly a bug that I will report to engineering team.

As to icons in the project tree that show files git status - that's a very helpful feature indeed.

**Comment by ghost** [comment]
@freewind can you still reproduce this issue?

**Comment by freewind** [comment]
I think this issue can be closed
