### ISSUE TITLE
Add a doc section about how to troubleshoot slow workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17308]
### Is your enhancement related to a problem? Please describe.

We often get complaints about slowness of workspaces: [at startup](https://github.com/eclipse/che/issues/14879) and at runtime. There are some tips & tricks to make them faster that should be shared in the documentation.

### Describe the solution you'd like

In the "Troubleshooting for end-users guide" I would add the following sections:

1. Improve Workspaces Startup Times
- Image puller
- Change storage backend or configure ephemeral mode
- Offline setup
- Reduce the number of plugins
- Reduce the number of public routes
- CDN configuration

2. Improve Workspace Runtime Performances
- Increasing CPU
- Increase memory
- Change storage backend or configure ephemeral mode

**Comment by sunix** [comment]
Looks like we already have a section for image puller.
Not sure if this should go into admin or user guide as it would contain hints for both ....
