### ISSUE TITLE
chectl doesn't update Eclipse Che correctly using a custom CR

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#17312]
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Expected behavior

Actually is not possible to test Eclipse Che Updates in **che operator** side using **minishift** platform and **chectl installation** method. To test updates in operator side first we deploy last stable of Che using chectl. Then we use `chectl server:update --installer=operator --platform=minishift --che-operator-image=quay.io/eclipse/che-operator:<_new-release-version_>  --templates=templates` to update che to the new releasable version. The problem is chectl is not able right now to update all components to the new releaseble version, only update the operator.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [X] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [X] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tolusha** [comment]
Fixed by https://github.com/che-incubator/chectl/pull/923
