### ISSUE TITLE
Image puller doesn't help to cache che-machine-exec image

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#17313]
## Summary
In QE team right now we are developing performance tests for Eclipse Che. To get measure times for workspaces we download container images using kubernetes image puller and then start workspaces with images already in machine. We faced a problem when we try to download machine-exec:
- che-machine-exec is not working in image puller because of all the containers are started with `sleep 30d` command -> https://github.com/che-incubator/kubernetes-image-puller/blob/master/utils/clusterutils.go#L208
- che-machine-exec is builded `FROM scratch` . See : https://github.com/eclipse/che-machine-exec/blob/master/build/dockerfiles/Dockerfile#L48

**Comment by l0rd** [comment]
@ibuziuk one solution is to write a go application that just sleeps, build it statically and copy it in the machine-exec image.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/16689
@flacatus exec  is ~20 MB image and atm it is not expected to be pre pulled  https://www.eclipse.org/che/docs/che-7/caching-images-for-faster-workspace-start/#image-puller-overview_caching-images-for-faster-workspace-start (see The minimal requirements part)
