### ISSUE TITLE
Update Maven/JDK version in Quarkus devfile

### ISSUE THREAD

**Issue by ebramirez** [eclipse-che/che#17311]
Hi,

In this line is stated that the maven version is 3.6.0, while the minimum required to run the latest version of Quarkus is 3.6.2

https://github.com/eclipse/che-devfile-registry/blob/a4cc00362d515c61f3296ae2898d16478a4ca4a3/devfiles/quarkus/meta.yaml#L3

**Comment by sunix** [comment]
PR created

**Comment by sunix** [comment]
fixed with https://github.com/eclipse/che-devfile-registry/pull/260
