### ISSUE TITLE
'Failed to initialize Keycloak' error after workspace start

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17316]
### Describe the bug
On a Hosted Che, we are seeing the issue with Keycloak initialization when the workspace is started. As @ibuziuk reported, this issue is also present in upstream Che. 
**Warn**: I don't have logs from the run, so I searched for them in Kibana. As I don't have permission for an elastic search, I pasted just a link for a search. Please note, that in a week or so the logs can be gone. 
You can see the occurrences of this issue here: https://github.com/redhat-developer/rh-che/issues/1892

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: 7.14.3

### Steps to reproduce

1. Start some workspace from Get Started page
2. Sometimes, when the workspace starts, you can see the red error message in terminal part of IDE. (see screenshot)

### Expected behavior
There should be no error with Keycloak initialization during the workspace startup.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/86242307-c7d6df80-bba4-11ea-82bf-e508719ef7c2.png)

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: Hosted Che

### Eclipse Che Logs
Nothing weird on rh-che logs in Kibana during the workspace running [1]. See all the logs from that time period in the URL [2]. Please note that those logs can be done in week or so. Workspace id workspaceg3ocx7ozicyafgw9.
[1]
![Screenshot from 2020-07-02 12-46-06](https://user-images.githubusercontent.com/29278800/86349819-08486300-bc62-11ea-8922-05e080ad671e.png)

[2] https://logs.dsaas.openshift.com/app/kibana#/discover?notFound=search&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-30T14:11:37.389Z',mode:absolute,to:'2020-06-30T14:17:01.012Z'))&_a=(columns:!(message),index:'project.dsaas-production.129c1244-1b37-11e7-8db9-124160897002.*',interval:auto,query:(query_string:(query:'kubernetes.container_name%3Drhche+AND+workspaceg3ocx7ozicyafgw9')),sort:!('@timestamp',desc))

**Comment by sleshchenko** [comment]
I assume from the shared screenshot that workspace is started and Theia is loaded but Welcome Page in WebView is failed to load for some reason... 
@Katka92 Are you able try refresh a page when you face it? Does refreshing helps to solve an issue?
If so - in short term we could add `Try refresh link` into error to improve UX

**Comment by Katka92** [comment]
@sleshchenko Hi, yes, refreshing the page helps to solve this issue.

**Comment by sleshchenko** [comment]
Well, I did not pay attention that refresh button is already on the error page =)

**Comment by Katka92** [comment]
Ou I'm so sorry, I confused this issue with another one. I haven't seen that issue when running the workspace manually for quite some time, but it's visible in tests. In tests we are not doing a refresh, so I can not say if refreshing helps. I can barely remember that refreshing didn't helped when I saw this last time when testing manually, but I'm not 100% about that. 
The problem I had was that when this error popped up, I was not able to start any command.
