### ISSUE TITLE
Can't scroll to the bottom in workspace plugin and devfile settings

### ISSUE THREAD

**Issue by SpicySpaceman** [eclipse-che/che#17314]
### Describe the bug
In the plugin and devfile settings of a workspace, I'm not able to see the content at the end as it is covered by other elements. It works fine in the projects view of the workspace settings.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
I should be able to see the whole content when scrolling to the bottom

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/10995998/86338593-cc59d180-bc52-11ea-9691-a4bfb2e35dcb.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/17204

@danidoedel feel free to reopen if the referenced issue does not fully cover this issue
