### ISSUE TITLE
Git extension rebasing improvements

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#17327]
During rebasing, I had to over 88 files to delete in every separate message
![image](https://user-images.githubusercontent.com/11182824/86465798-b4c73980-bd75-11ea-9c59-ddc4b9578f5f.png)

**Comment by l0rd** [comment]
@SDAdham do you know how better the UX is when using VS Code?

**Comment by ericwill** [comment]
We are in the process of [updating](https://github.com/eclipse/che/issues/16041) `vscode-git`, which provides the integrated git support. Stay tuned as it may fix this issue.

**Comment by SDAdham** [comment]
thanks @ericwill That'll be very helpful and appreciated

**Comment by ericwill** [comment]
Is this still an issue you experience, even with latest vscode-git in Che?
