### ISSUE TITLE
DevWorkspace failure reason must be propagated through status or events

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17326]
### Is your enhancement related to a problem? Please describe.
Currently, when workspace fails to start - the only place to get error message is controller logs, which are not available for real users. It's needed to propagate DevWorkspace failure reason through status or event.

**Comment by amisevsk** [comment]
We need to decide on the best way to implement this. Some options:

1. Field in `devworkspace.status`, e.g. `.status.message` or similar
    - Pros: simple, easy to incorporate into short description (i.e. via `oc get devworkspace`)
    - Cons: Not clear how field should be used when workspace is not failed (should it be a proxy for the last condition set?)
2. Add another condition to `.status.conditions` that's set when workspace fails
    - Pros: In line with how other workspace information is reported
    - Cons: Unclear how to integrate this into `oc get devworkspace` output
3. Both?

**Comment by sleshchenko** [comment]
I don't find it's the best UX but maybe we could take into account how deployments/pod propagates issues... Isn't it mostly events if we want to get more or less concrete info, like `failed to pull image, unknown blah-blah`?

**Comment by amisevsk** [comment]
Events would be ideal, but I have no idea how events are generated at the moment :)

I've settled on adding a condition for now because it's fairly simple and better than nothing.
