### ISSUE TITLE
Sometimes Account page does not recover correctly after web page is reloaded.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#17322]
### Describe the bug
Sometimes **Account** page on **Dashboard** does not recover correctly after web page is reloaded.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. From Dashboard open Account page.
2. Refresh the web page.
3. Wait for the Account page restored.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift 4.4.6
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_134](https://user-images.githubusercontent.com/7760565/86375758-c97cd200-bc8e-11ea-93a6-cdaabeaed628.png)

### Installation method
   - [x] chectl
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by sleshchenko** [comment]
@SkorikSergey If you are able to provide the response of `/profile` request - it would help a lot in fixing this issue. Thx

**Comment by sleshchenko** [comment]
Parvathy faced it as well on a che.openshift.io when she had networking issue, slack was not stable, a single simple /api/profile request took 3 seconds

<img width="1691" alt="3" src="https://user-images.githubusercontent.com/5887312/106895867-745bdf80-66f9-11eb-9b5f-c97b2cbba0da.png">

It can be reproduced by manually limiting network:
![Screenshot_20210204_150137](https://user-images.githubusercontent.com/5887312/106896175-e59b9280-66f9-11eb-8d29-70ee799651d4.png)

and as far as I see - the new Dashboard correctly displays loader for time data is not loaded.
