### ISSUE TITLE
Not replaced {nbsp} in docs

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#17325]
Some pages in [Eclipse Che Documentation](https://www.eclipse.org/che/docs) contain attribute that is not replaced with the replacement text. 

E.g. screenshot of [creating a workspace from code sample](https://www.eclipse.org/che/docs/che-7/creating-a-workspace-from-code-sample/) page:

![Screenshot 2020-07-03 at 11 42 05](https://user-images.githubusercontent.com/16220722/86450556-676dac80-bd22-11ea-9b42-dda1cc105414.png)

**Comment by rkratky** [comment]
This is weird. It works-renders fine when built locally. I'll revert the change.

**Comment by ibuziuk** [comment]
Should be P1 IMO, reproduced in https://github.com/eclipse/che-docs/pull/1366

**Comment by themr0c** [comment]
I have done a quick fix that reverts to previous behavior (a standard space). I believe it is acceptable as the lifetime of Jekyll is counted on this project.
