### ISSUE TITLE
Can't debug the NodeJS Quickstart

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17329]
### Describe the bug
`NodeJS Express Web Application` stack should provide debug functionality OOTB but it doesn't work as expected.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a Workspace from `NodeJS Express Web Application` stack.
2. Build the app by running `download dependencies` command.
3. Run the app in debug mode with `run the web app (debugging enabled)` command.
4. Start a debug session with `Attach to Remote` debug configuration.

See the notification:
![image](https://user-images.githubusercontent.com/1636395/86470815-dc51de00-bd44-11ea-875d-aeb72b015b8c.png)

After going to the dashboard and adding node-debug plugin, I got another message:
![image](https://user-images.githubusercontent.com/1636395/86471479-225b7180-bd46-11ea-98b1-b6f2166cfff5.png)

### Expected behavior
The debug session should start.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (Hosted Che)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Additional context
Seems debugger knows nothing about the app running in a sidecar.

**Comment by tsmaeder** [comment]
@svor I think this one is fixed in master, right?

**Comment by svor** [comment]
should be fixed by https://github.com/eclipse/che-plugin-registry/pull/506/files

**Comment by azatsarynnyy** [comment]
It works with https://github.com/eclipse/che-plugin-registry/pull/506/files
Thanks!
