### ISSUE TITLE
che pod expect self-signed-cert even if che-tls configured

### ISSUE THREAD

**Issue by ismailyenigul** [eclipse-che/che#17333]
### Describe the bug
using GKE kubernetes cluster 1.16

I created che-tls secret file from a valid wildcard ssl files in che namespace.
I can see that `chectl` can detect it 

```
$ chectl server:start  --devfile-registry-url https://che-devfile-registry.$DOMAIN/ --plugin-registry-url=https://che-plugin-registry.$DOMAIN/v3 --chenamespace=che --templates=$(pwd)/chectl-templates --installer=helm --platform=k8s  --multiuser --tls --domain=$DOMAIN 
Check Eclipse Che TLS certificate...TLS certificate secret found
```
But che pod fails with `  Error: secret "self-signed-cert" not found `  error message.

### Che version
che-server:7.14.2
chectl/7.15.0 darwin-x64 node-v10.21.0

Full ouput
```
✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify remote kubernetes status...done.
    ✔ Check Kubernetes version: Found v1.16.9-gke.6.
    ✔ Verify domain is set...set to dev.ide.mydomain.io.
    ↓ Check if cluster accessible [skipped]
Eclipse Che logs will be available in '/tmp/chectl-logs/1593791428779'
  ✔ Start following logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che 
 ›   (--installer=olm).
  ✔ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.1.2+gd878d4d
    ✔ Create Namespace (che)...does already exist.
    ✔ Check Eclipse Che TLS certificate...TLS certificate secret found
    ✔ Check Cluster Role Binding...does not exists.
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Eclipse Che Helm Chart...done.
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Eclipse Che pod bootstrap
      ✔ scheduling...done.
      ✖ downloading images
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
        starting
      Retrieving Eclipse Che server URL
      Eclipse Che status check
    Show important messages
 ›   Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000
 ›   Installation failed, check logs in '/tmp/chectl-logs/1593791428779'
```

**Comment by ismailyenigul** [comment]
It seems that after 7.14.2, the following lines 
   if (flags['self-signed-cert']) {
      setOptions.push('--set global.tls.useSelfSignedCerts=true')
    }

has been replaced with
``` 
const selfSignedCertSecretExists = !! await this.kubeHelper.getSecret(CHE_TLS_SECRET_NAME, flags.chenamespace)
    setOptions.push(`--set global.tls.useSelfSignedCerts=${selfSignedCertSecretExists}`)
```
and selfSignedCertSecretExists sets true when there is che-tls secret in the namespace?

I deployed che  with chectl 7.14.2
Please check functionality of  the following lines.
```
const selfSignedCertSecretExists = !! await this.kubeHelper.getSecret(CHE_TLS_SECRET_NAME, flags.chenamespace)
 setOptions.push(`--set global.tls.useSelfSignedCerts=${selfSignedCertSecretExists}`)
```
at https://github.com/che-incubator/chectl/blob/7.14.3/src/tasks/installers/helm.ts#L318

**Comment by tolusha** [comment]
It seems like a bug. In case of helm installer we incorrectly set `global.tls.useSelfSignedCerts` flag

**Comment by ismailyenigul** [comment]
yes, better to have another flag say dontcreateselfsignedCert  
the current code only check if  che-tls  or not. Does not have any check whether it is self-signed or not

**Comment by bendavis78** [comment]
I'm also having this issue. Is there a workaround?

**Comment by ismailyenigul** [comment]
Hi @bendavis78 
uninstall the latest chectl release and Use chectl version 7.14.2

**Comment by bendavis78** [comment]
@ishitatsuyuki I'm still getting the timeout error on 7.14.2.  Unfortunately I can't see the logs -- I removed the /tmp/chectl-logs directory, and for some reason the directory is not recreated?

**Comment by tolusha** [comment]
@ismailyenigul 
I have  created a PR https://github.com/che-incubator/chectl/pull/775
The fix is simple, but I have no ability to test it with a real (not self signed cert)

**Comment by ismailyenigul** [comment]
I can test it if I can get a new binary of `chectl` or should I build it manually?

**Comment by tolusha** [comment]
@ismailyenigul 
You can build them manually.
1. branch: `https://github.com/che-incubator/chectl/tree/helmselfsignedcert`
2. launch `yarn` in the root of the project
3 cd `bin`
4. `./run server:start  ....`

**Comment by ismailyenigul** [comment]
Thanks @tolusha 
it works with `helmselfsignedcert` branch

**Comment by tolusha** [comment]
@ismailyenigul 
Thank you for testing.
