### ISSUE TITLE
[che-operator] As a developer, I do not want to manually generate / update a dozen of files for every PR

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17338]
### Is your enhancement related to a problem? Please describe.
While working on a simple fix for https://github.com/eclipse/che/issues/17186 it occurs that contribution to the operator requires quite a few steps - https://github.com/eclipse/che-operator/pull/322#issuecomment-652878309

1. Update comment in che_types.go instead of org_v1_che_crd.yaml
2. Launch olm/update-cr-crd-files.sh to correctly update org_v1_che_crd.yaml
3. Launch olm/update-nightly-olm-files.sh to generate new nighly olm files
4. Set 'spec.metrics.enabled: true' in both (kubernetes and openshift) new clusterserviceversion files
5. Update both new (kubernetes and openshift) clusterserviceversion.yaml.diff files

### Describe the solution you'd like
 As a developer, I do not want to manually generate / update tons of files for every PR. From the 5 commits/steps I want to contibute only the first one - https://github.com/eclipse/che-operator/pull/322/commits (the rest 4 commits should be generated automatically by CI/bot)

### Describe alternatives you've considered
Continue manual error-prone approach with the generation and editing files 

### Additional context
Examples of PRs where the change is simple / one-line fix but still 10+ files are manually generated :
 - https://github.com/eclipse/che-operator/pull/322
 - https://github.com/eclipse/che-operator/pull/186

**Comment by AndrienkoAleksandr** [comment]
We could try to use https://github.com/marketplace/actions/add-commit to automate nightly bundle update.
