### ISSUE TITLE
Investigate why Che Theia build fails on CI

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17332]
### Is your task related to a problem? Please describe.
[`devtools-che-theia-che-build-master`](https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-build-master/) job fails on CentOS CI since Jun 30.
Note, the Che Theia builds pass well on PR checks with both GitHub Workflow and CentOS CI jobs. So, it's not a blocker issue ATM, as it fails on `devtools-che-theia-che-build-master` job only.
But it may indicate some potential issues.

### Describe the solution you'd like
Need to investigate why the CI job started failing despite the fact that there're no changes were introduced in `webpack.config` related code.

### Additional context
`
Error: Please check that you specified the three parameters: '--env.monacopkg', '--env.monacohtmlcontribpkg', '--env.monacocsscontribpkg'\n    at Object.customizeWebpackConfig (/home/theia-dev/theia-source-code/examples/assembly/cdn/webpack-customizer.js:29:15)\n    at Object.<anonymous> (/home/theia-dev/theia-source-code/examples/assembly/cdn/webpack.config.js:38:22)\n    at Module._compile (/home/theia-dev/theia-source-code/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (/home/theia-dev/theia-source-code/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)\n    at WEBPACK_OPTIONS (/home/theia-dev/theia-source-code/node_modules/webpack-cli/bin/convert-argv.js:133:13)\n    at requireConfig (/home/theia-dev/theia-source-code/node_modules/webpack-cli/bin/convert-argv.js:135:6)\n    at /home/theia-dev/theia-source-code/node_modules/webpack-cli/bin/convert-argv.js:142:17\n    at Array.forEach (<anonymous>)\n    at module.exports (/home/theia-dev/theia-source-code/node_modules/webpack-cli/bin/convert-argv.js:140:15)\n    at yargs.parse (/home/theia-dev/theia-source-code/node_modules/webpack-cli/bin/webpack.js:239:39)\n    at Object.parse (/home/theia-dev/theia-source-code/node_modules/yargs/yargs.js:551:18)\n    at /home/theia-dev/theia-source-code/node_modules/webpack-cli/bin/webpack.js:217:8\n    at Object.<anonymous> (/home/theia-dev/theia-source-code/node_modules/webpack-cli/bin/webpack.js:512:3)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/home/theia-dev/theia-source-code/node_modules/webpack/bin/webpack.js:156:2)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[0m[91m@eclipse-che/theia-assembly: Error: webpack exited with an unexpected code: 1.\n    at ChildProcess.<anonymous> (/home/theia-dev/theia-source-code/dev-packages/application-manager/lib/application-process.js:67:28)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[0m@eclipse-che/theia-assembly: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[91m@eclipse-che/theia-assembly: error Command failed with exit code 1.
[0m[91mlerna ERR! execute callback with error
[0m[91mlerna ERR![0m[91m Error: Command failed: yarn run build
`

**Comment by azatsarynnyy** [comment]
From a quick investigation by @benoitf :

working build
```
@eclipse-che/theia-assembly: $ theia build --mode production --config cdn/webpack.config.js --env.cdn=./cdn.json --env.monacopkg=@theia/monaco-editor-core@0.19.3 --env.monacohtmlcontribpkg=monaco-html@2.6.0 --env.monacocsscontribpkg=monaco-css@2.6.0 && yarn run override-vs-loader
```
failed build
```
@eclipse-che/theia-assembly: $ theia build --mode production --config cdn/webpack.config.js --env.cdn=./cdn.json --env.monacopkg=@theia/monaco-editor-core@0.19.3 --env.monacohtmlcontribpkg= --env.monacocsscontribpkg= && yarn run override-vs-loader
```

`--env.monacohtmlcontribpkg=monaco-html@2.6.0 --env.monacocsscontribpkg=monaco-css@2.6.0`
 vs
`--env.monacohtmlcontribpkg= --env.monacocsscontribpkg=`

**Comment by azatsarynnyy** [comment]
I've changed severity to blocker as it prevents from publishing the fresh npm packages to npmjs.org

**Comment by danidoedel** [comment]
Hey @azatsarynnyy, not sure if it's related to this change, that's I'm posting it here instead of creating a new ticket for now. With Theia next the html language server crashes after some time:

```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:473959)
    at n (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:158)
    at Object.<anonymous> (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:520451)
    at n (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:158)
    at Object.<anonymous> (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:38535)
    at n (/default-theia-plugins/vscode-builtin-html-language-features/extension/server/dist/htmlServerMain.js:1:158)
[Info  - 9:47:05 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:638
    throw err;
    ^
```

**Comment by azatsarynnyy** [comment]
Hello @danidoedel 
we'll take a look at it ASAP. Thanks for reporting!

**Comment by azatsarynnyy** [comment]
Thanks @danidoedel 
I've filed the issue https://github.com/eclipse/che/issues/17381
