### ISSUE TITLE
Adapt Che Theia to work with any CHE_PROJECTS_ROOT

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17347]
### Is your task related to a problem? Please describe.
Che Theia expects a user's project directory to be `/projects` only.
It become a problem once the user tries to set `CHE_PROJECTS_ROOT` pointing to some folder that's different from a default one - `/projects`.

### Describe the solution you'd like
Need to adapt Che Theia to work correctly with any `CHE_PROJECTS_ROOT`.

### Additional context
https://github.com/eclipse/che/issues/17260

**Comment by benoitf** [comment]
https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/src/entrypoint.sh#L84

**Comment by sleshchenko** [comment]
Should Dockerfile be adapted as well https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/Dockerfile#L186, if possible?
And we have hard-coded /projects not only on Che Theia side, like https://github.com/che-dockerfiles/che-sidecar-openshift-connector/blob/master/etc/entrypoint.sh#L25

**Comment by benoitf** [comment]
for the Dockerfile there is no way because WORKDIR is an offline instruction while CHE_PROJECTS_ROOT is set at runtime

for the entrypoint, yes should be fixed

**Comment by benoitf** [comment]
But I know that when we open terminals in theia, it asks in which folder to open the terminal (in which project among all workspace roots)

so it should probably happen at this level/time (as at that time, we know the root project)
