### ISSUE TITLE
How to add ssh keys in che.openshift.io

### ISSUE THREAD

**Issue by dhanendras** [eclipse-che/che#17341]

**Comment by ibuziuk** [comment]
@dhanendras https://github.com/eclipse/che-theia/tree/master/plugins/ssh-plugin#theia---ssh-plug-in should help

@vinokurig do we have the ssh generation described in the official docs - https://github.com/eclipse/che-docs ?

**Comment by vparfonov** [comment]
@dhanendras  https://www.eclipse.org/che/docs/che-7/version-control/#accessing-a-git-repository-via-ssh_version-control

**Comment by ibuziuk** [comment]
@dhanendras closing. Feel free to reopen if more clarification is required
