### ISSUE TITLE
Provide documentation on how to install Che with external Keycloak

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17358]
### Is your enhancement related to a problem? Please describe.

We do support an external Keycloak but there is no documentation about how configure it.

### Describe the solution you'd like

Add a section about it [here](https://www.eclipse.org/che/docs/che-7/authenticating-users/#obtaining-the-token-from-keycloak_authenticating-to-the-che-server)

**Comment by davidfestal** [comment]
PR https://github.com/eclipse/che-docs/pull/1452 added a section, but at a lightly different place that seemed appropriate: just before the [following section](https://www.eclipse.org/che/docs/che-7/configuring-authorization/#configuring-prod-short-to-work-without-identity-provider_configuring-authorization) of the *Authorizing users* section in the Administration guide.

**Comment by davidfestal** [comment]
Fixed by https://github.com/eclipse/che-docs/pull/1452
