### ISSUE TITLE
[Hosted Che] Commands in Java with Spring Boot and MongoDB stack fails on quota

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17353]
### Describe the bug
Default commands in `Java with Spring Boot and MongoDB` stack can not be run because of disc quota exceeded.
The issue is not reproduced with upstream che version 7.15.1.
EDIT: Issue is reproducible only with temporary (ephemeral) storage.

### Che version

 - [x] latest 7.15.1
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Login to Hosted Che
2. Go to `Get Started` page, `Get Started` tab
EDIT: 2.a Ensure your temporary storage is turned on.
3. Click `Java with Spring Boot and MongoDB` stack
![Screenshot from 2020-07-08 11-52-51](https://user-images.githubusercontent.com/29278800/86904868-94023980-c111-11ea-879b-48d94f15dd02.png)

4. Wait for the workspace to start
5. Run some default command (e.g. `maven build backend`)
6. Wait for en error to appear in terminal (see pic below)

### Expected behavior
All default commands should be able to run.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/86904738-6917e580-c111-11ea-8bb6-4e758c8e0ed5.png)

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify Hosted Che

**Comment by ibuziuk** [comment]
@Katka92 it fail for both ephemeral and non-ephemeral

**Comment by Katka92** [comment]
@ibuziuk It's reproducible only with ephemeral storage. But when a user clicks on a sample, he/she doesn't have the choice to switch to non-ephemeral storage.

**Comment by Katka92** [comment]
@ibuziuk It's reproducible only with temporary storage.

**Comment by ibuziuk** [comment]
ok, closing in favour of https://github.com/redhat-developer/rh-che/issues/1770 (this is a known issue)
