### ISSUE TITLE
CI check images for plugin and devfile registries

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#17368]
### Is your task related to a problem? Please describe.
We need to have CI check to make sure, that plugin or devfile contributor provided valid images in the yaml content. Because for offline mode Che we need to get image digest, and it is important to have valid images. 

### Describe the solution you'd like
We can use yq to parse images from devfile or plugin meta.yaml:

https://github.com/eclipse/che-devfile-registry/commit/42f410973ad0113707b23818623fd9f2e1492090#diff-ecd1486e9431f7bf21b360ead369c59bR16

https://github.com/eclipse/che-devfile-registry/commit/42f410973ad0113707b23818623fd9f2e1492090#diff-ecd1486e9431f7bf21b360ead369c59bR19

Then We can use skopeo to get image digest:
https://github.com/eclipse/che-operator/blob/adfe6980313acb0d26e30ba796a98b3efb784f73/olm/buildDigestMap.sh#L87

If we can get image digest, than CI check completed successfully, otherwise fail check.

**Comment by amisevsk** [comment]
Setting as P1 priority since it affects restricted networks pretty directly and doesn't seem terribly complicated to implement.

**Comment by flacatus** [comment]
Done!
