### ISSUE TITLE
Should sidecar images be hosted on quay.io and dockerhub only?

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#17369]
## Summary
I think it's a good practice to use images from global public image registries, like quay.io, docker.io and so on for devfile and plugin meta yamls. But is it a good practice for Che to use images from **private** registry in the plugin devfile meta yamls ?

### Context
For now I see we have two images from private registry without registry name: https://github.com/eclipse/che-devfile-registry/blob/db49e19affd7dd0198249e3039a250ceac6d6ff4/devfiles/che4z/devfile.yaml#L39 and https://github.com/eclipse/che-devfile-registry/blob/db49e19affd7dd0198249e3039a250ceac6d6ff4/devfiles/che4z/devfile.yaml#L50, so I ask to make sure, that it's ok. Maybe Am I wrong, but for me it looks like this images stored in the bintray.com private registry provided to some organization.

**Comment by amisevsk** [comment]
We should clarify here that "private" means not docker nor quay.io. The images are still publicly available.

The question is more of "should we require outside contributors to host their images on docker/quay?"

**Comment by ericwill** [comment]
If a community contributor wants to provide a plugin and maintain it, then to me it doesn't make a difference where the image is hosted, as long as it's publicly available.

In the case of the plugins/devfiles you linked, they are maintained (regularly) by developers working for Broadcom. The images are hosted on what appears to be Broadcom's corporate image registry, which is perfectly fine for use in Che IMO.

**Comment by l0rd** [comment]
I have changed the title because the question was not about private registries. And the 2 examples are about a company repo on the public registry bintray.io. And I don't see anything wrong about that.

**Comment by AndrienkoAleksandr** [comment]
Ok, thank, guys.
