### ISSUE TITLE
DevWorkspace controller denies updating workspace service by OpenShift Service CA

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17366]
### Describe the bug
DevWorkspace controller denies updating workspace service by OpenShift Service CA.
OpenShift Service CA actually wants to set two annotation:
```yaml
service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1592636609
service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1592636609
```

It's may be needed to revise how to restrict access to modifying workspace objects.
Maybe we should block changing for service only - selector, ports, controller-related labels and annotations...
Or add service CA service account to exclusion but who knows how much components will need to use labels or annotations.

### Steps to reproduce
```
export WEBHOOK_ENABLED=true
export DEFAULT_ROUTING=openshift-oauth
make deploy
oc apply -f ./samples/cloud-shell.yaml
# Check that webhook server logged: 
# logger":"webhook.workspace.handler","msg":"Denied request to UPDATE resource with kind /v1, Kind=Service by user system:serviceaccount:openshift-service-ca:service-ca: object is owned by workspace and cannot be updated."}
oc logs devworkspace-controller-XXXXXXXXXXXX
```

### Expected behavior
Service CA successfully store info it needs.

**Comment by sleshchenko** [comment]
@amisevsk Do you think https://github.com/devfile/devworkspace-operator/pull/126/commits/65a2afb4ee65deffa89502303fb019c53a997641 fully resolves this issue or do you think it makes sense to rework our current approach to like:
> block changing for service only - selector, ports, controller-related labels and annotations(creator, workspace id...)

?

**Comment by amisevsk** [comment]
The commit does resolve the issue but I suppose we could tighten up what can be modified; that may be a separate issue however. I imagine a sufficiently privileged user could impersonate the service-ca SA to get around webhooks.

**Comment by sleshchenko** [comment]
This issue is solved by https://github.com/devfile/devworkspace-operator/pull/126.
There a dedicated issue for investigation if we can provide generic solution https://github.com/eclipse/che/issues/17536
