### ISSUE TITLE
Typo in devfile-registry hostname override: mentions plugin-registry

### ISSUE THREAD

**Issue by filipkroupa** [eclipse-che/che#17372]
### Describe the bug

Devfile registry received template file for hostname override possibility.
https://github.com/eclipse/che-devfile-registry/blob/master/deploy/kubernetes/che-devfile-registry/templates/_template.tpl
This file in default contains override to plugin-registry (possibly forgotten copy/paste issue). When using helm to deploy  [custom build of devfile-registry](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#building-a-custom-devfile-registry_building-and-running-a-custom-registry-image), CHE_DEVFILE_REGISTRY_URL is overriden and ponting to https://che-plugin-registry-... Which fails the deploy.

### Che version

 - [ ] latest
 - [X] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Build custom devfile registry https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#deploying-the-registries_building-and-running-a-custom-registry-image
2. Deploy custom devfile registry with helm https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#deploying-the-registries_building-and-running-a-custom-registry-image
3. Start Che using chectl with --devfile-registry-url pointing to expected registry URL https://github.com/che-incubator/chectl#chectl-serverstart
4. On Che Dashboard, you'll see that devfiles are not available

### Expected behavior

Expected is normal start of Che using custom built devfile registry.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [X] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [X] other: please specify
    CentOS VM

### Additional context

I've tested with fixing the copy/paste typo and it works

**Comment by benoitf** [comment]
fixed

**Comment by benoitf** [comment]
thanks @filipkroupa

**Comment by monaka** [comment]
Nice catch! @filipkroupa
