### ISSUE TITLE
Support multi-arch in web-terminal-operator

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17373]
### Is your task related to a problem? Please describe.
Currently, the web-terminal-operator only supports `x86_64`. For OpenShift 4.6, we will need to support multiple architectures for all the docker images we build.

### Describe the solution you'd like
Multi-arch builds for:
- [ ] web-terminal-tooling
    - Figure out either how to bundle ~200MB of sources for each arch or a way to reuse multi-arch builds for the tooling we install.
- [ ] web-terminal-exec (can we reuse multi-arch build from machine-exec?)
- [ ] web-terminal-operator

**Comment by sleshchenko** [comment]
is moved to WTO project https://issues.redhat.com/browse/WTO-81
