### ISSUE TITLE
Is it possible to load a browser/browser application inside eclipse che?

### ISSUE THREAD

**Issue by Rahith-RR** [eclipse-che/che#17382]
Lets say, i have a reactJS application running in localhost:8080/dempApp. Can i load this inside Eclipse che web view/view container? Also if possible can anyone please share link of similar sample application?
Thank you

**Comment by ericwill** [comment]
Yes it's possible, if you look on the Getting Started page of the Che dashboard, there should be a NodeJS + React example. If you start this workspace and build + deploy the sample app, you'll see what you are looking for.

There are also other examples with various small Node webapps.

**Comment by Rahith-RR** [comment]
Thank you @ericwill
