### ISSUE TITLE
rework che docs sections

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17386]
### Is your enhancement related to a problem? Please describe.
Even for me, and when I know that the information is somewhere in the doc ... it is very hard to find it. .... so i cannot imagine how it is for a new user ...

### Describe the solution you'd like
There is an idea about divided sections into 'levels'

- Section 1 - Level 1. you heard about it, watching videos, tweets, blog post and getting excited ... be a Che dreamer!
- Section 2 - Level 2. you want to try it: using che.openshift.io, testing few stack, maybe installing it locally or your own cluster ... be a Che first timer!
- Section 3 - Level 3. you want to own it. use it in your projects, creating devfiles, sharing your devfiles/workspaces to others ... be a Che leader!
- Section 4 - Level 4: you want to customize it, adding your favorite vscode extensions to your devfile, contributing to the default che plugin registry or default stacks ... be a Che community member!
- Section 5 - Level 5: you want to contribute, fixing bugs in Che-theia, che, dashboard etc ... be a Che master! (sorry because of the master slave restriction: be a Che contributor!)

**Comment by themr0c** [comment]
As I understand it, to start moving in that direction we have to focus on reorganizing the End-User Guide.

**Comment by boczkowska** [comment]
Docs team Jira https://issues.redhat.com/browse/RHDEVDOCS-2655
