### ISSUE TITLE
How do you enable sharing of workspaces?

### ISSUE THREAD

**Issue by bendavis78** [eclipse-che/che#17387]
I'd like to enable sharing of workspaces between users. As I understand, there should be a "Share" tab in the workspace detail screen. I've installed multi-user che on Azure kubernetes. However, upon logging in as admin and creating a basic workspace, I don't see a Share tab. Do you have to do something specific to enable sharing?

**Comment by gattytto** [comment]
as the comment mentions, it's been disabled and is part of an epic milestone, the comment also points to instructions on how to re-enable organizations feature in dashboard.
https://github.com/eclipse/che/issues/16973#issue-620955917

**Comment by l0rd** [comment]
@bendavis78 @gattytto thanks for opening this. I have opened https://github.com/eclipse/che/issues/17403 because there are users requesting workspace sharing and we should have a document that explains what happened.
