### ISSUE TITLE
Fix Eclipse Che testing Jenkins CI jobs to use 'eclipse-che' namespace 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17395]
### Is your task related to a problem? Please describe.
Eclipse Che is installed into `che` namespace by default, Jenkins CI build scripts rely on that namespace when getting routes, logs etc, for example:
- [in Eclipse Che repo PR/nightly E2E tests on ci.centos]( https://github.com/eclipse/che/blob/3c30d6470352113149e5e4261201b569b0c8ddac/tests/.infra/centos-ci/functional_tests_utils.sh#L427);
- [in Eclipse Che repo PR/nightly E2E tests on CRW Jenkins CI](https://github.com/eclipse/che/blob/3ceb16245fa72722ddf9004747c092c693ee4b28/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile#L340);
- [in che-operator repo E2E tests](https://github.com/eclipse/che-operator/blob/db5dc8c3e3a25d7fe3d3fb55692005889e4855f0/.ci/cico_updates_minishift.sh#L27).

### Describe the solution you'd like
We need to replace `che` namespace name with `eclipse-che`.

### Additional context
It's follow up of https://github.com/eclipse/che/issues/17187

**Comment by rhopp** [comment]
@SkorikSergey @artaleks9 I'm assigning it to you. Please decide who will work on this once you come back from PTO. Thanks!
