### ISSUE TITLE
Restructure folders in web-terminal-operator

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17398]
### Is your task related to a problem? Please describe.
We currently have a fairly large number of gitignored folders at the top level of the web-terminal-operator repo, and it can be confusing to sort through which folders are used for what (e.g. there is `/manifests` and `/generated/manifests`. This could potentially become more confusing if we end up adding even more ignore directories to the repo.

### Describe the solution you'd like
Reorganize folders so that `dependencies` contains all dependent ignored code, and `generated` contains all generated ignored code:

```
./devworkspace-dependencies  -> ./dependencies/combined
./devworkspace-operator      -> ./dependencies/operator
./devworkspace-crds          -> ./dependencies/crds
./generated                  -> ./generated/???
./exported-manifests         -> ./generated/exported-manifests
```

### Additional context
https://github.com/redhat-developer/web-terminal-operator/pull/8#discussion_r454550778

**Comment by JPinkney** [comment]
Fixed by https://github.com/redhat-developer/web-terminal-operator/pull/64
