### ISSUE TITLE
Add a contribute link on Che docs

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17405]
### Is your task related to a problem? Please describe.

There is no link to edit the documentation for users that would like to help.

### Describe the solution you'd like

Add an edit/contribute button on the documentation header.

**Comment by skabashnyuk** [comment]
@l0rd  Where do you want to put the link? 
-  https://github.com/eclipse/che/blob/master/README.md
- Index page https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/  aka https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc

**Comment by l0rd** [comment]
I was thinking about the header of the documentation website:

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/606959/88164506-81f5c000-cc14-11ea-9918-6fd842ca8588.png">

Replacing the `Source Code` link (that currently points to eclipse/che...) with a `Contribute` link.

Does that make sense?

**Comment by skabashnyuk** [comment]
>Does that make sense?

Looks reasonable to me.
