### ISSUE TITLE
Mention how to enable workspace sharing (and its risks) in docs

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17403]
### Is your enhancement related to a problem? Please describe.

Organisations and workspace sharing are disabled from the dashboard. Documentation doesn't mention how to enable that and the reason why it's disabled by default and we discourage it.

### Describe the solution you'd like

We should mention how [organisations and sharing can be enabled](https://github.com/eclipse/che-dashboard#configurability).

For workspace sharing we should explain that it's disabled because of the security risks associated with it and mention that sharing a workspace is possible via devfile and add a link to this WIP issue https://github.com/eclipse/che/issues/16875. 

For organizations we should mention that the old model was designed to run on a docker infrastructure and that we are still analysing how to implement organisations properly on Kubernetes but that it's likely that it will leverage Kubernetes resource limits and requests (something that is currently possible manually).

**Comment by tomgeorge** [comment]
@l0rd does this require building a custom che-theia with an updated `product.json` as per (https://www.eclipse.org/che/docs/che-7/branding-che-theia/)[Branding Che-Theia]?

**Comment by tomgeorge** [comment]
Can you elaborate on some of the security risks involved with enabling sharing?

**Comment by l0rd** [comment]
@tomgeorge when sharing a workspace any secret that is mounted on the workspace containers will be shared as well (as ssh key pairs, Kubernetes and GitHub tokens etc...). In most enterprises sharing those personal information is not allowed.

**Comment by Dracks977** [comment]
how to share with api some workspace ?

**Comment by boczkowska** [comment]
Docs Jira issue: https://issues.redhat.com/browse/RHDEVDOCS-2574

**Comment by monaka** [comment]
It looks pages for organizations are removed in the new react-based dashboard.
So I guess nobody can operate it via the dashboard UI. (Even though APIs are still alive.)

**Comment by sleshchenko** [comment]
@monaka that's true. Thanks for catching it.
So, closing this issue and if anybody needs an ability to share the workspace, new issue should be created/or contribution provided to implement it on the new React-based dashboard.

@Dracks977 Here you should be able to find info how to archive the same with Rest API, or Swagger UI Che provides
https://www.eclipse.org/che/docs/che-7/administration-guide/authorizing-users/
Feel free to ask if it's not clear enough.

**Comment by sympatheticmoose** [comment]
There is still value in having this documented even whilst it cannot be enabled through the dashboard. We wanted to be able to explain why the functionality was disabled and how a user could choose to enable if they are comfortable with the risks.

**Comment by tracetechnical** [comment]
This is missing from the documentation.
