### ISSUE TITLE
[documentation] Add documentation about Asynchronous Storage feature 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#17409]
### Describe the solution you'd like
Write documentation about  Asynchronous Storage feature provided by PR's:

- https://github.com/eclipse/che/pull/16972 
- https://github.com/eclipse/che-theia/pull/771
- https://github.com/eclipse/che-plugin-registry/pull/525

**Comment by ibuziuk** [comment]
@vparfonov are you ok to close this issue in favour of https://github.com/eclipse/che/issues/17294 ?

**Comment by vparfonov** [comment]
done
