### ISSUE TITLE
How to create a custom menu using che-theia plugin ? If it is possible please guide us or share a sample application 

### ISSUE THREAD

**Issue by renjith8710github** [eclipse-che/che#17402]

**Comment by renjith8710github** [comment]
Hi I am new to Che-theia plugin development.
I could create a custom menu on the explorer of the IDE . Is it possible to create custom menu on the top ?
Could you explain anyone that what are the difference between front end and back end plugin ?

**Comment by RomanNikitenko** [comment]
I think we have similar question https://github.com/eclipse/che/issues/17478
I provided some info about the topic here: https://github.com/eclipse/che/issues/17478#issuecomment-663486137

Please take a look.
