### ISSUE TITLE
Errors in workspace after checking out (missing jdt dependencies)

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#1740]
I have used the Yatta Profile to setup the workspace. After completing, there are around 3000 compilation errors, because the JDT dependencies cannot be resolved (che-core-ide-app, che-plugin-java-debugger-server, che-plugin-java-plain-server and che-plugin-maven-server)

**Che version:**    master
**OS and version:** Linux
**Che install:**  Yatta Installer

**Comment by ghost** [comment]
@JonasHelming the issue is most likely caused by missing modules - Yatta installer does not seem to import all Che modules.

**Comment by JonasHelming** [comment]
So who is repsonsible for fixing this then?

**Comment by zenobios** [comment]
We updated the Yatta Profile https://marketplace.yatta.de/profiles/iQBd to import all required dependencies. Additionally, the maven build is triggered to generate some required code.

Please update your profile. You should see an "Update" icon right next to the profile entry within the launcher (see https://marketplace.yatta.de/profiles/help#update for addtional help).

**Comment by JonasHelming** [comment]
Thanks, seem to work now. A plugin named "Takari" has been added in the new version. I forces me to publish usage data. Can we somehow avoid this?

**Comment by zenobios** [comment]
@JonasHelming I've also seen this. This was introduced by installing an m2e connector to avoid some problems reported by Maven concerning the pom.xml.

I think we can just remove the plugin from the profile and introduce a maven lifecycle mapping to ignore the reported maven problems.

I'll have a look into that.

**Comment by slemeur** [comment]
@zenobios Sounds like a good idea.

**Comment by zenobios** [comment]
We removed the Maven Development Tools which had the "Takari" plugin as a dependency and introduced some new m2e lifecycle mappings to ignore reported m2e problems.

**Comment by TylerJewell** [comment]
Thanks for helping on this - going to close this for now.  Ok to reopen if we see another issue appear.
