### ISSUE TITLE
Improved "exit code" interpretations

### ISSUE THREAD

**Issue by jamesfalkner** [eclipse-che/che#17412]
### Is your enhancement related to a problem? Please describe.
When a command successfully exits, a popup message shows:

![Screen Shot 2020-07-15 at 7 53 40 AM](https://user-images.githubusercontent.com/861894/87542127-75032a80-c670-11ea-9250-38c469993517.png)

Several of my teammates have complained "has exited with code 0" is alarming, since typically errors are associated with "error codes" or "codes", and if you don't understand the notion of a shell's exit status, you may interpret _any_ message about "codes" to be "error codes" and therefore an error occurred.
 
### Describe the solution you'd like
In the case of "exit code 0", I would recommend the message say something like "has successfully completed" with no mention of "exit code". Simply putting "success" (or some variant of that word) will make it clearer that the thing worked.

### Describe alternatives you've considered
Teach people about exit codes and why "0" means success.

**Comment by ericwill** [comment]
Thanks for the bug report, I agree this could be improved upon.

**Comment by jamesfalkner** [comment]
It appears this no longer pops up for exit code 0 so closing
