### ISSUE TITLE
How to implement nested tree structure in tree view?

### ISSUE THREAD

**Issue by Rahith-RR** [eclipse-che/che#17417]
Hi, I am new to Che and typescript.
I was trying to understand/Implement a sample tree view plugin from GitHub: https://github.com/eclipse/che-theia-samples/tree/master/samples/tree-view-sample-plugin

I tried to change code to **make it to a nested tree view structure** but was not able to. 
I came across various examples in React-JavaScript, but need to change the following area of code to make a nested tree structure which is in typescript:-

const comments: Map<string, string[]> = new Map<string, string[]>();
comments.set('Ann', ['Great plugin!', 'Can you share the link to this example?']);
comments.set('Yevhen', ['Cleanup your code please']);
comments.set('Sun', ['Do not forget about docs']);

![image](https://user-images.githubusercontent.com/67456372/87559262-b0850f80-c6d7-11ea-8093-53ee654f0926.png)

Can anyone please help?

**Comment by tsmaeder** [comment]
@Rahith-RR this seems like a pure Theia question: you'll probably have more luck finding docs over at https://github.com/eclipse-theia/theia
