### ISSUE TITLE
Adapt Asynchronous Storage feature to 'unique' and 'per-workspace' PVC strategies

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#17410]
### Is your task related to a problem? Please describe.

In initial PR https://github.com/eclipse/che/pull/16972 it enabled only for 'common' PVC strategy

**Comment by nickboldt** [comment]
reopening because this is a N&N item so it shouldn't be autoclosed. Or, if it's a dead issue we won't do, then it's also not N&N. 

@ibuziuk feel free to re-resolve and/or remove the N&N label.

**Comment by nickboldt** [comment]
Florent says, "n&n should not be applied to an open issue anyway so right fix would be to unset n&n on open issues"
