### ISSUE TITLE
Workspace should update project by path instead by name

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1741]
As project name is not a mandatory attribute for the project, we need to change behaviour of updating project on the workspace {{org.eclipse.che.api.workspace.server.WorkspaceService#updateProject}} to search project by its path, not by name, otherwise we can get a NPE.
`
if (!workspace.getConfig().getProjects().removeIf(project -> project.getName().equals(update.getName()))) {
      throw new NotFoundException("Workspace " + id + " doesn't contain project " + update.getName());
}
`

**Comment by voievodin** [comment]
Already [fixed](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L635-L639) by #954
