### ISSUE TITLE
Add a button or link in che-docs pull-request to open it in workspaces.openshift.com for review

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#17424]
As a reviewer, I would like to have a button or link in GitHub Web UI, in each che-docs pull-request, to open the pull-request in Hosted Che for review.

For a starter: how to open a pull-request with a factory?

I failed with this: https://workspaces.openshift.com/f?url=https://github.com/eclipse/che-docs/pull/1403 (result: `Internal Server Error`).

Then, how do we implement this in GitHub?

As a subsidiary task, explain the procedure in the End-User Guide.

Any help appreciated.

**Comment by l0rd** [comment]
`che.openshift.io` link in PR checks details currently allows to open the PR in https://che.openshift.io.  

![image](https://user-images.githubusercontent.com/606959/87863267-b5f18c80-c959-11ea-9433-7e5f11d4a8fe.png)

However I agree that a comment with the factory link would be much better.

**Comment by l0rd** [comment]
cc @benoitf

**Comment by themr0c** [comment]
cc: @sunix

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-2844

**Comment by l0rd** [comment]
This looks fixed:
 
![image](https://user-images.githubusercontent.com/606959/134027503-438072f2-0f0d-4798-9609-982ddca96a8d.png)

Closing
