### ISSUE TITLE
How can i create a custom file with custom extension and link it with the editor

### ISSUE THREAD

**Issue by Rahith-RR** [eclipse-che/che#17439]
How can i create a custom file with custom extension and link it with the editor (need to open custom contents for the file) using eclipse Che

**Comment by ibuziuk** [comment]
sorry, it is not clear what are you trying to achieve. is it somehow related to - https://github.com/eclipse/che/issues/17438 ?

if yes, are you ok to close this issue and properly describe the use-case in https://github.com/eclipse/che/issues/17438 ?

**Comment by Rahith-RR** [comment]
yes. It is related. we can close this. i have commented our usecase in #17438 .
