### ISSUE TITLE
How can I create a custom view container with the functionality of 'PREVIEW'?

### ISSUE THREAD

**Issue by Rahith-RR** [eclipse-che/che#17438]
How can I create a custom view container with the functionality of 'PREVIEW'? I would like to load the URL inside the custom view container but with some customization also required.

**Comment by ibuziuk** [comment]
@Rahith-RR hi, could you please clarify the use-case and functionality of the plugin a bit more?
@ericwill could you please to the docs for creating a custom plugin and contributing it to the plugin-registtry?

**Comment by Rahith-RR** [comment]
Hi @ibuziuk 
Usecase:-
1. Need to create a file with custom extension. While clicking on the file, i need to open a ReactJS application. This is the actual use case.

**Comment by ibuziuk** [comment]
@Rahith-RR could you please clarify a bit more - what is the intention of this functionality? Do you happen to have some mockups?

**Comment by Rahith-RR** [comment]
Hi @ibuziuk , Our functionality need is:- we have a react js application, it will contain drag and drop of certain elements and allows to create some templates.

**Comment by ibuziuk** [comment]
So, it is some sort of WYSIWYG editor for react js development?

**Comment by Rahith-RR** [comment]
React js implementation dosen't matter here. not with the specified editor
