### ISSUE TITLE
Instructions to add a certificate in Firefox are incomplete

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17437]
### Describe the bug

The section [Add Certificates to Firefox](https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#adding-certificates-to-firefox) mentions:

```
(...)
 d. Click the View Certificate button on the Security tab.
 e. Click the PEM (cert) link and save the certificate.
(...)
```

But trying to import the certificate downloaded following those instructions fails:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/606959/87888540-cb37eb00-ca2d-11ea-9eb3-2943647ff05e.png">

The Certificate View has 2 tabs and importing the certificate from the link on the second tab works fine:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/606959/87888337-b1e26f00-ca2c-11ea-8e66-b2bcf9c0c45b.png">

Hence the instructions should be:

```
(...)
 d. Click the View Certificate button on the Security tab.
 e. Select the ingress tab
 f. Click the PEM (cert) link and save the certificate.
(...)
```

### Che version

Nightly Che using Firefox Developer Edition 79.0b9 (64-bit)

### Runtime

Openshift 4.5.2

### Installation method
 
```
chectl server:start --installer=operator \
                    --platform=openshift \
                          -n "${CHE_SERVER_PROJECT}"
```

### Environment
   - Cloud
       - Amazon

**Comment by tolusha** [comment]
Depends on https://github.com/eclipse/che/issues/16773
Workaround https://github.com/eclipse/che/issues/16926#issuecomment-628504281

**Comment by l0rd** [comment]
@tolusha why do you think that this issue (import the certificate from the browser) is related to #16926 (importing the certificate provided by chectl) or even #16773 (`self-signed-caertificate` secret). The issue I am describing happens when you try to import the certificate of the openshift console so I don't think there is nothing wrong about it and there is no need to edit it: we just need to document to download the right certificate.

**Comment by tolusha** [comment]
@l0rd 
I see I misread the description.
