### ISSUE TITLE
Some maven artifacts inacessible during builds

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#17442]
### Describe the bug
This is a problem that occures rarely, but it may be just the maven repo inconsistency.

This is related to the tracking issue ([link](https://github.com/redhat-developer/rh-che/issues/1943))

### Che version
 - [x] latest
 - [ ] nightly
 - [x] other: 7.16.0, 7.15.1

### Steps to reproduce
* Try to build the default maven project ([link](https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/java-maven))
* Very rarely an artifact will become inaccessible and the build will fail

### Expected behavior
* Build finishes without failure

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
```
Version
OpenShift Master:
v3.11.154
Kubernetes Master:
v1.11.0+d4cacc0
OpenShift Web Console:
v3.11.154

Client Version: openshift-clients-4.3-31-gc25fb9c7
Kubernetes Version: v1.11.0+d4cacc0
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/16451875/87935079-ade83880-ca90-11ea-8f1b-1c4d4a84afcd.png)
![image](https://user-images.githubusercontent.com/16451875/87935093-b2acec80-ca90-11ea-9b8d-06123c49c081.png)
![image](https://user-images.githubusercontent.com/16451875/87935104-b771a080-ca90-11ea-89e2-d10198a99049.png)
![image](https://user-images.githubusercontent.com/16451875/87937099-54820880-ca94-11ea-9846-e40c3efb7cd6.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) che.OSIO
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by ibuziuk** [comment]
@ScrewTSW this looks like a maven central issue. What is the expectation in this regard? can you reproduce the very same issue manually?
 cc: @ericwill

**Comment by ericwill** [comment]
@ScrewTSW have you seen this issue lately?
