### ISSUE TITLE
Link to load devfile should load the devfile from the appropriate branch

### ISSUE THREAD

**Issue by edeandrea** [eclipse-che/che#17448]
### Che version

 - [X] latest - `7.15.2`
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Log into OpenShift cluster as cluster admin
1. Deploy the che operator as well as a `CheCluster` instance, then wait for it to spin up
1. If logged in as administrator, on left side menu change 'adminstrator' to 'developer' to show `topology` link on left nav bar.
1. Click **+Add**
1. Click **From Git**
1. In the **Git Repo URL** field, enter https://github.com/edeandrea/summit-lab-spring-music
1. Expand **Show Advanced Git Options**
1. In the **Git Reference field**, enter **pipeline**
1. In the **Resources** section, select **Deployment Config**
1. In the **Advanced Options** section, click the word **Labels** and enter the label **app.openshift.io/runtime=spring** and hit enter
1. Click **Create**
1. Wait for build & deployment to complete
1. Click the **che** logo on the deployment (see attached screenshot)

### Expected behavior
After going through the steps to reproduce above, the URL that is generated for the icon is `https://<che-url>/dashboard/#/load-factory/?url=https://github.com/edeandrea/summit-lab-spring-music&policies.create=peruser` but it should be `https://<che-url>/dashboard/#/load-factory/?url=https://github.com/edeandrea/summit-lab-spring-music/tree/pipeline&policies.create=peruser` since the application was added using the **pipeline** branch. It should respect that and hence load the workspace using the devfile on the **pipeline** branch and not the **master** branch.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
Client Version: openshift-clients-4.4.0-202004250654
Server Version: 4.3.13
Kubernetes Version: v1.16.2
```

### Screenshots
![Screen Shot 2020-07-20 at 3 55 20 PM](https://user-images.githubusercontent.com/363447/87980389-8d74aa00-caa1-11ea-81c7-4a155a432ac5.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [X] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [X] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
Hello @edeandrea . thank you for this report. As I can see the link is generated on OpenShift Console https://github.com/openshift/console/ . I belive the issue has to be created here https://github.com/openshift/console/issues

**Comment by edeandrea** [comment]
I've also posted this as openshift/console#6077

**Comment by sleshchenko** [comment]
Closing it since after link is changed on OpenShift Console side everything should work as expected. Tested on https://che.openshift.io/dashboard/#/load-factory/?url=https://github.com/edeandrea/summit-lab-spring-music/tree/pipeline&policies.create=peruse
