### ISSUE TITLE
NodeJS MongoDB Web Application doesn't have a functioning LS

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#17446]
### Describe the bug
LS for JS/TS is initialized, but the functionality is not being provided.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: please specify 7.16.0

### Steps to reproduce
* Start a NodeJS MongoDB Web Application example ([link](https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs-mongo))
* Open any .js file
* Wait for LS to initialize
* Try any LS functionality (error highlighting, code completion, code navigation) - does not function

### Expected behavior
LS will provide the required functionality

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
```
Version
OpenShift Master:
v3.11.154
Kubernetes Master:
v1.11.0+d4cacc0
OpenShift Web Console:
v3.11.154

Client Version: openshift-clients-4.3-31-gc25fb9c7
Kubernetes Version: v1.11.0+d4cacc0
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
N/A

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) che.OSIO
   - [ ] other: please specify

### Eclipse Che Logs
https://pastebin.com/yU1zr0V1

### Additional context
N/A

**Comment by ericwill** [comment]
Is this the latest iteration of #15919?

**Comment by Katka92** [comment]
Can not reproduce. Closing.
