### ISSUE TITLE
Install git in quay.io/eclipse/che-docs

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17450]
### Is your enhancement related to a problem? Please describe.
The `quay.io/eclipse/che-docs` image is used as the main dev container in the [che-docs devfile](https://github.com/eclipse/che-docs/blob/231c92fe5ca4dfbb57bdb1c124c31cc787142417/devfile.yaml#L8). When using a workspace I expect to be able to perform git operations by opening a Theia terminal in a developer container.

### Describe the solution you'd like
Install git in the dev container for che-docs

### Describe alternatives you've considered
Git is installed in the Theia container, so it's possible to work-around the issue by opening a terminal in the Theia tooling container. Using the Theia git UI also works.

**Comment by l0rd** [comment]
[GitHub cli](https://github.com/cli/cli) would be useful too
