### ISSUE TITLE
Getting Started NodeJS+Yarn fails to run

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17453]
### Describe the bug
When the workspace is started, the predefined commands can not be run. The first command that needs to be run is `install all required dependencies`. 

The error is shown in terminal:
```
error Could not write file "/projects/react-web-app/yarn-error.log": "errmap.get is not a function or its return value is not iterable"`
error An unexpected error occurred: "Unknown system error -122: Unknown system error -122, copyfile '/home/user/.cache/yarn/v4/npm-@babel-types-7.10.5-d88ae7e2fde86bfbfe851d4d81afa70a997b5d15/node_modules/@babel/types/lib/definitions/utils.js' -> '/projects/react-web-app/node_modules/@babel/plugin-syntax-object-rest-spread/node_modules/@babel/types/lib/definitions/utils.js'".
```

### Che version

 - [x] latest 7.16.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Go to `Get Started` page and `Get Started` tab
2. Cick on `NodeJS Web Application based on Yarn`
3. Run command `install all required dependencies`

### Expected behavior
The commands should work correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) 4.4
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
EDIT: Updated image
![Screenshot from 2020-07-22 11-32-44](https://user-images.githubusercontent.com/29278800/88160637-355bb600-cc0f-11ea-8883-a9590f420e64.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify OpenStack

**Comment by tsmaeder** [comment]
The error in the output says "no space left on device".

**Comment by Katka92** [comment]
@tsmaeder Oh damn, sorry, I posted the wrong image. I've updated that.

**Comment by tsmaeder** [comment]
Darn...I was already starting to yell "duplicate" ;-)

**Comment by benoitf** [comment]
I already had this issue, it's related to an out-of-space on the disk in ephemeral case

yarn command download node_modules but fail to download more as ephemeral storage is reached

to validate that, when you see this message, try to do:

```
echo "test" > /projects/foo
```
it will display a message indicating that there is no more space

**Comment by Katka92** [comment]
@benoitf Thank you for your advice, I verified that it is quota exceeded issue - it's also present in 7.17.2 on Hosted Che. It happens for ephemeral storage.
When I run the workspace in the non-ephemeral storage, I get this error:
![Screenshot from 2020-08-27 11-47-49](https://user-images.githubusercontent.com/29278800/91426029-3b6f3300-e85c-11ea-9aa6-b24fc68e55a4.png)
cc @ibuziuk can it also be related to the storage issues?

**Comment by ericwill** [comment]
Thanks for the fix @svor
