### ISSUE TITLE
[devworkspace-controller] Propagate errors from provisioning components and/or workspaceRoutings to condition

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17455]
### Is your enhancement related to a problem? Please describe.
With PR https://github.com/devfile/devworkspace-operator/pull/138 some failure reasons are propagated to the user, but the messages for Components and Routing failures are generic and not helpful.

### Describe the solution you'd like
We need to propagate the specific reason the controller cannot reconcile Components and WorkspaceRoutings into the condition message.

**Comment by l0rd** [comment]
@amisevsk I am closing this issue because the linked PR is merged. Reopen if the work is not completed yet.

**Comment by sleshchenko** [comment]
The linked PR introduces initial error propagation while this issue is about implementing good failure propagation from multiple components and workspaceRouting.

**Comment by amisevsk** [comment]
We should consider migrating this issue to the devworkspace-operator repo.

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1866
