### ISSUE TITLE
None of the containers in the che docs factory workspace have git installed

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#17456]
### Describe the bug

You can't create a new branch as part of the che-docs [contributing guide](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc) in a che workspace because there is no version of `git` installed in any of the containers.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify

### Steps to reproduce

Follow the factory link to che docs: https://che.openshift.io/factory?url=https://github.com/<github-handle>/che-docs/<branch-name>/tree/

Open  a `che-docs-dev` container terminal, and attempt to create a new git branch

### Expected behavior

I am able to use git commands to contribute code to che-docs

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
It seems to be duplicate for https://github.com/eclipse/che/issues/17450.
@tomgeorge If so - please close it and feel free to add missing info in 17450 with a comment.

**Comment by tomgeorge** [comment]
It is a duplicate.  Sorry for not checking earlier! Closing
