### ISSUE TITLE
Getting workspaces logs should be in end-user guide

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17459]
### Is your enhancement related to a problem? Please describe.

Page [viewing Che workspaces logs](https://www.eclipse.org/che/docs/che-7/viewing-che-workspaces-logs/) is currently in the Che Admin Guide. But those infos are gold for an end-user that tries to troubleshoot a workspace that is failing to start. And he will never find those in the section dedicated to him.

### Describe the solution you'd like

Move a that page in the end-user guide. Probably in [troubleshooting for che end users](https://www.eclipse.org/che/docs/che-7/troubleshooting-for-che-end-users/https://www.eclipse.org/che/docs/che-7/troubleshooting-for-che-end-users/) section.

Mention a link to that page from the admin guide (just in case).

**Comment by amisevsk** [comment]
Not sure the status of this issue: PR https://github.com/eclipse/che-docs/pull/1431 was closed without merging but the currently deployed docs still show instructions for workspace logs in the admin guide.

**Comment by rkratky** [comment]
@l0rd, this would be assuming that the end user is interested in debugging failing workspaces. I don't think we should do that. Workspaces should just work for the end user. When workspaces fail, the product fails -- that's an issue for the administrator to resolve, not the end-user developer who just wants to code.

I suggest we include links to the AG in EUG, not move the content.

**Comment by l0rd** [comment]
@rkratky As a user, if there is something that is not working as expected, I will want to have access to the logs of my IDE to see what's going on there. It may be something related to my devfile, to the application that I am testing, to my git configuration or the connection to an external service I am using from my IDE. A Che admin may not have the context to investigate the problem and may even not have access to the logs (logs are in the user namespace). We also ask users to provide their IDE logs when opening a bug. Administrators have access to the che server, keycloak, registries and postgres logs (something a user doesn't have access to) but should not analyse anomalies on users IDEs (given that they have access to the logs). That said I hope you agree that it is critical to move that part to the user guide.

**Comment by rkratky** [comment]
Ack, thanks for the clarification, @l0rd.

**Comment by themr0c** [comment]
I believe the merged PR fixes the issue. @l0rd, please reopen if it doesn't meet requirements

See: https://www.eclipse.org/che/docs/che-7/end-user-guide/viewing-che-workspaces-logs/

**Comment by l0rd** [comment]
@themr0c [viewing plugin broker logs](https://www.eclipse.org/che/docs/che-7/administration-guide/viewing-plug-in-broker-logs/) should be in end user guide too. As well as collecting [workspace logs using chectl](https://www.eclipse.org/che/docs/che-7/administration-guide/collecting-logs-using-chectl/). I cannot find those info there so reopening this issue.

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-2512
