### ISSUE TITLE
Che-Theia UI does not list option to git checkout branch

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17474]
### Describe the bug
The Che-Theia UI does not show an option to check out a different branch from the current one. It's necessary to use the command palette for this.

![Screenshot from 2020-07-23 13-50-10](https://user-images.githubusercontent.com/16168279/88332267-7f19ce80-cceb-11ea-9982-9f4df533cc6d.png)

### Che version
Hosted Che (`7.16.0`)
`Che-Theia@8740bbe using Theia@a0e635aed`

### Steps to reproduce
Start a workspace, open the Source Control panel (`ctrl` + `shift` + `g`), and try to check out a different branch

### Expected behavior
The similar menu for VS Code had a "Checkout to..." option:

![Screenshot from 2020-07-23 13-52-48](https://user-images.githubusercontent.com/16168279/88332494-e6378300-cceb-11ea-8194-888ce543ea03.png)

### Additional Info
The functionality *does* exist in Che-Theia, as it's available via the command palette.

**Comment by ericwill** [comment]
I believe this is because the `vscode-git` built-in we use is out of date. We are waiting for upstream Theia PR's to be merged so we can update it in Che, see #16041 and our [sprint plan](https://github.com/eclipse/che/issues/17418).

**Comment by ericwill** [comment]
Fixed by #16041
