### ISSUE TITLE
Che-Theia cannot access clipboard on Chrome

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17475]
### Describe the bug
Using the `Copy Path` context menu option (`ctrl-alt-c`) in the Theia Explorer UI briefly shows a toast `Access to the clipboard is denied. Check your browser's permission.`. This message is shown when the permissions is "Ask" (the default), and when explicitly set to "Allow"

### Che version
Hosted Che 7.16.0
`Che-Theia@8740bbe using Theia@a0e635aed`
Chrome `Version 84.0.4147.89 (Official Build) (64-bit)`

### Steps to reproduce
Open a workspace, open file explorer, and try to copy relative path:
![Peek 2020-07-23 14-07](https://user-images.githubusercontent.com/16168279/88333740-f81a2580-cced-11ea-8b2a-f14d842177ac.gif)

### Expected behavior
If necessary, Theia prompts in browser for clipboard access, and copies to clipboard.

### Eclipse Che Logs
I couldn't find any output in Theia logs when error occurs

**Comment by amisevsk** [comment]
Setting as P1 since this is a step in the [che-docs contribution flow](https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc#building-and-validating-the-documentation-using-che)

**Comment by panneer26** [comment]
facing same issue

**Comment by azatsarynnyy** [comment]
I can't reproduce it on Google Chrome Version 90.0.4430.212

**Comment by panneer26** [comment]
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

due to this chromium feature, browser restricting the clipboard access
![image](https://user-images.githubusercontent.com/40835567/122217241-dbb94580-ceca-11eb-9503-ae6dda47ba38.png)

**Comment by Panneerselvam-D** [comment]
https://github.com/eclipse-che/che-dashboard/pull/283
PR raised
