### ISSUE TITLE
[Hosted Che] Webviews not working correctly

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17472]
### Describe the bug
My environment has problems viewing pages containing webviews. When I start the workspace, the welcome page is not shown correctly. Even when reloading the page, I still get an error. The problem is visible also when I install some plugin using webviews and I try to use that. (see pictures sections for gifs).
I tried with Google Chrome v. 81 and 84, both "normal" and incognito window. I was not able to reproduce with Firefox v. 78 (both normal and incognito). I tried different users on different clusters (2, 2a). I tried to clear cache, restart the browser, restart the whole PC - the issue is still the same. 
 
### Che version

 - [x] latest 7.16.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Log in to che.openshift.io
2. Click on one of workspaces examples.
3. Wait for workspace to start.
4. Wait for welcome page (Eclipse Che tab).
(for testing the plugin using webviews:)
5. Install `vscode-didact` plugin.
6. Restart workspace to enable the plugin.
7. Open file tree.
8. At the bottom, click `DIDACT TUTORIALS` -> `Didact`
9. Click on play icon next to `Didact Demo`.

### Expected behavior
Web pages should work correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
Welcome page reload don't fix the problem
![captured](https://user-images.githubusercontent.com/29278800/88286684-6a403980-ccf1-11ea-8aa4-212c15225140.gif)

Plugin using webviews not working

![plugin3](https://user-images.githubusercontent.com/29278800/88287208-46c9be80-ccf2-11ea-87a4-6b8fe7421152.gif)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know **Hosted Che**

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify **Hosted Che**

### Eclipse Che Logs
When trying to reload the page, those logs appear in console and network tab:
![Screenshot from 2020-07-23 15-03-05](https://user-images.githubusercontent.com/29278800/88289509-a4133f00-ccf5-11ea-8678-84bd88595d15.png)

**Comment by ibuziuk** [comment]
@Katka92 is it reproducible against upstream?

**Comment by sunix** [comment]
I have been using the plugin didact in che.openshift.io but had no issue with that.
Setting p2, unless someone else could reproduce. feel free to increase the priority.

**Comment by amisevsk** [comment]
Adding link to Hosted Che issue I opened: https://github.com/redhat-developer/rh-che/issues/1953

**Comment by Katka92** [comment]
@ibuziuk I could not reproduce that on upstream 7.16.0.

**Comment by jeanbisutti** [comment]
We have the same issue with [this devfile](https://github.com/quick-perf/quickperf-examples/pull/28)

**Comment by jeanbisutti** [comment]
In incognito mode:
![image](https://user-images.githubusercontent.com/14811066/90624979-20c40b00-e219-11ea-9e04-5d9b82d86ef8.png)

**Comment by sunix** [comment]
So in last screenshot, the theia ide is not loading, it is spinning forever.
Reproduced in Jean's laptop (chrome + windows) but i couldn't reproduce on mine

**Comment by ibuziuk** [comment]
@sunix could you reproduce the same issue on pure upstream?

**Comment by sunix** [comment]
@ibuziuk no and I couldn't reproduce on my laptop: just Jean's laptop

**Comment by benoitf** [comment]
I reproduce it as well on che.openshift.io

```
Refused to frame 'https://sso.redhat.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

![image](https://user-images.githubusercontent.com/436777/90638896-355ece00-e22e-11ea-8535-daf7969f6651.png)

**Comment by ibuziuk** [comment]
@benoitf @artem wondering if this issue will likely be reproducible when the external keycloak will be used for upstream che / crw ?

**Comment by benoitf** [comment]
Well it's sso.redhat.com that specify this:
```
$ curl -v -L https://sso.redhat.com/

> GET /auth/realms/redhat-external/protocol/saml/clients/legacy-idp-servlets HTTP/1.1
> Host: sso.redhat.com
> User-Agent: curl/7.64.1
...
< Content-Security-Policy: frame-src 'self' *.demdex.net; frame-ancestors 'self'; object-src 'none';
...
```

**Comment by ibuziuk** [comment]
@benoitf ok probably I should create an issue for adding can create an issue for adding `*.openshift.io` to the Content-Security-Policy on the sso end, but wondering why it is not reproducible against all the browsers?

**Comment by sunix** [comment]
@ibuziuk somehow I have it .... now ... (not this morning)
![image](https://user-images.githubusercontent.com/650571/90649304-dbb0d080-e23a-11ea-9483-640fabe5d146.png)

**Comment by sunix** [comment]
@ibuziuk Any updates on this one? It is stopping many plugins to work properly :/ (asciidoc, didact, etc ...)

**Comment by ibuziuk** [comment]
@sunix I can not reproduce the issue anymore against Chrome `85.0.4183.121`. Could you please confirm ?

**Comment by sunix** [comment]
yep couldn't reproduced neither on my side, i can confirm :+1:

**Comment by tomgeorge** [comment]
I ran into the issue described in the [rh-che issue](https://github.com/redhat-developer/rh-che/issues/1953#issuecomment-670077867) that was closed in favor of this today in a Chrome incognito window as well.  My network tab seems to repeatedly try to hit the auth endpoint

![devtools](https://user-images.githubusercontent.com/1291508/95406419-f2d97980-08df-11eb-9ec7-8b9e96189053.png)

**Comment by sunix** [comment]
@tomgeorge maybe worth open a new issue and link to both this and the other https://github.com/redhat-developer/rh-che/issues/1953#issuecomment-670077867 issue. The problem with webviews is solved so I guess the infinite redirect is related to another root cause.

**Comment by ibuziuk** [comment]
@tomgeorge I think we need to update the Troubleshooting doc - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#_troubleshooting

My understanding is that disabling "Block Third-Party Cookies" fixes the issue in incognito

**Comment by sunix** [comment]
@ibuziuk maybe it is worth creating a new issue. If block Third-Party Cookie is causing issues. Can't we detect that and show a proper error message with a suggestion how to fix it?

**Comment by ibuziuk** [comment]
@sunix for now I just document it to the Troubleshooting instructions -  https://github.com/eclipse/che-docs/pull/1641
