### ISSUE TITLE
Preview panel and workspace commands panel share size

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17476]
### Describe the bug
Opening a preview URL in the side panel (as prompted by Che-Theia) reuses the commands panel, causing any size changes to propagate to the commands panel:

![Peek 2020-07-23 14-21](https://user-images.githubusercontent.com/16168279/88335110-fea99c80-ccef-11ea-82c2-2412f88a7a17.gif)

This means switching between the two requires manually resizing the panel every time.

### Che version
Hosted Che 7.16.0
`Che-Theia@8740bbe using Theia@a0e635aed`
Chrome `Version 84.0.4147.89 (Official Build) (64-bit)`

### Steps to reproduce
1. Create workspace that has a preview URL
2. Start preview and open URL in side panel
3. Switch between URL and commands and note that size is kept.

### Expected behavior
Each panel remembers its last size and opens to that width.

**Comment by l0rd** [comment]
@amisevsk it looks like normal behavior. Think about the anology with how tabs work in chrome: 2 tabs on the same window are both affected if change the window size. In theia (or vscode) 2 tabs on the same area are affected if you change the area size. If you want tabs to have distinct sizes you can move the tab in another area.

**Comment by amisevsk** [comment]
I understand why it happens, but perhaps the more fundamental issue is reusing the same sidebar for very different purposes. There are various sidebars in Theia where this functionality makes sense (e.g. all of the tabs on the left sidebar fit within roughly the same size); here it means you have to resize every time you switch tabs. I wouldn't store two tabs in the same window in Chrome if one needed 50% of the screen and the other needed 25%.

In addition, the first time you open a preview, it rescales the side panel used for commands to 50% of the editor space, so clicking the "open preview URL" popup changes the layout of your workspace.

**Comment by amisevsk** [comment]
Thinking more about what's available in Theia -- would it be possible to open to page in an editor tab, like we do for markdown previews? This would decouple the web preview from the side panel.

**Comment by JPinkney** [comment]
You should just be able to grab the icon on the right-hand side and drag it into the editor tab

**Comment by amisevsk** [comment]
@JPinkney beautiful:

![Peek 2020-07-27 16-33](https://user-images.githubusercontent.com/16168279/88589419-1a31e180-d027-11ea-9dc7-d94267a89dcd.gif)

I still have to resize the panel after the initial open, but this is great. I think this should be the default open behaviour.

**Comment by l0rd** [comment]
> I still have to resize the panel after the initial open, but this is great. I think this should be the default open behaviour.
makes sense
