### ISSUE TITLE
Build of che-plugin-registry fails during plugin download with 404

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#17473]
**EDIT:** changed build command and clarified this was an offline registry

### Describe the bug

Building **an offline version** of the che-plugin-registry fails downloading `rhamt-vscode-extension-0.0.37-589`:

```
Caching extension https://download.jboss.org/jbosstools/adapters/stable/rhamt-vscode-extension/rhamt-vscode-extension-0.0.37-589.vsix
    https://download.jboss.org/jbosstools/adapters/stable/rhamt-vscode-extension/rhamt-vscode-extension-0.0.37-589.vsix:
2020-07-23 16:25:56 ERROR 404: Not Found.
```

I have confirmed that this plugin version is not in the listing at https://download.jboss.org/jbosstools/adapters/stable/rhamt-vscode-extension
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

`./build.sh --offline`

### Expected behavior

The build creates a custom plug-in registry image

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ericwill** [comment]
cc @johnsteele

**Comment by tsmaeder** [comment]
There was some recent activity in github issues about rhamt being renamed to sth. else.

**Comment by ericwill** [comment]
Even with the rename, this is still an issue as https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/rhamt/0.0.23/meta.yaml#L37 is still returning 404.

**Comment by ericwill** [comment]
> Even with the rename, this is still an issue as https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/rhamt/0.0.23/meta.yaml#L37 is still returning 404.

Seems to be fixed now, it no longer 404's for me.
