### ISSUE TITLE
An error appears when starting a workspace with the OpenShift-connector plugin

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#17471]
### Describe the bug

An error appears when starting a workspace with the openshift-connector plugin
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace
2. Apply the `openshift-connector` plugin
3. See the error:
![screenshot-che openshift io-2020 07 23-15_22_18](https://user-images.githubusercontent.com/7668752/88286020-c65a8c00-ccf8-11ea-9ef1-30fae1d36d3e.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sunix** [comment]
I have been through that issue in che.openshift.io but it did stopped me to get automatically connected to the openshift cluster with my account. Let me know if it works on your side
Setting p2 for the moment.
