### ISSUE TITLE
Provide yaml schema for devfile on schemastore

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#17479]
### Is your enhancement related to a problem? Please describe.

Providing a yaml schema for devfile will ease development of devfile.

Publishing it on https://www.schemastore.org/json/ will allow support fo rit in several IDEs https://www.schemastore.org/json/#editors

**Comment by amisevsk** [comment]
cc: @JPinkney in case you have any input here.

**Comment by JPinkney** [comment]
I think the only thing to add is that we can link directly to a url instead of actually embedding a schema directly in the json schema store so if we have a stable link on github we can add it easily

**Comment by l0rd** [comment]
That should be the [link to the json schema](https://raw.githubusercontent.com/eclipse/che/master/wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json). @apupier would you like to contribute it?

**Comment by apupier** [comment]
> would you like to contribute it?

I can but i'm on PTO for 3 weeks. so if someone else wants to do it before, he is more than welcome. The repository is https://github.com/SchemaStore/schemastore

also need to know what is the fiel pattern to use. only `devfile.yaml`? or `.devfile.yaml`? any others?

**Comment by l0rd** [comment]
Both `devfile.yaml` and `.devfile.yaml`

**Comment by apupier** [comment]
done in SchemaStore
