### ISSUE TITLE
is possible to create a custom menu at the top using che-theia plugin ?

### ISSUE THREAD

**Issue by Rahith-RR** [eclipse-che/che#17478]
I could create a custom menu on the explorer of the IDE . Is it possible to create custom menu on the top like File,Edit etc and add options to that menu?

**Comment by RomanNikitenko** [comment]
Hello!
I think plugin system allows to add menu items to certain list of entities.
You can see an example how it can be achieved [here](https://github.com/eclipse/che-theia-samples/blob/fd354e6d3be2d530c32d1adccaee3a5e19eaa083/samples/menus-contribution-plugin/package.json#L37)

Menu contributions are handled on `Theia` side and the corresponding code you can see [here](https://github.com/eclipse-theia/theia/blob/fd239889618f16b8ac48d50a754bf363ee5230c9/packages/plugin-ext/src/main/browser/menus/menus-contribution-handler.ts#L96-L174)
I think it's matched to the corresponding entities of VS Code: https://code.visualstudio.com/api/references/contribution-points#contributes.menus
 
Taking into account the info above, I don't see a way to provide menu items on the top like `File`, `Edit`, etc from plugin side.
But I believe it's possible from extension side.

**Comment by Rahith-RR** [comment]
@RomanNikitenko, thank you for the info.

**Comment by Rahith-RR** [comment]
How we can create custom extensions for Theia with Eclipse Che?
Tried an example using this link below but its not working and showing issue.
https://eclipsesource.com/blogs/2019/11/21/how-to-create-develop-an-eclipse-theia-ide-extension/

**Comment by RomanNikitenko** [comment]
You could use one of the existed extensions as an example: https://github.com/eclipse/che-theia/tree/master/extensions
