### ISSUE TITLE
An attempt to migrate the Lombok plug-in from vscode failed.

### ISSUE THREAD

**Issue by xiazhijian** [eclipse-che/che#17485]
## Summary
An attempt to migrate the Lombok plug-in from vscode failed.
An error occurred during installation:
Unable to install plugin 'GabrielBB/vscode-lombok/latest'. Request addPlugin failed unexpectedly without providing any details.

## Relevant information
Source code address: https://github.com/xiazhijian/vs-code-lombok
Error screenshot：
<img src="https://xiazhijian.github.io/vs-code-lombok/1.png"/>

**Comment by ericwill** [comment]
Let's discuss this in #17483
