### ISSUE TITLE
Che operator olm files are mangled since 7.16.0

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17480]
Comparing nightly olm file vs. 7.16.0, we see the formatting for embedded annotations has been mangled:

![image](https://user-images.githubusercontent.com/227597/88401015-2acc2880-cd97-11ea-9406-5de9ff73497e.png)

Also further down in the file we see another mangled formatting:

![image](https://user-images.githubusercontent.com/227597/88401227-72eb4b00-cd97-11ea-8296-825acaefe05e.png)

(this is comparing 7.15.2 and 7.16.0, so evidently this change happened some time after 7.15.2 was released.)

This looks to me like someone applied a `yq` transformation without using the `yq -yY` flags to preserve whitespace formatting.

**Comment by nickboldt** [comment]
I wonder if the problem is here?

```
  if [[ $platform == "openshift" ]]; then
    yq -riSY  '.spec.preserveUnknownFields = false' ${RELEASE_CRD}
    yq -riSY  '.spec.validation.openAPIV3Schema.type = "object"' ${RELEASE_CRD}
    eval head -10 ${LAST_NIGHTLY_CRD} | cat - ${RELEASE_CRD} > tmp && mv tmp ${RELEASE_CRD}
  fi
```
-- https://github.com/eclipse/che-operator/blob/master/olm/release-olm-files.sh

**Comment by nickboldt** [comment]
I think the reason the diff generator isn't reporting this problem is that we compute the diff BEFORE running addDigests.sh:

```
  cp ${LAST_NIGHTLY_CRD} ${RELEASE_CRD}
  if [[ $platform == "openshift" ]]; then
    yq -riSY  '.spec.preserveUnknownFields = false' ${RELEASE_CRD}
    yq -riSY  '.spec.validation.openAPIV3Schema.type = "object"' ${RELEASE_CRD}
    eval head -10 ${LAST_NIGHTLY_CRD} | cat - ${RELEASE_CRD} > tmp && mv tmp ${RELEASE_CRD}
  fi

  sed -e "s/${lastPackagePreReleaseVersion}/${RELEASE}/" "${packageFilePath}" > "${packageFilePath}.new"
  mv "${packageFilePath}.new" "${packageFilePath}"

  diff -u ${PRE_RELEASE_CSV} ${RELEASE_CSV} > ${RELEASE_CSV}".diff" || true
  diff -u ${PRE_RELEASE_CRD} ${RELEASE_CRD} > ${RELEASE_CRD}".diff" || true
done
cd "${CURRENT_DIR}"

source ${BASE_DIR}/addDigests.sh -w ${BASE_DIR} \
                -r "eclipse-che-preview-.*\.v${RELEASE}.*yaml" \
                -t ${RELEASE}
```

**Comment by amisevsk** [comment]
Setting as P1 since even though it does not impact usage, it's a build issue that could bite us.
