### ISSUE TITLE
When deploying on OpenShift we should setup OpenShift OAuth by default

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17488]
### Is your enhancement related to a problem? Please describe.

When deploying Che using `chectl server:start --platform=openshift` it does not automatically setup OpenShift OAuth if the `--os-oauth` flag is not provided.

### Describe the solution you'd like

When deploying on OpenShift we shoud always setup OpenShift OAuth

**Comment by tolusha** [comment]
I kind of agree.

To be consistent:
- set `openShiftoAuth: true` in CR https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L105
- remove `--os-oauth` flag from `chectl`
- provide description how to deploy on OpenShift without OAuth support.
