### ISSUE TITLE
Definition of done for Pull Requests

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17486]
### Is your task related to a problem? Please describe.

Here is an updated PRs Approval Checklist:

The things a reviewer needs to verify before approving a PR (in italic those checks that can/should be automated):

1. Code produced (No TODO items on the code, tickets are created for them)
2. Code documented
3. Builds without errors
4. Doesn’t break self-hosting
5. Static code analysis done and issues fixed 
6. Unit tests written and passing
7. How the PR has been tested (which env) and how a reviewer can test it too (if possible, a button to check online)?
8. Deployed to test/staging environment and passed e2e happy path test 
9. Code review done
10. Any build/deployment/configuration changes are implemented, tested, documented and communicated (Operational documentation) 
11. Relevant documentation produced and/or updated (User documentation)
12. Video Recording of the fix or feature (optional)
13. Link to corresponding issues (if any)
Has a milestone and a type (bug/feature/task) or is linked to issue with milestone and type

This definition of done applies to all the work that is merged into the Che code repositories. Therefore it should be applied to all Pull Requests and is part of the code review. It is both  reviewers’ and the pull request creators’ responsibility to ensure that it has been followed..

**Comment by benoitf** [comment]
Here is an example of what could be done for PR (updating template)

https://github.com/benoitf/che-template-issues/pull/1

**Comment by dmytro-ndp** [comment]
@benoitf, @l0rd: WDYT about dividing the list by _mandatory_ and _optional_ sections to simplify approval decision?

_Mandatory_:

(1). Code produced (No TODO items on the code, tickets are created for them)
(2). Code documented
(3). Builds without errors
(4). Doesn’t break self-hosting
(5). Static code analysis done and issues fixed
(6). Unit tests written and passing
(7). How the PR has been tested (which env) and how a reviewer can test it too (if possible, a button to check online)?
(8). Deployed to test/staging environment and passed e2e happy path test
(9). Code review done
(14). Has a milestone and a type (bug/feature/task) or is linked to issue with milestone and type

_Optional_:

(10). Any build/deployment/configuration changes are implemented, tested, documented and communicated (Operational documentation)
(11). Relevant documentation produced and/or updated (User documentation)
(12). Video Recording of the fix or feature (optional)
(13). Link to corresponding issues (if any)

**Comment by l0rd** [comment]
@dmytro-ndp I think that we should distinguish between points that can be mandatory for the the particular PR (docs updates for example) and points that are always optional (video recording). 

I would remove optionals (video recording) from the the checklist since it's mentioned in the description (screen capture or screencast).

**Comment by l0rd** [comment]
@benoitf thinking about this afternoon discussion I am wondering if we should not provide a more compact checklist and then provide detailed explanation in the wiki.

For example:

```
## What does this PR do?
(with screencast)

## The PR Checklist

As the author of this PR I made sure that:

 - [ ] The Eclipse Contributor Agreement has been signed
 - [ ] Code produced is complete
 - [ ] Code builds without errors
 - [ ] A corresponding automated test is added for every bug fixed
 - [ ] The devfile is up to date and works
 - [ ] The PR has been tested and "How to test" instructions are provided below
 - [ ] Link to any corresponding issue and PR is provided below
 - [ ] Relevant user documentation updated
 - [ ] Relevant contributing documentation is updated
 - [ ] CI/CD changes implemented, documented and communicated

A detailed explanation of the PR checklist is available in the Development Process section of the Eclipse Che wiki. 

## How to test this PR

## Corresponding issues and PRs
```

**Comment by l0rd** [comment]
Other enhancements: 
  - The list doesn't need to be numbered
  - Checkboxes should only be for the PR checklist, not for runtime/installation method/environment otherwise:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/606959/88581928-34cb8100-d04e-11ea-8c41-0c05cf240287.png">
