### ISSUE TITLE
How can we store github access tokens in eclipse che workspace.

### ISSUE THREAD

**Issue by awsompankaj** [eclipse-che/che#17482]
### Is your enhancement related to a problem? Please describe.
We have a developenet enviroment where we access the github repo using access tokens, we didnt find any way to store access tokens

### Describe the solution you'd like
 any options to save access token in workspace or user settings

**Comment by amisevsk** [comment]
Hi @awsompankaj, have you taken a look at this section in [the docs](https://www.eclipse.org/che/docs/che-7/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/)?

cc: @skabashnyuk @sunix I think you've been working on this recently.

**Comment by awsompankaj** [comment]
Hi @amisevsk thank you for your response, i am searching an option to store access token from workspace GUI settings.

Is there any way or only we have this option mounting secret file.

**Comment by sunix** [comment]
@awsompankaj that was a first step, we may have an option to do that from the Che dashboard or workspace but would need a workspace restart. would that works for you ?
@l0rd any thoughts?

**Comment by awsompankaj** [comment]
@sunix workspace restart is OKAY it we have an option to save access keys in GUI. Just to make sure it would be permanent?
i mean whenever i start the workspace i need to put access token?

**Comment by sunix** [comment]
no you would do it once, maybe from the dashboard or a workspace. Then any workspaces started after would have the token injected.

**Comment by sunix** [comment]
Also, we may even not have to add the token. Would be done through oauth if we implement https://github.com/eclipse/che/issues/14217

**Comment by awsompankaj** [comment]
@sunix  Thanks for you help, lets see if oauth will work for your use case.
