### ISSUE TITLE
How to register a new custom file extension (Ex : example.wpdx) in Eclipse che? 

### ISSUE THREAD

**Issue by Rahith-RR** [eclipse-che/che#17490]
How to register a new custom file extension (Ex : ex.wpdx)in Eclipse che . 
Also I want to enable preview for extension file. Is it possible?

**Comment by ericwill** [comment]
cc @azatsarynnyy, looks like something for your team

**Comment by l0rd** [comment]
This looks like a good candidate for a new documentation article

**Comment by azatsarynnyy** [comment]
Hello @Rahith-RR 
[here's the example](https://github.com/eclipse-theia/theia/blob/fe2463042c7df9c51c73b5e13a96fbb9d8290e25/packages/preview/src/browser/markdown/markdown-preview-handler.ts#L33) of implementing `PreviewHandler` for markdown preview

**Comment by azatsarynnyy** [comment]
Closing this one as the question has been addressed. Feel free to reopen if more info will be needed.
