### ISSUE TITLE
che-docs dockerfile is set up strangely

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17495]
### Describe the bug
It's unclear what the [che-docs dockerfile](https://github.com/eclipse/che-docs/blob/master/Dockerfile) is meant to be used for. It appears to be written so that running it will serve the Che documentation locally, but:
- No sources are copied into the file, and the workdir (`/che-docs`) is empty:
  ```
  $ docker run -it --rm quay.io/eclipse/che-docs:latest /bin/bash
  bash-5.0# ls -al
  total 12
  drwxrwxr-x    2 root     root          4096 Feb 24 12:50 .
  drwxr-xr-x    1 root     root          4096 Jul 27 20:08 ..
  bash-5.0# pwd
  /che-docs
  bash-5.0# 
  ```
- It's also used for the che-docs devfile, but the workdir being set to `/che-docs` means terminals open in the wrong directory. The standard for images used in devfiles is to set workdir to `/projects` (or for a project-specific devfile, it could be `/projects/che-docs`

We should clarify the purpose of this docker image and set it up to naturally work with that goal in mind.

### Related
https://github.com/eclipse/che/issues/17450

**Comment by amisevsk** [comment]
In addition, the docker image does not have an entrypoint like we do for other devfile images, meaning the user has no `${HOME}` directory or username.

**Comment by benoitf** [comment]
I think docker image was at first designed to:
- build documentation and publish it to eclipse che website from ci.eclipse.org (Jenkinsfile)
- use locally (not on che) with run.sh script

**Comment by benoitf** [comment]
> It's also used for the che-docs devfile, but the workdir being set to /che-docs means terminals open in the wrong directory. The standard for images used in devfiles is to set workdir to /projects (or for a project-specific devfile, it could be /projects/che-docs

I think here we're missing somehow an upstream theia feature where a terminal is opened by default into the project root directory and if several roots, user should be prompted to select the folder for its terminal

**Comment by amisevsk** [comment]
> build documentation and publish it to eclipse che website from ci.eclipse.org (Jenkinsfile)
> use locally (not on che) with run.sh script

Neither of these use cases are supported right now though -- it seems to be built as the dev container for the devfile with some vestigial "build documentation" goals. Source code is not copied into the image, the entrypoint refers to an empty directory, and the commands

```
    && mkdir /che-docs \
    && for f in "/che-docs"; do \
           chgrp -R 0 ${f} && \
           chmod -R g+rwX ${f}; \
       done
```
are basically a no-op.

I also had some trouble building it locally to update it for my use -- I had to add `python3 -m ensurepip` or else the `pip install` step would fail.

**Comment by benoitf** [comment]
> -
```
  && mkdir /che-docs \
    && for f in "/che-docs"; do \
           chgrp -R 0 ${f} && \
           chmod -R g+rwX ${f}; \
       done
```
will perform `chgrp -R 0/che-docs && chmod -R g+rwX /che-docs` so it's not a no-op


> I also had some trouble building it locally to update it for my use -- I had to add python3 -m ensurepip or else the pip install step would fail.
see
https://github.com/eclipse/che-docs/pull/1429


basically it's because the parent image has changed (from alpine latest (which was 3.11) to alpine latest now (which is 3.12))

**Comment by benoitf** [comment]
> Source code is not copied into the image, the entrypoint refers to an empty directory, and the commands

it's mounted (see `run.sh` / `"${RUNNER}" run --rm -v "${SRC_PATH}":/che-docs:Z "$@"` )

**Comment by amisevsk** [comment]
>  perform chgrp -R 0/che-docs && chmod -R g+rwX /che-docs so it's not a no-op

Makes sense, but why structure the command to be a for loop over one element, that recursively chgrps an empty directory?

> it's mounted (see run.sh / "${RUNNER}" run --rm -v "${SRC_PATH}":/che-docs:Z "$@" )

Ah I didn't see `run.sh`. If the Dockerfile is only intended to work with a mounted volume, could we document that in a comment?

**Comment by themr0c** [comment]
The che-docs image was created to work with Jekyll. Now we are using Antora, and the container produced by the Antora project, and other containers with good maintainers for other tools, the purpose of the che-docs container is probably coming to an end.

**Comment by amisevsk** [comment]
If the che-docs container is not used for the build anymore, that simplifies the problem. The che-docs container will still be required to support the devfile image.

**Comment by themr0c** [comment]
The devfile doesn't use the che-docs container anymore. We use directly the containers maintained by the upstream projects.
