### ISSUE TITLE
Factory sometimes doesn't create workspace

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17508]
### Describe the bug
From time to time, a workspace that should be created and started via factory URL is not even created. The UI is stuck on the first step and no error is shown to the user. This problem was reproduced manually and was also caught by nightly tests against nightly Che build.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Login to che
2. Past factory link to the URL: `<che_url>/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/java-maven/devfile.yaml`
3. Wait for factory page to be loaded.

### Expected behavior
The workspace should be created and started or some error should be shown to the user.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`) minikube v1.1.1 on linux (amd64)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/88673962-7f4e0b80-d0e9-11ea-8052-688ab8a0f6f4.png)

### Installation method
   - [x] chectl chectl/0.0.20200721-next.cf7baad linux-x64 node-v10.21.0
chectl server:start --k8spodreadytimeout=180000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/mnt/hudson_workspace/workspace/basic-MultiUser-Che-check-e2e-tests-against-k8s/custom-resource-patch.yaml
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
[Browser logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2031/artifact/tests/e2e/report/Workspace_creation_via_factory_url_Wait_workspace_readyness_Wait_for_workspace_readiness/browserlogs-Wait_for_workspace_readiness.txt)
[Che logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2031/artifact/logs-and-configs/che-logs/che-c96cf6d99-tx6hx.pod.log)
[All other logs gathered by test](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2031/artifact/logs-and-configs/)

**Comment by sleshchenko** [comment]
I can't reproduce this issue on che.openshift.io. 7 successful tries. @Katka92 it would be cool if you attach browser HAR (requests history) to the issue.

**Comment by Katka92** [comment]
@sleshchenko I reproduced that on nightly, on che.openshift.io there is 7.16.0 (should be updated to 7.16.2 early next week) so I'm not sure if that can be a difference. I'll try to reproduce that manually and if I'll be successful, I'll share the requests history.

**Comment by Katka92** [comment]
Now we have 7.16.2 on che.openshift.io. I was not able to reproduce it there. I tried for ~7 times.

**Comment by Katka92** [comment]
This issue was reproduced again during our nightly tests of nightly Che. All logs that we have can be found [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2084/artifact/logs-and-configs/).

**Comment by sleshchenko** [comment]
@Katka92 it seems to be an error on client side and as far as I see the referenced logs do not contain browser logs nor HAR =(
Hope https://github.com/eclipse/che-dashboard/pull/80 will make the cause more visible.
@olexii4 Could you give a quick look if error on `Loading factory` should be propagated after Oleksii PR?

**Comment by sleshchenko** [comment]
It's proved that the error is propagated if it's an error returned by Che Server with JSON format
![Screenshot_20200817_171832](https://user-images.githubusercontent.com/5887312/90406397-c490a800-e0ad-11ea-95e0-ed7d459cbbaa.png)

But according to the first browser logs 
```
"SEVERE" "" "https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js 1332:3936 TypeError: Cannot read property 'message' of null
    at e.value (https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1743:4421)
    at https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1743:2886
    at l (https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1333:10244)
    at https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1333:10690
    at p.$digest (https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1333:16549)
    at p.$apply (https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1333:18543)
    at a (https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1332:24602)
    at v (https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1332:27171)
    at XMLHttpRequest.k (https://che-che.10.0.101.2.nip.io/dashboard/scripts/app-a9edd8504e.js:1332:27661) "Possibly unhandled rejection: {}""
"SEVERE" "" "https://che-che.10.0.101.2.nip.io/api/factory/resolver - Failed to load resource: net::ERR_NETWORK_CHANGED"
```
^ dashboard fails and shows nothing if it's some browser error, like certificate issue, cors, err_network_changed.
So, from dashboard point of view - we can make that failure more visible (a dedicated issue is created https://github.com/eclipse/che/issues/17646) but it's not really clear why QE tests fail, probably it's some QE tests infrastructure issue.

**Comment by Katka92** [comment]
We are experiencing a factory issue from time to time with a different design. Not sure if it is related to this issue or if a new issue should be created.
[Browser logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-single-host-check-e2e-tests-against-k8s/77/artifact/tests/e2e/report/Workspace_creation_via_factory_url_Wait_workspace_readyness_Wait_for_workspace_readiness/browserlogs-Wait_for_workspace_readiness.txt)
![image](https://user-images.githubusercontent.com/29278800/93310478-1d667400-f805-11ea-9b2d-542637ed19e7.png)

**Comment by sleshchenko** [comment]
@Katka92 It's related to this issue. Again it's 
```
"SEVERE" "" "https://10.0.107.166.nip.io/api/factory/resolver - Failed to load resource: net::ERR_NETWORK_CHANGED"
"WARNING" "" "https://10.0.107.166.nip.io/dashboard/scripts/app-a78217241b.js 1321:4173 "WebSocket connection is closed.""
"WARNING" "" "https://10.0.107.166.nip.io/dashboard/scripts/app-a78217241b.js 1321:4173 "WebSocket is reconnecting, attempt #1 out of 5...""
```
so, something is wrong with networking... Thanks for reporting, we'll try to convert object.Object to some more readable in such case.

**Comment by sleshchenko** [comment]
@Katka92 https://github.com/eclipse/che-dashboard/pull/94 is supposed to imrpove a message but it's hard to reproduce that NETWORK_CHANGED error. if you face it again - please let us know if it's fine now, if not - browser logs can help us understand how to can finally solve it in proper way.

**Comment by Katka92** [comment]
Ok, thank you very much, I'll keep watching and comment if I'll see that again :)

**Comment by Katka92** [comment]
@sleshchenko Hello, it seems the problem appeared again - is that the message that you've added? :) 

`failed to fetch devfile due to "-1" returned by "/api/factory/resolver"`

![image](https://user-images.githubusercontent.com/29278800/93737350-44e18600-fbe3-11ea-8ce1-b3cc41cfc2e8.png)
[browser logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2242/artifact/tests/e2e/report/Workspace_creation_via_factory_url_Wait_workspace_readyness_Wait_for_workspace_readiness/browserlogs-Wait_for_workspace_readiness.txt)

**Comment by sleshchenko** [comment]
@Katka92 yeah, it's the message we added which is supposed to be better in case of a completed HTTP request.
We'll take a look at how we can improve the message in case of an incomplete HTTP request.

Anyway, it'll be just another error message. Do you have any ideas why request is interrupted on the Che installations you use?

**Comment by Katka92** [comment]
> yeah, it's the message we added which is supposed to be better in case of a completed HTTP request.
We'll take a look at how we can improve the message in case of an incomplete HTTP request.

Thank you for adding the message, it is absolutely better then just echoing `Object`. :+1: 

> Do you have any ideas why request is interrupted on the Che installations you use? 

To be honest, the infra we are using seems to be pretty stable for other tests, so it's interesting that only that one test is having such issues that frequently. Maybe @rhopp or @dmytro-ndp can have some ideas?

**Comment by rhopp** [comment]
The error indeed seems like a problem with networking... To understand it better we would need to add more debug output into the execution of the test...
For start I would run ping to che server URL in the background & also output of `ip address` every few seconds as suggested here: https://superuser.com/a/1302316. Maybe there is something fishy in networking between host<->minikube

**Comment by sleshchenko** [comment]
closing since it's about old dashboard that is fully removed
