### ISSUE TITLE
Kubernetes plugin wants `minikube` to be installed in the container

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#17501]
### Describe the bug

The latest Kubernetes plugin cannot be launched inside Che-Theia.

In the workspaces, created from [devfiles](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/tree/master/dogfooding), it's become not possible to develop K8S plugin cloned from it's repository.
The newer version of the plugin requires the `minikube` to be installed in the container.

### Che version

 - [x] latest
 - [x] nightly

### Steps to reproduce

1. Create workspace from the [devfile](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/blob/master/dogfooding/devfile.yaml)
2. Inject kubeconfig
3. Run 1.1, 1.2, 1.3 commands
4. Run 2.1 and 2.2 commands
5. Open Che-Theia dev instance and check Kubernetes plugin

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![Screenshot from 2020-07-28 13-40-40](https://user-images.githubusercontent.com/1655894/88659386-a56dae80-d0dd-11ea-8be1-4b0527f7b58b.png)

![Screenshot from 2020-07-28 13-41-08](https://user-images.githubusercontent.com/1655894/88659396-aa326280-d0dd-11ea-9df6-6d08cbd45918.png)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

**Comment by ericwill** [comment]
@vitaliy-guliy so this is a plugin requirement, it does not block che-dockerfiles/che-sidecar-kubernetes-tooling#18 ?

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy so this is a plugin requirement, it does not block [che-dockerfiles/che-sidecar-kubernetes-tooling#18](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/pull/18) ?

It does not block, but it stay unchecked how the plugin works in container built with changes from PR.
