### ISSUE TITLE
Shutdown Asynchronous Pod after some idle time

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#17507]
### Is your task related to a problem? Please describe.
To not spend resources we need to shut down Asynchronous Pod after some idle time. 
We can shutdown it in case no running workspace configured with Asynchronous Storage.
We can do it immediately but in this case we will stop it even if user going to restart workspace, so I propose to add some configurable timeout for this procedure.

**Comment by ibuziuk** [comment]
@vparfonov PRs are merged. Should we close the issue?
