### ISSUE TITLE
[Docs] Add instructions how to remove Che user

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#17500]
## Summary
**Update:** Please see https://github.com/eclipse/che/issues/17500#issuecomment-665952556
 
My question is: is it possible to remove an user on `Che`?

My motivation is: I can not start any workspace due to incorrect namespace, please see `relevant info` section.
I tried to remove user using swagger. After removing user doesn't exist, but after refreshing a page or at next login the system has the same user with the same `ID`.

Please see my short demo:
 
![user_delete](https://user-images.githubusercontent.com/5676062/88644113-3b4c0e00-d0cb-11ea-9a78-ccccfd3693f5.gif)

## Relevant information
I faced with the problem like described here: https://github.com/eclipse/che/issues/17265#issuecomment-650947172
So:
- Che's Keycloak shows the form with `username`, `email`, etc. when a user is trying to login into Che Dashboard the very first time
- autofill plugin sets the fields 
- as result `username` can get incorrect value (with real names, including spaces or email for example)

Then user can not create a workspace due to not a valid namespace:
`The workspace would be started in a namespace/project '<incorrect value here>', which is not a valid namespace/project name.`

Please see https://github.com/eclipse/che/issues/17265#issuecomment-650947172.

**Comment by sleshchenko** [comment]
cc @skabashnyuk @tolusha Any thoughts if it's possible to fully unregister the user by themselves? Seems keycloak user should be removed as well, but is it possible?

**Comment by skabashnyuk** [comment]
@sleshchenko I don't know. Probably keycloak admin can do that. Che-server API behaves correctly in this use-case as far as I can see.

**Comment by tolusha** [comment]
It is necessary to remove user in keycloak.
![Screenshot from 2020-07-29 13-57-19](https://user-images.githubusercontent.com/1640675/88792148-7883cf00-d1a3-11ea-9561-29f7532ff4bc.png)

**Comment by tolusha** [comment]
@RomanNikitenko 
Did I answer your question?

**Comment by RomanNikitenko** [comment]
@tolusha 
I guess it's possible for admin role only.

So for my case for https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/ instance I can not remove myself from keycloak. 

correct?

**Comment by tolusha** [comment]
yes, only admin can remove use from the keycloak.

**Comment by RomanNikitenko** [comment]
@skabashnyuk @tolusha @sleshchenko 
thank you very much for your help and support!

Now it's clear for me, so I'm closing the issue

**Comment by l0rd** [comment]
@RomanNikitenko if it's not in documentation yet we should probably re-open this issue as a documentation issue. We need to add:
- a section about how to remove a user in the admin guide
- a link to #17265 in the known issues

**Comment by ibuziuk** [comment]
@l0rd there was a request from the Toolchain team to make the Delete API call GDPR compliant and cleanup resources not only on the db level, but also on keycloak - https://github.com/eclipse/che/issues/17541
I believe we need to treat it as a high priority issue ^

**Comment by l0rd** [comment]
@ibuziuk priority now is documentation (let's include this issue into next sprint backlog) and then let's prioritize the API side (the issue you mentioned).

**Comment by skabashnyuk** [comment]
@ibuziuk is there anything left on this task?

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2576

**Comment by themr0c** [comment]
Is the current doc here sufficient? https://www.eclipse.org/che/docs/che-7/administration-guide/removing-user-data/

**Comment by boczkowska** [comment]
@l0rd could you take a look if the current documentation covers the issue https://www.eclipse.org/che/docs/che-7/administration-guide/removing-user-data/ ? Can we close it?

**Comment by l0rd** [comment]
@boczkowska yes. Closing.
