### ISSUE TITLE
Setup GitHub actions to run builds and PR checks for che-incubator/workspace-data-sync repository

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#17515]
### Is your task related to a problem? Please describe.
Setup GitHub actions to run builds and PR checks for https://github.com/che-incubator/workspace-data-sync repository

**Comment by sleshchenko** [comment]
@vparfonov Just want to share the good PR check devfile/parser has for go code, where formatting and go modules are checked https://github.com/devfile/parser/blob/master/.github/workflows/go.yml

**Comment by vparfonov** [comment]
> @vparfonov Just want to share the good PR check devfile/parser has for go code, where formatting and go modules are checked https://github.com/devfile/parser/blob/master/.github/workflows/go.yml

thanks
