### ISSUE TITLE
[Docs] Fix instructions for build plug-in and devfile registries

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#17510]
### Is your enhancement related to a problem? Please describe.

The [docs](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/) describing how to build a new version of the plug-in and devfile registries instruct the user to run `docker build -t my-registry image .`.    The two repositories now rely on a build script.

### Describe the solution you'd like

The documentation should be changed to reflect how these images are currently built, using their respective build scripts.

**Comment by themr0c** [comment]
The chapter "Building and running a custom registry image" is outdated
    The story "Installing {prod} in a restricted environment" contains an updated version of most steps, except "modifying the content of the registry"

What we need now is:

    Reuse in "Custom" story the modules already used in the "Installing" story
    Add proper procedures for the  "Modifying the content of the {devfile,plugin} registry" steps.

**Comment by themr0c** [comment]
Referenced in: https://issues.redhat.com/browse/RHDEVDOCS-2168
