### ISSUE TITLE
[Docs] Clean up documentation for including a plug-in binary in a registry image

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#17511]
### Is your enhancement related to a problem? Please describe.

The [documentation](https://www.eclipse.org/che/docs/che-7/including-the-plug-in-binaries-in-the-registry-image/) for including a plug-in bianry in the registry image does not work and is in need of a clean up. Some of the commands don't work and appear to be copy/pasted asciidoc.

**Comment by rkratky** [comment]
Fixed by https://github.com/eclipse/che-docs/pull/1432
