### ISSUE TITLE
Loading flow when loading IDE is flickering

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1752]
Flickering problems with transitions.
1. Empty gray screen
2. IDE half-loaded
3. IDE showing "start workspace agent" when it was already done in factoring loading
4. IDE showing "searching for recipe"

**Reproduction Steps:**
See the attached files for animation.

**Che version:**    4.4.2 

![factory-from-github](https://cloud.githubusercontent.com/assets/392458/16896186/528781b2-4b41-11e6-9536-0cea6e788b5c.gif)

**Comment by ashumilova** [comment]
Is not reproduced in CHE - need to check with factories

**Comment by ashumilova** [comment]
cannot reproduce
