### ISSUE TITLE
Switch to newer version of builtin plugins

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#17524]
### Is your enhancement related to a problem? Please describe.

Default plugins we are using in Che-Theia are bit outdated. They were released 10 month ago

### Describe the solution you'd like

To have plugins updated we need:
- [ ] synchronize references to plugin binaries between [theiaPlugins.json](https://github.com/eclipse/che-theia/blob/master/generator/src/templates/theiaPlugins.json) in Che-Theia and [package.json](https://github.com/eclipse-theia/theia/blob/master/package.json) in Theia
- [ ] carefully test each the plugin we updated

**Comment by svor** [comment]
@vitaliy-guliy `vscode-builtin-java` will be updated in separate issue, don't care about it
