### ISSUE TITLE
I can't define a private container registry secret for che-theia 

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#17522]
### Describe the bug

I added a secret for the registry then I added imagePullSecrets to containers' meta.yaml in the plugin-registry but it didn't work for the che-theia.

### Che version

7.14.2

### Steps to reproduce
1. Create a secret for a private registry in Kubernetes
2. Add imagePullSecrets to containers' meta.yml in plugin-registry
3. Imagepulloff error

### Expected behavior

Successfully pull che-theia images from the private registry.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by l0rd** [comment]
@cenkce have you looked at the documentation?

**Comment by l0rd** [comment]
@cenkce is it only che-theia image that's in a private registry or other workspace components images too?

**Comment by cenkce** [comment]
Yes I can't find any information about this in documentations. I can't only run our che-theia images. Che-server, plugin-registry and dev-file registry images work without any problem from the private registry.

**Comment by dkwakkel** [comment]
Any update on this?

**Comment by l0rd** [comment]
@dkwakkel it's possible to add registry credentials from the admin menu item of the user dashboard

![image](https://user-images.githubusercontent.com/606959/94044548-969a3400-fdce-11ea-8144-b7494c88a7ce.png)

**Comment by cenkce** [comment]
Yes but it's just for a user, I need to define all users.

**Comment by l0rd** [comment]
@cenkce ok so no we do not have an admin dashboard where you can set the secret for all the users. 
You can manually create a secret [in users namespaces](https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry) but I don't think we have a way to inject it automatically in workspaces pods with [`ImagePullSecret`](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) yet (do we @skabashnyuk @mshaposhnik?)

**Comment by l0rd** [comment]
> Yes but it's just for a user, I need to define for all users.

But anyway every user has his own user credentials right? Or you want to use one shared credential for all the users?

**Comment by cenkce** [comment]
Actually it's enough that I can pull private image from provider using ImagePullSecret in plugin-registry instead of inject. Like other images Che-server, plugin registry etc.

**Comment by cenkce** [comment]
Users shouldn't view this information.
