### ISSUE TITLE
Bypass E_CHE_API_NOTFOUND

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#17534]
### Is your enhancement related to a problem? Please describe.

It appears the Che deployed an expired certificate.

![image](https://user-images.githubusercontent.com/4656027/88968692-4b075600-d275-11ea-882d-bbeda8a6e56d.png)

### Describe the solution you'd like

There have been other situations where I wanted to retry an installation of Che, but because the API was non-functional, server:stop and server:delete don't work.

Instead of trying to use an API, perhaps kubectl could be used to undo any changes?  

### Describe alternatives you've considered

Documentation of CheCtl's internals so the end user could manually undo chectl's action.

**Comment by tolusha** [comment]
@gnoejuan 
Do you have any errors with `server:delete` command?

**Comment by gnoejuan** [comment]
![image](https://user-images.githubusercontent.com/4656027/89049718-46937980-d317-11ea-9d64-e50f06c4d314.png)

Yes. I believe my current problem isn't related to Che exactly. Currently I believe the problem is with my k8s deployment, but I'm still hunting that down.

`chectl server:start -a helm -b mainhub.lan -p k8s`

**Comment by tolusha** [comment]
@gnoejuan 
Thank you. I got it.

**Comment by SpontaneousDuck** [comment]
Perfect, I am also seeing the same issue. I think I am having a different problem with the front end as my browser just throws `ERR_CONNECTION_TIMED_OUT` but the issue with `chectl server:delete` is the same. Thanks for looking at this @tolusha

**Comment by gnoejuan** [comment]
Just to confirm, the certificate problem was/is most likely a problem with k3s.

https://github.com/rancher/k3s/issues/1621

I guess, just following up. After migrating back to microk8s, the cert was fine.
