### ISSUE TITLE
Fix PR check / nightly E2E tests Jenkins jobs to having OS OAuth support enabled by default 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17547]
### Is your task related to a problem? Please describe.
Our E2E testing Jenkins jobs on ci.centos / CRW CCI rely on chectl installation with _OS OAuth_ disabled by default.
They will start failing after https://github.com/eclipse/che/issues/17488 issue has been resolved and **chectl** will install Che with _OS OAuth_ enabled by default.

### Describe the solution you'd like
So, we need to those Jenkins job after https://github.com/eclipse/che/issues/17488 issue has been resolved and **chectl** will install Che with OS OAuth enabled by default.

**Comment by rhopp** [comment]
@SkorikSergey Please get in touch with @tolusha to make sure this issue is resolved together with https://github.com/eclipse/che/issues/17488.

**Comment by SkorikSergey** [comment]
> @SkorikSergey Please get in touch with @tolusha to make sure this issue is resolved together with #17488.

Ok. I will update scripts.
