### ISSUE TITLE
Cannot add a second project via the User Dashboard

### ISSUE THREAD

**Issue by jfrantzius** [eclipse-che/che#17549]
### Describe the bug
Hi, on che.openshift.io I wasn't able to add a public Githug (gotta keep that typo) Github project to my workspace. In the list of projects for my workspace, I added another project by HTTPS URL. Now anywhere I tap (on Chrome Android), it'll tell me that my configuration wasn't saved and that I could discard it. Unfortunately, I can't see a way of saving it anywhere? 

### Che version
Che-Theia@8740bbe using Theia@a0e635aed

### Steps to reproduce
1. Create a workspace using Quarkus template
2. Go to list of workspaces
3. Click "+" sign to the right of the workspace to add a new project
4. Choose "Git", enter https://github.com/OAI/OpenAPI-Specification
5. Try to find a way of saving the new project configuration, none is offered

### Expected behavior
Either a way of saving the workspace configuration, or some obvious indicator on why this isn't possible.

### Runtime
   - [X] other: as hosted on che.openshift.io

### Screenshots
https://drive.google.com/file/d/1OSxMjn66U6ti-CbJtCijkIz300mSakdZ/view?usp=drivesdk

### Installation method
 che.openshift.io

### Environment
   - [X] my computer (web client)
       - [X] Android using Chrome
   - [X] Cloud
       - [X] other: che.openshift.io

**Comment by ibuziuk** [comment]
@jfrantzius there is a save button for that ;-)

![adding a second project](https://user-images.githubusercontent.com/1461122/89267367-6ee0e800-d637-11ea-9879-118d2cba3c15.gif)

@sleshchenko might be a good idea to make the UX more intuitive (e.g. add save button to the top of page )

**Comment by jfrantzius** [comment]
@ibuziuk alright, as you can see in my screenshot on Chrome on an Android tablet, the Save button simply isn't visible there. I just tried in Chrome on Mac, and there I can see it :)

**Comment by sleshchenko** [comment]
It does not duplicate but is related to https://github.com/eclipse/che/issues/12989

**Comment by sleshchenko** [comment]
The described UI is not present on a new dashboard
