### ISSUE TITLE
Display cpu/memory/diskspace indicator in che-theia status bar

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17546]
### Is your enhancement related to a problem? Please describe.
Most of the time, running a workspace is restricted to quotas defined by the admin. The user will never have endless resources and be limited to it. This is understandable, but at the moment, it is hard for the user to figure out what is wrong when he is reaching quotas limit.
### Describe the solution you'd like

it would be nice if we could provide some indicator in Che-theia bottom status bar. with colors like red if it is very close to the limit.
What is the limit and the current value.
It would be nice to have that for each indicator: cpu, ram, diskspace.

### Describe alternatives you've considered
Display that in the dashboard.

**Comment by l0rd** [comment]
#17205 Is similar right @sunix ?

**Comment by sunix** [comment]
yep @l0rd duplicates
