### ISSUE TITLE
Create a Che-specific loader to replace the vertical bars

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1754]
This issue is to replace the current loader we have with vertical bars with another one. We would like to find a glowing one that uses the Che logo.
![screen shot 2016-07-14 at 10 39 31](https://cloud.githubusercontent.com/assets/392458/16896215/f7ddb096-4b41-11e6-8c28-d3344660bfae.png)

**Comment by olexii4** [comment]
@TylerJewell  It is not clear for me. Could you tell me ideas about what it should be?

**Comment by slemeur** [comment]
We are discussing it @olexii4 .

**Comment by slemeur** [comment]
@olexii4 You can replace the vertical bar with the Che logo. we will have a small animation like the following.

[loader-idea2.mp4.zip](https://github.com/eclipse/che/files/484531/loader-idea2.mp4.zip)

**Comment by olexii4** [comment]
![anim](https://cloud.githubusercontent.com/assets/6310786/18914016/ed9fb70a-8593-11e6-9803-fc4c67485b38.gif)

**Comment by olexii4** [comment]
2d 4h
