### ISSUE TITLE
[operator] Automatic updates are broken since 7.15.1 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17556]
### Describe the bug
Reproduced against dogfooding instance on OSD v4 where automatic updates are enabled: 

- che-operator version on the cluster - ` 7.16.2` 
- che version on the cluster - `7.15.0`

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
both che and operator versions and identical

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift / OSD v4 (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Logs

Not sure if related but there are multiple logs:

```
time="2020-08-04T09:45:39Z" level=error msg="Failed to detect if self-signed certificate used. Cause: routes.route.openshift.io \"test\" already exists"
time="2020-08-03T20:11:32Z" level=error msg="Failed to create test route 'test': routes.route.openshift.io \"test\" already exists"

```
might be broken due to test route creation:

```
	if len(endpointURL) < 1 {
		// Create test route to get certificates chain.
		// Note, it is not possible to use SyncRouteToCluster here as it may cause infinite reconcile loop.
		routeSpec, err := GetSpecRoute(instance, "test", "test", 8080, clusterAPI)
		if err != nil {
			return nil, err
		}
```

### Installation method
   - [x] OperatorHub

**Comment by tolusha** [comment]
That's strange.
I've just checked updating from 7.15.0 to 7.16.2 and it works.
Could you just remove test route?
`oc delete route test -n <namespace>`

**Comment by ibuziuk** [comment]
@tolusha well it is definitely an issue with updates on OSD v4 Dogfooding instance - you can check it there. Also, the same issue was reported against OCP v4

**Comment by tolusha** [comment]
I see. This this the case when a real (not a self-signed) certificate is used.

**Comment by tolusha** [comment]
Meanwhile pls use the workaround to proceed the installation.

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse/che-operator/commit/08c51a4e11614ca5ed18a34208e4f0208f27fa82

**Comment by ibuziuk** [comment]
@tolusha will wait for 7.17.0 and verify it against. Is there any impact on CRW 2.2 -> 2.3 update cc: @rhopp ?

**Comment by tolusha** [comment]
@ibuziuk 
that's a good question.
it is better to apply the same fix for 7.16.x branch.

**Comment by alexeykazakov** [comment]
> Meanwhile pls use the workaround to proceed the installation.

What is the workaround?

**Comment by tolusha** [comment]
The workaround is to delete `test` route
`oc delete route test -n <namespace>`

**Comment by alexeykazakov** [comment]
I've deleted the test route but the che server was not re-deployed. It's still running an old version.

**Comment by tolusha** [comment]
Scale down/up che-operator deployment.
Eclipse Che will start deploying from the beginning.
