### ISSUE TITLE
Add syntax coloration to machine outputs when starting a workspace

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1755]
When we start a workspace with the crane loader, we display the outputs with syntax coloration. We need to do the same when loading the ws in the IDE.
![screen shot 2016-07-14 at 10 49 26](https://cloud.githubusercontent.com/assets/392458/16896225/2d8a6ee6-4b42-11e6-8d68-101e2ed35b44.png)

**Comment by vzhukovs** [comment]
Time spent: 1d.
Time spent on code review: 2d 4h.
