### ISSUE TITLE
Passing the JWT token in the URL 

### ISSUE THREAD

**Issue by esubah1989** [eclipse-che/che#17559]
### Is your enhancement related to a problem? Please describe.

I have performed some penetration test on Che and it seems like the JWT token is passed via URL. Passing JWT token through URL is not safe.
### Describe the solution you'd like

 I would rather pass the JWT token via the body of the POST request than passing it via URL.

**Comment by gyezheng** [comment]
Any update for the issue? Thanks!

**Comment by kristinochka** [comment]
Would like to add some more information here. The following urls are effected:
https://routeavu3mjxb-codeready.apps.mycluster.com/connect?token=eyJhbGciOiJSUzI1NiIs
https://routeavu3mjxb-codeready.apps.mycluster.com/connect?token=eyJhbGciOiJSUzI1NiIsIm&clientId=2
