### ISSUE TITLE
Adapt Che Theia to upstream changes

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#17550]
### Is your task related to a problem? Please describe.
A few PRs were merged today to Theia project.
Our tests are failed after that.
We need provide some adaptation on che-theia side.

### Describe the solution you'd like
Che Theia needs to be adapted to upstream changes.

**Comment by azatsarynnyy** [comment]
ATM Che Theia is switched to Theia 1.4.0 https://github.com/eclipse/che-theia/pull/821
It should be fixed by adapting Che Theia to new Theia FS API https://github.com/eclipse/che/issues/17357 if no other upstream commits contain breaking changes.
