### ISSUE TITLE
Cannot using debug (Spring-boot, gradle)

### ISSUE THREAD

**Issue by yu-sungho** [eclipse-che/che#17566]
I'm trying to use debug now.

bug that error occurs.
"Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<"

build.gradle setting information

bootRun {
    jvmArgs=["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0.0:5005"]
}

Please check. Thank yo.

**Comment by sparkoo** [comment]
@yu-sungho can you please share your devfile, version of che, how did you install your che, etc. ?

**Comment by ericwill** [comment]
No response in awhile. Please file a new ticket if you continue to experience the issue -- thanks.
