### ISSUE TITLE
Add ability to download workspace starting outputs from IDE loader

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1756]
We should be able to download the logs from the console. We need to make another way, simpler and more obvious so that the user can download the outputs in case something goes wrong.

**Comment by slemeur** [comment]
Attached corresponding mockup.
New loader in the IDE + download logs button.

![loading-workspace-in-ide - v2](https://cloud.githubusercontent.com/assets/1636769/17665000/5e13c792-62f8-11e6-956a-9f77eddd0e55.png)

**Comment by slemeur** [comment]
Updated design.

![loading-workspace-in-ide - v2](https://cloud.githubusercontent.com/assets/1636769/18133994/11ffe08c-6f9d-11e6-81c1-b9668567099a.png)

We need to make the part for the outputs being maximized

We will also take care about making the width of the tree in the Console panel as minimal as possible.

**Comment by vitaliy-guliy** [comment]
Spent 3 days
