### ISSUE TITLE
Remove old RELATED_IMAGE_* entries for obsolete che images every sprint (automation / release process)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17562]
### Is your enhancement related to a problem? Please describe.

Today, the CSV for Eclipse Che 7.16.x contains many copies of old machine exec and theia plugins, when only ONE of them will every be installed via the OLM operator. Why carry all that old garbage along? Includng anything more than the latest version means that we need a mechanism to differentiate the old and new versions of containers. Do we also need old versions of sidecars?

```
RELATED_IMAGE_che_theia_plugin_registry_image_ x 37
RELATED_IMAGE_che_machine_exec_plugin_registry_image_ x 36
RELATED_IMAGE_che_theia_endpoint_runtime_binary_plugin_registry_image_ x 30
RELATED_IMAGE_che_sidecar_camelk_plugin_registry_image_ x 8
RELATED_IMAGE_che_sidecar_openshift_connector_plugin_registry_image_ x 4
RELATED_IMAGE_coder_plugin_registry_image_ x 3
RELATED_IMAGE_che_sidecar_go_plugin_registry_image_ x 3
RELATED_IMAGE_che_sidecar_dependency_analytics_plugin_registry_image_ x 2
RELATED_IMAGE_che_sidecar_dotnet_plugin_registry_image_ x 2
...
```

Right now, because we have so many references to multiple copies of the same images (eg., 7.16.2, 716.1, 7.16.0, 7.15.2, 7.15.1, .... and all the nightly 9.9.9.`timestamp` ones) we use base32 to encode the tag as a sha:

```
                      - name: RELATED_IMAGE_coder_plugin_registry_image_GIXDCNJSGMWXM43DGEXDGOBOGEWWG2DFBI______
                        value: docker.io/chinodesuuu/coder@sha256:6387eee627678d36fa1313017cf5620890f25559df8b24cb53e1d5f4ab6f4726
                      - name: RELATED_IMAGE_coder_plugin_registry_image_GIXDCNRVGAWXM43DGEXDGOJOGIWWG2DFBI______
                        value: docker.io/chinodesuuu/coder@sha256:1af9c45c3f8c9836dba10c4a2c7b43915bc04fa4b9b9cc598d4bad5cf036817e
                      - name: RELATED_IMAGE_coder_plugin_registry_image_NZSXQ5AK
                        value: docker.io/chinodesuuu/coder@sha256:77f51200f6f9ff62551794be48a3497e464c93f2420877253b98de3e041e0e9d

```

But this results in an encoded name that's not human readable, AND introduces a dependency on base32 encoding (which has proven to be challenging to make work in the CentosCI build pipeline for Eclipse Che automated releases.

### Describe the solution you'd like

Could we solve two problems at once by:

a) removing all the dupe entries, which obviate the need for encoding, and 
b) switch to a simpler conversion method that instead of base32 simply replaces "bad" characters not allowed in env vars with underscores, eg.,

```
$➔ echo "quay.io/eclipse/che-plugin-artifacts-broker:v3.2.0" | tr "./:@=-" "_" | sed -r -e "s#quay.io#RELATED_IMAGE#"
RELATED_IMAGE_eclipse_che_plugin_artifacts_broker_v3_2_0
```

### Describe alternatives you've considered

Or, we could:

* figure out how to install base32 in Centos CI for the RHEL7 build pipeline (so far we've only found content sets / rpm repos for RHEL 8)
* build this part of the release process pipeline on RHEL8 instead of 7
* concoct some perl or node based base32 solution that doesn't rely on the rpm-installed cli tool

### Additional context

The reason this is a problem is that we're trying to automate the generation of and validation of PRs for each Che release to the community operators operatorhub. Since base32 isn't available in the current CentosCI environment, PR generation fails and must be done manually. 

* Greater context for automating Che release process, see https://github.com/eclipse/che/issues/17562
* Greater context for RELATED_IMAGE_ entries, see https://github.com/eclipse/che/issues/16815

**Comment by tolusha** [comment]
If we don't need obsolete images then we have to remove them from plugin-registry
https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/eclipse/che-machine-exec-plugin

**Comment by benoitf** [comment]
this PR https://github.com/eclipse/che-plugin-registry/pull/562 removes version of che-theia + che-machine-exec older than 3 minor versions (semver)

**Comment by nickboldt** [comment]
So we've manually cleaned out old versions... do we want to run this process every 3 weeks to purge old stuff with every Che 7.y.0 release?

**Comment by l0rd** [comment]
> So we've manually cleaned out old versions... do we want to run this process every 3 weeks to purge old stuff with every Che 7.y.0 release?

@nickboldt makes sense. Should we use this issue for the automation?

**Comment by nickboldt** [comment]
+1, I've renamed it accordingly.

**Comment by nickboldt** [comment]
Eric said:
> it will become obsolete once we change to using only the latest plugins in the registry
> so you may just want to mark it as 7.x

**Comment by nickboldt** [comment]
Fixed by https://github.com/eclipse/che/issues/18183 and https://github.com/eclipse/che-plugin-registry/pull/672

... Assuming we don't start adding multiple versions again. :)
