### ISSUE TITLE
Provide more space to the console when the workspace is booting

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1757]
When we start the workspace we are displaying the machine outputs.  The default area we are using is not enough, it does not let the user being able to read all the information.  We should make the area for the machine outputs higher when we are starting it.  Once the machine is booted, we can automatically resize the output to be the default one.

Should take 75% of the height like here:
![_thumb_81663](https://cloud.githubusercontent.com/assets/392458/16896238/8ff487b0-4b42-11e6-9e22-e741e65d924c.png)

**Comment by TylerJewell** [comment]
@slemeur I do not like this design.  I think it's better to leave the console alone, or make it full screen so that project explorer and editor is hidden.

**Comment by slemeur** [comment]
Please refer to https://github.com/eclipse/che/issues/1758 for the mockup

**Comment by vitaliy-guliy** [comment]
Resolved by PR https://github.com/eclipse/che/issues/1758
