### ISSUE TITLE
Unable to create factories in eclipse che 7.17

### ISSUE THREAD

**Issue by veeramanikandanvv** [eclipse-che/che#17574]
We are unable to create factories  as the application throws error message as "this factory is using old workspace definition".

No workspaces loaded while creating factories.

Eclipse che 7.17.0
Multiuser with single host.
Deployed over kubernetes cluster

**Comment by skabashnyuk** [comment]
Expected behavior. Sharing with factories would be replaced with UserDevfile functionality https://github.com/eclipse/che/issues/16875.
Old code would be removed as https://github.com/eclipse/che/issues/17390
