### ISSUE TITLE
[operator] - don't set LivenessProbe when debugging che-server

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17581]
### Is your enhancement related to a problem? Please describe.

I often attach a debugger to che-server and stop execution with breakpoints. If this takes a bit longer (I think 30s `FailureThreshold(3)` * `PeriodSeconds(10)`), liveness probe then restarts the che-server pod, which destroys debug session (and cause other issues like workspace stuck in starting state without an option to get out of it, etc.)

### Describe the solution you'd like

Don't set livenessProbe for che deployment if `cheDebug=true` (see https://github.com/eclipse/che/issues/17581#issuecomment-669188166)

### Describe alternatives you've considered

If `cheDebug=true` set `FailureThreshold` to some huge number.

Or have the `FailureThreshold` configurable with `CheCluster` CR like:
```
server:
  cheLivenessProbeFailureThreshold: 3
```

Currently `LivenessProbe` values are hardcoded -> https://github.com/eclipse/che-operator/blob/master/pkg/deploy/deployment_che.go#L192

**Comment by tolusha** [comment]
Adding LivenessProbe to this section should help
https://github.com/eclipse/che-operator/blob/master/pkg/deploy/deployment_che.go#L291

**Comment by sparkoo** [comment]
> Moving LivenessProbe to this section should help
> https://github.com/eclipse/che-operator/blob/master/pkg/deploy/deployment_che.go#L291

That should work. I've updated the description to have this as main proposed solution.

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che-operator/pull/399
