### ISSUE TITLE
Display loading steps when booting ws from IDE

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1758]
On UD, we were displaying explanations about what the system is doing while we are booting workspace runtime.  We need to provide a similar mechanism in the IDE. We will display a small loading view which will display the steps of loading and way to download outputs.
![loading-workspace-in-ide](https://cloud.githubusercontent.com/assets/392458/16896266/68bffbec-4b43-11e6-9b06-cf889c66617b.png)

**Comment by TylerJewell** [comment]
1. No popup - needs to be blended into the IDE widgets that are already there.
2. The download outputs need to be also in the same location.

Not a fan of using the editor space to show this information - it doesn't feel right. That is an editor location, not an information heads up display.  Might be better to have this information shown within the tool bar, or may be within the lower right corner, the way we handle maven dependencies.

**Comment by slemeur** [comment]
Updated design. We will show a toast loader at the top of the screen. It will go over the IDE layout.

![loading-workspace-in-ide - v2](https://cloud.githubusercontent.com/assets/1636769/17036917/a6a556ec-4f8e-11e6-8c5b-6eca98cc93de.png)

(3 steps detailed in the mockup)

**Comment by TylerJewell** [comment]
+1 on concept.

**Comment by slemeur** [comment]
Add updated design #1756 

![loading-workspace-in-ide - v2](https://cloud.githubusercontent.com/assets/1636769/18165533/112a92d4-7046-11e6-9a56-4d2d73d55be7.png)

We need to make the part for the outputs being maximized

We will also take care about making the width of the tree in the Console panel as minimal as possible.

**Comment by ashumilova** [comment]
resolved
