### ISSUE TITLE
Don't use digest for quay.io/eclipse/che-sidecar-workspace-data-sync:latest image

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#17580]
### Is your task related to a problem? Please describe.
Got this error :
```
Pulling image "quay.io/eclipse/che-sidecar-workspace-data-sync@sha256:88d0125837d5a57cb24bb3ed81e6a8f4119a5043b7926bd2bd01710854c44f10"
Failed to pull image "quay.io/eclipse/che-sidecar-workspace-data-sync@sha256:88d0125837d5a57cb24bb3ed81e6a8f4119a5043b7926bd2bd01710854c44f10": rpc error: code = Unknown desc = Error reading manifest sha256:88d0125837d5a57cb24bb3ed81e6a8f4119a5043b7926bd2bd01710854c44f10 in quay.io/eclipse/che-sidecar-workspace-data-sync: manifest unknown: manifest unknown
Error: ErrImagePull
```
Installed with Operator: Eclipse Che 7.16.2 provided by Eclipse Foundation
### Describe the solution you'd like
Adding `quay.io/eclipse/che-sidecar-workspace-data-sync:latest` to the [digestExcludeList](https://github.com/eclipse/che-operator/blob/master/olm/digestExcludeList#L3) should fix the problem

**Comment by ibuziuk** [comment]
@vparfonov this is for 7.17 ?

**Comment by tolusha** [comment]
@ibuziuk right, I am going to fix it ASAP
