### ISSUE TITLE
Che docs site does not have search

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17588]
### Describe the bug
Search is missing on Che documentation web site.
Sometimes it takes more time to find some information without a search. It could especially happen when one need more information about a specific option.

### Che version
Che 7.x

### Steps to reproduce
N/A

### Expected behavior
A search bar is present in Che docs web site.

### Runtime
N/A

### Additional context
In older versions of Che docs search was present.

**Comment by benoitf** [comment]
should have a way when switching to antora https://github.com/eclipse/che-docs/pull/1291

**Comment by sunix** [comment]
maybe we could temporary enable a search with Google CSE https://cse.google.com/
https://twitter.com/eclipse_che/status/1283363714171838465

**Comment by sunix** [comment]
it has been merged: https://github.com/eclipse/che-docs/pull/1454
