### ISSUE TITLE
Storage type switcher does not appear on Hosted Che

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17590]
### Describe the bug
The storage type section in the create custom workspace page does not show up on Chrome:

![Screenshot from 2020-08-06 13-09-52](https://user-images.githubusercontent.com/16168279/89561276-421f0300-d7e6-11ea-8220-b9b6612e684f.png)

### Version
- Hosted Che 7.16.2
- Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- Firefox 79.0 (64-bit)

### Steps to reproduce
1. Navigate to che.openshift.io
2. Navigate to create custom workspace tab

### Expected behavior
Storage type switcher shows options

### Additional context
I wonder if this might be related to Hosted Che setting a default value for persistVolumes?

**Comment by ibuziuk** [comment]
@amisevsk I think this is related to the way how the UD is injected in upstream and downstream (next version is used during the build):

- https://github.com/redhat-developer/rh-che/blob/master/dockerfiles/che-fabric8/Dockerfile#L9
- https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile#L12

**Comment by sleshchenko** [comment]
So, it's caused by missing `che.workspace.storage.available_types` from Che Server side
![Screenshot_20200817_154435](https://user-images.githubusercontent.com/5887312/90397557-b12b1000-e0a0-11ea-98f1-b7e1991b021e.png)
It should not be an issue for 7.17.0 but we should reconsider how bug fix release is done and next version should not be used there.

**Comment by ibuziuk** [comment]
This looks like Hosted Che specific issue and the correct build arguments should be used for Hosted Che dockerfile builds 
`--build-arg:"CHE_DASHBOARD_VERSION=${CHE_VERSION},CHE_WORKSPACE_LOADER_VERSION=${CHE_VERSION}"  

https://github.com/redhat-developer/rh-che/blob/master/.ci/cico_do_docker_build_tag_push.sh

**Comment by ibuziuk** [comment]
PR sent - https://github.com/redhat-developer/rh-che/pull/1979
