### ISSUE TITLE
Cannot import chectl-generated server CA cert

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17591]
### Describe the bug
The docs describe the process of importing certificates for locally-deployed clusters [here](https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#importing-self-signed-tls-certificates-to-browsers_installing-che-in-tls-mode-with-self-signed-certificates)

However, following these steps on Chrome fails, with Chrome reporting that the certificate (both chectl exported and the certificate in the browser) is invalid

```
Certificate Import Error
The Private Key for this Client Certificate is missing or invalid
```

The instructions work on firefox.

### Che version
- Che Nightly
- `chectl` version `chectl/0.0.20200731-next.a889d06 linux-x64 node-v10.22.0`
- Chrome Version 84.0.4147.105 (Official Build) (64-bit)

### Steps to reproduce
Deploy Che on minikube and attempt to add certs to Chrome [as instructed](https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#importing-self-signed-tls-certificates-to-browsers_installing-che-in-tls-mode-with-self-signed-certificates)

**Comment by amisevsk** [comment]
It looks like Chrome [removed](https://support.google.com/chrome/thread/28404872?hl=en) the settings page for adding certificates in version 80. It doesn't seem to be possible to add self-signed certs to Chrome anymore.

**Comment by mmorhun** [comment]
I have Chrome 84.0.4147.105 and I can import self-signed certificates.

**Comment by tolusha** [comment]
@amisevsk 
Do you have running instance to check the certificate?

**Comment by amisevsk** [comment]
Woops, I was trying to add it to the wrong section -- my bad.
