### ISSUE TITLE
Remove the current workspace runtime loader

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1759]
Remove this in favor of other loaders.
![screen shot 2016-07-14 at 14 00 45](https://cloud.githubusercontent.com/assets/392458/16896278/c0b5be18-4b43-11e6-9f73-cea3b20156ee.png)

**Comment by TylerJewell** [comment]
Please see my other comments in the epic issues. This strikes me as a good widget and a proper place to show the status, stevan.  It'll also be quicker to be done. @slemeur

**Comment by vitaliy-guliy** [comment]
Fixed by PR https://github.com/eclipse/che/issues/1758
