### ISSUE TITLE
Add repo branching/tagging to che-docs repository

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17596]
### Describe the bug
AFAIK documentation is tied to a given che version but it's not tagged since 7.12.1

### Expected behavior
https://github.com/eclipse/che-docs should contains che version tags

![image](https://user-images.githubusercontent.com/436777/89660430-9e128600-d8d1-11ea-878d-347054059786.png)

**Comment by nickboldt** [comment]
PR: https://github.com/eclipse/che-docs/pull/1457

**Comment by nickboldt** [comment]
Done as of yesterday's release of 7.17.2
