### ISSUE TITLE
My che container starts very slow

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#176]
From  @eivantsov's video of starting che container in a digital ocean server, it just uses less than 3 minutes in total (including downloading che images, creating workspace, until it's ready): 

https://www.youtube.com/watch?v=UVucYKI5NHs

But for me, most time of the it's pretty slow. The fastest record is about 10 minutes, and most of the time, it needs me 20 minutes or so to do the same thing as in eivantsov's video. And the longest record is 60 minutes (starting che container: 41minutes, other things 20 minutes)

So I wonder what's your configurations in your digital ocean? Mine is:
- 4GB Ram
- 60GB SSD Disk
- San Francisco

**Comment by TylerJewell** [comment]
I have never seen Che take more than a couple minutes to start even when I am running it within vm that only has 2 gb of ram.

-Tyler

On Sun, Jan 10, 2016 at 9:55 PM -0800, "freewind" notifications@github.com wrote:

From  @eivantsov's video of starting che container in a digital ocean server, it just uses less than 3 minutes in total (including downloading che images, creating workspace, until it's ready): 

https://www.youtube.com/watch?v=UVucYKI5NHs

But for me, most time of the it's pretty slow. The fastest record is about 10 minutes, and most of the time, it needs me 20 minutes or so to do the same thing as in eivantsov's video. And the longest record is 60 minutes (starting che container: 41minutes, other things 20 minutes)

So I wonder what's your configurations in your digital ocean? Mine is:

4GB Ram
60GB SSD
Disk San Francisco 1

**Comment by ghost** [comment]
Are you talking about Che in Docker right now?

I have just tried it on a clean Digital Ocean machine, and it looks ok for me.

What I have noticed with Digital Ocean, is that when you start a clean machine, install java and run tomcat, the war gets deployed very slowly. To fix it, I had to change Java security options - https://www.digitalocean.com/community/questions/fresh-tomcat-takes-loong-time-to-start-up

You may change$JAVA_HOME/jre/lib/security/java.security and replace securerandom.source=file:/dev/random with securerandom.source=file:/dev/urandom

**Comment by ghost** [comment]
@freewind any update on this one? Did you try using other VM providers to make sure this is a Digital Ocean thing? Did you try my instructions?

**Comment by freewind** [comment]
@eivantsov Sorry I've taken a long sick-leave these days, will continue the work maybe next week. I will report if I have any updates on these issues. Thanks for your help

**Comment by TylerJewell** [comment]
@freewind Could you see solution to #253.  This may be related.

**Comment by freewind** [comment]
@TylerJewell, thanks for the link, but my che is always running on the digital ocean, not on a local virtual machine.

I tried with the `codenvy/che:nightly` and `4.0.0-RC3` yesterday, the first several times the starting was very fast, just about 10 or 20 seconds, but suddenly it began to cost more than 15 minutes to start the server, without any changes. It didn't be faster even if I rebooted the server.

**Comment by ghost** [comment]
Are you still running Docker in Docker or following https://eclipse-che.readme.io/docs/usage-docker?

**Comment by freewind** [comment]
@eivantsov I went this way: https://eclipse-che.readme.io/docs/usage-docker#using-docker-syntax, is it the "docker in docker" you mentioned?

To make it accurate, I used this command: 

```
docker run -ti --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage -e DOCKER_MACHINE_HOST=198.199.105.97 codenvy/che:nightly
```

The only difference is the `-e DOCKER_MACHINE_HOST=198.199.105.97` part.

**Comment by ghost** [comment]
It looks like you are constantly running into this issue - https://www.digitalocean.com/community/questions/fresh-tomcat-takes-loong-time-to-start-up

We're investigating a fix - exporting the right JAVA_OPST for both Che server and ws-agent.

**Comment by freewind** [comment]
@eivantsov Thanks so much, I just install `apt-get install haveged` as that page gives, and it's starting very fast now.

I remember you have given me this link before and I should followed that solution, and I totally forget to install it in new servers. Thanks again!

**Comment by freewind** [comment]
Let me repeat the solution again here for anyone who needs it: 

```
apt-get install haveged
```

**Comment by ghost** [comment]
We will add these opts for both servers anyway. it looks like it is a good thing to do.

**Comment by jiri-kulik** [comment]
Hi,
I know this is old but found it when researching the same issue on google cloud. Is it possible that:
1. the issue still exists
2. applies also for google?
The start takes > 15 minutes for me, during which cpu is used just for a few seconds.
Haven't tried to install haveged yet, still searching for possible cause.
