### ISSUE TITLE
Replace wsmaster by eradicating problematic language

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17602]
### Is your task related to a problem? Please describe.
`wsmaster` word is problematic and needs to be replaced

### Describe the solution you'd like
Here are current proposals for the new name

- [ ] wsserver
- [ ] cheserver
- [ ] api
- [ ] controller

### Additional context
if you have other proposals, please edit or comment this issue.

**Comment by amisevsk** [comment]
@benoitf @l0rd Not sure if this one would be considered P1 or P2 priority. I'm setting P2 for now but feel free to reassign. 

I'll also add a :-1: to the name `controller`, since we've taken to calling the in-development operator the controller.

**Comment by benoitf** [comment]
yes agree @amisevsk I put the `controller` as I heard it but probably it will not be picked up because the role of the controller is shifting to a different codebase

**Comment by nickboldt** [comment]
wsserver seems the simplest solution to me, since it's the (master) server for workspaces.

**Comment by benoitf** [comment]
@nickboldt yes the thing is that server is being "reduced" to REST services with the new dev workspace controller.

**Comment by l0rd** [comment]
That's a subtask of https://github.com/eclipse/che/issues/17454

**Comment by nickboldt** [comment]
so... is this issue done?

**Comment by nickboldt** [comment]
Marking this resolved as things got merged and no one has commented since Sep 2021.
