### ISSUE TITLE
Improve loader when snapshotting

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1760]
When we are snapshotting the workspace from the IDE - we are displaying a ugly general loader.
We need to improve this loader and be more explicit about what the system is doing.  We will reuse the mecanism done in #1758 .

![restart](https://cloud.githubusercontent.com/assets/1636769/18316200/04069d0e-751a-11e6-9618-ada933306c14.png)

**Comment by vitaliy-guliy** [comment]
Spent 4 hours
