### ISSUE TITLE
[Hosted Che] Cannot create a workspace from quarkus stack: exceeded quota

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#17611]
### Describe the bug

Cannot create a workpsace from quarkus stack on che.openshift.io
The workspace needs more resources than is allowed for the user

### Che version

 - [x] latest

### Steps to reproduce

1. Create a workspace based on quarkus stack

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots

![Screenshot from 2020-08-11 14-37-39](https://user-images.githubusercontent.com/1655894/89893479-1b473f00-dbe1-11ea-9eb4-0ecee09d8cd0.png)

**Comment by codingme** [comment]
I have the exact same trouble, please!

**Comment by ibuziuk** [comment]
Closing - the issue should be fixed on workspaces.openshift.com
che.openshift.io EOL day was March 1st
