### ISSUE TITLE
Improve wizard to restart workspace

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1761]
When you stop a workspace we show a dialog with some problems.  User is in the context of a workspace, he does not need to select which worksapce to restart. The workspace to be restarted is the one selected in the left nav bar. We have a second dialog to ask the user if he wants to restart from snapshot.  We can improve this wizard.

**Comment by TylerJewell** [comment]
@slemeur - not ok with using the popup design.  But whatever we do for the workspace loading, we would reapply here.

**Comment by slemeur** [comment]
Updated design. We'll use a toast at the top of the IDE

![restart](https://cloud.githubusercontent.com/assets/1636769/17036885/82eb5d82-4f8e-11e6-87f3-564ad3658b0f.png)

**Comment by vitaliy-guliy** [comment]
Spent 3 days
