### ISSUE TITLE
[async storage] Run async service in Deployment instead creating a Pod directly

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17616]
## Summary
Currently, when async storage is named for a workspace, a k8s pod is created to host the container. However, in the past, we have had issues where the cluster automatically kills pods after some time period, and this was the original reason we started using deployments instead of pods to host Che workspaces on k8s/OpenShift. 

We currently have https://github.com/eclipse/che/issues/17507 open to add an automatic timeout, but this issue is somewhat different, as the pod deadline means the pod can be removed while it's actively being used.

## Relevant information
Original issue for workspaces: https://github.com/redhat-developer/rh-che/issues/668 and the PR it lead to: https://github.com/eclipse/che/pull/10021

**Comment by l0rd** [comment]
Good question @amisevsk. We should use a deployment. Directly creating a Pod is discouraged. I don't know why we made that choice cc @vparfonov.

**Comment by vparfonov** [comment]
> Good question @amisevsk. We should use a deployment. Directly creating a Pod is discouraged. I don't know why we made that choice cc @vparfonov.

Update issue description and will rework it
