### ISSUE TITLE
Dashboard devfile editor shouldn't reformat the devfile

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17614]
### Describe the bug
Each time we edit the devfile of a workspace, or after creating one from a devfile. The devfile is being reformat (order of items are changed, tables in one line splitted in multiple lines, etc...).
Few annoying use cases:
- User would like to sync the devfile with the original one in Github after having made some changes.
- User would like to have `alias` in the first line of a component because it would make your file more readable ... but it is moved to another line ... somewhere else.
- User would like to have an empty line between components for readability. but it is removing these lines.
- User would like to have `apiVersion` in the first lines of the devfile, but it goes after the components section and before the che commands.

**Comment by sleshchenko** [comment]
I'm not sure we are able not to and should not reformat the devfile. It's not possible while we store it in database as an object but not text/json entry...
If we take into account kubernetes API - it also reformats user's defined object.
But +1 to agreed on the common meaningful format and it's supposed to be solved in https://github.com/eclipse/che/issues/16797. So, closing it as duplicate. @sunix Let me know if the referenced issue does not fully cover this one.
