### ISSUE TITLE
Inconsistent labels on Dashboard Next

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17617]
Dashboard Next includes 3 different ways to say "get started / getting started / get started page", and two ways to suggest how to create a custom workspace.

![image](https://user-images.githubusercontent.com/227597/89926336-bab10580-dbd2-11ea-8a01-dd5d2b592aad.png)

We should try to be consistent here with the labelling.

**Comment by nickboldt** [comment]
Maybe we could adopt the naming convention from other products and instead of "Get Started" and "Sample" we could simply refer to all these as Quickstarts:

![image](https://user-images.githubusercontent.com/227597/89927370-3495be80-dbd4-11ea-980b-9316b22d9293.png)

(colours for emphasis, not to suggest we want red text on grey.)

**Comment by l0rd** [comment]
The "Get(ting) started" inconsistency exists in the current dashboard too:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/606959/90007294-c667ff00-dc9a-11ea-9fce-6d50f2724838.png">

Before replacing `Get Started` with `QuickStarts` I would like to ear from @beaumorley @parvathyvr @rkratky what they think about it.

As a quick fix I would `s/Getting started/Get started/` and `s/Create Workspace/Custom Workspace/` as you are suggesting.

**Comment by beaumorley** [comment]
@nickboldt @l0rd FYI We just launched a new feature in the Dev Console for OpenShift called "Quick Starts". It will be available in 4.6. It is for a tutorial type experience. I propose we don't use that right now since it may be confusing for integrated experience. We can think about terms. Probably most important is to use whatever we choose consistently. Let me put together some thoughts.

**Comment by nickboldt** [comment]
@sleshchenko since Dashboard next is coming real soon to CRW, can we prioritize this item for 7.24 or 7.25?

**Comment by sleshchenko** [comment]
@nickboldt thanks for raising it.
@beaumorley @ParvathyRV do we have a design suggestion for that?

**Comment by sleshchenko** [comment]
It should be fixed with redesigning of the Get Started and left-nav bar
https://github.com/eclipse/che/issues/18975
https://github.com/eclipse/che/issues/18980
