### ISSUE TITLE
Devfile documentation points to (non existing) embedded documentation

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17628]
### Describe the bug

Dashboard devfile editor has a link at the bottom to the Documentation. That link references a URL to the embedded documentation: `https://<che-host>/docs/che-7/using-developer....`

<img width="950" alt="image" src="https://user-images.githubusercontent.com/606959/90144308-f5f03780-dd7e-11ea-8e3c-aece1644e7de.png">

### Che version

7.17

**Comment by sleshchenko** [comment]
Two points which should be figured out:
1. Did we stop package docs into Che by default?
2. What is the article URL that should be referenced, https://www.eclipse.org/che/docs/che-7/configuring-a-workspace-using-a-devfile/ ?

**Comment by benoitf** [comment]
> for 1.

https://github.com/eclipse/che/issues/16779

**Comment by sleshchenko** [comment]
The link in the footer needs to be updated as well, at least on Hosted Che
![Screenshot_20200826_151459](https://user-images.githubusercontent.com/5887312/91302312-f04b1680-e7ae-11ea-9da3-a2a47c08a02a.png)
