### ISSUE TITLE
CRW Openshift Connector plugin - inClusterUser does not have access to cluster projects

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#17626]
### Describe the bug
By default, the openshift-connector-plugin does not work with CRW.
The pre-logged-in user does not see the projects that are available on the cluster.
There is no way to create new projects without the plugin being re-logged in with a different user from the cluster.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
* Start any workspace
* Press CTRL+Shift+J
* Install openshift-connector-plugin and reload the workspace
* Open openshift-connector plugin section on the left side of the IDE
* Wait for the plugin to load
* Empty cluster is displayed
* Right-click on the cluster and logout
* Login with cluster admin account
* The projects are now visible and you can create your own projects in the namespaces

### Expected behavior
* Required and proper project is displayed to the `inClusterUser` account and appropriate permissions are set

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift 
```
Client Version: 4.3.5
Server Version: 4.5.5
Kubernetes Version: v1.18.3+08c38ef
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
To be added

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other - ocp45.crw-qe.com
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by sunix** [comment]
Hello,
In Che https://github.com/eclipse/che/issues/15261 it should work
If you have the issue with CRW, please open a issue in https://issues.redhat.com/browse/CRW

**Comment by l0rd** [comment]
Closing as this has been fixed on Che 7.12 and from what I understand you are testing latest CRW (2.2) that is based on Che 7.9.x.
If that's a CRW 2.3 issue please open an issue on CRW Jira.
If that's a Che 7.12 or higher issue please re-open this issue.

**Comment by MichalMaler** [comment]
CRW issue is here
https://issues.redhat.com/browse/CRW-1158. It should be actual for 2.3

**Comment by ScrewTSW** [comment]
@l0rd yes, the issue is opened in Jira that @MichalMaler linked. It's related to latest CRW 2.3
