### ISSUE TITLE
OpenShift OAuth for Che doesn't work on OpenShift 4.5

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#17632]
### Describe the bug

Openshift oauth for Che doesn't work on OpenShift 4.5.4
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Deploy che: `chectl server:start -p=openshift --os-oauth`
See a warning:
```
❗ [WARNING] 'os-oauth' flag was disabled, because Openshift oauth hasn't got any identity providers. https://docs.openshift.com/container-platform/4.1/authentication/understanding-identity-provider.html#identity-provider-overview_un
```

### Expected behavior

The openshift oauth must be applied
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tolusha** [comment]
This warning means that it isn't possible to deploy Eclipse Che with OpenShift OAuth when there are no identity providers.
Pls add one (https://docs.openshift.com/container-platform/4.1/authentication/understanding-identity-provider.html#identity-provider-overview_understanding-identity-provider) and try again.
