### ISSUE TITLE
Missing Token Revocation on JWT in Che container

### ISSUE THREAD

**Issue by ArvinB** [eclipse-che/che#17639]
### Describe the bug
The JWT token is used as an authentication mechanism in the application. As per the claims in the token, there do not seem to have a token revocation mechanism in place.
The tokens are always advisable to have a revocation mechanism considering the scenario of the stolen token. In the case of multi-factor authentication where the user needs to provide the user credentials as well as additional identity proofs, stolen tokens are much risky over the stolen user credentials. The reason why token revocation is essential.
In the application, the token revocation mechanism is missing.

This is an issue because the same token can be used to log back into the workspace even after the user has logged out. In case of stolen tokens, the attacker can easily impersonate the victim.

Note: The same issue is applicable on API URLs. Since there is no explicit logout API in APIs this was not explicitly reported for APIs. It was noted that even after generating a new auth token, the previous token can be used to fetch the details.

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1.Login to the application.
2.Generate the JWT token.
3.Logout from the application.
4.It is observed that still we can execute the APIs with the JWT token (which is generated in step2).

### Expected behavior
The JWT token should be revocable after logging out of the session

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) - 4.3.28_1532
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/1202744/90161089-9e42d380-dd60-11ea-89ee-6b3ed4bcddda.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other - IBM Cloud
   - [ ] other: please specify

### Additional context

**Fix Recommendation:**
Provide the mechanism via custom claims in the token to revoke specific token. Set a reasonable expiration time on tokens
Delete the stored token from client side upon log out
Enforce Rate limit for token generation process.

**Comment by gyezheng** [comment]
Any update for the issue? Thanks!

**Comment by sleshchenko** [comment]
As far as I know JWT Token you referencing is a machine token. To revocate it's needed simply to restart a workspace.
Hope it can help a bit, but it does not seem to solve the issue.

**Comment by ArvinB** [comment]
Lets close this issue. Another penetration test is due up this year with a newer version of Keycloak. Taken into advisement to ensure a restart of the workspace will eliminate the machine token so that it is revoked.
