### ISSUE TITLE
Implement additional CA bundle propogation for non-OpenShift 4 infrastructures

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17634]
### Is your enhancement related to a problem? Please describe.
As of now, cluster CA bundle might be propagated to Che components only on Openshift 4 infrastructure.
This should be also supported on Kubernetes and Openshift 3

### Describe the solution you'd like
In case of Openshift 4 (only) it is possible to request from the Openshift cluster a config map with CA bundle, which then is propagated to Che components by Che. In case of other platforms we may require the configmap from a user (Che admin) instead of requesting it from the cluster. However, please note, that CA bundle provided by Openshift cluster many certs including commonly trusted one. And I do not think that it makes sense to request them all in case of manual config map creating. So here we have to merge (not replace) this configmap's certs with Che component's trust stores (it is done in most - if not all - cases).

### Additional context
This is actual if due to some reasons, some endpoints is secured by other CA certificates. For example: external SSO, proxy with SSL Bump, a resource (a project as zip file) served outside cluster or inside cluster but with custom TLS certificate and so on...

**Comment by tolusha** [comment]
Changes are needed to be ported into master branch before starting working on the issue
https://github.com/eclipse/che/pull/18264

**Comment by mmorhun** [comment]
Looks like the changed [already](https://github.com/eclipse/che/pull/18280) ported.

**Comment by mmorhun** [comment]
done
