### ISSUE TITLE
Support AntiClickJacking in Che container

### ISSUE THREAD

**Issue by PrasangAPrajapati** [eclipse-che/che#17636]
### Describe the bug
Che application does not use X-frame-Options header in the HTTP response, which may lead to Clickjacking attack. Most modern Web browsers support the X-Frame-Options HTTP header. Ensure it's set on all web pages returned by che application URL. Attacker can lure victim to enter sensitive information such as Username, Password etc on the transparent element, controlled by him/her, and steal the information.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

In Che container HTTP Response, there is no support for x-frame options.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) - 4.3.28_1532
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) - IBM Cloud
   - [ ] other: please specify

**Comment by gyezheng** [comment]
Any update for the issue? Thanks!

**Comment by kristinochka** [comment]
The following url is effected: https://codeready-workspaces.apps.test.mycluster.com/dashboard/#/workspaces
