### ISSUE TITLE
When 'pvcStrategy' is changed old PVCs become stale and still consume quota

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17648]
### Is your enhancement related to a problem? Please describe.
Steps to reproduce: 

1. install che with the default custom resource config (`per-workspace` strategy is used) via operator / operatorhub
2. create and start a couple of workspaces
3. PVCs for those workspaces are created

![image](https://user-images.githubusercontent.com/1461122/90482492-9a81c900-e133-11ea-8fc2-64690bedb4ac.png)

4. change the PVC strategy to common e.g.  `pvcStrategy: common`
5. start yet another workspace -  common `claim-che-workspace` PVC is created, but there are still stale PVC from the old setup

Even though this could be treated as expected behavior there are a couple of open questions:

- changes from the workspaces started in the 'per-worspace' mode will not be available once the strategy is switched to 'common'
- PVC created via 'per-workspace' config are stale and still hold quota
- should we have a warning in the docs that changing strategy is not recommended and should be configured properly since the very beggining?

**Comment by metlos** [comment]
@ibuziuk, I see this as two separate issues:

* how to handle and/or document the consequences of changing the pvc strategy
* whether to change the default pvc strategy to "common"

Would you please create a separate issue for the latter so that we can narrow the scope of this issue to the former?

**Comment by ibuziuk** [comment]
a separate issue for changing default strategy to common on the operator end - https://github.com/eclipse/che/issues/17654

**Comment by metlos** [comment]
I have updated the description to not mention the point handled by #17654.
