### ISSUE TITLE
Move che-dashboard-next into eclipse organization

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#17655]
### Is your enhancement related to a problem? Please describe.
After adding [che-dashboard-next](https://github.com/che-incubator/che-dashboard-next) into che-server image 
(margin the [PR](https://github.com/eclipse/che/pull/17041)) there are two ways to develop this project: 
* keep it as is in the che-incubator until che-dashboard replacement;
* move it into eclipse organization as a separate project;

As for me, the second variant is the best, because che-dashboard-next used completely different technology and there is no reason to keep it in che-incubator after resolving all required CQs.

I want to know other developers opinions in this question.

Please, vote 
- :+1: for moving [che-dashboard-next](https://github.com/che-incubator/che-dashboard-next) into **eclipse** organization as a separate project 
- :rocket: for keeping dashboard-next in che-incubator till we move it from the alpha phase
- or leave other proposals as a comment

**Comment by sleshchenko** [comment]
Maybe it makes sense to postpone moving Dashboard Next to Eclipse until it fully replaces Dashboard to avoid redundant repos movements.

**Comment by sleshchenko** [comment]
Dashboard Next is going to be moved to Che Dashboard repository since the plan is to replace the dashboard instantly without supporting both.

**Comment by sleshchenko** [comment]
Dashboard next is moved to https://github.com/eclipse/che-dashboard/tree/main-react
The last thing that should be done, reconfigure dashboard next PR check to use that

**Comment by sleshchenko** [comment]
> reconfigure dashboard next PR check to use that

That's also done. There are issues with docker pull limit, but it's out of scope of the current PR.
