### ISSUE TITLE
Is it possible to setup Che in AWS EKS using ALB-Ingress?

### ISSUE THREAD

**Issue by Shashi0838** [eclipse-che/che#17657]
Using Nginx-Ingress, we are not able to use AWS Certificates.

We got a suggestion by AWS Support to Use the ALB Ingress, We can add Certificate for it.

I tried to setup ALB Ingress Controller following below link:
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/setup/
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#iam-permissions.

When I tried to run the che server using chectl command, there were 4 ALB's are created for each pod.

Can someone help us on Setting up ALB with Che?

**Comment by tolusha** [comment]
@Shashi0838 
To be honest I don't have experience with ALB-ingress, maybe @metlos knows something.
btw what is the exact problem with nginx ?

**Comment by Shashi0838** [comment]
@tolusha when we use Nginx it will create the classic load balancer. with classic load balancer we cant create global accelerator.
we need to use the AWS certificate to attach to load balancer and planning to use the global accelerator.

Even if we are able to use the AWS certificate with nginx would be great for us. will plan an alternative to the global accelerator

**Comment by Shashi0838** [comment]
@tolusha  @metlos Any luck on this? Waiting desperately!!

**Comment by Shashi0838** [comment]
I can see in che docs to support network load balancer. closing this issue
