### ISSUE TITLE
Theia terminal must report the error if request to machine-exec fails

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17663]
### Describe the bug
From time to time it happens that Theia terminal is empty and there is no clue for an user what is the cause.
In my case, debugging shows that che-machine-exec fails to create exec with error:
```
message: "Get https://172.30.0.1:443/api/v1/namespaces/labs-infra/pods?fieldSelector=status.phase%3DRunning&labelSelector=che.workspace_id%3Dworkspacepvsrvhkshe46hw5g: http2: no cached connection was available"
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
there is no clear scenario how to reproduce it, but it should be easy to build custom che-machine-exec that always return error and face the same.

### Expected behavior
Theia (terminal extension) reports the issue when it happens.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot_20200819_164328](https://user-images.githubusercontent.com/5887312/90642662-5a0d7280-e23b-11ea-8866-19f375d39e5c.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by andrewyuau** [comment]
I am getting the same issue, @sleshchenko did you manage to fix the terminal not coming up issue?

![image](https://user-images.githubusercontent.com/14987623/100680387-8a7db480-33c5-11eb-800e-b386c94c69de.png)

**Comment by sleshchenko** [comment]
@andrewyuau the cause may be different, this issue is just about exposing failed requests to a user.
Could you check the che-machine-exec container logs? If you don't manage to solve the issue you face, please register a new one.
