### ISSUE TITLE
Reduce number of ConfigMaps for gateway single-host

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17669]
### Is your enhancement related to a problem? Please describe.
https://github.com/eclipse/che/issues/17060 will introduce gateway based exposure for single-host strategy. For that, we create a Configmap in che installation namespace for every exposed server, that means at least 7 configmaps per running workspace (possibly more, depends on the devfile). This may become a bottleneck to have so many configmaps in one namespace.

### Describe the solution you'd like
Merge all gateway configurations of single workspace into single configmap.

### Additional context
https://github.com/eclipse/che/issues/17060
epic: https://github.com/eclipse/che/issues/12914

**Comment by nickboldt** [comment]
which team will work on this? can you assign it to that team's / area's label?
