### ISSUE TITLE
Doc about installing Che on kind needs restructure

### ISSUE THREAD

**Issue by rkratky** [eclipse-che/che#17664]
### Is your enhancement related to a problem? Please describe.

The **Installing Che on kind** chapter is incorrectly structured -- the majority of the procedure actually prepres a kind installation for Che, while the actual Che installation is just the last step.

### Describe the solution you'd like

Either 
* link (from the **Prerequisites** section) to external docs that explain the preparation steps, or
* create a new procedure with prep steps for kind and make it a prereq of the actual Che install procedure

**Comment by themr0c** [comment]
Issue referenced in https://issues.redhat.com/browse/RHDEVDOCS-2273
