### ISSUE TITLE
add javadoc to a method in che/tests/legacy-e2e/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestFactoryServiceClient.java

### ISSUE THREAD

**Issue by 129124** [eclipse-che/che#17668]
Hi there, when I was reading the code of the function "public void deleteFactory(String name)" in che/tests/legacy-e2e/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/client/TestFactoryServiceClient.java , I found it has no Javadoc. I would like to contribute by adding “load a factory from the given name @param name of the factory". Can you check if this is correct?

**Comment by rhopp** [comment]
@129124 Feel free to create PR and we can have the discussion there ;-)

**Comment by 129124** [comment]
Thanks.
