### ISSUE TITLE
Upgrade VS Code Camel K to 0.0.16 to support Camel K 1.1.0

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#17673]

**Comment by apupier** [comment]
prepared branch https://github.com/apupier/che-plugin-registry/tree/17673-upgradeVSCodeCamelKTo0.0.16 to update with sidecar sha1 when https://github.com/che-dockerfiles/che-sidecar-camelk/pull/12 will be reviewed and merged

**Comment by nickboldt** [comment]
>  che-dockerfiles/che-sidecar-camelk#12 will be reviewed and merged

Done. 

Time for a PR from your branch?

**Comment by apupier** [comment]
https://github.com/eclipse/che-plugin-registry/pull/583
