### ISSUE TITLE
devfile for configbump tool

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17677]
### Is your enhancement related to a problem? Please describe.

https://github.com/che-incubator/configbump
Since we're introducing new tool into Che family, we should provide a devfile for it.

### Describe the solution you'd like

create a devfile in https://github.com/che-incubator/configbump repository root with all tooling needed to provide full developer experience (build, test, run, debug).

### Describe alternatives you've considered

n/a

### Additional context

https://github.com/eclipse/che/issues/17063
https://github.com/eclipse/che/issues/12914

**Comment by nickboldt** [comment]
which team will own the configbump tool? can you assign it to that team's area/team label?

**Comment by sparkoo** [comment]
> which team will own the configbump tool? can you assign it to that team's area/team label?

platform team. It does not have area label, should I create new one?

**Comment by l0rd** [comment]
> platform team. tool does not have area label, should I create new one?

I have added area/wsmaster for now since it's a wsmaster dependency. But feel free to create a dedicated label if you think it deserves one.
