### ISSUE TITLE
Workspace starting fails with "Plugins installation process timed out" error

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#17670]
### Describe the bug
Workspace starting fails with "Plugins installation process timed out" error. There is a problem with **che-plugin-metadata-broker-v3-2-0** container starting - "flag provided but not defined: -cadir"(see logs below).

### Che version
Eclipse Che 7.18.0-SNAPSHOT

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_079](https://user-images.githubusercontent.com/7760565/90744592-b2df1880-e2d8-11ea-9931-832a82f69ea9.png)

![Selection_080](https://user-images.githubusercontent.com/7760565/90747635-dc4c7400-e2d9-11ea-86b5-c79db711e175.png)

### Installation method
   - [x] chectl
     chectl/0.0.20200812-next.0314dc6 linux-x64 node-v10.22.0
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
```che-plugin-metadata-broker-v3-2-0``` container logs

```
﻿flag provided but not defined: -cadir
Usage of /metadata-broker:
  -cacert string
    	Path to Certificate that should be used while connection establishing
  -disable-push false
    	Whether pushing of data and logs to endpoint should be disabled. false by default. Needed for testing and debugging purposes
  -enable-auth false
    	Whether authenticate requests on workspace master before allowing them to proceed.By default the value from 'CHE_AUTH_ENABLED' environment variable is used or false if it is missing (default true)
  -metas string
    	Path to configuration file on filesystem (default "//config.json")
  -print-events-only false
    	Output events that are usually sent Che master instead of regular logs to imitate what a user can see.false by default. Needed for testing and debugging purposes
  -push-endpoint string
    	WebSocket endpoint where to push statuses
  -registry-address string
    	Default address of registry from which to retrieve meta.yaml's when plugin FQNs do not specify a registry
  -runtime-id string
    	The identifier of the runtime in format 'workspace:environment:ownerId'
  -use-localhost-in-plugin-urls localhost
    	This configures the broker to use the localhost name instead of the Kubernetes service name to build Theia or VSCode plugin endpoint URL.`true` by default since until now all remote VS Code or Theia plugin containers are started on the same POD as the Theia IDE container (default true)```

**Comment by mmorhun** [comment]
Should be fixed by https://github.com/eclipse/che/pull/17671

**Comment by mmorhun** [comment]
Fixed.
