### ISSUE TITLE
[docs] OpenShift 3 quickstart upgrading instructions do not make sense

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17687]
### Is your enhancement related to a problem? Please describe.
The section "Upgrading from a previous Che installation" in the [OpenShift 3 quickstart](https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-3-using-the-operator/) doesn't seem to work. Executing the `oc delete` and `oc patch` commands listed deletes resources from the cluster, but the operator gets stuck in a error loop:

```
time="2020-08-22T03:34:38Z" level=error msg="Failed to get  CR: CheCluster.org.eclipse.che \"eclipse-che\" not found"
time="2020-08-22T03:34:38Z" level=error msg="Failed to get  CR: CheCluster.org.eclipse.che \"eclipse-che\" not found"
time="2020-08-22T03:34:38Z" level=error msg="Failed to get  CR: CheCluster.org.eclipse.che \"eclipse-che\" not found"
time="2020-08-22T03:34:38Z" level=error msg="Failed to get  CR: CheCluster.org.eclipse.che \"eclipse-che\" not found"
E0822 03:34:43.693655       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to watch *v1.CheCluster: the server could not find the requested resource (get checlusters.org.eclipse.che)
E0822 03:34:44.695598       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.CheCluster: the server could not find the requested resource (get checlusters.org.eclipse.che)
E0822 03:34:45.697739       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.CheCluster: the server could not find the requested resource (get checlusters.org.eclipse.che)
E0822 03:34:46.699784       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.CheCluster: the server could not find the requested resource (get checlusters.org.eclipse.che)
```
and does not recreate anything. This step also causes any workspaces to be lost if you try to `chectl server:start` again.

The original deploy command is 
```
chectl server:start -n <namespace> -p openshift
```
as suggested in the doc.

### Additional Info
Originally encountered while using downstream `crwctl/2.3.0-GA-redhat.abf3efd linux-x64 node-v10.19.0`, verified in `chectl/0.0.20200820-next.290685f linux-x64 node-v10.22.0`

**Comment by themr0c** [comment]
We support only upgrade from minor version, are these steps still relevant?

I believe they are outdated and can be safely removed, but I would like some confirmation from team/deploy.

If the steps are relevant, we need an updated version of the commands, and move them where they belong, in the "Upgrading" story.

**Comment by themr0c** [comment]
Referenced in: https://issues.redhat.com/browse/RHDEVDOCS-2276

**Comment by themr0c** [comment]
Confirmed by @tolusha : we can remove.
