### ISSUE TITLE
Cannot login into Che using Openshif OAuth when proxy with authentication is used

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17681]
### Describe the bug
It is not possible to login into Che when Openshift OAuth is used on a cluster which has cluster wide proxy with authentication configured.

### Che version
nightly

### Steps to reproduce
1. Deploy Eclipse Che on an Openshift 4 cluster which is configured to use proxy with authentication
2. Open Che dashboard link and try to login in Openshift OAuth
3. After login Che show error.

### Expected behavior
Che should work behind proxy

### Runtime
Openshift 4.5

### Screenshots
![Screenshot from 2020-08-21 12-27-12](https://user-images.githubusercontent.com/15607393/90875337-ac6ca180-e3a9-11ea-9761-a5acddd94d50.png)

### Installation method
chectl

### Environment
 Cloud

### Additional context
When install Eclispe Che on the cluster with cluster wide proxy configured it is required to add `api.<cluster-url>` to `nonProxyHosts`

**Proxy Logs:**

```
1598003734.988   4839 35.237.0.38 TCP_TUNNEL/200 3127 CONNECT oauth-openshift.apps.ci-ln-cslqx32-f76d1.origin-ci-int-gce.dev.openshift.com:443 test HIER_DIRECT/104.196.69.165 -
1598003750.395 901315 35.196.42.134 TCP_TUNNEL/200 3420 CONNECT api.ci-ln-cslqx32-f76d1.origin-ci-int-gce.dev.openshift.com:6443 test HIER_DIRECT/104.196.15.45 -
1598003760.401  90787 35.237.0.38 TCP_TUNNEL/200 3140 CONNECT oauth-openshift.apps.ci-ln-cslqx32-f76d1.origin-ci-int-gce.dev.openshift.com:443 test HIER_DIRECT/104.196.69.165 -
1598003764.020   4830 35.237.0.38 TCP_TUNNEL/200 3127 CONNECT oauth-openshift.apps.ci-ln-cslqx32-f76d1.origin-ci-int-gce.dev.openshift.com:443 test HIER_DIRECT/104.196.69.165 -
1598003765.012   4846 35.237.0.38 TCP_TUNNEL/200 3127 CONNECT oauth-openshift.apps.ci-ln-cslqx32-f76d1.origin-ci-int-gce.dev.openshift.com:443 test HIER_DIRECT/104.196.69.165 -
1598003784.443      1 35.196.42.134 TCP_DENIED/407 4233 CONNECT oauth-openshift.apps.ci-ln-cslqx32-f76d1.origin-ci-int-gce.dev.openshift.com:443 - HIER_NONE/- text/html
1598003790.398  90793 35.237.0.38 TCP_TUNNEL/200 3140 CONNECT oauth-openshift.apps.ci-ln-cslqx32-f76d1.origin-ci-int-gce.dev.openshift.com:443 test HIER_DIRECT/104.196.69.165 -

```

**Comment by tolusha** [comment]
Keycloak supports authentication proxy since 9.0.0 version
https://github.com/keycloak/keycloak/pull/6111

**Comment by tolusha** [comment]
Workaround is to configure nonProxyHosts in a CR:
```
spec:
  server:
    nonProxyHosts: oauth-openshift.apps.<DOMAIN>|api.<DOMAIN>
```

**Comment by tolusha** [comment]
Fixed with updating keycloak to a new version
