### ISSUE TITLE
[doc] Che4z page update

### ISSUE THREAD

**Issue by zeibura** [eclipse-che/che#17685]
The Che4z page at https://www.eclipse.org/che/docs/che-7/eclipse-che4z/ needs an update. New versions of the stacks were released including:
- New version of COBOL Language Support which has its own syntax coloring feature and local copybook support
- New version of Debugger for Mainframe which adds support for Batch applications

**Comment by themr0c** [comment]
Fixed by https://github.com/eclipse/che-docs/pull/1487
