### ISSUE TITLE
Wrong reference in  che-plugin-registry/v3/plugins/redhat/mta/0.0.37/meta.yaml

### ISSUE THREAD

**Issue by DarthBlair** [eclipse-che/che#17680]
### Describe the bug

The mentioned reference doesn't exist: [meta.yaml](https://github.com/eclipse/che-plugin-registry/blob/c0fcbd27e93bb1e497bb7f33eaaed23b6197075c/v3/plugins/redhat/mta/0.0.37/meta.yaml#L37)
https://download.jboss.org/jbosstools/adapters/stable/rhamt-vscode-extension/rhamt-vscode-extension-0.0.37-589.vsix
Actual file is: https://download.jboss.org/jbosstools/adapters/stable/rhamt-vscode-extension/rhamt-vscode-extension-0.0.37-581.vsix

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. 
```
./build.sh --organization eclipse \
       --registry harbor.private \
       --tag 7.16.1 \
       --offline 
```
2. Download failed

### Expected behavior

Image build is successful
### Additional context

Change to:
```
extensions:
  - https://download.jboss.org/jbosstools/adapters/stable/rhamt-vscode-extension/rhamt-vscode-extension-0.0.37-581.vsix
```

**Comment by nickboldt** [comment]
PR: https://github.com/eclipse/che-plugin-registry/pull/585

**Comment by DarthBlair** [comment]
The Path is still wrong. Its only fixed if you use the latest version only

**Comment by ericwill** [comment]
> @nickboldt
> The Path is still wrong. Its only fixed if you use the latest version only

Please just use the latest version. Our only other recourse is to remove the old version, as the maintainer who contributed the plugin hasn't responded with a fix.
