### ISSUE TITLE
[Hosted Che] The connection was interrupted while the page was loading

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17695]
### Describe the bug
This error occurs quite often in browser console logs and probably is the cause of many different failures when running workspaces:
```
The connection to wss://routeqcaxo1fa-kkanova-preview-che.b542.starter-us-east-2a.openshiftapps.com/attach/2?token=<token> was interrupted while the page was loading.
```

Observed symptoms:
 - Commands are failing on different issues
 - LS starts to behave weirdly or stops to work

Those issues are seen through different workspaces.

### Che version
 - [x] latest 7.17.2
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to `Get Started` page, `Get Started` tab
2. Create workspace `Apache Camel based on Spring Boot`
3. Run `build` command (for me failed in 3/4 tries)
4. Check browser console logs

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify) Hosted Che

### Screenshots
![Screenshot from 2020-08-24 11-32-40](https://user-images.githubusercontent.com/29278800/91028543-e9c96d00-e5fd-11ea-9a2f-54029a16235a.png)
![Screenshot from 2020-08-24 09-29-43](https://user-images.githubusercontent.com/29278800/91028555-ee8e2100-e5fd-11ea-82cc-7d4b71c4a739.png)
![Screenshot from 2020-08-24 09-13-25](https://user-images.githubusercontent.com/29278800/91028568-f3eb6b80-e5fd-11ea-858c-8a06c84d9d8d.png)
![Screenshot from 2020-08-24 11-48-47_2](https://user-images.githubusercontent.com/29278800/91031513-f7ccbd00-e600-11ea-83c2-0b5a418d73cc.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know - Hosted Che

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify - Hosted Che

**Comment by ibuziuk** [comment]
Closing. Should be fixed on workspaces.openshift.com
