### ISSUE TITLE
The cursor is moving backwards on its own

### ISSUE THREAD

**Issue by malikshubham827** [eclipse-che/che#17690]
### Describe the bug

The cursor automatically move backwards (to left) while coding.
If I press Enter to go to new line, it first goes to correct indented column and then instantly goes to starting of line. I have tried tab and space but of no use.
When I am coding it moves backwards automatically screws up everything.

The above is happening when I am coding in a `.java`, `.js`, `.py` file (tested these only). 
I created a `.txt` file to check and that worked _fine_.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x ] other: Che-Theia@[5955916](https://github.com/eclipse/che-theia/commit/5955916) using Theia@[a0e635aed](https://github.com/eclipse-theia/theia/commit/a0e635aed)

### Steps to reproduce

1. Open any `.java`, `.js`, `.py` file or create new one.
2. Start coding, press Enter to go to new line
3. Cursor moves backwards on its own, and in case of new line it moves to start of line with 0 indentation.

### Expected behavior

Cursor should be at its place if no key is pressed on keyboard.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (che.openshift.io)
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
It should be already fixed by https://github.com/eclipse/che-theia/pull/912
If it still reproduced - feel free to reopen the issue.
Upstream Theia issue related to EditorConfig VS Code extension - https://github.com/eclipse-theia/theia/issues/8718
