### ISSUE TITLE
how to modify the /etc/ssh/ssh_config in workspace

### ISSUE THREAD

**Issue by whafra** [eclipse-che/che#17692]
Dear forum members,
I am runing che in k8s (private cloud ) ,the command is 
chectl  ...--install operator --platform k8s ....
Due to the account for git  is deffrent from the login username of  container , I tried  to modify the /etc/ssh/ssh_config  ，
the expected content is following:

Host *
User XXXX(the git account)
IdentifyFile .......

However ,i can not modify it , Could you give me some advice ?
thank you .

**Comment by ericwill** [comment]
Would it not be better to edit the git config?

**Comment by whafra** [comment]
@ericwill 
thanks for your reply.
I have modified the git config , and i could  pull the code using git clone ssh://<username>@gitserver..... 
however，i want to  simplify the command , just  using git clone ssh://git server....
So i want  to modify the ssh config file.
Of cause  ,i  could also modify the ~/.ssh/config . but , i have to edit it when i create a new workspace every time .
It is so inconvenient.  
I wonder if there is another way to edit  the config file only  once ,just like SSH->generate ssh key pairs.

**Comment by vparfonov** [comment]
@whafra You can generate SSH Key for particular host and it will be added on each workspace on next start. Something like this will be on your  ssh_config.
```
host test.com
IdentityFile /etc/ssh/private/test.com
```

**Comment by whafra** [comment]
@vparfonov 
thanks for your concern. However i want to find  a way to insert the line -- User   xxx  into the config file.

**Comment by vparfonov** [comment]
We don't have such ability at the moment

**Comment by whafra** [comment]
@vparfonov 
Is it possible to have such ability in future? It is really  a universal demand.
thank you .

**Comment by l0rd** [comment]
@whafra we have recently added the ability to inject a [git credentials](https://git-scm.com/docs/git-credential-store#_storage_format) file on every workspace (see [doc](https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-git-credential-store-into-a-workspace-container_mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container)). Maybe that can work for you? Anway Your original request is to provide Che users the ability to inject an SSH config file in every workspace. Is that correct?

**Comment by whafra** [comment]
@l0rd 
Thanks for your advise. However, the method you provided maybe only support the same user in the workspace. In our team , every teamate should login che and use the same devfile to create the workspace ,and  in the workspace ,he/she should be able to get the code from gerrit with his/her own credentials.
Is there any better way  to meet the demand  ?
thank you
