### ISSUE TITLE
workspace welcome page fails to load in single-host

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17694]
### Describe the bug

Having Che deployed in single-host, workspace welcome page fails to load. It just shows `Cannot GET /serverj4587ysj-jwtproxy/server-4402/webview/index.html`.

### Che version

 - [x] latest

### Steps to reproduce
1. deploy Che in single-host mode
1. start any workspace
1. see workspace welcome page error

### Expected behavior
Welcome page should load correctly

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![20200824_104420_1650x941_scrot](https://user-images.githubusercontent.com/1160903/91024112-c3a0ce80-e5f7-11ea-988a-60af00b9b66f.png)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

**Comment by sparkoo** [comment]
not yet sure if it's wsmaster or che-theia issue. Adding both labels for now

**Comment by sparkoo** [comment]
I can see this 404 request in browser console:
```
GEThttps://192.168.39.51.nip.io/serverpkys5zyv-jwtproxy/webviews/serverpkys5zyv-jwtproxy/server-4402/webview/index.html?id=ded62160-10e0-4f45-991a-3a4a9e22a26f
[HTTP/2 404 Not Found 10ms]

```
from this it's clear that url is wrong as it is for some reason concatenating 2 server paths togetner with `/serverpkys5zyv-jwtproxy/webviews/serverpkys5zyv-jwtproxy/server-4402/webview/`.

I was trying to debug che-theia to figure out how this url is constructed, but I couldn't get anywhere. Leaving this to someone more skilled with che-theia development.

Please ping me for any help with setup.

**Comment by azatsarynnyy** [comment]
Thanks @sparkoo for publishing your findings.
As we've discussed with @skabashnyuk, we'll try to help you with that during the next sprint.

**Comment by azatsarynnyy** [comment]
Moving to 7.22 as we don't have enough resources to look at it in 7.21

**Comment by azatsarynnyy** [comment]
I'm setting P1, as a single host mode is going to be a default.

**Comment by nickboldt** [comment]
Marking this critical in downstream for 2.6 (7.22): https://issues.redhat.com/browse/CRW-1336

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse/che-theia/pull/932
