### ISSUE TITLE
Add javadoc to a method in LimitsCheckingWorkspaceManager

### ISSUE THREAD

**Issue by 129124** [eclipse-che/che#17691]
Hi there, when I was reading the code of the function "public WorkspaceImpl updateWorkspace(String id, Workspace update)" in che/multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/LimitsCheckingWorkspaceManager.java , I found it has no Javadoc. I would like to contribute by adding “create a   new workspace in the local store. @param id controller id of the workspace". Can you please check if this is correct? Thanks.

**Comment by ericwill** [comment]
Hey @129124, please open a PR with your proposal and someone will take a look!

**Comment by 129124** [comment]
Thanks.
