### ISSUE TITLE
[Hosted Che] 'Build' command fails in Java Maven stack

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17699]
### Describe the bug
While running automated tests against https://che.prod-preview.openshift.io, sometimes there is an issue with running command `build` which fails with this message:
`Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?`

### Che version
 - [x] latest 7.17.2
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Run automated test for Java Maven against https://che.prod-preview.openshift.io

### Expected behavior
Maven command `build` should pass.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) ocp 4
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/91130559-1cca3a00-e6ac-11ea-98d1-fb71bbe50f01.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify Hosted Che

### Eclipse Che Logs
http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/3380/

**Comment by ericwill** [comment]
Since this is a Hosted Che bug I'm inclined to close it, now that Hosted Che is gone. If you experience this on workspaces.openshift.com then please file a new ticket.
