### ISSUE TITLE
missing stack images in single-host

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17693]
### Describe the bug
Stack images on getting started page are missing in single-host mode. URLs of these images is wrongly composed. It's e.g.: `https://192.168.39.23.nip.io/images/angular.svg`, but it should include devfile-registry url. Correct URL is `https://192.168.39.23.nip.io/devfile-registry/images/angular.svg`.

### Che version

 - [x] nightly

### Steps to reproduce
1. deploy in single-host
1. go to Get started page and see missing images

### Expected behavior
Images urls must point to actual devfile-registry images.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![20200824_102126_1593x880_scrot](https://user-images.githubusercontent.com/1160903/91021718-6e16f280-e5f4-11ea-8b73-bf6cc393de9f.png)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

**Comment by sparkoo** [comment]
I don't know yet whether issue is on wsmaster side or the dashboard. Assigning both labels for now.

**Comment by tolusha** [comment]
That's weird.
I saw this issue when fixing single host deployment on k8s.

**Comment by sleshchenko** [comment]
@akurinnoy tested it with che operator and chectl and it seems to work as expected. @tolusha @sparkoo  could you clarify which installation methods you used?

**Comment by sparkoo** [comment]
I couldn't reproduce it now, so it was probably my fault it wasn't working for me. If I reproduce it again, I'll reopen (or create new issue) with exact deploy steps. For now, sorry about confusion. closing
