### ISSUE TITLE
[Devfile tests] Test for opening project failing

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17698]
### Describe the bug
Starting with released 7.17.2, we started to observe the test flakiness. Test which is trying to verify that IDE loaded correctly is from time to time stuck at the phase where it can not open project. This issue is not reproduced on minishift or minikube, but on openshift v 4.

### Che version

 - [x] latest 7.17.2
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Run automated devfile tests for Java Maven against https://che.prod-preview.openshift.io 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) ocp v4
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/29278800/91128132-e68abb80-e6a7-11ea-8202-01e95b3427fe.png)

video: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-preview-2a/3379/e2e_report/report/ffmpeg_report/output.mp4 (you can start watching at 1:07)

**Comment by vzhukovskii** [comment]
Hi @Katka92, is everything okay with tests on 7.12.1 (openshift)?

**Comment by Katka92** [comment]
Hi @vzhukovskii, do you mean 7.17.1? We haven't tested that much on OCP as there was some issue blocking promotion on Hosted Che. The last version that was tested properly was 7.16.2 (and this is the version that is currently on production). Sorry that I missed that in the description.

**Comment by vzhukovskii** [comment]
Yep, 7.12.1 and maybe earlier releases.

**Comment by Katka92** [comment]
@vzhukovskii So we were testing 7.12.0 on Hosted Che some time ago and we didn't have many tests automated - we were testing basically all the stuff manually. The current version of tests doesn't have to be compatible with the 7.12.1 version or earlier. 
But this particular issue that is reported here is seen just in 7.17.2 version (so maybe present also in 7.17.1 or 7.17.0, as latest tested version was 7.16.2).

**Comment by ScrewTSW** [comment]
This issue was fixed with https://github.com/eclipse/che/pull/17793
