### ISSUE TITLE
[new UD] refactor stores

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#17705]
*Umbrella issue*

For each store:

- replace promises with async/await
- don't resolve fetch requests with any values
- use selectors to return necessary subset of results

Stores to refactor: 

- [x] DevfileFilters - get rid of this store in favour of using selectors https://github.com/eclipse/che/issues/17531
- [x] Workspaces https://github.com/eclipse/che/issues/17710
- [ ] DevfileRegistries
- [ ] InfrastructureNamespaces
- [ ] Branding

**Comment by sleshchenko** [comment]
Almost all of the listed is fixed.
What is left will be refactored when related side issues will be prioritized.
