### ISSUE TITLE
Annoying pop-up when saving the file

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17704]
### Describe the bug
When updating a file, the pop-up is shown asking the user if he/she wants to save the file. It's quite annoying, it's happening in different stacks. It not showing all time, sometimes auto saver saves that without problems.
Note: The issue was reproduced when immediately opening the file after workspace loaded. When I waited a few minutes, the issue was gone.

### Che version
 - [x] latest 7.17.2
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Go to `Get Started` page, `Get Started` tab
2. Click on  `Java Gradle` workspace
3. Open `HelloWorld.java` file (go to file explorer and open `console-java-simple/src/main/java/org/eclipse/che/examples`
4. Type something, wait for the auto saver to save your changes

### Expected behavior
The pop-up should not be shown.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) OSD 4
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-08-25 14-57-22](https://user-images.githubusercontent.com/29278800/91179274-967f1980-e6e6-11ea-94ea-210dfd189932.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify - Hosted Che

**Comment by tsmaeder** [comment]
What kind of storage are you using on that workspace?

**Comment by ibuziuk** [comment]
> What kind of storage are you using on that workspace?

gluster @Katka92 does the issue reproducible against ephemeral?

**Comment by Katka92** [comment]
@ibuziuk I can reproduce using persistent volume but can not reproduce against ephemeral. Tired 3 times every type using Java Gradle workspace.

**Comment by sunix** [comment]
duplicates https://github.com/eclipse/che/issues/16751 ?

**Comment by ibuziuk** [comment]
Closing as duplicate -  #16751
