### ISSUE TITLE
Stabilize tests for OSD v4

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17702]
### Is your task related to a problem? Please describe.
The latest tests on Hosted Che shows that there are some issues found on OCP that are not found during nightly testing Che on minishift and minikube. Stabilize the devfile test suite so it is not failing even on OCP. 

### Describe the solution you'd like
Run devfile test suite multiple times with those setups:
 - nightly Che on OCP
 - latest Che on OCP (currently 7.17.2)
 - latest Hosted Che OCP 4 (OCP 3 if available, not a high priority)

Related issues with detailed descriptions of failures:
https://github.com/eclipse/che/issues/17698
https://github.com/eclipse/che/issues/17722

**Comment by ScrewTSW** [comment]
PR has been merged, closing issue
