### ISSUE TITLE
Docs link for importing self-signed certificates is broken

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17712]
### Describe the bug
Merging PR https://github.com/eclipse/che-docs/pull/1451 broke the link on the certificate error page:

![Screenshot from 2020-08-26 15-56-06](https://user-images.githubusercontent.com/16168279/91350585-e3c9bc80-e7b4-11ea-9d50-ceab226b075e.png)

Clicking this link currently leads to a 404 instead of the appropriate procedure.

### Che version
 - [x] other: 7.17.2

**Comment by tolusha** [comment]
This is a very important section. It is used in `chectl' and `crwctl` tools to explain how to import the certificate into a browser.

/cc @rkratky
