### ISSUE TITLE
Add Ports section in the workspace configuration

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1771]
We need to let the user being able to configure the ports for a workspace.

Design which will be discussed and iterate:

![1 - workspace details - settings - july 2016 copy](https://cloud.githubusercontent.com/assets/1611939/16900358/ac33ea44-4c2b-11e6-9200-daa141d31a97.png)

**Comment by ashumilova** [comment]
As discussed with Stevan : 
After user does changes in workspace config - we display him the message:  
“Changes will be applied after the next workspace restart." [APPLY NOW]
We will mark the changes that were not yet applied.

**Comment by slemeur** [comment]
Add updated design:
![1 - workspace details - environments - july 2016](https://cloud.githubusercontent.com/assets/1636769/17665142/4d7cad76-62f9-11e6-9b41-22e36a0350a5.png)
