### ISSUE TITLE
Temporary Storage toggle  in Get Started Page. 

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#17711]
## Summary
While creating a new workspae, the Storage Type in the Custom Workspace screen is showing as a drop down , while it is showing as a toggle switch in the Get Started tab. 

I have a requirement to  allow just Ephemeral storage in our cluster. I did add the following che properties in the  che custom resource yaml 
CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES: ephemeral
CHE_WORKSPACE_STORAGE_PREFERRED__TYPE: ephemeral

This does show properly in the Custom Workspace wherein the dropdown shows just the Ephemeral option.  But in the Get Started tab, the toggle for temporary storage is showing disabled which means it will create a persistent storage. 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/17478559/91333602-69685f00-e7eb-11ea-81ea-1b71789a89b0.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/17478559/91333658-7b4a0200-e7eb-11ea-98d2-26f733ef9371.png">

Shouldn't the Get Started also show the drop down to select the storage type? If done, the above 2 properties should probably take effect in that case. 

I have che server version 7.17.2 setup.

**Comment by sleshchenko** [comment]
@pgirishibm 

> I have a requirement to allow just Ephemeral storage in our cluster

Unfortunately, `CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES` defines the only default behavior for the dashboard even if it makes the impression that it should deny every other. It was designed mainly to disable promoting experimental features, like async storage. But if I'm not mistaken users are able to configure any storage type with devfile attributes, @vparfonov am I right?

After https://github.com/eclipse/che/issues/17725 is fixed, the temporary storage type should be enabled by default, so you'll have more consistent behavior on the Dashboard.
If you need a strong requirement that any other storage types should be disabled - feel free to open a new feature request, and even contribute the solution for that )

**Comment by pgirishibm** [comment]
Thanks for the information @sleshchenko . I will keep a watch on #17725 . Closing this issue..
