### ISSUE TITLE
Automate release and publishing typescript Che API

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17721]
### Is your task related to a problem? Please describe.
Currently, Che API [pom.xml has 7.8.0-SNAPSHOT](https://github.com/eclipse/che/blob/master/typescript-dto/dto-pom.xml#L21) version while the latest published lib is [7.4.0 + 7.5.0-SNAPSHOT](https://registry.yarnpkg.com/@eclipse-che/api).
It's not really consistent with the latest Che Release with is 7.18.0.

### Describe the solution you'd like
Che API is published each Che Release.

### Describe alternatives you've considered
Che API uses different versions and is releases on-demand as we do with che-plugin-broker.

**Comment by mkuznyetsov** [comment]
during the 7.18.2 release, the latest 7.18.2 Typescript API has been pushed manually using `mvn clean install` & publish.sh script.
build.sh needs to be fixed, as it exits after the build with no output, and does no publishing.
+ 2FA might be in a way to run this in an automated workflow on Centos CI / Github actions

**Comment by nickboldt** [comment]
Is this done?
