### ISSUE TITLE
[Devfile tests] Test for opening file fails sometime

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17722]
### Describe the bug
From time to time, some devfile tests fails on opening the file. The file is opened correctly, but the test thinks it is not. It can be caused by stolen focus or maybe that the tab has not the "selected" state (in the "selected" state, the name of the file is white, but in "non-selected" it is grey - different style class, that may be used in the test). The last time issue was reproduced on a minikube.

job log: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2144/console

video from test: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2144/artifact/tests/e2e/report/

### Che version

 - [x] latest 7.17.2
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Run the devfile tests against minikube multiple times and investigate failures. 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/91408126-9ea09b80-e843-11ea-98c4-e4293db64001.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by dmytro-ndp** [comment]
The issue hasn't been reproduced on CRW CCI for a week after test execution flow had been changed. 
So, IMHO, we can now close the issue.
