### ISSUE TITLE
Migrate Eclipse Che testing jobs from old ci.centos.org to new openshift-based CI infra

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17727]
### Is your task related to a problem? Please describe.
ci.centos.org is going to be deprecated in Nov/Dec in favor of new openshift based infrastructure https://lists.centos.org/pipermail/ci-users/2020-June/002095.html, https://issues.redhat.com/browse/APPSRE-2140

### Describe the solution you'd like
Old Eclipse Che testing jobs on ci.centos have to be migrated to openshift based infrastructure.

**Comment by ibuziuk** [comment]
Potential options for CI:
- use new OpenShift CI / move CI config from app-interface 
- Eclipse CI
- GitHub actions
- Travis CI

**Comment by benoitf** [comment]
I saw https://github.com/marketplace/actions/github-action-build-chain-cross-repo-builds in some mailing list this week as well (for the 'release perspective')
