### ISSUE TITLE
Docs on VS Code ext.\s in Che has bad code example

### ISSUE THREAD

**Issue by rkratky** [eclipse-che/che#17728]
### Describe the bug

Bad markup in code block at https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/

### Expected behavior

Correct callout numbers.

### Screenshots

![image](https://user-images.githubusercontent.com/6623103/91454006-bc402600-e880-11ea-8688-0d8a26bb78cf.png)

**Comment by rhopp** [comment]
@rkratky I'm seeing correct numbers (in google-chrome v. 84)
![image](https://user-images.githubusercontent.com/1215011/91457944-3f637b00-e885-11ea-80fc-380aad8d5baa.png)

**Comment by rkratky** [comment]
@rhopp, strange, I'll investigate more (screenshot taken using Firefox).

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2542
