### ISSUE TITLE
Add Environment variables in the workspace configuration

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1772]
A user must be able to see and configure the environment variables for a workspace. It is parts of the workspace settings

Design which will be discussed and iterate:
![1 - workspace details - settings - july 2016 copy](https://cloud.githubusercontent.com/assets/1611939/16900373/0eb8048e-4c2c-11e6-8855-50ce068e7213.png)

**Comment by gazarenkov** [comment]
What is this page?
Looks like a mix of Workspace and Machine configuration.
IMO Workspace have not got environment variables, it is Machine (Container) property.

**Comment by TylerJewell** [comment]
It is a mix of workspace and environment configuration.  What we decided to do was that when a workspace has a single environment to simplify the user dashboard view by configuring the machine elements in the workspace configuration.   

What we do not have is a good design on how to configure many machines that each have their own environment and ports.   I do not think Stevan has that design yet.

**Comment by slemeur** [comment]
Attached, the mockup with environment configuration.

![1 - workspace details - environments - july 2016](https://cloud.githubusercontent.com/assets/1636769/17665290/587f3abc-62fa-11e6-92e1-90f6cf1264ae.png)
