### ISSUE TITLE
[doc] Instructions for importing self-signed certs are unclear

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17734]
### Is your enhancement related to a problem? Please describe.
The documentation for importing the self signed cert [[1]](https://www.eclipse.org/che/docs/che-7/installing-che-on-minishift/#adding-certificates-to-google-chrome-on-linux-or-windows) is somewhat unclear -- by default when I follow these instructions, the certificate that ends up exported is not an authority; to get the right one I need to manually select the certificate one step up in the chain.

### Additional context
Related: https://github.com/eclipse/che-docs/pull/1493

**Comment by tolusha** [comment]
That's basically the issue https://github.com/eclipse/che/issues/16773

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2545
