### ISSUE TITLE
Set up automated checks that clients(dashboard/chectl) uses the valid links to docs

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17739]
### Is your enhancement related to a problem? Please describe.
Lately, our docs are often restructured and articles links are changed. But references are not updated on the dashboard side.
It's needed to find a solution and ideally create PR check for docs repo that would show that links become broken with PR changes.

On the dashboard all documentation links are stored in 
https://github.com/eclipse/che-dashboard/blob/master/src/components/branding/branding.constant.ts
+ 
https://github.com/eclipse/che-dashboard/blob/master/src/assets/branding/product.json
note: we'll take a look if one place could be enough.

### Describe the solution you'd like
So, the idea is run the documentation from the PR, and test every docs link does not return 404 (not sure if we can check bookmark in that way, I mean URL#some-particular-part)

### Describe alternatives you've considered
Just improve docs PR template to reference dashboard files which may need be updated and make PR author responsible to adapt dashboard. It can be even a first step.

**Comment by benoitf** [comment]
the check should run in the documentation or on the dashboard side ?

**Comment by sleshchenko** [comment]
I think on the documentation side since usually the link become broken after changes on the docs side.
