### ISSUE TITLE
Add Delphi and Pascal support to eclipse Che

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17733]
there are pascal and delphi extensions in ms-vscode marketplace

one could think pascal and delphi are extinct but they are still being used in some environments:
universities teaching the first year of soft. dev. to introduce students to basic dev concepts.

some libraries use it for book management too. 

https://marketplace.visualstudio.com/items?itemName=alefragnani.pascal

https://marketplace.visualstudio.com/items?itemName=alefragnani.delphi-pack

making it a single issue since I think they can share the sidecar

**Comment by brianking** [comment]
Might these work "out of the box" if the extensions were added to Open VSX?

**Comment by ericwill** [comment]
> Might these work "out of the box" if the extensions were added to Open VSX?

They probably need a sidecar container with the relevant tooling installed, first.
