### ISSUE TITLE
Eclipse che on EC2 using AWS certificate

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#17738]
Hi all,

Kindly refer to the documentation: https://www.eclipse.org/che/docs/che-7/installing-che-on-aws/
The procedure uses certificate issued by `letsencrypt`.

Can we use certificate issued by AWS instead of letsencrypt ?
Could you please guide me on what are all the changes needed in the procedure given above?

Thanks in advance !

**Comment by tolusha** [comment]
> Can we use certificate issued by AWS instead of letsencrypt ?

I think we can. The eventual goal is to create `che-tls` secret in the `che` namespace.

**Comment by boczkowska** [comment]
I think we should provide this info in the docs, wdyt @rkratky?

**Comment by svkr2k** [comment]
Thank you, @tolusha .
@boczkowska , @rkratky, ues, it would be helpful if this info is provided in the docs.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2543

**Comment by tolusha** [comment]
Duplicates https://github.com/eclipse/che/issues/17798
