### ISSUE TITLE
Add section in workspace to handle the stack

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1773]
User needs to be able to see what is the stacks that is currently associated to a workspace. 

We also needs to let the user being able to reconfigure the stacks.

When the stack the user select a stack, we will ask him if he is sure and if he wants to restart the workspace.

Proposed designed to be iterated:
![1 - workspace details - stacks - july 2016](https://cloud.githubusercontent.com/assets/1611939/16900399/a389711a-4c2c-11e6-93fa-40f1b825ee41.png)

Need to think about how we handle the projects that are in the stack.

**Comment by TylerJewell** [comment]
@slemeur - can you please link all of the stack issues into a stack epic, please?  This issue is part of a workspace creation / edit view, but let's cross link it into a stack system as well.
