### ISSUE TITLE
Generate branches every sprint for kubernetes image puller

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17742]
### Is your enhancement related to a problem? Please describe.

Today, new commits of k8s image puller are published as quay images, but for projects or products that rebuild & productize the image puller, there's no "stable" branch from which to pull commits.

Also today, I manually create 7.16.x or 7.18.x branches so that I'm not required to use master or a random commit SHA.

https://github.com/che-incubator/kubernetes-image-puller/tree/7.18.x
https://github.com/che-incubator/kubernetes-image-puller/tree/7.16.x

### Describe the solution you'd like

So... should the k8s image puller project start generating a once-per-sprint branch? We can script that and do it as part of the overall Che release process. Or we could do a weekly tag. Or both. 

WDYT @ibuziuk ?

**Comment by ibuziuk** [comment]
@nickboldt image puller has a distinct lifecycle which is not bound to che, so at this point I'm -1 for creating
che specific release branches for puller.

**Comment by nickboldt** [comment]
So how would you like me to get the latest stable release every 6 weeks? I'm good with a differently named branch or tag, as long as it's predictable.

**Comment by tomgeorge** [comment]
after discussing with @nickboldt we think we can do away with the `imagepuller-rhel8` image, and document that if you want to use the image puller/image puller operator, that it is a community operator and no support is offered.

@nickboldt @ibuziuk Does this then invalidate https://github.com/che-incubator/kubernetes-image-puller-operator/pull/39 ?  The user will be deploying the upstream image puller and then per [CRW docs](https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.5/html/administration_guide/caching-images-for-faster-workspace-start_crw) they can set `IMAGES` to the recommended list of images.

**Comment by ibuziuk** [comment]
@nickboldt not following, why do you want to have image puller to be an unsupported feature, CRW docs already refer to it as part of the product.

**Comment by nickboldt** [comment]
I never said Che KIP would be unsupported. All I wanted was a stable 7.yy.x branch against which to sync code into downstream CRW builds.

https://github.com/che-incubator/kubernetes-image-puller/pull/36

**Comment by nickboldt** [comment]
New branch creation action created & verified working: https://github.com/che-incubator/kubernetes-image-puller/actions?query=workflow%3A%22Create+branch%22

Now we just need to trigger it from https://github.com/eclipse/che-release/blob/master/cico_release.sh
cc: @mkuznyetsov 

See https://github.com/eclipse/che-release/pull/24
