### ISSUE TITLE
Add section in workspace to handle the agents

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1774]
We will need a new section in the workspace details to handle the agents.
This is a proposed design that we will iterate.
![1 - workspace details - agents - july 2016](https://cloud.githubusercontent.com/assets/1611939/16900421/0bbb6932-4c2d-11e6-897c-2efc938e7b5c.png)

**Comment by ibuziuk** [comment]
@ashumilova I have started to work on this one. After browsing a little bit through REST API I figure out how to get agents per workspace: 

`this.agents = this.workspace.config.environments.default.machines["dev-machine"].agents;`

Basically, the agents' names for my test workspace are: 

```
org.eclipse.che.terminal
org.eclipse.che.ws-agent
org.eclipse.che.ssh
```

looking at the mockup I find it hard to understand  how can I get agents' "state" and "description" properties. REST API for agents e.g `api/agent/name/org.eclipse.che.ws-agent` return object with properties like: "name" / "dependencies" / "properties" / "script".  Am I on the wrong track ?

**Comment by slemeur** [comment]
@ibuziuk : Glad, and super excited to see you contributing to Che. Please give a look at the updated mockup. 

Agents will be defined per machines in environments.
![1 - workspace details - environments - save changes option1](https://cloud.githubusercontent.com/assets/1636769/18438389/780761c6-7901-11e6-958b-c5e2f20275b9.png)

In the agent section, you'd have the ability to see the whole list of agents installed with Che. User will then just have to use the slider to activate the agents in the machine or not.

**Comment by ibuziuk** [comment]
@slemeur hey, buddy! I also super exited having a possibility to contribute - for now I'm only getting familiar with a code base though. New mockup looks completed, however I still baffled with the agent properties "state" / "description" - I can not figure out what API should be used here.

**Comment by tolusha** [comment]
Currently agents don't provide description.

**Comment by ashumilova** [comment]
What we have is dependencies, properties and script. @tolusha can we add description - to have smth human readable.

@ibuziuk about state - the state is determined whether machine includes the agent provided by Che or not. So we display all agents provided by Che in the list, and those that are mentioned in machines agents list - are active for this machine, others - inactive.

**Comment by slemeur** [comment]
@tolusha : Each agents must be provided with a set of meaningful information for end-user. 
When I see the name = "org.eclipse.che.terminal" and all the properties you have related to the agent, they seem perfect for internal - but definitely not to be exposed to end-users.

Please create the issue to improve this area.

**Comment by ibuziuk** [comment]
@tolusha @ashumilova Thanks for clarifications

**Comment by ibuziuk** [comment]
@slemeur @ashumilova As it was mentioned above  **Che Agent API** is missing "description" property and the "name" property like **"org.eclipse.che.ls.json"** does not look viable from the user perspective. So, I guess with the current version of API  the best layout would be the following (please, let me know if it is ok for the initial implementation):

![agents](https://cloud.githubusercontent.com/assets/1461122/18730105/dbcce762-8054-11e6-9102-d74eab2891c6.png)

Basically, in the next iteration it would be great to change the Agents REST API the following way:
1. Add **id** field. The value of it would be the current value of the **name** field i.e. **org.eclipse.che.ls.json**
2. Amend **name** field so, that it would reflect meaningful name of the agent i.e. **JSON language service**
3. Add **description** field
4. Change REST API, so that new **id** will be used instead of **name** e.g. change `GET /agent/name/{name}` to `GET /agent/id/{id}`

WDYT ?
If you think it is relevant, I would be glad to work on it ;-)

**Comment by TylerJewell** [comment]
Yes, yes, yes, and yes. :)

I think using the fully qualified name as you have it is a reasonable first start so that we can go ahead and get the capabilities merged into master.  We can then make an improvement PR once the API is updated.  So I am +1 for splitting into two segments.

**Comment by ibuziuk** [comment]
@TylerJewell awesome! I am planning to provide the initial implementation by the end of the week

**Comment by TylerJewell** [comment]
That is really awesome.  There are just a couple of lingering language server and agent bugs, but if all goes well, we may have a shippable release with agents and language server by next week!

**Comment by ibuziuk** [comment]
@ashumilova @slemeur @TylerJewell while implementing the agents enabling / disabling I have noticed that API does not allow to disable **ws-agent** agent:

![ws-agent](https://cloud.githubusercontent.com/assets/1461122/18768383/0c04c46a-8125-11e6-8fcf-3690cd94128e.png)

Am I correct that the switch for this agent should be permanently disabled ?

**Comment by ashumilova** [comment]
@ibuziuk yes we have that restriction that at least one machine in environment should be with ws-agent. 
Perhaps it should be disabled in case it's the only one machine with ws-agent. @slemeur what do you think?

**Comment by slemeur** [comment]
@ibuziuk and @ashumilova : Yes at least one machine from the environment needs the ws-agent. I think we should use the "Dev" slider to handle that. 

The "ws-agent" will still be listed in the agents list, but in disable state.

**Comment by ibuziuk** [comment]
@slemeur just want to be sure that we are on the same page:
- ws-agent switch is listed but **always** disabled for machine regardless of it's state
- switching of the ws-agent happens **only** via "Dev" slider

I'm polishing my PR now, but I do not really know when 5.0.0-M3 is going to be released to be sure that the fix will be ready on time for it

**Comment by ashumilova** [comment]
The approximate date of 5.0.0-M3 release is Monday (09/26).

**Comment by ibuziuk** [comment]
@ashumilova oh, awesome I was thinking it's today ;-)

**Comment by slemeur** [comment]
@ibuziuk : yes perfect! we are on the same page ;)

**Comment by ibuziuk** [comment]
![out](https://cloud.githubusercontent.com/assets/1461122/18795730/3551dc76-81c6-11e6-9e47-e47930e12092.gif)
@ashumilova @slemeur PR is ready - https://github.com/eclipse/che/pull/2577
The biggest concern is that enabling / disabling agent results in screen blinking. Actually, it is also true for other sections like "Dev" / slider in "RAM" - for agents it is more noticeable though.

**Comment by ashumilova** [comment]
Fixed by @ibuziuk

**Comment by ibuziuk** [comment]
@ashumilova @slemeur as I understand it was decided to split this issue in two parts. First one is done and merged, the second one is coupled with changing Agents REST API and adjusting front-end part for it. Should I work on the second part ?

**Comment by slemeur** [comment]
@ibuziuk Yes sure ! It would definitely be great for the product ! 
We have not planned this work in the upcoming sprint for us, so if you would like to contribute it, it would be wonderful :) !

**Comment by ibuziuk** [comment]
@slemeur great! should I create another issue for it ?

**Comment by slemeur** [comment]
@ibuziuk Yes please, it would make it clearer ;)

**Comment by ibuziuk** [comment]
@slemeur done - https://github.com/eclipse/che/issues/2654
