### ISSUE TITLE
replace manual testing of deployment on openshift w/ PR validation check that triggers CRW QE Jenkins automated e2e test to deploy on OCP 4.4, 3.11, 4.5, 4.3

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17747]
### Is your enhancement related to a problem? Please describe.

Rather than manually testing new PRs for openshift for Che operator release, we should have PR validation check(s) that trigger automated e2e tests for testing deployment on OCP 4.4, 3.11, 4.5, 4.3

**Comment by rhopp** [comment]
@nickboldt @mkuznyetsov I'm not really sure what this issue should be about...
Who is doing this manual testing and what it consist of?

**Comment by nickboldt** [comment]
@flacatus @mkuznyetsov can you elaborate on what's being done today and what should be automated in future?

**Comment by nickboldt** [comment]
for example @rhopp ... 
![image](https://user-images.githubusercontent.com/227597/93083018-e7d45600-f65f-11ea-8da5-5afc952620da.png)

**Comment by flacatus** [comment]
@nickboldt @mkuznyetsov ci.centos will be deprecated soon. The problem which we have now it is we are not able to run ocp 3.11 anywhere... I tried using github actions and I didn't got a good result. 
We need to setup job for 4.3 in openshift ci.

**Comment by flacatus** [comment]
Also I tried to setup OCP 3.11 tests in Openshift CI. In this case che-operator is trying to certificates from the test route. That means the test routes will be exposed in 443 port which is blocked in Openshift CI... Here are the logs: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/11715/rehearse-11715-pull-ci-che-incubator-chectl-master-3.11-chectl-e2e/1304364041803665408/artifacts/chectl-e2e/pods/che_che-operator-65ff745cfc-lkvq9_che-operator.log

**Comment by flacatus** [comment]
@nickboldt Do we think we need to add also `4.6-Nightly`?
