### ISSUE TITLE
Broken contribute/developer workspace badge for external repos README.md

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17758]
Readme files in any repo using badges with https://che.openshift.io/factory/resources/factory-contribute.svg image are broken.

![image](https://user-images.githubusercontent.com/650571/91734502-4b17b000-ebab-11ea-8744-54071549220d.png)

Note that we give that file as an example in our doc: https://www.eclipse.org/che/docs/che-7/end-user-guide/workspaces-overview/#_including_the_developer_workspace_badge_in_a_readme

**Comment by sunix** [comment]
maybe related to that: https://github.com/eclipse/che/commit/2baa79c9684eb2221cdf364ac7460db6d489d9ff

**Comment by ibuziuk** [comment]
@sunix I guess we can close the issue, also the docs have been updated - https://github.com/eclipse/che-docs/pull/1884
