### ISSUE TITLE
Failed to run workspace: failed to mount volume

### ISSUE THREAD

**Issue by samschurter** [eclipse-che/che#17751]
### Describe the bug
Trying to launch any workspace, existing or new results in the following:
```
Error: Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'FailedMount', 'Unable to mount volumes for pod "workspacesmc4lnjqzmlql6t4.che-plugin-broker_skippotter1-che(ac413392-ea24-11ea-99e2-029a5a55534e)": timeout expired waiting for volumes to attach or mount for pod "skippotter1-che"/"workspacesmc4lnjqzmlql6t4.che-plugin-broker". list of unmounted volumes=[claim-che-workspace]. list of unattached volumes=[broker-config-volumeuit5qz claim-che-workspace workspacesmc4lnjqzmlql6t4-sshprivatekeys ssshkeyconfigvolume gitconfigvolume che-workspace-token-rfh2q]', 'workspacesmc4lnjqzmlql6t4.che-plugin-broker'"
```

Logging in to the cluster console as described in the FAQ shows a non-stop stream of events, it's constantly creating a pod, failing to mount volumes, and trying again.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.17.2

### Steps to reproduce

1. Log in to hosted Che
2. Click on a workspace to start it 
3. Wait

### Expected behavior
Expect to see the workspace begin to load with log message about starting plugins and pulling images etc. Instead the loading screen displays until timeout when the error appears.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: hosted

### Screenshots

![image](https://user-images.githubusercontent.com/7039470/91644014-dd7a5100-e9fd-11ea-9602-f97cb489faea.png)
![image](https://user-images.githubusercontent.com/7039470/91644138-dc95ef00-e9fe-11ea-8968-860a8eca0e08.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [x] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
@samschurter It seems to be infrastructure issue... Are you able to start any pod(not Che Workspace) with PVC mounted?
Could you try to reconfigure workspace in temporary storage mode?

**Comment by ibuziuk** [comment]
@samschurter If it was che.openshift.io specific than the incident is resolved already - https://che.statuspage.io/incidents/dp42q8xv257h

**Comment by samschurter** [comment]
This seems to have fixed it. The pod stopped restarting and workspaces are launching normally.
