### ISSUE TITLE
How to fix che theia gyp ERR! configure error  gyp ERR! stack Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by GNSubrahmanyam** [eclipse-che/che#17752]
[LOCAL] ~/Desktop/practice/theia/che-theia/theia[master]:$ yarn install
yarn install v1.22.5
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.22.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.22.0/node-v10.22.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.22.0/node-v10.22.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.22.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.22.0/SHASUMS256.txt
10.22.0
gyp info ok 
[1/5] Validating package.json...
error @theia/monorepo@0.0.0: The engine "node" is incompatible with this module. Expected version ">=12.14.1 <13". Got "10.22.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[LOCAL] ~/Desktop/practice/theia/che-theia/theia[master]:$ sudo n 12.18.3
[sudo] password for subrahmanyam: 
   installed : v12.18.3 (with npm 6.14.6)
[LOCAL] ~/Desktop/practice/theia/che-theia/theia[master]:$ yarn install
yarn install v1.22.5
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v12.18.3/node-v12.18.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.18.3/node-v12.18.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.18.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.18.3/SHASUMS256.txt
12.18.3
gyp info ok 
[1/5] Validating package.json...
[2/5] Resolving packages...
warning workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @eclipse-che/theia-plugin-ext > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
[3/5] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning "workspace-aggregator-a23a509c-ee86-4bbb-9f7b-3cefa755c414 > @eclipse-che/theia-assembly > html-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
[1/16] ⢀ command-join
[7/16] ⠠ drivelist
[6/16] ⠠ native-keymap
[4/16] ⠠ puppeteer
error /home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.18.3 | linux | x64
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/subrahmanyam/.cache/node-gyp/12.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/subrahmanyam/.cache/node-gyp/12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/subrahmanyam/.cache/node-gyp/12.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Package xkbfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbfile' found
gyp: Call to '${PKG_CONFIG:-pkg-config} x11 xkbfile --cflags | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/electron-rebuild/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.0.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/subrahmanyam/Desktop/practice/theia/che-theia/theia/node_modules/native-keymap

**Comment by vparfonov** [comment]
@azatsarynnyy Please take a look

**Comment by azatsarynnyy** [comment]
Hello @GNSubrahmanyam 
please, make sure that you have all the prerequisites installed.
See the docs https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites

**Comment by tsmaeder** [comment]
Your node version seems to be out of date
```
error @theia/monorepo@0.0.0: The engine "node" is incompatible with this module. Expected version ">=12.14.1 <13". Got "10.22.0"
```

**Comment by azatsarynnyy** [comment]
> Your node version seems to be out of date
> 
> ```
> error @theia/monorepo@0.0.0: The engine "node" is incompatible with this module. Expected version ">=12.14.1 <13". Got "10.22.0"
> ```

@tsmaeder I spotted it as well but then, after a closer inspection, I've seen that there are two executions in the attached output.

Below, there's another run with the correct Node version:
`gyp info using node@12.18.3 | linux | x64`
