### ISSUE TITLE
Display list of plugin version respecting semantic versioning scheme

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#17753]
### Is your enhancement related to a problem? Please describe.

in View -> plugins, when clicking on the little arrow to see available versions. The list is sorted in revered Alphanumerically order. Consequently, version 0.0.9 appears before 0.0.10. 

### Describe the solution you'd like
having a sort respecting semantic version would be easier.

### Additional context
You can notice it currently with Camel K

![Screenshot from 2020-08-31 08-58-55](https://user-images.githubusercontent.com/1105127/91691818-952b7200-eb68-11ea-9664-f5292f8da2b2.png)

**Comment by ericwill** [comment]
Only the latest version of a plugin is kept in the registry, so this is no longer relevant.
