### ISSUE TITLE
Helm installer is broken

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17766]
### Describe the bug
When try to install Eclipse Che using chectl and helm installer it fails.

### Che version
nightly

### Steps to reproduce

Run:
```sh
chectl server:start --platform=minikube --installer=helm
```

### Expected behavior
Helm installer installs Che

### Runtime
kubernetes

### Installation method
chectl

### Environment
minikuibe

### Eclipse Che Logs
Erorr log of Che server:
```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, org.eclipse.che.api.workspace.server.spi.InfrastructureException: Neither KUBERNETES_NAMESPACE nor POD_NAMESPACE is defined. Unable to determine Che installation location
  at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.CheNamespace.<init>(CheNamespace.java:54)
  at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.CheNamespace.class(CheNamespace.java:54)
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.namespace.CheNamespace
```

### Additional context
Operator installation works as expected

**Comment by sparkoo** [comment]
@mmorhun to give you some context, I've intentionally introduced this into che-server with https://github.com/eclipse/che/pull/17557 (https://github.com/eclipse/che/pull/17557/files#diff-8855fac8bb68d106dd25037d440a3e22R43). It previously just silently returned `null`, which was imho silent ticking bomb. I didn't know that it's not set in helm. Sorry for that, I should have tested it and communicate it sooner with you.

**Comment by mmorhun** [comment]
Fixed
