### ISSUE TITLE
Add a Lombok extension to Che plugin registry.

### ISSUE THREAD

**Issue by asavin-cl** [eclipse-che/che#17767]
As you may know, many developers use **Lombok** during writing the code.
Could you add a **Lombok extension** to Che? It will increase the usability of your product.
Link to VS Code extension:
https://marketplace.visualstudio.com/items?itemName=GabrielBB.vscode-lombok

**Comment by sparkoo** [comment]
@asavin-cl are you interested in contributing it?

**Comment by gattytto** [comment]
duplicate of https://github.com/eclipse/che/issues/17483

@asavin-cl we can continue on the other issue and maybe you can close this one?.

**Comment by ericwill** [comment]
Closed as duplicate of #17483
