### ISSUE TITLE
Make sure E2E tests are working successfully after WorkspaceConfig related REST API has been removed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17762]
### Is your task related to a problem? Please describe.
There is PR https://github.com/eclipse/che/pull/17682 to removed **WorkspaceConfig** related REST API.

It could affect E2E selenium tests which relies on **WorkspaceConfig** API:
- https://github.com/eclipse/che/blob/master/tests/legacy-e2e/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/factory/TestFactoryInitializer.java#L199
- https://github.com/eclipse/che/blob/1179cd25bbc2c75e983eb5383cf3185c40d1a365/tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceConfig.java#L75
- https://github.com/eclipse/che/blob/1179cd25bbc2c75e983eb5383cf3185c40d1a365/tests/legacy-e2e/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/dashboard/workspaces/WorkspaceConfig.java#L36
...

### Describe the solution you'd like
TBD

**Comment by SkorikSergey** [comment]
WorkspaceConfig related REST API removing showed no regression in java selenium tests.
