### ISSUE TITLE
"Possibly unhandled rejection" error on Dashboard

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#17779]
### Describe the bug
There is `"Possibly unhandled rejection"` error in web console after Dashboard is open. The error appeared after [Removed WorkspaceConfig related REST API](https://github.com/eclipse/che/pull/17682) changes.

### Che version
 - [x] latest

### Runtime
   - [x] Openshift 3.11

### Screenshots
![Selection_085](https://user-images.githubusercontent.com/7760565/92112179-13e90f00-edf6-11ea-9b56-0901adcd37b9.png)

### Installation method
   - [x] chectl

### Eclipse Che Logs
[che-657b84d5fc-k2fr7.log](https://github.com/eclipse/che/files/5168316/che-657b84d5fc-k2fr7.log)

**Comment by akurinnoy** [comment]
should be fixed by https://github.com/eclipse/che-dashboard/pull/90
