### ISSUE TITLE
Add Device logging for Artik

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1777]
It should be possible to get logs from device. At the moment it's not clear what exact logs, we may start with executing such a command as `journalctl -f`

This should be a button on consoles panel, next to terminal. We may also have it in Artik menu

**Comment by TylerJewell** [comment]
@jamesdrummond, @ashumilova @bmicklea - please move into ARTIK project.

**Comment by ashumilova** [comment]
Solved in artik project by adding a command to workspace.
