### ISSUE TITLE
Eclipse Che is failed to deploy on Minishift

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17770]
### Describe the bug
Eclipse Che is failed to deploy on Minishift

### Che version

 - [x] nightly

### Steps to reproduce
Follow the doc https://www.eclipse.org/che/docs/che-7/overview/installing-che-on-minishift/

### Expected behavior
Deployment is succeeded

### Runtime
   - [x] minishift (include output of `minishift version` and `oc version`)

### Installation method
   - [x] chectl
     * `server:start --platform minishift --installer operator`
     * `chectl/0.0.20200831-next.9be13df linux-x64 node-v10.22.0`

### Environment
   - [x] my computer
       - [x] Linux

### Eclipse Che Logs
```
2020-09-02 07:54:15,925[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 175]  - Exception sending context initialized event to listener instance of class [org.eclipse.che.inject.CheBootstrap]
--
  | com.google.inject.CreationException: Unable to create injector, see the following errors:
  | 1) Error injecting constructor, org.eclipse.che.inject.ConfigurationException: Unsupported server naming strategy 'default-host' configured
```

**Comment by flacatus** [comment]
I can observe the same problem in OCP 4.X

![image](https://user-images.githubusercontent.com/59865209/91957862-e3767780-ed06-11ea-93e9-f88faef4e38f.png)

**Comment by sparkoo** [comment]
@tolusha Issue is caused by this PR https://github.com/eclipse/che/pull/17765 which enables to set exposure strategy on OpenShift, which was ignored before. Default value is default-host, which is invalid on OpenShift. We have there multi-host and now new coming single-host.

**Comment by sparkoo** [comment]
@flacatus @tolusha can you please verify that setting `CHE_INFRA_KUBERNETES_SERVER__STRATEGY=multi-host` fix the issue ?

**Comment by SkorikSergey** [comment]
Setting `CHE_INFRA_KUBERNETES_SERVER__STRATEGY=multi-host` fixes this issue.

**Comment by dmytro-ndp** [comment]
@sparkoo, @skabashnyuk: do you happened to know if `CHE_INFRA_KUBERNETES_SERVER__STRATEGY=multi-host` has to be by default?

**Comment by sparkoo** [comment]
@dmytro-ndp `CHE_INFRA_KUBERNETES_SERVER__STRATEGY=multi-host` is explicitly set by Operator and Helm for k8s. For OpenShift, it fallback to what is set in che.properties, which is `default-host` now.

I'll change default in `che.properties` to multi-host in che-server and imho we should start setting it explicitly for OpenShift from installers as well.
