### ISSUE TITLE
In che-docs can we remove the config for the maven build?

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#17778]
To publish che-docs on www.eclipse.org, we do not use these files:

- .ci/*
- make-release.sh
- pom.xml

As far as I know, they were used by ant builds to embed the documentation into the application.

This issue is to double-check that we may remove all these files safely.

**Comment by benoitf** [comment]
I would say that ci.centos.org jobs should be removed first as well (or after as they're all failing)
https://ci.centos.org/job/devtools-che-docs-che-nightly/
https://ci.centos.org/job/devtools-che-docs-che-build-master/
https://ci.centos.org/job/devtools-che-docs-che-release/
