### ISSUE TITLE
Devfile registry nightly builds are unstable due to timeout

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17776]
### Is your task related to a problem? Please describe.
Nightly [devfile registry builds](https://ci.centos.org/job/devtools-che-devfile-registry-nightly/) are timing out more often than not at around 40 minutes. Successful runs appear to take around 20 minutes, so I suspect it's due to slow pulls while building the user ID patch images/the happy path image.

### Describe the solution you'd like
We should look into increasing the timeout for devfile registry CI builds.

### Describe alternatives you've considered
We could potentially also disable nightly builds for UID patch images, since they don't change that often, but it would require using different tags for master branch devfiles and updating the release scripts to correctly set release versions.

Alternatively, we could split the CI build into separate builds for the devfile registry and for the devfile/happy path images, but that does not solve the time problem, as sometimes it times out before finishing building just the UID patch images.

**Comment by rhopp** [comment]
I removed `area/qe` label as this issue doesn't seem like it has anything to do with QE - added label `area/productization`

**Comment by ericwill** [comment]
This may not be an issue anymore since devfile registry nightly builds occur [via GitHub action](https://github.com/eclipse/che-devfile-registry/actions?query=workflow%3ABuild%2FPush).

**Comment by nickboldt** [comment]
Closing as no more complaints in this thread for nearly a year.
