### ISSUE TITLE
On Launching VSCODE extension webview che workspace hangs

### ISSUE THREAD

**Issue by nsharma1989** [eclipse-che/che#17786]
### Describe the bug
I am trying to test my vscode extensions on che workspace. The extensions are installed correctly. I see all the console logs verifying that the plugins were installed. However when I try to run the command which opens up my extensions webview it shows a blank white page and then my workspace hangs forever and give me attached logs in dev tools. and after a certain period I get 
`hhttps://servernevegy2a-jwtproxy-webviews.192.168.64.9.nip.io/webview/theia-resource/file/tmp/vscode-unpacked/test-extension.1.0.1.qgbzmhxrgb.test-extension-1.0.0.vsix/extension/dist/bundle.js` net::ERR_FAILED

### Che version

 - [] latest
 - [ ] nightly
 - [x] other: please specify 7.18 

### Expected behavior
webview should be able to access local resources from the dist folder

### Runtime
   - [x] kubernetes 1.18.3
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (1.12.3 
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

<img width="438" alt="Screen Shot 2020-09-03 at 10 41 38 PM" src="https://user-images.githubusercontent.com/18398195/92193919-73b3da00-ee37-11ea-8b31-c58fafd5f78e.png">

### Installation method
   - 

- [x] chectl
chectl/7.18.0 darwin-x64 node-v10.22.0
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by nsharma1989** [comment]
Hi it looks like my webview extension is not loading the js files bundle.js and polyfill.js.

**Comment by l0rd** [comment]
@nsharma1989 it would be helpful if you could provide the steps needed to reproduce your problem.

**Comment by nsharma1989** [comment]
Hi @l0rd , Thank you for your reply.. the problem was resolved . It looks like `vscode-resource` schema is not being recognized by che-theia and thus blocking my extensions script files . This problem didn't occurred in Theia. I removed vscode-resource schema and added a nounce with the scripts and it worked.

**Comment by nsharma1989** [comment]
closing the issue as this was resolved after using `vscode.webview.asWebviewUri`
