### ISSUE TITLE
Single-host testing on OpenShift

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17789]
### Is your task related to a problem? Please describe.
We should figure out where we are with single-host implementation  https://github.com/eclipse/che/issues/12914 on OpenShift.

### Describe the solution you'd like
Run as much as possible automated tests.

### Describe alternatives you've considered
- add some manual testing
### Additional context
**Known issues** 
 - Running demo application of 'java-web-spring' doesn't work in CHE 'single-host' on k8s https://github.com/eclipse/che/issues/17783 -> **Resolved, partially. There was opened the another:**
- [che-theia] - open http preview in separate browser tab https://github.com/eclipse/che/issues/18002
- 'Plugins' list is absent in IDE in CHE 'single-host' on k8s https://github.com/eclipse/che/issues/17749 -> **Resolved, the issue is closed**

**Comment by skabashnyuk** [comment]
How to setup environment https://github.com/eclipse/che/issues/16842#issuecomment-686960328

**Comment by artaleks9** [comment]
* On this moment was checked installation CHE 'single-host' on OCP 4.5 by using specific 'che-operator' and 'patch-cr.yaml' provided 'platform-team'. 
CHE 'single-host' was installed and worksapce launched. 'Smoke' tests have found a problem with run demo application which is describided in #17783
* I'm planning to update script and run E2E tests in specific job for  CHE 'single-host' on OCP 4.5 /4.4

**Comment by artaleks9** [comment]
* There were created two jobs which can launch E2E tests on CHE  with 'single-host' strategy:
-[che-single-host-chectl-tls-oauth](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che17789-che-chectl-tls-oauth/)
-[che-single-host-chectl-tls-no-oauth](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che17789-che-chectl-tls-no-oauth/)
* Results of E2E and manual tests don't show blockers issue on this moment.
* There was done several runs on OCP 4.5/4.4/3:
-Devfile E2E tests (in some runs some of test were fail by flakiness reasons, the similar results are on 'default-nightly' Che) 
-Git SSH flow E2E test (is success)
-Dashbord Java E2E  (some of them were fail, and require rework / update)
-Happy path E2E test is not still implemented to run on OCP (working in progress)

**Comment by artaleks9** [comment]
* The 'Happy-path' E2E test was implemented to launch on CHE 'single-host' on OCP. There was done several runs - it is OK. Considering thew known issue #17783, in 'Happy-path' E2E test was done a workaround for it. 
* Launching 'Happy-path' test is working for CHE with TLS and without oAuth and is not untill working on CHE with both TLS and oAuth. A problem, it seems,  is on test side and is in progress work.
* After the last changes in 'che-operator' and 'patch-yaml' (see https://gist.github.com/sparkoo/0b45957eee70a35f05b93ad1796f7948) there is reproduced the bug with 'Plugins' list which is describded in #17749

**Comment by artaleks9** [comment]
* I think, the goal of this issue was reached.
* The issue can be closed.

**Comment by rhopp** [comment]
Automation is being done in https://github.com/eclipse/che/issues/17789
