### ISSUE TITLE
Che on EC2 : Using AWS Certificate instead of Letsencrypt certificate

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#17798]
Thank you all,
I was able to run Che on EC2 instance by following the procedure given here:
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-aws/

In step 11, Lets encrpt certificate is used to setup the cert manager.
I would like to know how I can setup this using an AWS certificate instead of Let's Encrpyt certificate.
Please help.

**Comment by l0rd** [comment]
cc @benoitf

**Comment by MichalMaler** [comment]
Hello Florent. Please, I assigned you (after conv with Sun) to this old issue.

Is that ok? Does this work for you?
Don't want to put more load on your shoulders, nor I have a position to do some requests here. I just want to clear the PRs that have the `docs` label on it and help with them if possible.
Thank you @benoitf
