### ISSUE TITLE
OLM not upgrading stable version of che-operator

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#17792]
## Summary
I installed eclipse che via operator hub with the following steps as per the instructions here https://operatorhub.io/operator/eclipse-che
1) Installed OLM
2) Installed che-operator
3) installed the che crd

This is a normal kubernetes setup and I was able to get che running and everything is fine.  

The version of che installed is 7.17.2 (this was a couple of weeks back).  I now see the stable version available on operatorhub is 7.18.0.   Also the latest version of che-opertor in quay.io is 7.18.0

I had expected olm to upgrade the che-operator and in turn upgrade the che version as well to the latest.  As per this link. https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/catalog-polling.md I did add updateStrategy with a registryPoll interval of 15 mts. 

What am i missing here. Shouldn't the upgrade of che-operator and the che version be taken care of via the OLM?

**Comment by pgirishibm** [comment]
The CatalogSource has the following
spec:
  displayName: Community Operators
  image: quay.io/operator-framework/upstream-community-operators:latest
  publisher: OperatorHub.io
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m

The Subscription has the following..
$ kubectl describe  Subscription playground-dev-subscription -n playground-dev
Spec:
  Channel:           stable
  Name:              eclipse-che
  Source:            operatorhubio-catalog
  Source Namespace:  olm
Status:
  Catalog Health:
    Catalog Source Ref:
      API Version:       operators.coreos.com/v1alpha1
      Kind:              CatalogSource
      Name:              operatorhubio-catalog
      Namespace:         olm
      Resource Version:  13229588
      UID:               17e31a64-686c-4a91-a994-c87f742b2432
    Healthy:             true
    Last Updated:        2020-09-07T05:34:31Z
  Conditions:
    Last Transition Time:  2020-09-07T05:34:31Z
    Message:               all available catalogsources are healthy
    Reason:                AllCatalogSourcesHealthy
    Status:                False
    Type:                  CatalogSourcesUnhealthy
  Current CSV:             eclipse-che.v7.18.0
  Install Plan Ref:
    API Version:       operators.coreos.com/v1alpha1
    Kind:              InstallPlan
    Name:              install-5486d
    Namespace:         playground-dev
    Resource Version:  446266
    UID:               506ac50f-2381-40af-bf14-0e6afa66f1c8
  Installed CSV:       eclipse-che.v7.17.2
  Installplan:
    API Version:  operators.coreos.com/v1alpha1
    Kind:         InstallPlan
    Name:         install-5486d
    Uuid:         506ac50f-2381-40af-bf14-0e6afa66f1c8
  Last Updated:   2020-09-07T05:34:31Z
  State:          UpgradePending
Events:           <none>

The InstallPlan has the following
$ kubectl get InstallPlan -n playground-dev
NAME            CSV                   APPROVAL    APPROVED
install-5486d   eclipse-che.v7.17.2   Automatic   true
$

**Comment by pgirishibm** [comment]
The CatalogSource does seem to attempt an upgrade but shows a Transient failure. 

Name:         operatorhubio-catalog
Namespace:    olm
Labels:       <none>
Annotations:  <none>
API Version:  operators.coreos.com/v1alpha1
Kind:         CatalogSource
Spec:
  Display Name:  Community Operators
  Image:         quay.io/operator-framework/upstream-community-operators:latest
  Publisher:     OperatorHub.io
  Source Type:   grpc
  Update Strategy:
    Registry Poll:
      Interval:  45m
Status:
  Connection State:
    Address:                   operatorhubio-catalog.olm.svc:50051
    Last Connect:              2020-09-07T05:21:34Z
    Last Observed State:       TRANSIENT_FAILURE
  Latest Image Registry Poll:  2020-09-07T05:21:14Z
  Registry Service:
    Created At:         2020-09-04T06:58:41Z
    Port:               50051
    Protocol:           grpc
    Service Name:       operatorhubio-catalog
    Service Namespace:  olm
Events:                 <none>


What can i check further?

**Comment by tolusha** [comment]
@AndrienkoAleksandr 
Can we suggest anything here?

**Comment by pgirishibm** [comment]
I saw the CatalogSource pods in the olm namespace were going into a CrashLoopBackOff state. I recreated those pods and now I see the CatalogSource is in READY state and the CatalogSource pods are also in good state.

The eclipse-che Subscription is still showing as UpgradePending. 

  spec:
    channel: stable
    name: eclipse-che
    source: operatorhubio-catalog
    sourceNamespace: olm
  status:
    catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: operatorhubio-catalog
        namespace: olm
        resourceVersion: "13340135"
        uid: 17e31a64-686c-4a91-a994-c87f742b2432
      healthy: true
      lastUpdated: "2020-09-07T08:07:07Z"
    conditions:
    - lastTransitionTime: "2020-09-07T08:07:07Z"
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: "False"
      type: CatalogSourcesUnhealthy
    currentCSV: eclipse-che.v7.18.0
    installPlanRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
      name: install-5486d
    installedCSV: eclipse-che.v7.17.2
    installplan:
      apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
      name: install-5486d
    lastUpdated: "2020-09-07T08:07:07Z"
    state: UpgradePending

**Comment by AndrienkoAleksandr** [comment]
Hello. Yes, old Olm manager really had some ugly issue with stability: https://github.com/operator-framework/operator-lifecycle-manager/issues/1087 But I think it was fixed. I recommend to use newer olm manager, at least 0.15.1. There is newer 0.16.1, but I didn't tested it yet.

When olm pods are green it is doesn't mean they are working. They could be in synchronization state. To make sure that CatalogSource with Eclipse Che was really synced with operatorhub: 

```bash
$ kubectl get packagemanifest -n olm | grep eclipse-che
### Output:
eclipse-che                                Community Operators   12h
```

If this command return an emty list, then community CatalogSource is still syncing with operatorHub.

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr I have 0.15.1 olm manager.  running the command gives me this.

$ kubectl get packagemanifest -n olm | grep eclipse-che
eclipse-che                                Community Operators   116d
$ 

Also, I reinstalled the che-operator and i can see the new version of the che-operator getting installed.  

Any other thoughts on how i can get the upgrade happen automatically?

**Comment by AndrienkoAleksandr** [comment]
> Any other thoughts on how i can get the upgrade happen automatically?

I think it should work automatically from the box.

**Comment by AndrienkoAleksandr** [comment]
But, You can force your Subscription to 'Automatic' mode (but I believe that this mode is 'Automatic' from the box):

```
$ kubectl get subscription my-eclipse-che -n my-eclipse-che -o yaml
$ kubectl patch subscription/my-eclipse-che -n my-eclipse-che --type=merge -p '{"spec":{"installPlanApproval":"Automatic"}}'
```

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr  I will try out the above and get back, Thank you for those pointers. 

another question.  once the che-operator is upgraded , Should the che instance also get upgraded automatically or does that need an edit to the che crd?

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr quick thought here.  

Does the namespace in which  the che-operator and the che instance are deployed have any particular naming convention? Also, I have multiple instances of che deployed in different namespaces.

**Comment by tsmaeder** [comment]
From the comments, this looks like it's a bug.

**Comment by AndrienkoAleksandr** [comment]
> another question. once the che-operator is upgraded , Should the che instance also get upgraded automatically or does that need an edit to the che crd

olm brings new crd from olm package, so you don't think that You need to upgrade crd.

> che instance are deployed have any particular naming convention?

We don't have namespace naming convention. You can use any namespace where is you have permissions.

**Comment by AndrienkoAleksandr** [comment]
> From the comments, this looks like it's a bug.

I, Agree it can be a bug. But I'm not sure that's a bug on the Che side. Maybe it's a bug of the Olm... Any way we should investigate more.

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr  I meant the che crd.  Once the che-operator is upgraded, what triggers the upgrade of the che-server? Should that also happen automatically?

**Comment by AndrienkoAleksandr** [comment]
Whole picture: Olm installs che-operator using package: https://github.com/eclipse/che-operator/tree/master/olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.18.0 In the package you can see file with Che CRD(https://github.com/eclipse/che-operator/blob/master/olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.18.0/eclipse-che-preview-kubernetes.crd.yaml). Olm should upgrade Che crd. Then will be deployed che-operator using deployment and permission definitons from CSV file(https://github.com/eclipse/che-operator/blob/master/olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/eclipse-che-preview-kubernetes/7.18.0/eclipse-che-preview-kubernetes.v7.18.0.clusterserviceversion.yaml) User should apply (manually or using Olm ui) `che-cluster' object. This action trigger che-operator to start installation Eclipse Che. che-operator installs postrgress, keyckloak(for multi-user), plugin registry, devfile registry and finally che-server.

**Comment by tolusha** [comment]
> I meant the che crd. Once the che-operator is upgraded, what triggers the upgrade of the che-server? Should that also happen automatically?

I will happens automatically

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr  I am seeing these logs in the catalog-operator pod.  

time="2020-09-17T13:38:53Z" level=warning msg="an error was encountered during reconciliation" error="Operation cannot be fulfilled on subscriptions.operators.coreos.com \"my-eclipse-che\": the object has been modified; please apply your changes to the latest version and try again" event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/my-eclipse-che/subscriptions/my-eclipse-che
E0917 13:38:53.687395       1 queueinformer_operator.go:290] sync {"update" "my-eclipse-che/my-eclipse-che"} failed: Operation cannot be fulfilled on subscriptions.operators.coreos.com "my-eclipse-che": the object has been modified; please apply your changes to the latest version and try again
time="2020-09-17T13:38:53Z" level=info msg=syncing event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/pg-imagepuller-operator/subscriptions/pg-imagepuller-operator
time="2020-09-17T13:38:53Z" level=info msg=syncing event=update reconciling="*v1alpha1.Subscription" selflink=/apis/operators.coreos.com/v1alpha1/namespaces/my-eclipse-che/subscriptions/my-eclipse-che

I cleaned up the che-operator and re-installed it. Also upgraded olm to 0.16.1. But still see these logs. Does this give any clue on what is wrong in my setup?

**Comment by AndrienkoAleksandr** [comment]
@pgirishibm Could you try to install che to another namespace?

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr I did. I see the above logs for all the namespaces that i install che into.. Infact the logs start showing up as soon as i install the che-operator (in any namespace). i,e. before I even create the che instance.  The eclipse-che subscription is what seems to be conflicting with some template (probably in the Catalog? ).

**Comment by AndrienkoAleksandr** [comment]
Could you provide more info about your cluster? If it's a minikube, then version. I will try to reproduce it. Also I asked olm developers about such error log, maybe they have any hints.

**Comment by AndrienkoAleksandr** [comment]
Also provide, please, che-operator logs. Maybe some error on the our side.

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr my cluster is on IBM Kubernetes Service.  My setup is currently in a bad state and I am setting it up once again, Will get back with the operator logs once thats done.

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr After I setup my che environment afresh, the che version installed was 7.18.2.   Today, I observed that the upgrade from 7.18.2 to 7.19.1  happened automatically. 

Looking back at how i had setup my earlier environment, I realize, after installation, I used to edit the CheCluster resource via the 'kubectl edit' command. I had to do it to add new CheProperties which i had missed while applying the CRD.    Wondering if that is the cause of the original issue?  Could it also be the reason for the "the object has been modified"  logs in the Catalog Operator which i pasted above? 

I am trying to recreate the problem once again by doing a 'kubectl edit'. Will post the logs if i am able to see the issue.

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr Sorry for the delay on this. I was able to setup the cluster once again and i do not see the eclipse che upgrade happening.    

Currently i have 7.19.2 installed. 
$ kubectl get csv -n my-eclipse-che
NAME                  DISPLAY       VERSION   REPLACES              PHASE
eclipse-che.v7.19.2   Eclipse Che   7.19.2    eclipse-che.v7.19.1   Succeeded
$

I do not see any logs in the che-operator related to upgrade. But the catalog-operator in olm is showing these logs. Attached file has the catalog-operator logs.. 

Also I have multiple instances of che on my cluster.

$ kubectl get CheCluster -A
NAMESPACE        NAME                     AGE
default          pg-security              56d
my-eclipse-che   eclipse-che              22h
pg-security      pg-security              52d
pg-dev   pg-dev-cluster   58d
$ kubectl get InstallPlan -A
NAMESPACE                 NAME            CSV                                      APPROVAL    APPROVED
pg-security               install-8h2db   eclipse-che.v7.19.2                      Automatic   true
pg-security               install-jndgz   eclipse-che.v7.19.1                      Automatic   true
pg-dev            install-xzx9f   eclipse-che.v7.18.2                      Automatic   true
pg                install-bg2zz   eclipse-che.v7.12.2                      Automatic   true
$  kubectl get csv -A
NAMESPACE                 NAME                                     DISPLAY                            VERSION   REPLACES              PHASE
my-eclipse-che            eclipse-che.v7.19.2                      Eclipse Che                        7.19.2    eclipse-che.v7.19.1   Succeeded
pg-security               eclipse-che.v7.19.2                      Eclipse Che                        7.19.2    eclipse-che.v7.19.1   Succeeded
pg-dev            eclipse-che.v7.18.2                      Eclipse Che                        7.18.2    eclipse-che.v7.18.0   Succeeded
pg                eclipse-che.v7.12.2                      Eclipse Che                        7.12.2                          Succeeded
$ kubectl get Subscription -A
NAMESPACE                 NAME                          PACKAGE                           SOURCE                  CHANNEL
my-eclipse-che            my-eclipse-che                eclipse-che                       operatorhubio-catalog   stable
pg-security               pg-security-subscription      eclipse-che                       operatorhubio-catalog   stable
pg-dev            pg-dev-subscription   eclipse-che                       operatorhubio-catalog   stable
pg                pg                    eclipse-che                       operatorhubio-catalog   stable
$ 


Any clues from the logs? 

E1120 12:45:19.323935       1 queueinformer_operator.go:290] sync "my-eclipse-che" failed: constraints not satisfiable: eclipse-che is mandatory, gvkunique/org.eclipse.che/v1/CheCluster permits at most 1 of operatorhubio-catalog/olm/stable/eclipse-che.v7.4.0, ........
Wondering if this indicates having multiple instances of CheCluster could have issues?

**Comment by pgirishibm** [comment]
[catalog-operator-logs.docx](https://github.com/eclipse/che/files/5573731/catalog-operator-logs.docx)

**Comment by pgirishibm** [comment]
Also 

$ kubectl get packagemanifest -n olm | grep eclipse-che
eclipse-che                                Community Operators   190d
$

Does 190d mean the Catalog Source last synched with Operatorhub 190 days back? Is that ok?

**Comment by pgirishibm** [comment]
@AndrienkoAleksandr  With the multiple install/uninstall we observed that the OLM fails to upgrade when a che operator after an uninstall is reinstalled onto the same namespace. 

I had a completely new che setup done onto a new namespace and I could find the upgrade happening via OLM.  That setup had to be reinstalled for a reason and we reinstalled onto the same namespace. since then the upgrade does not happen and the catalog operator  start showing the logs in the earlier attached file. 

any thoughts around this?

**Comment by tolusha** [comment]
@pgirishibm 
Could you provide commands or steps how did you reinstalled Eclipse Che ?

**Comment by pgirishibm** [comment]
@tolusha I had installed che via operatorhub. using the instructions given here. https://operatorhub.io/operator/eclipse-che

After installing OLM and the che operator, I created the "Custom Resource Definition" for my kubernetes cluster and ran 'kubectl create -f che.yaml -n my-eclipse-che'. This created all the pods for che. 

Inorder to uninstall I did a 'kubectl delete -f che.yaml -n my-eclipse-che'

Inorder to reinstall i ran the same step again. 'kubectl create -f che.yaml -n my-eclipse-che'.

**Comment by AndrienkoAleksandr** [comment]
Hello. I want to share a bit more information: don't use OLM addon from Minikube. It contains community catalog source image with hardcoded image tag instead of tag latest. That's why it can provide the latest release for operators https://github.com/kubernetes/minikube/issues/10768#issuecomment-831784280 . Minikube developers don't allow to use the latest tag, because that it could cause security issue. OLM developers recommends to use operator-sdk to install OLM on the k8s clusters (`operator-sdk olm install` command)
