### ISSUE TITLE
[devworkspace-operator] Should we create a community version of the Web Terminal Operator?

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17791]
## Summary
As far as I know, there is no timeline for a community release of the devworkspace operator. As we being talking about the Web Terminal operator release, we should consider also releasing something to the [community operators](https://github.com/operator-framework/community-operators) repo.

**Comment by l0rd** [comment]
I would say that:
- the web terminal operator should be Red Hat only
- the devworkspace operator should be decoupled from the web terminal and published in both:
  - in the Red Hat catalog so that it can be used by the Web Terminal and by CRW
  - in the Community catalog so that it can be used used by Che

**Comment by amisevsk** [comment]
@l0rd My main concern here is that as we talk of releasing WTO and start blogging about it, we'll be discussing something that is unavailable to a normal user. The audience we reach is much smaller if e.g. you can't just install the operator on `crc` via OperatorHub. Since users could simply go to `redhat-developer/web-terminal-operator` and run `make install` to install the operator on any cluster, we should consider doing a similar community release of the devworkspace-operator or something similar in the very near future (i.e. spin a community release off of https://github.com/redhat-developer/web-terminal-operator that uses the already-built quay images).

**Comment by amisevsk** [comment]
Issue is out of date.
