### ISSUE TITLE
Automate check for devfiles set to ephemeral by default

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#17794]
### Is your task related to a problem? Please describe.
Che stopped using Ephemeral mode as a default since 7.18.0
We need to make an automated test to verify that this option is selected by default

### Describe the solution you'd like
Automated typescript selenium test for GetStarted page checking the option before selecting a workspace and then verifying that the workspace is ephemeral by checking it's configuration in Workspaces tab

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Katka92** [comment]
Do you plan to have that as a separate test or to do the check before every workspace test?

**Comment by Katka92** [comment]
Closing, will not implement.
