### ISSUE TITLE
[Singlehost on Openshift] Keycloak behind the gateway

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#17809]
Because of the nature of its operation, Keycloak needs some non-standard configuration when put behind the reverse proxy (and therefore our Traefik-based gateway) - https://www.keycloak.org/docs/latest/server_installation/index.html#_setting-up-a-load-balancer-or-proxy.

We need to find the proper configuration of the Che ingress, Traefik gateway and Keycloak deployment so that they all play well together and Keycloak is able to correctly authenticate and redirect clients.

Based on the Keycloak documentation above, this following JBoss CLI script should be enough to configure it for functioning behind the gateway:

```
embed-server --server-config=standalone.xml --std-out=echo
/socket-binding-group=standard-sockets/socket-binding=proxy-https/:add(port=443)
/subsystem=undertow/server=default-server/http-listener=default/:write-attribute(name=redirect-socket, value=proxy-https)
stop-embedded-server
```

This script needs to be invoked in one of the setup scripts that are run before Keycloak is started in the `che-keycloak` image (https://github.com/eclipse/che/tree/master/dockerfiles/keycloak).

On the Traefik side, we need to ensure that it sends the proper `X-Forwarded-*` headers, possibly by configuring the behavior of endpoints - https://docs.traefik.io/v2.0/routing/entrypoints/.

This is a subtask of #12914.

**Comment by tolusha** [comment]
@metlos 
CRW uses a different identity provide image, we have to be sure that is works in the downstream as well.

**Comment by metlos** [comment]
No changes required in the identity provider image after all. We managed to do it all through traefik config. Implemented in https://github.com/eclipse/che-operator/pull/378 and #17064.
