### ISSUE TITLE
How to update devfile from workspace with command line?

### ISSUE THREAD

**Issue by sblumenstock-doubleSlash** [eclipse-che/che#17805]
I wonder if it is possible to update the devfile from a workspace with the command line?

**Comment by tolusha** [comment]
@sblumenstock-doubleSlash 
Could you elaborate more?

It is possible to create a workspace from a devfile using https://github.com/che-incubator/chectl/:
`chectl workspace:create`

**Comment by sblumenstock-doubleSlash** [comment]
No that's not what i want.
Is it possible to work on the same devfile (workspace) at several machines and update all these devfiles (workspaces) at the same time?

**Comment by RomanNikitenko** [comment]
@sblumenstock-doubleSlash 
If I understand correctly, you have one devfile which is used for creating workspaces on different machines.
If so, please take a look https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#what-is-a-devfile_configuring-a-workspace-using-a-devfile

> The devfile can be saved in the root folder of a Git repository, a feature branch of a Git repository, a publicly accessible destination, or as a separate, locally stored artifact.

So you could have one source for a devfile for creating workspaces.
Does it solve your issue?
If so, you can see detailed description for each way in the doc mentioned above.
For example, [Creating a workspace from a publicly accessible standalone devfile using HTTP](https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#creating-a-workspace-from-a-publicly-accessible-standalone-devfile-using-http_configuring-a-workspace-using-a-devfile)

**Comment by sblumenstock-doubleSlash** [comment]
> If I understand correctly, you have one devfile which is used for creating workspaces on different machines.

Yeah that is what I done so far. But now I change the devfile. Do I have to recreate all workspaces with this devfile now on every machine?
Or can I somehow update the workspaces so that they use the new devfile?

**Comment by RomanNikitenko** [comment]
> Yeah that is what I done so far. But now I change the devfile. Do I have to recreate all workspaces with this devfile now on every machine?
Or can I somehow update the workspaces so that they use the new devfile?

You can edit a devfile from dashboard for each workspace.
Unfortunately I don't know a way how to **update** all existed workspaces from one place.
