### ISSUE TITLE
As a user, I want to have a possibility to cleanup storage / PVC from User Dashboard

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17806]
### Is your task related to a problem? Please describe.
Eclipse Che should allow user to cleanup storage / recreate PVC 

### Describe the solution you'd like
Cleanup Storage Button available in the User Dashboard. 

### Describe alternatives you've considered
N/A

### Additional context
Example when this feature can be useful - https://github.com/eclipse/che/issues/17804

**Comment by sleshchenko** [comment]
Removing area/dashboard since there is nothing we can do with that until Che provides API for that.

**Comment by ibuziuk** [comment]
I think this issue can be closed due to the fact that now removal of all workspaces should also remove the common PVC - https://github.com/eclipse/che/issues/18369
