### ISSUE TITLE
How to solve cross domain problem when deploy docker on seperate node

### ISSUE THREAD

**Issue by Madixin** [eclipse-che/che#1781]
I have refered https://eclipse-che.readme.io/docs/usage-docker to deloy che and docker in different node

I have set DOCKER_MACHINE_HOST  and modify machine.docker.che_api.endpoint in the che.properties file.And it can run worksapce correctly on seperate node

However when I open che,I got "WebSocket connection to 'ws://10.93.95.35:32836/wsagent/ext/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED",I think this should be a cross domain problem,is there anyway to solove?

che version:4.3.0

**Comment by ghost** [comment]
@42690727 do you have 32836 port opened on 10.93.95.35 node? It looks like you are using an internal IP while it should be an external one.

**Comment by Madixin** [comment]
login 10.93.95.35 machine
root@SZX1000060086:/home/user/che# nc -v 10.93.95.35 32836 
nc: connect to 10.93.95.35 port 32836  (tcp) failed: Connection refused
root@SZX1000060086:/home/user/che# nc -v 127.0.0.1 32836 
Connection to 127.0.0.1 32836  port [tcp/*] succeeded!

I think there is no firewall policy

**Comment by Madixin** [comment]
root@SZX1000060086:/home/user/che# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

**Comment by ghost** [comment]
@42690727 you should make sure you can connect to Docker node from your local machine. Also, this node should have ephemeral port range opened. 

I have just started two nodes and checked it once again - it works, but opening ports is mandatory. Also, it should be an external IP.

**Comment by Madixin** [comment]
ok,I found the problem:  The terminal service is not work in workspace.   That is becuase the terminal directory in docker deamon machine is root permission ,while the workspace container is launch by user
