### ISSUE TITLE
Che-theia build fails

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#17812]
### Describe the bug

Che-theia build fails.
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1.Go to the root of the theia project.
2. Run `che-theia init`
3 Run `yarn`
See: an error appears:
```
@eclipse-che/theia-logging: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run lint
lerna ERR! error Command failed with exit code 1.
lerna ERR! 
lerna ERR! $ eslint --cache=true --no-error-on-unmatched-pattern=true "{src,test}/**/*.{ts,tsx}"
lerna ERR! 
lerna ERR! /home/ivinokur/projects/theia/che/che-theia/extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-backend-module.ts
lerna ERR!   1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing
lerna ERR! 
lerna ERR! /home/ivinokur/projects/theia/che/che-theia/extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-server.ts
lerna ERR!   1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing
lerna ERR! 
lerna ERR! ✖ 2 problems (2 errors, 0 warnings)
lerna ERR! 
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at /home/ivinokur/projects/theia/node_modules/execa/index.js:236:11
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
Error: Command failed: yarn run lint
error Command failed with exit code 1.

$ eslint --cache=true --no-error-on-unmatched-pattern=true "{src,test}/**/*.{ts,tsx}"

/home/ivinokur/projects/theia/che/che-theia/extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-backend-module.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/home/ivinokur/projects/theia/che/che-theia/extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-server.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

✖ 2 problems (2 errors, 0 warnings)

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at /home/ivinokur/projects/theia/node_modules/execa/index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 1,
  killed: false,
  stdout: '$ eslint --cache=true --no-error-on-unmatched-pattern=true "{src,test}/**/*.{ts,tsx}"\n' +
    '\n' +
    '/home/ivinokur/projects/theia/che/che-theia/extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-backend-module.ts\n' +
    "  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing\n" +
    '\n' +
    '/home/ivinokur/projects/theia/che/che-theia/extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-server.ts\n' +
    "  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing\n" +
    '\n' +
    '✖ 2 problems (2 errors, 0 warnings)\n' +
    '\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run lint',
  timedOut: false,
  exitCode: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by benoitf** [comment]
it looks strange as CI is building che-theia correctly

**Comment by RomanNikitenko** [comment]
@benoitf 
I think Igor faced with the issue at working che in che.
Theia bumped eslint related versions to 3.1.0
For 3.0.0 version `class-name-casing` was replaced by `naming-convention`: https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0

**Comment by benoitf** [comment]
@RomanNikitenko but theia is pinned down to an old version as it doesn't work with current theia no ?

**Comment by RomanNikitenko** [comment]
@benoitf 
I guess Igor used `master` of `theia` for che-in-che development.

@vinokurig is it correct?

**Comment by vinokurig** [comment]
@RomanNikitenko 
> I guess Igor used master of theia or his branch in theia based on master for che-in-che development.

checking out to `v1.5.0` in `theia` gives the same result.

**Comment by RomanNikitenko** [comment]
@vinokurig 
> checking out to v1.5.0 tag in theia gives the same result.

It's expected for me, because `v1.5.0` contains the corresponding commit https://github.com/eclipse-theia/theia/commit/8bf15dc1d9b186b11c1f954b4c51500e611d3072#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R20

**Comment by vinokurig** [comment]
Should be fixed by https://github.com/eclipse/che-theia/pull/823
