### ISSUE TITLE
[docs] Variable {prod-ver} is not kept up to date.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17817]
### Describe the bug
The Che documentation depends on variable `{prod-ver}` to refer to the currently-released version of Che in documentation. However, it appears that there is no process for updating this variable to the current version of Che, and it is currently set to [`7.15`](https://github.com/eclipse/che-docs/blob/3e9b404c0bef89b86546555213ffe0ee1c646799/antora.yml#L74). This results in pages such as https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-and-configuring-a-new-workspace/ being pushed to the docs.

There are currently 32 references to this out-of-date variable across our documentation.

**Comment by boczkowska** [comment]
@rkratky @themr0c we need to review all uses of the attribute and remove those that are non-essential.

**Comment by themr0c** [comment]
Is it possible to add in the manual checklist or automated process that does version bumps to maintain these 2 attributes also in antora-playbook.yml:

*     prod-prev-ver: 7.18
*     prod-ver: 7.19

Please keep in mind that only master is published, and `prod-ver` is referencing the version of Che that has already been released. As a consequence, `prod-ver` is always 1 version behind the version in the VERSION file, which is the next version.
