### ISSUE TITLE
How do I retrieve Keycloak admin password after installation

### ISSUE THREAD

**Issue by desaiRahulS** [eclipse-che/che#17816]
## Summary

I have installed Eclipse on Microsoft Azure by following the document here https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/.

Command ran to install: 
chectl server:start --installer=helm --platform=k8s --domain=<domain_name> --multiuser

The installation went fine, however I failed to save the auto generated keycloak admin password printed on the console and I am trying to figure out a way to retrieve it.

## Relevant information
Steps taken so far:
- Tried using admin:admin which did not work
- Tried looking into che.log and keycloak.log using the chectl server:logs and/or kubectl logs command which did not have the information I was looking for.
- Tried looking into the events logged under the che namespace

Any help would be appreciated.

**Comment by tolusha** [comment]
keycloak user/passwords are stored as env variables in the keycloak deployment:
- KEYCLOAK_USER
- KEYCLOAK_PASSWORD
