### ISSUE TITLE
State of the multi-module project is not restored

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1782]
After expanded the multi-module project if you go to Dashboard and return back, this project will be minimized

**Che version:**    [4.5.0]

**Comment by JamesDrummond** [comment]
@azatsarynnyy @vparfonov  Provide status label.

**Comment by artaleks9** [comment]
This bug is related with CHE-3021 (https://github.com/eclipse/che/issues/3021) and  right now it is not reproduced.
