### ISSUE TITLE
Stop using `self-signed-certificate` secret to store certificate chain of trust in favor of labeled config maps

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17825]
### Is your enhancement related to a problem? Please describe.
For the time being operator automatically creates `self-signed-certificate` secret also user is able to put additional certificates into `ca-certs` configmap. The main goal is to have a single place for all certificates. 

### Describe the solution you'd like
Investigate were `self-signed-certificate` secret is used.
Remove is usage ensure backward compatibility. 

### Additional context
Depends on:
 - [x] https://github.com/eclipse/che/issues/17634

**Comment by tolusha** [comment]
- create configmap `ca-certs` automatically / select configmap by labels (decided by us)? 
- remove the name from the configuration `operator.yaml`

**Comment by sleshchenko** [comment]
If it's about https://github.com/che-dockerfiles/che-tls-secret-creator/blob/master/entrypoint.sh#L141 please keep us updated since we're close to using that in devworkspace controller. And yeah, at this point we don't depend on CA secret but we would need to adapt our code

**Comment by tolusha** [comment]
I strongly against changing the default behavior. 
It might cause a lot of issues in cases where there is a dependency on `self-signed-certificate` secret.

so, resolution is WON'T FIX
