### ISSUE TITLE
Go stack has next version of editor in stable version of Che

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17824]
### Describe the bug
In Che plugin registry, Go lang stack has editor hardcoded to `next` version. In other words, if a user installs stable Eclipse Che release, the user gets `next` version of the editor (Che Theia) instead of released one.
Also it would be nice to check other plugins for such issue.

### Che version
latest (7.18.1)

### Steps to reproduce

1. Install Eclispe Che 7.18.1
2. Create a workspace from Go stack
3. Check editor version

### Expected behavior
It should be `latest` or `7.18.1` instead of `next`

### Runtime
Checked on Openshift, but doesn't really matter.

### Installation method
chectl, operator installer

### Eclipse Che Logs
N/A

### Additional context
Seems like editor version is hardcoded in devfiole or plugin yaml.

**Comment by gattytto** [comment]
I don't see the word "next" in either the go extensions (both versions) meta.yaml within plugin-registry nor in the devfile from the devfile-registry, but is reproduceable.
![image](https://user-images.githubusercontent.com/407397/92763753-3afd8e80-f36a-11ea-863b-fc29b9859866.png)

**Comment by ericwill** [comment]
Isn't this fixed already? https://github.com/eclipse/che-devfile-registry/commit/fed807e2569d0c2c7d71cafdf7e4b64daf835cb9
