### ISSUE TITLE
Migrate che-operator to the newer operator-sdk.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#17828]
### Is your enhancement related to a problem? Please describe.
Currently we are using very old one 0.10.0. It is very old version. We have a both: go modules and dep tool, but we want to save and support only go-modules. For development we bounded to the $GOPATH (old operator sdk debugger mode doesn't work with other location). 

### Describe the solution you'd like
It would be nice to migrate che-operator to the newer operator-sdk. It's not trivial task, because project layout for new operator sdk was very changed, but become mature. And currently we have some CRD limitations, because we still support openshift 3.

**Comment by tolusha** [comment]
I believe CRD limitation we can bypass by updating it by bash script

**Comment by tomgeorge** [comment]
https://github.com/eclipse/che/issues/18133 also depends on this.  I can't import any of the image puller operator types into che-operator without downgrading the image puller operator to a very old version of `operator-sdk` and kubernetes APIs

**Comment by ibuziuk** [comment]
@tomgeorge are you going to start working on this since this looks like a pre-requirement for https://github.com/eclipse/che/issues/18133 ?

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse/che-operator/pull/515
Migrated to operator-sdk 0.15.2 version
