### ISSUE TITLE
Java `http.nonProxyHosts` system variable contains incorrect wildcard domains

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17831]
### Describe the bug
`spec.server.nonProxyHosts` field is used to configure non proxy domains. But when it is converted to java system variable to be propagated to che-server it should contains `*` for wildcard domains [1].

[1] https://docs.oracle.com/javase/9/docs/api/java/net/doc-files/net-properties.html

### Che version

 - [x] latest

### Additional context
Check if the same modification is required for identity provider.

**Comment by RickJWagner** [comment]
Historical note:  A similar issue was noted on [1][2], it was handled in documentation at [3].  (But the doc wasn't carried forward from 1.2 to 2.x, unfortunately.)

[1] https://issues.redhat.com/browse/RHDEVDOCS-1104
[2] https://issues.redhat.com/browse/CRW-300
[3] https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.2/html-single/administration_guide/index  // section 2.5

**Comment by mmorhun** [comment]
Fixed

**Comment by RickJWagner** [comment]
Thanks for the work on https://github.com/eclipse/che-operator/pull/440.

This one seems like it should include some doc work, to ensure the docs show the preferred form.  (*.some.domain vs .some.domain).  Is there a docs change associated also?

**Comment by tolusha** [comment]
@RickJWagner 
It isn't covered by the doc, but I created the PR to reflect changes in CRD file [1]

[1] https://github.com/eclipse/che-operator/pull/476

**Comment by RickJWagner** [comment]
Super, thank you @tolusha.
