### ISSUE TITLE
[docs] Section "Overriding container entrypoints" in the devfile reference section does not make sense.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17836]
### Describe the bug
The section [Overriding container entrypoints](https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_overriding_container_entrypoints) in the devfile reference does not make sense:

> As with the understood by Kubernetes).
>
> There can be more containers in the list (contained in Pods or Pod templates of deployments). To select which containers to apply the entrypoint changes to.
>
>The entrypoints can be defined as follows:

### Che version
 - [x] nightly

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2544
