### ISSUE TITLE
Fix potential unhandled exceptions in che-dashboard.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#17833]
### Describe the bug

This is a potential bug.

There are some `Promise.then` with 2 arguments in code of `che-dashboard`.
This type of `then` can't handle exceptions caused in the first argument.

For example, this code will cause "unhandled exception".

```
promise
  .then((value) => {
    throw new Error("causes unhandled exception");
  },
  (err) => { /* error handling */ });
```

It should be

```
// Plan A
promise
  .then((value) => {
    throw new Error("causes unhandled exception");
  },
  (err) => { / * error handling */ })
  .catch((err) => { /* another error handling */ });  // <--- added.
```

 or

```
// Plan B
promise
  .then((value) => {
    throw new Error("causes unhandled exception");
  })
  .catch((err) => { /* error handling */); // <--- splitted.
```

This fix will reduce bugs like #17779, #17822 .

**Comment by akurinnoy** [comment]
@monaka is this issue to revise the dashboard codebase in order to add `catch` to each promise chain?

**Comment by monaka** [comment]
@akurinnoy Basically, yes. In almost all cases, the possibility of the unhandled exception is not good sign.
But I've not inspected deeper yet. It should be fixed with care because some may cause unexpected side effects.

**Comment by monaka** [comment]
Recently Che-dashboard was renewal. So this may be resolved.
I'll check code in this weekend.

**Comment by monaka** [comment]
I inspected code in che-dashboard. I couldn't find any issues pointed by here.
So I close this as obsolete.
