### ISSUE TITLE
Figure out versioning/release info for devworkspace controller and WTO

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17835]
### Is your task related to a problem? Please describe.
We should decide on a branch/tag structure for devworkspace-operator/web-terminal-operator releases. Currently, we have the [`v1.0.0-alphax` branch](https://github.com/devfile/devworkspace-operator/tree/v1.0.0-alphax) of devworkspace-operator, and the [`v1.0.x` branch](https://github.com/redhat-developer/web-terminal-operator/tree/v1.0.x) of web-terminal-operator. However, these versions aren't reflected in files within the repo:
- version.go in devworkspace operator is v0.0.1 for both master and the v1.0.0-alphax branches
- the web-terminal-operator lists version [`1.0.0`](https://github.com/redhat-developer/web-terminal-operator/blob/ae46a81427b6c492b62b6257512d58ad81cbc07c/manifests/web-terminal.clusterserviceversion.yaml#L363) in both the master and v1.0.x branches. 

Additionally, both 'release' branches are v*.*.x, and there are no tags in either repo to signify which commit in the branch is the `v1.0.0-alpha1` or `v1.0.0` release.

### Describe the solution you'd like
- Create tags at current `v1.0.*` branch HEADs to tag releases
- Include updated version info with repo files for both repos

### Additional info
Version numbers for the currently released and next version are consumed to generate automatic backlogs from multiple sources. The version numbers for WTO should match releases in the Jira backlog.

**Comment by amisevsk** [comment]
cc: @benoitf

**Comment by sleshchenko** [comment]
Good catch!

**Comment by sleshchenko** [comment]
I think the tags are not created the mainly due fact that we still changing some code.
About version.go in the X branches and in master - they should be aligned for sure.

**Comment by sleshchenko** [comment]
devworkspace operator has v1.0.0-aplha1 tag and 1.0.0-next in version.go. Is it going to help to automated tools or we need like v1.0.0-alpha2-snapshot in version.go?

**Comment by benoitf** [comment]
it might not be enough from .go files.

Note that some che repos have a `VERSION` file where the current version is defined and this file is used by the job that do the release. (so it can be triggered easily)

example https://github.com/eclipse/che-machine-exec/blob/master/VERSION

**Comment by sleshchenko** [comment]
In addition it makes sense to put versions into https://github.com/redhat-developer/web-terminal-tooling (no version) and https://github.com/redhat-developer/web-terminal-exec/tree/v1.0.x ([7.17.0-SNAPSHOT
](https://github.com/redhat-developer/web-terminal-exec/blob/v1.0.x/VERSION) version from upstream)

**Comment by sleshchenko** [comment]
I believe now it's resolved
