### ISSUE TITLE
support local Dockerfile to allow trivial setup 

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#17846]
gitpod and codespaces has both their unique setup but they both allow use of a in-repo dockerfile to setup build environment. This makes for not only full and reproducible development environment but also lets the config follow the repository and even allow easy customization within branches/tags.

But besides that it has the nice sideffect you can share the dev setup between all these 3 web based ide's.

codespaces defaults to look for .devcontainer/Dockerfile
gitpod lets you have a .gitpod.yml that you then point to .devcontainer/Dockerfile

could che allow for similar ? (this makes it necessary to have the git repository cloned or at least introspected first but that would solve lots of other issues) 

Example of repo that has shared config for both gitpod and codespaces is https://github.com/jbangdev/jbang-examples - I would love to be able to add che into this repository without having to maintain another (external) container setup.

could devfile.yml at least allow referring to a local dockerfile and not just external images/containers ? 

note: the sharing of config is just a nice sideeffect of this; the main thing is that working with gitpod and codespaces you as a user and team can do changes and updates self-service rather than having an external image configured for you.

**Comment by davidstrauss** [comment]
/remove-lifecycle stale

I'm definitely still interested in seeing this support land.
