### ISSUE TITLE
Add PWA (Progressive Web Application) support

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#17844]
### Is your enhancement related to a problem? Please describe.

Some browers hook some keybinds (like Ctrl-N) before handling by Che.

### Describe the solution you'd like

Adding content for PWA and making it as an application.

### Describe alternatives you've considered

Publishing webview application for clients.

### Additional context

PizzaFactory (Che fork) has already started the basic PWA support.
Cache and offline support are WIP.
I'll contribute later (may be within this Christmas holiday).

![Screenshot 2020-08-23 at 13 42 59](https://user-images.githubusercontent.com/101795/92981842-98aee980-f4d6-11ea-9c18-9e0ab9bce99e.png)

**Comment by azatsarynnyy** [comment]
Hello @monaka 
it would be cool to see such a contribution.
Do you plan to work on PWA for both clients: Dashboard and Che Theia?
If for both, will it require some work in upstream Theia or in Che Theia only?

**Comment by monaka** [comment]
Currently the code is in Dashboard. (And is copied into the che-server image). https://github.com/PizzaFactory/che-dashboard/tree/937317a/wpa-resources
The status is "experimental". I'm not sure if this approach is best.

**Comment by monaka** [comment]
@gorkem Currently, the implementation has been postponed.
I agree the caching for Theia is challenging.
And I suppose that just even adding `mainfest.json` and icons will improve the user experience.

**Comment by sleshchenko** [comment]
Droppped dashboard part since I believe it's already done with https://github.com/eclipse-che/che-dashboard/pull/323
