### ISSUE TITLE
Automatically handle users with a name that is not compatible with k8s namespace name

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17841]
### Is your task related to a problem? Please describe.
We would like to automatically handle usecase when users have a name that is not compatible with k8s namespace name
and che server is going to create namespace according to the patter <username> - che.

### Describe the solution you'd like
1. Introduce a configuration variable that is set by default 'true' and explicitly telling that che server is allowed namespace creation.
   The negative value is will be handled in separate issues and it is about use case when the che admin is responsible for pre-creating namespaces for users.
2. If during the process of workspace startup che server wants to create a k8s namespace we detected that name contains invalid characters or it is longer when needed we needed.
    -  remove all invalid characters 
    -  shrink name to 56 symbols
    -  add suffix - '-<6 random characters-or-digits>'
    - record this name to user preferences for later use.

### Describe alternatives you've considered
 admin is responsible for pre-creating namespaces for users.
### Additional context

https://github.com/eclipse/che/issues/15323

**Comment by mshaposhnik** [comment]
Merged in #17892
