### ISSUE TITLE
[devworkspace] Investigate the authentication/authorization mechanism compatible with Che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17856]
### Is your enhancement related to a problem? Please describe.
It's needed to investigate the authentication/authorization mechanism compatible with Che.
Currently, we have openshift-oauth but it has drawbacks:
- it does not do needed autorization (access for the specific user, creator);
- it's able to serve only one port, so each devworkspace would require 3+ openshift-oauth containers;
- authentication should be done(user should logging, no really SSO) separately for each devworkspace and even devworkspace server if we talk about cookies powered authentication;
- it's not compatible with Kubernetes clusters.

We need to investigate the authentication/authorization we would be able to use for devworkspaces and it should be compatible with Kubernetes/OpenShift and we also should keep in mind integration with optional Che.

**Comment by amisevsk** [comment]
Unless openshift-oauth-proxy gains support for proxying multiple ports, it's a no-go for our uses. Many links aren't navigated to explicitly, so the login prompt is never seen by the user; you would have to manually open each endpoint and log in to set a cookie before your browser could access it (IIRC).

**Comment by sleshchenko** [comment]
So, the investigation is not fully completed yet but here what we have at this point. Here can be found the existing Che authentication workflow as well as the investigated ones https://github.com/sleshchenko/devworkspace-operator/tree/authentication-schemas/authentication-schemas
A short description of investigated flows:
- if we try to keep jwtproxy workflow - it seems to be possible but then we **will lose creator only access** since JWT token should be stored somewhere near devworkspace CR, like in secret and then everybody who is able to read that secret is able to access workspace via Http endpoint after a few manipulation with requests. I'm not sure if it's a requirement but seems to be nice to have;
- using oauth/openid workflow directly on devworkspaces does not seems to be possible on Kubernetes cluster, since there is no embedded oauth flow as OpenShift has which allows registering oauth client per devworkspace instance, and reusing the same does not seem to be secure enough; apart from that, it does not provide SSO experience where user logs in once and all other workspaces authentication does not require manual logging.

Further steps: I have a feeling that we should be able to build a bit custom oauth workflow with SSO experience since authentication is done on one endpoint and token in propagated into devworkspaces after additional authorization is done (we guarantee that only creator's token is sent to workspace otherwise devworkspace authentication should fail). After we make sure that workflow does not have any security issues we can investigate if there is out-of-the box solutions we could reuse - like Dex.

**Comment by sleshchenko** [comment]
The investigation is done and here is the proposal https://github.com/sleshchenko/devworkspace-operator/tree/authentication-schemas/auth-proposal which is going to be discussed and agreed on
