### ISSUE TITLE
[devworkspace] Support TLS routing on kubernetes

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17853]
### Is your enhancement related to a problem? Please describe.
TLS became a requirement for Che Theia. So, it's needed to implement TLS routing on the kubernetes.
The kubernetes support is divided from OpenShift, because on the OpenShift there is an out-of-the-box solution where it's really easy to enable TLS by Route configuration.

### Describe the solution you'd like
The plugins are listening localhost only, and some proxy is needed but at this point it's going to be a separate issue.
So, I see that we can implement something like `basic-tls` or even `basic-tls-k8s` routing that is going to:
1. Have an ability to use the configured TLS secret.
2. Have an ability to generate TLS secret by its own if it's not configured: Che already has needed solution within Che Operator https://github.com/eclipse/che-operator/blob/master/pkg/deploy/tls.go#L277.
3. Using secret means propagating TLS certificates in the namespaces where workspaces live and configure workspace-related ingresses to use them.
* Should we use one secret per namespace or per workspace? Per namespace seems better in terms of duplication but then it's not really clear how we can clean them up after workspaces are removed.

### Describe alternatives you've considered
Let me know if there is a better alternative.

**Comment by sleshchenko** [comment]
Probably it makes sense to implement https://github.com/eclipse/che/issues/17855 first and then reuse that code in the TLS routing

**Comment by metlos** [comment]
I believe this is superseded by https://github.com/eclipse/che/issues/19394.
