### ISSUE TITLE
Exposing the eclipse-che container to the kubernetes cluster's public ip

### ISSUE THREAD

**Issue by daronhudson** [eclipse-che/che#17850]
Well to start off, I've been messing with setting up eclipse-che in every way it's available and i've been trying to mess around with kubernetes and the features available for the automatic install and I've managed to get it running on my lan but haven't been successful with external.
I've tried exposing the kubernetes cluster itself, but that hasn't worked. I've tried running it manually through helm, also hasn't worked.
I've managed to run it on windows and linux (windows 10 pro, datacenter 2019 and centos 7/8) but haven't come up with a solution as to exposing the container to the outside world which I do need as I'm running it on a remote hypervisor. I've been running it using chectl, helm and docker desktop on windows and openshift on linux.

I have absolutely no idea where to go from here and any help would be phenomenal since I'm fairly new to this area of containers and network management. My last resort is just passing it through a VPN agent, but I'd definitely rather not have to do that everywhere I go.

Thank you to anyone that even reads this!

**Comment by tomgeorge** [comment]
Hi @daronhudson 

If I understand correctly, you want to be able to reach the eclipse che page from outside of the cluster.  In general [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) is the mechanism for getting traffic from outside of the cluster into the cluster.  Kubernetes `Ingress` objects map hostnames, ports, and request paths to a Service.

How to go about enabling ingress on a cluster on where it is installed.  Cloud providers will give you access to their load balancers, minikube has an ingress add-on, etc.  Eclipse che docs has a section about installing che on kind using the [NGINX ingress controller](https://kubernetes.github.io/ingress-nginx/deploy/)  and [MetalLB](https://metallb.universe.tf/) [here](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-kind/).

If you give more information about the cluster you are using (minikube? kind? self-installed?) we should be able to help you more.

**Comment by daronhudson** [comment]
I ended up using a full blown openshift installation and got it up and running. But now the problem I'm facing is a certificate issue. No matter how I import the certificate or which store I import it into I can't seem to get it to be trusted.

Would you happen to know a way to use a real ssl certificate with the openshift operator installation of che? I've tried messing around with it but whenever I try to use my certificate for it, the page just doesn't load anymore.

**Comment by daronhudson** [comment]
This is what happens in the chrome console:
[https://i.imgur.com/mq5He8h.png](url)

**Comment by tolusha** [comment]
When Eclipse Che is deployed it creates a `self-signed-certificate` secret. Could you check if it exists?

> Would you happen to know a way to use a real ssl certificate with the openshift operator installation of che?

In this case you have to reconfigure OpenShift Ingress to use a real certificate:
https://docs.openshift.com/container-platform/4.5/security/certificates/replacing-default-ingress-certificate.html

**Comment by daronhudson** [comment]
Yes it does have the self signed certificate in the secret sections. So by replacing the openshift ingress certificate, the one that eclipse tries to use is gonna be the valid one that the controller has since it's the one that makes it?

**Comment by tolusha** [comment]
Could you compare certificates into secret with ones obtained by the command:
`openssl s_client -connect plugin-registry-eclipse-che.<DOMAIN>:443   -showcerts`

**Comment by daronhudson** [comment]
Yeah they’re the same, what I did was just copy whatever was in the secret into a certificate file then imported it to the system. I’m trying to find a way to replace the ingress certificate with my own without using oc as I have a problem with it on my installation that I haven’t figured out yet. Would you know of a way to do it without using oc? Or maybe doing it manually through the console?

**Comment by tolusha** [comment]
Here is the doc
https://docs.openshift.com/container-platform/4.5/security/certificates/replacing-default-ingress-certificate.html

**Comment by daronhudson** [comment]
I'll give it a try and report back/close the issue if I end up resolving it

**Comment by daronhudson** [comment]
@tolusha  

So I replaced the ingress certificate and the cluster ca certificate and now end up getting this when trying to initialize the postgre pod

![image](https://user-images.githubusercontent.com/26112933/93657817-a3500e00-fa03-11ea-9a64-a30358542261.png)

It has no logs or anything it just keeps doing that in events

**Comment by tolusha** [comment]
@daronhudson 
I don't think that is it related to the certificate.  I recommend to remove PVC (operator will recreate it) or try to reinstall Eclipse Che in a clean namespace
