### ISSUE TITLE
Adapt Che Theia to the latest @eclipse-che/api npm package

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17860]
### Is your task related to a problem? Please describe.
The latest version of [`@eclipse-che/api`](https://www.npmjs.com/package/@eclipse-che/api) npm package (7.18.2) brings the breaking changes for Che Theia.

See the build output [here](https://ci.centos.org/job/devtools-che-theia-pullrequests-build/716/consoleFull).

### Describe the solution you'd like
Need to adapt Che Theia to the latest version of `@eclipse-che/api`.

### Describe alternatives you've considered
We've pinned Che Theia to the previous version (7.5.0-SNAPSHOT) of `@eclipse-che/api` in the PR https://github.com/eclipse/che-theia/pull/858

**Comment by benoitf** [comment]
7.18.2 is totally broken

```
$ npm i @eclipse-che/api                                                                                                                                                                                            
+ @eclipse-che/api@7.18.2
added 1 package and audited 1 package in 5.41s
found 0 vulnerabilities

$ more node_modules/@eclipse-che/api/index.d.ts                                                                                                                                                                     [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) on project dts-dto-typescript: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by azatsarynnyy** [comment]
Closing it as the new version has been published, see https://github.com/eclipse/che/issues/17861#issuecomment-692170084
