### ISSUE TITLE
Stopping a RUNNING workspace when a new workspace is being created

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#17863]
## Summary
When I create a new workspace in eclipse che, if there is already another workspace running, I get a message saying 'Only one workspace can be started at a time'.  

Is there  way i can hook into the workspace loading action and stop the currently running workspace, so that this new workspace i am creating is not blocked? 

I have a python code, which makes use of the che API, to stop the workspace of any user (using admin credentials).  I am looking at the best place where this should be called.

**Comment by sparkoo** [comment]
It's not clear to me, what do you want to achieve. Looks like you have API call to stop the workspace, so what are you missing? Btw you can increase count of allowed workspaces running.

Can you please better describe your use-case ?

**Comment by pgirishibm** [comment]
Hi @sparkoo  In our che setup, users are able to create multiple che workspaces. Also by default, che allows to have just one workspace RUNNING. I do not want to change that.  

Now, when a user has one workspace running and then tries to start a second one, the user gets a message "You are not allowed to start more workspaces".   I was looking for a way to bypass this message and instead programmatically stop the already RUNNING workspace and allow this workspace to start up. 

The python code which i mentioned in my earlier post is a standalone code which allows to stop a workspace of any user.  Now is there a way to  integrate that code into che so that it executes when a user tries to start a workspace, so that any already running workspace can be stopped.

**Comment by sparkoo** [comment]
@pgirishibm I see. I don't think it's currently possible to do from the dashboard and che-server directly does not support this either. Setting it as P2 enhancement, feel free to contribute.
