### ISSUE TITLE
[che-theia] Cannot read property 'recent' of null

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#17862]
### Describe the bug

I got logs like this on start-up phase.

```
Uncaught (in promise) TypeError: Cannot read property 'recent' of null
```

```
Uncaught (in promise) TypeError: Cannot read property 'current' of null
````

I suppose this is not occurred in the code of the vanilla Theia. 
As StorageService is overridden by `@eclipse-che/theia-user-preferences-synchronizer`.

### Che version

`Che-Theia@37a957d using Theia@1e09b8165` on che.openshift.io .

### Steps to reproduce

1. Open your workspace.
2. Open DevTool window.
3. Watch console logs.

### Expected behavior

No unhandled exception shown.

### Screenshots

![image](https://user-images.githubusercontent.com/101795/93169440-10dc1000-f760-11ea-9118-b202219fbe87.png)

**Comment by monaka** [comment]
I found the same issue on my PizzaFactory build (from almost same code with the master branch).
So this will be happened on the master branch also.

**Comment by monaka** [comment]
It looks this log is also the same root cause.

```
Could not start contribution TypeError: Cannot read property 'breakpointsEnabled' of null
```

**Comment by monaka** [comment]
I'm inspecting related code.

In `extensions/eclipse-che-theia-user-preferences`, `undefined` will be returned if the target preference file is not available.

https://github.com/eclipse/che-theia/blob/503ca56a3c1a7e7c9ccab1f975b49e8ecd0ea993/extensions/eclipse-che-theia-user-preferences/src/node/che-storage-server.ts#L36

The message will be transferred via JSON RPC. 

https://github.com/eclipse/che-theia/blob/503ca56a3c1a7e7c9ccab1f975b49e8ecd0ea993/extensions/eclipse-che-theia-user-preferences/src/node/che-theia-user-preferences-backend-module.ts#L33-L37

And JSON can't handle `undefined`, AFAIK.

For now, I have no idea why JSON parser/stringifyer doesn't cause any exception in the server side.
But does it give any hints to fix this issue ?

**Comment by ibuziuk** [comment]
@monaka could you please clarify if the issue still relevant with the latest version of Eclipse Che?

**Comment by monaka** [comment]
@ibuziuk thank you for the heads up.

I rechecked a minute ago. I couldn't reproduce it. Instead,
I got the another message instead. But it should be reported in the another issue.
I close this.
