### ISSUE TITLE
@eclipse-che/api:7.18.2 npm package is corrupted

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17861]
### Describe the bug
The recently published version of `@eclipse-che/api` npm package - `7.18.2` contains wrong `index.d.ts` with the following content:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) on project dts-dto-typescript: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### Expected behavior
Normally, it should contain the TypeScript definitions of Che API DTOs.

**Comment by azatsarynnyy** [comment]
The new version 7.18.1 was published https://www.npmjs.com/package/@eclipse-che/api/v/7.18.1 with the latest tag updated.
It contains a correct `index.d.ts`. Thanks @benoitf!

**Comment by azatsarynnyy** [comment]
Also, should be fixed by adding an additional check in https://github.com/eclipse/che/pull/17865

**Comment by benoitf** [comment]
it's still odd as with -e/-u flag, maven command exit with error code so it can't continue
