### ISSUE TITLE
Tree of 'changes to be performed' in the refactoring 'Rename' window does not work correctly

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1786]
After removal of the flag from the parent element the flags from descendants didn't deleted

**Comment by bmicklea** [comment]
@svor was this issue merged into 4.6?  If it was it should have the milestone set to 4.6.0, if not that's fine, but let me know.

**Comment by svor** [comment]
@bmicklea This issue was merged into 4.6. I've changed the milestone.
