### ISSUE TITLE
Migrate che-machine-exec tasks to the github actions

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#17875]
### Is your task related to a problem? Please describe.
Centos Ci is deprecated, so we need migrate che-machine-exec tasks to the github actions.

**Comment by flacatus** [comment]
I've migrated docker nightly build with multi-platform arch. Release process was not migrated, is part of another issue of productization team(https://github.com/eclipse/che/issues/17857)

**Comment by AndrienkoAleksandr** [comment]
@ibuziuk @flacatus Sorry Do we have release job https://github.com/eclipse/che-machine-exec/blob/master/make-release.sh which should be migrated too?
