### ISSUE TITLE
Remove workspace id from websocket connection path to master

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1787]
Workspace statuses are now tracked by various websocket connections per workspace id. It creates a lot of problems in order to handle the high number of websockets. (especially in dashboard)
Providing one connection with various channels will decrease the number of persistent websocket connections. Thus the clients will be able to use one connection to listen statuses of all workspaces, instead on multiple ones.

**Comment by TylerJewell** [comment]
@vparfonov - is there a PR for this?  Why add to 4.6 milestone if PR is not readied.
