### ISSUE TITLE
Investigate why openshift oauth fails for some time after switching between multi-host and single-host

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#17886]
### Is your task related to a problem? Please describe.
When switching between multi-host and single-host server exposure strategy (in either direction) with OpenShift oauth switched on, the authentication stops working after the change with the following output from `oauth-openshift....`:

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"i-M7Bzw4vSMkTPhGvNfchqQ4jQaIkFaM1mi-YsjNLR0.09j6zg3lqCA.che-public"}
```

The communication between the browser and the server that shows the symptom: [communication.har.zip](https://github.com/eclipse/che/files/5232525/communication.har.zip) (unzip and load the har file in the network tab of web tools in firefox - not sure if this is supported in chrome, but that shouldn't matter - this just shows the recorded communication between browser and the server).

### Describe the solution you'd like
This might be inevitable due to the change in the location of keycloak and actually this condition disappears after some (yet unidentified) amount of time, but we should investigate how to mitigate this (by some kind of oauth client reset or something).

**Comment by metlos** [comment]
This is indeed caused by keycloak changing the location which is not known to the oauth-client. So the procedure to re-enable the login is following:

```
oc get oauthclient | grep eclipse-che-openshift-identity-provider
```

notice the (randomized) name of the eclipse che oauth client.

```
oc edit oauthclient <name-of-the-client>
```

and add the keycloak URL for the current server exposure type.

For multi-host, the URL is of the form:
```
http://keycloak-<che-namespace>.apps.<cluster-domain>/auth/realms/che/broker/openshift-v4/endpoint
```
For single-host, it is:
```
http://che-<che-namespace>.apps.<cluster-domain>/auth/realms/che/broker/openshift-v4/endpoint
```

Once the oauth client is updated with the corresponding URL, the login works again.

The thing I am not sure about is whether this can be done by the operator, keycloak or if this requires manual intervention by the cluster administrator.

**Comment by ibuziuk** [comment]
@metlos tried to use the workaround for our OSD v4 dogfooding instance and enable the single-host by default there, but it looks like the dedicated admin has no permissions to manipulate with the `oauthclient` 

```
Error from server (Forbidden): oauthclients.oauth.openshift.io is forbidden: User "ibuziuk" cannot list resource "oauthclients" in API group "oauth.openshift.io" at the cluster scope
```

So, looks like it will work only for cluster-admin

**Comment by metlos** [comment]
@ibuziuk - the che operator is creating the oauth client - so maybe just a delete and re-create would work for non-admins?

**Comment by ibuziuk** [comment]
@metlos you mean delete and recreate the whole Che instance?
