### ISSUE TITLE
Language Server Protocol: Implement document formatting

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1788]
Language server protocol supports several types of formatting https://github.com/Microsoft/vscode-languageserver-protocol#document-formatting
We need to support hem all

**Comment by evidolob** [comment]
Document range formatting demo:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/929743/17170047/17679fda-53f3-11e6-8531-df2f6b3bd02c.gif)

Document on type formatting demo ( for C# trigger character is '}')
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/929743/17170055/1b3f63f4-53f3-11e6-83d6-ce44cdfab896.gif)
