### ISSUE TITLE
[devworkspace] add an ability to configure trust store e.g. for plugin registry with self-signed certs

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17898]
### Is your task related to a problem? Please describe.
Add an ability to configure the trust store e.g. for plugin registry with self-signed certs.

### Describe the solution you'd like
It's possible to configure CA certs for plugin brokering at least.
Later we may need to propagate self-signed CAs to devworkspaces but I would like to separate it.

**Comment by benoitf** [comment]
also I could live with an insecure flag as well

**Comment by sleshchenko** [comment]
The agreement we got during planning - the configuring CA could differ depending on the future plan regards plugin registry deployment, should it be a part of devworkspace controller or not.
At this point, it does not have a big priority (configuring and propagated CA), but we're going to introduce configuration flag to enable insecure connections to the configured plugin registry.

**Comment by l0rd** [comment]
After discussion at this week dw cabal we agreed that this should not be included in milestone 3
