### ISSUE TITLE
[new UD]  Rework workspace details components

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#17899]
### Is your enhancement related to a problem? Please describe.

We need to rework workspace details component and split it into smaller functional and logical part. 

### Describe the solution you'd like

The workspace details component should include
- [breadcrumbs component](https://www.patternfly.org/v4/documentation/react/components/breadcrumb) and workspace status component
- component that handles tabs switching and errors indicating
- dedicated component for each tab content
- buttons to save, apply, cancel changes

If it's possible, wrap each component with a [container component](https://reactpatterns.com/#container-component) that should be responsible for fetching the workspace data.

**Comment by sleshchenko** [comment]
Should be implemented in https://github.com/che-incubator/che-dashboard-next/pull/68
