### ISSUE TITLE
Add support for devfile `kubernetes` and `openshift` components

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17894]
### Is your enhancement related to a problem? Please describe.

Che currently ignores kubernetes and openshift components. These were previously supported by the che-server workspaces engine.

### Describe the solution you'd like

- Do not re-implement a che-server like behavior (i.e. extract the container of a pod/deployment and add it to the workspace pod): in the new implementation, an inner loop `kubernetes` or `openshift` component, would be applied without any modification.
- This issue is not about the outer loop `kubernetes` and `openshift` components (there is a specific [issue](https://github.com/eclipse/che/issues/21186) for that)
- Block privileges escalations scenarios (i.e. if the user doesn’t have the privileges to create a pod in a given namespace, this feature should not allow him to do it)

### Release Notes Text

Eclipse Che now supports devfile components of type `kubernetes` and `openshift`. That allow to reference Kubernetes and OpenShift manifests in a devfile and include them as part of the workspace. Devfile components of type `volume` and `container` were already supported, components of type `image` are not supported yet.

**Comment by Bolodya1997** [comment]
Is there any plan for implementing this feature?
In out project we want to create k8s Secret component with automount credentials annotation to add git credentials from the private Git repositories other than the devfile location.

**Comment by l0rd** [comment]
This has been addressed by https://github.com/devfile/devworkspace-operator/pull/961
