### ISSUE TITLE
Crashes Che-Theia on 'che.openshift.io because of authentication issues.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#17890]
### Describe the bug

I suppose this error is caused by the exception logged below.

```
Refused to frame 'https://sso.redhat.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.openshift.io".
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify (7.18.2)

### Steps to reproduce

1. Start workspace
2. Open DevTools (may not required)
3. Just waiting for a few minutes.

### Expected behavior

No exceptions.

### Runtime
   - [x] Openshift (include output of `oc version`) che.openshift.io

### Screenshots

![Screenshot 2020-09-17 at 09 55 49](https://user-images.githubusercontent.com/101795/93407137-5d445e80-f8cc-11ea-9bea-43a11c9a1671.png)

### Installation method
   - [x] I don't know

### Environment
   - [x] my computer
       - [x] ChromeOS Version 85.0.4183.108 (Official Build) (64-bit)

### Eclipse Che Logs

I can't do it as the environment is SaaS.

### Additional context

I've not got this issue on PizzaFactory/Camino instances that Keycloak is used for auth.
I suspect this issue is related on #17470

**Comment by gorkem** [comment]
I have also seen this one briefly today. @ibuziuk

**Comment by azatsarynnyy** [comment]
Hi,
it's a known issue - SSO related https://github.com/eclipse/che/issues/17472
I'm closing this one as a duplicate.
