### ISSUE TITLE
[docs] Search results contain advertisement

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17895]
### Describe the bug
As of now Che [docs web site](https://www.eclipse.org/che/docs) uses Google under the hood for the search in the docs. However the price is annoying ads in the search result.
We shouldn't relay on third parties and use the search provided by the framework the docs site build on.

### Steps to reproduce

1. Open [Che docs web site](https://www.eclipse.org/che/docs) 
2. Search something
3. See commertials

### Expected behavior
As Eclispe Che is free and open source project it should not contain any advertisement.

### Screenshots
![docs-search](https://user-images.githubusercontent.com/15607393/93454341-87ede180-f8e3-11ea-8f8a-51f2969318ac.png)

**Comment by themr0c** [comment]
Antora doesn't have an out of the box solution for the search. People have implemented search with additional tools like Algolia and Lunr. We should investigate the possible solutions and use what best suits our needs.

See:

* https://gitlab.com/antora/antora-ui-default/-/issues/44
* https://gitlab.com/antora/antora-ui-default/-/issues/68
* https://github.com/Mogztter/antora-site-generator-lunr

**Comment by themr0c** [comment]
This issue is also tracked there: https://issues.redhat.com/browse/RHDEVDOCS-2269

**Comment by mmorhun** [comment]
The issue is still actual and pretty annoying.

**Comment by themr0c** [comment]
Since then we have switched to an internal search engine using lunr. It fixed this issue.
