### ISSUE TITLE
Build a catalog source image only if there is a new nightly bundle image

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17907]
### Is your enhancement related to a problem? Please describe.
For the time being we continuously build catalog source image it leads to the error when there is no a  new nightly bundle image
https://github.com/eclipse/che-operator/runs/1130900636?check_suite_focus=true

### Describe the solution you'd like
Build a catalog source image only if there is a new nightly bundle image

**Comment by flacatus** [comment]
done!
