### ISSUE TITLE
[che-theia] VSCode's TreeView.reveal() function does nothing in Theia (same function works in regular VSCode)

### ISSUE THREAD

**Issue by rajeshkumarboda** [eclipse-che/che#17906]
TreeView.reveal() function can be used to expand a tree view node automatically and set focus. But this function is not doing anything in che-theia whereas it works fine in vscode.

Below is the scenario
All nodes will be in collapsed state initially. Then, I want to select a particular child node.  That particular child node should automatically expand and should get a focus
For eg: My custom VSCode tree looks like this: I want entire tree to be in collapsed state except childNode2
parentNode1
    childNode1
parentNode2
    childNode2

I am trying to run this function:
  treeView.reveal(item, {select: true, focus: true, expand: true});
Here Item is the childNode 2. 
getParent() method is implemented as per the documentation:
     
This function is doing nothing in che-theia

I saw a similar Bug reported in eclipse-thia. It seems it got fixed there. 
https://github.com/eclipse-theia/theia/issues/7815

**Comment by rajeshkumarboda** [comment]
Can this be moved to P1?

**Comment by benoitf** [comment]
Hi, it should be fixed as well in Che if it's fixed in upstream theia
