### ISSUE TITLE
e2e tests for Che-Theia fails sporadically.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#17905]
### Describe the bug

I'm using Azure Pipelines for testing Che-Theia.
And e2e tests are failed sporadically.

I tried on my local machine and it was reproduced.
I suspect this issue will depend on the spec of the test machine.

### Che version

 - [x] latest

### Steps to reproduce

Plan A.

1. Run test on Azure Pipelines. Example `azure-pipelines.yml` is [here](https://github.com/PizzaFactory/che-theia/blob/c9f9de14bccf9203f6ef6e5705c93743ead992d8/azure-pipelines.yml)

Plan B.

1. Run the container `docker run -p 3100:3100 --rm -it -e CHE_API_INTERNAL=http://localhost:3100/api -e CHE_WORKSPACE_ID=workspaceId -e CHE_WORKSPACE_TELEMETRY_BACKEND_PORT=4167       -e CHE_MACHINE_TOKEN=foobar quay.io/eclipse/che-theia:next`
2. Run e2e tests on the local machine (poor spec is better.).
 
### Expected behavior

No error reported from Cypress test suite.

### Runtime
   - [x] other: (please specify) Docker on Azure Pipelines

### Environment
   - [x] Cloud
       - [x] other (Docker on Ubuntu)

### Additional context

I'm going to refactor *.spec.ts files. I'll send PR soon.

**Comment by benoitf** [comment]
e2e tests have been removed (replaced by happy path tests)
