### ISSUE TITLE
getting net::ERR_ABORTED 404 (Not Found) while loading extension resource

### ISSUE THREAD

**Issue by nsharma1989** [eclipse-che/che#17903]
## Summary
- With version 7.16 while launching vscode extension I am getting 
`GET http://routeadacfi5q-debug.apps.debug.os.fyre.com/webview/theia-resource/file///tmp/vscode-unpacked/debugui.1.0.1.hzhghyoxvk.debugui-1.1.0.vsix/extension/dist/bundle.js net::ERR_ABORTED 404 (Not Found)`

the CSP inside the code is like 
```
<meta http-equiv="Content-Security-Policy"
      content="default-src 'self' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
      style-src 'self';
      img-src 'self' data:;
      connect-src * data: blob:"/>
```

I have tried with http as well it still gives a 404 error and a log 
`service Workers are not enabled. Webviews will not work properly`

**Comment by azatsarynnyy** [comment]
Hello @nsharma1989 
Che Theia WebView is working in a secure context only, e.g. localhost, https.
See the comment https://github.com/eclipse-theia/theia/pull/6465#issuecomment-557494879 for more details.

**Comment by nsharma1989** [comment]
@azatsarynnyy Thanks. Yes I noticed that too now. Closing the issue.
