### ISSUE TITLE
Validate links with linckecker for each che-docs PR

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#17909]
We rely on the user to validate links on PR.

We have a linkchecker configuration (`linkcheckerrc`).

Now that we have browseable build output thanks to Netlify, we would like to validate the links with linkchecker for each PR.

NB: In the devfile, we use the container provided by  https://github.com/linkchecker/linkchecker

cc: @benoitf

**Comment by sleshchenko** [comment]
A related issue on the dashboard/chectl side https://github.com/eclipse/che/issues/17739
