### ISSUE TITLE
Limit Keycloak's redirect url to certain urls

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17902]
### Is your task related to a problem? Please describe.
Keycloak redirect URL is too generic. We can improve security by limiting it.

### Describe the solution you'd like
Limit Keycloak's redirect url to certain URLs
 - https://{domain}/dashboard/
 -  https://{domain}/workspace-loader/
 -  https://{domain}/_app/loader.html

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by sleshchenko** [comment]
Can we also include localhost:XXXX to being able to start like dashboard locally? auth on openshift.io allows that.
cc @akurinnoy @olexii4

**Comment by skabashnyuk** [comment]
>Can we also include localhost:XXXX 

Should it be a separate configuration option that is disabled by default? I have some doubts that this is 100% safe. WDYT?

**Comment by sleshchenko** [comment]
I'm OK with option as well. I assume that it's safe because it's enabled on openshift.io )
@ibuziuk WDYT?

**Comment by tolusha** [comment]
@skabashnyuk 
Should the limitation works in both single and multi hosts modes?

**Comment by skabashnyuk** [comment]
@tolusha I think yes

**Comment by ibuziuk** [comment]
> I'm OK with option as well. I assume that it's safe because it's enabled on openshift.io )

@sleshchenko on Hosted Che we do not use operator based deployment, so not sure which configuration are you referring to  . Could you please clarify?

**Comment by sleshchenko** [comment]
@ibuziuk I'm asking about allowing `localhost:...` as a redirect URL for authentication. On upstream it's only `$CHE_HOST`

**Comment by sleshchenko** [comment]
I think we also need to allow `#$CHE_HOST/_app/oauth.html` https://github.com/eclipse/che/blob/master/assembly/assembly-root-war/src/main/webapp/_app/oauth.html
