### ISSUE TITLE
User Devfile UI

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17914]
### Is your task related to a problem? Please describe.
UI implementation of https://github.com/eclipse/che/issues/16875

### Describe the solution you'd like
see details in epic https://github.com/eclipse/che/issues/16875

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/16875

**Comment by sleshchenko** [comment]
Moving down to P2 since we don't have a concrete plan regards this.
