### ISSUE TITLE
chectl should keep my certificate when using minikube/minishift/crc

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17921]
### Describe the bug
When using a local platform like minikube or minishift, each time I install/uinstall che, there is a new file written into `$HOME/cheCA.crt`  and then I need to trust this certificate into my browser (or system in macos) but my minikube instance is still the same.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
```bash
$ minikube start
$ chectl server:start --platform=minikube
$ chectl server:delete
$ chectl server:start --platform=minikube
```

### Expected behavior
I shouldn't have to trust again certificates in my browser as I'm using the same minikube instance.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
N/A

### Installation method
   - x ] chectl

### Environment
   - [x] my computer
       - [x] macOS

**Comment by mmorhun** [comment]
In my opinion current behaviour is correct because if a user deletes Eclipse Che completely, everything Che related (CR, CRDs, secrets, configmaps and so on) goes away.

**Comment by benoitf** [comment]
UX is really bad 
I would say that I expect `uninstall`  and not `full delete` so certificates could be kept into my `.minikube` folder

> Moreover, keeping private keys on chectl side is a security issue.
minikube is storing private key in `$HOME/.minikube/key.pem`

**Comment by mmorhun** [comment]
> I would say that I expect uninstall and not full delete

Then a user might expect to have all the configuration saved as well (including CR and configmaps). I think the idea of the command was to uninstall Che, not just remove pods.

> certificates could be kept into my .minikube folder

1. Is it ok to store a namespace scoped objects of a Minikube profile in `.minikube`?
2. What to do in case of real cluster? Storing the private keys that way is no secure.
