### ISSUE TITLE
At Least Half a Line of Devfile Cut off in Editor

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#17935]
### Describe the bug
When you scroll all the way down in the devfile editor with a large devfile, some content is cut off at the bottom.

### Che version

 - [ ] latest
 - [x ] nightly
 - [ ] other: please specify

### Screenshots
![CutScroll](https://user-images.githubusercontent.com/13163770/93980265-b0ac2600-fd7e-11ea-9070-7d4fc3ce0aba.PNG)

### Environment
   - [ ] my computer
       - [x ] Windows
       - [ ] Linux
       - [ ] macOS

This is in Chromium

**Comment by l0rd** [comment]
cc @olexii4 @akurinnoy

**Comment by sleshchenko** [comment]
please check it with the new dashboard and reopen if it's still relevant.
