### ISSUE TITLE
chectl must detect issues with Che Operator image

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17937]
### Describe the bug
If Che Operator has any issues with start up - Che will never be started and user is told that postgres scheduling takes a lot of time.

P.S. I solved the issue for myself by updating chectl to the latest version but it's not about compatibility issue but about telling more precise error message.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start Che with Che Operator image that is not compatible with the current chectl version.

### Expected behavior
Chectl tells that che operator is failed to start, e.g. 
` ✔ 🏃  Running the Eclipse Che operator` has one more step `Che Operator pod bootstrap`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] crc
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot_20200923_115209](https://user-images.githubusercontent.com/5887312/93990350-af392880-fd93-11ea-8eae-a6456f766ce3.png)
![Screenshot_20200923_115226](https://user-images.githubusercontent.com/5887312/93990352-afd1bf00-fd93-11ea-96e5-ee9485412d01.png)
![Screenshot_20200923_115250](https://user-images.githubusercontent.com/5887312/93990354-b06a5580-fd93-11ea-888b-64bfaf85e1bd.png)

### Installation method
   - [x] chectl
     * chectl server:start --platform=crc
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context
https://github.com/eclipse/che/issues/17942

**Comment by l0rd** [comment]
Setting P1 to this issue because that's a bug and because providing the right diagnostic when an error happens is becoming critical.
