### ISSUE TITLE
Add a configuration to launch a custom extension by default when loading the theia IDE

### ISSUE THREAD

**Issue by rajeshkumarboda** [eclipse-che/che#17934]
### Problem

In the present scenario, when we create a Workspace in Eclipse Che, Eclipse Theia IDE launches with default explorer view.
I developed a custom extension plugin which I added to the workspace and the plugin icon is now visible on the left nav bar.
Now If I click on the icon, I can able to launch the extension view.

Now my requirement is, If I launch  the eclipse che workspace, I don't want to see explorer view by default. Instead I want to show the extension view by default. I should not have to click on the extension icon explicitly to launch the extension.

### Proposed Solution 
Provide some configuration which will enable the user to select the default view

**Comment by benoitf** [comment]
@rajeshkumarboda : are you using the stock che-theia image or you've your own che-theia image ?

**Comment by rajeshkumarboda** [comment]
> @rajeshkumarboda : are you using the stock che-theia image or you've your own che-theia image ?

I am using stock che-theia Image. I can able to figure out that I can launch my custom extension by default by keeping the below code in the activate method of the custom extension that I want to show as default.
vscode.commands.executeCommand("<extensionId>")
But I think it is better if there Is a configuration outside of the extension code
