### ISSUE TITLE
remove obsolete CSVs

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17943]
### Is your enhancement related to a problem? Please describe.

In `olm/eclipse-che-preview-kubernetes/deploy/olm-catalog/` and `olm/eclipse-che-preview-openshift/deploy/olm-catalog` there are CSVs going back to Che 7.0.0.beta5 which are of course EOL and unsupported. We should delete those old ones and make publishing new CSVs and metadata images faster.

```
$➔ tree -d . --sort=version
.
└── eclipse-che-preview-openshift
    ├── 7.0.0
    ├── 7.0.0-beta-5.0
    ├── 7.0.0-rc-2.0
    ├── 7.0.0-rc-4.0
    ├── 7.1.0
    ├── 7.2.0
    ├── 7.3.0
    ├── 7.3.1
    ├── 7.4.0
    ├── 7.5.1
    ├── 7.6.0
    ├── 7.7.0
    ├── 7.7.1
    ├── 7.8.0
    ├── 7.9.0
    ├── 7.10.0
    ├── 7.11.0
    ├── 7.12.0
    ├── 7.12.1
    ├── 7.12.2
    ├── 7.13.1
    ├── 7.13.2
    ├── 7.14.1
    ├── 7.14.2
    ├── 7.15.0
    ├── 7.15.1
    ├── 7.15.2
    ├── 7.16.0
    ├── 7.16.1
    ├── 7.16.2
    ├── 7.17.0
    ├── 7.17.1
    ├── 7.17.2
    ├── 7.18.0
    ├── 7.18.1
    └── 7.18.2

37 directories
```

Even better, we should have a process in place to purge old CSVs when they're perhaps 3 releases old.

### Describe the solution you'd like

Create a script that can purge old CSVs every time we release a new .0 version, so we only retain the last 3 versions.

**Comment by tolusha** [comment]
@nickboldt 
https://github.com/eclipse/che-operator/pull/483
