### ISSUE TITLE
Unable to install Che on docker-desktop using helm3 on windows 10 using chectl

### ISSUE THREAD

**Issue by aaraodeo** [eclipse-che/che#17956]
### Describe the bug
Unable to install Che on docker-desktop using helm3 on windows 10 using chectl

Command:
chectl server:start --platform=docker-desktop --installer=helm --skip-kubernetes-health-check
› Current Kubernetes context: 'docker-desktop'
  ↓ Verify Kubernetes API [skipped]
  √ �  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "che"...it is not
  > ✈️  Docker Desktop preflight checklist
    √ Verify if kubectl is installed
    √ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    ↓ Verify remote kubernetes status [skipped]
    √ Check Kubernetes version: Found v1.16.6-beta.0.
    × Verify if nginx ingress is installed
      → Error: unable to verify the first certificate
      Installing nginx ingress
      Verify domain is set
 »   Error: Error: Error: unable to verify the first certificate
 »   Installation failed. There are no available logs.

### Che version
nightly

### Steps to reproduce

chectl server:start --platform=docker-desktop --installer=helm --skip-kubernetes-health-check

### Expected behavior
che install successfully.

### Runtime
   docker-desktop + K8S (include output of `docker version` and `kubectl version`)

docker version

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683   

kubectl version

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Docker Desktop:
Version: 2.3.0.5(48029)
Channel: Stable

chectl version
chectl/7.19.0 win32-x64 node-v10.22.1

### Screenshots
   N/A

### Installation method
   chectl with platform Docker Desktop and installer helm3
   

### Environment
     Windows 10 Pro Version 1909 (OS Build 18363.1082)
     Local Single Node Kubernetes cluster as part of Docker Desktop
     Hardware: Laptop with 16 GB RAM with  Intel(R) Core(TM) i5-8350U CPU 4 cores, logical process 8, Virtualization Enabled.
     Connected to a HTTP proxy with high speed internet connection
     More than 100 GB Disk Free on C: where che installation is attempted

### Eclipse Che Logs
No Logs

### Additional context
 N/A

**Comment by tolusha** [comment]
Could you try `export NODE_TLS_REJECT_UNAUTHORIZED=0` before running chectl ?

**Comment by aaraodeo** [comment]
Tried setting  set NODE_TLS_REJECT_UNAUTHORIZED=0 then running following command:
Its fails

chectl server:start --platform=docker-desktop --installer=helm --skip-kubernetes-health-check --domain=10.76.63.167.nip.no
Current Kubernetes context: 'docker-desktop'
  ↓ Verify Kubernetes API [skipped]
  √ �  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "che"...it is not
  > ✈️  Docker Desktop preflight checklist
    √ Verify if kubectl is installed
    √ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    ↓ Verify remote kubernetes status [skipped]
    √ Check Kubernetes version: Found v1.16.6-beta.0.
    × Verify if nginx ingress is installed
      → HttpError: HTTP request failed
      Installing nginx ingress
      Verify domain is set
 »   Error: Error: HttpError: HTTP request failed
 »   Installation failed. There are no available logs.

Even i am not able to delete server too
chectl server:delete --skip-kubernetes-health-check
› Current Kubernetes context: 'docker-desktop'
You're going to remove Eclipse Che server in namespace 'che' on server 'https://kubernetes.docker.internal:6443'. If you want to continue - press Y: Y
  ↓ Verify Kubernetes API [skipped]
  × Delete oauthClientAuthorizations
    → HttpError: HTTP request failed
    Delete the Custom Resource of type checlusters.org.eclipse.che
    Delete CRD checlusters.org.eclipse.che
    Delete role binding che-operator
    Delete role che-operator
    Delete cluster role binding che-che-operator
    Delete cluster role che-che-operator
    Delete server and workspace rolebindings
    Delete service accounts che-operator
    Delete PVC che-operator
    Check if OLM is pre-installed on the platform
    Delete(OLM) custom catalog source eclipse-che-custom-catalog-source
    Delete(OLM) nigthly catalog source eclipse-che-preview
    Delete all deployments
    Delete all services
    Delete all ingresses
    Delete configmaps for Eclipse Che server and operator
    Delete rolebindings che, che-workspace-exec and che-workspace-view
    Delete service accounts che, che-workspace
    Delete PVC postgres-data and che-data-volume
    Delete consoleLink che
    Delete all deployments for DevWorkspace controller
    Delete all services for DevWorkspace controller
    Delete all ingresses for DevWorkspace controller
    Delete configmaps for DevWorkspace controller
    Delete ClusterRoleBinding for DevWorkspace controller
    Delete cluster Roles for DevWorkspace controller
    Delete service account for DevWorkspace controller
    Delete DevWorkspace controller CRDs
    Purge Eclipse Che Helm chart
    Wait until Eclipse Che pod is deleted
    Wait until Keycloak pod is deleted
    Wait until Postgres pod is deleted
    Wait until Devfile registry pod is deleted
    Wait until Plugin registry pod is deleted
    Error: HttpError: HTTP request failed

**Comment by tolusha** [comment]
Please,  examine the certificate chain of trust of your cluster 
`openssl s_client -connect kubernetes.docker.internal:443   -showcerts`
I assume the root CA is missed in the chain

**Comment by aaraodeo** [comment]
Is there any other way of confirming this on windows 10? openssl tool is not available in windows by default. I also tried downloading and using external openssl.exe tool and run the above command but its not working. Its most prob issue with openssl binary i am using.

openssl s_client -connect kubernetes.docker.internal:443 -showcerts
19692:error:0200274D:system library:connect:reason(1869):crypto\bio\b_sock2.c:110:
19692:error:2008A067:BIO routines:BIO_connect:connect error:crypto\bio\b_sock2.c:111:
connect:errno=0

**Comment by aaraodeo** [comment]
All right here is the output of the command u asked for:
openssl s_client -connect kubernetes.docker.internal:6443 -showcerts

CONNECTED(0000019C)
depth=0 CN = kube-apiserver
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = kube-apiserver
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = kube-apiserver
   i:CN = kubernetes
-----BEGIN CERTIFICATE-----
MIIDrDCCApSgAwIBAgIIJyzdcyVzngEwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
AxMKa3ViZXJuZXRlczAeFw0yMDA4MDUwNjU0NTdaFw0yMTA4MDUwNjU0NThaMBkx
FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAv2IxvArkG2WBMDhPdpvDg4Woa/ZOX8bRTWcxkk87Lrk3JRjS4Rbv
PRYRg4e2F7Rf+SYZnbb2NKZyXj2Coo5p4elBHKjGU/+G3s6nOnwVr9IyHLLbNjdn
k8ENUOL00kW6g7IMpHv3crGxI1ZR2alDaqjSxezHJIca2DC7ZrSoMgFIxMopTxm9
FULbUyvC/zskcMpgMrDAIMZ96WjZHgb7iFruJwCK7fO54bjMzJIB/R7dXdNiXTqe
XkD/5snm03c3eMfANjilF9ofKWyW1B3lB1wdgV71QrmjGfWq+6yCmE1JNHxLqGIl
Yqzp8vh/v2h9OPmjTJIoXutZ8msn8SMaFwIDAQABo4H7MIH4MA4GA1UdDwEB/wQE
AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATCB0AYDVR0RBIHIMIHFghJkb2NrZXIt
Zm9yLWRlc2t0b3CCCmt1YmVybmV0ZXOCEmt1YmVybmV0ZXMuZGVmYXVsdIIWa3Vi
ZXJuZXRlcy5kZWZhdWx0LnN2Y4Ika3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVz
dGVyLmxvY2FsghprdWJlcm5ldGVzLmRvY2tlci5pbnRlcm5hbIISdm0uZG9ja2Vy
LmludGVybmFsgglsb2NhbGhvc3SHBApgAAGHBAAAAACHBMCoQQOHBH8AAAEwDQYJ
KoZIhvcNAQELBQADggEBADKKusc73h68luAYwLtXWETeWcQdaqXp2xUv1L4azdLs
wKvbfCT8CT4FMOIZ8jwrLTadscDGick+cBALUNKJrmSVFJynLFvC+0KtThHBDhTt
/1uJlThak88g/w64T/lrMiQEZzj8wwAbQzf9Js9SIT3VpIok5bQmh21R9EaTmJbq
AqFG6q8LVrsNPKUYUJTPELbvqF+tNjTQcOkiOXUbdmix4zUuiSQqaiEgvg0IWko5
fkMP+nIOM6oQrMD08LoestdxC4uJz4tDaU3bnYiAVIuHcxKNkxki1T+gFmH9WTti
lx8v71vWDo7HG77KygcEnbYoE9F8Ad5NH5enxNaL+BE=
-----END CERTIFICATE-----
---
Server certificate
subject=CN = kube-apiserver

issuer=CN = kubernetes

---
Acceptable client certificate CA names
CN = kubernetes
CN = kubernetes
Requested Signature Algorithms: RSA-PSS+SHA256:ECDSA+SHA256:Ed25519:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA384:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA-PSS+SHA256:ECDSA+SHA256:Ed25519:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA384:ECDSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1607 bytes and written 422 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 21 (unable to verify the first certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_128_GCM_SHA256
    Session-ID: E020F7C4C3558258A6E10FE89D313C23D0319D508CD3E3C307DD117DD67058A1
    Session-ID-ctx:
    Resumption PSK: 3E40F4FD9A96CF17F12B939B515D5C71AFC1BC618B76378C9108B5D8E3A61FAC
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket:
    0000 - 28 fd 07 24 ad b3 2c c8-78 b6 66 e8 71 fe 51 db   (..$..,.x.f.q.Q.
    0010 - 56 99 8c 0b d0 9d a2 af-11 d2 e3 ee 5d 29 29 8c   V...........])).
    0020 - 20 a3 8c 35 79 78 3e 84-9d 0a 0e b8 42 f5 32 eb    ..5yx>.....B.2.
    0030 - 0e 11 d3 8e 38 79 01 39-1c b3 3e 82 15 2d 48 69   ....8y.9..>..-Hi
    0040 - 16 93 19 c6 9d 33 06 60-6f b4 89 dc f4 ab c6 f5   .....3.`o.......
    0050 - e3 36 f5 e4 53 10 d8 10-bf d7 f9 d2 3a e4 a5 6e   .6..S.......:..n
    0060 - 05 66 89 98 30 51 a2 5e-38 18 63 d3 ac 54 7b cf   .f..0Q.^8.c..T{.
    0070 - de                                                .

    Start Time: 1601282381
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK

I executed similar command on a local kubernetes cluster running on linux vm.
I got similar following output but there chectl che installation does not fails for same reason and it continues:
    Start Time: 1601282079
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)

For Linux VM used the command: chectl server:start --cheimage=quay.io/eclipse/che-server:7.19.1 --installer=operator --platform=k8s --skip-kubernetes-health-check --domain=10.242.131.161.nip.io --che-operator-cr-patch-yaml=patch.yaml --self-signed-cert

Shouldn't this error be handled by chectl for docker-desktop, as certainly a self signed certificate is being used?
chectl server:start --platform=docker-desktop --installer=helm --skip-kubernetes-health-check --self-signed-cert
»   Warning: "self-signed-cert" flag is deprecated and has no effect. Autodetection is used instead.
I think the autodetection is NOT working properly for chectl with docker for desktop.

**Comment by flacatus** [comment]
Hi @aaraodeo! 
We are not able to check the issue using chectl with docker-desktop. I did the next steps to install che in Windows10:

- Install docker-desktop from: https://www.docker.com/products/docker-desktop and then install WSL.
- After docker-desktop installation I enabled kubernetes from docker-desktop
- Then install chectl from https://github.com/che-incubator/chectl
- Install helm from https://helm.sh/docs/intro/install/
And in the end start che with the same command mentioned in the issue: `chectl server:start --platform=docker-desktop --installer=helm --skip-kubernetes-health-check`

I'll attach screenshot of installation.

![image](https://user-images.githubusercontent.com/59865209/96568881-ba1aa680-12c8-11eb-9da7-6d1116c5bf4e.png)

**Comment by aaraodeo** [comment]
Ok so it works in WSL for docker-desktop but not in non WSL mode.

**Comment by aaraodeo** [comment]
I switched to WSL2 on docker-desktop and tried again i got the same results.

![Screenshot 2020-10-21 010448](https://user-images.githubusercontent.com/9564014/96635462-8166e580-1339-11eb-8624-fe1b89d423a7.jpg)

One differentiator could be that i am using a http proxy to access the internet. Does chectl has issue in working behind http proxy?
