### ISSUE TITLE
Fix host in previewUrl

### ISSUE THREAD

**Issue by marouim** [eclipse-che/che#17955]
We would like to be able to specify the Openshift / Kubernetes route path instead of a generated one. 

Today, every time we start the application, Theia propose a generated route that is different at each execution. 

Example: 

spec:
  host: **route3fhlnfwt**-user-codeready.apps.openshift.domain.com
  to:
    kind: Service
    name: serveravliij4m-theia-ide2ac
    weight: 100

À recent enhancement allow users to define the home path and port to their application to generate the previewUrl. This can be specified in the command section of the devfile: 

commands:
  - name: run app
    previewUrl: 
       port: 3000 
       path: /

This request is to add a configurable Host portion in the preview Url to have a static route: 

commands:
  - name: run app
    previewUrl: 
       port: 3000 
       path: /
       host: my-app-develop.apps.openshift.domain.com

The result would be:

spec:
  host: **my-app-develop**.apps.openshift.domain.com
  to:
    kind: Service
    name: serveravliij4m-theia-ide2ac
    weight: 100

This might be already possible, if yes could you please point out how ? 

Thanks,

**Comment by benoitf** [comment]
cc @skabashnyuk @sleshchenko looks like more a server-side issue (when routes are created)

**Comment by sleshchenko** [comment]
It's really specific to the cluster configuration. Typically cluster users (non-admins) do not have the ability to specify custom-host.
And also it can lead to conflicts, where users are not able to run the workspaces from the same devfile. So, I'm not sure it should be a part of Devfile.
@davidfestal @l0rd WDYT?
