### ISSUE TITLE
Add single user mode installation test

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17958]
### Is your task related to a problem? Please describe.
We do not have tests to check installation of Eclispe Che in single user mode.

### Describe the solution you'd like
Add installation tests for single user mode which covers Operator and Helm installers

### Additional context
This issue is a requirement to complete checklist of [this PR](https://github.com/eclipse/che-docs/pull/1613).

**Comment by rhopp** [comment]
If this is about e2e tests, in past there was a decision to switch all of them to use multi-user deployment (as that's the primary deployment configuration). 
e2e tests are pretty expensive to run and maintain, so if we really need to test this, we should have pretty good reasons for this (cc. @l0rd )
I would prefer to close this issue.
