### ISSUE TITLE
Che installation fails on Minikube 1.13.1

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17952]
### Describe the bug
If try to install Eclipse Che on latest (1.13.1) Minikube, the installation fails:
```
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ❯ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Check Kubernetes version: Found v1.19.2.
    ✔ Verify if minikube ingress addon is enabled
    ✖ Enable minikube ingress addon
      → * Verifying ingress addon...
      Retrieving minikube IP and domain for ingress URLs
      Checking minikube version
      Check if cluster accessible
 ›   Error: Error: Command timed out after 18000 milliseconds: minikube addons enable ingress
 ›   Timed out
 ›   * Verifying ingress addon...
 ›   Installation failed. There are no available logs.
```

### Che version
nightly

### Steps to reproduce
Try to install Eclispe Che on Minikube 1.13.1

### Expected behavior
Installation is successful

### Runtime
Minikube 1.13.1

### Installation method
chectl

**Comment by benoitf** [comment]
I think chectl should not start minikube and try to enable ingresses by itself. Just report that ingress addon is not there and that minikube should be launched with `--addons=ingress` 
(to avoid such errors)

**Comment by mmorhun** [comment]
@benoitf yes, but not all users know about that.

**Comment by benoitf** [comment]
there is also some incompatibility on macos with minkube and ingresses. For example it's saying that ingress addon can't be enabled so even extending timeout will fail anyway

**Comment by benoitf** [comment]
> @benoitf yes, but not all users know about that.

chectl should print a nice message.

**Comment by mmorhun** [comment]
> chectl should print a nice message.

chectl enables it automatically if it wasn't.

**Comment by benoitf** [comment]
what i'm saying is that chectl can't do it automatically on minikube/macos with default minikube settings

**Comment by l0rd** [comment]
Starting with minikube 1.12 [docker is the default minikube driver](https://github.com/kubernetes/minikube/issues/8353) but the [ingress add-on doesn't work with the docker driver](https://github.com/kubernetes/minikube/issues/7332). The command `minikube start --memory=4096` is not enough anymore on fresh installations.

What I would propose is:
1. Fix [documentation](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/) and code to `minikube start --memory=4096 --vm=true && minikube addons enable ingress` on mac and windows
2. Update code to avoid starting minikube but providing explicit instruction to install / run / enable ingress for minikube based on the platform.

**Comment by benoitf** [comment]
For the documentation, 
`minikube start --memory=4096 --vm=true && minikube addons enable ingress`
can be replaced by
`minikube start --memory=4096 --vm=true --addons=ingress`

**Comment by mmorhun** [comment]
> what i'm saying is that chectl can't do it automatically on minikube/macos with default minikube settings

@benoitf I see. I tested it on Fedora and everything was working fine.
