### ISSUE TITLE
Move che.openshift.io specific code from che-theia to external plug-in

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17951]
### Is your task related to a problem? Please describe.
che-theia should not contain specific items related to where it's hosted.
But it can provide any API helping to customize behavior

### Describe the solution you'd like
Remove che.openshift.io specific code from the codebase
maybe move it to https://github.com/che-incubator/che-theia-openshift-auth

### Describe alternatives you've considered
N/A

### Additional context
https://github.com/eclipse/che-theia/blob/d8039264b1c763b7d57f40d16315dc4df6ddc5f6/extensions/eclipse-che-theia-plugin-ext/src/browser/che-openshift-main.ts#L31-L33

**Comment by ibuziuk** [comment]
@vinokurig @benoitf I guess you can clean it up safely since che.openshift.io has been shut down on March 1st
