### ISSUE TITLE
Hosted Che sso redirect page has a bad CSS

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17965]
### Describe the bug

When I login as a new user on che.openshift.io this is how I am welcomed:

![image](https://user-images.githubusercontent.com/606959/94265787-71760480-ff39-11ea-9c25-fdd22f8731a6.png)

### Steps to reproduce

Open an icognito window and browse to https://che.openshift.io/

### Expected behavior

Images, colors etc...should be visible

**Comment by Katka92** [comment]
@ibuziuk verified on che.openshift.io - working correctly now. Closing.
