### ISSUE TITLE
Theia Debug menu item should be Run menu item

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17967]
### Is your enhancement related to a problem? Please describe.

In Che Theia menu there is currently a "Debug" item but no "Run" item.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/606959/94274094-8ce70c80-ff45-11ea-881c-5a535f96b4f8.png">

In VS Code instead this menu item is called "Run" which is more straighforward:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/606959/94274264-c4ee4f80-ff45-11ea-8b1f-7e0bdb724652.png">

### Describe the solution you'd like

Rename "Debug" menu item as "Run".

**Comment by tsmaeder** [comment]
We should fix this upstream, not in che-theia.

**Comment by azatsarynnyy** [comment]
It has been fixed upstream.
issue https://github.com/eclipse-theia/theia/issues/8603
PR https://github.com/eclipse-theia/theia/pull/8653
