### ISSUE TITLE
Replace Thorntail stack with Quarkus on Eclipse Che website

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#17961]
https://www.eclipse.org/che/getting-started/cloud/ list things like thorntail which is no longer supported - could it be replaced with a Quarkus flow ?

**Comment by ibuziuk** [comment]
PRs sent:
- https://github.com/eclipse/che-website/pull/45
- https://github.com/redhat-developer/devfile/pull/64

**Comment by ibuziuk** [comment]
PRs have been merged. Closing
![image](https://user-images.githubusercontent.com/1461122/96608984-4a251400-12fa-11eb-849c-d799029393fb.png)
