### ISSUE TITLE
What's "Quarkus command mode" stack?

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17966]
## Summary

In the Quick Starts we have [recently](https://github.com/eclipse/che-devfile-registry/pull/272) introduced a "Quarkus command mode" stack.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/606959/94273489-c8cda200-ff44-11ea-9ca5-371a36196600.png">

How does this stack differ from the Quarkus stack? Why is it important to have both in Che getting started?

**Comment by l0rd** [comment]
cc @sunix

**Comment by sunix** [comment]
This is the getting-started sample to use https://quarkus.io/blog/introducing-command-mode/
Quarkus is also nice for writting CLI application. and it is quite different from the classic quarkus stack as we don't run a webapp. So the interaction is not the same.

The value in Che: when you are starting with Che and you are a Java developer and want to do a CLI that runs superfast supersonic, this is one option to start with.

**Comment by l0rd** [comment]
Ok got it. So I think that it would be better to change that to something like:

Title: Quarkus REST API
Description: Quarkus Stack with the default REST endpoint application sample

Title: Quarkus CLI
Description: Quarkus Stack with the command-mode sample
