### ISSUE TITLE
Implement Devfile tab on the Workspace Details

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17971]
### Is your task related to a problem? Please describe.
Implement Devfile tab on the Workspace Details
![image18](https://user-images.githubusercontent.com/5887312/94409607-11709f80-017f-11eb-801e-ede4f963567a.png)

**Comment by parvathyvr** [comment]
@sleshchenko I have updated the Devfile file tab to have SAve and Cancel buttons in the design doc.Please refer the updated designs [here](https://docs.google.com/document/d/1Ao0mfcqA41dv_h8SVgsVV7sPbO57opSuplL0331_xwM/edit?ts=5f185cf5#heading=h.sg9cjesmjmdb)

**Comment by olexii4** [comment]
fixed in https://github.com/che-incubator/che-dashboard-next/pull/68
