### ISSUE TITLE
Disable tasks output scanning

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17970]
### Is your enhancement related to a problem? Please describe.

Every time I start a task I am prompted with a question about "scanning the task output".

<img width="350" alt="image" src="https://user-images.githubusercontent.com/606959/94276038-fa943800-ff47-11ea-8a73-5eb6e1a841d8.png">

This is a bad UX. I understand that this is a VS Code behavior but it's still a bad behavior. I don't know why I am asked for that: if scanning helps to highlight problems in my source code it should always be enabled, otherwise it should not. That's not a question for users. 

And the help links to VS Code documentation where it says

> VS Code ships with several problem matchers 'in-the-box'

but I have no clue if Che/Theia ships with the same problem matchers or not.

### Describe the solution you'd like

Disable output scanning by default. Don't ask user.
When we will be convinced that this is helpful in Che/Theia we will enable output scanning. But we should never ask users if they want to enable it.

**Comment by tsmaeder** [comment]
@l0rd you realize you can just select "never scan the task output" to make it shut up, right?

**Comment by l0rd** [comment]
@tsmaeder you don't know how many times I clicked that yes.

**Comment by tsmaeder** [comment]
Are we not keeping that state when we restart the workspace?

**Comment by azatsarynnyy** [comment]
`Never scan the task output` stores the state as `"problemMatcher": []` in `tasks.json`
We could propose adding some option/preference in upstream Theia to disable it by default.

**Comment by tsmaeder** [comment]
> if scanning helps to highlight problems in my source code it should always be enabled, otherwise it should not.

That just does not work for tasks defined by the user (shell tasks, basically): the system can't know what output scanner to apply to a random shell command.

**Comment by l0rd** [comment]
> > if scanning helps to highlight problems in my source code it should always be enabled, otherwise it should not.
> 
> That just does not work for tasks defined by the user (shell tasks, basically): the system can't know what output scanner to apply to a random shell command.

Got it. The task in question is defined in the quarkus devfile in our registry. Given that we specify the task  we should also specify the scanner to apply. That could be another option but is that possible? In any case the developer that is using a devfile maintained by us should not be asked.

**Comment by tsmaeder** [comment]
Sound more like a problem in the devfile, if you ask me.

**Comment by l0rd** [comment]
> Sound more like a problem in the devfile, if you ask me.

If the devfile syntax currently allow to specify the problemMatchers for every command let's to that for all the devfile in the registry.

**Comment by azatsarynnyy** [comment]
We don't need to modify all Devfiles.
The problem can be solved by a minor enhancement of Task Plugin.

If we have decided that scanning a task output with the problem matchers must be disabled by default, it's enough to simply use the corresponding mechanism, already provided by Che Theia, in the right way.

Each task, defined in the tasks.json file, may have a list of problem matchers attached. It's optional and can be empty as well.
Only if it's **explicitly** defined as empty (`"problemMatcher": []`) Che Theia won't ask the user to choose a preferred option to scan output.

So, what we need to do?
On the stage of translating/importing a Che Command from a Devfile to tasks.json file, Task Plugin should add an empty problem matcher to each imported task. Just a single property and that's it.

With this enhancement applied, such Che Command in Devfile
![image](https://user-images.githubusercontent.com/1636395/95382752-cda23680-08f2-11eb-8224-070ac9bf3e41.png)

will be imported as the task with an empty problem matcher
![image](https://user-images.githubusercontent.com/1636395/95383578-0a226200-08f4-11eb-8811-5fe913114eec.png)

And the user won't be asked anymore for any additional info after running such a task. As long as he/she set some problem matcher for the task.
