### ISSUE TITLE
Icons for tabs are not displayed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#17978]
### Describe the bug
Icons are absent for different kinds of tabs: task tab, terminal tab, editor tab.
Please see  https://github.com/eclipse/che/issues/17978#issuecomment-700739292

The issue is blocking an update Devfile E2E tests and GitSSH flow E2E tests #17973.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start nightly Eclipse Che
2. Create and open Java maven workspace
3. Open any file, terminal or run a task

### Expected behavior
A tab contains the corresponding icon:
![tabs_expected_behavior](https://user-images.githubusercontent.com/5676062/94571981-2f222f80-0279-11eb-8a07-816115767b44.png)

### Actual wrong result
There are no icons for tabs:
![tabs_actual_behavior](https://user-images.githubusercontent.com/5676062/94572067-452ff000-0279-11eb-8811-44e0ecbce79b.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by RomanNikitenko** [comment]
Tested on `che-dogfooding` instance - can not reproduce it.

**Comment by azatsarynnyy** [comment]
@dmytro-ndp is it stable reproducible or does it requires some specific environment, devfile, etc.

**Comment by azatsarynnyy** [comment]
@dmytro-ndp It seems we were modifying the issue labels at the same time 
That's why it shows I removed the blocker from it. It's done not on purpose :slightly_smiling_face: 
Feel free to re-check the labels and correct it if needed.

**Comment by RomanNikitenko** [comment]
Tested on https://che.openshift.io/ - can not reproduce the bug

![status_icon_openshift](https://user-images.githubusercontent.com/5676062/94411272-0e76ae80-0181-11eb-998c-60adce171b26.gif)

**Comment by azatsarynnyy** [comment]
> @dmytro-ndp is it stable reproducible or does it requires some specific environment, devfile, etc.

@dmytro-ndp could you also attach the screenshot of Help>About dialog to check what version is used in your case?

**Comment by dmytro-ndp** [comment]
@azatsarynnyy, @RomanNikitenko: I also can't reproduce it on che.openshift.io in workpsace having changes from corresponding PR https://che.openshift.io/f/?url=https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-823/simple/che-theia-maven-devfile.yaml

**Comment by dmytro-ndp** [comment]
@azatsarynnyy
> @dmytro-ndp could you also attach the screenshot of Help>About dialog to check what version is used in your case?

It's nightly version of che-theia: quay.io/eclipse/che-theia@sha256:3be78bf018b54eb6a8cf518a85cda95973cb831652819003e43c234116f3aa05

**Comment by dmytro-ndp** [comment]
@RomanNikitenko, @azatsarynnyy: I have reproduced an issue on Eclipse Che nightly instance on QE OCP https://che-nightly-che.apps.ocp45.crw-qe.com/dashboard/#/ide/admin/apache-camel-k-sxln1?tab=getStarted
![Screenshot from 2020-09-28 18-37-43](https://user-images.githubusercontent.com/1197777/94453946-f66f5100-01b9-11eb-8281-4083aa52d1e7.png)

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
Nice!

But from your screenshot I see that a task was not started at all
I tried your link and see that behavior as well
![error_task](https://user-images.githubusercontent.com/5676062/94455613-f4a68d00-01bb-11eb-80b9-cd1203d89af1.gif)

I thought that E2E tests were failed because they were waiting successfully completed task https://github.com/eclipse/che/issues/17973
isn't it?

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
I played a little with the instance that you provided and can reproduce the issue for started tasks and different statuses.
So, looks like we can use this instance to debug and fix the issue.

Thank you very much for your help, Dmytro!

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: you are right about the test. 
Actually, the issue is about task status icon, which isn't been shown doesn't matter if it's successful, error, or in-progress task:
![Screenshot from 2020-09-28 19-02-12](https://user-images.githubusercontent.com/1197777/94458070-1b65c300-01be-11eb-9ea3-ca89cf07a089.png)

**Comment by RomanNikitenko** [comment]
> Actually, the issue is about task status icon, which isn't been shown doesn't matter if it's successful, error, or in-progress task

I understand, but technically the causes of the problems are different for already started task and not started at all.
To fix ETE tests it was important to reproduce the issue for already started tasks.
That's why I asked about it.

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
For the instance that you provided I see that icons are absent for different kinds of tabs: task tab, terminal tab, editor tab. So the issue more global.

**Expected:**
![tabs_expected_behavior](https://user-images.githubusercontent.com/5676062/94570876-fd5c9900-0277-11eb-93c5-3f86f562c939.png)

**Actual:**
![tabs_actual_behavior](https://user-images.githubusercontent.com/5676062/94570958-136a5980-0278-11eb-8961-d9744b4f6ec5.png)

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: good catch, thank you!
