### ISSUE TITLE
Language Server Protocol: DidChangeConfiguration Notification feature

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1798]
A notification sent from the client to the server to signal the change of configuration settings.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#didchangeconfiguration-notification

**Comment by vparfonov** [comment]
Currently Che IDE doesn't have such configurations so we can't implement it now.

**Comment by slemeur** [comment]
Fixed in Che 7
