### ISSUE TITLE
[docs] level 3 and 4 headers are not well visible (missing styles?)

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17987]
### Is your enhancement related to a problem? Please describe.

Styles for level 3 and 4 headers (it's actually h4 and h5 in html) are too small to be clearly visible on page.

See this screenshot. Rounded texts are level 3 headers like `=== Component type: cheEditor`, but they are practically invisible on the page as headers, because they blend in other text styling.
![20200929_143209_1631x906_scrot](https://user-images.githubusercontent.com/1160903/94559035-efe7e480-0260-11eb-8978-185e77471445.png)

Situation with level 4 header is even worse, because it's even smaller than normal text:
![20200929_143821_1424x689_scrot](https://user-images.githubusercontent.com/1160903/94559618-cf6c5a00-0261-11eb-8f30-a72dcffed7c8.png)

### Describe the solution you'd like

Update css styles so at least level 3 and 4 headers are clearly visible on the page.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by themr0c** [comment]
We should get rid of these level 3 and 4 titles, as they are not compliant with the structure of a reference module according to modular docs. See:   https://redhat-documentation.github.io/modular-docs/#creating-reference-modules

> If you have a large volume of the same type of information to document, use a structure into which the information details can fit, and then document each logical unit of information as one reference module. For example, think of man pages, which document very different information details, but which still use consistent titles and formats to present those details in a uniform information structure.

**Comment by boczkowska** [comment]
Docs Jira https://issues.redhat.com/browse/RHDEVDOCS-2650
