### ISSUE TITLE
Generate a docker image from customized eclipse theia source code 

### ISSUE THREAD

**Issue by youssef-chtourou** [eclipse-che/che#17988]
after i customize eclipse theia IDE

how i can generate a image from this IDE to use in eclipse che

**Comment by tsmaeder** [comment]
@chtourou-youssef could you describe a bit what you're doing? What exactly are your changes to che-theia?

**Comment by azatsarynnyy** [comment]
@chtourou-youssef use the `./build.sh` script. For more details https://github.com/eclipse/che-theia/tree/master/dockerfiles/theia#how-to-build-theia-image

**Comment by chtourou-youssef** [comment]
> @chtourou-youssef could you describe a bit what you're doing? What exactly are your changes to che-theia?

i disable the download option in IDE

any user shouldn't download the project in his laptop

**Comment by chtourou-youssef** [comment]
> @chtourou-youssef use the `./build.sh` script. For more details https://github.com/eclipse/che-theia/tree/master/dockerfiles/theia#how-to-build-theia-image

no , i would build a docker image

**Comment by benoitf** [comment]
build.sh script generates docker images that can be published so I think this issue can be closed.
This script is used to build the current che-theia images and publish them on quay.io
