### ISSUE TITLE
Switching to persistent storage on che.osio we should warn about the filesystem issues

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17990]
### Is your enhancement related to a problem? Please describe.

On che.osio workspaces use ephemeral storage by default because of the issues with the persistent volumes file system of that platform.

New users are not aware of such issues and may be tempted to switch to persistent storage. After all, in the eyes of a new user, persistence will be better because changes don't get lost.

### Describe the solution you'd like

We should warn users that switching to persistent volume may have performance and integrity issues (with links to the corresponding issues) and ask them to confirm their choice.

**Comment by sleshchenko** [comment]
Seems it's going to be fixed for on dashboard next
![Screenshot_20201001_161052](https://user-images.githubusercontent.com/5887312/94813527-c5cd2880-0400-11eb-832a-7b56487b1d06.png)
![Screenshot_20201001_161104](https://user-images.githubusercontent.com/5887312/94813530-c665bf00-0400-11eb-9a01-51e9084b4429.png)

**Comment by ibuziuk** [comment]
+ 1 to have this in the upstream. Otherwise, we would need to patch the dashboard specifically for Hosted Che, smth that we just get rid of several months ago and want to avoid as much as possible

**Comment by ibuziuk** [comment]
Closing since che.openshift.io EOL was March 1st
