### ISSUE TITLE
When switching from ephemeral to persistent storage I am not expecting to lose my files

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17991]
### Is your enhancement related to a problem? Please describe.

When a user switch from ephemeral to persistent storage type it does that because he doesn't want to lose the changes he has been working on. The issue is that when switching from ephemeral to persistent storage all changes get lost immediately without any warning.

### Describe the solution you'd like

Warn users that previous changes done using ephemeral storage will get lost and ask for confirmation.

### Describe alternatives you've considered

Move data from ephemeral storage to the persistent storage so that user won't need to start from scratch.

**Comment by sleshchenko** [comment]
The new dashboard has the corresponding warning:
![Screenshot_20210204_144345](https://user-images.githubusercontent.com/5887312/106894293-6e64ff00-66f7-11eb-9f25-d74a87cd0a14.png)

@l0rd feel free to reopen if it's not sufficient
