### ISSUE TITLE
[Hosted Che] update to 7.19.x is failing due to changes in permissions required for single-host

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17999]
### Describe the bug

Looks like currently with a single host implementation configmaps are read unconditionally (for Hosted Che we need a way to disable since SA does not have permissions for that)

There was a similar issue related to extra configmap permissions in 7.17.0 -  https://github.com/eclipse/che/issues/17576

### Che version

 - [ ] 7.19.1

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/94689669-72d77080-032f-11eb-86ce-1b271389a42e.png)

### Eclipse Che Logs

```
Error: Failed to run the workspace: "Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/prcheck-1969/configmaps?labelSelector=che.workspace_id%3Dworkspaceqycvd644cj6fsr1c. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps is forbidden: User "system:serviceaccount:prcheck-1969:rhche" cannot list resource "configmaps" in API group "" in the namespace "prcheck-1969". The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password."
```

### Additional context
Hosted Che related PR - https://github.com/redhat-developer/rh-che/pull/1969

**Comment by ibuziuk** [comment]
@sparkoo @skabashnyuk thank you for looking into this one. Any chance for a hot-fix for 7.20.x? We will need to stick with this version on Hosted Che for a while since it will be a base for CRW 2.5

**Comment by sparkoo** [comment]
> Any chance for a hot-fix for 7.20.x?
There's always a chance :) I believe I will have fix tomorrow. The patch itself should be simple, the most tricky part is how to do it right.

**Comment by sparkoo** [comment]
I believe it fails here https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/CheNamespace.java#L163 which is called on workspace startup https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java#L198.

In normal Che deployments, `che` serviceaccount should have permissions to list configmaps in `che` namespace, but for some reason it's not the case here.

I have few ideas, how to fix this, but I don't like neither of them:
1. We could catch the exception and ask if it's permissions issue `code == 403`. If yes, just log it and continue, without throwing exception up
   - This is ugly for multiple reasons.
     - control flow with exception
     - requesting k8s API again and again for the same 403 result
     - this will silently pass, even if we really want to fail here (gateway single-host)
1. In theory, we need to cleanup configmaps in che namespace only in gateway single-host. So ask in `KubernetesInternalRuntime` or `CheNamespace` if we're on gateway single-host.
    - so far neither of these classes know about the workspace exposure type
    - there might be an edge-case, when we switch from gateway single-host to something else, the configmaps in che namespaces won't be cleaned
1. create some `Cleaner` class, that would have all the information to decide what to clean and will be injected into `KubernetesInternalRuntime`
    - more complex
    - again, edge-case with gateway single-host => something else switch
1. Introduce some new config property, that will just tell `cleanup_che_namespace=true|false`



cc: @ibuziuk @skabashnyuk

**Comment by sparkoo** [comment]
I've created draft PR of the cleanest solution I can currently think of. WDYT @skabashnyuk @ibuziuk ?
