### ISSUE TITLE
"Quarkus Tools for Eclipse Che" welcome page is not for Che

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18005]
### Describe the bug

![image](https://user-images.githubusercontent.com/606959/94748851-9bd52100-0382-11eb-81c3-7dc29d6f126e.png)

As soon as a workspace that includes Quarkus is started the welcome page "Quarkus Tools for Ecclipse Che" is shown. That page, when rendered in Che, has several problems:

1. The Requirements section includes links of type `vscode:extension` that fail to open in Theia. And anyway those requirements are ALWAYS included with Quarkus in Che [as dependencies](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/quarkus-java11/1.6.0a/meta.yaml#L22) so that is only confusing for a user.
2. The Get started section proposes to create a new `quarkus-getting-started` project. But if we just started a workspace from Che get-started that project has just been cloned. We should probably mention that Che getting started includes that project and ask if we want to clone a distinct on in current workspace.
3. Clicking on "Create Quarkus project" starts a wizard that, at the very end, shows a filesystem explorer to select the target folder where the Quarkus project will be cloned. If the user selects a folder different then `/projects` the project won't be available in the IDE.

### Che version

che.osio

### Steps to reproduce

1. Open che.openshift.io
2. Select "Quarkus Tools" among the Getting started samples
3. Wait for the workspace to start
4. Open a java file and wait for the "Quarkus Tools for Eclipse Che" welcome page to show up

### Expected behavior

Every section of "Quarkus Tools for Eclipse Che" welcome page should be written with Che in mind.

**Comment by nickboldt** [comment]
So is this issue asking for a fix to https://download.jboss.org/jbosstools/vscode/stable/vscode-quarkus/vscode-quarkus-1.6.0-390.vsix to remove unneeded text content? 

(As a naive contributor trying to do triage, I would find it easier if  bug reports pointed to the repo where the problematic code resides, so I can have a look at it and maybe even contribute a quickfix text change.)

**Comment by l0rd** [comment]
> So is this issue asking for a fix to https://download.jboss.org/jbosstools/vscode/stable/vscode-quarkus/vscode-quarkus-1.6.0-390.vsix to remove unneeded text content? 
> 
> (As a naive contributor trying to do triage, I would find it easier if  bug reports pointed to the repo where the problematic code resides, so I can have a look at it and maybe even contribute a quickfix text change.)

@nickboldt I have no idea :-) I was actually surprised that it was customised for Che.

**Comment by ericwill** [comment]
I don't see this anymore, at least not on Dev Sandbox as of today.
