### ISSUE TITLE
Update vale binary version in the che-sidecar-vale image

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18008]
The `vale` binary in the image referenced in latest version of vale plugin, `https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/testthedocs/vale/0.9.1/meta.yaml`, `quay.io/eclipse/che-sidecar-vale:0.9.1-ad53ccf`, is outdated: `vale version 1.7.0`.

Latest `vale` release is `2.4.0`, see https://github.com/errata-ai/vale/releases.

We need at least version `2.3` to get the new Vocab features working in `che-docs`.

**Comment by ericwill** [comment]
I'll take care of this for 7.20.
