### ISSUE TITLE
Language Server Protocol: Hover feature

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1800]
The hover request is sent from the client to the server to request hover information at a given text document position.
Changed: in 2.0 the requests uses TextDocumentPositionParams with a proper textDocument and position property. In 1.0 the uri of the referenced text document was inlined into the params object.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#hover

**Comment by JamesDrummond** [comment]
@evidolob @vparfonov Provide status label.

**Comment by bmicklea** [comment]
Further specification will be written during this sprint.
