### ISSUE TITLE
How do I use or refrence the dynamic previewUrl? in either devfile commands and/or startup task scripts? 

### ISSUE THREAD

**Issue by Mbd06b** [eclipse-che/che#18003]
## Summary
Whenever I startup a workspace and run an apache server it get's a dynamically generated previewUrl like:
https://serveru1wmiqtd-php-server-8080.che.example.com/ 
https://serverkkqjxktq-php-server-8080.che.example.com/   (workspace closed and reopened) 

![image](https://user-images.githubusercontent.com/12649222/94762614-d3859e00-036d-11eb-9b42-faf0f224e044.png)
_Ok there you are .... now how do I get you?_

The project I'm trying to host in eclipse che has an environment configuration which needn to reference the app context URL.  

So the question is:  How either in devfile commands, or within project startup scripts, can I "get", "refer to", or "query" the dynamic previewUrl OR  generated "id" (ie. _u1wmiqtd, kkqjxktq_),   to assign those project variables using commands (tasks.json) or startup scripts? 

Thereby avoiding having to manually update a project-specific file before running tasks on every launch? And allowing the project to be truly portable.  

## Relevant information
eclipse-che: 7.17.0, theia editor,  using a php/apache/mysql stack. 

Things I've reviewed so far...
Eclipse Che devfile documentation: https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_command_preview_url
possibly related Mattermost discussion.... https://mattermost.eclipse.org/eclipse/pl/u4hsunmhnb84xg7x14qudmc6wy
Eclipse Che 6 related issue? "How to know workspace Id"... https://github.com/eclipse/che/issues/10508

Feature discussion on previewUrl support 
"Add previewURL support in Devfile format" ..https://github.com/eclipse/che/issues/13945

@sparkoo @l0rd ?

**Comment by nickboldt** [comment]
@skabashnyuk is this a platform team issue?

**Comment by sparkoo** [comment]
If you need internal communication on service level, you can use discoverable endpoints or even `localhost` as everything is running in a single pod.

If you need url of external endpoint, I don't think it's currently possible. But maybe I'm wrong.

**Comment by skabashnyuk** [comment]
@nickboldt I think it's better to ask @benoitf. I think hi was the author of this issue. Or plugins team.

**Comment by Mbd06b** [comment]
> If you need url of external endpoint, I don't think it's currently possible. But maybe I'm wrong.

Setting an app context url is super important for any kind of front end web-app development. There has to be a way of getting this.

**Comment by sleshchenko** [comment]
I think the solution here would be: via devfile define enpoint, in the running workspace access endpoint URL via an environment variable like `CHE_${COMPONENT_NAME}_${ENDPOINT_NAME}_ENDPOINT_URL`. Currently we have some ports info injected by plugin broker or k8s api:
![Screenshot_20201005_102352](https://user-images.githubusercontent.com/5887312/95050851-ecd37500-06f4-11eb-922b-66febf08ae8e.png)
