### ISSUE TITLE
DELETE user API, should stop running workspaces instead of failing with 500 error

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18000]
### Is your task related to a problem? Please describe.
Currently delete user API `curl -X DELETE http(s)://{che-host}/api/user/{id}` is failing with 500 error if a user has running workspaces. Instead of this, the Che server should stop all the workspaces belonging to the given user and then perform the cascade deletion of the all user data

### Describe the solution you'd like
`curl -X DELETE http(s)://{che-host}/api/user/{id}`
DELETE user API, should stop all running workspaces instead of failing with 500 error

### Describe alternatives you've considered
N/A

### Additional context
The task is related to the original GDPR related issue https://github.com/eclipse/che/issues/17541

**Comment by skabashnyuk** [comment]
@ibuziuk can we guarantee in all cases that che-server SA or admin user SA has enough permission to perform stop operation?

**Comment by ibuziuk** [comment]
> @ibuziuk can we guarantee in all cases that che-server SA or admin user SA has enough permission to perform stop operation?

I suppose not in all cases, but we should investigate the following options:

- Stopping workspaces during the DELETE user call should be possible when both OpenShift OAuth  and `che.workspace.stop.role.enabled` are enabled ('che' ServiceAccount should have the `stop-workspace` role with this setup)

- Alternatively, there could be an option that would allow cleanup all the user data (including workspace data) during DELETE call only on the Che level only, and on k8s level the only thing that would be needed is the removal of the underlying namespace.  
This approach could be treated more like a workaround in case there will be problems with permissions for stopping all workspacces gracefully
