### ISSUE TITLE
[UX] When clicking "Run" nothing happens unless a java file is open / extension is loaded

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18004]
### Describe the bug

Clicking "Start Debugging" or "Start Without Debugging" from Theia Debug menu has no effects until the Java extension is not activated:

![image](https://media.giphy.com/media/kZZg5WDRIrOWK8qcLm/giphy.gif)

Clicking on those items AFTER opening a Java file (and the Java extension has started) does have an effect.

### Che version

che.openshift.io

### Steps to reproduce

1. Go to che.openshift.io
2. Click on the Quarkus Tools stack
3. Wait for the workspace to start 
4. Click "Start Debugging" or "Start Without Debugging" from Theia Debug menu

### Expected behavior

If no event is hooked to a menu item, then that item should be disabled.

**Comment by sunix** [comment]
Hello,
The path I have chosen was to see if we could from che-theia,

1. detect a debug port activation
2. change the Start Debug command enablement according to that.

so 1. is done in port plugin

For 2. I try to see if we could override an existing command enablement from a plugin or a theia extension. but it looks like it is not possible. https://github.com/eclipse-theia/theia/blob/master/packages/core/src/common/command.ts is not providing a way to override an existing command.
