### ISSUE TITLE
Enhance chectl message after a successful deployment

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#18019]
### Is your enhancement related to a problem? Please describe.
CLI users face a successful completion that doesn't offer much information.  Please add more useful information to the 'end of script' messaging.

### Describe the solution you'd like
Please provide a better message at the end of the script: 
- list the URLS for keycloak, postgres, registries, server, documentation, known issues
- suggest a command to create your first workspace

### Describe alternatives you've considered
Figure all that stuff in other ways.  It's be nice if the script provided it.

### Additional context
These ideas originated with a team call 01 Oct 2020.  Team members may have other ideas to contribute.

**Comment by nickboldt** [comment]
This is nice to have for 7.21, which if done in time could be backported to 7.20.2.

**Comment by nickboldt** [comment]
@RickJWagner can you draft the layout / content you'd like to see onscreen? Once we have a template, we can share that with the deploy team and get this turned into a PR.

**Comment by RickJWagner** [comment]
Suggested end message, following a successful installation:

CodeReady Workspaces {version} has successfully installed in {minutes}:{seconds}
Users can access the Dashboard at {CRW Route}
Release Notes are at {portal release notes URL}
Product documentation is at {portal docs URL}
Devfiles can be viewed at {devfile registry URL}
Plugins can be viewed at {plugin registry URL}
Red Hat SSO can be accessed at {Keycloak URL}

**Comment by nickboldt** [comment]
Not yet implemented, so reopening:

* suggest a command to create your first workspace
* list the URLS for postgres, known issues

Also tweaked the layout a little in followup issue https://github.com/eclipse/che/issues/18122

**Comment by tolusha** [comment]
@nickboldt 
> suggest a command to create your first workspace

It make sense only if workspace commands are available in downstream project, aren't they?

> list the URLS for postgres

There is no ingress/route for the postgres, so nothing to show

**Comment by tolusha** [comment]
@nickboldt 
pls, provide the exact message you would like to see with `workspace:create` command

**Comment by tolusha** [comment]
Not yet implemented, so reopening:

> suggest a command to create your first workspace

Pls provide message, I will do it in another issue.

> list the URLS for postgres

There is no public url for PostgreSQL

> known issues

Done for downstream only
