### ISSUE TITLE
[new UD] Add Actions for the WorkspaceDetails page

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#18013]
### Is your task related to a problem? Please describe.
Add Actions for the WorkspaceDetails page:
![Screenshot from 2020-10-01 17-00-56](https://user-images.githubusercontent.com/6310786/94819251-b43b4f00-0407-11eb-818a-4f592e95a726.png)
![Screenshot from 2020-10-01 17-04-04](https://user-images.githubusercontent.com/6310786/94819624-26139880-0408-11eb-8c52-808281e4f0b8.png)

**Comment by sleshchenko** [comment]
Missed feature - `Start in debug mode`

**Comment by parvathyvr** [comment]
@olexii4 @sleshchenko here is the  marvel link to the Actions menu https://marvelapp.com/prototype/6e5cjhj/screen/74882133
**The main update is after 'Open' we have 'Open in verbose mode' which is the updated action for 'Run in Debug mode' from the old UI.**
Let me know if you have any questions-This is also updated in the [design doc](https://docs.google.com/document/d/1Ao0mfcqA41dv_h8SVgsVV7sPbO57opSuplL0331_xwM/edit?ts=5f185cf5#heading=h.nbsiazoprj7h)
