### ISSUE TITLE
Vale extension should only use the vale configuration in the project.

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18010]
When there is no vale configuration in a project, or when there is a problem for the side-car container to access the vale configuration in the project, I would prefer that the vale plugin does not use at all a random configuration, which is misleading for the user.

To achieve that, no configuration file or style should be present inside the container.

This happened on a workspace started yesterday:

When editing in Hosted Che a file from `che-docs` https://che.openshift.io/f?url=https://github.com/eclipse/che-docs/, the `.vale.ini` inside the project was not used, but the configuration file present in the vale plugin container. In `che-docs`, we recently reorganized the styles to keep only three active styles: `CheDocs,IBM,Vale`. Opening some random files in the repository, I could see problems reported for styles that are not present anymore `write-good`.

I guess that, for some reason, the vale side-car container could not access the project configuration file?

Today, I can't reproduce the issue: the configuration file from the project is used.

**Comment by ibuziuk** [comment]
@ericwill not sure why area/hosted-che is there, I suppose it is not Hosted Che specific issue per se

**Comment by ericwill** [comment]
> @ericwill not sure why area/hosted-che is there, I suppose it is not Hosted Che specific issue per se

I think I just derped when assigning the label, sorry about that!
