### ISSUE TITLE
Please provide more flexibility at installation time

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#18018]
### Is your enhancement related to a problem? Please describe.
Che is installed in a wide variety of environments.  Please consider ways to increase flexibility in installation to allow deployment under various environments.

### Describe the solution you'd like
There should be more options when deploying.  Especially considering TLS and custom certificates, we should have ways to easily provide CA certs that are propagated to all the necessary places.

### Additional context
This request originated with a team call Oct 01, 2020.  At the time it was noted there should be other options provided as well.  Please confer with others, seek ideas, implement them.

**Comment by tolusha** [comment]
@RickJWagner 
Could you elaborate more please? I am not sure If I understand it completely.

**Comment by tolusha** [comment]
Implemented and described in the doc 
https://github.com/eclipse/che-docs/pull/1719
