### ISSUE TITLE
Add a new chectl command server:deploy and change server:start behavior

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#18015]
### Is your enhancement related to a problem? Please describe.
The enhnancement is related to the CLI tooling.  

### Describe the solution you'd like

  'server:start' should be renamed 'server:deploy' and server:start/stop should work only if CRW is already deployed
 - check if an existing deployment exists, and if not, echo error:  no such deployment exists, did you mean to run server:deploy?"
 -  if a deployment DOES exist already, running server:start would check for existing deployment, and if not running, would spool up pods or echo a warning saying "deployment is already started"
 -  Existing functionality in :start would move to :deploy, and new :start command would just spool pods up if not running
 -  New :stop command would spool pods down if running or echo warning saying “deployment is already stopped”

### Describe alternatives you've considered
Continue usage of current CLI tooling

### Additional context
These suggestions originated with a team call 01 Oct 2020.  

- [x] Add server:deploy as alias to server:start command https://github.com/eclipse/che/issues/18057
- [x] Update automated tests

**Comment by nickboldt** [comment]
Hoping we can tackle this during the next sprint for 7.20.x / 7.21. It would be great to get this refactoring done for CRW 2.5 since that's hopefully the release where we support crwctl for OCP 4.x.

**Comment by tolusha** [comment]
> 'server:start' should be renamed 'server:deploy' and server:start/stop should work only if CRW is already deployed

Unfortunately that's barely possible. All users and documentation refers to `server:start` command.
What I can do is to add `server:deploy` alias to `server:start` command and improve messages for `start/stop` commands for  cases you mentioned.

**Comment by l0rd** [comment]
@tolusha what about the following plan:
- SPRINT N:
  - add a new command `server:deploy` as an alias of `server:start`
  - add a deprecation warning on `server:start`
  - communicate on che-dev
  - update documentation
- SPRINT N+1:
  - update automated tests
- SPRINT N+2:
  - server:start fails if che server is not deployed

**Comment by tolusha** [comment]
@l0rd 
ok, It make sense for me
