### ISSUE TITLE
Go to Definition doesn't work.

### ISSUE THREAD

**Issue by pranaysashank** [eclipse-che/che#18038]
### Describe the bug
Go to Definition, which is usually mapped to Ctrl+Click is disabled. When we right click on a symbol, "Go to Definition" is disabled in the go stack (& possibly other languages as well, I tried with Haskell).

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace using the predefined go template in the Get Started tab.
2. Once the workspace is open, make example folder your workspace root (by going to File menu and clicking on Open Workspace Roots)
3. In the example folder workspace, go to outyet/main.go and right click on any function call
4. You should see Go to Definition disabled.

### Expected behavior

Go to Definition should work.
In a standalone theia that I installed the lsp server works fine i.e. Ctrl + Click & Go to Definition works properly, so the plugin is probably fine.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) - 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```
   - [x] Openshift (include output of `oc version`) - whatever is on che.openshift.io
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2020-10-03 23-25-26](https://user-images.githubusercontent.com/15224715/94998518-e4cde500-05cf-11eb-9cd2-b1f560896488.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
```bash
chectl server:start --installer=helm --platform=k8s --domain=domainname --multiuser 
```
     * provide an output of `chectl version` command
```
chectl/7.19.1 linux-x64 node-v10.22.1
```
   - [ ] OperatorHub
   - [ ] I don't know
The same problem occurs on minikube, kubectl, and che.openshift.io.

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other - Digital Ocean, che.openshift.io
   - [ ] other: please specify

### Additional context

In a standalone theia that I installed, the lsp server, with the plugins pasted in the plugins folder, works fine i.e. Ctrl + Click & Go to Definition works properly, so the plugin is probably fine.

**Comment by pranaysashank** [comment]
https://github.com/eclipse/che/issues/16929 looks like it's related to this

**Comment by pranaysashank** [comment]
The java-maven workspace which is using vscode-java plugin is working as expected. Perhaps there is a problem with the go plugin, maybe it's not advertising "Go to Definition" capability?

**Comment by gattytto** [comment]
this is produced because the dockerfile needs to be updated and change gopls from "latest" to "master" and also add "golang.org/x/tools@master". 
![image](https://user-images.githubusercontent.com/407397/95117690-5f594a80-071f-11eb-96d3-c2531127639c.png)
