### ISSUE TITLE
Create automated E2E system tests of IntelliJ IDEA as a Che editor

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18035]
### Is your task related to a problem? Please describe.
Eclipse Che 7.20.0 planned to support IntelliJ IDEA as a Che editor https://github.com/eclipse/che/issues/17790

So, we need to automate verification of workspaces with IntelliJ IDEA as embedded editor.

**Comment by l0rd** [comment]
Testing intelliJ running in the browser may be tricky. Checking that the workspace is started successfully should be enough.

**Comment by azatsarynnyy** [comment]
> Testing intelliJ running in the browser may be tricky. Checking that the workspace is started successfully should be enough.

+1 as noVNC web client is used here. It draws the UI within HTML Canvas. So, there're no DOM elements to check.

**Comment by rhopp** [comment]
From meeting with @l0rd 
Good to check: 
* Activity checker (when active, pings are sent, when inactive, pings are not sent)
* * Idling (connected to activity checker)
* Configuration persistence.
This could/should be done mostly by monitoring server logs and InteliJ Idea logs/standard output.

**Comment by vzhukovskii** [comment]
>Activity checker (when active, pings are sent, when inactive, pings are not sent)

Note, at this moment there's a simple implementation of activity tracker, that always pings ws master, no matter if browser window in focus or not.

**Comment by rhopp** [comment]
@l0rd Question about the configuration persistance. 
This is meant in the scope of single workspace (config is persisted between restarts). 
Not in the "user" scope (the settings are the same for all Idea-based workspaces).

**Comment by l0rd** [comment]
> @l0rd Question about the configuration persistance.
> This is meant in the scope of single workspace (config is persisted between restarts)?
> Not in the "user" scope (the settings are the same for all Idea-based workspaces of particular user), right?

@rhopp correct, workspace scope, at least as a first iteration.

**Comment by Ohrimenko1988** [comment]
@rhopp @l0rd Looks like persistence doesn't work.
When workspace stopped by dashboard related pod also removed
and if start the same workspace again it will be launched without any previous changes.

**Comment by l0rd** [comment]
> @rhopp @l0rd Looks like persistence doesn't work.
> When workspace stopped by dashboard related pod also removed
> and if start the same workspace again it will be launched without any previous changes.

cc @vzhukovskii

**Comment by vzhukovskii** [comment]
@Ohrimenko1988 @rhopp how are you trying to change the preferences, through the Intellij UI?

**Comment by Ohrimenko1988** [comment]
@vzhukovskii I haven't tried to change preferences.
I created a new project and after that stopped workspace.
After restart the previous project was absent and legal agreement was shown.
After that, I tried to investigate a reason and found that pod deletes already after the workspace stop.

**Comment by l0rd** [comment]
@Ohrimenko1988 pod delete is normal, sources are persisted in a volume.

**Comment by Ohrimenko1988** [comment]
@l0rd 
Yes, thanks to @vzhukovskii explanation I can confirm that project restores if save it to the `/projects` directory.
But additional issue that the "~/IdeaProjects" folder configured by default.
So maybe it worth to mount such folder into the volume if it is impossible to reconfigure Intelij default project folder.

**Comment by vzhukovskii** [comment]
@Ohrimenko1988 Iegal agreement will be shown, there's a plan to hide it in future.

As for preferences:
![prefs](https://user-images.githubusercontent.com/1968177/95470328-566bb180-0989-11eb-954c-18ab548249dc.gif)

As for project restoring:
![projects](https://user-images.githubusercontent.com/1968177/95470361-608db000-0989-11eb-81a6-fc0d820a20b8.gif)

Note, that projects has to be created in `/projects` directory, then they will be persisted. To be sure, that Intellij Idea persisted information about opened projects I can suggest to call `File > Save All`. Maybe some actions are performed to fast.

**Comment by vzhukovskii** [comment]
>So maybe it worth to mount such folder into the volume if it is impossible to reconfigure Intelij default project folder.

We're limited in volume mount amount per container. We can mount only one volume, which is reserved for storing Intellij Idea preferences and caches.

**Comment by Ohrimenko1988** [comment]
Done:
 - Covered functionality: https://gitlab.cee.redhat.com/codeready-workspaces/jenkins-jobs/-/merge_requests/68
 - Uncovered functionality: https://github.com/eclipse/che/issues/18239
