### ISSUE TITLE
Move jobs pushing test images

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18048]
### Is your task related to a problem? Please describe.
Move the jobs for building & pushing test images to the new Jenkins / Centos CI instance.

**Comment by Katka92** [comment]
related issue https://github.com/eclipse/che/issues/17727

**Comment by ScrewTSW** [comment]
* Check `Call to action - ci.centos.org migration` thread for more info
* Contact ci.centos.org guys regarding details about decommission date

**Comment by rhopp** [comment]
Given the che-e2e image is being built together with all the other che images from https://github.com/eclipse/che/tree/master/dockerfiles I hope it's safe to assume the e2e image build will be migrated together with jobs, which are currently building those images:
- nightly: https://ci.centos.org/job/devtools-che-che-nightly/
- release: https://ci.centos.org/job/devtools-che-che-release/
@mkuznyetsov @nickboldt Is there an issue for migrating those jobs we can watch?

**Comment by ScrewTSW** [comment]
c.c.: @mkuznyetsov @nickboldt any updates on this issue?

**Comment by Katka92** [comment]
@mkuznyetsov @nickboldt Guys could you please confirm that you're taking care of that? :wink: Thank you

**Comment by ibuziuk** [comment]
@Katka92 @nickboldt is the issue still relevant? removing the hosted-che label

**Comment by mkuznyetsov** [comment]
Nightly and release CentOS workflows have been moved to GitHub actions (and are running for quite some time now). If that's all of the images that are covered by the issue scope, then I guess it could be resolved

**Comment by Katka92** [comment]
Thank you for your answer :) I'm closing the issue
