### ISSUE TITLE
We need apply code format check for che-operator

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#18042]
### Is your enhancement related to a problem? Please describe.
It would be nice to have code format check for che-operator

**Comment by sleshchenko** [comment]
Hope it can be useful - devworkspace operator has go mod state + go sources format + licenses https://github.com/devfile/devworkspace-operator/blob/master/.github/workflows/pr.yml

**Comment by tolusha** [comment]
Added a github action to validate source code.
