### ISSUE TITLE
Eclipse Che couldn't clone repo with default 'main' branch

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#18044]
### Describe the bug
When cloning a repository in Java Selenium tests from the factories package, the error message "Couldn't clone repo" appears. New test repository has a **main** branch instead of **master**.

http://artifacts.ci.centos.org/devtools/che/che-nigthly-multiuser-stable-test/239/report/site/failsafe-report.html#org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolderTest
![Selection_098](https://user-images.githubusercontent.com/7760565/95070721-3467fa00-0711-11eb-8914-7b0df2d91262.png)

**The reason**: "On Oct. 1, 2020, any new repositories you create will use main as the default branch, instead of master," https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

### How to reproduce
1. Create new GitHub repo with default settings.
2. Create factory URL to create workspace from new repo, for example: https://che.openshift.io/f/?url=https://github.com/dmytro-ndp/TestMainBranch.git
3. Go to factory URL.

**Comment by azatsarynnyy** [comment]
Che Theia reads `branch` value from a Devfile.
Please, check that `master` branch isn't specified your Devfile.

**Comment by benoitf** [comment]
it may be related to factory acceptance
Factory services creates a DevFile with URL https://che.openshift.io/f/?url=https://github.com/dmytro-ndp/TestMainBranch.git

https://github.com/eclipse/che/blob/5343ae4f80d0d93255ad533a21ceb357d08d77cb/wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUrl.java#L38

so might be more wsmaster scope issue.

**Comment by azatsarynnyy** [comment]
This is what Che Workspace API responds when it's asked for a Devfile
![image](https://user-images.githubusercontent.com/1636395/95180788-1bbc1a80-07cb-11eb-8f5f-424f8e67881c.png)

if no Devfile was provided in the project repo.

cc @skabashnyuk

**Comment by azatsarynnyy** [comment]
I'm moving it to `area/wsmater` as Che Theia just relies on what it gets from Che Workspace API.

**Comment by skabashnyuk** [comment]
@azatsarynnyy what are the expectation? Should we remove the branch if it's not set?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy what is the expectation? Should we remove the branch if it's not set?

@skabashnyuk agree, I'd say we should keep it blank in such cases. Then Che Theia will just skip the `--branch` command-line argument when cloning a project. So, the default branch will be used despite what it would be called.
