### ISSUE TITLE
Provide full lifecycle capabilities including creating and restoring backups in the Che operator

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18043]
### Is your enhancement related to a problem? Please describe.

Current Che operator doesn't handle operand (che server) failures. If che server fails to start the operator has no fail-over or fail-back capability.

### Describe the solution you'd like

Support [operator framework](https://operatorframework.io/operator-capabilities/) `LEVEL Ⅲ: FULL LIFECYCLE` capabilties:

- Operator provides the ability to create backups of the Operand
- Operator is able to restore a backup of an Operand
- Operator orchestrates complex re-configuration flows on the Operand
- Operator implements fail-over and fail-back of clustered Operands
- Operator supports add/removing members to a clustered Operand
- Operator enables application-aware scaling of the Operand

In che server context the backup includes the operands (che server, postgres, keycloak, registries) configuration properties and postgres tables.

Subtasks:
- [x] [Initial operator backup/restore support](https://github.com/eclipse/che/issues/18703)
- [ ] Backup of worksapces objects (PVs, secrets, configmaps)

**Comment by nickboldt** [comment]
Downstream, see https://issues.redhat.com/browse/CRW-1288

**Comment by nickboldt** [comment]
Florent had an idea on another issue ( https://github.com/eclipse/che/issues/19291 ) that's worth mentioning here:

> sometimes current images are broken and it's impossible to get back in time.
> Maybe it should be easy to go back in days as well :D like chectl update yesterday / chectl server:deploy
