### ISSUE TITLE
Language Server Protocol: Code Lens

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1804]
The code lens request is sent from the client to the server to compute code lenses for a given text document.
Changed: in 2.0 the request uses CodeLensParams instead of a single uri.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#code-lens

## Code Lens  (depends on #5330)

A code lens represents a command that should be shown along with source text, like the number of references, a way to run tests, etc.

![code lens](https://cloud.githubusercontent.com/assets/578124/17823670/5081c41e-6666-11e6-9d76-6050bb503c3b.png)

**Comment by vparfonov** [comment]
To implement the code lens feature we need to have ability displaying some widget placed 'near' an editor position. My searches for this opportunity in Orion editor was not successful.
But I have found this opportunity in Monaco editor. This one has IContentWidget which can be used to achieve the goal: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icontentwidget.html.
So may be it will be more easily implemented after resolve #5330

**Comment by slemeur** [comment]
Fixed in Che 7
