### ISSUE TITLE
`PluginContext.globalStorage" broken in self-hosting context.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#18056]
### Describe the bug
When running a self-hosting workspace according to https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md, the value of theia.PluginContext.globalStoragePath is wrong: it ends up being  `/home/theia/home/theia-` which is incorrect.

When a plugin is trying to write a file to that location using the vscode.workspace.fs API, the write will fail. The latest version of the ms python extension shows the problem 

### Che version
master

### Steps to reproduce
Start a self-hosting workspace containing the ms python extension. You'll find the following error in the plugin host log:

```
 (FileSystemError): Error: EACCES: permission denied, mkdir '/home/theia'
    at new FileSystemError (/projects/theia/packages/plugin-ext/lib/plugin/types-impl.js:1294:28)
```

**Comment by tsmaeder** [comment]
There are two problems going on here:
1. We assume that the home directory of the container running theia is `/home/theia`, while in the theia-dev container it's '/home/theia-dev'
2. When a plugin uses the vscode file system API, file:// uris will end up writing to the theia back-end container, not the plugin container.

Approaches to fix this would be to share the configuration locations across containers or to rewrite plugin-local uri's

**Comment by apupier** [comment]
I think that sharing the configuration location across containers should allow to support Java Language support for Camel K files https://github.com/eclipse/che/issues/16018
(to put weigh in this option)

**Comment by tsmaeder** [comment]
In the move to multi-root workpaces, @RomanNikitenko added code to handle the case of `/homas/theia-dev`. I'm thinking maybe the front-end should not tell the plugin host where those storage areas are, but each plugin host should determine them on it's own.
