### ISSUE TITLE
Language Server Protocol: Code Lens Resolve

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1805]
The code lens resolve request is sent from the clien to the server to resolve the command for a given code lens item.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#code-lens-resolve

**Comment by RomanNikitenko** [comment]
To implement the code lens feature we need to have ability displaying some widget placed 'near' an editor position. My searches for this opportunity in Orion editor was not successful.
But I have found this opportunity in Monaco editor. This one has IContentWidget which can be used to achieve the goal: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icontentwidget.html.
So may be it will be more easily implemented after resolve https://github.com/eclipse/che/issues/5330

**Comment by slemeur** [comment]
Fixed in Che 7
