### ISSUE TITLE
vscode-shellcheck extension

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18064]
Please make the vscode-shellcheck extension available.

https://github.com/timonwong/vscode-shellcheck (the project is already including a vsix file in the releases)

NB: We will use it for in the IDE validation of shell scripts in the che-docs repository.

**Comment by ericwill** [comment]
We already have it: https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/timonwong/shellcheck
