### ISSUE TITLE
update OLM scripts to support operator-sdk 1.0.x (not 0.10.x from >1 year ago)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18061]
### Is your task related to a problem? Please describe.

Tried to submit a PR for che-operator, got told by PR checker I had to run `./olm/update-nightly-bundle.sh`

Tried to run that, got told I had to install `operator-sdk-v0.10.1-x86_64-linux-gnu`

Not reading carefully, I installed latest release 1.0.1, and it didn't work. So I installed the 0.10.1 release https://github.com/operator-framework/operator-sdk/releases/tag/v0.10.1 from Oct 2019, and it works.

But since we're moving to support OCP 4.6, it's likely we need a newer operator-sdk that knows about index bundles and such.

So...
### Describe the solution you'd like

* update ./olm/update-nightly-bundle.sh so ti can run with operator-sdk 1.0.x 

### Describe alternatives you've considered

* continue to use a year-old 0.x incubating version of operator-sdk

### Additional context

PR I was trying to submit was https://github.com/eclipse/che-operator/pull/484 in order to better support airgapped deployments that rely on mirroring UBI8-minimal image.

**Comment by tolusha** [comment]
Duplicates https://github.com/eclipse/che/issues/17828
