### ISSUE TITLE
Language Server Protocol: Rename feature

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1806]
The rename request is sent from the client to the server to do a workspace wide rename of a symbol.
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#rename

**Comment by evidolob** [comment]
The result of rename is list changes that we should apply to files over workspace, I'm not sure that client(browser) is right place to do that. We need to thick how apply that changes on server(ws-agent).

**Comment by tsmaeder** [comment]
@evidolob From the spec, I can't say if the delta you get back is describing an edit that has happened on the back end or if it's a "todo" for the client. Do you have more info?

**Comment by tsmaeder** [comment]
@evidolob I think you are correct. However, we do have an agent in the workspace that could execute the change. We don't really have to have the exact same protocol between the che ide and the language server api ws-agent and the individual language server implementations. Not sure where filed buffers live in che, though.

**Comment by tsmaeder** [comment]
Note that implementing infrastructure for applying workspace edits would also benefit https://github.com/eclipse/che/issues/3957

**Comment by evidolob** [comment]
This issue depends on https://github.com/eclipse/che/pull/5955 pull request
