### ISSUE TITLE
[chectl] Telemetry: what commands and what k8s targets are people using?

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18069]
### Is your enhancement related to a problem? Please describe.

We'd like to know what aspects of chectl and crwctl are being used by real people. 

For example:
* do people use the `workspace` commands or do they only use `server` to deploy and stop a workspace?
* which OCP and k8s versions are being used as the deployment target?

### Describe the solution you'd like

Some sorta web service that collects anonymous data about which commands and which k8s targets are being used.

### Describe alternatives you've considered

No data = no informed decisions about the future of the tool

### Additional context

Downstream: https://issues.redhat.com/browse/CRW-1266

**Comment by l0rd** [comment]
As mentioned during today call the platform `chectl` sends analytics to may be [segment](https://segment.com/) and we can use [oclif hooks](https://oclif.io/docs/hooks#custom-events).

**Comment by flacatus** [comment]
Created telemetry in upstream and downstream
