### ISSUE TITLE
Protected user preferences

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#18068]
### Is your task related to a problem? Please describe.
As far as we store some internal data in user preferences (workspace activity time, namespace assigned to user and other stuff), it seems to be useful to have some protection from modifying those settings.

### Describe the solution you'd like
Create validators on update/delete preferences operations similar to how it is done on workspace attributes.

**Comment by skabashnyuk** [comment]
The general direction is to use k8s objects, I don't think it makes sense to improve the User preferences API.
