### ISSUE TITLE
Can't log into Eclipse Che because it's impossible to get keycloak settings

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18075]
### Describe the bug
It was impossible to log into Eclipse Che deployed to minikube:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2379/
![screenshot-Open_workspace](https://user-images.githubusercontent.com/1197777/95434165-9d41b300-0959-11eb-8bc8-56117c136a13.png)

### Recent changes
https://github.com/eclipse/che-dashboard/pull/97
https://github.com/eclipse/che/commit/b399be7c16167ab103d53471ae3d0399db00ef5b

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: build from master branch

### Steps to reproduce
1. Build Eclipse Che from master branch
2. Deploy Eclipse Che to minikube by command:
```
chectl server:start --k8spodreadytimeout=180000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=custom-resource-patch.yaml --chenamespace=eclipse-che
```
where custom-resource-patch.yaml:
```
spec:
  server:
    cheImage: 'maxura/che-server'
    cheImageTag: 'master'
  auth:
    updateAdminPassword: false
``` 

3. Log into Eclipse Che

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl/0.0.20201007-next.4ecde0d linux-x64 **node-v10.22.1**
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

### Eclipse Che Logs
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2379/artifact/logs-and-configs/che-logs/

**Comment by sleshchenko** [comment]
Possible it's caused by https://github.com/eclipse/che-dashboard/pull/97 @akurinnoy please take a look
We still don't have any PR tests that would be able to catch such issues for che-dashboard https://github.com/eclipse/che/issues/16434 =(

**Comment by skabashnyuk** [comment]
Same thing after pulling latest dashboard image.
Potentially related to https://github.com/eclipse/che-dashboard/pull/97

**Comment by akurinnoy** [comment]
If that PR is the case I'll provide the fix ASAP

**Comment by ibuziuk** [comment]
@akurinnoy looks like this is smth we also observe on Hosted Che after trying to rollout 7.20.0-SNAPSHOT on dev cluster - https://github.com/redhat-developer/rh-che/pull/1969
