### ISSUE TITLE
Move devfile and plugin registry jobs to GitHub action

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18072]
## Nightly
Currently there are nightly build jobs running for both the plugin registry and devfile registry. These can be moved to GH action instead of using centos-ci.

Relevant jobs:
* devtools-che-plugin-registry-nightly
* devtools-che-devfile-registry-nightly

## Release
Both the plugin registry and devfile registry have release jobs on centos-ci as well. These could likely be moved to GH action, and can be triggered any time the `VERSION` file is changed.

Relevant jobs:
* devtools-che-plugin-registry-release
* devtools-che-devfile-registry-release

On the release side of things I'm not entirely sure how the centos-ci jobs were triggered, but I'd be willing to do the GH action replacement if @nickboldt / @mkuznyetsov if they can give me their use cases.

**Comment by benoitf** [comment]
I think release jobs should be done 'on demand' without any git change. 
It's now possible with GH action

**Comment by ericwill** [comment]
> I think release jobs should be done 'on demand' without any git change.
> It's now possible with GH action

Yes that works too. I was thinking only because the automated release PR bumps the `VERSION` file, so it could be based on that as well.

**Comment by benoitf** [comment]
@ericwill can be closed no ?

**Comment by ericwill** [comment]
> @ericwill can be closed no ?

No, there are still the release jobs that need to be migrated (happening this sprint).

**Comment by nickboldt** [comment]
Given we used the new GH actions for 7.24, I suspect we can close this.

https://github.com/eclipse/che-devfile-registry/actions?query=workflow%3A%22Release+Che+Devfile+Registry%22 (7.24.0 - 7.24.2)

https://github.com/eclipse/che-plugin-registry/actions?query=workflow%3A%22Release+Che+Plugin+Registry%22 (7.24 and 7.24.1 only so far)
