### ISSUE TITLE
Che Theia release script creates malformed JSON

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#18078]
### Describe the bug
During the latest release of che-theia, CI centos job failed with the following output
https://ci.centos.org/job/devtools-che-theia-che-release/49/

It appears that one of the package.json files was incorrectly processed by make-release.sh and produced an invalid JSON.

### Che version
releasing 7.20.0 from master branch

### Steps to reproduce
run ./make-release.sh --version 7.20.0 --repo git@github.com:eclipse/che-theia --trigger-release

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: Centos CI/ local machine

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse/che-theia/pull/874
Thanks @mkuznyetsov!
