### ISSUE TITLE
Integrate JPA components/tools with Che Infrastructure

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#1807]
Things to do:
- Set up h2 database as a replacement for local storages
- Bind _Jpa_ based dao implementations instead of _Local_ ones
- Ensure che works as expected

**Comment by akorneta** [comment]
We almost start che with relation databases, and we need to consider configuring the startup options. One of the available option is the base directory for the database so we propose add parameter e.g. `CHE_DB_LOCATION` to `che.sh` script and default value for it will be `${CHE_HOME}/db/`, the database name can be configured in `server.xml` file at section resources.
@TylerJewell, @skabashnyuk maybe you have something to add?

**Comment by TylerJewell** [comment]
@skabashnyuk @akorneta I like what you are suggesting.

A few things:
1: Location at `${CHE_HOME}/db/`.
2: Set che.properties variable as `che.database` to be inline with goals for #2015.
3. This would then have the environment variable be `CHE_DATABASE` to be consistent with #2014 where we want the environment variable for each property to be identical to the name of the property.

@garagatyi - just FYI.

**Comment by skabashnyuk** [comment]
@skabashnyuk @akorneta I like what you are suggesting.

> A few things:
> 
> 1: Location at ${CHE_HOME}/db/.

default value - ok

> 2: Set che.properties variable as che.database to be inline with goals for #2015. 

we can't have this property configured in che.properties. Since we need to have system variable before starting application server

> 3: This would then have the environment variable be CHE_DATABASE to be consistent with #2014 >where we want the environment variable for each property to be identical to the name of the >property.   

CHE_DATABASE - ok

I think we can propose PR so it will be more clear what we want to do.
