### ISSUE TITLE
Add new flags to chectl server:start (or server:deploy) to support more OperatorHub UI options

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18071]
### Is your enhancement related to a problem? Please describe.

We should add some new flags to chectl / crwctl to mimic the operatorhub UI experience :
- [x] Subscription: automated/manual (default automated)
- [x] Monitoring: true/false (default true)
- [x]  Use suggested namespace: true/false (default true)

### Describe the solution you'd like

Add more flags, with default values that align to the UI experience so the CLI behaves more closely to the UI.

### Describe alternatives you've considered

Docs explaining how the UI provides more options so if you're restricted to using the CLI due to your deployment env, you'll need to deploy and then apply `oc patch` updates to toggle behaviours above on or off.

### Additional context

Downstream: https://issues.redhat.com/browse/CRW-1266

**Comment by flacatus** [comment]
@nickboldt To enable cluster-monitoring via cli it is not easy. When we install CodeReadWorkspace from operatorHub UI, Openshift console create `openshift-workspaces` namespace with some labels like openshift.io/cluster-monitoring: 'true'  and also add some prometheus role/rolebinding to the namespace.
cc @tolusha @ibuziuk

**Comment by flacatus** [comment]
Pending to merge: https://github.com/redhat-developer/codeready-workspaces-chectl/pull/48
