### ISSUE TITLE
API Compatibility Report shows wrong Results

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#18085]
When looking at https://che-incubator.github.io/vscode-theia-comparator/status.html, I noticed that "registerCompletionItemProvider" is marked as "not implemented". However, that API has been present for a long time.
I suspect that a change in the definition of the type "CompletionItemProvider" causes this problem: we should analyze whether this represents real breakage and alternatively fix the tool or the API. FWIW, the change in CompletionItemProvider was:

```
export interface CompletionItemProvider<T extends CompletionItem = CompletionItem> {
```
from before: 
```
export interface CompletionItemProvider<T = CompletionItem> {
```

**Comment by ericwill** [comment]
cc @benoitf

**Comment by benoitf** [comment]
I saw that this morning, I think the tool is pretty dumb but would be better to still do the change in Theia API.

**Comment by benoitf** [comment]
I can take action on that

**Comment by benoitf** [comment]
https://github.com/eclipse-theia/theia/pull/8617

**Comment by benoitf** [comment]
fixed
