### ISSUE TITLE
Add c# project type

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1808]
Provide ability create C# Project Type. Code intellisense will be covered by LSP implementation for C#

**Comment by ghost** [comment]
@vparfonov @tolusha Isn't there a template already for .NET Core on eclipse che? (I have worked on the codenvy template for .NET Core). I assumed the same templates are used for both and therefore should allow easy addition of a c# project type.

If so the creation of a project is simply

```
mkdir folder

cd folder

dotnet new

dotnet restore

dotnet run
```

Just switch the `dotnet new` for `dotnet new -t web` for asp.net.

**Comment by TylerJewell** [comment]
Stacks, templates and project types are different things.  We have stacks and templates but not a project type.  The pt will allow for automatic injection of intellisense.

**Comment by TylerJewell** [comment]
Merged into M2
