### ISSUE TITLE
Create JPA based SshDao implementation

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#1810]
Todo:
- Create TCK(Existing MongoDB based tests can be refactored).
- Create JPA based implementation which passes all the TCKs

Data object structure

``` java
public class UserSshPair {
    private String owner;
    private String service;
    private String name;
    private String publicKey;
    private String privateKey;
}
```

**Comment by mkuznyetsov** [comment]
https://github.com/eclipse/che/pull/1975
