### ISSUE TITLE
Unable to deploy Eclipse Che nightly >7.21.0 on OpenShift 4.6 using olm installer (chectl times out waiting for subscription to be ready on fresh OCP 4.6)

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18105]
### Che version
 - [x] nightly

### Steps to reproduce
Deploy Eclipse Che on OpenShift 4.6 using chectl. See also https://github.com/eclipse/che/issues/18267

### Expected behavior
Eclipse Che nightly version is successfully deployed

### Runtime
   - [x] Openshift 4.6 (include output of `oc version`)

### Screenshots
![Untitled](https://user-images.githubusercontent.com/1640675/95841740-618a5d00-0d4e-11eb-8f40-12a1997cd0a0.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output) 
```
$ chectl server:start --platform openshift
› Current Kubernetes context: 'default/api-ci-ln-x6hf2yb-f76d1-origin-ci-int-gce-dev-openshift-com:6443/kube:admin'
› Installer type is set to: 'olm'
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
    ✔ Check OpenShift version: 4.x
    ✔ Check Kubernetes version: Unknown.
  ✔ Verify Openshift oauth....done.
  ✔ Start following logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
  ❯ 🏃‍  Running Olm installaion Eclipse Che
    ✔ Check if OLM is pre-installed on the platform...done.
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...done.
    ✔ Create operator group...created new one.
    ✔ Configure context information...done.
    ✔ Create nightly index CatalogSource in the namespace che
    ✔ Create operator subscription...created new one.
    ⠋ Wait while subscription is ready
      Wait while operator installed
      Create the Custom Resource of type checlusters.org.eclipse.che in the namespace che
```
     * provide an output of `chectl version` command
```
chectl version
chectl/0.0.20201012-next.a9bbea6 linux-x64 node-v10.22.1
```

### Environment
   - [x] my computer
       - [x] Linux

**Comment by l0rd** [comment]
Made it a blocker since whoever tries `chectl server:deploy` on a fresh OCP cluster today will get this error.

**Comment by l0rd** [comment]
The workaround is to specify `--installer operator`

**Comment by nickboldt** [comment]
Couple questions:

* Can you try a newer version? 0.0.20201012 is more than a month old.
* Could we build chectl with node 12? why are we still on v10.22.1 ? crwctl is on node 12... https://github.com/redhat-developer/codeready-workspaces-chectl/commit/2231a98fe958436016fcfdcb53ddf7fa6c153695

**Comment by nickboldt** [comment]
So the log just stops with `Create the Custom Resource of type checlusters.org.eclipse.che in the namespace che` ? Is there nothing more?

**Comment by l0rd** [comment]
@nickboldt I have tested with nightly chectl version and the problem is still there https://github.com/eclipse/che/issues/18267
