### ISSUE TITLE
Quarkus devfile test failing to click on workspace button

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18104]
### Describe the bug
Devfile tests are failing to click on the proper workspace button when on the `Getting started` page. 
Mostly happens for Quarkus devfile:

```
  4) Quarkus Tools test
       Create Quarkus Tools
         Open 'New Workspace' page:
     TimeoutError: Exceeded maximum clicking attempts, the 'By(xpath, //div[contains(@devfile, 'devfile')]/div/b[contains(text(), 'Quarkus Tools')])' element is not clickable
```

Log: https://ci.centos.org/job/devtools-che-nightly-devfiles-test/248/console
Artifacts: http://artifacts.ci.centos.org/devtools/che/che-devfile-test/248/report/

### Che version

 - [ ] latest
 - [x] nightly
 - [x] other: also seen in 7.20.0

### Steps to reproduce
Run devfile tests multiple times to observe the issue.

### Expected behavior
Test should click on the correct button.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/95841157-541ca500-0d45-11eb-9692-a6def69a65c4.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by ibuziuk** [comment]
Looks like quarkus specific - https://ci.centos.org/job/devtools-saas-openshiftio-pre-release-test/36/console (9 failing)

**Comment by Katka92** [comment]
The test is passing. Closing.
