### ISSUE TITLE
Dashboard load devfile doesn’t work if providing the github doesn't have `master` as default branch

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18117]
### Describe the bug
Same bug we have with the factory https://github.com/eclipse/che/issues/18116  but from the dashboard 

![Selection_023](https://user-images.githubusercontent.com/650571/96102769-2ff0cd80-0ed7-11eb-8d9a-33572a396fb0.png)

**Comment by sleshchenko** [comment]
I believe it should be fixed by https://github.com/eclipse/che/issues/18116 since Dashboard just reuses Che API to resolve devfile content.

**Comment by sleshchenko** [comment]
Tried with `https://github.com/eclipse-che/che-dashboard` and it works fine:
![Screenshot_20210429_150623](https://user-images.githubusercontent.com/5887312/116548142-7ac6b580-a8fc-11eb-8460-96364a867d7b.png)
