### ISSUE TITLE
Factory URL: devfile.yaml is not detected if the default branch is not master 

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18116]
### Describe the bug
For Github projects, when using `https://<che-host>/factory?url=https://github.com/sunix/scratch-gui` where `scratch-gui` has the a default branch `develop` and not `master`, Che factory can't find the devfile.yaml that is located in the root folder of the project in the default branch `develop`.
This is important to fix having that we will have less and less default branch called `master` in the near futur.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
Should load the devfile and clone the 3 repos + include all the components and commands defined in the devfile

**Comment by azatsarynnyy** [comment]
It seems a duplicate of https://github.com/eclipse/che/issues/18044 that was fixed by https://github.com/eclipse/che/pull/18066

**Comment by sunix** [comment]
ok I am closing for now
