### ISSUE TITLE
failure to deploy che  when using the external Db 

### ISSUE THREAD

**Issue by whafra** [eclipse-che/che#18124]
reference : https://www.eclipse.org/che/docs/che-7/administration-guide/external-database-setup/

the enviroment (air-gap ):
kubernetes version:v1.18.6
eclipse-che version: 7.19.0
install cmd:
chectl server:start --installer=operator --platform k8s  --multiuser  .... 

I have deplyed the eclipse-che successfully in air-gap enviroment  before. It is amazing!
At  present ,   i  tried to use the external db (  refer to 
https://www.eclipse.org/che/docs/che-7/administration-guide/external-database-setup/ ),the error occured .

I have deployed the postgresql:13.0 and pgadmin4:4.26 in k8s ,but when install che ,the status of  keycloak pod  is not normal and the process is stucked .
i checked  the log of pod ,and found the following information.

------[warning ---marked with yellow color ]---------
00:55:54,261 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnect                                                                             ionProviderFactory] (ServerService Thread Pool -- 61) Node name: keycloak-695885                                                                             7bb6-28k5g, Site name: null
00:55:54,631 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool]                                                                              (ServerService Thread Pool -- 61) IJ000604: Throwable while attempting to get a                                                                              new connection: null: javax.resource.ResourceException: IJ031084: Unable to crea                                                                             te connection
.....

----[error ---marked with the red color]-----
00:55:54,648 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 61                                                                             ) MSC000001: Failed to start service jboss.deployment.unit."keycloak-server.war"                                                                             .undertow-deployment: org.jboss.msc.service.StartException in service jboss.depl                                                                             oyment.unit."keycloak-server.war".undertow-deployment: java.lang.RuntimeExceptio                                                                             n: RESTEASY003325: Failed to construct public org.keycloak.services.resources.Ke                                                                             ycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatche                                                                             r)
------------------------just the delimiter------------------
It looked like that  the connection between the keycloak and postgresql is unormal. But i could not find  a clue..
and also,  i am confused about the "Configuring Che to work with an external PostgreSQL " of  the documentation .
Since  the che-server db and keycloak-db are created  in pgsql (refer to the step 2 and 3) , why in the  step 4 , the modification guidance of che-spec  ，the keycloak-db name is not mentioned. 

thanks for you concern and look  forward to  your advice.

**Comment by tolusha** [comment]
Where is external DB is deployed? I guess it is not accessible from the keycloak pod.

>  why in the step 4 , the modification guidance of che-spec ，the keycloak-db name is not mentioned.

The keycloak-db is hardcoded to `keycloak` and it isn't configurable.

**Comment by tolusha** [comment]
I guess I see the problem. 
`<identity-database>` could you try with `keycloak `?

**Comment by whafra** [comment]
@tolusha 
thanks for your reply .
I tried your method and created  the  <identity-database> using the name  "keycloak" , unfortunately ...the same error .....

**Comment by tolusha** [comment]
@whafra 
Could you use 'keyckoak' for `<identity-database-user>` as well, pls ?
If keycloak fail to connect to DB then provide the full keycloak pod log.

**Comment by whafra** [comment]
@tolusha 
Yes ,i created the db using name "keycloak" and refer to the  documentation ( https://www.eclipse.org/che/docs/che-7/administration-guide/external-database-setup/)  ,howerver,  the error was  just the same  to the previous post.

**Comment by tolusha** [comment]
@whafra 
what about `<identity-database-user>` did you `keycloak` also ?

**Comment by whafra** [comment]
@tolusha  
i tried keycloak as <identity-database>  and keycloak as  <identity-database-user> , che  was deployed successfully !!
thank you very much ~

**Comment by whafra** [comment]
i tried keycloak as <identity-database>   and keycloak as <identity-database-user> , che was deployed successfully !!
thank you very much ~

**Comment by whafra** [comment]
i tried keycloak as  "identity-database" and keycloak as "identity-database-user" , che was deployed successfully !!
thank you very much ~

**Comment by tolusha** [comment]
@whafra 
Thank you for checking. I will update the doc.

**Comment by tolusha** [comment]
Some notes from the eclipse-che public channel
https://mattermost.eclipse.org/eclipse/pl/xdyicg38oiyfjdksmod41ix75o
