### ISSUE TITLE
Eclipse che on kubernetes download latest version even if a version is specified

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#18127]
We use eclipse che with hosted kubernetes.

This is our installation script:
`chectl server:start --platform=k8s --installer=helm --multiuser --domain=${MAAP_DOMAIN} --k8spodwaittimeout=400000 --postgres-pvc-storage-class-name="sata-iac-0b" --workspace-pvc-storage-class-name="sata-iac-0b" --templates=$TEMPLATE_PATH`

we have a helm chart with values
```
cheWorkspaceHttpProxy: ""
cheWorkspaceHttpsProxy: ""
cheWorkspaceNoProxy: ""
**cheImage: quay.io/eclipse/che-server:7.18.0**
cheImagePullPolicy: Always
cheKeycloakRealm: "che"
cheKeycloakClientId: "che-public"
```

Today, when re deploying the che in our K8S we noticed that the che can't start. In the log we have 

```
) Error injecting constructor, org.eclipse.che.api.workspace.server.spi.InfrastructureException: Neither KUBERNETES_NAMESPACE nor POD_NAMESPACE is defined. Unable to determine Che installation location
  at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.CheNamespace.<init>(CheNamespace.java:54)
  at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.CheNamespace.class(CheNamespace.java:54)
  while locating org.eclipse.che.workspace.infrastructure.kubernetes.namespace.CheNamespace

```
When we compare the actual log with the log when che is deploying correctly we noticed this difference
new log
`2020-10-16 13:01:48,674[ost-startStop-1]  [INFO ] [o.e.c.a.c.u.ApiInfoLogInformer 36]   - Eclipse Che Api Core: Build info '7.19.2' scmRevision '78c092610a43c61dae96fd4cc7fa2f77bd30b270' implementationVersion '7.19.2'`
old log:
`2020-10-14 08:45:21,279[ost-startStop-1]  [INFO ] [o.e.c.a.c.u.ApiInfoLogInformer 36]   - Eclipse Che Api Core: Build info '7.18.2' scmRevision '2d066a201ee829bdc5bfa1d29fb37cc5ba24ae7c' implementationVersion '7.18.2'`

Eclipse che downloaded, we don't know how the version 7.19.2.

When We updated the deployment
`kc edit deployment -n che che ` and replace the image version by 
`image: quay.io/eclipse/che-server:7.18.2` everything the pod restarted properly. 

How could we do to correctly set the che image to be used ?

**Comment by tolusha** [comment]
@KOSSOKO 
The problem comes from the fact that you've used chectl 7.19.2 version which deployed the corresponding Eclipse Che 7.19.2 version. It is possible to override che-server image by using `--cheimage` flag.

**Comment by KOSSOKO** [comment]
@tolusha thanks. I will try it today.

**Comment by KOSSOKO** [comment]
ok, after trying the solution suggested by @tolusha, it works perfectly. So even if you use chectl with helm charts with values, it is not used at all. So add the version in the chectl command to have the version you need.

`chectl server:start --platform=k8s --installer=helm --multiuser --domain=${MAAP_DOMAIN} --cheimage=quay.io/eclipse/che-server:7.18.2 --k8spodwaittimeout=400000 --postgres-pvc-storage-class-name="sata-iac-0b" --workspace-pvc-storage-class-name="sata-iac-0b" --templates=$TEMPLATE_PATH`
