### ISSUE TITLE
vsix Plugin downloads fail (Ubuntu 20.04/microk8s/chectl)

### ISSUE THREAD

**Issue by mutech** [eclipse-che/che#18128]
### Describe the bug

Running workspaces fails because of download errors for vsix plugins (independent of the plugin/workspace type).

I installed two instances, one on macos/docker for macos and one on ubuntu using microk8s. The macos installation works fine, the Ubuntu installation consistently fails.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

- Install Ubuntu 20.04 (fresh installation in my case)
- Install microk8s using snap
- Prepare microk8s
  - enable storage, dns, helm
- Install chectl via curl

I tried three installation paths (deleting instance in between installations):
- `chectl server:start --installer=helm --platform=microk8s`
- `chectl server:start --installer=helm --platform=microk8s --multiuser`
- `chectl server:start --platform=microk8s`

All succeed and I can eventually access the dashboard and start a workspace which fails to download plugins after repeated tries:

```
Processing plugin extension 1/1
  Installing plugin extension 1/1
    Downloading plugin from https://download.jboss.org/...
failed to download plugin from ...
```

### Expected behavior

The workspace starts without failing to download vsix plugins.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: microk8s (v1.19.2)

### Installation method
   - [x] chectl
     * chectl server:start --platform=microk8s
     * chectl/7.20.0 linux-x64 node-v10.22.1
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context
I found few issues describing similar effects as a result of mitm ssl-proxies. I'm not using any proxies (not that I know off, I'm a k8s noob, so maybe microk8s is doing stuff I wouldn't expect).

**Comment by gattytto** [comment]
@mutech can you see an error code for the download fail? like 409 or 404

**Comment by mutech** [comment]
@gattytto

1. No, didn't find any more specific info
2. Happens to all downloads
3. Will check and update this issue later

Meanwhile I got the workspaces to start up by changing the default dns-server in microk8s (which is using 8.8.8.8/8.8.4.4 by default) to my local dns, so your tip #3 is probably the cause, at least the problem is related to DNS.

Now however I have the problem that from within the workspace, I cannot connect to any web services. Concretely, checking out the demo projects fails (theia). When opening a shell `wget anything` fails (remains in state "connecting to <ip-addr>" - so DNS is working now). 

I don't know if this is still in scope of this ticket. Should I open another one?

**Comment by gattytto** [comment]
@mutech it seems like your issue is not in "che" itself but in the previous layer which is the kubernetes single node cluster. You may want to check about similar issues in microk8s wikis and their gh repo to see if you see any fitting scenario. In the meantime maybe you can start a simple container (like ubuntu) that includes networking tools into your cluster to check out what's going on.

**Comment by ericwill** [comment]
microk8s support is available but needs to be improved -- there is an issue open for this already: https://github.com/eclipse/che/issues/14455

**Comment by mutech** [comment]
My bad, it was a firewall issue. Apparently microk8s, even though doing quite a bit of firewall massaging is not by default configuring it to let traffic from pods pass out. Sorry for steering up waves here, but maybe you can drop a hint in your microk8s installation notes to help the next guy stumbling over this: https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#2-deploying-microk8s
