### ISSUE TITLE
che-server installation successful but its not accessible.

### ISSUE THREAD

**Issue by aaraodeo** [eclipse-che/che#18129]
### Describe the bug
Che-server installation successful but its not accessible in and out of k8s cluster

### Che version
 - [*] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

chectl server:start --cheimage=quay.io/eclipse/che-server:7.20.0 --installer=helm --platform=k8s --skip-kubernetes-health-check --domain=10.242.131.161.nip.io

See Additional context

### Expected behavior
Che-server installs fine but its not accessible in and out of the k8s cluster

### Runtime
   - [*] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10+1.0.15.el7", GitCommit:"79ee15c532540dbf0c46bc26c26c93d0033393b8", GitTreeState:"clean", BuildDate:"2020-08-18T13:07:19Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10+1.0.15.el7", GitCommit:"79ee15c532540dbf0c46bc26c26c93d0033393b8", GitTreeState:"clean", BuildDate:"2020-08-18T13:07:19Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Screenshots
N/A

### Installation method
   - [* ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know
   
chectl version
chectl/7.20.0 linux-x64 node-v10.22.1

helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

### Environment
   - [ ] my computer
       - [ ] Windows
       - [* ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
Installation Log:
› Current Kubernetes context: 'kubernetes-admin@kubernetes'
  ↓ Verify Kubernetes API [skipped]
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ↓ Verify remote kubernetes status [skipped]
    ✔ Check Kubernetes version: Found v1.12.10+1.0.15.el7.
    ✔ Verify domain is set...set to 10.242.131.161.nip.io.
    ↓ Check if cluster accessible [skipped]
  ✔ Start following logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
  ✔ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.3.4+ga61ce56
    ✔ Create Namespace (che)...does already exist.
    ✔ Check Eclipse Che TLS certificate...TLS certificate secret found
    ✔ Check Cluster Role Binding...done.
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Eclipse Che Helm Chart...done.
  ✔ ✅  Post installation checklist
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Eclipse Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Eclipse Che status check
  ✔ Prepare post installation output...done
  ✔ Show important messages
    ✔ Eclipse Che 7.20.0 has successfully installed.
    ✔ Users can access the Dashboard at   : https://che-che.10.242.131.161.nip.io
    ✔ Plugins can be viewed at            : https://plugin-registry-che.10.242.131.161.nip.io/v3
    ✔ Devfiles can be viewed at           : https://devfile-registry-che.10.242.131.161.nip.io
    ✔ Product documentation is at         : https://www.eclipse.org/che/docs/
Command server:start has completed successfully in 00:50.

But the url https://che-che.10.242.131.161.nip.io is not working in web browser of my laptop outside k8s cluster.
Its throws "Unable to Connect Error Page".

Also its not accessible inside k8s cluster on the master node of k8s cluster.
curl -k -v https://che-che.10.242.131.161.nip.io
* About to connect() to che-che.10.242.131.161.nip.io port 443 (#0)
*   Trying 10.242.131.161...
* Connection refused
* Failed connect to che-che.10.242.131.161.nip.io:443; Connection refused
* Closing connection 0

 curl -k -v https://che-che.10.242.131.161.nip.io --no-proxy che-che.10.242.131.161.nip.io
* About to connect() to proxy che-che.10.242.131.161.nip.io port 1080 (#0)
*   Trying 10.242.131.161...
* Connection refused
* Failed connect to che-che.10.242.131.161.nip.io:1080; Connection refused
* Closing connection 0
curl: (7) Failed connect to che-che.10.242.131.161.nip.io:1080; Connection refused

Note: I have configured a http proxy to connect to internet from my linux vm.

**Comment by tolusha** [comment]
If che-server started successfully (not errors in the pod) then it isn't the issue with che itself.
For some reason che isn't available out side the cluster
maybe related to https://github.com/eclipse/che/issues/16996
