### ISSUE TITLE
All java devfiles don't have the debug port as endpoint with 'public=false' attribute

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18138]
### Describe the bug
Java devfiles don't have the debug port (usually 5005) flagged as a `public/false` attribute
So there is annoying prompt about the port 5005.
devfiles should set this value to public/false in order to prevent that.

note: it's different of https://github.com/eclipse/che/issues/17993 as for the other issue it's to update port-plugin, not the devfiles.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Start java/quarkus stacks and see the popup about the debug port being listening.

### Expected behavior
Endpoint that should not be public should be declared in the devfile.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by vitaliy-guliy** [comment]
@benoitf property `public: false` will be taken into account only after merging your changes (https://github.com/eclipse/che-theia/pull/875) to port plugin, right?

**Comment by benoitf** [comment]
yes, correct
I mean, right now even if endpoints have public:false it will still prompt for a redirect
after port plug-in change, it will be handled

**Comment by benoitf** [comment]
@vitaliy-guliy if you want to review https://github.com/eclipse/che-theia/pull/875 by validating your devfiles changes ;-)

**Comment by vitaliy-guliy** [comment]
@benoitf yes, I will build Che-Theia from your branch to test changes

**Comment by benoitf** [comment]
@vitaliy-guliy you can use images built by the ci.

**Comment by vitaliy-guliy** [comment]
@benoitf It's even easier
