### ISSUE TITLE
Installing che with a separate postgressql instance.

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18132]
Hi Team,
I am trying to install eclipse che with a separate postgresql instance.
Can you please provide some pointers on how to achieve this.
I looked at this document - https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-the-che-installation/#checluster-custom-resource-database-settings_configuring-the-che-installation

I understand that I have to set these values somewhere in a custom resource file. Where can I find this file ? 
Or I have to create it from scratch, if yes can you please point me to a sample custom resource file.

Once the file is created how can I run it using chectl ?

**Comment by tolusha** [comment]
Probably you are looking for this article
https://www.eclipse.org/che/docs/che-7/administration-guide/external-database-setup/

For the time being we have an issue with that 
https://github.com/eclipse/che/issues/18124

**Comment by chopraaakash91** [comment]
I am using --installer=helm.. and the issue talks about  using --installer= operator
is this an issue for both type of installers or just operator?

**Comment by tolusha** [comment]
@chopraaakash91 
We don't have instruction how to use externalDB with `--installer helm` 
So it is the issue with `--instaler operator`.

Closed in favor of https://github.com/eclipse/che/issues/18132
