### ISSUE TITLE
Request runTask failed with message: connection is closed

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#18134]
### Describe the bug
After using a workspace for a long time it's impossible to run a task.
The error is: ```Request runTask failed with message: connection is closed```

The problem was reported by solution architect:
> I am using RHPDS to provision my OCP 4.5 cluster and I am running CRW2.3 on it. 
In general it is when the workspace is running for a period of time (hours?) that the problem appears.

> With CRW2.4, refreshing the full CRW page fixes the problem.

> In fact, I have just got the same issue where I need to restart the workspace to fix it... 
One developer over 13...

> The ratio is better but the problem is still there

### Che version
RHPDS to provision my OCP 4.5 cluster, CRW2.3, CRW2.4

### Steps to reproduce
Run a task for a long running workspace

### Expected behavior
Task is running

### Additional context
Task plugin uses ```vscode-ws-jsonrpc```, so the issue potentially may be related to https://github.com/TypeFox/vscode-ws-jsonrpc/issues/24

**Comment by RomanNikitenko** [comment]
In Eclipse Che channel similar problem was reported:
```
I am facing an issue with multi-user eclipse/che 
when I am using che-theia with Java maven workspace 
mvn build and other tasks are working fine. 
I have set workspace idle timeout as well to 30 min 
but if I leave the screen idle for sometime(<30 mins) and then click on any of the tasks its failing with Request timeout. 
I am using 7.17.0 version of che.
```
It contains some details and can help to reproduce the issue.

**Comment by chaitu454** [comment]
I have reported this issue in Eclipse Che channel . To further add on this in one of other docs its been referred to be issue with nginx rebound. https://github.com/eclipse/che/issues/9943 . So unable to figure out which one of these are the actual reason for this behaviour.

**Comment by wcho** [comment]
I am also experiencing this issue.
/remove-lifecycle stale

**Comment by RomanNikitenko** [comment]
> I am also experiencing this issue.

@wcho 
What version of Che or CRW are you using?

**Comment by wcho** [comment]
We deployed 7.28.0 in local k8s cluster using chectl.
