### ISSUE TITLE
Route host too long when using che-workspace-<userid> in namespace template

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18146]
### Describe the bug

When using `che-workspace-<userid>` in namespace template, the Route host gets too long so it fails to create.
```
[~/dev/che] (master ✔) λ oc get routes -n che-workspace-431b8043-305d-4eb6-8817-1b8608e97867 
NAME            HOST/PORT     PATH   SERVICES                      PORT           TERMINATION     WILDCARD
route560f4mr6   InvalidHost          servery26gekm3-jwtproxy       server-4402    edge/Redirect   None
routebd74dqg7   InvalidHost          servery26gekm3-jwtproxy       server-4401    edge/Redirect   None
routejb09ya7s   InvalidHost          servery26gekm3-jwtproxy       server-4400    edge/Redirect   None
routekseo9ri2   InvalidHost          server7re7o8uy-theia-ide5ao   server-3130    edge/Redirect   None
routel3hrr3qa   InvalidHost          server7re7o8uy-theia-ide5ao   server-13133   edge/Redirect   None
routeof4j4gpo   InvalidHost          server7re7o8uy-theia-ide5ao   server-13131   edge/Redirect   None
routew0sqopkf   InvalidHost          server7re7o8uy-theia-ide5ao   server-13132   edge/Redirect   None
```

```
[~/dev/che] (master ✔) λ oc describe route route560f4mr6 -n che-workspace-431b8043-305d-4eb6-8817-1b8608e97867
Name:			route560f4mr6
Namespace:		che-workspace-431b8043-305d-4eb6-8817-1b8608e97867
Created:		46 seconds ago
Labels:			che.original_name=routeh8q1eo2u
			che.workspace_id=workspaceehmlj928r7rxcdv0
Annotations:		openshift.io/host.generated=true
			org.eclipse.che.machine.name=theia-ide5ao
			org.eclipse.che.server.theia.attributes={"cookiesAuthEnabled":"true","internal":"false","secure":"true","type":"ide","discoverable":"false"}
			org.eclipse.che.server.theia.port=3100/tcp
			org.eclipse.che.server.theia.protocol=https
Requested Host:		route560f4mr6-che-workspace-431b8043-305d-4eb6-8817-1b8608e97867.apps-crc.testing
			  rejected by router default:  (host apps-crc.testing)InvalidHost (46 seconds ago)
			    host name validation errors: spec.host: Invalid value: "route560f4mr6-che-workspace-431b8043-305d-4eb6-8817-1b8608e97867.apps-crc.testing": must be no more than 63 characters
Path:			<none>
TLS Termination:	edge
Insecure Policy:	Redirect
Endpoint Port:		server-4402

Service:	servery26gekm3-jwtproxy
Weight:		100 (100%)
Endpoints:	10.116.0.146:4401, 10.116.0.146:4402, 10.116.0.146:440
```

### Che version

 - [x] latest

### Steps to reproduce
1. deploy che with `<userid>` placeholder in namespace template. you can use this operator patch:
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    workspaceNamespaceDefault: che-workspace-<userid>
```
2. start any workspace
2. start will hang and eventually will fail with `Error: Failed to run the workspace: "Server 'theia' in container 'theia-ide5ao' not available."`
2. Check some route in that new namespace, you'll see `InvalidHost`

### Expected behavior

We should create valid route host (just cut it down?).

### Runtime
   - [x] Openshift (include output of `oc version`)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

**Comment by RomanNikitenko** [comment]
@sparkoo I'm not sure about area for the issue, please correct me if I'm wrong.

**Comment by sparkoo** [comment]
> @sparkoo I'm not sure about area for the issue, please correct me if I'm wrong.

it's wsmaster, I've fixed the label

**Comment by sparkoo** [comment]
We don't set Route host at all. When OpenShift gets the new route without host, it construct it from name and namespace like `<name>-<namespace>.domain...`. So when we have long namespace name, it fails here.

Currently I can see these options:
 - explicitly set the host
    - for this, we would need something like `che.infra.kubernetes.ingress.domain`, which is only on Kubernetes. On OpenShift we don't know the domain. This would need work on deployment side (Operator) as well.
 - Programatically prevent invalid configuration and fail as soon as possible with as clear message as possible (at startup if possible).
    - the length of `<userid>` is constant and we know it (UUID -> 36chars). So we could do it for `<userid>` case. We could catch the length without placeholders as well. We, probably can't do much with `<username>`.
    - we can improve the namespace normalization algorithm with knowing this new route host limitation
    - we probably can't do much with labeled namespaces
 - Just document the limitation and live with that

**Comment by sparkoo** [comment]
limitation documented https://github.com/eclipse/che-docs/pull/1654. I'm closing this issue. Reopen or create new one if needed.
