### ISSUE TITLE
Upgrade VS Code yaml to 0.11.1

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#18143]
### Is your enhancement related to a problem? Please describe.

current version is 0.8.0. it notably contains issues preventing good support of Camel K yaml files.

**Comment by ericwill** [comment]
Have you tested the new version on Che?

**Comment by apupier** [comment]
> Have you tested the new version on Che?

no

**Comment by RomanNikitenko** [comment]
I'm closing the issue as the corresponding PR was merged
