### ISSUE TITLE
Swagger is not acessible for Che without oauth

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18156]
### Describe the bug
I've deployed Che without OAuth and I'm not able to access the swagger page. I see the page for a while, but after a few seconds, an error screen is shown.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che using [chectl](https://github.com/che-incubator/chectl/releases/tag/20201021072005) : `checlt server:start -n katka-che --installer=operator --platform=openshift`
2. Change the CheCluster yaml - set `openShiftoAuth` to `false`
3. Allow user creation in keycloak
4. Create new user
5. Access swagger: <cheurl>/swagger
4. Wait for a few seconds for the error page to appear

### Expected behavior
Swagger should be accessible.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) 4.5
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-10-21 13-21-12](https://user-images.githubusercontent.com/29278800/96715586-1d2d3b80-13a4-11eb-93c1-c3aeb65ead6e.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output) `checlt server:start -n katka-che --installer=operator --platform=openshift`
     * provide an output of `chectl version` command `chectl/0.0.20201021-next.b21f570 linux-x64 node-v12.18.3`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) OpenStack
   - [ ] other: please specify

**Comment by rhopp** [comment]
I've added label "area/wsmaster", because swagger is exposing wsmaster API. If you thinkg some other arrea is more appropriate, please change that. Thanks (I have no idea whose responsibility swagger should be :smile: )

**Comment by sleshchenko** [comment]
I believe it's caused by https://github.com/eclipse/che-operator/pull/491
@tolusha Could you take a look and add swagger as a trusted redirect URL as well?

**Comment by tolusha** [comment]
@sleshchenko 
yes, I confirm.
