### ISSUE TITLE
No information about the root cause when using factories with invalid devfile

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18164]
### Describe the bug
If a devfile is incorrect, users are not able to easily find what is wrong when using a factory

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

https://che.openshift.io/f?url=https://gist.githubusercontent.com/benoitf/fd72f0c91b6e73b7b88a63642962319c/raw/72af74bc69a99db56ea7648a9c68f13f3d5cec6d/invalid-devfile.yaml

### Expected behavior
Have the root cause being displayed
We only see 'error 400'

### Screenshots
![image](https://user-images.githubusercontent.com/436777/96837237-61711800-1446-11eb-96c9-8541d98bfabe.png)

### Additional context
If I manually call `/api/factory/resolver` API I can see
```
{
"message": "Error occurred during creation a workspace from devfile located at `https://gist.githubusercontent.com/benoitf/fd72f0c91b6e73b7b88a63642962319c/raw/72af74bc69a99db56ea7648a9c68f13f3d5cec6d/invalid-devfile.yaml`. Cause: Devfile schema validation failed. Error: (/components/0/volumes/0):The object must have a property whose name is "containerPath"."
}
```

but this helpful message is not displayed

**Comment by sleshchenko** [comment]
Is merged in https://github.com/eclipse/che-dashboard/pull/115
