### ISSUE TITLE
Automated self-signed certificate install on macOS

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#18163]
### Is your enhancement related to a problem? Please describe.
There is an idea to automate certificate installation on macOS during `server:deploy` step:

```
    ✔ [ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /var/folders/cm/p5hvjvr53k33dyjv9kyr04hc0000gn/T/cheCA.crt.
   Documentation how to add a CA certificate into a browser: https://www.eclipse.org/che/docs/che-7/overview/importing-certificates-to-browsers/
```

### Describe the solution you'd like
To install self-signed certificate to trusted store on macOS it's enough to call system command:

```
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain /path/to/cheCA.crt
```

Above command requires sudo privileges, but it is okay to ask user to enter the password to perform this step.

### Describe alternatives you've considered
none

### Additional context
https://apple.stackexchange.com/questions/80623/import-certificates-into-the-system-keychain-via-the-command-line

**Comment by tolusha** [comment]
I am strongly against installing certificates for user without him is being aware of.
It is something that must be done manually or at least automated by at end user side.

**Comment by vzhukovs** [comment]
It can be a prompt for a user to call the system command after user's agree.
