### ISSUE TITLE
Simplify the factory URL link

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18165]
### Is your enhancement related to a problem? Please describe.
Many users are wondering what is the format to provide the devfile URL and often misspell the `/f?url=` link by forgetting the `/f` or missing the `url` attribute

### Describe the solution you'd like
would be nice to have only one special character
could be like gitpod and the `#` or something else but `/f?url=` is too hard for users.

`https://che.openshift.io#https://github.com/eclipse/che`

**Comment by sleshchenko** [comment]
We should keep in mind during addressing it:
1. We need make sure #... is correctly propagated during authentication.
2. In addition to devfile/repo URL, we support other parameters, like devfile patch, workspacePodLabels, creationStrategy(perStart/perUser). How then we define URL: `https://che.openshift.io#${URL}&workspacePodLabels=key=value&creationStrategy=perStart&patch.devfile.projects.url=https://github.com/eclipse/che` ? Where URL is required

**Comment by gorkem** [comment]
Also the new implementation should not break the existing urls

**Comment by benoitf** [comment]
yes, of course, maybe it was not clear, but current urls should still continue to work

**Comment by nickboldt** [comment]
another approach would be to generate the URL and put it on the screen when you paste in the URL for your devfile.

https://github.com/eclipse/che/issues/18415 

Then you don't have to type anything ... just copy/paste the /?url=... URL to your blog/readme/slack whatever.

**Comment by sleshchenko** [comment]
That's not clear how to divide URL part (which probably can contain query parameters) from the other factory parameters (workspacePodLabels, devfile overrides and so on).
In case of `/f?url={URL}&workspacePod=...`, {URL} is expected to be encoded in case it contains multiple query parameters.
The simple proposal Mario brought, we can at least start with the factory URL with hash that supports only Repo, Devfile URL. If you need advanced options, you need to use `/f?url=&workspacePodLabels=...&`

**Comment by sleshchenko** [comment]
Is opened since it would be great if we promote such way of doing factory in Che docs.
