### ISSUE TITLE
Update java plugin to 0.69.0

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#18170]
Since the latest version of vscode-java extension doesn't support java8 we have to update only [java11 plugin](https://github.com/svor/che-plugin-registry/tree/master/v3/plugins/redhat/java11) and migrate java plugin to Java 11

Subtasks:
- [x] Update redhat/java11 to use vscode-java 0.69.0
- [x] Migreate redhat/java to use Java 11
- [x] Adapt all java stacks in che-devfile-registry
- [x] Update java builtin plugin in che-theia

**Comment by ericwill** [comment]
All PR's merged, thanks Valerii!
