### ISSUE TITLE
chectl server:deploy not found

### ISSUE THREAD

**Issue by nicolasduminil** [eclipse-che/che#18177]
## Summary
Can't install on Minikube
## Relevant information
Quoting from the documentation:
    "Run the following command:

    $ chectl server:deploy --platform minikube"
But executing this command raises the following exception:
 
chectl server:deploy --platform minikube
 ›   Error: command server:deploy not found

So it seems that the server:deploy command simply doesn't exist. This is confirmed by the --help command which doesn't show any such option.

**Comment by rhopp** [comment]
Are you sure you are using latest chectl (7.20)?

**Comment by nicolasduminil** [comment]
chectl --version
chectl/7.20.0 linux-x64 node-v10.22.1

**Comment by tolusha** [comment]
@nicolasduminil 
For the time being use `server:start`. 
`server:deploy` is introduced as alias to `server:start` and available in the latest nightly version of chectl as well as will be added to 7.20.1 version.

**Comment by nicolasduminil** [comment]
I can't believe that I was able to open for the first time the documentation, to go to first chapter, Installation, to read a couple of sentences and and to find already an inadvertence ! Either I'm very lucky to find in a couple of minutes the first error, or the documentation is full of such issues.
But okay, I tried server:start which doesn't work neither, as shown below:

chectl server:start --platform minikube                                 
› Current Kubernetes context: 'minikube'
› Installer type is set to: 'operator'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Check Kubernetes version: Found v1.19.2.
    ✔ Verify if minikube ingress addon is enabled
    ✔ Enable minikube ingress addon
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.49.2.nip.io.
    ✔ Checking minikube version... 1.14.0
    ✔ Patch minikube storage... done
    ↓ Check if cluster accessible [skipped]
  ✔ Start following logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
  ✔ 🏃  Running the Eclipse Che operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...done.
    ✔ Create ServiceAccount che-operator in namespace che...done.
    ✔ Create Role che-operator in namespace che...done.
    ✔ Create ClusterRole che-che-operator...done.
    ✔ Create RoleBinding che-operator in namespace che...done.
    ✔ Create ClusterRoleBinding che-che-operator...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...done.
    ✔ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace che...done.
  ❯ ✅  Post installation checklist
    ❯ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✖ downloading images
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
        starting
      Keycloak pod bootstrap
      Devfile registry pod bootstrap
      Plugin registry pod bootstrap
      Eclipse Che pod bootstrap
      Eclipse Che status check
    Retrieving Keycloak admin credentials
    Retrieving Che self-signed CA certificate
    Prepare post installation output
 ›   Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000
 ›   Installation failed, check logs in '/tmp/chectl-logs/1603456649201'

**Comment by nicolasduminil** [comment]
And the file /tmp/chectl-logs/1603456649201/che/che-operator-748bcfbdb4-zs9vq/che-operator.log 
says:

time="2020-10-23T12:40:22Z" level=info msg="Default 'info' log level is applied"
time="2020-10-23T12:40:22Z" level=info msg="Go Version: go1.13.4"
time="2020-10-23T12:40:22Z" level=info msg="Go OS/Arch: linux/amd64"
time="2020-10-23T12:40:22Z" level=info msg="operator-sdk Version: v0.5.0"
time="2020-10-23T12:40:22Z" level=info msg="Operator is running on Kubernetes"
time="2020-10-23T12:40:22Z" level=info msg="Registering Che Components Types"
time="2020-10-23T12:40:22Z" level=info msg="Starting the Cmd"
time="2020-10-23T12:40:22Z" level=info msg="Creating a new object: ServiceAccount, name che-tls-job-service-account"
time="2020-10-23T12:40:22Z" level=info msg="Creating a new object: Role, name che-tls-job-role"
time="2020-10-23T12:40:22Z" level=info msg="Creating a new object: RoleBinding, name che-tls-job-role-binding"
time="2020-10-23T12:40:22Z" level=info msg="Creating a new object: Job, name che-tls-job"
time="2020-10-23T12:40:22Z" level=info msg="Waiting on job 'che-tls-job' to be finished"
...
time="2020-10-23T12:41:02Z" level=info msg="Import public part of Eclipse Che self-signed CA certificate from \"self-signed-certificate\" secret into your browser."
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: ServiceAccount, name che"
time="2020-10-23T12:41:03Z" level=info msg="Waiting on service account 'che' to be created"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: ServiceAccount, name che-workspace"
time="2020-10-23T12:41:03Z" level=info msg="Waiting on service account 'che-workspace' to be created"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: Role, name exec"
time="2020-10-23T12:41:03Z" level=info msg="Waiting on role 'exec' to be created"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: Role, name view"
time="2020-10-23T12:41:03Z" level=info msg="Waiting on role 'view' to be created"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: RoleBinding, name che"
time="2020-10-23T12:41:03Z" level=info msg="Waiting on role binding 'che' to be created"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: RoleBinding, name che-workspace-exec"
time="2020-10-23T12:41:03Z" level=info msg="Waiting on role binding 'che-workspace-exec' to be created"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: RoleBinding, name che-workspace-view"
time="2020-10-23T12:41:03Z" level=info msg="Waiting on role binding 'che-workspace-view' to be created"
time="2020-10-23T12:41:03Z" level=info msg="Updating eclipse-che CR with installation flavor: che"
time="2020-10-23T12:41:03Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: Secret, name che-postgres-secret"
time="2020-10-23T12:41:03Z" level=info msg="Updating eclipse-che CR with Postgres Secret: che-postgres-secret"
time="2020-10-23T12:41:03Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: Secret, name che-identity-postgres-secret"
time="2020-10-23T12:41:03Z" level=info msg="Updating eclipse-che CR with Identity Provider Postgres Secret: che-identity-postgres-secret"
time="2020-10-23T12:41:03Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:03Z" level=info msg="Creating a new object: Secret, name che-identity-secret"
time="2020-10-23T12:41:03Z" level=info msg="Updating eclipse-che CR with Identity Provider Secret: che-identity-secret"
time="2020-10-23T12:41:03Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:03Z" level=info msg="Updating eclipse-che CR with Postgres DB: dbche"
time="2020-10-23T12:41:03Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:03Z" level=info msg="Updating eclipse-che CR with Postgres hostname: postgres"
time="2020-10-23T12:41:03Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:03Z" level=info msg="Updating eclipse-che CR with Postgres port: 5432"
time="2020-10-23T12:41:04Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:04Z" level=info msg="Updating eclipse-che CR with Keycloak realm: che"
time="2020-10-23T12:41:04Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:04Z" level=info msg="Updating eclipse-che CR with Keycloak client ID: che-public"
time="2020-10-23T12:41:04Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:04Z" level=info msg="Updating eclipse-che CR with log level: INFO"
time="2020-10-23T12:41:04Z" level=info msg="Custom resource eclipse-che updated"
time="2020-10-23T12:41:04Z" level=info msg="Creating a new object: Service, name postgres"
time="2020-10-23T12:41:04Z" level=info msg="Waiting on service 'postgres' to be ready"
time="2020-10-23T12:41:04Z" level=info msg="Creating a new object: PersistentVolumeClaim, name postgres-data"
time="2020-10-23T12:41:04Z" level=info msg="Waiting on pvc 'postgres-data' to be bound. Sometimes PVC can be bound only when the first consumer is created."
time="2020-10-23T12:41:04Z" level=info msg="Creating a new object: Deployment, name postgres"
time="2020-10-23T12:41:04Z" level=info msg="Waiting on deployment 'postgres' to be ready"
time="2020-10-23T12:41:04Z" level=info msg="Waiting on deployment 'postgres' to be ready"
time="2020-10-23T12:41:04Z" level=info msg="Waiting on deployment 'postgres' to be ready"
time="2020-10-23T12:41:04Z" level=info msg="Waiting on deployment 'postgres' to be ready"
time="2020-10-23T12:41:04Z" level=info msg="Waiting on deployment 'postgres' to be ready"

**Comment by tolusha** [comment]
@nicolasduminil 
1. could you try `kubectl describe  pods -n che`
2. How did you start minikube?  any arguments?

**Comment by nicolasduminil** [comment]
Yes, sure:

1. kubectl describe pods -n che
Name:         che-764c49d4c8-srmd2
Namespace:    che
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Fri, 23 Oct 2020 15:11:41 +0200
Labels:       app=che
              component=che
              pod-template-hash=764c49d4c8
Annotations:  <none>
Status:       Running
IP:           172.17.0.15
IPs:
  IP:           172.17.0.15
Controlled By:  ReplicaSet/che-764c49d4c8
Containers:
  che:
    Container ID:   docker://3d7b4d5ba95a70f299df1a84729531b6d5b5bc9756a4683bbb90a1c5a8405956
    Image:          quay.io/eclipse/che-server:7.20.0
    Image ID:       docker-pullable://quay.io/eclipse/che-server@sha256:6e566fdfee7f38ae41b21153c681cab02461f992374b6b58d9141b21161681c3
    Ports:          8080/TCP, 8000/TCP, 8888/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 23 Oct 2020 15:16:40 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  1Gi
    Requests:
      memory:   512Mi
    Liveness:   http-get http://:8080/api/system/state delay=200s timeout=3s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8080/api/system/state delay=25s timeout=5s period=10s #success=1 #failure=18
    Environment Variables from:
      che  ConfigMap  Optional: false
    Environment:
      CHE_SELF__SIGNED__CERT:            <set to the key 'ca.crt' in secret 'self-signed-certificate'>  Optional: true
      CHE_GIT_SELF__SIGNED__CERT:        
      CHE_GIT_SELF__SIGNED__CERT__HOST:  
      CHE_KEYCLOAK_ADMIN__PASSWORD:      <set to the key 'password' in secret 'che-identity-secret'>  Optional: false
      CHE_KEYCLOAK_ADMIN__USERNAME:      <set to the key 'user' in secret 'che-identity-secret'>      Optional: false
      CM_REVISION:                       18685,
      KUBERNETES_NAMESPACE:              che (v1:metadata.namespace)
      CHE_JDBC_USERNAME:                 <set to the key 'user' in secret 'che-postgres-secret'>      Optional: false
      CHE_JDBC_PASSWORD:                 <set to the key 'password' in secret 'che-postgres-secret'>  Optional: false
    Mounts:
      /public-certs from che-public-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from che-token-2hk6g (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  che-public-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  che-token-2hk6g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  che-token-2hk6g
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>


Name:         che-operator-748bcfbdb4-zs9vq
Namespace:    che
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Fri, 23 Oct 2020 14:37:36 +0200
Labels:       app=che-operator
              pod-template-hash=748bcfbdb4
Annotations:  <none>
Status:       Running
IP:           172.17.0.10
IPs:
  IP:           172.17.0.10
Controlled By:  ReplicaSet/che-operator-748bcfbdb4
Containers:
  che-operator:
    Container ID:  docker://19e9627fc8618ad1592ad91f9fac7d31139ea778474204c71511ab9022a168e4
    Image:         quay.io/eclipse/che-operator:7.20.0
    Image ID:      docker-pullable://quay.io/eclipse/che-operator@sha256:ba4d0f28d1d49dbeac63403549d4dde31d5f51f37e7ccf58faf0fc8c6e1ed7d1
    Port:          60000/TCP
    Host Port:     0/TCP
    Command:
      /usr/local/bin/che-operator
    State:          Running
      Started:      Fri, 23 Oct 2020 14:40:22 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      WATCH_NAMESPACE:                                          che (v1:metadata.namespace)
      POD_NAME:                                                 che-operator-748bcfbdb4-zs9vq (v1:metadata.name)
      OPERATOR_NAME:                                            che-operator
      CHE_VERSION:                                              7.20.0
      RELATED_IMAGE_che_server:                                 quay.io/eclipse/che-server:7.20.0
      RELATED_IMAGE_plugin_registry:                            quay.io/eclipse/che-plugin-registry:7.20.0
      RELATED_IMAGE_devfile_registry:                           quay.io/eclipse/che-devfile-registry:7.20.0
      RELATED_IMAGE_che_tls_secrets_creation_job:               quay.io/eclipse/che-tls-secret-creator:alpine-d1ed4ad
      RELATED_IMAGE_pvc_jobs:                                   registry.access.redhat.com/ubi8-minimal:8.2-349
      RELATED_IMAGE_postgres:                                   centos/postgresql-96-centos7:9.6
      RELATED_IMAGE_keycloak:                                   quay.io/eclipse/che-keycloak:7.20.0
      RELATED_IMAGE_che_workspace_plugin_broker_metadata:       quay.io/eclipse/che-plugin-metadata-broker:v3.4.0
      RELATED_IMAGE_che_workspace_plugin_broker_artifacts:      quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0
      RELATED_IMAGE_che_server_secure_exposer_jwt_proxy_image:  quay.io/eclipse/che-jwtproxy:0.10.0
      RELATED_IMAGE_single_host_gateway:                        docker.io/traefik:v2.2.8
      RELATED_IMAGE_single_host_gateway_config_sidecar:         quay.io/che-incubator/configbump:0.1.4
      CHE_FLAVOR:                                               che
      CONSOLE_LINK_NAME:                                        che
      CONSOLE_LINK_DISPLAY_NAME:                                Eclipse Che
      CONSOLE_LINK_SECTION:                                     Red Hat Applications
      CONSOLE_LINK_IMAGE:                                       /dashboard/assets/branding/loader.svg
      CHE_IDENTITY_SECRET:                                      che-identity-secret
      CHE_IDENTITY_POSTGRES_SECRET:                             che-identity-postgres-secret
      CHE_POSTGRES_SECRET:                                      che-postgres-secret
      CHE_SERVER_TRUST_STORE_CONFIGMAP_NAME:                    ca-certs
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from che-operator-token-t4s9k (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  che-operator-token-t4s9k:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  che-operator-token-t4s9k
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>


Name:         devfile-registry-b49db49bd-rjqq9
Namespace:    che
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Fri, 23 Oct 2020 15:10:30 +0200
Labels:       app=che
              component=devfile-registry
              pod-template-hash=b49db49bd
Annotations:  <none>
Status:       Running
IP:           172.17.0.14
IPs:
  IP:           172.17.0.14
Controlled By:  ReplicaSet/devfile-registry-b49db49bd
Containers:
  che-devfile-registry:
    Container ID:   docker://8d89a0a68dd815bfc805c5719c1fa69b94894c3a979a5398f6d3d8f68835a803
    Image:          quay.io/eclipse/che-devfile-registry:7.20.0
    Image ID:       docker-pullable://quay.io/eclipse/che-devfile-registry@sha256:a0939aad1049b6b6954f66208bc0ec17d4ae3e22f06872d28cd476102466b231
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 23 Oct 2020 15:11:18 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  256Mi
    Requests:
      memory:   16Mi
    Liveness:   http-get http://:8080/devfiles/ delay=30s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:8080/devfiles/ delay=3s timeout=3s period=10s #success=1 #failure=10
    Environment Variables from:
      devfile-registry  ConfigMap  Optional: true
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hlf7j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-hlf7j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hlf7j
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>


Name:         keycloak-7bf478f895-5jzj5
Namespace:    che
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Fri, 23 Oct 2020 15:09:58 +0200
Labels:       app=che
              component=keycloak
              pod-template-hash=7bf478f895
Annotations:  <none>
Status:       Running
IP:           172.17.0.13
IPs:
  IP:           172.17.0.13
Controlled By:  ReplicaSet/keycloak-7bf478f895
Containers:
  keycloak:
    Container ID:  docker://3c337c73c578c52df5e5248eeb490b260be1c51a5376be2110db542d13306a36
    Image:         quay.io/eclipse/che-keycloak:7.20.0
    Image ID:      docker-pullable://quay.io/eclipse/che-keycloak@sha256:42ae2be185897649ee2a1b608691882cce0a3eee8bd552cec5b4d3a8155d1739
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /bin/sh
    Args:
      -c
      echo "ssl_required WAS UPDATED for master realm." && if [ ! -z "${CHE_SELF__SIGNED__CERT}" ]; then echo "${CHE_SELF__SIGNED__CERT}" > /scripts/che.crt && keytool -importcert -alias ROUTERCRT -keystore /scripts/openshift.jks -file /scripts/che.crt -storepass LeZzY87rfKLs -noprompt; fi && if [ ! -z "${OPENSHIFT_SELF__SIGNED__CERT}" ]; then echo "${OPENSHIFT_SELF__SIGNED__CERT}" > /scripts/openshift.crt && keytool -importcert -alias OPENSHIFTAPI -keystore /scripts/openshift.jks -file /scripts/openshift.crt -storepass LeZzY87rfKLs -noprompt; fi &&  keytool -importcert -alias MOUNTEDCRT -keystore /scripts/openshift.jks -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -storepass LeZzY87rfKLs -noprompt && if [ -f /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt ]; then keytool -importcert -alias MOUNTEDSERVICECRT -keystore /scripts/openshift.jks -file /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt -storepass LeZzY87rfKLs -noprompt; fi && keytool -importkeystore -srckeystore /etc/pki/ca-trust/extracted/java/cacerts -destkeystore /scripts/openshift.jks -srcstorepass changeit -deststorepass LeZzY87rfKLs && if [[ -d "/public-certs" && -n "$(find /public-certs -type f)" ]]; then for certfile in /public-certs/* ; do keytool -importcert -alias CERT_$(basename $certfile) -keystore /scripts/openshift.jks -file $certfile -storepass LeZzY87rfKLs -noprompt; done; fi && echo Installing certificates into Keycloak && echo -e "embed-server --server-config=standalone.xml --std-out=echo 
      /subsystem=keycloak-server/spi=truststore/:add 
      /subsystem=keycloak-server/spi=truststore/provider=file/:add(properties={file => "/scripts/openshift.jks", password => "LeZzY87rfKLs", disabled => "false" },enabled=true) 
      stop-embedded-server" > /scripts/add_openshift_certificate.cli && /opt/jboss/keycloak/bin/jboss-cli.sh --file=/scripts/add_openshift_certificate.cli && /opt/jboss/docker-entrypoint.sh -b 0.0.0.0 -c standalone.xml -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
    State:          Running
      Started:      Fri, 23 Oct 2020 15:09:59 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  2Gi
    Requests:
      memory:   512Mi
    Readiness:  http-get http://:8080/auth/js/keycloak.js delay=25s timeout=5s period=10s #success=1 #failure=10
    Environment:
      CM_REVISION:                   
      PROXY_ADDRESS_FORWARDING:      true
      DB_VENDOR:                     POSTGRES
      POSTGRES_PORT_5432_TCP_ADDR:   postgres
      POSTGRES_PORT_5432_TCP_PORT:   5432
      POSTGRES_PORT:                 5432
      POSTGRES_ADDR:                 postgres
      POSTGRES_DATABASE:             keycloak
      POSTGRES_USER:                 keycloak
      SSO_TRUSTSTORE:                openshift.jks
      SSO_TRUSTSTORE_DIR:            /scripts
      SSO_TRUSTSTORE_PASSWORD:       LeZzY87rfKLs
      CHE_SELF__SIGNED__CERT:        <set to the key 'ca.crt' in secret 'self-signed-certificate'>         Optional: true
      OPENSHIFT_SELF__SIGNED__CERT:  <set to the key 'ca.crt' in secret 'openshift-api-crt'>               Optional: true
      POSTGRES_PASSWORD:             <set to the key 'password' in secret 'che-identity-postgres-secret'>  Optional: false
      KEYCLOAK_PASSWORD:             <set to the key 'password' in secret 'che-identity-secret'>           Optional: false
      KEYCLOAK_USER:                 <set to the key 'user' in secret 'che-identity-secret'>               Optional: false
    Mounts:
      /public-certs from che-public-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hlf7j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  che-public-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-hlf7j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hlf7j
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>


Name:         plugin-registry-6789fd75dd-ft69c
Namespace:    che
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Fri, 23 Oct 2020 15:11:23 +0200
Labels:       app=che
              component=plugin-registry
              pod-template-hash=6789fd75dd
Annotations:  <none>
Status:       Running
IP:           172.17.0.12
IPs:
  IP:           172.17.0.12
Controlled By:  ReplicaSet/plugin-registry-6789fd75dd
Containers:
  che-plugin-registry:
    Container ID:   docker://1432c0752b4690e19958263ef6b2f29a7ce259745a53ddab608659f29ee32042
    Image:          quay.io/eclipse/che-plugin-registry:7.20.0
    Image ID:       docker-pullable://quay.io/eclipse/che-plugin-registry@sha256:044f22b66f7d543b9bb2d23833a567f7d5077455927ce40e2e04777835a2d702
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 23 Oct 2020 15:11:34 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  256Mi
    Requests:
      memory:   16Mi
    Liveness:   http-get http://:8080/plugins/ delay=30s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:8080/plugins/ delay=3s timeout=3s period=10s #success=1 #failure=10
    Environment Variables from:
      plugin-registry  ConfigMap  Optional: true
    Environment:       <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hlf7j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-hlf7j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hlf7j
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>


Name:         postgres-5677f5ffb8-57svk
Namespace:    che
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Fri, 23 Oct 2020 14:41:04 +0200
Labels:       app=che
              component=postgres
              pod-template-hash=5677f5ffb8
Annotations:  <none>
Status:       Running
IP:           172.17.0.11
IPs:
  IP:           172.17.0.11
Controlled By:  ReplicaSet/postgres-5677f5ffb8
Containers:
  postgres:
    Container ID:   docker://837a58a6a53ee450d412d7d20b00dd1735a30583e46438543650cc6b86106568
    Image:          centos/postgresql-96-centos7:9.6
    Image ID:       docker-pullable://centos/postgresql-96-centos7@sha256:b681d78125361519180a6ac05242c296f8906c11eab7e207b5ca9a89b6344392
    Port:           5432/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 23 Oct 2020 14:50:13 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  1Gi
    Requests:
      memory:   512Mi
    Readiness:  exec [/bin/sh -i -c psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d dbche -c 'SELECT 1'] delay=15s timeout=5s period=10s #success=1 #failure=10
    Environment:
      POSTGRESQL_DATABASE:        dbche
      POSTGRESQL_ADMIN_PASSWORD:  b2RqlCpARmcb
      POSTGRESQL_USER:            <set to the key 'user' in secret 'che-postgres-secret'>      Optional: false
      POSTGRESQL_PASSWORD:        <set to the key 'password' in secret 'che-postgres-secret'>  Optional: false
    Mounts:
      /var/lib/pgsql/data from postgres-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hlf7j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  postgres-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  postgres-data
    ReadOnly:   false
  default-token-hlf7j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hlf7j
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s

2. minikube start --driver=docker --cpus=4 --memory='8192m'
