### ISSUE TITLE
Workspace activity checker doesn't work for workspace based on "Intelij IDE" editor

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#18171]
### Describe the bug
Workspace activity checker doesn't work for workspace based on "Intelij IDE" editor

### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Go to the dashboard and create custom workspace using devfile https://github.com/che-incubator/che-editor-intellij-community/blob/master/devfiles/workspace.yaml
 - Wait until workspace with the Intelij Ide editor is started
 - Create project and start working with it
 - Pay attention that workspace will be stopped after timeout defined in the "CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT" even if user performs actions inside IDE.

### Expected behavior
Workspace has the "RUNNING" status after the "CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT" if during this period any actions were performed inside IDE.

### Observed behavior
Workspace has status "STOPPED" after the "CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT" even if actions inside IDE were performed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ x ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by vzhukovskii** [comment]
Need to check recent changes related to workspace activity tracker on platform side.
