### ISSUE TITLE
Command fails in Python Django

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18173]
### Describe the bug
The nightly test for Python Django failed to run the default commands. There was an error:
` sh: 1: .: Can't open /projects/.venv/bin/activate`

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run devfile test suites against nightly Che.
OR
Start Python Django workspace on nightly che. Try to run the commands. 

### Expected behavior
Commands should work correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
> chectl server:start --k8spodreadytimeout=180000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/mnt/hudson_workspace/workspace/basic-MultiUser-Che-check-e2e-tests-against-k8s/custom-resource-patch.yaml --chenamespace=eclipse-che

> chectl server:start --listr-renderer=verbose -a operator -p minishift --k8spodreadytimeout=360000 --che-operator-cr-patch-yaml=/tmp/custom-resource-patch.yaml --chenamespace=eclipse-che

   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
[Che logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2536/artifact/logs-and-configs/che-logs/che-644bf787cc-qq4vw.pod.log)
[Other logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2536/artifact/logs-and-configs/)

**Comment by ericwill** [comment]
The devfile for Python Django was recently changed, and has additional steps to set up the environment. I suspect that is what's causing the issue.

**Comment by Katka92** [comment]
@ericwill Can you please point me to the extra steps that should be performed? Thank you

**Comment by ericwill** [comment]
> @ericwill Can you please point me to the extra steps that should be performed? Thank you

Sure, the change was made here: https://github.com/eclipse/che-devfile-registry/pull/294 There is a new step "set up venv" that needs to be executed.

**Comment by Katka92** [comment]
Yes, you're right, it fixed my problem. I'll update our tests. Thank you!
