### ISSUE TITLE
Change Workspace environment model

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#1818]
Change model of workspace in accordance with environment model described in this doc
https://docs.google.com/document/d/1fEO8iY8JnfeGxYVEQV6TMIiGbiwNEYqvH1f_ctjATkc

**Comment by bmicklea** [comment]
@garagatyi - I believe we need to document these changes in the Eclipse Che docs so that external plugin developers are aware of them. Can you create a new issue with label:kind/docs and provide the technical information needed for the documentation please.

**Comment by garagatyi** [comment]
@bmicklea #2363
