### ISSUE TITLE
dashboard should show some error when it can't get the namespaces

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18180]
### Describe the bug

On "create a custom workspace" page, if `api/kubernetes/namespace` request fails, the dashboard does not show any error message or anything that would notify the user that something is wrong.

The error is visible in network communication and browser console (see screenshots).

Only indicator that something is wrong is that "Create & Open" button is disabled. On dashboard-next, the button is enabled and creation fails with `Danger alert:Failed to create a workspace.`

### Che version

 - [x] nightly

### Steps to reproduce

It's possible to reproduce on latest master because of https://github.com/eclipse/che/issues/18176. You need to use username with non-DNS characters, like an email. Then go to "create new custom workspace" page. You can see that there is no namespace shown.

Alternatively, I could provide che-server image that artificially fails the request.

### Expected behavior

User should be notified that something is wrong. Even some steps what to do, like contact admin, report a bug or something like that.

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots

![20201022_172235_1610x892_scrot](https://user-images.githubusercontent.com/1160903/96893711-483e8a80-148b-11eb-863a-a0e434bd7237.png)

![20201022_172244_1632x354_scrot](https://user-images.githubusercontent.com/1160903/96893742-52608900-148b-11eb-8a53-6bb354d46950.png)

![20201022_172509_1609x902_scrot](https://user-images.githubusercontent.com/1160903/96893966-8f2c8000-148b-11eb-9765-6f40410916e5.png)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

### Additional context

https://github.com/eclipse/che/issues/18176

**Comment by sleshchenko** [comment]
I believe it should be fixed by https://github.com/eclipse/che/issues/19564
