### ISSUE TITLE
chectl server:start doesn't work

### ISSUE THREAD

**Issue by nicolasduminil** [eclipse-che/che#18186]
## Summary
chectl server:start raises timeout error
## Relevant information
chectl server:start --platform minikube
› Current Kubernetes context: 'minikube'
› Installer type is set to: 'operator'
heavy_check_mark Verify Kubernetes API...OK
heavy_check_mark eyes Looking for an already existing Eclipse Che instance
heavy_check_mark Verify if Eclipse Che is deployed into namespace "che"...it is not
heavy_check_mark airplane Minikube preflight checklist
heavy_check_mark Verify if kubectl is installed
heavy_check_mark Verify if minikube is installed
heavy_check_mark Verify if minikube is running
↓ Start minikube [skipped]
→ Minikube is already running.
heavy_check_mark Check Kubernetes version: Found v1.19.2.
heavy_check_mark Verify if minikube ingress addon is enabled
heavy_check_mark Enable minikube ingress addon
heavy_check_mark Retrieving minikube IP and domain for ingress URLs...192.168.49.2.nip.io.
heavy_check_mark Checking minikube version... 1.14.0
heavy_check_mark Patch minikube storage... done
↓ Check if cluster accessible [skipped]
heavy_check_mark Start following logs
heavy_check_mark Start following Operator logs...done
heavy_check_mark Start following Eclipse Che logs...done
heavy_check_mark Start following Postgres logs...done
heavy_check_mark Start following Keycloak logs...done
heavy_check_mark Start following Plugin registry logs...done
heavy_check_mark Start following Devfile registry logs...done
heavy_check_mark Start following events
heavy_check_mark Start following namespace events...done
› Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
heavy_check_mark runner Running the Eclipse Che operator
heavy_check_mark Copying operator resources...done.
heavy_check_mark Create Namespace (che)...done.
heavy_check_mark Create ServiceAccount che-operator in namespace che...done.
heavy_check_mark Create Role che-operator in namespace che...done.
heavy_check_mark Create ClusterRole che-che-operator...done.
heavy_check_mark Create RoleBinding che-operator in namespace che...done.
heavy_check_mark Create ClusterRoleBinding che-che-operator...done.
heavy_check_mark Create CRD checlusters.org.eclipse.che...done.
heavy_check_mark Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
heavy_check_mark Create deployment che-operator in namespace che...done.
heavy_check_mark Create the Custom Resource of type checlusters.org.eclipse.che in the namespace che...done.
❯ white_check_mark Post installation checklist
❯ PostgreSQL pod bootstrap
heavy_check_mark scheduling...done.
heavy_multiplication_x downloading images
→ ERR_TIMEOUT: Timeout set to pod wait timeout 300000
starting
Keycloak pod bootstrap
Devfile registry pod bootstrap
Plugin registry pod bootstrap
Eclipse Che pod bootstrap
Eclipse Che status check
Retrieving Keycloak admin credentials
Retrieving Che self-signed CA certificate
Prepare post installation output
› Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000
› Installation failed, check logs in '/tmp/chectl-logs/1603456649201'

**Comment by themr0c** [comment]
@tolusha  Can someone from deploy team investigate?

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/18177

@nicolasduminil 

chectl failed with downloading image. But despite this fact che-operator continued deploying Eclipse Che.

1. `chectl server:status` to get Eclipse Che status
2. `chectl cacert:export` to get CA certificate
3. `chectl dashboard:open` to open Eclipse Che dashboard

**Comment by nicolasduminil** [comment]
"chectl failed with downloading image". I know, this is why I filed this issue.
"But despite this fact che-operator continued deploying Eclipse Che." So, finally it didn't fail ?
1. Are you asking me to post here the output of the command ? If yes, please find it here below:

    chectl server:status
    › Current Kubernetes context: 'minikube'
    Eclipse Che Version    : 7.20.0
    Eclipse Che Url        : https://che-che.192.168.49.2.nip.io
    OpenShift OAuth enabled: Yes

2. Not sure whether this is mandatory and why as the documentation doesn't require it.
3. Raises the following exception:

    The server failed the authenticity check (che-che.192.168.49.2.nip.io).

    The issuer certificate of a locally looked up certificate could not be found
    No certificates could be verified

**Comment by metlos** [comment]
`chectl server:status` is for checking the status of the server even after the deploy command has finished (either with an error or successfully). As @tolusha mentioned, the deploy command may fail due to timeout but the deployment still continues in the cluster. This command enables you to check the progress of that.
`chectl cacert:export` and `chectl dasboard:open` are commands you can use to obtain the information you normally get when the deploy command successfully finishes - the certificate to import into the browser and the url of the Che dashboard.

I am closing this issue as I think there is all the information necessary. If you find it insufficient, don't hesitate to reopen and ask further or raise another issue with more specific questions.

Thank you!
