### ISSUE TITLE
Delete multi-module projects in some case holding failure

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1819]
Steps to reproduce:
1. Import multi-module project (https://github.com/eclipse/che.git)
2. Try to delete this project without waiting update maven dependencies

[log.txt](https://github.com/eclipse/che/files/369019/log.txt)

**Comment by riuvshin** [comment]
this is still actual

**Comment by svor** [comment]
This bug has already fixed for the localhost, but still reproduced on the cloud version, I've created an issue https://github.com/eclipse/che/issues/1985.
