### ISSUE TITLE
how can I configure volumes for workspaces in eclipse che?

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18191]
Hi , how can I configure volumes for workspaces in eclipse che? In my other kuberntes apps, we create a storage class and bound it to a storage like azure disk. And in pod definition we we mount it to a particular path inside my container.  Something like - https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv 
I went through che docs and what I understood is I have to create a storage class bounded to azure disk and update the parameter workspacePvcStorageClassNsme in my checluster.yaml? Is my understanding correct? And I could not find any option for the mount path, like if I want to mount the disk at a particular location in my workspaces container, how can i do that? 
Kindly assist with this.

**Comment by ibuziuk** [comment]
@skabashnyuk could you please take this one?
