### ISSUE TITLE
Happy Path test fail because LS autocomplete not working

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18199]
### Describe the bug
The LS seems to be initialized, but the `autocomplete` test step fails as the autocomplete is not working correctly. It happens from time to time. It seems it's not a test issue.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: PR check - build from master 

### Steps to reproduce
Run Happy Path automated test.

### Expected behavior
When the LS loading bar is not present in the bottom, the LS should be initialized and working properly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/29278800/97163860-8e446880-1781-11eb-9de2-5a727993c6c0.png)

Video [link](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/3865/artifact/tests/e2e/report/output.mp4)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
>chectl server:start --k8spodreadytimeout=180000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/mnt/hudson_workspace/workspace/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/custom-resource-patch.yaml --chenamespace=eclipse-che

>chectl/0.0.20201022-next.2bbd800 linux-x64 node-v10.22.1
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify ci.centos.org

### Eclipse Che Logs
All available logs are [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/3865/artifact/logs-and-configs/).
Test reports can be found [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/3865/artifact/tests/e2e/report/).

**Comment by RomanNikitenko** [comment]
Looks like it's duplicate https://github.com/eclipse/che/issues/18196
