### ISSUE TITLE
Start Che Error

### ISSUE THREAD

**Issue by Cookie-Wang** [eclipse-che/che#182]
i user centos 7,and docker -v:Docker version 1.9.1, build a34a1d5.
when i run:
docker run -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che

who can help me?

----------Get this error:--------
mount: permission denied
rmdir: failed to remove 'cpu': Read-only file system
mount: permission denied
rmdir: failed to remove 'cpuacct': Read-only file system
- Starting Docker: docker                                               [ OK ]

!!! Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon.

Looks like something went wrong. Possible issues:
1. (Win | Mac) VirtualBox not installed          ==> Rerun Docker Toolbox installation
2. (Win | Mac) Docker Machine not installed      ==> Rerun Docker Toolbox installation
3. (Win | Mac) Docker is not reachable           ==> Docker VM failed to start
4. (Win | Mac) Docker ok, but docker ps fails    ==> Docker environment variables not set properly
5. (Linux) Docker is not reachable               ==> Install: wget -qO- https://get.docker.com/ | sh
6. (Linux) Permissions not properly set          ==> Che must run as UID 1000 with user in docker group
7. Could not find the Che app server             ==> Did /tomcat get moved away from CHE_HOME?
8. Wrong version of Java found                   ==> Che requires Java 1.8
9. Did you use the right parameter syntax?       ==> See usage

We have seen issues with VirtualBox on Windows where your VM gets corrupted when your computer is
suspended while the VM is still running. This will appear as SSH or ethernet connection issues. This is
rare, but if encountered, current known solution is to uninstall VirtualBox and Docker Toolbox, and then
reinstall.

Che Environment Variables:
  (REQUIRED) JAVA_HOME                             ==> Location of Java runtime
  (REQUIRED: WIN|MAC) DOCKER_TOOLBOX_INSTALL_PATH  ==> Location of Docker Toolbox
  (REQUIRED: WIN|MAC) VBOX_MSI_INSTALL_PATH        ==> Location of VirtualBox
  (OPTIONAL) CHE_HOME                              ==> Directory where Che is installed
  (OPTIONAL) CHE_LOCAL_CONF_DIR                    ==> Directory with custom Che .properties files
  (OPTIONAL) CHE_LOGS_DIR                          ==> Directory for Che output logs
  (OPTIONAL) CHE_DOCKER_MACHINE_NAME               ==> (Win | Mac) Name of VM created by docker-machine
  (OPTIONAL) DOCKER_MACHINE_HOST                   ==> (Linux) Docker host IP - set if browser clients remote

Usage:
  che [OPTIONS] [run | start | stop]
     -i,      --image        Launches Che within a Docker container using latest image
     -i:tag,  --image:tag    Launches Che within a Docker container using specific image tag
     -p:port, --port:port    Port that Che server will use for HTTP requests; default=8080
     -r:ip,   --remote:ip    If Che clients are not localhost, set to IP address of Che server
     -m:vm,   --machine:vm   For Win & Mac, sets the docker-machine VM name to vm; default=default
     -s,      --suppress     Do not print browser client connection information
     -h,      --help         Show this help
     -d,      --debug        Use debug mode (prints command line options + app server debug)
     run                     Starts Che application server in current console
     start                   Starts Che application server in new console
     stop                    Stops Che application server

The -r flag sets the DOCKER_MACHINE_HOST system environment variable. Set this to the IP address of the node
that is running your Docker daemon. Only necessary to set this if on Linux and your browser clients are not
localhost, ie they are remote. This property automatically set for Che on Windows and Mac.

**Comment by TylerJewell** [comment]
That is not the correct command line.  Please see the usage instructions on the Che docs available at eclipse.org/Che.

-Tyler

On Tue, Jan 12, 2016 at 3:05 AM -0800, "Cookie-Wang" notifications@github.com wrote:

i user centos 7,and docker -v:Docker version 191, build a34a1d5

when i run:

docker run -it -p 8080:8080 -p 49152-49162:49152-49162 codenvy/che

who can help me?

----------Get this error:--------

mount: permission denied

rmdir: failed to remove 'cpu': Read-only file system

mount: permission denied

rmdir: failed to remove 'cpuacct': Read-only file system

Starting Docker: docker                                               [ OK ]

!!! Running 'docker' succeeded, but 'docker ps' failed This usually means that docker cannot reach its daemon

Looks like something went wrong Possible issues:

  1 (Win | Mac) VirtualBox not installed          ==> Rerun Docker Toolbox installation

  2 (Win | Mac) Docker Machine not installed      ==> Rerun Docker Toolbox installation

  3 (Win | Mac) Docker is not reachable           ==> Docker VM failed to start

  4 (Win | Mac) Docker ok, but docker ps fails    ==> Docker environment variables not set properly

  5 (Linux) Docker is not reachable               ==> Install: wget -qO- https://getdockercom/ | sh

  6 (Linux) Permissions not properly set          ==> Che must run as UID 1000 with user in docker group

  7 Could not find the Che app server             ==> Did /tomcat get moved away from CHE_HOME?

  8 Wrong version of Java found                   ==> Che requires Java 18

  9 Did you use the right parameter syntax?       ==> See usage

We have seen issues with VirtualBox on Windows where your VM gets corrupted when your computer is

suspended while the VM is still running This will appear as SSH or ethernet connection issues This is

rare, but if encountered, current known solution is to uninstall VirtualBox and Docker Toolbox, and then

reinstall

Che Environment Variables:

  (REQUIRED) JAVA_HOME                             ==> Location of Java runtime

  (REQUIRED: WIN|MAC) DOCKER_TOOLBOX_INSTALL_PATH  ==> Location of Docker Toolbox

  (REQUIRED: WIN|MAC) VBOX_MSI_INSTALL_PATH        ==> Location of VirtualBox

  (OPTIONAL) CHE_HOME                              ==> Directory where Che is installed

  (OPTIONAL) CHE_LOCAL_CONF_DIR                    ==> Directory with custom Che properties files

  (OPTIONAL) CHE_LOGS_DIR                          ==> Directory for Che output logs

  (OPTIONAL) CHE_DOCKER_MACHINE_NAME               ==> (Win | Mac) Name of VM created by docker-machine

  (OPTIONAL) DOCKER_MACHINE_HOST                   ==> (Linux) Docker host IP - set if browser clients remote

Usage:

  che [OPTIONS] [run | start | stop]

```
 -i,      --image        Launches Che within a Docker container using latest image

 -i:tag,  --image:tag    Launches Che within a Docker container using specific image tag

 -p:port, --port:port    Port that Che server will use for HTTP requests; default=8080

 -r:ip,   --remote:ip    If Che clients are not localhost, set to IP address of Che server

 -m:vm,   --machine:vm   For Win & Mac, sets the docker-machine VM name to vm; default=default

 -s,      --suppress     Do not print browser client connection information

 -h,      --help         Show this help

 -d,      --debug        Use debug mode (prints command line options + app server debug)

 run                     Starts Che application server in current console

 start                   Starts Che application server in new console

 stop                    Stops Che application server
```

The -r flag sets the DOCKER_MACHINE_HOST system environment variable Set this to the IP address of the node

that is running your Docker daemon Only necessary to set this if on Linux and your browser clients are not

localhost, ie they are remote This property automatically set for Che on Windows and Mac
