### ISSUE TITLE
Wrong behavior after rename not java files

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1821]
**Reproduction Steps:**
1. Create web-java-spring project from template
2. open /src/main/webapp/index.jsp
3. Try to rename 

**Observed behavior:**
The file is not present in tree of Project Explorer, but after rediscover folder the file is present.

**Che version:**    

4.5.0-RC1-SNAPSHOT

**Comment by JamesDrummond** [comment]
@musienko-maxim Provide team label.

**Comment by kusa1992** [comment]
I encountered this issue on Eclipse version 2022-06 (4.24.0). And I can't import the project into workspace as an existing project. The error is "Some projects cannot be imported because they already exist in the workspace" but I can't find it in workspace at all. Could you suggest me what to do?
