### ISSUE TITLE
move sidecars definitions into plugin-registry

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18217]
### Is your task related to a problem? Please describe.
Currently, sidecars used in plug-ins are defined in the https://github.com/che-dockerfiles organisation.
It works pretty well for existing plug-ins but it make stuff complicated for contributing:

- when a new plug-in need to be added into the registry with a custom sidecar: a sidecar repository need to be defined, then the image needs to be built and then we can create a PR to the plug-in registry
- testing a plug-in by updating it's runtime (the sidecar) need to be done with 2 PR: one against the sidecar repository and one against the plug-in registry once the image is built. And image is built only if it gets approval and be merged.

Contributor experience should be smoother allowing to:
- do not request the creation of a repository but simply open a PR against che-plugin-repository
- let people test the plug-in with a custom image before even merging the sidecar definition.

### Describe the solution you'd like
Allow to add sidecar definitions in the che-plugin-registry referencing the path where sidecar is defined.

example inside a chePlugin:
```yaml
sidecar:
  path: "../../sidecars/java11"
```
and in `sidecars/java11` folder:
it could contain Dockerfile, entrypoint.sh, etc

### Additional context
Lifecycle might be different between sidecars and plug-ins.

**Comment by ericwill** [comment]
@benoitf any objections to using a monorepo for sidecar images in quay.io? For example: `quay.io/che-sidecar-java:8-0cfbacb` becomes `quay.io/eclipse/che-plugin-sidecar:java8-0cfbacb`

This removes the dependency of needing a new quay.io repo for every sidecar image.

**Comment by benoitf** [comment]
no objection 👍
