### ISSUE TITLE
Fix storage provisioner patch in chectl

### ISSUE THREAD

**Issue by prabhav-thali** [eclipse-che/che#18228]
### Is your enhancement related to a problem? Please describe.
As can be seen in chectl codebase, storage provisioner [patch](https://github.com/che-incubator/chectl/blob/b692313a66f465ace819193022641cfc2522633d/src/tasks/platforms/minikube.ts#L97) is applied from minikube version 1.9+. However, the bug is being fixed in version 1.12.2 of minikube (https://github.com/kubernetes/minikube/issues/7218).
Also, the image used in patch is only supported on amd64 arch. And it will lead to failure on other architectures.

### Describe the solution you'd like
The above issue can be fixed by either of the following options:
1. Apply the patch only for amd64.
2. Apply the patch only for minikube versions 1.9 to 1.12.1.

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/pull/960
