### ISSUE TITLE
Impossible to get docker outputs when fail append during building the image

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#1822]
It is impossible to get the docker outputs when a failure append during building the image. The outputs and machine logs are automatically cleaned and it is impossible to debug

**Reproduction Steps:**
1. Create a new workspace with the following custom stack

```
from nuxeo

ENV NODE_VERSION=0.12.9 \
    NODE_PATH=/usr/local/lib/node_modules

RUN cd /home/nuxeo && curl --insecure -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
    && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
    && rm "node-v$NODE_VERSION-linux-x64.tar.gz" SHASUMS256.txt.asc

RUN npm install -g npm@latest && \
    npm install --unsafe-perm -g gulp bower grunt grunt-cli yeoman-generator yo generator-nuxeo
```
1. Open the workspace

**Expected behavior:**

[impossible-get-docker-logs.mp4.zip](https://github.com/eclipse/che/files/369035/impossible-get-docker-logs.mp4.zip)

The system fail to build the image. It is possible to see the docker outputs and investigate what is the problem.

**Observed behavior:**

The system fail to build the image. It is not possible to see the docker outputs

[Describe observed behavior here]

**Che version:**    4.4.0
**OS and version:** MAC OS X
**Che install:**    Codenvy 

**Additional information:**
See attached video
- Problem started happening recently, didn't happen in an older version of Che: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by JamesDrummond** [comment]
@slemeur Provide team label.

**Comment by TylerJewell** [comment]
@slemeur - is this still accurate?

**Comment by slemeur** [comment]
Yes this issue is still accurate and existing. 
(The problem happen within the IDE)

**Comment by vparfonov** [comment]
can't reproduce it
