### ISSUE TITLE
Study impact of image pulling process on the percentage of startup failures

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18236]
### Is your task related to a problem? Please describe.
There is an impression that image pulling https://github.com/eclipse/che/issues/15863 can be a cause
of workspace startup failure. 

### Describe the solution you'd like
We need to investigate:
 - Can we distinct image pulling from the total workspace startup process?
 - Does image pulling included in the total workspace startup limit?
 - What the implication if we make image pulling infinite?
 - Can we track image pulling progress?

### Describe alternatives you've considered
n/a

### Additional context
https://github.com/eclipse/che/issues/15863

**Comment by gattytto** [comment]
@skabashnyuk thank you for opening this issue, I have always needed this kind of distinction.


> * Can we distinct image pulling from the total workspace startup process?
  yes, but it is download+unpack.
> * Does image pulling included in the total workspace startup limit?
  yes and this includes the unpacking time too which can be long if 1.8gb goes to 8gb with tons of small files. 
> * What the implication if we make image pulling infinite?
 it may avoid cache/mirror helpers from triggering depending on the scenario. It makes more sense to kill and retry like .visx downloads. Than to let it be and trust it will all work. 
> * Can we track image pulling progress?
  depends on the OCI implementation used to setup the cluster. Cri-o was to have it only available in system logs for the debug loglevel, now it's even gone from there. Maybe for docker it can be obtained. So for cri-o one can only watch a crictl images and wait for the image to show up in the list or the sha to be updated.
