### ISSUE TITLE
Error message about WebSocket connection failure is not hidden

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18235]
### Describe the bug

In the case of a network error, Dashboard displays the error message that is shown even when the connection is restored and I'm able to navigate through the Dasboard pages and open Che Theia.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open Che and shutdown your network connection. The error message should appear at the top.
2. Restore your network connection and make sure you are able to navigate in Dashboard and into Che Theia. The error message still displayed.

### Expected behavior

The error message must be hidden once WebSocket connection is restored.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Peek 2020-10-28 22-21](https://user-images.githubusercontent.com/1636395/97493358-86491c00-196d-11eb-84f8-de30a39e0417.gif)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: che.openshift.io

**Comment by sleshchenko** [comment]
It should be fixed by https://github.com/eclipse/che-dashboard/pull/143
