### ISSUE TITLE
Unable to install che on docker-destkop using helm3 on Windows 10 home, fails at Updating Helm Chart dependencies

### ISSUE THREAD

**Issue by EleganteVagabond** [eclipse-che/che#18234]
### Describe the bug
Upon running 
chectl server:deploy --platform=docker-desktop --installer=helm --skip-kubernetes-health-check
the process fails at the Updating Helm Chart dependencies step. Suggestion in output says to run helm repo update which yields a success "Happy Helming!" message 

### Che version
chectl/0.0.20201022-next.2bbd800 win32-x64 node-v10.22.1

### Steps to reproduce
Install docker-desktop
Add kubernetes
Update WSL, restart
Install Helm (DL zip, add to PATH, add repo)
Run chectl server:deploy --platform=docker-desktop --installer=helm --skip-kubernetes-health-check

### Expected behavior
chectl will deploy an instance of che to my local kubernetes cluster

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
      v1.18.8
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
      19.03.13

### Screenshots
![che_install_issue](https://user-images.githubusercontent.com/62182203/97481116-b7542d00-192a-11eb-9bdc-4620332ef469.png)

### Installation method
   - [x] chectl
     chectl server:deploy --platform=docker-desktop --installer=helm --skip-kubernetes-health-check
     chectl/0.0.20201022-next.2bbd800 win32-x64 node-v10.22.1

### Environment
   - [ ] my computer
       - [10 Home ] Windows

### Eclipse Che Logs
The events.txt file is empty

**Comment by tolusha** [comment]
As alternative, could you try `--installer operator`

**Comment by EleganteVagabond** [comment]
Hi. Thank you for the quick response. I was able to get a lot further this time but hit a timeout issue during the "Starting" phase of Eclipse Pod Boostrap. This is the information that was provided.

![che_install_issue](https://user-images.githubusercontent.com/62182203/97626998-1b492500-1a01-11eb-9d37-f2ba4905565e.png)

I checked the logs for docker container itself. 'quay.io/eclipse/che-server' and this error is thrown repeatedly (50 times)

Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: https://keycloak-che.172.26.32.1.nip.io/auth/realms/che/.well-known/openid-configuration

**Comment by tolusha** [comment]
Could you try one more time in a clean namespace?
1. `chectl server:delete --delete-namespace`
2. `chectl server:deploy ...`

**Comment by EleganteVagabond** [comment]
Thank you again for the quick response.

After following the directions I get this error

```Error: Error: namespaces "che" not found```

In the log it looks like the namespace is created just before it tries to create the ServiceAccount. I ran the command twice and got the same results.

![che_install_issue](https://user-images.githubusercontent.com/62182203/97726513-aaa81400-1aa5-11eb-9748-ec17b8e78b77.png)

**Comment by tolusha** [comment]
That's really strange
Above  you have
`Create Namespace (che)`
and below
`namespaces "che" not found"`

As workaround to continue installation try `kubectl create namespace che` before running chectl command.

**Comment by EleganteVagabond** [comment]
I did that and then it failed again when preparing the che cluster. In the logs it said that it could not connect to the endpoint, again, but I can both ping the endpoint and hit it from my browser (with a certificate warning). At this point I have given up and may try again later. Thank you for your help.
