### ISSUE TITLE
Check if the GitHub oAuth is available when asking to sign in the Pull Requests plugin 

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#18237]
### Is your enhancement related to a problem? Please describe.

If GitHub identity provider is not setup or GitHub oAuth is not configured, GitHub sign in functionality for the vscode GitHub Pull Request plugin won't work.

### Describe the solution you'd like

Check if GitHub oAuth is available. If not, do not show the notification to sign in the GitHub plugin:
![screenshot-che-che 192 168 99 254 nip io-2020 10 28-11_30_41](https://user-images.githubusercontent.com/7668752/97577952-c73a4280-19f8-11eb-867b-3937d4063801.png)

**Comment by benoitf** [comment]
Hello, we discussed at the devex call and we wanted to do the following:

two steps like short term and mid-long/term:
- [ ] : Short term:  if the github identity provider is not setup, we should notify the user on how to configure it by referencing the documentation (if one project is coming from github)
- [ ]: Mid term: Add a redirect to keycloak URL and how to do the setup (documentation)

**Comment by vinokurig** [comment]
Is blocked by https://github.com/eclipse/che/issues/18791

**Comment by ericwill** [comment]
Removing blocked status as the dependent issue has been resolved.
