### ISSUE TITLE
Store preference for user agreement in JetBrains products

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#18230]
### Is your task related to a problem? Please describe.
Need to store user agreement in JetBrains products after workspace restart.

![Eclipse Che | che-6z7xh 2020-10-28 16-18-54](https://user-images.githubusercontent.com/1968177/97448588-7d3e5780-1939-11eb-9964-24f31bd2c44f.jpg)

### Describe the solution you'd like
Analyze and provide preliminary configuration for JetBrains products.

### Describe alternatives you've considered
Not at this time

### Additional context
N/A

**Comment by azatsarynnyy** [comment]
I've checked it with the new Projector-based editor. Can't reproduce.
