### ISSUE TITLE
Implement checking of the mounting source code defined in the yaml to the workspace based on the "Intellij" IDE

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#18239]
### Is your task related to a problem? Please describe.
Currently, it is not possible to define source code in the workspace yaml (Based on the "Intellij" IDE).

### Describe the solution you'd like
After making it possible to define source code cover this functionality by automated test.

**Comment by amisevsk** [comment]
If I understand this one correctly, the goal is to support cloning projects into workspaces when not using Theia as your editor; the labels I've assigned are to reflect that -- feel free to revise as necessary.

I believe @davidfestal and @benoitf had some discussion recently about moving initial clone operations out of the editor and into an init container, but don't know the details there.

**Comment by azatsarynnyy** [comment]
> ... but don't know the details there.

a bit more details are in this epic https://github.com/eclipse/che/issues/15973

**Comment by skabashnyuk** [comment]
removing devfile since it's not related to format

**Comment by amisevsk** [comment]
Closing as this is implemented in DWO as of https://github.com/devfile/devworkspace-operator/pull/371
