### ISSUE TITLE
Change default registry build style to offline (include all referenced resources in the container at build time)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18242]
### Is your enhancement related to a problem? Please describe.

Today, starting the Che plugin or devfile registry is fairly quick, since the default build style is "online", in that references to .vsix and icons and project resources are all resolved later.

But this also means that starting a workspace can be slow, as all those plugins have to be downloaded from github, jboss.org, or the open-vsx marketplace.

Starting the workspace also involves checking out code from GH, which can sometimes be slow.

### Describe the solution you'd like

Switch registry builds (both devfile and plugin registry) to 'offline' mode by default. This will do two things:

* devfile registry will, during the build, fetch project sources from the specified repos and branches and include them as zips in the container, guaranteeing that the sources won't "move" after a release (you'll be testing the same project sources as are live in the source project repo). This also enables OOTB airgap support for the sample projects.

* plugin registry will, during the build, fetch plugins and include them in the container so there's no external dependency on any 3rd party hosting sites, which could unexpectedly be offline. This also enables OOTB airgap support for all the plugins in the registry.

**Comment by benoitf** [comment]
Hello @nickboldt and @ericwill 
I think we have all the bits to build the plug-in registry embedding all resources. (keeping the surge.sh /github.io without embedding vsix files)
what is preventing to implement it ?

**Comment by ericwill** [comment]
> Hello @nickboldt and @ericwill
> I think we have all the bits to build the plug-in registry embedding all resources. (keeping the surge.sh /github.io without embedding vsix files)
> what is preventing to implement it ?

Apart from time/effort I don't think there are any technical barriers.

**Comment by ericwill** [comment]
> I don't think there are any technical barriers.

Of course when I say that I tempt fate...looks like plugins with dependencies still reference some vsix files with HTTP URLs: #19746

**Comment by benoitf** [comment]
Ok I'll take a look at the issue 👍

**Comment by nickboldt** [comment]
As we now include surge.sh / github.io online registries in https://workspaces.openshift.com I'm inclined to close this as won't-do, unless a compelling reason and a contribution from someone who wants/needs it comes along. 

Having chatted with Florent on this one, seems like this would not **REPLACE** the current build/release process for creating online (non-airgapped) registries, but instead supplement it with a **SECOND** set of registries for offline/airgap usage. 

So, after almost 6 months of no effort put into this... close. 

If someone wants to put work into this, please reopen it.

**Comment by nickboldt** [comment]
If we decide to do this, it's lower priority than https://github.com/eclipse/che/issues/20549
