### ISSUE TITLE
Provide RHEL-based dockerfile to build openshift connector plugin without the oc binaries

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18241]
### Is your enhancement related to a problem? Please describe.

Today Che simply reuses the openshift connector plugin, which includes binaries of `oc` for win64, mac64, and amd64. So any time you use that plugin you've downloaded a few 00s of MBs of stuff your OS will never use.

Additionally, if you're on Z or P or aarch, you will need to have a sidecar with your arch's `oc` binary, so NONE of the included binaries are useful.

### Describe the solution you'd like

A Dockerfile (or containerfile) script to build the openshift connector plugin .vsix file, but which forks the upstream code to remove its need to include the `oc` binaries. 

This would immediately be reusable for downstream too, as we would benefit from a smaller plugin in CRW too.

And, if Che decides to switch to setting their registries to be in offline/airgap mode (that is, referenced vsix files, icons, and other resources like sample projects are copied into the container image at build time), this would help keep the offline plugin registry smaller and more performant.

**Comment by svor** [comment]
@nickboldt As far as I know we don't want to modify vscode extensions for upstream but I think it makes sense to implement that for downstream in https://github.com/redhat-developer/codeready-workspaces-vscode-extensions and reuse it.
