### ISSUE TITLE
FR: two-way binary sharing between sidecars/CLI containers

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#18249]
in Haskell sidecar one of the plugin extensions (hdx4vsc debug adapter) creates a .sh script at runtime and runs it to stablish a debug session, without the need of this .sh to be marked as +x in the sidecar filesystem. this is nice because nothing needs to be fixed in the extension wether it's running in actual windows vscode or theia. 

now the other way around, while running a debug session in the same haskell sidecar, ghci app manages the runtime provided to the debug adapter and it has a :edit command so .hs haskell files within the debug session can be sent to an editor. Naturally the sidecar editor can be vim or any other terminal editor but we need to be able to set theia as the default "editor" within the sidecar and also capture any extra hint or automated action like a "go to" specific part of the file when the action is taken from the sidecar terminal to an editor binary. 

sidecars exist to cover the assumption in vscode extensions that all the needed binaries are available. in the same way there is the need to intercept stuff from the language-servers and other cli apps that expect to be running in the same context as the code editor as a binary app for interaction.

![image](https://user-images.githubusercontent.com/407397/97755106-5c136d80-1ad7-11eb-841a-7c8ce998da3f.png)
![image](https://user-images.githubusercontent.com/407397/97756043-fb853000-1ad8-11eb-96f9-19cced9493ca.png)

 this could be considered the other way around of [this one issue](https://github.com/eclipse/che/issues/16870)

**Comment by tsmaeder** [comment]
@gattytto if you can tell the involved parties where the binary is created, you can locate it in a shared folder (`/projects`). Not an option?

**Comment by gattytto** [comment]
I'd like to be able to send files to theia from sidecar containers having theia set as the default editor to those terminals, as long as the content being sent from the sidecaR/cli to theia is available to the theia container.
