### ISSUE TITLE
Working offline with Eclipse Che (Self-hosted Google Cloud)

### ISSUE THREAD

**Issue by stasfilin** [eclipse-che/che#18243]
Hi all,
I found this article: https://che.eclipse.org/working-offline-with-eclipse-che-ee5cdb29d0ec

But it's for the OpenShift version, 

Is it possible to do this for the Self-hosted Google Cloud version?

Thanks

Best Regards,
Stanislav Filin

**Comment by benoitf** [comment]
@stasfilin yes it works on any kubernetes flavor (including openshift)

**Comment by stasfilin** [comment]
@benoitf but how to get authorization link
echo ${CHE_OSO_CLUSTER//api/console}

**Comment by benoitf** [comment]
it's the kubernetes console link.
you should have that link from your google cloud account

**Comment by benoitf** [comment]
as long as you see the workspace pod by doing `$ kubectl get pods --all-namespaces` you're in the right direction
