### ISSUE TITLE
After closing the Project wizard widget by ESC select path form still opened

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1825]
Step to reproduce:
1. Select some folder
2. In context menu select Convert folder to Project 
3. In opened window select parent path 
4. Push Esc 

Should close Select Path window but closing Project wizard 

![1825](https://cloud.githubusercontent.com/assets/1636592/16978452/98570282-4e64-11e6-8c84-7ec373573cb7.gif)

**Che version:**    4.5.0

**Comment by TylerJewell** [comment]
Please provide reproduction steps + animated GIF.  Cannot be taken into a sprint without this information.

**Comment by riuvshin** [comment]
QA checked. close issue
