### ISSUE TITLE
Workspace based on the "Intellij" editor doesn't persist preferences

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#18269]
### Che version

 - [ ] latest
 - [ x ] nightly
 - [ ] other: please specify

### Steps to reproduce
 - Create custom workspace using https://github.com/che-incubator/jetbrains-editor-images/blob/master/devfiles/workspace.yaml
 - Go inside created workspace and create a project in the /projects directory (the simplest way to use maven archetypes)
 - Change color scheme (File -> Settings -> Appearance and change "Theme" to "Darcula"), pay attention that theme has been changed
 - Go to Che dashboard and stop workspace
 - Run workspace again and go to it - Pat attention that the color scheme doesn't match the previously set "Darcula"

 - Open previously created project (ensure that project is persisted)
 - Pat attention that the color scheme doesn't match the previously set "Darcula"

### Expected behavior
After workspace restart, the color scheme is "Darcula"
![Screenshot from 2020-11-03 10-24-21](https://user-images.githubusercontent.com/22724619/97969378-a2fbae80-1dc8-11eb-9e04-7d05f131fd62.png)

### Observed behavior
After workspace restart, the color scheme is default
![Screenshot from 2020-11-03 10-23-43](https://user-images.githubusercontent.com/22724619/97969582-eb1ad100-1dc8-11eb-8e2c-216bd9f6032a.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ x ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by vzhukovskii** [comment]
Probably wrong path is used in meta.yaml: https://github.com/che-incubator/jetbrains-editor-images/blob/master/devfiles/meta.yaml#L27
