### ISSUE TITLE
travis-ci and chectl

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18260]
### Is your task related to a problem? Please describe.
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

>The upcoming pricing change will affect those of you who are:
> Building on the macOS environment

chectl is using macos so it might be impacted

### Describe the solution you'd like
Maybe move from travis-ci to github actions ? or avoid macos runner on travis-ci

**Comment by tolusha** [comment]
Basically we have to move the release process to github actions
