### ISSUE TITLE
Nightly Happy Path failing because of missing chectl parameter

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18265]
### Describe the bug
The workspace for the Happy Path test is not created so the Happy Path fails. The problem is that `chectl` is expecting extra parameter which is not present int the command:

```
chectl workspace:create --start --access-token <token> --chenamespace=eclipse-che --devfile=https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/happy-path-workspace.yaml
› Current Kubernetes context: 'eclipse-che/192-168-42-57:8443/developer'
    Error: Eclipse Che server API endpoint is required. Use 
    '--che-api-endpoint' to provide it.
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run the job for testing Happy Path on nightly Che with nightly chectl.

### Expected behavior
Happy Path should pass.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`) [job](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1834/console)
   - [x] minishift (include output of `minishift version` and `oc version`) [job](https://ci.centos.org/view/Devtools/job/devtools-che-nightly-happy-path-test/269/console)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/97958715-1217d980-1dae-11eb-82a9-e0489247a15a.png)

### Installation method
   - [x] chectl
> chectl server:start --listr-renderer=verbose -a operator -p minishift --k8spodreadytimeout=360000 --che-operator-cr-patch-yaml=/tmp/custom-resource-patch.yaml --chenamespace=eclipse-che
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify Linux

### Solution
Use `chectl auth:login` command instead of requesting token from Keycloak API.

**Comment by Ohrimenko1988** [comment]
Redundant issue
