### ISSUE TITLE
It's not obvious to users that default directory for project in the workspace based on the "Intellij" IDE doesn't persist

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#18270]
### Is your enhancement related to a problem? Please describe.
It's not obvious to users that default directory for project in the workspace based on the "Intellij" IDE doesn't persist.
(Workspace created using https://github.com/che-incubator/jetbrains-editor-images/blob/master/devfiles/workspace.yaml yaml)
### Describe the solution you'd like
Persist default directory or reconfigure the "Intellij" IDE for storing projects by default to the "/projects" directory.

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse/che-plugin-registry/pull/709
