### ISSUE TITLE
Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18276]
### Describe the bug

```
 ›   Error: Error: Unable to execute helm command helm upgrade --install che --force --namespace che --set global.cheDomain=url.com --set global.tls.useSelfSignedCerts=false --set global.ingressDomain=url.com
 ›   --set cheImage=quay.io/eclipse/che-server:7.21.0 --set che.disableProbes=true  -f /home/user/.cache/chectl/templates/kubernetes/helm/che/values/tls.yaml
 ›   /home/user/.cache/chectl/templates/kubernetes/helm/che/ / 
 ›   Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "che-data-volume" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
 ›     core.PersistentVolumeClaimSpec{
 ›      ... // 2 identical fields
 ›      Resources:        core.ResourceRequirements{Requests: core.ResourceList{s"storage": {i: resource.int64Amount{value: 1073741824}, s: "1Gi", Format: "BinarySI"}}},
 ›      VolumeName:       "",
 ›   -  StorageClassName: nil,
 ›   +  StorageClassName: &"microk8s-hostpath",
 ›      VolumeMode:       &"Filesystem",
 ›      DataSource:       nil,
 ›     }

```

I apologize, I was in the process of investigating another bug when I encountered this one. Previously, I was unable to launch che, but che wasn't producing any logs. I don't believe it affects this bug, but I also don't want to assume.

![image](https://user-images.githubusercontent.com/4656027/98027367-2ff73580-1dd2-11eb-8adf-3501959c6f11.png)

While this screenshot is **after** upgrading from `7.20.1 to 7.21.0`, I had encountered the scheduling bug in 7.20.1. I then `chectl server:delete` and attempted another deploy. `chectl server:deploy -a helm -b url.com -p microk8s --debug` The failed upgrade bug above appeared.

Logs are empty.

![image](https://user-images.githubusercontent.com/4656027/98027893-f246dc80-1dd2-11eb-982c-2044a70700c9.png)

### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

I believe the minimum steps are 

Deploy

Delete

Deploy

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ x ] other: (please specify) microk8s v1.19.2

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

```
charlesrod@mainhub:~$ chectl server:deploy -a helm -b url.com -p microk8s --debug
› Current Kubernetes context: 'microk8s'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  MicroK8s preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if microk8s is installed
    ✔ Verify if microk8s is running
    ↓ Start microk8s [skipped]
      → MicroK8s is already running.
    ✔ Check Kubernetes version: Found v1.19.2-34+1b3fa60b402c1c.
    ✔ Verify if microk8s ingress and storage addons is enabled
    ↓ Enable microk8s ingress addon [skipped]
      → Ingress addon is already enabled.
    ↓ Enable microk8s storage addon [skipped]
      → Storage addon is already enabled.
    ↓ Check if cluster accessible [skipped]
  ✔ Start following logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
  ❯ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.3.4+ga61ce56
    ✔ Create Namespace (che)...does already exist.
    ✔ Check Eclipse Che TLS certificate...TLS certificate secret found
    ✔ Check Cluster Role Binding...done.
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✖ Deploying Eclipse Che Helm Chart
      →   }
 ›   Error: Error: Unable to execute helm command helm upgrade --install che --force --namespace che --set global.cheDomain=url.com --set global.tls.useSelfSignedCerts=false --set global.ingressDomain=url.com
 ›   --set cheImage=quay.io/eclipse/che-server:7.21.0 --set che.disableProbes=true  -f /home/charlesrod/.cache/chectl/templates/kubernetes/helm/che/values/tls.yaml
 ›   /home/charlesrod/.cache/chectl/templates/kubernetes/helm/che/ 
 ›   Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "che-data-volume" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
 ›     core.PersistentVolumeClaimSpec{
 ›      ... // 2 identical fields
 ›      Resources:        core.ResourceRequirements{Requests: core.ResourceList{s"storage": {i: resource.int64Amount{value: 1073741824}, s: "1Gi", Format: "BinarySI"}}},
 ›      VolumeName:       "",
 ›   -  StorageClassName: nil,
 ›   +  StorageClassName: &"microk8s-hostpath",
 ›      VolumeMode:       &"Filesystem",
 ›      DataSource:       nil,
 ›     }
 ›
 ›   Installation failed, check logs in '/tmp/chectl-logs/1604428297736'
```

### Environment
   - [ ] my computer
       - [  ] Windows 
       - [ x ] Linux : Ubuntu 20.04.1 LTS
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs

None Produced

**Comment by gnoejuan** [comment]
It's the end of my day, but I plan on trying to delete the `che-data-volume` through kubectl on my next day off.

**Comment by azatsarynnyy** [comment]
@tolusha PTAL

**Comment by gnoejuan** [comment]
Because che-data-volume had `kubernetes.io/pvc-protection` I had to patch che-data-volume. 

Example:  `kubectl -n che patch pvc che-data-volume -p '{"metadata":{"finalizers": []}}' --type=merge`

I'm now back to just the scheduling bug. As luck would have it, I now notice that the pvc is always pending. 

https://github.com/che-incubator/chectl/blob/9304a686ba9f587af35c887e50a659944a5a7676/src/api/kube.ts#L2159

This was the closest I could get to figuring out how chectl manages pv. I was trying to figure out if there was a "ghost" pv, as suggested in this answer: `[I've seen this behaviour in microk8s 1.14.1 when two PersistentVolumes have the same value for spec/hostPath/path`](https://stackoverflow.com/a/55982035) [[full question and thread]](https://stackoverflow.com/questions/44891319/kubernetes-persistent-volume-claim-indefinitely-in-pending-state). I'm currently trying to figure out my specific situation.

![image](https://user-images.githubusercontent.com/4656027/98150008-9b550c00-1e93-11eb-81bc-e7b00ab86db5.png)

There's a chance both of these bugs are beyond Che and a problem with microk8s.

**Comment by gnoejuan** [comment]
I was unable to fix this without resetting microk8s. `microk8s reset --destroy-storage`

**Comment by tolusha** [comment]
@gnoejuan 
Did you eventually deployed Eclipse Che on microk8s ?

**Comment by gnoejuan** [comment]
The first deploy is always successful. Any subsequent deploy requires resetting microk8s (nuking).
