### ISSUE TITLE
Adapt Che Theia to the latest changes in che-workspace-client lib

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18278]
### Is your task related to a problem? Please describe.
While investigating https://github.com/eclipse/che/issues/18255 I've found out the PR https://github.com/eclipse/che-workspace-client/pull/39 introduces breaking changes for the dependent downstream projects.
It breaks Che Theia runtime as Che Theia depends on this lib for Che API communications.

### Describe the solution you'd like
We need to adapt Che Theia codebase to consume the latest version of [`@eclipse-che/workspace-client`](https://www.npmjs.com/package/@eclipse-che/workspace-client) lib.

### Describe alternatives you've considered
Temporary, pin `@eclipse-che/workspace-client` dependency in Che Theia to the previous version.
I'm already testing it in the PR https://github.com/eclipse/che-theia/pull/901

### Additional context
https://github.com/eclipse/che/issues/18255

**Comment by RomanNikitenko** [comment]
Maybe the solution will be on `che-workspace-client` side
Let's wait for review https://github.com/eclipse/che-workspace-client/pull/44

**Comment by RomanNikitenko** [comment]
The PR https://github.com/eclipse/che-workspace-client/pull/44 was merged.
I'm going to prepare the corresponding PR to `che-theia` to update dependencies by new version of `che-workspace-client` as soon as new package is published on `npm` registry
