### ISSUE TITLE
[che-theia] Reverts the color theme to dark when reloading window.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#18287]
### Describe the bug

I set the color theme light. But it is reverted to the dark theme when I reload the workspace window.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify (The original build based on the master branch.)

### Steps to reproduce

1. Open the workspace.
2. Set the color theme.
3. Reload the window.
4. 

### Expected behavior

The color theme should be kept.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) But this won't depend on the runtime.
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"73ec19bdfc6008cd3ce6de96c663f70a69e2b8fc", GitTreeState:"clean", BuildDate:"2020-09-17T04:17:08Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional context

They are content of `settings.json` in the theia-ide container.

Just after I set the color theme to `light` is like below.

```
~/.theia $ cat settings.json 
{
   "files.exclude": {
      "**/.classpath": true,
      "**/.project": true,
      "**/.settings": true,
      "**/.factorypath": true
   },
   "git.autofetch": true,
   "git.user.email": "monaka@monami-ya.com",
   "git.user.name": "Masaki Muranaka",
   "editor.tabSize": 2,
   "workbench.iconTheme": "theia-file-icons",
   "git.confirmSync": false,
   "go.useLanguageServer": true,
   "git.enableSmartCommit": true,
   "workbench.colorTheme": "light",
  "workbench.appearance.colorTheme": "light",
  "chePlugins.repositories": {}
```

And after I reloaded:

```
~/.theia $ cat settings.json 
{
   "files.exclude": {
      "**/.classpath": true,
      "**/.project": true,
      "**/.settings": true,
      "**/.factorypath": true
   },
   "git.autofetch": true,
   "git.user.email": "monaka@monami-ya.com",
   "git.user.name": "Masaki Muranaka",
   "editor.tabSize": 2,
   "workbench.iconTheme": "theia-file-icons",
   "git.confirmSync": false,
   "go.useLanguageServer": true,
   "git.enableSmartCommit": true,
   "workbench.colorTheme": "dark",
  "workbench.appearance.colorTheme": "light",
  "chePlugins.repositories": {}
}
```

`workbench.colorTheme` is back to `dark`.
 `workbench.appearance.colorTheme` keeps `light` but it seems this key is ignored.

**Comment by RomanNikitenko** [comment]
Checked for `latest` and `next` versions of `che-theia` editor - can confirm - the issue is reproduced at each page refreshing.

**Comment by monaka** [comment]
/remove-lifecycle stale
This issue is still reproduced on my env ... I'll inspect it again soon.
