### ISSUE TITLE
Quarkus CLI failing to start with quota exceeded

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#18288]
### Describe the bug
Quarkus CLI devfile fails to start because of quota exceeded
Happens every run of the test suite
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/quarkus-command-mode

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: 7.20.1

### Steps to reproduce
* Start a Quarkus CLI devfile

### Expected behavior
* Quarkus CLI devfile starts successfully (including all plugins and side-cars)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) hosted che production and prod-preview clusters
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/16451875/98042527-036c0980-1e24-11eb-9f9e-e53ce5a85d8a.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) Hosted Che production and prod-preview clusters
   - [ ] other: please specify

### Eclipse Che Logs
Could not reproduce manually

**Comment by ibuziuk** [comment]
@ScrewTSW could you identify at which point the quotas have been changed and why it requires so much resources?

**Comment by ibuziuk** [comment]
@ScrewTSW 7.21.1 is on prod-preview and I can not reproduce this issue. Please provide more details and investigation results

**Comment by ScrewTSW** [comment]
Fixed by removing a hidden running workspace pod from the account's cluster console
