### ISSUE TITLE
Include default vscode extensions to Che-Theia

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#18282]
### Is your enhancement related to a problem? Please describe.

We need to include some default VS Code extension to Che-Theia

- [ ] debug-server-ready https://github.com/microsoft/vscode/tree/master/extensions/debug-server-ready
- [ ] extension-editing https://github.com/microsoft/vscode/tree/master/extensions/extension-editing
- [ ] image-preview https://github.com/microsoft/vscode/tree/master/extensions/image-preview
- [ ] search-result https://github.com/microsoft/vscode/tree/master/extensions/search-result

Binaries for the extensions could be downloaded from Open VSX Registry
- debug-server-ready https://open-vsx.org/extension/vscode/debug-server-ready
- extension-editing https://open-vsx.org/extension/vscode/extension-editing
- image-preview https://open-vsx.org/extension/vscode/image-preview
- search-result https://open-vsx.org/extension/vscode/search-result

**Comment by benoitf** [comment]
For image preview: https://github.com/eclipse-theia/theia/issues/6636

**Comment by azatsarynnyy** [comment]
`debug-server-ready` - I wonder if this is something relevant for Che?

**Comment by vitaliy-guliy** [comment]
ES Lint extension should be updated to 2.1.8 after fixing https://github.com/eclipse-theia/theia/issues/8764

**Comment by vitaliy-guliy** [comment]
There is a PR https://github.com/eclipse/che-theia/pull/942 to add `vscode.extension-editing` and `vscode.search-result` extensions, that are seems to be working.

I played a lot with `debug-server-ready` extension, but it's not clear whether it working or not, and what the extension should do exactly (based on investigating the extension sources).

We can postpone adding of `image-preview`, as it use unimplemented Custom Editor plugin API.

**Comment by ericwill** [comment]
@vitaliy-guliy what's the status here?

**Comment by vitaliy-guliy** [comment]
I'm closing this issue as non relevant anymore (nobody has asked about those extensions for a long period of time).
We can easily reopen this issue or create a new one if needed.
