### ISSUE TITLE
Introduce Git* extensions to Che-Theia

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#18281]
### Is your enhancement related to a problem? Please describe.

Need to add following VSCode extension to Che-Theia

- git-ui https://github.com/microsoft/vscode/tree/master/extensions/git-ui
- github-authentication https://github.com/microsoft/vscode/tree/master/extensions/github-authentication
- github https://github.com/microsoft/vscode/tree/master/extensions/github

They are already published to Open VSX Registry
- https://open-vsx.org/extension/vscode/git-ui
- https://open-vsx.org/extension/vscode/github-authentication
- https://open-vsx.org/extension/vscode/github

**Comment by vinokurig** [comment]
* `github-authentication` plugin registers a GitHub authentication provider specific for vscode: https://github.com/microsoft/vscode/blob/1961260ef3f6993b9c57f7dadccb00f423a1c1b2/extensions/github-authentication/src/githubServer.ts#L79
Che-Theia already has its own GitHub authentication provider: https://github.com/eclipse/che-theia/blob/f48828db6dcf691f8f2b3c887496f67c1a293a55/plugins/github-auth-plugin/src/github-auth-plugin.ts#L18
* `github` plugin is already proposed by https://github.com/eclipse/che-theia/pull/906
* `git-ui` plugin only registers one command: https://github.com/microsoft/vscode/blob/ca22de4b17af4ec84394537546998bba195e84cd/extensions/git-ui/src/main.ts#L14
and I haven't found any places where this command is used in vscode. probably this command is needed for some external plugins. I am not sure we really need this plugin.
