### ISSUE TITLE
Add Che Plug-in based on EditorConfig VS Code extension

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18297]
### Is your enhancement related to a problem? Please describe.
Che Theia used to provide [EditorConfig VS Code extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) as a built-in Che Theia Plug-in.
A built-in one has been removed in https://github.com/eclipse/che-theia/pull/912 because of:
- it is not a built-in VS Code extension, see the [README.md](https://github.com/microsoft/vscode-editorconfig#editor-config-for-visual-studio-code) in the archived repo
- the default behavior may be confusing in some cases, see https://github.com/eclipse/che/issues/18096 and https://github.com/eclipse/che/issues/16194

### Describe the solution you'd like
We can provide EditorConfig VS Code extension as a Che Plug-in.
But when working on it, we should analyze how the default behavior described in https://github.com/eclipse/che/issues/18096 and https://github.com/eclipse/che/issues/16194 can be improved.

### Additional context
https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by vitaliy-guliy** [comment]
It would be nice also to display a proposal to disable auto save ( if it's possible to disable it ) because of issues you described.

**Comment by azatsarynnyy** [comment]
Sure, it's possible to disable autosave with `editor.autoSave` preference.
But it's just a workaround of the problem with a jumping cursor. BTW, it's reproducible with a manual save as well.
There may be other workarounds, like increasing autosave timeout from default 500 ms to several secs. But...

What we should do, before adding EditorConfig Plug-in, is to investigate why the leading whitespaces are not trimmed on the current line in VS Code, but they are trimmed in Theia. With `trim_trailing_whitespace = true` option.

**Comment by vitaliy-guliy** [comment]
Need to check how it works with the latest 0.16.4 version
https://open-vsx.org/extension/EditorConfig/EditorConfig
