### ISSUE TITLE
Cloudflare Proxy and Affordability Questions

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18298]
## Summary

# Question 1: 

I'm trying to keep everything as low-cost and secure as possible. I would like to have Eclipse Che publicly accessed on my own computer. I'd like to use cloudflare as a proxy to hide my physical location, but Cloudflare and Che seems to be incompatible with each other. Cloudflare requires the certificate be issued by Cloudflare OR subscribe at the enterprise level and upload a custom cert. Cloudflare appears to have a free offering that includes an [origin certificate](https://support.cloudflare.com/hc/en-us/articles/115000479507) that I **_might_** be able to convert into the [.crt .key combo](https://stackoverflow.com/questions/13732826/convert-pem-to-crt-and-key) but that only encrypts from the origin server. The client certificate doesn't appear to have any way of installing into ingress, as in, Cloudflare only serves the certificate from the proxy.

Using Let's Encrypt, I get `SSL_ERROR_NO_CYPHER_OVERLAP`

_Would there be a way to disable ssl on Che and allow Cloudflare control SSL?_

# Question 2:

Another limitation is Cloudflare's free plan doesn't support wildcard records (it does support wildcard certs).  I couldn't find documentation on how to plan the subdomains accordingly (workplaces, url previews, any other use case). Che requires `https://plugin-registry-che.che-host.com/v3` and `https://devfile-registry-che.che-host.com` to operate correctly. Are there any more?

**Comment by tolusha** [comment]
Hello.
You didn't mention installation type you used. I assume it is operator.

1.  It is possible to set `tlsSupport` to `false` in the CR
https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L39
But theia editor will work incorrectly in this case.

2. It is possible to deploy Eclipse Che in single-host mode by setting `serverExposureStrategy` to `single-host`
https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L59-L67
