### ISSUE TITLE
Stop an already running workspace when we create and start a second workspace

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18291]
Hi team , if 1 workspace is already running, and i try to create and start 2nd workspace, it gives error saying that you can not start more than 1 workspace. Is it possible that when i start second workspace, first one should get automatically stopped. I don't want to enable this - https://www.eclipse.org/che/docs/che-7/installation-guide/running-more-than-one-workspace-at-a-time/

is there a way to achieve this ?

**Comment by l0rd** [comment]
It makes sense to ask the user if he wants to stop the active workspace and start a new one of if he wants to abort.

**Comment by akurinnoy** [comment]
I'm closing the issue because it was resolved in https://github.com/eclipse-che/che-dashboard/pull/607 and then improved in https://github.com/eclipse-che/che-dashboard/pull/618 and https://github.com/eclipse-che/che-dashboard/pull/620.
