### ISSUE TITLE
[che-operator] Make REAMDE.md files up to date

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#18295]
### Is your task related to a problem? Please describe.

Right now we have a good bank of tests in che-operator and chectl which are not documented anywhere.
### Describe the solution you'd like

Create a Readme.md to describe:
- What part of project we are covering in tests
- In which platforms we are running our tests(Also which CI we are using...)
- Describe for external contribuitors how our tests are working(how to trigger, where to see the test results etc)

**Comment by tolusha** [comment]
I also would like to extend the issue by updating README.md file in operator repository. 
Some sections are required to be reviewed.  
Also it is need to add section to mention
- how to update CRD propertly
- how to add new roles
- in which cases `olm/update-nightly-bundle.sh`  is needed to run
..etc ?
@mmorhun  @AndrienkoAleksandr

**Comment by AndrienkoAleksandr** [comment]
We should fix info about how to debug che-operator, info is outdated. And we can apply info about our VSCode tasks for development.

**Comment by tolusha** [comment]
Added some chectl usage cases, like how to deploy:
- in single-user mode
- in single-host mode
- without generating untrusted ssl certificate
etc...
