### ISSUE TITLE
Load devfiles from private gitlab repositories.

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18299]
### Is your enhancement related to a problem? Please describe.
To allow users to load devfiles from private gitlab repositories. Currently it is only possible with github.

### Describe the solution you'd like
When trying to load the devfile from a private gitlab repository, we get the following error - Failed to fetch the devfile due to "400" returned by "/api/factory/resolver". Same thing works with private github repositories.

If I copy paste the devfile on the Che UI, in Create Custom Workspaces tab - it asks me for the uname and pwd if the projects in the devfile are in private gitlab repositories. If we can configure che to ask uname and pwd before loading the devfile from the url, then it might be able to access devfile from private repo.

**Comment by skabashnyuk** [comment]
Version 13.0?

**Comment by chopraaakash91** [comment]
13.4.4

**Comment by tdc-yamada-ya** [comment]
If GitLab version is 13.0 or higher, you can use  [project personal access token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) to get raw data of repository files.

```
https://gitlab/api/v4/projects/1234/repository/files/hogehoge/raw?access_token=xxxxxxxxxx&ref=master
```

GitLab Repository Files API Document
https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository

**Comment by skabashnyuk** [comment]
There are a couple of questions that we should answer to be able to ingrate gitlab private repositories in the factory.

1. Can we ingrate Kyecloak and Gitlab. OpenID/Saml
2. with help of keycloak how to get Gitlab OAuth token.
3. With Gitlab OAuth token can/how we get content of:
    1. Devfile from 'HEAD` branch
    2. Devfile from a specific branch
    3. Devfile from a specific commitid
4. Can we use Gitlab OAuth token as a password in `.gitcredential` file to be able to clone the whole git repo later in Theia.

**Comment by chopraaakash91** [comment]
Answers to the first 2 questions- 

1. Can we ingrate Kyecloak and Gitlab. OpenID/Saml -> Yes, We have integrated Keycloak and Gitlab. The integration is quite straightforward.
2. with help of keycloak how to get Gitlab OAuth token.-> we can get the Gitlab OAuth token using the following keycloak API ->  curl -X POST https://<keycloak-endpoint>/auth/realms/<realm>/protocol/openid-connect/token  -d 'client_id=gitlab' -d 'username=xxxxxx' -d 'password=xxxxxxx' -d 'grant_type=password' -d 'client_secret=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'. It will give us the access_token.

**Comment by skabashnyuk** [comment]
CC @mshaposhnik can we close this issue?

**Comment by mshaposhnik** [comment]
Yes it fixed by https://github.com/eclipse/che/issues/18205
