### ISSUE TITLE
In Che Theia inform user when his workspace has been idled

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18303]
### Is your enhancement related to a problem? Please describe.

When a workspace is idled no message is shown to the user. User may think that the IDE is still fully working or just temporarily offline.

### Describe the solution you'd like

Show a message to the user to inform that the workspace has been stopped for inactivity. And Provide the option to restart it or to go back to create a new one.

**Comment by benoitf** [comment]
Duo of https://github.com/eclipse/che/issues/18302
