### ISSUE TITLE
Client-side service to track client state

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#1830]
### Overview

In general it would be very useful if we could automatically track changes of client state in real time along with simple mechanism to add event handlers and transparent data format to represent those events in one place and in one manner.
### Description

There is a number of possible implementations, my suggestion is to provide a service that will  track registered changes of `IDE` state:
- open/close file in an editor
- expand/collapse directory in a project tree
- etc.

Events are tracked irrespective of their origins but only those that are registered along with their handlers. Those events are processed by the service and probably transformed into internal representation comfortable for serialization and transportation.  I'm currently looking towards `Json` as it simplifies data transfer over`Json RPC` protocol.  

Finally, there are a few important points I would like to draw your attention to:
- We should definitely think on comfortable and generalized we of defining and providing of all valuable state related data.
- Another important thing is to provide a convenient and extendable way to serialize and/or transfer those events further
- It is quite obvious that we will need to track more state-related events in future, so we should also keep that in mind and think on how we can easily track new event type and represent its data further.

**Comment by TylerJewell** [comment]
@dkuleshov - can you cross link the PR for this please?  Thanks.

**Comment by dkulieshov** [comment]
This issue was resolved under https://github.com/eclipse/che/pull/2339
