### ISSUE TITLE
Cannot save

### ISSUE THREAD

**Issue by samdesire** [eclipse-che/che#18307]
I've been using Eclipse Che for months now and recently I've had this problem that doesn't let me save my files. For instance when I run my workspace and type in some code and save it, then I leave the workspace and come back all the code I had made earlier is not saved. I've tried multiple methods of removing this problem (and yes i have auto save enabled) but nothing is working. This isn't just a problem on one of my Eclipse Che  accounts but on other Eclipse Che accounts that I have. Any way I can fix this problem?

**Comment by benoitf** [comment]
Hello,
Are you talking about che.openshift.io instance ?
Is ephemeral mode enabled ? With ephemeral, data are not saved

**Comment by SamuelAdejumo** [comment]
> Hello,
> Are you talking about che.openshift.io instance ?
> Is ephemeral mode enabled ? With ephemeral, data are not saved

Am not sure if my workspace is on ephemeral mode. Is there a way to check? And if so how do I switch it back to the normal mode so that is saves?

**Comment by azatsarynnyy** [comment]
@SamuelAdejumo you can check it on the Dashboard

![image](https://user-images.githubusercontent.com/1636395/98534006-7cd48380-228c-11eb-87c4-470c3ed92dbc.png)

**Comment by SamuelAdejumo** [comment]
I was able to change it to persistent and it saves now :D thank you very much!
