### ISSUE TITLE
Disable the new updates check for IntelliJ-based Che Editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18305]
### Is your enhancement related to a problem? Please describe.
Automatic new updates check for IntelliJ-based Che Editor doesn't make much sense in the context of Che.
As all updates will be lost after restarting a workspace.

### Describe the solution you'd like
Disable the new updates check for IntelliJ-based Che Editor with the config files, if it's possible.

### Describe alternatives you've considered
We could consider saving the updates in a dedicated volume if someone thinks it makes sense.

### Additional context
See the notification, in the bottom right corner:

![image](https://user-images.githubusercontent.com/1636395/98380492-54ad1080-2051-11eb-95ad-f61268eb2810.png)

**Comment by vzhukovs** [comment]
This property can be set in `options/updates.xml`

```xml
<application>
  <component name="UpdatesConfigurable">
    <option name="CHECK_NEEDED" value="false" />
  </component>
</application>
```
