### ISSUE TITLE
Using client certificate selection prompt add  self-signed CA certificate

### ISSUE THREAD

**Issue by liangminhua** [eclipse-che/che#18304]
### Describe the solution you'd like

Using client certificate selection prompt add the public part of the self-signed CA certificate into the browser after installing Che.

[Client Certificate Selection Prompt](https://docs.microsoft.com/en-us/archive/blogs/ieinternals/client-certificate-selection-prompt)

### Additional context

like this
![image](https://user-images.githubusercontent.com/11595308/98372695-23e0d180-2079-11eb-9a6b-b48854a4c081.png)

**Comment by sleshchenko** [comment]
I'm not sure we even officially support IE but we would be happy to see such a contribution

**Comment by liangminhua** [comment]
> I'm not sure we even officially support IE but we would be happy to see such a contribution

That's a technical introduction. This technology works not only with IE, but also with Chrome, Unfortunately, it's not supported by Firefox. The screenshot is from Chrome browser.

I will try to implement this feature.
