### ISSUE TITLE
Cannot connect to a github project from intellij IDE inside Che (no git or browser installed)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18317]
### Describe the bug

Today, I wanted to try out the intellij image for Che, and then import a project, but git is not installed in the sidecar, and there's no browser available to configure github either. 

So... how can I use a git project in this IDE?

### Che version

 - [x] other: 7.20.1

### Steps to reproduce

1. Open  https://che.openshift.io/dashboard/
2. Go to Workspaces tab, then click Add Workspace -> https://che.openshift.io/dashboard/#/getstarted?tab=customWorkspace
3. in the `URL of devfile` field, enter https://raw.githubusercontent.com/che-incubator/jetbrains-editor-images/master/devfiles/workspace.yaml and click `Load devfile`
4. scroll down and click `Create & Open`

![image](https://user-images.githubusercontent.com/227597/98582740-5e24bb80-2291-11eb-9866-305ffa4fe0cd.png)

5. Watch the console messages:

![image](https://user-images.githubusercontent.com/227597/98582789-6f6dc800-2291-11eb-9f42-c639217c1ee9.png)

6. Confirm acceptance of license, etc.

![image](https://user-images.githubusercontent.com/227597/98582868-86acb580-2291-11eb-9d18-dd5846be25ac.png)

7. Click `Get from Version Control`, but git is not installed

![image](https://user-images.githubusercontent.com/227597/98582939-a04dfd00-2291-11eb-9875-f6bd14cdfc59.png)

![image](https://user-images.githubusercontent.com/227597/98583011-bcea3500-2291-11eb-9668-e388ade72a91.png)

8. Try to log in to GitHub, but no default browser installed:

![image](https://user-images.githubusercontent.com/227597/98583087-d4292280-2291-11eb-915a-af6e2a488d5f.png)

![image](https://user-images.githubusercontent.com/227597/98583152-e86d1f80-2291-11eb-8dac-10e8a43546c2.png)

### Runtime
   - [x] Openshift - che.openshift.io

### Environment
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other - Hosted: che.openshift.io

**Comment by nickboldt** [comment]
Additional bit o' confusion is that the plugin loaded according to the console above is `eclipse/ideaIC-NOVNC/2020.2.3 - IntelliJ IDEA Community Edition running on the Web with noVNC`, but:

* there's no reference to that plugin path/version from https://raw.githubusercontent.com/che-incubator/che-editor-intellij-community/master/devfiles/meta.yaml
* the latest in che's plugin registry is 2020.2.2: https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/che-incubator/intellij-community/2020.2.2/meta.yaml

So... how is this version being loaded? Custom registry in hosted che?

**Comment by vzhukovs** [comment]
> there's no reference to that plugin path/version from https://raw.githubusercontent.com/che-incubator/che-editor-intellij-community/master/devfiles/meta.yaml

`quay.io/che-incubator/che-editor-intellij-community:latest` at this moment points to `2020.2.3` version. And version is provided in https://raw.githubusercontent.com/che-incubator/che-editor-intellij-community/master/devfiles/meta.yaml
```
...
publisher: eclipse
name: ideaIC-NOVNC
version: 2020.2.3
type: Che Editor
displayName:  IntelliJ IDEA Community Edition
...
```

> the latest in che's plugin registry is 2020.2.2: https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/che-incubator/intellij-community/2020.2.2/meta.yaml

Version in plugin-registry has not been updated yet. It will be updated soon to use 2020.2.3.

**Comment by azatsarynnyy** [comment]
It seems the git binaries are missing in the IntelliJ image.
@vzhukovs could you check, please?

**Comment by benoitf** [comment]
already fixed https://github.com/che-incubator/jetbrains-editor-images/pull/17

**Comment by benoitf** [comment]
fixed by https://github.com/eclipse/che/issues/18325
