### ISSUE TITLE
Unable to deploy eclipse che with TLS enabled

### ISSUE THREAD

**Issue by veeramanikandanvv** [eclipse-che/che#18312]
I am trying to deploy eclipse che 7.21 with multiuser,single-host native gateway on kubernetes with TLS enabled.

I am seeing connection refused error when che tries to retrieve open id configuration.

Note: che is trying to access keycloak from https:// protocol as TLS is enabled, but I could see keycloak is running in http. Kindly help me

**Comment by ibuziuk** [comment]
@veeramanikandanvv please provide steps to reproduce with the deployment method and CR that was used.

**Comment by ibuziuk** [comment]
cc: @sparkoo since there is a note about single-host / native gateway in the issue

**Comment by veeramanikandanvv** [comment]
Steps to reproduce:
1. Kubernetes v.1.18 should be installed and initiate with kubeadm.
2. Calico for pod network
3. Install che with helm.

While che pod is initializing, we see connection refused when it is trying to retrieve open id configuration

**Comment by ibuziuk** [comment]
@veeramanikandanvv thanks, could you please also provide the configuration that was used? As I understand you are using singlehost + nativegateway?

**Comment by sparkoo** [comment]
@veeramanikandanvv I have no such issue deploying Che with TLS  using Helm. It should be handled fine https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/ingress.yaml#L26 
I've used minikube with this command:
```
helm dependencies update "${CHEDIR}"/deploy/kubernetes/helm/che

helm upgrade --install che --namespace che \
--set global.ingressDomain=$(minikube ip).nip.io \
--set global.serverStrategy=single-host \
-f "${CHEDIR}"/deploy/kubernetes/helm/che/values/tls.yaml \
"${CHEDIR}"/deploy/kubernetes/helm/che
```

I don't know Calico. What is it used for? Can you deploy on different cluster without it, so we can rule out it's something wrong with it?

**Comment by veeramanikandanvv** [comment]
Calico is pod network. I am using kubernetes cluster and still face the
same issue? Also can you help me in deploying keycloak in https??

**Comment by sparkoo** [comment]
@veeramanikandanvv I don't know if I can help here. What exact issue are you meeting?
You need your certificate in the `che-tls`, then you deploy with command I've copypasted before. Or I believe that chectl should work out of the box, generating self-sign cert.

**Comment by veeramanikandanvv** [comment]
No it's not working.... Eventhough I have che-tls keycloak is not
accessible with https... It's accessible only in http

**Comment by sparkoo** [comment]
I'm sorry, but I'm afraid I can't help with so little information. Please fill in all predefined questions in bug template so we can help you with your issue.
