### ISSUE TITLE
[new UD] Improve Keycloak token refreshing

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#18311]
### Is your task related to a problem? Please describe.

After introducing the `che-workspace-client` in order to perform REST API request in new dashboard ([PR](https://github.com/che-incubator/che-dashboard-next/pull/65)) it lost the ability to refresh the Keycloak token.

### Describe the solution you'd like

The `che-workspace-client` should be able to expose an Axios instance. So, we can register [interceptor](https://github.com/axios/axios#interceptors) that refreshes keycloak token. Additionally, we'll be able to refresh token depending on user activity in UD even if no API requests are done.

### Describe alternatives you've considered

As an alternative solution, provide to `che-workspace-client` ability to add/remove user defined [interceptors](https://github.com/axios/axios#interceptors). That allows us to refresh keycloak token only on API request.

**Comment by sleshchenko** [comment]
https://github.com/che-incubator/che-dashboard-next/pull/86 partially or almost fixes issue with refreshing a token on the Dashboard Next.
But there still may be some corner cases that need additional fixes, as I faced with using expired token for establishing WebSocket connection, while I'm starting a workspace in tab that was inactive for some period (~5-10 minutes):
![Screenshot_20201210_133105](https://user-images.githubusercontent.com/5887312/101769456-a7b23180-3aef-11eb-9b94-186fdb4edb9e.png)

**Comment by sleshchenko** [comment]
Another case, create Custom Workspace when token is expired:
![Screenshot_20201210_140052](https://user-images.githubusercontent.com/5887312/101769942-69694200-3af0-11eb-938d-b6ab92ba7c60.png)

**Comment by sleshchenko** [comment]
Closing the issue since the problems with requests with outdated tokens are fixed.
The websocket issue should be solved in the scope of https://github.com/eclipse/che/issues/18490.

A dedicated issue should be created to move interceptors on the workspace-client-lib side.
