### ISSUE TITLE
noNVC config panel is in spanish / ¡el panel de configuración de noNVC está en español!

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18319]
### Describe the bug

While I'm not adverse to having UIs translated to other languages, the default should be English, not Spanish.

### Steps to reproduce

See steps in https://github.com/eclipse/che/issues/18317

Then open the panel at the left side of the workspace:

![image](https://user-images.githubusercontent.com/227597/98584639-28350680-2294-11eb-9601-afebbbdf2223.png)

### Expected behavior

Default UI should be in English, with an option to switch to another language like Spanish, French, German, or Ukrainian. :D

**Comment by benoitf** [comment]
when using the same devfile referenced in the other issue, everything is in english on my side:
![image](https://user-images.githubusercontent.com/436777/98649034-59b2de00-2337-11eb-9567-c697fd1f5ca7.png)

I tested with chrome.

do you have some language preferences defined in your browser ?

**Comment by azatsarynnyy** [comment]
> the default should be English, not Spanish

The default language depends on the user's language preferences set in a browser.

For example, I have in Chrome:
`window.navigator.languages` - `["en-US", "uk-UA", "uk", "en"]`
`window.navigator.language` - `"en-US"`

In FireFox:
`window.navigator.languages` - `[ "en-US", "en" ]`
`window.navigator.language` - `"en-US"`

Both my browsers show UI in English:
![image](https://user-images.githubusercontent.com/1636395/98658704-04cd9280-234c-11eb-83bd-6d987c7c9585.png)

---

To check language preferences:
- in Chrome, go to `chrome://settings/languages` and check the `Language` section:
![image](https://user-images.githubusercontent.com/1636395/98659586-f0d66080-234c-11eb-9082-d62208ed7ed1.png)

- in FireFox, go to `about:preferences#general` and check the `Language` section:
![image](https://user-images.githubusercontent.com/1636395/98659741-1e230e80-234d-11eb-8d1b-73777aacfa74.png)

**Comment by azatsarynnyy** [comment]
I'm closing it as noVNC UI language depends on the user's browser settings.

**Comment by nickboldt** [comment]
Interesting... so it seems my browser failed to use English (Canada) and fell back to Spanish:

![image](https://user-images.githubusercontent.com/227597/98687423-b4e4d080-2337-11eb-9800-e736b2b2a5f6.png)

**Comment by sparkoo** [comment]
There is probably no Canada English on the page, so it fallback to 2nd. Sooo many English...es... ?-D
