### ISSUE TITLE
it's possible to minimize intellij and have no way to unminimize the window

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18318]
### Describe the bug

It's possible to minimize intellij and have no way to unminimize the window. This is bad UX. 

### Steps to reproduce

See steps in https://github.com/eclipse/che/issues/18317

Then ...

![image](https://user-images.githubusercontent.com/227597/98584055-55cd8000-2293-11eb-8c55-d5e663fca074.png)

Now if you minimize the IntelliJ window... it's gone. Right-click doesn't give you an option to bring it back:

![image](https://user-images.githubusercontent.com/227597/98584180-801f3d80-2293-11eb-8d63-789dae91e1a5.png)

And since firefox and xterm aren't installed, those default menu items don't do anything either. 

### Expected behavior

Window is minimized such that you can bring it back; or, there should be no way to minimize a window if you can't unminimize.

**Comment by vzhukovs** [comment]
According to the fluxbox [configuration](http://fluxbox-wiki.org/Editing_the_init_file.html) it is possible to disable minimization.
```
session.screen0.titlebar.right: Minimize Maximize Close
     You can choose what buttons are visible in the titlebar and on which side.
     Possible buttons are Stick, Menu, Shade, Minimize, Maximize and Close.
```

**Comment by azatsarynnyy** [comment]
Thank you @nickboldt for noticing that :+1: 

Fluxbox provides a way to unminimize the minimized window with help of the system menu and hidden by default Toolbar:

![Peek 2020-11-10 12-34](https://user-images.githubusercontent.com/1636395/98663282-8c69d000-2351-11eb-9b3a-afea9f776c60.gif)

**Comment by azatsarynnyy** [comment]
@vzhukovs I think it a nice idea to disable the minimize buttons. As they provide no value for the user and even leads to confusing behavior.
@vzhukovs please, create an issue for that improvement. Thanks!

**Comment by azatsarynnyy** [comment]
I'm closing it as the solution has been provided and @vzhukovs is going to create an issue for further enhancement.
