### ISSUE TITLE
[ux] copy and paste does not work in IntelliJ editor, and URL field can't figure out that github.com = https://github.com

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18328]
### Describe the bug

Today, I wanted to try out the intellij image for Che, and then import a project, but using the git UI is a bit more difficult than it needs to be as there's no copy and paste and the UI needs to know which protocol to use in the URL (can't just sssume https://).

### Che version

 - [x] other: 7.20.1

### Steps to reproduce

1. Open  https://che.openshift.io/dashboard/
2. Go to Workspaces tab, then click Add Workspace -> https://che.openshift.io/dashboard/#/getstarted?tab=customWorkspace
3. in the `URL of devfile` field, enter https://raw.githubusercontent.com/che-incubator/jetbrains-editor-images/master/devfiles/workspace.yaml and click `Load devfile`
4. scroll down and click `Create & Open`

![image](https://user-images.githubusercontent.com/227597/98582740-5e24bb80-2291-11eb-9866-305ffa4fe0cd.png)

5. Watch the console messages. Confirm acceptance of license. Click `Get from Version Control`

Because there's no way to copy and paste into the field, the user is forced to type it in by hand... and if you forget the https:// prefix, you get:

![image](https://user-images.githubusercontent.com/227597/98737417-26427480-2374-11eb-98c9-752958b5bd5d.png)

So two UX enhancements are possible here:

- [ ] support copy and paste
- [ ] instead of an error message, deduce that "github.com" is a host name and prepend the https:// for the user. 

These might both be features of IntelliJ itself, so I'm not sure if this is possible... but it would make UX better.

### Runtime
   - [x] Openshift - che.openshift.io

### Environment
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other - Hosted: che.openshift.io

**Comment by vzhukovs** [comment]
If url field omits scheme, then IntelliJ Idea Community Edition will try to look for a local directory that represents a git repository, so url scheme is a mandatory parameter during the project importing.

**Comment by mmorhun** [comment]
This issue actually reports two problems:

1. **Copy-paste from user PC (browser) into remote desktop (noVNC) does not work**. This is sort of expected that direct copy-paste is not working in noVNC. However there is a clipboard functionality which can transfer a buffer inside remote desktop (tested with both Firefox and Chrome):
![copy-paste-novnc](https://user-images.githubusercontent.com/15607393/98793765-02813c00-2411-11eb-9b4e-a54e7a1f5f6a.png)
I think corresponding improvment should be done on noVNC side.

2. **URL field can't figure out that github.com = https://github.com**. This is sort of expected to me. The editor cannot know if user wants to use `https` or `ssh` to clone the project. Also this happens on the IntelliJ Idea side, so the improvement should be done there...

**Comment by azatsarynnyy** [comment]
1. The clipboard functionality works well and as expected with noVNC:

![Peek 2020-11-11 14-19](https://user-images.githubusercontent.com/1636395/98811187-18026000-2429-11eb-8f6f-d06b144b7c74.gif)

2. URL validation is a feature of IntelliJ IDEA itself.

So, I'm closing it as there're no bugs with IntelliJ-based Che Editor.

**Comment by nickboldt** [comment]
Is there no way to have the intelliJ VM inside noVNC listening for clipboard activity directly, without the extra paste-then-paste again functionality?

**Comment by vzhukovs** [comment]
AFAIK, it is not possible without modification noVNC source code.

**Comment by ericwill** [comment]
> Is there no way to have the intelliJ VM inside noVNC listening for clipboard activity directly, without the extra paste-then-paste again functionality?

Most VNC clients have a clipboard pass-through system between the connecting machine and the host machine. Since this is all running on containers, that's unlikely to work.

**Comment by azatsarynnyy** [comment]
noVNC uses its own intermediate clipboard because of the browser's security restrictions on accessing the system clipboard directly from an HTML Canvas with the Clipboard API.
From https://github.com/novnc/noVNC/issues/943 it seems that there were some attempts to work it around but no avail yet.
