### ISSUE TITLE
Disable window minimization for custom desktop based editors

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#18321]
### Is your task related to a problem? Please describe.
As an internal task for https://github.com/eclipse/che/issues/18318 there is a need to disable window minimization in `fluxbox`.

### Describe the solution you'd like
The following property needs to be configured in order to disable minimization:
```
session.screen0.titlebar.right: Minimize Maximize Close
     You can choose what buttons are visible in the titlebar and on which side.
     Possible buttons are Stick, Menu, Shade, Minimize, Maximize and Close.
```

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by nickboldt** [comment]
Can we prioritize this for 7.22? Or if not, 7.24?

**Comment by vzhukovs** [comment]
The concept of opened editor is not suppose to show the toolbar as for user it is completely useless. Better solution will be to disable minimize window at all. 

> Can we prioritize this for 7.22? Or if not, 7.24?

cc @azatsarynnyy

**Comment by azatsarynnyy** [comment]
@nickboldt `minimize` button has been removed https://github.com/che-incubator/jetbrains-editor-images/pull/18
