### ISSUE TITLE
[ux] Can't open .md file OOTB in IntelliJ 2020.2.3 inside che.openshift.io

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18329]
### Describe the bug

Seems I can't open a .md file in Intellij 2020.2.3 inside hosted che.

### Che version

 - [x] other: 7.20.1

### Steps to reproduce

1. Open  https://che.openshift.io/dashboard/
2. Go to Workspaces tab, then click Add Workspace -> https://che.openshift.io/dashboard/#/getstarted?tab=customWorkspace
3. in the `URL of devfile` field, enter https://raw.githubusercontent.com/che-incubator/jetbrains-editor-images/master/devfiles/workspace.yaml and click `Load devfile`
4. scroll down and click `Create & Open`

![image](https://user-images.githubusercontent.com/227597/98582740-5e24bb80-2291-11eb-9866-305ffa4fe0cd.png)

5. Watch the console messages. Confirm acceptance of license. Click `Get from Version Control` and open a project like https://github.com/redhat-developer/codeready-workspaces/ -- note that you have to type it in my hand (see https://github.com/eclipse/che/issues/18328 )

6. Open the README.md file in the above repo:

![image](https://user-images.githubusercontent.com/227597/98737918-f34cb080-2374-11eb-9dfb-5f2c0c33d2c9.png)

7. Click the 'Follow the instructions' link:

![image](https://user-images.githubusercontent.com/227597/98738007-0d868e80-2375-11eb-8709-13ec98c57ce0.png)

Should we install chrome or firefox inside the container?

**Comment by mmorhun** [comment]
@vzhukovs it looks like a bug, not a question. Why do you think that this issue is a question?

**Comment by vzhukovs** [comment]
@mmorhun because it is the question around missed installed libraries needed to support markdown plugin, which is actually internal thing according to classification of issue type. Created related issue: https://github.com/eclipse/che/issues/18336 with the following PR https://github.com/che-incubator/jetbrains-editor-images/pull/19

**Comment by vzhukovs** [comment]
Closing the issue because it has been fixed by https://github.com/che-incubator/jetbrains-editor-images/pull/19
