### ISSUE TITLE
Detector of VFS high level events related to client side state

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#1832]
### Overview

The idea is to provide a detector or detectors to be able to transfer all client side related events that happens on `VFS` through some event transport from server to client.
### Description

We need to be able to track events that impact client side and happens on server side on virtual file system so we could properly correspond. The most obvious example of such detector usage is tracking of file content changes. The workflow is the following:
- A user opens a file in `IDE` editor (a new editor tab with file's content)
- Client-side sevice tracks sees state changes and reports to the server-side that a file is opened
- Now server-side detector is aware of that and starts tracking of that file's state on `VFS`
- It watches and knows when changes (irrespective of source) are made
- It informs (via event transport) client-side that file's content is changed
- Client updates file's content in an editor's tab

**Comment by TylerJewell** [comment]
@dkuleshov - can you cross-link the PR for this please?

**Comment by dkulieshov** [comment]
This issue was resolved under #2339
