### ISSUE TITLE
[ux] Fullscreen error in IntelliJ 2020.2.2 in Che

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18330]
### Describe the bug

UI provides noVNC panel, which includes a fullscreen button, which doesn't work and instead throws an unclearable error.

Workaround: close and reopen the workspace. 

### Che version

 - [x] other: 7.20.1

### Steps to reproduce

1. Open  https://che.openshift.io/dashboard/
2. Go to Workspaces tab, then click Add Workspace -> https://che.openshift.io/dashboard/#/getstarted?tab=customWorkspace
3. in the `URL of devfile` field, enter https://raw.githubusercontent.com/che-incubator/jetbrains-editor-images/master/devfiles/workspace.yaml and click `Load devfile`
4. scroll down and click `Create & Open`

![image](https://user-images.githubusercontent.com/227597/98582740-5e24bb80-2291-11eb-9866-305ffa4fe0cd.png)

5. Watch the console messages. Confirm acceptance of license. 

6. Open noVNC panel. click the fullscreen icon. Get this:

![image](https://user-images.githubusercontent.com/227597/98755970-98788080-2397-11eb-8230-21eb030f93d5.png)

**Comment by mmorhun** [comment]
Confirm the issue, I can see the same error which is not disappeared until I refreshed the tab.
Probably, this happens because of iframe.

**Comment by azatsarynnyy** [comment]
> Probably, this happens because of iframe.

most likely yes
I've checked with the editor opened in a separate browser's tab (without dashboard) - it works well.

**Comment by azatsarynnyy** [comment]
noVNC can't go to a fullscreen mode due to the browser's security restrictions. The IFRAME that Dashboard provides for embedding an IDE should allow a fullscreen mode for any nested content. I've sent a PR to fix it on the Dashboard side.

Thanks for noticing it @nickboldt !
