### ISSUE TITLE
[docs] env vars with double `_` are not rendered correctly in the documentation

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18345]
env vars with double `_` are not rendered correctly in the documentation

Example: CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB

in the docs yaml displayed like: https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/

![image](https://user-images.githubusercontent.com/1461122/98935710-36796180-24e4-11eb-924d-d46fbc08c406.png)

This issue is also relevant to the product CRW docs:

example:

https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/html/installation_guide/advanced-configuration-options_crw#allowing_user_defined_workspace_namespaces

![image](https://user-images.githubusercontent.com/1461122/98935843-6b85b400-24e4-11eb-87bd-bd88b04cfb55.png)

The correct env var name is `CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED`

**Comment by boczkowska** [comment]
The formatting was fixed in one instance, but the docs need to be scoped for other bugs like these. Opening the Jira issue for the docs team, the progress can be tracked here https://issues.redhat.com/browse/RHDEVDOCS-2658
