### ISSUE TITLE
Promote Dashboard Next

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18348]
### Is your task related to a problem? Please describe.
We have a pretty full MVP for Dashboard Next. It's a good time to start promoting it.

#### Prereq:
- tests
- docs

### Describe the solution which should be implemented
Dashboard Next is only available on the Che installation on the `{CHE_HOST}/dashboard` path.

### Describe the solution you'd like
Dashboard and Dashboard Next are both available on the cluster, but Dashboard Next is the default one.
So, when a user opens like che.openshift.io, he gets redirect to che.openshift.io/dashboard/next (the same with $che_host/f?url=)
Users are able to reach old dashboard with the direct link che.openshift.io/dashboard.

P.S. CRW as previously should use the existing dashboard, and at the time we decided Dashboard Next is ready - we just replace dashboard there.

### Describe alternatives you've considered
The ideal solution would be:
Dashboard gets banner "Dashboard next now is available. Click here to try it out."
Dashboard Next gets the banner "Click here to save Dashboard Next as your default one."
Dashboard Next has someplace where a user is able to configure the default dashboard and return back to the old dashboard if needed.
^ but seems it needs more work which I'm not sure worths time.

**Comment by dmytro-ndp** [comment]
@sleshchenko: from Che QE team we have 8 Dashboard related tests at the moment:
- [Dashboard tests](https://github.com/eclipse/che/tree/master/tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard)
- [Workspaces tests](https://github.com/eclipse/che/tree/master/tests/legacy-e2e/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces)

Here the nightly E2E tests report which includes Dashboard and Workspaces tests: http://artifacts.ci.centos.org/devtools/che/che-nigthly-multiuser-all-test/279/report/site/failsafe-report.html

It would be nice to see more detailed changes list (PRs?) in _Dashboard Next_ to help Che QE team to estimate E2E tests update effort.

**Comment by dmytro-ndp** [comment]
@sleshchenko: do you have plan to update and to create more E2E tests on Dashboard side https://github.com/eclipse/che/issues/16910?

**Comment by sleshchenko** [comment]
As defined in the https://github.com/eclipse/che/issues/18391 the prerequisite for it from QE side are Stages 0 and 1

**Comment by sleshchenko** [comment]
@dmytro-ndp we want to cover all Dashboards functionalities with e2e testing but at this point there is no concrete plan with a timeline

**Comment by sleshchenko** [comment]
The plan is changed. We're going to switch the dashboard to react-based one in 7.25

**Comment by sleshchenko** [comment]
7.26 SNAPSHOT should already use new dashboard since https://github.com/eclipse/che/pull/18549 and https://github.com/eclipse/che-dashboard/pull/138 are merged :tada:
