### ISSUE TITLE
Publish to GitHub command doesn't make sense

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#18341]
### Describe the bug

The `github` vscode built-in plugin is needed to be able to git push to https repository via authentication instead of entering credentials, see https://github.com/eclipse/che-theia/pull/906 where a new brunch is pushed without entering credentials.
At the same time this plugin contributes `Publish to GitHub` command which creates a new repository from the opened workspace folder. It makes sens in theia or vscode where you can open a workspace from any folder and then publish it on GitHub. But in Che-Theia there is a predefined workspace folder `/projects`, so it makes no sens to create a repository from this directory.
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Run `Publish to GitHub` command.
2. Click `Allow` in the sign-in notification.
3. See a quick pick which asks to create a GitHub repository from `/projects` folder:
![screenshot-che openshift io-2020 11 11-16_20_11](https://user-images.githubusercontent.com/7668752/98822831-fbbaef00-2439-11eb-9c90-27538f82fa26.png)

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
> But in Che-Theia there is a predefined workspace folder /projects, so it makes no sens to create a repository from this directory

Right, `/projects` is a default Workspace Root Folder ATM. At least, until we're done with [Multi-root Che Theia Workspaces, by default](https://github.com/eclipse/che/issues/17212)

But in Che Theia, it is possible to open/add any folder as a Workspace Root Folder, with the `File > Open/Add Workspace Roots...` commands. So, I'd keep this command as it is to provide a way to convert any folder into a git repo from Che. I think it's a nice feature.

BTW, I don't think that having `Publish to GitHub` command is a bug. Even, if we'll decide to get rid of it, I'd say it's rather an enhancement than a bug :slightly_smiling_face:
