### ISSUE TITLE
[hosted Che] Users shouldn't be redirected to Red Hat SSO without being informed.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18372]
### Describe the bug
We provide factory link in Github projects, websites, guides, etc ... 
People clicking on a factory link may not know what it is about.
When clicking a factory link, it is redirected to Red Hat SSO. It is hard for the user to understand how it is related to Che and where he is.
Some users may just give up at this point being afraid not knowing what's happening.

### Expected behavior
We should have a intermediate page that would:
- Explain what is hosted che
- Inform that he is going to be redirected in 20 seconds
- Provide a link to perform the redirection right away

**Comment by gattytto** [comment]
maybe [this](https://github.com/eclipse/che/issues/18306) is related. Allowing anonymous users may just continue the factory process and leave the user in a working workspace, then display a warning like: "register to claim this workspace, this workspace is ephemereal, etc"..

**Comment by sunix** [comment]
@gattytto I don't think we can handle the load having too many bots starting anonymous workspaces for mining ...

**Comment by ibuziuk** [comment]
Hosted Che is Eclipse Che hosted by Red Hat and this info is already in the official docs / terms of service - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/ (Red Hat account is a pre-requirment)

**Comment by sunix** [comment]
@ibuziuk the point is can we tell the user what it is about before being redirected to Red Hat SSO ?

**Comment by ibuziuk** [comment]
@sunix thecnically it should be possible to do on the Upstream level - showing the message that you are not authorized and will be redirected to the login page

**Comment by sunix** [comment]
you mean possible: possible to implement that? or there is such a feature we can configure that?

**Comment by ibuziuk** [comment]
should be possible to implement on the UD level  - showing the message before the login page redirection.

**Comment by ibuziuk** [comment]
I believe we should close it as documented - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#registering-to-hosted-che_che
