### ISSUE TITLE
Hosted Che: Do we have metrics, that shows how many users are giving up after being redirected to Red Hat SSO?

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18373]
## Summary
I suspect that we have many new users giving up after being redirected to Red Hat SSO.
It would be nice to know and see the benefits of https://github.com/eclipse/che/issues/18372

**Comment by ibuziuk** [comment]
Ther is no such a metric. Red Hat account is a prerequrment for using Hosted Che https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#registering-to-hosted-che_hosted-che
