### ISSUE TITLE
Happy path test workspace failed on start workspace task because of dockerhub image pull rate limit exceeded for images

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18380]
### Describe the bug
On CRW Jenkins the Happy path test workspace failed on start workspace task because of dockerhub image pull rate limit exceeded for images:
- centos/mysql-57-centos7
- mariolet/petclinic:d2831f9b

```
✓ Open workspace (4625ms)
          ▼ Ide.waitAndSwitchToIdeFrame
          ▼ Ide.waitPreloaderVisible
    1) Wait for workspace readiness


  1 passing (6m)
  1 failing

  1) Validation of workspace start
       Wait for workspace readiness:
     TimeoutError: Exceeded maximum visibility checkings attempts for 'By(css selector, .theia-preload)' element, timeouted after 360000
      at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:146:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

![screenshot-Wait_for_workspace_readiness (3)](https://user-images.githubusercontent.com/1197777/99285267-feee1a80-283f-11eb-8e3e-5d08d62fa6a2.png)

https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/3980/artifact/logs-and-configs/kubectl/events.txt
> 5m32s       Normal    Pulling                 pod/workspacefphemfd2s1hg8yje.workspace-6779995476-ct8gx    Pulling image "**mariolet/petclinic:d2831f9b"**
> 5m32s       Warning   Failed                  pod/workspacefphemfd2s1hg8yje.workspace-6779995476-ct8gx    Failed to pull image "mariolet/petclinic:d2831f9b": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: **You have reached your pull rate limit.** You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> 5m32s       Warning   Failed                  pod/workspacefphemfd2s1hg8yje.workspace-6779995476-ct8gx    Error: ErrImagePull
> 5m32s       Normal    Pulling                 pod/workspacefphemfd2s1hg8yje.workspace-6779995476-ct8gx    Pulling image "**centos/mysql-57-centos7**"
> 5m32s       Warning   Failed                  pod/workspacefphemfd2s1hg8yje.workspace-6779995476-ct8gx    Failed to pull image "centos/mysql-57-centos7": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: **You have reached your pull rate limit**. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> 5m32s       Warning   Failed                  pod/workspacefphemfd2s1hg8yje.workspace-6779995476-ct8gx    Error: ErrImagePull

Possible solution: move next Happy path tests specific images to quay.io:
- maxura/che-server 
- mariolet/petclinic:d2831f9b

**Comment by benoitf** [comment]
do we know how many image pull requests to dockerhub are generated by each happy path test ?

**Comment by dmytro-ndp** [comment]
@benoitf: for _Multi Host Eclipse Che_ https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/3980/artifact/logs-and-configs/kubectl/events.txt :
- maxura/che-server
- centos/postgresql-96-centos7:9.6
- mariolet/petclinic:d2831f9b
- centos/mysql-57-centos7

For _Single Host Che_: +1:
- docker.io/traefik:v2.2.8

**Comment by benoitf** [comment]
because it looks like the 200 pulls are reached in very few launches

**Comment by dmytro-ndp** [comment]
I think it's because CRW Jenkins nodes use single IP address to go outside VPN.
