### ISSUE TITLE
Unable to edit PersistentVolumeClaim for Postgres when deploying eclipse che using chectl and Operator

### ISSUE THREAD

**Issue by veeramanikandanvv** [eclipse-che/che#18382]
Unable to edit PersistentVolumeClaim for Postgres when deploying eclipse che using chectl and Operator. 
As a result of the above, we see postgres pod is in pending status. 
Please help us on the same.

**Comment by dimgsg9** [comment]
Please provide complete details:

1. What are you trying to achieve and why are you editing PersistentVolumeClaim for Postgres? What parameters do you want to change?
2. What exactly do you mean by saying "Unable to edit"?
3. Please provide full command that you're executing to deploy Eclipse Che with all arguments.
4. What environment are you using? What version of `chectl` do you have installed?

**Comment by veeramanikandanvv** [comment]
i am trying to deploy eclipse che with chectl using operator on kubernetes platform.
When executing the below command, 
chectl server:deploy --installer=operator --domain=10.9.87.65.nip.io --multiuser --cheboottimeout=80000 --platform=k8s --deployment-name=che --che-operator-cr-patch-yaml=/root/che-operator/operator-patch.yaml

we see PVC's are getting created for Postgres and Keycloak. Can you please help us in binding the PVC with the volume?

**Comment by dimgsg9** [comment]
Are you using managed Kubernetes from any cloud provider or a local/on-prem instance of k8s? In order words, are you deploying locally or in the cloud (https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che/)? 

Did you check if any persistent volumes (PVs) were successfully created?

**Comment by veeramanikandanvv** [comment]
i am trying with On-Premise Kubernetes cluster.

**Comment by ibuziuk** [comment]
@veeramanikandanvv please update the issue based on the template with clear steps to reproduce
