### ISSUE TITLE
User deletion API returns 500 response when deletion request is accepted

### ISSUE THREAD

**Issue by rajivnathan** [eclipse-che/che#18383]
### Describe the bug

When using the Che User Delete API:
`/api/user/<user-id>`

As response, you can get 204 or 500 response code:
204 means that everything goes well, user is fully removed
500 (with body like: "User has workspace that is not stopped yet. Try again") need to retry probe, in some delay reasonable delay can be: 5- 30 sec.

Shouldn't this API return a 202 response code instead of 500 so that it's easier to differentiate between an error case and when things are working as expected?

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

`curl -iv -X DELETE "https://che-vp-che.apps.che-dev.<cluster>/api/user/<user-id>" -H "Accept: application/json" -H "Authorization: Bearer <Keycloak token>"`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
`./chectl server:deploy -n toolchain-che -p openshift --installer operator`
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by alexeykazakov** [comment]
cc: @ibuziuk

**Comment by ibuziuk** [comment]
This should be adressed in the new versions with https://github.com/eclipse/che/pull/18240
409 will be thrown if there is a conflict exception and retry is required

**Comment by ibuziuk** [comment]
The fix is merged anf will be available in 7.20.0 / CRW 2.6

**Comment by alexeykazakov** [comment]
Returning 409 when you just need time to delete the workspace looks a bit weird to be honest. There is no conflict the client can fix.
It should be 202 I think. And ideally something the client can use to check the actual status of that async deletion.

**Comment by sleshchenko** [comment]
202 may create an impression that the user is supposed to be removed asynchronious but in fact, it's not. So, the client needs to make another request to remove the user once workspaces are stopped.

I'm OK with 202 if it does not lead to confusion (at least API docs describe clearly behavior) or method to reworked to be asynchronious.

**Comment by alexeykazakov** [comment]
Hm.. I thought this is exactly what Che is doing...
if there is a running workspace when the the delete endpoint is called then Che returns 409/202/whatever and meanwhile stops the workspace and then deletes the user.
Are you saying it's not how it works and the user still needs to stop the workspace manually first before proceeding with the user deletion API?

**Comment by ibuziuk** [comment]
> Are you saying it's not how it works and the user still needs to stop the workspace manually first before proceeding with the user deletion API?

it works as you expect just instead of 409 (that will be in CRW 2.6) for now the response will be 500 with `User has workspace that is not stopped yet. Try again` that indicates that retry is required.
This isssue is just about improving the REST semantics

**Comment by alexeykazakov** [comment]
Thanks for the clarification. Then I think 202 would be more appropriate response. But it's not super critical of course.
