### ISSUE TITLE
[helm] Failed to deploy Eclipse Che using helm v3.4.1

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18396]
### Describe the bug
Failed to deploy Eclipse Che using helm v3.4.1

### Che version
 - [x] nightly

### Steps to reproduce
1. Install helm https://helm.sh/docs/intro/install/
2. Deploy Eclipse Che using chectl

### Expected behavior
Eclipse Che is deployed

### Runtime
   - [x] minikube 1.14.0

### Screenshots
```
 ✖ Updating Helm Chart dependencies
      → Error: no cached repository for helm-manager-1067d9c6027b8c3f27b49e40521d64be96ea412858d8e45064fa44afd3966ddc found. (try 'helm repo update'): open /home/tolusha/.cache/helm/repository/helm-manager-1067d9c6027b8c3f27b49e40521d64be96ea412858d8e45064fa44afd3966ddc-ind
…
      Deploying Eclipse Che Helm Chart
 ›   Error: Error: Command failed with exit code 1: helm dependencies update --skip-refresh /home/tolusha/.cache/chectl/templates/kubernetes/helm/che/
 ›   Error: no cached repository for helm-manager-1067d9c6027b8c3f27b49e40521d64be96ea412858d8e45064fa44afd3966ddc found. (try 'helm repo update'): open 
 ›   /home/tolusha/.cache/helm/repository/helm-manager-1067d9c6027b8c3f27b49e40521d64be96ea412858d8e45064fa44afd3966ddc-index.yaml: no such file or directory
 ›   Installation failed. Error log: /home/tolusha/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1605683982835
```

### Installation method
   - [x] chectl
     * `chectl server:deploy --platform minikube --installer helm -m`
     * `chectl/0.0.20201110-next.4213cef linux-x64 node-v10.23.0`

### Environment
   - [x] my computer
       - [x] Linux

**Comment by t1m0thyj** [comment]
Am seeing the same issue and it's blocking me from using Che. I'm unable to run `server:deploy` using Docker Desktop and Helm on Windows 10.
- chectl version: 0.0.20201117-next.7c15cbc
- Docker Desktop version: 2.5.0.1
  - Engine version: 19.03.13
  - Kubernetes version: 1.19.3
- Helm version: 3.4.1

**Comment by tolusha** [comment]
@t1m0thyj 
To unblock try downgrade helm (if possible) or use `--installer operator`

**Comment by ath0mas** [comment]
Same error with Helm 3.4.1 and 3.4.0
Downgrading to Helm 3.3.4: `Command server:deploy has completed successfully` 👍

**Comment by flacatus** [comment]
Fixed after merge https://github.com/che-incubator/chectl/pull/1011

**Comment by prashant-rathi** [comment]
Same issue with Helm 3.6.3. 

Error: Command failed with exit code 1: helm dependencies update /usr/local/lib/chectl/templates/kubernetes/helm/che
