### ISSUE TITLE
Basic factory flow with public bitbucket URL-s

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#18397]
### Is your task related to a problem? Please describe.
Implement Factory resolution process for public Bitbucket repositories (at server side).
That means ability to accept factories from public Bitbucket repos.

E.g the flow is:
1) Admin configures inthegration of Che and Bitbucket, setting `bitbucket.endpoint` property pointing to Bibucket host address.
2) User creates (or update existing) public Bitbucket repository containing devfile;
3) User is able to execute factory in general manner, i.e. `https://che-host/f?url=https://bitbucket.host/scm/project/repo...`

### Describe the solution you'd like
Implement all necessary server-side code to accept bitbucket factories (paremeters resolver, URL parsers etc).
Bitbucket URL are detected by matching factory host with the `bitbucket.endpoint` property.

### Additional context
 https://github.com/eclipse/che/issues/18397

**Comment by skabashnyuk** [comment]
P1 as a major part of  https://github.com/eclipse/che/issues/18397
