### ISSUE TITLE
Document how to configure the namespace per user strategy

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18390]
### Is your task related to a problem? Please describe.
It looks like the kubernetes namespace per user strategy is not set by default in non Openshift installation.

See: https://github.com/eclipse/che/issues/18381

We should document how to configure the namespace per user strategy.

https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-namespace-strategies/

### Describe the solution you'd like
> I don't think so and I agree that this should be at least documented. Something like "if you want to have namespace per user strategy, grant these cluster permissions `ClusterRole blablabla` to `che` SA and set `server.workspaceNamespaceDefault:'che-<username>'`"...

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2573

**Comment by themr0c** [comment]
@sunix Is the issue still relevant?

**Comment by sunix** [comment]
@themr0c I don't know, I have an existing installation, workspaces are all running in the same namespace and not sure what is the procedure to fix it.

**Comment by boczkowska** [comment]
@sunix 
@sparkoo has added some documentation in this PR https://github.com/eclipse/che-docs/pull/1747
Here it is on the website, PTAL https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-namespace-strategies/#_one_namespace_per_user_strategy

Is this sufficient or needs to be expanded?

**Comment by sunix** [comment]
@boczkowska I will try to update my own che cluster to see if this is OK. Closing for now, will open a new one if I have any issue.

**Comment by sunix** [comment]
Just a question:

> By default, every workspace is deployed in a distinct Kubernetes namespace or OpenShift project,

I thought the default was 1 namespace per user ?

**Comment by sparkoo** [comment]
@sunix I can see the changeset comes in this PR https://github.com/eclipse/che-docs/pull/1741, so it's better to ask @themr0c. I know that 1 namespace per user is the desired default, but I'm not sure it's default for all deployments. TBH I've lost a track. Maybe @tolusha can tell if all deployments has default 1ns/user ?

**Comment by skabashnyuk** [comment]
Already implemented
