### ISSUE TITLE
Java seems to have issues creating UnixDomainServerSocket on persistent storage

### ISSUE THREAD

**Issue by sideeffffect** [eclipse-che/che#18394]
Java seems to have issues creating a `UnixDomainServerSocket` when using the _persistent storage_ feature. This has been observed on the hosted instance `che.openshift.io`.
Is that something to be expected?

I'm not sure that it is indeed the case, more detailed investigation would be needed to have 100% proof.

But it would explain, why there are issues when importing a Scala project on Che (with persistent storage). sbt (the Scala build tool), during the import of the project, tries to create a Unix socket on the filesystem but doesn't seem to be able to do so. That causes it to get into a weird state, which blocks the import.

It is reproducible by creating a new Scala project from the available template.

Issue on Metals (the Scala language server) https://github.com/scalameta/metals/issues/2235
Issue on sbt https://github.com/sbt/sbt/issues/6101

/cc @eatkins @tgodzik

**Comment by skabashnyuk** [comment]
@sideeffffect thank you for this bugreport. Could you please follow Che's bug template report? Thanks.
