### ISSUE TITLE
GitHub related E2E java selenium tests are failing on Centos CI

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18401]
### Describe the bug
GitHub related E2E java selenium tests are failing on Centos CI, for example:
https://ci.centos.org/view/Devtools/job/devtools-che-nightly-oauth-test/284/console
```
2020-11-18 04:39:27,928[pool-4-thread-2]  [ERROR] [.e.c.s.c.i.SeleniumTestHandler 262]  - Failed to inject fields in org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolderTest
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.kohsuke.github.HttpException: {"message":"Bad credentials. The API can't be accessed using username/password authentication. Please create a personal access token to access this endpoint: http://github.com/settings/tokens","documentation_url":"https://docs.github.com/articles/creating-a-personal-access-token-for-the-command-line"}
  at org.eclipse.che.selenium.core.client.TestGitHubRepository.<init>(TestGitHubRepository.java:71)
  while locating org.eclipse.che.selenium.core.client.TestGitHubRepository
    for field at org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolderTest.testRepo(DirectUrlFactoryWithRootFolderTest.java:40)
  while locating org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolderTest
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run `org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolderTest` java selenium test.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: Centos CI

### Additional context
Beginning November 13th, 2020, GitHub has not longer accepted account passwords when authenticating with the REST API and has required the use of token-based authentication  https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/

### Solution
generate token for `che6ocpmulti` user [1], and replace password with token in the code [2] 
[1] https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
[2] https://github.com/eclipse/che/blob/master/tests/.infra/centos-ci/functional_tests_utils.sh#L397

**Comment by SkorikSergey** [comment]
Java selenium tests deleted for `Eclipse Che` repo - https://github.com/eclipse/che/pull/19519.
