### ISSUE TITLE
Move Che Theia nightly/main builds from ci.centos.org to GitHub Actions

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18407]
### Is your task related to a problem? Please describe.
As Red Hat supported ci.centos.org is going to be deprecated soon, we need to migrate Che Theia nightly/main builds to more community-friendly GitHub Actions.

### Describe the solution you'd like
Implement Che Theia nightly/main builds as GitHub Workflow.

### Additional context
https://github.com/eclipse/che-theia/blob/master/cico_build_master.sh

**Comment by benoitf** [comment]
here the `most difficult` part is to grab the keys to deploy on Akamai/cdn

**Comment by azatsarynnyy** [comment]
`eclipse/che-theia-dev:next` has been published successfully,
but `eclipse/che-theia-dev:sha` failed with `denied: requested access to the resource is denied`

Will try another run. If fails then will try `docker/build-push-action@v2`

**Comment by azatsarynnyy** [comment]
Done - https://github.com/eclipse/che-theia/actions/runs/540837999/workflow
