### ISSUE TITLE
Expose factory URL when loading a custom devfile

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18415]
### Is your enhancement related to a problem? Please describe.

To make it more obvious that the factory URL loader exists and can be used more easily than the paste-click-click approach to loading a custom devfile, why don't we actually publish the URL in the UI once it's loaded?

1. Click the `get started` tab, then `custom workspace`:

![image](https://user-images.githubusercontent.com/227597/99686159-51eaec00-2a51-11eb-9236-1b42ee761d42.png)

2. load a devfile

![image](https://user-images.githubusercontent.com/227597/99686277-73e46e80-2a51-11eb-8951-a11d4021cf9d.png)

3. scroll down (because the devfile editor field is just that much too long)

![image](https://user-images.githubusercontent.com/227597/99686419-95455a80-2a51-11eb-9f19-5aaae7a3f582.png)

### Describe the solution you'd like

4. (new UI) populate a field that can be easily copied & pasted:

![image](https://user-images.githubusercontent.com/227597/99686979-20265500-2a52-11eb-8893-c73542e0c4d2.png)

### Describe alternatives you've considered

Some other UI/UX? 

### Additional context

Factory URL in the above example is https://che.openshift.io/f?url=https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/crw-2.5-rhel-8/dependencies/che-editor-intellij-community/devfiles/workspace.yaml

**Comment by l0rd** [comment]
@nickboldt that's a good idea. I think we should be more brave and show it in the front Getting Started page. And remove the "Filter By" field.

cc @parvathyvr @beaumorley

![image](https://user-images.githubusercontent.com/606959/99689816-b9239300-2a87-11eb-95ad-3d7ccca81e27.png)

**Comment by l0rd** [comment]
cc @sympatheticmoose

**Comment by sympatheticmoose** [comment]
@l0rd I think the filter is just based on the title/description for the stacks at the moment? I'd be fine with that being removed, although it would be interesting if there were other elements we could filter on i.e. language, version etc.

**Comment by sympatheticmoose** [comment]
I think theres two distinct uses here.

1. Creating a new workspace for the first time
2. Enabling others to create a workspace

@nickboldt 's proposal helps with 2. 
@l0rd what you have helps to address 1.

A key aspect of 1 is that (afaik) `f?url=` is the only way you can create a new workspace with just a git repo and which doesn't currently have a devfile, and currently we don't expose this through the UI at all... This is a nice way to get started with che - indeed as we demoed at KubeCon.

**Comment by l0rd** [comment]
> @l0rd I think the filter is just based on the title/description for the stacks at the moment? I'd be fine with that being removed, although it would be interesting if there were other elements we could filter on i.e. language, version etc.

I think it's filtered by title and description. We could probably update that. I was just thinking that with ~30 stacks it's overkill.

And you are right, I have probably misinterpreted @nickboldt description. To share devfile links (and replace the old factory section) [we have this issue](https://github.com/eclipse/che/issues/16875) where the idea is to have a dedicated devfile section with all the devfiles that a user/organisation has ever used and could share with others.

**Comment by beaumorley** [comment]
@l0rd 
@nickboldt 
@sympatheticmoose sympatheticmoose

A couple of questions about the 2 uses:
1.) Based on the suggestions, it sounds like that when creating a workspace for the first time, we are looking for a more discoverable way for the user to enter an existing Devfile URL? You can do this from the "Custom Workspace" tab today. But the user needs to see the tab. Are you thinking that this is a pain point?

2.) @parvathyvr is working on a Devfile section (replaces Factories section) for the above mentioned issue (16875). This will include a "Get shareable link" option.  She'll add the designs to the issue and tag you all for review. We could build on that...

**Comment by l0rd** [comment]
@beaumorley today there is no way to specify the URL of a git repo and let Che do the magic. Just the git repo URL, without worrying about the devfile. That's a beloved feature available if you copy/paste a "factory link" in your browser (`http://<your-che-instance>/f?url=<your-git-repo>`) but is not "advertised" from the dashboard.

**Comment by sleshchenko** [comment]
Redesigned Get Started page allows to create a workspace from git repo without devfile, but it still does not advertise factory URL https://github.com/eclipse/che/issues/18975

**Comment by nickboldt** [comment]
Will the URL be advertised soon ? With great UX design comes great UX responsibility. :)
