### ISSUE TITLE
Deploy Eclipse Che Nightly using olm installer fails

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#18411]
### Describe the bug

Eclipse Che fail when olm installer it is used with chectl:
`server:deploy --installer=olm --platform=minikube`

Operator log:
`time="2020-11-19T08:56:18Z" level=fatal msg="Failed to initialize default value: 'RELATED_IMAGE_che_tls_secrets_creation_job'. Environment variable with default value was not found."
`
### Che version

 - [ ] latest
 - [X] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [X] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tolusha** [comment]
```
 chectl server:deploy --platform minikube --installer olm -n che
› Current Kubernetes context: 'minikube'
 ❕olm-suggested-namespace flag is turned on. Eclipse Che will be deployed in namespace: eclipse-che.
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"
      ✔ Found running Eclipse Che deployment
      ✔ Found running plugin registry deployment
      ✔ Found running devfile registry deployment
    ✔ Check Eclipse Che server status...RUNNING (auth disabled)
  ✔ ✅  Post installation checklist
    ✔ Eclipse Che status check
  ✔ Retrieving Keycloak admin credentials...failed.
  ✔ Retrieving Che self-signed CA certificate... commonly trusted certificate is used.
  ✖ Prepare post installation output
    → ERR_NAMESPACE_NO_EXIST - No namespace eclipse-che is found
 ›   Error: Error: ERR_NAMESPACE_NO_EXIST - No namespace eclipse-che is found
 ›   Installation failed. Error log: /home/tolusha/.cache/chectl/error.log
```

**Comment by flacatus** [comment]
After fix: https://github.com/che-incubator/chectl/pull/994 I can't reproduce the issue. 
Close
