### ISSUE TITLE
Improved tabbed editor design

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1841]
We have the basics of the functionality of multi editors, but we now have to implement a proper design and user experience.
Here is the design:
![multieditor](https://cloud.githubusercontent.com/assets/1636592/16918745/8b19dbd6-4d0f-11e6-8852-7dd0f0e04b8a.png)

**Focus**
Editor who is currently having the cursor is shown with:
- a layer over the background of the terminal #4A90E2 alpha:8%
- a 1px height line a the bottom of the editor's tab

**New Editor**
A new Editor can be invoked by opening a file from the project explorer.
The new editor is opened in the pane that was having the focus previously.
**Pane Management**
The management of panes is handled by a small button on the right of the tabs in the pane. When this button is clicked, it shows options:
- Close Pane: it closes the panes and all the associated terminals.
- Close All Tabs in Pane: it closes all the tabs from the pane, and close the pane.
- Split Pane Horizontally: it splits the area of the current pane to create another pane into another row (50% of the height of each pane)
- Split Pane Vertically: it splits the are of the current pane to create another pane into another column (50% of the width of each pane)

There is another way to split the editor, by doing a right click on a file. The options displayed are:
- Close: it closes the file
- Close Others: it closes all other opened file from the pane
- Close All: it closes all files opened in the current pane
- Split Pane in Two Rows: it splits the area of the current pane to create another pane into another row (50% of the height of each pane)
- Split Pane in Two Column: it splits the are of the current pane to create another pane into another column (50% of the width of each pane)

When a new pane is created, it always opens the last focused file.
**Too much editors in pane**
When there are too many editors in the pane, we do the same behavior than the one we have currently for the editor. We reuse the same button which is handling the pane management.
(Sample: 15 terminals opened in a pane, but space to display the tabs allow to display only 10, then we will have the other 5 terminals in the menu)
Attach one or more files to this issue

**Comment by slemeur** [comment]
Updated:
- _Close All Tabs in Pane:_ it closes all the tabs from the pane, and close the pane.
