### ISSUE TITLE
Add some compilation use-cases of che-theia inside theia-dev on PR checks

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18424]
### Is your task related to a problem? Please describe.
Che-theia images are automatically checked but sometimes it may happen that some dogfooding use-cases are broken

### Describe the solution you'd like
check:
- clone of theia repository + run of `che-theia init` + yarn command = success build
- clone of theia repository + clone of che-theia repository +  run of `che-theia init` with alias parameter for che-theia location
  + config parameter should be given as well when new modules are added == success build

it will ensure only that we can build without errors (not run but it's still a way forward compare to nothing)

### Describe alternatives you've considered
Any automated way to cross check all dogfooding use-cases

### Additional context
Do not break users development flows

**Comment by ibuziuk** [comment]
@benoitf putting P2 for now but feel free to update priority accordingly

**Comment by benoitf** [comment]
@ibuziuk look good
