### ISSUE TITLE
Move Happy path specific image mariolet/petclinic:d2831f9b to quay.io

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18426]
### Is your task related to a problem? Please describe.
We need to move Happy path specific image mariolet/petclinic:d2831f9b to quay.io, in order to work around docker pull rate limit.

It's a blocker for running Happy path nightly tests on Centos CI.

### Additional context
#18380

**Comment by ibuziuk** [comment]
@dmytro-ndp could you please update the issue title. it is non-informative atm

**Comment by dmytro-ndp** [comment]
@ibuziuk: thanks for notice!
Title has been fixed.

**Comment by rhopp** [comment]
This could be also an opportunity to update the image & move it to shared acount (not Mario's or anybody else's personal account)

**Comment by benoitf** [comment]
I've discussed with Mario, he will push his Dockerfile etc in a branch, but then we could refresh the content of the image with something up-to-date and publish it to quay.io

**Comment by l0rd** [comment]
https://quay.io/repository/mloriedo/spring-petclinic?tab=builds
