### ISSUE TITLE
User removal process should be fully asyncronous 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18427]
### Is your enhancement related to a problem? Please describe.
As part of the following issues initial GDPR process was setup:
- https://github.com/eclipse/che/issues/17541
- https://github.com/eclipse/che/issues/18000
- https://github.com/eclipse/che/issues/18383

However, the process is cascade event based and not fully asyncronous.

How it works currently:
- ```curl -iv -X DELETE "https://che-vp-che.apps.che-dev.x6e0.p1.openshiftapps.com/api/user/<user-id>" -H "Accept: application/json" -H "Authorization: Bearer <Keycloak token>"```
- As a response, you can get 204 or 500 response code:
   - 204 means that everything goes well, user fully removed 
   - 500 (with body like: "User has workspace that is not stopped yet. Try again") need to retry probe, in some delay reasonable delay can be: 5- 30 sec. 

### Describe the solution you'd like

1. UserService which consumes user ID and do the following in a separate thread:

- stop all workspaces
- delete all workspaces
- delete user from db
- delete user from keycloak
- delete user's namespace (**optional** - should be possible to disable namespace removal via property / env var)

From API perspective this should look the following way:
- 204 (if there are no running workspaces)
- 202 (if there are running workspaces) - request could be long-running (a couple of minutes). Response body contains the status link (by the id it should be possible to check if the job is done or still WIP)  
- Aditionally it would be nice to have a possibility (as an alternative to status link) to get the events from the websocket channel.

**Comment by skabashnyuk** [comment]
why do we need GDPR service. Could it be part of existed UserService?

**Comment by ibuziuk** [comment]
> why do we need GDPR service? Could it be part of existed UserService?

yeah, good point
