### ISSUE TITLE
Add CI mechanisms for new Che Docker images

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1842]
Based upon #1697 and the pull request #1683 we need to add enhancements to our continuous integration for latest, nightly, and tagged images.

| Image Name | Location | Purpose |
| --- | --- | --- |
| `codenvy/che-launcher` | `/dockerfiles/che-launcher/Dockerfile` | Launcher container |
| `codenvy/che-server` | `/dockerfiles/che-server/Dockerfile` | Launches Che via Tomcat |
| `codenvy/che-dev` | `/dockerfiles/che-dev/Dockerfile` | A container that can build extensions and custom assemblies |
| `codenvy/che` | Identical to `che-server` | Launches Che via Tomcat |
| `codenvy/che-mount` | `/dockerfiles/che-mount/Dockerfile` | A container to synchronize local path with remote workspace. |
| `codenvy/che-ip` | `/dockerfiles/che-ip/Dockerfile` | Grab docker internal network IP |
| `codenvy/che-test` | `/dockerfiles/che-test/Dockerfile` | Allow to test Eclipse Che instance |
| `codenvy/che-file` | `/dockerfiles/che-file/Dockerfile` | Allow to boot Eclipse Che from a local folder |
- [x] [This PR needs to be merged](https://github.com/eclipse/che/pull/2018)

A few items:
- We will eventually change `codenvy/che` to point to `che-launcher` instead of `che-server`.
- Each Dockerfile has the instructions on how to build it.  Please note that the `che-server` image must be built with a context that is at the root of the source repository. However, the other containers should be built with a context (PATH) that is the location of the Dockerfile.  By building those images in the directory where the Dockerfile lives will make the build faster.
- [x] 1. nightly images
- [x] 2. tags and latest images
- [x] 3. Setup CI systems to take che.sh and che.bat files from root of Che repository and add them to https://install.codenvycorp.com/che/ with the necessary latest, nightly, and version tags.  These files will be added to the root of the repository shortly.
- [x] 4. Add test to push all images into eclipse/ organization at DockerHub per instructions from wayne.
- [x] 5. Change the tagging of codenvy/che.  Today codenvy/che:latest is the same image as codenvy/che-server:latest.  Please have codenvy/che:latest now point to codenvy/che-launcher:latest.

```
che.sh  (latest)
che.bat (latest)
che-nightly.sh
che-nightly.bat
che-<tag>.sh
che-<tag>.bat
```

**Comment by riuvshin** [comment]
@TylerJewell I've added ci jobs to handle **nightly** images.
**latest** and **tags** will be added after **4.6.0** release

**Comment by benoitf** [comment]
We have also this merge. #1986.

| Image Name | Location | Purpose |
| --- | --- | --- |
| `codenvy/che-ip` | `/dockerfiles/che-ip/Dockerfile` | Grab docker internal network IP |
| `codenvy/che-test` | `/dockerfiles/che-test/Dockerfile` | Allow to test Eclipse Che instance |
| `codenvy/che-file` | `/dockerfiles/che-file/Dockerfile` | Allow to boot Eclipse Che from a local folder |

note: before building che-test and che-file we need to build the shared library
There is script for that
`https://github.com/eclipse/che/blob/master/dockerfiles/lib/typescript/compile.sh`

**Comment by benoitf** [comment]
I don't see che-test, che-file or che-ip on dockerhub ?

**Comment by riuvshin** [comment]
I'm unable to push images due to some reason it says

```
Repository does not exist: codenvy/che-file
```

while https://hub.docker.com/r/codenvy/che-file/ same issue with che-test

che-ip is pushed  https://hub.docker.com/r/codenvy/che-ip/tags/

**Comment by riuvshin** [comment]
btw @benoitf  I have such error when running script compile.sh

```
/bin/bash: line 0: cd: /usr/src/app/dependencies/compile: No such file or directory
Compilation has failed, please check TypeScript sources
```

**Comment by benoitf** [comment]
@riuvshin from Which directory are you executing script ? Could you run a 'CD' command to the compile.sh folder before running it ? as we mount current folder

**Comment by riuvshin** [comment]
@benoitf there is no `/usr/src/app/` folder, how it should appear?

**Comment by riuvshin** [comment]
@TylerJewell are you sure you want 
3. Have http://get.codenvy.com/ point to http://install.codenvycorp.com. ? and not https://start.codenvy.com ? 
https://start.codenvy.com/install-codenvy - here is our bootstrap script

**Comment by TylerJewell** [comment]
@riuvshin - "http://get.codenvy.com" should have the file `install-codenvy` load.  I think it was a mistake to use "start" and we should do it with "get"
