### ISSUE TITLE
Chectl does not respect dashboard deployment

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18421]
### Describe the bug
First of all sorry for introducing this bug, so in the PR helm char started run Dashboard in a dedicated deployment https://github.com/eclipse/che/pull/18093. But chectl server:stop (and server:start in case of starting stopped Che Cluster) is not aware of dashboard deployment.
So, it's needed to make chectl take into account dashboard deployment as well. Please note that che operator does not have dashboard as deployment yet.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl --installer=helm
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by mmorhun** [comment]
Fixed
