### ISSUE TITLE
What is the best deploy code base to use for a custom plugin registry?

### ISSUE THREAD

**Issue by cccs-eric** [eclipse-che/che#18436]
I would like to have my own `che-plugin-registry` since I would like to add custom plugins to my deployment of Che.  I have forked the [che-plugin-registry repository ](https://github.com/eclipse/che-plugin-registry) and added my plugins.  I was also able to create an image using `build.sh`.  Now I want to deploy this image as a container and use `chectl --plugin-registry-url=XXX` to get a Che deployment that uses my new custom plugin registry.  

So to deploy my custom registry, I have used the helm chart that I found under [che-plugin-registry/deploy/kubernetes/che-plugin-registry](https://github.com/eclipse/che-plugin-registry/tree/master/deploy/kubernetes/che-plugin-registry).  I got a problem related to the ingress YAML and submitted a [pull request](https://github.com/eclipse/che-plugin-registry/pull/708) to fix it.  But then today I browsed the Che repository looking for something else and stumbled upon other Helm charts in [che/deploy/kubernetes/helm/che/custom-charts](https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che/custom-charts) related to devfile-registry and plugin-registry.  Now I am confused...  Which one should I be using if I need to deploy my own registry?  I wanted to contribute back to improve the current Helm charts to support node taints, but I'm confused about which code base I should be using.

**Comment by sparkoo** [comment]
helm chart in `che-plugin-registry` is for deploying it on it's own, while charts in `che` repository is to deploy it together with Che.

If you want to deploy it with Che, you might want to use charts in `che` repository and set `chePluginRegistry.image` to your custom image. If you want to have more control over the registry deployment, you might want to deploy it separately and set `chePluginRegistry.deploy=false` and `che.pluginRegistryUrl=<your-registry-url>`.

**Comment by cccs-eric** [comment]
Thanks for the feedback @sparkoo . 
For others reading this thread, you need to embed that yaml into the subchart's name to make this work (assuming you are doing this via the helm installer, with `--helm-patch-yaml=patch.yaml`).

patch.yaml:
``` 
che-plugin-registry:
  chePluginRegistry:
    image: your.containerregistry.com/che-plugin-registry:latest

che-devfile-registry:
  cheDevfileRegistry:
    image: your.containerregistry.com/che-devfile-registry:latest
```

**Comment by cccs-eric** [comment]
One comment I'll add before closing this issue is having 2 different locations for helm chart deployment (one in `che`, one in `che-plugin-registry`) is not the best.  I know for a fact that the helm chart in `che-plugin-registry` is broken while the one in `che` works.  That happens when a fix is done in one project and not the other.  To me, both project should use the same Helm chart templates while having different configurations.  A well done helm chart can easily accomodate both project requirements.  

I find the overall deployment of Che is trying to support too many ways (chectl, Helm chart, Operator, etc...) while not supporting  one of them perfectly.

**Comment by cccs-eric** [comment]
@sparkoo @tolusha I would like to raise an issue with you about having 2 different deployments for `che` and `che-plugin-registry` (and also `che-devfile-registry`).  As I mentioned in a post above, having 2 different helm charts is error-prone and harder to maintain in my opinion.  As @sparkoo suggested earlier, I am not building my own image of che-plugin-registry and deploying it with `che` by overwriting `chePluginRegistry.image`.  This works really well and frankly, is much better than setting up my own deployment.  I'm pleased with the suggestion. 😃 

But now I have another problem that requires a feature that can be found in `che-plugin-registry` helm, but not in `che`'s helm chart for che-plugin-registry.  I need to deploy in an airgap network and I need to overwrite the images referenced by plugins.  I ran into the following PR that does exactly what I need: https://github.com/eclipse/che-plugin-registry/pull/245.
It introduces a new [env variable](https://github.com/eclipse/che-plugin-registry/blob/master/deploy/kubernetes/che-plugin-registry/templates/configmap.yaml#L17) in a configmap, but this feature is not present in `che`: https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates (the configmap does not even exist).

Could there be a way to combine both deployments, whether by having `che-plugin-registry` be a chart on its own an `che` using it as a dependency?  Or any other way you can think of?  In my experience, the chart-as-dependency approach is the common way to fix those things in Helm, but I am open to something else.  Thoughts?

**Comment by tolusha** [comment]
@cccs-eric 
Do you really need to override plugin images at runtime?

I can suggest the following:
- build your plugin/devfile registries by specifying registry and organization (see build.sh in corresponding git repository)
- follow this [1] guide to set custom registry and organization.

NOTE: it requires that all images (including che-server, keycloak ... with use same custom registry and organization)

[1] https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-in-a-restricted-environment/#configuring-che-to-run-in-a-restricted-environment_installing-che-in-a-restricted-environment

**Comment by cccs-eric** [comment]
@tolusha Yes, I already created an image for plugin & devfile registries by running `build.sh` using `--registry myregistry.com` and `--organization myorg`.  That will create an image ready to be pushed to `myregistry.com/myorg`.  That works very well and I point my helm chart to those images
```
    cheDevfileRegistry:
      image: myregistry.com/myorg/che-devfile-registry:7.22.1
```
Both of those images will be packaged with zip files of projects sources as well as VSCode extensions.  What is not being packaged are the docker images referenced in the plugins and devfiles.  They are still referencing `quay.io`.  In order to change those, it needs to be done at runtime by [`entrypoint.sh`](https://github.com/eclipse/che-devfile-registry/blob/master/build/dockerfiles/entrypoint.sh#L29) using those env variables:
```
REGISTRY=${CHE_SIDECAR_CONTAINERS_REGISTRY_URL}
ORGANIZATION=${CHE_SIDECAR_CONTAINERS_REGISTRY_ORGANIZATION}
TAG=${CHE_SIDECAR_CONTAINERS_REGISTRY_TAG}
```
Otherwise, Che will load the workspace and will complain that it can't find some docker images.

From my understanding, `build.sh` will not perform those changes.  The documentation page you linked is when Che is deployed using the operator, which I'm not.  I use Helm to deploy Che and I couldn't find something in the Helm chart to replace
```
spec:
  server:
    airGapContainerRegistryHostname: '<my-internal-registry>'
    airGapContainerRegistryOrganization: '<my-organization>'
```
from the operator CRD.  

Did I miss something?

**Comment by tolusha** [comment]
@cccs-eric 
yes, you are right. 
so I assume it is better to port this feature into [1]

[1] https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che/custom-charts

**Comment by cccs-eric** [comment]
@tolusha 
Alright.  I already done this for both che-devfile-registr and che-plugin-registry.  I'll create another PR for that 😃 
I will need your input on the new helm value names.  As you said, it is a mess and I'd like to propose something.  We can discuss it in the PR.

**Comment by tolusha** [comment]
sure. thank you!

**Comment by metlos** [comment]
I assume this issue can be closed because the PR addressing it has been merged. If you think this is still not solved, feel free to reopen the issue or create a new one. Thanks for your contributions!
