### ISSUE TITLE
Custom extension that contributes to Theia menu not working in che

### ISSUE THREAD

**Issue by priyamariarao** [eclipse-che/che#18439]
I have created a custom Theia extension by following the steps provided in 
https://theia-ide.org/docs/authoring_extensions/
the extension works fine in the browser-app and the Theia menu is modified as expected. I then package the extension as a Vsix and try to add it che-theia instance. the extension shows that its installed but it does not appear to work.
How can we hide Theia menu items from within che

**Comment by azatsarynnyy** [comment]
Hello @priyamariarao 
it seems you're trying to package your Che Theia Extension as a Che Theia Plug-in. It's not correct as these are two different concepts.
You can read more about extensions [here](https://theia-ide.org/docs/authoring_extensions) and about plug-ins [here](https://theia-ide.org/docs/authoring_plugins).

Choosing one or another way depends on what's your goal:
- customize the main menu? Then having an Extension is completely enough.
- be able to enable/disable your code at run-time with a Plug-in? Plug-in API doesn't provide access to the main menu.
