### ISSUE TITLE
WebSocket 502

### ISSUE THREAD

**Issue by LeapLu** [eclipse-che/che#18437]
I deployed che by helm before I have got the images about che（like quay.io/eclipse:nightly）all images'tag are nightly
```bash
git clone https://github.com/eclipse/che.git
cd deploy/kubernetes/helm
helm install -name che ./ -n che
```
now it started
<img width="660" alt="图片" src="https://user-images.githubusercontent.com/67357731/100044335-6dd40080-2e4a-11eb-9967-2273e9c328b8.png">
when I enter and try to create a workspace 502 appear
<img width="1534" alt="图片" src="https://user-images.githubusercontent.com/67357731/100044103-c5be3780-2e49-11eb-9e4b-798013cf5b13.png">
here are my ingress yml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: che
    meta.helm.sh/release-namespace: che
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/websocket-services: che-host
  creationTimestamp: "2020-11-24T03:34:56Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: che-ingress
  namespace: che
  resourceVersion: "27894"
  selfLink: /apis/extensions/v1beta1/namespaces/che/ingresses/che-ingress
  uid: dc311c20-1225-4654-9d41-7ce130c5f51c
spec:
  rules:
  - host: che-che.che.com
    http:
      paths:
      - backend:
          serviceName: che-host
          servicePort: 8080
        path: /
status:
  loadBalancer:
    ingress:
    - {}
```
It has troubled me about 4 days please help！

**Comment by KubeLouis** [comment]
I just wonder why websocket show 502 even if I set websocket-services in my ingress yaml
another image to the 502:
<img width="703" alt="图片" src="https://user-images.githubusercontent.com/67357731/100046620-80026e80-2e4b-11eb-8dd1-ccb23c308a1f.png">
