### ISSUE TITLE
Followed basic Azure installation however Theia is not working

### ISSUE THREAD

**Issue by mastercard-rob** [eclipse-che/che#18434]
### Describe the bug
When I load a workspace the editor fails to fire up. Did some looking around and the symptoms are very similar to https://github.com/eclipse/che/issues/18255

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Followed the instructions (https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/) and everything is up and running. 
2. Logged into keycloak and created an initial user to log into the user dashboard.
3. Logged into dashboard and created a workspace using the Angular template
4. Open workspace

### Expected behavior
Expect to be able to start working with the code in the editor

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [x] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
The command to gather workspace logs is suggesting that the workspace is not started when in fact it is, the following are logs from the theia container
[theia.log](https://github.com/eclipse/che/files/5583679/theia.log)

**Comment by mastercard-rob** [comment]
FWIW, I've just ran Che locally with docker-desktop on a Mac and I can see the difference in the log output at the point where my Azure instance has issues

2020-11-23 15:04:11.403 root ERROR [f36b3875-c011-441c-9938-b28e216179f4][vscode.markdown]: Language for 'meta.embedded.block.vs_net' not found. 
2020-11-23 15:04:11.404 root ERROR [f36b3875-c011-441c-9938-b28e216179f4][vscode.markdown]: Language for 'meta.embedded.block.dosbatch' not found. 
2020-11-23 15:04:11.405 root ERROR [f36b3875-c011-441c-9938-b28e216179f4][vscode.markdown]: Language for 'meta.embedded.block.coffee' not found. 
2020-11-23 15:04:11.406 root ERROR [f36b3875-c011-441c-9938-b28e216179f4][vscode.markdown]: Language for 'meta.embedded.block.objc' not found. 
2020-11-23 15:04:11.407 root ERROR [f36b3875-c011-441c-9938-b28e216179f4][vscode.markdown]: Language for 'meta.embedded.block.scala' not found. 
2020-11-23 15:04:11.408 root WARN 'php' language is remapped from 'source.php' to 'text.html.php' scope 
2020-11-23 15:04:11.409 root WARN a registered grammar configuration for 'php' language is overridden 
2020-11-23 15:04:11.579 root INFO [hosted-plugin: 48] PLUGIN_HOST(48): PluginManagerExtImpl/init() 
2020-11-23 15:04:11.582 root INFO [hosted-plugin: 48] PLUGIN_HOST(48): initializing(@eclipse-che/github-auth-plugin@7.21.2 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)

**Comment by azatsarynnyy** [comment]
From the provided theia.log I see Che Theia is started however it can't reach Che API.
Che Theia gets Che API URL from `CHE_API` environment variable.
I can suggest checking `CHE_API` variable in the Che Theia sidecar and ensure that the URL is correct and reachable.

**Comment by mastercard-rob** [comment]
I've looked at the deployment descriptor for the workspace I can see a sidecar image quay.io/eclipse/che-sidecar-node:10-0cb5d78 being used. There are multiple references to CHE_API, CHE_API_EXTERNAL and CHE_API_INTERNAL (for various containers), they all have the same value which is essentially the public facing url e.g. https://che-che.<mydomain>/api, i've redacted my domain. 
The other thing I did notice was that the environment variable CHE_WORKSPACE_NAMESPACE is set to 'rob' however the namespace is in kubernetes is 'rob-che'. I've tried manually editing the namespace to rob-che however the same issue persists.

**Comment by cccs-eric** [comment]
It that helps, here is what I did (I'm also in Azure AKS):
```
NS=che
# I am using a TLS cert with my own CA, so I need this:
kubectl --namespace ${NS} create secret generic self-signed-certificate --from-file=ca.crt=my-ca.crt

chectl server:deploy \
    --installer=operator \
    --multiuser \
    --deployment-name=che \
    --chenamespace=${NS} \
    --platform=k8s \
    --che-operator-cr-patch-yaml=patch.yaml \
    --domain=redacted.domain.com
```
and patch.yaml is:
```
spec:
  server:
    cheHost: che.redacted.domain.com
    customCheProperties:
      # Not sure if that works...
      CHE_LIMITS_USER_WORKSPACE_RUN_COUNT: "-1"
  k8s:
    # che-tls was created before, it holds my certs for Che, signed by my custom CA
    tlsSecretName: che-tls
  storage:
    pvcClaimSize: 1Gi
    pvcStrategy: per-workspace
```

**Comment by mastercard-rob** [comment]
I think I've managed to sort it, I tried your suggestion but had the same issue. But took inspiration from it. Following the tutorial I setup cert-manager and used letsencrypt. So I needed to disable the use of self signed certs so i use a patch for helm

```
chectl server:deploy --installer=helm --platform=k8s --domain=redacted.dev --multiuser --chenamespace=che --helm-patch-yaml=values.yaml 
```
and values.yaml is:
```
global:
  tls:
    useSelfSignedCerts: false
    selfSignedCertSecretName: ""
```

Perhaps the documentation should be updated to reflect.
