### ISSUE TITLE
Simplify checluster CR configuration: provide default values user can edit.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18442]
### Is your enhancement related to a problem? Please describe.
At the moment, when installing che from the Openshift operatorhub, some attribute should be easier to configure. Especially the values we pass through `customCheProperties`. 

### Describe the solution you'd like
It would be nice that the default yaml is prefilling commonly used `customCheProperties` with the default values. So user would just need to change the value.
The ones I use by default: 
```
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '3'
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '-1'
```

### Describe alternatives you've considered
move `customCheProperties` commonly used into the CheCluster CR definition.

**Comment by sparkoo** [comment]
I would be careful with this. "commonly used" is very subjective and CheCluster CR is already quite long. If you use some options everytime, it's quite easy to have CheCluster patch and apply it from chectl.
