### ISSUE TITLE
Error: connect ETIMEDOUT [ IP ADDRESS ]

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18446]
### Describe the bug

Error: connect ETIMEDOUT [ IP ADDRESS ] during PostgreSQL deploy. Opening IP ADDRESS returned Cloudflare's  

```
Error 1003 Ray ID: ####### • 2020-11-24 13:39:06 UTC
Direct IP access not allowed
```
Since the Operator was able to deploy, chectl's behavior *appears* to be inconsistent.

kubeconfig uses a URL and not an ip address.

### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ x ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
        `chectl server:deploy --che-operator-cr-yaml=che-cluster.yaml -a operator -p k8s -b url.com` 
     * provide an output of `chectl version` command
       `chectl/7.22.0 linux-x64 node-v10.23.0`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tolusha** [comment]
Could you provide chectl logs, pls ?

**Comment by gnoejuan** [comment]
Oops, I guess the timeout was a red-herring.

error.log:

```
2020-11-24T13:15:15.232Z Error: Error: Error: connect ETIMEDOUT 104.18.41.251:443
2020-11-24T13:15:15.232Z Installation failed. Error log: /home/charlesrod/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1606223172953
2020-11-24T13:15:15.232Z     at Object.error (~/.local/share/chectl/client/7.22.0/node_modules/@oclif/errors/lib/index.js:26:15)
2020-11-24T13:15:15.232Z     at Deploy.error (~/.local/share/chectl/client/7.22.0/node_modules/@oclif/command/lib/command.js:60:23)
2020-11-24T13:15:15.232Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.22.0/lib/commands/server/deploy.js:244:22)
2020-11-24T13:15:15.232Z     at Generator.next (<anonymous>)
2020-11-24T13:15:15.232Z     at fulfilled (~/.local/share/chectl/client/7.22.0/node_modules/tslib/tslib.js:112:62)
```

BUT `che-operator.log`

```
time="2020-11-24T13:06:24Z" level=info msg="Default 'info' log level is applied"
time="2020-11-24T13:06:24Z" level=info msg="Go Version: go1.13.4"
time="2020-11-24T13:06:24Z" level=info msg="Go OS/Arch: linux/amd64"
time="2020-11-24T13:06:24Z" level=info msg="operator-sdk Version: v0.15.2"
time="2020-11-24T13:06:24Z" level=info msg="Operator is running on Kubernetes"
time="2020-11-24T13:06:27Z" level=info msg="Registering Che Components Types"
time="2020-11-24T13:06:28Z" level=info msg="Starting the Cmd"
time="2020-11-24T13:06:28Z" level=error msg="Failed to create test ingress 'test': Ingress.extensions \"test\" is invalid: [spec.rules[0].host: Invalid value: \"charlesrod.me/che\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts: Invalid value: \"url.com/che\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]"
time="2020-11-24T13:06:28Z" level=error msg="Failed to detect if self-signed certificate used. Cause: Ingress.extensions \"test\" is invalid: [spec.rules[0].host: Invalid value: \"url.com/che\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts: Invalid value: \"url.com/che\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]"
```

url.com/che fails regex

**Comment by sparkoo** [comment]
looks like you're trying to use host with subpath as a domain. I don't think it's possible.

**Comment by gnoejuan** [comment]
Yeah, I changed the domain and it got past the issue. 

If the operator container deploying before the url check is the expected behavior, I believe this issue is resolved.
