### ISSUE TITLE
Syntax highlighting behaving strangely in several Java devfiles

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#18448]
### Describe the bug
Affected devfiles:
* Java Gradle
* Java Maven
* Java with Spring Boot

After Java LS is initialized, the colors get messed up
![Screenshot_20201124_163947](https://user-images.githubusercontent.com/16451875/100117327-f9fb1d80-2e74-11eb-8f15-906a1603b5f5.png)
![Screenshot_20201124_123751](https://user-images.githubusercontent.com/16451875/100117330-fa93b400-2e74-11eb-95a5-5dc81beb8834.png)
![Screenshot_20201124_123402](https://user-images.githubusercontent.com/16451875/100117331-fb2c4a80-2e74-11eb-98b8-ea3569e18e3d.png)

It is possible that the coulprit is `Semantic highlighting`
![Screenshot_20201124_163602](https://user-images.githubusercontent.com/16451875/100117423-1008de00-2e75-11eb-9008-ab2e72354b90.png)

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: 7.22.0

### Steps to reproduce
* Start any of the above mentioned devfiles
* Open a .java file
* Wait for the LS to initialize, the colors will change

### Expected behavior
* Colors work correctly

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: OCP 4.5 on crw-qe.com (https://che-tdancs-che.apps.ocp45.crw-qe.com/), (che.prod-preview.openshift.io)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
`chectl server:deploy -a operator -p openshift -n tdancs-che`
     * provide an output of `chectl version` command
`chectl/7.22.0 linux-x64 node-v10.23.0`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other: OCP 4.5 on crw-qe
   - [ ] other: please specify

### Eclipse Che Logs
https://pastebin.com/5zuav30Q

### Additional context
N/A

**Comment by Katka92** [comment]
Seen again in 7.24.1
![captured (1)](https://user-images.githubusercontent.com/29278800/104446577-f5acd000-559a-11eb-9ae5-1ec11fb302fc.gif)

**Comment by sunix** [comment]
OK I could reproduce it, it is first ok but then once the java plugin is up...
Just after startup:
![Selection_216](https://user-images.githubusercontent.com/650571/107624594-6a872e80-6c5b-11eb-9487-f118f1e846ce.png)
Then after few secs:
![Selection_217](https://user-images.githubusercontent.com/650571/107624603-6d821f00-6c5b-11eb-8eb7-a2d14a650f38.png)

**Comment by sunix** [comment]
Hello,
So after investigation, this is related to semantic highlighting. It is enabled by default. My guess is that CheTheia is failing to merge existing/builtin highlighting and semantic one. I have to see what is the best option short term and long term.
I still have to test, but disabling semantic highlighting in the preferences for Java should work.

**Comment by sunix** [comment]
Created an upstream issue https://github.com/eclipse-theia/theia/issues/9058

**Comment by sunix** [comment]
Closing it, disabling semantic hightlighting fix the syntax highlighting: https://github.com/eclipse/che-theia/pull/993
