### ISSUE TITLE
Fix for getting Starting sample for php-laravel - issue with JWT auth secret key

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18441]
### Describe the bug
Command `Generate a new JWT authentication secret key` is failing in `PHP Laravel with MySQL` devfile. Other commands seem to work fine. 
Reproduced on Hosted Che 7.22.0 and nightly upstream Che.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to `Get Started` page, `Get Started` tab
2. Select `PHP Laravel with MySQL` devfile and wait for it to start
3. Click on `Terminal` -> `Run Task...` -> `Install dependencies` to be sure everything is installed
4. Click on `Terminal` -> `Run Task...` -> `Generate a new JWT authentication secret key`

### Expected behavior
The command should work out of a box.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) ocp4.6
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify) Hosted Che

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/100087961-c1951880-2e4f-11eb-91a4-dd0d3a5ea698.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify Hosted Che

**Comment by ScrewTSW** [comment]
Still present in 7.23.1

**Comment by ScrewTSW** [comment]
![image](https://user-images.githubusercontent.com/16451875/104455131-2135b780-55a7-11eb-980f-7ee79cc0c2cc.png)
still present in 7.24.1

**Comment by RomanNikitenko** [comment]
It would be nice to provide an area to have better visibility for the issue - in such case the corresponding team could pick up the issue faster.

**Comment by sunix** [comment]
should be fixed with https://github.com/eclipse-che/che-devfile-registry/pull/357
