### ISSUE TITLE
che-theia: Prettier --check does not output info about what is wrong

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#18451]
### Is your enhancement related to a problem? Please describe.
Recently, `prettier` has replaced our previous formatter. The build fails if `prettier --check` finds anything that is not formatted along the rules. The problem is, that there is no information about what is wrongly formatted, so it's impossible to fix anything except to run `prettier` on the files.

### Describe the solution you'd like

1. If we have no information about what's wrong, the only way to fix the problem is to run the tool. So we can just run the formatter as part of the build process. 
2. If we don't want to do that, we need a way to find out what's wrong. A cursory search revealed `prettylint`, but there may be other tools we can use to check formatting that actually yield useful information.

**Comment by tolusha** [comment]
@tsmaeder 
Could you pls specify the project you are talking about?

**Comment by tsmaeder** [comment]
Sorry, living in my own world: updated the title.

**Comment by tsmaeder** [comment]
```
@eclipse-che/theia-remote: [format] $ prettier --check '{src,tests}/**/*.ts' package.json
@eclipse-che/theia-remote: [format] Checking formatting...
@eclipse-che/theia-remote: [format] [warn] src/node/hosted-plugin-process-log.ts
@eclipse-che/theia-remote: [format] [warn] src/node/plugin-remote.ts
@eclipse-che/theia-remote: [format] [warn] Code style issues found in the above file(s). Forgot to run Prettier?
@eclipse-che/theia-remote: [format] error Command failed with exit code 1.
```

**Comment by benoitf** [comment]
About the title of the issue I would say it's not related to che if you complain about the reporting output of the tool itself.
--> You could upvote https://github.com/prettier/prettier/issues/6069 but IMO it'll never happen

Now about improvements:
in che-theia, we run first the formatter and then the linter, maybe we should do the opposite as eslint reports problems in a better shape.
Also most of the issues are reported in the IDE itself when using eslint plug-in.

I thought you were against the "autoformat" of code this is why the default has been moved from "fix" to "check" on the formatting tool.

In development mode, using the watch mode is not triggering the linter/prettier check but we could have a mechanism to trigger or not these checks

**Comment by saikrishnabanda5** [comment]
Unable to format the code by using ctrl + s in theia. Also unable to see prettier below

![image](https://user-images.githubusercontent.com/54619513/113289545-fa696080-930d-11eb-8707-051cb3c86aaa.png)
