### ISSUE TITLE
Use local image before registry

### ISSUE THREAD

**Issue by jgroom33** [eclipse-che/che#1845]
Che looks for the image on a registry first even if the image is local.

**Reproduction Steps:**
1. Create a local docker image that is not on docker.io (and not on a registry)
2. Add the entry to stacks.json
3. Launch the workspace

**Expected behavior:**

The workspace should launch if the image is found locally.

**Observed behavior:**

[DOCKER] Pulling repository docker.io/custom/ubuntu
[DOCKER] [ERROR] Error: image custom/ubuntu not found
[DOCKER] Step 1 : FROM custom/ubuntu:1.0.0
[DOCKER] ---> 679e2974f308
[DOCKER] Successfully built 679e2974f308
rpc error: code = 2 desc = "oci runtime error: exec failed: open /run/runc/dca364d6c230b77ea751362328e9b857a154e71e392ad77bb50fd308f0139d0a/state.json: no such file or directory"
Machine is destroyed. The processes in this machine need more RAM. This machine started with 1000MB. Create a new machine configuration that allocates additional RAM or increase the workspace RAM limit in the user dashboard.

**Che version:**    [4.4.2]
**OS and version:** [Ubuntu 16.04]
**Docker version:** [1.11.2]
**Che install:**    [server zip]

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced

**Comment by ghost** [comment]
@jgroom33 simply change this to false - https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L112 in `/conf/che.properties`

**Comment by jgroom33** [comment]
Thanks. That solved it!
