### ISSUE TITLE
Adapt Che Theia to upstream changes

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18456]
### Is your task related to a problem? Please describe.
There's a WIP PR https://github.com/eclipse-theia/theia/pull/8759 in upstream Theia that will bring the breaking changes related to mini-browser functionality. The `/mini-browser` Theia endpoint will be served on a dedicated host.
We need to adapt Che Theia to these changes.

### Describe the solution you'd like
We need to declare another Che endpoint in Che Theia `meta.yaml` descriptor for exposing `/mini-browser` Theia's endpoint.
Like we did it for `/webviews` endpoint [here](https://github.com/eclipse/che-plugin-registry/blob/a9d4e0fdfb14aa68b0b9c28f00671d06831b1cf5/v3/plugins/eclipse/che-theia/next/meta.yaml#L24-L33).
And tell Che Theia to fetch the `/mini-browser`'s content through a dedicated Che endpoint.

### Sub-tasks
- [x] Declare a dedicated endpoint for exposing Che Theia `/mini-browser` content https://github.com/eclipse/che-plugin-registry/pull/712
- [x] Serve `/mini-browser` endpoint on a dedicated route https://github.com/eclipse/che-theia/pull/930

**Comment by benoitf** [comment]
@azatsarynnyy what about declaring the new endpoint as soon as possible ?

**Comment by azatsarynnyy** [comment]
I'm going to open a PR after lunch :wink:

**Comment by azatsarynnyy** [comment]
okay, opened a PR https://github.com/eclipse/che-plugin-registry/pull/712
now, going to lunch :smile:
