### ISSUE TITLE
Improve chectl helm installer to fix cheWorkspacesNamespace che-ws-<username> problem

### ISSUE THREAD

**Issue by cccs-eric** [eclipse-che/che#18459]
### Is your enhancement related to a problem? Please describe.
I am using `chectl` with `--installer=helm` and `--helm-patch-yaml=values.yaml` and when I put the following in `values.yaml`
```
global:
  cheWorkspacesNamespace: "che-ws-<username>"
```
`chectl` will crash since it is "flatting" the yaml fields and setting them individually using `--set global.cheWorkspacesNamespace=che-ws-<username>`.  The set argument is not escaped and the shell will interpret `<` and `>`.  So in order to make it work, I had to single-quote the value in yaml:
```
global:
  cheWorkspacesNamespace: "'che-ws-<username>'"
```
which is not a good user experience.

### Describe the solution you'd like
Here is what we have in `chectl`:
```
let command = `helm upgrade --install che --force --namespace ${flags.chenamespace} ${setOptions.join(' ')} ${multiUserFlag} ${tlsFlag} ${destDir}`;
```
we do a join on the options set.  What I would like to see is instead of using multiple `--set` switches, use `-f values.yaml` and you don't have to parse `values.yaml` and flat it.  If you use multiple `-f values.yaml` with helm, the right-most file on the command-line will overwrite the values from the previous ones, effectively taking precedence over the values from the other file.

### Describe alternatives you've considered
There is also another issue with the current implementation when let's say a user sets a value using one of `chectl` switches (let's say `chectl server:deploy --domain=mydomain.com` and also sets it again in `values.yaml`
```
global:
  cheDomain: "anotherdomain.net"
```
which one will be used?  The user has no clue that `chectl` is flatting the yaml and uses `--set`, and even if he does, he doesn't know the order that will be used for the `--set` switches.  So we end up with something like:
```
helm upgrade --install che --force --namespace che 
--set global.cheDomain=mydomain.com 
--set xxx=xxx
--set yyy=yyy
...
--set global.cheDomain=anotherdomain.net
...
```
So it creates confusion in my opinion.  A solution would be to leave the code as-is for the `chectl` arguments (pass them as `--set` arguments), so they will take priority over what's in `values.yaml`.  The documentation could be reflected accordingly to explain the priority, so the user can make a decision on overwriting or not what's in `values.yaml`.

**Comment by tolusha** [comment]
@cccs-eric 
Thank you for investigation, we will take that into account.

**Comment by mmorhun** [comment]
Resolved by https://github.com/che-incubator/chectl/pull/1026

**Comment by mmorhun** [comment]
@cccs-eric thank you for detailed report and investigation !
