### ISSUE TITLE
Configure static persistent volumes for che workspace storage

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18458]
HI Team, I am trying to configure static persistent volumes for che using the doc - https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-using-storage-classes/

Trying to follow point#3 - Bind static provisioned volumes using class names from the doc
I have created the following persistent volume -

apiVersion: v1
kind: PersistentVolume
metadata:
  name: che-azurefile
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: che-azurefile
  azureFile:
    secretName: azure-secret
    shareName: chefileshare
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

I am using azure files as backend storage.. 
Below is my storage class configuration 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: che-azurefile
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  location: eastus

and in my che-cluster.yaml , i am providing workspacePVCStorageClassName: 'che-azurefile'
but when i start the workspace, it is not taking the PV i have created.. 
claim-che-workspace   Bound    pvc-5483a689-5360-4f01-a74c-655d5a5b3e3e   1Gi        RWO            che-azurefile   17s
It is taking dynamic PV -  pvc-5483a689-5360-4f01-a74c-655d5a5b3e3e instead of che-azurefile

kindly assist.

**Comment by tolusha** [comment]
@chopraaakash91 
I think these points are important as well, see step 2. could you try?
* Set pvcStrategy as common.
* Configure Che to start workspaces in a single namespace.

**Comment by chopraaakash91** [comment]
I am using the below che-cluster file -
 
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    updateAdminPassword: false
  storage:
    workspacePVCStorageClassName: 'che-azurefile'
    pvcClaimSize: '2Gi'


i think the default strategy is common, and by default che starts workspaces in a single namespace. So these 2 points are taken care.

**Comment by chopraaakash91** [comment]
Looking at the configuration or the documentation, I am wondering how it will bind to my PV using storage class name. It will directly use the storage class and create a dynamic PV out of that storage class.

**Comment by chopraaakash91** [comment]
@tolusha I tried again with what you have suggested. Updated che-cluster-yaml:

apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    workspaceNamespaceDefault: 'cloudspace-akash'
  auth:
    updateAdminPassword: false
  storage:
    workspacePVCStorageClassName: 'che-azurefile'
    pvcClaimSize: '2Gi'
    pvcStrategy: 'common'

But even then, it did not take PV that i created. Below is the output of kubectl get pvc-
persistentvolumeclaim/claim-che-workspace   Bound    pvc-c7458a31-3d02-463d-aed5-26624cfff908   2Gi        RWO            che-azurefile   12s
 
I am expecting that it should pick che-azurefile as PV.
Kindly assist.

**Comment by sudr** [comment]
I've run into this same issue when deploying che via the following:
chectl server:deploy --workspace-pvc-storage-class-name che-workspace-storage --platform minikube --installer=helm

The PVC that che server creates is not using my specified storage class named 'che-workspace-storage'.  Instead the default storage class "che-data-volume" is being created and is using the "standard" storage class that is provisioned by minikube.

**Comment by tolusha** [comment]
@sudr 

strange.
1. deploy: `chectl server:deploy --workspace-pvc-storage-class-name workspace-sc --platform minikube --installer=helm -m`

2. check pvc

```bash
oc get pvc -n admin-che
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
claim-che-workspace   Bound    pvc-45c1cd77-133d-4b40-8c21-2528b7b93044   1Gi        RWO            workspace-sc   60s
```

**Comment by sudr** [comment]
It looks like it does work as expected when using the "-m" multi-user flag. I'm trying to install the single-use (ie. no database/Keycloak) mode and am seeing that it does not honor the specified workspace storage class name.
