### ISSUE TITLE
Hosted Che is Eclipse Che hosted by Red Hat

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18463]
### Is your enhancement related to a problem? Please describe.

In the [doc](https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/) and in the [website](https://www.eclipse.org/che/getting-started/cloud/) we mention "Hosted Che" and "SaaS Cloud" without mentioning that it's hosted by Red Hat.

### Describe the solution you'd like

For the sake of transparency we should make a clear distinction between the project and the product(s). Referring to "Eclipse Che hosted by Red Hat" address this.

**Comment by ibuziuk** [comment]
PRs sent:
 - [ ] https://github.com/eclipse/che-docs/pull/1732
 - [ ] https://github.com/eclipse/che-website/pull/48
