### ISSUE TITLE
Fortify, Sonatype Plugins in Eclipse Che

### ISSUE THREAD

**Issue by veeramanikandanvv** [eclipse-che/che#18465]
Hey Team,

We have a requirement of performing CyberSecurity process for the application in the development phase. As part of it we have to use Fortify and Sonatype Plugins in eclipse che. 

Do we have an option for this requiement?

**Comment by sunix** [comment]
Hello Veer,
I am not sure we have these plugins by default in Eclipse Che. Che plugins are vscode extensions backed by sidecar containers (for system dependencies). So if there are existing vscode extension, there is good chances that those extension can run in Eclipse Che.

**Comment by veeramanikandanvv** [comment]
Do we have any documentation for this?

**Comment by veeramanikandanvv** [comment]
We are seeing Fortify & Sonatype plugins in Visual Studio Market place but not in VSCode market place. Will that be compatible?

**Comment by azatsarynnyy** [comment]
> We are seeing Fortify & Sonatype plugins in Visual Studio Market place but not in VSCode market place. Will that be compatible?

@veeramanikandanvv Che supports VS Code extensions, but not Visual Studio extensions

**Comment by azatsarynnyy** [comment]
> Do we have any documentation for this?

This should help https://www.eclipse.org/che/docs/che-7/end-user-guide/testing-a-visual-studio-code-extension-in-che/

**Comment by gattytto** [comment]
I'll try my best with this one
