### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18474]
### Describe the bug

I'm unfortunately unable to figure out anything beyond the logs. 

`Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)`

Error.txt and logs: https://1drv.ms/u/s!AoSeaeVYrPG8jL1mt-k_otuRka37-A?e=9TkESQ
### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

`chectl server:deploy --che-operator-cr-yaml='/media/charlesrod/KINGSTON/kubernetes/k8s/che/che-cluster.yaml' -a operator -p k8s -b che-che.url.com` 

![image](https://user-images.githubusercontent.com/4656027/100394333-67888480-3002-11eb-8d72-61c7c9a25c68.png)

I've been able to deploy other k8s apps. Any further information I can give, just let me know. 

### Runtime
   - [ x ] kubernetes (include output of `kubectl version`)

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-16T17:18:52Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ x ] other: (please specify): k3os

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ x ] other (please specify): k3os
   - [ ] other: please specify

**Comment by tolusha** [comment]
Probably that is a location of the error:
https://github.com/eclipse/che-operator/blob/master/pkg/deploy/server/che_configmap.go#L285

@gnoejuan 
Do you have `che-tls` secret created in a namespace ?

**Comment by gnoejuan** [comment]
> Do you have `che-tls` secret created in a namespace ?

This lead me to the correct solution. There was a problem with the tls secret outside of Che's scope. Thank you!

**Comment by tolusha** [comment]
I will keep this issue opened for a while since NPE is not good anyway.

**Comment by mmorhun** [comment]
Fixed
