### ISSUE TITLE
Progress of workspace starting doesn't display on the dashboard-next

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#18477]
### Describe the bug
After creation workspace using dashboard-next the current workspace status doesn't match to displayed. 

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Deploy Che using minikube and chectl according to documentation.
 - Go to dashboard-next (edit URL   <producturl>/dashboard/next)
 - Create workspace using predefined devfiles
 - Wait several minutes and pay attention that according to workspace displaying created workspace still starting
 - Refresh page and pay attention that workspace already started

### Expected behavior:
The dashboard next shows the correct workspace status

### Observed behavior
The dashboard next shows the wrong workspace status

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (minikube version: v1.15.1)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
```                     
                  ${pathToChectl} server:deploy \\
                        --k8spodreadytimeout=600000 \\
                        --k8spodwaittimeout=600000 \\
                        --k8spoddownloadimagetimeout=600000 \\
                        --listr-renderer=verbose \\
                        --platform=minikube \\
                        --che-operator-cr-patch-yaml=$CUSTOM_RESOURCE_PATCH_FILE \\
                        --chenamespace=eclipse-che
```

   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context
![Screenshot from 2020-11-27 16-00-54](https://user-images.githubusercontent.com/22724619/100462040-50b16300-30d2-11eb-8a0f-b432d348e3fc.png)
![Screenshot from 2020-11-27 16-01-09](https://user-images.githubusercontent.com/22724619/100462044-5313bd00-30d2-11eb-93ef-8af1141c952b.png)

**Comment by sleshchenko** [comment]
Here we have two issues:
1. Dashboard fails to establish websocket connection.
2. Dashboard does not show a warning banner that websockets are not working. <- we already implemented it for existing Dashboard.

**Comment by Ohrimenko1988** [comment]
Fixed

**Comment by sleshchenko** [comment]
The part with the warning banner should be fixed in https://github.com/eclipse/che/issues/18490
