### ISSUE TITLE
configure PVC in eclipse che without using storage class name

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18470]
Is there a way in che to create PVC without using storage class names ?
I am trying to configure NFS as a PV for che using the doc - https://docs.microsoft.com/en-us/azure/aks/azure-nfs-volume
In the document, when creating PVC the storage class name needs to be empty, but che relies on storage class name to configure PVC's. Is there a way we can configure without using storage class name ?

**Comment by tolusha** [comment]
If storageclass isn't specified then a default will be used.

**Comment by chopraaakash91** [comment]
is there a way to configure che with persistent volume directly without using the storage class name ?
I am trying to configure NFS Server - https://docs.microsoft.com/en-us/azure/aks/azure-nfs-volume
and using storage class name is not possible if you see the documentation.
