### ISSUE TITLE
Invalid suggested command in chectl 

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18481]
### Describe the bug
chectl is displaying a wrong error message about a command to launch

### Che version
 - [x] nightly

### Steps to reproduce

After some errors on chectl server:deploy I've the following message:
```
›   Warning: Eclipse Che has been already deployed. Use server:start command to start a stopped Eclipse Che instance.
```

but server:start has been renamed to `server:deploy` so it won't work:

```
$ chectl server:start -p docker-desktop -i helm
› Current Kubernetes context: 'docker-desktop'
 ›   Error: Unexpected arguments: -p, docker-desktop, -i, helm
 ›   See more help with --help
```

### Expected behavior
Provides in help the new alias of the command

### Installation method
   - [x] chectl next

### Environment
   - [x] my computer / macOS

**Comment by tolusha** [comment]
@benoitf 
The message is not wrong. 
Please use `chectl server:start` without any flags. Since Eclipse Che has been already deployed neither `platform` no `installer` flags aren't needed anymore.

 for details: `chectl server:start -h`

**Comment by benoitf** [comment]
ok
