### ISSUE TITLE
[plugin-registry] Add support of the non-milicores values for the CPU Request / Limit

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18488]
### Is your enhancement related to a problem? Please describe.
Need to add support of the non-milicores values for the CPU Request / Limit e.g.

```
     cpuLimit: "1"
     cpuRequest: "0.03"
```

Currently, this fails with the schema validation exception:

```The command '/bin/sh -c ./check_metas_schema.sh v3' returned a non-zero code: 1 Error: Process completed with exit code 1.```

### Describe the solution you'd like
Both `1000m` and `1` values should be supported 

### Describe alternatives you've considered
Fix https://github.com/eclipse/che/issues/18484

### Additional context

See https://github.com/eclipse/che-plugin-registry/pull/716

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che-plugin-registry/pull/741
