### ISSUE TITLE
Very high CPU / Memory Request is set on the jwtproxy end

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18483]
### Is your enhancement related to a problem? Please describe.
jwt proxy is the only container that specifies CPU limit atm which is pretty high:

```
    Limits:
      cpu:     500m
      memory:  134217728
    Requests:
      cpu:     500m
      memory:  134217728
```

According to the 3.11 graphs request should be fairly low:

![image](https://user-images.githubusercontent.com/1461122/100605450-3b257e80-3308-11eb-8cc0-72529c408363.png)

### Describe the solution you'd like

memory request - 10 Mb
CPU request - 0.02 cores

**Comment by ibuziuk** [comment]
It looks like currently there are no properties for jwtproxy requests (only limits)

che.server.secure_exposer.jwtproxy.memory_limit=128mb
che.server.secure_exposer.jwtproxy.cpu_limit=0.5

so, I believe we need to introduce two new properties:

```
che.server.secure_exposer.jwtproxy.memory_request
che.server.secure_exposer.jwtproxy.cpu_request
```

The default values for the request could be `10md` and `0.01` according to the metrics:

![image](https://user-images.githubusercontent.com/1461122/100721375-89e21f80-33bf-11eb-8e5b-3210cec203c2.png)

**Comment by sparkoo** [comment]
docs issue is created. As docs PRs are merged after the release, I'm closing this issue.
