### ISSUE TITLE
[plugin-registry] Specifying memoryRequest, cpuRequest, cpuLimit to the plugins

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18485]
### Is your task related to a problem? Please describe.
Currently `memoryRequest`, `cpuRequest` and `cpuLimit` are not set for the plugins in the plugin registry. 

### Describe the solution you'd like
Each plugin should specify not only `memoryLimit`, but also:
- `memoryRequest`, 
- `cpuRequest`
- `cpuLimit` 

### Additional context
List of plugins:

- [ ] che-theia https://github.com/eclipse/che-plugin-registry/pull/716
- [ ] machine-exec
- [ ] jwt-proxy (related issue - https://github.com/eclipse/che/issues/18483)
.
.
.
- [ ] ....

Draft PR - https://github.com/eclipse/che-plugin-registry/pull/471/files

**Comment by ericwill** [comment]
I think we can use https://github.com/eclipse/che/issues/16685 for this, is that okay with you @ibuziuk?

**Comment by ibuziuk** [comment]
@ericwill #16685 does not have the memory request part

**Comment by ericwill** [comment]
> @ericwill #16685 does not have the memory request part

Now it does! Closing this ticket in favour of #16685
