### ISSUE TITLE
Che dashboard workspace is not loading on the UI

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18499]
I am trying to follow the contributing guide to start che-dashboard workspace - https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#dashboard

I am using the below devfile to create a workspace for che-dashboard:

apiVersion: 1.0.0
metadata:
  name: che-dashboard
projects:
  - name: che-dashboard
    source:
      location: 'https://github.com/eclipse/che-dashboard.git'
      type: git
components:
  - id: che-incubator/typescript/latest
    type: chePlugin
    alias: typescript-plugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'true'
          protocol: http
          path: /
        name: dashboard-dev-server
        port: 3000
    memoryLimit: 3Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-dashboard-dev:nightly'
    alias: dash-dev
commands:
  - name: '[UD] build'
    actions:
      - workdir: /projects/che-dashboard
        type: exec
        command: yarn build
        component: dash-dev
  - name: '[UD] install dependencies'
    actions:
      - workdir: /projects/che-dashboard
        type: exec
        command: yarn
        component: dash-dev
  - name: '[UD] start dev-server'
    actions:
      - workdir: /projects/che-dashboard
        type: exec
        command: 'npx gulp serve --server=${CHE_API_EXTERNAL%????}'
        component: dash-dev
  - name: '[UD] test'
    actions:
      - workdir: /projects/che-dashboard
        type: exec
        command: yarn test
        component: dash-dev

On the UI, I can see all logs are properly printed with all the images being pulled successfully and then it displays loading Runtime token and then it just keeps loading forever. 

I can see all the pods are up and running in kubectl get pods. 
Got the following error when checked the logs of theia container - 

2020-12-01 12:12:07.640 root ERROR Security problem: Unable to configure separate webviews domain:  Params: Error: Unable to get workspace containers. Cause: [object Object]
    at CheServerWorkspaceServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:193:31)
    at step (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:62:23)
    at Object.throw (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:43:53)
    at rejected (/home/theia/node_modules/@eclipse-che/theia-remote-api/lib/node/che-server-workspace-service-impl.js:35:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-01 12:12:07.641 root WARN Backend PluginApiContributionIntercepted.onStart is slow, took: 130096.1 ms 

Also, in the chrome browser console, I see the following error - Error: TIMEOUT
    at e._handleTimeout (https://static.developers.redhat.com/che/theia_artifacts/vendors.c8bdf28598a14f9b5776.js:365:8016)
    at https://static.developers.redhat.com/che/theia_artifacts/vendors.c8bdf28598a14f9b5776.js:365:7896

**Comment by veeramanikandanvv** [comment]
Can you please provide more details on the ingress controller namespace

**Comment by chopraaakash91** [comment]
It is working fine now, looks like an intermittent issue that came yesterday. Although, this issue is similar to - https://github.com/eclipse/che/issues/18255. Not sure how it is working now, I haven't done any changes.

did any one else faced this yesday as well ? or have you guys seen this error earlier ?

**Comment by chopraaakash91** [comment]
I could not find any error in ingress logs though.

**Comment by RomanNikitenko** [comment]
> It is working fine now, looks like an intermittent issue that came yesterday. 

Tried to reproduce on 2 different instances  - I was not able to reproduce the problem.



I'm not closing the issue, please provide more details if you are able to reproduce it again.

**Comment by myronV** [comment]
Hello! I have the same error when creating a workspace. In the logs of the Theia container I saw the same errors as in @chopraaakash91, also I have an error in the JVT container that the connection was Hijacked. I am not very strong in the knowledge of Kubernetes, but can I provide any more information?

**Comment by azatsarynnyy** [comment]
Hello @myronV 
what version of Che Server and Che-Theia you're using?
Recently we've met a similar issue that was caused by incompatible versions of different components.
For example https://github.com/eclipse/che/issues/18552#issuecomment-740582339

**Comment by myronV** [comment]
> Hello @myronV
> what version of Che Server and Che-Theia you're using?
> Recently we've met a similar issue that was caused by incompatible versions of different components.
> For example [#18552 (comment)](https://github.com/eclipse/che/issues/18552#issuecomment-740582339)

I use 
Eclipse Che CLI
VERSION
  chectl/0.0.20201203-next.d87017f wsl-x64 node-v10.23.0
Eclipse Che Version    : 7.23.0-SNAPSHOT
 and Theia-ide:latest

**Comment by azatsarynnyy** [comment]
@myronV looks like you hit the same issue as described in https://github.com/eclipse/che/issues/18552#issuecomment-740582339
Try switching to `che-theia:next`

**Comment by myronV** [comment]
> @myronV looks like you hit the same issue as described in [#18552 (comment)](https://github.com/eclipse/che/issues/18552#issuecomment-740582339)
> Try switching to `che-theia:next`

All the same errors with `che-theia:next` 
Also, I have errors in the web-browser, about loading resources timeout
![image](https://user-images.githubusercontent.com/38347451/101533955-2ba8d400-399f-11eb-813f-1000136da6b8.png)

**Comment by azatsarynnyy** [comment]
Maybe @tolusha can help here. I'm not sure what was the solution for https://github.com/eclipse/che/issues/18552#issuecomment-740582339

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/18552 was closes as "Can't reproduce"

@myronV  @chopraaakash91 
Try to update eclipse-che custom resource and set
`spec.server.useInternalClusterSVCNames: false`

**Comment by tolusha** [comment]
I am supposed that Eclipse Che has been installed using `--installer helm` .
Could you confirm that ?

**Comment by myronV** [comment]
> Try to update eclipse-che custom resource and set
> `spec.server.useInternalClusterSVCNames: false`

Hi! How I can do it?
And yes, I used `--installer helm` for deploying Eclipse Che.

**Comment by tolusha** [comment]
> spec.server.useInternalClusterSVCNames: false

It is for `--installer operator`.
Meanwhile please use the latest stable version of chectl
1. `chectl update stable`
2. `checlt server:deploy...`

**Comment by myronV** [comment]
> It is for `--installer operator`.

Oh, nice. Already is working. Thx for help

**Comment by tolusha** [comment]
@chopraaakash91 
could you provide more details about your cases?
Could you provide checlt command line you used ?

**Comment by tolusha** [comment]
Fixed for (tested for both `--installer helm` and `--installer operator`)
```
$ chectl version
chectl/0.0.20201210-next.0af053a linux-x64 node-v10.23.0
```
