### ISSUE TITLE
[documentation] - improve single-host setup documentation

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18498]
### Is your enhancement related to a problem? Please describe.

This documentation page has several issues https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspace-exposure-strategies/

 - [x] multi-host - `On OpenShift, this is the only possible strategy, and manual configuration of the workspace exposure strategy is therefore always ignored.` -> no longer true
 - [x] single-user - https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspace-exposure-strategies/#configuring-workspace-exposure-strategies-using-an-operator_configuring-workspace-exposure-strategies does not describe the simplest way how to deploy in single-host (or other strategies), it is just setting `server.serverExposureStrategy`. This should be imho emphasized in the beginning of the docs, that this is the property to look for.

There are probably more issues on this page as there were quite few changes especially with single-host. Read through the page and reflect the current state.

### Describe the solution you'd like

 - fix the issues above

**Comment by themr0c** [comment]
Referenced in: https://issues.redhat.com/browse/RHDEVDOCS-2455
