### ISSUE TITLE
[dashboard-next] show warning banner when websockets are not available

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18490]
### Is your enhancement related to a problem? Please describe.
That's already done for the existing dashboard.
Dashboard next should show warning banner when websockets are not available since it leads to 
incorrect work.

The related issue and PR for Dashboard https://github.com/eclipse/che/issues/17280 https://github.com/eclipse/che-dashboard/pull/72

**Comment by sleshchenko** [comment]
@ParvathyRV will provide the design
Spoiler: PF banner should be used here https://www.patternfly.org/v4/components/banner/

**Comment by parvathyvr** [comment]
@sleshchenko -below is the mock up screen using the PF4 banner for a global alert scenario.
![1-Che - Workspace-Global warning](https://user-images.githubusercontent.com/33114242/103016485-1bc8ec80-4568-11eb-96c7-e8ba0d3d6fc2.png)

**Comment by sleshchenko** [comment]
The described issue is fully solved by referenced PRs (not all are merged): warning banner is shown when Dashboard is loaded but websockets are blocked.

But it makes sense to extend the scope a bit:
- websocket context should be on WorkspaceClient side and clients (like dashboard does not need to define it). I think it may be a legacy from times when we had minor and major websocket endpoints https://github.com/che-incubator/che-dashboard-next/pull/112#discussion_r554049705
- client should be able to define a token initially, and then redefine it once it's expired https://github.com/che-incubator/che-dashboard-next/pull/110#pullrequestreview-564159859

Then we'll get the following workflow:
- WebSocket is established.
- WebSocket is interrupted.
  - WsClient notifies the dashboard about it.
  - Dashboard displays banner that WebSocket is lost
- WsClient endless tries to reconnect with dynamic delay: first 10 times every second, then every 30 seconds for example.
- Once Websocket is reestablished, WSClient notifies Dashboard that everything is fine with Websockets now.
- Dashboard hides the banner.

**Comment by sleshchenko** [comment]
Seems every related PR is merged. @JPinkney Can this issue be closed or there is anything left?

**Comment by JPinkney** [comment]
It can be closed
