### ISSUE TITLE
Suggest only the `latest` plugin version to use

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18491]
### Is your task related to a problem? Please describe.
Che Plugin Registry started serving only the latest version, so if a user chooses a specific version of the plugin, the workspace will be broken once Che Plugin Registry is updated with the newer plugin version.
We should suggest only the `latest` plugin version to use.
It may be solved on different levels:
- **Che plugin registry**: instead of having(che theia is used as an example):
```
  eclipse/che-theia/next
  eclipse/che-theia/7.22.0
  eclipse/che-theia/latest
```
go to
```
  eclipse/che-theia/next
  eclipse/che-theia/latest (the version inside is 7.22.0) 
```
- Dashboard: analyze that some version is an alias for another and merge them.

I believe the first is simpler, the second is possible but I don't have a good understanding the way how Dashboard and Devfile Editor (Yaml LS) should be improved to cover such cases.

### Additional context
How it currently looks like in the Dashboard:
![Screenshot_20201130_170958](https://user-images.githubusercontent.com/5887312/100628520-f95cfe00-3330-11eb-99c9-4ec84bbe8f94.png)
![Screenshot_20201130_171325](https://user-images.githubusercontent.com/5887312/100628523-f9f59480-3330-11eb-906a-e4ed1f17cefc.png)

**Comment by sleshchenko** [comment]
Documentation also needs to be reviewed if it does not suggest to use non-latest plugins, like here https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_component_type_cheplugin

**Comment by ericwill** [comment]
This task is a two-part fix right? One in Dashboard and the other on our side (docs, etc.)?

**Comment by benoitf** [comment]
I think first step is to remove 'version' entries in che-plugin-registry (just have 'latest' (+ other aliases like next) containing the meta.yaml)
so instead of having `my/plugin/v3.0.0` and `my/plugin/latest` to just have `my/plugin/v3.0.0` in index.json/v3/plugins

then dashboard will no longer see the versions like `v3.0.0` (nothing to do in dashboard)

then documentation can be updated

**Comment by nickboldt** [comment]
See also https://github.com/eclipse/che/pull/18822

**Comment by ericwill** [comment]
I think this one can be closed, no? AFAIK we are not suggesting versioned plugins anymore.
