### ISSUE TITLE
Che ignores user response when asks whether it should restore workspace or not

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#1849]
When there is workspace snapshot and user opens IDE it asks whether workspace should be restored or not. If user press cancel IDE does not send request to restore but default restoring behavior restores WS anyway.

**Reproduction Steps:**
1. Start workspace
2. Create a snapshot
3. Stop workspace
4. Refresh window
5. Click 'no' in Workspase recovering popup.

**Expected behavior:**

Correct behavior should be either Che doesn't ask user about restoring or send request with flag that forbids restoring enabled by default.

**Observed behavior:**

Default restoring behavior restores WS

**Comment by vkuznyetsov** [comment]
Easy fix. To fix just add boolean parameter to start workspace method of workspace manager. https://github.com/eclipse/che/blob/ce6fb560d3517f94170911425417b8fe91e3293d/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceService.java#L308-L308

**Comment by vinokurig** [comment]
@slemeur Please chose the behavior in this case:
1. Since we have snapshot auto-restore we can remove asking user to restore from snapshot. But auto-restore can be disabled and user can not enable it by himself. So if user will have snapshot and the auto-restore will be disabled user will not be able to restore ws from snapshot.
2. Also we can modify the start ws API request with flag that forbids restoring, if it is enabled by default.

**Comment by slemeur** [comment]
System define default behaviors - but the user must keep the control on what will happen. So, do not remove this ability for the user, but modify the API to take into account the choice made by the user.

In the future, we'll have this wizard to restart a workspace from the IDE:
![restart](https://cloud.githubusercontent.com/assets/1636769/16980314/ae1c446e-4e65-11e6-9cc7-4be6875f6a7a.png)

The checkbox, will be checked/unchecked by default depending on first:
1- Default system behavior
2- Workspace's configuration for this option

**Comment by TylerJewell** [comment]
-1 on this behavior.  It is not a suitable Ux.

**Comment by vinokurig** [comment]
@TylerJewell What should we do in this case?

**Comment by TylerJewell** [comment]
My -1 is to Stevan's wizard behavior not this issue.

**Comment by garagatyi** [comment]
@slemeur @TylerJewell Can you elaborate on which UX is OK. We prefer having spec on what should be done before we will change API.

**Comment by garagatyi** [comment]
Right now we considering API changes that will allow IDE to either:
- start workspace with restore
- start workspace without restore (no matter if auto-restore is enabled) 
- start workspace and rely on auto-restore behavior 

Please describe how workspace dialog should work. Then we will be able to implement needed changes.

**Comment by slemeur** [comment]
The API description you are providing is the good one.

@TylerJewell : your feedback is about the UI, not about the ability for the user to choose if he wants to restart the workspace from snapshot, right?

**Comment by TylerJewell** [comment]
You should start on the API.

My issue is with the IDE ui and dialog box which needs to change.  I do not think we will have a Ux design quickly so just do the API change now.
