### ISSUE TITLE
che-dashboard websocket Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by Rhain** [eclipse-che/che#18492]
Runing the che-dashboard project in locally, use the default api server 'https://che.openshift.io'.

then, got the websocket error `Connection closed before receiving a handshake response `.

![image](https://user-images.githubusercontent.com/1488036/100685721-db86ac00-33b7-11eb-836b-6c80f556f2a1.png)

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1.  open project che-dashboard
2. run `yarn serve`
3. open browser `http://localhost:3000/`

### Expected behavior
websocket working correctly

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by Rhain** [comment]
Is there any progress?

**Comment by sleshchenko** [comment]
we're moved to a new dashboard, which works fine for me when I do `yarn start` against che.openshift.io.

Please reopen if it still does not work for you
