### ISSUE TITLE
Document the differences of Che Theia WebView behavior in single-/multi-host modes

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18496]
### Is your task related to a problem? Please describe.
There're some differences in Che Theia WebView behavior depending on Che mode - single- or multi-host.
These differences are important to the user. ATM the known differences are:
1. When in a single-host mode, a WebView content is loaded from the same origin as Che Theia, so a WebView has access to Che Theia page's data in a browser
2. Unlike FireFox, Chrome browser requires importing a CA certificate to allow installing a [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) for loading a WebView content within Che Theia. It's needed to ensure [a secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).

### Describe the solution you'd like
Need to document it in Che/CRW docs.

**Comment by azatsarynnyy** [comment]
We've already discussed the first point - regarding the same origin for Che Theia and a Webview.

The second one we've discovered recently, with @sleshchenko. And I want to gather the opinions on how it's better to document it. This is how it looks to the end-user.

I go to Che URL without Che's self-signed CA certificate imported. Chrome provides the option to proceed with the disabled security check:

![image](https://user-images.githubusercontent.com/1636395/100776213-f0d9f580-340c-11eb-9fdc-8eb921e8c8f2.png)

I proceed and I'm able to load Che Theia but not a Webview, like the Welcome page.

![image](https://user-images.githubusercontent.com/1636395/100776868-bde43180-340d-11eb-8e97-95e2c6bfe215.png)

In the console, Chrome warns me about the security breach:

`
SecurityError: Failed to register a ServiceWorker for scope ('https://192.168.99.241.nip.io/serverlo8io398-jwtproxy/webviews/webview/') with script ('https://192.168.99.241.nip.io/serverlo8io398-jwtproxy/webviews/webview/service-worker.js'): An SSL certificate error occurred when fetching the script.
`

Chrome allows installing a [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) (load a Webview) in a completely [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) **only**.

For local development/testing Chrome provides a couple of options to disable this check:
1. `chrome://flags/#unsafely-treat-insecure-origin-as-secure` flag
2. `--ignore-certificate-errors` cmd parameter for launching the browser

So, there're three options available for the Che/CRW user: two mentioned above + import the self-signed CA certificate into Chrome.

Should we only recommend the user to import a self-signed certificate? Or document all three options at the discretion of the user?
In particular, I'm not sure whether all three are good advice for CRW users.
WDYT? @l0rd @benoitf @sympatheticmoose

**Comment by azatsarynnyy** [comment]
I believe we can't advise the user to disable the security checks in Chrome, as they are introduced to facilitate local development/testing only.

**Comment by l0rd** [comment]
@azatsarynnyy it looks like we are back at the initial problem we had with multi-host. In both cases we need to locally import the CA cert if it's untrusted by the local browser. That's annoying. Isn't there an alternative to serviceworker to load webviews?

**Comment by azatsarynnyy** [comment]
> ... Isn't there an alternative to serviceworker to load webviews?

@l0rd  Service workers are an essential part of Webview API in Theia. It allows handling loading the webview resources (packaged with a plugin) in a very neat/graceful way.
Initially, such architecture comes from VS Code, after they reworked their Electron-based webviews. Then it was adopted by upstream Theia and Che Theia. Now, we’re working on adapting it to our multi-container approach. It’s a true upstream-first way of consuming that part: VS Code > Theia > Che Theia. So, we’re able to get the latest changes relatively cheap.

I agree, asking the user to import a certificate is an annoying step. But I’m not sure if it worth reinventing the wheel yourself by implementing the whole complex mechanism of Webview API in some alternative way and start maintaining it downstream.

**Comment by azatsarynnyy** [comment]
che-docs has been updated with the note https://github.com/eclipse/che-docs/pull/1717
We'll investigate if it's possible to do something with ServiceWorker https://github.com/eclipse/che/issues/18566
