### ISSUE TITLE
Docs may out of date

### ISSUE THREAD

**Issue by xring** [eclipse-che/che#185]
I followed the docs on [documentation](https://eclipse-che.readme.io/docs/openshift-config) , after `git checkout openshift` and execute `mvn clean install`, I got these errors:

> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]  
> [ERROR]   The project org.eclipse.che.depmgt:maven-depmgt-pom:4.0.0-M5 (/root/che-depmgt/pom.xml) has 1 error
> [ERROR]     Non-resolvable parent POM: Could not transfer artifact org.eclipse.che.parent:maven-parent-pom:pom:4.0.0-M5 from/to codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/): maven.codenvycorp.com: unknown error and 'parent.relativePath' points at no local POM @ line 16, column 13: Unknown host maven.codenvycorp.com: unknown error -> [Help 2]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

actually these two urls are not reachable:

```
Downloading: https://maven.codenvycorp.com/content/repositories/codenvy-public-snapshots/org/eclipse/che/parent/maven-parent-pom/4.0.0-M5/maven-parent-pom-4.0.0-M5.pom
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/che/parent/maven-parent-pom/4.0.0-M5/maven-parent-pom-4.0.0-M5.pom
```

**Comment by TylerJewell** [comment]
Sorry about this.

The OpenShift plug-in was built specifically against version 4.0.0-M5
version.  Please do a git checkout of this version of Eclipse Che to build
against and you will not get these errors.  We recently changed the groupId
and artifactId of core Che modules in a recent release, and we haven't
updated the OpenShift docs and plug-in to reflect this.

I opened an issue to get this done.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by xring** [comment]
Thanks @TylerJewell I'll try it.

**Comment by TylerJewell** [comment]
Could you tell us more about your OpenShift environment?  Is it OpenShift enterprise or OpenShift Dedicated?
