### ISSUE TITLE
Add multi-platform images for che-machine-exec releases

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#18509]
### Is your enhancement related to a problem? Please describe.
It would be nice to apply multi-platform images for che-machine-exec releases. We have such platform images for nightly tag. We should provide the same feature for released versions of the che-machine-exec.

### Describe the solution you'd like
It would be nice to apply multi-platform images for che-machine-exec releases. We have such platform images for nightly tag. We should provide the same feature for released versions of the che-machine-exec.

**Comment by tolusha** [comment]
We need to add `linux/arm64` to build patforms [1] only.
Adding `linux/s390x` depends on https://github.com/eclipse/che/issues/19062
[1] https://github.com/eclipse-che/che-machine-exec/blob/master/make-release.sh#L35-L42
[2] https://github.com/eclipse/che/issues/19062
