### ISSUE TITLE
[che-operator] garbage collect cluster-scoped objects

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18501]
### Describe the bug

Che-operator is using owner reference for namespaced-scoped objects, so they are autmatically cleaned when parent object is deleted. However, this does not work for cluster-scoped objects, like `consolelink`, `oauthclient`, `clusterrolebinding`, ... This does not work by design on Kubernetes https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents.
These objects are not cleaned when che is uninstalled from the cluster. Chectl is trying to do some cleanup (cleaning the consolelink), but it's not without issues and with that, che-operator is leaking object's lifecycle. Also, if you uninstall che instance by deleting CheCluster instance, all these objects are not removed as chectl is not involved in the process.

#### Proposed solution
This is just an idea, but might be useful here (bear in mind that I don't fully know the whole deployment lifecycle)
 - label all cluster-scoped objects with `component=che,app=che,namespace=<installation-namespace>`. With this, we sould be able from che-operator or chectl find all cluster-scoped objects and clean them.

### Expected behavior

Che-operator should not left any che runtime objects after che is uninstalled.

### Che version

 - [x] latest

### Steps to reproduce
1. deploy with che-operator on openshift
1. remove CheCluster instance
1. list consolelink or oauthclient objects (`kubectl get consolelink`, `kubectl get consolelink`) and see they are still there, but che pods/services/ingresses are gone

### Runtime
   - [x] Openshift (include output of `oc version`)

### Installation method
   - [x] chectl

### Additional context
https://github.com/gorkem/app-labels/blob/master/labels-annotation-for-openshift.adoc

this PR will add clusterrolebindings that is cluster-scoped as well, so it will not be cleaned https://github.com/eclipse/che-operator/pull/543

### Related issues
che-operator does not clean old ConsoleLink on changeName/update/uninstall  https://github.com/eclipse/che/issues/17185

**Comment by tolusha** [comment]
consolelink, clusterrolebinding, oauthclient are removed when checluster CR is removed.
