### ISSUE TITLE
chectl server:update requires chectl to be updated first

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18514]
### Describe the bug
I have been trying to upgrade Che with chectl following https://www.eclipse.org/che/docs/che-7/installation-guide/upgrading-che-using-the-cli-management-tool/. 
First the describe command are not working out of the box:

![Selection_078](https://user-images.githubusercontent.com/650571/100902428-293d0a80-34c5-11eb-938d-a65328546a39.png)

```
$ chectl -n che server:update
> Error: command -n not found
```
and then the platform is required

Then, It wasn't completly clear that I needed to update chectl as well. Should tell the user how to upgrade chectl.

![Selection_079](https://user-images.githubusercontent.com/650571/100903888-b46ad000-34c6-11eb-8119-992ef2550582.png)

### Che version

 - [x] 7.20.1

### Runtime
   - [x] kubernetes (GKE)

### Installation method
   - [x] chectl

### Environment
   - [x] Cloud
       - [x] GCE

**Comment by l0rd** [comment]
> First the describe command are not working out of the box

@sunix what do you mean? That when an error occurs we should show the "usage" message?

> Then, It wasn't completely clear that I needed to update chectl as well. Should tell the user how to upgrade chectl.

That's fair. `chectl server:update -p k8s` won't do the update if you don't have a newer version of the operator yaml files. Upgrading chectl is one option, probably the easiest one. But we could also just fetch the latest deployment yaml files.

**Comment by sunix** [comment]
> > First the describe command are not working out of the box
> 
> @sunix what do you mean? That when an error occurs we should show the "usage" message?

No just neeed to fix in our doc, `-n` option is placed before the command, should be command first

**Comment by tolusha** [comment]
doc PR https://github.com/eclipse/che-docs/pull/1729
chectl PR to improve messages and notify user to update chectl https://github.com/eclipse/che-docs/pull/1729

**Comment by sunix** [comment]
I am reopening this issue as it is not clear at all
https://www.eclipse.org/che/docs/che-7/installation-guide/upgrading-che-using-the-cli-management-tool/

> Prerequisites
> - And administrative account on an OpenShift instance.

Should not be openshift but kubernetes

> - A running instance of a previous minor version of Eclipse Che, installed using the CLI management tool on the same instance of OpenShift, in the <eclipse-che> project.
> - An installation of the chectl 7.25 version management tool. See Using the chectl management tool.

This is absolutely error prone. So finally the user will in anycase have to update chectl. So why not simply providing the right procedure. Something like:

> Run the following commands:
> 
> ```
>   $ chectl update
>   $ chectl server:update -n <eclipse-che>
>   ```

**Comment by boczkowska** [comment]
Docs team Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2654

**Comment by max-cx** [comment]
@sunix I'm working on fixing the docs.
Do you happen to know if the upgrade command should instead be presented in the text as
`$ chectl server:update -n eclipse-che`
rather than
`$ chectl server:update -n <_eclipse-che_>` as is now in
https://www.eclipse.org/che/docs/che-7/installation-guide/upgrading-che-using-the-cli-management-tool/

**Comment by tolusha** [comment]
It must be `chectl server:update -n eclipse-che`

**Comment by max-cx** [comment]
@tolusha Great, thank you! That answers my question. I'll fix it then,

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse/che-docs/pull/2071
