### ISSUE TITLE
Javascript editor does not validate code after changes

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1851]
**Reproduction Steps:**
1 Create javascript file and paste for example next code: 
function myFunction(name,job)
{ document.getElementById("demo").innerHTML ="Welcome " + name + ", the " + job + "."; }

**Expected behavior:**
We should see error marker with error 'document is undefined'

**Observed behavior:**
The error marker does not appear
Close file and open again. Error marker appears. After applying 'quick fix' proposal - all work correct.

**Che version:**  
Affects Versions: 4.x

**Comment by ghost** [comment]
Closed as duplicated of https://github.com/eclipse/che/issues/4886
