### ISSUE TITLE
Broken links in eclipse/che README

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18515]
### Describe the bug

Images on [REAME.md](https://github.com/eclipse/che/blob/master/README.md) are broken:

![image](https://user-images.githubusercontent.com/606959/100935668-acc02100-34f0-11eb-9851-f7fe7020230e.png)

The broken links are:
https://raw.githubusercontent.com/eclipse/che/assets/eclipseche.png
https://raw.githubusercontent.com/eclipse/che/assets/screenshoft_che7-quarkus-demo.png

**Comment by l0rd** [comment]
@sunix you added those links last year. I am not able to find them anymore.

**Comment by sunix** [comment]
someone removed the branch :/

**Comment by sunix** [comment]
I pushed back the branch

**Comment by sunix** [comment]
but not sure i had the right version can someone check ?

**Comment by sunix** [comment]
@l0rd do you have permission to set `assets` as a protected branch?

**Comment by l0rd** [comment]
> I pushed back the branch

Thanks

> @l0rd do you have permission to set assets as a protected branch?

No, please open a bugzilla

**Comment by sunix** [comment]
ok https://bugs.eclipse.org/bugs/show_bug.cgi?id=569452
