### ISSUE TITLE
Adapt documentation to Dashboard Next

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18518]
### Is your task related to a problem? Please describe.
This is an umbrella issue that holds work needed to adapts documentation to Dashboard Next.
Here is a list of articles that contains Dashboard screenshots or workflows:
- [x] End User Guide. Fix: https://github.com/eclipse/che-docs/pull/1737
  - Create and configure a workspace https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-and-configuring-a-new-workspace/
  - Configure workspace with k8s application as component https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-a-kubernetes-application-into-a-workspace/#adding-a-kubernetes-application-to-an-existing-workspace-using-the-dashboard_importing-a-kubernetes-application-into-a-workspace
  - Create a workspace from code sample https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-from-code-sample/
  - Create a workspace by importing source code https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-by-importing-source-code-of-a-project/
  - Starting a workspace in debug mode https://www.eclipse.org/che/docs/che-7/end-user-guide/starting-a-che-workspace-in-debug-mode/
  - Restart a workspace in debug mode after failure https://www.eclipse.org/che/docs/che-7/end-user-guide/restarting-a-che-workspace-in-debug-mode-after-start-failure/
  - Copy chectl login command https://www.eclipse.org/che/docs/che-7/end-user-guide/navigating-che-using-the-dashboard/#logging-in-to-eclipse-che-using-chectl_navigating-che-using-the-dashboard
- [x] Configuring storage type https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-storage-types/#_configuring_storage_type_defaults_for_che_dashboard **fix:** https://github.com/eclipse/che-docs/pull/1769
- [x] Generating Theia Plugins https://www.eclipse.org/che/docs/che-7/contributor-guide/developing-che-theia-plug-ins/#generating-a-new-plug-in-using-the-yeoman-wizard_developing-che-theia-plug-ins **fix:** https://github.com/eclipse/che-docs/pull/1768
- [x] Installing Che on AWS [article](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-aws/#installing-che-on-kubernetes-using-the-chectl-command_installing-che-on-aws) fix https://github.com/eclipse/che-docs/pull/1740/files
- [x] Installing Che on GCP [article](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-google-cloud-platform/#installing-che-on-google-cloud-platform-using-chectl_installing-che-on-google-cloud-platform) fix: https://github.com/eclipse/che-docs/pull/1739
- [x] Installing Che on Microsoft Azure [article](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/) fix https://github.com/eclipse/che-docs/pull/1740/files
- [x] Deploying Custom Registries [article](https://www.eclipse.org/che/docs/che-7/administration-guide/running-custom-registries/#deploying-registries-in-kubernetes_running-custom-registries) **fix:** https://github.com/eclipse/che-docs/pull/1749
- [x] Testing Che Theia Plugins [article](https://www.eclipse.org/che/docs/che-7/contributor-guide/testing-che-theia-plug-ins/) fix: https://github.com/eclipse/che-docs/pull/1750
- [x] Publishing Che Theia plugins [arcticle](https://www.eclipse.org/che/docs/che-7/contributor-guide/publishing-che-theia-plug-ins/) fix: https://github.com/eclipse/che-docs/pull/1745

Also, since Dashboard Next is going to appear upstream first, it's needed to make sure that CRW Docs still references Dashboard. Docs Team input is needed here.

**Comment by themr0c** [comment]
Copy chectl login command https://www.eclipse.org/che/docs/che-7/end-user-guide/navigating-che-using-the-dashboard/#logging-in-to-eclipse-che-using-chectl_navigating-che-using-the-dashboard -> A procedure without any screenshot would be better.

**Comment by themr0c** [comment]
Create and configure a workspace https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-and-configuring-a-new-workspace/ 
I believe we can restart from zero here, as only the devfile tab stays (nice UI simpification!). We could replace it with 3 navigation entries, like this, WDYT?
1. Creating a workspace from sample using the dashboard 
2. Creating a workspace from a remote devfile using the dashboard 
3. Creating a custom workspace with the devfile editor using the dashboard

**Comment by themr0c** [comment]
> Publishing Che Theia plugins https://www.eclipse.org/che/docs/che-7/contributor-guide/publishing-che-theia-plug-ins/

We can probably do without the screenshots.

**Comment by themr0c** [comment]
> Testing Che Theia Plugins https://www.eclipse.org/che/docs/che-7/contributor-guide/testing-che-theia-plug-ins/

Does not follow much modular docs guidelines, need rewrite that will probably make the screenshots useless.

**Comment by themr0c** [comment]
> Generating Theia Plugins https://www.eclipse.org/che/docs/che-7/contributor-guide/developing-che-theia-plug-ins/#generating-a-new-plug-in-using-the-yeoman-wizard_developing-che-theia-plug-ins

Does not follow much modular docs guidelines, need rewrite that will probably make the screenshots useless.

**Comment by themr0c** [comment]
>  Deploying Custom Registries https://www.eclipse.org/che/docs/che-7/administration-guide/running-custom-registries/#deploying-registries-in-kubernetes_running-custom-registries

The screenshots are redundant with the written content, we can remove them.

**Comment by themr0c** [comment]
> Configuring storage type https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-storage-types/#_configuring_storage_type_defaults_for_che_dashboard

Replace screenshots with more descriptive text.

**Comment by themr0c** [comment]
>  Installing Che on Microsoft Azure https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/

Replace screenshots with more descriptive text.

**Comment by themr0c** [comment]
> Installing Che on GCP https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-google-cloud-platform/#installing-che-on-google-cloud-platform-using-chectl_installing-che-on-google-cloud-platform

Replace screenshots with more descriptive text.

**Comment by sleshchenko** [comment]
The work on documentation is done, the [last PR](https://github.com/eclipse/che-docs/pull/1737) will be merged in a scope of issue about dashboard replacement
