### ISSUE TITLE
Useless error message on factory crane screen if devfile is invalid

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18511]
### Describe the bug

Factory crane screen does not give meaningful message when devfile is invalid. It only writes `Failed to fetch the devfile due to "400 Bad Request" returned by "/api/factory/resolver"`, which is more misleading than useful.

https://che.openshift.io/f?url=https://gist.githubusercontent.com/sparkoo/61c3edb2e245362e8aafda71074bd92c/raw/07b3081c6987cfe4f712711185de17f37104e2e6/invalidDevfile.yaml

### Che version

 - [x] latest

### Steps to reproduce
1. open invalid devfile with factory url
   - you can use this devfile https://gist.githubusercontent.com/sparkoo/61c3edb2e245362e8aafda71074bd92c/raw/07b3081c6987cfe4f712711185de17f37104e2e6/invalidDevfile.yaml
   - che.openshift.io factory link https://che.openshift.io/f?url=https://gist.githubusercontent.com/sparkoo/61c3edb2e245362e8aafda71074bd92c/raw/07b3081c6987cfe4f712711185de17f37104e2e6/invalidDevfile.yaml
1. see error message

### Expected behavior

We should give meaningful message what really happens. In this case something like "invalid devfile" and even better to write some output of devfile validation (like in dashboard editor).

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots

![20201202_145812_687x556_scrot](https://user-images.githubusercontent.com/1160903/100881979-e7a16500-34ae-11eb-92e2-1ee246d5e5d1.png)

### Installation method
   - [x] I don't know

### Environment
   - [x] che.openshift.io

**Comment by benoitf** [comment]
I think it's a duplicate of https://github.com/eclipse/che/issues/18164

**Comment by sparkoo** [comment]
> I think it's a duplicate of #18164

yes, I'm closing this one
