### ISSUE TITLE
Static version number in devfile registry doc

### ISSUE THREAD

**Issue by rkratky** [eclipse-che/che#18530]
### Describe the bug

The doc at https://www.eclipse.org/che/docs/che-7/administration-guide/building-custom-registry-images/#building-custom-devfile-registry-image_che lists

Ste #1 of the procedure:

```
$ git clone git@github.com:eclipse/che-devfile-registry.git
$ cd che-devfile-registry
$ git checkout 7.19.x
```
The version should be parametrized to always show the latest released version. (Or, if it already is parametrized, the value needs updating.)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-2461
