### ISSUE TITLE
Cannot apply Go into feature after reimporting a maven multimodule project

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1853]
**Reproduction Steps:**
1) Import from github a maven multimodule project. Apply Go into from context menu for any folder.
2) Import from github a maven multimodule project again. And try to apply  Go into feature again.

**Expected behavior:**   Go into feature should be available in the Context menu
**Observed behavior:**  Go into feature is not availible

**Che version:**    4.5.0
**OS and version:** Ubuntu OS 14.0  
**Docker version:** 1.11.2 
**Che install:**   local bundle   

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: YES

_Expected behavior :_ https://drive.google.com/file/d/0B3rJ8buYPDL6REVSYUdYUkhHT1k/view
_Actual behavior:_ https://drive.google.com/file/d/0B3rJ8buYPDL6QlZvSTVSbXdHYUE/view
Related selenium test: KeepDirectoryGitImportTest

**Comment by JamesDrummond** [comment]
@musienko-maxim Provide team label.

**Comment by ghost** [comment]
mcedit command still work

**Comment by musienko-maxim** [comment]
Still actual in version 5.15.0.

**Comment by ghost** [comment]
@vzhukovskii is it possible to have 2 projects in project explorer that can use go into feature?

**Comment by vzhukovs** [comment]
@eivantsov go into feature may be applied to any folder only once, there is the same behavior as in eclipse.

**Comment by ghost** [comment]
So, is there a fix for this one? The use case is that when one project is already in Go into, we clone a new project that does not have this feature available. If this is expected behavior, it's ok to close.  A workaround would be to go out of the first project?

**Comment by vzhukovs** [comment]
If go into has been already executed, so

>**Observed behavior:** Go into feature is not availible

this will be a right expectation. This issue might be closed.
