### ISSUE TITLE
How can I allow 'admin' user to access workspaces of all other users?

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#18538]
## Summary
Can I get the eclipse che admin user to read , start and stop che workspaces of others users?    I have been trying via the swagger apis to work with the che workspaces.  

I tried using the    following settings in the crd. 
   CHE_SYSTEM_SUPER__PRIVILEGED__MODE: "true"
   CHE_SYSTEM_ADMIN__NAME: "admin"  settings.  

But admin is able to work with just its own workspaces. 

Need some  help on this please...

**Comment by ibuziuk** [comment]
docs - https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/

```System Super Privileged Mode. Grants users with the manageSystem permission additional permissions for getByKey, getByNameSpace, stopWorkspaces, and getResourcesInformation. These are not given to admins by default and these permissions allow admins gain visibility to any workspace along with naming themselves with admin privileges to those workspaces.```

AFAIK Super Admin can not start & delete existing workspaces cc: @skabashnyuk

**Comment by ibuziuk** [comment]
@pgirishibm also, if you expect that workspace will be manageable via the GUI / UD then it is not the case. Only API requests are supported

**Comment by pgirishibm** [comment]
@ibuziuk  Thank you for this information. I did try out the 2 settings listed in the link, CHE_SYSTEM_SUPER__PRIVILEGED__MODE: "true"  and CHE_SYSTEM_ADMIN__NAME: "admin".  But I still do not see it working. i.e. the 'admin' user is not able to list the workspaces of other users. 

BTW, after adding the above two settings, I just restarted the che  pods. that should be good enough for the settings to take effect?

**Comment by pgirishibm** [comment]
a get permissions call for the admin user gives me this..
[{"id":"system","allowedActions":["manageSystem","monitorSystem","setPermissions","manageUsers"]},{"id":"workspace","allowedActions":["read","use","run","configure","setPermissions","delete"]},{"id":"devfile","allowedActions":["read","update","setPermissions","delete"]},{"id":"organization","allowedActions":["manageSuborganizations","update","setPermissions","delete","manageResources","createWorkspaces","manageWorkspaces"]}]

**Comment by sleshchenko** [comment]
Super admin should be able to list and stop workspace of other users. I'll take a look at that and provide some more details.

**Comment by sleshchenko** [comment]
Here is a code that allows admins (ones who has manageSystem on system domain) to stop/getByNamespace/getByID workspaces if the super-priviliged mode is enabled https://github.com/eclipse/che/blob/master/multiuser/permission/che-multiuser-permission-workspace/src/main/java/org/eclipse/che/multiuser/permission/workspace/server/filters/WorkspacePermissionsFilter.java

@pgirishibm first of all, make sure that you as admin have manageSystem in GET `api/permissions/system`. ( seems you shared the response from `api/permissions` which is not related to the current user).
- If no - something is wrong with configuring the admin.
- If yes - share the requests which fail for you.

**Comment by pgirishibm** [comment]
@sleshchenko I see every user in my che setup has manageSystem on system domain. so would that mean every user is an admin?  Eeeks.  This is still a dev environment though..

So is it the case that admin cannot see workspaces of other admins?  

Also any clues on what to check to remove admin from all normal users?

**Comment by sleshchenko** [comment]
> I see every user in my che setup has manageSystem on system domain. so would that mean every user is an admin? 

That must not be a true. On what your conclusion is based? Could you share the request or link to swagger API method?

**Comment by sleshchenko** [comment]
> So is it the case that admin cannot see workspaces of other admins?

no, admin is able to access every workspace(read configuration/stop/delete), even one that belongs to another admin.

**Comment by pgirishibm** [comment]
> > I see every user in my che setup has manageSystem on system domain.
> 
> That must not be true. On what your conclusion is based? Could you share the request or link to swagger API method?

If I do a getPermissions call on any user i get the same out put. 
`[{"id":"system","allowedActions":["manageSystem","monitorSystem","setPermissions","manageUsers"]},{"id":"workspace","allowedActions":["read","use","run","configure","setPermissions","delete"]},{"id":"devfile","allowedActions":["read","update","setPermissions","delete"]},{"id":"organization","allowedActions":["manageSuborganizations","update","setPermissions","delete","manageResources","createWorkspaces","manageWorkspaces"]}]`

**Comment by sleshchenko** [comment]
![Screenshot_20201210_091852](https://user-images.githubusercontent.com/5887312/101734313-bf29f400-3ac8-11eb-8562-2d8358a11c68.png)
Permissions just return the current permissions available to configure in general.
So, please use permissions/${domain} method instead

**Comment by pgirishibm** [comment]
@sleshchenko  Thank you.   using the permissions/${domain} method  I get this for admin for system
`{"actions":["manageUsers","setPermissions","monitorSystem","manageSystem"],"domainId":"system","userId":"6d54b11e-e157-4544-9f61-446b6a3032b3"}`
and this for other users. 
`System permissions for user '3f7b227e-310e-4d4f-8d64-2f84c6366d60' not found`

Now, using the access token of the admin, we were able to perform the following actions on the workspace of a user
1) List the workspaces created
2) Stop a workspace
What did not work was
1) Delete a workspace. 

So all this is working as designed and what you mentioned above as well. Thank you for the details. They were helpful.

**Comment by sleshchenko** [comment]
Great you hear that it works as supposed. Do you think you could try to contribute to che docs to make this thing simpler for others?)
BTW Closing this issue since the question is addressed. Feel free to reopen or create another ticket if you have any issue
