### ISSUE TITLE
Copy chectl login command on the Dashboard Next

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18533]
### Is your task related to a problem? Please describe.
It's needed to implement a command that will copy chectl login command into the buffer.

**Comment by parvathyvr** [comment]
@sleshchenko When the user clicks on the 'username' on the masthead we could show a menu with options like 'Account' 'User preferences' 'Logout' etc. The 'Copy chectl login command' can be part of the menu as the first option.
Here is a quick mock up of the same:
<img width="1506" alt="Menu under username in masthead" src="https://user-images.githubusercontent.com/33114242/101173572-bcfb0c00-3668-11eb-93a2-ff3f5b86b28a.png">
