### ISSUE TITLE
happy path che-server tests against ubi-based image

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18546]
### Is your task related to a problem? Please describe.
https://github.com/eclipse/che/blob/master/dockerfiles/che/rhel.Dockerfile File is used in Che downstream process.
We would like to  ensure that this image provides the same level of functionality as https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile

### Describe the solution you'd like
Enable happy path che-server tests against the ubi-based image

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/18545
https://github.com/eclipse/che/issues/18293#issuecomment-739819742
https://issues.redhat.com/browse/CRW-1381

**Comment by rhopp** [comment]
Are we even building/publishing this UBI version of server image? I guess that's first step (cc @nickboldt ). Then we can create nightly Happy Path job checking the basic functionality with the UBI version of che-server.

**Comment by skabashnyuk** [comment]
@rhopp we should https://github.com/eclipse/che/issues/18545
