### ISSUE TITLE
build ubi8 based che-server Dockerfile and push to quay

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18545]
### Is your task related to a problem? Please describe.
https://github.com/eclipse/che/blob/master/dockerfiles/che/rhel.Dockerfile File is used in Che downstream process.
We would like to give an opportunity to use/test this image widely. 

### Describe the solution you'd like
build ubi8 based che-server Dockerfile and push to quay

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by nickboldt** [comment]
I'm assuming we want a GH action to build a container and push to quay on every push. Do we need pull-request and manual triggers too?

**Comment by skabashnyuk** [comment]
> we want a GH action to build a container  

+1
> every push

+1 . let say with the tag `latest`

>pull-request 

+1

>manual triggers too

Not sure why we need it. Do you?

**Comment by nickboldt** [comment]
`ubi8-latest` probbly better than just `latest` to avoid collision with alpine builds.

**Comment by mkuznyetsov** [comment]
After moving from Centos CI to GH Actions workflow, now nightly builds feature new che server image based on ubi8 with tag `rhel-nightly`

**Comment by nickboldt** [comment]
I feel like we all decided to use ubi8-latest, not rhel-nightly... but sure? @skabashnyuk are you OK with this change?
