### ISSUE TITLE
Add prettier VS Code extension in plug-in registry

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18550]
### Is your enhancement related to a problem? Please describe.
Some che projects are using prettier (and many other projects as well)

### Describe the solution you'd like
There is a VS Code extension so we could have it enable don the plug-in registry

### Describe alternatives you've considered
N/A

**Comment by ericwill** [comment]
Not sure why this one got reopened, we have a prettier plugin in the registry now?

**Comment by benoitf** [comment]
fixed by https://github.com/eclipse-che/che-plugin-registry/pull/747

**Comment by benoitf** [comment]
@ericwill just wanted to append reason
