### ISSUE TITLE
Problems in creating annotated workspaces

### ISSUE THREAD

**Issue by LookMumNoBackup** [eclipse-che/che#18559]
## Summary
We tried to setup a k8s cluster (in AWS) with Eclipse Che as described in official setup documentation. We failed to create workspaces which have user-defined k8s pod annotations (like proposed in this [guide](https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#allowing-users-to-define-workspace-deployment-labels-and-annotations_configuring-a-workspace-using-a-devfile) )

Is someone who is able to use this feature already? Can someone confirm that this feature is working and creating k8s pod annotations as specified?

## Relevant information
Dear Che Developer Team,

we are currently trying to setup an Eclipse Che installation using AWS and the EKS service which provides k8s clusters. We were able to setup the system so far that we can create workspaces and write some HalloWorld examples (in Python) in the browser-ide.

Eclipse Che had been setup according to following [instruction ](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-aws/#installing-che-on-kubernetes-using-the-chectl-command_installing-che-on-aws)

Our next step was to try out adding some workspace deployment labels using the factory concept of Eclipse Che. We need this feature in our company to be able to derive certain AWS specific roles from this pod annotations. In detail we want to set IAM roles using [kube2iam](https://github.com/jtblin/kube2iam) and need this feature for this 

The issue we are facing now is, that after trying out the [instruction](https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#allowing-users-to-define-workspace-deployment-labels-and-annotations_configuring-a-workspace-using-a-devfile) we were not able to create workspaces with any specific labels.

The [pull](https://github.com/eclipse/che-dashboard/pull/103) which was merged on 26. Oct 2020 should provide this feature, yet after some hours of try and error we were not able to reproduce the results from the official guide.

We would be really happy to get information if the label feature is working within Che environments created by chectl found in master branch. If yes and we are doing something wrong we would happy to hear suggestions what could be done on our side to find out the root cause of this problem.

Kind regard
Daniil 

Further information:
OS version: Linux SMP Debian 4.9.240-2 x86_64 GNU/Linux
chectl version: 7.22.2 linux-x64 node-v10.23.0
Kubernetes version: 1.18
AWS Platform Version: eks.3
Cluster components: 3 x EC2-Nodes (t3.large)

**Comment by skabashnyuk** [comment]
@B166ER-2 thanks for this report. Can you provide more information about your environment (please follow bug report), the way how to reproduce it. Factory link example is welcomed.

**Comment by skabashnyuk** [comment]
closing in favor of https://github.com/eclipse/che/issues/18560
