### ISSUE TITLE
Configure locale in a docker container

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1856]
**Description:**
 It is impossible to build svn plugin without properly configured locale and following error is appeared
$ svn --no-auth-cache --non-interactive --trust-server-cert copy A/B/lambda A/B/E/lambda
svn: warning: cannot set LC_CTYPE locale, svn: warning: environment variable LANG is en_US.UTF-8, svn: warning: please check that your locale name is correct
To configure locale is enough to add in Dockerfile

**Che version:**  
4.0.0

**Additional information:**
![svn](https://cloud.githubusercontent.com/assets/8051404/16945440/c2acfdb4-4dad-11e6-8c44-ba7c6ca3ad79.png)

**Comment by ghost** [comment]
https://github.com/codenvy/dockerfiles/commit/339f7e992680295f6e7215b9e4881956ef8cbf2a this should fix it. @AndreyChizhikov please confirm

**Comment by ghost** [comment]
@ddementieva can you perform the same for all base images and rebuild them on DockerHub?

**Comment by tolusha** [comment]
Are there any svn options to fix such error or it is kind of requirements?
@eivantsov if user start container for his own recipe then it won't help.

**Comment by ghost** [comment]
@tolusha locale generation is a must for a lot of software to function properly.

**Comment by tolusha** [comment]
Ok then. I won't insist.

**Comment by ddementieva** [comment]
@eivantsov SVN commands are executed without any warnings in the Terminal and from the CMD widget:
![cmd-widget](https://cloud.githubusercontent.com/assets/6860395/17333441/17153c4e-58db-11e6-8e0b-ea622cc8fa0a.png)

![terminal](https://cloud.githubusercontent.com/assets/6860395/17333445/1d0031d6-58db-11e6-8031-72e1560f9720.png)

Warnings appear only when using `Subversion > Status`.

**Comment by JamesDrummond** [comment]
@eivantsov Provide status label.
