### ISSUE TITLE
Depending on che flavor, use the the right image puller image for the deployment as part of che-operator

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18569]
Based on discussions in eclipse/che-operator#541, we should choose the correct image puller image based on Che flavor. this can be done via an additional field in the ConfigMap, or by injecting an environment variable into the deployment.

It is not 100% clear why we can not use the upstream UBI base image / also some related discussion - https://github.com/eclipse/che/issues/17742

**Comment by gattytto** [comment]
@ibuziuk could there be a imagePullerImage attribute in the che crd and the che-image-puller-crd to customize this value?

**Comment by ibuziuk** [comment]
@gattytto there is a separate issue for supporting image puller in chectl - https://github.com/eclipse/che/issues/18570
Also, we are going to close this issue since currently we do not plan to support `cheFlavour` in image puller and leave it as is as a community supported component
