### ISSUE TITLE
[chectl] Adding image puller support

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18570]
### Is your task related to a problem? Please describe.
image puller was integrated into operatorhub installation flow as part of https://github.com/eclipse/che/issues/18133

For the feature parity need to add the image-puller support to `chectl` CLI

**Comment by tolusha** [comment]
What does it actually mean?

**Comment by gattytto** [comment]
may this issue be related to https://github.com/eclipse/che/issues/18569 ?

**Comment by tomgeorge** [comment]
Right now, if you were to run `chectl` and pass in a `CheCluster` CR that has `imagePuller.enabled` set to true, it will fail.  Ideally, `chectl` should take care of this for the user.

**Comment by tolusha** [comment]
@tomgeorge 
sorry, I didn't get ^(

**Comment by tolusha** [comment]
@ibuziuk 
Is it still relevant ?

**Comment by tolusha** [comment]
I am closing this issue since chectl provides `--che-operator-cr-patch-yaml` flag to customize `CheCluster` CR
