### ISSUE TITLE
[che-docs] config properties without inline doc has wrong description

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18572]
### Describe the bug

Documentation of configuration options generated from `che.properties` does not handle correctly properties without inline docs.

See: https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/
and find `CHE_SERVER_SECURE__EXPOSER_JWTPROXY_MEMORY__LIMIT`. This property does not have a inline doc in `che.properties` https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L610 but it's description looks like taken from last property that had one.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2631

**Comment by sparkoo** [comment]
@xbaran4 is working on it
