### ISSUE TITLE
[che-docs] "Calculating Che resource requirements" is outdated

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18573]
### Describe the bug

https://www.eclipse.org/che/docs/che-7/administration-guide/calculating-che-resource-requirements/ page is outdated. We should review this page and make it up to date.

I didn't read the whole page carefully, so these are just issues I saw on first go. Feel free to add more:

 - Table 1. ControllerServices
   - [ ] Che-server and dashboard are splitted into 2 pods
   - [ ] Missing che-gateway
   - [ ] wrong default resource values
 - [ ] A workspace example has wrong values thus final calculation is wrong

### Expected behavior

Page should be up to date.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2578
