### ISSUE TITLE
Rename project doesn't work

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1857]
**Reproduction Steps:**
1. Create or open any project
2. Try to rename it.

**Expected behavior:**
Project renamed.
**Observed behavior:**
Project didn't rename.

**Che version:**  
4.5.0

**Additional information:**
For more information see video:
https://drive.google.com/file/d/0B9-nTKmolEaZTDJlcVVCMXN0ZTg/view

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
