### ISSUE TITLE
Fix the Dashboard next tab title

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18581]
### Is your task related to a problem? Please describe.
Currently, dashboard next browser tab has title: New-dashboard.
On the existing Dashboard it's `Project(Product) Name | Tab name`, like `Eclipse Che | Get Started`.
It should be the same on Dashboard Next

**Comment by parvathyvr** [comment]
I agree that instead of showing 'New-dashboard', it would be good to show  'the product name| the tab the user is in' as the title of the browser tab -similar to how we show in the existing dashboard!It gives more context to the user.
