### ISSUE TITLE
Where to find Dockerfile of che-python provided by default in che

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#18588]
In the first version of eclipse che, we created a custom docker image `eclipse/ubuntu_python` provided by Eclipse.

We are upgrading our components and we would know where to find the Docker file of this image `quay.io/eclipse/che-python-3.7:nightly`. Is the source open ? 

Thanks in advance.

**Comment by benoitf** [comment]
Hello,

quay.io/eclipse/che-python-3.7:nightly is extending python:3.7.4-slim by adding 'anyuid, permission issues stuff, user id, etc'

Source definition is there
https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/base_images#L16

**Comment by KOSSOKO** [comment]
@benoitf, thanks for the answer. We would like to allow our scientists users with our stack based on your default image to install components. But it is blocked. For example with jq

```
bash-5.0 /projects/toto $ apt-get install jq
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
bash-5.0 /projects/toto $ 
```
How could we remove this limitation ?

**Comment by benoitf** [comment]
@KOSSOKO 
hello, yes with underlying runtime, such as OpenShift, we don't have root access to install something in the container (and even with root access it would not be persisted across workspace restart or if you share the workspace definition with someone else.

You should build your own images:
Either you can do inheritance and then inherit from a python image or something else and add all required tools inside or you can add other containers bringing the tooling you need. (like a container with only jq tool inside)

**Comment by KOSSOKO** [comment]
@benoitf i tried to build my own image base on python (the official one), but during start it crashes, because I don't have what you said ` 'anyuid, permission issues stuff, user id, etc'`. 
I extended then `FROM quay.io/eclipse/che-python-3.7:nightly` but still face the same issue. And with your version, I can't install conda, Gdal, even Git.

In our use case it is not a problem if during restart we loose installed components.
Some components are installed by default, and others must be installed by the scientist when needed.
Here our dockerfile:

```
#FROM eclipse/ubuntu_python
FROM quay.io/eclipse/che-python-3.7:nightly
#FROM python:3.7

LABEL maintainer="teddy.kossoko@capgemini.com"
LABEL version="1.0"
LABEL description="Docker file based on ubuntu for eclipse-che workspaces for Biomass project"

USER root

RUN apt-get update \
 && apt-get install -y sudo

RUN adduser --disabled-password --gecos '' docker
RUN adduser docker sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

#USER docker

# this is where I was running into problems with the other approaches
RUN sudo apt-get update

#RUN apt update && apt install sudo && \
#    adduser maapuser && \
#    usermod -aG sudo maapuser

#USER root

RUN python --version
#RUN  chmod 777 /etc/apt/sources.list
RUN  sudo apt-get update
RUN  sudo apt-get clean
# Installation of pip, gdal, python3, matplotlib, doxyen
# installation of scikit-learn, pandas, geopandas, fiona,  shapely

RUN  pip3 install --upgrade pip

#RUN  sudo apt-get clean

RUN   apt-get install -y  --no-install-recommends  rsync software-properties-common python3-lxml python3-pip python3-dev gdal-bin libgdal-dev octave && \
     #apt-get install -y software-properties-common python-software-properties python3-lxml python3-pip &&\
      pip3 install scipy && \
      pip3 install matplotlib && \
      pip3 install property && \
      pip install pillow && \
      pip install -U scikit-learn && \
      pip install pandas && \
      pip install --user fiona && \
      pip install Shapely && \
      pip install opencv-python && \
      pip install octave_kernel && \
      apt-get -y install doxygen  && \
      apt-get -y install jq && \
      pip3 install --upgrade pip && \
      add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
      pip install requests

#RUN   sudo pip install conda

     # git clone https://github.com/geopandas/geopandas.git && \
     # cd geopandas && \
     # pip install .


# installation of GDL
RUN  apt -y install gnudatalanguage

# install gdal and matplotlib with CONDA
#RUN conda install -y gdal matplotlib

#RUN  pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`

# We add the script folder and the zip file to be able to unzip the structure of the project
COPY initTemplate.sh /usr/bmap/initTemplate.sh
COPY initCredentials.sh /usr/bmap/initCredentials.sh
COPY Project_template.zip /usr/bmap/Project_template.zip
COPY shareAlgorithm.sh /usr/bmap/shareAlgorithm.sh
COPY .gitlab-ci.yml /usr/bmap/.gitlab-ci.yml


# We add the RestClient file
COPY RestClient.py /usr/bmap/RestClient.py
COPY quicklook_raster.py /usr/bmap/quicklook_raster.py
COPY ingestData.py /usr/bmap/ingestData.py
COPY ingestData.sh /usr/bmap/ingestData.sh
COPY OWSLib /usr/modules/OWSLib
COPY maap-s3.sh /usr/bmap/maap-s3.sh

RUN  chmod +x /usr/modules/OWSLib
RUN  chmod +x /usr/bmap/initTemplate.sh
RUN  chmod +x /usr/bmap/shareAlgorithm.sh
RUN  chmod +x /usr/bmap/ingestData.sh
RUN  chmod +x /usr/bmap/maap-s3.sh
 

ENV PATH="/usr/bmap/:${PATH}"
ENV PYTHONPATH="/usr/bmap/:${PYTHONPATH}"
ENV PATH="/usr/modules/:${PATH}"
ENV PYTHONPATH="/usr/modules/:${PYTHONPATH}"

USER user

#EXPOSE 8080
```

**Comment by benoitf** [comment]
in you Dockerfile you don't need to install sudo and use sudo commands as inside the image you're a root user when you specify `USER root`

> I extended then FROM quay.io/eclipse/che-python-3.7:nightly but still face the same issue. And with your version, I can't install conda, Gdal, even Git.

Running your Dockerfile and it seems that conda fails with 
```
 unable to execute 'gcc': No such file or directory
```
so you've to install these dependencies but it's not related to che.


last line should be `USER 1001`

**Comment by KOSSOKO** [comment]
@benoitf , I succeed building the stack, but still have the root issue. For example, we have a custom script that have to create files in the user workspace to store data. During the touch, we got `operation not permitted`.

Please how could we remove this limitation ? It is very blocking for us. We succeed with the first version of che two years ago, but with the new stack, it is impossible.

**Comment by KOSSOKO** [comment]
@benoitf please, how could even with inheritance strategy (see ou dockerfile) to activate root access so our users can install plugin from their workspace even if it is ephemeral ?

**Comment by KOSSOKO** [comment]
@benoitf , we tried a lot of ways to activate root in order to install component without success. We tried this dockerfile provided by NASA,but works only for che 6, not with 7

```
FROM continuumio/miniconda3:4.7.12

RUN mkdir /projects
WORKDIR /projects
RUN sed -i -e 's/\/root/\/projects/g' /etc/passwd

WORKDIR /root

RUN conda install gdal
RUN conda install -c conda-forge Cython
RUN conda install -c conda-forge h5py
RUN conda install -c conda-forge numba

#RUN conda install -c conda-forge/label/cf202003 pygeos
#RUN conda install -c conda-forge pyproj
#RUN conda install -c conda-forge rasterio
#RUN conda install -c conda-forge scipy
#RUN conda install -c conda-forge pandas

# install maap-py library
...
```
We tried tons of solutions without success. 
Could we have access to `quay.io/eclipse/che-python-3.7` dockerfile ? It is extremely important for us to activate this root user to install components

**Comment by KOSSOKO** [comment]
the solution is simple. If you are on kubernetes, just change these line value by  0
```
  // run as root
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP     = "0"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER = "0"
```
