### ISSUE TITLE
 Che docs devfile is broken

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#18580]
### Describe the bug
It is not possible to start a workspace form [che-docs](https://github.com/eclipse/che-docs) repository [devfile](https://github.com/eclipse/che-docs/blob/master/devfile.yaml)

### Che version
- nightly
- latest

### Steps to reproduce
1. Open Che dashboard
2. Go to `Get Started` tab
3. Switch to `Custom Workspace`
4. Insert `https://github.com/eclipse/che-docs` into devfile url field
5. Create and try to start the workspace

### Expected behavior
It is possible to start a workspace by providing docs repository link while creating workspace from Che dasbboard

### Runtime
- Openshift (hosted Che)
- Minikube

### Screenshots
![Screenshot from 2020-12-09 17-17-11](https://user-images.githubusercontent.com/15607393/101739896-da98fd00-3ad0-11eb-8497-2f6a631555a3.png)

### Installation method
chectl

### Environment
- Hosted Che
- Minikube locally

### Eclipse Che Logs
Che server logs has no errors

### Additional context
Che server shows that workspace is started, but Theia fails to connect to Che server (at least it seems so because of yellow status bar).
When look at workspace details, there is a warning about deprecated plugins.

**Comment by themr0c** [comment]
I can't reproduce. Workspace is starting properly:
![Screenshot from 2020-12-10 11-20-54](https://user-images.githubusercontent.com/243761/101759426-e0dfa700-3ad9-11eb-8772-65e7beb01cd0.png)
![Screenshot from 2020-12-10 11-15-29](https://user-images.githubusercontent.com/243761/101759429-e1783d80-3ad9-11eb-83e7-6e5a31f72981.png)

**Comment by themr0c** [comment]
Oh I see: https://github.com/eclipse/che-plugin-registry/tree/7.20.x/v3/plugins vs. master.

So we have to ask to get back these plugins in che-plugin-registry:

* joaompinto/vscode-asciidoctor 
*  testthedocs/vale

**Comment by benoitf** [comment]
these plug-ins are ther
https://pr-check-755-alpine-che-plugin-registry.surge.sh/v3/plugins/joaompinto/asciidoctor-vscode/

**Comment by themr0c** [comment]
Is anyone else able to reproduce the issue on a development version of Che?

**Comment by benoitf** [comment]
![image](https://user-images.githubusercontent.com/436777/101762714-0ff81780-3ade-11eb-8e47-a9f27cd0c8bb.png)


works as expected on my side

**Comment by themr0c** [comment]
@mmorhun can you have another try today?

**Comment by mmorhun** [comment]
Still reproducible for me:
![start-error](https://user-images.githubusercontent.com/15607393/101773621-b69be280-3af5-11eb-81b9-aa5d18c4d6d8.gif)

**Comment by themr0c** [comment]
Could it be that the plugin is broken, not the devfile?

Devfile contains following, which looks absolutely legit: 

```  - id: ms-vscode/vscode-github-pullrequest/latest
    type: chePlugin
```

**Comment by mmorhun** [comment]
@themr0c I don't know on what side the root problem is, but I have the same issue when I open provided by you factory. Before I used the devfile from the `che-docs` repository. But if I create a workspace, say, from go-land standard devfile - everything works as expected.

**Comment by boczkowska** [comment]
Docs team Jira issue: https://issues.redhat.com/browse/RHDEVDOCS-2669

**Comment by rkratky** [comment]
@themr0c, @mmorhun, has there been any development in this regard?

**Comment by themr0c** [comment]
It's broken in another place:  

```
Unable to start workspace. Error when trying to start the workspace: Plugins installation process failed. Error: Plugin brokering process for workspace workspacejo62edkah1flmztc failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://codeready-codeready-workspaces-operator.apps.sandbox.x8i5.p1.openshiftapps.com/plugin-registry/v3/plugins/errata-ai/vale-server/latest/meta.yaml': Downloading https://codeready-codeready-workspaces-operator.apps.sandbox.x8i5.p1.openshiftapps.com/plugin-registry/v3/plugins/errata-ai/vale-server/latest/meta.yaml failed. Status code 404. Response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL was not found on this server.</p> </body></html> 
```

See:Originally posted by @ibuziuk in https://github.com/eclipse/che-docs/pull/1866#discussion_r581209951_

**Comment by ericwill** [comment]
This is a CRW specific issue, as we are missing the plugins in the CRW plugin registry. Adding them to the CRW registry will solve the problem.
