### ISSUE TITLE
[image-puller] Reduce default CPU requests and limits

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18591]
### Is your enhancement related to a problem? Please describe.
Currently, default CPU requests and limits are pretty high `0.05` and `0.2` per image:

https://github.com/che-incubator/kubernetes-image-puller/commit/2f33aef63766353852a29df649973ff171c4f84d

This could result in a pretty high CPU consumption depending on the number of images e.g.

![image](https://user-images.githubusercontent.com/1461122/101777874-5e63e100-3af3-11eb-94fd-f3b0102e5da7.png)

### Describe the solution you'd like
Profile and reduce CPU limits/requests

### Describe alternatives you've considered
N/A

### Additional context
The open question is - should we specify both requests and limits, or only requests:

```
Limits for memory are useful if you know how much memory your workload uses and can plan your limit to +10-20% of its peak use.

Limits for CPU for soft-tenancy pods are probably not going to be helpful unless you’re approaching very dense setups (> 10 pods / core) - you’ll waste more CPU throttling than you save.  And cpu limits definitely increase tail latencies for most non-predictable workloads (ie almost all request driven use cases) in a way that will result in a worse overall application environment for most users most of the time (because of how limits are sliced).  At lower pods per core you are almost certainly trading a false security for a worse quality of service for the apps you are trying to run.
```

**Comment by tomgeorge** [comment]
In my testing I've been able to set `cachingCPULimit` to `.1` and it doesn't kill/crash any of the containers.  Also it looks like overall CPU usage for those daemonset pods is pretty low.

**Comment by ibuziuk** [comment]
@tomgeorge can we also set it by default on the image-puller end? default `CACHING_CPU_REQUEST` is 50 millicores as I recall

**Comment by ibuziuk** [comment]
I'm not sure if we need to set the limit though..
