### ISSUE TITLE
Wrong symbols in the message console after git merge

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1859]
**Reproduction Steps:**
Perform git merge operation in some project.

**Observed behavior:**
The message in the 'Consoles' has html tags after git merge operation.

**Che version:**         4.3.0
**Chrome browser:** ver.50

**Additional information:**
![git_console_msg](https://cloud.githubusercontent.com/assets/8051404/16947479/ff2a7104-4db7-11e6-9f3e-945fac7c815a.png)

**Comment by JamesDrummond** [comment]
@riuvshin Provide status label.
