### ISSUE TITLE
generated PRs for plugin registry should remove all but the latest plugins (instead of including multiple copies of machine-exec and theia)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18596]
### Is your enhancement related to a problem? Please describe.

Today, the generated PRs from the plugin registry's make-release.sh script ADD new plugins to the .x and master branches.

* https://github.com/eclipse/che-plugin-registry/pull/660
* https://github.com/eclipse/che-plugin-registry/pull/705
and 
* https://github.com/eclipse/che-plugin-registry/pull/729
etc.

### Describe the solution you'd like

But since we've decided to keep only a single version (latest), the PRs should:

* add the new plugins
* purge the old ones

We can also take this opportunity (once a week for the .z and .0 releases) to purge old plugins that might have crept in accidentally, by scripting the logic that only ONE plugin (the one stored in latest.txt) should be kept.

**Comment by benoitf** [comment]
If we're fast on implementing meta.yaml generation from che-editors file it'll just be a matter of updating che-editors.yaml

**Comment by nickboldt** [comment]
I'm guessing this has slipped to 7.24

**Comment by nickboldt** [comment]
slipped to 7.25, and done thanks to @ericwill
