### ISSUE TITLE
Dashboard Next landing page should depend on the number of workspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18609]
### Describe the bug
Dashboard next opens Get Started tab on Get Started Page, but it should depend on the workspace number + way how user opens tab:
1. User opens Dashboard there are no existing workspaces: user gets Get Started tab on Get Started Page.
2. User opens Dashboard and there is a workspace: user gets Workspaces page opened.
3. User clicks on `Add workspace` on Workspaces: Create Custom Workspace tab is opened on Get Started Page.

**Comment by tsmaeder** [comment]
@sleshchenko sounds like a feature request to me. Care to explain why this is indeed a bug?

**Comment by sleshchenko** [comment]
Because it's basic functionality that already present on Dashboard but is missing for Dashboard Next. But changing it to an enhancement does not change anything, so I'm OK with it.
