### ISSUE TITLE
Unable to install chectl with next channel

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18604]
### Describe the bug
Missing binaries of current chectl next
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

```
$  docker run --rm -it centos
[root@7af9b0135a93 /]# bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
environment: line 2: which: command not found
ERROR: Missing redirect link from the download link https://che-incubator.github.io/chectl/download-link/next-linux-x64. Content found is '''
```
there are no binaries there https://github.com/che-incubator/chectl/releases/tag/20201211150429

### Expected behavior
Able to install

**Comment by benoitf** [comment]
I make blocker as it may block all QE jobs using chectl next

**Comment by tolusha** [comment]
I've deleted the release tag. It should work.

**Comment by benoitf** [comment]
Thanks
