### ISSUE TITLE
Typescript plugin 1.49.3 fails to run typescript language server

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#18605]
### Describe the bug
The typescript language service crashes immediately when using v 1.49.3 (currently "latest") of the typescript plugin. Che-theia version is "next".

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Open a self-hosting workspace.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
       chectl server:deploy -p docker-desktop
       chectl/0.0.20201210-next.0af053a win32-x64 node-v10.23.0
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by tsmaeder** [comment]
The failure happens immediately when starting up the language server. This looks a lot like the original failure we had with the nexe'd custom-built nodejs. @benoitf can you confirm that the current plugin host executable is using a version of the node executable that can run "child_process.fork" correctly?

**Comment by benoitf** [comment]
for che-theia:next yes:
https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile#L1

![image](https://user-images.githubusercontent.com/436777/101927698-0e5d4b00-3bd5-11eb-95e6-2ae64fef45a3.png)

**Comment by benoitf** [comment]
it's also tested there: https://github.com/che-dockerfiles/che-custom-nodejs-deasync/blob/master/test/main.js

**Comment by benoitf** [comment]
I just did a new check (I already checked yesterday evening before approving) and it's working on my side
![image](https://user-images.githubusercontent.com/436777/101930348-52058400-3bd8-11eb-9e09-fc4e9c0509c7.png)
![image](https://user-images.githubusercontent.com/436777/101930458-73ff0680-3bd8-11eb-8d6d-7b07b6f5ab70.png)


https://che.openshift.io/f/=?url=https://gist.githubusercontent.com/benoitf/aea539a20400e5370d2a89bdd0ff0261/raw/9cbf48ac9f85e1fa6eb704ada01e9add17673bfb/devfile-typescript.yaml

**Comment by tsmaeder** [comment]
@benoitf the gist uses images from some PR check: the question is whether the images used in che-theia:next are the same.

**Comment by benoitf** [comment]
> @benoitf the gist uses images from some PR check: the question is whether the images used in che-theia:next are the same.

@tsmaeder it is using the same images definition
Because in the meta.yaml it's referencing `quay.io/eclipse/che-theia:next` and `quay.io/eclipse/che-theia-endpoint-runtime-binary:next`

**Comment by tsmaeder** [comment]
@benoitf using the gist gives me
```
Pulling image "quay.io/eclipse/che-plugin-sidecar:node-cefcc0c"

Failed to pull image "quay.io/eclipse/che-plugin-sidecar:node-cefcc0c": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/eclipse/che-plugin-sidecar:node-cefcc0c not found: manifest unknown: manifest unknown

Error: Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "quay.io/eclipse/che-plugin-sidecar:node-cefcc0c": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/eclipse/che-plugin-sidecar:node-cefcc0c not found: manifest unknown: manifest unknown', 'workspacesnimbxscgmwzvyoz.che-workspace-pod-756789cdbf-w5fjp'"
```

**Comment by benoitf** [comment]
I think I did not copy the latest update of the gist in the PR check, I've updated
http://che.openshift.io/f?url=https://che.openshift.io/f/url=?https://gist.githubusercontent.com/benoitf/aea539a20400e5370d2a89bdd0ff0261/raw/62089d1905bb5fe2944f0dfbe8a17eb18a3ab48f/devfile-typescript.yaml

**Comment by tsmaeder** [comment]
One thing that is sure is that it's not a problem with the fork call: the tsserver starts and exists after processing at least some requests

**Comment by benoitf** [comment]
is it an out of memory error ? I think I had my workspace running for a long time and processing all the requests ?

**Comment by tsmaeder** [comment]
There are two things which were strange:
1. The "plugins" page was offering a plugin called `che-incubator/typescript/1.49.3`. That is not the case anymore this morning
2. Yes, it seems there is a memory problem: upping the memory to 1G seems to fix the problem for the angular example.

**Comment by tsmaeder** [comment]
Looks like the memory limit got lost when moving to che-theia-plugins.yaml

**Comment by benoitf** [comment]
@tsmaeder ok to close the issue ?
