### ISSUE TITLE
It's impossible to move the package

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1860]
**Reproduction Steps:**
1. Create any java project
2. Create two packages in the project.
3. Try to move one package to another by using 'Refactoring'->'Move' command

**Observed behavior:**
The package is impossible to move

**Che version:**  
Version :4.5.0-RC1-SNAPSHOT
Revision :82bf213a3949ee5e
Build Time :2016-07-15 17:35:32

**Additional information:**
![move](https://cloud.githubusercontent.com/assets/8051404/16947663/060ec456-4db9-11e6-904a-156f7306b304.png)

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
