### ISSUE TITLE
Add an ability to hide navigation bar

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#18614]
### Is your enhancement related to a problem? Please describe.
When user opens the workspace based on the JetBrains product it is not possible to hide navigation bar.

### Describe the solution you'd like
Modify noVNC html by adding the script that will allow to interact with the dashboard and hide the navigation bar.

### Describe alternatives you've considered
N/A

### Additional context
Request came from Eclipse Che (Google Chat) channel.

**Comment by azatsarynnyy** [comment]
Not relevant anymore with the new dashboard and its hamburger button.
