### ISSUE TITLE
Multi cluster support

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18617]
### Is your enhancement related to a problem? Please describe.

The next Che online service will be the one hosted by Red Hat Developer Sandbox. That service uses a vanilla CodeReady Workspace instance (Eclipse Che distributed by Red Hat).

The service is currently on Beta and runs on a single OpenShift cluster. To be able to scale we will soon need to provision users among multiple clusters.

### Describe the solution you'd like

Use one central Che server that based on the user sends the workspace creation request to the right Kubernetes cluster. That should probably be done in the context of Che using the DevWorkspace operator to avoid doing the work twice.

### Describe alternatives you've considered

A short term alternative would be to deploy one Che/CRW instance per Kubernetes cluster and deploy a central proxy to route that will be responsible to route the requests to the right Che/CRW instance. That assumes that an external service provides the cluster where a given user is provisioned.

# Implementation
 - [x] [Spike] Intro in Multi cluster support  https://github.com/eclipse/che/issues/18711

**Comment by sparkoo** [comment]
- Is single user forever bound to one cluster for her workspaces and Che server is acting as a load-balancer here?
 - Is Che server responsible to create and maintain these User <> Cluster bounds?

**Comment by l0rd** [comment]
> * Is single user forever bound to one cluster for her workspaces and Che server is acting as a load-balancer here?
 
No. There are use cases where workspaces of a same user need to be scheduled on different clusters. For example, a european user's workspace will be scheduled in the european cluster but, if he travels to north america, he will expect his workspaces to be scheduled in the north american cluster.

> * Is Che server responsible to create and maintain these User <> Cluster bounds?

The criteria to find the most appropriate cluster for a user (european or north american for example) is out of the scope of this issue. For this issue we should assume that a distinct service associates one user to one particular cluster and, that this association can change between the creation of two workspaces.

**Comment by l0rd** [comment]
cc @alexeykazakov @pdaverh
