### ISSUE TITLE
Internationalization of che: che-docs as first step

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#18613]
To start the efforts in che internationalization, che-docs seems like a good first step, not only to translate docs contents but to address the outdated parts.

Can we have a translation team?

**Comment by themr0c** [comment]
IMHO, the UI strings in the app would be a much better first step.

**Comment by themr0c** [comment]
This wiki page gives an overview of the internalization project of the Antora based Fedora documentation: https://fedoraproject.org/wiki/User:Jibecfed/fedoradoc-antora-localization It is fairly complex for a first step.

**Comment by boczkowska** [comment]
Docs team Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2648

**Comment by themr0c** [comment]
@l0rd what are the plans for i18n? From the documentation team perspective, starting with the documentation appears to be a bad idea: the content is currently much too volatile.

**Comment by l0rd** [comment]
@gattytto maintaining internationalization of docs requires a huge effort that we are not able to sustain at the moment. At every Che release (every 3 weeks) documentation is updated significantly (new articles are added and multiple existing ones are updated) and we don't have the bandwidth to maintain i18n properly. 

On the other end, working on the UI i18n (both CLI and GUI), is something that would be easier to maintain as messages don't get updated so often. We should start from that and we have an [issue for the CLI
](https://github.com/eclipse/che/issues/16032) although we haven't planned any work yet.

I am closing this issues as, at present, we wouldn't be able to maintain documentation i18n.
