### ISSUE TITLE
Automate code coverage reporting

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18626]
### Is your task related to a problem? Please describe.
Automate code coverage reporting for the following repositories:
-  https://github.com/eclipse/che-operator
- https://github.com/eclipse/che-machine-exec
- https://github.com/che-incubator/chectl

### Additional context
https://github.com/eclipse/che/issues/18621

**Comment by azatsarynnyy** [comment]
I'm setting P2, the same as for the related epic. Feel free to reprioritize it if needed.
