### ISSUE TITLE
Use Oomph to create development environment in Eclipse for authoring Che extensions / assemblies (from Yatta)

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#1862]
For users, which already use the default Eclipse installer, it would be great to have an Oomph setup model instead of the Yatta profile

As I think that Yatta is based on a Oomph profile anways, so probbaly it is easy to publish that, too.

**Comment by TylerJewell** [comment]
@JonasHelming - with a couple PRs that are about to be merged, we will be moving the default (and really the only) way to install Che to be `docker run eclipse/che start`. There are a variety of reasons that this is beneficial.

I am not that familiar with Oomph - but does its installer allow for this type of execution?  If so, then I think it would still be appropriate.  We can ask the Yatta guys to publish their profile.

**Comment by JonasHelming** [comment]
I am not sure, whether I understand that correctly, I am talking about how to set up an Eclipse IDE to work on Che and/or extensions.
Do you plan to provide a docker image with a preconfigured eclipse IDE?
If so, that would also be fine...

**Comment by TylerJewell** [comment]
I was implying something different.  Ok, I understand what you mean now.  This is about using Oomph to automate setting up a development environment for authoring che extensions / assemblies.

**Comment by JonasHelming** [comment]
exactly

**Comment by bmicklea** [comment]
@zenobios is this something that you can help with?

**Comment by JonasHelming** [comment]
Another reason would be to be able to select the branch to be checked out

**Comment by zenobios** [comment]
Profiles uses Oomph under the hood. Everything you can do with Oomph, you can do with Profiles as well. Additionally, Profiles supports the team aspect and sharing and installing is more straight forward compared to Oomph. Having said that, imho it makes no sense to maintain two possibilities to setup the Eclipse Che development environment.

If choosing the branch to checkout is a requirement, we can just add that to the profile.

**Comment by zenobios** [comment]
We added the possibility to choose the branch to check out. During installation process, a dialog will ask for the 'Eclipse Che Branch' to checkout (default: master).

**Comment by bmicklea** [comment]
@zenobios - is this fixed?  Can it be closed?  Just trying to keep the issues clean ;)

**Comment by zenobios** [comment]
From our side this is fixed.

**Comment by bmicklea** [comment]
@slemeur  can you test the fix please?

**Comment by bmicklea** [comment]
Removed milestone and re-labeled to kind/task because this doesn't require changes in the Che repo.
