### ISSUE TITLE
Switch install in cloud docs to use operator

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18622]
### Is your task related to a problem? Please describe.
Our default way to deploy Che is Operators, but Deploy in Cloud docs articles references helm as installer.

### Describe the solution you'd like
Docs suggest operator as an installer for chectl

Documentations changes are pretty simple, just one file after https://github.com/eclipse/che-docs/pull/1740/files is merged but probably it's needed to be tested before switching.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2649

**Comment by themr0c** [comment]
@sleshchenko which cloud installation are you referring to? AWS and Azure?

**Comment by sleshchenko** [comment]
AWS, Azure, GCP
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/ https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-google-cloud-platform/
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-aws/
all of them use --installer=helm
