### ISSUE TITLE
Enable GH action for generating community operator PRs

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18627]
### Is your task related to a problem? Please describe.

Today, to generate community operator PRs, we need to manually run a script using a user who has permission to pull/pushche-operator, and submit a PR from che-incubator/community-operators to https://github.com/operator-framework/community-operators/pulls?q=%22Update+eclipse-che+operator%22+is%3Aopen

Manual steps are here: 

```
./olm/prepare-community-operators-update.sh
```

https://github.com/eclipse/che-release/blob/master/README.md#phase-2---manual-steps

### Describe the solution you'd like

Instead of a manual step, a GH action should be called when a push occurs in the che-operator.

Started working on such a GH action, but it's stuck trying to push the PR:

```
   - Push branch update-eclipse-che-upstream-operator-7.23.0 to https://github.com/che-incubator/community-operators.git
To https://github.com/che-incubator/community-operators.git
 ! [remote rejected]   update-eclipse-che-upstream-operator-7.23.0 -> update-eclipse-che-upstream-operator-7.23.0 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/deploy_image.yaml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/che-incubator/community-operators.git'
```

Log: https://github.com/eclipse/che-operator/runs/1558228150?check_suite_focus=true

Source: https://github.com/eclipse/che-operator/blob/master/.github/workflows/release-community-operator-PRs.yml#L64

### Additional context

See also:

* Move Che release workflow from Centos CI #17857
* Migrate cico che-release script to run in GH action / ubuntu #18576

**Comment by nickboldt** [comment]
The plan Florent and I came up with was:
* GH action in che-operator triggers API call to another action in community-operators and chectl repos, passing in correct che-incub-bot-token
* GH action in community operators (workflow action) is triggered, generates PRs for the updated CSVs
* GH action in chectl (workflow action) is triggered, generates PR for the chectl release
* GH action in chectl (push action, optional workflow too) is triggered when the PR is merged, starting the push to GH releases page

So the big missing pieces are:

* create new bot account for che-incubator-bot
* get the che-incub token and add it to the appropriate repos via api push
* split the current che-operator community PRs action into two repos

**Comment by nickboldt** [comment]
We're done the 2 chectl actions:

* MANUAL GH action in chectl (workflow action) is triggered, generates PR for the chectl release - https://github.com/che-incubator/chectl/actions?query=workflow%3A%22Release+-+create+pull+request+for+upcoming+release%22
* ON_PUSH GH action in chectl (push action, optional workflow too) is triggered when the PR is merged, starting the push to GH releases page - https://github.com/che-incubator/chectl/actions?query=workflow%3A%22Release+-+generate+release+and+push+artifacts+to+github+pages+%28after+PR+approved%29%22

However, the first one should be triggered by API call when operator release is done.

- [ ] Add action to trigger chectl PR when operator release is done

And we still have to split the existing che-operator action into two pieces: che-operator trigger, and community-operators action:

- [ ] ON_PUSH GH action in che-operator triggers API call to another action in community-operators and chectl repos, passing in correct che-incub-bot-token

- [ ] MANUAL GH action in community operators (workflow action) is triggered, generates PRs for the updated CSVs

**Comment by mkuznyetsov** [comment]
Workflows that now triggere release of projects that "depend" on operator:
chectl: https://github.com/eclipse/che-operator/blob/master/.github/workflows/release-chectl.yml
community operator PRs: https://github.com/eclipse/che-operator/blob/master/.github/workflows/release-community-operator-PRs.yml
docs: https://github.com/eclipse/che-operator/blob/master/.github/workflows/release-che-docs.yml
