### ISSUE TITLE
Do you still need the Vert.x docker-file contribution?

### ISSUE THREAD

**Issue by tsegismont** [eclipse-che/che#18623]
Hi,

For some time, we (the Vert.x team) have contribute to the `che-dockerfiles` repo by providing updates to the Vert.x recipe.

The last PR sent was https://github.com/eclipse/che-dockerfiles/pull/254 and it's still opened since May.

We have released other Vert.x versions since then and just released a new major, Vert.x 4.0.0.

We would like to know if there is still interest in this repo? Is it still maintained?

Thank you

**Comment by azatsarynnyy** [comment]
Currently, we have all the https://github.com/eclipse/che-devfile-registry for "stacks"
and https://github.com/eclipse/che-plugin-registry/tree/master/sidecars for the sidecars.

I'm not sure if https://github.com/eclipse/che-dockerfiles is something that is currently used in Che 7.

cc @benoitf @ericwill

**Comment by tsegismont** [comment]
@azatsarynnyy thanks for the prompt reply!

Looking at https://github.com/eclipse/che-devfile-registry/blob/0093cdb5c6f77a59ce57e98faa6c7a4590898bad/devfiles/java-web-vertx/devfile.yaml#L5-L10

It seems the Vert.x example is based on https://github.com/openshift-vertx-examples/vertx-http-example, correct?

In this case, as long as we update `https://github.com/openshift-vertx-examples` we should be fine. And we could stop pushing PRs to `che-dockerfiles`.

**Comment by benoitf** [comment]
Hello, yes since che 7, we do not use anymore https://github.com/eclipse/che-dockerfiles repository anymore.

> It seems the Vert.x example is based on https://github.com/openshift-vertx-examples/vertx-http-example, correct?

correct !

**Comment by tsegismont** [comment]
Thank you @azatsarynnyy and @benoitf

**Comment by benoitf** [comment]
@tsegismont also if you think we should use another example we could update the description/etc

**Comment by tsegismont** [comment]
@benoitf this example is fine, it shows a basic Vert.x app with Vert.x Web router. All good
