### ISSUE TITLE
Improve usability and flow for chectl releases

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18628]
### Describe the bug

Today, there are two different "release" actions for releasing a new version of chectl:

* https://github.com/che-incubator/chectl/actions?query=workflow%3ARelease
* https://github.com/che-incubator/chectl/actions?query=workflow%3A%22Create+release+and+push+to+github+pages%22

I suggest we rename these and re-reference them like this, so they're listed alphabetically in the order they run, and grouped by purpose:

* Release - create pull request for upcoming release
* Release - generate release and push artifacts to github pages (after PR approved)

We can then update the che-release readme to refer to these more descriptive names.

**Comment by nickboldt** [comment]
PRs: 

* https://github.com/che-incubator/chectl/pull/1036/files
* https://github.com/eclipse/che-release/pull/15/files

WDYT @flacatus @tolusha @benoitf  ?

**Comment by flacatus** [comment]
+1 from my side
