### ISSUE TITLE
[docs] - bring "Configuring namespace strategies" page up to date

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18625]
### Describe the bug

Revisit and fix issues in "Configuring namespace strategies" page https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-namespace-strategies/

 - [x] Describe configuration with che-operator and Helm

### Additional context

https://issues.redhat.com/browse/RHDEVDOCS-2023

**Comment by azatsarynnyy** [comment]
I'm setting P1 as it has a high priority for downstream. Feel free to reprioritize it if needed.
