### ISSUE TITLE
Automate testing of Single-Host CHE on OpenShift CI

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#18630]
### Is your task related to a problem? Please describe.
* Related to #17789

### Describe the solution you'd like
1. We need to create automation testing on CSB Jenkins to check CHE 'single-host' on OCP
2. E2E tests should be adapted properly considering to differences between 'multi-host' and 'single-host' strategies:
- Running preview of demo application in editor in Happy Path tests
- Getting 'bearer token' of Keycloak 

### Additional context
https://github.com/eclipse/che/issues/18765

**Comment by tolusha** [comment]
FYI:
We testing the following scenarios on che-operator side on every PR:
- deploy Eclipse Che on minikube with single-host mode and gateway exposure strategy
- deploy Eclipse Che on minikube with single-host mode and native exposure strategy
- deploy Eclipse Che on openshift 4.6 with single-host mode
- deploy Eclipse Che on openshift 4.7 with single-host mode

 and workspace creation

**Comment by artaleks9** [comment]
@tolusha, thanks for info.

* We're going to run next E2E UI tests against nightly Che 'single-host' on running workspaces: 
-Happy-path 
-Devfiles tests 
-Git SSH flow

* Che will be deployed on minikube with gateway exposure strategy and on OCP with oauth support.

**Comment by dmytro-ndp** [comment]
I has been already fixed.
