### ISSUE TITLE
Issues with deploying Eclipse Che on docker-desktop and importing certificate into a Firefox browser

### ISSUE THREAD

**Issue by mtsmfm** [eclipse-che/che#18647]
### Describe the bug

I've just followed Adding certificates to Firefox guide but I saw "This is not a certificate authority certificate, so it can’t be imported into the certificate authority list." error

https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-certificates-to-browsers/

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. bash <(curl -sL  https://www.eclipse.org/che/chectl/)
2. chectl dashboard:open
3. Follow Adding certificates to Firefox document

### Expected behavior

Open dashboard without Certificate Error

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:53 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots

![image](https://user-images.githubusercontent.com/1796864/102563570-eb72ef80-411c-11eb-8ada-db6b3e9019be.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context

I've also tried google chrome and it doesn't work.
The doc has two problems in Adding certificates to Google Chrome on Linux or Windows section.

1. Authorities tab does not exist

> 5. At the center of the screen, click Manage certificates and navigate to Authorities tab.

![image](https://user-images.githubusercontent.com/1796864/102563883-a7ccb580-411d-11eb-9d82-c38723111300.png)

It opens Windows OS's certificates setting and there's no Authorities tab

It'll be like this

![](https://support.globalsign.com/application/files/5715/8373/7713/Import_Wizard_Screen-03.PNG)

https://support.globalsign.com/digital-certificates/digital-certificate-installation/install-client-digital-certificate-windows-using-chrome

2. The cert is not marked as valid even I imported ingress fake cert as root authorities

I guess Authorities tab described in step 5 means Trusted Root Certification Authorities tab.
So I exported the cert as p7b from here

![image](https://user-images.githubusercontent.com/1796864/102564501-ec0c8580-411e-11eb-902e-dc6bdb62e3a1.png)

and imported the p7b as Trusted Root Certification Authorities but it's still marked as invalid.

**Comment by gattytto** [comment]
@mtsmfm after che installs it gives you a root CA certificate into a temporary folder (you can export it again using chectl), that one in windows you may need to add it (using MMC windows tool) to BOTH the root certificates folder and the intermediary certificates folder too. Then you add the certificate you obtain from the browser to the personal certificates folder of MMC. then close all browsers and reopen and it should work.

**Comment by mtsmfm** [comment]
@gattytto Which directory can I find root CA certificate?

> you can export it again using chectl

I guess you meant `chectl cacert:export` but it doesn't work

```
$ chectl cacert:export
› Current Kubernetes context: 'docker-desktop'
Self signed certificate secret not found. Is commonly trusted certificate used?
```

**Comment by tolusha** [comment]
@mtsmfm 
It is interesting to know which secret do you have in the `che` namespace 
`kubectl get secret -n che`

**Comment by mtsmfm** [comment]
@tolusha Here's the result

```
$ kubectl get secret -n che
NAME                           TYPE                                  DATA   AGE
che-identity-postgres-secret   Opaque                                1      13h
che-identity-secret            Opaque                                2      13h
che-operator-token-7dc7q       kubernetes.io/service-account-token   3      13h
che-postgres-secret            Opaque                                2      13h
che-tls                        kubernetes.io/tls                     3      13h
che-token-ggds5                kubernetes.io/service-account-token   3      13h
che-workspace-token-764qq      kubernetes.io/service-account-token   3      13h
default-token-vp7xp            kubernetes.io/service-account-token   3      12d
```

**Comment by tolusha** [comment]
`openssl s_client -connect che-che.192.168.50.122.nip.io:443  -showcerts`

**Comment by tolusha** [comment]
Also I would like to inspect operator logs.
Pls grab it with `chectl server:logs` command

**Comment by mtsmfm** [comment]
```
$ openssl s_client -connect che-che.192.168.50.122.nip.io:443 -showcerts
CONNECTED(00000003)
depth=0 O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate
   i:O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate
-----BEGIN CERTIFICATE-----
MIIDcDCCAligAwIBAgIRAJsS58cQrJtTGpO9BosCWh4wDQYJKoZIhvcNAQELBQAw
SzEQMA4GA1UEChMHQWNtZSBDbzE3MDUGA1UEAxMuS3ViZXJuZXRlcyBJbmdyZXNz
IENvbnRyb2xsZXIgRmFrZSBDZXJ0aWZpY2F0ZTAeFw0yMDEyMTgwMDU3MTdaFw0y
MTEyMTgwMDU3MTdaMEsxEDAOBgNVBAoTB0FjbWUgQ28xNzA1BgNVBAMTLkt1YmVy
bmV0ZXMgSW5ncmVzcyBDb250cm9sbGVyIEZha2UgQ2VydGlmaWNhdGUwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+NvQ2EqOFGjGZGkqASEdKHWUDq0/7
18IHUXfEQwPHsuKOTif6cnSVTpdFVk6tbrpV3POVQh+UPy4rkVkouxbV5TGohZv1
BotrsElITorfc2mTKZH7Ja0nLWWl+qirlfKUTR464rvjoMx72Lyb/FSYV9VEsCiK
lo7aPiTKYuHr05XgR0r+IPd01btLiLsi10R/6/1EfPVIBJTXEm7EjZjlDODN1Wvn
OnSAevP0JIqVH0ECRse4JrW0SbzbFOydTmwDk4nMf6ASr8OplxEUlchbKl2vHAun
11x0NyB06FiRNqCWmdOiTdgDJ1aJCsMcX/GYMWE1WOZpQJBSSwPmYtqbAgMBAAGj
TzBNMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMB
Af8EAjAAMBgGA1UdEQQRMA+CDWluZ3Jlc3MubG9jYWwwDQYJKoZIhvcNAQELBQAD
ggEBAD8/4yI2iGbXX0Fe6aF+4Ed7b57SEDsat4NZrw/pPtYMLPKgoNz6n44NNhrC
0upxnNZcAhpdg263mF3AN/GAkWU7hCfENG94ApKB7B+t9spdNxRusWGv2dml3peC
buOXINXpb6kU3xAyVrx/WYwjg8EdrovSbhhEmdUUZ/3/EhpeJXbv3p5/Sti3a7MI
HGGdX1ixIbUF+BG0ZPb9zkz/bziyNSh5DNhWIgM9U/i1ld+VOe44CIUq9yJBGRgE
FvdKLqKoGvoGloQK1xsjkdcoHWkT/2eurjKCqRjYzS2PtNFd/N2G3GbeelTHi2rr
H7gPHZ1mYyra3Df9MAVcZl/3+5Q=
-----END CERTIFICATE-----
---
Server certificate
subject=O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate

issuer=O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1561 bytes and written 414 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6D21E36119C50614CB4770074C08807D675EB33BED33642D2C14D16F461BF939
    Session-ID-ctx:
    Master-Key: 24E51485450C680E3D10739736969C997F4F69EC5115EA496655B7743F7F11D156BD536725969C414C2205448994278F
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
    0000 - 1e 04 ee d0 5b c7 4c ca-0c 22 ea 91 91 01 ff 83   ....[.L.."......
    0010 - ad 61 19 d8 73 b0 ff a6-84 5f 30 99 f4 32 90 94   .a..s...._0..2..
    0020 - af 65 0b 9d aa 21 42 c6-0e ea 9b 2e e5 a2 0b 4f   .e...!B........O
    0030 - b3 fa f6 ac 10 b2 9a 59-b6 d9 58 41 5b 65 9c 72   .......Y..XA[e.r
    0040 - 53 00 ed ea 52 ea 68 47-dd 40 36 8c e2 75 d0 2e   S...R.hG.@6..u..
    0050 - 3d a0 cf b9 ed 2c 3f c8-81 85 f8 e6 12 65 40 fe   =....,?......e@.
    0060 - 97 81 ed c4 a3 c9 9b 52-52 0e 1a a8 28 f8 4b 0f   .......RR...(.K.
    0070 - ac 8a ec c1 c2 1b 79 5e-a1 de 02 29 c7 8c 4e d5   ......y^...)..N.
    0080 - e2 f9 e6 1e 2f 80 3e c7-69 7f 90 9c 7b 50 d9 96   ..../.>.i...{P..
    0090 - 42 ff ad ae 52 ca 03 c1-97 7d 51 c5 51 28 7b 28   B...R....}Q.Q({(
    00a0 - d4 49 0d 7e b4 5a 62 e2-ec f8 cc 89 e6 90 ed 0b   .I.~.Zb.........
    00b0 - 00 9b 10 06 6b f8 36 83-32 81 64 9d de b0 2d 1d   ....k.6.2.d...-.
    00c0 - 82 87 1e c5 19 c2 e3 d5-ae cd bf 8e 02 b2 7b 22   ..............{"

    Start Time: 1608304707
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
```

**Comment by mtsmfm** [comment]
`chectl server:logs`

[che.zip](https://github.com/eclipse/che/files/5716512/che.zip)

**Comment by tolusha** [comment]
I see. self-signed-certificate secret hasn't been created for some reason.
It might happened if `spec.k8s.tlsSecretName` is empty in the custom resource.
Could you check it?
` kubectl get checlusters  eclipse-che -n che -o yaml | grep tlsSecretName`

**Comment by mtsmfm** [comment]
```
$ kubectl get checlusters eclipse-che -n che -o yaml | grep tlsSecretName
          f:tlsSecretName: {}
    tlsSecretName: che-tls
```

**Comment by gattytto** [comment]
@mtsmfm try chectl server:export --help

**Comment by mtsmfm** [comment]
```
$ chectl server:export --help
 ›   Error: command server:export not found
```

**Comment by gattytto** [comment]
my bad, edited

**Comment by mtsmfm** [comment]
```
$ chectl cacert:export --help
Retrieves Eclipse Che self-signed certificate

USAGE
  $ chectl cacert:export

OPTIONS
  -d, --destination=destination    Destination where to store Che self-signed CA certificate.
                                                       If the destination is a file (might not exist), then the certificate will be saved there in PEM format.
                                                       If the destination is a directory, then cheCA.crt file will be created there with Che certificate in PEM format.
                                                       If this option is omitted, then Che certificate will be stored in a user's temporary directory as cheCA.crt.

  -h, --help                       show CLI help

  -n, --chenamespace=chenamespace  [default: che] Kubernetes namespace where Eclipse Che server is supposed to be deployed

  --skip-kubernetes-health-check   Skip Kubernetes health check
```

**Comment by gattytto** [comment]
> @gattytto Which directory can I find both the root certificates and the intermediary certificates?

in windows go to start => run and input "MMC" then click ok. or WIN+R and write mmc + hit enter.
then in MMC: file => add or remove complements. find the certificates complement and bring it to the list on the right side, when asked choose "computer account" from the 3 options. hit ok and there you can see the store for your local pc certs. use the import function to import both CA as root and intermediate and then import the certificate you can export from the browser when going to the dashboard url as Personal certificate.

**Comment by mtsmfm** [comment]
@gattytto /tmp/cheCA.crt is the one you mentioned, right?

**Comment by mtsmfm** [comment]
Still doesn't work.
I tried restarting my machine and I found I can't access che-che.192.168.50.122.nip.io anymore because ipaddr for ingress is changed (probably because of WSL?)

**Comment by mtsmfm** [comment]
I tried:

```
$ rm -rf /tmp/che*
$ chectl server:delete
$ chectl server:deploy --platform=docker-desktop --domain 127.0.0.1.nip.io
```

I noticed `/tmp/cheCA.crt` isn't generated again.

Firefox still shows MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT.
Chrome and Edge still show ERR_CERT_COMMON_NAME_INVALID

**Comment by mtsmfm** [comment]
I think it's because of Subject Alternative Name:

```
$ openssl s_client -connect che-che.127.0.0.1.nip.io:443 </dev/null 2>/dev/null | openssl x509 -noout -text | grep 'Subject Alternative' -A 1
            X509v3 Subject Alternative Name:
                DNS:ingress.local
```

It should be che-che.127.0.0.1.nip.io I think

**Comment by mtsmfm** [comment]
Finally it works.

1. Reset k8s cluster
![image](https://user-images.githubusercontent.com/1796864/102704282-cfa64f80-42bc-11eb-9112-0b529bfa3a5e.png)

2. `chectl server:deploy --platform=docker-desktop --domain 127.0.0.1.nip.io`

`--domain` is needed because ip addr might be changed after restarting
I can see 

> ✔ [ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /tmp/cheCA.crt.

message and /tmp/cheCA.crt is generated.

3. Follow the guide "Adding certificates to Firefox" but import `\\wsl$\tmp\cheCA.crt`, not saved cert

https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-certificates-to-browsers/

I guess we have two problems

1. https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-certificates-to-browsers/ is wrong

According to the doc, we need to export cert from che dashboard and import again but what we actually need is to import generated cheCA.crt as trusted root certification.

2. `chectl server:delete` lacks cleaning up TLS or secret stuff

As I reported https://github.com/eclipse/che/issues/18615, server:deploy via chectl 7.22.2 doesn't work well.
It seems chectl doesn't setup self signed CA well after broken setup.
I tried server:delete and server:deploy with 7.22.2 and 7.23.1 again and again.
So I guess for some reason server:delete doesn't remove something and as a result server:deploy doesn't setup TSL correctly.

**Comment by gnoejuan** [comment]
I was about to create a new issue, but I might have a related problem. 

Clean microk8s install.

microk8s plugins: dns storage ingress (disable ha-cluster)

```
helm install longhorn longhorn/longhorn --namespace longhorn-system --values rancher-values.yaml --create-namespace
kubectl patch storageclass microk8s-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

should be irrelevant. 
```

`chectl server:deploy -a helm -p microk8s --postgres-pvc-storage-class-name=longhorn --workspace-pvc-storage-class-name=longhorn --k8spoderrorrechecktimeout=60000`

![image](https://user-images.githubusercontent.com/4656027/103056331-49129c00-4562-11eb-95f5-8240879b4c07.png)

Imported cert auth into firefox.

`che-che.192.168.1.30.nip.io has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.`

![image](https://user-images.githubusercontent.com/4656027/103056385-70696900-4562-11eb-9aae-5341ec67e823.png)

I notice that both of us have `Kubernetes Ingress Controller Fake Certificate`. 

Previously, successful deployments had an ingress che-ingress.

**Comment by mmorhun** [comment]
There is a [mistake](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/#importing-certificates-to-browsers_che) in docs. It says to obtain certificate directly from browser. But that certificate is server one where we need CA one. In the end it will not work.
The right way is to use `chectl cacert:export` command or fetch it directly form cluster.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2540

**Comment by gnoejuan** [comment]
> The right way is to use `chectl cacert:export` command or fetch it directly form cluster.

Still have an issue. 

![image](https://user-images.githubusercontent.com/4656027/105741099-8a022580-5eff-11eb-9b5b-27876dfb8732.png)

**Comment by mmorhun** [comment]
@gnoejuan looks strange. Especially `Expires on` value, that probably is the reason (the certificate is expired).
