### ISSUE TITLE
Dashboard Next should propose user to restart a workspace in debug mode if it's failed

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18640]
### Is your task related to a problem? Please describe.
Existing Dashboard proposes users to restart a workspace if it's failed to start 
https://www.eclipse.org/che/docs/che-7/end-user-guide/restarting-a-che-workspace-in-debug-mode-after-start-failure/

It's a good way to promote this feature and get more reach logs in the bugs reports. So Dashboard Next should do the same. Currently, it only displays that user is able to check logs without a suggestion to try Verbose mode.
![Screenshot_20201217_140003](https://user-images.githubusercontent.com/5887312/102485420-41d62480-4070-11eb-9e73-f794086be3f5.png)
![Screenshot_20201217_140011](https://user-images.githubusercontent.com/5887312/102485423-43075180-4070-11eb-8663-5698bc9d569f.png)

**Comment by sleshchenko** [comment]
Maybe we should here show the actions list: Download logs, Interrupt start(while it's starting, Restart, Restart in Verbose (after it's failed to start) ?
@ParvathyVR WDYT?

**Comment by parvathyvr** [comment]
Hi @sleshchenko I agree that we should provide the action list to the user as links. 
In the 'generic error scenario' we had defined in this [design doc for loading page](https://docs.google.com/document/d/1wfUBTGd77bo_-C3vA83NM_5kXj5Ya-P_xAtAV3RQrwY/edit?ts=5f183462#heading=h.ar5udxvxuu53),that's what we propose as the point 3 in the structure of the error message
1)Title-explains the summary of the failure.
2)Explanation-details/reason of the error is explained to the user.
3)Action items- 
**Links to possible workarounds-eg:Open in Debug mode.Close a Workspace etc**

**Comment by sleshchenko** [comment]
There is one bug and makes sense to fix it in this issue scope:

Workpace loading is not consistent after workspace startup failure
![Screenshot_20201223_173627](https://user-images.githubusercontent.com/5887312/103013609-1fe41280-4546-11eb-96f2-485b80e3942b.png)
-- Steps to reproduce
1. Start a workspace
2. stop a workspace
3. it's marked a failed
4. open it again with left nav bar
5. workspace loading says it's failed, left nav bar says it's starting (and it's true)
6. go workspaces list and open that starting workspace again. errors from the previous start up are not cleaned up

-- Expected behavior

When open failed workspace - Workspace Loading shows the failure reason but does not restart a workspace automatically, instead it proposes user to restart workspace manually. It's overlapping a bit with 
https://github.com/eclipse/che/issues/18640

+ I believe we should not show interrupted startups as failed.

**Comment by sleshchenko** [comment]
It also makes sense to make Check logs link that will open Logs tab.

**Comment by sleshchenko** [comment]
is implemented in https://github.com/che-incubator/che-dashboard-next/pull/104
