### ISSUE TITLE
che operator nightly bundle check fails for release pr's

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#18644]
### Is your enhancement related to a problem? Please describe.
In the release pull request we are changing `che-operator.yaml`. We set up release tags instead of nightly tag. For example:

https://github.com/eclipse/che-operator/pull/583/files#diff-3cbaaa330e7ffeab27fc2751c0454be7d83bb82914ea948d6d7c09f5029e0e34

But also we have OLM bundle files:

https://github.com/eclipse/che-operator/tree/master/deploy/olm-catalog/eclipse-che-preview-openshift/manifests https://github.com/eclipse/che-operator/tree/master/deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests

Content of these files depends on `operator.yaml`, because these files should be generated using https://github.com/eclipse/che-operator/blob/7.23.x/olm/update-nightly-bundle.sh script(operator-sdk under the hood). In the development flow on every `operator.yaml` change, we should generate and update OLM files too. We have special nightly check for this purpose: https://github.com/eclipse/che-operator/blob/master/.github/workflows/check-nightly-olm-bundle.yaml

For release flow pr's we have an issue: this check fails, because check expected that pr should contains bundle files with changes grabbed from `operator.yaml`. But we can't update these files in the pr. Because it's a wrong to apply to the nightly bundle some release tag, like `7.23.1`. Nightly should be nightly. It should not be mixed with release version.

### Describe the solution you'd like
1. First off all, nightly check should print a `diff` with desired changes for nightly bundle, if developer forget to update. It will be more information for developers.
2. Change release script or github action script to handle this situation.

### Describe alternatives you've considered
Some idea: For release we modify operator.yaml, because chectl will use this file like template. Maybe we should make copy of the operator.yaml file for release, and provide this file for chectl che-operator `template` from another place.Then nightly bundle won't be affected by appearing stable tag in the operator.yaml.

**Comment by tolusha** [comment]
I've found one more bug with this check.
It passed for this commit but actually bundles weren't up to date.
https://github.com/tomgeorge/che-operator/commit/2dda07c9df10bf20c1ce38474112580efb603e0c

**Comment by flacatus** [comment]
@tolusha Here https://github.com/tomgeorge/che-operator/commit/2dda07c9df10bf20c1ce38474112580efb603e0c it is a GH actions bug. 

Taking a look to the workflow file(https://github.com/eclipse/che-operator/actions/runs/487371576/workflow) running in this PR don't take this changes from: https://github.com/eclipse/che-operator/pull/628

**Comment by tolusha** [comment]
@AndrienkoAleksandr 
If you don't mind we will close the issue.
We simply disabled this check for release branches.

**Comment by AndrienkoAleksandr** [comment]
OK +1.
