### ISSUE TITLE
Migrate Theia akamai/cdn setup from cico to GH action

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18645]
### Is your task related to a problem? Please describe.

Process for publishing theia artifacts to the Akamai CDN needs to be migrated to a GH action for both nightly and release. 

For downstream, we use this script:

https://github.com/redhat-developer/codeready-workspaces-theia/blob/crw-2.6-rhel-8/akamai.Jenkinsfile#L25

For upstream, we have 

https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml#L584-589

and these 4 jobs:

![image](https://user-images.githubusercontent.com/227597/102498336-d2e4d580-4047-11eb-93a3-c29a501e51f9.png)

eg.,

```
Pushing CDN files to the Akamai directory...
   Pushing theia_artifacts/che.731a0dd3025723cb46e5.js
```

-- https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-release/63/consoleText

### Describe the solution you'd like

The above jobs should be moved to che-theia GH actions, using the appropriate login/keys.

**Comment by benoitf** [comment]
dup or subtask of https://github.com/eclipse/che/issues/18407 ?

**Comment by benoitf** [comment]
pull request build job is already migrated

**Comment by nickboldt** [comment]
subtask, I guess. wanted to make sure we capture the need for akamai setup & process for getting the credentials, which I've now gotten from Radim. TLDR is you can export credentials from jenkins. I've got the akamai settings in a file here:

https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/56/diffs#diff-content-c30d2fd458bf7dd8474e3fea7efc46ffa6942acc
