### ISSUE TITLE
HappyPath tests are failed for Che-Theia with bad GITHUB_TOKEN

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18659]
### Describe the bug

The HappyPath tests started failing today morning on Che-Theia PRs with the following error:
`10:03:01 Step 10/39 : ADD https://${GITHUB_TOKEN}:x-oauth-basic@api.github.com/repos/${THEIA_GITHUB_REPO}/git/refs/heads/master /tmp/branch_info.json
10:03:02 ADD failed: failed to GET https://****:x-oauth-basic@api.github.com/repos/eclipse-theia/theia/git/refs/heads/master with status 401 Unauthorized: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}`

It looks like there's something wrong with `GITHUB_TOKEN` environment variable.

Here are a couple of examples of the failed jobs:
- https://github.com/eclipse/che-theia/pull/946#issuecomment-747934341
- https://github.com/eclipse/che-theia/pull/778#issuecomment-747944060

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
I'm marking it `blocker` as it blocks us from merging the Che-Theia PRs.

**Comment by dmytro-ndp** [comment]
Outdated GitHub token have been renewed https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2147/
