### ISSUE TITLE
che-docs: left nav bar is displayed over content

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18660]
### Describe the bug
left nav bar is displayed over content

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/
2. Scroll Down where the description table row appears.
3. Check how it's displayed
![Screenshot_20201218_134958](https://user-images.githubusercontent.com/5887312/102611782-4cf48780-4138-11eb-9d2b-8b78c856ef75.png)
![Screenshot_20201218_135107](https://user-images.githubusercontent.com/5887312/102611783-4e25b480-4138-11eb-8b58-cb71ddcb263d.png)

I can reproduce it on 

Version 87.0.4280.88 (Official Build) (64-bit)
and Firefox 84.0 (64-bit)

**Comment by themr0c** [comment]
oO the problem doesn't exist on a local build oO.

**Comment by themr0c** [comment]
Some CSS are loaded on a local build and not on the published website:

![Screenshot from 2021-01-13 15-25-40](https://user-images.githubusercontent.com/243761/104464847-afb03600-55b3-11eb-911e-c519d77f6d85.png)

**Comment by themr0c** [comment]
Can reproduce on che.openshift.io.

devfile and Jenkinsfile are not using the same container, that doesn't help for consistent behaviour.

**Comment by themr0c** [comment]
This PR make sure the same container is used in devfile, Jenkinsfile, and for local builds:  https://github.com/eclipse/che-docs/pull/1795

Now I can reproduce the issue using Che and on a local environment.

**Comment by boczkowska** [comment]
The progress can be tracked here https://issues.redhat.com/browse/RHDEVDOCS-2506
