### ISSUE TITLE
github pr plugin: fork creation is hanging when creating a pull request

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18664]
### Describe the bug
Using the Github PR plugin to create a new PR, it is proposing to create a fork but is hanging at that point

![Selection_111](https://user-images.githubusercontent.com/650571/102617558-aad59f00-4139-11eb-8c27-55fcddc27609.png)

### Che version

 - [x] 7.22.1

### Steps to reproduce
- Create a new workspace from a github project.
- add the github pr plugin in the devfile
- start/restart the workspace
- allow/signin github
- checkout a new branch
- make changes, commit
- from the github pr panel, create a new PR
- user is invited to create a fork. Accept.
- the popup hangs with the message: `Creating Pull Request: Start publishing branch ...`

### Runtime
   - [x] kubernetes 

### Installation method
   - [x] chectl

### Environment
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by vinokurig** [comment]
Couldn't reproduce the issue:
![video-convert (2)](https://user-images.githubusercontent.com/7668752/104729448-1dd63380-5741-11eb-823e-4edfa2403fe9.gif)

**Comment by sunix** [comment]
@vinokurig try to create a PR where you are not the owner :)

**Comment by sunix** [comment]
@vinokurig I am wondering if the github app we create have enough permissions:

![Uploading image.png…]()

**Comment by vinokurig** [comment]
@sunix 
I don't think that the problem is in permissions, I've authenticated the plugin with hardcoded token which had `repo` permissions and the issue is still reproducible.

**Comment by sunix** [comment]
@vinokurig this is what I have in my `/home/theia/.theia/workspace-storage/.../workspace-state.json`

![Selection_194](https://user-images.githubusercontent.com/650571/106634462-19eb4380-6580-11eb-95e3-d643f065de3f.png)

**Comment by vinokurig** [comment]
depends on https://github.com/eclipse/che/issues/18933
I can't built my custom che-theia image with additional logging to catch the error.

**Comment by ericwill** [comment]
Removed blocked status as the blocker issue has been resolved.

**Comment by sunix** [comment]
I don't have this problem anymore !!!!
Don't know what did the fix but, this is what I have now:

![Selection_202](https://user-images.githubusercontent.com/650571/107370692-997a9480-6ae3-11eb-9bd9-c152a8d2bb99.png)

And then when using the Github PR:

![Selection_201](https://user-images.githubusercontent.com/650571/107370732-a6978380-6ae3-11eb-9c7e-6e3b01d7e452.png)

**Comment by vinokurig** [comment]
@sunix 
> I don't have this problem anymore !!!!

Ok, I'll check it on my side.

**Comment by sunix** [comment]
To test it I created that PR https://github.com/eclipse/che-theia/pull/988

**Comment by vinokurig** [comment]
I still can reproduce it by creating a PR to https://github.com/testmagic-123/test.git

**Comment by sunix** [comment]
I have this now:
![Selection_215](https://user-images.githubusercontent.com/650571/107540402-4c232380-6bc6-11eb-91c1-4c13be4378da.png)

**Comment by sunix** [comment]
when I don't have permission it should try to create a fork.

**Comment by vinokurig** [comment]
I've tried this on the latest version of the GitHub PR plugin an the issue is NOT reproducible there. So updating to a newer version should fix the problem: https://github.com/eclipse/che/issues/18661
