### ISSUE TITLE
Dashboard should show Che-Theia plugins if the editors is Theia only

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18667]
### Is your enhancement related to a problem? Please describe.

Most of the Che plugins published in the registry are not Che plugins: they can only be used with one specific editor: Theia.

The Dashboard shows Theia plugins as if they were Che plugins. 

### Describe the solution you'd like

Don’t show Che Theia plugins among Che Plugins in Che dashboard

### Additional context

This work should be included in the context of [che workspaces that use the DevWorkspace operator](https://github.com/eclipse/che/issues/17307), so that's not for v1 devfiles/plugins.

**Comment by ericwill** [comment]
I believe we've partially solved this based on how the plugins are defined in the registry:
* che-theia plugins go in `che-theia-plugins.yaml`
* Che editors go in `che-editors.yaml`
* All other components go in `che-components.yaml`

**Comment by tsmaeder** [comment]
It's not quite clear what a "che-plugin" is. What are the criteria? What do they consist of?

**Comment by benoitf** [comment]
@tsmaeder to make it simple, a Che Plugin is not tied to an editor and is not an editor itself

**Comment by l0rd** [comment]
With the transition to DevWorkspace Operator we are not showing editors plugins in the dashboard anymore. Those need to be managed from the editor itself. Closing this issue.
