### ISSUE TITLE
HappyPath tests are failed for Che-Theia because of outdated link to chectl binary

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#18665]
### Describe the bug
Happy path tests fail for che-theia PRs with the error:
```
ERROR: Unable to download chectl binary from https://github.com/che-incubator/chectl/releases/download/20201217151304/chectl-linux-x64.tar.gz
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Please see the test report https://github.com/eclipse/che-theia/pull/778#issuecomment-748092668

### Expected behavior

The tests are happy!

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by azatsarynnyy** [comment]
It seems HappyPath tests depend on the non-existing `chectl` version - `20201217151304`.
I don't see such a release on https://github.com/che-incubator/chectl/releases page.

**Comment by azatsarynnyy** [comment]
I'm raising it to `blocker` as it's a mandatory Che-Theia PRs status check.

**Comment by dmytro-ndp** [comment]
@azatsarynnyy Happy path tests are not dealing with direct link to chectl binary, but rather calling install_chectl.sh script which creating the link to download chectl:
```
download_chectl(){
  curl -vsL  https://www.eclipse.org/che/chectl/ > install_chectl.sh
  chmod +x install_chectl.sh
  sudo PATH=$PATH ./install_chectl.sh --channel=${HAPPY_PATH_CHANNEL}
  sudo chmod +x /usr/local/bin/chectl
}
```

At the happy path tests execution time next inbuilt command returned outdated link to chectl binary:
```
curl https://che-incubator.github.io/chectl/download-link/stable-linux-x64
https://github.com/che-incubator/chectl/releases/download/20201217151304/chectl-linux-x64.tar.gz
```

Correct link is:
```
curl https://che-incubator.github.io/chectl/download-link/stable-linux-x64
https://github.com/che-incubator/chectl/releases/download/20201218111626/chectl-linux-x64.tar.gz
```

Recent execution of Happy path tests haven't been suffered from outdated link: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2154/
