### ISSUE TITLE
[Test issue] Quarkus CLI test run native waiting for input

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#18663]
### Describe the bug
Quarkus CLI run native is waiting for input during test run, causing the devfile test to hang and fail with timeout

### Che version

 - [x] latest
 - [ ] nightly
 - [x] other: 7.23.1

### Steps to reproduce
* Run e2e selenium test for Quarkus CLI
* The test will hang at run Native stage

### Expected behavior
* Test inputs a required variable into the terminal window and presses enter

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/16451875/102613474-d608c000-4132-11eb-8a44-604b838d1f13.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) hosted che staging
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
This is a test issue, not a che issue

**Comment by ibuziuk** [comment]
@ScrewTSW is it planned to 7.27?
