### ISSUE TITLE
Devfile creation walkthroughs

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18671]
### Is your enhancement related to a problem? Please describe.

When a workspace is started and there is no Devfile in the project repository, we are not recommending to create one.

### Describe the solution you'd like

We should recommend:

- To use an existing stack (a (parent) devfile from the devfile registry)
- To add container components (select image, endpoint, volumes etc...) 
- To include plugins (if the editor is che-theia or vscode)
- To create and commit devfiles/extensions.json/che-theia-plugins.yaml in the project

Subtasks:

- [x] VS Code [walkthrough extension](https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs)

### Additional context

This work should be included in the context of [che workspaces that use the DevWorkspace operator](https://github.com/eclipse/che/issues/17307), so that's not for v1 devfiles/plugins.

**Comment by l0rd** [comment]
Let's put this one on hold. We may want to use the devfile library that should help generating a Devfile for a given repository.

**Comment by ibuziuk** [comment]
@l0rd @vitaliy-guliy folks, can we close the issue? extension has been published
