### ISSUE TITLE
[operatorhub] Eclipse Che is not available by default on OCP 4.6

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18676]
### Describe the bug
Eclipse Che is not available by default on OCP 4.6

### Che version
N/A

### Steps to reproduce

1. OCP 4.6
2. Click on 'Operator' -> 'OperatorHunb'
3. Type "Eclipse Che":

![image](https://user-images.githubusercontent.com/1461122/102779377-68f46500-4394-11eb-98ee-a04a9ab0561b.png)

### Expected behavior
Eclipse Che operator is available on OCP 4.6

### Runtime
OCP 4.6

### Installation method
Operatorhub

### Additional context

just for the record Eclipse Che is available on OSD 4.5.1 via Operatorhub

**Comment by tolusha** [comment]
![Screenshot from 2020-12-24 11-28-23](https://user-images.githubusercontent.com/1640675/103078789-43a56800-45db-11eb-9e8d-5ba98fdc72e7.png)
![Screenshot from 2020-12-24 11-28-09](https://user-images.githubusercontent.com/1640675/103078794-4607c200-45db-11eb-88e8-fa76576bfe59.png)

**Comment by tolusha** [comment]
Double checked.
It is there.
