### ISSUE TITLE
Dashboard Next: Account details

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18685]
### Is your enhancement related to a problem? Please describe.
On the existing dashboard, we have a read-only account view, which optionally has an edit button that open a tab with keycloak where a user is able to modify account details.

Probably we need the same for Dashboard Next
![Screenshot_20201222_141024](https://user-images.githubusercontent.com/5887312/102887362-77f41980-445f-11eb-8599-f4d0198a357c.png)
![Screenshot_20201222_141028](https://user-images.githubusercontent.com/5887312/102887365-79254680-445f-11eb-8dd6-0d72b85c5e4c.png)

**Comment by parvathyvr** [comment]
Hi @sleshchenko Here is the mock up :point_down: and the [marvel link](https://marvelapp.com/prototype/fj65fh0/screen/76282658) to the Accounts page for Dashboard next.I have kept the Accounts as separate section as we currently have.

![Che - Accounts New](https://user-images.githubusercontent.com/33114242/105699037-c4ce8280-5f2c-11eb-94cc-4ef338793ed0.png)
