### ISSUE TITLE
Switch e2e typescript selenium tests to selenium/standalone-chrome:87.0

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18683]
### Is your task related to a problem? Please describe.
We need to switch e2e typescript selenium tests to use Google Chrome 87, but make sure next issue is not returned https://github.com/eclipse/che/issues/18602

```
FROM selenium/standalone-chrome:87.0
```

https://github.com/eclipse/che/pull/18646/files

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/18696
