### ISSUE TITLE
How to disable che-ctl auto update ? 

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#18680]
We installed chectl 4 months ago and on our kubernetes cluster installed `che 7.18.0`

Today, at 8am we undedploy and redeploy without a problem with this command:
`chectl server:start --platform=k8s --installer=helm --multiuser  --cheimage=quay.io/eclipse/che-server:7.18.0 --domain=${MAAP_DOMAIN} --k8spodwaittimeout=400000 --postgres-pvc-storage-class-name="csi-disk-topology" --workspace-pvc-storage-class-name="csi-disk-topology" --templates=$TEMPLATE_PATH`

at 3pm when we tried and reinstall, we got an error:

```
› Current Kubernetes context: 'INT.config'
 ›   Error: Unexpected arguments: --platform=k8s, --installer=helm, --multiuser, --cheimage=quay.io/eclipse/che-server:7.18.0, --domain=int.esa-maap.org,
 ›   --postgres-pvc-storage-class-name=csi-disk-topology, --workspace-pvc-storage-class-name=csi-disk-topology, --templates=/home/cloud/jenkins-delivery/ict-INT/che7
 ›   See more help with --help
```
We noticed that the chectl version have automatically changed to `chectl/7.23.1 linux-x64 node-v12.20.0`.

How could we disable auto update of chectl ? So we don't have to manage api changes each morning.
Thanks in advance.

**Comment by ibuziuk** [comment]
@tolusha @AndrienkoAleksandr could you please take a look?

**Comment by tolusha** [comment]
chectl is not auto-updated.

**Comment by KOSSOKO** [comment]
@tolusha , so why after 3 months, suddently we can't no longer redeploy ?

**Comment by KOSSOKO** [comment]
whe check the path to the checlt client and noticed that today, a new version was installed and a symbolic link now pointed on `7.23.1`

```
ls -l  /home/cloud/.local/share/chectl/client/
total 0
drwxr-xr-x. 7 cloud cloud 179 Dec 21 09:34 7.22.1
drwxr-xr-x. 7 cloud cloud 179 Dec 21 14:38 7.23.1
drwxrwxr-x. 2 cloud cloud  20 Dec 21 09:34 bin
lrwxrwxrwx. 1 cloud cloud   8 Dec 21 09:34 current -> ./7.23.1

```

**Comment by KOSSOKO** [comment]
With the version 7.23.1 that auto-updates our initial command was deprecated.
So instead of using 

`chectl server:start --platform=k8s --installer=helm --multiuser --cheimage=quay.io/eclipse/che-server:7.18.0 --domain=${MAAP_DOMAIN} --k8spodwaittimeout=400000 --postgres-pvc-storage-class-name="csi-disk-topology" --workspace-pvc-storage-class-name="csi-disk-topology" --templates=$TEMPLATE_PATH`

we change it to 

`chectl server:deploy --platform=k8s --installer=helm --multiuser --cheimage=quay.io/eclipse/che-server:7.18.0 --domain=${MAAP_DOMAIN} --k8spodwaittimeout=400000 --postgres-pvc-storage-class-name="csi-disk-topology" --workspace-pvc-storage-class-name="csi-disk-topology" --templates=$TEMPLATE_PATH`

but prometheus repo is not found. Why Eclipse che want to install prometheus ? And why the repo is not found ? 
How to choose che-ctl version we want to use ? 

We downloaded the `7.18.0` archive of che-ctl, and run `alias chectl=$HOME/chectl/bin/run` but it is not working.
We run then `alias chectl=$HOME/chectl/bin/chectl` and version detected in console is  `7.18.0`  but during `chectl start` it seems that vers `7.23` is used because we still have the same error.

**Comment by KOSSOKO** [comment]
@tolusha, @AndrienkoAleksandr, @ibuziuk   I found in our kubernetes `/home/cloud/.cache/chectl/autoupdate.log` the lines for the auto update:

```
waiting until 2020-12-21T20:10:06.400Z to update
time to update
chectl: Updating CLI...
chectl: Updating CLI from 7.18.0 to 7.23.1... done
chectl: Updating CLI... done
```

**Comment by tolusha** [comment]
@KOSSOKO 
I have to admit that underlying oclif framework has autoupdate functionality [1] 
We have never faced such a problem because we always use the latest version.

https://github.com/oclif/plugin-update/blob/master/src/hooks/init.ts#L35-L48

pls use to disable autoupdate
`export CHECTL_DISABLE_AUTOUPDATE=1`

**Comment by KOSSOKO** [comment]
First base in install script log, we created a script shell to install the version we need : 7.18.0

`
mkdir -p /usr/local/lib
cd /usr/local/lib
rm -rf chectl
rm -rf ~/.local/share/chectl/client
curl -fsSL https://che-incubator.github.io/chectl/download-link/stable-linux-x64
curl -#fSL https://github.com/che-incubator/chectl/releases/download/20200826160252/chectl-linux-x64.tar.gz | tar xz
rm -f /usr/local/bin/chectl || true
rm -f /usr/local/bin/chectl
ln -s /usr/local/lib/chectl/bin/chectl /usr/local/bin/chectl
/usr/local/lib/chectl/bin/node -v > /dev/null 2>&1 || rm /usr/local/lib/chectl/bin/node
`
Then we added 
`export CHECTL_DISABLE_AUTOUPDATE=1` and
`export DISABLE_AUTOUPDATE=1` in our environment file to block update

**Comment by KOSSOKO** [comment]
The auto update broke something related to Prometheus...Even after reinstalling the 7.18, this issue is still there

```
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✖ Updating Helm Chart dependencies
      → Deleting newly downloaded charts, restoring pre-update state
      Deploying Eclipse Che Helm Chart
 ›   Error: Error: Command failed with exit code 1: helm dependencies update --skip-refresh /home/cloud/.cache/chectl/templates/kubernetes/helm/che/
 ›   Error: could not find : chart prometheus not found in https://kubernetes-charts.storage.googleapis.com/
 ›   Saving 7 charts
 ›   Save error occurred:  could not find : chart prometheus not found in https://kubernetes-charts.storage.googleapis.com/
 ›   Deleting newly downloaded charts, restoring pre-update state
 ›   Installation failed, check logs in '/tmp/chectl-logs/1608653654757'
```

**Comment by tolusha** [comment]
This should help
https://github.com/eclipse/che/issues/18673

**Comment by KOSSOKO** [comment]
@tolusha  Thanks a lot everything works fine now. Merry Christmas to you and all Che team. See you on 2021 for new issues ;) .

**Comment by tolusha** [comment]
You are welcome!
