### ISSUE TITLE
Eclipse Che with docker support

### ISSUE THREAD

**Issue by amoldhondse** [eclipse-che/che#18693]

**Comment by AndrienkoAleksandr** [comment]
Sorry this issue is duplication of https://github.com/eclipse/che/issues/18692 ?

**Comment by amoldhondse** [comment]
click on below link and it gives error 
 **Running Eclipse Che on Kubernetes using Docker Desktop on macOS or Windows.**

**Comment by tolusha** [comment]
Duplicates https://github.com/eclipse/che/issues/18606
