### ISSUE TITLE
Happy path PR check doesn't leave comment with test result at PR page

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18699]
### Describe the bug
Happy path PR check on Eclipse Che and Eclipse Che-Theia repo has stopped posting comments to PR page with test results, e.g.:
- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/4246/
- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2178/

**Comment by AndrienkoAleksandr** [comment]
I set up P2, but fill free to set up higher priority if it's a critical.

**Comment by azatsarynnyy** [comment]
I'd say it's a blocker. As of now, it's impossible to know what's failed and what should be fixed in the PR.

**Comment by dmytro-ndp** [comment]
@azatsarynnyy: there is PR checks section where the status can be seen:
![Screenshot from 2020-12-23 18-48-02](https://user-images.githubusercontent.com/1197777/103020844-dbf70a80-4551-11eb-92f3-699c05d13242.png)

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy: there is PR checks section where the status can be seen:
> ![Screenshot from 2020-12-23 18-48-02](https://user-images.githubusercontent.com/1197777/103020844-dbf70a80-4551-11eb-92f3-699c05d13242.png)
> 
> So, the issue doesn't look as a blocker, IMHO.

Agree, returning P2. Thank you @dmytro-ndp for the clarification.

**Comment by dmytro-ndp** [comment]
@azatsarynnyy: set P1, because for Eclipse Che-Theia comment contains important information like try-URLs to open workspace in hosted che.

**Comment by dmytro-ndp** [comment]
The root cause of issue was problem with **che-bot** account, which had lost permissions.
After permissions have recently been restored, Happy path PR check is now able to leave comment at PR page, e.g. https://github.com/eclipse/che-theia/pull/957#issuecomment-754092724
