### ISSUE TITLE
building che-theia with --skip-tests

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#18690]
## Summary
What is the best way to build che-theia without running the tests? 
I followed the instructions here https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/README.md
From the che-theia root folder I ran 
./build.sh --skip-tests

From the logs I see the tests are still running. 
I see logs like this.
@eclipse-che/theia-generator: Test Suites: 14 passed, 14 total
@eclipse-che/theia-generator: Tests:       57 passed, 57 total

and many more and the whole build takes close to an hour

What is the way to have a build generated without running the tests? I am just trying out a prototype with che-theia and don't really need the tests to run right now

**Comment by AndrienkoAleksandr** [comment]
@azatsarynnyy Could you help?

**Comment by pgirishibm** [comment]
@azatsarynnyy Can you help with this please?  Though i am not blocked with this. but need to get the build running faster.
