### ISSUE TITLE
Enhancement: Che operator supports automated backup and restore of Che server components

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18703]
### Is your task related to a problem? Please describe.
To support level 3 of the operator framework capability levels che-operator should provide the ability to create backups/restore of the Operand.

### Additional context
https://github.com/eclipse/che/issues/18043

### Release Notes Text

Che operator supports automated backup and restore of Che server components. The backup and restore operation can be triggered through Che command line tool `chectl` or by creating a dedicated CustomResource (`CheClusterBackup` and `CheClusterBackup`). Only the backup of Che server components is currently supported: users workspaces objects are not included in backup/restore yet.

**Comment by mmorhun** [comment]
@l0rd should the backup/restore care about content of `/projects` volume of the user's workspaces?

**Comment by l0rd** [comment]
@mmorhun that's a good question. We should probably consider the content of workspaces volumes. But we can delay that to a second step. cc @sympatheticmoose

**Comment by nickboldt** [comment]
Florent had an idea on another issue ( https://github.com/eclipse/che/issues/19291 ) that's worth mentioning here:

> sometimes current images are broken and it's impossible to get back in time.
> Maybe it should be easy to go back in days as well :D like chectl update yesterday / chectl server:deploy

**Comment by l0rd** [comment]
After discussing with @sympatheticmoose we agreed that we can ignore workspaces objects (PV, secrets, configmap) for this first implementation. I have updated [the epic](https://github.com/eclipse/che/issues/19291) to reflect that.

**Comment by themr0c** [comment]
Release notes:https://issues.redhat.com/browse/CRW-1878

**Comment by mmorhun** [comment]
Done

**Comment by MichalMaler** [comment]
https://issues.redhat.com/browse/CRW-1965

**Comment by nickboldt** [comment]
Note that the CRW issue above is for 2.11 as this issue is resolved for milestone 7.33.
