### ISSUE TITLE
Minor: It would be nice to use only one logger in the che-operator - "zap"

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#18701]
### Is your enhancement related to a problem? Please describe.
In the che-operator for now we are using two loggers:  "zap" and "logrus". 

### Describe the solution you'd like
It would be more clear to use only one of them: logger zap. Because the latest operator-sdk recommends this logger.

### Describe alternatives you've considered
-

### Additional context
-

**Comment by tolusha** [comment]
WON'T FIX
