### ISSUE TITLE
Dashboard next does not need its own loader

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18734]
### Describe the bug
As far as I understand after @akurinnoy told me, Dashboard Next shows loader until it receives the event from IDE that it's ready. But:
1. It makes an impression that it takes more time for IDE to be opened in the Dashboard Next.
2. It makes it impossible to open IDE that does not send event (I assume jupyter and Intelij are such)

So, when Dashboard Next opens an IDE in an iframe, it does not need to show its own loading but instead of it should just display what iframe has: loader.js UI and then Theia UI ( that has its own loader as well).

**Comment by akurinnoy** [comment]
> It makes it impossible to open IDE that does not send event (I assume jupyter and Intelij are such)

I missed it previously but figured it now: there is a 1 minute timeout until iframe content is shown if there are no event from iframe. But still an editor may load much faster than that timeout ends, so user have to wait.

**Comment by sleshchenko** [comment]
Is implemented in https://github.com/eclipse/che-dashboard/pull/142
