### ISSUE TITLE
crw-theia build failing due to che-custom-nodejs-deasync:12.18.2 ?

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18735]
### Describe the bug

Job fails to run the theia-endpoint part of the crw-theia build:

```
13:29:48 + cp .Dockerfile .ubi8-dockerfile
13:29:48 + docker build -f .ubi8-dockerfile -t che-theia-endpoint-binary-builder:tmp --target builder . --no-cache --build-arg GITHUB_TOKEN=****
13:29:48 Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
13:29:48 STEP 1: FROM che-custom-nodejs-deasync:12.18.2 AS custom-nodejs
13:29:48 fcb95e1984e1cc865e0bae548bbf48e70161aade44e07e697339a500f07ef5e2
13:29:48 STEP 2: FROM eclipse/che-theia:next AS builder
13:29:48 STEP 3: ARG NEXE_SHA1=0f0869b292f1d7b68ba6e170d628de68a10c009f
13:29:49 fa407492214f2a2d06b98b70cb53b88440d74c7b323ef12c1107e1ebe824aa83
13:29:49 STEP 4: WORKDIR /home/theia
13:29:50 4a42876ca2b920e3a43dfd15203fc7871188baed0a7d2940883cc537af69397a
13:29:50 STEP 5: ENV PATH=${HOME}/.yarn/bin:${PATH}
13:29:51 0433b9d5e3f3c1d06d225899012f6e34d1dd276f4f202ed70d797f9e6ace9d9d
13:29:51 STEP 6: ENV NEXE_FLAGS="--target 'alpine-x64-12' --temp /tmp/nexe-cache"
13:29:51 c3f9c23c48d42503a51e7fb4591208dba2a76e2432ec6027fb4c2c732fa3071b
13:29:51 STEP 7: COPY --from=custom-nodejs /alpine-x64-12 /tmp/nexe-cache/alpine-x64-12
13:29:52 Error: error building at STEP "COPY --from=custom-nodejs /alpine-x64-12 /tmp/nexe-cache/alpine-x64-12": no files found matching "/home/hudson/.local/share/containers/storage/overlay/76e43096a5559ce3ed169ebb2575a51d51caefe8fd9e3f23cff0667e87a0df36/merged/alpine-x64-12": no such file or directory
```
-- https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-sources_2.6/1/console

I wonder if this is a consequence of https://issues.redhat.com/browse/CRW-1215 and the fact that we have different definitions of che-custom-nodejs-deasync image for different arches.

### Che version
 - crw-theia @ crw-2.6-rhel-8, 
 - che-theia @ 7.23.x, 
 - theia @ 4641a298

### Steps to reproduce

1. run a build from https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-sources_2.6/
2. observe console output

**Comment by nickboldt** [comment]
PR https://github.com/redhat-developer/codeready-workspaces-theia/pull/28 merged. 

Building in https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-sources_2.6/2/console to verify. 

NOTE:  must actually check published artifacts in https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-sources_2.6/lastSuccessfulBuild/artifact/crw-theia/dockerfiles/

and if all three builds' artifacts appear there, can also check this job for a new run w/ 3 successful subtasks:

https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-containers_2.6/

**Comment by nickboldt** [comment]
Also noteworthy, the version of image che-custom-nodejs-deasync:12.18.2 vs. the version of node we're using in crw-theia (which is now 12.19.1 as that's what's in ubi latest image).

Should the deasync image also be updated to 12.19.1?

**Comment by nickboldt** [comment]
Merged https://github.com/redhat-developer/codeready-workspaces-theia/pull/28 but same error in build log:

```
13:29:51 STEP 7: COPY --from=custom-nodejs /alpine-x64-12 /tmp/nexe-cache/alpine-x64-12
13:29:52 Error: error building at STEP "COPY --from=custom-nodejs /alpine-x64-12 /tmp/nexe-cache/alpine-x64-12": no files found matching "/home/hudson/.local/share/containers/storage/overlay/76e43096a5559ce3ed169ebb2575a51d51caefe8fd9e3f23cff0667e87a0df36/merged/alpine-x64-12": no such file or directory
```

--- https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-sources_2.6/2/console

**Comment by benoitf** [comment]
@nickboldt there is something that is changing the node version in the build

https://github.com/eclipse/che-theia/blob/c394167d7a533d21eca8e7b0d97f005108b87eb9/dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile#L1

It should be 12.20.0 version of the image that is used as only 12.20.0 version of che-custom-nodejs-deasync contains the expected nexe prebuilt binary

**Comment by nickboldt** [comment]
OK, I've done this:

https://github.com/redhat-developer/codeready-workspaces-theia/commit/018499146b1312370409434c084bab9f4c8ee18b

So that we can build the async image using 12.20.0 (alpine) and everything else with 12.19.1 (ubi).

Really, we need to create a rhel.Dockerfile for that async image, since this is Not The Product Way. :(

**Comment by nickboldt** [comment]
Further improvement based on convo w/ Florent today:

https://github.com/redhat-developer/codeready-workspaces-theia/commit/68f00ab6a3a88de8229b1491781b4d410cf14776

Running in:

https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-sources_2.6/3/console

**Comment by nickboldt** [comment]
followup work in https://issues.redhat.com/browse/CRW-1215
