### ISSUE TITLE
Staging changes appears to take a long time to complete 

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#18743]
### Describe the bug
Making a simple change to a readme and staging that change appears to take a long time to complete (up to 3 minutes). You can actually still commit the change whilst the action is showing as "in progress" i.e. the animation under the menu, but it gives the impression to the user that the process has not completed. Checking the output from git shows repeated output of:
```
> git show --textconv :README.md
> git ls-files --stage -- /projects/nodejs-mongodb-sample/README.md
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
> git ls-files --stage -- /projects/nodejs-mongodb-sample/README.md
> git show --textconv :README.md
> git ls-files --stage -- /projects/nodejs-mongodb-sample/README.md
> git show --textconv :README.md
> git ls-files --stage -- /projects/nodejs-mongodb-sample/README.md
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
> git ls-files --stage -- /projects/nodejs-mongodb-sample/README.md
> git ls-files --stage -- /projects/nodejs-mongodb-sample/README.md
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
> git cat-file -s ca7b1bdf96b9257478ba6af20c8403e8821f1e52
```

Note: I have also seen this happen just from saving the change, but is more consistent with staging the change.

### Che version
Experienced in both che.openshift.io and CRW 2.5.1

### Steps to reproduce

1. Create workspace with git project as source
2. Optionally show git output to verify issue
3. Make a simple change to the readme, i.e. new line with single word addition
4. Save the file
5. In the source control view stage the change

### Screenshots
This recording (edited) shows the issue where it took just under 3 minutes to 'complete':

https://user-images.githubusercontent.com/19860021/103764342-2f1d9280-5013-11eb-8e50-439fd75adc80.mp4

**Comment by l0rd** [comment]
@mmorhun we should set an area label when doing triage. If we do not do that issues won't be considered for next priorizaiton / planning.
