### ISSUE TITLE
Missing options in source control: git

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#18742]
### Describe the bug
I believe within the view for source control there should be additional options which would include the ... menu for more actions such as pushing changes which have been committed. As shown in this screenshot from VS Code:

<img width="440" alt="Screenshot 2021-01-06 at 11 13 21" src="https://user-images.githubusercontent.com/19860021/103762807-d3eaa080-5010-11eb-8042-28f8bbc91844.png">

However, in both che.openshift.io and CRW 2.5.1 there are no options within the view other than to switch from tree to list, as shown below:

<img width="754" alt="Screenshot 2021-01-06 at 09 27 11" src="https://user-images.githubusercontent.com/19860021/103763004-1f04b380-5011-11eb-8f46-5dd560e32313.png">

This makes it difficult for the user to perform actions such as push through the UI.

**Comment by ericwill** [comment]
Are you using a specific devfile, or can this be reproduced from any of the default stacks from the `Getting Started` page?

**Comment by sympatheticmoose** [comment]
@ericwill this was based on the nodejs-mongo default, but with a swapped project as the source. I haven't tried with others to be fair.

**Comment by ericwill** [comment]
I was just able to reproduce it on che.openshift.io, using just the default nodejs-mongodb stack. We'll look into it.

**Comment by vinokurig** [comment]
Should be fixed by https://github.com/eclipse-theia/theia/pull/8996

**Comment by vinokurig** [comment]
Fixed by https://github.com/eclipse-theia/theia/pull/8996

**Comment by nickboldt** [comment]
Fixed in 7.26 (CRW 2.7). Downstream issue: https://issues.redhat.com/browse/CRW-1581
