### ISSUE TITLE
Ensure branches are deleted upon merge in all che-* repositories

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18748]
### Is your enhancement related to a problem? Please describe.
On che repository, when PR are merged, branches are deleted but it may not be the case on all the che-* repositories.

### Describe the solution you'd like
Ensure that branches are automatically removed when the associated PR is merged

**Comment by nickboldt** [comment]
As this is an admin task for GH administrator, and prod team does not have admin rights on all che repos, I've assigned this to the devex team.

**Comment by benoitf** [comment]
hoping prod team would have created the BZ ticket, but here it is https://bugs.eclipse.org/bugs/show_bug.cgi?id=576475
