### ISSUE TITLE
How to setup a running tomcat service (as a chePlugin) for dev workspace

### ISSUE THREAD

**Issue by han5** [eclipse-che/che#18756]
## Summary
Really confused, cannot find a path forward.
Please provide recipe or devfile for how typical setup of a container, like tomcat7, as a chePlugin and have it run the war build ?

This is vanilla classic java need (albeit legacy monolithic app work) to be able to build the project and run the war in an app server like tomcat.  But there are needs like the tomcat server.xml, maybe ssl setup, and the context setup, and how to receive/deploy the war file for the tomcat docker image. 

The port mapping of theia to tomcat7/dockerimage is another thing which is confusing.  

I've searched for docs, and tried several options, and still cannot figure out how to set this up correctly.  

With this information, we can update the docs for the hordes of java spring devs out there (yikes!).

**Comment by ericwill** [comment]
Hello,

Have you taken a look at the pre-built [java-spring devfile](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-web-spring/devfile.yaml)? We have one that is provided as part of Che `Getting Started` stacks.

**Comment by han5** [comment]
yes i have, and that is not really a good or solid example.  

what we want to accomplish is to have a container for our tools like a tomcat7 (not an embedded mvn driven spring boot) and cassandra or mysql etc. 

it should be possible to setup a container holding a tomcat server and run it, stop it, deploy to it etc.  not this embedded project driven solution but externalized tools in other containers that can be shared via dockerimage or git clone etc.

**Comment by han5** [comment]
alright i see there is a mongo db setup, wondering where those credentials come from
