### ISSUE TITLE
Update the vale plugin to the latest supported version and fix the sidecar image

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18755]
### Is your task related to a problem? Please describe.
The [vale extension we are currently using in Che](https://github.com/testthedocs/vscode-vale) is deprecated in favour of an [officially supported one](https://github.com/errata-ai/vale-vscode).

### Describe the solution you'd like
Replace the vale extension in the che-plugin-registry with the latest supported one.

### Describe alternatives you've considered
N/A

**Comment by ericwill** [comment]
It seems also that the vale sidecar is broken.
![image](https://user-images.githubusercontent.com/6290632/104338564-a5fbd500-54c4-11eb-86a6-6e093be5dc97.png)

**Comment by tsmaeder** [comment]
Strangely, the official vale image on docker hub uses Alpine. 🤷

**Comment by tsmaeder** [comment]
@ericwill the suggested extension does not specify a license _at all_. I don't think we can use it currently.

**Comment by ericwill** [comment]
> @ericwill the suggested extension does not specify a license _at all_. I don't think we can use it currently.

I don't think it's an issue, we have closed source plugins in the registry already and it's fine.

**Comment by tsmaeder** [comment]
This is not a question of closed vs. open source: we (and also our users) have no legal basis for using that extension. I don't think that is proper.

**Comment by tsmaeder** [comment]
I filed https://github.com/errata-ai/vale-vscode/issues/45

**Comment by benoitf** [comment]
https://github.com/errata-ai/vale-vscode/blob/master/package.json#L13

**Comment by tsmaeder** [comment]
Ah...so that makes the intention clear, but I don't think just referencing MIT in the package.json is proper: https://en.wikipedia.org/wiki/MIT_License#License_terms 
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by tsmaeder** [comment]
They added a proper license file.
