### ISSUE TITLE
Add support for Mermaid preview and syntax highlighting VS Code extensions

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#18750]
### Is your enhancement related to a problem? Please describe.
Che does not yet provide a good way to render graphs, an area where Mermaid excels.  

### Describe the solution you'd like
Provide the Bierner markdown plugin [1] as a Che plugin.
[1] https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid

### Describe alternatives you've considered
We've tried to adapt it ourselves, but were not successful.  We are hoping the Che plugin experts will better understand what's necessary.

### Additional context
Thank you for considering this Enhancement request!

**Comment by RickJWagner** [comment]
Please note that the Mermaid plugin is very popular for VSCode, over 130,000 installs.  Hopefully Che users will find it useful, too.

**Comment by ericwill** [comment]
Fixed by eclipse/che-plugin-registry#856
