### ISSUE TITLE
Docs on "Building Extensions" is outdated

### ISSUE THREAD

**Issue by helderm** [eclipse-che/che#1875]
The documentation on [Building Extensions](https://eclipse-che.readme.io/docs/create-and-build-extensions) page is somewhat outdated and confusing. While going through it, this is what I so far noticed:
1. The `master` branch at [che-ide-extension](https://github.com/che-samples/che-ide-extension) sample has the code for the client side of the plugin, while the docs explain how to build a server side plugin. I guess that the code that the correct source code is [che-server-extension](https://github.com/che-samples/che-server-extension)
2. In [Link Extension to Assembly](https://eclipse-che.readme.io/docs/create-and-build-extensions#section-link-extension-to-assembly), there is no `assembly-machine-war` in version `4.4.0`. I would guess that the POM changes should be done at `assembly-wsagent-war` and `assembly-wsagent-server`, judging by the instructions at [Build Che Assembly with your Extension](https://eclipse-che.readme.io/docs/create-and-build-extensions#section-build-che-assembly-with-your-extension)
3. The generated docs at `assemblies/assembly-main/target/{eclipse-version}/{eclipse-version}/plugins/examples/`, there is a mention of docs at [Developing Extensions](https://eclipse-che.readme.io/docs/developing-extensions) which is not linked anywhere in the left menu of Che docs main page. However, it does seems that they are a more complete set of examples than  [Building Extensions](https://eclipse-che.readme.io/docs/create-and-build-extensions) .

**Comment by slemeur** [comment]
Thanks @helderm we will give a look asap.

**Comment by helderm** [comment]
1. Using the `che-server-extension` sample, I could not get it to work as specified at [Test your Extension](https://eclipse-che.readme.io/docs/create-and-build-extensions#section-test-your-extension). I built it, declared as dependency both in `assembly-wsagent-war` and `assembly-wsagent-server`, built all aseemblies again, run `che.sh`, tried curling `http://localhost:8080/wsagent/ext/hello/myservice` and voila, 404. Is this URL still valid?

**Comment by JamesDrummond** [comment]
@slemeur Do you know who will be assigned to this?

**Comment by slemeur** [comment]
@vparfonov, @ddementieva and myself.

Issue "2." has been updated in the docs.

We need to:
- update the plugin sample #1882 and make it part of the default sample extensions provided. ( @vparfonov )
- update the documentation to walk through the steps to build che with the code of that sample ( @slemeur @ddementieva )
- update the link in the generated docs ( @vparfonov )

This issue is linked to #2077 .

**Comment by TylerJewell** [comment]
Closing this out as we are replacing this with github.com/eclipse/che-archetypes.  This will come with a docs restructuring that solves these problems.
