### ISSUE TITLE
Folder Compare plugin deployed in che  has  Loss of function

### ISSUE THREAD

**Issue by whafra** [eclipse-che/che#18752]
the enviroment (air-gap ):
OS :ubuntu 18.04.5 LTS
kubernetes version:v1.18.6
eclipse-che version: 7.21.0
install cmd:
chectl server:start --installer=operator --platform k8s --multiuser ....

I have deplyed the eclipse-che successfully ,of course i build the  offline devfile registry and plugin registry.
Well,  my team need the function of folder-compare . I choose the plugin moshfeu/vscode-compare-folders/v0.20.0
(github :https://github.com/moshfeu/vscode-compare-folders )
The plugin could compare the files and folders .However ,after i deploy it in che,I found something changed .
I can not find the folder-compare shorcut or right-click. 
Anybody tried this plugin in che? or Is there some other userful folder-compare plugin in che?
thank you .

**Comment by ericwill** [comment]
> Anybody tried this plugin in che? or Is there some other userful folder-compare plugin in che?

I don't think anyone has tried this particular extension in Che, no. We can consider adding it. How did you add the plugin to Che?

**Comment by whafra** [comment]
@ericwill
thanks  for your concern.   The following is my steps:
1) create the neccesary files . 
I create the directory moshfeu/vscode-compare-folders  in  the  devfile_dir/v3/plugins.
And in moshfeu/vscode-compare-folders ,I create the file named latest.txt  and folder named   v0.20.0 which contains a file named meta.yaml.
2) build the offline images . refer to https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-in-a-restricted-environment/#building-an-offline-plug-in-registry-image_che.

Then ,i can see the plugins in the che. and i install the plugin and use it .
