### ISSUE TITLE
Support README.adoc for readme to automatically open on workspace start

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#18753]
### Is your enhancement related to a problem? Please describe.

when a workspace is starting, a readme is automatically opened. In the case of https://github.com/apache/camel-k , it is opening a readme.md inside helm subbfolder instead of the root one called REAME.adoc

### Describe the solution you'd like

Open readme.adoc files on workspace start

**Comment by azatsarynnyy** [comment]
Since it's handled by [`Welcome Plug-in`](https://github.com/eclipse/che-theia/blob/ff88e4e124a78c17274a5bac1f85a6e6336dc989/plugins/welcome-plugin/src/welcome-plugin.ts#L55-L75), I'm moving it to `area/plugins`.
