### ISSUE TITLE
[chectl]- Not able to to deploy Eclipse Che using operator installer

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#18754]
### Describe the bug

Chectl fails to install when operator installer.
Installation logs:

[flacatusu@localhost Downloads]$ chectl server:deploy --installer=operator --platform=minikube
› Current Kubernetes context: 'minikube'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Check Kubernetes version: Found v1.20.0.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.49.2.nip.io.
    ✔ Checking minikube version... 1.16.0
    ↓ Check if cluster accessible [skipped]
  ✔ Following Eclipse Che logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che server logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
    ✔ Start following namespace events...done
  ❯ 🏃‍  Running the Eclipse Che operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Create ServiceAccount che-operator in namespace che...done.
    ✔ Create Role che-operator in namespace che...done.
    ✔ Create ClusterRole che-che-operator...done.
    ✔ Create ClusterRole che-che-namespace-editor...done.
    ✔ Create ClusterRoleBinding che-che-operator-namespace-editor...done.
    ✔ Create RoleBinding che-operator in namespace che...done.
    ✔ Create ClusterRoleBinding che-che-operator...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...done.
    ❯ Operator pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✖ Starting...failed
        → Failed to start a pod, reason: Completed
      Prepare Eclipse Che cluster CR
 ›   Error: Error: Failed to start a pod, reason: Completed
 ›   Command server:deploy failed. Error log: /home/flacatusu/.cache/chectl/error.log

EVENTS:
````
eclipse-che   2m7s        Normal    Pulled                    pod/che-operator-5c7fb97d6c-z5xfx                Successfully pulled image "quay.io/eclipse/che-operator:nightly" in 178.53657ms
eclipse-che   28s         Warning   Unhealthy                 pod/che-operator-5c7fb97d6c-z5xfx                Readiness probe failed: Get "http://172.17.0.3:6789/healthz": dial tcp 172.17.0.3:6789: connect: connection refused
eclipse-che   22s         Warning   Unhealthy                 pod/che-operator-5c7fb97d6c-z5xfx                Liveness probe failed: Get "http://172.17.0.3:6789/readyz": dial tcp 172.17.0.3:6789: connect: connection refused
eclipse-che   22s         Normal    Killing                   pod/che-operator-5c7fb97d6c-z5xfx                Container che-operator failed liveness probe, will be restarted
````
### Che version

 - [ ] latest
 - [X ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by l0rd** [comment]
I confirm I have seen the same problem this morning. That's a blocker.

**Comment by mmorhun** [comment]
I cannot reproduce this issue as of now

**Comment by tolusha** [comment]
Latest chectl contains incorrect templates

**Comment by artaleks9** [comment]
Confirming of issue - Che nightly job is failed from 07.01.2021 to this day by this reason:
```
6:34:07  [23:34:06] Downloading images...done [completed]
06:34:07  [23:34:06] Starting [started]
06:35:59  [23:35:54] Starting...failed [title changed]
06:35:59  [23:35:54] Starting...failed [failed]
06:35:59  [23:35:54] → Failed to start a pod, reason: Completed
06:35:59  [23:35:54] Operator pod bootstrap [failed]
06:35:59  [23:35:54] → Failed to start a pod, reason: Completed
06:35:59  [23:35:54] 🏃‍  Running the Eclipse Che operator [failed]
06:35:59  [23:35:54] → Failed to start a pod, reason: Completed
06:35:59   ›   Error: Error: Failed to start a pod, reason: Completed
06:35:59   ›   Command server:deploy failed. Error log: 
```
```
NAME                           READY   STATUS    RESTARTS   AGE
che-operator-97c57d75c-hqv7x   0/1     Running   1          2m2s
```
```
LAST SEEN   TYPE      REASON              OBJECT                              MESSAGE
2m1s        Normal    Scheduled           pod/che-operator-97c57d75c-hqv7x    Successfully assigned eclipse-che/che-operator-97c57d75c-hqv7x to minikube
2m          Normal    Pulling             pod/che-operator-97c57d75c-hqv7x    Pulling image "quay.io/eclipse/che-operator:nightly"
118s        Normal    Pulled              pod/che-operator-97c57d75c-hqv7x    Successfully pulled image "quay.io/eclipse/che-operator:nightly"
118s        Normal    Created             pod/che-operator-97c57d75c-hqv7x    Created container che-operator
117s        Normal    Started             pod/che-operator-97c57d75c-hqv7x    Started container che-operator
12s         Warning   Unhealthy           pod/che-operator-97c57d75c-hqv7x    Readiness probe failed: Get http://172.17.0.6:6789/healthz: dial tcp 172.17.0.6:6789: connect: connection refused
10s         Warning   Unhealthy           pod/che-operator-97c57d75c-hqv7x    Liveness probe failed: Get http://172.17.0.6:6789/readyz: dial tcp 172.17.0.6:6789: connect: connection refused
2m1s        Normal    SuccessfulCreate    replicaset/che-operator-97c57d75c   Created pod: che-operator-97c57d75c-hqv7x
2m1s        Normal    ScalingReplicaSet   deployment/che-operator             Scaled up replica set che-operator-97c57d75c to 1
```

**Comment by artaleks9** [comment]
It also blocks launch PR-check.

**Comment by mmorhun** [comment]
> Latest chectl contains incorrect templates

I tried with master branch, not with the latest release

**Comment by RenDhark-star** [comment]
Works now

**Comment by l0rd** [comment]
👍 goo job, it works for me too.
