### ISSUE TITLE
[new UD] Delete running workspaces on Workspaces List page

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#18761]
### Is your task related to a problem? Please describe.

[This PR]() changes the default behaviour of deleting a single workspace and bulk deleting workspaces. That was done in order to deliver PR sooner and keep code clearer. 

Deleting workspaces fails if their status is not STOPPED or ERROR. User has to manually stop the workspace and then try to delete it again. The result of failure is shown in an alert warning.

Delete a single running workspace:

<img width="627" alt="Screenshot 2021-01-08 at 15 56 52" src="https://user-images.githubusercontent.com/16220722/104023424-55396300-51ca-11eb-9f9c-5061090b61d6.png">

Bulk delete running workspaces:

<img width="627" alt="Screenshot 2021-01-08 at 15 57 29" src="https://user-images.githubusercontent.com/16220722/104023682-acd7ce80-51ca-11eb-9540-3453496b30df.png">

### Describe the solution you'd like

Leave it as is and improve the UI if necessary.

### Describe alternatives you've considered

Implement deletion of running workspace on Dashboard site.

### Additional context

Since it was implemented on old dashboard, user considers it as regression:

#### Describe the bug
Dashboard displays a warning when a user removes a running workspace from the main dashboard page.
The message is: `Unable to delete workspace 'workspace_name'. Only STOPPED workspace can be deleted.`

I think there is some inconsistency. After clicking on `Delete` button `dashboard` asks a user to confirm the operation. Then the warning is displayed that it's impossible. 
If it's impossible to remove a running workspace - why the confirmation dialog is displayed? Should the warning be displayed instead?

Moreover, a user is able to delete the same running workspace without any problems  using `Actions` => `Delete Workspace` menu.

#### Steps to reproduce

1. Go to the main `dashboard` page and try to remove a running workspace using `Delete` button. 
2. Confirm removing the workspace
3. See a warning
4. Try to remove the workspace using `Actions` => `Delete Workspace` menu.
5. Compare the behavior of the first and the second way of a running workspace removing .

Please see a short video below.

#### Expected behavior

I think it should be possible to remove a running workspace from the main page of the dashboard (as it's possible from `Actions` => `Delete Workspace` menu)

![delete_workspace_dashboard](https://user-images.githubusercontent.com/5676062/108098192-c1da3400-708b-11eb-8c70-9d2931c8dab5.gif)

**Comment by sleshchenko** [comment]
@skabashnyuk Do you think it's a good idea to expose [REMOVE_WORKSPACE_AFTER_STOP](https://github.com/eclipse/che/pull/18136/files#diff-ff1714cd9246d40c00ed51f33320d15ba2c788b41edfe66d2966b1aa1ae29e4fR244) via REST API and reuse it on Dashboard side, or it's better to do such sequence of operations on Dashboard side (in the second case such operation won't be finished if you close the tab)?

Or we can just disable remove buttons for RUNNING/STARTING/STOPPING workspaces and force users manually stop workspaces and wait it's done before removing.

@ParvathyVR do you have opinion on that?

**Comment by parvathyvr** [comment]
> @skabashnyuk Do you think it's a good idea to expose [REMOVE_WORKSPACE_AFTER_STOP](https://github.com/eclipse/che/pull/18136/files#diff-ff1714cd9246d40c00ed51f33320d15ba2c788b41edfe66d2966b1aa1ae29e4fR244) via REST API and reuse it on Dashboard side, or it's better to do such sequence of operations on Dashboard side (in the second case such operation won't be finished if you close the tab)?
> 
> Or we can just disable remove buttons for RUNNING/STARTING/STOPPING workspaces and force users manually stop workspaces and wait it's done before removing.
> 
> @parvathyvr do you have opinion on that?

Hi @sleshchenko I like the idea of disabling the option to 'Remove/Delete workspace' for RUNNING/STARTING/STOPPING workspaces and enabling it back only when the workspace gets to a stopped status. CC @skabashnyuk

**Comment by skabashnyuk** [comment]
![image](https://user-images.githubusercontent.com/1614429/104901058-8dd4fb80-5985-11eb-92ae-47f1ca4578d9.png)

**Comment by sleshchenko** [comment]
The issue is created to add an ability on Che Server to async remove non-stopped workspaces https://github.com/eclipse/che/issues/19367
