### ISSUE TITLE
[UD] As an admin, I would like to have a possibility to add information / warning header to the User Dasboard

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18769]
### Describe the solution you'd like
From time to time, Admin needs to communicate some information with the users e.g.:
- scheduled maintenance  
- deprecation / EOL notifications

Admin should have a possibility to configure the header that will be applied to the UD layout.

from the UX perspective It could look similar to the warning we are having for workspace format were not only the text, but also links are supported in the message body:

![image](https://user-images.githubusercontent.com/1461122/104163902-6e732700-53f7-11eb-9af1-e15e58d7cc68.png)

### Describe alternatives you've considered
A possible solution could be configuring a header via `product.json` e.g.:

```
 "header" : {
    "warning": "On date January 04, 2019 07:00 GMT, The service will undergo scheduled maintenance. More information can be found on the <a href="url">website</a>"
  }
```

### Additional context
The proper solution would be having the extended Admin UI for that purpose and allowing admin / super-admin to edit the header via UI without the necessity of redeploying the instance.

**Comment by JPinkney** [comment]
This has been implemented in: https://github.com/eclipse/che-dashboard/pull/143. Unfortunately, we aren't able to render the text as html because I believe it opens us up for xss attack so it's just shown as plaintext

**Comment by ibuziuk** [comment]
@JPinkney thanks, but we also need to refer to some URL similar to what already exist in UD - https://user-images.githubusercontent.com/1461122/104163902-6e732700-53f7-11eb-9af1-e15e58d7cc68.png

Could you please provide this possibility also?

**Comment by sleshchenko** [comment]
Now `<a> tags are allowed and target and href attributes are allowed` @ibuziuk please reopen if it's not sufficient.
