### ISSUE TITLE
A single dogfooding devfile for che-theia

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18763]
### Is your task related to a problem? Please describe.
We have too many devfiles there and there. We want a unique devfile to work on a che-theia plugin or a che-theia extension.

### Describe the solution you'd like
- a single devfile at the root folder of the che-theia repo with a contribute badge to devsandbox
- a didact guide to explain how it works and how to contribute
- the github pr plugin to commit/push and create an PR
- we would remove all the devfiles located in the `devfiles` directory when this is done.

Maybe this tasks could be splitted in several steps:

0. build/test watch
  - started the devfile, you can open and modify any .ts file
  - you could run `yarn test watch current project` command: that would run the test in watch mode of the yarn project you are currently working on
  - you could run `yarn build current project` command: that would build the yarn project you are currently working on

1. run a plugin
  - started the devfile, you can open and modify a ts file of a plugin
  - you could run `test watch` command: that would run the test in watch mode of the plugin you are currently working on
  - you could run `build current yarn project` command: that would build the plugin you are currently working on
  - you could run `run the plugin in che-theia next` command that would run the plugin in a dedicated che-theia:next container.

2. work with extensions (TODO)

**Comment by tsmaeder** [comment]
I have 4 commands in my che-theia devfile:
1. Run back end
2. Debug back end
3. Run plugin container
4. Debug plugin container

Plus two debug configs for the back-end and the plugin container

As for the build setup, I usually do that by hand. `cd <plugin directory> && yarn'. Afterwards I do a `rm -rf che/che-theia/node_modules`. Otherwise the `yarn` in the theia directory usually fails. (https://github.com/eclipse/che-theia/pull/955 should fix that problem, IMO). When rebuilding a theia extension, I usually do a `yarn` in the base directory in order to catch breakage from my changes.
<details>
<summary>my devfile</summary>

```
apiVersion: 1.0.0
metadata:
  name: che-theia-all
components:
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: eclipse/che-theia/next
    memoryLimit: 2Gi
    type: cheEditor
    alias: theia-editor
    env:
      - value: '0'
        name: NODE_TLS_REJECT_UNAUTHORIZED
  - id: vscode/typescript-language-features/latest
    memoryLimit: 1Gi
    type: chePlugin
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          protocol: http
          public: 'true'
        name: theia-dev-flow
        port: 3010
    memoryLimit: 2Gi
    type: dockerimage
    alias: che-dev
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: '--max_old_space_size=1800'
        name: NODE_OPTIONS
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
  - mountSources: true
    memoryLimit: 1Gi
    type: dockerimage
    alias: plugin-host
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
      - value: 'local-dir:///projects/plugins1/'
        name: THEIA_PLUGINS
      - value: /projects/java-11-openjdk
        name: JAVA_HOME
commands:
  - name: Run plugin host
    actions:
      - workdir: /projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node plugin-remote.js
        component: plugin-host
  - name: Debug plugin host
    actions:
      - workdir: /projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node --inspect-brk=8888 plugin-remote.js
        component: plugin-host
  - name: Run back end
    actions:
      - workdir: /projects/theia/examples/assembly
        type: exec
        command: 'yarn run start --hostname=0.0.0.0 --port=3010 --plugins=local-dir:/projects/theia/plugins'
        component: che-dev
  - name: Debug back end
    actions:
      - workdir: /projects/theia/examples/assembly
        type: exec
        command: 'yarn run start --inspect-brk=9999 --hostname=0.0.0.0 --port=3010 --plugins=local-dir:/projects/theia/plugins'
        component: che-dev
  - name: Debug Configs
    actions:
      - referenceContent: |
          {
            "name": "Attach to Plugin Host",
            "type": "node",
            "request": "attach",
            "port": 8888,
            "outFiles": [
                "/projects/theia/**/*.js"
            ]
          }, {
            "name": "Attach to Back End",
            "type": "node",
            "request": "attach",
            "port": 9999,
            "outFiles": [
                "/projects/theia/**/*.js"
            ]
          }
        type: vscode-launch
```

</details>

**Comment by sunix** [comment]
@tsmaeder  you don't clone the projects ? what about che-theia init ?
