### ISSUE TITLE
How should I debug the Eclipse Che core?

### ISSUE THREAD

**Issue by BingxuHong** [eclipse-che/che#1876]
### Dev env:

Che version: [latest]
OS and version: [windows 10]
Docker version: [docker toolbox]
Che install: [Yatta]
### I tried the following steps.
1. Install pre-requirements and download source from Yatta.
2. mvn clean install at \che\assembly.
3. run 'che --debug start' at \che\assembly\assembly-main\target\eclipse-che-4.6.0-SNAPSHOT\eclipse-che-4.6.0-SNAPSHOT\bin.
4. debug remote Java Application in Eclispse IDE.
   ![image](https://cloud.githubusercontent.com/assets/20534093/16986133/013fe704-4ec0-11e6-9eb8-41c1c42070ed.png)

And a problem occurred.. 
![image](https://cloud.githubusercontent.com/assets/20534093/16986208/2e9a397a-4ec0-11e6-8a5a-bcdf86eab99d.png)

I don't know what the problem is and how to fix it.
**Does anyone can tell me what IDE you use for Eclipse Che is and the way to debug the Eclipse Che core source code running in tomcat?**

**Comment by TylerJewell** [comment]
See this known issue with debugging with Yatta.  I am going to close this issue and ask that you track #1861 instead.

https://github.com/eclipse/che/issues/1861
