### ISSUE TITLE
Migrate che-theia release process from ci centos to GH action

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18779]
See overall tracker https://github.com/eclipse/che/issues/17857#

Steps to perform:
* create new GH action for performing a release, as triggered by a push to release branch - see example in https://github.com/eclipse/che-plugin-registry/actions?query=workflow%3A%22Release+Che+Plugin+Registry%22 and https://github.com/eclipse/che-plugin-registry/blob/master/.github/workflows/release.yml
* disconnect release branch trigger from CICO via MR against https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml
* verify new action works when VERSION file in release branch is updated, after running make-release.sh script
* verify action works as part of overall che-release script

**Comment by nickboldt** [comment]
Please update this issue with links to PR for the new action you wrote for this, plus PRs involved in disabling ci centos release branch trigger. If this issue is done, please close it.

**Comment by benoitf** [comment]
@azatsarynnyy is it complete now ?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy is it complete now ?

@benoitf I suppose you wanted to ask @mkuznyetsov

**Comment by nickboldt** [comment]
Not yet done, see:

* https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml#L2012
* https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml#L2178

**Comment by nickboldt** [comment]
MR to remove theia from cico: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/15206/diffs
