### ISSUE TITLE
Released Che should reference the latest plugins

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18777]
### Is your task related to a problem? Please describe.
This issue is about the missed piece after we moved to latest plugins only.

To be compatible with different version of plugins registries, Che Server should define `latest` version for plugin it references, like default editor and factory default editor:
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L662
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L650

The master should still reference nightly or next, but released Che should reference latest.

Related issue: Suggest only the `latest` plugin version to use https://github.com/eclipse/che/issues/18491

**Comment by sleshchenko** [comment]
cc @sunix @ericwill

**Comment by nickboldt** [comment]
Could this be a fix for what you need?

https://github.com/eclipse/che/pull/18822

**Comment by nickboldt** [comment]
is this done?

**Comment by sleshchenko** [comment]
Seems https://github.com/eclipse/che/pull/18822 fully fixes the described issue. Released Che should now reference latest plugins and be compatible with old plugin registries.
