### ISSUE TITLE
Publish che-e2e npm package into public registry

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#18772]
### Is your task related to a problem? Please describe.
We would like to start publishing orh typescript e2e tests package on npm registry for easier dependency management in downstream.

### Prerequisite: 
Have proper versioning of e2e npm package #18771

### Describe the solution you'd like
- [x] Che release pipelines should also publish che-e2e package into https://www.npmjs.com/package/@eclipse-che/che-e2e or simmilar
- [x] Che nightly pipelines should publish che-e2e package with timestamped version (for example `7.25.0.1610365568`) and tag `nightly`
    - Example of this timestamp versioning can be found here: https://github.com/che-incubator/vscode-theia-comparator/blob/master/.travis.yml#L25

Story points: 3-5 (copy process for existing npm publishing, eg., from che-plugin-registry (generator) or che-server (dto)

**Comment by nickboldt** [comment]
Work started this past week on dependent issue #18771, but it is unclear how much progress has been made, as Mykhailo did not provide a standup / status before going on PTO for two weeks.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by dmytro-ndp** [comment]
@makambalaji , @mkuznyetsov : it looks as fixed.
Can it be closed?
