### ISSUE TITLE
Migrate che-machine-exec release process from ci centos to GH action

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18778]
See overall tracker https://github.com/eclipse/che/issues/17857#

Steps to perform:
* create new GH action for performing a release, as triggered by a push to release branch - see example in https://github.com/eclipse/che-plugin-registry/actions?query=workflow%3A%22Release+Che+Plugin+Registry%22 and https://github.com/eclipse/che-plugin-registry/blob/master/.github/workflows/release.yml
* disconnect release branch trigger from CICO via MR against https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml
* verify new action works when VERSION file in release branch is updated, after running make-release.sh script
* verify action works as part of overall che-release script

**Comment by mkuznyetsov** [comment]
https://github.com/eclipse/che-machine-exec/pull/119

**Comment by nickboldt** [comment]
Not done, as we saw today it's not actually working due to a problem in the make-release.sh script.

Here's the fix we discussed today on the call: https://github.com/eclipse/che-machine-exec/pull/125

I looked all day for your PR but I guess you must have released che-machine-exec 7.25.1 manually, as I see new sha and version tags here:

https://quay.io/repository/eclipse/che-machine-exec?tag=latest&tab=tags
