### ISSUE TITLE
Stop using npm-install in CI. Use npm-ci instead

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#18773]
### Is your task related to a problem? Please describe.
We are currently using `npm install` in lot of places in our testing pipelines & docker image build of e2e-tests image.
This is not safe, as npm install could produce different dependency tree each time (for example when new version of some dependency is published) [1].
For sake of reproducible builds&tests we should use `npm-ci` which doesn't compute new dependency tree, but instead of that just reproduces the dependency tree from package-lock.json.
Documentation:
- https://docs.npmjs.com/cli/v6/configuring-npm/package-locks
- https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json
- https://docs.npmjs.com/cli/v6/commands/npm-ci

[1] https://stackoverflow.com/a/56254478/2556329

### Describe the solution you'd like
We should not use `npm install` in any of our testing pipelines and build scripts. 

`npm install` should be used only for local development and if upversioning of any dependency is needed, package-lock.json needs to be updated.

**Comment by makambalaji** [comment]
Drafted the pr: https://github.com/eclipse/che/pull/20927

**Comment by makambalaji** [comment]
PR got merged: #20927, so closing this issue
