### ISSUE TITLE
Github PR plugin: restarting a workspace is asking again to sign in

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18782]
### Describe the bug
Github PR plugin - Sign in is not persisted.

### Che version

 - [x] latest 7.24.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. start a workspace with the github pr plugin and a github project to clone.
2. sign in as requested
3. browse the gh panel -> ok
4. restart the workspace
5. sign in is requested again
6. also IF YOU DO NOT CLICK `Sign in` on time (say you gone to take a coffee), it is impossible to sign in again (command not available) -> need to restart again the workspace. (created https://github.com/eclipse/che/issues/18783)

### Expected behavior
Should not request sign in again, information should be persisted.
Ideally it should be persisted in the user level (so sign in once, would work for any workspace started by the user)
If not, at least it should be persisted for the workspace.

Also for 6. should have a command to sign in. created a additional issue for that https://github.com/eclipse/che/issues/18783

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Selection_154](https://user-images.githubusercontent.com/650571/104295597-f6713380-54c0-11eb-99e7-cbd768b4db03.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by vinokurig** [comment]
is fixed by https://github.com/eclipse/che-plugin-registry/pull/798

**Comment by sunix** [comment]
@vinokurig I am reopening the issue as it has been reverted https://github.com/eclipse/che-plugin-registry/commit/aeb6ffb8981eb6e4192c479700d1abc8504d20f7
