### ISSUE TITLE
Migrate che-server release process from ci centos to GH action

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18780]
See overall tracker https://github.com/eclipse/che/issues/17857#

Steps to perform:
* extract che server build steps from overall che-release script, including credentials for maven nexus artifact deployment
* create new GH action for performing a release, as triggered by a push to release branch - see example in https://github.com/eclipse/che-plugin-registry/actions?query=workflow%3A%22Release+Che+Plugin+Registry%22 and https://github.com/eclipse/che-plugin-registry/blob/master/.github/workflows/release.yml
* disconnect release branch trigger from CICO via MR against https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml
* verify new action works when VERSION file in release branch is updated, after running make-release.sh script
* verify action works as part of overall che-release script

**Comment by nickboldt** [comment]
Can we remove these lines from cico?

https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/ci-centos/defaults.yaml#L2133-2176

@mkuznyetsov: Please update this issue with links to PR for the new action you wrote for this, plus PRs involved in disabling ci centos release branch trigger.

Once this issue is done, please close it.

**Comment by nickboldt** [comment]
MR to remove server from cico: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/15206/diffs

**Comment by mkuznyetsov** [comment]
Action is complete - https://github.com/eclipse/che/actions/workflows/release.yml
