### ISSUE TITLE
Changing workspaces deployment strategy

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18789]
### Is your enhancement related to a problem? Please describe.

Current workspaces deployment strategy is `RollingUpdate` but that doesn't work well with RWO Persistent Volumes.

![image](https://user-images.githubusercontent.com/606959/104440624-e2960200-5592-11eb-9b3b-761eea2fdb0e.png)

As a consequence `kubectl rollout restart deployment/<workspace-deployment>` will fail when the workpace pod is attached to a RWO PV.

### Describe the solution you'd like

Use `Recreate` strategy instead.

### Additional context

Given the fact that we are transitioning to the `DevWorkspace Operator` that should be done there rather then in the che-sever infrastructures.

**Comment by sleshchenko** [comment]
DevWorkspace Operator already sets Recreate update strategy for DevWorkspace deployment https://github.com/devfile/devworkspace-operator/blob/master/controllers/workspace/provision/deployment.go#L202
