### ISSUE TITLE
Add ability to install Orion plugins inside the Che editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#1878]
In order to easily extend Orion editor functionality we need to add possibility to install Orion plugins for Che editor.

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.

**Comment by TylerJewell** [comment]
@azatsarynnyy - can you do a quick bulleted list of what the end user sequence might be like?  Do we have a short example of an existing orion plugin that can be added into Che?

**Comment by azatsarynnyy** [comment]
@TylerJewell this task is needed more for us than for end user.
See [Highlight Artik-specific keywords in the editor](https://github.com/codenvy/artik-ide/issues/87).
Also it may be used by plugins' developer for adding Orion plugin programmatically.
But, for now, there's no way for end user to install Orion plugin.
