### ISSUE TITLE
Che4z: Dead links for Zowe CLI plug-ins

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18788]
These links are dead. Content preventively commented out.

 The following Zowe CLI plug-ins are included in the Che4z basic stack:

    CA Endevor SCM plug-in for Zowe CLI

    CA File Master Plus plug-in for Zowe CLI

    IBM Db2 plug-in for Zowe CLI

    IBM CICS plug-in for Zowe CLI

URL        `https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ca-endevor-scm.html'
Parent URL http://localhost:4000/che-7/extensions/eclipse-che4z/, line 933, col 4
Real URL   https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ca-endevor-scm.html
Result     Error: 404 Not Found

URL        `https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ca-file-master-plus.html'
Parent URL http://localhost:4000/che-7/extensions/eclipse-che4z/, line 936, col 4
Real URL   https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ca-file-master-plus.html
Result     Error: 404 Not Found

URL        `https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-db2-database.html'
Parent URL http://localhost:4000/che-7/extensions/eclipse-che4z/, line 939, col 4
Real URL   https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-db2-database.html
Result     Error: 404 Not Found
 1 thread active,    34 links queued, 1410 links in 1490 URLs checked, runtime 6 minutes, 26 seconds

URL        `https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-cics.html'
Parent URL http://localhost:4000/che-7/extensions/eclipse-che4z/, line 942, col 4
Real URL   https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-cics.html
Result     Error: 404 Not Found

**Comment by SNiemann15** [comment]
Here the updated links: 
* CA Endevor SCM plug-in for Zowe CLI
https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-endevor-scm-plug-in-for-zowe-cli.html
* CA File Master Plus plug-in for Zowe CLI
https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-file-master-plus-plug-in-for-zowe-cli.html
* IBM Db2 plug-in for Zowe CLI
https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-db2-database.html
* IBM CICS plug-in for Zowe CLI
https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-cics.html

Alternatively you could also link to docs.zowe.org. However, I only found the two IBM plugins there:  
* IBM Db2 plug-in for Zowe CLI
https://docs.zowe.org/v1-0-x/user-guide/cli-db2plugin.html
* IBM CICS plug-in for Zowe CLI
https://docs.zowe.org/v1-0-x/user-guide/cli-cicsplugin.html

**Comment by zeibura** [comment]
Addressed in https://github.com/eclipse/che-docs/pull/1831
