### ISSUE TITLE
UX: detection for advertisement blocker

### ISSUE THREAD

**Issue by mschindl** [eclipse-che/che#18797]
### Is your enhancement related to a problem? Please describe.
Yes, because uBlock stopped loading the UX with the error message "Loading a runtime token..."

### Describe the solution you'd like
A detection for advertisement blocker with a note about malfunction.

### Additional context
Disable / Uninstall of advertisement blocker helped

![image](https://user-images.githubusercontent.com/26382876/104476273-58fd2900-55c0-11eb-8762-b38856cbee27.png)

**Comment by benoitf** [comment]
@mschindl are you using che.openshift.io or it's on a custom install ?

**Comment by mschindl** [comment]
No, I used following deployment:
https://developers.redhat.com/developer-sandbox
