### ISSUE TITLE
Allow to build custom registries using OpenShift Build

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18798]
### Is your enhancement related to a problem? Please describe.

The [guide to build custom registries](https://www.eclipse.org/che/docs/che-7/administration-guide/building-custom-registry-images/) tells to run the script [`build.sh` at the root of the registry repository](https://github.com/eclipse/che-devfile-registry/blob/master/build.sh). That script does a `docker build`.

The problem is that users may not have the privileges to run `docker` in their enterprise network and won't be able to build a custom registry. 

### Describe the solution you'd like

Add an option to use buildah rather than docker.

### Describe alternatives you've considered

Add an option to `build.sh` to use [OpenShift build](https://docs.openshift.com/container-platform/4.6/builds/creating-build-inputs.html#builds-define-build-inputs_creating-build-inputs) rather than Docker. For example using [`oc start build`](https://docs.openshift.com/container-platform/4.6/builds/creating-build-inputs.html#builds-binary-source_creating-build-inputs).

**Comment by l0rd** [comment]
As discussed at prioritization we are going to start with adding a `buildah/podman` option.

**Comment by ericwill** [comment]
Both registries support building with podman/buildah now.
