### ISSUE TITLE
Rh-Che video is broken in 7.24.1

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18796]
### Describe the bug
Typescript tests running on rh-che has broken video recording. The issue was also present in upstream but is solved now, so it seems it's puerly rh-c-he specific issue.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
The video should be shown properly.

Example of corrupted video: http://artifacts.ci.centos.org/devtools/rhche/devtools-saas-openshiftio-pre-release-test/64/e2e_report/report/ffmpeg_report/output.mp4

**Comment by dmytro-ndp** [comment]
@Katka92: fixup is to set proper resolution in entrypoint.sh:
```
Xvfb :20 -screen 0 1920x1080x24 > /dev/null 2>&1 &
```
https://github.com/eclipse/che/commit/dd488baf8b938a0204defc142338dacc46bc2b31#diff-fd0068b460871039e0e5fe4e23f3ef957c31a48f0e9b61ce12ec27dbf573ff00

**Comment by Katka92** [comment]
Fixed.
