### ISSUE TITLE
Impact of new plugin model on the documentation

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18793]
We need changes to the documentation reflection changes in the new plugin model.

For example, this procedure is broken:  https://www.eclipse.org/che/docs/che-7/contributor-guide/branding-che-theia/

**Comment by themr0c** [comment]
cc @ericwill

**Comment by ericwill** [comment]
We should document the new [che-editors.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml) file, and remove direct links to the old hosted `meta.yaml` files.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2647

**Comment by ericwill** [comment]
> Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2647

We actually don't need a downstream issue, because the upstream plugin registry and downstream ones are different (at least for now).

**Comment by ericwill** [comment]
That said, we are thinking of aligning the two registries, so maybe keeping a downstream ticket open for now isn't such a bad idea.
