### ISSUE TITLE
About the feature of "remote machine"

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#188]
Hi, when I'm reading the doc of [Custom Machines](https://eclipse-che.readme.io/docs/custom-machine), I found there is a feature of remote machine:

> Environments contain one or more machines. A machine is an abstraction for a single run time, defined by a recipe or stack. A machine can have different implementations and our default implementation is to have one Docker container for each machine. Different Che deployments can have different implementations for machines such as localhost or **a remote VM**.
> 
> Any changes made to the project files within the machine is synchronized back to the workspace master out of the machine. On local systems this happens through a simple mount. **On distributed systems, Che uses an rsync protocol to keep project files synchronized between machines and the workspace that owns the machine.**

I'm quite interested in this feature, but can't find more information.

What is a remote VM? How can we create a remote VM? Is the remote VM is a docker container, or any other virtual hosts like digital ocean, aws ec2, or something?

For now, is this feature available that I can have a try myself?

**Comment by TylerJewell** [comment]
This feature will be available in Codenvy On-Prem that is a distributed cloud based upon Eclipse Che. Codenvy based upon Eclipse Che 4 will be released after we ship Che.  Codenvy has an embedded swarm system that has the ability to distribute workspaces to any node, whether it is in your datacenter, at EC2, Digital Ocean, etc.

We will have a beta of Codenvy On-Prem based on Che in a few weeks.

**Comment by garagatyi** [comment]
Docker implementation of remote machine is only available now. Swarm system is used for Codenvy onprem. Other variants (such as VMs) are not implemented  yet.

**Comment by TylerJewell** [comment]
We have added a section to the docs discussing Scaling Che. This should provide the specifics you are seeking.
https://eclipse-che.readme.io/docs/scaling
