### ISSUE TITLE
factory devfile: should support URL from Github

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18805]
### Describe the bug
Providing a devfile.yaml URL from Github to the Che factory is failling. Che is expecting a `raw` URL. But it is a common that user provide the Github view URL.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. go to https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/quarkus
2. right click on the `devfile.yaml` link.
3. copy the link address (should be https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml)
4. paste the  link in the Che dashboard (add workspace, url of devfile)
5. the dashboard is failing to load the devfile.

### Expected behavior
it should detect that it is github and fetch the raw devfile automatically: https://github.com/eclipse/che-devfile-registry/raw/master/devfiles/quarkus/devfile.yaml

### Screenshots
![Selection_159](https://user-images.githubusercontent.com/650571/104585521-6a980c80-5664-11eb-9fb4-94793ff1b11d.png)

**Comment by Siddharth1010** [comment]
Hi @sunix,  Could you please let me know which file this issue lies in?

**Comment by sunix** [comment]
@Siddharth1010 it should be in https://github.com/eclipse/che/tree/master/wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github

**Comment by skabashnyuk** [comment]
not reproduced on the latest version 7.26-snapshot.
![Знімок екрана 2021-02-04 о 15 37 50](https://user-images.githubusercontent.com/1614429/106900267-fe5a7700-66fe-11eb-8b79-d15fa74f10db.png)

**Comment by sunix** [comment]
Nice @skabashnyuk, I trust you and closing it.
Do you have an idea which PR is solving that one ?

**Comment by skabashnyuk** [comment]
Tested with the wrong url. Reopening.

**Comment by skabashnyuk** [comment]
Fixed in https://github.com/eclipse-che/che-server/pull/41  and https://github.com/eclipse-che/che-server/pull/43
