### ISSUE TITLE
Is it possible way to debug Che Server?

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#1880]
I built my own Che plugin (client and server side extensions) and I need to debug my REST API  in IntelliJ IDEA. 
Is it some possible way to do it?

**Comment by ghost** [comment]
@zatsepinvl https://eclipse-che.readme.io/docs/setup-che-workspace this can help you

**Comment by BingxuHong** [comment]
@eivantsov 
The server side plug-in runs in the Tomcat server. 
I think we should configure Tomcat Remote Server. (not Super dev mode)
The contents about this are not in the document you linked.

I tried to make it, but the debug button isn't active. I think my settings are incorrect.
![image](https://cloud.githubusercontent.com/assets/20534093/17008961/31a14ce6-4f31-11e6-8fb8-3c56a8611714.png)

**Comment by zatsepinvl** [comment]
@eivantsov 
@BingxuHong is right, it's not exactly what I want: it describes debugging only client side (which is GWT)

@BingxuHong
Try to set "Application server" to "<your_built_assembly>/tomcat". But it's not enough to debug. It must be set some additional parameters to IDE and to Tomcat and this is problem for me now.

**Comment by tolusha** [comment]
@zatsepinvl 
To debug server side you have to open operation perspective in the IDE and go to servers tab:
![screenshot from 2016-07-21 11 42 01](https://cloud.githubusercontent.com/assets/1640675/17016472/f8d52656-4f37-11e6-9a73-3a57d4b5d6d1.png)

Have a look the list of server addresses. The needed one where exposed port is 4403/tcp.
In my case it is: `node2.beta.codenvy.com:51745`
So create remote debug in Intellij IDE with yours values, it will be something like `localhost:32340`

**Comment by zatsepinvl** [comment]
I have this one:
![untitled1](https://cloud.githubusercontent.com/assets/11683340/17017409/f26f67a0-4f3b-11e6-88be-d077b984da71.png)
And I need to set up: Host, Port and address (in debug). I dont understand what I need to use from this image. 
Moreover, it's all 192.168.99.100 address, but I use localhost and cannot establish any connection to the first one.

**Comment by tolusha** [comment]
try localhost:32779 to setup remote debug

**Comment by zatsepinvl** [comment]
"Unable to connect to the localhost:32779" 
"Unable to connect to the 192.168.99.100:32779"

**Comment by tolusha** [comment]
Try to add new port forwarding rule for your VB image:
![screenshot from 2016-07-21 12 38 17](https://cloud.githubusercontent.com/assets/1640675/17018323/f173748c-4f3f-11e6-9302-34160033ae01.png)

![screenshot from 2016-07-21 12 38 51](https://cloud.githubusercontent.com/assets/1640675/17018335/f6652abc-4f3f-11e6-9a38-f15b8a8a8d83.png)

**Comment by zatsepinvl** [comment]
Unable to open debugger port (localhost:32779): java.net.SocketException "Connection reset"

**Comment by zatsepinvl** [comment]
It WORKS! Thanks a lot! I think it will be great to add this tutorial in the Che docs.

**Comment by tolusha** [comment]
Take notice, if you restart che the debug port will be changed then.

**Comment by ghost** [comment]
@zatsepinvl it is weird though that you cannot connect using VM IP. I'll run some tests on Windows myself.

**Comment by zatsepinvl** [comment]
Can it be due to my local antivirus/firewall?

**Comment by ghost** [comment]
@zatsepinvl I can't say right away what it is until I try it myself.

**Comment by ghost** [comment]
@zatsepinvl I don't know what's happening but I have just attached a debugger on Windows 8 with VirtualBox (see screenshot). So, yes, maybe it's your local security settings that cause connection failure.
![debug](https://cloud.githubusercontent.com/assets/5337267/17033692/006040fe-4f88-11e6-8697-a391827cab8d.png)
