### ISSUE TITLE
Update plugin sample 

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#1882]
For documentation and customer needs we created a sample plugin showing various aspect of developing an extension for Che:
https://github.com/vparfonov/plugin-sample-wizard

This sample extension must be packaged with the default Che assembly, as we did here:
https://github.com/eclipse/che/tree/master/samples

Please, ensure that this plugin will be kept up-to-date with master. So at any point in time, this plugin sample can be built and tested.

**Comment by slemeur** [comment]
This issue is cross-linked with #1875

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
