### ISSUE TITLE
Update copyright dates to reflect reality

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18821]
### Is your task related to a problem? Please describe.

Today, new files are being created in che repos with copyright dates set to 2012-2018, because that's how the license checker is configured. 

For example:

https://github.com/eclipse/che/commit/07ad51bd3e682e4f75c9481c9314149e1d742fc0#diff-77d55377de800c8f1190b6335aaf5e8f9bc0f8704a0e0aaefc063f89add91577R2
https://github.com/eclipse/che/commit/f122dad96cfc3474b4b1c86b3c77b088b3344b5d#diff-77d55377de800c8f1190b6335aaf5e8f9bc0f8704a0e0aaefc063f89add91577L2

Obviously, that's wrong, so we should use a correct license range. Or better, ignore the date range entirely, so it's acceptable to have new files w/ a 2021 copyright instead of a 2012-2021 range for files created this year.

### Describe the solution you'd like

For CRW, I worked around the problem recently with code like this:

https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.6-rhel-8/pom.xml#L4
https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.6-rhel-8/pom.xml#L49

But for Che, there are significantly more files to update and keep current.

### Describe alternatives you've considered

Maybe it's time to disable the license checker, or move to a more modern version that can use more than one valid date range?

**Comment by ibuziuk** [comment]
I opened https://github.com/eclipse/che/issues/16470 back in 2020 but this got stale, so hopefully, this can be addressed in 2021

**Comment by skabashnyuk** [comment]
Related PRs
https://github.com/eclipse/che-parent/pull/97
https://github.com/eclipse/che/pull/12264

**Comment by skabashnyuk** [comment]
Done
