### ISSUE TITLE
Cannot deploy Eclipse Che with external Keycloak

### ISSUE THREAD

**Issue by KateSieraia** [eclipse-che/che#18827]
### Describe the bug
Cannot deploy eclipse che with `--che-operator-cr-patch-yaml` flag and external keycloak provider

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)

    $docker version
    Client: Docker Engine - Community
     Version:           20.10.2
     API version:       1.41
     Go version:        go1.13.15
     Git commit:        2291f61
     Built:             Mon Dec 28 16:14:16 2020
     OS/Arch:           windows/amd64
     Context:           default
     Experimental:      true
    Server: Docker Engine - Community
     Engine:
      Version:          20.10.2
      API version:      1.41 (minimum version 1.12)
      Go version:       go1.13.15
      Git commit:       8891c58
      Built:            Mon Dec 28 16:15:28 2020
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          1.4.3
      GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
     runc:
      Version:          1.0.0-rc92
      GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
     docker-init:
      Version:          0.19.0
      GitCommit:        de40ad0

    $kubectl version
    Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     `chectl/7.24.1 win32-x64 node-v12.20.0`

    $chectl server:deploy  --platform=docker-desktop  --installer=operator --che-operator-cr-patch-yaml=our_resource.yaml
    › Current Kubernetes context: 'docker-desktop'
    √ Verify Kubernetes API...OK
    √ 👀  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "che"...it is not
    √ ✈️  Docker Desktop preflight checklist
    √ Verify if kubectl is installed
    √ Verify if kubectl context is Docker Desktop: Found docker-desktop.
    √ Verify remote kubernetes status...done.
    √ Check Kubernetes version: Found v1.19.3.
    √ Verify if nginx ingress is installed
    ↓ Installing nginx ingress [skipped]
      → Ngninx ingress is already setup.
    √ Verify domain is set... auto-assigning domain to 172.23.48.1.nip.io....set to 172.23.48.1.nip.io.
    √ Following Eclipse Che logs
    √ Start following Operator logs...done
    √ Start following Eclipse Che server logs...done
    √ Start following Postgres logs...done
    √ Start following Keycloak logs...done
    √ Start following Plugin registry logs...done
    √ Start following Devfile registry logs...done
    √ Start following namespace events...done
    »   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
    √ 🏃‍  Running the Eclipse Che operator
    √ Copying operator resources...done.
    √ Create Namespace (che)...It already exists.
    √ Create ServiceAccount che-operator in namespace che...done.
    √ Create Role che-operator in namespace che...done.
    √ Create ClusterRole che-che-operator...done.
    √ Create ClusterRole che-che-namespace-editor...done.
    √ Create ClusterRoleBinding che-che-operator-namespace-editor...done.
    √ Create RoleBinding che-operator in namespace che...done.
    √ Create ClusterRoleBinding che-che-operator...done.
    √ Create CRD checlusters.org.eclipse.che...done.
    √ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    √ Create deployment che-operator in namespace che...done.
    √ Operator pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Prepare Eclipse Che cluster CR...Done.
    √ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace che...done.
    > ✅  Post installation checklist
    √ PostgreSQL pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Devfile registry pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Plugin registry pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    > Eclipse Che pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      × Starting...failed
        → Failed to start a pod, reason: Error, exitCode: 137
      Eclipse Che status check
    Retrieving Keycloak admin credentials
    Retrieving Che self-signed CA certificate
    Prepare post installation output
    »   Error: Error: Failed to start a pod, reason: Error, exitCode: 137
    »   Command server:deploy failed. Error log: C:\Users\sieraia\AppData\Local\chectl\error.log

our_resource.yaml:

    apiVersion: org.eclipse.che/v1
    kind: CheCluster
    metadata:
      name: eclipse-che
    spec:
      auth:
        externalIdentityProvider: true
        identityProviderURL: https://auth.example.com
        identityProviderRealm: ExampleId
        identityProviderClientId: ExampleId

   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
As the error was in the eclipse che pod, here are the logs from it:
[eclipse_che_pod.log](https://github.com/eclipse/che/files/5835285/eclipse_che_pod.log)

### Additional context
I wanted to run Eclipse Che with external Keycloak instance (locally as a test, and if it was successful I planned to do it in aws later). As I wanted to leave everything else by default, I used   `--che-operator-cr-patch-yaml` flag and changed only part of yaml that is relevant to keycloak (see our_resource.yaml above)
It fails to deploy, looks like the custom keycloak address is not available, see logs:

    2021-01-19 09:13:02,698[ost-startStop-1]  [INFO ] [o.e.c.m.k.s.OIDCInfoProvider 70]     - Retrieving OpenId configuration from endpoint: /auth/realms/ExampleId/.well-known/openid-configuration

    ...

    Error in custom provider, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: /auth/realms/ExampleId/.well-known/openid-configuration

    ...

    Caused by: java.net.MalformedURLException: no protocol: /auth/realms/ExampleId/.well-known/openid-configuration
	    at java.base/java.net.URL.<init>(Unknown Source)
	    at java.base/java.net.URL.<init>(Unknown Source)
	    at java.base/java.net.URL.<init>(Unknown Source)
	    at org.eclipse.che.multiuser.keycloak.server.OIDCInfoProvider.get(OIDCInfoProvider.java:72)
	    ... 124 more

Compare with deployment with default keycloak:

    2021-01-18 14:51:12,825[ost-startStop-1]  [INFO ] [o.e.c.m.k.s.OIDCInfoProvider 70]     - Retrieving OpenId configuration from endpoint: http://keycloak.che.svc:8080/auth/realms/che/.well-known/openid-configuration

But when I inspect the cluster after failed deployment, the address is there:

    $ kubectl describe CheCluster -n che
    Name:         eclipse-che
    Namespace:    che
    Labels:       <none>
    Annotations:  <none>
    API Version:  org.eclipse.che/v1
    Kind:         CheCluster
    Metadata:
      Creation Timestamp:  2021-01-19T09:11:53Z
      Generation:          10
      Managed Fields:
        API Version:  org.eclipse.che/v1
        Fields Type:  FieldsV1
        fieldsV1:
          f:spec:
            .:
            f:auth:
              .:
              f:externalIdentityProvider:
              f:identityProviderClientId:
              f:identityProviderRealm:
              f:identityProviderURL:
              f:updateAdminPassword:
            f:database:
              .:
              f:externalDb:
            f:k8s:
              .:
              f:ingressDomain:
              f:tlsSecretName:
            f:metrics:
              .:
              f:enable:
            f:server:
              .:
              f:allowUserDefinedWorkspaceNamespaces:
              f:cheClusterRoles:
              f:cheDebug:
              f:gitSelfSignedCert:
              f:tlsSupport:
              f:useInternalClusterSVCNames:
            f:storage:
              .:
              f:preCreateSubPaths:
              f:pvcClaimSize:
              f:pvcStrategy:
        Manager:      unknown
        Operation:    Update
        Time:         2021-01-19T09:11:53Z
        API Version:  org.eclipse.che/v1
        Fields Type:  FieldsV1
        fieldsV1:
          f:spec:
            f:auth:
              f:identityProviderIngress:
              f:identityProviderPostgresSecret:
              f:identityProviderRoute:
              f:identityProviderSecret:
            f:database:
              f:chePostgresDb:
              f:chePostgresHostName:
              f:chePostgresPort:
              f:chePostgresSecret:
            f:imagePuller:
              .:
              f:enable:
              f:spec:
            f:server:
              f:cheFlavor:
              f:cheHost:
              f:cheLogLevel:
              f:cheServerIngress:
              f:cheServerRoute:
              f:devfileRegistryIngress:
              f:devfileRegistryRoute:
              f:externalDevfileRegistry:
              f:externalPluginRegistry:
              f:pluginRegistryIngress:
              f:pluginRegistryRoute:
              f:selfSignedCert:
          f:status:
            .:
            f:cheClusterRunning:
            f:cheURL:
            f:cheVersion:
            f:dbProvisioned:
            f:devfileRegistryURL:
            f:keycloakProvisioned:
            f:keycloakURL:
            f:openShiftoAuthProvisioned:
            f:pluginRegistryURL:
        Manager:         che-operator
        Operation:       Update
        Time:            2021-01-19T09:12:38Z
      Resource Version:  60957
      Self Link:         /apis/org.eclipse.che/v1/namespaces/che/checlusters/eclipse-che
      UID:               78bfba75-1df4-46db-937f-058ae55fcef9
    Spec:
      Auth:
        External Identity Provider:   true
        Identity Provider Client Id:  ExampleId
        Identity Provider Ingress:
        Identity Provider Postgres Secret:  che-identity-postgres-secret
        Identity Provider Realm:            ExampleId
        Identity Provider Route:
        Identity Provider Secret:  che-identity-secret
        Identity Provider URL:     https://auth.example.com
        Update Admin Password:     true
      Database:
        Che Postgres Db:         dbche
        Che Postgres Host Name:  postgres
        Che Postgres Port:       5432
        Che Postgres Secret:     che-postgres-secret
        External Db:             false
      Image Puller:
        Enable:  false
        Spec:
      k8s:
        Ingress Domain:   172.23.48.1.nip.io
        Tls Secret Name:  che-tls
      Metrics:
        Enable:  true
      Server:
        Allow User Defined Workspace Namespaces:  false
        Che Cluster Roles:                        che-che-namespace-editor
        Che Debug:                                false
        Che Flavor:                               che
        Che Host:                                 che-che.172.23.48.1.nip.io
        Che Log Level:                            INFO
        Che Server Ingress:
        Che Server Route:
        Devfile Registry Ingress:
        Devfile Registry Route:
        External Devfile Registry:  false
        External Plugin Registry:   false
        Git Self Signed Cert:       false
        Plugin Registry Ingress:
        Plugin Registry Route:
        Self Signed Cert:                false
        Tls Support:                     true
        Use Internal Cluster SVC Names:  true
      Storage:
        Pre Create Sub Paths:  true
        Pvc Claim Size:        1Gi
        Pvc Strategy:          common
    Status:
      Che Cluster Running:           Unavailable
      Che URL:
      Che Version:
      Db Provisioned:                true
      Devfile Registry URL:          https://devfile-registry-che.172.23.48.1.nip.io
      Keycloak Provisioned:          false
      Keycloak URL:
      Open Shifto Auth Provisioned:  false
      Plugin Registry URL:           https://plugin-registry-che.172.23.48.1.nip.io/v3
    Events:                          <none>

**Comment by skabashnyuk** [comment]
@KateSieraia  Thank you for this report. Could you please also share the content of patch ``--che-operator-cr-patch-yaml``  (is this our_resource.yaml?) and tell us more about your k8s. I see this is windows. Docker version? K8s version?

**Comment by KateSieraia** [comment]
@skabashnyuk yes, the patch is `our_resource.yaml` file. The output of `docker version` and `kubectl version` is already included in the **Runtime** section of the bug report, sorry for bad placement

**Comment by skabashnyuk** [comment]
Are you sure that `identityProviderURL: https://auth.example.com` is an external URL that is reachable from the che-server pod?

**Comment by KateSieraia** [comment]
I tried 2 configurations:
1. Host keycloak on localhost:8080, I tried following:
- `identityProviderURL: localhost:8080`
- `identityProviderURL: http://localhost:8080`
- `identityProviderURL: 127.0.0.1:8080`
- `identityProviderURL: http://127.0.0.1:8080`
I also tried notation without the port:
- `identityProviderURL: localhost`
- `identityProviderURL: http://localhost`
- `identityProviderURL: 127.0.0.1`
- `identityProviderURL: http://127.0.0.1`

2. External site that is available only in the corporate network which my pc is currently in, so it shouldn't be a problem.

Both configuration fail in the same way

**Comment by tolusha** [comment]
Using localhost as identity provider url is incorrect because it won't be reachable from another containers.
It should be public urls

**Comment by KateSieraia** [comment]
"Using localhost as identity provider url is incorrect because it won't be reachable from another containers." - I suspected as much, but I then tried external site (hosted on aws in public hosted zone) with the same result. Maybe the fact that is only accessible from within the corporate network is the case? I will try to deploy it on aws tomorrow.

**Comment by tolusha** [comment]
Try `curl/wget` inside che-server container to check if it is reachable.

**Comment by nfrush** [comment]
I'm facing a similar issue with Che 7.25.1 and Keycloak 11. The Keycloak server is curl-able from the che container (using the custom certs laid down by annotation the custom-certs configmap). However, Che fails to get the OAuth well known data from the Keycloak endpoint.

**Comment by tolusha** [comment]
@nfrush 
Do you have any stacktrackes ?

**Comment by KateSieraia** [comment]
I had to make following changes to the AWS configuration that we use:
Add the public IP of the NAT Gateway to the inbound rules of that gateway.
After this change everything works.
I am closing this issue

**Comment by tolusha** [comment]
@KateSieraia 
Thank you for updates.
