### ISSUE TITLE
Unable to push to community-operators repo during "Release community operator PRs" workflow execution

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#18830]
### Describe the bug
During the release of 7.24.2 community operator PRs it was not possible to push changes to the community-operators repository:

`(refusing to allow a Personal Access Token to create or update workflow `.github/workflows/operator_release.yaml` without workflow` scope)`

### Steps to reproduce
running `Release community operator PRs` workflow in che-operator repository

**Comment by Vinicius-8** [comment]
Enter you github profile settings > developer settings > Personal access tokens > edit your bash token  > check the workflow scope

**Comment by mkuznyetsov** [comment]
thanks, looks like this issues has been solved some time ago (probably, an improper token was used)
