### ISSUE TITLE
Review how the che server could return the default namespace of a user (resolve che-<placeholder>)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18839]
### Is your task related to a problem? Please describe.
We need to provide the default namespace of a user configuration from che-server side to other clients like the dashboard.

### Describe the solution you'd like
- Add one extra value for the result of  `/api/workspace/settings/` method.
### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by sparkoo** [comment]
For devfile2/devworkspace milestone 1, dashboard will create namespaces and will use `/kubernetes/namespace` che-server REST API method to obtain namespace name. If there are any issues with that method, the new issue should be created for that. As well as work for next milestones in this area will be handled with new issues. For those reasons I'm closing this one as there are no further actions planned to do.
