### ISSUE TITLE
Add ability to preview an HTML file into another browser window

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#1883]
It should be possible to preview an HTML file into another browser window.

The experience expected would be the following:
- The project explorer is showing HTML files
- User can right-click on the HTML files
  - User will get "Preview" option in the right-click menu
- When click on "Preview", the HTML file is opened and rendered into another browser window. 

**Che version:**    4.5.0

**Comment by TylerJewell** [comment]
Or would "Send-To" be better words?  I think either can work.
