### ISSUE TITLE
[Rest API] Support factory link that points to a git repo of petclinic with a devfile 2.0

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18838]
### Is your task related to a problem? Please describe.
We would like to move forward with factory and devfile 2.0 support
### Describe the solution you'd like
Enhance `/api/factory/resolve/` API method so It can.
-  Accept factory link that points to a git repo of petclinic with a devfile 2.0 that has just mysql as a component (WITHOUT plugins), theia and machine exec.
- Validate if possible according to devfile 2.0 schema.
- Return devfile in 2.0 format in json or yaml whatever is simplest 

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by flacatus** [comment]
I will add severity P1, feel free to change base on yours priorities

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che/pull/18868
