### ISSUE TITLE
Vale false positive in administration-guide/con_cachine-images-for-faster-workspace-start.adoc

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#18849]
### Describe the bug

`vale` does not seem to recognize `ifeval` on a PR check run.

Vale output 
```
/che-docs/modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
 2:15  error  Did you really mean 'ifeval'?  Vale.Spelling 
```

For full Vale output see https://github.com/eclipse/che-docs/pull/1800/checks?check_run_id=1731978836
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by boczkowska** [comment]
Issue in docs Jira https://issues.redhat.com/browse/RHDEVDOCS-2281

**Comment by themr0c** [comment]
Fixed with the campaign targetting all vale errors.
