### ISSUE TITLE
Language and formatting in "Mounting a git credentials store into a workspace container" doc

### ISSUE THREAD

**Issue by rkratky** [eclipse-che/che#18848]
### Describe the bug

A number of formatting and language mistakes in the "Mounting a git credentials store into a workspace container" section of docs: https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-git-credential-store-into-a-workspace-container_che

* Articles
* App names
* Naked URL
* Missing mark-up
* etc. (see screenshots)

### Screenshots

![image](https://user-images.githubusercontent.com/6623103/105187748-6ae84a00-5b33-11eb-9f39-0592345f173c.png)

![image](https://user-images.githubusercontent.com/6623103/105187087-aafafd00-5b32-11eb-93fd-b6907671fb5c.png)

**Comment by boczkowska** [comment]
Issue in docs Jira https://issues.redhat.com/browse/RHDEVDOCS-2531
