### ISSUE TITLE
Setup code coverage reporting for Che-Theia repo

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18844]
### Is your task related to a problem? Please describe.
We need to set-up an automated code coverage reporting for Che-Theia.

### Describe the solution you'd like
Investigate what free services provide the required functionality and set-up one of them to report the code coverage automatically.

### Describe alternatives you've considered
- https://sonarcloud.io/
- https://about.codecov.io/

### Additional context
https://github.com/eclipse/che/issues/18621

**Comment by benoitf** [comment]
what is nice with github actions and codecov.io is that no token need to be provided (useful to run in PR jobs which don't have access to tokens)

**Comment by sunix** [comment]
Example for typescript + jest projects: https://github.com/eclipse/che-plugin-registry/pull/821
To have realistic code coverage metrics, I think we would need to enable `jest` for plugins and extensions that don't have any test ...

**Comment by sunix** [comment]
Reopening because it is not reflecting the real code coverage for the whole repo. It only gets the projects from the ones which has tests ... but projects with no tests should be marked as 0%.

**Comment by benoitf** [comment]
@sunix AFAIK it should be a new issue.

**Comment by sunix** [comment]
> @sunix AFAIK it should be a new issue.

I don't think so, this is not displaying the right value

**Comment by benoitf** [comment]
This task was to setup the automatic reporting.

reflecting code coverage is a different task. (not saying it's less important) but it has nothing to do about adding a codecov action.

**Comment by sunix** [comment]
This task is to report automatic reporting of code coverage, not "fake" code coverage.

**Comment by benoitf** [comment]
automatic reporting is done
if it's not accurate it's another issue.

**Comment by sunix** [comment]
It's like, a weather forecast report saying that it is sunny the whole week but, it's not (raining the whole week)

**Comment by sunix** [comment]
I prefer not to report rather then reporting wrong values.

**Comment by vzhukovs** [comment]
Created the following issue for the actual test coverage in core packages: https://github.com/eclipse/che/issues/19130

**Comment by sunix** [comment]
I renamed this issue, closing it.
