### ISSUE TITLE
chectl with workspace-engine=dev-workspace doesn't work

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18842]
### Describe the bug

Running `chectl server:deploy --workspace-engine=dev-workspace` currently doesn't work.

### Che version

nightly

### Steps to reproduce

On minikube try 

```
chectl server:deploy --workspace-engine=dev-workspace -p minikube
```

### Expected behavior

The devworkspace operator gets installed along with Che

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/606959/105170468-42edec00-5b1d-11eb-9d45-9f93facc76d4.png)

### Installation method

```
$ chectl version
chectl/0.0.20210115-next.dc032a1 darwin-x64 node-v12.20.1
```

### Environment

my computer / macOS

### Eclipse Che Logs

```
  ❯ 🧪  DevWorkspace engine (experimental / technology preview) 🚨
    ✔ Create Namespace (devworkspace-controller)...Done.
    ✖ Create ServiceAccount devworkspace-controller in namespace devworkspace-controller
      → ENOENT: no such file or directory, open '/Users/mariolet/.local/share/chectl/client/0.0.20210115-next.dc032a1/templates/devworkspace/service_accoun
…
      Create Cluster Role devworkspace-controller
      Create ClusterRole edit-workspaces
      Create ClusterRole view-workspaces
      Create ClusterRoleBinding devworkspace-controller
      Create dev workspace CRDs
      Create dev workspace controller ConfigMap
      Create dev workspace controller
    Retrieving Keycloak admin credentials
    Retrieving Che self-signed CA certificate
    Prepare post installation output
 ›   Error: Error: ENOENT: no such file or directory, open
 ›   '/Users/mariolet/.local/share/chectl/client/0.0.20210115-next.dc032a1/templates/devworkspace/service_account.yaml'
 ›   Command server:deploy failed. Error log: /Users/mariolet/Library/Caches/chectl/error.log
```

### Additional context

Probably it got broken when the dev-workspace operator has been updated to use [Operator SDK v1](https://github.com/devfile/devworkspace-operator/pull/187). Operator yamls have been replaced with kustomize templates so there is no easy way to fix that. 

One option is to generate the operator yaml files when a PR is merged devworkspace side. Those yaml should be published somewhere (gh releases or pages) and retrived by chectl at build time.

Another option is to use kustomize during [chectl build](https://github.com/che-incubator/chectl/blob/master/package.json#L140).

**Comment by sleshchenko** [comment]
It depends on https://github.com/devfile/devworkspace-operator/pull/257

**Comment by sleshchenko** [comment]
https://github.com/devfile/devworkspace-operator/issues/250 is closed now.
https://github.com/devfile/devworkspace-operator/tree/master/deploy/deployment contains flat yamls for deploying Operator on K8s or OpenShift.
