### ISSUE TITLE
Initial Dashboard support for DevWorkspaces

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#18858]
### Is your enhancement related to a problem? Please describe.
We need to investigate work required and begin implementing basic DevWorkspace functionality in the dashboard:
- List current workspaces
- Apply a workspace given a DevWorkspace CR
- Read / Track status of DevWorkspaces

Maybe this can be implemented via a custom factory flow, to avoid having to implement all DevWorkspace features (editing, showing editors, etc.)

A [PR](https://github.com/eclipse/che-dashboard/pull/175) has been submitted to fix this issue but it's currently blocked by the following subtask:

- [x] [Che Server should tell Dashboard if DevWorkspaces are supported or not](https://github.com/eclipse/che/issues/19160)

**Comment by amisevsk** [comment]
Related to https://github.com/eclipse/che/issues/18402

**Comment by l0rd** [comment]
This is currently blocked by https://github.com/eclipse/che/issues/19160

**Comment by sleshchenko** [comment]
It's unblocked, the fix is coming on dashboard side.
