### ISSUE TITLE
Use Git (not git) for app name in docs

### ISSUE THREAD

**Issue by rkratky** [eclipse-che/che#18850]
### Describe the bug

The docs (https://www.eclipse.org/che/docs/) use "git" to refer to "Git" in multiple places. The capitalized form needs to be used when talking about the application/tool. It shouldn't be used when referring to the executable or to various config values etc. Example: "Run `git config` to configure Git credentials."

**Comment by boczkowska** [comment]
Issue in docs Jira https://issues.redhat.com/browse/RHDEVDOCS-2533
