### ISSUE TITLE
Jetty stack/plugin support

### ISSUE THREAD

**Issue by dihlorfos** [eclipse-che/che#18852]
### Is your enhancement related to a problem? Please describe.
There is a need to run my headless RCP app as an isolated Jetty/Equinox container, so it will be possible to use it as a backend. 

### Describe the solution you'd like
The list of standard stacks does not contain any Jetty stack. Please make it possible to create and run the Jetty container as a Che custom plugin (or maybe just Openshift/Kubernetes node?) with some Jetty stack. 

### Describe alternatives you've considered
An alternative was to edit the 'java maven console app' workspace and alter the image in 'DevFile' with some custom Jetty image, but the workspace run failed with error.

### Additional context
I tried to make and use a custom Dockerfile in quay.io with the following contents:
FROM quay.io/eclipse/che-java11-maven:nightly
FROM jetty:11.0.0-jre11-slim

and I also tried https://quay.io/repository/jasonswat/jetty - no luck same exit code=2 error.

**Comment by amisevsk** [comment]
Hi @dihlorfos 

If you want to add a container to run in your workspace, there are a few things that need to be kept in mind:
1. Che workspaces expect containers to be non-terminating; if the entrypoint to your container is some terminating command the workspace will fail to start (the container finishes, Kubernetes restarts it, ad nauseam). Typically this is done by using e.g. `tail -f /dev/null` in the entrypoint.
    - I suspect this is your issue -- when testing `quay.io/jasonswat/jetty:9.4`, I see that the entrypoint is `java -jar /usr/local/jetty/start.jar`, which by default gives
        ```
        ERROR : Nothing to start, exiting ...
        
        Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
               java -jar $JETTY_HOME/start.jar --help  # for more information
        ```
2. If running on OpenShift (or Kubernetes depending on configuration), the container needs to be build to run without root privileges. See subhead "Support arbitrary user ids" [here](https://docs.openshift.com/container-platform/4.6/openshift_images/create-images.html#images-create-guide-openshift_create-images) for a quick rundown

We have an automated script that can convert a given image into one that should work on Che in the [devfile registry](https://github.com/eclipse/che-devfile-registry/tree/master/arbitrary-users-patch). It can be reused by running
```bash
docker build -t <my-image-tag> --build-arg FROM_IMAGE=<image-to-adapt> .
```
This image should then be usable as a [dockerimage component](https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#component-type-dockerimage_che) in your devfile, e.g.:
```yaml
components:
  - type: dockerimage
    image: 'quay.io/amisevsk/che-jetty:9.4-jre11'
    alias: jetty
    mountSources: true
    memoryLimit: 256Mi
    # and any additional config (env vars, ports, etc.)
```

I was able to get a basic workspace up and running on che.openshift.io  by building a Jetty image from the links above:
```bash
cd git/che-devfile/registry/arbitrary-users-patch
docker build -t quay.io/amisevsk/che-jetty:9.4-jre11 --build-arg FROM_IMAGE="jetty:9.4-jre11" .
```
Let me know if this is helpful.

If you would like further info about creating a custom Jetty stack, see the [Che docs](https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-and-configuring-a-new-workspace/).
