### ISSUE TITLE
Go to definition not working in Python stack

### ISSUE THREAD

**Issue by LeapLu** [eclipse-che/che#18853]
I started a workspace in eclipse che which is in public internet (https://che.openshift.io/)
the workspace is django and directly select Python Django Devfile
![image](https://user-images.githubusercontent.com/67357731/105326756-0eeff500-5c09-11eb-9f5d-40fbcca4bb4d.png)
and after I exec the commands of 'setup env' and 'install dependencies', it showed 'Unable to import 'rest_framework.views'pylint(import-error)'
the snapshot is here:
![image](https://user-images.githubusercontent.com/67357731/105327112-7a39c700-5c09-11eb-8d20-6b0d542104d9.png)

![image](https://user-images.githubusercontent.com/67357731/105326703-fed81580-5c08-11eb-953c-686399ba6434.png)

**Comment by ericwill** [comment]
Hello,

I tried to reproduce the issue and couldn't. Here are the steps I took:
1. Run the `set up venv` command.
2. Run the `install dependencies` command
3. Ensure that Che is using the python interpreter from the virtual environment. You can look at the status bar in the bottom left corner, and check that the `.venv` interpreter is being used. If it's not, click on that text and select the interpreter from the `.venv` virtual environment.
![venv](https://user-images.githubusercontent.com/6290632/105360976-302ff180-5bc7-11eb-8978-3c28ef3603b8.png)
4. Open Django files and see that the imports are working correctly.

One thing that I see is missing is that `pylint` is not installed in the virtual environment. That's probably something we can fix.

**Comment by KubeLouis** [comment]
> Hello,
> 
> I tried to reproduce the issue and couldn't. Here are the steps I took:
> 
> 1. Run the `set up venv` command.
> 2. Run the `install dependencies` command
> 3. Ensure that Che is using the python interpreter from the virtual environment. You can look at the status bar in the bottom left corner, and check that the `.venv` interpreter is being used. If it's not, click on that text and select the interpreter from the `.venv` virtual environment.
>    ![venv](https://user-images.githubusercontent.com/6290632/105360976-302ff180-5bc7-11eb-8978-3c28ef3603b8.png)
> 4. Open Django files and see that the imports are working correctly.
> 
> One thing that I see is missing is that `pylint` is not installed in the virtual environment. That's probably something we can fix.

yeah I've got it, but there's another question, I cannot go to definition. click that button named 'Go To Definition' but nothing happened
![image](https://user-images.githubusercontent.com/67357731/105434637-e7e00480-5c96-11eb-9cea-9cdd7e21f2fb.png)

**Comment by svor** [comment]
It seems the problem was fixed:

![screencast-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 02 14-10_56_22](https://user-images.githubusercontent.com/1271546/153831900-e8a88e10-0693-44b5-b6dd-e34d5d9c8d37.gif)
