### ISSUE TITLE
Provide a code coverage report for the devfile and plugin registries

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18851]
### Is your task related to a problem? Please describe.
This is the devfile/plugin registry version of #18621.

### Describe the solution you'd like
Add a code coverage badge to the repository README, or daily report.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by sunix** [comment]
For the che-plugin-registry: https://github.com/eclipse/che-plugin-registry/pull/821

For che-devfile-registry: need to introduce automated test and code coverage for bash scripts: reading https://medium.com/wemake-services/testing-bash-applications-85512e7fe2de looks like https://github.com/bats-core/bats-core is a good candidate.
Discussed during team meeting that we would skip it as things may change for devfile 2.0.

**Comment by ericwill** [comment]
> For che-devfile-registry: need to introduce automated test and code coverage for bash scripts: reading https://medium.com/wemake-services/testing-bash-applications-85512e7fe2de looks like https://github.com/bats-core/bats-core is a good candidate.
> Discussed during team meeting that we would skip it as things may change for devfile 2.0.

Let's skip the devfile registry for now.
