### ISSUE TITLE
tag of che-plugin-registry doesn't contain the up-to-date metadata while the image has

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18855]
### Describe the bug
https://github.com/eclipse/che-plugin-registry/blob/7.25.0/che-editors.yaml#L164 contains a reference to che 7.24.0
while the image published on quay.io https://quay.io/repository/eclipse/che-plugin-registry?tab=tags with 7.25.0 has the correct content

$ docker run --rm -it --entrypoint=sh quay.io/eclipse/che-plugin-registry:7.25.0 -c "ls -la htdocs/v3/plugins/eclipse/che-theia"
drwxrwxr-x 5 root root 4096 Jan 20 17:15 .
drwxrwxr-x 5 root root 4096 Jan 20 17:13 ..
drwxrwxr-x 2 root root 4096 Jan 20 17:15 7.25.0
drwxrwxr-x 2 root root 4096 Jan 20 17:15 latest
-rw-rw-r-- 1 root root    7 Jan 20 17:13 latest.txt
drwxrwxr-x 2 root root 4096 Jan 20 17:15 next

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
 https://github.com/eclipse/che-plugin-registry/blob/7.25.0/che-editors.yaml#L164 

### Expected behavior
tag should have the correct values (the same that have been used to create and publish the image)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by benoitf** [comment]
it's not so important for 7.25.0 if 7.25.1 fixes the problem (and it's fixed onwards)
so you think it's already fixed ?

**Comment by ericwill** [comment]
> it's not so important for 7.25.0 if 7.25.1 fixes the problem (and it's fixed onwards)
> so you think it's already fixed ?

I believe so, the fixes for `make-release.sh` should have fixed it. For example in today's PR we had the correct metadata: https://github.com/eclipse/che-plugin-registry/pull/812

**Comment by benoitf** [comment]
but `7.25.0` tag has been done yesterday including the fix
![image](https://user-images.githubusercontent.com/436777/105367455-c0d6f380-5c00-11eb-856b-499f863aa7a4.png)

This is why I'm unsure it's really fixed

**Comment by ericwill** [comment]
So it looks like there were 3 fixes to the `make-release.sh` script:
![release_fixes_make-release sh](https://user-images.githubusercontent.com/6290632/105381197-bf93cf80-5bdc-11eb-8aa4-fac9cfb1f43f.png)

but `7.25.0` only has two of them:
![7 25 0_missing](https://user-images.githubusercontent.com/6290632/105381231-ca4e6480-5bdc-11eb-82d0-6d8ebf80bb32.png)

**Comment by benoitf** [comment]
@ericwill so we wait 7.25.1 next week and close this issue
or we close now and wait 7.25.1 to re-open if it's still failing ?

**Comment by ericwill** [comment]
> @ericwill so we wait 7.25.1 next week and close this issue
> or we close now and wait 7.25.1 to re-open if it's still failing ?

I'll take a look today and answer once I know a bit better what is going on

**Comment by ericwill** [comment]
So it looks like:
* `git add v3/plugins/eclipse/` was still being used when pushing to the `7.25.0` branch/tag
* this means the updated `sed` changes to `che-editors.yaml` and `che-plugins.yaml` were not committed and pushed
* this is why we have old `7.24.0` references in the generated `meta.yaml` files

Maybe the release was run multiple times? Because the `7.25.0` tag was created in GitHub yesterday, but the PR bumping to `7.26.0-SNAPSHOT` was done today. cc @mkuznyetsov

**Comment by nickboldt** [comment]
Just so we have an assignee, I'm putting Eric on this one as owner... feel free to pass the conch if that's inappropes.

**Comment by ericwill** [comment]
I think this has been fixed in subsequent `7.25.1` and onward releases, no?

**Comment by benoitf** [comment]
yes it is fixed now
Thanks everyonee
