### ISSUE TITLE
Add third dependency SmartGWT to the che

### ISSUE THREAD

**Issue by ywg1990** [eclipse-che/che#1886]
I add third dependency SmartGWT to the che and open a new workspace.  It always stay on this page.

**Reproduction Steps:**
1. add third dependency SmartGWT to che project.
2. modify the pom.xml and IDE.gwt.xml
3. run che, new workspace.
   ![1](https://cloud.githubusercontent.com/assets/20349254/17009837/2cdd5682-4f31-11e6-93cf-af60558fe363.PNG)
   ![2](https://cloud.githubusercontent.com/assets/20349254/17009836/2bae30e2-4f31-11e6-87c0-657921c0bb84.PNG)

*_Che version:4.4.2  
*_OS and version: win7 64  

**Additional information:**
Does che only use the control of GWT？Any other Control？

**Comment by TylerJewell** [comment]
Needs proper description and explanation.  Feel free to open issue outlining complete details.

**Comment by ghost** [comment]
@ywg1990 can you share what exact dependencies did you add?

**Comment by ywg1990** [comment]
@eivantsov I want to use third dependency SmartGWT to develop the example-plugin. I modify the pom.xml and IDE.gwt.xml.
![3](https://cloud.githubusercontent.com/assets/20349254/17240411/fb24530c-559d-11e6-82bb-1ea7475c9d1d.PNG)
![4](https://cloud.githubusercontent.com/assets/20349254/17240412/fbf2824a-559d-11e6-8f84-9f555e0787c7.PNG)

**Comment by ghost** [comment]
@ywg1990 can you share source code of your plugin?

**Comment by ywg1990** [comment]
I use the SmartGWT in a view. Here is my source code.

[ProcessMainViewImpl.java.txt](https://github.com/eclipse/che/files/393536/ProcessMainViewImpl.java.txt)

**Comment by ghost** [comment]
@ywg1990 can you share the entire plugin as a repository so that I can try creating the same assembly?

**Comment by JamesDrummond** [comment]
@ywg1990 Just following up. Were you able to get this working?

**Comment by ywg1990** [comment]
@JamesDrummond Not yet implemented.

**Comment by ywg1990** [comment]
@eivantsov Failed to upload Zip file in GitHub, so I sent you an email. Thanks.

**Comment by ddementieva** [comment]
@ywg1990 Any update on your issue?

**Comment by TylerJewell** [comment]
Closing due to no response >60 days. Ok to reopen if this can be reproduced with the latest versions.

**Comment by hkolvenbach** [comment]
@ywg1990 were you able to solve the problem? i am interested in a solution to this problem as well.
