### ISSUE TITLE
Remove VERSION file in che-docs; keep antora-playbook.yml up to date instead

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18864]
The content of the PR is always false. The master branch contains the documentation for the *released* version of Che but the bot is always trying to update the file to the *next* version. Very confusing.

Example erroneous PR: https://github.com/eclipse/che-docs/pull/1806

I am not aware of any process in che-docs using the VERSION file. We should probably remove it completely to remove a source of confusion.

The only relevant place to define the Che version should be in https://github.com/eclipse/che-docs/blob/master/antora-playbook.yml

```
    prod-prev-ver-major: 6
    prod-prev-ver: 7.22
    prod-ver-major: 7
    prod-ver: 7.23
    prod-ver-patch: 7.23.2
```

If we want to keep an automated process, please make sure it is setting the *released* version of Che in `antora-playbook.yml` (as well as the previous version).

**Comment by nickboldt** [comment]
I suspect that fixing this issue will also mean that pages like https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-and-configuring-a-new-workspace/ will be up to date (and thus show 7.25 instead of 7.23)

**Comment by boczkowska** [comment]
Jira docs issue https://issues.redhat.com/browse/RHDEVDOCS-2538

**Comment by nickboldt** [comment]
PR for making playbook current w/ every weekly release: https://github.com/eclipse/che-docs/pull/1823
