### ISSUE TITLE
Use the che-docs container for github workflow actions in che-docs

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18865]
In order to have every process in  che-docs use exactly the same version of the tools, use the `quay.io/eclipse/che-docs` container in GitHub workflow actions for all processes that have tools built in the che-docs containers:
* Execute antora
* Execute vale
* Execute linkchecker
* Execute bash scripts

**Comment by nickboldt** [comment]
Current release action:

https://github.com/eclipse/che-docs/blob/master/.github/workflows/release.yml

which just runs:

https://github.com/eclipse/che-docs/blob/master/make-release.sh 

to perform tagging/branching/updating the VERSION file (which will be changed to the playbook file in https://github.com/eclipse/che/issues/18864).

So... 

are you saying we should update a different workflow action?

* https://github.com/eclipse/che-docs/blob/master/.github/workflows/build-pr-docs.yaml#L22
* https://github.com/eclipse/che-docs/blob/master/.github/workflows/link-checker.yaml#L23
* https://github.com/eclipse/che-docs/blob/master/.github/workflows/publish-netlify.yaml ?

**Comment by themr0c** [comment]
Yes that's not for the release script but for the other ones!

**Comment by nickboldt** [comment]
So instead of 
```
           yarn
           ./node_modules/.bin/antora generate antora-playbook.yml
```

what are you suggesting should be done instead? How do you want `quay.io/eclipse/che-docs` used?

**Comment by themr0c** [comment]
What we do in devfile and Jenkinsfile: run antora / linkchecker / vale directly in the `quay.io/eclipse/che-docs` container.
For vale it's also quite important to keep same version because of some surprises with upgrades.

**Comment by boczkowska** [comment]
Issue in docs Jira https://issues.redhat.com/browse/RHDEVDOCS-2537

**Comment by themr0c** [comment]
Exemple of surprise: linkchecker running fine using the che-docs image, broken using the official and outdated linkchecker image: https://github.com/eclipse/che-docs/pull/1801

**Comment by themr0c** [comment]
Example:

In the middle, linkchecker executed using che-docs container.
On the right, linkchecker executed using linkchecker/lickchecker container.

Options are not taken into account, a big subset of the URLs is not checked:

![Screenshot from 2021-01-26 15-27-47](https://user-images.githubusercontent.com/243761/105858817-0a9e5000-5fec-11eb-8236-912541ded9d9.png)


![Screenshot from 2021-01-26 15-33-23](https://user-images.githubusercontent.com/243761/105858718-ed698180-5feb-11eb-8403-11b762f0975e.png)

**Comment by benoitf** [comment]
@themr0c should we close this issue as you've done by yourself some enhancements ?

**Comment by themr0c** [comment]
You helped a lot. I just checked, seems we are good yes.
