### ISSUE TITLE
[new UD] Create a health check for the registry URL

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#18867]
### Is your enhancement related to a problem? Please describe.

We have the ability to add a new registry and there is only the regex URL validation. A typo can happen while adding a registry URL so it will point to a non-existing address.
### Describe the solution you'd like

We should add an ability to check the registry URL on a button click for example.

### Additional context

The current state without a health check for the registry URL.

![Screenshot from 2021-01-22 17-38-39](https://user-images.githubusercontent.com/6310786/105511551-ae2fed80-5cd8-11eb-93d7-9c4b9e2141c2.png)

**Comment by olexii4** [comment]
![Screenshot from 2021-01-25 16-14-59](https://user-images.githubusercontent.com/6310786/106028645-de123300-60d4-11eb-932d-667d4c913b55.png)

**Comment by sleshchenko** [comment]
Users may want to configure credentials for private registries, which are not available from the browser (temporary if VPN is disabled or persistently if it's cluster internal registry, which may have authentication as well)

**Comment by sleshchenko** [comment]
I misunderstood https://github.com/eclipse/che/issues/18867#issuecomment-768442762 and thought Save button is disabled when the url is not reachable. So, it's fine
