### ISSUE TITLE
E2E Happy path tests are failing while waiting for workspace readiness

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18876]
### Describe the bug
E2E Happy path tests are failing while waiting for workspace readiness:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/4377/console

```
  Validation of workspace start
          ▼ DriverHelper.navigateToUrl https://che-eclipse-che.10.0.102.227.nip.io/dashboard/#/ide/admin/petclinic-dev-environment
  [WARN] PreferencesHandler.setPreference could not set theia-user-preferences from api/preferences response, forcing manually.
          ▼ PreferencesHandler.setTerminalToDom
          ▼ MultiUserLoginPage.login
          ▼ CheLoginPage.waitEclipseCheLoginFormPage
          ▼ CheLoginPage.inputUserNameEclipseCheLoginPage username: "admin"
          ▼ CheLoginPage.inputPaswordEclipseCheLoginPage password: "admin"
          ▼ CheLoginPage.clickEclipseCheLoginButton
    ✓ Open workspace (3867ms)
          ▼ Ide.waitAndSwitchToIdeFrame
          ▼ Ide.waitPreloaderVisible
    1) Wait for workspace readiness
  [ERROR] CheReporter runner.on.fail: Validation of workspace start Wait for workspace readiness failed after 722912ms


  1 passing (12m)
  1 failing

  1) Validation of workspace start
       Wait for workspace readiness:
     TimeoutError: Exceeded maximum visibility checkings attempts for 'By(css selector, .theia-preload)' element, timeouted after 360000
      at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:152:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

![screenshot-Wait_for_workspace_readiness (1)](https://user-images.githubusercontent.com/1197777/105695045-43fe8f00-5f0a-11eb-8d39-fe82776efd22.png)

The issue has affected PR Happy path tests, therefor it's kind of blocker.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context
Latest changes: Dashboard Next https://github.com/eclipse/che/issues/18391

**Comment by Ohrimenko1988** [comment]
Done: https://github.com/eclipse/che/pull/18428
