### ISSUE TITLE
Che Theia improvements to support DevWorkspace configuration

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18874]
### Is your enhancement related to a problem? Please describe.

When Che uses the DevWorkspace operator as the workspace engine, Che Theia should not use Che server API.

### Describe the solution you'd like

Decouple Che Theia from the Che server API to retrieve config and runtime information.

**Comment by benoitf** [comment]
che-theia is now supporting k8s API in all Theia/Che-Theia extensions.
For milestone 2, work will done for plug-ins.
