### ISSUE TITLE
Is there any way to use service instead of ingress for communicating between che server and theia?

### ISSUE THREAD

**Issue by mtsmfm** [eclipse-che/che#18872]
## Summary

Currently, it seems `serverResolver` returns ingress host name.

https://github.com/eclipse/che/blob/83d797f67fb4ee9932405e585144030f8165beac/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntime.java#L870

k8s pods may not be able to reach to ingress via che's domain.
For example, `chectl server:deploy --platform=docker-desktop` on WSL2 sets che domain as `https://che-eclipse-che.<wsl2 machine ip>.nip.io` but WSL2 and k8s use different private network.

## Relevant information

Not only theia, but also che-plugin-broker should be connected via service I think.
I guess these communication issues related to this problem.

https://github.com/eclipse/che/issues/18582
https://github.com/eclipse/che/issues/16439

**Comment by tolusha** [comment]
@mtsmfm
Hello.
That's possible since Eclipse Che 7.23.0 if you use operator as installer.
For helmcharts it is added since Eclipse Che 7.24.0.

**Comment by mtsmfm** [comment]
@tolusha Can I ask you to tell me the option to do so?

**Comment by mtsmfm** [comment]
> Services (by default) is used for inter-component communication

As I described in https://github.com/eclipse/che/issues/18674, che-plugin-broker still refers ingress, not service even che 7.23.1. And 7.24.2 also doesn't.

**Comment by tolusha** [comment]
This aspect slipped from us.
Plugin broker does use public endpoint to communicate with che but uses services to communicate with plugin-registry

```
2021/01/26 07:47:05 Broker configuration
2021/01/26 07:47:05   Push endpoint: wss://che-eclipse-che.192.168.99.100.nip.io/api/websocket
2021/01/26 07:47:05   Auth enabled: true
2021/01/26 07:47:05   Runtime ID:
2021/01/26 07:47:05     Workspace: workspacep5lsy64k3uajyq6m
2021/01/26 07:47:05     Environment: default
2021/01/26 07:47:05     OwnerId: 13f988ed-31c6-49cc-9538-14772c7c948b
2021/01/26 07:47:05   Self signed certificate /tmp/che/secret/ca.crt
2021/01/26 07:47:05   CA bundle certificates path /public-certs
2021/01/26 07:47:05 Starting plugin artifacts broker
2021/01/26 07:47:05 Fetching plugin meta.yaml from http://plugin-registry.eclipse-che.svc:8080/v3/plugins/redhat-developer/che-omnisharp-plugin/latest/meta.yaml
2021/01/26 07:47:05 Fetching plugin meta.yaml from http://plugin-registry.eclipse-che.svc:8080/v3/plugins/redhat-developer/netcoredbg-theia-plugin/latest/meta.yaml
2021/01/26 07:47:05 Fetching plugin meta.yaml from http://plugin-registry.eclipse-che.svc:8080/v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
2021/01/26 07:47:05 Fetching plugin meta.yaml from http://plugin-registry.eclipse-che.svc:8080/v3/plugins/eclipse/che-theia/next/meta.yaml
2021/01/26 07:47:05 Cleaning /plugins dir
2021/01/26 07:47:05 Processing plugin redhat-developer/che-omnisharp-plugin/latest
2021/01/26 07:47:05   Installing plugin extension 1/1
2021/01/26 07:47:05     Downloading plugin from https://github.com/redhat-developer/omnisharp-theia-plugin/releases/download/v0.0.6/omnisharp_theia_plugin.theia
2021/01/26 07:47:34 Processing plugin redhat-developer/netcoredbg-theia-plugin/latest
2021/01/26 07:47:34   Installing plugin extension 1/1
2021/01/26 07:47:34     Downloading plugin from https://github.com/redhat-developer/netcoredbg-theia-plugin/releases/download/v0.0.3/netcoredbg_theia_plugin.theia
2021/01/26 07:47:38 Saving log of installed plugins
2021/01/26 07:47:38 All plugin artifacts have been successfully downloaded
```

**Comment by tolusha** [comment]
TODO: helmcharts
