### ISSUE TITLE
Implement proper tag recreation option for release scripts

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#18879]
### Is your task related to a problem? Please describe.
By default, we shouldn't recreate tags/branches every time we launch a release script for the Che project,
However in some cases, regeneration of tags/branches is a must, so this should be added to the workflow as an optional parameter (since it must be used with caution)
This behaviour should become consistent across of all projects, that are being released.

- [x] che-theia - https://github.com/eclipse/che-theia/blob/master/.github/workflows/release.yml - forceRecreateTags
- [x] che-machine-exec - https://github.com/eclipse/che-machine-exec/blob/master/.github/workflows/release.yml (to be renamed from .yaml) forceRecreateTags
- [x] che-devfile-registry - https://github.com/eclipse/che-devfile-registry/blob/master/.github/workflows/release.yml  - forceRecreateTags
- [x] che-plugin-registry - https://github.com/eclipse/che-plugin-registry/blob/master/.github/workflows/release.yml  - forceRecreateTags
- [x] che-parent + server - https://github.com/eclipse/che/blob/master/.github/workflows/release.yml - forceRecreateTags
- [x] che-dashboard - https://github.com/eclipse/che-dashboard/blob/master/.github/workflows/release.yml  - forceRecreateTags
- ~~che-workspace-loader~~ - project is deprecated
- [x] che-operator - https://github.com/eclipse/che-operator/blob/master/.github/workflows/release.yml - to refactor force_update to forceRecreateTags so we have the same block-release-if-tag-exists flow
- [x] chectl - https://github.com/che-incubator/chectl/blob/master/.github/workflows/release.yml  - forceRecreateTags

**Comment by nickboldt** [comment]
Any progress here? it's been a couple months :(

**Comment by nickboldt** [comment]
Seems that some of this is now done. @mkuznyetsov please update w/ latest status.

**Comment by nickboldt** [comment]
Theia and chectl appear to be done. Others TBD. Some renaming/refactoring to be done - see above.

**Comment by nickboldt** [comment]
PR for operator to use the same block-if-version-exists logic: https://github.com/eclipse-che/che-operator/pull/748
PR to rename che-machine-exec's release.yml for consistency: https://github.com/eclipse-che/che-machine-exec/pull/144

**Comment by mkuznyetsov** [comment]
all affected projects have the implementation
