### ISSUE TITLE
Dashboard should add a routing class when creating a DevWorkspace

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#18886]
### Is your task related to a problem? Please describe.

As part of the DevWorkspace integration into the dashboard, we will need to find a way automatically set the routing class when creating a che workspace

### Describe the solution you'd like

Before the DevWorkspace is created set the routing class

### Describe alternatives you've considered

None

**Comment by sleshchenko** [comment]
fixed by https://github.com/che-incubator/devworkspace-client/pull/11
