### ISSUE TITLE
Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18884]
### Describe the bug

Windows 10

Chectl cannot update due to `Error: Cannot find module 'chalk'`

### Che version

 - [  ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

`Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://www.eclipse.org/che/chectl/win/'))`

`chectl update`

```
Error: Cannot find module 'chalk'
    at Object.<anonymous> (C:/Users/gnoej/AppData/Local/chectl/client/0.0.20200410-next.f7851be/node_modules/@oclif/color/lib/index.js:4:17)
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ x ] other: (please specify): Windows 10 Version	10.0.18363 Build 18363

### Installation method
   - [ x ] chectl
   -  `chectl update`
   -  `chectl/0.0.20200410-next.f7851be win32-x64 node-v10.20.0`
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs

No logs created

**Comment by flacatus** [comment]
Hi @gnoejuan .
Are you using `git bash` with chectl. I have a similar issue using git bash.
Using Powershell or CMD I'm not able to reproduce your issue. I can deploy successfully Che.

**Comment by gnoejuan** [comment]
Sorry for the late response!

Powershell version

```
└[~]> (Get-Host).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      1      3      -1
```

chectl version 

```
chectl/0.0.20200410-next.f7851be win32-x64 node-v10.20.0

```

```
└[~]> chectl update
Error: Cannot find module 'chalk'
    at Object.<anonymous> (C:/Users/gnoej/AppData/Local/chectl/client/0.0.20200410-next.f7851be/node_modules/@oclif/color/lib/index.js:4:17)
```

manually updated just now:

```
┌[gnoej]
└[C:\ProgramData\chectl]> chectl version
chectl/0.0.20200410-next.f7851be win32-x64 node-v10.20.0
┌[gnoej]
└[C:\ProgramData\chectl]> chectl update
Error: Cannot find module 'chalk'
    at Object.<anonymous> (C:/Users/gnoej/AppData/Local/chectl/client/0.0.20200410-next.f7851be/node_modules/@oclif/color/lib/index.js:4:17)

```

**Comment by tolusha** [comment]
@gnoejuan 
Could you try to reinstall `chectl` to check if problem gone
`bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next`

**Comment by gnoejuan** [comment]
Since this is for powershell, I assume you meant

`$CHANNEL="next"; Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://www.eclipse.org/che/chectl/win/'))`

```
VERSION
  chectl/0.0.20200410-next.f7851be win32-x64 node-v10.20.0
```

But, I did run `bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next` in git bash too, 

```
gnoej@Power MINGW64 ~
$ bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next
bash: /dev/fd/63: No such file or directory
```

**Comment by gnoejuan** [comment]
I have factory reset my computer and I'm not encountering this bug. One thing I did not install was nvm, node-version-manager

But that doesn't make sense to me, since the error has a reference to chalk in the chectl directory. Unless nvm was interfering with chectl installing its own chalk.

Nonetheless, I believe since I'm not encountering the bug, this issue can be closed.

**Comment by tolusha** [comment]
@gnoejuan 
Thank you for letting us know.
