### ISSUE TITLE
Flag to skip Microk8s check for remote deployments

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18883]
### Is your enhancement related to a problem? Please describe.

Deploying from one computer to a remote server, chectl stops after `× Verify if microk8s is installed`. 

A flag to skip that check would be nice. I assume it would be a microk8s specific command

**Comment by tolusha** [comment]
@gnoejuan 
Are you interested in contributing?

**Comment by gnoejuan** [comment]
I am interested, yes. How can I help?

**Comment by tolusha** [comment]
I think we don't need any flags.
If you deploy Eclipse Che on a remove server we can simply use:
`chectl server:deploy --platform k8s --domain <..> ...`
Could you check this pls?

**Comment by gnoejuan** [comment]
```--platform k8s --domain <..> ```

Works. While that seems obvious, ~~I do request a small note added to~~

Oh, there is no microk8s [documentation](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-locally/)

I see there is a issue for improved microk8s support https://github.com/eclipse/che/issues/14455 . . . would that be the appropriate place to ask for documentation?

**Comment by tolusha** [comment]
Sure, you can ask in https://github.com/eclipse/che/issues/14455 for a documentation
