### ISSUE TITLE
Setup of the DevWorkspace version of the Happy path e2e test

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18888]
### Is your enhancement related to a problem? Please describe.

That's related to https://github.com/eclipse/che/issues/17307

### Describe the solution you'd like

We should start testing DevWorkspace based workspaces. Note that, at first, editors plugins won't be supported.

**Comment by dmytro-ndp** [comment]
Actually, the issue is blocked by https://github.com/eclipse/che/issues/18842

**Comment by rhopp** [comment]
# Meeting 2021-09-02

## Target infra
 - Mario told us that first target is Openshift - beacuse of Theia auth (`Authentication supported on OpenShift only (because we require OpenShift OAuth)`)
 - lkrejci is now developing that using minikube
 - How should we select the target CI/infra to run the test given it should run against Openshift?
     - github actions :x: 
         - :heavy_minus_sign: We can't run any openshift there
         - :heavy_plus_sign: github "native" way these days
         - :heavy_plus_sign: Relatively simple development
     - Run on qe jenkins behind VPN :shrug: 
         - :heavy_plus_sign: Relatively easy for us to do
         - :heavy_plus_sign: We can use QE's OCP clusters running in PSI
         - :heavy_minus_sign: It's behind VPN - not good for upstream
         - :heavy_minus_sign: More workload on our self-managed infrastructure.
     - openshift-ci :shrug: 
        - :heavy_plus_sign: OCP clusters "for free" without any hassle
        - :heavy_plus_sign: Basically canonical way how to test on openshift
        - :heavy_minus_sign: We need to migrate repos (work associated) (not 100% necessary until end of Q1 at least)

## Scenario
0. Build the project(repo)
2. Prepare infra
    - Start or get access to running OCP cluster
    - Downolad & install chectl (next)
    - Download & install oc client
3. Install che
    - chectl server:deploy (`--workspace-engine=dev-workspace` is important here)
    - wait for che to be running (for chectl command to succesfully finish)
4. [Run Factory UI test](https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e/FactoryUrl.spec.ts) (might need to be created/modified?)
    a. Access the factory URL
    b. Wait for the workspace to be ready.
    - @Sergii needs to figure out which devfile we should use.


## Next meeting:
- @Sergii will try the scenario on our internal OCP4, will get more familiar with how DevWroskapce engine works (ask lkrejci how to deploy, when chectl is not working #18842)
- @Radim will write down steps required to be able to run this on openshift-ci
- @Radim will possibly raise this topic on Internal Call (maybe the migration in general)
    - Select which repo will be the best candidate for first implementation.

**Comment by rhopp** [comment]
# Update from today's meeting with @SkorikSergey and @dmytro-ndp:
- We will try to use openshift-ci
- This PR check will be probably implemented first in github.com/devfile/devworkspace-operator repo

## Action items:
 - [ ]  @SkorikSergey Will get in touch with controller team to figure out who to run Che with custom version of DevWorkspace operator (from the PR). Ideally using chectl (to cover whole story)
 - [ ] @SkorikSergey @rhopp will get more familiar with openshift-ci
   - https://github.com/openshift/release/tree/master/ci-operator
   - https://docs.ci.openshift.org/docs/
   - Flavius has some experience, so we can use his knowledge ;-)
   - AI: @SkorikSergey  try creating WIP/Draft PR into openshift-ci adding simple job (hello world?)

**Comment by SkorikSergey** [comment]
@sleshchenko I tried to install **devworkspace-operator** on Openshift 4.7 from [devworkspace-operator](https://github.com/devfile/devworkspace-operator) repo and created a workspace from [flattened_theia-nodejs.yaml](https://github.com/devfile/devworkspace-operator/blob/main/samples/flattened_theia-nodejs.yaml) yaml. It works as expected. 

But when I try to deploy Eclipse Che there is a problem with starting **keycloak** pod:
<code>
time="2021-02-23T06:45:15Z" level=info msg="Running exec for 'create Keycloak DB, user, privileges' in the pod 'postgres-5d89dfd896-6sqml'"
time="2021-02-23T06:45:15Z" level=error msg="Error running exec: Internal error occurred: failed calling webhook \"validate-exec.devworkspace-controller.svc\": Post \"https://devworkspace-webhookserver.devworkspace-controller.svc:443/validate?timeout=30s\": service \"devworkspace-webhookserver\" not found, command: [/bin/bash -c OUT=$(psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='keycloak'\"); if [ $OUT -eq 1 ]; then echo \"DB exists\"; exit 0; fi && psql -c \"CREATE USER keycloak WITH PASSWORD 'PBq31Ua3B9kc'\" && psql -c \"CREATE DATABASE keycloak\" && psql -c \"GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak\" && psql -c \"ALTER USER ${POSTGRESQL_USER} WITH SUPERUSER\"]"
time="2021-02-23T06:45:15Z" level=error msg="Stderr: "
</code>

And only **devworkspace-operator** uninstalling helps. It is block us for using this Openshift 4 for other Eclipse Che deployments.

**Comment by sleshchenko** [comment]
It seems that devworkspace operator is not installed properly or partially uninstalled.

**Comment by l0rd** [comment]
@rhopp @SkorikSergey @dmytro-ndp what's the status of this epic? I see that a PR has been merged. Should we close this epic or should I move it to next milestone?

**Comment by SkorikSergey** [comment]
[[Selenium] Add DevWorkspaceHappyPath e2e typescript test](https://github.com/eclipse/che/pull/19152) PR added simple 'happy-path' test to check workspace created by devworkspace-controller. Next step is "testing DevWorkspace based workspaces" automation on openshift-ci.

**Comment by SkorikSergey** [comment]
DevWorkspace happy-path test starts as PR checker in `che-operator repo` and nightly. Test results are on [prow.ci.openshift.org](https://prow.ci.openshift.org/?repo=eclipse-che%2Fche-operator).
