### ISSUE TITLE
On PR, check all shell scripts in che-docs with shellcheck

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18898]
On pull request, validate with ShellCheck all shell scripts in che-docs located in the `tools` directory. 

Optionally, validate only scripts that are modified by the PR.

If we still don't have ShellCheck in the che-docs container, it is fine using the official container published by https://github.com/koalaman/shellcheck, else use the quay.io/eclipse/che-docs container. See https://github.com/eclipse/che/issues/18899.

**Comment by boczkowska** [comment]
Docs team Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2657
