### ISSUE TITLE
.NET test failing on LS issues

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18891]
### Describe the bug
.NET Core devfile test is failing some times on LS features. When tested manually, LS seems to work fine, it just takes more time to load up. A possible solution should be increasing the timeout for .NET LS tests.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run .NET Core devfiel test against Hosted Che.

### Expected behavior
If the LS feature is not broken, the test should pass.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) Hosted Che
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify) 

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/105839654-1ed55380-5fd2-11eb-95b9-9a2392c060be.png)
![image](https://user-images.githubusercontent.com/29278800/105839683-2694f800-5fd2-11eb-9019-398a82831a52.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know - Hosted Che

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify Hosted Che

**Comment by ibuziuk** [comment]
@Katka92 is the issue still relevant in the context of upstream / product?

**Comment by Katka92** [comment]
@ibuziuk yes, the issue is still present in upstream devfile tests.
