### ISSUE TITLE
IDE doesn't change state after workspace start from context menu

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#1889]
**Reproduction steps:**
1. Open a workspace
2. Stop it form main menu (Workspace -> Stop) and wait for workspace start/create dialog window
3. Run workspace using context menu on the dashboard panel

**Expected behavior:**

Workspace start/create dialog window should disappear and IDE must be opened

**Observed behavior:**

Workspace started successfully, but IDE is stuck.
After page refresh or reopen this (already running) workspace from dashboard all works correctly

**Che version:**   4.6.0-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**  tomcat server

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by JamesDrummond** [comment]
@mmorhun Please assign and provide status label.

**Comment by TylerJewell** [comment]
This issue is not actual anymore.
