### ISSUE TITLE
After switching to auto-generated plugin registry, the plugin icons were reset to default icon

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#18908]
### Describe the bug

At the moment, a set of `meta.yaml` files for the plugin registry is automatically generated when building the registry and based on
- [che-theia-plugins.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml)
- [che-plugins.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/che-plugins.yaml)
- [che-editors.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml)

When building the registry, the build script is downloading the extensions and extracts the icons to `/v3/images` directory.
In the plugin `meta.yaml` the icon URI refers to the icon from that directory
```
icon: /v3/images/atlassian-atlascode-icon.png
```

Related URI is not jet supported by Che-Theia.
The icon URI (`/v3/images/atlassian-atlascode-icon.png`) is used as it is, what forces to display the default icon instead.
![Screenshot from 2021-01-27 17-08-43](https://user-images.githubusercontent.com/1655894/106016357-0fd0cd00-60c8-11eb-823f-03388541b6bb.png)

The plugin registry root should be taken into account when getting/forming the icon URI.

### Che version

 - [x] nightly
 - [x] latest

**Comment by ericwill** [comment]
@vitaliy-guliy please backport this to `7.26.x`
