### ISSUE TITLE
C/C++ test artifacts not saved

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18904]
### Describe the bug
When the C/C++ devfile test fails, the artifacts are not saved. I think that it is happening due to the slash in the test name. We had a similar problem when the test was starting with a dot - `.Net Core`. 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Run a C/C++ devfile test and set the timeout for workspace creation to few seconds, so it's sure that the test will fail.

### Expected behavior
Artifacts should be generated and saved.

**Comment by Katka92** [comment]
@ScrewTSW @Warfvf Is it still an issue or should it be safely closed?

**Comment by Warfvf** [comment]
Yes, there is still an error: `Error: ENOENT: no such file or directory, mkdir './report/C/C++_test_Create_C/C++_workspace_Wait_for_workspace_readiness'`

**Comment by Katka92** [comment]
Thanks, for the info @Warfvf!

**Comment by ScrewTSW** [comment]
Issue has been fixed using Sanitizer implementation, closing.
https://github.com/eclipse/che/commit/9d947842ed49d176b8d8dd7a387d6e9bf77d462b#diff-b1650117ae04112b8b387fe820270cd338a7dc23568783ace70682d9f23922e0
