### ISSUE TITLE
Add vscode-shellcheck plugin in che-docs devfile

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18900]
Add vscode-shellcheck plugin in che-docs devfile.
If necessary, make sure the plugin is available in the plugin-registry.
See:   https://github.com/timonwong/vscode-shellcheck

**Comment by ericwill** [comment]
Yep, it's in the registry:

https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml#L492-L500
and 
https://che-plugin-registry-main.surge.sh/v3/plugins/timonwong/shellcheck/0.10.1/meta.yaml

**Comment by themr0c** [comment]
So all what we need is to add this in devfile, am I correct?

```
  - id: timonwong/shellcheck/latest
    type: chePlugin
```

**Comment by ericwill** [comment]
> So all what we need is to add this component in devfile, am I correct?
> 
> ```
>   - id: timonwong/shellcheck/latest
>     type: chePlugin
> ```

As I understand it, it would be

```yaml
- type: chePlugin
  id: timonwong/shellcheck/latest
```

**Comment by boczkowska** [comment]
Docs team Jira https://issues.redhat.com/browse/RHDEVDOCS-2656
