### ISSUE TITLE
Dashboard: loading devfile from a github project with no devfile is failing

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18919]
### Describe the bug
Load devfile action is failing to load a github repo with no devfile.

### Che version

 - [x] latest 7.24.0

### Steps to reproduce
1. Click `Create Workspace`
2. Set `https://github.com/eclipse/che-devfile-registry/` as `URL of devfile`
3. Click on `Load devfile`
4. It is showing `Load devfile failed.`

### Expected behavior
It should
- tell the user that the devfile couldn't be found in the repo
- load an empty devfile with just the project to clone

### Screenshots
![Selection_182](https://user-images.githubusercontent.com/650571/106256729-efb22280-621b-11eb-9661-6ad86fe14061.png)

### Additional context
using the 'old' dashboard, have not tested the new one.

**Comment by sleshchenko** [comment]
The same issue is actual for Create Custom Workspace page on a new Dashboard, but the flow of using repo without devfile should be better after https://github.com/eclipse/che/issues/18975
