### ISSUE TITLE
How do I deploy Che to docker-desktop's Kubernetes?

### ISSUE THREAD

**Issue by fbricon** [eclipse-che/che#18913]
### Describe the bug
I've been trying to figure out how to install che on my docker-desktop's Kubernetes instance, on my Mac.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

I found https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-docker-desktop/ that links to  https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1 which leads to the homepage, so no instructions.

I tried to wing it, after installing chectl:

```
❯ chectl server:start
› Current Kubernetes context: 'docker-desktop'
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
 ›   Warning: Eclipse Che has not been deployed yet. Use server:deploy command to deploy a new Eclipse Che instance.
❯ chectl server:deploy
› Current Kubernetes context: 'docker-desktop'
› Installer type is set to: 'operator'
Enable CLI usage data to be sent to Red Hat online services. [y/n]: y
  ✔ Verify Kubernetes API...OK
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✖ ✈️  Platform preflight checklist
    → Platform is required ¯\_(ツ)_/¯
 ›   Error: Error: Platform is required ¯\_(ツ)_/¯
 ›   Command server:deploy failed. Error log: /Users/fbricon/Library/Caches/chectl/error.log Eclipse Che logs: /var/folders/lj/syy7z_ln77gbg1184g62krm40000gn/T/chectl-logs/1611825651685
```

`Platform is required ¯\_(ツ)_/¯` was very helpful. not. Nothing in the chectl help provides any instructions related to platform

Eventually @sunix gave me the proper blog post URL with updated (Jan. 2020) instructions (https://medium.com/eclipse-che-blog/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1).

Then it kept failing:
```
❯ chectl server:start --platform=docker-desktop --installer=helm
› Current Kubernetes context: 'docker-desktop'
 ›   Error: Unexpected arguments: --platform=docker-desktop, --installer=helm
 ›   See more help with --help
```

### Expected behavior
- Instructions to run Che on local docker desktop should be easily accessible (no dead link)
- Error message should be more helpful than  `Platform is required ¯\_(ツ)_/¯`.
- instructions should be updated (again)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
```
❯ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"299b6af", GitTreeState:"clean", BuildDate:"2020-11-26T04:01:17Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [ x] chectl

### Environment
   - [x ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS

**Comment by flacatus** [comment]
Hello @fbricon !
To deploy a new instance of Eclipse Che please try `server:deploy`.

Can you try to use for your case `chectl server:deploy --platform=docker-desktop --installer=helm` instead, please?

**Comment by fbricon** [comment]
@flacatus yeah it's in the bug report

**Comment by fbricon** [comment]
@flacatus ok my bad, I should use my glasses sometimes. 
`chectl server:deploy --platform=docker-desktop --installer=helm instead of server:start` worked, after I installed helm

Command server:deploy has completed successfully in 02:53.

**Comment by fbricon** [comment]
Link to instructions to load certificates in browsers is invalid: https://www.eclipse.org/che/docs/che-7/overview/importing-certificates-to-browsers/ => 404

**Comment by flacatus** [comment]
@fbricon Can you try to access https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-certificates-to-browsers/ docs?
We are providing a fix in chectl side

**Comment by fbricon** [comment]
link works
