### ISSUE TITLE
Unable to access Artik IDE at the URL (Unauthorized message on the browser)

### ISSUE THREAD

**Issue by blackbird1989** [eclipse-che/che#1892]
[Problem Description]
I am trying to set up the Artik IDE using Vagrant installer on my Windows machine. When i run vagrant provision, it shows me the following log,

D:\artik>vagrant provision
ARTIK IDE: VAGRANT INSTALLER
ARTIK IDE: REQUIRED: VIRTUALBOX 5.x
ARTIK IDE: REQUIRED: VAGRANT 1.8.x

==> artik: Configuring proxy for Docker...
==> artik: Configuring proxy environment variables...
==> artik: Configuring proxy for Yum...
==> artik: Running provisioner: shell...
    artik: Running: inline script
==> artik: -----------------------------------
==> artik: .
==> artik: ARTIK IDE: CONFIGURING SYSTEM PROXY
==> artik: .
==> artik: -----------------------------------
==> artik: HTTP PROXY set to: http://10.20.8.190:808
==> artik: HTTPS PROXY set to: https://10.20.8.190:808
==> artik: ----------------------------------
==> artik: ARTIK IDE: UPGRADING DOCKER ENGINE
==> artik: ----------------------------------
==> artik: #
==> artik: #
==> artik: #
==> artik: #
==> artik: #
==> artik: #
==> artik: #
==> artik: Docker version 1.11.1, build 5604cbe
==> artik: mkdir: cannot create directory `/etc/systemd/system/docker.service.d'
: File exists
==> artik: --------------------------------------
==> artik: ARTIK IDE: DOWNLOADING ARTIK IDE IMAGE
==> artik: --------------------------------------
==> artik: #
==> artik: ----------------------------------------
==> artik: .
==> artik: ARTIK IDE: DOWNLOADING ARTIK RUNTIME SDK
==> artik:            (950MB TOTAL DOWNLOAD SIZE)
==> artik: .
==> artik: ----------------------------------------
==> artik: #
==> artik: ------------------------------
==> artik: ARTIK IDE: BOOTING ECLIPSE CHE
==> artik: ------------------------------
==> artik: Configuring proxy for Docker...
==> artik: Running provisioner: shell...
    artik: Running: inline script
==> artik: #
==> artik: ----------------------------------------
==> artik: ARTIK IDE: BOOTED AND REACHABLE
==> artik: ARTIK IDE: http://192.168.28.200:8261
==> artik: ----------------------------------------
==> artik: Configuring proxy for Docker...
D:\artik>

**Observed behavior:**
When i access the URL , http://192.168.28.200:8261 , i get the below message on my browser,
**Unauthorized ...
IP Address: 10.20.8.48
MAC Address:
Server Time: 2016-07-15 09:48:31
Auth Result: Auto disabled at 2** 

**Che version:** latest 

**OS and version:** Windows 8 (64-bit)

**Docker version:**
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

**Che install:**    [Vagrant]   

**VirtualBox version:**  Version 5.0.20 r106931

**Java version:**
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**Docker info**
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 1
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:3
6:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: BB45:HW52:G2EB:LYOB:6P36:IEXU:MNFQ:WRHK:KWBB:DANV:ZLD4:YRDX
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 37
 System Time: 2016-07-19T08:48:44.582911088Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

**Comment by ghost** [comment]
@blackbird1989 you have got proxy variables. Do you have an opportunity to try it without proxies?

UPD: I have tested the installer on a Win 8 machine with VirtualBox - no errors occured. I wonder if this is a proxy issue.

**Comment by merin1989** [comment]
I tried without proxies. When i access the URL on the browser, it shows me a black screen with a loading symbol but it's stuck there and doesn't complete loading. 

The output of curl command is as follows,
[vagrant@localhost ~]$ curl -v http://192.168.28.200:8261/dashboard
* About to connect() to 192.168.28.200 port 8261 (#0)
*   Trying 192.168.28.200...
* Connected to 192.168.28.200 (192.168.28.200) port 8261 (#0)
> GET /dashboard HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.28.200:8261
> Accept: */*
>
< HTTP/1.1 302 Found
< Server: Apache-Coyote/1.1
< Location: /dashboard/
< Transfer-Encoding: chunked
< Date: Fri, 29 Jul 2016 12:21:07 GMT
<
* Connection #0 to host 192.168.28.200 left intact

**Comment by blackbird1989** [comment]
I tried without proxies. When i access the URL on the browser, it shows me a black screen with a loading symbol but it's stuck there and doesn't complete loading. 

The output of curl command is as follows,
 [vagrant@localhost ~]$ curl -v http://192.168.28.200:8261/dashboard
•About to connect() to 192.168.28.200 port 8261 (#0)
• Trying 192.168.28.200...
•Connected to 192.168.28.200 (192.168.28.200) port 8261 (#0) > GET /dashboard HTTP/1.1 > User-Agent: curl/7.29.0 > Host: 192.168.28.200:8261 > Accept: / > < HTTP/1.1 302 Found < Server: Apache-Coyote/1.1 < Location: /dashboard/ < Transfer-Encoding: chunked < Date: Fri, 29 Jul 2016 12:21:07 GMT <
•Connection #0 to host 192.168.28.200 left intact

**Comment by ghost** [comment]
@blackbird1989 the output of curl command shows the right redirect to `/dashboard`

Do you see any errors in browser console when the page is being loaded?

**Comment by blackbird1989** [comment]
No, there are no errors seen on the browser. It just looks like the IDE page is loading ( black screen with a blue loading symbol on the centre of the page )

**Comment by ddementieva** [comment]
@blackbird1989 Press F12 to call a browser dev console. Are there any errors in that view?

**Comment by blackbird1989** [comment]
On F12, I get the below errors on Console,
You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material! vendor-6fbb3a1843.js:66:23451

Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. vendor-6fbb3a1843.js:66:23451
Preloading IDE javascript /ide/_app/F841838995744957B980B82ACC3ECFAC.cache.js app-52709b75ae.js:513:1410

Also I get many css errors such as these,
Error in parsing value for 'text-shadow'.  Declaration dropped. dashboard:1:6582
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. dashboard:1:6648
Error in parsing value for 'text-shadow'.  Declaration dropped. dashboard:1:7188
Error in parsing value for 'color'.  Declaration dropped. dashboard:1:13325
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. dashboard:1:5123
Error in parsing value for 'text-shadow'.  Declaration dropped. dashboard:1:6596
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. dashboard:1:6662
Error in parsing value for 'text-shadow'.  Declaration dropped. dashboard:1:7202
Error in parsing value for 'color'.  Declaration dropped. dashboard:1:13339
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. dashboard:1:5102

I'm using Mozilla Firefox as my browser.

**Comment by ghost** [comment]
@blackbird1989 can you use Chrome and open it's dev console? I have tested this Vagrantfile on Windows 8 and 10, Ubuntu and Centos 7.2. Cannot reproduce the issue.

**Comment by blackbird1989** [comment]
In Chrome's dev console I get the below errors,

You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material! vendor-6fbb3a1843.js:33767
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. vendor-6fbb3a1843.js:33767
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. vendor-6fbb3a1843.js:33767
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. vendor-6fbb3a1843.js:33767
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. vendor-6fbb3a1843.js:33767
ReferenceError: Map is not defined
    at new e (http://192.168.28.200:8261/dashboard/scripts/app-52709b75ae.js:153:692)
    at Object.<anonymous> (http://192.168.28.200:8261/dashboard/scripts/app-52709b75ae.js:23:1697)
    at Object.i [as invoke](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19553)
    at Object.$get (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:17943)
    at Object.i [as invoke](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19553)
    at http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:20130
    at r (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19183)
    at Object.i [as invoke](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19520)
    at Object.$get (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:17943)
    at Object.i [as invoke](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19553) vendor-6fbb3a1843.js:33767
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. vendor-6fbb3a1843.js:33767
ReferenceError: Map is not defined
    at new e (http://192.168.28.200:8261/dashboard/scripts/app-52709b75ae.js:163:752)
    at Object.<anonymous> (http://192.168.28.200:8261/dashboard/scripts/app-52709b75ae.js:23:1697)
    at Object.i [as invoke](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19553)
    at Object.$get (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:17943)
    at Object.i [as invoke](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19553)
    at http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:20130
    at r (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19183)
    at Object.i [as invoke](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:19520)
    at http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:162:1892
    at Object.o [as forEach](http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:65:994) vendor-6fbb3a1843.js:33767
Failed to load resource: the server responded with a status of 404 (Not Found) http://192.168.28.200:8261/api/
TypeError: Object 552D8745C433CAE2CB32107D9A9EB794.cache.js has no method 'endsWith'
    at e.t.CheIdeFetcher.o.value (http://192.168.28.200:8261/dashboard/scripts/app-52709b75ae.js:513:1848)
    at http://192.168.28.200:8261/dashboard/scripts/app-52709b75ae.js:513:1372
    at l (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:66:30211)
    at http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:66:30383
    at h.$eval (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:67:5881)
    at h.$digest (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:67:4397)
    at h.$apply (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:67:6161)
    at o (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:66:13557)
    at g (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:66:15405)
    at XMLHttpRequest.x.onload (http://192.168.28.200:8261/dashboard/scripts/vendor-6fbb3a1843.js:66:15948) vendor-6fbb3a1843.js:33767

**Comment by ghost** [comment]
@blackbird1989 I suspect this is some sort of a Virtual Box or local networking setup issue. Can you run Eclipse Che in Vagrant? Here's the Vagrantfile - https://github.com/eclipse/che/blob/master/Vagrantfile

**Comment by ghost** [comment]
@blackbird1989 can you check out the latest Getting Started docs? https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started

**Comment by ddementieva** [comment]
@blackbird1989 Any update on this?

**Comment by TylerJewell** [comment]
Closing - old, and could be reopoened on the ARTIK IDE issue repository.
