### ISSUE TITLE
traefik gateway service url format

### ISSUE THREAD

**Issue by kazimsarikaya** [eclipse-che/che#18927]
Hello,

The default format is defined at:

https://github.com/eclipse/che/blob/594982badff2bd830604c348898240aa49348a32/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/TraefikGatewayRouteConfigGenerator.java#L58

We use multiple kubernetes with different cluster domain different than cluster.local. Hence this static value blocks us to use che at our environments. If this format can be a envrionment variable, it will be useful for deployments like ours.

**Comment by tolusha** [comment]
I believe `"http://%s.%s.svc:%s"; ` should be enough.

**Comment by kazimsarikaya** [comment]
I believe it should be more generic like `"http://%s.%s.svc.%s:%s"`. Because each service URL has format like `<servicename>.<namespace>.svc.<cluster_domain>:<port>`. The `<cluster_domain>` is an installation parameter of kubernetes. probably/mostly no one will install che with cross cluster, however being generic sounds good. The cluster_domain may be an env variable such as `CHE_INFRA_KUBERNETES_CLUSTER_DOMAIN`.

I don't know the structure of project, hence I don't know how to handle config environment variables. So I didn't create a pr for this enhancement.

**Comment by ibuziuk** [comment]
@kazimsarikaya thanks for reporting the issue, maybe you will be interested in contributing?

**Comment by kazimsarikaya** [comment]
@ibuziuk let me try, however i don't know how it will be ended

**Comment by kazimsarikaya** [comment]
I opened a pr however. I think I need to work on.

/assign @kazimsarikaya

**Comment by tolusha** [comment]
Search domains in `/etc/resolv.conf` already contain `<cluster_domain>`
that's why it works with the simple format `"http://%s.%s.svc:%s"`

**Comment by kazimsarikaya** [comment]
> Search domains in `/etc/resolv.conf` already contain `<cluster_domain>`
> that's why it works with the simple format `"http://%s.%s.svc:%s"`

Adding cluster_domain as parameter is not only about dns resolving. kube fed and multitenancy can use multiple cluster domains. In the future some one probably will ask cluster_domain paramater. hence supoorting it from now, sounds good.

**Comment by sparkoo** [comment]
@kazimsarikaya are you still interested in contributing this? We've moved the che-server repo to https://github.com/eclipse-che/che-server so you can create new PR there and finish the work.

**Comment by kazimsarikaya** [comment]
@sparkoo i added wip because of the discussion with @tolusha didn't completed.

**Comment by tolusha** [comment]
@kazimsarikaya 
My bad, I haven't seen that PR.
Could you move your PR to another repo and we can continue discussion there?

**Comment by kazimsarikaya** [comment]
i created https://github.com/eclipse-che/che-server/pull/17
