### ISSUE TITLE
chectl server:update stopped updating che-operator:nightly

### ISSUE THREAD

**Issue by filipkroupa** [eclipse-che/che#18922]
### Describe the bug
I have a Che deployment from chectl next channel. From a Jenkins job, I periodically update chectl and run `chectl server:update` to run the latest version of Che docker images with `nightly` tag. Recently this approach stopped working as chectl states Che is already up to date, when there are newer images with nightly tag.

### Che version

 - [ ] latest
 - [X] nightly
 - [ ] other: please specify

### Steps to reproduce
My flow is as folows:

1. Check the current docker images hash
**$ kubectl describe pod che -n nightly | grep sha256**
```
Image ID:       docker-pullable://quay.io/eclipse/che-server@sha256:42a0d4e30a62827727aa6e68789f7ee76ef9d6d24a4e57685aebe2e3d49cb8a2
Image ID:      docker-pullable://quay.io/eclipse/che-operator@sha256:30b773419dce4266e274cfc669dfa0f4c4de45ba8fc214bf60860ce768c395de
```
Note the versions:
[https://quay.io/repository/eclipse/che-server?tab=history](https://quay.io/repository/eclipse/che-server?tab=history) version from Tue, Jan 26, 2021 2:08 AM
[https://quay.io/repository/eclipse/che-operator?tab=history](https://quay.io/repository/eclipse/che-operator?tab=history) version from Tue, Jan 26, 2021 2:25 AM

2. Check chectl version
**$ chectl --version**
`chectl/0.0.20210127-next.5bc2773 linux-x64 node-v12.20.0`

3. Update chectl channel next
**$ chectl update next**
```
chectl: Updating CLI from 0.0.20210127-next.5bc2773 to 0.0.20210128-next.9f55489 (next)... done
chectl: Updating CLI... done
```

4. Update Che
**$ chectl server:update --chenamespace nightly --yes**
```
› Current Kubernetes context: 'gke_mfd-eng-che4z_us-central1-a_mfd-che4z-gke1'
› Installer type is set to: 'operator'
  ✔ Verify Kubernetes API...OK
  ✔ 🏃‍  Running the Eclipse Che operator Update
    ✔ Checking versions compatibility before updating
Existed Eclipse Che operator: quay.io/eclipse/che-operator:nightly.
New Eclipse Che operator    : quay.io/eclipse/che-operator:nightly.
Eclipse Che is already up to date.
```
See **Che was not updated**

5. Check the current docker images hash
**$ kubectl describe pod che -n nightly | grep sha256**
```
Image ID:       docker-pullable://quay.io/eclipse/che-server@sha256:42a0d4e30a62827727aa6e68789f7ee76ef9d6d24a4e57685aebe2e3d49cb8a2
Image ID:      docker-pullable://quay.io/eclipse/che-operator@sha256:30b773419dce4266e274cfc669dfa0f4c4de45ba8fc214bf60860ce768c395de
```
Note: docker images did not change

### Expected behavior

I expected the quay.io/eclipse/che-operator:nightly would be updated to latest available image
`nightly was moved to SHA256 a3c34aea8950 from SHA256 ef338c339922 | Fri, Jan 29, 2021 2:14 AM`
-- | --

### Runtime
   - [X] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [X] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context

Based on my logs, this behavior change first appeared when I updated from chectl 0.0.20201210-next.0af053a to chectl 0.0.20201211-next.fa906ce

**Comment by tolusha** [comment]
@filipkroupa
thank you report. I will provide fix soon.

**Comment by tolusha** [comment]
Fixed.
Pls update chectl to a newer version.
