### ISSUE TITLE
Intelij IDEA editor must be secure

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18934]
### Describe the bug
In the same way as Theia editor, Intelij IDEA editor server be secure 
https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml#L17

Otherwise, everybody who has the server URL, can connect to the editor, which I reproduced locally, I'm able to open Intelij IDEA in the incognito window without authentication.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start Intelij IDEA editor.
2. find the IDE server url.
3. Open the URL in the another browser or incognito window.
4. Check that it's opened without any authentication is done.

### Expected behavior
User must authenticate with keycloak before IDE is opened.
If it's another user is authentication - IDE is not opened at all.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
cc @vzhukovs @azatsarynnyy

**Comment by vzhukovs** [comment]
Fixed by adding secure parameters to `meta.yaml`: https://github.com/che-incubator/jetbrains-editor-images/tree/meta
