### ISSUE TITLE
Openvsx dropped some extensions

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18933]
### Describe the bug
Eclipse Che plug-in registry is referencing some extensions that have been dropped from OpenVsx registry

example: bash-debug
it was on openvsx/ google referenced it
![image](https://user-images.githubusercontent.com/436777/106443601-f4294600-647c-11eb-8c69-31cacb565051.png)

but today https://open-vsx.org/extension/rogalmic/bash-debug is returning 404 error

Should be related to the final date of "publishing agreement deadline of January 29, 2021"
It makes impossible to build plugin registry without cache and workspaces using these plug-ins will fail

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
Working VS Code extensions

**Comment by sunix** [comment]
Sounds blocker to me:
- new builds are failing
- some devfiles may fail to load if using the one of the missing extensions

**Comment by sunix** [comment]
from what I have tested, the ones that are failing:
- https://open-vsx.org/api/castwide/solargraph/0.22.0/file/castwide.solargraph-0.22.0.vsix
- https://open-vsx.org/api/rogalmic/bash-debug/0.3.9/file/rogalmic.bash-debug-0.3.9.vsix
- https://open-vsx.org/api/gattytto/phoityne-vscode/0.0.28/file/gattytto.phoityne-vscode-0.0.28.vsix

**Comment by sunix** [comment]
To prevent the problem for the user at runtime, we could make the plugins available "offline" in the registry.
Could not be done for all plugins so we would need to have a denylist for those license don't authorize to redistribute.

**Comment by brianking** [comment]
This was just discussed on the community call. Can someone summarize the proposed solution?

**Comment by ericwill** [comment]
> This was just discussed on the community call. Can someone summarize the proposed solution?

I believe the way forward is:
* Remove the problematic devfiles/plugins for now
* Find replacement links to update the plugin registry
* Enable offline builds in the plugin registry by default
* Re-introduce the devfiles that were removed

**Comment by tsmaeder** [comment]
@ericwill  how about we contact the authors of the plugins in question and get them to sign? Has this been explored? 

> Enable offline builds in the plugin registry by default so that all vsix files are downloaded at build time

We need to be aware that we're crossing a line between referencing and distributing here. Not saying it's a problem, but the licensing requirements are different.

**Comment by sunix** [comment]
- for the ruby plugin: https://github.com/castwide/vscode-solargraph/issues/204
- I have pinged @gattytto in mattermost but not answer: https://mattermost.eclipse.org/eclipse/pl/scxqr9p61jb1mpmnnd3cozwhie

**Comment by sunix** [comment]
@tsmaeder about offline mode: https://github.com/eclipse/che/issues/18933#issuecomment-770824246
> To prevent the problem for the user at runtime, we could make the plugins available "offline" in the registry.
> Could not be done for all plugins so we would need to have a denylist for those the license don't authorize to redistribute.

**Comment by ibuziuk** [comment]
@sunix @ericwill could you please cherry-pick relevants PRs for fixing bash devfile for 7.25.x ? we would like to have a fix in the `7.25.2` that is planned for tomorrow.

**Comment by ericwill** [comment]
> @sunix @ericwill could you please cherry-pick relevants PRs for fixing bash devfile for 7.25.x ? we would like to have a fix in the `7.25.2` that is planned for tomorrow.

All relevant PRs have been cherry-picked.

**Comment by sunix** [comment]
I am closing this one as it looks like everything has been merged/cherry-picked
