### ISSUE TITLE
Stop publishing Che parent and Che server artifacts to Maven Central

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18941]
### Is your task related to a problem? Please describe.

Since we now live in a container world, publishing maven artifacts is an outdated construct. 
And since we also now live in a typescript/nodejs/golang world, only 1 small part of the Che build/release process still depends on Maven at all, with everything else having already moved to other languages and other publishing methods.

### Describe the solution you'd like

As such, it's time to move away from publishing these maven artifacts. We'd like to deprecate as of 7.26.0 (Feb 10) and cease publishing the che server and che parent artifacts in April 2020, starting with Che 7.29.0 (April 14).

If you have any technical objections to this plan, please reply to [this thread](https://www.eclipse.org/lists/che-dev/msg04006.html) or comment on this issue, as we'd like to formalize this plan in time for the start of the 7.26 release next week.

**Comment by nickboldt** [comment]
As there have been no objections to this plan, looks like we're going ahead with it. We'll stop publishing maven artifacts for che server as of 7.29 (in ~3 weeks).

**Comment by l0rd** [comment]
@nickboldt @mkuznyetsov can we close this one?

**Comment by mkuznyetsov** [comment]
sure, not publishing artifacts since 7.29.0
