### ISSUE TITLE
Enable multiarch builds for che-plugin-registry

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18942]
### Is your task related to a problem? Please describe.

As discovered in https://issues.redhat.com/browse/CRW-1475 the che registries are still publishing as single-arch amd64 images. We need ppc64le and s390x, too.

### Describe the solution you'd like

Borrowing code from:
* https://github.com/eclipse/che-plugin-registry/blob/master/.ci/sidecar-build-publish.sh#L28-L35 and 
* https://github.com/eclipse/che-plugin-registry/blob/master/.github/workflows/sidecar-build-push.yaml#L35-L48

we can enable buildx builds for the registry for both nightly and release, allowing it to be easier to test Che on other arches.

**Comment by aditijadhav38** [comment]
@nickboldt For che-plugin-registry [issue](https://github.com/eclipse/che/issues/18705) has been already raised for adding s390x support to RHEL dockerfile which will be used for image-build-PR-check workflow.

**Comment by nickboldt** [comment]
Well, this clearly isn't an urgent priority. Closing.
