### ISSUE TITLE
SSH plugin failed to upload ssh key to GitHub

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#18952]
### Describe the bug

SSH plugin proposes to upload a new key to GitHub in case the user is cloning a repository via SSH.
This feature is not working anymore since the oauth authentication failed.

![Screenshot from 2021-02-02 19-03-51](https://user-images.githubusercontent.com/1655894/106635601-b9610400-6589-11eb-9d67-e4c876a4b6b9.png)

It's hard to notice, but after clicking 'Upload' button the oauth popup opens for a while, but then immediately hides with this error in theia console

```
2021-02-02 16:46:38.723 root ERROR Request getOAuthToken failed with error: Failed access: http://keycloak.eclipse-che.svc:8080/auth/realms/che/broker/github/token?token, method: GET, response code: 502, message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">

    <title>Log in to Eclipse Che</title>
    <link rel="icon" href="/auth/resources/6.0.1/login/che/img/favicon.ico" />
            <link href="/auth/resources/6.0.1/login/che/css/che-login.css" rel="stylesheet" />
</head>

<body class="">
  <div class="">
    <div id="kc-header" class="">
      <div id="kc-header-wrapper" class="">Eclipse Che</div>
    </div>
    <div class=" ">
      <header class="">
        <h1 id="kc-page-title">        We&#39;re sorry...
</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">


        <div id="kc-error-message">
            <p class="instruction">Could not obtain token from identity provider.</p>
        </div>

        </div>
      </div>

    </div>
  </div>
</body>
</html>
```

Tested on multiuser Che running in local minikube.

Required for https://github.com/eclipse/che/issues/13494

### Che version

 - [x] latest

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

**Comment by vitaliy-guliy** [comment]
On hosted Che I have
```
2021-02-03 09:28:12.031 root ERROR Request getOAuthToken failed with error: "401" returned by "/oauth/token?oauth_provider=github"." Params:
```

**Comment by vinokurig** [comment]
> On hosted Che I have
>
>
>```
>2021-02-03 09:28:12.031 root ERROR Request getOAuthToken failed with error: "401" returned by "/oauth/token?oauth_provider=github"." Params:
>```

I think it will be fixed by https://github.com/eclipse/che-theia/pull/969

**Comment by vitaliy-guliy** [comment]
The issue is mostly related for the local Che. Adding of the key works fine when the keycloak is properly configured.
I'm close this issue as not relevant anymore.
