### ISSUE TITLE
What's checluster field should I use to configure Che custom certificate?

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18958]
## Summary

I would like to use a custom TLS certificate for my Che endpoints. 

From the documentation it looks like 2 distinct fields could be used:

- [`spec/k8s/tlsSecretName`](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-the-che-installation/#checluster-custom-resource-k8s-settings_che)
- [`spec/server/cheHostTLSSecret`](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-che-hostname/)

What's the one that should be set? Should we update the documentation accordingly?

**Comment by mmorhun** [comment]
@l0rd usually `tlsSecretName` should be used. This field defines a secret that is used for TLS termination of all Che ingresses.
`cheHostTLSSecret` defines secret which should be used for TLS termination of only one additional endpoint cheHost (a beautiful name for Che (in other words entrypoint link to dashboard) ). Actually both properties might point to the same secret if the certificate itself covers both of the hostnames.

**Comment by mmorhun** [comment]
As about docs, [Configuring Eclipse Che server hostname](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-che-hostname/) page describes the process of configuring beautiful Che dashboard hostname, but not TLS configuration of Che itself.
@l0rd should we add a link to `tlsSecretName` property from that page (like to configure TLS for Che itself, please set that property (as we don't have a separate page for TLS configuration) or should we create a separate page fro TLS configuration) WDYT?

**Comment by l0rd** [comment]
@mmorhun for my understanding: if I set `cheHost` I will have 2 TLS terminations (one for the default domain name, the other one for the beautiful domain name)?

**Comment by mmorhun** [comment]
`cheHost` covers only beautiful domain (which is optional) and `tlsSecretName` covers all mandatory Che ingresses.
If a user goes to a regular Che ingress (including non-beautified `che-chenamespace.<cluster-domain>`) then the secret from `tlsSecretName` is used for TLS termination. `cheHostTLSSecret` will be used only for the beautiful link, if any. Which secret to use for termination depends on the link the user opens. However, the user will always need secret from `tlsSecretName` as it is used for, at least, securing Keycloak (needed to login) and actual IDE (Che Theia for example) of a workspace.

**Comment by boczkowska** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2673
