### ISSUE TITLE
Devfile v2 factory property overrides

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18950]
### Is your enhancement related to a problem? Please describe.

Che-server factory can override properties in devfile v1 (https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#overriding-devfile-values-using-factory-parameters_che). Current factory implementation proposal (https://github.com/eclipse/che/pull/18868) for devfile v2 does not implement this feature. If the devfile v2 does not deprecate usecases of this feature, we should implement it for devfile v2 as well.

### Describe the solution you'd like

Implement che-server property override in similar fashion as devfile v1. Consider the limitation that che-server does not know the devfile v2 structure and treats it only generic Map/Json/Yaml. This should not be a blocker as in current implementation for devfile v1, overrides are applied before translating the devfile raw format into data object.

### Describe alternatives you've considered

Don't implement the overrides in che-server and let the dasboard (or other client) do this. In new devfile v2 oriented architecture, this would probably make more sense as che-server plays very limited role here, especially with handling devfile and creating workspaces.

### Additional context

https://github.com/eclipse/che/issues/18838
https://github.com/eclipse/che/pull/18868

**Comment by benoitf** [comment]
reopening as a user is asking support for that
https://github.com/eclipse/che/issues/21148

**Comment by martinelli-francesco** [comment]
Also [this issue](https://github.com/eclipse/che/issues/20137) referes to the same issue.

**Comment by sparkoo** [comment]
@benoitf I think this one should be closed in favor of https://github.com/eclipse/che/issues/20137. They are same feature requests with different implementation proposals. With current architecture, it does not make sense for che-server to to this job. wdyt?
