### ISSUE TITLE
Schema support is broken for task and launch configurations

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#18956]
### Describe the bug

Content assistant is not working for tasks.json and launch.json files.
So user doesn't have the corresponding schema support at adding/editing task and launch configurations.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Try to configure task or launch configuration.
1. Please use:
- `Terminal` => `Configure Tasks` action for tasks 
-  `Run`=> `Open Configurations` for launch configs
- or open/create the corresponding `tasks.json`/`launch.json` file manually 
2. Try to use content assistant to create/edit a configuration

### Expected behavior
How it works for tasks for 7.21 version of the editor:

![tasks_schema_expected](https://user-images.githubusercontent.com/5676062/106736345-02629800-661e-11eb-9a79-3541f8a2a19b.gif)

How it works for launch configs for the current version of vanilla Theia:

![launch_schema_expected](https://user-images.githubusercontent.com/5676062/106736669-6dac6a00-661e-11eb-918b-e48d5d7b1e36.gif)

### Runtime
I am able to reproduce the issue on che.openshift.io and dogfooding instances

**Comment by tsmaeder** [comment]
Btw: putting debug configs inside the devfile is also broken: they don't show up in the launch.json for new workspaces.

**Comment by RomanNikitenko** [comment]
@tsmaeder 
I can not reproduce your use case - checked few minutes ago for the `next` version of the editor on dogfooding instance.
Could you share your `devfile` or some details to help reproduce the bug?
