### ISSUE TITLE
Unable to run task when using custom TLS certificate

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18957]
### Describe the bug

I have deployed Che on minikube. I am using a custom TLS certificate for Che endpoints. 

That means that I have:

- created a Kubernets tls secret with the key and certificate
- updated CheCluster setting both [`spec/k8s/tlsSecretName`](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-the-che-installation/#checluster-custom-resource-k8s-settings_che) and [`/spec/server/cheHostTLSSecret`](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-che-hostname/) to point to that secret
- add the CA certificate in configmap properly labelled (as described [here](https://www.eclipse.org/che/docs/che-7/installation-guide/importing-untrusted-tls-certificates/#_adding_new_ca_certificates_into_che))

When trying to run a task I get the following error:

```log
Error launching task 'maven build': Request runTask failed with message: Failed to execute Che command: unable to verify the first certificate 
```

<img width="1743" alt="image" src="https://user-images.githubusercontent.com/606959/106728188-81e76b80-660c-11eb-825a-69afb4e907fa.png">

### Che version

nightly

### Steps to reproduce

Deploy Che on minikube using chectl
Configure Che to use a custom certificate as described [here](https://che-incubator.github.io/2021/02/01/@mario.loriedo-using-mkcert-to-locally-trust-eclipse-che-tls-certificates-ffaafe76e5d0.html)
Start the Java maven sample
Try to start one of the 2 tasks provided

### Expected behavior

The maven build should run successfully

### Runtime

minikube

```
minikube version: v1.17.1
commit: 043bdca07e54ab6e4fc0457e3064048f34133d7e
```

### Installation method

```bash
$  chectl update next && \
   chectl server:deploy \
       -p minikube
```

### Environment

macOS

**Comment by azatsarynnyy** [comment]
I'm labeling it as `area/plugins` it's related to Task Plug-in.

**Comment by sunix** [comment]
I have managed to reproduce this issue.
My thoughts:
- why it is working with the origininal self-signed certificate that is generated when installing Che?
- why are we trying to use an 'external URL' when we are trying to reach machine exec which is local to the workspace pod: https://github.com/eclipse/che-theia/blob/9a76d18382e3b90858b1fd63e713eb908facbb70/plugins/task-plugin/src/che-workspace-client.ts#L112

**Comment by sunix** [comment]
Maybe different cert being used here: https://github.com/eclipse/che-machine-exec/blob/master/main.go#L87

**Comment by sleshchenko** [comment]
> Why it is working with the origininal self-signed certificate that is generated when installing Che?

The difference I see:
https://che-incubator.github.io/2021/02/01/@mario.loriedo-using-mkcert-to-locally-trust-eclipse-che-tls-certificates-ffaafe76e5d0.html creates CA into `custom-certs` cert

While default certs Che operator generated, are propagated over 
```
    spec:
      containers:
      - env:
        - name: CHE_SELF__SIGNED__CERT
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: self-signed-certificate
              optional: true
        - name: CHE_GIT_SELF__SIGNED__CERT
        - name: CHE_GIT_SELF__SIGNED__CERT__HOST
```
from secret `self-signed-certificate`
Custom certificates and Che Self-signed can be used on different ways.

**Comment by ericwill** [comment]
What's left to be done for this ticket, @sunix can we close it?

**Comment by sunix** [comment]
Yes closing. FYI, I created https://github.com/eclipse/che/issues/19246 to clarify our docs on how things should be configured as a che admin. And how plugins/editors/applications should consume these certificate.

**Comment by l0rd** [comment]
@sunix Can you provide more details? In particular what's not clear is:
1) Have you been using a custom TLS certificate (not the auto generated one) and have Che working?
2) Are the steps to configure Che to use a custom certificate easy to follow for an admin?

**Comment by l0rd** [comment]
@sunix the custom certificate is trusted by the Che server (because it's able to communicate with Keycloak), by the plugin brokers (because they are able to communicate with the registries), by Theia (because it's able to communicate with the Che server). But somehow there is a process that probably looks in the bad (old/legacy) folder for trusted certificates and running tasks fail.

**Comment by sunix** [comment]
To test: remove the certificate generated by chectl from the browser and see if terminal is working or not.

**Comment by l0rd** [comment]
I have somehow missed that the issue had been solved by https://github.com/eclipse/che-theia/pull/1019. I thought that the issue was closed in favor of a doc issue. I will verify the fix and if it works for me I will close the issue later today.

> To test: remove the certificate generated by chectl from the browser and see if terminal is working or not.

I never install the certs generated by chectl anyway

**Comment by l0rd** [comment]
Closing as this issue as been solved. Although I am still not able to successfully run this scenario as I have found [another bug](https://github.com/eclipse/che/issues/19309) 😡
