### ISSUE TITLE
CSV description should have README section

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18968]
### Is your task related to a problem? Please describe.

The OCP Administration catalog UI will render the markdown in the spec.description field of the operator's CSV in the install tile for the operator. The spec.description of the CSV file must contain the following sections "Introduction", "Details", "Prerequisites", "Resources Required", "Installing", "Configuration", "Limitations", "SecurityContextConstraints Requirements"

The following CSVs are missing descriptions:
deploy/olm-catalog/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml
deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/che-operator.clusterserviceversion.yaml

### Describe the solution you'd like

Example:
```
spec:
  description: |-
    # Introduction
    # Details
    Various Details
    ## Prerequisites
    Various prerequisites
    ## Resources Required
    Various Resources Required
    ## Installing
    Various Installation details
    # Configuration
    Various Configuration information
    ### Limitations
    Various Limitations
    ### SecurityContextConstraints Requirements
    SCC Requirements
```

**Comment by ArvinB** [comment]
@kristinochka based on our discussion today. I think we can close this issue out and handle it within IBM.
