### ISSUE TITLE
Required Metadata labels are missing 

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18967]
### Is your task related to a problem? Please describe.

The labels that Kubernetes recommends provide useful identification information used by Kubernetes, users of the cluster, and other resources. The recommended labels to be defined at metadata.labels on each resource are **app.kubernetes.io/name, app.kubernetes.io/managed-by, app.kubernetes.io/instance**.

### Describe the solution you'd like

The following resources are missing labels:
deploy/role.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels
deploy/role_binding.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels 
deploy/role_binding_oauth.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels 
deploy/service_account.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels

deploy/cluster_role.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels 
deploy/cluster_role_binding.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels 
deploy/crds/org_v1_che_cr.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels
deploy/crds/org_v1_che_crd.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels
deploy/namespaces_cluster_role.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels
deploy/namespaces_cluster_role_binding.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels

deploy/olm-catalog/eclipse-che-preview-kubernetes/generated/roles/role.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels 
deploy/olm-catalog/eclipse-che-preview-kubernetes/manifests/org_v1_che_crd.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels 
deploy/olm-catalog/eclipse-che-preview-openshift/generated/roles/role.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels
deploy/olm-catalog/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels 
deploy/operator.yaml: ["app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name"] not defined under metadata.labels
 deploy/operator.yaml: ["app.kubernetes.io/managed-by"] not defined under spec.template.metadata.labels

**Comment by tolusha** [comment]
1. The following files are removed from the repository.
```
deploy/role_binding_oauth.yaml
deploy/namespaces_cluster_role.yaml
deploy/namespaces_cluster_role_binding.yaml
```

2.  To be honest I am not sure about correct value for `app.kubernetes.io/managed-by`. olm, che-operator, chectl?
```
deploy/role.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels
deploy/role_binding.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels
deploy/service_account.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels
deploy/cluster_role.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels
deploy/cluster_role_binding.yaml: ["app.kubernetes.io/managed-by"] not defined under metadata.labels
```

3. All files in the following folders are autogenerated based on files above and should n't been taken into account.
```
deploy/olm-catalog/*
```

4. Labels are missing
```
deploy/crds/org_v1_che_cr.yaml
deploy/crds/org_v1_che_crd.yaml
deploy/crds/org_v1_che_crd_v1beta1.yaml
deploy/operator.yaml
```

[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by ArvinB** [comment]
/remove-lifecycle stale
@tolusha This is related to the recent PR.
