### ISSUE TITLE
raise error when building offline che-plugin-registry image

### ISSUE THREAD

**Issue by robbiesguo** [eclipse-che/che#18966]
## Summary
When I checkout the tag 7.25.1 of che plugin registry ,I build the offline che plugin registry image with folowing commond
./build.sh --tag 7.25.1  --offline --latest-only
The error will be raised.

Run the module to generate meta files...
stack=Error: end of central directory record signature not found
    at /node_modules/yauzl/index.js:187:14
    at /node_modules/yauzl/index.js:631:5
    at Immediate.<anonymous> (/node_modules/fd-slicer/index.js:202:5)
    at processImmediate (internal/timers.js:461:21)
Unable to start Error: end of central directory record signature not found
    at /node_modules/yauzl/index.js:187:14
    at /node_modules/yauzl/index.js:631:5
    at Immediate.<anonymous> (/node_modules/fd-slicer/index.js:202:5)
    at processImmediate (internal/timers.js:461:21)
The command '/bin/sh -c ./generate_vscode_extensions.sh' returned a non-zero code: 1
When I checkout the master of the che plugin registry,I build the offline che plugin registry image with following commond
./build.sh --tag 7.25.1  --offline
The error will be raised.
  FAIL  tests/sidecar/sidecar-docker-image.spec.ts (27.554 s)
[test]   ● Test Sidecar › basics
[test]
[test]     TypeError: Object.fromEntries is not a function
[test]
[test]       47 |       n: '1',
[test]       48 |     };
[test]     > 49 |     const result = await this.git.log(logOptions);
[test]          |                                   ^
[test]       50 |     const latest = result.latest;
[test]       51 |     if (!latest) {
[test]       52 |       throw new Error(`Unable to find result when executing ${JSON.stringify(logOptions)}`);
[test]
[test]       at userOptions (../../node_modules/simple-git/src/lib/tasks/log.ts:63:18)
[test]       at parseLogOptions (../../node_modules/simple-git/src/lib/tasks/log.ts:102:22)
[test]       at Git.Object.<anonymous>.Git.log (../../node_modules/simple-git/src/git.js:871:26)
[test]       at SidecarDockerImage.<anonymous> (src/sidecar/sidecar-docker-image.ts:49:35)
[test]       at src/sidecar/sidecar-docker-image.ts:1824:40
[test]       at Object.<anonymous>.__awaiter (src/sidecar/sidecar-docker-image.ts:1767:10)
[test]       at SidecarDockerImage.getDockerImageFor (src/sidecar/sidecar-docker-image.ts:1878:12)
[test]       at tests/sidecar/sidecar-docker-image.spec.ts:32:45

**Comment by l0rd** [comment]
cc @ericwill

**Comment by benoitf** [comment]
@robbiesguo what is your node version ?
You should have at least nodejs 12 or 14

**Comment by disaster37** [comment]
same problem here without this `--offline --latest-only`.

Tested on centos8 with nodejs 12 and nodejs 14.

```
Summary of all failing tests
 FAIL  tests/sidecar/sidecar-docker-image.spec.ts (13.695 s)
  ● Test Sidecar › basics
[test] 
    Unable to find result when executing {"format":{"hash":"%H"},"file":"/projects/che-plugin-registry/sidecars/go","n":"1"}
[test] 
      50 |     const latest = result.latest;
      51 |     if (!latest) {
    > 52 |       throw new Error(`Unable to find result when executing ${JSON.stringify(logOptions)}`);
         |             ^
      53 |     }
      54 |     const hash = latest.hash;
      55 |     return `${SidecarDockerImage.PREFIX_IMAGE}:${sidecarShortDirectory}-${hash.substring(0, 7)}`;

      at SidecarDockerImage.<anonymous> (src/sidecar/sidecar-docker-image.ts:52:13)
      at fulfilled (src/sidecar/sidecar-docker-image.ts:1783:24)
```

**Comment by DarthBlair** [comment]
...might be the same Problem. Any ideas?
```
Generate artifacts...
- Read che-theia-plugins.yaml file
✔ Read che-theia-plugins.yaml file
- Download/Unpack/Analyze CheTheiaPlugins in parallel (may take a while)
✖ Error analyzing extensions https://open-vsx.org/api/redhat/vscode-openshift-connector/0.2.0/file/redhat.vscode-openshift-connector-0.2.0.vsix,https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-kubernetes-tools/vscode-kubernetes-tools-1.1.0.vsix,https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-yaml/vscode-yaml-0.8.0.vsix,https://github.com/che-incubator/che-theia-openshift-auth/releases/download/0.0.1/che-openshift-authentication-plugin-0.0.1.vsix from https://github.com/redhat-developer/vscode-openshift-tools
stack=Error: end of central directory record signature not found
    at /builds/eclipse/che-plugin-registry/git/node_modules/yauzl/index.js:187:14
    at /builds/eclipse/che-plugin-registry/git/node_modules/yauzl/index.js:631:5
    at Immediate.<anonymous> (/builds/eclipse/che-plugin-registry/git/node_modules/fd-slicer/index.js:202:5)
    at processImmediate (internal/timers.js:456:21)
Unable to start Error: end of central directory record signature not found
    at /builds/eclipse/che-plugin-registry/git/node_modules/yauzl/index.js:187:14
    at /builds/eclipse/che-plugin-registry/git/node_modules/yauzl/index.js:631:5
    at Immediate.<anonymous> (/builds/eclipse/che-plugin-registry/git/node_modules/fd-slicer/index.js:202:5)
    at processImmediate (internal/timers.js:456:21)
```

**Comment by ericwill** [comment]
What version of the registry are you using? It seems to work fine for me when specify `--offline`

**Comment by DarthBlair** [comment]
I am trying to build 7.28.2

**Comment by ericwill** [comment]
Can you try commenting out the openshift connector plugin definition? https://github.com/eclipse-che/che-plugin-registry/blob/master/che-theia-plugins.yaml#L313-L333

I'm wondering if it's specific to that plugin.

**Comment by DarthBlair** [comment]
i would love to, but since yesterday there is another problem:
```
[test] FAIL tests/sidecar/sidecar-docker-image.spec.ts (6.188 s)
[test]   ● Test Sidecar › basics
[test] 
[test]     fatal: ambiguous argument '/builds/eclipse/che-plugin-registry/sidecars/go': unknown revision or path not in the working tree.
[test]     Use '--' to separate paths from revisions, like this:
[test]     'git <command> [<revision>...] -- [<file>...]'
[test] 
[test]       at GitExecutorChain.onFatalException (../../node_modules/simple-git/src/lib/runners/git-executor-chain.ts:67:77)
[test]       at GitExecutorChain.<anonymous> (../../node_modules/simple-git/src/lib/runners/git-executor-chain.ts:59:21)
[test]           at Generator.throw (<anonymous>)
[test]       at rejected (../../node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
[test] 
```

**Comment by zWingz** [comment]
same problem.
The downloaded file by tool is corrupted
But it's ok to download it myself
