### ISSUE TITLE
Clean up che-theia build: rely on multistage build as much as possible.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18969]
### Is your task related to a problem? Please describe.
I tried to build che-theia from my local laptop but failed :
- Missing `yarn` command
- At the moment, yarn installation was broken on Fedora
- Missing `g++`

We are already doing most of the build in docker multistage builld, so I don't see any reason to keep this line:
https://github.com/eclipse/che-theia/blob/39b67042da45484b53af20ad1759ddaeaf19762c/build.sh#L16

### Describe the solution you'd like
Remove the line https://github.com/eclipse/che-theia/blob/39b67042da45484b53af20ad1759ddaeaf19762c/build.sh#L16
And make sure everything is done and still working in existing multistage build.

### Describe alternatives you've considered
N/A

### Additional context

![Selection_198](https://user-images.githubusercontent.com/650571/106865187-20d29d00-66cb-11eb-9630-98d3f98ace93.png)

![Selection_196](https://user-images.githubusercontent.com/650571/106865207-25975100-66cb-11eb-91ce-ea2e0e733648.png)

**Comment by benoitf** [comment]
I would say it's not so important as dogfooding is #1 priority and everything is setup in theia-dev image.

**Comment by sunix** [comment]
If we download the dependencies in the che-theia-dev build, it would benefit dogfooding UX: it won't redownload the dependencies each time you create a new workspace.

**Comment by benoitf** [comment]
well if it's to address caching of dependencies, the title is wrong.

I think time should be spent on improving dogfooding, not setuping a local build as for development mode you'll probably loose too many times on all changes you do.

**Comment by benoitf** [comment]
anyway, on your local computer, you could just have used quay.io/che-theia:dev image as well
