### ISSUE TITLE
Issue on Eclipse Che using vagrant behind firewall

### ISSUE THREAD

**Issue by muralaris** [eclipse-che/che#1897]
Hi,
I tried installing che using https://eclipse-che.readme.io/docs/usage-vagrant
and am running behind a firewall.I did configure proxy and was able to install successfully on port 9292.
I could see the following on the console:

D:\Eclipse_Che>vagrant up
ECLIPSE CHE: VAGRANT INSTALLER
ECLIPSE CHE: REQUIRED: VIRTUALBOX 5.x
ECLIPSE CHE: REQUIRED: VAGRANT 1.8.x

Bringing machine 'che' up with 'virtualbox' provider...
==> che: Checking if box 'boxcutter/centos72-docker' is up to date...
==> che: Resuming suspended VM...
==> che: Booting VM...
==> che: Waiting for machine to boot. This may take a few minutes...
    che: SSH address: 127.0.0.1:2222
    che: SSH username: vagrant
    che: SSH auth method: private key
==> che: Machine booted and ready!
==> che: Configuring proxy for Docker...
==> che: Configuring proxy environment variables...
==> che: Configuring proxy for Yum...
==> che: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> che: flag to force provisioning. Provisioners marked to run always will still run.
==> che: Running provisioner: shell...
    che: Running: inline script
==> che: #
==> che: ---------------------------------------
==> che: ECLIPSE CHE: BOOTED AND REACHABLE
==> che: ECLIPSE CHE: http://192.168.28.100:9292
==> che: ---------------------------------------
==> che: Configuring proxy for Docker...

But when i try to access http://192.168.28.100:9292, it was not reachable and timed out.

I tried to SSH into the VM on 127.0.0.1@2222 and found that the container with the name "che' was running and had the status as "Restarting before x seconds". Is this OK ?

How do i check if Che is running inside the container on port 9292.

What could have gone wrong here?

-Murali

**Che version:**   latest
**OS and version:** windows
**Docker version: 1.11
**Che install:**    Vagrant

**Comment by ghost** [comment]
@muralaris It does look like Che container never started. 

Can you ssh into the box and try to start it manually?

This is how the container is started https://github.com/eclipse/che/blob/master/Vagrantfile#L171-178

Sure thing, replace hoast and port variables with real values.

**Comment by muralaris** [comment]
Hi,
I tried to ssh and start the container with the command line as in the vagrantfile but in vain.
The container status is still "Restarting (0) 1 seconds ago" as shown below:

[vagrant@localhost ~]$ docker run --net=host --name=che --restart=always --detach -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/storage:/home/user/che/storage -v /home/user/che/conf:/container -e CHE_LOCAL_CONF_DIR=/container codenvy/che:latest --remote:192.168.28.100 --port:9292 run &>/dev/null
[vagrant@localhost ~]$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                         PORTS               NAMES
c0d56bf77097        codenvy/che:latest   "/home/user/che/bin/c"   5 seconds ago       Restarting (0) 1 seconds ago                       che
[vagrant@localhost ~]$ docker exec c0d56bf77097 bash
Error response from daemon: Container c0d56bf770976b1393295ad5654318651a16128a09a4a61ba13a645a82f63b6a is restarting, wait until the container is running
[vagrant@localhost ~]$

What could have gone wrong.
-Murali

**Comment by muralaris** [comment]
Hi,
The /home/user/che directory doesn't have the necessary bin with the che.sh executable.
I presume it should be present for Che to come up. If required, how did i miss them ?
-Murali

**Comment by ghost** [comment]
`docker pull codenvy/che:latest`
`docker run --net=host -ti -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/storage:/home/user/che/storage -v /home/user/che/conf:/container -e CHE_LOCAL_CONF_DIR=/container codenvy/che:latest --remote:192.168.28.100 --port:9292`

Can you try it this way and share logs?

I have just run it on Ubuntu - no issues found, and the OD should not matter here.

**Comment by muralaris** [comment]
Hi,
I got the following when i ran the above

[vagrant@localhost ~]$ docker run --net=host -ti -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/storage:/home/user/che/storage -v /home/user/che/conf:/container -e CHE_LOCAL_CONF_DIR=/container codenvy/che:latest --remote:192.168.28.100 --port:9292

!!!
!!! Running 'docker' succeeded, but 'docker ps' failed.
The file /var/run/docker.sock does not have appropriate permissions.
OWNER READ:  r
OWNER WRITE: w
GROUP READ:  r
GROUP WRITE: w
OTHER READ:  -
OTHER WRITE: -
Run 'sudo chmod 666 /var/run/docker.sock' to give the right permissions.
!!!

After i gave in 666 for the /var/run/docker.sock and ran again, che seemed to have come up.

Now, how do we add the same in vagrantfile to automate and fix this.
Is there any other way out ?
-Murali

**Comment by TylerJewell** [comment]
@muralaris - I am having a hard time reproducing the error. I think the flow of the issue is too broken up.  Can you please provide the exact Vagrantfile that you are using with an HTTP proxy that caused the error?  We need all of the details to attempt to reproduce the issue.

Inside of the default Vagrantfile, the /var/run/docker.sock is already set with `chmod 777 /var/run/docker.sock`, so the permissions should be suitable.

By the way, we will be moving towards more of a pure Docker launcher soon - see the instructions [here](https://eclipse-che.readme.io/v4.4/docs/usage-docker-launcher).

**Comment by ghost** [comment]
@muralaris I have tried to reproduce it and failed. Permissions for `docker.sock` are OK - https://github.com/eclipse/che/blob/master/Vagrantfile#L144

**Comment by TylerJewell** [comment]
@muralaris - any upate, please?

**Comment by muralaris** [comment]
Hi Tyler & eivantsov,
It worked me as well once started from a clean setup.Thanks again.
-murali
