### ISSUE TITLE
Redesign Get Started page & Introduce Import from git

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18975]
### Is your task related to a problem? Please describe.
Instead of Get Started, we need `Create Workspace` left nav-bar with two tabs: 
1. `Quick Add` which includes `Import from Git`(which can propose a new devfile if it's not there yet) or `Select a Sample`.
2. Custom Workspace which we used to have.
![Screenshot_20210204_135353](https://user-images.githubusercontent.com/5887312/106889251-6e153580-66f0-11eb-85fc-a4e96f56e148.png)

The details can be found at Marvelapp: https://marvelapp.com/prototype/9a777d1/screen/75865190

The old screenshot for comparing 
![Screenshot_20210204_135436](https://user-images.githubusercontent.com/5887312/106889346-8d13c780-66f0-11eb-95b1-479b38e6c3a9.png)

**Comment by sleshchenko** [comment]
The last thing that is left in the scope of this issue: when we click Enter button in the Git Repo URL field, it refreshes pages, when expectation is - trigger `Create & Open`

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1870

**Comment by themr0c** [comment]
Did the documentation receive any update on this? See: modules/installation-guide/examples/proc_che-preparing-a-private-registry.adoc
