### ISSUE TITLE
Restyle Create Custom Workspace

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18978]
### Is your task related to a problem? Please describe.
All details can be found at https://marvelapp.com/prototype/9a777d1/screen/75805138
The desired UI
![Screenshot_20210204_140439](https://user-images.githubusercontent.com/5887312/106890392-ee886600-66f1-11eb-9865-f9f2ab3aee69.png)

The existing
![Screenshot_20210204_140505](https://user-images.githubusercontent.com/5887312/106890449-ffd17280-66f1-11eb-9d32-ab94aadf4a25.png)

**Comment by akurinnoy** [comment]
I'm closing this issue because the Custom Workspace tab is not available to users anymore.
