### ISSUE TITLE
The "Happy Path" test fails on the "Wait error highlighting" step

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#18974]
### Describe the bug
The "Happy Path" test fails on the "Wait error highlighting" step:

```
12:33:34           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:34           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:34           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:35           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:35           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:35           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:35           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:35           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:36           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:36           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: ""
12:33:36           ▼ Editor.performKeyCombination title: "PetClinicApplication.java" text: "error"
12:33:37           ▼ Editor.waitErrorInLine line: "30"
12:33:37           ▼ Editor.getLineYCoordinates line: "30"
12:34:45     1) Error highlighting
12:34:45   [ERROR] CheReporter runner.on.fail: Language server validation Error highlighting failed after 70925ms
12:34:45 
12:34:45 
12:34:45   4 passing (6m)
12:34:45   1 failing
12:34:45 
12:34:45   1) Language server validation
12:34:45        Error highlighting:
12:34:45      TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //div[contains(@style, 'top:551px')]//div[contains(@class, 'squiggly-error')])' element, timeouted after 60000
12:34:45       at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:152:15)
12:34:45       at process._tickCallback (internal/process/next_tick.js:68:7)
12:34:45 
```
![screenshot-Error_highlighting](https://user-images.githubusercontent.com/22724619/106883798-250db300-66e9-11eb-94e9-c6d812fb083d.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by dmytro-ndp** [comment]
There is another Happy path test failure related to Language server validation https://github.com/eclipse/che/issues/19004

**Comment by Ohrimenko1988** [comment]
Done: https://github.com/eclipse/che/pull/18983
