### ISSUE TITLE
Fix video recording for e2e typescript tests

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#18984]
### Describe the bug
Although the screenshots are correct, in the video there is a footer that is hiding the status bar of a Che. As a consequence, we lost the ability to check if the workspace was switched to offline - which can be the root cause of LS not working and commands failing. It is reproduced on a Hosted Che, not reproduced on a nightly Che test image or 2.5/2.6 CRW test image.

### Che version

 - [ ] latest 
 - [ ] nightly
 - [ ] other: please specify 7.24.2

### Steps to reproduce
Run any video from tests.

### Expected behavior
The bottom bar in Che should be visible in the video.

### Screenshots
![Screenshot from 2021-02-04 12-16-00](https://user-images.githubusercontent.com/29278800/106901855-7e311300-66f8-11eb-9136-24db3e229597.png)

**Comment by ibuziuk** [comment]
is the issue still relevant in the context of upstream / product / workspaces.openshift.com ?

**Comment by Katka92** [comment]
Yes, we have the same problem in DevSandbox periodic tests. cc @ScrewTSW I know you wanted to work on that, I'm assigning this issue to you.

**Comment by Katka92** [comment]
This should be fixed now, right @ScrewTSW ?

**Comment by ScrewTSW** [comment]
that's correct. the video is now working as expected. closing.
