### ISSUE TITLE
Quarkus CLI run native fails with missing binary

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#18982]
### Describe the bug
When executing `Run Native` step in Quarkus CLI devfile, after the username is entered into the terminal window, the execution fails with missing binary

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: 7.25.0

### Steps to reproduce
* Start Quarkus CLI workspace
* Run `Build Native`
* Run `Run Native` and input some string

### Expected behavior
* Quarkus native application starts successfully

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: CodereadyContainers 4.6

### Screenshots
![Screenshot_20210204_102703](https://user-images.githubusercontent.com/16451875/106899978-45903a00-66f6-11eb-892c-8ae6634833da.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by sunix** [comment]
Fixed with https://github.com/eclipse/che-devfile-registry/pull/355
