### ISSUE TITLE
Copy and paste not working in the terminal

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#1899]
**Reproduction Steps:**
1. Start the latest Che from master
2. Run a command in a terminal
3. Ctrl + C and then Ctrl + V the output.

**Expected behavior:**

Text is copied and pasted

**Observed behavior:**

An error occurs (see screenshot)

**Che version:**    [4.6.0-SNAPSHOT]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]
  ![terminal](https://cloud.githubusercontent.com/assets/5337267/17033580/834a2666-4f87-11e6-9630-6c3069b946e4.png)

**Comment by thpglobal** [comment]
Still not working today - can you guys roll-back the version on beta.codenvy.com until it's fixed???

**Comment by TylerJewell** [comment]
We have a roll forward policy due to data migrations. It's labeled as a blocker and hot fix investigations are underway.

**Comment by rajat1saxena** [comment]
It seems like this issue is still there in codenvy.io IDE.

**Comment by cifren** [comment]
It seems copy is not working anymore, though paste is working.
