### ISSUE TITLE
Migrate che-operator and che-machine-exec to 'eclipse-che' organization

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#18995]
### Is your task related to a problem? Please describe.

As we speak during Eclipse Che Community call we will start to move Che related repos to new organization.
### Describe the solution you'd like

In order to migrate che-operator and che-machine-exec to new organization we should consider:

- Sync all release scripts
- Install Openshift CI github application in the new organization and related webhooks
- Make sure all tests will work in the new organization

**Comment by flacatus** [comment]
I add this consideration for now about migration to new organization. @l0rd Please feel free to change if I miss something

**Comment by sleshchenko** [comment]
cc @JPinkney 
since WTO should be adapted to these changes as well.

**Comment by sleshchenko** [comment]
I assume it's cheap if in the scope of this issue we also migrate to main default branch (instead of master)

**Comment by l0rd** [comment]
Can we avoid moving chectl? I am afraid that porting it to an eclipse foundation repo would require a review of the telemetry data we are collecting as well.

**Comment by flacatus** [comment]
@l0rd @sleshchenko Bugzilla opened: https://bugs.eclipse.org/bugs/show_bug.cgi?id=571912

**Comment by nickboldt** [comment]
Downstream issue for how this impacts CRW and how to adapt to the change: https://issues.redhat.com/browse/CRW-1661

**Comment by nickboldt** [comment]
> Can we avoid moving chectl?

Wouldn't that also require an incubation exit review, with all the attendant Eclipse Foundation paperwork and process?

**Comment by nickboldt** [comment]
Adding blocker label since as we start this change, we block Che and CRW releases, which means implementing solution to the change will be high-priority work (too bad we still don't have priority labels, eh @l0rd ? :D )

**Comment by benoitf** [comment]
hello, please ensure https://github.com/eclipse/che/blob/master/.repositories.yaml is up-to-date as well

**Comment by tolusha** [comment]
thank you.
https://github.com/eclipse/che/pull/19353
