### ISSUE TITLE
Happy path tests are failing on 'Language server validation' step

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19004]
### Describe the bug

Happy path tests are failing on the `Language server validation` step.

```
14:06:25   Language server validation
14:09:06     ✓ Java LS initialization (160259ms)
14:10:11     1) Error highlighting
14:10:11   [ERROR] CheReporter runner.on.fail: Language server validation Error highlighting failed after 65388ms
14:10:11 
14:10:11 
14:10:11   4 passing (4m)
14:10:11   1 failing
14:10:11 
14:10:11   1) Language server validation
14:10:11        Error highlighting:
14:10:11      TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //div[contains(@style, 'top:551px')]//div[contains(@class, 'squiggly-error')])' element, timeouted after 60000
14:10:11       at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:152:15)
14:10:11       at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
I checked it on a test PR without any changes: https://github.com/eclipse/che-theia/pull/695#issuecomment-775092583

### Expected behavior

The tests are happy.

### Runtime
  I detected it on PR's check

**Comment by RomanNikitenko** [comment]
@dmytro-ndp @Ohrimenko1988 
After merging https://github.com/eclipse/che/pull/18983 the issue is still actual
Please see:
- https://github.com/eclipse/che-theia/pull/695#issuecomment-775666426
- https://github.com/eclipse/che-theia/pull/778#issuecomment-775664790

**Comment by benoitf** [comment]
do you think happy path tests should use test API of Che-Theia instead ?

I mean, instead of grabbing/parsing html pages for 90% of the work, it could just execute a VS Code extension/Theia plug-in that would interact with the IDE and then at the end it displays a success or error (and only that is requiring html/css parsing ?)

**Comment by RomanNikitenko** [comment]
I think it would be really more stable.

About the current issue - from the video of the tests report it looks like the tests type some text in an editor too early - I believe typing text in couple seconds later fixes the issue.

**Comment by dmytro-ndp** [comment]
Nightly Eclipse Che E2E Happy path tests don't reproduce the issue.

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
It's still actual for `che-theia` PRs. A few minutes ago I got the same error for the test PR without any changes: https://github.com/eclipse/che-theia/pull/695#issuecomment-777500863

**Comment by RomanNikitenko** [comment]
The same `Error highlighting` here: https://github.com/eclipse/che-theia/pull/778#issuecomment-777640184

**Comment by RomanNikitenko** [comment]
The issue is pretty critical for me - I need the Happy Path tests for testing my changes related to the multi-root workspace support.
So, I spent some time investigating the problem and found the following:
-  the [workaround](https://github.com/eclipse/che/blob/ccbf9cebaf23c016aea3e57f7b009ec8c9f23e83/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts#L125-L126) is not working
I analyzed a video provided by the tests + my logs and I didn't see the refreshing a page (it's used as workaround)
- I detected that the `setPreference` request to set `application.confirmExit` to `never` value failed with `status: 400, statusText: 'Bad Request'`. 
If I understand correctly - it's used to avoid asking about confirmation of refreshing a page. 
So - can the failed request be the cause of the problem that the test can not reload a page? 
- I [commented above](https://github.com/eclipse/che/issues/19004#issuecomment-776522217) my guess about the cause of the current issue - that the tests type some text in an editor too early. I added some delay before typing a text (just for testing) to the corresponding `Happy Path` test. The result - the test passed successfully a couple of times. You can see it on the video or using logs [here](https://github.com/eclipse/che-theia/pull/778#issuecomment-777797978), for example (the tests failed this time due to another cause - related to debug functionality).  

I think there is no problem related to IDE, but some changes are required on `Happy Path` tests side.

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: thank you for investigation!
It is really strange that it was required 20 seconds wait before typing into the Editor, and that 120 seconds were not enough to highlight error.

May be there is an answer in fresh [test workspace logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2417/artifact/logs-and-configs/workspace-logs/):
- [Che-theia container logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2417/artifact/logs-and-configs/workspace-logs/theia-ide3n2-container.log/*view*/):
```
2021-02-16 13:18:33.480 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at https://serverd0uocwc5-jwtproxy-server-4403.10.0.208.69.nip.io/bundle.js:44:363191 
```

- [cscode-java container logs](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2417/artifact/logs-and-configs/workspace-logs/vscode-javal1i-container.log/*view*/)
```
{
  message: 'Starting Java server with: /usr/lib/jvm/default-jvm/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /tmp/vscode-unpacked/redhat.java.latest.qziqhjeouo.java-0.69.0-2547.vsix/extension/server/plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -configuration /home/theia/home/theia/redhat.java/0.69.0/config_linux -data /home/theia/home/theia/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2021-02-16 13:15:58.252'
}
{
  message: '[Error - 1:16:07 PM] Feb 16, 2021, 1:16:07 PM Failed to build workspace.\n' +
    'jdt.ls-java-project does not exist\n' +
    'Java Model Exception: Java Model Status [jdt.ls-java-project does not exist]\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:583)\n' +
    '\tat org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:256)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:267)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getPackageFragmentRoots(JavaProject.java:2322)\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getPackageFragments(JavaProject.java:2346)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.cleanupResources(ProjectsManager.java:214)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.buildWorkspace(BuildWorkspaceHandler.java:53)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:815)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$50(JDTLanguageServer.java:981)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)\n' +
    '\tat java.base/java.lang.Thread.run(Thread.java:834)\n',
  level: 'info',
  timestamp: '2021-02-16 13:16:07.842'
}
```

**Comment by RomanNikitenko** [comment]
> It is really strange that it was required 20 seconds wait before typing into the Editor, and that 120 seconds were not enough to highlight error.

@dmytro-ndp 
As I mentioned above for my current issue it's pretty critical to have `Happy Path` tests working. So, I added a delay to `Language server validation` step. You can see my changes [here](https://github.com/eclipse/che/compare/devfile-workspace-root) - actually it's just one line with the delay 20 seconds:
```
await driverHelper.getDriver().sleep(20000);
```
Maybe 20 seconds is too long delay - I don't know - it's just a workaround for testing my changes. 

Today I rerun the tests 5 times, `Language server validation` test passed successfully without any exception.
You can see it in the corresponding reports:
- https://github.com/eclipse/che-theia/pull/778#issuecomment-780435869
- https://github.com/eclipse/che-theia/pull/778#issuecomment-780459085
- https://github.com/eclipse/che-theia/pull/778#issuecomment-780651105
- https://github.com/eclipse/che-theia/pull/778#issuecomment-780705026
- https://github.com/eclipse/che-theia/pull/778#issuecomment-780759452

The tests failed due to another issue: https://github.com/eclipse/che/issues/19085.

**Comment by dmytro-ndp** [comment]
Should be fixed in https://github.com/eclipse/che/pull/19068
