### ISSUE TITLE
[devworkspace-che] Honor endpoints declaring their support for singlehost

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#19008]
### Is your enhancement related to a problem? Please describe.
In devworkspaces we have no distinction between plugins and devfile endpoints as we used to have in devfile1. Because singlehost requires the endpoints to correctly run behind a reverse proxy, we cannot switch it on by default. Therefore we need to introduce a new endpoint attribute, maybe something like `webroot-independent`, which the endpoints will be able to set to true, at which point they will be deployed on a subpath behind a reverse-proxy in singlehost mode. Otherwise the endpoints will require their own ingress/route even in the singlehost mode.

### Describe the solution you'd like
This attribute is specific to che and therefore cannot be made a property of the endpoint itself. Instead we need to make it just an attribute on the endpoint.

**Comment by l0rd** [comment]
@metlos you are excluding the option to use devfile v2 `endpoints[].exposure` field right? In other words users won't be able to specify, using a devfile, that their application won't work with path-rewriting based endpoints.

**Comment by metlos** [comment]
> @metlos you are excluding the option to use devfile v2 endpoints[].exposure field right? In other words users won't be able to specify, using a devfile, that their application won't work with path-rewriting based endpoints

The endpoint exposure can be only "public", "internal" or "none", none of which can express whether an endpoint can "live" behind a path-rewriting reverse proxy... Currently I'm thinking about a new endpoint attribute, similar to `unique`, for which the best name I could come up with is `relocatable`, defaulting to `false`. I.e., as we discussed, only the endpoints that mark themselves as relocatable will be put on a sub path. By default, endpoints will be on subdomains.

**Comment by l0rd** [comment]
@metlos makes sense. Other options for the field name: `urlRewritable`, `urlRewriteSupported`...

**Comment by metlos** [comment]
We had a discussion about this a while back and ruled out `relocatable` as too difficult to understand, because it doesn't really suggest that it influences the ability to function behind a path-rewriting reverse proxy.

So we're left with these options:
* `urlRewritable`
* `urlRewriteSupported`
* `pathRewriteSupported`

I've looked at a couple of reverse proxies and the following terms are used for this concept:

* `IIS` uses `url rewrite`
* `nginx` use "rewrite" of URIs, while the nginx ingress controller has a notion of `rewrite-target`, nginx can also modify the headers though
* `httpd` talks about `request mapping` in its `ProxyPass` directive and `URL rewriting` in `mod_rewrite` (but can match on headers, etc)
* `traefik` has a lot of rules for changing the requests including `ReplacePath`, but also has ability to modify incoming/outgoing request headers, ...
* `haproxy` has vast number of options for rewriting and talks mostly about `request rewriting`

 So in most cases, we can see that the proxies talk about some kind of rewriting. Many of them support more than just path rewriting. They mostly are able to modify the request (and response) in all of its aspects.

In our use case, we need the endpoints to declare that they are capable of functioning behind a reverse proxy that rewrite the domain and path of the incoming requests, but will not touch the response body (but may add some headers).

Therefore I personally lean towards `urlRewriteSupported` - it is simple enough to understand and uses familiar terminology.

**Comment by sleshchenko** [comment]
The issue on devfile api side https://github.com/devfile/api/issues/230
