### ISSUE TITLE
chectl should deploy devworkspace-che-operator when the engine is devworkspace

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#19001]
### Is your enhancement related to a problem? Please describe.
There is the new github.com/che-incubator/devworkspace-che-operator for handling che-specific parts of devworkspaces. Chectl should deploy it so that devworkspaces with the `che` routing class can be handled correctly.

### Describe the solution you'd like
 chectl should deploy the devworkspace-che-operator (along with devworkspace-operator) when the engine is devworkspace

### Additional context
We should also probably think about how this is going to happen in OLM.

**Comment by sleshchenko** [comment]
Please pay attention on https://github.com/eclipse/che/issues/19121, so maybe it does not make sense to make chectl apply Che DevWorkspace Operator resources.

**Comment by metlos** [comment]
Superseded by #19142.
