### ISSUE TITLE
Dashboard does not reset workspace name when field is cleared

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#19014]
### Describe the bug
If you enter a workspace name in the "create custom workspace" page and then erase the value, the field is left invalid.

![Peek 2021-02-09 12-11](https://user-images.githubusercontent.com/16168279/107400710-16037800-6ad0-11eb-9738-b37dfed3c226.gif)

My assumption would be that the default value for the field is used whenever the field is blank.

### Che version
- [x] nightly

### Steps to reproduce
1. Go to "create custom workspace" page
2. Note "Workspace name" field is valid and devfile contains `generateName: wksp-`
3. Enter text into the "Workspace name" field
4. Devfile gets `name: <entered value>`
5. Delete text in "Workspace name" field
6. Devfile `.metadata.name` is deleted, devfile is now invalid

### Expected behavior
If the user clears the text in the workspace name box, the devfile should go back to the earlier state (default to `generateName: wksp-`)

### Runtime
   - [x] Openshift (include output of `oc version`)

**Comment by amisevsk** [comment]
:neutral_face:

**Comment by akurinnoy** [comment]
I'm closing this issue because the Custom Workspace tab is not available to users anymore.
