### ISSUE TITLE
Enabling multi-arch support missing for 15  sidecar images of che-plugin-registry

### ISSUE THREAD

**Issue by bivasda1** [eclipse-che/che#19025]
### List of pending sidecar images to enable multiarch support
1.asciidoc
 https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/asciidoc/PLATFORMS
2.bazal
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/bazel/PLATFORMS
3.camelk
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/camelk/PLATFORMS
4.clang
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/clang/PLATFORMS
5.dart
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/dart/PLATFORMS
6.dotnet
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/dotnet/PLATFORMS
7.flutter
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/flutter/PLATFORMS
8.go
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/go/PLATFORMS
9.haskell
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/haskell/PLATFORMS
10.protobuf
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/protobuf/PLATFORMS
11.rust
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/rust/PLATFORMS
12.scala
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/scala/PLATFORMS
13.shellcheck
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/shellcheck/PLATFORMS
14.tekton
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/tekton/PLATFORMS
15.vale
https://github.com/eclipse/che-plugin-registry/blob/master/sidecars/vale/PLATFORMS

**Comment by ghatwala** [comment]
hi @ericwill , attempting to make che-plugin registry image as multi-arch as per https://issues.redhat.com/browse/CRW-1475?focusedCommentId=15721358&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#com[…]1358, out of the 25 sidecar images  , we know that around 11 plugin sidecar images(popular ones) are multi-arch already , do we need all the 25 plugin sidecars to be Multi-arch or can we go with current working list of  around 11 sidecars and work towards making che-plugin-registry image as multi-arch , please let us know your thoughts ?

**Comment by ericwill** [comment]
> hi @ericwill , attempting to make che-plugin registry image as multi-arch as per [https://issues.redhat.com/browse/CRW-1475?focusedCommentId=15721358&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#com[…]1358](https://issues.redhat.com/browse/CRW-1475?focusedCommentId=15721358&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#com%5B%E2%80%A6%5D1358), out of the 25 sidecar images , we know that around 11 plugin sidecar images(popular ones) are multi-arch already , do we need all the 25 plugin sidecars to be Multi-arch or can we go with current working list of around 11 sidecars and work towards making che-plugin-registry image as multi-arch , please let us know your thoughts ?

We don't need all sidecar images to be present for multi-arch, no. But there should be some logic that does not build plugins on non-supported arches. For example if the `vale` sidecar does not support multi-arch, then all plugins in `che-theia-plugins.yaml` using the `vale` sidecar shouldn't be built on arches where it's not available. By built I mean we shouldn't generate `meta.yaml` for them as part of the build process.
