### ISSUE TITLE
[che-server] Provide devfile v2 schema on REST API

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#19023]
### Is your enhancement related to a problem? Please describe.

The dashboard needs to access the devfile v2 schema for autocompletion, validation, hover, etc

### Describe the solution you'd like

Che-server provides a rest api for accessing the devfile v2 schema, similar to what it does for v1

### Additional context

https://github.com/eclipse/che/pull/19012#discussion_r573276721

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che/pull/19043
