### ISSUE TITLE
The first phase of workspace start is silent

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19027]
### Describe the bug
There is pretty big delay (how big depends on the cluster) when workspace is starting but no logs are provided.

As far as I see during this phase the following happening:
1. mkdir pod
2. plugin brokering # It's the isssue on dashboard side https://github.com/eclipse/che/issues/19028
3. again mkdir

It would be great if Che Server could propagate info about pods which are created, to make sure that delay is related to K8s.

P.S. I know we're moving to DevWorkspace but it should be pretty easily to generate logs on Che Server side.

https://user-images.githubusercontent.com/5887312/107492951-b079bf00-6b95-11eb-8429-7649e8981d0e.mp4

**Comment by sleshchenko** [comment]
The alternative resolution for this issue can be disabling mkdir pod since it should be redundant on newer K8s https://github.com/kubernetes/kubernetes/issues/97460

**Comment by sleshchenko** [comment]
After bug on dashboard is fixed and plugin broker logs are propagated, on my RHPDS cluster it takes ~20 seconds to pass mkdir phase and first log line appear

**Comment by amisevsk** [comment]
I suspect the reason it takes so long is that it seems by default the `mkdir` container used is just `centos`, which is `209MB`

**Comment by ibuziuk** [comment]
> The alternative resolution for this issue can be disabling mkdir pod since it should be redundant on newer K8s kubernetes/kubernetes#97460

I would love to disable `mkdir` on Sandbox since this is indeed time-consuming. In which version of k8s it is going to be fixed?

**Comment by amisevsk** [comment]
Based on the relevant [commit](https://github.com/kubernetes/kubernetes/commit/19c9cf7a2036509cc891e356cc72319852f8c541) it looks like it's coming in `1.21`. We'd also need to validate that the PR actually resolves the issue -- I haven't done that yet -- but I agree it would be _great_ to get rid of this functionality.

**Comment by ibuziuk** [comment]
heh, on OSD we are currently running against `v1.19.0+1833054 `

**Comment by ibuziuk** [comment]
OpenShift 4.9 is going to be based on k8s 1.22 (release date https://www.kubernetes.dev/resources/release/). Currently, workspaces.openshift.com is running against 4.7.16 / k8s v1.20.0+2817867

**Comment by ibuziuk** [comment]
The Developer Sandbox clusters have been updated to 4.8.11 (v1.21.1+9807387). We should check if it is possible to disable the mkdir pods on the workspaces.openshift.com https://github.com/eclipse/che/issues/19027#issuecomment-788059995

**Comment by skabashnyuk** [comment]
@ibuziuk is it makes sense to keep this issue open? Do you have any plans for it?

**Comment by amisevsk** [comment]
IMO this issue can be closed. What we talk about with "phases of workspace start" is completely different under DWO (and there should be at least some info immediately in that case).
