### ISSUE TITLE
Refreshing "Create custom workspace" page sometimes does not populate existing workspaces

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#19020]
### Describe the bug
Refreshing the "Create custom workspace" page sometimes leaves the list of existing workspaces empty on load:

![workspaces-list](https://user-images.githubusercontent.com/16168279/107406582-988f3600-6ad6-11eb-8883-383b7d3bae8a.gif)

Reproduces in Chrome and Firefox. In the browser console, I see
- there's a call to `/api/workspace` that returns HTTP 200 and the list of workspaces
- There's an error logged: 
    ```
    client.js:1 Uncaught (in promise) Error: Failed to request workspaces: 
    InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
        at client.js:1
        at async Ht.updateWorkspaces (client.js:1)
    ```

<details>
<summary>Full log</summary>

  | eval | @ | index.ts?81d4:245
-- | -- | -- | --
  | async function (async) |   |  
  | updateWorkspaces | @ | PreloadData.ts?ede8:103
  | init | @ | PreloadData.ts?ede8:62
  | async function (async) |   |  
  | init | @ | PreloadData.ts?ede8:54
  | eval | @ | index.tsx?ec1a:33
  | ./src/index.tsx | @ | client.js:54674
  | __webpack_require__ | @ | client.js:833
  | fn | @ | client.js:130
  | 0 | @ | client.js:55094
  | __webpack_require__ | @ | client.js:833
  | (anonymous) | @ | client.js:971
  | (anonymous) | @ | client.js:974

</details>

    but I see the same error when workspaces are correctly populated

### Che version
- [x] nightly

### Steps to reproduce
1. Create a few workspaces
2. Navigate to "Create custom workspace" page
3. Refresh
4. Workspaces list is empty in sidebar

**Comment by amisevsk** [comment]
When this occurs, it's necessary to refresh the page again (on a different tab) to populate the list of workspaces
![workspaces-need-refresh](https://user-images.githubusercontent.com/16168279/107407912-451de780-6ad8-11eb-9c44-ec988f45fc18.gif)

**Comment by amisevsk** [comment]
This also seems to happen when a factory URL link is used.

**Comment by sleshchenko** [comment]
Reproduced. It does not depend on the page which is opened. Oleksiis know the reason and will provide fix later

**Comment by sleshchenko** [comment]
I think it's related to this precache issue as well, if no - a dedicated issue should be created:
![Screenshot_20210215_143730](https://user-images.githubusercontent.com/5887312/107947725-75afc680-6f9b-11eb-8cfc-580321747eae.png)
