### ISSUE TITLE
Unable to deploy che with server:deploy command

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19033]
### Describe the bug
on a github action job I got:

```
Calling chectl server:deploy...
› Current Kubernetes context: 'minikube'
    SyntaxError: /home/runner/.cache/chectl/next-update-info.json: Unexpected 
    end of JSON input
stack=Error: Command failed with exit code 1: chectl server:deploy --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/tmp/custom-resource-patch.yaml --chenamespace=eclipse-che
    SyntaxError: /home/runner/.cache/chectl/next-update-info.json: Unexpected 
    end of JSON input
```

### Steps to reproduce

```
$ minikube start ...
...
$ chectl server:deploy --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/tmp/custom-resource-patch.yaml --chenamespace=eclipse-che
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     chectl/0.0.20210210-next.64ce295 linux-x64 node-v12.20.1

**Comment by tolusha** [comment]
I can't reproduce it locally.
What is the action job ?

**Comment by benoitf** [comment]
it happened there: https://github.com/eclipse/che-plugin-registry/runs/1872675606?check_suite_focus=true

I suppose there is something not robust that may lead to corrupted data on server:deploy/update/check command.
