### ISSUE TITLE
Che editors should be defined using Devfile v2 syntax

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19034]
### Is your enhancement related to a problem? Please describe.

Editors in [che-editors.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml) are defined using the legacy meta.yaml syntax. We should consider moving to the [devfile v2 spec](https://docs.devfile.io/devfile/2.0.0/user-guide/api-reference.html). 

That should help transforming editors definitions into a `DevWorkspaceTemplates`.

### Additional context

That's required for https://github.com/eclipse/che/issues/18668

**Comment by sleshchenko** [comment]
The issue to generate devfiles v2 on plugin registry side https://github.com/eclipse/che/issues/19060

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1867
