### ISSUE TITLE
Allow to execute plug-ins in some user container instead of the sidecars provided by plug-ins.

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19050]
### Is your enhancement related to a problem? Please describe.
Sometimes I've a user runtime and I've plug-ins using the same runtime.
I could opt-in to say that plug-ins could run in my user container

### Describe the solution you'd like
Allow to say in devfile to launch plug-ins in my user containers instead of the pre-defined sidecar.

### Describe alternatives you've considered
it may be interesting option for bootstrapping/single terminal/specific use cases

### Additional context

cc @l0rd

**Comment by sleshchenko** [comment]
Do we need it for Che Workspace or DevWorkspace?
If the second, it's not plugin broker (which is going to be fully deprecated).

**Comment by benoitf** [comment]
tagging with DevWorkspace even if it would have been nice for Che Workspace

**Comment by benoitf** [comment]
support added for devWorkspaces using devfile v2 attribute
```yaml
che-theia.eclipse.org/sidecar-policy: USE_DEV_CONTAINER
```
