### ISSUE TITLE
Devfile tests has problems with workspace removal

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#19053]
### Describe the bug
At the end of a devfile test, the workspace should be removed using the dashboard. Comming with the new dashboard, it seems there is an issue with workspace removal - the wrong pop-up is opened.
This behavior is consumed downstream too so may cause some problems there as well.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run the test suite that runs all the devfiles. Maybe it would also work to pre-create one workspace and then run some devfile test case (not tested).

### Expected behavior
All workspaces should be removed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/29278800/107765472-33378100-6d32-11eb-98c8-f363e3924f44.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Test logs
```
07:01:35      Stop and remove workspace
07:01:35            ▼ Dashboard.stopAndRemoveWorkspaceByUI "nodejs-3fh5k"
07:01:35            ▼ Dashboard.openDashboard
07:01:36            ▼ Dashboard.waitPage
07:01:37            ▼ Dashboard.clickWorkspacesButton
07:01:37            ▼ Workspaces.waitPage
07:01:37            ▼ Workspaces.waitWorkspaceListItem "nodejs-3fh5k"
07:01:37            ▼ Workspaces.waitWorkspaceWithRunningStatus "nodejs-3fh5k"
07:01:37            ▼ Workspaces.stopWorkspaceByActionsButton
07:01:37            ▼ Workspaces.waitWorkspaceListItem "nodejs-3fh5k"
07:01:37            ▼ Workspaces.openActionsPopup for the 'nodejs-3fh5k' list item
07:01:37            ▼ Workspaces.clickActionsButton of the 'nodejs-3fh5k' list item
07:01:37            ▼ Workspaces.waitActionsPopup of the 'nodejs-3fh5k' list item
07:01:42            ▼ Workspaces.clickActionsStopWorkspaceButton for the 'nodejs-3fh5k' list item
07:01:43    [ERROR] DriverHelper.waitAndClick - failed with an unexpected exception - WebDriverError: element click intercepted: Element <button tabindex="-1" data-key="2" disabled="" type="button" class="pf-m-disabled pf-c-dropdown__menu-item">...</button> is not clickable at point (1788, 461). Other element would receive the click: <li role="menuitem">...</li>
07:01:43      (Session info: chrome=87.0.4280.141)
07:01:43    Build info: version: '4.0.0-beta-1', revision: '02d5e641d5'
07:01:43    System info: host: 'minikube-rhel7-24gb-895', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.el7.x86_64', java.version: '1.8.0_275'
07:01:43    Driver info: driver.version: unknown
07:01:43        10) Stop and remowe workspace
07:01:43    [ERROR] CheReporter runner.on.fail: NodeJS Express Web Application test Stop and remove workspace Stop and remowe workspace failed after 8051ms
```

**Comment by ScrewTSW** [comment]
seen 19 times over the weekend

**Comment by dmytro-ndp** [comment]
@Katka92, @ScrewTSW: could you, please, check whether it still actual?

**Comment by ScrewTSW** [comment]
Yes, it still is, working on a fix

**Comment by dmytro-ndp** [comment]
@ScrewTSW : thanks.
I have set appropriate `team/hosted-che` label.

**Comment by Katka92** [comment]
This issue is not happening anymore. Closing issue
