### ISSUE TITLE
Start in backgroud action tries to use expired token

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19058]
### Describe the bug
I don't have a good steps to reproduce that I face the issue that start in backgroud used expired token.
Probably I left tab without any activity for some period and when returned back - got this issue.
![Screenshot_20210209_190016](https://user-images.githubusercontent.com/5887312/107773131-e198f180-6d45-11eb-8a24-bb02cc8940c0.png)

**Comment by sleshchenko** [comment]
Is may be related to https://github.com/eclipse/che/issues/19045

**Comment by vitaliy-guliy** [comment]
I cannot stop the workspace after working some time in the IDE and then switching back to the dashboard

![Screenshot from 2021-02-18 12-27-54](https://user-images.githubusercontent.com/1655894/108343709-eac20c80-71e4-11eb-89ad-a48a97720968.png)
