### ISSUE TITLE
Generates devfile v2 entries in addition to meta.yaml entries generated from che-editors/che-plugins yaml files

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19060]
### Is your task related to a problem? Please describe.
plugin-broker is consuming for now meta.yaml from the plug-in registry.
With devfile 2, consumers won't be able to consume 'meta.yaml' format.
As we have a central/pivot format, we can generate both meta.yaml and devfile v2 entries

### Describe the solution you'd like
generate devfile entries from che-editors.yaml and che-plugins.yaml files

### Describe alternatives you've considered
step2: could convert the che-editors.yaml and che-plugins.yaml to be devfile 2.0 objects (and still generate meta.yaml/devfile.yaml)

### Additional context
There is some limitation on devfile 2.0 consumer like dev workspace operator, s:
1. it shouldn't generate entries with secure/true
2. 127.0.0.1 listening is not supported so it should be mapped to 0.0.0.0

cc @sleshchenko please provide any input about current limitations that I've not listed

**Comment by sleshchenko** [comment]
If I'm not mistaken, currently Che Plugin Broker overrides plugins entrypoint to use remote-runtime binary, with devworkspace and devfile, that's plugin registry who should provision that stuff into plugin's definition.

**Comment by benoitf** [comment]
@sleshchenko good question/feedback. Will need to think on who will set that variable. Probably che-theia that will take care of plug-ins as value is defined in che theia current meta.yaml definition

But management of theia plug-ins is for milestone 2 (so still some time to think about it)
