### ISSUE TITLE
Remove che-theia `yarn build` mandatory PR check

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19066]
### Is your enhancement related to a problem? Please describe.
There is a mandatory PR check on the che-theia repository. The PR check fails for pull request https://github.com/eclipse/che-theia/pull/948. However, the code in the pull request compiles just fine when it is compiled against Theia master (as our production code is). So IMO, this is a false positive and mandatory PR checks should never prevent us from merging correct code.

### Describe the solution you'd like
Remove the PR check, we have other checks that ensure the code builds correctly.

### Describe alternatives you've considered
We could fix the build to be realistic, but we already have other checks that ensure that the code works.

**Comment by benoitf** [comment]
if yarn.lock is updated it should work as expected

**Comment by benoitf** [comment]
also this PR check is launching the tests/linters, so removing this check will remove the tests/linters

**Comment by tsmaeder** [comment]
Note that the "linkless build" proposal would get rid of the two ways to build che-theia. Then the "node build" and the "pr build" would be the same.

**Comment by tsmaeder** [comment]
It has been proposed to remove the yarn.lock file from the repo, but that would break when Theia introduces a breaking change (and we fix the "real build" by pointing to an older Theia commit".

**Comment by azatsarynnyy** [comment]
We have to make sure that Che-Theia build is green in both cases:
1/ when we get the Theia framework and customize it with our extensions + plug-ins
2/ when we get any Che-Theia's extension or plug-in and build it separately

The 1'st case is important because this is how we build our product.
The 2'nd one is important as well because we're distributing some parts of Che-Theia as npm packages through npmjs.org. And we have to make sure that each package builds successfully before publishing it to npmjs.

**Comment by tsmaeder** [comment]
> The 2'nd one is important as well because we're distributing some parts of Che-Theia as npm packages through npmjs.org. And we have to make sure that each package builds successfully before publishing it to npmjs.

If we distribute the packages as npm modules, we should start versioning them properly. Currently, they're all stuck at `0.0.1`

**Comment by tsmaeder** [comment]
@azatsarynnyy where does the code releasing the che-theia packages live?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy where does the code releasing the che-theia to npm packages live?

@tsmaeder it's here https://github.com/eclipse-che/che-theia/blob/master/.github/workflows/release.yml
