### ISSUE TITLE
che-operator build failed for linux/s390x platform

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19065]
### Describe the bug
che-operator multi-platform build failed
https://github.com/eclipse/che-operator/actions/runs/566993292

### Additional context

Build failed for `linux/s390x` platform

**Comment by rhopp** [comment]
@cwsolee Is this something your team would like/should work on?

**Comment by cwsolee** [comment]
@rhopp We're certainly interested to find out more but we're working on other che issues right now, wonder whether those issues are similar to this. We'll take a look at this one too.

**Comment by flacatus** [comment]
Thank you @cwsolee ! I would like to add from Deploy Team side we are detecting this problem in all golang projects :(

**Comment by cwsolee** [comment]
@rhopp My team has been debugging and root problem is the version of qemu that is being used. While debugging, we've noticed that newer version(v6.0.0-rc1) seems to solve our problem. Qemu v6 GA is set to be 4/20 now, our plan is to PR the use of this latest qemu when it's out. We could consider PR now to use rc1 if we don't want to wait, any preference?

**Comment by tolusha** [comment]
@cwsolee 
Thank you for update.
We can wait until `Qemu v6 GA`  is released

**Comment by tolusha** [comment]
@cwsolee 
Hello. Any updates?

**Comment by cwsolee** [comment]
Qemu V6 just released, it contain a number of fixes for z, done by multiple teams, worth a try. We're working on a separate effort to use Travis to build because native build is always more stable. Machine-exec is building with Travis now, Theia will be next, if both looks stable for a while, we'll start enabling others.
