### ISSUE TITLE
Initialize devworkspace client

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19071]
### Is your task related to a problem? Please describe.
DevWorkspace + Dashboard integration depends on the https://github.com/JPinkney/devworkspace-client
And we should move it somewhere in a common place.

From DevWorkspace Cabal meeting:
we're not sure that we need that library on devfile side at this point, so the option that we chose for start http://github.com/che-incubator/devworkspace-che-client (or che-devworkspace-client but we already have https://github.com/che-incubator/devworkspace-che-operator)

That library should have a methods to work with DevWorkspace or DevWorkspaceTemplates.
We keep in mind that we may need later migrate it to devfile organization, or it should keep be Che independent:
- K8s API endpoint (dashboard can configure Che Server unsupported, che theia can configure K8s API directly)
- namespace (Theia use DEVWORKSPACE_NAMESPACE env var, Dashboard use value from Che Server default namespace)
- authentication: token should be parameter, Dashboard does not specify it(Che Server handles it), Che Theia specifies it from /var/.../serviceaccount/token);

In addition, this library can have Che dependent functions, like resolve DevWorkspaceTemplate from che editor reference.

**Comment by benoitf** [comment]
For now this library can't be used for che-theia as it's using `/api/unsupported/k8s` and che-theia has no idea about che-api server
Also che-theia is server side and has access to K8s api directly so no need to use http/axios layer with proxy stuff.

**Comment by sleshchenko** [comment]
The described library is initialized but it's needed to check what is missing and create dedicated issues for found items if any https://github.com/che-incubator/devworkspace-client
