### ISSUE TITLE
[UD] should have a simple way to stop a workspace

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19072]
### Describe the bug
With Dashboard next, it is not convenient to stop a workspace.
right click on the left bar workspace item is not showing any menu and action to stop the workspace.

### Che version

 - [x] latest 7.26.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. start a workspace
2. right click on the workspace

### Expected behavior
3. expected to have the menu with the `stop` action but got the default browser context menu

### Screenshots
![Selection_228](https://user-images.githubusercontent.com/650571/107977637-ba4b5a00-6fbb-11eb-98a4-b2694136e43b.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by ibuziuk** [comment]
@sleshchenko set P2, but if you think it is an important UX pitfall feel free to put P1

**Comment by sunix** [comment]
@sleshchenko this is very annoying from the user perspective. Even though I am aware of that issue, I am still looking where is that `stop` button is everytime I want to stop a workspace.
At the moment, ...

1. click in `workspaces`
2. find the right workspace to stop
3. right click on "..." button
4. scroll ... (my workspace is at the very bottom of the page, and the menu is not visible)
5. click `stop workspace`

**Comment by sleshchenko** [comment]
On the UX call we agreed that it's better to avoid context menu in left-nav bar, it's not recommended by Patternfly framework we currently use due issues with accessibility, discoverability and support for touch devices.
But we agreed that that's needed to find how we can implement shortcuts for left-nav bar items to Start/Stop, Open Workspace Details.
Parvathy will take a look how we can handle it and come with proposal.

**Comment by parvathyvr** [comment]
@sunix @sleshchenko I have created a design document that shows the various menu options available to different workspace statuses under 'Recent Workspaces'. Please Review-Thanks!
Link to Design doc-https://docs.google.com/document/d/1IQy5RJhvXTjK6mp7sx_ZMfsammOFjY_pUOmt4jQWH7c/edit#heading=h.tzfrhoaq09as .A link to the Marvel prototype can be found inside the design doc.
