### ISSUE TITLE
[UD] UX: should have 1 single workspace page and not 2

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19073]
### Is your enhancement related to a problem? Please describe.
In the new user dashboard, there is a new workspace page with workspace loading page.
It is confusing for the user to have 2 kind of page for the same thing: one to see the workspace details and devfile, and another one to see the logs and loading sequence.

### Describe the solution you'd like
have a single page with all the tabs

### Additional context
![Selection_232](https://user-images.githubusercontent.com/650571/107977980-4f4e5300-6fbc-11eb-9219-cd2092d65596.png)
![Selection_231](https://user-images.githubusercontent.com/650571/107977987-537a7080-6fbc-11eb-87aa-a83d69612f86.png)

**Comment by sleshchenko** [comment]
The first impression that it would be so convenient to review workspace devfile and switch back to start the process.
But start workspace page opens IDE once workspace is running, when you're on workspace details, it's not clear for me when IDE should be opened.

**Comment by sunix** [comment]
I think it is fine to do a redirect once it is ready if the user is in the progress or the log tabs.
But if the user is coming back, he should see the progress page as it is and maybe a link to redirect to the IDE next to "Open IDE"

**Comment by sleshchenko** [comment]
It was discussed on UX Call, and we agreed that it's not really two pages for workspace, because Workspace Start Progress is just an intermediate state before IDE is opened.
Nobody was confused when it was just Loader with logs, now it's a similar look that may cause confusion but we don't have a plan to address it at this point.
But we may revisit it after we see more peoples' reactions.

**Comment by sunix** [comment]
To me it was already confusing before: it was already painful, for instance, how to find back the devfile editor of a running workspace. Some users don't even know that the devfile editor exists after days using Che.
But this is now even worse with the new layout. So adding confusion to confusion is definitely making the user experience very poor. It is not equaly poor, it is worse.

**Comment by sympatheticmoose** [comment]
Sorry @sunix but I really can't see what is so different and 'even worse/adding confusion'? 

There was a workspaces page which shows you all your existing workspaces and clicking a workspace brings you into the editor. Same as before. 

When you start a workspace, it your context switches to the appropriate one in the recent workspaces list and you can see loading progress. Now, there is no 'workspace loading page' as a first class 'thing' - it's a temporary screen whilst the workspace loads replacing the crane animation. I would argue minimal change. A potential issue here is inconsistency between what clicking a workspace does, between in the workspaces menu and the recent workspaces list and we're investigating options there, but as a potential problem it existed before and now.

**Comment by sunix** [comment]
I don't think saying that because a problem was there before, it should be minimized. We had inconsistency that was causing confusion and this is amplifying the confusion when navigating.

Can we prioritize this based on what the problem it is causing and not based on what it was doing in the previous dashboard?

The question is how can we simplify the user experience to get where he wants to go:
- I am in the ide, I want to rename the workspace name, or add a postgresql container to the devfile 
- I started a workspace but it fails to start because of memory limit, I want to quickly modify the devfile and change the memory limit of one component.

I can find more examples: at the moment, you get through minimum 3 pages to get where you want to go. Maybe never if I am a new user. Maybe we can find another way rather then having 1 single page for the workspace. But that way we would bring consistency as well as simplifying the navigation and the user experience.

**Comment by sunix** [comment]
In term of implementation, we would avoid duplication of code.

**Comment by sunix** [comment]
Then I don't say it should be done urgently. But p3 sounds like it never gonna get done.

**Comment by sympatheticmoose** [comment]
>I don't think saying that because a problem was there before, it should be minimized.

Nowhere did I say this. Your comments on the new implementation were that things were "even worse", which I was challenging as an unfair assessment, and that there was an issue with inconsistency which existed before and still needs to be addressed.

> how can we simplify the user experience to get where he wants to go

I agree this is what needs to be explored, and having use cases helps here. The transient loading screen looking similar to the workspaces page, personally I cant see how it causes _excessive_ confusion. However, in the case of a workspace failing to start as you mention - it could be useful to be 'next' to the devfile editor and to have the ability to make changes and restart.

> I am in the ide, I want to rename the workspace name, or add a postgresql container to the devfile

Is renaming really something a user would want to do often? Why within the IDE? Generally as I understand we're not yet able to properly link between the running workspace and a devfile present in the project, so I'm not sure we can solve this without having to come out of the IDE. Maybe a 'Go to workspace definition' or similar menu item would be useful. Would be interested in your ideas there.

**Comment by sunix** [comment]
> Nowhere did I say this. Your comments on the new implementation were that things were "even worse", which I was challenging as an unfair assessment, and that there was an issue with inconsistency which existed before and still needs to be addressed.

From my perspective, it is more confusing because I think I am in the right page but I am not. At least before it was completely different UI. Then having the same UI make sense if we merge the 2 pages.
 

> Is renaming really something a user would want to do often? Why within the IDE? 

I often rename my workspaces because I use 1 workspace per task or issue, which Che is really great for. So I rename the workspaces not be lost in the several issue i may work. I could have 4 workspaces from the same devfile: 1 for the feature i am working on, 2 for the PR that haven't been merged and the last one for the PR i am reviewing.
