### ISSUE TITLE
Remove non-devfile workspaces related logic

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19082]
### Is your task related to a problem? Please describe.

We don't support non-devfile workspaces AFAIK.
But there is still workspace config related logic, so we need some refactoring on `che-theia` side.

### Describe the solution you'd like

We need some refactoring on `che-theia` side.

### Additional context
- [handleWorkspaceProjects](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L26)
- [WorkspaceProjectsManager](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L36)
- [WorkspaceConfigProjectsManager](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L166)
- [startSyncWorkspaceProjects](https://github.com/eclipse/che-theia/blob/af8b33d7696f6df384128f19ca513cd9b66a44de/plugins/workspace-plugin/src/workspace-projects-manager.ts#L71) is not async actually 

Note: we should review creation of a workspace related logic in general, not only references above.

**Comment by azatsarynnyy** [comment]
dup of https://github.com/eclipse/che/issues/15249

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
thanks! 

Moving additional context to https://github.com/eclipse/che/issues/15249 and closing the issue.
