### ISSUE TITLE
NodeJS Web Application based on Yarn fails to import project

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#19088]
### Describe the bug
The workspace is started properly, but the project was not imported. I encounter this behavior 100% on my `kkanova-preview` account while testing 7.26.0 Hosted Che on prod-preview and also `kkanova` account testing on prod. I can not reproduce on pure Che 7.26.0. 

### Che version

 - [x] latest 7.26.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Go to dashboard, `Get Started Page`, `Get started` tab
2. Click `NodeJS Web Application based on Yarn`
3. Wait for the workspace to spin up and error message to appear

### Expected behavior
Project should be imported

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: Hosted Che

### Screenshots
![Screenshot from 2021-02-17 13-14-21](https://user-images.githubusercontent.com/29278800/108203786-4330d580-7123-11eb-8677-adceba1f41e2.png)

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: please specify Hosted Che

**Comment by ibuziuk** [comment]
Closing. Should be fixed in workspaces.openshift.com - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/
