### ISSUE TITLE
Preview URL for android workspaces not include for Eclipse Che version 4.5.1

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#1908]
A fresh installation of **Eclipse Che version 4.5.1**, try run for an android project, notice that the preview URL are not include in the "build" run command.
![preview](https://cloud.githubusercontent.com/assets/1939446/17055929/aa136bc0-5042-11e6-9274-53c3d8fef505.JPG)

**Comment by ghost** [comment]
@thyeun how did you create the project - from User Dashboard or in the IDE? If it was in User Dashboard, then it's a bug, however, both samples have preview URL in the template object - https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L82 and https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L152

**Comment by thyeun** [comment]
from user dashboard.

**Comment by ddementieva** [comment]
@thyeun It seems you've created a workspace, not a project from the Dashboard.

You can either create a project, not a workspace, from the Dashboard ![screenshot1](https://cloud.githubusercontent.com/assets/6860395/17295462/e8cf7da8-5804-11e6-967f-42444e19008e.png) or add Preview URL to the command manually. 

It can look something like that: http://${server.port.6080}
![command](https://cloud.githubusercontent.com/assets/6860395/17295478/ffd7186c-5804-11e6-8ed0-0ba0b2111734.png)

**Comment by thyeun** [comment]
@ddementieva i already done that myself (for add-in the preview url command), from the json file, thanks alot anyway. and for your info i created workspace and project at the same time from dashboard. on version 4.5.1 (instead of created the project inside IDE.)

That is why i feel the different from version 4.4 and 4.5.1 (and that why i created this issue), not sure either my files goes wrong or the newer version goes wrong.....

p/s : if this is not a bug, hope you can close the issue. and thanks for the support!!

**Comment by ddementieva** [comment]
Just checked it on 4.5.1 and 4.6.0. Works as expected. Commands are created with Preview URLs for sample projects created from the Dashboard. Closing it as cannot reproduce.
