### ISSUE TITLE
Removing a running workspace

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19081]
### Describe the bug

Dashboard displays a warning when a user removes a running workspace from the main dashboard page.
The message is: `Unable to delete workspace 'workspace_name'. Only STOPPED workspace can be deleted.`

I think there is some inconsistency. After clicking on `Delete` button `dashboard` asks a user to confirm the operation. Then the warning is displayed that it's impossible. 
If it's impossible to remove a running workspace - why the confirmation dialog is displayed? Should the warning be displayed instead?

Moreover, a user is able to delete the same running workspace without any problems  using `Actions` => `Delete Workspace` menu.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Go to the main `dashboard` page and try to remove a running workspace using `Delete` button. 
2. Confirm removing the workspace
3. See a warning
4. Try to remove the workspace using `Actions` => `Delete Workspace` menu.
5. Compare the behavior of the first and the second way of a running workspace removing .

Please see a short video below.

### Expected behavior

I think it should be possible to remove a running workspace from the main page of the dashboard (as it's possible from `Actions` => `Delete Workspace` menu)

### Runtime
I'm able to reproduce it on the `dogfooding` instance

### Screenshots

![delete_workspace_dashboard](https://user-images.githubusercontent.com/5676062/108098192-c1da3400-708b-11eb-8c70-9d2931c8dab5.gif)

**Comment by sleshchenko** [comment]
Duplicates https://github.com/eclipse/che/issues/18761
@RomanNikitenko That's a great description, I put it in the referenced issue as well.
