### ISSUE TITLE
IDE resources caching from UD is broken

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#1909]
Earlier UD cached IDE resources to speedup loading of IDE. Now this technick is broken. URL of compilation mapping file is not reachable due to changes in URL scheme. Here is the URL used by UD: http://localhost:8080/ide/_app/compilation-mappings.txt?uid=553185

**Reproduction Steps:**
1. Load UD
2. Check error in console of browser dev tools

**Expected behavior:**

UD should be able to get compilation mapping file, get resources URL and fetch it into the cache. 

**Observed behavior:**

Request to retrieve compilation mappings file returns main IDE page.
There is an error in console of the browser: **Unable to find the IDE javascript file to cache**

**Che version:**    4.6.0-SNAPSHOT
**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by riuvshin** [comment]
Is it UD issue?

**Comment by benoitf** [comment]
I will fix it
