### ISSUE TITLE
Multi-root: workspace folders auto detection 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19101]
### Is your enhancement related to a problem? Please describe.

We are going to support multi-root workspaces for Che, there is the PR https://github.com/eclipse/che-theia/pull/778

The idea of the PR: projects defined in the devfile are cloned and stored as workspace folders to `che.theia-workspace` config file at starting a workspace.

The idea for improvement is: we should track `/projects` folder for a multi-root workspace and add/delete folders to/from `che.theia-workspace` config file automatically.
It's useful for the case, for example,  when a user clones a project manually to `/projects`.

### Describe the solution you'd like

We should track `/projects` folder for a multi-root workspace and add/delete folders to/from `che.theia-workspace` config file automatically.

**Comment by sunix** [comment]
@RomanNikitenko you can have a look in workspace plugin: it is tracking git project creation and updating the devfile dynamically

**Comment by l0rd** [comment]
Setting label `new&noteworthy` and milestone `DevWorkspace Integration STEP 2` as it blocks #19489

**Comment by azatsarynnyy** [comment]
I'm closing it, as @vitaliy-guliy is already working on it within https://github.com/eclipse/che/issues/19544
