### ISSUE TITLE
Remove "ci.centos.org (build)" PR status check on Che-Theia repo

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19100]
### Is your task related to a problem? Please describe.
There is "ci.centos.org (build)" PR status check on Che-Theia repository.
![image](https://user-images.githubusercontent.com/1636395/108409877-65b01500-722f-11eb-965b-9e969c4554f4.png)

We don't need it anymore as it has been replaced by GitHub Workflow https://github.com/eclipse/che/issues/18407.

### Describe the solution you'd like
Need to contact Eclipse Webmaster and ask to remove the PR check from the repo.
Also, remove the related cico scripts from the repo.

**Comment by benoitf** [comment]
It's strange it was already fixed by https://bugs.eclipse.org/bugs/show_bug.cgi?id=563549 and https://github.com/eclipse/che/issues/17008#issuecomment-633565294

**Comment by azatsarynnyy** [comment]
It seems they just made it non-mandatory.

**Comment by benoitf** [comment]
I'm pretty sure it has been removed but came back 🤦

**Comment by azatsarynnyy** [comment]
built-in check :smile:

**Comment by azatsarynnyy** [comment]
I've reopened https://bugs.eclipse.org/bugs/show_bug.cgi?id=563549

**Comment by azatsarynnyy** [comment]
All `ci.centos.org` related webhooks have been deleted for che-theia
