### ISSUE TITLE
File editor real time content update

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#1910]
### User story

As a `Che` user I want to have actual content of file in the editor irrespective of source of file modification.
### Scenario
- User **A** opens a file **F** in `Che` IDE in workspace **W**
- User **A** or user **B** `ssh` mounts to workspace **W**
- User **A** or user **B** modifies the file **F** using outside means
  - IDE (Intellij IDEA, Eclipse, NetBeans)
  - CLI
  - Text Editor (Sublime, TextMate, vi, etc.)
- Content of the file **F** is updated automatically (no refresh needed)

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
