### ISSUE TITLE
No way to restart a workspace after failure

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19105]
### Describe the bug
When the startup of a workspace fails, I have no obvious way to start it again.

### Che version
 - [ ] other: please specify 7.26.0

### Steps to reproduce
The failure in the screenshot below sometimes happens, I know it's transient, so I just want to start the workspace again. However, there is no way to do that.

1. There is no right-click menu on the list of workspaces in the left sidebar
2. When I click the "Open" menu on the right side in workspaces page, I just get sent to the error page, no attempt at reload is made
3. There is a "Start in Background" and "Open in Verbose Mode", both of which are not what I want

### Expected behavior
A way to start the workspace once again. The right click menu was a fast way, but even just making the "Open" menu on the open page do the right thing (attempt to start the workspace again).

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![WorkspaceFail](https://user-images.githubusercontent.com/13163770/108483390-f96afb00-729a-11eb-8d88-0c1f3be71231.PNG)

### Installation method
   - [ ] chectl server:update from 7.24.0

### Environment
   - [ ] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

Firefox.

**Comment by tsmaeder** [comment]
Additional info: pressing "Start in Background" fails with a 401 error. Refreshing the page lets me start the workspace again.

**Comment by sleshchenko** [comment]
> Additional info: pressing "Start in Background" fails with a 401 error. Refreshing the page lets me start the workspace again.

 this will be solved by https://github.com/eclipse/che-dashboard/pull/172

**Comment by sleshchenko** [comment]
Adding  Restart link should be easy fix.
