### ISSUE TITLE
Document how to use private container registries in Che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19104]
### Is your task related to a problem? Please describe.
We got that questions several times in Che and CRW but it still is not documented.
So, it's needed to fill that gap, describe how to configure user's credentials for a specific private registry.

**Comment by themr0c** [comment]
Referenced in: https://issues.redhat.com/browse/RHDEVDOCS-2699

**Comment by xbaran4** [comment]
Is there any progress with this issue? If not, I will start working on it.

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che-docs/pull/1925
