### ISSUE TITLE
[UD] Create backend for dashboard

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#19116]
### Is your enhancement related to a problem? Please describe.

Currently, with the devworkspace in dashboard work, we're relying on che-servers passthrough to the kubernetes api in order to do things like get all DevWorkspaces, create DevWorkspaces, etc. It would be a great improvement if we can switch to a backend so that the dashboard won't have to depend on so much on che-server. Also, by using a backend we can continue the work on a common library that chectl, che-theia, and dashboard can use

### Describe the solution you'd like

Dashboard starts using a backend

### Additional context

- [WIP Run dashboard as separate deployment](https://github.com/eclipse/che-operator/pull/684)
- [Provide high-level library for managing DevWorkspace objects for clients](https://github.com/eclipse/che/issues/18402)
- [Begin implementing basic DevWorkspace functionality into new dashboard](https://github.com/eclipse/che/issues/18858)

**Comment by sleshchenko** [comment]
now dashboard has different packages for frontend and backend https://github.com/eclipse-che/che-dashboard/pull/268

the only thing left in the current issue scope - adapt syncing to CRW

**Comment by sleshchenko** [comment]
CRW part if moved to a scope of https://issues.redhat.com/browse/CRW-2009. So closing it now
