### ISSUE TITLE
Why are happy path tests not running maven compile-time tests? 

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19115]
I discovered today that the `dashboard-next-happy-path` tests are not running the maven tests:

```
-DskipTests -Dskip-enforce -Dskip-validate-sources
```

-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/rest/organizations/jenkins/pipelines/dashboard-next-happy-path/runs/377/nodes/41/steps/93/log/?start=0

Granted, they're being run elsewhere for nightly and release bulds...

* https://github.com/eclipse/che/blob/master/make-release.sh
* https://github.com/eclipse/che/tree/master/.github/workflows

But would it make sense to run them here too?

**Comment by benoitf** [comment]
Usually happy path test is taking a long time (build, spin up minikube, deploy che, etc), so we remove all checks of the build to test the build as soon as possible.
And other jobs tests that the build/unit tests are passing and as maven build is mandatory to merge I don't see any issue there.
