### ISSUE TITLE
File explorer real time content update

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#1911]
### User story

As a `Che` user I want to have actual content of project explorer irrespective of source of project structure modification.
### Scenario
- User **A** creates a project **P** in a workspace **W**
- User **A** sees the project tree in a project explorer window in `Che` 
- User **A** or user **B** `ssh` mounts to workspace **W**
- User **A** or user **B** modifies project **P** structure 
  - Add/move/remove files/directories
- Modifications are done outside of `Che` by
  - IDE (Intellij IDEA, Eclipse, NetBeans)
  - CLI
  - File managers (MC, FAR, etc)
- Project **P** content is updated in a project explorer window automatically (no refresh needed)

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
