### ISSUE TITLE
Can not clone project for 'Bash' getting-started devfile

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#19119]
### Describe the bug
Premature end of pack file - 48 bytes missing fatal

### Che version
7.26.0

### Steps to reproduce

Hosted Che - start workspace with Bash devfile

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/108683490-f453b900-74f1-11eb-9d3e-76f9229ed742.png)

**Comment by ibuziuk** [comment]
cc @sunix

**Comment by sunix** [comment]
@ericwill is this in our scope?

**Comment by ericwill** [comment]
> @ericwill is this in our scope?

Most likely, is it reproducible only on hosted che, or separately also?

**Comment by ibuziuk** [comment]
Closing as outdated
