### ISSUE TITLE
Git checkout operation notification

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#1912]
### User story

As a `Che` user I want to be informed if git project that I'm working on in `Che` IDE is modified by git checkout operation irrespective of source of modification.
### Scenario
- User **A** opens a git project **P** in workspace **W** in `Che` IDE
- User **A** or user **B** `ssh` to workspace **W**
- User **A** or user **B** perform `Git` `checkout` operation
  - Checking out of a `branch`
  - Checking out of a `commit`
  - Checking out of a `tag`
- `Git` operation is performed outside of `Che` by
  - Third party `Git` client 
  - CLI
- User **A** is notified by `Che` that `Git` operation is performed
- All relative data is updated automatically (no refresh needed)

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
