### ISSUE TITLE
chectl update is very slow

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19129]
### Describe the bug
When doing `chectl update` I estimate the download rate to around 30kbytes/second. The update is 30mbytes and it takes minutes.

### Che version
7.26.0

### Expected behavior
I would expect the download to be faster. Doesn't have to be Gbs, but what we have now is _very_ slow.

**Comment by tolusha** [comment]
I am not sure if we can do anything here since update is completely controlled by oclif framework [1]
[1] https://github.com/oclif/plugin-update

**Comment by tsmaeder** [comment]
You could file an upstream bug or  poke the people responsible for the servers where the updates are downloaded from.
