### ISSUE TITLE
Publish a new version of che-docs container at release time.

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19137]
We need a process to make sure we have regular updates of the che-docs container.

Currently, it is a manual process to upload the Dockerfile to quay when some human (usually @themr0c) knows some change occurred in the file. It is not sufficient.

They are multiple aspects in this task:

* Publish on Quay a new version of the `che-docs` container for each release.
* Publish on Quay a new version of the `che-docs` container when the Dockerfile is updated.
* Test the functionalities before releasing the container.
* Using `che-docs:latest` everywhere will probably lead us to some trouble if we upload a container not enough tested.
* Using `che-docs:latest` doesn't permit reproducible build for older versions.
* A container not updated regularly has security issues piling up.

Here are some ideas:

* Make the publication of the che-docs container part of the release process.
* Test the functionality of the container before pushing to quay: a successful run of antora, vale, linkchecker, newdoc, scripts in `tools` directory: `checluster_docs_gen.sh`, `environment_docs_gen.sh`.
* Tag the container with the same name as the version branch (example: `7.26.x`) and make sure we use this tag everywhere (`devfile.yaml`, `Jenkinsfile`, actions in the `.github` directory, scripts in the `tools` directory).
* Also validate the functionality of the container after pushing to quay: does the devfile works correctly in a Che instance, is the publication with Jenkins successful.

**Comment by themr0c** [comment]
@nickboldt Here is the issue I promised.

**Comment by boczkowska** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2742
