### ISSUE TITLE
Remove some editor api interfaces and clases and simplify editor initialization process

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#1913]
Now we have a lot of factory interfaces:
- EditorBuilder
- OrionTextEditorFactory
- EditorWidgetFactory
- TextEditorPresenterFactory
- EditorModule
- OrionEditorModule

Each of them has only one implementation. Most of implementation just call another factory.
I propose to delete them all and keep only one interface.

Also editor initialization logic in _TextEditorPresenter_ is very confusing and over complicated, this class should be refactored

**Comment by gazarenkov** [comment]
Need to get rid the Editor related complex abstractions which allowed us to have diff implementation of editor. It is useless and error prone (a lot of code to support) in practice.
Very important for Language Server support
