### ISSUE TITLE
Report realistic code coverage for che-theia repo

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#19130]
### Is your task related to a problem? Please describe.
At the moment, code-coverage is not providing the right information: we have extensions and plugins with no test and these ones should be counted in the overall che-theia codecoverage metric.

The following epic should represent the state of test coverage across main che-theia parts, e.g. extensions and plugins.
For the packages, that are not configured to have unit testing support should be created the particular configuration, e.g. jest, mocka + sinon, etc.

In the following section will provide the packages that should be processed to have the mechanism which will display the test coverage:

- [ ] extensions/*
- [ ] plugins/*

This is the next step after creating the mechanism which [measures the test coverage across che-theia repository](https://github.com/eclipse/che/issues/18844).

**Comment by sunix** [comment]
I suggest that we split that in 2 main steps:
1. configure `jest` to produce test reports for all plugins + renaming the badge `plugins code-coverage: xx%`
2. configure `jest` to produce test reports for all the extensions + renaming the badge `coverage: xx%`

**Comment by azatsarynnyy** [comment]
> I suggest that we split that in 2 main steps:
> 
> * [ ]  1. configure `jest` to produce test reports for all plugins + renaming the badge `plugins code-coverage: xx%`
> * [ ]  2. configure `jest` to produce test reports for all the extensions + renaming the badge `coverage: xx%`

I wonder what the purpose of such separation? More badges in the readme file?
We used to have a separate repo for each extension/plug-in.
Today, Che-Theia is a project that contains all its parts in a single repository.
Why we would need separate badges for different folders in a single repo?

**Comment by sunix** [comment]
@azatsarynnyy no the same badge but labeled differently based on the coverage it is really showing.

At the moment, it is showing wrong value, we don't have 59% code coverage. If we want to do it step by step, at least we should tell what we are really showing.
