### ISSUE TITLE
Update kubernetes-client and jackson versions

### ISSUE THREAD

**Issue by xbaran4** [eclipse-che/che#19136]
### Is your task related to a problem? Please describe.

We are using an older version of kubernetes-client (4.9.0) and jackson (2.10.3)

### Describe the solution you'd like

Update kubernetes-client to the latest stable version 5.1.0 and update jackson version (to 2.11.2) to match that of kubernetes-client. Resolve any build errors.

**Comment by xbaran4** [comment]
The plan is to first update kubernetes-client to highest 4.x version, that is 4.13.2. Resolve any compilation problems, deploy it on minikube and test it. And after successfully doing that, update kubernetes-client to 5.1.0 and repeat. 
There are some issues that 4.13.2 introduces which are fixed in 5.1.0, this however should not cause problems. 
I am currently in the process of fixing the compilation errors of our tests from the update to 4.13.2.

**Comment by skabashnyuk** [comment]
implemented
