### ISSUE TITLE
chectl installation doesn't do anything

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19135]
### Describe the bug
As describe in the doc https://www.eclipse.org/che/docs/che-7/installation-guide/using-the-chectl-management-tool/, trying to install chectl, but it doesn't do anything:

```
$ bash <(curl -sL  https://www.eclipse.org/che/chectl/)
chectl script requires superuser access.
You will be prompted for your password by sudo.
$
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
N/A see description.

### Expected behavior
Should install or ask password

### Runtime
N/A

### Screenshots
![Selection_245](https://user-images.githubusercontent.com/650571/108917417-fae84a80-762f-11eb-947b-d45fb417060a.png)

### Installation method
N/A

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by sunix** [comment]
`declare -F` contains entries with just `declare -f` and not `declare -fx`

here are the printf of the `f` variable and `f:12`:

```
f: declare -fx check_another_install -- f12: check_another_install
f: declare -fx check_bin_path -- f12: check_bin_path
f: declare -fx check_requirements -- f12: check_requirements
f: declare -fx chectl_install -- f12: chectl_install
f: declare -fx cleanup_previous_install -- f12: cleanup_previous_install
f: declare -f clearLmod -- f12: learLmod
f: declare -f clearMT -- f12: learMT
f: declare -fx command_exists -- f12: command_exists
f: declare -fx compute_download_link -- f12: compute_download_link
f: declare -fx error -- f12: error
f: declare -fx get_arch -- f12: get_arch
f: declare -fx get_channel -- f12: get_channel
f: declare -fx get_operating_system -- f12: get_operating_system
f: declare -fx get_remove_other_versions -- f12: get_remove_other_versions
f: declare -fx grab_download_link -- f12: grab_download_link
f: declare -fx grab_progress_command -- f12: grab_progress_command
f: declare -fx grab_silent_command -- f12: grab_silent_command
f: declare -fx init_constants -- f12: init_constants
f: declare -fx log -- f12: log
f: declare -fx ml -- f12: ml
f: declare -fx module -- f12: module
f: declare -f xSetTitleLmod -- f12: SetTitleLmod
```

which is making the script failing ...
I have change locally:
```
for f in $(declare -F); do
  if [[ ${f} == *"-fx"* ]];then
    PRE_DEFINED[${COUNTER}]="${f:12}"
    COUNTER=$((COUNTER+1))
  fi
done
```

**Comment by tolusha** [comment]
You have some luck to find chectl issues ;)
I can't reproduce it

**Comment by sunix** [comment]
where is the source code of this `install.sh` script ? I would like to provide the patch but cannot find it.

**Comment by tolusha** [comment]
https://github.com/che-incubator/chectl/blob/gh-pages/install.sh

**Comment by sunix** [comment]
@tolusha https://github.com/che-incubator/chectl/pull/1114
