### ISSUE TITLE
Prompt users to provide an SSH key pair if using Git with SSH in a devfile

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#19133]
### Is your task related to a problem? Please describe.

It's possible to clone the project with `Git: Clone` command.
SSH plugin catches the errors when cloning of git projects and displays a notification with proposal to add key to GitHub.

![Screenshot from 2021-02-23 17-34-44](https://user-images.githubusercontent.com/1655894/108868165-9b257b80-75fe-11eb-8c2d-601fff554ece.png)

It would be nice, if the SSH plugin will have the same UX as the workspace plugin and will display similar notifications.

Improvements of workspace plugin introduced with https://github.com/eclipse/che-theia/pull/995

It would be nice also if the SSH plugin will handle the clone not only from GitHub to be able to configure SSH for any git server.

**Comment by sunix** [comment]
We could somehow, take the control of any ssh calls done by git.
See https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#_miscellaneous

> GIT_SSH, if specified, is a program that is invoked instead of ssh when Git tries to connect to an SSH host. It is invoked like $GIT_SSH [username@]host [-p <port>] <command>. Note that this isn’t the easiest way to customize how ssh is invoked; it won’t support extra command-line parameters, so you’d have to write a wrapper script and set GIT_SSH to point to it. It’s probably easier just to use the ~/.ssh/config file for that.

So imagine a CLI like https://github.com/che-incubator/chedo that would use, making any git clone of a ssh uri would be handled the same way, either it is called from theia or the terminal.

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1820

**Comment by X-dark** [comment]
Is this really doing what it pretends to do?
It seems to me that it is only making the `Git: clone` commands within Theia behave correctly but has no effect on putting a Git url with ssh protocol within the devfile.
