### ISSUE TITLE
Che Operator should be able to install the Devworkspace che operator

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#19142]
### Is your task related to a problem? Please describe.
The che operator is adding the capability to install the devworkspace operator in #19121. Devworkspace on its own is not meant to imitate the capabilities of Che, so we also need to  install the Devworkspace che operator, which builds on top of it to bring the che-like capabilities to the devworkspace "world".

In particular, we want to enable singlehost support in milestone 1, which is only provided by the devworkspace che operator.

### Describe the solution you'd like
We should unconditionally deploy the devworkspace che operator alongside with the devworkspace operator, if the instructed to do so.

**Comment by metlos** [comment]
This depends on https://github.com/eclipse/che-operator/pull/689

**Comment by l0rd** [comment]
I have referenced this issue as a subtask of the epic #19121 and removed it from STEP1 milestone (to make things clearer I am only including epics in the milestone).
