### ISSUE TITLE
Document how to include an upstream Theia patch into Che-Theia release

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19141]
### Is your task related to a problem? Please describe.
During the last several months, there were a couple of times when it was needed to include an upstream Theia commit into CRW. It wasn't clear how to do it.

### Describe the solution you'd like
Describe the possible options in Che-Theia's 'release.md' doc.
Option 1 is to use [`patches`](https://github.com/eclipse/che-theia/tree/master/dockerfiles/theia/src/patches) folder.
Option 2 is to use a fork of upstream Theia with the required commit cherry-picked. Possible this one https://github.com/redhat-developer/eclipse-theia can be used for such purpose.

**Comment by boczkowska** [comment]
Docs Jira https://issues.redhat.com/browse/RHDEVDOCS-2741
