### ISSUE TITLE
Wrong URL is generated when a command with previewURL attribute is clicked

### ISSUE THREAD

**Issue by vladiacob** [eclipse-che/che#19143]
### Describe the bug
Command previewUrl property from Devfile is not working as expected, port :8080 added at the end of the URL.
Example: 
+ Expected: http://server163wmriy-nodejs-server-3000.ide.staging.hackajob.co/
+ Return: http://server163wmriy-nodejs-server-3000.ide.staging.hackajob.co:8080/

URL is displayed correctly in the Endpoints section.

### Che version
 - [x] other: 7.26.1

### Steps to reproduce

1. Create a new workspace where you have a command with previewUrl, this command is the latest from the list 
2. Click on the command from the menu
3. The wrong URL is opened in the preview section, it is displayed wrong also in the terminal

### Expected behavior
Correct URL is opened without the weird 8080 port.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)

### Screenshots
-

### Installation method
   - [x] chectl
chectl server:deploy --platform=k8s --installer=operator --domain=x.x.x.x.co --multiuser --tls --version=7.26.1 --chenamespace=che --no-auto-update

### Environment
   - [x] Cloud
       - [x] Amazon

### Eclipse Che Logs
-

### Additional context
-

**Comment by vladiacob** [comment]
**Some more info, when I start the workspace I get:**
A new process is now listening on port 8080 but this port is not a current endpoint. Would you want to add a redirect for this port so it becomes available ?

**And then when I click yes I get:**
Redirect is now enabled on port 8080. External URL is https://serverni24p3c7-theia-ided5g-server-13131.ide.staging.x.co/

**Comment by azatsarynnyy** [comment]
I suppose it's not relevant anymore. But probably something to check on the Task Plug-in side. cc @svor
