### ISSUE TITLE
Usage of inversify inside devworkspace-client

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19149]
### Is your enhancement related to a problem? Please describe.
Che-theia is using inversify so it might be good to use dependency injection in this library to easily mock objects / work with interfaces instead of having static methods

### Describe the solution you'd like
Provides inversify modules

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by JPinkney** [comment]
Done in https://github.com/che-incubator/devworkspace-client/pull/15. We've just done it on the node side because we will eventually be removing the browser side anyways
