### ISSUE TITLE
Allow `localhost` as redirect URL for keycloak authentication

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#19158]
### Is your task related to a problem? Please describe.
Currently, `localhost` redirect URL should be configured manually by admin
Would be great to have an env var (probably disabled by default) to automatically add the keycloak / SSO redirect web origin for localhost development.  This will allow having `workspaces.openshift.com` a default option for local run of Eclipse Che Dashboard without any manual steps

### Describe the solution you'd like
property e.g. `che.keycloak.allow_localhost`, if set to true adds the `localhost:3000` redirect / web-origin, which would allow  local run of Eclipse Che Dashboard

### Describe alternatives you've considered
Manually configured by admin 

### Additional context
Downstream issue https://issues.redhat.com/browse/CRT-955

**Comment by ibuziuk** [comment]
cc: @sleshchenko @tolusha

**Comment by sleshchenko** [comment]
Implemented in https://github.com/eclipse-che/che-operator/pull/937.
https://github.com/eclipse-che/che-dashboard/pull/300 adds instructions on how to enable localhost on the cluster.
