### ISSUE TITLE
Provides DevWorkspace API types

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19153]
### Is your enhancement related to a problem? Please describe.
While we might have some interfaces for devfile api with https://github.com/devfile/api/issues/353
we should still have for consumers interfaces/types for component status and/or DevWorkspace operator objects (like CRD WorkspaceRouting or DevWorkspaces)

### Describe the solution you'd like
Having npmjs package exposing these types

### Describe alternatives you've considered
Types can be for now included/exposed by the devworkspace-client library

**Comment by sleshchenko** [comment]
It should be already fixed by https://github.com/devfile/api/pull/551
@benoitf please try the latest devfile/api and let me know if it works for you or anything is missing.

**Comment by benoitf** [comment]
@sleshchenko I still don't have the DevWorkspaces types

**Comment by benoitf** [comment]
I have only 'devfile' schema, not what is used by the DevWorkspace Operator implementation

**Comment by sleshchenko** [comment]
@benoitf 

So,

> we should still have for consumers interfaces/types for component status and/or DevWorkspace operator objects (like CRD WorkspaceRouting or DevWorkspaces)

Types from Devfile/api is already available: v1alpha2DevWorkspace and v1alpha2DevWorkspaceTemplate.

DevWorkspace Routing is from DevWorkspace controller API and it's not available yet.
Do you really need it? Isn't flatten devfile enough?

**Comment by sleshchenko** [comment]
closing it. If devworkspace routing is needed - it's a duty of DWO to publish NPM type, please raise the issue there (only if it's needed)
