### ISSUE TITLE
Upgrade the golang plugin

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19154]
### Is your task related to a problem? Please describe.
The vscode-go plugin we have in Che is at version 0.16.1 but the latest plugin version is 0.22.0: https://github.com/golang/vscode-go

### Describe the solution you'd like
Update the plugin to the latest version.

### Describe alternatives you've considered
N/A

### Additional context
Part of  #17208

**Comment by gattytto** [comment]
Blocked by: https://github.com/eclipse-theia/theia/issues/8752

**Comment by svor** [comment]
Need to wait when monaco will be updated https://github.com/eclipse-theia/theia/issues/8969

**Comment by svor** [comment]
Currently the version of golang plugin is 0.23.0. Upgraded by https://github.com/eclipse-che/che-plugin-registry/pull/1015
