### ISSUE TITLE
Make ability to show notifications from dashboard when IDE iframe is showed

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#1915]
Since IDE is showed in iframe and it is possible to perform some actions in dashboard with opened IDE, notification from dashboard can be showed when IDE is opened. 

Need to provide showing notifications from dashboard in special place when IDE iframe is opened.

**Needed for:** https://github.com/codenvy/codenvy/issues/408

**Comment by slemeur** [comment]
We must not show the notifications from the UD if the IDE is opened

**Comment by vinokurig** [comment]
@slemeur but it is contrary to the specifications in https://github.com/codenvy/codenvy/issues/408

**Comment by slemeur** [comment]
It is not - the warning message is displayed in the left sidebar.

**Comment by vinokurig** [comment]
and what will be when something wrong will happen in dashboard while IDE iframe is opened?

**Comment by vinokurig** [comment]
@slemeur do you agree to create issue to disallow notifications from UD when IDE iframe is opened instead this issue?

**Comment by gazarenkov** [comment]
@vinokurig please provide more information about concrete problem you try to solve.

**Comment by vinokurig** [comment]
Dashboard will not show notifications if IDE iframe is showed
