### ISSUE TITLE
Add unit tests in devworkspace-client

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19150]
### Is your enhancement related to a problem? Please describe.
When doing the implementation in che-theia I added jest tests by mocking kubernetes-client's call and I think it would improve the quality of this library if unit tests are handled as well there.

### Describe the solution you'd like
jest/mock data of the real k8s platform

### Describe alternatives you've considered
N/A

**Comment by JPinkney** [comment]
@benoitf Can you link to where you had this implemented in che-theia

**Comment by benoitf** [comment]
@JPinkney https://github.com/eclipse/che-theia/tree/master/extensions/eclipse-che-theia-remote-impl-k8s/tests
