### ISSUE TITLE
Jupyter Extension in Elipse Che

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#19157]
## Summary
Jupyter commands enabled via the jupyter extension are failing in eclipse che. 
## Relevant information
The Jupyter vsix file was dowloaded up from https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
The Jupyter and Python vsix file was packaged into the plugin-registry and deployed in eclipse che 

Che Version : Tried on 7.26.1 and 7.20.1
Jupyter: ms-toolsai.jupyter-2021.2.576440691.vsix
Python: ms-python.python-2021.2.576481509.vsix

The eclipse che workspace was started fine with  the jupyter extension enabled. 
<img width="747" alt="image" src="https://user-images.githubusercontent.com/17478559/109173806-40c91e00-77aa-11eb-9f80-5b68f8c367f0.png">

With the workspace loaded, we can see the jupyter commands
<img width="593" alt="image" src="https://user-images.githubusercontent.com/17478559/109174884-45da9d00-77ab-11eb-89a5-dc4696c024ba.png">

But executing any command throws the below error. 
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/17478559/109174524-ed0b0480-77aa-11eb-8461-b9a8d58d5f99.png">

We tried exploring around CustomEditorProvider but haven't got any leads.  I need help to get Jupyter working on eclipse che as a plugin. What am i missing to add ?

**Comment by RomanNikitenko** [comment]
I see that the corresponding PR for the `CustomEditor` API support is not merged yet  https://github.com/eclipse-theia/theia/pull/8910.

Maybe @azatsarynnyy has more details about it.

**Comment by azatsarynnyy** [comment]
The extension depends on CustomEditor API that is in progress currently https://github.com/eclipse-theia/theia/pull/8910

**Comment by pgirishibm** [comment]
@azatsarynnyy @RomanNikitenko 
We see a new version of the jupyter extension at /Users/pgirish/apihub/scans/repos/playground-che-theia. The file is ms-toolsai.jupyter-2021.3.600686576.vsix. 

We integrated this version into our Eclipse Che setup and now we see the below error when we try to run any Jupyter command within eclipse che
<img width="521" alt="image" src="https://user-images.githubusercontent.com/17478559/109657287-5617c100-7b8b-11eb-9481-7fd4ba9f41ba.png">

Any clues on this one?

**Comment by pgirishibm** [comment]
this is the change log for the new version.  https://marketplace.visualstudio.com/items/ms-toolsai.jupyter/changelog

**Comment by azatsarynnyy** [comment]
I would wait for merging the CustomEditor API first, in the upstream Theia.
