### ISSUE TITLE
The command chectl server:deploy fails if the specified version of Che doesn't exist

### ISSUE THREAD

**Issue by robbiesguo** [eclipse-che/che#19165]
## when i installed eclise che on k8s whith  chectl ,the error was raised.

chectl server:deploy --installer=helm --platform=k8s --multiuser -b che.test.com.cn --postgres-pvc-storage-class-name=nfs-client  --workspace-pvc-storage-class-name=nfs-client   --che-operator-cr-patch-yaml=/u01/chectl/patch.yaml -n che --version=7.26.1
› Current Kubernetes context: 'kubernetes-admin@kubernetes'
    TypeError: Invalid Version: undefined

## Relevant information
chectl version: chectl/7.26.1 linux-x64 node-v12.20.2
helm version:  version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
k8s version:
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by robbiesguo** [comment]
I try chectl with version 7.26.2,the same error was raised. What need i do?

**Comment by tolusha** [comment]
@robbiesguo 
Could you share the content of `/u01/chectl/patch.yaml` ?
Could you try to deploy Eclipse Che without patch file ?

**Comment by robbiesguo** [comment]
> @robbiesguo
> Could you share the content of `/u01/chectl/patch.yaml` ?
> Could you try to deploy Eclipse Che without patch file ?

I have tried to do it ,but the same error raised.

**Comment by robbiesguo** [comment]
I try install eclipse che in windows,but the same error raised.

PS C:\Users\guoxi> chectl -v
chectl/0.0.20210225-next.6c95e9d win32-x64 node-v12.20.2
PS C:\Users\guoxi> helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
PS C:\Users\guoxi> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

PS C:\Users\guoxi> chectl server:deploy
    TypeError: Invalid Version: undefined

**Comment by flacatus** [comment]
Hello @robbiesguo 
I tried to deploy chectl in Windows 10 and was successfully.

![image](https://user-images.githubusercontent.com/59865209/109622156-183f7c00-7b3c-11eb-84b3-52d67cfb5f06.png)

Can you try to download latest chectl binaries and execute chectl?

**Comment by romakoifman** [comment]
It happens when function getLatestChectlVersion fails to fetch the version info. 

`try {
                const { data } = yield axiosInstance.get(`https://che-incubator.github.io/chectl/channels/${channel}/linux-x64`);
                return data.version;
            }
            catch (_a) {
                return;
            }
`
It silently returns; then 

`const isCachedNewerVersionAvailable = semver.gt(newVersionInfo.latestVersion, currentVersion);`

fails because newVersionInfo.latestVersion is undefined. 

Happens for example behind https proxy .

**Comment by tolusha** [comment]
@romakoifman 
Thank you for investigation.
We will provide a fix.

**Comment by romakoifman** [comment]
Confirming. Fix works.
