### ISSUE TITLE
Che Server should tell Dashboard if DevWorkspaces are supported or not

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19160]
### Is your task related to a problem? Please describe.
Dashboard don't know if DevWorkspaces should be fetched or not, and it depends on plafform + openshift oauth settings, since for milestone 1 we support only OpenShift + OpenShift OAuth enabled.

### Describe the solution you'd like
Che Server returns something like
```
supportedWorkspaceTypes: cheWorkspace, devWorkspace
```
as part of workspace/settings.
^ devworkspace is not present for K8s or when Che is deployed without `devworkspace: enabled` in CheCluster CR.

**Comment by skabashnyuk** [comment]
What about property `che.devworkspaces.enabled=false` on che server side? We can expose it with `/api/workspace/settings`

**Comment by sparkoo** [comment]
@xbaran4 will be working on this

**Comment by l0rd** [comment]
I have added this issue as a subtask of [this epic](https://github.com/eclipse/che/issues/18858). Removing it from the STEP1 milestone since it's not an epic.

**Comment by skabashnyuk** [comment]
merged in https://github.com/eclipse/che/pull/19193
