### ISSUE TITLE
Create tests for the shellcheck plugin

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19163]
### Is your task related to a problem? Please describe.
The [shellcheck plugin](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck) is critical to our che-docs development flow. We should have some e2e tests for it to make sure we catch when it breaks.

### Describe the solution you'd like
Create an e2e test suite for this plugin.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/19205
