### ISSUE TITLE
Quarkus `get started` sample fails to load its Didact guide when Che is configured with a self-signed certificate.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19168]
### Describe the bug
Just configured Che on minikube with a selfsigned certificate and it fails to load the didact guide of the Quarkus `get started` sample.

Shouldn't any Theia plugins or vscode extensions be configured with the selfsigned certificate?

### Che version

 - [x] latest 7.26.2
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
- install Che with minikube with the default options (it will generate a self-signed certificate to be added to the browser settings)
- Start the quarkus sample from the `Get Started page`
- See the error and an empty page

### Expected behavior
Should show the guide.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube  v1.17.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_251](https://user-images.githubusercontent.com/650571/109484722-119ffe80-7a81-11eb-8c5b-39e28430cb9e.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sunix** [comment]
I have added env variable NODE_EXTRA_CA_CERTS with the value`/public-certs/custom-certs.rootCA.pem` in the devfile (for che-theia component) and it seems to work.
Looking for a more generic way to fix all of these.

**Comment by azatsarynnyy** [comment]
It may be related to https://github.com/eclipse/che/issues/19120 which is supposed to be fixed by https://github.com/eclipse/che-theia/pull/1014

**Comment by azatsarynnyy** [comment]
another hint is https://github.com/eclipse/che/issues/19309#issuecomment-801866127

**Comment by sunix** [comment]
@azatsarynnyy ok but we cannot have fixes there and there. It should be a global way to set `NODE_EXTRA_CA_CERTS` properly so any plugins and vscode extensions could benefit.
