### ISSUE TITLE
Migrate Maven Eclipse RCP to Eclipse Che

### ISSUE THREAD

**Issue by Kerdanyy** [eclipse-che/che#19161]
Hello,

We have an IDE based on Eclipse RCP and I was wondering if it is possible to migrate existing plugins in RCP application to Eclipse Che? or we have to re-write the whole application from the beginning?

**Comment by ibuziuk** [comment]
Hello, Eclipse Che does not support RCP Eclipse plugins, however, it is compatible with vscode extensions. So, the way to go is to rewrite the RCP plugin to https://www.vsixgallery.com/
@ericwill @benoitf any other pointers?
