### ISSUE TITLE
Dashboard is not handling anymore 'restart-workspace' event

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19174]
### Describe the bug
Che-theia is sending this message to restart workspaces

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

From inside che-theia, if you use 'workspaces: open recent workspaces.." or "try to install plug-ins it's asking to restart" but no restart happen

### Expected behavior
Restart of the workspace happen

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context

commit that added the feature was there:
https://github.com/eclipse/che-dashboard/commit/bd429a0c036aa48feb729769dc3ac9b36a1a3370

looking at current source code it's not anymore there

**Comment by sleshchenko** [comment]
It also should be backported to 7.27.1
