### ISSUE TITLE
multi-root workspaces should be default when using Dev Workspaces / devfile v2

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19191]
### Is your task related to a problem? Please describe.
multi-root is currently optional in Eclipse Che and will soon be a default.
But for DevWorkspaces it should be enabled now by default

### Describe the solution you'd like
Do not need to specify attribute in devfile for devfilev2 to enable multi-root. It should be the only choice available.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by azatsarynnyy** [comment]
@RomanNikitenko below are some useful notes for this issue :arrow_down: 

To detect if we're running a DevWorkspace, check the `DEVWORKSPACE_NAME` environment variable, e.g. `process.env['DEVWORKSPACE_NAME']`.

To start a workspace with the DevWorkspace engine
1. Start your local cluster, e.g. `minikube start --memory 8192 --disk-size 50g --driver virtualbox`
2. Start Che with the dev-workspace engine: `chectl server:deploy --platform=minikube --workspace-engine=dev-workspace`
3. grab https://raw.githubusercontent.com/devfile/devworkspace-operator/main/samples/flattened_theia-next.yaml and save it a local file on you machine.
4. Start a DevWorkspace:
```
kubectl create ns my-dev-workspace
kubectl apply -f flattened_theia-next.yaml -n my-dev-workspace
kubectl get dw --all-namespaces
```
The latest command should print you a Che-Theia URL to follow.
Note, it requires some time to start a workspace. So, if there's no URL - just wait several seconds and repeat the last command.
