### ISSUE TITLE
When restarting a workspace, open project tree re-appears as closed.

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1919]
**Reproduction Steps:**
1. Go to the IDE and open some file and directory. 
2. Workspace ->Stop. Start again.

**Expected behavior:** Opened items should be resored.
**Observed behavior:** The project is collapsed

**Expected behavior:** after clicking on the fires item the Compare button should be enabked
**Observed behavior:** after clicking on the fires item the Compare button still disabled
**Che version:**    4.6.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Related test**: RestoreStateOfProjectTest

**Comment by riuvshin** [comment]
it seems this is same issue as https://github.com/eclipse/che/issues/1902

**Comment by JamesDrummond** [comment]
Please provide a status.

**Comment by bmicklea** [comment]
@vzhukovskii : Was this merged into the 4.6.0 milestone?  The milestone isn't set on the issue but based on the merge time I suspect it's in 4.6...

**Comment by ashumilova** [comment]
Added milestone, was missed
