### ISSUE TITLE
Try to setup minikube + dex + OIDC + RBAC

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19196]
### Is your task related to a problem? Please describe.
We would like to meet this expectation: `Every Che user should be authenticated as a Kubernetes user`

### Describe the solution you'd like
Try to setup minikube + dex + OIDC + RBAC .

### Describe alternatives you've considered
n/a
### Additional context
epic: _Authentication and authorization in Eclipse Che_ #19182
https://github.com/mrbobbytables/oidckube
https://github.com/kiali/kiali/blob/master/hack/k8s-minikube.sh
https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
https://github.com/gini/dexter
https://github.com/micahhausler/k8s-oidc-helper
https://github.com/Spantree/dex-demo-github
https://github.com/mintel/dex-k8s-authenticator
https://habr.com/ru/company/dataline/blog/497482/
https://habr.com/ru/post/436238/

**Comment by sparkoo** [comment]
I've configured minikube with Dex as oidc provider and RBAC working. I've prepared few scripts to reproduce/play with the setup. See the repo: https://github.com/sparkoo/che-auth-playground/tree/master/minikube_dex

**Comment by skabashnyuk** [comment]
Works for me on macOS
<img width="912" alt="Знімок екрана 2021-03-16 о 12 41 04" src="https://user-images.githubusercontent.com/1614429/111749344-4cd06900-889a-11eb-91a5-7cef3557e272.png">
Fixed some problems in https://github.com/che-incubator/che-auth-playground/pull/2
