### ISSUE TITLE
Remove unused Jenkins jobs on centos.ci

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#19190]
### Is your task related to a problem? Please describe.
After new Dashboard releasing we no longer use java Selenium tests. Therefore, we need to delete all tasks related to `java tests` on `centos.ci`.

There is a list of jobs:
- devtools-che-nightly-multiuser-all-test 
- devtools-che-nightly-multiuser-hot-update-test
- devtools-che-nightly-multiuser-stable-test
- devtools-che-nightly-oauth-test

**Comment by Katka92** [comment]
Jobs that was used by Hosted Che and will be cleaned are in this issue: https://github.com/redhat-developer/rh-che/issues/2059

**Comment by nickboldt** [comment]
what about https://ci.centos.org/view/Devtools/job/devtools-che-nightly-openshif-plugin-test/ ? Was last run 7 days ago

**Comment by nickboldt** [comment]
Note that sunset date for cico is Mar 31 so this should probably be escalated to blocker so it gets done in time.

**Comment by dmytro-ndp** [comment]
@nickboldt: https://ci.centos.org/view/Devtools/job/devtools-che-nightly-openshif-plugin-test/ is needed, because OpenShift connector test requires Eclipse Che deployed to OpenShift.

**Comment by SkorikSergey** [comment]
Done by https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/17899.
