### ISSUE TITLE
Async storage does not work in workspaces.openshift.com

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#19198]
### Describe the bug
Starting a workspace with async storage depends on the `eclipse/che-async-pv-plugin/latest` plugin, which is not present in the registry used on workspaces.openshift.com.

### Steps to reproduce
1. Start a workspace with `storageType: async`
2. Workspace fails with
![crw-async-storage](https://user-images.githubusercontent.com/16168279/109831304-4c36a200-7c0d-11eb-8921-9ad56d973d7d.png)

### Environment
   - [x] other: `workspaces.openshift.com`

**Comment by ibuziuk** [comment]
@amisevsk yeah, this is a known one - https://issues.redhat.com/browse/CRW-1422
