### ISSUE TITLE
Restore state of project feature - does not apply to a maven multimodule projects

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1920]
**Reproduction Steps:**
Precoditions: go to the IDE by direct URL
1. Create a multimodule project open several folders for example
2. Refresh page
**Expected behavior:** project should be restored
**Observed behavior:** all items have collapsed to root

[**Expected behavior:** after clicking on the fires item the Compare button should be enabled
**Observed behavior:** after clicking on the fires item the Compare button still disabled
**Che version:**    4.6.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Comment by JamesDrummond** [comment]
@azatsarynnyy Provide status label.

**Comment by musienko-maxim** [comment]
In the 4.8.0 cannot reproduce this problems
