### ISSUE TITLE
In che-docs, use an attribute for "Eclipse Che Hosted By Red Hat"

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19204]
1. Define useful attributes for common strings related to "Eclipse Che Hosted By Red Hat".
2. Add Vale rules promoting the change
3. Use the attributes in the documentation.

First, get some agreement on the attributes:

```
developer-sandbox-name:  Developer Sandbox for Red Hat OpenShift
developer-sandbox-url: https://developers.redhat.com/developer-sandbox
hosted-che-name: Eclipse Che Hosted By Red Hat
hosted-che-url: https://workspaces.openshift.com/
```

**Comment by themr0c** [comment]
@ibuziuk Can you please enhance and validate the list of useful attributes?

**Comment by ibuziuk** [comment]
looks good, thank you!

**Comment by boczkowska** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2746
