### ISSUE TITLE
Fetching catalog.json takes a lot of time in che-theia

### ISSUE THREAD

**Issue by vinayb21** [eclipse-che/che#19202]
**Bug Description:**
When Theia is loaded, I have observed that there is a long freeze before actually fetching catalog.json file

**Steps to Reproduce:**
- Create a Theia IDE using che-theia image and respective che plugin registry
- Check the network tab (Chrome or firefox)
- There is a big delay before the actual fetching of catalog.json

**Comment by azatsarynnyy** [comment]
Hello @vinayb21 
could you please clarify what is `catalog.json` file and where it fetched from? Is it related to any plug-in?
I don't remember `catalog.json` file being used in Che-Theia.

**Comment by vinayb21** [comment]
Hello @azatsarynnyy 
In the core package of Theia, `catalog.json` is being fetched
https://github.com/eclipse-theia/theia/blob/57b4b671f621dc1c5c6eec7f8c6ab1fe0585e4a5/packages/core/src/browser/json-schema-store.ts#L99

**Comment by azatsarynnyy** [comment]
@vinayb21 have you observed the same behavior in vanilla Theia?

**Comment by vinayb21** [comment]
@azatsarynnyy In vanilla Theia, the waiting time is around 200-250ms
![image](https://user-images.githubusercontent.com/14150149/109944269-12909480-7cfc-11eb-9a64-9968963a9ecf.png)
For Gitpod:
![image](https://user-images.githubusercontent.com/14150149/109947208-14a82280-7cff-11eb-9379-72f67acecb55.png)
For self hosted Che-theia:
![image](https://user-images.githubusercontent.com/14150149/109947248-212c7b00-7cff-11eb-9426-9977353d9086.png)

For Gitpod and self hosted che-theia:
The combined Initial connection and SSL are taking more than 1.3 seconds (waiting time is similar to plain theia)

Do you know if there is a fix for this?

**Comment by azatsarynnyy** [comment]
@vinayb21 I believe that's how `azurewebsites.net` responds.
I've checked it with cURL:
`curl 'https://schemastore.azurewebsites.net/api/json/catalog.json' -w 'Total: %{time_total}s\n'`
and got `Total: 0.945549s`

**Comment by vinayb21** [comment]
@azatsarynnyy Can we move this catalog.json to some CDN with lower latency. Thoughts?
`curl 'https://schemastore.azurewebsites.net/api/json/catalog.json' -w 'Total: %{time_total}s\n'`
For me, it's `Total: 1.821044s`

**Comment by azatsarynnyy** [comment]
@vinayb21 I propose to discuss it in a single place. Let's continue upstream https://github.com/eclipse-theia/theia/issues/9149 as obviously, it's not Che-Theia specific.
