### ISSUE TITLE
Happy Path Tests on che-theia PR flakiness

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19210]
### Describe the bug
I had to restart 3 times to have a successful build on https://github.com/eclipse/che-theia/pull/1015

![image](https://user-images.githubusercontent.com/436777/109996681-bfc0d800-7d0f-11eb-839e-62f229058f33.png)

It's also failing on jobs running github actions so it's not related to the underlying infra I would say but from the tests.
They used to be all green. Now it's one ouf 4 or 8 that is green

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Look at https://github.com/eclipse/che-theia/pull/1015 reports

### Expected behavior
Should be successful on the first attempt

**Comment by dmytro-ndp** [comment]
@benoitf: Happy path tests are pretty stable on CRW Jenkins.

WDYT about closing the issue?
