### ISSUE TITLE
The name of the workspace view should be improved

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19214]
### Is your task related to a problem? Please describe.

Right now the title of the workspace view is **MY WORKSPACE: WORKSPACE** which doesn't look good to me
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 03 05-10_57_56](https://user-images.githubusercontent.com/1271546/110096233-635cc780-7da6-11eb-8c9f-358b9d45bce1.png)

### Describe the solution you'd like

If we want to have real name of the workspace it should be like 
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 03 05-11_21_09](https://user-images.githubusercontent.com/1271546/110096321-78d1f180-7da6-11eb-9dab-223e28e18b3c.png)
But i prefer only have WORKSPACE as the title
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 03 05-11_23_31](https://user-images.githubusercontent.com/1271546/110096457-9737ed00-7da6-11eb-8efd-e4f1c8f01093.png)
 
@parvathyvr WDYT

**Comment by parvathyvr** [comment]
Hi @svor I think it would be good to show the  real name of the workspace so that the user can easily see which workspace they are currently in.The other idea would be just to say 'WORKSPACE' instead of 'MY WORKSPACE'. So it would be WORKSPACE:<NAME OF WORKSPACE>

**Comment by benoitf** [comment]
@parvathyvr a preference between the name of the workspace or the generic 'workspace' name ?

**Comment by parvathyvr** [comment]
> @parvathyvr a preference between the name of the workspace or the generic 'workspace' name ?

My earlier comment wasn't complete! Updated it...I think we should show WORKSPACE: NAME OF WORKSPACE

**Comment by azatsarynnyy** [comment]
Related to the Containers Plug-in, so I'm relabeling it to `area/plugins`
