### ISSUE TITLE
Change default of chectl/che-operator in case of DevWorkspace

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19218]
### Is your task related to a problem? Please describe.
Today when installing che by defaul, chectl is picking up multi-host by default.
Single host has advantages for ssl/self-signed certificates so it should be the new default

### Describe the solution you'd like
Install che with single-host mode if devworkspace engine is selected in che-operator or with chectl toggle.

**Comment by SkorikSergey** [comment]
As I understood `--dev-workspace-controller-image=` flags is the only way to change devworkspace-controller image(except 
 patching devworkspace pod). And it is important for testing Eclipse Che with the `devworkspace-controller` image built from the PR.

**Comment by l0rd** [comment]
@flacatus I am +1 to remove it if we provide a way to configure it in the `CheCluster` CR.

**Comment by flacatus** [comment]
@SkorikSergey To use a custom devworkspace controller image please consider to use:

``` yaml
spec:
  devWorkspace:
    enable: true
    controllerImage: '<custom-image>'
```
