### ISSUE TITLE
Add select all factories on dashboard feature

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1921]
**Reproduction Steps:**
1. An user may have a lot of factories in the list. This factories may become deprecated for example. And the user decide to delete them. But for this he should select the each factory by checkbox. It may irritate

**Che version:**    4.6.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Comment by TylerJewell** [comment]
Provided in 5.7 with factories release for Che.
