### ISSUE TITLE
Unexpected reloading the factories page after selecting

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1922]
**Reproduction Steps:**
If we have a large list of factories and we select they step by step the page is reloaded unexpectedly
See also screencast : 
![anim](https://cloud.githubusercontent.com/assets/1640058/17062935/a25eb1b4-503d-11e6-87a9-31085ecdd78f.gif)
**Expected behavior:** after clicking on the fires item the Compare button should be enabked
**Observed behavior:** after clicking on the fires item the Compare button still disabled
**Che version:**    4.6.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Comment by JamesDrummond** [comment]
@musienko-maxim Provide status label and assign.
