### ISSUE TITLE
Che launches a new browser window when changing left-side navigation options

### ISSUE THREAD

**Issue by toddjames** [eclipse-che/che#1923]
While rapidly switching between menu options on the left side of the Che web interface (Dashboard, Workspaces, Projects, Administration), occasionally, a new window/tab is launched in the browser.

**Reproduction Steps:**
1. Perform a fresh install of Eclipse Che using the server zip file (on Ubuntu 16.04 Server, if it matters)
2. Rapidly switch between items on the left-side navigation menu items in Che in the browser (Dashboard, Workspaces, Projects, Administration). (Using Chrome in Windows 10, if it matters)
3. Notice that occasionally, clicking any one of these will launch a new window.

**Expected behavior:**

All browsing between menu options happens in the current window.

**Observed behavior:**

A new window/tab pointing to the link that was clicked is launched occasionally.

**Che version:**    4.4.2
**OS and version:** Server is running Ubuntu 16.04 Server, client is running Google Chrome on Windows 10
**Docker version:** 1.11.2
**Che install:**    Server (zip)

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Unsure, this is my first time using Che
- Problem can be reliably reproduced, doesn't happen randomly: It is random, but highly reproducible

**Comment by toddjames** [comment]
Here's a clip to demonstrate the issue:

![che](https://cloud.githubusercontent.com/assets/860775/17081373/c362eace-5123-11e6-8d85-274d52d11f6a.gif)

**Comment by TylerJewell** [comment]
Long clicks are interpreted as launching in a new browser tab.  I wonder if the browser is confusing fast clicks for long clicks.

**Comment by ghost** [comment]
@toddjames I clicked as fast as I could.. and @TylerJewell is right - long clicks open a new tab. Instead of clicking fast, click and hold. Reproduced with Che dashboard but no such effect on GitHub.

I am not sure this should be labeled as bug. @TylerJewell wdyt?

**Comment by toddjames** [comment]
I see both behaviors. A single long click on an item will open a new tab, as well as many short and fast clicks to switch between multiple items. It seems like something in the long click logic is misinterpreting the successive short clicks as a long click and opening a new tab.

To be clear, I discovered this after installing Che to try it out for the first time and my intention is/was not to open a new tab at all. Nor would I expect anything to open a new tab unless I have Shift held down, which I believe is the standard way to open a new tab if that's what the user desires. To me it seems like having the long-click functionality just reinvents the wheel that the browser already has, but that's up to you all and as a user, I can live with it if it doesn't interfere with my normal browsing.

I simply noticed that I was randomly getting new tabs when switching quickly between options on the left  when I realized I went to the wrong one occasionally and thought I would let you guys know. If quickly switching between options on the left IS intended to open new tabs, then I suppose this isn't a bug, but that doesn't seem like desirable behavior, to me at least.

**Comment by TylerJewell** [comment]
@slemeur @ashumilova - I agree that we should change long-click to shift-long click.  I will mark this as enhancement.

**Comment by toddjames** [comment]
If you go that direction, and since just <shift|ctrl> + <long|short> click is already handled by the browser, you can probably just let the browser handle the behavior however it wants and simply remove the custom code for the long click.

**Comment by TylerJewell** [comment]
Fixed in this PR.
https://github.com/eclipse/che/pull/2237
