### ISSUE TITLE
Document how to change the plugin registry via preferences

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19237]
### Is your task related to a problem? Please describe.
It's possible to [change the plugin registry URL via `settings.json`](https://user-images.githubusercontent.com/7668752/108871725-1b99ab80-7602-11eb-9601-0445e6eed6db.gif), but this information is not documented. We also validate the information entered in that setting, which should also be documented.

### Describe the solution you'd like
Document such steps somewhere in our current [Running custom registries articles](https://www.eclipse.org/che/docs/che-7/administration-guide/running-custom-registries/).

### Describe alternatives you've considered

None so far.

### Additional context
https://github.com/eclipse/che-theia/pull/1003

**Comment by boczkowska** [comment]
Jira docs issue https://issues.redhat.com/browse/RHDEVDOCS-2770

**Comment by ericwill** [comment]
I believe this is done, closing it now.
