### ISSUE TITLE
docs: clarify creation and usage of custom tls certificate in Che

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19246]
### Is your task related to a problem? Please describe.
There is some confusion on how certificates are configured and should be consumed in che-theia plugins: https://github.com/eclipse/che/issues/18957

### Describe the solution you'd like
We should clarify in our advanced documentation:

- [ ] Document how the certificates should be configured so it works as expected. Probably verify https://www.eclipse.org/che/docs/che-7/installation-guide/importing-untrusted-tls-certificates/ and compare to what the che operator is generating: https://github.com/eclipse/che/issues/18957#issuecomment-793538950
- [ ] Document how these certificates should be consumed (by a plugin, an extension or a che editor, or an application running in the workspace)

**Comment by l0rd** [comment]
@sunix do you have an idea about how "certificates should be configured so it works as expected"? Are you working on this task?

**Comment by sunix** [comment]
@l0rd no we have some hints there: https://github.com/eclipse/che/issues/18957#issuecomment-793538950
but I haven't had a deeper look at it. Also not in our team scope ATM. cc @ericwill

**Comment by l0rd** [comment]
> @l0rd no we have some hints there: [#18957 (comment)](https://github.com/eclipse/che/issues/18957#issuecomment-793538950)

What's the hint? Except the fact that it works with the certificate that we auto generate (that no one will ever use in production), I have no idea if and how, as a user, I can configure Che to use my own certificate.

We cannot assume that it's a documentation issue if we haven't been able to verify if there are some steps that an admin can follow to makes it work.

Please re-open when you have more details.
