### ISSUE TITLE
Several stoped workspaces created if you click several times in samples workspace

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#19248]
### Describe the bug

If you click several times in one sample in che dashboard several stopped workspaces will be crated and an error saying `Workspace <workspace_name> failed to start` .
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Navigate to the new Che Dashboard
2. In the left navigation panel, go to Get Started.
3. Click several times in one of the samples and an error will be displayed saying: `Workspace <workspace_name> failed to start`

### Expected behavior
Get started is blocked after sample is clicked, and only one workspace is created

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/59865209/110613129-2e2eeb80-8191-11eb-85b2-531e7acd68ef.png)
^ workspace failed to start because there is a limit - 1 running workspace at the same time.

![get-started](https://user-images.githubusercontent.com/5887312/110613242-b87b4d80-8199-11eb-9180-eecf3e775c6e.gif)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
Is fixed by https://github.com/eclipse/che-dashboard/commit/e0bf90a2e20014bcb8290f1c85e2a85b347c0e1f
