### ISSUE TITLE
Migrate community operator to the new bundle format

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19244]
### Is your task related to a problem? Please describe.
Stable and nightly channels are moved to the new bundle format [1] but to create community operator PR we still convert those bundle to an older format [2]

[1] https://github.com/eclipse/che-operator/tree/master/deploy/olm-catalog
[2] https://github.com/eclipse/che-operator/blob/master/olm/prepare-community-operators-update.sh#L66

### Describe the solution you'd like
Create PR to community operator to migrate to a new format.

### Additional context
https://github.com/eclipse/che/issues/16928

**Comment by flacatus** [comment]
Done. We have new bundles format in community operators.
