### ISSUE TITLE
Create Custom Workspace page crashes on click into select template edit after editing the devfile

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#19250]
### Describe the bug
After editing of a devfile template and clicking again on the `Select a devfile template` field dashboard shows an error. Only page reload helps to restore it.

### Che version
nightly

### Steps to reproduce

1. Open Create Custom Workspace page
2. Click on `Select a devfile template` and pick one
3. Edit something in the devfile ditor
4. Click on `Select a devfile template` again
5. See the error

### Expected behavior
No error

### Runtime
Openshift

### Screenshots
![bug](https://user-images.githubusercontent.com/15607393/110615536-32acd180-819c-11eb-9139-d200406fea3c.gif)

### Eclipse Che Logs
N/A

**Comment by olexii4** [comment]
It was fixed in https://github.com/eclipse/che-dashboard/pull/187/commits/5eb72841169c4f10148f9a23bd3bcc8f3f4104cd#diff-338802cc4d6dee7ac6794409995cc83915e3bd55cd65f1bd4f2a831fe6cdbe82R66
