### ISSUE TITLE
Delete Workspace item is enabled when it cannot be used

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#19251]
### Describe the bug
In a workspace context menu (three dots at right side) there is `Delete Workspace` item. It is always enabled (for example when the workspace is in `RUNNING` or `STARTING` phase). When user selects this item, a new dialog windows appears. After checking checkbox and confirming the deleting an error is show which says that only `STOPPED` workspaces can be deleted.

### Che version
nightly

### Steps to reproduce

1. Create and run a workspace
2. Go to dashboard, open workspaces list
3. Click on additional actions (three dots) and see the `Delete Workspace` is enabled
4. Go through confirmation window, confirm the deletion
5. See the error

### Expected behavior
`Delete Workspace` is enabled only on stopped workspaces.

### Runtime
Openshift

### Screenshots
![bug2](https://user-images.githubusercontent.com/15607393/110619081-0dba5d80-81a0-11eb-830b-47a0c42932af.png)
![bug2_1](https://user-images.githubusercontent.com/15607393/110619127-1ad74c80-81a0-11eb-8c77-3b1a9b85b2a4.png)

### Eclipse Che Logs
N/A

### Additional context
Some other items in the context menu are correctly disabled when needed.

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/18761. that's really annoying behavior.

**Comment by sleshchenko** [comment]
Well, not really duplicates, the references more is about bulk removal, when this is about Actions. I'm keeping both opened.

**Comment by RomanNikitenko** [comment]
IMO it's duplicate of https://github.com/eclipse/che/issues/19081
