### ISSUE TITLE
Logs tab of workspace start is not scrolled down automatically

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#19255]
### Describe the bug
When a new lines of logs are added at workspace start time, user has to scroll down manually to follow them.

### Che version
nightly

### Steps to reproduce

1. Create and start a workspace
2. Switch to the `Logs` tab
3. Wait for some output
4. Wait more to see scroll bar
5. It never scrolls to the end automatically

### Expected behavior
By default it should scroll to the end. If a new line appears in the logs it should be visible.
If a user scroll manually up, auto scroll to the end should be disabled, but when user scrolls back to the end - enabled again.

### Runtime
Openshift

### Screenshots
![bug](https://user-images.githubusercontent.com/15607393/110648171-27b86800-81c1-11eb-8d61-4b6886337dbe.png)

### Eclipse Che Logs
N/A

**Comment by mmorhun** [comment]
Is the issue fixed?

**Comment by olexii4** [comment]
> @olexii4 do you know if the issue is fixed?

This issue is not fixed yet.
