### ISSUE TITLE
Update documentation describing the Che workspaces architecture

### ISSUE THREAD

**Issue by sudr** [eclipse-che/che#19265]
On the Che workspaces architecture documentation page (https://www.eclipse.org/che/docs/che-7/administration-guide/che-workspaces-architecture/) the text following Figure 1. says "In the diagram, there are three running workspaces: two belonging to User A and one to User C. A fourth workspace is getting provisioned where the plug-in broker is verifying and completing the workspace configuration.". It doesn't appear that this text explains the diagram accurately.

Should the text be updated to more accurately describe the figure?

**Comment by davidfestal** [comment]
It's right that the text doesn't seem to really fit with the diagram.
cc @themr0c Should be route this issue to the initial contributor of this part of the doc ?

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-2845
