### ISSUE TITLE
Publish a versioned che-plugin-registry release to GitHub pages and surge.sh

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19268]
### Is your task related to a problem? Please describe.
Currently, we are only publishing a [nightly che-plugin-registry release](https://che-plugin-registry-main.surge.sh/v3/plugins/) on surge.sh.

### Describe the solution you'd like
It would be nice to publish a version at release time, for example:
* https://che-plugin-registry-7-26-0.surge.sh/v3/plugins/
* https://che-plugin-registry-7-26-1.surge.sh/v3/plugins/

and so on. This way we can reference versioned plugin registry releases in other places, like the devfile registry.

### Describe alternatives you've considered
Publish to GitHub pages instead of surge.sh.

### Additional context
Needed in order to enable community plugins and devfiles on Dev Sandbox.

**Comment by sunix** [comment]
Currently looking at it.
Not sure we can use 
```yaml
on:
  workflow_run:
    workflows: ["Release Che Plugin Registry"]
    types:
      - completed
```
to publish after a release job.
However it looks like the image is pushed before the tag creation. See https://github.com/eclipse-che/che-plugin-registry/blob/master/make-release.sh#L34 and https://github.com/eclipse-che/che-plugin-registry/blob/master/make-release.sh#L152
So we could trigger the publishing on a tag event

**Comment by ericwill** [comment]
> Currently looking at it.
> Not sure we can use
> 
> ```yaml
> on:
>   workflow_run:
>     workflows: ["Release Che Plugin Registry"]
>     types:
>       - completed
> ```
> 
> to publish after a release job.
> However it looks like the image is pushed before the tag creation. See https://github.com/eclipse-che/che-plugin-registry/blob/master/make-release.sh#L34 and https://github.com/eclipse-che/che-plugin-registry/blob/master/make-release.sh#L152
> So we could trigger the publishing on a tag or release event

Could we not add the surge.sh publish step inside the `make-release.sh` script?

**Comment by sunix** [comment]
we could it would required installing surge in `make-release.sh`. maybe in the step following the release ? https://github.com/eclipse-che/che-plugin-registry/blob/master/.github/workflows/release.yml#L85-L92 
Question is: do we want to mark the release job as failed if something is wrong with surge.sh ?

**Comment by ericwill** [comment]
> Question is: do we want to mark the release job as failed if something is wrong with surge.sh ?

Since we plan to start using it in other places (i.e. devfiles) we should probably make sure it runs successfully, yes. IMO this means it that the release should fail if the surge.sh publish fails.

Side note: we do not need to only publish to surge.sh, it might be a good idea to publish to GitHub pages as well.

**Comment by sunix** [comment]
if we want to use in other places, better not relying on surge.sh. It has been down couple of times.

**Comment by ericwill** [comment]
> if we want to use in other places, better not relying on surge.sh. It has been down couple of times. Github pages sounds like a good option.

Sounds good! :+1:
