### ISSUE TITLE
When a change occurs in che-server file `che.properties`, generate equivalent docs in che-docs

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19264]
### Is your task related to a problem? Please describe.

In `che-docs`, we generate some part of the documentation based on `che.properties`, using the `tools/environment_docs_gen.sh`.

As there is no automation / release management around that process:

* A human runs the script manually and raise a PR when he knows some change happened.
* As the generated docs always lags behind, the script is also run at build and publication time (but not commited back).

### Describe the solution you'd like

We would like that a change of `che.properties` in a given branch of the `che` repository triggers an update in the according branch of the `che-docs` repository.

Example:

* File is changed in the branch `7.26.x` of the `che` repository => run `tools/environment_docs_gen.sh` in the branch `7.26.x` of the `che-docs` repository.

* File is changed in the branch `main/master` of the `che` repository => run `tools/environment_docs_gen.sh` in the branch `main/master` of the `che-docs` repository.

**Comment by nickboldt** [comment]
So I'm hearing:

on push of change to `/eclipse/che/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties` in any .x or master/main branch:

* trigger workflow in che-docs repo with single parameter "branch" = same branch affected in eclipse/che repo

This means we need:

* a workflow action in eclipse/che-docs
* an on-push action in eclipse/che which does API call to workflow action in eclipse/che-docs

**Comment by boczkowska** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2833

**Comment by themr0c** [comment]
@nickboldt exactly that!

**Comment by mkuznyetsov** [comment]
closing, as It has been tested, and seems to work now
