### ISSUE TITLE
Improve workflow when user denies Bitbucket access for Che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19274]
### Is your task related to a problem? Please describe.
Currently after user denies access to Bitbucket server, he gets page with JSON
```json
{
  "message": "401\noauth_problem=permissions_denied"
}
```

### Describe the solution you'd like
But ^ it's pure UX, instead dashboard should be opened where user is notified that they denied Bitbucket access and it's not possible to resolve factory from the specified URL.

### Describe alternatives you've considered
Be optimistic, and leave as is keeping in mind that nobody must denies access.

### Additional context
![Screenshot_20210311_114729](https://user-images.githubusercontent.com/5887312/110768805-39048180-8260-11eb-93f5-67e368b7efaa.png)
![Screenshot_20210311_114749](https://user-images.githubusercontent.com/5887312/110768808-3a35ae80-8260-11eb-8f74-8ca33ffaca08.png)
Bitbucket epic - https://github.com/eclipse/che/issues/18385

**Comment by sleshchenko** [comment]
removed area/dashboard. A dedicated issue should be created for dashboard if needed.

**Comment by sleshchenko** [comment]
Just for link, Dashboard has a separate issue which we expect to be fixed in 7.30: Dashboard should handle error codes from oauth flow https://github.com/eclipse/che/issues/19722

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse/che/pull/19620 and https://github.com/eclipse/che/pull/19723
