### ISSUE TITLE
chectl next channel is broken

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19277]
### Describe the bug
chectl next channel is broken
```
 bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
chectl script requires superuser access.
You will be prompted for your password by sudo.
[sudo] password for tolusha:              
Sorry, try again.
[sudo] password for tolusha:              
ERROR: Missing redirect link from the download link https://che-incubator.github.io/chectl/download-link/next-linux-x64. Content found is '''
```

**Comment by benoitf** [comment]
can be closed
```
$ curl https://che-incubator.github.io/chectl/download-link/next-linux-x64                                                                                                                       
https://github.com/che-incubator/chectl/releases/download/20210311160018/chectl-linux-x64.tar.gz
```

**Comment by dmytro-ndp** [comment]
The issue had happened again [yesterday](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2591/console):
```
10:28:10 ERROR: Missing redirect link from the download link https://che-incubator.github.io/chectl/download-link/stable-linux-x64. Content found is '''
```

@benoitf: do you happened to know reliable solution?

**Comment by benoitf** [comment]
I suspect a race condition (or something done too soon) between the script that call the github action to update and the actual publication of artifacts to the release

**Comment by dmytro-ndp** [comment]
Can we improve the process to prevent such an error in future?

**Comment by benoitf** [comment]
well, the process could check as post-step that the artifact is there at 'https://che-incubator.github.io/chectl/download-link/stable-linux-x64' or 'https://che-incubator.github.io/chectl/download-link/next-linux-x64'

**Comment by dmytro-ndp** [comment]
I see. Thanks for explanation!
Taking into account 2 occurrences during the last 6 days, it is worth to be improved, IMHO
