### ISSUE TITLE
Make it possible to run the "che-theia" standalone

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#19275]
### Is your enhancement related to a problem? Please describe.
It would be great to have an ability to run the "che-theia" standalone for verifying editor cases.
The main problems we have now:
 - resources consumption (makes using GH actions impossible because the lack of resources for example),
 - a lot of pre-steps before running tests - setup minikube, setup Che instance, start workspace ... It leads to raising test duration and instability (on each mentioned step, which doesn't relate directly to the necessary scenario, something may go wrong and cause the test to fail )

### Describe the solution you'd like
Make it possible to run the "che-theia" standalone.
It will give us the ability to start implementing integration level tests for the editor, plugins and etc instead of E2E scenarios.
Besides integration level tests will be very useful for the development testing.

**Comment by benoitf** [comment]
for point 1, there is enough memory to run che-theia on kubernetes on github action and
For point 2, installing/starting minikube/che never fails. 
Almost all the time it's the flakiness of the tests using timeout everywhere

Also Che theia is tied to kubernetes now. So there is no point developing an abstraction of the runtime

Also for your scenario there is unit tests that are fast

**Comment by tsmaeder** [comment]
> Also Che theia is tied to kubernetes now. So there is no point developing an abstraction of the runtime

On the other hand, we now have libraries to access the Che services (k8s or Che server). Maybe a dummy implementation of testing for that library would feasible.
