### ISSUE TITLE
Remove obsolete nightly/RC jobs from ci centos

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19287]
### Is your task related to a problem? Please describe.

There are still a number of jobs running on the cico server:

![image](https://user-images.githubusercontent.com/227597/111162400-7fb0ef00-8572-11eb-9aa0-33748fe37e27.png)

These have run in the last week:

![image](https://user-images.githubusercontent.com/227597/111162537-9e16ea80-8572-11eb-8724-f782476a4070.png)

![image](https://user-images.githubusercontent.com/227597/111162584-a8d17f80-8572-11eb-8094-bb69dab10b88.png)

These are apparently no longer running:

![image](https://user-images.githubusercontent.com/227597/111162665-bf77d680-8572-11eb-94e7-79e1eb7b9151.png)
![image](https://user-images.githubusercontent.com/227597/111162701-c999d500-8572-11eb-982f-427df7f941bf.png)
![image](https://user-images.githubusercontent.com/227597/111162755-d5859700-8572-11eb-8e01-4e7ccda68dfb.png)
![image](https://user-images.githubusercontent.com/227597/111162799-de766880-8572-11eb-887e-a43b15bef9b5.png)

![image](https://user-images.githubusercontent.com/227597/111162835-e6cea380-8572-11eb-9da0-377b98a34081.png)

![image](https://user-images.githubusercontent.com/227597/111162872-f0f0a200-8572-11eb-8668-075385bf6dc3.png)

![image](https://user-images.githubusercontent.com/227597/111162898-f948dd00-8572-11eb-9a1b-976b038f6268.png)

![image](https://user-images.githubusercontent.com/227597/111162922-ff3ebe00-8572-11eb-9087-0e480d9153c5.png)

![image](https://user-images.githubusercontent.com/227597/111162969-0c5bad00-8573-11eb-85e5-214aa675715b.png)

### Describe the solution you'd like

* Migrate those we need to new casc Jenkins, 
* Delete those we don't by submitting a PR against https://gitlab.cee.redhat.com/service/app-interface/

### Additional context

https://github.com/eclipse/che/issues/17857

**Comment by dmytro-ndp** [comment]
Che QE jobs specific issue https://github.com/eclipse/che/issues/19287

**Comment by nickboldt** [comment]
Most urgent to assess (migrate or delete):
* https://ci.centos.org/view/Devtools/job/devtools-che-jwtproxy-nightly/

* https://ci.centos.org/view/Devtools/job/devtools-che-plugin-broker-nightly/

* https://ci.centos.org/view/Devtools/job/devtools-che-parent-che-nightly/

* https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-nightly/
* https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-build-master/
* https://ci.centos.org/view/Devtools/job/devtools-che-theia-pullrequests-build/

* https://ci.centos.org/view/Devtools/job/devtools-che-machine-exec-build-master/

* https://ci.centos.org/view/Devtools/job/devtools-che-docs-che-nightly/
* https://ci.centos.org/view/Devtools/job/devtools-che-docs-che-build-master/

and

* https://ci.centos.org/view/Devtools/job/devtools-che-nightly-openshif-plugin-test/ (note the spelling error in the job name)

**Comment by nickboldt** [comment]
* JWT proxy: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/16275 @skabashnyuk 
* server, parent, vertx-server: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/16276 @skabashnyuk 
* machine-exec: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/16277 @tolusha 
* che-theia + PR check: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/16278 @azatsarynnyy

**Comment by skabashnyuk** [comment]
@nickboldt ok for me to delete jwt-proxy and che-server.

**Comment by nickboldt** [comment]
thx, MR already merged :) 

Still to do are these two (but not urgent as they rarely update / rarely release / CICO end of life is not imminent:

* https://ci.centos.org/view/Devtools/job/devtools-che-plugin-broker-nightly/ - no GH workflows
- [ ] migrate 2 jobs in #19295, then delete from cico
* For KIP / KIPO (5 jobs)
- [ ] migrate in #19294, then delete from cico

**Comment by nickboldt** [comment]
Other than the last two projects (tracked in separate issues) this is now done, so closing.
