### ISSUE TITLE
Update vale plugin to version v2.10.2

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19289]
### Describe the bug

In che-docs, we had issues with vale  2.8.0 that were solved by upgrading vale to 2.10.0 in che-docs container.

Can you upgrade also the vale plug-in container?

shell in vale plug-in:

```
/projects/che-docs $ vale che-docs/CONTRIBUTING.adoc 
E100 [NewE201] Runtime error
error parsing regexp: invalid or unsupported Perl syntax: `(?!`
Execution stopped with code 1.
/projects/che-docs $ vale -v
vale version v2.8.0
```

vs. shell in che-docs container (with vale 2.10.0):

```
~/che-docs $ vale che-docs/CONTRIBUTING.adoc 
✖ 10 errors, 14 warnings and 62 suggestions in 1 file.
~/che-docs $ vale  -v
vale version master
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Open the che-docs project in wokspaces.openshift.com
2. Open an AsciiDoc file, for example CONTRIBUTING.adoc
3. Activate the *Problems* view: no vale errors are reported.
4. Open shell in vale plug-in, run vale che-docs/CONTRIBUTING.adoc
5. Open shell in che-docs container, run vale che-docs/CONTRIBUTING.adoc

### Expected behavior

Vale errors are reported in the *Problems* view.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) workspaces.openshift.com
   - [ ] other: please specify

**Comment by vinokurig** [comment]
@themr0c 
When I run `vale /projects/che-docs/CONTRIBUTING.adoc` I see an error:
```
~/vale $ vale /projects/che-docs/CONTRIBUTING.adoc 
E100 [loadStyles] Runtime error

style 'write-good' does not exist on StylesPath

Execution stopped with code 1.
~/vale $ vale --v
vale version v2.8.0
~/vale $ 
```

**Comment by vinokurig** [comment]
Fixed by https://github.com/eclipse-che/che-plugin-registry/pull/895

**Comment by nickboldt** [comment]
Upstream only, no vale in CRW
