### ISSUE TITLE
Use Projector to run JetBrains IDEs

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19281]
### Is your enhancement related to a problem? Please describe.

JetBrains has recently released [Projector](https://blog.jetbrains.com/blog/2021/03/11/projector-is-out/) to run it's IDE remotely (for example in a container). That should provide a significative better UX than current vnc-based approach.

**Comment by azatsarynnyy** [comment]
dup of https://github.com/eclipse/che/issues/18619

**Comment by l0rd** [comment]
thanks @azatsarynnyy
