### ISSUE TITLE
Migrate che plugin broker builds from cico to GH actions

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19295]
### Is your task related to a problem? Please describe.

It appears that the plugin broker builds are still being built on cico:

* https://ci.centos.org/view/Devtools/job/devtools-che-plugin-broker-build-master/
* https://ci.centos.org/view/Devtools/job/devtools-che-plugin-broker-nightly/
* https://ci.centos.org/view/Devtools/job/devtools-che-plugin-broker-release/

```
        - '{ci_project}-{git_repo}-build-{branch}':
            git_organization: eclipse
            git_repo: che-plugin-broker
            ci_project: 'devtools'
            ci_cmd: '/bin/bash .cico/cico_build_ci.sh'
            timeout: '10m'
        - '{ci_project}-{git_repo}-nightly':
            git_organization: eclipse
            git_repo: che-plugin-broker
            ci_project: 'devtools'
            ci_cmd: '/bin/bash .cico/cico_build_nightly.sh'
            timeout: '10m'
        - '{ci_project}-{git_repo}-release':
            git_organization: eclipse
            git_repo: che-plugin-broker
            ci_project: 'devtools'
            ci_cmd: '/bin/bash .cico/cico_build_release.sh'
            timeout: '10m'
```

-- git@gitlab.cee.redhat.com:service/app-interface.git -> resources/jenkins/ci-centos/jobs.yaml

### Describe the solution you'd like

need new GH actions for these nightly/release builds

https://github.com/eclipse/che-plugin-broker/tree/master/.github

### Describe alternatives you've considered

In 2 weeks the cico service will be shut off, so the alternative is no more builds. :) 

### Additional context

See also https://github.com/eclipse/che/issues/19287

**Comment by amisevsk** [comment]
This task is on a backburner for now -- the current devfile 2.0 work does not require the plugin broker as written, so in all likelihood it will be deprecated before any further releases are required.
