### ISSUE TITLE
Migrate KIP and KIPO builds from cico to GH actions

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19294]
### Is your task related to a problem? Please describe.

It appears that the Kubernetes Image Puller and its Operator are still being built on cico:

* https://ci.centos.org/view/Devtools/job/devtools-kubernetes-image-puller-nightly/
* https://ci.centos.org/view/Devtools/job/devtools-kubernetes-image-puller-operator-nightly/

* https://ci.centos.org/view/Devtools/job/devtools-che-incubator-kubernetes-image-puller-build-master/
* https://ci.centos.org/view/Devtools/job/devtools-che-incubator-kubernetes-image-puller-operator-build-master/
* https://ci.centos.org/view/Devtools/job/devtools-kubernetes-image-puller-build-master/

```
        - '{ci_project}-{git_repo}-build-{branch}':
            git_organization: redhat-developer
            git_repo: kubernetes-image-puller
            ci_project: 'devtools'
            ci_cmd: '/bin/bash cico_build_deploy.sh'
            saas_git: saas-openshiftio
            extra_target: rhel
            timeout: 15m
        - '{ci_project}-{git_organization}-{git_repo}-build-{branch}':
            git_organization: che-incubator
            git_repo: kubernetes-image-puller
            ci_project: 'devtools'
            ci_cmd: '/bin/bash cico_build_ci.sh'
            timeout: 15m
        - '{ci_project}-{git_organization}-{git_repo}-build-{branch}':
            git_organization: che-incubator
            git_repo: kubernetes-image-puller-operator
            ci_project: 'devtools'
            ci_cmd: '/bin/bash cico_build_ci.sh'
            timeout: 15m
        - '{ci_project}-{git_repo}-nightly':
            git_organization: che-incubator
            git_repo: kubernetes-image-puller-operator
            ci_project: 'devtools'
            ci_cmd: '/bin/bash cico_build_nightly.sh'
            timeout: 15m
        - '{ci_project}-{git_repo}-nightly':
            git_organization: che-incubator
            git_repo: kubernetes-image-puller
            ci_project: 'devtools'
            ci_cmd: '/bin/bash cico_build_nightly.sh'
            timeout: 15m
```

-- git@gitlab.cee.redhat.com:service/app-interface.git -> resources/jenkins/ci-centos/jobs.yaml

### Describe the solution you'd like

need new GH actions for all these nightly/release builds for both repos.

* https://github.com/che-incubator/kubernetes-image-puller/tree/master/.github/workflows
* https://github.com/che-incubator/kubernetes-image-puller-operator/tree/master/.github/workflows

### Describe alternatives you've considered

In 2 weeks the cico service will be shut off, so the alternative is no more builds. :) 

### Additional context

See also https://github.com/eclipse/che/issues/19287

**Comment by ibuziuk** [comment]
> In 2 weeks the cico service will be shut off, so the alternative is no more builds. :)

@nickboldt where did you get that info? ci.centos.org jenkins instance will be okay to live past Q1

**Comment by nickboldt** [comment]
oh... I must have conflated Centos CI with the old CCIT Jenkins services. All good then. :D

**Comment by ibuziuk** [comment]
I mean it is a good idea to migrate everything to GH actions, just it is not that critical atm

**Comment by nickboldt** [comment]
This was apparently done in another issue. Both repos now use GHA. 

https://github.com/che-incubator/kubernetes-image-puller-operator
https://github.com/che-incubator/kubernetes-image-puller
