### ISSUE TITLE
Dashboard should allow CORS for any external devfile registry domain.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19302]
### Describe the bug
Defining an external devfile registry in CheCluster CR:

```yaml
    devfileRegistryUrl: https://sunix-che-devfile-registry-lombok-qpd6g.surge.sh
    externalDevfileRegistry: true
```
is failling to load the content because of CORS

![Selection_271](https://user-images.githubusercontent.com/650571/111337515-7315bf00-8676-11eb-92b5-5b02ba4f457d.png)

Looks like it is because this registry is not based on the che-plugin-registry container image: https://github.com/eclipse/che-devfile-registry/blob/master/.htaccess#L1

However, it dashbard should accept domain origin from external registries when defined.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Set your che server to use this devfile registry:
```yaml
    devfileRegistryUrl: https://sunix-che-devfile-registry-lombok-qpd6g.surge.sh
    externalDevfileRegistry: true
```

Open Get Started Page and it should fail to load (see screenshot above).

### Expected behavior
Should see the stacks.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
As far as I know, it's the registry that defines allowed requests but not wise versa.

**Comment by sunix** [comment]
OK my understanding was wrong. I will use https://code4developers.com/cors-anywhere/ as a workaround

**Comment by sunix** [comment]
Had surge.sh cors fixed with: https://surge.sh/help/enabling-cross-origin-resource-sharing
