### ISSUE TITLE
Add container registry checking

### ISSUE THREAD

**Issue by xbaran4** [eclipse-che/che#19308]
### Is your enhancement related to a problem? Please describe.

Right now, when adding container registry the UI is not very helpful in deciding whether I inputted a valid container registry.
It accepts any string of size <= 256. 
![image](https://user-images.githubusercontent.com/73115616/111453429-db66ae00-8713-11eb-92fe-0e261ee235ff.png)

### Describe the solution you'd like

Implement checking mechanism that would display ❌ on invalid container registry.

### Describe alternatives you've considered

Provide an example or hint of valid registry and let the user decide.

**Comment by flacatus** [comment]
Adding severity p2. Please feel free to change it

**Comment by sleshchenko** [comment]
But dashboard can't do much with registry validation.
Maybe we should just drop verification there to avoid confusion.

from Fatima

> we can also have a small info kind of line reminding folks to enter valid registry urls. I mean under the reg url text box.

**Comment by xbaran4** [comment]
> Maybe we should just drop verification there to avoid confusion.
I think this would suffice.
