### ISSUE TITLE
Che Server should include JSON schema for devfile 2.1.0-alpha

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19304]
### Is your task related to a problem? Please describe.
Currently, Che Server includes [1.0.0 and 2.0.0](https://github.com/eclipse/che/tree/master/wsmaster/che-core-api-workspace/src/main/resources/schema) Devfile versions, but there is also available 2.1.0-alpha:
https://github.com/devfile/api/blob/master/schemas/latest/jsonSchemaVersion.txt
https://github.com/devfile/api/blob/master/schemas/latest/devfile.json

Che Server should pull it as well.
It can be done manually, but then Devfile API side should know about Che Server dependency, so it would be more reliable if 2.1.0-alpha would be pulled like during build time, so then we'll be make sure that the latest available is used....

Also, since DevWorkspace operator depends on devfile api as well, and Che uses it for its integration with devfile v2, it makes sense to consider depending on the same version as DWO depends on:
https://github.com/devfile/devworkspace-operator/blob/main/Makefile#L26

**Comment by sparkoo** [comment]
fixed by #19552
