### ISSUE TITLE
Improve and fix dogfooding devfile for che-devfile-registry

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19305]
### Is your task related to a problem? Please describe.
Continue the work started in this PR: https://github.com/eclipse/che-devfile-registry/pull/345 to have a great dogfooding devfile for the che-devfile-registry

### Describe the solution you'd like
- [x] investigate 'start devfile-registry' task is failing when running it from a che-theia task.
- [x] add a badge in readme 
- [x] no more RestAPI with devworkspace: https://github.com/eclipse/che-devfile-registry/pull/345#discussion_r596736688
- [x] env variables CHE_WORKSPACE_NAMESPACE and CHE_WORKSPACE_NAME won't exist in devworkspace
- [x] don't use the plugin-registry builder/dev container image but create a dedicated one for devfile registry
- [ ] Fix the build/dev/build-devfile-registry.sh so that it generates dw and dwt (using ./generate_devworkspace_templates.sh)
- [ ] Add a command to build the offline version
- [x] Fix the UDI image with some [tweaks that allow using buildah in rootless mode](https://github.com/l0rd/tilt-example-java/blob/main/Dockerfile.dev?rgh-link-date=2022-07-14T21%3A48%3A43Z#L9)
- [ ] Add a build image command that builds the devfile registry image using buildah
- [ ] Add a publish image command that push the locally built image in a container registry using buildah
- [ ] Add a run with local image command that runs a custom devfile registry image using the locally built image
- [ ] Add a replace Che devfile registry command that patch the CheCluster to use the locally built devfile registry image

**Comment by l0rd** [comment]
Updated the issue description with what will be left after https://github.com/eclipse-che/che-devfile-registry/pull/663 is merged.
