### ISSUE TITLE
Removing a workspace is confusing when a user has 2 tabs

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19317]
### Describe the bug

I tried to remove a workspace, got the notification that the operation was successful.
But the deleted workspace was still displayed in the dashboard.
I tried to remove it again ==> the notification that it was successful ===> the workspace was still displayed
Refreshing a page resolved the problem.

I think the cause of the problem - I had 2 open tabs with dashboard.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Open 2 tabs with dashboard.
2. Try to remove a workspace

Please see a short video below.

Maybe some order switching between tabs before removing a workspace has an impact.

### Expected behavior

The deleted workspace is not displayed when the operation is successful.

### Runtime
 dogfooding instance
 
### Screenshots

![remove_workspace](https://user-images.githubusercontent.com/5676062/111592731-d36d4380-87d1-11eb-9fb6-15ebdb024cae.gif)

**Comment by sleshchenko** [comment]
I don't see how it's related to fact that you have two opened tabs, but that's weird bug

**Comment by RomanNikitenko** [comment]
I thought it's related because when I went to another tab - there the removed workspace was absent - so it looked like one tab displayed correctly the actual state and the active tab - incorrectly...
