### ISSUE TITLE
Increase default size of the persistent volume claim for workspaces

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19314]
### Is your task related to a problem? Please describe.
Currently pvcClaim size is `1Gi` [1] 
It is not enough for  `common` `pvcStrategy` in most cases.

### Describe the solution you'd like
The default value should be increased.

### Additional context
[1] https://github.com/eclipse-che/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L91-L96

**Comment by ibuziuk** [comment]
:+1: let's make it 10 to be compatible with the workspaces.openshift.com configuration

**Comment by sleshchenko** [comment]
A bit out of the current issue but qood question: We're able to change the existing PVC size? If no - it is clear from CheCluster CRD?

**Comment by tolusha** [comment]
It is possible by setting:  `spec.Storage.PvcClaimSize`

**Comment by sleshchenko** [comment]
I mean is Che Server is able to modify claimSize for already created PVCs, after Che Operator prodives the new value.
