### ISSUE TITLE
Activity tracker in User Dashboard

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#19310]
### Is your task related to a problem? Please describe.

Keycloak tokens are get updated before a request to Che API if it's going to expire within some predefined time. The current implementation of the User Dashboard performs much fewer requests to the API than the previous one, hence the possibility of expiring tokens is much higher. 

The example of such token expiration is the following:
- user edit workspace configuration for refresh token time (30minutes by default);
- user tries to save the made devfile configuration after that time, they redirected to login page with losing all the made stuff.

### Describe the solution you'd like
Implement a simple activity tracker to periodically update tokens during the usage of the UD that doesn't require interactions with the API.

### Describe alternatives you've considered

--

### Additional context

Tokens updating based on user activity may also resolve issues similar to described here: https://github.com/eclipse/che/issues/19307

**Comment by sleshchenko** [comment]
After we have activity tracker, we should be careful with updating token when reconnecting webSocket connection, because it will lead to endless user's session regardless keycloak settings.

**Comment by sleshchenko** [comment]
Seems it loses its priority since OpenShift OAuth is not something that allows you to refresh token in the same way as it was with keycloak. I assume the expected workflow is - once token is expired - go though OAuth flow again.

**Comment by akurinnoy** [comment]
This issue can be closed then. If it still makes sense we need to consider another approach how to help users and prevent losing something unsaved while they do authentication.
