### ISSUE TITLE
Creating factory from repository without devfile have confusing message

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#19312]
### Is your enhancement related to a problem? Please describe.
When applying factory from repository w/out devfile:

![image](https://user-images.githubusercontent.com/1651062/111483265-52fd0300-873d-11eb-80a0-88dd41cc26d8.png)

### Describe the solution you'd like
Imo it's better not to say that devfile is found, but say that there is no devfile and default workspace configuration will be applied.

**Comment by sleshchenko** [comment]
Closing in favor of https://github.com/eclipse/che/issues/19753
