### ISSUE TITLE
Che-docs devfile live-reload is not working

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19311]
### Describe the bug
When using the devfile in che-docs repo, livereload is not working and user need to refresh

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace from this devfile/repo in Che https://github.com/eclipse/che-docs
2. Start the preview server
3. open a file
4. make a change
5. no changes in the preview ... refreshing the preview page works

### Expected behavior
changes should not need manual refresh of the preview view

Maybe configuring a proxy providing the right route to the livereload url could work:
```
gulp.task('server', function(){
  connect.server({
    root: ['www'],
    port: 9000,
    livereload: true,
    middleware: function(connect, o) {
      return [ (function() {
          var url = require('url');
          var proxy = require('proxy-middleware');
          var options = url.parse('http://beta.rhinobird.tv/api');
          options.route = '/api';
          return proxy(options);
      })() ];
    }
  });
```

**Comment by themr0c** [comment]
Nice, I believe it never worked as expected and I have no clue how to fix it. Can you provide a PR with the change?

**Comment by sunix** [comment]
Yes I will give a try next time I have to contribute to che-docs

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-2842
