### ISSUE TITLE
DevWorkspaceTemplates are left on the cluster after devworkspace is removed

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19328]
### Describe the bug
DevWorkspaceTemplates leave on the cluster after devworkspace is removed.

I assume DevWorkspaceClient just need to set ~~foreground~~ [background](https://github.com/devfile/devworkspace-operator/blob/e0f5b03748220f7ece702c5c6081862438df13f0/pkg/provision/storage/cleanup.go#L80) deletion pull policy.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by JPinkney** [comment]
Fixed in https://github.com/eclipse/che-dashboard/pull/197
