### ISSUE TITLE
Migrate che projects to 'eclipse-che' organization

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19329]
### Is your task related to a problem? Please describe.

Followup to  #18995. Rate limiting in GH actions is now causing releases to take significantly longer. che-theia release this week was queued for >5hrs before the 25 min build could run.

Projects to migrate:

- [x]  https://github.com/eclipse-che/che-machine-exec - #18995
- [x]  https://github.com/eclipse-che/che-operator - #18995
- [x] https://github.com/eclipse/che-theia https://github.com/eclipse/che/issues/19391
- [x] https://github.com/eclipse/che-devfile-registry - #19388
- [x] https://github.com/eclipse/che-plugin-registry - #19387
- [x] https://github.com/eclipse/che-parent - https://github.com/eclipse/che/issues/19754
- [x] https://github.com/eclipse/che (server) - https://github.com/eclipse/che/issues/19754
- [x] https://github.com/eclipse/che-dashboard https://github.com/eclipse/che/issues/19614
- [x] https://github.com/eclipse/che-workspace-client https://github.com/eclipse/che/issues/19614

Projects we don't have to migrate:
- [x] https://github.com/che-incubator/chectl
- [x] https://github.com/che-incubator/devworkspace-che-operator
- [x] https://github.com/devfile/devworkspace-operator

Projects we could migrate (but won't bother for now):
- [ ] che-parent
- [ ] che-dev
- [ ] che-lib

### Describe the solution you'd like

In order to migrate che-* projects to new organization we should consider:

- Sync all release scripts
- Install Openshift CI github application in the new organization and related webhooks
- Make sure all tests will work in the new organization
- impacts on downstream syncs/jobs - https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins

**Comment by nickboldt** [comment]
Che parent, dev, and lib were not migrated as per https://github.com/eclipse/che/issues/19754 -> https://bugs.eclipse.org/bugs/show_bug.cgi?id=571958

But since they never get built anyway, I'm resolving this issue.

**Comment by benoitf** [comment]
@nickboldt should we move https://github.com/eclipse/che-release as well ?

**Comment by nickboldt** [comment]
We should! But I missed your comment here because firehose of GH emails :)

I've opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=574569 to move che-release as @mkuznyetsov realized today that he's being throttled there too.

**Comment by nickboldt** [comment]
bug resolved. PR merged https://github.com/eclipse-che/che-release/pull/38
