### ISSUE TITLE
Feature request: Devfile v2 editor in Dashboard

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19330]
### Is your task related to a problem? Please describe.
Currently, Dashboard provides read-only support for devworkspaces.

### Describe the solution you'd like
This issue is about adding an ability to modify and save devfile.

![Screenshot_20210318_165641](https://user-images.githubusercontent.com/5887312/111647172-ee0fde80-880a-11eb-81b2-80309ec1f5e6.png)

Note: plugins components should be hidden from editor.

**Comment by nickboldt** [comment]
I know nothing about the severity of this issue so I'll just set P1 so that the reporter or SMEs can comment and set the prio appropriately. Yaya round robin by nonSMEs!

**Comment by sleshchenko** [comment]
Since schemaVersion is not a part of devWorkspace, it should be stored somewhere in CR annotations.
