### ISSUE TITLE
Replace the templates from the website with the workspaces.openshift.com Getting Started devfiles

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#19337]
### Is your task related to a problem? Please describe.
Create a workspace from a template https://www.eclipse.org/che/getting-started/cloud/ should be updated with the getting-started devfiles from the workspaces.openshift.com

### Describe the solution you'd like
getting started templates are identical between the workspaces.openshift.com UD and the website

### Describe alternatives you've considered
N/A

### Additional context
As part of this task before each update of the workspaces. openshift.com the job / script should run and confirm that the devfiles promoted on the website exist in the upcoming release

**Comment by ibuziuk** [comment]
PR sent - https://github.com/eclipse/che-website/pull/58
All the getting started templates have been replaced with the devfiles from workspaces.openshift.com
Once merged the CI / script mechanism should be created to verify the links before the rollout update new CRW version to production

**Comment by Katka92** [comment]
We have a test and job for that. I think we can close the issue.
