### ISSUE TITLE
Wrong behavior after starting workspace from snapshot 

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1933]
**Reproduction Steps:**
1. Create snapshot
2. Stop workspace
3. Start workspace from snapshot

**Observed behavior:**

Workspace starts well but next error appears in browser console:
`Request URL:http://localhost:8080/wsmaster/api/recipe/script/machinedi5xowscpv2tfvgn
Request Method:GET
Status Code:500 Internal Server Error
java.net.URISyntaxException: Illegal character in scheme name at index 7: machine_snapshot_t1eg3vcfcyf0zrc4:latest`

**Che version:**   4.6.0-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**    local

**Comment by TylerJewell** [comment]
Removed severity blocker after issue update.  It was not clear that the ws starts normally even with the error.
