### ISSUE TITLE
Align TaskScope with VS Code API

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19338]
### Is your task related to a problem? Please describe.

At the moment the following `TaskScope` enum is used on `che-theia` side:
```
export enum TaskScope {
        Global = 0,
        Workspace = 1
}
``` 

The corresponding VS Code enum is:
```
export enum TaskScope {
	Global = 1,
	Workspace = 2
}
```
Theia has the difference as well, but it's going to be changed on `theia` side soon.

### Describe the solution you'd like

I believe we should align the enum with VS Code API ASAP to avoid conflicts.

### Describe alternatives you've considered

I don't see an alternative.

### Additional context

AFAIK the following plugins are affected:
- workspace-pugin
- containers-plugin
- task-plugin

and  eclipse-che-theia-plugin extension

**Comment by RomanNikitenko** [comment]
The corresponding PR in upstream was merged, locally at building images I got the following:
![tasks_scope_errors](https://user-images.githubusercontent.com/5676062/111812090-6bf1e980-88e0-11eb-8a44-2e18355322cb.png)

**Comment by benoitf** [comment]
thanks for the fix 👍
