### ISSUE TITLE
Fail to clone projects with `sparseCheckoutDir` set and `main` as a default branch 

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19346]
### Describe the bug
Starting `Quarkus REST API` devfile from `Get Started Page` fails to clone the project.

It seems to be related to 
```
sparseCheckoutDir: getting-started
```
and changes in the repo: now default branch is `main` (previously `master`)

### Che version

 - [x] latest 
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a new workspace from the `Quarkus REST API` devfile.
2. The workspace starts, It is starting to clone but never finish, no error message. The quarkus project folder is empty.

### Expected behavior
Should clone the project

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_281](https://user-images.githubusercontent.com/650571/111800716-85893600-88cc-11eb-9484-941f6930a858.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by sunix** [comment]
https://github.com/eclipse/che-devfile-registry/pull/351 is a quick-fix.
We need a proper fix, so keeping that one open.

**Comment by edeandrea** [comment]
I'm seeing a similar issue when trying to use `sparseCheckoutDir` in the developer sandbox (workspaces.openshift.com). My devfile has

```yaml
projects:
  - name: rhoar-getting-started
    source:
      type: git
      location: https://github.com/openshift-katacoda/rhoar-getting-started.git
      branch: solution
      sparseCheckoutDir: spring/spring-db-access
```

When the project gets checked out, the UI and the tooling (running `git branch`) shows `master`, yet the source code thats checked out reflects the correct branch (the `solution` branch in my specific case).

![Screen Shot 2021-07-20 at 11 53 25 AM](https://user-images.githubusercontent.com/363447/126356327-017a612b-0af6-4acd-9b9b-ebcda7c9cbdd.png)

**Comment by l0rd** [comment]
@svor does that make sense anymore? I don't think there is `sparseCheckoutDir` anymore in the [Devfile version 2](https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference/).

**Comment by svor** [comment]
@l0rd If it's not supported anymore, no sense.
Do you know if it's possible to use **starterProjects.subDir** in devfile v2 as an alternative way of `sparseCheckoutDir`.

**Comment by svor** [comment]
@l0rd fair enough
Closing the issue since devfile v2 doesn't support **sparseCheckoutDir** feature
