### ISSUE TITLE
Projects in the devfile registry should be owned by the Che team.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19359]
### Is your task related to a problem? Please describe.
We are cloning projects from Github. But these projects could move or change and causing regressions in our default devfiles in the Get Started Page.

### Describe the solution you'd like
Here is a list of projects that may need to be moved/forked to https://github.com/che-samples/:
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/angular/devfile.yaml#L10
  - fork https://github.com/che-samples/nodejs-angular
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/apache-camel-k/devfile.yaml#L10 (maybe not needed as it is maintained by @apupier?) 
  - fork https://github.com/che-samples/apache-camel-k
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/apache-camel-springboot/devfile.yaml#L10  (maybe not needed as it is maintained by @apupier?) 
  - fork https://github.com/che-samples/fuse-rest-http-booster
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/go/devfile.yaml#L10
  - fork https://github.com/che-samples/golang-example
  - fork https://github.com/che-samples/golang-echo-example
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-mysql/devfile.yaml#L10 - using commitId
  - fork https://github.com/che-samples/java-spring-petclinic
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-web-spring/devfile.yaml#L10  - using commitId
  - fork https://github.com/che-samples/java-spring-petclinic
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-web-vertx/devfile.yaml#L10 Is https://github.com/openshift-vertx-examples/vertx-http-example.git maintained by redhat ?
  - fork https://github.com/che-samples/java-web-vertx
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/nodejs-react/devfile.yaml#L10
  - fork https://github.com/che-samples/nodejs-react-redux
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-laravel/devfile.yaml#L10
  - fork https://github.com/che-samples/php-laravel
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-mysql/devfile.yaml#L10
  - fork https://github.com/che-samples/php-mysql
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-symfony/devfile.yaml#L10
  - fork https://github.com/che-samples/php-symfony
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml#L10
  - fork https://github.com/che-samples/quarkus-quickstarts
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus-command-mode/devfile.yaml#L10
  - fork https://github.com/che-samples/quarkus-quickstarts
- [x] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/scala-sbt/devfile.yaml#L10
  - fork https://github.com/che-samples/scala-sbt

### Describe alternatives you've considered
Have non-regression tests that covers all these flows.

**Comment by ericwill** [comment]
In order to increase stability we should fork all these sample projects into the `che-samples` org, and that way we don't have breaking samples due to things like branch names changing.

**Comment by apupier** [comment]
what about pointing to tags in pointed repositories? Can it be a valid solution fo rsome of them?

**Comment by sympatheticmoose** [comment]
This needs to be discussed alongside devfile v2 efforts around consolidating samples and #19442
