### ISSUE TITLE
Eclipse che - volume mount error while launching more than 5 workspace at a time

### ISSUE THREAD

**Issue by andr-azeez** [eclipse-che/che#19355]
### Describe the bug

Logged in 10 different users at the same time and launched 10 workspaces of each users at a time. 3 - 5 users are able to launch the workspace successfully, for remaining users getting time out error in mount volume, some users keep on loading the workspace and nothing is initialised in log window.

### Che version

 - [x] latest

### Advanced configuration: 
![ss](https://user-images.githubusercontent.com/81161330/111986361-dea6d300-8b33-11eb-8aa9-c4d409ffc551.png)

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
     * kubectl version - Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

### Installation method
   - [x] chectl
     * chectl installation command -  sudo chectl server:deploy --installer=helm --platform=k8s --domain=cl-ide.domain.com --multiuser --installer=operator 
     * chectl version - chectl/7.27.1 linux-x64 node-v12.21.0

### Environment
   - [ ] my computer
       - [x] Linux
   - [ ] Cloud
       - [x] GCE
         * Google Kubernete Engine (GKE) - with 2 nodes running
         * Node Configuration -  2 core 8 GB memory Machine with 30 GB hardisk
         * Auto scale is enabaled
### Screenshots

![Screenshot from 2021-03-22 16-57-43](https://user-images.githubusercontent.com/81161330/111983109-c5038c80-8b2f-11eb-8ab7-51209bff3e3d.png)

### Steps to reproduce

- Login 10 users at a time.
-  launch 10 different workspace at time. 

### Expected behavior
 It should be able to launch more than 50 workspaces at a time.

**Comment by vadirajspringpeople** [comment]
Even I am facing this issue, requesting to fix the issue ASAP.

**Comment by andr-azeez** [comment]
Same test is repeated again with the upgraded machine as
**Machine size:** 8 core vcpu / 16 gb memory 
**Nodes:** 3
**Auto Scaling :** Enabled

8 users are able to login successfully, 2 users got error as in screenshot 

![1sc](https://user-images.githubusercontent.com/81161330/112266912-b1c10000-8c9a-11eb-8d52-70fc814334d7.png)


![2sc](https://user-images.githubusercontent.com/81161330/112266925-b685b400-8c9a-11eb-9187-89aea7c4ad18.png)



Is there any concurrent queing issue or it has to be updated somewhere in advanced configuration?

**Comment by sleshchenko** [comment]
I believe there is not much Che can do with it.
I assume K8s behaves bad when one K8s namespace has many configmaps, which then should be mount to pod.
Che could merge all data to one configmap, but then you'll hit the same issue but with more running workspaces.
The only solution: use `per-user` namespace strategy. It's `workspaceNamespaceDefault: <username>-che`.
Note also that all workspace in one namespace, is going to be fully deprecated soon.

**Comment by andr-azeez** [comment]
Tried with the following config,

`server:`
`  workspaceNamespaceDefault: <username>-che`
`storage:`
`  pvcClaimSize: 1Gi`
`  pvcStrategy: common`

again facing the same issue, while loading 10 workspace at a time. It launches ~6 workspace successfully, remaining fails.

**Comment by sleshchenko** [comment]
Well, the issue you faced is not about PVC but about configmap cache, which is K8s internals.
=( that namespace strategy did not help.

The last thing I can try to workaround the issue: remove FailedMount from unrecoverable events, in CheCluster CR it should be like the following:
```yaml
spec:
  server:
    customCheProperties:
      CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS: FailedScheduling,MountVolume.SetUpfailed,Failed to pull image,FailedCreate,ReplicaSetCreateError
```
Then workspace won't fail immediately after warning happened and maybe it will go further.

You may find a solution for you cluster and you search `kubernetes failed to sync configmap cache timed out waiting for the condition`, I see some issues on github created.

**Comment by andr-azeez** [comment]
Changed the configuration as follows:

```spec:
  server:
    customCheProperties:
     CHE_INFRA_KUBERNETES_PVC_JOBS_MEMORYLIMIT: 756Mi
      CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS: FailedScheduling,MountVolume.SetUpfailed,Failed to pull image,FailedCreate,ReplicaSetCreateError`
````

Now tested with 20 users and launched 20 workspaces of random stacks. 
Most of the workspace skipped the error with `kubernetes failed to sync configmap cache timed out ` but able to launch the workspace successfully.
Nearly 15 - 17 workspace were launched successfully and nearly 4 - 5 workspace got `workspace launch time out` error.

Next step is to test about to launch 50 workspace simultaneously, and I will post the result here once the test is done.
