### ISSUE TITLE
Add an ability to async remove non stopped workspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19367]
### Is your task related to a problem? Please describe.
The UX would be better(and consistent with devworkspaces) if user would have an ability to remove Che workspaces even if they are not stopped yet.

### Describe the solution you'd like
So, there should be an query parameter that would allow mark workspace as one which should be deleted, once it's stopped, and initiate stop process if it's running.

Such workspaces should have some attribute to make it clear for client that it's going to be removed.

Also, workspace removal event should be sent trough websocket.

### Describe alternatives you've considered
Require user to stop workspace and only then remove it manually.

### Additional context
It may be good to have a new workspace status, like terminating but I think it's not mandatory at all.

**Comment by gazarenkov** [comment]
@skabashnyuk is it an actual che-server related issue?

**Comment by skabashnyuk** [comment]
No longer relevant for devworkspaces.
