### ISSUE TITLE
Trying to stop a DevWorkspace make it restart

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19369]
### Describe the bug
Apply `spec: started : false` and workspace is not stopped but restarted.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Start a DevWorkspace using Eclipse Che
Edit DW and replace 'spec/started: true' by false

It restarts my workspace

https://user-images.githubusercontent.com/436777/112119234-78ff2900-8bbd-11eb-9a86-15f452da2c0f.mp4

### Expected behavior
Workspace is stopped

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
It should be cherry-picked into 7.28.x (DWO 0.2.x) if it's not done before release.

**Comment by sleshchenko** [comment]
I think would be great if we back-ported it to 7.28.x

**Comment by amisevsk** [comment]
Does not reproduce for workspaces created manually (i.e. no Che running).

**Comment by dmytro-ndp** [comment]
@benoitf, @amisevsk: the issue is duplicating https://github.com/eclipse/che/issues/19379 and had already fixed by https://github.com/eclipse/che-dashboard/pull/193 in Eclipse Che 7.28.0

**Comment by sleshchenko** [comment]
@dmytro-ndp thanks for hint.
I'll try DevWorkspace created by Che and make sure it works.

**Comment by benoitf** [comment]
workspace is now stopped (and pods removed)

```
NAMESPACE   NAME               WORKSPACE ID                PHASE     INFO
user1-che   spring-petclinic   workspaceea5ac4ddc8354c9e   Stopped   Stopped
```
