### ISSUE TITLE
Support telemetry for Red Hat VS Code extensions in Eclipse Che

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19361]
### Is your task related to a problem? Please describe.
In order to enable telemetry support in Che, we need to add the [vscode-commons](https://github.com/redhat-developer/vscode-commons/) vsix to all Che plugins in the plugin registry.

### Describe the solution you'd like
Since all plugins in the registry should have this vsix in their `extensions` list, it's something we can add at build time. Perhaps something like:
* Create a `defaultExtensions.json` in the root of the plugin registry. This file will contain a list of vsix files that should be present in all Che plugin registry entries
* Modify the che-plugin-registry build process to automatically append any vsix listed in `defaultExtensions.json` to the `extensions` field of every generated `meta.yaml` file

### Describe alternatives you've considered
Manual addition of the vscode-commons vsix file to all Che plugin entries in `che-theia-plugins.yaml`

**Comment by ericwill** [comment]
@fbricon is the expectation that the `vscode-commons` plugin will work if there are multiple instances of it running in the same workspace? If so we could just naively add it to every supported plugin entry. However if it's a problem, then we'll have to figure out a way so that there is only ever one running instance of the plugin in any given workspace.

**Comment by tsmaeder** [comment]
Is there anything special in the commons extensions that would prevent us from just running it as a built-in extension in the theia back-end? Extensions API _can_ be invoked remotely.

**Comment by fbricon** [comment]
I believe not a single VS Code extension out there is expected to work properly when multiple instances are running concurrently. I don't even know how it'll behave or how we'd mitigate issues.

Having a single extension across the whole installation is definitely the safest

**Comment by ericwill** [comment]
> I believe not a single VS Code extension out there is expected to work properly when multiple instances are running concurrently. I don't even know how it'll behave or how we'd mitigate issues.
> 
> Having a single extension across the whole installation is definitely the safest

Do you know if there are any concerns about it not running in the same container as an extension? Otherwise we can enable this trivially by making it a che-theia built-in, as Thomas has suggested.

**Comment by benoitf** [comment]
AFAIK It can't be part of che-theia built-in for Che, it's not a mandatory extension at all just a Red Hat specific extension (built-in plug-in is what is default on VS Code), .

**Comment by tsmaeder** [comment]
@benoitf good point: requiring red hat stuff for an Eclipse project is bad form. What's the state of inter-che-plugin dependencies these days?

**Comment by ericwill** [comment]
I don't mind investigating alternatives, but I also don't object to adding it as a built-in if there are no possible alternatives. Not having this plugin installed is blocking us from upgrading other extensions.

**Comment by sympatheticmoose** [comment]
For what its worth, it seems that installing vscode-commons by itself doesn't really do anything as far as a user is concerned. It is only activated by the extensions which depend on it.

**Comment by l0rd** [comment]
@ericwill closing because the PR has been merged. Feel free to reopen if needed.

**Comment by vinokurig** [comment]
I've tried to start the lates `openshift-connector` plugin:
```
apiVersion: 1.0.0
metadata:
  name: wksp-ezioz
components:
  - type: chePlugin
    reference: 'https://gist.github.com/vinokurig/b1eb70baca6ddf96025743cbe0444f88/raw/a0d89a96c25cb1a534963ec93f94717b0e2e8317/plugin-meta.yaml'
```
and it fails because of the `redhat.vscode-commons` plugin:
![screenshot-che-eclipse-che 192 168 99 118 nip io-2021 05 24-09_09_38](https://user-images.githubusercontent.com/7668752/119305233-200d4900-bc71-11eb-984c-12960a116a58.png)

**Comment by vinokurig** [comment]
@benoitf could you please check it?

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/CRW-1818

**Comment by ericwill** [comment]
I suppose we should wait until the `vscode-commons` extension is removed. The other option is that we include the vscode-commons extension in the openshift-connector plugin definition. @benoitf WDYT?

**Comment by benoitf** [comment]
Openshift connector has removed the dependency to vscode-commons 
https://github.com/redhat-developer/vscode-openshift-tools/commit/f22a6d3308ad4bd6dbf43665050d3a9c453b7083
but it has not yet released a new version but I would say it'll be done pretty soon.

I think that if we include commons extension in the openshift connector, it will collide with the plugin added by default by che-server (so should be removed first)
