### ISSUE TITLE
Workspace stuck on importing zip project

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#19377]
### Describe the bug
Eclipse Che 7.28.0-SNAPSHOT can't import project in workspace: https://che-nightly-che.apps.ocp47.crw-qe.com/dashboard/
Che-theia pod logs:
```
2021-03-24 08:10:56.470 root INFO PluginTheiaDirectoryHandler: accepting plugin with path Params: /plugins/installed.json
2021-03-24 08:10:56.470 root INFO PluginTheiaDirectoryHandler: accepting plugin with path Params: /plugins/sidecars
2021-03-24 08:10:56.471 root ERROR Failed to load plugin dependencies from '/plugins/installed.json' path Params: Error: ENOTDIR: not a directory, open '/plugins/installed.json/package.json'
2021-03-24 08:10:56.472 root ERROR Failed to load plugin dependencies from '/plugins/sidecars' path Params: Error: ENOENT: no such file or directory, open '/plugins/sidecars/package.json'
2021-03-24 08:10:56.587 root WARN Backend CheMiniBrowserEndpoint.onStart is slow, took: 148.8 ms
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Eclipse Che to OpenShift or minikube
2. Go to dashboard and start Java maven or Go workspace
3. Wait on workspace is created and zip project is imported

### Expected behavior
zipped project content:
- has been downloaded from devfile registry https://devfile-registry-nightly-che.apps.ocp47.crw-qe.com/resources/golang-golang-echo-realworld-example-app-master.zip
- extracted into workspace
- appeared in Project Tree panel

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift 4.7
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2021-03-23 23-09-41](https://user-images.githubusercontent.com/1197777/112219357-8c49dd00-8c2d-11eb-9db8-3c35ef516b80.png)

### Installation method
   - [x] chectl server:deploy
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * chectl next
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs
[devfile-registry logs|https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/dashboard-next-happy-path/494/artifact/logs-and-configs/che-logs/devfile-registry-5dfcdd578b-v8ptz.pod.log/*view*/]:
```
Updating devfiles to point at internal project zip files
[Tue Mar 23 20:18:38.704835 2021] [unixd:alert] [pid 14:tid 140125615336776] (1)Operation not permitted: AH02156: setgid: unable to set group id to Group 2
[Tue Mar 23 20:18:38.705057 2021] [unixd:alert] [pid 15:tid 140125615336776] (1)Operation not permitted: AH02156: setgid: unable to set group id to Group 2
[Tue Mar 23 20:18:38.705111 2021] [mpm_event:notice] [pid 1:tid 140125615336776] AH00489: Apache/2.4.43 (Unix) configured -- resuming normal operations
[Tue Mar 23 20:18:38.705311 2021] [core:notice] [pid 1:tid 140125615336776] AH00094: Command line: 'httpd -D FOREGROUND'
[Tue Mar 23 20:18:38.705279 2021] [unixd:alert] [pid 16:tid 140125615336776] (1)Operation not permitted: AH02156: setgid: unable to set group id to Group 2
```

### Additional context
Related changes: https://github.com/eclipse/che-theia/pull/1014/files

**Comment by vzhukovs** [comment]
@vitaliy-guliy, can you take a look? AFAIK, workspace plugin is responsible for importing zip projects.

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy, can you take a look? AFAIK, workspace plugin is responsible for importing zip projects.

It's strange. In general it become not working after merging this PR https://github.com/eclipse/che-theia/pull/1014
or even earlier https://github.com/eclipse/che/issues/19120

But the PR https://github.com/eclipse/che-theia/pull/1014 should not broke cloning of the projects, as it just include system default certificates to list of certificates and that's it.

**Comment by vitaliy-guliy** [comment]
@l0rd reported the same problem https://github.com/eclipse/che/issues/19309#issuecomment-802408031

**Comment by vitaliy-guliy** [comment]
Workspace plugin must find all available certificates/bundles and write them all to `/tmp/ca-bundle.crt`.
I noticed, that `/tmp/ca-bundle.crt` does not exist. That's why `curl` was not able to download zip.

Here we have two issues:
- bundle is not created in temporary directory
- workspace plugin is not failed and reported that missing certificate/bundle
