### ISSUE TITLE
Explicitly enable/disable multi-root in devfiles of che-devfile-registry 

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19375]
### Is your task related to a problem? Please describe.
Currently multiroot is disabled by default. this is a new feature. Could be enabled in devfile with:
```yaml
attributes:
 multiRoot: 'on'
```
Multiroot may be activated by default in the next weeks.
Some devfile may not work yet.

### Describe the solution you'd like
The idea of this issue is to explicitly enable or disable multi-root in devfiles of the che-devfile-registry. Enabled if no problem. Disabled if any problem.

**Comment by sunix** [comment]
So far:
- Quarkus Rest API devfile is broken with multiroot: didact.md is referencing a file to open concidering the project root is `/projects`. Will be fixed with the upcomming PR
- Golang devfile is broken with multiroot: no code completion as it is.

**Comment by benoitf** [comment]
for golang it's quite disappointing as multi-root workspace should fix imports from the project !

**Comment by azatsarynnyy** [comment]
Doesn't it require enabling go modules in multi-root mode?

**Comment by sunix** [comment]
no idea ... I am a Golang newbie

**Comment by sunix** [comment]
Not related to multi-root: the `Java Spring Boot` devfile `maven build` is failing (killed). I tried increasing the memoryLimit to 1G and it works.

**Comment by sunix** [comment]
Not related to multi-root: the python stack does not have code completion....

**Comment by sunix** [comment]
same for python django
-> the preview is not working. Maybe CORS (it works in its own window)

**Comment by sunix** [comment]
I may have a fix for python and python django to come

**Comment by sunix** [comment]
Closing as it has been covered with https://github.com/eclipse-che/che-devfile-registry/pull/359
