### ISSUE TITLE
Refactor devworkspace client where Che and DevWorkspace logic are separate interfaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19382]
### Is your task related to a problem? Please describe.
Refactor devworkspace client where Che and DevWorkspace logic are separate interfaces.

DevWorkspace client would handle some basic CRUD for devworkspaces and devworkspace templates (along with tricky ownerRef logic we have on dashboard now).

Che part should handle at least setting Che Routing, then maybe work with Che Plugin Registry(but for time being it's OK if it will leave on dashboard side.

**Comment by JPinkney** [comment]
Done in https://github.com/che-incubator/devworkspace-client/pull/16. I also made it so that you can set the routingClass in the create method to remove the dependency on che routing.
