### ISSUE TITLE
Unable to copy public key from SSH prefs

### ISSUE THREAD

**Issue by joeldavis84** [eclipse-che/che#1938]
Just started Eclipse Che, trying to pull in a remote repository and I'm unable to either generate an ssh key pair or upload one I make on another server. I get the option to upload at Profile>Preferences>SSH>VCS but it only seems to ever ask for the private key. If I use the option to automatically generate a key that also seems to work but I can't copy the public key out of the web ui and it looks too short (the hostname portion at least is clipped) 

**Reproduction Steps:**
1. Start Eclipse Che with CHE_HOME set to /opt/che and the Oracle 1.8 JRE (Che is not dockerized, just the workspaces).
2. Create a new workspace
3. Create a project in said workspace, 
4. initialize git, configure remote and attempt to pull
5. Realize you need to set up the ssh keys, go into profile preferences, cry a little bit, and eventually realize there's no way to get both public and private in both gitlab and Che.

**Expected behavior:**

I should be able to import a project from gitlab similar to how the regular IDE can.

**Observed behavior:**

There's no option to upload a key pair and generating a key pair works but I can't seem to find a way to get it out. The "Machine" screen has an option to download but even that appears to only be for the private key. Even ignoring the lack of a "view" on public key pulls still fail. 

**Che version:**    4.5.1
**OS and version:** RHEL 7.2
**Docker version:**  1.11.2
**Che install:**    server (zip)

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No] n/a (fresh install no prior experience with Che)
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes

This is what I see when trying to upload a pre-existing keypair:
![image](https://cloud.githubusercontent.com/assets/4549727/17123502/e6e26bfc-52b1-11e6-9b43-e0b508b9f78c.png)

This is what I see when trying to retrieve the public key on a generated pair:

![image](https://cloud.githubusercontent.com/assets/4549727/17123529/1abc6fd6-52b2-11e6-8dd6-97438244cf0b.png)

Highlighting text and doing CTRL-C apparently doesn't copy the public key.

**Comment by ghost** [comment]
@joeldavis84 

First off, when uploading a private key you need to specify host which should be `gitlab.com` in your case.

Secondly, you need to upload an existing private key to Che and make sure it's public part is added to SSH keys in your GitLab account. Or, you generate a new key, copy its public part and save it to your GitLab account. And this is where the copy issue shows up.

I am labeling this one as a bug. However, if you have an existing key, upload it with the right hostname, and you should be good to go.

**Comment by joeldavis84** [comment]
Alright no this does appear to be pilot error. Sorry about that.

**Comment by riuvshin** [comment]
@vparfonov seems we need take this and fix in 4.6.0
