### ISSUE TITLE
Migrate che-devfile-registry to the eclipse-che organization

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19388]
### Is your task related to a problem? Please describe.
GitHub actions have been hanging for awhile due to organization wide resource limits. It's high time we migrated to the eclipse-che organization in GitHub to avoid this. Also, we need to migrate in order to allow openshift-ci PR checks to run.

### Describe the solution you'd like
Migrate to the eclipse-che organization.

### Describe alternatives you've considered
N/A

**Comment by nickboldt** [comment]
Hopefully the only thing downstream of this we have to adapt is:

https://github.com/eclipse/che-release/blob/master/make-release.sh#L140-L145

Not sure if we need to do anything for CRW as registry is a fork w/ no (partial) sync to upstream yet.

**Comment by flacatus** [comment]
Hi @ericwill !
Deploy team already migrate repos to new organization. Please use our bugzilla to migrate to avoid creating separate Bugzilla issues for each repo migration.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=571958
