### ISSUE TITLE
inject annotation into the workspace deployment object

### ISSUE THREAD

**Issue by fcomte** [eclipse-che/che#19386]
### Is your enhancement related to a problem? Please describe.
Is it possible to inject some annotations to the deployment workspace ?

### Describe the solution you'd like
I would like to be able to write some annotation in a devfile.yaml that will be inject into the kubernetes object of the workspace
It could help developpers to manage some external tools like vault to inject secrets.

**Comment by l0rd** [comment]
@fcomte please have a look at [this documentation article](https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-from-remote-devfile/#allowing-users-to-define-workspace-deployment-labels-and-annotations_che). It should address your problem.

**Comment by fcomte** [comment]
I am unable to make this functionnality works.
Annotations are not added to the deployment annotations.. Is there any prerequisite that is not write into the documentation?

**Comment by fcomte** [comment]
```
Version
7.28.2
Browser Name
chrome
Browser Version
90.0.4430
Browser OS
Windows 10
```
