### ISSUE TITLE
Devfile registry: move all the Java 8 based devfiles to Java 11

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19385]
### Is your enhancement related to a problem? Please describe.
We still have Java devfiles based on Java 8 in the che-devfile-registry. Java 8 is going end of life. 

### Describe the solution you'd like
Should move to Java 11 (LTS) or the latest (but would need to have the right stack for that).

**Comment by apupier** [comment]
For Fuse, Java 8 is still required.
Java 11 will be supported starting with Fuse 7.9 which is planned to be released for the 31st of May 2021

**Comment by sympatheticmoose** [comment]
<img width="1503" alt="Screenshot 2021-03-26 at 17 19 11" src="https://user-images.githubusercontent.com/19860021/112669257-64d65880-8e57-11eb-84c7-8cfe4425e9f5.png">
I've got significant concerns with this proposal as lots of people are still using Java 8. Take this example from the State of the JVM survey Synk published last year (new one is currently running) and search Java 8 to find the torrent of abuse in the reviews of the Java plugin for VS Code https://marketplace.visualstudio.com/items?itemName=redhat.java&ssr=false#review-details

**Comment by ericwill** [comment]
> <img alt="Screenshot 2021-03-26 at 17 19 11" width="1503" src="https://user-images.githubusercontent.com/19860021/112669257-64d65880-8e57-11eb-84c7-8cfe4425e9f5.png">
> I've got significant concerns with this proposal as lots of people are still using Java 8. Take this example from the State of the JVM survey Synk published last year (new one is currently running) and search Java 8 to find the torrent of abuse in the reviews of the Java plugin for VS Code https://marketplace.visualstudio.com/items?itemName=redhat.java&ssr=false#review-details

Thanks for bringing this up, let's keep Java 8 for now then.

**Comment by sunix** [comment]
@ericwill @sympatheticmoose this is not about removing the java8 plugin, but updating our default devfiles when we are saying "Java".
Also, when has this survey been done?

**Comment by sunix** [comment]
so this is about updating the Get Started devfiles. Not about removing the Java 8 plugin. We don't want developers to Get Started with Java8, do we?

**Comment by ericwill** [comment]
We should probably include one Java 8 `Getting Started` just so that people know that we support it and it's possible to use Java 8 in Che. I am :+1: to migrate the rest though.
