### ISSUE TITLE
Migrate the che-plugin-registry to the eclipse-che organization

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19387]
### Is your task related to a problem? Please describe.
GitHub actions have been hanging for awhile due to organization wide resource limits. It's high time we migrated to the eclipse-che organization in GitHub to avoid this. Also, we need to migrate in order to allow openshift-ci PR checks to run.

### Describe the solution you'd like
Migrate to the eclipse-che organization.

### Describe alternatives you've considered
N/A

**Comment by nickboldt** [comment]
Hopefully the only thing downstream of this we have to adapt is:

https://github.com/eclipse/che-release/blob/master/make-release.sh#L140-L145

Not sure if we need to do anything for CRW as registry is a fork w/ no (partial) sync to upstream yet.

**Comment by benoitf** [comment]
https://github.com/eclipse/che/blob/master/.repositories.yaml and its script to update CONTRIBUTING.MD need to be updated as well

**Comment by ericwill** [comment]
>     * https://github.com/eclipse/che-release/blob/master/make-release.sh#L140-L145

What do these lines have to do with moving to the `eclipse-che` org? Maybe I am missing something.

**Comment by benoitf** [comment]
It's the top level project orchestrating release jobs launch to other repositories
So if one repo being used will move to a new location, we need to update it
