### ISSUE TITLE
Merge DWCO and CO in a single codebase

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19408]
### Is your task related to a problem? Please describe.
This is a sub task of [1] and the second step to merge DWCO and CO in a single codebase.

### Describe the solution you'd like
We have to:
- Pick up a build system
- Merged codebase
- Update release process

### Additional context
[1] https://github.com/eclipse/che/issues/19145

**Comment by metlos** [comment]
I've created a separate https://github.com/eclipse/che/issues/20088 as a prerequisite of this issue.

**Comment by metlos** [comment]
The current state of this issue is that I was able to run at least some of the failing CI tests sucessfully locally. But for them to pass we need a patch to DWO with this PR https://github.com/devfile/devworkspace-operator/pull/504.

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse-che/che-operator/pull/925
