### ISSUE TITLE
Run DWCO and CO in single pod but different containers

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19402]
### Is your task related to a problem? Please describe.
This is a sub task of [1] and the first step to merge DWCO and CO in a single codebase.

### Describe the solution you'd like
We have to:
- Merged deployment files
- Merged RBAC
- Update e2e tests

### Additional context
[1] https://github.com/eclipse/che/issues/19145

**Comment by sparkoo** [comment]
shouldn't it be "single pod with 2 containers" rather than "single container but in different pods"?

**Comment by mmorhun** [comment]
As all the subtasks are done, I am marking this issue as resolved.
