### ISSUE TITLE
Add an option to stop a workspace while it is starting

### ISSUE THREAD

**Issue by tstastna** [eclipse-che/che#19414]
It would be convenient to be able to stop a workspace in the **Starting workspace _<workspace_name>_** tab, instead of having to go to **Workspaces**.

**Comment by sleshchenko** [comment]
We discussed it a bit some time ago and decision was to add Actions to Restart/Stop workspace into Workspace Loading page, similar what we have for Workspace Details.
![Screenshot_20210402_094916](https://user-images.githubusercontent.com/5887312/113389440-b5d6d700-9398-11eb-81db-44eb87f41514.png)
