### ISSUE TITLE
Access token is not automatically used in Swagger UI for CodeReady Workspaces

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#19411]
If a user wants to interact through the API they need their access token which we automatically add to requests made in Swagger UI. It apparently works in Che, but not CodeReady Workspaces, including on DevSandbox (https://workspaces.openshift.com/swagger) where requests return a 401 unauthorized.

Workaround exists since you can grab the token from the network tab in Chrome DevTools, but this isn't in any way clear to an end user.

**Comment by ibuziuk** [comment]
@skabashnyuk I suppose this issue is single-host specific

**Comment by sympatheticmoose** [comment]
@ibuziuk I thought multi-host was the default? This also presents on my AWS OCP 4.7 cluster and I wouldn't have specified anything non-default

**Comment by ibuziuk** [comment]
multi-host is the default for now, but I suppose this is going to change in the short run. e.g. workspaces.openshift.com is running against single-host
