### ISSUE TITLE
[doc] Improvements to Creating a workspace using a factory link

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19413]
Changes to: https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-from-remote-devfile/

* Rename the story "Creating a workspace from remote devfile" into: "Creating a workspace using a factory link"
* In the intro, the link on devfile.yaml in is pointing to the che devfile in GitHub. This link is not necessary.
* There are two forms for factory URL: make the following list a list.
* Procedure and examples should use the same syntax for the factory link (`#` when possible).
* Procedure with one step should use an unordered list.
* Use an example block for the examples.
* The example in "Creating a workspace from a publicly accessible standalone devfile using HTTP" should be a standalone devfile.
* The examples in "Overriding devfile values using factory parameters" should be consistent.
* This example need either the correct value for the repository-url, or make replace other values by a placeholder (web-java-spring-petclinic, branch name) https://workspaces.openshift.com/f?url=<repository-url>&override.projects.web-java-spring-petclinic.source.branch=1.0.x

**Comment by MichalMaler** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2876

**Comment by sumitgsh** [comment]
@themr0c I am very new to kubernates and Would love to contribute on this issue ,can u please guide me through the process
