### ISSUE TITLE
Switch `che-operator`, `che-machine-exec` and `chectl` from `master` to `main` branches

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19410]
### Describe the solution you'd like
Switch `che-operator` and `che-machine-exec` from `master` to `main` branch

**Comment by nickboldt** [comment]
In https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/tree/master/jobs/CRW_CI we have a number of .groovy scripts which fetch code from 'master' branch for the 2.x versions of the jobs. These references will have to be changed to 'master'.

**Comment by flacatus** [comment]
Done in downstream gitlab.
