### ISSUE TITLE
Java code analysis bug

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#1941]
I've found bug in Java code analysis. 

Here is the code that was misunderstood by Java analyzer https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L794

![selection_011](https://cloud.githubusercontent.com/assets/1851863/17128852/331b03ba-5318-11e6-9c3e-8d359e158fbb.png)

**Che version:**    4.6.0-Snapshot
**OS and version:** Ubuntu 14.04
**Docker version:** 1.11.2
**Che install:**    Docker container

**Comment by JamesDrummond** [comment]
@vparfonov Please provide status.

**Comment by musienko-maxim** [comment]
Cannot reproduce
