### ISSUE TITLE
Dashboard devfile editor: Autocompletion for plugin's id doesn't work

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19423]
### Describe the bug

Autocompletion for plugin's id doesn't work. I can see the small window but it is not possible to switch into that window and scroll it to see all elements.

### Steps to reproduce
1. Create a workspace  and go to the devfile editor
2. Try to change the id of some chePlugin component by using ctrl+space

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2021-03-26 15-32-21](https://user-images.githubusercontent.com/1271546/112639048-8714aa00-8e48-11eb-9865-f1aaa58f63dc.png)

**Comment by sunix** [comment]
I could reproduced in my gcp cluster with 7.28.0. To me this is a major issue as we cannot add plugins anymore ...

**Comment by sunix** [comment]
when trying from che-theia: 
![Eclipse Che_315](https://user-images.githubusercontent.com/650571/113408474-b5960600-93af-11eb-9226-9b09dc31feff.png)

So not sure it is a dashboard issue

**Comment by sleshchenko** [comment]
The dashboard side is fixed by https://github.com/eclipse/che-dashboard/commit/e0638a5102ecfd73166a5dbb67da8b7b6760e70f

@sunix if you still face the issue on dashboard or Theia side - please create a dedicated issue.
