### ISSUE TITLE
That's not possible to override devfile attribute with dots in its name

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19426]
Following procedure: https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-from-remote-devfile/#overriding-devfile-values-using-factory-parameters_che

I used this example instead of the placehosder:
https://<che-host>dashboard/#/load-factory/?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che&override.attributes.dot.name.format.attribute=true

```
Danger alert:Failed to create a workspace. Error: Failed to create a new workspace from the devfile: Devfile schema validation failed. Error: (/attributes/dot):The value must be of string type, but actual type is object.
```

**Comment by themr0c** [comment]
Sorry for the labels collision.

**Comment by sympatheticmoose** [comment]
FWIW http://workspaces.openshift.com/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che&override.metadata.generateName=myprefix worked for me... not sure if the attribute being overridden has to be present in the devfile beforehand? i.e there is no `attribute` in that devfile.

**Comment by benoitf** [comment]
workspaces.openshift.com is using the old dashboard so it might explain as well

**Comment by themr0c** [comment]
@sleshchenko could not reproduce as well, but I could reproduce it both on Firefox and Chrome with user42 on the cluster up for the click party on Friday. Note that the autocompletion in the devfile editor was not working as well.

**Comment by sleshchenko** [comment]
That's related to Dashboard.
I checked and Che Server correctly handles such overrides
![Screenshot_20210402_100929](https://user-images.githubusercontent.com/5887312/113391090-a1e0a480-939b-11eb-9001-659288111cc2.png)

Closing and it will be fixed by https://github.com/eclipse/che/issues/19424 when Dashboard will again use Che Server to perform overriding
