### ISSUE TITLE
dashboard devfile editor: should have component types as main suggested completion items for components

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19429]
### Describe the bug
At the moment, writing a devfile in the dashboard and adding a new component. Code completion is suggesting many items that may not be usuable in all the components type. For kubernetes components, `memoryLimit` is display but doesn't make sense.
If no type is specified, the editor should suggest
- all the component types available
- name
- alias

and let the other suggestion being available once the type is selected.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Screenshots
![Selection_299](https://user-images.githubusercontent.com/650571/112649357-a7ddff00-8e4a-11eb-94da-91733bfe755b.png)
![Selection_300](https://user-images.githubusercontent.com/650571/112649370-aa405900-8e4a-11eb-84f3-1834ce13fbae.png)

**Comment by sunix** [comment]
I could reproduced in my gcp cluster with 7.28.0. To me this is a major issue as we cannot add plugins anymore ...

**Comment by sunix** [comment]
opps wrong issue

**Comment by sleshchenko** [comment]
Assigning enhancement, since AFAIK it's yaml language server that provides that + it did not work in such way.
Yaml language server should better work in the latest JSON Schemas where such configure field with some condition appeared.
