### ISSUE TITLE
"Delete workspace" should not be enabled for running workspaces

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19421]
### Is your enhancement related to a problem? Please describe.
On the workspace page of the dashboard, the "Delete Workspace" action is enabled for running workspaces. The "Start in Background" and "Start in Verbose Mode" actions are disabled. But when I execute "Delete Workpace", the action fails telling me you can't do that.

### Describe the solution you'd like
The "Delete Workspace" action should be disabled for running workspaces.

**Comment by RomanNikitenko** [comment]
The similar issues: 
- https://github.com/eclipse/che/issues/19081
- https://github.com/eclipse/che/issues/19251
- https://github.com/eclipse/che/issues/18761

**Comment by sleshchenko** [comment]
closing. it's fixed for DevWorkspaces and won't be for Che Workspaces.
