### ISSUE TITLE
 Restart in Verbose Mode link

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19428]
https://www.eclipse.org/che/docs/che-7/end-user-guide/investigating-failures-at-a-workspace-start-using-the-verbose-mode/

Documentation says: click on the displayed Restart in Verbose Mode link.

Dashboard next displays: "Open in Verbose mode".

**Comment by boczkowska** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2903

**Comment by sleshchenko** [comment]
https://www.eclipse.org/che/docs/che-7/end-user-guide/investigating-failures-at-a-workspace-start-using-the-verbose-mode/ now has `Open in Verbose mode` which is consistent with what dashboard has. Closing this one.
