### ISSUE TITLE
Dashboard: Failed to run the workspace: "Your session has expired.....

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19420]
### Describe the bug
Restarting a workspace and got the error:
```
Failed to run the workspace: "Your session has expired. Please <a href='javascript:location.reload();' target='_top'>login</a> to Che again to get access to your OpenShift account"
```
Refreshing the page is OK

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_297](https://user-images.githubusercontent.com/650571/112637120-1bc5da80-8e3e-11eb-85c0-9e41f0c8c578.png)

**Comment by sleshchenko** [comment]
@sunix did you get error immediately or after some time of waiting?

**Comment by sunix** [comment]
immediately afair
