### ISSUE TITLE
Docker Che launcher doesn't show progress on pull of new che-server image

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#1942]
Docker Che launcher hangs until image is pulled on update. It shows nothing so it seems that it hangs. But in few minutes (depending on network) it shows that image is pulled.
On slow network user might think that it doesn't work.

Che version: 4.6.0-Snapshot
OS and version: Ubuntu 14.04
Docker version: 1.11.2
Che install: Docker container

**Comment by TylerJewell** [comment]
I noticed this last night with a friends image.  Can this be improved?  I am not sure this is a bug.  The system is not hanging, just running slowly with no output.

**Comment by garagatyi** [comment]
I didn't say that this is a bug. It works, just not as verbose as can be.

**Comment by TylerJewell** [comment]
@garagatyi @l0rd - I need some help on this one.  I did a test.  In this shell file, I am able to see all of hte output as expected from docker pull.  However, the same exact syntax in the che-launcher script does not have the same output.  The difference, I suppose is that the che-launcher script is running inside of a container, and the script I ran below was native on the host.  Any ideas?

```
#!/bin/sh
docker pull codenvy/che-server:nightly &
pid=$!
while kill -0 "$pid" >/dev/null 2>&1; do
  sleep 1
done
wait $pid
```

**Comment by garagatyi** [comment]
Can you explain why you need that script? I think that docker pull behaves in the same way, so no need to add sleep and kill -0.

**Comment by l0rd** [comment]
It should work if you add `-t` option (allocate pseudo terminal) when you execute `docker run`

**Comment by TylerJewell** [comment]
@l0rd - that did it.  Adding "-t" to the docker run syntax fixed the issue.  So question is now - is this just a documentation issue for how people should use the product (always pass -t option), or is there a way to programmatically inject this from the launcher?

**Comment by l0rd** [comment]
You can try prefixing with TERM=xterm:

``` bash
TERM=xterm docker pull codenvy/che-server:nightly &
```

**Comment by TylerJewell** [comment]
Tried that - it didn't work.  Kept the same behavior.

**Comment by TylerJewell** [comment]
Added a capability in the Che CLI to override whether the -it parameter is provided.
https://github.com/eclipse/che/pull/2239
