### ISSUE TITLE
Create Exec agent

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#1943]
We need machine agent that is able to expose REST (or/and websocket) API for commands execution.

We considered that it should be written using Golang.
-  it will allow deploy it without external dependencies such as JRE, NodeJs,  etc
-  it is fast and has small memory footprint
-  it has very good model for processing http requests, websockets, execute commands in the OS
-  it is quite easy to port it into different OSes and CPU architectures

**Comment by skabashnyuk** [comment]
@evoevodin 

Current state:
I've developed a prototype of machine-agent which has RESTFul API for managing processes and 
not full set of websocket API for managing processes through websocket channels.

The prototype repository: https://github.com/evoevodin/machine-agent
The [docs](https://github.com/evoevodin/machine-agent/blob/master/docs/rest_api.md) for available REST API.
The [docs](https://github.com/evoevodin/machine-agent/blob/master/docs/ws_api.md) for available Websocket API.
The [docs](https://github.com/evoevodin/machine-agent/blob/master/docs/events.md) for available Events(messages sent to the websocket channel clients).
Things TODO:
- The REST API, is not fully completed it needs a few more methods.
- Websocket API, is not fully completed right now it provides 2 methods for starting and killing proceses.
- Integrate terminal into machine-agent.
- Use configuration flags instead of hardcoded values(e.g. for logs directory)
- Not clear for now, when to clear resources(channels, processes, logs).
- Tests are not there at the moment.

**Comment by JamesDrummond** [comment]
NTS I will add these docs to the codenvy repo docs folder which will get moved to che repo once we are finished with creating codenvy docs jekyll generated doc pages.
