### ISSUE TITLE
Failed to update che-operator on OCP 4.8

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19436]
### Describe the bug
Failed to update che-operator from 7.27.2 to 7.28.0 on OCP 4.8
OCP 4.8.0-0.nightly-2021-03-26-054333

InstallPlan failed:

```
error validating existing CRs against new CRD's schema: checlusters.org.eclipse.che: error validating custom resource against new schema &apiextensions.CustomResourceValidation{OpenAPIV3Schema:(*apiextensions.JSONSchemaProps)(0xc001a85200)}: [].status.openShiftOAuthUserCredentialsSecret: Invalid value: "null": status.openShiftOAuthUserCredentialsSecret in body must be of type string: "null"
```

### Che version
 - [x] 7.28.0

### Steps to reproduce

1. Run ocp 4.8 cluster
2. Run test [script ](https://github.com/eclipse-che/che-operator/blob/master/.ci/cico_updates_openshift.sh)

### Runtime
   - [x] Openshift (include output of `oc version`)

### Environment
   - [x] Cloud

**Comment by ibuziuk** [comment]
@tolusha wanted to put the blocker, or at least P1 prio for this, not sure why it is a P2 ;-)

**Comment by mkuznyetsov** [comment]
@ibuziuk it was discovered during Che operator release 7.28.0, which is not finished yet. My question is, if it is blocker, do I halt the release until it is resolved, or ignore it for now and complete 7.28.0 release (and consider it for bugfix release)?

**Comment by tolusha** [comment]
@ibuziuk 
The reason is the following:
1. It is the first release when we run tests against ocp 4.8, so the bug probably existed before but we never noticed
2. It is nightly OCP build (not a stable version)
3. Tests passed on 4.6 and 4.7

**Comment by flacatus** [comment]
I'm wondering if we should add here(https://github.com/eclipse-che/che-operator/blob/master/pkg/apis/org/v1/che_types.go#L568) to checluster api `omitempty`.

**Comment by ibuziuk** [comment]
> It is nightly OCP build (not a stable version)

@tolusha  will let you decide what the priority is, but IMO it is a red sign that could become a potential blocker
