### ISSUE TITLE
Update Traefik to v2.3.2

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19431]
Che is still using image from dockerHub: docker.io/traefik:v2.2.8 for 'single-host':

* https://github.com/eclipse-che/che-operator/blob/master/deploy/olm-catalog/nightly/eclipse-che-preview-openshift/manifests/che-operator.clusterserviceversion.yaml#L672

Because of that our nightly job 'che-single-host' fails quite often, with annoying error '..too many requests'.

I would like to ask if there is possibility to use the one on quay.io in 'eclipse' organization -> https://quay.io/repository/eclipse/che--traefik?tab=tags  ?

There is a previously closed issue about this too: https://github.com/eclipse/che/issues/18292#issuecomment-726201516

**Comment by nickboldt** [comment]
I've copied traefik 2.3.2 over here https://quay.io/repository/eclipse/che--traefik?tab=tags

**Comment by tolusha** [comment]
Sure we can.
As far as I understand it is the same approach as for PostgerSQL image.

**Comment by nickboldt** [comment]
yes, the process is to run this script https://github.com/eclipse/che-release/blob/master/utils/copyImagesToQuay.sh when you need a new image copied to quay. 

Then someone from che-operator updates the csvs & various other yamls to point to the new image name/tag.
