### ISSUE TITLE
Cloned project is absent in the project tree

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#19444]
### Describe the bug
* I faced out with a problem of absent cloned project in the project tree. The cloned project appears in the tree only after refreshing web page.

### Che version
 - [x] nightly

### Steps to reproduce
1. Create and open a simple workspace
2. Generate Ssh key in the IDE and add to some GitHub repo
3. Try clone the project from GitHub by Ssh link
4. Cloned project doesn't present in the tree
5. After refresh web page the project is appeared

### Expected behavior
The cloned project should appear in the tree immidiately after cloning

### Runtime
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![che-cloned-repo-absent](https://user-images.githubusercontent.com/5408906/112845848-fdfeac80-90ad-11eb-90ec-8f40117340ad.png)

![cloned-projecr-reload-page](https://user-images.githubusercontent.com/5408906/112847914-37d0b280-90b0-11eb-9503-ae5e1f3cd7ad.png)

### Installation method
   - [x] chectl

**Comment by RomanNikitenko** [comment]
should be fixed by https://github.com/eclipse/che/issues/19101

**Comment by azatsarynnyy** [comment]
dup of https://github.com/eclipse/che/issues/19101 which is going to be fixed next sprint

**Comment by artaleks9** [comment]
* The actual issue for tracking now is #19544
