### ISSUE TITLE
Evaluate current list of samples

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#19442]
Before we update our samples to be based on the devfile v2 spec, we should review which ones are candidates for removal or consolidation on common grounds with what is being used by other tooling/communities.

We should look to see which are actively maintained, which are from Red Hat vs community provided and what should be in downstream.

This relates to #19341

**Comment by svor** [comment]
The list of samples which need to be ported is here https://github.com/eclipse/che/issues/19341#issuecomment-947443288
