### ISSUE TITLE
Devfile registry: it is not clear in which order to execute commands in some devfiles

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19458]
### Describe the bug
Some devfiles have several commands that need to be executed in a precise order to succeed.
Some are named with prefixed numbers that help the user, but some others are not.

For instance:
- angular
- python-django

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. start the Django Python devfile
2. open my workspace view
3. start the first command: `install dependencies`
4. it fails ```sh: 1: .: Can't open /projects/.venv/bin/activate```

### Expected behavior
the commands should be prefixed with numbers that would tell which one to start. in this case, user should execute the command `set up venv` first, but it is listed in alphabetical order: at the end.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_301](https://user-images.githubusercontent.com/650571/112963644-df4cf400-9147-11eb-943d-7755a428c29f.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by l0rd** [comment]
The numbers are a workaround but the right solution is to run the prerequisite commands if they haven't been run before.

**Comment by l0rd** [comment]
Also it would be nice to see the list of examples that have this problem in this issue. We could make it an epic. Adding n&n label anyway as that has a important impact on UX, especially for new users.

**Comment by sunix** [comment]
> The numbers are a workaround but the right solution is to run the prerequisite commands if they haven't been run before.

Could this be part of devfile v2?

**Comment by l0rd** [comment]
> Could this be part of devfile v2?

v2 has composite commands. I don't think it will solve the problem though.
