### ISSUE TITLE
Provide rapid workspace starts in a read-only manner as more complete experience loads in background or on a refresh

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#19461]
Investigate whether we could adopt a similar approach to [github1s](https://github.com/conwnet/github1s) to provide a faster initial loading of a workspace with limited capability. Ideally this should work with GitHub, GitLab and Bitbucket

**Comment by sparkoo** [comment]
AFAIK the biggest "time waste" in workspace startup now is waiting for Ingresses/Routes to initialize. I don't know how exactly it works in the cluster, but from my experience, it can take up to a minute from creating an Ingress object, to the endpoint actually available externally. See this demo I did when we were implementing new gateway single-host https://youtu.be/Fhzt8DiBajU. Top left screen is pure single-host without any new Routes.

Nowdays we're aiming into mixed endpoints, where some workspace endpoints will be single-host (subpaths of main route -> no new Routes) and some multi-host (subdomains -> new Route). Issue is, if you have only one new Route, we're waiting for it in the startup.

I see 2 ways how to improve the situation:
 - have essential routes single-host and wait only for those
   - I believe Theia already can do that, so we should be able to get to the editor similar to the video.
 - have routes prepared for the user
   - first start would be slow, but then we could leave the routes there (for some time) for reuse

**Comment by Hadsch** [comment]
@sparkoo: Thanks for sharing this info. 

I think, these performance considerations should be mentioned here https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspace-exposure-strategies/#default-host-workspace-exposure-strategy_che
or here https://www.eclipse.org/che/docs/che-7/end-user-guide/troubleshooting-slow-workspaces/!
