### ISSUE TITLE
Error: Unable to get available storage types

### ISSUE THREAD

**Issue by abrakhim** [eclipse-che/che#19465]
After installation with chectl on docker-desktop or minikube, both run without obvious errors, i get "Error: Unable to get available storage types" in the browser. No errors in container logs. No hits for this error in google. 
I tried setting the StorageType to persistent in the che ConfigMap, but the error also ... errr... persists.

When installing via CRC Operator, all green.
Anyone else getting this?

![grafik](https://user-images.githubusercontent.com/40267667/113008434-52219380-9177-11eb-850a-ecc165558045.png)

**Comment by tolusha** [comment]
duplication https://github.com/eclipse/che/issues/19403
Fixed in 7.29.0

**Comment by garyyang85** [comment]
Encounter this issue on 7.31.2, installed by operator on openshift. But currently only reproduced on Firefox browser. Chrome works good.
