### ISSUE TITLE
Remove or update globalMemoryLimit in devfiles' meta.yaml

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19464]
### Is your task related to a problem? Please describe.

I don't see any reason to have `globalMemoryLimit` attribute in devfile's meta.yaml like this https://github.com/eclipse-che/che-devfile-registry/blob/master/devfiles/dotnet/meta.yaml#L6

### Describe the solution you'd like

If this field isn't used, let's go through all devfiles and remove `globalMemoryLimit` from meta.yaml 

### Describe alternatives you've considered

If it used somewhere need to validate this value for each devfile.

**Comment by benoitf** [comment]
related to https://github.com/devfile/api/issues/361

**Comment by nickboldt** [comment]
Sounds like this is related to the fix we did in https://github.com/redhat-developer/codeready-workspaces/pull/455 to move memory limits from devfiles and into plugins.

**Comment by ericwill** [comment]
+1 to removing it, we have plenty of tools available when it comes to memory limits (plugin definitions, devfiles). I do not think we need a third one.

**Comment by l0rd** [comment]
Today we do not have a mechanism to tell the user that they should NOT try to run a Java stack on a 4GB or less Kubernetes node. That was a first step to try to setup that mechanism.

But as of today we are not using it and we are not maintaining that information. At this stage it's better to remove it.

**Comment by ericwill** [comment]
Fixed by eclipse-che/che-devfile-registry#379
