### ISSUE TITLE
Fix: Error during Che user deactivation when Keycloak cascade user removal is enabled

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#19473]
### Is your task related to a problem? Please describe
During the deactivation GDPR process, some accounts were in an inconsistent state - user existed in che db, but was removed on keylock / sso

### Describe the solution you'd like
Need to figure how this situation could occur

### Describe alternatives you've considered
When a user does not exist in keycloak, but exists in Che db - remove the user only on Che end, without failure:

```
java.io.IOException: Failed access: https://<domain> openshiftapps.com/auth/admin/realms/codeready/users/xxx, method: DELETE, response code: 404, message: {"error":"User not found"}
```

### Release Notes Text

After the deactivation of inactive users, some accounts were in an inconsistent state: user existed in Che postgres database but was removed from Keycloak. That produced an error. This has been fixed now: when a user does not exist in Keycloak, but exists in Che postgres database - remove it without failure.

**Comment by ibuziuk** [comment]
PR for fixup and refactoring - https://github.com/eclipse-che/che-server/pull/26

**Comment by ibuziuk** [comment]
merged. Closing
should be part of 7.32 & CRW 2.10

**Comment by MichalMaler** [comment]
https://issues.redhat.com/browse/CRW-1963
