### ISSUE TITLE
Stabilize the 'devfile' E2E tests on 'Che-nightly' job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#19477]
### Is your task related to a problem? Please describe.
* A quite long time the 'devfile' E2E tests are fail on our 'che-nightly' job.
* The reasons are different, but with to be sure may say about a problem with stop/remove workspace:
```
08:08:18        2) Stop and remowe workspace
08:08:18    [ERROR] CheReporter runner.on.fail: Java Maven test Stopping and deleting the workspace Stop and remowe workspace failed after 6731ms
---
08:37:18        21) Stop and remowe workspace
08:37:18    [ERROR] CheReporter runner.on.fail: Java Spring Boot test Stopping and deleting the workspace Stop and remowe workspace failed after 6984ms
```
 
### Describe the solution you'd like
* It needs to investigate reasons of it and fix up the tests.

### Additional context
![che-devfiles-tests-stop-delete-ws](https://user-images.githubusercontent.com/5408906/113258261-67600480-92d4-11eb-9f7f-53831eb57b09.png)

**Comment by dmytro-ndp** [comment]
Issue looks fixed https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/eclipse-che/899/artifact/eclipse-che/tests/e2e/report/
