### ISSUE TITLE
che - 7.28.0 ErrImagePull error while launching workspace

### ISSUE THREAD

**Issue by andr-azeez** [eclipse-che/che#19470]
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Launch workspace with stacks  - C/C++,NodeJS React Web Application,ASP.NET Core Web Application, etc

### Expected behavior

Launch workspace successfully

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   -  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.15-gke.1501", GitCommit:"de67bb0d58413ba2ba9b64810ab438a9734a2ab9", GitTreeState:"clean", BuildDate:"2021-02-26T23:41:52Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority

   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2021-03-31 15-39-13](https://user-images.githubusercontent.com/81161330/113128292-47c6ce80-9237-11eb-80dd-847ae265a4fd.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * chectl server:deploy --installer=helm --platform=k8s --domain=lab.cl-ide.domain.com --multiuser --installer=operator
     * `chectl version` - chectl/7.28.0 linux-x64 node-v12.21.0
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by tolusha** [comment]
https://quay.io/repository/eclipse/che-cpp-rhel7?tag=latest&tab=tags
There is no 7.28.0 tag
/cc @ericwill @mkuznyetsov

**Comment by andr-azeez** [comment]
Working fine with the version 7.29.2
