### ISSUE TITLE
Enable the multi-root mode for Go devfile

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19476]
### Is your task related to a problem? Please describe.

At the moment the multi-root mode [is disabled](https://github.com/eclipse-che/che-devfile-registry/blob/3274a200943485fe93f3ecf0cd5222337d67f862/devfiles/go/devfile.yaml#L4) for `Go` devfile
It was disabled because there is no code completion: https://github.com/eclipse/che/issues/19375#issuecomment-805824430 

I quickly tested and looks like the code completion works with enabled multi-root mode **and** enabled  `GO111MODULE`.

![multi-root-on](https://user-images.githubusercontent.com/5676062/113196222-e836e600-926b-11eb-8b93-15b2f0b8d108.gif)

Also I don't have errors in the `Problems` view when the multi-root mode is `ON`.
I have a lot of errors when the multi-root mode is `OFF`:

![multi-root-off](https://user-images.githubusercontent.com/5676062/113196159-d9e8ca00-926b-11eb-8c14-7811bb856415.png)

For testing I did the following:
-  replacing the value for `GO111MODULE` by `on` [here](https://github.com/eclipse-che/che-devfile-registry/blob/3274a200943485fe93f3ecf0cd5222337d67f862/devfiles/go/devfile.yaml#L27)
- give `memoryLimit: 2Gi` for `Go` component
- wait for `Loading packages` process - you can see the corresponding loader in the status bar when you open a `go` file after starting a workspace 

### Describe the solution you'd like

My propose is:
- test the base `Go` functionality with enabled  `GO111MODULE`
- if it doesn't help - investigate what should be done to get `Go` functionality working in the multi-root mode for `Che`.

**Comment by ericwill** [comment]
Fixed by eclipse-che/che-devfile-registry#387
