### ISSUE TITLE
Che-plugin-registry image build fails

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#19478]
### Describe the bug

The building of `che-plugin-registry` image fails.
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Go to `che-plugin-registry` folder.
2. Execute `./build.sh`.
3. See an error:
```
Generate artifacts...
✔ Read che-theia-plugins.yaml file
⠋ Download/Unpack/Analyze CheTheiaPlugins in parallel (may take a while)(node:36455) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/tmp/che-plugin-registry/unpack-folder/vscode-camelk-0.0.22-135.vsix/extension/package.json'
(node:36455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36455) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✖ Error analyzing extensions https://download.jboss.org/jbosstools/vscode/stable/vscode-camelk/vscode-camelk-0.0.22-135.vsix,https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-kubernetes-tools/vscode-kubernetes-tools-1.2.1.vsix,https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-yaml/vscode-yaml-0.11.1.vsix,https://download.jboss.org/jbosstools/stable/vscode-commons/vscode-commons-0.0.4-38.vsix from https://github.com/camel-tooling/vscode-camelk
stack=Error: Unable to find package.json file from vsix https://download.jboss.org/jbosstools/vscode/stable/vscode-camelk/vscode-camelk-0.0.22-135.vsix
    at VsixReadInfo.<anonymous> (/home/ivinokur/projects/che-plugin-registry/tools/build/lib/extensions/vsix-read-info.js:34:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ivinokur/projects/che-plugin-registry/tools/build/lib/extensions/vsix-read-info.js:11:58)
Unable to start Error: Unable to find package.json file from vsix https://download.jboss.org/jbosstools/vscode/stable/vscode-camelk/vscode-camelk-0.0.22-135.vsix
    at VsixReadInfo.<anonymous> (/home/ivinokur/projects/che-plugin-registry/tools/build/lib/extensions/vsix-read-info.js:34:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ivinokur/projects/che-plugin-registry/tools/build/lib/extensions/vsix-read-info.js:11:58)
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by benoitf** [comment]
@vinokurig what's your node version ? 12 ?

it looks like an environment issue

**Comment by sunix** [comment]
@vinokurig could you reproduce it with the devfile ?

**Comment by benoitf** [comment]
I just ran the build and it was successful so removing blocker

**Comment by vinokurig** [comment]
Cleaning the `/tmp/che-plugin-registry` directory solved the problem
