### ISSUE TITLE
Most stacks are broken on Che 7.28 due to missing 7.28.0 tag of images on quay.io

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19486]
### Describe the bug

```
Pulling image "quay.io/eclipse/che-java11-maven:7.28.0"

Failed to pull image "quay.io/eclipse/che-java11-maven:7.28.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/eclipse/che-java11-maven:7.28.0 not found: manifest unknown: manifest unknown

ErrImagePull

Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a"

Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "quay.io/eclipse/che-java11-maven:7.28.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/eclipse/che-java11-maven:7.28.0 not found: manifest unknown: manifest unknown', 'workspaceqisa44i745dswjt8.maven-59975cd798-tzm5k'"
```

tag 7.28.0 is missing https://quay.io/repository/eclipse/che-java11-maven?tag=7.28.0&tab=tags

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify 7.28.0

### Steps to reproduce

1. Start Java Maven workspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by apupier** [comment]
same for Java Vert.x but with quay.io/eclipse/che-java8-maven:7.28.0

**Comment by apupier** [comment]
same for Quarkus but with image quay.io/eclipse/che-quarkus:7.28.0

looks alike all 7.28.0 tags are missing

**Comment by ericwill** [comment]
Looks like the base images never got pushed: https://github.com/eclipse-che/che-devfile-registry/runs/2200751523?check_suite_focus=true

**Comment by ericwill** [comment]
For the `Build and push patched base images and happy path image` step I see this warning message:

`No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load`

**Comment by ericwill** [comment]
cc @mkuznyetsov @nickboldt

**Comment by nickboldt** [comment]
Curious... on Mar 25:
![image](https://user-images.githubusercontent.com/227597/113339878-23332b00-92f9-11eb-9403-d8120cae1afd.png)

And this morning:
![image](https://user-images.githubusercontent.com/227597/113339938-3940eb80-92f9-11eb-8042-d6e423147edd.png)

**Comment by ericwill** [comment]
cc @bivasda1

**Comment by nickboldt** [comment]
Seems like the problem here is that we're using `docker buildx build --platform "$PLATFORMS"` which...
* is unstable on s390x
* may attempt to build based on base images for which there is no arch available (eg.,

**Comment by nickboldt** [comment]
This might be useful in future...

```
curl -sSLo- https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/master/arbitrary-users-patch/base_images | sed -r -e "s#che-.+ +##g" > /tmp/base-images.txt

for d in $(cat /tmp/base-images.txt); do if [[ $d != *"/"* ]]; then d=docker.io/$d; fi; echo; echo $d; skopeo inspect docker://${d} --raw | jq -r .manifests[].platform.architecture 2>&1 | tr "\n" " "; rm -f /tmp/out.txt; echo; done

rm -f  /tmp/base-images.txt

```

Output today:
```
docker.io/antora/antora:2.3.3
jq: error (at <stdin>:45): Cannot iterate over null (null) 

registry.access.redhat.com/devtools/llvm-toolset-rhel7
amd64 ppc64le s390x 

mcr.microsoft.com/dotnet/core/sdk:2.2-stretch
jq: error (at <stdin>:45): Cannot iterate over null (null) 

mcr.microsoft.com/dotnet/core/sdk:3.1.301-buster
jq: error (at <stdin>:45): Cannot iterate over null (null) 

docker.io/golang:1.12-stretch
amd64 arm arm64 386 ppc64le s390x 

docker.io/golang:1.14-stretch
amd64 arm arm64 386 

docker.io/gradle:6.6.1-jdk11
amd64 arm arm64 ppc64le s390x 

docker.io/maven:3.6.3-jdk-11
amd64 arm64 

docker.io/maven:3.6.1-jdk-8
amd64 

docker.io/node:10.16
amd64 arm arm64 ppc64le s390x 

docker.io/node:12.18
amd64 arm arm64 

registry.access.redhat.com/ubi8/nodejs-10
amd64 arm64 ppc64le s390x 

registry.centos.org/che-stacks/centos-nodejs
jq: error (at <stdin>:40): Cannot iterate over null (null) 

quay.io/eclipse/che-php-base:7.4
jq: error (at <stdin>:90): Cannot iterate over null (null) 

centos/python-36-centos7:1
jq: error (at <stdin>:55): Cannot iterate over null (null) 

docker.io/python:3.8.6-slim
amd64 arm arm arm64 386 mips64le ppc64le s390x 

quay.io/quarkus/centos-quarkus-maven:21.0-java11
jq: error (at <stdin>:20): Cannot iterate over null (null) 

docker.io/rust:1.39.0-slim
amd64 arm arm64 386 
```

**Comment by nickboldt** [comment]
Followup work to validate required containers and tags exist: https://github.com/eclipse/che/issues/19490

**Comment by nickboldt** [comment]
attempt to rebuild che devfile registry 7.28.1 has failed due to lack of disk space.

https://github.com/eclipse-che/che-devfile-registry/runs/2249263764?check_suite_focus=true

perhaps we have to do fewer things in parallel, or else do some better `docker rmi` cleanup once we're doing pushing stuff to quay?

**Comment by nickboldt** [comment]
Tried again and got (again):

`2021-04-01T21:30:59.2145076Z ##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 0 MB
`

**Comment by nickboldt** [comment]
Immediate problem is solved for now. Followup work in https://github.com/eclipse/che/issues/19490
