### ISSUE TITLE
In hosted-instance-log: "TypeError: Cannot read property 'path' of undefined" from vscode-builtin-json-language-feature

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19485]
### Describe the bug
stack error in hosted-instance-log when staring a workspace:

```
Extension-Host:Promise rejection not handled in one second: TypeError: Cannot read property 'path' of undefined , reason: TypeError: Cannot read property 'path' of undefined
Extension-Host:With stack trace: TypeError: Cannot read property 'path' of undefined
    at Object.a [as joinPath] (/default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:248754)
    at /default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:116514
    at Array.forEach (<anonymous>)
    at /default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:116371
    at Array.forEach (<anonymous>)
    at f (/default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:116229)
    at /default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:122454
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify 7.28.0

### Steps to reproduce

1. Start Camel K stack
2. look inside the hosted-instance-log output

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by apupier** [comment]
it happens on several workspaces. tested with Camel K and Java Maven

**Comment by kibblerz** [comment]
I'm also experiencing this issue.

Array.isArray(r) && r.forEach(n => { let { fileMatch: r, url: o } = n; if ("string" == typeof r && (r = [r]), Array.isArray(r) && "string" == typeof o) { let n = o; "." === n[0] && "/" === n[1] && (n = a.joinPath(e.extensionUri, n).toString()), r = r.map(e => ("%" === e[0] ? e = (e = (e = e.replace(/%APP_SETTINGS_HOME%/, "/User")).replace(/%MACHINE_SETTINGS_HOME%/, "/Machine")).replace(/%APP_WORKSPACES_HOME%/, "/Workspaces")

This seems to be the piece of code the error is occurring at, for some reason the extensions aren't getting valid Uri's?

**Comment by tsmaeder** [comment]
On obvious problem is that in Theia, the URI class does not declare a `joinPath` method.

**Comment by bfitzpat** [comment]
I encountered this on a sandbox CRW instance with this devfile from @sunix

**Comment by apupier** [comment]
> On obvious problem is that in Theia, the URI class does not declare a `joinPath` method.

see https://github.com/eclipse-theia/theia/issues/8752

**Comment by tsmaeder** [comment]
Bit of a 🤦‍♂️ moment here: while i have a fix for the upstream problem https://github.com/eclipse-theia/theia/issues/8752, it turns out that I was looking at the wrong version of the json extension: 1.49.3 vs. 1.50.1. In 1.50.1, the extension implements a 'joinPath' function, which accesses the `Extension.extensionUri` field, which is not implemented in Theia.

**Comment by tsmaeder** [comment]
I implemented the `extensionURI` stuff. However, when I open a `package.json` in the editor, I get an error message complaining it can't load the schema from a uri like 'combinedschema://schemaservice/chepluginresource:/...`. 
It seems the json language service living at https://github.com/microsoft/vscode-json-languageservice gets it's knickers in a twist on some non-standard URI's, see for example https://github.com/microsoft/vscode/issues/115419. Note that the issue has been closed very recently, so this might be fixed in a new version of the plugin than what we have.

**Comment by apupier** [comment]
still occuring with CRW 2.10 (so Che 7.32.2)

```
Extension-Host:Promise rejection not handled in one second: TypeError: Cannot read property 'path' of undefined , reason: TypeError: Cannot read property 'path' of undefined
Extension-Host:With stack trace: TypeError: Cannot read property 'path' of undefined
    at Object.a [as joinPath] (/default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:248754)
    at /default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:116514
    at Array.forEach (<anonymous>)
    at /default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:116371
    at Array.forEach (<anonymous>)
    at f (/default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:116229)
    at /default-theia-plugins/vscode-builtin-json-language-features/extension/client/dist/node/jsonClientMain.js:1:122454
 ```
