### ISSUE TITLE
upgrade tekton-cli and octant in tekton sidecar

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#19498]
upgrade respectively in tekton's sidecar:
tekton-cli v0.17.1
octant v0.18.0

TODO: after this, upgrade vsix from https://github.com/redhat-developer/vscode-tekton/releases/download/v0.13.0/tekton-pipelines-0.13.0-49.vsix from 0.2.0 to 0.13.0

**Comment by ericwill** [comment]
Is this something you plan to work on? @gattytto

**Comment by gattytto** [comment]
yes, I tried but first we need [this](https://github.com/eclipse/che/issues/19488) merged to use the new kube tools sidecar image in tekton.
