### ISSUE TITLE
Che-plugin-registry don't take into account CHE_SIDECAR_CONTAINERS_REGISTRY_URL 

### ISSUE THREAD

**Issue by NM4** [eclipse-che/che#19492]
### Che version

 - [ x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Build plugin registry with offline option
deploy Eclipse Che with helm and che-plugin-registry.cheDevfileImagesOverride.url pointing to intenal Docker proxy registry

### Runtime
   - [ x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs

In the logs we can see that at workspace startup, Che try to pull images indicated in plugin registry from quay.io

**Comment by sunix** [comment]
Hi there,
https://github.com/eclipse-che/che-plugin-registry/pull/937 has been merged.
I am closing this issue,
Thanks
