### ISSUE TITLE
Upgrade VS Code xml from 0.14 to 0.16

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19494]
### Is your enhancement related to a problem? Please describe.

https://marketplace.visualstudio.com/items/redhat.vscode-xml/changelog

https://github.com/eclipse-che/che-plugin-registry/blob/13ab2ea940452ef1f07b7145702d9dc081709885/che-theia-plugins.yaml#L462

nota the revision is incorrect, still at 0.13: 
https://github.com/eclipse-che/che-plugin-registry/blob/13ab2ea940452ef1f07b7145702d9dc081709885/che-theia-plugins.yaml#L452

**Comment by fbricon** [comment]
0.16.0 is out 0.16.1 should follow very very soon ;-)
