### ISSUE TITLE
Upgrade VS Code yaml from 0.14.0 to 0.18.0

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19493]
### Is your enhancement related to a problem? Please describe.

it contains several bugfixes and enahncements https://marketplace.visualstudio.com/items/redhat.vscode-yaml/changelog
https://github.com/eclipse-che/che-plugin-registry/blob/13ab2ea940452ef1f07b7145702d9dc081709885/che-theia-plugins.yaml#L336

nota: a lot of other extensions relies on even older versions. For instance OpenShift connector https://github.com/eclipse-che/che-plugin-registry/blob/13ab2ea940452ef1f07b7145702d9dc081709885/che-theia-plugins.yaml#L331

**Comment by ericwill** [comment]
We need the VS Code version to be 1.52 first, as vscode-yaml depends on that: https://github.com/redhat-developer/vscode-yaml/issues/471

Theia issue: https://github.com/eclipse-theia/theia/issues/9193

**Comment by apupier** [comment]
VS Code API 1.52 seems now available as eclipse-theia/theia#9193 is closed
latest VS COde yaml is now 1.2.2 and still declares vs code 1.52 as minimal version required https://github.com/redhat-developer/vscode-yaml/blob/ca93afaf6867731d349e2cfef954da9f9e01786d/package.json#L27
