### ISSUE TITLE
Stop of Che container in new Che launcher is broken

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#1949]
New Che launcher stop Che and suppresses error output. Then container is removed with **docker rm -f**.
Because of that Che doesn't store created workspaces and other information into data storage folder.

**Reproduction Steps:**
1. Start Che in a container
2. Create workspace
3. Stop Che with Che launcher
4. Restart Che 

**Expected behavior:**

Created workspace exists

**Observed behavior:**

There is no workspaces in Che

Che version: 4.6.0-Snapshot
OS and version: Ubuntu 14.04
Docker version: 1.11.2
Che install: Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by jcpowermac** [comment]
@TylerJewell this is exactly the problem I experienced.  Once there is a PR I will be willing to test it out.

**Comment by TylerJewell** [comment]
@jcpowermac - in diagnostics, it seems to be error in the way that che-launcher executes a stop.  I experienced it yesterday on MacOS.

**Comment by bmicklea** [comment]
For @l0rd to fix.
