### ISSUE TITLE
Close Preview on reloading Workspace

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#19508]
## Summary
On reloading/reopening a Running Workspace, can we close the Preview which was kept open during the previous run?

## Relevant information

I have a sample app running within my eclipse che workspace. It looks like this.
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/17478559/113703031-ecde1d00-96f7-11eb-9744-7b5149ee7454.png">

 Now I just logoff and relogin and open the same running workspace.  I get this screen now

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/17478559/113703149-0ed79f80-96f8-11eb-9eff-284638a00516.png">

So as you see in the second screen shot 
1) the earlier preview which had the sample app running, is still showing but does not load. 
2) The terminal where i ran the sample app is still running. but the url is not accessible  

Is there a way to do a slight cleanup of the workspace before reloading? 
1) Stop all running processes in any of the terminals and possibly close the terminals
2) close out the preview  if i relaunch the workspace which was already running. ? 

If I kill the running process and start it again, the sample app loads fine. 

Eclipse Che Version: 7.27.1
Environment :  Docker Desktop.

**Comment by RomanNikitenko** [comment]
> Is there a way to do a slight cleanup of the workspace before reloading?
> 
> 1. Stop all running processes in any of the terminals and possibly close the terminals
> 2. close out the preview  if i relaunch the workspace which was already running. ?
> 

Hello!
I guess you have an extension and looking the way how to implement the functionality on the extension side.
So, about:
> Stop all running processes in any of the terminals

You could try to [send](https://github.com/eclipse-che/che-theia/blob/b4e69f7a96af709d19b68d7521e304d2f4bda6f6/extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L342) `\x03` to a terminal. We use such way to stop a task [here](https://github.com/eclipse-che/che-theia/blob/b4e69f7a96af709d19b68d7521e304d2f4bda6f6/plugins/task-plugin/src/task/che-task-runner.ts#L96), for example.
This [method](https://github.com/eclipse-che/che-theia/blob/b4e69f7a96af709d19b68d7521e304d2f4bda6f6/extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L262) can be used to get terminal widgets.

> and possibly close the terminals

I think it should be possible to close all terminals from an extension side like:
```
@inject(TerminalService)
protected readonly terminalService: TerminalService;

this.terminalService.all.forEach(terminal => terminal.close());
``` 

> close out the preview

```
@inject(ApplicationShell)
protected readonly shell: ApplicationShell;
  
this.shell.collapsePanel('right');
```

**Comment by bodarajeshkumar** [comment]
@RomanNikitenko Yes, we are using an extension and trying to close all the open terminals and preview windows before doing actual operations of the extension. In the example code mentioned, You are using injecting TerminalService class and ApplicationShell class. Where are these classes available?

I am trying below code to close the terminals. does this looks good.?
###
 vscode.window.terminals.forEach(terminal => terminal.dispose());
###

**Comment by RomanNikitenko** [comment]
Well, let's check that we're on the same page :-)
> Yes, we are using an extension 

Do you mean VS Code extension or `che-theia` extension?
Che-theia has [extensions](https://github.com/eclipse-che/che-theia/tree/master/extensions) and [plugins](https://github.com/eclipse-che/che-theia/tree/master/plugins) as well.
My examples above were provided for a `che-theia` extension.

Your example:
> vscode.window.terminals.forEach(terminal => terminal.dispose());

is actual for VS Code extension

**Comment by bodarajeshkumar** [comment]
Thanks @RomanNikitenko. yes we are using vscode extension :). Now trying with Che-theia extension.

**Comment by pgirishibm** [comment]
@RomanNikitenko Is there a way to close the preview instead of just collapsing it.  The extension that we built (vs code and che-theia)  using the pointers you mentioned above, does collapse the preview on startup,  But when we open another url and the preview exapands,  the , 'Bad Gateway' error shows up first. After the preview is reloaded the url loads. 

So instead of collapse, if we can close out the preview, then we would need to reopen (recreate) the preview which  does not show the 'Bad Gateway' error ..

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko Is there a way to close the preview instead of just collapsing it. 

Hello!

> Can that action be called from within the che-theia plugin?

Unfortunately, I don't know a way, how you could do it from a `plugin` side.
You could explore `theia.d.ts` file or ask https://github.com/eclipse-theia/theia/discussions as there is nothing `che` specific.

I tried something like:

```
commandRegistry.registerCommand(CommonCommands.CLOSE_PREVIEW, {
            isEnabled: (event?: Event) => {
                return true;
            },
            execute: (event?: Event) => {
                const tabBar = this.shell.getTabBarFor('right');
                if (!tabBar) {
                    return;
                }

                const preview = tabBar.titles.find(title => title.label === 'Preview');
                if (preview) {
                    preview.owner.close();
                }
                
            }
        });
```
It worked for me:

![close_preview](https://user-images.githubusercontent.com/5676062/119319661-65d30d00-bc83-11eb-9117-96b511391cbc.gif)

That example can be used on an `extension` side (not che-theia `plugin` side).

**Comment by RomanNikitenko** [comment]
btw: 
using the approach above you could:
- register the `Close Preview` command on an extension side
- use  `theia.commands.executeCommand('close-preview-command-ID');` from a plugin side
