### ISSUE TITLE
Code Coverage report problems

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19505]
### Describe the bug

I detected few problems related to Code Coverage report for `che-theia` PRs:
- sometimes there is no report for a PR ([here](https://github.com/eclipse-che/che-theia/pull/1066) and [here](https://github.com/eclipse-che/che-theia/pull/1063), for example)
- the `Impacted Files` section looks strange for me - for example my PR contains changes on `workspace-plugin` side, but the section displays some files from `task-plugin` - I have no idea, how it can be related to my changes. 
- the report is not regenerated if I push additional changes to a PR ([here](https://github.com/eclipse-che/che-theia/pull/1064), for example)      

### Steps to reproduce
I detected the problems on PRs for `che-theia`. Some references you can find above in the description.

**Comment by nickboldt** [comment]
Not sure but I think code coverage is owned by QE team.
