### ISSUE TITLE
Support CertManager in che operator for devworkspace controller deployment

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#19502]
### Is your task related to a problem? Please describe.

In order to delegate all devworkspace controller deployment to che operator we should support CertManager API in che operator

Right now che-operator client-go it is pinned to 0.16.2 version and in order to use CertManager/v1 APIs to create ISSUER and Certificate Objects for DevWorkspace Controller deployment we should pin to a higher client-go version(v0.19.0 or higher). 

CertManager dependencies: https://github.com/jetstack/cert-manager/blob/v1.0.0/go.mod#L55.
DWO Certificate object: https://github.com/devfile/devworkspace-operator/blob/main/deploy/deployment/kubernetes/objects/devworkspace-controller-serving-cert.Certificate.yaml#L1

I think this issue depends on: https://github.com/eclipse/che/issues/19466

**Comment by tolusha** [comment]
We decided to close the issue and let cert-manager to be a prerequisite instead of deploying it via che-operator
