### ISSUE TITLE
Dashboard do not show OAuth login page on Gitlab OAuth2 "authentication needed" response.

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#19512]
### Describe the bug
When resolving the Gitlab factory by unauthenticated user, the response is returned (very similar to Bitbucket flow):

```
{
  "attributes": {
    "oauth_provider": "gitlab",
    "oauth_authentication_url": "https://che-eclipse-che.apps.cluster-max-fbfa.max-fbfa.example.opentlc.com/api/oauth/authenticate?oauth_provider=gitlab&request_method=POST&signature_method=rsa",
    "oauth_version": "2.0"
  },
  "errorCode": 401,
  "message": "SCM Authentication required"
}
```

It is expected to OAuth login page to be shown, but it is error message instead.

### Che version
7.29.0

### Expected behavior
It is expected to OAuth login page to be shown, but it is error message instead.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/1651062/113822881-a84d9280-9786-11eb-8aff-78930ad025f7.png)

![image](https://user-images.githubusercontent.com/1651062/113761271-efed0380-971f-11eb-9de5-7d02d380a0e0.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by akurinnoy** [comment]
The UD works properly and provides the correct redirection URL.
