### ISSUE TITLE
Create automated test for the GitHub PR plugin

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19513]
### Is your task related to a problem? Please describe.
Currently we have no automated testing of the GitHub PR plugin. 

### Describe the solution you'd like
We should create some sort of automated test to put the plugin through some steps that test functionality.

### Describe alternatives you've considered
N/A

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/19863
