### ISSUE TITLE
Require docker images for ARM64

### ISSUE THREAD

**Issue by odidev** [eclipse-che/che#19525]
I am trying to use che-dev image over ARM64v8 but it seems it does not have an arm64 supported tag in [docker hub](https://hub.docker.com/r/eclipse/che-dev/tags?page=1&ordering=last_updated)

I have tried [building it](https://github.com/eclipse/che/blob/master/dockerfiles/dev/Dockerfile) locally but it is failing with “exec format error”. The base image of the package “registry.centos.org/che-stacks/centos-stack-base” is not available for the ARM64 platform. I have explored its source to build the image but unable to find it.

Do you have any plans for releasing an ARM64 image?

May I know how the amd64 image is getting published on Docker hub?

I am happy to help in providing the ARM64 support in oryx docker image, but first we require the ARM64 tag of the base image (registry.centos.org/che-stacks/centos-stack-base) or link to the source to build it..

Please provide suggestions on the same.

**Comment by benoitf** [comment]
Hello @odidev 

che-dev is not multiarch but che-server image is 
https://github.com/eclipse/che/tree/master/dockerfiles/che

che-dev could be turned into multiarch as well.
but probably you could remove centos and use any other multi-arch image (like using `FROM adoptopenjdk/openjdk11:jre-11.0.8_10` as in che-server image)

**Comment by odidev** [comment]
@benoitf Thanks for your suggestion. I was able to build the [docker image](https://hub.docker.com/layers/odidev/che-dev/latest/images/sha256-3d5e04237506529f81cd90de9f879cb139fa02731d73f4ceab0f10bfd821a3db?context=repo) for che-dev for arm64 by using **adoptopenjdk/openjdk11:aarch64-centos-jre-11.0.10_9** as base image and adding these [changes](https://github.com/odidev/che/commit/5113aea4e274deaa4b8aee3796a396a6d4755e5f). I have built it using **“docker build .”** command on both platforms.

I am getting the same response on both platforms ([amd64 ](https://hub.docker.com/layers/eclipse/che-dev/latest/images/sha256-cd42f781440c8a9d8899ee5a87d571928298c3655eadbaa2dc7f930be472f2b8?context=explore) and [arm64](https://hub.docker.com/layers/odidev/che-dev/latest/images/sha256-3d5e04237506529f81cd90de9f879cb139fa02731d73f4ceab0f10bfd821a3db?context=repo)) while I was testing the image by using “docker run -it --rm <image name>” command.
 
ARM64 Image: https://hub.docker.com/layers/odidev/che-dev/latest/images/sha256-3d5e04237506529f81cd90de9f879cb139fa02731d73f4ceab0f10bfd821a3db?context=repo

Changes required: https://github.com/odidev/che/commit/5113aea4e274deaa4b8aee3796a396a6d4755e5f

Please let me know if I can raise a PR with these [changes](https://github.com/odidev/che/commit/5113aea4e274deaa4b8aee3796a396a6d4755e5f).
