### ISSUE TITLE
Find text skips .php files

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#1952]
**Reproduction Steps:**
1. Create a php sample app
   2.Ctrl+Shift+F
2. Type hello

**Expected behavior:**

Text occurrence is found in index.php

**Observed behavior:**

No matches found

**Comment by JamesDrummond** [comment]
@vparfonov Please assign to someone and provide status label.

**Comment by thpglobal** [comment]
Any action on getting this bug fixed? I don't see anyone assigned - I notice that the current release on codenvy (4.7.0) is able to find a first instance but none beyond the first.

**Comment by thpglobal** [comment]
Any action on this? I don't see any milestone linked to it. I was under the impression this would be a key feature of codenvy 4, and I really could use it.

**Comment by TylerJewell** [comment]
John - we document our roadmap and our upcoming milestones according to the process outlined in the wiki here. The roadmap is documented, and teams indicate the issues they will be taking in the current sprint and the next upcoming sprint.  The roadmap is mapped out 6-9 months thematically and then milestones are mapped out for the current sprint and next sprint. When an issue is taken into a sprint the labels are updated and then it will be trackable.

https://github.com/eclipse/che/wiki

the team/ide is responsible for this area of the product, and they manage a backlog of about 100 issues at any given point in time. Their key priorities have been around adding support for language server protocol, including the PHP epic, performance tuning the IDE, and a variety of bug fixes related to mavne / java capabilities. In Q4, this team will be emphasizing support for a new type of simplified command structure that will make the product easier to use.

**Comment by thpglobal** [comment]
@vparfonov - Hello Vitalli - any sense when this bug will get into the schedule? Having to manually track down every reference to every function is really a pain. Since a recursive find seems to work on other text files, it's not clear to me why it is difficult to enable it on .php files as well.
