### ISSUE TITLE
Should run che-theia tests against Theia master on PRs

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19523]
### Is your enhancement related to a problem? Please describe.
We're currently not running the tests in che-theia against master in our PR checks: in the "node build" we run them against whatever version of theia:next was current when the `yarn.lock` file in che-theia was last updated. When we build the che-theia related images, we skip the tests. So we can get into states where the self-hosting process is broken (aka the tests don't run) without noticing.

### Describe the solution you'd like
Ideally, the real build (aka the one we'll use to build and publish images) should include running the tests. A quick fix would be to delete 'yarn.lock' in the "node build" PR check: that way the node build would at least always run against the latest published theia:next version.

### Describe alternatives you've considered
We could stop checking in yarn.lock altogether: The only place it's use when building production che artifacts is when invoking `foreach_yarn` to build the che plugins. And that is likely wrong, since the plugins should run in the theia app we just built against master, not one built against the version that was current when `yarn.lock` was last updated.

**Comment by benoitf** [comment]
it looks like the same issue than https://github.com/eclipse/che/issues/19066

**Comment by tsmaeder** [comment]
Not really: this one asks for the tests to be run, ideally against theia master. The "quick fix" could be the same, but this issue goes further.
