### ISSUE TITLE
Invalid plugin registry URL

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19522]
### Describe the bug
The list of plugins is empty in che-theia editor. The error from notification window is: `Invalid plugin registry URL: "https://plugin-registry-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/v3/plugins/" is detected`

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] 7.28.1

### Steps to reproduce

1. Create Java Maven workpsace
2. Go to View -> PLugins

### Expected behavior
List of plugins should be displayed

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] che dogfooding instance

### Screenshots
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 04 07-15_09_04](https://user-images.githubusercontent.com/1271546/113864171-3e97ad80-97b3-11eb-88ca-7258c5c9477d.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs
From the browser console:
`root INFO Unable to read plugin registry https://plugin-registry-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/v3/plugins/`

From theia-ide container:
`2021-04-07 12:15:43.829 root INFO Cannot access the registry Params: Error: EISDIR: illegal operation on a directory, read
2021-04-07 12:15:44.016 root INFO Unable to read plugin registry Params: https://plugin-registry-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/v3/plugins/`

**Comment by svor** [comment]
cc @sunix

**Comment by vinokurig** [comment]
Is fixed by https://github.com/eclipse-che/che-theia/pull/1073
