### ISSUE TITLE
Create tests to run Eclipse Che in OCP Disconnected Environment

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#19534]
### Is your task related to a problem? Please describe.

Right now in Eclipse Che deployment we are running only tests which install Eclipse Che behind proxy. Will be nice to have some cron job to deploy Eclipse Che every night in OCP disconnected environment.
### Describe the solution you'd like

1. Use flexy job in Jenkins to deploy OCP disconnected env
2. Create a script to copy only Eclipse Che images to the cluster
3. Run some basic tests like:
     3.1 Deploy Che nightly
     3.2 Check if Che was deployed successfully
     3.3 Create workspace
     3.4 Check if Workspace was created successfully
     3.5 Send to mattermos/slack report about test results

**Comment by tolusha** [comment]
depends on https://github.com/eclipse/che/issues/19492
