### ISSUE TITLE
 [che-operator] Do not allow to upgrade che 7.31 or later to upgrade installation that configured with namespace strategies other than "per user" 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19537]
### Is your task related to a problem? Please describe.
With this task https://github.com/eclipse/che/issues/19536 in 7.31  all support of namespace strategies other than "per user"  would be removed. It would be reasonable to block any che 7.31 or later to upgrade installation that configured with namespace strategies other than "per user" .

### Describe the solution you'd like
Do not allow to upgrade che 7.31 or later to upgrade installation that configured with namespace strategies other than "per user" 

### Describe alternatives you've considered
n/a
### Additional context

https://github.com/eclipse/che/issues/19365
https://github.com/eclipse/che/issues/19536

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1871
