### ISSUE TITLE
Handling the new SameSite setting in Chrome in Eclipse Che

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#19547]
## Summary
The new SameSite setting in Chrome in breaking the eclipse che setup if using a multi domain setup. We are getting a keycloak connectivity error when it is called into from a different domain. This is seen only in Chrome. 

## Relevant information

The Chrome Samesite setting is handled in Keycloak 8.0.2.  But I see the version used in latest eclipse che keycloak image  is 6.0.1 .  Do we have a workaround for this Chrome setting in the existing keycloak setup in eclipse che? 

Our setup works fine in firefox. Also with the following manual change in chrome it works well. 
Go to chrome://flags/
Search for “Samesite”
Disable “SameSite by default cookies” flag.
Relaunch.

But is there a way to handle this on the server side in the existing eclipse che setup?  I am using version 7.20.1, But I suppose the same issue would be seen on the latest version as well since the keycloak has not been upgraded?

**Comment by pgirishibm** [comment]
I see this PR that was added as a patch.  https://github.com/eclipse/che-jwtproxy/pull/23/files.  I tried the patch but i still see the error during workspace launch. 

any thoughts on how this can be handled within eclipse che

**Comment by skabashnyuk** [comment]
Steps to reproduce are missing. what is not working?

**Comment by pgirishibm** [comment]
@skabashnyuk Our setup is like this
1) A UI component is deployed on domain abc.com
2) Eclipse che is deployed on domain xyz.com
3) The UI calls into eclipse che to launch a workspace. and since its a cross domain call the Chrome setting SameSite which is now enabled by default blocks these calls. 

We see the latest  keycloak version is handling the SameSite setting, and I see  we are still working on upgrading keycloak. But in older versions is there a way to disable the SameSite setting to allow cross domain calls?

**Comment by skabashnyuk** [comment]
Can you provide a concrete request(sequence of requests) that is failing?

**Comment by pgirishibm** [comment]
@skabashnyuk We implemented a workaround on our cluster to get over the issue. So currently i do not have the environment to recreate the issue and provide the requests causing the issue mentioned here.  I will try to see if i can setup the environment once again and provide the information.

But basically you have 2 different domains available. example.com and sample.com.    Now I have my custom che-dashboard deployed on example.com and the che-server on sample.com.    In this situation, if the dashboard makes a call to keycloak to authenticate we get a cross domain error saying samesite setting prohibits the call in Chrome.

**Comment by skabashnyuk** [comment]
>But basically you have 2 different domains available. example.com and sample.com. Now I have my custom che-dashboard deployed on example.com and the che-server on sample.com. In this situation, if the dashboard makes a call to keycloak to authenticate we get a cross domain error saying samesite setting prohibits the call in Chrome.


I believe that is made on purpose in Che domain of keycloak. Have you tried to replace the original dashboard with your variant, so they are running in the same domain?

**Comment by pgirishibm** [comment]
@skabashnyuk Yes. it works when both are in the same domain. 

I did see the latest version of keycloak has the required configuration to handle the SameSite cookie. and  I do see there is issue opened for upgrading keycloak in che.
