### ISSUE TITLE
Use new format, closer to devfile v2, to specify Che Theia plugins in addition to meta.yaml files

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19545]
### Is your task related to a problem? Please describe.
For editors and plugins, we do generate now devfile.yaml in addition to meta.yaml files
the devfile.yaml are with v2 format.

We should also generate che-theia-plugin.yaml file for every plug-in as meta.yaml is not suitable to provide all information (for example preferences can't be there, etc)

### Describe the solution you'd like
Generate new fragment file and reference them in index.json as alternate files.

### Additional context
https://github.com/eclipse/che/issues/18668

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1868
