### ISSUE TITLE
Multiroot workspace: project must appear in the project explorer when it was cloned by a command in terminal

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#19544]
### Describe the bug

In the multiroot workspace projects only appear if they are described in the devfile.
If we create a simple workspace w/o projects and then open a terminal and clone any project by hands, this project will not be opened in the Exporer view.
The same we have when trying to clone a project by `Git: clone` command.

Workspace plugin handles adding of the project to the devfile when cloning them by hands.
It's a good candidate to handle file system changes and register newly cloned projects in `/projects/che.theia-workspace`

### Che version

 - [x] nightly

### Steps to reproduce

- Create workspace w/o projects
- Open terminal, clone any project with `git clone ...`
- Try to clone another project with `Git: clone` command from command palette.

- Check the file system. Open a terminal and run `ls /projects`

### Screenshots

![Screenshot from 2021-04-08 18-42-58](https://user-images.githubusercontent.com/1655894/114057439-3a46bf80-989b-11eb-9199-12b11fd60847.png)

**Comment by RomanNikitenko** [comment]
duplicates https://github.com/eclipse/che/issues/19101

**Comment by azatsarynnyy** [comment]
I'm transferring the labels from the original issue https://github.com/eclipse/che/issues/19101#issuecomment-812678349

> Setting label `new&noteworthy` and milestone `DevWorkspace Integration STEP 2` as it blocks #19489

fyi @l0rd
