### ISSUE TITLE
Add the "OWNERS" file to the "che-plugin-registry" repository.

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#19556]
### Is your task related to a problem? Please describe.

The "OWNERS" file in the target repo is a requirement of the openshift.ci

![Screenshot from 2021-04-09 16-44-41](https://user-images.githubusercontent.com/22724619/114189977-79384c00-9953-11eb-8f7e-2f87811c4dec.png)

### Describe the solution you'd like

Create such file.
Guideline: https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md

**Comment by tsmaeder** [comment]
> OWNERS files are used to designate responsibility over different parts of the Kubernetes codebase. 

Last time I checked, we're not part of the kubernetes codebase. This sounds like we should not be running on that CI.

**Comment by Ohrimenko1988** [comment]
I am trying to unboard the "che-plugin-registry" repo to the openshift CI.
For this all automation checks should pass.
And only two left:
![Screenshot from 2021-04-09 16-44-41](https://user-images.githubusercontent.com/22724619/114190573-1c896100-9954-11eb-9e12-71e84934da74.png)

I guess the Kubernetes metioned here because openshift CI uses "Prow" (https://github.com/kubernetes/test-infra/blob/master/prow/README.md)

**Comment by Ohrimenko1988** [comment]
This error message has a good explanation:
![Screenshot from 2021-04-09 17-05-29](https://user-images.githubusercontent.com/22724619/114192202-e351f080-9955-11eb-87ef-435ea4b962e2.png)

**Comment by Ohrimenko1988** [comment]
Implemented on the openshift ci side
