### ISSUE TITLE
Issues with the Installation Guide

### ISSUE THREAD

**Issue by tstastna** [eclipse-che/che#19555]
### `oc` command not found after running `crc start`
Step 7 fails in 'Using CodeReady Containers to configure OpenShift 4' [https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-codeready-containers/](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-codeready-containers/). It is neccessary to execute the commands given by `$ crc start --memory 12288` first. 

The commands are:
`$ eval $(crc oc-env)`
`$ oc login -u developer <url>`

### Logging in with `oc login` not reflected on the web console
In 'Using CodeReady Containers to configure OpenShift 4' [https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-codeready-containers/](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-codeready-containers/), in step 6 , we open a web console. Executing the command in step 7 has no effect on the web console (it still displays a login screen, even after refreshing the page).

### No guide on logging in linked at the end of the installation guide
At the end of the page 'Installing Che on OpenShift 4 using OperatorHub' [https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-openshift-4-using-operatorhub/](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-openshift-4-using-operatorhub/), there is no direct link to the docs describing how to log in.

**Comment by boczkowska** [comment]
Docs Jira issue https://issues.redhat.com/browse/RHDEVDOCS-2929

**Comment by tstastna** [comment]
### Logging in with `oc login` update
Login flow for `oc` and console are two separate flows. The docs should describe both options separately or only focus on one (web console).
