### ISSUE TITLE
Rework the "che-plugin-registry" image build using multistage dockerfile

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#19554]
### Is your task related to a problem? Please describe.

Currently, building of the "che-plugin-registry" requires preinstalled tools on the local machine:
 - nodejs
 - yarn
 - git

In my opinion it would be great to rework the current flow for using multi-stage docker flow.
It gives us several advantages:
 - We will get rid of pre-build steps, all necessary tools will be already in the container
 - Reduce the possibility of local environment issues
 - Keep the image small

**Comment by benoitf** [comment]
it should not be a 'pure multi-stage' Dockerfile, but also publish both 'dev image' and a 'build image'
dev image allows 'dogfooding usage'

**Comment by benoitf** [comment]
BTW we already have the `dev-image`
