### ISSUE TITLE
chectl fail on version comparison

### ISSUE THREAD

**Issue by cb3zopp** [eclipse-che/che#19562]
Fixed for the next channel.
Could you try to check if problem has gone ?
1. `chectl update next`
2. `chectl server:deploy ...`

_Originally posted by @tolusha in https://github.com/eclipse/che/issues/19165#issuecomment-813911285_

**Comment by cb3zopp** [comment]
Did you fix this also für chectl for Windows?
If I install with Windows 10 Hyper-V without a proxy it works.
But on an Azure VM behind a HTTPS proxy I still get the error also with the 'next' channel.

**Comment by tolusha** [comment]
@cb3zopp 
Could you pls attach logs please?
You can use `chectl server:logs` command

**Comment by cb3zopp** [comment]
PS C:\cloud> set_net                                                                                                    
PS C:\cloud> minikube start --addons=ingress --vm=true --memory=8192
* minikube v1.18.1 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
* Found network options:
  - HTTP_PROXY=185.46.212.88:80
  - HTTPS_PROXY=185.46.212.88:80
  - NO_PROXY=192.168.99.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12,10.113.41.0/24,172.0.0.0/8
  - http_proxy=185.46.212.88:80
  - https_proxy=185.46.212.88:80
  - no_proxy=192.168.99.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12,10.113.41.0/24,172.0.0.0/8
* Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...
  - env HTTP_PROXY=185.46.212.88:80
  - env HTTPS_PROXY=185.46.212.88:80
  - env NO_PROXY=192.168.99.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12,10.113.41.0/24,172.0.0.0/8
* Verifying Kubernetes components...
  - Using image us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
  - Using image gcr.io/k8s-minikube/storage-provisioner:v4
  - Using image jettech/kube-webhook-certgen:v1.2.2
  - Using image jettech/kube-webhook-certgen:v1.3.0
* Verifying ingress addon...
* Enabled addons: ingress, storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
PS C:\cloud> kubectl get po -A
NAMESPACE     NAME                                        READY   STATUS      RESTARTS   AGE
kube-system   coredns-74ff55c5b-svqmh                     1/1     Running     2          3d5h
kube-system   etcd-minikube                               1/1     Running     0          52s
kube-system   ingress-nginx-admission-create-gkjfn        0/1     Completed   0          3d5h
kube-system   ingress-nginx-admission-patch-chn6q         0/1     Completed   0          3d5h
kube-system   ingress-nginx-controller-65cf89dc4f-zj2ln   1/1     Running     3          3d5h
kube-system   kube-apiserver-minikube                     1/1     Running     0          52s
kube-system   kube-controller-manager-minikube            0/1     Running     2          3d5h
kube-system   kube-proxy-cgh27                            1/1     Running     2          3d5h
kube-system   kube-scheduler-minikube                     1/1     Running     2          3d5h
kube-system   storage-provisioner                         1/1     Running     5          3d5h
PS C:\cloud> chectl --version
chectl/0.0.20210408-next.cf44212 win32-x64 node-v12.22.0
PS C:\cloud> chectl server:deploy --platform minikube
    TypeError: Invalid Version: undefined
PS C:\cloud> chectl server:logs
Eclipse Che logs will be available in 'C:\Users\cb3zopp\AppData\Local\Temp\chectl-logs\1618229297428'
› Current Kubernetes context: 'minikube'
  × Verify Kubernetes API
    → Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint: https://172.21.186.161:8443/healthz
 …
    Verify if namespace 'eclipse-che' exists
    Read Operator logs
    Read Eclipse Che server logs
    Read Postgres logs
    Read Keycloak logs
    Read Plugin registry logs
    Read Devfile registry logs
    Read namespace events
 »   Error: Error: Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint:
 »   https://172.21.186.161:8443/healthz - Error message: getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes
 »    cluster is healthy - you can skip this check with '--skip-kubernetes-health-check' flag.
 »   Command server:logs failed. Error log: C:\Users\cb3zopp\AppData\Local\chectl\error.log Eclipse Che logs:
 »   C:\Users\cb3zopp\AppData\Local\Temp\chectl-logs\1618229297428

**Comment by cb3zopp** [comment]
I guess chectl server:logs can only work after a successful deployment.
TypeError: Invalid Version: undefined
is the primary error.

**Comment by tolusha** [comment]
@cb3zopp 
I got the problem. 
Thank you for reporting.

**Comment by tolusha** [comment]
Meanwhile could you remove
Could you remove `next-update-info.json` file.
On windows it is located in `<user>\AppData\local\chectl ` directory.

**Comment by tolusha** [comment]
pls.
try `chectl update next` and then `chectl server:deploy ... ` to check if issue is fixed.

**Comment by cb3zopp** [comment]
I think it works. I'm one step further but get a new error. 
My problem is that the no proxy configurations works for the kubernetes unix tools but not for the windows system itself.
For windows I can set the external proxy to get internet. In this case the direct 172.x.x.x adresses don't work. I get only access to the kubernetes cluster when the 172.x.x.x adresses are rebound to localhost.
 Or I set a pac-file which should excludes the internal adresses from the sending to the proxy. In this case I don't get internet access. Must find  error in the windows pacfile/configuration to get both at the same time.

  × Verify Kubernetes API
    → Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint: https://172.24.147.37:8443/healthz
-…
    👀  Looking for an already existing Eclipse Che instance
 »   Error: Error: Failed to connect to Kubernetes API, error: E_K8S_API_NO_RESPONSE - Endpoint:
 »   https://172.24.147.37:8443/healthz - Error message: getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes
 »   cluster is healthy - you can skip this check with '--skip-kubernetes-health-check' flag.
 »   Command server:deploy failed. Error log: C:\Users\cb3zopp\AppData\Local\chectl\error.log Eclipse Che logs:
 »   C:\Users\cb3zopp\AppData\Local\Temp\chectl-logs\1618302145186

**Comment by tolusha** [comment]
Use `--skip-kubernetes-health-check` flag to skip `Verify Kubernetes API` step.

**Comment by cb3zopp** [comment]
I did. This helps to avoid the health check but some steps later there is the next E_K8S_API_NO_RESPONSE error. There must be a way to have a proxy set but exclude the local container adresses from the proxy routing.

**Comment by tolusha** [comment]
Do you mind create a dedicated issue?
I would like not to mix several problems into a single one.
