### ISSUE TITLE
Dashboard should report issues which happens on preLoad

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19564]
### Describe the bug
Currently, when Dashboard fails to preload data (plugins/devfile/workspaces) it just silently does not show objects (samples cards, workspaces). Instead, it should show an error which informs users that requests fails due some reason.

It may overlap a bit with: [UD] Show a proper error page when Che API is not available https://github.com/eclipse/che/issues/18092

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by themr0c** [comment]
Release notes:https://issues.redhat.com/browse/CRW-1872
