### ISSUE TITLE
Review modularity and language on proc_creating-a-telemetry-plugin.adoc 

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19567]
Review the modularity and language of the file `modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc` used to build https://www.eclipse.org/che/docs/che-7/extensions/creating-a-telemetry-plugin/

* Subsections should be separate procedures.
* The main file should become an assembly including all procedures.
* Each procedure should be an ordered list.
* Be more directive.
* Language: avoid `we`, `our`.

**Comment by boczkowska** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2928

**Comment by boczkowska** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-3005
