### ISSUE TITLE
Investigate delays related to theia.workspace.updateWorkspaceFolders

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19566]
### Is your task related to a problem? Please describe.

We use `theia.workspace.updateWorkspaceFolders` API to add projects from the `devfile` to the `theia` workspace config file.
We send a request to add a project as a workspace folder once the projects is cloned.
But [according to the documentation](https://github.com/eclipse-theia/theia/blob/b722e4de165d0a364b27815c9a68bfdf2d031c4a/packages/plugin/src/theia.d.ts#L5902) we should wait till a previous project is added, otherwise we face with the bug that one workspace folder is replaced by another one in the config file.  

The problem is: 
it takes ~ 3 seconds (sometimes 4-5 seconds) between sending a request and getting the `onDidChangeWorkspaceFolders` event. We have to wait this time before sending the next request to add another project as workspace folder.
The value of the delay (3-5 seconds) is actual for the `dogfooding` instance, I guess it can be more critical for `minikube` instance running on a machine with low resources.

### Describe the solution you'd like

We could investigate where the delay is.

I see 3 stages which should be checked:
- communication `workspace-plugin` of `che-theia` ===> `theia` side, so `workspace-plugin` sends a request on the `theia` side to add a project as a workspace folder
- `theia` does some actions related to adding a workspace folder 
- communication `theia` side ===>  `workspace-plugin` of `che-theia`, so `theia` sends an event that workspace folders were updated and `workspace-plugin` catch the event.

**Comment by azatsarynnyy** [comment]
I suppose it's still relevant. So, reopening.
Feel free to close if you see it isn't a problem anymore.
