### ISSUE TITLE
Impossible to restart Happy path tests for che-theia PRs

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19571]
### Describe the bug

I tried to restart the Happy path tests for my PR to che-theia using `[crw-ci-test]` and `[crw-ci-test --rebuild]`, but there was no effect.

### Steps to reproduce
Try to restart the Happy path tests for a PR.
I tried it [here](https://github.com/eclipse-che/che-theia/pull/1075#issuecomment-818642124) and [here](https://github.com/eclipse-che/che-theia/pull/1049#issuecomment-818660783)

**Comment by dmytro-ndp** [comment]
Restart of Happy path tests has been restored.
The root problem was the recent outage on CRW Jenkins CI infrastructure.
