### ISSUE TITLE
Add @devfile/api types to devworkspace-client

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#19579]
### Is your enhancement related to a problem? Please describe.

Now that https://github.com/devfile/api/pull/384 is merged, we now have typescript types for the devfile api. We should integrate these into the devworkspace-client

### Describe the solution you'd like

Add https://www.npmjs.com/package/@devfile/api to the devworkspace-client typescript library

**Comment by sleshchenko** [comment]
There are two issues in devfile/api types currently:
- [ ] metadata of typescript DevWorkspace types is just object https://github.com/devfile/api/issues/494
- [ ] Devfile API typescript types does not have a type for devfile https://github.com/devfile/api/issues/493

**Comment by sleshchenko** [comment]
https://github.com/che-incubator/devworkspace-client/pull/26 actually does what is needed but before merging it, it's needed to refactor Dashboard pretty significantly. Moving it to a separate issue https://github.com/eclipse/che/issues/20191
