### ISSUE TITLE
Update keycloak from 6.0.1 to the latest version, 15.0.2

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19585]
### Is your enhancement related to a problem? Please describe.
For the time being there multiple issues with Keycloak 6.0.1 related to Eclipse Che:
- #19547
- #17681 
- #19279
- #18030
- #19646
- #19653

### Describe the solution you'd like
1. To try update and collect possible issues
2. Estimate them if it worth updating or wait until Keycloak won't be mandatory (5-6 month)

### Release Notes text
Update keycloak from 6.0.1 to the latest version, 15.0.2

**Comment by l0rd** [comment]
cc @jenia90

**Comment by jenia90** [comment]
@l0rd thank you for opening the issue. It will take us couple of days since it's holidays here, but my colleagues and myself will open all of the relevant issues somewhere next week.

**Comment by jenia90** [comment]
Ref issue #19646 with a list of vulnerabilities that were found in che-keycloak image.

**Comment by cccs-tom** [comment]
I am very interested in this update, but I see it's been removed from all milestones at this time. Is this still on the roadmap, @tolusha?

**Comment by tolusha** [comment]
@cccs-tom 
yes, It is still in the roadmap.
Unfortunately @AndrienkoAleksandr  who is an expert in this field, currently is busy with another long lasting task

**Comment by cccs-tom** [comment]
Great, thanks for the update!

**Comment by AndrienkoAleksandr** [comment]
I tested keycloak 15.0.0 on the k8s platform(minikube) and my result: login/logout/ access to user profile works. Workspaces are starting and running, but ingress blocks che-theia editor page. I found that new keycloak sends plenty big header in the response and ingress block it:

```
2021/08/09 07:56:12 [error] 18582#18582: *3520556 upstream sent too big header while reading response header from upstream, client: 192.168.99.1, server: keycloak-eclipse-che.192.168.99.111.nip.io, request: "GET /auth/realms/che/protocol/openid-connect/auth?client_id=che-public&redirect_uri=https%3A%2F%2Fche-eclipse-che.192.168.99.111.nip.io%2F_app%2Floader.html%3FredirectUrl%3Dhttps%3A%2F%2Fserverkjz3u98u-jwtproxy-server-4402.192.168.99.111.nip.io%2F%26workspaceId%3Dworkspacevfbms22q4nf4eetc&state=5db1dbf2-af3d-45aa-9a5e-e5999be5e528&response_mode=fragment&response_type=code&scope=openid&nonce=cd5d9e34-b29e-453b-8073-1d73c35e81bf HTTP/2.0", upstream: "http://172.17.0.15:8080/auth/realms/che/protocol/openid-connect/auth?client_id=che-public&redirect_uri=https%3A%2F%2Fche-eclipse-che.192.168.99.111.nip.io%2F_app%2Floader.html%3FredirectUrl%3Dhttps%3A%2F%2Fserverkjz3u98u-jwtproxy-server-4402.192.168.99.111.nip.io%2F%26workspaceId%3Dworkspacevfbms22q4nf4eetc&state=5db1dbf2-af3d-45aa-9a5e-e5999be5e528&response_mode=fragment&response_type=code&scope=openid&nonce=cd5d9e34-b29e-453b-8073-1d73c35e81bf", host: "keycloak-eclipse-che.192.168.99.111.nip.io", referrer: "https://che-eclipse-che.192.168.99.111.nip.io/"
```

So user see error page "502 Bad Gateway nginx" instead of che-theia. It can be fixed creation custom ingress configmap and modification ingress controller deployment to use this custom configmap, but such variant doesn't satisfy us. I will contact with keycloak team and I will try investigate why it works fine good on the old keycloak and brings troubles with newer one.

**Comment by tolusha** [comment]
Just to inform. 
We have completed all tests and ready to migrate to keycloak 15.0.2 (will be done approximately next week)

**Comment by jenia90** [comment]
> 
> 
> Just to inform.
> We have completed all tests and ready to migrate to keycloak 15.0.2 (will be done approximately next week)

This is great news! :)
