### ISSUE TITLE
Pressing Enter key on a node inside FindUsage widget works incorrectly

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1959]
**Steps to reproduce:** Open the GreetingController class of the Spring project. Set cursor on the userName variable. Invoke the Find Usage feature. Select the last node in the Usages widget and press Enter key.
**Expected result:** the userName variable should be selected.
**Actual result:** the userName variable is replaced on new line in the Editor

**Comment by JamesDrummond** [comment]
@musienko-maxim @eivantsov Please assign someone.
