### ISSUE TITLE
IDEA Che editor window must be maximized

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19595]
### Is your task related to a problem? Please describe.
Currently, IDEA Che editor window isn't maximized and there're no buttons to change the window's state.
The only way to get it maximized is to change the browser's window size, e.g. restore and maximize it again.

### Describe the solution you'd like
Need to find a way to fix that: in the upstream repo (projector-client), in our downstream repo or on the dashboard side.

### Additional context
![image](https://user-images.githubusercontent.com/1636395/114733239-d9f8c780-9d4b-11eb-8095-0708ee006958.png)

**Comment by vzhukovs** [comment]
Linked upstream issue: https://youtrack.jetbrains.com/issue/PRJ-452
