### ISSUE TITLE
Update vscode-openshift-tools to the latest version

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19597]
### Is your task related to a problem? Please describe.
The latest version is `0.2.4` but in Che we have `0.2.0`.

### Describe the solution you'd like

Update to the latest version.

### Describe alternatives you've considered
N/A

### Additional context
Useful for the devfile 2.0 story.

**Comment by vinokurig** [comment]
Depends on https://github.com/eclipse/che/issues/19361
