### ISSUE TITLE
127.0.0.1:8080 always redirects to /che/default for Chrome

### ISSUE THREAD

**Issue by howdoicomputer** [eclipse-che/che#196]
I uninstalled Che, checked every autocomplete setting there is, and my browser is still redirecting me to `/che/default/` whenever I visit `127.0.0.1` through Chrome. Doesn't do the same on Firefox. This is probably more of a Chrome bug but I thought I would report it here for any luck.

**Comment by TylerJewell** [comment]
That is an unusual issue. Have you attempted to do a hard refresh? On Chrome, open the developer tools console (CTRL-SHIFT-i). Then you can right click on the refresh button for various caching options. Do a hard refresh and cache cleanse.
