### ISSUE TITLE
[UD] Avoid re-rendering the Workspace Details page

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#19601]
### Is your task related to a problem? Please describe.

This is a technical debt issue. The PR for improving devworkspaces support introduces the bug that the whole workspace details page gets re-rendered each time the workspace is updated. That's the regression and it brings inconvenience to the devfile editor usage.  

### Describe the solution you'd like

The solution is to provide necessary changes to the nested components without re-rendering of the root page component.

### Additional context

https://github.com/eclipse/che-dashboard/pull/209

**Comment by sleshchenko** [comment]
fixed by https://github.com/eclipse-che/che-dashboard/pull/217
