### ISSUE TITLE
Wrong behavior after  renaming a package

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1960]
- Import  the attachment example and open class from package test0.r  Perform renaming the package for example test0.r -> testm.r

![anim](https://cloud.githubusercontent.com/assets/1640058/17171607/20c10e0c-53fa-11e6-8352-2219f67b8666.gif)

**Wrong:** After performing refactoring java content disappears from a opened class. The current package is collapsed.

[rename-package.zip](https://github.com/eclipse/che/files/385758/rename-package.zip)

**Comment by JamesDrummond** [comment]
@musienko-maxim @eivantsov Please assign someone.

**Comment by artaleks9** [comment]
The issue is not actual.
