### ISSUE TITLE
recommendation plug-in is not working

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19610]
### Describe the bug
Open a workspace like spring-petclinic, we don't see any recommendation

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

provide URL factory like `#https://github.com/spring-projects/spring-petclinic`

### Expected behavior
see recommendations

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by benoitf** [comment]
should be fixed again 🎉

**Comment by nickboldt** [comment]
commented above: 22 apr 12:41pm gmt-3
rebuilt in quay:        22 apr 6:11 pm ADT / gmt-3 (?)

So probably included in the latest builds, but would need to check commit SHAs and logs to be sure.
