### ISSUE TITLE
Fix Happy path PR check of che-dashboard after migration to new repo

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19617]
### Is your task related to a problem? Please describe.
Fix Happy path PR check of che-dashboard after migration to new repo https://github.com/eclipse-che/che-dashboard

**Comment by dmytro-ndp** [comment]
Happy path test pipelins on CRW Jenkins CI has been fixed: https://github.com/eclipse-che/che-dashboard/pull/204#issuecomment-821329863
