### ISSUE TITLE
Deprecate CurrentProjectChangedEvent and his handler

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#1961]
CurrentProjectChangedEvent and CurrentProjectChangedHandler is never used. Mark them as deprecated.

**Che version:**    4.6.0-SH
**Additional information:** None

**Comment by benoitf** [comment]
maybe use Fixes #1961 in commit message 
https://help.github.com/articles/closing-issues-via-commit-messages/
so when PR is merged, it will close the issue automatically
