### ISSUE TITLE
Investigate the way how to provide plugins to JetBrains Editor Images at startup time

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#19626]
### Is your task related to a problem? Please describe.
There is a need to find out the way how to easily install plugins into JetBrains Editor Images at workspace startup.

### Describe the solution you'd like
Each single JetBrains Plugin represents a single directory with the set of jars, that can be copied to the plugins directory.
There might be a mechanism, that can check the plugin id and version (for example) and download/unpack the plugin before Projector Server initialize.

### Describe alternatives you've considered
N/A at this moment.

### Additional context
Plugin for example: https://plugins.jetbrains.com/plugin/164-ideavim/versions/stable
Upstream discussions: https://youtrack.jetbrains.com/issue/PRJ-350

**Comment by azatsarynnyy** [comment]
The solution was implemented within the https://github.com/che-incubator/jetbrains-editor-images/pull/78
