### ISSUE TITLE
Reconsider addWorkspaceFolder() implementation

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19624]
### Is your task related to a problem? Please describe.

[addWorkspaceFolder() method](https://github.com/eclipse-che/che-theia/blob/60773883a5ff09ec30e3853f856b72031f9f0440/plugins/workspace-plugin/src/workspace-folder-updater.ts#L18) is responsible for the logic that add projects as workspace folders step by step, it respects [the documentation](https://github.com/eclipse-theia/theia/blob/8b9fb43c763f2f1d179f9839ef993d7218d99073/packages/plugin/src/theia.d.ts#L5902) for `theia.workspace.updateWorkspaceFolders()` API.  
The method returns a promise and it's expected that the promise is resolved when a project is added as workspace folder. 
But at the moment it's not true - there is no guarantee that a project is added as a workspace folder when a promise is resolved.
The promise can be resolved, for example, when [a project just added to a queue](https://github.com/eclipse-che/che-theia/blob/60773883a5ff09ec30e3853f856b72031f9f0440/plugins/workspace-plugin/src/workspace-folder-updater.ts#L26).

Previously, it was not critical, the goal of the current implementation was - add projects as workspace folders with respect [the documentation](https://github.com/eclipse-theia/theia/blob/8b9fb43c763f2f1d179f9839ef993d7218d99073/packages/plugin/src/theia.d.ts#L5902).  

But now we are starting to rely on a returned promise within https://github.com/eclipse-che/che-theia/pull/1079, so we should revisit [addWorkspaceFolder()](https://github.com/eclipse-che/che-theia/blob/60773883a5ff09ec30e3853f856b72031f9f0440/plugins/workspace-plugin/src/workspace-folder-updater.ts#L18) and improve it.
 
### Describe the solution you'd like

I believe we should resolve a returned promise when we get an event from `theia` side that a project was added as workspace folder.
Please pay attention on the [the documentation](https://github.com/eclipse-theia/theia/blob/8b9fb43c763f2f1d179f9839ef993d7218d99073/packages/plugin/src/theia.d.ts#L5902).

### Additional context

AFAIK the problem has no influence for cloning process or adding projects to projects tree and so on.
At the moment it is actual for the recommendations plugin.

**Comment by vitaliy-guliy** [comment]
Linking with https://github.com/eclipse-che/che-theia/pull/1076 as it contains reworked `addWorkspaceFolder` and added `removeWorkspaceFolder`, which are synchronized with each other.

**Comment by vitaliy-guliy** [comment]
Solved by https://github.com/eclipse-che/che-theia/pull/1076
