### ISSUE TITLE
Naming of CheCluster Custom Resource server `devfileRegistryUrl` and status `devfileRegistryURL` is confusing and error prone

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19632]
### Describe the bug
Looks like https://github.com/eclipse/che/issues/19627 wasn't a bug. `devfileRegistryURL` instead of `devfileRegistryUrl`. However this is errorprone. Same for the `pluginRegistryUrl`: I had that issue 3 weeks ago not knowing what was wrong ... but probably the same problem

![image](https://user-images.githubusercontent.com/650571/115422322-15d4d680-a1fd-11eb-9598-9a28ad5ddbfc.png)

And broker not able to download plugins from the registry.
We cannot keep the "almost" the same names for these. Either they are the same, or we should use completely different names to avoid errors.

### Che version

 - [x] latest 7.29.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
See https://github.com/eclipse/che/issues/19627

### Expected behavior
Maybe `status.devfileRegistryURL` should be renamed `status.devfileRegistryUrl`. (and `status.pluginRegistryURL` renamed `status.pluginRegistryUrl`) that would avoid error from the user.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by tolusha** [comment]
Close in favor of https://github.com/eclipse/che/issues/20758
