### ISSUE TITLE
An error/warning hint in editor disappears when new line in console is added

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#1963]
An error/warning hint (near a line number) on mouse hover in editor disappears when new line in console is added

**Reproduction Steps:**
1. Open a project
2. Open a file with an warning/error 
3. Run maven build (many new lines like `Downloading: *****` is expected)
4. Hover mouse cursor on an warning/error ico

**Expected behavior:**
Hint is visible until mouse on an ico

**Observed behavior:**
Hint appears, but when new line is added into console it disappears

**OS and version:**
Che 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

![err_hint](https://cloud.githubusercontent.com/assets/15607393/17174071/63e1c106-5407-11e6-97df-9d5b3bc14be6.gif)

**Comment by JamesDrummond** [comment]
@vparfonov Can we change this to kind/task?

**Comment by JamesDrummond** [comment]
Provide status label.

**Comment by mmorhun** [comment]
Still actual.

**Comment by slemeur** [comment]
Won't fix
