### ISSUE TITLE
Automate testing Plugins view from the IDE

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19639]
### Is your task related to a problem? Please describe.
We have to add automation tests to check the process of the plugins' installation from Plugins view. It will help us to detect problems like https://github.com/eclipse/che/issues/19623 immediately

### Describe the solution you'd like
The flow could be:
1. Open Plugins view
2. Check list of installed plugins
3. Try to install not installed plugin
4. Check the devfile if new plugin was added

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/19766
