### ISSUE TITLE
Dashboard should be be able to group samples in dedicated groups

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19633]
### Is your task related to a problem? Please describe.
For enabling community samples on DevSandbox, dashboard should support grouping samples to make it clear which ones come from RedHat and which from the community(upstream).

### Describe the solution you'd like
Dashboard allows to configure different devfile registries into different groups, like:
```
samples: {
  "RedHat certified samples": "che-devfile-registry.workspace.io",
  "Community samples": "https://che-devfile-registry.github.com, https://sleshchenko-devfile-registry.github.com",
}
```
Then dashboard display it somehow like
![Screenshot_20210420_182758](https://user-images.githubusercontent.com/5887312/115424755-a7494600-a207-11eb-9acf-f4d25d8ae671.png)

Or provides switcher with the first selected by default.

**Comment by ericwill** [comment]
To make it more extensible, I was thinking we could introduce a category system with a tag schema based on [devfile tags](https://github.com/eclipse-che/che-devfile-registry/blob/master/devfiles/apache-camel-k/meta.yaml#L4). We could show all devfiles in the same view and let the user filter with a filtering system, similar to [OperatorHub](https://user-images.githubusercontent.com/6290632/115447506-95a37680-a1e6-11eb-937c-7fc4370151d0.jpg). We could then filter based on categories from the tag schema like:
* Architecture (devfiles with tags `amd64`, `s390x`, etc.)
* Source (devfiles with tags `community` or `crw`)
* Airgap Compatibility (devfiles with tags `airgap` or not)
*  Etc.

As for including these devfiles in CRW's `Getting Started` view, we can just append the published URL of the upstream devfile registry to the CRW devfile registry URLs list.

**Comment by sleshchenko** [comment]
For architecture and airgap mode, I agree, but for source, it seems to have security issue, any devfile registry(including) can bring `crw`, `redhat-certified` devfile, when they are not such.
So, I believe the source should define Cluster Administrator but not devfile itself.

**Comment by sleshchenko** [comment]
from Mario: the following design would be enough
![image (2)](https://user-images.githubusercontent.com/5887312/116548697-4acbe200-a8fd-11eb-941a-465c042f786d.png)

**Comment by sunix** [comment]
> For architecture and airgap mode, I agree, but for source, it seems to have security issue, any devfile registry(including) can bring `crw`, `redhat-certified` devfile, when they are not such.
> So, I believe the source should define Cluster Administrator but not devfile itself.

I don't see any security concern. Adding a defile registry that you cannot trust is the danger and this is the responsibility of the admin to trust it or not.
If this is a security concern, we should not let anyone adding external sources: these could contain devfiles with images containing arbitrary malicious code.

**Comment by sleshchenko** [comment]
> If this is a security concern, we should not let anyone adding external sources: these could contain devfiles with images containing arbitrary malicious code.

it's a different story, because users accept risk. But in such case confirmation dialog will be by passed.

Also, note that architecture will be handled our of tags in devfile v2: https://github.com/devfile/api/pull/490

**Comment by sunix** [comment]
Today we say, that community devfiles are coming from a distinct source. But, if we change our mind and choose to have supported AND community in the same regirstry, the approach [here](https://github.com/eclipse/che/issues/19953) will still work. The proposed approach with separate sections won't work.

**Comment by sunix** [comment]
About security, if the admin is setting
```
samples: {
  "RedHat certified samples": "https://che-devfile-registry.github.com, https://sleshchenko-devfile-registry.github.com"
}
```
confirmation dialog will be by passed.

**Comment by sleshchenko** [comment]
Interesting to share similar case: the way how OpenShift Console allows to configure custom sources for helm charts: https://docs.openshift.com/container-platform/4.7/cli_reference/helm_cli/configuring-custom-helm-chart-repositories.html

```yaml
apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  name: <name>
spec:
 # optional name that might be used by console
 # name: <chart-display-name>
  connectionConfig:
    url: <helm-chart-repository-url>
```

**Comment by nickboldt** [comment]
This is required for implementing UDI image (if we want to have ALL the tech preview and GA supported stuff in the same container). (Or else we need to do https://github.com/eclipse/che/issues/19953.) 

As long as there's a visual indicator of quality/support/source (eg., community/tech preview/RH supported) then I'm happy. 

See:
* https://github.com/devfile/api/issues/616
* https://issues.redhat.com/browse/CRW-2463
* https://issues.redhat.com/browse/CRW-2464

**Comment by ibuziuk** [comment]
The current plan is:
- devfile registry will provide relevant tags for each devfile
- if tags contain 'community' or 'tech-preview' dashboard wiill add a relevant label in the OperatroHub style e.g.

![image](https://user-images.githubusercontent.com/1461122/143423000-2316794a-89df-4f58-8701-15af00c162f2.png)

- if there are no `community` or `tech-preview` tags the devfile is displayed on UD in a regular manner without any labels

N.B. tags can not contain both  'community' and 'tech-preview' (only one is applicable)

**Comment by ibuziuk** [comment]
@nickboldt could you clarify if we have the tags on the devfile registry end or those are still missing?

**Comment by ibuziuk** [comment]
@nickboldt any updates?

**Comment by ibuziuk** [comment]
@akurinnoy the `community` / `tech-preview` tags are in place - https://github.com/eclipse/che/issues/19953#issuecomment-980175566

**Comment by nickboldt** [comment]
Tags were added 19 days ago. I guess no one noticed / asked me directly :( And yet... someone merged them... 

Will we be able to get this UI enhancement in place for 7.41?

**Comment by benoitf** [comment]
moving issue to 7.42 milestone as this issue is part of the endgame

**Comment by nickboldt** [comment]
Followup in https://github.com/eclipse/che/issues/20976
