### ISSUE TITLE
Trigger chectl#next nightly in addition to main branch push

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19644]
### Is your task related to a problem? Please describe.
Sometimes newer Che Operator image depends on the updated manifests files. This means that chectl#next may not work correctly since it deploys the next che operator image with the `latest` cached templates
Trigger chectl#next nightly in addition to main branch push just to refresh templates and avoid chectl breaking.

**Comment by tolusha** [comment]
I am not sure if it is possible to commit files inside GitHub action
