### ISSUE TITLE
Automatically configure Kubernetes Image Puller with the list of images used by Che

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19657]
### Is your enhancement related to a problem? Please describe.

Today, using the KIPO requires manual configuration to add the list of images to pre-pull into your cluster, be it for offline/airgapped mode w/ OCP 3.11, or for performance tuning by caching the images across your cluster's various nodes.

### Describe the solution you'd like

So, in future, it would be a great UX / simplification if the KIP could simply read the Che Operator's CSV and use that list of RELATED_IMAGE_* env vars to prepopulate the image list it will pull. 

https://issues.redhat.com/browse/CRW-2082 

### Release Notes Text

The ImagePuller had to be configured manually. Now Che operator automatically configure it to pre-pull the images used the Che-Theia plugins in developer workspaces.

**Comment by skabashnyuk** [comment]
Should it be a separate config map for example? I wonder - are we care about independence Kubernetes Image Puller (KIP) from che . CC @ibuziuk

**Comment by ibuziuk** [comment]
yes, KIP should be separated for che, however the integration the operator level could technically fall back on some mechanism for retrieving the images for pre-pulling, I'm not sure that Che operator csv is the way to go though.

**Comment by nickboldt** [comment]
Why does it need to be independent? Who's using it outside the context of Che/CRW?

That said, if you DO keep it independent, would it make sense to have the OPTION to prepopulate from the che operator's CSV ?

If you're using KIPO to install KIP via the Che operator in operatorHub on OCP, to me it makes sense to take advantage of the data already available in the CSV. 

If you're not installing KIPO from the Che operator, then sure, we'd need another way to prepopulate the list.

**Comment by ibuziuk** [comment]
> Why does it need to be independent? Who's using it outside the context of Che/CRW?

There are external contributors from the community you can see recently merged / opened PRs. 

> That said, if you DO keep it independent, would it make sense to have the OPTION to prepopulate from the che operator's CSV

I do not think CSV is the common way to exchange the data between operators - that needs to be investigated.

**Comment by l0rd** [comment]
@ibuziuk we should review that during next cabal

**Comment by ibuziuk** [comment]
The initial implementation is done - https://github.com/eclipse-che/che-operator/pull/880
Closing
