### ISSUE TITLE
Fix happy path PR check on a new CI instance after moving dashboard to a separate deployment

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19652]
### Is your task related to a problem? Please describe.
There is an PR that adapts dashboard happy path on the old CI instance after moving dashboard to a separate deployment. The new one is also needs to be adapted.

Required changes: https://github.com/eclipse/che/pull/19606

**Comment by dmytro-ndp** [comment]
@sleshchenko : is the issue still actual, after target PR had been merged?

**Comment by sleshchenko** [comment]
@dmytro-ndp I think so if dashboard happy path is running on the old CI.
If it's on new already and works - then it can be closed.
