### ISSUE TITLE
Add CI job that verifies sidecar images digests in devfile registry

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#19660]
### Is your task related to a problem? Please describe.

Occasionally, images that we list for sidecars may have outdated digests. If that happens, we would like to find out about it as early as possible (before the scheduled weekly releases), and decide whether we should update the images

### Describe the solution you'd like

A github actions workflow that runs daily to check if all images have correct digest, if not - fetch a correct one (with skopeo or curl) and submit a PR to devfile-registry to update it

**Comment by nickboldt** [comment]
Specific reason for this is the quarkus sidecar image, which keeps updating its floating tags and removing older images' digests.

**Comment by nickboldt** [comment]
WIP in https://github.com/eclipse-che/che-devfile-registry/pull/380 awaits revision and merge.

**Comment by nickboldt** [comment]
Job has failed in https://github.com/eclipse-che/che-devfile-registry/runs/2471789961?check_suite_focus=true

```
 ./arbitrary-users-patch/check_sidecar_images_digests.sh
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/b0039ca4-c0f6-46d5-80be-30920f8bb6fd.sh: line 4: ./arbitrary-users-patch/check_sidecar_images_digests.sh: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by nickboldt** [comment]
WIP in https://github.com/eclipse-che/che-devfile-registry/pull/383/files

**Comment by nickboldt** [comment]
Done and green in https://github.com/eclipse-che/che-devfile-registry/actions/workflows/sidecar-check.yml
