### ISSUE TITLE
Integrated selenium tests to check if JetBrains editor image is not corrupted during the build

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#19661]
### Is your task related to a problem? Please describe.
Since rendering framework operates with canvases in browser document. It is possible to use Selenium Framework to create a set of integration tests to check if image is not corrupted and IDE is able to start after Docker image build. Each window which is rendered in the browser document represents a dedicate canvas with class names and ids. This allows to create a simple use case to check via selenium tests.

**Comment by azatsarynnyy** [comment]
If I understand correctly, we already have the tests for checking IDEA startup - https://github.com/eclipse/che/pull/18187
Or do you mean something else?

**Comment by vzhukovs** [comment]
@azatsarynnyy, tests in [#18187](https://github.com/eclipse/che/pull/18187) only checks whether iframe with openVNC is opened, but with noVNC it was not possible to check what exactly was rendered inside document, because it had only one canvas element to display the whole desktop. On the other hand, Projector allows to observe each IDE window as separate canvas. And these integration tests should be integrated into GitHub actions which will be executed before publishing image to quay.io
