### ISSUE TITLE
Che Operator does not update DWO and DWCO resources

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19664]
### Describe the bug
Che Operator does not update DWO and DWCO resources but only creates them.
This is error-prone for CI version, since after deployment manifests or CRDs are changed and CI DWO or DWCO depends on it(next tag), they will fail.
The flow to recover Che installation from broken state - remove DWO and DWCO resources manually and let Che Operator recreate them.

For the released version, it means that newer Che versions won't get newer DWO and DWCO.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
The scenario above should explain almost all. If details or help is needed how to reproduce it - let me know.

### Expected behavior
Che Operator runs DWO and DWCO that correspond to deployed Che version.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by tolusha** [comment]
I strongly against updating DW resource from operator.
Imagine testing environment with different version of Eclipse Che installed.
Every single Che will try to update DW to its own version ^(

**Comment by amisevsk** [comment]
Che can't depend on a specific version of DWO without potentially being incompatible with the web terminal operator.

**Comment by tolusha** [comment]
Some notes from Deploy team cabal call.

```
For now we must update DW by CO, but when we have DW on OperatorHub it will be updated automatically via OLM mechanism. If this issue takes more than 3 days then it is better to publish DW on OperatorHub.
```
