### ISSUE TITLE
Che using an external keycloak fails to update

### ISSUE THREAD

**Issue by matthewfisch** [eclipse-che/che#19670]
### Describe the bug
The community operatorhub installplan fails to upgrade from 7.28.2 to 7.29.0 using an external keycloak.

The Che container will never reach ready because of unexpected input from the Keycloak server.

By reviewing the operator installplan log I noted the change to the keycloak auth URL (see below).

By manually editing the checluster keycloak URL (and the subsequent configmap) to the previous URL Che ran fine and install completed (I added '/auth' back to the end). See logs at bottom for the installplan behavior that created this issue.

### Che version
7.29.0

### Steps to reproduce

- Using an external keycloak
- Using Che with operator 7.28.2
- Manually (or automatically) approve the installplan

### Expected behavior
Che upgrades and restarts

### Runtime
   - [ X ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ X ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs

OperatorHub Log entry:

-               "CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL": "https://keycloak.dev.domain/auth",
+               "CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL": "https://keycloak.dev.domain",
-               "CHE_KEYCLOAK_AUTH__SERVER__URL":           "https://keycloak.dev.domain/auth",
+               "CHE_KEYCLOAK_AUTH__SERVER__URL":           "https://keycloak.dev.domain",

**Comment by tolusha** [comment]
@matthewfisch 
Thank you for reporting. I got the problem

**Comment by tolusha** [comment]
Fixed for 7.29.2 and 7.30.0

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1869
