### ISSUE TITLE
Machine recipe not editable

### ISSUE THREAD

**Issue by ddementieva** [eclipse-che/che#1967]
Machine recipe not editable in operations perspective 
**Reproduction Steps:**
1. Start a workspace
2. Go to Operations perspective
3. Create a new recipe
4. Try to edit it.

**Expected behavior:**

The recipe is editable and can be saved

**Observed behavior:**

The recipe is not editable.

**Comment by bmicklea** [comment]
@skabashnyuk: This is affecting a customer - assess and add a status label, this is urgent.

**Comment by TylerJewell** [comment]
@vparfonov - milestone?
