### ISSUE TITLE
What is {prod-namespace} supposed to be?

### ISSUE THREAD

**Issue by simjnd** [eclipse-che/che#19672]
Hi, I'm trying to install Eclipse Che in Microsoft Azure. There's something I'm not sure I understand in the docs ([the installing cert-manager part](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/#installing-cert-manager-on-azure_che)) we can read this:

![image](https://user-images.githubusercontent.com/43272781/116061459-29f85800-a683-11eb-9a11-8745a5a8b5eb.png)

What is the {prod-namespace} supposed to be? The rest of the docs gives you fixed names for things (ingress-nginx is named ingress-nginx, the cert-manager namespace, the eclipse-che namespace), so I find it unsettling that here we're supposed to fill this in with out "production namespace" but I'm not sure what is my production namespace? Is it my eclipse-che namespace?

Thanks!

(was confused as well by the {orch-cli} when the whole rest of the docs shows commands with kubectl)

**Comment by tolusha** [comment]
@simjnd 
`{prod-namespace}` is supposed to be `eclipse-che`
`{orch-cli}` is supposed to be `kubectl`

@themr0c

**Comment by simjnd** [comment]
Thank you very much!

**Comment by tolusha** [comment]
If you don't mind I will keep this issue opened to allow doc team to update the doc.

**Comment by ibuziuk** [comment]
cc: @themr0c ^ please prioritize

**Comment by MichalMaler** [comment]
Jira issue to fix this:
https://issues.redhat.com/browse/RHDEVDOCS-3015

**Comment by MichalMaler** [comment]
Fixed
