### ISSUE TITLE
Docs asking to manually deploy cert-manager when chectl deploy takes care of it

### ISSUE THREAD

**Issue by simjnd** [eclipse-che/che#19680]
Hi again,

I faced the same problem as #16694 during the installation process, with `chectl server:deploy` failing because of "invalid secret" after I followed the docs and manually deployed `cert-manager` as is prescribed.

In the comments of this issue [it is mentioned](https://github.com/eclipse/che/issues/16694#issuecomment-617578892) :

> We have inconsistency between doc the and the installation.
> The doc describe steps how to deploy cert-manager and how to create secret, but chectl with helm installer deploys cert-manager also and expect a specific che-tls secret.

I have redone the installation and when I skipped the whole part about cert-manager it ended up working perfectly.

My point being: the issue aforementioned has been closed but it looks like the docs has not been corrected to remove that part or to tell people they shouldn't actually do it. So I was wondering if that was something you guys were are aware of?

**Comment by tolusha** [comment]
@simjnd 
Thank you for bringing that up.
It probably slipped from us.

**Comment by boczkowska** [comment]
A JIra issue for the docs team https://issues.redhat.com/browse/RHDEVDOCS-3004

**Comment by pmkovar** [comment]
@tolusha Do you want to self-assign this one?
