### ISSUE TITLE
Wrong behavior 'Close other' feature from context menu for tabs in the editor

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#1968]
[Short description of problem here]

**Reproduction Steps:**
1. Create project or import any project
2. Open  multiple files (java and not java files) in the editor
3. Select first opened tab
4. Open context menu and select 'Close other'

**Expected behavior:**
All tabs were closed, except selected tab

**Observed behavior:**
 Not all tabs were closed

**Che version:**  4.6.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.11.2
**Che install:**   local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes

**Comment by JamesDrummond** [comment]
@riuvshin Provide status label.

**Comment by AndreyChizhikov** [comment]
Сannot reproduce
