### ISSUE TITLE
Setup release management for JetBrains Che Editor Images

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#19698]
#### Preface

The is a need to set up the release management for https://github.com/che-incubator/jetbrains-editor-images repository.

#### Semantic versionning

Semantic versionning for Docker images can be look like: 

- `next` which points to the latest commit in master branch
  - `quay.io/che-incubator/che-idea:2020.3.3-next`
  - `quay.io/che-incubator/che-pycharm:2020.3.5-next`

- `latest` which points to the latest released `version`
  - `quay.io/che-incubator/che-idea:latest`
  - `quay.io/che-incubator/che-pycharm:latest`

- `version` which points to the latest released `version-YYYYMMDD.hashId`
  - `quay.io/che-incubator/che-idea:2020.3.3`
  - `quay.io/che-incubator/che-pycharm:2020.3.5`

- `version-YYYYMMDD.hashId`, e.g. `2020.3.3-20210428.aabbccdd`
  - `quay.io/che-incubator/che-idea:2020.3.3-20210428.aabbccdd`
  - `quay.io/che-incubator/che-pycharm:2020.3.5-20210428.aabbccdd`

#### Tagging policy

Each git tag and release version should look like: `YYYYMMDD.hashId` and reflect changes made in current release.

#### Changelog policy

Repository should have `CHANGELOG.md` which represents up-to-date list of changes made in master branch after each commit.

#### Additional tasks

- Create document which reflects thoughts in current issue about release management

- Update about and description section in repository configuration

- `default-che-container.json` should be update and contains information about:
  - `che-idea` image name and url which is used in current release version
  - `che-pycharm` image name and url which is used in current release version

- `build-container.sh` and `build-container-dev.sh` should handle additional flags `--idea`, `--pycharm` and take particular configuration from `default-che-container.json` to build the image.
  - to build a custom image there should be flag used `--custom` with nadling container name and download url
- `run-container.sh` and `run-container-mounted.sh` should handle additional flags `--idea`, `--pycharm` and take the particular image name to run from `default-che-container.json`

**Comment by vzhukovs** [comment]
@benoitf @azatsarynnyy wdyt of this?

**Comment by benoitf** [comment]
hi, I was wondering if we could use the jetbrains versioning directly ?

like `quay.io/che-incubator/che-idea:2020.3.3`

**Comment by vzhukovs** [comment]
- `quay.io/che-incubator/che-dea:2020.3.3`
- `quay.io/che-incubator/che-python:20202.3.5`

Sounds ok, but if we take into account that fact, that repository is one for building two images, how the release tagging will look like in this case? 

I suppose, that flow in this scenario will look like:
1. New commits go to master.
2. On particular date, we'll create a tag with name, e.g. `YYYYMMDD.hashId`, perform release.
3. Build:
    1. `quay.io/che-incubator/che-idea:2020.3.3` which points to: 
    `quay.io/che-incubator/che-idea:2020.3.3-YYYYMMDD.hashId`
    2. `quay.io/che-incubator/che-pycharm:20202.3.5` which points to:
    `quay.io/che-incubator/che-pycharm:20202.3.5-YYYYMMDD.hashId`
4. Create tag `latest`:
    1. `quay.io/che-incubator/che-idea:latest` which points to latest: 
    `quay.io/che-incubator/che-idea:2020.3.3`
    2. `quay.io/che-incubator/che-pycharm:latest` which points to latest: 
    `quay.io/che-incubator/che-pycharm:2020.3.5`

Similar flow has been done in chectl repository: https://github.com/che-incubator/chectl/releases

**Comment by benoitf** [comment]
yes I'm fine to your latest proposal 👍 
anyone looking at tags can easily understand what's inside

**Comment by vzhukovs** [comment]
Will update the description of issue with the latest comments
