### ISSUE TITLE
[Safari] Failed to request branding data by URL

### ISSUE THREAD

**Issue by simjnd** [eclipse-che/che#19696]
Hi,
After installing Eclipse Che on Azure with `chectl` (version 7.29) and adding the certificate to my list of registered certificates I'm faced with this error when attempting to open the dashboard: 
<img width="642" alt="Screenshot 2021-04-28 at 09 40 31" src="https://user-images.githubusercontent.com/43272781/116366707-df074d80-a806-11eb-87de-a82ed48cd6a3.png">

When attempting to go to `mydomain.com/dashboard` I'm automatically redirected to `mydomain.com/dashboard/#/`. I can find an empty object `{}` when manually querying `mydomain.com/dashboard/assets/branding/product.json` but the error looks like it is trying to get `mydomain.com/dashboard/#/assets/branding/product.json` which does not exist? (I may be completely off here)

I'm faced with the same error when trying to reach a minimal workspace created at `mydomain.com/dashboard/#/ide/admin/minimal-workspace`

I've tried to search for this error message in the existing issues and in Google but could not find anything. I can log in but can't do anything else. I've tried restarting the Eclipse Che server with chectl without success. Do you have any idea where that might be coming from?

**Comment by tolusha** [comment]
@sleshchenko Could you have a look pls?

**Comment by sleshchenko** [comment]
@simjnd Could you check browser logs and network (developer tools), which exactly URL dashboard tries to do when request product.json?

**Comment by simjnd** [comment]
I should probably have tested this before reporting the issue, but Che actually works just fine in Google Chrome. The issue I'm having happens in Safari (of course it does...)

Here are the logs:
<img width="1262" alt="Screenshot 2021-04-28 at 15 39 49" src="https://user-images.githubusercontent.com/43272781/116414282-9e282c80-a838-11eb-92e2-4002c2c0c74c.png">

And network requests:
<img width="1265" alt="Screenshot 2021-04-28 at 15 40 02" src="https://user-images.githubusercontent.com/43272781/116414298-a1bbb380-a838-11eb-97b9-754dcbf39cd0.png">

**Comment by gmawdo** [comment]
I experiencing exactly the same issue with 7.32.1 - my 'client' is saari on ipad.....I also tried firefox on the ipad with exactly the same error as reported by simjnd

**Comment by ibuziuk** [comment]
@sleshchenko we got some complaints about this particular issue on workspaces.openshift.com ? 
Will it be possible to prioritize it? At least we need to provide a clear message on UI that Safari is not yet supported

**Comment by sleshchenko** [comment]
Created a separate issue for that: Dashboard should report that it does not support Safari https://github.com/eclipse/che/issues/20123

**Comment by stbenjam** [comment]
> I experiencing exactly the same issue with 7.32.1 - my 'client' is safari on ipad.....I also tried firefox on the ipad with exactly the same error as reported by simjnd
> 
> 
> 
> ok a little more info: I tried chrome on the ipad too with the same result
> 
> 
> 
> my error is displayed in all browser (on the iPad) precisely as: Failed to fetch branding data by URL: "./assets/branding/product.json", reason: "401" returned by "undefined"."
> 
> 
> 
> given to focus here on safari being 'the issue', I then supposed perhaps it's 'the iPad' ?
> 

FWIW, any browser on the iPad is just Safari wrapped in branding, they don't allow any third-party browsers on the OS.


> 
> So I tried on my linux desktop with firefox , added the certificate authority and all works just dandy
> 
> 
> 
> Mind you my goal is to scrap my linux deskup in favour of working entirely in the cloud from the iPad.....largely my workflow now works and I'm hoping Che gives me more dev options in my 'minimal' physical hardware model :-)

**Comment by gmawdo** [comment]
thanks @stbenjam - interesting to know that firefox and chrome on iOS are simply wraps

also now using pure Theia (off backend server running container) from the iPad (Safari) without any issues - so this is very much a Che Workspace issue and the wrapped Theia IDE's work a treat when used standalone
