### ISSUE TITLE
Workspace reloading automatically after sometime

### ISSUE THREAD

**Issue by bodarajeshkumar** [eclipse-che/che#19692]
I have a custom VSCode extension added to the eclipse-che. This is working fine. There is an activate method which gets called when loading the workspace. I can also open a node-js terminal in eclipse-che to run an application loaded into explorer. so far things working fine.

Below are the problems I am seeing

1) If I leave the workspace idle for few minutes, I see the node terminals that I opened, getting closed automatically. When I try to create a new one, they are starting with some higher number than before.

For eg: If the terminal that I opened has name "nodejs terminal 1", when I check after few minutes, the terminal get closed and the new terminal that I started may have name "nodejs terminal 9". All the previous terminal processes are still  running in the background. Below are the screen shots which explains the problem clearly
Stage1: When loading
<img width="1381" alt="Screenshot 2021-04-28 at 10 22 32 AM" src="https://user-images.githubusercontent.com/82795269/116350147-0c57f980-a80f-11eb-95f9-6c09562e4e3a.png">
Stage 2: After few minutes
<img width="1243" alt="Screenshot 2021-04-28 at 10 44 35 AM" src="https://user-images.githubusercontent.com/82795269/116350151-0d892680-a80f-11eb-9718-596c0709345d.png">
Stage3: After creating new terminal
<img width="1381" alt="Screenshot 2021-04-28 at 10 44 47 AM" src="https://user-images.githubusercontent.com/82795269/116350155-0eba5380-a80f-11eb-98bc-7aff8ea55a09.png">

My question is, how can we avoid this automatic closing of terminals or how can we make the already existing terminals opened instead of creating a new terminal always. 

2) Sometimes the workspace gets reloaded automatically. Because of this, the extension activation event gets called each time the reload happens and all the actions mentioned in the method are executing again in the middle. We are seeing some unexpected behaviour because of this. Is there a way to stop reloading the workspace when it is already kept open

**Comment by skabashnyuk** [comment]
@bodarajeshkumar thank you for this report. It sounds like a bug. Could you please follow the bug template? That will help better understand the use case.

**Comment by tolusha** [comment]
@bodarajeshkumar 
I think it would be interesting to check Theia container logs.
Workspace should not reload arbitrarily, at least I am aware of that.

**Comment by bodarajeshkumar** [comment]
@tolusha Thank you. 
 I am leaving the workspace idle in the browser for sometime. Can I expect the workspace to be not reloaded even after some period of time. Will there be any anything like session timeout?

**Comment by azatsarynnyy** [comment]
@bodarajeshkumar there's an idle timeout in Che to stop the workspaces. But they shouldn't be reloaded, normally.
Could you check machine-exec container logs? I suppose there should be something related to the closed terminal sessions.

**Comment by azatsarynnyy** [comment]
We have discussed this topic internally with @RomanNikitenko and @vzhukovs this morning.
@vzhukovs told me that recently he also has faced Che page reloading, but it happened with his IDEA-based workspace. I guess it can be a Dashboard's functionality that reloads a page for refreshing a Keycloak token.
@sleshchenko any thoughts?

**Comment by bodarajeshkumar** [comment]
Is there a possibility that below error could cause workspace to reload?
level=error msg="Unable to upgrade connection to ws-conn websocket: could not find connection header with token 'upgrade'"

**Comment by sleshchenko** [comment]
Sorry for the delay, recently we got created the similar issue and after investigation, it was clear that it's nginx ingress controller that does a trick. More see https://github.com/eclipse/che/issues/19796#issuecomment-873131404

@bodarajeshkumar could you confirm or break the assumption you use nginx ingress controller?

**Comment by bodarajeshkumar** [comment]
Thank you @sleshchenko yes, It is it's nginx ingress controller that causing the issue.

**Comment by sleshchenko** [comment]
related PRs 
https://github.com/eclipse-che/che-server/pull/56
https://github.com/eclipse-che/che-server/pull/54
