### ISSUE TITLE
Avoid untrusted binary popups in vscode-java when using Lombok

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19690]
### Is your task related to a problem? Please describe.
Running the Lombok devfile will show a warning about trusting the binary: 

![Screenshot_20210426_104500](https://user-images.githubusercontent.com/6290632/116268259-26300880-a74b-11eb-830a-79aa9d6be328.png)

### Describe the solution you'd like
We should find a way to have this popup not appear, and the binary be trusted by default. The binary is installed in the sidecar at build time.

### Additional context
This happens with vscode-xml as well: https://github.com/redhat-developer/vscode-xml/blob/master/src/server/binary/binaryServerStarter.ts#L166

**Comment by benoitf** [comment]
https://github.com/redhat-developer/vscode-xml/blob/985705ebd603bd08ee8ca149484d3ea48841007a/docs/Preferences.md#trusted-binary-hashes

**Comment by sunix** [comment]
for vscode-java is done here: https://github.com/redhat-developer/vscode-java/blob/master/src/settings.ts#L141-L158

**Comment by sunix** [comment]
Filed issue in vscode-java: https://github.com/redhat-developer/vscode-java/issues/1965

**Comment by svor** [comment]
depends on https://github.com/eclipse/che/issues/20134

**Comment by nickboldt** [comment]
Note that in CRW 2.14 we will consume lombok 1.18.22 built from sources. https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-plugin-java8/build/build_lombok.sh

Not sure if that makes it easier to excempt lombok from security warning.

**Comment by rgrunber** [comment]
This should have also been fixed in https://github.com/redhat-developer/vscode-java/issues/1965 (since v0.82.0). The prompt should be ignored as long as the resource originates from outside the workspace.

**Comment by svor** [comment]
Fixed by https://github.com/eclipse-che/che-plugin-registry/pull/1060
