### ISSUE TITLE
[che-auth] - adapt che-dashboard to new authentication

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#19706]
### Is your task related to a problem? Please describe.

In new Che auth, we won't be using Keycloak as an identity/oidc provider. Instead of that, we'll use Openshift Oauth directly and whole authentication and authorization will be delegated into separate layer. That means, that Dashboard should not do anything for auth. In my POCs it was working quite well when `/keycloak/settings` returned 404. Dashboard then run in single-user mode and did not try to call keycloak or do any authentication.

### Describe the solution you'd like

I don't believe that everything will be working out of the box in this state. This issue should gather problems on dashboard side with new Che auth. Che-server will most probably need to expose some new configuration that we're running with new auth. This is not yet defined.

Known issues:
  - https://github.com/eclipse/che/issues/20071

### Additional context

epic: Authentication and authorization in Eclipse Che #19182
this issue will very much depend on che-server work https://github.com/eclipse/che/issues/19703 and deployment https://github.com/eclipse/che/issues/19705

**Comment by l0rd** [comment]
@sparkoo are you currently working on this?

**Comment by sparkoo** [comment]
I've created this issue as an umbrella for dashboard adaptation to new auth. I assumed there will be "a lot" of work needed from dashboard side, but so far it works out of the box and only issue known to me is with logout (https://github.com/eclipse/che/issues/20071). I'm closing this issue as it seems there will be no significant work needed on dashboard side.
