### ISSUE TITLE
Publish port exposed by workspace at a particular port 

### ISSUE THREAD

**Issue by lhwong** [eclipse-che/che#1971]
In Dockerfile, I specify EXPOSE 8080 to expose port 8080 for tomcat.

On Operations Perspective/Servers, the following is shown 
tomcat8  8080/tcp  192.168.1.150:32848 http://192.168.1.150:32848

Can I configure mapping using a particular port (e.g. 192.168.1.150:80) to port 8080 exposed by my workspace similar to  -p option when running docker container process? If yes, how can I do it?

**Comment by ddementieva** [comment]
Exposed ports are currently mapped to a random port from the ephemeral port range. Labeling it as enhancement.

**Comment by lhwong** [comment]
Found info on Che Workspace Port Configuration #808
