### ISSUE TITLE
Install any plain vscode extensions on existing containers of the workspace.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19727]
### Is your enhancement related to a problem? Please describe.
Installing vscode extension (that is not in the plugin registry) is quite painful at the moment: in many cases a container is required to provide the extension dependencies. The current way to handle that is for the user to create a Che plugin and restart the workspace. This is too difficult.

### Describe the solution you'd like
In many cases, the devfile of a project is defined with containers that are used for building, running the app. These containers may already contain the right dependencies and could be good enough to host a vscode extension!

The plugin view could have plain vscode ext in addition of che plugins. when a user install a vscode ext, we could ask him, in which container to start the extension and make it happen ... without restart.

### Describe alternatives you've considered
N/A

**Comment by sunix** [comment]
Related to https://github.com/eclipse/che/issues/19050

**Comment by JPinkney** [comment]
Setting as P2 for now, feel free to change it
