### ISSUE TITLE
[operator] ensure old instances are migrated to use internal services if not specified

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19726]
### Is your task related to a problem? Please describe.
New Eclipse Che instances are using by default internal services

```yaml
 # Use internal cluster SVC names to communicate between components to speed up the traffic and avoid proxy issues.
useInternalClusterSVCNames: true
```

but old clusters (having done some upgrades) may not have this parameter set and then the value is defaulted to false while we expect it should be true as well.

### Describe the solution you'd like
if the value is not defined, it should set the value to `true`, not `false`.

### Describe alternatives you've considered
N/A

**Comment by tolusha** [comment]
`UseInternalClusterSVCNames` field doesn't have `omitempty` attribute. 
It means it is defined anyway and it is set to `false` after update.

[1] https://github.com/eclipse-che/che-operator/blob/main/pkg/apis/org/v1/che_types.go#L141

**Comment by JPinkney** [comment]
Setting as P1 for now. If it's not P1 then please change the priority or if @tolusha's answer solves this then please close!

**Comment by tolusha** [comment]
We can deprecate this field and enable internal urls by default.
To allow external urls we can introduce a new field like `disableInternalClusterSVCNames`
