### ISSUE TITLE
Che Operator Security Context Defined Posture Parameters

### ISSUE THREAD

**Issue by ArvinB** [eclipse-che/che#19737]
### Is your task related to a problem? Please describe.
The securityContext under each Pod must be fully declared in order to clearly communicate the workload's security posture. In order to be declarative about their security posture, Pods must define every parameter available in its securityContext and each container's securityContext. For Pods, this includes hostNetwork, hostPID, and hostIPC. For each container, this includes privileged, readOnlyRootFilesystem, allowPrivilegeEscalation, and at least one element in capabilities.add or capabilities.drop. The runAsNonRoot and runAsUser parameters may be defined on each container individually or on the Pod to apply it to all containers. If either is not defined on a container, then it must be defined on the Pod. When linting in the context of an OpenShift cluster, runAsUser is not required. Some parameters have specific requirements regarding the acceptable values, but it is most important that each is defined in order to be declarative about the product's security posture.

[Pod Security Guidance](https://playbook.cloudpaklab.ibm.com/pod-security-guidance#linter-rule)

### Describe the solution you'd like
Missing parameters are to be added to the `securityContext`

### Additional context
Expected results are that these changes will trickle down into Red Hat CodeReady Workspaces @nickboldt and Wazi Developer for Workspaces @ArvinB

FYI @tolusha

**Comment by tolusha** [comment]
@ArvinB 
Can we close this one?

**Comment by ArvinB** [comment]
Yes
