### ISSUE TITLE
A project should be removed from devfile at using 'Remove Folder from Workspace' action  

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19730]
### Describe the bug

We should remove a project from devfile when a user applies `Remove Folder from Workspace` action.  

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace with a project
2. Select the project in `Projects Tree`
2. Apply `Remove Folder from Workspace` action using context menu.
3. You can see that the project was removed from the `Projects Tree` view.
4. Go to dashboard - the project is still in the devfile
5. Try to refresh a page with IDE - the project will be restored in the `Projects Tree` view and workspace config file.

### Expected behavior

A project should be removed from devfile.
I'm not sure if we should remove it from file system as well.
  
### Runtime
dogfooding instance

**Comment by azatsarynnyy** [comment]
> I'm not sure if we should remove it from file system as well.

It shouldn't touch a physical folder on the file system. It's just about the logical project structure and a Devfile.

**Comment by azatsarynnyy** [comment]
not a priority for the nearest future, but still relevant
