### ISSUE TITLE
Upgrade VS Code extension Apache Camel to v0.0.32

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19740]

**Comment by nickboldt** [comment]
Done downstream in https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-pluginregistry/che-theia-plugins.yaml#L366

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1783
