### ISSUE TITLE
Upgrade VS Code extension Camel K to v0.0.24

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19745]
### Is your enhancement related to a problem? Please describe.

new release available

### Additional context

new Camel K CLI 1.4.0 to use in sidecar

**Comment by l0rd** [comment]
[PR is merged](https://github.com/eclipse-che/che-plugin-registry/pull/945). Closing

**Comment by nickboldt** [comment]
Looks like Mario forgot to actually push the "close" button, so doing that now.

**Comment by nickboldt** [comment]
Done downstream in https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-pluginregistry/che-theia-plugins.yaml#L169

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1784
