### ISSUE TITLE
Further improve start-up time using the Kubernetes Image Puller - with all Che images now fully compatible

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19755]
### Is your enhancement related to a problem? Please describe.

Today, KIP can only be used with non-scratch images based on Alpine/ubuntu (Che) or ubi8-minimal/httpd (CRW).

But if we could embed a **statically compiled binary** for `sleep` into scratch images (as attempted in https://issues.redhat.com/browse/CRW-1594 without success, as that `sleep` required bash dependencies)

### Describe the solution you'd like

- [x] add sleep.go to this repo
- [x] update KIP logic to use hours instead of days as the unit to sleep (currently 30 days); this will allow the sleep binary to be as small as possible, without needing calendar/date libraries
- [ ] for Che scratch images, pull the /bin/sleep binary from the https://quay.io/repository/eclipse/kubernetes-image-puller?tag=latest&tab=tags image and use it in downstream Dockerfiles; adds <1M to image size
- [ ] for CRW scratch images, pull the /bin/sleep binary from the https://quay.io/repository/crw/imagepuller-rhel8?tag=latest&tab=tags image as an asset file, commit it to pkgs.delel, and use it in downstream Dockerfiles (cannot use 3-stage builds in Brew w/ multiple builder stages); adds <1M to image size

Once this is done, we can also:
- [ ] remove need for a Dockerfile and a rhel.Dockerfile in upstream repos, as we can now have ubi8-based go builder images, with scratch runtime images

### Describe alternatives you've considered

* Migrate all scratch images to ubi8-minimal base (adds 100M to image size)

### Additional context

* https://issues.redhat.com/browse/CRW-1594
* https://github.com/eclipse-che/che-machine-exec/pull/156
* https://github.com/redhat-developer/codeready-workspaces-images/pull/27
* https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/506/diffs#85b500d4f10d4ba3426a6b0a8f3f1706fe836928

### Release Notes Text

```asciidoc
The Kubernetes Image Puller is now able to pre-download any workspace required image on all the nodes of a Kubernetes cluster, except the operator-metadata image (which doesn't need pre-pulling).
```

**Comment by ibuziuk** [comment]
please, close this issue only once relevant docs are merged in the https://www.eclipse.org/che/docs/che-7/administration-guide/defining-the-list-of-images-to-pull/
