### ISSUE TITLE
Migrate maven projects involved in building Che server to new eclipse-che org 

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19754]
### Is your task related to a problem? Please describe.

To avoid long delays building che server due to limited GH action builder nodes allocated to the `eclipse` organization, we should migrate the che server projects to the `eclipse-che` organization.

* [ ] Migrate che server project to the new eclipse-che org

Optional, as these rarely change / need rebuilding:

* [ ] Migrate che-parent project to the new eclipse-che org
* [ ] Migrate che-dev project to the new eclipse-che org
* [ ] Migrate che-lib project to the new eclipse-che org

**Comment by flacatus** [comment]
@skabashnyuk There is already a bugzilla about migration to new organization. I guess you can continue with the thread of migrations:
Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=571958
