### ISSUE TITLE
Workspace is not restarting when prompted to restart it

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19751]
### Describe the bug
Open a fresh workspace with recommendations plug-in
expect to see new plug-ins being added and workspace restarting.

(but the workspace is not restarting)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

click on a factory link like
https://workspaces.openshift.com/#https://github.com/spring-projects/spring-petclinic

### Expected behavior
Restart is happening

### Screenshots

https://user-images.githubusercontent.com/436777/117134925-8f94c480-ada6-11eb-92d7-c94c32e03e6b.mp4

### Additional context
Browser console is not reporting any error

**Comment by ericwill** [comment]
Looks similar to https://issues.redhat.com/browse/CRW-1761

**Comment by benoitf** [comment]
yes sure but it's reproduced in che

**Comment by sleshchenko** [comment]
As far as I see, Theia sends event to Dashboard parent frame, but it for some reasons does not handles it correctly, after workspace is created with factory - nothing is happening. After I refresh a tab - workspace is stopped but not started again.
![Screenshot_20210512_142111](https://user-images.githubusercontent.com/5887312/117968436-dba7b200-b32e-11eb-9de9-3752de6e839d.png)
![Screenshot_20210512_143232](https://user-images.githubusercontent.com/5887312/117968481-e7937400-b32e-11eb-8a3b-0a82ba6a01ea.png)

**Comment by sleshchenko** [comment]
Should be backported to 7.32.x
