### ISSUE TITLE
Misleading wording when creating workspace from git repo with no devifle

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#19753]
If I create a new workspace from a factory link pointing at a repo with no devfile present i.e. `<checluster>`#https://github.com/spring-projects/spring-petclinic 

The progress page shows a confusing and inaccurate message where:
- Devfile is found as `<repo>`
- Applying devfile

<img width="768" alt="Screenshot 2021-05-05 at 13 24 19" src="https://user-images.githubusercontent.com/19860021/117142749-f9619e00-ada7-11eb-86fc-c68b50184fb6.png">

I would prefer a message like "No devfile found in `<repo>`, generating one".

That way if you are expecting to find one but for some reason its not being used... you find out sooner.

When a devfile is found you get this message:
- Devfile is found as devfile.yaml in `<repo>`

**Comment by sleshchenko** [comment]
It duplicates https://github.com/eclipse/che/issues/19312 but keeping this one since it has a bit more concrete proposal

**Comment by cccs-eric** [comment]
We just ran into this issue while troubleshooting our integration with Github.  In our case, we have a private repo containing a valid `devfile.yaml` and we thought the devfile was loaded successfully when in fact it wasn't.  This was very misleading to us.  You can have the same error message if you specify a repo that doesn't even exist:  
`http://your.che.server.com/f?url=https://github.com/i_dont_exist_as_a_user/bogus_repo`:

![image](https://user-images.githubusercontent.com/56447460/120390129-55fa9f00-c2fb-11eb-9c45-4b59f4f49500.png)

If the repository exist, creating a default devfile for it is nice.  But when it does not, it is pointless.  With this, I have one question (and that will help me understand my problem with Github integration): 

**Q:** If I'm not mistaken, this check would happen in `che-dashboard`.  Is `che-dashboard` capable of seeing a private repository (so it would need to perform an OAuth authentication with Github first)?
