### ISSUE TITLE
Ability to set resource quotas per user

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19767]
### Is your enhancement related to a problem? Please describe.

There is no way for an admin to limit the amount of memory/cpu/PV that a Che user is going to consume. That need to be done manually specifying the resources quotas at the namespace level.

### Describe the solution you'd like

The `CheCluster` CR should have a some fields to specify users quotas for CPU/memory/PV
Che server should create resource quotas when it creates the user namespace.

### Other solution

If the namespace already exist, has been created by the Che SA, and the quotas do not match, we should update the namespace quotas with the values that are in the CheCluster CR. That can be done at workspace startup or as soon as the CheCluster is updated.

### Additional context

We should wait for https://github.com/eclipse/che/issues/19717 before implementing this.
This is only applicable if a Che user correspond to Kubernetes user (for example if openshift OAuth or kubeproxy are used)  and if the namespace strategy is per user <== we should deprecate other strategies anyway.

⚠️ This is not related to organizations/teams implementations

**Comment by skabashnyuk** [comment]
I think in the context of devworkspaces it's also related to https://github.com/eclipse/che/issues/20219
