### ISSUE TITLE
Publish a latest/main devfile registry to GitHub pages

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19779]
### Is your task related to a problem? Please describe.
Currently we publish a versioned release to GitHub pages, for example: https://eclipse-che.github.io/che-devfile-registry/7.30.0/

As per [this comment](https://github.com/eclipse-che/che-devfile-registry/pull/377#issuecomment-828229306), it was suggested to publish a main/master/latest one as well, which would be updated on every commit. The `registryUrl` fields for this published version would refer to the [main published che-plugin-registry](https://che-plugin-registry-main.surge.sh/v3/plugins/).

### Describe the solution you'd like
Publish the devfile registry to GitHub pages on every commit/push to the master branch.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by l0rd** [comment]
@ericwill can you please add a link to the GH pages registry in the devfile-registry README file?
