### ISSUE TITLE
Failed to start a devworkspace via factory URL

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19788]
### Describe the bug

Failed to start a workspace via factory url   

### Che version

 - [x] nightly

### Steps to reproduce

DevWorkspace happy path tests
See logs
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/811/pull-ci-eclipse-che-che-operator-main-v7-devworkspace-happy-path/1392364571125092352

### Runtime
   - [x] Openshift (include output of `oc version`)

### Screenshots

![1111111](https://user-images.githubusercontent.com/1640675/117940713-06374200-b312-11eb-8a1f-842b152d9356.png)

### Installation method
   - [x] I don't know

### Environment
   - [x] Cloud

### Eclipse Che Logs

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/811/pull-ci-eclipse-che-che-operator-main-v7-devworkspace-happy-path/1392364571125092352/

**Comment by tolusha** [comment]
Unfortunately it can't be reproduced constantly ^(

**Comment by JPinkney** [comment]
Should be fixed by https://github.com/eclipse-che/che-dashboard/pull/243
