### ISSUE TITLE
Sometimes workspace created from devfile v2.0 won't start

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#19797]
### Describe the bug
Sometimes a workspace created from devfile v2.0 doesn't start.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Deploy Eclipse Che with `devworkspace` support enabled

```bash
$ cat patch.yaml
spec:
  devWorkspace:
    enable: true
$ chectl server:deploy --che-operator-cr-patch-yaml=patch.yaml \
                     -p openshift --no-olm-suggested-namespace \
                     -n workspaces-server
```

Devworkspace happy-path script - https://github.com/eclipse-che/che-operator/blob/main/.ci/oci-devworkspace-happy-path.sh

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift 4.7 on Openshift CI
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Wait_for_workspace_readiness (1)](https://user-images.githubusercontent.com/7760565/117837728-5d8dd180-b282-11eb-8726-55988136577c.png)

### Installation method
   - [x] chectl
   - [ ] OperatorHub
   - [ ] I don't know

###  Logs
- Openshift CI test build - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/828/pull-ci-eclipse-che-che-operator-main-v7-devworkspace-happy-path/1392482518556479488
- Eclipse Che and Devworkspace logs - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/eclipse-che_che-operator/828/pull-ci-eclipse-che-che-operator-main-v7-devworkspace-happy-path/1392482518556479488/artifacts/devworkspace-happy-path/devworkspace-happy-path/artifacts/

**Comment by sleshchenko** [comment]
duplicates https://github.com/eclipse/che/issues/19788
