### ISSUE TITLE
Keep yarn.lock dependencies in sync with the current/released version of Eclipse Che Server API

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19799]
## Summary

Just wondering why in master branch we have:

![image](https://user-images.githubusercontent.com/227597/118158577-fab74a00-b3e9-11eb-8eb6-c3c5afcd2c58.png)

And in 7.30.x we have:

![image](https://user-images.githubusercontent.com/227597/118158350-a744fc00-b3e9-11eb-991b-c201d8e2b1d6.png)

But also in master:

![image](https://user-images.githubusercontent.com/227597/118158496-d8bdc780-b3e9-11eb-93da-75acf2d2858d.png)

And in 7.30.x:

![image](https://user-images.githubusercontent.com/227597/118158442-c6438e00-b3e9-11eb-9a26-5e8259054aac.png)

Should not the same version of the API be used for the release, rather than being one release (and one .z maintenance build) behind?

**Comment by benoitf** [comment]
yes it would be better (even if for now the DTOs objects are almost never changed), but for that release process needs to be improved
before cutting a new che-theia version, yarn.lock file needs to be updated for the given `@eclipse-che/api`

so, before tagging and pushing the .x branch, we should include a `yarn upgrade @eclipse-che/api@VERSION` step to upgrade
