### ISSUE TITLE
How to run Che-Theia within the Che IDE

### ISSUE THREAD

**Issue by sboudreaux96** [eclipse-che/che#19792]
## Relevant information

Hello - I am new to Che-Theia and have gotten Che to run locally on my computer. I am able to create a workspace from the che-theia-all dev file, but cannot figure out how to run the UI through Che. It seems that there are many containers that I can use but I am not sure which one to use, and the ones I use seem to not work at all when I use yarn. Is there any place I can be directed to for help on this?

**Comment by azatsarynnyy** [comment]
Hello @sboudreaux96 
you can find the steps in this doc https://github.com/eclipse-che/che-theia/blob/master/CONTRIBUTING.md
Let me know if you have more questions.

**Comment by sboudreaux96** [comment]
@azatsarynnyy  I have ran into issues for compiling Che-Theia. I seem to have ran into a few issues (some pictures below). Please let me know if more info is needed.

![image](https://user-images.githubusercontent.com/83592423/119000600-3f4a6480-b959-11eb-82e3-99fa4690a6e7.png)

![image](https://user-images.githubusercontent.com/83592423/119001288-d7484e00-b959-11eb-9567-14c5f4fe4a3f.png)

![image](https://user-images.githubusercontent.com/83592423/119001366-e7602d80-b959-11eb-8ded-190bfbaa2b43.png)

![image](https://user-images.githubusercontent.com/83592423/119001478-ff37b180-b959-11eb-926a-7f9b1abb96a4.png)

**Comment by azatsarynnyy** [comment]
FYI: recently, the build process has been reworked slightly https://github.com/eclipse-che/che-theia/pull/955
so, try to follow the steps provided in the `How to test this PR?` PR section
