### ISSUE TITLE
Viewing or editing a file containing line 'exit' kills the terminal

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#1979]
Trying to view or edit a text file containing line 'exit' leads to closing the terminal.

**Reproduction Steps:**
1. Create a project and a text file with line 'exit'
2. Open a terminal and run Midnight commander
3. Go to the text file and press F3 or F4

**Expected behavior:**

The file must be opened for edit or view.

**Observed behavior:**

The terminal is closed.

**Che version:**    4.6.0-SNAPSHOT
**OS and version:** Linux Mint 17.1 64 bit
**Docker version:** 1.10.3
**Che install:** server (zip)

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

depends on https://github.com/eclipse/che/issues/1518

**Comment by vitaliy-guliy** [comment]
![killing-the-terminal](https://cloud.githubusercontent.com/assets/1655894/17213519/4557842e-54dd-11e6-9bc8-1589bdd6b5f5.gif)

**Comment by sixtyeight** [comment]
even simpler to reproduce, just enter `echo exit`in the shell.

Version : `4.4.2`
Revision : `c3e34e105dcb86a3`
Build Time :`2016-07-06 08:16:23`

**Comment by JamesDrummond** [comment]
@eivantsov Can we assign this to someone yet?

**Comment by AndrienkoAleksandr** [comment]
Original issue description is not actual. Actual bug(for 5.0.0-M9-SNAPSHOT): terminal should be closed, when user typed "exit" (if terminal has no background processes which can catch it).
