### ISSUE TITLE
The first try to open 'Find Command' container is failing

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#19793]
### Describe the bug
* _The first try to open 'Find Command' container is failed, container is not been opening. The next try the container is opened._

### Che version
 - [x] nightly

### Steps to reproduce
1. Create a workspace and open IDE 
2. Go to 'View ' -> 'Find Command' (Note: this action should be the first) 
3. 'Find Command' container is not opened
4. Next try opens the container 'Find Command'

### Expected behavior
* The container 'Find Comand'  should be opened from the first try

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots
* **_See the video:_**

https://user-images.githubusercontent.com/5408906/117995713-37cbff80-b34a-11eb-9fe2-0787ef914c3b.mp4

### Installation method
   - [x] chectl
`$ ./chectl/bin/chectl server:deploy --platform=minikube --telemetry=off --che-operator-cr-patch-yaml=/home/ashmaraiev/CHE_PROJECTS/che-oauth-patch.yaml --chenamespace=nightly-che`

`$ ./chectl/bin/chectl version
chectl/0.0.20210511-next.b6130d8 linux-x64 node-v12.22.1`

### Environment
   - [x] my computer
       - [x] Linux

**Comment by dmytro-ndp** [comment]
@artaleks9: it looks like Dashboard issue.
If so, appropriate issue labels are `area/dashboard`, `team/controller`, and assignee - @sleshchenko

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
I don't think it's related to Dashboard area, please see the video.

**Comment by artaleks9** [comment]
It seems, this is still actual
/remove-lifecycle stale
