### ISSUE TITLE
Fix and improve startup performances of Python workspaces using venv

### ISSUE THREAD

**Issue by cccs-eric** [eclipse-che/che#19806]
### Describe the bug

When using a python virtual environment, the vscode-python sidecar cannot activate the venv since it tries to activate it using the `source` command, which is not available in the current shell (`/bin/sh`).

### Che version
7.29.2

### Steps to reproduce

1. Create a new workspace using the built-in Python stack.
2. Once the workspace is loaded, set up a new venv using the devfile's `set up venv` command
3. Change the Python interpreter and select the venv python3 binary under `/projects/.venv/bin/python3`
4. Open the `hello-world.py` file and execute it using the green "Play" arrow located at the top-right of the editor
5. You should see the following error:
```
$ source /projects/.venv/bin/activate
/bin/sh: 1: source: not found
$ /projects/.venv/bin/python3 /projects/python-hello-world/hello-world.py
Hello, world!
```

### Expected behavior
I should be able to run `hello-world.py` using the devfile command and also the built-in run button of the editor.  But to do so, it needs to activate the venv associated.

Not sure what would be the best solution, but I can see:

1. Change the default shell of the sidecar to be `bash`, so `source` can be used
2. Change the way the venv is activated by using `.` instead or `source`

### Screenshots
![image](https://user-images.githubusercontent.com/56447460/118276828-15df9380-b496-11eb-8801-3faebe3179e9.png)

### Release Notes Text

The default Python image now uses bash as the default shell and `venv` runs successfully. The startup time of an existing workspace has been significantly reduced for the Python getting started example with an update to persist `venv` folder.

**Comment by ericwill** [comment]
> Change the default shell of the sidecar to be bash, so source can be used

I think this is preferable. The convention is to use source (at least from what I've read).

**Comment by ericwill** [comment]
@sunix this should be handled by your current work, yes?

**Comment by sunix** [comment]
@ericwill yes this is related although I did not faced that issue. The plugin sidecar is using `sh` by default, but as far as I remember, the dev container was OK. i will have a look while updating the devfiles with my current work.

**Comment by l0rd** [comment]
@ericwill can you please review if that fix will be ported downstream (and update the new and noteworthy label if it won't)?

**Comment by ericwill** [comment]
> @ericwill can you please review if that fix will be ported downstream (and update the new and noteworthy label if it won't)?

It won't be making it for 2.9 but it will make it for 2.10.

**Comment by l0rd** [comment]
> It won't be making it for 2.9 but it will make it for 2.10.

`new&noteworthy` label is correct but the we need to set the right milestone then.

**Comment by ericwill** [comment]
I have also filed a JIRA to make it more clear (this fix + Jupyter notebooks work): [CRW-1880](https://issues.redhat.com/browse/CRW-1880)
