### ISSUE TITLE
Task terminal not revealed when started from the 'My Workspace view'

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19805]
### Describe the bug
Regression: when we start a task from the `My workspace view`, the task output view is not showing up. It works when starting a task from the command palette.

### Che version

 - [x] latest 7.30.1
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a workspace with Che commands
2. Open the my workspace view
3. Try to run any of the task from the view
4. The task output view is not showing up
5. opening a new terminal will show the task running in another tab.

### Expected behavior
Task ouput should be displayed in the bottom view.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

https://user-images.githubusercontent.com/650571/118274546-8baf2380-b4c5-11eb-9c90-bccc59bc727d.mp4

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by sunix** [comment]
upstream issue: https://github.com/eclipse-theia/theia/issues/9605

**Comment by tsmaeder** [comment]
@sunix since upstream is fixed, can we close this one?

**Comment by sunix** [comment]
ok but we should revert my quickfix so https://github.com/eclipse-che/che-theia/pull/1138

**Comment by tsmaeder** [comment]
Does is make a difference?

**Comment by sunix** [comment]
@tsmaeder Yes it maybe a corner case, but with the revert, we would make sure the task is executed in the right container https://github.com/eclipse-che/che-theia/blob/d35f8a33f9bcb859a732bcaa63f0b739da239031/plugins/containers-plugin/src/containers-tree-data-provider.ts#L293

**Comment by tsmaeder** [comment]
Makes sense, will you open a PR, then?

**Comment by vitaliy-guliy** [comment]
Reverted by https://github.com/eclipse-che/che-theia/pull/1199
