### ISSUE TITLE
Sometimes devworkspace-che deployment fails because of docker.io '...pull rate limit' for `traefik` image

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#19814]
### Describe the bug
Sometimes `devworkspace-che` deployment fails because of docker.io '...pull rate limit' for `traefik` image(see screenshot). 
Path to  `traefik` image sets in [combined.yaml](https://github.com/che-incubator/devworkspace-che-operator/blob/main/deploy/deployment/openshift/combined.yaml#L521) file. Also we already have `traefik:v2.2.8` image on quay.io - https://quay.io/repository/eclipse/che--traefik?tab=tags and it can be used to fix this issue.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Eclipse Che with `devworkspace` support enabled

```bash
$ cat patch.yaml
spec:
  devWorkspace:
    enable: true
$ chectl server:deploy --che-operator-cr-patch-yaml=patch.yaml \
                     -p openshift --no-olm-suggested-namespace \
                     -n workspaces-server
```
2. Check that both pods in devworkspace-che deployment started 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/7760565/118494264-a59d7000-b72a-11eb-82cd-d9b47d38c164.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by benoitf** [comment]
looks like a missing item of  https://github.com/eclipse/che/issues/19431
