### ISSUE TITLE
Add an ability to use kubernetes API proxy on Kubernetes

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19813]
### Is your task related to a problem? Please describe.
Currently, kubernetes API proxy supports only OpenShift with OAuth enabled.
And this issue is about enabling an ability to use Kubernetes Proxy on Kubernetes.

### Describe the solution you'd like
Since we don't have in the session(browser) the identity with which we can access K8s API, proxy would need use ServiceAccount's identity, but to avoid privileges escalation it would additionally need to check if users accessing their default namespace, which should be only available.

### Describe alternatives you've considered
It can be done on Che Server K8s API proxy that we have
Or dashboard backend which is not in a place yet

**Comment by skabashnyuk** [comment]
API is available in k8s. I want to create a separate issue for devworkspace on k8s.
