### ISSUE TITLE
Upgrade Tooling for Apache Camel K VS Code extension to v0.0.25

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#19811]
new release available

### Release Notes Text

Upgrade Tooling for Apache Camel K VS Code extension to v0.0.25

**Comment by apupier** [comment]
nota: a new menu for debuggign is availabel on right-click on deployed Integration. it won't be working as VS Code Java debug is missing from the stack/dependencies

**Comment by benoitf** [comment]
done

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1876
