### ISSUE TITLE
Bottom panel is not displayed at running a task

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19825]
### Describe the bug

Bottom panel with a task's output is not displayed when a user runs a task from the `Workspace` panel.
For a user it looks like the task was not started.

The panel is displayed when user starts a task from the `Terminal` => `Run Task` menu, but doesn't from the `Workspace` panel. 

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Expected behavior

The bottom panel with the task's output should be displayed when a user runs a task from the `Workspace` panel.

### Runtime
   dogfooding instance

### Screenshots

![tasks_bottom_panel](https://user-images.githubusercontent.com/5676062/118791588-82e09800-b89f-11eb-85a4-dd64e7d3ed01.gif)

**Comment by vitaliy-guliy** [comment]
Link with https://github.com/eclipse/che/issues/19805
