### ISSUE TITLE
Can't establish connection to rsync server. Cause:[object Event] - Che Latest version 

### ISSUE THREAD

**Issue by USTQE** [eclipse-che/che#19823]
## Summary
We are getting a popup error in the Eclipse Che theia editor after the workspace creation 

Can't establish connection to rsync server. Cause:[object Event] 

![image](https://user-images.githubusercontent.com/55679958/118774314-52026200-b8a3-11eb-8ea0-6edbf04dd9dc.png)

Also, we are getting Emphemeral Mode even after selecting Persistent mode while creating the workspace. 

![image](https://user-images.githubusercontent.com/55679958/118774367-6181ab00-b8a3-11eb-8ef8-e06940c55b35.png)

**Comment by davidfestal** [comment]
Could you please precise some context information:
- the version of Che
- the infrstructure on which Che has been installed (Kubernetes, OpenShift)

Thanks.

**Comment by AbhiAuto** [comment]
@davidfestal 

Please find the details below. 

Che version: latest (7.31.0)
Deployed on Azure Kubernetes (AKS) Using helm chart  
Kubernetes version: 1.18.17, ​16Gb 4CPU
Storage for a workspace -10GB

**Comment by azatsarynnyy** [comment]
Hello,
Could you also check the browser's console logs? There should be some related info.

**Comment by azatsarynnyy** [comment]
I've sent a PR for a better message on rsync server connection errors https://github.com/eclipse-che/che-theia/pull/1111

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse-che/che-theia/pull/1111
