### ISSUE TITLE
Deleting workspace doesn't work properly from Dashboard UI

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#19833]
### Describe the bug
* _Deleting workspace doesn't work properly using Dashboard UI - the workspace is still present. Only after refresh a browser page the workspace will be disappeared from dashboard._

### Che version
 - [x] nightly

### Steps to reproduce
1. Run a workspace
2. Return back from IDE to Dashboard
3. Try to delete the workspace using Dashboard UI
4. Only after refresh a browser page, the workspace will be disappeared from dashboard

### Expected behavior
* The workspace should be disappeared immidiately after deleting

### Runtime
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots
* **Here is the video**

https://user-images.githubusercontent.com/5408906/118977652-1341da00-b97f-11eb-9290-dd54a8b29a52.mp4

### Installation method
   - [x] chect
     * `chectl/0.0.20210511-next.b6130d8 linux-x64 node-v12.22.1`
     * `server:deploy --k8spodreadytimeout=600000 --k8spodwaittimeout=600000 --k8spoddownloadimagetimeout=600000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/mnt/hudson_workspace/workspace/Che/e2e/minikube/basic/eclipse-che/custom-resource-patch.yaml --telemetry=off --chenamespace=eclipse-che`

**Comment by sleshchenko** [comment]
Che Server already provides information about scm repo, like repo location, branch. Dashboard can start using it https://github.com/eclipse-che/che-server/pull/5
