### ISSUE TITLE
AtlasMap VS Code Extension

### ISSUE THREAD

**Issue by sboudreaux96** [eclipse-che/che#19839]
Hello - I am trying to get the AtlasMap VS Code Extension to run in Che by following other examples to use plugins/extensions in Che but I am having no luck. I have been able to get it running in VS Code and Theia but I am struggling with Che. What are the steps I could try to get it to run?

**Comment by apupier** [comment]
@sboudreaux96 you can have a look to previous (but old) attempts https://github.com/eclipse/che/issues/13922

Please share the experience. What have you already tried? Which errors do you have?
