### ISSUE TITLE
[UD] upgrade patternfly/react-core

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#19832]
### Is your task related to a problem? Please describe.

The latest versions of patternfly/react-core provide the ability to simply and accurately implement designs made by the UX team.

### Describe the solution you'd like

Contribute to ClearlyDefined, or get approved CQ for this dependency, upgrade dependency and provide necessary fixes.

### Additional context

https://github.com/eclipse-che/che-dashboard/pull/246#pullrequestreview-664230513

**Comment by sleshchenko** [comment]
fixed by https://github.com/eclipse-che/che-dashboard/pull/268
