### ISSUE TITLE
Javascript errors while building from source

### ISSUE THREAD

**Issue by helderm** [eclipse-che/che#1984]
Hi everyone,

I'm having a hard time building a Che binaries from source which works flawlessly, I'm getting several Javascript errors as can be seen in the attached screenshot.
I started noticing it when it got stuck while trying to create a new workspace and project.
I checked out both 4.4.0 and 4.5.1 tags from Che repo, did a build with Docker as specified in the tutorials that worked with no indication of errors, and ran the binary in the `assembly-main`.

**Reproduction Steps:**
1. Checkout tag 4.4.0 from repo

``` bash
git checkout tags/4.4.0
```
1. Build with Docker

``` bash
docker run -it --rm --name build-che -v "$HOME/.m2:/home/user/.m2" -v "$PWD":/home/user/che-build -w /home/user/che-build codenvy/che-dev mvn -DskipTests=true -Dgwt.compiler.localWorkers=2 -T 1C -Dskip-validate-sources -Denforcer.skip=true clean install
```
1. Open `http://localhost:8080` using Firefox 47 or Chrome 52 for Linux
2. Open the web console and check the errors

**Expected behavior:**

Expected that I would be able to create workspaces and projects, but I was unable to do so, several Javascript errors are ocurring even though the build was successfull

**Che version:**    4.4.0 (also tried 4.5.1 with no luck)
**OS and version:** `Linux trusty 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
**Docker version:** Docker version 1.11.2, build b9f10c9
**Che install:**    Built from docker image `codenvy/che-dev`, image ID `1f9ad2e2af4d`
**Java JDK:** Oracle 1.8

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No] Yes
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes

![bug_che](https://cloud.githubusercontent.com/assets/1608228/17215366/ee990a9a-54dc-11e6-8c3f-d83d0b075618.png)

**Comment by TylerJewell** [comment]
@helderm - I just did a build of Che from the tagged master and could not reproduce this.  So investigating this will be fun :).

Have you tried just building the source with maven? I am wondering if there is some platform-specific regression from the che-dev docker image. 

```
cd /assembly/assembly-main
mvn clean install
```

**Comment by ghost** [comment]
@helderm have you used Che before? Same thing if you download binaries directly? I'd suggest trying again in an incognito tab, of course if you used to run Che before on your machine.

**Comment by helderm** [comment]
I had it working at some point, I even went through the plugin tutorial after a lot of tinkering. But now I keep getting those Javascript errors even after a clean build. I tried an incognito window in Firefox and it the same problem happened. I asked for a colleague to access it for the first time in his browser, and the same thing happened, so I guess it is not a browser cache problem. I tried using another Ubuntu-based server for building to no avail.
I noticed some error logs during the "Compiling permutations" part which I guess is related to GWT. I have no idea why these errors are happening since as I said I cloned the source code clean from 4.4.0 tag.
I attached the build log, I hope it is helpful.

[build.txt](https://github.com/eclipse/che/files/390707/build.txt)

**Comment by ghost** [comment]
@helderm do you havw the same issue when running 4.5.1 binaries which you can download here https://install.codenvycorp.com/che/eclipse-che-latest.zip?

Can you also try checking out 4.5.1 and doing the same?

**Comment by helderm** [comment]
I tried 4.5.1 today, and now it seems to be working. I don't think I did anything different than using this newer tag, I compiled the same way with the Docker image.
Maybe as @TylerJewell said it is some regression error with the image itself? Does your CI workflow also tests and updates the Docker image? As a suggestion, I'd add a tag to the of image corresponding to the Che version which is supported by it, I noticed that today you only have the `latest` and `nightly` tags assigned to it. That would also help the plugin developers who are building with Docker who doesn't want to update the core version due to API incompatibilities, else I'd have to upload the image to my own Docker Hub just to be safe.

**Comment by ghost** [comment]
@helderm I do not think there's any regression since I tried both tags.

**Comment by helderm** [comment]
The image ID that I had at that point is `1f9ad2e2af4d`, which differs from the current one at Docker Hub, were any changes made to the Dockefile that generates this image? I can only see that `che-dev` Dockerfile was added to the repo 2 weeks ago by de60983, but nothing else.
Anyway, matter of fact the bug happened as can be seen in the screenshot, and the build was successful as can be seen in the logs, everything else is just speculation on my part trying to help you guys figure out what may have happened.

**Comment by ddementieva** [comment]
@helderm Nightly image is built every day, latest - on the release day. This explains why IDs differ.

**Comment by TylerJewell** [comment]
@helderm - thanks for the hash codes.  There have been a significant number of changes made since the hash id you were using. It has to do with the introduction of new launcher packages as docker images.  I'm really glad that everything is resolved here.  I am going to close the issue.
