### ISSUE TITLE
Upgrade the Python plugin with the latest mspython extension

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19843]
### Is your task related to a problem? Please describe.
Current ms-python extension version is 2020.7.94776.

### Describe the solution you'd like
New version could be used: https://github.com/microsoft/vscode-python/releases/tag/2021.5.842923320
Beware that in the new versions, jupyter notebooks are supported in a separate vscode extension: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by miboettc** [comment]
Are there any updates regarding this issue? Meanwhile the current python plugin version (2020.7.94776) is almost two years old and since then there have been > 20 releases of the plugin.
