### ISSUE TITLE
How to configure docker engine inside eclipse-che environment

### ISSUE THREAD

**Issue by amoldeshpande05** [eclipse-che/che#19856]
I have a mac os and I have installed eclipse che in my local machine using chectl inside docker-desktop
using command
`chectl server:deploy --platform=docker-desktop --installer=helm`

`chectl server:start`

I've built a custom recipe using a docker file using image docker:dind and I've pushed it to a docker hub and 
my devfile looks like this where amoldeshpande/custom-node-test is my docker file having docker:dind pushed to dockerhub.
`apiVersion: 1.0.0
metadata:
  name: test
components:
  - mountSources: true
    endpoints:
      - name: test
        port: 3000
    memoryLimit: 512Mi
    type: dockerimage
    alias: nodejs
    image: amoldeshpande/custom-node-test`

Now when I run the docker command inside the eclipse che workspace 
`/$ docker images ` 

I get following exception

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` 

I found out that it needs privileged access to run docker:dind inside eclipse che so I edited the che deployment file

`kubectl edit deployment che  -n eclipse-che` 

and I added 

securityContext:
     privileged: true

`kubectl rollout restart deployment/che -n eclipse-che` 
And still, I get the same error. Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Can anyone help me here?

**Comment by ibuziuk** [comment]
@vitaliy-guliy I recall that you did some experiments with docker / buildah inside Che. Could you please comment on that?

**Comment by vitaliy-guliy** [comment]
It's difficult to answer right now as it was a year ago. But at that moment we were able to build images with buildah on local minikube deployment. I will try find my demo and steps how we did that and write here.

**Comment by amoldeshpande05** [comment]
@vitaliy-guliy Any update on this?

**Comment by vitaliy-guliy** [comment]
@amoldeshpande05
This is video demonstrating how we did that https://www.youtube.com/watch?v=pNjTmjhnGJw
There is `buildah` plugin, with which you could try to build your dockerfile.
```
  - id: containers/buildah/latest
    type: chePlugin
```

**Comment by amoldeshpande05** [comment]
@vitaliy-guliy Thank you, it works fine, any alternative to kubectl on eclipse che?

**Comment by vitaliy-guliy** [comment]
@amoldeshpande05 I forgot to mention the `buildkit`. I believe it could work on openshift. But, as with buildah, we only managed to run it on the minikube.

demo video: https://www.youtube.com/watch?v=6gK7EA_JGec

**Comment by amoldeshpande05** [comment]
Thanks, @vitaliy-guliy This is working as expected.
