### ISSUE TITLE
What purpose does eclipse/che repo serve, now that the server has moved to eclipse-che/che-server?

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19851]
## Summary

After lengthy discussion on slack, we still have an unresolved question caused by the [removal of che server](https://github.com/eclipse/che/commit/528913b1a50b33513ba520b52a98f88c7059dfd6) from [eclipse/che](https://github.com/eclipse/che) to [eclipse-che/che-server](https://github.com/eclipse-che/che-server).

All that's left in there are:
* e2e tests
* readme
* issue tracker + PR template
* https://github.com/eclipse/che/blob/main/.repositories.yaml
* other docs re: contributing, code of conduct
* outdated numbering doc (last update 5 yrs ago)
* outdated changelog (las update 2 years ago
* outdated wiki (list of labels is no longer accurate)

Should some of these items be moved to a new repo? For example...
- [ ] e2e tests could go into che-operator or chectl or [new repo, che-tests](https://issues.redhat.com/browse/CRW-1732)
- [ ] readme w/ links to eclipse.org could go into che-docs

**Comment by ibuziuk** [comment]
@nickboldt please put the appropriate labels to the issue
