### ISSUE TITLE
Adapt Che-Theia to upstream changes (Tasks)

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19866]
### Is your task related to a problem? Please describe.
There are breaking changes made in upstream Theia by the commit https://github.com/eclipse-theia/theia/pull/9409/commits/db778876b8842c0fda3e7bc307c4cad9b80fcde7
It breaks Che-Theia build.

### Describe the solution you'd like
Need to adapt Che-Theia to the upstream changes.

**Comment by zWingz** [comment]
it throw error in tag `7.31.2` and `7.32.0` when i run `yarn`, how to fixed it ?

**Comment by benoitf** [comment]
I think some changes need to be backported to 7.32.x branch
probably you could disable tests (run the command by prefixing by SKIP_TEST like `SKIP_TEST=true yarn`)

**Comment by zWingz** [comment]
@benoitf i have run `export SKIP_LINT=true SKIP_TEST=true SKIP_FORMAT=true` before run `yarn`, but it throw err in `compile` stage

**Comment by benoitf** [comment]
@zWingz I think the docker build is at least working, could you try from root folder

```
./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
```

**Comment by zWingz** [comment]
@benoitf thanks.

**Comment by benoitf** [comment]
@zWingz I think the release script is not picking-up the sha1 of build.include is set but take the current sha1


you may replace all `1.15.0-next.af9b883d` occurence in package.json by `1.14.0-next.d734315e` for 7.32.x

**Comment by zWingz** [comment]
@benoitf Do i need to replace all `1.14.0-next.bb87e69d` by `1.14.0-next.2eb4319` for `7.31.2` ?

**Comment by benoitf** [comment]
@zWingz https://github.com/eclipse-che/che-theia/pull/1151

**Comment by benoitf** [comment]
ah for 7.31.2 yes you need to match https://github.com/eclipse-che/che-theia/blob/7.31.x/build.include#L17 (so you're correct)

**Comment by zWingz** [comment]
@benoitf thanks very much
