### ISSUE TITLE
Che service account cannot delete PVC when Che is deployed with the operator

### ISSUE THREAD

**Issue by dkwon17** [eclipse-che/che#19867]
### Describe the bug
It seems that the che service account can view and create PVCs but cannot delete them when Che is deployed with the operator. This happens regardless of the [PVC storage strategy](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-storage-strategies/#storage-strategies-for-che-workspaces_che).

### Che version
![image](https://user-images.githubusercontent.com/83611742/119570733-8633c200-bd7e-11eb-9483-3956c83a6b0a.png)

### Steps to reproduce
1. Start minikube and deploy Che with the operator with `chectl`
```
$ minikube start --addons=ingress --vm=true --memory=8192
$ chectl server:deploy --platform minikube
```

2. Create a workspace, which creates a PVC (here the PVC strategy is `common`) in the `admin-che` namespace:
![image](https://user-images.githubusercontent.com/83611742/119572172-5b4a6d80-bd80-11eb-9ad0-cb56f9e9e4d6.png)

3. Try to delete the PVC
```
oc project admin-che
oc delete pvc claim-che-workspace
```
Which results in the following:
```
Error from server (Forbidden): persistentvolumeclaims "claim-che-workspace" is forbidden: User "system:serviceaccount:eclipse-che:che" cannot delete resource "persistentvolumeclaims" in API group "" in the namespace "admin-che"
```

### Expected behavior
PVC should be deleted.

### Version output
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
Output of `oc version`:
```
Client Version: 4.7.11
Kubernetes Version: v1.20.2
```
Output of `minikube version`:
```
minikube version: v1.20.0
commit: c61663e942ec43b20e8e70839dcca52e44cd85ae
```
Output of `chectl version`:
```
chectl/7.30.2 darwin-x64 node-v12.22.1
```

### Environment
   - [x] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS

### Additional context
This issue was found while testing https://github.com/eclipse/che/pull/18713 with a more recent version of Che and Che-operator.

**Comment by ibuziuk** [comment]
It looks like Che SA has no permissions to remove PVC. I suspect that the side-effect is that if the `per-workspace` PVC strategy is used PVC deletion will fail with the permission issues. Looks like this change has been introduced as part of the https://github.com/eclipse-che/che-operator/pull/772 cc: @tolusha 


[1] https://github.com/eclipse-che/che-operator/blob/main/pkg/controller/che/workspace_namespace_permission.go#L206-L208

**Comment by ibuziuk** [comment]
@dkwon17 could you please confirm that this issue is operator-specific and not reproducible against the helm installer. According to the chart che SA should have the cluster admin permissions when using this installation method - https://github.com/eclipse-che/che-server/blob/main/deploy/kubernetes/helm/che/templates/cluster-role-binding.yaml#L19

**Comment by dkwon17** [comment]
Yes, I could not reproduce this when using the helm installer (`chectl server:deploy --platform minikube --installer helm`).
