### ISSUE TITLE
On workspace start error, "Start Workspace" dialog covers error dialog

### ISSUE THREAD

**Issue by jelazos7** [eclipse-che/che#1987]
When a workspace fails to start, a "Start Workspace" dialog pops up, covering the error dialog. You cannot focus on any other dialog or any other part of the interface. Clicking "Create" or "Start" causes the dialog to flicker.

Environments: Public beta, latest che docker image as of the time of this post. Google Chrome

![image](https://cloud.githubusercontent.com/assets/1299004/17229668/b1e439d0-54e6-11e6-830b-3a7fef354cd1.png)

Steps to reproduce:
- Use a custom stack with an invalid command, e.g. VOLUME.
- Attempt to create the workspace

**Comment by ghost** [comment]
Confirmed. Labeling as bug.

**Comment by JamesDrummond** [comment]
@RomanNikitenko @vparfonov Please provide status label.

**Comment by bmicklea** [comment]
@vparfonov - this was merged into 4.7, correct?
