### ISSUE TITLE
The Devworkspace Che Operator and Che operator have different CRDs Group names

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#19870]
### Describe the bug

DevWorkspace Che Operator use CRD group name `che.eclipse.org`[1] which is different from the CRD api group used by Che Operator `org.eclipse.che`[2].
1. https://github.com/che-incubator/devworkspace-che-operator/blob/main/deploy/deployment/openshift/objects/chemanagers.che.eclipse.org.CustomResourceDefinition.yaml#L12
2. https://github.com/eclipse-che/che-operator/blob/main/deploy/crds/org_v1_che_crd.yaml#L16

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by metlos** [comment]
Yep, `CheManager` is going away and we're going to settle on `CheCluster` and hence keep `org.eclipse.che` group even though it doesn't conform to the Kubernetes naming conventions..
