### ISSUE TITLE
Happy path test are failing on "Validation of debug functionality" because  there is no debug configuration

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#19887]
### Describe the bug
Happy path test are failing on "Validation of debug functionality" because of there is no debug configuration:
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/37/console

Test error log:
```
08:19:33            ▼ DebugView.clickOnDebugConfigurationItem "Debug (Attach) - Remote (petclinic)"
08:19:33              ‣ DriverHelper.waitAndClick By(xpath, //select[contains(@class,'debug-configuration')]//option[text()='Debug (Attach) - Remote (petclinic)'])
08:19:33              ‣ DriverHelper.waitVisibility By(xpath, //select[contains(@class,'debug-configuration')]//option[text()='Debug (Attach) - Remote (petclinic)'])
08:19:34              ‣ DriverHelper.waitAndClick - Polling timed out attempt #1, retrying with 1000ms timeout
08:19:34              ‣ DriverHelper.waitVisibility By(xpath, //select[contains(@class,'debug-configuration')]//option[text()='Debug (Attach) - Remote (petclinic)'])
08:19:35              ‣ DriverHelper.waitAndClick - Polling timed out attempt #2, retrying with 1000ms timeout
08:19:35              ‣ DriverHelper.waitVisibility By(xpath, //select[contains(@class,'debug-configuration')]//option[text()='Debug (Attach) - Remote (petclinic)'])
08:19:36              ‣ DriverHelper.waitAndClick - Polling timed out attempt #3, retrying with 1000ms timeout
08:19:36      1) Run debug and check application stop in the breakpoint
08:19:36    [ERROR] CheReporter runner.on.fail: Validation of debug functionality Run debug and check application stop in the breakpoint failed after 11884ms
08:19:36  
08:19:36  
08:19:36    21 passing (13m)
08:19:36    1 pending
08:19:36    1 failing
08:19:36  
08:19:36    1) Validation of debug functionality
08:19:36         Run debug and check application stop in the breakpoint:
08:19:36       TimeoutError: Exceeded maximum clicking attempts, the 'By(xpath, //select[contains(@class,'debug-configuration')]//option[text()='Debug (Attach) - Remote (petclinic)'])' element is not clickable
08:19:36        at DriverHelper.waitAndClick (/tmp/e2e/utils/DriverHelper.ts:301:15)
08:19:36        at process._tickCallback (internal/process/next_tick.js:68:7)
08:19:36  
```

![screenshot-Run_debug_and_check_application_stop_in_the_breakpoint (4)](https://user-images.githubusercontent.com/1197777/119942695-cf605d80-bf9a-11eb-81ad-567ded2507e1.png)

Screencast: 

https://user-images.githubusercontent.com/1197777/119943605-eb183380-bf9b-11eb-819e-b6552623e610.mp4

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run Happy path tests.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [x] other: CRW CCI

### Eclipse Che Logs
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/37/artifact/logs-and-configs/workspace-logs/

**Comment by tsmaeder** [comment]
@dmytro-ndp on Firefox,/Windows, it says "video can't be played becuase the file is corrupt" in your screencast above.

**Comment by dmytro-ndp** [comment]
@tsmaeder: thanks for information.
If it's a blocker, I can upload screencast to youtube.

**Comment by dmytro-ndp** [comment]
The issue is reproduced from time to time, e.g. https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-tests-pr-check/46/console

It looks like a product flakiness, not the test flakiness.

**Comment by dmytro-ndp** [comment]
The issue has been reproduced in Eclipse Che nightly tests [1], and is constantly reproducing in Eclipse Che PR check today  [2].

[1] https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/197/console
[2] https://github.com/eclipse/che/pull/20002#issuecomment-864022501

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
I see on the video for the `Happy Path` tests `No Configurations` item and there is no refreshing a page.
Does it mean that the workaround is not working?

Please see the report [here](https://github.com/eclipse-che/che-theia/pull/1157#issuecomment-874208806)

**Comment by dmytro-ndp** [comment]
@RomanNikitenko : thank you for information!

**Comment by dmytro-ndp** [comment]
Second try: https://github.com/eclipse/che/pull/20079
