### ISSUE TITLE
Recommendation plug-in provides wrong information

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19883]
### Describe the bug
After starting the workspace I see an Info window with recommended plugins and the list of plugins contains vscode-xml plugin 3 times. Also if recommendation plugin provides more than 1 plugin they should be separated by space.
![screenshot-che-eclipse-che 192 168 99 211 nip io-2021 05 27-17_27_46](https://user-images.githubusercontent.com/1271546/119844219-eb1f2180-bf10-11eb-91fa-3c0bf972ac91.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace from the devfile https://github.com/eclipse/che/blob/main/tests/e2e/files/happy-path/happy-path-workspace.yaml
2.  Wait for the recommendation window
### Expected behavior
Recommendation window should contain only one vscode-xml plugin

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by ericwill** [comment]
cc @benoitf

**Comment by benoitf** [comment]
I missed the ping !
