### ISSUE TITLE
Implement Account API

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#1989]
Epic link https://github.com/codenvy/codenvy/issues/409

Implement Account API

As result of this issue there should be implemented API that will allow users to:
- create, remove workspace which belong to user (personal account)
- fetch workspaces which belong to some personal account by account name

**Comment by TylerJewell** [comment]
@sleshchenko - the epic link provided doesn't seem to be the right one.  Can you update please.

**Comment by sleshchenko** [comment]
@TylerJewell thanks for remark, fixed.

**Comment by bmicklea** [comment]
@sleshchenko is this closed?  The epic link you've referenced has been closed already.
