### ISSUE TITLE
Rename/replace nightly build of che-server with on-push workflow

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19894]
### Is your task related to a problem? Please describe.

Today we have https://github.com/eclipse-che/che-server/blob/main/.github/workflows/nightly-build.yml which runs daily, but most other projects are doing continuous integration and push new builds on every commit. 

### Describe the solution you'd like

Instead we should have a per-commit on_push workflow. This workflow should be updated and renamed/relabelled accordingly.

For example, che-theia does this:

```
name: Build & Publish `next`

on:
  push:
    branches:
      - master
```
-- https://github.com/eclipse-che/che-theia/blob/master/.github/workflows/build-publish-next.yml#L10-L15

### Additional context

See also https://github.com/eclipse/che/issues/19291

**Comment by mkuznyetsov** [comment]
done as part of https://github.com/eclipse/che/issues/19291
