### ISSUE TITLE
Globalization Framework for Language Support

### ISSUE THREAD

**Issue by ArvinB** [eclipse-che/che#19900]
### Is your enhancement related to a problem? Please describe.
Globalization strategy ensures that offering teams can consistently and efficiently deliver solutions, products, and platforms that support the language and cultural needs of our clients worldwide. Without sufficient globalization, our clients may not be able derive business value from our offerings.

### Describe the solution you'd like
A framework to support internationalization / globalization for any language that can be added.

These are the 6 core languages to support at a minimum:
- English
- German
- Spanish
- French
- Italian
- Japanese

These are the 6 core languages to support globalization.

### Describe alternatives you've considered
None, but open to ideas.

### Additional context
This enhancement request is coming from IBM with a request to implement by June 1, 2022.

**Comment by tolusha** [comment]
I think it is about providing support for internalization and allows anyone to contribute any language he wants.

**Comment by ArvinB** [comment]
@tolusha Agreed, a framework to support internationalization. Updating the title and description to reflect this.

**Comment by l0rd** [comment]
@ArvinB that should be decomposed in multiple (independent) subtasks, each one dedicated to the i18n of the messages/UI of one of Che components:
- chectl
- Che dashboard
- Che operator
- DevWorkspaces operator
- Devfile and Plugin registries metadata
- Che Theia

@sympatheticmoose I am labelling that as a `roadmap/1-year` epic.

**Comment by sympatheticmoose** [comment]
@ArvinB is this something which IBM are able to assist with implementing?

**Comment by ArvinB** [comment]
> @ArvinB is this something which IBM are able to assist with implementing?

@sympatheticmoose 
Yes we plan on doing this.

**Comment by stevisco** [comment]
Isn't this the same as https://github.com/eclipse-theia/theia/issues/1327 ? we at Arduino are working with Typefox to implement 1327 and there is a good amount of work done in PR https://github.com/eclipse-theia/theia/pull/9538. We are hoping this PR makes some progress soon...

**Comment by azatsarynnyy** [comment]
> Isn't this the same as [eclipse-theia/theia#1327](https://github.com/eclipse-theia/theia/issues/1327) ?

@stevisco you're right, https://github.com/eclipse-theia/theia/issues/1327 is the same but it's specific for upstream Theia.
This epic is a general one - for all Che components. See https://github.com/eclipse/che/issues/19900#issuecomment-853157613
