### ISSUE TITLE
Why in Che-Theia do we remove all electron-browser module but not electron module ?

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#19902]
## Summary

![image](https://user-images.githubusercontent.com/13031838/120445390-2612d080-c3bb-11eb-8824-51ef02af1b3f.png)

**Comment by l0rd** [comment]
@zWingz I suppose you are referring to [Che Theia Dockerfile](https://github.com/eclipse-che/che-theia/blob/master/dockerfiles/theia/Dockerfile#L69) right?

@azatsarynnyy @benoitf can you help @zWingz?

**Comment by benoitf** [comment]
We remove the source code depending on electron. Maybe you've a more specific issue or a problem that you're trying to solve ?

**Comment by zWingz** [comment]
@benoitf I just don't understand why we only remove 'electron-browser' but not 'electron-node'
`che-theia` run in browser, all of electron module is useless ?
![image](https://user-images.githubusercontent.com/13031838/120574931-c1a35000-c452-11eb-9b28-e3c7f117858f.png)

**Comment by zWingz** [comment]
@benoitf Hi, Can you solve my question ?
