### ISSUE TITLE
Rework the openshift-ci jobs for using the "next" tag

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#19903]
### Is your task related to a problem? Please describe.

Building of the **quay.io/eclipse/che-e2e** image was reworking for using
the "next" tag.

### Describe the solution you'd like

Rework the openshift-ci jobs for using the "next" tag

**Comment by l0rd** [comment]
@Ohrimenko1988 not sure why it was labelled `team/plugins` but I have changed that to `area/ci-prod`.

@nickboldt there is no `team/prod` label, don't you need one for issues that you plan to work on?

**Comment by nickboldt** [comment]
@l0rd we use an `area` label so that any of the 40 people on the greater Che team can work on it, not just the 2 people in the Prod team. That was the reason for moving away from team labels a year ago, wasn't it? 

(Aside: I see we still have `ide`, `ide2` and  `osio` labels in the wiki @ https://github.com/eclipse/che/wiki/Labels Could you update that doc so it reflects the current reality?)

**Comment by l0rd** [comment]
> @l0rd we use an area label so that any of the 40 people on the greater Che team can work on it, not just the 2 people in the Prod team. That was the reason for moving away from team labels a year ago, wasn't it?

There is a misunderstanding. `team/*` labels are not deprecated, they are used when a team plan to work on an issue to inform others that the issue is taken.

> (Aside: I see we still have ide, ide2 and osio labels in the wiki @ eclipse/che/wiki/Labels Could you update that doc so it reflects the current reality?)

I hope that cross teams collaboration applies to the wiki too! You are welcome to fix something if it doesn't reflect reality.

**Comment by Ohrimenko1988** [comment]
@l0rd Hello Mario, I am a QE person in the plugins team, so I label my tasks related only to plugins tests by "team/plugins". Also, I maintain openshift-ci jobs related to plugins tests.

**Comment by l0rd** [comment]
> @l0rd Hello Mario, I am a QE person in the plugins team, so I label my tasks related only to plugins tests by "team/plugins". Also, I maintain openshift-ci jobs related to plugins tests.

Got it thanks

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse-che/che-plugin-registry/pull/978
