### ISSUE TITLE
7.31.0 operator installation failure on OCP 4.9

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#19908]
### Describe the bug
7.31.0 operator installation failure on OCP 4.9 

### Che version
7.31.0

### Steps to reproduce
install the latest che from the Operatorhub on OCP 4.9

### Expected behavior
successful Installation flow 

### Runtime
OCP 4.9

### Screenshots
![che-operator-installation-failure](https://user-images.githubusercontent.com/1461122/120467999-079fdb80-c3a1-11eb-918e-1f668e2064b4.gif)

### Installation method
Operatorhub

### Environment
OCP 4.9 / Cluster Bot

**Comment by ibuziuk** [comment]
probably related to https://github.com/eclipse/che/issues/19770

**Comment by tolusha** [comment]
duplicates https://github.com/eclipse/che/issues/19770
