### ISSUE TITLE
Is there a central page for all che/workplace variables?

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#19901]
## Summary

I was curious if there was a reference page for the special variables in Eclipse Che.  https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-with-dashboard/ such as:  $(CHE_PROJECTS_ROOT)

**Comment by tolusha** [comment]
Maybe this one
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/

**Comment by gnoejuan** [comment]
Thank you!
