### ISSUE TITLE
Dashboard displays incorrect devfile for a starting/running workspace

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19917]
### Describe the bug

I tried to create a workspace for the Python stack from the `Quick Add` page.
As result - it displayed me another devfile (with different projects and so on) which I had in my account. 
Please see a video.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a custom workspace and stop it.
2. Try to create a workspace from the `Quick Add` page.
3. Go to the devfile when a workspace is starting.
4. Pay attention - is it correct devfile or the devfile for the previous workspace from 1 (`Create a custom workspace and stop it.`)
5. Go to the devfile again when the workspace is running.
6. Pay attention - is it correct devfile or the devfile for the previous workspace 

### Expected behavior

Dashboard displays a correct devfile for a starting/running workspace.

### Runtime
  dogfooding instance

### Screenshots

![dashboard_creation](https://user-images.githubusercontent.com/5676062/120631392-80219d80-c470-11eb-97b8-d036c57257bd.gif)

**Comment by sleshchenko** [comment]
I can't reproduce it.
@RomanNikitenko let me know if you face it again. Thanks!
