### ISSUE TITLE
Dashboard duplicates workspace-items at removing workspaces

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19918]
### Describe the bug

I faced with the strange behavior at removing workspaces: dashboard displayed two workspace-items with the same name instead of removing two items. Please see a video.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create few (at least 3) workspaces.
2. Select 2 of them.
3. Remove them.
You can see two items with the same name.

### Expected behavior

The corresponding items are removed.
Dashboard doesn't display removed items, doesn't duplicate them.
### Runtime
   dogfooding instance.
   
### Screenshots

![dashboard_removing_workspace](https://user-images.githubusercontent.com/5676062/120646007-bfa4b580-c481-11eb-8864-1306b47bc102.gif)

**Comment by RomanNikitenko** [comment]
One more use case:

![remove_workspace_bug](https://user-images.githubusercontent.com/5676062/120649295-4313d600-c485-11eb-879d-878b2c11126b.gif)

**Comment by dmytro-ndp** [comment]
It could be related to recent changes in Dashboard https://github.com/eclipse-che/che-dashboard/pull/259

**Comment by sleshchenko** [comment]
Well, it should be fixed by https://github.com/eclipse-che/che-dashboard/pull/259.
Leaving me assigned here to test it on newer version.
@RomanNikitenko if you will be able to do it first, would be great.
BTW Thanks for reporting it.

**Comment by sleshchenko** [comment]
I can't not reproduce it anymore
