### ISSUE TITLE
Adapt automatic commit message to semantic commits

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19912]
### Is your task related to a problem? Please describe.

There are some messages like:
```
[release] Add 7.31.1 plugins in master
```
but it does not respect semantic commits syntax

### Describe the solution you'd like
adapt the automatic commit messages/PR title to be compliant

**Comment by nickboldt** [comment]
Commits prefixed with `[release]` appear for these projects:

* plugin & devfile registries
* che-docs
* eclipse/che
* machine-exec
* che-parent
* theia
* DWO

I assume the prefered prefix is `chore:`

**Comment by nickboldt** [comment]
PRs:

* plugin & devfile registries: https://github.com/eclipse-che/che-devfile-registry/pull/571 & https://github.com/eclipse-che/che-plugin-registry/pull/1162
* che-docs: https://github.com/eclipse/che-docs/pull/2205
* eclipse/che: and che-server: already done
* machine-exec: https://github.com/eclipse-che/che-machine-exec/pull/199
* che-parent: https://github.com/eclipse/che-parent/pull/188
* che-plugin-brokers: https://github.com/eclipse/che-plugin-broker/pull/128
* theia: https://github.com/eclipse-che/che-theia/pull/1284
* DWO: https://github.com/devfile/devworkspace-operator/pull/725/files
