### ISSUE TITLE
Failed to save changes to devfile 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19922]
### Describe the bug

Sometimes I get an error `Failed to update. undefined` when I save some changes to a devfile from the dashboard.
Refreshing a page does **not** fix the issue.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

I can not reproduce it permanently.

Go to devfile on dashboard and try to edit it and then press the `Save` button.

### Expected behavior

The changes should be saved without errors.

dogfooding instance.

### Screenshots

![save_devfile](https://user-images.githubusercontent.com/5676062/120661546-0ea61700-c491-11eb-8dd6-f93cbd4f9fa2.png)

![failed_save](https://user-images.githubusercontent.com/5676062/120662021-778d8f00-c491-11eb-9cad-33fd2351e14c.gif)

**Comment by sleshchenko** [comment]
@RomanNikitenko if you can reproduce it - please check Network from developer tools, what are failed requests if any? Thx

**Comment by sleshchenko** [comment]
now the reason is more clear
![Screenshot_20210624_162536](https://user-images.githubusercontent.com/5887312/123270706-d41c2100-d508-11eb-9ac9-0e1542ae7887.png)
