### ISSUE TITLE
Dashboard should resolve editor and plugins from repo during factory flow

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19927]
### Is your task related to a problem? Please describe.
Dashboard should resolve editor and plugins from repo during factory flow.

It's part of epic https://github.com/eclipse/che/issues/18668

it depends on: 
- [x] Allow resolver API to resolve other files than [.]devfile.yaml https://github.com/eclipse/che/issues/19540
- [x] Update workspace-client library to handle new information on Factory resolver API https://github.com/eclipse/che/issues/19925

**Comment by benoitf** [comment]
done in 7.32
