### ISSUE TITLE
IDE Editor doesn't open after starting the workspace from Dashboard

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19938]
### Describe the bug

After stopping and starting a workspace from the dashboard another dashboard opens in the frame.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace
2. Stop it
3. Open it again from the dashboard

### Expected behavior
IDE Editor should be opened

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

Tested on [dogfooding](che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com) instance:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 06 08-12_27_38](https://user-images.githubusercontent.com/1271546/121163296-5513c100-c857-11eb-9832-b9b6ff9ffc98.png)

https://user-images.githubusercontent.com/1271546/121164075-fd298a00-c857-11eb-90c9-b1025234d7b5.mp4

Local minikube:
![screenshot-che-eclipse-che 192 168 99 212 nip io-2021 06 08-12_25_08](https://user-images.githubusercontent.com/1271546/121164130-09154c00-c858-11eb-9a14-4da146523ec2.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by benoitf** [comment]
it looks like a dup of https://github.com/eclipse/che/issues/19931

**Comment by svor** [comment]
> it looks like a dup of #19931

@benoitf thx! 
Closed as it's dup of https://github.com/eclipse/che/issues/19931
