### ISSUE TITLE
Devfile should be updated after changing Storage Type in the Dashboard

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19939]
### Describe the bug
Devfile should contain changes related to Storage Type which were made from the Dashboard

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace
2. Stop it and to the Overview tab
3. Change Storage Type and save changes
4. Go to the Devfile tab 

### Expected behavior

New changes related to Storage Type should be present

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

https://user-images.githubusercontent.com/1271546/121172112-061e5980-c860-11eb-80f3-fb4c819e531a.mp4

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by skabashnyuk** [comment]
Afaik that is by design. Storage type is a workspace/runtime configuration, not a devfile. 

CC @sleshchenko @l0rd

**Comment by sleshchenko** [comment]
storage settings live in a devfile like https://github.com/eclipse-che/che-dashboard/blob/main/devfile.yaml#L5, otherwise, I don't think they will have an effect.

**Comment by skabashnyuk** [comment]
@sleshchenko you are right. That's a bug then.

**Comment by l0rd** [comment]
@sleshchenko If that's a fix only for Devfile v1 I don't think it's worth investing time on it right now. We should verify/fix the Devfile v2 scenarios instead.

**Comment by sleshchenko** [comment]
> If that's a fix only for Devfile v1 I don't think it's worth investing time on it right now. We should verify/fix the Devfile v2 scenarios instead.

@l0rd I would argue a bit, since:
- it's a regression for CRW;
- it should be pretty quick to fix;

This issue is not actual for DevWorkspace since:
- devfile v2 does support volume type (emptyDir, PVC) on individual volume level;
- devworkspace support does not support emptyDir on devworkspace level yet; I'll create a separate issue for that and in any case, it's going to be devworkspace annotation but not devfile attribute I assume.

I'll create a separate issue to align the desired behavior for DevWorkspace.

**Comment by l0rd** [comment]
If it's pretty quick to fix then go ahead. But if it takes more than one week of work I would put that on hold: I haven't heard of customers/users being affected by this issue.
