### ISSUE TITLE
Support deploying devworkspaces on Kubernetes

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#19944]
### Is your enhancement related to a problem? Please describe.
Enabling devworkspaces currently only works on OpenShift. To enable this on Kubernetes, too, we need to start deploying all the files from the `deployment/kubernetes` directory of `devworkspace-operator`. We also need to make sure that che-operator installs the `cert-manager` if not present in the cluster (tracked by #19502).

It seems that #19502 might be dependent on #19466

### Describe the solution you'd like
When using the `devworkspace-operator` files on kubernetes, we should make sure we deploy all the files necessary on kubernetes.

**Comment by skabashnyuk** [comment]
1. Cluster roles has to be add for che-operator SA  in che-operator/deploy/cluster_role.yaml


```
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - create
      - get
      - list
      - update
```

After that we can deploy che on minikube

```

#!/bin/bash
set +e
echo 'deploing che'
chectl update next
minikube stop
minikube delete
set -e



minikube start --cpus 4 --memory 600
TMP_DIR=$(mktemp -d)'/templates'
mkdir -p $TMP_DIR'/che-operator'
mkdir -p $TMP_DIR'/devworkspace'

cp -R ~/dev/src/eclipse-che/che-operator/deploy/*  $TMP_DIR'/che-operator'
cp -R ~/dev/src/eclipse-che/devworkspace-operator/deploy/*  $TMP_DIR'/devworkspace'
echo $TMP_DIR 

chectl server:deploy --platform=minikube --installer=operator --workspace-engine=dev-workspace --che-operator-image=quay.io/skabashn/che-operator:che19944 --templates $TMP_DIR 
rm -rf $TMP_DIR


kubectl patch checluster/eclipse-che -n eclipse-che --type=json -p \
   '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": true}]'



kubectl patch checluster/eclipse-che --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S\": \"true\"}}}}" --type=merge -n eclipse-che
kubectl create namespace admin-che
```
After that I got this error

```
2021-06-25T07:53:34.363Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:34.384Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:34.424Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:34.505Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:34.665Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:34.986Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:35.626Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:36.907Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}                                      │
│ 2021-06-25T07:53:39.467Z    INFO    che    validation errors    {"errors": "The following validation errors were detected:\n- workspaceBaseDomain must be specified\n"}
```
To fix it I've manually add to CheManager CR

```
workspaceBaseDomain: 192.168.64.208.nip.io
```
<img width="510" alt="Знімок екрана 2021-06-25 о 11 33 24" src="https://user-images.githubusercontent.com/1614429/123395712-3167af00-d5a9-11eb-8859-c31a37ea3fc5.png">
After that I saw that configbump/trefik deployment
<img width="1638" alt="Знімок екрана 2021-06-25 о 11 08 16" src="https://user-images.githubusercontent.com/1614429/123395748-3b89ad80-d5a9-11eb-8ac6-2cea11f7645c.png">



After that, I was able to create a workspace from the dashboard.
<img width="966" alt="Знімок екрана 2021-06-25 о 11 10 01" src="https://user-images.githubusercontent.com/1614429/123396034-83a8d000-d5a9-11eb-8210-734a62c86c42.png">
And It pods successfully started
<img width="1678" alt="Знімок екрана 2021-06-25 о 11 16 40" src="https://user-images.githubusercontent.com/1614429/123396127-a1763500-d5a9-11eb-8a35-1290e24fd6ee.png">
Theia showed up. Hower I saw some eroros. Maybe related to TLS
<img width="1577" alt="Знімок екрана 2021-06-25 о 11 37 26" src="https://user-images.githubusercontent.com/1614429/123396272-cb2f5c00-d5a9-11eb-9346-053c7dc2fdf0.png">

**Comment by skabashnyuk** [comment]
Things todo:
- deal with roles
- Setup workspaceBaseDomain. https://github.com/che-incubator/devworkspace-che-operator/blob/ae29f7cc2e2b475fe7fc139989a36b63152ad743/pkg/manager/chemanager_controller.go#L176-L192
-  deal with tls
