### ISSUE TITLE
Provide clear public information relating to the devfile v2 and DevWorkspace efforts within the project

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#19941]
With the upcoming release of [milestone 2](https://github.com/eclipse/che/milestone/139), we will be at the point where Che users should actively start experimenting with the [new support for Devfile v2 and DevWorkspaces](https://github.com/eclipse/che/issues/17307). Given this is a significant effort within the project, we should ensure that it is easy for a Che user or someone exploring the project to be able to understand:

- Why the devfile specification has evolved - the advantages this brings for the user and the project, where to find out more
- Progress and timelines for integration in Che
- How a Che user can try this out
- Known limitations
- How to provide feedback 
- ?

This can leverage existing materials where possible, what is important is that we ensure we are surfacing this information as much as possible. I would suggest this includes an update to the `eclipse/che` readme.

**Comment by MichalMaler** [comment]
Related Jira: https://issues.redhat.com/browse/RHDEVDOCS-3373

**Comment by benoitf** [comment]
closing as it's tracked in JIRA

**Comment by nickboldt** [comment]
See https://issues.redhat.com/browse/RHDEVDOCS-2555
