### ISSUE TITLE
Error message should be more helpful at creation a workspace

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19945]
### Describe the bug

I have got an error like: `Failed to create a new workspace from the devfile:undefined`
The cause of the problem was - the workspace with such name existed in my account.
Actually I copied a devfile from another workspace to workaround https://github.com/eclipse/che/issues/19922 (I could not to save my changes to existent devfile, so I tried copy it and create a new workspace).

Dashboard could inform a user about the problem by providing more clear message.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace.
2. Try to create another workspace with the same name ^
3. See error

### Expected behavior

Dashboard could inform a user about the problem by providing more clear message.

### Runtime
  dogfooding instance

### Screenshots

![create_workspace_undefined](https://user-images.githubusercontent.com/5676062/121310065-9cf42000-c90b-11eb-9c5b-3f06096607b5.gif)

**Comment by sleshchenko** [comment]
Again this undefined =(
