### ISSUE TITLE
Update Node Debugging Experience

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19952]
### Is your enhancement related to a problem? Please describe.
The Debugging experience for Node seems to be much better in VS Code than what we have in Che right now. For example, when debugging the Theia back-end process, breakpoints in subprocesses (the plugin host process in particular) are hit, as well. I also feel the performance is better in VS Code.

### Describe the solution you'd like
Let's investigate where we have gaps: in particular update the node-debug/node-debug2 extensions to a newer level and identify gaps in API or what we need to improve in the debugger implementation in Theia.

**Comment by tsmaeder** [comment]
For starters, vs code now uses "jd-debug" for javascript debugging: https://github.com/microsoft/vscode-js-debug. To quote, "It has been the default JavaScript debugger in Visual Studio Code since 1.46".
We're still using node-debug and node-debug2 in Che.

**Comment by tsmaeder** [comment]
Also, Theia is a bit behind on the Debugger API, in particular, it does not group debug sessions in a parent hierarchy.

**Comment by tsmaeder** [comment]
I filed https://github.com/eclipse-theia/theia/issues/9664, we're also quite behind on the DAP implementation: https://github.com/eclipse-theia/theia/issues/8136

**Comment by svor** [comment]
jsdebug configuration was added for [nodejs](https://github.com/che-samples/web-nodejs-sample/blob/devfilev2/.vscode/launch.json) and [nodejs+mongoDB](https://github.com/che-samples/nodejs-mongodb-sample/blob/devfilev2/.vscode/launch.json) devfiles v2
![screenshot-nimbus-capture-2021 09 20-15_10_04](https://user-images.githubusercontent.com/1271546/134495015-57306142-7142-4243-98a5-0793d7571d38.png)
