### ISSUE TITLE
"Edit Commands..." for java seems don't work

### ISSUE THREAD

**Issue by michaellee8** [eclipse-che/che#1996]
I add a `Run` Command in `Run` > `Edit Commands` for one of my class in my java project, the command is generated, but when I selected the corresponding command and clicked the play button on it, a newly generated terminal showed the corresponding command, but I have to wait for minutes for the first line of output to come out, then the program seems stopped, I cannot do any input as well as that rectangle box does not exist any more. Note that when I type those 3 commands for compiling and running java CLI program separately, which are `cd`, `javac`, and `java`, the program works fine.

**Reproduction Steps:**
1. Open your workspace.
2. Create a new java project with `src` as source code folder.
3. Just type something CLI code like `System.out.print()` and `new Scaner(System.in).next()` into the `main`
4. Go to `Edit Commands...`, and then add a command for running the program with the java option in the left-hand side list by clicking the `+` button on it
5. Browse your `main` file.
6. Save the command, and then run it in IDE.

**Expected behavior:**

No output for a few minutes, then saw the first line of output, program seems stuck there, no rectangle box, no input possible to the terminal

**Observed behavior:**

First line of output produced immediately, with proper I/O

**Che version:**    4.5.1
**Che install:**   Codenvy

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ghost** [comment]
@michaellee8 what you are trying to say is perhaps that when you execute your Java code that expects user input, it is impossible to do that when running it as a command. This is expected behavior. If you need user input, you should manually execute commands in the terminal. 

Perhaps the best way to illustrate a problem is to attach a screenshot or a gif here?

**Comment by michaellee8** [comment]
@eivantsov Really? Then would you like to tell me what functionality does `Edit Commands` used for?

**Comment by TylerJewell** [comment]
Edit commands should allow for user input, but it's a limitation of the product right now. The commands - today - are docker execs without a pseudo terminal, so while we can stream output from those commands, we cannot yet stream standard input into them. So it's a limitation in the command framework. There is a big epic to create a command framework that does not use docker exec capabilities and this sort of pseudo terminal interaction can then happen with commands.

The workaround for this is to use a terminal window and executing your command in that window. Commands are using the same bash syntax that you would run in a terminal window.

**Comment by michaellee8** [comment]
@TylerJewell Thanks for your explanation. Just one following question is can I do my Android Run / Gradle Build in Che? I saw a tutorial on youtube for the legacy codenvy, but how about a beta Che one?

**Comment by TylerJewell** [comment]
See the docs - there are android and gradle instructions.
https://eclipse-che.readme.io/docs/

**Comment by michaellee8** [comment]
I got it, thank you for your help

**Comment by TylerJewell** [comment]
Enjoy the product!
