### ISSUE TITLE
Share backup server configuration between backup & restore CRs

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19977]
### Is your task related to a problem? Please describe.
Currently backup and restore controllers updates its configuration which is not a typical practice. 

### Describe the solution you'd like
Introduce a new CR with server configuration configurations.
Share it between backup & restore CRs

### Describe alternatives you've considered

N/A

**Comment by mmorhun** [comment]
Solution commits were added into https://github.com/eclipse-che/che-operator/pull/844
