### ISSUE TITLE
[CHECTL] chectl over corporate proxy not working

### ISSUE THREAD

**Issue by disaster37** [eclipse-che/che#19979]
### Describe the bug
`chectl server:deploy --version=7.31.2` not working over coorporate proxy.

Same matter with `chectl update stable` over coorporate proxy.

It failed on:
```
  ✖ Check versions compatibility
    → request to https://api.github.com/repos/eclipse-che/che-operator/git/ref/tags%2F7.31.2 failed, reason: connect ETIM
```

After check with our security team, chectl try ton connect directly to api.gihtub.com and so, seems to ignore http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY.

### Che version

 - [x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

`chectl server:deploy --version=7.31.2` over corporate proxy.

### Runtime
   - [X ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

**Comment by tolusha** [comment]
@disaster37 
as a workaround try to install the latest 7.31.2 using curl
`bash <(curl -sL  https://www.eclipse.org/che/chectl/)`
and then you can use `chectl server:deploy` without specifying a version

**Comment by disaster37** [comment]
Its finnaly work. It was issue about auth with proxy work in our coorporate
