### ISSUE TITLE
[Cross-Project Epic] Standardization/Harmonization of go-based tooling builds and deployment process

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19970]
### Is your task related to a problem? Please describe.
multiple go-based tooling has different base builder/and deployment images and the way how to build them.
It's very hard to support them

### Describe the solution you'd like

The idea is to have common base images. One for go-based tooling build, another for runtime. That will allow simplifying several things.
 - Deliver bug fixes in images.
 - Deliver new SSL certificates in images.
 - Deliver timezone update in images.
 - Setup of new components/services
 - Maintenance of existed  components/services.

As a result, we will have.

1. Repository with based dockerfiles.
2. Set of base images on https://quay.io/
2. Repository with a reference implementation of the build process.

### Describe alternatives you've considered
n/a

### Additional context
* [Cross-Project Epic] CI Build / Weekly Release process should use consistent quay tags for sha-version/next and 7.yy.z/latest  - https://github.com/eclipse/che/issues/19291
* [Cross-Project Epic] Migrate rhel.Dockerfiles in all che repos to use ubi8 + install go-toolset RPMs (go-toolset container deprecated as of RHEL 8.4) - https://github.com/eclipse/che/issues/19762

**Comment by nickboldt** [comment]
I like the idea of a single cross-Che-project base image for all the golang container builds... but with the caveat that:

* Brew can't use quay images as `FROM` base images, so
* all the sync.sh scripts we have today to pull upstream content and transform it into midstream/downstream will need an additional transformation, something like this:

upstream:
```
FROM quay.io/eclipse/che-golang-builder:1.15
```

downstream
```
FROM registry.access.redhat.com/ubi8-minimal:8.4-200.1622548483 as builder
RUN microdnf install -y golang unzip && go version
```

You'll also want to make sure that all the projects are ready to move to a new base image when updates happen. For example, when UBI8 contains go 1.16, all projects based on this shared builder image will have to be updated to use go 1.16.

**Comment by nickboldt** [comment]
Note that the EOL notice has been removed from the go-toolset images in RHEC, and the new ubi8 go-toolset image will be supported.

So we can do this now:

```
# https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/ubi8/go-toolset
FROM registry.access.redhat.com/ubi8/go-toolset:1.15.7-11 as builder
ENV GOPATH=/go/
```

and then where possible, use the ubi8-micro image for the runtime:

```
# https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/ubi8-micro
FROM registry.access.redhat.com/ubi8-micro:8.4-72
```

**Comment by skabashnyuk** [comment]
won't fix
