### ISSUE TITLE
Adapt Che-Theia to upstream changes

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19984]
### Is your task related to a problem? Please describe.

There are breaking changes made in upstream `Theia` by the commit: https://github.com/eclipse-theia/theia/commit/f9c031120708e0b4c7ef4afe86210144062ebde8.
The `Che` Workspace fails, I detected the following problem:

![fail_start](https://user-images.githubusercontent.com/5676062/122219070-be2eb080-ceb7-11eb-8cc8-c1b8e8a83d4f.png)

it's something related to `keytar` which was added within https://github.com/eclipse-theia/theia/commit/f9c031120708e0b4c7ef4afe86210144062ebde8

### Describe the solution you'd like

Need to adapt Che-Theia to the upstream changes.

**Comment by azatsarynnyy** [comment]
Theia now depends on `keytar` which requires installed `libsecret`.
Checking... https://github.com/eclipse-che/che-theia/pull/1142/commits/6b900cb1a0b6d1fb66399c26d6868650dfc2030c

**Comment by azatsarynnyy** [comment]
Fixed by: https://github.com/eclipse-che/che-theia/pull/1142/commits/6b900cb1a0b6d1fb66399c26d6868650dfc2030c + https://github.com/eclipse-che/che-theia/pull/1142/commits/ca2038e5af2a7e202af8e673b727759112aefdc6
