### ISSUE TITLE
Add GITHUB_TOKEN in che-theia PR check

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#19986]
### Is your enhancement related to a problem? Please describe.
We need to add GITHUB_TOKEN in che-theia PR check, to eliminate build error:
```
Rate limit for https://api.github.com is reached.To be able to build this image, please provide GITHUB_TOKEN environment variable
```

Target CI: CRW Jenkins

**Comment by nickboldt** [comment]
Probably just need to do:
```
        export GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}
```

like in https://github.com/eclipse-che/che-theia/blob/master/.github/workflows/release.yml

**Comment by dmytro-ndp** [comment]
@nickboldt it had to be fixed in Happy path test pipeline stored in CRW Jenkins repo: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/commit/008da9405e836bf4943fb3971b174d298010f173#4d398de5f312979bf5aa592f65783f04a57fae5b_179_176

Sorry for misleading description of issue.
