### ISSUE TITLE
Dashboard backend basic API

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19987]
### Is your enhancement related to a problem? Please describe.
https://github.com/eclipse-che/che-dashboard/pull/268 introduces static server that serves dashboard frontend resources. That is the first step to desired dashboard backend.

So, this issue is about moving to node server(https://github.com/fastify/fastify-static) that would serves static resources + provide API, the first step we need - K8s API proxy, but to simplify the stuff we may proceed with a limited APIs numbers (we have already https://github.com/JPinkney/dashboard-backend/blob/master/src/index.ts) and then migrate it to full proxy.

**Comment by l0rd** [comment]
@sleshchenko do we have an epic or issue that explains why we are introducing a Dashboard backend?

**Comment by sleshchenko** [comment]
@l0rd not yet. I'll create one

**Comment by sleshchenko** [comment]
@l0rd here is Dashboard backend epic https://github.com/eclipse/che/issues/20129

**Comment by sleshchenko** [comment]
The basic dashboard backend is already merged into new dev branch https://github.com/eclipse-che/che-dashboard/pull/314
We'll create other issues for polishing the implementation
