### ISSUE TITLE
Unable to authenticate from IOS  14.6 (chrome,firefox)

### ISSUE THREAD

**Issue by abdelhamidfg** [eclipse-che/che#19998]
### Describe the bug
Received error message as attached  "Failed to request branding" during authentication from IOS 14.6 iphone/ipad  chrome/safari/firefox 

 Che version
 - [ ] latest **7.28.2**

### Steps to reproduce

1- provide username /password in the login page from IPAD/iphone 14.6 using chrome/firefox
2- error message will be received "Failed to request branding""

### Runtime
   -  Openshift (include output of `oc version`)

### Installation method
   - [ ] OperatorHub

### Environment
   -IPAD /Iphone

[
![image (4)](https://user-images.githubusercontent.com/7538645/122513243-3661b700-d01b-11eb-9a23-c809b65e0f42.png)
](url)

**Comment by ibuziuk** [comment]
@abdelhamidfg could you please clarify how the EclipseChe was installed on the cluster? Is it reproducible against OCP v4?
Please, provide more detailed steps to reproduce, including the installation instructions / env

**Comment by ibuziuk** [comment]
@sleshchenko could you please take a look? based on the error message could be UD specific (failed to request product.json)

**Comment by abdelhamidfg** [comment]
@ibuziuk  I am using openshift 4.7.8 , installed using Red Hat CodeReady Workspaces operators 2.8.0 .Please let me know if you need access to the environment.

**Comment by gmawdo** [comment]
i too get this precise issue and get it in two very different environments:
1. simply create an online redhat account and run che in a sandbox in their codeready enviroment: https://oauth-openshift.apps.sandbox-m2.ll9k.p1.openshiftapps.com/oauth/authorize?scope=user etc......on the page choose dev sand box option
2. create kubernetes cluster at DigitalOcean, install ingress from their market place, add an ingress, configure clusterissuer, install Che using chectl with olm installer

in the second scenario (DO)i get additional info of 'reason 401' (i.e unauthorized)
