### ISSUE TITLE
run automation throw error 'no such file or directory' in che-plugin-registry

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#19997]
### Describe the bug

when i run automation, it throw error 'no such file or directory'

![image](https://user-images.githubusercontent.com/13031838/122500347-36ff4b00-d025-11eb-9421-401c1f85968d.png)

[che-theia-openshify-auth@0.0.1](https://github.com/che-incubator/che-theia-openshift-auth/tree/0.0.1) does not have `package.json`

![image](https://user-images.githubusercontent.com/13031838/122500449-62823580-d025-11eb-8416-cdd768f3cf92.png)

**Comment by ibuziuk** [comment]
@ericwill could you please take a look?

**Comment by ericwill** [comment]
@zWingz can you please provide the steps you ran to reproduce this issue?

**Comment by zWingz** [comment]
@eriawan 
- `cd tools/automation`
- `node ./lib/check-plugin-updates.js`

![Uploading image.png…]()

**Comment by ericwill** [comment]
> @eriawan
> 
>     * `cd tools/automation`
> 
>     * `node ./lib/check-plugin-updates.js`
> 
> 
> ![image](https://user-images.githubusercontent.com/13031838/122848720-b8641f80-d33c-11eb-912b-6c6d0ef063d1.png)

This isn't meant to be run by users, it's for generating a nightly report about the update status of plugins in the plugin registry. Are you trying to run the build script instead?

**Comment by eriawan** [comment]
@zWingz 


> @eriawan
> 
> * `cd tools/automation`
> * `node ./lib/check-plugin-updates.js`

Just a humble reminder, could you update your comment so the next conversation will not quote my name? I think you mean ericwill, not me.

Cheers! 🙂

**Comment by benoitf** [comment]
I've updated the comments thx for the notice

**Comment by zWingz** [comment]
> > @ericwill
> > ```
> > * `cd tools/automation`
> > 
> > * `node ./lib/check-plugin-updates.js`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/13031838/122848720-b8641f80-d33c-11eb-912b-6c6d0ef063d1.png)
> 
> This isn't meant to be run by users, it's for generating a nightly report about the update status of plugins in the plugin registry. Are you trying to run the build script instead?

yes, i know it is to generate a report about the update status of plugins. but it seem not work. Should I run it in another way ?

**Comment by ericwill** [comment]
Seems you are correct, it is a bug. Thanks for the report, we'll take a look.

**Comment by vitaliy-guliy** [comment]
@zWingz how do you run the script exactly?
Is it in the container or on your local machine?
When I try to run it by hands, I always get the following
```
$ node ./lib/check-plugin-updates.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- /home/vitaliy/projects/automation-issues/che-plugin-registry/tools/automation/lib/check-plugin-updates.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/vitaliy/projects/automation-issues/che-plugin-registry/tools/automation/lib/check-plugin-updates.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/vitaliy/projects/automation-issues/che-plugin-registry/tools/automation/lib/check-plugin-updates.js'
  ]
}
```

**Comment by zWingz** [comment]
@vitaliy-guliy I run the script on my local machine. you should run `yarn node`  because it use `yarn@2` https://yarnpkg.com/cli/node

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy I run the script on my local machine. you should run `yarn node ./lib/check-plugin-updates.js` because it use `yarn@2` https://yarnpkg.com/cli/node

Thanks.
I see, that the tag [0.0.1](https://github.com/che-incubator/che-theia-openshift-auth/tree/0.0.1), on which the [plugin registry refers](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L318-L319), does not have sources.

We will re-create the tag, this should will fix the issue.

**Comment by vitaliy-guliy** [comment]
Tag https://github.com/che-incubator/che-theia-openshift-auth/tree/0.0.1 is updated, the script is running wo errors.
