### ISSUE TITLE
Unexpected collapse of  project tree after configuration of a keeping directory

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1999]
1. Clone maven multimodule projects and keep directory. Set Keep following directory checkbox for a sub module.
2. Clone, select just cloned submodule. Try to configure the submodule as maven.

**Expected behavior:**  After settings -  the opened items should be opened 
**Observed behavior:** The items are collapsed. But after some clicking on the projects, works correct

**Expected behavior:** after clicking on the fires item the Compare button should be enabked
**Observed behavior:** after clicking on the fires item the Compare button still disabled
**Che version:**    4.6.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Comment by JamesDrummond** [comment]
@musienko-maxim Please assign to someone.

**Comment by slemeur** [comment]
@musienko-maxim is this still accurate?

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
