### ISSUE TITLE
[chectl] Add workspace specific "RELATED_IMAGE" to the operator.yaml to make it consistent with csv

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20005]
### Is your enhancement related to a problem? Please describe.
Currently `RELATED_IMAGES_*` vary across installation methods:

- OperatorHub / chectl `installer --olm` contain extended list of RELATED_IMAGES, including workspace specific - https://github.com/operator-framework/community-operators/blob/b560ec81cd4e586e9cb05c3674426da4971ba3b3/community-operators/eclipse-che/7.32.0/eclipse-che.v7.32.0.clusterserviceversion.yaml#L1029-L1142
- chectl `installer --operator` only contains basic (non workspace-specifc) list of images - https://github.com/eclipse-che/che-operator/blob/main/deploy/operator.yaml#L52-L81 

Since it is planned to fall back on the `RELATED_IMAGES_*` for the kubernetes image puller integration with Eclipse Che it would be great to have the extended list of images available as env vars regardless of the installation method. This issue is important for:

### Describe the solution you'd like
`RELATED_IMAGES_*` are consistent across the installation methods - Operatorhub, chectl (operator), chectl(olm)
Image puller is going to generate the images for pre-pulling based on the RELATED_IMAGES env var
### Describe alternatives you've considered
N/A

### Additional context
This issue is considered to be an important enhancement for the further kubernetes image puller integration with Eclipse Che:
- https://github.com/eclipse/che/issues/19657
- https://github.com/eclipse/che/issues/18570

**Comment by tolusha** [comment]
We are talking here only about stable version of che-operator. 
The next/nightly one won't contain `RELATED_IMAGES_*`  anyway

**Comment by ibuziuk** [comment]
yeah, I believe stable version is fine

**Comment by l0rd** [comment]
Should we deprecate `installer --operator` if OLM is available on the cluster instead? There is a cost maintaining both `olm` and `operator` options. What's the value for the user?

**Comment by ibuziuk** [comment]
I'm fine with deprecating the `installer --operator `, but this is more a question to the deploy team I believe
