### ISSUE TITLE
Add vscode-xml plugin into all maven-based stacks in che-devfile-registry 

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#20001]
### Is your task related to a problem? Please describe.

Each time when we create a workspace from the devfiles with samples based on maven, the recommendation plugin recommends to install vscode-xml plugin to provide better support for editing pom.xml.  
![screenshot-che-eclipse-che 172 17 0 2 nip io-2021 06 18-12_07_08](https://user-images.githubusercontent.com/1271546/122542187-150cc500-d033-11eb-8d70-fc42bfaa8188.png)

It makes sense to include vscode-xml by default for such devfiles. The list of devfiles with maven is:

- [ ] [java-maven](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-maven/devfile.yaml)
- [ ] [java-lombok](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-lombok/devfile.yaml)
- [ ] [java-mongo](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-mongo/devfile.yaml)
- [ ] [java-mysql](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-mysql/devfile.yaml)
- [ ] [java-web-spring](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-web-spring/devfile.yaml)
- [ ] [java-web-vertex](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-web-vertx/devfile.yaml)
- [ ] [quarkus](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/quarkus/devfile.yaml)  
- [ ] [quarkus-command-mode](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/quarkus-command-mode/devfile.yaml) 

### Describe the solution you'd like

Add a component with vscode-xml plugin:
```yaml
  -
    type: chePlugin
    id: redhat/vscode-xml/latest
  -
```

**Comment by benoitf** [comment]
or we turn off recommendation plug-in for the getting started sample ?

**Comment by svor** [comment]
> or we turn off recommendation plug-in for the getting started sample ?

@benoitf yes, I'm going to discuss about that in the next Cabal. But in case of maven-based stack it would be nice to have better support to edit pom.xml.
