### ISSUE TITLE
Theia is loading silently when internet connection is pure

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20006]
### Describe the bug
When internet connection is pure, Theia is loading silently:
![Screenshot_20210618_180943](https://user-images.githubusercontent.com/5887312/122582263-a0507f80-d060-11eb-8873-25e4a3c4cf95.png)

Maybe Theia could have a light index.html that displays loader and only then starts loading huge resources.

**Comment by benoitf** [comment]
hello, I'm not sure I understand the type of internet connection ?
