### ISSUE TITLE
[devworkspaces] Not able to start a devworkspace because namespace are not found

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20014]
### Is your task related to a problem? Please describe.
 Not able to start a devworkspace because namespace are not found

### Describe the solution you'd like
Steps to reproduce 

 1. Deploy che on k8s with devworkspaces
 2. Enable unsupported k8s API on che server.
    kubectl patch checluster/eclipse-che --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S\": \"true\"}}}}" --type=merge -n eclipse-che
 3. Try to start devworkspaces    
<img width="729" alt="Знімок екрана 2021-06-22 о 16 37 33" src="https://user-images.githubusercontent.com/1614429/122936349-c1bfad00-d379-11eb-9b2f-47f579630976.png">

**Comment by JPinkney** [comment]
The devworkspace-client currently only initializes namespaces on OpenShift: https://github.com/che-incubator/devworkspace-client/blob/main/src/browser/che-api.ts#L35, we still need to add support for kubernetes

**Comment by sleshchenko** [comment]
it should be easy fix, adding to the current sprint as unplanned to unblock moving forward in the direction of DevWorkspace support on Kubernetes.
