### ISSUE TITLE
Adapt chectl to devfile 2.0

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20010]
### Is your enhancement related to a problem? Please describe.

Currently chectl uses Che API to handle workspace commands.
When devfile 2.0 is out then Che API won't work. 

### Describe the solution you'd like
We need some workspace client to allow chectl to communicate with it.

### Describe alternatives you've considered
Use k8s API

**Comment by tolusha** [comment]
We have to adopt all chectl commands to devfile 2.0

**Comment by tolusha** [comment]
close if favor of https://github.com/eclipse/che/issues/20671
