### ISSUE TITLE
Migrate manifests and API clients to use the networking.k8s.io/v1 API version

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#20019]
### Is your task related to a problem? Please describe.

The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress will no longer be served in v1.22. 

Currently `extensions/v1beta1` is used:
1. che-operator: https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/ingress.go#L64
2. helmcharts: https://github.com/eclipse-che/che-server/blob/main/deploy/kubernetes/helm/che/templates/ingress.yaml#L23
3. che-server: fabric8 client which creates Ingress v1beta1

https://github.com/eclipse-che/che-server/blob/main/pom.xml#L75
https://github.com/eclipse-che/che-server/blob/main/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/util/Ingresses.java#L18

### Describe the solution you'd like

Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19. [1]

### Describe alternatives you've considered

N/A

### Additional context

N/A

[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
[2] https://kubernetes.io/releases/

### Sub tasks
- [x] https://github.com/eclipse/che/issues/20182
- [x] https://github.com/eclipse/che/issues/20181
- [x] Update chectl to check the minimum k8s version

**Comment by l0rd** [comment]
@tolusha @flacatus if we use `v1` we won't be able to support older version of Kubernetes and OpenShift right? Maybe that should be reviewed to make sure that we don't break installations on older version that we currently support.

**Comment by tolusha** [comment]
@l0rd 
The idea is to use Ingress v1 only if platform supports it otherwise Ingress v1beta1 will be used.
So, Eclipse Che will still work on older versions of Kubernetes.

**Comment by tolusha** [comment]
this issue depends on https://github.com/eclipse/che/issues/19466

**Comment by sleshchenko** [comment]
related issue on DWO side https://github.com/devfile/devworkspace-operator/issues/543

**Comment by tolusha** [comment]
Remaining task https://github.com/eclipse/che/issues/20298

**Comment by apupier** [comment]
For information, Che is not working with latest released Kubernetes 1.22.0 as this deprecated `extensions/v1beta1` has been removed.
Kubernetes 1.22.0 will be the base of OpenShift 4.9.

**Comment by tolusha** [comment]
@apupier 
I've just checked `next` version.
Everything works fine.
Which version were you talking about?

**Comment by apupier** [comment]
> Which version were you talking about?

latest released Eclipse Che 7.35.2

**Comment by tolusha** [comment]
Should work for 7.36.0
