### ISSUE TITLE
fix invalid certificate for https://che.eclipseprojects.io 

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#20029]
This invalid certificate is causing failur on blocking cheks on all che-docs pull requests.

Get "https://che.eclipseprojects.io": x509: certificate is valid for www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com, not che.eclipseprojects.io

**Comment by benoitf** [comment]
related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=574381

**Comment by themr0c** [comment]
https://che.eclipseprojects.io/ responding correctly now. Thanks!
