### ISSUE TITLE
Che operator redistributes restic, but does not include 2-Clause BSD license

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20028]
The Che operator build now depends on a 3rd party binary called restic.

https://github.com/eclipse-che/che-operator/blob/main/Dockerfile#L19-L20

this code is under the BSD 2 / FreeBSD license, https://github.com/restic/restic/, which means we have to include the license next to the binary if we redistribute it.

```
Redistributions in binary form must reproduce the above copyright notice, 
this list of conditions and the following disclaimer in the documentation 
and/or other materials provided with the distribution.
```
 -- https://opensource.org/licenses/BSD-2-Clause

Seems you're just redistributing the binary, but not the license.

**Comment by mmorhun** [comment]
Fixed
