### ISSUE TITLE
license checker failing Che 7.32.2 build due to "missing header"

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20026]
While building Che 7.32.2 as part of CRW 2.10, I get a build failure due to that super annoying license checker:

```
15:28:01 [INFO] --- license-maven-plugin:3.0:check (check-headers) @ che-core-commons-annotations ---
15:28:01 [INFO] Checking licenses...
15:28:01 [WARNING] Missing header in: /var/lib/jenkins/workspace/CRW_CI/sync-to-downstream_2.x/targetdwn/codeready-workspaces/core/commons/che-core-commons-annotations/src/main/java/org/eclipse/che/commons/annotation/Nullable.java
15:28:01 [WARNING] Missing header in: /var/lib/jenkins/workspace/CRW_CI/sync-to-downstream_2.x/targetdwn/codeready-workspaces/core/commons/che-core-commons-annotations/src/main/java/org/eclipse/che/commons/annotation/Traced.java
15:28:01 [INFO] ------------------------------------------------------------------------
15:28:01 [INFO] Reactor Summary for Che Server 7.32.2-SNAPSHOT:
15:28:01 [INFO] 
15:28:01 [INFO] Che Server ......................................... SUCCESS [ 37.106 s]
15:28:01 [INFO] Che Core Parent .................................... SUCCESS [  0.085 s]
15:28:01 [INFO] Che Core :: Commons :: Parent ...................... SUCCESS [  0.073 s]
15:28:01 [INFO] Che Core :: Commons :: Annotations ................. FAILURE [  2.895 s]
```
--- https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/sync-to-downstream_2.x/258/console

But looks like those files haven't changed in 3 years... so, why is the license checker complaining that these files have a 2018 copyight date on them? and "Missing header" seems a bit harsh when the files do in fact have content in them.

https://github.com/eclipse-che/che-server/tree/7.32.x/core/commons/che-core-commons-annotations/src/main/java/org/eclipse/che/commons/annotation

**Comment by nickboldt** [comment]
weirdly I can't reproduce this locally. so must be a jenkins node that's misbehaving :(

**Comment by skabashnyuk** [comment]
doesn't reproduced upstream
