### ISSUE TITLE
Improve che operator tests in openshift ci to cover image puller

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#20032]
### Is your task related to a problem? Please describe.

Currently Image puller is not covered for any tests in che operator side.
### Describe the solution you'd like

Improve our current tests in che operator to cover image puller deployment with che operator.

### Describe alternatives you've considered

N/A
### Additional context

N/A

**Comment by tolusha** [comment]
Image puller is deployed in `ci/prow/v7-stable-to-nightly` tests
