### ISSUE TITLE
Angular getting started devfile start / build commands are failing with exit code 137

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20045]
### Describe the bug
Angular getting started devfile start / build commands are failing with exit code 137

### Che version
CRW 2.8 / samples from community devfiles 7.32.0

### Steps to reproduce

1. go to http://workspaces.openshift.com/#get-started  
2. start a new workspace based on the Node.js / Angular devfile  
3. run yarn install command
4. run build command
5. ERROR: comand fails with `error Command failed with exit code 137.`

### Expected behavior
build and start commands are not failing

### Runtime
- workspaces.openshift.com 

### Screenshots
![image](https://user-images.githubusercontent.com/1461122/123925708-7580f800-d98b-11eb-8ae9-a1d7be94526c.png)

### Eclipse Che Logs
```
yarn run v1.17.3
$ ng build --prod  --base-href ./ && cp CNAME dist/CNAME
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Killed
Warning: Worker #1 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/platform-browser-dynamic, formatProperty: es2015, processDts: Yes}
  Current phase: compiling
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ibuziuk** [comment]
@ericwill could you please invesigate. Customers have issues with the angular workspace setup

**Comment by benoitf** [comment]
it was fixed by https://github.com/eclipse-che/che-devfile-registry/commit/c0ff42a5f7d05a60a383b71c23b24a51a141d3a3#diff-bb232b84fc7eca5f42b22f563f8593d81ad920a090b261a0de315847a081a02e

**Comment by ibuziuk** [comment]
@benoitf thanks
@ericwill can we have it backported in the `7.32.1` and update the workspaces.openshift.com asap?

**Comment by ericwill** [comment]
> @benoitf thanks
> @ericwill can we have it backported in the `7.32.2` and update the workspaces.openshift.com asap?

Sure we can backport. Which version of the community devfile registry is deployed on workspaces.openshift.com at the moment?

**Comment by ibuziuk** [comment]
> Sure we can backport. Which version of the community devfile registry is deployed on workspaces.openshift.com at the moment?

7.32.0

**Comment by ericwill** [comment]
Looks like version 7.32.2 of the devfile registry is already out. Can it wait until 7.33 (next week)?

**Comment by ibuziuk** [comment]
@ericwill well, it can but this means that the angular on http://workspaces.openshift.com/#get-started is going to be broken for 7+ days

**Comment by ericwill** [comment]
> @ericwill well, it can but this means that the angular on http://workspaces.openshift.com/#get-started is going to be broken for 7+ days

Alright, instead of respinning I will backport the fix to the published devfile registry only

**Comment by ibuziuk** [comment]
@ericwill please, let me know which community registry link contains a fix, and I will bump production

**Comment by benoitf** [comment]
maybe we need '.x' branch publication as well in addition to tags

**Comment by ericwill** [comment]
I've updated all 7.32.x Angular devfiles, i.e.:

https://eclipse-che.github.io/che-devfile-registry/7.32.0/devfiles/nodejs-angular/devfile.yaml
https://eclipse-che.github.io/che-devfile-registry/7.32.1/devfiles/nodejs-angular/devfile.yaml
https://eclipse-che.github.io/che-devfile-registry/7.32.2/devfiles/nodejs-angular/devfile.yaml

**Comment by ericwill** [comment]
> maybe we need '.x' branch publication as well in addition to tags

It wouldn't help in this case unless we respin, because backport would come after the last 7.32.x release

**Comment by benoitf** [comment]
I mean everytime we push to '7.32.x' branch it updates /7.32.x/
We don't override tags like 7.32.1, 7.32.2 etc as it should be immutable


I don't see why it wouldn't work. DevSandbox will just use '7.32.x' instead of 7.32.1, 7.32.2 etc

**Comment by ibuziuk** [comment]
thanks, folks
verified on workspaces.openshift.com. Closing
