### ISSUE TITLE
Hosted instance has been terminated

### ISSUE THREAD

**Issue by gautam-borkar** [eclipse-che/che#20043]
### Describe the bug
I am writing a plugin for che-theia and want to launch an instance of a plugin under development. I run the command `Hosted Plugin: Start Instance`. 

However I see the below error message :- 
```
2021-06-30 14:04:01.902 root INFO Deploy plugins list took: 13372.7 ms 

Hosted instance has been terminated
Extension-Host:PLUGIN_HOST(44): PluginManagerExtImpl/loadPlugin(/default-theia-plugins/vscode-builtin-js-debug/extension/src/extension.js)
Extension-Host:Debug configuration provider has been registered: pwa-chrome
Extension-Host:Debug configuration provider has been registered: pwa-msedge
Debug configuration provider has been registered: pwa-extensionHost
Debug configuration provider has been registered: pwa-node
Debug configuration provider has been registered: node-terminal
Debug configuration provider has been registered: pwa-chrome
Debug configuration provider has been registered: pwa-msedge
Debug configuration provider has been registered: pwa-node
Debug configuration provider has been registered: pwa-node
Extension-Host:The port 3130 is no longer listening on interface ::
```

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: please specify : 7.32.0

### Steps to reproduce
1.  Create workspace with git :- https://github.com/eclipse/che-theia-samples/tree/master/samples/hello-world-backend-plugin
2. Click `Ctrl+Shift+P` and select `Hosted Plugin: Start Instance`. 
3. See error in output tab.

### Expected behavior
A new theia instance, which is identical to your development environment, but additionally host the deployed plugin under development.

### Runtime
   - [x] kubernetes 
   ```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15",
GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z",
GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [x] other: 
   ```
NAME="CentOS Linux"
VERSION="7 (Core)"
```
   
### Eclipse Che Logs
[output.log](https://github.com/eclipse/che/files/6741671/output.log)

**Comment by benoitf** [comment]
Hello @gautam-borkar 

could you please file the bug using the template provided for bugs https://raw.githubusercontent.com/eclipse/che/main/.github/ISSUE_TEMPLATE/bug_report.md

Because here you're missing lot of useful data.
like che version, how you're launching the command, etc

**Comment by gautam-borkar** [comment]
@benoitf I have updated the description per the `md` file.

**Comment by benoitf** [comment]
@gautam-borkar thanks
