### ISSUE TITLE
add configbump branch creation to che release process

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20053]
### Is your task related to a problem? Please describe.

Along with JWTProxy and KIP projects, which don't release regularly but which need to be branched so that we can avoid getting main branch changes mixed in to the stable CRW builds, configbump should have branches too.

```
branchJWTProxyAndKIP() {
    invokeAction eclipse/che-jwtproxy "Create branch" "5410230" "branch=${BRANCH}"
    invokeAction che-incubator/kubernetes-image-puller "Create branch" "5409996" "branch=${BRANCH}"
}
```

### Describe the solution you'd like

Add a new invokeAction call for che-incubator/configbump to create a branch for each new che release branch, which we can then use in downstreaming.

**Comment by nickboldt** [comment]
Next step: adding branch creation to the che-release process... https://github.com/eclipse-che/che-release/pull/39

... and verifying it works. Locally, I couldn't make this work. Unclear why - wrong workflowID? missing token? wrong token? missing permissions on the repo for che-incubator bot to push changes?

**Comment by mkuznyetsov** [comment]
branch creation job is verified to be working and included into release automation framework https://github.com/che-incubator/configbump/actions/runs/1074750043
