### ISSUE TITLE
Cluster role left behind after server delete

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#20065]
### Describe the bug
The `chectl server:delete` command should clear everything Che-related from the cluster. The `che-operator-proxy` cluster role and cluster role binding are still present in the cluster after running the server delete though.

### Che version
latest

### Steps to reproduce
1. `chectl server:deploy ...`
2. `chectl server:delete`
3. `oc get clusterroles | grep che`
4. `oc get clusterrolebindings | grep che`

### Expected behavior
The last two commands from the repro steps shouldn't return any results related to Che, but both contain `che-operator-proxy` object (either a clusterrole or a binding).

### Runtime
any supported

### Screenshots
N/A

### Installation method
chectl

### Environment
any

### Eclipse Che Logs
N/A

**Comment by tolusha** [comment]
I've just tested and don't find any issues.
Probably fixed by https://github.com/che-incubator/chectl/pull/1367
