### ISSUE TITLE
Adapt Che-Theia to upstream changes (Monaco)

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#20069]
### Is your task related to a problem? Please describe.

We need provide some adaptation on `che-theia` side after upgrade `Monaco` version in upstream.

![errors_monaco](https://user-images.githubusercontent.com/5676062/124280218-179e0d00-db51-11eb-858f-0ee9993ff0f0.png)

### Describe the solution you'd like

Need to adapt Che-Theia to the upstream changes.

**Comment by RomanNikitenko** [comment]
depends on https://github.com/eclipse/che/issues/20076

**Comment by RomanNikitenko** [comment]
We need provide some adaptation for the Happy path tests after upgrade Monaco version in upstream: https://github.com/eclipse/che/issues/20172

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse-che/che-theia/pull/1171
