### ISSUE TITLE
The "TypescriptPlugin" fails because of no debug config displays

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20067]
### Is your task related to a problem? Please describe.

The "TypescriptPlugin" fails because of no debug config displays

### Describe the solution you'd like

Add refreshing page in a case if debug config is not displayed

**Comment by dmytro-ndp** [comment]
Similar problem has been reproduced in Happy path test https://github.com/eclipse/che/issues/20046

**Comment by Ohrimenko1988** [comment]
Fixed https://github.com/eclipse/che/pull/20079
