### ISSUE TITLE
Align CheWebviewEnvironment to upstream changes

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#20077]
### Is your task related to a problem? Please describe.

Warnings related to webview and mini-browser endpoints are displayed at starting a workspace.
Please see the screenshot below.

The behaviour was caused by [changes in upstream](https://github.com/eclipse-theia/theia/commit/112d7243e420f066b894abe10c4249e879bad10a).

### Describe the solution you'd like

We should investigate and provide the corresponding alignment for [CheWebviewEnvironment](https://github.com/eclipse-che/che-theia/blob/909e6974240a6c137647dafe09dc23a8af7638e0/extensions/eclipse-che-theia-plugin-ext/src/browser/che-webview-environment.ts#L21)

### Additional context

![webview_endpoint](https://user-images.githubusercontent.com/5676062/124567360-9abeac00-de4c-11eb-9fa7-21f317c12677.png)

**Comment by l0rd** [comment]
@svor do you think that your team could take this issue in current sprint?

**Comment by svor** [comment]
> @svor do you think that your team could take this issue in current sprint?

@l0rd we'll take a look at it. Added as unplanned into current sprint
