### ISSUE TITLE
Failed to run debug session in the "NodeJS Express Web Application" based workspace

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20075]
### Describe the bug

Failed to run debug session in the "NodeJS Express Web Application" based workspace

### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Go to dashboard and create workspace using the "NodeJS Express Web Application" default devfile
 - Go inside created workspace and run the "download dependencies" preinstalled command
 - Run the "run the web app (debugging enabled)" preinstalled command
 - Go to the debug view and run the "Attach to Remote (node-js-web-app)" debug configuration
 - Pay attention to the error notification (debug logs and screenshot in attachments)

### Expected behavior
Debug session has been run

### Observed behavior
Debug session has failed to start

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ x ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
```
chectl server:deploy \
  --k8spodreadytimeout=600000 \
  --k8spodwaittimeout=600000 \
  --k8spoddownloadimagetimeout=600000 \
  --listr-renderer=verbose \
  --platform=minikube \
  --chenamespace=iokhrime-che \
  --telemetry=off
```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ x ] my computer
       - [ ] Windows
       - [ x  ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs

[debug.log](https://github.com/eclipse/che/files/6764180/debug.log)

### Additional context

![Screenshot from 2021-07-05 15-11-26](https://user-images.githubusercontent.com/22724619/124471920-292c2280-dda6-11eb-98f3-73681977b0d7.png)

**Comment by tsmaeder** [comment]
@Ohrimenko1988 anything interesting in the browser or Theia container logs?

**Comment by Ohrimenko1988** [comment]
I haven't seen error's in the browser or in containers. Only in debug ext container (logs in the description https://github.com/eclipse/che/files/6764180/debug.log)

**Comment by tsmaeder** [comment]
Oddly, the only exception in the log is the same as in https://github.com/eclipse/che/issues/18455. Are we using an old version of the plugin host runtime?

**Comment by svor** [comment]
After fixing a problem need to activate TypescriptPlugin test, see https://github.com/eclipse-che/che-plugin-registry/pull/1017/files#diff-298fe638eadfc88982df332f4d56a871a7f3b4b262363c047628ed1056beb8b2R30

**Comment by tsmaeder** [comment]
This sounds like something that is fixed in Theia: https://github.com/eclipse-theia/theia/pull/9730

**Comment by tsmaeder** [comment]
Indeed, it's fixed in che-theia:next. 

@Ohrimenko1988 the relevant stack trace is visible in the container log of the node debug plugin. Unfortunately, the only way to get those logs is through the OpenShift console (for my dogfooding instance something like https://console-openshift-console.apps.che-dev.x6e0.p1.openshiftapps.com/k8s/ns/tsmaeder-che/pods/workspacenxxxx....).
