### ISSUE TITLE
Happy path checks fail for che-theia: "Command server:deploy failed"

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#20076]
### Describe the bug

The issue was detected on  `che-theia` PR's check.

In the logs I see the following:

```
'[11:47:28] Enable minikube ingress addon [started]\n' +
    '[11:48:28] Enable minikube ingress addon [failed]\n' +
    '[11:48:28] → Command timed out after 60000 milliseconds: minikube addons enable ingress\n' +
    'Timed out\n' +
    '  - Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0\n' +
    '  - Using image docker.io/jettech/kube-webhook-certgen:v1.5.1\n' +
    '  - Using image docker.io/jettech/kube-webhook-certgen:v1.5.1\n' +
    '* Verifying ingress addon...\n' +
    '[11:48:28] ✈️  Minikube preflight checklist [failed]\n' +
    '[11:48:28] → Command timed out after 60000 milliseconds: minikube addons enable ingress\n' +
    'Timed out\n' +
    '  - Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0\n' +
    '  - Using image docker.io/jettech/kube-webhook-certgen:v1.5.1\n' +
    '  - Using image docker.io/jettech/kube-webhook-certgen:v1.5.1\n' +
    '* Verifying ingress addon...',
  stderr: '    Error: Command server:deploy failed. Error log: \n' +
    '    /home/runner/.cache/chectl/error.log. Eclipse Che logs: \n' +
    '    /tmp/chectl-logs/1625485648085.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
``` 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

I detected a problem on the `che-theia` PR's checks.
Please see https://github.com/eclipse-che/che-theia/pull/1157

### Screenshots

![errors_che-theia](https://user-images.githubusercontent.com/5676062/124477306-904cd580-ddac-11eb-9f6a-dab856f73ea9.png)

**Comment by mmorhun** [comment]
> Command timed out after 60000 milliseconds: minikube addons enable ingress

This is infrastructure issue

**Comment by RomanNikitenko** [comment]
Restarting jobs few times didn't help, will try one more time + check if it depends somehow on `minikube` version.

**Comment by RomanNikitenko** [comment]
It looks like it really depends somehow on the `minikube` version - switching to `1.21.0` fixes the problem...
I'm going to prepare a PR to `che-theia` to change the `minikube` version.

**Comment by ibuziuk** [comment]
@RomanNikitenko looks like you are on the right track with the PR with a fix, assigning to you based on the draft PR

**Comment by RomanNikitenko** [comment]
I have changed the severity to P1 as at the moment there is no way to merge any PR to che-theia without those happy path checks.

**Comment by RomanNikitenko** [comment]
should be fixed by https://github.com/eclipse-che/che-theia/commit/9f2aaf97c494ef9f4519a25298e1bad035463cec
