### ISSUE TITLE
Make DevWorkspaceRouting a pre-requisite of che-operator

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#20088]
### Is your task related to a problem? Please describe.
Currently,  we have che-operator (CO) and devworkpace che operator (DWCO) running as separate containers in a single pod. In addition to other responsibilities, CO is in charge of enabling the support for Devworkspaces. This includes the installation of all the necessary CRDs (i.e. DevWorkspace, DevWorkspaceTemplate, DevWorkspaceRouting and possibly others, depending on what DWO declares).

DWCO requires `CheCluster` and `DevWorkspaceRouting` for its operation.

In order to be able to run DWCO and CO as a single executable, we need `DevWorkspaceRouting` pre-installed in the cluster.

### Describe the solution you'd like
Pre-install the `DevWorkspaceRouting` CRD (defined in the DWO codebase) before installing the che-operator.

### Describe alternatives you've considered
We can also keep the codebases separate and co-deploy the CO and DWCO containers in the operator pod as is done at the moment (doing that enables us to wait until all the CRDs are available before starting the controller manager in DWCO).

**Comment by metlos** [comment]
@l0rd what do you prefer?

1. Merging the codebases makes the life easier for future development and removes 1 image from our deliverables, but requires part of the "devworkspace ecosystem" be preinstalled even if devworkspaces are disabled.
2. Keep the CO and DWCO codebases separate (2 deliverables instead of one, slightly more complex dependency structure) but be able to "flip on and off" devworkspaces completely.

**Comment by l0rd** [comment]
@metlos 👍 for option 1

**Comment by metlos** [comment]
The DWR CRD cannot be pre-installed the way we imagined in this issue.
