### ISSUE TITLE
As an Admin, I want to update the list of default images for pre-pulling when a new version of Eclipse Che is rolled out

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20081]
### Is your task related to a problem? Please describe.
This task is a follow-up work on the https://github.com/eclipse/che/issues/19657
Now we can identify the good defaults for Kubernetes Image Puller during the installation, however when the rollout update of a new version happens the list of images for pre-pulling should be updated accordingly.

https://issues.redhat.com/browse/CRW-2107

### Describe the solution you'd like
1. Eclipse Che is installed with the Image puller enabled
2. The default set of images for pre-pulling is identified https://github.com/eclipse/che/issues/19657
3. A new version of Eclipse Che has been rolled out
4. The list of images for pre-pulling is updated

### Describe alternatives you've considered
N/A

### Additional context
Related issues:
 - #18133 
 - #19657

### Release Notes text
The list of the images to pull is automatically updated on each Eclipse Che update.
It allows to have Kubernetes Image puller to pull always up-to-date images and have faster workspaces.

**Comment by ibuziuk** [comment]
@dkwon17 PR is ready to be merged - https://github.com/eclipse-che/che-operator/pull/940
Please, provide relevant documentation changes to https://www.eclipse.org/che/docs/che-7/administration-guide/installing-image-puller-using-che-operator/

**Comment by dkwon17** [comment]
Thank you, I will make changes to the docs

**Comment by ibuziuk** [comment]
Going to close once the doc PR is merged - https://github.com/eclipse/che-docs/pull/2065

**Comment by ibuziuk** [comment]
doc PR has been merged. Closing
