### ISSUE TITLE
Currently it is not possible to differentiate `che_plugin_sidecar_plugin_registry_image` from the RELATED_IMAGEs 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20089]
### Is your enhancement related to a problem? Please describe.
CSV contains a bunch of the  `che_plugin_sidecar_plugin_registry_image` Related Images - https://github.com/operator-framework/community-operators/blob/b560ec81cd4e586e9cb05c3674426da4971ba3b3/community-operators/eclipse-che/7.32.0/eclipse-che.v7.32.0.clusterserviceversion.yaml#L1029-L1079 

This becomes a problem if we want to automatically pre-pull by default some of the sidecar images e.g. `java8`
Currently, it is simply not possible to differentiate those, since all of them are using the same image names and different digests, and it is only possible to identify by tag names - https://quay.io/repository/eclipse/che-plugin-sidecar?tag=latest&tab=tags

### Describe the solution you'd like
It should be possible to differentiate in the CSV `che_plugin_sidecar_plugin_registry_image`

### Describe alternatives you've considered
Not pre-pull sidecar images at all by default 

### Additional context
This issue is related to https://github.com/eclipse/che/issues/19657

**Comment by ibuziuk** [comment]
@nickboldt would be great to get your input on this

**Comment by tolusha** [comment]
Theoretically we can include image tag in RELATED_IMAGE env var name like this:
`RELATED_IMAGE_che_plugin_sidecar_plugin_registry_image_java8_1273116_<....>`
Will it fit your needs?

**Comment by ibuziuk** [comment]
@tolusha that would be great! 
cc @dkwon17 I believe we will be able to retrieve the required images based on the pattern in this case

**Comment by ibuziuk** [comment]
will it be possible to get rid of the base32 encoding as part of this issue, which looks like overkill?
Basically I would propose replacing
```
RELATED_IMAGE_che_theia_plugin_registry_image_IBZWQYJSGU3DUMJVGBQTSM3DGEZTMMTDMJRTMOBTG5STMYLFMVRDMNBUME4TCYJXGBQTKZTCGYZTAMZRMUZDGNJVGJTDAMLEHEZTMYJSMIZTCMTFMQ3Q____
                        value: quay.io/eclipse/che-theia@sha256:150a93c1362cbc6837e6aeeb644a91a70a5fb63031e23552f01d936a2b312ed7
```
with
```
RELATED_IMAGE_che_theia_plugin_registry_image
                        value: quay.io/eclipse/che-theia@sha256:150a93c1362cbc6837e6aeeb644a91a70a5fb63031e23552f01d936a2b312ed7 
```

**Comment by tolusha** [comment]
Does it cause any issues besides overkill?

**Comment by ibuziuk** [comment]
> Does it cause any issues besides overkill?

not, this just looks pretty sophisticated, and there is going to be no need for this. IMO we should keep it as simple as possible

**Comment by AndrienkoAleksandr** [comment]
plugin_registry_image/devfile_registry_image postfix was used, because che-operator have to filter images, and inject to the corresponding image registries.

**Comment by ibuziuk** [comment]
@tolusha @AndrienkoAleksandr just to be clear I'm fine if you would like to continue doing base32 encodings, the most imporatnt thing for us atm is to have possibility to differentiate in the CSV `che_plugin_sidecar_plugin_registry_image` by the var name - other stuff is optional

**Comment by nickboldt** [comment]
FWIW here's what we have in the digest pinned version of the CRW csv:

https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-operator-metadata-generated/manifests/codeready-workspaces.csv.yaml#L994

(it's even sorted alphabetically because it avoids random nuissance commits when syncing from upstream.)

Here's the unpinned version (with tags instead of digests):

https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-operator-metadata/manifests/codeready-workspaces.csv.yaml#L1012

As you can see, it's cleaner and easier to read... just uses the image path to create the RELATED_IMAGE_* variables.

**Comment by nickboldt** [comment]
> plugin_registry_image/devfile_registry_image postfix was used, because che-operator have to filter images, and inject env variables to the corresponding image registries.

Would this need go away if we fix https://github.com/eclipse/che/issues/19736 and the registries can simply fetch their images from the CSV's RELATED_IMAGE_* list (or the operator's env vars) ?

**Comment by tolusha** [comment]
I though it was relatively easy to differentiate images by adding tag to env var name.
But now I don't think so. Sidecar images are already referenced by digests in a plugin-registry and I don't see a way to figure out their tags.

**Comment by ibuziuk** [comment]
@ericwill @svor any ideas how can we differentiate `che_plugin_sidecar_plugin_registry_image`  ^ ?
