### ISSUE TITLE
Display Kubernetes Image Puller images in multiple lines

### ISSUE THREAD

**Issue by dkwon17** [eclipse-che/che#20084]
### Is your enhancement related to a problem? Please describe.

When creating a new instance of Kubernetes Image Puller via the Kubernetes Image Puller operator from OperatorHub, it would be great if the images were displayed in multiple lines (one image per line), rather than displaying the images in a single, semi-colon separated string:

![image](https://user-images.githubusercontent.com/83611742/124649669-ca7aad80-de66-11eb-86e0-43252967621e.png)

### Describe the solution you'd like

The following UI is easier to navigate, especially if there are many default images.
![image](https://user-images.githubusercontent.com/83611742/124650152-686e7800-de67-11eb-81ba-ae3b07706283.png)

Something similar to the image above would be great.

Also, I'm not sure how feasible this is, but maybe a UI that displays the images as rows of key-value pairs instead would also be nice.

### Additional context

This feature would be great especially if there are more default images in the future.
Relevant comment: https://github.com/eclipse-che/che-operator/pull/880#issuecomment-875039444

**Comment by ibuziuk** [comment]
Moving to the next prioritization. This feature depends on https://github.com/eclipse-che/che-operator/pull/880/files
