### ISSUE TITLE
Errors notifications shown during trying to invoke the python language server functions

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20093]
### Describe the bug

Errors notifications shown during trying to invoke the python language server functions
### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Go to dashboard and create workspace using the "Python" default devfile
 - Go inside created workspace and open the "hello-world.py" file
 - Try to press the "ctrl + space" combination on the "print" word
 - Pay attention to the shown error notifications https://user-images.githubusercontent.com/22724619/124749756-4dfed200-df2d-11eb-9ee0-8ae701c07085.png
 - Pay attention that functionality works despite errors. https://user-images.githubusercontent.com/22724619/124749991-98804e80-df2d-11eb-8e6f-2ce606d7595a.png
 - Type the "err" word at the 7-th row to invoke error highlighting
 - Pay attention that error highlighting doesn't work https://user-images.githubusercontent.com/22724619/125253211-d8ff1400-e301-11eb-8676-a4994c614362.png

### Expected behavior
The language server functionality works and no error message shown

### Observed behavior
The autocomplete functionality works but notifications with error messages are shown.
Error highlighting doesn't work.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ x ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2021-07-07 13-56-37](https://user-images.githubusercontent.com/22724619/124749756-4dfed200-df2d-11eb-9ee0-8ae701c07085.png)

![Screenshot from 2021-07-07 14-13-51](https://user-images.githubusercontent.com/22724619/124749991-98804e80-df2d-11eb-8e6f-2ce606d7595a.png)

![Screenshot from 2021-07-12 11-09-26](https://user-images.githubusercontent.com/22724619/125253211-d8ff1400-e301-11eb-8676-a4994c614362.png)

**Container logs:**
[python-container.log](https://github.com/eclipse/che/files/6776656/python-container.log)

### Installation method
   - [ x ] chectl
```
chectl server:deploy \
  --k8spodreadytimeout=600000 \
  --k8spodwaittimeout=600000 \
  --k8spoddownloadimagetimeout=600000 \
  --listr-renderer=verbose \
  --platform=minikube \
  --chenamespace=iokhrime-che \
  --telemetry=off
```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by l0rd** [comment]
It may make sense to add it in the release notes now that it has been fixed.
