### ISSUE TITLE
Server 'terminal' in container 'che-machine-exec672' not available.

### ISSUE THREAD

**Issue by gautam-borkar** [eclipse-che/che#20098]
### Describe the bug
Failed to start kubernetes workspace error message :- `Server 'terminal' in container 'che-machine-exec672' not available.`. 

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: `7.32.0`

### Steps to reproduce
- Install che with command :- `chectl server:deploy --platform k8s --domain <domain-name> --installer=operator` with trusted CA for the domain.
- Click on create workspace
- Select NodeJS express sample
- See error message in the logs

### Expected behavior
Workspace should be running without any error.

### Runtime
   - [x] kubernetes 
   ```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: `centOS, k8s`

### Installation method
   - [x] chectl
     * chectl server:deploy --platform k8s --domain <domain-name> --installer=operator
     * chectl version :- `chectl/7.32.2 linux-x64 node-v12.22.1`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [x] other: CenOS

### Eclipse Che Logs
[che.log](https://github.com/eclipse/che/files/6780952/che.log)

### Additional context
Eclipse che installation with self-signed certificate is working fine.

**Comment by tolusha** [comment]
To check if certificates configured correctly.
1. Try exec into che-server pod
```
echo "$CHE_SELF__SIGNED__CERT" > /tmp/ca.crt
```
2. start a workspace
3. Find workspace ingress ending with `server-4402`
4. Exec into che-server pod
```
curl -v --cacert  /tmp/ca.crt https://<domain>/serverhcychrl4-jwtproxy/server-4402/ (serverhcychrl4-jwtproxy will be different for a new workspace)
```

**Comment by mmorhun** [comment]
Hello @gautam-borkar 
By `trusted CA for the domain` do you mean commonly trusted certificate or institutional one?
Could you please show certificates chain that your ingresses return? Is the output of:
```bash
openssl s_client -showcerts -connect <che-url-without-protocol>:443
```
If you don't want to share the domain, please send the output to me and @tolusha in mattermost

**Comment by gautam-borkar** [comment]
> 1. Patch checluster CR to add some logger for che-server
> 
> ```
> oc patch checluster/eclipse-che --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_LOGGER_CONFIG\": \"org.eclipse.che.api.workspace.server.hc.HttpConnectionServerChecker=DEBUG\"}}}}" --type=merge -n che
> ```
> 
> 1. Try to start a workspace. Let's check if we have more information.

@tolusha I am seeing lot of `2021-07-08 16:03:27,756[ServersChecker]   [DEBUG] [.h.HttpConnectionServerChecker 116]  - Failed to establish http connection to check server 'theia:https://servere1h0l7qj-jwtproxy-server-4402.open-trial-labs.ibm.com/'. Cause: servere1h0l7qj-jwtproxy-server-4402.open-trial-labs.ibm.com`.

[che.log](https://github.com/eclipse/che/files/6785894/che.log)

**Comment by gautam-borkar** [comment]
> echo "$CHE_SELF__SIGNED__CERT" > /tmp/ca.crt

I tried to exec to `che-86gtma9yy-d8amc` pod and did a `echo "$CHE_SELF__SIGNED__CERT"`. But output is empty :- 
```
CHE_SELF__SIGNED__CERT=
CHE_GIT_SELF__SIGNED__CERT=
CHE_GIT_SELF__SIGNED__CERT__HOST=
```

**Comment by gautam-borkar** [comment]
> Hello @gautam-borkar
> By `trusted CA for the domain` do you mean commonly trusted certificate or institutional one?
> Could you please show certificates chain that your ingresses return? Is the output of:
> 
> ```shell
> openssl s_client -showcerts -connect <che-url-without-protocol>:443
> ```
> 
> If you don't want to share the domain, please send the output to me in mattermost

@mmorhun I am getting this error for the command above :- 
`verify error:num=20:unable to get local issuer certificate`

**Comment by gautam-borkar** [comment]
*Note:-* In checluster resource I have both signedCertificate and tlsSupport as true.

**Comment by mmorhun** [comment]
> verify error:num=20:unable to get local issuer certificate

This means the certificate is not commonly trusted.
To trust the certificate, please follow [Che docs](https://www.eclipse.org/che/docs/che-7/installation-guide/importing-untrusted-tls-certificates/)
Also please note, that it is required to have whole certificates chain in the configmap: from the 'lowest' CA till root.

**Comment by mmorhun** [comment]
@gautam-borkar in general my advice will be:
1. Make sure that your certificates are not expired. If so, request a new one.
2. When certificates are ok, configure your cluster with it
3. Completely delete Che (you've changed some secrets manually that might brake something)
4. In Che namespace (`eclipse-che` by default) create a configmap with additional certificate chain until root CA (server one should not be included). See [docs](https://www.eclipse.org/che/docs/che-7/installation-guide/importing-untrusted-tls-certificates/).
5. Deploy new Che in the namespace

**Comment by gautam-borkar** [comment]
Thank you very much @tolusha @mmorhun for all your help!

**Issue**
Che was deployed with multi-host strategy. And hence when workspace was created it was trying to access `https://servere1h0l7qj-jwtproxy-server-4403.<domain>` using ingress and the DNS was not able to resolve this host.

**Fix for the issue**
Deployed eclipse-che with single-host strategy. 
Steps for deployment :- https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspace-exposure-strategies/

Closing this ticket now.
