### ISSUE TITLE
Investigate how to use images built from Dockerfiles with docker in swarm mode

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2009]
Docker 1.12 in swarm mode doesn't support build of images from Dockerfiles. 
We need to know how to use such images because Dockerfile is convenient way of container describing for users and we don't want to disallow users to use them.
We would want to omit special type of machine nodes for image builds. It can complicate our infrastructure. So we expect that Che code will be able to use the same nodes that run containers as build nodes.

**Comment by l0rd** [comment]
The Docker API should still be available. Swarm and Docker API are both available but on different TCP ports.

**Comment by garagatyi** [comment]
Yes, but we won't control where container will be scheduled, so can't build image on that node. On the other hand docker will try to pull image and fail.

**Comment by l0rd** [comment]
Oh I see what you mean. Docker built it locally somewhere but swarm cannot start it on another node because the image cannot be found. Is it right?

**Comment by garagatyi** [comment]
Yes, exactly.

**Comment by l0rd** [comment]
Maybe using a affinity filter wher running the container can help? 

``` sh
-e affinity:image==<image-name>
```

would make the container run only on nodes where <image-name> already exists.

**Comment by garagatyi** [comment]
In that case we will lose scheduling of swarm mode and will have to reimplement it

**Comment by l0rd** [comment]
Reimplementing task scheduling in Che makes no sense. Filters are a Swarm feature and you don't have to feel guilty for using them 😱 ! In the end you will have:
- The Che server is scheduled by Swarm on an arbitrary node
- The workspaces are scheduled by Swarm to run on the server node

But if you want workspaces to be scheduled to run on arbitrary nodes too there is still a solution for that too 😄  You can achieve it with a special container. Let's call it `che-worspace-launcher`. This container would build and run workspaces on its docker host. `che-workspace-launcher` would be run by Che and scheduled by Swarm.

**Comment by TylerJewell** [comment]
Will not implement - instead moving to kubernetes.
