### ISSUE TITLE
What is wrong with installation: Che API is not available, air gapped environment on K8s AWS ?

### ISSUE THREAD

**Issue by KevinQSmith** [eclipse-che/che#20097]
Hello,

I am trying to install Eclipse Che version 7.29.1 in an air gapped environment and have run into an issue.  We are using Helm, Chectl, and Kubectl on a Linux EC2 instance that’s connected to a Kubernetes cluster in AWS.  I have followed this documentation to set it up in a multiuser environment: https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-aws/ 
Once we figured out how to install in the air gapped environment, the install went smoothly with no errors. 

Here is the issue I am hitting: 
 
![Screenshot of Issue](https://user-images.githubusercontent.com/87094753/124821441-b608e480-df3c-11eb-88dd-292728716a7f.png)

Here is our ingress file that is used in conjunction with the one in the docs above:
![Screenshot of ingress file](https://user-images.githubusercontent.com/87094753/124821464-be611f80-df3c-11eb-861b-890eef916bf2.png)
 
Here is also our requirements.yaml which helm uses to install.  Due to an air-gapped deployment, the file property is pointing to “custom-charts” so we can reference these images from our internal image repo.
![Screenshot of our Requirements yaml](https://user-images.githubusercontent.com/87094753/124821462-bdc88900-df3c-11eb-802b-3540cc0eddfd.png)
 
Here is the version of the installed software tools:

Helm: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Chectl: chectl/7.30.1 linux-x64 node-v12.22.1

Kubectl: Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Here is the install command we are using:
`chectl server:deploy --installer=helm --platform=k8s --domain=che.domain.com --multiuser`

There is not too much information online about this issue.  I have found this:
https://github.com/eclipse/che/issues/19465 

And this

https://github.com/eclipse/che/issues/19611 which has been closed and patched in the 7.29.0 version, however we are still hitting the issue.

### Describe the bug
Error: Unable to get available storage types.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify
 - **7.29.1**

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
I'm not able to reproduce it on minikube when I deploy Che with `chectl server:deploy --installer=helm --platform=minikube --multiuser`.

@KevinQSmith could you share response of `/api/workspace/settings` request? I have 
![Screenshot_20210708_104542](https://user-images.githubusercontent.com/5887312/124883243-cd49df80-dfd9-11eb-902e-f67ad20e5ca7.png)

**Comment by KevinQSmith** [comment]
Hi Sleshchenko, thank you for your reply.  

I am unable to hit `che.domain.com/api/workspace/settings` I just receive a 404.

If this helps, here is a screenshot of our /dashboard route with the call to the settings url.

![Screenshot of settings call from dashboard page](https://user-images.githubusercontent.com/87094753/124959248-0473bd00-dfe9-11eb-94a9-7e3811c808d9.jpg)

**Comment by sleshchenko** [comment]
@KevinQSmith
Well, I missed that from the beginning, ingresses rules does not seem to be the right.

- `che-dashboard` should be available at /dashboard (now /)
- `che-host` should be / (now /host)
- `che-devfile-registry` should be /che-devfile-registry
- `postgres` does not need ingress at all

Could you iterate on your configuration?
