### ISSUE TITLE
If there are no projects in devfile then empty workspace is not ready to use

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#20109]
I want to create an empty workspace and let the user ability to create any folders that he wants.
But if section "projects" in devfile is an empty array then the user cannot create folder

I know that WA exists. User can choose /projects via the "Open Workspace" menu item. But it is not convenient way.

### Che version
7.32.1

### Screenshots
![image](https://user-images.githubusercontent.com/2270831/124930662-334e5b00-e00a-11eb-814e-b0a7fef080de.png)

**Comment by RomanNikitenko** [comment]
should be fixed by https://github.com/eclipse-che/che-theia/pull/1123

**Comment by gorshkov-leonid** [comment]
@RomanNikitenko, @sleshchenko I tested 7.34.1, and what I noticed. After clone git repository via command 'Git clone' I have a suggestion to Open, Open in New Window and Add folder to Workspace. All is ok except my case. I have a language server(yang-vscode) that does not support multi-root projects. Even if I closed the suggestion dialog with a cross then the folder would have been added to the workspace. 
For example, `/projects` is chosen as the only project of workspace. I call `Git clone` command, choose `/projects`, and expect that this folder will be shown under `/projects` in Explorer. But after that, I also have an additional root folder.

**Comment by RomanNikitenko** [comment]
Hello, @gorshkov-leonid!

> Even if I closed the suggestion dialog with a cross then the folder would have been added to the workspace.

- che works in the multi-root mode
- the system tracks `/projects` (as it's projects' root) using file watchers and adds any folder from `/projects` as a workspace folder of a multi-root workspace

**Comment by gorshkov-leonid** [comment]
@RomanNikitenko Thank you.  But my comment also relveals behaviour that different from VScode. In vscode if you do not want to add  folder to workspace then you can close suggestion dialog. In the case of Che folder will be added to the workspace in any case. I mean workspace, not filesystem.

**Comment by RomanNikitenko** [comment]
We track projects' root to add a folder to Che workspace (for example, user clones a project using a terminal). For the multi-root mode it's more common use case - clone a project and add it to the workspace...

About your use case, could you clarify a little:
- first you have a devfile without projects
- get a workspace like:
<img width="672" alt="Screenshot 2021-09-07 at 16 34 03" src="https://user-images.githubusercontent.com/5676062/132355075-a3531486-5aa1-44f4-8e6a-f79de3714dc7.png">

- then you go to `File` -> `Open` to open `projects`
- then clone a project using `Git clone` command

is it correct?
if so - for me it looks like you are trying to use the single root mode, but Che works in the multi-root mode...

Anyway, I think it's better to create a new issue, as the current one doesn't reflect the actual problem and your use case.
Then we could take a look how to improve the behaviour (I guess the dialog that you mentioned comes from upstream)...
