### ISSUE TITLE
Unable to create workspace from sample on K8s due wrong URLs reported by devfile registry

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20100]
### Describe the bug
Unable to create workspace from sample on K8s due wrong URLs reported by devfile registry:
![Screenshot_20210708_105729](https://user-images.githubusercontent.com/5887312/124884808-4d247980-dfdb-11eb-958d-53c5769459c6.png)

^ see the cluster internal IP is reported.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Deploy Che on K8s with helm chart (chectl server:deploy --installer=helm --platform=minikube --multiuser)
2. Open dashboard and check if samples have icons displayed.
3. Try to create a workspace with sample.

### Expected behavior
Icons are displayed and it's possible to create a workspace with sample.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
see avove

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by svor** [comment]
I don't see such problem with `--installer=operator`, only reproducible if use `helm`. @tolusha @mmorhun any idea what could be wrong?

**Comment by tolusha** [comment]
I see that che-server returns correct settings:

```json
{
  "supportedRecipeTypes": "kubernetes,no-environment",
  "che.workspace.auto_start": "true",
  "cheWorkspacePluginRegistryUrl": "https://plugin-registry-eclipse-che.192.168.99.100.nip.io/v3",
  "cheWorkspacePluginRegistryInternalUrl": "http://plugin-registry.eclipse-che.svc:8080/v3",
  "cheWorkspaceDevfileRegistryUrl": "https://devfile-registry-eclipse-che.192.168.99.100.nip.io",
  "cheWorkspaceDevfileRegistryInternalUrl": "http://devfile-registry.eclipse-che.svc:8080",
  "che.factory.default_plugins": "redhat/vscode-commons/latest",
  "che.factory.default_editor": "eclipse/che-theia/next",
  "che.workspace.storage.available_types": "persistent,ephemeral,async",
  "che.workspace.storage.preferred_type": "persistent",
  "che.devworkspaces.enabled": "false"
}
```

Is that dashboard who adjust url ?

**Comment by svor** [comment]
@tolusha probably che-devfile-registry [configmap](https://github.com/eclipse-che/che-server/blob/main/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/configmap.yaml) should contain env variable with URL like [here](https://github.com/eclipse-che/che-devfile-registry/blob/main/deploy/kubernetes/che-devfile-registry/templates/configmap.yaml#L26)

**Comment by vitaliy-guliy** [comment]
linking with https://github.com/eclipse/che/issues/19084

**Comment by tolusha** [comment]
@sleshchenko @svor 
Everything was working in 7.32.0
The problem can't be with helm templates.
https://github.com/eclipse-che/che-server/pull/48 is not relevant.

**Comment by svor** [comment]
@vitaliy-guliy Could you please check if the problem can be related to these changes https://github.com/eclipse-che/che-devfile-registry/pull/420

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy Could you please check if the problem can be related to these changes [eclipse-che/che-devfile-registry#420](https://github.com/eclipse-che/che-devfile-registry/pull/420)

Yes, checking it..

**Comment by vitaliy-guliy** [comment]
> @sleshchenko @svor
> Everything was working in 7.32.0
> The problem can't be with helm templates.
> [eclipse-che/che-server#48](https://github.com/eclipse-che/che-server/pull/48) is not relevant.

Links to the devfiles were wrong for single-host deployments.
We form links, based on CHE_DEVFILE_REGISTRY_URL and it must be set into devfile registry container.

When deploying Che with helm, the variable is not set.

You could also open the conrainer logs and scroll to top.
There is a message, indicating missing variable.
```
WARNING: environment variable 'CHE_DEVFILE_REGISTRY_URL' not configured for an offline build of this registry. This may cause issues with importing projects in a workspace.
```

**Comment by tolusha** [comment]
I've just deployed 7.32.0
I see the very same message
```
WARNING: environment variable 'CHE_DEVFILE_REGISTRY_URL' not configured for an offline build of this registry. This may cause issues with importing projects in a workspace.
```
But I can create a workspace.

**Comment by svor** [comment]
It means that `CHE_DEVFILE_REGISTRY_URL` environment variable wasn't set  for che-devfile-registry pod, probably the message should be improved. For my understanding `CHE_DEVFILE_REGISTRY_URL` should be defined in any case. If to compare configmap deployed via operator and helm we can see that env was set in operator deployment:
![screenshot-127 0 0 1_34883-2021 07 13-09_56_36](https://user-images.githubusercontent.com/1271546/125409074-36f43000-e3c4-11eb-9993-45e7e861735c.png)
but it is absent in the helm deplpoyment:
![screenshot-127 0 0 1_34883-2021 07 13-10_13_49](https://user-images.githubusercontent.com/1271546/125409361-7e7abc00-e3c4-11eb-8c51-5209668cc3fa.png)
