### ISSUE TITLE
Test golang example failed in Go test devfile

### ISSUE THREAD

**Issue by Warfvf** [eclipse-che/che#20104]
### Describe the bug

Currently, there are wrong paths to required folders in product devfile.
We need to edit the paths.

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: please specify

### Steps to reproduce

* start `Go` test

### Expected behavior

All testing suites passed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (output of `minikube version` and output of `kubectl version`):
   ```
   $ minikube version
   minikube version: v1.18.0
   commit: ec61815d60f66a6e4f6353030a40b12362557caa-dirty
   ```
   ```
   $ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"e29b355e74c9efd4491d64b9bb013c6091770d20", GitTreeState:"clean", BuildDate:"2021-06-03T23:21:41Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
   ```
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/57172594/124909061-50733180-dfea-11eb-8b3c-c0e8d1e688cf.png)
![image](https://user-images.githubusercontent.com/57172594/124914593-d2feef80-dff0-11eb-8317-eab5a78ba283.png)
![image](https://user-images.githubusercontent.com/57172594/124914603-d6927680-dff0-11eb-8b40-a97bff9bef6d.png)
![image](https://user-images.githubusercontent.com/57172594/124914616-d98d6700-dff0-11eb-803d-1089cc46c2fa.png)

### Installation method
   - [x] chectl 
     * provide a full command that was used to deploy Eclipse Che (including the output): `chectl server:deploy --platform minikube`
     * provide an output of `chectl version` command:  `chectl/0.0.20210707-next.2f8c67a linux-x64 node-v12.22.1`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs

N/A
### Additional context

N/A

**Comment by ScrewTSW** [comment]
This issue is not reproducible on Che 7.32.2 release, it only affects 7.33.0-SNAPSHOT

**Comment by ScrewTSW** [comment]
works correctly in `quay.io/eclipse/che-golang-1.14@sha256:da831c03340bccc94a6d3dde30ed5aace253857fd3a3c57f2a48aef1abaa910a` but fails with the screenshots in `quay.io/eclipse/che-golang-1.14:next`
