### ISSUE TITLE
Mixed content: Failed to load devfiles from the registry 

### ISSUE THREAD

**Issue by rminchev1** [eclipse-che/che#20115]
## Summary

I would appreciate some help with the issue I'm getting.

![image](https://user-images.githubusercontent.com/1092422/125092093-a377e200-e0d9-11eb-8b62-6e2b9e4a4c31.png)

## Relevant information

The deployment is in kubernetes ( aws ) version:  7.30.1. I messed it up while playing with the helm configurations, that's why I'm asking for some guidance as to how to further debug it and fix the configuration.

Thanks once again guys!

**Comment by rminchev1** [comment]
Okay, I figured it out, In my deployment I used the helm charts from [here](https://github.com/eclipse-che/che-server/tree/main/deploy/kubernetes). The faulty one is [che-devfile-registry](https://github.com/eclipse-che/che-server/tree/main/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry). It doesn't seem updated and it lags behind  [this one](https://github.com/eclipse-che/che-devfile-registry/tree/main/deploy/kubernetes/che-devfile-registry), and since I used a newer devfile registry image with tag next, my configmap doesn't have  ``` CHE_DEVFILE_REGISTRY_URL ``` environment variable set and when the container starts the entrypoint.sh scripts assigns an the internal service registry IP, rather the public one.

https://github.com/eclipse-che/che-devfile-registry/blob/main/build/dockerfiles/entrypoint.sh#L140

**Comment by rminchev1** [comment]
Should we have have this configmap updated?
https://github.com/eclipse-che/che-server/blob/main/deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/configmap.yaml

**Comment by sleshchenko** [comment]
Seems it duplicates https://github.com/eclipse/che/issues/20100
The reference to fix can be found inside.
