### ISSUE TITLE
Unable to start workspace on docker-desktop with custom domain

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#20112]
### Describe the bug
Unable to start workspace
![image](https://user-images.githubusercontent.com/13031838/125058840-3cf4c300-e0dd-11eb-8cdf-92f500455bb0.png)

### Che version

 - [x] 7.31.2

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * chectl server:deploy -p=docker-desktop --installer=helm -b=cloudide.com
![image](https://user-images.githubusercontent.com/13031838/125059031-77f6f680-e0dd-11eb-83df-68870d629c43.png)

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS

### Eclipse Che Logs
```text
Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"
Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0" in 3.925055926s
Created container che-plugin-metadata-broker-v3-4-0
Started container che-plugin-metadata-broker-v3-4-0
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 Broker configuration
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 Push endpoint: wss://che-eclipse-che.cloudide.com/api/websocket
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 Auth enabled: false
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 Runtime ID:
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 Workspace: workspace9buho8i6u3isv5th
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 Environment: default
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 OwnerId: che
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:40 Self signed certificate /tmp/che/secret/ca.crt
[che-plugin-metadata-broker-v3-4-0] -> 2021/07/09 09:42:50 Couldn't connect to endpoint 'wss://che-eclipse-che.cloudide.com/api/websocket', due to error 'dial tcp 127.0.0.1:443: connect: connection refused'
Failed to run the workspace: "Plugins installation process timed out"
```

**Comment by sleshchenko** [comment]
@tolusha @mmorhun any ideas/suggestions?

**Comment by zWingz** [comment]
![image](https://user-images.githubusercontent.com/13031838/125286214-21442380-e34e-11eb-9357-9e6d7ff7f113.png)
It throw error when run `chectl server:deploy`

**Comment by tolusha** [comment]
@zWingz 
`-b=cloudide.com` bothers me... Is it resolvable host?

**Comment by zWingz** [comment]
It is a custom hosts. I add it into `/etc/hosts`

**Comment by tolusha** [comment]
so, did `che-eclipse-che.cloudide.com` is added to  `/etc/hosts` as well ?

**Comment by flacatus** [comment]
![install](https://user-images.githubusercontent.com/59865209/125303424-13ca7180-e32d-11eb-8bbe-b57b2867f4be.jpeg)

@tolusha @zWingz For me is working without `-b=cloudide.com`. Also I can start an workspace without problem:

![workspace](https://user-images.githubusercontent.com/59865209/125303676-42e0e300-e32d-11eb-809e-c083bf405d0b.jpeg)

**Comment by zWingz** [comment]
@tolusha YES, All hosts are added to `/etc/host`

**Comment by zWingz** [comment]
@flacatus It work without `-b=cloudide.com` for me...
![image](https://user-images.githubusercontent.com/13031838/125378230-f47d2400-e3c0-11eb-9b69-a4c18cfe16c8.png)
