### ISSUE TITLE
Devfile projects not working with custom theia editor

### ISSUE THREAD

**Issue by sgraband** [eclipse-che/che#20128]
## Summary
I have a custom theia editor, that i am deploying to che. Specifying the editor in the devfile works as expected. However, when i specify a project in the devfile, to clone into the workspace, the project is not cloned. I do not get an error, hence it seems like the process for cloning the repository is not even started. There is also no indication in the logs that the cloning is tried.

When trying out a workspace from the default devfile-registry it works. Do i need to configure my theia editor in a specific way to get the support for importing projects via the devfile? Or is this unexpected behavior?
## Relevant information
Che Version 
7.32.2
Deployed on minikube using chectl

**Comment by svor** [comment]
@sgraband hello, 
in che-theia we have [workspace-plugin](https://github.com/eclipse-che/che-theia/tree/a0e12b3f0ea5b8f9f79ae251e1d8e1b3b1e09787/plugins/workspace-plugin) which is responsible for parsing devfile and [cloning defined projects](https://github.com/eclipse-che/che-theia/blob/a0e12b3f0ea5b8f9f79ae251e1d8e1b3b1e09787/plugins/workspace-plugin/src/workspace-projects-manager.ts#L54). 
I'd say there is no easy way to include such functionality into your editor, you have to implement something similar. 
@benoitf  please correct me if I'm wrong

**Comment by sgraband** [comment]
@svor is there any reason why i cannot reuse the existing workspace-plugin?

**Comment by l0rd** [comment]
@sgraband the other option you have is to use the [devworkspace operator](https://www.eclipse.org/che/docs/che-7/installation-guide/enabling-dev-workspace-engine/). Not that this is an experimental feature but, in this case, projects are cloned by an init container rather than the editor.

**Comment by svor** [comment]
> @svor thanks for your help! Is there any reason why i cannot reuse the existing workspace-plugin?

You can try to reuse it but workspace-plugin depends on another plugins/extensions, so it could be a problem

**Comment by sgraband** [comment]
I tried to enable the devworkspace operator with [these instructions](https://www.eclipse.org/che/docs/che-7/installation-guide/enabling-dev-workspace-engine/). However, i have a few questions:
- If i understand it correctly the operator enables devfile 2.0 support in Che. Is this correct? 
- Does this also mean i have to use a 2.0 devfile to get the projects to import? 
- Or is this a different feature that should also work with v1 devfiles?
- For me neither the project cloning nor the devfile 2.0 support seems to work. Are there any additional instructions available than the ones in the link?
- Last but not least, i wanted to ask whether or not there is a roadmap for this feature set? Is this something that is actively being worked on or are you planning on leaving this up to the editor to implement these functionalities?

**Comment by benoitf** [comment]
>I tried to enable the devworkspace operator with [these instructions](https://www.eclipse.org/che/docs/che-7/installation-guide/enabling-dev-workspace-engine/). However, i have a few questions:
>- If i understand it correctly the operator enables devfile 2.0 support in Che. Is this correct?

yes correct, it brings devWorkspace support /devfile v2.0 instead of che-server/devfilev1 workspaces

>- Does this also mean i have to use a 2.0 devfile to get the projects to import? 

yes, it's handling only devfile 2.1.0+ devfiles


> - Or is this a different feature that should also work with v1 devfiles?

It's a different engine supporting only devfile v2


> - For me neither the project cloning nor the devfile 2.0 support seems to work. Are there any additional instructions available than the ones in the link?

Using the instruction should be enough.

> - Last but not least, i wanted to ask whether or not there is a roadmap for this feature set? Is this something that is actively being worked on or are you planning on leaving this up to the editor to implement these functionalities?

Yes it's actively support as che-server workspaces will be deprecated and replaced by DevWorkspace / DevWorkspace operator

you can track with dedicated milestones in che github tracker
Also most of epics are around devfile v2 support
https://github.com/eclipse/che/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fepic+devfile
