### ISSUE TITLE
Migrate Che Dashboard to use Yarn 1 (support for Big Endian systems like s390x)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20138]
### Is your enhancement related to a problem? Please describe.

Today the Che Dashboard uses Yarn2 in Che and is converted to using Yarn1 in CRW, because Yarn 2 doesn't support Big Endian arches like s390x.

### Describe the solution you'd like

Rather than using one BE-incompatible system in Che and a BE-compatible one in CRW, we could simply use Yarn 1 in both places, which would allow us to build the Che Dashboard for Z as well as the CRW one. This would allow us to potentially catch Z related bugs sooner. 

### Describe alternatives you've considered

Continue to use Yarn2 in Che and Yarn1 in CRW, and maintain scripts/Dockerfile transformation that convert from one to the other, along with all the requisite bug fixes...

https://github.com/redhat-developer/codeready-workspaces-images/commits/crw-2-rhel-8/codeready-workspaces-dashboard/build

### Additional context

We intend to be able to build and release all the Che projects for at least 3 (or 4) arches: 
* amd64 / x86_64
* s390x (Linux on Z)
* ppc64le (Power)
* aarch64 / arm64

So this will eventually block that endeavour unless a version of Yarn 2 appears that supports Big Endian.

**Comment by aditijadhav38** [comment]
@nickboldt Even Che-plugin-registry was also moved to yarn 2. So could you please let me know if there are any plans for moving back to yarn1 for plugin-registry.

**Comment by nickboldt** [comment]
There are no plans to move to Yarn 1 in plugin registry. However @benoitf has suggested that for Travis + s390x builds of plugin reg, to bypass Yarn 2 BigEndian issues, we could:

```
rm -rf .pnp.js .yarn .yarnrc.yml
```
(or something like that)

**Comment by benoitf** [comment]
it should be also possible to set
```
yarn set version classic
```

 before running yarn commands

**Comment by aditijadhav38** [comment]
@nickboldt @benoitf Thanks it worked.. Able to build plugin-registry image.
