### ISSUE TITLE
Update vscode-java extension to  0.82.0 version

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#20134]
### Is your task related to a problem? Please describe.
Che vscode-java plugin is outdated, its version is v0.75.0.  
Currently latest released version of [vscode-java](https://github.com/redhat-developer/vscode-java/tree/v0.80.0) extension is 0.80.0. 

### Describe the solution you'd like

We need to upgrade vscode-java plugin in che-plugin registry. For this need to do some steps:

- [x] Try latest vscode-java extension in vanilla Theia and investigate what API it is required and what work should be done on Theia side
- [x] Update existing `redhat/java11` extension in [che-theia-plugins.yaml](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml).
- [x] Test if the extension works es expected with existing java-based devfiles on Che 

Release Notes:
Upgrade redhat.java VS Code extension to v0.82.0

**Comment by tsmaeder** [comment]
The Theia API check tool reports these missing elements: 
```
  "missingSymbols": [
    "\"vscode\".CodeActionKind.QuickFix",
    "\"vscode\".CodeActionKind.Refactor",
    "\"vscode\".CodeActionKind.RefactorExtract",
    "\"vscode\".CodeActionKind.RefactorInline",
    "\"vscode\".QuickPick.onDidHide",
    "\"vscode\".QuickPick.show",
    "\"vscode\".QuickPick.step",
    "\"vscode\".QuickPick.title",
    "\"vscode\".QuickPick.totalSteps",
    "\"vscode\".Selection.end",
    "\"vscode\".Selection.isEmpty",
    "\"vscode\".Selection.start",
    "\"vscode\".SymbolKind.toString"
  ],
  "missingCommands": [
    "editor.action.goToLocations",
    "editor.action.rename",
    "editor.action.showReferences",
    "editor.insertSpaces",
    "editor.tabSize",
    "java.action.organizeImports",
    "java.edit.organizeImports",
    "java.execute.workspaceCommand",
    "markdown.api.render",
    "markdown.css",
    "workbench.action.manageTrust",
    "workbench.action.openSettings",
    "workbench.action.openSettingsJson",
    "workbench.action.reloadWindow",
    "workbench.extensions.installExtension"
  ],
  "dynamicCommandCalls": [
    "action.command (C:/Users/thomas/code/chedev/vscode-java/src/standardLanguageClient.ts 168:31)",
    "error.command (C:/Users/thomas/code/chedev/vscode-java/src/extension.ts 140:28)",
    "params.command (C:/Users/thomas/code/chedev/vscode-java/src/standardLanguageClient.ts 176:35)",
    "params.command (C:/Users/thomas/code/chedev/vscode-java/src/standardLanguageClient.ts 180:28)",
    "refactorEdit.command.command (C:/Users/thomas/code/chedev/vscode-java/src/refactorAction.ts 225:42)",
    "refactorEdit.command.command (C:/Users/thomas/code/chedev/vscode-java/src/refactorAction.ts 227:42)"
  ]
```

**Comment by tsmaeder** [comment]
false positives: 

* CodeActionKinds are all implemented, this the reports are because these are static fields.
* QuickPick items are implemented, but in the `QuickInput` super-interface
* Selection stuff again is implemented in the super-interface `Range?`
* SymbolKind.toString() is implicit, since all enums have a "toString()" method.

**Comment by svor** [comment]
@tsmaeder [CHANGELOG 0.80.0](https://github.com/redhat-developer/vscode-java/blob/v0.80.0/CHANGELOG.md) contains information about supporting Workspace Trust:

> enhancement - Support Workspace Trust. See #1926.

Am i right that this functionality won't work in Theia since it doesn't provide [Workspace Trust](https://code.visualstudio.com/docs/editor/workspace-trust)?

**Comment by tsmaeder** [comment]
Theia does not have that concept. As far as I understand the code in VSCode-Java, they treat workspaces as trusted if the API is not there.

**Comment by tsmaeder** [comment]
So functionality should work.

**Comment by tsmaeder** [comment]
While 0.82 works (with some messages in the log) in the exact theia version we're using in che-theia, the startup of the extension fails when running in a java11 workspace on the che dogfooding instance.

**Comment by tsmaeder** [comment]
When googling for the error message "TypeError: Class extends value undefined is not a constructor or null", one mostly gets answers related to circular dependencies or improper use of `import` or `require`

**Comment by tsmaeder** [comment]
When running the the Java plugin in a self-hosting workspace, the plugin starts up correctly. This looks more and more to be an artifact of how we build the plugin host executable.

**Comment by tsmaeder** [comment]
Spoke too soon: now I can actually run the java plugin in my outer self-hosting workspace. Not sure what changed from two days ago.

**Comment by svor** [comment]
closed by https://github.com/eclipse-che/che-plugin-registry/pull/1060

**Comment by benoitf** [comment]
@svor is that downstreaming this work is planned ?

**Comment by svor** [comment]
@benoitf We haven't done it for downstream yet.  I'll create an issue for that

**Comment by svor** [comment]
here it is: https://issues.redhat.com/browse/CRW-2590
