### ISSUE TITLE
Make che-launcher inject all CHE_* environment variables into che-server

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2013]
It will help to use environment variables to configure any property used by CHE

**Comment by TylerJewell** [comment]
Already provided in `che.sh` in the root of the repo.  Sorry - having weird issues with github and it sometimes ends my messages early.

Question - should this be part of the che-launcher (auto-discover all CHE_\* entries), or is it suitable to just do it in the native outside launcher, the way it is here.  https://github.com/eclipse/che/blob/master/che.sh#L165-L173

**Comment by garagatyi** [comment]
These variables are needed for che-server. So it looks like all the scripts/containers in the middle should pass these variables. 
- che.sh already [does that](https://github.com/eclipse/che/blob/master/che.sh#L260)
- che-launcher [does not](https://github.com/eclipse/che/blob/master/dockerfiles/che-launcher/launcher_cmds.sh#L33)

**Comment by garagatyi** [comment]
Also it is not clear to me whether these scripts should pass HTTP_PROXY/HTTPS_PROXY/NO_PROXY env variables or not.
Maybe someone can help to understand that?

**Comment by garagatyi** [comment]
And looks like there is a bug in environment variables passing in che.sh [here](https://github.com/eclipse/che/blob/master/che.sh#L234).
In case there is variable that has spaces its value will be splitted into separate pieces and passed to che-launcher.
Here is an example

```
✔ ~
10:21 $ env | grep CBUILD
PATH_TO_CBUILD_LIBRARY_FOLDER=/Users/gaal/workspace/deployment/automation
CBUILD_USER_DEFAULT_PARAMS=--t --skip-sources-validation --q --odyssey --dshb --gwt --aio
CBUILD_NOTIFICATION_OK_TIME_MS=100000
CBUILD_NOTIFICATION_FAIL_TIME_MS=100000
PATH_TO_CBUILD_PROJECTS_FOLDER=/Users/gaal/workspace/
✔ ~
10:21 $ SOME_VAR=$(env | grep CBUILD)
✔ ~
10:22 $ echo $SOME_VAR
PATH_TO_CBUILD_LIBRARY_FOLDER=/Users/gaal/workspace/deployment/automation CBUILD_USER_DEFAULT_PARAMS=--t --skip-sources-validation --q --odyssey --dshb --gwt --aio CBUILD_NOTIFICATION_OK_TIME_MS=100000 CBUILD_NOTIFICATION_FAIL_TIME_MS=100000 PATH_TO_CBUILD_PROJECTS_FOLDER=/Users/gaal/workspace/
✔ ~
10:22 $ for ss in  $SOME_VAR; do echo $ss; done
PATH_TO_CBUILD_LIBRARY_FOLDER=/Users/gaal/workspace/deployment/automation
CBUILD_USER_DEFAULT_PARAMS=--t
--skip-sources-validation
--q
--odyssey
--dshb
--gwt
--aio
CBUILD_NOTIFICATION_OK_TIME_MS=100000
CBUILD_NOTIFICATION_FAIL_TIME_MS=100000
PATH_TO_CBUILD_PROJECTS_FOLDER=/Users/gaal/workspace/
```

**Comment by TylerJewell** [comment]
Thanks for pointing this out! Is this a bug if all of our CHE_ variables only require full strings without spaces?  I don't know of any variables that would accept parameters like you suggest.

**Comment by TylerJewell** [comment]
Also @garagtyi - the variables that are passed from Che.sh into che-launcher are needed.   However, the Che-server requires different kinds of variables.   So I agree that once the Che server will respect all Che properties as an environment variable then the Che launcher must auto discover them and odd along.

**Comment by garagatyi** [comment]
If you want to add env variables to alternate each property than support of variables with spaces is needed. Also paths in existing env variables can contain spaces.

**Comment by TylerJewell** [comment]
It is probably an easy fix.  If the variable in the loop does not match a pattern environment variable then it should be appended to the string without the --env prefix.  Though we will need to make some tests.

I do not know if we should include HTTP_ variables in the pass through.  Do you have an opinion?

**Comment by TylerJewell** [comment]
@garagatyi - I have updated the latest pull request that contains the CLI to now accept environment variables with spaces. Those spaces must be double quote delimited, however, the CLI will fail.

**Comment by TylerJewell** [comment]
@l0rd - I have made a number of improvements.
https://github.com/eclipse/che/pull/2057
1. Added environment variable discovery for all CHE_ into che-launcher.
2. Moved environment variables into --env-file option as it respects variables with spaces better.
3. Consolidated "che info" in the CLI to handle debug info for launcher and CLI at same time.
