### ISSUE TITLE
Add an ability to override devfile v2 bits with factory URL

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20137]
### Is your enhancement related to a problem? Please describe.
Sometimes users would like to reuse published devfile somewhere with just a few modification like repo url, workspace name and so on.
Initially, this feature is added for devfile v1 within https://github.com/eclipse/che/issues/13617.

TODO Add detailed info on what is allowed to be overridden and what not.

### Describe the solution you'd like

Factory URL with Devfile v2  should still support an ability to override some devfile fragments.
We start with projects.

**Comment by dmytro-ndp** [comment]
Set severity/P2, because URL is not so convenient to hold text fragment - it is encoded and has limited size.
