### ISSUE TITLE
Remove 'nightly' / 'master' ci-centos CI for kubernetes-image-puller-operator

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20149]
### Is your task related to a problem? Please describe.
Remove 'nightly' / 'master' ci-centos CI for kubernetes-image-puller-operator - https://github.com/che-incubator/kubernetes-image-puller-operator

- [x] Remove nightly CI
- [x] Remove master CI
- [x] Switch to the 'main' branch 
- [x] Remove 'master' branch 
- [x] Switch to the usage of the 'next' tag

### Additional context
Related to https://github.com/eclipse/che/issues/19291

**Comment by ibuziuk** [comment]
@mkuznyetsov @nickboldt moving to the next
Could you clarify when is it planned to provide the relevant GitHub action to https://github.com/che-incubator/kubernetes-image-puller-operator ?

**Comment by nickboldt** [comment]
PR https://github.com/che-incubator/kubernetes-image-puller-operator/pull/54

**Comment by ibuziuk** [comment]
Centos CI has been removed. Closing
