### ISSUE TITLE
Can not execute the che-plugin-registry builder npm package

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#20146]
### Describe the bug

Since the [che-plugin-registry builder npm package](https://www.npmjs.com/package/@eclipse-che/plugin-registry-generator) was published we need to use it in the [CRW plugin registry](https://github.com/vinokurig/codeready-workspaces/tree/072639b005b9d05e22d31505a62c036ec312d281/dependencies/che-plugin-registry) instead of the duplicated sources from the [upstream plugin registry](https://github.com/eclipse-che/che-plugin-registry/tree/main/tools/build), see https://issues.redhat.com/browse/CRW-1928. The problem is that the npm package hasn't any executable references, so it cannot be executed e.g. by `npx`.
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

execute `npx @eclipse-che/plugin-registry-generator`.
See: 
```
npx: installed 88 in 4.203s
command not found: plugin-registry-generator
```
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by benoitf** [comment]
now it works with latest next version published
```bash
$  npx @eclipse-che/plugin-registry-generator@7.34.0-dev-170a33f                                                                                                                                                                                                                                                           
npx: installed 112 in 9.718s
✖ Read che-theia-plugins.yaml file
```
