### ISSUE TITLE
Configuration of Persistent Volumes 

### ISSUE THREAD

**Issue by sdagostini** [eclipse-che/che#20145]
## Summary
I am installing an Eclipse Che instance (v 7.33.1) in multi user mode on a Centos7 machine where minukube has been installed. I would like to store the postgreSQL db data on a specific folder of the machine (e.g., `/data/che/postgres`) and the workspaces data under another specific folder (e.g., `/data/che/workspace`) 

## Relevant information

In order to achive the objective described in the previous section I have defined and created two persistent volumes as described below:

`postgres-pv-volume`

> apiVersion:v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/che/postgres" 

`workspace-pv-volume`
> apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/che/workspace"

After the installation of the `Che` server the postgres pv is bound to the postgreSQL db. Concerning the workspaces created by the users I have the following behaviour:

- The first user that creates a workspace is bound to the `workspace-pv-volume` so that the workspace data are stored under the folder I specified on the pv definition.
- When another user creates another workspace a new pv is created and the workspace data are stored under a `temp` folder

Here the result of the ` kubectl get pv --all-namespaces` command

> NAME                        ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                      STORAGECLASS 
postgres-pv-volume     RWO                     Retain                    Bound    eclipse-che/postgres-data                        standard 
pvc-370bfc55-30df-
4892-9785-93c96dabe3db  RWO              Delete                    Bound    _username_-che/claim-che-workspace     standard          
workspace-pv-volume   RWO                    Retain                    Bound    _username_-che/claim-che-workspace     standard

Is it possible to make some configurations so that the data of the workspaces created by `User A` and by `User B` are all stored under the folder I specified on the defined `workspace-pv-volume` (e.g., under `/data/che/workspace`)
 
Thank you in advance.

**Comment by skabashnyuk** [comment]
>Is it possible to make some configurations so that the data of the workspaces created by User A and by User B are all stored under the folder I specified on the defined workspace-pv-volume (e.g., under /data/che/workspace)

All available storage options are described here https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-storage-strategies/#storage-strategies-for-che-workspaces_che

Also you may consider to explore this https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-storage-types/

**Comment by sdagostini** [comment]
ok Thank you!
