### ISSUE TITLE
What is the `@eclipse-che/plugin` version if a plugin base on che-theia@7.31.2

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#20154]
## Summary

The plugins on che-theia will depend on workspace version. 
If a plugin doesn't develop on che-theia directory, what is the `@eclipse-che/plugin` version
There are not [@eclipse-che7.31.2](https://www.npmjs.com/package/@eclipse-che/plugin) in npm

![image](https://user-images.githubusercontent.com/13031838/126320212-b5d99c29-5f0e-451d-b1f2-fb4b6f0aafd0.png)

**Comment by sparkoo** [comment]
cc @svor

**Comment by svor** [comment]
@azatsarynnyy @benoitf can you help with this

**Comment by benoitf** [comment]
basically it's using the latest version of the compilation (it's replaced when we cut a release)

**Comment by zWingz** [comment]
@benoitf yes, I know it will be replaced. My team depoly a `Che` base on `7.31.2`, and I have to develop a plugin for `che-theia`. 
The plugin is a single project
```
- che-theia
  - plugins
    - eclipse-che-xxx-plugin 
- my-plugin
```
So, My plugin is not a `workspace` in `che-theia`, but It depend on `@eclipse-che/plugin`.
```
yarn add @eclipse-che/plugin
```
But there are not `@eclipse-che/plugin@7.31.2` in npm, So I can't install it

**Comment by benoitf** [comment]
Hello @zWingz 
you can use this file to grab the version you need

https://github.com/eclipse-che/che-theia/blob/7.31.2/yarn.lock#L945

**Comment by zWingz** [comment]
@benoitf Get it, Thanks
