### ISSUE TITLE
Cannot Modify ~/.gitconfig by git config --global xxxx xxxx

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#20150]
### Describe the bug
```
git config --global credential.helper 'store --file ~/.my-credentials'
```
Cannot not Modify `~/.gitconfig`
I think It is caused by the plugin `eclipse-che-theia-git-provisioner` 

- change `~/.gitconfig` and fire the file watcher [git-configuration-contribution.ts#L22](https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-contribution.ts#L22)
- updated the preference and fire the preference watcher [git-configuration-contribution.ts#L23](https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-contribution.ts#L23)
- use `git.user.name` and `git.user.email` from `preference` to update `~/.gitconfig`. but It use a object to override. It should use `Object.assign` [git-configuration-controller.ts#L125-L135](https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-controller.ts#L125-L135)

### Che version

 - [x] 7.31.2

### Steps to reproduce

- run `git config --global credential.helper 'store --file ~/.my-credentials'`

### Expected behavior
`~/.gitconfig` should append new line
```
[credential]
	helper = store --file ~/.my-credentials
```

### Runtime
   - [x] kubernetes (include output of `kubectl version`)

**Comment by skabashnyuk** [comment]
@zWingz  `~/.gitconfig ` is not editable by design. It is constructed by che-server and mounted to the workspace's container. Data are taken from the user's profile or k8s secretes. What exactly config param of git-config you are interested in?

**Comment by zWingz** [comment]
@skabashnyuk  
I want to add a credential
`git config --global credential.helper 'store --file ~/.my-credentials'`
 https://git-scm.com/docs/git-credential

**Comment by skabashnyuk** [comment]
>I want to add a credential
>git config --global credential.helper 'store --file ~/.my-credentials'

Have you tried this? 

https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-git-credential-store-into-a-workspace-container_che

**Comment by zWingz** [comment]
@skabashnyuk thanks, I would try it
