### ISSUE TITLE
How to define a task which run after workspace start

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#20152]
## Summary

just like [gitpod-start-tasks](https://www.gitpod.io/docs/config-start-tasks)
For example:
autorun `yarn` after workspace start

**Comment by sparkoo** [comment]
I don't think it's currently possible. cc: @svor @azatsarynnyy

**Comment by svor** [comment]
It's related to the post start events epic https://github.com/eclipse/che/issues/12925. For now it is not possible

**Comment by zWingz** [comment]
@svor thanks
