### ISSUE TITLE
Devfile schema validation failed due to unexpected type for the persistVolumes field

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#20153]
### Describe the bug

It's impossible to start a workspace when `persistVolumes` value is boolean type.
The error is:
``` 
Failed to resolve a devfile. Error occurred during creation a workspace from devfile located at `https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1049/simple/che-theia-nodejs-devfile.yaml`. Cause: Devfile schema validation failed. Error: (/attributes/persistVolumes):The value must be of string type, but actual type is boolean.
```

According to [the doc](https://www.eclipse.org/che/docs/che-7/end-user-guide/authoring-devfiles-version-1/#_adding_attributes_to_a_devfile) it should work well for the boolean type 
### Che version

  nightly
 

### Steps to reproduce

1. Try to start a workspace from the devfile https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1049/simple/che-theia-nodejs-devfile.yaml

### Screenshots

<img width="1788" alt="try_it_buttons_errors" src="https://user-images.githubusercontent.com/5676062/126288422-3fe0496e-6483-42f7-8794-782ab9b9d57c.png">

### Environment
   Dev Sandbox (workspaces.openshift.com)

**Comment by sparkoo** [comment]
I think it's documentation issue https://github.com/eclipse-che/che-server/blob/main/wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json#L19
