### ISSUE TITLE
Migrate local json-based storage to jpa

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2016]
We need to migrate all data stored in json-based storage to jpa database

Important thing here is how we will do that. There is two options
- As component of che
- As separate tool

There is couple of pros and cons in both ways
- Component is part of the che. User don't need to download anything . Everything will happen automatically
- We don't want to keep this code for long time. Ideally remove it in release after. So separate tool is better.

**Comment by skabashnyuk** [comment]
@TylerJewell  do you have a vision what is better of user and for us?
For instance can we tell user who has json-base storage and wants to migrate data  to run some particular predefined version of che first and then run the latest version of che? In this case we will keep migration code only in first jpa based version of che
wdyt?

**Comment by TylerJewell** [comment]
@skabashnyuk - I don't see how that could be really good for the user.  Is there any way we could ship a couple different migrations:
1: If you have version x, then the migration is automatic.
2: If you have version x-1, x-2, then we have an internal migration up to x, and then migrate to JPA
3. If you have version x-3, we do not support migration.
