### ISSUE TITLE
Upgrade Tooling for Apache Camel K VS Code extension to v0.0.26

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#20163]
### Is your enhancement related to a problem? Please describe.

A new version of the extension is available. It will allow to use latest kamel version (1.5.0). Also, it might help to fix https://issues.redhat.com/browse/CRW-1951

see changelog https://github.com/camel-tooling/vscode-camelk/blob/master/CHANGELOG.md#0026

### Additional context

Notable change is that it removes dependency on vscode-commons

**Comment by apupier** [comment]
PR https://github.com/eclipse-che/che-plugin-registry/pull/1007

**Comment by AndrienkoAleksandr** [comment]
@apupier I set up P2. But you can change severity if it is critical.
