### ISSUE TITLE
[Dashboard] Ensure k8s namespace exists before workspace related operation

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20167]
### Is your task related to a problem? Please describe.
It might happen that k8s namespace is not created https://github.com/eclipse/che/issues/19236 or for some reason has been deleted.
### Describe the solution you'd like

Invoke ```/kubernetes/namespace/provision``` method before each workspace/devworkspace related, factory resolve operation.  
### Describe alternatives you've considered
N/a

**Comment by sleshchenko** [comment]
https://github.com/eclipse-che/che-server/pull/61 provides needed API method

**Comment by skabashnyuk** [comment]
and factories "resolve"

**Comment by sleshchenko** [comment]
I believe it's only workspace client part that is merged and dashboard part is coming, so, reopened.
