### ISSUE TITLE
Reducing the installation options for Che

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20178]
### Is your enhancement related to a problem? Please describe.

We currently have multiple options to deploy Che. That's hard to maintain and it doesn't bring value for customers.

### Describe the solution you'd like

| Platforms |    Current Options |  New Options (step1) |  New Options (step2) | 
| ---------  | ------------- | ------------- | ------------- | 
|  minikube/k8s/microk8s/docker-desktop  | helm/olm/operator | operator |  operator |
|  openshift 4/crc  |  helm/olm/operator | olm | none (not supported) |
|  minishift  | operator | operator |  operator |

A few clarifications:
- The goal is to have one installation mode only. That's easier to maintain and simpler for users. The only installation mode would be operator (applying the Kubernetes resources to deploy Che operator CRD and controller without OLM).
- On OpenShift there is the option to install CRW (Red Hat distribution of Che) and that should be the default choice. That's why we want to remove Che support for olm (step 2).
- We want to keeep olm support temporarly (step 1) untlil we have weekly releases of CRW ([downstream issue](https://issues.redhat.com/browse/CRW-1759)). That's because we want have a rapid validating of OLM installation (nightlies build rather than 6 weeks build cadence of CRW).
-  we replace current helm chart with a new one that uses operator templates.  We publish the new chart to https://artifacthub.io/ and we setup a gh action to automatically release a new version of the chart at every che release

Installers for k8s platform:

![k8sinstallers](https://user-images.githubusercontent.com/1640675/138101804-0d61f5fe-c013-4bb2-b422-ae22736d4a7b.png)

Tasks:
- [x] https://github.com/eclipse/che/issues/20668
- [x] https://github.com/eclipse/che/issues/20552

Subepic:

-  [Deprecate installation of upstream Che using the OperatorHub](https://github.com/eclipse/che/issues/19659)

**Comment by l0rd** [comment]
@tolusha please create a subtask for step 1 and add it as `sprint/next`. That includes stop supporting helm charts so it's a big change. We need to deprecate it initially and disable it, if there are no strong push back, after a couple of sprints.

**Comment by tolusha** [comment]
Helmchart deprecation
https://github.com/eclipse/che/issues/20183

**Comment by l0rd** [comment]
`chectl sever:deploy` is the way to deploy Che using the command line. And it should continue to be like that.

Step 1 implies that we should deprecate the "--installer" parameter because there is only one per platform. Step 2 (blocked by [this downstream issue](https://issues.redhat.com/browse/CRW-1759))  means that we should deprecate "openshift" and "crc" platforms as those should be better served/covered by CRW. @tolusha does that make sense for you?

**Comment by nickboldt** [comment]
> On OpenShift there is the option to install CRW (Red Hat distribution of Che) and that should be the default choice. That's why we want to remove Che support for olm (step 2).

Does this mean that crwctl will ONLY be used for OCP 3.11 (operator mode) ?

Or is the plan to keep olm mode in crwctl, but remove it from chectl?

Asking because QE relies heavily on crwctl to do install tests w/ CRW 2.13. Seems a strange choice to make crwctl an Officially Supported install method, then remove it a few months later. 

So if crwctl will continue support olm mode, we need to be clear about HOW we maintain the fork downstream once we get to *step 2*.

**Comment by tolusha** [comment]
OCP 3.11: crwctl with `--installer operator`
OCP 4.x: OpeatorHub + crwctl with `--installer olm`

**Comment by nickboldt** [comment]
Ah, so no change then. This is the current state of affairs for CRW:
> OCP 3.11: crwctl with `--installer operator`
> OCP 4.x: OpeatorHub + crwctl with `--installer olm`

**Comment by Kasturi1820** [comment]
@tolusha Is step 1 done ?

**Comment by tolusha** [comment]
@Kasturi1820 
Yes, completed.
Besides the fact, that it is still possible to use `--installer operator` to deploy on OpenShift (moslty for testing purpose)

**Comment by l0rd** [comment]
Closing this issue as the first step is done (reducing the installation options). The second step (remove Che from OperatorHub) is tracked [in a distinct issue](https://github.com/eclipse/che/issues/19659) and is blocked by [this downstream issue](https://issues.redhat.com/browse/CRW-1759).
