### ISSUE TITLE
The Che-theia welcome page should provide information about how to use Che-theia and what this is all about

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#20175]
### Is your enhancement related to a problem? Please describe.
starting a workspace, the welcome page is showing up: 
![Selection_425](https://user-images.githubusercontent.com/650571/126618943-f20c71ea-1458-4ee1-8468-70db496d0cdd.png)

There is not that much information out there except few actions:
- new file
- git clone
- open files
- etc.

I am not sure this is something that new user is expecting to do when coming to a new workspace (that is usually created from a devfile)

### Describe the solution you'd like
Provide guidance:
- few lines about what is a che workspace: your application and tools running in containers in a kubernetes pod. usually generated from a devfile  and talk quickly about DEaC (Development Environment as Code)
- talk about the project explorer to navigate the files of your project
- talk about my workspace view to access to the containers + predefined commands
- talk about the command palette
- talk about plugins and features that could be enabled

following by links to the doc and chat.

**Comment by sunix** [comment]
Maybe get inspiration from https://github.com/eclipse-che/che-devfile-registry/blob/62b7dbdbbd0e359361cb6e61a9059dc9fbc8e617/devfiles/quarkus/didact.md

**Comment by benoitf** [comment]
Walkthroughs can be contributed by extensions:

https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs

**Comment by sunix** [comment]
@benoitf nice !
