### ISSUE TITLE
Adapt samples, plugins and devfiles to work with Quarkus 2.0

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#20174]
### Is your enhancement related to a problem? Please describe.
Quarkus 2.0 has been released. We need to upgrade our samples, devfiles and plugins to use quarkus 2.0

### Describe the solution you'd like
Update the get started samples to use Quarkus 2.
Also see if the Didact guide needs to be updated: maybe showcase new features of quarkus like continuous testing.

**Comment by svor** [comment]
The get started sample was updated: https://github.com/che-samples/quarkus-quickstarts/pull/6
