### ISSUE TITLE
Upgrade minikube from 1.18.1 to 1.22.0 in VS Code kubernetes sidecar

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#20173]
### Is your enhancement related to a problem? Please describe.

new versions are available.
It will avoid to have a notification on workspace startup `Minikube upgrade available to v1.22.0, currently on v1.18.1`

**Comment by svor** [comment]
**kubectl** version in quay.io/devfile/universal-developer-image:ubi8-latest is:
```
sh-4.4$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"2b525e8d2647a41e686bc7da5b7430667a13953e", GitTreeState:"clean", BuildDate:"2021-08-20T21:43:10Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
