### ISSUE TITLE
Adapt Happy Path tests to the changes related to upgrade Monaco

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#20172]
### Is your task related to a problem? Please describe.

We need provide some adaptation for the `Happy path` tests after upgrade Monaco version in upstream.
### Describe the solution you'd like

Need to adapt `Happy path` tests to the upstream changes.
### Additional context

https://github.com/eclipse/che/issues/20069

**Comment by RomanNikitenko** [comment]
I started to do it within https://github.com/eclipse/che/issues/20069, but, unfortunately, the tests are still unhappy, so we need to put more efforts to get it working...

**Comment by RomanNikitenko** [comment]
At the moment the `Happy Path` tests fail due to a workspace can not be started
the error is:
```
2021-07-22 06:50:48,616[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspacelyw1f4qaodizyvwq.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Waiting for Kubernetes environment 'default' of the workspace'workspacelyw1f4qaodizyvwq' reached timeout
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.waitMachines(KubernetesInternalRuntime.java:393)
```
manually starting a workspace from the devfile of the Happy Path  tests works perfect, so it's not related to the `Monaco` changes

@Dmytro I need your help here, please take a look when you have a chance https://github.com/eclipse-che/che-theia/pull/1171#issuecomment-884694811

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse/che/pull/20204
