### ISSUE TITLE
Make the hostnames created for devworkspace endpoints stable in DWCO

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#20176]
### Describe the bug
DWCO uses map iteration order to determine parts of the hostname for created routes/ingresses for a DWR. This is not stable and may result in different hostnames being created during each reconciliation. While this is generally not a problem, because DWRs (DevWorkspaceRouting objects which DWCO reconciles) are not updated during the lifetime of a workspace, but IMHO we should be more defensive and tolerate and update of the DWR without the danger of endpoint hostnames changing.

Note that this is tricky - we cannot just sort the endpoints by name, because adding a new endpoint could change the order and therefore change the hostnames of some of the already exposed endpoints.

### Che version
latest

### Steps to reproduce
1. Create a devworkspace with `che` routingClass and start it
1. Let DWCO reconcile it and create all the ingresses/routes
1. Delete the DWRs of the workspace
1. Wait until DWO re-creates the DWRs and DWCO reconciles them
1. Sometimes the hostnames for the same endpoint might change after DWRs are recreated

### Expected behavior
The hostname of an endpoint should never change (unless it is renamed or something similarly "drastic")

**Comment by l0rd** [comment]
After discussion at latest dw cabal we decided to remove this issue from the scope of milestone "DevWorkspace Integration - STEP3".
