### ISSUE TITLE
Enable subpath mode for Che Theia editor in devworkspaces

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20180]
### Is your task related to a problem? Please describe.
At this point Che Theia editor https://github.com/eclipse-che/che-plugin-registry/blob/1fad8d4e2c14ecdc3681063841c37a60da6f9d5d/che-editors.yaml#L44-L98 
is not declared as the one that supports the subpath mode of serving for devworkspaces.

### Describe the solution you'd like
Add `urlRewriteSupported` attribute to each endpoint of Theia editor.

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by azatsarynnyy** [comment]
> the subpath mode of serving for devworkspaces

Could you clarify a bit more, what is `the subpath mode`? Do we have any doc on that?
What does `urlRewriteSupported` attribute mean? What are the steps to verify that everything works as expected, after adding this attribute?

**Comment by skabashnyuk** [comment]
>the subpath mode

aka `single host mode`. 

>What does urlRewriteSupported attribute mean

This endpoint can be server over the gateway in subpath mode. It. means that server is tolerant to the fact that his content would not be at the root. 

>What are the steps to verify that everything works as expected, after adding this attribute?

Add attribute, enable devworkspaces. Theia should be server over subpath, not the subdomain.

**Comment by sparkoo** [comment]
@xbaran4 can we close ?

**Comment by xbaran4** [comment]
Resolved by https://github.com/eclipse-che/che-plugin-registry/pull/1013
