### ISSUE TITLE
Che operator should use KIP to prepull arch-specific images

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20184]
### Is your enhancement related to a problem? Please describe.

Today, the Che operator use of KIP will prepull a number of sidecars, but it's hardcoded to the amd64 ones. Specifically, this means that for s390x and ppc64le, the openjdk8 and openjdk11 sidecars will be pulled, even though there are no openjdk8 or openjdk11 sidecars for those arches.

### Describe the solution you'd like

Since the Che operator is already arch-aware and can deploy RELATED_IMAGEs based on the uname suffix...

```
- name: RELATED_IMAGE_codeready_workspaces_plugin_java11
  value: registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-plugin-java11-rhel8:2.11
- name: RELATED_IMAGE_codeready_workspaces_plugin_java11_openj9
  value: registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-plugin-java11-openj9-rhel8:2.11
- name: RELATED_IMAGE_codeready_workspaces_plugin_java11_ppc64le
  value: registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-plugin-java11-openj9-rhel8:2.11
- name: RELATED_IMAGE_codeready_workspaces_plugin_java11_s390x
  value: registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-plugin-java11-openj9-rhel8:2.11
```
-- https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-operator-metadata/manifests/codeready-workspaces.csv.yaml#L1022-L1028

... we could reuse that logic so that on s390x and ppc64le deployments of Che/CRW, we would pull the **openJ9** images instead of the **openJDK** ones. 

This would both:
* improve java-based workspace performance on Z and Power, and 
* eliminate the pre-pulling of images what will never be used by users (there are no plugin-java*-rhel8 builds for Z or Power). 

### Describe alternatives you've considered

Or, we could enhance the list of regexes in https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/kubernetes_image_puller.go#L461-L476 to include the openj9 variants... but then we would be pulling openj9 images on amd64, and they'd never be used there as the plugin-java*-openj9-rhel8 containers are only built for Z and Power. 

### Additional context

* https://issues.redhat.com/browse/CRW-2064 and https://issues.redhat.com/browse/CRW-2082
* https://github.com/eclipse/che/issues/19657

**Comment by ibuziuk** [comment]
@tolusha removed deploy label. Also, I do not think this issue is a priority atm, according to @nickboldt 

> I agree it's not urgent as we don't know how many openj9 users we have on P/Z
