### ISSUE TITLE
Review kustomize changes which handles new operator-sdk for che-operator and handle them for chectl

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#20192]
### Is your task related to a problem? Please describe.
Review kustomize changes which handles new operator-sdk for che-operator and handle them for chectl if needed.

**Comment by tolusha** [comment]
The list of resources are created when Eclipse Che v7.34.0 is installed via OperatorHub are managed by chectl as well.
No action required.

![Screenshot from 2021-08-05 09-02-12](https://user-images.githubusercontent.com/1640675/128299365-aa2e72ac-437b-4641-9b5f-b9aef608f68c.png)
