### ISSUE TITLE
Sparse checkout broken

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2019]
Wrong behavior when importing a chosen module of a project

**Reproduction Steps:**
1. Clone https://github.com/artik-iot/artik-sdk-examples
2. Set http as keepDir in import window

**Expected behavior:**

The chosen module is checked out in the project tree

**Observed behavior:**

The chosen module is imported as submodule or an otherwise empty project.
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

![import](https://cloud.githubusercontent.com/assets/5337267/17320401/0dd070de-589c-11e6-87e3-362689aabeb1.png)

**Comment by ghost** [comment]
@vkuznyetsov we need this one for Samsung urgently

**Comment by vinokurig** [comment]
Git sparse-checkout works fine. We are not applying 'go into' to selected folder like it was in 3.x, because we can have more than one project in project explorer. In 3.x there is only one project can be opened in project explorer.
