### ISSUE TITLE
When DevWorkspace is enabled and Che is upgraded to a new version, existing workspaces should pick the new editors

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20193]
### Is your enhancement related to a problem? Please describe.

When Che uses DevWorkspace engine, everytime a user creates a workspace a DevWorkspaceTemplate object is created. The DWT has the description of the workspace editor ~~and plugins~~ extracted from Che plugin registry.

When Che is updated to a new version and the plugin registry contains updated descriptions of editors ~~and plugins~~ but the existing workspace will never be updated with the new editor~~/plugin~~ definition. 

### Describe the solution you'd like

At workspace re-start the client (Che UD) should check if there is the editor~~/plugins~~ described in the DWT has to be updated.

**Comment by sleshchenko** [comment]
@l0rd that's a good explanation on how editor update should work.
There are some minor stuff we can discover during implementing it, like probably we also should put plugin registry URL somewhere, like for DevSandbox where they have theia from CRW and theia from upstream.

> Then Che should manage it and updated it if the default changes.

Could you clarify if it's about Che Dashboard/Che Editor (like Theia) both?

> The DWT has the description of the workspace editor and plugins extracted from Che plugin registry.

With sidecar policy - use dev container, that's not true anymore. Plugin is merged with user's devfile and we don't have the ability to update it, at least good way from Dashboard side.
But maybe we should reconsider that policy, and to simplify stuff deny it from Milestone 3.
Or we may declare that we don't update plugins but I'm not sure about corner cases, and use dev container currently only make stuff more difficult to understand and trace.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by olexii4** [comment]
@max-cx
Yes. It requires some updates in the End-user Guide about a possible editor update If the editor is a default one.
