### ISSUE TITLE
Custom image fails on workspace build, stuck in "Starting"

### ISSUE THREAD

**Issue by robadler** [eclipse-che/che#202]
When creating a workspace based on an image that fails to execute/build/etc it gets stuck in "Starting" state. When there it can't be deleted, stopped, recovered, etc - or at least I haven't been able to find a way to yet.

**Comment by garagatyi** [comment]
I just tried Che with Dockerfile https://gist.githubusercontent.com/garagatyi/60b6ae414d9fb45b2390/raw/e40dcd3c2a7278b5724956de93ab89128b2dd5cc/gistfile1.txt and workspace status is Stopped.
Can you provide more information. Che version, dockerfile content, which error was thrown, etc.

**Comment by ghost** [comment]
@automatedtendencies can you repeatedly reproduce with with RC3?

**Comment by ghost** [comment]
Cannot reproduce with current master 4.0.1-RC1-SNAPSHOT
