### ISSUE TITLE
[che-auth] - enable nativeUserMode by default on openshift with devworkspaces

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#20203]
### Is your task related to a problem? Please describe.

Since we do not have any known blocker regression in `nativeUserMode` way of auth, we would like to enable it by default to gather feedback as soon as possible.

known issues:
 - https://github.com/eclipse/che/issues/20071 regression
 - workspace auth not implemented yet. Not a regression.
   - https://github.com/eclipse/che/issues/19707

### Describe the solution you'd like

Set `auth.nativeUserMode: true` by default when deploying on openshift with devworkspace engine.

### Describe alternatives you've considered

Keep it optional

### Additional context

epic: https://github.com/eclipse/che/issues/19182

**Comment by sleshchenko** [comment]
Actually, there is one user-facing change after we make it as default - it won't be possible to open Che Workspaces when DevWorkspace is enabled. So, let's discuss it again on the next devworkspace cabal.

**Comment by skabashnyuk** [comment]
>Actually, there is one user-facing change after we make it as default - it won't be possible to open Che Workspaces when DevWorkspace is enabled.

it would not change much since it wasn't declared as possible before. 
Is there an alternative plan have we can make devworkspace production-ready except start enabling necessary features one by one?

**Comment by sparkoo** [comment]
At the moment, Che Workspaces does not work with devworkspaces (https://github.com/eclipse/che/issues/20072). I assume it's "easy" fix, but still...

Then the question is, whether devworkspaces without authentication are really usable. I guess we can go 2 ways:
 - live with unsecure dev-workspaces and working che-workspaces and switch default only after both is working
 - switch default now and live with not-working che-workspaces and secure dev-workspaces, and start working on working che-workspaces (or not)

note that dev-workspaces are not authenticated yet with `nativeUserMode`, but we plan to work on it this sprint https://github.com/eclipse/che/issues/19707

Anyway, I'm now only creating draft PR to this, because I still have few open technical questions there. I'll raise a topic on dw cabal.

**Comment by sparkoo** [comment]
fixed by https://github.com/eclipse-che/che-operator/pull/978 and https://github.com/che-incubator/chectl/pull/1502
