### ISSUE TITLE
Project is not accessible in Dashboard

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#2020]
Project created in IDE is not accessible from Dashboard.

**Reproduction Steps:**
1. Open IDE
2. Select Workspace -> Create Project
3. Select Node JS and enter the name
4. Go to the workspaces list in the Dashboard
5. Select workspace and go to Projects tab
6. Click on the unnamed project

![screencast](https://cloud.githubusercontent.com/assets/16220722/17323850/5f14ed5c-58ac-11e6-96c4-cbb66707e334.gif)

**Expected behavior:**

Project tab contains hello-world project in list. Click on each project leads to it details page.

**Observed behavior:**

Project tab contains unnamed item in list. Click on it does not provide any details of project.

**Che version:**    4.6.0
**OS and version:** Ubuntu 14.04.4 LTS
**Docker version:** 1.11.2
**Che install:**  local 

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ashumilova** [comment]
Resolved
