### ISSUE TITLE
Is it possible to add annotations to the ingress's that Che makes when you start a workspace?

### ISSUE THREAD

**Issue by FoodyFood** [eclipse-che/che#20205]
Hi,

So there are the standard ingress's as we know for the devfile, plugin, che-host etc, and then there those extra ingress's that are generated when a workspace starts, like this one I captured.

I wondered, is there a setting, a place in the helm chart, or a place in the config map that I have missed that would let me put in a couple of extra annotation in there?

![image](https://user-images.githubusercontent.com/16269177/127139562-7a74c8ee-7070-4ac1-97b0-19fc1cba95e2.png)

In particular I wanted to insert one for nginx.

So I had a look and found these but none stood out for the ingress's it generates:

devfileRegistryIngress | The devfile registry ingress custom settings.
pluginRegistryIngress | Plugin registry ingress custom settings.
cheServerIngress | The Che server ingress custom settings.

**Comment by skabashnyuk** [comment]
At this moment - no. PR in progress https://github.com/eclipse-che/che-server/pull/57  and https://github.com/eclipse/che/issues/16426

**Comment by FoodyFood** [comment]
> At this moment - no. PR in progress [eclipse-che/che-server#57](https://github.com/eclipse-che/che-server/pull/57) and #16426

Thank you so much! I'll close this question and watch the PR :)
