### ISSUE TITLE
spring petclinic devworkspace sample does not have devfile.yaml

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#20211]
### Describe the bug

Our spring petclinic sample that is shown when devworkspaces are enabled, does not have `devfile.yml` with devfile v2 content. It is actually started as v1, with che-server creating the workspace.

### Che version

 - [x] latest

### Steps to reproduce
1. deploy with devworkspace enabled
2. start spring pectlinic sample
3. check che-server logs, that it is actually starting a workspace
4. check `devworkspace` objects in user's namespace, there's none

### Expected behavior

spring petclinic should have devfile v2 file, so it is properly started with devworkspace.

Alternatively, we should "autogenerate" devfile v2 when resolving the factory, when devworkspaces are enabled.

### Runtime
   - [x] Openshift (include output of `oc version`)

### Installation method
   - [x] chectl `chectl server:deploy --platform=openshift --installer=operator --workspace-engine=dev-workspace`

### Environment
   - [x] Cloud
       - [x] rhpds

### Eclipse Che Logs

```
2021-07-27 13:35:05,945[nio-8080-exec-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 475]   - Starting workspace 'user10/java-spring-petclinic6c6lg' with id 'workspace8rnucx0am19yo0si' by user 'user10'
```

**Comment by vzhukovs** [comment]
Need to add `devfile.yml` to the forked repository https://github.com/che-samples/java-spring-petclinic

**Comment by benoitf** [comment]
the devfile is in the custom branch https://github.com/che-samples/java-spring-petclinic/tree/devfilev2

**Comment by sparkoo** [comment]
already fixed
