### ISSUE TITLE
No index.html when creating a java-swing workspace with mentioned stack

### ISSUE THREAD

**Issue by michaellee8** [eclipse-che/che#2021]
I try to follow instructions in [https://eclipse-che.readme.io/docs/che-and-swing](https://eclipse-che.readme.io/docs/che-and-swing) to creat a java swing workspace, but it seems something is wrong.

**Reproduction Steps:**
1. Create a project from dashboard, according to the first box of instruction
2. Use the custom stack in [https://hub.docker.com/r/codenvy/ubuntu_jdk8_x11/~/dockerfile/](https://hub.docker.com/r/codenvy/ubuntu_jdk8_x11/~/dockerfile/)
3. Problem comes out, the log files is here

```
[DOCKER] latest: Pulling from codenvy/ubuntu_jdk8 
[DOCKER] Digest: sha256:83a1cfefdf56dc8194055b6c2e97ec2ce1c7819f4102420a83e6e5f35e0f3138 
[DOCKER] Status: Image is up to date for codenvy/ubuntu_jdk8:latest 
[DOCKER] ---> 5fca53411e54
[DOCKER] Step 2 : RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends supervisor x11vnc xvfb net-tools blackbox rxvt-unicode xfonts-terminus libxi6 libgconf-2-4
[DOCKER] ---> Using cache
[DOCKER] ---> f7142b00fe4d
[DOCKER] Step 3 : RUN sudo mkdir -p /opt/noVNC/utils/websockify && wget -qO- "http://github.com/kanaka/noVNC/tarball/master" | sudo tar -zx --strip-components=1 -C /opt/noVNC && wget -qO- "https://github.com/kanaka/websockify/tarball/master" | sudo tar -zx --strip-components=1 -C /opt/noVNC/utils/websockify
[DOCKER] ---> Using cache
[DOCKER] ---> e069018705d0
[DOCKER] Step 4 : ADD index.html /opt/noVNC/
[DOCKER] [ERROR] lstat index.html: no such file or directory
```

**Expected behavior:**

Workspace created, everything works fine

**Observed behavior:**

Creation process stopped in something like `Creating workspace`

**Che version:**    4.5  
**Che install:**   Codenvy 

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: I don't know
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@ddementieva - please take a look.

**Comment by ddementieva** [comment]
@michaellee8 If you copy a complete Dockerfile, you need to remember, that files, added to the container with ADD instruction, such as index.html, should be in the directory, where Dockerfile is located. Take a look at how it's done for our default x11_vnc image: https://github.com/codenvy/dockerfiles/tree/master/x11_vnc 

You can simply paste `FROM codenvy/ubuntu_jdk8_x11`, as it's stated in the Tutorial, to the Select Stack > Custom Stack. 

![custom-stack](https://cloud.githubusercontent.com/assets/6860395/17331689/aeaa3962-58d4-11e6-8c4d-4e51ca293061.png)

**Comment by michaellee8** [comment]
Thank you, i can start workspace now but i don't know how to do some of rest

```
#In the noVNC window right mouse click to call the Terminal. Go to `projects/{your-project-name}/target` directory and start your project:
```

Can anyone explain how to get that noVNC window pls? I get ERR_CONNECTION_REFUSED each time I try to do the fire up my browser to the link in preview

**Comment by ddementieva** [comment]
@michaellee8 Are there any errors in the browser console? Can you send a screenshot with browser dev console opened?

**Comment by ghost** [comment]
@michaellee8 any update on this? Are you running Che locally or in the cloud?

**Comment by ghost** [comment]
Closing this. Feel free to reopen if the problem persists.
