### ISSUE TITLE
Starting a simple workspace in Che leads to pulling dozen of useless images

### ISSUE THREAD

**Issue by vemonet** [eclipse-che/che#20223]
### Is your enhancement related to a problem? Please describe.

When starting a simple workspace (in my example python, but the issue is with any workspace) Che will first pull dozens of images and run dozens of containers to "prepare the workspace" (I guess), which is not necessary. It leads us to wait for dozens of minutes, and the workspace deployment to ultimately fail most of the time.

We have an OKD4.6 cluster installed on bare metal, we installed Che 7.33.2 from the OperatorHub

I sometimes managed to start workspaces (showing the installation worked!), but most of the time it will fail due to pulling the dozens of useless images taking too much time.

This **creates security issues**. Because as a user I cannot trust the dozens of image Che is automatically running (cf. the list of images below). But I can review and trust the **1 VisualStudio Code image** I actually want to run. Running that many obscure images give attackers a much larger surface of attack on clusters

This also creates **environmental concerns** by using way more resources that it actually needs. This puts Docker registries under high stress due to software like Che which are pulling dozens of images to do the simplest task (this is the reason why DockerHub added pull rates limits...)

Here is the list of useless images that are pulled and started in my case (to start a default Python workspace):
* Pulling image "quay.io/eclipse/che-plugin-metadata-broker@sha256:df1ea2eadb28dbc97761adf4ea984af5ca941025a67b39c6abe373816a84bba9"
* Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:e30114658be537fc578efda0edd5760c024fb159695a437efb3ad78e6bf7c615"
* Pulling image "quay.io/eclipse/che-plugin-artifacts-broker@sha256:4891a6e19be9eae59372f4b31144653f9bd1284e0301ecfe896a099ca6a12b58"
* Pulling image "quay.io/eclipse/che-jwtproxy@sha256:881d1c91e7f5840314f25104ef5c0acee59ed484a5f9ef39daf3008725ea1033"
* Pulling image "quay.io/eclipse/che-python-3.8@sha256:ddbdec22abee20dcf23ce5ea06e82bc9d3f34d46d755388d03d6b6db9be52ccb"
* Pulling image "quay.io/eclipse/che-plugin-sidecar@sha256:7919d965a77f1ec969e073a1cc86686f92e99fc53a0b0c8d2eb13aea61c63467"
* Pulling image "quay.io/eclipse/che-theia@sha256:d4c034322792afbc97e67aa1be841179252250a94a3abb3ea5ba21cf0bb33634"
* Pulling image "quay.io/eclipse/che-machine-exec@sha256:b32f6bfa456d1a555c470c4d4ffa3a000a767ef462a5a859411d8a2db7692aae"

In this case the deployment failed here with `Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the workspace'workspacenqsey3lbxeeigk28' reached timeout"`

Otherwise this would have continued to start dozens of images until finally starting my VSCode workspace, but then the workspace would have go down if I don't use it for a few minutes, and I would need to restart it (which is randomly successful) 

### Describe the solution you'd like

All you should be doing is to start 1 container based on a VisualStudio Code image, and attach it to the persistent volume. In general a software like Che should strive for reducing the number of different containers used and aim to adopt Occam's razor principles: only add complexity when it is really necessary. **There is no need for running dozens of images to start a simple VSCode container**.

If you need to do some preparation of the VSCode container then you can just run a configuration script at the startup of the container.

### Describe alternatives you've considered

I am currently not using Che for workspace because I just start my VSCode image directly using a template built by me. It takes less than 30s and works 100% of the time.

I understand that you need to run some stuff to prepare the workspace, but the current state of starting a workspace in Che seems to be heavily over-engineered at a point that it is hard to believe it is actually used by people in production

### Additional context

Here is a screenshot (failing after more than 10minutes of pulling images)

![Screenshot from 2021-07-29 11-35-09](https://user-images.githubusercontent.com/3778439/127470587-d8d338bf-5fcf-4e3c-b2bf-12e95a09182e.png)

**Comment by sparkoo** [comment]
It's not as simple as you probably imagine. I'm not saying that reducing the number of containers isn't a good idea. BUT

Point of the devfile is to have descriptive definition of the workspace, which you can easily share, modify, reuse etc. Che supports multiple editors, many plugins, workspaces are highly customizable, run on multiple environments, can run in offline environment, workspaces must be secure and isolated, etc. etc. All this brings complexity with it and I would agree that if you're single-user and you want something lightweight, Che might not be right fit for you. You can read through the intro page in che-docs https://www.eclipse.org/che/docs/che-7/overview/introduction-to-eclipse-che/. It's explaining quite well what is Che good for and what it can do. You may then better understand why things are how they are.

 - Workspace has plugins, where customers might want to have their own plugins, so we need plugin registry + something that can talk with that registry can prepare the plugins for the workspace -> `quay.io/eclipse/che-plugin-metadata-broker` + `quay.io/eclipse/che-plugin-artifacts-broker`. 
 - In container world, it makes sense to package plugin into container. So you have your `quay.io/eclipse/che-python-3.8` (plugin), `quay.io/eclipse/che-plugin-sidecar` (I believe this is for intention to put all needed plugins into single container). 
 - `quay.io/eclipse/che-theia` is actually your editor, so I wouldn't consider it useless. 
 - `quay.io/eclipse/che-machine-exec` is running terminals and tasks in the workspace. 
 - `quay.io/eclipse/che-jwtproxy` makes sure that only owner of the workspace has access to it.

With amount of image pulling, the second start of the workspace should have the images pulled already + we also have https://github.com/che-incubator/kubernetes-image-puller which you can use for image caching (I don't have much experience with it though).

Please, if you find any security issues, don't hesitate to contact us. Security is very important for us.

I hope it explains a bit why things are how they are (and I hope I didn't write something inaccurately, others might correct me :) )

**Comment by vemonet** [comment]
Hi @sparkoo Thanks a lot for this detailed answer!

> the second start of the workspace should have the images pulled already

It was already the second start of the workspace. The problem was that we actually manage to start it once or twice, but restarting it would always take a lot of time, and finally timeout most of the time, so it is hard to consider Che as a workspace runner we can trust 

From the descriptions it seems like the amount of containers could be reduced drastically:

* The plugin broker and workspace preparer: `quay.io/eclipse/che-plugin-metadata-broker` + `quay.io/eclipse/che-plugin-artifacts-broker` : if those 2 are always required to handle plugins and prepare the workspace, why do we need 2 and not just 1 container to handle plugins all-together? Checking at the description in their GitHub repo: https://github.com/eclipse/che-plugin-broker they basically just download a few files and setup some env variables (note there is already just 1 code repo for those 2 images)
* For `che-machine-exec` the terminal and running tasks seems to be a basic feature of the editor, so couldn't it be directly integrated in `eclipse/che-theia`? (at least that's already the case for the terminal in the image I usually use, and this image seems to be quite big seems it is the one that timed out in my example)
* For `quay.io/eclipse/che-jwtproxy`: authentication and authorization seems to be quite a basic feature for accessing the editor, couldn't it be also integrated within che-theia too?

Most "plugins" from `eclipse-che` are actually just VSCode extensions with additional complexity, as said in the [introduction](https://www.eclipse.org/che/docs/che-7/overview/introduction-to-eclipse-che/):

> As a result, it is easy to bring an existing plug-in from Visual Studio Code into Eclipse Che. The main difference is in the way the plug-ins are packaged. On Eclipse Che, plug-ins are delivered with their own dependencies in their own container. 

So most of them could just be added directly to `eclipse-theia` under the form of VisualStudio Code extensions without the need for pulling a whole image for each extension (what if I need to install an 15 extensions?).

From my experience installing a VisualStudio Code extension takes less than 5s on my local laptop or in my containerized VSCode, and it never fails. I have a hard time to understand why we need to add a whole container for each of those plugin

Note that I love containers and I have been using them extensively for years, but in this case it seems like it could be used with more parsimony otherwise it can easily become a problem

**Comment by benoitf** [comment]
Hi,

it seems your overall problem is the time to pull the images.
Then you should enable the kubernetes image puller https://www.eclipse.org/che/docs/che-7/administration-guide/caching-images-for-faster-workspace-start/
Then there is a local cache and you don't need to wait to pull images on every workspace start/restart.

>  I have a hard time to understand why we need to add a whole container for each of those plugin

your image may not have all the requirements, so it pulls sidecars to execute the extensions. For example the Theia only has nodejs runtime so it won't be able to run VS Code java that requires java. And as you don't post-install stuff in containers, then the extension comes with its runtime (java) and execute the extension there.

Note that with DevWorkspaces 2, it's possible to execute extensions in the 'user container'
https://che.eclipseprojects.io/2021/06/23/@florent.benoit-devfile-v2-and-ide-plug-ins.html#deploy-plug-ins-in-existing-containers


> For che-machine-exec the terminal and running tasks seems to be a basic feature of the editor, so couldn't it be directly integrated in eclipse/che-theia? (at least that's already the case for the terminal in the image I usually use, and this image seems to be quite big seems it is the one that timed out in my example)

At some point we introduced the machine-exec endpoint as a standalone container so that any IDE wanted to connect to all containers of the pod could reuse this endpoint (so a separate container)

But yes we're planning to store the machine-exec binary in the IDE image as well. 
https://github.com/eclipse/che/issues/20018

And reduce some init containers by merging them as well
https://github.com/eclipse/che/issues/20018

**Comment by benoitf** [comment]
With DevWorkspace engine and single-container for plug-ins we've reduced the number of containers

DevWorkspace being the default engine starting with 7.42.0, we can close the issue.
