### ISSUE TITLE
Incorrect factory validation behavior when field value matches default for its type

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#2022]
Factory validator fails when field value matches default for its type, e.g. if set `boolean` variable to `false`, ot `intereger` to `0`e.t.c

Issue related to https://github.com/codenvy/codenvy/issues/455

**Reproduction Steps:**
Try create factory with several machines described, when one of them has `"dev" : false` property.

**Expected behavior:**
Factory must be created

**Observed behavior:**
Factory validator throws error saying "dev" property is not set

**Che version:**    4.6.0

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@mshaposhnik - should this belong in a different repository - /codenvy/codenvy

**Comment by mshaposhnik** [comment]
@TylerJewell No - factory API is in Che.

**Comment by bmicklea** [comment]
@mshaposhnik was is merged into the 4.7.0 milestone?  If so please add that milestone designation to this issue.
