### ISSUE TITLE
Inject of all RELATED_IMAGES_* env variables for plain operator (not just OLM)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20228]
### Describe the bug

Today, the `RELATED_IMAGE` env vars are injected only when installing via OLM for OCP 4.6+.

But in CRW-1157, we're moving away from hard-coded, pregenerated registry digests and instead plan to use these `RELATED_IMAGE` variables.

This means that at build time, related image (sidecars, theia, machine-exec) references will use floating tags (7.34.2, 2.11), and the at run time, entrypoint.sh will switch from tags to the sha256 digests, ensuring that the correct images are always used.

This will also make it easier/faster to rebuild the whole Che / CRW stack for nightly builds, eg., if a sidecar is updated for a bugfix, the only image that will then also need to be rebuilt is the operator-metadata, as the CSV will need a fresh digest for the new sidecar. 

**So what's the problem?**

RELATED_IMAGE env vars are only available for OLM-installed Che / CRW installations. This means all the great plans above won't work for OCP 3.11 users and k8s users. 

**Proposed solution:**

For **BOTH** the OLM and Operator style installs (via chectl or operator hub), inject RELATED_IMAGE env vars such that the plugin and devfile registry containers can resolve those variables when the container pods start up. 

### Che version

 - [x] latest 7.34

### Installation method
   - [x] chectl

### Additional context

https://issues.redhat.com/browse/CRW-1157?focusedCommentId=16486614&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16486614

**Comment by nickboldt** [comment]
Dumb question:

Do digests even work in OCP 3.11? I feel like we specifically don't use them in CRWCTL deployments because they're not supported. So... maybe we don't need to do anything to support related image env vars on OCP 3.11.

**Comment by tolusha** [comment]
We have RELATED_IMAGES for an operator since 7.33.0 [1] (and a fixup for 7.34.0 [2])

[1] https://github.com/eclipse-che/che-operator/pull/893
[2] https://github.com/eclipse-che/che-operator/pull/967

Scripts updates operator templates on release, so only a tagged version of che-operator contains those env variables.

**Comment by nickboldt** [comment]
The issue I raised above was for OCP 3.11 and k8s support, where OLM doesn't exist:

> RELATED_IMAGE env vars are only available for OLM-installed Che / CRW installations. This means all the great plans above won't work for OCP 3.11 users and k8s users.

Do we have a solution for OCP 3.11/k8s? Should we just use hardcoded tags instead of trying to replace those tags with digests?
