### ISSUE TITLE
eclipse-che.github.io/che-devfile-registry is not updated with a new releases

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20224]
### Describe the bug
eclipse-che.github.io/che-devfile-registry is not updated with a new releases 
the latest available is https://eclipse-che.github.io/che-devfile-registry/7.32.2/ there are no 7.33.x

### Expected behavior
https://eclipse-che.github.io/che-devfile-registry/7.33.2/ returns the dedicated version - currenlty 404 

### Additional context
Most likely related to https://github.com/eclipse-che/che-devfile-registry/commit/4a6d9f22b928bc122eae3791f197b6e4ca79a212

**Comment by benoitf** [comment]
release script is now publishing as expected the files
https://github.com/eclipse-che/che-devfile-registry/tree/gh-pages
