### ISSUE TITLE
In multi-user mode, deploying via Helm, allow defining imagePullSecrets for Workspace Service Account

### ISSUE THREAD

**Issue by gustavoromerobenitez** [eclipse-che/che#20239]
### Is your enhancement related to a problem? Please describe.
Workspaces cannot pull images from a private repository under the following circumstances:

- Che 7.33.2.
- Multi-user mode.
- Helm Chart deployment.
- Private GKE cluster using a private image repository (Nexus).
- Automated installation, without manual intervention, hence adding credentials via the console is not an option.
- Also not able to use registry.username and registry.password in values.yaml due to security restrictions.

The image pull secret is defined as kubernetes secret using the .dockerconfigjson format. It has been added to the controller workspace manually. That has allowed me to deploy the Controller components by specifying the imagePullSecrets in the _che_ Service Account  (serviceaccount.yaml)  or in the Deployment manifests for each component.

I cannot create workspaces because the workspaces Service Account is created by Che and it does not seem to pass on the imagePullSecret.

### Describe the solution you'd like
Please provide a way to either:
- Pass the imagePullSecret to the workspace Service Account via a Che property, hence via the configmap.yaml file. 
- or define the manifest for the Workspace Service account to allow adding the imagePullSecrets.
- or any other way to:
  - Define manifest to be created dynamically in user workspaces.
  - Allow workspaces to read existing secrets and pull images from a private repository.

### Describe alternatives you've considered
I have previously used the above setup with Google Container Registry without issues, since authentication was handled via workload identity however, that solution is not compliant with security policies I have to adhere to. The issue appeared when I switched to a Nexus repository with credentials defined in a .dockerconfigjson kubernetes secret. 

I'm aware t would be possible to read the repository credentials from a vault and replace the registry.username/password values at the beginning of s deployment pipeline however, that solution only allows to connect to one repository. Having a .dockerconfigjson kubernetes secret allows having multiple repository credentials into one file and, with the right configuration, pulling images from different repositories. For instance, some images might live in a staging repository while waiting to be tested, and other images can be stored in a production repo, after having passed vulnerability scanning and attestation.

### Additional context
In the workspace logs, I find the error below which shows a response from the Nexus server that is consistent with scenarios where the correct credentials have not been provided.

```
Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'Failed', 'Failed to pull image "repository.*****/***/che-plugin-metadata-broker:v3.4.0": rpc error: code = Unknown desc = Error response from daemon: error parsing HTTP 400 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center></body>\r\n</html>\r\n"', 'workspaceqrju4dj62dbg231i.che-plugin-broker'
```

**Comment by tolusha** [comment]
@gustavoromerobenitez 
Can it [1]  [2] fit your needs? if not, could you contribute into the project?

[1] https://github.com/eclipse/che/issues/19999
[2] https://github.com/eclipse-che/che-server/pull/49

**Comment by gustavoromerobenitez** [comment]
@tolusha Thanks you for your quick reply. I have tried with che-server:7.34.0 which contains the code in that PR but the workspace-creator pod  (mkdir-workspace...), that is created in a new user namespace in GKE, fails to pull the image from the private registry. The manifest for that pod does not contain an imagePullSecrets: section.

I'll look into making a contribution as you suggested. In the meantime, I'd appreciate it any of the proposed solution could be considered as a future improvement.
