### ISSUE TITLE
[UD] inform users about any unsupported browsers

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20236]
### Is your task related to a problem? Please describe.
After https://github.com/eclipse-che/che-dashboard/pull/315 we inform users about unsupported safari, since we know that it's not going to work, but actually, we don't support any other browsers than Google Chrome.

So, it's needed to show that banner on any browser if it's not Google Chrome for people to expect possible issues on that browsers.

**Comment by ibuziuk** [comment]
What about Firefox - https://github.com/eclipse/che/issues/14015 ?

**Comment by sleshchenko** [comment]
@ibuziuk QE does not verify anything else but only Google Chrome, so it's not officially supported IMHO.
But I'm happy to hear alternatives proposal/opinions.

**Comment by kollachaitanyakrishna** [comment]
Since IE Edge also built on chromium, try to enable the IE Edge also.
