### ISSUE TITLE
Limit new all-namespaces-stable channel to OpenShift 4.8+

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20234]
### Is your task related to a problem? Please describe.
On the latest DevWorkspace Cabal we agreed that CRW 2.11 with devworkspace support is going to be limited to be supported only starting from OpenShift 4.8.
So, it means that new channel is not going to appear on older OpenShift as well.

**Comment by nickboldt** [comment]
Related downstream issue https://issues.redhat.com/browse/CRW-2138
