### ISSUE TITLE
Can not enable the latest upstream 7.34.0 devfile registry on workspaces.openshift.com

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20233]
### Che version
CRW 2.9 

### Steps to reproduce

1. enable upstream 7.34.0 devfile registry on workspaces.openshift.com
2. start any of the upstream devfiles
3. ERROR: `Failed to create a new workspace from the devfile, reason: Devfile schema validation failed. Error: `

![image](https://user-images.githubusercontent.com/1461122/127834432-d98d8bdd-52da-45e1-85d0-1d495b816983.png)

If you check devfile https://eclipse-che.github.io/che-devfile-registry/7.34.0/devfiles/java-mysql/devfile.yaml you'll see that registryUrl is empty string while it's supposed to lead to upstream plugin registry.
 
### Expected behavior
Workspace based on upstream devfile is started correctly 

### Runtime
   - workspaces.openshift.com

### Additional context
Currently, we are using 7.32.2 upstream version of devfile registry, which works correcty

**Comment by benoitf** [comment]
should be fixed by https://github.com/eclipse-che/che-devfile-registry/commit/e9c54caae4876ceaf511e9abc9b9eb160783a1ed
