### ISSUE TITLE
PythonDjango test devfile needs update

### ISSUE THREAD

**Issue by Warfvf** [eclipse-che/che#20230]
### Describe the bug

Currently, there in test devfile `PythonDjango.spec.ts` is a suite that runs task 'set up venv', which no longer exists. Also we need a suite, which runs task 'run server in debug mode'.

We need to edit the PythonDjango test devfile by updating task running suits.

https://github.com/eclipse/che/blob/59ec70a890b67b47c0a37dda7b032411eba5da7b/tests/e2e/tests/devfiles/PythonDjango.spec.ts#L46

### Che version

 - [x] latest
 - [x] nightly
 - [x] other: please specify

### Steps to reproduce

* start `PythonDjango` test devfile

### Expected behavior

All testing suites passed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`): 
```
Client Version: 4.7.16
Server Version: 4.7.0-0.nightly-2021-06-07-203428
Kubernetes Version: v1.20.0+2817867
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output): `chectl server:deploy -p openshift --no-olm-suggested-namespace --telemetry=off -n warfvf-che
(node:94902) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
› Installer type is set to: 'olm'
› Current Kubernetes context: 'warfvf-che/api-ocp47-aws-crw-qe-com:6443/admin'
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "warfvf-che"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
    ✔ Check OpenShift version: 4.x
    ✔ Check Kubernetes version: Unknown.
  ✔ Following Eclipse Che logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che Server logs...done
    ✔ Start following PostgreSQL logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plug-in Registry logs...done
    ✔ Start following Devfile Registry logs...done
    ✔ Start following Eclipse Che Dashboard logs...done
    ✔ Start following namespace events...done
  ✔ 🏃  Running Olm installaion Eclipse Che
    ✔ Check if OLM is pre-installed on the platform...done.
    ✔ Create Namespace (warfvf-che)...It already exists.
    ✔ Create operator group...created new one.
    ✔ Configure context information...done.
    ✔ Create nightly index CatalogSource in the namespace warfvf-che
    ✔ Create operator subscription...created new one.
    ✔ Wait while subscription is ready...done.
    ✔ Wait while operator installed...done.
    ✔ Prepare Eclipse Che cluster CR...Done.
    ✔ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace warfvf-che...done.
  ✔ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Keycloak pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Devfile Registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Plug-in Registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che Dashboard pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che Server pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che status check...done
  ✔ Retrieving Che self-signed CA certificate...OK
  ✔ Prepare post installation output...done
  ✔ Show important messages
    ✔ Eclipse Che 7.33.0-SNAPSHOT has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://che-warfvf-che.apps.ocp47-aws.crw-qe.com
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://plugin-registry-warfvf-che.apps.ocp47-aws.crw-qe.com/v3/
    ✔ Devfile Registry          : https://devfile-registry-warfvf-che.apps.ocp47-aws.crw-qe.com/
    ✔ -------------------------------------------------------------------------------
    ✔ Identity Provider URL     : https://keycloak-warfvf-che.apps.ocp47-aws.crw-qe.com/auth/
    ✔ Identity Provider login   : "admin:kaHEZ2AqYZIG".
    ✔ -------------------------------------------------------------------------------
    ✔ [ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /tmp/cheCA.crt.
   Documentation how to add a CA certificate into a browser: https://www.eclipse.org/che/docs/che-7/end-user-guide/i
mporting-certificates-to-browsers/
Command server:deploy has completed successfully in 08:34.`
     * provide an output of `chectl version` command:  `chectl/0.0.20210729-next.6041615 linux-x64 node-v12.22.3
`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs

N/A
### Additional context

N/A

**Comment by dmytro-ndp** [comment]
@Katka92: do you think _Hosted Che_ QE team could take care of this issue?

**Comment by Katka92** [comment]
@dmytro-ndp Sure, I thought it's already done. @Warfvf could you please explain if there is any amount of work remaining? I see your PR is merged. If not, please close the issue. Thanks

**Comment by Warfvf** [comment]
@Katka92 yes, it is done, i'll close it. Thank you
