### ISSUE TITLE
Helm/Operator deployment - Add nodeSelector for Controller components

### ISSUE THREAD

**Issue by gustavoromerobenitez** [eclipse-che/che#20240]
### Is your enhancement related to a problem? Please describe.
Currently it is possible to provide a Che property value to configure the K8s node pool where the workspaces will run, but I could not find a way to define the node pool for the **controller components** in the Helm and Operator deployment strategies. 

I have not tried chectl, but I could not find a Che property for the above purpose so I assumed it would not be possible either.

### Describe the solution you'd like
Add a Che property to configure the K8s Node group where the Controller components will run, to allow both controller and workspaces to run on **non-default** node groups in a shared K8s cluster

### Describe alternatives you've considered
For now, I have followed this approach (snippet below):
- Edited the manifests of all the controller components I needed (server, dashboard, keycloak, postgres, devfile-registry, plugin-registry) 
- Added the _nodeSelector_ entry under specs
- Added new properties in values.yaml to define the nodeSelector label. In this case it is a label called workload which values were either _che-controllers_ or _che-workspaces_)

```
spec:
  template:
    spec:
      nodeSelector:
        workload: {{ .Values.global.controllerNodeSelector }}
```

With the above approach, I have managed to deploy the controller components and workspaces in two different non-default K8s (GKE) node pools.

### Additional context
Che 7.33.2
GKE
Multi-User mode

**Comment by skabashnyuk** [comment]
@gustavoromerobenitez can you please clarify what do you mean by " Controller components" ?
Are you talking about this https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspaces-nodeselector/ ?

**Comment by gustavo-benitez-ctr** [comment]
@skabashnyuk No, I'm referring to the Che Server, Dashboard, Plugin registry, Keycloak, Devfile Registry and Postgres components that form the [Che Controller](https://www.eclipse.org/che/docs/che-7/administration-guide/che-workspace-controller/).

When I deployed the Helm charts in GKE for the first time, those components were always deployed to the default Node Pool. It should be possible to specify a nodeSelector for each on of those Deployments.

Adding a nodeSelector to each deployment.yaml file, allowed me to deploy them to a specific Node Pool in GKE.

Let me know if you need any additional clarification. Thank you.

**Comment by skabashnyuk** [comment]
CC @tolusha looks like related to deployment. wdyt?

**Comment by skabashnyuk** [comment]
Fixed for operator https://github.com/eclipse-che/che-operator/pull/1301
