### ISSUE TITLE
Directory traversal vulnerability in Codeready/Che workspace request

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#20244]
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Enable the Network tab in your browser and see the request that come in as the page loads
2. Load a CodeReady/Che workspace in that browser window 
3. One of these requests is https://routehd64kxqu-codeready-admin.apps.mycluster.com/hostedPlugin/vscode_theme_solarized_dark/themes/solarized-dark-color-theme.json
4. End user can traverse the directory in that container and look at any file.

### Expected behavior
End user can only request the necessary file: solarized-dark-color-theme.json

### Actual behavior
End user can modify the url like so in order to see other files in the container:

https://routehd64kxqu-codeready-admin.apps.mycluster.com/hostedPlugin/vscode_theme_solarized_dark/themes/../../../../etc/passswd
https://routehd64kxqu-codeready-admin.apps.mycluster.com/hostedPlugin/vscode_theme_solarized_dark/themes/../../../../run/secrets/kubernetes/serviceaccount/service-ca.crt

Note: The browser by default strips out relative paths like ../../ so a special tool needs to be used to modify the request before it's sent out. 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) Custom hosted OpenShift 
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by benoitf** [comment]
Hello @kristinochka , the workspace pod (where Theia container is running) is dedicated to one user.
And the IDE route is only accessible by this user (it requires authentication)

So there is no vulnerability as once you're logged in, you can open terminals to any containers and read all the files there.
And you can only see pod/resources/files that you own.

Basically, as a user you've access to all the files you own (using URLs or executing commands in the IDE, etc)

Sharing a link like
https://routehd64kxqu-codeready-admin.apps.mycluster.com/run/secrets/kubernetes/serviceaccount/service-ca.crt

won't work as people will need to log-in.

**Comment by ArvinB** [comment]
@benoitf 
Thank you for the response. @kristinochka and I did validate that you must be logged in to access the files for a given workspace otherwise the following error is presented.

```
Error: Failed to get the workspace: "The user does not have permission to read workspace with id 'workspacepf3piqhslrthfjyn'"
```

We will send this back to IBM's penetration testing team for further review. Again thank you for your timely response.

FYI @nickboldt @ericwill
