### ISSUE TITLE
Is there anyway I can run podman inside eclipse che container.

### ISSUE THREAD

**Issue by amoldeshpande05** [eclipse-che/che#20241]
I am trying to use podman docker image quay.io/podman/stable:latest, 
Dockerized it and linked it to devfile.

When I try podman, I get the following error.
Error: mount /home/xyz/.local/share/containers/storage/overlay:/home/xyz/.local/share/containers/storage/overlay, flags: 0x1000: permission denied

**devfile**
`components:
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 3000
    memoryLimit: 3Gi
    type: dockerimage
    alias: apic
    image: 'amoldeshpande/test-podman'`
    
    
**dockerfile** : 
    FROM quay.io/podman/stable
    CMD sleep infinity
    
Is there any che plugin I can use? or any steps to achieve podman inside eclipse che is appreciated.

**Comment by xbaran4** [comment]
Not sure if this is for plugins. CC @svor ?

**Comment by vitaliy-guliy** [comment]
I have tried it before, but wasn't lucky. Seems there were issues with permissions.
At the moment we can run `buildah` and `buildkit`, but only on local minikube deployments.

**Comment by amoldeshpande05** [comment]
@vitaliy-guliy 
Like you said, I am using buildah plugin.
When I run buildah command. I am getting permission denied.


`buildah from docker.io/alpine
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1724` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1724` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
Getting image source signatures
Copying blob a0d0a0d46f8b done  
Copying config 14119a10ab done  
Writing manifest to image destination
Storing signatures
ERRO Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: permission denied 
Error committing the finished image: error adding layer with blob "sha256:a0d0a0d46f8b52473982a3c466318f479767577551a53ffc9074c9fa7035982e": ApplyLayer exit status 1 stdout:  stderr: permission denied
ERRO exit status 1  `

where to provide the permissions?

**Comment by vitaliy-guliy** [comment]
> where to provide the permissions?

We haven't yet investigated it in dept.
