### ISSUE TITLE
Transition from Java EE to Jakarta EE

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20247]
### Is your task related to a problem? Please describe.
Some of the downstream products that use everrest has difficulties with using Java EE implementations.

### Describe the solution you'd like
The goal of this task is to migrate to Jakarta EE specifications.
That is 
 - jakarta.servlet-api  5.0.0
 - jakarta.ws.rs 3.0.0
 - Tomcat 10.0.8
 - Jetty 11.0.6
 - jakarta.mail
 - jakarta.xml.bind-api
 - jakarta.activation

### Additional context
Context 
 - https://blogs.oracle.com/javamagazine/transition-from-java-ee-to-jakarta-ee
 - https://issues.redhat.com/browse/CRW-2122
 - https://www.eclipse.org/jetty/
 - https://github.com/codenvy/everrest/pull/62
 - https://github.com/codenvy/everrest/issues/61

**Comment by benoitf** [comment]
Removing `status/release-notes-review-needed` label because there is no `n&noteworthy` label
if really new&noteworthy it should have a `release notes` section

**Comment by skabashnyuk** [comment]
`javax.persistance` has not been migrated yet.
