### ISSUE TITLE
Push the new bundle format to community operators

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#20250]
### Describe the solution you'd like

Currently we are pushing to community operators using old bundle format where is not included DevWorkspace dependency or the bundles metadata.

Right now in community operators we are pushing onlythe manifests: https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/eclipse-che

Figure out how to push the new bundle format to community operators.

**Comment by tolusha** [comment]
duplicates https://github.com/eclipse/che/issues/19244
