### ISSUE TITLE
Using @eclipse-che/plugin gives error

### ISSUE THREAD

**Issue by sgraband** [eclipse-che/che#20259]
### Summary

I am trying to read out the devfile in a custom theia editor, which i want to use in a Che workspace. I am following these instuctions: https://www.eclipse.org/che/docs/che-7/contributor-guide/che-theia-plug-in-api/. If i understand it correctly this should work with the `@eclipse-che/plugin` package. However when i create a theia plugin (or vscode extension) consuming this package and use `await che.workspace.getCurrentWorkspace();` in the `activate()` function, the plugin cannot be build. I was able to workaround the build failure, but then the same error happens when the plugin is activated:
```
root ERROR [hosted-plugin: 292] Activating extension 'che-extension' failed: Error: Cannot find module '@eclipse-che/plugin'
Require stack:
- /tmp/theia-unpacked/che-extension.theia/lib/che-extension-backend.js
- /custom-theia/client/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js
- /custom-theia/client/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.module._load (/custom-theia/client/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:67:33)
    at Function.module._load (/custom-theia/client/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js:43:33)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/theia-unpacked/che-extension.theia/lib/che-extension-backend.js:45:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/theia-unpacked/che-extension.theia/lib/che-extension-backend.js',
    '/custom-theia/client/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js',
    '/custom-theia/client/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host.js'
  ]
}
```

Is there something i am missing with the `@eclipse-che/plugin` package? Is it only usable inside of Che-Theia or does it have any other constraints?
Thanks in advance.

UPDATE:
The problem above seems to not occur using the following theia plugin: https://github.com/sgraband/che-plugin-test.
However, the plugin can still not be activated due to 'che' not being define:
`Activating extension '*' failed: che is not defined`

### Relevant information

I also tried it with this code:
```
const eclipseCheExtPlugin = vscode.extensions.getExtension('@eclipse-che.ext-plugin');
if (eclipseCheExtPlugin) {
  // grab user
  const user = await eclipseCheExtPlugin.exports.user.getCurrentUser();
 vscode.window.showInformationMessage(`Eclipse Che user information: id ${user.id} with name ${user.name}`);
} else {
  vscode.window.showWarningMessage('Not running inside Eclipse Che, not displaying any user information');
}
```

But this results in `Not running inside Eclipse Che, not displaying any user information`, when running the editor in Che.

**Comment by benoitf** [comment]
`@eclipse-che.ext-plugin` is only working in che-theia where we add `@eclipse-che/plugin` (in addition to other vscode/theia namespace)

so you can't just take this plug-in without adding as well the whole che-theia plug-in ext module

**Comment by sgraband** [comment]
@benoitf Thanks for your answer! If i understand you correctly, your response is about the code in the relevant information section. 
But what about just using `@eclipse-che/plugin` like described in the summary section. Is this also only possible inside of Che-Theia? According to the [README.md](https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-plugin/README.md) it `contains Eclipse Che API available for Eclipse Theia Plugins`. So this should in theory work outside of Che-Theia?

**Comment by benoitf** [comment]
it works only in che-theia because `@eclipse-che/plugin` is just a plug-in definition and something needs to provide the binding at runtime (and this is what does the che-plugin-ext implementation that is only in che-theia

**Comment by JonasHelming** [comment]
Is there any other foreseen way to access Che (devfile and API) from within a custom Theia editor that is not Che-Theia? Is it conceptionally possible to refactor the che/plugin in a way that it can be included into custom Theia editors that are not Che-theia, e.g. by reorganizing the dependencies?

**Comment by tsmaeder** [comment]
@benoitf does it make sense to npm-publish the API, but not the implementations?

**Comment by benoitf** [comment]
> Is there any other foreseen way to access Che (devfile and API) from within a custom Theia editor that is not Che-Theia? Is it conceptionally possible to refactor the che/plugin in a way that it can be included into custom Theia editors that are not Che-theia, e.g. by reorganizing the dependencies?

we publish the API provided by che-theia, so if you want to use "che-theia programming model' you need to use che-theia.

Devfile API is accessible by che-server Rest API or through a mounted file in case of DevWorkspace. So you can access these information without CheTheia custom namespace.

**Comment by tsmaeder** [comment]
> We publish the API provided by che-theia, so if you want to use "che-theia programming model' you need to use che-theia.

But why do we publish the @eclipse-che/plugin package to npm if it can't be used by anyone outside the che-theia source tree anyway?

**Comment by benoitf** [comment]
we publish to npmjs because you can develop vscode Extensions / Theia plug-ins to be installed in CheTheia by depending only on this package, not depending on the implementation.

**Comment by sgraband** [comment]
Thanks a lot @benoitf ! This sounds exactly what we would need for the custom editor use case. I see this is on the roadmap for next month, which is great. If we can help and or test anything, please let us know anytime.

**Comment by tsmaeder** [comment]
> So it means that if a 'custom Theia' would use the implementation of our Che-Theia, it would have to stick to the same "Theia+Che version" which is a very high constraint and it's also due to the Extension Model of Theia that is mostly failing when not using the same Theia dependency.

The provision of the API as a Theia plugin namespace is tied to the underlying Theia version (and necessarily so), but nothing keeps us from making a library that can provide access to the dev workspace (from the che server or devworkspace operator) and publishing that for use of third-party editors.

Another idea would be to run a "proxy" inside the workspace that provides the API and dispatches to che server or devworkspace operator depending on the setup. It could provide a http API accessible from any language.
