### ISSUE TITLE
Che Workspaces startup should be frozen when devworkspace is enabled

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20254]
### Is your task related to a problem? Please describe.
Che Workspace and DevWorkspace can't together on the same cluster

### Describe the solution you'd like
When devworkspace enabled, Che Workspace can't be started anymore, so:
- Che Workspaces startup should be frozen when devworkspace is enabled;
- Currently, there is no visible difference on left-nav bar, workspace details or workspaces list that workspace is devworkpsace or Che Workspace, the only clue is devfile version in devfile editor. Frozen Che Workspaces should be identified somehow, maybe with special status icon;
- We should guide users to use devworkspaces instead;

**Comment by parvathyvr** [comment]
The below screens show how we could denote the deprecated Che workspaces. 
We could use the 'Alert' icon and when the user hovers,show the tool tip 'Deprecated workspace'.
![Deprecated workspace#20254](https://user-images.githubusercontent.com/33114242/130085116-e926bb45-cc00-4ec2-b3cb-6e5f7f54ffd7.png)

And when the user clicks on the workspace name and goes to the detailed page-we could show an inline alert which specifies the details and then a action link (eg: link to documentation how they can upgrade the workspace) as shown below.
![Workpace details #20254](https://user-images.githubusercontent.com/33114242/130086084-0a783853-06f7-4651-a88a-ce469215ede4.png)
PS: these are sample screens-we could work on changing the message what the inline alert show.

**Comment by ibuziuk** [comment]
@l0rd wdyt about the mockups from the previous comment? should we show the che-server-based workspaces and provide relevant docs for migration to devfile v2

**Comment by l0rd** [comment]
I am +1 for that if that's about less than a week of work. If the estimated effort required is more than that let's skip it.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by nickboldt** [comment]
Yes, end user experience is impacted by this change and should be updated accordingly.

**Comment by ibuziuk** [comment]
@l0rd my understanding is that we need to close this issue and open a new one to be aligned with the endgame plan (after migration, workspaces can be restarted without the loss of data persisted in PVs)

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/eclipse/che/issues/20845
