### ISSUE TITLE
Handle .che/che-editor.yaml setting from the dashboard (DevWorkspace)

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#20258]
### Is your task related to a problem? Please describe

With factory flow or other flows based from a given repository, dashboard is getting access to other files like .che/che-theia-plugins.yaml, .che/che-editor.yaml etc

While it give all the 'plugins' stuff to theia when the editor is theia, it does nothing when we have `.che/che-editor.yaml` or if the content is inlined in the devfile.

### Describe the solution you'd like

In that case, dashboard should use the specified content instead of using the 'default' editor

### Describe alternatives you've considered

N/A

**Comment by l0rd** [comment]
After discussion at latest dw cabal we decided to remove this issue from the scope of milestone "DevWorkspace Integration - STEP3".
