### ISSUE TITLE
Switch default branch to main (from master)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20252]
### Is your task related to a problem? Please describe.

Today, the che-docs repo uses a problematic term for its default branch. It should move to `main` like the rest of the Che projects.

 https://github.com/eclipse/che-docs (also should this move to eclipse-che org?)

Additionally, it could move to the eclipse-che organization if desired. To do so, reopen https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863#c10 and drop a comment in there. 

### Describe the solution you'd like

Instead of 
https://github.com/eclipse/che-docs/tree/master 
switch to 
https://github.com/eclipse-che/che-docs/tree/main

Then update all scripts that refer to the old repo path and branch. 

### Additional context

https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

**Comment by themr0c** [comment]
Referenced in https://issues.redhat.com/browse/RHDEVDOCS-3242
