### ISSUE TITLE
As an Admin, I want to have a granularity for the DevWorkspace startup failures exposed as a Prometheus metric

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20261]
Currently, the Che server has a single `che_workspace_failure_total` metric, which basically counts every single failure no matter what was the reason for it e.g. misconfiguration (invalid devfile), the limit of concurrent workspaces exceeded, quota, infrastructure errors e.g. networking / Kube API timeouts:

![image](https://user-images.githubusercontent.com/1461122/128373765-141006ea-0cbe-4ad7-bf3b-3d3e0ed68632.png)

it is not possible from the graph to identify what was the reason for particular failures and their ratio e.g. number of failures that happened due to invalid workspace definition. With the DevWorkspace we need to have better granularity for workspace startup failures and capture startup errors based on the reason of failure:

- misconfiguration / invalid devfile
- unrecoverable event occurred
    - FailedCreate
    - FailedMount
    - FailedScheduling
    - ReplicaSetCreateError
    - ErrImagePulling
- ~~limits e.g. not allowed to start more concurrent workspaces~~
    -  the # of concurrent workspaces should be defined and validated on the UD level, and users should not be allowed to start more workspaces
- quota 
- infrastructure issues
- other

As an additional note, Grafana dashboards for DevWorkspaces should be stored in the repository so that it would be possible to reuse them on a particular cluster

| reason | sub-reasons |
| --- | --- |
|`bad_request` | invalid devfile, insufficent [cpu\|memory\|storage] resources, image not found, container stopped immediately, unauthorized,... | 
| `infrastructure_failure` | failed scheduling, failed mounting, failed creating resource, failed pulling, response timeout... |
| `workspace_engine_failure` |  out of memory, npe, timeout... |

This classification would help us understanding where we should improve:

1. `bad_request`: help users submitting valid requests
2. `infrastructure_failure`: monitor and address infrastructure failures
3. `workspace_engine_failure`: make the controller more robust and scalable

Sub-tasks:
 - Provide a pie chart Grafana visualization for DevWorkspace failure reasons #20661
 - Provide documentation for enabling DevWorkspace monitoring (Prometheus / Grafana) #20662

**Comment by ibuziuk** [comment]
Design proposal:
- leave the counter metric name `che_workspace_failure_total` as is (this counter metric naming is currently used for Che Server)
- add a new `reason` label which will correspond to the failure e.g. `reason="quota"` / `reason=`"devfile"` / reason='infrastructure'`
- `reason` label is meant to provide granularity and it will be possible to query particular set of failures e.g. `sum(che_workspace_failure_total{reason=~"quota|devfile|limit"})`

![image](https://user-images.githubusercontent.com/1461122/132699775-f10d6d95-132b-4f86-a44f-fc6b35f6a802.png)

Concerns:
 - every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. We should find the right balance between the number of reasons and the desired granularity. e.g. from the granularity perspective, it would be great to have a reason per unrecoverable event e.g. `failed_create` / `err_Image_pulling` etc. however from the prometheus perspective it would be better to merge them all to the single `unrecoverable_event` reason. N/B the more reasons we have, the more time series will be created, the more difficult will it be to get the cardinality approval for the telemeter
 - It is not always straight-forward which failures are user-drivn and which are not. Even with the detailed granularity in some cases it will be impossible to figure out the root cause from metrics e.g. `reason="err_Image_pulling"` could happen for  a few reasons which could be both user-driven and non-user-driven
 - image registry is down
 - user defined non-existing image in the devfile


@l0rd @sleshchenko @skabashnyuk would be great to get your input. Currently, it is planned to start with the `reason="devfile"` since the DevWorkspace has already a proper validation in place

**Comment by amisevsk** [comment]
Small note (and also a comment to make sure this issue reaches the top of my notifications going forward): one thing we won't be able to track is failure due to limits (on number of concurrent workspaces) -- the DevWorkspace operator doesn't have that functionality currently and will try to start any DevWorkspace that's created. We could potentially add such a feature but I think it maybe makes more sense to enforce that restriction at the dashboard/Che level.

**Comment by ibuziuk** [comment]
@amisevsk thanks for the comment regarding the # of concurrent workspaces feature. I do agree, lets just add the validation on the UD level and disallow to start more workspaces if the limit is configured.

**Comment by l0rd** [comment]
I am +1 with this approach. 

If we want to reduce the possible reasons I think we should consider the 3 following macro-categories:

| reason | sub-reasons |
|`bad_request` | invalid devfile, insufficent [cpu|memory|storage] resources, image not found, container stopped immediately, unauthorized,... | 
| `infrastructure_failure` | failed scheduling, failed mounting, failed creating resource, failed pulling, response timeout... |
| `workspace_engine_failure` |  out of memory, npe, timeout...

This classification would help us understanding where we should improve:

1. `bad_request`: help users submitting valid requests
2. `infrastructure_failure`: monitor and address infrastructure failures
3. `workspace_engine_failure`: make the controller more robust and scalable

**Comment by mmarimuthu** [comment]
@ibuziuk @l0rd is there a clear documentation on Prometheus integration. The one in Eclipse che documentation is not complete.

Is there any sample reop to get config files.

**Comment by ibuziuk** [comment]
@mmarimuthu hello, this issue is about the new version of the workspace engine, that is not default atm
@skabashnyuk could you please point to the current documentation for Che Server Prometheus setup (I also noticed that grafana dashboards have been removed from `che-server` repo for some reason)

**Comment by ibuziuk** [comment]
@l0rd sounds good, minor correction from my initial comment, after discussion with DevContoler team it looks like we should not use `che` naming in the DevController metrics, so failures will be collected under the `devworkspace_fail_total`

**Comment by ibuziuk** [comment]
Docs PR has been merged - https://github.com/eclipse/che-docs/pull/2161
Closing
