### ISSUE TITLE
Che api calls failing with request header too large error

### ISSUE THREAD

**Issue by hthakkar1320** [eclipse-che/che#20263]
### Summary

It is observed on making che api calls like 'api/user' to get logged in user  or 'api/workspace' to get workspace which user can read fails if request size exceeds 8k with error :

![image](https://user-images.githubusercontent.com/73720876/128376470-122224c5-33a3-4b15-9573-fcd298bcb02f.png)

I have tried increasing request header buffer size in nginx ingress controller to 32k , but that is not helping as che-server  fails to handle request beyond 8k size. 
The same api calls are successful if the request header size is reduced by removing unwanted cookies using Cookie manager browser add-on.
But for my application there are large session cookies generated by IdP login, making request size more than 8k. 

Steps to reproduce  :
1. Open eclipse che Swagger UI 
2. Login with IdP configured in Keycloak that generates large number of session cookies.
3. Make any api call , session cookies are appended to the call.
4. Fails with response HTTP 400 Bad Request error , Request header size too large.
5. It can be reproduced by increasing request size more than 8k.

![image](https://user-images.githubusercontent.com/73720876/128384573-c114c8c9-bac2-4575-86c6-508d9fa7070d.png)

Error output :
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Request header is too large</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><p><b>Exception</b></p><pre>java.lang.IllegalArgumentException: Request header is too large
	org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:770)
	org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:919)
	org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:608)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:524)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base&#47;java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	java.base&#47;java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base&#47;java.lang.Thread.run(Unknown Source)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.56</h3></body></html>

Question - It looks like 8k is max request header size, so is there an Eclipse Che server setting to increase request header size more than 8k ?

**Comment by sparkoo** [comment]
I guess it's Tomcat who is blocking that. AFAIK there is currently no way how to configure that. You would have to update Connector in `server.xml` (https://github.com/eclipse-che/che-server/blob/main/assembly/assembly-che-tomcat8/src/assembly/conf/server.xml#L71) with `maxHttpHeaderSize` (https://tomcat.apache.org/tomcat-8.0-doc/config/http.html) and build your own che-server image. I haven't tested it, so I'm not 100% sure it will help.

I don''t think we would like to change the default value in upstream. Make it configurable will be tricky, you may propose PR.

**Comment by hthakkar1320** [comment]
@sparkoo  Thank you for your quick response,  As per your suggestion, Trying out changes to update Tomcat server to increase maxHttpHeaderSize.
