### ISSUE TITLE
Problem getting local build of che-theia running on 7.34.1

### ISSUE THREAD

**Issue by gregj0** [eclipse-che/che#20279]
### Summary

I am unable to build the 7.34.1 tag of che-theia and then run it locally successfully.  We have an extension we build currently build into 7.20.1 and am looking to upgrade.  Even without adding in our extension into it, it is failing.  Is it an issue or my process (no references to it elsewhere so wondering if just me)?

More details in relevant info

### Relevant information

In the end it is showing no useful information in the workspace pod in the theia-xxxx logs.  Nothing after 
```root INFO Deploy plugins list took```

The browser never gets to the spinner of theia loading and shows in the console issues loading monaco

```loader.js:1 Uncaught TypeError: Cannot read property 'instance' of undefined
    at loader.js:1
(anonymous) @ loader.js:1
index.js:101 Failed to start the frontend application.
(anonymous) @ index.js:101
Promise.catch (async)
44651 @ index.js:100
n @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js:2
index.js:103 TypeError: e is not a function
    at monaco-loader.ts:45
    at new Promise (<anonymous>)
    at Object.t.loadMonaco (monaco-loader.ts:44)
    at monaco-browser-module.ts:23
(anonymous) @ index.js:103
Promise.catch (async)
44651 @ index.js:100
n @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js:2
```

Here is what how I am building.

Using node 12.22.4 and npm 6.14.14

Clone https://github.com/eclipse-che/che-theia and checkout the 7.34.1 tag

Run these with a valid GITHUB_TOKEN from the root directory of the repo

```
export GITHUB_TOKEN=<mygithub-token>
export CDN_PREFIX=https://static.developers.redhat.com/che/theia_artifacts/ 
export MONACO_CDN_PREFIX=https://cdn.jsdelivr.net/npm/

SKIP_TEST=true SKIP_LINT=true SKIP_FORMAT=true GITHUB_TOKEN=${GITHUB_TOKEN}  CDN_PREFIX=${CDN_PREFIX} MONACO_CDN_PREFIX=${MONACO_CDN_PREFIX} ./build.sh --dockerfile:Dockerfile.alpine --skip-tests
```

I get the same results if I just run this (from the github actions used to build there)in the repo
```
./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
```

I tag and push these 2 images created and pushing to my quay.io, ignoring
che-theia-vsix-installer:latest

Tag and push to my quay.io 
```
docker tag eclipse/che-theia:latest quay.io/gregj0/che-theia:7.34.1
docker push quay.io/gregj0/che-theia:7.34.1

docker tag eclipse/che-theia-endpoint-runtime-binary:latest quay.io/gregj0/che-theia-endpoint-runtime-binary:7.34.1
docker push quay.io/gregj0/cche-theia-endpoint-runtime-binary:7.34.1
```

Locally install 7.34.1 with
```
chectl server:deploy -n eclipse-che -p docker-desktop --installer operator -v=7.34.1
```

Open a terminal on the plugin-registry pod and edit 
/var/www/html/v3/plugins/eclipse/che-theia/latest/meta.yaml

Replace the image referenced to che-theia in following to point to my quay.io image using the 7.34.1 tag
containers:
  - image

Replace the image referenced to che-theia-endpoint-runtime-binary to point to my quay.io.image using the 7.34.1 tag
initContainers
  - image

Logged on to my local deployment of eclipse-che through browser and created a basic workspace (custom with no additions).

This process works in older 7.20.x branch but not here.  I have tried it on the 7.34.1 tag and the 7.34.x branch (which I think are the same right now)

**Comment by benoitf** [comment]
@gregj0 we're building che-theia from 7.34.x branch on PR checks and it's building (also 7.34.2 was cut today)

do you reproduce the issue with the image that we're producing like  

https://quay.io/repository/eclipse/che-theia?tab=tags

`quay.io/eclipse/che-theia:7.34.2` ?
to know if the issue is from the build environment or the runtime/client ?

**Comment by gregj0** [comment]
No issues when I use 
quay.io/eclipse/che-theia:7.34.1
or now
quay.io/eclipse/che-theia:7.34.2

It was only when running from my own build of 7.34.x a few days back so maybe not with the last 7.34.2 additions or 7.34.1.  I'll let you know with 7.34.2 when I finish a build with that tag.

**Comment by gregj0** [comment]
And I did a rebuild with the code in the 7.32.2 tag and still have the same error in the console with it failing to loading the workspace

![image](https://user-images.githubusercontent.com/23464162/129247458-d47848ce-7535-40bd-aa64-061830c4486a.png)

**Comment by gregj0** [comment]
I was able to get it to work.  I think it was an issue with the either the GITHUB_TOKEN or the permissions granted to it that was used on the build.
