### ISSUE TITLE
Docs: Single-host vs multihost confusion in the docs

### ISSUE THREAD

**Issue by max-cx** [eclipse-che/che#20286]
https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspace-exposure-strategies/#_devfile_endpoints_multi_host

devfile endpoints: **multi-host**

CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE: '**multi-host**'

This **single-host** configuration exposes the endpoints on subdomains, for example: http://serverihzmuqqc-go-cli-server-8080.<che-host>. These endpoints are exposed on an unsecured HTTP port. A dedicated Ingress or Route is used for such endpoints, even with gateway single-host setup.

This configuration limits the usability of previews shown directly in the editor page when Che is configured with TLS. Since https pages allow communication only with secured endpoints, users must open their application previews in another browser tab.

**Comment by skabashnyuk** [comment]
There is nothing we can do here from server POV. UI/UX has to be adapted to this behavior.

**Comment by themr0c** [comment]
referenced in https://issues.redhat.com/browse/RHDEVDOCS-3225
