### ISSUE TITLE
Drop single user support

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20295]
### Is your task related to a problem? Please describe

Single User support has no benefit comparing to Multi-User support, except less memory consumption, which is not critical.

### Describe the solution you'd like

And since we don't test it in any way, the proposal is to fully drop that from everywhere.

Items I can name and separate issues that needs to be created:
- deprecating/dropping --multiuser flag on chectl;
- review documentation not to reference single user mode;
- drop the logic on Che Operator side that respects `.spec.server.customCheProperties.CHE_MULTIUSER`;
- probably drop respecting CHE_MULTIUSER env var on Che Server; https://github.com/eclipse/che/issues/20314
- ... please add anything I might miss.

**Comment by tolusha** [comment]
@skabashnyuk 
What about existed instances running on single-user?

**Comment by skabashnyuk** [comment]
>@skabashnyuk
>What about existed instances running on single-user?

They will have to migrate to a multi-user or stay with the old version.

**Comment by tolusha** [comment]
I mean they will be automatically migrated to multi-user version if they deploy a new version of Eclipse Che.
Is it ok?

**Comment by skabashnyuk** [comment]
>I mean they will be automatically migrated to multi-user version if they deploy a new version of Eclipse Che.

no automatic or manual migration is going to be provided.
