### ISSUE TITLE
[devworkspace-che-operator] should generate networking.k8s.io/v1 version of Ingress

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20298]
### Is your task related to a problem? Please describe

Ingress v1beta1 is deprecated from 1.19 and is going to be dropped in the next major release.
 `networking.k8s.io/v1`   is available since 1.19 which is the oldest maintainable version of Kubernetes 
See more https://kubernetes.io/releases/

### Describe the solution you'd like

devworkspace-che-operator should generate  `networking.k8s.io/v1` version of Ingress

### Describe alternatives you've considered

Che server should generate  `networking.k8s.io/v1` version of Ingress

### Additional context

https://github.com/eclipse-che/che-operator/blob/main/controllers/devworkspace/solver/endpoint_exposer.go#L174-L205
https://github.com/eclipse/che/issues/20019

**Comment by metlos** [comment]
This depends on https://github.com/eclipse/che/issues/20300 and https://github.com/devfile/devworkspace-operator/pull/540 because we're using DWO infrastructure code for handling ingresses.

**Comment by skabashnyuk** [comment]
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23691
- [ ]  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23690
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23687
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23684

**Comment by skabashnyuk** [comment]
license check complete
