### ISSUE TITLE
Move examples to use Java17 which is the upcoming LTS

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#20294]
### Is your enhancement related to a problem? Please describe

We have lot of examples using Java11 but Java17 is becoming the new LTS you we should check/ensure our plug-ins work with this version and probably update the devfiles to use Java17

### Describe the solution you'd like

Add Java17 sidecar and switch most of the examples to this new LTS

**Comment by sunix** [comment]
related to https://github.com/eclipse/che/issues/16765
