### ISSUE TITLE
Mounting user's home folder in Che

### ISSUE THREAD

**Issue by Hoeze** [eclipse-che/che#20292]
### Summary

How would one configure Che to mount the user's home folder (+ other folders eventually) inside the container?
We need to have direct access to the shared home folders on our system.

### Relevant information

Our cluster is a traditional HPC stack (FreeIPA for accounting, SLURM as job scheduler, CephFS/NFS for shared directories) running CentOS8.
We can use podman-based technologies though.

**Comment by ibuziuk** [comment]
Hello, please find the relevant documentation for mounting volumes in the devfiles - https://www.eclipse.org/che/docs/che-7/end-user-guide/authoring-devfiles-version-1/#_persistent_storage

**Comment by Hoeze** [comment]
Hi @ibuziuk, thanks a lot for your answer.
I checked the docs that you linked but as far as I understand they do not really answer my question.

The docs state that I can mount persistent volumes in the Che containers.
But how does this work with home folders that are mounted on the container host?
E.g. when I am working in a container as UID 0, this gets mapped to UID 10000 on the host.
This means even when I mount the host directory to the container, the user and group IDs will be wrong.

How does Che solve this issue?

**Comment by ibuziuk** [comment]
oh, ok I do not think we support this kind of setup on a devfile level
@benoitf maybe you can comment on that?
