### ISSUE TITLE
failed to deploy Che using minikube ->   ✖ Verify if kubectl is installed       → E_REQUISITE_NOT_FOUND

### ISSUE THREAD

**Issue by debimishra89** [eclipse-che/che#20297]
I want to use Che on my centos VM. I have followed the steps mentioned in Che installation document. but Che fails to deploy.
please find below the steps I followed

1.Installed kubectl 
![image](https://user-images.githubusercontent.com/84674037/129481752-3d2420c5-efd9-4100-80e0-8a6ca942c8c6.png)

2.installed minikube
![image](https://user-images.githubusercontent.com/84674037/129481778-241c8997-f193-4638-ba4f-3e10581d3f5f.png)

3. minikube start --addons=ingress --vm=true --memory=8192 --driver=none
4. Installed chectl
![image](https://user-images.githubusercontent.com/84674037/129481843-5bd8d790-493e-4bd8-aa76-a24c41675192.png)

5. chectl server:deploy --platform minikube (FAILED)
![image](https://user-images.githubusercontent.com/84674037/129481865-e4294d7b-7365-46de-9853-33902e8f3420.png)

FYI ,kubectl is running
![image](https://user-images.githubusercontent.com/84674037/129481995-f3f24d9f-e644-4c6e-ac74-fe241349be5b.png)

**Comment by tolusha** [comment]
Everything looks correctly. 
But I am wondering why everything is run under sudo? That's maybe a culprit.
We don't do any magic, we just check if command exists [1].
 
1. Is `kubectl` under `$PATH` or it is just copied into a current directory (if so, then `chectl` won't find it) ?
2. Could you try without sudo ?
 
[1] https://github.com/che-incubator/chectl/blob/main/src/tasks/platforms/minikube.ts#L33-L35 
[2] https://github.com/che-incubator/chectl

**Comment by debimishra89** [comment]
> 1. $PATH

1. kubectl is under $PATH
2. I am trying the 2nd suggestion

**Comment by debimishra89** [comment]
Do you have any docker image for Che.
FYI, https://hub.docker.com/r/eclipse/che/ is not working

**Comment by tolusha** [comment]
Could you try `which kubectl` on behalf of `debi` user ?

**Comment by debimishra89** [comment]
> Could you try `which kubectl` on behalf of `debi` user ?

![image](https://user-images.githubusercontent.com/84674037/129670690-cf539797-6d7a-4682-9d86-8d575a2420cc.png)

**Comment by tolusha** [comment]
Maybe related to this
https://github.com/eclipse/che/issues/16457

**Comment by debimishra89** [comment]
> Maybe related to this
> #16457
I have not used any alias
![image](https://user-images.githubusercontent.com/84674037/129698500-073db921-0ede-4612-8ba5-4bfe451d5cbe.png)

**Comment by tjhood97** [comment]
Bumping because I am having the exact same problem. I initially had the command `kubectl` as an alias for `minikube kubectl -- ` per issue #16457, but even when I removed it, the error persists.

Running on Ubuntu 20.04.2 LTS. I get the same exact output as Debi above, but I am happy to include screenshots if need be.

**Comment by benoitf** [comment]
hello, I've extracted the code that is checking for kubectl, it's using command-exists npm library

Could you try to execute the command
```
$ npx https://github.com/benoitf/kubectl-exists
```

source code is there: https://github.com/benoitf/kubectl-exists/blob/main/index.js

**Comment by tjhood97** [comment]
Hi,

Thank you for your response! I have run the command, and this is the output:

![image](https://user-images.githubusercontent.com/22802388/129896165-ae2a16bb-413d-49dd-b9bc-99eae3c5cf5e.png)

Right below it is a quick `which kubectl` I ran just to verify that kubectl exists in PATH. `chectl` still fails in the same way as before.

Could it be some bug on the npm side? I've never worked with npm, so I don't have an idea how it works.

**Comment by benoitf** [comment]
@tjhood97 could you say how you installed kubectl ?
I'm trying to reproduce the issue inside a Docker container

**Comment by benoitf** [comment]
@tjhood97 also if you can launch again the command 

```
$ npx https://github.com/benoitf/kubectl-exists
```

I've added more traces

**Comment by debimishra89** [comment]
> @tjhood97 could you say how you installed kubectl ?
> I'm trying to reproduce the issue inside a Docker container

I have used below steps to install kubectl and minikube

1. mkdir kube
2. cd kube
3. curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
4. curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
5. curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
6.  sudo install minikube-linux-amd64 /usr/local/bin/minikube
7.  minikube kubectl -- get po -A

FYI, I am using centos7 VM

**Comment by benoitf** [comment]
@debimishra89 could you run the command
```
$ npx https://github.com/benoitf/kubectl-exists
```
?

Also here your kubectl command is not executable, you didn't do like `chmod u+x kubectl`

**Comment by debimishra89** [comment]
> @debimishra89 could you run the command
> 
> ```
> $ npx https://github.com/benoitf/kubectl-exists
> ```
> 
> ?
> 
> Also here your kubectl command is not executable, you didn't do like `chmod u+x kubectl`

You are right. that was the reason.
before chmod command
![image](https://user-images.githubusercontent.com/84674037/129918275-b90d6869-6743-40e2-ac93-b2058cbe4c01.png)


after chmod command
![image](https://user-images.githubusercontent.com/84674037/129918339-a5326756-4e2e-4e29-9392-8f1c98f17d99.png)


thanks a lot. let me try chectl deploy now

**Comment by debimishra89** [comment]
Now its failing at minikube start step. Do I need to downgrade minikube version?
![image](https://user-images.githubusercontent.com/84674037/129919701-164bc8e7-c013-4205-8d9f-39e2f6498d60.png)

**Comment by benoitf** [comment]
you should start minikube before running chectl

**Comment by debimishra89** [comment]
> you should start minikube before running chectl

minikube is already running. Let me delete and start again.

**Comment by debimishra89** [comment]
now its failing at post installation check. Error is not clear at all.
![image](https://user-images.githubusercontent.com/84674037/129930394-0e71daef-fabd-4dce-a4ad-7c1f5e24f6a7.png)

![image](https://user-images.githubusercontent.com/84674037/129930584-111e1585-afcc-4fac-9d24-6b8a26d921eb.png)

**Comment by tjhood97** [comment]
`chmod u+x /usr/local/bin/kubectl` did the trick! Thanks so much!

![image](https://user-images.githubusercontent.com/22802388/129930869-d8c17995-646c-4416-bb59-b8050baef78a.png)

I am not sure how common this issue might be, but it might be useful to mention this step somewhere in the chectl installation docs.

**Comment by debimishra89** [comment]
> `chmod u+x /usr/local/bin/kubectl` did the trick! Thanks so much!
> 
> ![image](https://user-images.githubusercontent.com/22802388/129930869-d8c17995-646c-4416-bb59-b8050baef78a.png)
> 
> I am not sure how common this issue might be, but it might be useful to mention this step somewhere in the chectl installation docs.

have you successfully deployed CHE . Mine is failing at post installation checklist

**Comment by tjhood97** [comment]
@debimishra89 Mine completed the post-installation checklist just fine. It looks like it fully deployed, although now I am having some trouble getting Mozilla to register the right certificates. I will look at it more when I have time.

What does the error log from your post-installation checklist say?

**Comment by debimishra89** [comment]
I am not able to proceed beyond this step

[23:50:15] ✅  Post installation checklis [failed]
 [23:50:15] → Timeout: there are no pods in the namespace: eclipse-che, selector: app=che,component=postgres. Check Eclipse Che logs for details. Consider increasing error recheck timeout with --k8spoderrorrechecktimeut flag.

**Comment by tolusha** [comment]
@debimishra89 
Could attach logs getting from `chectl server:logs` command ?

**Comment by debimishra89** [comment]
> @debimishra89
> Could attach logs getting from `chectl server:logs` command ?

let me tell you what issues I am facing repeatedly when i execute "chectl server:deploy --platform minikube"

1. first error I am getting at PostgreSQL pod bootstrap
![image](https://user-images.githubusercontent.com/84674037/130009857-21f978af-fcfa-4741-9b72-e8af127e95ff.png)

2. when I try to execute the che:deploy command 2nd time its throwing below error
![image](https://user-images.githubusercontent.com/84674037/130009965-f46ebe95-6a41-4d0a-8d02-09cd50ddcbfb.png)

error log
![image](https://user-images.githubusercontent.com/84674037/130010035-792baa05-cf9d-4ec4-bf6b-ba685d6d2ff9.png)

**Comment by benoitf** [comment]
I think that timeout related issues may come from a low bandwidth to setup che (pull all images)

try to perform
```
$ chectl server:delete
```

then restart the `server:deploy` command (but do not delete minikube as it'll remove the OCI images and then you'll face the same issues)

**Comment by debimishra89** [comment]
> I think that timeout related issues may come from a low bandwidth to setup che (pull all images)
> 
> try to perform
> 
> ```
> $ chectl server:delete
> ```
> 
> then restart the `server:deploy` command (but do not delete minikube as it'll remove the OCI images and then you'll face the same issues)

but sadly chectl server:deploy is not recognizing minikube cluster after the second failure I mentioned above. I have to delete minikube and start again.

**Comment by debimishra89** [comment]
@benoitf , I don't know why CHECTL is not recognizing minikube cluster when deployment fails after the 2nd error mentioned below.

❯ ✅ Post installation checklist
❯ Eclipse Che Server pod bootstrap
✖ Scheduling
→ Timeout: there are no pods in the namespace: eclipse-che, selector: app=che,component=che. Check Eclipse Che logs for details. Consider increasing

**Comment by tolusha** [comment]
@debimishra89 
deployment failed.
To get details `chectl server:logs`

**Comment by debimishra89** [comment]
> chectl server:logs

ERROR-1
![image](https://user-images.githubusercontent.com/84674037/130322652-2b69abb7-e10e-42b2-a9ba-b2d453923875.png)

Logs from chectl server:logs
![image](https://user-images.githubusercontent.com/84674037/130322692-6d1fdd57-4ef6-4094-aead-58f01024e61f.png)

Logs from che-postgres (/tmp/chectl-logs/1629550719934/eclipse-che/postgres-64c78c79fb-8ffrq)
![image](https://user-images.githubusercontent.com/84674037/130322720-a4f931b8-34a6-47bc-bfa9-892c35413fc7.png)

**Comment by tolusha** [comment]
`kubectl get events -n eclipse-che` ?

**Comment by debimishra89** [comment]
> `kubectl get events -n eclipse-che` ?

![image](https://user-images.githubusercontent.com/84674037/130431323-53b1d630-5359-4c1a-a97a-d5da0f8aa6a0.png)

**Comment by debimishra89** [comment]
![image](https://user-images.githubusercontent.com/84674037/130432096-d2f82738-8b49-44f0-a5ec-2fb9e6fb2dbe.png)

**Comment by debimishra89** [comment]
hello, any luck. I am running out of time as I am going to propose this IDE to my client

**Comment by tolusha** [comment]
Unfortunately I am out of ideas.
Maybe you can try minikube 1.21.1 ?

**Comment by debimishra89** [comment]
resolved the postgres crashpod issue by setting "vm.nr_hugepages=0" in sysctl.conf file

**Comment by tolusha** [comment]
@debimishra89 
Cool. Thank you for letting us know.

**Comment by rbbl-dev** [comment]
unreal.
i've seen that its just node project so i cloned it.

running directly from source works on `main` and `7.45.0` :thinking:

**Comment by rbbl-dev** [comment]
i know this sound really off but i double checked.
i use gnome-terminal as terminal emulator.

when having gnome terminal open and running chectl straight from source (in the intellij terminal) then the regular chectl works in all gnome-terminal tabs except the first.
chectl does not work in a second gnome-terminal window, when i launch that afterwards.

maybe this helps narrowing it down

**Comment by rbbl-dev** [comment]
i knew it sounded way to outlandish. i just connected the dots wrong :facepalm: 

i swear i'm losing it :D

so chectl works anywhere except "in" `~` :laughing: 

![image](https://user-images.githubusercontent.com/78143613/160448090-02ec325a-d555-49da-9a8d-ff03eb34fd7e.png)

**Comment by rbbl-dev** [comment]
holy fuck.
so from the kubectl setup i still had the `kubectl` in my home folder. thats why it gave a false negative in that directory.

probably directly relates to https://github.com/mathisonian/command-exists/issues/35

**Comment by kedare** [comment]
I confirm, from $HOME, I get the same error, moving to `/` make it work
