### ISSUE TITLE
Why use cdt-vscode instead of cpptool ?

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#20305]
### Summary

I find a relation issue abount support C/C++ https://github.com/eclipse/che/issues/13698#issuecomment-515403416
I don't know why use cdt-vscode but not [cpptool](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)
And I can't find cdt-vscode in  [open-vsx](https://open-vsx.org/?search=cdt&category=&sortBy=relevance&sortOrder=desc)

**Comment by skabashnyuk** [comment]
@svor any ideas?

**Comment by svor** [comment]
@zWingz as far as I remember the reason why we don't use cpptool is the license problem. It can be used only under VS Code IDE

**Comment by zWingz** [comment]
@svor Thanks
https://github.com/microsoft/vscode-cpptools/blob/main/RuntimeLicenses/cpptools-srv-LICENSE.txt#L18
