### ISSUE TITLE
Upgrade che-operator to controller-runtime 0.9.5

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#20300]
### Is your enhancement related to a problem? Please describe

Currently, `che-operator` depends on `sigs.k8s.io/controller-runtime v0.6.3`. Because DWO is in the process of migrating to controller runtime 0.9.5 (https://github.com/devfile/devworkspace-operator/pull/540) and DWO is a dependency of `che-operator`, we should also consider upgrading from the old version of the controller runtime currently in use.

### Describe the solution you'd like

Use the same version of `sigs.k8s.io/controller-runtime` in both `che-operator` and DWO.

### Describe alternatives you've considered

Keep an increasingly complex list of version replacements and pray everything somehow still works together.

**Comment by tolusha** [comment]
We run our PR checks on minishift, so I assume it is compatible.
