### ISSUE TITLE
Drop single user support on Che Server

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20314]
### Is your task related to a problem? Please describe

Drop single user support on Che Server

### Describe the solution you'd like

- Remove single-user alternative https://github.com/eclipse-che/che-server/blob/main/assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java#L324-L359
- Remove sungle-user only classes, components, modules
- remove h2 db driver from packaging.

### Additional context

- https://github.com/eclipse/che/issues/20295

### Release Notes Text

The single user (unsecured) configuration of Che is not supported anymore. Che is a multi-tenant development workspace manager and there was no value to support a single user configuration. From now on, for single user scenarios users should consider deploying the DevWorkspace Operator without Che.

**Comment by l0rd** [comment]
@skabashnyuk can we close this issue? And when we close it can we label it "status/release-notes-review-needed"?

**Comment by sparkoo** [comment]
There's still PR open https://github.com/eclipse-che/che-server/pull/89
