### ISSUE TITLE
Is not possible to access Che Dashboard route on OpenShift

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#20318]
### Describe the bug

Dashboard Route in Openshift 4.8 throw 404 when try to access.

### Che version

7.34@latest

### Steps to reproduce

1. Install Che 7.34.2 from Operator Hub
2. Access the che-dashboard route and will get the 404 described bellow

### Expected behavior

`/` is missing from route: https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/dashboard/dashboard.go#L40

### Runtime

OpenShift

### Screenshots

![image (1)](https://user-images.githubusercontent.com/59865209/129741641-bad5a681-be16-45d6-b31b-a1b6aea850b7.png)

### Installation method

other (please specify in additional context)

### Environment

Linux

### Additional context

Instaling from Operator Hub UI

**Comment by samdotci** [comment]
Not sure if it's best to respond here or open another issue, but it seems like this fix has broken my deployment of Eclipse Che on K3s when using the operator.

It deploys perfectly when using Helm as this doesn't produce a dashboard ingress with a trailing slash, but the operator results in a 404 when trying to access the dashboard. It seems like all of the ingresses are fully identical between my Helm and Operator setup, with the exception of the slash.

Pretty sure it isn't any other issues in my setup as I've fully deleted my cluster and started again about 10 times, and every other service works such as keycloak, the plugin registry, etc.

The below is the ingress definition as defined by the operator which results in a 404:
```yaml
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      che.eclipse.org/managed-annotations-digest: NpIhR7gmyYZJ3KW2WvSw4lBBh-vqSAsF5n83BvCrMeE=
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    creationTimestamp: "2021-09-10T15:43:16Z"
    generation: 1
    labels:
      app.kubernetes.io/component: che-dashboard
      app.kubernetes.io/instance: che
      app.kubernetes.io/managed-by: che-operator
      app.kubernetes.io/name: che
    name: che-dashboard
    namespace: che
    ownerReferences:
    - apiVersion: org.eclipse.che/v1
      blockOwnerDeletion: true
      controller: true
      kind: CheCluster
      name: eclipse-che
      uid: bddfb406-80e8-435c-8144-b5eedc6f43a4
    resourceVersion: "1234"
    uid: 2331dedf-b6f7-4dd4-a35b-5ac61bc6c765
  spec:
    rules:
    - host: che-che.removed.domain.com
      http:
        paths:
        - backend:
            service:
              name: che-dashboard
              port:
                number: 8080
          path: /dashboard/
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - che-che.removed.domain.com
      secretName: che-tls
  status:
    loadBalancer:
      ingress:
      - ip: 172.16.21.2
```

The ingress as defined by the Helm chart:
```yaml
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      meta.helm.sh/release-name: che
      meta.helm.sh/release-namespace: che
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    creationTimestamp: "2021-09-10T16:02:22Z"
    generation: 1
    labels:
      app: che
      app.kubernetes.io/managed-by: Helm
      component: che-dashboard
    name: che-dashboard-ingress
    namespace: che
    resourceVersion: "1108"
    uid: 00815a87-85f4-4268-bbdc-706d63432f03
  spec:
    rules:
    - host: che-che.removed.domain.com
      http:
        paths:
        - backend:
            service:
              name: che-dashboard
              port:
                number: 8080
          path: /dashboard
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - che-che.removed.domain.com
      secretName: che-tls
  status:
    loadBalancer:
      ingress:
      - ip: 172.16.22.2
```
