### ISSUE TITLE
Provide IntelliJ IDEA and PyCharm as a Che Editor on DevSandbox

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#20313]
### Is your task related to a problem? Please describe

There is a need to provide contribution to the che-plugin-registry and che-devfile-registry by adding definitions for the IntelliJ IDEA and PyCharm to allow community to use the following stacks instead of default Che-Theia editor.

### Describe the solution you'd like

Update che-plugin-registry and che-devfile-registry by adding plugin meta configuration and particular devfile for the both type of editors.

**Comment by vzhukovs** [comment]
Won't be implemented as it available now by using factory with `che-editor` query parameter.

**Comment by azatsarynnyy** [comment]
More details are in the docs https://www.eclipse.org/che/docs/stable/end-user-guide/selecting-an-ide/
