### ISSUE TITLE
Che Operator 7.35.0 release is broken

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#20336]
### Describe the bug

Che Operator release workflow completes with broken pull requests, that do not contain OLM files, like this one https://github.com/eclipse-che/che-operator/pull/1021/files

### Che version

next (development version)

### Steps to reproduce

1. Launch "Che Operator Release" workflow

### Expected behavior

OLM files should be created and included into release PR

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

Issue is about running release workflow on GitHub actions infrastructure

**Comment by mmorhun** [comment]
Fixed

**Comment by tolusha** [comment]
Thank you! That was my fault.
