### ISSUE TITLE
Build che-theia the same way in image build as in dev build

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#20330]
### Is your enhancement related to a problem? Please describe

Currently, the way we build che-theia is very different from when we build che-theia in development. The normal way of building che-theia in development is (in a quay.io/eclipse/che-theia-dev:next container):

1. git checkout github.com/eclipse-theia/theia
2. cd theia
2. che-theia init
3. yarn
4. cd che/che-theia/plugins
5. ./foreach_yarn

if we look at https://github.com/eclipse-che/che-theia/blob/main/dockerfiles/theia/Dockerfile#L59, there is much more going on. This makes it hard to keep the two build processes in sync and to debug build failures that do no occur during development.

### Describe the solution you'd like

I would the development build and image build processes to be as similar as possible. If changes in the source tree are necessary (like in the linked dockerfile from line 59 on), they should also be present in the development time build. The logical place would be `che-theia init,` in this case.

### Additional context

Using the linkless build (https://github.com/eclipse/che/issues/16852) process would simplify the process by removing some of the manipulations neccessary in `che-theia init`.

**Comment by tolusha** [comment]
@tsmaeder 
feel free to update priority
