### ISSUE TITLE
machine-exec: Provides API to list all available containers

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#20338]
### Is your enhancement related to a problem? Please describe

Today, the machine-exec component expects that client provides information like

```
identifier: {
   machineName,
   workspaceId,
}
```

in order to open a connection to a given container.

But from the client POV, if we want to list available choices, it would be great if `machine-exec` could provide the list of available identifiers

### Describe the solution you'd like

Add a new RPC commands on the endpoint to provide the list of available identifiers by the current machine-exec endpoint.

machine-exec component is aware if it's running as part of a che server workspaces or a DevWorkspace so it has all the logic to search available containers and for which workspaceId we can connect to.

Today there is `create`, `check` and `resize` so we could have another method to grab the identifiers.

So a client would not have to know the workspace ID or how to grab containers from a current pod.

### Describe alternatives you've considered

N/A

### Additional context

It would be nice as well to return if the connection to the container will be possible or not.
For example a `FROM scratch` container won't allow connecting so client should not display it (or should be aware that it may not work)

**Comment by JPinkney** [comment]
@benoitf I've marked this issue as severity/p2. Feel free to upgrade to severity/p1 if its a bigger issue
