### ISSUE TITLE
We need reimplement auto login for swagger operations

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#20334]
## Referenced issues:
https://github.com/eclipse/che/issues/19585
https://github.com/eclipse-che/che-server/pull/80

### Is your task related to a problem? Please describe

During working on keycloak update task I see, that swagger keycloak auto login feature doesn't work with newer keycloak(newer keycloak has slower refresh token operation and it affects swagger). Also I see it no make sense try to fix it, because, we have pull request to update swagger: https://github.com/eclipse-che/che-server/pull/80 and this feature any way should be reimplemented for new swagger.

### Describe the solution you'd like

It would be nice to reimplement swagger keycloak auto login feature, initially created by https://github.com/eclipse/che-lib/commit/46feab12ffe673784e2a499e9ba30a68bf3dadbc#diff-da597f452e757bc197e4cf109f11889657a55bb9e12513ac8c57949ea7ff3206

**Comment by skabashnyuk** [comment]
Works for me devworkspace mode.
