### ISSUE TITLE
Continuous  logging of connection is closed in the browser console after network reconnect

### ISSUE THREAD

**Issue by skandasa** [eclipse-che/che#20339]
### Summary

We are uisng che-theia inside the che environment. Whenever network connection is broken and reconnected. The application recovers and works normally, However in the console of the browser continuous logging Error: connection is closed error is happning until we refresh/reload the whole browser. The erros are logged by Telemetray server. We are unable to disable the telemtery service . Please suggest a way to overcome this issue 

rpc-protocol.ts:71 Uncaught (in promise) Error: connection is closed
    at Object.e.create (rpc-protocol.ts:71)
    at e.remoteCall (rpc-protocol.ts:162)
    at Proxy.n.<computed>.r.charCodeAt.n.<computed> (rpc-protocol.ts:152)
    at che-telemetry-main.ts:35
    at event.ts:117
    at e.invoke (event.ts:125)
    at e.fire (event.ts:267)
    at Object.<anonymous> (event.ts:329)
    at bundle.js:2
    at Object.next (bundle.js:2)

### Relevant information

![image](https://user-images.githubusercontent.com/7127323/130204602-85e38a93-ae94-4406-8040-57c900562992.png)

**Comment by skabashnyuk** [comment]
Possible related to https://github.com/eclipse/che/issues/19796
