### ISSUE TITLE
Completion applying :: sample-plugin-json

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#2034]
There is the function in the SimpleCompletion.java for applying proposal (from https://github.com/eclipse/che/blob/master/samples/sample-plugin-json/che-sample-plugin-json-ide/src/main/java/org/eclipse/che/plugin/jsonexample/ide/editor/SimpleCompletion.java):

```
document.replace(
                document.getCursorOffset(),
                proposal.length(),
                proposal);
```

Are your sure that it's all right here? When I try to apply selected proposal, text is changed in some weird way. 
If it's expected behavior, so how to implement proposals with normal behavior?

**Comment by ghost** [comment]
@zatsepinvl can you illustrate it with an example (a screenshot)?

**Comment by zatsepinvl** [comment]
Ok. The context is another from json plugin, but the applying code of the completion is absolutely the same.
First of all I have the clean document and my proposlas:
![1](https://cloud.githubusercontent.com/assets/11683340/17392383/b706ab16-5a25-11e6-98a9-c313096fc6be.png)

Then I push "Enter" and apply it. It's OK:
![2](https://cloud.githubusercontent.com/assets/11683340/17392471/465a957a-5a26-11e6-803f-fc7afda92e25.png)

Then I type ": some_value " and open proposals, **but some another bug here: semantic highlighting doesn't work here, however it works after the document reopening.** 
![3](https://cloud.githubusercontent.com/assets/11683340/17392504/8540eb0e-5a26-11e6-8df3-7cef14bb92db.png)

And after applying the "metadata" proposal I have this one:
![4](https://cloud.githubusercontent.com/assets/11683340/17392540/b73ba43c-5a26-11e6-9fb0-0b0b142f60ad.png)

(I've got the same effect using sample-plugin-json)

**Comment by ghost** [comment]
@edgarmueller can you please comment?

**Comment by edgarmueller** [comment]
@eivantsov @zatsepinvl No, I guess it's not the expected behaviour as I also pointed out in my [initial PR](https://github.com/eclipse/che/pull/1349#issue-156552702), but I didn't have the time to further investigate. Actually, I'd also be interested in how-to set-up completion with a static list of custom keywords properly since I only came up with this by digging through the Java plugin.

**Comment by zatsepinvl** [comment]
Any results?

**Comment by TylerJewell** [comment]
@vparfonov - can you revisit this issue.  is it still actual?  It's clearly not a blocker as it does not cause data corruption.
