### ISSUE TITLE
Tab styling on operations perspective

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#2035]
![selection_015](https://cloud.githubusercontent.com/assets/5712744/17371930/7c21fe72-59aa-11e6-8b07-a66656d929ae.png)

There are white lines on the top and the bottom of selected tab (see screenshot), they must be removed.

**Reproduction Steps:**
Launch workspace in IDE, go to operations perspective.

**Che version:**
4.7.0-SNAPSHOT

**Comment by TylerJewell** [comment]
We should remove operations view in IDE once we have stack editing in UD.
