### ISSUE TITLE
[Whitelabel/branding] Support using alternate container for vsix-installer; use released versions 

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20368]
### Describe the bug

As of 7.35, che-theia hardcodes the URL for the vsix-installer as **[quay.io/eclipse/che-theia-vsix-installer:next](https://quay.io/repository/eclipse/che-theia-vsix-installer?tag=next&tab=tags)**.

This is neither updated in the 7.35.x branch to point to a stable release like 7.35.0, nor is it exposed to the downstream productization process as a parameter that can easily be replaced by a different, more stable, product image.

### Che version

next (development version)

### Steps to reproduce

1. Open this file https://github.com/eclipse-che/che-theia/blob/7.35.x/tools/devworkspace-handler/src/vsix-installer/vsix-installer-component-updater.ts#L33
2. see line 33

### Expected behavior

There should be a better way to change this value from a hardcoded :next build to a stable one

Che release process should replace :next with a real released version. 

Downstream builds should have a way to whitelabel/rebrand/replace this image. 

### Runtime

Kubernetes (vanilla), OpenShift

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by azatsarynnyy** [comment]
I'm closing it as we've got rid of vsix-installer separate image in https://github.com/eclipse-che/che-theia/pull/1222
