### ISSUE TITLE
[che-auth] Che with Devworkspaces should be able to use Dex as identity provider on OIDC enabled k8s

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20362]
### Is your task related to a problem? Please describe

After https://github.com/eclipse/che/issues/19366 . New Auth should work with any k8s with OIDC enabled.

### Describe the solution you'd like

We should be able to reconfigure Che with Devworkspaces to use dex as OAuth provider for OAuth-proxy.  Also, we can use OIDC part of Dex to get identities inside of che. 
 - [x] https://github.com/eclipse/che/issues/20633
 - [x] https://github.com/eclipse/che/issues/20635

### Additional context

https://github.com/eclipse/che/issues/19182

**Comment by sparkoo** [comment]
task splitted into https://github.com/eclipse/che/issues/20633 and https://github.com/eclipse/che/issues/20635. Closing this one to keep structure flat.
