### ISSUE TITLE
Update che-dashboard next-build-multiarch.yml to support main-7.yy branches

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#20361]
### Is your task related to a problem? Please describe

With the advent of a new temporary main-7.37 branch, we'll want to produce `:next-7.37` builds.

### Describe the solution you'd like

So the next builder needs to be updated such that:

* main and main-* branches are built - https://github.com/eclipse-che/che-dashboard/blob/main/.github/workflows/next-build-multiarch.yml#L17
* :next tag uses the same suffix after `main` (thus main-7.3.7 branch will cause `:next-7.37` tags to be created).

### Describe alternatives you've considered

do nothing. 

### Additional context

See discussion in https://coreos.slack.com/archives/CR87LL0PL/p1629881716085500

**Comment by sleshchenko** [comment]
we don't have main-7.yy branches anymore, closing it for time being.
