### ISSUE TITLE
[UD] Dashboard backend should trust Che CA while requesting Server and Keycloak

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#20367]
### Is your enhancement related to a problem? Please describe

Remove 'rejectUnauthorized: false'.

### Describe the solution you'd like

Dashboard backend should respect Che CA while requesting Server and Keycloak

**Comment by sleshchenko** [comment]
As an alternative it can go internal URLs instead. Which is more preferable option I think since sometime ago we switched to in cluster communication to avoid some HTTP_PROXY issues

**Comment by sleshchenko** [comment]
well, also I must verify if dashboard deployment needs HTTP_PROXY env vars

**Comment by sleshchenko** [comment]
Dashboard should respect `useInternalNetwork`

**Comment by sleshchenko** [comment]
For reference how Theia uses CAs and HTTP proxy
https://github.com/eclipse-che/che-theia/blob/main/plugins/workspace-plugin/src/ca-cert.ts
https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-server-https.ts
https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-http-service-impl.ts#L58
