### ISSUE TITLE
[UD] Setup formatter and linter for the dashboard backend

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#20379]
### Is your task related to a problem? Please describe

The dashboard backend package doesn't have any formatter set up and only contains the configuration file for tslint that was deprecated some time ago.

### Describe the solution you'd like

Setup typescript formatter and eslint for the dashboard backend package; reuse configurations from the dashboard frontend package. Run linter and formatter for staged files on pre-commit hook.

**Comment by sleshchenko** [comment]
fixed by https://github.com/eclipse-che/che-dashboard/pull/361
