### ISSUE TITLE
An admin should be able to specify CA certificates that need to be trusted on devfile v2 based workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20387]
### Is your enhancement related to a problem? Please describe

This is something that we do support for devfile v1 based workspaces but not for v2.

### Describe the solution you'd like

Inject the certificates bundle on devworkspaces.

**Comment by skabashnyuk** [comment]
@metlos is this issue covered by https://github.com/eclipse-che/che-operator/pull/1027?

**Comment by metlos** [comment]
We now sync the `ca-certs-merged` that che-operator gathers into the devworkspace namespaces and mark it to be mounted into the devworkspace pods by DWO. @tolusha is that enough to implement what this issue asks for?

**Comment by tolusha** [comment]
@metlos 
I believe yes.

**Comment by metlos** [comment]
Closing as this should now be implemented.
