### ISSUE TITLE
Support OpenShift global proxy configuration and trusted certificate bundle when DevWorkspace is enabled

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20386]
### Is your enhancement related to a problem? Please describe

That's related to clusters that use a proxy or other services that use a certificate signed by an untrusted CA. 

### Describe the solution you'd like

OpenShift has a mechanism to distribute the certificates bundle and we support it when the che-server is used to start workspaces.

We should support it in the DevWorkspace scenario too.

**Comment by skabashnyuk** [comment]
@metlos is this issue covered by https://github.com/eclipse-che/che-operator/pull/1027?

**Comment by metlos** [comment]
Yes, this should theoretically be handled by eclipse-che/che-operator#1027. It copies the configuration gathered by che-operator during che-server deployment time also into the namespaces of devworkspaces so that DWO can inject it into devworkspace pods.

**Comment by metlos** [comment]
This is implemented in https://github.com/eclipse-che/che-operator/pull/1027.

**Comment by nickboldt** [comment]
closed for Che 7.37
