### ISSUE TITLE
Verify if downloading a vsix from a devfile registry with untrusted TLS cert work when DevWorkspace is enabled

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20383]
### Is your task related to a problem? Please describe

That's a point that was in the [DevWorkspace MVP epic](https://github.com/eclipse/che/issues/19538) ("Che-Theia should be able to use a plugin registry that is using an untrusted certificated") and that may be related to a bug found recently [downstream](https://issues.redhat.com/browse/CRW-2200).

### Describe the solution you'd like

We should verfiy if, when the plugin registry is built with the plugins vsix files, Che is able to start a devfile v2 file.

**Comment by nickboldt** [comment]
Should this P1 be in the forthcoming sprint?

**Comment by l0rd** [comment]
We are using internal (unsecured) URL. Closing.
