### ISSUE TITLE
DevWorkspace happy path test is broken

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20389]
### Describe the bug

DevWorkspace happy path test is broken.
IDE is opened but tests can't locate it
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21509/rehearse-21509-pull-ci-devfile-devworkspace-operator-main-v8-devworkspace-happy-path/1432985082313838592
![Screenshot_20210901_115028](https://user-images.githubusercontent.com/5887312/131665460-235b0d61-1b19-45d9-a819-d8021988dc13.png)

### Che version

next (development version)

### Steps to reproduce

run happy devworkspace happy path test on Dashboard or DevWorkspace

### Expected behavior

it passes

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by dmytro-ndp** [comment]
@sleshchenko , @musienko-maxim: is there a chance to resolve this issue together with https://github.com/eclipse/che/issues/20385 ?
