### ISSUE TITLE
[UD] WebSockets does not work with native authentication

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20388]
### Describe the bug

[UD] WebSockets does not work with native authentication
![Screenshot_20210831_120740](https://user-images.githubusercontent.com/5887312/131522830-2e1038c1-60ca-4718-ab81-9b26628a1a57.png)

### Che version

next (development version)

### Steps to reproduce

Do deploy Che with dashboard backend on OpenShift and try to start and open a devworkspace.

### Expected behavior

DevWorkspace is running and IDE is opened.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by tsmaeder** [comment]
What's "native" authentication?

**Comment by sparkoo** [comment]
> What's "native" authentication?

https://github.com/eclipse/che/issues/19182 new way of authentication without keycloak

**Comment by sleshchenko** [comment]
fixed by https://github.com/eclipse-che/che-dashboard/pull/330
