### ISSUE TITLE
PostgreSQL version 13 is deployed on fresh installations

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#20398]
### Is your task related to a problem? Please describe

The final Release of PostgreSQL 9.6 should be November 11, 2021.
We use it as a database for che-server and keycloak.
We need to migrate to a more recent common version.

### Describe the solution you'd like

Adapt the code of che-operator. New installation should use PostgreSQL 13. Old installation should remain untouched.
Provide a migration guidance from PostgreSQL 9 -> 13. Proposal is to use Che's build in backup/restore methods.

### Describe alternatives you've considered

n/a

### Additional context

https://github.com/eclipse/che/issues/20246

### Release Notes Text

Starting from this release, deployment will include PosgreSQL 13. Previous deployments used PosgreSQL 9.6, which is EOL in November 2021.

**Comment by kcrane** [comment]
sync'd to redhat jira #CRW-2335

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2349

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2353

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2354

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2355

**Comment by max-cx** [comment]
@tolusha, I updated the Release Notes Text for this issue:

----

= PostgreSQL Upgrade

{prod} {prod-ver} installs with PostgreSQL 13.
In previous {prod} versions, PosgreSQL 9 is deprecated.

----

Feel free to okay, comment, or correct it in https://issues.redhat.com/browse/CRW-2374.
Thanks!
