### ISSUE TITLE
The all-namespace channel should be labelled as tech preview

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20393]
### Is your enhancement related to a problem? Please describe

Users that deploy Che are promted with the selection of the update channel:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/606959/131688825-117d7494-32b3-46ab-bf6c-0d558ba6f2b8.png">

but there is no evidence that the `all-namespace` channel is tech preview.

### Describe the solution you'd like

Users should know that the `all-namespaces` channel is a tech preview, not ready for production. Ideally we should add a description but if that's not possible we should rename the channel `tech-preview-stable-all-namespaces`.

**Comment by flacatus** [comment]
The channel was renamed successfully after https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/194. 

![image](https://user-images.githubusercontent.com/59865209/132463061-1fe70690-ea77-4bf6-bd1d-8d5143545b7c.png)
