### ISSUE TITLE
[kubernetes-image-puller] Remove the references of all 'nightly' and 'latest' tags from the repositories

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20399]
### Is your task related to a problem? Please describe

Remove the references of all 'nightly' and 'latest' tags from the repositories:
- https://quay.io/eclipse/kubernetes-image-puller
- https://quay.io/eclipse/kubernetes-image-puller-operator

examples of the references of images that have been removed:
- quay.io/eclipse/che-golang-1.12:nightly
- quay.io/eclipse/che-golang-1.12:latest
- quay.io/eclipse/che-java11-maven:nightly

### Describe the solution you'd like

Replace all the refences with the 'next' tagreferences

### Describe alternatives you've considered

N/A

### Additional context

https://github.com/eclipse/che/issues/19291#issuecomment-907220922

**Comment by nickboldt** [comment]
Tags nightly and latest removed from:

* https://quay.io/repository/eclipse/kubernetes-image-puller?tag=latest&tab=tags
* https://quay.io/repository/eclipse/kubernetes-image-puller-operator?tag=latest&tab=tags
