### ISSUE TITLE
Happy path tests failed because there was no trust git repository authors popup

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#20408]
### Describe the bug

Happy path tests failed on "Wait for workspace readiness" step because there was no trust git repository authors popup: 
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/665/

![screenshot-Wait_for_workspace_readiness](https://user-images.githubusercontent.com/1197777/131985600-232d5bf9-b880-444a-b700-d393f1c607f9.png)

```
     ​1) Wait for workspace readiess
   ​[ERROR] CheReporter runner.on.fail: Validation of workspace start Wait for workspace readiness failed after 205408ms
            ​‣ FullTitle:Validation of workspace start Wait for workspace readiness
            ​‣ FullTitleSanitized:Validation_of_workspace_start_Wait_for_workspace_readiness
            ​‣ TestTitle:Wait for workspace readiness
            ​‣ TestTitleSanitized:Wait_for_workspace_reainss
 
 ​
   ​3 passing 4m)
   ​1 filin
 ​
   ​1) Validation of workspace start
       ​Wait for workspace readiness
      ​TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //div[@class='theia-notification-message']/span[contains(.,'Do you trust the authors of')])' element, timeouted after 60000       ​at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:156:15)       ​at process._tickCallback (internal/process/next_tick.js:6:7)
   ​From: Task: <anonymous>       ​at pollCondition (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2195:19)       ​at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2191:7       ​at new ManagedPromise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1077:7)       ​at ControlFlow.promise (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2505:12)       ​at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2190:22       ​at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)       ​at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)       ​at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2974:25)       ​at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7       ​at process._tickCallback (internal/process/next_tick.js:6:7)
   ​From: Task: <anonymous wait>       ​at scheduleWait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2188:20)       ​at ControlFlow.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2517:12)       ​at thenableWebDriverProxy.wait (/tmp/e2e/node_modules/selenium-webdriver/lib/webdriver.js:934:29)       ​at Ide.waitNotificationAndClickOnButton (/tmp/e2e/pageobjects/ide/Ide.ts:100:45)       ​at Context.test (/tmp/e2e/tests/e2e_happy_path/HappyPath.spec.ts:85:19)       ​at process._tickCallback (internal/process/next_tick.js687)
```

### Che version

next (development version)

### Steps to reproduce

Run Happy path tests.

### Expected behavior

There should be trust git repository authors popup.

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

### Additional context

Related changes: https://github.com/eclipse/che/pull/20374

**Comment by vitaliy-guliy** [comment]
We are waiting for https://github.com/eclipse-che/che-theia/pull/1212 that hopefully will fix building and publishing of `che-theia:next`.
The build of `che-theia:next` it temporary broben, it was published last time more than 2 weeks ago https://quay.io/repository/eclipse/che-theia?tag=next&tab=tags

As a temporary solution - is to check for the notification and click `Trust` button only when appeared.

**Comment by dmytro-ndp** [comment]
@vitaliy-guliy: Thanks for an answer!

I have recently got the notification that `che-theia:next` image had been updated.
After that [Happy path tests have passed successfully](https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/668/):
![Screenshot from 2021-09-03 16-01-06](https://user-images.githubusercontent.com/1197777/132009560-d484462b-c44d-460d-b7a6-edf066663e5f.png)
