### ISSUE TITLE
Provides CHE_PLUGIN_REGISTRY_INTERNAL_URL

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#20402]
### Is your enhancement related to a problem? Please describe

Sometimes external links are not working (like missing certificates, etc)

### Describe the solution you'd like

Add in addition to the external link the internal link of the plugin registry
`CHE_PLUGIN_REGISTRY_INTERNAL_URL`

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by sleshchenko** [comment]
I believe it can be closed after https://github.com/eclipse-che/che-dashboard/pull/331 is merged
