### ISSUE TITLE
Errors thrown by devWorkspaceController

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#20400]
### Describe the bug

Unable to start a DevWorkspace using minikube/1.22 or OpenShift 4.6 or 4.8

DevWorkspace controller is reporting
```
E0902 14:35:36.547680       1 leaderelection.go:325] error retrieving resource lock devworkspace-controller/8d217f93.devfile.io: leases.coordination.k8s.io "8d217f93.devfile.io" is forbidden: User "system:serviceaccount:devworkspace-controller:devworkspace-controller-serviceaccount" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "devworkspace-controller"
```

and the dashboard
```
client.8de151386c57f4ec954e.js:1 Uncaught (in promise) TypeError: Cannot read property 'devworkspaceId' of undefined
    at b.createStatusUpdate (client.8de151386c57f4ec954e.js:1)
    at client.8de151386c57f4ec954e.js:1
    at Array.forEach (<anonymous>)
    at client.8de151386c57f4ec954e.js:1
```

### Che version

next (development version)

### Steps to reproduce

Click on a DevWorkpace 2.0 example after enabling DevWorkspace engine with chectl

### Expected behavior

DevWorkspace is starting fine

### Runtime

OpenShift, minikube

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by sleshchenko** [comment]
fixed by https://github.com/eclipse-che/che-operator/pull/1050
