### ISSUE TITLE
Cannot get CHE_INFRA_KUBERNETES_PVC_QUANTITY to work correctly

### ISSUE THREAD

**Issue by donenocode** [eclipse-che/che#20407]
### Summary
EDIT: Rebuilt on 7.35.0 and I still dont get it to work, have updated below information:

I have tried to use the 'CHE_INFRA_KUBERNETES_PVC_QUANTITY' key to change the default PVC size from 10Gi to 1Gi as per:
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#kubernetes-infra-parameters

The 'cheCluster' definition shows (I have removed most options to show the relevant settings):
```kubectl get cheCluster -n this -o json```
```
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "org.eclipse.che/v1",
            "kind": "CheCluster",
            "metadata": {
                "name": "eclipse-che",
                "namespace": "this",
            },
            "spec": {
                "server": {
                    "customCheProperties": {
                        "CHE_INFRA_KUBERNETES_PVC_QUANTITY": "1Gi"
                    },
                },
                "storage": {
                    "preCreateSubPaths": true,
                    "pvcClaimSize": "10Gi",
                    "pvcStrategy": "common"
                }
}
```

I can see 'CHE_INFRA_KUBERNETES_PVC_QUANTITY' and 'pvcClaimSize'  which may or may not be correct?
I have tried manually scaling down and back up the che pod but this did not help.

I am probably using this incorrectly, and could really use a couple of pointers!

I do have other custom properties set that do work (such as idle workspace timeout and run limit) I just cant see what I have done wrong with this one!

EDIT: Rebuilt on 7.35.0 and since that I can see that the setting does not make it to the Che server POD (see below output from the command inside the container)

Thanks.

### Relevant information

This is my development setup and not production!
cheVersion: 7.35.0
Deployed via operator
Rancher RKE cluster

```
#inside che server container
set | grep -i PVC
CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE=registry.access.redhat.com/ubi8-minimal:8.4-208
CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS=true
CHE_INFRA_KUBERNETES_PVC_QUANTITY=10Gi
CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME=
CHE_INFRA_KUBERNETES_PVC_STRATEGY=common
```
EDIT: Rebuilt on 7.35.0 and I still dont get it to work, have updated above information

**Comment by tolusha** [comment]
@donenocode 
1. It is enough to set `spec.storage.pvcClaimSize: 1Gi`
2. Should be done before deploying Eclipse Che

```bash
chectl server:delete

cat >/tmp/che-cr-patch.yaml <<EOL
spec:
  storage:
    pvcClaimSize: 1Gi
EOL

chectl server:deploy --che-operator-cr-patch-yaml=/tmp/che-cr-patch.yaml ...
```

**Comment by donenocode** [comment]
Thanks for this.

I have noted since the upgrade to 7.35.1 this has now taken effect correctly.
