### ISSUE TITLE
Eclipse Che not opening in browser on Windows

### ISSUE THREAD

**Issue by mmarimuthu** [eclipse-che/che#20411]
### Summary

Eclipse Che was successfully installed on minikube but couldn't access it on the browser. is anything needed more to get it working on the browser. Its been three days i am hitting to get to see the dashboard. 

Commands Used

To start minikube -> `minikube start --addons=ingress --vm=true --memory=4092`
To start che -> `chectl server:deploy --platform minikube`

Version Information
**minikube :** v1.22.0
**chectl** : chectl/0.0.20210903-next.e9578a5 win32-x64 node-v12.22.6
**kubectl :**

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

![image](https://user-images.githubusercontent.com/28609408/132019203-c157969f-f85f-4a7b-8750-35475ac7f6b1.png)
![image](https://user-images.githubusercontent.com/28609408/132019091-ef82742e-1514-4a1a-bc5c-c78c91251820.png)
![image](https://user-images.githubusercontent.com/28609408/132019123-ceb09fb5-abc4-4a1e-b016-a7c3f815146c.png)
![image](https://user-images.githubusercontent.com/28609408/132019162-07f6cae6-b104-49be-b375-426f06a183a4.png)
![image](https://user-images.githubusercontent.com/28609408/132023446-3e62b881-924d-4bf6-b6fa-c79274028358.png)

**Comment by debimishra89** [comment]
have you put hostnames of che dashboard and keycloak in your windows/mac host file?
 hosts file location in windows: C:\Windows\System32\drivers\etc

**Comment by mmarimuthu** [comment]
Yes. You are right. It worked after making entry in hosts file.
