### ISSUE TITLE
failed to create workspace : failed to download plugin because of connection refused error

### ISSUE THREAD

**Issue by debimishra89** [eclipse-che/che#20418]
### Describe the bug

I am not able to create workspace because of the below issue

#### failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused

I have checked my internet connection and firewall settings. There is no problem. Even I can download this plugin using "wget" in linux terminal. But its throwing error from Che UI

### Che version

7.35@latest

### Steps to reproduce

1. Install Che using minikube on centos7 VM: https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/
2. create workspace

### Expected behavior

workspace should be created successfully

### Runtime

minikube

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
Successfully assigned admin-che/workspace8zvc8ayjai4qhqrh.che-plugin-broker to exp-3.dastc.stee.com

Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0" in 6.545374518s

Created container che-plugin-metadata-broker-v3-4-0

Starting plugin metadata broker

List of plugins and editors to install

- ms-python/python/latest - Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.

- eclipse/che-theia/latest - Eclipse Theia

All plugin metadata has been successfully processed

Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:a6508bee982104d194435741e6e14aebe22a358d92526464e4e9f3f716c52ecd"

Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:a6508bee982104d194435741e6e14aebe22a358d92526464e4e9f3f716c52ecd" in 1.16756443s

Created container remote-runtime-injectoru2j

Started container remote-runtime-injectoru2j

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0" in 3.728127877s

Created container che-plugin-artifacts-broker-v3-4-0

Starting plugin artifacts broker

Cleaning /plugins dir

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix

Started container che-plugin-artifacts-broker-v3-4-0

failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0" in 4.45999581s

Created container che-plugin-artifacts-broker-v3-4-0

Started container che-plugin-artifacts-broker-v3-4-0

Starting plugin artifacts broker

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix

Cleaning /plugins dir

failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused

Back-off restarting failed container

Back-off restarting failed container

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0" in 3.468759866s

Created container che-plugin-artifacts-broker-v3-4-0

Starting plugin artifacts broker

Cleaning /plugins dir

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix

Started container che-plugin-artifacts-broker-v3-4-0

failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused

Back-off restarting failed container

Back-off restarting failed container

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0" in 3.887667365s

Created container che-plugin-artifacts-broker-v3-4-0

Starting plugin artifacts broker

Cleaning /plugins dir

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix

failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused

Started container che-plugin-artifacts-broker-v3-4-0

Back-off restarting failed container

Starting plugin artifacts broker

Cleaning /plugins dir

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix

failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused

Starting plugin artifacts broker

Cleaning /plugins dir

Processing plugin ms-python/python/latest

Installing plugin extension 1/1

Downloading plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix

failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused

Back-off restarting failed container

Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the workspace'workspace8zvc8ayjai4qhqrh' reached timeout"
```

**Comment by debimishra89** [comment]
I saw similar issue #16387 , but couldn't figure out the solution

**Comment by sunix** [comment]
@debimishra89 thanks for reporting this issue.
What about downloading (wget) from your Centos VM? same issue?

**Comment by tolusha** [comment]
That's strange. It works for me. Could you try again?

![screenshot-che-eclipse-che 192 168 99 100 nip io-2021 09 06-18_00_49](https://user-images.githubusercontent.com/1640675/132235994-cadf9ce2-af9d-4af6-88ab-0c142660ef2b.png)

**Comment by debimishra89** [comment]
> That's strange. It works for me. Could you try again?
> Do you use proxy?
> 
> ![screenshot-che-eclipse-che 192 168 99 100 nip io-2021 09 06-18_00_49](https://user-images.githubusercontent.com/1640675/132235994-cadf9ce2-af9d-4af6-88ab-0c142660ef2b.png)

No, i dont have any proxy setting.
![image](https://user-images.githubusercontent.com/84674037/132241537-7f4e59ff-5b83-4574-a431-565db040ca19.png)

I found #16387 which is same issue

**Comment by debimishra89** [comment]
below screenshot shows successful download by using WGET in the linux terminal. it means firewall is not a problem.
![image](https://user-images.githubusercontent.com/84674037/132243521-c1070a0d-e6a9-4524-82d8-cd6fa6b61780.png)

**Comment by debimishra89** [comment]
@sunix , @tolusha , could you pls advise how to debug this issue

**Comment by debimishra89** [comment]
please find below minikube cluster details
![image](https://user-images.githubusercontent.com/84674037/132291408-142f68a0-fb97-41aa-a770-942be6083017.png)

#### CHE OPERATOR pod crashloops sometimes  because of below error
{"level":"info","ts":1630993559.2189076,"logger":"controller","msg":"Starting workers","reconcilerGroup":"org.eclipse.che","reconcilerKind":"CheCluster","controller":"checluster","worker count":1}
I0907 05:46:00.969425       1 request.go:655] Throttling request took 1.048642411s, request: GET:https://10.96.0.1:443/apis/coordination.k8s.io/v1beta1?timeout=32s
E0907 05:46:11.512016       1 leaderelection.go:325] error retrieving resource lock eclipse-che/e79b08a4.org.eclipse.che: Get "https://10.96.0.1:443/api/v1/namespaces/eclipse-che/configmaps/e79b08a4.org.eclipse.che": dial tcp 10.96.0.1:443: connect: connection refused
time="2021-09-07T05:46:13Z" level=error msg="Get \"https://10.96.0.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/eclipse-che-cheworkspaces-devworkspace-clusterrole\": dial tcp 10.96.0.1:443: connect: connection refused"
{"level":"error","ts":1630993573.2937756,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"org.eclipse.che","reconcilerKind":"CheCluster","controller":"checluster","name":"eclipse-che","namespace":"eclipse-che","error":"Get \"https://10.96.0.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/eclipse-che-cheworkspaces-devworkspace-clusterrole\": dial tcp 10.96.0.1:443: connect: connection refused","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/che-operator/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
E0907 05:46:13.512933       1 leaderelection.go:325] error retrieving resource lock eclipse-che/e79b08a4.org.eclipse.che: Get "https://10.96.0.1:443/api/v1/namespaces/eclipse-che/configmaps/e79b08a4.org.eclipse.che": dial tcp 10.96.0.1:443: connect: connection refused
time="2021-09-07T05:46:14Z" level=error msg="Error discovering image puller APIs: Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: connect: connection refused"
{"level":"error","ts":1630993574.2956011,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"org.eclipse.che","reconcilerKind":"CheCluster","controller":"checluster","name":"eclipse-che","namespace":"eclipse-che","error":"Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: connect: connection refused","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/che-operator/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
time="2021-09-07T05:46:15Z" level=error msg="Error discovering image puller APIs: Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: connect: connection refused"
{"level":"error","ts":1630993575.2967649,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"org.eclipse.che","reconcilerKind":"CheCluster","controller":"checluster","name":"eclipse-che","namespace":"eclipse-che","error":"Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: connect: connection refused","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/che-operator/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
E0907 05:46:15.513203       1 leaderelection.go:325] error retrieving resource lock eclipse-che/e79b08a4.org.eclipse.che: Get "https://10.96.0.1:443/api/v1/namespaces/eclipse-che/configmaps/e79b08a4.org.eclipse.che": dial tcp 10.96.0.1:443: connect: connection refused
time="2021-09-07T05:46:16Z" level=error msg="Error discovering image puller APIs: Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: connect: connection refused"

#### STORAGE PROVIDER pod too crashloops sometimes
goroutine 123 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc00069c490, 0x0)
        /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00069c480)
        /usr/local/go/src/sync/cond.go:56 +0x99
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0004f5560, 0x0, 0x0, 0x100)
        /Users/medya/go/pkg/mod/k8s.io/client-go@v0.20.5/util/workqueue/queue.go:145 +0x89
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem(0xc00046cc80, 0x18e5530, 0xc000140a00, 0x203001)
        /Users/medya/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v6@v6.3.0/controller/controller.go:990 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runVolumeWorker(...)
        /Users/medya/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v6@v6.3.0/controller/controller.go:929
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.3()
        /Users/medya/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v6@v6.3.0/controller/controller.go:881 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000192160)
        /Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000192160, 0x18b3d60, 0xc0006d8000, 0x1, 0xc0001d4660)
        /Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000192160, 0x3b9aca00, 0x0, 0x1, 0xc0001d4660)
        /Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000192160, 0x3b9aca00, 0xc0001d4660)
        /Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
        /Users/medya/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v6@v6.3.0/controller/controller.go:881 +0x3d6

goroutine 157 [runnable]:
k8s.io/client-go/tools/record.(*recorderImpl).generateEvent.func1(0xc00069c3c0, 0xc00046c280)
        /Users/medya/go/pkg/mod/k8s.io/client-go@v0.20.5/tools/record/event.go:341
created by k8s.io/client-go/tools/record.(*recorderImpl).generateEvent
        /Users/medya/go/pkg/mod/k8s.io/client-go@v0.20.5/tools/record/event.go:341 +0x3b7

**Comment by tolusha** [comment]
Something wrong with a cluster. Could you try another minikube version or restart this?

/cc @svor

**Comment by debimishra89** [comment]
> Something wrong with a cluster. Could you try another minikube version or restart this one?
> 
> /cc @svor

looks like CHE OPERATOR pod has some issues. But I strictly followed installation document and haven't done additional setting.

**Comment by tolusha** [comment]
Yes, but besides che-operator other cluster components fails.
So, let's try with a clean working cluster first.

**Comment by debimishra89** [comment]
> Yes, but besides che-operator other cluster components fails.
> So, let's try with a clean working cluster first.

please suggest which version of minikube i shd use now

**Comment by tolusha** [comment]
Try the latest `v1.23.0`

**Comment by tolusha** [comment]
sorry, We have an issue with minikube v1.23
https://github.com/eclipse/che/issues/20431

**Comment by debimishra89** [comment]
@tolusha , @svor 

#### CHE OPERATOR pod crashloops sometimes because of below error (dial tcp 10.96.0.1:443: connect: connection refused)
#### Storage Provider pod also failing because of same issue.
#### Workspace creation is also failing because of same issue
failed to download plugin from https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: Get https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix: dial tcp 192.64.147.223:443: connect: connection refused



I feel all are inter-related. if we resolve this connection refused issue, maybe all pods issue will go away and workspace will be created.

I am ready to debug if someone give me some guidance.

**Comment by debimishra89** [comment]
kubectl describe pod/che-operator-778d679b49-cxfs8 --namespace=eclipse-che


Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Normal   Pulling    59m (x483 over 4d14h)    kubelet  Pulling image "quay.io/eclipse/che-operator:7.35.1"
  Warning  Unhealthy  9m51s (x640 over 4d14h)  kubelet  Liveness probe failed: Get "http://172.17.0.4:6789/healthz": dial tcp 172.17.0.4:6789: connect: connection refused
  Warning  Unhealthy  3m51s (x653 over 4d14h)  kubelet  Readiness probe failed: Get "http://172.17.0.4:6789/readyz": dial tcp 172.17.0.4:6789: connect: connection refused

**Comment by tolusha** [comment]
I still believe it is a cluster issue.
If you use minikube 1.22 please try 1.21 and vice versa.

**Comment by debimishra89** [comment]
@tolusha , Agreed , this is pod issue. Please see logs from che-operator pod.

time="2021-09-09T15:37:13Z" level=info msg="Deployment plugin-registry is in the rolling update state."
I0909 15:37:15.651964       1 request.go:655] Throttling request took 1.04725976s, request: GET:https://10.96.0.1:443/apis/extensions/v1beta1?timeout=32s
time="2021-09-09T15:37:16Z" level=info msg="Deployment plugin-registry is in the rolling update state."
I0909 15:37:37.710602       1 request.go:655] Throttling request took 1.046990691s, request: GET:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1?timeout=32s
W0909 15:43:23.172829       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
E0909 15:47:05.403189       1 leaderelection.go:325] **error retrieving resource lock** eclipse-che/e79b08a4.org.eclipse.che: Get "https://10.96.0.1:443/api/v1/namespaces/eclipse-che/configmaps/e79b08a4.org.eclipse.che": **context deadline exceeded**
I0909 15:47:05.403334       1 leaderelection.go:278] **failed to renew lease eclipse-che/e79b08a4.org.eclipse.che: timed out waiting for the condition**
{"level":"info","ts":1631202425.4036877,"logger":"controller","msg":"Stopping workers","reconcilerGroup":"org.eclipse.che","reconcilerKind":"CheCluster","controller":"checluster"}
{"level":"error","ts":1631202425.4034257,"logger":"setup","msg":**"problem running manager","error":"leader election lost"**,"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/che-operator/vendor/github.com/go-logr/zapr/zapr.go:132\nmain.main\n\t/che-operator/main.go:254\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:204"}

**Comment by debimishra89** [comment]
@tolusha , I have googled this and the solution is to disable leader election.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/622
https://github.com/zhyass/mysql-operator/issues/8

could you please help disable leader election on this CHE OPERATOR pod.
I am not so familiar with kubernetes and finding it hard to debug it.

**Comment by tolusha** [comment]
I've removed `ref: "${{ github.event.inputs.version }}"` from
```
 - name: Checkout che-plugin-registry
      uses: actions/checkout@v2
      with:
        repository: eclipse-che/che-plugin-registry
        path: che-plugin-registry 
```

and added 
```
        git fetch
        git checkout ${{ github.event.inputs.version }}
```

Images are referenced by digests now 
https://github.com/tolusha/plugins-registry/runs/3564851353?check_suite_focus=true

**Comment by tolusha** [comment]
That's not possible. Disabling leader election won't solve your problem.  I believe that's not a cause but consequence of misworking cluster.

**Comment by debimishra89** [comment]
Hi @tolusha , as you advised, 
1. I have reinstalled minikube v1.21.0
2. chectl (7.63.1) server deployed on minikube
3. BUT same issue issue while creating workspace.

cluster info:
![image](https://user-images.githubusercontent.com/84674037/134126078-10438a2b-82e8-4fba-a421-2eabde988f05.png)

![image](https://user-images.githubusercontent.com/84674037/134126125-5a79436f-03af-43b8-9c7d-b58d9f68812d.png)

![image](https://user-images.githubusercontent.com/84674037/134126168-251ca6f1-2f1e-4fc9-bf94-4908147d0331.png)


Error while creating workspace:
![image](https://user-images.githubusercontent.com/84674037/134126229-cb24a921-a503-4c45-aad5-88294e2d483b.png)


Now please advise how to resolve this workspace creation error. I really want to get it working.

**Comment by tolusha** [comment]
@benoitf 
Do you have any ideas?

**Comment by debimishra89** [comment]
@tolusha , @benoitf - I am waiting for your guidance

**Comment by benoitf** [comment]
Hello, I think there is network issue from inside your containers.

Are you able to exec into one container of your minikube instance and perform the curl operation ?

(or for example connecting to minikube with `minikube ssh`

Also based on https://github.com/kubernetes/minikube/issues/3704

> After using hyperkit instead of virtualbox seems having no issue so far. Try this if anyone having the same issue. https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver

And some people try to remove entirely ~/.minikube folder as well before reinstalling minikube

**Comment by debimishra89** [comment]
> Hello, I think there is network issue from inside your containers.
> 
> Are you able to exec into one container of your minikube instance and perform the curl operation ?
> 
> (or for example connecting to minikube with `minikube ssh`
> 
> Also based on [kubernetes/minikube#3704](https://github.com/kubernetes/minikube/issues/3704)
> 
> > After using hyperkit instead of virtualbox seems having no issue so far. Try this if anyone having the same issue. https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver
> 
> And some people try to remove entirely ~/.minikube folder as well before reinstalling minikube

Hi @benoitf , 
minikube ssh not supported with none driver
![image](https://user-images.githubusercontent.com/84674037/134373677-65315be6-b80b-4586-9585-bcfc796ce5d6.png)


I can confirm when i reinstalled minikube, I removed ~/.minikube using "minikube delete --all --purge"

**Comment by debimishra89** [comment]
@benoitf , I tried to do curl inside a pod bash, but its showing #### connection refused

![image](https://user-images.githubusercontent.com/84674037/134376892-b1858726-11ca-4948-9052-ed04b272320d.png)

**Comment by debimishra89** [comment]
@benoitf , I tried to execute curl command inside a pod of minikube cluster and its throwing connection refused error

![image](https://user-images.githubusercontent.com/84674037/134378565-6a228eb3-f449-4ab3-8b11-68bec229f4db.png)
