### ISSUE TITLE
Is it possible to use CockroachDB with Eclipse Che

### ISSUE THREAD

**Issue by RyuunoAelia** [eclipse-che/che#20413]
### Summary

I find that Postgres is a great solution for DB, however setting up HA can be really hard if
* you don't have dedicated postgres experts
* you are not in a cloud that provides managed postgres
* you don't want to have your (hard to duplicate) persistent data inside k8s (because you use blue-green k8s deployments etc)

So I was wondering if the requirements of Eclipse Che were compatible with what a solution like CockroachDB provides. It is postgres-compatible on-wire but since it is distributed, locking and some other SQL features and ACID properties are not exactly the same as what Postgres provides.

**Comment by tolusha** [comment]
@RyuunoAelia 
We have never tested with such a DB.
You can give a try
```bash
cat >/tmp/che-cr-patch.yaml <<EOL
spec:
  database:
    postgresImage: <CockroachDB image>
EOL

chectl server:deploy  --che-operator-cr-patch-yaml=/tmp/che-cr-patch.yaml .....
```
