### ISSUE TITLE
Empty projects in `Dashboard - Quick Add` devfiles and invite the user to clone or generate a project

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#20428]
### Is your enhancement related to a problem? Please describe

Users who want to start with a new devfile would either
- start/generate a new project
- use an existing project

If we take the quarkus devfile, generating a new project could be done with the generator https://quarkus.io/guides/getting-started#bootstrapping-the-project

Having a predefined sample project doesn't make sense most of the time. In both case, this sample project would be removed and replaced with a new one

### Describe the solution you'd like

if possible, Quick Add devfiles should not contain sample projects to clone, che-theia would invite the user to clone or generate a project as a first step if empty. Could be done as part of a didact guide or something automated in a plugin.
Also, the commands would need to be more generic and use variables to refer to the workspaceFolder, not hard coding the path of the project location.

**Comment by svor** [comment]
As for me it's good enough when devfile provides a sample project from the start and if user wants to remove it I don't think it is a problem. 
In case of quarkus as I know vscode-quarkus already provides a command to generate a sample project `Quarkus: Generate a Quarkus Project`

**Comment by sunix** [comment]
To me, it is a big User experience issue: what are the Quick Add projects made for ? what is the purpose ?
These are questions for the new users as well as the day to day users. If in 100% of the case, the users would remove the project, why should we keep it ?

**Comment by l0rd** [comment]
Samples are just samples (code + devfile), these are not templates or stacks that can be applied to any project.
When a user wants to open his project he should just provide the repo url and then we should guide him in the creation of the devfile ==> https://github.com/eclipse/che/issues/18671

**Comment by sunix** [comment]
@l0rd https://github.com/eclipse/che/issues/18671 is good ok for existing project.

- what if a user would like to create a quarkus or springboot project from scratch ? can't he be pointed to an empty workspace with a quarkus/springboot stack and use the tools in there to bootstrap the project ?
- what is the purpose of the sample projects for our users ? is this just for demo ?
