### ISSUE TITLE
Failed to request factory resolver namespaces not found

### ISSUE THREAD

**Issue by mtsmfm** [eclipse-che/che#20420]
### Describe the bug

It seems we can't create new workspace with Import from Git if the repo doesn't have devfile.yaml and it's first time to create workspace.

### Che version

7.35@latest

### Steps to reproduce

1. Setup eclipse che
2. Create workspace with Import from Git and input https://github.com/eclipse/che
![image](https://user-images.githubusercontent.com/1796864/132229820-e1aaf75d-524e-45cf-ab98-ee6cf6a94597.png)

### Expected behavior

A workspace is created successfully

### Runtime

Kubernetes (vanilla), Docker Desktop

### Screenshots

![image](https://user-images.githubusercontent.com/1796864/132229953-d9205f39-a20a-401b-b802-4e13589ed821.png)

### Installation method

chectl/latest

### Environment

Windows, Amazon

### Eclipse Che Logs

https://che-eclipse-che.che.127.0.0.1.nip.io/api/factory/resolver/ returns 400 and the response message is

```shell
Error occurred during creation a workspace from devfile located at `https://raw.githubusercontent.com/eclipse/che/HEAD/devfile.yaml`. Cause: Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/mtsmfm-che/secrets. Message: namespaces "mtsmfm-che" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=namespaces, name=mtsmfm-che, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=namespaces "mtsmfm-che" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
```

### Additional context

I can't find any log on che server component with the following steps:

1. Run the following command
```
$ kubectl logs -n eclipse-che -l component=che --follow
```
2. Do the Steps to reproduce

I think you can easily reproduce this problem with `kubectl delete ns <yourname>-che`

**Comment by skabashnyuk** [comment]
Duplicates https://github.com/eclipse/che/issues/19236 and should be fixed https://github.com/eclipse/che/issues/20167
Workaround - create at least one workspace.

**Comment by mtsmfm** [comment]
@skabashnyuk Thank you for pointing out.
I searched issues with some keywords like "namespace not found" though I overlooked them.
