### ISSUE TITLE
Confused behavior when switching to Events area

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2042]
**Reproduction Steps:**

1.Open some project in IDE.
2. Click on the Events tab. 
3. Invoke git status and then press Events tab again.

**Expected behavior:**
the Events area should be visible.

**Observed behavior:**
the Events area is closed and need to click on the tab again that it became visible. 

**Che version:**   4.7.0  
**OS and version:**  Ubuntu 14.04  
**Docker version:**  1.11.1  
**Che install:**  local bundle   

**Additional information:**
See attachment.
![events_area](https://cloud.githubusercontent.com/assets/5408906/17392864/d145a2e0-5a28-11e6-962e-c21d84a74c1e.gif)

**Comment by bmicklea** [comment]
The current behavior seems reasonable to me. If you trigger a command that has an output I want to see the output not the events. If I want the events I can always click back to it.

I don't think this is a bug.

**Comment by artaleks9** [comment]
Now the bug is fixed and not reproduced.
