### ISSUE TITLE
Ingress container is giving failure 

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [eclipse-che/che#20436]
### Summary

I am using the latest chectl to create a local setup using the docker desktop.

My setup was successful and able to run for 10 days, updated to latest using the chectl. Now I facing an error related to the "ingress" controller. 

![image](https://user-images.githubusercontent.com/64516009/132364277-30225b36-0bc0-43aa-930c-9d23dacea364.png)
Unable to move to next line, and error report at ingress pod

![image](https://user-images.githubusercontent.com/64516009/132365873-226fea10-0a7d-4c93-a77a-6f2eb73729df.png)

### Relevant information
![Screenshot 2021-09-07 at 8 16 03 PM](https://user-images.githubusercontent.com/64516009/132366127-cd0516e2-ad30-45c3-bfd8-7aa6388d2778.png)
_No response_

**Comment by RomanNikitenko** [comment]
@tolusha 
could you take a look

**Comment by tolusha** [comment]
@kollachaitanyakrishna 
Have you restarted you docker-desktop? If so, you might hit the issue https://github.com/eclipse/che/issues/16134
What is your docker-desktop version? What is the Eclipse Che version?

@RomanNikitenko 
I have no idea why work workspace start up related to deploy ;)

**Comment by kollachaitanyakrishna** [comment]
![Screenshot 2021-09-08 at 12 24 08 PM](https://user-images.githubusercontent.com/64516009/132460860-ae04839f-8f90-43d1-9a9e-886a8594aa03.png)


![image](https://user-images.githubusercontent.com/64516009/132461570-4659d027-4a7b-44b5-84ec-b97c893c4a28.png)
sharing the info as requested.

**Comment by kollachaitanyakrishna** [comment]
I do not remember the old version.

**Comment by tolusha** [comment]
@flacatus 
Could you check pls?

**Comment by flacatus** [comment]
@kollachaitanyakrishna I cannot reproduce your issue on Docker Desktop 3.5.1 in Windows platform.
Can you check a newer version and with che 7.35.2?

**Comment by kollachaitanyakrishna** [comment]
![Screenshot 2021-09-09 at 2 58 52 PM](https://user-images.githubusercontent.com/64516009/132660970-b70e3861-66e3-4467-bebe-f9022862987d.png)

I am on the latest as per the CLI, but UI shows older version, is there a way for the force upgrade. I am on MAC.

**Comment by flacatus** [comment]
`chectl server:update` update your che version
`chectl update` update your chectl cli

**Comment by tolusha** [comment]
@kollachaitanyakrishna
What does print?
`kubectl get ingress -n eclipse-che`

**Comment by tolusha** [comment]
as well
```
NGINX_POD=$(kubectl get pods -n ingress-nginx | grep ingress-nginx-controller | awk '{print $1}')
kubectl logs $NGINX_POD -n ingress-nginx
```

**Comment by kollachaitanyakrishna** [comment]
chectl server:update : resulted an error, check screen shot.
![Screenshot 2021-09-09 at 3 34 48 PM](https://user-images.githubusercontent.com/64516009/132666833-3f07c77a-6da1-4037-be4b-d57a79b8f8dc.png)
![Screenshot 2021-09-09 at 3 35 45 PM](https://user-images.githubusercontent.com/64516009/132666864-c2b1e982-61cf-4f49-80aa-d0997d9242c9.png)
@tolusha , @flacatus

**Comment by tolusha** [comment]
@flacatus 
`helmcharts` were used. Could you check again?

**Comment by kollachaitanyakrishna** [comment]
@tolusha : I user chectl server:deploy to create the instance. During the deployment it used the helm charts.

**Comment by flacatus** [comment]
@kollachaitanyakrishna We cannot reproduce your poroblem in MacOs even with helm charts.... I have some suggestions for you:
  1. Remove che completelly and install again 7.35.2? `chectl server:deploy --installer=helm --platfrom=docker-desktop`
  2. Use minikube in your local environment instead of docker-desktop if previous step didn't worked.

**Comment by kollachaitanyakrishna** [comment]
![Screenshot 2021-09-10 at 11 36 35 PM](https://user-images.githubusercontent.com/64516009/132898157-34e06595-d9be-4055-8a38-59e069c89634.png)

**Comment by kollachaitanyakrishna** [comment]
Deleted the old setup as mentioned above and create new setup, Now I am on the latest, but the error remains same, 
![image](https://user-images.githubusercontent.com/64516009/132901536-1aa00b67-c52a-4d3c-a7fb-daeca05cb9d7.png)
![Screenshot 2021-09-11 at 12 09 28 AM](https://user-images.githubusercontent.com/64516009/132901747-a70e258d-85da-4da8-9017-4c93d5ab5025.png)

**Comment by kollachaitanyakrishna** [comment]
![image](https://user-images.githubusercontent.com/64516009/132901995-3d6d0fdb-c818-4a5a-80d8-d20f78d373d3.png)
@flacatus : I cannot move to minikube.

**Comment by kollachaitanyakrishna** [comment]
![image](https://user-images.githubusercontent.com/64516009/132901995-3d6d0fdb-c818-4a5a-80d8-d20f78d373d3.png)
@flacatus : I can not move to minikube.

**Comment by tolusha** [comment]
1. try to start a workspace in verbose mode and inspect logs if there is an obvious error
2. try to start che-server in debug mode [2] and inspect logs

[1] https://www.eclipse.org/che/docs/che-7/end-user-guide/investigating-failures-at-a-workspace-start-using-the-verbose-mode/
[2] `kubectl patch checluster/eclipse-che --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_LOGGER_CONFIG\": \"che.infra.request-logging=TRACE,io.fabric8.kubernetes.client=DEBUG\"}}}}" --type=merge -n eclipse-che`

**Comment by kollachaitanyakrishna** [comment]
thanks for your responses, Below steps helped me resolved
A) I deleted the images, containers, pods related to the ingnix.
B) Used server destroy
C) Redployed.

This helped me resolve the issue.
