### ISSUE TITLE
Re-enable upstream devfile registry on workspaces.openshift.com

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20437]
### Is your task related to a problem? Please describe

The upstream devfile registry has been disabled due to a regression in CRW 2.10.1 - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#_differences_between_eclipse_che_and_codeready_workspaces

### Describe the solution you'd like

As part of this re-enable the registry again and remove the warning from the docs - `The community-supported devfile registry has been temporarily disabled on the Eclipse Che hosted by Red Hat due to a defect in the product. This devfile registry will be re-enabled for Hosted Che with the upcoming release in September 2021.` https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#_differences_between_eclipse_che_and_codeready_workspaces

### Additional context

The upstream devfile registry should be 7.36.0 
The way to enable it is to update the CR accordingly:

```
      externalDevfileRegistries:
        - url: 'https://eclipse-che.github.io/che-devfile-registry/7.36.0/'
      externalDevfileRegistry: false
```

### Release Notes Text

All languages stacks have been re-enabled on Che hosted by Red Hat (https://workspaces.openshift.com)

**Comment by ibuziuk** [comment]
Looks like the regression is still in place and we will need to wait till the next CRW 2.12 release (October 2021) - https://issues.redhat.com/browse/CRW-2116

**Comment by nickboldt** [comment]
sync'd to Red Hat JIRA https://issues.redhat.com/browse/CRW-2553
