### ISSUE TITLE
Quarkus sample does not work with latest devworkspace controller

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#20439]
### Describe the bug

Here's the quarkus sample devfile https://github.com/che-samples/quarkus-quickstarts/blob/devfilev2/devfile.yaml.  As far as I understand, there is now devfile v2 validation webhook in devworkspace-controller. 
This validation fails because there are 2 endpoints with same name "hello-greeting-endpoint". If I rename one endpoint, the validation fails again because 2 endpoints have same target port. If I remove one of them completely, it passes.

### Che version

next (development version)

### Steps to reproduce

1. deploy with devworkspaces
2. start quarkus sample
3. see failure

### Expected behavior

sample devfile must work

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by benoitf** [comment]
should be solved now by https://github.com/che-samples/quarkus-quickstarts/commit/ceebce65c1c72fe11bd21e47553d66f0634790aa
