### ISSUE TITLE
Theia fails to load plugins when it's run as DevWorkspace on OpenShift behind OAuth

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20448]
### Describe the bug

Theia fails to load plugins when it's run as DevWorkspace on OpenShift behind OAuth

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che with DevWorkspace on OpenShift.
2. Run any Theia based workspace.
3. Toggle Plugins view

### Expected behavior

Plugins are displayed.

### Runtime

OpenShift

### Screenshots

![Screenshot_20210909_161100](https://user-images.githubusercontent.com/5887312/132692538-90e4b459-58ac-4293-8a8a-ee332074342d.png)
![Screenshot_20210909_161128](https://user-images.githubusercontent.com/5887312/132692543-1700daa6-0c49-42aa-8303-0dceb6181580.png)
![Screenshot_20210909_161431](https://user-images.githubusercontent.com/5887312/132692545-a9d5ba68-5d1c-4da8-a4ad-7f8fcf4e7024.png)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

### Additional context

OpenShift 4.8 on RHPDS

**Comment by svor** [comment]
It is also reproducible on Minikube (v1.22.0):
![screenshot-192 168 49 2 nip io-2021 09 24-10_47_50](https://user-images.githubusercontent.com/1271546/134639527-989d9cc0-910a-47e5-a78f-38d9322fefbb.png)
