### ISSUE TITLE
quarkus devfile v2 sample is broken

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20445]
### Describe the bug

quarkus devfile v2 sample is broken
![Screenshot_20210908_143105](https://user-images.githubusercontent.com/5887312/132503878-7708a698-829e-494a-a499-fa06faf297ad.png)

### Che version

next (development version)

### Steps to reproduce

screenshot says more than enough

### Expected behavior

it works

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by sparkoo** [comment]
duplicate of https://github.com/eclipse/che/issues/20439 ?

**Comment by benoitf** [comment]
dup of https://github.com/eclipse/che/issues/20439 (and it should be fixed now)
