### ISSUE TITLE
Unable to request plugins/devfiles without authentication

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20449]
### Describe the bug

Devfile and Plugin Registries used to be publicly available, but with Native authentication, it's not the case anymore, which lead to complexity for some components, but it's not really clear if it's requirement or not.

And there are corner cases which may be fully broken by that change, like when in-cluster communication is not allowed.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che with DevWorkspaces enabled on OpenShift.
2. Try to curl devfile or plugin registry

### Expected behavior

Content is received

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by sparkoo** [comment]
we've agreed that registries should be accessible without authentication. It should be doable with `-bypass-auth-for` or `-skip-auth-regex` on openshift/oauth-proxy https://github.com/openshift/oauth-proxy/blob/master/README.md#command-line-options.

On upstream oauth2-proxy, it's `--skip-auth-route` https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#command-line-options
