### ISSUE TITLE
Recursive ssh import does not work

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2045]
**Reproduction Steps:**
1. Try to import recursively a project (e.g. git@github.com:idexmai/ProjectGitSubmodule.git)

**Expected behavior:**
the project should be imported.

**Observed behavior:**
recursive importing does not work by ssh url.

**Che version:**    4.7.0  
**OS and version:** Ubuntu 14.04  
**Docker version:** 1.11.1  
**Che install:**   local bundle  

**Additional information:**
See attachment.
![imp_recursive_ssh](https://cloud.githubusercontent.com/assets/5408906/17395167/bb27893a-5a35-11e6-8984-2082f31e0c4f.png)

**Comment by JamesDrummond** [comment]
@artaleks9 Provide status label.
