### ISSUE TITLE
Create a new olm channel in order to deploy Eclipse Che next version using DWO dependency and installMode: AllNamespaces

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#20455]
### Is your task related to a problem? Please describe

Actaully we have stable-all-namespaces olm channel which deploy eclipse che in AllNamespace mode and with DWO dependency. The problem is we don't have a way to deploy che next in All Namespace mode with DWO olm dependency		

### Describe the solution you'd like

Create a new channel `next-all-namespaces` to deploy che in AllNamespace mode. This channel as next will not be pushed to community operators.

**Comment by l0rd** [comment]
Ok so someone could use that channel doing:

```bash
chectl update next && \
chectl server:deploy  \
           --installer=olm --platform=openshift --olm-channel=next-all-namespaces
```

Hence a couple of questions:

- Manually adding the che catalog source will be a prerequisite to use that command?
- Does it make sense to remove `chectl` option `--workspace-engine`? I am asking because  `--olm-channel` choice will also decide the workspace engine. And anyway at some point the devworkspcae will be the only choice.

**Comment by flacatus** [comment]
@l0rd 
Sorry for delay.
> Manually adding the che catalog source will be a prerequisite to use that command?
No, the chectl will add automatically the catalog for you in the cluster

> Does it make sense to remove chectl option --workspace-engine? I am asking because --olm-channel choice will also decide the workspace engine. And anyway at some point the devworkspcae will be the only choice

To be honest we can remove this flag and use the channel to install the new devworkspace engine

**Comment by l0rd** [comment]
> To be honest we can remove this flag and use the channel to install the new devworkspace engine

@flacatus ok but maybe we will still need `--workspace-engine` for Kubernetes clusters that do not have OLM? Not sure what's the best way to handle that.

**Comment by flacatus** [comment]
Ok, Maybe is better to mantain the flag until the devworkspace engine will be by default also in pure kubernetes.
