### ISSUE TITLE
Adapt Che-Theia Activity Tracker extension to DevWorkspace mode

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20460]
### Is your enhancement related to a problem? Please describe

Currently, DevWorkspaces are not idled by timeout.

### Describe the solution you'd like

We agreed to cover that is currently working for workspaces powered by Che Server workspace engine. As it's relatively cheap to do. So, it's needed to adapt the activity Theia plugin to be run in DevWorkpsace mode, there is should report their activities to Che Machine Exec instead of Che Server. It's POST without body to `/activity/tick` API path
![Screenshot_20210913_153252](https://user-images.githubusercontent.com/5887312/133084159-d3ceda7f-e4bc-43a9-86dc-42bd1db21535.png)

### Describe alternatives you've considered

The alternative is to handle that on Che level but not editor, but it's something we plan to do in https://github.com/eclipse/che/issues/20345

**Comment by azatsarynnyy** [comment]
Let me know once an endpoint on Machine Exec side is ready.

**Comment by sleshchenko** [comment]
@azatsarynnyy It's already there

**Comment by azatsarynnyy** [comment]
Thanks! We'll look at it next sprint.

**Comment by azatsarynnyy** [comment]
@vzhukovs could you give a brief update on the state of the work - what has been done and what problems still need to be solved?
