### ISSUE TITLE
Updating certificates in Eclipse che is not picked by the workspace.

### ISSUE THREAD

**Issue by benitonfdo** [eclipse-che/che#20613]
### Summary

Hi, 

I am trying to update the certificate for my Che Server. 

I have deployed it with cheHost & cheHostTLSSecret.  
To update I patched the 'che-tls' secret with an updated certificate. as below

TLS_KEY=$(base64 < "./certkey.pem" | tr -d '\n')

TLS_CRT=$(base64 < "./doc.crt" | tr -d '\n')

kubectl patch secret che-tls -n cloud -p "{\"data\":{\"tls.key\":\"${TLS_KEY}\",\"tls.crt\":\"${TLS_CRT}\"}}"

My operator.yml
server:
    cheHost: 'xyz.abc.com'
    **cheHostTLSSecret**: 'domain-tls'
 k8s:
    ingressDomain: 'xyz.abc.com'
    **tlsSecretName**: 'che-tls'

After updating certificates it is loading the Eclipse che. But when i try the start the workspace it is failing as the workspace is not picking the correct certificate.

Is there anything I am missing to update when updating the certificates? Any help or pointer would be helpfiul.

### Relevant information

OS : MacOS
Browser: Chrome
Che version: 7.34.x

**Comment by tolusha** [comment]
stop & start a worspace
che-server must propagate a new certificate into the workspace

**Comment by benitonfdo** [comment]
Hi @tolusha,

I have stopped and started the workspace but still it is the same. This issue occurs in MacOS + Chrome browser.

In Windows and MacOS + FF it is working fine.

And it fails on websocket call.

**Comment by tolusha** [comment]
@benitonfdo 
Could you check if `che-tls` secret in `eclipse-che` namespace and `workspace<id>-che-tls` secret are the same?
if not, try 
1. stop a workspace
2. remove the secret from a workspace namespace
3. start a workspace

**Comment by tolusha** [comment]
Operator can't sync configmap because it is stuck with reconciliation error

```
time="2021-10-20T06:18:44Z" level=error msg="Stderr: Picked up JAVA_TOOL_OPTIONS: -Duser.home=.\nLogging into http://0.0.0.0:8080/auth as user admin of realm master\nInvalid user credentials [invalid_grant]\nPicked up JAVA_TOOL_OPTIONS: -Duser.home=.\nNo server specified. Use --server, or 'kcadm.sh config credentials or connection'.\nPicked up JAVA_TOOL_OPTIONS: -Duser.home=.\nNo server specified. Use --server, or 'kcadm.sh config credentials or connection'.\n"
```

Have you reconfigured keycloak in some way?

**Comment by benitonfdo** [comment]
I am still facing this issue. I am not sure how to reopen this issue.
