### ISSUE TITLE
Eclipse che not working in clients machine

### ISSUE THREAD

**Issue by svigneshvikki** [eclipse-che/che#2062]
[Eclipse che not working in clients machine, with the 32768-65535 ports are open]

**Reproduction Steps:**
1. [runned the cmd with remote ip parameter]
2. [started the project and in my local successfully]
3. [try it on my client machine it wont work]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[window.IDE.eventHandlers.initializationFailed@http://10.74.154.144:8080/ide/wksp-test?uid=325635:39......]

**Che version:**    [4.4.2]  
**OS and version:** [windows 10]  
**Docker version:** [1.10.3]  
**Che install:**    [Codenvy]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ghost** [comment]
@svigneshvikki can you confirm `10.74.154.144` is accessible from another machine?

This should be an externally accessible IP.

**Comment by svigneshvikki** [comment]
yes it is accessible, even the dashboard is visible in the client machine. but, project's are not able to create or run.

**Comment by svigneshvikki** [comment]
I have also attached the screenshot when error occurs while opening the project
![error](https://cloud.githubusercontent.com/assets/20900629/17480900/cf6dd2ea-5d97-11e6-9328-7b2cad1c3da4.jpg)

**Comment by TylerJewell** [comment]
@svigneshvikki - this may be a websocket access problem. Can you run one more test that verifies web socket connectivity from the browser to the workspace and back?

**Comment by TylerJewell** [comment]
@svigneshvikki - I just experienced this on a Mac device. This happens on Docker for Mac beta due to some limitations in the way that it is currently structured.  Since you are on Windows 10, I recommend doing the following:
1. Install docker for windows - it will get you on Docker 1.12 which is a lot more stable.
2. You can then get some additional utilities and a simpler way to start che 4.6.1.  It will address any sort of multi-host scenarios that you may need to encounter.  [Try this syntax](https://eclipse-che.readme.io/docs/usage-docker#)

**Comment by svigneshvikki** [comment]
I tried this, but when run the che the
![java_home_error](https://cloud.githubusercontent.com/assets/20900629/17517757/7ab574e4-5e62-11e6-81bb-04d10869dd0f.jpg)
 error shown is :

**Comment by svigneshvikki** [comment]
I tried the above solution, the error shown is:
![docker_error_error](https://cloud.githubusercontent.com/assets/20900629/17517868/039de872-5e63-11e6-8b69-fa8e41f6b169.jpg)

**Comment by svigneshvikki** [comment]
Even I started with normal way it shows:
![java_home_error](https://cloud.githubusercontent.com/assets/20900629/17517900/2a2372f0-5e63-11e6-86d0-437331a2cc91.jpg)

**Comment by TylerJewell** [comment]
@svigneshvikki - it doesn't look like Docker for Windows was installed.  There is a difference between the Docker Toolbox for windows, which forces you to use VirtualBox and Docker for Windows, which has use of HyperV.  The Docker for Windows is a much faster & cleaner solution.  Managing virtualbox is quite the pain.  So you want this install, not the one you have.  This will solve the problem with running Che with the elegant syntax we gave :)
https://docs.docker.com/docker-for-windows/

**Comment by ghost** [comment]
@svigneshvikki let's deal with the original problem. It's fairly simple. 
On Windows, Docker runs in a virtual machine. When a workspace is loaded, the client tries to reach workspace agent (by the way can you please open browser console and share a screenshot - I am sure there are failed websocket requests there). When you run Che loally, this IP is available for the browser. When you reach Che from another machine, you need to make sure that the VM can be reached from within the network. In other words, the VM IP should be available from the machine you are using to access Che.

This is Windows/mac limitation for a "remote Che" scenario.

**Comment by svigneshvikki** [comment]
Here is the browser console screenshot,
![image](https://cloud.githubusercontent.com/assets/20900629/17557058/54c00c1e-5f33-11e6-9b70-9917c6da3bf4.png)

and cmd console screenshot,
![console output](https://cloud.githubusercontent.com/assets/20900629/17557085/71013ce0-5f33-11e6-89df-2bbe7558983a.jpg)

and one more thing my actual IP is 192.168.1.8 but it shows in cmd console is,

![image](https://cloud.githubusercontent.com/assets/20900629/17557174/d78307c8-5f33-11e6-8e73-3b002610f7c7.png)

**Comment by svigneshvikki** [comment]
may I know the update on this?

**Comment by ghost** [comment]
@svigneshvikki you need to make sure your VirtualBox is reachable in the network - as you can see 192.168.99.100 is unreachable for the client (browser you are using).

Here's a simpler use case for you to understand the problem.

SSH into the VM. Run apache or any other simple web server there. And try to reach it from another machine.

Solution: make sure VirtualBox gets a public IP or forward ephemeral port range in VirtualBox so that when you go to $MachineIP:$port you get forwarded into VirtualBox.

**Comment by TylerJewell** [comment]
@eivantsov - now that we have the docker launcher, when there are issues with the older versions running the default scripts, let's work to get people to update to the newer system, as it has many auto-detection and controls within it that solves some of the issues that @svigneshvikki is encountering.

@svigneshvikki - can you please upgrade to Che 4.6.2 and test using the product with the following syntax?  You will need to set the `CHE_HOST_IP` environment variable to the externally reachable IP address of your boot2docker VM, if you are still using that.

https://eclipse-che.readme.io/docs/usage-docker

**Comment by ghost** [comment]
@TylerJewell the new Docker syntax isn't a remedy here. The only issue @svigneshvikki faces is VM being reachable in the network. 

The new docker syntax is worth trying though :)

**Comment by svigneshvikki** [comment]
Hi team, the problem that I am facing now is the docker machine is configured to my ip address but it is unreachable. Please solve this issue.
![docker unable to connect](https://cloud.githubusercontent.com/assets/20900629/18157280/0d2c2dde-703a-11e6-83f4-58e8e8f7b6c3.jpg)

![cmd of che](https://cloud.githubusercontent.com/assets/20900629/18157358/8e85f1c6-703a-11e6-878b-3b7edf9d8c05.jpg)

**Comment by ghost** [comment]
@svigneshvikki can you remove all docker-machines and start anew?

Docker is broken in your Windows

**Comment by svigneshvikki** [comment]
I tried with new docker machine after removing the all docker machines, it initially gave the default ip 192.168.99.100 and then I configured it to my ip 192.168.1.100 in virtualbox and docker machine but it wont works.

![image](https://cloud.githubusercontent.com/assets/20900629/18301187/2353470c-74ed-11e6-9aee-c0734444d3cf.png)
![image](https://cloud.githubusercontent.com/assets/20900629/18301196/32939b4a-74ed-11e6-86d7-a235baae5de7.png)

**Comment by ghost** [comment]
@svigneshvikki this is a Docker configuration issue. Perhaps if you post this to Docker Forums you will get a faster response. Currently, docker is broken on your windows machine.

Can you try deleting all machines, and then in VBox settings > Network delete all host only adapters.

Then try Docker Quick Start again. Note that you should be able to run `docker ps` to verify docker is running.
