### ISSUE TITLE
Add "native update hook refresh option" to Yatta Profile

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#2063]
It is recommended (https://eclipse-che.readme.io/docs/setup-che-workspace),
so it would make sense to add it to the profile.

**Comment by zenobios** [comment]
We updated the profile to enable this preference by default.

**Comment by bmicklea** [comment]
@zenobios - so this fixed and can be closed?  Or is there more to do?

**Comment by slemeur** [comment]
Tested on two various computers (two Macs).

1st: it requires to restart Eclipse in order to continue the installation flow.
2nd: it worked perfectly and smoothly. Didn't require any restart.

Frederic from Yatta is investigating this issue.
