### ISSUE TITLE
Deploying Che

### ISSUE THREAD

**Issue by wbondarchuk** [eclipse-che/che#20643]
### Summary

Hello everyone, my university allocates me a server and wants to deploy Eclipse Che+Eclipse Theia there in order to then work with the web-ide, and the system should be multi-user. Please tell me, can I use Kubespray for this task and deploy a local multi-user system on my server, or do I need to use Google or Microsoft clouds?

**Comment by tolusha** [comment]
@wbondarchuk 
You can use any preferable platform 
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che/
