### ISSUE TITLE
che-launcher based provisioning with Vagrant doesn't restart the server

### ISSUE THREAD

**Issue by creckord** [eclipse-che/che#2066]
Using the new `che-launcher`based server startup with Vagrant, the server does not start when restarting the vagrant machine.

**Reproduction Steps:**
1. Get Vagrantfile from https://raw.githubusercontent.com/eclipse/che/master/Vagrantfile
2. Run `vagrant up`and ignore vagrant error message at the end
3. Check that the Che server is running afterwards
4. Stop the vagrant machine, either with `vagrant halt`, through VirtualBox, or by rebooting the host
5. Restart the vagrant machine with `vagrant up`

**Expected behavior:**

The Che server is up and running

**Observed behavior:**

The Che server is not restarted when restarting the Vagrant machine.

Before the move to che-launcher, the docker container for the Che server was created with `--restart=always`, so it would get started automatically when the VM was booted and/or when the server process exited for some reason. With the new `che.sh` and the `che-launcher` container, this is no longer the case.

Depending on what the user story is for interacting with the `che.sh` startup script, this is probably entirely intentional and makes sense in a native docker environment. In the Vagrant case however, the main interaction point is the vagrant CLI. So one would expect everything to come up with a `vagrant up`.

Possible solutions could be
- (Re-)Adding the `--restart=always` flag to the container creation command in `start_che_server()`
- Conditionally creating the server container with `--restart=always` only in the Vagrant case
- Adding a server startup/status check call to the Vagrantfile in `script2`, which runs on every `vagrant up`

**Che version:**    see Additional Information
**OS and version:** Windows 7 SP1 (Host), CentOS Linux release 7.2.1511 (Core) (Vagrant Box)
**Docker version:** 

``` Shell
[vagrant@vagrant ~]$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64
```

**Che install:**    Vagrant

**Additional information:**

``` Shell
[vagrant@vagrant ~]$ docker run -t --name "che-launcher" -v /var/run/docker.sock:/var/run/docker.sock $(get_list_of_variables) codenvy/che-launcher:latest info                                                                               ip: can't find device 'eth0'
DEBUG: ---------------------------------------
DEBUG: ---------  CHE DEBUG INFO  ------------
DEBUG: ---------------------------------------
DEBUG:
DEBUG: ---------  PLATFORM INFO  -------------
DEBUG: DOCKER_INSTALL_TYPE       = native
DEBUG: DOCKER_HOST_OS            = CentOS Linux 7 (Core)
ip: can't find device 'eth0'
DEBUG: DOCKER_HOST_IP            =
DEBUG: DOCKER_DAEMON_VERSION     = 1.12.0
DEBUG:
DEBUG:
DEBUG: --------- CHE INSTANCE INFO  ----------
DEBUG: CHE CONTAINER EXISTS      = YES
DEBUG: CHE CONTAINER STATUS      = running
DEBUG: CHE SERVER STATUS         = running
DEBUG: CHE IMAGE                 = codenvy/che-server:latest
DEBUG: CHE SERVER CONTAINER ID   = 332610b65718
DEBUG: CHE CONF FOLDER           = /home/user/che/conf
DEBUG: CHE DATA FOLDER           = /home/user/che/workspaces
DEBUG: CHE DASHBOARD URL         = http://localhost:8080
DEBUG: CHE API URL               = http://localhost:8080/api
DEBUG: CHE LOGS                  = run `docker logs -f che-server`
DEBUG:
DEBUG:
DEBUG: ----  CURRENT COMMAND LINE OPTIONS  ---
DEBUG: CHE_PORT                  = 8080
DEBUG: CHE_VERSION               = latest
DEBUG: CHE_RESTART_POLICY        = no
DEBUG: CHE_USER                  = root
DEBUG: CHE_HOST_IP               =
DEBUG: CHE_LOG_LEVEL             = info
DEBUG: CHE_HOSTNAME              = localhost
DEBUG: CHE_DATA_FOLDER           = /home/user/che
DEBUG: CHE_CONF_FOLDER           = not set
DEBUG: CHE_LOCAL_BINARY          = not set
DEBUG: CHE_SERVER_CONTAINER_NAME = che-server
DEBUG: CHE_SERVER_IMAGE_NAME     = codenvy/che-server
DEBUG:
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
Error: No such container: f0c6a26187995745aae94841c8fb2a148803ee131bc5083ef66d586812173c4a
```
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@creckord - good catch.  Looking at solutions here.  We'd like to consider discontinuing the Vagrant installer entirely.  If we no longer supported this form of installation with each release, would that be a problem for Yatta?  If it is, then we'll maintain it.

**Comment by TylerJewell** [comment]
@creckord - here is a PR that addresses the issues - system should run better now.
https://github.com/eclipse/che/pull/2085

**Comment by creckord** [comment]
@TylerJewell thank you :) 

Regarding the future of the Vagrant installer - I think it would be good to keep it. Yatta will support native Docker for systems that support it, but that leaves out older Windows versions. 

We could switch from Vagrant to Docker Toolbox there, but automatic installation of Docker Toolbox proves to be a much more fickle beast, because its installer is essentially a blackbox and it tries to install a lot of other systems, which the user might or might not already have.
