### ISSUE TITLE
How to debug che source code in windows?

### ISSUE THREAD

**Issue by qeesung** [eclipse-che/che#2070]
I want to debug the eclipse che source code in my windows intellij IDEA. But I do not know how to debug local or remote.

I cloned the repo into my linux machine, then  `cd assembly && mvn clean install` to  complile assembly. then I get the target and execute `./che.sh -d` to start the che server.

Now I can only debug the `assembly-ide-war` through port `8000` In my intellij. But if I want to debug `docker plugin` or `ws-master`  local or remote.m what  should I configure?  what debug ports should I use?

thx a lot.

**Comment by TylerJewell** [comment]
Hi!  Take a look at this page in the docs dedicated to getting your IDE setup to author plugins.   This is how we do some of our debugging.https://eclipse-che.readme.io/docs/setup-che-workspace

Can you tell us a bit about what you are working on?

**Comment by qeesung** [comment]
@TylerJewell Thanks a lot，this debugging document does not seem to be what I want. I am trying to learning eclipse che source code , and want to extend a openshift plugin  for workspace. But I still don't find a way to debug in a highly efficient and useful way. T_T. In other words, if I want to extend a new plugin, how to debug in a highly efficient and useful way?

**Comment by ghost** [comment]
@qeesung what's the problem with debugging docker plugin? It is deployed with a workspace master, so, running Che in a debug mode and connecting to port 8000 should be enough.

**Comment by qeesung** [comment]
@eivantsov Thanks a lot.I have solved my problem.8000 port is correct.^_^
