### ISSUE TITLE
Scroll to bottom automatically doesn't work in Consoles while starting a workspace

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#2075]
No automatic scroll in console while starting workspace, when "Scroll to bottom automatically" is set.

**Reproduction Steps:**
1. Create a workspace
2. Open it in IDE

**Expected behavior:**
Workspace starting logs should scroll automatically

**Observed behavior:**
No automatic scroll

**Che version:**   4.7.0-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** Docker version 1.11.2
**Che install:**   server (zip)

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes
  ![noscrollondockerbuild](https://cloud.githubusercontent.com/assets/15607393/17511947/0beb801e-5e2e-11e6-95a1-f530625c9185.gif)

**Comment by slemeur** [comment]
Cannot reproduce
