### ISSUE TITLE
Issue building Che with custom plugin - Project extension doesn t appear

### ISSUE THREAD

**Issue by lgas** [eclipse-che/che#2077]
Hello, 
I coded a groovy plugin based on the json example tutorial. Like exactly the same. 
Then I build che with my plugin. When I run it, only editor et file extension seems to be added to che (my resource icon appears when i create .groovy file). I can t add a groovy project to workspace.

For build it, I add groovy-ide and groovy-shared packages to assembly-ide-war pom and the groovy.gwt.xml to IDE.gwt.xml. I also add groovy-server and groovy-shared to assembly-wsagent-war.
Then, I run, mvn clean install in /assembly folder, and che.sh in assembly-main/target.

I checked other plugins (code, dependencies, etc) and I don t understand what differs about mine.
Any help would be appreciate. Thanks

**Che version:**    4.7.0-SNAPSHOT  
**OS and version:** Ubuntu 16.04  
**Docker version:** 1.11.2  
**Che install:**    from sources

**Comment by TylerJewell** [comment]
@ddementieva @RomanNikitenko

**Comment by ghost** [comment]
@lgas looks like running mvn clean install in `/assembly` isn't enough. You need to rebuild all modules that you were making edits in (I suppose you have added dependencies to pom and GWT inheritance)

**Comment by lgas** [comment]
I edited /assembly-ide-war, pom and IDE.gwt.xml (for groovy-ide & groovy-shared) -> mvn clean install
I also edited /assembly-wsagent-war, pom (for groovy-server & groovy-shared) -> mvn clean install
Then run mvn clean install on /assembly and run /bin/che.sh but my project type still not showing up.  

I would like to create a groovy project from workspace/create project window.

**Comment by ddementieva** [comment]
@lgas can you share the source code of your plugin?

**Comment by lgas** [comment]
I have two classes in che-plugin-groovy-server

`public class GuiceModule extends AbstractModule{
    @Override
    protected void configure() {
        Multibinder<ProjectTypeDef> projectTypeDefMultibinder = newSetBinder(binder(),ProjectTypeDef.class);
        projectTypeDefMultibinder.addBinding().to(GroovyProjectType.class);
    }
}`

`public class GroovyProjectType extends ProjectTypeDef {
    @Inject
    public GroovyProjectType() {
        super(GROOVY_PROJECT_TYPE_ID, "GROOVY", true, true);
        addConstantDefinition(LANGUAGE, LANGUAGE, GROOVY_PROJECT_TYPE_ID);
    }
}`

**Comment by ddementieva** [comment]
@lgas Do you have it somewhere as a git repo? We would like to create an assembly and check for errors.

**Comment by lgas** [comment]
yes
https://github.com/lgas/che-plugin-groovy

**Comment by lgas** [comment]
Hi @ddementieva, 
any news about the issue ?

**Comment by ddementieva** [comment]
@lgas You also need to register your Groovy project type in the IDE wizard. 

You may want to take a look at how it's done for C and C++ project types: 
- Wizard pages for C and C++ project types: https://github.com/eclipse/che/tree/master/plugins/plugin-cpp/che-plugin-cpp-lang-ide/src/main/java/org/eclipse/che/plugin/cpp/ide/project 
- Registering wizard pages in the IDE: https://github.com/eclipse/che/blob/master/plugins/plugin-cpp/che-plugin-cpp-lang-ide/src/main/java/org/eclipse/che/plugin/cpp/ide/inject/CppGinModule.java#L40

**Comment by lgas** [comment]
@ddementieva I made it without results.
I pushed it to my repo.

**Comment by ddementieva** [comment]
@lgas It seems it's also necessary to mark GroovyGuiceModule class with org.eclipse.che.inject.DynaModule annotation.

Also uncomment the following dependency declaration in the che-plugin-groovy-server/pom.xml:

```
<dependency>
        <groupId>org.eclipse.che.core</groupId>
        <artifactId>che-core-commons-inject</artifactId>
</dependency>
```

**Comment by lgas** [comment]
It's finally working !
Thank you very much for your help.
