### ISSUE TITLE
Orion editor - Highlight issue

### ISSUE THREAD

**Issue by lgas** [eclipse-che/che#2078]
Hi,
I coded a Groovy plugin and highlight doesn t working.
I registered my file extension, che recognize it because it opens the "good" editor when i create a .groovy file.

For highlight, i went in org.eclipse.che.ide.api.editor.filetype.ExtensionFileTypeIdentifier, as mentioned in jsonsampleplugin tutorial, for add my extension but saw that Orion already handle it :
`this.mappings.put("groovy", Collections.singletonList("text/x-groovy"));`

So, for me, it seems to be ok. 
What did i miss ?

**Comment by ddementieva** [comment]
@lgas There is no syntax highlighting for .groovy files in the Orion. You can check it on the Orionhub.

So you may need to add a custom syntax highlighting for this particular file extension, something like https://github.com/eclipse/che/pull/1392

**Comment by lgas** [comment]
Okay thanks you, i ll check that.
But can you explain me what, "this.mappings.put("groovy", Collections.singletonList("text/x-groovy"));" in ExtensionFileTypeIdentifier, is about ?
Is that a preset that will bind my new syntax highlighting with my file extension ?

**Comment by ddementieva** [comment]
@lgas This mapping will work when Orion adds syntax highlighting for .groovy files.

In the meantime, you need to add a custom syntax highlighting for this file type.

**Comment by TylerJewell** [comment]
Closed due to it being resolved.
