### ISSUE TITLE
Registry disappears from admin section

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2082]
So - just learning Eclipse Che and added a registry in admin section.
I was just practicing -> so I've entered my dockerhub auth data.

Now -> at some point registry disappeared:  
http://i.imgur.com/a3lwldS.png  

However I cannot start the wokspace anymore, I get this: error message: 

[default] [DOCKER] Step 1 : FROM codenvy/ubuntu_android
[default] [DOCKER] [ERROR] Get https://registry-1.docker.io/v2/codenvy/ubuntu_android/manifests/latest: toomanyrequests: too many failed login attempts for username or IP address
[default] [ERROR] Docker image build failed. Image id not found in build output.

**Comment by TylerJewell** [comment]
@ddementieva @eivantsov - this looks like an interesting issue.  Can you cc the engineers that worked on this part for investigation?  Haven't seen something like this before.

**Comment by linuxd3v** [comment]
This is a paid dockerhub account with private dockers support. Not sure if this matters.

**Comment by TylerJewell** [comment]
Once private registry access is setup - should maintain that and work ok.  

If you are using che - my concern is that you didn't export the CHE_DATA_FOLDER - so if you reran the container, then maybe configuration data was not saved in between runs.

**Comment by ghost** [comment]
@loganto how did you run Che? Natively as a server or as a Docker container?

Are you certain credentials are OK? With DockerHub account configured, we send credentials in request headers. So, this response from DockerHub API is quite normal if you fail to login several times in a row.

**Comment by linuxd3v** [comment]
@eivantsov in a docker container. Host is Ubuntu 16.04 LTS.  
To my knowledge creds are ok - > Im pulling work containers on daily basis.

**Comment by linuxd3v** [comment]
@eivantsov @ddementieva 

Yeah - I can consistently reproduce this issue.  
I just went ahead and removed all Che containers, then I've restarted che container like this:  

> docker run \
>     --rm -t \
>     --name che-launcher-jc \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -e CHE_PORT=3005 \
>     -e CHE_DATA_FOLDER:/srv/che/jcarter \
>     codenvy/che-launcher:nightly start

Then I went into administration and added a registry:  
http://i.imgur.com/ZvYk3RD.png   

`Ctr+R` to refresh to simply refresh the page, registry is gone:  
http://i.imgur.com/3HT6MSS.png

**Comment by ddementieva** [comment]
@loganto Bug confirmed.

**Comment by uraniumsteel** [comment]
I am experiencing this same issue.
I created a workspace in bitnami che with script -worked fine.
Deleted workspace
Recreated workspace - getting this exact error

FROM gcr.io/stacksmith-images/ubuntu-buildpack:14.04-r9

MAINTAINER Bitnami containers@bitnami.com

RUN echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

ENV  STACKSMITH_STACK_ID="u9fs9c0" \
    STACKSMITH_STACK_NAME="Ruby for bitnami/bitnami-docker-laravel" \
    STACKSMITH_STACK_PRIVATE="1" \
    BITNAMI_APP_NAME=laravel \
    BITNAMI_APP_VERSION=5.2.31 \
    LARAVEL_ENV=development \
    BITNAMI_IMAGE_VERSION=5.2.31-r5 \
    PATH=/opt/bitnami/java/bin:/opt/bitnami/node/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/top/bitnami/mongodb/sbin:/opt/bitnami/mongodb/bin:/opt/bitnami/common/bin:~/.composer/vendor/bin:$PATH \
    NODE_PATH=NODE_PATH=/opt/bitnami/node/lib/node_modules

# Install java dependency

RUN bitnami-pkg install java-1.8.0_91-0 --checksum 64cf20b77dc7cce3a28e9fe1daa149785c9c8c13ad1249071bc778fa40ae8773

# Install Laravel related dependencies

RUN bitnami-pkg install node-6.3.0-0 --checksum f2997c421e45beb752673a531bf475231d183c30f7f8d5ec1a5fb68d39744d5f
RUN bitnami-pkg install php-7.0.10-0 --checksum 5f2ec47fcfb2fec5197af6760c5053dd5dee8084d70a488fd5ea77bd4245c6b9
RUN bitnami-pkg install mariadb-10.1.14-4 --checksum 4a75f4f52587853d69860662626c64a4540126962cd9ee9722af58a3e7cfa01b -- --password=laravelSample --username=laravelSample --database=laravelSample
RUN bitnami-pkg unpack mongodb-3.2.9-0 --checksum 367db26aa2b687e8a389073809602412bde95d5800f655f4221ab39dc251cd1f
RUN npm install -g gulp

RUN mkdir /tmp/laravel-sample && cd /tmp/laravel-sample && composer create-project "laravel/laravel=5.2.31" /tmp/laravel-sample --prefer-dist
CMD ["nami", "start", "--foreground", "mongodb"]
CMD ["nami", "start", "--foreground", "mariadb"]
VOLUME ["/bitnami/mongodb"]

EXPOSE 3000

LABEL che:server:3000:ref=laravel che:server:3000:protocol=http

USER bitnami
WORKDIR /projects

#Adding useful environment variables for enabling functionality
ENV TERM=xterm \
    DB_HOST=127.0.0.1 \
    DB_USERNAME=laravelSample \
    DB_DATABASE=laravelSample \
    DB_PASSWORD=laravelSample
    MONGODB_USERNAME=my_user
    MONGODB_PASSWORD=password123
    MONGODB_DATABASE=my_database

CMD ["tail", "-f", "/dev/null"]
