### ISSUE TITLE
Write documentation about LanguageServer support status

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#2088]
Need to describe current state and planned features for LanguageServer support

**Comment by TylerJewell** [comment]
@evidolob - plesae just keep the epic up to date.  https://github.com/eclipse/che/issues/1287
Let's not create an issue just to keep another issue up to date :)

**Comment by gazarenkov** [comment]
I asked for this since we are (with @TylerJewell) not sure #1287 is good enough to appropriate tracking the project. Probably, new, more clear issue will be created as a result of it.
Let's keep going please.
