### ISSUE TITLE
Pasting in multiple lines of text in che IDE console terminal creates extra lines.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2092]
Pasting in multiple lines of text into console add extra blank line between each line of text pasted.

**Reproduction Steps:**
1. Copying multiple lines of text from a text editor of your choice on local machine or copying code from web page. 
2. In Che console paste the multiple lines of text into a terminal.

example lines to copy

```
echo Line 1
echo Line 2
echo Line 3

```

**Expected behavior:**

Each line of text pasted in runs sequentially. 

```
user@4a757c66cd52:/projects$ echo Line 1
Line 1
user@4a757c66cd52:/projects$ echo Line 2
Line 2
user@4a757c66cd52:/projects$ echo Line 2
Line 3
user@4a757c66cd52:/projects$
```

**Observed behavior:**

Each line of text is proceeded by a blank line/extra return.

```
user@4a757c66cd52:/projects$ echo Line 1                                                                
Line 1                                                                                                  
user@4a757c66cd52:/projects$                                                                            
user@4a757c66cd52:/projects$ echo Line 2                                                                
Line 2                                                                                                  
user@4a757c66cd52:/projects$                                                                            
user@4a757c66cd52:/projects$ echo Line 3                                                                
Line 3                                                                                                  
user@4a757c66cd52:/projects$                                                                            
user@4a757c66cd52:/projects$
```

**Che version:**  4.7.0-SNAPSHOT  
**OS and version:** Google cloud. Ubuntu 1.16  
**Docker version:** 
 Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
**Che install:**  
Google cloud with CLI `sudo docker run -t -v /var/run/docker.sock:/var/run/docker.sock --env CHE_HOST_IP=$(curl -s https://4.ifcfg.me/) --env CHE_VERSION=nightly --env CHE_CONF_FOLDER=$PWD --env CHE_PORT=80 codenvy/che-launcher:nightly start`

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by musienko-maxim** [comment]
Cannot reproduce on version 5.6.0
