### ISSUE TITLE
Cannot regain last ssh sessions after refresh

### ISSUE THREAD

**Issue by t-oss** [eclipse-che/che#2094]
SSH session will be lost after refresh.
3 cases here:
1) Everytime refresh, new "Terminal" ssh session created, and the last terminal ssh go background
2) Everytime refresh, ssh session created by "CMD Widget" can be restored if cmd uncomplete, but output cannot be restored.
3) Project importing status will lost after refresh.

Case 1:
  **Reproduction Steps:**
    1) Excute some cmd in "Terminal" (or some other ssh) manually.
    2) Refresh
  **Expected behavior:**
    Terminal session and output will be restored,  
  **Observed behavior:**
    A new terminal session created, and last terminal session go background.
    For example, if we type vi cmd, and then refresh, vi will go background, and cannot be recalled.

Case 2:
  **Reproduction Steps:**
    1) Excute some cmd from "CMD Widget".
    2) Refresh
  **Expected behavior:**
    Terminal session and output will be restored,  not only for uncomplete CMD, but also for completed CMD
  **Observed behavior:**
    If CMD not complete, session can be restored, but only output after page loaded will be shown.
    If CMD competed, session cannot be restored, developer will missing the PASS/FAIL output

Case 3:
  **Reproduction Steps:**
    1) Import some project from VCS, such as github.
    2) Refresh
  **Expected behavior:**
    Importing status can be restored
  **Observed behavior:**
    Once refresh, importing task will go background, only project folder can be seen, and no importing status will be shown or popup. user cannot confirm whether the import is successfull or not.

**Che version:**   Che packaged with Codenvy 4.6.1  
**OS and version:** CentOS 7.2  
**Docker version:** 1.11.1, build 5604cde
**Che install:**    Codenvy

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ghost** [comment]
Labeling this as enhancement. Terminal sessions are not restored indeed.
