### ISSUE TITLE
Wrong behavior while creating project from maven archetype

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2098]
**Reproduction Steps:**
1. Run workspace
2. Click on 'Workspace'-> 'Create Project...' in the top menu
3. Select 'Maven' type of project  and enter name
4. Click on 'Next' and select any archetype.

**Expected behavior:**
Project has been created and it  match selected archetype.

**Observed behavior:**
Project has been created, but it does not match selected archetype.
![archetype](https://cloud.githubusercontent.com/assets/8051404/17589547/1a6c4d74-5fde-11e6-9c3a-98511f84d160.png)

**Che version:**   4.7.0-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**    local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
