### ISSUE TITLE
Che launcher debug prints wrong port / hostname for running server if variables change

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2102]
The debugging output of che-launcher is wrong if you have a running server whose CHE_HOSTNAME or CHE_PORT values change after the server was started.

**Reproduction Steps:**
1. Start che with launcher.
2. Set CHE_HOSTNAME or CHE_PORT to a value that is not the value of the currently running server.
3. Run `che info`

Gives wrong PORT & HOSTNAME values for the running server.

This is the offending code:
https://github.com/eclipse/che/blob/master/dockerfiles/che-launcher/launcher_cmds.sh#L121-L122

@l0rd - do you have a clever way to interrogate a running che-server container to find out which hostname and port it is using instead of inheriting from environment variables?

**Comment by l0rd** [comment]
I think we have 2 options here:
- Set the hostname to `$DEFAULT_CHE_HOSTNAME` and get the port using the command `docker inspect --format='{{ (index (index .NetworkSettings.Ports "8080/tcp") 0).HostPort }}' ${CHE_SERVER_CONTAINER_NAME}`
- Write a `.che-launcher` file (that could be stored in `CHE_DATA_FOLDER`) where all the launcher options are written whe `che` is running.

The first option is the easiest to implement (and I probably prefer it right now). The second option has the benefit to be more reliable and make the `restart` command consistent too.
