### ISSUE TITLE
Problem authenticating on github

### ISSUE THREAD

**Issue by klsorge** [eclipse-che/che#2104]
I am having a problem connecting to github.com with my local che instance. I have followed the directions on https://eclipse-che.readme.io/docs/git and started my che instance with the following docker command:

`$ docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_CONF_FOLDER=/path/to/config codenvy/che-launcher:latest start`

My `che.properties` contains:
oauth.github.clientid=<Client ID from Github>
oauth.github.clientsecret=<Client Secrect from Github>
oauth.github.authuri= https://github.com/login/oauth/authorize
oauth.github.tokenuri= https://github.com/login/oauth/access_token
oauth.github.redirecturis= http://localhost:${SERVER_PORT}/wsmaster/api/oauth/callback
auth.oauth.access_denied_error_page=/error-oauth

The error I get from pressing the octocat on Profile > Preferences > VCS :

![github_error](https://cloud.githubusercontent.com/assets/6654472/17602972/a23feb3e-5fd4-11e6-94b3-816005408235.PNG)

I am having problems debuging past this point.

**Comment by TylerJewell** [comment]
Hi @klsorge - in the `docker run` syntax the path after the `CHE_CONF_FOLDER=/path/to/conf` - did you update that with the right directory path so that it points to the updated che.properties?

Also - what is your OS?  if you are on Windows & using boot2docker, there are limitations on files you can have on your system that get passed into Che.

**Comment by klsorge** [comment]
Yes, I did update CHE_CONF_FOLDER with the correct MINGW64 path, In this case it is /c/Users/ksorge.

I am using Windows 7 and the docker quickstart terminal.

**Comment by TylerJewell** [comment]
That looks really good - definitely the write directory where boot2docker should pick up the right location and mount the folder.  My suspicion is that your che.properties file is not being picked up by virtualbox here.  I can give you a test to see if that is happening.

**Comment by TylerJewell** [comment]
machine.ws_agent.max_start_time_ms=1000

Set this value in che.properties.  Your workspace should fail to start with an error message saying that the agent wasn't able to start in a second.  If you set this and your workspace starts ok, then the che.properties file is not being properly mounted.  There is an issue with your virtualization that is preventing our stuff from seeing your files.

**Comment by klsorge** [comment]
I think you may be right. I am starting VirtualBox with ubuntu and try things there. What can I do to check out this windows setup?

**Comment by TylerJewell** [comment]
@klsorge - hmm, if that is the issue, then I recommend either:
1: Upgrade to windows 10 - and then you get the wonderful docker for windows which has no such problems, or:
2: You can do a more complicated install - where you install our server and run it natively on your windows OS.  And then the workspaces will run inside of your virtualbox VM.

This is a bit more effort - as you need to have JAVA installed properly - but this ultimately how the che server is launched inside of docker.  https://eclipse-che.readme.io/docs/usage

**Comment by klsorge** [comment]
Thank you for the recommendations. Upgrading to windows 10 is really not possible since this is a corporate machine. I will look over the link you sent and see if that works.

I was, however, able to start up an ubuntu vm and get it all working on that. Since our che instances will be going to AWS or Azure, I am going to table this for now and work on Linux.

**Comment by TylerJewell** [comment]
Great!  Should we close this issue?

**Comment by klsorge** [comment]
Yes, Thank you for all your help.

**Comment by TylerJewell** [comment]
what do you think of the product so far?

**Comment by klsorge** [comment]
From the little bit that I have worked with it, I can see a lot of potential.

**Comment by thyeun** [comment]
@klsorge actually you can try this for your windows 7, you make a new folder **"conf"** inside your /users/ksorge. 

than with the below command line 

**docker run --rm -t -v //var/run/docker.sock:/var/run/docker.sock -e CHE_CONF_FOLDER=//c/Users/ksorge/conf eclipse/che start**
