### ISSUE TITLE
Renaming workspace doesn't change underlying directory in workspaces dir

### ISSUE THREAD

**Issue by jpapejr** [eclipse-che/che#2112]
Renaming workspace doesn't change underlying directory in workspaces dir
**Reproduction Steps:**
1. Create workspace called default, observe the new directory created in the CHE_DATA_FOLDER/workspaces directory on host
2. With workspace running, rename it to default2, no change in the CHE_DATA_FOLDER/workspaces
3. Restart the workspace, a new default2 directory is created in CHE_DATA_FOLDER/workspaces

**Expected behavior:**

Original workspace dir in CHE_DATA_FOLDER/workspaces should be renamed

**Observed behavior:**

Workspace dir in CHE_DATA_FOLDER/workspaces does not change. 

**Che version:**    4.6.2
**OS and version:** MacOS 10.11.6
**Docker version:**

>  Client:
>  Version:      1.12.0
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   8eab29e
>  Built:        Thu Jul 28 21:04:48 2016
>  OS/Arch:      darwin/amd64
>  Experimental: true
> 
> Server:
>  Version:      1.12.0
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   8eab29e
>  Built:        Thu Jul 28 21:04:48 2016
>  OS/Arch:      linux/amd64
>  Experimental: true

**Che install:**    Docker container
- Problem started happening recently, didn't happen in an older version of Che: First seen on 4.6.2
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
Thanks for reporting this issue.  It is not something we have thought to think about before.  Is this a bug or a feature?

Could you elaborate a bit on why it is important for you to have the underlying host infrastructure match the internal Che in this way?  Hearing the use case will help set the priority for this.

**Comment by JamesDrummond** [comment]
@TylerJewell I am currently having the same issue. If you set `--env CHE_DATA_FOLDER=/home/user/my-che` using codenvy/che-launcher, no data is put into `/home/user/my-che/storage` or `/home/user/my-che/workspaces` but these empty folders are created. Instead all information is put into `/home/user/che/storage` and  `/home/user/my-che/workspaces`. This is a bug.

Also the `lib` folder is at `/home/user/che/lib` but no folder created at `/home/user/my-che/lib`. Should the lib folder also be put at `/home/user/my-che/lib` too?

**Comment by TylerJewell** [comment]
This issue is confirmed and fixed in #2119.

**Comment by JamesDrummond** [comment]
@TylerJewell Provide status label.

**Comment by TylerJewell** [comment]
It is not for me to provide a status.  I am going to elevate it to a blocker for now.  We may push it out to another release, or remove the blocker label until dev takes a look.

**Comment by ghost** [comment]
This is how Docker does the magic for us. If the directory with ws-name does not exist, it creates it. I am going to close this one. If it becomes a burning problem for Che 6, we will probably revisit the approach
