### ISSUE TITLE
Hide the `Tweet Feedback` button in Che-Code

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#21131]
### Is your enhancement related to a problem? Please describe

There's a `Tweet Feedback` button in Che-Code bottom panel:

![image](https://user-images.githubusercontent.com/1636395/152781175-b38f457c-c31f-437f-8ec0-2a2e4133d7ae.png)

It's not relevant in Che/CRW context.

### Describe the solution you'd like

Need to disable it by default or permanently:

![image](https://user-images.githubusercontent.com/1636395/152781493-d1be18e2-c442-4bff-ad76-61b44bcc1dae.png)

**Comment by benoitf** [comment]
hello, why should we disable it ?

**Comment by azatsarynnyy** [comment]
> hello, why should we disable it ?

A counter-question: why do we need it in the Che/CRW context?

**Comment by benoitf** [comment]
I would say that we keep what is in VS Code (try to not diverge) and let people tweet about using Che

**Comment by benoitf** [comment]
I think that the "Request a missing feature" is already redirecting to che github tracker
https://github.com/che-incubator/che-code/blob/main/code/product.json#L101
