### ISSUE TITLE
Signer information does not match (version 4.6.2)

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#2113]
When open IDE, getting the below message

**java.lang.SecurityException: class "org.eclipse.jdt.internal.core.Openable"'s signer information does not match signer information of other classes in the same package**

and fail to open workspace

**Comment by TylerJewell** [comment]
You'll need to provide details on OS / version / how che was run.  Super odd message - especially if you are using the che launcher which should make things consistent on any OS.

**Comment by thyeun** [comment]
OS : windows 10 build 10240
Version Che : 4.6.2

![signer](https://cloud.githubusercontent.com/assets/1939446/17639388/38e8103e-6124-11e6-98af-bba6b6205402.JPG)

**Comment by TylerJewell** [comment]
Please be explicit - each step that you did to create this problem including the startup command you used, any OS configuration, the stack you chose, etc.  

We have tested heavily on that OS & version - and have not seen any issues.

**Comment by TylerJewell** [comment]
@riuvshin - is this a signing issue from the eclipse binary for :latest?

**Comment by thyeun** [comment]
**OS : windows 10 build 10240**
**Version Che : 4.6.2**
**Using Stack : blank stack**
**OS configuration : None**

Just create a new workspace after changing the **version che from 4.5.1 to 4.6.2** and get the error message as you can see from my previous comment.

**Comment by TylerJewell** [comment]
How you started - the command line & any configuration parameters - is also needed.

**Comment by thyeun** [comment]
Step i did
- Started Che with **Che run**
- create a new workspace
- than after finish initial
- than try to open IDE, and i get the error message

i did nothing but just create a blank stack workspace!!!

**Comment by TylerJewell** [comment]
hmm - do you have same error when launching with the launcher - this is now the preferred approach:
https://eclipse-che.readme.io/docs/usage-docker

**Comment by thyeun** [comment]
![s1](https://cloud.githubusercontent.com/assets/1939446/17639708/6b442e02-6127-11e6-8ee1-b961592bf045.JPG)

![s2](https://cloud.githubusercontent.com/assets/1939446/17639711/738ed4cc-6127-11e6-8978-e66e0d462898.JPG)

![s3](https://cloud.githubusercontent.com/assets/1939446/17639715/7f510762-6127-11e6-9fa5-8edfac4fa701.JPG)

As you can see from the pictures, from started, no error at all

**Comment by TylerJewell** [comment]
The approach you are using to start Che is going to be deprecated.  Please launch che with this syntax:
https://eclipse-che.readme.io/docs/usage-docker

**Comment by thyeun** [comment]
i getting below message

**C:\eclipse-che\bin>docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start
docker: An error occurred trying to connect: Post http://127.0.0.1:2375/v1.22/containers/create: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it..
See 'docker run --help'.**

**Comment by TylerJewell** [comment]
That error means that Docker for Windows is not properly installed.  The nice part about using Docker for Windows is that you don't need virtualbox anymore.  It's very fast & flexible.  

https://docs.docker.com/docker-for-windows/

**Comment by thyeun** [comment]
hahaha.........now you said the magic words

i'm using windows 10 build 10240, docker for windows cant be use.

meaning that i cant change to che version 4.6.2?

**Comment by TylerJewell** [comment]
Out of curiosity what is it about that version of Windows that prevents docker for Windows to work?

Che will still work but you have to get docker working.  You are using docker toolbox with virtualbox.  You have to add the docker env Params to your environment variables.  Look at the docker docs and verify you can do a docker hello world on the console then Che will start.

**Comment by thyeun** [comment]
@TylerJewell you did not read my previous comment, i'm not the launcher issue, my launcher working perfectly. (as you can see my attach pictures)

**Comment by TylerJewell** [comment]
Those screen shots are not the launcher.  

The launcher is the docker run syntax.  The thing in your screen shots is the native startup scripts.

Fix docker toolbox on Windows so you can do hello world and then the launcher syntax will work.

**Comment by thyeun** [comment]
ok.... understand now.....

![s5](https://cloud.githubusercontent.com/assets/1939446/17641892/9fc2e316-6164-11e6-841f-a641b546ea3f.JPG)

@TylerJewell will it be the correct syntax as show from the picture?

**Comment by TylerJewell** [comment]
Yep - that looks like good output.

**Comment by thyeun** [comment]
@TylerJewell things going backward with the picture below, with three times same error, any ideal to solve the issue?

![s6](https://cloud.githubusercontent.com/assets/1939446/17643555/b5df32cc-619f-11e6-8378-9c759f731cd8.JPG)

**Comment by TylerJewell** [comment]
Those seem to be issues with Docker - not with Che.  Something on your system is causing problems for Docker.  Have you gone through the various Docker support & analysis steps that they provide?

**Comment by thyeun** [comment]
already try and done, but still have the same issue, might try to dig-in more on docker. and i'm thinking to use the same step apply for hyper-v, see any different error or not.

And sorry for trouble you too, if from your experience, it is not che issue, feel free to close this issue. and thank you for your guidance.

**Comment by TylerJewell** [comment]
We'll leave it open for a bit in case you find something that suggests that it's not a Docker issue.

**Comment by thyeun** [comment]
@TylerJewell everything good to go, not docker nor che issue, is my ISP having some internal issue, after double check with my ISP, i'm able to run che.

hope you can close this issue, and sorry for trouble you. and thanks alot (i'm learn alot here)

**Comment by TylerJewell** [comment]
Great - glad that it was able to work!
