### ISSUE TITLE
[devworkspace-handler] As a user I want to run a custom che-plugin by setting it into .che/che-theia-plugins.yaml file

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#21165]
### Is your task related to a problem? Please describe

For now, if I want to test some custom plugin, I need to generate all in one DevWorkspace with the custom plugin-registry link and then apply it into the cluster. We don't have an easy way to run a custom che-plugin in che, I mean the plugin which isn't provided by the default plugin registry. 

### Describe the solution you'd like

It'd be nice to have `reference` field instead of `id` in `.che/che-theia-plugins.yaml` file or support 2 fields: `pluginRegistryUrl` + `id`.
So, there should be 3 supported options:
1. `id` - the plugin will be taken from the default registry
2. `reference` - the plugin will be taken from the raw content
3. `id` + `pluginRegistryUrl` - the plugin will be taken from the custom registry bu its id

**Comment by vitaliy-guliy** [comment]
We should have an option as well to inline the content of the plugin definition inside `.che/che-theia-plugins.yaml` like @l0rd mentioned in the description https://github.com/eclipse/che/issues/18668

**Comment by svor** [comment]
since we don't use theia editor anymore, I'm going to close the issue
