### ISSUE TITLE
UnknownHost Exception. Che Server not able to access User Workspace URL

### ISSUE THREAD

**Issue by csa-nathan** [eclipse-che/che#21181]
### Summary

How to fix  Service Account system:serviceaccount:eclipse-che:che cannot get resource pods/log in API group "" in the namespace admin-che?

Getting the following error: 

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"workspaceioyfowrq20uehi3b.che-plugin-broker\" is forbidden: User \"system:serviceaccount:eclipse-che:che\" cannot get resource \"pods/log\" in API group \"\" in the namespace \"admin-che\"","reason":"Forbidden","details":{"name":"workspaceioyfowrq20uehi3b.che-plugin-broker","kind":"pods"},"code":403}

### Relevant information

Creating a New Workspace from Dashboard. Getting exception which triggers the websocket to be closed and kills the pods without able to start the workspace.

**Comment by nickboldt** [comment]
Please provide more details about...
* che version
* cluster version/details
* any of the other fields in https://github.com/eclipse/che/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml that seem like they might help diagnose the problem or make it reproduceable

**Comment by csa-nathan** [comment]
Hello Nick,

Error I get is not only in che-plugin-broker, but also for the pod...

Che Version : 7.41.0  ( Tried 7.40.0, 7.41.2 & 7.41.1 as well. Getting the same issue)
Cluster version:  AKS 1.21.7
Additional Information:   

In lot of places in the Che Server log,  apart from the error initially posted in this issue, could find similar error for the pod as shown below ( For Go, it creates 5 container and in the pod status it shows Running) - Attaching Che Server Error Log of Version 7.40.0 for your reference. ( Its a huge log). I would prefer version 7.40.0 as in other versions i tried, while creating new workspace, before starting it prompts an error message and proceeds).

[EclipseCheErrorLog-150220221750.txt](https://github.com/eclipse/che/files/8093849/EclipseCheErrorLog-150220221750.txt)


{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"workspaceioyfowrq20uehi3b.go-cli-7759dcb88-nqmdn\" is forbidden: User \"system:serviceaccount:eclipse-che:che\" cannot get resource \"pods/log\" in API group \"\" in the namespace \"admin-che\"","reason":"Forbidden","details":{"name":"workspaceioyfowrq20uehi3b.go-cli-7759dcb88-nqmdn","kind":"pods"},"code":403}

....
.....

Then the new workspace that gets created for the user rollback and the in the Dashboard gives one of the the following error.
![image](https://user-images.githubusercontent.com/99651183/154609289-7b1bbf1f-0545-48c6-a6fc-7eee871fd98d.png)

**Comment by ibuziuk** [comment]
@tolusha @skabashnyuk could you please take a look?

**Comment by csa-nathan** [comment]
The issue is being discussed in https://mattermost.eclipse.org/eclipse/channels/eclipse-che channel and have shared the logs, yaml files...

**Comment by skabashnyuk** [comment]
For some reason this code
https://github.com/eclipse-che/che-server/blob/470e5b86be8f31f19ae29a3d48bd3e8af73521bd/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/HttpConnectionServerChecker.java#L89

return IoException with supper wired message `server4f0gdeio-jwtproxy-server-4402.ide.banyanpro.uk`
Which gives absolutely no information about the error. Looks like some cluster-specific. 
```
2022-02-21 14:21:11,249[ServersChecker]   [DEBUG] [.h.HttpConnectionServerChecker 116]  - Failed to establish http connection to check server 'theia:https://server4f0gdeio-jwtproxy-server-4402.ide.banyanpro.uk/'. Cause: server4f0gdeio-jwtproxy-server-4402.ide.banyanpro.uk
```

**Comment by skabashnyuk** [comment]
The reason was in UnknownHostException.

**Comment by csa-nathan** [comment]
How to resolve this issue?

![image](https://user-images.githubusercontent.com/99651183/155097487-c1fcd439-e7fa-4467-ace8-50b962961fd5.png)

**Comment by csa-nathan** [comment]
It was an issue with the Domain Registrar end and now able to create the workspace for user..  Thanks to @skabashnyuk (https://github.com/skabashnyuk) for helping to identify it as an UnknownHostException..

**Comment by tolusha** [comment]
@csa-nathan 
Thank you for letting us know about solution.
