### ISSUE TITLE
Malformed Host Header error on Che startup

### ISSUE THREAD

**Issue by fusion809** [eclipse-che/che#2124]
I attempted to start che using:

``` bash
che start
```

where `/usr/local/bin/che` has been defined using [this gist](https://gist.githubusercontent.com/TylerJewell/f064857038110d2205c5aa377c01942f/raw/ae89b795c0e688649a6feab81028add9a0750fd1/get-che-cli-linux). 

But this gave the error message:

``` bash
WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
INFO: ECLIPSE CHE: FOUND IMAGE codenvy/che-launcher:latest
INFO: ECLIPSE CHE: LAUNCHING LAUNCHER
time="2016-08-15T08:34:49Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header
```

Directly calling on Docker to start che with:

``` bash
docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start
```

returns the same error:

``` bash
time="2016-08-15T08:42:02Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header"
```

**OS and version:** Arch Linux.
**Docker version:** 1.11.2.
**Che install:**  Docker.

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Unknown (not tested with previous versions).
- Problem can be reliably reproduced, doesn't happen randomly: Yes.

I doubt this is just a Docker issue as I can start other Docker containers without an issue.

**Comment by TylerJewell** [comment]
@fusion809 - that looks like it may be a Docker configuration issue on your host. 
1. Which linux variant are you using?
2. Can you verify that docker run hello-world is successful?
3. Can you bypass the CLI and just run the launcher syntax directly: https://eclipse-che.readme.io/docs/usage-docker

**Comment by ghost** [comment]
@TylerJewell I think it happens because of `/var/run/docker.sock` mount. Probably different Docker versions on the host and in the container?

**Comment by TylerJewell** [comment]
The `codenvy/che-launcher` uses a Docker 1.6 client, but shares access to the same docker host.  We've tested this with a variety of Docker client versions - so surprised if the client versions are conflicting with the host daemon, unless the host daemon is not current enough?

**Comment by fusion809** [comment]
@TylerJewell:

Reply to:
1. If you mean my distro I mentioned that in my original report (Arch Linux)
2. Yes it runs fine the output is:

``` bash
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world

c04b14da8d14: Pull complete 
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```
1. The link you provided seems to indicate that I should try: `docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start`? If so, please read my original report again as I mentioned I tried that and it failed. If you meant something else please be more specific (I'm not trying to be rude, it's just I don't know what you meant for me to do by sharing that link).

**Comment by TylerJewell** [comment]
My apologies @fusion809 - I didn't fully read through your issue posting and missed some of the salient details.  Yes, I agree that @eivantsov is saying - this could be an odd mismatch of the Docker version on your daemon vs. what is running in the che-launcher.

Can you do a:

```
che info
```

Can you also do a `docker version`, `docker info` as well?

**Comment by fusion809** [comment]
`che info` returns:

``` bash
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
DEBUG: ---------------------------------------
DEBUG: ---------  CHE CLI DEBUG INFO  --------
DEBUG: ---------------------------------------
DEBUG: 
DEBUG: ---------  PLATFORM INFO  -------------
DEBUG: DOCKER_INSTALL_TYPE       = native
DEBUG: DOCKER_HOST_IP            = 172.17.0.1
DEBUG: IS_DOCKER_FOR_WINDOWS     = NO
DEBUG: IS_DOCKER_FOR_MAC         = NO
DEBUG: IS_BOOT2DOCKER            = NO
DEBUG: IS_NATIVE                 = YES
DEBUG: HAS_DOCKER_FOR_WINDOWS_IP = NO
DEBUG: IS_MOBY_VM                = NO
DEBUG: 
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
INFO: 
INFO: ECLIPSE CHE: FOUND IMAGE codenvy/che-launcher:latest
INFO: ECLIPSE CHE: LAUNCHING LAUNCHER
time="2016-08-16T01:12:48Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header"
```

`docker version` returns:

``` bash
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Tue Jun 21 00:43:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Tue Jun 21 00:43:14 2016
 OS/Arch:      linux/amd64
```

`docker info` returns:

``` bash
Containers: 25
 Running: 0
 Paused: 0
 Stopped: 25
Images: 17
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:17-22749625-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 22.37 GB
 Data Space Total: 107.4 GB
 Data Space Available: 85 GB
 Metadata Space Used: 15.5 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.133 (2016-08-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.0-1-ck
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.61 GiB
Name: fusion809-pc
ID: YNBE:S6OR:HIZZ:CUME:4X35:IM2P:QICR:OB7K:3AZ4:3T2L:WYQK:M2HZ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
```

**Comment by TylerJewell** [comment]
Thanks for taking the time to share some of the additional debugging information.  Time to bring out the big guns.  @l0rd - can you take a peak at this particular issue?  I find it quite odd that a 1.11 docker client would be causing these issues.

@fusion809 - do you have the ability to upgrade your Docker to 1.12 on your host?  I cannot imagine that it would fix the issue if it's a docker daemon client issue, but it's good to at least eliminate another variable.

@fusion809 - this is the closest issue in the Docker forums that I could find related to your issue.  This suggests that there is a Go incompatibility issue with Docker 1.11 daemons.  https://github.com/docker/docker/issues/20865

**Comment by fusion809** [comment]
My version of Go is 1.6.2. Now I have tried upgrading both Go and Docker to the latest stable versions (1.7 and 1.12.0, respectively), but it failed. See I took the PKGBUILD for [Docker](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/docker) and [Go](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/go) in the Arch Linux `[community]` repository and bumped their `pkgver` to those aforementioned versions and built them with `makepkg` and they failed with the outputs:

``` bash
==> Making package: go 2:1.7-1 (Tue Aug 16 12:53:18 AEST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating go git repo...
Fetching origin
==> Validating source files with md5sums...
    go ... Skipped
==> Extracting sources...
  -> Creating working copy of go git repo...
Reset branch 'makepkg'
==> Removing existing $pkgdir/ directory...
==> Starting build()...
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /usr/lib/go.
panic: runtime error: index out of range
fatal error: panic holding locks

goroutine 11 [running]:
runtime.throw(0x5f85f0, 0x13)
        /usr/lib/go/src/runtime/panic.go:547 +0x90 fp=0xc8201d2e20 sp=0xc8201d2e08
panic(0x59f7c0, 0xc82000e100)
        /usr/lib/go/src/runtime/panic.go:405 +0x357 fp=0xc8201d2ea0 sp=0xc8201d2e20
runtime.panicindex()
        /usr/lib/go/src/runtime/panic.go:27 +0x65 fp=0xc8201d2ec8 sp=0xc8201d2ea0
runtime.(*gcWork).tryGet(0xc820023c20, 0x8)
        /usr/lib/go/src/runtime/mgcwork.go:160 +0xf3 fp=0xc8201d2ef8 sp=0xc8201d2ec8
runtime.gcDrain(0xc820023c20, 0x5)
        /usr/lib/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc8201d2f30 sp=0xc8201d2ef8
runtime.gcBgMarkWorker(0xc820022a00)
        /usr/lib/go/src/runtime/mgc.go:1435 +0x583 fp=0xc8201d2fa8 sp=0xc8201d2f30
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201d2fb0 sp=0xc8201d2fa8
created by runtime.gcBgMarkStartWorkers
        /usr/lib/go/src/runtime/mgc.go:1330 +0x92

goroutine 1 [runnable]:
fmt.(*pp).doPrintf(0xc82005e0d0, 0x5d1a98, 0x5, 0xc820043aa0, 0x2, 0x2)
        /usr/lib/go/src/fmt/print.go:1101
fmt.Sprintf(0x5d1a98, 0x5, 0xc820043aa0, 0x2, 0x2, 0x0, 0x0)
        /usr/lib/go/src/fmt/print.go:203 +0x6f
main.pathf(0x5d1a98, 0x5, 0xc820043aa0, 0x2, 0x2, 0x0, 0x0)
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:26 +0x5c
main.bootstrapBuildTools()
        /home/fusion809/abs/go/src/go/src/cmd/dist/buildtool.go:88 +0xb9f
main.cmdbootstrap()
        /home/fusion809/abs/go/src/go/src/cmd/dist/build.go:1022 +0x389
main.xmain()
        /home/fusion809/abs/go/src/go/src/cmd/dist/main.go:43 +0x1e9
main.main()
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:496 +0x592

goroutine 17 [select]:
main.bghelper()
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:150 +0x152
created by main.bginit
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:143 +0x5a

goroutine 18 [select]:
main.bghelper()
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:150 +0x152
created by main.bginit
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:143 +0x5a

goroutine 19 [select]:
main.bghelper()
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:150 +0x152
created by main.bginit
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:143 +0x5a

goroutine 20 [select]:
main.bghelper()
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:150 +0x152
created by main.bginit
        /home/fusion809/abs/go/src/go/src/cmd/dist/util.go:143 +0x5a
==> ERROR: A failure occurred in build().
    Aborting...
```

and:

``` bash
==> Making package: docker 1:1.12.0-1 (Tue Aug 16 12:43:00 AEST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating docker git repo...
Fetching origin
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 10 (delta 8), reused 8 (delta 7), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/docker/docker
 + 343174d...0474349 refs/pull/25705/merge -> refs/pull/25705/merge  (forced update)
  -> Found docker.sysusers
==> Validating source files with md5sums...
    docker ... Skipped
    docker.sysusers ... Passed
==> Extracting sources...
  -> Creating working copy of docker git repo...
Reset branch 'makepkg'
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#

bundles/1.12.0 already exists. Removing.

---> Making bundle: dynbinary (in bundles/1.12.0/dynbinary)
Building: bundles/1.12.0/dynbinary-client/docker-1.12.0
Created binary: bundles/1.12.0/dynbinary-client/docker-1.12.0
Building: bundles/1.12.0/dynbinary-daemon/dockerd-1.12.0
# github.com/ugorji/go/codec
runtime: nonempty check fails b.log[0]= 0 b.log[1]= 0 b.log[2]= 0 b.log[3]= 0
fatal error: workbuf is empty

goroutine 7 [running]:
runtime.throw(0x87b2c0, 0x10)
        /usr/lib/go/src/runtime/panic.go:547 +0x90 fp=0xc820034e80 sp=0xc820034e68
runtime.(*workbuf).checknonempty(0x7f7f13067900)
        /usr/lib/go/src/runtime/mgcwork.go:321 +0x153 fp=0xc820034eb8 sp=0xc820034e80
runtime.trygetfull(0xa7, 0xc820034f28)
        /usr/lib/go/src/runtime/mgcwork.go:385 +0x55 fp=0xc820034ed8 sp=0xc820034eb8
runtime.(*gcWork).tryGet(0xc820025c20, 0x8)
        /usr/lib/go/src/runtime/mgcwork.go:150 +0x7c fp=0xc820034f08 sp=0xc820034ed8
runtime.gcDrain(0xc820025c20, 0x6)
        /usr/lib/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc820034f40 sp=0xc820034f08
runtime.gcBgMarkWorker(0xc820024a00)
        /usr/lib/go/src/runtime/mgc.go:1433 +0x25f fp=0xc820034fb8 sp=0xc820034f40
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820034fc0 sp=0xc820034fb8
created by runtime.gcBgMarkStartWorkers
        /usr/lib/go/src/runtime/mgc.go:1330 +0x92

goroutine 1 [runnable]:
cmd/internal/obj.Flushplist(0xc8200a4000)
        /usr/lib/go/src/cmd/internal/obj/objfile.go:159 +0x9ee
cmd/internal/obj.Writeobjdirect(0xc8200a4000, 0xc843c91340)
        /usr/lib/go/src/cmd/internal/obj/objfile.go:114 +0x21
cmd/compile/internal/gc.dumpobj()
        /usr/lib/go/src/cmd/compile/internal/gc/obj.go:88 +0xe5f
cmd/compile/internal/gc.Main()
        /usr/lib/go/src/cmd/compile/internal/gc/lex.go:495 +0x2225
cmd/compile/internal/amd64.Main()
        /usr/lib/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
        /usr/lib/go/src/cmd/compile/main.go:32 +0x395
==> ERROR: A failure occurred in build().
    Aborting...
```

respectively. So alas I'm kinda stuck until the versions of these two packages are updated in the `[community]` repository.

**Comment by TylerJewell** [comment]
I've reread those threads a couple times and it was unclear exactly what the proposed solution was to resolve. It seemed that one user had to downgrade their docker daemon to 1.10 to get it to work.

So if this issue is bad client meets bad daemon, let's just bypass the Che launcher and use your native docker client to launch the server.  Inside the che-launcher we ship a Docker 1.6 client as a sort of universal client that can work with any forward rolling Docker daemon, but it seems that you have tripped into the one scenario where that doesn't work.

```
docker run --rm --net=host \
           --name che \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /home/user/che/lib:/home/user/che/lib-copy \
           -v /home/user/che/workspaces:/home/user/che/workspaces \
           -v /home/user/che/storage:/home/user/che/storage \
           codenvy/che-server --remote:<external-ip-of-server>
```

**Comment by fusion809** [comment]
What should I set as the `<external-ip-of-server>`? 8080?

**Comment by TylerJewell** [comment]
If you are just using the system with localhost - you do not have to provide the `--remote:<ip>` at all.  However, if you are setting up the Che instance to be a server for others, then this would be the IP address that is externally reachable by other clients.  It would be one of the IP addresses that you get from `ifconfig`.

**Comment by fusion809** [comment]
This is just for individual use so I ran:

``` bash
docker run --rm --net=host \       
           --name che \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /home/user/che/lib:/home/user/che/lib-copy \
           -v /home/user/che/workspaces:/home/user/che/workspaces \
           -v /home/user/che/storage:/home/user/che/storage \
           codenvy/che-server
```

but that gave the error:

``` bash
flag provided but not defined: --format
See 'docker version --help'.
```

Any ideas why this is?

**Comment by TylerJewell** [comment]
Backslashes are formatting.

```
docker run --rm --net=host --name che -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/storage:/home/user/che/storage codenvy/che-server
```

**Comment by fusion809** [comment]
For me I get no output from that command. I get it's meant to start a server that I can access via localhost but it doesn't tell me where to point my browser to in order to access Eclipse Che.

**Comment by TylerJewell** [comment]
Well, I am sure this us to be pretty frustrating.  At this point I need a screen share to diagnose the issues further.  I am signing off for this evening but will be back at it tomorrow.

**Comment by ghost** [comment]
@fusion809 I wonder if upgrading Docker in the base image helps. Can you please perform the following?
1. Create a Dockerfile with the following recipe

```
FROM codenvy/che-server
RUN sudo rm /usr/bin/docker
ENV DOCKER_BUCKET get.docker.com
ENV DOCKER_VERSION 1.12.0
ENV DOCKER_SHA256 3dd07f65ea4a7b4c8829f311ab0213bca9ac551b5b24706f3e79a97e22097f8b

RUN set -x \
    && sudo curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
    && sudo echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
    && sudo tar -xzvf docker.tgz \
    && sudo mv docker/* /usr/bin/ \
    && sudo rmdir docker \
    && sudo rm docker.tgz
```
1. Try to start Che either using a CLI utility or using a pure Docker syntax.

You may experiment with different docker versions in `che-server` image, say, try installing 1.11.2 - the same version you have on your host. 

Note that `ENV DOCKER_SHA256` for 1.11.2 will be `8c2e0c35e3cda11706f54b2d46c2521a6e9026a7b13c7d4b8ae1f3a706fc55e1`

**Comment by fusion809** [comment]
So to start Che I'd run:

``` bash
docker run --rm --net=host --name che -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/storage:/home/user/che/storage ImageID
```

where ImageID is the ID for the Docker image generated by the aforementioned Dockerfile. Is this right? I'm new to che so please forgive my ignorance.

**Comment by ghost** [comment]
`docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start`

**Comment by frankbolander** [comment]
You guys might want to look at:

https://github.com/docker/docker/issues/20865

Talks about bind mount of /var/run/docker.sock and problems with go 1.6+. /var/run/docker.sock is no longer valid endpoint due to go checking. Other apps that use the bind mount technique are having problems too.

**Comment by TylerJewell** [comment]
Yes, I think that is the issue.  We had another thread in the past week where we pointed out an issue with docker 1.11 and the go issue, but now for the life of me, my searches are not able to find it. I want to link it to this issue.  The solution has been (so far) to downgrade Docker on certain Linux systems to 1.10.

**Comment by TylerJewell** [comment]
@fusion809 - some ideas for us to overcome these docker issues.
1. If you add `-v /usr/local/bin/docker:/usr/local/bin/docker` to the command to launch the che-launcher, what is the outcome?  What this does is instructs the che-launcher to ignore the 1.6 Docker client that is included within the container and (instead) use the one that is installed on your host, which will match the daemon that is also installed.
2. @l0rd - one thought that we could do is to vary the che-launcher syntax to have different che-launchers with different versions of the docker client.  The default one would be using a Docker 1.6 client. But we could have label overrides that embed clients for a particular version.  We could then have some logic within the Che CLI to detect the daemon version and then use the launcher version that matches the daemon on the host.

**Comment by JamesDrummond** [comment]
@frankbolander I don't think the issue is docker version or go version by itself but the use of archlinux with these versions. I can use the same docker version and go version but on ubuntu.

```
sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64
```

The problem is with arch linux and go version from what I recall. I am trying to find my notes on it but I remember running into the same issue when using archlinux, docker and che awhile back. If you are up for it try this. It uses docker-in-docker to run che from inside a container(ubuntu 5.3.1) with docker version 1.12.0 and Go 1.6.3. 

```
sudo mkdir -p /root/containerRoot
sudo docker run --privileged --name che-dind -v /root/containerRoot:/var/run -v \
/var/run/docker.sock:/var/run/docker.sock --net host -d docker:dind
sudo docker exec -ti che-dind /bin/sh
docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start
```

 If you don't want enter the `che-dind` container, you can use the following:

```
sudo mkdir -p /root/containerRoot
sudo docker run --privileged --name che-dind -v /root/containerRoot:/var/run -v \
/var/run/docker.sock:/var/run/docker.sock --net host -d docker:dind
sudo docker exec -t che-dind docker run \
--rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start
sudo docker exec -t che-dind docker ps
sudo docker exec -t che-dind docker run \
--rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che stop
```

Running dind you need to remember that there is two different daemons running. With che-dind and the che server/container running I get the following:

```
$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
638934d7f1a4        docker:dind         "dockerd-entrypoint.s"   29 minutes ago      Up 29 minutes                           che-dind

$ sudo docker exec -t che-dind docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              POR
TS                              NAMES
b82e1dd495b0        codenvy/che-server:latest   "/home/user/che/bin/c"   18 seconds ago      Up 16 seconds       800
0/tcp, 0.0.0.0:8080->8080/tcp   che-server
```

After you get everything working you could just create a alias then include in entire path to docker if you need to run something on the native docker daemon `/usr/bin/docker`. 

```
alias docker="sudo docker exec -t che-dind docker"
$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                              NAMES
b82e1dd495b0        codenvy/che-server:latest   "/home/user/che/bin/c"   4 minutes ago       Up 4 minutes        8000/tcp, 0.0.0.0:8080->8080/tcp   che-server
$ sudo /usr/bin/docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
638934d7f1a4        docker:dind         "dockerd-entrypoint.s"   37 minutes ago      Up 37 minutes                           che-dind
```

**Comment by l0rd** [comment]
I've fixed this issue for Che (java side) a couple of months ago: #1550.

This fix is barely useful now because by default the Docker daemon accepts these malformed HTTP requests. But the behavior noticed by @fusion809 can still show up when Docker daemon (version <= 1.12) is built from source using go 1.6.

Workarounds suggested by @TylerJewell should work well: rebuild docker daemon with go <=1.6 or bind mount the docker binary. 

2 different flavors of the che-launcher is a good idea too (one with docker 1.6 and the other with version 1.10).  Another option would be to add a second docker client (version 1.10) in che-launcher image. The 1.10 client is 33MB.

**Comment by ghost** [comment]
@fusion809 is right about the issue with mounting `/var/run/docker.sock` 

The easiest way to check it is to run an official docker image with `-v /var/run/docker.sock:/var/run/docker.sock`

**Comment by JamesDrummond** [comment]
@l0rd +1 on adding an additional docker client inside the same che-launcher. Our che-launcher image size is 8mb now with docker client 1.6 included? Wonder why 1.10 is so large. Also an epic to allow che docker to run in swarm would required docker 1.12 #1836 . Would 1.12 work too instead of 1.10?

**Comment by l0rd** [comment]
@JamesDrummond yes client v1.10 should work with daemon v1.12 too and 8MB is the compressed size (22MB uncompressed).

**Comment by jalberto** [comment]
I have same problem with docker 1.10.3 (Ubuntu TLS default pkg)

**Comment by TylerJewell** [comment]
I am going to close this. We have upgraded the new Che CLI to use a Docker 1.11 client as the default.   The new CLI is now available for select usage and you can see the docs here.

https://github.com/eclipse/che/tree/master/docs
