### ISSUE TITLE
Require password

### ISSUE THREAD

**Issue by izuolan** [eclipse-che/che#213]
I use docker to install Che, but access it does not require a password, how to enter the password when access?

**Comment by TylerJewell** [comment]
There is no password required to launch and access the server. The server is configured for single identity multiple workspaces initially.

**Comment by izuolan** [comment]
But I am deployed on the server, it is public, and perhaps not safe. I would like to add a password to access, how should I do? Thanks.

**Comment by garagatyi** [comment]
You can install nginx or something like that with basic authentication
