### ISSUE TITLE
Dashboard's New Project wizard fails if workspace source type is 'location'

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#2134]
I am adding my own stack with source.type = 'location' and source.origin = 'https url to Dockerfile'. I can create a workspace from this stack using the New Workspace wizard, but it fails using the New Project wizard.

**Reproduction Steps:**
1. Open the Dashboard.
2. Click the + button on the top-right corner to open the New Project wizard, i.e. go to http://localhost:8080/dashboard/#/create-project
3. Select the "New from blank, template, or sample project" radio button in the Select Source section.
4. Select my custom stack in the READY-TO-GO-STACKS in the Select Stack section.
5. Select one of the ready-to-run project samples in the Select Template section.
6. Click the CREATE WORKSPACE AND PROJECT button.

**Expected behavior:**

The workspace and project are created successfully.

**Observed behavior:**

The progress stops on "Creating and initializing workspace". A REST call for creating the workspace in not sent to the server (I don't see the respective log in the server's output).

**Che version:**    latest master branch
**OS and version:** Fedora 24
**Docker version:** 1.10.3
**Che install:**    local build from master, run from bin/che.sh

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Don't know
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by kaloyan-raev** [comment]
I believe the issue is in https://github.com/eclipse/che/blob/2079ccc75fca29357244918c9c7511456a3be501/dashboard/src/app/projects/create-project/create-project.controller.js

I compared it to https://github.com/eclipse/che/blob/2079ccc75fca29357244918c9c7511456a3be501/dashboard/src/app/workspaces/create-workspace/create-workspace.controller.js

create-workspace.controller.js has some logic (line 139) if the source.type is 'location'. I don't find such piece of code in create-project.controller.js.

**Comment by ashumilova** [comment]
Thank you for reporting this bug, we will fix it ASAP.
