### ISSUE TITLE
Change type of pointed messages from ERROR to WARNING

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2135]
Following ERROR messages should be changed to WARNING messages:
- when user does a docker pull remote that fails (we then fail over to local);
- when we get the two GitHub oAuth errors in agent boot.

**Comment by AndrienkoAleksandr** [comment]
About first item: function pull over to local will be deleted soon after merge CHE-1818 so we should not fix  fail over to local log.

**Comment by bmicklea** [comment]
@AndrienkoAleksandr what milestone is this fixed in?  M3? M4?  M5?
