### ISSUE TITLE
Wrong displaying of commands into 'Consoles' after refresh 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2139]
**Reproduction Steps:**
1. Create sample web application on the dashboard (e.g. web-nodejs-simple).
2. Open the IDE and run it.
3. After that perform refreshing.

**Expected behavior:**
Do not have to be duplicate commands into 'Consoles'

**Observed behavior:**
We have wrong duplicate commands into 'Consoles' after refreshing

**Che version:**   4.7.0  
**OS and version:** Ubuntu 14.04 
**Docker version:** 1.11.1  
**Che install:**   local bundle

**Additional information:**
See the attachment.
![duplicate_commands](https://cloud.githubusercontent.com/assets/5408906/17700367/22169932-63ce-11e6-9d9f-2a8951daa4be.gif)

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.

**Comment by artaleks9** [comment]
Now the bug is not reproduced.
