### ISSUE TITLE
Folders that only contain one subfolder break the UI

### ISSUE THREAD

**Issue by wiredwizardsCoach** [eclipse-che/che#214]
I have imported a git project that contains nested folders with no content for several levels deep.  Che seems to collapse these into one folder and breaks navigation.

![image](https://cloud.githubusercontent.com/assets/15069580/12505603/70a88756-c0b6-11e5-88c5-d83f46a8246e.png)

If I go into the terminal and throw a dummy file into each folder `touch .foo`, the UI will work as expected.

![image](https://cloud.githubusercontent.com/assets/15069580/12505633/b2a79b10-c0b6-11e5-88b6-ca907337ee5b.png)

**Comment by garagatyi** [comment]
Yes, it is a feature used to simplify navigation in the tree.
I think that problem is not in the collapsed folder but in the ability to create files in one of the collapsed folder.
Am I right?

**Comment by wiredwizardsCoach** [comment]
Yes, I figured it was trying to be something similar to github's simplified directory navigation however when you click on my 'robot' folder, nothing happens.  You can see there's no down arrow next to the folder and so I can't see any of my actual files.

**Comment by wiredwizardsCoach** [comment]
Turns out the folder structure seems that it must be src/main/java and the project type set to java or the folder navigation doesn't work. As soon as I matched the example folder structure it was perfect.

![image](https://cloud.githubusercontent.com/assets/15069580/12519109/c1717c0c-c10a-11e5-9ece-d9d6b1ea59d1.png)
