### ISSUE TITLE
Refresh in Project Explorer does not work

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#2141]
Projects, created using a CLI tool (like `git clone` or `composer create-project`) in the Terminal, do not appear in the Project Explorer even after clicking the Refresh button.

The workaround is to reload the IDE by refreshing the browser.

**Reproduction Steps:**
1. Create new Java workspace with no project.
2. Execute `mkdir test` in the Terminal. This will create a new /projects/test folder.
3. Click on the Refresh button in the Project Explorer view.

**Expected behavior:**

The `test` folder should appear in the Project Explorer view.

**Observed behavior:**

The `test` folder should appear in the Project Explorer view.

**Che version:**    4.7.0-RC2-SNAPSHOT
**OS and version:** Fedora 24
**Docker version:** 1.10.3
**Che install:**    local build from master, run with bin/che.sh 

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
This is expected behavior.  In 4.7 coming soon there are new vfs and system watchers allowing external changes to workspaces which auto update clients like the tree without refresh.

**Comment by kaloyan-raev** [comment]
@TylerJewell This sounds great!

Will these watchers require any additional configuration, or will they work off-the-shelf?

**Comment by TylerJewell** [comment]
You can follow the epic here.  It is mostly done in branches.

**Comment by TylerJewell** [comment]
https://github.com/eclipse/che/issues/1824

**Comment by kaloyan-raev** [comment]
Thank you!
