### ISSUE TITLE
Blank Workspace Won't Start with Obscure Error

### ISSUE THREAD

**Issue by rickspencer3** [eclipse-che/che#2149]
**Reproduction Steps:**
1. Click on Workspaces to get to the Workspaces page
2. Click the "+" in the top to to New Workspace page
3. Click the "Blank" workspace and then the "Create Workspace" button (note that this also happens with the Go workspace)
4. In Workspace Information, click "Run"
5. Click "Show more" to go the workspace
5. Wait

**Expected behavior:**
The workspace opens in the IDE and you can start programming

**Observed behavior:**
The progress indicator goes for a long time, while the command drop down says "Starting workspace." A dialog box appears with an obscure error, the workspace never loads:
Error: Can't load project types: Error
    at Object.window.IDE.eventHandlers.initializationFailed (http://localhost:8080/che/default?uid=635902:39:27)
    at btb (_app-0.js:1965:168)
    at otb (_app-0.js:1971:57)
    at _.Ap (_app-0.js:4159:319)
    at eval (_app-0.js:962:86)

*\* Versions**
Che version:  Version :4.6.2Revision :4aa3f4e9c822e4edBuild Time :2016-08-09 13:27:38
OS and version: OSX 10.11.6 (15G31)
Docker version: Docker version 1.12.0, build 8eab29e, experimental
Che install:    docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start

**Additional information:**

Problem started happening recently, didn't happen in an older version of Che: Don't Know
Problem can be reliably reproduced, doesn't happen randomly: Yes

![screen shot 2016-08-17 at 10 54 56 am](https://cloud.githubusercontent.com/assets/13948193/17731467/b5051116-646d-11e6-9de3-a600da1a6ed7.png)

**Comment by ddementieva** [comment]
@rickspencer3 Can you please check if there are any errors in the browser console? 

Can you send us a screenshot with browser dev console opened?

**Comment by rickspencer3** [comment]
@ddementieva this is the output and the screenshot:

You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material!
4vendor-e40b80297f.js:32906Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.
app-52be14bb30.js:6721Preloading IDE javascript /_app/581E7ED11D2C7471060528BC35312310.cache.js
vendor-e40b80297f.js:32906 ARIA: Attribute " aria-label ", required for accessibility, is missing on node: <md-slider min=​"1" max=​"32" step=​"0.5" ng-model=​"cheWorkspaceRamAllocationSliderCtrl.inputVal" class=​"ng-pristine ng-untouched ng-valid" tabindex=​"0" role=​"slider">​…​</md-slider>​
vendor-e40b80297f.js:32906 ARIA: Attribute " aria-label ", required for accessibility, is missing on node: <input type=​"number" min=​"1" max=​"100" step=​"0.5" ng-model=​"cheWorkspaceRamAllocationSliderCtrl.inputVal" class=​"ng-pristine ng-untouched ng-valid md-input ng-valid-min ng-valid-max" id=​"input_11" aria-invalid=​"false">​
vendor-e40b80297f.js:32906 Status channel of workspaceID workspace1q9imhhrbp60abte Object {machineId: "machinecup23yg891jgiudt", eventType: "CREATING", dev: true, machineName: "default", workspaceId: "workspace1q9imhhrbp60abte"}
vendor-e40b80297f.js:32906 Status channel of workspaceID workspace1q9imhhrbp60abte Object {machineId: "machinecup23yg891jgiudt", eventType: "RUNNING", dev: true, machineName: "default", workspaceId: "workspace1q9imhhrbp60abte"}
_app-0.js:185 SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
vendor-e40b80297f.js:104836 WebSocket connection to 'ws://192.168.65.2:32806/wsagent/ext/ws' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
_app-0.js:254 GET http://192.168.65.2:32806/wsagent/ext/project net::ERR_CONNECTION_TIMED_OUTtAa @ _app-0.js:254Cvc @ _app-0.js:4322sS @ _app-0.js:4322_.Dp @ _app-0.js:4324_.Bp @ _app-0.js:956(anonymous function) @ _app-0.js:961fM @ _app-0.js:956Lpb @ _app-0.js:1909mtb @ _app-0.js:2055_.Ap @ _app-0.js:1969(anonymous function) @ _app-0.js:962
_app-0.js:963 Uncaught (in promise) Error(…)eM @ _app-0.js:963gM @ _app-0.js:956_.wn @ _app-0.js:4324KYa @ _app-0.js:959_.Hk @ _app-0.js:960_.Fk @ _app-0.js:255(anonymous function) @ _app-0.js:819(anonymous function) @ _app-0.js:5889
_app-0.js:254 GET http://192.168.65.2:32806/wsagent/ext/ net::ERR_CONNECTION_TIMED_OUTtAa @ _app-0.js:254Cvc @ _app-0.js:4322sS @ _app-0.js:4322_.Dp @ _app-0.js:4324_.Bp @ _app-0.js:956(anonymous function) @ _app-0.js:961fM @ _app-0.js:956gmb @ _app-0.js:1851_.Ap @ _app-0.js:1969(anonymous function) @ _app-0.js:962
_app-0.js:4807 ERROR (org.eclipse.che.ide.api.machine.WsAgentStateController$5): X8 @ _app-0.js:4807Y8 @ _app-0.js:4809qT @ _app-0.js:4808KU @ _app-0.js:4806_.Ap @ _app-0.js:1856(anonymous function) @ _app-0.js:962
_app-0.js:254 GET http://192.168.65.2:32806/wsagent/ext/project-type net::ERR_CONNECTION_TIMED_OUTtAa @ _app-0.js:254Cvc @ _app-0.js:4322sS @ _app-0.js:4322_.Cp @ _app-0.js:1912_.Bp @ _app-0.js:955(anonymous function) @ _app-0.js:961cM @ _app-0.js:955iM @ _app-0.js:957_.pq @ _app-0.js:4158hW @ _app-0.js:1966_.Ap @ _app-0.js:1969(anonymous function) @ _app-0.js:962
_app-0.js:4807 ERROR (org.eclipse.che.api.promises.client.callback.PromiseHelper): ErrorX8 @ _app-0.js:4807Y8 @ _app-0.js:4809qT @ _app-0.js:4808kM @ _app-0.js:4810_.Ap @ _app-0.js:957(anonymous function) @ _app-0.js:962
_app-0.js:4807 ERROR (org.eclipse.che.ide.projecttype.ProjectTypeComponent): 
java.lang.Exception: Can't load project types: Error
    at Unknown.Error(Unknown)
    at Unknown.ak(_app-0.js)
    at Unknown.lw(_app-0.js)
    at Unknown.ow(_app-0.js)
    at Unknown.qw(_app-0.js)
    at Unknown.Ap(_app-0.js)
    at Unknown.eval(_app-0.js)X8 @ _app-0.js:4807Y8 @ _app-0.js:4809qT @ _app-0.js:4809KU @ _app-0.js:4806otb @ _app-0.js:1971_.Ap @ _app-0.js:4159(anonymous function) @ _app-0.js:962
wksp-aguq?uid=977346:40 WebSocket connection to 'ws://192.168.65.2:32804/pty' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

![screen shot 2016-08-17 at 3 57 18 pm](https://cloud.githubusercontent.com/assets/13948193/17738876/5cb09c6c-6493-11e6-94f2-b5bf23426e5d.png)

**Comment by ddementieva** [comment]
@rickspencer3 Do you have Docker beta or Docker Toolbox installed? 

You may need to run some additional commands to make it work. Find more details on that at https://eclipse-che.readme.io/docs/usage-docker#pre-reqs

**Comment by rickspencer3** [comment]
@ddementieva yes, I was running the mac beta, and those instructions fixed this issue for me
