### ISSUE TITLE
Simplify boxes' design for Dashboard page

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2158]
At this moment we are having the following design for the boxes displayed on the Dashboard page.

![screen shot 2016-08-17 at 18 23 17](https://cloud.githubusercontent.com/assets/1636769/17744367/b31eac92-64a7-11e6-93d6-14c126e06a4e.png)

Since we are going to update the design of the list + the design of the form component, the header at the top of those boxes is not aligned anymore and needs to be updated.

Proposal:
- Remove the blue shape
- Replace the color of the text+icon in the headers to the dark blue we are using for page's title.

**Comment by JamesDrummond** [comment]
@slemeur Should this have `kind/enhancement` or `kind/task` label?
