### ISSUE TITLE
I don't think APIs in swagger related to projects are working correctly.

### ISSUE THREAD

**Issue by skyboy0701** [eclipse-che/che#2166]
I am not sure if I am doing something wrong. But, I cannot use any of the APIs that can be performed
by workspace owner. I could use the POST and DELETE APIs for Workspace runtime when I used them in the same tomcat that is running Eclipse Che at 8080port.

**Reproduction Steps:**
For POST project API
1. run Eclipse Che at localhost:8080
2. make a workspace
3. go into swagger at localhost:8080/swagger
4. use the POST /workspace/{id}/project with workspace id and body:
{
"name": "test",
        "attributes": {},
        "links": [],
        "type": "blank",
        "source": {
          "location": "https://github.com/che-samples/blank",
          "type": "git",
          "parameters": {}
        },
"description": "A blank project example.",
        "path": "/test",
        "problems": [],
        "mixins": []
}
5. open the ide in the workspace.
6. workspace shows project that has red x on it. 
7. check the project file location and find out that project files are not there.

For DELETE project API
1. run Eclipse Che at localhost:8080
2. make a workspace in 
3. go into swagger at localhost:8080/swagger
4. use the DELETE /workspace/{id}/project with workspace id and path: name of the project folder (test for my case)
5. open the ide in the workspace.
6. workspace shows project that has red x on it. 
7. check the project file location and find out that project files are there and not deleted.

**Expected behavior:**
For POST project API
Make a project in the workspace and get the project files from the git.
For DELETE project API
Delete a project in the workspace and also delete the project files 

**Observed behavior:**
For POST project API
Project files are not created in the local file location but workspace thinks project is created.
For DELETE project API
Project files are not deleted in the local file location but workspace thinks project is deleted.

**Che version:**   4.7.0, 4.5.1
**OS and version:** Windows 7 and ubuntu
**Docker version:** Docker installed from Docker tool box  
**Che install:**    Yatta, docker container

**Additional information:**
Is there a way to use the APIs that need to be performed only by the workspace owner?
I want to call the APIs from other project running on different port.
- Problem started happening recently, didn't happen in an older version of Che: No I also tested 4.5.1 version
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ddementieva** [comment]
@skyboy0701 http://localhost:8080/api/workspace/{id}/project method adds project only to the workspace config. That will not import the project itself. 

To import the project to the workspace you need to send a POST request `http://localhost:${ws-agent-port}/wsagent/ext/project/import/${project-name}` with the following body:

`{"location":"${location}", "type":"${import-type}"}`

${ws-agent-port} is a wsagent port, chosen from the ephemeral port range. You can find it in the Operations Perspective > Servers tab.

${import-type} can be git, svn or zip.

${location} in the location you can indicate your git or svn repos URLs or URL of the remotely hosted zip.

**Comment by skyboy0701** [comment]
Thank you, for answering my question.
I could be able to make a project using that post request.
Do you know how to use workspace runtime API?
I think I need some kind of authorization when I try to start and stop workspace via API.
I can only use the workspace runtime API in the page that runs in the tomcat running Eclipse Che.
Is there any way for me to just call Eclipse Che's API to start and stop workspaces outside the port that is already running Eclipse Che?
Is there a way for the Eclipse Che to know I am authorized person and I am allowed to start and stop workspace?
Sorry, about so many questions;;

**Comment by skyboy0701** [comment]
Oh, I just found the problem. There was a typo in my code sorry about that;;
Everything works fine now XD
Thanks for all the helps!!
