### ISSUE TITLE
Java Refactoring Rename feature broken after merging  VFS Events and Split Editor features

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#2168]
Merge of #1910 and #1837 breaks java refactoring feature.

The issue is that when we rename java class (java file) it is properly renamed in project explorer, and editor's file tab, but the content in file is not updated - class has previous name.

Most likely it is caused by several problems:
- VFS does not respect renaming (it respects remove/create instead), right now we can't catch the event of file moving/renaming by means of VFS
- IDE editor for some reason not always update it's content however the data is changed properly, most likely misbehavior in multi-tabs editor management logics. 
- IDE document storage update editor's content irrespectively of it's origin and content, may lead to overriding or vice versa - not updating of content.

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.
