### ISSUE TITLE
How do I make eclipse che instance persist across host reboots

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2170]
Srry if this is a newb question (both docker & eclipse newb).
So I start eclipse che as suggested by docs:  
(https://eclipse-che.readme.io/docs/usage-docker)  

`docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start`  

But it doesn't seem like docker persists after reboot.  
I have to restart it using the same command. -> is that expected? how would I make it autostart?

**Comment by TylerJewell** [comment]
You need to set some of the environment variables.  CHE_DATA_FOLDER variable to the location where ws should be stored.  There is also another variable for saving Che configuration state.   And there is another variable that lets you set the server restart policy.  These are all in the docs on the usage page.

**Comment by linuxd3v** [comment]
I see. Yeah - I've added `CHE_RESTART_POLICY=always` variable and it persisted.  However -> on that page it says `always` is a **default value**, which is why I didn't try it to begin with.    

I mean -> shouldn't `default value` mean -> u know -> that that's a value that would be applied by default if I don't specify one?

**Comment by TylerJewell** [comment]
Looks like its an error in the docs.  I recall the default policy being "always", but in looking at master, it's clearly not.

https://github.com/eclipse/che/blob/master/dockerfiles/che-launcher/launcher.sh#L59

**Comment by TylerJewell** [comment]
Resolved this in the docs for 4.6 - it had wrong default value specified.

**Comment by linuxd3v** [comment]
Thanks! wow that was quick.
