### ISSUE TITLE
Enable node.js debugging via GDB

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2171]
Today you can run debug for node apps in the terminal by launching `node debug <filename>.js`.  However, node's built-in debugger is compatible with GDB so it would be great to be able to debug node apps with Che's GDB debugger by adapting our way of launching GDB client to work with node.js.

**Comment by TylerJewell** [comment]
Is this duplicate of #2214?

**Comment by tolusha** [comment]
I think yes.

**Comment by bmicklea** [comment]
Closed as duplicate of #2214
