### ISSUE TITLE
Workspaces don't persist between docker service restarts

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2172]
I create a default PHP workspace and blank PHP project

http://i.imgur.com/HAHXmJl.png

Then I restart docker service from  host:  

`sudo systemctl restart docker.service`  

Workspace is gone:

 http://i.imgur.com/Nzd1hDZ.png

**Comment by TylerJewell** [comment]
@loganto - this is expected behavior.

You have to stop Che using Che's commands in the docker launcher.  Otherwise, important files will not be saved in the right locations.

Note that we have a small bug on saving workspaces outside the container (for Linux) that is fixed in 4.7.

https://eclipse-che.readme.io/docs/usage-docker
Make sure you set the CHE_DATA_FOLDER and other parameters.

**Comment by linuxd3v** [comment]
> You have to stop Che using Che's commands in the docker launcher.     

OK, but what if someone reboots the server - for maintenance or what not?     

P.S. thx -> yeah - I do set CHE_DATA_FOLDER.

**Comment by TylerJewell** [comment]
Should be ok once you have the environment variables set.
There are certain lifecycle items:
1. Preferences are stored in STORAGE parameter the moment they are changed.
2. Workspace + projects are mounted to a directory on the host, so always there.
3. Workspace snapshots are only saved when the workspace is stopped by the user.

So everything will recover other than the internal image state in your scenario, which is to be expected.  That would be like any other server scenario where you had something in memory.

**Comment by linuxd3v** [comment]
Doesn't persist for me on server reboot.
Here's my example code:

```
sudo mkdir -p /srv/che/developers
sudo mkdir -p /srv/che/developers/jcarter/data
sudo chmod -R 777 /srv/che/developers/jcarter/data

#Here's how I start the docker:   
docker run --rm -t \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e CHE_SERVER_CONTAINER_NAME=che_jcarter \
    -e CHE_HOSTNAME=localhost \
    -e CHE_RESTART_POLICY=always \
    -e CHE_PORT=3007 \
    -e CHE_DATA_FOLDER=/srv/che/developers/jcarter/data \
    eclipse/che start
```

^o then I open `localhost:3007`, create workstation and reboot a host -> workstation is gone.

**Comment by TylerJewell** [comment]
Syntax looks good.  What is in:
/home/user/che &
/srv/che/developers/jcarter/data

**Comment by linuxd3v** [comment]
ok - I've just dropped all che containers and recreated using code above.
Then created a workspace with php project, then rebooted -> again workspace and project disappeared from eclipse.

```
stan@stan-ThinkPad-W540:~$ ls -alh /home/user/che
total 16K
drwxr-xr-x  4 root root 4.0K Aug 18 17:21 .
drwxr-xr-x  3 root root 4.0K Aug 18 14:12 ..
drwxr-xr-x  4 stan stan 4.0K Aug 19 15:25 lib
drwxr-xr-x 10 root root 4.0K Aug 19 15:24 workspaces
stan@stan-ThinkPad-W540:~$

stan@stan-ThinkPad-W540:~$ ll /srv/che/developers/jcarter/data
total 16
drwxrwxrwx 4 root root 4096 Aug 19 15:22 ./
drwxr-xr-x 3 root root 4096 Aug 18 14:09 ../
drwxr-xr-x 2 stan stan 4096 Aug 19 15:24 storage/
drwxr-xr-x 3 stan stan 4096 Aug 19 15:24 workspaces/
stan@stan-ThinkPad-W540:~
```

**Comment by TylerJewell** [comment]
The files are all there - when you are rebooting docker, are you sure that the rebooted server is picking up the environment variables?  Maybe it's an issue with how docker restart policy handles the values?

**Comment by linuxd3v** [comment]
> when you are rebooting docker

This basically Ubuntu 16.04 desktop that Im practicing on. Im just clicking on gui  reboot buttons and doing entire host reboot.

**Comment by TylerJewell** [comment]
Without seeing your system, I think the issue is that restart policy is not picking up the environment variables when you restart.  If you ignore the host thign for a moment and just use our syntax to start / stop che, you'll find that it should work as advertised with the environment varibales.

**Comment by linuxd3v** [comment]
thx. yeah - Im trying to troubleshoot this.

```
stan@stan-ThinkPad-W540:~$ docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che stop
INFO: ECLIPSE CHE: STOPPING SERVER...
---------------------------------------
ERROR: !!!
ERROR: !!! ECLIPSE CHE: Timeout waiting Che container to stop.
ERROR: !!!
---------------------------------------
```

Any idea why i wouldnt be able to stop a container?

**Comment by TylerJewell** [comment]
Huh - that is interesting.  I think the default timeout is 20 seconds or so - should be plenty of time for the container to contact the server and shut it down.  

I did notice that you started Che with a set of environment variables, but you did not stop it with the same (which are needed here).  If you passed in a particular container name, then the che launcher cannot find it without the matching variable on the stop command.

**Comment by linuxd3v** [comment]
I've tried both ways - same result:

```
```

**Comment by linuxd3v** [comment]
stan@stan-ThinkPad-W540:~$ docker run --rm -t \

> ```
> -v /var/run/docker.sock:/var/run/docker.sock \
> -e CHE_SERVER_CONTAINER_NAME=che_jcarter \
> -e CHE_HOSTNAME=localhost \
> -e CHE_RESTART_POLICY=always \
> -e CHE_PORT=3007 \
> -e CHE_DATA_FOLDER=/srv/che/developers/jcarter/data \
> eclipse/che stop
> ```
> 
> ## INFO: ECLIPSE CHE: STOPPING SERVER...
> 
> ERROR: !!!
> ERROR: !!! ECLIPSE CHE: Timeout waiting Che container to stop.
> 
> ## ERROR: !!!
> 
> ```
> ```

**Comment by TylerJewell** [comment]
What does `docker logs che-server` and `docker logs che_jcarter` say?

**Comment by linuxd3v** [comment]
hmm. weird:

```
stan@stan-ThinkPad-W540:~$ docker logs che_jcarter
Error: No such container: che_jcarter
```

**Comment by linuxd3v** [comment]
docker logs che-server:

https://paste.fedoraproject.org/410965/16381771/

**Comment by TylerJewell** [comment]
I think because - right now - CHE_SERVER_CONTAINER_NAME is hard coded to che-server, and it's only configurable starting in 4.7.

**Comment by TylerJewell** [comment]
do this test - without restarting your host.
1: Set the restart policy = "no".
2: Start che
3: Stop che
4: Start che

The error message in the stack trace was benign - it wouldn't cause issues with starting.  I am wondering if in the attempt to stop che, the restart policy is getting in the way.

**Comment by linuxd3v** [comment]
thx. can't do it right away -> but Ill try this when I get home. When r u guys going to release 4.7?

**Comment by TylerJewell** [comment]
https://github.com/eclipse/che/issues/2029

**Comment by linuxd3v** [comment]
Sigh. Really struggling with this one. 
I don't know why wokspaces don't persist and not sure how to troubleshoot "environment variables not being picked up".

I'm trying to launch eclipse/che without starter container -> but this doesn't seem to work either.  
Here's what Im doing:  

```
sudo mkdir -p /srv/che/developers/jcarter/data/{storage,workspaces}
sudo chmod -R 777 /srv/che/developers/jcarter/data

docker run \
    -d \
    --name che_jcarter \
    -p 3007:8080 \
    --restart=always \
    --user=root \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /home/user/che/lib:/home/user/che/lib-copy \
    -v /srv/che/developers/jcarter/data/storage:/home/user/che/storage \
    -v /srv/che/developers/jcarter/data/workspaces:/home/user/che/workspaces \
    eclipse/che
```

^ this results in container constantly restarting. And `docker logs` output is following:  

```
Usage:
  docker run -v /var/run/docker.sock:/var/run/docker.sock codenvy/che-launcher [COMMAND]
     start                              Starts Che server
     stop                               Stops Che server
     restart                            Restart Che server
     update                             Pull latest version of codenvy/che-server
     info                               Print some debugging information

Docs: http://eclipse.org/che/getting-started.
```

**Comment by TylerJewell** [comment]
You have changed your syntax, and now the syntax you are using is wrong.  You cannot mix the syntax for eclipse/che (same as codenvy/che-launcher) with the syntax for codenvy/che-server.

Let's stick with the eclipse/che syntax as it's simpler.  

You had written:

```
docker run --rm -t \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e CHE_SERVER_CONTAINER_NAME=che_jcarter \
    -e CHE_HOSTNAME=localhost \
    -e CHE_RESTART_POLICY=always \
    -e CHE_PORT=3007 \
    -e CHE_DATA_FOLDER=/srv/che/developers/jcarter/data \
    eclipse/che start
```

Why don't you change the CHE_RESTART_POLICY=no, and do the tests this way.

**Comment by linuxd3v** [comment]
I did this test: 

```
do this test - without restarting your host.
1: Set the restart policy = "no".
2: Start che
3: Stop che
4: Start che
```

And yes - I can confirm that I  can see my projects intact.   

And yeah - I understand that this means it's Ubuntu 16.04 or docker problem. The problem for me - I have no idea how to fix "restart policy getting in the way".

**Comment by linuxd3v** [comment]
hmm. I don't know what exactly happened.
But after I've set `-e CHE_RESTART_POLICY=always \` and restarted -> I am now seeing eclipse autostarting properly and loading previously created workpsaces and projects. weird.

Thank you for ur patience Tyler.

**Comment by TylerJewell** [comment]
Cool!  I took some notes in that I want to improve some of our docs. I don't think we link off properly on the getting-started guide so that people do not get lost.
