### ISSUE TITLE
HTTPS Support?

### ISSUE THREAD

**Issue by chestnutprog** [eclipse-che/che#2174]
![image](https://cloud.githubusercontent.com/assets/13086194/17829105/f14247e2-66d5-11e6-8f0f-1ffae7149f18.png)
Will this feature be added?

**Comment by ghost** [comment]
@chestnutprog right now Che does not support https.

@TylerJewell may enlighten you on plans to do so.

**Comment by TylerJewell** [comment]
It is not available in Che.  It is, however, available within Codenvy.  The reason it is not included is complexity of architecture.  To enable https we require a reverse proxy to be deployed to manage the traffic from the browser to the agents in an https configuration.  The agents cannot house certificates and the reverse proxy would hold that along with handling decryption and routing.  This makes Che too complex to deploy and thus we do not include it.
