### ISSUE TITLE
Copy/Paste doesn't work in the Terminal (Firefox)

### ISSUE THREAD

**Issue by ddementieva** [eclipse-che/che#2178]
Copy/Paste doesn't work in the Terminal (Firefox)

**Reproduction Steps:**
1. Open any workspace in the IDE (use Firefox browser for that).
2. Go to the Terminal, type something.
3. Try to copy text in the Terminal and paste it there.

**Expected behavior:**

Text is copied and pasted in the Terminal.

**Observed behavior:**

Text is not copied and pasted in the Terminal. Can be reproduced only in Firefox.

**Comment by bmicklea** [comment]
@vparfonov can this be fixed in 4.7 or is it a bigger job?

**Comment by olexii4** [comment]
https://github.com/eclipse/che-lib/pull/13
