### ISSUE TITLE
Support running `chectl` on on M1 mac

### ISSUE THREAD

**Issue by scr-oath** [eclipse-che/che#21783]
### Describe the bug

Chectl cannot be installed on M1 mac.

### Che version

7.55@latest

### Steps to reproduce

Try to follow along with https://www.eclipse.org/che/docs/stable/administration-guide/installing-che-locally/ on M1 mac; see the following error message about not having arm support

```bash
$ bash <(curl -sL  https://www.eclipse.org/che/chectl/)
chectl script requires superuser access.
You will be prompted for your password by sudo.
Password:
curl: (22) The requested URL returned error: 404
ERROR: No download link found at https://che-incubator.github.io/chectl/download-link/stable-darwin-arm
```

### Expected behavior

Should be able to install and get started evaluating

### Runtime

Docker Desktop

### Installation method

chectl/latest

### Environment

macOS

**Comment by AObuchow** [comment]
@scr-oath Sorry to hear you experienced this issue - I tested things out and it seems there is either an issue with the install script (getting the wrong download link) or the release script is not releasing to `https://che-incubator.github.io/chectl/download-link/...` (It seems like [GitHub releases is now being used instead](https://github.com/che-incubator/chectl/commit/0df428d1c243be3e90f9492bdc81b9c2f3ffee6a)?).

My suggestion is to follow the [manual install](https://github.com/che-incubator/chectl#installation) instructions for chectl, and download the [latest stable release](https://github.com/che-incubator/chectl/releases/tag/7.55.0) of chectl for [darwin-x64](https://github.com/che-incubator/chectl/releases/download/7.55.0/chectl-darwin-x64.tar.gz). This worked on my M1 MacBook Pro. 

Hope this helps :)

**Comment by tolusha** [comment]
Should be fixed by https://github.com/che-incubator/chectl/pull/2348
