### ISSUE TITLE
Revamp list's header

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2179]
As part of the work done to simplify the list and grips in UD.
We needt improve the way we are displaying description of UD's sections.

Here is the design:
![2 - workspace list header](https://cloud.githubusercontent.com/assets/1636769/17850582/2775e77c-685e-11e6-8d54-d4eb6c127cc5.png)

Labels of each pages:
_Dashboard:_
Access your recently used workspaces and Factories, or create a new workspace. Clicking on your user name at the bottom will open up account and (with sufficient permissions) administration settings.

_Workspaces:_
A workspace is composed of projects, environments and commands. Create a new workspace or manage an existing workspace (start, stop, reconfigure or delete).  Learn more.

Learn more will redirect to: 
https://eclipse-che.readme.io/docs/environments

_Administration:_
Control the configuration and policies for your installation.

**Comment by ashumilova** [comment]
Resolved
