### ISSUE TITLE
Jade/Coffeescript/SASS support?

### ISSUE THREAD

**Issue by TareqElMasriDev** [eclipse-che/che#2180]
Hi, I really like the IDE, I was just wondering if there's any way to add other languages support, like Jade, coffeescript and sass? Thanks.

**Comment by ddementieva** [comment]
@TareqElMasri You can easily install jade, coffeescript and sass with npm in the Terminal or create your own custom stack with necessary packages installed. 

If you need to add e.g. syntax highlighting to some specific file types, you can add your own extension for that: https://eclipse-che.readme.io/docs/code-editors#section-add-syntax-highlighting-for-your-own-language

Find more details about building extensions at https://eclipse-che.readme.io/docs/create-and-build-extensions

**Comment by TareqElMasriDev** [comment]
Awesome, thanks a lot.

**Comment by Gl1TcH-1n-Th3-M4tR1x** [comment]
The part [https://eclipse-che.readme.io/docs/code-editors#section-add-syntax-highlighting-for-your-own-language](https://eclipse-che.readme.io/docs/code-editors#section-add-syntax-highlighting-for-your-own-language) on the documentation explaining how to add syntax highlighting for your own language does not clearly explain how to do it.

It mentions two options, but neither option is fully explained. For example, the second option is:
- You can configure arbitrary new contentTypes and corresponding highlight configuration.

Usage example:

 Java

and a code snippet, but it does not include the file name where to add that code to and how to link that code to the new file type created earlier.

**Comment by TylerJewell** [comment]
@ashumilova - for you.

**Comment by ashumilova** [comment]
@German-Development 
The first part of the section described in the docs binds provided file extension( example "txt", "java" etc) and proper content type. So thus file with extension "go" will be processed as "text/x-go" by editor automatically:
`this.mappings.put("go", makeList("text/x-go"));`
The used editor is Orion, which has the defined set of content types it can process: 
https://github.com/eclipse/orion/tree/master/editor/releases/latest/stylers

But, if there is any need to add own highlighting or extend existing one, then need to follow second part of the section and here is [sample from our code](https://github.com/eclipse/che/blob/master/plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/LanguageServerFileTypeRegister.java)

`contentTypeRegistrant.registerFileType(contentType, config);` - that is how content type you tied to extension before is registered in editor with provided config.

**Comment by Gl1TcH-1n-Th3-M4tR1x** [comment]
Where do you add the Java code listed at the end of the wiki page under "Java"

You can configure arbitrary new contentTypes and corresponding highlight configuration.
Usage example:
Java
@Inject
    protected void configureContentType(final OrionContentTypeRegistrant contentTypeRegistrant) {
        // register content type and configure orion
        final String contentTypeId = "text/x-testlang";

```
    OrionContentTypeOverlay contentType = OrionContentTypeOverlay.create();
    contentType.setId(contentTypeId);
    contentType.setName("Test Language");
    contentType.setExtension("testlang");
    contentType.setExtends("text/plain");

    // highlighting
    OrionHighlightingConfigurationOverlay config = OrionHighlightingConfigurationOverlay.create();
    config.setId("testlang.highlighting");
    config.setContentTypes(contentTypeId);
    config.setPatterns(
            "[\n" + 
                    "  {include: \"orion.lib#string_doubleQuote\"},\n" + 
                    "  {include: \"orion.lib#string_singleQuote\"},\n" + 
                    "  {include: \"orion.lib#brace_open\"},\n" + 
                    "  {include: \"orion.lib#brace_close\"},\n" + 
                    "  {include: \"orion.lib#bracket_open\"},\n" + 
                    "  {include: \"orion.lib#bracket_close\"},\n" + 
                    "  {include: \"orion.lib#parenthesis_open\"},\n" + 
                    "  {include: \"orion.lib#parenthesis_close\"},\n" + 
                    "  {include: \"orion.lib#number_decimal\"},\n" + 
                    "  {include: \"orion.lib#number_hex\"},\n" + 
                    "  {\n" + 
                    "    match: \"\\\\b(?:false|true)\\\\b\",\n" + 
                    "    name: \"keyword.json\"\n" + 
                    "  }\n" + 
            "]");

    contentTypeRegistrant.registerFileType(contentType, config);
}
```

Where does this code go?
