### ISSUE TITLE
Where can I find che.properties file and export workspace snapshot?

### ISSUE THREAD

**Issue by TareqElMasriDev** [eclipse-che/che#2186]
I can't find che.properties file in my mac machine, also I need to duplicate the workspace I have with the packages I've installed to other machines, how can I do that? Thanks.

**Comment by TylerJewell** [comment]
We do not place a copy of che.properties into the installation.  You can add one, however, to override the values that are there. The default che.properties is located at:  https://github.com/eclipse/che/blob/08344fe62ebedfaa199e3258279b29acec7c88f8/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties.

You can override any property you want by adding in your own properties file.

You need to perform a workspace export / import to get a ws to move from one machine to another. You can do this with REST API or in the dashboard.

**Comment by TareqElMasriDev** [comment]
So, it will export along with the apt packages I've installed?

**Comment by TylerJewell** [comment]
No.  The export exports the ws config. The ws config references a stack or dockerfile that is used to create the runtime.   If you have installed stuff into your ws which is not in the stack definition then you will need to snapshot the ws and use that image instead of the stack in the ws export.
