### ISSUE TITLE
Support for private docker registries withotut authentication?

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2188]
For out purposes w'd like to use private docker registry.  
Since it's an internal network and is not available to the outside world -> we were hoping to forego TLS & authentication setup (cuz it's PITA to setup).     

However -> Eclipse che currently doesn't support registries without authentication. 
Any chance this feature could be added? that would simplify things a lot for us.

**Comment by TylerJewell** [comment]
I haven't tested it - but are you sure that authentication is mandatory for private registries?  We support DockerHub today (no authentication), so I don't see any reason why you cannot provide a private registry with no auth config.

**Comment by linuxd3v** [comment]
Yeah - Im sure:  
http://i.imgur.com/JCP6d8A.png

See how create button is greyed out.   It says "Password is required" and I cannot click on "create".
Afaik DockerHub support is build in (I dont think I have to add it specifically).

**Comment by TylerJewell** [comment]
Have you tried just creating a custom stack that references a Dockerfile, and then just use FROM <your-private-repo-url>/<repository-name>.

The FROM syntax in Docker assumes docker.io as the host, but you can prepend other hosts.  And this syntax doesn't require a custom registry setup then.

**Comment by linuxd3v** [comment]
I haven't tried that yet. Ill try it today.

**Comment by ghost** [comment]
@TylerJewell DockerHub requires auth.

What @loganto is trying to say is perhaps that User Dashboard requires login and pass otherwise a registry cannot be added?

But if your Docker registry requires no auth, @TylerJewell has suggested the right thing - just inherit your base image in a custom recipe and let's see how it goes.

**Comment by linuxd3v** [comment]
@eivantsov  

> What @loganto is trying to say is perhaps that User Dashboard requires login and pass otherwise a registry cannot be added?

Yeah - exactly this.

> just inherit your base image in a custom recipe and let's see how it goes.  

Yeah - just trying to make it easier for team members. Logically there is no reason one shoudln't be able to add private registry with no auth using the same gui mechanism.

**Comment by TylerJewell** [comment]
I will label it as an enhancement.  It's not _entirely_ a bug because there is a way to access public repositories today.  It's a bit of a UX issue as I get @loganto point about the registry list not rejecting a public repository.  So we could add in that sort of logic to the registry screen.

**Comment by ashumilova** [comment]
Closing as far as trying to add public registry to the list of private registries. The needed host can be directly pointed in docker file.

**Comment by Learath** [comment]
Will this bug be fixed?
