### ISSUE TITLE
Eclipse che up freezing

### ISSUE THREAD

**Issue by TareqElMasriDev** [eclipse-che/che#2189]
I'm trying `che up` on my Mac OSX, this happens every time.
It just happens with `che up`, it works normal with `che start`.

```
DEBUG: Boot2docker detected - limited mounting
DEBUG: Host OS -> Che folder mapping disabled
DEBUG: Consider Docker for Mac or Windows to activate mounting
DEBUG:
INFO: ECLIPSE CHE: FOUND IMAGE codenvy/che-file:latest
INFO: ECLIPSE CHE FILE: LAUNCHING CONTAINER
INFO: ECLIPSE CHE FILE: STARTING ECLIPSE CHE SILENTLY
```

And it freezes at `STARTING ECLIPSE CHE SILENTLY`, any ideas how to fix that?

Also, I can't find ssh button in “Consoles” panel, how can I enable it?

**Comment by ddementieva** [comment]
On Ubuntu after `che.up`:

```
Status: Downloaded newer image for codenvy/che-file:latest
INFO: 
INFO: ECLIPSE CHE: IMAGE codenvy/che-file:latest INSTALLED
INFO: ECLIPSE CHE FILE: LAUNCHING CONTAINER
/usr/local/bin/che: 224: /usr/local/bin/che: Bad substitution
invalid value ":" for flag -v: bad format for path: :
See '/usr/bin/docker run --help'.
```

@TareqElMasri Can you please open a different issue for problem with SSH button?

**Comment by ghost** [comment]
@TylerJewell @l0rd i have got the same on my ubuntu machine.

**Comment by benoitf** [comment]
for che up this PR will be required
https://github.com/eclipse/che/pull/2048

**Comment by TylerJewell** [comment]
This problem will be resolved after the other PR is merged which should be soon.

**Comment by TylerJewell** [comment]
PR was merged - this issue should be resolved.  Closing.

**Comment by TareqElMasriDev** [comment]
So when I can update my che so I can have this fix?
