### ISSUE TITLE
Preparing a Workspace with a Maven Project

### ISSUE THREAD

**Issue by akervern** [eclipse-che/che#2191]
Hi,

We'd like to use Che to make bugfixes on our maintenances branches easier. The idea is to build one workspace image per version with the whole source code accessible as a ready-to-use Maven project, due to the size of the repository.

I have some questions:
## Link Workspace project to a local path

While creating the Workspace image, the git repository is cloned and built once to populate the Maven repository. But I can't figure out how to add my local folder as a Project in the User Workspace automatically. 
It looks like a symlink, post mount of `/projects` folder, would do the trick but it can only be done manually for now. Any ideas?
## Improving or preparing Maven dependencies resolution time

Also, when setting the project as a Maven one; the dependencies resolution took something like 5 min, and some `.codenvy/classpath` files are created, they all look like the same file. I could create them manually, but I'd prefer to rely on an API endpoint / Maven plugin :slightly_smiling_face:

Do you know if there is anything that can improve this resolution time?

Thanks for your help.

**Comment by ghost** [comment]
@akervern if you have all the deps in a maven repo in a workspace, 5 mins is a lot to resolve them. I do not think Che requires 5 mins to create files. We have done some tests with Che project and a custom base image with a maven repo pre populated with dependencies. Deps resolution was fast.

As to local folder to projects, sources of each workspace are mounted into `/projects` - it happens automatically. You may simply find this workspace folder locally, copy anything you need into it, and then refresh project tree in the IDE. It's in /workspaces/ws-name dir unless you provided some custom properties to Che server.

**Comment by slemeur** [comment]
@akervern It would be helpful if you can share the dockerfile that you are using in order to create the workspace's runtime. 

@eivantsov : In Arnaud's use case he did clone the sources of projects directly in the image. He created the `/projects` and cloned the sources there. But the point is that, when the workspace runtime started, the sources of the workspace are mounted on that `/projects` folder and the content created in the image is cleared.

**Comment by akervern** [comment]
@eivantsov Thanks, I tried to link the file manually in the `/projects` folder and it worked well. But, I'd like to do it without any user actions and with the Maven project configured.

@slemeur You can find the repo here: https://github.com/nuxeo-sandbox/nuxeo-docker-che
And I pushed an image to let you test without building everything: 
`docker pull quay.io/akervern/nuxeo-che`
After the workspace is up; just link the sources `ln -s /opt/nuxeo /projects/nuxeo` and refresh, etc.

**Comment by ghost** [comment]
@akervern I have just run the following test:
1. Built an image with the following recipe

```
FROM codenvy/che-dev
RUN cd /home/user && \
    git clone https://github.com/eclipse/che && \
    cd che && \
    mvn clean install -DskipTests -Dskip-validate-sources
```
1. Created a workspace with this image and imported https://github.com/eclipse/che
2. The project has been resolved almost immediately. 

Are you certain .m2 contains all the deps that your project requires?

**Comment by akervern** [comment]
@eivantsov just tried the following:
1. Open a new workspace using the custom stack:
   `FROM quay.io/akervern/nuxeo-che`
2. Once loaded, ensure m2 repository is ok:
   `$ cd /opt/nuxeo && mvn package -o -DskipTests`
   And everything goes fine.
3. Link `ln -s /opt/nuxeo /projects/`, reload and configure the project as a Maven one.

But the resolution time took something like 5-6min even on beta.codenvy.com.

**Comment by ghost** [comment]
@akervern what about `mvn clean install` rather than `package`? This way artifacts will be installed in your local maven repo.

**Comment by akervern** [comment]
@eivantsov in my last comment, I just tried the `mvn package` with offline mode to ensure the repo is correctly filled in the workspace. So, it proves that the maven local repo si good.

**Comment by ghost** [comment]
But `clean package` won't install any artifacts. `clean install` will.

**Comment by akervern** [comment]
You're right. You asked me if i'm sure to have all my deps installed on my local repo. 
Building a global `package` in offline mode should be enough to make it sure all deps are presents. Am I right? But yes, while building my custom workspace, I done a `mvn install`.
Specially as I'm using a released version of Nuxeo on this workspace, and I guess version check on the maven repository origin should not happens.

**Comment by ghost** [comment]
@akervern I will take a look at the image.

**Comment by akervern** [comment]
Hi @eivantsov, do you find anything that could improve the load time?

**Comment by TylerJewell** [comment]
@bmicklea @eivantsov - any update on this?  It's been greater than 60 days, if @akervern still has the open issue, we should prepare a note for what to do here.

**Comment by ghost** [comment]
@akervern @TylerJewell I haven't been able to reproduce. Each time I try to create an image with M2 repo and then load Che, the deps are resolved almost instantly.

**Comment by TylerJewell** [comment]
Closing until we can reliably reproduce.
