### ISSUE TITLE
Che can't make workspace or project

### ISSUE THREAD

**Issue by linetor** [eclipse-che/che#220]
Hello...I try to set up che at ec2 in ASW.
And I build che and start che and test for making work space and project.

In 2 step, I chose READY-TO-GO STACKS(JAVA) and select templete(console-java-simple) and create project.

Next time I get a processing 1~4. 
After 3 step(Injecting and starting workspace agent), it print 
[STDOUT] 2016-01-25 09:10:13,645[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 17124 ms
but can't Create project(Step4)

But it make work-space. So I Choose the stack itself(Step2 STACK LIBRARY). And process create project.
It print console-java-simple : Project created. And I go to the opin in IDE.
It print "connection failed with terminal"
Why it happend? doest it need to change property?
i Change 
machine.docker.che_api.endpoint=myIP
api.endpoint=miIP:${SERVER_PORT}/ide/api
I'm not used to docker and che. So if you need any information. Please tell me..

**Comment by garagatyi** [comment]
Try set property `machine.docker.local_node_host` to IP of your AWS instance.

**Comment by linetor** [comment]
Oh~~~~I can make my project.
Thanks..
