### ISSUE TITLE
How to integrate Eclipse Che with Perforce or GitSwarm.

### ISSUE THREAD

**Issue by rajasekaran07** [eclipse-che/che#2201]
[Short description of problem here]

Please let me know is there any perforce or gitswarm plugin available for Eclipse Che. Because, In worldwide nearly 15000+ customers are using Perforce as their source code repository. If they switch to Eclipse Che, the SCM will be really challenging. Please let me know if there is any alternate solution as well.

**Comment by TylerJewell** [comment]
You could add both of these capabilities with a custom stack into Che.  A custom stack lets you define a dockerfile that installs various utilities for gitswarm or perforce.  You can then manage in the terminal the connection from your workspace to these other repositories.

**Comment by ghost** [comment]
@rajasekaran07 could you perhaps provide more details on what you are trying to achieve? Have you tried anything specified or met particular issues?

**Comment by ghost** [comment]
@rajasekaran07  any update on this?

**Comment by rajasekaran07** [comment]
@eivantsov my sincere apologies for the delay. This was integrated with Helix P4V and GitSwarm. Thanks for your inputs.

**Comment by kevinmat** [comment]
I am looking to checkin code via eclipse che editor to Perforce. However , currently the editor is not integrated with Perforce , Can I get specific steps how to achieve this?
