### ISSUE TITLE
Ability to create a workspace from any repository hosting provider

### ISSUE THREAD

**Issue by kontulai** [eclipse-che/che#2202]
Is it possible to create a workspace from other repository hosting providers than GitHub/GitLab? One of our users at [deveo.com](https://deveo.com) asked whether it would be possible to use Eclipse CHE together with Deveo. I was instructed to submit a support request here by Tyler Jewell.

**Reproduction Steps:**
1. Go to https://www.eclipse.org/che/getting-started/cloud/
2. Look at text "Create a workspace from your GitHub or GitLab repo"
3. Wonder whether it's possible to create workspace from e.g. [deveo.com](https://deveo.com) repository (private code hosting)

**Expected behavior:**

Would like to create a workspace from a repository at Deveo.

**Observed behavior:**

Not sure if that is possible. No instructions or hints available.

**Che version:**    Cloud/SaaS
**OS and version:** OSX 10.11.6
**Docker version:** Didn't use docker yet
**Che install:**    Didn't install it yet

**Additional information:**

No additional information available.

**Comment by TylerJewell** [comment]
We've tested on 15 or so.  It shouldn't be a problem as long as there is SSH support with the provider, which deveo has.  You can see about how to setup keys on this page - https://eclipse-che.readme.io/docs/git.

**Comment by kontulai** [comment]
Thanks. Will close this issue.
