### ISSUE TITLE
debian jessie JAVA_HOME issue

### ISSUE THREAD

**Issue by michael-basil** [eclipse-che/che#221]
I'm trying to get Che running on Debian Jessie ... I think it's close, but I'm getting an error saying JAVA_HOME isn't set, but I've set it in /etc/profile (see below).  I will be attempting to run this on the Azure Container Service as well.

I pulled this version: https://install.codenvycorp.com/che/eclipse-che-latest.tar.gz

macadmin@mbsbxche:~/eclipse-che$ tail /etc/profile
if [ -d /etc/profile.d ]; then
for i in /etc/profile.d/*.sh; do
if [ -r $i ]; then
. $i
fi
done
unset i
fi

JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
macadmin@mbsbxche:~/eclipse-che$ echo $JAVA_HOME
/usr/lib/jvm/java-8-oracle/jre/

macadmin@mbsbxche:~/eclipse-che$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

macadmin@mbsbxche:~/eclipse-che$ docker --version
Docker version 1.9.1, build a34a1d5

macadmin@mbsbxche:~/eclipse-che$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"

macadmin@mbsbxche:~/eclipse-che$ bin/che.sh 
Docker is natively installed and reachable...
###### ######## HOW TO CONNECT YOUR CHE CLIENT

After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
###### 

JAVA_HOME is not set. Please set to directory of JVM or JRE.

**Comment by benoitf** [comment]
if you add export keyword in /etc/profile?
export JAVA_HOME=.....

**Comment by michael-basil** [comment]
Thanks.  Seems to have worked.  I knew it must be something simple :)

Can Che run over a secure port?  Maybe with Let's Encrypt integration?

mb

**Comment by TylerJewell** [comment]
No reason that it couldn't.  Please note that there are three separate connections that have to be managed:
1. Between browser & Che
2. Between browser & each workspace
3. Between Che & each workspace

How these connections are made & managed is documented here. 
https://eclipse-che.readme.io/docs/networking

I am going to close this issue since the original issue is resolved.
