### ISSUE TITLE
Enhance GDB debugger to work with node.js

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2214]
With many users moving to Node it would be good to offer an enhanced debugging experience with node using our built-in GDB debugger.

@tolusha - if you need any extra information let me know.

**Comment by TylerJewell** [comment]
I saw this is requested for the next sprint. What is the driver for doing it so quick - do we have outstanding user requests?

**Comment by bmicklea** [comment]
@tolusha what's the latest status? Is there someone who can provide the code review so we can get this merged?

**Comment by 0Grit** [comment]
The host and port debug configuration options are not implemented in the gui for the node debugger.
I'd like to debug a remote target with the node debugger.
Can this be implemented and any recommendations accomplishing this until then?
