### ISSUE TITLE
Assign simpler names to docker containers created by Che

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2224]
Currently, when a workspace is created, we generate Docker container names that have long hash codes. It makes it difficult for a user to understand which containers below to which workspace when doing a `docker ps` or a `docker inspect`.  

We'd like to give a pretty-name to containers created by Che for workspaces.

```
che-ws-<ws-name>-dev-machine
che-ws-<ws-name>-<second-machine-name-from-yml>
```

**Comment by skabashnyuk** [comment]
@TylerJewell  is this issue up to date?

**Comment by TylerJewell** [comment]
Yes I believe it is.  I have a question about machine names.  Are machine names defined by the user or do we define them internally?  I am wondering how pretty or ugly it will be.  The goal here is readability for the user when they do a 'docker ps'.

**Comment by garagatyi** [comment]
It is defined internally for now

**Comment by skabashnyuk** [comment]
@TylerJewell is this issue still needed?

**Comment by TylerJewell** [comment]
Yes, this will be a long-lived issue.  We'll eventually want to have pretty-names for all containers generated by Che.
