### ISSUE TITLE
In company's network,workspace open error,and can't create project

### ISSUE THREAD

**Issue by chendongping** [eclipse-che/che#2226]
[Short description of problem here]
local deploy,ubuntu docker enviroment as a server. 
when I open a workspace, pop error infomatiaon,
when I Create project, there is no react

**Reproduction Steps:**
STEP 1:open a workspace,error infomatiaon:
1. 
Error:Can't load project types:Error
 at Object.window.IDE.eventHandlers.initializationFailed(...)
 at btb(_app-0.js:1965:168)
 at otb(_app-0.js:1971:57)
 at _.Ap(_app-0.js:4159:319)
 at eval(_app-0.js:962:86)
2.
 Connection failed with terminal

and the loading gif cant stop

STEP 2:Create project
 input a project name in dialog popped, and confirm,but no react

[deploy eviroment]
1. local deploy,ubuntu docker enviroment as a server,**but this server is in company's network and can't access to internet** for some secret inquirement. 
2. as a contrast,I deploy a VM server in my home,it works fine

so,my question is, does local deployed che server must connect to internet?

**Che version:**    [4.6]  
**OS and version:** [ubuntu 14.04]  
**Docker version:** [1.12]  
**Che install:**    [Docker container:docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start]

**Comment by JamesDrummond** [comment]
The che server does download stack docker images from docker hub but from your description it seems like it at least has access download from the internet. Please describe where you are trying to access your che server from that is running on your company's server. This seems like ports are being blocked by a firewall. Take a look at [https://eclipse-che.readme.io/docs/networking](https://eclipse-che.readme.io/docs/networking) for additional information.

**Comment by chendongping** [comment]
thanks for you advice.
yes,the che server has access download docker images indeed,but it is from our company's mirror.
my web client is in company's network,it can visit my che server.web client can open IDE page,but with some error msg,and can't create project.
I want to know if the local che server can work alone in a closed network without the support of eclipse/codenvy's cloud? if it is,I will search problems between client and che server

**Comment by ghost** [comment]
@JamesDrummond it's not about downloading Docker images. 

The error is caused by the client attempting to access  the workspace agent.

@chendongping make sure the ephemeral port range is not filtered. Also, can you share screenshot fo a browser dev console? I am pretty sure there are failed websocket connection messages.

**Comment by chendongping** [comment]
yes,there are connection fail.
get 172.17.0.1:32778 failed, I think 172.17.0.1 is the work-space ip,
my server host ip is 10.21.206.199, how can i route to 172.17.0.1 ,it is a nat IP in server,maybe I should add a route to 172.17.0.1 with gateway 10.21.206.199?

**Comment by chendongping** [comment]
I ping work-space ip 172.17.0.1 fail, 
How does the work-space ip allocated ?
I can't understand it, 172.17.0.1 is  a NAT IP, let web client connects to a NAT IP directly, it can't route to there

**Comment by ghost** [comment]
Are you accessing Che from a remote client (browser?) If so, you need to start Che with `-r:$IP` parameter where `$IP` is IP address of the server running Che,

Why do you have different IPs for server and workspace?

**Comment by ghost** [comment]
@chendongping can you try running Che with `-e "CHE_HOST_IP=10.21.206.199"` - this way you tell the server and the client to use this IP and no auto detection happens.

**Comment by JamesDrummond** [comment]
@chendongping As @eivantsov stated when you are trying to access the che server remotely you need to set the `CHE_HOST_IP`. The standard use case described at [https://eclipse-che.readme.io/docs/usage-docker#start](https://eclipse-che.readme.io/docs/usage-docker#start) is for when accessing the che server from the same machine.

**Comment by chendongping** [comment]
thanks, " -e CHE_HOST_IP=10.21.206.199"  done!

**Comment by lishoujun** [comment]
@eivantsov    

How if I have run “docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock  eclipse/che start”
before？
Now I have an error message。
“ERROR: !!!
ERROR: !!! A container named "che-server" already exists. Please remove it manually (docker rm -f che-server) and try again.
ERROR: !!!”

**Comment by JamesDrummond** [comment]
@lishoujun That means a container named che-server already exists so "docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start" was already ran. In order to restart the che server run "docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_HOST_IP=10.21.206.199 eclipse/che restart". If this command fails/hangs then try "docker rm -f che-server" to force remove of container. The latter approach is not preferable "docker rm -f che-server" though as some user preferences will not be saved.
