### ISSUE TITLE
Folder/File disappeared after rename

### ISSUE THREAD

**Issue by t-oss** [eclipse-che/che#2227]
Folder/File disappeared in "Project Explorer after rename", a refresh of its parent folder is needed

**Reproduction Steps:**
1. Open some project
2. Rename a file or folder, the folder will disappeared.
3. Refresh the page or fold -> expand it's parent folder will find the renamed folder/file.

**Expected behavior:**
The renamed result will be seen directly.

**Che version:**    [Codenvy 4.6.2]  
**OS and version:** [CentOS 7.2]  
**Docker version:** [1.11.1]  
**Che install:**    [Codenvy]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ghost** [comment]
This is a known issue. Closing this one. You may follow https://github.com/eclipse/che/issues/1821
