### ISSUE TITLE
Investigate how to use Docker Swarm mode in Docker 1.12 for runtime of workspace

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2228]
Investigate whether usage of following Docker features differ in swarm mode of Docker 1.12 comparing to Docker 1.11/ Swarm 1.2.
- container creation (can we track progress to show to the user)
- exec (start additional processes in a container)
- commit/push (save machine into snapshot functionality)
- events streaming
- container logs streaming
- container killing
- nodes configuration

**Comment by TylerJewell** [comment]
Also, we need to study how startup and shutdown may be affected through configuration, che-server and che-launcher.  Any alterations to the standard startup and configuration tactics should be discussed.

**Comment by garagatyi** [comment]
Sorry, but I am not sure what you mean. Can you elaborate more?

**Comment by TylerJewell** [comment]
We need an assessment of what changes should be made to Che server and, if appropriate, che-launcher when configuring Che to run on Swarm.  How will users tell Che how to use Swarm, what are the properties.  We need to see whether there will be a significant impact on configuring the Che launcher and maybe the CLI.

**Comment by garagatyi** [comment]
I've added #2254 for that

**Comment by TylerJewell** [comment]
Will not implement. Will instead move to kubernetes.
