### ISSUE TITLE
Incomprehensible behavior for creation a factory from dashboard

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2229]
[Short description of problem here]

**Reproduction Steps:**
1. Create a workspace with a project
2. Got to the Dasboard -> Factories
3. Click Create Factory -> Select the Workspace Tab -> click create button.

**Expected behavior:**
The Create button should be disabled (because we did not select the project for factory)
**Observed behavior:**
The button is enabled. After clicking we have unexpected errors.

![anim](https://cloud.githubusercontent.com/assets/1640058/17998572/caef5998-6b7d-11e6-9719-29690daba440.gif)

**Che version:**   4.7.0-RC2-SNAPSHOT
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Comment by JamesDrummond** [comment]
Should this issue be moved to codenvy repo?

**Comment by ashumilova** [comment]
Moved to codenvy https://github.com/codenvy/codenvy/issues/637
