### ISSUE TITLE
Add macros for host

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2230]
${host.name} -- Returns the host name of the underlying OS running Che native or its Docker daemon.
${host.ip} -- Returns the IP address of the underlying OS running Che native or its or Docker daemon.

**Comment by TylerJewell** [comment]
@ashumilova @vzhukovskii - after studying this issue more indepth - I agree that to implement it similar to how we do it in che-launcher would be a significant amount of work.  I am going to close this as "won't fix" - at least for now.
