### ISSUE TITLE
Modify Error Message When Trying to Run Che Server Twice

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2233]
Should we change the error message when trying to run che server if it is already running.

**Reproduction Steps:**
1. docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start
2. docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start

![movie](https://cloud.githubusercontent.com/assets/20580888/18008320/4e136fe6-6b6d-11e6-8c9c-81ada1b6e28e.gif)

**Expected behavior:**

Error message stating to run `docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che stop`. 

**Observed behavior:**

Error message stating to run `docker rm -f che-server`.

[Describe observed behavior here]

**Che version:**    nightly-4.7  
**OS and version:** Ubuntu 16.04.1 LTS
**Docker version:** 
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64
**Che install:**  
Google Cloud.   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No] No
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes

**Comment by TylerJewell** [comment]
This is expected behavior.

**Comment by JamesDrummond** [comment]
If the server is shutdown with `docker rm -f che-server` certain files will not be saved. I know sometimes `docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che stop` will not work sometimes if the che server container is not responsive. Would putting both messages make sense. I meant to put both in expected behavior. Might be that I restart che server more then the average user though :).

**Comment by TylerJewell** [comment]
Good point. I added this to the che-launcher.  Should show up in nightly by end of the week.  Here is the new output.

```
ERROR: !!!
ERROR: !!!
           A container running ECLIPSE CHE named "che-server" already exists.
             1. Use "info" to find it's URL.
             2. Use "restart" to stop it and start anew.
             3. Stop it with "stop".
             4. Remove it manually (docker rm -f che-server) and try again. Or:
             5. Set CHE_SERVER_CONTAINER_NAME to a different value and try again.
ERROR: !!!
```
