### ISSUE TITLE
Eclipse CHE is up on vagrant but not available on the browser

### ISSUE THREAD

**Issue by SanthoshHari912** [eclipse-che/che#2235]
Am trying to configure Eclipse CHE as workspace development server in a Windows 7 machine. Am following the usage guide using vagrant and virtual box given here https://eclipse-che.readme.io/docs/usage-vagrant
On vagrant up am getting a info message as ,
==> che: --------------------------------
==> che: ECLIPSE CHE: BOOTING ECLIPSE CHE
==> che: --------------------------------
==> che: ECLIPSE CHE READY AT: http://192.168.28.100:8080

But not able to access this url in the browser.I get "the site cannot be reached" error.

Can someone advise to get over this issue ?

Thanks
Santhosh

**Comment by TylerJewell** [comment]
@SanthoshHari912 - well, I just tried to boot up the vagrant image and it was a total failure!  Ok, something has changed so we have a bit of a bug.  Thanks for commenting on this.  Can you try the Docker launcher in the meantime until we get a fix?

**Comment by TylerJewell** [comment]
@SanthoshHari912 - A fix has been made into the core repository of Che.  You can now use this Vagrantfile: https://github.com/eclipse/che/pull/2236.
