### ISSUE TITLE
IDE can't build and run project

### ISSUE THREAD

**Issue by chendongping** [eclipse-che/che#2238]
[Short description of problem here]
IDE can't build and run project

**Reproduction Steps:**
1. [First Step]
   in a cpp workspace,create a simple c project with only 1 source code file:main.c, here is the code
   # include <stdio.h>
   
   int main(void)
   {
       printf("hello, world\n");
   }
2. [Second Step]
   click 'run' button on IDE 

**Expected behavior:**
console output:
"hello, world\n"

**Observed behavior:**
console output:
command:cd /projects/testc && make && ./a.out
[default] make: **\* No targets specified and no makefile found.  Stop.

**Che version:**    [4.6]  
**OS and version:** [ubuntu 14.04]  
**Docker version:** [1.12]  
**Che install:**    [Docker container]    

**Additional information:**
other language JAVA/PYTHON workspace can't build and run project also.

**Comment by chendongping** [comment]
java workspace msg;
console output:
mvn -f /projects/testjava clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM /projects/testjava/pom.xml: /projects/testjava/pom.xml (No such file or directory) @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project  (/projects/testjava/pom.xml) has 1 error
[ERROR]     Non-readable POM /projects/testjava/pom.xml: /projects/testjava/pom.xml (No such file or directory)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

CHROME DEBUG CONSOLE:
VM558 _app-0.js:254 GET http://10.21.206.199:8080/wsmaster/api/recipe/script/machine7g509nlbcxchg03b 500 (Internal Server Error)tAa @ VM558 _app-0.js:254Cvc @ VM558 _app-0.js:4322sS @ VM558 _app-0.js:4322_.Dp @ VM558 _app-0.js:4324_.Bp @ VM558 _app-0.js:956(anonymous function) @ VM558 _app-0.js:961fM @ VM558 _app-0.js:956rfc @ VM558 _app-0.js:3640_.Ap @ VM558 _app-0.js:3677(anonymous function) @ VM558 _app-0.js:962
VM558 _app-0.js:4807 ERROR (org.eclipse.che.ide.extension.machine.client.perspective.widgets.machine.appliance.recipe.RecipeTabPresenter): Failed to get recipe script for machine machine7g509nlbcxchg03b: 500 Internal Server Error http://10.21.206.199:8080X8 @ VM558 _app-0.js:4807Y8 @ VM558 _app-0.js:4809qT @ VM558 _app-0.js:4808kM @ VM558 _app-0.js:4810_.Ap @ VM558 _app-0.js:3652(anonymous function) @ VM558 _app-0.js:962
VM558 _app-0.js:254 GET http://10.21.206.199:8080/wsmaster/api/recipe/script/machine7g509nlbcxchg03b 500 (Internal Server Error)tAa @ VM558 _app-0.js:254Cvc @ VM558 _app-0.js:4322sS @ VM558 _app-0.js:4322_.Dp @ VM558 _app-0.js:4324_.Bp @ VM558 _app-0.js:956(anonymous function) @ VM558 _app-0.js:961fM @ VM558 _app-0.js:956rfc @ VM558 _app-0.js:3640_.Ap @ VM558 _app-0.js:3677(anonymous function) @ VM558 _app-0.js:962
VM558 _app-0.js:4807 ERROR (org.eclipse.che.ide.extension.machine.client.perspective.widgets.machine.appliance.recipe.RecipeTabPresenter): Failed to get recipe script for machine machine7g509nlbcxchg03b: 500 Internal Server Error http://10.21.206.199:8080

**Comment by chendongping** [comment]
some enviroment info:

root@SZX1000149552:~# docker ps -a
CONTAINER ID        IMAGE                                                                       COMMAND                  CREATED             STATUS                  PORTS                                                                                                                                                                                           NAMES
b65ddb7b6820        eclipse-che/workspacejn4aj8z8ub9zudxd_machineemh7gjz7x5cfah0u_che_default   "/home/user/entrypoin"   About an hour ago   Up About an hour        0.0.0.0:                  32826->22/tcp, 0.0.0.0:32825->4401/tcp, 0.0.0.0:32824->4403/tcp, 0.0.0.0:32823->4411/tcp                                                                              workspa                  cejn4aj8z8ub9zudxd_machineemh7gjz7x5cfah0u_che_default
4e72f7ce65bc        eclipse-che/workspacepsiny2oeqn7hwuwn_machine7g509nlbcxchg03b_che_default   "/bin/sh -c 'sudo /us"   About an hour ago   Up About an hour        0.0.0.0:                  32815->22/tcp, 0.0.0.0:32814->4401/tcp, 0.0.0.0:32813->4403/tcp, 0.0.0.0:32812->4411/tcp, 0.0.0.0:32811->8000/tcp, 0.0.0.0:32810->8080/tcp, 0.0.0.0:32809->9876/tcp   workspa                  cepsiny2oeqn7hwuwn_machine7g509nlbcxchg03b_che_default
3ded0505f080        eclipse-che/workspacex7gu0zgmcnfbb61i_machined47qsf73etr6yedb_che_default   "/home/user/entrypoin"   6 hours ago         Up 6 hours              0.0.0.0:                  32808->22/tcp, 0.0.0.0:32807->4401/tcp, 0.0.0.0:32806->4403/tcp, 0.0.0.0:32805->4411/tcp, 0.0.0.0:32804->8080/tcp                                                     workspa                  cex7gu0zgmcnfbb61i_machined47qsf73etr6yedb_che_default
0868b0de7446        eclipse-che/workspacejigrsb9e236q4lzg_machinevsprbeyayq835fo2_che_default   "/home/user/entrypoin"   7 hours ago         Up 7 hours              0.0.0.0:                  32799->22/tcp, 0.0.0.0:32798->4401/tcp, 0.0.0.0:32797->4403/tcp, 0.0.0.0:32796->4411/tcp, 0.0.0.0:32795->8080/tcp                                                     workspa                  cejigrsb9e236q4lzg_machinevsprbeyayq835fo2_che_default
4cc7ca4b5404        codenvy/che-server:latest                                                   "/home/user/che/bin/c"   9 hours ago         Up 9 hours              8000/tcp                  , 0.0.0.0:8080->8080/tcp                                                                                                                                              che-ser                  ver
314d1bc79ff0        hello-world                                                                 "/hello"                 2 days ago          Exited (0) 2 days ago                                                                                                                                                                                                   cranky_                  feynman
root@SZX1000149552:~# ^C
root@SZX1000149552:~# docker images
REPOSITORY                                                                  TAG                 IMAGE ID            CREATED             SIZE
eclipse-che/workspacepsiny2oeqn7hwuwn_machine7g509nlbcxchg03b_che_default   latest              c26f26332869        6 hours ago         830.3 MB
machine_snapshot_bragmdapwtk04mcq                                           latest              c26f26332869        6 hours ago         830.3 MB
codenvy/cpp_gcc                                                             latest              2ce309da61da        2 weeks ago         646.7 MB
eclipse-che/workspacejn4aj8z8ub9zudxd_machineemh7gjz7x5cfah0u_che_default   latest              2ce309da61da        2 weeks ago         646.7 MB
codenvy/ubuntu_python                                                       2.7                 3551fcad3fd5        2 weeks ago         740.8 MB
eclipse-che/workspacex7gu0zgmcnfbb61i_machined47qsf73etr6yedb_che_default   latest              3551fcad3fd5        2 weeks ago         740.8 MB
codenvy/ubuntu_python                                                       latest              6e3ac59d6701        2 weeks ago         775 MB
eclipse-che/workspacejigrsb9e236q4lzg_machinevsprbeyayq835fo2_che_default   latest              6e3ac59d6701        2 weeks ago         775 MB
codenvy/che-server                                                          latest              e0ce11b7422f        2 weeks ago         309.6 MB
codenvy/che                                                                 latest              cda93ea38352        2 weeks ago         22.14 MB
eclipse/che                                                                 latest              cda93ea38352        2 weeks ago         22.14 MB
codenvy/ubuntu_jdk8                                                         latest              5fca53411e54        4 weeks ago         723.9 MB
hello-world                                                                 latest              c54a2cc56cbb        8 weeks ago         1.848 kB
alpine                                                                      latest              4e38e38c8ce0        9 weeks ago         4.799 MB
root@SZX1000149552:~#

**Comment by TylerJewell** [comment]
In both of your cases you ran a command that did not have the files present.  Commands are just processes that execute in the terminal for you.  

So go into the terminal and you should be able to run gcc or javac against the files you created.  Once the terminal scenario works - you can update the commands by editing them with the entry that you did in the terminal.

**Comment by TylerJewell** [comment]
Since this is an issue related to programming and not an issue with the product, going to close.  Feel free to reopen if you think there is still a bug.

**Comment by chendongping** [comment]
----"So go into the terminal and you should be able to run gcc or javac"----
sorrr I dont know what is "the terminal" mean, is it means HOST ubuntu?
I think gcc or javac should installed in the images such as cpp-gcc,ubuntu_jdk8,and work in work-space.I have downloaded this images.
is there any detail operate guide?

**Comment by chendongping** [comment]
It works, need to config command in IDE

**Comment by chendongping** [comment]
java console project,use this command can run:
cd ${current.project.path} && javac -classpath ${project.java.classpath} -sourcepath ${project.java.sourcepath} -d ${project.java.output.dir} src/Main.java && java -classpath

**Comment by chendongping** [comment]
but  make this command is difficult for developer , should it be automation?

**Comment by TylerJewell** [comment]
The templates provide much of the automation built in for different types. This is why many developers use maven.
