### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by Pyjou** [eclipse-che/che#224]
When I go to create a project, it remains on this [INFO] :

![](http://i.imgur.com/yf6Ox9P.png)

I use Docker image on Ubuntu 14.04

**Comment by TylerJewell** [comment]
Hi @Pyjou:  We could use some more details:
1. Did you run Che as a docker image itself, or were you just indicating that your docker daemon is running on Ubuntu.  The networking configuration varies between the two.
2. The workspace agent was started successfully, but for some reason the notification that the agent was booted did not make its way back to the ws master. This probably means that there is some sort of issue with how the workspace agent networking is setup to reach back to the ws-master.  So, can you ssh into that container, and can you ping the IP address of the node where che server is running?
3. The workspace is booted - so maybe you can jump right into the ide.  Can you jump into /ws/{ws-name} or /ide/{ws-name} to have the IDE load with this workspace?  If this is successful, then that tells us there is something that is preventing the agent calling back to the server.

**Comment by ghost** [comment]
Are you running Che on a remote machine? Or is it a local Ubuntu?

**Comment by randywallace** [comment]
I have to +1 this.

After many, many hours deep in Vagrant (I like running custom VM's for docker) and the CHE codebase configs and whatnot... I too have run into this.

It seems to me like the workspace agent should not be run in the foreground... (https://github.com/codenvy/che/blob/aeddc889fc71778cc51d154ff5debb02e62f3c03/assembly-ide-war/src/main/java/org/eclipse/che/api/deploy/ApiModule.java#L123) perhaps `catalina.sh jpda start` instead of `catalina.sh jpda run` ?

I'll test it locally and see if that works for me...

**Comment by randywallace** [comment]
Note that I did get to the workspace/ide as you suggest @TylerJewell, but since it never successfully starts the agent, it acts very goofy. 

Version: 4.0.0-beta-13 and master
Docker: 1.9.1
Recipe attempted: ubuntu_jdk8

Running with the docker-in-docker scenario.

Here is the processlist of the agent container as it hung there: 

```
user@52f1a1010b0c:/$ ps -Af
UID        PID  PPID  C STIME TTY          TIME CMD
user         1     0  0 08:15 ?        00:00:00 /bin/sh -c sudo /usr/sbin/sshd -D &&     tail -f /dev/null
root         6     1  0 08:15 ?        00:00:00 sudo /usr/sbin/sshd -D
root         7     6  0 08:15 ?        00:00:00 /usr/sbin/sshd -D
user         8     0  0 08:15 ?        00:00:00 /bin/bash -c trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-1.pid ] && rm /tmp/docker-exec-1.pid' EXIT; echo $$>/tmp/docker-exec-1.pid; rm -rf ~/che && mkdir -p ~/che && unzip /mnt/che/ws-agent.zip -d ~/
user        16     8  2 08:15 ?        00:00:11 /opt/jdk1.8.0_45/bin/java -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms256m -Xmx1024m -server -Dche.logs.dir=/home/user
user        61     0  0 08:15 ?        00:00:00 /bin/bash -c mkdir -p ~/che && cp /mnt/che/terminal -nR ~/che&& ~/che/terminal/terminal -addr :4411 -cmd /bin/bash -static ~/che/terminal/
user        67    61  0 08:15 ?        00:00:00 /home/user/che/terminal/terminal -addr :4411 -cmd /bin/bash -static /home/user/che/terminal/
```

so at least to my casual eye everything _seems_ to be running that should be, no?

And here is the processlist of the che container's nested docker to show the port forwarding:

```
user@4bc7d12a1e11:/$ docker ps -a
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                         NAMES
52f1a1010b0c        eclipse-che/che_workspacejq80a4cp5p6i7di9_ws-machine_woqat   "/bin/sh -c 'sudo /us"   19 minutes ago      Up 19 minutes       0.0.0.0:32774->22/tcp, 0.0.0.0:32773->4401/tcp, 0.0.0.0:32772->4403/tcp, 0.0.0.0:32771->4411/tcp, 0.0.0.0:32770->8000/tcp, 0.0.0.0:32769->8080/tcp, 0.0.0.0:32768->9876/tcp   che_workspacejq80a4cp5p6i7di9_ws-machine_woqat
```

I also confirmed that the agent container can ping successfully to the host container and to the interwebs.

Regards.

**Comment by ghost** [comment]
So, you are running Che in a VM? And then access it via IP address, not localhost, correct? If so, you need to pass VM IP address to startup script:

./che.sh -r:ip -run where ip is an actual IP of your VM box.

As to the way a ws agent is started, it does not really matter in this case.

**Comment by randywallace** [comment]
I have to admit, that worked.  Not exactly why it worked, but it did.  I had tried that a few times to fix other things then removed it.. to think I was skulking around trying to figure out why `machine.docker.che_api.endpoint` was working just fine from the agent to master..

**Comment by ghost** [comment]
This parameter lets client code know where Docker is, thus connect to workspace agent that is running inside a container via websockets.

**Comment by TylerJewell** [comment]
@eivantsov: this parameter seems to be the reason that many new installations are failing.  And it is a simple parameter to add.  Maybe we should consider making it mandatory with instructions how to provide its value.  And then for select installations developers can choose to ignore it if they provide an override.

**Comment by randywallace** [comment]
In your defense, though, the docker logs do, via the `che.sh`, indicate rather clearly that I _really_ should set that, although I didn't.  I assumed that since many things _were_ working right, that this one thing couldn't have been affected by that.

**Comment by TylerJewell** [comment]
Well thank you... but in the defense of users, what is happening now is that the Che server always starts, and we plop you right into that beautiful dashboard. And it's a reasonable expectation from most users that if the browser can connect to the dashboard over localhost, then the product is working.  It's a reasonable leap for any user to conclude that workspace creation & connection should also work.  Even though we have provided a lot of docs on the importance of setting the --remote:ip variable, the error occurs at the worst possible time (after you have used the product and only after the workspace has been generated, and at the last moment where the browser is now attempting to connect to its new workspace).  It's very hard for a user to connect that they needed to set a startup parameter when they are 10 minutes into the product usage.

So, I think solutions to this are:
1. We can embed inside of our APIs some helpful messages when browsers fail to connect to new workspaces. It's_likely_ the case that the server was not set with --remote:ip, so we can say, "Hey, did this happen?  You might have forgotten to set this.  See these docs, and just restart Che."
1. We could consider proxying all terminal, ws-agent, and websocket communications between browser and workspace _through_ the Che server, which internally knows how to communicate to the workspace. Performance would take a sizable hit, and the complexity level would jump.  But users would be guaranteed that if their browser can connect to the Che server, then it will connect to the workspace, too.
2. Or, we could _force_ all users to set --remote:ip to the appropriate value for all Che runs.  We prevent the server from starting.  This will annoy users who just need localhost access as unnecessary.  But for all other users, we surface the issue of remote connectivity before the che server starts.

**Comment by Pyjou** [comment]
--remote:ip working for me thanks

**Comment by Pyjou** [comment]
Sorry but I've one more question, Is it possible to have a user system ?

**Comment by TylerJewell** [comment]
Can you elaborate on what you mean by user system?  

If you are asking about whether there can be account management with authentication, authorization, permissions, and access controls.  Then, yes, it is built into the system that it can be extended that way.  However, currently, Che is a single server, multi-workspace, single identity system. You can have many users using different workspaces, but they share a single identity.

https://eclipse-che.readme.io/docs/scaling
There are three ways to overcome this:
1. You can run a Che farm with nginx router in front of the farm, where there is one Che install for each user.  
1. You can upgrade to Codenvy which is a multi-tenant implementation of Che with account management.
2. You can extend the Che service interfaces with a different implementation of user and account management. The APIs are all there and you can extend the system to include a user database with authentication.

I am going to close this issue as the original problem has been solved.  You can open other tickets if you'd like.
