### ISSUE TITLE
Unable to import GitSwarm Projects

### ISSUE THREAD

**Issue by rajasekaran07** [eclipse-che/che#2244]
[Short description of problem here]

I am trying to import my GitSwarm project in Eclipse Che using Git But I am getting below error.

![image](https://cloud.githubusercontent.com/assets/19193992/18046390/4da55210-6df5-11e6-8a74-f1bf860e28ba.png)

**Reproduction Steps:**
1. [First Step]

Opened Eclipse Che and clicked workspace and import project
1. [Second Step]

Source Control ->Git and entered GitSwarm URL to import.
1. [Other Steps...]

Please note that we are using private cloud with Internal IP. Both Eclipse Che and GitSwarm are running on internal IP only.

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Che version:**    [Enter Che version here]   

WARNING: No swap limit support
DEBUG: ---------------------------------------
DEBUG: ---------  CHE CLI DEBUG INFO  --------
DEBUG: ---------------------------------------
DEBUG:
DEBUG: ---------  PLATFORM INFO  -------------
DEBUG: DOCKER_INSTALL_TYPE       = native
DEBUG: DOCKER_HOST_IP            = 172.17.0.1
DEBUG: IS_DOCKER_FOR_WINDOWS     = NO
DEBUG: IS_DOCKER_FOR_MAC         = NO
DEBUG: IS_BOOT2DOCKER            = NO
DEBUG: IS_NATIVE                 = YES
DEBUG: HAS_DOCKER_FOR_WINDOWS_IP = NO
DEBUG: IS_MOBY_VM                = NO
DEBUG:
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
INFO:
INFO: ECLIPSE CHE: FOUND IMAGE codenvy/che-launcher:latest
INFO: ECLIPSE CHE: LAUNCHING LAUNCHER

**OS and version:** [Enter OS name and version here]   

Linux ipaclient.openshift.loc 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Docker version:** [Enter your Docker version here `docker version` on CLI]   

root@ipaclient:/home/bcause/Downloads# docker version
Client:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:18:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:18:04 2016
 OS/Arch:      linux/amd64

**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by rajasekaran07** [comment]
Also I would like to know how to make Git server communication in Eclipse Che to reflect our changes in GitSwarm.

**Comment by rajasekaran07** [comment]
Hi Team,

Now I have imported my project into Eclipse Che but I am unable to push my changes in to GitSwarm remote repository.

![image](https://cloud.githubusercontent.com/assets/19193992/18050886/e5bc490a-6e0e-11e6-860b-8d4d1bd39ca4.png)

I have configured my user.name and user.email but still i cant push my code. Help me on this.

**Comment by ddementieva** [comment]
@rajasekaran07 You've tried to import your project with HTTP URL. You need to use SSH URL for that.

Also you need to generate SSH key to be able to push changes. You can do that at Profile > Preferences > SSH > VCS. The hostname will look something like 10.172.112.34. Copy a newly generated SSH key and save to the GitSwarm settings.

**Comment by rajasekaran07** [comment]
@ddementieva Thanks for your comment. Can we do this by http URL?
If possible please let me know the steps.

**Comment by ghost** [comment]
@rajasekaran07 http URL will require login password. You may want to try having them in the URL itself

**Comment by rajasekaran07** [comment]
@eivantsov Thanks for your help.. Its working now..
