### ISSUE TITLE
Build Che Using Docker - npm error

### ISSUE THREAD

**Issue by motorina0** [eclipse-che/che#2247]
Trying to "Build Che Using Docker" as described here: 
https://github.com/eclipse/che/wiki/Development-Workflow#build-che-using-docker

**Reproduction Steps:**
1. Install latest version of Docker Toolbox
2. Start and connect to the VM
3. Run the docker command for running the Che build (see docker-che-build.txt)

**Expected behavior:**
Build runs with success. On my host's Maven repo I have all the Che artifacts

**Observed behavior:**
Build Fails with:
An Ant BuildException has occured: exec returned: 185 around Ant part ...<exec failonerror="true" dir="/home/user/che-build/dashboard" executable="npm">... @ 4:82 in /home/user/che-build/dashboard/target/antrun/build-main.xml

Attached two files with the logs from "docker run" and "npm" (docker-che-build.txt and npm-debug.log )

**Che version:**    Source Code (branch created from tag 4.6.1)
**OS and version:** Windows 7 Profesional
**Docker version:** 
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

**Che install:**    Docker

**Additional information:**
Increased VM memory from 1 GB to 3GB, but build still fails.
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
  - older versions did not had build using Che
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by motorina0** [comment]
Log files:
[docker-che-build.txt](https://github.com/eclipse/che/files/442577/docker-che-build.txt)
[npm-debug.log.txt](https://github.com/eclipse/che/files/442578/npm-debug.log.txt)

**Comment by TylerJewell** [comment]
@benoitf - assigned to you.

**Comment by ghost** [comment]
@motorina0 This is a VBox issue. When dashboard is built, a symlink is created. Since project sources are mounted in your Windows OS, it is not allowed to create symlinks there.

https://github.com/npm/npm/issues/9901 similar issue

**Comment by benoitf** [comment]
@motorina0 could you add after line
https://github.com/eclipse/che/blob/master/dashboard/pom.xml#L63

```
 <arg value=" --no-bin-links" />
```

**Comment by motorina0** [comment]
updated like this:

```
       <!-- Download NPM dependencies -->
       <exec dir="${basedir}" executable="npm" failonerror="true">
          <arg value="install" />
          <arg value="--no-bin-links" />
       </exec>
```

Got new error:

```
     [exec] npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
     [exec] npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
     [exec]
     [exec] (null):0
     [exec] (null)
     [exec]
     [exec] RangeError: Maximum call stack size exceeded
[INFO] ------------------------------------------------------------------------

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (compile) on project che-dashboard-war: An Ant BuildException has occured: exec returned: 7
[ERROR] around Ant part ...<exec failonerror="true" dir="/home/user/che-build/dashboard" executable="npm">... @ 4:82 in /home/user/che-build/dashboard/target/antrun/build-main.xml

```

**Comment by benoitf** [comment]
could you run again ? it seems first run fails while second run succeed with npm --no-bin-links ...
https://github.com/npm/npm/issues/9953

**Comment by motorina0** [comment]
Second run gave me:

```
    [exec] npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
     [exec] npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
     [exec] npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
     [exec] npm ERR! Linux 4.4.16-boot2docker
     [exec] npm ERR! argv "node" "/usr/local/bin/npm" "install" "--no-bin-links"
     [exec] npm ERR! node v0.12.9
     [exec] npm ERR! npm  v3.10.5
     [exec] npm ERR! path /home/user/che-build/dashboard/node_modules/ng-annotate-loader/node_modules/source-map
     [exec] npm ERR! code EPERM
     [exec] npm ERR! errno -1
     [exec]
     [exec] npm ERR! Error: EPERM, rename '/home/user/che-build/dashboard/node_modules/ng-annotate-loader/node_modules/source-map'
     [exec] npm ERR!     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:64:7
     [exec] npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
     [exec] npm ERR!     at Array.forEach (native)
     [exec] che-dashboard@4.0.0 /home/user/che-build/dashboard
     [exec] ├─┬ babel-core@6.14.0
```

See also attached files  [docker-che-build2.txt](https://github.com/eclipse/che/files/442679/docker-che-build2.txt) and  [npm-debug2.log.txt](https://github.com/eclipse/che/files/442678/npm-debug2.log.txt)

**Comment by motorina0** [comment]
Second run gave me:

```
    [exec] npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
     [exec] npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
     [exec] npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
     [exec] npm ERR! Linux 4.4.16-boot2docker
     [exec] npm ERR! argv "node" "/usr/local/bin/npm" "install" "--no-bin-links"
     [exec] npm ERR! node v0.12.9
     [exec] npm ERR! npm  v3.10.5
     [exec] npm ERR! path /home/user/che-build/dashboard/node_modules/ng-annotate-loader/node_modules/source-map
     [exec] npm ERR! code EPERM
     [exec] npm ERR! errno -1
     [exec]
     [exec] npm ERR! Error: EPERM, rename '/home/user/che-build/dashboard/node_modules/ng-annotate-loader/node_modules/source-map'
     [exec] npm ERR!     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:64:7
     [exec] npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
     [exec] npm ERR!     at Array.forEach (native)
     [exec] che-dashboard@4.0.0 /home/user/che-build/dashboard
     [exec] ├─┬ babel-core@6.14.0
```
See also attached files  [docker-che-build2.txt](https://github.com/eclipse/che/files/442679/docker-che-build2.txt) and  [npm-debug2.log.txt](https://github.com/eclipse/che/files/442678/npm-debug2.log.txt)

**Comment by ghost** [comment]
@motorina0 do you absolutely need to build dashboard? Is building just an assembly a way to go for you?

I cannot reproduce it on Ubuntu and CentOS.

**Comment by motorina0** [comment]
I did wanted to build the dashboard since I wanted to do some customization.
I will run the normal build on Windows then. Thank you.

Issue can be closed from my side.

**Comment by motorina0** [comment]
It would be useful to specify on the [wiki](https://github.com/eclipse/che/wiki/Development-Workflow#build-che-using-docker) that on Windows with Docker Toolbox there are still some issues.
Just updating the paths does not seam to be enough

```
# For Windows, replace $HOME with maven repo directory.
# For Windows, replace $PWD with Che source code directory.
```

**Comment by benoitf** [comment]
@motorina0 ok thanks for the report I've updated the wiki with a note for errors on Windows for Dashboard module
