### ISSUE TITLE
Unexpected appearance of the second terminal after refresh

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2249]
**Reproduction Steps:**
- Create some workspace and open in the IDE.
- Perform a refresh.

**Expected behavior:**
Should be one terminal after refresh.

**Observed behavior:**
Two terminals are displayed after refresh.

[Describe observed behavior here]

**Che version:**  4.7.0  
**OS and version:** Ubuntu 14.04  
**Docker version:** 1.11.1  
**Che install:**  Docker container

**Additional information:**
See the attachment.
![two_terminal_after_refresh](https://cloud.githubusercontent.com/assets/5408906/18056449/951d39ea-6e14-11e6-8152-cae8973a4c60.gif)

**Comment by TylerJewell** [comment]
Possibly related.
https://github.com/eclipse/che/issues/2324

**Comment by riuvshin** [comment]
#2324 is duplicate and should be closed.

**Comment by vparfonov** [comment]
https://github.com/eclipse/che/pull/2341
