### ISSUE TITLE
"Error while creating the project - Internal Server Error: Unable get private ssh key"

### ISSUE THREAD

**Issue by gzsombor** [eclipse-che/che#225]
I've tried to setup a project, specifying an internal git url, the setup runs fine for a couple of minutes, but after it shows an error dialog : "Error while creating the project
Internal Server Error: Unable get private ssh key" 

After I can't do anything, retry doesn't work - and I don't know how to configure this private ssh key thing.

**Comment by ghost** [comment]
Did you try to import a project using ssh Git URL? Were you trying it in a dashboard or in the IDE itself?

**Comment by gzsombor** [comment]
Yes, I've tried ssh git url, like " ssh://xxx.yyyy@gerrit.internal.corporate:29418/importantproject" - unfortunately the same thing happens, even if I create an empty project, and later try to import from git from the menu

**Comment by ghost** [comment]
When in the IDE, go to Help > Settings > SSH and generate a key for your server. Copy this key and save it on your server. This should fix the problem.

**Comment by gzsombor** [comment]
Sorry, this is not a github URL, but a simple git ssh url (managed by gerrit btw), so GitHub oAuth hardly helps

**Comment by ghost** [comment]
I have updated my comment.

**Comment by gzsombor** [comment]
Thanks, it worked ! Sorry :)

**Comment by ShashankaNataraj** [comment]
Clicking on the help item in the burger menu results in a browser redirect to the eclipse che page. Has this settings option been removed from the latest releases?
