### ISSUE TITLE
Cannot use github without oauth

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2253]
Without setting up oauth with github, I cannot use the the git menu to push changes after setting up an ssh key pair.

**Reproduction Steps:**
1. Add Committer Information
2. Add new host under ssh->VCS.
3. Import my repo from github.
4. Copy/paste public key from vcs to github account.
5. Make change to file to imported project, git add, git commit, and git push.

![github](https://cloud.githubusercontent.com/assets/20580888/18062597/168bd784-6ded-11e6-984f-3cd7d29cabaf.gif)

**Expected/Enhanced behavior:**

Through the `git->remotes->push` push changes to my github repo . I think the oauth is required/expected by the documents at [https://eclipse-che.readme.io/docs/git](https://eclipse-che.readme.io/docs/git) but I would like to use github by setting up only ssh keypairs without setting up oauth. Note: I have successfully done pushed to bitbucket.org by setting up ssh keypairs.

**Observed behavior:**

Unauthorized message pops up when I try to push to my account using ssh keypairs without oauth setup.

**Che version:**    nightly 4.7 snapshot  
**OS and version:**    Ubuntu 16.04.1 LTS
**Docker version:** 
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

**Che install:**   Google cloud

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No] No
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes

**Comment by bmicklea** [comment]
This may be related to https://github.com/codenvy/codenvy/issues/656

**Comment by riuvshin** [comment]
it is not related to codenvy/codenvy#656

**Comment by bmicklea** [comment]
@vparfonov it seems this has been the normal behavior for some time but we need to change it. A user shouldn't have to setup GitHub oAuth just to do commits. Setting up SSH key pairs and setting up oAuth are two separate actions and it should be easy for a user to setup GitHub SSH key pairs.

**Comment by riuvshin** [comment]
Issue is not actual.

**Comment by JamesDrummond** [comment]
@riuvshin Thanks!

Alright looks like you need to use the ssh link not the https link. Will update the docs to include this just in case someone else has the same issue.

HTTPS used with oauth only.
![image](https://cloud.githubusercontent.com/assets/20580888/18068995/e17f388e-6e09-11e6-90e7-01d28da3b847.png)

Click `use SSH` link at top right shown in image above. This can be used with ssh without having to setup oauth.
![image](https://cloud.githubusercontent.com/assets/20580888/18069014/fe2658d2-6e09-11e6-9cd0-721781df2186.png)

**Comment by JamesDrummond** [comment]
@bmicklea Can you remove all labels and milestone?
