### ISSUE TITLE
Investigate what should be done to run che-server/che-launcher in docker with swarm mode

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2254]
We need an assessment of what changes should be made to Che server and, if appropriate, che-launcher when configuring Che to run on Swarm. How will users tell Che how to use Swarm, what are the properties. We need to see whether there will be a significant impact on configuring the Che launcher and maybe the CLI.

**Comment by skabashnyuk** [comment]
won't fix, che-launcher has been deprecated
