### ISSUE TITLE
Lockout github 'Octocat' icon and import page without oauth properties set.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2256]
I would like to disable the 'Octocat' icon in `preferences=>vcs` if the oauth properties have not been set and give a hover over message that tells the user to set these values to enable the icon. Also I would like the `github` menu item in `import projects` disabled with a similar hover over message too. 

![image](https://cloud.githubusercontent.com/assets/20580888/18067495/b24d336a-6e02-11e6-82f8-17eff65e780d.png)

![image](https://cloud.githubusercontent.com/assets/20580888/18067473/a3c7cf44-6e02-11e6-926e-82791e11f012.png)

update 9/6/16:
Disable the 'Octocat' icon: Gray out 'Octocat' icon to indicate it's not usable. If user clicks or hovers over the grayed out 'Octocat' icon, a warning message would appear telling users to configure oauth and refer to git documentation for additional information. I am ok with just a hover over message without the click popping up a window though but popup won't hurt anything.

Disable import project -> github: When user clicks on import project -> github menu item, open project input forms and load repo button on right side of window as normal but grayed out and disabled. Insert message(in red?) at top on right side telling users to configure oauth and refer to git documentation for additional information.

**Comment by bmicklea** [comment]
@JamesDrummond would it be clear enough to have a popup that clearly explains what needs to be done?  I can see disabling in Codenvy where enterprises may not have or want developers accessing GitHub but for an open source project disabling seems too extreme...

**Comment by JamesDrummond** [comment]
@bmicklea I am fine with not disabling as long as there is some warning to the user. A popup that tells user how to setup the feature instead of actually failing when performed. Not sure what allowing a user to fail oauth would accomplish if we can determine it failing before hand by missing oauth information.

**Comment by bmicklea** [comment]
Great, then @JamesDrummond please update this issue to clarify that this is a need for a popup and add a new enhancement issue in codenvy/codenvy to add the ability to disable the octocat.

**Comment by JamesDrummond** [comment]
@bmicklea I think changes to che will effect codenvy automatically. Should I provide issue the references this in codenvy rep0? 

What do you think about the following to define what "disable" is?

Disable the 'Octocat' icon: Gray out  'Octocat' icon to indicate it's not usable. If user clicks or hovers over the grayed out 'Octocat' icon, a warning message would appear telling users to configure oauth and refer to git documentation for additional information. I am ok with just a hover over message without the click popping up a window though but popup won't hurt anything.

Disable `import project -> github`: When  user clicks on `import project -> github` menu item, open  project input forms and load repo button on right side of window as normal but grayed out and disabled. Insert message(in red?) at top on right side telling users to configure oauth and refer to git documentation for additional information.

**Comment by bmicklea** [comment]
That experience makes sense, please edit the title and description to represent this.

For Codenvy my thought was that we should allow admins to entirely turn off the octacat button - make it disappear. However, that's not really necessary so we'll ignore for the moment.

**Comment by JamesDrummond** [comment]
@bmicklea We could consider providing ways to lockout features. Might consider opening another issue with a list of things that we can disable through the use of environment variables such as `CHE_GITHUB` where the default value is true. There could be many things that admins could do to remove features not needed or wanted. Think this would still be a che feature though that would then be included into codenvy. I would think this would be more of an epic. 

Can you label this task/enhancement for us.
