### ISSUE TITLE
'conditional binary operator expected' error

### ISSUE THREAD

**Issue by vandershraaf** [eclipse-che/che#227]
che/assembly-main/src/assembly/bin/che.sh

Specifically line #341

```
if [[ "${LINUX_GROUPS}" =~ "docker" ]] ; then
```

It should be "==" (comparison symbol), not "=~" (Perl's regex?). When I ran the script, it threw "line 342: conditional binary operator expected" error. I ran the script in Windows 10. Changed the symbol myself and the error no longer happens. Let me know if you need more information or have comments on this.

**Comment by garagatyi** [comment]
Looks like your bash doesn't support this operation. Can you check your version of bash?
Please try to replace this conditional operator with `if groups $(whoami) | grep "docker" &>/dev/null; then`
Is it working in with that change?

**Comment by vandershraaf** [comment]
Yup, it seems to work. So the code should be changed to the one you gave, yes?

**Comment by garagatyi** [comment]
I think yes. I'll submit PR with that fix shortly.

**Comment by vandershraaf** [comment]
Coolio. Thanks for looking into this

**Comment by garagatyi** [comment]
PR merged, so I close this issue.
