### ISSUE TITLE
chrome developer tools network show ”Provisional headers are shown“

### ISSUE THREAD

**Issue by lishoujun** [eclipse-che/che#2270]
[Short description of problem here]
Using `docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e  "CHE_HOST_IP=(my server ip)xx.xx.xx.xx" eclipse/che start`  to start my che.
open my che in  chrome 
create a workspace 
open the workspace 

![_100](https://cloud.githubusercontent.com/assets/8399413/18115544/b9ccf01e-6f72-11e6-899a-d3af781a8534.png)

![_101](https://cloud.githubusercontent.com/assets/8399413/18115905/db7f89e4-6f75-11e6-82b6-86ca135e9a1b.png)

http://115.159.108.33:8080/   you can try it.

**Che version:**    where show this info?
*_OS and version:debian 8.2
*_Docker version:
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
**Che install:**   Docker container

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ddementieva** [comment]
@lishoujun It seems the ephemeral port range was previously blocked. Now we can reach the workspace, however, the Terminal is not launched. It looks like it's a bug on Che side. Investigating.

Can you try to create a new workspace and run it?

**Comment by lishoujun** [comment]
@ddementieva  
“Can you try to create a new workspace and run it?”
you mean create in chrome ？  or run some command  in Terminal？

**Comment by ddementieva** [comment]
@lishoujun On the Dashboard go to the Workspaces tab, click `+` button and create a workspace with any stack provided. Open it in the IDE.

**Comment by ghost** [comment]
@lishoujun I was able to properly run a workspace on your instance.

What I have noticed is that sometimes the client cannot connect to a workspace agent or a terminal, and I suspect this has smth to do with resources availability. How much RAM and how many cores does your instance have?

![screen](https://cloud.githubusercontent.com/assets/5337267/18158537/91dfbdc4-702c-11e6-860b-a0512cb6d122.png)

**Comment by lishoujun** [comment]
@eivantsov 1GB 1 core          I know ^-^...

**Comment by ghost** [comment]
I think 2GB and 2 cores is the minimum. All these issues are expected. A workspace agent just cannot start.
