### ISSUE TITLE
Make Che with debug flag use default log level instead of debug log level

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2272]
Debug mode of Che enables debug log level of Che java application. This level of debug is almost never used. It can produces tens of gigabytes of logs in several days. 

It would be better to allow debugging of Che when debug mode is enabled by leave log level unchanged. 
Then debug log level with debugging can be set with another flag , e.g. -dd instead of -d

**Che version:**    Che 4.7.0
**OS and version:** Ubuntu 14.04
**Docker version:** docker 1.12
**Che install:**    Linux native  
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by bmicklea** [comment]
@garagatyi  who should this be assigned to for effort estimation?  Please take it yourself or assign to a team lead to assess.

**Comment by garagatyi** [comment]
@TylerJewell are you ok if I change behavior of --debug flag of che.sh to not change debug level and just start tomcat in debug mode? 
It will still be possible to change log level with `-l:level,  --logs_level:level` syntax.

**Comment by TylerJewell** [comment]
I do not understand the request.  The che.sh file that is in the root of the reps outcry does not have a --debug flag as part of it.  Can you be more explicit on what is being proposed?

Note that customers are not encouraged to run Che server natively - so any embedded Che server alterations also affects how the che-server container must operate and be configured

**Comment by garagatyi** [comment]
ok, then, please, explain your vision on which way you are encouraging to use for development of Che and how to debug Che without changing default logging level.

**Comment by TylerJewell** [comment]
The only acceptable use of Che is through the Che-launcher, which calls the che-server container.

When using Che launcher users can have the che-server use a local binary by setting env variable pointing to its location.  

I don't have a vision for how the Che server should be changing its logging level.  But if it is to be done then it should only through use of env variables passed into the che-server container.  Please draft specification of how it should work and exactly which parameters should be set

**Comment by bmicklea** [comment]
@garagatyi when an issue is closed please add the milestone label. If the issue has been closed for some reason other than a code commit please clarify the reason for closing.

**Comment by garagatyi** [comment]
It was fixed. I added the milestone.
