### ISSUE TITLE
Proper C# support for Che

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#2274]
it seems that Che  has the ability to recognize and write C# programs  but limited to ASP.NET programs.
It would be beneficial if Che has the ability to actually compile non-ASP.NET programs written in C#.
is it possible?

**Proposed Ideas**
-support for Mono (if possible).
-Automatic dependency checking (can be extended to support a variety of languages supported by Che currently).
-ability to open Visual Studio Solution files (.sln) (if possible, seems needed for the dependency lists too).

**Comment by ddementieva** [comment]
@sr229 Labeling it as enhancement.

Have you tried to install some compiler, e.g. Mono, for C# applications? You can do that manually in the Terminal.

**Comment by sr229** [comment]
I did try, but it would be better if it's defaulted for the dotnet stack

**Comment by TylerJewell** [comment]
@sr229 - can you propose a pull request that improves the default stacks?  We will be shipping language server intellisense for C# in a couple months.

**Comment by TylerJewell** [comment]
We have shipped this capability - it's now merged into 5.0.0-M2.
