### ISSUE TITLE
GitHub SSH key generation and uploading is not working on private project importing

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#2277]
When importing private project, user will be prompted with a dialog for authorizing through GitHub, as well as optionally generating and uploading SSH key. If that option is on, importing will fail, because of failed SSH key uploading.

**Reproduction Steps:**
1. Open in IDE top menu Workspace - Import project.
2. Select 'Git', enter URL of the GitHub private repo.

**Expected behavior:**

Project is successfully imported, as well as ssh key is generated and uploaded to GitHub

**Observed behavior:**

Project is not imported, nor key is generated/uploaded.

**Che version:**    4.8.0-SNAPSHOT

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by slemeur** [comment]
This issue is still accurate:
![screen shot 2017-04-18 at 19 12 53](https://cloud.githubusercontent.com/assets/1636769/25143532/1907b886-246b-11e7-85ae-5e55952bd207.png)

**Comment by vinokurig** [comment]
@slemeur Could you please check this issue again. I can't reproduce it.

**Comment by vinokurig** [comment]
Can not reproduce
