### ISSUE TITLE
Remote Che: terminal unavailable

### ISSUE THREAD

**Issue by ddementieva** [eclipse-che/che#2281]
Terminal doesn't launch in the remote Che

**Reproduction Steps:**
1. Start Che with Vagrantfile.
2. Create any workspace, open it in the IDE.

**Expected behavior:**

Terminal is available.

**Observed behavior:**
Terminal is unavailable.

**Che version:**    4.8.0
**Che install:**    Vagrant

**Comment by ghost** [comment]
It turns out that `terminal` never gets copied over to ~/che/terminal. Adding some sleep command before this exec should fix it.

@garagatyi may also suggest code changes on how to get terminal logs as part of machine logs.

**Comment by TylerJewell** [comment]
When @riuvshin and I saw this issue, we were looking inside the container and it seemed that the terminal was mounted.  But the start command was flawed and it wouldn't start.  Looks like you uncovered some other behaviors that are preventing this.

**Comment by ghost** [comment]
The terminal never gets `copied` not mounted. It is available in `/mnt/che/terminal` but not in `~/che/terminal` where this exec expects it - https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java#L71

**Comment by ghost** [comment]
Tested remotely with Difital Ocean - cannot reproduce. Also, failed to reproduce on Windows, where a workspace container is running in a Virtual Box VM.

So, I suspect that the remote scenario isn't the key here since such a behavior used to be observed locally as well. Most probably it has smth to do with Docker performance - for instance an exec happens before the mount is set up.

**Comment by riuvshin** [comment]
That issue will be fixed once @tolusha  merge https://github.com/eclipse/che/issues/1823

**Comment by riuvshin** [comment]
why we keep duplicate issues open? It seems we should close #2322 and keep this issue
