### ISSUE TITLE
Grammar for PHP tag doesn't support all cases

### ISSUE THREAD

**Issue by mniewrzal** [eclipse-che/che#2283]
Grammar for PHP tag doesn't support all cases

**Reproduction Steps:**
1. Create php file
2. Paste
   `
   <html>
   <body>
   
   <?=$somevar->get('test')?>
   
   <?= $somevar->get('test')?>
   </body>
   </html>
   `

**Expected behavior:**

Both PHP tag examples should be highlighted as PHP.

**Additional information**
Fix for this issue is already in Orion master (https://bugs.eclipse.org/bugs/show_bug.cgi?id=500497). Only thing to fix this in Che is to update Orion editor to latest.

**Comment by ddementieva** [comment]
@mniewrzal We are planning to update Orion to 12. You can track the following issue https://github.com/eclipse/che/issues/1900
