### ISSUE TITLE
Gray out menus until the workspace is not loaded or stopped

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2286]
The goal of this issue is to gray out certain menus while the workspace is either starting or has been stopped.

Menu to be grayed out:
- Project
- Machine
- Edit
- Assistant
- Run
- Profile
- Git
- Subversion

**Comment by bmicklea** [comment]
@slemeur who should this be assigned to?  Please take it yourself or assign to a team lead to asses.
