### ISSUE TITLE
Change octocat icon to be white

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2287]
The octocat icon in black is not visible on the dark theme.

<img width="513" alt="screen shot 2016-08-31 at 16 57 56" src="https://cloud.githubusercontent.com/assets/1636769/18133803/54ad8124-6f9c-11e6-871d-8f0974595369.png">

For dark theme:
- We need to change it to be white over gray button

For light theme:
- We need to keep it black over the light gray

**Comment by bmicklea** [comment]
@slemeur who should this be assigned to?  Please take it yourself or assign to a team lead to asses.
