### ISSUE TITLE
Fix tag on default template "web-javaee-jaxrs"

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2290]
The web-javaee-jaxrs template appears when you select the default Java stack, however, this template actually requires the "TomEE" stack in order to build and run properly.

**Reproduction Steps:**
1. Select Java stack
2. Select web-javaee-jaxrs template
3. Create workspace
4. Try and build app and you'll get an error because $TOMEE_HOME isn't defined because it's not part of this stack.

**Expected behavior:**
I only see templates that work with my stack so this template should only appear if I select the TomEE stack.

**Che version:**    4.6+
**Che install:**   verified on che 4.7, codenvy on-prem 4.6.2 and beta.codenvy.com 4.7

**Comment by bmicklea** [comment]
@ddementieva I spoke to Eugene about this and he said you could retag this template so that it will only show up with the TomEE stack.

**Comment by ghost** [comment]
https://github.com/eclipse/che/pull/2376
 Closing it.
