### ISSUE TITLE
Node console template not showing up

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2291]
When you select the default Node stack only the node web app template appears. However, there's a node console template that you can see in the full list of templates. (perhaps this is a tagging issue?)

**Reproduction Steps:**
1. Go to the dashboard page for creating a new workspace + project
2. In the Workspace section, select the Node stack
3. In the Templates section, notice only the node web app template is the only one there
4. Go back to the Workspace section and select Custom Stack
5. In the Templates section you'll now see both a web and console app template for node.

**Expected behavior:**
Both web and console templates should be shown for the Node app

**Observed behavior:**
Only the web app template is shown.

**Che version:**    4.6+
**OS and version:** Mac OS 10.11.6
**Che install:**   Docker launcher + beta.codenvy.com (4.7)

**Comment by ghost** [comment]
https://github.com/eclipse/che/pull/2376

Fixed.
