### ISSUE TITLE
Unexpected alert  is displayed in the 'git compare form'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2299]
This bug is reproduced into branch CHE-1818

**Reproduction Steps:**
1. Open java file and type some content in the editor.
2. Go to - > 'Git' - > 'Compare' - > 'Compare with latest repository version'.
3. Set the focus into 'git compare form'.
4. Perform 'Go to Line' (press Ctrl + L).

**Expected behavior:**
Should be displayed the 'Go to line' widget.

**Observed behavior:**
The alert  is displayed after invoking the 'Go to Line'.

**OS and version:**
Che(Che6 branch) 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by artaleks9** [comment]
This issue is actual into master branch and right now it is reproduced for CHE version 5.6.0

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by artaleks9** [comment]
Still actual in 6.13.0
