### ISSUE TITLE
any documentation for backup workspaces before upgrade/rebuild new github updates?

### ISSUE THREAD

**Issue by mleader1** [eclipse-che/che#230]
Hi,

I'm not very familiar with maven (I'm converted from Microsoft and run asp.net 5 on Eclipse Che), is there a way to keep all my workspace and project source files?

I always keep myself pioneered with latest github update of Eclipse Che however whenever I run "mvn clean install" it obviously deletes everything so I have to create my workspace, download source code of my projects and modify build commands again which is very not productive. (I use my own aspnet stack).

Is there a way to preserve all my work already in current Che?  Anyone throw me some lights please...

thx.

**Comment by ghost** [comment]
Hi,

Take a look here - https://eclipse-che.readme.io/docs/configuration

Basically, you need to export CHE_LOCAL_CONF_DIR, point it to a local directory, create a .properties file in that directory, and in that file override the following properties:

che.user.workspaces.storage=/local/path/goes/here
che.conf.storage=/local/path/goes here

This way you will store workspaces and configuration outside Tomcat.

**Comment by TylerJewell** [comment]
You have another option - workspace snapshots.  Your workspace is both the projects (source code) and the runtimes (docker image).  The project state survives between runs of Che.  But the runtime state is reset each run of the server.  If you do a mvn install inside of your project, and that command downloads libraries into the maven repository, then that repository state will be lost on another run.

A workspace snapshot will save the image state into a docker registry and then when you restart the workspace, it picks up that last state.  It's a bit slow to save initially but very fast to re-start if you have recycled the server.

You need to launch a registry when you start the server, and you can use the --registry option to have us launch one for you in your docker container.

**Comment by mleader1** [comment]
Had a quick test based on the config documentation @eivantsov provided, it works exactly as I wanted, thanks!

But I think workspace snapshots might be the perfect solution I was expecting. I had a look into Codenvy's On Premise solution which seems the way to go instead of configuring whole lot on our own servers, but I couldn't find out where to download it's Team free version (might because I'm on mobile at the moment? ...) Will try again to find out the download section on the website.

Cheers.
