### ISSUE TITLE
How integrate eclipse Che with AD and LDAP

### ISSUE THREAD

**Issue by rajasekaran07** [eclipse-che/che#2302]
[Short description of problem here]
Hi Team,

I am looking for some KB article to integrate AD and LDAP with Eclipse Che. Can someone please help me on this.

**Reproduction Steps:**
1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Che version:**    [Enter Che version here]  

WARNING: No swap limit support
DEBUG: ---------------------------------------
DEBUG: ---------  CHE CLI DEBUG INFO  --------
DEBUG: ---------------------------------------
DEBUG:
DEBUG: ---------  PLATFORM INFO  -------------
DEBUG: DOCKER_INSTALL_TYPE       = native
DEBUG: DOCKER_HOST_IP            = 172.17.0.1
DEBUG: IS_DOCKER_FOR_WINDOWS     = NO
DEBUG: IS_DOCKER_FOR_MAC         = NO
DEBUG: IS_BOOT2DOCKER            = NO
DEBUG: IS_NATIVE                 = YES
DEBUG: HAS_DOCKER_FOR_WINDOWS_IP = NO
DEBUG: IS_MOBY_VM                = NO
DEBUG:
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
INFO:
INFO: ECLIPSE CHE: FOUND IMAGE codenvy/che-launcher:latest
INFO: ECLIPSE CHE: LAUNCHING LAUNCHER
/usr/bin/docker: Error response from daemon: Conflict. The name "/che-launcher" is already in use by container d96af31532887d0f5519b8c1c2ee73667de56c8aa0c493760a91515e214a6a6d. You have to remove (or rename) that container to be able to reuse that name..

**OS and version:** [Enter OS name and version here]   

root@ipaclient:~# uname -a
Linux ipaclient.openshift.loc 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Docker version:** [Enter your Docker version here `docker version` on CLI]   

root@ipaclient:~# docker version
Client:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:18:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:18:04 2016
 OS/Arch:      linux/amd64

**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

Docker

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by TylerJewell** [comment]
Eclipse Che is a single identity product without authentication or a user database.  Please consider talking to Codenvy.  They have a version of Che that supports authentication, multiple identities and LDAP integration.
