### ISSUE TITLE
Git history window is too small

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2308]
When using the Git History in the UI the actual history window at the bottom is much too small, it makes it hard to use.
1. Open a project with a long git history
2. Select a step in the history
3. Try to read the git history in a very small window :(

**Expected behavior:**
It would be nice to be able to resize the git history viewing window so that on a large screen I can see much more of the history.

**Che version:**    4.7
**OS and version:**  Mac OSX 10.11.6 and beta.codenvy.com 4.7
**Docker version:** 1.12.1
**Che install:**    Docker container

**Comment by RomanNikitenko** [comment]
The history window with default size looks like:
![default_size](https://cloud.githubusercontent.com/assets/5676062/19598744/1dc7b5cc-97a5-11e6-9569-d3443465c638.png)
We can resize this one like this, for example:
![resize](https://cloud.githubusercontent.com/assets/5676062/19598751/2f69df1c-97a5-11e6-90a0-4b152300e07a.png)
@bmicklea 
Could you clarify what new behavior do you prefer?
Do we need change default size or we need find a more appropriate place for this window?

**Comment by bmicklea** [comment]
Yes, please make the default size 3x wider.

**Comment by bmicklea** [comment]
@RomanNikitenko is this still in code review?  If so can we get a review and merge please?

**Comment by bmicklea** [comment]
@vparfonov this is part of 5.0.0 isn't it?

**Comment by RomanNikitenko** [comment]
We have some merged changes related to setting size of part stacks. So I need to check and update my pull request.

**Comment by RomanNikitenko** [comment]
AFAIK we have the new visual Git history window, so the issue can be closed as fixed by https://github.com/eclipse/che/pull/3799
@bmicklea WDYT?

**Comment by bmicklea** [comment]
Fixed by #3799
