### ISSUE TITLE
How to config mirror for maven? cant run vi in che container

### ISSUE THREAD

**Issue by chendongping** [eclipse-che/che#2309]
My che enviroment cant connect to Internet directly, Maven need to download sth from Internet, so I think I need to config a mirror for maven. I have the mirror address,but how to config in a docker container?

first step, I run command " docker run -t -i  codenvy/ubuntu_jdk8 /bin/bash" to get into container.
secondly, I find the maven install position and the config file-"settings.xml"
thirdly, I run command "sudo vi setting.xml" ,but the answer is "vi command not found"
I can't edit the config file, how can I config mirror for che container and image?vi

**Comment by ghost** [comment]
@chendongping you need to override the default settings.xml with yours. There are several ways to achieve that.
1. Mount your settings.xml into /home/user/.m2

There is che property for that in /conf/che.properties

machine.server.extra.volume=/path/to/your/settings/xml:/home/user/.m2/settings.xml
1. Build a custom image with your settings.xml, upload it to DockerHub and inherit from this image:

https://eclipse-che.readme.io/docs/recipes#section-custom-recipe

**Comment by chendongping** [comment]
@eivantsov  there are still some problems for me.
1、I guess you mean use mount to transfer a file to container than to edit the file. 
It's a good idea,but I failed to mount. I run this command in container:
user@71b124a73cd8:/$ sudo mount -o username=xxx,password=xxxxxx //10.57.49.235/share3 /mnt/share
mount: //10.57.49.235/share3 is write-protected, mounting read-only  
mount: cannot mount //10.57.49.235/share3 read-only  

but I can run same command success in host ubuntu ,then I try to input a errer password in container, the response is same--share3 read-only
1. why put  settings.xml into /home/user/.m2, I think I should override /home/user/apache-maven-3.3.9/conf/settings.xml

**Comment by JamesDrummond** [comment]
@chendongping Try the following if **/mnt/share/settings.xml** is where the file will be mounted on the host. https://eclipse-che.readme.io/docs/che-getting-started

```
export \
CHE_PROPERTY_machine_server_extra_volume=/mnt/share/settings.xml:/home/user/.m2/settings.xml 
che start
```

The use of `docker run -t -i codenvy/ubuntu_jdk8 /bin/bash` is not a standard way to interact with che containers as there are other arguments that are passed to ws from the che-server container. You can ssh into a running ws container or use the built in terminal to interact with ws container. See https://eclipse-che.readme.io/docs/desktop-ide-mounting#configure for ssh information.

**Comment by ghost** [comment]
@chendongping maven'ts settings.xml can be in ~/.m2 as well.

Follow instructions from @JamesDrummond. You need to pass this additional property to Che. Once it's there, all workspaces will mount your local settings.xml into a a workspace location specified in property's mount binding.
