### ISSUE TITLE
Che won't start on Windows7

### ISSUE THREAD

**Issue by snorthov** [eclipse-che/che#231]
I had a previous boot2docker installed.  Not sure this matters.

Here are the steps:

1) Use the single file Windows install that (does everything for you)
2) cd C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin
3) che run
4) BUG: Che does not start.  Here is the output:

C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>che run
###### 

On Windows, Che projects can only reside in %userprofile% due
to limitations of Docker. On this computer, %userprofile% is
C:\Users\snorthov
###### 

Docker machine named default already exists...
Setting environment variables for machine default...
Docker is configured to use vbox docker-machine named default with IP 192.168.99
.100...
###### ######## HOW TO CONNECT YOUR CHE CLIENT

After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
###### 

Could not find Che's application server.

Looks like something went wrong. Possible issues:
1. (Win | Mac) VirtualBox not installed ==> Rerun Docker Toolbox inst
allation
2. (Win | Mac) Docker Machine not installed ==> Rerun Docker Toolbox inst
allation
3. (Win | Mac) Docker is not reachable ==> Docker VM failed to start
1. (Win | Mac) Docker ok, but docker ps fails ==> Docker environment variab
   les not set properly
2. (Linux) Docker is not reachable ==> Install: wget -qO- https:
   //get.docker.com/ | sh
3. (Linux) Permissions not properly set ==> Che must run as UID 1000
   with user in docker group
4. Could not find the Che app server ==> Did /tomcat get moved awa
   y from CHE_HOME?
5. Wrong version of Java found ==> Che requires Java 1.8
6. Did you use the right parameter syntax? ==> See usage

We have seen issues with VirtualBox on Windows where your VM gets corrupted when
your computer is
suspended while the VM is still running. This will appear as SSH or ethernet con
nection issues. This is
rare, but if encountered, current known solution is to uninstall VirtualBox and
Docker Toolbox, and then
reinstall.

Che Environment Variables:
(REQUIRED) JAVA_HOME ==> Location of Java runtime
(REQUIRED: WIN|MAC) DOCKER_TOOLBOX_INSTALL_PATH ==> Location of Docker Toolbo
x
(REQUIRED: WIN|MAC) VBOX_MSI_INSTALL_PATH ==> Location of VirtualBox
(OPTIONAL) CHE_HOME ==> Directory where Che is in
stalled
(OPTIONAL) CHE_LOCAL_CONF_DIR ==> Directory with custom Che
.properties files
(OPTIONAL) CHE_LOGS_DIR ==> Directory for Che output
logs
(OPTIONAL) CHE_DOCKER_MACHINE_NAME ==> (Win | Mac) Name of VM cr
eated by docker-machine
(OPTIONAL) DOCKER_MACHINE_HOST ==> (Linux) Docker host IP -
set if browser clients remote

Usage:
che [OPTIONS] [run | start | stop]
-i, --image Launches Che within a Docker container using late
st image
-i:tag, --image:tag Launches Che within a Docker container using spec
ific image tag
-p:port, --port:port Port that Che server will use for HTTP requests;
default=8080
-r:ip, --remote:ip If Che clients are not localhost, set to IP addre
ss of Che server
-g, --registry Launch Docker registry as a container (used for w
s snapshots)
-m:vm, --machine:vm For Win & Mac, sets the docker-machine VM name to
vm; default=default
-s:client, --skip:client Do not print browser client connection informatio
n
-s:uid, --skip:uid Do not enforce UID=1000 for Docker
-h, --help Show this help
-d, --debug Use debug mode (prints command line options + app
server debug)
run Starts Che application server in current console
start Starts Che application server in new console
stop Stops Che application server

The -r flag sets the DOCKER_MACHINE_HOST system environment variable. Set this t
o the IP address of the node
that is running your Docker daemon. Only necessary to set this if on Linux and y
our browser clients are not
localhost, ie they are remote. This property automatically set for Che on Window
s and Mac.

C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>

**Comment by TylerJewell** [comment]
This is the second report of nearly an identical nature of the same error today.  We will diagnose in the next 24 hours.

**Comment by ghost** [comment]
Can you help us debug it please? When in /bin directory, where the startup script is, can you run `dirname "$(cd $(dirname ${0}) && pwd -P)")`

Odds are that this check does not work with a particular bash version on Windows 7.

**Comment by snorthov** [comment]
Sorry for not getting back to you right away.  Here it is:

C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>dirname "$(cd $(dirname ${0}) && pwd -P)")
.

**Comment by adnedelcu** [comment]
I managed to get past that error by running the command
`C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>che -i -r:192.168.99.100 start`
and the machine started correctly with the che container, but I am unable to connect to the http://192.168.99.100:8080. The Chrome gives error ERR_CONNECTION_REFUSED.

The output of the command is as follows:
C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>che -i -d -r:192.168.99.100 start
USE_DOCKER: true
CHE_DOCKER_TAG: latest
CHE_PORT: 8080
CHE_IP: "192.168.99.100"
CHE_DOCKER_MACHINE: default
LAUNCH_REGISTRY: false
PRINT_CLIENT_CONNECT: true
CHECK_DOCKER_UID: true
USE_HELP: false
CHE_SERVER_ACTION: start
USE_DEBUG: true

#############################################################
On Windows, Che projects can only reside in %userprofile% due
to limitations of Docker. On this computer, %userprofile% is
C:\Users\dev24
#############################################################

Could not find an existing docker machine.
Creating docker machine named default... Please be patient, this takes a couple minutes the first time.
Successfully started docker machine named default...
Setting environment variables for machine default...
Docker is configured to use vbox docker-machine named default with IP 192.168.99.100...

############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://192.168.99.100:8080, or:
2. Open native chromium app.
#############################################################

Starting Che server in docker container named che.
A Docker container for che does not exist or duplicate conflict was discovered.
Launching a new Docker container named che from image codenvy/che:latest with Docker command:
- 'C:\Program Files\Docker Toolbox\docker.exe' run --privileged -e '"DOCKER_MACHINE_HOST=192.168.99.100"' --name che -d -p 8080:8080 -p 32768-32788:32768-32788 codenvy/che:latest bash -c 'true && sudo chown -R user:user /home/user/che && sudo service docker start && tail -f /dev/null'
  Unable to find image 'codenvy/che:latest' locally
  latest: Pulling from codenvy/che

fcee8bcfe180: Pull complete
4cdc0cbc1936: Pull complete
d9e545b90db8: Pull complete
c4bea91afef3: Pull complete
f332d67eaa06: Pull complete
1d551183d586: Pull complete
47923467af26: Pull complete
5365e4732309: Pull complete
b855879bf0d2: Pull complete
3b28039ec239: Pull complete
decb7aaca048: Pull complete
3e33dd344ffb: Pull complete
3a0fb3cc6377: Pull complete
Digest: sha256:f47238795e58e8cd53985e22d0fefe6089202fa87d03fdcc6f6180be12da2f2b
Status: Downloaded newer image for codenvy/che:latest
55d7e7a48e6e72159b3a99e79e78b26f2649eb9db77d4e0d685d09f809919418
- set +x
  Docker container named che successfully started.
  Launching Che app server inside the container named che.
  Docker is natively installed and reachable...

**Comment by snorthov** [comment]
I believe the answer came back "." for me for the dirname thing.  What else can I try?  Should I fool around with the -r thing?

**Comment by adnedelcu** [comment]
For me, the command it didn't work. I have Windows 10 and apparently there is no dirname command in Windows 10.

**Comment by ghost** [comment]
Do you have the same problem on Windows 10? che.bat run ends in nothing? Can you provide logs?

**Comment by snorthov** [comment]
Installed the latest VirutalBox (I was prompted when I started it).  Still failing (I wonder, could it be firewall/security crap?):

C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>che run

#############################################################
On Windows, Che projects can only reside in %userprofile% due
to limitations of Docker. On this computer, %userprofile% is
C:\Users\snorthov
#############################################################

Docker machine named default already exists...
Docker machine named default is not running.
Starting docker machine named default...
Starting "default"...
(default) Waiting for an IP...
Machine "default" was started.
Started machines may have new IP addresses. You may need to re-run the `docker-m
achine env` command.
Setting environment variables for machine default...
Docker is configured to use vbox docker-machine named default with IP 192.168.99
.100...

############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
#############################################################

Could not find Che's application server.

Looks like something went wrong. Possible issues:
1. (Win | Mac) VirtualBox not installed          ==> Rerun Docker Toolbox inst
   allation
2. (Win | Mac) Docker Machine not installed      ==> Rerun Docker Toolbox inst
   allation
3. (Win | Mac) Docker is not reachable           ==> Docker VM failed to start
4. (Win | Mac) Docker ok, but docker ps fails    ==> Docker environment variab
   les not set properly
5. (Linux) Docker is not reachable               ==> Install: wget -qO- https:
   //get.docker.com/ | sh
6. (Linux) Permissions not properly set          ==> Che must run as UID 1000
   with user in docker group
7. Could not find the Che app server             ==> Did /tomcat get moved awa
   y from CHE_HOME?
8. Wrong version of Java found                   ==> Che requires Java 1.8
9. Did you use the right parameter syntax?       ==> See usage

We have seen issues with VirtualBox on Windows where your VM gets corrupted when
 your computer is
suspended while the VM is still running. This will appear as SSH or ethernet con
nection issues. This is
rare, but if encountered, current known solution is to uninstall VirtualBox and
Docker Toolbox, and then
reinstall.

Che Environment Variables:
  (REQUIRED) JAVA_HOME                             ==> Location of Java runtime
  (REQUIRED: WIN|MAC) DOCKER_TOOLBOX_INSTALL_PATH  ==> Location of Docker Toolbo
x
  (REQUIRED: WIN|MAC) VBOX_MSI_INSTALL_PATH        ==> Location of VirtualBox
  (OPTIONAL) CHE_HOME                              ==> Directory where Che is in
stalled
  (OPTIONAL) CHE_LOCAL_CONF_DIR                    ==> Directory with custom Che
 .properties files
  (OPTIONAL) CHE_LOGS_DIR                          ==> Directory for Che output
logs
  (OPTIONAL) CHE_DOCKER_MACHINE_NAME               ==> (Win | Mac) Name of VM cr
eated by docker-machine
  (OPTIONAL) DOCKER_MACHINE_HOST                   ==> (Linux) Docker host IP -
set if browser clients remote

Usage:
  che [OPTIONS] [run | start | stop]
     -i,        --image        Launches Che within a Docker container using late
st image
     -i:tag,    --image:tag    Launches Che within a Docker container using spec
ific image tag
     -p:port,   --port:port    Port that Che server will use for HTTP requests;
default=8080
     -r:ip,     --remote:ip    If Che clients are not localhost, set to IP addre
ss of Che server
     -g,        --registry     Launch Docker registry as a container (used for w
s snapshots)
     -m:vm,     --machine:vm   For Win & Mac, sets the docker-machine VM name to
 vm; default=default
     -s:client, --skip:client  Do not print browser client connection informatio
n
     -s:uid,    --skip:uid     Do not enforce UID=1000 for Docker
     -h,        --help         Show this help
     -d,        --debug        Use debug mode (prints command line options + app
 server debug)
     run                     Starts Che application server in current console
     start                   Starts Che application server in new console
     stop                    Stops Che application server

The -r flag sets the DOCKER_MACHINE_HOST system environment variable. Set this t
o the IP address of the node
that is running your Docker daemon. Only necessary to set this if on Linux and y
our browser clients are not
localhost, ie they are remote. This property automatically set for Che on Window
s and Mac.

C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>

**Comment by adnedelcu** [comment]
This is the output:
C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\bin>che.bat run

#############################################################
On Windows, Che projects can only reside in %userprofile% due
to limitations of Docker. On this computer, %userprofile% is
C:\Users\dev24
#############################################################

Docker machine named default already exists...
Setting environment variables for machine default...
Docker is configured to use vbox docker-machine named default with IP 192.168.99.100...

############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
#############################################################

Could not find Che's application server.

Looks like something went wrong. Possible issues:
1. (Win | Mac) VirtualBox not installed          ==> Rerun Docker Toolbox installation
2. (Win | Mac) Docker Machine not installed      ==> Rerun Docker Toolbox installation
3. (Win | Mac) Docker is not reachable           ==> Docker VM failed to start
4. (Win | Mac) Docker ok, but docker ps fails    ==> Docker environment variables not set properly
5. (Linux) Docker is not reachable               ==> Install: wget -qO- https://get.docker.com/ | sh
6. (Linux) Permissions not properly set          ==> Che must run as UID 1000 with user in docker group
7. Could not find the Che app server             ==> Did /tomcat get moved away from CHE_HOME?
8. Wrong version of Java found                   ==> Che requires Java 1.8
9. Did you use the right parameter syntax?       ==> See usage

We have seen issues with VirtualBox on Windows where your VM gets corrupted when your computer is
suspended while the VM is still running. This will appear as SSH or ethernet connection issues. This is
rare, but if encountered, current known solution is to uninstall VirtualBox and Docker Toolbox, and then
reinstall.

Che Environment Variables:
  (REQUIRED) JAVA_HOME                             ==> Location of Java runtime
  (REQUIRED: WIN|MAC) DOCKER_TOOLBOX_INSTALL_PATH  ==> Location of Docker Toolbox
  (REQUIRED: WIN|MAC) VBOX_MSI_INSTALL_PATH        ==> Location of VirtualBox
  (OPTIONAL) CHE_HOME                              ==> Directory where Che is installed
  (OPTIONAL) CHE_LOCAL_CONF_DIR                    ==> Directory with custom Che .properties files
  (OPTIONAL) CHE_LOGS_DIR                          ==> Directory for Che output logs
  (OPTIONAL) CHE_DOCKER_MACHINE_NAME               ==> (Win | Mac) Name of VM created by docker-machine
  (OPTIONAL) DOCKER_MACHINE_HOST                   ==> (Linux) Docker host IP - set if browser clients remote

Usage:
  che [OPTIONS] [run | start | stop]
     -i,        --image        Launches Che within a Docker container using latest image
     -i:tag,    --image:tag    Launches Che within a Docker container using specific image tag
     -p:port,   --port:port    Port that Che server will use for HTTP requests; default=8080
     -r:ip,     --remote:ip    If Che clients are not localhost, set to IP address of Che server
     -g,        --registry     Launch Docker registry as a container (used for ws snapshots)
     -m:vm,     --machine:vm   For Win & Mac, sets the docker-machine VM name to vm; default=default
     -s:client, --skip:client  Do not print browser client connection information
     -s:uid,    --skip:uid     Do not enforce UID=1000 for Docker
     -h,        --help         Show this help
     -d,        --debug        Use debug mode (prints command line options + app server debug)
     run                     Starts Che application server in current console
     start                   Starts Che application server in new console
     stop                    Stops Che application server

The -r flag sets the DOCKER_MACHINE_HOST system environment variable. Set this to the IP address of the node
that is running your Docker daemon. Only necessary to set this if on Linux and your browser clients are not
localhost, ie they are remote. This property automatically set for Che on Windows and Mac.

**Comment by ghost** [comment]
Can you pease add echo $CHE_HOME after
https://github.com/codenvy/che/blob/master/assembly-main/src/assembly/bin/che.sh#L220

**Comment by adnedelcu** [comment]
CHE_HOME is /

**Comment by adnedelcu** [comment]
I think the problem is that it tries the local docker instead of the boot2docker version. I think that's why it shows the localhost in the `HOW TO CONNECT YOUR CHE CLIENT` section

**Comment by ghost** [comment]
The problem is with detection of Che tomcat directory - CHE_HOME. It works on Win 8 though.

**Comment by adnedelcu** [comment]
What directory should it be?

**Comment by ghost** [comment]
../tomcat/bin is ASSEMBLY_BIN_DIR

This is where the script fails https://github.com/codenvy/che/blob/master/assembly-main/src/assembly/bin/che.sh#L443

**Comment by adnedelcu** [comment]
I added the following commands after line 220 in che.sh:
`echo $(dirname ${0})`
`echo $(pwd -P)`
`echo $(cd $(dirname ${0}) && pwd -P)`
`echo $CHE_HOME`
and this was the output:
`C: Files Che\eclipse-che-4.0.0-beta-13\bin`
`/c/Program Files/Eclipse Che/eclipse-che-4.0.0-beta-13/bin`
`/c`
`/`

I don't think this was the expected behaviour.

**Comment by ghost** [comment]
Yes, definitely. I have just done it on Win 8 and got accurate paths. We'll need to test it on Win 7 and Win 10

**Comment by adnedelcu** [comment]
Just out of curiosity, what bash version do you have?

**Comment by ghost** [comment]
4.3.42(2)

**Comment by adnedelcu** [comment]
I have 4.3.42(5)... maybe that's the reason :D

**Comment by adnedelcu** [comment]
Managed to get a better output of those commands by changing the install directory.
If you install in a directory that has no spaces in its path you get to the eclipse che folder as CHE_HOME.
`C:\personal\eclipse-che-4.0.0-beta-13\bin`
`/c/personal/eclipse-che-4.0.0-beta-13/bin`
`/c/personal/eclipse-che-4.0.0-beta-13/bin`
`/c/personal/eclipse-che-4.0.0-beta-13`

**Comment by adnedelcu** [comment]
Now it fails when it's trying to check for the Java version, because, for some reason, the JRE_HOME is still in the previous path (C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\tools\jre).

**Comment by adnedelcu** [comment]
Yeeeey... It works. With some changes to the catalina.sh file, but it works.

The problem si that there is no logs folder in the $CATALINA_BASE folder and the script dies when it tries to do touch on $CATALINA_OUT which by default is $CATALINA_BASE/logs/catalina.out.

To fix that, you add the following line of code at 199 so that it looks like this:
`if [ -z "$CATALINA_OUT" ] ; then`
`mkdir -p $CATALINA_BASE/logs`
`CATALINA_OUT="$CATALINA_BASE"/logs/catalina.out`
`fi`

**Comment by ghost** [comment]
Yes, spaces in the path cause the problem. We'll fix that.

As to logs issue, never encountered it before. Will test more.

**Comment by snorthov** [comment]
I uninstalled Docker and reinstalled che in c:\users\snorthov  (ie. no spaces)

Now it just comes back and doesn't run the server at all (it seems):

C:\Users\snorthov\eclipse-che-4.0.0-beta-13\bin>che run

#############################################################
On Windows, Che projects can only reside in %userprofile% due
to limitations of Docker. On this computer, %userprofile% is
C:\Users\snorthov
#############################################################

Docker machine named default already exists...
Setting environment variables for machine default...
Docker is configured to use vbox docker-machine named default with IP 192.168.99
.100...

############## HOW TO CONNECT YOUR CHE CLIENT ###############
After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
#############################################################

C:\Users\snorthov\eclipse-che-4.0.0-beta-13\bin>

**Comment by adnedelcu** [comment]
@snorthov it is because of the java path. Go throug your environment variables and modify the path from the old path to the new one.

**Comment by TylerJewell** [comment]
For everyone.  There were two particular issues:
First, the space in the Program Files directory on Windows 7 is causing problems when we are attempting to set CHE_HOME automatically. Either the version of bash is causing that issue, or it's special formatting on that version of Windows.  We are investigating.

Second, there was an unnecessary "eval" command when evaluating the Java version.  This has already been resolved in the master branch and is in the nightly build.

**Comment by snorthov** [comment]
The eval command was the thing that stopping me from working after I moved to a directory with no spaces.  I'm going to close this because "Che won't start on Windows7" is no longer true for me.  If the spaces thing is not being tracked elsewhere, feel free to reopen and change the title to reflect the problem.  Thanks!

**Comment by TylerJewell** [comment]
@snorthov The issue has to do with tomcat on windows 7 not liking spaces in the folder names.  And as a result, the JRE is unable to load the right files.  FWIW, if you change the CHE_HOME path to include a directory with the shortened windows name like PROGRA~1, then the classloading issue will not appear.

**Comment by TylerJewell** [comment]
@snorthov There is a pull request which fixes the windows directory issue.  The issue is Tomcat, and we came up with a workaround.
https://github.com/codenvy/che/pull/241
