### ISSUE TITLE
Running che as a server on Mac with odd behavior

### ISSUE THREAD

**Issue by vazexqi** [eclipse-che/che#2313]
I've tried to follow the instructions from https://eclipse-che.readme.io/docs/usage-docker-server-for-mac#running-che-as-a-server (which was based on #1482) but when I open the browser, it renders weirdly. And when I create a workspace, I see that it's not able to connect:

```
2016-09-02 03:17:13,954[kspaceManager-0]  [ERROR] [.c.a.a.s.w.WsAgentLauncherImpl 112]  - Fail pinging ws agent. Workspace ID:workspace67i68lrgwcg4on2z. Url:http://localhost:32913/wsagent/ext/. Timestamp:{}
2016-09-02 03:17:15,705[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 666]    - Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:261) ~[che-core-api-workspace-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:650) ~[che-core-api-workspace-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.8.0-SNAPSHOT.jar:4.8.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
```

**Reproduction Steps:**
1. Clone the che repo (so it's on master but I've also reproduce this on the language-server branch)
2. mvn clean package.
3. cd into the assembly-main/target/eclipse-che-_/eclipse-che-_
4. Run bin/che.she run

**Expected behavior:**

It should render properly and be able to connect to the workspace.

**Observed behavior:**

![screen shot 2016-09-02 at 3 17 20 am](https://cloud.githubusercontent.com/assets/54414/18200883/f09bcc42-70bb-11e6-9193-5a20584e290d.png)

**Che version:**    build from source (master)
**OS and version:** OS X 10.11.6
**Docker version:**  
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
**Che install:**    local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Not sure. Started working on this today.
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Workaround**

I've been able to tweak the instructions at https://github.com/eclipse/che/wiki/Development-Workflow#build-and-run---docker to get myself running. So basically

```
# Build the Che server Docker image from the root of our source:
docker build -t codenvy/che-server:nightly  .

# Run using the che-launcher:nightly from https://hub.docker.com/r/codenvy/che-launcher/
# Didn't seem to need to build from https://github.com/eclipse/che-dockerfiles
docker run --rm -t \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e CHE_DATA_FOLDER=/Users/nchen/che \
    -e CHE_HOST_IP=10.10.42.22 \
    -e CHE_LOCAL_BINARY=/Users/nchen/Development/my-eclipse-che-developer/che/assembly/assembly-main/target/eclipse-che-4.8.0-SNAPSHOT/eclipse-che-4.8.0-SNAPSHOT \
    codenvy/che-launcher:nightly start

```

**Comment by TylerJewell** [comment]
@vazexqi - can you help me understand the use case you are trying to achieve? Are you looking to:
1: Run che as a server outside of its container, as in the link you provided
2: Compile che and run it on your own
3: Just run Che on docker for mac

I am going to run some tests around running Che natively as a server on Docker for Mac - but the easier approach is to use the Che launcher container, and then set CHE_LOCAL_BINARY environment variable to use your locally compiled binary.  In other words, you are currently choosing the path of most complexity :)

**Comment by vazexqi** [comment]
@TylerJewell I'm prototyping a language server and want to see how to integrate it with Che (#1287). Hit some [issues](https://github.com/eclipse/che/issues/1287#issuecomment-244349158) trying to get the language server to activate so this question is to check if I am doing something wrong.

I am using the CHE_LOCAL_BINARY approach (I updated my opening post to reflect that more clearly). Is that the easiest approach on Macs rather than trying to compile and launch using `bin/che.sh run`?

I was just worried that because I am working on the _language-server_ branch, that the Che launcher codenvy/che-launcher:nightly might not be compatible with it. Especially since it's been moved to a separate repo at https://github.com/eclipse/che-dockerfiles/ so I don't know how they are kept in sync.

**Comment by TylerJewell** [comment]
It would be preferred to use the `CHE_LOCAL_BINARY`. This makes it easier for us to help you diagnose any problems.  When you run the Che server natively on your computer, then we have to make sure that Java, maven, Docker and a bunch of other parameters are configured just right, and these parameters vary for each operating system.  So that poses challenges.

When you set `CHE_LOCAL_BINARY` and use our CLI or the Che launcher docker image, what happens is that we launch a Docker container that has the exact configuration needed to start / stop Che on any operating system.  We make sure all of the right flags are passed for the various situations.  When you set the path to CHE_LOCAL_BINARY, the Che launcher container then calls the Che server container, but instead of using the embedded binary that ships in the Che server container, it will instead mount the host folder where your binary is compiled and use that instead.  

So you can get local compilation of any branch and any binary, and then reuse our utilities for launching the server.

**Comment by TylerJewell** [comment]
@vazexqi - I am going to close this issue for now, as I think we have given you a good path forward.  If you have some more specifics, feel free to reopen it.
