### ISSUE TITLE
Unable to select text on terminal window

### ISSUE THREAD

**Issue by alex-marinov** [eclipse-che/che#2320]
Unable to select text on terminal window.

**Reproduction Steps:**
1. Open terminal window
2. ie. google app engine deploy command which generates web link to auth offline access
3. Unable to select the text to be able to copy.

**Expected behavior:**

Select text to be able to copy and paste somewhere else.

**Observed behavior:**

Unable to select text

**Che version:**    4.7.0
**OS and version:** Windows 10 64-bit
**Docker version:** 
**Che install:**    Codenvy (Version :4.7.0Revision :dcd260e409862185Build Time :2016-08-29 20:15:54)

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No] Yes
  I was able to select text on previous versions (I don't know which version exactly)
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
  I've tried on my Mac book pro (with Chrome and Opera), and Windows 10 with Chrome, Opera, Firefox and still can't select text on terminal window.

**Comment by JamesDrummond** [comment]
Confirmed using 4.7.0 windows 10 chrome.

![issue](https://cloud.githubusercontent.com/assets/20580888/18285816/a4b9af6a-7435-11e6-9cae-76fb49892158.gif)

**Comment by ghost** [comment]
@alex-marinov @JamesDrummond this should be fixed in current master.

**Comment by alex-marinov** [comment]
I've noticed if I switch to "Operations Perspective", I can select the text on terminal window.

![codenvy_text_select](https://cloud.githubusercontent.com/assets/490052/18523006/3bdcf2a6-7aaa-11e6-8644-26369dcc7db9.gif)

![capture](https://cloud.githubusercontent.com/assets/490052/18523020/4e282a0c-7aaa-11e6-9449-e3f467f3569f.JPG)

**Comment by ghost** [comment]
@alex-marinov this is fixed in master.
