### ISSUE TITLE
"cannot enable tty mode on non tty input" on Eclipse Che version 4.7.0

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#2321]
OS : windows 10 build 10240
Docker : boot2docker v1.11.2
Che version :  4.7.0

Cant even start Eclipse Che 4.7.0

![ss1](https://cloud.githubusercontent.com/assets/1939446/18216405/115c5834-7189-11e6-9a91-716deab333c3.JPG)

**Comment by TylerJewell** [comment]
set IS_INTERACTIVE=false or IS_TTY=false.  See: https://eclipse-che.readme.io/docs/configuration#section-environment-variables

**Comment by thyeun** [comment]
@TylerJewell after the **set** result as below

![ss2](https://cloud.githubusercontent.com/assets/1939446/18222954/bc033cf8-71d9-11e6-99cd-91ba9a61bf1c.JPG)

**Comment by thyeun** [comment]
@TylerJewell inside the che.sh file (newer version), i have to change the **line 165** -t to -i, to make it work

docker_run_with_pseudo_tty() {
  if has_pseudo_tty; then
    docker_run_with_env_file -t "$@"
  else
    docker_run_with_env_file "$@"
  fi
}

**Comment by thyeun** [comment]
@TylerJewell after go into IDE, i'm getting another error, as below picture.

![ss3](https://cloud.githubusercontent.com/assets/1939446/18223471/baec501e-71ea-11e6-9107-956a7d3cc2a0.JPG)

**Comment by TylerJewell** [comment]
It doesn't look like you are getting a clean run of the cli.  There are errors appearing in the run.  Are you in a Windows shell - not a bash shell?

**Comment by thyeun** [comment]
@TylerJewell this is the result after with **Che start**

![ss4](https://cloud.githubusercontent.com/assets/1939446/18224323/f71eb496-7203-11e6-9e19-e15bf3b79a33.JPG)

![ss5](https://cloud.githubusercontent.com/assets/1939446/18224327/fdf5f84c-7203-11e6-82c3-509d84166f22.JPG)

but i still getting the same error from the IDE

**Comment by thyeun** [comment]
@TylerJewell more info regarding the fail start of workspaces (for current now)

It is only happen for **Java stack and blank stack**, (python stack are working fine, python stack will pull the latest file from docker)

**Comment by TylerJewell** [comment]
You are using boot2docker - is there any chance that the VM is out of disk space?  Can you SSH into the VM and then do a "df" command to take a look around?

**Comment by thyeun** [comment]
@TylerJewell result as below

![ss6](https://cloud.githubusercontent.com/assets/1939446/18228098/84b7f7f2-726f-11e6-80d2-b8b2a600cd36.JPG)

![ss7](https://cloud.githubusercontent.com/assets/1939446/18228108/42a818c8-7270-11e6-862f-411797b0949a.JPG)

which should delete?

**Comment by TylerJewell** [comment]
Something is maxing out your disk in that VM.  If you are using boot2docker and you have saved your stuff properly, have you thought about destroying the VM and starting again?  It would be something like docker-machine rm default, or something similar.

**Comment by thyeun** [comment]
@TylerJewell i understand now, after remove it, i have create again

**Comment by thyeun** [comment]
@TylerJewell can you educated me, why it will full? i'm really dont understand, i only use it for my VBox only use for Eclipse Che

**Comment by TylerJewell** [comment]
Virtualization is a very different sort of world.  There could be a lot of reasons that cause this, many of them beyond our understanding.  But all VMs are a fixed size - so maybe we hit some mythical limit with all of the docker images loaded into the system.

**Comment by thyeun** [comment]
@TylerJewell so educational for this, thanks a lot!
