### ISSUE TITLE
Machine tab does not have full output of the workspace boot

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2325]
With the new tabbed terminals, the machine console tab appears with limited information when it should have the complete output of the docker image download, container output, tomcat boot logs.

The output is currently:

```
2016-09-02 00:25:28,704[nio-4401-exec-2]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 51]   - Web socket session opened
2016-09-02 00:25:28,772[nio-4401-exec-2]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 52]   - Endpoint: 850535212
```

**Comment by tolusha** [comment]
It can't be blocker.

**Comment by vparfonov** [comment]
Looks like it's normal behavior. We get log message via WebSocket channel and those 2 lines new events we got then IDE refreshed and connect again to ws-agent

**Comment by TylerJewell** [comment]
Ok then we have serious problem.  It may be expected behavior from tech point of view but it is not expected behavior from user point of view.  We have created a no mans land situation by providing information that is unhelpful.  What is needed to change the normal behavior?
