### ISSUE TITLE
from 4.7.0 become 4.6.2 

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#2326]
OS : windows 10 build 10240
Docker : 1.12.1
Eclipse Che : 4.7.0

I dont know what happen, below are the picture of the result, dashboard still are 4.7.0 but the IDE editor are become 4.6.2

so, what really goes wrong?

![ss8](https://cloud.githubusercontent.com/assets/1939446/18228958/6ead7cee-7296-11e6-8f9e-de6c3b945cf0.JPG)

![ss9](https://cloud.githubusercontent.com/assets/1939446/18228960/7786507a-7296-11e6-9899-2e03a870a3ea.JPG)

**Comment by thyeun** [comment]
Below are the result of **Che info**

![ss10](https://cloud.githubusercontent.com/assets/1939446/18228968/177d1668-7297-11e6-9860-3062f1bca6e7.JPG)

**Comment by TylerJewell** [comment]
That is crazy odd - cannot think of anything that would cause that to happen.  Is there any way that you need to do a browser hard refresh?  It would be a right-click on this.  Another thing - perhaps the ":latest" tag is causing confusion, so maybe explicit with the version you want of ":4.7.0".

**Comment by thyeun** [comment]
@TylerJewell, you are correct, not all browser affected, only chrome browser 64-bit latest version affected, but it will come back several times of open/close eclipse (with previous version, an example 4.6.2) than loading the newer version (4.7.0), than the same issue happen again.

i try it on firefox, it never having the issue, this might be the cache issue on chrome browser 64-bit.

**nothing related with "latest" or "4.7.0" on CHE_VERSION.**

**Comment by TylerJewell** [comment]
Open up chrome dev tools and then when you right click on refresh button you can get some hard cache refresh options.

**Comment by thyeun** [comment]
Happy with the below result after a day of trying here and there

![ss12](https://cloud.githubusercontent.com/assets/1939446/18232796/092373be-730a-11e6-8baa-16172f794a60.JPG)
