### ISSUE TITLE
Che server and workspace machines on separate nodes

### ISSUE THREAD

**Issue by lhwong** [eclipse-che/che#2327]
As per https://eclipse-che.readme.io/docs/scaling,

"(Coming Soon). Your workspace runtimes are Docker containers that do not have to reside on the same machine as the Che server, which is the workspace master. You can optionally deploy Docker onto a different physical node apart from the Che server. You can then size the Docker node based upon the number of concurrent workspaces that you want to have active and / or snapshot."

May I know in which release this feature is planned for?

**Comment by TylerJewell** [comment]
We have not published a milestone date yet.  We will discuss it more publicly soon.
