### ISSUE TITLE
Close editor when file is deleted

### ISSUE THREAD

**Issue by vlad-tury** [eclipse-che/che#2328]
I could not find a way to close the editor in which my file (of my defined type) is opened when the file is deleted from the workspace.

Basically I have defined a new file type that opens in an editor I have built.

I have to mention that this problem does not happen for other file types and editors: xml, md, etc.

Is there something I have to do more for my file type or my editor?

How can I subscribe to be notified when the file is deleted?

Thank you.

Please find the reproduction steps below.

**Reproduction Steps:**
1. Create a new file of the type MyType
2. The file open in my editor => OK
3. Right-click and Delete on the file.
4. Click OK in the confirmation dialog
5. The file is deleted =>OK

**Expected behavior:**
1. The editor tab in which the deleted file was opened is closed.

**Observed behavior:**
1. The editor tab in which the deleted file was opened is **NOT** closed. I can modify it in this unstable state

**Che version:**    4.6.2, but it happen on 4.5.1 as well
**OS and version:** Windows 7
**Docker version:** 1.10.3

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by JamesDrummond** [comment]
@vlad-tury I am not able to reproduce on 4.7.0. Let me know if my step reproduce yours.

![issue](https://cloud.githubusercontent.com/assets/20580888/18285057/3683acce-7432-11e6-9576-78ef9c0507ee.gif)

**Comment by vlad-tury** [comment]
@JamesDrummond : the problem reproduces if I open the file with my own built Editor.
In order to reproduce the problem you would have to build a small editor and associate it with the .MyType file type by means of:

fileTypeRegistry.registerFileType(myType);
editorRegistry.registerDefaultEditor(myType, myTypeProvider);

In your case the problem does not reproduce because the file is opened with the default text editor.
Thank you.

**Comment by TylerJewell** [comment]
This is expected behavior today, so not a bug.  

You are wanting and waiting for the new file system watcher capability which will allow outside editors modify the file system and then then browser is notified.  

See: https://github.com/eclipse/che/pull/2339

**Comment by vlad-tury** [comment]
@TylerJewell thank you for the feedback. 
The only particularity for my case is that I am not using an outside editor, but an editor create in Eclipse Che as a plugin.

Does this info change your answer? Or my scenario will also be covered by the implementation of #2339 ?

Thank you.

**Comment by TylerJewell** [comment]
I think there are a couple APIs that you will have to implement so that you can detect certain file system events.  @dkuleshov - is the author of the VFS capability and can give you some insights into what you may need to do in your extension.

**Comment by vlad-tury** [comment]
@TylerJewell Thanks for the info.
@dkuleshov : Can you please let me know how is the proper way to get notified when a file is delete from a project so I can close the extension editor as well.
Thank you.

**Comment by ghost** [comment]
@vlad-tury you may want to take a look at https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/part/widgets/editortab/EditorTabWidget.java#L329-329

**Comment by vlad-tury** [comment]
@eivantsov Thank you for the hint. I have managed to fix the problem.

Basically what I did is to make the presenter responsible for my editor to extend ResourceChangedHandler.

The implemented method of the interface looks like:
`@Override
    public void onResourceChanged(ResourceChangedEvent event) {
        final ResourceDelta delta = event.getDelta();
        if (delta.getKind() == ResourceDelta.REMOVED) {
            if (delta.getResource().isFile() && delta.getResource().getLocation().equals(input.getFile().getLocation())){
                workspaceAgent.removePart(this);
            }
        }   
    }`

@eivantsov , @TylerJewell - if it is ok with you I will close this issue
