### ISSUE TITLE
Cannot paste (Ctrl+V) into Text Area widget

### ISSUE THREAD

**Issue by vlad-tury** [eclipse-che/che#2329]
I have found this problem in Text Area's in my own developed editor, but I managed to reproduce it also in other cases as well (not related to my code).

See reproduction steps below.

I have tested this for the Git-> Commit text area, but I am rather sure it reproduces for all text areas
**Reproduction Steps:**
1. Create a project in the workspace
2. Select the project and from the menu: Git -> Initialize Repository
3. After the repository is initialized and the Commit menu item becomes available click on it
4. Copy some text from elsewhere
5. Paste the text (Ctrl+V) in the Git -> Commit message text area

**Expected behavior:**
6. The text gets pasted in the text area

**Observed behavior:**
6. The text is not pasted in the text area and the following error appears in the F12 console:

Sun Sep 04 14:03:25 GMT+300 2016 com.google.gwt.logging.client.LogConfiguration
SEVERE: Nothing to processjava.lang.IllegalStateException: Nothing to process
    at Unknown.ak(_app-0.js)
    at Unknown.dw(_app-0.js)
    at Unknown.gw(_app-0.js)
    at Unknown.Ft(_app-0.js)
    at Unknown.Rp(_app-0.js)
    at Unknown.vlc(_app-0.js)
    at Unknown.qo(_app-0.js)
    at Unknown.YI/b<(_app-0.js)
    at Unknown.Zu/<(_app-0.js)
    at Unknown.anonymous(Unknown)

The problem happens only for Text Area's as far as I have observed. Other widgets work ok from this point of view.
I have managed to reproduce this problem in both Chrome 52.0 (Incognito and normal mode) and Firefox 48.0.2.

**Che version:**    4.6.2
**OS and version:** Windows 7
**Docker version:** 1.10.3

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by JamesDrummond** [comment]
@vlad-tury Currently using 4.7.0 windows 10 chrome 52.0.2743.116 I am not able to reproduce. Can you upgrade your che version to 4.7.0 to see if you get the same problem? If upgrading is a problem for, let me know and I can try to use 4.6.2 to see if I get the same issue.

**Comment by vlad-tury** [comment]
@JamesDrummond: unfortunately I cannot upgrade to 4.7.0. It would be great if you could try to reproduce the problem on 4.6.2.
Thank you.

**Comment by JamesDrummond** [comment]
@vlad-tury Just tried using 4.6.2 and could not reproduce. Let me know how you are starting che. Follow [https://eclipse-che.readme.io/docs/che-getting-started](https://eclipse-che.readme.io/docs/che-getting-started) then do the following to see if anything changes. If you are using a custom che server binary then use the `CHE_LOCAL_BINARY` to set the folder .

Command prompt

> set CHE_DATA_FOLDER=\c\Users\%USERNAME%\
> set CHE_VERSION=4.6.2
> che start

**Comment by JamesDrummond** [comment]
@vlad-tury Have you had any progress with this issue?

**Comment by vlad-tury** [comment]
@JamesDrummond unfortunately I have been busy going from Che to Codenvy, but I will try this soon, maybe in Codenvy installation and come back to you.

**Comment by TylerJewell** [comment]
Going to close since it is >60 days.  We are going to deprecate 4.x line shortly as the 5.0 release is about to ship.  Ok to open a new issue if it's still recurring on the new version.
