### ISSUE TITLE
Cannot launch a workspace after creation

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2331]
**Reproduction Steps:**
1. Create  a workspace from the Dashboard and go to the workspace

**Expected behavior:**
The workspace should start without errors
**Observed behavior:** 
During creation the workspace we have error mesage like: 
`Could not start workspace rtetr. Reason: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.``

![selection_012](https://cloud.githubusercontent.com/assets/1640058/18240238/21ed4d2c-7353-11e6-9775-24a1b189f5dc.png)

**Che version:**    4.8.0
**OS and version:** Che nightly image with latest changes
**But  if we use Che without docker (as tomcat) workspaces are created correct**

**Comment by ghost** [comment]
The problem is caused by che-server container not being part of the network which is created when a workspace container starts. As a result, workspace container cannot reach Che server container.

**Comment by riuvshin** [comment]
Agree that it is a blocker because Che in docker is our primary way to launch it.

**Comment by pierryangelo** [comment]
After importing the virtual machine, when I try to access on a browser, it shows the default page, but it doesn't load the dashboard. 

Note: It shows the dashboard loading page forever.

**Comment by TylerJewell** [comment]
Hi @pierryangelo - if you are testing the latest nightly, there are some bugs that prevent you from creating workspaces and loading the dashboard.  Can you set CHE_VERSION=latest and try again?

**Comment by pierryangelo** [comment]
@TylerJewell, how do I do that? I just export an environment variable and refresh the page?

**Comment by TylerJewell** [comment]
Set an environment variable in your terminal, and then restart Che using the CLI.  `che stop; che start`.

**Comment by ghost** [comment]
@pierryangelo this is an unrelated problem. Can you open a new issue since this one is totally different. Thanks.

**Comment by pierryangelo** [comment]
Sorry. I'll do that.
