### ISSUE TITLE
The size of workspase is not correctly displayed on the dashboard.

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2333]
**Reproduction Steps:**
1. Create any workspace with  2 GB RAM
2. Click on 'Workspaces' item in the navbar

**Observed behavior:**
Information about size of the workspace is not displayed
![ram_ws](https://cloud.githubusercontent.com/assets/8051404/18241568/8d28ba16-735a-11e6-9b67-01f5644944da.png)

**Che version:**   Version :4.8.0-SNAPSHOT
**OS and version:**  Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**    local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ashumilova** [comment]
Resolved
