### ISSUE TITLE
Workspace - "Download as Zip..." action should download all projects in the workspace

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2336]
Workspace - "Download as Zip..." action should download all projects in the workspace.
(related to https://github.com/codenvy/artik-ide/issues/115)

**Reproduction Steps:**
1. Get a workspace with multiple projects
2. Hit action "Download as Zip..." from Workspace menu

**Expected behavior:**
It downloads all projects from the workspace

**Observed behavior:**
It downloads only the projects selected in the project explorer.

**Che version:**    4.7.0

**Comment by vparfonov** [comment]
fixed in https://github.com/eclipse/che/pull/2347

**Comment by vparfonov** [comment]
https://github.com/codenvy/artik-ide/issues/115
