### ISSUE TITLE
Import zip project from dropbox works wrong

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2349]
**Reproduction Steps:**
1. Workspase -> Import Project ->zip 
2. Paste the link for example: https://dl.dropboxusercontent.com/u/69709469/Spring1726.zip

**Expected behavior:**
The project should be imported as Spring maven project
**Observed behavior:**
The project lose some files and is not configured as maven

**Che version:**    4.8.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.12
**Che install:**    Codenvy

**Comment by svor** [comment]
Can't reproduce
