### ISSUE TITLE
Wrong behavior after run command 'Delete' in Subversion plugin

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2350]
**Reproduction Steps:**
1. Import project from Subversion
2. Open any file form 'trunk' directory in the editor
3. Select this file
3.  Run 'Subversion'->'Delete' in the top menu

**Expected behavior:**
 File is deleted from directory, is not present in the project explorer and the file tab is closed.

**Observed behavior:**
File is deleted from directory, **but it present** in the project explorer and the file tab is opened.
![delete_svn](https://cloud.githubusercontent.com/assets/8051404/18274345/9e87c928-744a-11e6-8be6-59ee56a64bb5.png)

**Che version:**     4.8.0-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**    local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by tolusha** [comment]
Can't reproduce
