### ISSUE TITLE
Need guide for Maven Usage

### ISSUE THREAD

**Issue by randywallace** [eclipse-che/che#236]
I am having a heck of a time trying to get the Java/Maven integration working with our project.  We don't use Maven (buildr actually) so I've attempted drafting pom.xml files to make Che discover modules and whatnot, and more often than not, either Che will delete the whole project when reloading the workspace, or it will render a submodule/child completely invisible in the UI.  I've tried figuring out how to skulk around delete stuff so I can try again (i.e. the .codenvy folders littered about) but it doesn't help.  I have used the che repo's pom.xml files as a reference.

I've tried to do it all thru the 'Create Project' and 'New => Maven Module' dialog(s) and by manually creating pom.xml files with a little success, but (way) more often than not its unsuccessful.

I'd rather _not_ use Maven, but afaict it seems to be the only option to get Che to pull down external dependencies and make a project's java source editable.  We have Eclipse .classpath and IntelliJ idea files littered about, is there any way I can use those?!

**Comment by TylerJewell** [comment]
You do not have to use maven.  We need to learn more about your setup, but if you want to use buildr, you can do so.

The steps to using buildr:
1. You will need to get buildr installed into your workspace.  You have two choices here.  If you have already created the workspace, you can then use the terminal and just install it on the command line. It'll then be available to your workspace for the duration that the workspace is active.  You can author commands that use any software available on the command line.
1. If you want buildr to be installed into your workspace as it is created, this gets into write a custom stack as a Dockerfile. The Dockerfile will have the command to get buildr installed.

Let us know which path you'd like to take - but this should solve your issues.

**Comment by randywallace** [comment]
I don't think you understand my issue.

I have a (very) custom Dockerfile that I use as a recipe that installs all that, and a bunch more (jetty, npm, node, ruby, ant ... ... ).  I have no problem with buildr and our environment in the Terminal, nor do I have any issues with what my Dockerfile needs in order to interoperate properly with Che (i.e. those fancy LABEL's for the machine view).  But if I only used the terminal, there's no point in using Che in the first place.

The problem is not with the terminal, or the workspace. 

The problem is with the Project Explorer, and getting it to detect our java projects and external dependencies from our private github repo.  I need help with setting up whatever needs to be setup so that I can get our non-maven project to be detected as a 'java' project so all the java intellisense stuff will work.  

Right now, since the project I am importing into the workspace via our github private repo is not a maven project (which is the only option right now), I cannot use all that java goodness.  Once I start trying to turn it into one tho, thru the IDE, either thru manually creating pom.xml files, or using the project dialogs in the menu and project explorer (i.e. create maven module), things blow up and either che completely wipes out the project (all the way to the /projects folder) or it hides all of our java source files in the explorer, making editing them in the IDE impossible.  

This does not seem to be due to poorly formatted maven pom files, it seems more to do with what the maven plugin does with that information after reloading the workspace or project explorer.  For example, I see that the che project uses both inheritance and modules throughout; do I have to do that for every module?  

What is the maven plugin looking for me to do so that it will detect my project correctly while I am working in the IDE to get it up to par?  Is there a maven command I can run while working on pom files to see how Che would eventually detect it, so that I can work on it outside Che and be certain everything will be detected correctly (I would rather not merge a whole bunch of pom.xml files into our default branch prior to knowing if they will even work as expected, since I cannot specify in Che which branch to checkout when using private github repos). 

Does that make more sense?

**Comment by ghost** [comment]
All java features will work only if this is a Maven project with a valid pom.xml. So, you will need to mavenize your project.

As to helping you with your project setup, it's extremey difficult to do that without actually tking a look at the project.

**Comment by randywallace** [comment]
I see that nobody intends to actually answer the questions that I have asked, regarding the bugginess of the Project Explorer in the process of attempting to mavenize my project..  After a grueling effort I figured out what I needed to.  Thanks anyway.

**Comment by TylerJewell** [comment]
Randy:  Eugene is providing the right answer.  You are asking about how project auto detection, also called an estimation process works.  For maven in Che the detection algo works by looking for a valid pom.xml.  If that is not there the project will be treated as another.   There is also manual configuration with the project -> configuration menu option.

If the tree is wiping out then something is amiss.  Can you provide steps to reproduce or a short screencast.
