### ISSUE TITLE
Not able to import projects from my Github account though can see the projects listed. 

### ISSUE THREAD

**Issue by gma-git-admin** [eclipse-che/che#2360]
[err.txt](https://github.com/eclipse/che/files/457803/err.txt)

Am facing this issue for a while on Che 4.7.0 on EC2 ubuntu 14.04 running on remote. I am trying to import projects from GitHub while selecting Node stack. It works fine till starting the workspace and gets stuck while creating project. When within the workspace if I select Workspace->Import Project it shows a blank dialog box with the import button. So I don't find any ways to import projects from my github account. Please help. The error log files are mostly blank and at times they have this line at the end: 
**Client has aborted connection. Response writing omitted.**

**Reproduction Steps:**
1. Select Create New Workspace from Dashboard page
2. Select Source as Import from existing location' on New Workspace page
3. Select Github from the available options. All the available projects are listed there
4. Select a specific project
5. Select Create new workspace from stack from Select Workspace option
   6, Click the Create button

**It should clone the github repo and create a new project in the workspace**

**The program gets stuck at the Create Project step and the log is mostly blank while at times have the following line in the end
`[o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.`**

**Che version:**    4.7.0  
**OS and version:** EC2 Ubuntu 14.04 Trusty  
**Docker version:** 1.12.1  
**Che install:**    Docker container   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Not Sure
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ghost** [comment]
@gma-git-admin can you share a screenshot please? Empty import menu is smth very unusual.

**Comment by thyeun** [comment]
@gma-git-admin, are you also getting a "timeout" message?

**Comment by gma-git-admin** [comment]
@eivantsov please find the screenshot as requested

![che-import](https://cloud.githubusercontent.com/assets/18621769/18320832/15a80f6c-74f1-11e6-839a-98143ccc9a88.png)

Also I observed that am not able to create a sample project either. After a while it gets stuck and I get a Retry button. When I get into the workspace I do find the project however with a red cross mark and I can't delete the project either. While in the dashboard view there is no project listed for the given workspace. I guess there is problem while working with projects. Am not sure what's wrong here.

**Comment by gma-git-admin** [comment]
@thyeun Am not sure about that though it seems similar to that. Most of the time there are blank logs and sometimes we get the ones that is already uploaded.

**Comment by thyeun** [comment]
@gma-git-admin it look like you are not using the newer che launcher. So, which che launcher syntax are you using?

**Comment by gma-git-admin** [comment]
@thyeun  Am using the following command to launch Che

 `sudo docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_HOST_IP=<My_EC2_Public_IP> -e CHE_PORT=8080 -e CHE_CONF_FOLDER=/etc/che eclipse/che start`

This is taken from https://eclipse-che.readme.io/docs/usage-docker

**Comment by TylerJewell** [comment]
@gma-git-admin - that syntax looks good. Your issue is very unusual. Could you try a couple things for me, please. The eclipse/che image is a pointer to another one that is more actively maintained, `codenvy/che-launcher`.  So please, can you do some things for me.

```
# First, delete all of your docker images on your existing system, especially any related to codenvy/che-server and eclipse/che.  Use `docker rm -f <imgid>`

docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_HOST_IP=<ip> -e CHE_VERSION=4.7.0 codenvy/che-launcher:nightly start
```

If you want a simpler interface, we have a CLI that you can install - it simplifies a lot of this stuff. You can just configure some of these vars and then run `che start`, `che stop`.  https://eclipse-che.readme.io/docs/che-getting-started

Let us know if the issue still happens.

**Comment by gma-git-admin** [comment]
Thanks @TylerJewell for the detailed help. I followed your instruction but the result was almost same.

So after installing Che, I tried following:
1. Create project from dashboard using NodeJS sample. It got stuck. The corresponding screenshot and log is attached.
2. Open the workspace, create project from workspace menu. An error dialog box appears with blank no message even though a project appears in the project explorer window. The screenshot is attached.
3. Import project from workspace menu. The blank Import Project dialog box appears as earlier. Please note that the OAuth details for Github was not provided yet. The screenshort is attached.

The log output of the first step though provides some indication. 

```
[STDOUT] 2016-09-08 03:58:18,992[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/ws-agent/webapps/wsagent.war
[STDOUT] 2016-09-08 03:58:24,343[ost-startStop-1]  [ERROR] 
[e.c.p.m.s.c.c.ClasspathManager 87]   - Maven server not started looks like you don't have Maven in your path
```

And a simple google search took me to https://github.com/eclipse/che/issues/1482. But I couldn't follow the instruction there.

A `docker version` command produces the following output:

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

```

![che_create_project](https://cloud.githubusercontent.com/assets/18621769/18337127/75bb2792-7553-11e6-82b2-cf2b0aaf9a05.png)
![che_create_project_dashboard](https://cloud.githubusercontent.com/assets/18621769/18337126/75b9631c-7553-11e6-88f7-2bc9ce231cd4.png)
![che_import_project](https://cloud.githubusercontent.com/assets/18621769/18337125/75b63520-7553-11e6-8030-95a5626c0d07.png)

**Comment by ddementieva** [comment]
@gma-git-admin Have you tried to do that in an incognito mode?

Also, can you try to create a new workspace, create project in it and see if there are any errors in the browser dev console? Can you send us screenshots of these steps with browser dev console opened?

**Comment by gma-git-admin** [comment]
@ddementtieva Let me try in the incognito mode. But I want to get hang of this issue. Are all this problems just because of that? The issue of maven server not starting as seen in the attached log has anything to do with this? Or is my docker causing this as I find in issue #1482. Am quite clueless about all this and some guidance and explanation would be of great help. Thanks.

**Comment by TylerJewell** [comment]
We have never seen this issue before. So we do not know the root cause.  All of our ideas are experiments to try and get some clues.

**Comment by thyeun** [comment]
@gma-git-admin can you clear your browser data (cache images and file, browsing history, and download history). Because one of your screenshoot are same with my issue before.

**Comment by gma-git-admin** [comment]
@thyeun  I did exactly what you suggested with the same result.

I guess the problem is the conflict between external and internal IP address usage with Docker in the EC2 environment. And as it appeared from the log file that there is problem in communication between the Che Server and the workspace agent. 

I ran the following command:

`sudo che info --networking
`
and following is the output:

```
WARNING: No swap limit support
INFO:
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: Browser             => Workspace Agent (Hostname)   : Connection succeeded
INFO: Browser             => Workspace Agent (External IP): Connection succeeded
Unable to find image 'codenvy/che-server:latest' locally
latest: Pulling from codenvy/che-server
Digest: sha256:ca680e83a16b816fcb4d4cf9ccd0c356898856298d4d4dba129c47585ed71c32
Status: Downloaded newer image for codenvy/che-server:latest
curl: (6) Couldn't resolve host ' '
/usr/local/bin/che: line 887: -I: command not found
INFO: Che Server          => Workspace Agent (External IP): Connection failed
INFO: Che Server          => Workspace Agent (Internal IP): Connection succeeded
```

Now it's clear that Che Server to Workspace Agent on External IP connection is failing. I generally run Che on the external IP so that it's accessible remotely.  Hope this gives you guys some clue.

**Comment by TylerJewell** [comment]
@gma-git-admin - there was a bug in the Che CLI that would cause that problem.  Can you get the latest from master (just download it again) and rerun it.  Another user had this issue and we saw that this test was reporting certain things incorrectly.

**Comment by gma-git-admin** [comment]
@TylerJewell so do you mean to run the following command again after clearing the existing docker che images?

`docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_HOST_IP=<ip> -e CHE_VERSION=4.7.0 codenvy/che-launcher:nightly start`

If so, then I did just that before reporting my last update.

**Comment by TylerJewell** [comment]
Yes - ok, thanks.  Also please grab the latest CLI from master - just redownload it and then rerun "che info --networking"

**Comment by gma-git-admin** [comment]
@TylerJewell So, I did all that with no change in fortune. Also, I did a few things on my end:
1. In che.properties file modified the che_host with the public ip address of the ec2 instance `machine.docker.che_api.endpoint=http://<EC2_Public_IP>:${SERVER_PORT}/wsmaster/api`

This resolved the network issue as highlighted in my earlier comment
1. Installed Java version 1.8.0_101 and this resolved the Maven server not getting started as found in the logs

**But it still didn't solve my problem of not getting the projects created. I can't create it from dashboard, neither from within the workspace and nor can import one from GitHub.**

I tried all the options suggested so far; getting the nightly build for che, getting the latest che cli, and accessing the IDE from incognito Chrome window after clearing out all history cache etc. It's still the same output with similar screenshots that is shared with earlier comments.

Please note that am using AWS EC2 Ubuntu environment for this installation.

**Comment by TylerJewell** [comment]
Please look at @ddementieva note - she is wanting some screen shots of chrome developer console to see if there are any debugging stack traces in there.

**Comment by gma-git-admin** [comment]
@TylerJewell and @ddementieva:

I tried to create new project in existing workspace with the following result:

The dashboard view

![create_project_dashboard_err_view](https://cloud.githubusercontent.com/assets/18621769/18367614/aeb227d8-75e1-11e6-8cd0-396b723dec2a.png)

The dev consolve view

![che_create_project_console_log](https://cloud.githubusercontent.com/assets/18621769/18367629/c29423aa-75e1-11e6-848d-a8e39605ebfe.png)

And the log file which is considerably different than earlier ones

[create_project_log.txt](https://github.com/eclipse/che/files/462749/create_project_log.txt)

Hope this helps. Thanks.

**Comment by TylerJewell** [comment]
@ashumilova - any ideas?  It looks like the agent has not been successfully started.  @gma-git-admin - are you sure that there are no error outputs in the section titled "Starting workspace agent..."?

**Comment by gma-git-admin** [comment]
@TylerJewell Am getting just this one error message in the section "Starting workspace agent" and this I had shared in my earlier comments too. 

```
[STDOUT] 2016-09-09 05:52:48,338[ost-startStop-1] [ERROR]
[e.c.p.m.s.c.c.ClasspathManager 87] - Maven server not started looks like you don't have Maven in your path
```

And these are the last few lines under the same section

```
[STDOUT] 2016-09-09 05:52:48,788[main] [INFO] 
[o.a.catalina.startup.Catalina 642] - Server startup in 6415 ms
[STDOUT] 2016-09-09 05:52:49,008[nio-4401-exec-1] [WARN ] 
[o.e.c.impl.ContainerResponse 93] - Client has aborted connection. Response writing omitted.
```

I think the last line here probably has some clue to our problem. But am not sure how to further debug this.

**Comment by ghost** [comment]
@TylerJewell  the agent has successfully started. Maven server not starting because it failed for find M2_HOME env.

@gma-git-admin what stack do you use to create a workspace? Also, what kind of project are you trying to import?

We are able to create projects on your instance of Che!

Can you create a workspace from the default Java stack and a sample Java app please?

**Comment by ashumilova** [comment]
Also dashboard has the problem - not correctly handling the error occurring in this case. Will handle it.

**Comment by gma-git-admin** [comment]
@eivantsov  How to set M2_HOME env? Also I noticed that Maven server gets started fine for Java but not for Node, two of the stacks am working with

Am trying to import angular project from my github account using Node stack. 

By the way I tried creating workspace from the default Java stack and a console-java-simple project but had the same outcome. The log file is attached for reference.

[create_java_project_log.txt](https://github.com/eclipse/che/files/463363/create_java_project_log.txt)

**Comment by ghost** [comment]
@gma-git-admin node stack does not have maven. Why do you import a Java project into a node stack?

I can create projects on your Che instance.

![image](https://cloud.githubusercontent.com/assets/5337267/18385995/900aa510-769c-11e6-8a0d-3c3db2bf888a.png)

**Comment by ghost** [comment]
@gma-git-admin can you record a video of how you create a Java stack with a Java sample app and get this error? Your Che instance is totally OK for me.

**Comment by gma-git-admin** [comment]
@eivantsov I don't create Java project in node stack but angular one. Not sure why it tries to start Maven there though.

I also can get to the dialog box that you are getting there while creating new project in existing workspace from within ide. Once we click Create, an Error dialog box appears with no message. The project explorer does get a project though [only if you use existing sample project. For a new project you don't get any project in explorer too]. But if you try to delete it, it won't. The same behavior is observed while working with both Node and Java stack.

Also my objective is to import existing project from Github. I can't get it either from the dashboard or from within the IDE. If I try from dashboard it gets stuck in create project section. And in the IDE, if I select Import project from workspace menu, a blank dialog box appears with no option. Hope this explains my case. Am going to perform this action and share the recording in my next update. Thanks.

**Comment by gma-git-admin** [comment]
@eivantsov - I recorded the steps for creating simple Java project from both dashboard and IDE. In both the cases, it failed. While in the first it got stuck and then the Retry button appeared. This time though I got the blank log because was using existing workspace. So generally there is no log for the step "Creatign project".  For the second, got the blank Error dialog box.

Recording for both the activities are attached for reference. 

[create_new_java_project_from_dashboard.zip](https://github.com/eclipse/che/files/464520/create_new_java_project_from_dashboard.zip)
[create_new_java_project_from_ide.zip](https://github.com/eclipse/che/files/464519/create_new_java_project_from_ide.zip)

**Comment by gma-git-admin** [comment]
Are you guys still on it? We have committed as an organization to use cloud IDE for all our development activities and have few projects in python  and angular that has to be made available to the team for collaboration over the cloud. We explored with a few cloud IDEs and Che seemed most suitable to our requirements being comprehensive and mature. Let me know if you need any further detail from me or want me to try something else on my end. Look forward to hear from you guys.

**Comment by TylerJewell** [comment]
@gma-git-admin - This is open source and a public forum. You are getting free support. The engineers will take a look when they get a moment.  If you are working against a timeframe, Codenvy provides paid support contracts with an SLA where responses are guaranteed and prioritized over the community request.

Now - two things.  We always appreciate getting more materials to help.  I don't think the attached documents offer any insight into what is happening.  There are a few things that you can do:
1. First, please record the steps that you take in an animated gif that can be pasted directly into this issue.  There are many pieces of software available that let you record an animated gif. When you do the animation, open Google Chrome Dev Tools (inspect) so that we can see all of the console operations and any errors that appear. This is very important.
1. Second, hvae you tried setting up Che on Digital Ocean?  It's cheap and very easy.  I'd like to rule out your client as a problem.  If you set it up on digital ocean and have identical issues, then there is something going on with your client & network we have to investigate.

**Comment by thyeun** [comment]
@gma-git-admin, do you have two different host-ip? one docker_ip and one host_ip? when you have two different ip, your websocket wont be working fine as it should be, but you still can go into your IDE, and you wont be possible to let workspaces working as usual. 

an example, if you have one internal ip and one external ip, than your websocket need to have your internal ip to communicate with your docker. (i dont know how to explain, but i can re-produces two of your screenshot above).

1st one 
"[STDOUT] 2016-09-09 05:52:48,788[main] [INFO] 
[o.a.catalina.startup.Catalina 642] - Server startup in 6415 ms
[STDOUT] 2016-09-09 05:52:49,008[nio-4401-exec-1] [WARN ] 
[o.e.c.impl.ContainerResponse 93] - Client has aborted connection. Response writing omitted."

2nd one is the retry screenshot on creating project. actually this one happen because your workspaces can 't launch successfully due to that your websocket are timemout!!

**Comment by gma-git-admin** [comment]
@thyeun, you are right there and I believe that's the issue but I don't know how to address that. As specified earlier, am running Che on EC2 instance and accessing that on its public IP address but the Docker runs on its internal IP address by default. In my earlier update, had mentioned that I overwrote this line by replacing **che_host** with public IP address of the host EC2 instance.

`machine.docker.che_api.endpoint=http://**EC2_PUBLIC_IP**:${SERVER_PORT}/wsmaster/api`

to get rid of the following connection issue:

```
INFO: Che Server          => Workspace Agent (External IP): Connection failed
INFO: Che Server          => Workspace Agent (Internal IP): Connection succeeded
```

Also  in my earlier update had alluded to issue #1482 which looked similar to this. Can you please explain to me or refer me to a link explaining how to resolve this internal and external IP issue? That will be a great help.

@TylerJewell, Appreciate help and support from your team. My question was just to ensure that I can wait to hear from you guys because on our end we have exhausted all other forums and this is the only window available as of now. Also I guess as more users move to use Che and report diverse range of issues from their different setup env, it helps Che as a product to get more mature with wider acceptability and user base. We will positively go for paid support contracts once we have our dev env comprehensively transitioned to Che. Thanks for the help and support though!

**Comment by thyeun** [comment]
@gma-git-admin good day, first things, you need to know which docker_ip are communicate in between, so, to know the ip, use "docker-machine ls" it will show you the ip (your-internal-ip).

2nd one, your Oauth setting need to be the same exact ip too. 

so the result will be like below

CHE_HOST={your-internal-ip}
Oauth github call back = {your-internal-ip}
Oauth github URL={your-external-ip}

and make sure you know which is your internal and external ip.

**Comment by ghost** [comment]
Three things. First, if I go to your Che installation I can import projects.

![image](https://cloud.githubusercontent.com/assets/5337267/18434472/fbaecd7c-78f5-11e6-86e5-4e36a4a140b9.png)

Second thing is - is the project you are trying to import a private or public one?

Third thing - can you share a screenshot with dev console on?

It is some connectivity issue on your side since I can use your Che installation without any restrictions.

**Comment by gma-git-admin** [comment]
@eivantsov, am very much perplexed as to the reason of it not working at my end. Am accessing the Che IDE over a wireless connection. Hope that's not causing any issue. I tried multiple options but no change in luck here. It keeps throwing the same issue. Am going to send the mp4 file of screen recording in my next update. 

@thyeun, am not thinking about OAuth and importing projects from GitHub now rather focused around just creating some sample project. The issue is am not able to create project either from dashboard or from within the workspac IDE. Both the times I get the same issue. 

Changes in the che.properties file [excluding OAuth section]:

```
machine.docker.che_api.endpoint=http://54.149.167.58:${SERVER_PORT}/wsmaster/api
api.endpoint=http://54.149.167.58:${SERVER_PORT}/wsmaster/api

```

Command to start Che

`sudo docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_HOST_IP=54.149.167.58 -e CHE_PORT=8080 -e CHE_VERSION=4.7.0 -e CHE_CONF_FOLDER=/etc/che codenvy/che-launcher:nightly start`

And here are the screenshots:

![step1](https://cloud.githubusercontent.com/assets/18621769/18448639/7e192c1c-78f1-11e6-9414-3880ce18dd7e.png)
![step2](https://cloud.githubusercontent.com/assets/18621769/18448637/7e1437c0-78f1-11e6-9891-962fffbcbb23.png)
![step3](https://cloud.githubusercontent.com/assets/18621769/18448636/7e141966-78f1-11e6-9e9c-26c6f00e49eb.png)
![step4](https://cloud.githubusercontent.com/assets/18621769/18448640/7e1979b0-78f1-11e6-93da-25850170f88d.png)
![step5](https://cloud.githubusercontent.com/assets/18621769/18448638/7e1660a4-78f1-11e6-8341-40aaf33151ab.png)
![step6](https://cloud.githubusercontent.com/assets/18621769/18448641/7e1a3e18-78f1-11e6-8adb-1fe01df4d7ba.png)
![step7](https://cloud.githubusercontent.com/assets/18621769/18448642/7e1f863e-78f1-11e6-9fcc-3527163ea7e7.png)

By the way, the eth0 IP address probably used by Docker is 172.31.37.152.

**Comment by gma-git-admin** [comment]
So I tried Bitnami private cloud setup and surprise! The issue persists. So I agree with @eivantsov that the problem seems to be at my end. Am using Windows 7 machine with Chrome and Firefox browsers over wireless connection. Have tried with both office and home internet connection with same result. Not sure what's next steps for me.

**Comment by TylerJewell** [comment]
@gma-git-admin - if you are in windows 7 - is it possible that there is either:
1. Windows firewall on - and it's being unnecessarily aggressive in blocking important communications.
2. You have some sort of malware on your particular computer that is causing an issue.

So - things to try - test the connection on another computer in the same location. Disable all firewalls and test on your primary computer.

**Comment by ghost** [comment]
@gma-git-admin @TylerJewell it's interesting. It's not connection time out. So, it's not blocked ports issue. It's empty response which I do not get on my end.

@gma-git-admin do you have a chance to access your Che installation using a different connection?

**Comment by gma-git-admin** [comment]
@TylerJewell  @eivantsov  So tried again on my primary computer disabling all the firewall but with no change in the outcome. I also agree with @eivantsov  that it's not port issues. Meanwhile I did some googling and came across this: http://stackoverflow.com/questions/12073455/net-4-5-websocket-server-running-on-windows-7. So it seems like websocket issues on Windows 7 causing this erroneous behavior. Meanwhile I tried accessing Che on my IPad and it worked like charm. I tried creating simple Java projects from dashboard and from within workspace without any issues. Will try importing angular projects from GitHub and see if that works alright.

Thank you @eivantsov, @thyeun, @TylerJewell, @ddementieva and @ashumilova for the continuous help and support. You guys kept me going. Thanks much again :)

**Comment by TylerJewell** [comment]
That was an interesting link.  I wonder if Firefox or Mozilla browser on Windows 7 ships with the third party libraries to overcome the issue you have encountered?

What is your strategy now for overcoming the hurdle?

**Comment by gma-git-admin** [comment]
@TylerJewell @eivantsov So I further tried running this on different OS env. It did work on mac with firewall disabled. Probably it will work on Windows 10 also with firewall setting appropriately configured or disabled. 

However, I observed some other small issues occurring intermittently. At times workspace will fail to initialize or take forever to load. The workaround for me was to start the workspace from dashboard view and then wait till the workspace is in running state and then open that. Similarly, the project import at times will appear in proper expected form and at some other time the blank dialog box will appear. I guess this may be because of slow or broken Internet connection. Also, the Node stack does try to start the Maven server which is not an expected behavior I believe.

@TylerJewell Strategy for us would be either upgrade to Windows 10 that seemingly has the websocket  issue resolved or transition to ubuntu platform.

**Comment by TylerJewell** [comment]
These behaviors are just super odd.  I think for our engineers to properly diagnose them when they are happening, we'd need to schedule a support screen share, so that they can grab a bunch of diagnostics packets when the issue is happening to see if we can detect / work around the issue somehow.
