### ISSUE TITLE
Can't load project

### ISSUE THREAD

**Issue by Driky** [eclipse-che/che#2361]
When i try to access my ide i get an error where i can't load my project

![bro](https://cloud.githubusercontent.com/assets/1233974/18294924/413db6f8-749d-11e6-9e27-8c108c3ddcc5.png)

The request that fails on this image try to access the right IP but on port 32788. My installation use port 8080.

Here are some informations, if you need more tell me.

**che info --networking**

```
INFO: ECLIPSE CHE: Loaded profile one
INFO:
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: Browser             => Workspace Agent (Hostname)   : Connection succeeded
INFO: Browser             => Workspace Agent (External IP): Connection succeeded
curl: (6) Couldn't resolve host ' '
/usr/local/bin/che: line 887: -I: command not found
INFO: Che Server          => Workspace Agent (External IP): Connection failed
INFO: Che Server          => Workspace Agent (Internal IP): Connection succeeded
```

**che info**

```
INFO: ECLIPSE CHE: Loaded profile one
INFO: ---------------------------------------
INFO: ---------    CLI DEBUG INFO    --------
INFO: ---------------------------------------
INFO:
INFO: ---------  PLATFORM INFO  -------------
INFO: CLI DEFAULT PROFILE       = one
INFO: CHE_VERSION               = latest
INFO: CHE_UTILITY_VERSION       = nightly
INFO: DOCKER_INSTALL_TYPE       = native
INFO: DOCKER_HOST_IP            = 172.17.0.1
INFO: IS_NATIVE                 = YES
INFO: IS_WINDOWS                = NO
INFO: IS_DOCKER_FOR_WINDOWS     = NO
INFO: IS_DOCKER_FOR_MAC         = NO
INFO: IS_BOOT2DOCKER            = NO
INFO: HAS_DOCKER_FOR_WINDOWS_IP = NO
INFO: IS_MOBY_VM                = NO
INFO: HAS_CHE_ENV_VARIABLES     = YES
INFO: HAS_TEMP_CHE_PROPERTIES   = NO
INFO: HAS_INTERACTIVE           = YES
INFO: HAS_PSEUDO_TTY            = YES
INFO:
DEBUG: ---------------------------------------
DEBUG: ---------    DEBUG INFO    ------------
DEBUG: ---------------------------------------
DEBUG:
DEBUG: ---------  PLATFORM INFO  -------------
DEBUG: DOCKER_INSTALL_TYPE       = native
DEBUG: DOCKER_HOST_OS            = Ubuntu 16.04 LTS
DEBUG: DOCKER_HOST_IP            = 172.17.0.1
DEBUG: DOCKER_DAEMON_VERSION     = 1.11.1
DEBUG:
DEBUG:
DEBUG: --------- CHE INSTANCE INFO  ----------
DEBUG: CHE CONTAINER EXISTS      = YES
DEBUG: CHE CONTAINER STATUS      = running
DEBUG: CHE SERVER STATUS         = running & api reachable
DEBUG: CHE IMAGE                 = codenvy/che-server:latest
DEBUG: CHE SERVER CONTAINER ID   = bd2d439db21d
DEBUG: CHE CONF FOLDER           = /home/user/che/prop
DEBUG: CHE DATA FOLDER           = /home/user/che/workspaces
DEBUG: CHE USE URL               = http://163.172.128.44:8080
DEBUG: CHE API URL               = http://163.172.128.44:8080/swagger
DEBUG: CHE LOGS                  = run `docker logs -f che-server`
DEBUG:
DEBUG:
DEBUG: ----  CURRENT COMMAND LINE OPTIONS  ---
DEBUG: CHE_PORT                  = 8080
DEBUG: CHE_VERSION               = latest
DEBUG: CHE_RESTART_POLICY        = no
DEBUG: CHE_USER                  = root
DEBUG: CHE_HOST_IP               = 163.172.128.44
DEBUG: CHE_LOG_LEVEL             = info
DEBUG: CHE_DEBUG_SERVER          = false
DEBUG: CHE_DEBUG_SERVER_PORT     = 8000
DEBUG: CHE_HOSTNAME              = localhost
DEBUG: CHE_DATA_FOLDER           = /home/user/che
DEBUG: CHE_CONF_FOLDER           = /home/user/che/prop
DEBUG: CHE_LOCAL_BINARY          = not set
DEBUG: CHE_SERVER_CONTAINER_NAME = che-server
DEBUG: CHE_SERVER_IMAGE_NAME     = codenvy/che-server
DEBUG:
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
DEBUG: ---------------------------------------
```

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@Driky - are you behind a firewall?  What happens when Che boots is that each workspace is launched as a set of docker containers. The internal services of the containers are launched on ports like 8080, but they are exposed to the world through the ephemeral port range 32K+.  Your browser then maintains a connection to the Che server running on port 8080 and each workspace through a different set of ports.  If you go into the terminal and do a `docker ps`, you will see the containers.

Also, you might try doing a `che info --networking` to do a test to see if you can reach the appropriate communications.

**Comment by Driky** [comment]
No firewall blocking those ports

You can find the result of  `che info --networking` in my initial post

**docker ps**

```
CONTAINER ID        IMAGE                                                                       COMMAND                  CREATED             STATUS              PORTS                                                                                                                                              NAMES
dcc422676de0        eclipse-che/workspacenq7mo8g68tlokdfe_machinen30b5r5w3tecemdw_che_default   "/home/user/entrypoin"   About an hour ago   Up About an hour    0.0.0.0:32791->22/tcp, 0.0.0.0:32790->80/tcp, 0.0.0.0:32789->3306/tcp, 0.0.0.0:32788->4401/tcp, 0.0.0.0:32787->4403/tcp, 0.0.0.0:32786->4411/tcp   workspacenq7mo8g68tlokdfe_machinen30b5r5w3tecemdw_che_default
bd2d439db21d        codenvy/che-server:latest                                                   "/home/user/che/bin/c"   About an hour ago   Up About an hour    8000/tcp, 0.0.0.0:8080->8080/tcp                                                                                                                   che-server
```

And the error that is shown when i load my ide is : 
`Error: Can't load project types: Error    at Object.window.IDE.eventHandlers.initializationFailed (http://163.172.128.44:8080/che/wksp-php?uid=57896:39:27)    
at Bwb (_app-0.js:2000:406)    
at Owb (_app-0.js:2006:56)    
at _.gq (_app-0.js:4281:319)    
at eval (_app-0.js:978:86)`

**Comment by TylerJewell** [comment]
Oops - I didn't see the extra output.  Looks like someone somewhere has reverted the networking tests.  I am not sure that test is failing for you - rather it may be a test failure.  I'm going to give you some more diagnostics in a moment.

In the mean time can you do `ifconfig`?

**Comment by Driky** [comment]
**ifconfig**

```
docker0   Link encap:Ethernet  HWaddr 02:42:ee:98:68:b4
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:eeff:fe98:68b4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:39952 errors:0 dropped:0 overruns:0 frame:0
          TX packets:36605 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:36656810 (36.6 MB)  TX bytes:2619563 (2.6 MB)

eth0      Link encap:Ethernet  HWaddr 00:07:cb:03:ed:92
          inet addr:10.1.165.9  Bcast:10.255.255.255  Mask:255.255.255.254
          inet6 addr: fe80::207:cbff:fe03:ed92/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:961542 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2790828 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1115590480 (1.1 GB)  TX bytes:4109198464 (4.1 GB)
          Memory:80000000-8001ffff

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:10 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:1038 (1.0 KB)  TX bytes:1038 (1.0 KB)

veth18b7135 Link encap:Ethernet  HWaddr 6e:54:0e:83:dc:d3
          inet6 addr: fe80::6c54:eff:fe83:dcd3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:12407 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10971 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:23515476 (23.5 MB)  TX bytes:811384 (811.3 KB)

vethc3fde18 Link encap:Ethernet  HWaddr 26:e5:36:a0:8d:f2
          inet6 addr: fe80::24e5:36ff:fea0:8df2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:18953 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18942 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1047999 (1.0 MB)  TX bytes:1388964 (1.3 MB)
```

And thank you for your help :-)

**Comment by TylerJewell** [comment]
Your default CHE_HOST_IP is being set to 163.172.128.44, but it seems that your eth0 is 10.1.165.9.  What happens if you:

```
export CHE_HOST_IP=10.1.165.9
che start
```

**Comment by Driky** [comment]
10.1.165.9 is the private IP of my server. It is available only from the local network, it is used for communication between different servers.

**Comment by TylerJewell** [comment]
I was surprised that the workspace even booted.  And just to confirm, if you access "http://localhost:8080/" you get the same issues when opening a workspace as well?

**Comment by Driky** [comment]
localhost ? since che is on my server (distant) localhost shouldn't come into play ?

**Comment by TylerJewell** [comment]
It shouldn't - no, and it will be a problem, but I am trying to figure out if you can get a workspace to load if browser and server are same host.

**Comment by Driky** [comment]
i'm not sure to understand. I can't have a browser from the same host than my server since I only have an ssh access to that one.

Do I miss something ?

**Comment by TylerJewell** [comment]
You are not missing anything - was just ruling out different scenarios.  Is there a reason that your server's external IP address, 163.172.128.44, is not appearing when you do an ifconfig?

**Comment by TylerJewell** [comment]
Can you replace the che.sh that is on your server with the one here, and re-run `che info --networking` please.

https://github.com/eclipse/che/blob/98c0df30772af229bb12c9fc2a88e00a70740f03/che.sh

**Comment by Driky** [comment]
not that i know. I didn't touch the network configuration of the server. From what i have read it is the normal behavior.

**Comment by TylerJewell** [comment]
Yeah, I just did a test on ubuntu - on Digital Ocean yesterday.  Works like a champ without having to reconfigure anything.  So it is either websockets being blocked, firewall blocking some ports, or something about the way the workspaces are configured to expose themselves.

If the issue was the last item, the workspace should never load.

**Comment by Driky** [comment]
i did what you asked about che.sh : 

**che info --networking**

```
INFO: ECLIPSE CHE: Loaded profile one
INFO:
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: Browser             => Workspace Agent (Hostname)   : Connection succeeded
INFO: Browser             => Workspace Agent (External IP): Connection succeeded
INFO: Che Server          => Workspace Agent (External IP): Connection succeeded
INFO: Che Server          => Workspace Agent (Internal IP): Connection succeeded
```

The test is working. i w'll try to look around for anything that could block either websockets or ports.

In case i can't resolve my problem and somebody open a new issue with the same one:
My server is hosted by https://scaleway.com

**Comment by TylerJewell** [comment]
@JamesDrummond on our team is a monster scaleway fan - I believe he has set up multiple servers there.

**Comment by JamesDrummond** [comment]
@Driky Been a while since I tried che on scaleways. I took a little time to update my document just for you :). I must say it is way easier to get working. One thing I like about scaleways is it is does not secure ports by default. Some would say that is a bad thing but it is easier to get going and provide your own firewall or update the default security using scaleways.

Let meknow if you get stuck anywhere along the way.

[https://docs.google.com/a/codenvy.com/document/d/1R4tzxs18mgBx1NlTLirTuNuflELC_8fAbK4HiIG4dMM/edit?usp=sharing](https://docs.google.com/a/codenvy.com/document/d/1R4tzxs18mgBx1NlTLirTuNuflELC_8fAbK4HiIG4dMM/edit?usp=sharing)

@TylerJewell Your CLI works really great now BTW.

**Comment by ghost** [comment]
@Driky `CHE_HOST_IP` should be an external IP of the server that is running Che. Also, the ephemeral port range should not be filtered.

**Comment by Driky** [comment]
Hi @JamesDrummond, just seen your message. The google doc is protected so I sent a request for access.

@eivantsov `CHE_HOST_IP` is configured with an external IP from the server and the port range is unprotected.

**Comment by Driky** [comment]
@JamesDrummond i followed your guide which was close to identical to what i had done and it worked. I don't know why but thank you ;-)

**Comment by JamesDrummond** [comment]
@Driky Glade I could help :)
