### ISSUE TITLE
Stop VM running che after idle/inactivity for long time

### ISSUE THREAD

**Issue by lhwong** [eclipse-che/che#2362]
Hi,

I am looking at making change to the code to stop the VM which runs the Che Server after idle/inactivity for long time. Idea on how to implement this is greatly appreciated.

Regards,
--Wong LH

**Comment by ghost** [comment]
The following class `javax.servlet.http.HttpSessionListener` may offer such a possibility:

public interface HttpSessionListener extends EventListener {
   void sessionCreated(HttpSessionEvent var1);

   void sessionDestroyed(HttpSessionEvent var1);
}
