### ISSUE TITLE
After cloning a maven multimodule project root node is not opened

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2364]
**Reproduction Steps:**
1. Clone for example the Artic project and configure as maven
**Expected behavior:**
The root node after configuring should be opened
**Observed behavior:**
The project still closed. The same behavior after consuming a factory with multimodule project.
**Note:** For a user it may not be is important. But some selenium tests may fail. (For example ChecFactoryWithMultiModuleTest)

**Che version:**   4.8.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.12.0
**Che install:**  a10 acceptance server

**Comment by ghost** [comment]
Cannot be reproduced in 5.15-SNAPSHOT
