### ISSUE TITLE
Java package collapses in explorer after some file move operations (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2367]
**Reproduction Steps:**
- Expand a project and open java file (e.g. web-java-spring).
- Perform refactor move the java file to subpackage.

**Expected behavior:**
the package should not collapse after refactor move.

**Observed behavior:**
the package collapses after refactor move.

**Che version:**  5.0.0  
**OS and version:** Ubuntu 14.04  
**Docker version:** 1.11.1 
**Che install:**   local bundle  

**Additional information:**
See the attachment.
![package-after-move](https://cloud.githubusercontent.com/assets/5408906/18306753/f0718548-74f5-11e6-9c09-eccca4b0d2cf.gif)

**Comment by riuvshin** [comment]
regression

**Comment by bmicklea** [comment]
Now that this is a 5.0.0-M1 release let's push this issue - regressions in a Milestone release aren't blockers.
