### ISSUE TITLE
How to run codenvy/openshift-che docker image

### ISSUE THREAD

**Issue by rajasekaran07** [eclipse-che/che#2368]

**Comment by rajasekaran07** [comment]
The docker image codenvy/openshift-che is not available on hub.docker.com I am unable to pull that image. Kindly provide some alternate solution here..

Regards,
Raja

**Comment by ddementieva** [comment]
@rajasekaran07 codenvy/openshift-che image was made for Che 3.x to run Che in Openshift and it has been already deleted. There is no docker type installation for the Openshift and Che 4.x right now.

There is an Openshift plugin for Che 4.x. Have you seen docs on that https://eclipse-che.readme.io/docs/openshift-config?

**Comment by rajasekaran07** [comment]
@ddementieva 

I had tried that too. But Openshift Plugin is not added in my eclipse che console.

Steps I follwed...
1. My Eclipse Che is running on 10.172.112.36:8080, I opened that server
2. Installed Maven and Java
3. cloned openshift plugin in my eclipse che server using "git clone https://github.com/codenvy/plugin-openshift"
4. Moved to plugin folder. "cd plugin-openshift"
5. started maven build "mvn clean install"
6. Created a directory to host conf files "mkdir -p /home/user/.che/plugin-conf"
7. Set CHE_LOCAL_CONF_DIR to be this new folder 
     "echo "export CHE_LOCAL_CONF_DIR=/home/user/.che" >> ~/.bashrc"
8. Created ~/.che/che.properties
   openshift.api.endpoint=https://ose.openshift.loc:8443/
   oauth.openshift.authuri=https://ose.openshift.loc:8443/oauth/authorize
   oauth.openshift.tokenuri=https://ose.openshift.loc:8443/oauth/token
   oauth.openshift.clientid=che
   oauth.openshift.clientsecret=Test!007
   oauth.openshift.redirecturis=http://10.172.112.36:${SERVER_PORT}/wsmaster/api/oauth/callback
9. Created ~/.che/plugin-conf/che.properties
   openshift.api.endpoint=https://ose.openshift.loc:8443/
10. Registered a custom oAuth client in my OpenShift master node
    [root@ose ~]# oc create -f <(echo '

{
"kind": "OAuthClient",
"apiVersion": "v1",
"metadata": {
"name": "che"
},
"secret": "Test!007",
"redirectURIs": [
"http://10.172.112.36:8080/wsmaster/api/oauth/callback"
]
}')
11. Refreshed my eclipse che console but i did not get Openshift plugin there.

Note: I have started my eclipse che using docker run before starting the above all steps.

Please let me know if you want any other details...

**Comment by ddementieva** [comment]
@rajasekaran07 You don't need to build Che. Openshift plugin contains Tomcat assembly, so you can simply download archive, unzip it, perform steps 6-10 from your workflow above and start Openshift plugin itself. 

You can download binaries at http://maven.codenvycorp.com/service/local/repo_groups/public/content/org/eclipse/che/openshift-plugin-assembly-main/4.3.0-RC1-SNAPSHOT/openshift-plugin-assembly-main-4.3.0-RC1-20160609.061451-47.zip 

This is a relatively old version. We are working on an update.

**Comment by rajasekaran07** [comment]
Thank you @ddementieva I will check this during my working hours because I dont have VPN access.
Also one small query here.. 
What is oauth.openshift.clientid and oauth.openshift.clientsecret?
both are user defined values or these data are predefined somewhere? Also in step 6-10 I am not seeing Che start command then how my Eclipse Che will run. (Sorry to disturb you, Since I dont have much idea on this i am getting lot of questions) 
Regards,
Raja

**Comment by rajasekaran07** [comment]
@ddementieva I am waiting for your response...

**Comment by rajasekaran07** [comment]
@JamesDrummond
Here I am trying to import my OpenShift not Git oAuth. The reference you gave in #2335 is related to Git configuration. Looking for some guidance here.

**Comment by rajasekaran07** [comment]
@ddementieva 

I have done with step 6-10, may I know how to start Che..

**Comment by rajasekaran07** [comment]
test che

**Comment by ddementieva** [comment]
@rajasekaran07 `oauth.openshift.clientid` and `oauth.openshift.clientsecret` are user defined values. 
API endpoint is the URL of your OpenShift installation (can be a domain name or IP address). Client ID and secret should match those registered in a [custom oAuth client](https://eclipse-che.readme.io/docs/openshift-config#register-a-custom-oauth-client).

Have you tried to start it with `che.sh run` in the bin directory?

**Comment by rajasekaran07** [comment]
My user id is 1000 now but I am getting permission denied error when run by my user raja, If I am using sudo then it is showing UID!=1000 how to fix this one.

**Comment by rajasekaran07** [comment]
Should we install tomcat before starting che?

Regards,
Raja

**Comment by ddementieva** [comment]
@rajasekaran07 Try to start Che with the following syntax without sudo:
`/home/user/eclipse-che-4.3.0-RC1-SNAPSHOT/bin/che.sh`
Or `cd /home/user/eclipse-che-4.3.0-RC1-SNAPSHOT/bin` and `./che.sh` there.

**Comment by rajasekaran07** [comment]
@ddementieva Both are not working.... **Should we install tomcat before starting che?**

**Comment by eivantsov** [comment]
What exectly does not work for this command?
`/home/user/eclipse-che-4.3.0-RC1-SNAPSHOT/bin/che.sh`

**Comment by ghost** [comment]
Have you tried launching it as user?

**Comment by rajasekaran07** [comment]
@yes I just run the below command from my terminal..

**Comment by ghost** [comment]
Can you remove everything and download the archive again? It looks like smth's wrong with permissions for .sh script that starts tomcat

**Comment by rajasekaran07** [comment]
sure I am trying now... will update you soon..

**Comment by rajasekaran07** [comment]
Getting same error...

**Comment by ghost** [comment]
Try tar.gz http://maven.codenvycorp.com/service/local/repo_groups/public/content/org/eclipse/che/openshift-plugin-assembly-main/4.3.0-RC1-SNAPSHOT/openshift-plugin-assembly-main-4.3.0-RC1-20160609.061451-47.tar.gz

**Comment by rajasekaran07** [comment]
I tried with multiple ways... all are not working...

**Comment by ghost** [comment]
Why are you doing chmod on che.sh? Doesn't it work out of the box?

**Comment by rajasekaran07** [comment]
Should tomcat installed before che executing.?

**Comment by rajasekaran07** [comment]
If I didnt use chmod che would not be execute. Please see below

**Comment by ghost** [comment]
@rajasekaran07 I do not understand your question. Tomcat is packaged inside the assembly that you download. All scripts should be executable there. There's no need to chmod anything there.

**Comment by rajasekaran07** [comment]
I was made that che.sh as executable file using chmod +x che.sh then I run ./che.sh
was it not correct way to execute?

**Comment by rajasekaran07** [comment]
@eivantsov tar.gz is working but I am unable to start my workspace..

**Comment by ghost** [comment]
@rajasekaran07 this is a known issue for some Linux distributions. It's fixed in Eclipse Che. But right now there's no OpenShift assembly with this fix.

https://github.com/codenvy/plugin-openshift/issues/36 you may follow this issue.

**Comment by rajasekaran07** [comment]
Seeing the below error when starting workspace...

**Comment by rajasekaran07** [comment]
@eivantsov 
Is there any way to use this OpenShift assembly with different other OS?
or 
Is there any other way to use OpenShift in Eclipse Che.

Regards,
Raja

**Comment by ghost** [comment]
@rajasekaran07 you need to wait for https://github.com/codenvy/plugin-openshift/issues/36 to be fixed.

**Comment by rajasekaran07** [comment]
@JamesDrummond,
do let me know if there are any complete documents available to configure openshift in Che. I tried with https://eclipse-che.readme.io/v5.0/docs/openshift-config but it is showing error while passing mvn clean install.

Regards,
Raja

**Comment by TylerJewell** [comment]
@rajasekaran07 - we are working on improved documentation for OpenShift this quarter with Red Hat.  We will also have some really nice things to show at their dev nation event in May.

**Comment by vinokurig** [comment]
Is this still an issue? If so please let us know otherwise in 1 week we will close this due to inactivity.

**Comment by TylerJewell** [comment]
This is still an issue.  This needs to be left open until Che on openshift completed.

**Comment by ghost** [comment]
@TylerJewell are you certain Che on OpenShift is an answer here? I think we're talking about OpenShift plugin for Che.

https://github.com/codenvy/plugin-openshift has never been dockerized.

**Comment by TylerJewell** [comment]
@eivantsov - you may be right, and I was misunderstanding the request of the issue.  What is involved with packaging the openshift plugin for Dockerization?  Also, I see it is in a Codenvy repository - did we not choose to open source it with Eclipse Foundation?

**Comment by ghost** [comment]
Dockerizing openshift plugin is the same job we did for Codenvy On Prem, Codenvy SaaS, Che, Artik.. building a custom CLI for it.

**Comment by TylerJewell** [comment]
Let's add this to @vkuznyetsov team for the next sprint.  Would that be ok?

**Comment by ghost** [comment]
If you think this is a priority, then new CLI should be built for this particular assembly. Also, we will need to configure all of the Jenkins jobs to continuously build images

**Comment by TylerJewell** [comment]
Yes, setting this up to be similar to Codenvy is likely a priority.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55
