### ISSUE TITLE
how to configure che to pull private images from docker hub

### ISSUE THREAD

**Issue by asthomasdk** [eclipse-che/che#237]
How do you set up che to be able to log on to Docker hub and pull private images. I want to create a custom stack, using one of our own docker images. 

The only place I can see where I might be able to do this is in the che.properties file - where it looks like I have to store the login credentials in clear text. 

Is this the place to set this up - and then restart the che server to have this kick in? Or am I overlooking something? 

It would be nice to have a UI for this - as it should not be necessary for users have to edit the config file to set this up.

**Comment by randywallace** [comment]
I think there's more to it (I am not one the developers), it needs tags and whatnot as well.. even tho the UI for creating a custom stack doesn't show it; its a 'recipe' .. not just a Dockerfile.

That being said, what I've been doing is pasting in my Dockerfile into the custom stack for the workspace every time i start a project... not the best I agree!

**Comment by asthomasdk** [comment]
According to the docs, 

"It is possible to convert any official image into a Che workspace image, for example use official Node, Ruby, PHP or WordPress images.

Requirements to a workspace machine environment are listed above. To automate installation of Java and other must-have packages, add the following to your Dockerfile:"

You can then add extra lines to the recipe to make it into a che workspace image. 

Haven't tried it yet though - have to be able to pull my private images from Docker hub first...

**Comment by TylerJewell** [comment]
@eivantsov will be able to comment further.

The properties that you found are definitely for setting up access to a private registry.  I know for a fact that the private registry is for saving and loading snapshot images. I have not tested it as to whether it can be used by the worksapce master when creating new workspaces from scratch.  So we will need to get engineering confirmation that the properties in che.properties for registries are for both use cases.

Yes, everyone would love to have a GUI for configuring properties. We have one designed, but it did not make it into the beta.  There are about 50 parameters that people would like to have configured and saved through a GUI.  So it's a non-trivial UI to author.  First step has been to focus on simplifying all of these initial boot & workspace creation steps.

**Comment by asthomasdk** [comment]
Thanks - any info you can provide on this would be appreciated. 

I had hoped that I could cheat and manually do a docker pull onto the docker machine that che is using - so that the FROM image is available locally. But this does not seem to be picked up by che. 

So it would also be interesting to know where Che is looking for cached images.

**Comment by TylerJewell** [comment]
We are working on the local cached images. Che is looking at them in a private directory right now. For the GA, the algorithm on how Che loads its images will change. a docker pull from the specified registry, which by default is docker hub.  If that fails, then the system will fail on you.  

What is weird about the docker behavior is that if you are offline, and have a cached image, the nature of docker will still have this fail.  So we have tested some logic which will let us check local image cache first, and then fall back to check the registered registry second.  But it didn't make it into the beta.  @garagatyi is the engineer that worked on this.

**Comment by asthomasdk** [comment]
Thanks Tyler, 

I will try and get the Docker hub stuff set up in the properties file and see if this works with pulling our own images to create custom workspaces.

**Comment by randywallace** [comment]
Haven't tried it, but these are the registry settings... https://github.com/codenvy/che/blob/3ac1dc9fef84c2062fc621806f2fd000c359dc2a/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L68

You could try hosting a recipe URL (somewhere?) with json dockerfile magic like this: https://github.com/codenvy/che/blob/3ac1dc9fef84c2062fc621806f2fd000c359dc2a/assembly-ide-war/src/main/resources/predefined-recipes.json#L29 pulling in the image from your private repo..  you can get the recipe json format you would need from the machine perspective (switchbox at the very top right in the IDE) under the Recipes 'view' (very far left)... then there is a URL at the right you can load in a new tab to see the json.......

No idea if that would work tho!

**Comment by ghost** [comment]
There is no way right now to pull private DockerHub repositories. However, there's a worksparound.
1. Pull this repo through the command line
2. Set machine.docker.pull_image=false
See [Configuration](https://eclipse-che.readme.io/docs/configuration) for details

Docker will then be able to use local images. Let me know if this helps.

**Comment by asthomasdk** [comment]
Thanks - I will try that and see if I can get that to work.

**Comment by TylerJewell** [comment]
@eivantsov On your proposed work around, is there any reuqirements on where the pulled image is stored, or just any docker pull will do?

**Comment by ghost** [comment]
Docker pull will do the trick. Having changed `machine.docker.pull_image=false` Docker will use a local image.

**Comment by asthomasdk** [comment]
I will give this a go.

**Comment by ghost** [comment]
@asthomasdk Any update? Did you manage to pull a private image manually and can Che then use it locally instead of grabbing it from DockerHub?

**Comment by ghost** [comment]
@asthomasdk I'm closing the issue for now. Feel free to reopen if the suggested workaround does not help.
