### ISSUE TITLE
Not all editor tabs are closed after stopping workspace (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2372]
**Reproduction Steps:**
- Expand a project and open two or more files.
- Perform the stop workspace.

**Expected behavior:**
The editor tabs should be closed.

**Observed behavior:**
One editor tab still stays open.
Also we have errors into console of browser.

**Che version:**    5.0.0  
**OS and version:** Ubuntu 14.04  
**Docker version:** 1.11.1  
**Che install:**    local bundle   

**Additional information:**
See the attachment.
![tab-editor-stop-ws](https://cloud.githubusercontent.com/assets/5408906/18307712/43edb3c8-74fa-11e6-8411-8f90af9d58af.gif)

**Comment by riuvshin** [comment]
regression

**Comment by bmicklea** [comment]
Clearing milestone since this is listed as starting in the next sprint.

**Comment by artaleks9** [comment]
Right now this bug is reproduced again.

**Comment by vparfonov** [comment]
can't reproduce
