### ISSUE TITLE
There is no content of recipe into 'Operation Perspective'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2373]
This function is turned off temporarily by Alexander Garagatyi and will be turned on later.

**Reproduction Steps:**
- Create a workspace and switch to the 'Operations Perspective'.
- Open the 'Recipe' tab. 

**Expected behavior:**
Should be the recipe's information of workspace.

**Observed behavior:**
The content of recipe workspace absent.

**Che version:**    5.0.0  
**OS and version:** Ubuntu 14.04 
**Docker version:** 1.11.1  
**Che install:**   local bundle  

**Additional information:**
See the attachment.
![ws-recipe](https://cloud.githubusercontent.com/assets/5408906/18309514/857a0852-7502-11e6-93e1-88118aff08c2.png)

**Comment by riuvshin** [comment]
regression

**Comment by slemeur** [comment]
panel can be removed for 5.0.0-M1
