### ISSUE TITLE
dotnet workspace can't create donet/c# project

### ISSUE THREAD

**Issue by chendongping** [eclipse-che/che#2374]
I create a dotnet workspace, then I create a project,but there is no donet/c# project to select in popped guide. there are only java/c++/python project.

the rails workspace can't create ruby project also.

**Che version:**    [4.6]  
**OS and version:** [ubuntu 14.04]  
**Docker version:** [1.12]  
**Che install:**    [Docker container]

**Comment by ddementieva** [comment]
@chendongping Are you looking for the C# and Ruby project types in the Wizard? 

There is no C# and Ruby project types right now. You can build a custom plugin to add them to Wizard. It may look something like https://github.com/eclipse/che/tree/master/plugins/plugin-cpp

Find more details on how to build your extension at https://eclipse-che.readme.io/docs/create-and-build-extensions

**Comment by TylerJewell** [comment]
Just following up with one more question.  Is it clear to you on the difference between project types and stacks?  The stack defines the runtime components.  The project type defines how the extensions behave in the runtime and in the ide.  You can have stacks on a technology with or without a project type.  Project type is where users get added intelligence such as automatic dependency downloads.

**Comment by chendongping** [comment]
It's a little difficult for me to understand what I should do to add a extensions.
should I start from a java source code?
In my career, I have used many programing language in real project,such as c/c++,c#,python,ruby,HTML/JS,but I have not used JAVA.

I wish I can learn how to add extensions step by step, firstly I can download a ready-made bin package, I just need to run some commands or edit some config files,then the extensions run. 
After this, maybe I will try to build a extention of my own.

**Comment by ddementieva** [comment]
@chendongping Follow these steps to add your extension to Che:
- Clone Che to your local machine: `git clone https://github.com/eclipse/che.git`
- `cd che`
- Build Che with `mvn clean install` 
- Build your extension.
- Add dependencies to the ~/che/assembly/assembly-ide-war/pom.xml:

```
<dependency>
            <groupId>${your-client-module-groupId}</groupId>
            <artifactId>${your-client-module-artifactid}</artifactId>
            <version>${project.parent.version}</version>
</dependency>
```
- Add GWT module dependency to the ~/che/assembly/assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml:

`<inherits name="${your-gwt-module-fqn}"/>`
- Add dependencies to the ~/che/assembly/assembly-wsagent-war/pom.xml:

```
<dependency>
        <groupId>${your-client-module-groupId}</groupId>
        <artifactId>${your-client-module-artifactid}</artifactId>
        <version>${project.parent.version}</version>
</dependency>
```
- `mvn sortpom:sort` and rebuild Che with `mvn -Denforcer.skip=true clean install` 
- Start Che.

Find more details on how to build your extension itself at https://eclipse-che.readme.io/docs/create-and-build-extensions

**Comment by TylerJewell** [comment]
Close due to being resolved.
