### ISSUE TITLE
Wrong behavior after delete java file from terminal

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2375]
**Reproduction Steps:**
1. Create new workspace with java stack and start it.
2. Create any java project 
3. Open any java file in editor.
4. Go to terminal and delete this file.

**Observed behavior:**
File has been deleted but with error
![delete_file](https://cloud.githubusercontent.com/assets/8051404/18314039/1b62f2e0-751a-11e6-97a2-0ce0e8593b0f.png)

**Che version:**    5.0.0-M1  
**OS and version:**  Ubuntu 14.04 LTS
**Docker version:**  1.11.2
**Che install:**    local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by vparfonov** [comment]
can't reproduce
