### ISSUE TITLE
Download project as Zip does not work

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2377]
**Reproduction Steps:**
1. Try to download as zip for example the Artik project

**Expected behavior:**
Project should be saved as zip on your a file system
**Observed behavior:**
Nothing happens

**Che version:**    [Enter Che version here]  
**OS and version:** [Enter OS name and version here]  
**Docker version:** [Enter your Docker version here `docker version` on CLI]  
**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**
**Che version:**    5.0.0-M1  
**OS and version:**  Ubuntu 14.04 LTS
**Docker version:**  1.12
**Server location:** nightly

**Comment by riuvshin** [comment]
regression
