### ISSUE TITLE
The box 'boxcutter/centos72-docker' could not be found

### ISSUE THREAD

**Issue by Pacoies** [eclipse-che/che#2379]
I am following instructions from https://www.eclipse.org/che/getting-started/download/ to install Eclipse Che using vagrant in OS X El Capitán
1. mkdir che
2. Download Vagrantfile from https://github.com/eclipse/che/blob/master/Vagrantfile to che/
3. cd che/
4. vagrant up

Receive error message: 

> The box 'boxcutter/centos72-docker' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/boxcutter/centos72-docker"]
> Error: The requested URL returned error: 404 Not Found

I have browsed https://atlas.hashicorp.com/boxcutter and I cannot find any other xxxx-docker box to  put in the Vagrantfile.

Any hint? :-)

**Comment by TylerJewell** [comment]
@paco-cruz-iesbelen - grumble.  It does seem that this particular docker image has been removed.  We'll need to revamp the Dockerfile to use a base image and we'll do a fresh install of Docker into it.

If you don't mind me asking - is there value in the Vagrant image for Che?  Given that we have the Che launcher which launches it as a docker container, isn't that approach even simpler? Would it make sense for us to consider phasing out the Vagrantfile approach and only supporting the Docker container approach?

**Comment by humb1t** [comment]
@paco-cruz-iesbelen catch it   config.vm.box = "andrewhk/centos72-docker"

**Comment by Pacoies** [comment]
@TylerJewell the value for me is _simple_ human laziness :-) 

I happen to have vagrant already installed, someone passed me a link and I tried the easiest route, that's all.  

Nevertheless, the image from @humb1t is up and running OK.

**Comment by Pacoies** [comment]
@humb1t the image is up and running OK. Thanks a lot! :-)

**Comment by Pacoies** [comment]
I was thinking that perhaps it would be appropriate to either edit the page at https://www.eclipse.org/che/getting-started/download/ and remove the reference to vagrant, or to update http://github.com/eclipse/che/blob/master/Vagrantfile with a correct image to avoid others getting the same error I had.

**Comment by TylerJewell** [comment]
The issue needs to remain open as other users will encounter the problem.  We are tempted to remove Vagrant installation entirely - and only support Docker installation approach.  It's cleaner and faster.

**Comment by TylerJewell** [comment]
PR to fix: https://github.com/eclipse/che/pull/2388.  Also requires 4.7.1 which has a critical bug fix about running Che in a container while inside of a VM.  4.7.1 release will happen within the next 24 hours.

**Comment by TylerJewell** [comment]
Fixed and merged - 4.7.2 was released this morning.
