### ISSUE TITLE
using che with nginx-proxy 

### ISSUE THREAD

**Issue by asthomasdk** [eclipse-che/che#238]
Has anyone tried setting up Che with an nginx-proxy container in front? 

As part of our standard setup, we have nginx-proxy running and then generate custom URLs on the fly when we build new containers. 

If anyone has any pointers for this, I'd be keen to see them. 

Thanks 

/Thomas

**Comment by dklesev** [comment]
There is the same question on stackoverflow https://stackoverflow.com/questions/35057344/how-to-run-eclipse-che-behind-nginx-reverse-proxy, but it seems that there could be a problem with websockets. If I find time I try to investigate the issue.

**Comment by TylerJewell** [comment]
We are documenting the complete set of protocols and ports that need to be opened on this page. We would like for this to be the guide on what should be configured within a router or a VM hosting system to enable remote access to Che. I am not personally familiar with configuring nginx, but this would be the set of areas that I'd walk through for testing.

https://eclipse-che.readme.io/docs/networking

**Comment by TylerJewell** [comment]
We will use https://github.com/eclipse/che/issues/1560 as a tracking issue.
