### ISSUE TITLE
Commands in the output console are duplicated.

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2382]
**Reproduction Steps:**
-  Create new custom command in the command widget like echo 'Hello world'  and run it. 

**Expected behavior:**

The command should be appears just once

**Observed behavior:**
The command is duplicated

**Che version:**    5.0.0-M1  
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.12
**Che install:**   nightly server.

**Comment by artaleks9** [comment]
The bug is still actual for nightly server.
