### ISSUE TITLE
Help needed to make custom che.properties work on boot2docker-hyperV in windows 10

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#2384]
OS : windows 10 build 10240
Docker version : boot2docker v1.12.1
Virtual machine : Hyper-V

i'm not possible to using CLI **"CHE_CONF_FOLDER"** to make custom **che.properties** work on hyper-v, anyone here have any ideal? guide me or teach me pls

issue : after **"set CHE_CONF_FOLDER=/c/Users/thomas/cong"**, when i check with **"docker-machine ssh che"** the folder inside **"cong"** are empty without the **"che.properties"** file

**Comment by TylerJewell** [comment]
I don't have any experience with hyperv mounting with boot2docker.  Have you done any research on which folders are acceptable for mounting?  It could change.  When you ssh into the VM, are there any root folders available in the VM that you can see?

**Comment by thyeun** [comment]
@TylerJewell, the root folder that you mean, it is call "share folder" from VBox? 

i think all folder can be mounted on hyper-V (after 8 hours of google-ing around), i found out that when i

set CHE_CONF_FOLDER=/c/Users/thomas/cong, the file che.properties are not copy/created inside the folder that i want to set as custom folder.

And it is different from CHE_DATA_FOLDER, data folder look like it copy the json file into the folder that i want to be set, but it is not the case for CHE_CONF_FOLDER. 

very confusing but i have fun of it...hahaha

**Comment by ghost** [comment]
@thyeun when you ssh into a machine, do you see /c/users directory when you run `ls` in the root?

**Comment by thyeun** [comment]
@eivantsov good day, yes, i can see the folder but not the files!!! (not the file che.properties).

**Comment by thyeun** [comment]
@eivantsov yes i can see it, and i try all the folder, only spacing folder are not possible ("thyeun-che" folder possible too)

**Comment by TylerJewell** [comment]
can you "touch file" and does it generate in the host system?  Can you screen shot the directory names and make sure case sensitivity is just right?

**Comment by thyeun** [comment]
@TylerJewell and @eivantsov below picture show the result

![ss15](https://cloud.githubusercontent.com/assets/1939446/18354985/405f9a8e-761a-11e6-8998-866327c40f15.JPG)

**no matter big "C" or small "c", it can see the folder inside ssh VM.**

**Comment by TylerJewell** [comment]
This seems similar to your issue.
https://github.com/docker/docker/issues/22981

**Comment by thyeun** [comment]
@TylerJewell, i try this but hanging there almost 2 hours

![ss16](https://cloud.githubusercontent.com/assets/1939446/18362095/0e6ea886-7637-11e6-8fe8-cfa3a8e583d6.JPG)

**Comment by TylerJewell** [comment]
That means it worked.  It doesn't return - it stays active during the mount period.  Now you can see the files in other tools and consoles.

**Comment by thyeun** [comment]
@TylerJewell not working, only mounted the folder, but inside the folder still empty without any files.

**Comment by TylerJewell** [comment]
This mount capability only works if you are able to mount folders into your hyperv VM.  You haven't solved the first issue that you cited.  Look on the docker forums - this is not a Che issue.  You are having an issue with Docker & Hyperv.  docker/docker#22981

**Comment by thyeun** [comment]
still can't make the share folder working, but i'm using the "touch" to create the file and save the content by "vi editor", to make Oauth github working.

**Comment by TylerJewell** [comment]
That should be your ultimate test.  You should be able to ssh into the VM, go to a mounted directory, create a file, edit it - and then see it appear on your host.  If you can do that, then grab the exact folder path that you see within the VM and make sure it's identical to what you are setting with the CHE CLI variables.

**Comment by thyeun** [comment]
that way is possible, i try it in "/mnt/sda1/var/lib/boot2docker/che.properties" is work even after restart docker/hyper-v

**Comment by thyeun** [comment]
@TylerJewell, good day, no luck for me to make the share folder working for current knowledge that i have after try and error.

so, sorry for trouble you, and need you to close this "question", due to that it is not related with che.

**Comment by TylerJewell** [comment]
It seems - according to this particular comment - that this may not be a feature that is allowed with HyperV and VirtualBox yet.  

https://github.com/docker/docker/issues/22981#issuecomment-221637488
