### ISSUE TITLE
Load README.md file in editor whenever new project imported first time.

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2386]
In situations where a user is opening a workspace for the first time, or they have just imported a new project into a workspace, we should load into the editor a README.md file, if it is present in the root of the project that was just imported.  If such a file does not exist, we would not open the editor with any files.

If this is the 2nd time that a user is opening the workspace, we would reload the editor with files that were previously open.  This is unchanged behavior from what we provide today.
- [ ] If IDE open or being loaded and project present for the first time (import or other way to create), then detect if the project has a README.md and load it into the editor.
- [ ] Add a README.md file to the root repository of all of our Che templates.
- [ ] Get from PM the contents of the README.md file. We should provide some basic instructions on what a developer should do with the project in the form of steps.

**Comment by bmicklea** [comment]
I like loading the project's README.md the first time. The only thing that's weird about that is that we're doing it for informational reasons, not editing reasons.  So if possible, it would be great to open it in the editor pane, but as a formatted MD file. Not sure how easy it would be to do that...

I'd also argue that if the repo doesn't have a README.md (which isn't common) then we'd load a Che default README.md (this could point to tutorials and more info). The templates that ship with Che would this README.md. It would be a collection of resources pointing to tutorials, docs and site for further info and not include anything project or project type specific.

I can write the Che template README.md if we go in this direction.

**Comment by TylerJewell** [comment]
+1 to the idea of loading a default Che README.md if a project doesn't have a .md file.

**Comment by vparfonov** [comment]
Where we will locate default Che README.md?

**Comment by TylerJewell** [comment]
Let's put it in the assembly's /conf directory.  Call it default_project_readme.md. This is the directory that gets created in the root of the assembly when we build it.  It's where we place the default che.properties into an assembly as well.

**Comment by vparfonov** [comment]
You mean it must be configurable in runtime? I ask because we can't load any file from file system it must be under our Project API. So i propose inject default_project_readme.md to the client side code. Or we need to develop special service for reading this file.

**Comment by vparfonov** [comment]
Or we can copy this file to each project to the  hidden dir .che if it don't has own README.md

**Comment by TylerJewell** [comment]
I like the last suggestion.  Just always copy it into .che Dir of project when project created.  Though shouldn't the original start from /conf ?

**Comment by vparfonov** [comment]
ok thx
