### ISSUE TITLE
Che force closes

### ISSUE THREAD

**Issue by balloman** [eclipse-che/che#239]
I can't seem to run it, because every time I start the server it loads for around 3 seconds and then closes.

**Comment by TylerJewell** [comment]
We need diagnostic deals.  Os, Java configuration, any outputs.  The more details you can provide the better.

**Comment by balloman** [comment]
Windows 10
Java 8
Can't get any outputs because can't read the screen in 2 seconds

**Comment by TylerJewell** [comment]
Is there anything if you do --debug when running?  What about trying --image?

**Comment by garagatyi** [comment]
Which Java you are using, Oracle or OpenJDK?

**Comment by ghost** [comment]
Can you also copy and share logs for us to find some clues where the script fails?

**Comment by balloman** [comment]
@garagatyi I'm using Oracle, and @TylerJewell  running the shortcut to start the server. 
@eivantsov how do i copy and share logs

**Comment by TylerJewell** [comment]
@balloman Please run che on the command line, following the Usage instructions in the docs.  Go into the directory where Che was installed and use the che scripts to see the output.

If you installed Che on windows with a directory that has a space in it, there is a known issue, solved by this pull request which has not been merged yet.  https://github.com/codenvy/che/pull/241

**Comment by ghost** [comment]
241 has been merged.

**Comment by TylerJewell** [comment]
I believe the pull request #241 solves this issue.  Closing.  Reopen if issue reappears.

**Comment by balloman** [comment]
Well, I got an error that says`Running docker succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon`
@TylerJewell

**Comment by TylerJewell** [comment]
This is a different kind of issue.  Can you talk about how you started Che and the os you are on?   We may have a pull request to address this issue.

**Comment by balloman** [comment]
I used powershell because when i used the docs, git bash gave me a no directory error, and i got no command from cmd. I am on windows 10

**Comment by TylerJewell** [comment]
I have never seen a no directory error from git bash.
1. What directory is Che installed into?
2. Can you provide the command you ran and the output please?

**Comment by balloman** [comment]
![2016-02-04 1](https://cloud.githubusercontent.com/assets/11762027/12837717/cb899e42-cb8a-11e5-99be-9ead866678d1.png)

**Comment by TylerJewell** [comment]
Ahhh, simple fix.

If you want to run Che in bash you have to use bash syntax :)
bin/che.sh run (bash doesn't auto recognize the file extension the way windows batch recognizes a .bat file).

**Comment by balloman** [comment]
I still get the same error

**Comment by TylerJewell** [comment]
Are there files in the /bin directory?

**Comment by balloman** [comment]
Yes

**Comment by TylerJewell** [comment]
Another approach would be to type "bash --login -i <path-to-che.sh>".  You need to provide the full path to che.sh.  If you still get no such file or directory, I'd need to see your console in a live screen share to understand better.

**Comment by balloman** [comment]
Yes, but I don't think this is the problem

**Comment by balloman** [comment]
It does this in PowerShell too

**Comment by TylerJewell** [comment]
Well, @balloman you'll need to provide very specific steps to try and recreate this issue, or invite one of our engineers into a screen share.  You will have to document each step you take.  But generally if the shell is saying no file found, then the command line parameter is not being entered properly.

**Comment by balloman** [comment]
Ok, I open power shell, I CD to the Che directory, and I run the bin/Che run command, it runs but I get the running docker succeeded but docker ps failed error

**Comment by TylerJewell** [comment]
The details are not enough to reproduce.  Can you provide the output of the console and /or a screencast of the execution.

**Comment by balloman** [comment]
Sorry for the long time to reply @TylerJewell 

[Che Screencast](https://vid.me/K6fT)

**Comment by ghost** [comment]
Can you try removing your default machine and give it another shot? It looks like Docker deamon isn't running in a VM (you may run `docker-machine ssh default` and run `docker ps` there) or you cannot invoke Docker commands from your powershell which means a corrupted connection to a VM or something.

I think default machine removal should help.

Also, I can see that your laptop is running on battery. Do you have a power-saving mode on when unplugged? Some users have noticed that power-saving mode makes Virtual Box very slow if not unresponsive. You may want to take a look at this issue https://github.com/codenvy/che/issues/253

**Comment by balloman** [comment]
@eivantsov I have my laptop on high performance at all times.
This happened after i removed the VM with virtualbox 
![2016-02-07 2](https://cloud.githubusercontent.com/assets/11762027/12875186/57c230ec-cdaa-11e5-9fd3-0e538611a699.png)
![2016-02-07 3](https://cloud.githubusercontent.com/assets/11762027/12875187/57c29b54-cdaa-11e5-965b-a460e0261c4f.png)
![2016-02-07](https://cloud.githubusercontent.com/assets/11762027/12875188/57c5cf18-cdaa-11e5-8502-1b561c26ef4b.png)
![2016-02-07 1](https://cloud.githubusercontent.com/assets/11762027/12875185/57c1f172-cdaa-11e5-9203-8aa4e28464ad.png)

**Comment by TylerJewell** [comment]
That particular exception means that you have something else running on your system that is already bound to localhost:8080.  This link gives some ideas on how to figure out what else is running.

http://stackoverflow.com/questions/12737293/how-do-i-resolve-the-java-net-bindexception-address-already-in-use-jvm-bind

**Comment by balloman** [comment]
Well, I used your suggestion, stopped the program, ran the commands again in powershell, and it works!

**Comment by balloman** [comment]
![2016-02-07 4](https://cloud.githubusercontent.com/assets/11762027/12875394/ec351376-cdae-11e5-8875-5a71bd330392.png)

**Comment by TylerJewell** [comment]
Woot!  Great job in diagnosing and figuring it out.
