### ISSUE TITLE
Project explorer scrolling is slow on Safari

### ISSUE THREAD

**Issue by xcoulon** [eclipse-che/che#2394]
[Short description of problem here]

**Reproduction Steps:**
1. [First Step]
   Using Safari (9.1.2 in my case), open a workspace with a large codebase (e.g.: Che)
2. [Second Step]
   Expand a few nodes in the project explorer view and start scrolling vertically

**Expected behavior:**
Scrolling should be fast and smooth

**Observed behavior:**
Scrolling is very slow. Note that this does not happen on other views (editors) nor on the Project Explorer view on Chrome 

**Che version:**    4.7.0
**OS and version:** MacOS 10.11.6
**Docker version:** 1.12.1
**Che install:**    Docker

**Comment by TylerJewell** [comment]
@xcoulon - if you have an animated gif, could you attach it to the issue, please?

**Comment by slemeur** [comment]
Cannot reproduce this on my side.
@xcoulon : If you are still having the issue, please reopen it.
