### ISSUE TITLE
Wrong behavior when renaming java class

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2398]
**Reproduction Steps:**
![refactor](https://cloud.githubusercontent.com/assets/8051404/18386676/1c7e5510-76a1-11e6-8cd1-110f0e972f91.gif)

**Observed behavior:**
  `500 Internal Server Error`
`http://localhost:32801/wsagent/ext/java/refactoring/rename/create`
`java.lang.NullPointerException`

Che version: 5.0.0-M1
OS and version: Ubuntu 14.04 LTS
Docker version: 1.11.2
Che install: local

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: Yes
But if you rename another java class and try to rename again this problem is not reproduced.

**Comment by riuvshin** [comment]
regression?

**Comment by AndreyChizhikov** [comment]
No

**Comment by musienko-maxim** [comment]
Not actual
