### ISSUE TITLE
GitLab docs update

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2405]
The addition of GitLab support will require changes to our docs:
- [x] Add GitLab oAuth as a section on this page #2404
- [x] Move content from oAuth sections on Config page to the Version Control page
- [x] In the oAuth sections on the Config page point the reader to the new sections in the Version Control page
- [x] Make the language for [Git using SSH](https://eclipse-che.readme.io/docs/git#git-using-ssh) section generic to any git provider
- [x] Provide examples with GitHub and GitLab within the [Git using SSH](https://eclipse-che.readme.io/docs/git#git-using-ssh) section

**Comment by bmicklea** [comment]
@JamesDrummond please work through these tasks and comment when each is complete so I can check them off.

**Comment by JamesDrummond** [comment]
@bmicklea All done.

**Comment by bmicklea** [comment]
Reviewed - thanks @JamesDrummond
