### ISSUE TITLE
CLI artik-ide

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2406]
I am currently using che and artik-ide CLI with profiles. artik-ide CLI currently uses ~/.che/ to store profile information which is also used by che CLI. Can we change this to ~/.artik/ so that there are not conflicts. I currently cannot set separate default profiles for each one.

**Comment by bmicklea** [comment]
This is probably a lower priority issue since very few engineers outside Codenvy are using ARTIK and Che simultaneously...but as one of those people I'd like it ;)

**Comment by TylerJewell** [comment]
Added enhancement request with this property.  If merged, then can be copied over to ARTIK CLI. https://github.com/eclipse/che/pull/2410

**Comment by JamesDrummond** [comment]
Profiles no longer used with dockerized version.
