### ISSUE TITLE
GitLab oAuth blocked by GitLab bug

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2409]
Currently it's not possible for Eclipse Che to use oAuth integration with GitLab. Although GitLab supports oAuth for clone operations, pushes are not supported. We are tracking [this GitLab issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/18106) for updates.

**Comment by bmicklea** [comment]
When GitLab issues is resolved and we add GitLab oAuth the following docs pages will need updating:
- https://eclipse-che.readme.io/v4.7/docs/configuration#section-gitlab-oauth
- https://eclipse-che.readme.io/docs/git#section-gitlab-oauth

**Comment by skabashnyuk** [comment]
I think at this moment Keycloak can be integrated with Gitlab oAuth
