### ISSUE TITLE
Show/Hide Hidden Files feature works wrong

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2415]
**Reproduction Steps:**
- Create a workspace. Create a maven project from samples. Apply  Show/Hide Hidden Files (Project -> Show/Hide Hidden Files).  After refreshing a browser the feature may work.

**Expected behavior:**
In the project tree should appear/disappear the hidden files
![anim](https://cloud.githubusercontent.com/assets/1640058/18431288/ecc6823e-78e4-11e6-8511-ed57fa4727f4.gif)

**Observed behavior:**
Nothing happens

Che version: 5.0.0-M1
OS and version: Ubuntu 14.04 LTS
Docker version: 1.12
Che install: nightly server

**Comment by AndreyChizhikov** [comment]
Cannot reproduce
