### ISSUE TITLE
Fix project creation page issues on dashboard

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2416]
- [ ] The animations should be removed.  The side-to-side loading as you select different tabs.  It's not adding any value.  So we should remove any animation here.
- [ ] GitHub is misspelled (missing capital H)
- [ ] GitHub section has to be left-justified
- [ ] Broken link on dashboard page to custom stacks documentation #2440

**Comment by bmicklea** [comment]
Edited the issue description to replace the outline of point 4 with a link to this issue: https://github.com/eclipse/che/issues/2440
