### ISSUE TITLE
Double printing in outputs using echo command

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2417]
When doing an echo in the console, the output is printed two times.

**Reproduction Steps:**
1. Go into the "Edit Commands" 
2. Create a new "custom command", it has the instructions to do an "Hello". 
3. Run this command

**Expected behavior:**

The message is printed one time in the outputs panel.

**Observed behavior:**

The message is printed two times in the console.
Adding an "sleep 0.2s &&" before the commande seems to solve the issue. Sounds as a race condition problem.

See the attached recording:
![bug-double-output](https://cloud.githubusercontent.com/assets/1636769/18435013/eeb887f2-78f0-11e6-92dd-057844682f16.gif)

**Che version:**    4.7.2
**Che install:**   cli, Bitnami, Codenvy   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by musienko-maxim** [comment]
For 5.6.0 is not actual
