### ISSUE TITLE
Add scrollbars to terminal

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2423]
Scroll bars are missing from terminal.

**Reproduction Steps:**
1. Open the IDE on beta.codenvy.com or in Che 4.7.2
2. Run a set of commands in the terminal so that you have >1 screen of info

**Expected behavior:**
There should be a scroll bar on the right

**Observed behavior:**
There is no scroll bar.

**Che version:**   4.7.2
**Che install:**  beta.codenvy.com

**Additional information:**
The console output during machine startup does have a scrollbar as does the panel for SSH.
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by bmicklea** [comment]
This is a regression.

**Comment by vitaliy-guliy** [comment]
I could'n say this is a regression. I have never seen scrollbars in the terminal before.

**Comment by vitaliy-guliy** [comment]
We use https://github.com/chjj/term.js at the client and there is no option to configure visibility of scrollbars.

**Comment by bmicklea** [comment]
Closing issue because adding scrollbars isn't possible with the JS library we use.

**Comment by bmicklea** [comment]
Reopening - we've had a few customers ask about this. @vparfonov I think you said that there should be a solution, please consult with the team.

(re-labeling as analyzing)

**Comment by vitaliy-guliy** [comment]
There is another one #3529 to update terminal.
