### ISSUE TITLE
Project import is not tracked on multiple browsers

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2428]
Precondition: we should use 1 common workspace for browser #1 and browser #2 (browsers should be authorized in the workspace)
**Reproduction Steps:**
1. In the browser #1  import a project from github for example.

**Expected behavior:**
In the browser #2 should appear notification about just added project. In the project explorer tree should appear the project.

**Observed behavior:**
In the browser #2 the notifications and new items do not appear

Che version: 5.0.0-M1
OS and version: Ubuntu 14.04 LTS
Docker version: 1.12
Che install: nightly server

**Comment by ghost** [comment]
A very old scenario. Cannot be reproduced.

**Comment by musienko-maxim** [comment]
Still actual for 5.15.0 version this events are not tracked, the scenario is reproduced
