### ISSUE TITLE
Code validation features are not available after editing a java/maven projects from not by IDE

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2429]
Precondition: we should use 1 common workspace for browser and ssh console. In the workspace should be created the Spring project.

**Reproduction Steps:**
1. Open a project in a browser. Open the GreetingController class. Connect into the workspace with ssh. We can use midnight commander.
2. Rename the package with class by MC. 

**Expected behavior:**
After renaming package the class should be valid .

**Observed behavior:**
In the class the error markers are absent. The code is not validated

Che version: 5.0.0-M1
OS and version: Ubuntu 14.04 LTS
Docker version: 1.12
Che install: nightly server

**Comment by slemeur** [comment]
Cannot reproduce.
