### ISSUE TITLE
Projects are not removed after deleting a workspace

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2435]
**Reproduction Steps:**
- Create a workspace, open in the IDE and create a project (e.g.'web-spring').
-  Go to dashboard and delete the workspace.
- Create the workspace with same name and open it In the IDE. 

**Expected behavior:**
in the project explorer should not be any project

**Observed behavior:**
there is the project as no configured.

**Che version:**   5.0.0  
**OS and version:** Ubuntu 14.04  
**Docker version:** 1.11.1  
**Che install:**   local bundle  

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- On the hosted che we have the same behavior (the projects are not deleted after delete workspace).
  ![project_after_delete_ws](https://cloud.githubusercontent.com/assets/5408906/18470994/0df088dc-79b8-11e6-81f2-46d23b84e9d2.png)

**Comment by bmicklea** [comment]
@vkuznyetsov can you get a code review completed for this so we can have it merged into M5

**Comment by riuvshin** [comment]
this issue in  progress again after reviews.
