### ISSUE TITLE
Formatting the whole document makes a big mess

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#2437]
Formatting a JSON document of average size makes a big mess. See the animated gif. 

I have a local build of Che with the latest content from the `language-server` branch.

I see similar result with PHP files using a PHP language server. So, it seems to be a generic formatting issue when using language servers, i.e. related to how #1788 is implemented.

![formatting-mess](https://cloud.githubusercontent.com/assets/468091/18473814/99734d72-79c7-11e6-823b-4e23f8300813.gif)

**Reproduction Steps:**
1. Create a workspace with project from this GitHub repo: https://github.com/kaloyan-raev/AstroSplash.git
2. Open the composer.json file
3. Invoke Edit > Format from the main menu

**Expected behavior:**

The JSON file is nicely formatted.

**Observed behavior:**

The document is completely broken.

**Che version:**    latest content from the `language-server` branch
**OS and version:** Fedora 24
**Docker version:** 1.10.3 
**Che install:**    local build, started with the `bin/che.sh` script

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ddementieva** [comment]
@kaloyan-raev Bug confirmed.

**Comment by kaloyan-raev** [comment]
I did some debugging. The text edits returned by the language server are all calculated based on the document before any modification is applied.

Che applies the edits to the document one by one. If the inserted text has a different length than the replaced text then the ranges of the remaining edits become invalid and they must be shifted appropriately.

I am working on a PR to fix this issue.

**Comment by kaloyan-raev** [comment]
Pushed PR #2719 with the fix.
