### ISSUE TITLE
Stop workspaces before user removal

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2438]
To be able to remove all user workspaces from database we need to stop all his running workspaces.

**Comment by akorneta** [comment]
At current state we decide to reuse logic from `WorkspaceManager` and throw `ConflictException` when the workspace is `running`, we have a common vision of the solution and partial implementation.

**Comment by bmicklea** [comment]
@skabashnyuk is this a must-have for M5?  If not I'll move to M6.
