### ISSUE TITLE
Don't use Docker-in-Docker when running as a Docker Container

### ISSUE THREAD

**Issue by randywallace** [eclipse-che/che#244]
'docker-in-docker' usage is wrought with pain and suffering, and generally not recommended by the docker maintainers.

I've got Che running great _without_ doing this.  Regardless, if you guys _really_ insist on doing it this way, I recommend at the very least updating the Dockerfile to put /var/lib/docker in the container on a volume, otherwise you're beating the storage driver senseless, guaranteeing performance issues, especially when building containers.

Here's the docker compose file I'm running that make Che work without the 'docker-in-docker' implementation:

```
che:
  image: codenvy/che:latest
  #image: codenvy/che:4.0.0-beta-13
  command: >
    bash -c "
    sudo rm -rf /home/user/che/lib-copy/* &&
    sudo rm -rf /home/user/che/workspaces/* &&
    sudo rm -rf /home/user/che/tomcat/temp/local-storage/* &&
    mkdir -p /home/user/che/lib-copy/ &&
    sudo chown -R user:user /home/user/che &&
    cp -rf /home/user/che/lib/* /home/user/che/lib-copy &&
    cd /home/user/che/bin/ && ./che.sh run -d -r:${DOCKER_MACHINE_HOST}
    "
  ports:
    - "8080:8080"
    - "32768-32788:32768-32788"
  volumes:
    - "${HOME}/.che/conf:/home/user/.che"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/user/che/lib:/home/user/che/lib-copy"
    - "/home/user/che/workspaces:/home/user/che/workspaces"
    - "/home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage"
  privileged: true
  container_name: che
  extra_hosts:
    - "vagrant-docker:127.0.0.1"
```

I need the extra_hosts probably b/c I'm using Che via Vagrant, and the vagrant host is vagrant-docker in my os x /etc/hosts... still no idea why i need this, but it works where no other configs do... YMMV

Last thing is the che.properties, which I updated with:

```
machine.docker.che_api.endpoint=http://172.17.0.1:8080/ide/api
```

This allowed the workspace to poll back in... the IP is the docker0 bridge IP.

Note that I am not using host networking, as I find that to be an unnecessary workaround and presents unnecessary fragility.  I haven't found anything that doesn't work.. workspace building, recipes, etc.. all seem to work fine.

**Comment by ghost** [comment]
This is what we have actually tried - moving directories, creating everything on the host system. A couple of things we did not like in this approach:
1. We will actually create /home/user/che directory in the host filesystem. Not good. Sure, better that Docker in Docker.
2. Mounting Docker socket may cause issues when a user in the container won't be actually allowed to trigger Docker on the host.

We are thinking of a solution where container B with the workspaces can use volumes from container A with a Che server and all the resources.

Great job though! I came to the same solution a month ago, although everything was in a Dockerfile and a docker run command (not everyone has Docker compose installed)

And `machine.docker.che_api.endpoint=http://172.17.0.1:8080/ide/api` did not work for me. I had to use --net=host in a compose yml file otherwse ws agent cannot connect to workspace master.

**Comment by garagatyi** [comment]
I think that we can provide a way to communicate with docker API for Che inside container. 
It doesn't require priviledged mode. 
The idea is to inject DOCKER_HOST env variable inside Che container. Then Che will use it to communicate with Docker API. 
It require tcp access to docker. The easiest way is to disable TLS. If TLS is enabled that mounting of certificates also needed.

**Comment by ghost** [comment]
Yes, but the problem is not with trying to get rid of Docker in Docker.. that can be solved in several ways.. the idea is how to make it elegant with mounting.. since ws agent and terminal, as well as workspace storage have to live in the host system.

**Comment by garagatyi** [comment]
We can create shared volume.

**Comment by randywallace** [comment]
@eivantsov I agree, it isn't easy.  I do feel very strongly, though, that docker-in-docker is not the answer, and neither is running Che outside docker on the host.  Docker inside docker is extremely fragile, as can be seen in the myriad issues regarding `Docker not found by 'docker ps'` and whatnot.  There are also storage driver issues that have to be contended with (certain storage drivers / Host OS's do not work well, or at all, with dind), and users more often than not will not be able to easily detect that the container's docker instantiation is the issue, without lots of GH Issues and probably a ton of FAQ/Wiki entries to the effect of debugging docker-in-docker on Che.

I feel that you can expect docker-compose to be available to "most" users, especially people running it on OS X and Windows, b/c it is an official part of the [Docker Toolbox](https://www.docker.com/products/docker-toolbox), which would at the very least make maintaining the docker run commands a bit easier on the eyes... and allows certain facets of the startup commentable for the user to edit (i.e. that dreaded -r flag).  If you expect someone to have docker-machine on OSX/Win, I think its safe to assume that you should also expect docker-compose to be available.

Why can't the workspace dependencies be hosted by the api as well?  `wget http://che-host:8080/ide/api/ws-libs/ws-agent.zip` seems very sensible to me as a means to getting stuff from one end to the other.

Regarding the sharing of workspaces and whatnot as OS Level Filesystems and whatnot between the master and slave... is this really necessary?  What is the master doing that the slave couldn't facilitate on behalf of the master via an api hosted on the workspace?  The workspace _already_ has a running tomcat and terminal that run stuff locally in this manner, is it possible that those could be leveraged for the IDE to perform certain tasks for the Project Explorer, Git, Maven, et. al.?

**Comment by ghost** [comment]
@randywallace yes, Docker in Docker isn't the answer. A Docker type installation is more like an experiment so far.

For the time being, workspace resources get mounted as they get mounted, i.e. from a host file system. Having them available through API, that's an interesting idea.

The compose way is just neater, but the traditional `docker run` will also work.. although the command line will be huge.

Still, I failed to run it this way without net=host  - otherwise workspace agent won't connect to Che master.

**Comment by randywallace** [comment]
oh yeah, I never expected my compose file to work for anyone but me, I have a rather custom setup, to say the least.  the '8080:8080' exposed port is visible on the host, with '172.17.0.1', are what allow, for me, `machine.docker.che_api.endpoint` to work.  the IP is assigned to the `docker0` bridge on my vagrant box.  I suppose the easiest way to find an IP that would work would be checking to see what port the master is listening on (i.e. 8080), and checking if that is listening on the host (i.e. `netstat -lnp` on the host) and verifying that its curl-able _from_ the host.  Then, logging into the workspace while its failing (i.e. `docker exec -it <failing_workspace_container_id> /bin/bash --login`) and trying to hit (curl) that endpoint with various IP/port/w.e. combinations I know are listening on the host until I find something that works.  Then going back and modifying `machine.docker.che_api.endpoint` with what I know to work and restarting the docker container for che so it picks up the updated property.  

That's how I troubleshoot this stuff with docker anyway ;)

Oh what fun it is ;)

**Comment by ghost** [comment]
Did all that stuff. Grabbed Che master IP and pinged it from inside the workspace container. Seems to work, but the ws agent Tomcat cannot connect to it anyway,

I'll try it on another machine.

**Comment by randywallace** [comment]
you should try the docker0 IP endpoint, I usually use it as a workaround when `--icc` (inter-container communication) is disabled on the docker daemon... its enabled by default on Docker 1.9.1.  That being said, from my workspace, I have no problem hitting `curl http://172.17.0.2:8080/ide/api` from the workspace to `172.17.0.2:8080` (the IP Assigned to the Che Master) instead of `172.17.0.1` (the IP Assigned to the docker bridge); they both work.  I would be interested in whether or not you have any special daemon flags turned on in your host.  I imagine if `--iptables`, `--ip-masq`, `--icc`, or `--ip-forward` are set to false by the daemon, things wouldn't work well at all.  On my vagrant host, I'm using a very basic docker server config: 

```
vagrant@localhost:~$ cat /etc/default/docker
DOCKER_OPTS="-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 -s aufs"
```

**Comment by asthomasdk** [comment]
With regard to the mounted directories, is the solution to this not data containers? We use containers built from busybox for data for lots of our containers. Very easy to set up with both docker and compose. 

The only thing to look out for is with docker compose, you can very easily delete the data container if you use "docker-compose rm" as this takes all the containers from the compose file. 

For a scalable and flexible docker based solution, mounting anything except access to docker itself on the host would be something to avoid.

**Comment by asthomasdk** [comment]
I would also be tempted to eliminate this from your command line: 

`sudo rm -rf /home/user/che/lib-copy/* &&
    sudo rm -rf /home/user/che/workspaces/* &&
    sudo rm -rf /home/user/che/tomcat/temp/local-storage/* &&
    mkdir -p /home/user/che/lib-copy/ &&
    sudo chown -R user:user /home/user/che &&
    cp -rf /home/user/che/lib/* /home/user/che/lib-copy &&
`

And instead use a custom Dockerfile build file with 
`FROM codenvy/che`

Or is there a reason you are not doing that?

**Comment by ghost** [comment]
In fact it does not matter where CMD is executed - as a Dockerfile instruction or as a Docker run argument that overrides the default CMD. It works both ways

**Comment by randywallace** [comment]
@asthomasdk I just know that's what works for me, and since its a CMD and not a RUN, a bit faster than waiting for a local build if I make my edits there... not a collaborator trying to reinvent the wheel here ;)

Regarding mounted directories.. a data container is a nice idea, but from an over-arching, is-this-really-where-you-want-to-go perspective, a data container still breaks one very important thing: you can't run on different hosts!  "Scaling" isn't really a possibility, when you consider that even a _moderate_ java dev environment requires at _least_ 2G of Ram.  Just for my che testing, my Vagrant VM needs at least 4G of ram (fortunately I have a Hackintosh with 32GB running all this) to support our build environment (one 3G workspace), which makes trying to run Che in AWS for our devs a very expensive proposition...

All of this may be a moot point, tho; seems like work is in progress on [this idea](https://eclipse-che.readme.io/docs/scaling): 

> (Coming Soon). Your workspace runtimes are Docker containers that do not have to reside on the same machine as the Che server, which is the workspace master.

**Comment by TylerJewell** [comment]
Hi.  We have made a proposed pull request which will launch the Che Docker image without using docker-in-docker. 

Pull Request: #257 

First, this performs a docker pull to get the latest image before creating a container.

Second, the container is run with special volume mounts.

```
docker run -ti --net=host -e "DOCKER_MACHINE_HOST=$ip" -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage codenvy/che
```

Third, when Che server is launched with a docker exec, we then perform some special file movement and management to set up Che to run.

```
sudo rm -rf /home/user/che/lib-copy/* && \
    mkdir -p /home/user/che/lib-copy/ && \
    sudo chown -R user:user /home/user && \
    cp -rf /home/user/che/lib/* /home/user/che/lib-copy && \
    cd /home/user/che/bin/ && ./che.sh run
```

If you are in Windows or Mac with VirtualBox, we need to do the moving of files and creating directories after the volumes have been mounted, as any existing files in those directories could be overwritten.

This has a consequence of making some project management while on Windows and Mac faster. 

NOTE:
If you run the Che docker image on Windows or Mac, your project files will permanently reside within the vbox VM.  As your projects are created, they are stored inside the VM at /home/user/che in storage.  We are not doing anything to cross-mount those project files to be outside of the VM so that they are stored in your %userprofile% directory.  This means that your projects will survive the lifespan of the VM in between runs of Che.  But if you destroy the VM that is used for Docker, then your project files will be lost.

**Comment by TylerJewell** [comment]
Please try the new script that was committed this morning at:
https://github.com/codenvy/che/pull/257

Note that you must get the boot2docker.iso version 1.10 that was released 4 days ago.  This version solves some major instability issues with AUFS that was affecting vbox.  You can get this on your current system by having a docker-machine default running, and then executing `docker-machine upgrade default`.

**Comment by ghost** [comment]
Closing the issue. Updated the image and docs. No Docker in Docker now. Creating resources on the host isn't nice either, maybe we will think of `volumes-from` solution.
