### ISSUE TITLE
Broken link on dashboard page to custom stacks documentation

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2440]
At the bottom of the "Custom Stack" section of the New Workspace definition page in the user dashboard is a link to "Custom stack documentation" which goes to a 404. The correct link should be https://eclipse-che.readme.io/docs/stacks#custom-stacks-for-che

**Reproduction Steps:**
1. Create a new workspace
2. Choose "Select Stack"
3. Choose "Custom Stack"

**Che version:**    4.7.2
**Che install:**   beta.codenvy.com

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Unsure
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ashumilova** [comment]
Resolved
