### ISSUE TITLE
CLI - che start is not selinux aware

### ISSUE THREAD

**Issue by sherl0cks** [eclipse-che/che#2441]
Che server does not start when selinux is enabled

**Reproduction Steps:**
1. Install CLI per [the docs](https://eclipse-che.readme.io/docs/che-cli) (fedora 24 in my case)
2. Ensure selinux is enabled: `setenforce 1`
3. try to start che server: `che start`

**Expected behavior:**
Server start normally

**Observed behavior:**

```
[sherl0cks@localhost jenkins-plugin]$ che start
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
INFO: ECLIPSE CHE: Pulling image codenvy/che-launcher:nightly
Trying to pull repository docker.io/codenvy/che-launcher ... 
nightly: Pulling from docker.io/codenvy/che-launcher
e110a4a17941: Already exists 
495e4dd69a48: Pull complete 
2df88a24dd1e: Pull complete 
fffbdf549d12: Pull complete 
354f00265cef: Pull complete 
9ddaff61b027: Pull complete 
Digest: sha256:53efd10b3976d4dd01aaf3be6e52b4ff476b8cc05111a035ac6cea98996b63e0
Status: Downloaded newer image for docker.io/codenvy/che-launcher:nightly

time="2016-09-13T18:52:25Z" level=fatal msg="Get http:///var/run/docker.sock/v1.18/containers/json: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?" 
```

**Che version:**    the most useful thing I can get from the cli is `DEBUG: CHE_VERSION= latest`, please let me know how to give more descriptive info
**OS and version:** fedora 24
**Docker version:**  1.10.3
**Che install:**    cli per [the docs](https://eclipse-che.readme.io/docs/che-cli)

**Additional information:**
The issue is cause by [this line of code](https://github.com/eclipse/che/blob/master/che.sh#L199) in the shell. The cli is trying to mount the docker.sock but is not using the `:Z` syntax required to do this properly in an selinux environment. There should be some smarts in the CLI to detect if it is running in an selinux environment and the run the appropriate command if so. More info on selinux docker mounts [here](http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)

FYI @bmicklea @TylerJewell
- Problem started happening recently, didn't happen in an older version of Che: Not sure
- Problem can be reliably reproduced, doesn't happen randomly: 100% reproducibility

**Comment by benoitf** [comment]
I suppose we should use Z flags on every mount like on agent, terminal,etc

**Comment by TylerJewell** [comment]
If we add those flags to all mounts are their any downsides for systems that don't need them?

**Comment by sherl0cks** [comment]
The selinux flags were added to docker 1.7, so that feature should be available on all distros. I just ran a quick test by spinning up an [ubuntu vagrant image](https://atlas.hashicorp.com/rboyer/boxes/ubuntu-trusty64-libvirt). Executing both commands below, the che server came up and was responsive. I suspect that the additional metadata docker is adding with `:Z` isn't used in the case where selinux is not present, but I'm not an expert on the subject. 
- `sudo docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock:z eclipse/che start`
- `sudo docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock:Z eclipse/che start`

The other option could be to test for selinux's presence by running something like `sestatus` and then checking exit code.

**Comment by TylerJewell** [comment]
I think the challenge with that approach is that we are not passing along the flag to volume mounts internally.  The eclipse/Che container is just a process for launching another container with a different set of mounts.  Most of these mounts point back to the docker host.

So it seems that in the cli we need to detect if the customer has provided the :z in the initial mount OR check for setstatus and if either is true pass along the appropriate flags.  Internally the Che launcher needs a similar check I think.

**Comment by benoitf** [comment]
for che agent or terminal we don't do any detection, always add Z flag so maybe we don't need to detect it
and add it as part of che.sh script and subcalls

**Comment by garagatyi** [comment]
We had the same problem with terminal and ws-agent. @eivantsov added **:Z** flag and checked that everything was working on systems with _enabled/disabled/without support_ of selinux.
So I believe it is completely safe to add this flag to all mount without checking whether selinux enabled or not

**Comment by benoitf** [comment]
@sherl0cks 
did you have installed https://github.com/dpw/selinux-dockersock ? (because even if we add Z flag you'll still need require this kind of extension)

**Comment by sherl0cks** [comment]
@benoitf it does not appear so. I do have `docker` semodule installed tho, just not dockersock.

```
[sherl0cks@localhost rhc]$ sudo semodule -l | grep dockersock | wc -l
0
```

Reading through the semodule, I think it's a workaround that is not needed. Just using the :z/:Z flag works for mounting the docker sock...

**Comment by ghost** [comment]
@sherl0cks any particular reason you start docker with sudo? Can you add your user to docker group?

**Comment by benoitf** [comment]
@sherl0cks without this semodule here what I have on fedora 24:
![withoutdockernode](https://cloud.githubusercontent.com/assets/436777/18543506/86b31b3a-7b30-11e6-8bf4-f5785c386327.gif)
the docker.sock is mounted with Z flag, but I still get error when using it

and with semodule
![withdockernode](https://cloud.githubusercontent.com/assets/436777/18543595/dd70c864-7b30-11e6-8c1e-cfc1d85d8e0f.gif)
docker.sock is mounted and I can use it

are you able then to use "docker ps" with a docker.sock without using this module ?

**Comment by TylerJewell** [comment]
Some fixes for this were added into the master for M2 milestone.  Going to close this as I believe the improvements should resolve all the issues.
