### ISSUE TITLE
Move 'Git' and 'Subversion' menus to the left

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2447]
At this moment, we have 'Git' and 'Subversion' menu that are on the right of 'Profile'.

<img width="1008" alt="screen shot 2016-09-14 at 15 22 31" src="https://cloud.githubusercontent.com/assets/1636769/18513818/4ab7a782-7a8f-11e6-9c77-2834deefbea0.png">

We should have the following order:
- 'Git' / 'Subversion' / 'Profile' / 'Help'
  instead of:
- 'Profile'/ 'Git' / 'Subversion' / 'Help'

**Comment by vitaliy-guliy** [comment]
Spent 1h
