### ISSUE TITLE
Having to go through a series of steps before Eclipse Che starts.

### ISSUE THREAD

**Issue by RahulMukherji** [eclipse-che/che#2449]
I am running Eclipse Che on Windows 10 64 bit. I am running it on cmd. I am able to get it working, however I have to go through a series of steps. 

**Reproduction Steps:**
1. I have installed all necessary components (Java 1.8, Maven 3.3.9)
2. I installed the Docker Toolbox (Docker 1.12, Git)
3. I downloaded the Eclipse Che zip archive and extracted it to C:\Users\Rahul\eclipse-che
4. I have set my JAVA_HOME to the location of my JDK (C:\Program Files\Java\jdk1.8.0_102), M2_HOME and MAVEN_HOME to my Maven install folder (C:\Program Files\Apache\Maven). I have added Git Bash and Maven to my path. Both work fine. I created a folder in the eclipse-che directory called cli, and downloaded the Eclipse Che CLI (che.sh and che.bat) to this folder, and then added it to my path.

**Expected behavior:**

I want to run `che start` and have the Che Server start without any hassle. Same goes for all other commands. 

**Observed behavior:**

When I run `che start`, I get the following error:

`An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json: open //./pipe/docker_engine: The system cannot find the file specified.`

I am able to resolve this by running `docker-machine start default` which starts the container, followed by `docker-machine env default`, which prints out the instructions and commands for setting up the environment:

```
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\RMukh\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env default') DO @%i
```

After I copy-paste these commands into the prompt, I rerun the `che start` command, and everything works fine. If I close and reopen cmd, I have to rerun the commands in `docker-machine env default`. If I reboot the machine, I have to run the `docker-machine start default` command and then run the commands in `docker-machine env default`. Is there any way I can remove these unnecessary steps such that simply running `che start` starts Eclipse Che?

**Che version: 4.7.2** 
**OS and version: Windows 10 64-bit**  
**Docker version: 1.12.0**
**Che install: Docker Container**

**Comment by thyeun** [comment]
@RahulMukherji good day, for the moment there are yet any shortcut for windows 10 64bit if you using boot2docker, but for "docker for windows" the answer will be yes, at least you wont need to repeat the "docker-machine env" 

for boot2docker, and if you on cmd, you still can make a batch file to execute all the command from "docker-machine env".

**Comment by TylerJewell** [comment]
Thanks @thyeun!  He is correct.

We require Docker to be running before you start Che.  We do a basic check for it but we do not take any steps to launch docker machine if you haven't started it already.

So if you activate your boot2docker, verify you can do a docker hello world and then Che will work.  I am going to close this issue but continue to ask questions if you need to.

**Comment by RahulMukherji** [comment]
Thanks @thyeun!

I managed to solve this problem by adding the `docker-machine start default` command and the commands in `docker-machine env default` to the che.bat script.
