### ISSUE TITLE
MVN Clean Install Fails on windows 8.1

### ISSUE THREAD

**Issue by ddc22** [eclipse-che/che#245]
The build fails when trying to do an mvn clean install... everything else seems to be fine... I have included screenshots of the error log!
<img width="723" alt="1" src="https://cloud.githubusercontent.com/assets/3422709/12694508/7b24c5ae-c756-11e5-85b8-e4a210bd37a1.PNG">
<img width="707" alt="2" src="https://cloud.githubusercontent.com/assets/3422709/12694507/7b243170-c756-11e5-8f45-1d236aca181c.PNG">
<img width="719" alt="3" src="https://cloud.githubusercontent.com/assets/3422709/12694506/7b2362ae-c756-11e5-949f-c6e2c71508c4.PNG">
<img width="733" alt="4" src="https://cloud.githubusercontent.com/assets/3422709/12694509/7b25961e-c756-11e5-8b55-f09ac1608e27.PNG">

**Comment by ghost** [comment]
What is your Java and Maven version? Can you please run `java -version` and `mvn --verison`?

Did you `git clone` the repository? Can you try it with `git pull` and `mvn clean install -U`?

**Comment by ddc22** [comment]
What do you mean to try it with git pull?... I cloned the repo today... and git pulled but well everything is up to date
These are the other parameters!
<img width="447" alt="jmvn" src="https://cloud.githubusercontent.com/assets/3422709/12694781/3750a61a-c75e-11e5-9710-900fa4e78327.PNG">

**Comment by ghost** [comment]
I have just built it ok on win 8.1 with a clean maven repo and freshly installed Java.

I can see that your Java_HOME is in Che directory. Maybe this is the reason.

You may need to resinstall Java to a default location (Program Files usually) and set JAVA_HOME to point to that location.

**Comment by TylerJewell** [comment]
Please set your JAVA_HOME variable to the root directory where your JDK is installed.  This is the issue.  Please let us know if this resolves the issue.

**Comment by TylerJewell** [comment]
@jdc91 Any update - it's possible that the update repository was mid-cycle. If you clone the repository again with latest changes and build, do you still get same error?

**Comment by ddc22** [comment]
Hi guys sorry for the late reply... My PC broke... Now working on a mac... Will try building this on the mac :)... Really interested in contributing to the CHE project :)... Will start off by building it!

**Comment by TylerJewell** [comment]
Great.  Looking forward to this being successful.

**Comment by ghost** [comment]
@jdc91 Can you reproduce the issue with the current master?

**Comment by ghost** [comment]
Cannot reproduce with current master. assembly module builds ok both on Windows 8 and 10. Closing the issue. @jdc91 feel free to reopen if the problem is still there.
