### ISSUE TITLE
Workspace environment page enhancement

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2451]
During demo the following list of bugs were discovered, that should be fixed for environment page:
- [ ] Remove animation from tabs transition
- [x] Rename "Environments" -> "Runtime" for now
- [x] Change message to "Workspace updated" in notification
- [x] Move recipe section to the bottom and add description "Injects terminal, SSH and IDE tooling."
- [x] Align the Ram label and widget
- [x] Add label in source section to define the origin type (Ex "image: codenvy/ubuntu_jdk8", "dockerfile: url")
- [x] Rename "Dev" label to be more expressive what it means for end user
- [x] Rename "Ports" -> "Exposed Ports"
- [x] Fix recipe updation on changes in UI
- [x] Disable Delete button for dev machine
- [x] Enhance the dev machine switching (disable switcher for dev machine; when making machine as dev - automatically make current dev machine as not dev)
- [x] Expand/Collapse on a machine must be working on all the machine's header (not only the small '>' icon)

**Comment by TylerJewell** [comment]
Let's change "Environment" to be "Runtime".

**Comment by slemeur** [comment]
@TylerJewell yes, it was already updated in the issue description.

**Comment by slemeur** [comment]
For: 
`Rename "Dev" label to be more expressive what it means for end user`
I propose "Dev Services"

**Comment by TylerJewell** [comment]
@slemeur - I think the fix wasn't to the label, it was to the description text that appears at the right of the toggle button.  It needs to describe what we do as opoosed to saying "inject dev services."

**Comment by akurinnoy** [comment]
@TylerJewell 

> Add label in source section to define the origin type (Ex "image: codenvy/ubuntu_jdk8", "dockerfile: url")

![screenshot-localhost 3000 2016-09-15 19-24-53](https://cloud.githubusercontent.com/assets/16220722/18558054/31327d82-7b7a-11e6-977f-60b41299502a.png)
![screenshot-localhost 3000 2016-09-15 19-24-29](https://cloud.githubusercontent.com/assets/16220722/18558058/349153e0-7b7a-11e6-8e80-0260d26708c1.png)

WDYT?

**Comment by TylerJewell** [comment]
+1 - very slick.
