### ISSUE TITLE
Configuring of named variable with underscore in name doesn't work if it was set using environment variables

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2454]
It is possible to configure Che using environment variables instead of property file.
Supposed way of doing that is:
env variable **CHE_SOME_PROPERTY** is converted into **some.property**.

But it is not possible to configure property if it contains underscore, e.g. **some.variable_with_underscore**.

**Che version:**    5.0.0-M2
**OS and version:** Linux (behavior will be the same for any OS)
**Che install:**    Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes - there was no env variable injection before]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by TylerJewell** [comment]
Cannot reproduce.

Use double underscore to create underscore.  See the docs.

**Comment by garagatyi** [comment]
I reproduced it. Here is no replacing of double underscores with single https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/CheBootstrap.java#L272

**Comment by TylerJewell** [comment]
I still cannot reproduce this.  If you use the CLI, then the underscores are converted.

**Comment by garagatyi** [comment]
Can you provide steps to reproduce that it is working?

**Comment by TylerJewell** [comment]
1. Get CLI
2. `export CHE_PROPERTY_machine_ws__agent_max__start__time__ms=1000`
3. `che start`
