### ISSUE TITLE
UD not updated properly when ws stopped under certain conditions

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2457]
In certain circumstance, the UD does not update its indication that a workspace is stopped. It is showing the workspace as running even though it's state has been stopped. 
1. Start a ws and open IDE.
2. Right click in UD to stop ws.  It will begin snapshotting process  
3. Before finished, go into workspaces view & view workspace.  It is running.
4. Wait - eventually WS is stopped.  However....
5. WS view & left nav never updated even though ws stopped.  Only green dots.  But the ws is stopped.
6. Try to stop ws & get error message
7. If you refresh browser, then UD is updated with correct gray dots.

This was tested on 5.0.0-M1.

**Comment by ashumilova** [comment]
Depends on https://github.com/eclipse/che/issues/2683

**Comment by ashumilova** [comment]
Fixed by https://github.com/eclipse/che/pull/2875
