### ISSUE TITLE
Add ability define default command to the Project Type definition

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#2458]
It can be command for examples for compile project, run it or debug.

**Comment by azatsarynnyy** [comment]
In many cases, the default commands for a project depend on a project's type.
A quick example: maven build command. It makes sense only for the projects with Maven PType.
But Dashboard provides several stacks propose the same command for maven build. It would be provided PType.
So I think that allowing Project Type to bring its default command is extremely useful.

**Comment by slemeur** [comment]
Won't fix in Che 6
