### ISSUE TITLE
import project from local file system

### ISSUE THREAD

**Issue by chorkiong** [eclipse-che/che#246]
based on this [link](https://eclipse-che.readme.io/docs/import-a-project), I can import project from a local file system by "Copy a project to Che's projects folder on the local file system". May I know what's the Che's projects path?

Thanks

**Comment by benoitf** [comment]
hello @chorkiong , you should find it in the che.properties located in che conf folder
https://github.com/codenvy/che/blob/master/assembly-ide-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L16-L20

On Windows, all workspaces stored in c:\%userprofile%\AppData\Local\Eclipse Che\
che.user.workspaces.storage=${che.home}/workspaces
