### ISSUE TITLE
The settings 'errors/warning' for editor are not storage after restart workspace 

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2460]
**Reproduction Steps:**
1. Start workspace
2. Go to 'Profile' -> 'Preferenses' -> 'Errors/warning'
3. Change the settings and save them.
4. Restart the workspace

**Observed behavior:**
The settings 'errors/warning' for editor return to default values

**Che version:**    5.0.0-M2-SNAPSHOT
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**   local   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ghost** [comment]
Cannoted be reproduced anymore
