### ISSUE TITLE
Improve Panels behaviors in IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2463]
The goal of this issue is to improve the behaviors of panel. 
A user should be able to maximize the size of any panel in the UI
A panel could have display options and various secondary actions which does not need to be displayed all the time to the user. 

There are two enhancements:
- [ ] Provide mecanism for panel's options
- [ ] Allow any panel to be maximized/minimized

Here is a first proposal for the UI.
_Minimized version of the Console Panel_
![ide - console panel - small](https://cloud.githubusercontent.com/assets/1636769/18781132/ca1390c0-8180-11e6-96a7-64848fd28fd0.png)

_Maximized version of the Console panel_
![ide - console panel - fullscreen](https://cloud.githubusercontent.com/assets/1636769/18781140/d0538e72-8180-11e6-8420-9e8801562b0c.png)

**Comment by TylerJewell** [comment]
It takes two clicks for someone to hide the console tree.  That doesn't seem very user friendly.

**Comment by TylerJewell** [comment]
Developers will expect key bindings for each behavior as well.

**Comment by slemeur** [comment]
Discussed and agreed on this solution.
Will soften the icons.

**Comment by slemeur** [comment]
Updated mockups

**Comment by TylerJewell** [comment]
"Fullscreen Pane" is not good english.  Change it to "Maximize".  Also, the buttons seem to be too big vs. other menu drop downs that we have.  And I am not clear on the differences between the button to expand vs. the drop down.  So I am not sure this issue is design complete.

**Comment by slemeur** [comment]
Updated icon shape + styles.

![ide - console panel - small](https://cloud.githubusercontent.com/assets/1636769/19522297/ec465290-9616-11e6-8e97-fa59a2eba903.png)

![ide - console panel - fullscreen](https://cloud.githubusercontent.com/assets/1636769/19522298/ec5083be-9616-11e6-833d-0d6a0550dfb2.png)

**Comment by slemeur** [comment]
Two new options proposed.

## Option1: Panels with always 3 buttons
- button1: expand/collapse
- button2: maximize
- button3: more options

The button3 "more options" will display a dropdown which show the state of the maximize mode with a checkmark. The other panel options are displayed in this dropdown menu. 

![ide - console panel - normal](https://cloud.githubusercontent.com/assets/1636769/19602432/862ea65e-97ad-11e6-9a5b-f4957a9a46ee.png)
![ide - console panel - small](https://cloud.githubusercontent.com/assets/1636769/19602434/8637b8f2-97ad-11e6-8e77-ba0a3812f319.png)
![ide - console panel - fullscreen](https://cloud.githubusercontent.com/assets/1636769/19602433/862f4c30-97ad-11e6-9941-1e1bb589d841.png)

## Option2: Panels with 1 button always displayed and other revealed on hover in the title bar

The idea of this option is to limit the number of buttons displayed in the toolbar. Only primary actions should be displayed to a user - and secondary actions should be displayed in a discoverable and learnable way.

All panels would display the "option button":
![ide - console panel - no hover](https://cloud.githubusercontent.com/assets/1636769/19602680/6fdddef0-97ae-11e6-853b-cda96edd304c.png)

On hover, we then display the other actions:
![ide - console panel - hover](https://cloud.githubusercontent.com/assets/1636769/19602678/6fd79054-97ae-11e6-9c62-6d532e01c5f7.png)

On clicked, we show the dropdown:
![ide - console panel - clicked](https://cloud.githubusercontent.com/assets/1636769/19602679/6fdb5ed2-97ae-11e6-965c-42f7f0c98715.png)

Maximized:
![ide - console panel - fullscreen](https://cloud.githubusercontent.com/assets/1636769/19602801/eafdb0b0-97ae-11e6-8d24-c335825ee84f.png)

Option2 provide a more elegant UX, but for simplicity and consistency with other existing IDE, I prefer the Option1.

I let others voting.

**Comment by vitaliy-guliy** [comment]
Which option is preferred?
