### ISSUE TITLE
Send schema associations to JSON language server

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#2471]
The VS Code language server expects a custom (not part of the protocol) notification `json/schemaAssociations` to associate JSON files to JSON schemas. This activates capabilities like code completion, validation and hover without the need to add a `$schema` key.

Here is an example object passed with the `json/schemaAssociations` notification:

``` json
{
    "/bower.json": [
        "http://json.schemastore.org/bower"
    ],
    "/composer.json": [
        "https://getcomposer.org/schema.json"
    ],
}
```

Currently, Che does not send the `json/schemaAssociations` notification, which significantly limits the capabilities of the JSON language server integration. It is not realistic to expect that users will manually add the `$schema` key to each JSON file they work with.

**Reproduction Steps:**
1. Open a bower.json file
2. Try code completion

**Expected behavior:**

Code completion, validation and hover work without specifying a proper `$schema` key.

**Observed behavior:**

Code completion, validation and hover do not work without specifying a proper `$schema` key.

**Che version:**    5.0.0-M2-SNAPSHOT (latest master)
**OS and version:** Fedora 24
**Docker version:** 1.10.3
**Che install:**    local build, run with the `bin/che.sh` script

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by kaloyan-raev** [comment]
I submitted PR #2474 with the fix.

Note that it contains a hardcoded list of associations. It's enough as a first step, but in future we should think about an extensible way to contribute to this list by plugins.

For example:
- The JavaScript plugin should contribute the associations for `bower.json`
- The Node plugin - for `package.json`
- The PHP plugin - for `composer.json`
- The TypeScript plugin - for `tsconfig.json`
- etc.

For reference here is how the PHP plugin in VS Code contributes the schema association for `composer.json`: https://github.com/Microsoft/vscode/blob/master/extensions/php/package.json#L51-L56

**Comment by bmicklea** [comment]
@kaloyan-raev I'm moving this to M6 milestone because we're pushing to get M5 out ASAP.

**Comment by tolusha** [comment]
@kaloyan-raev 
Nice work.

Concerning implementation to have code cleaner I would change a bit your approach. I would add a new entity `SchemeAssociator` as observer of the `ServerInitializer` and wouldn't mix it with LanguageServer itself.

**Comment by kaloyan-raev** [comment]
@tolusha OK. I am curious to see how this new approach looks like.
