### ISSUE TITLE
Do not try to connect to terminal if terminal agent not found in machine config

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2472]
When the terminal agent is missing in machine config, the IDE still tries to connect to a terminal. As a result, error messages pop up which is not a good user experience.

It would be good is the IDE checks if there's a terminal agent in the machine config and connects to it only if there's one.

**Comment by vparfonov** [comment]
Nice catch

**Comment by vitaliy-guliy** [comment]
Spent 1d
