### ISSUE TITLE
CLI: Run Che specify CHE_HOST_IP

### ISSUE THREAD

**Issue by wiserweb** [eclipse-che/che#2476]
[Short description of problem here]

Che CLI allows launching using short commands 'To Make Life Simpler'

`$ che start|stop|restart|info|update`

There doesn't seem to be a way to specify CHE_HOST_IP with the CLI script. The IP is determined by get_docker_host_ip() method in script.

**Reproduction Steps:**

`$ che start`

**Expected behavior:**

`$ che start CHE_HOST_IP=192.168.1.110`

Anything here would suffice to be able to specify desired host IP. This is so that machines on the LAN can access the CHE instance.

**Observed behavior:**

Currently the IP is assigned by get_docker_host_ip() and doesn't seem to provide a way to explicitly specify the desired IP.

**Che version:**    latest 4.7.2
**OS and version:** Ubuntu 16.0.4
**Docker version:** 1.11.2
**Che install:**    Docker

**Additional information:**

Perhaps this already exists but I could not locate the documentation. It seems the only workaround is to use the long form docker launch method.

`sudo docker run –rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_HOST_IP=192.168.1.110 eclipse/che start`

**Comment by TylerJewell** [comment]
Set the variable as an environment variable of your OS before running the cli.

'export CHE_HOST_IP'

**Comment by wiserweb** [comment]
Sorry, this is not obvious... but since sudo is being used the 'export CHE_HOST_IP' doesn't take... 

```
owner@opteron:~$ export CHE_HOST_IP=192.168.1.110
owner@opteron:~$ sudo ./che.sh start
WARNING: No swap limit support
INFO: ECLIPSE CHE: Found image codenvy/che-server:latest
INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 4.7.2
INFO: ECLIPSE CHE: Use: http://172.17.0.1:8080
INFO: ECLIPSE CHE: API: http://172.17.0.1:8080/swagger
```

**Comment by TylerJewell** [comment]
The host IP is what sets the system for how it will bind itself to a particular IP address.  Che_hostname defines what will be advertised as the published IP.  You can set both independently.

**Comment by wiserweb** [comment]
The use case is just to allow other clients on the LAN to access the che instance. 

To be clear and for others who might encounter this need... the following works.. confirmed.

```
owner@opteron:~$ sudo -i
root@opteron:/home/owner# export CHE_HOST_IP=192.168.1.110
root@opteron:/home/owner# ./che.sh stop
WARNING: No swap limit support
INFO: ECLIPSE CHE: Stopping server...
INFO: ECLIPSE CHE: Removing container
INFO: ECLIPSE CHE: Stopped
root@opteron:/home/owner# ./che.sh start
WARNING: No swap limit support
INFO: ECLIPSE CHE: Found image codenvy/che-server:latest
INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 4.7.2
INFO: ECLIPSE CHE: Use: http://192.168.1.110:8080
INFO: ECLIPSE CHE: API: http://192.168.1.110:8080/swagger
```

Thank you Tyler for assistance..
