### ISSUE TITLE
Workspace name and RAM not respected when importing from workspace definition file

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2477]
When I create a workspace by importing from a workspace definition file the workspace name and RAM allocation in the workspace definition file are not used for my new workspace. I would expect that these values would be brought into the UD so that they are used if I don't edit them.

**Comment by slemeur** [comment]
Discussed. will be taken in current sprint.

**Comment by ashumilova** [comment]
Log work : 6h
