### ISSUE TITLE
Add editing mode in workspace view

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2478]
When there are any changes in workspace config made by user, dashboard should show - editing mode with proposal to save or cancel changes and restart workspace.

![pasted_image_at_2016_09_01_04_24_pm](https://cloud.githubusercontent.com/assets/1611939/18625062/ac1884a6-7e54-11e6-908a-63c93d1e7d14.png)

**Comment by akurinnoy** [comment]
![screencast](https://cloud.githubusercontent.com/assets/16220722/18714377/3a02c018-801e-11e6-95dd-41a57b0aaf4b.gif)

**Comment by slemeur** [comment]
Looks nice to me !

**Comment by akurinnoy** [comment]
time spent: 2d
