### ISSUE TITLE
Cannot create additional machine

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#248]
I created a new project from the PHP template. Then I went to the Machine Perspective and tried to create a new machine from this recipe: https://raw.githubusercontent.com/codenvy/dockerfiles/master/php/ubuntu/Dockerfile

The machine is built successfully, but then fails to start and disappears from the Machines view. 

Here is the output in the Machine view:

> [DOCKER] Step 1 : FROM codenvy/ubuntu_jre
> [DOCKER] Trying to pull repository docker.io/codenvy/ubuntu_jre ...
> [DOCKER] latest: Pulling from codenvy/ubuntu_jre 
> [DOCKER] Digest: sha256:db3441ba1a77d1b813041b88408c7d3587ed581a9f3069735cbbc6cc6a2a3aaa 
> [DOCKER] Status: Image is up to date for docker.io/codenvy/ubuntu_jre:latest 
> [DOCKER] 
> [DOCKER] ---> b04de6d0da93
> [DOCKER] Step 2 : RUN sudo apt-get update && sudo apt-get install -y apache2 php5 php5-mhash php5-mcrypt php5-curl php5-cli php5-mysql php5-gd libapache2-mod-php5 php5-cli php5-json php5-cgi php5-sqlite && sudo apt-get clean && sudo apt-get -y autoremove && sudo apt-get -y clean && sudo rm -rf /var/lib/apt/lists/*
> [DOCKER] ---> Using cache
> [DOCKER] ---> def8fe11ac0a
> [DOCKER] Step 3 : RUN sudo sed -i 's/\/var\/www\/html/\/projects/g'  /etc/apache2/sites-available/000-default.conf && sudo sed -i 's/\/var\/www\//\/projects\//g' /etc/apache2/apache2.conf && sudo sed -i 's/None/All/g' /etc/apache2/apache2.conf && echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf && sudo a2enmod rewrite && curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
> [DOCKER] ---> Using cache
> [DOCKER] ---> 1981e6b55e89
> [DOCKER] Step 4 : LABEL che:server:80:ref apache2 che:server:80:protocol http
> [DOCKER] ---> Using cache
> [DOCKER] ---> 9cd02f2ff2da
> [DOCKER] Step 5 : EXPOSE 80
> [DOCKER] ---> Using cache
> [DOCKER] ---> 10dd1405b3a2
> [DOCKER] Step 6 : CMD sudo chown -R www-data:www-data /projects && sudo chmod -R 777 /projects && tail -f /dev/null
> [DOCKER] ---> Using cache
> [DOCKER] ---> 1f65c82609cb
> [DOCKER] Successfully built 1f65c82609cb
> Machine is destroyed.

**Comment by ghost** [comment]
Try it this way:

```
FROM codenvy/php
CMD tailf /dev/null
```

The image has been designed to serve as a workspace machine where there's `projects` directory with mounted local projects. In case of an auxiliary machine, no mounting happens and therefore `chown` fails. We do `chown` so that Apache can write files in that directory.

**Comment by kaloyan-raev** [comment]
Thanks! This worked.

Now, I faced another issue. When I changed the focus to the Machine view, the new machine got renamed to "docker". Now, I have two machine with name "docker" in the list. 

When I switch back to the Project Perspective I see only the "ws-machine" available to execute commands on. My expectation was that the new auxiliary machine would be an alternative choice for executing commands. Do I have wrong understanding?

**Comment by ghost** [comment]
Two machines named Docker is a bug.

As to executing commands against a machine, it is only possible to do so against a workspace machine with a workspace agent inside.

**Comment by garagatyi** [comment]
No, it is possible to fire command in any machine - API supports it. But it is not implemented on UI yet.
Please open an issue for that feature.

Also, please, open an issue for machines with names "docker".

**Comment by kaloyan-raev** [comment]
Thanks for your replies. I opened #249 and #250.
