### ISSUE TITLE
iPad issue

### ISSUE THREAD

**Issue by ChristianBcn** [eclipse-che/che#2481]
Once I'm in the Dashboard I can see all projects I go ahead choosing one but the loading bar comes to load and doesn't happen anything. I tried in my laptop an it works well. On iPhone happens the same.

**Reproduction Steps:**
1. Going to Dashboard
2. Select Project
3. Loading bar all time

**Expected behavior:**

Start to create/edit files from project

**Observed behavior:**

Not starts to show porject

**Che version:**    4.7.2  
**OS and version:** problem in iOS 10  (server installed google compute engine Debian GNU/Linux 8.5 (jessie))
**Docker version:** 1.12.1  
**Che install:**   Bitnami   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: First time I use Che
- Problem can be reliably reproduced, doesn't happen randomly: No

**Comment by TylerJewell** [comment]
Thanks for reporting the issue.  We don't include mobile devices in our test matrix right now as it is not a target that we currently want to support.  So minor issues like this are to be expected from time to time.  We will think about this next year.

**Comment by ChristianBcn** [comment]
Thanks Tyler. It is a pity so I'm looking forward this for the next year so. I appreciate your help and if  you need in the future help to report iPad issues of this kind of issues count with me.

**Comment by hermitmaster** [comment]
First-class iPad/touchscreen support would be huge for me. I’ve got a lot of clients that I could get to use Che if it supported mobile devices. Specifically the iPad Pro and other large tablets.

**Comment by amccarri** [comment]
Would be awesome to see this happen.  The ability to code on iPad was the only reason I was looking at Eclipse Che.

**Comment by ThisIsSet-L** [comment]
+1 for iPad support.

**Comment by ryanrdetzel** [comment]
So disappointed this doesn't work. I setup Che and got it running just to find out I can't really use it with the ipad. :-(  It does't feel like a hard problem, maybe I'll dive in a take a look.

**Comment by TheSpaceNomad** [comment]
Using an iPad Pro (2016 9.7”, iOS 12.1, w/ apple smart keyboard) :
I managed to open a file by using “navigate to”. It wasn’t easy anyway, and had a lot of hit-and-misses.
Another problem is that the “spacebar” doesn’t register as the character “space”. You need to us “SHIFT + SPACEBAR” in order to get the “space” char. 
Same happens with other shortcuts as well.

**Comment by hermitmaster** [comment]
I think a lot of people are still looking for tablet support. The need for a proper IDE is the only thing that still ties me to a desktop OS.

**Comment by skabashnyuk** [comment]
Not relevant anymore. Please consider opening a new issue if you think it is up to date.
