### ISSUE TITLE
Copy to clipboard button animation works strange in export workspace config view

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2482]
It almost never changes color on mouse hover.

**Che version:**    5.0.0-M2-Snapshot
**OS and version:** ubuntu 14.04
**Che install:**    native

**Comment by ghost** [comment]
Not an issue in 5.15-SNAPSHOT:

![image](https://user-images.githubusercontent.com/5337267/28065489-6e29f456-6641-11e7-96d7-c072423b3ede.png)
