### ISSUE TITLE
Creating a workspace from definition file doesn't work

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2489]
When I import a workspace from a definition file in Che I cannot start the workspace due to errors that appear to be related to the project.

**Reproduction Steps:**
1. Codenvy: Create a workspace at beta.codenvy.com with a sample project inside
2. Codenvy: Confirm that the workspace and project can be edited, built and run in beta.codenvy.com
3. Codenvy: Export the config for the workspace
   Scenario 1
4. Che: Open a local Che instance and navigate to the "Workspaces" page in the UD left-nav
5. Che: Create a new workspace from the definition file
6. Che: Try to open the IDE
   Scenario 2
7. Codenvy: In beta.codenvy.com navigate to the "Workspaces" page in the UD left-nav
8. Codenvy: Create a new workspace from the definition file
9. Codenvy: Open the IDE
10. Codenvy: After IDE opens try to open the source code

**Expected behavior:**
The workspace starts with the same runtime and projects defined in the definition file. The source code can be edited, built and run.

**Observed behavior:**
Scenario 1: The workspace cannot be created due to errrors.
Scenario 2: The workspace is created, but the project cannot be opened.

Scenario 1:
**Codenvy version:** beta.codenvy.com running 4.7.2
**Che version:**    4.7.0
**OS and version:** Mac OSX 10.11.6
**Docker version:** 1.12.1-beta26
**Che install:**    che start  

Scenario 2:
**Codenvy version:** beta.codenvy.com running 4.7.2

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by benoitf** [comment]
@bmicklea
I would say that for scenario1:
beta.codenvy.com is running 5.0.x version (not 4.7.2 but 5.0.0-M2 for now) and then as workspace model definition has been changed internally, che version needs to be >= beta.codenvy.com version

and for scenario2 I would say that it's a bug if it doesn't work
