### ISSUE TITLE
New auxiliary machine displayed with name "docker"

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#249]
Eclipse Che 4.0.0-beta-13 on Fedora 23 64-bit

Steps to reproduce:
1. Create new PHP project/workspace.
2. Go to the Machines Perspective.
3. Create new machine via Machine > Create... from main menu.
4. Give name "zendserver".
5. Use the following URL for recipe: https://raw.githubusercontent.com/kaloyan-raev/che-zendserver/master/Dockerfile
6. Click on the Create button and wait for the creation process to complete.
7. Once you see "[DOCKER] Successfully built 40b6bb989d40" in the Machine output, click on the new "zendserver" item in the list of the Machines view.

At this moment the name of the new machine is changed from "zendserver" to docker. It only happens in the master part (the list) of the view. The name is correctly displayed in the details part.

![image](https://cloud.githubusercontent.com/assets/468091/12711563/a0c37dfe-c8c9-11e5-8ef2-2b06222b2618.png)

**Comment by TylerJewell** [comment]
@garagatyi Please open issue for this, and lets target fix for 4.0.0 GA.

**Comment by garagatyi** [comment]
@TylerJewell We already have issue IDEX-3888

**Comment by dimashnurenko** [comment]
The issue is fixed.

**Comment by ghost** [comment]
Closing the issue. @kaloyan-raev feel free to reopen if you can reproduce it with current master of RC5 that we will release later.
