### ISSUE TITLE
Java reconcile problem

### ISSUE THREAD

**Issue by mstojanovic087** [eclipse-che/che#2491]
Semantic highlight and parsing stops working when certain actions are taken. 

**Reproduction Steps:**
1. Create new plain Java project.
2. Import some library jar (L) and add it to classpath.
3. Add line to java class: 'SomeClassFromL obj = new SomeClassFromL();'
4. (Important) Use refactoring->rename action on obj. (i.e. rename it to obj2)
5. After document is stabilized, delete import line which refers to SomeClassFromL.
6. Notice that no error has been reported and semantic highlight (i.e. main function or Constructor name) is missing.

**Expected behavior:**

After removing the import line, error of no class definition found should be reported and SomeClassFromL occurrences should be underlined. (like when step 4. is excluded)
If you exclude step 4. from reproduction steps, you get Expected behavior. 

**Observed behavior:**

After removing the import line, the file behavior changes to normal after closing and again opening the 
file. 

**Che version:**    4.7.2
**OS and version:** Centos 7
**Docker version:** 1.12.1
**Che install:**    Docker container (Che was run from codenvy/che-server:4.7.2. image) 
- Problem can be reliably reproduced, doesn't happen randomly: Yes

![cheissue](https://cloud.githubusercontent.com/assets/20304671/18638775/a7348fce-7e91-11e6-9ef6-03c70d202424.gif)

**Comment by evidolob** [comment]
Cannot reproduce on 0b82be1 version
