### ISSUE TITLE
json structure to create dot net project in eclipse che workspace

### ISSUE THREAD

**Issue by worksamp** [eclipse-che/che#2493]
[Short description of problem here]

I had referred eclipse che api for api's but did'nt get json structure for dotnet project.

can you please help me with this?

**Reproduction Steps:**
1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Che version:**    [Enter Che version here]  
**OS and version:** [Enter OS name and version here]  
**Docker version:** [Enter your Docker version here `docker version` on CLI]  
**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by AndrienkoAleksandr** [comment]
If you want to create empty "csharp" project you can use such json:
`{
  "name": "MyCsharpSample",
  "attributes": {
    "language": [
      "csharp_lang"
    ]
  },
  "type": "csharp",
  "source": {
    "parameters": {}
  },
  "path": "/MyCsharpSample",
  "problems": [],
  "mixins": []
}`

**Comment by worksamp** [comment]
I am not able to create asp dot net project from above structure.

Is there any way from which i will be able to import project from git repository (need json structure for importing project from git repository)

**Comment by worksamp** [comment]
Hi,

I am using following json for creating workspace with dot net project:

{
  "defaultEnv": "default",
  "environments": [
    {
      "machineConfigs": [
        {
          "dev": true,
          "servers": [ ],
          "envVariables": { },
          "limits": {
            "ram": 1000
          },
          "source": {
            "type": "dockerfile",
             "content": "FROM codenvy/dotnet_core"
          },
          "name": "default",
          "type": "docker",
          "links": []
        }
      ],
      "name": "default"
    }
  ],
  "commands": [
    {
      "commandLine": "cd ${current.project.path} && dotnet restore",
      "name": "update dependencies",
      "type": "custom",
      "attributes": {
        "previewUrl": ""
      }
    },
    {
      "commandLine": "cd ${current.project.path} && dotnet run",
      "name": "run",
      "type": "custom",
      "attributes": {
        "previewUrl": "http://${server.port.5000}"
      }
    },
    {
      "commandLine": "cd /projects/aspnet-web-simple && dotnet restore",
      "name": "aspnet-web-simple: update dependencies",
      "type": "custom",
      "attributes": {
        "previewUrl": ""
      }
    },
    {
      "commandLine": "cd /projects/aspnet-web-simple && dotnet run",
      "name": "aspnet-web-simple: run",
      "type": "custom",
      "attributes": {
        "previewUrl": "http://${server.port.5000}"
      }
    }
  ],
  "projects": [{
            "links": [],
        "name": "aspnet-web-simple",
        "attributes": {
          "vcs.provider.name": [
            "git"
          ],
          "git.current.branch.name": [
            "master"
          ],
          "git.repository.remotes": [
            "https://github.com/che-samples/aspnet-web-simple.git"
          ]
        },
        "type": "blank",
        "source": {
          "location": "https://github.com/che-samples/aspnet-web-simple.git",
          "type": "git",
          "parameters": {}
        },
    "path": "/aspnet-web-simple",
        "problems": [],
        "mixins": [
          "git"
        ]
        }],
  "name": "wksp-xyz6",
  "links": []
}

**Comment by ddementieva** [comment]
@worksamp Follow these steps to import your git repository to Eclipse Che workspace:
1. In the REST API client choose POST as method and application/json as a content type.
2. Paste `http://localhost:$port/wsagent/ext/project/import/$your-project-name` as a Request URL.

$port - is a wsagent port, chosen from the ephemeral port range. When in Eclipse Che, open your workspace, switch to the Operations Perspective, go to the Servers tab and copy wsagent port in the Server Address column.

$your-project-name - change this value to your own project name
3. Paste {"location":"$your-git-repo-url-here", "type":"git"} in the Raw payload.
4. Click `Send` button.
5. Go to your Eclipse Che workspace and refresh the entire page.
6. Find your project in the Project Explorer.

Your request may look something like this:
![rest-client](https://cloud.githubusercontent.com/assets/6860395/18907675/41d99b84-8575-11e6-8201-7d6ce78a0d4a.png)

**Comment by worksamp** [comment]
By using link : http://localhost:$port/wsagent/ext/project/import/$your-project-name
I am getting following error: "can not get workspaces.The reason:Workspace with name ext and owner wsagent was not found".

**Comment by worksamp** [comment]
I am using swagger for creating workspace and project.

In that I am using create workspace link and using following json, but not able to create project:

{
  "defaultEnv": "dotnet",
  "environments": [
    {
        "name": "dotnet",
        "machineConfigs": [
          {
            "limits": {
              "ram": 1000
            },
            "name": "ws-machine",
            "type": "docker",
            "source": {
              "type": "dockerfile",
              "content": "FROM codenvy/dotnet_core"
            },
            "dev": true,
            "servers": [],
            "envVariables": {},
            "links": []
          }
        ]
      }
  ],
 "commands": [
      {
        "commandLine": "cd ${current.project.path} && dotnet run",
        "name": "run",
        "attributes": {
          "previewUrl": "http://${server.port.5000}"
        },
        "type": "custom"
      },
      {
        "commandLine": "cd ${current.project.path} && dotnet restore",
        "name": "update dependencies",
        "attributes": {
          "previewUrl": ""
        },
        "type": "custom"
      }
    ],
  "projects": [
    {
        "links": [],
        "name": "aspnet-web-simple",
        "attributes": {
          "vcs.provider.name": [
            "git"
          ],
          "git.current.branch.name": [
            "master"
          ],
          "git.repository.remotes": [
            "https://github.com/che-samples/aspnet-web-simple.git"
          ]
        },
        "type": "blank",
        "source": {
          "location": "https://github.com/che-samples/aspnet-web-simple.git",
          "type": "git",
          "parameters": {}
        },
        "path": "/aspnet-web-simple",
        "problems": [],
        "mixins": [
          "git"
        ]
      }
  ],
  "name": "wksp-sample27",
  "links": []
}

**Comment by worksamp** [comment]
@ddementieva : Thank you so much :-) Now I am able to create project using api.

Now I need to create workspace using api.

Can you please help me with this

**Comment by ddementieva** [comment]
@worksamp To see the correct workspace json, you can create a default workspace with dotnet stack from the Dashboard, go to the Workspaces tab, choose dotnet workspace and click `Export as a file` button.

Copy its content, modify if necessary, go to the `Swagger > workspace > Create a new workspace based on the configuration` (http://localhost:8080/swagger/#!/workspace/create), paste your json as a body there.  

Your JSON to create dotnet workspace may look something like that:

```
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "dev-machine": {
          "attributes": {
            "memoryLimitBytes": "2147483648"
          },
          "servers": {},
          "agents": [
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh"
          ]
        }
      },
      "recipe": {
        "location": "codenvy/dotnet_core",
        "type": "dockerimage"
      }
    }
  },
  "projects": [],
  "name": "default-dotnet",
  "commands": [
    {
      "commandLine": "cd ${current.project.path} && dotnet restore",
      "name": "update dependencies",
      "attributes": {},
      "type": "custom"
    },
    {
      "commandLine": "cd ${current.project.path} && dotnet run",
      "name": "run",
      "attributes": {},
      "type": "custom"
    }
  ]
}
```

**Comment by worksamp** [comment]
@ddementieva : I am using this only, but I need to create it from Rest API client.

**Comment by ddementieva** [comment]
@worksamp This is POST method to http://localhost:8080/api/workspace

![create-ws-example](https://cloud.githubusercontent.com/assets/6860395/18952650/3a6b3504-8653-11e6-9989-a9792f141ab3.png)

**Comment by worksamp** [comment]
Thank you so much for your inputs. I am able to create it :-) :+1:
