### ISSUE TITLE
Impossible to change RAM when compose stack is selected

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2494]
It is not possible to change the RAM when the compose stack is selected.

![screen shot 2016-09-19 at 18 51 52](https://cloud.githubusercontent.com/assets/1636769/18640880/69872ebc-7e9a-11e6-809e-7cfacc62358a.png)

**Reproduction Steps:**
1. Create a new workspace, select "Java-MYSQL"

**Expected behavior:**
It is possible to change the RAM.

**Observed behavior:**
The RAM widget is not displayed. see image.

**Che version:**    5.0.0-M1
**Che install:**    Che and Codenvy

**Comment by akurinnoy** [comment]
time spent: 4h

**Comment by ashumilova** [comment]
@slemeur this fix cannot be backported to M1 without changes introduced with this commit - https://github.com/eclipse/che/commit/4e7f9fae9d82be36497a4e287aabee6d01878653 (M2)

**Comment by slemeur** [comment]
For for the update. Then, this issue will wait M3.
