### ISSUE TITLE
Incorrect url is being used when pulling from private registry (v5 M1)

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2495]
So im adding private dockerhub account as a private registry, using this dockerhub url:
https://index.docker.io/v1/  
(see here: http://imgur.com/P7bJ0WE )

Then Im creating a custom workspace simply by typing:

```
FROM username/repo
```

Workspace then fails to start with the following message: 

```
DOCKER] Step 1 : FROM username/repo
[DOCKER] [ERROR] Get https://registry-1.docker.io/v2/username/repo/manifests/latest: unauthorized: incorrect username or password
[ERROR] Docker image build failed. Image id not found in build output.
```

(see here: http://imgur.com/a/CxfI7)

^ so it seems like it tries to pull from a different url then the one I've specified in the config:
I've specified: https://registry-1.docker.io/v1
but it's pulling from : https://registry-1.docker.io/v2

Is this a bug or am I doing something wrong?

**Comment by JamesDrummond** [comment]
@loganto Have you added the registry to your che server configuration? [https://eclipse-che.readme.io/docs/configuration#section-add-your-registry-to-che](https://eclipse-che.readme.io/docs/configuration#section-add-your-registry-to-che). If you don't want to use the che.properties and you are using the latest version of che 4.7 you will be able to set the environment variables like so

```
#use export in lieu of set if on LInux and mac
set CHE_PROPERTY_docker_registry_auth_url=https://index.docker.io/v1/
set CHE_PROPERTY_docker_registry_auth_username=<user1>
set CHE_PROPERTY_docker_registry_auth_password=<pass>
set CHE_PROPERTY_docker_registry_auth_email=<user1@email.com>
```

**Comment by ghost** [comment]
@loganto can you add DockerHub as `docker.io` - just checked - it should work.

@JamesDrummond there's no need to add this one to properties.

**Comment by linuxd3v** [comment]
@eivantsov 
Just `docker.io` without any prefix? doesn't seem to  work either.

**Comment by ghost** [comment]
@loganto yes, just `docker.io`

Can you remove the registry. Restart Che, and add it again?

**Comment by linuxd3v** [comment]
@eivantsov 
facepalm moment. I've been using the wrong password. lol.
Thanks for helping!

**Comment by JamesDrummond** [comment]
@loganto It happens :) . Please close issue when you get a chance. Thanks.
