### ISSUE TITLE
How would I preview a typical LAMP project?

### ISSUE THREAD

**Issue by linuxd3v** [eclipse-che/che#2497]
So I've got Che installed and configured.
I pulled project from bitbucket just fine.  

But can't wrap my head around how would I be previewing changes that I make?
Let's say I code something in php -> Id usually refresh the page and see my changes.
How would would I do i with Eclipse Che?

**Comment by TylerJewell** [comment]
The PHP application needs to be launched inside of a container. So you first need to run a command that launches the PHP server as you normally would on your desktop.  In the command, you then need to provide a preview URL which indicates how to access that PHP server inside of your container.  We provide instructions on how to write these preview URLs with macros, which provide a mapping from inside your workspace to the outside world.  

So you may be running your PHP server on port 9000, but our macros will look it up and tell you that it's really running on port 32789 to the outside world.  Most of the templates that we have shipping with Che have these preview URLs contained within them that you can see and test.

https://eclipse-che.readme.io/docs/previews

**Comment by linuxd3v** [comment]
thx. I think Im getting the idea. Ill try it.

**Comment by ghost** [comment]
@loganto if it's running on 80 port, go to operations perspective (a switcher in the top right corner) and find the published port for port 80.
