### ISSUE TITLE
Execute commands on auxiliary machines

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#250]
As discussed in #248 it should be possible to run commands on auxiliary machines. This is possible via the REST API, but not implemented in the UI yet.

**Comment by ghost** [comment]
@kaloyan-raev this is already implemented in one of the development branches. I hope to see it in master pretty soon.

**Comment by ghost** [comment]
Feature implemented. You can now choose a target machine when running a command.
