### ISSUE TITLE
Code Assistant and Code Validation don't work for C# 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#2509]
**Reproduction Steps:**
1. Add org.eclipse.che.ls.csharp agent to the you environment 
2. Start workspace
3. Create C# project
4. Crete new CS file

**Expected behavior:**

Code intellisense  should work 

**Che version:**    5.0.0-M2-SNAPSHOT
**OS and version:** Ubuntu 15.10
**Docker version:** 1.12.0

**Additional information:**
I created workspace from Debian stack. Stop it. Then add org.eclipse.che.ls.csharp with swagger in workspace/update environment section. Start workspace again

**Comment by evidolob** [comment]
OmnySharp language server requires project.json file in project root folder https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json 
For demo I use project.json file with this content: 

``` json
{
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "1.0.0-rc2-3002702"
        }
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": "dnxcore50"
        }
    }
}
```
