### ISSUE TITLE
Is there a demo server available?

### ISSUE THREAD

**Issue by vadimnehta** [eclipse-che/che#251]
Is there an Eclipse Che demo server available to try without setup?

**Comment by TylerJewell** [comment]
We are setting one up, but it is not currently available. It needs a lot more testing and we have to put some security controls in place to prevent bitcoin mining, limit visibility to other user's workspaces, and the so forth.   Right now, the quickest way to get started is to install and run the server yourself.

**Comment by vadimnehta** [comment]
Thank you.
