### ISSUE TITLE
Link to 4.7 Release Notes on homepage broken

### ISSUE THREAD

**Issue by wiserweb** [eclipse-che/che#2513]
Unrelated to Eclipse Che software.

The link on the homepage https://eclipse.org/che/ for 4.7 Release notes [http://che.eclipse.org/release-notes-eclipse-che-4-7/] doesn't appear to work.

**Comment by ghost** [comment]
@TylerJewell or whoever has access to this page, can you take a look please?

@wiserweb thanks for the heads up

**Comment by slemeur** [comment]
The link is the correct one, but the blog seems to be down - it's an Eclipse Foundation service. Checking to restore it.
