### ISSUE TITLE
Add ability to configure machines inside stack definition

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2515]
User configures the machines composing the stack's environment. It can be single machine or multi-machine. The list of machines is collapsible/expendable. By expending a machine, its details and configuration options are displayed, 
Each machine have:
- a name
- RAM
- can be defined as dev-machine (meaning it will be the primary machine where Che will injects agents for IDE tooling) (it is a toggle, activating the dev-machine in one machine of the environment will toggle-off in the other machines)
- a list of agents (if selected, they'll be injected in the machine)
- configuration for environment variables
- configuration for ports
- a list of commands

**Comment by olexii4** [comment]
6d
