### ISSUE TITLE
Add ability to set stack's category (advanced, general)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2516]
User should be able to set stack's category:
- advanced - stack will be listed on stack library section
- general - stack will be listed on ready-to-go section

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/2734/commits/272684dd1604efd60d17fb8900e4cb283f892f3c

**Comment by olexii4** [comment]
https://github.com/eclipse/che/commit/25f916760c62e07d610c6697996deba3f7f89bda

**Comment by olexii4** [comment]
1d
