### ISSUE TITLE
Eclipse Che Space in filepath error

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#252]
I wrote the question here: http://stackoverflow.com/questions/35143201/eclipse-che-not-starting-up/35143646#35143646, and followed the answer. It worked, but it said to post the issue here.

I'm using Windows 10, 64 bit. I downloaded the nightly version on 2/1/2016. This is the directory:

C:\Program Files\Eclipse Che\eclipse-che-nightly\eclipse-che-4.0.0-RC1-snapshot/

Just to clarify, the answer posted worked.

**Comment by TylerJewell** [comment]
Hi @ShivenGupta:

I am sorry that you ran into this issue. I'd appreciate you helping me diagnose any problems.

I just grabbed the 2/2 nightly build and ran it on Windows 10 in a directory name that matched your own. It ran OK.  There are a couple things that I'd like for you to check if you could.

First, the nightlies should have commits from last week that resolve the windows name spacing. In particular, can you inspect `/bin/che.bat` to see if it has these lines:

```
REM IDEX-4232 change windows long directories to DOS 8.3 format to handle directories with spaces
FOR %%i in ("%~dp0..") do set "CHE_WINDOWS_SHORT_DIR=%%~Si"
```

If it doesn't, then please grab the latest nightlies to ensure you have this addition.  If it does have those lines and you run the Che server, can you give me the output of the following lines.  When run on Windows 10, it should look like the following:

```
Using CATALINA_BASE:   /c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-R/tomcat
Using CATALINA_HOME:   /c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-R/tomcat
Using CATALINA_TMPDIR: /c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-R/tomcat/temp
Using JRE_HOME:        /c/codenvy/jdk1.8.0_45
```

Thanks.

**Comment by ghost** [comment]
I did not have those lines, and downloaded the new nightly, and it worked in the original directory.

**Comment by TylerJewell** [comment]
Thank you for following up.  Will close this issue.
