### ISSUE TITLE
Manage stack testing

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2520]
Once the user is done with the configuration of the stack, we provide the ability to test the stack with a temporary workspace, which will be used only for this purpose.
While editing the stack configuration, two buttons are displayed to the user to "test" the stack. Those buttons are displayed in the header and in the footer overlay.

![6 - stacks - testing - step 1](https://cloud.githubusercontent.com/assets/1636769/18206231/fb3327f8-7125-11e6-8958-28593b18a5a7.png)

When the user hits the "test" button, we show a popup where he can select the templates that are matching the tags he provided to the stack. This step is optional, user is not forced to inject project templates in the temporary workspace, he could also import projects from git, subversion sources.

![6 - stacks - testing - step 2](https://cloud.githubusercontent.com/assets/1636769/18206233/00a3c22e-7126-11e6-98c0-467aa0d4c1a5.png)

After this step is handle, the system boot the temporary workspace and use the stack. The IDE is displayed over the dashboard as it is a temporary one. If user closes the IDE view, the workspace is automatically destroyed. 
All machines outputs are displayed as usual inside of the "Consoles" panel.

**Comment by olexii4** [comment]
7d
