### ISSUE TITLE
Item 'Clear list' was present earlier but it's absent now

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2521]
**Reproduction Steps:**
1. Open any file in the editor
2. Go to 'Edit' -> 'Recent' on the top menu

**Observed behavior:**
Item 'Close list' is not present in the top menu

**Che version:**    Version :5.0.0-M2
**OS and version:** ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**   local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by olexii4** [comment]
5h
