### ISSUE TITLE
Wrong behavior after delete project on dashboard

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2527]
**Reproduction Steps:**
1. Create any project 
2. Go to 'Workspaces' 
3. Select workspace with this project and click on it
4. Open 'Projects' tab and click on the project
5. Click 'Delete'

**Observed behavior:**
After project will be removed you will be redirected to 'Runtime' tab. The project is still present on ''Projects' tab.

**Che version:**    5.0.0-M3-SNAPSHOT
OS and version: ubuntu 14.04 LTS
Docker version: 1.11.2
Che install: local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ashumilova** [comment]
Fixed by https://github.com/eclipse/che/pull/2537/files#diff-84447164726f1fc653a0410113734e6cR109
