### ISSUE TITLE
Unable to Create Workspace

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#253]
![capture](https://cloud.githubusercontent.com/assets/16431000/12740377/6c0b4444-c927-11e5-9cb8-9a7e2bee9f12.JPG)

I am using Windows 10, 64 bit. This is the nightly build on 2/1/2016. It says that the workspace does not respond, so I cannot create any projects at all. 

Thanks

**Comment by ghost** [comment]
How did you start Che and create the project?

Can you provide ws-agent logs? You should have seen them when starting a workspace.

**Comment by ghost** [comment]
@eivantsov I started che by running che.bat. I opened the ide by using a browser and going to localhost:8080. I created the workspace by doing new workspace. Here are the logs in a zip file (from the tomcat/logs).  The ws-agent folder is zipped, so the logs folder is empty. Do I need to unzip the folder?

[logs.zip](https://github.com/codenvy/che/files/114985/logs.zip)

**Comment by jcao219** [comment]
I have the same issue on Windows 10.

I would like to ssh into the thing, so that I can provide ws-agent logs, but I don't know the port.

--edit: Managed to ssh into it.

----edit: Problem resolved itself after restarting host machine.

**Comment by ghost** [comment]
The problem was fixed for you by restarting the machine? I tried restarting, but I still have the same problem.

**Comment by ghost** [comment]
Please see this comment: https://github.com/codenvy/che/issues/264#issuecomment-179438913

**Comment by ghost** [comment]
@eivantsov I just grabbed the latest nightly, and made sure I have java 1.8.0.71. I also tried deleting the VM in Virtualbox, following that comment, and rerunning che.bat. This still produces the same error.

**Comment by TylerJewell** [comment]
@ShivenGupta If you are up for a live debugging session, I am available for the next 60 minutes and happy to do a google hangout.

**Comment by ghost** [comment]
@TylerJewell  Ok sure.

**Comment by TylerJewell** [comment]
Yes - please post email and I'll send an invite.

**Comment by ghost** [comment]
shiven.gupta@gmail.com

**Comment by ghost** [comment]
I cannot do a video call right now. This laptop doesn't have a video camera.

**Comment by TylerJewell** [comment]
@eivantsov:  I did a 30 minute diagnostic.  Here are the results.  Che is working as specified.  But the issue is that on @ShivenGupta's Windows 10 computer, Virtual Box is running very slowly. It took nearly  4 minutes to create the default VM.  And when Che would start, it would take 35 seconds for Tomcat to activate. When the agent was being activated, the IDE.war was taking nearly a minute to deploy and then the timeout error.

Fix: We should make the ws-agent timeout configurable in che.properties.  This would solve this problem.

**Comment by ghost** [comment]
@eivantsov @TylerJewell After you told me the problem was with VirtualBox, I did a quick Google Search, and found [this](http://www.rawinfopages.com/tips/2015/05/speed-up-virtualbox-enormously-with-this-simple-tweak/) . I just changed power mode from HP Recommended to High Performance, and VirtualBox sped up. Now Che opens quickly, and opens the workspace!

**Comment by TylerJewell** [comment]
:100:

**Comment by ghost** [comment]
For future readers-

After you change your power plan to High Performance, you either need to only run Che when plugged into the charger, or go edit High Performance and change the min CPU level to 80%-90%,

**Comment by ghost** [comment]
Tried to reproduce it on my HP laptop but it's probably too powerful to be CPU greedy in a power saving mode, although `default` machine and workspace agent start was considerably slower. For instance, deployment of ide.war for ws-agent was completed in 9 seconds, vs 40 seconds in a power saving mode.
