### ISSUE TITLE
Rename of workspace prevent its start

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2538]
After renaming of workspace it is not possible to start that workspace.

**Reproduction Steps:**
1. Create new Workspace from stack
2. Check that it starts well
3. Open swagger
4. Get workspace object
5. Change name in workspace object
6. Update workspace with swagger
7. Open UD
8. Start renamed workspace

**Expected behavior:**

Renamed workspace starts.

**Observed behavior:**

UD hangs. Shows loader forever. Api calls to `http://localhost:8080/wsmaster/api/workspace/che:tetetetererrere` returns 404 with message `Workspace with name 'tetetetererrere' in namespace 'che' doesn't exist`

**Che version:**    5.0.0-M3-Snapshot
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12
**Che install:**    native

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by benoitf** [comment]
and if you rename workspace through UD ?

**Comment by garagatyi** [comment]
the same

**Comment by riuvshin** [comment]
seems it is a blocker
