### ISSUE TITLE
UD doesn't show error on workspace opening when IDE opened outside of UD shows

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#2539]
When some error on IDE opening happens in IDE it shows error.
For example bug #2538 leads to next error in IDE opened outside of UD:
![image](https://cloud.githubusercontent.com/assets/1851863/18740304/c25d5d2c-80b1-11e6-8980-9be6cebdef63.png)

But when workspace is opened using UD it shows nothing except loader:
![image](https://cloud.githubusercontent.com/assets/1851863/18740325/dc9be9c4-80b1-11e6-91f6-7346b11ad691.png)

**Reproduction Steps:**

Use steps from #2538 while it is not fixed. Commit ID to use for reproducing later 5c27745b85c5a7e557946dff77a37483c18f4856.

**Expected behavior:**

UD shows an error that workspace can not be opened.

**Observed behavior:**

UD shows loader.

**Che version:**    5.0.0-M3-Snapshot
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12
**Che install:**    native

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ghost** [comment]
Cannot be reproduced with 5.15-SNAPSHOT.

![image](https://user-images.githubusercontent.com/5337267/28059337-9c4a80c2-662c-11e7-9bc5-4fd38f8116be.png)
