### ISSUE TITLE
Workspace "learn more" link in UD is wrong

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2551]
The Learn More link in the UD Workspaces page should point to: https://eclipse-che.readme.io/docs/introduction

https://eclipse-che.readme.io/docs/introduction#workspace-model
<img width="351" alt="screen shot 2016-09-22 at 6 57 11 am" src="https://cloud.githubusercontent.com/assets/7644938/18750907/e6845b76-8091-11e6-8d89-cbfadeff5c5c.png">

**Comment by ashumilova** [comment]
Fixed
