### ISSUE TITLE
Add Doc About Workspace Sharing

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2557]
Will create documentation on how to share your workspace if working with a team. It will have the following structure.

Using Che as an IDE

> Sharing   
> 
> > Setting Up Che as a Server  
> > Export and Import Workspaces   
> > 
> > > Export to File  
> > > Export to Cloud     
> > 
> > Share with Codenvy Factories

**Comment by bmicklea** [comment]
@JamesDrummond I think it's better to put this as "Share" under the Using the IDE section. People probably want to share once they've gotten acclimatized to the IDE.

**Comment by JamesDrummond** [comment]
@bmicklea Edited per your comment.
