### ISSUE TITLE
Create Docker Image to Get CLI

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2559]
Would in make sense to create a simple docker image that downloads and chmods the cli script for the user based on alpine. The ENTRYPOINT script would curl and chmod cli into container /mnt/(che.sh and che.bat). Command would look like 

`docker run -v .:/mnt codenvy/cli`

We could put something in /mnt folder of the Docker image so that if user doesn't mount it will detect the file and tell the user the above syntax.

**Comment by TylerJewell** [comment]
-1

It adds unnecessary usability complexity.  It's ok for people to chmod the script.  We can - in the instructions - make the initial curl script do both download & chmod in a single line.
