### ISSUE TITLE
Question: Using a Docker insecure registry

### ISSUE THREAD

**Issue by Spritekin** [eclipse-che/che#2563]
Does Che allow using an insecure docker registry?

**Comment by ghost** [comment]
@Spritekin yes, you may reference base images from an  insecure registry in your recipes:

`FROM my.insecure.registry:5000/myImage`

**Comment by Spritekin** [comment]
Thanks, but I mean the button "Administration" in the left. It leads to a page with a button 
"Add registry" but it will force a password, so I can't use an insecure registry (no password).

Still, thanks for the info... so a recipe is like a Dockerfile?

**Comment by ddementieva** [comment]
@Spritekin The purpose of adding registry is to use secure registry. 

Yes, recipe is like Dockerfile where you are inheriting some image and adding some components, if necessary.
