### ISSUE TITLE
Performance issue for Che In Che with slow I/O /projects disk

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#2567]
**Use Case** : mount local folder into Eclipse Che workspace (for example che source code)

Operation is done on macOs . So the mount is operated with docker osxfs which result in having slow I/O operations on this disk. Then any operation that may take 5 seconds with SSD host filesystem may take many seconds/minutes for the same operation using osxfs.

I have then analyzed why it takes almost 10+ minutes to boot Eclipse Che + Workspace being ready (and by having all docker images cached, local M2 folder mounted)

I’ve seen that some heavy I/O operations is taking time and I’ve analyzed some of them which are listed below. Note that it should also improve time on Linux and reduce heavy I/O operations

**Reproduction Steps:**

Using macOs or Windows

```
$ git clone https://github.com/eclipse/che
$ cd che
$ che dir up
```

**Expected behavior:**

Boot as fast as possible

**Observed behavior:**

Workspace takes several minutes before being ready with project imported.
## issue 1 : Chown of directory (1minute lost)

https://github.com/eclipse/che/blob/af2f1098d7fafbac8faf463c5672d23d68ec2c80/wsmaster/che-core-api-agent/src/main/resources/agents/scripts/org.eclipse.che.ws-agent.script.sh#L26
`${SUDO} sh -c "chown -R $(id -u -n) /projects"`

(my che folder is using 1.1GB)
`$ docker run -v $HOME/che:/projects/che -v $HOME/.m2:/home/user/.m2 -ti florentbenoit/che-in-che /bin/bash
`
So in my test, we can see that user “user” already own the files

```
user@ac6a5bec360f:/projects$ ls -la
total 8
drwxr-xr-x  3 root root 4096 Sep 22 07:27 .
drwxr-xr-x 60 root root 4096 Sep 22 07:27 ..
drwxr-xr-x 38 user root 1292 Sep 21 14:16 che

```

```
user@ac6a5bec360f:/projects$ id -u -n
user

```

```
user@ac6a5bec360f:/projects$ ls -la che/
total 236
drwxr-xr-x 38 user root  1292 Sep 21 14:16 .
drwxr-xr-x  3 root root  4096 Sep 22 07:27 ..
drwxr--r--  7 user user   238 Sep 21 14:26 .che
drwxr-xr-x  3 user user   102 Sep 21 10:10 .codenvy
-rw-r--r--  1 user root   146 Jun 17 09:01 .dockerignore
drwxr-xr-x 17 user root   578 Sep 22 07:17 .git
-rw-r--r--  1 user user    34 Sep 19 13:42 .gitattributes

```

And here the time that chown operation takes

```
$ date;sh -c "chown -R $(id -u -n) /projects";date
Thu Sep 22 07:30:44 UTC 2016
Thu Sep 22 07:31:45 UTC 2016

```

1mn to change something that is not needed on this case

⇒  Proposed change : Check before using chown ?
## issue 2 : FileTreeWatcher (2mn lost)

When agent is booted, ProjectManager will call startup on File Tree Watcher
https://github.com/eclipse/che/blob/5d267fe305dce3d151baf0c866393fbf733216f2/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectManager.java#L132

Which call walkTreeAndSetupWatches
https://github.com/eclipse/che/blob/5d267fe305dce3d151baf0c866393fbf733216f2/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/impl/file/FileTreeWatcher.java#L168-L179

Time of Workspace Agent to boot with these watches : 2 minutes

```
INFO: che(dir): "[STDOUT] 2016-09-21 14:26:31,048[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler [\"http-nio-4401\"]" 
INFO: che(dir): "[STDOUT] 2016-09-21 14:26:31,055[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 126118 ms" 

```

Time of Workspace Agent to boot without these watches : 10 seconds
`INFO: che(dir): "[STDOUT] 2016-09-21 17:01:48,055[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 9882 ms" 
`

(I've removed call to add filewatchers on this test)

⇒  Proposed change : Optimize, configure, disable these watchers to consume less time when I/O is slow ?
What do we loose without them ?
## issue 3 : Project Types

Booting workspace will call ProjectRegistry initProjects

```
org.eclipse.che.api.project.server.type.ProjectTypeDef.resolveSources(ProjectTypeDef.java:181)
org.eclipse.che.api.project.server.ProjectTypes.addTransient(ProjectTypes.java:125)
org.eclipse.che.api.project.server.RegisteredProject.<init>(RegisteredProject.java:95)
org.eclipse.che.api.project.server.ProjectRegistry.putProject(ProjectRegistry.java:208) org.eclipse.che.api.project.server.ProjectRegistry.initUnconfiguredFolders(ProjectRegistry.java:383)
org.eclipse.che.api.project.server.ProjectRegistry.initProjects(ProjectRegistry.java:103)

```

Then, updating project type will loop as well in the same layers

```
org.eclipse.che.api.project.server.type.ProjectTypeDef.resolveSources(ProjectTypeDef.java:181)
org.eclipse.che.api.project.server.ProjectTypes.addTransient(ProjectTypes.java:125)
org.eclipse.che.api.project.server.RegisteredProject.<init>(RegisteredProject.java:95)
org.eclipse.che.api.project.server.ProjectRegistry.putProject(ProjectRegistry.java:208)
org.eclipse.che.api.project.server.ProjectManager.updateProject(ProjectManager.java:313)
org.eclipse.che.api.project.server.ProjectService.updateProject(ProjectService.java:222)

```

ProjectTypes addTransient method is iterating on all Provider Factory and create new instances each time
https://github.com/eclipse/che/blob/c93bf4d0c2bda003ba6efd92f3fc3d9f9d492cf1/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/type/ProjectTypeDef.java#L181
(so even if factories are handing some caches it won’t help)

⇒ ProjectType does not seem to be optimized
## issue 4 : GitValueProviderFactory (several minutes lost)

When project type is checked on a folder, it will ask Git Project Type to provide values
https://github.com/eclipse/che/blob/c93bf4d0c2bda003ba6efd92f3fc3d9f9d492cf1/wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitValueProviderFactory.java#L58-L70

Then we see that asking for current branch is resulting into
`return Collections.singletonList(gitConnection.status(StatusFormat.LONG).getBranchName());`

So it calls `git status` to get current branch

But git status is iterating on all files

```
    at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:216)
    at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:131)
    at org.eclipse.jgit.util.FileUtils.getFileAttributesPosix(FileUtils.java:689)
    at org.eclipse.jgit.util.FS_POSIX.getAttributes(FS_POSIX.java:258)
    at org.eclipse.jgit.treewalk.FileTreeIterator$FileEntry.<init>(FileTreeIterator.java:365)
    at org.eclipse.jgit.treewalk.FileTreeIterator.entries(FileTreeIterator.java:242)
    at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:227)
    at org.eclipse.jgit.treewalk.FileTreeIterator.createSubtreeIterator(FileTreeIterator.java:233)
    at org.eclipse.jgit.treewalk.AbstractTreeIterator.createSubtreeIterator(AbstractTreeIterator.java:572)
    at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:1196)
    at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:814)
    at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:437)
    at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:377)
    at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:148)
    at org.eclipse.che.git.impl.jgit.JGitStatusImpl.<init>(JGitStatusImpl.java:64)


```

So to get current branch name it took 30seconds

As we call this several times, it may take 5minutes for 10 calls

⇒ Proposed Change : Use getBranchName() of JGitConnection instead of using “status” command to get it

Result is almost immediate
## issue 5 Maven Project Type resolver

We iterate on all folders and go in the Project Types loop iterating again on all factories.
→ slow process

ValueProviderFactories are not cached, knowing we iterate on all folders to get new projects and if value provider are not optimized, it takes a long long time

Also, why do we need to check against git project type for sub folders for example ? 
## Experiments

Note : by hardcoding removal of all the listed operations or rewriting GitProvider, Eclipse Che + Workspace booted + Che updated project comes to < 3 minutes

**Che version:**    5.0.0-M3
**OS and version:** macOs or Windows
**Docker version:** 1.12.1
**Che install:**   docker

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by bmicklea** [comment]
@benoitf is this something you're going to change?  Or should this be assigned to the platform team?

**Comment by benoitf** [comment]
@bmicklea I've worked on issue #4 with PR https://github.com/eclipse/che/pull/2569, for the remaining issues, I would like that to discuss (maybe it's platform and ide team)

**Comment by bmicklea** [comment]
Thanks for the clarification Florent.
