### ISSUE TITLE
Modifiable agent registry

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#2571]
Every codenvy installation and locally launched che must have agent registry. Currently there is a very basic implementation of the [AgentRegistry](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/impl/LocalAgentRegistryImpl.java) with several limitations:
- No storage
- Impossible to add/remove/update agents
- Relying on [launcher](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/AgentLauncher.java)

We need to have a new implementation without limitation mentioned above. 
Consider the case when new agents requires binaries, where they will be located/stored?
Take into account users` permissions.

**Comment by TylerJewell** [comment]
Requirements are clear.  I am not sure on priority for implementation - but we will probably consider it after first release of team capabilities.  It will be interesting to see how we get C/C++ language server.
