### ISSUE TITLE
Problems with Eclipse Che build.

### ISSUE THREAD

**Issue by friendRU** [eclipse-che/che#2576]
Hello. I've some problems with build an Eclipse Che.

Actually, I want to write a plugin.

When I make 'git clone 5.0.0-M2' and trying to build it, then I receive ["build-log.txt"](https://drive.google.com/file/d/0BwnEmVWu1dYMMzBDcUZKM3JtYlk/view?usp=sharing). Look it.
When I'm trying make 'mvn clean install -Dmaven.test.failure.ignore=true' or something similar, then I receive ["build-log1.txt"](https://drive.google.com/file/d/0BwnEmVWu1dYMRTUtSTYzaVpuTGs/view?usp=sharing). E.t.c.

I can solve some of the problems that arise, but not all. In the end, I get too difficult problems for my understanding.

Maybe I'm doing something wrong?

Che version: 5.0.0-M2
Maven version: Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T20:41:47+04:00)
Maven home: C:\Tools\apache-maven-3.3.9
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: C:\Tools\Java\jdk1.8.0_101\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by friendRU** [comment]
Then I'm also trying to build Che with simple extension.

I downloaded a simple extension from [here](https://github.com/che-samples/che-ide-extension)

1) Add to "..\che\assembly\assembly-ide-war\src\main\resources\org\eclipse\che\ide.IDE.gwt.xml":

```
<module rename-to='_app'>
        <inherits name="examples.MyExtension"/>
</module>
```

2) Add to "..\che\assembly\assembly-ide-war\pom.xml":

```
<dependencyManagement>
    <dependencies>
           <dependency>
              <groupId>org.eclipse.che</groupId>
              <artifactId>che-examples-action</artifactId>
              <version>4.3.0-RC1</version>
           </dependency>
    </dependencies>
 </dependencyManagement>
```

```
<dependencies>
        <dependency>
           <groupId>org.eclipse.che</groupId>
           <artifactId>che-examples-action</artifactId>
        </dependency>
 </dependencies>
```

3) Make `mvn sortpom:sort` from "..\che\assembly\assembly-ide-war\"

4) Make `mvn clean install` from "..\che\"

All I'm doing right?

**Comment by TylerJewell** [comment]
After you have updated your dependencies, then you should try building in `/che/assembly/assembly-main`.  This will generate the full assembly for you.  You don't need to rebuild the entirety of che itself, as that goes into rebuilding every module one at a time, and some of those modules will not build without special utilities.

**Comment by ghost** [comment]
@friendRU just run `mvn clean install` in `/assembly` - this will be enough to recompile modules you have made changes in, as well as build the assembly-main module with binaries.
