### ISSUE TITLE
Cannot Paste commands in Command Definition Window

### ISSUE THREAD

**Issue by wiserweb** [eclipse-che/che#2579]
It seems that nightly build does not allow pasting commands in Command Definition Window.

Discovered issue while following the steps in this comment [https://github.com/eclipse/che/issues/392#issuecomment-185596024] to be able to access a Meteor workspace instance from machine on LAN.

Secondary issue, using Enter key with focus in Command Line field saves changes instead of inserting new line. Workaround is to use concatenated command i.e. cd `${current.project.path} && meteor`

**Reproduction Steps:**
1. Create CMD using Command Definition window and attempt to paste command in field
2. Attempt to use Crtl-V and right-click context menu for Paste are not available to user

**Expected behavior:**

Ability to copy/paste command from and into Command Line field.

Ability to insert new line by using Enter key in Command Line field.

**Observed behavior:**

Enter key saves the dialog information.

**Che version:**    nightly
**OS and version:** OSX el Capitain 10.11.6
**Docker version:** Docker version 1.12.1, build 23cf638
**Che install:**    Docker 

**Additional information:**

Related issue... When clicked the preview url [192.168.1.111:32736] that is created/outputed does not open a browser window with the URL. It opens a about:blank window. The preview URL must be manually entered into browser window to access Meteor project after successful build.
- Problem started happening recently, didn't happen in an older version of Che: N/A
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ghost** [comment]
@wiserweb I have just run Che nightly on Windows 8 and **can** copy and paste in the CMD widget. I wonder if this is a Mac specificissue.

> Secondary issue, using Enter key with focus in Command Line field saves changes instead of inserting new line.

This is expected behavior.

> When clicked the preview url [192.168.1.111:32736] that is created/outputed does not open a browser window with the URL. It opens a about:blank window. 

I used the following macro is my command preview URL - `http://${server.port.8080}` and it worked.
