### ISSUE TITLE
How to specify port for previewing Meteor projects

### ISSUE THREAD

**Issue by wiserweb** [eclipse-che/che#2580]
Following this guide [https://github.com/eclipse/che/issues/392#issuecomment-185596024] the result in the run pane is as follows:

```
cd /projects/todos && meteor
preview:192.168.1.111:33797

[[[[[ /projects/todos ]]]]]

=> Started proxy.
=> Started MongoDB.
[34mW20160923-16:53:25.298(0)? (STDERR) [39m[35mNote: you are using a pure-JavaScript implementation of bcrypt.[39m
[34mW20160923-16:53:25.384(0)? (STDERR) [39m[35mWhile this implementation will work correctly, it is known to be[39m
[34mW20160923-16:53:25.385(0)? (STDERR) [39m[35mapproximately three times slower than the native implementation.[39m
[34mW20160923-16:53:25.385(0)? (STDERR) [39m[35mIn order to use the native implementation instead, run[39m
[34mW20160923-16:53:25.385(0)? (STDERR) [39m[35m[39m
[34mW20160923-16:53:25.386(0)? (STDERR) [39m[35m  meteor npm install --save bcrypt[39m
[34mW20160923-16:53:25.386(0)? (STDERR) [39m[35m[39m
[34mW20160923-16:53:25.387(0)? (STDERR) [39m[35min the root directory of your application.[39m
=> Started your app.

=> App running at: http://localhost:3000/
[dev-machine] => It looks like a simple tweak to your system's configuration will make many
[dev-machine]    tools (including this Meteor command) more efficient. To learn more, see
[dev-machine]    https://github.com/meteor/meteor/wiki/File-Change-Watcher-Efficiency
```

The app can be accessed at the generated preview IP:PORT, i.e. 192.168.1.111:33797.

How does one explicitly specify which port that app will be accessible on?

Use case: Have two apps communicate to each other via APIs. 

i.e. One app expected on port 3200 other app on port 3000. This way API calls can be performed on known ports until application is pushed to production where they use domain name resolution.

**Reproduction Steps:**
1. Issue run command following this guide [https://github.com/eclipse/che/issues/392#issuecomment-185596024]

**Expected behavior:**

Ability to explicitly specify the port that will be used when the app is run.

i.e. One app expected on port 3200 other app on port 3000. This way API calls can be performed on known ports until application is pushed to production where they use domain name resolution.

**Observed behavior:**

The preview Port number appears to be generated randomly.

*_Che version: nightly
*_OS and version: OSX el Capitan 10.11.6
*_Docker version: Docker version 1.12.1, build 23cf638
*_Che install: Docker

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: N/A
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
Docker does not make that possible today.

Inside of your container - the port may be exposed as 3000, but docker transforms that port onto the ephemeral port range. There is no way to pre-determine which port that will be.  This allows for a single workspace to advertise many different services in different containers on different ports, and they will not conflict with one another.

Please track other issues related to "hiding ports" or tunneling Che / Codenvy through a single port. There are 2-3 of these topics with very long threads explaining why.  It's a long lived epic, but maybe in the future we will embed a capability inside of Che where it includes its own reverse proxy, where everything going out of che will be mapped to a single port.  And then incoming traffic will be routed into the proxy for translation to the proper internal port.

**Comment by TylerJewell** [comment]
https://github.com/eclipse/che/issues/1560

**Comment by wiserweb** [comment]
@TylerJewell  Thanks for the link. I must of missed that thread when I was searching the issues.

Docker does have its downsides I guess. This will unfortunately be a show stopper for my team. We need ability to run a few different instances on known ports as we're using micro-service architecture. If we cannot know what the ports will be the next time the project is run it will be chaotic.

Short of an internal proxy (which will likely have its own issues) I suppose the workaround would be to somehow load eclipse che in virtual machines outside of docker containers. This is how cloud9 is doing it and it reduces the networking complexity.

In meantime I will watch the other thread for any new developments.

**Comment by TylerJewell** [comment]
You lose the ability to make workspaces movable from location to location without Docker.  That makes cloud9's SDK just an SDK for a browser IDE.  It's not responsible for actually managing the workspace the way we do - with injected agents, portable workspaces, and total ws isolation.  We may implement a concept of localhost workspaces where docker isn't allowed - like c9, but we fundamentally think that creates more problems than solutions it solves.

**Comment by wiserweb** [comment]
Well, while portability of workspaces is a nice to have feature, I'm not certain it is a killer feature. With cloud instances today you can snapshot your machine and restore its state. Also, if you have a startup script you can have your Openstack instances run the script after they are created. Effectively, this gives you consistent environment that are just as portable as docker without the networking restrictions of docker.

I'm not claiming that c9 is superior to che, or vice versa, it's just that I cannot see a simple way to work on micro-services with the che stack as it stands as there is the control that belongs to the programmer is relegated to a docker's random port assignment.

I don't see any benefit to having this ability removed. I fail to see what one is gaining in exchange for surrendering control over their network port controls.

**Comment by TylerJewell** [comment]
Workspace portability is the fundamental underpinning of Che. It's the necessary part that enables workspaces to move from desktop <> cloud and back. It will also be what allows for pure offline mode. The Dockerfile & composefile syntax, exposed within stacks is what allows users and other ISV providers to version-control their runtime.

Writing a script is not necessarily portable between different OS. But encoding the runtime for a workspace inside of compose file offers a lot of configuration control.  It's kind of like Vagrant, but even Vagrant only exposes certain VM elements.

**Comment by wiserweb** [comment]
Of course you can do that without docker using a VM. Portability is built-into openstack and AWS. You can export your machine and import it into virtualbox or vmware, and import in once more into openstack. But you wouldn't normally do this for an OS state. You would most likely do this because you have specific data on the instance that wasn't generated by a script. It's quicker to just start a new instance in the the cloud and run your script. Takes 5 minutes on a typical droplet. No need to spend any energy dealing with networking details, proxies, ip tables or any of that stuff.

Dockerfiles must do and must account for the different OS nuances. Perfect example is Debian and Ubuntu. One can't use the same dockerfile expecting it to work on both systems unless care was taken to create it in such as way.  Both docker and shell script will have to account for their different packages. This is a moot point.

At the end of the day a dockerfile is a shell script with prefixes which provide entry points for the docker logic to occur. That is all.

Meantime all this effort to get docker instances working and you lose control over networking. It's not worth it. Then you have also created another surface attack layer. So you end up duplicating work without any net benefits.

I see docker as useful for certain thing when deployed directly on the cloud. For example meteor-up uses docker images for deployment which scales to N nodes.

**Comment by TylerJewell** [comment]
Thanks for the thoughts.  

The Che system does not really require Docker.  The workspace is dependent upon an environment which can be running / stopped / etc.  This machine layer is pluggable and there is an SPI for it. While Docker is the out of the box configuration, we have also done an implementation of SSH.  A vagrant provider could be implemented for it, or maybe even macmini for example.  We have a well structured set of lifecycle events that define how machines can be plugged in.  The localhost machines implementation we eventually do would be one approach.

So, this is open source, perhaps you should provide a VM-machine implementation as a pull request for others to consider.

**Comment by wiserweb** [comment]
You're welcome. The support I received so far was excellent FYI. So this is a big plus for this project.

I get what you're saying. I don't doubt that che's architecture is flexible and well intended. All of those good intentions do not necessarily translate into something **easily** useable for the developers though. For instance node.js projects that require defined ports are not feasible at this current junction. Is it node's fault or docker's fault. It's not a blame thing, it's more of choosing the right tool for the jobsite.

I think that using cloud IDE is the way to go. This is the killer feature that got me to try che. Simply having a window/project open on one device, walking over to the next and continuing where one left off it a huge time saver. If you add up all the hours just opening and closing your IDE, setting up your tabs and pushing and pulling to the repo these amount to significant time that could be otherwise used for actual development.

If I had more time I would probably consider proving a VM-machine implementation but that probably won't happen since it's out of scope for my deliverable.

I'll leave this in your hands. Perhaps there'll be some way to do this easily in the near future.

**Comment by TylerJewell** [comment]
What project are you working on building with Che right now?

**Comment by wiserweb** [comment]
Meteor based projects are the big ones. Micro-services and just some legacy php/mysql projects that need maintenance.

**Comment by TylerJewell** [comment]
If you are using che to build some other products - and you are thinking of a redistribution, having my company Codenvy understand those scenarios will help. If we can understand where the big commercial opportunities are, and it requires a VM-based machine solution, then it can affect the backlog.

**Comment by wiserweb** [comment]
Sure. 

Well meteor has grown tremendously and is now maturing nicely. At first there were complaints that they were creating their own eco-system but this is no longer a concern. If you look at the community statistics on meteor and look at the repos on github that are meteor based this should confirm what I'm sharing here.

Their support for react, node.sj 5.6, npm integration make them the stack of choice for web, mobile apps and even desktop app.

I think it was recently announced that amazon purchased c9. Who knows where they will take it but I suspect they are trying to capitalize on a cloudification trend of desktop apps.

If you go the vm route you can have pre-build .ova images for common stacks. This would essentially cover all bases.
