### ISSUE TITLE
How to authenticate against bitbucket?

### ISSUE THREAD

**Issue by rajukiran** [eclipse-che/che#2581]
Hi,

When i try to import the project which is there in bitbucket into eclipse-che browser it says..
java.lang.IllegalStateException: Remote repository requires authentication, but no OAuth provider found for this url

I have tried to edit the che.properties file to update the required access tocken.

i'm unable to edit any of the file because no editor is supporting in browser to edit the files.

How do i achieve this?

can anybody help me?

Che Version :4.7.2
Revision :9b093e09dd84ab32
Build Time :2016-09-09 10:26:29

**Comment by rajukiran** [comment]
when i try to use the SUBVERSION under source control to import the project by giving username and password i met another error like ... :

java.lang.IllegalStateException: org.eclipse.che.ide.websocket.rest.exceptions.ServerException: svn: E175011: Unable to connect to a repository at URL 'https://bitbucket.org/username/android' svn: E175011: Repository moved temporarily to 'https://bitbucket.org/account/signin/%3Fnext=/username/android'; please relocate

**Comment by thyeun** [comment]
@rajukiran good day, which OS are you using? and which syntax are you using to run che?

**Comment by rajukiran** [comment]
Welll i'm using ubuntu 14.04 LTS.
I used this steps to setup .. [Local Install](https://www.eclipse.org/che/getting-started/download/)

`$che start`
is the syntax for running my eclipse-che

**Comment by thyeun** [comment]
@rajukiran good day, [here](https://eclipse-che.readme.io/docs/configuration) follow the link than configure your che.properties

**Comment by rajukiran** [comment]
link doesn't have any page..

**Comment by thyeun** [comment]
@rajukiran, sorry mistake, try again the link

**Comment by TylerJewell** [comment]
@jamesdrummond, @ddementieva  - please assist.

**Comment by JamesDrummond** [comment]
@rajukiran OAuth for bitbucket is not supported. Take a look at the issue #1049 and our documentation page on [Git with SSH](https://eclipse-che.readme.io/docs/git#git-with-ssh) for additional information on how to connect bitbucket via SSH. Let us know if you run into any issues.

**Comment by ghost** [comment]
@rajukiran make sure you use SSH URL and setup SSH keys. https will require username/password which is not supported anywhere in the UI.

**Comment by rajukiran** [comment]
Thanks for your concerns. I 'll let you know if i gone through any issues.
