### ISSUE TITLE
Eclipse Che Extension : Sample hello-world extension project Run issue 

### ISSUE THREAD

**Issue by alexanup** [eclipse-che/che#2583]
We have been following the [tutorial](https://eclipse-che.readme.io/v4.7/docs/setup-che-workspace) to get the helloworld github [sample](https://github.com/codenvy/che-tutorials/tree/master/che-tutorial-helloworld-ext) working. However while doing the Run of superdevmode as mentioned in the tutorial gives GWT compilation errors. The output of Run is uploaded at (https://github.com/eclipse/che/files/491083/SuperDevMode_Run_Output.txt).

**Reproduction Steps:**
1. Same steps as explained at [tutorial](https://eclipse-che.readme.io/v4.7/docs/setup-che-workspace) 

**Expected behavior:**

Same outcome as explained at [tutorial](https://eclipse-che.readme.io/v4.7/docs/setup-che-workspace) 

**Observed behavior:** 
[The output is at : [SuperDevMode_Run_Output.txt](https://github.com/eclipse/che/files/491083/SuperDevMode_Run_Output.txt)]

**Che version:**    [Latest as installed by Yatta install]  
**OS and version:** [Windows 10]  
**Docker version:** [As downloaded by Yatta]  
**Che install:**    [Yatta]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [N/A]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

@TylerJewell This issue is created as per your request at [https://github.com/codenvy/codenvy/issues/756#issuecomment-247613780](url)

**Comment by TylerJewell** [comment]
@alexanup - does this issue also happen if you run Che with the CLI with a local binary? The Yatta installer is doing a number of modifications that are hidden from us.

@slemeur - When did we change our docs to encourage the community that the best way to do development of Che plugins is with the Yatta installer? Our internal engineering organizations don't use that configuration, so seems counter intuitive to propose it as the default option.  It is likely the Yatta configuration is doing configuration items that are not part of our QA and integration tests - leading to the sort of problem reported by @alexanup.

@slemeur @azatsarynnyy @vparfonov @benoitf  @eivantsov @vzhukovskii

**Comment by slemeur** [comment]
Hi @alexanup. 

I think one of the issue you are having is that you are trying to build a sample extension which is very old and which we have not validated with the tutorial you tried. Could you tell me where you found a reference to this sample? It is definitely an old reference and we'll fix that.

I'd recommend you to get started with the following sample:
- https://github.com/eclipse/che/tree/master/samples/sample-plugin-wizard (more advanced one)

Thanks for your input, we will give a look onto your specific issue compilation error.

**Comment by alexanup** [comment]
@TylerJewell - We did not try running that as a local binary yet.

@slemeur - The helloworld-ext sample was picked up as it was been referred in the screen shot of the tutorial.
We shall try the sample you recommended. Do we need to try that with the eclipse Run setup as mentioned in the tutorial or run as a local binary via Che CLI ie as in [building extentions](https://eclipse-che.readme.io/docs/create-and-build-extensions)

@nitingudle @srinisubramanian

**Comment by ghost** [comment]
@slemeur i do not think the tutorial itself is what causes the problem. Most certainly it's superdevmode setup.

```
Errors in 'file:/C:/Development/eclipse-che-developer/workspace/che/wsmaster/che-core-api-machine-shared/target/classes/org/eclipse/che/api/machine/shared/dto/DtoServerImpls.java'
               Line 419: No source code is available for type org.eclipse.che.dto.server.JsonSerializable; did you forget to inherit a required module?
               Line 545: No source code is available for type com.google.gson.JsonElement; did you forget to inherit a required module?
```

I think it's Yatta installer that has performed an incomplete import of the project. There are other threads where users complain about superdevmode on Windows. I failed to reproduce it with Yatta on Ubuntu though.

**Comment by TylerJewell** [comment]
@alexanup - We are reviewing all of the docs and configuration process. We are going to have some better docs around configuring Eclipse IDE without using Yatta.  Also, we have asked Yatta to take a look into their configuration as well.  But I did just do a quick run through of setting up Eclipse IDE without Yatta and did get GWT super dev mode to work.  I have gone through and updated the docs on some areas where there may be confusion - so that things are not misleading.

**Comment by alexanup** [comment]
@TylerJewell - Thanks for the update. You mean to say it works on Windows eclipse environment ? If the document changes your are refering is already made public, pls provide link to the documentation we should be following to setup everything from scratch upto running a sample (ie without Yatta). 

@srinisubramanian @nitingudle

**Comment by TylerJewell** [comment]
We will be making these improvements in our 5.0 branch - https://eclipse-che.readme.io/v5.0-M3/docs/setup-che-workspace.

**Comment by alexanup** [comment]
@TylerJewell  - look like the https://eclipse-che.readme.io/v5.0-M3/docs/setup-che-workspace has gone offline or disabled. Could you check and enable it back or provide a PDF copy ?

@nitingudleunvired @vicky-unvired

**Comment by TylerJewell** [comment]
The version label changed - there is a version selector in the upper corner of docs.

https://eclipse-che.readme.io/v5.0/docs/setup-che-workspace

**Comment by slemeur** [comment]
The document has been updated with step by step guide in order to setup a Che workspace in Eclipse Neon - without using the Yatta Installer. 

@alexanup : We are supposing that the setup of the workspace you had, was missing few pieces. Would you please give another try, by following this procedure to configure Eclipse from scratch?

**Comment by alexanup** [comment]
@slemeur - Thanks, we shall attempt and get back..

**Comment by alexanup** [comment]
@slemeur We are stuck at this issue in the maven build process. Pls find the attached build out put with Error on npm at the end.
[MavenBuildOutput.txt](https://github.com/eclipse/che/files/502199/MavenBuildOutput.txt)

**Comment by slemeur** [comment]
The error is meaning that it does not found "npm" properly installed. Either:
1- NodeJS is not installed properly
2- Environment variables for npm are not properly seen by Eclipse.

In the case 2, you should try by configuring the 'PATH' environment variable with the build command itself.

![screen shot 2016-09-29 at 16 36 55](https://cloud.githubusercontent.com/assets/1636769/18982143/2db5cf7c-86e4-11e6-962d-c159e83f6403.png)

**Comment by alexanup** [comment]
@slemeur - we went past the issue as per your guidance. Now were are stuck on another. The DEBUG output attached. The env command could not be executed inside. Could you provide some clue ?
Its Ubuntu 16.04 LTS VM.

[BuildOutput.txt](https://github.com/eclipse/che/files/502756/BuildOutput.txt)

**Comment by slemeur** [comment]
It's failing to execute goal org.apache.maven.plugins:maven-patch-plugin:1.1.1:apply while building Orion editor. This is weird. 

Could you tell me what is the command you used to build Che from Eclipse IDE? 

Make sure you are doing a `clean install`

**Comment by nitingudleunvired** [comment]
@slemeur Here is a snap of config

![image](https://cloud.githubusercontent.com/assets/22521564/18990403/3f3596e2-872f-11e6-999b-93cf5faf2f2d.png)

**Comment by slemeur** [comment]
Weird.

Which version of the JDK you have installed? 

Similar to the issue with NPM, you could try by adding '$JAVA_HOME' on the environment variables of the command.

**Comment by nitingudleunvired** [comment]
@slemeur Same result after adding $JAVA_HOME on the environment variables, check once, is correct ?

![image](https://cloud.githubusercontent.com/assets/22521564/18991039/b3c3473a-8733-11e6-9a81-2d64a6ee9884.png)

**Comment by slemeur** [comment]
It seems okay.

To be sure of the configuration of those environment variables, you could:
1. do `echo $JAVA_HOME` and `echo $PATH` in a terminal 
2. should have the same values in Eclipse

Maybe you could try to do a `mvn clean` before the command you are trying to configure. 

Have you got `patch` tool installed? http://savannah.gnu.org/projects/patch/  and https://maven.apache.org/plugins/maven-patch-plugin/

Alternatively, you could skip the build of this module (just to pass over this issue), by adding 
`-pl ‘che-plugin-orion-editor’`to your command

@eivantsov : any other suggestion?

**Comment by slemeur** [comment]
Could you check that you have the tool `env` installed? 
In a terminal execute the following command: `which env`

**Comment by nitingudleunvired** [comment]
Hi @slemeur Maven build is successful this time.
Now we trying step 8 of "[Eclipse IDE - Neon Installer](https://eclipse-che.readme.io/v5.0/docs/setup-che-workspace#eclipse-ide-neon-installer)"
Installed docker as explained in  "[Usage: Docker Launcher](https://eclipse-che.readme.io/v5.0/docs/usage-docker#local-eclipse-che-binaries)" 
Subsequently trying to run "[Local Eclipse Che Binaries](https://eclipse-che.readme.io/v5.0/docs/usage-docker#local-eclipse-che-binaries)" and this the output (error) 

---

sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e CHE_LOCAL_BINARY=/home/osboxes/git/che/assembly eclipse/che start
Unable to find image 'eclipse/che:latest' locally
latest: Pulling from eclipse/che

e110a4a17941: Pull complete 
495e4dd69a48: Pull complete 
2df88a24dd1e: Pull complete 
b392ee29baf9: Pull complete 
671cf68ea970: Pull complete 
e36174fcbf93: Pull complete 
Digest: sha256:571fc886ffd823e68420a6435e11cbcafd6cfc1617ac443341f9b4eb5051fd66
Status: Downloaded newer image for eclipse/che:latest
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
c0cb142e4345: Pulling fs layer
c0cb142e4345: Verifying Checksum
c0cb142e4345: Download complete
c0cb142e4345: Pull complete
Digest: sha256:ca7b185775966003d38ccbd9bba822fb570766e4bb69292ac23490f36f8a742e
Status: Downloaded newer image for alpine:latest
INFO: ECLIPSE CHE: Pulling image codenvy/che-server:latest
latest: Pulling from codenvy/che-server
e110a4a17941: Already exists
87de885dae11: Pulling fs layer
dcf05c63220c: Pulling fs layer
87de885dae11: Verifying Checksum
87de885dae11: Download complete
87de885dae11: Pull complete
dcf05c63220c: Verifying Checksum
dcf05c63220c: Download complete
dcf05c63220c: Pull complete
Digest: sha256:6f9335d09cca87d499cd95bf1dd360d9bc7a70364c7871de92348d4757c59903
Status: Downloaded newer image for codenvy/che-server:latest

INFO: ECLIPSE CHE: Starting container...
time="2016-10-04T11:29:21Z" level=fatal msg="Error response from daemon: oci runtime error: exec: \"/home/user/che/bin/che.sh\": stat /home/user/che/bin/che.sh: no such file or directory" 

@alexanup @vicky-unvired

**Comment by TylerJewell** [comment]
You did not provide a good directory for the CHE_LOCAL_BINARY variable.  It must not be pointing to the root of the assembly you created.  The assembly root must be where the bin dir is.

**Comment by slemeur** [comment]
Yes, you CHE_LOCAL_BINARY should have the following path:
`{workspace-path}\che\assembly\assembly-main\target\eclipse-che-<version>\eclipse-che-<version>`

**Comment by srinisubramanian** [comment]
@slemeur @TylerJewell That helped.  We were able to make progress and the server now starts up.   The UI though is not looking right. Additionally there are some errors.

Please check the attached screenshots and let us know how we can set this right.  Inc are you need remote access or a hangouts call also let me know.   Thanks for your assistance.

![img_05102016_124234](https://cloud.githubusercontent.com/assets/8343179/19104516/8d096faa-8afa-11e6-9a89-9e4c987b8026.png)
![img_05102016_124239](https://cloud.githubusercontent.com/assets/8343179/19104517/8d83e5dc-8afa-11e6-805c-a0bf9a16cffd.png)
![img_05102016_124252](https://cloud.githubusercontent.com/assets/8343179/19104518/8d84970c-8afa-11e6-83bd-1e50ad19f1f9.png)

**Comment by slemeur** [comment]
This is a strange issue. 

In order for us to help you, we would need your javascript console logs and che server logs.
You can get the javascript log from Chrome and to get logs:
When starting your binary, you should have:
INFO: ------------------------------------
INFO: ECLIPSE CHE: CONTAINER STARTING
INFO: ECLIPSE CHE: SERVER BOOTING
**INFO: ECLIPSE CHE: See logs at "docker logs -f che"**
INFO: ECLIPSE CHE: BOOTED AND REACHABLE
INFO: ECLIPSE CHE: http://<your-che-host>:8080
INFO: ------------------------------------

Please check also:
https://eclipse-che.readme.io/v5.0/docs/usage-docker#diagnose-boot-problems

**Comment by slemeur** [comment]
Please reach me at slemeur.at.codenvy.com

**Comment by srinisubramanian** [comment]
JS Console log does not show any errors, file attached.

Docker logs also attached.

[catalina.txt](https://github.com/eclipse/che/files/510619/catalina.txt)
[chrome.txt](https://github.com/eclipse/che/files/510618/chrome.txt)

**Comment by slemeur** [comment]
It seems your source code is based on old version. We did number of improvements in the system since this version - you might be running into an old issue. 

Could you please update your source code to the current master?

**Comment by srinisubramanian** [comment]
We updated to the latest master ().  Still issue persists.  Attached docker log and screenshot where some improvement is there :)

Docker command: sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e CHE_LOCAL_BINARY=/home/osboxes/git/che/assembly/assembly-main/target/eclipse-che-5.0.0-M5-SNAPSHOT/eclipse-che-5.0.0-M5-SNAPSHOT -e CHE_HOST_IP=192.168.98.76 eclipse/che start

[catalina2.txt](https://github.com/eclipse/che/files/511211/catalina2.txt)
![img_05102016_183630](https://cloud.githubusercontent.com/assets/8343179/19114258/da25e1c6-8b2a-11e6-9582-f34215348f8f.png)

**Comment by ghost** [comment]
@srinisubramanian can you host your binaries somewhere so that I can download and try myself? Looks like some Javascript issues even though it's an incognito tab.

If you have your source code hosted as a git repo that will work too - I will compile it myself.

**Comment by srinisubramanian** [comment]
@eivantsov I did update @TylerJewell and @slemeur on our progress but forgot to update the issue. 

Basically we gave up on running this on Windows and tried with Ubuntu on a VirtualBox VM which is where we had the above issues.  Finally we tried again on a barebones Ubuntu machine and the whole process went off without a hitch.  So Eclipse on Windows/VBox seems to be the issue in case you want to try to reproduce it.

No changes to the standard source code but looks like the issue was that on Windows and VBox somehow the Maven or project setup is creating issues in an Eclipse environment.

For now you can close this issue, it will be good though if the team can figure out support for Eclipse on Windows (for now we are going ahead with Ubuntu and starting on the plugins)

Thanks

**Comment by TylerJewell** [comment]
Can you share more details about what you did with Windows on VirtualBox?  vbox on windows has some limitations about how you can share files with volume mounts. So if you were doing something in that area, it's common to run into issues.  Docker for Windows, though, does not have this same problem.

**Comment by slemeur** [comment]
Closing this issue as we went over the troubles.
