### ISSUE TITLE
Running the docker launcher with MACHINE_WS_AGENT_MAX_START_TIME_MS has no effect

### ISSUE THREAD

**Issue by PietroBoido** [eclipse-che/che#2584]
Hi,

using -e MACHINE_WS_AGENT_MAX_START_TIME_MS=... does not change the maximum start time.

**Reproduction Steps:**

As per https://eclipse-che.readme.io/docs/usage-docker

docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock  -e MACHINE_WS_AGENT_MAX_START_TIME_MS=400000 eclipse/che start

**Expected behavior:**

The the workspace master waits 400000 ms for the agent to start up.

**Observed behavior:**

The workspace master waits for 60 seconds, which is the value found in the configuration file.

2016-09-24 14:59:29,523[kspaceManager-0]  [INFO ] [c.p.d.m.DockerInstanceProvider 591]  - Machine with id 'machinebcbjahtuvzjgx3uf' backed by container '9a52691a3dbbea3c37e7b12cc4c66c4dea518b451c676b128a7624b969ede270' has been deployed on node 'localhost'
2016-09-24 15:00:32,426[kspaceManager-0]  [ERROR] [.c.a.a.s.w.WsAgentLauncherImpl 115]  - Fail pinging ws agent. Workspace ID:workspace6m1vvko95m1u8doq. Url:http://10.1.0.1:32794/wsagent/ext/. Timestamp:{}
2016-09-24 15:00:35,293[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 666]    - Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:261) ~[che-core-api-workspace-4.7.2.jar:4.7.2]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$2(WorkspaceManager.java:650) ~[che-core-api-workspace-4.7.2.jar:4.7.2]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-4.7.2.jar:4.7.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_92-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_92-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_92-internal]

**Che version:**   latest 
**OS and version:** Amazon Linux AMI 2016.03  
**Docker version:** 1.11.2  
**Che install:**    Docker container 

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

DEBUG: ---------------------------------------
DEBUG: ---------    DEBUG INFO    ------------
DEBUG: ---------------------------------------
DEBUG: 
DEBUG: ---------  PLATFORM INFO  -------------
DEBUG: DOCKER_INSTALL_TYPE       = native
DEBUG: DOCKER_HOST_OS            = Amazon Linux AMI 2016.03
DEBUG: DOCKER_HOST_IP            = 172.17.0.1
DEBUG: DOCKER_DAEMON_VERSION     = 1.11.2
DEBUG: 
DEBUG: 
DEBUG: --------- CHE INSTANCE INFO  ----------
DEBUG: CHE CONTAINER EXISTS      = YES
DEBUG: CHE CONTAINER STATUS      = running
DEBUG: CHE SERVER STATUS         = running & api reachable
DEBUG: CHE IMAGE                 = codenvy/che-server:latest
DEBUG: CHE SERVER CONTAINER ID   = ba17f6797d65
DEBUG: CHE CONF FOLDER           = not set
DEBUG: CHE DATA FOLDER           = /home/user/che/workspaces
DEBUG: CHE USE URL               = http://172.17.0.1:8080
DEBUG: CHE API URL               = http://172.17.0.1:8080/swagger
DEBUG: CHE LOGS                  = run `docker logs -f che-server`
DEBUG: 
DEBUG: 
DEBUG: ----  CURRENT COMMAND LINE OPTIONS  ---
DEBUG: CHE_PORT                  = 8080
DEBUG: CHE_VERSION               = latest
DEBUG: CHE_RESTART_POLICY        = no
DEBUG: CHE_USER                  = root
DEBUG: CHE_HOST_IP               = 172.17.0.1
DEBUG: CHE_LOG_LEVEL             = info
DEBUG: CHE_DEBUG_SERVER          = false
DEBUG: CHE_DEBUG_SERVER_PORT     = 8000
DEBUG: CHE_HOSTNAME              = localhost
DEBUG: CHE_DATA_FOLDER           = /home/user/che
DEBUG: CHE_CONF_FOLDER           = not set
DEBUG: CHE_LOCAL_BINARY          = not set
DEBUG: CHE_SERVER_CONTAINER_NAME = che-server
DEBUG: CHE_SERVER_IMAGE_NAME     = codenvy/che-server

**Comment by TylerJewell** [comment]
Hi @pietro-boido - it looks like you used the wrong syntax.

The syntax for configuring Che properties is different for the CLI vs. the docker container. In the docker container, we have some properties which are configured as environment variables and most properties which have to be configured within a che.properties file and then the location of that file passed into the container using CHE_LOCAL_CONF environment variable.

If you use the CLI, however, we also support one-time properties, which you can set as an environment variable. If you set the property as an environment variable, then we create a che.properties file with the right value and then pass it into the container with the right syntax.

Configuring the docker container technique:
https://eclipse-che.readme.io/docs/usage-docker#add-custom-eclipse-che-properties

Configuring one time use properties with CLI:
https://eclipse-che.readme.io/docs/configuration#section-one-time-use-properties

**Comment by PietroBoido** [comment]
Yes, in fact later I tried setting CHE_LOCAL_CONF and it worked.

I must have misunderstood this part of the documentation:

https://eclipse-che.readme.io/docs/usage-docker#environment-variables

> Starting in 4.7, you can also define any property typically loaded from che.properties using an environment variable. che.properties is an internal configuration file that defines advanced ways that Che will configure itself. If an override is not provided by a user, then Che loads the default file. There are dozens of additional configuration parameters available. You can change the default value of a property by passing in a variable that matches the name of the property replacing . with _. For example, you can pass -e CHE_WORKSPACE_STORAGE=<value> to override the location where workspaces are stored.

With my use case it would be easier to just pass the configuration properties as a command line argument, rather than writing a full configuration file.

Thank you!

**Comment by TylerJewell** [comment]
@pietro-boido - I think that the issue related to that particular improvement did not make it into our code base until 5.0.0-M1. So that is probably a mistake. But, in theory, yes, there is also supposed to be a way to configure che.properties using the Docker container.  I didn't indicate it in my note, because I didn't think it had been fully tested and documented.

I haven't tried it myself, but I think the internal server expects CHE_<var>.  So that may be the issue with why it didn't work for you the first time.
