### ISSUE TITLE
Cannot uninstall che in mac?

### ISSUE THREAD

**Issue by shakahub** [eclipse-che/che#259]
How to completely remove che in mac?

Once tomcat process is stopped, a new tomcat process is started at a different pid.

**Comment by TylerJewell** [comment]
On Mac, it should just be deleting the directory that Che was intalled into. 

There isn't anything in Che that has automatic re-starting of Tomcat processes. In your installation, did you set the Che server or che.sh script to be a Mac service that will restart it if the process is killed?

**Comment by TylerJewell** [comment]
Closing issue, unless it continues to repeat - and then please reopen.
