### ISSUE TITLE
Editor does not filter code completion proposals from language server

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#2592]
As visible on the below screenshot, the editor does not filter the completion proposals retrieved from the language server. I would expect to have only the "name" item in the list, but I get a lot more.

![code-completion-filtering](https://cloud.githubusercontent.com/assets/468091/18836038/dc8913e6-8406-11e6-8c10-5d454e55efdd.png)

While for JSON files the completion proposal list is relatively short, for programming language like Java, PHP and others it can be exhaustive. Lack of filtering would make the code completion feature unusable.

Note that the issue is not specific to the JSON editor, but for any editor using a language server (see #1287).

**Reproduction Steps:**
1. Have a build including #2474 
2. Create a `composer.json` file.
3. Start typing a key (like on the screenshot) and invoke code completion.

**Expected behavior:**

The list of completion items is filtered in the editor.

**Observed behavior:**

The list of completion items is not filtered at all.

**Che version:**    build from PR #2474 
**OS and version:** Fedora 24
**Docker version:** 1.10.3 
**Che install:**    local build, started with the `bin/che.sh` script

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by vparfonov** [comment]
Not sure it is bug on client side looks like LS should give as already filtered result. We will take a look

**Comment by kaloyan-raev** [comment]
This is how it works in VS Code. The JSON language server make only context-based filtering. Then it leaves the client to decide how to execute the filtering based on the user input: using startWith, substring or fuzzy matching strategy. This is why the LSP defines the `filterText` property for the `CompletionItem`.

Of course, the language server can decide to implement the text-input filtering itself, but this is not strictly defined by the protocol. Even if the server does it, there is no drawback if the client does it once again - e.g. for displaying the highlighting in the completion proposal window.

BTW, I am almost done on a PR based on the FuzzyMatcher used for the GoToSymbolAction.
