### ISSUE TITLE
After trying to delete predefined stack - message is not clear

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2593]
**Reproduction Steps:**
1. Go to the nav bar -> Stacks 
2. Click on 'Trash' icon of the predefined stack

**Expected behavior:**
The  icon should be disabled/or removed. Or an user should get clear message.
**Observed behavior:**
After clicking on 'delete' icon we get empty error message
![anim](https://cloud.githubusercontent.com/assets/1640058/18838028/96800442-840e-11e6-8b1b-2297029764e6.gif)

**Che version:**  5.0.0-M3-SNAPSHOT
**OS and version:** 
_OS and version:_\* Ubuntu 14.04  
**Docker version:** 1.12.0  
**Che install:**   local bundle

**Comment by riuvshin** [comment]
@ashumilova please take a look
