### ISSUE TITLE
GWT SuperDev Mode command does not work

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#2595]
**Reproduction Steps:**
1. Clone Che
2. Build it
3. Create GWT SDM for Che 
4. Try to star command

**Che version:**   5.0.0-M3

**Comment by vparfonov** [comment]
Main problem for now is to build a correct classpath for SDM command it should contains:
- dependencies as jar
- related modules from opened project as source dependencies 
For example if your GWT application has dependency on some jar and this jar is a part of your project it must be declared as a source dependency in this case changes in this module will be recompiled automatically by SDM .

**Comment by azatsarynnyy** [comment]
Fixed in #6582 but final solution will be proposed as part of #6602, after finishing migrating to the new gwt-maven-plugin.
