### ISSUE TITLE
Error while creating a workspace without projects

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2601]
Misconfiguration of the workspace while creating it without project.
(I recommand to watch the video to better understand the issue)

[bug-create-workspace-without-project.mp4.zip](https://github.com/eclipse/che/files/494951/bug-create-workspace-without-project.mp4.zip)

**Reproduction Steps:**
1. From dashboard, click on "Create workspace" button in the list of recent workspaces.
2. Switch to "Stack library" and select "Debian LS" stack

**Expected behavior:**
The projects fields are empty, and it is possible to create a workspace without a project. 

**Observed behavior:**
The default choices are displayed in the project's fields. It seems they are used while creating the workspace and it raises an error.

See the attached video.

**Che version:**   5.0.0-M4
**Che install:**  Codenvy

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by ghost** [comment]
Once can definitely create and run a workspace with or without projects now.
