### ISSUE TITLE
Project import/creation performance issues

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#2602]
Import or creation of a project that contains a great amount of files causes huge lags on macOS.

**Reproduction Steps:**
1. Go to project menu
2. Import a Eclipse Che project
3. Be patient 

**Expected behavior:**

Project import should be performed for a moderate amount of time

**Observed behavior:**

Project import takes too much time or does not finish at all

**Che version:**    5.0.0-M3
**OS and version:**  macOS

**Additional information:**
This happens only on macOS and only with really large projects
- Problem started happening recently, didn't happen in an older version of Che: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by benoitf** [comment]
it's related to https://github.com/eclipse/che/issues/2567 no ?

**Comment by dkulieshov** [comment]
@benoitf sorry for the delay I guess there is a problem with my notification filters, and yes, I think you are absolutely right, it is most likely related to the mentioned issue.
