### ISSUE TITLE
Unexpected rewriting content of stack after renaming

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2603]
**Reproduction Steps:**
See screencast:
**Expected behavior:**
Stack should be saved
**Observed behavior:**
User stack is overwritten
![anim](https://cloud.githubusercontent.com/assets/1640058/18870724/b56f5f2c-84ba-11e6-94c2-580d18e457f5.gif)

_**Observed behavior:_*
The recipe is not displayed.

**Codenvy version:** 5.0.0-M3
**OS and version:** 14.04

**Comment by riuvshin** [comment]
@ashumilova please take a look

**Comment by bmicklea** [comment]
Closing this because it will be fixed by #2734
