### ISSUE TITLE
Running npm commands freeze the IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2608]
Running npm commands freeze the IDE.

While doing an 'npm install' a lot of dependencies are retrieved and new files created inside of the workspaces. The IDE is triggering those file changes and trying to re-index the content of the workspace. 

This behavior is freezing the IDE impacting the performances. 
It basically makes the product not usable for a NodeJS project.

Discussed with @dkuleshov , it seems a side effect of the file watcher components. I believe this can be reproduced with other tools and in other situations where a lot of new files are created/modified in the workspace.

See the attached videos.

[ide-freeze-npm-install-small.mp4 2.zip](https://github.com/eclipse/che/files/495406/ide-freeze-npm-install-small.mp4.2.zip)

**Reproduction Steps:**
1. Create a workspace, using the stack https://hub.docker.com/r/codenvy/debian_jdk8_node/
2. Import a sample NodeJS project 'https://github.com/jhipster/jhipster-sample-app'
3. Open a terminal, go into the project folder and execute the command 'npm install'

**Che version:**    5.0.0-M3
**Che install:**    beta.codenvy.com, but true with Che as well.

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by bmicklea** [comment]
@vparfonov please investigate whether there's a workaround that can be used to get people past this.

**Comment by vparfonov** [comment]
@bmicklea we found workaround which allows to fix this specific problem, but looks like its challenge that require more time for investigation

**Comment by bmicklea** [comment]
@vparfonov so this will continue in the next sprint?
