### ISSUE TITLE
Building and skipping tests with default maven goal is failing

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2610]
When developers want to build and skip tests there are few options to do that.

By default, IDEs (like Eclipse or IntelliJ) are using the following goal:
_-Dmaven.test.skip=true_

<img width="1678" alt="screen shot 2016-09-27 at 15 04 23" src="https://cloud.githubusercontent.com/assets/1636769/18874864/bb42b80a-84c3-11e6-8cc1-d7d0fd91ec02.png">

But in our case, the build is failing (seems the way we configured the dependencies into our pom.xml)

In order to be able do build Che user can't use the default configuration used by Maven plugins in IDE. 

**Steps to reproduce:**
1. Inside of a terminal
   $ cd che/wsmaster/che-core-api-factory 
   $ mvn clean install -Dmaven.test.skip=true

The outputs:
INFO] --- maven-dependency-plugin:2.10:analyze-only (analyze) @ che-core-api-factory ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.eclipse.che.core:che-core-api-machine-shared:jar:5.0.0-M3-SNAPSHOT:compile
[WARNING]    org.eclipse.che.core:che-core-api-machine:jar:5.0.0-M3-SNAPSHOT:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

-DskipTests seems to be workaround but other developers could also use -Dmaven.test.skip=true, from the terminal but also from integrated Maven plugin in IDEs.
1. Inside of Eclipse
   <img width="1678" alt="screen shot 2016-09-27 at 15 04 23" src="https://cloud.githubusercontent.com/assets/1636769/18874864/bb42b80a-84c3-11e6-8cc1-d7d0fd91ec02.png">

**Che version:**    5.0.0-M4

**Comment by skabashnyuk** [comment]
In some cases we are generating test jars to be able to reuse it in other modules. When you use `-Dmaven.test.skip=true` this jars are not generated and if you do not  compile this jars before, you'll fail. To correctly build and skip test use `-DskipTests` flag instead

**Comment by benoitf** [comment]
@skabashnyuk they won't be downloaded from maven repository if not generated locally ?
also from what I see, it's Eclipse itself that is using -Dmaven.test.skip=true option when checkbox is enabled to it's more a bug to me than a question (Eclipse user using this option will have a failed build, not great as first approach)

**Comment by skabashnyuk** [comment]
>@skabashnyuk they won't be downloaded from maven repository if not generated locally ?
AFAIK no.

**Comment by skabashnyuk** [comment]
> @skabashnyuk they won't be downloaded from maven repository if not generated locally ?

I don't know

**Comment by slemeur** [comment]
@skabashnyuk This is a minor issue, but it is a big pain in the ass for anyone who would like to get the Che's sources built with default Maven plugin from an IDE.
