### ISSUE TITLE
C# icon has word "c#" which makes it seem like a duplicate

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2614]
**Expected behavior:**
C# label should be  only one

**Observed behavior:**
The label is duplicated
![selection_018](https://cloud.githubusercontent.com/assets/1640058/18876809/bfc2b014-84d3-11e6-9449-f4a1c1b97912.png)

**Codenvy version:** 5.0.0-M3
**OS and version:** 14.04

**Comment by JamesDrummond** [comment]
@slemeur Please provide Vitalii icon.

**Comment by slemeur** [comment]
Could you please try with the following one.

[c-sharp-icon.svg.zip](https://github.com/eclipse/che/files/568473/c-sharp-icon.svg.zip)

**Comment by bmicklea** [comment]
@vparfonov please set status label

**Comment by vparfonov** [comment]
![che-2614](https://cloud.githubusercontent.com/assets/1636592/20559940/97de04a8-b17f-11e6-9566-ef98a62a17ab.png)
