### ISSUE TITLE
Improve Find capabilities in IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2617]
Provide the ability to do a Find without case sensitive.

![screen shot 2016-09-27 at 16 01 19](https://cloud.githubusercontent.com/assets/1636769/18878432/d24a456a-84d0-11e6-93e6-cfe630b6af5a.png)

We need to add a small checkbox to enable/disable the case sensitive option.

![screen shot 2016-09-27 at 16 01 12](https://cloud.githubusercontent.com/assets/1636769/18878439/d9bb0064-84d0-11e6-85b0-be16e26d90be.png)

**Che version:**   5.0.0-M3

**Comment by akervern** [comment]
The search can also be improved using some common tricks that can be found on IntelliJ or Github repository search:
- Exclude some files depending of the project type; for instance in case of a Maven one: files inside `target` folder are mainly pointless noise
- Using CamelHumps / snake syntax for file resolution
- Wildcard support

**Comment by vitaliy-guliy** [comment]
Also improve popup with the search result:
- make it smaller
- add scroll bars
- add key navigation

![navigate to file](https://cloud.githubusercontent.com/assets/1655894/21674433/6400c4a8-d336-11e6-8c18-bf60582f78c9.png)

**Comment by vitaliy-guliy** [comment]
There is a similar one https://github.com/codenvy/codenvy/issues/1038

**Comment by vitaliy-guliy** [comment]
The result

![navigatetofile](https://cloud.githubusercontent.com/assets/1655894/22106968/05e124b6-de54-11e6-8289-2bf3a03aae4b.png)
