### ISSUE TITLE
Eclipse Che che.sh script not compatible with bash

### ISSUE THREAD

**Issue by tikaa** [eclipse-che/che#262]
When I try to run che.sh as sh che.sh it fails. further it gives syntax errors on all function declarations in the script file that I had to change all function declarations in the script

from 

function ABC {}

to

ABC () {}

**Comment by TylerJewell** [comment]
Can you provide the Linux operation system, its version, and the version of bash.  Che has been tested on latest versions of Ubuntu, CentOS, Mac, and a variety of versions of Windows.  On Mac & Windows, Docker Toolbox installs Git Bash, and we are tested against that, too.  So it may be a compliance issue.

**Comment by tikaa** [comment]
Yes it could be a compliance issue. Appreciate your prompt reply!

Ubuntu 14.04

GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

Awanthika Senarath
Software Engineer, WSO2 Inc.
Mobile: +94717681791

**Comment by TylerJewell** [comment]
Ok, bash version is ok.  This is a POSIX compatibility issue.
http://stackoverflow.com/questions/4654700/what-are-the-parentheses-used-for-in-a-bash-shell-script-function-definition-lik

Opened internal tracking ticket
https://jira.codenvycorp.com/browse/IDEX-4272

**Comment by griffinwebnet** [comment]
interesting. im on 14.04 as well yet i have no issues running the script

**Comment by garagatyi** [comment]
@griffinwebnet  It's because POSIX compliant mode is disabled in your system.
Try add `set +o posix` after shebang line and you will have the same issue.

**Comment by TylerJewell** [comment]
@tikaa See this pull request for a fix.
https://github.com/codenvy/che/pull/257

**Comment by garagatyi** [comment]
@TylerJewell After merge PR #257 we can close this issue. WDYT?
