### ISSUE TITLE
Ubuntu 16.04 unable to install Eclipse

### ISSUE THREAD

**Issue by elysium306** [eclipse-che/che#2621]
I tried to install Eclipse to my newly installed Ubuntu 16.04. 

went to the website, followed the steps that was given, 
1. Start Che with Docker
   
   Docker 1.8+ required.
   Docker for Mac requires 1-time setup of loopback device.
   Don't want to install Docker? Use Yatta (requires TOS acceptance) which installs Che and Docker together.

Linux & Mac - Add Our CLI
$ curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > /usr/local/bin/che
$ chmod +x /usr/local/bin/che
view raw
get-che-cli-linux hosted with ❤ by GitHub 

**Expected behavior:** : I assumed it would show up in the dock on the desktop. 

but it said permission denied.

I don't know who denied the permission. 

I could've installed from the software center, but all the comments below was saying Eclipse was outdated. I went to the Eclipse website follow the above steps, and got the above result. 

Please shed some light on this.

**Comment by TylerJewell** [comment]
@elysium306 - are you trying to install the Eclipse IDE (desktop - the older IDE).  Or, are you trying to install Eclipse Che (next-generation developer workspace server and cloud IDE)?  They are diffterent products that share the same foundation (Eclipse), but are different system.  Che is a hosted product that you can run as a server on your desktop, and then access workspaces over a server.

Eclipse IDE is a desktop product that has a desktop installer.

**Comment by ghost** [comment]
@elysium306 can you perhaps share a screenshot of what you have done and what error you have got?

**Comment by elysium306** [comment]
Hello @eivantsov 

I am new to Linux, I was trying to download Eclipse to practice my coding.

1> I know Eclipse is a pretty good IDE tool, all I was trying to do is to download some IDE that works well plus, doesn't take up too much processing power. 

2> I am not sure if I was trying to download/install the correct software ... 

3> What might've been the issue that caused the error message ? 

Thank you very much for your reply.  

![screenshot from 2016-09-27 22-38-51](https://cloud.githubusercontent.com/assets/22020806/18901921/d4144ab6-8503-11e6-8dfd-2f0395970087.png)
![screenshot from 2016-09-27 22-39-33](https://cloud.githubusercontent.com/assets/22020806/18901920/d41314f2-8503-11e6-911f-fe11325df8d4.png)

##### ERROR MESSAGE

admin@admin:~$ curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > /usr/local/bin/che
bash: /usr/local/bin/che: Permission denied
admin@admin:~$ chmod +x /usr/local/bin/che
chmod: cannot access '/usr/local/bin/che': No such file or directory
admin@admin:~$

**Comment by elysium306** [comment]
@TylerJewell : Hello Tyler. Thank you for your reply very much! 

I was just trying to install a bit LATER version of Eclipse IDE to practice coding. I got, still do. the impression that Eclipse Che maybe the latest version of Eclipse IDE. If I'm mistaken then I just need an up-to-date IDE :) 

Kind Regards

**Comment by thyeun** [comment]
@elysium306, che are very good for coding practice, actually you are on the correct way to run che on Ubuntu 16.04, just before that, you have to install docker. 

And you need to include "sudo" to run the syntax of CLI (command line interface), to avoid permission denied.

**Comment by elysium306** [comment]
@thyeun : Thank you for your confirming the direction for me. Now I had  a different challenge to install Docker. at this point I think maybe I am new to the Ubuntu world, I might be just not doing the things right. I'll install the dockers and try to install the eclipse again.

Thank you

**Comment by thyeun** [comment]
@elysium306 good day, if you need anything that related with Che, here is the right place for you, and all the members here are all willing to help, and you might learn one or two extra things (like linux CLI, docker way of doing things and etc from the members here). 

And lastly hope you enjoy coding with Che!!!!

**Comment by TylerJewell** [comment]
@elysium306 - of course you will absolutely love Eclipse Che - it is the future.  However, if you just wanted  the latest Eclipse IDE, you would click on the Neon button for your screen shot.

**Comment by alex-salnikov** [comment]
Still, regarding "/usr/local/bin/che: Permission denied" - following helped me:
sudo wget -O /usr/local/bin/che https://raw.githubusercontent.com/eclipse/che/master/che.sh
sudo chmod +x /usr/local/bin/che

**Comment by TylerJewell** [comment]
Glad you are enjoying it.  Thanks for being a user!
