### ISSUE TITLE
Status of workspace displayed incorrectly on the navbar panel after creating snapshot

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2622]
**Reproduction Steps:**
1. Create any workspace and run it
2. Create snapshot
![ws_status](https://cloud.githubusercontent.com/assets/8051404/18905210/ba496122-856a-11e6-941d-5e3f50a0fe2b.gif)

**Observed behavior:**
Status indicates that the workspace was stopped but it still running.

**Che version:**    5.0.0-M3-SNAPSHOT
**OS and version:** Ubuntu 
**Docker version:** 1.11.2
**Che install:**  local

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by mmorhun** [comment]
Also, after snapshot creation button "Stop" is changed to "Run" in dashboard (if dashboard is open in another tab).
