### ISSUE TITLE
IDE is trying to get projects while the workspace is not started

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2629]
The workspace is not yet started, but the IDE is displaying a loader indicating that it is trying to get the projects.

![screen shot 2016-09-28 at 14 21 53](https://cloud.githubusercontent.com/assets/1636769/18913297/6602ebac-8587-11e6-8aee-aee153fff5cf.png)

Either it is a side effect of the changes that we introduced with the new loader - or it is a wrong sequencing of the event. 

Getting the project should not be triggered before the workspace is fully started.

**Che version:**    5.0.0-M4

**Comment by riuvshin** [comment]
moved to M8
