### ISSUE TITLE
Update dependency failed

### ISSUE THREAD

**Issue by jcao219** [eclipse-che/che#263]
Right now this is happening:

http://i.imgur.com/EfxtBH5.png

There should be a way to know what's causing the failure.

**Comment by ghost** [comment]
There should be Outputs panel in the bottom. Any errors there? It is possible that Maven failed to resolve the dependencies that you have added.

**Comment by jcao219** [comment]
It turns out, one of the dependencies did fail to resolve.

I don't think there was an Outputs panel in the bottom.  I restarted the Che server and things worked fine afterwards.
