### ISSUE TITLE
Leak of open file descriptors

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2633]
[Short description of problem here]

**Reproduction Steps:**
A lot of start and stop of new processes.

**Expected behavior:**
All opened files descriptors will be closed
**Observed behavior:**

Each time we start new process with  MachineProcessManager.exec 
method we open a new file with process output. But this descriptor
never released back. I'm proposing to close it and delete output file
during process termination.

**Comment by skryzhny** [comment]
We definitely need to fix that.
I have several monitoring system warning already.
I used to restart codenvy service.
It is a problem for on-prem installations.

**Comment by mmorhun** [comment]
Actually, deletion of output file doesn't release file descriptor. And I think, that log file shouldn't be deleted after process termination. May be after workspace stop, but it is clean up problem, which doesn't concerned with leaking of file descriptors.

**Comment by mmorhun** [comment]
Fixed
