### ISSUE TITLE
Cover by selenium tests the Bitnamy stacks from dashboars

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2636]
**Test examples for checking:**
Bitnami Codeigniter
Bitnami Express
Bitnami Laravel
Bitnami Play for Java
Bitnami Rails
Bitnami Swift
Bitnami Symfony

**Test plan for each sample:** https://docs.google.com/spreadsheets/d/1cCMH_o4CwrfKYmPWqf6C-qUJKNqfQ7jhEnjwIaDnTCQ/edit#gid=0

**Comment by AndreyChizhikov** [comment]
Moved to QA
