### ISSUE TITLE
Upgrade Node.js version on the node.js stacks on more recent LTS versions

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#2642]
currently, the node.js Stack only feature nvm and Node 0.12 but the following version cannot read arrow functions on javaScript files that has this.

a example of this would be a the following:

`bot.on("message" m =>{});`

although the following is valid JS code. Node 0.12 cannot read arrow functions which makes Node.js developers that works on more latest versions struggling to test on a Che workspace.

**Proposed Changes**
- Upgrade Node.js versions to a more latest LTS release (ie, at this time of writing, 4.x.x is the LTS version)

**Comment by TylerJewell** [comment]
Cool.  Please consider sending us a pull request for the updated stack.  The recipes are saved in /eclipse/che-dockerfiles repository.

**Comment by benoitf** [comment]
https://github.com/codenvy/dockerfiles/commit/9cc02acfbca755cf05b97503522d4c15f1067271

**Comment by TylerJewell** [comment]
That repo isn't supported anymore - so are those changes moved to eclipse?  Florent can you mention that to Anna and then have eugene close the codenvy repo.

**Comment by benoitf** [comment]
I'm not sure the changes are backported to https://github.com/eclipse/che-dockerfiles/tree/master/recipes
Also @eivantsov said yesterday that dockerhub account is still connected to https://github.com/codenvy/dockerfiles

**Comment by sr229** [comment]
I did a quick edit using 4.6.0 LTS https://github.com/eclipse/che-dockerfiles/pull/20
still hasn't tested since I can't test on a Network with metered connection 😢 
(also it seems my git won't sign commits too )

**Comment by TylerJewell** [comment]
@sr229 - thansk for the pull request.  But seems that we already have the improvement in our backup repository.  And that the issue we have now is why our open source repository (che-dockerfiles) is not being updated.  So we will turn our attention onto that, and will close your PR.

**Comment by ddementieva** [comment]
@sr229 We've manually updated image for NodeJS stack. You can pull the updated image codenvy/node

The latest node version is there.

**Comment by sr229** [comment]
thanks, will attempt to update images now.
