### ISSUE TITLE
Remove hard check for the zip extension

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2650]
We provide the ability to import a project from a ZIP file. For that the user has to provide the URL to the zip file.
We have in place a check that, the end of the url must finish by ".zip"

This check is not necessary as the ".zip" might not be there depending on the source. 

![unnamed](https://cloud.githubusercontent.com/assets/1636769/18949776/0e4b1e5a-863d-11e6-8463-73c7370ac5fa.png)

**Comment by gazarenkov** [comment]
I'd consider it as a bug which have to be fixed in IDE, it (unlike UD) still check for "zip" extension
