### ISSUE TITLE
Need to change Agent REST API and update UI in "Agents" section

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#2654]
This issue is the second iteration of the https://github.com/eclipse/che/issues/1774
It was decided to change change the Agents REST API the following way:

1 Add **id** field. The value of it would be the current value of the **name** field i.e. **org.eclipse.che.ls.json**
1. Amend **name** field so, that it would reflect meaningful name of the agent i.e. **JSON language service**
2. Add **description** field
3. Change REST API, so that new id will be used instead of name e.g. change `GET /agent/name/{name}` to `GET /agent/id/{id}`

After that need to update Dashboard UI, so that new API would be consumed.

**Current behavior:**

https://cloud.githubusercontent.com/assets/1461122/18795730/3551dc76-81c6-11e6-9e47-e47930e12092.gif

As you can see the "description" property is missing and the "name" property does not look viable from the user perspective

**Che version:**    5.0.0-M3

**Comment by garagatyi** [comment]
@gazarenkov @tolusha Please take a look

**Comment by TylerJewell** [comment]
I believe Ilya plans a pull request.

**Comment by gazarenkov** [comment]
Cosmetic changes, np to me.
@tolusha  ?

**Comment by tolusha** [comment]
Looks good to me too.

**Comment by ibuziuk** [comment]
@garagatyi @gazarenkov @tolusha hi, guys. I have started to look into the 'wsmaster' component in order to change the REST API. Basically, I'm trying to figure out what is the best workflow / environment setup when working with 'wsmaster' component. For now I have imported the wsmaster module to the workspace and can browse through the code & run unit tests. What I would like to  setup is possibility to debug wsmaster services. Could you please clarify how can I achieve this (maybe there is some doc) ? Thanks in advance

**Comment by TylerJewell** [comment]
Adding @sleshchenko - it may be a good idea to do a quick session with him and @slemeur.  @sleshchenko has been developing a lot of our server-side APIs recently and he would have the best workflow in mind.  And @slemeur has been documenting these various points for our docs.

**Comment by ibuziuk** [comment]
@TylerJewell thank you! I have just had a chat with @l0rd who recommended to use **jpda** approach:
1. Build the module e.g. **wsmaster** 
2. Build Che **asembly/assembly-main** to generate a new war with my updates
3. build the docker image: `docker build -t codenvy/che-server:local .`
4. If needed build the che-launcher:local too. That's really easy but the Dockerfile is in another github repository (eclipse/che-dockerfiles)
5. Run the launcher: `docker run -t --rm -v /var/run/docker.sock:/var/run/docker.socke -e "CHE_DEBUG_SERVER=true" -e "CHE_DEBUG_SERVER_PORT=9999" codenvy/che-launcher:local start`
6. Use IDE "remote debug configuration" facilities in order to attach to the running tomcat

AFAIK, there is no documentation covering **jpda** technic. @slemeur we can contribute the info about jpda setup to the che documentation  (as far as I know most, if not all, from red hat use this approach for development)

**Comment by slemeur** [comment]
@ibuziuk 
Let's discuss about it. I'll reach you over email.
Thanks

**Comment by TylerJewell** [comment]
I think the step 3 - build the che-server docker image is unnecessary.  You can use the che-launcher with CHE_LOCAL_BINARY environment variable pointing to your local assembly.  This would have the same affect, I believe.

**Comment by benoitf** [comment]
as @TylerJewell wrote, I'm using flag `-e CHE_LOCAL_BINARY=/Users/Documents/git/eclipse/che/assembly/assembly-main/target/eclipse-che-5.0.0-M5-SNAPSHOT/eclipse-che-5.0.0-M5-SNAPSHOT` to use my local assembly from che-server image (no step 3 or 4  required)

**Comment by l0rd** [comment]
I confirm that @TylerJewell and @benoitf way to debug Che is more efficient than mine. That's because I love typing `docker build` 😃
