### ISSUE TITLE
Documentation for Workspace Administration - Intro

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2659]
Update the `Workspace Administation - Intro` page for the 5.0.0 release. Work includes adding multi-machine feature and cleaning up links.

[https://eclipse-che.readme.io/v5.0/docs/workspace-admin-intro](https://eclipse-che.readme.io/v5.0/docs/workspace-admin-intro)

**Comment by JamesDrummond** [comment]
@bmicklea Please review.

**Comment by bmicklea** [comment]
Looks good thanks
