### ISSUE TITLE
Documentation for Workspace Administration - Runtime Stacks

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2662]
Update the `Workspace Administation - Runtime Stacks` page for the 5.0.0 release. Work includes adding multi-machine feature, adding new images, cleaning up links, etc.

[https://eclipse-che.readme.io/v5.0/docs/stacks](https://eclipse-che.readme.io/v5.0/docs/stacks)

**Comment by JamesDrummond** [comment]
@bmicklea Please review.

**Comment by bmicklea** [comment]
reviewed and complete
