### ISSUE TITLE
Could not load [org.h2.mvstore.MV Store$2]

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#2663]
Seems lack of some class files.

**Reproduction Steps:**
1. Start che
2. display log

**Expected behavior:**

Probably with no exceptions.

I put the full stack trace to [my gist](https://gist.github.com/monaka/c8acbd252360bfba8e32d34f7ba01371).   The root cause is here.

```
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.h2.mvstore.MV
Store$2]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
        ... 6 more
```

**Che version:**

 nightly

**OS and version:**

CoreOS 1122.2.0   

**Docker version:**

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:  
 OS/Arch:      linux/amd64

**Che install:**    Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
Hi @monaka - hummmm.  So, I have not seen this error before. It looks like you are using the Docker launcher to start / stop Che.  Can you provide the syntax that you used to set the CHE_VERSION, and any other environment variables before calling the Docker container?

My first guess is that perhaps some folder on your host system that should be RW is not currently RW. I do not believe we have done much testing on coreos.

**Comment by monaka** [comment]
I could run che-server:latest without exceptions. This issue is reproduced under nightly only to me.
Comparing their logs, it was added `-Dh2.baseDir=/home/user/che/db/` to the nightly.

And I found the similar issue on the other product. https://github.com/brettwooldridge/HikariCP/issues/298
I guess this is a bug on the nightly.

**Comment by TylerJewell** [comment]
The latest is running 4.7.2 and nightly is 5.0.0-M3, which just introduced a complete rewrite of the data storage layer, consolidating everything into a JPA-based interface.  @skabashnyuk - can you have team take a look?

**Comment by akorneta** [comment]
this [commit](https://github.com/eclipse/che/commit/0c8bfddec73f3bac05257e42c15b7deb7dce9016) already fixes this problem

**Comment by monaka** [comment]
It seems be fixed. So I close this. Thanks for your improvement.
