### ISSUE TITLE
Code completion for PHP

### ISSUE THREAD

**Issue by ekkode** [eclipse-che/che#2666]
I'd like to see code completion for PHP projects added. I'm interested mostly in Symfony projects that run in Eclipse Che. Is there any plan on this?

**Comment by ddementieva** [comment]
@ekkode We have the issue registered for the PHP support. You can track it with https://github.com/eclipse/che/issues/2590

**Comment by kaloyan-raev** [comment]
@ekkode There is currently some level of code completion provided by the [Crane](https://github.com/HvyIndustries/crane) php language server, which was recently integrated with Che (#2282). Make sure you have the `org.eclipse.che.ls.php` agent activated for your workspace.

The Crane language server provides basic code completion, nothing specific to Symfony.

We are currently working on another PHP language server: [felixfbecker/php-language-server](https://github.com/felixfbecker/php-language-server). The work on code completion is currently a work in progress: https://github.com/felixfbecker/php-language-server/pull/38.

Once we have some reasonable code completion, we will replace the Crane language server with the "felixfbecker" one. The benefit of the latter is that it is implemented in pure PHP and has a greater potential of attracting the PHP community-at-large to contribute and improve it.

So, if you are an experienced PHP developer, I invite you to the [felixfbecker/php-language-server](https://github.com/felixfbecker/php-language-server) project and join forces for the features you want to see in Che.
