### ISSUE TITLE
Execution of commands ends with errors (Bitnami Swift)

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2667]
**Reproduction Steps:**
1. Create workspace from the 'Bitnami Swift' with 'swift' project from template
2. Run command 'swift: 1. Create project'

**Observed behavior:**
`[dev-machine] :0: error: unable to attach DB: unable to initialize database (near "WITHOUT": syntax error)`
`[dev-machine] swift-build: error: exit(1): /opt/bitnami/swift/bin/swift-build-tool -f /projects/swift/app_template/.build/debug.yaml`

![swift](https://cloud.githubusercontent.com/assets/8051404/18993355/82c9e538-872b-11e6-86ee-48d969d5593f.png)

**Che version:**    5.0.0-M4
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**    local

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by artaleks9** [comment]
Right now the bug is not reproduced.
