### ISSUE TITLE
Creating a Project for a different runtime within a Workspace fails to create a project that will compile/run

### ISSUE THREAD

**Issue by snorthov** [eclipse-che/che#267]
I was in the workspace that I created for console-java-simple.  I said:

1) Workspace->Create Project
2) SAMPLES: web-nodejs-simple
3) Press 'Create'
4) BUG 'CMD' button still says 'consle-java-simple: build' instead of JS build commands
5) Open a console (+)
6) Type npm
7) BUG: no npm

From talking to people, my understanding is that all of the projects within a workspace must all be of the same type (ie. all Java).  If this is so, then 'Create Project' needs to gray out runtimes that don't apply (or something like that) so I am unable to get into this error state from the UI.

**Comment by TylerJewell** [comment]
@snorthov All three issues are confirmed. One is a regression from the beta build.  We have issues opened and they will be resolved before the GA.

**Comment by TylerJewell** [comment]
This was resolved in 4.3.
