### ISSUE TITLE
Workspace configurations are not saved on Che server restart.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2670]
On persistent storage with H2/JPA in che and docker containers

datasource is used as 
[https://github.com/eclipse/che/blob/dda5acf61ebe9e89a9dda6b6afe738b6fd09bfa6/assembly/assembly-main/src/assembly/tomcat/conf/server.xml#L53](https://github.com/eclipse/che/blob/dda5acf61ebe9e89a9dda6b6afe738b6fd09bfa6/assembly/assembly-main/src/assembly/tomcat/conf/server.xml#L53)

and folder for db is using
[https://github.com/eclipse/che/blob/dda5acf61ebe9e89a9dda6b6afe738b6fd09bfa6/assembly/assembly-main/src/assembly/bin/che.sh#L611](https://github.com/eclipse/che/blob/dda5acf61ebe9e89a9dda6b6afe738b6fd09bfa6/assembly/assembly-main/src/assembly/bin/che.sh#L611)

so database is saved into ${CHE_HOME}/db/

but when reading [https://eclipse-che.readme.io/docs/usage-docker#workspace-storage](https://eclipse-che.readme.io/docs/usage-docker#workspace-storage) we can use `-e CHE_DATA_FOLDER`to customize the host directory where to save the data

[https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L28-L29](https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L28-L29)

**Reproduction Steps:**
1. Start Che server with CLI or che-launcher.  
2. Create and open a new workspace.
3. Make changes to workspace configuration.  
4. Stop che server.
5. Repeat steps 1 and 2. Configurations are not there.

**Expected behavior:**

All workspace configurations are changed after restart.

**Observed behavior:**

Workspace configurations are not saved after restart.

**Che version:**    5.0.0 master(M3)   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by benoitf** [comment]
adding labels asked by @JamesDrummond

**Comment by riuvshin** [comment]
М4 already released. moved to M5

**Comment by riuvshin** [comment]
@bmicklea please also move it to M5 milestone plan

**Comment by TylerJewell** [comment]
To be clear - the use case is that we need to honor the CHE_DATA_FOLDER and CHE_CONF_FOLDER variables that are in the CLI and in the che-launcher containers. These systems pass along certain configuration data to within the che-server.  

https://eclipse-che.readme.io/docs/configuration#section-environment-variables

Also, if a user has 4.7.2 and they have their old JSON files saved with one of these values, then when the upgrade takes place, we should not lose that location. This should be fine, because within the che-server they were always saved in the same location. These values just change the location where they are volume mounted into che-server.

**Comment by skabashnyuk** [comment]
I'm not really familiar with che-launcher internals. @benoitf @TylerJewell can you confirm that changing `-Dh2.baseDir=${CHE_HOME}/db` to `-Dh2.baseDir=${CHE_HOME}/storage` is what are you looking for?

**Comment by benoitf** [comment]
@skabashnyuk I would say it will at least restore the previous way of mounting storage folder

But before it seems this folder was also configurable through `che.properties` file

https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L28-L29

**Comment by skabashnyuk** [comment]
Ok let's restore previous way.
FYI `-Dh2.baseDir=` is the way to affect on database files location. 
It's not pissible to configure it through `che.properties` now.
