### ISSUE TITLE
Default Stacks Do Not Reference Minimal Base Images.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2671]
With the introduction of agents, we do not need to use our own custom docker base images such as `codenvy/ubuntu_jdk8` as currently used in stacks.json. For example [https://github.com/eclipse/che/blob/564e5de5cf43faea42220e44268ab06d17d7555e/ide/che-core-ide-stacks/src/main/resources/stacks.json#L119](https://github.com/eclipse/che/blob/564e5de5cf43faea42220e44268ab06d17d7555e/ide/che-core-ide-stacks/src/main/resources/stacks.json#L119) .

Can we revise Che's `stacks.json` file to use `ubuntu` for recipes' base image?

**Comment by benoitf** [comment]
With these customs image we don't need extra dependencies installed at runtime (it saves boot time) this is faster

**Comment by JamesDrummond** [comment]
Thanks for the clarification.
