### ISSUE TITLE
[Q] Why two versions of che.sh available?

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#2675]
In the repository, there have /che.sh and /assembly/assembly-main/src/assembly/bin/che.sh.
They looks similar. I feel /che.sh is more refactored. But Dockerfile uses che.sh in the assembly folder.
Why are two che.sh available?

**Comment by TylerJewell** [comment]
There are multiple things going on.
1. The /assembly/.../che.sh is part of the Che assembly. This is the script that is run if you are running Che natively as a server.  It starts / stops Tomcat.  This script is OS-specific and has lots of different behaviors about how to manage Tomcat for an OS.
1. The che.sh in the root repository is the CLI itself.  The CLI manages our varoius utilities, such as the che-launcher, which itself is responsible for launching the che-server docker container, which inside of it has the assembly's che.sh for Tomcat.

We have these extra layers as the CLI is cross-platform and also 12-factor app - define configuration in environment variables and start / stop with common syntax.

We started che only as a tomcat image, but we have added these important layers to make things a lot simpler for new users.

**Comment by monaka** [comment]
Thank you for your information. I see the overview.
It's required to read files in eclipse/che-dockerfiles also if I want to know the current whole Che, right?

**Comment by TylerJewell** [comment]
All of the docker images used by our tools are built from the other repository, yes.

**Comment by monaka** [comment]
I got the concept of container administration in Che after I read che-dockerfiles. Thank you  for your support!
