### ISSUE TITLE
yellow on white hard to read

### ISSUE THREAD

**Issue by thpglobal** [eclipse-che/che#2676]
The new light ide appearance uses yellow for html tags

**Reproduction Steps:**
1. Enter an HTML tag into a .php file
2. Try to read it 

**Expected behavior:**

Readable, high-contrast color choices.

**Observed behavior:**

Nearly unreadable low-contrast color choice for HTML tags

[Describe observed behavior here]

**Che version:**    [Enter Che version here]  
**OS and version:** [Enter OS name and version here]  
**Docker version:** [Enter your Docker version here `docker version` on CLI]  
**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by ghost** [comment]
@jcoonrod labeling as enhancement. Indeed, html tags are barely readable in the light theme.
