### ISSUE TITLE
'Running' bage is always shown on the process item

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#2679]
'Running' bage on the process item isn't hides after ending the corresponding process.

**Reproduction Steps:**
1. Create new custom command with default command line `echo "hello"`.
2. Execute it.

**Expected behavior:**

An appropriate process item should be shown in the **Processes** panel and the process's 'Running' bage should be hidden after ending the process.

**Observed behavior:**

An appropriate process item is shown in the **Processes** panel but the process's 'Running' bage isn't hides after ending the corresponding process.
![screenshot](https://cloud.githubusercontent.com/assets/1636395/19031051/857c7f80-895a-11e6-9741-616d52be39cf.png)

**Che version:**    5.0.0-M5-SNAPSHOT   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by slemeur** [comment]
Cannot reproduce
