### ISSUE TITLE
Compose Syntax Links Not Working.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2687]
Compose syntax `links` is currently not working. The workaround is to use `depends_on` in lieu of `links`.

**Expected behavior:**

Use `Links` in compose recipe for use in creating stacks/workspaces.

**Observed behavior:**

Use `Links` in compose recipe for use in creating stacks/workspaces will fail. Have to use `depends_on` instead.

**Che version:**    5.0.0-M1   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by bmicklea** [comment]
This is critical to M6.

**Comment by riuvshin** [comment]
Moved to M7

**Comment by mmorhun** [comment]
Done
