### ISSUE TITLE
Documentation for Workspace Administration - Runtime Recipes

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2688]
Update the `Workspace Administation - Runtime Recipes` page for the 5.0.0 release. Work includes adding multi-machine feature, adding supported/non-supported compose syntax, cleaning up links, etc.

[https://eclipse-che.readme.io/docs/recipes](https://eclipse-che.readme.io/docs/recipes)

**Comment by bmicklea** [comment]
reviewed
