### ISSUE TITLE
Improve selected state in textfield for dark theme

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2689]
The selected state in textfields for dark theme is hard to see and read.

Instead of this colors:
![screen shot 2016-10-03 at 18 50 59](https://cloud.githubusercontent.com/assets/1636769/19045667/5e394b48-899a-11e6-971a-810d84763413.png)

Move to these:
![screen shot 2016-10-03 at 16 37 39](https://cloud.githubusercontent.com/assets/1636769/19045645/3b4a042e-899a-11e6-96e0-251a11ec29fd.png)

**Comment by vitaliy-guliy** [comment]
Spent 3 hours

**Comment by vitaliy-guliy** [comment]
https://github.com/eclipse/che/pull/2958
