### ISSUE TITLE
The pop up dialog about "Success created workspace "overlay the open button on dashboard

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2690]
**Reproduction Steps:**
Do steps for creating a workspace (For exampl: Add Workspace -> Java Stack ->Click on Create Workspace button )
**Observed behavior:**
![screenshot from 2016-10-04 10 58 04](https://cloud.githubusercontent.com/assets/1640058/19066446/f41cdae4-8a21-11e6-9eba-4508d902a659.png)
This may irritate of many users
**Che version:**    5.0.0 M5
**OS and version:** Ubuntu 14 TLS
**Docker version:** 1.12
**Che install:**    local tomcat

**Comment by ashumilova** [comment]
Depends on https://github.com/eclipse/che/issues/2627

**Comment by ashumilova** [comment]
Depended issue is closed.
