### ISSUE TITLE
Request: Parametrise workspace folder mount options

### ISSUE THREAD

**Issue by Spritekin** [eclipse-che/che#2692]
This issue has been discussed at: https://github.com/eclipse/che/issues/2565

Summary:
The distinct Che folders (workspace, lib, storage) are mounted by the Che server into the workspace containers using a docker "Z" option (used to declare a folder to be shared by multiple containers). This flag is hardcoded in the Che server code and was added to solve mounting problems in RHEL.

Unfortunately, this flag doesn't play nice with NFS folders. When an NFS folder is used the Z flag causes an error preventing the workspace to be launched. This effect was tested on CoreOS 1122.2, with both a standard NFS and an AWS EFS. Test details in the ticket mentioned above.

Request:
Allow the workspace mount flags (specifically the Z flag) to be configured by a Che server starting parameter (proposed parameter name is --shared_workspace_folder=true). 
This parameter will be on by default so Che will default to the current operation. However, the parameter will allow the user to disable the Z share flag.

**Comment by TylerJewell** [comment]
We now allow multiple volume mounts to be configured as a property within Che. Those same volume mounts are then available across all of the che workspaces generated from that initial server.  So I think we would need to allow for a set of volume mount properties to be defined in a single location and then reused.  

We could, for example, let the volume properties be defined as a string.
`che.machine.volume.mount.options="Z,ro"`
which would allow for both the shared option along with read only.

A user could set `che.machine.volume.mount.options=` as a way to remove any flags that we provide as a default.
