### ISSUE TITLE
can not find or open /mnt/che/lib/ws-agent.zip

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#2701]
OS : ubuntu 16.04
Docker : v1.12.1
Che : v4.7.2

i'm not sure this is a bug or not

When i set the 
CHE_DATA_FOLDER=/home/thyeun/Che, i been getting an error **can not find or open /mnt/che/lib/ws-agent.zip**

than i try to change it to CHE_DATA_FOLDER=/home/thyeun/che, no error happen.

same goes to CHE_CONF_FOLDER.

hope someone can reproduce it with a different name or different OS, to make sure folder with capital letter wont affected.

**Comment by TylerJewell** [comment]
It is not a bug.  Folders are case sensitive.
