### ISSUE TITLE
Terminal wasn't opened after restart workspace (regression)

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2702]
**Reproduction Steps:**
1. Create workspace **with project** and run it
2. Click on 'Workspace' -> 'Stop'
3. Click on 'Start' in the toast loader

**Observed behavior:**
The workspace was started, but terminal wasn't opened. 
![terminal](https://cloud.githubusercontent.com/assets/8051404/19106167/8997f06e-8aee-11e6-96f3-af7877e16644.png)

**Che version:**    5.0.0-M5-SNAPSHOT 
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.11.2
**Che install:**   Docker container

**Additional information:**
- Problem started haping recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by riuvshin** [comment]
This is regression.

**Comment by AndreyChizhikov** [comment]
Yes

**Comment by bmicklea** [comment]
@AndreyChizhikov if the user opens the terminal manually does it work?

**Comment by AndreyChizhikov** [comment]
@bmicklea Yes
