### ISSUE TITLE
Documentation for Workspace Administration - Runtime Machines

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2716]
Update the `Workspace Administation - Runtime Machines` page for the 5.0.0 release. Work includes defining a machine, adding additional libraries/tools to a runtime machine, adding snapshots, and viewing/editing machine information.

[https://eclipse-che.readme.io/v5.0/docs/machines](https://eclipse-che.readme.io/v5.0/docs/machines)

**Comment by bmicklea** [comment]
reviewed
