### ISSUE TITLE
Documentation for Workspace Administration - Workspace Agents

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2718]
Update the `Workspace Administation - Workspace Agents` page for the 5.0.0 release. Work includes defining a agents, adding agents to stack and adding agents to custom stack.

[https://dash.readme.io/project/eclipse-che/v5.0/docs/workspace-agents](https://dash.readme.io/project/eclipse-che/v5.0/docs/workspace-agents)

**Comment by bmicklea** [comment]
reviewed
