### ISSUE TITLE
Documentation for Using Che as an IDE - Intellisense

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2720]
Update the `Using Che as an IDE - Intellisense` page for the 5.0.0 release. Work includes stating how intellisense is included in Che using language server protocols, describing the features on intellisense and defining the language server protocol.

[https://eclipse-che.readme.io/v5.0/docs/intellisense]https://eclipse-che.readme.io/v5.0/docs/intellisense)

**Comment by bmicklea** [comment]
reviewed
