### ISSUE TITLE
Wrong behavior with stack bulk operation

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2727]
**Reproduction Steps:**
1. Open Stack page
2. Click on bulk operation checkbox
3. Click Delete button

**Expected behavior:**

Only stacks with visible checkboxes in first column should be proposed to delete.

**Observed behavior:**

All stacks are proposed to delete.

![stack_bug](https://cloud.githubusercontent.com/assets/1611939/19181673/5765a908-8c77-11e6-9d4d-4849ca8a2036.png)

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/2734/commits/d9a5871a4d9f0a39fed926923358ef02675449f2

**Comment by olexii4** [comment]
https://github.com/eclipse/che/commit/196e8279ef712bf78ab3a6a1157be32f161f5c69

**Comment by olexii4** [comment]
1d
