### ISSUE TITLE
How to configure Che when workspaces + browser are on different networks

### ISSUE THREAD

**Issue by instigardo** [eclipse-che/che#2736]
Che Server URL-> Dashboard->Recent Workspaces->Open in IDE I get following error.

Error: Can't load project types: Error
at Object.window.IDE.eventHandlers.initializationFailed (http://x.x.x.x:8080/che/wksp-odt1?uid=843004:39:27)
at Jwb (_app-0.js:2003:406)
at Wwb (_app-0.js:2009:56)
at _.hq (_app-0.js:4290:319)
at eval (_app-0.js:980:86)

It is working fine when I am opening it on pc on which VM ware is running but when I try to access the same from other machine on same network, the dashboad loaded fine but workspace wont load and throws this error.

**Comment by TylerJewell** [comment]
There is probably something on your network that is preventing the browser to connect to the workspace.  These parameters are configurable by the Che admin.  You can read about the various parameters to configure in the networking page.
https://eclipse-che.readme.io/docs/networking#connectivity

**Comment by instigardo** [comment]
Hi 
I did some debugging, it seems it is trying to connect to the ip of the vm instance rather than my server ip. Is there a way to map it to the server ip?

**Comment by TylerJewell** [comment]
Yes - please see the configuration options that can be set here.

https://eclipse-che.readme.io/docs/networking#connectivity

**Comment by instigardo** [comment]
Thanks it got resolved by machine.docker.local_node_host=IP

**Comment by TylerJewell** [comment]
Great!  What are you using Che for.
