### ISSUE TITLE
Enhancements to the terminal features

### ISSUE THREAD

**Issue by binduwavell** [eclipse-che/che#274]
**Description of problem:** It would be great if the terminal could be setup to create/re-attach to a tmux session (even if this is not the default.) It allows one to get back to where one left off when the browser refreshes. If we can suspend the main machine for a workspace then we can actually re-enter our terminal upon resume. I have this setup with my codenvy runners and find it very useful. I get that you might not want to make this the default behavior, but making it easy for folks to do would be super.

It would be nice if we could name our terminal tabs in the UI (rather than Terminal and Terminal-2 we could call them: Java and Node or whatever makes sense.) Of course I can do this with tmux, but it would be a nice feature to have in the UI. Especially if these could be restored after a suspend...

**Che version:** `4.0.0-beta-13-1`
**Che install directory:** `~/Downloads/eclipse-che-4.0.0-beta-13-1`
**Docker version:** 

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Docker Info:** 

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: S6GZ:TD7N:M4BZ:J6DK:RN3E:455I:YTPI:BDY4:32XR:ONHD:MGDJ:HFVC
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 39
 System Time: 2016-02-07T22:56:03.470098201Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: binduwavell
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Java version:** `N/A I'm using che.sh run -i (so whatever you have in your container)`
**Environment details (AWS, VirtualBox, physical, etc.):** `I'm on my mac using the default dockertoolbox 0.10 and default che 4.0.0-beta-13-1.`

**Comment by TylerJewell** [comment]
@slemeur - please create the appropriate epic within GitHub that tracks all of the improvements that are anticipated for the terminals including terminal splitters, tabbed terminals, and the so forth.  Please review this issue and incorporate additional check box items that may make sense.

**Comment by TylerJewell** [comment]
@slemeur *bump*

**Comment by slemeur** [comment]
Cross linking with: https://github.com/eclipse/che/issues/1888

Also created the following epic for terminal improvements: https://github.com/eclipse/che/issues/4824
