### ISSUE TITLE
Local IDE Mount with docker hangs

### ISSUE THREAD

**Issue by sklosedr** [eclipse-che/che#2742]
Hi ,
I try to mount a remote workspace on my windows laptop.
ip and port work with ssh (putty)
my local path exists. Docker ist working.

If I run this command:

`docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --name codenvy-mount -v /c/Users/sklose/mount:/mnthost codenvy/che-mount <ip> <port>`

I'm asked to logon with password. After the input of the password the command hangs.

How should I proceed? Where is the error log etc...

Best regards
Stefan

**Comment by TylerJewell** [comment]
The utility is non-terminating.  It actually is supposed to hang :).  It has started the sync process and continues it as long as the process is running.

If you go into another terminal, you will see that your workspace has been synchronized.  By the way, if you use the CLI, it simplifies the discovery of the workspaces + ports for you.  You just have to type `che mount` and we take care of the rest.

**Comment by sklosedr** [comment]
Hi Tyler,

1.)
I followed  [https://youtu.be/WmBYF7xNLR8](https://youtu.be/WmBYF7xNLR8)  The Che Server and the Workspace is run at Google (Bitnami installation).

In the Video there is an Info message that the local directory has been mounted. 
In my case there is no info message and there is no replication of the workspace to my local directory.

2.)  I also tried che mount with a local che installation on my laptop and it works. BUT I want to mount the workspace from my google cloud and I do not have any clue how to do it with che mount (wich seems to work with local che only?). Therefore I switched to the codenvy/che-mount approach as described in the Youtube Video.

Best regards
Stefan

**Comment by TylerJewell** [comment]
Hi Stefan - the Che mount utility from the CLI inherits the Che properties set by environment variables.   So if you haven't modified those properties then the cli is looking to connect to a local Che server.  If I get some time early this week I will do an example of using the cli with a remote Che server.

So now I understand why you are using the container syntax so that you can hit the remote IP of the workspace.

When you use the container option are you providing the IP of your workspace?  Do my use the IP of your Che server.

**Comment by TylerJewell** [comment]
Sorry that was typo.  I am trying to help you by writing a response on my phone so my fat thumbs make mistakes.  I wanted you to get both the public IP of your workspace and the che server connecting to both with the container for testing.

**Comment by sklosedr** [comment]
Hi Tyler,

the docker mount works on the Codenvy Version 5.0.0-M4 environment on my personal account:
`docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --name codenvy-mount -v /c/Users/sklose/mount:/mnthost codenvy/che-mount 40.114.82.27 34457`

But we need it on our Bitnami Google Image (which is Che version 4.7.2. Build Time :2016-09-09 10:26:29)

you can check it out if you try to mount my che workspace on ount bitnami google cloud (Standard password)

`docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --name codenvy-mount -v /c/Users/sklose/mount1:/mnthost codenvy/che-mount 146.148.115.101 32774`

In our installation che server and workspace server are on the same google vm which got one external IP Address (146.148.115.101 at the moment). you can logon to the workspace with putty.

I would very much appreciate also an working example with  che mount using the cli directly.

Thanks in advance 
Stefan

PS: If I install Che version 4.7.2. on my laptop I can mount the workspace - so it must be something with the bitnami google installation
[https://community.bitnami.com/t/eclipse-che-on-google-compute-engine-can-not-be-mounted/44795](https://community.bitnami.com/t/eclipse-che-on-google-compute-engine-can-not-be-mounted/44795)

**Comment by ghost** [comment]
@TylerJewell indeed, it hangs, while ssh directly into a container works and so does sshfs on Ubuntu.

```
eugene@eugene:~$ sshfs -o idmap=user user@146.148.115.101:/projects /home/eugene/Downloads/projects/ -p 32774
user@146.148.115.101's password: 
eugene@eugene:~$ 

eugene@eugene:~/Downloads/projects$ ls
project-hg2n  web-java-spring
```

**Comment by TylerJewell** [comment]
@sklosedr - may I just confirm the scenario:
1: `che mount` to local Eclipse Che or beta.codenvy.com works properly.
2: `che mount` to a remote Eclipse Che hosted by Bitnami does not work.
3: However, sshfs does directly work into a remote Eclipse Che hosted by Bitnami.

Is this the correct situation?

**Comment by ghost** [comment]
@TylerJewell sshfs worked for me using Che Bitnami VM.

**Comment by TylerJewell** [comment]
Yes, then if sshfs works for you into Bitnami, then are you sure `che mount` is hanging?  It purposefully does not return. It stays in the foreground while syncing.  You have to open another terminal to see the copied files.

**Comment by sklosedr** [comment]
@TylerJewell 

1: che mount to local Eclipse Che  works properly
--> yes
1a: che mount to beta.codenvy.com works properly.
--> don't know how to use che mount with remote che server / workspaces from codenvy.com
1b:
`docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --name codenvy-mount -v /c/Users/sklose/mount1:/mnthost codenvy/che-mount 40.114.82.27 34457`
 --> WORKS with remote che server / workspaces from codenvy.com

2: che mount to a remote Eclipse Che hosted by Bitnami does not work.
--> don't know how to use che mount with remote che server / workspaces

2a:
`docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --name codenvy-mount -v /c/Users/sklose/mount1:/mnthost codenvy/che-mount  146.148.115.101 32774`
 --> WORKS NOT with remote che server / workspaces from google / bitnami

3: However, sshfs does directly work into a remote Eclipse Che hosted by Bitnami.
--> didnt try but @eivantsov  says it works

Pershaps you can give me a hint how to use che mount instead of the docker approach to mount a remote che server / workspace. 

Thanks
Stefan

**Comment by ghost** [comment]
@sklosedr what OS do you use? I'm asking since my further suggestions will vary depending on your answer.

**Comment by TylerJewell** [comment]
This does seem like some sort of weird limitation - perhaps due to the nature of the Bitnami firewall that they set up.  If this continues to be a bug where I need to investigate it, it may be awhile before I can get to it or assign an engineer.  We are taking the engineers that look after this area of the product into a super-secret-fun-important hackathon for 10 days starting Thursday.  So this will be important to investigate, but not sure I can guarantee timing.

**Comment by sklosedr** [comment]
@eivantsov : I use Windows 7

**Comment by sklosedr** [comment]
No comment from the bitnami forum so far:
[https://community.bitnami.com/t/eclipse-che-on-google-compute-engine-can-not-be-mounted/44795](https://community.bitnami.com/t/eclipse-che-on-google-compute-engine-can-not-be-mounted/44795)

**Comment by sklosedr** [comment]
unintentionally closed

**Comment by amrecio** [comment]
Hello,

Bitnami Developer here. I've looked into the issue and it seems unison is working properly but because it doesn't print any progress during the synchronization, it appears to be frozen. I've stopped the test with @sklosedr 's workspace after an hour but it seems it takes even longer to finish the process.

In summary, che-mount is working properly. It's just taking a long while to finish.

**Comment by sklosedr** [comment]
@amrecio  Thanks for the feedback. I will check it. But there must be something wrong in the Bitnami google specific configuration if it takes hours for a few kByte. 

Can you investigate / solve the Problem as we are new to the google cloud.

[But we had already a simular effekt in the google kubernetes Cloud, where it took minutes to connect from an app-POD to an DB-Pod by using external IP Adresses.]

**Comment by TylerJewell** [comment]
@amrecio - the che-mount utility doesn't terminate.  It will continue to run and seem like it's blocking.  The synchronization should be nearly instant however.  If you terminate the che-mount process and force the terminal to return, then the synchronization link will be broken.  I know this isn't ideal - that it really should be entirely in the background, but we need some improvements in the SSH processing layer before we execute it in the background.

So - can you check to see if the issue is really slow synchronization or was there _any_ synchronization done of any files?

@sklosedr - I am the author of the che-mount utility, and I also run Codenvy as it's CEO.  So this issue makes it away to my assignment - but this is probably something I can not investigate more deeply for a number of days as I am traveling for business right now.

**Comment by sklosedr** [comment]
@TylerJewell 
Im the CEO of Next Level Integration a german Software company.  We investige Che as an altermative to our existign environment. But Local IDE will still play a role in future. Therefore the combination and the snyc is a VERY important thing. 

Thanks for  your help.  In fact I have new information which is not good as far as I can see:

In che google bitnami workspace there were two projects. One with a few kB and another one with 270MB (all build artefacts included).  The second is still regarded as small. 

The  sync of the second project was the reason that it lasts 3 hours from our google Cloud (which was interpreted by me as "it hangs"). If I change a single file (nothing else) it lasts 1 hour to sync.

I checked the project into the codenvy workspace and now it has the same behaviour as the google cloud (it syncs for an hour an no effect ist visible).

If we cant speed this way  up be y factor of xx to sync to a local IDE, it cannot be used in real world scenarios.

We need to talk about workarounds.

0.) It could be helpful NOT to replicate build artefacts 

1.) We used docker with codenvy/che-mount --> maybe che mount cli is faster. But we dont know how to handle it for remote Workspaces (see my questions above)

2.) We could run a local che installation on our Laptops and sync form there. But We dont understand how to replicate the workspace definitions from the central che server to our local che servers. This is described at powerpoint level ("you can work in the train") but I couldnt find a technical description how to subscribe an central che workspace and sync it with a local che workspace..

Mabye we should get in contact offline. You can reach me a sklose@next-level-integration.com 

Best regards
Stefan

**Comment by TylerJewell** [comment]
Hi Stefan - when I get some down time I will write you offline.

To your points - which are good.  The Che cli is just calling the docker container - so it is identical.  If the issue with the docker container persists then the cli will fail too.

Syncing from Che to Che is something that we think a lot about.  And we have rudimentary support built in but it could be a bit tricky for you to set it up for a local sync.  There are at least two things that must be sync - the projects folder and the Che database, which stores the internal configuration of the workspace.  But even with that you would lose the state of the workspace runtime snapshots for any files modified outside of the projects.  It is possible to sync snapshots but it would be a lot of docker manual steps.  Ultimately the profit is not worth the cost and better for you to wait for our engineering teams to add in auto sync between two Che servers next year.

The better answer is to diagnose why file sync on bitnami is so awful and get it fixed.

One alternative which is also a bit slow is to avoid sync and instead we show you how to sshfs direct into the workspace.  You can use the local IDE but it is working against the remote files.

**Comment by sklosedr** [comment]
Hi Tyler,

thanks for clarification. Its NOT an Bitnami problem as I described above. Its a general problem.
https://beta.codenvy.com syncnronization lasts also hours for the same project.

sshfs doesnt make sense if the build artefacts are > 100 MB. Is there a way only specifice folders (e.g. exclude target  folder)?

Best regards
Stefan

**Comment by TylerJewell** [comment]
Ahh - there were too many notes back and forth and didn't pick up that we have confirmed that it isn't a bitnami issue.  I certainly think the idea of providing some sort of exclude list could be interesting.  I will need to do some research with our fuse implementation to see whether that is super simple or very difficult.

We can also write up some instructions about how to do a sync by hand.  I hope to get into the research of some of this soon.  Is your Bitnami image still running?

**Comment by TylerJewell** [comment]
@sklosedr - I can confirm that there are a number of tactics that we can use to enable che-mount to skip synchronizing certain directories.  We will provide a capability that allows for different path specifications including regex.

**Comment by TylerJewell** [comment]
@sklosedr @amrecio - FYI, this pull request would be a big improvement to avoid the issues that @sklosedr have run into.

https://github.com/eclipse/che-dockerfiles/pull/28/files

**Comment by sklosedr** [comment]
@TylerJewell  we stopped our Bitnami image as it makes no difference to a local installation ( in an windows environment some things works only with windows admin authorization) or with my workspace at codenvy.

**Comment by TylerJewell** [comment]
@sklosedr - closing this particular issue as I believe we have incorporated all of the improvements and they have been merged in.  We have another set of improvements coming soon that will improve performance further by having a dual unison sync.
