### ISSUE TITLE
Allow to customise shortcuts

### ISSUE THREAD

**Issue by hlavacek** [eclipse-che/che#2748]
Would it be possible to customise the shortcuts provided by Eclipse Che? 
E.g. on OS X the shortcut for Find Action is Command + A - which is the same as Select All, making it unusable.

**Comment by TylerJewell** [comment]
Hi @hlavacek - at this point in time, it is not possible for a user to customize the key binding shortcuts that are provided with Eclipse Che.  I am a bit surprised, as I thought we had a long lived epic that was tracking the work to be done on this. The request comes up frequently and we are hoping that some of the community gets involved in helping us to improve this.  There is quite a bit of work as key bindings do vary by operating system and browser combination. Also, if you provide key bindings, we need a robust panel where you can change the values, detect key strokes, and allow people to test those bindings before committing them.
