### ISSUE TITLE
Consider improving UX for adding new projects to an existing workspace

### ISSUE THREAD

**Issue by binduwavell** [eclipse-che/che#275]
**Description of problem:** It was not clear to me how to add additional projects to an existing workspace. 

Would be nice if there was a new project option in the folder with the plus dropdown thingy near the top left of the UI, that was where I looked for it originally. 

The second place I looked was under the project menu...

I hacked around this by checking something out under /projects from a terminal... 

Then I found it in a pretty obvious place (under the workspace menu... so probably me just being dumb, but at least knowing it was hard to find for someone unfamiliar with the UI might be useful.) 

**Che version:** `4.0.0-beta-13-1`
**Che install directory:** `~/Downloads/eclipse-che-4.0.0-beta-13-1`
**Docker version:** 

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Docker Info:** 

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: S6GZ:TD7N:M4BZ:J6DK:RN3E:455I:YTPI:BDY4:32XR:ONHD:MGDJ:HFVC
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 39
 System Time: 2016-02-07T22:56:03.470098201Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: binduwavell
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Java version:** `N/A I'm using che.sh run -i (so whatever you have in your container)`
**Environment details (AWS, VirtualBox, physical, etc.):** `I'm on my mac using the default dockertoolbox 0.10 and default che 4.0.0-beta-13-1.`

**Comment by ghost** [comment]
We have reworked `Creating a project in an existing workspace` flow. Now, if you have existing workspaces, and you want to create a project, you will be prompted to do so in a User Dashboard. When in the IDE, the flow is same and dead simple - Project > Create
