### ISSUE TITLE
Install che behind specific Port range to communicate

### ISSUE THREAD

**Issue by CGM-Face** [eclipse-che/che#2751]
Hello all,

I want to install eclipse che in our company.
We have a tansparent proxy and a firewall.
Our firewall expert opens a port range rom 8080 until 8999 for my project (eclipse che) from our server network to the client network.
1. I've install a debian system with jessie and docker version 12.x.x.
   I've configured the port range for docker in the "/proc/sys/net/ipv4/ip_local_port_range" file.
2. With these port range, I've download the eclipse che Codenvy software (latest version)
3. I've configured the proxy in docker settings.
4. I've started the server with:
   docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_HOST_IP=10.0.xxx.153 eclipse/che start
   //xxx stays for sequence of numbers
5. Now, I can connect to my eclipse che (server network) with my notebook browser (client network) with http://10.0.xxx.153:8080/
6. I can created a workspace and connect to him.
7. I want to crate a sample project and I receive the message, that my che can't connect to github.com. But why? 

So, my problem is, that my docker communicate about the right ports (8080 - 8999) to our client network, but my workspace (all workspaces) want to communicate about the higher ports (35***\* - 65573). So what can I do, that I run sample project from github.

If you need any information or you have questions about my discription, don't hasitate to contact me.

Thank you very much for your help!!

Best regards,

**Comment by TylerJewell** [comment]
Hi @CGM-Face - it seems that you are getting pretty far along with Che.  So, from what I can gather, you have been able to create workspaces and then have the browser connect over the terminal.  That is good.  But the workspace is unable to create a sample project from within it.

Projects are cloned from git inside of the workspace. So after the workspace has started, we install git utilities into the workspace (or they are already loaded there as part of a stack that is loaded).  So if you are unable to do a git clone operation from within the workspace, then it probably means that you need to configure the workspace to communicate properly over a proxy.  Much like any VM that you would configure on your network, you will need to have the appropriate `http_proxy` and `https_proxy` and `no_proxy` environment variables configured.  

You can either configure these after the workspace is loaded.  Or, you can start using some of the 5.0.0 milestone releases which allow you to edit and provide custom stacks, which reference custom recipes, which are Docker images.  You can have in your Docker image custom networking details embedded within the OS that are tailored for your company.

**Comment by ghost** [comment]
@TylerJewell it looks like the problem is a bit deeper. I am pretty sure it's related to JGit being unable to connect to GitHub.

@CGM-Face if you git clone directly in the Terminal, does it work for you? Any repo. If it does, then it's related to this one https://github.com/codenvy/artik-ide/issues/153. So, please, check connectivity from within the workspace. curl, wget, git, anything.

The second issue is the ephemeral port range. You seemed to try to limit it, but it did not work since Docker started publishing ports from 32.... Not sure what's wrong here. But, you will need these ports only if you want to preview running apps. Let's get past the first problem and then deal with ports.

**Comment by CGM-Face** [comment]
@TylerJewell , @eivantsov, thank you very much for your answere, but @eivantsov is right.

When I checked the proxy configuration of my workspace with the command "export", my proxy will be show in the list.

When I do a git clone, I receive all packages from git server. Also curl from git works.

So, I think the port range is the problem.
Or what do you think ?

**Comment by TylerJewell** [comment]
I do not believe the port range is the problem.  The port range limits incoming traffic into the workspace - it's how outside services connect inside.  The ephemeral port range should not be affecting internal services (like git) that need to communicate to the outside.

**Comment by CGM-Face** [comment]
Ok, but what do you think is the problem?
The workspace knows the http and https proxy and can connect to git.

**Comment by TylerJewell** [comment]
Unsure - but it could be this error - https://github.com/codenvy/artik-ide/issues/153

**Comment by ghost** [comment]
@CGM-Face Java does not recognize system wide proxy envs. https://github.com/codenvy/artik-ide/issues/153 will fix it.

You may try to hack it a bit.
1. Start workspace. 
2. In the terminal `mcedit ~/.bashrc`
3. `export JAVA_OPTS="-Dhttp.proxyHost=http://your.proxy.com -Dhttp.proxyPort=$port"` same for https
4. `~/che/ws-agent/bin/catalina.sh stop`
5. `~/che/ws-agent/bin/catalina.sh run`
6. Workspace > Import Project.

**Comment by AtlassianCGM** [comment]
@eivantsov 
1. I've created a new Workspace.
2. I've added the new export line:
![terminal](https://cloud.githubusercontent.com/assets/21329948/19265568/e9bf6862-8fa5-11e6-89d3-a826368abb96.PNG)

3. I've run your scripts, but when I start the "~/che/ws-agent/bin/catalina.sh run" script, I receive the following error:
![terminal 2](https://cloud.githubusercontent.com/assets/21329948/19265744/a4c861c2-8fa6-11e6-9270-3199b43a8aa1.PNG)

But what did I wrong.

An external import or create a project also does not work.
![terminal 3](https://cloud.githubusercontent.com/assets/21329948/19265855/5a4d886a-8fa7-11e6-803c-6da44131171b.PNG)

**Comment by CGM-Face** [comment]
@eivantsov 
1. I've created a new Workspace.
2. I've added the new export line:
![terminal](https://cloud.githubusercontent.com/assets/21329948/19265568/e9bf6862-8fa5-11e6-89d3-a826368abb96.PNG)
1. I've run your scripts, but when I start the "~/che/ws-agent/bin/catalina.sh run" script, I receive the following error:
   ![terminal 2](https://cloud.githubusercontent.com/assets/21329948/19265744/a4c861c2-8fa6-11e6-9270-3199b43a8aa1.PNG)

But what did I wrong.

An external import or create a project also does not work.
![terminal 3](https://cloud.githubusercontent.com/assets/21329948/19265855/5a4d886a-8fa7-11e6-803c-6da44131171b.PNG)

**Comment by AtlassianCGM** [comment]
Any idea?

**Comment by CGM-Face** [comment]
Any idea?

**Comment by TylerJewell** [comment]
@CGM-Face @eivantsov - did we work to close this issue out?  I am spending some time and circling back on all open questions to see which ones are still open vs. those that are resolved vs. those that have gone stale.

**Comment by CGM-Face** [comment]
@TylerJewell - yes, thank you.
