### ISSUE TITLE
Handle DOCKER_HOST better

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#2754]
`/home/user/che/bin/che.sh` around line 381 should check if file `/var/run/docker.sock` exist to avoid failing without error.

**Comment by ghost** [comment]
Since we launch Che in a container based on the image that has Docker installed, this file is always there. What's the scenario when the file is missing?

**Comment by wernight** [comment]
For example if running `che-server` directly (which IMO is preferable). Even in che-server manual launch documentation there's the option to use `DOCKER_HOST` socket instead of mounting the unix socket file. In that case the file is missing.

**Comment by TylerJewell** [comment]
He's [referencing this capability](https://eclipse-che.readme.io/docs/usage-docker-server#docker-unix-socket-mounting-vs-tcp-mode), which I suppose if you launch the che-server with the extra DOCKER_HOST variable, then you do not need to volume mount /var/run/docker.sock anymore.

**Comment by ghost** [comment]
@wernight @TylerJewell I see. Yeah, it's me who authored that piece of docs :)

@TylerJewell what do you think about it? If DOCKER_HOST is exported then we do not do the unix socket mount.

**Comment by garagatyi** [comment]
if DOCKER_HOST is exported we should check its value:
- if it is URI of unix socket we still need mounting
- if it is HTTP URI then just set it in a container
- if it is https/tcp URI we should handle certificates to communicate with docker 
- if it is localhost URI we should do additional steps to change it to URI accessible from within a container

**Comment by wernight** [comment]
All those are probably the safest things to do. Right now the main issue is that this file check just stops that shell script without any error if the file is missing. Just getting exit code 1 without reason.

**Comment by TylerJewell** [comment]
@wernight - I will assign this issue to myself.  I will link this to an epic around rewriting the che.sh for Tomcat instances to be a lot more simplified.  It's a big project, unfortunately, so unsure when I'll get to it.  But I think some of the ideas are good.  I will probably do this after the pull request with all of hte new property names for Che is merged for M6.  We are simplifying all of the property names to make it simpler.  We will have aliases for existing names so they will still work.

**Comment by JamesDrummond** [comment]
@eivantsov Can we label this kind/enhancement?

**Comment by TylerJewell** [comment]
@wernight - pr: #2786 - has changes in it to no longer check for /var/run/docker.sock if the initial docker check fails.  We have simplified the Tomcat boot script to just do a hard fail if Docker is not properly configured. 

For the changes proposed by Alex, some of those checks belong in the che-launcher, which can detect if the user has provided a custom `DOCKER_HOST` and then provide additional parameters in the invocation of the che-server container.  But those tests are probably are suited for another issue in the che-dockerfiles repository.

**Comment by wernight** [comment]
Looking better. I didn't try but it sounds like this issue can be closed, unless you feel that it's important to handle `DOCKER_HOST` better (I think it's good but I feel there are more urgent issues out there).
