### ISSUE TITLE
Creating a new machine in the machine perspective doesn't appear in project perspective (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2759]
**Reproduction Steps:**
1) Add new machine in the Machine perspective. Make sure that this one has been created correct.
2) Go to the project perspective.
**Expected behavior:**
In the processes widget should appear just created machine
**Observed behavior:**
There is no the expected machine 

**Codenvy version:** 5.0.0.-M6
**OS and version:** Ubuntu 14 TLS, Chrome v. 53.

**Additional information:**
Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by bmicklea** [comment]
Closing this issue as "won't fix" because we are moving machine creation to the user dashboard.
