### ISSUE TITLE
Add a health check

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#2761]
In order to restart Che if anything is wrong (it seems to happens when messing around creating, renaming... workspaces), a `/healthz` page or similar would be useful.

Basically a HTTP GET on `/healthz` should just respond 200 and with content may be just `ok` if everything looks fine, and return any non-200 if something's wrong.

Example of similar implementation in some major projects:
- [Sentry](https://github.com/getsentry/sentry/blob/bfc711ed2579d8588f99170c75d974af3d4c8e96/docs/monitoring.rst) (see also [source code](https://github.com/getsentry/sentry/blob/master/src/sentry/middleware/health.py))
- [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html)
- [GitLab](https://docs.gitlab.com/ce/user/admin_area/monitoring/health_check.html)

**Comment by wernight** [comment]
Uh? Why closed?

**Comment by TylerJewell** [comment]
I am doing bulk closing of older issues to reduce open enhancement requests from 250 down to 150 along with moving all related issues from Codenvy over to Che, and then further consolidating related issues into unified ones for easier tacking.

In this particular case, we are formalizing Che on k8s support for Che 6 and this will be handled within k8s policies.

**Comment by wernight** [comment]
Is there an issue tracking Che support on k8s? Because there is no comment on #1193 regarding this.
