### ISSUE TITLE
Commands don't work in workspaces which were created from Bitnami stack [Regression]

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2764]
**Reproduction Steps:**
1. Create workspace with project from  Bitnami stack
2. Try run command

**Observed behavior:**
![commands](https://cloud.githubusercontent.com/assets/8051404/19305253/bff2bf2e-9078-11e6-8226-25abbfed3a59.png)

**Che version:**   5.0.0-M6-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:**  1.12.2
**Che install:** Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by AndreyChizhikov** [comment]
This problem is only in Che.

**Comment by vparfonov** [comment]
@slemeur can you help with it?

**Comment by JamesDrummond** [comment]
@AndreyChizhikov I will let Bitnami know.

**Comment by prydonius** [comment]
Thanks @AndreyChizhikov. The startup command assumes it is run in bash, which appears to work fine in Codenvy. I'm not entirely familiar with the way Che runs these commands in the containers. Perhaps @amrecio knows more.

The simplest solution would be to wrap the command in [.codenvy.json#L53](https://github.com/bitnami/bitnami-docker-express/blob/che/.codenvy.json#L53) in `bash -c`.

**Comment by prydonius** [comment]
Was something changed in the last milestone (5.0.0-M6) to do with the way the commands in containers are run?

**Comment by AndreyChizhikov** [comment]
This problem is reproduced on [hosted](https://nightly5.codenvy-stg.com) version too.

**Comment by AndreyChizhikov** [comment]
Cannot reproduce
