### ISSUE TITLE
Amount of machines is not correctly displayed in process tree [Regression]

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2775]
**Reproduction Steps:**
1. Create workspace from custom stack by using [compose file](https://gist.githubusercontent.com/idexmai/cb1a4ae1f51202ffc1cf72d1649edb1f/raw/44aef96d5c32348ae4d573905da197c487724de6/recipe_db)

**Expected behavior.**
In tree of processes is displayed  **dev-machine** and **db**
**Observed behavior:**
In tree of processes is displayed  **only dev-machine**
![machine](https://cloud.githubusercontent.com/assets/8051404/19338753/b01a4496-9127-11e6-94c5-39093387802a.png)

**Che version:**  5.0.0-M6-SNAPSHOT  
**OS and version:** Ubuntu 16.04 LTS
**Docker version:**  1.12.2
**Che install:**   Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by JamesDrummond** [comment]
Add current-sprint label.

**Comment by riuvshin** [comment]
@vparfonov what is the current status of this?

**Comment by vparfonov** [comment]
![che_2775](https://cloud.githubusercontent.com/assets/1636592/19703621/29d6f9fc-9b0d-11e6-84ae-47635c974113.gif)
