### ISSUE TITLE
Che launcher: not clear error message

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2777]
```
[11:47:36]sj:~#: che start
INFO: ECLIPSE CHE: Found image codenvy/che-server:latest
INFO: ECLIPSE CHE: Starting container...
time="2016-10-13T08:47:46Z" level=fatal msg="Error response from daemon: oci runtime error: exec: \"/home/user/che/bin/che.sh\": stat /home/user/che/bin/che.sh: no such file or directory"
[11:47:46]sj:~#:
```

```
[11:46:54]sj:~#: env |grep  CHE
CHE_LOGS_DIR=/Users/sj/.che/logs
CHE_LOCAL_CONF_DIR=/Users/sj/.che/
CHE_LOCAL_BINARY=/Users/sj/dev/src/codenvy/che/assembly/assembly-main/target
```

```
[11:47:46]sj:~#: docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by benoitf** [comment]
CHE_LOCAL_BINARY needs to set to a Che assembly folder
so it should contain the eclipse-**_-SNAPSHOT/eclipse-che-**_-SNAPSHOT/ folder at the end

maybe che script could check directory is a valid directory (contains all what is expected for a Che assembly like ./bin folder, ./conf folder, etc)

**Comment by skabashnyuk** [comment]
I see you point. But it's not clear what is going on from error message.

**Comment by benoitf** [comment]
sure

**Comment by TylerJewell** [comment]
This has been improved in #2786.  I am I. The process of rewriting the che.sh native scripts for tomcat, the che-server docker container and the Che-launcher.   There were some checks being done in the che-launcher that belonged in the che-server container.  This check was one of them.

**Comment by TylerJewell** [comment]
Resolved as part of PR: https://github.com/eclipse/che/pull/2786
