### ISSUE TITLE
Make alternative to CHE_LOCAL_BINARY

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2778]
CHE_LOCAL_BINARY is the path to unzipped che.
During development of che it looks like this

```
CHE_LOCAL_BINARY=/Users/sj/dev/src/codenvy/che/assembly/assembly-main/target/eclipse-che-5.0.0-M6-SNAPSHOT/eclipse-che-5.0.0-M6-SNAPSHOT
```

It contains version, that is not very good. Because it sometimes changes.
I'm proposing to add new variable  - path to zip with che.

```
CHE_LOCAL_BINARY_ZIP=/Users/sj/dev/src/codenvy/che/assembly/assembly-main/target
```

The important thing that it should not  require version

**Comment by benoitf** [comment]
I would opt-in for an option that use the assembly of the current che

so if we're in `/Users/sj/dev/src/codenvy/che`we could give a flag and then it will use 'current che assembly target folder'

note that to avoid to set full version name you could use
`CHE_LOCAL_BINARY=$(cd /Users/sj/dev/src/codenvy/che/assembly/assembly-main/target/eclipse-che-*/eclipse-che-* && pwd)`

but it could save extra time to use current che resulting assembly

**Comment by TylerJewell** [comment]
We could also have the assembly generator of maven copy the assembly into a directory that does not have the version numbers in it.  Something like /target/final.   I would note that florents syntax would not work on Windows.

**Comment by benoitf** [comment]
If we could use as we're inside a Che source folder

a syntax like `che --use-local-assembly start` would be a lot easier
no need to set any variable.

for windows I would prefer to not write the syntax as it is quite "challenging"

in the past we were using something like

```
set DIRNAME=%~dp0%
set FILE=%DIRNAME%\assembly-main\target\eclipse-che-*
for /F %%i in ("%FILE%") do (set VERSION=%%~nxi)

set ASSEMBLY_FOLDER=%DIRNAME%eclipse-che\target\%VERSION%\%VERSION%
```

**Comment by JamesDrummond** [comment]
I agree with Tyler but instead of copying, create a symbolic link `codenvy/che/assembly/assembly-main/target/eclipse-che` that points to `codenvy/che/assembly/assembly-main/target/eclipse-che-5.0.0-M6-SNAPSHOT/eclipse-che-5.0.0-M6-SNAPSHOT` .

**Comment by TylerJewell** [comment]
Symbolic links are not consistently implemented on windows so it's not a tactic we can use.

**Comment by JamesDrummond** [comment]
@TylerJewell I forgot that those files can be imported into che-server with CHE_LOCAL_BINARY environment variable from a Windows machine.

**Comment by TylerJewell** [comment]
@l0rd - suggested that we have some logic.  If we are in the current source repository and it is the che repository, we can parse the pom.xml to discover the current verison, and then assign the CHE_ASSEMBLY value to the current assembly.  We would only do this if CHE_ASSEMBLY is not currently set.

**Comment by skabashnyuk** [comment]
Any thoughts guys when it can be implemented?

**Comment by TylerJewell** [comment]
Specification is not clear - no solution proposed that makes sense yet.
