### ISSUE TITLE
Command editor should allow multi-line commands to be typed without using &&

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2780]
Today we allow people to create multi-line commands by either:
1. Adding "&&" between commands on a single line in the command editor.
2. Creating a multiline command outside the command editor and pasting it in.

There is no ability to add a return in the command editor itself. It would be better to allow Shift-Enter to be used for a return and Enter to accept the dialog.

**Comment by slemeur** [comment]
This will also be improved by refactoring the Commands Manager from a popup wizard, to a Command Explorer + Command Editor.
https://github.com/eclipse/che/issues/2681

**Comment by bmicklea** [comment]
Closing as it will be fixed by #2681
