### ISSUE TITLE
CHE using Docker on Mac with Chrome: Can't load project types: Error at Object.window.IDE.eventHandlers.initializationFailed 

### ISSUE THREAD

**Issue by JunhaoWang** [eclipse-che/che#2782]
The problem is shown in the picture

**Reproduction Steps:**
1. In Mac El Capitan Terminal 
`$che start`
2. Open Google Chrome and go to localhost:8080
3. Open a project

**Expected behavior:**

An interactive terminal should start normally and I would be able to program.

**Observed behavior:**

Can't load project types: Error at Object.window.IDE.eventHandlers.initializationFailed 

**Che version:**    nightly build
**OS and version:** OSX El Capitan
**Docker version:** Docker version 1.12.1, build 6f9534c
**Che install:**    Docker

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Happens all the time
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by JunhaoWang** [comment]
<img width="412" alt="screen shot 2016-10-13 at 3 23 11 pm" src="https://cloud.githubusercontent.com/assets/16586487/19364957/74568b04-915e-11e6-8922-a12303beab47.png">
<img width="568" alt="screen shot 2016-10-13 at 3 23 22 pm" src="https://cloud.githubusercontent.com/assets/16586487/19364972/8146c1e4-915e-11e6-9c26-6c9372b757dd.png">

**Comment by slemeur** [comment]
Could you please run the connectivity test:
https://eclipse-che.readme.io/docs/usage-docker#diagnose-boot-problems

``` Shell
che info --networking
```

It seems there is a problem in your Docker configuration.
Have you tried to execute the following instructions mentioned here:
https://eclipse-che.readme.io/docs/usage-docker#pre-reqs

``` Shell
# Grabs the IP address of the Xhyve VM
export DOCKER_VM_IP=$(docker run --rm --net host alpine sh -c "ip a show eth0" | \
                    grep 'inet ' | cut -d/ -f1 | awk '{ print $2}')

# Sets the loopback alias for the DOCKER IP
# You will be asked for your root password
sudo ifconfig lo0 alias $DOCKER_VM_IP
```

**Comment by ghost** [comment]
Commands that @slemeur has shared must be executed, otherwise the client (your browser) cannot connect to a workspace agent.

**Comment by slemeur** [comment]
@JunhaoWang did it solve your issue?

**Comment by TylerJewell** [comment]
Close due to no-response. Ok to open new issue.
