### ISSUE TITLE
Hello World Extension Not Working

### ISSUE THREAD

**Issue by nitingudleunvired** [eclipse-che/che#2784]
We are trying to design sample hello world extension for eclipse-che as mentioned https://eclipse-che.readme.io/v5.0/docs/helloworld-extension

Screenshots for how we configured che-helloworld-sample extension

**Steps** 
**# CREATE HELLOWORLDEXTENSION CLASS**
![5](https://cloud.githubusercontent.com/assets/22521564/19385215/09c4251c-922b-11e6-9bd4-e517b897fcc0.png)

**#  ADD DEPENDENCIES AND PARENT DEFINITION TO THE POM.XML** 
![4](https://cloud.githubusercontent.com/assets/22521564/19385348/a47abca6-922b-11e6-88af-3be74aba7275.png)

**# CREATE HELLOWORLDEXTENSION GWT MODULE**
![6](https://cloud.githubusercontent.com/assets/22521564/19385245/2a4444e8-922b-11e6-891f-02fed71ed427.png)

**# ADD HELLOWORLDEXTENSION GWT MODULE TO ASSEMBLY**
![3](https://cloud.githubusercontent.com/assets/22521564/19385315/815c860a-922b-11e6-909d-fafd48229fe6.png)

**# ADD EXTENSION TO ROOT POM OF CHE**
![1](https://cloud.githubusercontent.com/assets/22521564/19385259/41d3c494-922b-11e6-8d3f-46bc1f10d476.png)

**# LINK TO IDE ASSEMBLY**
![2](https://cloud.githubusercontent.com/assets/22521564/19385265/4aeacdf2-922b-11e6-9531-d7abf7bfe607.png)

 **Subsequently i have rebuild extension (che-helloworld-sample) and che (assembly-main)
but did not get the desire output as explained in docs**
![7](https://cloud.githubusercontent.com/assets/22521564/19385446/215d14b2-922c-11e6-87f5-d5bd06cc0f2b.png)

@vicky-unvired @eivantsov @alexanup @srinisubramanian

@TylerJewell @slemeur @azatsarynnyy @vparfonov @benoitf @eivantsov @vzhukovskii

**Comment by slemeur** [comment]
You have a typo in the way you registered the GWT Module.

**Comment by slemeur** [comment]
Ping me on skype and let's do screenshare please.

**Comment by slemeur** [comment]
In the docs, it is said that you have to rebuild "assembly-ide-war" and then rebuilt "assembly-main".
If you are not doing this (in this order), then Che's assembly will be built from the latest "assembly-ide-war" which was build and stored on your local Maven repository - in this cas, you'll not see the "HelloWorld" message.

**Comment by nitingudleunvired** [comment]
Finally it is running.

one step was missing, rebuild of assembly-ide-war (https://eclipse-che.readme.io/v5.0/docs/helloworld-extension#section-8-build-che-with-your-extension-) anyway...

@slemeur thanks :)
