### ISSUE TITLE
Chefile ip parameter

### ISSUE THREAD

**Issue by mdanter** [eclipse-che/che#2787]
There’s a hard-coded IP string address in the Chefile as a value of the key che.server.ip. Though the che ide is accessible via 127.0.0.1 as well. When the IP has changes, the workspace is not loading. the message in a standard modal dialog is:

```
Your workspace is not responding. To fix the problem, verify you have a good network connection and restart the workspace.
```

If there’s an IP specified in a file, that the IDE only binds to that IP, and I would love to receive an error at che dir up if the IP the file is specifying isn’t available.

after changing the chefile ip to 127.0.0.1, things are working as expected
**Reproduction Steps:**
1. have inaccuarete ip in Chefile
2. attempt to che dir up

**Expected behavior:**
che dir init should not create che.server.\* keys by default in the Chefile. Respectively, if it does, the command should verify that the IP specified is located on the host.
Also, if the ip is specified, the server should bind to that IP only.

**Observed behavior:**
When the IP has changes, the workspace is not loading. the message in a standard modal dialog is:

```
Your workspace is not responding. To fix the problem, verify you have a good network connection and restart the workspace.
```

**Che version:** 
nightly build corresponding to 

https://github.com/eclipse/che-dockerfiles/commit/7688a9214760e8eee9431a6581032bff2a0e8bf3

**OS and version:** 
macOS 10.12

**Docker version:** 
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Che install:**    Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: N/A
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by benoitf** [comment]
issue is now fixed. Thanks for the report @mdanter
