### ISSUE TITLE
"OOM of process" in container

### ISSUE THREAD

**Issue by mariosotil** [eclipse-che/che#2788]
I'm trying to deploy Che on a AWS server. I'm using this command

```
docker run \
           --network=host \
           --name che \
           --rm \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /home/user/che/lib:/home/user/che/lib-copy \
           codenvy/che-server -d --remote:x.x.x.x
```

 If I make it work on localhost works fine, but if I use --remote:x.x.x.x, I see a lot of these messages:

```
[eStopDetector-0]  [INFO ] [d.m.DockerInstanceStopDetector 137]  - OOM of process in container 3b836e6781713374a5ffc8b369632b3a0ddffdf5e08be54134405df2d5e4f575 has been detected
```

The EC2 instance is a t2.large. I checked it and every moment there's 4GB free of memory.

It seems the wsagent finally dies and the IDE is not able to connect to it. May you give me any advice about how to fix this?

Ubuntu Xenial 16.04
Docker version 1.12.2, build bb80604

**Comment by TylerJewell** [comment]
This issue may be related to #1988 - this generally happens when there are rogue processes within your workspace that are causing the workspace to lose all of its memory and then crash the workspace agent inside of it.  

My guess would be that there is something about your docker configuration that is preventing containers launched on the system from being allocated any memory.  The containers are being created with a small amount and not allowed to grow to use the memory available to them.

**Comment by mariosotil** [comment]
It's really weird. I changed the swapiness to 10 on Ubuntu, and using this command, but I still getting OOM messages :-(

```
docker run \
           --network=host \
           --name che \
           --oom-kill-disable \
           --memory=2048M \
           --rm \
           --memory-swap=-1 \
           -v /home/user/che/conf:/home/user/che/conf \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /home/user/che/lib:/home/user/che/lib-copy \
           codenvy/che-server -d --remote:x.x.x.x
```

**Comment by ghost** [comment]
@mariosotil this a Che server container while OOM is happening in your workspace container. How much RAM did you allocate for your workspace? What stack did you use and what command have you executed?

**Comment by TylerJewell** [comment]
@mariosotil - any update please?

**Comment by TylerJewell** [comment]
@mariosotil - we have launched an entirely new - very simple CLI.  It's been working great for people.  The docs for 5.0 have been updated as well.  Closing this for age.
