### ISSUE TITLE
Github oauth uploaded ssh key worked, terminal not using it

### ISSUE THREAD

**Issue by patricknazar** [eclipse-che/che#2789]
I've been able to set up OAUTH with the che.properties, which worked and che uploaded an ssh key to my github account. I can use git in the menu and it works fine. It's just in terminal i get Permission denied (public key) error. I've tried restarting the workspace no go.

**Reproduction Steps:**
1. Setup OAUTH for github
2. Import a project
3. Attempt git pull command in terminal, under newly created project directory

**Expected behavior:**

SSH connection to git works

**Observed behavior:**

Permission denied (public key) error

**Che version:**    4.7.2-1  
**OS and version:** Ubuntu 14.04.5 LTS
**Docker version:** 1.12.1
**Che install:**    Bitnami   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: I believe so
- Problem can be reliably reproduced, doesn't happen randomly: Appears so

**Comment by JamesDrummond** [comment]
The oauth and ssh key are stored in the che-server container. Only the menu/GUI will use this information for authorization. If you want to use a ssh key in for authorization in your workspace(s) terminal, you can set environment variable to something like `CHE_EXTRA_VOLUME_MOUNT=~/.ssh:/home/user/.ssh` to volume mount a private key from the host into the workspace(s) runtime machine.

**Comment by patricknazar** [comment]
I see, thanks for the clarification!
