### ISSUE TITLE
Che Mount - Accept Unison Profiles

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2791]
Add the ability to accept a unison profile, which is a document that allows a user to customize the list of files / directories that are replicated or ignored.  Unison profiles are very flexible and can contain multiple overlapping rules, and use a variety of pattern matching techniques.

Referenced pull request. [https://github.com/eclipse/che-dockerfiles/pull/28](https://github.com/eclipse/che-dockerfiles/pull/28) . Referenced issue #2742 .

**Comment by TylerJewell** [comment]
Not needed to create another issue when we have a user issue that already discusses the need.
