### ISSUE TITLE
Unexpected loss of focus on the project (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2795]
This bug is especially actual when run the selenium tests.

**Reproduction Steps:** 
- Create a project in the IDE (e.g. web-java-spring).
- Perform refresh.
- Open Git commands.

**Expected behavior:**
The Git commands should be enabled.

**Observed behavior:**
The Git commands are disabled.
If select the project in the project explorer, git commands become enabled.  

**Che version:**    5.0.0-M6  
**OS and version:**   Ubuntu 14.04  
**Docker version:** 1.12  
**Che install:**  Docker container   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- See the attachment:
  ![git_disabled](https://cloud.githubusercontent.com/assets/5408906/19431084/9e9fee1a-945f-11e6-86f7-e3b07a43b9b8.gif)

**Comment by musienko-maxim** [comment]
The problem related with many selenium tests

**Comment by riuvshin** [comment]
@vzhukovskii what is the status of this?

**Comment by vzhukovs** [comment]
@riuvshin PR created
