### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by nitingudleunvired** [eclipse-che/che#2797]
We are trying to build plugin with some action, this page
[Actions](https://eclipse-che.readme.io/v5.0/docs/actions#section-authoring-actions) we referring to start with sample

**This is an error in eclipse**
![error](https://cloud.githubusercontent.com/assets/22521564/19434123/56208e84-9481-11e6-94ef-d9e6bf204ead.png)

@vicky-unvired @eivantsov @alexanup @srinisubramanian
@TylerJewell @slemeur @azatsarynnyy @vparfonov @benoitf @eivantsov @vzhukovskii

**Comment by slemeur** [comment]
Please change by: getRootProject().

https://github.com/eclipse/che/blob/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/app/AppContext.java#L104
