### ISSUE TITLE
Add command macros that accept user input

### ISSUE THREAD

**Issue by binduwavell** [eclipse-che/che#280]
**Description of problem:**
- I have some commands (like npm test) that output ansi codes to produce pretty results, these work when run in the terminal but don't display correctly when running as a command. 
- I have some commands that require user input (like running a yeoman generator that requires the user to respond to several prompts.) It would be super cool if user input was possible for this use case. Then we can setup a bunch of yeoman generator and sub-generator commands to help new folks know what they can do.

**Che version:** `4.0.0-beta-13-1`
**Che install directory:** `~/Downloads/eclipse-che-4.0.0-beta-13-1`
**Docker version:** 

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Docker Info:** 

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: S6GZ:TD7N:M4BZ:J6DK:RN3E:455I:YTPI:BDY4:32XR:ONHD:MGDJ:HFVC
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 39
 System Time: 2016-02-07T22:56:03.470098201Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: binduwavell
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Java version:** `N/A I'm using che.sh run -i (so whatever you have in your container)`
**Environment details (AWS, VirtualBox, physical, etc.):** `I'm on my mac using the default dockertoolbox 0.10 and default che 4.0.0-beta-13-1.`

**Comment by TylerJewell** [comment]
@binduwavell - hi we are doing some long term planning and thinking more about how to improve commands. We have in the next sprint an exercise to make it possible for a much larger selection of macros for commands.

I had a question for you - if instead of supporting ansi and input in command consoles, we allowed you to optionally launch the command inside of an open terminal, and if one is not open, launch it into a new terminal window, would this be a suitable solution?

**Comment by ashumilova** [comment]
@binduwavell we will investigate the way for us to support ansi codes in commands output as well.

**Comment by TylerJewell** [comment]
@binduwavell - this is now getting studied for commands.
https://github.com/eclipse/che/issues/2151
