### ISSUE TITLE
Maven modules not recognized

### ISSUE THREAD

**Issue by Teg79** [eclipse-che/che#2805]
Maven modules in a maven multi-module project are normal folders, not java projects

**Reproduction Steps:**
1. Clone a maven multimodule project from github (https://github.com/Teg79/BBArena)

**Expected behavior:**

The maven modules must be parsed like java projects with packages and java and test source folders

**Observed behavior**

In project explorer the parent pom is a regular project, but it's modules are normal folders

**Che version:**    Codenvy.com online version
**OS and version:** macOS 10.12.1

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: don't know
- Problem can be reliably reproduced, doesn't happen randomly: yes

**Comment by TylerJewell** [comment]
The project type must be set to maven.  When you clone the project, did you open the project configuration wizard and set it to maven?  We built Codenvy and Che with maven multi modules, so this is something that is tested and used often.

**Comment by Teg79** [comment]
Yes, I set it to maven.
If I right click on a module pom and press update then sometimes it becomes a java project but only until the next restart

**Comment by TylerJewell** [comment]
It's possible you have stumbled into this bug.  https://github.com/eclipse/che/issues/1725.  It's not consistent.  @vparfonov

**Comment by Teg79** [comment]
Thank you, the problem is resolved.
The project in the master branch is empty, so after the clone the IDE cannot find any maven or java projects. 
After switching to the develop branch the maven modules are added to the file system but you need to go to Project -> Update Project Configuration -> Select again Maven -> Save
