### ISSUE TITLE
How can we setup environments with multiple machines?

### ISSUE THREAD

**Issue by binduwavell** [eclipse-che/che#281]
**Description of problem:** It is not clear to me how to setup an environment with multiple machines, is that possible yet?

**Che version:** `4.0.0-beta-13-1`
**Che install directory:** `~/Downloads/eclipse-che-4.0.0-beta-13-1`
**Docker version:** 

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Docker Info:** 

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: S6GZ:TD7N:M4BZ:J6DK:RN3E:455I:YTPI:BDY4:32XR:ONHD:MGDJ:HFVC
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 39
 System Time: 2016-02-07T22:56:03.470098201Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: binduwavell
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Java version:** `N/A I'm using che.sh run -i (so whatever you have in your container)`
**Environment details (AWS, VirtualBox, physical, etc.):** `I'm on my mac using the default dockertoolbox 0.10 and default che 4.0.0-beta-13-1.`

**Comment by ddementieva** [comment]
It's possible to create the additional machines in the Machine Perspective, using our default images (you can find them at https://github.com/codenvy/dockerfiles) or your own custom recipes. 

Click the Recipes tab on the left side of the IDE and create your recipe using NEW or COPY button. Now you can go to the Machine > Create... menu, add machine's name and recipe URL (it's also possible to find it by tags) and create new machine there. 

Your machine will appear in the Machines list on the left side of the IDE. Temporarily all new machines will be named as docker, it's a bug on our side, we have a GitHub issue on that at https://github.com/codenvy/che/issues/249 and we are trying to fix it asap.

After a successful machine creation you can use swagger (http://localhost:8080/swagger/#!/machine/executeCommandInMachine) to execute commands in it.

**Comment by binduwavell** [comment]
I hope to give this a try this weekend when I should have time to dig back into che.

**Comment by ghost** [comment]
@binduwavell i am closing the issue, as there seems to be no problems with running additional machines in a workspace. Feel free to reopen if you run into issues or have questions.
