### ISSUE TITLE
Some commands that have worked through bash shell, can work wrong (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2811]
**Reproduction Steps:**

After setup of **sh** as default shell in the Codenvy - some commands that was saved early will be wrong. For example some workspace used command like: `echo -e 'some text for check' > ~/check.txt.`

**Expected behavior:**
After execution the command - should be created the check.txt file with next content: **some text for check**

**Observed behavior:**
The content in the file will be like: **-e some text for check**  (-e flag will be added into file)

This problem may do many unexpected results for commands, that were saved in the workspaces created earlier. The same problem can be in the factories, which use bash commands. Many  users may be puzzled.

**Che version:**  5.0.0-M6-SNAPSHOT  
**OS and version:** Ubuntu 14.04 LTS
**Docker version:**  1.12.2
**Che install:**   Docker container

**Comment by JamesDrummond** [comment]
Add current-sprint label.

**Comment by benoitf** [comment]
@musienko-maxim please check with next nightly

**Comment by musienko-maxim** [comment]
The test (LoginBySshTest) that covers this feature - passed. I think issue can be closed.
