### ISSUE TITLE
Service owned by current user

### ISSUE THREAD

**Issue by worksamp** [eclipse-che/che#2818]
I am using swagger api for eclipse che.

I need to get ssh key for workspace, for this I am using following api:

http://ip-address/api/ssh/servicename

Can you please tell me what is the "servicename" in this?
Swagger url: http://<ip-address>/swagger/#!/ssh/getPairs

**Comment by ddementieva** [comment]
@worksamp Service here is:
vcs - to get all the SSH keys generated for git and svn hostings;

machine - to get all the SSH keys used to connect from the local machine to the workspace machine.

**Comment by worksamp** [comment]
@ddementieva :+1: 
Thank you so much for your help.
Its working :-)
