### ISSUE TITLE
"No workspace selected. Unable to open IDE" displayed while opening the IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2820]
There is a odd message displayed while loading the IDE as an iframe from the dashboard.

![loading-bug-no-workspace-loaded](https://cloud.githubusercontent.com/assets/1636769/19511662/6f286f92-95e8-11e6-8190-dcaa257688ef.png)

See attached animated gif:
![loading-bug-che](https://cloud.githubusercontent.com/assets/1636769/19511746/db5bbd90-95e8-11e6-9883-57f60fe6e3bd.gif)

See issue: https://github.com/codenvy/codenvy/issues/985

We need to display this message, only when it is accurate and no workspace has been selected. We should not display it while opening the IDE.
We need to remove the placeholder message from:
https://github.com/eclipse/che/blob/master/dashboard/src/app/ide/ide.html

**Che version:**    5.0.0-M5

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: No

**Comment by akurinnoy** [comment]
time spent: 2d
