### ISSUE TITLE
How To Start many che instances on same machine

### ISSUE THREAD

**Issue by achabahe** [eclipse-che/che#2821]
Hi tyler ! how would i start a second instance of eclipse che , bitnami created an instance of eclipse che running in the cloud i need to start an other instance of eclipse che on that same VM , and assign to that instance a user and a password

**Comment by ddementieva** [comment]
@achabahe Can you please specify how you start Che? Using docker launcher?

**Comment by achabahe** [comment]
i actually don't use docker launcher to start it (i am just a beginner in this IDE) !! i use CLI to start and stop eclipse che instance
'sudo su eclipseche -- /opt/bitnami/apps/eclipseche/che/bin/che.sh -p:8080 -s:uid stop'
when I do that bitnami give me 503 error (Service Unavailable).
which means the eclipse che has shutdown and bitnami can't  find an eclipse che instance listening on port 8080 but when i do start an eclipse che instance using command 
"sudo su eclipseche -- /opt/bitnami/apps/eclipseche/che/bin/che.sh -p:9090 -s:uid stop"
which should start an instance of eclipse che instance on port 9090 it doesn't start (i use netstat to check if port 9090 is on listening)

**Comment by achabahe** [comment]
forgive my mistakes if i have some miss consumption , i am still a beginner !!!

**Comment by ddementieva** [comment]
@achabahe Can you try to execute run command, not start, e.g. `sudo su eclipseche -- /opt/bitnami/apps/eclipseche/che/bin/che.sh -p:9090 -s:uid run`, and send us logs?

**Comment by achabahe** [comment]
Here you GO!!
[log.txt](https://github.com/eclipse/che/files/538699/log.txt)

**Comment by achabahe** [comment]
i mistakenly closed the coversation

**Comment by achabahe** [comment]
my bad !!

**Comment by TylerJewell** [comment]
The log says that port 32001 is already in use.  Your second instance is trying to deploy some rmi package that must be already deployed in your first instance.   I don't believe this is a Che issue but it is an issue with how bitnami repackages Che.  I am not sure that bitnami ever intended their vm to allow for more than one server at a time.   I think they want you and need you to create separate vm.

**Comment by achabahe** [comment]
probably that is what they want me to do !! i might deploy docker container of bitnami eclipse che in my VM that would solve partialy my problem but i can't find a docker container of bitnami eclipse che  do you know how i can find it !!! they this link should take me to it but it does not work [broken link to eclipse che docker container](https://bitnami.com/docker?ref=eclipse-che)
and this is the page that gave me that [link](https://bitnami.com/stack/eclipse-che)

**Comment by TylerJewell** [comment]
You would need to talk to bitnami about what they can provide for you.  The Che project provides certified Docker images - we recommend that you use the che-launcher image; https://eclipse-che.readme.io/v5.0/docs/usage-docker
