### ISSUE TITLE
Project registry works wrong  if a factory has invalid mixin type

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#2831]
**Reproduction Steps:**
1. Go to the Dashboard -> Factories ->Create factory ->Templates -> Complete
2. Change value 'mixin' on invalid 
3. Consume the factory
   ![anim](https://cloud.githubusercontent.com/assets/1640058/19524550/cb3f3c3c-9626-11e6-8392-a2527ade7360.gif)

**Expected behavior:**
An user should be informed about invalid mixin type. The workspace creation should be interrupted.
**Observed behavior:**
Infinity loop during a workspace creation

**Codenvy version:**  5.0.0-M5
**OS and version:** Ubuntu 14.04 LTS
 **Related issue:** https://github.com/codenvy/codenvy/issues/977
**Stack trace:**   [download.txt](https://github.com/eclipse/che/files/539401/download.txt)

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
