### ISSUE TITLE
Error while creating java project

### ISSUE THREAD

**Issue by worksamp** [eclipse-che/che#2839]
Hi,

I have installed eclipse che successfully.
I am accessing it using: localhost:8080
Successfully able to create dot net workspace successfully but not able to create java workspace.

I am getting following error:
Error: Can't load project types: Error
at Object.window.IDE.eventHandlers.initializationFailed (http://localhost:8080/ide/che/wksp-odt1?uid=740979:39:27)
at hsb (_app-0.js:1969:166)
at usb (_app-0.js:1974:454)
at _.gp (_app-0.js:4236:317)
at eval (_app-0.js:935:130)

can you please help me with this

**Comment by ddementieva** [comment]
@worksamp how much RAM did you allocate for the Java workspace? Can you try to create a new Java workspace with more RAM?

**Comment by worksamp** [comment]
@ddementieva : 
I didnt do any changes ,it automatically get started
