### ISSUE TITLE
Unable to close process tab after close canceling

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#2840]
**Reproduction Steps:**
1. Open a workspace
2. Run command which takes some time
3. While command is running try to close output tab
4. In appeared dialog click `cancel`
5. Try to close tab again

**Expected behavior:**
New dialog which ask whether terminate process

**Observed behavior:**
Nothing happens. It is impossible to close the tab.
Closing it from tab-list has no result, just removing from tab-list.
For mere info see attached screencast.

**Che version:**   5.0.0-M6-SNAPSHOT  
**OS and version:** Ubuntu 16.04
**Docker version:**  CLI: Version:  1.12.1   API version:  1.24
**Che install:**  server (zip)

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes
  ![closeexecbug](https://cloud.githubusercontent.com/assets/15607393/19552824/34145402-96ba-11e6-92ea-edf32dffd25e.gif)

**Comment by mmorhun** [comment]
New commands didn't fix this issue.

**Comment by azatsarynnyy** [comment]
fixed
