### ISSUE TITLE
import from Google Cloud VCS

### ISSUE THREAD

**Issue by Xaver2k** [eclipse-che/che#2842]
hi guys, i uploaded an android project from android studio to Google´s VCS. Now i want to import this project in eclipse che. Does anybody know how to do this and to use google´s vcs like in android studio as a git for eclipse che????

i´m trying this on beta.codenvy.com and they told me to ask here ^^

Thanks in advance

**Comment by TylerJewell** [comment]
Did you take a look at the docs on git?  https://eclipse-che.readme.io/docs/git.  This is an open source project and the community can help you out with any problems that you are having, but you need to provide a full set of steps of what you are attempting, so that an engineer or another community member can try to reproduce any issues that you may have.   

https://github.com/eclipse/che/blob/master/CONTRIBUTING.md

**Comment by Xaver2k** [comment]
hey Tyler, sorry i am really new to all that git stuff ^^

in the che ide i go to 
"workspace - Import project"
Select "Source Control - Git"
in URL "https://source.developers.google.com/p/my-project-id-here"
then i click "import"
and i get the error message
![test-import](https://cloud.githubusercontent.com/assets/7150036/19562652/64e63d66-96dd-11e6-8c07-e0ba336dd015.JPG)

i tried adding SSH Keys from google cloud console in my workspace but i´m not sure if this is even compatible.

**Comment by TylerJewell** [comment]
@jamesdrummond, @ddementieva  - please take a look at this and see if you can provide some guidance.  @Xaver2k - this looks like the SSH keys for Google VCS were not properly loaded into your IDE.  It's not obvious, but in IDE Preferences, you need to add your SSH keys for each repository, otherwise it will not work.

**Comment by Xaver2k** [comment]
i generated a key in the google cloud console and downloaded it as a JSON file
![test-cloudconsole](https://cloud.githubusercontent.com/assets/7150036/19572675/8f3ad5a6-9703-11e6-891f-cc576e99acf7.jpg)
(i don´t know if this is even right)
and then at beta.codenvy.com in the eclipse che ide, i went to 
Profile - Preferences
SSH - VCS
button Upload Key

and there i tried as Host: https://source.developers.google.com and source.developers.google.com
and as file i used the previous downloaded JSON file.

**Comment by JamesDrummond** [comment]
@Xaver2k I do not have a project setup with google for testing. From what I can tell, google uses oAuth to authenticate. Maybe there is a ssh git url that they provide like `git@<git url>:<account>/<project>.git` .  In our docs it's stated at the end of the ssh section "Note: HTTPS url can only be used for oauth authentication described in Git Using oAuth." We currently only support oAuth with github.

One work around is to link your google account with a github(paid private) or bitbucket(private) repo as described on google's docs [https://cloud.google.com/source-repositories/docs/connecting-hosted-repositories](https://cloud.google.com/source-repositories/docs/connecting-hosted-repositories) .

**Comment by TylerJewell** [comment]
@JamesDrummond @eivantsov - we might need to escalate this to higher in support.

@Xaver2k - is this issue still actual?

**Comment by ghost** [comment]
@Xaver2k What is the format of a JSON file? When you uploaded the key in Codenvy, did you use private or public part of the key?

**Comment by Xaver2k** [comment]
Hey i didn't try it anymore as i moved everything to github, because it was the easiest. But i will check it on the weekend.

**Comment by ghost** [comment]
The trick is to get the right key and add it with the right hostname to Che.

**Comment by Xaver2k** [comment]
@eivantsov Thank you for the info.
Can you provide a step by step guide, please?

**Comment by ghost** [comment]
@Xaver2k when you get a json, what format is it? Can you share it (change key values of course)? When adding a key in Che you need to specify hostname which I think should be source.developers.google.com

Keys are added at Profile > Preferences > SSH > VCS
