### ISSUE TITLE
There is no modelling tool on Eclipse Che

### ISSUE THREAD

**Issue by JohnUethTosij** [eclipse-che/che#2844]
Hi,

Im curious about if modelling resources is planned to Eclipse CHE, we know Microsoft will make UML to be ejected from Microsoft Visual Studio on next version [01] and about bpm there is no plan from Camunda BPM to integrate the web modeller with Eclipse CHE [02], a trend on reactive systems is strong but the Service Component Architecture (SCA) is now almost dead as we can see on internet [03], about BPM there is GPL and ready to use web based BPM editors made by Camunda [04] and Eclipse has the Eclipse Stardust BPM Project also done [05] and the Eclipse Sirius Project that dramatically reduces the time for creating domain-specific modeling tools [06], JBoss, have tools related and is part of Red Hat that is a Eclipse CHE Partner [07] and there is research on modelling for reactive systems [08]. 
What are the plans for modelling on Eclipse CHE  ?
CHE is an acronym for what ?

[01] - http://www.infoworld.com/article/3131600/application-development/uml-to-be-ejected-from-microsoft-visual-studio.html
[02] - https://forum.camunda.org/t/eclipse-che-for-camunda/430
[03] - https://lists.oasis-open.org/archives/sca-assembly-comment/201502/msg00000.html
[04] - {
            https://bpmn.io/
            https://bpmn.io/toolkit/bpmn-js/
            https://github.com/camunda/camunda-bpm-workbench
            http://stackoverflow.com/questions/13617409/open-source-framework-to-build-web-based-bpmn-designer
            https://orionhub.org
        }
[05] - http://www.eclipse.org/stardust/
[06] - https://eclipse.org/sirius/
[07] - {
            http://developers.redhat.com/blog/2016/06/27/red-hat-eclipse-che/
            http://switchyard.jboss.org/
            http://people.redhat.com/tsurdilo/vid/execprocess.swf
            http://hawt.io/
        }
[08] - {
            https://imve.informatik.uni-hamburg.de/projects/VisualAFRP
            http://rxmarbles.com/
            https://github.com/curran/model
            http://blog.takipi.com/async-goes-mainstream-7-reactive-programming-tools-you-must-know/
        }

Thanks

**Comment by TylerJewell** [comment]
Hi - thanks for the exhaustive list of resources.  The community has been discussing adding a modeling layer to Eclipse Che on this issue - https://github.com/eclipse/che/issues/1177.  If you don't mind, I will cross link this issue and close this one, as I'd like to keep #1177 as the tracking issue overall.

Two years ago, we built a prototype of some technology which would provide a modeling layer. Also, Genmymodel has discussed the possibility of contribruting their platform to the open source layer which we would package within Che.  There is also experimentation work being done with some large fortune companies whose name that I cannot mention yet.  We built a sequence editor that was BPM-like inside of che for Eclipse Che 3.x generation and we have a technology that we call CMF which generates Che editors from a modeling syntax.  We have not ported it to the 4.x and 5.x branch, but we will likely do so once the community organizes around a modeling project or if my company, Codenvy, gets a commercial contract to do so.  

We would prefer the community organizing itself to add this layer in conjunction with our core engineers.  It is not a simple task, and it would require a sustained commitment.  I think we are close to having that sort of interest, as the conversation comes up every week now.  But if you are wanting to roganize something, there are others who want to talk with you.

Che is the name of the city that the product was invented in the Ukraine.
