### ISSUE TITLE
Cordova/Phonegap stacks, templates, and commands

### ISSUE THREAD

**Issue by JohnUethTosij** [eclipse-che/che#2845]
Cant found Cordova provider here: https://eclipse-che.readme.io/docs/get-started-with-nodejs-and-che  

There is some planned?? 

Thanks

**Comment by TylerJewell** [comment]
Hi - I think on this one, you can provide your own custom stacks and extension that add this capability for users.  So this sort of extensibility is built into the solution.   https://eclipse-che.readme.io/v5.0/docs/stacks.  If the community were to provide an extension and a set of certified stacks as a PR, then we could merge that in and it would be part of a certified distribution.
