### ISSUE TITLE
Wrong hover tooltip behavior

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2846]
The tooltip's behavior on Dashboard is creating problem of usability.

When moving fast the pointer over multiple elements where a hover can be displayed, all tooltips are displayed at the same time.

We should always display only one tooltip at a time.

See attached animated gif:
![behavior-when-hover](https://cloud.githubusercontent.com/assets/1636769/19565427/19e4c97c-96e7-11e6-9e7e-074447360635.gif)

**Che version:**    5.0.0-M5

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No
- Problem can be reliably reproduced, doesn't happen randomly: No

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/3286/commits/7f340fb11f557f96807ad29c475229fd3c379de1
