### ISSUE TITLE
"fast" profile does not disable "skip-validate-sources"

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#2848]
After some tests of this profile it looks like `-Pfast` is not disabling the validate source profile

using `-Dskip-validate-sources` is working but using `-Pfast` not

```
$ mvn -Pfast help:active-profiles |grep validate-sources
 - validate-sources (source: org.eclipse.che.parent:maven-parent-pom:5.0.0-M6-SNAPSHOT)
 - validate-sources (source: org.eclipse.che.parent:maven-parent-pom:5.0.0-M6-SNAPSHOT)
 - validate-sources (source: org.eclipse.che.parent:maven-parent-pom:5.0.0-M6-SNAPSHOT)
```

`$ mvn -Pfast -Dskip-validate-sources help:active-profiles |grep validate-sources
`
**Expected behavior:**
It is expected that using "fast" profile will disable "skip-validate-sources"

**Che version:**    [5.0.0-M6]  
**OS and version:** [All]   

**Additional information:**
more details can be found in the https://github.com/eclipse/che/pull/2733

**Comment by ibuziuk** [comment]
Basically, one can not activate a profile when another one is activated (chaining activation is prohibited in maven). skip-validate-sources actually enables another profile - https://github.com/eclipse/che-parent/blob/master/pom.xml#L1651 

Also it is not possible to configure **OR** logic for profile activation - 

```
      <profile>
            <id>validate-sources</id>
            <activation>
                <property>
                    <name>!skip-validate-sources</name>
                    <name>fast</name>
                </property>
            </activation>
```

it used to be possible  before v3.2.2 but now it is "fixed" -  https://issues.apache.org/jira/browse/MNG-4565

For now it is not possible to configure **OR** condition for maven profile activation unless using a copy-paste approach - having two identical profiles with different activation logic. At the same time, chaining profile activation is also prohibited. So, there are two possible things we can do:
1. Remove skip-validate-source from fast profile (using the profile would include resource validation step )
2. duplicate skip-validate-source profile with different activation logic e.g.

```
<activation>
  <property>
    <name>fast</name>
  </property>
</activation>
```

and change fast profile activation logic the same^ way - after that it would be possible to use **"-Dfast"** for acctivation

WDYT ?

**Comment by TylerJewell** [comment]
I think your proposal on #1 is a good enough work around.  Skipping validation doesn't buy you that much time.

**Comment by ibuziuk** [comment]
@TylerJewell agree, PR for removing "skip-validate-sources" from "fast" maven profile has been sent.
It would be great if some one with maven experience confirm that there is no other options for tackling the issue

**Comment by TylerJewell** [comment]
@skabashnyuk will chime in at some point - went ahead and merged the change so that we have it for now.

**Comment by ibuziuk** [comment]
@TylerJewell great, thanks!
