### ISSUE TITLE
The eclipse che can't start a workspace

### ISSUE THREAD

**Issue by achabahe** [eclipse-che/che#2849]
when I create a workspace the ide keeps telling me initializing the workspace for ever!
1i used bitnami to initialize for me a machine with eclipse che in the cloud 
2I tried to create a worksapace i allocated 4 GB of  RAM and used java stack for it
then it keeps initializing it 4 ever 
SPECS:
Docker version : 1.12.1
machine ram: 13 GB
diskspace 500GB

**Comment by TylerJewell** [comment]
This request does not match our contribution guidelines.  Please, you must spend time investigating the issue and providing information thta makes it possible for others to recreate your issue.  If it cannot be reproduced in steps, then it will not be taken as an issue.  You can open new issues, but please follow the guidelines.

https://github.com/eclipse/che/blob/master/CONTRIBUTING.md

**Comment by achabahe** [comment]
i updated the issue

**Comment by achabahe** [comment]
when list the containers in the machine i see that the docker container of that workspace machine has been created but after a while it gets shutdown and removed i suspect that it is configured to remove the container wonce it can't start
