### ISSUE TITLE
The eclipse che can't start a workspace

### ISSUE THREAD

**Issue by achabahe** [eclipse-che/che#2851]
when I create a workspace the ide keeps telling me initializing the workspace for ever!
1i used bitnami to initialize for me a machine with eclipse che in the cloud 
2I tried to create a worksapace i allocated 4 GB of RAM and used java stack for it
then it keeps initializing it 4 ever 
SPECS:
Docker version : 1.12.1
machine ram: 13 GB
che install : bitnami
diskspace 500GB
linux : Linux eclipseche-1-vm 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

obeservation:
when list the containers in the machine i see that the docker container of that workspace machine has been created but after a while it gets shutdown and removed i suspect that it is configured to remove the container wonce it can't start

**Comment by achabahe** [comment]
i want to delete this issue , all the problems arre coming from BITNAMI wich provides a virtual machine with eclipse che full of bugs or i don't know what the heck was that !!!! i recently installed a docker on my debian machine and installed eclipse che and it is working like charm ! sory @TylerJewell  again for bothering you !!

**Comment by TylerJewell** [comment]
Ok - we will close the issue - thanks for the persistence on this.  It's possible that you were on a firewall that prevented you from communicating between your browser and Bitnami.  There is a lot of internet between us and Bitnami.
