### ISSUE TITLE
Overwriting of name of workspace on creation with auto generated value

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#2855]
**Reproduction Steps:**
1. Go to Dashboard -> `Workspaces` -> `Add Workspace`
2. Type name of new workspace
3. Switch to `Runtime` tab and go back to `Settings` tab
4. Click on `Create` button

**Expected behavior:**
Workspace with inputted name will be created

**Observed behavior:**
Workspace is created, but has auto generated name

**Che version:** 
**OS and version:** Ubuntu 16.04
**Docker version:** CLI: Version: 1.12.1 API version: 1.24
**Che install:**  server (zip)

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes
  ![unexpectednameofworkspace](https://cloud.githubusercontent.com/assets/15607393/19588645/ce7e9966-976f-11e6-9a85-0331ec8db00a.gif)

**Comment by olexii4** [comment]
Cannot Reproduce
