### ISSUE TITLE
Cannot build on windows "npm" command not found

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#2858]
The maven build is failing on windows because it can't find npm executable.
Ant can't launch executable without extensions. See http://ant.apache.org/manual/Tasks/exec.html "Windows user"

This line (and the following) need to be modified https://github.com/eclipse/che/blob/master/dashboard/pom.xml#L62

**Reproduction Steps:**
1. launch mvn clean install -Pfast on Windows

**Expected behavior:**

maven build success

**Observed behavior:**

maven build fail

**Che version:**    [Enter Che version here]  
**OS and version:** Windows 10
**Docker version:** [Enter your Docker version here `docker version` on CLI]  
**Che install:**    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by TylerJewell** [comment]
@apupier - there are certain submodules that require additional libraries to be installed in order for the compilation to work.  You can:
1: Either install these libraries and rerun
2: Skip the modules, or:
3: Use our che-dev Docker image which includes all necessary dependencies

For what it's worth, it's only the subversion and dashboard modules that require these additional dependencies.

We have tried to keep this section of the docs clear on what is going on - but if you think something is missing, let us know.  https://github.com/eclipse/che/wiki/Development-Workflow#build-and-run---tomcat

**Comment by apupier** [comment]
@TylerJewell npm is installed, it is a limitation of Ant on Windows.

'For what it's worth, it's only the subversion and dashboard modules that require these additional dependencies.'
i'm currently trying to setup an environment for the EclipseCon Europe tutorial and so I'm following the instructions sent by mail. Maybe I don't need these dependencies?

**Comment by slemeur** [comment]
@apupier : During the tutorial, we will not change the dashboard or the subversion plugin. So it's ok to skip building these modules. 

But agree that this is an issue which needs to be addressed for a broader purpose.

**Comment by TylerJewell** [comment]
@slemeur - harumph.  What do you mean by addressing it - what is the solution, and can we consider having kabashnyuk's team consider it next sprint?

**Comment by apupier** [comment]
the solution is to provide different configuration based on the OS.
For Windows, you will need to use npm.cmd and not npm.

**Comment by apupier** [comment]
but next steps seems not trivial, I can't find the correct command that need to be put for bower, seems that there is no bower.cmd or bower.bat

**Comment by slemeur** [comment]
Maybe we should be clearer for developers on Windows.
Either they skip the tests + build of dashboard, or if they want to do a complete build of Che, they do it in the che-dev Docker image

**Comment by slemeur** [comment]
I added information into the documentation:
https://eclipse-che.readme.io/v5.0/docs/setup-che-workspace#developers-on-windows

I'll add a similar section on the wiki: https://github.com/eclipse/che/wiki/Development-Workflow

@skabashnyuk + @benoitf : I'm not sure about a solution for that problem. Have you got some ideas? Is that something we can fix?

**Comment by benoitf** [comment]
For dashboard it would be to build it with docker son we're sure of all dependencies
The same for module using 'patch' maven plugin as most of users don't have 'patch' tool installed
