### ISSUE TITLE
Provide better alignements in the Process panel

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2859]
The alignements of the icons in the Process panel are not correct.
![screen shot 2016-10-21 at 17 05 21](https://cloud.githubusercontent.com/assets/1636769/19603263/ceb0dbf6-97b0-11e6-9600-470c63b4183d.png)

We need to improve that so the alignement will be better handled:
![screen shot 2016-10-21 at 17 05 34](https://cloud.githubusercontent.com/assets/1636769/19603353/2229b532-97b1-11e6-8cec-38f3f0006ec7.png)
- moved objects: 
  - expand/collapse arrow
  - state icon
- height reduced:
  - resources widget

**Che version:**   5.0.0-M6

**Comment by vitaliy-guliy** [comment]
Spent 4 hours.
