### ISSUE TITLE
Updating .NET Core Template and Maintainer

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2862]
I've already contributed the PR to eclipse/che-dockerfiles#30 and have signed the CLA (I have a screenshot in the PR). There has been no merge so far and I have been informed to post here so it makes the next sprint.

**Comment by JamesDrummond** [comment]
@eivantsov @ddementieva Please add label so we can track.

**Comment by ghost** [comment]
@eivantsov Any update? One of your competitors has shut down, so many will be looking for a strong alternative.

**Comment by TylerJewell** [comment]
@rogersachan - it's been slotted for the M8 milestone.  We are releasing the 5.0-M7 milestone in a day or two, and we anticipate that M8 will not be long as it is focused entirely on bug fixes and stabilization.

**Comment by bmicklea** [comment]
Closing as this PR has been merged: https://github.com/eclipse/che-dockerfiles/pull/30
