### ISSUE TITLE
che.sh + docker: IPs and ws-agent timeouts

### ISSUE THREAD

**Issue by jc776** [eclipse-che/che#2864]
First time running Che locally, I'm using the `che start` launcher. The first workspace I started, '.NET stack' with 'aspnet-web-simple' had a dialog "Workspace Connection Error" and continuous error popups "Connection failed with terminal" in the editor.

There are browser console errors timing out on to an IP that's on the `docker0` Ubuntu network, which an external machine's browser can't see.
The dialog suggested customizing che-server's "--remote", but links to a README that only talks about environment variables for che-launcher, which `che start` uses indirectly.

~~"Maven server not started looks like you don't have Maven in your path"~~ - not relevant.

**Reproduction Steps:**

What I've done so far...
1. I installed Ubuntu 16.01 on a clean VM (VirtualBox in Windows 10)
2. Made it a 'bridged network' so I can connect to it from host/home network
3. I'm running commands inside the VM on a terminal. I'm not using `docker-machine` or anything.
4. `sudo apt-get install docker.io`, added myself to docker group, etc until `docker run hello-world` works
5. From [https://eclipse-che.readme.io/docs/che-getting-started]:

```
mkdir ~/bin
curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > ~/bin/che
chmod +x ~/bin/che
```
1. `che start`, wait until "Booted and reachable"
2. Use che (from the PC hosting the VM, not inside the VM) at `[vm's hostname]:8080`.
3. Made a new workspace with the ".NET" stack and the "aspnet-web-simple" template.
4. Errors start at "Starting workspace agent".
   (See discussion for later attempts using CHE_HOST_IP and nightly)

**Expected behavior:**

The workspace starts without errors...

~~If Maven is a dependency...~~ - Not relevant.

**Observed behavior:**

"New Workspace" screen stops at "Starting Workspace Agent". [che-dotnet-workspace-log.txt](https://github.com/eclipse/che/files/545885/che-dotnet-workspace-log.txt)
"Workspace Connection Error" dialog pops up a bit later talking about '--remote:<ip-address>', not sure if it's relevant? The browser using Che is outside the VM, but the workspace containers are in the same Docker daemon as Che. The [configuration readme](https://eclipse-che.readme.io/docs/configuration#envrionment-variables) linked doesn't mention "--remote" directly at all.

The workspace appears to have been created, but nothing's working right when opening it: "Starting workspace agent" takes forever, repeated popups "Connection failed with terminal".

If I use the .NET stack in 'codenvy beta', none of these problems happen.

**Che version:**  Whatever today's che.sh downloaded:
codenvy/che-server:latest 81c28128c057 "6 weeks ago" (See discussion for later attempts using nightly)
codenvy/che-launcher:nightly 8d79343ce840 "4 weeks ago"
codenvy/dotnet_core:latest 8bb4970ceaba "10 weeks ago"
**OS and version:** Ubuntu Desktop 16.01 as a VirtualBox VM on Windows 10
**Docker version:** 1.12.1, client and server
**Che install:** Docker.

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: No clue, first used the launcher today. If I use the same stack in 'codenvy beta', it works fine.
- Problem can be reliably reproduced, doesn't happen randomly: Investigating.

**Comment by ghost** [comment]
@jc776 can you open your browser's dev console and look for errors there?

The workspace agent starts OK. And the log line about Maven server not being started is expected. It does not affect anything in this case. We auto detect that the stack does not have Maven and thus do not start our Maven plugin.

**Comment by jc776** [comment]
OK, the problem is from '--remote'. Using the browser inside the VM works fine. Outside, there are console errors of timeouts on all the REST APIs, `172.17.0.1:32788/wsagent/ext/project` etc.

That IP is the 'docker0' network, not the bridge IP or hostname. Manually browsing with `[hostname]:32788/wsagent/ext/project` works.

The [Configuration Readme](https://eclipse-che.readme.io/docs/configuration#envrionment-variables) should probably talk about `che.[sh/bat]` as well as `che-launcher`. Not sure whether to set '--remote' with the hostname or the IP. Ideally it'd work it out from `window.location`...

**Comment by TylerJewell** [comment]
The Configuration README is only for the CLI and the che-launcher. That particular page lists the environment variables which flow into the --remote flag.

That is a different installation and execution tactic than just running the che-server docker container (2nd approach), or running our Tomcat natively (3rd approach).  And we have different docs for those configurations.  But they are different systems with different configurations and behaviors.  

FYI - the 5.x branch has many bug fixes, so you may want to try running the nightly of the che-launcher.  set CHE_VERSION=nightly and rerun.

**Comment by jc776** [comment]
With `CHE_VERSION=nightly che start`, when I create a workspace, it still times out with the internal docker IP.
`CHE_HOST_IP=`hostname` che start` gets past this stage, but runs into #2331
`CHE_VERSION=nightly CHE_HOST_IP=`hostname` che start` still gets #2331, even though it should be fixed since #2392.

I've had a few too many 2-minute timeouts on the startup error and on 'che stop', so I'm going to stop for now.

With the initial issue, I had this dialog box come up once, so "CHE_HOST_IP means --remote" should definitely be on that readme page.
`.title('Workspace Connection Error')
            .content('It seems that your workspace is running, but we cannot connect your browser to it. This commonly happens when Che was' +
            ' not configured properly. If your browser is connecting to workspaces running remotely, then you must start Che with the ' +
            '--remote:<ip-address> flag where the <ip-address> is the IP address of the node that is running your Docker workspaces.' +
            'Please restart Che with this flag. You can read about what this flag does and why it is essential at: ' +
            'https://eclipse-che.readme.io/docs/configuration#envrionment-variables')`

**Comment by jc776** [comment]
OK, I can now start, connect to and open a project from a browser on the host PC with `CHE_HOST_IP=192.168.1.120 CHE_VERSION=nightly che start`. (VM's 'bridged network' IP) I guess it's just picky about using the IP instead of ``hostname``, plus the 'internal network' fix in nightly.

I can run 'Hello world' in a Java workspace. A .NET workspace [segfaults on 'dotnet restore'](https://github.com/dotnet/cli/issues/3681) - might be my VM's kernel or MS's fault, not part of connectivity.

**Comment by TylerJewell** [comment]
That is really great!  Makes me smile - and I will close this particular issue.
