### ISSUE TITLE
Upgrade to GWT 2.8.0

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#2869]
http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_0

**Comment by skabashnyuk** [comment]
Make sure gwt 2.8.0 is corectlly aligned with our versions of guava and guice

**Comment by TylerJewell** [comment]
And check the docs to ensure that the superdevmode setup process for eclipse still works.

**Comment by dkulieshov** [comment]
CQ for GWT 2.8.0: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12311

**Comment by dkulieshov** [comment]
CQ for Google Guava 20.0: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12329

**Comment by dkulieshov** [comment]
CQ for JSR305: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11244

**Comment by dkulieshov** [comment]
CQ for build and test dependencies update: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12330

**Comment by dkulieshov** [comment]
Status update:

Piggyback CQ for JSR305 as workswith: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12486
Piggyback CQ for GWT 2.8.0 as approved: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12485
Google Guava 20.0 approved:  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12329
Build and Test Dependencies workswith: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12330
