### ISSUE TITLE
What is the right way to stop che?

### ISSUE THREAD

**Issue by binduwavell** [eclipse-che/che#287]
**Description of problem:** I started che with `bin/che.sh run -i`. At this point I see the che tomcat startup in my terminal.

In a new terminal I run:

```
➜  eclipse-che-4.0.0-beta-13-1   bin/che.sh stop
Docker machine named default already exists...
Setting environment variables for machine default...
Docker is configured to use vbox docker-machine named default with IP 192.168.99.100...
Stopping Che server running on localhost:8080
```

However the running instance does not stop. I end up going to the original terminal and pressing Control-C. Should I expect `bin/che.sh stop` to work in this case?

**Che version:** `4.0.0-beta-13-1`
**Che install directory:** `~/Downloads/eclipse-che-4.0.0-beta-13-1`
**Docker version:** 

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Docker Info:** 

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: S6GZ:TD7N:M4BZ:J6DK:RN3E:455I:YTPI:BDY4:32XR:ONHD:MGDJ:HFVC
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 39
 System Time: 2016-02-07T22:56:03.470098201Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: binduwavell
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Java version:** `N/A I'm using che.sh run -i (so whatever you have in your container)`
**Environment details (AWS, VirtualBox, physical, etc.):** `I'm on my mac using the default dockertoolbox 0.10 and default che 4.0.0-beta-13-1.`

**Comment by binduwavell** [comment]
`bin/che.sh stop -i` was required to cause the che in docker instance to stop. Seems like `bin/che.sh stop` could detect there is no local che and see if there is one in docker and at least warn folks to use the `-i` flag.

**Comment by TylerJewell** [comment]
This might be a nice optimization, though there is no simple way to test for local Che, short of making JMX calls both locally and into a provided VM to see if Che or Che in a container is provided.

I am thinking that over the longer term, we'll separate out running Che natively vs. running Che as a docker container into separate Che execution scripts, so the admin has to choose the script given the type of behavior they want.

**Comment by TylerJewell** [comment]
@binduwavell Please try the new script that was committed this morning at:
https://github.com/codenvy/che/pull/257

Note that you must get the boot2docker.iso version 1.10 that was released 4 days ago.  This version solves some major instability issues with AUFS that was affecting vbox.  You can get this on your current system by having a docker-machine default running, and then executing `docker-machine upgrade default`.

**Comment by ghost** [comment]
As a side node, it is imperative to have the latest iso image for VBox. Also, the new script gets rid of Docker in Docker, and launches a workspace container in a VM rather than in a Che server container. No privileged mode is necessary now.

**Comment by binduwavell** [comment]
I am already using 1.10. I hope to have time this weekend to try out the new start script. Maybe you'll have a new beta by then? :)

**Comment by TylerJewell** [comment]
We posted RC3 two days ago.  Check out the release notes in the docs for what was added.  Though the new che.sh that removes the dind isn't in it.  You have to grab that from master.

**Comment by ghost** [comment]
Instructions posted - https://eclipse-che.readme.io/docs/usage-docker#using-che-scripts

Closing the issue. Feel free to reopen if script flags do not work as documented.
