### ISSUE TITLE
File watchers don't always work as expected

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2876]
[Short description of problem here]

**Reproduction Steps:**
1. Start workspace
2. Create directory `aaa`  from terminal in `/projects` folder

**Expected behavior:**
To see `aaa` project with `blank` project type.

**Observed behavior:**
Nothing happened.

**Che version:**    master  
**OS and version:** OSX   

![dir_bug](https://cloud.githubusercontent.com/assets/1614429/19679934/71a4bba4-9aac-11e6-91f1-342468d833c5.gif)

**Comment by musienko-maxim** [comment]
On nightly5.codenvy-stg.com works as expected
