### ISSUE TITLE
Adding a new project template to custom stack

### ISSUE THREAD

**Issue by SanthoshHari912** [eclipse-che/che#2879]
I have created a custom stack and want to provide a template to be available under sample category in New Project Wizard. Also the same need to prompted while workspace is getting created newly from the custom stack in the dashboard.

I have added a template object to the existing templates folder in che/templates/samples.json.

I have then tried restarting the Che instance. But am not able to get the newly added template getting prompted either while creating workspace or in New Project wizard

Can some one guide me  if am missing something in the workflow?

Regards
Santhosh

**Comment by TylerJewell** [comment]
@jamesdrummond @slemeur - please one of you verify that the 5.0 docs are accurate, and that the latest JSON schema is posted., and then follow up with @SanthoshHari912 here.  I don't know why we keep getting questions - our docs need to be rock solid on this.

@SanthoshHari912 - the good news is that much like the stack editing, we'll also be adding template editing to the GUI shortly.

**Comment by SanthoshHari912** [comment]
@TylerJewell Thanks for the input ..Just a feedback as you have mentioned about docs here. Few of the doc links given as reference either in github or in Che documentation pages are broken. Very few are like this otherwise your documentation helped in a greater way to configure che.

**Comment by TylerJewell** [comment]
We have a lot of problems with readme.io as the nature of their system breaks links a lot.  It would be helpful if you could post any broken links here and then PMs will get them fixed.

**Comment by JamesDrummond** [comment]
@SanthoshHari912 Take a look at [https://eclipse-che.readme.io/docs/code-template](https://eclipse-che.readme.io/docs/code-template) and [https://eclipse-che.readme.io/docs/stacks](https://eclipse-che.readme.io/docs/stacks).

**Comment by slemeur** [comment]
Hi @SanthoshHari912 . I hope the documentation helped you.

I'd like to discuss with you about the stack you are trying to setup + the previous issue you created #2806 and follow-up. Could you please reach us directly at slemeur.at.codenvy.com and jdrummond.at.codenvy.com 

Thanks

**Comment by TylerJewell** [comment]
@SanthoshHari912 - closing as I think this issue is resolved.
