### ISSUE TITLE
How to finish an inline-rename of a field with vi-mode enabled?

### ISSUE THREAD

**Issue by binduwavell** [eclipse-che/che#288]
In a java file, I initiated an in-line rename (command-shift-a rename) on a member variable. When I pressed return it inserted a newline rather than finishing the rename operation. I have vi mode enabled. I disabled vi mode and tried again. Updated the field name and then pressed return and it completed the rename operation. The rename failed with a red toast indicating some sort of 500 error however the rename was partially reflected in the editor. I used command-z to get back to a place before the rename. I ran the rename again and this time it worked without any errors.

**Comment by binduwavell** [comment]
**Che version:** `4.0.0-beta-13-1`
**Che install directory:** `~/Downloads/eclipse-che-4.0.0-beta-13-1`
**Docker version:** 

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Docker Info:** 

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: S6GZ:TD7N:M4BZ:J6DK:RN3E:455I:YTPI:BDY4:32XR:ONHD:MGDJ:HFVC
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 39
 System Time: 2016-02-07T22:56:03.470098201Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: binduwavell
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Java version:** `N/A I'm using che.sh run -i (so whatever you have in your container)`
**Environment details (AWS, VirtualBox, physical, etc.):** `I'm on my mac using the default dockertoolbox 0.10 and default che 4.0.0-beta-13-1.`

**Comment by ddementieva** [comment]
Problem with rename refactoring has been fixed in our latest version. You can download it at https://install.codenvycorp.com/che/eclipse-che-nightly.zip and run with `che.sh run` command.

Can you please try it on your side and tell if you face any problem with it?

**Comment by binduwavell** [comment]
I downloaded and exploded the linked nightly. I started my default docker-machine. I used `bin/che.sh start` UI came up. I attempted to create a project (and workspace) to test this and it is stuck on Creating Workspace. Nothing interesting in `catalina.out`. I restarted che with the same result.

I deleted my default docker-machine and attempted to `bin/che.sh run`. Still stuck on "Creating workspace". If I run `docker ps` or `docker images` I now see nothing. So it appears that the workspace image is not getting pulled. `docker version` correctly provides information about my client and server versions, so I assume my environment is setup correctly. I just ran `docker run hello-world` from the same shell I'm running che commands from and I got the appropriate output.

Aside: It would help to know if there was a less destructive way of resetting things, I might have containers in my default machine I don't want to just wipe out.

**Comment by binduwavell** [comment]
I created just a workspace and it seems to be working, so possibly there is an issue with creating a project & workspace concurrently with the nightly? I'll try again once this workspace has finished downloading the associated docker image.

**Comment by binduwavell** [comment]
Oh too bad, once workspace is started I try to open IDE and get: `Cannot get workspaces. The reason: (TypeError): Cannot read property 'a' of null.`

**Comment by binduwavell** [comment]
I tried restarting che again, no dice. I do see the workspace container running, but I get the same error as above.

**Comment by binduwavell** [comment]
Switched over to beta and I'm not having issues creating projects/workspaces. So I guess the nightly is just broken?

**Comment by ghost** [comment]
Did you try to open it in an incognito mode or just clear cache?

Also, do you create a new workspace or open an existing one? There have been some changes in workspaces that cause incompatibility between beta and RC.

**Comment by binduwavell** [comment]
I did not try in incognito mode. I did rebuild default docker-machine, so assume there are no compatibility issues as it was a fresh environment.

**Comment by ghost** [comment]
If you still face this problem, open a separate issue if it's repeatedly reproducable.

**Comment by ghost** [comment]
@binduwavell can you reproduce the original issue with the latest release version - RC3? http://www.eclipse.org/che/download/

**Comment by ghost** [comment]
@binduwavell any update on this? We failed to reproduce with RC3 and current master. I am closing the issue now. Feel free to reopen if the problem is still there.
