### ISSUE TITLE
On Mac, Running che command throws error `/usr/local/bin/che: line 165: init_global_variables: command not found`

### ISSUE THREAD

**Issue by virtualit786** [eclipse-che/che#2890]
Running che command fires the error

`/usr/local/bin/che: line 165: init_global_variables: command not found`

**Reproduction Steps:**
1. Followed step 0. Pre-Reqs [https://eclipse-che.readme.io/v5.0/docs/che-getting-started](url)
2. Followed step 1. Get the Eclipse Che CLI 
3. Followed step 2. Start Che . Stuck after che start command as it produced the error

**Expected behavior:**
Che should have been started

**Observed behavior:**

Everytime any che command is fired, it throws error
`/usr/local/bin/che: line 165: init_global_variables: command not found`

**Che version:**    Cannot obtain che version as even firing che version throws the error. 
**OS and version:** System Version: macOS 10.12 (16A323)
      Kernel Version: Darwin 16.0.0
      Boot Volume: OSX
      Boot Mode: Normal

**Docker version:** 
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
**Che install:**    I followed the guide and installed docker first.

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: I am not sure as its the first time I have installed che.
- Problem can be reliably reproduced, doesn't happen randomly: Yes. I have tried removing all and reinstall but with same result.

**Comment by TylerJewell** [comment]
So the Che script is a self-updating script.  It connects to GitHub to download a "cli.sh" which actually has the commands, including the init_ command that is not found.  This file is saved to ~/.che/cli.  Can you check to see if any file is there?  If it's not there, do you have access to github from where you ran the script?

There are ways to work around this limitation, if it is still happening.

**Comment by virtualit786** [comment]
@TylerJewell Thanks for looking into it. Yes cli-latest.sh file is at your mentioned location.

**Comment by TylerJewell** [comment]
Well that is interesting - that file should be automatically loaded.

If you go into that file `cli-latest.sh`, what is its date, and is there an init_global_variables function at the top?

**Comment by virtualit786** [comment]
File has no contents. Zero bytes. 
After setting the ~./bash_profile stuff thats mentioned in the guide,  I am doing the followings and getting this error.
1. curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > /usr/local/bin/che
2. chmod +x /usr/local/bin/che
3. che start
Plus everytime I open terminal, now its asking for root password as well.

**Comment by TylerJewell** [comment]
Inside the che.sh - it is downloading the CLI using curl.  You can go to the master branch of the che repo, and download the cli.sh and save it as cli-latest.sh in that directory.  If you do that it should run.  But the issue is that something is preventing us from downloading the file using curl.

**Comment by virtualit786** [comment]
Ok so I did what you suggesting and ran the script after and tried this few times and everytime getting error:-

Segmentation fault: 11

**Comment by TylerJewell** [comment]
One last test please and if this fails I may need access to your box to test.  Can you try sudo before downloading the initial script and when running it?

**Comment by virtualit786** [comment]
@TylerJewell You mean to try this

`sudo curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > /usr/local/bin/che`

**Comment by virtualit786** [comment]
I did that and then removed it just to check again. And then as per guide, i fired
`curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > /usr/local/bin/che`

Now its downloading the script to /usr/local/bin/che and then firing following changes its rights to execute 

`chmod +x /usr/local/bin/che`

And now its started to download. 

I am not sure what changed here.

**Comment by TylerJewell** [comment]
Yeah, you go it.  I wanted to know if you did sudo when you saved the first file if it would solve the problems.  It sounds like that is the solution.  I have to think about why this happened some more.

**Comment by virtualit786** [comment]
Yeah, its strange. If I was using Windows, I would simply blame Microsoft :) Thanks man for the help !

**Comment by TylerJewell** [comment]
Enjoy!!
