### ISSUE TITLE
The number of machines is not correctly displayed in the tree if you add workspace using URL

### ISSUE THREAD

**Issue by AndreyChizhikov** [eclipse-che/che#2892]
**Reproduction Steps:**
1. Create workspace from custom stack by using [URL](https://gist.githubusercontent.com/idexmai/cb1a4ae1f51202ffc1cf72d1649edb1f/raw/44aef96d5c32348ae4d573905da197c487724de6/recipe_db) on compose file

**Expected behavior:**
In tree of processes is displayed **dev-machine** and **db**
**Observed behavior:**
In tree of processes is displayed only **dev-machine**
![b01a4496-9127-11e6-94c5-39093387802a](https://cloud.githubusercontent.com/assets/8051404/19716591/48f55632-9b65-11e6-8571-a40934a96bbc.png)

**Che version:**  5.0.0-M6-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.2
**Che install:**  Docker container

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ashumilova** [comment]
cannot reproduce, tried same compose file - process panel displays all mentioned machines from recipe.
