### ISSUE TITLE
Che With Windows 64-bit? Not finding Java

### ISSUE THREAD

**Issue by edfultz** [eclipse-che/che#290]
I am trying to run on a Windows 7 64-bit environment.  When I start I get error wrong version of Java installed.  I commented out the check and later it did not find the file or directory because it was looking in the wrong program files directory.

Does Che support Windows 7 64-bit?

Using CATALINA_BASE:   /c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-B/tomcat
Using CATALINA_HOME:   /c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-B/tomcat
Using CATALINA_TMPDIR: /c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-B/tomcat/temp
Using JRE_HOME:        /C/Program Files/Java/jdk1.8.0_66
Using CLASSPATH:       /c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-B/tomcat/conf/:/C/Program Files/Java/jdk1.8.0_66/lib/tools.jar:/c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-B/tomcat/bin/bootstrap.jar:/c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-B/tomcat/bin/tomcat-juli.jar
/c/PROGRA~1/ECLIPS~1/ECLIPS~1.0-B/tomcat/bin/catalina.sh: line 333: /C/Program Files/Java/jdk1.8.0_66/bin/java: No such file or directory

**Comment by TylerJewell** [comment]
Yes, Che should run on Windows 7 with 64 bit.   Though Tomcat has numerous issues with paths that have spaces in them on Windows 7.

It looks like the CHE_HOME was properly set to a shortened windows directory.  But I see that your JRE_HOME has the full path in it.  I need to investigate more, but have you attempted to set JAVA_HOME system environment variable to the shortened path to where your JDK is installed?

We can look to add a patch that sets JRE_HOME to /c/progra~1/java/jdk1.8.0_66 when Che starts, which would likely prevent this issue you are having.

**Comment by edfultz** [comment]
I found problems with my installation of Java being removed.  Not sure how, or why but found Java 1.6 installed for some reason.  I re-installed the latest java 8 and removed java 6.  I updated my environment variables and now che has started.  I have succeeded in getting the browser window to open.

Now, on to learning how to use it.

**Comment by TylerJewell** [comment]
Woot. Great - this issue was quite concerning for me as we have had some troubles with Java version detection, so was concerned we uncovered another edge case to fix.
