### ISSUE TITLE
Implement possibility to execute commands from the context menu

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#2900]
User should be able to execute commands from the context menu of Project Explorer, Processes panel, editor's tab.

![](https://cloud.githubusercontent.com/assets/1636769/19035278/d97cdd7e-8968-11e6-947e-4504b64bdb5c.png)

**Comment by TylerJewell** [comment]
@azatsarynnyy @slemeur - link into epic on intelligent commands.
