### ISSUE TITLE
Error creating new project

### ISSUE THREAD

**Issue by jeyvison** [eclipse-che/che#2902]
Whenever a try to create a new project i get the following error: 

**Internal Server Error: <REPO_URL> : cannot open git-upload-pack**

**REPO_URL** is the url from where Che  tries to clone the projects.

All i'm doing is: Go to Dashboard -> Select **New fom blank, template, or sample project** -> Select the Java Ready-to-go Stack(for example) -> leave the options how it is and then i click on **Create**.

In **Creating Project Phase** i get the above error. What i can see from google is this is an ssl verification that fails. How can i disable it when che tries to download some repo?

thanks for your help :)

**Che version:**    4.7.2 
**OS and version:** Linux Mint 18 ( Sarah) 
**Docker version:** 1.11.2
**Che install:**   Container

**Comment by benoitf** [comment]
I think you're not selecting "project wizard" template at the end but you pickup one default template (and templates are loaded by git clone)
So pickup the option "Wizard-driven templates"

**Comment by jeyvison** [comment]
It works to create a new project when i select **Wizard-Driven templates** but samples(templates) are still not being cloned.

**Comment by benoitf** [comment]
Could you print the full ssl error that you have for templates ? You said you wanted to avoid to clone repositories.
Do you use custom DNS servers ? or using proxy ?

**Comment by jeyvison** [comment]
Hi @benoitf . I'm behind my company's proxy.

Follow the log and the printscreen:

[log.txt](https://github.com/eclipse/che/files/554413/log.txt)

![screenshot from 2016-10-26 16-27-14](https://cloud.githubusercontent.com/assets/2052262/19743753/eac6d73e-9ba0-11e6-9989-a998b70a5d3b.png)

**Comment by benoitf** [comment]
as you're behind a proxy you should have to configure proxy in Che for allowing git clone operations.

**Comment by TylerJewell** [comment]
I think this is resolved based upon feedback that I have seen in other issues.
