### ISSUE TITLE
Improve "Recent Workspaces" behaviors

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2908]
The _Recent Workspaces_ in the left navbar is having the following behaviors:
- It always displayed the latest 5 opened workspaces
- It keeps order accurate (with time of the latest open action)

We need to simplify this a bit, so it avoid being updated too oftenly:
- we order the list only when we first load it
- we don't change the order so if a user is opening a workspace from the list, it will stay displayed at its current position
- when a workspace is opened and is not in the list, we add it by replacing the workspace which was opened since the oldest time.

**Che version:**    5.0.0-M6

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/3286/commits/8dc912151cd77a7c84fe875aa13caaf7b67d42f0

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/3286/commits/271eca04dd7c7c1c2b5b437c02effcab20807202
