### ISSUE TITLE
Better handle "Process Panel" when commands are long

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2911]
The process panel is not properly handling situations where:
- name of the command is long
  <img width="923" alt="screen shot 2016-10-27 at 09 42 01" src="https://cloud.githubusercontent.com/assets/1636769/19758716/a64e0788-9c29-11e6-91ab-42bf329d4778.png">
- command is long
  <img width="909" alt="screen_shot_2016-10-27_at_09_42_31" src="https://cloud.githubusercontent.com/assets/1636769/19759011/3c0ac3a0-9c2b-11e6-8a71-616194fc16d9.png">

We need to improve and handle those situations properly.

We should truncate the name of the command in the process tree and display a tooltip when user hover it:
<img width="296" alt="screen shot 2016-10-27 at 09 54 25" src="https://cloud.githubusercontent.com/assets/1636769/19759696/83f44990-9c2e-11e6-9ce9-d62f16277f2e.png">

We should also do the same when we display the command executed:
![long command](https://cloud.githubusercontent.com/assets/1636769/19759751/a4b734d0-9c2e-11e6-955f-e77c7a90d6a1.png)

**Comment by TylerJewell** [comment]
@slemeur - link into epic on intelligent commands.

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/3286/commits/e59465b0afa5778154aa79a655859307418369f8

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/3286/commits/2de17e0422902ea3e2554ad9224604aefe4828f5
