### ISSUE TITLE
action on multiple selected projects

### ISSUE THREAD

**Issue by ccampo** [eclipse-che/che#2913]
if I select multiple projects and perform an action it is only applied to the first project. that is unexpected. 

**Reproduction Steps:**
1. select three projects
2. right click on "Convert to Project"
3. only first project is converted

**Expected behavior:**

it should convert all projects

*_Che version:5.0.M6    [Enter Che version here]  
*_OS and version:Mac OS X El Capitan [Enter OS name and version here]  
*_Docker version:1.12.1 [Enter your Docker version here `docker version` on CLI]  
*_Che install:Mac Docker local    [Vagrant, Docker container, server (zip), Bitnami, Yatta, or Codenvy?]   

**Additional information:**

Missing feature

**Comment by TylerJewell** [comment]
@tolusha - is this usage expected behavior?  I don't see how a user would select three projects (that are already projects) and you convert all of them to projects.

**Comment by tolusha** [comment]
We convert only the first selected folder into the project.

**Comment by TylerJewell** [comment]
What is expected by a user?

**Comment by benoitf** [comment]
if you're able to select multiple folders (and that it's hightlighting this selection (folders get another color) then it should apply to the whole selection

**Comment by ccampo** [comment]
One of the pitfalls that might come up is, that some action are multiselection-able and some are not. So for instance "Rename" makes no sense really if you select 10 projects. Actually a lot of actions that are followed by a dialog are things you probably dont want for multiselection. So that might lead to a concept where you need to annotate your actions whether they can be executed with multiple nodes selected and change the right-click popup menu accordingly.

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by vparfonov** [comment]
not actual
