### ISSUE TITLE
Small question: what is inside eclipse/che:latest - where to find the dockerfile?

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#2917]
It is not an issue but just a question: I cannot find the dockerfile of eclipse/che:latest that launches codenvy/che-server. (described in this page https://eclipse-che.readme.io/docs/usage-docker).
Where can it be found?

And furthermore, can I ask you: what is the interest of this supplementary image? I mean, what is the improvement compared to:
docker run --net=host \
           --name che \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /home/user/che/lib:/home/user/che/lib-copy \
           -v /home/user/che/workspaces:/home/user/che/workspaces \
           -v /home/user/che/storage:/home/user/che/storage \
           codenvy/che-server
 (but maybe if I see it, I will understand.)

**Comment by TylerJewell** [comment]
eclipse/che image is the che-launcher - documented here:
https://eclipse-che.readme.io/docs/usage-docker

The che-launcher has a simpler syntax than the che-server, includes a docker 1.6 client inside of it to allow for it to run against any Docker daemon, and handles some ugly nuances in volume mounts + env configurations that exist for Docker on different OS.  So while the che-server is the server itself, it is not possible for identical syntax to work on that for each docker daemon and each OS.

The dockerfiles for the che-launcher is at github.com/eclipse/che-dockerfiles
