### ISSUE TITLE
This Linux user is not in 'docker' group

### ISSUE THREAD

**Issue by krewmarco** [eclipse-che/che#2922]
Can't start che-server.  Getting 'This Linux user is not in 'docker' group' in docker logs for containter che-server.  User is member of docker group.  

**Reproduction Steps:**
1. download che.sh according to instructions
2. che start

**Expected behavior:**
I expect the server to start and provide a url
**Observed behavior:**

ERROR: !!!
ERROR:      ECLIPSE CHE: Timeout waiting for server. Run "docker logs che-server" to inspect the issue.
ERROR: !!!

**Che version:**    latest
**OS and version:** Ubuntu 14.04 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Docker version:** 1.11.0, build 4dc5990
**Che install:**    Docker container

**Additional information:**
output of >groups
marco@marco-Compaq-Presario-A900-Notebook-PC:~$ groups
marco adm cdrom sudo dip plugdev lpadmin sambashare docker

contents of che info:
INFO:  ---------------------------------------
INFO:  -------------   CLI INFO   ------------
INFO:  ---------------------------------------
INFO:  
INFO:  ---------  PLATFORM INFO  -------------
INFO:  CLI DEFAULT PROFILE       = not set
INFO:  CHE_VERSION               = latest
INFO:  CHE_CLI_VERSION           = latest
INFO:  CHE_UTILITY_VERSION       = nightly
INFO:  DOCKER_INSTALL_TYPE       = native
INFO:  DOCKER_HOST_IP            = 172.17.0.1
INFO:  IS_NATIVE                 = YES
INFO:  IS_WINDOWS                = NO
INFO:  IS_DOCKER_FOR_WINDOWS     = NO
INFO:  IS_DOCKER_FOR_MAC         = NO
INFO:  IS_BOOT2DOCKER            = NO
INFO:  HAS_DOCKER_FOR_WINDOWS_IP = NO
INFO:  IS_MOBY_VM                = NO
INFO:  HAS_CHE_ENV_VARIABLES     = NO
INFO:  HAS_TEMP_CHE_PROPERTIES   = NO
INFO:  IS_INTERACTIVE            = YES
INFO:  IS_PSEUDO_TTY             = YES
INFO:  
INFO: ---------------------------------------
INFO: ---------   LAUNCHER INFO  ------------
INFO: ---------------------------------------
INFO: 
INFO: ---------  PLATFORM INFO  -------------
INFO: DOCKER_INSTALL_TYPE       = native
WARNING: No swap limit support
INFO: DOCKER_HOST_OS            = Ubuntu 14.04.4 LTS
INFO: DOCKER_HOST_IP            = 172.17.0.1
INFO: DOCKER_HOST_EXTERNAL_IP   = not set
INFO: DOCKER_DAEMON_VERSION     = 1.11.0
INFO: 
INFO: 
INFO: --------- CHE INSTANCE LIST  ----------
INFO: 
INFO: --------- CHE INSTANCE: f5edfaaef700
INFO: CHE SERVER CONTAINER NANE = che-server
INFO: CHE CONTAINER EXISTS      = YES
INFO: CHE CONTAINER STATUS      = stopped
INFO: 
INFO: 
INFO: ----  CURRENT COMMAND LINE OPTIONS  ---
INFO: CHE_VERSION               = latest
INFO: CHE_DATA                  = /home/user/che
INFO: CHE_CONF                  = not set
INFO: CHE_ASSEMBLY              = not set
INFO: CHE_PORT                  = 8080
INFO: CHE_HOST_IP               = 172.17.0.1
INFO: CHE_RESTART_POLICY        = no
INFO: CHE_USER                  = root
INFO: CHE_LOG_LEVEL             = info
INFO: CHE_DEBUG_SERVER          = false
INFO: CHE_DEBUG_SERVER_PORT     = 8000
INFO: CHE_HOSTNAME              = localhost
INFO: CHE_SERVER_CONTAINER_NAME = che-server
INFO: CHE_SERVER_IMAGE_NAME     = codenvy/che-server
- Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
  Yes
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
  Yes

**Comment by TylerJewell** [comment]
Hi.  I believe we have resolved this issue in the latest version.  Can you set CHE_VERSION=nightly and rerun?  Let's see what happens.

**Comment by option0417** [comment]
I have same problem but it is resolved when I set **CHE_VERSION=nightly** and rerun.

**Comment by chrisdbarnett** [comment]
Same problem for me. While CHE_VERSION=nightly resolves, I now have a different problem:

@krewmarco @option0417 - Do you also now have this issue with CHEDIR? : 

Step 1: mkdir phpdev3
Step 2: cd phpdev3
Step 3: che dir up

## ERROR: ECLIPSE CHE(dir): Call on rest url /wsagent/ext/project/estimate/phpdev3?type=blank returned invalid response code (404) with error:Folder not found: phpdev3 

If you don't get this error, please let me know and I'll create a new issue.
Thanks.

**Comment by TylerJewell** [comment]
This would be an unrelated issue.  Try setting CHE_UTILITY_VERSION=nightly and then try again with the che-dir capability.  You may now be running a che-dir, which is a Docker image that is not the same version as the che-server.  If that continues to be an issue, we should set up a different github issue for that.
