### ISSUE TITLE
CHEDIR broken.

### ISSUE THREAD

**Issue by chrisdbarnett** [eclipse-che/che#2925]
CHE DIR UP bombs out with error - even on blank/virgin project directory.

**Reproduction Steps:**
1. CHE STOP + delete straggling docker containers + delete locally cached docker images + delete che-conf + che-data directories.
2. Reinstall Eclipse che + update che + start & stop che
3. MKDIR ~/phpdev8 + CD ~/phpdev8 + CHE DIR UP

**Expected behavior:**

Expected behavior is that CHE DIR UP will launch a basic Che workspace.

**Observed behavior:**

ERROR: ECLIPSE CHE(dir): Call on rest url /wsagent/ext/project/estimate/phpdev8?type=blank returned invalid response code (404) with error:Folder not found: phpdev8

**Che version:**    5.0.0-M7-SNAPSHOT  
**OS and version:** Ubuntu 16.04.1 LTS  
**Docker version:** 1.12.1
**Che install:**    Docker (Native to Ubuntu)   

INFO:  ---------------------------------------
INFO:  -------------   CLI INFO   ------------
INFO:  ---------------------------------------
INFO:  
INFO:  ---------  PLATFORM INFO  -------------
INFO:  CLI DEFAULT PROFILE       = not set
INFO:  CHE_VERSION               = nightly
INFO:  CHE_CLI_VERSION           = nightly
INFO:  CHE_UTILITY_VERSION       = nightly
INFO:  DOCKER_INSTALL_TYPE       = native
INFO:  DOCKER_HOST_IP            = 172.17.0.1
INFO:  IS_NATIVE                 = YES
INFO:  IS_WINDOWS                = NO
INFO:  IS_DOCKER_FOR_WINDOWS     = NO
INFO:  IS_DOCKER_FOR_MAC         = NO
INFO:  IS_BOOT2DOCKER            = NO
INFO:  HAS_DOCKER_FOR_WINDOWS_IP = NO
INFO:  IS_MOBY_VM                = NO
INFO:  HAS_CHE_ENV_VARIABLES     = YES
INFO:  HAS_TEMP_CHE_PROPERTIES   = NO
INFO:  IS_INTERACTIVE            = YES
INFO:  IS_PSEUDO_TTY             = YES
INFO:  
INFO: ---------------------------------------
INFO: ---------   LAUNCHER INFO  ------------
INFO: ---------------------------------------
INFO: 
INFO: ---------  PLATFORM INFO  -------------
INFO: DOCKER_INSTALL_TYPE       = native
INFO: DOCKER_HOST_OS            = Ubuntu 16.04.1 LTS
INFO: DOCKER_HOST_IP            = 172.17.0.1
INFO: DOCKER_HOST_EXTERNAL_IP   = not set
INFO: DOCKER_DAEMON_VERSION     = 1.12.1
INFO: 
INFO: 
INFO: --------- CHE INSTANCE LIST  ----------
INFO: 
INFO: --------- CHE INSTANCE: fea1a03dddd3
INFO: CHE SERVER CONTAINER NANE = che-server-c0fdb8eb-b1dc-4a6d-9f6f-eff93d8d6db5
INFO: CHE CONTAINER EXISTS      = YES
INFO: CHE CONTAINER STATUS      = running
INFO: CHE SERVER STATUS         = running & api reachable
INFO: CHE VERSION               = 5.0.0-M7-SNAPSHOT
INFO: CHE IMAGE                 = codenvy/che-server:nightly
INFO: CHE CONF FOLDER           = not set
INFO: CHE DATA FOLDER           = not set
INFO: CHE USE URL               = http://172.17.0.1:8080
INFO: CHE API URL               = http://172.17.0.1:8080/swagger
INFO: CHE LOGS                  = run `docker logs -f che-server-c0fdb8eb-b1dc-4a6d-9f6f-eff93d8d6db5`
INFO: 
INFO: 
INFO: ----  CURRENT COMMAND LINE OPTIONS  ---
INFO: CHE_VERSION               = nightly
INFO: CHE_DATA                  = /home/chrisdbarnett/che-data
INFO: CHE_CONF                  = /home/chrisdbarnett/che-conf
INFO: CHE_ASSEMBLY              = not set
INFO: CHE_PORT                  = 8080
INFO: CHE_HOST_IP               = 172.17.0.1
INFO: CHE_RESTART_POLICY        = no
INFO: CHE_USER                  = root
INFO: CHE_LOG_LEVEL             = info
INFO: CHE_DEBUG_SERVER          = false
INFO: CHE_DEBUG_SERVER_PORT     = 8000
INFO: CHE_HOSTNAME              = localhost
INFO: CHE_SERVER_CONTAINER_NAME = che-server
INFO: CHE_SERVER_IMAGE_NAME     = codenvy/che-server

.profile 
export CHE_VERSION=nightly
export CHE_CLI_VERSION=nightly
export CHE_UTILITY_VERSION=nightly
export CHE_CONF_FOLDER=/home/chrisdbarnett/che-conf
export CHE_DATA_FOLDER=/home/chrisdbarnett/che-data
export CHE_DATA=/home/chrisdbarnett/che-data
export CHE_CONF=/home/chrisdbarnett/che-conf
- Problem started happening recently, didn't happen in an older version of Che: Happened on latest nightly - but even if I knock everything down and rebuild under older version of CHE, problem persists, even after rebooting docker, cleaning out locally cached docker images.  
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by TylerJewell** [comment]
@benoitf - please consider this a blocker. there must be an API shift that was not documented or triggered in the move from M6 to M7.

@chrisdbarnett - yesterday we merged a number of destabilizing items after we shiipped M6. It's possile that supporting utilities are out of sync.

**Comment by benoitf** [comment]
@chrisdbarnett could you start che dir up command with `--logger-debug` argument

**Comment by chrisdbarnett** [comment]
[debug.txt](https://github.com/eclipse/che/files/558107/debug.txt)
Please find attached the output. Cheers.

**Comment by benoitf** [comment]
@chrisdbarnett thanks 
https://github.com/eclipse/che/pull/2707 has broken this feature in current master so it will require a fix

**Comment by chrisdbarnett** [comment]
@benoitf - is there another version that I can use in the meantime? Thanks.

**Comment by benoitf** [comment]
Sorry my comment was not added ( I was on airport)
@chrisdbarnett you could use export CHE_VERSION=5.0.0-M6

**Comment by chrisdbarnett** [comment]
@benoitf 

Thanks, I appear to be getting on fine with M5.

Surely M6 puts me back in the land of:

!!! This Linux user is not in 'docker' group. See https://docs.docker.com/engine/installation/ubuntulinux/#create-a-docker-group 

????

**Comment by benoitf** [comment]
@chrisdbarnett I forgot to mention that current master should work (nightly)

**Comment by slemeur** [comment]
Closing the issue
