### ISSUE TITLE
fix usage of CHE_DATA in Che Server

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#2941]
CHE_DATA are not being picked up by Che-Server, so it is impossible to use custom user configuration/data mounting volume.

**Che version:**    5.0.0-M7-SNAPSHOT 
**Docker version:** [Enter your Docker version here `docker version` on CLI]   
**Che install:**    Che Launcher

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by TylerJewell** [comment]
I do not understand the issue.  I was testing the che server this weekend and do not have such issues.    Please provide reproduction steps and outputs.

**Comment by mkuznyetsov** [comment]
As we have figured out, it was failing because of property and variable renaming leftover (in particular, rewriting properties with values that point to mounted data, mounting  stacks and templates)

**Comment by mkuznyetsov** [comment]
Fixed by merging PRs:
https://github.com/eclipse/che/issues/2955
https://github.com/eclipse/che-dockerfiles/pull/34
