### ISSUE TITLE
 OAuth protocol from github does not work

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2944]
**Reproduction Steps:**
* Open the IDE.
* Go to 'Profile' -> 'Preferences' -> 'VCS'
* Try to generate key to GitHub

**Expected behavior:**
Should be appear the OAuth github window.

**Observed behavior:**
There is: 'Unsupported OAuth provider github'.

**Che version:**  5.0.0-M7  
**OS and version:** Ubuntu  14.04  
**Docker version:** 1.11  
**Che install:**   local bundle  

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by riuvshin** [comment]
@mkuznyetsov please link this issue to one you are working on
