### ISSUE TITLE
WS Fails Creation - Zombie Docker Networks

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2945]
In rare situations, it seems possible that zombie Docker networks are created.  When we have too many zombie networks, then there is a networking pool connection error and workspace creation fails because docker network cannot create a new network.

This probably happens when che servers are killed without che being able to destroy a network.  We should test for this situation and have Che clean up zombie networks.

**Comment by bmicklea** [comment]
Closing as a duplicate of https://github.com/eclipse/che/issues/2930
