### ISSUE TITLE
How to change location in origin(Git-->Remotes-->origin) using curl

### ISSUE THREAD

**Issue by worksamp** [eclipse-che/che#2951]
Hi,

I have created workspace and project successfully.

Now i need to change location in origin(Git-->Remotes-->origin) using curl.

Can you please help me with this

Thanks,
Worksamp

**Comment by tolusha** [comment]
@worksamp 

Hi.
Why do you need to use `curl` ?

**Comment by worksamp** [comment]
Hi
I am using swagger api for creating workspaces and project.
By using swagger api I need to change that location so that user can push code to mentioned github repository

**Comment by tolusha** [comment]
It should help. 
`https://github.com/eclipse/che/blob/master/wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitService.java#L382`
