### ISSUE TITLE
Error starting workspace

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2952]
Error starting workspace

`Could not start workspace wksp-dopn. Reason: Start of environment default failed. Error: Error response from docker API, status: 500, message: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network`

**Comment by TylerJewell** [comment]
I ran into this yesterday and this is a duplicate.  The resolution is to remove docker networks on the command line or within the product.

**Comment by TylerJewell** [comment]
#2945
