### ISSUE TITLE
Feature Request : Environmental Variables in main project / app container.

### ISSUE THREAD

**Issue by chrisdbarnett** [eclipse-che/che#2954]
It would be nice if shell scripts could be run that could easily find the project name, project directory etc.

**Comment by TylerJewell** [comment]
There are macros which can be inserted into preview URLs and commands for this.  Look up the macros and commands portion of the docs.

**Comment by chrisdbarnett** [comment]
@TylerJewell - I know. But sometimes people may want to run scripts rather than commands.....and I wasted 15 minutes of my life typing an explanation in this reply as to why........until I realised that I need more coffee.........if in that time it didn't cross my mind to simply pass in the macros as parameters to my script!
