### ISSUE TITLE
Windows 10 - Eclipse che fails to create 'projects' folder

### ISSUE THREAD

**Issue by mjitch** [eclipse-che/che#296]
i do not see 'projects' folder being created in the default location specified in che.properties -

CHE_HOME====D:\eclipse-che-4.0.0-beta-13-1
###### 

On Windows, Che projects can only reside in %userprofile% due
to limitations of Docker. On this computer, %userprofile% is
C:\Users\manjit.s
###### 

I tried looking for it and i do not see it anywhere.

**Comment by TylerJewell** [comment]
Hi.  This is a known issue due to user directories that have periods in them on Windows.  We are working on a fix.

Do you have another user account that you can user temporarily?

**Comment by ghost** [comment]
`projects` folder is the one that gets created in a container while on your Win host filesystem you should have `workspaces` directory with your workspaces and their projects. All configuration is stored at `/tomcat/temp/local-storage` - you should see a bunch of jsons there.

**Comment by mjitch** [comment]
I am running che as a standalone, not as a docker container. so, is there a work-around for this issues at the moment? I am unable to import my existing projects as of now.

**Comment by ghost** [comment]
Is Che running successfully? I mean you can start it but you expect `/projects` folder somewhere?

Can you successfully start a workspace? Can you import a project at Workspace > Import Project?

**Comment by mjitch** [comment]
Yes, I am able to start/stop che and looking for _/projects_ folder to be available as configured in _che.properties_. The workspace creation is also fine. My intention is to copy an existing project as mentioned feature in che to import project.

**Comment by ghost** [comment]
`/projects` is created **inside** a container and we mount projects from a local file system into this dir. It is created when a container is starting.

After you have imported a project in Che, you can find it in `/workspace/${ws-name}` in CHE_HOME

**Comment by mjitch** [comment]
I am not able to find any reference of the workspace/project in my local drive. As per the import options mentioned in the doc, it still remains a mystery.

**Comment by ghost** [comment]
It is `D:\eclipse-che-4.0.0-beta-13-1\workspaces`

**Comment by mjitch** [comment]
Nop, I do not see that workspace folder in that location.

**Comment by ghost** [comment]
Sorry, that was Linux configuration.

`Storage and user configuration
The location where your workspaces (and their projects) are stored.
This property is ignored on Windows due to limitations with VirtualBox
On Windows, all workspaces stored in c:\%userprofile%\AppData\Local\Eclipse Che\
che.user.workspaces.storage=${che.home}/workspaces`

You should be able to find your projects at `C:\Users\manjit.s\AppData\Local\Eclipse Che\vfs`

**Comment by mjitch** [comment]
Thanks eivantsov, finally i found it!

**Comment by ghost** [comment]
Closing the issue. If you have any additional questions or issues with project mounting, feel free to reopen it.
