### ISSUE TITLE
Cannot save previewURL into a command (regression)

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2966]
**Reproduction Steps:**

1. Create a new command
2. Try to save it with a preview URL http://${server.port.8080}

**Expected behavior:**

Command is saved with a previewURL

**Observed behavior:**

Preview URL is not saved

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: Not sure
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by artaleks9** [comment]
Related selenium test is the 'PreviewUrlIntoCommandTest'.

**Comment by riuvshin** [comment]
Fixed.
