### ISSUE TITLE
Improve the stack selector widget

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2971]
The goal of this issue is to improve the current stack selector that we have in the Dashboard. At this moment:
- the widget does not scale nicely when the list of stacks is huge
- icons are displayed only for ready-to-go stack
- each stack is represented with a tile, but the tiles does not redraw properly for small resolution
- the search/filter capabilities are 
- the tabs experience is not that easy for end-users
- adding a new stack is difficult to find

Here is the proposed solution:
![integration-dashboard](https://cloud.githubusercontent.com/assets/1636769/19962988/a7f3406c-a1ba-11e6-8e9a-da6b54ae12e2.png)

And the behaviors detailled:
![1 - workspace details - runtime selection - october 2016](https://cloud.githubusercontent.com/assets/1636769/19962996/ade222a4-a1ba-11e6-8dcf-a5177ffe6073.png)

**Comment by ashumilova** [comment]
We can use "Quick Start" instead of "Getting started".

**Comment by slemeur** [comment]
Good idea ! +1

**Comment by slemeur** [comment]
As for the first stage of this issue. we will not implement the part with the filter. 
This part will definitely be the one which will take the more time - and the experience could also be improved with another ideas that I have.

I'm going to update the issue with mockups without the filters.
