### ISSUE TITLE
Manage empty states in IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2972]
There are various situations where the IDE could be seen as "empty". Let's improve that experience by providing tips to the users about what they could do.

We will display:
- links to features. When clicked, it opens the corresponding wizard
- we display the associated keyboard shortcut, so the user can learn them
- we display the Eclipse Che logo as watermark.

*When there are no projects in the workspace:*
![eclipse che empty state - no project](https://cloud.githubusercontent.com/assets/1636769/19963489/ecd985fe-a1bc-11e6-8f8e-f85adc91e407.png)

*When no files are opened in the editor:*
![eclipse che empty state - no file](https://cloud.githubusercontent.com/assets/1636769/20137590/b4dfa282-a67b-11e6-978e-4f844b621f89.png)

We can start with the following features displayed and add other ones later.

**Comment by slemeur** [comment]
@evidolob: The name of the actions are incorrect.

![slack-imgs](https://cloud.githubusercontent.com/assets/1636769/20500599/634264cc-b036-11e6-90c3-b0fe992f06c6.png)

- "File" like this does not mean any action to the user, it must be "Create New File..."
- "Create Project" should be "Create New Project..."

And you are not displaying the keyboard shortcuts.

**Comment by TylerJewell** [comment]
"new" is redundant - it is just not needed

**Comment by slemeur** [comment]
Could you please give a look to the side bug related: https://github.com/eclipse/che/issues/3136

**Comment by slemeur** [comment]
Also managing the Codenvy side has not been properly handled: https://github.com/codenvy/codenvy/issues/1086
