### ISSUE TITLE
Need to update github url in remotes using swagger

### ISSUE THREAD

**Issue by worksamp** [eclipse-che/che#2973]
Hi,

I have eclipse che workspace with java project.

I need to change github url in remotes but using swagger api.

Is there any way to do it?

Thanks and regards,
worksamp

**Comment by tolusha** [comment]
Duplicates https://github.com/eclipse/che/issues/2951

**Comment by ghost** [comment]
PUT to endpoint: `https://localhost:${PORT}/wsagent/ext/git/remote?projectPath=/console-java-simple`

where `$PORT` is the port is the published port for ws-agent port (4401)

Request payload:

`{"branches":[], "url":"${your-remote}", "name":"${your-remote-name}"}`

**Comment by worksamp** [comment]
Hi @eivantsov 

in request payload:
url = github url
name = github project name

is it ryt??

**Comment by worksamp** [comment]
@eivantsov 
I am using endpoint mentioned by you.

can you please help me with parameters.

project path = ?
url = ?
name = ?

**Comment by worksamp** [comment]
@eivantsov 
i am getting following error:
There is no any resources matched to request path /remote

**Comment by ghost** [comment]
@worksamp can you share more info on how you execute the request?

**Comment by worksamp** [comment]
@eivantsov 
I am using rest client, following are the details:

Request type: PUT
Request url: http://${ip-address}:${PORT}/wsagent/ext/git/remote?projectPath=/aspnet-web-simple
Request payload:

{"branches":[], "url":"${github-url}", "name":"origin"}

**Comment by ghost** [comment]
What is your port in this case?

**Comment by worksamp** [comment]
wsagent
4401/tcp
ip-address:33024
http://ip-address:33024/wsagent/ext

so port no is: 33024

**Comment by ghost** [comment]
@worksamp sorry for the confusion. Two mistakes from me:

`remote-add` instead of `remote` in the endpoint

And it should be POST method.

Let me know if it works for you

**Comment by worksamp** [comment]
@eivantsov 
will try it and let you know

**Comment by worksamp** [comment]
@eivantsov 
I replaced remote to remote-add but getting following error:
java.lang.NullPointerException

**Comment by worksamp** [comment]
@eivantsov 
Now i am getting following error:
"message": "Add Remote operation failed, remote name origin already exists."
so i think first i need to remove name "origin"

can you please tell me the endpoint for removing origin?

**Comment by ghost** [comment]
@worksamp i got it wrong, since I thought about adding a new remote. As a workaround you may remove an existing origin remote and add a new one with a new URL.

DELETE `/api/git/remote/origin?projectPath=/yourProject`

**Comment by TylerJewell** [comment]
Thanks @eivantsov - closing as resolved.
