### ISSUE TITLE
Multi-Machine Workspace creation

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2979]
When creating a workspace the names of the machines are not displayed for allocating available ram.

![che-machine-names-for-ram](https://cloud.githubusercontent.com/assets/20580888/19978325/93ed3942-a1c4-11e6-8715-54db9bc2ddcc.jpg)

**Expected behavior:**

Names of each machine. "dev-machine" and "db" in the java-myqsl stack sample.

**Observed behavior:**

All machines are labelled machine.

**Che version:**    Hackathon codenvy
**OS and version:** Debian - Linode remote cloud

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by bmicklea** [comment]
@ashumilova this seems like a quick fix - could it be added to M7?

**Comment by JamesDrummond** [comment]
Fixed with new interface.

**Comment by ashumilova** [comment]
we still have this in workspace+project creation flow

**Comment by ashumilova** [comment]
![image](https://cloud.githubusercontent.com/assets/1611939/20075426/bdb430d4-a53c-11e6-84db-9e7b5712f03d.png)
