### ISSUE TITLE
Cursor doesn't move to the end of line on Emacs keybinding.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#2981]
Cursor doesn't move to next line on Emacs keybinding.

**Reproduction Steps:**

1. Start Che workspace
2. Change keybinding to Emacs. 
3. Open Editor.
3. Press Ctrl-P in Editor.

the cursor moves to previous line.
But  the cursor doesn't move. 

**Che version:**   Nightly   
**OS and version:** CoreOS (but may be OS independent)   
**Docker version:** 1,11,2 (but may be Docker independent)
**Che install:**  Docker (but may be...)

In some cases I type Ctrl-P, Che shows list like the attached image.
I suspect Ctrl-P is hooked by Che IDE before the editor consumes it.

![screenshot 2016-11-04 at 19 44 16](https://cloud.githubusercontent.com/assets/101795/20003066/92283a0e-a2c7-11e6-9a80-68879d2b23a6.png)
.

* Problem started happening recently, didn't happen in an older version of Che: Unknown
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by monaka** [comment]
Ctrl-p works as expected in the C editor.
So Ctrl-p set by Orion may be overridden by JavaExtension.

I think the best way is to fix #2748.
But it may be enough effective to initialize Orion after all extensions initialized.
Simplest way is to change keybinding in JavaExrension. But it may cause other side effects.

**Comment by tolusha** [comment]
Confirm, should be fixed by #2748.

**Comment by monaka** [comment]
Sorry for keep this unresolved.
I checked on the recent nightly.
`Ctrl-P` works well with Emacs binding.
So I close this. Thanks for your implements.

**Comment by monaka** [comment]
Ooops.... `Ctrl + e` doesn't work....  It was hooked by `Recent file` dialog.

I changed the title of this issue and re-open. (recycling ;-)

**Comment by hsgwd** [comment]
How is this issue going? 
I faced the same problem.

Several other Emacs keybindings are also duplicated with IDE or browser keybindings, and I cannot use Emacs keybindings.
I cannot use ``Ctrl +N``  for ``Line down`` because it opens new window of browser.
``Ctrl + B`` cannot be used for ``Previous Character`` because it activates ``Branches`` dialog.

Is there any workarounds for this issue?

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
