### ISSUE TITLE
A lot of space is used for empty panel

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#2987]
<img width="1440" alt="2016-11-04 17 57 18" src="https://cloud.githubusercontent.com/assets/1614429/20012543/61fc19ae-a2b8-11e6-8692-374ff79b23b9.png">

**Comment by slemeur** [comment]
This is related to https://github.com/codenvy/codenvy/issues/1064

**Comment by TylerJewell** [comment]
I like the arrows.  No way to mistake what you mean :)

**Comment by skabashnyuk** [comment]
This is che. It has nothing to do with PR plugin.

**Comment by slemeur** [comment]
The two issues are still connected as they land in the same state - hopefully this one will solve the other one.
On codenvy side, I have not been able to reproduce the issue with another panel than the PR one.
Definitely - if it's not the same problem, it seems related.
