### ISSUE TITLE
Incremental search doesn't work?

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#2992]
It seems incremental search doesn't work even if it was selected Emacs bindings.

**Reproduction Steps:**

1. Set `profile` -> `preferences` and `IDE` -> `Editor` -> `Key bindings` to `Emacs`
2. Open a C-lang file.
3. Press Ctrl+S
4.. type any keys.

**Expected behavior:**

Cursor should be moved matched strings if available.

**Observed behavior:**

Just inserted characters into the editor.

**Che version:**   Nightly on my cluster. And also today's codenvy.io.   
**OS and version:** Probably independent.
**Docker version:** Probably independent.   
**Che install:**    At least Codenvy. And also my specialized K8s cluster.   

* Problem started happening recently, didn't happen in an older version of Che: Unknown
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by tolusha** [comment]
@monaka 
Use `Ctrl+Shift+F` to find test

**Comment by monaka** [comment]
`Ctrl+Shift+F` is't an incremental search, right?
Codenvy (and also mine) shows `Ctrl+S` is bound to "Incremental Find". So it should work.

![screenshot 2016-11-08 at 07 12 40](https://cloud.githubusercontent.com/assets/101795/20078218/07b5d5b6-a583-11e6-80c5-9c3e2f8288f6.png)

And... I found it seems `Ctrl+Shift+F` doesn't search in C source code. It should be opened as the another issue. (I will inspect and report later.)

**Comment by AndrienkoAleksandr** [comment]
@monaka we have "Incremental search". In our IDE we use Orion editor, so you can use "incremental search" embedded to this editor. You can use hotKeys: "Ctrl + F". Thank you for your question. 
![capture image](https://cloud.githubusercontent.com/assets/6873095/20619600/16e52a7c-b2fe-11e6-8e45-1aee6e3c9ad0.png)

**Comment by monaka** [comment]
Hmm? This issue is pointed to Emacs bindings.

> You can use hotKeys: "Ctrl + F". 

In almost all environments which bound to Emacs bindings, "Ctrl + F" are not bound to "incremental search".
Have you ever used Emacsen?

**Comment by AndrienkoAleksandr** [comment]
Sorry @monaka Ctrl + S really doesn't work for Emacs, because editor action was overridden by hidden Action https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java#L682 . Thank you for bug report.

**Comment by monaka** [comment]
@AndrienkoAleksandr  Thanks for fixing this issue. I'll try it after new builds including your patches.
