### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by patrixsk-ss** [eclipse-che/che#301]
**_1 Upvote**_ Hi All,

Is there any plugin (autocomplete, build, etc) for scala ?

Thanks much.

**Comment by ddementieva** [comment]
Hi,

There is no dedicated plugin in Che. 

However, Che uses Orion editor with syntax coloring for Scala. As to build and run environment, you can build a custom stack for it.

**Comment by patrixsk-ss** [comment]
Thanks Daria.

**Comment by TylerJewell** [comment]
We have had about a dozen requests for Scala.  I think there are some private people working on a Scala plugin.  Nate Yonkee, nathan.yonkee@gmail.com I think is leading this.

**Comment by patrixsk-ss** [comment]
Thanks Tyler for the info.

**Comment by ceefour** [comment]
:+1: for this

**Comment by ceefour** [comment]
Especially that Scala is 
1. the language for Spark
2. Usable for frontend & scripting via [ScalaJS](http://scala-js.org)
