### ISSUE TITLE
Cannot start a workspace from centos:6.6

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#3011]
**Reproduction Steps:**

1. Create a workspace from a custom stack:

```
FROM centos:6.6
CMD tail -f /dev/null

```
https://github.com/eclipse/che/blob/2f5ee437370c5194bf593090203c40a302527e82/wsmaster/che-core-api-agent/src/main/resources/agents/scripts/org.eclipse.che.ssh.script.sh#L16

There's no such file in centos:6.6

**Comment by bmicklea** [comment]
PR merged
