### ISSUE TITLE
Customizing dashboard

### ISSUE THREAD

**Issue by Alexpud** [eclipse-che/che#3016]
Hi, i began looking into customizing eclipse che dashboard and found this [https://github.com/eclipse/che/blob/master/CUSTOMIZING.md](url), which says you can customize several parts o eclipse che. 

Following that, i read [https://github.com/eclipse/che/wiki/Development-Workflow](url) and followed it's tutorial, and managed to build the assemblies and other submodules from che. After reading more, i learned that assemblies pull che submodules like dashboard from your repository and not from the folders on che.

My questions are:

1. How can i integrate my changes made on the dashboard to a che container? 
2. Do i need to create a plugin for that?

Thank you.

**Che version:**    4.6   
**OS and version:** Ubuntu 16.04  
**Docker version:** 1.12.1

**Comment by benoitf** [comment]
hello @Alexpud ,
if you perform a change in https://github.com/eclipse/che/tree/master/dashboard
- you can use `$ gulp serve` for development mode (modify file and browser is refreshed with the changes) and connect to http://localhost:3000/
- when you're happy with the changes, you run `mvn install`from this module (dashboard)
- then you go in assembly folder and you run `$ mvn -pl '!assembly-ide-war' clean install` and then you've a custom che .tgz/.zip assemblies in assembly/assembly-main/target folder

**Comment by garagatyi** [comment]
@benoitf **-pl '!assembly-ide-war'** is not related to the topic, so, please, remove it from instructions because it may confuse those who are customizing Che.

**Comment by benoitf** [comment]
@garagatyi it is if you customize only the dashboard (which is the question)

**Comment by Alexpud** [comment]
@benoitf Thank you for the quick answer!

I will try that now!

**Comment by Alexpud** [comment]
@benoitf It worked! Thank you for the help!
