### ISSUE TITLE
Wordpress issue www-data:www-data

### ISSUE THREAD

**Issue by tijsproost** [eclipse-che/che#3018]
To update plugins in a wordpress installation i updated the file folder ownership of the project in eclipse to www-data:www-data. However at the moment that broke the file explorer in eclipse.

anybody suggestions how to fix this and keep wordpress updating plugings directly?

Workspace: PHP-default-stack
Project Source: Git - Wordpress

Step 1 - in terminal
sudo apt-get upgrade
sudo apt-get update
sudo apt-get install nano
sudo apt-get install phpmyadmin (and complete all steps)

Step 2 - setup wordpress

Step 3 - change the project directory owner to www-data:www-data to give the wordpress website permission to update plugins directly. Now my file explorer in the eclipse ide appears to by in 'read only' mode.
I tried to add 'user' to the www-data group and this didn't solve the problem.

Next i changed the owner to user:www-data wich solved the IDE problem but my wordpress install is not updating plugins.

**Comment by benoitf** [comment]
@tijsproost I think you should add more details to this issue in order to reproduce it or help more quickly
Version of Che
Docker image used / workspace
Error reported/screenshot, etc.

**Comment by TylerJewell** [comment]
Yes, we need step by step instructions to reproduce the issue - from the moment of installation + all configuration items.

**Comment by tijsproost** [comment]
@benoitf  @TylerJewell  I updated the question.

**Comment by TylerJewell** [comment]
@kaloyan-raev - adding for perspective and expertise.

**Comment by kaloyan-raev** [comment]
@tijsproost Try loosening permissions instead of changing the ownership, i.e. execute `chmod -R 777 your-wordpress-folder`.

**Comment by tijsproost** [comment]
@kaloyan-raev Wouldn't that effect the overall security?

**Comment by kaloyan-raev** [comment]
@tijsproost You are giving write permissions for all OS users to your project files. What specific security concerns do you have about this?

**Comment by ghost** [comment]
Yes, if a user in a container cannot have access to project files, they won't be displayed in the project tree. I think just lettings everyone to read and write but keeping user ownership will fix the issue for you.

**Comment by tijsproost** [comment]
Ok! The solution works. The only problem I still encounter: if I now upload or create new files they have owner user:user instead of www-data:www-data like all other files. Any suggestions?
