### ISSUE TITLE
The expanded project is collapsed when workspace is restarted (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3021]
When I have an expanded project in the tree and perform restarting the workspace, the project is collapsed. But it should restore previos state

**Reproduction Steps:**
* Expand a project in the IDE.
* Perform restart the workspace.

**Expected behavior:**
The project should save his state. 

**Observed behavior:**
The project is collapsed.

**Che version:**   5.0.0-M7   
**OS and version:**   Ubuntu 14.04 
**Docker version:** 1.12   
**Che install:**  Docker container   

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly:  Yes

**Comment by ashumilova** [comment]
Depends on https://github.com/eclipse/che/issues/2795

**Comment by ashumilova** [comment]
The issue is the result of restore state task - so did re-assign.
