### ISSUE TITLE
Sources are not indexed after being added to the project 

### ISSUE THREAD

**Issue by bartlomiej-laczkowski** [eclipse-che/che#3022]
It looks like the sources that are added to the project by means of copying them from some location to the \projects\project-name dir in Che are not added to the Lucene index. The same situation is if I i.e. use some custom command to download some files/dirs to my project. Added files are visible in explorer tree but none of them can be found i.e. by using 'Navigate To File' action. 

The workaround that probably causes those new files to be added to the Lucene index is to use 'Update Project Configuration...' action.

**Reproduction Steps:**

1. Create new workspace from one of 'Ready-to-go' stacks, i.e. PHP stack.
2. Create new PHP project in Che and name it 'a'.
3. Create 'b.php' file in \tmp directory available in Che machine.
4. Copy 'b.php' file from \tmp to \projects\a directory.
5. 'b.php' file should be visible in the tree structure of 'a' project in Che explorer.
6. Open 'Assistant -> Navigate To File' window and put 'a' in the filter field.

**Expected behavior:**

'a.php' file name should be displayed in the proposals list.

**Observed behavior:**

'a.php' file is not displayed in the proposals list.

**Che version:** 5.0.0-M7
**OS and version:** Ubuntu 14.04 
**Docker version:** 1.12
**Che install:** Docker container   

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: Probably was also in previous versions
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by tolusha** [comment]
Confirm. 
It is only indexed when you open it.

**Comment by vparfonov** [comment]
can't reproduce
