### ISSUE TITLE
Ctrl-A in Terminal tab doesn't work as expected

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#3023]
Ctrl-P, Ctrl-N, Tab are working same as typical consoles, but Ctrl-A doesn't.

**Reproduction Steps:**

1. Forus in `Teiminal` tab
2. Type something.
3. Press `Ctrl-A`

**Expected behavior:**

The cursor moves.

**Observed behavior:**

All regions are selected.

**Che version:**   5.0.0-M7-SNAPSHOT b3ef0a2edcdfb80e
**OS and version:** Probably no dependency.   
**Docker version:** Probably no dependency.   
**Che install:**    Docker container  

**Additional information:**

It seems there have no key binding information in menus.
So I can't determine that this is a specification or a bug.

* Problem started happening recently, didn't happen in an older version of Che: Unchecked
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by vkuznyetsov** [comment]
Should be fixed by https://github.com/eclipse/che/issues/3529

**Comment by AndrienkoAleksandr** [comment]
Fixed after xterm.js intergration https://github.com/eclipse/che/commit/830cc34070808b3b733fdbdccc63ba415fdeabbd
