### ISSUE TITLE
How to customise project properties and preferences in Che?

### ISSUE THREAD

**Issue by mjitch** [eclipse-che/che#303]
In other versions of Eclipse, you've the option of customizing the properties of a project like maven settings, jdk ver, etc. I am not able see such options in che. As a result, maven fails to download my project dependencies and hence, build fails.

**Comment by ghost** [comment]
There isn't such a possibility at the moment. Both Maven and JDK version are defined in a Dockerfile for a chosen environment that runs your workspace.

Can you share Maven output? Why does it fail? Private artifacts? Wrong Maven version?

**Comment by mjitch** [comment]
Problem here is i used a custom artifactory in my maven builds. So, I need an option to specify my own maven settings xml as a preference.

**Comment by ddementieva** [comment]
You may try to use `mvn clean install -s /path/to/your/settings.xml` command in such case.

You can upload your setting.xml file directly in the IDE or copy it into the project directory on a local file system.

**Comment by mjitch** [comment]
i have tried copying my settings xml to my project folder, it didn't work out. It still takes the default maven settings

**Comment by ghost** [comment]
Can you share the command you're running?

**Comment by mjitch** [comment]
I am actually running the standard mvn command from the Eclipse GUI - " mvn clean install package". Run --> Edit Commands

**Comment by ghost** [comment]
Do not forget about `-s /path/to/your/settings.xml`

**Comment by mjitch** [comment]
ok...I'll check that option too and come back. Thanks!

**Comment by ghost** [comment]
Or you may put your settings.xml to `~/.m2`. Maven will use it by default then.

**Comment by mjitch** [comment]
Didn't want to change that actually.

**Comment by ghost** [comment]
Well, these the are the 2 options - either tell Maven what settings to use in the command line or put your settings.xml in the location where Maven expects it.

**Comment by mjitch** [comment]
Now, the settings xml is detected. But it seems Che has issues understanding the Windows format of the location - `<localRepository>.m2\repository</localRepository>`

Logs -

`[INFO] Error stacktraces are turned on.

[ERROR] Could not create local repository at /.m2\repository -> [Help 1]

org.apache.maven.repository.LocalRepositoryNotAccessibleException: Could not create local repository at /.m2\repository`

Not sure now, how do i specify the path in my settings xml.

**Comment by ghost** [comment]
You need to remove it. `.m2/repository` will be created by default.

**Comment by mjitch** [comment]
Yes, finally my project built worked in che! But a few questions still remains though -
1. My custom commands are not saved permanently. Whenever i restart the container, these are wiped clean. Is there a way to save them permanently?
2. We use an SVN repository instead of GitHub. Is there a plugin available to integrate SVN with Che?

**Comment by ghost** [comment]
1. What are the steps to reproduce? I create a workspace, start it, add a command, stop it. Restart it - the command is there.
2. There's no SVN plugin at the moment. You may use terminal and svn command line instead (or commands). SVN is installed in a JAVA stack.

**Comment by mjitch** [comment]
#1 - The command settings are not retained when I restart Che.

**Comment by ghost** [comment]
Just checked it. Commands are there. They are saved into a workspace configuration.  Any special steps  to reproduce?

**Comment by mjitch** [comment]
Nothing special just the routine start and stop. I face it almost every time. Not sure why as I am saving my commands

**Comment by ghost** [comment]
I have tried to reproduce it a couple of times, and commands are there. Can you record a short video demoing the commands are gone/.

**Comment by mjitch** [comment]
ok

**Comment by ghost** [comment]
@mjitch any update? Do you still see your custom commands missing? Please note that commands are saved in a workspace scope, i.e. if you created them in Workspace A they won't be available in Workspace B.

**Comment by mjitch** [comment]
This issue was observed in the last beta. I am working on RC3 at the moment. Since, RC has a problem importing my workspace (another issue I opened) I couldn't verify it. Let me resolve the workspace issue, and then get on with it on the same RC release.

**Comment by mjitch** [comment]
I am not seeing this issue in the latest RC3 release. So, closing it.
