### ISSUE TITLE
OpenShift API implementation

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#3031]
Implement DockerConnector  APIs using OpenShift counterparts.

[ ] Images 
    - buildImage 
    - commit
    - inspectImage
    - listImages
    - pull
    - push
    - removeImage
    - tag
[ ] Network
     - connectContainerToNetwork
     - createNetwork
     - disconnectContainerFromNetwork
     - inspectNetwork
     - removeNetwork
[ ] Exec
    - attachContainer
    - createExec
    - startExec
[ ] Info
    - getContainerLogs
    - getEvents
    - getExecInfo
    - getNetworks
    - getNetworks
    - getSystemInfo
    - getVersion
    - top
[ ] Containers 
    - listContainers
    - getResource
    - putResource
    - removeContainer
    - startContainer
    - stopContainer
    - waitContainer

**Comment by l0rd** [comment]
This tasks are needed to remove --privileged container constraint for running Che workspaces in OpenShift (third bullet of #2847). 

Other tasks are:
- remove usage of hostPath volumes for workpaces (a solution is to download agents via http and #3013 should implement it)
- allow to run workspaces behind a reverse proxy (cf PR #2004)

**Comment by ibuziuk** [comment]
I am going to work on **Containers** implementation, @amisevsk on **Network** & **Exec** and @snjeza on **Images**

**Comment by TylerJewell** [comment]
Superceded by epic tracking all activities.
