### ISSUE TITLE
The Content Assist do not work automatically (regression)

### ISSUE THREAD

**Issue by Madixin** [eclipse-che/che#3038]
The Content Assist do NOT work well while I check the "Show Content Assist automatically" in preferences. However, the content assist show correct while I using the Menu >> Assistant >> Content Assist.

Reproduction Steps:
1, Checking the setting in Menu >> Profile >> Preferences >> IDE >> Editor >> Language Tools >> "Show Content Assist automatically" and it is checked.
2,Input "this" in the class and follow with dot ".", there is not Content assist automatically，However, manually click the menu "Content Assist" , it can trigger the content asist
Expected behavior:
The related method for "this" will be listed after "." for intellisense.

Observed behavior:
 There is not prompt for the method.

Che version: 5.0.0-M5 ,  4.5.1
OS and version: Ubuntu 14.04 LTS
Docker version: 1.12.2
Browser：chrome53 （in winows7）

**Additional information:**
If I click the "Content assist" in menu action manually, It could show method list

* Problem started happening recently, didn't happen in an older version of Che: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
What is the source code that you imported and the project type that was set?

Content assist does not exist for every language and if the project type is not properly structured then content assist should not be available and hidden.

**Comment by Madixin** [comment]
java language and java project type 

If I click the "Content assist" in menu action manually, It could show method list

**Comment by TylerJewell** [comment]
Can you provide step by step instructions of the stack, project cloned, and how the project type was configured.  If the classpath or maven structure is not setup just right, then content assist will cause problems.  WE should avoid this and provide helpful messages, but it's not foolproof.

**Comment by Madixin** [comment]
I just create a simple java project ,only one java class with main fucntion ,using JAVA stack

`public class Main {

```
public static void main(String[] args) {
    // write your code here
    System.out.println("Hello World!");
}
```

}
`

I think the  there is no problem for classpath. because it can  show method list by manually click  "Content assist" , only not automatically

**Comment by TylerJewell** [comment]
Can you share a screen cast of exactly how you create the project, how you set the project type, and so forth.  Our engineers need to see all of the steps one by one.  

Projects do require some human configuration, so if you didn't do these steps then there will be an issue.  Now, content assist should not be available in that case, but to understand the use case you have to show a screen cast or every step you took.

**Comment by Madixin** [comment]
Just sample project using JAVA stack
![1](https://cloud.githubusercontent.com/assets/6182588/20166552/806cfd9e-a750-11e6-8689-91466a0800d7.png)

![2](https://cloud.githubusercontent.com/assets/6182588/20166590/cd5f3400-a750-11e6-9223-989ab64fdac9.png)

![3](https://cloud.githubusercontent.com/assets/6182588/20166679/5efa334c-a751-11e6-9e69-dabf57965f33.png)

![4](https://cloud.githubusercontent.com/assets/6182588/20166696/7ba6ea8a-a751-11e6-918e-3832998a8035.png)

**Comment by Madixin** [comment]
![5](https://cloud.githubusercontent.com/assets/6182588/20171257/cb1b5920-a76a-11e6-96d2-04cea2b1bb02.png)

**Comment by TylerJewell** [comment]
Got it - I think that this issue is more about labeling than a functional bug.  

I think that the "content assist" that you are showing us is related to the Orion editor. And it's specific to certain types of editor assistants and not specifically the intellisense.  But I totally understand that it is really confusing and we need to be explicit on this.

We do _not_ currently support the Eclipse or IntelliJ style auto content assist where we do auto complete without having to type CTRL-Space, for example.  We do get requested for this - but we do not actually support it, and this flag means something different.

@evidolob @vparfonov @ashumilova @slemeur - who can we speak to about this particular issue.  We should change the name of the orion content assist toggle so that it's clearer what this is enabling.  I think it will be common for users to think that this flag means auto-auto-complete, but it does not.

**Comment by slemeur** [comment]
We have added the capability to get auto content assist while typing, but we checked and this is a regression.

@vparfonov 's team will give a look.

**Comment by vparfonov** [comment]
@Madixin  Our first implementation of this feature was not ideal and we want to improve it so we will prepare another solution soon

**Comment by Madixin** [comment]
@vparfonov    thanks

**Comment by 20avva** [comment]
Is this idea going anywhere? I would love to have IntelliJ style auto-completing in codenvy, it would be really helpful.
