### ISSUE TITLE
The button "save" and "cancel" in Debug Configuration window always in disabled status.

### ISSUE THREAD

**Issue by Madixin** [eclipse-che/che#3039]
The button "save" and "cancel" in Debug Configuration window always in disabled status. You can not save or cancel the configutation that all changes are saved automaticlly.
The commands dialog also have this problem.

Reproduction Steps:
1,Click Menu >> Run >> Edit Debug Configurations... to open the Debug Configuration Window
2,Click the Add to new a new Remote Java
3,Check the button "save" and "cancel" status

Expected behavior:
the button "save" and "cancel" should be enabled.

Observed behavior:
the button "save" and "cancel" always in disabled status.

Che version: 5.0.0-M5
OS and version: Ubuntu 14.04 LTS
Docker version: 1.12.2
Browser：chrome53 （in winows7）

Problem started happening recently, didn't happen in an older version of Che: No
Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
We are going through a significant rewrite of the command and debug configuration dialog boxes. It is happening in the upcoming sprints.  So I think this design and implementation will supplant this request.

https://github.com/eclipse/che/issues/2463
https://github.com/eclipse/che/issues/2901
