### ISSUE TITLE
Developing with libgdx in che

### ISSUE THREAD

**Issue by michaellee8** [eclipse-che/che#3041]
I am currently working on my own game with libgdx, and I try to do it with che since it is portable, compact and currently my favorite IDE. I am using the one provided by codenvy.io.
However, it is too difficult to google for an appropriate recipe, but I just not good enough to create one by myself. Therefore, I am posting here to know if someone can help me to archive it. Can someone help?

I believe the following components is required to make libgdx work in che.
1. jdk8
2. andoid sdk
3. x11/noVNC
4. gradle

I don't make sure if the following is needed to run it properly.
1. maven
2. ssh

I will be glad if anyone can help me. Thank you.

**Comment by tolusha** [comment]
You definitely need to write you custom recipe. If you are familiar how to install to components in question at you desktop machine it will be easy for you to do the same in Codenvy.

Go to `https://codenvy.io/dashboard/#/`  -> `Workspaces` -> `Add Workspace` -> `Runtime` -> `Custom stack` -> `DOCKERFILE` -> `Write you own stack`

![screenshot from 2016-11-10 10 21 03](https://cloud.githubusercontent.com/assets/1640675/20169374/d5ac693c-a72f-11e6-9e67-d936b6e2c7cf.png)

Add following recipe replacing `COMMANDS_TO_INSTALL_COMPONENTS` by commands to install needed components. You don't need to install jdk8 and maven. They are already there.

```
FROM codenvy/ubuntu_jdk8
RUN COMMANDS_TO_INSTALL_COMPONENTS
CMD tail -f /dev/null
```

And click `CREATE` button on the top-left corner.

**Comment by michaellee8** [comment]
Thanks for replying. But hence another problem comes out.
1. **_How to configure the x11/novnc so that it can shows my both my GUI output for desktop application (could be java swing) and android (emulator) application**_
2. I just don't sure about that, does libgdx need extra components to shows its HTML5/javascript, 
   what are they and how to install?

Big thanks for replying.

**Comment by TylerJewell** [comment]
@michaellee8 - sorry about the delay.  We have been quite busy with readying the 5.0 release.  You should take a look at the recipe for our Android stack, which includes x11/novnc in it.  It's located in github.com/eclipse/che-dockerfiles.
