### ISSUE TITLE
Remove temporary workspaces on server shutdown

### ISSUE THREAD

**Issue by voievodin** [eclipse-che/che#3044]
Temporary workspaces are removed only when workspace stop method is called directly, 
so if che server is stopped and temporary workspaces are running they won't be removed, unless you start and stop them again.

**Reproduction Steps:**

1. Start a temporary workspace
2. Stop che server in any possible way e.g. `che.sh stop`
3. Start che server

**Expected behavior:**
Temporary workspaces removed

**Observed behavior:**
Temporary workspace are listed with `STOPPED` status

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: YES

The simplest way to fix this issue is to remove temporary workspace on `WorkspaceStatus[STOPPED]` event.

**Comment by mshaposhnik** [comment]
Fixed by https://github.com/eclipse/che/pull/3245
