### ISSUE TITLE
Endpoint for removing origin in eclipse che

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3047]
can anyone knows how to delete origin from eclipse che ?
I need endpoint for that

**Comment by TylerJewell** [comment]
Sorry, the question is not clear.  Can you provide some steps to reproduce the problem that you are having with any screen shots?

**Comment by nipobhsnro** [comment]
@TylerJewell 
Actually by using api i need to change the path in origin.(Github path)
![origin](https://cloud.githubusercontent.com/assets/23380460/20179492/64bd73e0-a77c-11e6-81c7-6d3186295e4f.PNG)

I have attached the screenshot for the same.

**Comment by nipobhsnro** [comment]
I have created the sample project from stack but now i need to remove "origin" from github-->remotes but by using any api not manually

Is there any way to do that?

**Comment by vinokurig** [comment]
To remove remote you should use DELETE request to [wsagent url]/git/remote/[remote name]?projectPath=[project Path]

wsagent url is showed in 'Operation Perspective'
remote name is the name of the remote you want to remove
project Path is a path to project e.g. /MyProject

**Comment by nipobhsnro** [comment]
I am using following path:
Request type: Delete
Url: http://ip-address:wsagent-port-no/wsagent/ext/git/remote/origin?projectPath=/Java-20

but i am getting following error:

There is no any resources matched to request path /remote/origin

**Comment by vinokurig** [comment]
What is the version of your CHE assembly?

**Comment by nipobhsnro** [comment]
version means??

**Comment by vinokurig** [comment]
yes, you can find it in menu 'help' --> 'about'

**Comment by nipobhsnro** [comment]
ok..
4.5.1 version

**Comment by vinokurig** [comment]
We have changed the git API in the latest version.
As for 4th. version the request is:
Request type: POST
Url: [wsagent url]/git/remote-delete/[remote name]?projectPath=[project Path]

**Comment by nipobhsnro** [comment]
@vinokurig :+1: 

Thank you so much :+1: 

Its working :-)
