### ISSUE TITLE
Are workspaces persistent?

### ISSUE THREAD

**Issue by kinastowski** [eclipse-che/che#3057]
Hi, I new to Che and want to try it out on Amazon and/or Google Cloud but every time I restart my Instance/VM I lose all my workspaces. Is this how Che works? Is it possible to make them persistent?
thanks

**Comment by chrisdbarnett** [comment]
When you are in the CHE IDE, ensure you press the stop button before
shuttting down anything else and it will save a snapshot that will restore
then next time you open up the workspace.

**Comment by kinastowski** [comment]
thanks, that worked
