### ISSUE TITLE
Cannot start Eclipse Che using command line tool

### ISSUE THREAD

**Issue by wtrocki** [eclipse-che/che#3058]
Cannot start Eclipse Che due to missing docker hub tag:
`Tag latest not found in repository docker.io/eclipse/che-server`

When going to dockerhub we see that `latest` tag is in fact missing:
https://hub.docker.com/r/eclipse/che-server/tags/

**Note:**
If latest tag is not desired here it would be better to update following guide:
https://eclipse-che.readme.io/docs/che-getting-started

**Workaround**

Change $CHE_VERSION from latest to any version available in:
https://hub.docker.com/r/eclipse/che-server/tags/

**Reproduction Steps:**

1. Download and install che command line as in Getting Started Guide:
https://eclipse-che.readme.io/docs/che-getting-started
2. Execute `che start`
```
╰─$ che start                                                                                                                                     130 ↵
INFO:  Pulling image curl:latest
INFO:  Downloading cli-latest
WARNING: No kernel memory limit support
INFO: (che update): Pulling image eclipse/che-launcher:nightly
nightly: Pulling from eclipse/che-launcher

Digest: sha256:6429fdec20046021d4c9c8aeeb9c8945ec2378d6dc973a82ce724afb68eab09e
Status: Downloaded newer image for eclipse/che-launcher:nightly

INFO: ECLIPSE CHE: Pulling image eclipse/che-server:latest
Pulling repository docker.io/eclipse/che-server
FATA[0003] Tag latest not found in repository docker.io/eclipse/che-server
```

**Che version:**    master (ebe8ed9fac8223fcafbdc1d08b1afe1fe8aeb446)
**OS and version:** MacOs X El Capitan 
**Docker version:** Docker version 1.12.3, build 6b644ec
**Che install:**    [command line/source code]

**Comment by TylerJewell** [comment]
Yes, good catch.  I have updated hte docs to now be explicit that "5.0.0-latest" is required if using htis particular container.  i will have our CI group push a "latest" for eclipse/che-server to DockerHub.  This particular image is a new kind of image.  We used to have all of these as codenvy/che-server and have been sloppy in moving them over to eclipse.
