### ISSUE TITLE
Invalid docker ip address when running by cli

### ISSUE THREAD

**Issue by wtrocki** [eclipse-che/che#3060]
When starting eclipse che cli it's trying to detect what user IP should be used by calling get_docker_host_ip. For docker 1.12.3 on mac this URL would be localhost.

Mentioned function:
https://github.com/eclipse/che/blob/master/cli.sh#L285-L297

Urls returned:
```
INFO: ECLIPSE CHE: Use: http://192.168.65.2:8080
INFO: ECLIPSE CHE: API: http://192.168.65.2:8080/swagger
```
Valid urls
```
INFO: ECLIPSE CHE: Use: http://localhost:8080
INFO: ECLIPSE CHE: API: http://localhost:8080/swagger
```

Problem is most likely to be platform related (OSX and docker) 
This is really minor issue. 

**Reproduction Steps:**

1. run `che start`
2. Wait for command to execute
3. Go to url provided in  `INFO: ECLIPSE CHE: Use: http://192.168.65.2:8080`  
4. Should finish with browser timeout
5. Go to `http://localhost:8080` - it works

**Che version:**    master (ebe8ed9fac8223fcafbdc1d08b1afe1fe8aeb446)
**OS and version:** MacOs X El Capitan 
**Docker version:** Docker version 1.12.3, build 6b644ec
**Che install:**    [command line/source code]

**Comment by TylerJewell** [comment]
@wtrocki - the update of docker 1.12.3 has caused our utility - eclipse/che-ip:nightly to be put into a bit of weird state.  We issued an emergency fix to fix a problem on windows.  It seems that on docker for windows, they changed the interface for which we discover the IP address from eth0 to hvint0.  

I was under hte impression that we were ok on Docker for Mac, but it seemst that you are running into issues.  

It is our preference not to show localhost, but to get the right IP address.  So I consider this an issue with the eclipse/che-ip utility which discovers the right IP address.  

@benoitf - can you take a look please?

**Comment by TylerJewell** [comment]
This is the source code for the IP discovery that we do.
https://github.com/eclipse/che-dockerfiles/blob/master/che-ip/getip.sh

**Comment by benoitf** [comment]
the utility che-ip is getting the docker ip.
But on macOs this ip is only accessible to docker containers

So while we still need to use 192.168.65.2 end user should only see localhost

Another way is to add aliasing of this ip (which is written there)
https://eclipse-che.readme.io/docs/usage-docker#pre-reqs

changing the display will simplify the user process.

**Comment by TylerJewell** [comment]
Is this the right logic?
1. If inside che-launcher, codenvy cli, or che cli, and:
2. if docker_for_mac(), then:
3. Change display_host=localhost for any presentation of the IP + port to the end user?

**Comment by benoitf** [comment]
@tylerjewell Correct

**Comment by TylerJewell** [comment]
@benoitf - I have added such logic into the Codenvy CLI.  I'll let you do it for the che-launcher and che CLI this week with the rationalization + improvements.

You probably should do a quick fix for the Che CLI.sh in master given that we will have the conference on Tuesday.

**Comment by benoitf** [comment]
It has been fixed in master
