### ISSUE TITLE
Set uncaught exception handler for executors

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3065]
Now in Che uncaught exception handler is not set. Due to this we may miss some bugs. I suggest to set it with com.google.common.util.concurrent.ThreadFactoryBuilder#setUncaughtExceptionHandler or similar method.

**Comment by skabashnyuk** [comment]
Can you narrow the scope of this issue and list the places where we should do that?

**Comment by garagatyi** [comment]
Here is StackOverflow topic with explanation what is happening in first comment http://stackoverflow.com/questions/3929342/choose-between-executorservices-submit-and-executorservices-execute 

We should find all places where ExecutorService is created and call appropriate method, e.g. com.google.common.util.concurrent.ThreadFactoryBuilder#setUncaughtExceptionHandler
