### ISSUE TITLE
How to run java project in eclipse che

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3067]
I have created 1 java project in eclipse che
Can please anyone tell how to run it?

Beach when I am running project with given command it automatically get deleted

**Comment by bmicklea** [comment]
Can you provide more information on your setup?
- Are you using a Java console or web app?
- Are you using our Java stack or a custom stack?
- Can you provide a screenshot or short video of the behavior when you click on the command?

**Comment by nipobhsnro** [comment]
I am using java console from java stack

**Comment by nipobhsnro** [comment]
please find attached screenshot:
![build](https://cloud.githubusercontent.com/assets/23380460/20272268/6d81749c-aab3-11e6-89b0-3e76080a5d5d.PNG)
![builderror](https://cloud.githubusercontent.com/assets/23380460/20272269/6d911a50-aab3-11e6-9123-ec31e6189479.PNG)
![run1](https://cloud.githubusercontent.com/assets/23380460/20272270/6d9aaf0c-aab3-11e6-8f28-1dad43d0208d.PNG)

**Comment by bmicklea** [comment]
Everything looks okay - you should end up with this:

<img width="804" alt="screen shot 2016-11-14 at 3 08 43 pm" src="https://cloud.githubusercontent.com/assets/7644938/20280888/5172123e-aa7c-11e6-8fbb-69bec116e05e.png">

The hello world line is just at the bottom of the build output and easy to miss.

**Comment by nipobhsnro** [comment]
But after running project explorer is getting blank...

**Comment by tolusha** [comment]
I can't reproduce the issue. What version of che did you use?

**Comment by nipobhsnro** [comment]
Che version: 4.5.1
Now its working.
Thanks @bmicklea and @tolusha for your help
