### ISSUE TITLE
File Sync agent is disabled by default

### ISSUE THREAD

**Issue by wtrocki** [eclipse-che/che#3071]
### Background  

`che mount` command would fail if `File Sync` agent would be disabled. 
It looks for me that by default all workspaces having `Unison File Synchronizer` option disabled. 
If users wish to use file sync they need to enable it in workspace options.

![screen shot 2016-11-14 at 9 52 55 pm](https://cloud.githubusercontent.com/assets/981838/20284365/b9e8edaa-aab4-11e6-811c-656abed828bd.png)

This information is missing from in documentation:
https://eclipse-che.readme.io/docs/desktop-ide-mounting

### Required actions

- Add info to   https://eclipse-che.readme.io/docs/desktop-ide-mounting to enable agent before executing sync. 
- Provide some useful information when executing `che mount`.
We can do this by querying `GET /workspace/{id}/check` and see if `org.eclipse.che.unison` agent is enabled.

### Steps to reproduce

1. Create default java workspace ( File Sync disabled)
2.  Try to sync it localy using guide: https://eclipse-che.readme.io/docs/desktop-ide-mounting
3. `che mount` command returns no results - file sync failed.

### My setup 

Che version: master (ebe8ed9)
OS and version: MacOs X El Capitan
Docker version: Docker version 1.12.3, build 6b644ec
Che install: [command line/source code]

**Comment by TylerJewell** [comment]
Hi!  So it should be the scenario where the sync agent is optional not required.  If you do not have the sync agent sync does occur but the initial sync is a lot slower.  If the sync utility is failing anyways then that is an outright bug for investigation.   

The extra sync agent just makes sync faster and therefore disabled by default.

**Comment by TylerJewell** [comment]
@benoitf - FYI.

**Comment by wtrocki** [comment]
I did investigation why sync wasn't executed and it looks like 

`che action list-workspaces` 

returns no results on my machine. I have 2 workspaces with projects and sync enabled. Swagger api returns them properly. This feels like issue but it also could be something with my local setup.
I think that would be awesome if command line client would return some results in this case.

Quote from docs:

> You can get a list of workspaces in a Che server that have an SSH agent deployed and are also a dev-machine where /projects are deployed. This means it is sync-ready.

What `are also a dev-machine where /projects are deployed.` means in this context?

**Comment by TylerJewell** [comment]
Before @benoitf investigates - can you confirm that you had the SSH agent deployed?  While the sync agent is _not_ required, the SSH agent _is_ required. So when we do a list workspaces, we should list all workspaces and then give you a table of which workspaces have machines with the SSH agent deployed inside of it.

**Comment by benoitf** [comment]
hello @wtrocki 
based on your information, you said you're using master with
https://github.com/eclipse/che/commit/ebe8ed9fac8223fcafbdc1d08b1afe1fe8aeb446
which is 5.0.0-M6

new updates on che mount are on 5.0.0-M7. Also che.sh was defaulting to 4.7(latest) tag so I guess that it's why it's returning nothing

could you try

```
$ export CHE_UTILITY_VERSION="nightly"
$ che action list-workspaces
```

**Comment by wtrocki** [comment]
It works now. Closing as invalid. Sorry for troubles. Moving my local dev to 5.0.0 release tag.
