### ISSUE TITLE
Not able to load eclipse che workspace url in iframe

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3072]
I am trying to load eclipse che workspace url in ifram but getting following error:

refuse to display <url> in iframe because it set 'X-Frame-Options' to 'SAMEORIGIN'. 

can anyone knows how to resolve it?

Thanks!!

**Comment by tolusha** [comment]
Could you provide more details.
What specific `url` did you past into iframe?

**Comment by nipobhsnro** [comment]
Sorry for late reply...
I want to load eclipse che workspace in iframe.
So in jquery iframe i am trying to open workspace url: http://ip-address/che/wksp-name

But getting error: refuse to display due to X-Frame-Options' to 'SAMEORIGIN

**Comment by ashumilova** [comment]
@nipobhsnro did you change something in che tomcat configuration? By default we have that turned off. 
Please, take a look at your **conf/web.xml** file content:

```
<!--
    <filter>
        <filter-name>httpHeaderSecurity</filter-name>
        <filter-class>org.apache.catalina.filters.HttpHeaderSecurityFilter</filter-class>
        <async-supported>true</async-supported>
    </filter>
-->
```

This filter should be disabled. If you have it enabled for some reasons, then need to add following property:

```
<filter>
      <filter-name>HTTP Header Security Filter</filter-name>
      <filter-class>org.apache.catalina.filters.HttpHeaderSecurityFilter</filter-class>
      <init-param>
        <param-name>antiClickJackingOption</param-name>
        <param-value>ALLOW-FROM</param-value>
      </init-param>
      <init-param>
        <param-name>antiClickJackingUri</param-name>
        <param-value>YOUR URL</param-value>
      </init-param>
    </filter>
```

**Comment by nipobhsnro** [comment]
Actually, i have changed in apache httpd.conf file by follwing and it worked.

<IfModule headers_module>
    <IfVersion >= 2.4.7 >
        Header always setifempty X-Frame-Options GOFORIT
    </IfVersion>
    <IfVersion < 2.4.7 >
        Header always merge X-Frame-Options GOFORIT
    </IfVersion>
</IfModule>

**Comment by nipobhsnro** [comment]
Is it right way to do it?

**Comment by ashumilova** [comment]
You use Apache for running your own application, right? and in the page of your application you tried to put iframe with link to che workspace. But in this case you get "refuse to display in iframe because it set 'X-Frame-Options' to 'SAMEORIGIN'." cause server responses from che server is configured that way, not your apache server.

**Comment by nipobhsnro** [comment]
ok...
now when i adding above code in tomcat web.xml file i am getting following error:

XMLHttpRequest cannot load http://ip-address/che/wksp-name/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'My application url' is therefore not allowed access. The response had HTTP status code 401.

**Comment by ashumilova** [comment]
Can you show the headers values in browser console. maybe it conflicts with our CORS filter. Yes, we haven't tested before those filters switch on together.

**Comment by nipobhsnro** [comment]
![headererror](https://cloud.githubusercontent.com/assets/23380460/20387987/ce68cc10-ace8-11e6-816c-f2eb710bde11.PNG)

**Comment by nipobhsnro** [comment]
![headererror](https://cloud.githubusercontent.com/assets/23380460/20388023/fca8ca6c-ace8-11e6-9d87-51bfa074616d.PNG)

**Comment by nipobhsnro** [comment]
![headererror](https://cloud.githubusercontent.com/assets/23380460/20388045/15b27738-ace9-11e6-91b5-a111eb952a24.PNG)

**Comment by benoitf** [comment]
@nipobhsnro are you using iframe to che server or to an httpd apache server frontend that is running in front of a che server ?

If you use iframe to che running on 8080 port, there is nothing to do, it works like this.
If you put an http server, then you've to tune your apache server but it's no longer che issue.

**Comment by nipobhsnro** [comment]
@benoitf  I am accessing che url(like http:ip-address/che/wkspname) from my machine
so do i need to tune apache server with my machine?

**Comment by benoitf** [comment]
@nipobhsnro by default it should use 8080 port no ? so more `http://ip-address:8080/che/wkspname` than `http:ip-address/che/wkspname`
UD in dev mode is accessing workspace api from a remote server and it works.

I've also tried with a jsfiddle and it works so it's not che the problem
http://jsfiddle.net/zyb6w87k/3/

![image](https://cloud.githubusercontent.com/assets/436777/20392257/4e551b5c-acd7-11e6-8e5b-1a7d4187fa72.png)

**Comment by nipobhsnro** [comment]
@benoitf  I tried using above jsfiddle but getting same error. please find attached screen shot for the same
![che_error](https://cloud.githubusercontent.com/assets/23380460/20698191/40d4bb52-b625-11e6-9206-d9a62fdaa4ae.PNG)

**Comment by nipobhsnro** [comment]
![che_error](https://cloud.githubusercontent.com/assets/23380460/20698195/4ddda35e-b625-11e6-89d5-d3e5a21abda3.PNG)

**Comment by benoitf** [comment]
@nipobhsnro Che is unauthenticated and running on port 8080 by default.
So it's mainly your changes or adding a Apache or nginx frontend that is causing the issue
