### ISSUE TITLE
Discussion: Adding OT to Pair Programming Extension

### ISSUE THREAD

**Issue by shadowcodex** [eclipse-che/che#3080]
Pair Programming extension is great, but needs a collision algorithm and I think OT (Operational Transformation) is up for the job.

I'm going to start working on adding the functionality to https://github.com/eclipse/flux. But wanted to drop an issue here for discussion and tracking. I'll reference the issue over at the flux repo when I get over there. 

Eclipse/flux#24

**Comment by shadowcodex** [comment]
@sunix What other backbones were you thinking of adding besides flux?

@TylerJewell Open source OT implementation I was going to use as a reference: https://github.com/Operational-Transformation/ot.js

**Comment by shadowcodex** [comment]
I am thinking that we only need to implement the inclusion side of OT.  

`p = position` & `c = character to insert` & `sid = identifier`

``` java
void T_inc(ins(p1, c1, sid1), ins(p2,c2,sid2)){
  if (p1 < p2) { return ins(p1,c1,sid1);}
  else if (p1 == p2 && sid1 < sid2) { return ins(p1,c1,sid1)}
  else { return ins(p1 + 1, c1, sid1) }
}
```

we can do the exclusion side too, but doubles everything. But would allow us to support undo and locking.

``` java
void T_exc(ins(p1, c1, sid1), ins(p2,c2,sid2)){
  if (p1 < p2) { return ins(p1,c1,sid1);}
  else if (p1 == p2 && sid1 < sid2) { return ins(p1,c1,sid1)}
  else { return ins(p1 - 1, c1, sid1) }
}
```

**Comment by shadowcodex** [comment]
@sunix if we create a che only backbone we could use rethinkdb to hold the operations.

We could set this up as a che_sync agent to be included on workspace composer options.

**Comment by shadowcodex** [comment]
ShareDB is a database integration layer dedicated to Operational Transformation: https://github.com/share/sharedb

**Comment by ghost** [comment]
@shadowcodex do you want this issue to be opened?

**Comment by TylerJewell** [comment]
I am ok to leave this issue open as long lived issue to track discussion around pair programming.

**Comment by shadowcodex** [comment]
@eivantsov and @TylerJewell . I would leave this up for tracking this discussion as well. However I have become overloaded with system conversions and such at work. So I am unable to work on this going forward. I had high hopes for this, but I just don't have the extra time atm.

**Comment by rektide** [comment]
Perhaps an existing collaborative editing spec or project might work well for Che. Some candidates:

- [TogetherJS](https://togetherjs.com)
- [Gobby's Infinote Protocol](https://github.com/gobby/libinfinity)
- [Atom's Teletype](blog.atom.io/2017/11/15/code-together-in-real-time-with-teletype-for-atom.html) ([very limited](https://github.com/atom/teletype/issues/211) solution atm)
- [Mobwrite](https://code.google.com/archive/p/google-mobwrite/wikis/Protocol.wiki)
- [ShareJS](https://github.com/josephg/ShareJS)
- [ot.js](https://github.com/Operational-Transformation/ot.js/)

(repasting from https://github.com/eclipse/che/pull/2131#issuecomment-345114850 which is a similar, closed issue)

**Comment by rektide** [comment]
Oh! https://github.com/redhat-developer/rh-che/issues/438 has a spike experimenting with either Ot.js or teletype (again [very limited](https://github.com/atom/teletype/issues/211) protocol atm). Yay!

**Comment by sunix** [comment]
@rektide the protocol is one thing but then how you use it afterwards is another. IMO what you thing is limited in atom in <https://github.com/atom/teletype/issues/211> can be solved in Che using the existing piece (teletype-client).

**Comment by eivantsov** [comment]
Closing this one. Please follow https://github.com/eclipse/che/issues/8286
