### ISSUE TITLE
<tag> content is filtered out when a command is executed

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#3091]
**Reproduction Steps:**

1. Create a maven sample project with pom.xml in it
2. Create a command `cd ${current.project.path} && cat pom.xml`
3. Execute this command.

Here's the result. All tags content isn't displayed.

![image](https://cloud.githubusercontent.com/assets/4285392/20360976/94220ad0-ac3e-11e6-9872-6e81c19b0cac.png)

**Comment by musienko-maxim** [comment]
In the 5.6.0 version is not actual

**Comment by ghost** [comment]
Can be still reproduced

**Comment by ghost** [comment]
I think we do it on purpose since we cannot allow execution of any scripts in IDE tabs.
