### ISSUE TITLE
Implement plugins for FindBugs, Checkstyle, PMD and Sonar

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3111]
Most developers coming to Che are used to having IDE plugins for [find bugs](https://marketplace.eclipse.org/content/findbugs-eclipse-plugin), [checkstyle](https://marketplace.eclipse.org/content/checkstyle-plug), [PMD](https://marketplace.eclipse.org/content/pmd-eclipse), and [Sonar](http://www.sonarlint.org/eclipse/).

Che should offer these plugins either out of the box (as it does with Maven, git and SVN) or through add-on extensions.

These would add inline markers for defects in the IDE and make using Che for most developers much more enjoyable.

**Comment by bmicklea** [comment]
@ashumilova can you estimate the effort for doing these set of plugins?

**Comment by manueldeveloper** [comment]
Is there any task scheduled in order to integrate sonar? Thanks

**Comment by bmicklea** [comment]
Not at this time - but we’d welcome community contributions in this area :)

**Comment by lovedshell** [comment]
Is there already has plugin-checkstyle  in Che? if i want to use checkstyle in che, Should I develop an plugin-checkstyle  for che？

**Comment by skabashnyuk** [comment]
There is no separate functionality for that. However, you can use maven checkstyle to do the same thing.

**Comment by lovedshell** [comment]
thanks. I has already use maven command-'mvn checkstyle:checkstyle'  to realize that. @skabashnyuk
