### ISSUE TITLE
Find command not returning all instances of string in project

### ISSUE THREAD

**Issue by darrinsimmons** [eclipse-che/che#3112]
I have installed the angular-patternfly-starter project into a Node stack workspace.  I have installed dependencies and run the project.  When I do a find index.html from within the IDE, it returns 9 results.  When I do the following command:
grep -rl 'index.html' . | wc
it returns 191 files with index.htlm in them.

**Reproduction Steps:**

1. Create Workspace using Node Stack and include angular-patternfly-starter project
2. Install depdendencies
3. run
4. In the terminal, execute grep -rl 'index.html' . | wc
This should give you the total number of files that include index.html
5. In the IDE, select Edit-->Find and search for "index.html" with the default scope and filters checked.
This returns only 9 occurrences of files with index.html in them.

**Expected behavior:**
I expect the find command with default settings should find the same number of occurrences of a given string as a grep -rl '<string>' <project folder> does from the terminal. 

**Observed behavior:**

I observed Google Chrome Helper going to 101.5% CPU for about 10 seconds and then returning with only 9 files with index.html whereas grep showed 191 files.

**Che version:**    5.0.0-M7   
**OS and version:** macOS Sierra 10.12.1   
**Docker version:** 1.12.3(13776)  
**Che install:**    Docker Container

**Additional information:**

This is 100% reproducible.  

I have not tracked it down yet, but having the find window up and closing files seems to hang the browser as well.  If I can narrow down a reproducible scenario, I'll file that as well.

**Comment by tolusha** [comment]
It seems newly created files are not indexed. They also can't be found by `Navigate to file` action.

**Comment by riuvshin** [comment]
@vparfonov blocker bugs can't be next-sprint, please take this as unplanned OR move to next version.

**Comment by bmicklea** [comment]
Removing blocker status - this is something that we want to enhance but will take some time.

**Comment by sunix** [comment]
triage: closing as no update for a while, you can reopen if this is still an issue
