### ISSUE TITLE
Add iPad Support

### ISSUE THREAD

**Issue by jon-c** [eclipse-che/che#3116]
Hello,

Just installed the latest version and when trying to access a new workspace from an IPad (Safari, Chrome and Firefox) an error stating "Unable to initialize IDE" is shown before the workspace creates a snapshot and stops.   

Thanks

**Comment by TylerJewell** [comment]
We have not tested Che against mobile devices yet.  So it will not be easy to determine whether the issue is due to something that is in the core system or whether it is for iOS platform.

There are a number of usability items in the IDE right now which are not tablet optimized so we would expect it to run but not be functional.

Out of curiosity - what is your thinking for using Che on an iPad - what is the use case?

**Comment by jon-c** [comment]
I have multiple desktops and laptops that I use for work most of the time but often find myself with just wanting to carry a tablet when I'm between locations or out and about.  I happen to have a IPad that I use when I can pull it away from the kids and I was hoping this might be a solution to me carrying both it and my laptop everywhere.  

I'm also looking at Che as a solution for remote/local "pairing" or continuation of development between our on and offshore teams and depending on where they are, some are carrying decent sized Android devices that could be used in a pinch.  Right now, we can use Remote Desktop or Webex which is also not ideal but works.

Jon

**Comment by TylerJewell** [comment]
That is great.  I hope we can find a way to get a configuration that works for your team.

In terms of androi apps we would expect it to work with the chrome browser on those devices.  I would just expect iOS to be problematic.

**Comment by shadowcodex** [comment]
@jon-c is there any way for you to post a log? Either from the workspace creation or from browser? I know you are on iOS so there are two options for getting a browser log from your device. You could either hook up to a mac and do safari debugging. Or you can use firebug lite bookmarklet to get it directly on your device.

I'll also start working to reproduce this and try and figure out where it is breaking.

safari debugging: https://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787

bookmarklet: https://getfirebug.com/firebuglite_mobile

Thanks!

**Comment by jon-c** [comment]
Here's the console output

[Warning] ARIA: Attribute " (3) (vendor-ae4aa9ca8d.js, line 127)
"aria-label"
"\", required for accessibility, is missing on node:"
<input type="hidden" name="dev" ng-trim="false" data-ng-model="valueModel" ng-required="true" tabindex="0" class="ng-pristine ng-untouched ng-valid md-input ng-valid-required" id="input_9" required="required" aria-invalid="false">
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Warning] Unexpected CSS token: : (font-awesome.min.css, line 4)
[Log] ZeroClipboard error of type "flash-disabled": Flash is disabled or not installed (wksp-m7h7, line 5243, x8)
[Error] WebSocket network error: The operation couldn’t be completed. Connection refused
[Error] Failed to load resource: Could not connect to the server. (project, line 0)
[Error] Failed to load resource: Could not connect to the server. (supported, line 0)
[Error] ERROR (org.eclipse.che.plugin.languageserver.ide.LanguageServerFileTypeRegister): 
java.lang.Exception: 
    at Unknown.Vl(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.Uw(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.Yw(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.$w(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.xr(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.anonymous(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.promiseReactionJob(Unknown)
Caused by: org.eclipse.che.ide.commons.exception.ServerDisconnectedException: undefined
    at Unknown.Vl(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.Uw(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.B$a(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.A$a(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.Am(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.ym(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.anonymous(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    at Unknown.anonymous(http://192.168.1.28:8080/che/wksp-m7h7?uid=773592)
    E7 (_app-0.js:5322:157)
    F7 (_app-0.js:5324:355)
    m_ (_app-0.js:5324:154)
    i_ (_app-0.js:5322)
    nJb (_app-0.js:2293)
    xr (_app-0.js:5785:229)
    (anonymous function) (_app-0.js:1237:89)
    promiseReactionJob
[Error] Failed to load resource: Could not connect to the server. (ext, line 0)
[Error] Failed to load resource: The request timed out. (fontawesome-webfont.woff2, line 0)
[Info] INFO (org.eclipse.che.ide.statepersistance.AppStateManager): write: {"workspace5a86yka6ap1jbpua":{"workspace":{"workspace":{"perspectives":{"Project Perspective":{"ACTIVE_PART":"org.eclipse.che.ide.extension.machine.client.processes.panel.ProcessesPanelPresenter","PART_STACKS":{"INFORMATION":{"SIZE":571,"ACTIVE_PART":"org.eclipse.che.ide.extension.machine.client.processes.panel.ProcessesPanelPresenter","HIDDEN":false,"PARTS":[{"CLASS":"org.eclipse.che.ide.notification.NotificationManagerImpl"},{"CLASS":"org.eclipse.che.ide.extension.machine.client.processes.panel.ProcessesPanelPresenter"}]},"NAVIGATION":{"SIZE":0,"HIDDEN":true,"PARTS":[{"CLASS":"org.eclipse.che.ide.part.explorer.project.ProjectExplorerPresenter"}]},"TOOLING":{"SIZE":0,"HIDDEN":true}}}}},"editor":{}}},"workspace99zld74uw6fna45f":{"workspace":{"workspace":{"perspectives":{"Project Perspective":{"ACTIVE_PART":"org.eclipse.che.ide.extension.machine.client.processes.panel.ProcessesPanelPresenter","PART_STACKS":{"INFORMATION":{"SIZE":260,"ACTIVE_PART":"org.eclipse.che.ide.extension.machine.client.processes.panel.ProcessesPanelPresenter","HIDDEN":false,"PARTS":[{"CLASS":"org.eclipse.che.ide.notification.NotificationManagerImpl"},{"CLASS":"org.eclipse.che.ide.extension.machine.client.processes.panel.ProcessesPanelPresenter"}]},"NAVIGATION":{"SIZE":259,"HIDDEN":false,"PARTS":[{"CLASS":"org.eclipse.che.ide.part.explorer.project.ProjectExplorerPresenter"}]},"TOOLING":{"SIZE":260,"HIDDEN":true}}}}},"editor":{}}}} (wksp-m7h7, line 5322)
[Error] WebSocket network error: The operation couldn’t be completed. Connection refused

**Comment by shadowcodex** [comment]
@jon-c just by looking at that it looks like websockets are blocked/not-connecting.

Are you running behind a firewall? Just located my ipad pro so will test it's websocket connect to my local che instance.

**Comment by jon-c** [comment]
No.  I'm able to get to the front page.   The workspace actually stops when I go to it from the iPad and   I'm also able to replicate it on regular Safari in OSX and the Simulator in Xcode.  My Windows 10 laptop can access the same remote workspace without an issue.   Che is running on another Windows 10 Docker instance and the firewall is disabled.  I can install the server on a Linux VM later if you think that may make a difference.

**Comment by shadowcodex** [comment]
I'm having the same issue accessing from my ios device and safari on osx.

Works in chrome on osx. I'm going to search for previous issues with websockets and see if this has been encountered before. I'll get back to you later today or tomorrow.

thanks,
shannon

**Comment by ghost** [comment]
@jon-c @shadowcodex are you sure you can run Che on a Mac and then access it from a Win machine?

**Comment by shadowcodex** [comment]
@eivantsov mine is running on centos and accessing from Mac/iPad . Works fine from chrome on Mac, but not safari. Nothing works on iPad.

Has to do with the way Apple handles secure websockets. 

However it shouldn't matter what system Che is hosted on. It should still be accessible from any browser.

**Comment by ghost** [comment]
@shadowcodex well, it matters. When running on Mac or Win you need to make sure your VM is externally reachable. In your case, you run it on CentOS where docker runs natively.

**Comment by jon-c** [comment]
It's running on a Windows machine,  firewall disabled and I'm able to access it from other machines without an issue.   The issue is only on OSX with Safari or iOS with any browser.

Thanks

**Comment by ghost** [comment]
@jon-c how do you run Che on Windows machine? What run syntax did you use?

**Comment by jon-c** [comment]
I run it in the latest docker for Windows 10 using the docker command on the che site.

**Comment by ghost** [comment]
`che.bat start`?

And you are able to connect to a workspace from another machine? What IP do you use when accessing Che on Win 10 machine where Che is run and another machine?

**Comment by TylerJewell** [comment]
#2481 - this is the tracking issue for formal ipad support.  Closing this issue and ask that you track the other one.
