### ISSUE TITLE
Need to push changes to github branch

### ISSUE THREAD

**Issue by worksamp** [eclipse-che/che#3122]
I have 1 github repo and have multiple branches.
I am able to push changes to github master repo but now i need to push changes to any 1 branch.
 can anyone please tell me how to puch changes to github branch?

**Comment by TylerJewell** [comment]
If on the command line or in the GUI, did you "git checkout <branch>"?   And when you do this, you can then push back to your origin the changes to this branch.

**Comment by shadowcodex** [comment]
Try this:

``` shell
$> git checkout master
$> git push origin branchname # assuming branch is created
```

For more information on branching take a look at this book, chapter 3. https://git-scm.com/book/en/v2

**Comment by nipobhsnro** [comment]
in eclipse che-->git-->remotes
I am adding Name= origin & location=github ssh url for main repo

So for branch what will be the url?

**Comment by nipobhsnro** [comment]
@TylerJewell  & @shadowcodex 👍 
Thank you so much..by using $git push origin branchname i am able to push code to branch

**Comment by shadowcodex** [comment]
@nipobhsnro glad to hear it!
