### ISSUE TITLE
Endpoint for create and delete branch in eclipseche-->git-->branches

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3126]
I need to rename master branch by another name in eclipseche-->git-->branches using api.

can anyone please help me with the endpoint for the same

**Comment by TylerJewell** [comment]
@vinokurig @bmicklea @vkuznyetsov - this is an API-related question.

**Comment by nipobhsnro** [comment]
@TylerJewell : can you please help me with respective url to post this question beacuse i am totally new to this and need to create branch using wsagent url.

**Comment by TylerJewell** [comment]
I've cc'd the people who would need to help.  They are all offline now - it's their Friday evening.  So they will take a look when they can.

**Comment by nipobhsnro** [comment]
ok....sure thank you so much

**Comment by shadowcodex** [comment]
Here's your endpoint:

![image](https://cloud.githubusercontent.com/assets/1348053/20444574/2f746934-ad97-11e6-977f-c5d0f865c527.png)

**Comment by nipobhsnro** [comment]
@shadowcodex 👍 
Thanks a lot :-) Its worked :-) 👍
