### ISSUE TITLE
Fail to start workspace agent 

### ISSUE THREAD

**Issue by migdur** [eclipse-che/che#3128]
Che failing to succesfully start a workspace agent

**Reproduction Steps:**

1. Che up and running
2. Create workspace (eg. Python 2.7, but tried with others)
3. [Other Steps...]

**Expected behavior:**

**Observed behavior:**

Workspace creates and initializes correctly. Runtime is correctly started but the workspace agent initialization is failing. Project cannot be created inside the workspace.

**Che version:**    4.7.2
**OS and version:** Windows 7 Professional 64 bit
**Docker version:** 1.12.2 (API 1.24)
**Che install:**    server (eclipse-che-latest zip) 

**Additional information:**
Log:
[default] [DOCKER] 2.7: Pulling from codenvy/ubuntu_python 
[default] [DOCKER] Digest: sha256:ab9caddab203062765dd81ea313dad27afcda76a9d569a5c6951c65d62efe608 
[default] [DOCKER] Status: Image is up to date for codenvy/ubuntu_python:2.7 
[default] [DOCKER] Step 1 : FROM codenvy/ubuntu_python:2.7
[default] [DOCKER] ---> 3551fcad3fd5
[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2016-11-19 17:11:05,796[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32
[STDOUT] 2016-11-19 17:11:05,799[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC
[STDOUT] 2016-11-19 17:11:05,801[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0
[STDOUT] 2016-11-19 17:11:05,803[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2016-11-19 17:11:05,804[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.4.27-boot2docker
[STDOUT] 2016-11-19 17:11:05,804[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2016-11-19 17:11:05,807[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jre1.8.0_65
[STDOUT] 2016-11-19 17:11:05,808[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_65-b17
[STDOUT] 2016-11-19 17:11:05,809[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2016-11-19 17:11:05,811[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2016-11-19 17:11:05,811[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2016-11-19 17:11:05,813[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2016-11-19 17:11:05,816[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2016-11-19 17:11:05,819[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2016-11-19 17:11:05,819[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
[STDOUT] 2016-11-19 17:11:05,820[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2016-11-19 17:11:05,822[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2016-11-19 17:11:05,823[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2016-11-19 17:11:05,824[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2016-11-19 17:11:05,831[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2016-11-19 17:11:05,832[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2016-11-19 17:11:05,832[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2016-11-19 17:11:05,832[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2016-11-19 17:11:05,833[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2016-11-19 17:11:05,835[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2016-11-19 17:11:05,836[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2016-11-19 17:11:06,033[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-11-19 17:11:06,075[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2016-11-19 17:11:06,079[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 610 ms
[STDOUT] 2016-11-19 17:11:06,166[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2016-11-19 17:11:06,167[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
[STDOUT] 2016-11-19 17:11:06,167[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32
[STDOUT] 2016-11-19 17:11:06,287[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/ws-agent/webapps/wsagent.war
[STDOUT] 2016-11-19 17:11:12,997[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[.[/wsagent] 4818]       - Exception sending context initialized event to listener instance of class org.eclipse.che.inject.CheBootstrap
[STDOUT] com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.SecurityException: class "org.eclipse.jdt.internal.core.Openable"'s signer information does not match signer information of other classes in the same package
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.inject.internal.FailableCache.get(FailableCache.java:48) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:138) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:536) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:160) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:123) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:na]
[STDOUT] 	at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140) ~[everrest-integration-guice-1.13.1.jar:na]
[STDOUT] 	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) ~[guice-servlet-4.1.0.jar:na]
[STDOUT] 	at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85) ~[everrest-integration-guice-1.13.1.jar:na]
[STDOUT] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812) [catalina.jar:8.0.32]
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
[STDOUT] 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
[STDOUT] Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.SecurityException: class "org.eclipse.jdt.internal.core.Openable"'s signer information does not match signer information of other classes in the same package
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.inject.internal.FailableCache.get(FailableCache.java:48) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
[STDOUT] 	... 29 common frames omitted
[STDOUT] Caused by: java.lang.SecurityException: class "org.eclipse.jdt.internal.core.Openable"'s signer information does not match signer information of other classes in the same package
[STDOUT] 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895) ~[na:1.8.0_65]
[STDOUT] 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665) ~[na:1.8.0_65]
[STDOUT] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758) ~[na:1.8.0_65]
[STDOUT] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_65]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2469) ~[catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:835) ~[catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1277) ~[catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142) ~[catalina.jar:8.0.32]
[STDOUT] 	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_65]
[STDOUT] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_65]
[STDOUT] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_65]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2469) ~[catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:835) ~[catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1277) ~[catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142) ~[catalina.jar:8.0.32]
[STDOUT] 	at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.8.0_65]
[STDOUT] 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[na:1.8.0_65]
[STDOUT] 	at java.lang.Class.getDeclaredFields(Class.java:1916) ~[na:1.8.0_65]
[STDOUT] 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:37) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37) ~[guice-4.1.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
[STDOUT] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
[STDOUT] 	... 44 common frames omitted
[STDOUT] 2016-11-19 17:11:13,228[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[.[/wsagent] 4818]       - Exception sending context initialized event to listener instance of class org.eclipse.che.everrest.ServerContainerInitializeListener
[STDOUT] java.lang.NullPointerException: null
[STDOUT] 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210) ~[guava-18.0.jar:na]
[STDOUT] 	at org.everrest.core.impl.RequestDispatcher.<init>(RequestDispatcher.java:84) ~[everrest-core-1.13.1.jar:na]
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.getEverrestProcessor(ServerContainerInitializeListener.java:165) ~[che-core-api-core-4.7.2.jar:4.7.2]
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.createWsServerEndpointConfig(ServerContainerInitializeListener.java:123) ~[che-core-api-core-4.7.2.jar:4.7.2]
[STDOUT] 	at org.eclipse.che.everrest.ServerContainerInitializeListener.contextInitialized(ServerContainerInitializeListener.java:91) ~[che-core-api-core-4.7.2.jar:4.7.2]
[STDOUT] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939) [catalina.jar:8.0.32]
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812) [catalina.jar:8.0.32]
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
[STDOUT] 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
[STDOUT] 2016-11-19 17:11:13,230[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5256]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
[STDOUT] 2016-11-19 17:11:13,236[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5307]     - Context [/wsagent] startup failed due to previous errors
[STDOUT] 2016-11-19 17:11:13,263[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/ws-agent/webapps/wsagent.war has finished in 6,975 ms
[STDOUT] 2016-11-19 17:11:13,264[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory /home/user/che/ws-agent/webapps/ROOT
[STDOUT] 2016-11-19 17:11:13,373[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory /home/user/che/ws-agent/webapps/ROOT has finished in 109 ms
[STDOUT] 2016-11-19 17:11:13,379[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-11-19 17:11:13,388[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 7308 ms

* Problem started happening recently, didn't happen in an older version of Che: this is my first install.
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
Really interesting - haven't seen this sort of exception trace before.  Have you tried this on 5.0.0-M7 release to see if it exists there as well?

**Comment by migdur** [comment]
Do you have a pointer to this release please?

**Comment by TylerJewell** [comment]
You should be setting CHE_VERSION (or the appropriate variable based upon the launcher technology that you are using).  The list of versions that are available are available in the [GitHub releases](https://github.com/eclipse/che/tags) or in DockerHub tags - search on eclipse/che or eclipse/che-server.
