### ISSUE TITLE
Project can't be created without Z option

### ISSUE THREAD

**Issue by snjeza** [eclipse-che/che#3129]
**Reproduction Steps:**

- set the option
che.docker.volumes_projects_options=
- try to create a project

**Expected behavior:**

The project is created.

**Observed behavior:**

You will encounter a 500 internal error

**Che version:**     5.0.0-M8-SNAPSHOT, rev 13000b066f56d27792e9b625cb0c8742d04e6444   
**OS and version:** Fedora 24 
**Docker version:** 1.12.3  
**Che install:**    Docker container   

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ghost** [comment]
@snjeza what's your expected behavior? Z suffix has been added to make it possible to do mounts on Fedora and RHEL. And yes, without it you cannot do mounts even using just pure Docker. Am I wrong?
