### ISSUE TITLE
Feature request: Add coffeescript support

### ISSUE THREAD

**Issue by GulinSS** [eclipse-che/che#3131]
There are a lot of frontend projects which use coffeescript. It would be nice to have its support. Even basic support like highlighting is very useful.

**Comment by TylerJewell** [comment]
There seems to be this old issue about how to add support in a custom configuration.  https://github.com/eclipse/che/issues/2180.  @ashumilova - is there a reason that coffeescript syntax highlighting is not enabled by default for certain file types.

**Comment by TylerJewell** [comment]
Closing this as language-specific feature requests will be delegated into language servers for the language that we can add dynamically over time.
