### ISSUE TITLE
How to configure SSL che terminal ?

### ISSUE THREAD

**Issue by xiong305817127** [eclipse-che/che#3132]
Hello, che terminal is there any way to use SSL to start? Configured SSL, I want to make the link more secure, but I use HTTPS configuration che tomcat, che terminal using the WSS protocol, but the link can't do it.

**Comment by ghost** [comment]
@xiong305817127 can you elaborate on what you are trying to achieve? Run Che in https?

**Comment by xiong305817127** [comment]
@eivantsov 
Yes, I want to use the HTTPS run che , I have configured the tomcat (che server and che agent are configured), I visit https://IP:Port/dashboard/#/ide/che/wksp-wcvy, in addition to the terminal failed, all communication is very good. 

brower console error: 

_app - 0. Js: 3586 WebSocket connection to 'wss://10.93.200.102:32855/pty failed: Error during the WebSocket handshake: Unexpected response code: 502 

Whether in starting the terminal command: "~/che/terminal/che -websocket -terminal -addr:4411 -CMD/bin/bash -static ~/che/terminal/", what parameters can configure WSS 
or other way?

**Comment by ghost** [comment]
@xiong305817127 there's https support in Codenvy which is based on Che where URL is rewritten (reverse proxy is used).

You may try installing ssl certificate into every container which isn't an elegant solution though.

**Comment by TylerJewell** [comment]
Yes, thanks eugene.  SSL support is available in codenvys implementation of Che.  See github.com/codenvy/codenvy.

**Comment by xiong305817127** [comment]
thanks,glad to hear it!
