### ISSUE TITLE
After reset or shut down computer CHE networks still exist.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#3135]
After reset or shut down computer CHE can not correct stop and clean up networks, so we need to create job to periodically clean up networks. We have a class DockerContainerCleaner. It periodically clean up docker containers and we can add logic to clean up networks. Actually we can not remove network if network has running docker container which was bind to this network. So it would be logically clean up containers and after that clean up networks.

**Reproduction Steps:**
1. Create workspace from MySql stack.
2. After starting computer type to the terminal: "docker network ls".
3. Run workspace.
4.  After starting computer type to the terminal: "docker network ls". Should appear new network.
5. Reset or shut down computer.
6. After starting computer type to the terminal: "docker network ls".

**Expected behavior:**
Network should not exist or we should clean up it on next working IDE session.

**Observed behavior:**
Network still exist.

**Additional information:**
* Problem started happening recently, didn't happen in an older version of Che: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by AndrienkoAleksandr** [comment]
Our CHE has troubles on start if system contains too much networks.

**Comment by mmorhun** [comment]
Fixed
