### ISSUE TITLE
Image viewer (part) is transparent

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#3136]
Image viewer (part) shouldn't be transparent

**Reproduction Steps:**

1. Open some picture from the the Project Explorer.
2. If picture isn't too large you can see that image viewer (part) is transparent.

**Expected behavior:**

Image viewer (part) shouldn't be transparent and background with text **No files are open** shouldn't be visible.

**Observed behavior:**

Image viewer (part) is transparent and background with text **No files are open** is visible.

**Che version:**    5.0.0-M8-SNAPSHOT   

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

![bug](https://cloud.githubusercontent.com/assets/1636395/20496730/0d0e4dfc-b02f-11e6-93ed-517cecf1db4b.gif)

**Comment by slemeur** [comment]
has been fixed
