### ISSUE TITLE
org.eclipse.che.ws-agent should check java version before starting

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#3137]
If java is installed and its version is lower or equal to 1.7 than agent has to download and install it

**Comment by ghost** [comment]
requested by Aurea

**Comment by bmicklea** [comment]
@tolusha this is a blocker - people need to be able to create workspaces with Java versions older than 1.8.  It's a quick fix, please deal with it tomorrow as we have customers waiting on it.
