### ISSUE TITLE
where is documentation of class ProposalApplyResult?

### ISSUE THREAD

**Issue by tanhe123** [eclipse-che/che#3138]
ProposalApplyResult is a dto class describing how to complete when user uses code-assist in java, but I want to know what every field means in ProposalApplyResult.

where can I find any documentation about it?

ps: the class is in the path `che/plugins/plugin-java/che-plugin-java-ext-lang-shared-src/main/java/org/eclipse/che/ide/ext/java/shared/dto.ProposalApplyResult.java`

**Comment by TylerJewell** [comment]
I think @tolusha or @evidolob will need to provide these details.

@tanhe123 - FYI, eventually the Java plugin will be replaced with the Java language server being developed by Red Hat, which is an implementation of the language server protocol.  It's not there now, but this is a direction we will be heading in.

**Comment by tanhe123** [comment]
@TylerJewell I see maven plugin has been packed into "MavenServer". Is Java Language Server like MavenServer? Any way, it's helpful for us to read the source code, and I think it will supply more standard APIs for us.

Thanks for your contributions. I will continually pay attention to this progress of [language-server-protocol](https://github.com/Microsoft/language-server-protocol).

**Comment by TylerJewell** [comment]
The maven server is something different from the language server.  

Right now, there are different servers that can run in the workspace:
1. Language servers, which are all packaged as ZIP offerings and configurable in the UD.
2. Terminal
3. The ws-agent, which provides our APIs inside the workspace (how we control it)
4. The Che-proprietary java language server --- this is not using the language server protocol, it's something we have built that redhat is converting into a language server that handles the real protocol.
5. The maven server is a server process that we launch if you configure any project with maven project type.  It's how we automatically detect dependencies in the pom and download them in the background.

**Comment by tanhe123** [comment]
@TylerJewell Now I know what the maven server really does, also the differences between servers in workspace and language servers.

Thank you for being patient.

**Comment by dkulieshov** [comment]
Hi, as I see unfortunately there isn't much information on `ProposalApplyResult` class fields in the code but I will try to explain each field here:
- `changeInfo`: corresponding DTO interface ``org.eclipse.che.ide.ext.java.shared.dto.refactoring.ChangeInfo``. It is responsible for storing refactoring meta information like type of operation (_RENAME_COMPILATION_UNIT, RENAME_PACKAGE, UPDATE, MOVE_) or operation resource path. It is used to analyze the operation and to build a diff.
- `changes`: corresponding DTO interface `org.eclipse.che.ide.ext.java.shared.dto.Change`. It holds a list of actual text changes related to this refactoring. Changes are quite simple and contain offset, length and text change.
- `region`: corresponding DTO interface `org.eclipse.che.ide.ext.java.shared.dto.Region`. Contains information corresponding to a text region being changed inside a text editor.

**Comment by tanhe123** [comment]
@dkuleshov thanks for your explanation. 

I have troubles in applying completion. 

For example, if I have a class A: 

```
public class A {
    public static void test(int a, int b) {
        
    }
}
```

I try to apply a completion for method "test" in other class, and the result returned by `CodeAssistService` is:

```
{
    "selection":{
        "offset":208,
        "length":0
    },
    "linkedModeModel":{
        "escapePosition":208,
        "groups":[
            {
                "positions":[
                    {
                        "offset":202,
                        "length":1
                    }
                ]
            },
            {
                "positions":[
                    {
                        "offset":205,
                        "length":1
                    }
                ]
            }
        ]
    },
    "changes":[
        {
            "text":"test(0, 0);",
            "offset":197,
            "length":0
        }
    ]
}
```

The result is something like snippet in IDEs: "changes" is to added to the text editor, and "linkedModeModel" describing where cursor jump when user input 'tab', and the "selection" is the position when user input 'return' to end this completion progress.

But what does "escapePosition" mean?

**Comment by evidolob** [comment]
`escapePosition` is offset cursor position where linked mode should turnoff

**Comment by tanhe123** [comment]
In some case, there is no `linkedModeModel` and it seems that `selection` describing the offset cursor position(when length is 0) or the region(when length is not 0).

For above example, `selection` and `escapePosition` both specify the same offset.

What is the difference between `escapePosition` and `selection`?

**Comment by TylerJewell** [comment]
@evidolob @tanhe123 - sorry this was left open.  I think the crazyniess of 5.0 launch got us all distracted.  Is this still an open issue?

**Comment by tanhe123** [comment]
@TylerJewell This problem has been solved and @evidolob is right.
Che 5.0 is amazing. 
Thanks for your product and contribution. 😄
