### ISSUE TITLE
Not possible to create ws with project if oAuth is not configured

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#3139]
Error appear when I'm trying create WS with project and my oAuth is not configured.
It should not depend on oAuth because it is simple `git clone`, btw it IDE creating workspaces works fine.
<img width="1680" alt="screen shot 2016-11-22 at 11 51 36 am" src="https://cloud.githubusercontent.com/assets/1636732/20519076/1d9e4c5a-b0aa-11e6-87a4-8df1f54fa859.png">

@ashumilova  please take a look

**Comment by skabashnyuk** [comment]
Steps to reproduce?

**Comment by ashumilova** [comment]
Tested on Che and Devbox with github oauth not configured - it's not reproduced.

**Comment by riuvshin** [comment]
I still able to reproduce  it on codenvy in docker.

**Comment by riuvshin** [comment]
So we've figured out that this happens only on MAC when I use "localhost" instead of IP (it works with IP)

<img width="1680" alt="screen shot 2016-11-25 at 1 01 01 pm" src="https://cloud.githubusercontent.com/assets/1636732/20623253/632ec846-b30f-11e6-9442-99fc16026a56.png">

here on screenshot we can see that some links are localhost and some of them 192.168.65.2 that is the issue. @vparfonov @garagatyi  guys please take a look on that


We don't think it is blocker anymore

**Comment by riuvshin** [comment]
No longer actual
