### ISSUE TITLE
Chefile needs to support docker-compose file

### ISSUE THREAD

**Issue by lucyllewy** [eclipse-che/che#3144]
I'm attempting to chefile https://github.com/10up/twentysixteenreact which has both a dockerfile and a docker-compose.yml. Currently chefile/chedir uses the dockerfile only. The correct mechanism would be to use the docker-compose.yml.

Also the Chefile documentation at https://eclipse-che.readme.io/docs/chefile indicates that a composefile can be added inline into the configuration using the `workspace.runtime.docker.composefile` key. This does not currently do anything.

**Comment by benoitf** [comment]
Fixed in 5.2.0
