### ISSUE TITLE
Che version should be visible on the user dashboard

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3154]
Currently to check the version of Che being run you have to open the IDE itself and go to the Help > About menu. It would be much faster when working on Che to be able to confirm the version from the user dashboard page.

Perhaps there should be an "About" entry in the bottom menu for the user?  Or maybe clicking on the Eclipse Che logo at the upper-left can bring up the About?

**Comment by ashumilova** [comment]
Depends on https://github.com/eclipse/che/issues/3257

**Comment by ashumilova** [comment]
Also done for Codenvy - https://github.com/codenvy/codenvy/issues/1273
