### ISSUE TITLE
Set "expand tabs" according to file type being edited

### ISSUE THREAD

**Issue by impca** [eclipse-che/che#3157]
When editing Makefile, tabs should not automatically be converted to spaces, otherwise Makefiles won't work. 

However, when editing other files, tabs SHOULD be automatically converted to spaces (depending on user's preferences, of course).

Is there a way to set the editor to handle this automatically? 

**Expected behavior:**
When editing Makefile, tabs are not converted to spaces automatically.
When editing other files, tabs are converted to spaces automatically.

**Observed behavior:**
The editor does not care what kind of file is currently being edited, it just converts all tabs to spaces (assuming "expand tabs" is currently selected in menu).

**Che version:**    5.0.0-M7
**OS and version:** Debian Jessie
**Docker version:** 1.12.2
**Che install:**    Docker container

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
