### ISSUE TITLE
Refresh page on user subsequent clicks on the appropriate menu item

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#3160]
When user clicks on the navbar menu item - the page is loaded. But the next click on the selected menu - does nothing, need to do the page refresh - for user to have more actual data displayed. Cause now user has to select another item and then get back to the needed one.

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/3518/commits/58795bb6b35ea0193136c9bc21a9263f04b06187

**Comment by ghost** [comment]
Cannot be reproduced with 5.15-SNAPSHOT
