### ISSUE TITLE
Allow admin to configure additional Docker run command line options in che.env

### ISSUE THREAD

**Issue by agnesagnes** [eclipse-che/che#3161]
Hello,

Some flags cannot be set up in che.properties when running a che workspace (docker run [flags]...). It is the case with --cap-add (in my case I would like to add the NET_ADMIN capacity). 
We can set the --privileged flag, but it is too much. Do you plan to give the possibility to add cap-add in che.properties? I see that we can already set it directly in MachineProviderImpl thanks to withCapAdd(new String[] {"NET_ADMIN"}) but I don't want to change che-plugin-docker-machine.

I don't think there is a way to change the docker run command used when launching a workspace otherwise? (asking in case I missed something)

**Comment by TylerJewell** [comment]
We have talked about this for six months or so.  But we have not made it a priority for implementation.  We feel that there are a couple dozen docker run flags that admins want control over and that they should be configurable in properties and the dashboard, so we see this as an epic which requires a team commitment and sustained engineering effort.

**Comment by TylerJewell** [comment]
Setting this as an enhancement request to be added to platform team backlog.
