### ISSUE TITLE
Add Markdown for Handlebars

### ISSUE THREAD

**Issue by ConProgramming** [eclipse-che/che#3168]
So, I use .hbs files ([handlebars](http://handlebarsjs.com/)) in my work, and I just imported my all my files to Eclipse Che. I now notice, though, that Eclipse Che doesn't have markdown for .hbs files.

Are there anyways to fix this, like making Eclipse Che think the .hbs file is a .html file?

Plus, why does Eclipse Che think all of this is wrong? In JetBrains Webstorm it was fine.
![screencapture-40-76-13-157-dashboard-1480005188323](https://cloud.githubusercontent.com/assets/20548516/20605559/95efdf74-b231-11e6-89f8-22823b950218.png)

**Comment by AndrienkoAleksandr** [comment]
Actually, our IDE calculates import js objects in the area one file. That why some part of your code were highlighted by red color. In the future we will implement building js object tree beetween all files in the project including objects from NodeJS libraries.

**Comment by TylerJewell** [comment]
@slemeur - would you be so kind as to link in the right docs about configuring text editor and highlighting patterns.

**Comment by ghost** [comment]
Here are some docs - http://www.eclipse.org/che/docs/plugins/code-editors/index.html

As to errors in the editor, you may click on red bulb and fix it by adding a header in the file (you'll need to reopen the file to see changes).
