### ISSUE TITLE
Properly handle the dimensions of split editors.

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#3171]
An editor part may be hidden when the IDE is closed and then opened in the window with smaller dimensions.

**Reproduction Steps:**

1. Open the IDE and three files with splitting the editor
2. Close the IDE
3. Decrease the window size and open the IDE again
4. See the result

![editors1](https://cloud.githubusercontent.com/assets/1655894/20621938/430a108a-b309-11e6-85a1-dbbea14ccc73.png)

![editors2](https://cloud.githubusercontent.com/assets/1655894/20621948/48927e7a-b309-11e6-81fd-16b87162335b.png)

**Comment by ghost** [comment]
Editors are not responsive to tab size. Checked in 5.15-SNAPSHOT

**Comment by vitaliy-guliy** [comment]
not actual
