### ISSUE TITLE
Is there any way in ehich we can install eclipse che on any virtual machine

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3172]
I have created azure virtual machine with bitnami eclipse che image.
But is there any way in which i will install eclipse che on my virtual machine?

**Comment by TylerJewell** [comment]
https://eclipse-che.readme.io/docs/usage-docker-server

**Comment by nipobhsnro** [comment]
@TylerJewell  but when i am installing docker in virtual machine I am not able to install it since we have to change bios settings for docker installation.
can you please help me with this?

**Comment by TylerJewell** [comment]
That seems like a question for the Docker user group forums.
