### ISSUE TITLE
Workspace does not start from 'Bitnami Codeigniter' stack on dashboard

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3173]
I try to create a template project from stack library 'Bitnami Codeigniter', but the workspace agent does not start.

**Reproduction Steps:**
* Go to 'Dashboard' -> 'Stack library' -> 'Bitnami Codeigniter'.
* Select the template project 'codeigniter' and create it.

**Expected behavior:**
* Should start workspace agent and open IDE. 

**Observed behavior:**
* The workspace agent does not start.

**Che version:**   5.0.0-M8
**OS and version:**  Ubuntu 14.04   
**Docker version:**  1.12 
**Che install:**   Docker container   

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly:  Yes
* See the attachment
![codeignitier_ws](https://cloud.githubusercontent.com/assets/5408906/20622550/17893b9a-b30c-11e6-8415-78218b3a89e9.png)

**Comment by riuvshin** [comment]
@slemeur Hey can you please talk to those guys why they removed that tag?

**Comment by slemeur** [comment]
@riuvshin Could you precise what tag you are thinking about? (also it works on nightly...)

@amrecio: Could you please give a look on this problem?

**Comment by ashumilova** [comment]
Tag is mentioned at the end of the error message - che-3.1.2-r2

**Comment by riuvshin** [comment]
@slemeur you can see it on screenshot

**Comment by slemeur** [comment]
yes the tag is not present on dockerhub indeed.
@amrecio should we change to use another version? `che-3.1.0-r9` ?

**Comment by amrecio** [comment]
According to the screenshot attached to the bug report, the tag seems to be `bitnami/che-codeigniter:che-3.1.0-r2` (not `che-3.1.2-r2`, as mentioned later). However, I can see `che-3.1.0-r2` on Docker Hub ([here](https://hub.docker.com/r/bitnami/che-codeigniter/tags/)) and it also works for me using Docker:
```
$ docker pull bitnami/che-codeigniter:che-3.1.0-r2
che-3.1.0-r2: Pulling from bitnami/che-codeigniter
862a3e9af0ae: Already exists
6498e51874bf: Already exists
...
f7073243f352: Pull complete
Digest: sha256:b2026b5df9ed27ac3090e61f2b28c78159f88a20e9ec11a68396286349645806
Status: Downloaded newer image for bitnami/che-codeigniter:che-3.1.0-r2
```
BTW, the tag `che-3.1.0-r9` is [the correct one for Che 5.0.0](https://github.com/eclipse/che/pull/3051/files#diff-be4e3a94b98c39160862773dcffad022L1764), and it's the one in [master](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L1698). Why is version 5.0.0-M8 trying to use an older tag?

**Comment by riuvshin** [comment]
@slemeur @ashumilova  can you please update tag to `che-3.1.0-r9` ?

**Comment by ashumilova** [comment]
@artaleks9 the tag **bitnami/che-codeigniter:che-3.1.0-r2** works fine on my side on codenvy.io. And also works on nightly with **bitnami/che-codeigniter:che-3.1.0-r9**. So if you cannot reproduce as well, please, close the issue.

**Comment by idexmai** [comment]
Right now the bug is not reproduce.

**Comment by artaleks9** [comment]
Right now the bug is not reproduce.
