### ISSUE TITLE
The editor has wrong behavior after restart workspace

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3175]
There is an opened file in the editor and I perform restart workspace. Then I open another file and in the editor is displayed a content two files.

**Reproduction Steps:**
* Open a file in the editor.
*  Go to 'Workspace' -> 'Stop' and then start workspace.
* Open another file in the editor.

**Expected behavior:**
* Should displayed the content only an one file.

**Observed behavior:**
* In the editor is displayed the content two files.

**Che version:**    5.0.0-M8 
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12
**Che install:**  Docker container  

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* See the attachment
![editor_restart_ws](https://cloud.githubusercontent.com/assets/5408906/20624006/0863e564-b313-11e6-99f3-7e55bac619ba.gif)

**Comment by riuvshin** [comment]
@vparfonov  can you please take a look on that?
