### ISSUE TITLE
Customize and Add more support for code formatter

### ISSUE THREAD

**Issue by michaellee8** [eclipse-che/che#3180]
I entered 2 in Preferences -> IDE -> Editor -> Tabs -> Tab Size, but I found that I still get 4 spaces for an indent level when I used Alt+Shift+L for code formatting, while having 2 spaces when indenting with TAB. **Can I make my code formatter also indent 2 spaces only?**

Also can is the **code formatter support of c/c++** in the plan?

**Comment by michaellee8** [comment]
May I receive an answer on this?

**Comment by vinokurig** [comment]
It's a known bug: https://github.com/eclipse/che/issues/4138

**Comment by slemeur** [comment]
Closing and keeping #4138 for tracking
