### ISSUE TITLE
Request for Lombok plugin

### ISSUE THREAD

**Issue by KakashiMamun** [eclipse-che/che#3185]
There is no lombok plugin. So lombok related methods highlighted as error

**Reproduction Steps:**

1. User Lombok annotation

**Expected behavior:**
Shouldn't be highlighted as error.

**Observed behavior:**

Lombok used classes shows error.

**Che version:**    [5.0.0-M7]     
**Che install:**     Docker container   

**Additional information:**

If anyone explain me about jdt implementation for eclipse che i will try to implement.

**Comment by KakashiMamun** [comment]
https://github.com/KakashiMamun/plugin-lombok

**Comment by TylerJewell** [comment]
Thanks for the link - will you be issuing a pull request that can be tracked?  The pull request will have a complete list of recommended changes, CI components, and doc improvements necessary to become part of the product.

**Comment by KakashiMamun** [comment]
Yes @ tyler. Because lombok is not in che-parent and I used lombok in my plugin dependacy. In my Local I build with -Denforcer.skip=true. but i reckon in codenvy-ci it will fail. so someone should add lombok version 1.16.10 in che-parent. Let me know if you want to do make a PR for that.
