### ISSUE TITLE
Upload files into workspace?

### ISSUE THREAD

**Issue by ne0h** [eclipse-che/che#3194]
Hi,

is ist possible to upload files from the computer into a workspace (imported from git repo)? For example an existing sqlite database for a rails project?
I do not want to add this database to the git repo of course.

Thanks in advance!
Max

**Comment by TylerJewell** [comment]
@slemeur - for you, please.

**Comment by slemeur** [comment]
Hi Maximilian (@ne0h),

There are few ways to achieve that. The obvious way is by using the GUI, in the menu Project:
<img width="158" alt="screen shot 2016-11-29 at 20 55 50" src="https://cloud.githubusercontent.com/assets/1636769/20726525/40ba5afe-b676-11e6-8593-02b9e9136b87.png">


Other ways could be by using ssh and more by using the [CLI](https://eclipse-che.readme.io/docs/che-cli) with the `che mount` capabilities.

The `che mount <ws-name>` command will start a container that bridges your Che workspace with your local file system. This way you can copy the files you need in the synced folder from your computer directly.

You can learn more on the following documentation: https://eclipse-che.readme.io/docs/desktop-ide-mounting#mount-and-sync

**Comment by dimplerohara** [comment]
Most of the eclipse che links like  https://eclipse-che.readme.io/docs/desktop-ide-mounting#mount-and-sync is no more working. Could you please provide the working link for this issue?
