### ISSUE TITLE
No refresh in project explorer

### ISSUE THREAD

**Issue by lgas** [eclipse-che/che#3195]
No refresh happen in project explorer when :
- you rename a resource
- you copy/paste a file/folder
- you create a folder via mkdir cmd

Even when you hit the dedicated button, it s random.

**Che version:**    4.7.0

**Comment by TylerJewell** [comment]
The 5.0 release train has file watchers that auto refresh the tree when file changes in the ws are made.  Please upgrade to one of the milestones.

**Comment by lgas** [comment]
Ok, Thank you
