### ISSUE TITLE
Enhancement - Rename file after moving it.

### ISSUE THREAD

**Issue by lgas** [eclipse-che/che#3196]
When you move a file in a folder where there is already a file called the same, you can choose if you want to rename the file.
In this case, a blank input field appears where you can choose a new name.

It would be nice to have here the old name to modify.

**Comment by AndrienkoAleksandr** [comment]
More detail:
Steps to reproduce:
1. Create folder "SomeFolder" in the projects.
2. Create file with name "Test" in the "SomeFolder".
3. Create file in the another place with the same name "Test".
4. With help context menu (or menu Edit) Cut file "Test" and paste to the folder "SomeFolder".
5. Wait "Error" window.
6. Click "Change name".
Current behavior:
"Enter new Name" window contains empty input for new name.
Enhancement of the behavior:
"Enter new Name" window contains input with old file name.

**Comment by lolo58200** [comment]
no associated commit and still reproducible with 5.18.0 
closed = discarded here ?
thks
