### ISSUE TITLE
Investigate usage  xterm.js instead of  old and unsupported  term.js

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#3210]
For now we are using our own fork of the  https://github.com/chjj/term.js for user interface websocket-terminal.But actually this project is no longer maintained. So we can not get new releases from this project and we need support this script on our own. Original project contains link for a maintained fork https://github.com/sourcelair/xterm.js  This fork uses MIT license and community intensive develops this project. It has such users like: Microsoft Visual Studio Code, SourceLair, ttyd. Community improved xterm.js : code became more structural and readable. They had already 46 releases https://github.com/sourcelair/xterm.js/releases. I think we can investigate usage this client side for our Golang terminal server side instead of old  term.js. We need analyze all pluses and all minuses.

**Comment by AndrienkoAleksandr** [comment]
Result of investigation https://docs.google.com/a/codenvy.com/document/d/18qj976gQ7L7BOE8uCfEfEB7mb4HCVkPjCvHLKGZzquc/edit?usp=sharing

**Comment by garagatyi** [comment]
Really good investigation!

**Comment by vkuznyetsov** [comment]
Created the next issue https://github.com/eclipse/che/issues/3517 on migration to xterm
