### ISSUE TITLE
Restyle input field in dashboard

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#3213]
Input field should be restyled and need to pay attention that error state doesn't cause the shifting of other components.
![label](https://cloud.githubusercontent.com/assets/1611939/20754842/6fac9a8a-b715-11e6-8c5a-a01ecf6a9cbc.png)

**Comment by slemeur** [comment]
Please @akurinnoy find the corresponding CSS values used in the mockup.

*Title (NAME)*  
font-family: OpenSans-Semibold;
font-size: 12px;
color: #949AA2;
letter-spacing: 1.3px;

*Subtitle (Define a name for yo...)*
font-family: OpenSans-Light;
font-size: 11px;
color: #A8A8A8;

*Textfield background*
background: #FFFFFF;
border: 1px solid #CDCDCD;
box-shadow: 0 2px 4px 0 rgba(0,0,0,0.07);
border-radius: 2px;

*Textfield value*
font-family: OpenSans;
font-size: 12px;
color: #949AA2;
