### ISSUE TITLE
Is there any possibility from which we can by pass username and password in eclipse che url?

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3215]
I want to display eclipse che url : http://{ip-addrees}/dashboard in mvc C# but every time when I am loading that url it is giving me a pop up for username and password. So is there any api or any thing from which I can bypass username and password?

can any one please help me with this?

**Comment by TylerJewell** [comment]
The reproduction steps are not clear, so engineers will not be able to help without those steps and possibly animated gif to show it.

**Comment by nipobhsnro** [comment]
Che version :4.5.1 and image: bitnami eclipse che.
please find attached screen shot
![bitnami1](https://cloud.githubusercontent.com/assets/23380460/20756184/b5c256b4-b737-11e6-9a31-f219f6a75d16.PNG)

**Comment by TylerJewell** [comment]
This will not be a Che issue - it's a Bitnami issue with their configuration.  @bmicklea - who is the right person from Bitnami to investigate?

**Comment by bmicklea** [comment]
@nipobhsnro when you started the cloud machine from Bitnami you should have seen a screen that looks like this:

![screen shot 2016-11-30 at 12 40 15 pm](https://cloud.githubusercontent.com/assets/7644938/20763963/44ad471e-b6fa-11e6-9674-13901d782608.png)

In the Credentials section you have your username and password. That should get you in.

**Comment by nipobhsnro** [comment]
@bmicklea I have created virtual machine from azure portal with eclipse che installation.
And I change default password of bitnami using following command:
 sudo htpasswd /opt/bitnami/apps/eclipseche/conf/.htpasswd user

**Comment by bmicklea** [comment]
Ah, I see - you want to avoid the login altogether. As Tyler mentioned that authentication is part of the Bitnami image so we will need someone from Bitnami to explain if it can be turned off or bypassed. Of course if you turn it off then anyone who knew the IP address would be able to access your server.

**Comment by worksamp** [comment]
@bmicklea ya by turning off credentials any one can access it..so i dont want to turn off credentials but is there any api from which we can pass that credentials and open eclipse che url?
In my application i need to open that url but user(which will use that application) would not known the username and password so i need to by pass it using any api

**Comment by bmicklea** [comment]
I don't think so, the API is part of Che but the authentication you're
seeing is from the Apache web server and added by Bitnami to secure Che
when used on a public cloud.

**Comment by TylerJewell** [comment]
Bitnami does not provide an API for their credential management, I believe.  @bmicklea - the API for Che is a different auth mechanism, not the one he is running into.

**Comment by worksamp** [comment]
@bmicklea  and @TylerJewell  so everytime i need to enter that credentials?

**Comment by bmicklea** [comment]
I believe so, but as I said you're really asking about something that Bitnami built and isn't part of Eclipse Che directly so I'm not 100% sure.  I've asked Bitnami to comment.

**Comment by worksamp** [comment]
@bmicklea and @TylerJewell  Thank you so much for your help. I am looking forward from Bitnami.

**Comment by amrecio** [comment]
@worksamp I'm a Bitnami Engineer. As mentioned earlier, Bitnami does not provide an API for credential management. Our Eclipse Che cloud image is configured to use HTTP basic authentication to avoid exposing the application to the Internet in a public cloud provider.

I'm aware this is not the best solution to your issue, but if you want to disable the authentication for your server, you may do so by running the following commands:

```
$ sudo sed -i -e 's/Require valid-user/Require all granted/g' /opt/bitnami/apps/eclipseche/conf/httpd-app.conf
$ sudo /opt/bitnami/ctlscript.sh restart apache
```

An alternative solution would be to include the username and the password in the URL, like this:

```
http://<user>:<password>@example.com/dashboard
```

**Comment by nipobhsnro** [comment]
@bmicklea @TylerJewell @worksamp @amrecio Thanks for your help .
I think its better everytime user will enter username and password any ways by using this http://<user>:<password>@example.com/dashboard user will know the username and password.
