### ISSUE TITLE
Add Clojure Support

### ISSUE THREAD

**Issue by staypufd** [eclipse-che/che#3217]
Add Clojure support to Che

The two other bugs mentioning Cloure got closed referencing each other.  So I'm adding this bug back b/c Clojure support should be added to Che.

Thanks,

Sam Griffith

**Comment by TylerJewell** [comment]
We are only adding in language server support for languages that have had a formal language server created for them. The language server protocol is fairly new and we are hoping that the languages fill out soon.   You can see what has been done in the open source realm here - we are adding 1-2 of these / month.  

There is no Clojure support, so we will wait for the community to get one packaged.  Will close this in the mean time and include this link in the other issues for people who are going through history, and they will not have to scratch their head the way you did.

http://langserver.org/
