### ISSUE TITLE
Not able to load eclipse che Java console app 

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3219]
I have created java console app from stack in eclipse che but getting an error:

Error: Can't load project types: Error
at Object.window.IDE.eventHandlers.initializationFailed (http://XXXXXXX:8080/ide/WS_JAVA_1?uid=712513:39:27)
at Idb (_app-0.js:1781:44)
at Vdb (_app-0.js:1786:380)
at _.Wn (_app-0.js:4291:317)
at eval (_app-0.js:1316:278)

if i would create any other project like .net then it works perfectly only for java i am getting an error.
i have attached screenshot also.
![java_workspace](https://cloud.githubusercontent.com/assets/23380460/20785512/7fe285d4-b7c6-11e6-8e3c-fdfdc30e76c4.PNG)

Any idea?

**Comment by nipobhsnro** [comment]
From localhost:8080 also I am getting same error

**Comment by AndrienkoAleksandr** [comment]
Write please steps to reproduce and version of CHE.

**Comment by nipobhsnro** [comment]
che version: 4.5.1
steps:
1) Create Java workspace from eclipse che stack.
2) Create Java console app from eclipse che stack.
3) Open created project.

**Comment by AndrienkoAleksandr** [comment]
I checked CHE 4.5.1 it works fine. Can you attach logs, please (from /tomcat/logs)? We need more detail. And add info about your OS, please.

**Comment by nipobhsnro** [comment]
please find attached logs

**Comment by nipobhsnro** [comment]
[log1.txt](https://github.com/eclipse/che/files/624433/log1.txt)

**Comment by AndrienkoAleksandr** [comment]
Download please https://install.codenvycorp.com/che/eclipse-che-4.5.1.tar.gz or https://install.codenvycorp.com/che/eclipse-che-4.5.1.zip  unpack it  and try to reproduce your problem on this binaries.

**Comment by nipobhsnro** [comment]
I have installed eclipse che from bitnami stack.
will above link install eclipse che from codenvy?

**Comment by ghost** [comment]
@nipobhsnro since you are running Che remotely, it is necessary to use -r:$IP parameter when you start Tomcat. $IP is IP of the server where you run Che.

Can you share the syntax that you used to start Che?

**Comment by nipobhsnro** [comment]
i am using following command:
docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:5.0.0-latest start
but every time it says "a container running ECLIPSE CHE named 'che server' already exists"
 
actually i m new to eclipse che so can you please tell me how to run -r:$IP ?

**Comment by ghost** [comment]
`docker rm -f che-server`
`export CHE_HOST_IP=$IP`
`docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:5.0.0-latest start`

Execute these commands. Replace $IP with an actual IP.

**Comment by nipobhsnro** [comment]
I used above command but getting an error:

bitnami@VMHireSmartBitnami:~$ docker rm -f che-server
che-server
bitnami@VMHireSmartBitnami:~$ export CHE_HOST_IP=52.175.19.0
bitnami@VMHireSmartBitnami:~$ docker run --rm -t -v /var/run/docker.sock:/var/ru                                                                                        n/docker.sock eclipse/che:5.0.0-latest start
INFO: ECLIPSE CHE: Pulling image eclipse/che-server:5.0.0-latest
5.0.0-latest: Pulling from eclipse/che-server
3690ec4760f9: Already exists
3cfcebaba840: Pull complete
2de6e0dd61f4: Pull complete
Digest: sha256:0c3683650fb4695cd4247a618a329626f31d7af4b0c36ac079c2f82117e401ef
Status: Downloaded newer image for eclipse/che-server:5.0.0-latest

INFO: ECLIPSE CHE: Starting container...
time="2016-12-01T14:45:26Z" level=fatal msg="Error response from daemon: driver                                                                                         failed programming external connectivity on endpoint che-server (999a99de3583ddc                                                                                        e2a91d27d01e59cf1cf99c86926f04edd4300c4350ea6946b): Error starting userland prox                                                                                        y: listen tcp 0.0.0.0:8080: bind: address already in use"

**Comment by ghost** [comment]
You have got a running Che instance. Make sure nothing is listening on 8080 port.

**Comment by nipobhsnro** [comment]
but from localhost:8080 port also i am getting same error for **java project only** for dot net project everything working properly as:
Error: Can't load project types: Error
at Object.window.IDE.eventHandlers.initializationFailed (http://XXXXXXX:8080/ide/WS_JAVA_1?uid=712513:39:27)
at Idb (_app-0.js:1781:44)
at Vdb (_app-0.js:1786:380)
at _.Wn (_app-0.js:4291:317)
at eval (_app-0.js:1316:278)

**Comment by ghost** [comment]
Are you running Che locally or on localhost? I am confused.

Also, can you share screenshot with Chrome dev console opened so that I can check for errors.

**Comment by nipobhsnro** [comment]
i am running che on localhost also on different machine but when i am trying to create any java project from stack(either locally or from different machine) i am getting that error.

I have attached screen shot for console

[console.txt](https://github.com/eclipse/che/files/624946/console.txt)

**Comment by nipobhsnro** [comment]
![capture](https://cloud.githubusercontent.com/assets/23380460/20798874/7855cd04-b806-11e6-9de2-cc4b5d45e396.PNG)
[console1.txt](https://github.com/eclipse/che/files/624947/console1.txt)

**Comment by ghost** [comment]
You need to open ephemeral port range on that VM

**Comment by nipobhsnro** [comment]
i have attached screen shot for the port which i had already opened on VM.
Please let me know do i need to open any other port which i didn't mentioned in screen shot.
![port1](https://cloud.githubusercontent.com/assets/23380460/20801225/2a011b24-b80e-11e6-835b-c83ce76f0bd5.PNG)
![port2](https://cloud.githubusercontent.com/assets/23380460/20801226/2a05cd9a-b80e-11e6-9f70-e171defcdc03.PNG)
![port3](https://cloud.githubusercontent.com/assets/23380460/20801227/2a08a952-b80e-11e6-9577-84ffc5338c27.PNG)
![port4](https://cloud.githubusercontent.com/assets/23380460/20801228/2a0db4ce-b80e-11e6-9800-d558b42a3647.PNG)

**Comment by ghost** [comment]
Still the same error? There must be some security policy that prevents your browser from connecting to this IP over these ports.

**Comment by nipobhsnro** [comment]
yes still getting same error. But i am connection from my personal laptop. 
Also i am getting error for java project only.
is there any port which i need to open particularly for java?

**Comment by AndrienkoAleksandr** [comment]
Try to open port 32844 . Request goes on ip 52.175.19.0 and port 32844. It's from your sreenshort.

**Comment by nipobhsnro** [comment]
I opened port 32844 still getting same error

**Comment by AndrienkoAleksandr** [comment]
Try to download latest bitnami Eclipse CHE image and read this article please http://che-experience.blogspot.com/2016/12/install-eclipse-che-with-help-bitnami.html . Actually you can install Eclipse CHE without virtual machine, but you need install docker and read docs https://eclipse-che.readme.io/docs/installation

**Comment by ghost** [comment]
The screenshot clearly says that your browser cannot reach IP:port

Make sure nothing blocks it in your network.

Is this a publicly available node? Can you run che there and let me try to connect?

**Comment by nipobhsnro** [comment]
@eivantsov yes i checked it nothing is blocking since i am working from open network
you want to connect that url?
@AndrienkoAleksandr  i will try the url which you have mentioned and will let u know

**Comment by nipobhsnro** [comment]
@eivantsov IP level access is enabled  on firewall which include all tcp and udp port(ephemeral port range) but still its giving  error failed to inject Orion editor.

**Comment by AndrienkoAleksandr** [comment]
Attach screenshot with browser logs please.

**Comment by ghost** [comment]
@nipobhsnro it is a 100% network related problem since the server is able to reach workspace agent and vice versa.

If it's ok for you, share your access credentials so that I can try to access the instance (you may email username/pass to me privately).

**Comment by ghost** [comment]
@nipobhsnro I was able to open a workspace.

However, I have noticed that you allocate 1GB RAM for your workspaces. That is not enough for a Java workspace. Try allocating 2GB.

Also, how much RAM does the VM have?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/5337267/21402532/9ca4f6ec-c7c1-11e6-8d53-55de17d40d76.png)

**Comment by nipobhsnro** [comment]
@Eugene Ivantsov: Thanks for your help.
Actually I am creating java workspace with 1 GB.
Will try it by allocating 2GB space for java workspace and will observe the
behavior for some time and will let you know

**Comment by nipobhsnro** [comment]
@Eugene Ivantsov:  Thanks for your help :-)

I am able to load java project by allocating 2 gb space for java workspace.

**Comment by nipobhsnro** [comment]
@Eugene Ivantsov:  I need one more help. Please bear me actually i have
just started using eclipse che.

Asp dot net core project which is mentioned in eclipse che has no unit test
project associated with it.

I tried to import dot core sample project in eclipse che workspace but
project is not going to build.

Can you please help me with dot net unit test project which is supported by
eclipse che enviornment?

Thanks in advance!!!!!

On Thu, Dec 22, 2016 at 8:40 PM, nipobhsnro rosnbhponi <nipobhsnro@gmail.com
> wrote:

> @Eugene Ivantsov:  Thanks for your help :-)
>
> I am able to load java project by allocating 2 gb space for java workspace.
>
> On Thu, Dec 22, 2016 at 10:13 AM, nipobhsnro rosnbhponi <

**Comment by ghost** [comment]
@nipobhsnro can you share logs or screenshots? Share the project and commands you use to run it?

**Comment by nipobhsnro** [comment]
Hi Eugene

I am referring below project urls:
1) https://github.com/IEvangelist/Dnx.Xunit.Testing
2)
https://github.com/dotnet/docs/tree/master/samples/core/getting-started/unit-testing-using-dotnet-test

Log for 2nd project:
A fatal error was encountered. The library 'hostpolicy.dll' required to
execute
the application was not found in
'D:\368735\AspNetCore\unit-testing-using-dotnet
-test\src\PrimeService\bin\Debug\netcoreapp1.0'.

I am using below commands:
1) dotnet restore
2) dotnet build
3) dotnet run

**Comment by ghost** [comment]
> 'D:\368735\AspNetCore\unit-testing-using-dotnet
> -test\src\PrimeService\bin\Debug\netcoreapp1.0'.

Windows path in a Linux workspace? Can you check if you have any hardcoded stuff in your project?

**Comment by nipobhsnro** [comment]
Ops my bad.

Actually I have attached windows log since I am not able to copy logs from
eclipse che terminal

**Comment by ghost** [comment]
oops. It is fixed in current master. You may open chrome dev console and copy text from the div

**Comment by nipobhsnro** [comment]
user@3b8f2522ff04:/projects$ cd SampleApp/src/PrimeService
user@3b8f2522ff04
:/projects/SampleApp/src/PrimeService$ dotnet restore
log  : Writing lock file to disk. Path:
/projects/SampleApp/src/PrimeService/project.lock.json
log  : /projects/SampleApp/src/PrimeService/project.json
log  : Restore completed in 2874ms.
user@3b8f2522ff04
:/projects/SampleApp/src/PrimeService$ dotnet build
Project PrimeService (.NETCoreApp,Version=v1.0) will be compiled
because expected outputs are missing

A fatal error was encountered. The library 'libhostpolicy.so' required
to execute the application was not found in '/projects

**Comment by ghost** [comment]
It looks like the SDK issue. You may want to try installing a newer dotnet version - create a custom stack using this recipe - https://github.com/eclipse/che-dockerfiles/blob/master/recipes/dotnet_core/Dockerfile#L19

Just use a newer version.

You may want to take a look at thread like this one https://github.com/dotnet/cli/issues/5059

**Comment by nipobhsnro** [comment]
Ok..will try it and let you know

**Comment by TylerJewell** [comment]
With the 5 release and the explanation, this should be resolved.  Closing the issue for now.
