### ISSUE TITLE
Git compare fails on huge projects

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#3221]
When try to compare edited file in huge project with original repository version then internal server error will occur. 

**Reproduction Steps:**
1. Create workspace and import Eclipse Che project (configure as maven)
2. Open any java file and change something
3. Use Menu -> Git -> Compare -> Compare with latest repository version

In case of comparison of whole project Git compare window is appeared, but the same error happens when try to compare a file from the list.

**Expected behavior:**
Compare widget is appeared

**Observed behavior:**
Internal server error in events tab

**Che version:**    5.0.0-M8-SNAPSHOT
**OS and version:**  Ubuntu 16.04
**Docker version:** Version: 1.12.3 API version: 1.24
**Che install:**   tomcat server (zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by slemeur** [comment]
Cannot reproduce

**Comment by mmorhun** [comment]
Still actual, but now the same behaviour even on comparison of whole project (no compare widget appears, but errors in logs).
![screenshot from 2017-04-19 09-00-15](https://cloud.githubusercontent.com/assets/15607393/25165345/b2b199e8-24de-11e7-886c-a1ad6d1581e8.png)

**Comment by slemeur** [comment]
Thanks @mmorhun

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT. I have imported Che into a Java workspace, edited one class, hit compare and got an internal server error. I think this should be fixed since the feature is unusable for real life enterprise level projects.

**Comment by mmorhun** [comment]
Fixed
