### ISSUE TITLE
che-sample-plugin-json-ide fails to compile

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3222]
/che/samples/sample-plugin-json/che-sample-plugin-json-ide  fails to compile

mvn clean compile returns

***
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ che-sample-plugin-json-ide ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 20 source files to C:\Users\D067440\che\samples\sample-plugin-json\che-sample-plugin-json-ide\target\classes
C:\Users\D067440\che\samples\sample-plugin-json\che-sample-plugin-json-ide\src\main\java\org\eclipse\che\plugin\jsonexample\ide\editor\SimpleCompletionProposal.java:23: error: SimpleCompletionProposal is not abstract and does not override abstract method getAdditionalProposalInfo(AsyncCallback<Widget>) in CompletionProposal
public class SimpleCompletionProposal implements CompletionProposal {
       ^
C:\Users\D067440\che\samples\sample-plugin-json\che-sample-plugin-json-ide\src\main\java\org\eclipse\che\plugin\jsonexample\ide\editor\SimpleCompletionProposal.java:37: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.993 s
[INFO] Finished at: 2016-12-01T09:58:05+01:00
[INFO] Final Memory: 54M/1323M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project che-sample-plugin-json-ide: Compilation failure -> [Help 1]
***

**Che version:**    5.0.0-latest 
**OS and version:** Microsoft Windows [Version 10.0.10586]
**Docker version:** Docker version 1.12.3, build 6b644ec
**Che install:**  Docker container

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by kaloyan-raev** [comment]
Are you sure you have all the latest changes from master?

It seems you have an outdated version of the SimpleCompletionProposal.java file. Here is the latest version on master: https://github.com/eclipse/che/blob/master/samples/sample-plugin-json/che-sample-plugin-json-ide/src/main/java/org/eclipse/che/plugin/jsonexample/ide/editor/SimpleCompletionProposal.java

You can see that line 23 is a comment and line 37 is an empty line. Thus, my guess it is outdated on your system.

**Comment by aleksei-burlakov** [comment]
Thank you! I did $she.sh update, so I thought that I'm up to date, but I should have made $git pull.
