### ISSUE TITLE
Upload a new version of the PHP Language Server

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#3227]
Please upload the below attachment to https://codenvy.com/update/repository/public/download/org.eclipse.che.ls.php.binaries
Attachment: [php-language-server.tar.gz](https://dl.dropboxusercontent.com/u/74228612/php-language-server.tar.gz)

This is a more stable version of the existing PHP Language Server. No big changes, mostly bugfixing. Completely backward compatible with the current version.

**Comment by tolusha** [comment]
@kaloyan-raev 
Does it require any changes in the code?

**Comment by kaloyan-raev** [comment]
No.

**Comment by tolusha** [comment]
done.

**Comment by kaloyan-raev** [comment]
Thank you!
