### ISSUE TITLE
Toolbar is empty after restart workspace (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3234]
After restart workspace the toolbar panel becomes empty.

**Reproduction Steps:**
* Open a project in the IDE.
* Perform restart the workspace.

**Expected behavior:**
* The icons are present in the toolbar.

**Observed behavior:**
* Toolbar is empty. Need to refresh a browser. 

**Che version:**    5.0.0-M8  
**OS and version:** Ubuntu 14.04   
**Docker version:**  1.12  
**Che install:**   Docker container 

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* See the attachment:
![toolbar_panel](https://cloud.githubusercontent.com/assets/5408906/20793690/f2ee8afa-b7d0-11e6-91cc-b98f0655d8d1.png)

**Comment by TylerJewell** [comment]
I am moving to 5.1.0.  A refresh solves the problem and it is in the next sprint.  But this is not a pre-condition for making the initial GA.

**Comment by artaleks9** [comment]
Right now the bug is not reproduced.
