### ISSUE TITLE
Project may lose selection after opening  a class from external libraries

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3237]
**Reproduction Steps:**

1. Create for example the Spring project form dashboard
2. Open GreetingController class
3. Set cursor to 13:11 position and press F4 key
4. Launch build command

**Expected behavior:**
Project should be built
**Observed behavior:**
Nothing happened

**Che version:**    5.0.0 M-8
**OS and version:** Ubuntu 14.0 TLS
**Docker version:** 1.12
**Che install:**   Docker container

**Comment by ghost** [comment]
Cannot reproduce. Build command formed for me after an eternal class was opened upon pressing F4
