### ISSUE TITLE
Add ability to stop/cancel workspace startup while in progress

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3249]
As a developer I would like to be able to stop/cancel workspace startup once it is in progress if I realize I have mis-selected the workspace. Having to wait for the workspace to complete startup is not ideal.

**For newly created workspaces**
When the starting workspace is cancelled it should be stopped and return to the state it was in before starting.

**For existing workspaces**
When a newly created workspace is cancelled the workspace should be stopped and destroyed.

 - [x]  API cancel workspace start https://github.com/eclipse/che/issues/3742
 - [x]  Allow to cancel workspace start from UI https://github.com/eclipse/che/issues/3743

**Comment by skabashnyuk** [comment]
We have a couple of stages.
1. Build or download image
2. Start containers
3. Start agens
As an option we can cancel workspace startup between stages by canceling future execution. Is this cover your needs @bmicklea ?

**Comment by bmicklea** [comment]
Yes, that works but we'll need to be clear with the user so a message needs
to be shown:

"Cancelling workspace startup, this may take some time."

I would expect most people to cancel pretty soon after starting and I think
step 1 is pretty short so it should be generally responsive.
