### ISSUE TITLE
Extend the Che CLI with http proxy parameters

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#3259]
Extend the Che CLI so that if a user passes in -e HTTP_PROXY, ALL_PROXY, NO_PROXY, HTTPS_PROXY during an init() phase, that these values are automatically placed in the codenvy.env that is generated during initialization.

**Comment by TylerJewell** [comment]
I can take this task after an engineer has setup a proxy environment and has verified what sort of proxy configurations are needed to make che & codenvy work properly in a proxied environment.

**Comment by skabashnyuk** [comment]
ok

**Comment by TylerJewell** [comment]
@skabashnyuk - I think we need to asisgn a co-partner with me on this.  I was not able to get a proxy environment setup today in a place where I could do development.  So it's not easy for me to write the code to test for the values.  However, having said that, I am fairly confident in what code needs to be written.  So if I could pair-program with someone for 2-3 hours, we will either be able to implement a PR or prove that this particular approach will not be possible.

1) in the check_docker() method, we should check to see if the docker daemon has proxy environment variables set for it. This would be running a "docker info" in the CLI container, and then (hopefully) this returns whether the daemon is configured with a proxy or not. If the proxy information is not available then we have a problem.

2) We would then use these values to export the values for the container + scripts at large. We would also then in the init() or config() method, we would update codenvy.env & che.env to set the PROXY_FOR_CODENVY values with the right values.

**Comment by TylerJewell** [comment]
Merged.
