### ISSUE TITLE
Can't create a workspace or anything for that matter with latest eclipse che

### ISSUE THREAD

**Issue by silageman** [eclipse-che/che#3268]
Not working with 64 bit ubuntu server 16:04 i have tested this twice both with fresh installs.
i followed the steps both on docker site and eclipse local install instructions.
I'm accessing the local server by going to the LAN ip address (no gui so cant use localhost) from my laptop and everything looks ok except for the fact that i cannot create a container (workspace) from the web gui, the buttons just don't run. Docker is installed and hello world image runs...

**Reproduction Steps:**

1. install ubuntu server 16.04
2. follow all insctuctions for docker + eclipse che local install
3. cry

**Expected behavior:**
create/delete workspaces

**Observed behavior:**

"create" buttons do nothing.

**Che version:**    5.0.0-latest
**OS and version:** Ubuntu 16.04 64 bit (server) 
**Docker version:** native 1.12.3
**Che install:**    Docker container   

**Additional information:**

Got eclipse che to install and work on my raspberry pi 2 just wanted more power with proper server.
Looks to be exactly what i need (great software) just can't get it working now.

* Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by TylerJewell** [comment]
Hi @silageman - I just spun up a new instance of Ubuntu on digital ocean and che started up perfectly for me.  I did have to set the IP address to the IP address of the node, however.

So it's interesting that it didn't start immediately for you.  Can you attempt to try this alternative CLI to let us know if there are some additional error messages that are being generated for you?  We are about to switch over our docks to use this format - it's a lot simpler.

Please run the "nightly" version.

https://github.com/eclipse/che/tree/master/docs

**Comment by silageman** [comment]
Thanks for the reply @TylerJewell here's what it throws:

unable to find image 'eclipse/che-cli:latest' locally
Pulling repository docker.io/eclipse/che-cli
docker: Tag latest not found in repository docker.io/eclipse/che-cli.

I've no idea whats wrong here, is it possible the docs are not updated on the main site?

**Comment by TylerJewell** [comment]
You need to try the "nightly" version.  eclipse/che-cli:nightly

**Comment by silageman** [comment]
INFO: Welcome to Eclipse Che!
INFO:
INFO: Eclipse Che commands require additional parameters:
INFO:   Mounting 'docker.sock', which let's us access Docker
INFO:
INFO: Syntax:
INFO:   docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock
INFO:                   che/cli start

**Comment by TylerJewell** [comment]
That is running properly - just follow the guided instructions.

**Comment by silageman** [comment]
sorry but i'm lost

i have tried this:

docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che-cli:nightly start

**Comment by TylerJewell** [comment]
Yes it is guided help and will tell you what else to enter to run Che properly.

**Comment by silageman** [comment]
sorry i have a question when i run sudo che info   the host ip is 172.17.0.1 should this not be on the same network as my LAN?

**Comment by TylerJewell** [comment]
The utility should automatically discover the external IP address to bind itself to, but it's not always perfect. You would normally find this out by running 'ifconfig' to get a list of ip addresses on the system.

You would then need to do something like

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /some/path:/che -e CHE_HOST=<ip> eclipse/che-cli:nightly start
