### ISSUE TITLE
Docs reference image eclipse/che-file which doesn't exist

### ISSUE THREAD

**Issue by elonmallin** [eclipse-che/che#3269]
The [docs](https://eclipse-che.readme.io/docs/installation#from-source) are referencing a docker image that doesn't exist: `eclipse/che-file`.

**Comment by TylerJewell** [comment]
It was a typo in the docs.  It should have been eclipse/che-dir.  I updated the docs. Thanks for the catch.

**Comment by elonmallin** [comment]
Okey cool, wasn't sure thought it might should have been `codenvy/che-file` since that exists.
