### ISSUE TITLE
Allow custom font size in Editor

### ISSUE THREAD

**Issue by Sammaye** [eclipse-che/che#3270]
I must say: so far I love Eclipse Che.

There is just one thing that reallllly bugs me right now. The font size is too small for me to easily read my code and so I keep making mistakes.

It would be really nice if you guys allowed for a custom font size in the editor.

**Comment by TylerJewell** [comment]
Hi @Sammaye  - one thing that you can do (which is what we do during presentations) is to use the browser's CTRL-+ option to zoom all of the contents of the browser to be larger or smaller.  It's pretty convenient and covers most of the primary use cases.

We'll look at giving more fine grained control over this in 2017.

**Comment by Sammaye** [comment]
I do that at times but it increases the whole IDE including the actual UI elements making the editor not display what it should (since I still have a cruddy 1080 21" monitor).

Awesome, this would be great for 2017

**Comment by slemeur** [comment]
Will be fixed with #5330

**Comment by batobolg** [comment]
Great, hope  custom font size in any sub editor or other window.

**Comment by karasjoh000** [comment]
I would of used che but this font issue sucks. I CANT read the text!!!!!. Useless IDE.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
