### ISSUE TITLE
Enhancements for workspace create REST service to support additional parameters

### ISSUE THREAD

**Issue by sbryzak** [eclipse-che/che#3283]
It would be useful for the workspace creation REST service to support setting up a new workspace with some additional parameters, such as open files, cursor positions in files, breakpoints, stacktrace info, etc.   This would enable a developer to create a new workspace with the required state for working on an issue or feature request with these additional parameter values being provided by the issue tracking system.

This enhancement would require some changes to org.eclipse.che.api.workspace.server.WorkspaceService (che-core-api-workspace), probably in the org.eclipse.che.api.workspace.shared.dto.ProjectConfigDTO class, and changes in WorkspaceManager to support the extra params.

**Comment by AndrienkoAleksandr** [comment]
@skabashnyuk what do you think about this suggestion?

**Comment by gazarenkov** [comment]
Workspace API supposed to be client behavior agnostic.

I think we have this things (pretty much the same you requested) when call IDE with Factory parameters. Not sure if it is available on Che assembly as well (not Codenvy only) but still - I believe we should not mix client specific with REST API, let's better keep using factory (on top of ws definition) for that.

**Comment by sbryzak** [comment]
Hi @gazarenkov , I've looked at the Factory API already (I believe that you're talking about https://codenvy.readme.io/docs/factories ).  I don't believe this feature is available in Che, also my concern with using Factory is that it is limited by URL length (see http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers ).  The 2000 character limit will easily be exceeded if we are going to be including a list of open files, cursor positions, breakpoints and stacktrace information in the URL.  The only reasonable way I can think of to send all this state is in a REST call which would not be restricted by size limits.

**Comment by TylerJewell** [comment]
Factories have a fixed-length when they are encoded with a hash, such as `http://<hostname>:<port>/f?id=<hash-code>`.  The non-encoded version is one that we have discontinued as it made reading of the URL to complicated.  With encoded factories, a factory has to be first created by the user by submitting their parameters over a REST call, those parameters are saved in a database and associated to a Factory, and then the REST service returns the hash code identifier of the Factory.

A user can then invoke a factory with the ID code and the system will then generate a workspace according to the configuration that was previously saved.  So, in effect, a Factory implements exactly what you are seeking.

**Comment by sbryzak** [comment]
@TylerJewell that sounds very interesting, the way you describe it is exactly what I'm looking for.  Which REST call is used to create the factory? I see mention of configuring using a JSON snippet passed via URL or the command line here - https://codenvy.readme.io/docs/factories#configure, or is the REST call for creating the factory a different thing?  Also, how do we get the factories feature in Che?

**Comment by TylerJewell** [comment]
It does, yes.  In the 5.0.0 version that we are shipping with Che, we have been enhancing the "workspace state" object inside of the "workspace" object which factories embody. The workspace state is a server-side set of properties that define (for the client) what it should configure itself to. It has things like open terminals, open files, which folder in the tree should be open, editor layout, client preferences.  This state object is far from complete, but it's a server-side object that we incrementally enhance.

If you pass a factory object with workspace state within it, then when the workspace is created the client will be passed this state information and told to configure itself that way.

**Comment by TylerJewell** [comment]
I think this thread has moved into other directions, so closing it for now.
