### ISSUE TITLE
maven-server-impl test fails

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3295]
maven-server-impl fails to compile

**Reproduction Steps:**

1. git clone https://github.com/eclipse/che.git
2. cd ~/che/plugins/plugin-maven/maven-server/maven-server-impl
3. mvn clean install

**Expected behavior:**

When I do the same in Windows then it compiles. 

**Observed behavior:**

In Ubuntu 16 it fails to compile.

**Che version:** 5.0.0-latest    
**OS and version:** Ubuntu 16.04.1 LTS 
**Docker version:** 1.12.1, build 23cf638   

**Additional information:**
It outputs:

Tests run: 25, Failures: 1, Errors: 0, Skipped: 20, Time elapsed: 5.307 sec <<< FAILURE! - in TestSuite
setUp(org.eclipse.che.maven.server.ProjectResolverTest)  Time elapsed: 0.234 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:277)
	at org.eclipse.che.maven.server.ProjectResolverTest.setUp(ProjectResolverTest.java:61)

Results :

Failed tests: 
org.eclipse.che.maven.server.ProjectResolverTest.setUp(org.eclipse.che.maven.server.ProjectResolverTest)
  Run 1: ProjectResolverTest.setUp:61 » NullPointer
  Run 2: PASS
  Run 3: PASS
  Run 4: PASS
  Run 5: PASS
  Run 6: PASS
  Run 7: PASS

* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by evidolob** [comment]
Hi, check that you set "M2_HOME" environment variable and it's point to proper local maven distributive.

**Comment by aleksei-burlakov** [comment]
Thank you. It fixed the issue.
