### ISSUE TITLE
Can't resize process window when there is download file in chrome browser

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#3298]
When I have download in progress or already downloaded files I can't resize process window.
See scriinshot

**Reproduction Steps:**

1. Download some files in Chrome browser
2. Start workspace in Che/Codenvy

**Expected behavior:**

Process window in maximized mode can be resized

**Observed behavior:**

Processes window in maximized mode can't be resized

**Che version:**   5.0.0-M7
**OS and version:** Centos 7.2
**Docker version:** 1.11.1
**Che install:**   Codenvy

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: No idea
* Problem can be reliably reproduced, doesn't happen randomly: Yes
![chromedownload-preventresize](https://cloud.githubusercontent.com/assets/1636620/20930154/24299850-bbd5-11e6-8880-72508e58e489.png)

**Comment by svor** [comment]
Can't reproduce for **5.0.0-M9-SNAPSHOT**
