### ISSUE TITLE
Xtext Based Editor Support

### ISSUE THREAD

**Issue by chetanladdha** [eclipse-che/che#3303]
I am trying to implement the Editor for my domain-specific language based on Xtext. I am trying to implement editor features like code assist,hightligher and also extension points to the editor.
As Che has support for LSP and Xtext beta release has Xtext  language server implementation, How I can generate the editor and these feature from given Xtext grammar ? 
Can Che be extended to support Xtext based editor from the Xtext grammar?

Scenario: In my environment from Xtext grammar, we can generate the Xtext DSL editor in Eclipse with editor capabilities like highlighting, code-assist and few editor extensions points. We want to use existing grammar and generate the Che Xtext based Editor. We would be great if you could guide about the compatibility, possible approaches/workaround to achieve this kind of feature with Eclipse Che?

**Comment by TylerJewell** [comment]
Hi @chetanladdha - yes, Xtext is already supported and an xtext language server is possible with Che.  @svenefftinge did the original implementation with us a few months ago and will have more details. Also adding @cdietrich who also has some experience with this.

What I found:
1. There is [this issue](https://github.com/eclipse/che/issues/3127), which has a sample using a Che LS based upon xtext.
2. Adding syntax: https://github.com/eclipse/che/issues/1608#issuecomment-229681552

**Comment by chetanladdha** [comment]
Thanks @TylerJewell  for your attention.

**Comment by chetanladdha** [comment]
@svenefftinge: Kindly let me know if you have any documentation/blog for moving existing Xtext grammar to make it compatible with Xtext LSP. ( I believe latest Xtext 2.11 release will make this transition easily)

Thanks to @cdietrich for the prototype on Xtext based DSL and Che integration at https://github.com/cdietrich/che/tree/xtext2rx.

**Comment by chetanladdha** [comment]
Blog has been created for Xtext and Che integration: https://blogs.itemis.com/en/how-to-get-started-with-xtext-language-servers-and-che?success=true

**Comment by TylerJewell** [comment]
Thank you @svenefftinge @chetanladdha - I have added this to the media page on the Che site, and also created an issue for this to be added to docs.
