### ISSUE TITLE
Create electron client packaging for Windows (exe), Mac (dmg), and Linux (zip / tgz)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#3308]
Create electron client packaging for Windows (exe), Mac (dmg), and Linux (zip / tgz). The electron packagaing should have a nice icon for the product that it represents, provide minimize / maximize, and also have an icon that appears in the system tray when minified.

For start will be something simple without ability connect to remote codenvy host.

**Comment by benoitf** [comment]
FYI https://github.com/dschaefer/eclipse-two

**Comment by ghost** [comment]
@evidolob please and some sort of an onClose hook, so that when the last windows is closed, che server is stopped. There sould be a confirmation popup asking if a user really wants to do so.

**Comment by evidolob** [comment]
The 'dmg' file can be build only on [MacOS](https://github.com/electron-userland/electron-builder/issues/811)
