### ISSUE TITLE
Chefile error: location is undefined in workspace.runtime.image.location

### ISSUE THREAD

**Issue by elonmallin** [eclipse-che/che#3317]
I used the CLI `che dir init` command to get a Chefile and then added this line `workspace.runtime.image.location="node:6"`. But this gives me an error when I run `che dir up`:
```
WARNING: No kernel memory limit support
ERROR: ECLIPSE CHE(dir): Error: Error while parsing the file '/d/Projects/Tests/che-dir/Chefile' at line 3 and column 33. The error is :Cannot set property 'location' of undefined
```

**Reproduction Steps:**

1. Get the [CLI](https://eclipse-che.readme.io/docs/che-getting-started#1-get-the-eclipse-che-cli)
2. Make sure you set the vars like suggested `CHE_DATA=<somedir>` and `CHE_VERSION=nightly`
3. Switch to the [che dir getting started guide](https://eclipse-che.readme.io/docs/getting-started-chedir) and make sure you set `CHE_UTILITY_VERSION=nightly`
4. Go into an empty folder and run `che dir init`.
5. Open the generated "Chefile" and add `workspace.runtime.image.location="node:6"`.
6. Run `che dir up`.

**Expected behavior:**

Start a che server with a workspace that has the node:6 image.

**Observed behavior:**

```
WARNING: No kernel memory limit support
ERROR: ECLIPSE CHE(dir): Error: Error while parsing the file '/d/Projects/Tests/che-dir/Chefile' at line 3 and column 33. The error is :Cannot set property 'location' of undefined
```

**Che version:** nightly?
**OS and version:** Windows 10 Pro   
**Docker version:** 1.12.3 (Native windows version)

**Comment by TylerJewell** [comment]
@benoitf - is this issue still actual?

**Comment by benoitf** [comment]
@TylerJewell yes it is (but priority P2 so not yet handle)

**Comment by benoitf** [comment]
I've checked and it's a doc issue.

Correct setting is workspace.runtime.docker.image="node:6"

**Comment by benoitf** [comment]
Documentation updated
