### ISSUE TITLE
Configure Master & Agent JVMs to Inherit Proxy Settings

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#3319]
In discussing with @riuvshin - it seems that there is some work to be done for Che to operate similar to how Codenvy does with proxy configuration. While today the workspaces inherit a proxy configuration, the JVMs for ws-master and ws-agent do not inherit these values.  We need puppet configurations set up to modify how the JVM starts.

Codenvy's ws-agent starts with proxies passed into the JVM:
https://github.com/codenvy/codenvy/blob/master/dockerfiles/init/modules/codenvy/templates/machine.properties.erb#L89

But Che's ws-agent does not start with any properties passed:
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L41

And in Codenvy's startup JVM for tomcat, there are additional parameters that we specify to have ws-master JVM start with proxy configuration.
https://github.com/codenvy/codenvy/blob/master/dockerfiles/init/modules/codenvy/templates/codenvy.env.erb#L28-L57

This must be done and merged with the nightly eclipse/che-server image before we can merge the CLI improvements which have tools for auto-detecting and auto-setting the proxy values into the che.env.

https://github.com/eclipse/che/pull/3301

**Comment by riuvshin** [comment]
done
