### ISSUE TITLE
artik-ide start and ERROR !!! Error - Docker not installed properly issue

### ISSUE THREAD

**Issue by Connin** [eclipse-che/che#3328]
Hello,
I am trying to follow 
https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started

But it gave me a lot of errors.. 

I got this error message by following this step (Win7 64-bit).
1. Install Docker.
2. Run Docker Quickstart Terminal and run docker run hello-world to verify it works.
3. Install Git for windows
4. Run Window cmd.
5.  window cmd, Type
set PATH=C:\Program Files\Git\bin\;%PATH%
6. Type
@FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i

7.Type
docker run hello-world 
and it works

8. Type
$ docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start

And I got this message. kyle.bae is my username.

C:\Users\kyle.bae>docker run --rm -t -v /var/run/docker.sock:/var/run/docker.soc
k eclipse/che start
INFO: ECLIPSE CHE: Found image eclipse/che-server:latest
INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 5.0.0-M7
INFO: ECLIPSE CHE: Use: http://192.168.99.100:8080
INFO: ECLIPSE CHE: API: http://192.168.99.100:8080/swagger

9. Go to http://192.168.99.100:8080 and I verified that the link let me have Eclipse Che Workspace creation.
10. Type Bash and type those:

mkdir /c/Users/$USERNAME/artik-ide
cd /c/Users/$USERNAME/artik-ide
curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/artik-ide.bat > artik-ide.bat
curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/artik-ide.sh > artik-ide.sh
mkdir /c/Users/$USERNAME/artik-ide/data

Verify all corresponding files are in artik-ide folder.

11. exit bash and type
set PATH=/c/Users/$USERNAME/artik-ide/;%PATH%
set CHE_DATA_FOLDER=/c/Users/%username%/artik-ide/data

12.OK, I think I did all to install ARTIK IDE.
If I type artik-ide start, I got this message.

C:\Users\kyle.bae>set PATH=/c/Users/$USERNAME/artik-ide/;%PATH%

C:\Users\kyle.bae>set CHE_DATA_FOLDER=/c/Users/%username%/artik-ide/data

C:\Users\kyle.bae>artik-ide start
'artik-ide' is not recognized as an internal or external command,
operable program or batch file.

13. If I cd to artik-ide and type artik-ide start, I got this error message.

C:\Users\kyle.bae>cd artik-ide

C:\Users\kyle.bae\artik-ide>artik-ide start
---------------------------------------
ERROR: !!!
ERROR: !!! Error - Docker not installed properly: \nCONTAINER ID        IMAGE
                    COMMAND                  CREATED             STATUS
     PORTS                              NAMES
c9feed3839d1        eclipse/che-server:latest   "/home/user/che/bin/d"   33 minu
tes ago      Up 33 minutes       8000/tcp, 0.0.0.0:8080->8080/tcp   che-server
ERROR: !!!
---------------------------------------

14. It says Docker not installed properly. But When I type docker run hello-world, I got this message.

C:\Users\kyle.bae\artik-ide>docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

It shows my docker install was done without an issue.

Ok. I think I missed something which is very simple stuff for experts.
It is my first experience to use bash cmd, cloud-based IDE, docker, or VM stuffs.
Can you help me to fix the error please? 

**Che version:**    5.0.0-M7  
**OS and version:** Window7  
**Docker version:** 1.12.3 
**Che install:**    docker  

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

Thanks.

**Comment by ghost** [comment]
Duplicate of https://github.com/codenvy/artik-ide/issues/257
