### ISSUE TITLE
Not able to create project

### ISSUE THREAD

**Issue by chetanladdha** [eclipse-che/che#3332]
I have done che setup in windows 7. Workspace gets successfully created but error while creating the project.
I get message `Unable create folder. Item specified as parent is not a folder` while creating folder.

![image](https://cloud.githubusercontent.com/assets/16016268/21129236/621bd58c-c126-11e6-8a84-ee77e337eac8.png)

I was able to run che in past but facing problem now with this error now. 

Envrionment Details:

**Che version:**   eclipse-che-5.0.0-M8-SNAPSHOT
**OS and version:** Windows 7 Professional 
**Docker version:** [Enter your Docker version here `docker version` on CLI]   
**Che install:**     Zip

che info output

> che info
> WARN: Boot2docker for Windows - CHE_DATA set to /c/Users/cpra/.che
> INFO:  ---------------------------------------
> INFO:  -------------   CLI INFO   ------------
> INFO:  ---------------------------------------
> INFO:
> INFO:  ---------  PLATFORM INFO  -------------
> INFO:  CLI DEFAULT PROFILE       = not set
> INFO:  CHE_VERSION               = 5.0.0-latest
> INFO:  CHE_CLI_VERSION           = latest
> INFO:  CHE_UTILITY_VERSION       = nightly
> INFO:  DOCKER_INSTALL_TYPE       = boot2docker
> INFO:  DOCKER_HOST_IP            = 192.168.99.100
> INFO:  IS_NATIVE                 = NO
> INFO:  IS_WINDOWS                = YES
> INFO:  IS_DOCKER_FOR_WINDOWS     = NO
> INFO:  IS_DOCKER_FOR_MAC         = NO
> INFO:  IS_BOOT2DOCKER            = YES
> INFO:  HAS_DOCKER_FOR_WINDOWS_IP = NO
> INFO:  IS_MOBY_VM                = NO
> INFO:  HAS_CHE_ENV_VARIABLES     = NO
> INFO:  HAS_TEMP_CHE_PROPERTIES   = NO
> INFO:  IS_INTERACTIVE            = YES
> INFO:  IS_PSEUDO_TTY             = YES
> INFO:
> INFO: ---------------------------------------
> INFO: ---------   LAUNCHER INFO  ------------
> INFO: ---------------------------------------
> INFO:
> INFO: ---------  PLATFORM INFO  -------------
> INFO: DOCKER_INSTALL_TYPE       = boot2docker
> INFO: DOCKER_HOST_OS            = Boot2Docker 1.12.3 (TCL 7.2); HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
> INFO: DOCKER_HOST_IP            = 192.168.99.100
> INFO: DOCKER_HOST_EXTERNAL_IP   = not set
> INFO: DOCKER_DAEMON_VERSION     = 1.12.3
> INFO:
> INFO:
> INFO: --------- CHE INSTANCE LIST  ----------
> INFO:
> INFO:
> INFO: ----  CURRENT COMMAND LINE OPTIONS  ---
> INFO: CHE_VERSION               = 5.0.0-latest
> INFO: CHE_DATA                  = /c/Users/cpra/.che
> INFO: CHE_CONF                  = not set
> INFO: CHE_ASSEMBLY              = not set
> INFO: CHE_PORT                  = 8080
> INFO: CHE_HOST_IP               = 192.168.99.100
> INFO: CHE_RESTART_POLICY        = no
> INFO: CHE_USER                  = root
> INFO: CHE_LOG_LEVEL             = info
> INFO: CHE_DEBUG_SERVER          = false
> INFO: CHE_DEBUG_SERVER_PORT     = 8000
> INFO: CHE_HOSTNAME              = 192.168.99.100
> INFO: CHE_SERVER_CONTAINER_NAME = che-server
> INFO: CHE_SERVER_IMAGE_NAME     = eclipse/che-server

`

**Additional information:**
 Problem started happening recently, didn't happen in an older version of Che: Not with eclipse-che-5.0.0-M3, I can run with that version now also.

I have tried multiple times on two different machine for doing setup but same error. Any thought ?

**Comment by TylerJewell** [comment]
@benoitf - any chance this is related to the che-server bug discovered yesterday on where projects are written?

**Comment by benoitf** [comment]
@TylerJewell unfornately no, yesterday bug can only happen in "native" mode
here we're with boot2docker

**Comment by TylerJewell** [comment]
Try starting with Che with this command and let us know the output.
https://eclipse-che.readme.io/docs/usage-docker-server

**Comment by chetanladdha** [comment]
Thanks for the help.

It works with docker command but looks like it is not considering  CHE_ASSEMBLY from my local.
`docker run -v /var/run/docker.sock:/var/run/docker.sock  -e CHE_DEBUG_SERVER=true -e CHE_ASSEMBLY=/c/LatestChe/che-xtext2/assembly/assembly-main/target/eclipse-che-5.0.0-M8-SNAPSHOT/eclipse-che-5.0.0-M8-SNAPSHOT// codenvy/che-launcher:nightly start`

Does I am missing anything?

**Comment by benoitf** [comment]
@chetanladdha could you get rid of two extra // at the end of your `CHE_ASSEMBLY` path ?

**Comment by chetanladdha** [comment]
@benoitf : I tried by removing extra // but it's still not working.  Anything missing/wrong ?

**Comment by chetanladdha** [comment]
Currently, I am not able to up che with my local che_assembly. Is this bug with Windows or am I missing anything ?

**Comment by ghost** [comment]
@chetanladdha What if you move your Che binaries to a a user directory - `/c/%USERPROFILE%/LatestChe/`

Only user directory gets mounted into a Virtual Box machine.

**Comment by chetanladdha** [comment]
@eivantsov : I tried by moving to %USERPROFILE% but it didn't work. CHE_ASSEMBLY is getting ignored  Can this be related with https://github.com/eclipse/che/issues/3351? 
Also, project creation error doesn't resolve even if server started with che.bat directly without docker run command. Any thought ?

**Comment by ghost** [comment]
Once started, can you run docker ps, grab id of `che-server` container and run `docker inspect $containerID`?

**Comment by ghost** [comment]
@chetanladdha also, what 's the problem - inability to create a project or use custom Che binaries?

**Comment by chetanladdha** [comment]
Problem has been resolved with latest build. 
Thanks for your help.
