### ISSUE TITLE
CHE_HOST variable is not working as expected

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#3350]
I want to pass CHE_HOST=172.19.20.18 to che cli to be able to use che from remote host. 
Che started successfully. Workspace started but not able to communicate with master.
In che.env variable ```CHE_HOST``` was commented.
**Reproduction Steps:**

1. start che ```docker run -it --rm -e "CHE_HOST=172.19.20.18" -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.che/data:/data -v $HOME/dev/src/codenvy/che:/repo eclipse/che-cli:nightly start```
2. Start workspace

**Expected behavior:**
workspace started
**Observed behavior:**
workspace is not able to start

**Additional information:**

sj@sj-i7:~]$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

**Comment by skabashnyuk** [comment]
After I've edit ```che.env``` and set ```CHE_HOST=172.19.20.18``` workspace started successfully

**Comment by TylerJewell** [comment]
Just to confirm - the Che host is not being written into Che.env when you first do an installation?

**Comment by skabashnyuk** [comment]
NO. CHE_HOST was commented out.

**Comment by TylerJewell** [comment]
Bug confirmed.  It seems that in the refactoring, the ability to assignt this variable was altered.

**Comment by TylerJewell** [comment]
Fixed in https://github.com/eclipse/che/pull/3345.
