### ISSUE TITLE
Question about the "Using che.sh Script" way to start che

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#336]
From the documentation: https://eclipse-che.readme.io/docs/usage-docker#using-chesh-script, it says:

```
START CHE CONTAINER AND CHE SERVER IN IT
./che.sh -i

STOP CHE SERVER WITHOUT KILLING A CONTAINER
./che.sh stop

STOP CHE CONTAINER
./che.sh stop -i -t
```

I'm not quite clear how we can get the `che.sh` shell. Do we have to clone this repo (https://github.com/eclipse/che), and `mvn clean install` it to generate the required `che.sh`?

**Comment by ghost** [comment]
Yes:

`cd assembly`
`mvn clean install`

Or you can use Docker command line syntax

**Comment by freewind** [comment]
Cool, it's successful this time.

I think it will be great to add this information to the doc, since it could not be found from anywhere else. I tried to clone `https://github.com/eclipse/che` and run `mvn clean install` from the root (not `assembly`), it cost very long time and met several issues. But from `assembly` directory it's faster and easier

**Comment by ghost** [comment]
Yes, assembly is Che packaging, while other modules are other parts of Che and require additional tools and software to be built from source.

**Comment by TylerJewell** [comment]
@freewind We talk about building from assembly on these pages:
https://eclipse-che.readme.io/docs/assemblies
https://eclipse-che.readme.io/docs/contribute

**Comment by freewind** [comment]
@TylerJewell Thanks for these links, they did provide useful information. My concern is they are a little bit after the "Usage" pages, maybe we could add a link or tip in the "usage-docker" page?

**Comment by ghost** [comment]
Yes, I'll improve instructions on running Che in Docker using startup script

**Comment by ghost** [comment]
Added instructions to Usage: Docker docs.
