### ISSUE TITLE
REST call fails from GWT view, but works from menu action in Che

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-che/che#3362]
I have an action class that performs a REST call via my client class.  I invoke the action from a menu, and it works perfectly fine.  When I use the Action Manager to retrieve the same action and run it from a view, I get a ServerDisconnectionException.  The stack trace with the exception is not very helpful.

I am attaching the following Java classes to show what I am doing:

NavigatorServiceClientImpl.java - performs the REST calls.
GetPackagesAction.java - Successfully invokes the REST API client and gets a list of web tree nodes from the server
ServiceDevPackageNavigatorViewImpl.java - extends org.eclipse.che.ide.api.parts.base.BaseView.  Invokes the REST API client, but gets ServerDisconnectionException.
ServiceDevGinModule.java - binds ServiceDevServiceTesterView to ServiceDevPackageNavigatorViewImpl

**Che version:**   5.0.0-M6   
**OS and version:** 
Linux usrscp28 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
system     VMware Virtual Platform
bus        440BX Desktop Reference Platform
memory     87KiB BIOS
processor  Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz

**Docker version:** 1.12.1  
API version: 1.24
**Che install:**   Codenvy

This is the first version of Che I have worked with.  I haven't tried this in earlier versions.

Please let me know if you require any additional information.  Thank you

**Comment by ghost** [comment]
@BarryDrez probably you forgot to attach files. Can you please re attach them?

**Comment by BarryDrez** [comment]
[GetPackagesAction.txt](https://github.com/eclipse/che/files/648938/GetPackagesAction.txt)
[NavigatorServiceClientImpl.txt](https://github.com/eclipse/che/files/648937/NavigatorServiceClientImpl.txt)
[ServiceDevGinModule.txt](https://github.com/eclipse/che/files/648935/ServiceDevGinModule.txt)
[ServiceDevPackageNavigatorViewImpl.txt](https://github.com/eclipse/che/files/648936/ServiceDevPackageNavigatorViewImpl.txt)

Apologies.  Please see attached.

**Comment by BarryDrez** [comment]
@eivantsov Do you require any additional info?  Thanks - Barry

**Comment by vparfonov** [comment]
@BarryDrez Hello, I checked your code and as I see the problem may be caused by the moment when you initialize loadPackagesButton in ServiceDevPackageNavigatorViewImpl. Seems like you're trying to perform actions with instances or services that may be not fully initialized yet. Could you please provide the value of `final String url = baseUrl() + SERVERS + '/' + server + PACKAGES;` in `NavigatorServiceClientImpl.getPackagesList` for both cases?

**Comment by BarryDrez** [comment]
@vparfonov The url is http://172.17.0.1:32801/wsagent/ext/navigator/servers/Default/packages.   The port changes each time I create a new workspace (which is to be expected).  This url is the same for both cases.  Thanks

**Comment by BarryDrez** [comment]
@vparfonov, @eivantsov - I am able to debug using Chrome now, and I am seeing a 403 Forbidden from the Http request.  Any idea why this would be?

**Comment by vparfonov** [comment]
Thanks for response. Looks like problem in [this method](https://github.com/codenvy/codenvy/blob/master/wsmaster/codenvy-hosted-machine-authentication-ide/src/main/java/com/codenvy/machine/authentication/ide/MachineAsyncRequestFactory.java#L129). Can you debug it in line 136 and check value of `wsAgentBaseUrl`?

**Comment by BarryDrez** [comment]
Thank you @vparfonov.  I do not have this class in my source base.  I am using Che version 5.0.0-M6.  Am I missing a project?  Just fyi - I can use the url in a REST call from POSTMAN, and it works correctly.

**Comment by vparfonov** [comment]
Very strange if you got in Che 403 Forbidden it should never be. 
Anyway I will continue analyzing your problem

**Comment by BarryDrez** [comment]
@vparfonov Thank you.  If I come across anything new, I will let you know.

**Comment by BarryDrez** [comment]
Is there a step-by-step tutorial or some documentation that describes how to create a custom client for invoking REST services?  Maybe I missed something.

**Comment by TylerJewell** [comment]
@BarryDrez - I think the closest we have on this matter is researcing the Che source code and this documentation page - https://eclipse-che.readme.io/docs/calling-workspace-apis.  It's not a step by step tutorial, but it does cover the basics of the REST APIs.  

Vitalli will also keep investigating this particular issue.

**Comment by BarryDrez** [comment]
Thanks @TylerJewell.

**Comment by BarryDrez** [comment]
This is interesting.  As a test, I added a method to my REST API that returns a String instead of Json.  This works.  So the problem seems to be related to returning Json.  Could it be a problem with a DTO?

**Comment by TylerJewell** [comment]
Interesting question - could be a DTO bug.  @vparfonov ?

**Comment by BarryDrez** [comment]
I just discovered that I can get a single object back in my REST call but not a list.  I tried wrapping my list in an object, but that did not work.

**Comment by BarryDrez** [comment]
I have tracked this down to a problem with header parameters.  I removed the headers from my REST API and hard-coded the values.  Then I removed setting header parameters in my REST Client, and now I can get a list back.  I am still investigating, but please let me know if there are any known issues in this area.  I have only found one REST service class in Che that receives a HeaderParam: org.eclipse.che.api.core.rest.TestService.java - method: checkAuthorization.

**Comment by BarryDrez** [comment]
Attaching my REST service.  This may shed some light.  Please see getPackages.
[NavigatorService.txt](https://github.com/eclipse/che/files/661659/NavigatorService.txt)

**Comment by BarryDrez** [comment]
@vparfonov - I think this is a bug.  I can pass header parameters from POSTMAN, but not from my REST client within che.  When I pass header parameters from my client, I get the 403 error.

**Comment by TylerJewell** [comment]
Labeling a bug and assigning to a dev team for investigation.

**Comment by vparfonov** [comment]
@BarryDrez Hello, is your issue still actual? If yes can you share you code with us we try to solve your problem

**Comment by BarryDrez** [comment]
@vparfonov, I am going to go ahead and close this since it involves a pretty old version of Che.  I will be trying this with a much newer version, and if I still experience the problem, I will open a new ticket.  Thank you.
