### ISSUE TITLE
Can't connect to Che server with debug session 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#3367]
Following [this docs](https://github.com/eclipse/che/tree/master/docs#development-mode) Che server should be available for debugging it torn on DevMode but this is not work.

**Reproduction Steps:**

1. Start Che with this command:
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vetal/che:/data -v /home/vetal/codenvy/projects/che:/repo eclipse/che-cli:nightly start`
2. Try to connect debug session to the host: 172.17.0.1 port: 8000 
**Expected behavior:**
Debug session should be connected 
**Observed behavior:**
Error running Unnamed: Unable to open debugger port (172.17.0.1:8000): java.net.ConnectException "Connection refused"

**Che version:**   5.0.0-M9-SNAPSHOT
**OS and version:** Ubuntu 16.04
**Docker version:** 1.12.3
**Che install:**    Docker container

**Additional information:**

[cli.log](https://github.com/eclipse/che/files/649017/cli.log.txt)

**Comment by riuvshin** [comment]
I did investigation on that  and it seems i've found the issue.
https://github.com/eclipse/che/blob/master/dockerfiles/che/entrypoint.sh#L159 this is never true even in dev mode that is why jpda is not work

locally I did same way as in codenvy https://github.com/codenvy/codenvy/blob/master/dockerfiles/codenvy/entrypoint.sh#L44 here we always use `${JPDA}` and it will be set only in dev mode in env file. so in prod mode it will be just empty.  

I can issue PR with my changes but Im not sure it is a good solution for CHE so @benoitf @TylerJewell  I need your help here I don;t know how to fix that `CHE_DEBUG_SERVER` 
it is expected that it will be automatically set to true if dev mode is ON. After refactorings I don't understand how it works now and where fix should be.

**Comment by TylerJewell** [comment]
Let's solve this immediately after roadmap call.

**Comment by benoitf** [comment]
I've submitted fix https://github.com/eclipse/che/pull/3371

for now as eclipse/che-server image is also used by the launcher we had to use the same setting (CHE_DEBUG_SERVER)

**Comment by benoitf** [comment]
@vparfonov please test with pulling again the cli image
@vparfonov and reopen issue if it's still not working for you

**Comment by vparfonov** [comment]
Confirm works for now
