### ISSUE TITLE
Git history panel is not opened (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3369]
I try to open the git history panel, but it is not opened.

**Reproduction Steps:**
* Open a project with git repository in the IDE.
* Go to 'Git' > 'Show History..' 

**Expected behavior:**
* Should be opened the git history panel

**Observed behavior:**
* Git history panel is not opened.

**Che version:**  5.0.0-M9    
**OS and version:** Ubuntu 14.04   
**Docker version:** 1.12   
**Che install:**   Docker container   

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![git_history_panel](https://cloud.githubusercontent.com/assets/5408906/21144144/3ea1cbda-c152-11e6-92cd-176c304109a9.gif)

**Comment by vitaliy-guliy** [comment]
Spent 1d 4h.
