### ISSUE TITLE
Where is "che-tomcat8-slf4j-logback"?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#337]
https://github.com/eclipse/che/blob/2795099d2b293c97958d823ed0273fec92b4d389/assembly/assembly-machine-server/src/assembly/assembly.xml#L25

```
            <includes>
                <include>org.eclipse.che.lib:che-tomcat8-slf4j-logback</include>
            </includes>
```

Where can I find the `che-tomcat8-slf4j-logback` dependency? I searched through the che codebase, but not found

**Comment by skabashnyuk** [comment]
https://github.com/eclipse/che-lib/tree/master/che-tomcat8-slf4j-logback

**Comment by TylerJewell** [comment]
@freewind. In the docs under the assemblies page, we have added a new section that describes all of our repositories.  It is also in the readme of the Che repo.  We moved our repositories to eclipse last week and this shifted things around.

**Comment by freewind** [comment]
@TylerJewell Thanks, I found it now. It's https://github.com/eclipse/che-lib now :+1:
