### ISSUE TITLE
Permission denied for che-websocket-terminal after building Che on Windows

### ISSUE THREAD

**Issue by bartlomiej-laczkowski** [eclipse-che/che#3374]
After upgrading sources to 5.0.0-M9 and rebuilding Che on Windows I can not start any new workspace as I always get the following error:

![1](https://cloud.githubusercontent.com/assets/9252532/21155181/676a63dc-c171-11e6-8865-d964ff747981.png)

**Reproduction Steps:**

1. Build Che (on Windows) with the use of the latest 5.0.0-M9 sources
2. Run Che and try to create any new workspace with the use of one of "Ready-to-go" stacks

**Expected behavior:**

Workspace should start without a problem :)

**Observed behavior:**

As described at the beginning.

**Che version:** 5.0.0-M9
**OS and version:** Windows 10
**Docker version:** 1.12.3 (I am using Docker for Windows with Hyper-V support, anyway the problem is also the same while using Docker Toolbox)
**Che install:** Local build   

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

After some digging I think that the problem is probably related to new 'exec-agent'. While building 'exec-agent' on Windows all of the 'che-websocket-terminal' files that were built by GO are having 644 permission flags in my particular case. As a workaround I have added `<fileMode>0755</fileMode>` entry in 'assembly.xml' file (first fileSet) from 'exec-agent' and it helped. Anyway I am not sure whether it is more related to my Win setup or it is more general problem.

**Comment by ghost** [comment]
@bartlomiej-laczkowski thanks for a detailed report. @evoevodin will respond soon

**Comment by voievodin** [comment]
Hi @bartlomiej-laczkowski, thank you for such a good report.
I've just fixed it, so you can pull & try it on !

**Comment by bartlomiej-laczkowski** [comment]
@evoevodin 
Thanks! Works like a charm now :)
