### ISSUE TITLE
how do I add local (proprietary) tools to Eclipse Che server installed locally?

### ISSUE THREAD

**Issue by starbuck19** [eclipse-che/che#3377]
Hello,

I've spent some time trying to install/deploy the Che server on a local workstation behind a corporate proxy, and eventually succeeded after some hacks. I am now able to access the Che server at http://127.0.0.1 through Chrome running on the same workstation and navigate the Eclipse Che dashboard, create and run workspaces, create compile and run applications, etc. Unfortunately I cannot access the server from other workstations in the same corporate domain, but that's an issue I'm willing to live with for now (I'm in a time crunch). At this time I'm only interested in the C++ stack.

Here's what I'm trying to do next: I have some proprietary tools built on the same local workstation, and I want to add them to the Che server and make them available to the user through the Che IDE in the browser. So in the same way g++ is available as a command in a workspace built with a C++ stack, I want to add  a folder that contains all these proprietary tools to the Che server, and then be able to  use the tools the same way I'm running g++ in a regular C++-stack based workspace (either in the Che IDE terminal, or as part of a custom-defined command for the IDE).
I have some experience building Docker images with Dockerfiles. For example I've built an image (let's call it ubuntu-test) based on the following Dockerfile (the test_app folder is in the same folder as the Dockerfile):

_FROM ubuntu:16.04
ADD test_app /projects/test_app_

The test_app folder contains a C++ application (source code and binary) that I can then execute from the Docker container running the ubuntu-test image.

What I'd like to do is build upon the Eclipse Che server image the same way I build on the ubuntu:16.04 in the example above. I already tried building a custom Eclipse Che Docker image with the following Dockerfile:  

_FROM eclipse/che-server:5.0.0-latest
ADD test_app /projects/test_app_

Then I built the Docker image: 

_sudo  docker build -t test ._

and run it (the env var is a temp workaround for a problem I was having with the workspace agent failing):

_sudo docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_DOCKER_MACHINE_HOST_EXTERNAL=127.0.0.1 test start_

I can then access the Eclipse Che dashboard and workspaces just as before at http://127.0.0.1, but the test_app folder does not exist under /projects.

Any suggestions on how I can accomplish this?

Thanks in advance for your help!

**Comment by ghost** [comment]
@starbuck19 che-server is a Docker image that runs Che binaries. What you need to do is to create a workspace from C/CPP stack. When in the IDE, upload your local test_app into an empty project.

Please note that when a workspace starts `/projects` is a volume mount from your local file system.

**Comment by starbuck19** [comment]
@eivantsov thank you for your reply. That's not quite what I'm trying to achieve (sorry, I may have given too particular, or simple of an example in my first post); what I want to do is essentially build a custom stack off the C/CPP stack, for example in addition to g++/Git/make/etc that are available for a workspace "instantiated" w/ a C/CPP stack, also pack in a proprietary C++ compiler. I have the proprietary compiler tools installed on the same workstation(and taking up a lot of space) that I have the Che server set up on, how can I make it so that when I instantiate new workspaces while in the IDE, the new workspaces will "see" the proprietary compiler and be able to use it, e.g. instead of compiling the C++ projects with g++, compile with the proprietary compiler? 
That's why I was thinking of modifying the che-server image to add the proprietary tools, although it sounds like that's not the image I'd need to modify.
Could you please elaborate on the volume mount? Would it be possible for me to achieve what I want (short-term) by simply mounting somehow the location of the proprietary tools for all workspaces (existing and to be created) to see?

Thanks very much for your help!

**Comment by TylerJewell** [comment]
You need to build a custom stack, which is powered by a Dockerfile recipe. The Dockerfile will install the software that you need and then make it available so that when the terminal opens you can use those tools, and then hook up commands to use them.

https://eclipse-che.readme.io/docs/stacks

You can have your custom stack recipes (Dockerfiles) inherit from our CPP stack if you'd like, or start by writing a new one from scratch.

**Comment by starbuck19** [comment]
@TylerJewell thanks for the quick reply. I'm more comfortable/w command-line than the GUI at this time, so would you mind giving me some specifics for a Dockerfile, e.g. the name of the image used for the C/C++? Is it code-envy/cpp_gcc? I'm thinking something like this for the Dockerfile:

_FROM "standard C/CPP stack image"
ADD "local folder where custom compiler tools reside" /opt/"workspace-visible-folder"_

then build the new stack image:
_sudo docker build -t custom_cpp_stack_image ._

Now how do I get the Eclipse Che deployment pipeline see my new stack image in addition to the standard C/C++ stack image?

Thanks very much for your help!

**Comment by TylerJewell** [comment]
The default stack recipes that we build are here:
https://github.com/eclipse/che-dockerfiles/tree/master/recipes

You can inherit from them if you want.  We document how we build them and push them into dockerhub in the che docs.

You can build new stack images on the command line and then have your custom stack use that FROM.  The link I gave you has the instructions on how to set that up.

**Comment by starbuck19** [comment]
@TylerJewell thanks for the details, I will go try this out and report back on how it went. Thanks for the help :-).

**Comment by starbuck19** [comment]
OKay, I've built a test custom image locally based off of the  cpp_gcc image I have locally as follows:

This is my Dockerfile:

_FROM codenvy/cpp_gcc:latest
ADD test_app /home/user/test_app_

Then built it:

_sudo  docker build -t cpp-stack-test .
Sending build context to Docker daemon 28.67 kB
Step 1 : FROM codenvy/cpp_gcc:latest
 ---> 2ce309da61da
Step 2 : ADD test_app /home/user/test_app
 ---> 936ca209db15
Removing intermediate container f55693fa2f97
Successfully built 936ca209db15_

Then I followed the instructions here: https://eclipse-che.readme.io/docs/stacks, so Dashboard->Add Workspace->Runtime>Custom Stack->Import Custom Stack->Pick Dockerfile option. This is asking for a URL, how do I point it to the cpp-stack-test local image I built?

Thanks very much for  your help!

![eclipse_che_custom_stack](https://cloud.githubusercontent.com/assets/3172886/21198614/d8e66226-c1f4-11e6-92ba-802274cf9f2e.JPG)

**Comment by starbuck19** [comment]
@TylerJewell , I re-read your previous post and I wanted to clarify that I cannot push the local custom stack I've built based on the C/CPP stack to DockerHub since it will contain proprietary tools. I need to be able to load the stack image I've built and stored locally without going through DockerHub. Is that possible? 

Thanks.

**Comment by TylerJewell** [comment]
A couple things:
1) If you have built the image locally and it is in your Docker cache such that you can see it when you type `docker images`, then Che will be able to use it.  If the image is working the way you want it to locally, then when in Che you can just create a custom stack that has two lines the FROM <your-image-name> and the CMD with a non-terminating end to it.  Every stack references a Docker image or Dockerfile, so you can also just use the image name if you have it.

2) You should not put your project code in the image. We volume mount your source code into the image for you after the workspace is created. Your users would get this into the workspace by creating a new project, or importing a project (such as using git).  We will do a git clone and then in the process of setting up the proejct, set the type, and setup our management of that project. We will then be responsible for getting the project source code in / out.  You can see this with our out of the box stacks - you can pick a stack type, and then the templates are the source code.  We clone the source code into the workspace after we have started it.

**Comment by starbuck19** [comment]
@TylerJewell : thanks for your reply. I tried what you suggest in 1. in your prev comment as follows:

Take the local image that I built on top of the _codenvy/cpp_gcc_ image (named _cpp-stack-test_). Below is the output I get from `docker images`:

![docker_images](https://cloud.githubusercontent.com/assets/3172886/21238589/71f12262-c2b8-11e6-9ef3-b410d81241f7.JPG)

Then I tried creating a new workspace with a custom stack as shown in the image below:

![custom_stack](https://cloud.githubusercontent.com/assets/3172886/21238606/89ef1978-c2b8-11e6-9ef4-b39b3d8963bd.JPG)

It fails with the following error:

![custom_stack_fail](https://cloud.githubusercontent.com/assets/3172886/21238633/9deafd2a-c2b8-11e6-905d-9b06a0c4448d.JPG)

It seems it's trying to pull from a remote location instead of pointing to the local _cpp-stack-test_ image. Any suggestions on how I can make it point to that instead?

Thanks very much for your help!

**Comment by ghost** [comment]
@starbuck19 you have got 2 options:

1. Register at hub.docker.com and upload your image there
2. Tell Che to use local images.

`docker build -t yourNamespace/test-cpp-stack`
`docker login`
`docket push`

That's option #1. 

Option #2 implies changing the following property:

https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/codenvy/che.properties#L126

When it's true, Che always looks for an image at DockerHub. You need to set it to false. Once done, you can then use local images and inherit from them in your custom recipes.

Here are some docs on how you can override default che.properties - https://eclipse-che.readme.io/v5.0/docs/configuration#configure-che-using-the-cli

**Comment by TylerJewell** [comment]
Let's change this to a docs issue and have pm update the Che recipes and stacks to talk about this scenario.

**Comment by starbuck19** [comment]
@TylerJewell , unfortunately I cannot use option 1 due to tools that I'm adding to the image being proprietary/legal matters. 
Option 2 is what I am looking for, thank you! I will give it a try and report back on how it went.

Thanks so much for your help!

**Comment by ghost** [comment]
@starbuck19 let me know if you need help with overriding che.properties

**Comment by ghost** [comment]
@starbuck19 

`docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/eugene/Downloads/che:/data eclipse/che-cli:nightly init`

Replace ` /home/eugene/Downloads/che` with your local path.

Once inited, go to `/home/eugene/Downloads/che`, open che.env file and uncomment the following:

`#CHE_DOCKER_ALWAYS__PULL__IMAGE=true`

Save the file. Run:

`docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/eugene/Downloads/che:/data eclipse/che-cli:nightly restart`

**Comment by TylerJewell** [comment]
Closing due to age - ok to reopen - assuming this got resolved.
