### ISSUE TITLE
Electron Client should support upgrades

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#3388]
We would need a way to support upgrades. If a user gets a new version of the .exe installation and already has an electron client installed, how would the upgrade process work?  We should also verify that electron clients can be installed and run in Windows folders with spaces in the names.  We should also test this on Windows 7.

**Comment by TylerJewell** [comment]
There is an open question about "what does it mean to upgrade".  The electron client package would be versioned the same as Eclipse Che. Within that package there would be versioned assets for:
1) Eclipse Che (these assets definitely change)
2) Docker (these assets may or may not change, as we may require a new version)
3) Electron Client (these assets may or may not change, if we update the client)

So the upgrade process would involve:
1) Always replace the existing electron client with a new one without asking.
2) Always replace the existing Docker images for running Che with the new ones.
3) In the case of Docker, when we start Che, if the wrong version of Docker is present, Che fails. So if the end user has upgraded Che but not upgraded the underlying Docker version, then we should be able to detect that from the CLI and output it to the screen.
4) If the upgrade package has a version of Docker in our installer that is *newer* than the currently installed version of Docker, then we should ask users when upgrading the Che install if we can install a newer version of Docker.  If they say yes, we need to stop all Docker images on the system and perform the installation.
