### ISSUE TITLE
Add ability to configure the electron client and how it interacts with the outside world

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#3390]
We need to gracefully help users configure the electron client and how it interacts with the outside world.  The items of configuration that a user may need to configure could be done in a local configuration file, or perhaps as part of the onboarding GUI in a preferences window.  The configuration items include:
  - [ ] CHE_HOST / ARTIK_HOST / CODENVY_HOST
  - [ ] Local Only: CHE_PORT / ARTIK_PORT
  - [ ] Proxy Config: ALL_PROXY, HTTP_PROXY, HTTPS_PROXY, NO_PROXY (test conn to dockerhub)
  - [ ] Config property for stopping client: stop all remote workspaces?  yes / no
  - [ ] Config property for stopping client: stop local che server? yes / no
  - [ ] Default onboarding flow (local, remote)? --- skips onboarding screens

**Comment by TylerJewell** [comment]
There was a question about how must the configuration of the electron client look?  Does it just show the `che.env` file?

The answer is that `che.env` file is intended for admins, and it is not really a good experience for allowing end user developers to edit directly.  Also, the Electron client may also have the user edit fields that are in `che.env`, on their local Windows / Mac system, or in the Docker daemon configuration.

So the electron client needs to provide a simple, consistent UX in the client for editing all of these parameters. And then the electron client is smart enough to update `che.env`, Docker, or other utilities and then restart them.

I think the basic UX for this should be:
a) We should have a menu option that lets configuration take place, and:
b) We should also have a little gear icon in the upper right corner of the initial electron window screen that will also open the configuration screen.

**Comment by vparfonov** [comment]
@TylerJewell 
 - [ ] Config property for stopping client: stop all remote workspaces?  yes / no
 - [ ] Config property for stopping client: stop local che server? yes / no
 - [ ] Default onboarding flow (local, remote)? --- skips onboarding screens

We don't have this properties in che.env file. This is something specific for Electron client only?
