### ISSUE TITLE
Create widget for displaying popover

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#3392]
Need to create widget for displaying advanced filter and also can be used for import project source popup.
The sample: 
![image](https://cloud.githubusercontent.com/assets/1611939/21197149/0d9ac78e-c243-11e6-8eef-173d71a8ba8b.png)

**Comment by olexii4** [comment]
https://github.com/eclipse/che/commit/565cf1ddd823f2a67bf90c3531969cda329702e6

**Comment by olexii4** [comment]
![selection_046](https://cloud.githubusercontent.com/assets/6310786/26450548/a6864ed6-4160-11e7-959c-60b1e10f6dc6.png)
![selection_048](https://cloud.githubusercontent.com/assets/6310786/26450551/a927d128-4160-11e7-8614-618a84f5b597.png)
