### ISSUE TITLE
Formating xml files

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#340]
Can't format xml files such as pom.xml

**Comment by TylerJewell** [comment]
@eivantsov - I think we added this in 4.3 or 4.4.  Can you confirm?  If so we can close this.

**Comment by ddementieva** [comment]
Just checked. Formatting for xml files is not yet implemented.

**Comment by sunix** [comment]
up :)

**Comment by TylerJewell** [comment]
@sunix - closing as we do not have a reasonable expectation to implement near term - please see discussion on policy for backlog management.

**Comment by sunix** [comment]
reopening as part of  https://github.com/eclipse/che/issues/5529

**Comment by vparfonov** [comment]
Propose try do implement it with Language Server support, try to find existed our develop own

**Comment by slemeur** [comment]
Closing - covered with XML Plugin in Che 7
