### ISSUE TITLE
Memory settings on workspaces and VMs

### ISSUE THREAD

**Issue by ceosion** [eclipse-che/che#3401]
With Eclipse Che 5.0.0-latest, it doesn't appear that machines reflect the specified memory settings. This is shown by typing "free" or "grep -i memtotal /proc/meminfo" and the value always returning as ~1GB. This is potentially a serious problem, as it is preventing me from doing things within a workspace that needs more memory than this. (e.g. the JVM will crash during a build of my code when it tries to allocate more memory.)

**Reproduction Steps:**

1. Create a new workspace with any image, and set the memory size to 2GB or greater.
2. Start the workspace.
3. Once the terminal is available, enter "grep -i memtotal /proc/meminfo"

**Expected behavior:**

The expected behavior is that the output of the command given in step 3 should report the value specified as the memory of the machine during workspace configuration.

**Observed behavior:**

The output of the command is always ~1GB which does not reflect the workspace configuration.

**Che version:** Eclipse Che 5.0.0-latest
**OS and version:** Windows 10
**Docker version:** Client: 1.12.2    Server: 1.12.3 
**Che install:** Docker container 

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by ceosion** [comment]
It's worth noting that on Codenvy, when I repeat the steps given above, I do in fact see the correct value reported by /proc/meminfo.

**Comment by TylerJewell** [comment]
Thanks @ceosion.  I think we'll ask @ashumilova or @vparfonov to take a look in the next sprint. This is odd because Codenvy is just an implementation of Eclipse Che and I don't think that the memory management module is different between Che & Codenvy.

**Comment by ceosion** [comment]
Great! I'm sure you already know this, but it's worth mentioning that the version of Eclipse Che on Codenvy is the 4.x family, not the 5.x.

I've been poking around at this some more over the last hour, and it also seems that the che.workspace.default_memory_mb property is being ignored. I found that property, changed it to 2048 (from stock value of 1024) and it didn't affect my machines in either existing workspaces or in newly created workspaces.

**Comment by TylerJewell** [comment]
Hmm - We release codenvy at the same time we release Che - so it's 5.0.0-M8 right now at codenvy.io.

**Comment by TylerJewell** [comment]
@ceosion - can you share:
1. The command line that you used to run che, and:
2. The configuration that you set?

I will want to give you an alternative approach - launch it natively with docker or a new CLI we are testing to see if maybe the properties are not being applied properly.

**Comment by ceosion** [comment]
Oh. I wonder why I thought Codenvy was running a different version... never mind!

I'm currently using the CLI and running the following command in a Git Bash shell:
```
> winpty che.bat start
```

I've attached my [che.properties.txt](https://github.com/eclipse/che/files/655578/che.properties.txt) file (had to add .txt to it for GitHub). I also have the following env variables set:
```
CHE_CONF=/c/Users/arf41/
CHE_CONF_FOLDER=/c/Users/arf41/
```

I placed my modified che.properties in that path. I know it's picking it up because I was having a workspace startup timing issue, so I was able to raise the value of che.workspace.agent.dev.max_start_time_ms to resolve it.

**Comment by TylerJewell** [comment]
Can you try running Che with this syntax.  Please note that the way that you get your che.properties into the container is a bit different.  But let's verify that the property is really broken.  I suspect that maybe the CLI approach you are using is the problem and not so much Che itself.  This alternative tactic will answer it for us.

https://eclipse-che.readme.io/docs/usage-docker-server

**Comment by ceosion** [comment]
@TylerJewell so I got it running directly with the docker command, and confirmed that in the output it says "Found custom che.properties..." but the machine's RAM is still only ~1GB both in existing workspaces and in a brand new workspace.

**Comment by TylerJewell** [comment]
Thanks for doing the test.

**Comment by ashumilova** [comment]
1. Checked on our side the values, that are set in machine's config - the runtime ones, after workspace starting, are completely the same.
2. @garagatyi will comment on command usage to check RAM inside container.

**Comment by garagatyi** [comment]
@ceosion Free and proc are not container aware, so they show whole amount of memory on your host. Probably your docker VM in Docker fro Windows is configured to use 1 GB of RAM. Please check that value.

**Comment by TylerJewell** [comment]
Thanks everyone for analysis.  Let's change this to a docs issue and find where in our docs we should provide this feedback.

**Comment by ceosion** [comment]
Hi everyone, thanks for taking a look. @garagatyi I do see that when I run 'docker stats' that the containers show a limit of ~1GB, but I am unsure how to change this. I tried passing the '-m 2G' as an option when starting the Eclipse Che container, but it didn't change the limit for that container. (And, as one might expect, it didn't change the limit for containers started by Eclipse Che.)

Do you have any insight into how I can solve this problem?

**Comment by garagatyi** [comment]
Change from 1GB to 2 or more here https://docs.docker.com/docker-for-windows/#/advanced

**Comment by ceosion** [comment]
Awesome! I couldn't follow that guide directly, but 'translated' it to working with docker-machine (since I'm running Docker Toolbox because I also need to keep VirtualBox around). Increasing the initially allocated memory to my docker-machine instance seemed to do the trick.

**Comment by bmicklea** [comment]
Closing as issue appears to be resolved.
