### ISSUE TITLE
Web editor plugin with drag and drop

### ISSUE THREAD

**Issue by ganeshkar** [eclipse-che/che#3403]
**Web Editor Plugin with drag and drop**

- Can We have an web editor to edit html in which we will be able to drag and drop new elements in html?

Eclipse desktop IDE provides one web editor but didn't find the same in eclipse che.

**Comment by TylerJewell** [comment]
We'd love for the community to make a contribution like this.  There is also a lot of people who are requesting EMF/GMF enhancements, too.
