### ISSUE TITLE
Support `git push -f`

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#3416]
There have no function equivalent to `git push -f`

**Reproduction Steps:**

1. Select `Git` menu
2. `Remotes...` - `Push...`
3. See dialog.

**Expected behavior:**

Something like the checkbox for specifying 'force push'

**Observed behavior:**

There doesn't have

**Che version:**   5.0.0-M8
**OS and version:** Independent   
**Docker version:** Independent
**Che install:**   Independent

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by slemeur** [comment]
Hi @monaka we are going to address your request in the following specification: https://github.com/eclipse/che/issues/5128 . Your feedbacks will be appreciated

**Comment by monaka** [comment]
@slemeur I see. I close this and will keep tracking #5128.
