### ISSUE TITLE
Unable to create workspace on start

### ISSUE THREAD

**Issue by MSaifAsif** [eclipse-che/che#3417]
Cant create workspace

**Reproduction Steps:**

1. Fetch the setup script `curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > /usr/local/bin/che`
2. Start the instance `che start`
3. The following successful logs come up on the console

```
WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
INFO: ECLIPSE CHE: Pulling image eclipse/che-server:5.0.0-latest
5.0.0-latest: Pulling from eclipse/che-server
3690ec4760f9: Already exists 
7fe36e46c847: Pull complete 
dfadaee9cf2b: Pull complete 
Digest: sha256:c26ae6e678db91c263be66410bdcd4611a455505ed6eea6db74af530f76c04d0
Status: Downloaded newer image for eclipse/che-server:5.0.0-latest

INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 5.0.0-M8
INFO: ECLIPSE CHE: Use: http://172.17.0.1:8080
INFO: ECLIPSE CHE: API: http://172.17.0.1:8080/swagger

```

4. Navigating to `localhost:8080` and creating a new workspace gives the error `Could not start workspace wksp-as0w. Reason: Start of environment default failed. Error: no such id: codenvy/ubuntu_jdk8`. 

**Expected behavior:**

Should create a workspace

**Observed behavior:**

<img width="1423" alt="screen shot 2016-12-18 at 1 44 33 am" src="https://cloud.githubusercontent.com/assets/6280554/21290656/98c8ecf0-c4c3-11e6-8357-aea4ef6f8ccc.png">

**Che version:**    5.0.0-M8   
**OS and version:** Ubuntu 14   
**Docker version:** Docker version 1.12.3, build 6b644ec   
**Che install:**   Docker

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [First time install]
* Problem can be reliably reproduced : [Yes]

**Comment by TylerJewell** [comment]
Hi - can you please try starting the Che server using this alternative
Docker syntax and still see if you have the same issue:
https://eclipse-che.readme.io/docs/usage-docker-server

If you do, then it's a networking configuration issue:
https://eclipse-che.readme.io/docs/networking

Can you try this alternative approach and report back?

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by MSaifAsif** [comment]
Let me give it a try

**Comment by MSaifAsif** [comment]
@TylerJewell Workspace gets created but a different error pops up when I try to run it or create a project inside it . Attaching logs from the docker container

```
2016-11-11 08:50:30,563[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
2016-11-11 08:50:30,563[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38
2016-11-11 08:50:31,027[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/ROOT.war
2016-11-11 08:50:31,944[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/ROOT.war has finished in 918 ms
2016-11-11 08:50:31,966[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/dashboard.war
2016-11-11 08:50:32,146[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/dashboard.war has finished in 180 ms
2016-11-11 08:50:32,147[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/swagger.war
2016-11-11 08:50:32,225[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/swagger.war has finished in 78 ms
2016-11-11 08:50:32,237[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/wsmaster.war
2016-11-11 08:50:47,689[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
2016-11-11 08:50:47,714[ost-startStop-1]  [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.0.3 by Boxfuse
2016-11-11 08:50:47,716[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
2016-11-11 08:50:47,769[ost-startStop-1]  [INFO ] [i.f.CustomSqlMigrationResolver 153]  - Searching for sql scripts in locations [classpath:che-schema]
2016-11-11 08:50:47,792[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 2 migrations (execution time 00:00.024s)
2016-11-11 08:50:47,841[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "PUBLIC": 5.0.0.9.1
2016-11-11 08:50:47,843[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Schema "PUBLIC" is up to date. No migration necessary.
2016-11-11 08:50:50,473[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/wsmaster.war has finished in 18,236 ms
2016-11-11 08:50:50,478[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-8080"]
2016-11-11 08:50:50,486[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 20047 ms
2016-11-11 08:51:17,944[nio-8080-exec-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 884]    - Workspace 'che:wksp-cjys' with id 'workspace42c8yplqc3hnkj1y' created by user 'che'

```

And screenshot of the new error

<img width="1440" alt="screen shot 2016-12-18 at 2 18 53 am" src="https://cloud.githubusercontent.com/assets/6280554/21290797/85d40c38-c4c8-11e6-9839-4696c8a834e9.png">

Additional information : I am running it inside a Ubuntu VM. Verified connectivity with internet, ports and firewall is turned off.

**Comment by TylerJewell** [comment]
If you are running it inside of a VM, there is likely additional
configuration that you need to set on the container so that it can
communicate with the outside world properly.  To give you a sense, this is
the configuration that we put into the standard Vagrantfile which runs Che
as a container:

https://github.com/eclipse/che/blob/master/Vagrantfile#L178

I have to go out for the rest of the night now, but the issues that you are having are due to networking configuration of the Che server, so there is some extra networking configuration you need to do to amke sure that your browser, che server and containers can all reach each other smartly.

**Comment by MSaifAsif** [comment]
Thanks, I'll verify all this stuff soon. Too late here to experiment with different things at the moment. Will get back soon on this one.

**Comment by ghost** [comment]
@MSaifAsif @TylerJewell it does not look like connectivity issues between server and agent.

@MSaifAsif can you run `docker images` in your VM? And then `docker pull codenvy/ubuntu_jdk8`?

**Comment by MSaifAsif** [comment]
@eivantsov Attaching outputs

My docker images on the VM

```
$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED                  SIZE
eclipse/che-launcher       nightly             4076ccb43244        Less than a second ago   22.13 MB
eclipse/che-server         5.0.0-latest        942570307823        Less than a second ago   274 MB
maven                      3.3.9-jdk-8         b2ef69e414f5        25 hours ago             653.1 MB
maven                      latest              b2ef69e414f5        25 hours ago             653.1 MB
gitlab/gitlab-ce           latest              18072fa54f6e        2 days ago               1.221 GB
postgres                   latest              b06da01ac31f        2 days ago               264.7 MB
alpine                     latest              baa5d63471ea        3 weeks ago              4.799 MB
ubuntu                     latest              f753707788c5        4 weeks ago              127.1 MB
appropriate/curl           latest              50106f543547        6 weeks ago              6.126 MB
hello-world                latest              c54a2cc56cbb        4 months ago             1.848 kB
sequenceiq/hadoop-docker   2.7.0               789fa0a3b911        18 months ago            1.76 GB
sesteva/grunt-angular      latest              0b497fc00808        22 months ago            684.3 MB

```

And when I try to pull the `codenvy/ubuntu_jdk8`, I get connection reset

```
$ docker pull codenvy/ubuntu_jdk8
Using default tag: latest
latest: Pulling from codenvy/ubuntu_jdk8

ba76e97bb96c: Pulling fs layer 
4d6181e6b423: Pulling fs layer 
4854897be9ac: Pulling fs layer 
4458f3097eef: Waiting 
9989a8de1a9e: Waiting 
4b45533e1c79: Waiting 
c76ccede9241: Waiting 
e2170fb34a73: Waiting 
f58f9b85968e: Waiting 
396317de0287: Waiting 
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/40/4074bfc5705b11d6d963858f648347b8f73b0491e9d821816008a69c4355831d/data?Expires=1482057258&Signature=Xq0BVPrYTVMPOfthyodcY-kdcmg1tjE8zO6W1tRK1ai40Rj7xN0sTvieJ9ywggPPF~ehOud5xvomubgByMQsbJDhtwxtI9FFhkQ5208kzo70U4q4usexUNiVW9fcYmYcoa197hCDeg9U-dVDzxL2Oyn3HnUpxleWnvDV4oMjbH0_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: read tcp 10.0.2.15:49650->52.85.173.230:443: read: connection reset by peer

```

I verified that I have connectivity in the VM with firewall switched off.

```
$ ping www.google.com
PING www.google.com (172.217.21.228) 56(84) bytes of data.
64 bytes from fra16s13-in-f4.1e100.net (172.217.21.228): icmp_seq=1 ttl=63 time=109 ms
64 bytes from fra16s13-in-f4.1e100.net (172.217.21.228): icmp_seq=2 ttl=63 time=61.0 ms
^C
--- www.google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1004ms
rtt min/avg/max/mdev = 61.016/85.033/109.050/24.017 ms

```

**Comment by UnAfraid** [comment]
I've the same problem.

Turns out if you set CHE_IP=`<external ip>`, CHE_PORT=`<external port>`
```
docker run -p:80:80 \
 --name che \
 --restart always \
 -e CHE_IP=192.168.1.15 \
 -e CHE_PORT=80 \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v /C/tmp:/data \
 -v /C/conf:/conf \
 eclipse/che-server:5.0.0-latest
```
Then you go to `http://192.168.1.15` all works
But if you reverse it with nginx to that url, it won't start workspace for some reason.

**Comment by ghost** [comment]
@MSaifAsif you have got issues with Docker in the first place. Are you behind a proxy?

**Comment by MSaifAsif** [comment]
@eivantsov let me try this on a separate network and see if I can resolve this

**Comment by MSaifAsif** [comment]
I got it working after I manually pulled in the `codenvy/ubuntu_jdk8` docker image. So somehow that image doesn't get pulled in when creating a workspace even though I could pull that image on my own
@eivantsov

**Comment by ghost** [comment]
> I got it working after I manually pulled in the codenvy/ubuntu_jdk8 docker image.

Does it mean that after pulling the image manually you can run Java stack? What happens when you start workspaces from other stacks?

**Comment by MSaifAsif** [comment]
Yes, I pulled in the image of `codenvy/ubuntu_jdk8` manually and then it started to run fine. Tried with another stack (`ubuntu-go`), getting exactly the same error on that as well when I try to do everything from the dashboard.

<img width="1440" alt="screen shot 2016-12-21 at 3 25 30 pm" src="https://cloud.githubusercontent.com/assets/6280554/21392783/cfaf0940-c791-11e6-97ec-fed5f9e15379.png">

**Comment by TylerJewell** [comment]
@eivantsov - are you thinking this is a bug somehow in Che, or possible in Docker's daemon?

**Comment by ghost** [comment]
@MSaifAsif please run the following:

```
sudo service docker stop
sudo rm -rf /var/lib/docker
sudo service docker start
```

Launch Che again.

**Comment by MSaifAsif** [comment]
@eivantsov That did the trick and its working fine now. So I had landed up with a bad image or something?

**Comment by ghost** [comment]
Your Docker was acting up for some reason.
