### ISSUE TITLE
Problem with self hosted gitlab with different ssh port

### ISSUE THREAD

**Issue by divo1** [eclipse-che/che#3421]
Hi all,

I install eclipse/che and working good, but I have problem with self hosted gitlab.
I go to profile/preference/ssh/vcs and generate keys:
git@my.host.pl
git@my.host.pl:3333/
my.host.pl:3333/
http://my.host.pl/
http://my.host.pl:3333

Next I trying import project from git. I paste:
git@my.host.pl:3333/my/repo.git
click import and I getting error:
"java.lang.IllegalStateException: Unable get private ssh key. You can create a new SSH key pair in Profile->Preferences->SSH->Git"

**Expected behavior:**
Import repo from self hosted gitlab

**Observed behavior:**
Prompt with error

**Che version:**    Version :5.0.0-M7
**OS and version:** debian 7
**Docker version:** 1.7
**Che install:**    docker container

* Problem started happening recently, didn't happen in an older version of Che: I don't test it in older versions
* Problem can be reliably reproduced, doesn't happen randomly: I think yes

**Comment by ghost** [comment]
@divo1 there's no need to specify port. Just hostname - my.host.pl

**Comment by ghost** [comment]
@divo1 any update please? Have you need able to generate key?

**Comment by divo1** [comment]
I was try few combinations. Also without port. Not working. 
My gitlab web page is on 80 port, but ssh is on different port: 3333. So without defining port i can't connect to git from menu. 
In console I create ~/.ssh/config and I put here info about server. Now git working from command line (terminal), but not from menu. Big thanks for answer :)

**Comment by ghost** [comment]
@divo1 can you share some details? What is the hostname that you entered when generating a key? What is the URL of your Git repo?

**Comment by divo1** [comment]
Host (that i enter in eclipse):
git@gitlab.my.domain.pl
git@gitlab.my.domain.pl:3333/
gitlab.my.domain.pl:3333
http://gitlab.my.domain.pl/
http://gitlab.my.domain.pl:3333

Url from gitlab: git@gitlab.my.domain.pl:3333/cattaneo/transfer-v2.git

$ cat ~/.ssh/config
Host gitlab.my.domain.pl
  HostName xxx.xxx.xxx.xxx (public IPv4)
  User git
  Port 3333
  IdentityFile ~/.ssh/id_rsa
  IdentitiesOnly yes

Domain: gitlab.my.domain.pl is working from internet, it's public.

From eclipse terminal all working without trouble. I set ~/.ssh/config and push, pull and others. But from menu always want private key.
IMHO eclipse should use ~/.ssh/ folder. Could be much simpler :)

**Comment by ghost** [comment]
@divo1 have you tried generating ssh key for domain `gitlab.my.domain.pl` and then save the public key part in your `gitlab.my.domain.pl` account?

Can you share a screenshot of Profile > Preferences > SSH > VCS? And another screenshot of a public key part being saved in your Git hosting account preferences?

**Comment by divo1** [comment]
Hey :)

Here are screens. I check few times. All keys are in gitlab. I show key with host:
gitlab.my.domain.pl:3333

But other hosts keys are in gitlab too. 

![eclipse che php5 5](https://cloud.githubusercontent.com/assets/740945/21598265/1763d67c-d15a-11e6-9612-24956a0a3eed.png)
![eclipse che ssh keys profile settings gitlab](https://cloud.githubusercontent.com/assets/740945/21598264/17638ba4-d15a-11e6-827e-65c8eeaa091e.png)

**Comment by ghost** [comment]
@divo1 there should not be any port in hostname as you generate your key.

**Comment by eivantsov** [comment]
@divo1 you have port in the ssh url

**Comment by ghost** [comment]
@divo1 I see. Let me play around with self hosted gitlab and ask a few questions. I'll update the issue once I have some news.

**Comment by ghost** [comment]
@divo1 currently, there's no way to tell JGit which SSH port to use.

@TylerJewell do you think we should mark the issue as an enhancement and provide UI to let users define hosts and corresponding ports?

**Comment by TylerJewell** [comment]
Yes - I think it actually is probably a bug because the product cannot connect without this improvement.

**Comment by ghost** [comment]
@TylerJewell then I let you label it accordingly.

**Comment by ghost** [comment]
Having port in the url should do the trick. Closing the issue. Feel free to reopen if the problem is still there.
