### ISSUE TITLE
Configuration reset always

### ISSUE THREAD

**Issue by UnAfraid** [eclipse-che/che#3422]
[Short description of problem here]
Hello,
As title says, my configuration is always reset on start/stop/restart, no matter what i do its always reset to default values.

I tried to stop the che before editing saving and starting again but still same issue its reset.
I tried https://eclipse-che.readme.io/docs/usage-docker-server#section-override-che-internals
Still the same

**Reproduction Steps:**

1. sudo docker exec -it che vi /data/conf/che.properties
2. che restart
3. sudo docker exec -it che cat /data/conf/che.properties

Also tried to edit /home/user/che/conf/che.properties, same issue

**Expected behavior:**

I've expected configuration to be preserved but it wasn't.
Its default again.

I wanted to modify github integration and add some vhost that i've created che.mydomain.ltd
I've nginx which is making reverse proxy of localhost:8080

**Che version:**    5.0.0-latest
**OS and version:** Ubuntu 16.04 within ESXI
**Docker version:** 1.12.5
**Che install:**  docker

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
Hi.  What is the command you use to start che?

If you do not provide an override for the che.properties like here, then it will use the embeddedd properties.
https://eclipse-che.readme.io/docs/usage-docker-server#section-override-che-internals

**Comment by UnAfraid** [comment]
Hello,

I used `che start` to start it, also default docker syntax, nothing worked so far

**Comment by TylerJewell** [comment]
Sorry, that is not enough to help diagnose.  Please see the link that was provided. If you are using the docker syntax, please paste the entire command on the command line and all of the output. The link has specific syntax you must use to override internal properties.

Also, the syntax that you provided in the issue up top is not the syntax that is provided in the docs when running eclipse/che-server and changing the properties. You are mixing different CLI approaches which have different types of configuration.

**Comment by UnAfraid** [comment]
I tried few ways

1. docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -p 8000:8080 eclipse/che start
2. che start

I also created /home/user/.che/plugin-conf/che.properties, with only key/value pairs that i wanted to modify but they did not get included

**Comment by TylerJewell** [comment]
Please use this syntax: https://eclipse-che.readme.io/docs/usage-docker-server#section-override-che-internals

**Comment by UnAfraid** [comment]
```
docker run -p:8080:8080 \
 --name che \
 --restart always \
 -e CHE_IP=10.0.75.4 \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v /C/tmp:/data \
 -v /C/conf:/conf \
 eclipse/che-server:5.0.0-latest
```
Worked for me, created che.properties and after restart my changes were applied, thanks!
