### ISSUE TITLE
Update CI Systems

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#3423]
1. For testing purposes, we need 'latest' tag added to DockerHub for eclipse/che-cli. Have it temporarily point to 5.0.0-M8 until we make formal release.
2. Please have eclipse/che image retagged to point to eclipse/che-cli image.  It currently points to eclipse/che-launcher.
3. After #2 is done, we have to make a temporary update to the eclipse/che-launcher docs on README to use the fully qualified image name, not the short-hand.

**Comment by riuvshin** [comment]
@TylerJewell 1 and 2 done. 
can you please elaborate more what what should I do in 3 it is not clear to me.

btw do we still need che-launcher image?

**Comment by TylerJewell** [comment]
#3 is an action item for me - so you can assign it me.

On your question about `che-launcher`. We should continue to leave the existing images there, but we should not generate new images anymore.  In fact, you should disable the nightly builds for the che-launcher now.

**Comment by TylerJewell** [comment]
#3 is now done.

**Comment by riuvshin** [comment]
@TylerJewell should I close issue?

**Comment by TylerJewell** [comment]
ok
