### ISSUE TITLE
After applying new exec agent some commands may be invalid

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3438]
**Reproduction Steps:**

1. We used only shell commands before the exec agent. But exec agent bash command. In this way many commands that was written early may not work.
It may create many unexpected errors for users of the Codenvy. 
For example: echo -e '123'  > ~/test.txt
**Expected behavior:**
should be created file with content like: **123**
**Observed behavior:**
we have file with content like: ***-e 123***
 
**Che version:**    5.0.0-M9
**OS and version:** Ubuntu 14.0 TLS
**Docker version:** 1.12.1
**Che install:**    Docker container

**Comment by garagatyi** [comment]
Can you specify stack or WS config that was the source of workspace?

**Comment by musienko-maxim** [comment]
Go to the nigtly5 or nigtly server and create workspace from java stack for example.
