### ISSUE TITLE
We have red output after launching tomcat for the Spring project

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3439]
[Short description of problem here]

**Reproduction Steps:**
1. Create Spring project in the CHE from dashboard
2. Go to the IDE and launch tomcat using command
**Expected behavior:**
We should have tomcat log in the command output with gray style
[Describe expected behavior here]
**Observed behavior:**
We have:

![download](https://cloud.githubusercontent.com/assets/1640058/21321279/da85eee0-c61c-11e6-8998-aad8c8b2b24d.png)
**Che version:**    5.0.0-M9
**OS and version:** Ubuntu 14.0 TLS
**Docker version:** 1.12.1
**Che install:**    Docker container
**Additional information:**

**Comment by tolusha** [comment]
It is expected behavior.
By default bare tomcat produces logs into `stderr`.
We can reconfigure logger to producer logs into `stdout`.
@skabashnyuk wdyt?

**Comment by tolusha** [comment]
The the easiest choice is to update commands to redirect stderr to stdout.

**Comment by skabashnyuk** [comment]
AFAIK logback configured for stdout + syslog

**Comment by tolusha** [comment]
We have 2 choices:
* keep as is due to default Tomcat behavior
* redirect stderr to stdout `.../catalina.sh run 2>&1` in command to start tomcat

**Comment by tolusha** [comment]
@TylerJewell 
I need you decision

**Comment by TylerJewell** [comment]
If you redirect stderr to stdout is it no longer red?  If yes then do this

**Comment by tolusha** [comment]
It is no longer red.

**Comment by TylerJewell** [comment]
+1

**Comment by ghost** [comment]
I am surprised the command is NOT `./catalina.sh run 2>&1` It has been this way since version 3. So, yes, this is the right and cheap way to go.
