### ISSUE TITLE
Eclipse-che docs typo on Logical Architecture Section

### ISSUE THREAD

**Issue by Fabs** [eclipse-che/che#3440]
There is a small typo on the documentation of che website. 

If this is not the right place to post this bug, please point me to the right place. 

**Reproduction Steps:**

1. Go to https://eclipse-che.readme.io/docs/#logical-architecture
2. In the Logical Architecture section look for the sentence: *The machine is bound **to to** the workspace and to the projects*
3. There are **two** times the word **to** there. 

**Expected behavior:**

To find the sentence:
*The machine is bound **to** the workspace and to the projects*

**Comment by Fabs** [comment]
Oh. Found how to fix it :)

**Comment by bmicklea** [comment]
Hi @Fabs, I think this is fixed now, can you close?

**Comment by Fabs** [comment]
Oh sorry. Yes. its fine.
