### ISSUE TITLE
"Reading Project Structure" popup long and painful

### ISSUE THREAD

**Issue by cifren** [eclipse-che/che#3444]
Hi,

Again thanks for this project, the last update 5.0.0M8 was the best. 

The last thing, in my case, would be to remove or run in bg this "reading project structure" any time we add/remove/rename a file in the Code Editor.

I am not sure if I am in the right Repo to post this issue.

This popup will come everytime and stop the access to the interface for 30 sec each time or more sometimes.

**Reproduction Steps:**

1. Create a project and access the workspace
2. Create a folder

**Expected behavior:**

(If the reading wasn't existing) See my folder appeared and continue to dev

**Observed behavior:**

Stuck for 30+sec, see my folder appeared, stuck for 30sec and come back to dev. And sometimes the tree doesn't even refresh...

**Che version:**    5.0.0M8   
**OS and version:** Boot2Docker + windows 7 
**Docker version:** 1.12.3
**Che install:**    Docker container

* Problem started happening recently, didn't happen in an older version of Che: test
* Problem can be reliably reproduced, doesn't happen randomly: No/Yes

**Comment by TylerJewell** [comment]
Hi - we believe this issue is related or identical to:
https://github.com/eclipse/che/issues/3396

and:
https://github.com/codenvy/codenvy/issues/1249

Both of these issues are must-fixes for the 5.0.0-GA release, which we want to finalize this month.  Going to close and let you cross-track the other issues.

**Comment by cifren** [comment]
It doesn't seem to display the same message (maybe a difference of version) but it could be related.
I don't have the same errors in my console on my side.
![snap 2016-12-20 at 16 22 50](https://cloud.githubusercontent.com/assets/881943/21356058/9b470dcc-c6d0-11e6-8a65-206037ece605.png)

Thank you, my solution has been to give everything to the Boot2Docker (8Go RAM and 2 CPU) !! 
This server runs on Nitro ! (It does not change that much...)
