### ISSUE TITLE
Add Servers section to machine details

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#3456]
There is no ability now to completely configure such part of the machine as servers. So need to add appropriate section to machine's one. User has to be able to set reference to the server, port,protocol and properties.
As the result - the existing workspace details page will show servers info and we will be able to remove Machine Perspective from IDE.

**Comment by gazarenkov** [comment]
It has to replace "Exposed ports" section.

Important to implement before GA, we are not consistent otherwise.
Also customer asked for that.

**Comment by akurinnoy** [comment]
time spent: 5d
