### ISSUE TITLE
workspace rename not working when stopped.

### ISSUE THREAD

**Issue by webmutation** [eclipse-che/che#346]
Trying to rename a stopped workspace. Got the following error message 

Failed undefined

chrome debug 
http://localhost:8080/api/workspace/workspacet5gpubcjl97x4q3w/config Failed to load resource: the server responded with a status of 500 (Internal Server Error)

```
config: Object
data: Object
headers: Object
method: "PUT"
paramSerializer: (e)
transformRequest: Array[1]
0: (e)
length: 1
__proto__: Array[0]
transformResponse: Array[1]
0: xt(e,t)
length: 1
__proto__: Array[0]
url: "/api/workspace/workspacet5gpubcjl97x4q3w/config"
__proto__: Object
data: "This is not a JSON Array."
headers: (n)
status: 500
statusText: "Internal Server Error"

```

rename works if the workspace is running.

**Comment by ghost** [comment]
I have checked with with version RC4-SNAPSHOT and failed to reproduce. What version is in question?

**Comment by benoitf** [comment]
This error has already been fixed https://github.com/eclipse/che/commit/a7b88223afc188013d1cd0457267c37deabb0e83#diff-dc7161be3dbf2250c8954e560cc35060

**Comment by webmutation** [comment]
This was on RC3 the windows install version.

Great i will build my own version.
