### ISSUE TITLE
Unexpected appearance of empty split panel after first starting of workspace

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3460]
**Reproduction Steps:**
Create a workspace, run it and go to the ws.
**Observed behavior:**
![selection_015](https://cloud.githubusercontent.com/assets/1640058/21390762/1dd4040a-c791-11e6-8afa-bec4055a7bc0.png)

**Che version:**   5.0.0-M9
**OS and version:** Ubuntu 14.0
**Docker version:** 1.12.1
**Che install:**    Docker container

**Comment by bmicklea** [comment]
I think we can push this if it's going to take a long time. Roman is discussing with the team.

**Comment by musienko-maxim** [comment]
On current version (549f16ac65c08b8a) has not reproduced.
