### ISSUE TITLE
Provide docs and gifs for the new file watchers

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#3461]
Document all important information related to the new file system watchers configuration and usage, prepare animated GIF files for file content update and for Node.JS project `npm install` command.

**Comment by gazarenkov** [comment]
How we configure watchers for particular Project Type? (this is really powerful feature)

**Comment by vparfonov** [comment]
For now this is not implemented, but possible do it in future

**Comment by vparfonov** [comment]
https://docs.google.com/document/d/1kme_WaxaoXwRYLVMIMQVQutr54w5RZimEMeqT_26T60/edit?ts=588b4cc3
