### ISSUE TITLE
What's the proper way for a workspace `dev-machine` to connect to the docker daemon?

### ISSUE THREAD

**Issue by psharkey** [eclipse-che/che#3462]
**Reproduction Steps:**

1. Start latest che using the following bash snippet run with `che start`
```bash
che() {
     docker run --rm -it \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $HOME/.che:/che \
          eclipse/che "$@"
}
```
2. Create a workspace using `ECLIPSE CHE` stack
3. In the workspace's `dev-machine` terminal run `sudo docker ps -a`

**Expected behavior:**

The dev-machine should be able to connect to the docker daemon and list the current processes.

**Observed behavior:**

`sudo docker ps -a` returns:
"Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

**Che version:**    5.0.0-M8   
**OS and version:** macOS Sierra Version 10.12   
**Docker version:** Docker version 1.13.0-rc3, build 4d92237   
**Che install:**    Docker (using [eclipse/che](https://hub.docker.com/r/eclipse/che/) )

**Additional information:**

Adding `CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock` to  $HOME/.che/che.env (for the above example script) solves the problem. Is there a better way to do this preferably via the `docker run ...` command and using the `-e` flag to set an environment variable? I was unable to get the suggestions in a previous issue (https://github.com/eclipse/che/issues/2309) to work.

* Problem started happening recently, didn't happen in an older version of Che: No (but not certain)
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by garagatyi** [comment]
Docker daemon socket is not mounted into workspaces containers by default. The reason is that it is not secure since access to docker daemon can lead to accessing host machine with sudo privileges. 
So configured Che in a correct way to get docker working inside of workspace.
Changing che.env is appropriate way of configuring Che. Why do you need to specify something else instead of editing che.env?

**Comment by psharkey** [comment]
@garagatyi Thank you for the explanation and editing the che.env is an acceptable solution. I just  wanted to know if there was a different mechanism which should be used instead.

**Comment by TylerJewell** [comment]
That way is the correct way.

There is another way, though - which is you can have your WS recipe inherit from DIND images from Docker, which has docker daemon inside. In this situation you need to activate priviliged mode (also unsecure), but your ws gets its own dedicated daemon ready to go.
