### ISSUE TITLE
Can't expand folder in project explorer

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#3465]
Steps to reproduce:
1. Import project: https://github.com/google/web-starter-kit
2. Run `npm install`
3. Expand `node_modules` folder
4. Enjoy

Expected behavior: `node_modules` is expanded, its content is shown
Actual behavior: `node_modules` is not expdanded

**Comment by JamesDrummond** [comment]
Is this still happening?

**Comment by dkulieshov** [comment]
Seems it's gone, can't reproduce.
