### ISSUE TITLE
Project explorer shows removed folder

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#3466]
Steps to reproduce:
1. Import https://github.com/eclipse/che 
2. Create folder in root folder using terminal
3. Remove the folder using terminal
4. Refresh page
5. Enjoy

Expected behavior: after removal the folder is never shown again
Actual behavior: after removal it is not shown just until page is refreshed and then it is always shown

Branch: https://github.com/eclipse/che/tree/dynamic-fw

**Comment by TylerJewell** [comment]
@dkuleshov - is this still actual?

**Comment by dkulieshov** [comment]
this is actual of CHE 5.14.0
