### ISSUE TITLE
Project explorer synchronize is not optimized

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#3467]
When I add an empty file using terminal I see a loader 'Project structure update` or something similar and that makes me realize that probably project explorer synchronization is not optimally done which may lead to a huge performance issue. 

If I understand correctly there is no real need for project structure update when we just need to synchronize addition of a single empty file. I foresee that will make a lot of problems: for example when we update several files we run project structure update for each one which is ridiculous.

Please correct me if I misunderstood the logic that stands behind project explorer synchronization procedure.

Steps to reproduce:
1. Import https://github.com/eclipse/che
2. Add a file in the root of the project using terminal
3. Enjoy

Expected behavior: update only one file
Actual behavior: update all project structure

Branch: https://github.com/eclipse/che/tree/dynamic-fw

**Comment by TylerJewell** [comment]
Can this particular request be pushed to 5.1.0?  We don't have blocking functionality, just a particular use case wich could be performance optimized.

**Comment by TylerJewell** [comment]
@dkuleshov - relabeling this as a bug, and elevating to a P1 priority.  While performance optimization is an enhancement - the behavir of this particular use case is unexpected, so we can treat that as not performing to specification, and therefore a bug.  Let's consider this for next sprint.

**Comment by JamesDrummond** [comment]
@vitaliy-guliy If this is for your team can you label it with `team/IDE`?

**Comment by vzhukovs** [comment]
Fixed with https://github.com/eclipse/che/commit/6f971301a15aed55725feb10f6f06d3452712ab4

**Comment by dkulieshov** [comment]
@vzhukovskii excellent work
