### ISSUE TITLE
docker API, status: 404, message: Error relabeling upper directory: SELinux

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#3474]
When I was using IDE. Snapshot is run by IDE and got error like this.

```
Snapshot storing failed. org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 404, message: Error relabeling upper directory: SELinux relabeling of /var/lib/docker/overlay/5fef5c37a6e3f1d25105c14ee7f96360faf2867542f7ebbd01842baa1cac7a01/upper is not allowed: "no such file or directory"
```

**Reproduction Steps:**

1. Work on IDE

**Expected behavior:**

I'm not sure but at least should not get error.

**Observed behavior:**

Error like avove.

**Che version:**    5.0.0-M8   
**OS and version:** CoreOS 1185.5.0 (MoreOS)
**Docker version:** 
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64

**Che install:**    Docker container (che-server is on K8s, workspace is on Docker)

**Additional information:**

It may be a specific issue related on CoreOS. Please have a look also #3418.

This issue may not be frequently reproduced. It's a first time to me.
 
* Problem started happening recently, didn't happen in an older version of Che: Yes (to me)
* Problem can be reliably reproduced, doesn't happen randomly: No

**Comment by ghost** [comment]
@monaka can you try disabling SElinux and give it a shot?

**Comment by monaka** [comment]
I googled and I couldn't find out how to disabling SELinux on CoreOS.

The default value on CoreOS is `Permissive`. `Permissive` and `disable` is almost same without logging messages, right?
And the issue seems to be caused randomly. It will be return error always if it is caused by SELinux.

**Comment by ghost** [comment]
@monaka I have replied in https://github.com/eclipse/che/issues/3418

As to this one, I was unable to reproduce.

**Comment by monaka** [comment]
@eivantsov What is the version of your CoreOS?
And where do you deploy your CoreOS instance? (AWS, Azure, or somewhere?)

As I reported before, I deployed my instance on Azure via Azure Portal. Not customized.
I'll re-deploy and retry on my instance. And I want to try on the environment similar to yours, too.

**Comment by ghost** [comment]
@monaka the latest stable version. And I fired up a VM with Digital Ocean.

**Comment by ghost** [comment]
@monaka can you still reproduce this issue?

**Comment by monaka** [comment]
I'm not sure but probably not. (At least it can't reproduce it on my instance now.)
This may be fixed by upgrading Docker in CoreOS. (refs #3418 #3641).
I close this for now. Thank you for your support.
