### ISSUE TITLE
Inject panel in editor at runtime ?

### ISSUE THREAD

**Issue by lgas** [eclipse-che/che#3475]
Hello,
I would like to show a tmp JSON result in the editor view but I want to stylizing display. Like add colors, tables, etc

Is it possible to inject a panel in place of the TextEditorPartViewImpl editorPanel UIField, at runtime ?
Or injecting a new UIBinder for the whole view ?

I tried this, new editor is create but new view is not working :
```
public class ResultViewImpl {

    private static ResultViewImplUiBinder uiBinder = GWT.create(ResultViewImplUiBinder.class);

    @UiField
    SimplePanel editorPanel;
    @UiField
    RichTextArea content;

    private EditorAgent editorAgent;

    @Inject
    public ResultViewImpl(EditorAgent editorAgent) {
        this.editorAgent = editorAgent;
    }

    public void init(String result, String configName) {
        //Add new text editor to EditorPartStack 
        editorAgent.openEditor(new ResultFileImpl(configName, result));
        //Get HTMLPanel from TextEditorPartViewImpl
        Widget panel = ((OrionEditorPresenter)editorAgent.getActiveEditor()).getView().asWidget();
        //Remove childrens and add my simple panel
        Node child = panel.getElement().getChild(0);
        child.removeFromParent();
        child = panel.getElement().getChild(1);
        child.removeFromParent();
        panel.getElement().appendChild(uiBinder.createAndBindUi(this).asWidget().getElement());

        content.setText(result);
    }

    interface ResultViewImplUiBinder extends UiBinder<SimplePanel, ResultViewImpl> {}
}
```
- ResultViewImpl.ui.xml
```
   <g:SimplePanel width="100%" height="100%" addStyleNames="{style.editorZone-layout}">
        <g:SimplePanel ui:field="editorPanel" addStyleNames="{style.editorZone-editor}">
            <g:RichTextArea ui:field="content" />
        </g:SimplePanel>
    </g:SimplePanel>
```
Help would be appreciate.
Thank you.

**Comment by vitaliy-guliy** [comment]
Yes, we do the same in Commands explorer.
Please take a look at the screenshot. A maven command is opened in editor area.

![screenshot](https://cloud.githubusercontent.com/assets/1655894/21429068/d1bfad64-c865-11e6-8ab0-9a40972e442a.png)

You can do the same.

The first you have to implement your `ResultEditor extends AbstractEditorPresenter`, `ResultEditorView` interface and `ResultEditorViewImpl` with UIBinder.

See examples how we do that on the GitHub
https://github.com/eclipse/che/tree/intel_com2/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/editor

As I understand your `ResultFileImpl` implements `rg.eclipse.che.ide.api.resources.VirtualFile`.

See how we do the same in our `CommandFileNode`
https://github.com/eclipse/che/blob/intel_com2/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/node/CommandFileNode.java
and
https://github.com/eclipse/che/blob/260a261e9025424960304063cd846b68ddd296bc/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/CommandApiModule.java#L96-L96

How to register your file type
https://github.com/eclipse/che/blob/4953694dfa1b8ef00e5d56e18df94e57283a5b57/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/core/StandardComponentInitializer.java#L439-L439

**Comment by vitaliy-guliy** [comment]
And also take a look at our documentation
https://eclipse-che.readme.io/docs/code-editors

It could be helpful!

**Comment by lgas** [comment]
Hello Vitaliy,
Thank you for your help. I'm in a good way but still not working and files that you linked me aren't accessible anymore ? Do you know where I can find them still ?

**Comment by TylerJewell** [comment]
@vitaliy-guliy @vparfonov - i was trying to figure out the branch where we are implementing intelligent commands.  It seems that we have moved it from intel_com2.

**Comment by ghost** [comment]
@lgas @TylerJewell  I can see the files.

**Comment by TylerJewell** [comment]
I get 404 not found on the files with intel_com2 branch.

**Comment by ghost** [comment]
@TylerJewell indeed. Looks like this is the branch we're looking for - https://github.com/eclipse/che/tree/icom

**Comment by lgas** [comment]
Great, thank you

**Comment by TylerJewell** [comment]
@lgas - happy new year, hope you are enjoying che.  I am closing this thread as I think we are past the issue and it can be reopened if needed.
