### ISSUE TITLE
Autocomplete not working on nodejs

### ISSUE THREAD

**Issue by patrixsk-ss** [eclipse-che/che#348]
Hi All,

I'm not really sure if it's support yet or not. Is there any plugins for nodejs autocomplete on Eclipse Che ?

Thanks a lot.

**Comment by ghost** [comment]
Eclipse Che uses Orion editor. There's syntax highlighting, code auto completion and error marking for `.js` files.

There's no dedicated plugin for Node.js.

**Comment by patrixsk-ss** [comment]
Thanks. How to enable orion editor on Eclipse che ?

**Comment by ghost** [comment]
It is ON by default.

Can you elaborate on your use case? What happens when you hit Ctrl+Space in a `.js` file?

**Comment by patrixsk-ss** [comment]
Oh it's working now. 

Great Thanks.
