### ISSUE TITLE
Build che docs.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3487]
Need someone to finish up pull request I started. https://github.com/eclipse/che/pull/3473 . The pom.xml needs to be fixed to meet our maven/CI standards. Need to send jar to maven repo for codenvy build to use. 

Maven build requires jekyll 2.5.3

**Comment by skabashnyuk** [comment]
Issue is not clear. Can you define steps what do you want to do?

**Comment by JamesDrummond** [comment]
We are creating a separate repo for docs so this issue will not be done.
