### ISSUE TITLE
Create new docs repo

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3488]
Create new docs repo eclipse/che-docs .

**Comment by bmicklea** [comment]
@slemeur - I think Eclipse has given permission for us to go ahead with this haven't they?

**Comment by slemeur** [comment]
Yes: CQ gets checkin: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12475
Webmaster request to move the docs: https://bugs.eclipse.org/bugs/show_bug.cgi?id=510681
