### ISSUE TITLE
Ask user to save the command modifications on closing editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#3497]
**Reproduction Steps:**

1. Open any command in the editor
2. Do some changes
3. Close editor tab

**Expected behavior:**

User should be asked to save the command modifications.

**Observed behavior:**

![save](https://cloud.githubusercontent.com/assets/1636395/21451498/328e0ae4-c908-11e6-9b57-4d7b7aba974d.gif)

**Additional information:**

* branch [icom](https://github.com/eclipse/che/tree/icom)
* code that must handle such situation is already written [in this method](https://github.com/eclipse/che/blob/icom/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/command/editor/CommandEditor.java#L239) but it seems that some changes have been made in Part API and it broke the invocation of the [PartPresenter#onClose](https://github.com/eclipse/che/blob/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/parts/PartPresenter.java#L106) method.

**Comment by TylerJewell** [comment]
I think having a save button could be poor UX.  We do not ask users to save edits to their code files.  We just auto save them.   Why not the same here?
