### ISSUE TITLE
Add autocomplete for macros in command line and preview URL editors

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#3498]
In addition to already existing macros explorer, need to add autocomplete for macros in command line and preview URL editors.

![macros](https://cloud.githubusercontent.com/assets/1636395/21452400/5202667a-c90f-11e6-9af4-f5f03c7364bc.png)

**Additional information:**

* branch [icom](https://github.com/eclipse/che/tree/icom)

**Comment by slemeur** [comment]
Not replaced. we need to keep it.

But in addition, having autocompletion in the editor of the command would be great.

**Comment by TylerJewell** [comment]
We need different ux so that the command macros link is not cluttering the editor.
