### ISSUE TITLE
Docs maven build

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3510]
We need to build the che docs using jekyll 3.3.1. The following are requirements:

1. Create war file to use in tomcat server running in docker container. Can be used by eclipse/che-server . Building requires jekyll.
2. Need to provide docs to future codenvy docs maven build that requires the che docs source from src/main/ directory.

I created a branch that can be worked from. It is an optional starting point only. Requirements are listed above. 

https://github.com/codenvy/che-docs/tree/build-pom

**Comment by bmicklea** [comment]
related to https://github.com/codenvy/codenvy/issues/1376

**Comment by JamesDrummond** [comment]
@skabashnyuk @vkuznyetsov @riuvshin  I have updated to pom.xml to generate a jar file(target/che-docs-5.0.0-SNAPSHOT-sources.jar) with source files needed by codenvy. We need to get this file into maven repo so we can use it in building codenvy as a dependency/resource. I do not know how this is done. I guess it is a CI step. Once you let me know if the jar is uploaded to repo via CI I can close this issue. If it needs to be done in the pom.xml, we will need to make this change before closing the issue.

https://github.com/codenvy/che-docs/blob/master/pom.xml#L61-L73

**Comment by skabashnyuk** [comment]
@JamesDrummond  can you elaborate why you did this https://github.com/eclipse/che/issues/3510#issuecomment-269238986 and what is the scope of this issue?
So you need to package some folder as artifact to be able to reuse it in codenvy-docs? Lets say zip.
In which faze? What is the corresponding issue in codenvy? Why didn't you merge 
https://github.com/codenvy/che-docs/blob/master/pom.xml#L61-L73 this change?

**Comment by JamesDrummond** [comment]
@skabashnyuk Please see issue I just created for codenvy-docs https://github.com/codenvy/codenvy-docs/issues/11 . I wanted to wait until we got che-docs build working before creating the codenvy-docs issue. I think I got us about 90% there for both codenvy and che. Make sure you have jekyll 3.3.1 and run the following to generate all files needed:

```
cd /tmp/                                                                                                                                                                  
mkdir build-docs                                                                                                                                                          
cd build-docs/                                                                                                                                                            
git clone https://github.com/codenvy/che-docs.git                                                                                                                         
git clone https://github.com/codenvy/codenvy-docs.git                                                                                                                     
cd che-docs/                                                                                                                                                              
mvn clean package                                                                                                                                                         
cd ../codenvy-docs/                                                                                                                                                       
mvn clean package 
```

**Comment by JamesDrummond** [comment]
@skabashnyuk I installed jekyll 3.3.1 using java stack(eclipse/ubuntu_jdk8) in codenvy nightly with the following steps:

git clone https://github.com/codenvy/che-docs.git 
cd che-docs/                                                                                                                                                                     
sudo apt-add-repository ppa:brightbox/ruby-ng                                                                                                                                    
sudo apt-get update                                                                                                                                                              
sudo apt-get install ruby2.2 ruby2.2-dev build-essential                                                                                                                                          
sudo gem install jekyll -v 3.3.1                                                                                                                            
sudo gem install jekyll-feed jekyll-redirect-from jekyll-sitemap                                                                                                                 
mvn clean package

**Comment by JamesDrummond** [comment]
This now works.
