### ISSUE TITLE
persistent URLs

### ISSUE THREAD

**Issue by sukhifive5** [eclipse-che/che#3512]
[it be nice if we can define which port application will be published.  currently random port is assigned.  during development if we building separate stand lone applications which need to talk to each other is causing problem.    ]

**Comment by TylerJewell** [comment]
Please see: https://github.com/eclipse/che/issues/1560.  

This may be something that Red Hat looks to work on for the next many quarters.  It requires complicated internal structures and advanced proxy reconfiguration.  Imagine a world here you have multiple developers with different workspaces who all want to run the same server on the same port, and those workspaces are on the same physical node.  Routing and internal management is needed to address this.

**Comment by TylerJewell** [comment]
Closing this and just going to have everyone track #1560 as the issue for this.
