### ISSUE TITLE
Terminal enhancement by using xterm.js

### ISSUE THREAD

**Issue by Madixin** [eclipse-che/che#3513]
We found che terminal is very hassle to use , because some command output do not show well.
![1](https://cloud.githubusercontent.com/assets/6182588/21448298/fa318e50-c91b-11e6-9dc9-c623eebce54b.png)

Che use term.js for terminal . But it is no longer maintained, and recommended to use xterm.js 
https://github.com/chjj/term.js/
![2](https://cloud.githubusercontent.com/assets/6182588/21448306/28f728f8-c91c-11e6-9ef7-e72c27f321b1.png)

So we try to use "xterm.js" front code to instead of "termjs" , and keep backend terminal servcie che current using.The result is very cool , we want to make sure if it is possible to accepted by che.

![5](https://cloud.githubusercontent.com/assets/6182588/21467396/08f06612-ca27-11e6-8f1d-2d1908874988.png)

Another bug in che5.0 :  Can not support select and copy output in terminal .  
Reproduction Steps:
1. Open Terminal view
2.Select some output
Observed behavior:
It auto unselects the output , and can not copy . I think this problem is caused by terminal tab event.
Che version: 5.0.0-M7 
OS and version: Ubuntu 14.04 LTS
Docker version: 1.12.2
Browser：chrome53 （in winows7）

**Comment by TylerJewell** [comment]
We are three steps ahead of you!  We have completed an investigation and have an integration completed in another branch.  We have more bugs to fix and some more integration to do but we will target this merge in early 2017.

**Comment by TylerJewell** [comment]
Here is the research conclusion.  https://github.com/eclipse/che/issues/3210#issuecomment-268569189

**Comment by Madixin** [comment]
ok, that is cool , wish your new version

**Comment by TylerJewell** [comment]
Closing this as it's now about to be shipped.
