### ISSUE TITLE
Workspace storage location not inherited from server container

### ISSUE THREAD

**Issue by nsymms** [eclipse-che/che#3514]
I'm following the procedure outlined here: https://eclipse-che.readme.io/docs/usage-docker for using docker containers and che-launcher.

I pass CHE_DATA environment variable to che-launcher for host-based workspace storage. My command is this:
docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock \\
        -e CHE_DATA=/my/data/che-data \\
        -e CHE_HOST_IP=10.2.2.2 \\
        eclipse/che-launcher:5.0.0-latest start

The directory structure appears to be created correctly at /my/data/che-data within che-server, and indeed I can see from "docker inspect" a bind for "/my/data/dir:/data:Z" for the server container.

However, when I create a workspace with a demo project, its project storage still goes to /data.
Looking at "docker inspect" for the workspace container, I can see a bind for "/data/workspaces/wksp-zodo:/projects:Z". And of course the projects for that workspace do end up in /data when the workspace is shut down. I would expect them to be stored in /my/data/che-data with the rest of the data.

Evidently the docker volume mapping from server -> workspace is not being made properly.

**Che version:**  5.0.0-latest
**OS and version:** Ubuntu 16.04
**Docker version:** 1.12.1
**Che install:**    Docker container che-launcher 5.0.0-latest

**Comment by TylerJewell** [comment]
Hi:  sorry you are having this problem.  Would you please try this alternative approach and let us know if you experience the same issue?  This is a new cli we have had in development for 6 months designed for a greater level of simplicity.

https://github.com/eclipse/che/tree/master/docs/_docs/setup

**Comment by ghost** [comment]
@nsymms I cannot reproduce. Everything works as expected. I used the same command:

```
eugene@eugene:~$ docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -e CHE_DATA=/my/data/che-data eclipse/che-launcher:5.0.0-latest start
INFO: ECLIPSE CHE: Pulling image eclipse/che-server:5.0.0-latest
5.0.0-latest: Pulling from eclipse/che-server

3690ec4760f9: Already exists 
7fe36e46c847: Already exists 
dfadaee9cf2b: Pull complete 
Digest: sha256:c26ae6e678db91c263be66410bdcd4611a455505ed6eea6db74af530f76c04d0
Status: Downloaded newer image for eclipse/che-server:5.0.0-latest

INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 5.0.0-M8
INFO: ECLIPSE CHE: Use: http://172.17.0.1:8080
INFO: ECLIPSE CHE: API: http://172.17.0.1:8080/swagger
eugene@eugene:~$ cd /my/data/che-data
eugene@eugene:/my/data/che-data$ ls -la
total 32
drwxr-xr-x 8 root root 4096 гру 26 10:06 .
drwxr-xr-x 3 root root 4096 гру 26 10:06 ..
drwxr-xr-x 2 root root 4096 гру 26 10:06 conf
drwxr-xr-x 4 root root 4096 гру 26 10:06 lib
drwxr-xr-x 3 root root 4096 гру 26 10:06 stacks
drwxr-xr-x 3 root root 4096 гру 26 10:06 storage
drwxr-xr-x 2 root root 4096 гру 26 10:06 templates
drwxr-xr-x 2 root root 4096 гру 26 10:06 workspaces
eugene@eugene:/my/data/che-data$ cd workspaces/
eugene@eugene:/my/data/che-data/workspaces$ ls
wksp-fc8q
eugene@eugene:/my/data/che-data/workspaces$ 
```

**Comment by nsymms** [comment]
Thanks @eivantsov for testing this. I've researched this a bit more and discovered that what I am experiencing was reported in issue #3324. The workspace structure is created properly, as you demonstrated, but the workspace container creates projects and files in /data, not in /my/data/che-data.

I believe this has been fixed in PR #3318 which has other changes. I'm trying to find a recent build that I can use to test this. The nightly build is failing because che-server creates the directory structure as root and then launches the workspaces with user 1000, so they can't properly write into the storage area.

**Comment by nsymms** [comment]
I've just tried running everything from scratch with **che-launcher:nightly**. And it all looks great, and lots of other tiny things look better too, like the dashboard ajax updates that were stalling before.

So, I apologize for pointing out an issue that has already been fixed. Can't wait to see all this in the next release.

Che is a fantastic concept and product and I hope to be using it for all my projects in the future.

**Comment by gt945** [comment]
I still can reproduce this issue on centos7 with docker 1.12.6, che 5.17.0

`docker run --rm  -it  -v /var/run/docker.sock:/var/run/docker.sock  -v /media/important/che:/data eclipse/che start`

che info:
INFO: (che cli): 5.17.0 - using docker 1.12.6 / native
WARN: (che cli): 'CHE_HOST=192.168.1.77' is != discovered IP '172.17.0.1'

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che
 Version:        5.17.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /media/important/che
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.17.0
 CHE_HOST:       192.168.1.77
 CHE_INSTANCE:   /media/important/che/instance
 CHE_CONFIG:     /media/important/che
 CHE_BACKUP:     /media/important/che/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   172.17.0.1
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.17.0
 IMAGE_CHE=eclipse/che-server:5.17.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.17.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.17.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.17.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.17.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.17.0
che.env:
 CHE_HOST=192.168.1.77
 CHE_SINGLE_PORT=true


I also check this line:
https://github.com/eclipse/che/blob/f12b4766e4e9672a9698cedd37cac86554d8094e/dockerfiles/che/entrypoint.sh#L328

does it correct? Accroding to https://www.adelton.com/docs/docker/docker-inspect-volumes-mounts#docker-1.8-mounts

It should use new method

**Comment by ghost** [comment]
@nsymms please elaborate on the issue you have. This is a long thread and there were a few problems discussed here.

**Comment by nsymms** [comment]
I don't have any issues with this anymore. My issues were resolved by a PR and other updates. It's @gt945 who's currently having problems.

**Comment by ghost** [comment]
@nsymms sorry, wrong mention :)

@gt945 can you elaborate on the issue you have?

**Comment by gt945** [comment]
@eivantsov OK,
My os is centos7 with docker 1.12.6
I pull eclipse che 5.17 and start eclipse che use this command:
`docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /media/important/che:/data eclipse/che start`
Then I create a PHP workspace and create a project 

After create the project , I find project files are in /data of host, not in  /media/important/che
```
$ tree /data
/data
├── lib
│   └── linux_amd64
│       └── exec
└── workspaces
    ├── diagnostics
    └── PHP
        └── TEST
7 directories, 1 file
```
My question are:

1.  why project files are in /data of host?

2. I also check this line:
https://github.com/eclipse/che/blob/f12b4766e4e9672a9698cedd37cac86554d8094e/dockerfiles/che/entrypoint.sh#L328
does it correct for docker 1.8+ ?

**Comment by ghost** [comment]
@gt945 is it the first time you start Che? Can you try it with `/media/important/che1:/data` volume mount? Also, is this a VM?

**Comment by gt945** [comment]
@eivantsov I tested 5.18 last night, but still have same issue. my centos running on a host pc, not vm

```
rm -rf /media/important/che
docker rm every_che_containers
docker rmi every_che_images
docker pull eclipse/che:5.18.0
docker run --rm  -it  -v /var/run/docker.sock:/var/run/docker.sock  -v /media/important/che:/data   eclipse/che:5.18.0  init
#modify host ip in che.env
docker run --rm  -it  -v /var/run/docker.sock:/var/run/docker.sock  -v /media/important/che:/data   eclipse/che:5.18.0  start
#create a php workspace
```

At last ,I use a workaroud solution: 
```
mount /media/important/che   /data  -o bind
```

By the way, how do you think about my question 2?

**Comment by ghost** [comment]
@gt945 can you replace `-v /media/important/che:/data` with `-v ~/che:/data`? Is `media` a remote volume itself?
