### ISSUE TITLE
Dashboard "Create Workspace" button creates new project, not workspace

### ISSUE THREAD

**Issue by nsymms** [eclipse-che/che#3515]
When the dashboard first comes up, if you have existing workspaces, they are listed. There's also a button above the list titled "Create Workspace". If you click it, you're taken to the "Create Project" page, which attempts to create a project within (the first??) workspace.

I'm not sure if this is by design, but if so, it's not very clear.

The 1-word code change for this would be in the dashboard source, last-workspaces.html line 7. It is clearly calling "create-project" instead of "create-workspace." I could probably submit a pull-request, but I've only done one of those in my life and it didn't work well.

**Che version:** 5.0.0-latest
**OS and version:** Ubuntu 16.04
**Docker version:** 1.12.1
**Che install:** Docker container che-launcher 5.0.0-latest

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [never tried another version]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ghost** [comment]
@nsymms Importing a project is part of workspace creation flow. @slemeur or @ashumilova can elaborate on plans to change it.

**Comment by slemeur** [comment]
Hi @nsymms.

We have two different flows to create workspaces because of historical reasons. 
We previously had a "Project" sections and we saw Che's users mostly interacting from the dashboard with Workspaces and almost never managing the projects from this place. Usually, users manage the workspaces in the dashboard and then projects in the IDE. 

We are currently updating and improving the flow to create a workspace and making the ability to import a project at the same time an option.

To give you an insight, this is the mockup of the future flow - we thinking it'll improve the overall experience.  

![create-workspace](https://cloud.githubusercontent.com/assets/1636769/21478513/64589c60-cb4c-11e6-8917-d50737860161.png)

**Comment by nsymms** [comment]
Thanks for your response, but I think we are looking at different items. I'm looking at the "Recent Workspaces" list as shown in the image below.
![screenshot - 12_26_2016 7_37_19 am](https://cloud.githubusercontent.com/assets/9939843/21482912/d4d78206-cb3f-11e6-8fe6-98f34ab3df17.png)
If I click on the "Create Workspace" button, it doesn't create a new workspace. It adds a project to an existing workspace. If that is what is intended, then at least the button should say "Add Project". If you really want it to create a new workspace, then you should change this the code:
https://github.com/eclipse/che/blob/master/dashboard/src/app/dashboard/last-workspaces/last-workspaces.html#L7
to call "create-workspace" instead of "create-project". When the page comes up it actually says "New Workspace" but it's not creating a workspace. You can't choose a stack at this point and you can't choose a workspace name either. It's simply adding a project to an existing workspace.

![screenshot - 12_26_2016 7_52_52 am](https://cloud.githubusercontent.com/assets/9939843/21482945/5aefb5c0-cb40-11e6-85cf-2b54f8740867.png)


**To reproduce:**

1. Start new, empty server.
2. Create workspace with demo project.
3. Go back to dashboard (left nav pane "Dashboard" item).
4. Click "Create Workspace".
5. See the "New Workspace" title at the top -- but notice that there's nowhere to name your "new" workspace, and there's no place to select which stack you want.
6. Also note that if you select the same demo project that you created before -- it complains that there is a name conflict. This is because you're not creating a workspace, you're adding to an existing workspace that already has that project name.

**Comment by ghost** [comment]
@nsymms adding a project to an existing workspace is an option. You may create a new workspace and import a new project into it.

**Comment by TylerJewell** [comment]
Yes what Stevan is showing in the future also addresses your concern is a much more strategic way.  This workspace creation consistency is a target for us in q1.

However there may be a quicker short term fix that we make too.  I think the posters point about create workspace should mean that it honors the language explicitly.  So when we bring up the current page from that button we assume you want to add a project to an existing workspace.  Instead we should be loading that page with the new workspace radio selected.  And this would be a temporary fix until Stevan's long term design is implemented.

**Comment by nsymms** [comment]
Thank you, @TylerJewell. Now I see what I was missing. You **can** create a new workspace from that page, but it's not the default. When the page comes up, you're adding a new project. I was thinking like you said -- more literally. "Create Workspace" IMHO should go through the other 2-page workspace+project creation or at least have the "new workspace" radio selected on the page it goes to now.

**Edit:**
And since this particular item is already under review and a fix is in the works, I'll close this.
