### ISSUE TITLE
Investigate correct working xtermjs with requirejs

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#3517]
We did investigation usage xtermjs instead of old term.js and found technical problem: requirejs which we uses for Orion editor initialization fails xtermjs initialization, because xtermjs used node thechonlogy. Goal of this issue investigate how we can resolve this problem.

**Expected behavior:**

xtermjs scripts shold initalize successfull

**Observed behavior:**
Initalization xtermjs scrips  fails.

**Comment by AndrienkoAleksandr** [comment]
xterm.js can works like correct requirejs module, so I find solution: inject xterm.js like requirejs module https://github.com/eclipse/che/commit/48befcdd8c19b1ffbdf37f666f137a3d3d06592d

**Comment by TylerJewell** [comment]
Yeah!  Nice work @AndrienkoAleksandr !
