### ISSUE TITLE
Unsupported OAuth provider github for Ready-To-Run project

### ISSUE THREAD

**Issue by codergabs** [eclipse-che/che#3523]
[Short description of problem here]
I have installed che on windows 
che is running and workspaces are creating.
But when i am trying to create ready to run projects.
JAVA stack, web-java-spring project
It's throwing error
Unsupported OAuth provider github

**Che version:**    
Version :5.0.0-M8Revision :1c15a44844c96ff9
**Additional information:**
I have tried the resolution mentioned on 
https://github.com/eclipse/che/issues/1694
But of no help.

Can someone give me some pointers

**Comment by ghost** [comment]
@codergabs this is a warning that you have not configured GitHub oAuth. This warning does not affect you unless you want to clone and push to your private GitHub repos or use SSH.

Here are instructions on configuring oAuth - https://eclipse-che.readme.io/docs/git#section-github-oauth

**Comment by codergabs** [comment]
@eivantsov  I am getting this when trying to set up ready to run projects.
Why I have to set it up for ready to run sample projects for che, I installed it before, then it did run without these configurations.
And I have configured the settings mentioned on  https://eclipse-che.readme.io/docs/git#section-github-oauth without any luck
Github
Homepage URL
http://192.168.99.100:8080
Authorization callback URL
http://192.168.99.100:8080/wsmaster/api/oauth/callback

che.oauth.github.clientid=b2485c7d0fbf5c1e04a0
che.oauth.github.clientsecret=f0f67a725e1bec3ab55cd20275e1554430af214e
che.oauth.github.authuri= https://github.com/login/oauth/authorize
che.oauth.github.tokenuri= https://github.com/login/oauth/access_token
che.oauth.github.redirecturis= http://192.168.99.100:${SERVER_PORT}/wsmaster/api/oauth/callback

Then getting error on the following step
Once the oauth is setup, SSH keys are generated and uploaded automatically for GitHub at Profile > Preferences > SSH > VCS by clicking the 'Octocat' icon.

Did I miss anything?

**Comment by ghost** [comment]
@codergabs how did you apply your oAuth config? What happens when you click the octocat button?

**Comment by codergabs** [comment]
@eivantsov 
http://192.168.99.100:8080/wsmaster/api/oauth/authenticate?oauth_provider=github&scope=user,repo,write:public_key&userId=che&redirect_after_login=http://192.168.99.100:8080/ws/wksp-u3v3
{"message":"Unsupported OAuth provider github"}

**Comment by ghost** [comment]
@codergabs how did you apply GitHub oAuth config?

**Comment by codergabs** [comment]
@eivantsov  I went to the che.properties file and modified it.

**Comment by ghost** [comment]
@codergabs how did you start Che on Windows? Can you please elaborate? Your config hasn't been applied.

**Comment by codergabs** [comment]
@eivantsov 
I started che using following command
docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /che:/che eclipse/che start
on boot2docker terminal

**Comment by ghost** [comment]
@codergabs where did you edit che.properties then?

**Comment by codergabs** [comment]
@eivantsov 
I went into the che container and updated the file
./home/user/che/tomcat/webapps/wsmaster/WEB-INF/classes/codenvy/che.properties
./home/user/che/conf/che.properties
./data/conf/che.properties

Not exactly sure, which file to update, so updated all of them

Then clicked github octocat icon with no luck

**Comment by eivantsov** [comment]
@codergabs it will not work this way.

You need to create che.properties file locally with GitHub oAuth properties and then add env:

- e "CHE_CONF=/c/Users/username/che"

**Comment by codergabs** [comment]
@eivantsov 
Please review the following steps
So need to stop che
create che.properties file at /c/Users/username/che.properties with the details
   che.oauth.github.clientid=b2485c7d0fbf5c1e04a0
   che.oauth.github.clientsecret=f0f67a725e1bec3ab55cd20275e1554430af214e
   che.oauth.github.authuri= https://github.com/login/oauth/authorize
   che.oauth.github.tokenuri= https://github.com/login/oauth/access_token
   che.oauth.github.redirecturis= http://192.168.99.100:${SERVER_PORT}/wsmaster/api/oauth/callback
export "CHE_CONF=/c/Users/goba/che.properties"
start che

**Comment by ghost** [comment]
@codergabs here are instructions that will work:

1. Start Che this way. Mind this volume mount:

`/с/users/Username/che:/che`
Username is your windows user. Create a folder named che in your %USERPROFILE%. After Che starts, you should see some files and folders there.

`docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /с/users/Username/che:/che eclipse/che start`

2. Stop Che:

`docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /с/users/Username/che:/che eclipse/che stop`

3. Open `%USERPROFILE%\che\che.env`, look for GitHub oAuth section and add your oAuth info. Save the file:


```
########################################################################################
#####                                                                              #####
#####                                     OAUTH                                    #####
#####                                                                              #####
#
# You can configure a 3rd party provider's oAuth, which will be used for your users when.
# they initiate Git actions from within Che.
#
```

4. Start Che:

`docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /с/users/Username/che:/che eclipse/che start`

**Comment by codergabs** [comment]
@eivantsov 
Followng the procedure I could set up the github oAuth, not getting the Unsupported OAuth provider github error
But still couldn't add sample project into workspace.
It's throwing error
"Internal Server Error: https://github.com/che-samples/web-java-spring.git: cannot open git-upload-pack"

**Comment by codergabs** [comment]
@eivantsov 
No, and I could ping github.com from che container

**Comment by codergabs** [comment]
@eivantsov 
I could pull now, It's working!!!
Some network Issue it seems.
Thank you so much

**Comment by ghost** [comment]
Can you git clone manually when in a terminal in a workspace container?

`git clone https://github.com/che-samples/web-java-spring.git`

**Comment by ghost** [comment]
@codergabs GitHub is acting up for me as well. Hopefully, it'll be ok.

**Comment by ghost** [comment]
I am closing the issue.
