### ISSUE TITLE
File watcher works incorrectly (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3537]
**Reproduction Steps:**
* Open a file in the editor
* Delete the file

**Expected behavior:**
* Notification should not appear

**Observed behavior:**
* Notification appears

**Che version:**   5.0.0   
**OS and version:**  Ubuntu 14.04  
**Docker version:**  1.12 
**Che install:**    [Docker container]   

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![file_watcher](https://cloud.githubusercontent.com/assets/5408906/21501989/449fc808-cc55-11e6-9317-15ef499147c0.gif)

**Comment by TylerJewell** [comment]
Good bug, @artaleks9 - I think this will be really rare, so I am going to push it out to 5.1.0 for now.
