### ISSUE TITLE
Amazon ECR Support

### ISSUE THREAD

**Issue by jburgess** [eclipse-che/che#3538]
I am attempting to use a private Amazon ECR registry. However, when adding the registry in Che, I am not to use the password as it is longer than 128 characters. Is Amazon ECR registry supported? If so, how can I add this registry?

**Comment by TylerJewell** [comment]
Yes we absolutely do support it.  We just did an engineering cycle for supporting it with some customers.  We will dig up the right docs on this as there are special configs you need to use.

**Comment by ghost** [comment]
@gurumeditator you can add Docker registry not through user dashboard, but in property file. How do you run your Che instance? What syntax did you use?

**Comment by jburgess** [comment]
I ran the Che instance through docker and mounted the /che volume locally. I have added the ECR registry to the property file (and restarted):

che.docker.registry.auth.amazon-reg.*

But, I don't think this repo was attempted

**Comment by ghost** [comment]
@gurumeditator have you edited che.env? Can you share this part of file (replace passwords and any sensitive info with dummy data)

**Comment by jburgess** [comment]
Sorry for the New Year delay.

che.docker.registry.auth.amazon-cdc.url=https://12345678.dkr.ecr.us-east-1.amazonaws.com
che.docker.registry.auth.amazon-cdc.username=AWS
che.docker.registry.auth.amazon-cdc.password=[BIG_LONG_KEY]

**Comment by ghost** [comment]
@gurumeditator we have dedicated envs for AWS registries:

```
#CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ID=id1
#CHE_DOCKER_REGISTRY_AWS_REGISTRY1_REGION=region1
#CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ACCESS__KEY__ID=key_id1
#CHE_DOCKER_REGISTRY_AWS_REGISTRY1_SECRET__ACCESS__KEY=secret1
```

You need to register IAM user, grant permissions for AWS Registry. You will get key and secret, while you already know your registry ID and region.

**Comment by jburgess** [comment]
@eivantsov I have added my AWS Registry as suggested. Note, I am not quite sure where to locate the ID. Is this the name of the repository, or a field in the ARN/URI? I have tried using a few combinations. Below are the details available in the ECS registry:
```
All repositories : cdc
Repository ARN arn:aws:ecr:us-east-1:123456789012:repository/cdc
Repository URI 123456789012.dkr.ecr.us-east-1.amazonaws.com/cdc
```
che.env file
```
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ID=123456789012
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_REGION=us-east-1
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ACCESS__KEY__ID=[IAM_KEY_ID]
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_SECRET__ACCESS__KEY=[IAM_SECRET_ACCESS_KEY]
```

but, I get the following error I believe is related:
```
2017-01-15 16:32:06,617[ted-scheduler-1]  [INFO ] [ockerAbandonedResourcesCleaner 123]  - List containers registered in the api: []
2017-01-15 16:32:06,638[ted-scheduler-1]  [ERROR] [o.e.c.c.s.e.LoggedRunnable 64]       - null
java.lang.NullPointerException: null
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.cleanNetworks(DockerAbandonedResourcesCleaner.java:164) ~[che-plugin-docker-machine-5.0.1.jar:5.0.1]
        at org.eclipse.che.plugin.docker.machine.cleaner.DockerAbandonedResourcesCleaner.run(DockerAbandonedResourcesCleaner.java:91) ~[che-plugin-docker-machine-5.0.1.jar:5.0.1]
        at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:43) ~[che-core-commons-schedule-5.0.1.jar:5.0.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by TylerJewell** [comment]
@JamesDrummond - please investigate.  Sorry @gurumeditator about the long time in responses.  We have had a lot happening the past couple weeks with shipping 5 release.

**Comment by JamesDrummond** [comment]
@gurumeditator Have you set authentication? Refer to [https://eclipse.org/che/docs/setup/configuration/index.html#private-images](https://eclipse.org/che/docs/setup/configuration/index.html#private-images) for additional information.

```
CHE_DOCKER_REGISTRY_AUTH_REGISTRY1_URL=url1
CHE_DOCKER_REGISTRY_AUTH_REGISTRY1_USERNAME=username1
CHE_DOCKER_REGISTRY_AUTH_REGISTRY1_PASSWORD=password1
```

**Comment by ghost** [comment]
@JamesDrummond this is the wrong conf.

@gurumeditator the error you get has nothing to do with registries. So, you have added all of the ids and secrets and it still does not work?

**Comment by jburgess** [comment]
Yes, that is correct.  When you say all of the ID**s**, I have the following "CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ID" ID defined. Is this all that is needed?

```
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ID=123456789012
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_REGION=us-east-1
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ACCESS__KEY__ID=[IAM_KEY_ID]
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_SECRET__ACCESS__KEY=[IAM_SECRET_ACCESS_KEY]
```

I am still unsure as to what "CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ID" refers to. Can you provide a bit more information on what it is and where to find this value?

**Comment by ghost** [comment]
@gurumeditator each registry has an ID and region. And your IAM user has secret and secret access key.

**Comment by ghost** [comment]
@gurumeditator did you have a chance to setup it properly?

**Comment by ghost** [comment]
@gurumeditator I am closing the issue. Feel free to reopen if you failed to connect to your AWS registry.
