### ISSUE TITLE
Workspace doesn't startup

### ISSUE THREAD

**Issue by cifren** [eclipse-che/che#3543]
My workspace is stuck on start up and log displays 

```
2016-12-28 08:49:54,279[ost-startStop-1]  [WARN ] [e.c.p.m.s.c.c.ClasspathManager 87]   - Maven server not started looks like you don't have Maven in your path
```

This issues seems to be linked directly to the content of my projects directory, last time I thought it was because I created a symlink but when I did some tests the issue left and today again but I have no symlink. I removed a backup folder of a project and everything came as normal... I tried to start the workspace 4 times before removing the folder. And my workspace is reset too.

The project folder seems really sensitive and can block the startup of a workspace without giving any information about it.

**Reproduction Steps:**

1. Add a folder into project directory without passing by interface, via shell
2. Shutdown the workspace and the Che server
3. Start Che Server and workspace

**Expected behavior:**

Workspace starts without issue

**Observed behavior:**

Workspace gives timeout on boot
At that Log moment => 2016-12-28 08:49:54,279[ost-startStop-1]  [WARN ] [e.c.p.m.s.c.c.ClasspathManager 87]   - Maven server not started looks like you don't have Maven in your path

**Che version:**    5.0.0-M8   
**OS and version:**  Win7 + Boot2Docker 1.12.4
**Docker version:** Docker version 1.12.3
**Che install:**    Docker container

**Additional information: na

* Problem started happening recently, didn't happen in an older version of Che: Yes (but not sure)
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
@cifren - thank you for posting the issue. We appreciate it when the community gets engaged this way.  In the 5.0.0 release candidate builds, we have introduced a number of improvements to file watchers, which may solve this problem for you.  Could you run Che using this technique and try the "nightly" version to see if your problem still exists.

https://github.com/eclipse/che/tree/master/docs/_docs/setup

**Comment by ghost** [comment]
@cifren what stack did you use? The original warning is just a warning.

Can you share complete server logs and workspace agent logs please?

**Comment by cifren** [comment]
I use my own stack, which extends codenvy/node. This stack for what I see works perfectly, but sometimes when I add some new folders into projects it doesn't restart.

My stack
```
"recipe": {
   "location": "cifren-tchat",
   "type": "dockerimage"
}
```

I am sorry I don't have the logs, yesterday I installed the new 5.0.0M8 and today the new nightly version, the only things in docker still existing is the image of 5.0.0M8, the container has been deleted (at least I don't see it when I execute docker ps -a). I am not even sure how to get those logs lol.

Tell me how to get those logs and next time I see the issue comes back, I will share them. For now, I didn't try to kill the system, I didn't have the time to do it.

**Comment by ghost** [comment]
Logs are at `${location}//instance/data/logs/machine`

`$location` is a local directory that you have mounted into `/data` when running Che.

**Comment by cifren** [comment]
I have been able to retrieve the folder '${location}' but my version was slighlty differente maybe a previous build, the folder 'instance' does not exist, I have 'conf / lib / stacks / storage / templates / workspaces'

And just for information, in my other versions (5.0.0-M8 and nightly), i don't have any logs either, is there a flag to enable ?

**Comment by ghost** [comment]
What syntax did you use to run Che?

**Comment by cifren** [comment]
**docker** run --rm -t -v /var/run/docker.sock:/var/run/docker.sock **-e CHE_DATA=/c/Users/webide** eclipse/che:**latest** start

And the version number was coming from docker run eclipse/che:latest info

After that (yesterday morning) I installed the new build of 5.0.0-M8, which has completly changed the run command, forcing me to run:
docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock **-v /c/Users/webide/che:/che** eclipse/che:**5.0.0-M8** start

**Comment by ghost** [comment]
@cifren ok, this syntax indeed does not mount logs.

When you start a workspace, you should see the logs. This where you got this Maven warning from, right?

**Comment by cifren** [comment]
yes on the interface, there are 2 techniques to load the workspace, the first will be via **workspaces > nodejs(workspace name) > actions > start** but I prefer to start it via **recent workspaces > nodejs**, the logs are directly available there.

Usually, the interface ask if I want to start the snapshot, I say "nop", it restarts the process of building from docker and when I have the issue it stops on maven log and no more logs available.

Just for information, Maven warning appears everytime, it has nothing to be in the issue, that is just at that moment the issue is happening.

You didn't answer my question "is there a flag to enable the log files?"

**Comment by ghost** [comment]
@cifren no, there's no flag to enable logs using the syntax you used.

By the way, can you start workspaces from ready to go stacks?

**Comment by cifren** [comment]
My workspaces are working right now, like I said my issue happens randomly depending on the structure of the folder projects. But as soon I delete the last folder I modified, the workspace starts again without problem. 

My custom stack is working fine, and the ready to go too.

**Comment by ghost** [comment]
@cifren i'm afraid I do not have enough details to try to reproduce at this point. I will leave the issue opened though. Feel free to update it with steps to reproduce, if and when you can reliably reproduce it.

**Comment by cifren** [comment]
The last update seems to have improve performance on IDE, that is nice :)

Thanks for the help, I'll try to have more details next time.

**Comment by TylerJewell** [comment]
We just made a massive merge of a system around "file system watchers". It optimizes the tracking all changes on the server-side and minimizes notifications to the client side.  The performance is noticeably improved.  We hvae a tech article on it coming out soon.

**Comment by TylerJewell** [comment]
Closing this - feel free to open new issue once we have a reproducible bug report.
