### ISSUE TITLE
UD doesn't allow to restart WS if previous start failed

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3545]
If user starts WS in UD from WSs list and it fails UD shows red point as an indicator of WS start state and doesn't allow user to try again until reload of UD or navigation to another view.

**Reproduction Steps:**

1. Brake existing WS config, e.g. provide bad dockerfile as a source of machine. Or create new WS with broken config.
2. Open WSs view in UD.
3. Start WS with play button. It will fail.

**Expected behavior:**

It is possible to press play button again.

**Observed behavior:**

There is no play button.

**Che version:**    5.0.0-Snapshot
**OS and version:** Ubuntu 16.04
**Docker version:** 12.04
**Che install:**    Docker container

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by akurinnoy** [comment]
time spent: 4h
