### ISSUE TITLE
Make CLI show che-server start logs in dev mode 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3546]
Sometimes in development che-server doesn't start. It can happen if developer did mistake in configuration, etc.
In that case CLI waits che-server too long. It would improve Che developers experience if these logs were shown by default, so developer identify problem immediately after looking at errors in logs.

**Che version:**    5.0.0-Snapshot
**OS and version:** Ubuntu 16.04
**Docker version:** 12.04
**Che install:**    Docker container

**Comment by TylerJewell** [comment]
This was requested and discussed in last week's team leaders meeting.  The general feeling was that it would. Real the container philosophy.  Roman was a -1 on it.  I was as well because it introduces blocking behavior when we don't want to.

I cannot remember who was the engineer that raised it for consideration.

**Comment by garagatyi** [comment]
What do you mean blocking behavior? AFAIK CLI already waits server start, so what would be change in behavior?

**Comment by TylerJewell** [comment]
Log output of Che server would have a tailing affect making a start operation that is non blocking blocking.  The feeling of the team leads was that we had the docker logs option there to show the outputs for you.  You can write a local script that starts Che and shows the log output at the same time in the background but mixing the two would deviate from the container philosophy.

**Comment by garagatyi** [comment]
We already wait for deploy of API war. It is the longest operation in che-server boot sequence. And exactly that step sometimes fails because of developers mistakes. And this issue is intended to address that. So as far as I can see it can be implemented with no impacts on time of boostrapping and any change in blocking/non/blocking behavior.

**Comment by garagatyi** [comment]
It is essential because in case developer mises some property Che won't start and CLI will not show anything. So developer has to wait some time after boot. Then consider if it was to long, if yes check logs. It is not convenient.
If you don't want to expose them by default let it be some flag (variable) that enables that behavior.

With native Che we didn't have such problem because it showed logs, so I consider lack of that feature as regression

**Comment by TylerJewell** [comment]
So the requested logic would be:
```
If development_mode then
  if 'eclipse/che start -f' then
    during start, run 'docker logs -f che-server &'
  fi
  after successful boot, then kill the docker logs command
fi
```

@riuvshin needs to comment on whether this is viable, or breaking the design of the CLI. This is not a regression as this CLI was never intended to have this type of behavior. And I am not sure that it makes sense yet.

**Comment by garagatyi** [comment]
As far as I understand current logic is:
 - run compose start 
 - wait until container is running
 - wait until `curl <che_ip>:<che_port>/api/` responds 200 or 302

So we can get logs between curl calls. We don't have to follow logs, just get logs using time stamp of last logs fetch.
But It may be easier to implement and support if we do that in a way you suggest.
 - run compose start 
 - wait until container is running
 - run 'docker logs -f che-server &' and put id of that process into variable
 - wait until `curl <che_ip>:<che_port>/api/` responds 200 or 302
 - kill job with ID saved in variable

**Comment by TylerJewell** [comment]
I have an experimental pull request open for this.  It needs a lot of testing.

**Comment by riuvshin** [comment]
Sorry guys I don't understand why we need this if we already display command how to get codenvy / che logs, if user feels that it boots too long or failed to start just execute this command to get logs. I don;t think we have to complicate really simple things.

**Comment by garagatyi** [comment]
Probably you don't see value because you don't change java code every day.

**Comment by l0rd** [comment]
@garagatyi I usually open a separate shell to show che-server logs while the cli is running. But yeah that's annoying. Maybe we could have a `--attach` option for the CLI?

**Comment by TylerJewell** [comment]
I think that could be good if we wanted to give that much control over the process.  But I was thinking about it over the weekend and you really only want to show the logs if you are in a debugging mindset.  So if you do --debug, then this extra activty can be assumed.  If you are not debugging, then the extra step of running docker logs is ok for end user.

**Comment by garagatyi** [comment]
I've tested what Tyler implemented in his branch and it works like a charm without --attach option.
