### ISSUE TITLE
Wiped issue

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3550]
Wiped Issue

**Comment by TylerJewell** [comment]
We should elevate this to a blocker.

**Comment by garagatyi** [comment]
Why? It behaves in such a way from the beginning. And we didn't see many support tickets about  that.

**Comment by TylerJewell** [comment]
Security vulnerability as it is a simple way for an intruder to potentially destabilize the entire system.  We may even want to delete or hide this issue so as not to make it too public that this issue exists.

**Comment by garagatyi** [comment]
This issue doesn't affect the whole system - just users WS. So if user caused to his workspace he will have to deal with that. I don't see any security impacts

**Comment by TylerJewell** [comment]
It is absolutely a security issue. If user allows others into workspace and that user is bad actor then that is a security vulnerability.

**Comment by garagatyi** [comment]
If you mean that invited users can do that and it will harm owners browser then it is not worst thing invited user can do in workspace. Remember that probably this user will have sudo rights in terminal, so he can do a lot of bad things there.

**Comment by TylerJewell** [comment]
While it is easy for us to say that any invites user can potentially do bad things to a workspace and leave it an unstable state, that is true.  However what makes it a security issue is that we should never leave the browser or the system in an unstable state when that happens.  And anything that leaves one of those two items unstable is a type of security vulnerability.  It is low grade but still a threat.

**Comment by garagatyi** [comment]
I just mean that invited user can impact dev agent somehow that will cause huge traffic to browser also.
