### ISSUE TITLE
docker fails when starting a workspace

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3552]
Merry christmas and happy New year!

When I start any workspace I have a docker error. 

![docker-error](https://cloud.githubusercontent.com/assets/22703481/21520137/76ee5fb6-ccf2-11e6-8a50-82038ca8fac8.jpg)

**Reproduction Steps:**

1. 
$ git clone https://github.com/eclipse/che.git
$ cd che/assembly
$ mvn clean install
$ cd assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/bin
$ ./che.sh start

2. Create a new workspace and start it

**Expected behavior:**

It starts the workspace.

**Observed behavior:**

The error: `Could not start workspace wksp-u18r. Reason: Start of environment default failed. Error: Error response from docker API, status: 404, message: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-f6715790d40d -j DOCKER: iptables v1.4.21: Couldn't load target 'DOCKER':No such file or directory Try 'iptables -h' or 'iptables --help' for more information. (exit status 2)`

**Che version:**   the latest  
**OS and version:** Ubuntu 14.04  
**Docker version:** Docker version 1.12.5, build 7392c3b 

**Additional information:**

The host computer is behind a proxy. 

* Problem started happening recently, didn't happen in an older version of Che: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by aleksei-burlakov** [comment]
Thank you TylerJewell!

I also used docker to start che 
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-M9-SNAPSHOT/eclipse-che-5.0.0-M9-SNAPSHOT:/che  eclipse/che start`
the result was the same.

**Comment by ghost** [comment]
@aleksei-burakov that is certainly some iptables issue.

Can you manually run docker containers?

`docker run -ti -P codenvy/ubuntu_jdk8 bash`

Does the above command open a shell into a container?

**Comment by ghost** [comment]
Maybe threads like this one can shed some light - https://github.com/docker/docker/issues/15948
