### ISSUE TITLE
Fix package/deploy issue of docs.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3563]
Need docs war file to be "deploy/installed" at {host}/docs .

**Comment by skabashnyuk** [comment]
Issue is unclear. Please rephrase it.

**Comment by JamesDrummond** [comment]
@slemeur Please review path above.

**Comment by slemeur** [comment]
updated.

**Comment by JamesDrummond** [comment]
This issue has been fixed.
