### ISSUE TITLE
UD doesn't save changes on "save" if "apply" wasn't clicked and doesn't inform user that changes will be discarded

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3565]
In UD when user edits some jsons like configuration of WS on WS creation there are 2 buttons: apply and save.
Apply is location a bit far and user might not see it and press save. 
The problem is that on clicking "save" UD discards changes silently.

**Reproduction Steps:**

1. Open UD.
2. Open WS creation view.
3. In the WS configuration editing view go into "Workspace config" section.
4. Edit something.
5. Click save.
6. Go into "Workspace config" section and  check changes.

**Expected behavior:**

UD inform that changes should be applied before saving or UD applies changes automatically.

**Observed behavior:**

UD creates WS but discarded made by user changes.

**Che version:**    5.0.0-Snapshot
**OS and version:** Ubuntu 16.04
**Docker version:** 12
**Che install:**    Docker container

**Comment by TylerJewell** [comment]
I think this requires @slemeur to really think about UX a bit more here. I agree the current behavior is confusing. Unsure if the proposed solution is best UX.

**Comment by slemeur** [comment]
As we will have a new flow to create a workspace, I would not do too many changes for now on this.

As a little improvement, we need to catch the changes that are done by directly editing the json of workspace config. 
*Creating a workspace*
- When the user is editing the workspace configuration: the changes are applied automatically (without having to click on "Apply"). 

*Editing a workspace*
- When the workspace configuration is edited - changes are applied in other tabs - and clicking on "Save" will confirm the changes.

**Comment by akurinnoy** [comment]
time spent: 2d
