### ISSUE TITLE
No syntax highlighting for Groovy files

### ISSUE THREAD

**Issue by cptblaubaer** [eclipse-che/che#3569]
Hi there, 

I started to play around with Eclipse Che after finding the link to Codenvy in the documentation of vert.x. I used the docker image to setup my own instance

Version: 5.0.0-M8
Revision: 1c15a44844c96ff9
Build Time: 2016-12-07 12:51:44

When trying to work on Groovy source files the syntax-highlighting is missing. The status bar tells "text/x-groovy", when working on a Java-file it just tells "Java" and the highlighting is fine. Also JavaScript ("JavaScript") and Ruby ("text/x-ruby") work fine. 

Am I missing something in the configuration? I use UTF-8 encoding. 

I'd be happy to use Eclipse Che with our Team as an alternative to administer local eclipse install on n developer machines. As we would mainly use it as a Groovy Source Code Editor, Eclipse Che might be a good opportunity for us. 

@TylerJewell of @Codenvy asked me to open that issue. 

Thanks for developing this great project. Let me know if I can help you. 

Take care greetings from sunny but cold Germany

Andreas

**Reproduction Steps:**

1. Open a Groovy file
2. Check if there is syntax highlighting
3. Check the information in the editor status line

**Expected behavior:**

Source code is rendered with syntax highlighting

**Observed behavior:**

Source Code is shown in plain ASCII without highlighting

**Che version:**    5.0.0-M8   
**OS and version:** Linux a59ec30b29c6 4.4.39-moby #1 SMP Fri Dec 16 07:34:12 UTC 2016 x86_64 Linux
**Docker version:** 
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
    
**Che install:**    Docker image as stated in [Start Che with Docker](https://www.eclipse.org/che/getting-started/download/)
curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.sh > che.sh
curl -sL https://raw.githubusercontent.com/eclipse/che/master/che.bat > che.bat
che start

**Additional information:**
* Just worked with this version and it has happened from the start
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ghost** [comment]
Issue's confirmed.
