### ISSUE TITLE
Recipe location in stack editor should redirect to proper url

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3571]
In the stack editor, it is possible to click on the "recipe location" but it redirects to a wrong location.
![screen shot 2016-12-29 at 17 01 23](https://cloud.githubusercontent.com/assets/1636769/21547775/7508ee18-cde8-11e6-8aea-298550028f81.png)

We should redirect to: https://hub.docker.com/r/eclipse/dotnet_core/

We need to care if the recipe comes from a private Docker registry as well.

**Che version:**    5.0.0-snapshot

**Comment by TylerJewell** [comment]
@slemeur - are you saying that the recipe should pull the location from the contents of the stack definition?

**Comment by olexii4** [comment]
We have a list of registries. But we can't check anything from client side.  We could  disable ability to copy recipe location and/or redirect as a link. Check content of location. If it contains 'http' or 'https' - show the link.

**Comment by slemeur** [comment]
Agree with the proposal to fix that in 2 times:
1- we disable ability to click on the recipe for now
2- we implement proper API to get that, because we should be able to get it

Could you please create the issue for server side and cross link with this one.

Thanks.

**Comment by olexii4** [comment]
It depends on  https://github.com/eclipse/che/issues/4256
