### ISSUE TITLE
Responsive design doesn't work properly in Command section of stack details

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#3572]
Sometimes it is very uncomfortable to edit stack's commands.

**Reproduction Steps:**
1. Open dashboard, go to `Stacks` tab
2. Select `Eclipse CHE` stack
3. Scroll to `Commands` section

**Expected behavior:**
All controls should be visible.

**Observed behavior:**
Text of commands is cut. `Edit` and `Delete` buttons are behind right border and there is no scroll bars.

**Che version:**  5.0.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** Version: 1.12.5 , API version:  1.24
**Che install:**  cli, nightly

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: Yes, but only for some stacks.
![wrd](https://cloud.githubusercontent.com/assets/15607393/21561463/841e39de-ce75-11e6-8de8-14621a4cfa79.gif)

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa can you check if this issue is up to date?

**Comment by SkorikSergey** [comment]
This issue is actual for Che 6.8.0-SNAPSHOT.
