### ISSUE TITLE
Project becomes invalid after rename workspace

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3574]
**Reproduction Steps:**
* Open a workspace in the IDE and expand a project
* Press 'Workspaces' in the navbar and perform rename the workspace
* Open the workspace in the IDE after rename
* Try to use the project.

**Expected behavior:**
* The project should be available and restored

**Observed behavior:**
* The project is invalid. **This bug is reproduced only in CHE.**

**Che version:**  5.0.0  
**OS and version:**  Ubuntu 14.04  
**Docker version:**  1.12   
**Che install:**    [Docker container]   

**Additional information:**
* Related selenium test: _ProjectStateAfterRenameWorkspaceTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![rename_ws](https://cloud.githubusercontent.com/assets/5408906/21563224/8e8a64f2-ce88-11e6-8b14-4f994a8c214a.gif)

**Comment by iamslite** [comment]
If you rename the workspace back again you can then access the project again, so the files are obviously still present, but the connection seems to get broken by the rename.

**Comment by garagatyi** [comment]
This is bug in storage work. So this issue should be kept by platform or enterprise team

**Comment by AbyssalReClass** [comment]
As a temporary workaround, you can move your projects manually. Workspaces are stored in <data path>/instance/data/workspaces/, just copy the projects from the directory with the old workspace name to the new one.

**Comment by ghost** [comment]
Yes, when a workspace is renamed a new directory is created, and this dir does not contain project sources although workspace config has projects defined.

Luckily, when you open an IDE, it prompts you to import such a project.
