### ISSUE TITLE
Unexpected losing of  ocus in the terminal after minimize/maximize operations

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3578]
**Reproduction Steps:**

1. Go to the terminal, type for example `ps ax` command several times
2. Maximize terminal panel and type the `ps ax` commands one more time
3. Minimize the terminal try to type some text.

**Expected behavior:**
The terminal should scroll to last line, the text should be typed.
**Observed behavior:**
Terminal does not scroll position to last line. The focus is lost.  

**Che version:**   5.0.0
**OS and version:** Ubuntu 14 TLS
**Docker version:** 1.12.5
**Che install:**    Docker container

**Comment by svor** [comment]
Scrolling to the bottom will be fixed after applying xterm.js https://github.com/eclipse/che/issues/3529
