### ISSUE TITLE
anyone who can tell me where's  the source code of che-terminal-server

### ISSUE THREAD

**Issue by zhaohaiyi** [eclipse-che/che#3587]
1. where's the che-terminal-server source code used by che-4.5.1.
2. where's the che-terminal-server source code used by latest che.

**Comment by TylerJewell** [comment]
https://github.com/eclipse/che-lib

We keep major forks in another repo for management.  We will be replacing the current terminal with xterm shortly.  We have a branch and it is getting tested.

**Comment by TylerJewell** [comment]
Closing this question as it was answered.  FYI, there is a branch that is about to be merged that migrates term.js to xterm.js, a better supported offering.
