### ISSUE TITLE
Documentation for PHP Debugging

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#3594]
As the PHP Debugging topic is complete I would like to provide detailed documentation on this page: https://eclipse-che.readme.io/docs/debug

@TylerJewell What is the process of updating the documentation? Should I use the "Suggest Edits" action? Or is there a better way?

**Comment by kaloyan-raev** [comment]
Cool! This way it is more developer-friendly. Then I will make a PR directly to this file: https://github.com/codenvy/che-docs/blob/master/src/main/_docs/use-che-as-an-ide/ide-debug.md

**Comment by TylerJewell** [comment]
Give the kudos to @JamesDrummond @slemeur - they have spent 100s of hours on the conversion.

**Comment by kaloyan-raev** [comment]
PR https://github.com/codenvy/che-docs/pull/37
