### ISSUE TITLE
CLI download error.

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3596]
When I start ./che.sh from the base che folder it starts to download the latest CLI and crashes.

$ ./che.sh
INFO:  Downloading cli-latest
ERROR: CLI download error. Bad network or version. CLI update works for 5.0.0-M3+.

**Reproduction Steps:**

1. I have set http_proxy environment variables.
2. 
```
$ git clone https://github.com/eclipse/che.git
$ cd che
$ ./che.sh
INFO:  Downloading cli-latest
ERROR: CLI download error. Bad network or version. CLI update works for 5.0.0-M3+.
```

**Expected behavior:**

It pulls the images and lists the starting options.

**Observed behavior:**

It does not pull the images. It seems to be a proxy issue, but the proxy settings for docker and enviroment variables are set.

**Che version:**    latest
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12.15 

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by TylerJewell** [comment]
We are in the process of removing this cli approach as we transition to the 5 release this week.   Please see the new cli documented at https://github.com/eclipse/che/tree/master/docs/_docs/setup.  Please run the nightly version of it.

Sorry you had this problem.  We hope docs to be refreshed today or tomorrow.

**Comment by aleksei-burlakov** [comment]
The error does not appear anymore.
