### ISSUE TITLE
CLI does not use a local che assembly

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3599]
When I start che as 
`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT:/che -e CHE_ASSEMBLY=~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT eclipse/che start`
Then it does not use the local version of che. When I start che as 
`$ ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/bin/che.sh start`
then the local che starts.
(`~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT` is a **correct** the path to the assembly.)

**Che version:**   latest
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12.15 

**Additional information:**

`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT:/che -e CHE_ASSEMBLY=~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT eclipse/che start`
returns 
```
WARN: You are using CLI image version 'latest' which is set to '5.0.0-M8'.
INFO: (che cli): Loading cli...
INFO: (che cli): Checking registry for version '5.0.0-M8' images
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         port 8080 (http):       [AVAILABLE]

INFO: (che start): Starting containers...
INFO: (che start): Services booting...
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Booted and reachable
INFO: (che start): Ver: 5.0.0-M8
INFO: (che start): Use: http://10.44.104.213:8080
INFO: (che start): API: http://10.44.104.213:8080/swagger
```
and

`$  docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT:/che -e CHE_ASSEMBLY=~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT eclipse/che info`
returns
```
WARN: You are using CLI image version 'latest' which is set to '5.0.0-M8'.
INFO: (che cli): Loading cli...
INFO: ---------------------------------------
INFO: ------------   CLI INFO   -------------
INFO: ---------------------------------------
INFO:
INFO: -----------  CHE INFO  ------------
INFO: CHE_VERSION           = 5.0.0-M8
INFO: CHE_INSTANCE              = /home/d067440/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/instance
INFO: CHE_CONFIG                = /home/d067440/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT
INFO: CHE_HOST              = 10.44.104.213
INFO: CHE_REGISTRY          = /version
INFO: CHE_DEVELOPMENT_MODE  = off
INFO: CHE_BACKUP            = /home/d067440/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/backup
INFO:
INFO: -----------  PLATFORM INFO  -----------
INFO: DOCKER_INSTALL_TYPE       = native
INFO: IS_NATIVE                 = YES
INFO: IS_WINDOWS                = NO
INFO: IS_DOCKER_FOR_WINDOWS     = NO
INFO: HAS_DOCKER_FOR_WINDOWS_IP = NO
INFO: IS_DOCKER_FOR_MAC         = NO
INFO: IS_BOOT2DOCKER            = NO
```

* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by slemeur** [comment]
Hi @aleksei-burakov,

The CLI has been improved over the last months and this instruction to start with a local assembly are not supported anymore. We are in the process of updating our documentation on this.

You can find new CLI information and instructions to start with custom assembly on the following documentation:
https://github.com/codenvy/che-docs/blob/master/src/main/_docs/setup/che-setup-configuration.md#development-mode

**Comment by ghost** [comment]
@aleksei-burakov basically, you need to do a different mount: `/path/to/your/che/repo:/che` So, what is different now is that the entire repo is mounted, not just binaries

**Comment by aleksei-burlakov** [comment]
I tryed `docker run -it --rm -e CHE_HOST=10.44.108.110 -v /var/run/docker.sock:/var/run/docker.sock -e CHE_ASSEMBLY=~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT -v ~/che:/che eclipse/che start` and there was no change. Actually the change should be that there should appear a new stack. This stack is written in a single file namely `~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/stacks/stacks.json` Might it be that there anohter stacks.json file (in another dirrectory) is being read?

**Comment by TylerJewell** [comment]
@aleksei-burakov - I think you have slightly wrong syntax.  The new CLI simplifies a lot.  You are mixing hte old syntax with the new syntax a bit that we are transitioning to.

So, please try the following:
```
docker run -it --rm -e CHE_HOST=10.44.108.110 -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/tmp:/data eclipse/che-cli:nightly start
```

Explanation:
1. Mount your local git repo of che to :/repo - this will auto use your assembly
2. Mount your local data folder to :/data - this is where che will save user data
3. For now, use eclipse/che-cli:nightly as the image

Here are the new docs for the new CLI.
https://github.com/eclipse/che/tree/master/docs/_docs/setup

**Comment by aleksei-burlakov** [comment]
`$ docker run -it --rm -e CHE_HOST=10.44.108.110 -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/tmp:/data eclipse/che-cli:nightly start` does not start che. It returns only
```
WARNING: No swap limit support
INFO: Proxy: HTTP_PROXY=http://proxy.wdf.sap.corp:8080/, HTTPS_PROXY=https://proxy.wdf.sap.corp:8080/, NO_PROXY='192.168.174.148,.sap.corp,10.*,localhost,127.0.0.1,0.0.0.0,github.wdf.sap.corp,nexus.wdf.sap.corp:8443,nexus.wdf.sap.corp:8081,*.sap.corp,*.local,169.254/16,*.corp.sap,10.17.81.88:8081'
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
```
and when I go to `http://10.44.108.110:8080/` there the web site is not available.

**Comment by aleksei-burlakov** [comment]
If I use not the latest version, ie
`$ docker run -it --rm -e CHE_HOST=10.44.108.110 -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/tmp:/data eclipse/che-cli:latest start`
then I have
```
WARN: You are using CLI image version 'latest' which is set to '5.0.0-M8'.
INFO: Welcome to Eclipse Che!
INFO: 
INFO: We need some information before we can start Eclipse Che.
INFO: 
INFO: Eclipse Che commands require additional parameters:
INFO:   1: Mounting 'docker.sock', which let's us access Docker
INFO:   2: A local path where Eclipse Che will save user data
INFO: 
INFO: Simplest syntax:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/che
INFO:                          eclipse/che-cli start
INFO: 
INFO: 
INFO: Or run with overrides for instance and/or backup:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/che
INFO:                       -v <YOUR_INSTANCE_PATH>:/che/instance
INFO:                       -v <YOUR_BACKUP_PATH>:/che/backup
INFO:                          eclipse/che-cli start
```

**Comment by TylerJewell** [comment]
The 5.0.0-M8 version requires `:/che` to be mounted instead of `:/data`.  We changed that for M9.  So your first syntax was correct.

How aggressively have you tested your HTTP_PROXY and NO_PROXY configurations?  You can see the CLI is detecting the Docker daemon configuration for these items and then inheriting that.  I suspect that this is the issue.

**Comment by aleksei-burlakov** [comment]
There seems to be a typo in ~/tmp:/data . Ok, I did
`$ docker run -it --rm -e CHE_HOST=10.44.108.110 -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli:nightly start`
and there were
```
WARNING: No swap limit support
INFO: Proxy: HTTP_PROXY=http://proxy.wdf.sap.corp:8080/, HTTPS_PROXY=https://proxy.wdf.sap.corp:8080/, NO_PROXY='192.168.174.148,.sap.corp,10.*,localhost,127.0.0.1,0.0.0.0,github.wdf.sap.corp,nexus.wdf.sap.corp:8443,nexus.wdf.sap.corp:8081,*.sap.corp,*.local,169.254/16,*.corp.sap,10.17.81.88:8081'
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
ERROR: 
ERROR: Your CLI version 'eclipse/che-cli:nightly' does not match your installed version '5.0.0-M8'.
ERROR: 
ERROR: The 'nightly' CLI is only compatible with 'nightly' installed versions.
ERROR: You may not 'che upgrade' from 'nightly' to a numbered (tagged) version.
ERROR: 
ERROR: Run the CLI as 'eclipse/che-cli:<version>' to install a tagged version.
```
Seems it has to be nightly repo. However when I use latest instead of nightly I have 
```
WARN: You are using CLI image version 'latest' which is set to '5.0.0-M8'.
INFO: Welcome to Eclipse Che!
INFO: 
INFO: We need some information before we can start Eclipse Che.
INFO: 
INFO: Eclipse Che commands require additional parameters:
INFO:   1: Mounting 'docker.sock', which let's us access Docker
INFO:   2: A local path where Eclipse Che will save user data
INFO: 
INFO: Simplest syntax:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/che
INFO:                          eclipse/che-cli:latest start
INFO: 
INFO: 
INFO: Or run with overrides for instance and/or backup:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/che
INFO:                       -v <YOUR_INSTANCE_PATH>:/che/instance
INFO:                       -v <YOUR_BACKUP_PATH>:/che/backup
INFO:                          eclipse/che-cli:latest start
```

**Comment by TylerJewell** [comment]
Stick with the nightly - we changed the format after M8.  

I think the issue is either in your NO_PROXY configuration, or in something we are doing when we inherit it.

**Comment by aleksei-burlakov** [comment]
May we make the things clearer. I want to start the che - latest. I do
```
$ cd ~
$ git clone https://github.com/eclipse/che.git
$ cd che 
$ mvn clean install
```
I edit the file` ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/stacks/stacs.json`   by renaming `Blank` stack into `Empty` in order to indicate that the local version is used.
Then I do
`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/che eclipse/che start`
and I see `BLANK` stack instead of `EMPTY`, but `EMPTY` is expected.
I also try 
```
$ cd ~/che
$ ./che.sh start
```
I see again `BLANK` stack instead of `EMPTY`. `EMPTY` is expected. Then I try 
```
$ cd ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/bin
$ ./che.sh start
```
and I observe the desired result. There is `EMPTY` stack instead of `BLANK`.
What is wrong?

**Comment by ghost** [comment]
@aleksei-burakov to edit stacks, go to `~/che/instance/data/stacks` and edit json there.

**Comment by aleksei-burlakov** [comment]
@eivantsov , before sending someone anywhere, please go there yourself first to make sure that you are right. Apparently stacks.json originates from `~/che/ide/che-core-ide-stacks/src/main/resources` , not from `~/che/instance/data/stacks`. Anyway I edited the `~/che/instance/data/stacks/stacks.json` and recompiled che. Now in all the three cases I can only observe BLANK stack instead of EMPTY.

**Comment by TylerJewell** [comment]
@aleksei-burakov - what you did would most definitely would not work.  You are mixing together different concepts with the new CLI, and the concepts that you are poking at work differently with the new CLI.

Let me try to elaborate on the various concepts, so that we have a clear separation of concerns and cand then properly diagnose the system.

1. Stacks.  With stacks, these are runtime and data concepts - so modifying a stack should not have to trigger a recompilation of Che itself. However, the *nature* of how stacks are saved for loading within the UD has changed as we have evolved through the 5.0.0 release cycle.  Previously, in the 4.7 and the early 5.0-M* milestones, there was a stacks.json file which provided the list of Stacks that could potentially appear in Che when Che was first started.  But this file was a load-only concept. It was not actually the database of Stack definitions, so if you edited this stack within Che using our Stack editor, those changes would not be saved to that file.  So it was a load and done sort of scenario.  I am unsure, but I think starting around M4, we abandoned this load-and-done scenario and instead replaced the stack definitions with an internal in-memory database.  So given this, stacks are now data objects that are created, destroyed and modified using our REST API, for which we have with Stacks.

Perhaps @slemeur and @ashumilova could kindly comment on where stacks are permanently persisted and the approach for editing them.  I am not sure that our docs have caught up with this evolution.  So let's make sure we get that right.

2. CLI Instance Folder.  In the CLI, the /instance folder is intended to be where user-data is stored. It's not really intended for customizations.  What happens is that our Docker containers contain a variety of puppet templates and then when you first initialize the folder, we take those templates, your che.env file, and your OS and then generate an OS-specific /instance folder. That instance folder also contains all of the configuration and log files that Che needs during its boot and runtime process.  But since we treat this as more of an operational zone, you can have bad things happen if you go into the instance folder, modify some stuff, and restart Che, because we will take the source puppet templates from within the CLI Docker image and regenerate certain configuration files in that folder to ensure that we get a good run of the system.

Having said that, as engineers we modify files in the /instance folder all the time, so I would expect that if the stacks.json in that /instance folder is still being used for load-only scenarios, that a modification of that file would be reflected when you restarted Che.

3. Restarting Che with the CLI.  If you modify something in the /instance folder, then those configuration files are going to be picked up by Che during a restart.  You should not rebuild an assembly, so I would expect to do `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /che:/data eclipse/che-cli:nightly restart`.

4. Old Che CLI.  We are deprecating and destroying the che.sh, che.bat files that live within the root of the repository as soon as we complete our 5.0 release this week. We will also do the same for the eclipse/che-launcher image. Using these utilities while using the other CLI will just cause you problems.

5. Che Assemblies.  If you do build a completely customized Che assembly in /assembly/assembly-main, we will also be removing the start utilities that appear in the assembly/assembly-main/target folder, as that can also lead to inconsistencies.  You can use your custom assembly with the new CLI by:
```
docker run -it --rm 
  -v /var/run/docker.sock:/var/run/docker.sock 
  -v /che:/data 
  -v <path-to-che-git-repo-root>:/repo
  eclipse/che-cli:nightly start
```

All you now need to do is to mount the location of your Che repo (not the assembly, not anything in it) with the :/repo volume mount, and then the CLI will check to see that you have a valid assembly compiled and use those binaries instead of the ones that are typically included in the Docker image, while also still using the configuration in /instance.

**Comment by ashumilova** [comment]
@aleksei-burakov, so the changes in the file "stacks.json" will be affected each time you restart che. Note, that the che server should be stopped, when you edit that file. If you want to change the stacks in running che - you can use dashboard UI: Stacks -> choose the needed stack and edit it on stack details page.
By editing "stacks.json" I mean the one in 
`$ cd ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/bin`
if you edit it here `/che/ide/che-core-ide-stacks/src/main/resources` and rebuild che code - it will rewrite the content of the first one.

**Comment by ashumilova** [comment]
Also created the issue https://github.com/eclipse/che/issues/3629

**Comment by ghost** [comment]
@aleksei-burakov you are right. All suggestions must be tested and this is what I did.

https://www.youtube.com/watch?v=FeYsIXJlILc

You are right that stacks come from `~/che/ide/che-core-ide-stacks/src/main/resources` however when Che starts it mounts this json from the abovementioned location. There is no need to recompile Che in this case.

Perhaps using an incognito window or clearing cache may help.

**Comment by aleksei-burlakov** [comment]
@eivantsov , @ashumilova , @TylerJewell I appreciate you thorough answer. @eivantsov you were right, I should have done it exactly as you say and not have recompiled the project. 
There is still another question belonging this topic. Namely, how to apply changes in a plugin without recompiling the entire che. 
For example, there is a C# plugin. I edited `~/che/plugins/plugin-csharp/che-plugin-csharp-lang-server/src/main/java/org/eclipse/che/plugin/csharp/projecttype/CSharpProjectType.java` Line 25 where I renamed a string literal `"C# .Net Core"` to `"C# .Net Core2"`. Previously I had to recompile the plugin itself with che/assembly and restart the che.sh script, i.e.
```
$ cd ~/che/plugins/plugin-csharp
$ mvn clean install
$ cd ~/che/assembly/assembly-ide-war
$ mvn clean install
$ cd ~/che/assembly/assembly-wsagent-war
$ mvn clean isntall
$ cd ~/che/assembly/assembly-wsagent-server
$ mvn clean install
$ cd ~/che/assembly/assembly-main
$ mvn clean install
$ cd ~/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT/bin
$ ./che.sh start
```
This technik still works, when I start a new workspace and open a create project dialog, I can see **C# .Net Core2** in the list of projects. However, when I start che using docker
`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/che eclipse/che start `
There is **C# .Net Core**, but not **C# .Net Core2**. 
The question is how to apply the changes in plugins (in ~/che/plugins and ~/che/samples) without recompiling the entire projects, so that I could see them when start che using docker?

**Comment by ghost** [comment]
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/projects/che:/repo -v ~/Downloads/che2:/data eclipse/che-cli:nightly start --pull --debug`

where `~/projects/che` is my local che repo with custom binaries and `~/Downloads/che2` is where Che data and conf is stored.

**Comment by aleksei-burlakov** [comment]
I did 
`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli:nightly start --pull --debug`
It returned
```
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using binaries from your local repository
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
ERROR: 
ERROR: Your CLI version 'eclipse/che-cli:nightly' does not match your installed version '5.0.0-M8'.
ERROR: 
ERROR: The 'nightly' CLI is only compatible with 'nightly' installed versions.
ERROR: You may not 'che upgrade' from 'nightly' to a numbered (tagged) version.
ERROR: 
ERROR: Run the CLI as 'eclipse/che-cli:<version>' to install a tagged version.
```
Then I did 
```
$ docker pull eclipse/che-cli:nightly
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli:nightly start --pull --debug
```
The result was the same. `./che.sh info` returns
```
WARNING: No swap limit support
INFO:  ---------------------------------------
INFO:  -------------   CLI INFO   ------------
INFO:  ---------------------------------------
INFO:  
INFO:  ---------  PLATFORM INFO  -------------
INFO:  CLI DEFAULT PROFILE       = not set
INFO:  CHE_VERSION               = 5.0.0-latest
INFO:  CHE_CLI_VERSION           = latest
INFO:  CHE_UTILITY_VERSION       = nightly
INFO:  DOCKER_INSTALL_TYPE       = native
INFO:  DOCKER_HOST_IP            = 172.17.0.1
INFO:  IS_NATIVE                 = YES
INFO:  IS_WINDOWS                = NO
INFO:  IS_DOCKER_FOR_WINDOWS     = NO
INFO:  IS_DOCKER_FOR_MAC         = NO
INFO:  IS_BOOT2DOCKER            = NO
INFO:  HAS_DOCKER_FOR_WINDOWS_IP = NO
INFO:  IS_MOBY_VM                = NO
INFO:  HAS_CHE_ENV_VARIABLES     = NO
INFO:  HAS_TEMP_CHE_PROPERTIES   = NO
INFO:  IS_INTERACTIVE            = YES
INFO:  IS_PSEUDO_TTY             = YES
INFO:  
INFO: ---------------------------------------
INFO: ---------   LAUNCHER INFO  ------------
INFO: ---------------------------------------
INFO: 
INFO: ---------  PLATFORM INFO  -------------
INFO: DOCKER_INSTALL_TYPE       = native
WARNING: No swap limit support
INFO: DOCKER_HOST_OS            = Ubuntu 16.04.1 LTS
INFO: DOCKER_HOST_IP            = 172.17.0.1
INFO: DOCKER_HOST_EXTERNAL_IP   = not set
flag provided but not defined: --format
See 'docker version --help'.
INFO: DOCKER_DAEMON_VERSION     = 
INFO: 
INFO: 
INFO: --------- CHE INSTANCE LIST  ----------
INFO: 
INFO: 
INFO: ----  CURRENT COMMAND LINE OPTIONS  ---
INFO: CHE_VERSION               = 5.0.0-latest
INFO: CHE_DATA                  = /home/user/che
INFO: CHE_CONF                  = not set
INFO: CHE_ASSEMBLY              = not set
INFO: CHE_PORT                  = 8080
INFO: CHE_HOST_IP               = 172.17.0.1
INFO: CHE_RESTART_POLICY        = no
INFO: CHE_USER                  = root
INFO: CHE_LOG_LEVEL             = info
INFO: CHE_DEBUG_SERVER          = false
INFO: CHE_DEBUG_SERVER_PORT     = 8000
INFO: CHE_HOSTNAME              = localhost
INFO: CHE_SERVER_CONTAINER_NAME = che-server
INFO: CHE_SERVER_IMAGE_NAME     = eclipse/che-server
```

**Comment by ghost** [comment]
@aleksei-burakov you need to flush config in `~/che`:

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli destroy`

And then:

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che-config:/data eclipse/che-cli:nightly start --pull --debug`

I recommend that you keep your Che config outside Che repo, say, `~/che-config`

**Comment by aleksei-burlakov** [comment]
`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli destroy`
has returned
```
WARN: You are using CLI image version 'latest' which is set to '5.0.0-M8'.
INFO: Welcome to Eclipse Che!
INFO: 
INFO: We need some information before we can start Eclipse Che.
INFO: 
INFO: Eclipse Che commands require additional parameters:
INFO:   1: Mounting 'docker.sock', which let's us access Docker
INFO:   2: A local path where Eclipse Che will save user data
INFO: 
INFO: Simplest syntax:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/che
INFO:                          eclipse/che-cli destroy
INFO: 
INFO: 
INFO: Or run with overrides for instance and/or backup:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/che
INFO:                       -v <YOUR_INSTANCE_PATH>:/che/instance
INFO:                       -v <YOUR_BACKUP_PATH>:/che/backup
INFO:                          eclipse/che-cli destroy
```
I tryed 
`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/che eclipse/che destroy`
and it seemed to work :
```
WARN: You are using CLI image version 'latest' which is set to '5.0.0-M8'.
INFO: (che cli): Loading cli...
INFO: destroy !!! Stopping services and !!! deleting data !!! this is unrecoverable !!!

      Are you sure? [N/y] Y

INFO: (che stop): Stopping containers...
INFO: (che stop): Removing containers...
INFO: (che destroy): Deleting instance and config...
```
Then I did
`$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che-config:/data eclipse/che-cli:nightly start --pull --debug`
it has returned
```
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using binaries from your local repository
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
WARN: There is a newer eclipse/che-cli:nightly image on DockerHub.
WARN: (che init): 'nightly' installations cannot be upgraded to non-nightly versions
INFO: (che cli): Checking registry for version 'nightly' images
INFO: (che download): Pulling image puppet/puppet-agent-alpine:4.6.2

4.6.2: Pulling from puppet/puppet-agent-alpine
Digest: sha256:bf93e9f1a92b692efeb3138d25444c478093b6e18818f4242ffc723b04fc6a57
Status: Image is up to date for puppet/puppet-agent-alpine:4.6.2

INFO: (che download): Pulling image registry:2.5.0

2.5.0: Pulling from library/registry
Digest: sha256:1b68f0d54837c356e353efb04472bc0c9a60ae1c8178c9ce076b01d2930bcc5d
Status: Image is up to date for registry:2.5.0

INFO: (che download): Pulling image eclipse/che-init:nightly

nightly: Pulling from eclipse/che-init
e110a4a17941: Already exists 
c6be0cda3022: Already exists 
b883875a9222: Already exists 
d7e1053f3043: Already exists 
588fa03c26ba: Already exists 
d6098f4460bc: Extracting [==================================================>]  6.55 kB/6.55 kB
9609889c3387: Download complete 
6e6e19f86084: Download complete 
bb0743d3c38e: Waiting 
2aee681fe8c0: Waiting 
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/60/60e5f1b73660821dadeb1c1926b32c37277b6cb4273238e8ed6c34d6f2bb22c0/data?Expires=1483706598&Signature=S2Ss2VF-8ep5LfSLGrjH8Xa53zApTHXW2XTo0L6bCEHsc3KOt6sv8MKVoU15jLHCqg5iuKKCNeYGBZowXgLTAipz8z7FxOvvM4EjTLCHsnIwvNtInq1MNLtPaFYHyGzSpfU15kQAtxfhN4j6EFWCgDDKPAF7QcPSnDx5uOxdp0c_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: read tcp 10.0.2.15:53022->52.85.173.41:443: read: connection reset by peer
ERROR: Image eclipse/che-init:nightly unavailable. Not on dockerhub or built locally.
```

**Comment by ghost** [comment]
Smth's wrong with Docker? Can you restart Docker and give it a try again? I can pull this image.

```
eugene@eugene:~/Downloads$ docker pull eclipse/che-init:nightly
nightly: Pulling from eclipse/che-init
e110a4a17941: Already exists 
c6be0cda3022: Already exists 
b883875a9222: Already exists 
d7e1053f3043: Already exists 
588fa03c26ba: Already exists 
d6098f4460bc: Pull complete 
9609889c3387: Pull complete 
6e6e19f86084: Pull complete 
bb0743d3c38e: Pull complete 
2aee681fe8c0: Pull complete 
Digest: sha256:cf862e6d5ba201d2b60f936384a126b3b492038c93fdd11114f833182905b08e
Status: Downloaded newer image for eclipse/che-init:nightly

```

You're almost there. It should work this time.

**Comment by aleksei-burlakov** [comment]
I restarted the docker and pulled the image and then it worked.
```
$ sudo service docker restart
$ docker pull eclipse/che-init:nightly
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli:nightly start --debug
```
Thank you! The issue is closed.

**Comment by TylerJewell** [comment]
@aleksei-burakov - I need to give you some apologies that you ran into some issues. So, there are some dangers in using our "nightly" version for docker images. On the one hand, it is really convenient because you get the nightly.  But on the other hand, there are so many docker images we download and use in the background  that need to all match exactly.  If you download a newer nightly of Che and for whatever reason the other dependencies (which are also nightly) do not get repulled, then bad things can happen.  Bad things tend to happen if we change the interface of the CLI from one nightly to the next, like we did this week.

These issues never happen with versioned images like 5.0.0 because they are tagged.  But we are looking for smarter ways to detect these issues with nightly and then interrupt the CLI with a nice error message saying "wipe all images and repull please"

**Comment by aleksei-burlakov** [comment]
@TylerJewell , thank you. Is there then a way to start start a non-nightly che, so that one could see not only local custom stacks, but also local custom plugins? When I use the command 
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/che -v ~/che/instance:/che/instance eclipse/che-cli start --debug`
I could only observe custom stacks, but not the pugins (I did a dummy change in CSharpProjectType.java by renaming a string literal **"C# .Net Core"** into **"C# .Net Core2"** and the only **C# .Net Core** project is displayed, not **C# .Net Core2**).

**Comment by benoitf** [comment]
@aleksei-burakov in the new CLI, to use custom binaries you've to use ```<path-to-your-local-che-repository:/repo``` mount  
Also `/che` mount is not used anymore, it's `/data`

You can check the logs of che server, it should display that it is using a custom binary in that case

**Comment by aleksei-burlakov** [comment]
Indeed. Thank you!

**Comment by foresightyoue** [comment]
@benoitf I try to build the local che from git repository in branch che-3210 with -v <path-to-your-local-che-repository:/repo,the console output the wrong message as  **/scripts/base/startup_funcs.sh: line 455: /repo/dockerfiles/cli/scripts/cli.sh: No such file or directory**
platform:
win10,boot2docker
consloe log:
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /d/Devlop/che/che_github/che:/repo -v /d/Devlop/che/data:/data eclipse/che-cli:nightly start
WARN: Boot2docker detected - ensure :/data is mounted to %userprofile%
INFO: (che cli): :/repo mounted - using assembly and manifests from your local repository
/scripts/base/startup_funcs.sh: line 455: /repo/dockerfiles/cli/scripts/cli.sh: No such file or directory
Could you pls help on this for me ?Thanks.

**Comment by TylerJewell** [comment]
This is likely a situation where you are mixing older versions of Docker images with newer versions of the repository.  This is usually solved by:
1. Wiping your docker images
2. Rebuild /dockerfiles/base and then /dockerfiles/cli
3. When you then run the CLI, add a `--skip:nightly` hidden flag to avoid pulling new images.

This is a shipping feature now and branches should not be required.
