### ISSUE TITLE
Remove full docs from Che install

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3602]
The Che install doesn't need a full set of local docs, in fact it's likely to cause issues because:
- It adds significantly to the size of the download
- It makes loading Che much slower (due primarily to the large images that have to be loaded for docs)

It would make more sense to only include the docs "homepage" in the Che distribution. This would be a special docs homepage that:
- Removes the header items `docs`, `tutorials`, `Artik`, `Openshift`
- Replaces `View on GitHub` with `GitHub`
- Lists the version of Che the user has installed as a link to the online docs for that version

**Comment by JamesDrummond** [comment]
We can reduce overall size of docs recently so I am not sure if we still want to pursue this enhancement.

Not sure if this is still an issue. Need to confirm with dev if it's still slowed significantly from docs. Download size I would say we might want to consider providing a separate docker container that can be downloaded on demand when someone access the docs for the first time and/or excluding/external linking to the tutorial section where most of the download size from images are located.
