### ISSUE TITLE
Che issue starting debugger.

### ISSUE THREAD

**Issue by AbhiAtDocker** [eclipse-che/che#3604]
Hi, 

I am working on testing eclipse che's features one Windows 10 with docker VM on virtual box. 
I have upped a spring boot app and am able to see the results from the browser. 
But when i switch to debug mode i get the below exception

"Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - excepted >JDWP-Handshake<"

Command used to start the app
java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n  gs-spring-boot-0.1.0.jar 

Is it a known issue ?

Below are port mappings. 
Help appreciated

Thanks in Advance!
Abhishek 

c3fa06897b33        eclipse-che/workspace1k4ofepylfejy7yh_machineu04t5wsz03ogbggr_che_dev-machine   "/bin/sh -c 'sudo /us"   3 hours ago         Up 3 hours          0.0.0.0:32774->22/tcp, 0.0.0.0:32773->4401/tcp, 0.0.0.0:32772->4403/tcp, 0.0.0.0:32771->4411/tcp, 0.0.0.0:32770->8000/tcp, 0.0.0.0:32769->8080/tcp, 0.0.0.0:32768->9876/tcp   workspace1k4ofepylfejy7yh_machineu04t5wsz03ogbggr_che_dev-machine

**Che version:**    [5.0]   
**OS and version:** [Windows 10 Build 10240]   
**Docker version:** [1.12.5I]

**Comment by ghost** [comment]
@AbhiAtDocker can you share the project itself?

**Comment by AbhiAtDocker** [comment]
Pls find the Proj  shared at below location...FYI...i don't see above error anymore though debugger seem not to be starting and there is no error as to why . I verified  Events panel after running the debugger, the debugger connected event is not displaying. Have attached the debug configuration snapshot.

![image](https://cloud.githubusercontent.com/assets/10115913/21677105/9fa9a808-d35e-11e6-9686-31587261476c.png)


[initial.zip](https://github.com/eclipse/che/files/686955/initial.zip)

**Comment by ghost** [comment]
@AbhiAtDocker what happens when you click Debug?

I have just cloned spring-boot repo and ran one of the samples. No issues with debugging:

![image](https://cloud.githubusercontent.com/assets/5337267/21677214/d357141e-d341-11e6-9c49-5c1cebb25455.png)

**Comment by AbhiAtDocker** [comment]
@eivantsov  nothing happens though server is listening on the debug port...i have already restarted the containers, it did not helped.

**Comment by ghost** [comment]
@AbhiAtDocker what do you mean `nothing happens?` You click the button and the dialog does not close itself?

**Comment by AbhiAtDocker** [comment]
yes Dialog close itself , but i don't see any indicator for the operation and the fact that it does not stops at the break point confirms that debugger is not up. 

![image](https://cloud.githubusercontent.com/assets/10115913/21681738/8b1c8c58-d376-11e6-836e-5d1dd82a847d.png)

**Comment by ghost** [comment]
Can you record a short video? I cannot reproduce this one. What is your Che version? You can grab the version at Help > About

**Comment by ghost** [comment]
Also, can you open Chrome dev console, network tab, and send a screenshot with requests that are being made when you click Debug. Thanks

**Comment by AbhiAtDocker** [comment]
Pls download the video for project settings from 
https://www.dropbox.com/s/zvv7wf11pjy8bgm/debugger-issue.webm?dl=0
and for network calls.- no calls are made. (This seem to be happening only with debugger)
[debugger-calls.zip](https://github.com/eclipse/che/files/687384/debugger-calls.zip)

**Comment by ghost** [comment]
@AbhiAtDocker thanks. I will try to reproduce on my Win 8 laptop with Docker ToolBox.

**Comment by AbhiAtDocker** [comment]
Che version: [5.0]
OS and version: [Windows 10 Build 10240]
Docker version: [1.12.5I]

These are the versions on my machine. 

Thanks
Abhi

**Comment by ghost** [comment]
@AbhiAtDocker what if you run debugger not from the dialogue but from the menu Run > Debug > DebuggerName?

Have you tried different browsers? Incognito window?

**Comment by AbhiAtDocker** [comment]
Ok it worked in incognito mode for chrome. I tired Widows edge, got below response.
![image](https://cloud.githubusercontent.com/assets/10115913/21709747/7cc11b22-d409-11e6-93cd-3e932531d447.png)

Thanks

**Comment by ghost** [comment]
Edge is not supported. Can you please clear cache for localhost? It should fix it.

So, is the problem solved? Should I close the issue?

**Comment by AbhiAtDocker** [comment]
Fixed,Closing the issue.
