### ISSUE TITLE
Remove machine API since it is not used anymore

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3616]
We don't use Machine API anymore. We should remove it and it's client in IDE since it is additional technical debt for maintainers.
Issue supposes:
- remove machine creation/destroying API
- remove machine exec's API
- remove workarounds added to continue support of machine API

**Comment by skabashnyuk** [comment]
Question from @TylerJewell 

> What is the approved approach if someone wanted to provide a VM or virtualbox environment? If it's not a machine, what is the tactic?

@gazarenkov  can you comment?

**Comment by benoitf** [comment]
AFAIK I think machine API is used in chedir

**Comment by garagatyi** [comment]
Can you point where in chedir sources it is used?

**Comment by benoitf** [comment]
@garagatyi https://github.com/eclipse/che/blob/master/dockerfiles/lib/src/api/wsmaster/machine/machine-service-client.ts

**Comment by garagatyi** [comment]
We migrated to exec API deployed inside of machine. Master exec API should not be used anymore.
Can you describe which features are using this API?

**Comment by benoitf** [comment]
I suppose the issue that migrated the code was not covering the full scope of Che.
the feature is Chefile/che dir. It includes for example the list of commands that you want to execute after the workspace is started

**Comment by garagatyi** [comment]
ok, thanks for the explanation. I agree that it was not covered in PR that migrated usage of API

**Comment by mshaposhnik** [comment]
UI part is done under #3620 at https://github.com/eclipse/che/pull/3963/files

**Comment by mshaposhnik** [comment]
Blocked by #3967

**Comment by benoitf** [comment]
@mshaposhnik done
