### ISSUE TITLE
Executing commands on Target through Eclipse che

### ISSUE THREAD

**Issue by vijaypa1** [eclipse-che/che#3624]
Hi,

 * When Eclipse Che executes commands on a target board, does it use an IP address to send the command to the target? or is there a serial interface for that?

* Is the command invoked on the target through ssh?

regards
Vijay

**Comment by TylerJewell** [comment]
Can you elaborate on what it means "target board"?

In Eclipse Che, a workspace is composed of a runtime environment. That environment is implemented with different kinds of runtime implementations. The default implementation, for example, is with Docker and you can have many containers making up a workspace. In the Docker scenario commands are executed into a container using an "exec agent" which is a RESTful protocol that is similar to docker exec for injecting commands into a container by its container ID.

In the ARTIK IDE, for example, there is also a machine type of SSH where a workspace can have additional remote machines represented with a recipe that is IP address and login credentials identified. In this case, a command that is targeted for an SSH machine uses its IP and connection credentials to send the command onto the machine.

**Comment by vijaypa1** [comment]
Thanks Tyler.


> Can you elaborate on what it means "target board"?

The context is-  to use eclipse che as an IDE for a few Arm based boards ( eg. single CPU 1Ghz, 512MB RAM). The code can be developed on a linux/mac/windows host and cross compiled for ARM and then pushed to the target ARM boards. 

I was looking for the sequence to steps to achieve this and have posted a related query on the forum (#3273 )eariler.  I would appreciate any help on accomplishing this requirement.
. 

* From your message, it looks like i would also need the ssh machine type to inject some commands on the target ARM board . How do i set it up? 

*  Looking at an alternative of  launching Eclipse Che natively on single CPU ARM boards , it seems to me that this wouldn't be optimal since the CPU and memory resources are limited compared to a typical desktop/laptop. Has anyone tried it? Is there a minimum configuration recommended for running Eclipse Che natively?

**Comment by ghost** [comment]
@vijaypa1 apart from resource requirements, you will need Docker images built specifically for ARM. Both for Che server and workspaces.

Have you taken a look at Artik? https://github.com/codenvy/artik-ide It looks like this is what you are looking for.

**Comment by vijaypa1** [comment]
@eivantsov, Thank you.
 i started looking at ARTK IDE, but  don't seem to have access to the docs. i was trying to access the following link
https://dash.readme.io/project/eclipse-che/v4.0/docs/usage

Can the access enabled for me? Thanks in advance

regards
Vijay

**Comment by vijaypa1** [comment]
Hi,

Any updates to my previous request for granting access for documentation?
https://dash.readme.io/project/eclipse-che/v4.0/docs/usage

I am not also able to access the ARTIK IDE related page. while trying to access the webpage below it says access denied

https://dash.readme.io/project/eclipse-che/v5.0/docs/samsung-artik-ide-getting-started-mac-linux

please provide me access.


regards
Vijay

**Comment by ghost** [comment]
@vijaypa1 I think you need this link https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started

**Comment by vijaypa1** [comment]
@eivantsov, Thanks.  I had started from that page, and I accessed a link in that page (for mac setup) and the access was denied. 

> Mac and Linux users use this page.
this was pointing to https://dash.readme.io/project/eclipse-che/v5.0/docs/samsung-artik-ide-getting-started-mac-linux and I am not able to access it.
thanks in advance

**Comment by vijaypa1** [comment]
@TylerJewell @eivantsov , the documentation link for mac and linux is broken(under section 'Getting started - Windows'_.
 can this be fixed?

**Comment by ghost** [comment]
https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started-mac-linux

Basically, you need to run:

`docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v $location:/data codenvy/artik-cli start`

where `$location` is a local directory on your Mac where you want to store config and data for Artik IDE.

**Comment by vijaypa1** [comment]
@eivantsov , Thank you . I could launch the Che IDE and cross compile for ARM architecture.
