### ISSUE TITLE
che-sample-plugin-serverservice-server server not responding  

### ISSUE THREAD

**Issue by mutturajKaralatti** [eclipse-che/che#3634]
che-sample-plugin-serverservice-server server not responding. che-sample-plugin-serverservice-ide is able to send the request with url Ex: **http://172.17.0.1:32778/api/hello/xyz**. but getting reply as **"There is no any resources matched to request path /hello/xyz"**

I am referring https://eclipse-che.readme.io/docs/serverworkspace-access for enabling this plugin.
and following bellow procedure.

#### 1- Link to IDE assembly
The plugin-serverservice has both part, an IDE extension and a server extension. You have to introduce the extension as a dependency in `/che/assembly/assembly-ide-war/pom.xml`. 
Add: 
```XML
...
<dependency>
  <groupId>org.eclipse.che.sample</groupId>
  <artifactId>che-sample-plugin-serverservice-ide</artifactId>
</dependency>
...
```
You can insert the dependency anywhere in the list. After you have inserted it, run `mvn sortpom:sort` and maven will order the `pom.xml` for you.

#### 2- Link to WS-Master assembly
The plugin-serverservice has a server side part. You have to introduce the extension as a dependency in `/che/assembly/assembly-wsmaster-war/pom.xml`. 
Add: 
```XML
...
<dependency>
  <groupId>org.eclipse.che.sample</groupId>
  <artifactId>che-sample-plugin-serverservice-server</artifactId>
</dependency>
...
```
You can insert the dependency anywhere in the list. After you have inserted it, run `mvn sortpom:sort` and maven will order the pom.xml for you.

#### 3- Register dependency to the GWT application
Link the GUI extension into the GWT app. You will add an `<inherits>` tag to the module definition. The name of the GWT extension is derived from the direction + package structure given to the GWT module defined in our extension.
In: `assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml`

Add:
```XML
...
<inherits name='org.eclipse.che.plugin.serverservice.ServerService'/>
...
```
#### 4- Rebuild Eclipse Che
```Shell
# Create a new Che server web app that includes your Che server extension
cd che/assembly/assembly-wsmaster-war
mvn clean install

# Build a new IDE.war
# This IDE web app will be bundled into the assembly
cd che/assembly/assembly-ide-war
mvn clean install

# Create a new Che assembly that includes all new server- and client-side extensions
cd assembly/assembly-main
mvn clean install
#

**Reproduction Steps:**
1. Enable the plugin and build
2. launch eclipse che
3. right click on any projects created in eclipse che -> MyAction 

**Expected behavior:**
 service accepts a String {name} and responds with "Hello {name} !".

**Observed behavior:**
There is no any resources matched to request path /hello/{name}


Che version: 5.0.0-M8  
OS and version:  Ubuntu 14.04.5 LTS
Docker version: Docker version 1.12.5
Che install: Docker container   

**Additional information:**


* Problem started happening recently, didn't happen in an older version of Che: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by ghost** [comment]
@mutturajKaralatti how do you then run your Che instance? Can you share the syntax please?

**Comment by ghost** [comment]
Just fyi, you should have deployed your service with workspace agent, not ws-master if you want to see IDE-srver side communication in action.

**Comment by mutturajKaralatti** [comment]
@eivantsov  i am using bellow command to run Che instance.

sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      -e CHE_ASSEMBLY=/home/alethea/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT/eclipse-che-5.0.0-SNAPSHOT eclipse/che-launcher start

**syntax**
sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      -e CHE_ASSEMBLY=<path to che local binaries> eclipse/che-launcher start

How can i check whether service is deployed as agent or ws-master?

**Comment by ghost** [comment]
@mutturajKaralatti can you try it this way?

`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/alethea/che:/repo -v /home/alethea/che-conf:/data eclipse/che-cli:nightly start`

When the server is up go to `$IP:8080/hello/Hello`

**Comment by mutturajKaralatti** [comment]
@eivantsov 

With the above method its running the default binaries by pulling from githubserver(not taking local build binaries) where **che-sample-plugin-serverservice-server** plugin is not enabled.
And once after trying with your way even the older method it is not taking local build binaries.  i am unable run the locally built binaries.

**Comment by ghost** [comment]
@mutturajKaralatti can you share run syntax that you used and the output that you have got?

**Comment by mutturajKaralatti** [comment]
@eivantsov  I am sharing the CLI out put.

root@alepc26:/home/alethea# 
root@alepc26:/home/alethea# 
root@alepc26:/home/alethea#  sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock  -v /home/alethea/Muttu/Jan_2/che:/repo   -v /home/alethea/che-conf:/data  eclipse/che-cli:nightly 	start

WARNING: No swap limit support
WARN: Did not detect TTY - interactive mode disabled
INFO: (che cli): :/repo mounted - using binaries from your local repository
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
WARN: There is a newer eclipse/che-cli:nightly image on DockerHub.
WARN: (che init): 'nightly' installations cannot be upgraded to non-nightly versions
INFO: (che cli): Checking registry for version 'nightly' images
INFO: (che download): Checking for image 'puppet/puppet-agent-alpine:4.6.2'...found
INFO: (che download): Checking for image 'registry:2.5.0'...found
INFO: (che download): Checking for image 'eclipse/che-init:nightly'...found
INFO: (che download): Checking for image 'eclipse/che-server:nightly'...found
INFO: (che init): Installing configuration and bootstrap variables:
INFO: (che init):   CHE_HOST=10.1.1.133
INFO: (che init):   CHE_VERSION=nightly
INFO: (che init):   CHE_CONFIG=/home/alethea/che-conf
INFO: (che init):   CHE_INSTANCE=/home/alethea/che-conf/instance
INFO: (che init):   CHE_DEVELOPMENT_REPO=/home/alethea/Muttu/Jan_2/che
INFO: (che init):   CHE_ASSEMBLY=/home/alethea/che-conf/instance/dev/che-tomcat
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che config): Copying local binaries to /home/alethea/che-conf/instance/dev...
INFO: (che start): Preflight checks
         port 8080 (http):       [AVAILABLE] 

INFO: (che start): Starting containers...
INFO: (che start): Services booting...
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Booted and reachable
INFO: (che start): Ver: nightly
INFO: (che start): Use: http://10.1.1.133:8080
INFO: (che start): API: http://10.1.1.133:8080/swagger
root@alepc26:/home/alethea# 


**Note:** 
1. **/home/alethea/Muttu/Jan_2/che**  is Path che repository 
2. **/home/alethea/Muttu/Jan_2/che/assembly/assembly-main/target/eclipse-che-5.0.0-SNAPSHOT** contains local binaries.

**Comment by ghost** [comment]
Yes, your local binaries are properly mounted. 

`http://10.1.1.133:8080/api/hello/Eclipse`

Does it return anything?

**Comment by mutturajKaralatti** [comment]
@eivantsov  Its returning **There is no any resources matched to request path /hello/Eclipse**

In the same build i have added a Sample-HelloWorld plugin too. It should pop-up a **Helloworld** notification under the Events. But i don't see any notifications over there. with this observation i am doubting whether it is  mounting local binaries or not.

**Comment by ghost** [comment]
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/alethea/Muttu/Jan_2/che:/repo -v /home/alethea/che-conf:/data eclipse/che-cli:nightly start --pull --debug`

Can you give it a shot this way? I have double checked and can see this service.

![image](https://cloud.githubusercontent.com/assets/5337267/21838378/50c041fe-d7da-11e6-96c1-38e2823ea5fd.png)

**Comment by mutturajKaralatti** [comment]
@eivantsov  
1.  I tried the same binaries on different the machine(PC2) with my may of running the che instance. and its working fine. Thank you.

![screenshot from 2017-01-11 12 29 13](https://cloud.githubusercontent.com/assets/24957555/21839694/2bdb5ff2-d7ff-11e6-9270-5d06a12e543c.png)

2. But when I click on **My Action** it is not working. I have added some notifications in plugin when getHello() method is failed. There I am printing the url used by the client to send the request. I am sharing a shot when **My Action** is clicked. FYI I am collecting the url from (appContext.getDevMachine().getWsAgentBaseUrl()); 


![screenshot from 2017-01-11 12 52 53](https://cloud.githubusercontent.com/assets/24957555/21839727/520425a6-d7ff-11e6-9263-817996c4a5d9.png)


![screenshot from 2017-01-11 12 55 04](https://cloud.githubusercontent.com/assets/24957555/21839731/54cb184e-d7ff-11e6-9114-994b3e918a45.png)

Here the difference observed is the port number. its using 32770 instead of 8080.

3. But still on old machine (PC1) it is not mounting the local binaries.

**Comment by ghost** [comment]
@mutturajKaralatti you need to add your plugin to workspace agent, not workspace master, i.e. your dependency should be added to this pom https://github.com/eclipse/che/blob/master/assembly/assembly-wsagent-war/pom.xml

**Comment by mutturajKaralatti** [comment]
@eivantsov  I tried following combinations.

1.  Adding plug-in dependency  in wsagent instead of wamaster.
- Same behaviour with **My Action** (Not working)
- Even http://10.1.1.133:8080/api/hello/Eclipse is not working
![screenshot from 2017-01-11 15 26 45](https://cloud.githubusercontent.com/assets/24957555/21847466/1414ff86-d822-11e6-9ef3-18a46a22b817.png)


2.  Adding plug-in dependency  in both wsagent and wamaster.
- As good as adding dependency only in wamaster.
- Same behaviour with **My Action** (Not working)
- http://10.1.1.133:8080/api/hello/Eclipse is working

![screenshot from 2017-01-11 17 20 06](https://cloud.githubusercontent.com/assets/24957555/21847552/6fdcd2b2-d822-11e6-8a71-573e0b2e6ec4.png)

**Comment by vinokurig** [comment]
@mutturajKaralatti Can you show the source code of your plugin?

**Comment by ghost** [comment]
Closing the issue. @mutturajKaralatti feel free to reopen if the problem persists.

**Comment by ghost** [comment]
@eivantsov I have exactly the same issue, although I am running with the che.sh bash script.
The source code, is the one provided in https://github.com/eclipse/che/tree/master/samples/sample-plugin-serverservice.

I am using CentOs 7
And eclipseChe 5.0.1

I have tried running with Docker with this command
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/ndjuric/eclipseCheTest:/repo -v /home/ndjuric/eclipseCheTest:/data eclipse/che-cli:5.0.1 start --pull --debug

 but no luck.

Any help?

**Comment by ghost** [comment]
@grunf93 please try to build and run with 5.3.0 tag

**Comment by ghost** [comment]
I tried but unfortunately now it doesn't even recognize my samples? 

I can locate sample jar files in 
./assembly-ide-war/target/assembly-ide-war-5.3.0/WEB-INF/lib/che-sample-plugin-serverservice-ide-5.3.0.jar
./assembly-wsagent-war/target/assembly-wsagent-war-5.3.0/WEB-INF/lib/che-sample-plugin-serverservice-server-5.3.0.jar

This is the docker command I used to run it
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/ndjuric/che5/che:/data eclipse/che start

**Comment by ghost** [comment]
@grunf93 you need to mount your local che repo into :/repo in the container.

`-v $path_to_repo:/repo`

**Comment by ghost** [comment]
Thanks. For now, it works. 
But there is another problem at branch tagged with 5.3.0 with this script
https://github.com/eclipse/che/blob/5.3.0/dockerfiles/base/scripts/base/startup_04_pre_cli_init.sh

Command "compare_versions" does not exist?

**Comment by TylerJewell** [comment]
Wipe all your images and then start again.

**Comment by TylerJewell** [comment]
@grunf93 - when you are working in `:/repo` mode, it sources not just your binaries from the repo, but also the scripts for the CLI itself.  If the version / branch that you have open for your repo mount differs from the version of hte CLI image you are running then bad things will happen, just like what you saw.

So - make sure your images are fresh.  And then you can add `--skip:scripts` to the command line to have repo mode skip sourcing scirpts from the repository and only use it for the binaries.

**Comment by ghost** [comment]
Hi @TylerJewell, thanks I already made it work, but your explanation how and why things work is great!

I made it work by using the startup_04_pre_cli_init.sh script from the 5.3.1 tag on the branch. As I said the one from 5.3.0 doesn't have function _compare_versions_ and that's the next error I got from docker start.  I'd be glad if you could check the issue question I opened with tag #4220
