### ISSUE TITLE
Remove unnecessary files from workspace snapshots

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3637]
When Che saves snapshot it includes agents binaries into snapshot.
This means that we can speed up creation of snapshots by excluding these files from snapshot somehow.
Since snapshotting doesn't respect .gitignore or any other rules to reduce snapshot size in can take a lot of time to snapshot workspace with big amount of binaries. And some agents like ws-agent can be space-consuming. Also since snapshots are layered entity snapshoting of same WS will constantly slowing down.

**Reproduction Steps:**

1. Start WS.
2. Save WS into snapshot.
3. Get snapshot data from SQL DB.
4. Execute 
```
docker run -it <registry:port/repo_of_snapshot> bash -c ls ~/che
```

**Expected behavior:**

Nothing is printed or error message that ~/che doesn't exist.

**Observed behavior:**

Something like `terminal  websocket-terminal-linux_amd64.tar.gz  ws-agent` is printed.

**Che version:**    5.0.0-Snapshot
**OS and version:** Ubuntu 16.04
**Docker version:** 1.12.5
**Che install:**    Docker container

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by gazarenkov** [comment]
1/ What is the way to exclude files?
2/ Do you think it suits expectations to have "exactly the same machine" after restore?

**Comment by garagatyi** [comment]
1. Add environment variable that returns temp storage for agent binaries that won't be stored into snapshot. Then each agent can be reworked to use this variable. If agent uses this variable it doesn't litter container snapshot with its binaries.
2. No, only binaries of agents that respect that mechanism won't be at at restored container. Other new/changed files will be present.

**Comment by garagatyi** [comment]
We decided to abandon snapshots support in Che 6 in #6213. So closing this issue
