### ISSUE TITLE
[Docs] Intelij development setup section missing in help

### ISSUE THREAD

**Issue by wtrocki** [eclipse-che/che#3642]
IDE setup section in help is mentioning intelij support, but help refers to missing section:
https://eclipse-che.readme.io/v5.0/docs/setup-che-workspace#setup-the-intellij-ide

h3. Steps to reproduce:
1. Go to https://eclipse-che.readme.io/v5.0/docs/setup-che-workspace
2. Select Intelij
![screen shot 2017-01-06 at 11 27 04 pm](https://cloud.githubusercontent.com/assets/981838/21736319/c01b7170-d467-11e6-8168-4087423be3e8.png)

h3. Expected behavior 

Link should refer to some section or it should be removed.

**Comment by TylerJewell** [comment]
Hi!  Can you tell us how you found that docs page?  We (today) have been switching over from README over to our own self-hosted Jekyll site.  So if you look - the page is now here, and there is Jekyll docs with the proper link:

https://www.eclipse.org/che/docs/plugins/setup-che-workspace/index.html#gwt-super-dev-mode-for-intellij

**Comment by wtrocki** [comment]
I have been reading this page for couple days and have it opened in my browser. In new page everything works. Thanks for quick response! Closing ticket :)
