### ISSUE TITLE
Problem in folder (Package) with name "api" 

### ISSUE THREAD

**Issue by pabversist** [eclipse-che/che#3644]
Hi
I have a problem in SaaS version of eclipse che.
when i create a folder ( in my case java package) in my project , eclipse che can't work with it ... it can't create file , can't open it and when i create a file using terminal inside this folder, eclipse che don't recognize it...

**Comment by TylerJewell** [comment]
This was a known issue that was solved in the 5.0.0 release that was made last week.  You can install a new version of Che based upon this release with `docker run eclipse/che start`.  The SaaS and cloud versions with Bitnami will be updated to this new version in a couple weeks.
