### ISSUE TITLE
CHE-503 Add ability to edit and save file content in compare widget

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#365]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-503
Reporter:  Igor' Vinokur
Description: 
1 Make the "yours" part of git compare window editable
2 Add "Save" button to git compare window that will save edited content to compared file

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/142c91207f0dea60476df55283cd4b6201923fc0
