### ISSUE TITLE
CLI must check if all containers started properly

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#3655]
today CLI checks only is api server is available, but sometimes some containers may not start this usually happen due to docker bugs like after docker engine restart some container unable to start and the only way to make it work remove stopped container and restart. There is a lot of other possible scenarios where some container may not start so we must check every single container is it at least running container.

here is command how to do that check with inspect this command return `true` or `false`
```docker inspect -f {{.State.Running}} $CONTAINER_ID```

so all we neeed to do is to iterate across all codenvy containers and check if all is in running state.

here is a command how to get all existed (even stopped) codenvy containers:
```docker ps -qa --filter="name=codenvy_*"```

but that approach could be better if we will find a way how to do that check by container name because I think we could have situation where container was not created so we will not have `container id` to check. (Im not sure if that situation is possible)

**Comment by riuvshin** [comment]
So I think algorithm should be like that:

for each image from `images` file do:

1) get `container_id=$(docker ps -aq --filter=ancestor=$IMAGE_NAME)`
2) do check is `$container_id` is not empty, if it is empty we fail which means container didn't started due to some reason
3) do check is container running `docker inspect -f {{.State.Running}} $container_id` we ok if this return true, fail if false.


@benoitf wdyt?

**Comment by benoitf** [comment]
yeah I've understood the goal

**Comment by benoitf** [comment]
@riuvshin 
so after analyzing the issue I think your issue is only when docker compose is not able to be started the first time.
If docker compose successfully starts, then it is automatically restarting the containers 
and if che doesn't boot in the given amount of time, then we exit with an error


so I think we only need to check docker compose boot sequence. For now if there is a failure it silently exits

**Comment by benoitf** [comment]
https://github.com/eclipse/che/pull/3731
