### ISSUE TITLE
Delete GDB Debug Configuration

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3659]
Cannot delete GDB debug configuration.

![issue](https://cloud.githubusercontent.com/assets/20580888/21829396/46eef9a6-d75b-11e6-9cc6-42747bdb73ad.gif)

**Reproduction Steps:**

**Che version:**    
Version :5.0.0 
Revision :b5a7d04ca23c83d4 
Build Time :2017-01-06 12:05:18

**OS and version:**    
WIndows 10

**Docker version:**    
docker info
Containers: 24
 Running: 2
 Paused: 0
 Stopped: 22
Images: 17
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 137
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: IRLX:O3NP:SEW7:WI2K:HUWE:6ELL:RAE6:2F3F:MTGZ:CPUT:F6ZH:P27J
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 64
 System Time: 2017-01-10T23:35:03.831270894Z
 EventsListeners: 1
Username: --
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

**Comment by dmytro-ndp** [comment]
This bug is still actual for Che 5.5.0.

**Comment by dmytro-ndp** [comment]
There is selenium test [CppProjectDebuggingTest.shouldRemoveGdbDebugConfig()](https://github.com/codenvy/qa/blob/8f93e2089fa067ecea364c040843ad08bd2a81ac/src/test/java/com/codenvy/ide/debugger/CppProjectDebuggingTest.java#L145) which should be enabled after this bug is successfully fixed.
