### ISSUE TITLE
che project maven install error

### ISSUE THREAD

**Issue by blingeee** [eclipse-che/che#366]
l inserted 'mvn clean install' in terminal for building che project.
but error occurred like below..

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project che-core-api-machine: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ubuntu/che/core/platform-api/che-core-api-machine/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :che-core-api-machine

```

**Comment by ddementieva** [comment]
Can you share an entire build log with us?

**Comment by ghost** [comment]
@blingeee can you try it with a current master of the latest release?

**Comment by bepurushoth** [comment]
I have the same issue. Tried with tag 4.0.0-RC6. Any solution to this issue?

**Comment by bepurushoth** [comment]
tried with the master also and got the same issue

**Comment by ghost** [comment]
@bepurushoth  What is your OS and Maven version?

**Comment by bepurushoth** [comment]
Windows 10 64 bit and Maven version is apache-maven-3.3.9

logs below:
Running TestSuite
Configuring TestNG with: TestNG652Configurator
2016-02-25 15:52:29,581[main]             [INFO ] [org.eclipse.jetty.util.log 186]      - Logging initialized @1251ms
2016-02-25 15:52:29,699[main]             [INFO ] [o.eclipse.jetty.server.Server 345]   - jetty-9.3.1.v20150714
2016-02-25 15:52:29,864[main]             [INFO ] [o.e.j.s.handler.ContextHandler 737]  - Started o.e.j.s.ServletContextHandler@7cc0cdad{/,null,AVAILABLE}
2016-02-25 15:52:29,936[main]             [INFO ] [o.e.j.server.ServerConnector 270]    - Started ServerConnector@7c6908d7{HTTP/1.1,[http/1.1]}{0.0.0.0:10162}
2016-02-25 15:52:29,936[main]             [INFO ] [o.eclipse.jetty.server.Server 397]   - Started @1611ms
2016-02-25 15:52:30,691[main]             [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = testWsId: env = testEnvName: machine = validMachineName]
2016-02-25 15:52:30,792[main]             [INFO ] [o.e.c.a.m.s.MachineManager 168]      - Machine [ws = testWsId: env = testEnvName: machine = validMachineName] was successfully created, its id is 'machineId'
2016-02-25 15:52:30,804[main]             [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = testWsId: env = testEnvName: machine = MachineName]
2016-02-25 15:52:30,815[main]             [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = testWsId: env = testEnvName: machine = MachineName]
2016-02-25 15:52:30,822[main]             [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Creating machine [ws = wsId: env = env1: machine = @name!]
2016-02-25 15:52:30,831[main]             [WARN ] [o.e.j.s.handler.ContextHandler 1308] - o.e.j.s.h.ContextHandler@696f0212{/,null,null} contextPath ends with /
2016-02-25 15:52:30,844[pool-5-thread-1]  [INFO ] [o.eclipse.jetty.server.Server 345]   - jetty-9.3.1.v20150714
2016-02-25 15:52:30,845[pool-5-thread-1]  [INFO ] [o.e.j.s.handler.ContextHandler 737]  - Started o.e.j.s.h.ContextHandler@696f0212{/che/api/ext/api/workspace123/java,null,AVAILABLE}
2016-02-25 15:52:30,849[pool-5-thread-1]  [INFO ] [o.e.j.server.ServerConnector 270]    - Started ServerConnector@27cf8da8{HTTP/1.1,[http/1.1]}{0.0.0.0:61119}
2016-02-25 15:52:30,849[pool-5-thread-1]  [INFO ] [o.eclipse.jetty.server.Server 397]   - Started @2524ms
2016-02-25 15:52:31,600[main]             [WARN ] [o.e.j.s.handler.ContextHandler 1308] - o.e.j.s.h.ContextHandler@696f0212{/che/api/ext/api/workspace123/java,null,AVAILABLE} contextPath ends with /
2016-02-25 15:52:31,662[main]             [INFO ] [o.e.j.server.ServerConnector 310]    - Stopped ServerConnector@27cf8da8{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
2016-02-25 15:52:31,663[main]             [INFO ] [o.e.j.s.handler.ContextHandler 847]  - Stopped o.e.j.s.h.ContextHandler@696f0212{/che/api/ext/api/workspace123/java,null,UNAVAILABLE}
{"name":"name","permissions":{"groups":[{"name":"public","acl":["read","search"]}],"users":{}},"id":"recipe2d0ixos98sa5ryxt","type":"docker","script":"FROM ubuntu\n","creator":"user123","tags":[],"links":[{"method":"GET","parameters":[],"rel":"get recipe script","href":"http://localhost:10162/rest/private/recipe/recipe2d0ixos98sa5ryxt/script","produces":"text/plain"},{"method":"DELETE","parameters":[],"rel":"remove recipe","href":"http://localhost:10162/rest/private/recipe/recipe2d0ixos98sa5ryxt"}]}
[{"id":"id1","type":"docker","script":"script1 content","creator":"user123","tags":[],"links":[{"method":"GET","parameters":[],"rel":"get recipe script","href":"http://localhost:10162/rest/private/recipe/id1/script","produces":"text/plain"},{"method":"DELETE","parameters":[],"rel":"remove recipe","href":"http://localhost:10162/rest/private/recipe/id1"}]},{"id":"id2","type":"docker","script":"script2 content","creator":"user123","tags":[],"links":[{"method":"GET","parameters":[],"rel":"get recipe script","href":"http://localhost:10162/rest/private/recipe/id2/script","produces":"text/plain"},{"method":"DELETE","parameters":[],"rel":"remove recipe","href":"http://localhost:10162/rest/private/recipe/id2"}]}]
{"name":"name","permissions":{"groups":[],"users":{"user123":["read","write"]}},"id":"recipe123","type":"docker","script":"FROM ubuntu\n","creator":"someone2","tags":["java","mognodb"],"links":[{"method":"GET","parameters":[],"rel":"get recipe script","href":"http://localhost:10162/rest/private/recipe/recipe123/script","produces":"text/plain"},{"method":"DELETE","parameters":[],"rel":"remove recipe","href":"http://localhost:10162/rest/private/recipe/recipe123"}]}
FROM ubuntu

[{"id":"id1","type":"docker","script":"script1 content","creator":"user123","tags":["java"],"links":[{"method":"GET","parameters":[],"rel":"get recipe script","href":"http://localhost:10162/rest/private/recipe/id1/script","produces":"text/plain"},{"method":"DELETE","parameters":[],"rel":"remove recipe","href":"http://localhost:10162/rest/private/recipe/id1"}]},{"id":"id2","type":"docker","script":"script2 content","creator":"user123","tags":["java","mongodb"],"links":[{"method":"GET","parameters":[],"rel":"get recipe script","href":"http://localhost:10162/rest/private/recipe/id2/script","produces":"text/plain"},{"method":"DELETE","parameters":[],"rel":"remove recipe","href":"http://localhost:10162/rest/private/recipe/id2"}]}]
{"name":"name","permissions":{"groups":[{"name":"public","acl":["read"]}],"users":{}},"id":"recipeteg9001vrfiv5u07","type":"docker","script":"FROM ubuntu\n","creator":"user123","tags":["java","mongo"],"links":[{"method":"GET","parameters":[],"rel":"get recipe script","href":"http://localhost:10162/rest/private/recipe/recipeteg9001vrfiv5u07/script","produces":"text/plain"},{"method":"DELETE","parameters":[],"rel":"remove recipe","href":"http://localhost:10162/rest/private/recipe/recipeteg9001vrfiv5u07"}]}
{"message":"User user123 doesn't have access to use 'public: search' permission"}
{"message":"User user123 doesn't have access to recipe id"}
{"message":"Recipe script required"}
{"message":"Recipe type required"}
{"message":"Recipe required"}
{"message":"Recipe name required"}
{"message":"User user123 doesn't have access to update recipe id"}
{"message":"User user123 doesn't have access to update recipe id permissions"}
{"message":"User user123 doesn't have access to recipe recipe123"}
2016-02-25 15:52:35,472[main]             [INFO ] [o.e.j.server.ServerConnector 310]    - Stopped ServerConnector@7c6908d7{HTTP/1.1,[http/1.1]}{0.0.0.0:10162}
2016-02-25 15:52:35,478[main]             [INFO ] [o.e.j.s.handler.ContextHandler 847]  - Stopped o.e.j.s.ServletContextHandler@7cc0cdad{/,null,UNAVAILABLE}
Tests run: 60, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 8.403 sec <<< FAILURE! - in TestSuite
shouldCallWsAgentLauncherAfterDevMachineStart(org.eclipse.che.api.machine.server.MachineManagerTest)  Time elapsed: 0.009 sec  <<< FAILURE!
org.eclipse.che.api.machine.server.exception.MachineException: Can't create folder for the logs of machine
        at org.eclipse.che.api.machine.server.MachineManager.createMachineLogsDir(MachineManager.java:869)
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:324)
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:167)
        at org.eclipse.che.api.machine.server.MachineManagerTest.shouldCallWsAgentLauncherAfterDevMachineStart(MachineManagerTest.java:155)

shouldNotCallWsAgentLauncherAfterNonDevMachineStart(org.eclipse.che.api.machine.server.MachineManagerTest)  Time elapsed: 0.004 sec  <<< FAILURE!
org.eclipse.che.api.machine.server.exception.MachineException: Can't create folder for the logs of machine
        at org.eclipse.che.api.machine.server.MachineManager.createMachineLogsDir(MachineManager.java:869)
        at org.eclipse.che.api.machine.server.MachineManager.createMachine(MachineManager.java:324)
        at org.eclipse.che.api.machine.server.MachineManager.createMachineSync(MachineManager.java:167)
        at org.eclipse.che.api.machine.server.MachineManagerTest.shouldNotCallWsAgentLauncherAfterNonDevMachineStart(MachineManagerTest.java:164)

shouldLoadPredefinedRecipesFromValidJson(org.eclipse.che.api.machine.server.recipe.RecipeLoaderTest)  Time elapsed: 0.006 sec  <<< FAILURE!
org.eclipse.che.api.core.ServerException: Failed to get recipes from specified path /A:/Program%20Files/Eclipse_CHE/Master/che/core/platform-api/che-core-api-machine/target/test-classes/recipes.json
        at org.eclipse.che.api.machine.server.recipe.RecipeLoader.getResource(RecipeLoader.java:122)
        at org.eclipse.che.api.machine.server.recipe.RecipeLoader.loadRecipes(RecipeLoader.java:98)
        at org.eclipse.che.api.machine.server.recipe.RecipeLoader.start(RecipeLoader.java:73)
        at org.eclipse.che.api.machine.server.recipe.RecipeLoaderTest.shouldLoadPredefinedRecipesFromValidJson(RecipeLoaderTest.java:48)

shouldThrowExceptionWhenImpossibleToStoreRecipes(org.eclipse.che.api.machine.server.recipe.RecipeLoaderTest)  Time elapsed: 0.002 sec  <<< FAILURE!
org.testng.TestException:
The exception was thrown with the wrong message: expected "Failed to store recipe.*" but got "Failed to get recipes from specified path /A:/Program%20Files/Eclipse_CHE/Master/che/core/platform-api/che-core-api-machine/target/test-classes/recipes.json"
        at org.eclipse.che.api.machine.server.recipe.RecipeLoader.getResource(RecipeLoader.java:122)
        at org.eclipse.che.api.machine.server.recipe.RecipeLoader.loadRecipes(RecipeLoader.java:98)
        at org.eclipse.che.api.machine.server.recipe.RecipeLoader.start(RecipeLoader.java:73)
        at org.eclipse.che.api.machine.server.recipe.RecipeLoaderTest.shouldThrowExceptionWhenImpossibleToStoreRecipes(RecipeLoaderTest.java:72)

Results :

Failed tests:
  MachineManagerTest.shouldCallWsAgentLauncherAfterDevMachineStart:155 » Machine
  MachineManagerTest.shouldNotCallWsAgentLauncherAfterNonDevMachineStart:164 » Machine
  RecipeLoaderTest.shouldLoadPredefinedRecipesFromValidJson:48 » Server Failed t...
  RecipeLoaderTest.shouldThrowExceptionWhenImpossibleToStoreRecipes » Test
The ...

Tests run: 60, Failures: 4, Errors: 0, Skipped: 0

**Comment by ghost** [comment]
Confirmed on Win 10. Investigating.

**Comment by ghost** [comment]
-DskipTests will fix it.

Or you may build the assembly module only.

**Comment by bepurushoth** [comment]
it still failed at  [INFO] Che Core :: IDE :: App ............................. FAILURE [ 23.378 s] in version 4.0.0-RC6

A:\Program Files\Eclipse_CHE\4.0.0-RC6\che\core\ide\che-core-ide-app\src\test\java\org\eclipse\che\ide\part\explorer\project\synchronize\ProjectConfigSynchronizationListenerTest.java:302: warning: [deprecation] updateProject(String,String,ProjectConfigDto,AsyncRequestCallback<ProjectConfigDto>) in ProjectServiceClient has been deprecated
        verify(projectService).updateProject(eq(WORKSPACE_ID), anyString(), eq(projectConfig), Matchers.<AsyncRequestCallback>anyObject());
                              ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
18 warnings
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ che-core-ide-app ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ che-core-ide-app ---
[INFO] Building jar: A:\Program Files\Eclipse_CHE\4.0.0-RC6\che\core\ide\che-core-ide-app\target\che-core-ide-app-4.0.0-RC6.jar
[INFO]
[INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources) @ che-core-ide-app ---
[INFO] Building jar: A:\Program Files\Eclipse_CHE\4.0.0-RC6\che\core\ide\che-core-ide-app\target\che-core-ide-app-4.0.0-RC6-sources.jar
[INFO]
[INFO] --- maven-dependency-plugin:2.10:analyze-only (analyze) @ che-core-ide-app ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.eclipse.che.core:che-core-client-gwt-analytics:jar:4.0.0-RC6:compile
[WARNING]    org.eclipse.che.core:che-core-client-gwt-core:jar:4.0.0-RC6:compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Che Parent ......................................... SUCCESS [ 12.731 s]
[INFO] Che Core Parent .................................... SUCCESS [  0.209 s]
[INFO] Che Core :: Commons :: Parent ...................... SUCCESS [  0.172 s]
[INFO] Che Core :: Commons :: Annotations ................. SUCCESS [  7.491 s]
[INFO] Che Core :: Commons :: Java API extension classes .. SUCCESS [ 10.901 s]
[INFO] Che Core :: Commons :: Dependency Injecting ........ SUCCESS [  8.738 s]
[INFO] Che Core :: Commons :: Environment ................. SUCCESS [  5.410 s]
[INFO] Che Core :: Commons :: Json helpers ................ SUCCESS [  5.565 s]
[INFO] Che Core :: Commons :: XML ......................... SUCCESS [  8.352 s]
[INFO] Che Core :: Commons :: Scheduler service ........... SUCCESS [  8.662 s]
[INFO] Che Core :: Commons :: GWT ......................... SUCCESS [ 24.877 s]
[INFO] Che Core :: Commons :: Utilities for tests ......... SUCCESS [  3.938 s]
[INFO] Che Core :: API :: Model ........................... SUCCESS [  4.546 s]
[INFO] Che Core :: API :: Parent .......................... SUCCESS [  0.134 s]
[INFO] Che Core :: API :: DTO ............................. SUCCESS [ 14.374 s]
[INFO] Che Core :: API :: DTO Maven Plugin ................ SUCCESS [  8.253 s]
[INFO] Che Core :: API :: Core ............................ SUCCESS [ 18.440 s]
[INFO] Che Core :: API :: Virtual Filesystem .............. SUCCESS [ 19.630 s]
[INFO] Che Core :: API :: Machine ......................... SUCCESS [ 18.095 s]
[INFO] Che Core :: API :: Workspace ....................... SUCCESS [ 16.898 s]
[INFO] Che Core :: API :: User ............................ SUCCESS [  9.169 s]
[INFO] Che Core :: API :: Project ......................... SUCCESS [ 18.201 s]
[INFO] Che Core :: API :: Account ......................... SUCCESS [ 10.080 s]
[INFO] Che Core :: API :: Factory ......................... SUCCESS [ 11.999 s]
[INFO] Che Core :: API :: Analytics ....................... SUCCESS [  8.870 s]
[INFO] Che Core :: API :: Authentication .................. SUCCESS [ 15.818 s]
[INFO] Che Core :: Virtual File System (Deprecated) ....... SUCCESS [ 11.834 s]
[INFO] Che Core :: API :: Git ............................. SUCCESS [ 19.137 s]
[INFO] Che Core :: API :: SSH ............................. SUCCESS [  8.601 s]
[INFO] Che Core :: API :: Local Infrastructure ............ SUCCESS [  8.265 s]
[INFO] Che Core API :: Client GWT :: Parent ............... SUCCESS [  0.125 s]
[INFO] Che Core API :: Client GWT :: Core ................. SUCCESS [  8.469 s]
[INFO] Che Core API :: Client GWT :: Analytics ............ SUCCESS [  8.208 s]
[INFO] Che Core API :: Client GWT :: Auth ................. SUCCESS [  7.265 s]
[INFO] Che Core API :: Client GWT :: User ................. SUCCESS [  9.019 s]
[INFO] Che Core API :: Client GWT :: Machine .............. SUCCESS [ 16.037 s]
[INFO] Che Core API :: Client GWT :: Workspace ............ SUCCESS [ 17.327 s]
[INFO] Che Core API :: Client GWT :: Account .............. SUCCESS [  8.012 s]
[INFO] Che Core API :: Client GWT :: Project .............. SUCCESS [ 15.260 s]
[INFO] Che Core API :: Client GWT :: Virtual Filesystem ... SUCCESS [ 10.486 s]
[INFO] Che Core API :: Client GWT :: Factory .............. SUCCESS [ 12.184 s]
[INFO] Che Core API :: Client GWT :: GIT .................. SUCCESS [ 21.024 s]
[INFO] Che Core API :: Client GWT :: SSH .................. SUCCESS [ 10.581 s]
[INFO] Che Core :: IDE .................................... SUCCESS [  0.159 s]
[INFO] Che Core :: IDE :: API ............................. SUCCESS [ 21.424 s]
[INFO] Che Core :: IDE :: Generators ...................... SUCCESS [  8.371 s]
[INFO] Che Core :: IDE :: UI .............................. SUCCESS [ 18.137 s]
[INFO] Che Core :: IDE :: App ............................. FAILURE [ 23.378 s]
[INFO] Che Core :: IDE :: JsEditor ........................ SKIPPED
[INFO] Che Core :: IDE :: TEMPLATES ....................... SKIPPED
[INFO] Che Core :: IDE :: STACKS .......................... SKIPPED
[INFO] Che Core :: Git Impl Native ........................ SKIPPED
[INFO] Che Plugin :: Parent ............................... SKIPPED
[INFO] Che Plugin :: Help :: Parent ....................... SKIPPED
[INFO] Che Plugin :: Help :: Client ....................... SKIPPED
[INFO] Che Plugin :: Docker :: Parent ..................... SKIPPED
[INFO] Che Plugin :: Docker :: Docker Client .............. SKIPPED
[INFO] Che Plugin :: Docker :: Machine .................... SKIPPED
[INFO] Che Plugin :: Docker :: Docker Ext ................. SKIPPED
[INFO] Che Plugin :: Web :: Parent ........................ SKIPPED
[INFO] Che Plugin :: Web :: File Types .................... SKIPPED
[INFO] Che Plugin :: Orion :: Parent ...................... SKIPPED
[INFO] Che Plugin :: Orion :: Editor ...................... SKIPPED
[INFO] Che Plugin :: Machine :: Parent .................... SKIPPED
[INFO] Che Plugin :: Machine .............................. SKIPPED
[INFO] che-plugin-machine-ext-server ...................... SKIPPED
[INFO] Che Plugin :: Machine :: SSH Client ................ SKIPPED
[INFO] Che Plugin :: Java :: Parent ....................... SKIPPED
[INFO] Che Plugin :: Java :: Maven Tools .................. SKIPPED
[INFO] Che Plugin :: Java :: Archetype Generator .......... SKIPPED
[INFO] Che Plugin :: Java :: Extension Java Shared ........ SKIPPED
[INFO] Che Plugin :: Orion :: Compare Widget .............. SKIPPED
[INFO] Che Plugin :: Java :: Extension Java Client ........ SKIPPED
[INFO] Che Plugin :: Java :: Extension Java Server ........ SKIPPED
[INFO] Che Plugin :: Java :: Extension JDT ................ SKIPPED
[INFO] Che Plugin :: Java :: Eclipse JDT Core Repack ...... SKIPPED
[INFO] Che Plugin :: Java :: org.eclipse.core.filesystem .. SKIPPED
[INFO] Che Plugin :: Java :: org.eclipse.core.resources ... SKIPPED
[INFO] Che Plugin :: Java :: org.eclipse.core.filebuffers . SKIPPED
[INFO] Che Plugin :: Java :: Eclipse JFace ................ SKIPPED
[INFO] Che Plugin :: Java :: Eclipse JFace Text ........... SKIPPED
[INFO] Che Plugin :: Java :: Eclipse LTK Refactoring ...... SKIPPED
[INFO] Che Plugin :: Java :: Eclipse Search ............... SKIPPED
[INFO] Che Plugin :: Java :: Eclipse IDE UI ............... SKIPPED
[INFO] Che Plugin :: Java :: Eclipse JDT UI ............... SKIPPED
[INFO] Che Plugin :: Java :: Extension Maven .............. SKIPPED
[INFO] Che Plugin :: Java :: Extension Machine JDT ........ SKIPPED
[INFO] Che Plugin :: Java :: Extension Debugger Java Shared SKIPPED
[INFO] Che Plugin :: Java :: Extension Debugger Java Server SKIPPED
[INFO] Che Plugin :: Java :: Extension Debugger Java Client SKIPPED
[INFO] Che Plugin :: SDK :: Parent ........................ SKIPPED
[INFO] Che Plugin :: SDK :: Plugins Development ........... SKIPPED
[INFO] Che Plugin :: SDK :: Local Env ..................... SKIPPED
[INFO] Che Plugin :: SDK :: Tools ......................... SKIPPED
[INFO] Che Plugin :: Git :: Parent ........................ SKIPPED
[INFO] Che Plugin :: Git :: Extension ..................... SKIPPED
[INFO] Che Plugin :: Git :: Che credential provider ....... SKIPPED
[INFO] Che Plugin :: GIT :: SSH Client .................... SKIPPED
[INFO] Che Plugin :: Github :: Parent ..................... SKIPPED
[INFO] Che Plugin :: Github :: OAuth2 ..................... SKIPPED
[INFO] Che Plugin :: Github :: Github ..................... SKIPPED
[INFO] Che Plugin :: Github :: Credential provider ........ SKIPPED
[INFO] Che Plugin :: Dashboard :: Parent .................. SKIPPED
[INFO] Che Plugin :: Dashboard :: Client .................. SKIPPED
[INFO] Che Plugin :: GWT :: Parent ........................ SKIPPED
[INFO] Che Plugin :: GWT .................................. SKIPPED
[INFO] Che Dashboard :: Web App ........................... SKIPPED
[INFO] Che IDE :: Parent .................................. SKIPPED
[INFO] Che Machine Plugins :: Packaging ................... SKIPPED
[INFO] Che Assembly Machine Plugins :: Server ............. SKIPPED
[INFO] Che IDE :: Compiling GWT Application ............... SKIPPED
[INFO] Che IDE :: Assemblies Tomcat ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:00 min
[INFO] Finished at: 2016-02-25T16:51:15+05:30
[INFO] Final Memory: 205M/1927M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze-only (analyze) on project che-core-ide-app: Dependency problems found -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :che-core-ide-app

**Comment by bepurushoth** [comment]
for one another colleague...  it got failed at orion editor
Environment: Windows 7 - 64 bit, Maven 3.3.9

**Comment by TylerJewell** [comment]
@bepurushoth - in 4.3 we released a new maven plugin and have made many fixes. This issue should be resolved now.
