### ISSUE TITLE
NodeJS Hello World Broke

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3660]
Could not run nodejs sample project "hello world" with ready to go stack NodeJS. Seems like the sample uses old node js syntax.
<img width="509" alt="issue" src="https://cloud.githubusercontent.com/assets/20580888/21830372/d77de274-d761-11e6-9388-672219900357.png">

Replacing with `var server = http.createServer(function (response) {` with `var server = http.createServer(function (request, response) {` fixes issue. Need to update nodejs project sample(s).

<img width="394" alt="issue2" src="https://cloud.githubusercontent.com/assets/20580888/21830457/6d35c570-d762-11e6-8760-b1fed349f4f1.png">

**Reproduction Steps:**
1. Run application
1. Click preview url link to view page
1. Error in console appears

**Che version:**    5.0.0

**Comment by ghost** [comment]
@JamesDrummond do you want to issue a PR?

This is the file with the default content - https://github.com/eclipse/che/blob/master/plugins/plugin-nodejs/che-plugin-nodejs-lang-server/src/main/resources/files/default_node_content

**Comment by JamesDrummond** [comment]
@eivantsov Yes. Thanks for letting me know the file location.

https://github.com/eclipse/che/pull/3678
