### ISSUE TITLE
Improve error message when starting nightly from a latest configuration

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3664]
When user is using the CLI with the image `eclipse/che` and moving to use `eclipse/che:nightly` we are printing the following error message.

```
WARNING: No kernel memory limit support
INFO: Proxy: HTTP_PROXY=, HTTPS_PROXY=, NO_PROXY=*.local, 169.254/16
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
ERROR:
ERROR: Your CLI version 'eclipse/che:nightly' does not match your installed version '5.0.0'.
ERROR:
ERROR: The 'nightly' CLI is only compatible with 'nightly' installed versions.
ERROR: You may not 'che upgrade' from 'nightly' to a numbered (tagged) version.
ERROR:
ERROR: Run the CLI as 'eclipse/che:<version>' to install a tagged version.
```

This message is not helpful and doing an `upgrade` will not work. 

In general, I would think that we should catch when the user is starting `nightly` because it behaves differently than a tag version, and should be used in parallel of a default installation.

Would be nice to inform the user that, he can try nightly by installing it on another folder to be mount. 

**Che version:**    5.0.0
**OS and version:**    MAC OS 10.12.2
**Docker version:** 1.12.3

**Comment by TylerJewell** [comment]
I do not understand the issue with the message.  We do not allow nightly and non nightly installs to mix.  So the message is clear on what the error is.

**Comment by benoitf** [comment]
AFAIK It may not be clear that there is already an installation in the /data folder. Or alternative ways for the end-user

For example
```Your CLI version 'eclipse/che:nightly' does not match your installed version '5.0.0'.```
we could add
```Your CLI version 'eclipse/che:nightly' does not match your installed version '5.0.0' in /home/users/host-folder.```

and a message like :
```You may use a separate ${CHE_FORMAL_PRODUCT_NAME} by providing another /data volume mount folder.```

**Comment by TylerJewell** [comment]
I see what you all are coming from now.  This is an easy improvement.

**Comment by TylerJewell** [comment]
Added to the PR.
