### ISSUE TITLE
enviromental variables are not inherited in the web ide

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3665]
user doesn't inherit enviromental variables when executing a command in IDE. 

**Reproduction Steps:**

I have created a custom stack with a custom image. The image bases on codenvy/ubuntu_jdk8 and some environment variables are set in the .bashrc file in the image (e.g. HTTP_PROXY). When I do
`whoami && echo $HTTP_PROXY && echo HELLOWORLD`
in a terminal of the workspace then it returns
```
user
http://proxy.blah.blah:8080/
HELLOWORLD
```
as it is supposed to be. However if I create the same command as a custom command and push 'start' button it returns only
```
user

HELLOWORLD
```
Ther first question is if this is a normal behaviour? If so, then how to inherit the environment variables for the both cases? (Let's assume that duplicating environment variables in a workspace config is a bad solution). 

**Che version:**    5.0.0
**OS and version:**    Ubuntu 16.06
**Docker version:** 1.12.5

**Comment by ghost** [comment]
@aleksei-burakov can you share your Dockerfile?

Did you write those envs in ~/.bashrc in the terminal after the workspace has started? Or did you do that already in the Dockerfile?

**Comment by aleksei-burlakov** [comment]
> Did you write those envs in ~/.bashrc in the terminal after the workspace has started?

I added environmental variables in the image itself. The image was created without a dockerfile. It looked approximately as this.
The first console
```
$ docker run -it codenvy/ubuntu_jdk8 /bin/bash
$ echo 'export HTTP_PROXY=http://proxy.blah.blah' | sudo tee -a ~/.bashrc

```
The second console
```
$ docker commit <containerID> foo/bar
$ docker push foo/bar
```
Then I added a stack into stacks.json with the following recipe.

```
"recipe": {
                "type": "dockerfile",
                "contentType": "text/x-dockerfile",
                "content": "FROM foo/bar\nCMD tailf /dev/null\n"
          }
```

> Or did you do that already in the Dockerfile?

The evnironmental variables declared in a dockerfile in a recipe section work well. So if the recipe looked as 
```
"recipe": {
                "type": "dockerfile",
                "contentType": "text/x-dockerfile",
                "content": "FROM foo/bar\nENV HTTP_PROXY http://proxy.blah.blah:8080/\nCMD tailf /dev/null\n"
          }
```
then in the both cases the variable is set. It also works if I define the comand right in the comandLine in the command section of the stacks.json
```
"commands": [
        {
          "commandLine": "export HTTP_PROXY=http://proxy.blah.blah:8080/ && whoami && echo $HTTP_PROXY && echo HELLOWORLD",
          "name": "run",
          "type": "custom"
        }
```

**Comment by ghost** [comment]
This is expected behavior both for Docker execs and exec agent that Che uses:


```
eugene@eugene:~/Stuff/Dockerfiles/env$ docker exec d82704ff83d5 sh -c "whoami && echo $hello && echo HELLOWORLD"
user

HELLOWORLD
```

Exec agent executes commands in a non interactive mode, thus all user files like .bashrc and .profile are ignored. A true Docker way is to use ENV instructions

**Comment by aleksei-burlakov** [comment]
Thank you, it explains it.
