### ISSUE TITLE
Not consistent version of Che used with chedir utility

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3666]
Starting Che using chedir utility with the command: `che dir up` is not starting the right Che version. 

**Reproduction Steps:**
1. Start Che using che dir command. (latest or nightly versions of eclipse/che CLI)
2. Check version: 5.0.0-M7

**Che version:**    5.0.0 , 5.0.1
**OS and version:**    MAC OS 10.12.2
**Docker version:** 1.12.3

**Comment by benoitf** [comment]
Fixed by https://github.com/eclipse/che/pull/3751
