### ISSUE TITLE
Use consistent versions of Che images used between nightly/latest

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3667]
Utilities images are always pointing to "nightly" images.
https://github.com/eclipse/che/pull/3646#pullrequestreview-15885715

So that when you start a command using the eclipse/che:latest, it retrieves images that are `nightly`.

As a user, it feels strange and confusing. Would be expected that if starting with `latest` it uses always `latest` images, and if starting with `nightly` it uses always `nightly` images.

This will make debugging scenarios for users and customers hard to reproduce. 

**Che version:**   5.0.0, 5.0.1

**Comment by riuvshin** [comment]
we already discussed this with @TylerJewell this is a bad thing. we agreed that we will have all those images in `dockerfiles/cli/version/<version>/images_utilities` file same as `images` file.
but not sure that @TylerJewell will be able to do that for 5.0.1.  that issue can be really critical only if  nightly will become incompatible, so we probably can delay this to 5.1.0

**Comment by TylerJewell** [comment]
We will use this issue created by @slemeur as the tracking issue.

**Comment by benoitf** [comment]
Fixed by https://github.com/eclipse/che/pull/3751
