### ISSUE TITLE
Allow a user's SSH keys to be shared with the git client in the terminal

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3672]
It would be helpful if the git client used in the workspace machine could pull the SSH info that's configured in Profile > Preferences and used by the JGit implementation in Che.

Perhaps if the path to the SSH key defined in Preferences was copied to .ssh/config the git command line could pick up the same key.

For customer context see: https://github.com/codenvy/codenvy/issues/1505#issuecomment-271867863 by @richtera

**Comment by vinokurig** [comment]
I think such solution has a serious secure issue: if the workspace will be shared, all ssh keys will be visible.

**Comment by richtera** [comment]
Maybe giving each user a GIT_SSH environment is safer then. It could wrap around SSH and provide the key in a safe way

**Comment by vinokurig** [comment]
@richtera thanks for advice, I need to check it.

**Comment by vinokurig** [comment]
`GIT_SSH` variable with custom script will work, but if a workspace will be shared, native git from console will use SSH keys from user who shared the workspace. In the same time SSH keys from the user who uses shared workspace will be used, if Git operations from menu would be performed.

**Comment by richtera** [comment]
But can't GIT_SSH point to a ssh exec wrapper that retrieves the same keys that the menu would use? Well maybe not, but it sounds plausible.

**Comment by vinokurig** [comment]
Git from menu retrieves keys by HTTP request. I have prepared a script that also makes the same HTTP request, but with the help of the user token from environment variables.  The problem is that this token is a token of the user who shared the workspace, so the key whom belongs that token is received.

**Comment by richtera** [comment]
I see, so there is no new shell launched for each user. I was assuming a new shell was being launched since I see shells disappearing when refreshing the UI. Maybe a "git terminal" type UI object that's similar to a terminal but restarted for each new user. I know many people will be able to use just the UI, but for larger git operations it's a bit cumbersome.

**Comment by TylerJewell** [comment]
@richtera - yes it would have to be some sort of UI widget that was an explicit git terminal creation.

But on a more practical note, if you are sharing a workspace with others, it's like sharing localhost with your friends.  You are all sharing the same runtime as the same user ID.  What is the more likely path that we should push for:
1. Try to have the same workspace truly shared and create some sort of end user isolation within a common ws (this is not our model today and poses all sorts of challenges practically implementing it), or:
2. Encourage users to create their own workspace (either a clone, or create a new one from a shared stack). 

If two develoeprs are going to share a workspace for a short period of time, then the git isolation is not really needed.  It's probably a quick "let me help you with that in a pairing scenario".  You don't want the isolation.  But if it's a long lived collaboration, then wouldn't each user want their own workspace connected to the same repository, and then for each of them to have the workspace that is private?

**Comment by rhughes89** [comment]
I created a similar issue, #4715, to this where I made a suggestion on possibly being able to pull ssh private and public key info from the user API endpoint.

**Comment by ghost** [comment]
Duplicate of https://github.com/eclipse/che/issues/5169
