### ISSUE TITLE
Breakpoints disappear when nodejs debugger is resumed

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#3675]
Breakpoints disappear when nodejs debugger is resumed

**Reproduction Steps:**
See attachment below

**Che version:**    5.1.0-SNAPSHOT

**OS and version:**    Linux Mint 18.1

**Docker version:** 1.12

**Comment by tolusha** [comment]
![out](https://cloud.githubusercontent.com/assets/1640675/21852136/94184f60-d81a-11e6-8a03-8015dcccb043.gif)

**Comment by riuvshin** [comment]
please test java debugger after code changes to make sure we didn't break things

**Comment by tolusha** [comment]
Can't be reproduces after testing on the latest version of CHE with cleaned up cookies.

**Comment by JamesDrummond** [comment]
@tolusha Did you start che with a new data folder and then recreated the project? I am not able to reproduce with 5.0.0 but it did happen the first time I tried. I didn't restart che server and stepping no longer clears break points.

**Comment by bmicklea** [comment]
@JamesDrummond could it be a cookie issue?

**Comment by JamesDrummond** [comment]
@bmicklea It was. Not sure why we are using cookies for debugging.

**Comment by riuvshin** [comment]
I think it was cache not cookies issue
