### ISSUE TITLE
Cannot connect workspace over ssh with putty

### ISSUE THREAD

**Issue by codergabs** [eclipse-che/che#3687]
trying to connect workspace with ssh on windows
che is running over boot2docker on windows

trying the following command on DOS
putty -ssh -l Administrator -P 32772 192.168.99.100 -i C:\Eclipse-Che\putty-ssh.ppk

Using username "Administrator".
**Server refused our key**
Administrator@192.168.99.100's password:

ssh key file is putty converted key(via puttygen) from openssh key on my workspace
putty-ssh.ppk

PuTTY-User-Key-File-2: ssh-rsa
Encryption: none
Comment: imported-openssh-key
Public-Lines: 6
AAAAB3NzaC1yc2EAAAADAQABAAABAQCqc3yCiKVWi+dxhEyKm/ZM3WCkz+aKixAA
xf3SRyXyb6FDYw+b0FyVpzy75ilm67WG+qtqGesAl0uZpAwfbXgxlaH8G+J3xm9H
c/2vWIGT4Q/CxHHV8urtY0SXHRcdNwd5T14uNUsQOteSd/ZjiDeolQem1aZ74An/
QnlbID52kL6xoqUIGxZgC7wo0YL7C2YzyPn48z6v+CDW4WgM1q3a9aKfWfQcaEiH
nQYoAwp0p+MWTD8vAoVkWvJTlD7hD/pHp3Ws+2vP/NH+P7paVNGu7Tm9Uu2B2mGW
l2vjFR7ANcFwbUSsp+qOEckfhOwNx+EEcexgddAUpRyho+hk7hq1
Private-Lines: 14
AAABADJ4IXzREwuuPyhYgQVlqqcVwYDrYhrRlDp2ZXJ2yKChNwGp+jwrlM5nB0+n
lci4sDY4ULsI05GIOsVSUpiXpEgiQyVP6F2IrvhcOthJf4yWzkDgQ8iStcb2Zp/L
6EUpPxhHTN6nvwMeOShQRu8vrTNIdUyL5FC3hJ5FQ4Oc54HZXBgGB+KQa5JQNN43
fy9HXt0do6MbEy1Yw2Hu4aRi9S8rnIe3EyaiJt0qNQ53d3lB6StPfxW4s7PzZ5v+
H6N41Ve91QvjR9Ez+OtlikBAl7TkBgVJu01nbZ3lnZiH8OxyOYQLt3EZm1ENJh0E
yN0sn1ow76Hls0g1XmtpGFl/AwEAAACBANqrdo8tnNHG+z6BAV4Bd/rMzd9S91RR
uVCIAXWeF5AThA00QjAuECa8Hzz+9Cq48Cjaz+zfAkBKKt9a0k3klNT0M2NxQBLe
1oDrdXZoHSSdd8/3SrKvlfUxCYcvt74WBkUr3B0mf/ABoMMMdXNHii95q7ck5lIW
6Ei0vibiHPz1AAAAgQDHjLh7HHA6uGLjfvAeIYdOlV9HH6K7Coo2V7yVZU5W6fv6
CHU4/eGJzNlnlHbe/CUI4guIqaIwVCdzuFedZ3B9HUUENqKdjLfXXjE2ASPmrGGm
6qUAWbsui8vTVmCJrNJwe7+Bni3UprA6CZOOb90J2uAKh+NGc7j3o+xQ04YOwQAA
AIEAglf5rgZe0kDlpQWz3NSrvdG4/DwNh2K8WS38Tnm4uuLnqgQVO0UXTrfY81V5
SjuUfdEv9/vdYcGHbSt4yjSuJ6eTad8V5tuTT308k/QBVVBETD7T6w4o179gB7dU
gI88Ti9Y2nR/Jib7VMADcvoCykcdvR9d431HfMoWZfGCQLI=
Private-MAC: 60580c1c226a9818f9a268a5775e4cc1fe83ebd6

**Comment by codergabs** [comment]
I think it is an issue, 
I can sucsessfully login by putty with the default created sshkey, ssh-rsa value at UI and 
**/home/Administrator/.ssh/authorized_keys** matches.
But if I remove that key and generate again, then **/home/Administrator/.ssh/authorized_keys** value is not changing, retaining the old ssh-rsa value, 
So with the newly generated key cannot connect.

**Comment by ghost** [comment]
@codergabs can you elaborate on the use case? You started a workspace, then added a key? Did you restart the workspace then?

Also, username should be user (if we're talking about ready to go stacks)

**Comment by codergabs** [comment]
@eivantsov 
I have created my own stack with ssh enabled.
Then I have started workspace.
I can connect the workspace with default ssh private key.
Then I have removed the ssh key and generated a new pair.
After that I cannot connect with the new key, I can still connect with the old key.
I found the **/home/Administrator/.ssh/authorized_keys** is not updated with the new one,
it still holds the old key. that's why i can connect with the old key not the new one.
But my expectation is as I've changed the key I should be able connect with the new key.
(I am using username Administrator)

**Comment by ghost** [comment]
> Then I have removed the ssh key and generated a new pair.

Did you do that in Preferences in the IDE or directly in the terminal? If you did that in preferences you need to restart a workspace so that your public key part is injected into authorized_keys in a workspace.

**Comment by codergabs** [comment]
@eivantsov 
I changed at IDE, I didn't restart the workspace.
Please add this step at the documentation.

**Comment by ghost** [comment]
@codergabs did restart resolve the issue?

**Comment by codergabs** [comment]
Yes, restart resolved it.

**Comment by ghost** [comment]
@JamesDrummond can you add this requirement to docs please?

**Comment by TylerJewell** [comment]
@bmicklea @JamesDrummond - update please on the docs issue.

**Comment by JamesDrummond** [comment]
Updated docs which indicate that restart is needed when updating keypair of machine.
