### ISSUE TITLE
Problem importing OpenShift Git project in Eclipse Che on Codenvy

### ISSUE THREAD

**Issue by BvEijkelenburg** [eclipse-che/che#3696]
Hi, I'm getting an internal server error while importing an OpenShift git repo in Eclipse Che (running on Codenvy). I created an SSH-key in Eclipse Che (Preferences > SSH > VCS), and uploaded it to my OpenShift account. 

Next, I try to import the project, (URL: ssh://&lt;account&gt;@&lt;app-url&gt;.rhcloud.com:/~/git/codenvy.git) but i'm getting:

java.lang.IllegalStateException: org.eclipse.che.ide.websocket.rest.exceptions.ServerException: Internal Server Error occurred, error time: 2017-01-12 13:45:41

The SSH key was created for host &lt;app-url&gt;.rhcloud.com, without http or www.

Help would be very much appreciated!

**Reproduction Steps:**

**Che version:**    5.0.0-M8 Revision : 3cacf890eda7d9ba Build Time :2016-12-07 14:37:08

**OS and version:** Linux c9d82f218d2f 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 GNU/Linux on Codenvy

**Comment by BvEijkelenburg** [comment]
After hours of trying, I get the impression that this is more a Codenvy issue. I'm moving this issue there.

**Comment by TylerJewell** [comment]
If you are doing this on codenvy.io, we have to manually whitelist each domain.  however, if you are doing this within Che, it should not be required to add a whitelist and it could be an indication of another kind of problem.

**Comment by BvEijkelenburg** [comment]
Thanks! I'm doing this on codenvy.io. But from the Codenvy issuelist, I understand that the Openshift domain (rhcloud.com) is already on the whitelist.

**Comment by TylerJewell** [comment]
Yes, I don't think this is a che issue - best for codenvy.

**Comment by BvEijkelenburg** [comment]
Thanks, I copied the issue to: https://github.com/codenvy/codenvy/issues/1520
