### ISSUE TITLE
Create a prototype of maven archetype for Eclipse Che plugin developers.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#3697]
Archetype should contains

- Simple plugin with UI part
- Custom stack 
- Custom template
- Assembly of ws-master ws-agent

**Comment by TylerJewell** [comment]
Some other things that we should include in it:
1. Custom CLI that inherits from che-base, but includes minimum files to configure init, cli. This means have portions of the /dockerfiles directory included.
2. Simple plugin with custom agent or server-side part, too.

**Comment by skabashnyuk** [comment]
Prototype has been created here https://github.com/skabashnyuk/che-archetypes
