### ISSUE TITLE
CHE-507 Error appears when creating a new sample project

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#370]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-507
Reporter:  Igor' Vinokur
Description: Steps to reproduce:
Click Workspace -> Create Project... 
Select any sample (web-java-spring for example) 
Type the project's name
Click "Create"
Wrong: error window appears and the project is available only after refreshing the page.

**Comment by ddementieva** [comment]
Fixed
