### ISSUE TITLE
Chefile Dockerfile Error: Fail launching agent Terminal

### ISSUE THREAD

**Issue by william-kerr** [eclipse-che/che#3704]
I am trying to embed minimal Dockerfile content in a Chefile and I keep getting, "Error: Fail launching agent Terminal".  I've tried to strip out everything unnecessary from the eclipse/alpine_jdk8 image, which does work if I simply put "FROM eclipse/alpine_jdk8".

**Reproduction Steps:**
Create a Chefile that contains:
```
workspace.runtime.docker.content=`
FROM docker:1.12.0
RUN apk add --no-cache bash openssh sudo && \
    adduser -S user -h /home/user -s /bin/bash -G root -u 1000 && \
    echo "%root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "SECRET" >> /tmp/passwd && \
    echo "SECRET" >> /tmp/passwd && \
    cat /tmp/passwd | passwd user && \
    chown -R user /home/user/
EXPOSE 22
USER user
WORKDIR /projects
CMD sudo /usr/bin/ssh-keygen -A && \
    sudo /usr/sbin/sshd -D && \
    sudo su - && \
    tail -f /dev/null
`
```
Then, go into the directory containing the Chefile and run something like:
docker run -t --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD/.che:/data eclipse/che dir $PWD up

If using Windows PowerShell, replace the last $PWD in the command above with something like:
/c/users/REPLACE_WITH_THE_REST_OF_YOUR_PATH

This is the error you'll see in the terminal:
```
INFO: (che dir): Workspace created
INFO: (che dir): Workspace booting...
ERROR: (che dir): Error when starting the workspace{"error":"Start of environment default failed. Error: Fail launching
agent Terminal. Workspace ID:workspace6a1uxqckh8c0fvlo","eventType":"ERROR","prevStatus":"STARTING","workspaceId":"works
pace6a1uxqckh8c0fvlo"}
```
**Che version:**
5.0.0

**OS and version:**
Windows 10 Pro via PowerShell

**Docker version:**
1.13.0-rc6

**Che cli.log output:**
Fri Jan 13 05:12:53 UTC 2017
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (che cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
DEBUG: cli_parse
DEBUG: update_image_if_not_found
[0;32mINFO:[0m (che download): Checking for image 'eclipse/che-dir:nightly'...
found
DEBUG: docker_run

**Comment by TylerJewell** [comment]
Thanks @mscribe for the submission.  We found another error with how Chefiles are parsing recipes. @benoitf is going to investigate and we'll have an answer soon.

**Comment by william-kerr** [comment]
So, I noticed in the code that it pulled from a Dockerfile in the chedir, so I stuck this in a Dockerfile and it works.  It still is broken if I embed it in the Chefile, so the bug is parsing.
```
FROM golang

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        locales \
        openssh-server \
        sudo && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir /var/run/sshd && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    useradd -u 1000 -G users,sudo -p $(openssl rand -base64 32) -s /bin/bash -m user && \
    echo "#! /bin/bash\n set -e\n sudo /usr/sbin/sshd -D &\n exec \"\$@\"" > /home/user/entrypoint.sh && \
    chmod a+x /home/user/entrypoint.sh

ENV LANG C.UTF-8

USER user

RUN sudo localedef -i en_US -f UTF-8 en_US.UTF-8

EXPOSE 22

WORKDIR /projects

ENTRYPOINT ["/home/user/entrypoint.sh"]

CMD tail -f /dev/null
```

**Comment by TylerJewell** [comment]
Thank you @mscribe for reporting the issue.  I am going to crosslink a couple of minor issues related to chefiles that have been discovered.  I believe that florent is going to investigate these issues in the upcoming week and we will look at a patch.

**Comment by TylerJewell** [comment]
Issue: https://github.com/eclipse/che/issues/2787
Issue: https://github.com/eclipse/che/issues/3666

**Comment by benoitf** [comment]
yes I've bunch of issues around Chefile to handle no later than the upcoming week

**Comment by benoitf** [comment]
@mscribe of thanks for the report of the issue. It was a nasty one.
The content of Dockerfile inside Chefile was interpreted. There was also an issue with # character handling
I've added a fix in PR https://github.com/eclipse/che/pull/3875

After the fix I'm able to use your dockerfile inside a Chefile
```
workspace.runtime.docker.content=`
FROM golang

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        locales \
        openssh-server \
        sudo && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir /var/run/sshd && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    useradd -u 1000 -G users,sudo -p $(openssl rand -base64 32) -s /bin/bash -m user && \
    echo "#! /bin/bash\n set -e\n sudo /usr/sbin/sshd -D &\n exec \"\$@\"" > /home/user/entrypoint.sh && \
    chmod a+x /home/user/entrypoint.sh

ENV LANG C.UTF-8

USER user

RUN sudo localedef -i en_US -f UTF-8 en_US.UTF-8

EXPOSE 22

WORKDIR /projects

ENTRYPOINT ["/home/user/entrypoint.sh"]

CMD tail -f /dev/null
```

**Comment by william-kerr** [comment]
Thanks for fixing; embedding a Dockerfile in a Chefile works now.

**Comment by benoitf** [comment]
Thanks for the report
