### ISSUE TITLE
Boot2Docker - eclipse/che  - Are you trying to connect to a TLS-enabled daemon without TLS

### ISSUE THREAD

**Issue by AbhiAtDocker** [eclipse-che/che#3713]
Hi , m getting TLS error on running eclipse/che with boot2dockers on windows 10

**Command used** 
docker run -it --rm -e DOCKER_HOST="tcp://192.168.99.100:2376" eclipse/che action list-workspace

![image](https://cloud.githubusercontent.com/assets/10115913/21924762/77b4ba7a-d9a0-11e6-9add-45e80186ece7.png)

![image](https://cloud.githubusercontent.com/assets/10115913/21924778/8b5529de-d9a0-11e6-89ce-18fdffdf0e23.png)

Have tried disabling the TLS as per the blog 
https://coderwall.com/p/siqnjg/disable-tls-on-boot2docker
it did not helped.

Are there any specific steps for  TLS to work with above command? 

Versions are : 

eclipse/che            latest              ad78fd3b5f11        6 days ago          51.06 MB

Docker version: 
Docker version 1.12.5, build 7392c3b

Windows 10

**Comment by TylerJewell** [comment]
I don't think this is an issue for Che.  It looks like your docker machine variables were not set up in your shell before you tried running docker.  Those variables need to be applied to your shell system parameters before you do docker commands.

**Comment by ghost** [comment]
@AbhiAtDocker there's no need for DOCKER_HOST env in your docker run syntax.

Can you just run `docker ps` in your cmd?

**Comment by AbhiAtDocker** [comment]
rest of the docker commands are running fine. This is happening with instruction provided to up eclipse/che. Below is the instruction.

$ docker run <DOCKER_PARAMETERS>   eclipse/che action list-workspaces 

when i run this without Docker_host i get below message. 

![image](https://cloud.githubusercontent.com/assets/10115913/21927720/f50078a0-d9ac-11e6-8e03-f447351b5ef7.png)

and with  docker_host i get TLS issue.

**Comment by AbhiAtDocker** [comment]
@TylerJewell other than the one in first post are there any other parameters that you are pointing at to be set up in shell?

**Comment by ghost** [comment]
@AbhiAtDocker the error is expected on Windows when setting DOCKER_HOST this way. Disregard it, just mount docker.sock instead.

As to `action list-workspaces` @TylerJewell is the right person to help

**Comment by ghost** [comment]
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/yourUsername/some-folder:/data eclipse/che-cli:nightly action list-workspaces`

Works for me.

`/c/Users/yourUsername/some-folder` should be an existing directory in your Windows system.

**Comment by TylerJewell** [comment]
@AbhiAtDocker - if you are using Boot2Docker, then your workspace files for your users must be saved in a folder that is a subfolder of `%userprofile%`. This is a limitation of how Boot2docker is configured.  In @eivantsov example, he has mounted `/c/Users/` which is the subfolder of `%userprofile%`.

In the case of the explanation in the help, while it is true that you can connect directly to a DOCKER_HOST, that is not needed in your case, and the "mount" syntax is preferred like Eugene suggested.

**Comment by AbhiAtDocker** [comment]
Thanks mount syntax worked for me without TLS issues. 

Also  I had to upgrade from che-launcher to eclipse/ch; I noticed that new che instance did not picked my workspace from last instance. I want to import the previous workspace into the new che instance. 

I tried exporting the workspace via export option from last version. It gave a "download" file with workspace configuration. I am not able to find import option on che ide. I was expecting if these configurations can be imported while creating the workspace in new instance or an import option that will create the workspace on the basis of exported configuration

Second idea i have is that if i can import the existing workspace image into this current instance so that i can start from where i left. Pls help me understand the feasibility of it.

BRs

**Comment by TylerJewell** [comment]
You can import your workspace configuration from the old version into the new version using the dashboard.  When you create a new workspace you can do so by providing a workspace configuration.  It is an option in that first screen of the dashboard.

**Comment by TylerJewell** [comment]
Closing this issue as the original problem has been resolved.
