### ISSUE TITLE
UTILITY_IMAGE_CHEIP: unbound variable

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3716]
When starting a project it returns `UTILITY_IMAGE_CHEIP: unbound variable`

**Reproduction Steps:**

I have cloned and compiled a fresh che about an hour ago. When I start is as `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli start` it returns
```
WARN: You are using CLI image version 'latest' which is set to '5.0.0'.
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using binaries from your local repository
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
/repo/dockerfiles/cli/scripts/cli.sh: line 10: UTILITY_IMAGE_CHEIP: unbound variable
```
Previously this error did not occure.
**Che version:**    5.0.0
**OS and version:**    Ubuntu 16.04
**Docker version:** 1.12.5
**Che cli.log output:** 
```
Fri Jan 13 09:53:55 UTC 2017
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (che cli): Loading cli...
Fri Jan 13 09:54:22 UTC 2017
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (che cli): Loading cli...
```

**Comment by TylerJewell** [comment]
Somehow your docker images are getting mixed up with latest and others that you have built.  Wipe all of your images or rebuild the images from the dockerfiles directory and then rerun.

**Comment by ghost** [comment]
@aleksei-burakov since you use the latest Che code, you need to use nightly image: `eclipse/che-cli :nightly`

Can you give it a try?

**Comment by aleksei-burlakov** [comment]
@eivantsov  it seems that I have first to destroy the latest version, but I can't because of the same error. Without destroying the latest it returns
```
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/8e/8e089824e27c77140777cf9c273abfbf92a6965d26e65fff6989b10793ced9b6/data?Expires=1484308851&Signature=Z6cpYSawVbgF9jWnxhbsqXTlTOEXoOyBmlYPZgO4Hr99ApdU~9cEEL7n1N7ghuTH81qvj1jN91Bu86TtkI3ot2BVPF32PwE08N1Pfx7zsjccb1sZh7fMiZ5e3ErS2VedrKALDVjUO8ZJRJqrYNnyUSNqY-xO-S55Xljcqj3xuzY_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: read tcp 10.0.2.15:53458->52.222.149.38:443: read: connection reset by peer
ERROR: Image eclipse/che-init:nightly unavailable. Not on dockerhub or built locally.
```
However `docker pull eclipse/che-init:nightly` did the thing. The nightly version has started.

**Comment by ghost** [comment]
`error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/8e/8e089824e27c77140777cf9c273abfbf92a6965d26e65fff6989b10793ced9b6/data?Expires=1484308851&Signature=Z6cpYSawVbgF9jWnxhbsqXTlTOEXoOyBmlYPZgO4Hr99ApdU~9cEEL7n1N7ghuTH81qvj1jN91Bu86TtkI3ot2BVPF32PwE08N1Pfx7zsjccb1sZh7fMiZ5e3ErS2VedrKALDVjUO8ZJRJqrYNnyUSNqY-xO-S55Xljcqj3xuzY_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: read tcp 10.0.2.15:53458->52.222.149.38:443: read: connection reset by peer
ERROR: Image eclipse/che-init:nightly unavailable. Not on dockerhub or built locally.
`
Looks like temporary Docker glitches.

**Comment by aleksei-burlakov** [comment]
After removing all docker images, the latest version has started.
