### ISSUE TITLE
How to deploy on PaaS

### ISSUE THREAD

**Issue by blingeee** [eclipse-che/che#372]
Is there a way to deploy application to PaaS?
What is how to install cf cli on container..?

**Comment by ddementieva** [comment]
You can create a custom stack with cf cli installed for that and deploy your application directly from the Terminal.

Just go to Dashboard > Workspaces, click New Workspace button, choose Custom Stack > Write your own stack option and paste your Dockerfile there. It may look something like this:
FROM codenvy/ubuntu_jre
RUN mkdir /home/user/cf
WORKDIR /home/user/cf
RUN wget -q http://go-cli.s3-website-us-east-1.amazonaws.com/releases/v6.7.0/cf-cli_amd64.deb && \
   sudo dpkg -i cf-cli_amd64.deb
CMD tail -f /dev/null

Here we've used 6.7.0 CF version. You can change it to the latest one. 

After a successful workspace creation, you can open it in the IDE, go to the Consoles, click (+) button to open a New Terminal, login to your cf account and push your application using the appropriate cf commands.

Find more details about requirements to the custom stacks at https://eclipse-che.readme.io/docs/environments#custom-stacks

**Comment by blingeee** [comment]
Thanks a lot!!
