### ISSUE TITLE
Find Project Symbol does not work

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#3721]
Find Project Symbol popup does not work.
Uninformative error messages are appeared in developer console when typing.

![find project symbol](https://cloud.githubusercontent.com/assets/1655894/21930501/ff327dc2-d99e-11e6-9a96-81be0ddd5414.png)

**Comment by evidolob** [comment]
Find Project Symbol should be accessible only for files with LanguageServer, for Java file/project it should be disabled/hidden
