### ISSUE TITLE
CHE-510 Style improvements for dashboard

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#373]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-510
Reporter:  Stévan Le Meur
Description: Discussed over voice call, we will improve some styles inside of Dashboard.
- Improved shadow
- Smaller font sizes
- Change font to Open Sans
- Improvement in headers of the panels
- ...

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/1a6796646669893714b7e28bb4d785262ce38152
