### ISSUE TITLE
Actions are not enabled in sample-plugin-json 

### ISSUE THREAD

**Issue by elpddev** [eclipse-che/che#3735]
1. Added the sample-plugin-json to CHE, compiled it and run it.
2. Created a json sample project.
3. Opened the context menu for the project. The `JSON Example` Menu is grayed out and not enabled.

I think this comes from the `updateInPerspective` check on the `JsonExampleProjectAction`.  There is a bug in the logic of the resources check I think. 

```java
if (resources == null || resources.length != -1) {
            event.getPresentation().setEnabledAndVisible(false);
            return;
}
```

Instead of `resources.length != -1`, the idea here I think was to check if the resources are valid. 
`resources.length < 0`. But I am not sure why the `length` check is necessary when resources is an array unless the desire was to check that resources has at least one resource which in that case `resources.length <= 0` could fix this. I am not sure what the `resources` presents on the AppContext. 

https://github.com/eclipse/che/blob/master/samples/sample-plugin-json/che-sample-plugin-json-ide/src/main/java/org/eclipse/che/plugin/jsonexample/ide/action/JsonExampleProjectAction.java#L65

**Comment by TylerJewell** [comment]
@slemeur @evidolob @azatsarynnyy @vparfonov - would one of you mind taking a peak?  Seems like @elpddev has done his preparation and homework here.

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT

![image](https://user-images.githubusercontent.com/5337267/28106008-b839b1ae-66ea-11e7-8aa9-f7c5cbfbc812.png)
