### ISSUE TITLE
The 'Navigate To File' works incorrectly (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3739]
When I use the 'Navigate To File', then it does not determine a lower and upper case of input symbols.

**Reproduction Steps:**
* Open in the IDE a project (e.g. web-java-spring from template).
* Invoke the 'Navigate To File' from menu or by 'Ctrl+Alt+N'.
* Enter the 'P'.

**Expected behavior:**
* should not appear files with lowercase symbol.

**Observed behavior:**
* the files with lowercase symbol appear in the form.

**Che version:**        5.1.0-SNAPSHOT
**OS and version:**   Ubuntu 14.04 
**Docker version:**   1.12

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![navig_to_file](https://cloud.githubusercontent.com/assets/5408906/21962654/c771200a-db33-11e6-9976-7366798ed807.png)
![navi_to_file](https://cloud.githubusercontent.com/assets/5408906/21962655/c771c0d2-db33-11e6-8a1e-fee6ce13c99f.png)

**Comment by riuvshin** [comment]
@vparfonov this is regression can you please take a look

**Comment by vparfonov** [comment]
normal behavior
