### ISSUE TITLE
The language server cannot finish of initializing

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3744]
Steps to reproduce:
1. Create a workspace based on next configuration:
`{
  "environments": {
    "replaced_name": {
      "machines": {
        "ws-machine": {
          "agents": [
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh",
            "org.eclipse.che.ls.csharp",
            "org.eclipse.che.ls.json",
            "org.eclipse.che.ls.php"
          ],
          "attributes": {
            "memoryLimitBytes": "desired_memory_value"
          }
        }
      },
      "recipe": {
        "content": "FROM codenvy/debian_jre",
        "contentType": "text/x-dockerfile",
        "type": "dockerfile"
      }
    }
  },
  "defaultEnv": "replaced_name",
  "projects": [],
  "name": "replaced_name",
  "attributes": {},
  "temporary": false
}`
2. Create aspnet-web-simple project
3. Open Program.cs file
**Expected result:** The file should be opened. The base autocomplete features should be available
**Actual result:** The initializing of the language server cannot finish.
**Che version:** 5.1.0 Snapshot
**Docker version:** 1.12.6
**OS:** Ubuntu 14.0 LTS

**Comment by ghost** [comment]
@musienko-maxim have you tried it with `eclipse/debian_jre`

**Comment by ghost** [comment]
It's the same with this image actually.

Having tried to run the script manually, it turns out that there's nothing in ~/che/ls-csharp:

```
 throw err;                                                                                                                                                                                                                  
    ^                                                                                                                                                                                                                           
                                                                                                                                                                                                                                
Error: Cannot find module '/home/user/che/ls-csharp/node_modules/omnisharp-client/languageserver/server.js'                                                                                                                     
    at Function.Module._resolveFilename (module.js:469:15)                                                                                                                                                                      
    at Function.Module._load (module.js:417:25)                                                                                                                                                                                 
    at Module.runMain (module.js:604:10)                                                                                                                                                                                        
    at run (bootstrap_node.js:394:7)                                                                                                                                                                                            
    at startup (bootstrap_node.js:149:9)                                                                                                                                                                                        
    at bootstrap_node.js:509:3                                                                                                                                                                                                  
user@9b5f1bd5d9c9:~/che/ls-csharp$ ls                                                                                                                                                                                           
launch.sh                                                                                                                                                                                                                       
user@9b5f1bd5d9c9:~/che/ls-csharp$ pwd                                                                                                                                                                                          
/home/user/che/ls-csharp               
```

It looks like the problem is with curl and codenvy.com. For some reason, binaries for this agent arent' served by a container but downloaded from https://codenvy.com/update/repository/public/download/org.eclipse.che.ls.csharp.binaries

Certificate for codenvy.com has expired. So, curl ends up with an error., We should either use the same mechanism to distribute agents as we did for terminal and ws agent or use `-k` option with curl.

**Comment by musienko-maxim** [comment]
has been resolved

**Comment by VonTalavang** [comment]
it is not solve, and is 2018
