### ISSUE TITLE
Refactor client access to agents to respect workspace token in Che

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3746]
Now Codenvy uses workspace token to access agents API in workspace. Che doesn't use that technique. 
Goals of this task are:
- to add token into [WorkspaceRuntime](https://github.com/eclipse/che/blob/master/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/WorkspaceRuntime.java#L34)
- inject this token on server if it is supported by Che implementation
- put this token into context of IDE
- adapt agent API clients implementation in IDE to respect token if it exists in WorkspaceRuntime

**Comment by skabashnyuk** [comment]
will be fixed in #4429
