### ISSUE TITLE
CHE-514 Fix jdt tests

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#375]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-514
Reporter:  Anatoliy Bazko
Description: It blocks other issues like IDEX-4132

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/b09c14ed1884bcb448c2847a2d9c27691a11f945
