### ISSUE TITLE
unexpected grouping of create new project menu items

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3759]
I have added a new item in `che/instance/data/templates/samples.json` Its name is `Clustering` and its category is `Blank`. It is expected to see the `Clustering` project in the same `Blank` group, but it is put in another `Blank` group.

![capture](https://cloud.githubusercontent.com/assets/22703481/22016346/42e35ad2-dca6-11e6-8be2-beab9b2b0a03.PNG)

The question is if it is expected behaviour? If so, is there a way to put both blank groups together?

**OS and version:**    

Che version: 5.0.0
OS and version: Ubuntu 16.04
Docker version: 1.12.5

**Comment by ghost** [comment]
@aleksei-burakov it is expected behavior at the moment. If you want your sample to get into the sample list in the IDE, you need to choose Samples category otherwise Che will create a new one.

**Comment by aleksei-burlakov** [comment]
I have created Marmolata category (as on the picture) and I want it to consist of both of plugins registered by newSetBinder(...).addBinding().to(MyPlugin.class) and samples cofigured in `che/instance/data/templates/samples.json` . Che separates them. It's a matter of choise of course, but imho its expected to have them together. Anyway it would be good to have an option to put them together.

**Comment by ghost** [comment]
Che separates sample projects and project templates. Have you registered a custom project type and you want your plugin to provide samples?

**Comment by aleksei-burlakov** [comment]
Yes. I have implemented a ProjectWizardRegistrar class , ie a new plugin. It has created the Marmolata group. I would also like to put some samples from samples.json in that group.

**Comment by ghost** [comment]
You can just mimic what other plugins do, for instance node.js:

https://github.com/eclipse/che/blob/master/plugins/plugin-nodejs/che-plugin-nodejs-lang-server/src/main/java/org/eclipse/che/plugin/nodejs/generator/NodeJsProjectGenerator.java#L47

**Comment by aleksei-burlakov** [comment]
The problem is not to implement a plugin, but to rearrange plugins and samples on the list in new project dialog. As you see on the picture below there are two Marmolata groups. It is desired to have only one with the four elements.

![capture](https://cloud.githubusercontent.com/assets/22703481/22020695/e613535c-dcb9-11e6-8535-4904fb85ebf2.PNG)

**Comment by ghost** [comment]
You may add clustering to the list of templates that your plugin provides. So, ignore samples.json at all at this point.

**Comment by aleksei-burlakov** [comment]
If I add it as a plugin I will have to hardcode it. When it is configured in stacks.json, it gets cloned from a git repository.

**Comment by aleksei-burlakov** [comment]
This is an essential difference.

**Comment by ghost** [comment]
@aleksei-burakov so is current behavior. Creating a project from scratch (this is where your 3 other samples are) implies creating a file with little or no cotent at all. Some plugins use generators (like php composer or maven archetype).

@vparfonov may help you customize this behavior.

**Comment by aleksei-burlakov** [comment]
Thank you, I think I will live it as is by now.
