### ISSUE TITLE
CHE-513 Better handle exceptions when ws agent pings Che server

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#376]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-513
Reporter:  Eugene Ivantsov
Description: See https://github.com/eclipse/che/issues/319 to get a stack trace.

There's no diagnostic info there at all, like connection refused, connection timeout, malformed url, bad request etc.

This checker should handle exceptions in such a way so that it is well understood why the connection failed. We should also stop ws-agent then, since it produces tons of logs.

It will be also helpful to print /etc/hosts file since this information will help in diagnosis and possible solutions.

We should also print the following error:

"The workspace agent has attempted to start, but it is unable to ping the Che server at apiEndpoint

The workspace agent has been forcefully stopped. This error happens when the agent cannot resolve the location of the Che server. This error can usually be fixed with additional configuration settings in /conf/che.properties. The Che server will stop this workspace after a short timeout. You can get help by posting your config, stacktrace and workspace /etc/hosts below as a GitHub issue"

**Comment by ghost** [comment]
Fixed with https://github.com/eclipse/che/pull/368
