### ISSUE TITLE
Amend previous commit works incorrectly

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3760]
When I try to change commit message  by the 'Amend previous commit' in the commit form, I have unexpected error.

**Reproduction Steps:**
* Open in the IDE a project (e.g. web-java-spring from template).
* Make a change in a file and perform commit.
* Try to change the massage of commit by 'Amend previous commit'. 

**Expected behavior:**
commit message should be changed. 

**Observed behavior:**
nothing is changed and there is unexpected error.

Che version: 5.1.0-SNAPSHOT
OS and version: Ubuntu 14.04
Docker version: 1.12

**Che cli.log output:** [cli.log.zip](https://github.com/eclipse/che/files/710629/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![amend_prev_commit](https://cloud.githubusercontent.com/assets/5408906/22016148/d653e7c6-dcad-11e6-9e41-11ac859b776e.gif)

**Comment by vinokurig** [comment]
Waiting for QA Tests adoption
