### ISSUE TITLE
Workaround illegal response from docker daemon

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3761]
Docker 1.12.x has bug. When there is no networks with type=custom request to retrieve list of docker networks with filter **type=custom** returns `null/n` instead of `[]`.

There is an issue in docker for that bug docker/docker#29946

It will be fixed in docker 1.13 or even later. Since users suffer from this bug already we should workaround the problem somehow.

Offered solution is to catch exception and log error, but not allow it goes higher where it brakes task scheduler.

**Comment by mmorhun** [comment]
done
