### ISSUE TITLE
Workspace created by compose recipe url does not start (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3765]
When I try to create workspace  by compose recipe url from stack import, then workspace does not start.

**Reproduction Steps:**
* Go to the 'Workspaces' -> 'Add workspace' -> 'Runtime' -> 'Stack import' on the dashbord.
* Select compose recipe type and enter recipe url (e.g. https://gist.githubusercontent.com/idexmai/6918415efa88276bdf028756adc8b9fb/raw/04ea419e25e02d010a03d75278606c3e2218e1e6/composeJavaStack)

**Expected behavior:**
workspace should be created.

**Observed behavior:**
workspace is not created and there is unexpected error.

**Che version:** 5.1.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12

**Che cli.log output:**  [cli.log.zip](https://github.com/eclipse/che/files/711196/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

![imp_compfile_che](https://cloud.githubusercontent.com/assets/5408906/22023257/19a781e8-dcce-11e6-858a-a56a2ae5ae1c.png)
![imp_compfile_nightly](https://cloud.githubusercontent.com/assets/5408906/22023264/1cd0ad18-dcce-11e6-8452-e6657baa0620.png)

**Comment by riuvshin** [comment]
@TylerJewell @garagatyi guys seems this is regression it was working last week. should we mark this as blocker for 5.1.0 ?

**Comment by artaleks9** [comment]
Yesterday it worked.

**Comment by benoitf** [comment]
@artaleks9 do you have server traces ?

**Comment by garagatyi** [comment]
It is because of NPE on server side

**Comment by riuvshin** [comment]
nice, ty @evoevodin !
