### ISSUE TITLE
Unexpected error when import project in the IDE

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3766]
When I try to import  project by, then I have unexpected error

**Reproduction Steps:**
* Perform import any project in the IDE.

**Expected behavior:**
project should be imported and import project form closed.

**Observed behavior:**
there is unexpected error.

**Che version:** 5.1.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12

**Che cli.log output:** [cli.log.zip](https://github.com/eclipse/che/files/711324/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![import_in_che](https://cloud.githubusercontent.com/assets/5408906/22024322/458c1e3c-dcd2-11e6-9a20-e4903c6974ff.png)

**Comment by vzhukovs** [comment]
Proposal for the client side: https://github.com/eclipse/che/pull/3767
