### ISSUE TITLE
Update Wiki for PR Policy

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3773]
1. Provide single line in PR description that will be included into change log.
1. PR with features need to link to an associated issue/pr in docs repo before merge.
1. PR needs release notes section before merge.
1. Bug PRs change log is release notes. No need for PM sign off.
1. PM need to sign off on PRs with new features.
1. Does dev or TL need to add team/pm once it's ready for PM review?
1. Can we add link in generated description into all PR to wiki?

**Comment by bmicklea** [comment]
Policy: https://github.com/eclipse/che/wiki/Development-Workflow
PR Template: https://github.com/eclipse/che/pull/3839
