### ISSUE TITLE
Add Vert.x stack to default assembly

### ISSUE THREAD

**Issue by sbryzak** [eclipse-che/che#3774]
Add an Eclipse Vert.x (https://projects.eclipse.org/projects/rt.vertx) stack to the default Che assembly.

**Comment by bmicklea** [comment]
@sbryzak we largely rely on experts in each stack in the community to create and share their stacks. It's what the team at Zend / Rogue Wave did for PHP.  We're always happy to include new stacks in the default Che once they're ready and tested.

you can create a new custom stack by following the directions here: https://eclipse.org/che/docs/workspace/stacks/index.html

Once it's ready and tested you can submit it via a pull request as outlined here: https://eclipse.org/che/docs/workspace/stacks/index.html#adding-stacks-to-the-che-default-assembly

Do you have a stack already for vert.x?

**Comment by slemeur** [comment]
The PR for this issue is in progress here: https://github.com/eclipse/che/pull/3843
