### ISSUE TITLE
Right part stack is not restored after refresh page

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#3777]
**Reproduction Steps:**
1. Open some project
2. Open "Pull request" menu
3. Refresh page.

**Expected behavior:**
"Pull request"  menu is opened.
 
**Observed behavior:**
"Pull request"  menu is closed.

**Reproduction Steps:**
1. Open some project
2. Open "History" menu on the right part stack
3. Refresh page.

**Expected behavior:**
"History" menu displays git history.
 
**Observed behavior:**
"History" menu is empty.

**Che version:**   5.1.0

**OS and version:** Ubuntu 16.04

**Docker version:** 1.12.6 
![rightpartstack](https://cloud.githubusercontent.com/assets/5676062/22059056/ec3f8efc-dd73-11e6-96df-81123c022dd0.gif)

**Comment by ghost** [comment]
Can be reproduced in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
