### ISSUE TITLE
Failed to create a project from dashboard in Platformio stack

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#3782]
When user is trying to create a workspace with sample project based on stack Platformio (python based stack) the workspace creates without any problem, but import project fails.

![eclipse che - new project 2017-01-18 13-55-51](https://cloud.githubusercontent.com/assets/1968177/22063240/6f2630fc-dd86-11e6-8999-2de88daa8632.png)

Developer console denotes that during project import, server side method `api/project/batch` is called with request payloads:
```
[{"name":"platformio-arduino-blink","description":"Arduino blink sample","type":"cpp","commands":[],"attributes":{"language":["cpp"]},"options":{},"path":"/platformio-arduino-blink","source":{"location":"https://github.com/platformio/platformio-examples.git","parameters":{"convertToTopLevelProject":"true","keepVcs":"false","keepDir":"atmelavr-and-arduino/arduino-blink"},"type":"git"}}]
```
and batch creating fails with `500 Internal Server Error`. 
Server responded `/projects/.che2mktly/atmelavr-and-arduino/arduino-blink -> /projects/platformio-arduino-blink` 

See below:
![developer tools - http--localhost-8080-dashboard- 2017-01-18 13-56-29](https://cloud.githubusercontent.com/assets/1968177/22063345/f9993e96-dd86-11e6-9b3e-00191532c417.png)
![developer tools - http--localhost-8080-dashboard- 2017-01-18 13-56-48](https://cloud.githubusercontent.com/assets/1968177/22063352/ffc8fe5a-dd86-11e6-9ff6-cc602a04312d.png)

**Reproduction Steps:**
Create a workspace through the dashboard from stack `Platformio` and default sample project.

**Che version:**   5.1.0-SNAPSHOT (rev. 38e3aeb6f2c37972)

**OS and version:**    OSX 10.11.4

**Docker version:** 1.12.6

**Che cli.log output:**  -

**Comment by slemeur** [comment]
Cannot reproduce it

**Comment by gerisse** [comment]
same issue for me  :  i had this message : 
"error :  /projects/.cheoz6yja/atmelavr-and-arduino/arduino-blink -> /projects/pio-ard-blink "
when i choosed the arduino blink project in a platformio workspace.
Thanks.

**Comment by slemeur** [comment]
cc @skabashnyuk any hints?

**Comment by eivantsov** [comment]
@slemeur wrong URL

https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L1165

While https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L1167 does not exist here https://github.com/platformio/platformio-examples

**Comment by slemeur** [comment]
@eivantsov Then if the stack is not maintained/tested I recommend to remove it.
