### ISSUE TITLE
CHE-516 Java error "Target Java VM is not suspended" in time of debugging

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#379]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-516
Reporter:  Dmytro Nochevnov
Description: !target-java-vm-is-not-suspended-error_2016-02-17.png|thumbnail!

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/da3cbfc1b9d9ae93215a0f0622c0f7a32220555e
