### ISSUE TITLE
no_proxy is not applied when using samples.json

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#3790]
I edited a source location of an angular-patternfly-starter sample in `che/instance/data/templates/samples.json` Now the location is an internal github. NO_PROXY and no_proxy environment variables are set in the docker file. The workspace config recipe is
```
"recipe": {
        "type": "dockerfile",
        "content": "FROM marmolata/ubuntu_bashrc\nENV NO_PROXY github.wdf.sap.corp\nENV no_proxy github.wdf.sap.corp\nENV SBT_OPTS '-Dhttp.proxyHost=proxy.wdf.sap.corp -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.wdf.sap.corp -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=nexus.wdf.sap.corp'\nRUN git config --global http.sslVerify false\nCMD tailf /dev/null\n",
        "contentType": "text/x-dockerfile"
      }
```
When I do the command `git clone https://github.wdf.sap.corp/Marmolata/Demo.Calculator.git` in a workspace terminal then it clones the repo, but if I create a new angular-patternfly-starter project, then I have the following error.

![capture](https://cloud.githubusercontent.com/assets/22703481/22066223/45d6efce-dd8c-11e6-95b1-197c3a45d723.PNG)

I think it is likely to be a no_proxy issue. Can you please say, how repos are copied? I guess there should be a docker command like `docker -it <container> sh 'git clone ...'`

**Reproduction Steps:**

**Che version:**   5.0.0
**OS and version:**    Ubuntu 16.04
**Docker version:** 1.12.5

**Comment by TylerJewell** [comment]
We automatically set the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY values for your workspace when its created based upon the values in che.env.  There are some proxy values in there specific to how the workspaces are configured.  These values are set to the values that you have set within your Docker daemon and then we inherit them, apply them to Che's JVM and the workspaces automatically.  You can then edit che.env to override those default values.

So I am guessing that your recipe is overrdiing the defaults that we are already providing somehow.  And that is why the terminal is ok (our stuff) and the clone is not.

**Comment by aleksei-burlakov** [comment]
Thank you! I adjusted che.env and it worker.
