### ISSUE TITLE
Creating or import project in the running workspace on the dashboard does not work (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3797]
When I try to create or import a project in the running workspace on the dashboard, then the project is not created.

**Reproduction Steps:**
* Create workspace and run it.
* Go to 'Dashboard' -> 'Create Workspace' and create new project from template in the running existing workspace.

**Expected behavior:**
* the project should be created and opened in the IDE.

**Observed behavior:**
* the project is not created.

**Che version:** 5.1.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12

**Che cli.log output:** [cli.log.zip](https://github.com/eclipse/che/files/714221/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachments:
![create_project_running_ws](https://cloud.githubusercontent.com/assets/5408906/22069590/9fcf3788-dda1-11e6-9052-5d07a13406ff.gif)
![import_project_running_ws](https://cloud.githubusercontent.com/assets/5408906/22069601/a92d9888-dda1-11e6-92c4-93cd99f0aaff.gif)

**Comment by riuvshin** [comment]
@ashumilova  please take a look on this seems this pretty critical
