### ISSUE TITLE
Better handle server disconnection

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3802]
If the Che server crashes while a workspace is running and the IDE is in use there is no visual indication of what has happened. The workspace indicator remains green, some editing can still be done and files can still be selected although they open as blank.

We should have a way to notify clients (browser IDE, UD and Electron) that the server is unavailable so that the clients can create notifications for the user.

**Comment by ghost** [comment]
This is already done. When a server is down, the IDE shows a message - Server is not running. Ask your admin to start it.
