### ISSUE TITLE
Provide documentation for adding a stack to the default Che assembly

### ISSUE THREAD

**Issue by sbryzak** [eclipse-che/che#3804]
Currently the docs are here:

https://github.com/codenvy/che-docs/blob/master/src/main/_docs/workspace-administration/ws-stacks.md

The section "Adding Stacks to the Che Default Assembly" currently just says "//TODO".  The previous documentation at [1] instructs adding the stack to [2], however doing this has no effect and in fact this file can be removed completely and the list of default stacks in Che remains unchanged.

[1] https://eclipse-che.readme.io/docs/stacks#adding-stacks-to-the-che-default-assembly 
[2] https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json

**Comment by slemeur** [comment]
Hi @sbryzak.

This issue has already been fixed:
https://github.com/codenvy/che-docs/commit/29165deb63a3e2a444d449fbfe4394cc21830205

Sorry you were missing this part of the documentation.

**Comment by slemeur** [comment]
Could you explain what was your flow when you tried to update the default Stacks?

**Comment by sbryzak** [comment]
Hi @slemeur , apologies, this was fixed while I was in the process of submitting the issue.  Adding a stack as per the documentation does work for me now, the issue I was experiencing was from an unrelated cause.  We can close this issue.
