### ISSUE TITLE
Restarting of workspace after terminating - works wrong with autosnapshotting

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3805]
**Reproduction Steps:**
Go to a workspace and  invoke command: `kill -9 $(ps ax | grep java | grep ws-agent | grep conf | grep -v grep | awk '{print $1}')`. Wait dialog message and click on restart button

**Actual behavior:** After restarting we have creating snapshot from current workspace. Restart the workspace is failed after this one.
**Expected behavior:** The restarting of workspace should be finish without errors
**Che version:**  5.1.0

**OS and version:**    Ubuntu 14 TLS

**Docker version:** 1.13

**Comment by riuvshin** [comment]
@garagatyi @evoevodin guys please take a look on this. maybe this is client side issue idk.

**Comment by garagatyi** [comment]
Please provide more information if possible. Screenshot, websocket messages and server logs would be helpful

**Comment by riuvshin** [comment]
@garagatyi as I understand what happens is following, once you perform kill ws agent command in terminal IDE detect that connection to ws agent is lost, IDE shows pupup to restart WS, but start will fail because snapshotting in progress and WS start will fail.

**Comment by garagatyi** [comment]
If you are right then it is bug on client side

**Comment by riuvshin** [comment]
@vparfonov please take a look on this
