### ISSUE TITLE
Provide correct tooltip message if workspace doesn't have any command

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#3814]
Try to create a workspace without any commands. Then hover mouse on command list area and you'll see that tooltip message says `null`. See more on screenshot provided bellow:

![eclipse che - wksp-ty1p 2017-01-19 18-03-49](https://cloud.githubusercontent.com/assets/1968177/22114412/0c1a8f66-de72-11e6-81fc-98e3f2be96fe.png)

**Che version:**    5.2.0-SNAPNSHOT (rev. 1d8e31c63e8eae6f)

**OS and version:**    OSX 10.11.4

**Docker version:** 1.12.6

**Che cli.log output:**  -

**Comment by ghost** [comment]
Closed, as new intelligent command widget takes care of it.
