### ISSUE TITLE
Autocomplete for JSON sample works wrong

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3815]
**Reproduction Steps:**
Create JSON example project from wizard.  Open package.json and try to use autocomlete

**Expected result:** The autocomplete proposal should be pasted. The autocomplete widget should be closed.
**Actual result:** The autocomplete is not closed. Items may be pasted incorrectly.
**Che version:**  5.1.0

**OS and version:**    Ubuntu 14.0 TLS

**Docker version:** 12.1

**Comment by ghost** [comment]
Duplicate of https://github.com/eclipse/che/issues/5594
