### ISSUE TITLE
Wish - CLI notifies admin upon start that newer image exists if using "latest" tag

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3816]
When running the following Che CLI command to start Che:
`docker run eclipse/che start`
It started the previously download image while new ones are available.

We have added some enhancement for the nightly images:
https://github.com/eclipse/che/issues/3640
https://github.com/eclipse/che/pull/3671

But it seems we are still having the problem with `latest`

**Reproduction Steps:**

**Che version:**    5.0.0 / 5.0.1 / 5.1.0

**Comment by benoitf** [comment]
cli using latest : 
if dockerhub is there (user online), grab tags and see if there is a new version (like 5.1.0 > 5.0.0).
so it's more a notification like a hard update like we do for nightlies where we always pull images
User that is not using latest but is using a specific tag won't have this "notification" check

**Comment by JamesDrummond** [comment]
Think we need to change the description of this issue. It is normal not to automatically upgrade latest to a new version. User should only be be notified that a newer version exists for latest.

I actually think we should have a notification in the actual UI not CLI. In most cases I think users will not be restarting the server often and would be more like missed there(not good to block server start either in CLI to notify user). The popup in UI should be able to come up in any page(dashboard/workspace IDE etc) and need to be manually clicked to remove. If this an acceptable solution we should look into doing the same for all version(nightly, latest, 5.1.1 etc). For codenvy this popup would be shown for admin accounts only.

**Comment by TylerJewell** [comment]
This is an enhancemnet request - removing severity level.  Notifications in the UI on new versions has been talked about previously, but not something we are doing just yet.

**Comment by gorkem** [comment]
Closing as cli is no longer active
