### ISSUE TITLE
@media Print CSS for eclipse-che.readme.io

### ISSUE THREAD

**Issue by SamHasler** [eclipse-che/che#382]
Could some print CSS be added to the eclipse-che.readme.io stylesheet. As a minimum I'd suggest:

```
@media print {
  .section-left, img[alt="Fork me on GitHub"], .nav.pull-right, .suggest, header h1 {display: none!important;}
  body {font-size: 90%!important;}
  header, .main-content { padding: 0!important;}
}
```

**Comment by ddementieva** [comment]
Can you please specify why do you need to add @media print CSS to Che docs?

**Comment by TylerJewell** [comment]
That particular command will change the way the page prints on a printer.  I'll add it.
