### ISSUE TITLE
Image eclipse/che not Removed with CLI RMI 

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3820]
CLI image `eclipse/che` should be remove with CLI command `rmi`. Nightly and latest could have issues with incompatible CLI image and other che images.

**Reproduction Steps:**
Used codenvy CLI in example which uses same CLI.
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /root/codenvy-data:/data codenvy/cli:nightly rmi
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
WARNING: No swap limit support
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
INFO: (codenvy cli): Loading cli...
INFO: (codenvy download): Pulling image codenvy/cli:nightly

nightly: Pulling from codenvy/cli
Digest: sha256:d8af7e5e1f2c946efd223edcc52157aea1b3ffa62ff752e6cc94411745a8dffc
Status: Image is up to date for codenvy/cli:nightly

INFO: (codenvy rmi): Checking registry for version 'nightly' images
INFO: rmi !!! Removing images disables Codenvy and forces a pull !!!

      Are you sure? [N/y] y

INFO: (codenvy rmi): Removing codenvy Docker images...
INFO: (codenvy rmi): Removing haproxy:1.5.18-alpine...
INFO: (codenvy rmi): Removing nginx:1.10-alpine...

INFO: (codenvy rmi): Removing swarm:1.2.5...
INFO: (codenvy rmi): Removing registry:2.5.0...
INFO: (codenvy rmi): Removing postgres:9.5.4...
INFO: (codenvy rmi): Removing docker/compose:1.8.1...
INFO: (codenvy rmi): Removing zookeeper:3.4.9...
INFO: (codenvy rmi): Removing codenvy/socat:nightly...
INFO: (codenvy rmi): Removing codenvy/init:nightly...
INFO: (codenvy rmi): Removing codenvy/agents:nightly...
INFO: (codenvy rmi): Removing codenvy/codenvy:nightly...
INFO: (codenvy rmi): Removing codenvy/rsyslog:nightly...
root@debian:~# docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
codenvy/cli            nightly             ffd9bf04f3a8        22 hours ago        51.06 MB
```

**Che version:**    nightly

**Comment by TylerJewell** [comment]
This is expected behavior.  It is not expected that a container deleted the image that it comes from.  It would remove everything else, however.

**Comment by JamesDrummond** [comment]
Why is this not expected behavior? Not removing the cli image could potentially cause conflicts when newer latest and nightly images are pulled after running the cli rmi command but the cli image is a older latest/nightly version.

**Comment by TylerJewell** [comment]
It's a question of mutability.  The CLI's job is to operate on Che & its images, not itself.  The administration of the Che CLI image is done outside of the running container - where an admin can pull & rmi it using Docker's syntax.  

So the basic concepts are that the docker client is responsible for managing eclipse/che-cli, and then the eclipse/che-cli is responsible for its dependencies.

What we are doing with nightly is unnatural designed to support a particular type of unstable development channel.
