### ISSUE TITLE
The sample-serverservice example works wrong 

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#3824]
Build the IDE with serverservice extension, run it.

**Reproduction Steps:**
![anim](https://cloud.githubusercontent.com/assets/1640058/22142893/b375cc2e-df00-11e6-9e7d-963204219512.gif)

**OS and version:**    Ubuntu 14.0 TLS
**Che version:**  5.1.0
**Docker version:** 12.1

**Comment by ghost** [comment]
Che archetypes fix the issue - https://github.com/eclipse/che-archetypes/tree/master/plugin-serverservice-archetype
