### ISSUE TITLE
CHE-518 InvInvestigate and resolve problems in the selenium tests after first launching on CI

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#383]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-518
Reporter:  Maxim Musienko
Description: After first launching on CI (server location: nightly4.codenvy-stg.com) many tests have fallen with unexpected errors: like 'Stale Element Reference Exception'. Also in the IDE have been changed some refactoring features. We need check this in tests and do review actual issues related with selenium tests.

**Comment by ddementieva** [comment]
Cannot Reproduce
