### ISSUE TITLE
Some factories do not work on the getting-started page

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3836]
When I create  workspaces from template on the 'che getting-started' page, then several of them do not work. 

**Reproduction Steps:**
* Got to the -  http://www.eclipse.org/che/getting-started/cloud
* Create the workspaces from the list below:	
_eXo Task add-on_	
_Yeoman Alfresco_	
_.NET_	
_ASP.NET_

**Expected behavior:**
workspaces should be started

**Observed behavior:**
* workspaces do not started

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
_eXo Task add-on_	
![exo-ad-on](https://cloud.githubusercontent.com/assets/5408906/22155109/f5e87332-df36-11e6-804f-2d2630ffc445.png)
_Yeoman Alfresco_	
![yeoman_alfresco](https://cloud.githubusercontent.com/assets/5408906/22155115/fbb463c0-df36-11e6-8e6c-babeecc3e167.png)
_.NET_	
![net-console-app](https://cloud.githubusercontent.com/assets/5408906/22155123/0102cd30-df37-11e6-904f-9f2782b2c7e7.png)
_ASP.NET_
![asp net-web-app](https://cloud.githubusercontent.com/assets/5408906/22155129/0637b1d0-df37-11e6-84bb-7ff7d255dfdd.png)

**Comment by riuvshin** [comment]
please move this to codenvy/codenvy
