### ISSUE TITLE
"Terminal is currently unavailable. Retrying in 2 seconds..." infinite loop

### ISSUE THREAD

**Issue by ajaygm** [eclipse-che/che#3844]
**Reproduction Steps:**

1. Create a new workspace using an image that does not exist locally.
1. Start the workspace causing che to download the image.
1. While the image is being downloaded click on the "New Terminal" icon from within the workspace opened in the IDE.
1. Terminal window shows the message "Terminal is currently unavailable. Retrying in 2 seconds...".
1. Events window shows the following messages infinitely
"Failed to connect the terminal
Can not load term.js script"

**Expectation**
While the image is being downloaded the "New Terminal" icon should not be enabled.

**Che version:**    eclipse/che-server:5.0.0

**OS and version:**   Windows 7 

**Docker version:** 
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

**Che cli.log output:**

**Comment by TylerJewell** [comment]
Confirmed the issue - thanks for detailed report.

**Comment by JamesDrummond** [comment]
Please change sprint label.
