### ISSUE TITLE
Che 5.1.1 times out on F25

### ISSUE THREAD

**Issue by gbraad** [eclipse-che/che#3846]
Running `docker run eclipse/che start` on my Fedora 25 installation fails. I have tried to set the `CHE_HOST`, but no difference. The startup times out, but the dashboard can be opened using the hostaddress:8080/dashboard.

**Reproduction Steps:**
  1. On Fedora 25, using docker-latest, run `docker run eclispe/che start`

**Che version:**
5.1.1.

**OS and version:**    
Fedora 25 (updated)

**Docker version:**
```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-4.gitf499e8b.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      f499e8b/1.12.6
 Built:           Fri Jan 13 11:03:22 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-4.gitf499e8b.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      f499e8b/1.12.6
 Built:           Fri Jan 13 11:03:22 2017
 OS/Arch:         linux/amd64
```

**Che cli.log output:** https://gist.github.com/gbraad/7daae7837504d63973af7665e8a75f9d

**Comment by TylerJewell** [comment]
I spun up a Fedora 25 node on Digital Ocean and Che started without much issue.  Though the utility that we have embedded within Eclipse Che for auto detecting your IP address did not work and I had to manually set `-e CHE_HOST=<ip>`.

I noticed that on your system the IP address was set to your `docker0` interface.  Can you set CHE_HOST when you start to either the `zt0` internface IP address or another one that is likely to be exposed?

If you are planning to access Che from other computers than your current one, there is (temporarily) a bug and you will also need to add an additional property to `che.env` one time.  The variable is `CHE_DOCKER_IP_EXTERNAL` and it needs to be set to the same IP address as what is in `CHE_HOST`.

**Comment by gbraad** [comment]
@TylerJewell will try to do so later. And add a new comment with the results.

But the auto detection did fail for you?

**Comment by qband** [comment]
after set CHE_HOST, the two link below is still not right in browser
http://172.17.0.1:33140/api/
http://172.17.0.1:33140/api/languageserver/supported

**Comment by soleil0-0** [comment]
after set CHE_HOST, the link from dev machine is still not right in browser
http://172.17.0.1:33140/api/
http://172.17.0.1:33140/api/languageserver/supported

**Comment by ghost** [comment]
@gbraad you need to set `CHE_DOCKER_IP_EXTERNAL` to an externally reachable IP. You may not use CHE_HOST in this case at all.

**Comment by TylerJewell** [comment]
@qband - we have a temporary issue which requires the additional CHE_DOCKER_IP_EXTERNAL to be set to the same value as CHE_HOST inside of your `che.env` file.  Sorry about this.  We thought we had it fixed in master, but missed the cherry pick on this.

**Comment by soleil0-0** [comment]
@eivantsov @TylerJewell many thx, che show up now.
