### ISSUE TITLE
CHE-520 Project Explorer doesn't display just created project

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#385]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-520
Reporter:  Dmytro Nochevnov
Description: !project-explorer-doesnot-display-just-created-project_2016-02-17.png|thumbnail!

There was local projects linked into Che.

Project item appeared in _Project Explorer_ after refresh of browser's tab.

See [attached screencast for details|https://jira.codenvycorp.com/secure/attachment/81116/out.ogv].

**Comment by ddementieva** [comment]
Fixed
