### ISSUE TITLE
Add ability to see servers in the IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3853]
With 5.1.0 we removed the "Ops" perspective which was allowing to see the list of all servers.
We had, in the Dashboard, a table which allow the user to find those servers, per machine.

From UX point of view, the list of all servers should also be available within the IDE, even if the view has been added to UD, it is not convenient for the user to be forced to open the dashboard to get those informations.

We received few feedbacks around this trouble and need to draft a specification quickly on these use case. 

I propose to create a small button in the toolbar, which when clicked it displays a page with all servers (same information as in dashboard). Managing servers, will stay in the dashboard (until we have user request, I don't think it is necessary to provide 2 ways to manage the servers).

![servers-ports as editor](https://cloud.githubusercontent.com/assets/1636769/22268119/87cd451e-e286-11e6-9c4c-49bec7510463.png)

**Che version:**   5.1.0/5.2.0

**Comment by slemeur** [comment]
Attached mockup

**Comment by sr229** [comment]
Regarding the Mockup:
The Menu bar could use a consistent color, but that's just me.

**Comment by slemeur** [comment]
updated mockup

**Comment by TylerJewell** [comment]
I like the layout of the servers table itself.  But I think the button on the toolbar is not a good thing.  It's starting to make the toolbar really busy because we have different sized buttons and too many of them.  What if we just had it as a "Show Servers..." entry as a drop down to the preview tool bar button?

**Comment by slemeur** [comment]
It would work too, but gets tricky to find.

![screen shot 2017-01-24 at 23 04 29](https://cloud.githubusercontent.com/assets/1636769/22268891/866911dc-e289-11e6-9cac-1c4114443ddd.png)

**Comment by TylerJewell** [comment]
Well, what if...:
1. We relable "Preview" to just be "Servers",
2. We then have "Show all servers..." Be the botton entry (and left aligned).  I think this makes more sense to me.

Is there a reason that you have the "Preview" widget as wide as it is?  The main tool bar makes sense, but if we are not showing the preview URL in the widget, can it be shorter or wider?
