### ISSUE TITLE
Sample/Guide to implementing error mechanism for new language

### ISSUE THREAD

**Issue by elpddev** [eclipse-che/che#3856]
My use case includes implementing a new language plugin for CHE.

There are examples for code completion and syntax highlighting. What is the way to implement error hinting on an editor, like the errors the java editor provides ?

**Comment by slemeur** [comment]
Hi @elpddev, are you looking for those information along with the implementation of a language server or is it an implementation of a language plugin without following the protocol? 

We currently have an issue related to documenting the implementation of a language server: https://github.com/eclipse/che-docs/issues/70

**Comment by elpddev** [comment]
@slemeur 
Thank you. Currently I'm trying without a  language server implementation. The language is minimal. But It would be nice to have a guide to that too.

From looking at the maven project I understand that what is needed it  to implement a reconciling pattern the IDE will use when idle with an endpoint at the server that check the file and return the results of problems. Is that the right direction ?

**Comment by slemeur** [comment]
@elpddev Ok so you basically found information in the [developer guide for plugins](https://www.eclipse.org/che/docs/plugins/introduction/index.html) which introduce the basics to support a new language without using the language server. 

We don't have specific documentation about how error hinting could be handled. But I created the following doc issue to get that solved soon: https://github.com/eclipse/che-docs/issues/95

Until that, I think the direction you are taking is the right one indeed, but @evidolob and @vparfonov would you be kind to help @elpddev ? 

Thanks

**Comment by ghost** [comment]
@elpddev I'm closing the issue. If you have questions with your particular language server implementation open a new one and provide as many details as possible.
