### ISSUE TITLE
Workspace config json modification

### ISSUE THREAD

**Issue by Alexpud** [eclipse-che/che#3858]
Hi, for the past weeks i have been trying to make modifications on eclipse che requests to the REST API, with the purpose of adding a single parameter on the config field on the JSON for the workspace creation.

I managed to find where to modify, wsmaster module, and started modifying and wrote tests for the files that were modified to see if the module was still working.

The module passed all tests on the files that i modified, i checked using `mvn clean test`, and it seemed to work on theory but the validations didn't work when che was executed, rather were ignored.

My doubts are:

1. To make the modification on the body of the request, wsmaster is the correct module? If it isn't, what other modules i have to modify?

2. My second question is, which i think it is too much for you guys to answer but i will ask it anyway, can you give me tips to make this modification?

Since of now i thank you for your patience and help.

Che version: 4.7.0
OS: Ubuntu 16.04

**Comment by TylerJewell** [comment]
@skabashnyuk - this would be a statement about working with our DTO, I think.  So, I believe this belongs with team/platform to comment.

**Comment by skabashnyuk** [comment]
@Alexpud  can you please be more specific about what modifications you are talking about. Examples are welcomed.

**Comment by Alexpud** [comment]
@skabashnyuk It's simple, it means to add an extra variable on WorkspaceConfigDto, by looking at the code i managed to add the variable and it shows on swagger of compiled che.

To do that, i looked through files on wsmaster that seemed to be related to workspaceConfig and just put another variable on the declarations just like the name variable on WorkspaceconfigDto file. After modifying the files, i searched for the method which would receive the API request, and because of the name and it's contents, investigated workspaceService.

I put a simple clause to see if the variable i added was working, for that i used the LOG method that was used on the project to show the variable value. When i ran `mvn clean test`, it showed the variable so i thought it was a good start. A simple if clause was placed on create method to throw an exception if the variable i added was empty or non existent, again it worked on the tests.

When i compiled eclipse che again, the variable was still showing on swagger but it made no difference if i attached the variable on config or not, it created the workspace anyway.

Sorry for the long answer and thanks in advance.

**Comment by Alexpud** [comment]
@skabashnyuk 
Hi,
Before i go further i will call the copy of che that i am modifying the wsmaster as **cloneA,** and the other copy **cloneB**
After i posted my question i cloned the project again, **cloneB**,on a different folder to make modifications on the dashboard module of che. After my changes were done, i executed the compiled che binaries and  the change made to wsmaster on **cloneA**  that is on another folder, showed up.

After compiling the **cloneB** assembly with the command  mvn -pl '!assembly-ide-war' clean install``, the changes showed up. I am not sure what happened, maybe the changes were saved on cache somewhere?

The fact is, the command which i was using to compile the modifications made to dashboard, showed the modifications made on wsmaster, even if wsmaster belonged to another folder.

Could you guys tell me what the possible causes are for what happened?

Thank you and sorry for the trouble.

**Comment by ghost** [comment]
@Alexpud can you perhaps share your fork of Che so that we can take a look?

**Comment by Alexpud** [comment]
@eivantsov here is the link for the forked project [https://github.com/Alexpud/che.git](url), on the branch che-ufs-backend.

**Comment by skabashnyuk** [comment]
@Alexpud 
 - 4.7.0 is half year old branch
 - in ```che-ufs-backend``` too many things is going back and forth 
your intents for me is still unclear. 

Can you rebase your code with 5.1.0 , squash your commits and give a link to a single file that can explain what do you want to do.

**Comment by Alexpud** [comment]
@skabashnyuk 
Like you suggested, i did the modifications on the code based on 5.1.0 version, and got it working.  The link to the repository [https://github.com/Alexpud/che](url) and branch is test/extraVariable, the branch only has one commit. What i did was:

- I deleted .m2 folder and downloaded all dependencies again to avoid any problems with maven.
- I realized i was building the module wrong and built it correctly and all was working fine.

The motive behind  adding an extra variable on configDto was to see if how easy it was to do so, to add extra parameters to che DTO's, since on my college project i need to make modifications on che that will require modifications on existent DTO's or creation of them.

Once again, i thank you guys for your time and help.

**Comment by TylerJewell** [comment]
Great persistence.  Thanks for sticking with it.

**Comment by skabashnyuk** [comment]
@Alexpud  
>and got it working. 

Are we done with this issue? Can we close it?

**Comment by Alexpud** [comment]
Sorry, i will close it.
