### ISSUE TITLE
Che CLI: Improve diagnostic and `info` output

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#3859]
With the new CLI, many more people are able to run Che. However, there are challenges with providing timely support for those that are running the system. We would like to extend the system to make the output necessary for Che engineers to do diagnostics easier to capture.

This issue captures the specification for what should be done with the work.

1. Combine the concept of a `support` command with `info`. 
2. Have a basic info command, similar to `docker info`.
3. Simplify the output so that it's single line output with headers and indents
4. Display the digest of images that were loaded by interrogating the registry
5. Pull the list of all che.env properties that were customized
6. Simplify the output of cli.log - it's not readable
7. Add date / time stamp to cli.log output
8. Print out the full syntax line provided by the user when running the CLI - all arguments.
9. Optionally let "set -x" option for tracing perhaps with a global `--trace` option that can be applied to any command
10. Include the output of "docker info" in the output, if you were properly daemon connected
11. Potentially create a diagnostic package that includes /logs, cli.log, and docker info output
12. Include `info --network` detailed output in security package

Concept syntax and output.
`info [--trace] [--network] [--bundle]`

```
CLI:
 TTY: on/off
 Daemon: /var/run/docker.sock ... or DOCKER_HOST=<value>
 Image: <image-name>
 Command:
 Parameters: 
Mounts:
 :/data:
 :/sync:
 and so on...
System:
 Docker: docker4windows
 Proxy: <proxy-info>
 is_fast:
 is_initialized:
 is_offline:
 local_repo:
 local_assembly:
Internal:
 CHE_VERSION: <value> 
 CHE_INSTANCE          = /c/tmp/instance
 CHE_CONFIG            = /c/tmp
 CHE_HOST              = 10.0.75.2
 CHE_REGISTRY          = /version
 CHE_DEBUG             = false
 CHE_BACKUP            = /c/tmp/backup
Image Registry:
 image1=<value>
 ...
User Configuration: <not-initialized>
 FIRST_VALUE_UNSET=<value>
 ... List all values from che.env that are uncommented
```

**Comment by benoitf** [comment]
In the list of improvements

1. around logging
I think we could get rid of `INFO: (che cli): Loading cli…` trace and use something more helpful when ppl send few lines of logs copying the default output
something like : displaying the name of the cli (the image/product name), the version, and the docker remote that has been found with its version and if it’s native/boo2docker/docker 4mac
example : `INFO: Eclipse Che CLI nightly - using docker 1.12 / docker4mac`

2. Networking
- I thought that we might add the `default cheip utility ip` when (—network is used) 
- and use also “—net host” and displays all the network interfaces that are listed/found

**Comment by TylerJewell** [comment]
These are good additions.  I will put anything that has lots of output or needs to attach a file into the --diagnostic version keeping the ordinary info version simple and short.

**Comment by TylerJewell** [comment]
Here is the new CLI output when it is bootstrapping.   `INFO: (che cli): nightly - using docker 1.13.0 / docker4windows`

**Comment by TylerJewell** [comment]
https://github.com/eclipse/che/pull/3862
