### ISSUE TITLE
CHE-521 Git status output is different if 'Committer' has a name or has not.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#386]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-521
Reporter:  Aleksandr Shmaraev
Description: \* Open IDE and check that git user name(or email) is not set.
- Open a project, delete git repository (if it is).
- Initialize repository and check git status.
- Set the git user name(or email) repeat the actions with repository.
  Expected: the git status output should be same in the both cases. 
  Actual: the git status output is different.

**Comment by ddementieva** [comment]
Fixed by https://github.com/codenvy/plugins/commit/23028aa2479ef1243a3c034ac7d220543838af8f
