### ISSUE TITLE
Che doesn't update Project Directories properly and Immideately when switching branches on Git 

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#3860]
This is usually happens when you checkout a branch throught the CLI

**Reproduction Steps:**
1:) Clone a Repository

2:) cd throught the folder and run ``checkout <branch>``

3:) You would notice that the subfolders on the root folder doesn't update according to it's branch

**UPDATE** : It does switch but requires the Docker Machine to reboot to be able to check everything properly. Refresh still doesn't update it properly

**Che version:**    Codenvy 5.1.0

**Comment by ghost** [comment]
@sr229 can you reliably reproduce it? I failed to reproduce on Win 10 and Ubuntu.

**Comment by TylerJewell** [comment]
@sr229 - I just did a test on Mac and was not able to reproduce this specific sequence.  There is a small lag in updating the project tree files, but that everything is properly synchronized however.

**Comment by sr229** [comment]
@eivantsov 
This was done by making a  blank workspace then importing a project then running Git Checkout on the folder

**Comment by ghost** [comment]
@sr229 is it a public project? I have tried it with codenvy.io - project tree gets updated.

**Comment by sr229** [comment]
@eivantsov yes. Some files at the project tree somehow retains their version from the other branch instead of the current active branch.

I tried closing the tabs then run a refresh but to no avail. I restarted it and it somehow worked

**Comment by ghost** [comment]
@sr229 can you share your project? I have tried 3-5 projects having multiple branches and it worked for me. Maybe you can record a video?

**Comment by ghost** [comment]
@sr229 may I have an update on this one? I have tried Win 8 and 10, Ubuntu and MacOS. Project tree always reacted to branch changes.

**Comment by sr229** [comment]
I think it updated properly on the most recent Codenvy update.

Closing.
