### ISSUE TITLE
Default Values in che.env 

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3864]
Default commented out values in generated che.env file should match actual embedded default values. Below are some examples but we need to go through all and determine the best values.

I don't think we should change things that are clearly meant as examples such as `#CHE_WORKSPACE_VOLUME=/path/on/host:/path/in/workspace:ro,Z;/path/to/host2:/path/in/workspace2:ro,Z;` or `CHE_DOCKER_REGISTRY_AUTH_<insert-name>_URL=https://index.docker.io/v1/`

**Reproduction Steps:**
che.env examples of values that are not set to embedded default values.

#CHE_MACHINE_DEFAULT_MEM_SIZE_MB=1024
#CHE_DOCKER_ALWAYS__PULL__IMAGE=true

**Che version:**    Nightly

**Comment by garagatyi** [comment]
Notice that in that case developers will have to remember synchronize code, properties and che.env. So it quite possible that some default values will be outdated from time to time. So this task will have to be repeated from time to time. 
Also I believe some properties doesn't have single default value and depend on complex logic in code.

**Comment by JamesDrummond** [comment]
@garagatyi Understood. If there is not a single default value used everytime I think it's would be safe to exclude those. I will not get into how che.env is maintain with future code changes. Will leave that in the dev teams hand on how they want to handle that. They should be updated now though to be correct. This can confuse users to the true default "embedded" values when no value is assigned to an environment variable in che.env.

**Comment by benoitf** [comment]
@JamesDrummond is that issue is on how it is explained. Like clearly say it's an example value and not the default value if not set ?

**Comment by garagatyi** [comment]
I suppose users don't have to edit che.env until they want to change something. And if they need they don't change random variable but read docs or asks support. So I do believe it is safe to have there **examples** of values

**Comment by TylerJewell** [comment]
I wrote the original file and tried to use the defaults wherever possible and if it added clarity to state the default value intended within the comment section.  But yes we should try to capture the proper defaults.
