### ISSUE TITLE
Can't create an old version of che

### ISSUE THREAD

**Issue by ajaygm** [eclipse-che/che#3868]
I can't create an older version of che (tried with 5.0.0 and 5.0.0-latest).

**Reproduction Steps:**
1. Deleted all old images and containers related to che.
1. docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /C/ajay_temp/testProjects/docker/eclipse_che:/data eclipse/che:5.0.0 start

**Output**
> $ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /C/ajay_temp/testProjects/docker/eclipse_che:/data eclipse/che:5.0.0 start
> Unable to find image 'eclipse/che:5.0.0' locally
> 5.0.0: Pulling from eclipse/che
> 3690ec4760f9: Pull complete
> a301ca9a94b3: Pull complete
> 112bedd41daf: Pull complete
> 4541e9f1b1da: Pull complete
> 4d661e67dc06: Pull complete
> c0bd88284174: Pull complete
> Digest: sha256:4d48a7f648ea18437ae687353f55ce22941f506d647184bd3c527bb8e3ec74d4
> Status: Downloaded newer image for eclipse/che:5.0.0
> INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
> INFO: (che cli): Pulling image eclipse/che-ip:nightly
> INFO: (che cli): Loading cli...
> ERROR:
> ERROR: Your CLI version 'eclipse/che:5.0.0' is older than your installed version '5.1.1'.
> ERROR:
> ERROR: You cannot use an older CLI with a newer installation.
> ERROR:
> ERROR: Run the CLI with 'eclipse/che:5.1.1' to match the CLI with your existing installed version.
> 

**Che version:**    eclipse/che                    5.0.0 & 5.0.0-latest

**OS and version:**    Windows 7

**Docker version:** 

> $ docker version
> Client:
>  Version:      1.12.6
>  API version:  1.24
>  Go version:   go1.6.4
>  Git commit:   78d1802
>  Built:        Wed Jan 11 00:23:16 2017
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.12.6
>  API version:  1.24
>  Go version:   go1.6.4
>  Git commit:   78d1802
>  Built:        Wed Jan 11 00:23:16 2017
>  OS/Arch:      linux/amd64

**Che cli.log output:**

**Comment by mlabuda** [comment]
I think that's caused by still existing configuration in your local data folder /C/ajay_temp/testProjects/docker/eclipse_che. Try removing config files in /C/ajay_temp/testProjects/docker/eclipse_che and rerun the command. 

Removal of the Che instance should be done by calling destroy command. If you just kill running container and remove all containers, you will still keep configuration data what could cause problems with version compatibility in case of using Che of various versions.

**Comment by ajaygm** [comment]
**Fixed**

Restarted the Docker Toolbox docker-machine. Don't know the reason behind this though.

**Output**
```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /C/ajay_temp/testProjects/docker/eclipse_che:/data eclipse/che:5.0.0 start
INFO: (che cli): Checking network... (hint: '--fast' skips version and network checks)
INFO: (che cli): Loading cli...
INFO: (che cli): Checking registry for version '5.0.0' images
INFO: (che download): Checking for image 'puppet/puppet-agent-alpine:4.6.2'...found
INFO: (che download): Checking for image 'registry:2.5.0'...found
INFO: (che download): Checking for image 'eclipse/che-init:5.0.0'...not found
INFO: (che download): Pulling image eclipse/che-init:5.0.0

5.0.0: Pulling from eclipse/che-init
e110a4a17941: Already exists
c6be0cda3022: Already exists
b883875a9222: Already exists
d7e1053f3043: Already exists
588fa03c26ba: Pull complete
d6098f4460bc: Pull complete
9609889c3387: Pull complete
6e6e19f86084: Pull complete
bb0743d3c38e: Pull complete
2aee681fe8c0: Pull complete
Digest: sha256:cf862e6d5ba201d2b60f936384a126b3b492038c93fdd11114f833182905b08e
Status: Downloaded newer image for eclipse/che-init:5.0.0

INFO: (che download): Checking for image 'eclipse/che-server:5.0.0'...not found
INFO: (che download): Pulling image eclipse/che-server:5.0.0

5.0.0: Pulling from eclipse/che-server
3690ec4760f9: Already exists
7fe36e46c847: Pull complete
9a696c438d59: Pull complete
2afbf443d110: Pull complete
Digest: sha256:b799245f6786ddea23e176ce23959ab7011eed84aa759b9befccca0527de0f95
Status: Downloaded newer image for eclipse/che-server:5.0.0

INFO: (che init): Installing configuration and bootstrap variables:
INFO: (che init):   CHE_HOST=192.168.99.100
INFO: (che init):   CHE_VERSION=5.0.0
INFO: (che init):   CHE_CONFIG=/C/ajay_temp/testProjects/docker/eclipse_che
INFO: (che init):   CHE_INSTANCE=/C/ajay_temp/testProjects/docker/eclipse_che/instance
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         port 8080 (http):       [AVAILABLE]

INFO: (che start): Starting containers...
INFO: (che start): Services booting...
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Booted and reachable
INFO: (che start): Ver: 5.0.0
INFO: (che start): Use: http://192.168.99.100:8080
INFO: (che start): API: http://192.168.99.100:8080/swagger

```

**Comment by ajaygm** [comment]
@mlabuda An observation in my environment... I never see any files in that folder (/C/ajay_temp/testProjects/docker/eclipse_che). What should I be expecting there?

> Removal of the Che instance should be done by calling destroy command. If you just kill running container and remove all containers, you will still keep configuration data what could cause problems with version compatibility in case of using Che of various versions.

I'm guilty of this. This could be the reason.

**Comment by TylerJewell** [comment]
@mlabuda - we have built in some mechanisms to prevent using the wrong images against an installation of a different version.  So, hopefully if @ajaygm did this, the CLI was smart enough to catch the issue and stop with a grumpy error message.

**Comment by mlabuda** [comment]
@TylerJewell I am aware of those mechanism so that was my first though that there are stil configuration files in local data directory and (probably this file, I have not looked into scripts yet) che.ver.do_not_modify contains incompatible version. ;)

**Comment by TylerJewell** [comment]
I think we try and designed the system so that if you have an initialized folder that it will immediately fail if the image version does not match the `che.ver.do_not_modify` file.  If there is some edge case where the system could get past this check, then we should consider that and add in extra defenses into the bootstrap.
