### ISSUE TITLE
Recipe url is not pasted in the field(regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3869]
When I try to paste recipe url in the field then it is not pasted.

**Reproduction Steps:**
* Go to 'Workspace' -> 'Add workspace' -> 'Runtime' -> 'Stack import' and try to paste recipe url (e.g. https://gist.githubusercontent.com/idexmai/6918415efa88276bdf028756adc8b9fb/raw/04ea419e25e02d010a03d75278606c3e2218e1e6/composeJavaStack).

**Expected behavior:**
* recipe should paste in the field

**Observed behavior:**
* recipe url is not pasted.

**Che version:** 5.2.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachments:
![paste_recipe_url](https://cloud.githubusercontent.com/assets/5408906/22247208/3850764a-e241-11e6-8d53-b73cba09b505.png)

**Comment by riuvshin** [comment]
rise to p2 because this is pretty bad issue...
@ashumilova we should try to get this fixed for 5.2.0
