### ISSUE TITLE
CHE-522 Unexpected the 'Failed to commit' message in the 'Events' after git commit

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#387]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-522
Reporter:  Aleksandr Shmaraev
Description: \* Open a project and check git working directory clean.
- Perform git commit.
  Expected: the git console output and event message should be the same.
  Actual: the event message is:  'Failed to commit'.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/5670da396c758d0e7c6987e6c486ca5cdd746218
