### ISSUE TITLE
Change workspace idle timeout

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#3873]
The workspace timeout in the `che.env` file and default hard coded idle timeout should be changed to 4 hours.

che.env
```
# Idle Timeout
#     The length of time that a user is idle with their workspace when the system will suspend the
#     workspace by snapshotting it and then stopping it. Idleness is determined by the length of
#     time that the user has not interacted with the workspace, meaning that one of our agents
#     has not received instructions. Leaving a browser window open counts as idleness time.
#CHE_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS=600000
```

Related to https://github.com/codenvy/codenvy/issues/1592

**Comment by riuvshin** [comment]
@benoitf how we can change default value of that ENV var? in codenvy that env var used to generate property file so I;m able to set default in codenvy.pp but in che you did it in other way and it's not obvious how to change default value. (i think it is hardcoded in code but not sure)

**Comment by benoitf** [comment]
@riuvshin AFAIK there is no idle timeout in CHE it's in codenvy only
https://github.com/codenvy/codenvy/blob/df5323573f867560cbde17aaf6ffa33fb4ff2c9a/wsmaster/codenvy-hosted-workspace-activity/src/main/java/com/codenvy/activity/server/WorkspaceActivityManager.java

so I think the che.env shouldn't have this property

**Comment by riuvshin** [comment]
@benoitf that is exactly what I thought. @JamesDrummond we just need to remove that from CHE

**Comment by JamesDrummond** [comment]
@riuvshin @benoitf Are we sure of this. Maybe things have changed but when I used che before dockerized codenvy I would get idle timeouts with che from what I remember.

Might be wrong but just want to double check :)

**Comment by riuvshin** [comment]
I think there is not such code che at all

**Comment by benoitf** [comment]
@JamesDrummond the class is in codenvy so it's not possible in che
