### ISSUE TITLE
Allow combining multiple stacks to a new one

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#3878]
Please add support for combining multiple stacks to a new one on the http://eclipse-che:8080/dashboard/#/create-project project dashboard.

Since the custom stack documentation seems to be not available for now (at least the link in nightly points to a site telling me that) and I could easily put together what I need by just picking multiple items from the stack library, this seems like a natural thing to offer for people who have custom needs but which aren't deeply familiar with eclipse che just yet - at least from a usability perspective, I'm not sure how technically feasible it is.

**Reproduction Steps:**
1. Start fresh eclipse che install with empty data folder
2. Go to project dashboard
3. Try to somehow choose multiple stacks to be combined to a new one (what I observed: I see no obvious way on how to do it)

**Che version:** 
Your CLI version is 'nightly'.
Your installed version is 'nightly'.

**OS and version:**     Fedora 25 / Linux cyberman 4.9.3-200.fc25.x86_64 #1 SMP Fri Jan 13 01:01:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Docker version:** 
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
**Che cli.log output:** 
Probably not relevant

**Comment by ghost** [comment]
Alternatively, a smaller set of choices for "stack building bricks" or something similar that can be dragged together in a simple UI to form a stack would also help new users (especially those not familiar with docker) to throw together all software they need in a trivial manner for a new stack.

The current UI seems perfect for power users (of which I am probably one), but a bit needlessly complicated for someone who e.g. just needs python, git and maybe gnu make or some other standard choices thrown together - due to the lack of an easy "I need software A, B, C and that's all" combination screen.

**Comment by bmicklea** [comment]
Hi @JonasT, you can find all the dockerfiles associated with our stacks here: https://github.com/eclipse/che-dockerfiles/tree/master/recipes

It's fairly easy to choose the one that's closest to your needs, copy it into an editor then add the relevant commands (likely the RUN commands that get the packages) from another stack or two to your original in the editor.

The only thing is to watch out for situations where you add software like MySQL which might require you to EXPOSE a new port.

You can always find Che documentation here: https://eclipse.org/che/docs/ and the [stacks](https://eclipse.org/che/docs/workspace/stacks/index.html) documentation and [recipes](https://eclipse.org/che/docs/workspace/recipes/index.html) documentation are part of that.

I'd recommend reading the whole Workspace Automation section when you have time, it's not terribly long and deals with what is really the heart of Che.

**Comment by ghost** [comment]
@bmicklea I wrote my own Dockerfile from scratch, but thanks for the help :smile:
I suggested this for newcomers unfamiliar with Docker.

**Comment by TylerJewell** [comment]
@jonast - I don't see how this practically can be implemented.  Most `RUN` syntax for Dockerfiles runs in conflict in different types of Docker images. Bitnami has been working for two years on a stack editor API to provide some mechanism for this capability.  Also I think a lot of the register security search capabilities are trying to work on similar items.  

It's a super complicated scenario and I think we would need to partner with a vendor to make such a capability possible and stable.

**Comment by ghost** [comment]
I think you are overthinking what would be necessary.
It would be completely sufficient if this just allowed a few common pieces of software, it doesn't need to work with *arbitrary* Dockerfiles or all software choices. It's still completely ok to point the user to advanced finished stack files or to write Dockerfiles on their own for more complicated scenarios.

However, I don't understand why there can't be a simple collection of software choices (internally simply represented by the apt-get lines necessary for python, gcc, ...) prepared for one single fixed underlying system (e.g. latest Ubuntu LTS) where the user can simply click checkmarks on what they want, and get the resulting image. This would already allow a beginner to put together much more useful images than the current fixed premade stack choices of EITHER a python image, OR a C++/gcc image. Not that those premade stack choices are bad, and for some more hard-to-create stacks certainly useful, but being unable to even combine the simplest-to-install things in some easy way without writing custom Dockerfiles seems like a limitation that should be fixed.

**Comment by TylerJewell** [comment]
The list of choices would have to be different for each type of Linux distro.  It would be virtually impossible to test the various configurations, even if we only wanted to provide 3-5 popular components for each type of distribution.

This is a problem that we have spent a lot of time thinking through. We have not found any straight forward way to simplify the concept the way you are thinking.  If we could create such a basic abstraction I would agree with you on the materiality of its value. But this problem is in many layers of an onion that doesn't lend itself to simplification easily :)

**Comment by ghost** [comment]
It is much more doable if you limit to one single distro, and just a few simple choices with known few interactions (e.g. installing python is very unlikely to interact with gcc).

Again, I agree that making everything combinable with everything is futile. Also, I think the UI shouldn't even suggest you could do that. But adding a simple "Multi-software choice Image builder" which has some obvious label at the top when you enter it that it only works with a few limited options and if you need more you need to write a custom Dockerfile, would already make che a lot more beginner friendly.

Adding an UI possibility to just drag together any of the existing stacks arbitrarily is a bad idea, and I'm not suggesting that.

**Comment by TylerJewell** [comment]
I don't see the value in that for a beginner.  

Let me elaborate why.  

If you are truly a beginner, then you should not be doing custom stacks and require a builder of a limited nature. In that situation, we should have the stack library make it really easy for you to find a stack that has those elements already included inside for you.  If there is something wrong with the stack library and it is insufficient, then we should be pressured to add to that and make the search / sort of the library much better (which we will be doing very shortly - see the epic on the revising of workspace creation workflow for UD).  This would certainly hold true for the situation where you are only going to allow for a small number of widgets to add in - say <10.

However, if the role that you are seeking is someone who is not a beginner user, but is a beginner stack developer (beginner devops) then in that case giving a UX to add / remove just a couple items doesn't help them.  They really do need the advanced capability of a partner, ways for us to provide a smarter way to write Dockerfiles, or (and what I think is the best way) is an approach to stack lifecycle management that is more like Nix package management on the command line (or in the UX itself). This Nix approach provides a structured way to working on net new stacks so that you can start simply and prevent yourself from making mistakes along with having a nice rollback mechanism.

**Comment by ghost** [comment]
> If you are truly a beginner, then you should not be doing custom stacks and require a builder of a limited nature

WIth beginner I mean someone who doesn't know che or docker, but is a developer. Unless you work  on a super trivial project, the likeliness that as a developer you will need more than EITHER python OR gcc is pretty high - at least more than marginal. **Prepared stacks for everything can never work for this scenario ever.** As you said above there are too many combinations even with just a few choices, and if you added every such combination someone would ever need the library would explode.


> However, if the role that you are seeking is someone who is not a beginner user, but is a beginner stack developer

That is not the kind of person I am talking about. I am purely talking about someone who used eclipse or visual studio, and has no idea of docker *and most importantly also doesn't necessarily want to learn it*.

Of course if you want developers to be familiar with docker to use che beyond the most trivial setups, then I guess that's fine. I just see potential here to broaden the audience, and I think limiting yourself to the docker-savvy crowd is a problem.

Edit: fixing quote formatting

**Comment by TylerJewell** [comment]
Even for the beginner scenario that you describe, we believe that a richer library of default stacks is the preferred way to go.  Of course we would not provide permutations for all of the key items, but we can provide default stacks that are tied to a common programming language or framework.  Ie, if you ask for Python, there should be a Python stack that most likely has 99% of what a developer needs to start on a project.  The same for NodeJS.  OS-specific utilities should generally be included like curl.

I struggle to image a list of <10 major framework or language items that a beginning user would want to start with that couldn't be packaged into a set of well-tested default stacks in the library that are really easy to find / use.

**Comment by ghost** [comment]
> Of course we would not provide permutations for all of the key items, but we can provide default stacks that are tied to a common programming language or framework. Ie, if you ask for Python, there should be a Python stack that most likely has 99% of what a developer needs to start on a project. The same for NodeJS. OS-specific utilities should generally be included like curl.

This is basically the gist of the argument. It boils down to whether you assume most real-world projects only use *one* big framework, and whether you want to require people to become devops- and docker-familiar to work around this if it doesn't.

> I struggle to image a list of <10 major framework or language items that a beginning user would want to start with that couldn't be packaged into a set of well-tested default stacks in the library that are really easy to find / use.

I am suggesting this purely because I think requiring *combinations* might be not as rare as you think. However, I can only speak for myself, but I instantly found myself in a position for an actual real world project where I needed two frameworks that were in different stacks. Maybe that is super rare, I don't know good statistics on that. I know Dockerfiles so I could fix that, but I instantly thought "what would someone coming from eclipse / ... do here?".

Obviously fixing that can only go so far (very limited choices or otherwise it becomes untestable), and maybe it's not worth it. I am suggesting for at least the most basic building blocks it might be, but that's just my opinion.

You seem to have already made up your mind on what to choose here, so I won't barge into this discussion further. I'm just trying to explain where I am coming from.

Edit: fixed wrong quote

**Comment by TylerJewell** [comment]
I do understand where you are coming from. But, again, my point is that I cannot imagine what that limited list of components would be.  And I think most any reasonable person would struggle to identify what that list would be, too. We have tried developing this small list of components that you may want to mix and match, but every time it happens there is either a) no consensus that the list is accurage, or b) if the list is reasonable and small then any gaps can be reflected in the default ready-to-go stacks (which are all moving to alpine to make them as simple and small as possible), or c) there is this gravitational pull to amke the list much larger, circling back to the original issue of complexity.

If the thinking is that developers would like to start with a blank alpine stack and then give them 4-6 components (and nothing else that they can add to that), we could do that. However, what you will find in that situation is that even if it is something like python, there are other dependencies that have to be added, and those dependencies are reflected in the default stacks.  When you analyze the gaps between doing a minimal stack editor vs. what is contained in the default stacks, the default stacks are not adding a huge amount of heft / weight.

There is also an infrastructure benefit to the default stacks - there is image caching work that is done in a Codenvy distributed setting. So if we end up encouraging a lot of custom Dockerfiles to ultimately build something that is largely identical to images that already exist, we can impact distributed system performance by avoiding distribution cache of images.

I take every request seriously and think through the end user implications of them.  I believe that stack lifecycle and management is by far the most serious issue to the adoption of cloud IDEs. I think that while the noob user is important, I particularly think making stack editing a professionals tool is even more important, and we fall far short in that area today.

**Comment by ghost** [comment]
Yea I see that makes sense... you have probably thought about this problem a lot more already than I have! I guess under that light it might sense to close this ticket if there are no plans to implement, unless you want to keep it open for others to chime in with additional ideas or discussion.

---
On a slightly related note, have you considered making a sort of graphical wizard for editing Dockerfiles? Something like this:

```

                  Base system: [Ubuntu 16.04]


Step 1: [Run command (RUN)]    apt-get install -y python3                Computing result...
                              -----------------------------------

                     [Add additional step]
```
The "Computing result..." could already run the step in the background and change to a green tick or a red cross, indicating a problem (with the click allowing to see the terminal or something). The button `[Add additional step]` would insert a new Step defaulting to "(RUN)", and a new empty run step could display text like "Click here to see suggestions..." to open a popup with apt-get example commands to give the user an idea what to do. Some sort of `[Edit Dockerfile manually]` expert mode button could lead to the actual Dockerfile for people who know how to edit it.

Such a wizard might make it a lot easier for new people who have no idea of Docker to specify a new completely custom stack and get a better idea of what they're doing.

If you think it's a good idea I can file a feature request ticket :smile:

**Comment by TylerJewell** [comment]
I prefer to leave the issue open for others to comment for another month.  But I did write my statement as I am mentally preparing for the idea of closing this issue, only to be replaced with what is likely to be a much more sophisticated epic related to the lifecycle management of stacks themselves, for which we are starting to have (dare I say) dozens of concepts relating to it.

I think your idea and approach for graphical wizard for the construction of Dockerfiles is really sound.  I like it a lot.  Something like that would probably be great as another open source project as a starting point.  The Docker build subsystem doesn't have utilities for providing status and events and programmability of the build process itself, so we'd have to develop a bit of a service to add nice programmability to that (relatively well structured) process.

If that was a nice service that offered those sorts of structure, then it would be easy to provide a client IDE / editor experience that was interactive to it.  Select the base image, test a series of RUN commands, combine multiple RUN commands together, add ENV, and some sort of way to test ENTRYPOINT / CMDs.
