### ISSUE TITLE
Link to stack documentation is incorrect in the product

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3879]
On the stack editing page, there is a link to the stack documenation which is still pointing to readme.io

**Che version:**    5.1.0

**Comment by JamesDrummond** [comment]
Needs to refer to `/docs/workspace/stacks/index.html`. 

@skabashnyuk Is this for your team? If so can you add team label?

**Comment by skabashnyuk** [comment]
I think no.

**Comment by slemeur** [comment]
Fixed by https://github.com/eclipse/che/pull/3881
