### ISSUE TITLE
readme.io site is still unreachable.  When would that documentation site be available?

### ISSUE THREAD

**Issue by kiakj** [eclipse-che/che#3880]
https://eclipse-che.readme.io/ redirects to an inactive site

**Comment by benoitf** [comment]
@kiakj you may find the documentation at https://www.eclipse.org/che/docs/

**Comment by TylerJewell** [comment]
@kiakj - can you tell us where you sourced the wrong URL?  We have been working to remove all references from any existing site or google searches, but still have some lingering ones.  Readme does not provide us a redirect option, so we have these weird errors from time to time.

**Comment by ajaygm** [comment]
@TylerJewell 
Was searching for "che.env" in Google and got a reference to...

> Wordpress in Che · Eclipse Che
> https://eclipse-che.readme.io/docs/get-started-with-wordpress-and-che
> Click New Project and import a Wordpress repository and set up the right environment for it. Select Source. Let's import WP from an official WordPress GitHub ...

**Comment by TylerJewell** [comment]
Thanks, guys - we need to do more to get Google to reindex for certain terms to only pick up our new site.

**Comment by ajaygm** [comment]
CHE_WORKSPACE_VOLUME search on Google gives link to 

> Config: Security · Eclipse Che
https://eclipse-che.readme.io/docs/config-security
Exposing host file system files/folders through volume mounts such as environment variable CHE_WORKSPACE_VOLUME and giving workspace/docker ...

Let me know if I should stop reporting these now on.

**Comment by TylerJewell** [comment]
Thanks for identifying these.  The Google searches are an ongoing issue.  However, some of the others we can find and fix.

**Comment by cstrutton** [comment]
A quick google search for "eclipse-che.readme.io" (with the quotes) came up with 1450 hits including several from the github site and docker hub on the first page...
