### ISSUE TITLE
circular dependency in dockerfiles

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#3882]
@TylerJewell @benoitf 
during release I was faced with issue where I can't build tagged docker images due to circular dep

we have:
cli tests in base image wants to pull che-cli which is `FROM che-base`.

hopefully @benoitf showed me that there is a way to skip those tests so Im able to continue release but we have to fix this.

**Comment by benoitf** [comment]
I include @mlabuda as part of the discussion.

from what I see, the issue come from the fact that we tests code of the "base" image with the "cli" image.
- so either the test code is not at the right place (like all integration tests of che cli should be in che cli/ folder and not inside base)
- or we need to test the `base` image when we're inside `base/` folder and not the "cli" image (and then we test `cli` image in `cli/` folder

**Comment by mlabuda** [comment]
Yeah, that's the chicken-egg problem we were discussing in PR #3700 along the way. Problem is, if we move tests to cli folder, we still have dependency on other image - eclipse/che-bats which is in dockerfiles/bats folder. So having tests in cli could fix circular dependency but we would keep other dependency - cli on bats image. If it is ok and acceptable, I can fix it.

**Comment by benoitf** [comment]
@mlabuda yes I think that it's ok to have integration tests of cli depending on bats as bats image is not depending on che-base

Thus, it would be great to have also unit tests (for now it's more integration tests) and these unit tests could go along with "base/ folder" where we test the sh functions that are stored in that folder


so : unit tests close to the folder where they are dedicated.
and integration tests : where the CLI image is provided. (in this case it's cli and not base)

**Comment by mlabuda** [comment]
Once #3870 is merged, I will move tests to CLI folder and update env vars for test execution properly.

Problem with unit testing is as I wrote in #3700 the fact that functions in scripts are not write as a functions but more like procedures. It requires huge refactoring in almost all scripts to have functions (units) for unit testing.

**Comment by benoitf** [comment]
@mlabuda ok

@mlabuda we could start with a minimal refactoring (like extracting one critical method of maybe a file that is not library.sh but smaller one) and introduce unit test.
Then once unit tests setup is there we could iterate.
