### ISSUE TITLE
CLI - Create graceful and forced stop options

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#3886]
Eclipse Che is implementing a REST service that will offer a graceful shutdown of all services. Today, when we stop the server, Tomcat will be stopped if it has not naturally stopped within 4 minutes. If you have a large number of running workspaces, you may want them to all be stopped (with appropriate snapshots) before initiating Tomcat shutdown.  This REST service executes this process.

We need to extend the CLI to support two forms of stop:
1. forced stop (essentially what we do now where we just stop all containers without concern for internals)
2. graceful stop (default - which will execute the REST service).

The REST [service is documented here](https://github.com/codenvy/codenvy/issues/1568).  For Codenvy variations of this implemementation, it will require an admin token to complete.

The syntax:
```
eclipse/che stop [--force] [--user username] [--password password]
```
The `[--force]` is the current approach to stopping. The new default would invoke the REST service first.  We would then need to implement a periodic polling mechanism that prints out appropriate status while the stopping process is completing.  In the Codenvy variant, we will need to also ask for username / password on the command line to proceed.  These parameters can optionally be provided as parameters.

**Comment by benoitf** [comment]
issue for che for REST API is https://github.com/eclipse/che/issues/3892

**Comment by TylerJewell** [comment]
We discussed some implementation details:
1. We may opt to use custom action to interact with REST service.
2. We will not need any prompts for Che shutdown - we may need them for Codenvy shutdown.

**Comment by benoitf** [comment]
Adding pull request https://github.com/eclipse/che/pull/3968
