### ISSUE TITLE
che init does not create any files in host folder

### ISSUE THREAD

**Issue by ajaygm** [eclipse-che/che#3887]
I wanted to generate the che.evn file using the che init command, but the host folder mounted to /data always remains empty.

**Reproduction Steps:**
I tried the following che init command as specified [here](https://eclipse.org/che/docs/setup/configuration/index.html)
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /C/ajay_temp/testProjects/docker/eclipse_che:/data eclipse/che init
```
The results were the same with the che start command too i.e. the host folder corresponding to the /data folder was always empty.

**Che version:**    
> Your CLI version is '5.1.1'.
> Your installed version is '5.1.1'.

**OS and version:**    Windows 7

**Docker version:**   
> $ docker version
> Client:
>  Version:      1.12.6
>  API version:  1.24
>  Go version:   go1.6.4
>  Git commit:   78d1802
>  Built:        Wed Jan 11 00:23:16 2017
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.12.6
>  API version:  1.24
>  Go version:   go1.6.4
>  Git commit:   78d1802
>  Built:        Wed Jan 11 00:23:16 2017
>  OS/Arch:      linux/amd64
> 

**Che cli.log output:**

**Comment by TylerJewell** [comment]
You are on boot2docker with windows7?  If so, then you are using virtual box and only folders that are subfolders of %userprofile% are writable.  It's a limitation of vbox.

**Comment by TylerJewell** [comment]
Interestingly - we just committed a fix a day or two ago that will try and detect boot2docker better and print warning messages about this when you start.

**Comment by ajaygm** [comment]
@TylerJewell 
> You are on boot2docker with windows7? If so, then you are using virtual box and only folders that are subfolders of %userprofile% are writable. It's a limitation of vbox.

Yes I'm using boot2docker with Win7. Will try with user profile location and report back.

> Interestingly - we just committed a fix a day or two ago that will try and detect boot2docker better and print warning messages about this when you start.

Don't remember seeing any warning on 5.1.1. Was it on nightly or latest?

**Comment by TylerJewell** [comment]
Yeah, it would only be on nightly at this point.  This is the PR for it - it will show up in 5.1.2 which is in the release process now.  It should be in nightly.

https://github.com/eclipse/che/pull/3848

**Comment by ajaygm** [comment]
Confirming the warning on nightly... Good info for a newby :+1: 

```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /C/ajay_temp/testProjects/docker/eclipse_che:/data eclipse/che:nightly start
WARN: Boot2docker detected - ensure :/data is mounted to %userprofile%
INFO: (che cli): Checking network... (hint: '--fast' skips nightly, version, network, and preflight checks)
INFO: (che cli): Loading cli...
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che
Digest: sha256:68d499f321da6d5d25b8348ade7066b4d2bfd79ec650285f4e77901ec7987eb4
Status: Image is up to date for eclipse/che:nightly

INFO: (che start): Eclipse Che is already running
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Ver: <not-configed>
INFO: (che start): Use: http://192.168.99.100:8080
INFO: (che start): API: http://192.168.99.100:8080/swagger
```

Also the init command created the files now.
```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/am185011/testProjects/docker/eclipse_che:/data eclipse/che:nightly init
WARN: Boot2docker detected - ensure :/data is mounted to %userprofile%
INFO: (che cli): Checking network... (hint: '--fast' skips nightly, version, network, and preflight checks)
INFO: (che cli): Loading cli...
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che
Digest: sha256:68d499f321da6d5d25b8348ade7066b4d2bfd79ec650285f4e77901ec7987eb4
Status: Image is up to date for eclipse/che:nightly

WARN: (che init): 'nightly' installations cannot be upgraded to non-nightly versions
INFO: (che download): Pulling image eclipse/che-init:nightly

nightly: Pulling from eclipse/che-init
e110a4a17941: Already exists
c6be0cda3022: Already exists
b883875a9222: Already exists
d7e1053f3043: Already exists
cc7c1372b739: Already exists
73912c33a318: Pull complete
dd0f7724858d: Pull complete
a3960e3aecf9: Pull complete
bb0743d3c38e: Pull complete
2aee681fe8c0: Pull complete
Digest: sha256:12c9f2531b2dfd961875fa0885ab4c76ad245393665d8809a7bfdd62f49d3b15
Status: Downloaded newer image for eclipse/che-init:nightly

INFO: (che download): Pulling image eclipse/che-server:nightly

nightly: Pulling from eclipse/che-server
b7f33cc0b48e: Already exists
6ccc15629152: Already exists
1fccd90604b3: Already exists
e4bd5300f218: Pull complete
Digest: sha256:8b5b9794082b1c34ee0a094f0875fdaa75be0e4b4317fd626adede0ef62a63a3
Status: Downloaded newer image for eclipse/che-server:nightly

INFO: (che init): Installing configuration and bootstrap variables:
INFO: (che init):   CHE_HOST=192.168.99.100
INFO: (che init):   CHE_VERSION=nightly
INFO: (che init):   CHE_CONFIG=/c/Users/am185011/testProjects/docker/eclipse_che
INFO: (che init):   CHE_INSTANCE=/c/Users/am185011/testProjects/docker/eclipse_che/instance
```

Thanks @TylerJewell
