### ISSUE TITLE
Slow performances for opening files operations

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3889]
The performances for opening files operations feel slow and are needing investigation.

https://drive.google.com/open?id=0B__9XQfR4aFHeE9yaGw0ZGxUejQ

There are multiple aspect of the perceived feeling which can be discuss, but as a general statement, see this animated gif, showing what the experience .

The feeling is accented by the "steps" or the visual feedback which seems halting/chopped instead of being smooth. When you open a file, user can really see those steps:
- expand folder
- loading displayed on folder name
- folder expanded
- click on file
- **it opens an empty editor**
- **content is added in the editor without syntax coloration**
- **syntax coloration is applied**

Sometime the IDE is also showing the message "Loading file content..." while the file is only having less then 100 of lines.

This problem is new, opening files have always been fast and responsive, we needs to chase what are the issues.

**Note:** The same issue is visible on codenvy.io

**Reproduction Steps:**
See animated gif.
https://drive.google.com/open?id=0B__9XQfR4aFHeE9yaGw0ZGxUejQ

Happy to try and record any other scenario that could be useful to identify the problem.

**Che version:**    5.0.0 / 5.1.0 / nightly (5.2.0 at the time of the creation of this issue)
**OS and version:**    MAC OS X 10.12.2 
**Docker version:** 1.12.3

**Comment by JamesDrummond** [comment]
Team/ide has 3 other issues involving performance. Once work on those issues are completed this issue can be re-analyzed. Labeling this as blocked.

1. Che not responding after file operations (creation, deletion, renaming) eclipse/che#3847
1. Closing many files shows an ugly blocking loaders eclipse/che#3890
1. Performance - Copying Multiple Files eclipse/che#3891

**Comment by hkolvenbach** [comment]
I can confirm that this is actually very annoying as a user. When first opening a workspace it can take up to 10 seconds to load a simple Makefile (5-10 lines of code). If the workspace has been running for some time, it is faster though (1-2 seconds).
EDIT: it does not seem to be related to the length of the file at all.
EDIT2: i have attached a real world example (exact speed -> taking around 5 seconds)
![slow opening](https://cloud.githubusercontent.com/assets/26924052/26159100/f9220ee4-3b1d-11e7-84c9-27e076bcc29f.gif)

**Comment by ghost** [comment]
Right now, locally on Ubuntu, file opening takes ~1-2 seconds for me.

**Comment by JamesDrummond** [comment]
Generally only the first file I open takes a bit of time in a workspace but after that performance increases.

**Comment by hkolvenbach** [comment]
can confirm that is generally only the first time a file is opened, however this also the first time a user interacts with the platform and a bad first impression.

**Comment by SkorikSergey** [comment]
@slemeur is this still an issue?

**Comment by slemeur** [comment]
Let's close it and reopen if that happen again. thanks.
