### ISSUE TITLE
Create SystemService

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#3892]
We want to provide some REST API for CLI to make some activity before system shutdown.

 - ```POST /system/stop```
 Will iterate over all running workspaces and suspend them, also it will prevent new workspace starting.
 - ```GET  /system/status```
 Will return json with system ```state:running|preparetoshutdown|readytoshutdown ```

Moved from https://github.com/codenvy/codenvy/issues/1568#issuecomment-275040020

**Comment by benoitf** [comment]
looking at current commits, I see that there is event that is also propagated
Do we have as well a progress tasks , percentage on the graceful stop ?
like  number of wokspaces being stopped

I also notice that specification was 
```
GET /system/status
Will return json with system state:running|preparetoshutdown|readytoshutdown
```
but I see it's `/system/state`in the current code

**Comment by voievodin** [comment]
> Do we have as well a progress tasks , percentage on the graceful stop ?
like number of wokspaces being stopped

No, but you can react on workspace events + log messages are printed pretty often.

> GET /system/status

_status_ is to specific, in codenvy we have a method for getting system ram limit, i think it might be included to the response of _/system/state_ in the future, see [this](https://github.com/codenvy/codenvy/blob/master/wsmaster/codenvy-hosted-system-ram/src/main/java/com/codenvy/service/systemram/SystemRamService.java).
I think we can also include such information as count of currently running workspaces into the state, which may allow you to print some percentage on shutdown

**Comment by benoitf** [comment]
@evoevodin but we need to subscribe to each workspace id channels no ?

**Comment by voievodin** [comment]
hmm i see, you can still analyze logs, or maybe we can add running workspace ids to the state of the system.
What do you propose? btw i've added you as PR reviewer so feel free to suggest things there

**Comment by benoitf** [comment]
ok I was suggesting a pretty dumb simple countdown.
```
Stop in progress...
 stopping workspaces : 100 workspaces to close
 stopping workspaces : 97 workspaces to close
 stopping workspaces : 10 workspaces to close
stopped
```
I will add further comments on the PR

**Comment by TylerJewell** [comment]
First, absolutely YES that this information is ONLY for admins in Codenvy.  

I would recommend that we perhaps move forward with the existing implementation, as it will work, just without any useful feedback.  And then we do second PR with extension of API that includes helpful feedback for CLI clients.  This way we can ship this blocker for 5.2 and if the feedback slips to 5.3, we would be safe.

**Comment by benoitf** [comment]
@skabashnyuk IMHO it was only for admins in codenvy. 
BTW I'm ok as well if we merge as soon as possible the basics so I can implement/test it in CLI. Improvements can come after.
