### ISSUE TITLE
Replace CHE_EXTRA_VOLUME_MOUNT with CHE_WORKSPACE_VOLUME in cli.sh

### ISSUE THREAD

**Issue by ajaygm** [eclipse-che/che#3903]
Per https://github.com/eclipse/che/issues/3888#issuecomment-274988735 `CHE_EXTRA_VOLUME_MOUNT` has been replaced by `CHE_WORKSPACE_VOLUME`.

Need to update https://github.com/eclipse/che/blob/master/cli.sh accordingly.

@TylerJewell can you confirm if this is really a bug or I might have misunderstood your comment.

**Comment by TylerJewell** [comment]
Actually - that file should not be present.  We no longer support the `cli.sh` in the root of the repository and only support the Dockerized CLI. I need to investigate why this file is still present as we just removed a bunch of files.  I think this is a hangover of something.
