### ISSUE TITLE
Starting workspace hangs with symbolic file links in project

### ISSUE THREAD

**Issue by ceosion** [eclipse-che/che#3906]
When I start a workspace with a large amount of files (>3GB) Eclipse Che makes it to the point where it echo's "[INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war" for the dev-machine, but then hangs and eventually the timeout error occurs.

**Reproduction Steps:**
1. Create a new workspace
2. Load in a ton of files (>3GB) from svn, git, etc.
3. Shutdown the workspace
4. Restart the workspace

**Che version:** 5.0.0-latest

**OS and version:** Windows 10

**Docker version:** Client 1.12.5, Server 1.13.0

**Comment by ceosion** [comment]
My current work around is to move the workspace project files temporarily, start the workspace, then move them back.
Example:
```
cd ~/.che/workspaces
mv mywksp mywksp-tmp
# Start workspace in Eclipse Che
mv mywksp-tmp mywksp
```

**Comment by TylerJewell** [comment]
@ceosion - Alex, out of curiosity, have you tried this same sequence with Codenvy and does the issue happen there?  We have an rsync agent within Codenvy's on-prem system that moves project files in / out of a workspace differently than the way they move in and out with Che.  So would like to isolate the issue.

The syntax for starting Codenvy is the same as Che and there is a 3 free user license.  Just replace "eclipse/che" image name with "codenvy/cli".

**Comment by ghost** [comment]
@TylerJewell what you suggest will likely aggravate the situation since rsync will have to backup and restore 3GB and there's timeout for that as well. With Che, where a local mount happens it should be easier.

I failed to reproduce it with 11GB project on Linux. @ceosion is your project public? I will try to reproduce it on Win 10 and let you know.

**Comment by ghost** [comment]
@ceosion I have just tried importing Linux kernel which is quite big. Workspace started as usual. Can you perhaps share the project?

**Comment by ceosion** [comment]
@TylerJewell no, I haven't tried yet. I also can't place the profile files on a hosted server for security reasons.

@eivantsov thanks for your efforts thus far, unfortunately I cannot share the project. But after your findings, it definitely seems like it could be something specific with the project. I'm not exactly surprised to be honest, because I've run into several issues working with Windows/Eclipse Che and this project. For example, one consistent issue is that the project uses symlinks in it's repository and always fails when I try to check it out. I have to perform a sequence of 'svn update --set-depth' commands to selectively avoid the symlinks. (Thankfully the symlinks are in a part of the project that I don't need.) But then I also get intermittent SVN errors which I haven't been able to trace very far. To get around those, I simply just issue an 'svn cleanup' and then try again. I believe these issues (at least the symlink issue) is related to the fact that my host machine is Windows 10, and the application space is the Linux container controlled by Docker/Eclipse Che.

Any other ideas after hearing this? Any log files that I can look at/share that might help?

**Comment by TylerJewell** [comment]
Ok - this is interesting, and could warrant a different type of investigation into the future.  So the attributes which may let us reproduce this are:
1. Large number of files
2. Subversion
3. Symlinks in the repository requiring 'svn update --set-depth'
4. Windows with Che

@eivantsov would be in a position to tell you about other log files that could be interesting.  When you start a workspace, each workspace has a set of containers, and those containers each have their own log file that would have the error messages for failed clonings that we should take a look at.  For 5.2.0, we are going to introduce a nice utility that grabs all of these for us - but this is not merged yet.

#3862

**Comment by JamesDrummond** [comment]
@ceosion Not sure if there is a huge performance factor versus cloning natively plus the workspace start times agent startups. This should be investigated. 

Have you tried to increase you workspace agent timeout which I think embedded default is `CHE_MACHINE_WS_AGENT_MAX_START_TIME_MS=300000` (5 minutes) which maybe just exceeded. Try setting `CHE_MACHINE_WS_AGENT_MAX_START_TIME_MS=600000` in che.env file and see if it helps.

@eivantsov Do we log how long a workspace takes to start somewhere? If we do I could try to run a performance comparison.

**Comment by ceosion** [comment]
@JamesDrummond yes, I've tried increasing it exactly as you suggested, and still nothing. It's also pretty inconvenient to have to wait >5 minutes for a workspace to startup, so even if that worked, it wouldn't be good.

I tried poking around inside the container for logs or extra information, but couldn't find much in my ~20 minutes of investigation. I feel it has to be something involving Tomcat and the deployment of the /home/user/che/ws-agent/webapps/ROOT.war but I can't find a place where Tomcat is giving more detailed output aside from what is already being pumped into Eclipse Che's dev-machine console on the Web UI. (I did find that this is a tail of the catalina.log.0 file, but it's just the same output delivered to the web ui's console.

**Comment by JamesDrummond** [comment]
@ceosion Can your provide output of `docker info`.

**Comment by ceosion** [comment]
@JamesDrummond sure thing!
```
$ docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 46
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.43-boot2docker
Operating System: Boot2Docker 1.13.0 (TCL 7.2); HEAD : 5b8d9cb - Wed Jan 18 18:50:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.696 GiB
Name: default
ID: R3V5:4HZS:SLHJ:2S5F:BK46:O5H2:OKEH:FKWD:FMLD:IYMX:P3ZW:7BLP
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 47
 Goroutines: 56
 System Time: 2017-01-27T15:51:33.040519391Z
 EventsListeners: 1
Username: ceosion
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Comment by JamesDrummond** [comment]
@ceosion Maybe it does have to do with windows filesystem. Let's volume mount the data folder to a folder inside the boot2docker virtual machine. Try the following:

```
docker run --rm -v /home:/home alpine mkdir /home/che-data
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /home/che-data:/data eclipse/che start
```

You may need to increase your boot2docker storage size. Mine below is at 19.53GB for example.

![image](https://cloud.githubusercontent.com/assets/20580888/22378950/f798b9bc-e47c-11e6-9a59-a9c3a3891d01.png)

**Comment by ghost** [comment]
@ceosion @TylerJewell I am pretty sure it's symlinks and Windows. I have imported Linux kernel into Che on Win 10. Workspace agent starts in a jiffy.

**Comment by TylerJewell** [comment]
Eugene - if this is a simlinks issue, would there be an engineering workaround that we could think about with dev or is the solution to use projects without simlinks?

If it is something we can engineer around then I will uplevel this to a P2 severity bug.

@ceosion - my comment about codenvy earlier is whether you installed it or not.  Codenvy is installed almost indentically like Che.  You can even run it on your laptop.

I don't think it solves the issue but probably verifies it and perhaps simplifies diagnostic.

The codenvy image is codenvy/cli

**Comment by ghost** [comment]
@TylerJewell I don't know how to reproduce. @vparfonov has imported a 10GB project on his linux machine (basically copied all his local projects into a ws folder). I imported Linux Kernel on Win 10. None of us found any issues. I do not think we can effectively solve this issue without an actual or similar project and debugging.

**Comment by TylerJewell** [comment]
Well what do you think @ceosion?  Would you offer us some pointers on how we might set up a subversion system with similar properties to your own?

**Comment by ceosion** [comment]
Hey everyone, sorry for the delay in reply! I'm not sure that it's symbolic links present in the project. My point about mentioning that is there are known issues when dealing with symlinks in SVN and checking out on virtualized filesystems. SO, I excluded those symlinks. They are NOT present in my project files when I boot up the workspace.

I also don't think it has much to do with the size of the project files (not as a collection, anyway).

I'm sorry, I wish I could share this repo with you guys, but it's in a controlled environment. I'm not sure what else I can do to try and help. I was thinking about trying to piecemeal add the files to the workspace and seeing when the problem occurs. Would do it "tree search" style, to optimize this... but still, it would take quite a bit of time that I don't have right now.

@JamesDrummond stay tuned, I'm about to try what you suggested, basically keeping everything inside boot2docker and not have it on the Windows host.

@TylerJewell I can experiment a little with the Codenvy image after that!

**Comment by TylerJewell** [comment]
Or we could invite your company to do an NDA with us so that we can protect your ip while still doing proper investigation.

**Comment by ceosion** [comment]
@TylerJewell unfortunately it'd be more complicated, my company (Draper) often works with military and government agencies, and the project in question is one such project. The code is owned by the government, so we'd need to get the sponsor to agree to it, which I feel like is unlikely.

**Comment by TylerJewell** [comment]
Ok - let us know how it goes.  Looks like you are about to learn how to know the internals to become a Che committee :)

**Comment by ghost** [comment]
@ceosion I am going to run some tests on Win 10 and 8 with projects containing symlinks. Will update this thread soon.

**Comment by ghost** [comment]
@ceosion @TylerJewell I have just tried importing a simple project with symlinks in it. Win 10. No issues.

**Comment by TylerJewell** [comment]
Well that is interesting.  Was fairly certain that was going to be the root cause of the issue.

**Comment by ceosion** [comment]
I didn't think it was, because I have to **exclude** the symlinks in my environment. Attempting to check them out causes SVN errors. @eivantsov you were able to check out a project with symlinks on a Windows 10 host, inside a workspace, successfully? Was the base imagine starting with ubuntu:14.4?

**Comment by ghost** [comment]
@ceosion fedora based one.

**Comment by ceosion** [comment]
New data point: I upgraded last night to Eclipse Che 5.2.2 and tried starting the workspace with the problematic files again. This time, it got past the loading of the ROOT.war... but then hung a few lines later...

```
2017-02-08 19:25:28,624[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
2017-02-08 19:25:37,919[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 59]      - Workspace ID: workspacek8boduzw6k4ohr5x
2017-02-08 19:25:37,919[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 60]      - API Endpoint: http://che-host:8080/wsmaster/api
2017-02-08 19:25:37,920[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 61]      - User Token  : true
Wed Feb 08 19:25:39 UTC 2017 - [localhost-startStop-1] Product-specified preferences called before plugin is started
2017-02-08 19:25:39,378[s polled Thread]  [INFO ] [o.e.c.p.m.server.rmi.RmiClient 130]  - Port/Name:33001/MavenRemoteServerImpl70e4df7a
```

**Comment by JamesDrummond** [comment]
@ceosion Whenever I get strange errors after upgrading/changing versions I try running incognito due to cache issues sometimes. If it works for you then it is most likely a cache issue which you should clear. I don't know what the error means which someone else can maybe help with if it's not a cache issue.

**Comment by ceosion** [comment]
Hi @JamesDrummond, I don't think this is a cache issue (though I have seen that before, too). I believe this to be an issue with the files on the filesystem.

But just for kicks, since it's easy enough to try, I used incognito mode in Chrome and confirm that the problem persists. :(

**Comment by JamesDrummond** [comment]
Worth a shot. Also try what I mentioned above too in using the boot2docker VM file system to see if it has something to do with window's filesystem again with 5.2.2. The `rm` is just in case you already did this and there is old files there.

```
docker run --rm -v /home:/home alpine mkdir -p /home/che-data
docker run --rm -v /home:/home alpine rm -r /home/che-data/*
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /home/che-data:/data eclipse/che start
```

**Comment by ghost** [comment]
@ceosion do you have a linux box to give it a try? If not, I can arrange access to one of my Ubuntu tets nodes with Che already running there. Do you think it's worth a try? You import your project, observe behavior, share your findings with us, and delete the project.

**Comment by ghost** [comment]
I am going to close this issue since it looks like Docker on Windows issue.
