### ISSUE TITLE
Study possibility to restore workspace runtimes from docker information after improper restart

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#3910]
Sometimes it can happen that ws-master terminated or 
improperly restarted. It can be cause of many circumstances but
one of the most common is JVM failure. If in this time some workspace was running
we will lose it. The goal of this task is to study possibility to recover
all workspace runtime information from DB or from docker or swarm.
Result of this issue: list of things to do or almost working prototype.

**Comment by voievodin** [comment]
### 1. Containers to machines mapping

The example of container json returned by docker API for workspace machine

```bash
curl --unix-socket /var/run/docker.sock http:/containers/json | jq .
```

```json
[
  {
    "Id": "effc1578c518784555f7981fd560fb6979d8ee7d0ad54441648522dcc6299324",
    "Names": [
      "/workspaceos6k0l3pz89ufi2z_machinep91hshmqt17bi7lp_che_dev-machine"
    ],
    "Image": "eclipse-che/workspaceos6k0l3pz89ufi2z_machinep91hshmqt17bi7lp_che_dev-machine",
    "ImageID": "sha256:965f2a0ba70cd287a3fd1d9278909c35198f9565c7fca56d314c552517f97212",
    "Command": "/home/user/entrypoint.sh /bin/sh -c 'tail -f /dev/null'",
    "Created": 1486716564,
    "Ports": [
      {
        "IP": "0.0.0.0",
        "PrivatePort": 4401,
        "PublicPort": 32773,
        "Type": "tcp"
      },
      {
        "IP": "0.0.0.0",
        "PrivatePort": 22,
        "PublicPort": 32774,
        "Type": "tcp"
      },
      {
        "IP": "0.0.0.0",
        "PrivatePort": 9876,
        "PublicPort": 32768,
        "Type": "tcp"
      },
      {
        "IP": "0.0.0.0",
        "PrivatePort": 8080,
        "PublicPort": 32769,
        "Type": "tcp"
      },
      {
        "IP": "0.0.0.0",
        "PrivatePort": 8000,
        "PublicPort": 32770,
        "Type": "tcp"
      },
      {
        "IP": "0.0.0.0",
        "PrivatePort": 4411,
        "PublicPort": 32771,
        "Type": "tcp"
      },
      {
        "IP": "0.0.0.0",
        "PrivatePort": 4403,
        "PublicPort": 32772,
        "Type": "tcp"
      }
    ],
    "Labels": {
      "che:server:22/tcp:ref": "ssh",
      "che:server:4401/tcp:path": "/api",
      "che:server:4401/tcp:protocol": "http",
      "che:server:4401/tcp:ref": "wsagent",
      "che:server:4411/tcp:protocol": "http",
      "che:server:4411/tcp:ref": "terminal",
      "che:server:8000:protocol": "http",
      "che:server:8000:ref": "tomcat8-debug",
      "che:server:8080:protocol": "http",
      "che:server:8080:ref": "tomcat8",
      "che:server:9876:protocol": "http",
      "che:server:9876:ref": "codeserver"
    },
    "State": "running",
    "Status": "Up 19 minutes",
    "HostConfig": {
      "NetworkMode": "workspaceos6k0l3pz89ufi2z_ey679p821kt851jn"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "c536fb65b01036b09ec64a9c0e708d7f1740794373ca1c5e1368c26f1ef15052",
          "EndpointID": "40ed7d9fa78da679cfd6fc64bab23f9d521e9721c771777a0e92791b5b69e798",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.3",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
        },
        "workspaceos6k0l3pz89ufi2z_ey679p821kt851jn": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "4c96d960c49608e4587620cf5e7a04d5824bf68181e0fd4829578593a8b7f68f",
          "EndpointID": "d65d1dda87ccd5a1af20926cfe700f43a199f4ae2d503efdbe005fb337fed02f",
          "Gateway": "172.24.0.1",
          "IPAddress": "172.24.0.2",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
        }
      }
    },
    "Mounts": [
      {
        "Source": "/home/jumper/.che/data/instance/data/lib/linux_amd64/terminal",
        "Destination": "/mnt/che/terminal",
        "Mode": "ro,Z",
        "RW": false,
        "Propagation": "rprivate"
      },
      {
        "Source": "/home/jumper/.che/data/instance/data/workspaces/wksp-lz1b",
        "Destination": "/projects",
        "Mode": "Z",
        "RW": true,
        "Propagation": "rprivate"
      },
      {
        "Source": "/home/jumper/.che/data/instance/data/lib/ws-agent.tar.gz",
        "Destination": "/mnt/che/ws-agent.tar.gz",
        "Mode": "ro,Z",
        "RW": false,
        "Propagation": "rprivate"
      }
    ]
  }
]

```

To get machine into the previous state so workspace API returns machine json as if it wasn't stopped, 
the following fields have to be recovered from the container:

```
Machine:
  id
  workspaceId
  envName
  owner
  status
  config:
    name
```

Some of the parameters can be catched from existing data provided by docker, like
_id_,  _workspaceId_ and _name_ can be extract from the _image_ or _container names_ array:
```
eclipse-che/workspaceos6k0l3pz89ufi2z_machinep91hshmqt17bi7lp_che_dev-machine
```
but i don't think this is a good way, as naming generation strategy can be changed in future
so parsing of these fields would also reqire changes.

The most straightforward approach here is to save machine required data as container labels, 
so labels may look like this:
```
"che:env_name": "wksp-lz1b",
"che:id": "machinep91hshmqt17bi7lp",
"che:name": "dev-machine",
"che:owner": "che",
"che:workspace_id": "workspaceos6k0l3pz89ufi2z",
"che:server:22/tcp:ref": "ssh",
"che:server:4401/tcp:path": "/api",
"che:server:4401/tcp:protocol": "http",
"che:server:4401/tcp:ref": "wsagent",
"che:server:4411/tcp:protocol": "http",
"che:server:4411/tcp:ref": "terminal",
"che:server:8000:protocol": "http",
"che:server:8000:ref": "tomcat8-debug",
"che:server:8080:protocol": "http",
"che:server:8080:ref": "tomcat8",
"che:server:9876:protocol": "http",
"che:server:9876:ref": "codeserver"
```

Machine runtime servers are already saved to labels and don't require convertion.

_machine.config.limits.memory_ can be taken from container.hostConfig.memory attribute
which is present only in _docker inspect output_ so basically memory limit should be either 
saved to container labels or direct inspect should be used to get memory value.

Machine status can be taken from the _container.state_ value.

### 2. Network recovering

Network is docker specific feature that is missing from the model, but still used
by `CheEnvironmentEngine`, so let's say if `MachineProvider` exposes method for getting currently 
running machines e.g. `List<Instance> lookup()` it won't provide any explicit information 
about docker network, but `CheEnvironmentEngine` requires it to destroy network after environment
is destroyed. 

Network is destroyed in 2 cases
  - if environment is stopped(CheEnvironmentEngine)
  - if DockerAbandonedResourcesCleaner catches unused network

Network name is declared by _container.hostConfig.networkMode_ property.

The solutions i see:
  - or move network management from `CheEnvironmentEngine`.
  - or make network to not be docker specific feature.
   - or add methods to `MachineProvider` for getting information about network like `String getNetworkName(Instance instance)`.
  - or add network data to `Instance` implementation and workaround fetching of it in `CheEnvironmentEngine`.

### 3. Consistency 

Restored workspaces have to be in consistent state.

The requirements for restored environments i see:
- if any machine is missing from environment(defined 3 but running 2), 
the whole environment is stopped


### 4. Authentication 

Machine tokens are saved in memory as user + machine, which means  
that when server restarted those tokens are not recovered automatically.
The solutions i see:
- or save tokens to the DB, recover on startup.
- or make stateless communication between agents & master(don't cache token always request access on master).
- or agents expose API for reseting tokens, so when master starts it uses those APIs.


### 5. The components interfering recovery
There are several components that cleanup resources when servers is stopped/started or periodically:
- `DockerAbandonedResourcesCleaner` - cleans up docker networks and containers that are missing from runtime, the bootstrap of this class should be reworked as it will cleanup all the containers on boot.
- `TemporaryWorkspaceRemover` - cleans up temporary workspace when server is stopped/started, it should be reworked to not remove the workspaces that are recovered successfully.

**Comment by garagatyi** [comment]
Explanation looks good and complete. Here is some extra opinion on this strategy:
> Machine status can be taken from the container.state value.

We don't connect container state and machine state directly. So you probably mean that if container is running it means machine is running. In any other case machine doesn't exist anymore (we don't have stopped state for machine). 

> Network name is declared by container.hostConfig.networkMode property.

In case of che it just equal to this value. In codenvy it can differ. But it is taken from property and should be probably recovered by relying on that property too. 

About network recovering I'm +1 either 3 of 4 variant of solution.
