### ISSUE TITLE
No che-server logs in logs folder

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3913]
New Che CLI creates logs folder in instance folder but doesn't write there logs of che-server.
Also there is folder <instance-folder>/data/logs where logs of machines are stored.
For example Codenvy CLI stores logs of both in <instance-folder>/logs/codenvy.

**Che version:**    5.2.0-SNAPSHOT

**OS and version:**    Ubuntu 16.04

**Docker version:** 1.12.5

**Comment by riuvshin** [comment]
it seems this is simple issue, seems we just need mounts for logs in compose file

**Comment by benoitf** [comment]
@garagatyi I've made a pull request
