### ISSUE TITLE
Error Launching SSH Agent

### ISSUE THREAD

**Issue by hypertoast** [eclipse-che/che#3914]
My server is accessible via a PublicIP. I can connect to the dashboard and go to create a new workspace. It fails at the "Launching SSH Agent". I have tried running it on multiple OS (Ubuntu, Debian, CentOS). All have the same problem... Any help is appreciated.

**Reproduction Steps:**
Create a workspace (any stack)
Workspace loads until the following line appears: [STDOUT] ssh-keygen: generating new host keys: RSA1
The error popup will appear after a few minutes
"Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment 'default' failed. Error: Fail launching agent SSH. Workspace ID:workspacesrla9fgjiux3nutt"

**Che version:**    
Your CLI version is '5.1.2'.
Your installed version is '5.1.2'.

**OS and version:**    
OS: CentOS Linux release 7.3.1611 (Core)

**Docker version:**    
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Eclipse Browser Window Output:**
`[STDOUT] 2017-01-26 14:39:56,860[main] [INFO] [o.a.c.http11.Http11NioProtocol 488] - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-01-26 14:39:56,865[main] [INFO] [o.a.catalina.startup.Catalina 642] - Server startup in 7747 ms
[STDOUT] 2017-01-26 14:39:57,005[nio-4401-exec-2] [WARN ] [o.e.c.impl.ContainerResponse 93] - Client has aborted connection. Response writing omitted.
[STDOUT] 2017-01-26 14:39:57,005[nio-4401-exec-1] [WARN ] [o.e.c.impl.ContainerResponse 93] - Client has aborted connection. Response writing omitted.
[dev-machine] [STDOUT] ssh-keygen: generating new host keys: RSA1`

**Che cli.log output:**  
`2017-01-26 14:39:57,905[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 664]   - Launching 'org.eclipse.che.ssh' agent at workspace workspacesrla9fgjiux3nutt
2017-01-26 14:41:58,265[aceSharedPool-0]  [ERROR] [.a.a.s.l.AbstractAgentLauncher 96]   - Fail launching agent SSH. Workspace ID:workspacesrla9fgjiux3nutt
2017-01-26 14:42:01,229[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 701]    - Fail launching agent SSH. Workspace ID:workspacesrla9fgjiux3nutt
org.eclipse.che.api.core.ServerException: Fail launching agent SSH. Workspace ID:workspacesrla9fgjiux3nutt
        at org.eclipse.che.api.agent.server.launcher.AbstractAgentLauncher.launch(AbstractAgentLauncher.java:97) ~[che-core-api-agent-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:667) ~[che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1029) ~[che-core-api-workspace-5.1.2.jar:5.1.2]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:806) ~[che-core-api-workspace-5.1.2.jar:5.1.2]`

**Comment by ghost** [comment]
Can you get machine logs? They are in your data folder - `/instance/data/logs/machine/machineID`

Have you tried disabling firewall?

**Comment by hypertoast** [comment]
@eivantsov Thank you for your reply.

I dont have the standard centos firewall installed... (I believe)
`-bash: firewall-cmd: command not found`

my ipTables rules (configured by Docker I believe):
`[user@myhost machinecwpwlyvd9mv51ll9]# iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-ISOLATION  all  --  anywhere             anywhere
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.4           tcp dpt:webcache

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere`

**Numeric file log:**
`[user@myhost machinecwpwlyvd9mv51ll9]# cat 127
[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2017-01-26 18:32:12,431[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.38
[STDOUT] 2017-01-26 18:32:12,433[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 6 2016 20:51:55 UTC
[STDOUT] 2017-01-26 18:32:12,433[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.38.0
[STDOUT] 2017-01-26 18:32:12,433[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2017-01-26 18:32:12,434[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.14.32-xxxx-grs-ipv6-64
[STDOUT] 2017-01-26 18:32:12,434[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2017-01-26 18:32:12,434[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jre1.8.0_65
[STDOUT] 2017-01-26 18:32:12,435[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_65-b17
[STDOUT] 2017-01-26 18:32:12,435[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2017-01-26 18:32:12,435[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2017-01-26 18:32:12,435[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2017-01-26 18:32:12,436[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2017-01-26 18:32:12,436[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2017-01-26 18:32:12,436[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2017-01-26 18:32:12,437[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
[STDOUT] 2017-01-26 18:32:12,437[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2017-01-26 18:32:12,437[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2017-01-26 18:32:12,437[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
[STDOUT] 2017-01-26 18:32:12,437[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
[STDOUT] 2017-01-26 18:32:12,438[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2017-01-26 18:32:12,438[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2017-01-26 18:32:12,438[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2017-01-26 18:32:12,438[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2017-01-26 18:32:12,438[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2017-01-26 18:32:12,438[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2017-01-26 18:32:12,439[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2017-01-26 18:32:12,439[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2017-01-26 18:32:12,439[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2017-01-26 18:32:12,551[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 443]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-01-26 18:32:12,562[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2017-01-26 18:32:12,564[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 357 ms
[STDOUT] 2017-01-26 18:32:12,605[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2017-01-26 18:32:12,652[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] 2017-01-26 18:32:19,242[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 59]      - Workspace ID: workspacesrla9fgjiux3nutt
[STDOUT] 2017-01-26 18:32:19,243[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 60]      - API Endpoint: http://che-host:8080/wsmaster/api
[STDOUT] 2017-01-26 18:32:19,243[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 61]      - User Token  : true
[STDOUT] 2017-01-26 18:32:19,642[ost-startStop-1]  [WARN ] [e.c.p.m.s.c.c.ClasspathManager 87]   - Maven server not started looks like you don't have Maven in your path
[STDOUT] Thu Jan 26 18:32:19 UTC 2017 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2017-01-26 18:32:20,065[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 7,413 ms
[STDOUT] 2017-01-26 18:32:20,068[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-01-26 18:32:20,073[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 7508 ms
[STDOUT] 2017-01-26 18:32:20,288[nio-4401-exec-2]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.
[STDOUT] 2017-01-26 18:32:20,288[nio-4401-exec-1]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.

[STDOUT] 2017-01-26 18:32:12,605[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
[STDOUT] 2017-01-26 18:32:12,605[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38`

**machineID.log**
[user@myhost machinecwpwlyvd9mv51ll9]# cat machineId.logs
[DOCKER] latest: Pulling from eclipse/node
[DOCKER] Digest: sha256:c051f292bc5daa088eb116f00f55dbb0ac379d2c4606b1d71e570442f662a15b
[DOCKER] Status: Image is up to date for eclipse/node:latest
[STDOUT] Exec-agent configuration
[STDOUT]   Server
[STDOUT]     - Address: :4411
[STDOUT]     - Static content: /home/user/che/terminal/
[STDOUT]     - Base path: ''
[STDOUT]   Terminal
[STDOUT]     - Slave command: '/bin/bash'
[STDOUT]     - Activity tracking enabled: false
[STDOUT]   Process executor
[STDOUT]     - Logs dir: /home/user/che/exec-agent/logs
[STDOUT]
[STDOUT] ? Registered HttpRoutes:
[STDOUT]
[STDOUT] Process Routes:
[STDOUT] ? Start Process ........................... POST   /process
[STDOUT] ? Get Process ............................. GET    /process/:pid
[STDOUT] ? Kill Process ............................ DELETE /process/:pid
[STDOUT] ? Get Process Logs ........................ GET    /process/:pid/logs
[STDOUT] ? Get Processes ........................... GET    /process
[STDOUT]
[STDOUT] Channel Routes:
[STDOUT] ? Connect to Exec-Agent(webscoket) ........ GET    /connect
[STDOUT]
[STDOUT] Terminal routes:
[STDOUT] ? Connect to pty(webscoket) ............... GET    /pty
[STDOUT]
[STDOUT]
[STDOUT] ? Registered RpcRoutes:
[STDOUT]
[STDOUT] Process Routes:
[STDOUT] ? process.start
[STDOUT] ? process.kill
[STDOUT] ? process.subscribe
[STDOUT] ? process.unsubscribe
[STDOUT] ? process.updateSubscriber
[STDOUT] ? process.getLogs
[STDOUT] ? process.getProcess
[STDOUT] ? process.getProcesses
[STDOUT] ssh-keygen: generating new host keys: RSA1

**Comment by ghost** [comment]
@hypertoast let's do a quick test:

`docker run -d -p 32876:80 nginx`

You should be able to reach nginx welcome page at `$PUBLIC_IP:32876`

Keep this container running and start another one:

`docker run -ti appropriate/curl sh`
`curl -v $PUBLIC_IP:32876`

Can you reach nginx from this container? I believe that this is basically what happens with your workspace. SSH agent tries to verify that SSH port is reachable in a workspace container and it's doing it from che-server container. So, let's simulate this situation with these two small images.

**Comment by hypertoast** [comment]
@eivantsov 
Both the scenarios work perfectly fine. I am getting the nginx welcome page via the browser and curl. Thank you.

**Comment by ghost** [comment]
@hypertoast have you run curl from within the container?

**Comment by hypertoast** [comment]
@eivantsov 
Yes. Here is the output:
`
[user@myhost ~]# docker run -ti appropriate/curl sh
Unable to find image 'appropriate/curl:latest' locally
latest: Pulling from appropriate/curl
0a8490d0dfd3: Pull complete
3bcd34e3b219: Pull complete
290e0f1d9167: Pull complete
Digest: sha256:a6a78bae9692193281cccb394e7715b1d49e27de11ec185ba7c0a0d6d81c00ab
Status: Downloaded newer image for appropriate/curl:latest
/ # curl -v http://192.xx.xx.xx:32876/
*   Trying 192.xx.xx.xx...
* TCP_NODELAY set
* Connected to 192.xx.xx.xx (192.xx.xx.xx) port 32876 (#0)
> GET / HTTP/1.1
> Host: 192.xx.xx.xx:32876
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.11.9
< Date: Mon, 30 Jan 2017 13:19:13 GMT
< Content-Type: text/html
< Content-Length: 612

`

**Comment by ghost** [comment]
@hypertoast is it a local or a cloud VM? This is 100% network issue, however, I hoped that the tests I wanted you to run will fail.

Can you share your che.env file?

**Comment by hypertoast** [comment]
@eivantsov 
It is a dedicated server running Centos 7. 
Please find attached. I have redacted my public IP from the file.
[che.env.txt](https://github.com/eclipse/che/files/740136/che.env.txt)

Thank you.

**Comment by ghost** [comment]
@hypertoast another thing to try is to use `172.17.0.1` in that cURL test since this is the internal URL that the server should be using to verify an agent is up and running.

**Comment by hypertoast** [comment]
@eivantsov I tried with 172 address. it worked.

[user@myhost che]# docker run -ti appropriate/curl sh
/ # curl -v http://172.17.0.1:32876
* Rebuilt URL to: http://172.17.0.1:32876/
*   Trying 172.17.0.1...
* TCP_NODELAY set
* Connected to 172.17.0.1 (172.17.0.1) port 32876 (#0)
> GET / HTTP/1.1
> Host: 172.17.0.1:32876
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.11.9
< Date: Mon, 30 Jan 2017 21:08:57 GMT
< Content-Type: text/html

Thank you. I have sent my public IP to your email.

**Comment by ghost** [comment]
@hypertoast we have identified the problem and it is about how we check if or not sshd is launched.

I cannot reproduce it on a local machine and Amazon as well.

What is your VM provider? How do you start your VMs? Do you think it will be possible for me to get exactly the same machine?

**Comment by hypertoast** [comment]
Kimsufi.com is my provider. Its a dedicated server from their low cost
offerings if that helps. You can work on my server till then. No rush!

Thank you.

**Comment by hypertoast** [comment]
@eivantsov. Just checking in if any resolution has been found.. Thank you.

**Comment by ghost** [comment]
@TylerJewell do you think this needs to be taken to the next sprint? This issue is related to how an agent verifies it has been successfully started. On some kernels we fail to see processes that we expect to see, and thus, even though sshd is running, Che master thinks it is not.

**Comment by TylerJewell** [comment]
@eivantsov - I agree the issue is severe, and have given the background have set the serverity to P1. I would let the team leaders decide if this is in the next sprint or not given the wide array of customer issues that they are dealing with.  But we should not let many P1 issues sit for very long in the backlog.

**Comment by hypertoast** [comment]
@TylerJewell @eivantsov thank you!!

**Comment by TylerJewell** [comment]
@vkuznyetsov - fyi

**Comment by ghost** [comment]
@TylerJewell should this be taken into a sprint?

**Comment by TylerJewell** [comment]
Yes - it should be taken into a sprint.  I pinged Viktor for him to appropriately prioritize it into his backlog given that it is a P1.

**Comment by mmorhun** [comment]
Done

**Comment by mmorhun** [comment]
@hypertoast thank you for reporting and providing specific environment.
The fix will be included in CHE 5.8.0 or you can try nightly build tomorrow.

**Comment by hypertoast** [comment]
Wow. Thank you guys for your help. I'll wait for the new release!
