### ISSUE TITLE
Che workspace is not stopped if env.var to stop inactive workspace is set

### ISSUE THREAD

**Issue by mlabuda** [eclipse-che/che#3915]
Using CHE_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS property to set timeout when should be a workspace suspended does not work. After using this file in che.env and running instance with this env. var, workspace is running all the time.

**Reproduction Steps:**
EXEC: Init che files in a local data directory (e.g. through Che CLI).
EXEC: Modify che.env to set property CHE_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS  to a timeout 300 seconds.
EXEC: Start che with this configuration
EXEC: Create a new workspace and let it be inactive.
RESULT: After a specified amount of seconds by the property, the workspace is still running. I had set workspace to 600 seconds but it was running even after 20 minutes.

**Che version:** nightly che

**OS and version:** I think it affects all OSes

**Docker version:** Does not matter, but 1.12.

**Comment by benoitf** [comment]
@mlabuda this setting was a codenvy only setting
https://github.com/eclipse/che/issues/3873

this property has  been removed from che.env as it is a not a property which is handle in Che.
https://github.com/eclipse/che/pull/3874/files

**Comment by TylerJewell** [comment]
@mlabuda @l0rd - ok, it took me some time, but was able to gather the history on this along with the rationale. It is correct, that this is an attribute that is in Codenvy only attribute. The attribute should not have appeared in the `che.env` file.

This decision was made a couple years ago. Che is intended as a single user identity system, and in that situation, workspaces should not timeout as it would create a user experience that was not originally intended for Che.  Workspace timeouts are a concept that is necessary when thinking of a multi-user, multi-identity system (like Codenvy), where the system is managing a distributed set of different user identities and hardware nodes to power the workspaces.

Interestingly, we are in the final stages of implementing a graceful shutdown service within Che. This will run through all of the open workspaces and stop them gracefully before sending the shutdown signal to the Che server. This is not entirely the same as idle timeout, but it's a mechanism that helps with keeping single Che servers organized with its resources.  This will be a part of 5.2.0 release next week.

**Comment by mlabuda** [comment]
Ok, thanks for info.
