### ISSUE TITLE
Recipe Location URL incorrect

### ISSUE THREAD

**Issue by ajaygm** [eclipse-che/che#3918]
The recipe location URL (e.g. http://192.168.99.100:8080/dashboard/eclipse/debian_jre for "eclipse/debigna_jre") shown in the Stack's or Workspace's Runtime's detail section is incorrect.

It results in HTTP 404.

**Reproduction Steps:**
1. For Workspace
    1. Create a workspace
    1. Open the workspace using configure workspace option
    1. Go to Runtime section
    1. Click on the link in the Recipe Location
1. For Stacks
    1. Go to stacks section of the Dashboard.
    1. Open any existing stack
    1. Go to Runtime section
    1. Click on the link in the Recipe Location

**Che version:**    
```
Version :5.2.0-SNAPSHOT
Revision :c4bd4d0ee1d8fdeb
Build Time :2017-01-24 16:34:56
```

**OS and version:**    Windows 7

**Docker version:** 
```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
```

**Comment by slemeur** [comment]
Cross linking with https://github.com/eclipse/che/issues/3571
