### ISSUE TITLE
Proxy settings exported in the workspace container for a user not root

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#3920]
When http and https proxies are applied, they are applied for a current user in a container. However, apt-get or dnf or yum or any package manager commands should be run with sudo. A root user does not have those envs, as a result any package manager commands that need connection fail.

This affects launching agents in Che and Codenvy.

**Comment by TylerJewell** [comment]
@eivantsov - thanks for reporting - promoting to severity/blocker, as this prevents installation and usage in some situations, which is effectively an outage scenario.

**Comment by bmicklea** [comment]
@skabashnyuk - FYI this is a blocker that's preventing one of our major banking prospects from moving forward. Can someone take a look at it ASAP?
