### ISSUE TITLE
The 'Navigate To File' works incorrectly

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3928]
When I use the 'Navigate To File', then it finds files from hidden folders. This is a bug.

**Reproduction Steps:**
* Open a project in the IDE (e.g. web-java-spring from template).
* Call 'Navigate To File' from menu or by keyboard 'Ctrl+Alt+N'.
* Enter symbol 'p'.

**Expected behavior:**
* should not be found files from hidden folders.

**Observed behavior:**
* in the pop up there are files from hidden folder.

**Che version:** 5.2.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12

**Che cli.log output:**  [cli.log.zip](https://github.com/eclipse/che/files/735146/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachments:
![navi_to_file](https://cloud.githubusercontent.com/assets/5408906/22369365/1679588e-e494-11e6-9071-c62516f50744.png)

**Comment by sunix** [comment]
maybe related to this issue ... It should be possible not to display some folders/files from a global configuration somehow. For instance, I expect a way not to show files in 'target' folder for Maven projects

**Comment by vzhukovs** [comment]
@sunix as far as I know, target directories are excluded from indexing in lucene, so there is no search result for those kind of files, need to check this

**Comment by sunix** [comment]
@vzhukovskii seems not:
![eclipse che che-master - google chrome_002](https://cloud.githubusercontent.com/assets/650571/24857456/b529e24a-1de8-11e7-81f6-791593ef3e87.png)
Edit: seems that the problem is still here: 5.8.0-SNAPSHOT
![eclipse che che-gotoline - chromium_005](https://cloud.githubusercontent.com/assets/650571/24917307/06d01caa-1edd-11e7-8ca1-de86a1cfe36a.png)

**Comment by vzhukovs** [comment]
Update status: issue temporary frozen due to server side vfs refactorings. Waiting for using native JDK functionality instead of VFS layer.

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by dkulieshov** [comment]
Seems like this is not actual.
<img width="932" alt="2017-11-27 18 07 29" src="https://user-images.githubusercontent.com/1632360/33276401-245487b8-d39e-11e7-838f-020760a298d1.png">

**Comment by slemeur** [comment]
Closing the issue as it is solved with Che 6

**Comment by RomanNikitenko** [comment]
It is fixed for master branch too https://github.com/eclipse/che/pull/7096
