### ISSUE TITLE
Code highlighting and preview for Markdown

### ISSUE THREAD

**Issue by merlijn-sebrechts** [eclipse-che/che#3932]
Does Che support syntax highlighting and previewing markdown documents?

I'd like to use this for two reasons:

- To simplify markdown editing (almost any project on Github uses markdown, Eclipse Che included)
- To give the user documentation when he starts a new workspace. I want to put markdown documentation in the workspace and show it to the user after the workspace is started. Che's vision is to make contributing to code as easy as possible. Showing the user documentation after starting a workspace will bring us closer to that goal.

**Comment by TylerJewell** [comment]
Hello.  Unfortunately this is something that is missing and badly needed right now.  We really need an editor extension built that allows for dual viewing of content and preview for HTML and markdown files.  

We have another PR that has been open for quite awhile that adds a default markdown file for every project to be displayed in the editor upon boot.  We have chosen not to merge this PR yet as we wanted to wait for the editor to support markdown previews too.

Theoretically adding this sort of previewed to our editor should be straight forward but it would require an engineer to focus on it as a task for a sprint or two.

**Comment by merlijn-sebrechts** [comment]
Thanks for your reply! What about syntax highlighting for markdown?

**Comment by TylerJewell** [comment]
Syntax highlighting for markdown was added as part of the pull request that is pending. https://github.com/eclipse/che/pull/2628.  Syntax highlighting updates are easier - they are an extension to the Orion editor that we embed and make use of.

**Comment by merlijn-sebrechts** [comment]
Thanks! Awesome!

I'd argue that syntax highlighting + default README is good enough in itself to merge. Markdown is pretty human-readable especially with syntax highlighting.

**Comment by TylerJewell** [comment]
I agree with that.  We are also open to other pull requests to advance this work more quickly.  It's partly held up because we have been working for many months on a concept called Intelligent Commands (see the epic in the issues), and this implementation then has us rethink the concept of a "Preview" which is mostly a server concept today.  But once we get that implementating of new previews in there, then this markdown / HTML perspective becomes really urgent.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
