### ISSUE TITLE
Adding examples and stack icons using REST API

### ISSUE THREAD

**Issue by merlijn-sebrechts** [eclipse-che/che#3933]
1. Is there a way to add project templates/examples and stack icons using the REST API?
2. Is the REST API the preferred way to customize a Che installation or should I change the files in the data directory?

**Comment by TylerJewell** [comment]
Hi @galgalesh - Yes, in terms of adding / removing stacks & templates, REST will be the most consistent way to work with these right now.  As you have probably seen, our UX for adding / removing / editing stacks is well-developed. And that is persistent. However, we do not have the same UX for templates (which we rename to samples).

In both cases, the UD experience is 100% driven by REST APIs, and the REST APIs are relatively well documented with Swagger. In some of the closed issues, there are others that are discussing this preferred flow.

With stacks and templates, there is a stacks.json file that you can modify which causes 1-time loading of those items when Che boots. However, that stacks.json is not considered the persistent storage of Che. Che is backed by disk-based database, and the REST commands that load / edit / save those stacks / templates guarantee that they are persisted against the persistence model.

**Comment by TylerJewell** [comment]
@galgalesh - in reading the docs, we really do not make this basic process for custom assembly developers clear. I'm going to assign this task / how-to for an engineer in an upcoming sprint.  We'll get this cleaned up and clearer.  It's really simple, but our docs don't make it simple.

**Comment by TylerJewell** [comment]
In a discussion with @gazarenkov,  he clarified the use cases more concisely.

Case 1: If want to modify stacks / templates database of existing install - change it via REST/GUI
Case 2: If want to modify stacks / templates for a custom install (advanced case) - they change JSON files

We have fairly good docs on #1.  We don't really have it for #2 and will get that cleared up.

**Comment by ghost** [comment]
@galgalesh for REST calls, you may just open  browser console, network tab, and play with stacks in User Dashboard.

**Comment by merlijn-sebrechts** [comment]
Thanks for your answers!

The docs don't seem to mention how to add a stack *icon* and how to add a *project sample*. I also can't find how to do this in the GUI. Is this possible at all?

**Comment by ghost** [comment]
@galgalesh you may edit `$cheDataFolder/instance/data/stacks/stacks.json` and `$cheDataFolder/instance/data/stacks/images` to add a new stack and an icon for it.

Same thing happens to templates:

`$cheDataFolder/instance/data/templates/samples.json`

**Comment by merlijn-sebrechts** [comment]
Thanks!

These files are generated by Che when Che first starts. Currently I start Che, stop Che, edit the files, and start Che again. Is there an easier method or is this the way to go?

**Comment by TylerJewell** [comment]
Not right this moment, but there will be soon. We don't think we nailed the custom assembly approach very well.  So, we are working on some changes to really emphasize the following:

1. If you have an existing installation AND you want to modify the stacks, Che must be running and then you use either our APIs or the dashboard (which in turn uses the APIs). This updates the database which is the permanent record of truth.  This database also takes precedence over anything that is a JSON that was saved on the file system.

2. If you are working on a custom assembly where the assembly packaging will be distributed to others AND you want to modify the default set of stacks that appear in the assembly, then this will require a custom assembly and we'll provide a list of files that you edit which define what is loaded in the first execution of the Che server. Once the Che server is instantiated for an install, then end users will update the stacks through the UD or REST API, which is case #1.

We are working on some utilities which will make it deadly easy to create a minimal custom assembly with exactly the files you need to edit to custom a stack or a template.

**Comment by ghost** [comment]
@TylerJewell what should we do with this issue? We do have plans to make it possible to edit/add/remove stacks system wide, get rid of JSONs etc.

**Comment by TylerJewell** [comment]
Can you cross-link the other issues related to this topic on managing system stacks.  Standard practice is to cross-link other issues and then to leave this issue open until they are resolved.

**Comment by ghost** [comment]
The problem is that there's no such epic. It's work to be done.

@skabashnyuk may elaborate.

**Comment by TylerJewell** [comment]
This is the cross-linked issue - https://github.com/eclipse/che/issues/3629#issuecomment-276058132

**Comment by ghost** [comment]
I'm going to close this issue. Please follow https://github.com/eclipse/che/issues/3629
