### ISSUE TITLE
Navigation by keyboard does not work into dropdown of the 'Navigate To File'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3934]
When I use the 'Navigate To File', then navigation by keyboard does not work, if to do one click on a file into dropdown.

**Reproduction Steps:**
* Open a project in the IDE (e.g. web-java-spring from template).
* Invoke 'Navigate To File' from menu or by keyboard 'Ctrl+Alt+N'.
* Enter symbol 'p' and make one click on a file into dropdown.

**Expected behavior:**
* navigation by keyboard should work.

**Observed behavior:**
* navigation by keyboard should not work
* select a file by 'Enter' does not work also

**Che version:** 5.2.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version: 1.12**
**Che cli.log output**:  [cli.log.zip](https://github.com/eclipse/che/files/735436/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachments:
![navi_to_file_keyboard](https://cloud.githubusercontent.com/assets/5408906/22374105/57ca0752-e4ad-11e6-86d2-59f408520d1b.png)

**Comment by slemeur** [comment]
Cannot reproduce
