### ISSUE TITLE
Start che with --volumes-from using /data in data container

### ISSUE THREAD

**Issue by asthomasdk** [eclipse-che/che#3936]
I am trying to get Eclipse Che with docker working using a data container for /data instead of using a local bind mounted volume. 

Using local volumes goes against our standard for dockerized setups, as we want to be as independent of the host file systems as possible. 

**Reproduction Steps:**

So I was trying a simple setup like this: 
First, create a "che-data" container: 

`docker create --name che-data -v /data busybox`

Try to start che using this data container: 

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock --volumes-from che-data eclipse/che `start

**Che version:**    5.1.2

**OS and version:**    
RancherOS 0.7.1

**Docker version:** 1.12.3

**Che cli.log output:**  

```
WARN: Bound 'eclipse/che' to 'eclipse/che:5.1.2'
INFO: Welcome to Eclipse Che!
INFO: 
INFO: We could not detect a location to save data.
INFO: Volume mount a local directory to ':/data'.
INFO: 
INFO: Simplest syntax:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/data
INFO:                          eclipse/che start
INFO: 
INFO: 
INFO: Or, run with additional overrides:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/data
INFO:                       -v <YOUR_INSTANCE_PATH>:/data/instance
INFO:                       -v <YOUR_BACKUP_PATH>:/data/backup
INFO:                          eclipse/che start
```

This would be similar to creating a fdata container in docker-compose and using this - which I have not tried yet, but I assume this will give the same error. 

Question is - does che not support using data containers for data storage?

**Comment by TylerJewell** [comment]
The Che CLI explicitly looks for a volume mounted :/data folder and hard interrupts if it does not find it. That folder is used to write files from inside the container onto the host for the admin to see / work with during a restart, particularly the `che.env` file.  This sort of sequence allows to make sure that for people unfamiliar with Docker, they can have a clean and consistent startup experience with guided help, and also a clear location for where their Che files will be for editing.

If you use a docker volume the way you did, you will not necessarily know where the host location is for those files.  How would you plan to gain access to that?

It may be possible to adapt the CLI to support such a concept, but the concern would be that users who start to use such a syntax would no longer know where to go to find their core files.

Also, the CLI is a launcher for eclipse/che-server, which is just the server container. So you can bypass the whole thing and use that instead, which has its own separate rules about file management, but it's a more complicated container just dedicated for starting / stopping the core Che server, whereas the CLI has a lot of helper management.

**Comment by asthomasdk** [comment]
Thanks Tyler. 

In short, I don't really care where the local files are located ;-) as they are managed inside the container. If we created hosted setups with a Che server - we would never expect the users to have access to the host file system. 

It would also be a part of trying to get a setup working where we can have multiple Che servers on the same physical machine - which I don't know if you can either. 

With regards to knowing where the files are located, you can used named Docker volumes to make it easier to find the local directories. 

Another reason for being able to do this is to be able to use some of the many Docker volume drivers that are available or coming out - where there is a big focus on being able to set up distributed file systems - again with the end users of the containers not caring or needing to know where the directories and files are on the host or cluster of hosts.

**Comment by TylerJewell** [comment]
You can definitely run multiple che servers on a single machine. But that gets to be expensive. Wouldn't you want to just upgrade to Codenvy for that? *cough, cough*.

On the docker volume stuff - how would you as an administrator know the host location for each docker volume?  In the reading that we have done on the subject, when you create a docker volume, the location is usually in some dynamically generated directory that is not easily accessible.  In a situation where you are running a moby VM (Docker for Windows or Mac), this directory would not be accessible by a user (or admin) on the host because it's buried inside of a moby VM that is not SSH accessible.

I have not studied other docker volume drivers or plugins, so maybe you are thinking of those items and they may have flexible admin tools for administering where / how those volumes are host mounted.

**Comment by asthomasdk** [comment]
I may be overlooking something simple or conceptually here... why do you need to know or be able to work with the host directory for the che data?  Is it not possible to work everything that you need from the IDE and Che web interface? 

If I to setup a separate host with a Che server that is accessible on the network - is there anything I need to be able access on the host?

**Comment by TylerJewell** [comment]
There are a couple of things that warrant host access today:
1. If an admin of che needs to modify system properties, they are all done in the `che.env` file. We have not implemented anything within the Che server yet that lets you see these properties, modify them, and then execute a reboot of Che's container services.  You could envision a dashboard utility that does this graphically.  Or, perhaps we extend the CLI to display and edit those properties similar to how `git` works.  But in the absence of that, if you want to make any Che system modifications - those need to be done in that file.

2. All of your workspace projects are stored on the file system and then mounted into the workspace's containers. There are edge scenarios where letting a user have direct file system access to those files outside of Che is necessary.  These scenarios are rare, but usually involve workspaces that have projects that themselves are doing `docker build` or `docker run`, so in this situation the system is configured with workspaces having access to a docker daemon and the che server configured to point to those host files. It's a bit of a pain to configure this now, but if you are doing docker in docker in docker sort of development using che workspaces, then this is necessary.

3. If you need to generate a diagnostic bundle for support, the CLI generates this file and places it on the host system.

4. When we generate backup packages using the CLI, this TAR file is generated and saved on the host system.

None of these items are critical to just a blindless end user running the system, but those are the host dependencies right now.

**Comment by asthomasdk** [comment]
ok - thanks for the info. 

That explains well why it runs as it does now. 

It doesn't make it easy for us to set up Che like we do with many other docker based systems, so we'll have to look into that some more.

**Comment by TylerJewell** [comment]
I'm intrigued by this request - let me have some time to noodle on it.  

I think the difference is that with Che it's both a desktop app and a server application, so there are circumstances where end users want desktop-style host access that we try to accommodate. But in pure server scenarios, volumes-from would be the expected and preferred approach to abstract all of the file systems.

**Comment by asthomasdk** [comment]
Exactly ;-)

**Comment by TylerJewell** [comment]
@riuvshin @vkuznyetsov - FYI, this is the original early issue that triggered the thoughts.

1. Make /data optional
2. Use our property overrides on command line for configuring che.env
3. Allow for volumes-from setting of volumes
4. A process for how to save workspaces to disk as a result

**Comment by carloreggiani** [comment]
I'm trying to deploy Eclipse Che (6.5.0) on Docker EE 2.0 and I'm in trouble to assign a /data folder to a "local" volume (I'm executing only docker client on my pc configured by Docker EE client env.cmd).

This issue is close, but it seems nothing change... it means Eclipse Che doesn't support volume containers?

```
docker volume create eclipseche_volume
docker run  -it --rm  -e CHE_MULTIUSER=true -e CHE_HOST=dockeree.xxxx.com -v /var/run/docker.sock:/var/run/docker.sock -v eclipseche_volume:/data eclipse/che:6.5.0 start

INFO: Welcome to Eclipse Che!
INFO:
INFO: We could not detect a location to save data.
INFO: Volume mount a local directory to ':/data'.
INFO:
INFO: Simplest syntax:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/data
INFO:                          nexq.cadit.it/eclipse/che:6.5.0 start
INFO:
INFO:
INFO: Or, run with additional overrides:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/data
INFO:                       -v <YOUR_INSTANCE_PATH>:/data/instance
INFO:                       -v <YOUR_BACKUP_PATH>:/data/backup
INFO:                          nexq.cadit.it/eclipse/che:6.5.0 start
```
