### ISSUE TITLE
Codenvy and custom plugins

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-che/che#3938]
This is a question about contributing custom plugins into Codenvy.  I have created some plugins which build fine with Che, but I’m not certain how to build them into Codenvy.

My plugins:
org.eclipse.che.plugin:che-plugin-servicedev-ide
org.eclipse.che.plugin:che-plugin-servicedev-server
org.eclipse.che.plugin:che-plugin-servicedev-shared
 
I believe I put them where they need to go and put the dependencies in the right places (modeled after plugin-java).
 
I am getting the following error when building:
 [ERROR] Failed to execute goal on project onpremises-ide-compiling-war-ide: Could not resolve dependencies for project com.codenvy.onpremises:onpremises-ide-compiling-war-ide:war:5.2.0-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.che.plugin:che-plugin-servicedev-ide:jar:5.2.0-SNAPSHOT, org.eclipse.che.plugin:che-plugin-servicedev-shared:jar:5.2.0-SNAPSHOT: Failure to find org.eclipse.che.plugin:che-plugin-servicedev-ide:jar:5.2.0-SNAPSHOT in https://maven.codenvycorp.com/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of codenvy-public-repo has elapsed or updates are forced -> [Help 1]
 
Of course, my plugins will not be in https://maven.codenvycorp.com/content/groups/public/.  I guess I can put them into my local Maven repository  /home/user/.m2 …, but I don’t know how to build them into jars within Codenvy.
 
Any tips would be greatly appreciated.
 
Thank you,
 
Barry

Codenvy version: Source from master branch, 5.1.2 docker image
OS and version:
 Linux usrscp28 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 system VMware Virtual Platform
 bus 440BX Desktop Reference Platform
 memory 87KiB BIOS
 processor Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz

Docker version: 1.12.1
 API version: 1.24

**Comment by ghost** [comment]
@BarryDrez What version did you use in your plugins? You need to compile them locally and then build Codenvy assembly. As far as I understand you have already added all the dependencies into the right modules. Makes sure that your plugins are the same version, i.e. `5.2.0-SNAPSHOT`. Or explicitly use your plugin versions in Codenvy pom.xmls where you have added them.

**Comment by skabashnyuk** [comment]
@BarryDrez can I take a look on your source code?

**Comment by BarryDrez** [comment]
[plugin-servicedev.zip](https://github.com/eclipse/che/files/738905/plugin-servicedev.zip)

**Comment by BarryDrez** [comment]
Hi @skabashnyuk, my source is attached.

**Comment by BarryDrez** [comment]
@eivantsov, I have used 5.2.0-SNAPSHOT for the version in my plugins.  What I do not know is how to compile locally.  Do you men I should compile them in Che and port over to Codenvy?

**Comment by skabashnyuk** [comment]
@BarryDrez what should I do with this sources to get error like you have?

**Comment by BarryDrez** [comment]
Hi @skabashnyuk.  What I did (and I am not sure if this is correct or not) is extract the source and import it as 4 Maven projects under:
${user.home}/codenvy/dashboard/bower_components/che-dashboard/plugins.
Before that, I have cloned the master branch of Codenvy from github.
I have some dependent jar files that I installed into my local Maven repository.  I can get you those if you need them.  I installed using commands like:
mvn install:install-file -Dfile=com.softwareag.g11n_9.12.0.0000-0006.jar -DgroupId=softwareag -DartifactId=g11n -Dversion=9.12 -Dpackaging=jar
In ${user.home}/codenvy/pom.xml, I added my plugins as dependencies:

            <dependency>
              <groupId>org.eclipse.che.plugin</groupId>
               <artifactId>che-plugin-servicedev-ide</artifactId>
               <version>${che.version}</version>
             </dependency>
             <dependency>
               <groupId>org.eclipse.che.plugin</groupId>
               <artifactId>che-plugin-servicedev-server</artifactId>
               <version>${che.version}</version>
             </dependency>
             <dependency>
               <groupId>org.eclipse.che.plugin</groupId>
               <artifactId>che-plugin-servicedev-shared</artifactId>
               <version>${che.version}</version>
             </dependency>   
In ${user.home}/codenvy/assembly/onpremises-ide-compiling-war-ide/pom.xml, I added:
        <dependency>
            <groupId>org.eclipse.che.plugin</groupId>
            <artifactId>che-plugin-servicedev-ide</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che.plugin</groupId>
            <artifactId>che-plugin-servicedev-shared</artifactId>
        </dependency>

In ${user.home}/codenvy/assembly/onpremises-ide-packaging-war-ext-server/pom.xml, I added:
        <dependency>
            <groupId>org.eclipse.che.plugin</groupId>
            <artifactId>che-plugin-servicedev-ide</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che.plugin</groupId>
            <artifactId>che-plugin-servicedev-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che.plugin</groupId>
            <artifactId>che-plugin-servicedev-shared</artifactId>
        </dependency>

In ${user.home}/codenvy/dashboard/bower_components/che-dashboard/plugins/pom.xml, I added:
<module>plugin-servicedev</module>

In ${user.home}/codenvy/assembly/onpremises-ide-compiling-war-ide/src/main/resources/com/codenvy/ide/IDE.gwt.xml, I added: 
<inherits name='org.eclipse.che.plugin.servicedev.ServiceDev'/>

In ${user.home}/codenvy/dashboard/bower_components/che-dashboard/plugins/plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/actions/SwitchPerspectiveAction.java, I added:

        radioButtonGroup.addButton("", "Switch to Service Development Perspective", resources.serviceDevelopmentPerspective(),
                new ClickHandler() {
                    @Override
                    public void onClick(ClickEvent event) {
                        perspectiveManager.setPerspectiveId("Service Development Perspective");
                    }
                });


Thanks for your help.  Please let me know if there is anything else you need from me.

**Comment by ghost** [comment]
@BarryDrez do you have an entire assembly with your plugins? Also, why is your plugin in /dashboard/bower_components?

**Comment by BarryDrez** [comment]
@eivantsov, Yes, I am trying to create an entire assembly.  I have done this with Che with the same plugins but this is my first attempt to try with Codenvy. I put my plugins in codenvy/dashboard/bower_components/che-dashboard/plugins because I saw other ones there (like in Eclipse Che), so I assumed that mine should go there as well.  Is there a set of procedures that explain how I should be doing what I am attempting?  Thanks

**Comment by ghost** [comment]
@BarryDrez I recommend that you create plugins directory and put your plugins there. Make sure you compile them before you build the assembly where you edited poms and gwt.xml.

**Comment by BarryDrez** [comment]
Hi @eivantsov, Initially, I put my plugins here: codenvy/plugins (same folder as plugin-bitbucket, plugin github, plugin-gitlab, etc.).  It built without any errors, but when I started Codenvy, there was no trace of my plugins in the UI.  Wondering how I could allow switching to my custom perspective?

**Comment by BarryDrez** [comment]
Forgetting my specific scenario, How would I implement a plugin sample from Che in Codenvy?

**Comment by ghost** [comment]
1. You need to build your plugins.
2. You need to add dependencies to Codenvy assembly
3. You need to build this assembly.

@BarryDrez it will help us if you create an assembly with your plugins and let us take a look.

**Comment by BarryDrez** [comment]
@eivantsov, I'm pretty new to Codenvy.  Can you tell me what you consider to encompass an assembly?  Which components do you need?  And how should I get it to you?  Thanks

**Comment by TylerJewell** [comment]
@BarryDrez - I think Eugene is referring to the docs on this page.  https://codenvy.com/docs/white-labels/custom-assemblies/index.html.  He is trying to figure out which step failed you.

**Comment by BarryDrez** [comment]
Thank you Tyler and Eugene.  I will work on my assembly and get back to you asap.

**Comment by BarryDrez** [comment]
@eivantsov - Today when I try to build, I am getting the following error:
[ERROR] warning: unknown enum constant CascadeType.ALL
  reason: class file for javax.persistence.CascadeType not found
warning: unknown enum constant FetchType.EAGER
  reason: class file for javax.persistence.FetchType not found
warning: unknown enum constant FetchType.LAZY
/home/usabdr/codenvy/plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedDockerInstance.java:[61,14] error: incompatible types: DockerConnector cannot be converted to DockerConnectorProvider
[ERROR] /home/usabdr/codenvy/plugins/plugin-hosted/codenvy-machine-hosted/src/main/java/com/codenvy/machine/HostedMachineProviderImpl.java:[95,14] error: incompatible types: DockerConnector cannot be converted to DockerConnectorProvider

Any ideas?

**Comment by vinokurig** [comment]
@BarryDrez Can you show me your source code with latest changes?

**Comment by BarryDrez** [comment]
@vinokurig, @eivantsov is currently putting together some very simple sample extensions for me.  Hopefully, this will reveal the correct way to do this.  Thank you.

**Comment by ghost** [comment]
@BarryDrez I am closing this issue as you have got an assembly from me.
