### ISSUE TITLE
CHE-528 Icons and items in git merge window are not fit in line

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#394]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-528
Reporter:  Igor' Vinokur
Description: It is hard to understand what is selected in git merge window.
See attachment.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/dcdee680df047903cffc0505b10efbfd5ac0f021
