### ISSUE TITLE
Workspace created from dockerfile doesn't start behind a proxy

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#3948]
When workspace recipe is dockerfile and it contains instructions sensitive to proxy settings it doesn't start.

**Reproduction Steps:**
Start WS from docker file
```
FROM ubuntu
RUN apt-get update && apt-get install mc
CMD tail -f /dev/null
```
It is because Che doesn't pass proxy settings into docker build parameters.
All we need is to add proxy settings to build request.
 
**OS and version:**    
Ubuntu 16.04

**Comment by slemeur** [comment]
@garagatyi Is this issue still accurate?

**Comment by garagatyi** [comment]
Though I can't check it without proxy I do believe that it is actual because I don't see code needed to fix that in the repo

**Comment by garagatyi** [comment]
Here is an instruction how to configure Che/Codenvy behind a proxy to test how product behaves:

1. Configure docker
1.1. set http_proxy, https_proxy, no_proxy in docker daemon (google how to do it in your system)
1.2. set dns in docker daemon (google how to do it in your system)
1.3. Check proxy settings in docker info (IDK how to check that DNS settings are read properly)
2. Configure Che/Codenvy
2.1. set http_proxy, https_proxy, no_proxy in che/codenvy.env for master (CODENVY_HTTP_PROXY_FOR_CODENVY, CODENVY_HTTPS_PROXY_FOR_CODENVY, CODENVY_HTTPS_PROXY_FOR_CODENVY or corresponding properties for Che)
2.2. set http_proxy, https_proxy, no_proxy in che/codenvy.env for workspaces (CODENVY_HTTP_PROXY_FOR_CODENVY_WORKSPACES, CODENVY_HTTPS_PROXY_FOR_CODENVY_WORKSPACES, CODENVY_NO_PROXY_FOR_CODENVY_WORKSPACES or corresponding properties for Che)
2.3. set dns in che/codenvy.env (CODENVY_DNS_RESOLVERS or corresponding property for Che)
3. Configure proxy and dns in your browser
4. If users need to use sudo in docker build/inside of container they should use sudo -E to pass proxy settings to root's env or set proxy settings themselves.
