### ISSUE TITLE
Language Server Protocol : Code Action

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#3957]
The codeaction request is sent from the client to the server to compute code actions for a given text document and Diagnosis. This should be part of #2109 

See also:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_codeAction

**Comment by tsmaeder** [comment]
Working on this.
My approach is to look for an action that has the same id as the "command" field of the code action. The extra parameters will be passed to the action in an extended subclass of ActionEvent.

For the purposes of this issue, I'd like to implement a "lsp.applyTextEdit" action that applies a list of lsp TextEdit objects to the current editor.
In second step, it would make sense to implement "lsp.applyWorkspaceEdit" to implement changes to more than just one file. However, I would do that in a separate PR.

**Comment by benoitf** [comment]
Fixed by https://github.com/eclipse/che/pull/4345
