### ISSUE TITLE
Remove usage of the Machine API in the Chedir

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#3967]
Remove usage of the Machine API in Chedir. Example: [here](https://github.com/eclipse/che/blob/master/dockerfiles/lib/src/api/wsmaster/machine/machine-service-client.ts) and replace with exec's.

**Comment by benoitf** [comment]
I don't see why it's a blocker as I was not informed that it's gonna be removed and that when the code has been changed to use agent, job was not done on all parts ?

**Comment by skabashnyuk** [comment]
Sorry we thought that we know all places where it's used.  now we know what cheConf/ che dir is used it too.  severity/blocker set to inform about our intent to remove Deprecated Machine API asap.

**Comment by benoitf** [comment]
why the job of migrating machine api to agent was not including chedir ?

**Comment by skabashnyuk** [comment]
We don't know how it works and want to delegate it to authors who knows how it works.

**Comment by skabashnyuk** [comment]
PR where we introduced exec https://github.com/eclipse/che/pull/2163

Available API:
-  [REST API](https://github.com/eclipse/che/blob/exec-agent/exec-agent/docs/rest_api.md)
-  [Websocket API](https://github.com/eclipse/che/blob/exec-agent/exec-agent/docs/ws_api.md)
-  [Events](https://github.com/eclipse/che/blob/exec-agent/exec-agent/docs/events.md)

@benoitf  Do you know where Chedir functionality is located?

**Comment by benoitf** [comment]
@skabashnyuk sorry I didn't see your question
https://github.com/eclipse/che/blob/master/dockerfiles/lib/src/internal/dir/che-dir.ts

**Comment by skabashnyuk** [comment]
I see that ```/api/workspace``` is used in three places in https://github.com/eclipse/che/blob/master/dockerfiles/lib/src/internal/dir/che-dir.ts
-  checkCheIsNotRunning
- checkCheIsRunning
- pingCheAction

@benoitf Am I correct ?

**Comment by benoitf** [comment]
@skabashnyuk there are other places
I think you are interested in calls to machine API which are only there:
https://github.com/eclipse/che/blob/master/dockerfiles/lib/src/api/wsmaster/machine/machine-service-client.ts
