### ISSUE TITLE
Workspace folder exists inside "che" folder after deletion workspace on dockerized CHE.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#3973]
**Reproduction Steps:**
1. Run dockerized CHE, create and run new workspace, create project inside workspace.
2. Stop workspace.
3. Remove workspace.
4. Open folders `~/che/data/instance/data/workspaces/` , ( "~/che" this is default location, if you set another place you should correct path).
Actual result: 
Deleted workspace folder with created project still exists inside "workspaces".
Expected result:
"workspaces" folder should not contains data with deleted workspaces.

**OS and version:**    
Ubuntu 16.04 and Fedora 24
CHE version: 5.2.0-SNAPSHOT

**Comment by garagatyi** [comment]
Setting high priority since it increases time needed engineers to do QA on their feature branches. This is expensive bug in terms of RD time

**Comment by ghost** [comment]
Does not work on Windows 8
