### ISSUE TITLE
Unable to find image 'eclipse/che:5.2.0' locally

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#3974]
I am trying to setup the Eclipse Neon with latest che git repository.
https://www.eclipse.org/che/docs/plugins/setup-che-workspace/index.html

chakraborty@intus:~/slx/che/assembly/assembly-main/target/eclipse-che-5.2.0-SNAPSHOT/eclipse-che-5.2.0-SNAPSHOT$ ls -ll
total 48
drwxr-xr-x  2 root root  4096 Jan 31 21:20 bin
drwxr-xr-x  2 root root  4096 Jan 31 21:20 conf
drwxr-xr-x  4 root root  4096 Jan 31 21:20 lib
-rw-rw-r--  1 root root 11514 Jan 26 12:55 LICENSE
drwxr-xr-x  5 root root  4096 Jan 31 21:20 plugins
-rw-rw-r--  1 root root  1031 Jan 26 12:55 README
drwxr-xr-x  6 root root  4096 Jan 31 21:20 sdk
drwxr-xr-x  3 root root  4096 Jan 31 21:20 stacks
drwxr-xr-x  2 root root  4096 Jan 31 21:20 templates
drwxr-xr-x 10 root root  4096 Jan 31 21:20 tomcat
chakraborty@intus:~/slx/che/assembly/assembly-main/target/eclipse-che-5.2.0-SNAPSHOT/eclipse-che-5.2.0-SNAPSHOT$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:5.2.0 start
Unable to find image 'eclipse/che:5.2.0' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/eclipse/che/manifests/5.2.0: Get https://auth.docker.io/token?scope=repository%3Aeclipse%2Fche%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
chakraborty@intus:~/slx/che/assembly/assembly-main/target/eclipse-che-5.2.0-SNAPSHOT/eclipse-che-5.2.0-SNAPSHOT$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:5.2.0 start
Unable to find image 'eclipse/che:5.2.0' locally
docker: Error response from daemon: manifest for eclipse/che:5.2.0 not found.
See 'docker run --help'.

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by TylerJewell** [comment]
Hi.  Your syntax was correct for how to mount the repo.  But you don't need to have the Che image match the version in your repo.  So you can just run `eclipse/che:5.1.2` and it will use your local assembly inside that older image.

We haven't shipped eclipse/che:5.2.0 yet so the image does not exist.

**Comment by abchakra** [comment]
sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:5.1.2 start
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using assembly and manifests from your local repository
INFO: (che cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
INFO: (che cli): Loading cli...
/repo/dockerfiles/cli/scripts/cli.sh: line 10: BOOTSTRAP_IMAGE_CHEIP: unbound variable

**Comment by TylerJewell** [comment]
Ok, use the 'nightly' version instead.  When you are doing development with Che, you may have image mutability because our images have image dependencies, and all of your images need to be just proper.

**Comment by abchakra** [comment]
It is working , thanks !!!

**Comment by abchakra** [comment]
sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:nightly start

**Comment by TylerJewell** [comment]
Cool!  What do you think of the new way to start / stop Che?  We put a lot of effort into this syntax - we think it's pretty cool.
