### ISSUE TITLE
How to run the custom assembly

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#3975]
This will create an assembly in {workspace-path}\che\assembly\assembly-main\target\eclipse-che-<version>\eclipse-che-<version>

for instance I have that in the following directory:
/home/chakraborty/slx/che/assembly/assembly-main/target/eclipse-che-5.2.0-SNAPSHOT/eclipse-che-5.2.0-SNAPSHOT/

To start Che from the custom assembly you just built, you can refer to this Usage: Development Mode Launcher.
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock \
                    -v <local-path>:/data \
                    -v <local-repo>:/repo \
                    eclipse/che:<version> start
 

for my example it should be like this.

docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /home/chakraborty/tmpCHE:/data \
                    -v /home/chakraborty/slx/che:/repo \
                    eclipse/che:5.2.0 start

but this doesn't run 
chakraborty@intus:~/slx/che/assembly/assembly-main$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:5.2.0 start
[sudo] password for chakraborty: 
Unable to find image 'eclipse/che:5.2.0' locally
docker: Error response from daemon: manifest for eclipse/che:5.2.0 not found.
See 'docker run --help'.

Can you please help me out where i am getting this wrong.

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by chetanladdha** [comment]
@abchakra : I am also facing similar issue, can you please elaborate, how you resolved it ?

**Comment by TylerJewell** [comment]
You opened another ticket.  The question was addressed there.

**Comment by abchakra** [comment]
update the che git repo to latest master
my location che git repo "/home/chakraborty/slx/che"

and use "eclipse/che:nightly"


docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:nightly start

**Comment by TylerJewell** [comment]
This is a closed issue - please only address your questions on open issues that you file with appropriate diagnostic information.
