### ISSUE TITLE
/scripts/base/commands/cmd_start.sh: line 75: CHE_MIN_RAM: unbound variable

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#3977]
chakraborty@intus:~/slx/che/assembly/assembly-main$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:nightly start
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using assembly and manifests from your local repository
INFO: (che cli): nightly - using docker 1.13.0 / native
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che

Digest: sha256:4f816d934b4774a2b15d85e89883fbb24b0083fa3b49b5708444d33b57d9074e
Status: Image is up to date for eclipse/che:nightly

INFO: (che download): Pulling image eclipse/che-init:nightly

nightly: Pulling from eclipse/che-init

Digest: sha256:f226788d581cd25be946a022cf4e11434ce3fb3032205ad1afde792f8a678f8a
Status: Image is up to date for eclipse/che-init:nightly

INFO: (che download): Pulling image eclipse/che-server:nightly

nightly: Pulling from eclipse/che-server

Digest: sha256:6706bdf7087a3f2b3bd55ba43723cfb74bec3184099fd6a50ddf801a7ce2baff
Status: Image is up to date for eclipse/che-server:nightly

INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che config): Copying local binaries to /home/chakraborty/cheData/instance/dev...
INFO: (che start): Preflight checks
WARNING: No swap limit support
/scripts/base/commands/cmd_start.sh: line 75: CHE_MIN_RAM: unbound variable
/scripts/base/commands/cmd_start.sh: line 79: CHE_MIN_RAM: unbound variable
chakraborty@intus:~/slx/che/assembly/assembly-main$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.25/containers/json: dial unix /var/run/docker.sock: connect: permission denied
chakraborty@intus:~/slx/che/assembly/assembly-main$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
chakraborty@intus:~/slx/che/assembly/assembly-main$

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
can you try ```docker pull eclipse/che:nightly``` and restart che?

**Comment by abchakra** [comment]
`

chakraborty@intus:~/slx/che/assembly/assembly-main$ sudo docker pull eclipse/che:nightly
nightly: Pulling from eclipse/che
Digest: sha256:4f816d934b4774a2b15d85e89883fbb24b0083fa3b49b5708444d33b57d9074e
Status: Image is up to date for eclipse/che:nightly
chakraborty@intus:~/slx/che/assembly/assembly-main$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:nightly start
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using assembly and manifests from your local repository
INFO: (che cli): nightly - using docker 1.13.0 / native
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che
Digest: sha256:4f816d934b4774a2b15d85e89883fbb24b0083fa3b49b5708444d33b57d9074e
Status: Image is up to date for eclipse/che:nightly

INFO: (che download): Pulling image eclipse/che-init:nightly

nightly: Pulling from eclipse/che-init
Digest: sha256:f226788d581cd25be946a022cf4e11434ce3fb3032205ad1afde792f8a678f8a
Status: Image is up to date for eclipse/che-init:nightly

INFO: (che download): Pulling image eclipse/che-server:nightly

nightly: Pulling from eclipse/che-server
Digest: sha256:6706bdf7087a3f2b3bd55ba43723cfb74bec3184099fd6a50ddf801a7ce2baff
Status: Image is up to date for eclipse/che-server:nightly

INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che config): Copying local binaries to /home/chakraborty/cheData/instance/dev...
INFO: (che start): Preflight checks
WARNING: No swap limit support
/scripts/base/commands/cmd_start.sh: line 75: CHE_MIN_RAM: unbound variable
/scripts/base/commands/cmd_start.sh: line 79: CHE_MIN_RAM: unbound variable
chakraborty@intus:~/slx/che/assembly/assembly-main$ 
`

**Comment by abchakra** [comment]
I have tried deleting my data location /home/chakraborty/cheData/ , but of not use. Same if I try to run default version 5.1.2

**Comment by abchakra** [comment]
/scripts/base/commands/cmd_start.sh: line 75: CHE_MIN_RAM: unbound variable
/scripts/base/commands/cmd_start.sh: line 79: CHE_MIN_RAM: unbound variable

**Comment by ghost** [comment]
@abchakra you mount your local repo as well, and script are inherited from there. Can you make sure your che repo is up to date when you use nightly image?

**Comment by abchakra** [comment]
Thanks updating local che repo worked !!!
