### ISSUE TITLE
Tabs stacks absent on the dashboard (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#3981]
When I try to create a template project from stack, then tabs stack do not present on the dashboard.

**Reproduction Steps:**
* Go to 'Dashboard' -> 'Create Workspace' -> select radio button 'Create new workspace from stack'.

**Expected behavior:**
* should be displayed the tabs stacks

**Observed behavior:**
* tabs stacks are not displayed

**Che version:** 5.2.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12
**Che cli.log output:** [cli.log.zip](https://github.com/eclipse/che/files/744303/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachments:
![dashboard_stack_tab](https://cloud.githubusercontent.com/assets/5408906/22500600/d306205e-e86d-11e6-9a4c-ee34ca67fc9f.png)

**Comment by riuvshin** [comment]
this is a blocker because it is not possible create workspace from stack on UD
