### ISSUE TITLE
Che CLI is not considering local assembly

### ISSUE THREAD

**Issue by chetanladdha** [eclipse-che/che#4002]
I am trying to use the local Che assembly. I have followed below steps still, I am not able to see Che with local assembly. 
Am I missing any steps?

**Reproduction Steps:**
c:\dev\che5.2.0\che (master)
λ mvn clean install -Pfast -pl !dashboard
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:47 min
[INFO] Finished at: 2017-02-02T15:53:58+05:30
[INFO] Final Memory: 551M/1803M
[INFO] ------------------------------------------------------------------------

````
λ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/cpra/tmp:/data -v /c/dev/che5.2.0/che:/assembly eclipse/che-cli:nightly start

WARN: Boot2docker detected - ensure :/data is mounted to %userprofile%
INFO: (che cli): :/assembly mounted - using assembly from local host
INFO: (che cli): nightly - using docker 1.13.0 / boot2docker
INFO: (che download): Pulling image eclipse/che-cli:nightly

nightly: Pulling from eclipse/che-cli
Digest: sha256:44cb634008926d07ede24b594c02a5f3da41d65291948e2b2d1bdb7d1e657ac7
Status: Image is up to date for eclipse/che-cli:nightly

INFO: (che start): Booted and reachable
INFO: (che start): Ver: nightly
INFO: (che start): Use: http://192.168.99.101:8080
INFO: (che start): API: http://192.168.99.101:8080/swagger
````

**OS and version:**    
Windows 7 Professional

I can see the Che up but it's not considering my local assembly. I would be happy to provide more details if you needed.

**Comment by ghost** [comment]
@chetanladdha AFAIK, only user home directory gets mounted into the VM.

`/c/dev/che5.2.0/che` does not exist in the VM. Can you move your Che repository, say, to `/c/Users/cpra/che` and give it a try again?

**Comment by TylerJewell** [comment]
Because you are using boot2docker you can only mount folders that are part of %userprofile%

It is a limitation of the boot2docker virtualbox vm.

**Comment by chetanladdha** [comment]
I change the location and started building it, now I faced that server is starting but nothing on that host and port.

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/cpra/tmp:/data -v /c/Users/cpra/che5.2.0/che:/assembly eclipse/che-cli:nightly start`
```
INFO: (che start): Booted and reachable
INFO: (che start): Ver: nightly
INFO: (che start): Use: http://192.168.99.101:8080
INFO: (che start): API: http://192.168.99.101:8080/swagger
```
`but on http://192.168.99.101:8080, I don't get che up.

**Comment by TylerJewell** [comment]
Do you have firewall issues and the necessary ports opened?

**Comment by ghost** [comment]
@TylerJewell if CLi managed to reach Che API, then there should not be any connectivity issues. 

@chetanladdha what do you mean by Che is not up? What do you have at http://192.168.99.101:8080?

**Comment by TylerJewell** [comment]
@eivantsov - you are totally right, duh - of course.  I'm pre-caffeine this morning, so brain is not fully on yet.

**Comment by chetanladdha** [comment]
http://192.168.99.101:8080 is not reachable. I am getting site can't be reach error.

**Comment by ghost** [comment]
`docker run -d -p 80:80 nginx`

And go to http://192.168.99.101

Can you see nginx welcome page?

**Comment by chetanladdha** [comment]
When I run the command and went to 192.168.99.101, observed same error but when I went to 192.168.99.100, I got ngnix welcome page. Also, I got the http://192.168.99.100:8080/ up with no stacks and no project.  

`C:\Users\cpra\che5.2.0\che>docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/cpra/tmp/:/data -v /c/Users/cpra/che5.2.0/che/:/assembly eclipse/che-cli:nightly start
WARN: Boot2docker detected - ensure :/data is mounted to %userprofile%
INFO: (che cli): :/assembly mounted - using assembly from local host
INFO: (che cli): nightly - using docker 1.13.0 / boot2docker
WARN: **CHE_HOST (192.168.99.100) overridden by che.env (192.168.99.101)**
INFO: (che download): Pulling image eclipse/che-cli:nightly`

```
`INFO: (che start): Starting containers...
INFO: (che start): Services booting...
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Booted and reachable
INFO: (che start): Ver: nightly
**INFO: (che start): Use: http://192.168.99.101:8080**
INFO: (che start): API: http://192.168.99.101:8080/swagger`
```

**Comment by ghost** [comment]
Can you check C:\Users\cpra\tmp\instance directory?

**Comment by chetanladdha** [comment]
yes, a directory has stack folder which is empty. I will re-run and check.

**Comment by ghost** [comment]
Can you delete what you have there? And re-run?

**Comment by chetanladdha** [comment]
After re-run, I am able to see the project but still problem persist.

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/cpra/tmp:/data -v /c/Users/cpra/che5.2.0/che:/assembly eclipse/che-cli:nightly start
`
Che is not up with local assembly....

**Comment by TylerJewell** [comment]
That syntax is incorrect. You must mount the full path to the assembly all the way down to where the /bin folder lives.   I think you really want the :/repo mount which only requires the root of the Che repo.

**Comment by ghost** [comment]
@chetanladdha what if you flush your local data directory and try it without mounting your local binaries? Can you see stacks?

**Comment by ghost** [comment]
@chetanladdha is this still an issue for you?

**Comment by chetanladdha** [comment]
Sorry for late and thanks for your comments.  I am not able to reproduce it more, closing this bug.
