### ISSUE TITLE
CHE-530 Add a tooltip for the SSH button

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#401]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-530
Reporter:  Valeriy Svydenko
Description: The functionality of the SSH button isn't clear for the user. Need to add a tooltip.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/97bf08672df9e1eeb90ee8f7616e0f3b3e7f3f0b
