### ISSUE TITLE
Deleted file is not added to index

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#4015]
When I try to add to index deleted file, then it is not added to index.

**Reproduction Steps:**
* Open a project in the IDE
* Delete a file from the project
* Try to add to index it

**Expected behavior:**
* file should be added to index

**Observed behavior:**
* file is not added to index

**Che version:** 5.2.0-SNAPSHOT
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachments:
![add_to_index](https://cloud.githubusercontent.com/assets/5408906/22586888/db9272b8-ea07-11e6-8d85-994ab21ce708.gif)

**Comment by mmorhun** [comment]
Fixed
