### ISSUE TITLE
Eclipse Che start fails due to some connection issues

### ISSUE THREAD

**Issue by RobertBrown3** [eclipse-che/che#4021]
I am new to Eclipse Che and am attempting to start Che on a local machine. I am running the latest version (v5.2.2?)  under Docker v1.13.

I have followed the instructions for a local install provided at https://www.eclipse.org/che/docs/setup/getting-started/index.html

I successfully installed Docker and was able to start up Che using the following command:

sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/tstuser/software/docker:/data eclipse/che start

Note that I did not edit anything in the configuration (I didn't know about that yet). I just installed Docker and attempted the Che startup. Unfortunately, my attempt to start yielded the following result:

WARN: Bound 'eclipse/che' to 'eclipse/che:5.2.2'
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
INFO: (che cli): 5.2.2 - using docker 1.13.0 / native
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]

ERROR: Try 'docker run <options> eclipse/che info --network' for more tests.

Since the failure did not give ay substantive information, I did as the above error message suggested:

sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/tstuser/software/docker:/data eclipse/che info --network

This yielded the following:

WARN: Bound 'eclipse/che' to 'eclipse/che:5.2.2'
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
INFO: (che cli): 5.2.2 - using docker 1.13.0 / native
INFO: 
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: (che network): eclipse/che-ip: 172.17.0.1
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (172.17.0.1): Connection failed
INFO: (che network): Server  => Workspace Agent (External IP): Connection failed
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded

My first thought after seeing these lines was to look for configuration problems. I found the che.env file and read up on configuration at https://www.eclipse.org/che/docs/setup/configuration/index.html. Because I do not have any machines with IP 172.17.0.1, I set so,e of the configurations (like the CHE_HOST) to the address of the machine I was running Che on.

My configuration attempts failed. First, Che continued to generate the same failures as the ones in the connectivity test above. These were the exact same messages: attempts to connect to 172.17.0.1! The only difference in the messages this time was an additional warning saying that I had overridden 172.17.0.1 with my machine's IP address! Despite everything I tried, Che keeps insisting on attempting to connect to non- existent 172.17.0.1.

I am pretty sure I am missing something here, but I have no idea what that is. I have read through che.env and the configuration page, but have had no real help in stopping those connection failures.

So what am I missing. Someone please advise...

**Comment by TylerJewell** [comment]
It seems like the override of CHE_HOST was not set.  Are you sure it was configure?

Please run the info command and maybe the "info --bundle" for diagnostic information.

**Comment by ghost** [comment]
@RobertBrown3 `172.17.0.1` is your `docker0` IP.

What is your OS? Can you try disabling firewall? When firewall is on, I have the same issues on Ubuntu, since it blocks communications between containers.

**Comment by RobertBrown3** [comment]
Tyler:

Thanks for the advice. It helped find the problem.

I ran the "info --bundle" and generated the tar archive (neat, the way that works!). I looked at the various files in the archive.

I found that 172.17.0.1 is the IP of my docker0 "device", which is a bridged adapter created by the docker server. I also found out that che, as part of its network check, was running a curl command that attempted to connect to docker0 through port 32768. Since I am running a firewall on my system, that port was blocked. Once I unblocked it, everything worked.

eivantsov: FYI the OS I am using is CentOS 7 and, for various reasons, I need to keep my firewall enabled. That being said, I wish I had read your post before now, because it might have saved me some time.

A suggestion for the documentation: the Che folks might want to tell people about which ports should be open when doing a local install. That way, someone can know to either disable their firewalls or open the right ports before running Che.

One last question: how on Earth do you pronounce "Che"?

**Comment by TylerJewell** [comment]
Great that you found that it was a blocked port!

Che is pronounced "Chay".

And yes - we do a good job of documenting ports on Codenvy, a derivative of Che, but it seems like those docs never made their way over to Che.  We'll get them over now.

**Comment by carusyte** [comment]
It seems to be port 32768 by the way.

**Comment by hlalvesbr** [comment]
It's a firewall problem:
Try
firewall-cmd --permanent --new-zone dockerc
firewall-cmd --permanent --zone dockerc --add-port 8080/tcp
firewall-cmd --permanent --zone dockerc --add-port 32768/tcp
firewall-cmd --reload
