### ISSUE TITLE
Explicitly set protocol for ssh agent 

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#4025]
**Problems:**
* protocol is not defined
* there is no `Runtime url`  at `Servers` section on Dashboard

**Solution:**
Add protocol here:
https://github.com/eclipse/che/blob/c8dafb9c6b04f5a50b9ed6b0d033a91aedfc016b/agents/ssh/src/main/resources/org.eclipse.che.ssh.json#L8
Check `Runtime url`

**Comment by gazarenkov** [comment]
set severity to P1 since it impacts on data returned by API (w/o protocol it can not generate runtime URL)
