### ISSUE TITLE
ERROR: Image eclipse/che:nightly unavailable. Not on dockerhub or built locally.

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#4032]
chakraborty@intus:~/slx/che/assembly$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/chakraborty/cheData:/data -v /home/chakraborty/slx/che:/repo eclipse/che:nightly start
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using assembly and manifests from your local repository
INFO: (che cli): nightly - using docker 1.13.0 / native
INFO: (che download): Pulling image eclipse/che:nightly

Error response from daemon: Get https://registry-1.docker.io/v2/eclipse/che/manifests/nightly: Get https://auth.docker.io/token?scope=repository%3Aeclipse%2Fche%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 127.0.1.1:53: read udp 127.0.0.1:51119->127.0.1.1:53: i/o timeout
ERROR: Image eclipse/che:nightly unavailable. Not on dockerhub or built locally.

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:** 

chakraborty@intus:~/slx/che/assembly$ sudo docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by TylerJewell** [comment]
That is a local Docker networking issue - not a Che issue.  That is just a docker pull command from inside the CLI.

**Comment by abchakra** [comment]
Can i start che without docker ??

**Comment by TylerJewell** [comment]
We do not support starting Che's tomcat without Docker.  Keeps everyone honest by only requiring the Docker-based approach to starting the server, so that engineers are using the product the same way that end users are using it.

You can save the Docker images using the "offline" method and then start Che using Docker without networking.
