### ISSUE TITLE
How can I verify if my IDE plugins are successfully loaded into the CHE IDE

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#4033]
I have been struggling to verify whether my IDE plugin is loaded or not, as sometime it shows up  and some time it doesn't.

Are there some physical locations where i can verify if the jars are loaded or not.

**Comment by vzhukovs** [comment]
Hi @abchakra! It depends on the type of plugin. If plugin is based for the client (UI) you can click to _Profile_ (menu bar) -> _Preferences_ -> _Plug-Ins_ _List_, and see where your plugin loaded or not.

![eclipse che](https://cloud.githubusercontent.com/assets/1968177/22684006/2fbc5fb6-ed23-11e6-9916-78f96468e7b0.png)

**Comment by ghost** [comment]
@abchakra you may also look into ROOT.war of your ws-agent.

**Comment by ghost** [comment]
Closing the issue, as the questions seems to have been answered. Feel free to reopen though if you have more questions.
