### ISSUE TITLE
Receive event about created file after resuming file watching

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#4039]
It seems there is a problem particular with create file operation and file watcher.

**Reproduction Steps:**
1. suspend file watching service via client;
2. send a request to project service to create a new file;
3. wait some time;
4. resume file watching service via client;
5. receive a notification about created file.

**Che revision:**    9c0eec214a4363dfa0ea7dfdf4c565492d953226

**Comment by vparfonov** [comment]
not actual
