### ISSUE TITLE
Disable Orion Editor

### ISSUE THREAD

**Issue by jtcressy** [eclipse-che/che#4048]
I fired up a meteor project and upon opening any JS file, it flags almost every symbol as invalid syntax. 

**Reproduction Steps:** ``$ meteor create`` then open any .js file in the editor

**Eclipse/che version:** Codenvy 5.2.2

![image](https://cloud.githubusercontent.com/assets/7663028/22700678/b51b3ac0-ed18-11e6-8e11-2a9b14cd6d3f.png)

Are you really only able to add/remove plugins by re-building che? [see here](https://www.eclipse.org/che/docs/plugins/create-and-build-extensions/)

**Comment by TylerJewell** [comment]
@ashumilova @eivantsov - this is fair question.  I was doing a search in our archives as this has been asked before, but the search did not show any particular issues with a similar topic.  Do you know the answer?

**Comment by ghost** [comment]
It is being taken care of - https://github.com/eclipse/che/issues/2781

**Comment by ghost** [comment]
@jtcressy Closing as duplicate of https://github.com/eclipse/che/issues/2781
