### ISSUE TITLE
Eclipse Che plugin: Getting error trying to use local assembly

### ISSUE THREAD

**Issue by hrajan123** [eclipse-che/che#4052]
Hi,
I am trying to setup development of Che to build an extension. I am using the 5.2.0 build and tried running on both windows and Ubuntu using the local assembly. I can start the server but get the following error while creating a new project. I see other issues with this error but i am unable to resolve my issue. I am trying to setup a demo and am running short of time so would appreciate any quick help to set up my dev env.

**Timeout. The Che server is unable to ping your workspace. This implies
 a network configuration issue, workspace boot failure, or an unusually slow wor
kspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to p
ing your workspace. This implies a network configuration issue, workspace boot f
ailure, or an unusually slow workspace boot.
        at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java
:128) ~[wsagent-5.2.0.jar:5.2.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(W
orkspaceRuntimes.java:693) ~[che-core-api-workspace-5.2.0.jar:5.2.0]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsL
auncher.started(WorkspaceRuntimes.java:1054) ~[che-core-api-workspace-5.2.0.jar:
5.2.0]**

**Reproduction Steps:**
This is the command i am running on windows
$ docker run -p 8080:8080 --name xyz504 --rm -v /var/run/docker.sock:/var/run/d
ocker.sock -v /c/tmp:/data  -e CHE_HOST=192.168.99.100 -v /c/che-source/assembly/assembly-main/target/eclipse-che-5.1.2/eclipse-che-5.1.2 -e:/assembly eclipse/che-server:5.2.0

**OS and version:**    
Windows 
**Diagnostics:**

**Comment by TylerJewell** [comment]
Your syntax has a mistake.  `:/assembly` is a mount, not a variable.

```
docker run -p 8080:8080 --name xyz504 --rm 
-v /var/run/docker.sock:/var/run/docker.sock 
-v /c/tmp:/data 
-e CHE_HOST=192.168.99.100 
-v /c/che-source/assembly/assembly-main/target/eclipse-che-5.1.2/eclipse-che-5.1.2:/assembly eclipse/che-server:5.2.0
```

**Comment by hrajan123** [comment]
I am sorry that was a typo, this was the command i used

$ docker run -p 8080:8080 --name xyz503 --rm -v /var/run/docker.sock:/var/run/d
ocker.sock -v /c/tmp:/data  -e CHE_HOST=192.168.99.100 -v /c/che-source/assembl
y/assembly-main/target/eclipse-che-5.1.2/eclipse-che-5.1.2:/assembly  eclipse/che-server:5.2.0

**Comment by hrajan123** [comment]
I referred to the documentation on this page
[https://eclipse.org/che/docs/setup/docker/index.html#use-local-che-assembly]

If there is an updated doc elsewhere please let me know..I am fine with setting it up on either windows or linux

**Comment by TylerJewell** [comment]
When you run Che stand alone, you do not get this error?  Out of curiosity, if you mount :/repo to the root of the che repo and run it, do you get the same error?

**Comment by hrajan123** [comment]
It fails with the same error in both cases. I am using docker, do i need to set env variables like CHE_HOST, CHE_DOCKER_EXTERNAL_IP ?

I remember running Che successfully sometime back...not sure what build i had used earlier.

**Comment by TylerJewell** [comment]
Let's take the assembly out of the equation.  Are you able to just run Che normally?

**Comment by hrajan123** [comment]
No, I get the same error

**Comment by hrajan123** [comment]
Well, i added -e CHE_DOCKER_IP and that helped resolved the issue with creating workspaces on my linux setup. So i am good for now. Thanks!

**Comment by TylerJewell** [comment]
@hrajan123 - I am very glad to hear that it worked for you.  Thanks for the persistence.
