### ISSUE TITLE
CHE CLI does not detect that that there is newer image on hub

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#4060]
devs reported issue that CLI does not work in some cases, after some investigation I;ve figured out that due to some reason CHE CLI does not detect if there is newer nightly on hub and does not pull `che-cli:nightly` while codenvy CLI check this normally.

**Comment by benoitf** [comment]
what is the command used to start ?
what is the --trace output ?

**Comment by riuvshin** [comment]
@benoitf I will try to reproduce it locally and will provide more info. 
for now all I know is that @dkuleshov showed me that CLI failed and when I asked him to pull 
`eclipse/che-cli:nightly` it pulled newer image (I checked he didn't use any skips or --fast it was only start command)

**Comment by riuvshin** [comment]
unable to reproduce locally, I've build `che-cli:nightly` image locally (i've added simple echo to make it different) and when I run `start` it pulled newer image as expected. So I think in @dkuleshov  usecase he had outdated CLI locally which wasn't able to pull itself.
