### ISSUE TITLE
Timeout waiting for server

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#4062]
OS : linux-ubuntu 16.04 64-bit
Che : version 5.2.2
Docker : version 1.13.0

Getting this error, attach with a picture below.

![selection_005](https://cloud.githubusercontent.com/assets/1939446/22747677/b3c5acb4-ee62-11e6-81d5-80b09c1a8abf.jpg)

And attach with the log file.
[catalina-0.txt](https://github.com/eclipse/che/files/761345/catalina-0.txt)

**Comment by bmicklea** [comment]
Can you try running without `--fast` and send a screenshot of the output? There are a number of checks we perform by default that are skipped when you do --fast.

**Comment by thyeun** [comment]
result without --fast

![selection_006](https://cloud.githubusercontent.com/assets/1939446/22748357/c6e4e90c-ee64-11e6-8ea8-b3d31b5149fa.jpg)

**Comment by bmicklea** [comment]
Have you tried the suggestions in 1, 2 and 3?  If so what were the results/actions?

**Comment by thyeun** [comment]
i'm not using proxy

![selection_007](https://cloud.githubusercontent.com/assets/1939446/22748575/765a41e8-ee65-11e6-80e0-9c0ae0ff16fa.jpg)

![selection_008](https://cloud.githubusercontent.com/assets/1939446/22748685/ce4328ca-ee65-11e6-8741-821d1f377a72.jpg)

So, which one given me wrong/fault result?

**Comment by TylerJewell** [comment]
The test you did with curl was done on your host. But we run the CLI (and its tests) inside of a container. So, there can be differences from time to time from the results that you would get from running the command on the host vs. running the same command in a container.  So you can test the container scenario with `docker run --net host appropriate/curl --head dockerhub.com` as an alternative.

But I am suspicious that is not going to be your problem.

1. You can add `--skip:network` to skip this test that causes a hard failure.
2. The actual test that we are doing is to run `curl -I -k dockerhub.com -s -o /dev/null --write-out '%{http_code}'`.  If this returns a code of 301, then we could not reach DockerHub.

This is almost always a DNS resolver issues *inside* the container. Your container inherits certain proxy or networking settings from your Docker Daemon.  So run `docker info` and `info --bundle` to get more details to help figure this out.

**Comment by thyeun** [comment]
when i try using --skip:network , i getting another two error

![selection_009](https://cloud.githubusercontent.com/assets/1939446/22757584/6fac7728-ee86-11e6-84ef-8d471179df82.jpg)

**Comment by TylerJewell** [comment]
Wipe all of your docker images and try it again.  That sort of error shouldn't be occurring - so could be a CLI version mismatch.  If it happens again, append --trace to the end and then paste the part where there are issues in that section.

**Comment by thyeun** [comment]
after wipe all of the docker images, this is the outcome with --skip:network

![selection_010](https://cloud.githubusercontent.com/assets/1939446/22768157/1cfbb414-eebb-11e6-81d2-9b9339f232d6.jpg)

**Comment by ghost** [comment]
Same issues here - https://github.com/eclipse/che/issues/4071


Can you give it a try with nigthly tag?

**Comment by thyeun** [comment]
@eivantsov morning, yes, same issue, but i think it is docker issue, because it only happen on docker version 1.13.

**Comment by ghost** [comment]
I have just updated my Docker to 1.13. Cannot reproduce. I am on Ubuntu 14.04

**Comment by thyeun** [comment]
@eivantsov, ok, will give nightly a try, and will update the result too, thanks!

**Comment by thyeun** [comment]
@eivantsov, do you restart docker after updated?

**Comment by ghost** [comment]
Yes, I have restarted it

**Comment by thyeun** [comment]
@eivantsov, result with --skip:network

![selection_011](https://cloud.githubusercontent.com/assets/1939446/22785463/55ca8596-ef0f-11e6-9dfd-4100627f0d81.jpg)

**Comment by ghost** [comment]
a small test to run:

`docker run -d -p 80:32779 nginx`
`docker run -ti appropriate/curl sh`

when in that container:
`# curl -v 172.17.0.1:32779`

Can you reach nginx running in container A from container B?

**Comment by thyeun** [comment]
@eivantsov, normal result and --fast result.

![selection_012](https://cloud.githubusercontent.com/assets/1939446/22785635/1a59419a-ef10-11e6-9767-2d517c4f9f25.jpg)

![selection_013](https://cloud.githubusercontent.com/assets/1939446/22785641/1f9301a0-ef10-11e6-9d9b-a5ac7fd8f8f2.jpg)

**Comment by thyeun** [comment]
@eivantsov, for nginx, do i need to install also, since i'm not using nginx and the service are not activated!

**Comment by ghost** [comment]
With `--fast`, is it ok when you access Che in the browser?

**Comment by thyeun** [comment]
not possible.

**Comment by ghost** [comment]
Can you share server logs? Have you tried using the default port, by the way?

**Comment by thyeun** [comment]
This one???

[catalina-0.txt](https://github.com/eclipse/che/files/763836/catalina-0.txt)

**Comment by ghost** [comment]
Yes.

So, there's nothing at localhost:9000?

**Comment by thyeun** [comment]
yup, nothing to reach!

**Comment by ghost** [comment]
And with default port?

**Comment by thyeun** [comment]
same nothing

**Comment by ghost** [comment]
I cannot reproduce it at all.

Can you run `docker run -d nginx` and go to localhost? Do you see nginx welcome page?

**Comment by thyeun** [comment]
Result for 

docker run -d -p 80:32779 nginx
docker run -ti appropriate/curl sh

when in that container:
 curl -v 172.17.0.1:32779

![selection_014](https://cloud.githubusercontent.com/assets/1939446/22786438/7b19b890-ef13-11e6-9276-4ddae4259910.jpg)

**Comment by ghost** [comment]
And `docker run -d nginx` and then going to localhost in your browser?

Share output from `ifconfig`

**Comment by thyeun** [comment]
Result docker run -d nginx

![selection_015](https://cloud.githubusercontent.com/assets/1939446/22786562/05264ac6-ef14-11e6-97b7-f2f56c160271.jpg)

localhost at browser nothing! (did not have the welcome page)

**Comment by thyeun** [comment]
all my step are correct?

**Comment by thyeun** [comment]
my docker version and build

Docker version 1.13.0, build 49bf474 !!!

**Comment by ghost** [comment]
Oops, my bad.

`docker run -d -p 80:80 nginx`

And then check localhost.

**Comment by thyeun** [comment]
cant, my 8080 are in-use, that why i change CHE_PORT to 9000

**Comment by ghost** [comment]
port 80. not 8080

**Comment by thyeun** [comment]
Result error

docker: Error response from daemon: driver failed programming external connectivity on endpoint thirsty_lichterman (6e096bd3c553f810254b7896269e4fa18214f4360444193c26aa567aaa6e90aa): Bind for 0.0.0.0:80 failed: port is already allocated.

**Comment by ghost** [comment]
Make it 81. `-p 81:80`. Then localhost:81

**Comment by thyeun** [comment]
no error, but nothing at browser (did not have welcome page)

**Comment by ghost** [comment]
You need to fix that. Smth is wrong with network.

**Comment by thyeun** [comment]
cant figure out what goes wrong

**Comment by ghost** [comment]
You may want to file an issue with Docker

**Comment by thyeun** [comment]
due to what? if it is my network issue, than docker wont care about it.

i'm still try to figure out what goes wrong with my network configuration. 

anyway, thanks for helping me up, on catching some error that appear from my system. =.=

and sorry for create an issue that not related with Che.
