### ISSUE TITLE
Failed to create resource Internal error Time

### ISSUE THREAD

**Issue by bule0017** [eclipse-che/che#4068]
Hi
I recently installed Eclipse Che docker image and everything worked ok. I created three workspaces.
But today when I started eclipse-che docker image it wont create new file.
I check date and timezone on container and it was not the same as my linux host.
How to fix this?
Thank you very much

**Comment by ghost** [comment]
Can you elaborate on the issue please? It is not quite clear at what stage you get the error. Please, share logs and/or screenshots.

**Comment by bule0017** [comment]
Sorry for bad explanation. Here is the screenshoot:
![capture](https://cloud.githubusercontent.com/assets/24639708/22788698/f0faf926-eee0-11e6-8ba6-2e6c7dc98b19.PNG)

**Comment by bule0017** [comment]
You can close this issue.
I deleted opened projects and create new one and everthing is ok now.
Thank you
