### ISSUE TITLE
CHE-536 Differentiate explicitly created and detected projects on Workspace Agent. Do not save detected to Master ProjectConfig. 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#408]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-536
Reporter:  Gennady Azarenkov
Description: From the behaviour standpoint there are two types of projects:
1/ Ones created explicitly - by user's add, import/update etc Project calls
2/ Detected projects - like Maven modules calculated using parent's pom.xml and files structure.

Projects of 1-st type should be synchronized with Projects Config stored on Workspace Master side, projects of 2-nd type are initialized every time when "parent" project initialized .

**Comment by ddementieva** [comment]
Fixed
