### ISSUE TITLE
Information missing in workspace/runtime interface

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4080]
![image](https://cloud.githubusercontent.com/assets/20580888/22791378/c62eac24-eeae-11e6-877d-5f53fa35aa0c.png)

Using codenvy nightly staging server.

**Comment by JamesDrummond** [comment]
@ashumilova @slemeur Please take a look at this.

**Comment by slemeur** [comment]
What was your flow?
Really strange - can't reproduce it:
![screen shot 2017-02-09 at 17 05 45](https://cloud.githubusercontent.com/assets/1636769/22791554/137446b6-eeea-11e6-88a5-7d1da14ce2da.png)

Maybe a cache issue...
What happened when you refreshed the browser?

Maybe @olexii4 and @akurinnoy would have an idea too?

**Comment by vitaliy-guliy** [comment]
@JamesDrummond  Could you record a little video and say what browser do you use?

**Comment by JamesDrummond** [comment]
OK must be a cache thing thank goodness. It's working igcognito.

**Comment by JamesDrummond** [comment]
Sorry it's not cache. I have 4k monitor and opened igcognito with smaller browser window. Below is video. Relabelling with lower severity.  

Google chrome Version 56.0.2924.87 (64-bit)

![issue](https://cloud.githubusercontent.com/assets/20580888/22792515/a1b487b6-eeb2-11e6-8dd7-df45d8adc8b2.gif)

**Comment by vitaliy-guliy** [comment]
It looks like it's a CSS issue. Thanks.

**Comment by vitaliy-guliy** [comment]
I can not reproduce it on a1 with the latest dashboard.

![can not reproduce](https://cloud.githubusercontent.com/assets/1655894/22818021/84352c06-ef73-11e6-8a2a-58ab669ffaba.png)

**Comment by ashumilova** [comment]
will try to handle it along with this one https://github.com/eclipse/che/issues/3819

**Comment by JamesDrummond** [comment]
@vitaliy-guliy Need 4k monitor I think which is why I put severity at P2. What is your monitor resolution?

**Comment by ghost** [comment]
@ashumilova can you please verify if this is still an issue with new dashboard flows? thanks

**Comment by ashumilova** [comment]
Will be fixed by https://github.com/eclipse/che/issues/4359 (agents section)
