### ISSUE TITLE
Question about dto factory using childs classes

### ISSUE THREAD

**Issue by Bihlou** [eclipse-che/che#4089]
Actually I've 4 interfaces :

 ```
@DTO
public interface Class Garage {
	public List<Vehicle> getVehicle();
	public void setVehicle(List<Vehicle> vehicle);
}

@DTO
public interface Vehicle {
	public String getBrand();
	public void setBrand(String brand);
}

@DTO
public interface Car extends Vehicle{
	public int getSeat();
	public void setSeat(int seat);
}

@DTO
public interface Motorbike extends Vehicle {
	public String getName();
	public void setName(String name);
} 
```

Server side I create my dto garage adding a car in vehicle :

 ```
@Path("Garage")
@POST
public Garage getGarage() throws ServerException{

...
Car car = DtoFactory.getInstance().createDto(Car.class);
car.setBrand("brand");
car.setSeat(5);
Garage garage = DtoFactory.getInstance().createDto(Garage.class);
List<Vehicle> vehicleList = new ArrayList<Vehicle>();
vehicleList.add(car);
garage.setVehicle(vehicleList);
...
return garage; 
```

Client side I try to get back the car : 
 ```
Promise<PricingDataDto> promise = serviceClient.getGarage();
promise.then(new Operation<Garage>() {
@Override
public void apply(Garage garage) throws OperationException {
	Vehicle vehicle = garage.getVehicle().get(0);
    Car car = (Car) vehicle;
 ```
But I got a class cast exception.
When I look in the Json using for deserialization I see classes aren't stored, so class `Vehicle` specified in dto `Garage` is used and I lost all specifics parameters about `Car`.

I also try to use generic in `Garage` : 
 ```
@DTO
public interface Class Garage {
	public List<? extends Vehicle> getVehicle();
	public void setVehicle(List<? extends Vehicle> vehicle);
}
 ```
but I got an error during mvn clean install :

`...:generate failed: We do not handle this type -> [Help 1]`

Do you know if I can used dto factory this way or if I need to do semething else ?

**Comment by TylerJewell** [comment]
@mshaposhnik @sleshchenko @garagatyi @skabashnyuk @akorneta @evoevodin - you guys are some of our Java experts. You will be better positioned to answer a question about DTO transformation than I would.

@Bihlou - looks like you are getting into some engineering dev level questions for customization. It may be easier to connect you with some of our internal engineers that do not spend a lot of time online, especially if you are working on a complicated, big project (they'll be happy to learn what you are building).  You can email me directly if you want.

**Comment by vinokurig** [comment]
@Bihlou It looks like you have a mistake in initializing `garage` DTO.
Try to change:
`Garage garage = DtoFactory.getInstance().createDto(Car.class);` to 
`Garage garage = DtoFactory.getInstance().createDto(Garage.class);`

**Comment by Bihlou** [comment]
@vinokurig sorry it was a typo, I've updated my example.
My problem is I can't do `Car car = (Car) vehicle;` (got a class cast exception) probably because during the process of serialization / deserialization I lost my reference to `Car`.

@TylerJewell thank you, I've send an email to you

**Comment by garagatyi** [comment]
DTO mechanism doesn't store class information as you said. So you can't do such cast after you transferred DTO over network.
