### ISSUE TITLE
Creating workspaces by a compose recipe url does not work (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#4094]
I try to create a workspace by a recipe compose url, then it is not created.

**Reproduction Steps:**
* On the dashboard go to the 'Workspaces' -> 'Add Workspace' -> 'Runtime' -> 'Stack import'
* Enter recipe url (e.g. https://gist.githubusercontent.com/idexmai/6918415efa88276bdf028756adc8b9fb/raw/04ea419e25e02d010a03d75278606c3e2218e1e6/composeJavaStack)
* Try to create the workspace

**Expected behavior:**
* workspace should be created

**Observed behavior:**
workspace is not created, there is error message

**Che version:** 5.3.0
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12
**Che install:** Docker container
**Che cli.log output:**  [cli.log.zip](https://github.com/eclipse/che/files/766593/cli.log.zip)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![ws_by_compose_url](https://cloud.githubusercontent.com/assets/5408906/22826340/973b3076-ef9a-11e6-9597-d35d3e2fe2e2.png)

**Comment by riuvshin** [comment]
fixed by https://github.com/eclipse/che/pull/4087
