### ISSUE TITLE
Agents installation  specification

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4096]
- agent installation workflow
- agent installation API (how client should connect to it, stream and interpret data)

**Comment by garagatyi** [comment]
### Glossary:
WS - workspace

### Master - Bootstrapper workflow

1. Master starts WS.
1. Master starts Machine and passes needed environment configuration and an object that contains full definition of agents (including install scripts and dependent agents) in order they are supposed to be started. It is up to implementation to decide how binaries of _Bootstrapper_ should be delivered into machine.
**Agents config file format:**
``` json
[
   {
      "id":"exec",      
      "description":"Agent for command execution",
      "version":"1.0",
      "script":"$HOME/che/exec-agent -addr :4412",
      "servers":{
         "execAgent":{
            "port":"4412/tcp",
            "protocol":"http",
            "path":"/exec"
         }
      }
   }
]
```
3. Master adds Machine into lists of machines waiting for status confirmation.
1. If Machine doesn’t update status that moves it to the next step of booting until timeout expires Master stops machine forcefully and declares that it failed booting. WS start fails too.
1. Machine starts.
1. Machine gets _Bootstrapper_ binaries and starts it.
1. Machine starts _Bootstrapper_ and passes path to agents definition file. 
1. Machine adds _Bootstrapper_ logs into machine logs. It is supposed that logs of this agent should have appropriate prefix, e.g. [_Bootstrapper_].
1. _Bootstrapper_ opens WebSocket connection to master and notifies master that it was started.
1. _Bootstrapper_ starts agents defined by file one-by-one.
1. _Bootstrapper_ notifies master about states of agents.
1. Master waits for successful state of all agents in all machines and performs check of ws-agent that its API is responding. If it is not true and ws-agent start timeout expires WS is treated as failed booting and should be forcefully stopped.

### _Bootstrapper_ - agents workflow:
1. _Bootstrapper_ notifies Master that it started
1. _Bootstrapper_ notifies Master that particular agent starts
1. _Bootstrapper_ executes agent installation script
1. _Bootstrapper_ streams agent logs and states to interested sides
1. _Bootstrapper_ checks agent for installation state:
   1. If Agent contains server
      1. _Bootstrapper_ checks connection to socket on local port of machine
      1. If it is successful agent is treated as started
      1. Otherwise check is repeated with some delay.
      1. If agent boot time expires and last check failed agent is treated as failed
   1. If Agent contains multiple servers
      1. The same, but _Bootstrapper_ checks all ports
   1. If Agent doesn’t contain server
      1. IA waits until installation ends.
      1. If installation script exit code 0 agent is treated as booted.
      1. If installation script exit code differs from 0 agent is treated as failed
      1. If installation doesn’t end when installation time expires agent is treated as failed.
1. _Bootstrapper_ notifies Master about state of agent

## Note: 

it is supposed that _Bootstrapper_ will communicate with Master and clients using JSONRPC protocol we started using recently for communication between ws-agent and IDE client.

### Bootstrapper events

- _Bootstrapper_ is ready to push events. Occurs when bootstrapper is configured to push events on start, it connects to the specified websocket url(workspace master probably) and publishes this event before any other event.
```
{
  "jsonrpc": "2.0",
  "method": "bootstrapper/statusChanged",
  "params": {
    "status": "STARTING",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```
- Bootstrapping done, everything is started ok.
```
{
  "jsonrpc": "2.0",
  "method": "bootstrapper/statusChanged",
  "params": {
    "status": "DONE",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```
- Bootstrapping failed(when any agent fails or any error occurs), followed by disconnect and `os.Exit(1)`.
```
{
  "jsonrpc": "2.0",
  "method": "bootstrapper/statusChanged",
  "params": {
    "status": "FAILED",
    "error" : "couldn't start agent X",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```

### Installer events

- _Bootstrapper_ starts installer X
```
{
  "jsonrpc": "2.0",
  "method": "installer/statusChanged",
  "params": {
    "status": "STARTING",
    "installer": "org.eclipse.che.ws-agent",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```

- _Bootstrapper_ successfully started installer X(No server defined)
```
{
  "jsonrpc": "2.0",
  "method": "installer/statusChanged",
  "params": {
    "status": "DONE",
    "installer": "org.eclipse.che.ws-agent",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```

- _Bootstrapper_ successfully started installer X(Server defined)
```
{
  "jsonrpc": "2.0",
  "method": "installer/statusChanged",
  "params": {
    "status": "RUNNING",
    "installer": "org.eclipse.che.ws-agent",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```

- _Bootstrapper_ failed to start Installer X
```
{
  "jsonrpc": "2.0",
  "method": "installer/statusChanged",
  "params": {
    "status": "FAILED",
    "installer": "org.eclipse.che.my-agent",
    "error": "Install script exit code -1",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```

- Installer X stderr
```
{
  "jsonrpc": "2.0",
  "method": "installer/log",
  "params": {
    "text": "no command found",
    "stream": "STDERR",
    "installer": "org.eclipse.che.ws-agent",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```

- Installer X stdout
```
{
  "jsonrpc": "2.0",
  "method": "installer/log",
  "params": {
    "text": "Starting server...",
    "stream": "STDOUT",
    "installer": "org.eclipse.che.ws-agent",
    "machineName": "my-machine",
    "runtimeId": {
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
    },
    "time": "2017-02-23T16:22:22.50287146+02:00"
  }
}
```

**Comment by akorneta** [comment]
Added specification for **installer** config into **2nd** item.

**Comment by evoevodin** [comment]
Changed _AI_ in spec on _Installer_.

**Comment by voievodin** [comment]
Changed name _Installer_ to _Bootstrapper_

**Comment by TylerJewell** [comment]
Bootstrapper

- Tyler : 978-884-5355

On June 12, 2017 at 10:52 GMT, Yevhenii Voevodin <notifications@github.com> wrote:

Changed name Installer to Bootstraper

**Comment by voievodin** [comment]
Defined bootstrapper events.

**Comment by voievodin** [comment]
Changed `bootstrapper/statusChanged` status from __READY__ to __STARTING__

**Comment by voievodin** [comment]
Runtime ID format updated from 
```json
{
      "workspace": "workspace123",
      "environment": "default",
      "owner": "user123"
}
```
to
```json
{
      "workspaceId": "workspace123",
      "envName": "default",
      "owner": "user123"
}
```
