### ISSUE TITLE
 Rework docker runtime infrastructure to use bootstrapper events during workspace start

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4101]
Events specification is [here](https://github.com/eclipse/che/issues/4096#issuecomment-283067971)(section _Bootstrapper events_).

Rework docker infrastructure to use bootstrapper to start agents.
The golang bootstrapper is merged under https://github.com/eclipse/che/pull/5399.

**Comment by voievodin** [comment]
Depends on #5266

**Comment by voievodin** [comment]
@sleshchenko 
As bootstrapper is already part of the SPI branch the goal is changed a bit, there is no need to make synthetic implementation while the real bootstrapper can be used instead, i updated issue description.
Also i created a separate [issue](https://github.com/eclipse/che/issues/5413) for removing unused launchers and agents-related functionality.
