### ISSUE TITLE
[cli] Add check to avoid :/data and :/assembly being identical

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#4103]
I have cloned and compiled che. When I start it

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/che:/data eclipse/che-cli start --debug`

it throws an error 
```
WARN: Bound 'eclipse/che-cli' to 'eclipse/che-cli:5.2.2'
WARNING: No swap limit support
INFO: (che cli): :/repo mounted - using assembly and manifests from your local repository
/scripts/base/startup_funcs.sh: line 468: /repo/dockerfiles/cli/scripts/cli.sh: No such file or directory
```
it used to work in the earlier versions (about a month ago).

**Comment by TylerJewell** [comment]
This is a version mismatch.  It takes a long time to explain why but we have refactored the cli and the scripts in the repo are not compatible with the cli image you are using.   There is a workaround but will have to write it in a bit for you.

**Comment by TylerJewell** [comment]
We changed some things in the CLI with a refactoring, and this means that the `:/repo` mode will cause you to have inconsistencies between the image you are using and the script files in the version that have cloned.

1. You should use `:/assembly` as a mount to only have it use your binaries.  When you use :/repo, it uses all sorts of other stuff in the repository, including trying to replace the script files in your image with those from the repository. 

2. If you really need :/repo mode then build the nightly.  This will update your local image to work with the scripts that are in the repository.
a: build /dockerfiles/base
b: build /dockerfiles/cli
c; then run with `docker run .... <repo>:/repo eclipse/che-cli:nightly --skip:nightly`

**Comment by aleksei-burlakov** [comment]
I tryed `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/assembly -v ~/che:/data eclipse/che-cli start --debug` but no server was started. It only returned 
```
WARN: Bound 'eclipse/che-cli' to 'eclipse/che-cli:5.2.2'
WARNING: No swap limit support
WARN: Debugging activated without ':/repo' mount - using binaries inside Docker image
INFO: (che cli): :/assembly mounted - using assembly from local host
INFO: (che cli): 5.2.2 - using docker 1.13.1 / native
INFO: (che config): Generating che configuration...
Notice: Compiled catalog for 51cd872e5684.emea.global.corp.sap in environment production in 0.28 seconds
Notice: Applied catalog in 0.07 seconds
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che config): Copying local binaries to /home/che/che/instance/dev...
cp: cannot copy a directory, '/assembly/.', into itself, '/data/instance/dev/che-tomcat/.'
```

**Comment by TylerJewell** [comment]
You cannot have your `:/data` mount be identical to the `:/assembly` mount.

**Comment by aleksei-burlakov** [comment]
Thank you.

**Comment by TylerJewell** [comment]
Reopening, and using this error condition as a reason to add another check in the CLI to detect this condition and prevent it.

**Comment by ghost** [comment]
@TylerJewell I think you have implemented this in the CLI. Can I close the issue now?

**Comment by TylerJewell** [comment]
No it is still actual.   This particular test was not yet added.
