### ISSUE TITLE
Recover workspace runtimes on workspace master start

### ISSUE THREAD

**Issue by voievodin** [eclipse-che/che#4106]
Workspace runtimes(running environments) must be recovered from running containers on workspace master start. 

Proposed solution is:
- Extend `CheEnvironmentEngine` with a new method(e.g. `recover`) 
this method would lookup(#4105) through the running machine instances provided by `MachineProvider` and link environment configuration with data provided by running instances, saving consistently running environments.
- Recovery endpoint class `WorkspaceRuntimes` on boot triggers `CheEnvironmentEngine` recovery and collects recovered environments data into its own internal state. After boot of `WorkpspaceRuntimes` is finished workspace runtimes are recovered.
- After `WorkspaceRuntimes` boots `WorkspaceManager` is free to make any necessary cleanups
  - cleanup temporary workspace which are not running, so `TemporaryWorkspaceRemover` should be reworked to be a part of `WorkspaceManager` boot,
- `DockerAbandonedResourcesCleaner` should be reworked to respect recovery and not clean unlinked containers and networks on components start

Investigated by #3910 
Depends on #4105

**Comment by garagatyi** [comment]
Closing since it is implemented in SPI branch
