### ISSUE TITLE
Web page crashes when choosing stack types

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4107]
**Reproduction Steps:**

* In Dashboard start creating a new workspace;
* In **"Select workspace"** select **"Create new workspace from stack"** radiobutton;
* Click on **"Stack import"** and then on any of other option (**"Ready-to-go Stacks"**, **" Stack library"**, "**Stack authoring"**);

**Expected behavior:**
* Stack settings should be appear.

**Observed behavior:**
* The web page crashes.

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version**: 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/22830680/17eb77ac-efb0-11e6-94ff-da6a034c75e1.gif)

**Comment by riuvshin** [comment]
good catch @SkorikSergey !
@ashumilova please take a look at this one

**Comment by riuvshin** [comment]
@ashumilova this may be blocker for 5.3.0 release please assign someone to this

**Comment by SkorikSergey** [comment]
This bug is reproduced in 5.12.0 version. Step to reproduce are similar except  need click on the **Stack authoring** tab first in step 3(3. Click on **Stack authoring** tab and then on any of other option (**Ready-to-go Stacks**, **Stack library**);).
