### ISSUE TITLE
Terminal Copy/Paste with Ubuntu Firefox

### ISSUE THREAD

**Issue by jgroom33** [eclipse-che/che#4109]
Copy Paste does not function (ctrl-c or ctrl-v)  
Context menu does not appear on right click
Edit menu shows no option for copy or paste

OS: Ubuntu 16.04.1
Browser: Firefox 47.0
Che Server: 5.2.2

**Comment by TylerJewell** [comment]
Hi Jeff - yes this is a known issue. This will (thankfully) be resolved with the replacement of our term.js with xterm.js, which is a much more stable and richer platform.

https://github.com/eclipse/che/pull/3943

The PR should be merged this sprint. We are just finishing up some bugs and resolving some regressions on edge cases.  It should appear in Che 5.3.

**Comment by ghost** [comment]
@TylerJewell @jgroom33 Ctrl+Insert and Shift+Insert work for me both in FF and Chrome. Closing the issue.
