### ISSUE TITLE
[Question] Is it possible to Repackage Che as a Desktop IDE?

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#4113]
I have been trying out Che in Codenvy for a while and I fell in love on many aspects that the Eclipse Platform lacks. Most Notably the UI because it's clean to look at and reduces cognitive load when I code and I'm liking the Intellisense it provides (it just lacks the Quick Suggestions I need for Node.js and Proper ESLint support).

If it's possible, is there a way to compile Che without requiring to edit most of the codebase?

**Comment by TylerJewell** [comment]
We are working on an Electron client for Che and custom assemblies now.  It's quite a complicated project and includes:
1. OS-specific installers
2. A native electron client (very fast)
3. Bundled Docker installation + configuration
4. Running the Che server as an always-on docker container
5. Desktop icon with custom lifecycle of managing the che server
6. Configuring Docker proxies and other startup details in the electron client

I think we'll have something testable before the end of this quarter.  You can do searches for electron client in the issue archive.

Thank yo ufor being a fan of the project!

**Comment by ghost** [comment]
@sr229 do you have any further questions or comments? If not, you may close the issue.

**Comment by sr229** [comment]
I think I got none already. Closing.
