### ISSUE TITLE
Cannot successfully create project in workspace via REST API

### ISSUE THREAD

**Issue by sbryzak** [eclipse-che/che#4117]
It doesn't seem to be possible to create a new project using the REST API, using the latest trunk of Che.

**Reproduction Steps:**

1. Browse to the Swagger UI for the Che installation (http://localhost:8080/swagger/#/ if running locally).

2. Create a new workspace - expand the "workspace" heading, then expand [POST] /workspace and enter the following as the body then click the "Try it out!" button:

{
  "environments": {
    "default": {
      "machines": {
        "dev-machine": {
          "servers": {},
          "agents": [
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh"
          ],
          "attributes": {
            "memoryLimitBytes": "2147483648"
          }
        }
      },
      "recipe": {
        "location": "eclipse/ubuntu_jdk8",
        "type": "dockerimage"
      }
    }
  },
  "defaultEnv": "default",
  "name": "test",
  "description": null,
  "commands": [],
  "projects": [],
  "links": []
}

3. Find the workspace ID in the Response Body, and copy it to the clipboard. It should be close to the top of the response:

{
  "attributes": {
    "created": "1486958966689"
  },
  "namespace": "che",
  "temporary": false,
  "id": "**workspacega10o3ag1fxahz1c**",
  "status": "STOPPED",
  ...

4. Expand [POST] /workspace/{id}/runtime (Start the workspace by the id) and paste the workspace ID into the **id** parameter, then click "Try it out!". It should return a 200 Response Code.

5. Expand [GET] /workspace/{id}/check (Get state of the workspace agent by the workspace id) and paste the workspace ID into the **id** parameter, then click "Try it out!".  If the workspace is still starting up it should have a "workspaceStatus" value of "STARTING" in the Response Body.  Click "Try it out!" every couple of seconds until you have a workspace status of "RUNNING".

6. Expand [POST] /workspace/{id}/project (Adds a new project to the workspace) and once again paste the workspace ID into the **id** parameter value, and set the value of the **body** parameter to the following, then click "Try it out!".  The response code should be 200:

{
  "name": "eclipse-che",
  "type": "maven",
  "description": "Eclipse Che",
  "path": "/eclipse-che",
  "source": {
    "parameters": {
      "branch": "master",
      "keepVcs": "true"    
    },
    "type": "git",
    "location": "https://github.com/eclipse/che.git"
  },
  "attributes": {},
  "links": [ { } ],
  "mixins": [
    "git"
  ]
}

7. Open the Che dashboard in another browser window.

8. Browse to Workspaces -> click on the "che/test" workspace then click on the "Projects" link at the top.  The "eclipse-che" project should be listed.

9. Open the "test" workspace by clicking the link in the left sidebar.

10. The IDE should open, however instead of seeing the "eclipse-che" project in the Project Explorer as expected it simply states "There are no projects".

**Comment by sbryzak** [comment]
I've also tried various other combinations (attempting to create workspace and projects all in one call) and tweaking the values of the request bodies, neither of which had any success.  I would expect when the workspace is opened the project would be there and contain the source code specified by the Git repo and branch in the create project request.

**Comment by ghost** [comment]
@sbryzak you may want to take a look at https://github.com/eclipse/che/issues/4082

In a few words, you need to import a project and to do so you need a running workspace agent (project service is deployed with a workspace agent)

**Comment by ghost** [comment]
@JamesDrummond @slemeur this is a popular question. We should have it documented.

**Comment by sbryzak** [comment]
@eivantsov Thanks for the response, I've read through issue #4082 and I agree, this needs to be documented better.  Without having to go through the Che dashboard, is there a way to determine the wsagent runtime URL via the REST API, after a workspace has been started? If it's via /workspace/{workspaceId}/machine then what parameters should be used to query the result? (I.e. is "dev-machine" a safe enough value to query the name of the workspace machine, or is there a better way?)

**Comment by vinokurig** [comment]
@sbryzak To determine the wsagent runtime URL:
[GET] {che url}/api/workspace/{workspaceId}
The workspace API url will be in the received Json response:
runtime -> devMachine -> runtime -> servers -> 4401/tcp

**Comment by sbryzak** [comment]
@vinokurig What is the URL to use to create a project against the workspace API?  I've tried many different combinations, none of which worked.

**Comment by vinokurig** [comment]
@sbryzak You should make a POST requrest to {ws agent api url}/project/batch with Json data:
```
[
  {
    "name": "ProjectName",
    "attributes": {},
    "type": "blank",
    "source": {
      "location": "",
      "type": "",
      "parameters": {}
    },
    "path": "/path",
    "options": {},
    "description": null,
    "mixins": [],
    "problems": [],
    "links": []
  }
]
```

**Comment by sbryzak** [comment]
@vinokurig Thankyou, that worked successfully.  Is this something that can be improved in the documentation? Perhaps here? http://www.eclipse.org/che/docs/workspace/agents/index.html

**Comment by ghost** [comment]
@sbryzak why agents?
