### ISSUE TITLE
The "Projects" info page does not refresh after deleting a project.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4120]
**Reproduction Steps:**
1. **"Workspaces"** -> **"Configure workspace"** -> select tab **"Projects"**.
2. Create any project.
3. Select the project and click "Delete" button .
4. Confirm deleting.

**Expected behavior:**
The project is removed and not visible in the "Projects" tab.

**Observed behavior:**
The project is removed but the projects list  isn't refreshed. The deleted project name is still visible.

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![project_refresh](https://cloud.githubusercontent.com/assets/7760565/22877426/06165544-f1de-11e6-81b6-19158c2b1e19.gif)

**Comment by riuvshin** [comment]
@ashumilova please take a look I think we can do this for 5.3.0
