### ISSUE TITLE
After deleting a project from a workspace webpage chrashes

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4121]
**Reproduction Steps:**
1. **"Workspaces"** -> **"Configure workspace"** -> select tab **"Projects"**.
2. Create any project.
3. Click on the project name. Click **"Delete"** project button.
4. Confirm deleting.

**Expected behavior:**
The project is deleted and the **"Projects"** tab is visible.

**Observed behavior:**
The workspace settings is opened with workspace name which is not exists("projects"). After clicking on **"Workspaces"** the web page crash.

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![delete_project_crash_page](https://cloud.githubusercontent.com/assets/7760565/22877915/49608700-f1e0-11e6-8564-0f9d74878c28.gif)

**Comment by riuvshin** [comment]
@ashumilova please take a look this may be blocker for 5.3.0
