### ISSUE TITLE
Add custom language server but workspace agent not found

### ISSUE THREAD

**Issue by tsjfd** [eclipse-che/che#4124]
I try to integrate my own DSL in Eclipse Che. I have started by following the tutorial @ https://blogs.itemis.com/en/how-to-get-started-with-xtext-language-servers-and-che. The tutorial is based on Che 5.1.2 and everything works in non-proxy environments, but I can't use it because I am behind a corporate proxy and proxy propagation for workspaces is not working in 5.1.2. Now I try to port the tutorial to 5.2.2. I can compile che with my custom DSL and could start the server (docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/repo -v ~/data:/data [proxy settings] eclipse/che:5.2.2 start --debug) but as soon as I create a workspace from a stack containing my dsl I get an error message saying

Workspace 'che:wksp-b0eb' can't be started because: Agent org.eclipse.che.ls.mydsl not found"

Does anyone has an idea on how to track down this error? BTW everything works without my dsl plugin / agent, so I guess I have missed one config file...

**OS and version:** Ubuntu 16.04, Eclipse Che 5.2.2

**Comment by vinokurig** [comment]
@tsjfd From 5.2 version we changed the mechanism of adding language servers. The tutorial says to add the language server to [agents](https://github.com/eclipse/che/tree/master/agents) folder, but now it is needed to create a new submodule. Please follow https://codenvy.io/docs/getting-started/agents/index.html#adding-agents for more information

**Comment by tsjfd** [comment]
@vinokurig Thx, I missed the binding in WsMasterModule
