### ISSUE TITLE
Make it possible to provide envs for workspaces

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4126]
Right now, such feature is available only for workspaces created with compose files (in User Dashboard). It should be possible to provide envs for all workspaces.

A user may need to add envs without having to modify a Dockerfile.

These envs should be added to machine config and then passed to Docker when container is run.

**Comment by JonathanSpooner** [comment]
It is possible to set a machine's environment variables through the UI during workspace or stack creation by expanding the DEV-MACHINE node.

**Comment by ghost** [comment]
No, this feature has not been implemented yet.

**Comment by JonathanSpooner** [comment]
Here's a screenshot of the UI showing the "Add a new environment variable" UI. To access this feature you need to expand the DEV-MACHINE node during workspace or stack creation. (Running the latest version of eclipse/che locally)

![screenshot from 2017-03-22 23 46 09](https://cloud.githubusercontent.com/assets/4843444/24231309/3bb8d868-0f5a-11e7-8fd2-ef51c90f2dee.png)

**Comment by ghost** [comment]
My bad. The issue hasn't been assigned and no milestone has been set. Thanks. Closing the issue
