### ISSUE TITLE
Midnight Commander clears the terminal output

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4127]
**Reproduction Steps:**
1. Start any project.
2. Run a new terminal and do some commands.
3. Start Midnight Commander.
4. Press Ctr+O to hide MC.

**Expected behavior:**
History of the terminal output from the commands should be visible.

**Observed behavior:**
The terminal output is blank except command prompt.

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![mc_clear_console_history](https://cloud.githubusercontent.com/assets/7760565/22885599/be223526-f202-11e6-83b8-b9aac2bc07e9.gif)

**Comment by riuvshin** [comment]
@vparfonov please take this in some next sprint

**Comment by SkorikSergey** [comment]
This bug is not reproduced in Che version: 5.4.0-SNAPSHOT.
