### ISSUE TITLE
The web page crashes during configuration workspaces settings.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4136]
**Reproduction Steps:**
**"Workspaces"** -> In **"Action"** click **"Configure workspace"**.

**Expected behavior:**
The workspace configuration page should appears. 

**Observed behavior:**
The configuration page of not existing workspace appears("projects" ). The web pages crashes.
Similar crashing is in #4121  issue. 

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version**: 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![workspace configuration](https://cloud.githubusercontent.com/assets/7760565/22935882/89cb3a5e-f2dc-11e6-8b41-9ba145224458.gif)
![selection_001](https://cloud.githubusercontent.com/assets/7760565/22936121/35b20bcc-f2dd-11e6-85d2-b1d49a91e605.png)

**Comment by riuvshin** [comment]
@olexii4 please check this usecase with your fixes also
