### ISSUE TITLE
The Format feature does not respect tab spaces set in Preferences

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4138]
**Steps to reproduce:**
**Preconditions:** create the Spring project. Open the GreetingController class.

**Reproduction Steps:**
1. Profile ->Preferences ->Editor->Tab Size: -> set 2.
2. Edit -> format
**Expected result** new settings for the current code should be applied. 
**Actual result** the format is not changed
**OS and version:**    Chrome browser, Ubuntu 14 TLS.

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by ghost** [comment]
Can be reproduced in 5.15-SNAPSHOT. Question: should formatter pick up settings from user prefs anyway? They seem to be applied only for new code that is written in the editor.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
