### ISSUE TITLE
Sever-Client communicaton - Dto usage sample and documentation

### ISSUE THREAD

**Issue by elpddev** [eclipse-che/che#4139]
My use case is sending a completion proposal for instance that composed of several data fields. Looking at the Java plugin project, I see the sending over the server and client is done via Dto for serialization of that info instance. 

One way for me currently to implement this is to reverse engineer the Java plugin project. I see that for instance there is a need to create a build step in the shared project to create the Dto artifacts. 

Is there a guide for implementing a Dto support for a plugin project ?

**Comment by TylerJewell** [comment]
@vinokurig - FYI, question on DTO.
@elpddev - We haven't published a document on DTO, but it's a question that comes up from time to time.  I hope that an engineer will provide a couple examples of the process for creating and using DTO.

**Comment by skabashnyuk** [comment]
https://www.eclipse.org/che/docs/dto.html
