### ISSUE TITLE
Use Persistent Volumes Claims when creating workspaces

### ISSUE THREAD

**Issue by snjeza** [eclipse-che/che#4141]
Usage of hostPath volumes is not supported on multi-node OpenShift clusters. We should use PersistentVolumeClaims instead.

This issue is to change OpenShiftConnector::createContainer to use PersistentVolumeClaims.

See https://issues.jboss.org/browse/CHE-60

**OS and version:**    any

**Comment by skabashnyuk** [comment]
won't fix. out of date.
