### ISSUE TITLE
Debug session still active for NodeJs project after end of debugging

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4144]
**Reproduction Steps:** 
* Debug NodeJs project .
* Click on End of Debug button.
* Try to debug the project again

**Expected result:** All debug features should be available

**Actual result:** Debugger is not available

**OS and version:**    Ubuntu 14.0 TLS, Chrome browser.

**Additional information:** I think it happens because after end of debug session, data about debug session in browser storage are  not cleaned.

**Comment by riuvshin** [comment]
@tolusha please take a look on this

**Comment by tolusha** [comment]
Confirm.
Seems a bug

**Comment by tolusha** [comment]
Related to
https://github.com/nodejs/node-v0.x-archive/issues/25358
