### ISSUE TITLE
There are two ways to create a javascript file.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4145]
**Reproduction Steps:**

1. Open any project in the IDE.
2. Open the menu for creating a new file.

**Expected behavior:**
    There is one possibility for creating a javascript file.

**Observed behavior:**
    There are two items for creating a javascript file - "New JavaScript File" and "JavaScript File".

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![two_items_for_javascript_file](https://cloud.githubusercontent.com/assets/7760565/22978227/865b00d4-f39a-11e6-96f4-f0c1c2836221.gif)

**Comment by slemeur** [comment]
@ashumilova @vzhukovskii : I think this is a quick fix ;)
