### ISSUE TITLE
Network Diagnostic Tool Investigation

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4146]
Investigate diagnostic tool that will test network to tell user problems that could prevent workspace from starting.

**Comment by JamesDrummond** [comment]
@TylerJewell Can you add what you would like the diagnostic tool to accomplish for @vparfonov in the description above so he can start his investigation next sprint?

**Comment by TylerJewell** [comment]
This issue is already being worked on by Florent for the past week.  Where did this come from?

**Comment by benoitf** [comment]
https://github.com/eclipse/che/issues/3748
