### ISSUE TITLE
The information window without expected error information 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4147]
After trying to create the package with wrong name , the information window without expected error information was shown
 

**Reproduction Steps:**
1) Create some Java project
2) Expand project tree and cause context menu on the Java folder
3) Click on "New" -> "Java Package"
4) Type invalid package name :
            "...thisIsWrong"
            "This IS WROng"
            "This-IS-WROng"
            "123test"

5)Click on "Ok" button           
6)Pay attention to the displayed information window .

**Expected behavior:**

The information window contain information about error .

**Actual result :**

The information window was shown without error information .

**OS and version:**    
Ubuntu 16.04
Che version: 5.3.0-SNAPSHOT
Docker version: 1.13.1
Che install: Docker container

**Additional information:** 

- See the attachment :

![eclipse che wksp ypgp](https://cloud.githubusercontent.com/assets/22724619/22982514/162581fa-f3a8-11e6-9db8-31c1f24646ed.png)

**Comment by TylerJewell** [comment]
@Ohrimenko1988 - issue confirmed.  thanks for reporting it

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by vzhukovs** [comment]
Closed, because issue can not be reproduced
