### ISSUE TITLE
The "Delete" widget appears when working with the Terminal.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4150]
**Reproduction Steps:**
1. Open any project in the IDE.
2. In the **"Project Explorer"** set selection on any file or folder.
3. In the **"Terminal"** press "Delete" button.

**Expected behavior:**
Current symbol should be deleted.

**Observed behavior:**
The dialog widget appears with proposition to delete the selected file or folder in **"Project Explorer"**.
Similar issue https://github.com/eclipse/che/issues/4059.

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![delete_items_from_terminal](https://cloud.githubusercontent.com/assets/7760565/23015246/bb5c8834-f43a-11e6-8ddb-5047aed00857.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by musienko-maxim** [comment]
I think it is duplicated with this: https://github.com/eclipse/che/issues/4059
It happens because selection still remains on previous item in the Project explorer tree.  I think we can close the issue as duplicated.

**Comment by AndrienkoAleksandr** [comment]
Seems it's bug xterm.js. xterm.js should prevent another action.

**Comment by musienko-maxim** [comment]
Still actual
