### ISSUE TITLE
Workspace container RAM requirements

### ISSUE THREAD

**Issue by ariel-bentu** [eclipse-che/che#4151]
Hi,
I'm looking for ways to reduce (dramatically) the size of each workspace RAM consumption. Based on your docs, it should be minimally 256MB - I assume you refer to set JAVA -Xmx256m no less.
- If you measure RSS (Resident Set Size) on the Linux level, it usually is more (by far - see for example here: http://trustmeiamadeveloper.com/2016/03/18/where-is-my-memory-java/)

- In reality the out-of-the-box installation uses -Xmx2048:
  - memory actually used, after just creating a new workspace is close to 1GB RSS
  - how can I change the -Xmx settings?
- Is there a way to use Jetty:alpine instead of tomcat for the workspace agent? my simple measurements show 100MB less on RSS for an "empty" jetty vs. "empty" tomcat

Thanks,
Ariel
**Reproduction Steps:**

**OS and version:**  
Docker, Che 5 - latest  

**Diagnostics:**

**Comment by ghost** [comment]
@ariel-bentu you may decrease xmx in your che.env: `CHE_WORKSPACE_JAVA_OPTIONS`

As to using another server, it should be theoretically possible of course, but I assume it will involve some work to do.

**Comment by jjHimmelreich** [comment]
@eivantsov - I just tried to add `CHE_WORKSPACE_JAVA_OPTIONS=-Xms256m -Xmx512m` to /data/che.env file binded form host but it is not reflected in the `instance/data/conf/che.properties` file. 
On server docker contained startup, custom options are always overwritten by hardcoded defaults `-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom`.

Can you please point me to any documentation?

**Comment by ghost** [comment]
@eHimmelreich have you restarted Che after modifying .env file?

Docs are here http://www.eclipse.org/che/docs/

I have just edited my che.env:

![image](https://cloud.githubusercontent.com/assets/5337267/23021414/83884d66-f454-11e6-9f11-dd75984a1aea.png)

**Comment by jjHimmelreich** [comment]
Of course I did :)

Reproduction steps:
1. docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v **/tmp/che/data**:/data eclipse/che **stop**
2. Observe che.workspace.java_opts value in **/tmp/che/data**/instance/data/conf/che.properties file (or even delete it)
3. add `CHE_WORKSPACE_JAVA_OPTIONS=-Xms256m -Xmx512m` to `/tmp/che/data/che.env` file on host machine
3. docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v **/tmp/che/data**:/data eclipse/che **start**
4. observe default values in **/tmp/che/data**/instance/data/conf/che.properties file

**Comment by ghost** [comment]
`restart` not `start`

**Comment by ghost** [comment]
Sorry, haven't seen stop command.

Well, this is all I did - changing env file and restarting.

Can you actually check if ws agent has started with your custom options? The way I did?

I think that che.properties is ignored.

**Comment by TylerJewell** [comment]
@eivantsov - I think he would need the nightly version.  The default image he ran is 5.2.2 and that did not have the new OPTIONS config.

**Comment by ghost** [comment]
I used nightly, and in my properties file there were old values, although ws-agent used the ones I had provided in che.env

**Comment by jjHimmelreich** [comment]
I'm on 5.2.2. 
Tried one more time. ws agent starts with -Xmx2048m

**Comment by TylerJewell** [comment]
@eHimmelreich - wipe out your existing Docker images and then use `eclipse/che:nightly` image.  This version will support that che.env additional option Eugene mentions.

**Comment by jjHimmelreich** [comment]
Upgraded to nightly. Can confirm that it is working now. Thank you.
Is it also any option to control container MavenServer JVM settings?

**Comment by TylerJewell** [comment]
Yes - that was added as well.  Replace JAVA with MAVEN and you can override the defaults.
