### ISSUE TITLE
Xmx value for ws-agent's JAVA_OPTS must not exceed total machine RAM

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#4152]
I think part of machine crashes occur because Xmx for ws-agent is set to 2048M while machine run with limit of 1GB RAM.
This prevent garbage collector to be fired so linux kernel imposes RAM limit and terminates ws-agent with OutOfMemory error.

We need either dynamically set Xmx to something about no more than 70% of machine's RAM limit or disable starting machine with RAM limit less than 2.5GB if ws-agent is present in machine.

**Comment by TylerJewell** [comment]
@skabashnyuk - this seems like a very good thing for us to set / control with Che.  And perhaps it is not that difficult to add either.  Will you consider analyzing this in either the next or next.next sprint?

**Comment by skabashnyuk** [comment]
I think it make sense to do this task after we figure out how to not install maven toolchain in all stacks no matter if they are related to maven or not.

**Comment by musienko-maxim** [comment]
Some BitNami factories use 1GB RAM

**Comment by TylerJewell** [comment]
@skabashnyuk - can you connect for me the relationship between Maven and the memory on the JVM for ws-agent?  I don't see the technology connection.

**Comment by skabashnyuk** [comment]
now
1. MAVEN_OPTS=JAVA_OPTS
2. Maven server is part of ws-agent aka part of all stacks
So we have two JVM running with same xmx.
If we start maven command we will have 3 or more.

**Comment by TylerJewell** [comment]
Ok -that is clear, thanks.

**Comment by ghost** [comment]
@skabashnyuk will we move forward with this one?

**Comment by gorkem** [comment]
Useful reading on this https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/

**Comment by skabashnyuk** [comment]
fixed by https://github.com/eclipse/che/issues/7726
