### ISSUE TITLE
Exposed Ports not Displayed in Runtime Interface or Commands

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4163]
Not all exposed ports are displaying in runtime interface an workspace commands. Below are tests on mysql ready-to-go workspace.

**Reproduction Steps:**

-----

1. Create\Start new java mysql ready-to-go workspace
1. Open runtime interface in dashboard
1. Expand db or dev-machine 
1. Check the server section for ports
1. Ports 22 4403 and 3306 are missing.

db machine:
<img width="687" alt="port-issue1" src="https://cloud.githubusercontent.com/assets/20580888/23035189/eac3f090-f443-11e6-99db-a365993f9efa.png">

dev-machine:
<img width="703" alt="port-issue2" src="https://cloud.githubusercontent.com/assets/20580888/23035140/ca67233a-f443-11e6-8a6e-934fb4357ab0.png">

------

1. Create command in workspace for dev-machine `echo "server.port.4401:${server.port.4401} server.port.4403:${server.port.4403} server.port.4411:${server.port.4411} server.port.9876:${server.port.9876} server.port.22:${server.port.22} server.port.8080:${server.port.8080} server.port.8000:${server.port.8000}"`
1. Output is `server.port.4401:nightly.codenvy*.com server.port.4403:node1.nightly.codenvy*.com:55339 server.port.4411:nightly.codenvy*.com server.port.9876:node1.nightly.codenvy*.com:55335 server.port.22:node1.nightly.codenvy*.com:55341 server.port.8080:node1.nightly.codenvy*.com:55336 server.port.8000:node1.nightly.codenvy*.com:55337`
1. Ports 4401 and 4411 are seem incorrect by not including `/<port>_node1.nightly.codenvy*.com/api` at end. Not sure that these ports would be used via commands by the user however.

-------

1. Create command in workspace for db machine echo `"server.port.3306:${server.port.3306} server.port.4411:nightly.codenvy*.com"`
1. Output is`/bin/bash: server.port.3306:${server.port.3306} server.port.4411:nightly.codenvy*.com: bad substitution`

**OS and version:**    
Nightly staging 4.3.0 snapshot.

**Comment by ghost** [comment]
Checked with the latest tag. Cannot reproduce.
