### ISSUE TITLE
After refresh IDE cursor is not in place where it was before refresh

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4167]
**Reproduction Steps:**
1. Create default workspace : "Dashboard" -> "Create Workspace" -> "Create new workspace from stack" 
    ->  "Java stack" -> scroll down and choose "web-java-spring" ->  click "Create" button.

2. In "Project Explorer" expand project tree and click twice on "GreetingControler.java" .

3. In editor click right button on the "GreetingController" tab  , and choose "Split pane in two rows" ,          
    repeat previous actions but choose "Split pane in two columns". 

4. Click once on the right-up tab  -> in project explorer choose and open Readme.md .

5. Click once on the down tab -> in project explorer choose and open pom.xml  .

6. In the left-up tab put cursor on 16 row an first place , in the right-up tab put cursor on the 27 row ,
    in the down tab put cursor on the 35 row .

7. Click refresh button . Pay attention on the cursor in the tabs .

**Expected Behavior**
* After refresh cursor will be in the place where it was before refresh .

**Actual Behavior**
* After refresh cursor change its position.

**OS and version:**    
Ubuntu 16.04
Docker 1.13.1
Eclipse Che 5.3.0-SNAPSHOT

**Additional information**
See the attachment :

![eclipse che wksp io5p](https://cloud.githubusercontent.com/assets/22724619/23063417/22f7a0cc-f513-11e6-9f43-eb5e8eb35632.png)

**Comment by riuvshin** [comment]
@vparfonov is that a bug?

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by vparfonov** [comment]
can't reproduce

**Comment by Ohrimenko1988** [comment]
We have CheckRestoringOfSplitEditorTest that also checks the place of the cursor after refresh, and after refresh the page cursor is placed not in the previous place. So this is definitely a bug.
