### ISSUE TITLE
After returning from the project settings webpage crashes.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4170]
**Reproduction Steps:**
1. **"Workspaces"** -> **"Configure workspace"** -> select tab "Projects".
2. Create any project.
3. Click on the project name. Click "All workspaces" on top left corner of the "Project settings" page.

**Expected behavior:**
The **"Projects"** tab of the workspace is visible.

Observed behavior:
A workspace settings is opened with  a workspace name which is not exist("projects"). After clicking on "Workspaces" the web page crashes.

**Similar bugs:**
https://github.com/eclipse/che/issues/4121 
https://github.com/eclipse/che/issues/4136 

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![when exiting from project settings](https://cloud.githubusercontent.com/assets/7760565/23064459/e249dd50-f518-11e6-993d-ebd8daec9e06.gif)

**Comment by riuvshin** [comment]
@ashumilova @olexii4 another tab crash on UD

**Comment by riuvshin** [comment]
@SkorikSergey is this still actual?

**Comment by SkorikSergey** [comment]
Yes.

**Comment by riuvshin** [comment]
@ashumilova please include this in next sprint

**Comment by SkorikSergey** [comment]
The bug is fixed.
