### ISSUE TITLE
The configuration text from the Workspace config disappeares after pressing Ctr+Z.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4174]
**Reproduction Steps:**

1. **"Workspaces"** -> "**Configure workspace"** -> select tab **"Workspace Config"**.
2. Click on the "Workspace config" text.
3. Press Ctrl+Z.

**Expected behavior:**
Nothing happened.

**Observed behavior:**
The configuration text disappeared.
Ctrl+Shift+Z returns the config text.
On screenshots below are two similar examples.

**Che version:** 5.3.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

Additional information:
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![error with workspace config](https://cloud.githubusercontent.com/assets/7760565/23071591/930f10c4-f537-11e6-9202-6330f497e299.gif)

![screenshot from 2017-02-17 17-48-34](https://cloud.githubusercontent.com/assets/7760565/23072186/7eb642f8-f539-11e6-9346-f84148917fba.png)

![screenshot from 2017-02-17 17-49-14](https://cloud.githubusercontent.com/assets/7760565/23072215/a2aba130-f539-11e6-8b75-42efa0f21aeb.png)

**Comment by SkorikSergey** [comment]
The same bug is in **"Factory"** ->**"Configuration"**(JSON definition of the factory.).
![10](https://cloud.githubusercontent.com/assets/7760565/23097260/136fe580-f638-11e6-9a8c-822690522994.jpg)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
Fixed by https://github.com/eclipse/che/pull/12410.
