### ISSUE TITLE
Unable to start Eclipse Che on Raspberry Pi 2

### ISSUE THREAD

**Issue by Muirrum** [eclipse-che/che#4177]
Docker returns "docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exec format error"." when running Eclipse Che.

**Reproduction Steps:**
 - Run the command "sudo docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che-cli:nightly start"

**OS and version:**    
Raspbian Jessie
**Diagnostics:** 
Info command returns same error.

**Comment by TylerJewell** [comment]
http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/#going-wild-with-docker-what-can-you-actually-do-with-it:397c66ef19f9f061b6711d2e296cb276

You need to make sure that Docker & the images you grab are configured for ARM architectures. There are users in the old threads for Che (see closed issues on Raspberry Pi) that discuss what they must do to make it work.

**Comment by ghost** [comment]
@Dev-Osmium @TylerJewell it will be quite a challenging task since all images that CLI uses must be rebuilt to be ARM7 compliant.

Perhaps, if we revert the commit that bans Che from being started natively, it would be a simpler option for IOT users. In this case, only stack images have to be rebuilt.

**Comment by TylerJewell** [comment]
One of the things that is in the current version of the CLI is that the `config` method is now generating a native script for starting / stopping Che.  It has some issues that @skabashnyuk team is asked to resolve.  But the idea is to generate a native-script that is tailored to the unique configuration of the `che.env`. This may not solve the particular issue as this would require the bootstrap and base CLI images to rebuilt with ARM architectures. But, these images are largely under our control, so maybe it's not as big of an inconvenience?

**Comment by ghost** [comment]
@TylerJewell should we keep this issue opened?

**Comment by TylerJewell** [comment]
It's a legitimate issue - should remain open.

**Comment by ghost** [comment]
@TylerJewell should it be still a question? If so, @Dev-Osmium can you share your findings? Have you tried to rebuild cli images to be ARm7 compatible?

If not, I'd label it as an enhancement and maybe it is a good project to complete in a spare time - dockerized Che on Raspberry Pi.
