### ISSUE TITLE
After starting PlayForJavf

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4180]
**Reproduction Steps:** Create workspace form Bitnami Play for java stack. Run ```java-play: 1. Create and run project``` command.
![com codenvy ide dashboard stacks checkplayforjavastacktest checkplayforjavastack_cdwindow-2f1744d4-4d64-43ae-a09f-9dd4a86f0834](https://cloud.githubusercontent.com/assets/1640058/23120340/9fa23f6c-f764-11e6-896a-bd110b7e0b09.png)

**OS and version:**   Ubuntu 14 TLS, Chrome browser

**Comment by slemeur** [comment]
This issue is missing description. I'm closing it.
@musienko-maxim : feel free to update title and description to clarify and re-open it.
