### ISSUE TITLE
Developping plugins for eclipse che

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4183]
Hi, i'm trying too follow the tutorial DEVELOPER GUIDE - IDE PLUGINS that i find it on Eclipse Che website, i have a problem when i try to achieve the second step IDE Setup but when i run superdevmode i have this ERROR:
Super Dev Mode starting up
workDir: /tmp/gwt-codeserver-1827730222579086586.tmp
Job org.eclipse.che.ide.IDE_1_0
Loading inherited module 'org.eclipse.che.ide.IDE\'
[ERROR] Unable to find 'org/eclipse/che/ide/IDE.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

Link for the second step "IDE Setup" : https://www.eclipse.org/che/docs/plugins/setup-che-workspace/index.html

**Comment by ghost** [comment]
@ahmedchemek have you previously compiled Che? What OS and IDE do you use?

**Comment by ahmedchemek** [comment]
Yes i have compile Che
OS : ubuntu 16:04
IDE : Eclipse Neon.2 Release (4.6.2)

**Comment by bmicklea** [comment]
@jonashelming - is this something you can help with?  I know you're very familiar with Neon...

**Comment by ghost** [comment]
Duplicate of https://github.com/eclipse/che/issues/4231
