### ISSUE TITLE
The "Save" button is not active after changing a user name.

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4184]
**Reproduction Steps:**

1. Create any project.
2. **"Profile"** -> **"Preferences"** -> **"Git"** -> **"Committer"**.
3. Change the user name in **"Name:"** input box.
4. Press **"Tab"** button.

**Expected behavior:**
Focus is on "Email" input box and the "Save" button is active.

**Observed behavior:**
The "Save" button is not active.

Che version: 5.4.0-SNAPSHOT
OS and version: Ubuntu 16.04 LTS
Docker version: 1.12.3
Che install: Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/23126401/23370adc-f77f-11e6-8a04-15c06be83bf6.gif)

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
