### ISSUE TITLE
Sometime after changing workspace config 'SAVE' button missed

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#4191]
I was replacing memory limit for several workspaces and for some of them after editing memoryLimitBytes 'SAVE ' button hadn't appeared.
![save-button](https://cloud.githubusercontent.com/assets/1636620/23161677/bad17eae-f833-11e6-9bdf-98f8447752b4.png)

**Reproduction Steps:**
Try to edit Workspace Config

**OS and version:**    
Codenvy 5.3.0

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT. Save button does not appear after the first edit and shows up on subsequent ones.

**Comment by olexii4** [comment]
Cannot reproduce in the current version of Codenvy (5.22.1)
