### ISSUE TITLE
Wrong commands are added into workspace when create sample project from IDE

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#4195]
**Reproduction Steps:**
1) Create workspace from Java stack.
2) Open it in IDE (no projects so far)
3) Create project: `Workspace`->`Create Project` and select `web-java-spring`

**Actual result:** Commands are wrong, as a result preview url is wrong:
![wrongpreviewurl](https://cloud.githubusercontent.com/assets/15607393/23172439/6dc8b8e0-f85e-11e6-9888-b5f74dd0379b.png)

**Expected:** Correct commands should be added.
Note, when create project from dashboard all commands are correct.

**OS and version:**  Ubuntu 16.04, CHE 5.4.0-SNAPSHOT

**Comment by mmorhun** [comment]
Now the main problem is fixed, paths are correct, but all commands are added into COMMON section.

**Comment by ghost** [comment]
This is expected behavior. Commands are saved in workspace config, and most likely they are there without goals (old ones)
