### ISSUE TITLE
NullPointerException when expanding multimodule maven project.

### ISSUE THREAD

**Issue by dcdh1983** [eclipse-che/che#4196]
NullPointerException when expanding multimodule maven project.
[6VTPiwas.txt](https://github.com/eclipse/che/files/791626/6VTPiwas.txt)

**Reproduction Steps:**
Import the workspace provided.
Run the workspace *wksp-JEEventStore*.
Click on one of the maven project to expand it.
**OS and version:**    
Eclipse Che 5.3.0

**Diagnostics:** 
Unable to expand a project. A NullPointerException is thrown.
`java.lang.NullPointerException: null
	at org.eclipse.che.api.project.server.DtoConverter.asDto(DtoConverter.java:91) ~[che-core-api-project-5.3.0.jar:5.3.0]
	at org.eclipse.che.api.project.server.ProjectService.getTree(ProjectService.java:813) ~[che-core-api-project-5.3.0.jar:5.3.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	`

Regards,

Damien

**Comment by ghost** [comment]
@dcdh1983 I have imported https://github.com/JEEventStore/JEECQRS and was able to expand it. Can you perhaps specify the project that causes troubles?

**Comment by dcdh** [comment]
![issue](https://cloud.githubusercontent.com/assets/5189615/23239010/0faa3b00-f965-11e6-87bd-c5afc23f54dd.png)

Here is a screenshot of my eclipse Che issue. The exception is thrown when I want to click in the red rectangular.

**Comment by ghost** [comment]
@dcdh1983 it happens because you have projects in workspace config but have not physically imported them. Can you elaborate on how you have created such a workspace?

**Comment by ghost** [comment]
Labeling as a bug. Clicking on such a project should offer a user to clone it.

**Comment by dcdh** [comment]
@eivantsov I confirm I have naively added manually projects entries into the json workspace configuration from *Workspace Config* tab before executing the workspace.

**Comment by ghost** [comment]
This is a bug anyway. Someone will take a look next sprint.
