### ISSUE TITLE
start workspace error

### ISSUE THREAD

**Issue by soonyou** [eclipse-che/che#4198]
![image](https://cloud.githubusercontent.com/assets/25945830/23198012/f22d2204-f8f6-11e6-8348-5832ef1239ce.png)

After I done create the workspace in the workspaces tab and i click the wordspace i create and it will show me this dialog

**Reproduction Steps:**
1. Connect to 192.168.10.244:8080
2. Click workspaces > Add workspace
3. Click workspace I create under recent workspaces

**OS and version:**    
linux (ubuntu 14.04)

**Diagnostics:**

**Comment by ghost** [comment]
@soonyou can you share your start syntax? It looks like your local storage folder is outside %USERPROFILE%

**Comment by okit247** [comment]
hi, @eivantsov I am @soonyou ,here is my start systax
docker run -p 8080:8080            --name eclipseche            --rm            -v /var/run/docker.sock:/var/run/docker.sock            -v /mnt/che/:/data            eclipse/che-server:5.0.0-latest

**Comment by ghost** [comment]
@soonyou two things:

volume mount should be `-v /c/Users/yourUser/che-data:/data`

where `yourUser` is your current Win 7 user name

and the image should be:

` eclipse/che`

**Comment by okit247** [comment]
@eivantsov  i am using linux (ubuntu 14.04) what is the problem as such? how do i resolve?

**Comment by ghost** [comment]
@okit247 I have seen Windows 7 in the original message.

Can you try mount local storage into a different host dir?

`~/che:/data` for example.

**Comment by TylerJewell** [comment]
@okit247 - you are running outdated syntax for the CLI.  
1. If you are on Windows 7, your :/data folder must be a subfolder of %USERPROFILE%
2. Do not mount any ports
3. You need to add interactive `-it`

```
docker run -it --rm
  -v /var/run/docker.sock:/var/run/docker.sock 
  -v ~/che/:/data 
  eclipse/che start
```

**Comment by ghost** [comment]
@soonyou have you made any progress?

**Comment by okit247** [comment]
@eivantsov what is the docker version required for che? i'm using 1.6.2, the minimum required version for che

**Comment by TylerJewell** [comment]
Che requires docker 1.11 starting with 5.0.  Prefer docker 1.12.5 due to bug fixes.

**Comment by okit247** [comment]
@eivantsov @TylerJewell thanks, the problem has solved after I update the docker
