### ISSUE TITLE
Not responding Che GWT WebUI app when using "Navigate to File" action or F4

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#4205]
The GWT is not responding anymore when using "Navigate to File" action

**Reproduction Steps:**

- Create a new workspace with a Che in Che stack
- Clone the che git project
- Navigate to the file "WorkspaceService.java" with "Navigate to File" action
- The browser is hanging with high CPU load in Chrome process
- When using the project explorer to access to the file, it works fine
- Closing and reopening the browser tab stop CPU load the file is not open after reopening

**OS and version:**    
Linux Ubuntu Xenial

**Diagnostics:** 

```
CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:nightly
 Version:        nightly
 Command:        info
 Parameters:     info
Mounts:
 /data:          /home/sunix/dev/che-data
 /data/instance: not set
 /data/backup:   not set
 /repo:          /home/sunix/dev/che-data/instance/data/workspaces/che/eclipse-che
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    nightly
 CHE_HOST:       172.17.0.1
 CHE_INSTANCE:   /home/sunix/dev/che-data/instance
 CHE_CONFIG:     /home/sunix/dev/che-data
 CHE_BACKUP:     /home/sunix/dev/che-data/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   10.32.196.148
 Initialized:    true
 CHE_DEVELOPMENT_REPO: /home/sunix/dev/che-data/instance/data/workspaces/che/eclipse-che
Image Registry:
 IMAGE_INIT=eclipse/che-init:nightly
 IMAGE_CHE=eclipse/che-server:nightly
 IMAGE_COMPOSE=docker/compose:1.8.1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:nightly
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:nightly
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:nightly
 UTILITY_IMAGE_CHETEST=eclipse/che-test:nightly
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:nightly
che.env:
 CHE_HOST=172.17.0.1
 CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock;/home/sunix/.m2:/home/user/.m2
 CHE_DOCKER_PRIVILEGED=true
```

**Comment by sunix** [comment]
Seems to be an issue on Java files
Also hang when reoppening the IDE ... when had previously opened java files, ...
For me this is blocker
I tried with another che running on another computer and I can reproduce, maybe related to maven

**Comment by sunix** [comment]
ok seems to be when the file is not expanded in the project explorer, maybe related to the fact that packages are not displayed as a tree in the explorer.

**Comment by TylerJewell** [comment]
We are testing fixes that will resolve this and some other issues.  We will issue a bug fix as soon as this branch is merged - probably within a week.

https://github.com/eclipse/che/tree/che%233891

**Comment by sunix** [comment]
great !!!! can't wait to have these fixes :)
