### ISSUE TITLE
Debugger doesn't activate breakpoints in inner classes

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4211]
Java console project can be found [here](https://github.com/dmytro-ndp/java-inner.git). There are varouse type of inner classes with methods where breakpoints aren't activated in runtime after start of debug session.

**Reproduction Steps:**
1. Open workspace and import test project https://github.com/dmytro-ndp/java-inner as maven project.
1. Add maven command "**build-and-debug**": `clean install && java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y ${current.project.path}/target/*.jar`
1. Open "**src/main/java/test/App.java**" file inside editor and set next breakpoints:
\- _anonymous class_: at line **26** in the method _getAnonymValue()_
\- _method local inner class_: at line **42** in the method _App.getAppValue().MethodLocalInner.getValue()_;
\- _inner class_: at line **53** in the method _App.Inner.getInnerValue()_;
\- _static inner class_: at line **61** in the method _App.StaticInner.getStaticInnerValue()_.
1. Call top menu command "_Run > Edit Debug Configurations..._" and create _Java Remote configuration_ with port=8000.
1. Invoke "**build-and-debug**" command and wait until there is "Listening for transport dt_socket at address: 8000" message in console.
1. Call top menu command "_Run > Debug > Remote java_"

***Expected behavior:***
All breakpoints become an active, and Che is break executing of application at the next line one-by-one: 26, 42, 53, 61

***Actual wrong behaviour:***
Breakpoints didn't become an active, and Che executed an application without stops.

***Screencast:***
![out](https://cloud.githubusercontent.com/assets/1197777/23223321/6eeed9ea-f933-11e6-842c-d01626f2c49d.gif)

***Selenium tests:***
There is couple selenium tests which should be enabled after this bug is fixed:
- InnerClassAndLambdaDebuggingTest.**shouldDebugMethodLocalInnerClass()**
- InnerClassAndLambdaDebuggingTest.**shouldDebugInnerClass()**
- InnerClassAndLambdaDebuggingTest.**shouldDebugStaticInnerClass()**

**OS and version:**    
Ubuntu 14.04 LTS
Browser: Chrome Version 55.0.2883.87 (64-bit)
Che version: 5.3.1

How to fix:
Analyse parents of `iMember`
https://github.com/eclipse/che/blob/0e4ffb7f8704fd6536a5d03a9f98cb1ab2f88d3a/plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/utils/JavaDebuggerUtils.java#L224

If any parent is `instance of SourceMethod` it means we have deal with local inner class and have to take it in into account by altering fully qualified name from `classA$classB` to `classA$1classB`

- [x] Fix java debugger server side

**Comment by ghost** [comment]
Reproduced with 5.15-SNAPSHOT

**Comment by tolusha** [comment]
Won't be fixed due to https://github.com/eclipse/che/issues/6480
I will provide PR to remove test.

**Comment by dmytro-ndp** [comment]
Why it will not be fixed? It's still actual bug.

**Comment by dmytro-ndp** [comment]
If I understand it correctly, implementing of _VS Code_ (#6480) could, potentially, fix this issue as well. So, I propose do not close this issue until we ensure this bug doesn't reproduce with _VS Code_.
