### ISSUE TITLE
Stack text goes out from the boundaries of describing stack library

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4216]
**Reproduction Steps:**

1. Go to the **Dashboard** -> **Stacks**
2. Create a duplicated stack for BITNAMI CODEIGNITER
3. "Dashboard" -> "Create Workspace" -> Create new workspace from the stack library

**Expected behavior:**
The text should not go beyond the boundaries of  describing the stack library

**Observed behavior:**
The text goes out from the boundaries of  describing the stack library
![7bf97bcc-f9c4-11e6-9d49-bd92cc6b3329](https://cloud.githubusercontent.com/assets/1640058/23255705/45b37094-f9c5-11e6-82ed-9494727929cb.png)

**Che version:** 5.4.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![long_stack_text_info](https://cloud.githubusercontent.com/assets/7760565/23254774/df107970-f9c1-11e6-8e00-ebe521b0b36c.gif)

**Comment by ghost** [comment]
Cannot be reproduced in 5.15-SNAPSHOT. Stack icons and their representation on UD has changed.
