### ISSUE TITLE
CHE-546 Workspace Agent should consider to return transitional state while initializing projects

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#422]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-546
Reporter:  Gennady Azarenkov
Description: After Workspace agent is up and running it starts to perform projects initialization, to take provided attributes, add detected inner projects (modules) and for big projects (like /che itself) it may take a while.
During this time Agent is workable i.e. it is able to return projects but this list of project is not finite since initialization is in progress.
So as an initial solution if project list is not initialized we return ServerException with message like:
"Projects are not initialized yet".

**Comment by ddementieva** [comment]
Fixed
