### ISSUE TITLE
Visual mode of terminal is broken when user presses CTRL-\, ENTER in midnight commander

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#4227]
Visual mode of terminal is broken when user presses CTRL-L, ENTER in midnight commander.

**Reproduction Steps:**
1. Start WS
2. Open `mc` in terminal
3. Press CTRL-\, ENTER

![selection_037](https://cloud.githubusercontent.com/assets/1851863/23309256/9f370882-fab6-11e6-864d-ebfb5ea22929.png)

**Comment by ghost** [comment]
Resizing the terminal to a reasonable size did not do anything weird on my side. In fact, all panels, when resized like this stop scaling sooner or later.
