### ISSUE TITLE
Visual mode of terminal is broken in some case in midnight commander

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#4228]
Visual mode of terminal is broken in midnight commander when user creates file with `touch` utility and presses down or up key.

**Reproduction Steps:**
1. Start WS
2. Open `mc` in terminal
3. Type `touch test` 
4. Press ENTER, Down

![selection_038](https://cloud.githubusercontent.com/assets/1851863/23309430/4d3fb514-fab7-11e6-885b-a8245234cd8e.png)

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
