### ISSUE TITLE
MC is broken right after launch

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#4229]
When user opens `mc` in terminal and type `touch` terminal shows `ouch`

**Reproduction Steps:**
1. Start WS
2. Open `mc` in terminal
3. Type `touch`

![selection_039](https://cloud.githubusercontent.com/assets/1851863/23309532/a89f1f1c-fab7-11e6-995c-5f8d58bfd189.png)

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
