### ISSUE TITLE
Url preview is not being generated

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#4238]
Installed Docker and Che roughly 2 hours ago. ~(5 a.m CST Feb 27, 2017)

![](http://i.imgur.com/3ezNw6g.png)

Che appears to output the unevaluated argument as the preview URL, while evaluating arguments in the command line.

**Reproduction Steps:**

- Create node.js workspace with angular-patternfly-starter.
![image](https://cloud.githubusercontent.com/assets/4656027/23414554/f5fcde7e-fda1-11e6-812f-5405f50e73b7.png)

- Go to Workspaces in the side bar, select the node workspace, then Runtime, then Dev Machine, scroll down to Servers, and click Add to add a new server. Reference = `bower-browser` port =`3010` and protocol = `http`. Add and Save. Che restarts the workspace. 

- Open the node workspace. Che IDE opens.

- Use Terminal to install bower-browser globally.  `sudo npm i bower-browser -g`
![image](https://cloud.githubusercontent.com/assets/4656027/23414900/1c562872-fda3-11e6-9f2c-fd4ba0b800b7.png)

- Create a new custom command and name it "bower-browser" with `cd ${current.project.path}; bower-browser --silent` in the command line box and `http://${server.port.3010}` in the preview url.  _note:  `cd ${current.project.path} . . .` works as expected_. 

- Save Command and return to IDE.

- Use the dropdown to select "bower-browser" command and press play. Problem started here.
_Note: Today, Feb 28, as I went through the steps to clean up formatting and provide more screenshots, this one worked_

- Use the dropdown to select the node template's included command "angular-patternfly-starter: run" and press play. Problem continues.
![image](https://cloud.githubusercontent.com/assets/4656027/23416078/031aadac-fda7-11e6-8408-7087d3f1e15c.png)

- Delete and Recreate workspace with a different name (Node + angular-patternfly-starter). Skip exposing port and adding "bower-browser" command.

- Go to re-created node workspace and run angular command.

- Problem persists.
![image](https://cloud.githubusercontent.com/assets/4656027/23416539/d4cc8040-fda8-11e6-9129-e37598bc2259.png)

**OS and version:**    
`lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by TylerJewell** [comment]
@gnoejuan - I was having a bit of a hard time following your reproduction steps. It would help if you could use some markdown bullets to make it easier to follow.

1. Did you try running any of the provided stacks and templates?  Do their preview URLs show properly?
2. Your image embedded in the issue shows a macro called `${server.port.8003}` but your comments talk about `${server.port.3010}`.  Which one is it?  The macro maps the server that is internally bound to port 3010 inside of your workspace to the port that it is exposed to externally.  So your server needs to be running and bound inside the workspace.  On the command line, you can also see the port that it is running on by doing a `docker inspect <ws-container-id>`, and you can find the workspace's container by doing a `docker ps -a`.

**Comment by gnoejuan** [comment]
Thanks for responding!

In regards to the macro, it's both. 

 The one in the image (8003) is from the provided angular-fly-template. I'll update the original issue momentarily. 3010 is from the custom command I was trying to create.

**Comment by gnoejuan** [comment]
I've updated the original post. The deleting and recreating the workspace was just me trouble-shooting. 

I **believe** the "angular-patternfly-starter: run" command worked before I added "bower-browser" command, otherwise, I wouldn't have included the steps.

Edit: it looks like the provided node stack does not have port 8003 is not exposed? Here is the output of docker inspect:

```
            "Ports": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32818"
                    }
                ],
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32817"
                    }
                ],
                "4401/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32816"
                    }
                ],
                "4403/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32815"
                    }
                ],
                "4411/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32814"
                    }
                ],
                "5000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32813"
                    }
                ],
                "9000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32812"
                    }
                ]
            }
```

**Comment by ghost** [comment]
Indeed, port 8003 isn't exposed, that is why this macro isn't translated into an actual host:port.

As to adding own servers, it is possible in User Dashboard, but you need to restarted a workspace.

**Comment by ghost** [comment]
@gnoejuan I have updated node stack. Can you give it a try now?

**Comment by gnoejuan** [comment]
The url preview is now correct.

![image](https://cloud.githubusercontent.com/assets/4656027/23474357/2d1dc012-fe79-11e6-924f-03f6665742bb.png)
