### ISSUE TITLE
Wrong creation of project after recreate the same stack

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#4239]
When I recreate  workspace from the same stack then the template project is created recursively.

**Reproduction Steps:**
* On the dashboard go to 'Dashboard' -> 'Create Workspace' -> 'Create new workspace from stack' (e.g. Java ready stack)
* Delete the workspace and create it again
* In the IDE expand the project (e.g. console-java-simple)

**Expected behavior:**
the project should not be another project in himself

**Observed behavior:**
the project is created recursively

**Che version:** 5.4.0
**OS and version:**  Ubuntu 14.04 
**Docker version:** 1.12
**Che install:** Docker container

**Additional information:**

Problem can be reliably reproduced, doesn't happen randomly: [Yes]
See the attachment:
![wrong_create_project](https://cloud.githubusercontent.com/assets/5408906/23366748/8ceed248-fd10-11e6-9524-97a012205a26.png)

**Comment by riuvshin** [comment]
@vparfonov please take a look
