### ISSUE TITLE
Workflow for multi-machine stack development on the command line

### ISSUE THREAD

**Issue by dcdh1983** [eclipse-che/che#4240]
Hi, I've got a question about the creation of multi machine stack.
When I edit the provided one **Java-MySQL** I have noticed in the recipe a dependency between the **dev-machine** container and the **db** container represented by this code in **dev-machine** declaration:
```
depends_on:
    - db
```
(a document can be found here **https://www.eclipse.org/che/docs/tutorials/multi-machine/index.html** explaining the objective)
I tried to do the same with a new custom one, however I am unable to find a way to define dependencies between container using your interface and editing the raw configuration lead to an error.
Can you give me a way to define containers dependencies ?
Thanks by advance.

**Reproduction Steps:**
see below
**OS and version:**    
5.3.0
**Diagnostics:**

**Comment by TylerJewell** [comment]
Hi @dcdh1983 - it looks like you are trying to author a custom stack recipe.  We have documentation on how to write those as compose files here - https://www.eclipse.org/che/docs/workspace/recipes/index.html.  If you are following these instructions, you will need to provide a reproducible set of steps in the issue so that engineers can investigate further.

**Comment by ghost** [comment]
@dcdh1983 posting your composefile and error will help me help you.

**Comment by dcdh1983** [comment]
![capture d ecran de 2017-03-01 02 12 22](https://cloud.githubusercontent.com/assets/25872002/23441759/94353898-fe24-11e6-99ff-ab76b8890851.png)
@TylerJewell I confirm I want to write a custom stack recipe. I have tried your suggestion by defining a custom recipe in **Stack authoring** when adding a new workspace and it works.
However, if I want to create a reusable custom stack (from the link **Stacks** present in left menu) it's more complicated. From this screen I've found a way. Let's say I want a **dev** machine linked with a **db** machine I will do these steps:
- go to **Stacks**;
- click on the button **Add Stacks**;
- add a machine called **db**;
- add a machine called **dev** defining the **depends_on: - db** in the recipe;
- switch on the **Dev** button in **dev** machine;
- remove the default machine **dev-machine** (not used anymore);

It's working, but it's a little tricky.

I guess it would have been easier if ~~after adding a machine we would be able to edit the recipe (currently we can only view the content).~~ we could have the same comportment than **Stack authoring** ie. we put the content of the recipe on a Textarea then it creates all machines (and the textarea is always editable)

I've uploaded a picture representing the current result.

**Comment by TylerJewell** [comment]
@dcdh1983 - yes, thank you for the feedback.  I agree that the workflow around building and testing custom stacks using that particular GUI is a bit complicated. That GUI is primarily there for people who are consuming existing stacks and it's not exactly ideal for authoring new stacks as a DevOps or a Team Leader who is setting the stage for a group of other people.  

We have been thinking a lot around this process for stack creation, and are starting to work on designs for a command-line stack development workflow that will make this particular process more fun for those that want to quickly iterate on edit / build / test a stack inside of Codenvy.  I think it will take us some time to work through the details, but ideas that we are thinking about:
1. Determinism of stacks (sha256 or other cryptographic hash that spans all machines + stack metadata)
2. Command line sequence for add / edit / remove / build / test a stack.
3. Perhaps a language server for auto-complete and syntax analysis of a stack JSON
4. Stack versioning and rollback
5. Stack analysis, to give possible errors in how you have set various fields for feedback

**Comment by TylerJewell** [comment]
@benoitf - let's use this issue as a start for documenting thoughts that we develop on how to improve on the command line the workflow around building, signing, and registering stacks within a running system.
