### ISSUE TITLE
The tab for sorting workspaces by RAM doesn't work

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4242]
**Reproduction Steps:**

-  Create some workspaces with different sizes of RAM
-  Click the **Workspaces RAM** tab for sorting the workspaces list

**Expected behavior:**
The workspaces list was sorted by RAM

**Observed behavior:**
The workspaces list was not sorted

**Che version:** 5.4.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container
**Failed selenium test:** WorkspacesListTest

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![ws_sorting](https://cloud.githubusercontent.com/assets/7760565/23395836/5e54420e-fd99-11e6-90e4-439a0309011c.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
