### ISSUE TITLE
The recent workspaces list doesn't work correctly

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4243]
**Reproduction Steps:**

- Delete all the workspaces
- Create 6 any workspaces

**Expected behavior:**
In the **recent workspaces** list 5 recent workspaces are visible

**Observed behavior:**
Only the first created workspace is visible
If create workspaces again they will be added to the "Recent Workspaces" list and more then 5 workspaces are visible(see screenshot 1)

**Che version:** 5.4.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![recent_ws](https://cloud.githubusercontent.com/assets/7760565/23395152/c3612ec2-fd95-11e6-9951-7854ee7d6719.gif)
**Screenshot №1**
![_ws](https://cloud.githubusercontent.com/assets/7760565/23395162/d89c5e6a-fd95-11e6-826d-4183212e6532.png)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/issues/1687

**Comment by olexii4** [comment]
should be fixed in  https://github.com/eclipse/che/pull/4246/commits/be4bc51cd3c289e48d25c4af5543257969811c50
