### ISSUE TITLE
Rearrange Assembly Module

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#425]
It is confusing to new users on how an assembly is constructed.  The final assembly directory is the combination of assets that are generated across 4 different modules in the `assembly` directory of Che. Two of those four modules use the `maven-assembly-plugin` to construct an output directory. That plugin has a convention where the source files that are used in the construction of the output are located in `/src/assembly`. That plugin is also able to install files that are located in various repositories.

It's not logical nor sensible to have users traversing through four different modules to determine where various files that go into an assembly are source from.

I propose to reorganize the assembly so that the `maven-assembly-plugin` uses a single source assembly that is saved at the root of the assembly directory.  This source assembly would contain all base files used in the assembly, unless those files are copied in as part of a pull from a repository, such as the JAR files for plug-ins or the ZIP file for Tomcat.

Existing Assembly Structure

```
/assembly
/assembly/assembly-main
/assembly/assembly-ide-war
/assembly/assembly-machine-war
/assembly/assembly-machine-server
```

Proposed Assembly Structure

```
/assembly-che/server       # Generates the Che server
/assembly-che/webapp       # Generates the IDE client web app
/assembly-machine/server   # Generates the machine server for a workspace
/assembly-machine/webapp   # Generates the web app that goes into machine server
```

**Comment by skabashnyuk** [comment]
your proposal looks very strange from maven point of view
Usually sources should be inside of modules, not outside like /assembly/base  
I think such structure will confuse end users.

Lets stay with current.

**Comment by TylerJewell** [comment]
I am not ok with leaving as current. The maven approach is confusing. 

So if you do not approve of this solution please suggest additional options.  I have spoken with a few users and the current structure is virtually impossible to understand.

**Comment by garagatyi** [comment]
Now we have regular structure for maven project. You propose include partial compilation of code in assembly. It's really uncommon, so this may cause new bugs. Dependency management will be complicated due to lack information what dependency library is needed on what part of Che.

**Comment by TylerJewell** [comment]
There is no compiled code in the assembly.  The base directory would include all non nexus assets and the full directory structure.

**Comment by garagatyi** [comment]
Where dependencies will be declared? In base module or in modules where they are really needed?

**Comment by TylerJewell** [comment]
the maven assembly plugin uses an xml file to describe how to assemble a structure.  Today for a single assembly we have two separate files in two separate modules.  I would put the files into the base portion and label them so that it is clear how a single assembly will be built from layering their descriptors.

**Comment by TylerJewell** [comment]
@skabashnyuk there were some modifications made - what do you think of this structure?

**Comment by TylerJewell** [comment]
Specification rejected.
