### ISSUE TITLE
Update xterm.js to the latest version.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#4251]
We should update xterm.js to the latest version for bug fixing.
This issue consist of steps:
create and pass cq.
add latest xterm.js souce code to CHE.
update gulp tasks to build xterm.js and maybe fix some new css styles.
Apply our custom changes.

**Comment by AndrienkoAleksandr** [comment]
depend on https://github.com/eclipse/che/issues/4315

**Comment by skabashnyuk** [comment]
- are you planning to approve test resources?
- are you planning to move xcode related code to lib?

**Comment by AndrienkoAleksandr** [comment]
@skabashnyuk Yes, we will move terminal to lib (without tests.).

**Comment by AndrienkoAleksandr** [comment]
I checked integration new version of the terminal to Eclipse CHE. For now this issue awaiting to approve CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12882 .

**Comment by AndrienkoAleksandr** [comment]
CQ passed.
