### ISSUE TITLE
The error event message appears when deleting a file in the Project Explorer

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4252]
**Reproduction Steps:**

1. Start any workspace with a project
2. Open a file in the Editor
3. Delete the file

**Expected behavior:**
The file is **deleted**

**Observed behavior:**
The file deleted and "Failed to update content of file(s)" event appears
The error message appears only if this file open in the Editor

**Che version:** 5.4.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/23402893/450ca1a2-fdb6-11e6-80fc-a65108287df5.gif)

**Comment by SkorikSergey** [comment]
File watcher works incorrectly (regression)  - https://github.com/eclipse/che/issues/3537

**Comment by vzhukovs** [comment]
Fixed with 194f044
