### ISSUE TITLE
The MC editor doesn't start when a java file open in the Editor

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4260]
**Reproduction Steps:**

1. Create a project with java files(like web-java-spring, web-java-petclinic)
2. Open in the **Editor** any java file
3. Start the **Midnight Commander** in the **Terminal**
4. Select any file and press **F4**

**Expected behavior:**
Selected in the MC file is opened in the MC editor

**Observed behavior:**
Nothing happened. While the java file is open in the **Editor** **F4** button doesn't work.
Close the java file or open in the Editor any not java file then **F4** will be works.

**Che version:** 5.4.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![mc_and_nano_dont_work_with_javafile_open](https://cloud.githubusercontent.com/assets/7760565/23407472/bf7a7b4c-fdcc-11e6-9b4d-dfd77adeed7b.gif)

**Comment by riuvshin** [comment]
@vparfonov filewatchers!

**Comment by AndrienkoAleksandr** [comment]
@vparfonov maybe JDT because, @SkorikSergey said that bug is reproducible only for java files.

**Comment by riuvshin** [comment]
@vparfonov please take a look
