### ISSUE TITLE
The "Move Item" widget appeared when press Ctr+X in the Terminal

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4265]
**Reproduction Steps:**

1. Create a project with java files(like web-java-spring, web-java-petclinic)
2. Open in the Editor any java file
3. Start a new Terminal
4. Press **Ctr+X** in the Terminal

**Expected behavior:**
Nothing happened.

**Observed behavior:**
The **"Move Item"** widget appeared. 
The widget appears only if a java file is opened in the Editor.

**Che version:** 5.4.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]

![ctr c_for_terminal_with_javafile](https://cloud.githubusercontent.com/assets/7760565/23411531/38586430-fddb-11e6-8eac-d73b1990ef6a.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
