### ISSUE TITLE
Workspace creation from config with code

### ISSUE THREAD

**Issue by rajivece** [eclipse-che/che#4266]
Hi,
I'm trying to export workspace with code from git using export as a file and trying to import it into another Che instance through Dashboard -> New Workspace -> Create from configuration. 
Workspace is created successfully but the code is not pulled. 
How do I achieve this?

**Reproduction Steps:**
Two instances of Che are running on two systems

**OS and version:**    
Ubuntu 14.04
Docker version: 1.12.6

**Comment by ghost** [comment]
@rajivece @TylerJewell source is saved to workspace config, but it's just config. When you start such a workspace, you will see your project icon in the project tree with a red cross on it, which means it is in workspace config but there are no sources (physical location).

When clicking on such a project, the IDE should offer you to close the project from the repo which is saved in a workspace config.

Here's the issue - https://github.com/eclipse/che/issues/4196

**Comment by ghost** [comment]
Closing the issue. Follow https://github.com/eclipse/che/issues/4196
