### ISSUE TITLE
Debug console displays instance and local variables of the same name identically

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4267]
Java console project for testing can be found [here](https://github.com/dmytro-ndp/java8-static.git).

**Reproduction Steps:**
1. Open workspace and import test project https://github.com/dmytro-ndp/java8-static.git. Configure it as a maven project.
1. Add maven command "**build-and-debug**":
```
clean install && java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y ${current.project.path}/target/*.jar
```
1. Open "**src/main/java/test/Book.java**" file inside editor and set breakpoint at line 7.
1. Call top menu command "_Run > Edit Debug Configurations..._" and create _Java Remote configuration_ with port=8000.
1. Invoke "**build-and-debug**" command and wait until there is _"Listening for transport dt_socket at address: 8000"_ message in console.
1. Call top menu command "_Run > Debug > Remote java_"

***Expected behaviour:***
Che stop execution at the line 7. There is two rows in the _Variables panel_ of _Debug console_:
> this.title: null
> title: "java"

***Actual misleading behaviour:***
Che stopped execution at the line 7. There were two rows in the _Variables panel_ of _Debug console_:
> title: null
> title: "java"

![screenshot from 2017-02-28 19 00 07](https://cloud.githubusercontent.com/assets/1197777/23416077/0d7f46d4-fdea-11e6-9ce9-149f4b5a07dc.png)

***Screencast:***
![out](https://cloud.githubusercontent.com/assets/1197777/23416029/dc6cfdfc-fde9-11e6-821d-c703a1826345.gif)

There is selenium test [MultimoduleProjectDebuggingTest.shouldStopInsideConstructor()](https://github.com/codenvy/qa/blob/master/src/test/java/com/codenvy/ide/debugger/MultimoduleProjectDebuggingTest.java#L156) which should be updated as well after this bug is fixed.

**OS and version:**
Ubuntu 14.04 LTS
Browser: Chrome Version 55.0.2883.87 (64-bit)
Che version: 5.4.0-SNAPSHOT. Revision: 7187062d377da2bc

**Diagnostics:**
```
ndp@ndp:~/projects/training/qa/java8-static$ docker run -ti -v /home/ndp/data/che/:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:nightly info
WARNING: No swap limit support
INFO: (che cli): nightly - using docker 1.12.6 / native
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che
Digest: sha256:4b138b4519ed39c9d4ab9aa13d7678eeaa493fee4d010ac63a566ecad35b2d82
Status: Image is up to date for eclipse/che:nightly

CLI:
 TTY: true
 Daemon: /var/run/docker.sock
 Image: eclipse/che:nightly
 Version: nightly
 Command: info
 Parameters: info
Mounts:
 /data: /home/ndp/data/che/
 /data/instance: not set
 /data/backup: not set
 /repo: not set
 /assembly: not set
 /sync: not set
 /unison: not set
 /chedir: not set
System:
 Docker: native
 Proxy: not set
Internal:
 CHE_VERSION: nightly
 CHE_HOST: 172.19.20.32
 CHE_INSTANCE: /home/ndp/data/che//instance
 CHE_CONFIG: /home/ndp/data/che/
 CHE_BACKUP: /home/ndp/data/che//backup
 CHE_REGISTRY: /version
 CHE_DEBUG: false
 IP Detection: 172.19.20.32
 Initialized: true
Image Registry:
 IMAGE_INIT=eclipse/che-init:nightly
 IMAGE_CHE=eclipse/che-server:nightly
 IMAGE_COMPOSE=docker/compose:1.8.1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:nightly
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:nightly
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:nightly
 UTILITY_IMAGE_CHETEST=eclipse/che-test:nightly
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:nightly
che.env:
 CHE_HOST=172.19.20.32
 CHE_OAUTH_GITHUB_CLIENTID=***
 CHE_OAUTH_GITHUB_CLIENTSECRET=***
 CHE_OAUTH_GITHUB_AUTHURI=https://github.com/login/oauth/authorize
 CHE_OAUTH_GITHUB_TOKENURI=https://github.com/login/oauth/access_token
 CHE_OAUTH_GITHUB_REDIRECTURIS=http://localhost:${SERVER_PORT}/wsmaster/api/oauth/callback
```

**Comment by ghost** [comment]
Cannot be reproduced with 5.15-SNAPSHOT

![image](https://user-images.githubusercontent.com/5337267/28055737-eb522486-6622-11e7-8c89-2fe2e0bbcab4.png)
