### ISSUE TITLE
Improve run, debug and preview buttons behavior with new intelligent command

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4279]
# User stories
- As a user, I'm able to default the command which will be executed when pressing the "run", "debug" or "preview" button
- As a user, I can change the default command associated with one of the "run, "debug" or "preview" button

## Mockups
<img width="564" alt="screen shot 2017-03-01 at 16 59 48" src="https://cloud.githubusercontent.com/assets/1636769/23465468/05d4c384-fea1-11e6-8ca2-61eb23b283f0.png">

**Comment by TylerJewell** [comment]
1. If you have a button without a triangle on it, then it should not show a drop down.  It should either be grayed out, or it should just run the selected command.
2. If you have a button with a triangle on it, then it should always drop down with a single click.

You can then have long-click behaviors for each of these displays.

**Comment by slemeur** [comment]
Discussed and decided to keep the current behaviour as defined in initial specification #3519 

## Run and Debug buttons

https://cloud.githubusercontent.com/assets/1636769/22267856/9ab0b360-e285-11e6-9fdc-9c59415c4f19.png

By default, we display buttons for “Run” and “Debug”. The buttons when clicked, it displays the whole commands list of the goal and when a command is hovered, it allows to select the target where to execute the command.

Nice to have:
User must have the ability to define default command for a goal.
I’d like the user being able to configure a button per goal in the toolbar if he wants it. This should be in the Preferences, but by default, we would display “Run” and “Build” buttons in the toolbar.
We would have two actions on these buttons:

single-click: it executes the default command of the goal
long-click: it will display the whole commands list of the goal in a dropdown as we have today.
