### ISSUE TITLE
UD automatically change WS configuration in unexpected way

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#4281]
When I create WS, go into WS config section and change type of environment from **dockerimage** to **dockerfile** UD change environment into **compose** for some reason.

**Reproduction Steps:**
1. Press create WS
2. Choose ubuntu jdk 8 stack
3. Go to workspace config section
4. Change **dockerimage** to **dockerfile**

**Expected** 
UD change value and does nothing.

**Actual**
UD changes WS config completely. Now environment type is compose.

**Comment by ghost** [comment]
Cannot be reproduced with 5.15-SNAPSHOT. When such a change is actually made, Dashboard displays an error:

![image](https://user-images.githubusercontent.com/5337267/28065349-dc0de906-6640-11e7-9219-967a08ed6b18.png)
