### ISSUE TITLE
Eclipse Che - RecentWorkspace does not list items correctly

### ISSUE THREAD

**Issue by MuraliVidhya** [eclipse-che/che#4289]
Hello,
In the RECENTWORKSPACES section, the lats modified work space or the recent ones does not list up.
Always it shows only one though i have 6 workspaces Do we have any fix for this or is this a known issue.

Thank you.

**Comment by TylerJewell** [comment]
@mvidhya86 - those details are very thin.  You can search the issues for similar sorts of issues if they exist.  Otherwise, please provide a series of steps to reproduce the issue and possibly an animated gif with it, too.

**Comment by ghost** [comment]
@mvidhya86 we have released 5.4.0. Can you reproduce this behavior with the latest tag?

**Comment by MuraliVidhya** [comment]
Hi,
These are the steps i followed.
#> I created around 6 workspaces of different stacks
RECENT WORKSPACES lists always shows the old ones and not the last updated workspace though the status is running
#> Also during workspace creation if i consider 'Stack Authoring' and have docker receipe - the workspace name which i provided in this step is not same as the workspace name once it is created. In other words, workspace name provided during creation of workspace by Stack Authoring does not seem to work.

Yes, will upgrade to 5.4.0 version and check with the new version too

**Comment by ghost** [comment]
@mvidhya86 any update please?

**Comment by MuraliVidhya** [comment]
With new version of Che this issue seems to be resolved
