### ISSUE TITLE
CHE-549 [dashboard] increase timeout delays in unit tests

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#429]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-549
Reporter:  Florent Benoit
Description: on CI, when server is very busy we have some error messages during unit tests like
[exec] 18 02 2016 21:54:24.807:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.

We should increase these timeout value

**Comment by ddementieva** [comment]
Fixed
