### ISSUE TITLE
CHE-550 Adapt projects in dashboard to 4.0 changes

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#430]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-550
Reporter:  Anna Shumilova
Description: Need to adapt projects view and project details to 4.0 changes. Known bugs are:
# we allow to open project in stopped workspace (causes errors)
# rename/update project description fails
# unable to retrieve repository info

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/pull/483
