### ISSUE TITLE
Sometimes project-explorer tree expands needless paths

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#4300]
In some cases after page refreshing project explorer expands folders which weren't open before refresh.

**Reproduction Steps:**
1) Create a workspace
2) Clone [ticket-monster](https://github.com/jboss-developer/ticket-monster.git) through import project and configure as blanck project
3) Open some path in `ticket-monster`->`demo`->`....`, do not open `cordova` folder
4) Refresh page

After refreshing folder `cordova` is open, which shouldn't happen.
![opentree](https://cloud.githubusercontent.com/assets/15607393/23544332/448ffa6c-ffff-11e6-95fd-e60c2485ca40.gif)

**OS and version:**   Ubuntu 16.04 LTS

**Comment by ghost** [comment]
Can be reproduced with current master.
