### ISSUE TITLE
Che doesn't remove debug line highlighting if debugging file is changed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4307]
**Reproduction Steps:**
1. Open workspace and create project from **console-java-simple** template.
1. Add maven command "**build-and-debug**": `clean install && java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y ${current.project.path}/target/*.jar`
1. Open "**src/main/java/org/eclipse/che/examples/HelloWorld.java**" file inside editor and set breakpoint above the first line of main() method.
1. Invoke "**build-and-debug**" command and wait until there is _"Listening for transport dt_socket at address: 8000"_ message appeared in console.
1. Call top menu command "_Run > Debug > Remote java_" and wait until Che stops execution of **HelloWorld.java** in the first line of **main()** method.
1. Insert empty line before first line in **main()** method.
1. Step to the next line by clicking on **StepOver** button in _Debug console_.

***Expected behaviour:***
Che moves debug line highlighter to next line.

***Actual misleading behaviour:***
Che highlights two lines as debug line.
![screenshot from 2017-03-03 19 36 22](https://cloud.githubusercontent.com/assets/1197777/23562259/6195e72a-004a-11e7-9de8-27e5d8d85242.png)

***Screencast:***
![out](https://cloud.githubusercontent.com/assets/1197777/23562265/6a3eb244-004a-11e7-8dea-e0778db75439.gif)

**OS and version:**
Ubuntu 14.04 LTS
Browser: Chrome Version 55.0.2883.87 (64-bit)
Che version: 5.4.0-SNAPSHOT. Revision: c76d7bdcfe86ed1d

**Diagnostics:**
```
ndp@ndp:~/projects/qa$ docker run -ti -v /home/ndp/data/che/:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:nightly info
WARNING: No swap limit support
INFO: (che cli): nightly - using docker 1.12.6 / native
INFO: (che download): Pulling image eclipse/che:nightly

nightly: Pulling from eclipse/che
Digest: sha256:9d76f4c90c1f069cff65b813b268d12cbc61e3041c856351120baaaf409e4b05
Status: Image is up to date for eclipse/che:nightly

CLI:
 TTY: true
 Daemon: /var/run/docker.sock
 Image: eclipse/che:nightly
 Version: nightly
 Command: info
 Parameters: info
Mounts:
 /data: /home/ndp/data/che/
 /data/instance: not set
 /data/backup: not set
 /repo: not set
 /assembly: not set
 /sync: not set
 /unison: not set
 /chedir: not set
System:
 Docker: native
 Proxy: not set
Internal:
 CHE_VERSION: nightly
 CHE_HOST: 172.19.20.32
 CHE_INSTANCE: /home/ndp/data/che//instance
 CHE_CONFIG: /home/ndp/data/che/
 CHE_BACKUP: /home/ndp/data/che//backup
 CHE_REGISTRY: /version
 CHE_DEBUG: false
 IP Detection: 172.19.20.32
 Initialized: true
Image Registry:
 IMAGE_INIT=eclipse/che-init:nightly
 IMAGE_CHE=eclipse/che-server:nightly
 IMAGE_COMPOSE=docker/compose:1.8.1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:nightly
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:nightly
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:nightly
 UTILITY_IMAGE_CHETEST=eclipse/che-test:nightly
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:nightly
che.env:
 CHE_HOST=172.19.20.32
 CHE_OAUTH_GITHUB_CLIENTID=***
 CHE_OAUTH_GITHUB_CLIENTSECRET=***
 CHE_OAUTH_GITHUB_AUTHURI=https://github.com/login/oauth/authorize
 CHE_OAUTH_GITHUB_TOKENURI=https://github.com/login/oauth/access_token
 CHE_OAUTH_GITHUB_REDIRECTURIS=http://localhost:${SERVER_PORT}/wsmaster/api/oauth/callback
```

**Comment by ghost** [comment]
Reproduced with 5.15-SNAPSHOT

**Comment by tolusha** [comment]
Fixed
