### ISSUE TITLE
Improve UX of usage of docker images that are source of containers that exits right after start

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#4310]
Now if user uses some image that doesn't have `cmd`, `entrypoint` or have shell interpreter there Che shows weird error on workspace start. 

For such cases we can inspect image and if it is such image set entrypoint/cmd into container.
Since we can't detect all possible variants where container exist immediately after start we should also inspect container after start and if it has state stopped then return pretty error with the explanation on why container exited.

This enhancement was asked by @benoitf and @skryzhny 

**Reproduction Steps:**
1. Create WS from image ubuntu
1. Start this WS

**Comment by TylerJewell** [comment]
Yes, I think this will be a substantial improvement.  You mention Ubuntu - is this only for that distro or would it apply equally to all?

**Comment by benoitf** [comment]
It's to all (including for exemple alpine as well)

**Comment by benoitf** [comment]
In my case it was for openjdk:8-jre-alpine

**Comment by garagatyi** [comment]
Yes it is for several images, not just ubuntu. We can't cover all the images but those that have one of the expected entrypoint,cmd pairs can be improved
