### ISSUE TITLE
No notification that connection to server and ws agent has been lost

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4311]
Not sure if this is a bug or an enhancement request.

Steps to reproduce on Win 10.

1. Start Che
2. Start a workspace
3. Stop all running containers.

When in the IDE, should a user get a notification saying that connection to a server and ws agent has been lost? Right now, nothing happens.

If I stop just ws container, then in the IDE, the workspace is correctly stopped. But if a server container goes down the IDE does not notify a user.

@TylerJewell @vparfonov wdyt?

**Comment by TylerJewell** [comment]
Are you stopping the containers on the command line with docker client?

I would consider this a type of bug as our clients are supposed to proved pretty error messages to users any time an essential server side service is interrupted.

**Comment by ghost** [comment]
Yes, stopping containers `docker rm -f $(docker ps -aq)` or just stopping Docker for Windows

**Comment by TylerJewell** [comment]
Yes definitely a bug.  Severity P1 even as it is highly disruptive to user experience.

**Comment by ghost** [comment]
I will check on Linux, but on Windows it can be reliably reproduced. Samsung also hit this issue

**Comment by ghost** [comment]
Same behavior on Linux. I think our current mechanism of checking agent and ws-master availability can be improved.

Now, client pings ws-agent from time to time. If it cannot be reaches, then client sends a request to the ws-master to do the same. But since both master and agents are unavailable, the IDE does not know that there are no servers ready to handle its requests.

To sum it up, if Docker is down or there are problems with the host, the IDE and a user have no clue that Che has been stopped.

**Comment by svor** [comment]
What a text message should we show for users if it happens? @TylerJewell @eivantsov

**Comment by TylerJewell** [comment]
@svor - do we have any standard notification message that we show for when the agent and the client are normally disconnected?  I am wondering if it makes sense to just reuse the existing message, as this is just another variation of the same, or if we should have a special purpose message for this particular scenario.

**Comment by svor** [comment]
@TylerJewell 
When the agent is down:
 _"Workspace agent is no longer responding. To fix the problem, restart the workspace"_  

Or when we have bad connection:
_"Workspace agent is no longer responding. To fix the problem, verify you have a good network connection and restart the workspace"_

**Comment by TylerJewell** [comment]
I think that the message "To fix the problem..." is somewhat misleading, because it implies that restarting the workspace definitely fixes the problem.  It *may* fix the problem, but we cannot guarantee that it does.

So I think we should have the following messages - wdyt?  @eivantsov ?
"A workspace agent is not responding. Restart the workspace to restart it."

**Comment by ghost** [comment]
@TylerJewell this is a message to notify a user that a workspace master is down, i.e. che-server container is down which is probably a major failure with Docker.

**Comment by TylerJewell** [comment]
So we would have two simple flavors:

"A workspace agent is not responding. Restart the workspace to restart it."
"The {Che|Codenvy} server is not responding. Your admin must restart it."

**Comment by ghost** [comment]
Yes

**Comment by svor** [comment]
OK, thanks!
