### ISSUE TITLE
Number of workplaces is limited to 30

### ISSUE THREAD

**Issue by jjHimmelreich** [eclipse-che/che#4312]
Number of workplaces that can be generated is limited to 30. According to our analysis, it is related to network segment selection by docker. 

We are looking for configuration to select network subnet for isolated docker network from che.env file.
Is it any existing configuration for this?

**Reproduction Steps:**
Create 30 workspaces. 
On creating additional one, we get error message:
"Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"

**OS and version:**    
Ubuntu 16.04

**Diagnostics:** 

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che
 Version:        5.4.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /tmp/che/data
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.4.0
 CHE_HOST:       10.26.149.106
 CHE_INSTANCE:   /tmp/che/data/instance
 CHE_CONFIG:     /tmp/che/data
 CHE_BACKUP:     /tmp/che/data/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   10.26.149.106
 Initialized:    false
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.4.0
 IMAGE_CHE=eclipse/che-server:5.4.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.4.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.4.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.4.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.4.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.4.0

**Comment by TylerJewell** [comment]
@garagatyi - please as the expert, can you assist here?

**Comment by TylerJewell** [comment]
@eHimmelreich - out of curiosity, does Codenvy give you the same error issue?  It's free for 3 users and is run with the same syntax.  "docker run codenvy/cli start".  It's a variation of Che that adds distributed networking, scalability, and authentication.  Codenvy embeds usage of Docker Swarm to overcome workspace limitations that Docker engine imposes upon us when running a single Che server.

**Comment by garagatyi** [comment]
@eHimmelreich Can you provide output of docker version ?

**Comment by jjHimmelreich** [comment]
docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by garagatyi** [comment]
Ok, looks like I spotted the issue. 
Docker bridge driver is used by default for workspaces networks. It uses predefined addresses range for network pool. It is limited to 31 network.
@TylerJewell Codenvy will hit the same problem in case it is run with default network mode. 
In case of multiple nodes overlay networking should be used. Overlay networking allows creation of 64K networks. Here is an article that confirms this [issue with bridge networking](http://loomchild.net/2016/09/04/docker-can-create-only-31-networks-on-a-single-machine/).

**Comment by jjHimmelreich** [comment]
I just made curl based script that creates 30 workspaces in my codenvy.io account. 
On 31's, I get 500 Internal server error with "You are not allowed to create more workspaces."

**Comment by garagatyi** [comment]
So here are solutions I see:
1. Use overlay network. It works right now, no code is needed to use that. Codenvy starts zookeeper for that, in case of Che it should be started separately. 
1. Add configuration of IP addresses range that are allowed for usage by docker. We will have to set this range on network creation. 
1. Improve our management of bridge networks by setting precise amount of IP addresses on network creation. This can probably allow to increase amount of concurrently running workspaces up to 12-24 times.
1. Play with configuration of networking for Che workpaces to use another network, like default  bridge.

**Comment by garagatyi** [comment]
@eHimmelreich it is due to limits on our Saas offering for users. It is allowed to have 30 workspace concurrently. Since these workspaces are not running it has no connections with docker. It is just a limit set by operations team.

**Comment by liorokman** [comment]
The problem is that if the default docker network creation algorithm is used, DockerEngine will try to find an unused network subnet. The autodetection mechanism isn't that good.

The following script fragment will create 50 docker networks with a /24 size, which can each contain 254 hosts:

```bash
for net in {1..50}; do docker network create -d bridge --subnet=172.18.${net}.0/24 net${net}  ; done
```

By explicitly controlling the subnet to be used for each network the Docker autodetection algorithm for unused address spaces is bypassed, so it becomes possible to create more than 31 networks with the default "bridge" driver. 

Instead of 172.18.x.0/24 you can use any address range in the RFC1918 range. You are basically limited only by the available address-space in RFC1918 - and by managing the address spaces across all networks on a single Docker host so that there are no overlaps.

**Comment by garagatyi** [comment]
@liorokman yes, you are absolutely correct. We can improve that and it is what I suggested in items 2 and 3 of [this comment](https://github.com/eclipse/che/issues/4312#issuecomment-284339030).
2 improves it by allowing user to provide custom IP range to choose from.
3 improves allocation in existing default range.

**Comment by TylerJewell** [comment]
I don't think I would go with your option #1 or #4, Alex.  I think that Codenvy provides that and it introduces a lot of extra management configuration for admins that we don't want to introduce within Che itself. So we would need to think about your options #2 and #3.

**Comment by donenocode** [comment]
I realise this has been stale for over a year but are there any plans to look into this?

I understand the base issue is with docker's defaults for creating networks, and there is a PR on the open source docker project to try and deal with this, but thats not production yet. The PR states it will be available in 18.06.

An option in Che to work around this docker default would be ideal.

**Comment by gorkem** [comment]
Closing this as docker support is discontinued on Che 7

**Comment by AndrienkoAleksandr** [comment]
@gorkem this issue is reproducible for kubernetes and openshift. We still have default limit on the user dashboard in 30 workspaces. If user creates more than 30, user dashboard doesn't display this workpsace at all.

**Comment by sleshchenko** [comment]
@AndrienkoAleksandr It's another issue https://github.com/eclipse/che/issues/9752
