### ISSUE TITLE
Switching from alternative screen to normal screen in the terminal working incorrect after resize

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#4315]
Steps to reproduce:
1. Open terminal.
2. Type mc and Enter.
3. Resize terminal.
4. Type Ctrl + O.
Actual result: mc output still exist.
Expected result: terminal should delete mc output (output alternative screen).
Current terminal (and previous old terminal) wrong switch from alternative to normal screen. Issue related to https://github.com/sourcelair/xterm.js/issues/510

**Comment by AndrienkoAleksandr** [comment]
Can be fixed if issue https://github.com/eclipse/che/issues/5084  will be resolved.

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by AndrienkoAleksandr** [comment]
This bug was fixed for xterm.js since vesion 2.9.1. But this version contains quite critical bug https://github.com/sourcelair/xterm.js/issues/885, so I don't think we can update terminal while this bug is not fixed...

**Comment by AndrienkoAleksandr** [comment]
Fixed after update xterm.js to version 3.3.0.
