### ISSUE TITLE
"New Java Package" dialog is displayed after workspace was stopped

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4316]
**Reproduction Steps:**

- Create any Java project 
- Go to the Java folder 
- Click right mouse button on the Java folder -> New -> Java Package
- Wait until dialog will be displayed
- Stop workspace 
- Pay attention to the screen

  
**OS and version:**    

**Che version:** 5.5.0
**OS and version:** Ubuntu 16.04
**Docker version:** 1.31.1
**Che install:** Docker container

Additional information
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
See the attachment:

![anim](https://cloud.githubusercontent.com/assets/22724619/23605549/d8a3619a-0265-11e7-9484-8a60207d5994.gif)

**Comment by vzhukovs** [comment]
I think it's not a bug, this use hasn't implemented yet.
