### ISSUE TITLE
Machine section should not appear without recipe in the stack import tab

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4317]
A Machines section is visible while create a workspace from the Stack Import before import a recipe

**Reproduction Steps:**
Create a new workspaces from the **Stack import** tab:

- **"Workspaces"** -> **"Add workspace"**.
- In the workspace settings click tab **"Runtime"** -> **"Stack import"**

**Expected behavior:**
A **"Machines"** section should not appear because a recipe was not imported yet

**Observed behavior:**
The **"Machines"** section with settings from a **Ready-to-go Stacks** stack is appeared

**Che version:** 5.5.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container
![anim](https://cloud.githubusercontent.com/assets/7760565/23604850/128276e2-0263-11e7-9010-78dd0c728483.gif)

Additional information:
Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by riuvshin** [comment]
@ashumilova  please take a look

**Comment by ghost** [comment]
Probably this issue does not make sense with the recent UD changes. Feel free to reopen though if there's a similar problem in the new flow.
