### ISSUE TITLE
superdevmode using IntellijI

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4323]
Hi, i'm trying to run superdevmode using IntellijI but when i click on **Dev Mode On** i have this message : **Can't find any GWT Modules on this page.**
![capture du 2017-03-06 14-21-50](https://cloud.githubusercontent.com/assets/25527572/23611666/8c9d8362-0278-11e7-87b1-48d5869d4942.png)
![capture du 2017-03-06 14-22-57](https://cloud.githubusercontent.com/assets/25527572/23611667/8c9df202-0278-11e7-8fd9-88ba1e979a0f.png)

**Comment by ghost** [comment]
@ahmedchemek you need to navigate to localhost:8080/che/$ws-name

**Comment by ahmedchemek** [comment]
@eivantsov should i run the custom assembly that i alread build using docker ?

**Comment by ahmedchemek** [comment]
@eivantsov , before navigating to localhost:8080/che/$ws-name what command to use to run che ?

**Comment by ghost** [comment]
@ahmedchemek there is no need to mount your custom assembly. But there's nothing wrong with doing it either.

**Comment by ahmedchemek** [comment]
@eivantsov so i run che using this : docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/eclipse/che:/data eclipse/che:5.0.0 start

**Comment by ghost** [comment]
Why 5.0.0?

**Comment by ahmedchemek** [comment]
@eivantsov because it's release version

**Comment by ghost** [comment]
The latest tag is 5.4.0

**Comment by ahmedchemek** [comment]
release ? @eivantsov

**Comment by ghost** [comment]
Yes, the latest release is 5.4.0

You may drop tag, and the CLI will automatically use the latest tag

**Comment by ahmedchemek** [comment]
i haven't understand how can i customize eclipse che when it's running normally and without running the custom one @eivantsov

**Comment by ghost** [comment]
If it's superdevmode and client code, you specify your custom plugin and a local jar is used.

**Comment by ahmedchemek** [comment]
the last thing to ask @eivantsov:
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock \
                    -v < local-path >:/data \
                    -v  < local-repo >  :/repo \
                       eclipse/che:<version> start --debug
what **local-repo** refers to ?

**Comment by ghost** [comment]
To /repo

**Comment by ahmedchemek** [comment]
@eivantsov where i found this repo ?
