### ISSUE TITLE
After stop and run workspace the editor tabs was not restored

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4327]
**Reproduction Steps:**

- Go to editor and open some tabs
- Go to dashboard and stop workspace 
- Run workspace 
- Click on workspace link in the dashboard -> "Open" button
- Wait until workspace will be running
- Pay attention to the editor field

**OS and version:**    
**Che version:** 5.5.0
**OS and version:** Ubuntu 16.04
**Docker version:** 1.31.1
**Che install:** Docker container

Additional information
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
See the attachment:

![anim](https://cloud.githubusercontent.com/assets/22724619/23614146/a4b57af6-028a-11e7-9ea0-a7ceeb45ddc7.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look
