### ISSUE TITLE
After deleting a file from a project its name still exists in the Recent List

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4330]
**Reproduction Steps:**

- Open any file in editor
- Delete this file
- Go to the **Edit** - > **Recent** menu

**Expected behavior:**
The recent list doesn't show the deleted file name

**Observed behavior:**
The deleted file name is still in the recent list

**Che version:** 5.5.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container
![anim](https://cloud.githubusercontent.com/assets/7760565/23617576/385ac828-0296-11e7-8fb9-eb81f562f38c.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by slemeur** [comment]
@vitaliy-guliy + @ashumilova : I think we should take this issue in plugin team.
