### ISSUE TITLE
Run Che custom assembly

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4335]
what command to use to run eclipse che custom assembly ?

**Comment by ghost** [comment]
@ahmedchemek you need to mount your Che custom repo as:

`-v /path/to/repo:/repo` - this will mount the entire repo, including start scripts
`-v /path/to/assembly:/assembly` - this will mount just binaries

**Comment by ahmedchemek** [comment]
thank, it's solve me
