### ISSUE TITLE
Redesigned experience for managing workspaces 

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4359]
# Goals
In the past, we have unified the flows to create and edit workspaces, but it added more usability challenges to the end-user than the benefits. 
We also introduced the multi-machines workspaces which also complexified the usability of the Dashboard when it's time to configure a workspace.

The goals of this epic is to improve the user experience around creating workspaces from Dashboard and managing them. We will also rethink the loading experience and the transitions between the Dashboard and the browser IDE.

## Details

**Create Workspace flow:**
The idea is to provided a guided flow for the user when he has to create a workspace. We'll use this flow consistently in the dashboard to allow the creation of workspace (either it's a team workspace, or the first screen displayed to the user when starting Che). 

**Workspace Details:**
- We will revisit most of the forms which allow to configure a workspace. 
- We will improve agents management + multi-machine handling

**Loading Sequence**
- Replace crane loader when accepting a factory
- Analyze outputs of agents to display only relevant information to end-user (still allowing to get complete outputs)
- Provide a better loading sequence of workspaces in the IDE

### Create workspace
![1 - workspace details - settings](https://cloud.githubusercontent.com/assets/1636769/23711858/637ab310-0421-11e7-8f6d-2a4aa1924595.png)
(the widget at the bottom is showing the "Add Project" popover.)

### Workspace details

Here the goal is really to simplify the workspace details screens - especially the "Runtime" tab. 
We will split the various configuration items of the workspace into multiple tabs.

Please Note that for now, we will just rename "Workspace Config" to "RAW Config". 

#### Workspace Overview
![1 - workspace details - overview](https://user-images.githubusercontent.com/1636769/27130582-31ef50de-5107-11e7-98b3-454e38b1d07b.png)

**Note:** In the future, we can add more information into the "Overview" in order to summarize what's defined in the other tabs.

#### Workspace Machines
![1 - workspace details - machines](https://user-images.githubusercontent.com/1636769/27130587-3a04d24e-5107-11e7-9920-896c6f393bf3.png)

#### Workspace Agents
![1 - workspace details - agents v2](https://user-images.githubusercontent.com/1636769/27130597-4040e8f0-5107-11e7-93bb-abae9d1a9cf5.png)

#### Workspace Servers
![1 - workspace details - servers](https://user-images.githubusercontent.com/1636769/27130685-9be73542-5107-11e7-8bb6-855a9d9029c2.png)

#### Workspace Environment Variables
![1 - workspace details - env variables](https://user-images.githubusercontent.com/1636769/27130682-96cc3abc-5107-11e7-8d19-8155e4e04c6e.png)

### Loading sequence
refer to https://github.com/eclipse/che/issues/5231

**Comment by slemeur** [comment]
Add mockups for the workspace details

**Comment by garagatyi** [comment]
Do you have a mockup of view where one can edit the raw configuration? It may be needed for environment implementation specific syntax.
I suppose it is needed on both creation and edit steps.

**Comment by slemeur** [comment]
I didn't added a mockup for that, but it was mentioned in the description of the epic that we'll keep a "RAW Config" tab, which allow to get the json representation of the workspace and edit it - as we do today. 
I added that tab in the mockup to avoid confusion. Tks @garagatyi.

Also, when creating a workspace, you'll still have the ability to create the workspace from a JSON config. From the workspace list you'll have a button "Import workspace", there you'll be able to provide your raw configuration.

**Comment by garagatyi** [comment]
Thanks for the clarification!

**Comment by slemeur** [comment]
Done by https://github.com/eclipse/che/pull/5451 and https://github.com/eclipse/che/pull/5447
