### ISSUE TITLE
CHE-555 Preview  URL for application is wrong

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#436]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-555
Reporter:  Maxim Musienko
Description: See screenshot: !Selection_021.png|thumbnail!

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/76eca13445bb9587546db48e29a7f60c63c8dfad
