### ISSUE TITLE
Use a single port to route all traffic

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4361]
# Goals
Along with the work done for the [integration with Openshift](https://github.com/eclipse/che/pull/4269), we need to unify this mecanism for Che.

The idea would be to embed a reverse proxy in order to allow the single-port strategy.
This will likely simplify the administration and configuration of Che/Codenvy by reducing the number of port necessary using a single one.

We would also let the user being able to configure the port to get exposed .

### Linked Issues:
https://github.com/eclipse/che/issues/1560
https://github.com/eclipse/che/pull/4269
https://github.com/eclipse/che/issues/3037

**Comment by slemeur** [comment]
Linking with Traefik issue: https://github.com/containous/traefik/pull/1257

**Comment by benoitf** [comment]
for Che, it's done

**Comment by slemeur** [comment]
Excellent !
