### ISSUE TITLE
Extend the Eclipse Che editor by an new graphical editor

### ISSUE THREAD

**Issue by 19yak** [eclipse-che/che#4364]
Hello,
I am looking to develop a UML software (graphic editor containing a palette and an editor). I am looking for the different possibilities to extend the publisher Che.

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by TylerJewell** [comment]
@19yak - Eclipse Source is publishing a blog series on this topic.  
https://che.eclipse.org/emf-support-for-che-day-2-generating-code-1eb65e341c34#.ct3a2qfxm

We will also be updating all of our archetype structures very shortly to make it easier to show how you created JavaScript-based editors with graphical designs on them.

**Comment by ghost** [comment]
@19yak do you have any further questions?

**Comment by ghost** [comment]
@19yak any update please?

**Comment by ghost** [comment]
Closed due to inactivity.
