### ISSUE TITLE
Add the plugin emf4che to Eclipse Che

### ISSUE THREAD

**Issue by 19yak** [eclipse-che/che#4375]
I try to add the plug-in emf4che to Che,
in step did any own can help me.
My Eclipse Che version is 5.1.2

Finally you need to make sure the in all the POM files under /plugins/plugin-emf match with your Che version (i.e. compare with your parent POM). This includes the files:

    /plugins/plugin-emf/pom.xml
    /plugins/plugin-emf/che-plugin-emf-ide/pom.xml
    /plugins/plugin-emf/che-plugin-emf-server/pom.xml
    /plugins/plugin-emf/che-plugin-emf-shared/pom.xml

the step to run Che:
what is module that required to be builded:

    the plug-in root folder and sub-folder(emf-ide, emf-server and emf-shared)
    assembly-ide-war
    assembly-wsagent-war
    assembly-main
    che root??

**Comment by TylerJewell** [comment]
This EMF port is being handled by EclipseSource as a side project.  @JonasHelming may have some thoughts.

**Comment by 19yak** [comment]
@JonasHelming Hi, Can I know a deadline for updating the documentation for adding the emf4che plug-in to Eclipse Che?
I am a young developer, my end project studies the development of a UML plug-in for Eclispe Che.
I have many questions for the feasibility at that time of extending the editor Che by a graphical editor for UML.

**Comment by TylerJewell** [comment]
In addition to @JonasHelming fantastic work in this segment, also @dkuleshov has some particular expertise as he has built a drag and drop editor for Che in the past.  Maybe @dkuleshov can share some of the older code that used to work for more examples?

**Comment by 19yak** [comment]
@dkuleshov  Hi, I try to integrate the plugin Emf4che to be inspired but there is a problem: the plugin is updated but not its documentation.
Can I rely on HTML and JAVASCRIPT native and integrating JS graphical libraries like GoJS to develop this plug-in UML for Che.

**Comment by dkulieshov** [comment]
@19yak Hi, I guess you can take a look at CMF sources here: https://github.com/codenvy-legacy/cmf. It's been awhile since the project was stopped, but it is still a good example of how you can integrate graphical JS libraries into GWT applications (Eclipse Che)

**Comment by 19yak** [comment]
@dkuleshov Hi, CMF source is not accompanied by documentation that explains the different steps for the addition of this plug-in Che (readme file).
Can you join me the steps to test this plugin in Che.

**Comment by 19yak** [comment]
@TylerJewell @dkuleshov @JonasHelming Hi, I develop a small UML graphical editor with the following technologies: JointJS, angularJS, angular Bootstrap-ui, jquery. And when testing the addition of my editor I notice that the use of angularJS with GWT is not possible.

**Comment by ghost** [comment]
Closed due to inactivity. Feel free to reopen with questions, code snippets and any helpful information.
