### ISSUE TITLE
Superdev mode for Debugging IDE plugins

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#4377]
I am trying to setup my development environment for debugging Custom IDE plugins.

https://www.eclipse.org/che/docs/plugins/setup-che-workspace/index.html

But getting message "the code server isn't configured to compile this module"

![screenshot from 2017-03-09 15-15-32](https://cloud.githubusercontent.com/assets/2972205/23754027/d80e1612-04db-11e7-8971-23eb8017d1e1.png)
![screenshot from 2017-03-09 15-15-40](https://cloud.githubusercontent.com/assets/2972205/23754028/d811d360-04db-11e7-9a83-7bb1109672ab.png)

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by ghost** [comment]
Can you share a screenshot with your superdevmde config?

**Comment by abchakra** [comment]
I am able to correct the problem I have wrongly used <com.silexica.che.sequentialc.SequentialCExtension > instead <org.eclipse.che.ide.IDE>

-noincremental -src target/generated-sources/gen -src {path-to-your-extension}/src/main/java org.eclipse.che.ide.IDE\
