### ISSUE TITLE
Workspace agent script should not contain sudo commands

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#4381]
`org.eclipse.che.ws-agent.script.sh` contains several sudo commands for  java / tar / curl  package installations and creation of the `/projects` dir. Those sudo commands can not be executed on OpenShift online, so we had to patch stack's Dockerfile (for now is done only for vertx [1] ) in order to include packages required by ws-agent and create `/projects` directory. By doing this, no sudo commands would be run as part of the ws-agent script. This ws-agent "sudo cleanup" could be done relatively easy step-by-step without breaking stacks that would still require sudo execution from ws-agent :

- The following check should be added to the ws-agent script [2]

```
if [ ! -d "/projects" ]; then
    ${SUDO} mkdir -p /projects
    ${SUDO} sh -c "chown -R $(id -u -n) /projects"
fi
```
- Gradually stacks' Dockerfile would be patched with required instructions and both versions of stacks (sudo / non-sudo) would  be supported by the ws-agent script.  

[1] https://github.com/eclipse/che-dockerfiles/pull/70 
[2] https://github.com/eclipse/che/pull/4349/files#diff-1bf4c5348e6dab351e2402e9888727aeR39

**Comment by ghost** [comment]
@tolusha can you comment on consequences of removing sudo from the script?

**Comment by l0rd** [comment]
@eivantsov @tolusha I don't think that we want to remove sudo from the script. The goal is to avoid executing sudo commands if these are not needed (e.g. if the image has already the packages and if the folders are already created).

**Comment by l0rd** [comment]
And then adapt "official stacks" to avoid sudo commands.

The benefit would be that we can run a workspaces without the need to have root privileges in container (that's a good practice).

**Comment by ghost** [comment]
@l0rd of course all stacks that Che provides has required deps for a ws agent and terminal. AFAIK, the script checks if the required packages are installed and if they are, sudo gets never executed.

**Comment by l0rd** [comment]
@eivantsov ok so we all agree that we should avoid (when it's possible) to execute sudo commands.

That's a [sudo command](https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.script.sh#L37) that is always execuded isn't it? And the vert.x stack didn't had curl and tar so there were 2 more sudo commands needed. We are talking about improving that.

**Comment by vpavlin** [comment]
For the `/projects` dir - the best practice is to ideally use path which a user can write to, or create the directory during the image build. In any case you should `chown` and `chmod` as described in https://docs.openshift.com/enterprise/3.2/creating_images/guidelines.html#openshift-enterprise-specific-guidelines which then lets any OpenShift assigned uid to write to that dir.

**Comment by ibuziuk** [comment]
@vpavlin @l0rd  I have created PR for vertx stack - https://github.com/eclipse/che-dockerfiles/pull/75 
Could you take a look ?

**Comment by vpavlin** [comment]
Yeah, that should work fine on OpenShift - any OpenShift generated user id should be able to write to that dir
