### ISSUE TITLE
File revision/history?

### ISSUE THREAD

**Issue by kmob2** [eclipse-che/che#4382]
Hello,

I am currently using another cloud IDE, but I am considering switching. However one of the main features I really rely on, is file revisions, to get access to previously saved files.

Before I go ahead and install it Eclipse Che on my machine, does it support that feature?
If not, are there any plans to implement this? Or are there any other popular ways of keeping a backup of each file change?

Thanks.

**Comment by ghost** [comment]
@kmob2 while there is no file revision history, there's git history to track changes.

**Comment by TylerJewell** [comment]
Eclipse Che is installable, and as part of that you mount a file system where your workspaces will reside.  So you can install file revision history to manage that file system directly for you giving you the same benefit of tracking.
