### ISSUE TITLE
Extending Che's Menu bar with new item 

### ISSUE THREAD

**Issue by MuraliVidhya** [eclipse-che/che#4383]
Hi,
In Eclipse Che menu bar - where we have Git, SVN, i would like to add custom menu item with new functionality
Are there any code samples to achieve this.

Please support.

Thank you.

**Comment by ghost** [comment]
@mvidhya86 you may take a look at https://github.com/eclipse/che/blob/master/plugins/plugin-svn/che-plugin-svn-ext-ide/src/main/java/org/eclipse/che/plugin/svn/ide/SubversionExtension.java

**Comment by ghost** [comment]
@mvidhya86 does this answer your question?

**Comment by ghost** [comment]
Closed due to inactivity. @mvidhya86 feel free to reopen if you have questions about your particular plugin.
