### ISSUE TITLE
Just created terminal has incorrect name

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4392]
**Reproduction Steps:**
Start any project 
Create a new terminal

**Expected behavior:**
A new terminal appeared with "Terminal-2" name

Observed behavior:
The terminal name is "Terminal". Next created terminals have names started from "Terminal-2". 
Similar behavior happens when start a workspace or after refreshing a page.

**Che version:** 5.5.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.3
**Che install:** Docker container
![anim](https://cloud.githubusercontent.com/assets/7760565/23799548/9c7635e0-05b1-11e7-94e8-9f02dc7fdc0a.gif)

**Comment by AndrienkoAleksandr** [comment]
Main bug: terminal didn't added to the machine tree. In this issue described only side effect of this bug.
