### ISSUE TITLE
Adding dependency to IDE plugin

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#4398]
I have added following dependency to my IDE plugin , but I am not able to compile it , is this because of some dependency restrictions?

```
<dependency>
            <groupId>com.googlecode.gwt-charts</groupId>
            <artifactId>gwt-charts</artifactId>
            <version>0.9.10</version>
        </dependency>


```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireDepMgt failed with message:
com.googlecode.gwt-charts:gwt-charts:jar is not managed by dependency management
You are trying to use artifacts that are not in the list of allowed artifacts included in dependencyManagement in maven-depmgt-pom or have different version.
[I

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by ghost** [comment]
@abchakra in your root pom.xml declare this dependency.

You may want to take a look at https://github.com/eclipse/che/blob/master/pom.xml

**Comment by abchakra** [comment]
Yes this works . Thanks
