### ISSUE TITLE
Issue with Code Folding in case of Language Server

### ISSUE THREAD

**Issue by chetanladdha** [eclipse-che/che#4401]
I have my own Xtext based language server.   I can see code folding for C# but not for my DSL.
With same language server, I can see code folding in Visual Code. 

I want to know do I need to write any code/anything to enable code folding?  I could not find any documentation related to this, any link or pointer would be helpful.

**Comment by bmicklea** [comment]
@evidolob can you help here?

**Comment by evidolob** [comment]
Unfortunately Language Server Protocol doesn't have any support for  Code Folding. So yes you need to write custom language protocol extension with Code Folding support. Che use Orion editor, you can use https://orionhub.org/jsdoc/symbols/orion.editor.FoldingAnnotation.html to set foldion on some region of the text inside editor.

**Comment by chetanladdha** [comment]
@evidolob: Thanks for the reply. Do we have any example in any plugin? Any working reference would be very helpful.

**Comment by evidolob** [comment]
Unfortunately no, we don't have any example.
