### ISSUE TITLE
Module parameter in org.eclipse.che.ide.api.extension.Extension

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4404]
This parameter is a link between java code of extension and XX.gwt.xml file. In https://github.com/eclipse/che/issues/4373 we are going to reuse this parameter to generate single gwt.xml file for GWT compilation. Eventually we will generate gwt.xml only by modules from Extension annotation. Also we will have an ability to fail fast if module is not exists with nice message before actual GWT compilation

**Comment by vparfonov** [comment]
We dont need it anymore will be fixed in #6642
