### ISSUE TITLE
CHE-557 Maven command doesn't work

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#441]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-557
Reporter:  Dmytro Nochevnov
Description: _Use case_
# Open Che.
# Create sample _web-java-spring_ project.
# Create maven command:

{code}
clean install && cp ${current.project.path}/target/*.war /home/user/tomcat8/webapps/ROOT.war && /home/user/tomcat8/bin/catalina.sh jpda run
{code}
# Select created project in project explorer
# Click on execute command button in the command toolbar.

_Expected result_
IDE opens command execution console with execution log.

_Actual result_
clicking on execute command button doesn't affect on IDE.
Refresh of browser's tab fix this error.

See [attached screencast for details|https://jira.codenvycorp.com/secure/attachment/81132/out.ogv].

**Comment by ddementieva** [comment]
Cannot Reproduce
