### ISSUE TITLE
[INFO] java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor

### ISSUE THREAD

**Issue by abchakra** [eclipse-che/che#4410]
Downloaded: https://maven.codenvycorp.com/content/groups/public/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar (41 KB at 46.9 KB/sec)
[INFO] Compiling module org.eclipse.che.ide.IDE
[INFO] [ERROR] Unexpected internal compiler error
[INFO] java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
[INFO] 	at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:165)
[INFO] 	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:41)
[INFO] 	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:36)
[INFO] 	at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:100)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:352)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	... 19 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Che IDE :: Parent .................................. SUCCESS [  9.541 s]
[INFO] Che Workspace Agent War Packaging .................. SUCCESS [ 15.115 s]
[INFO] Che Assembly Workspace Agent Server ................ SUCCESS [  3.758 s]
[INFO] Che IDE :: Compiling GWT Application ............... FAILURE [01:13 min]
[INFO] Che IDE :: Compiling WS Master WAR ................. SKIPPED
[INFO] Che IDE :: Assemblies Tomcat ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:42 min
[INFO] Finished at: 2017-03-13T19:52:07+01:00
[INFO] Final Memory: 148M/1315M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.0:compile (default) on project assembly-ide-war: Command [[
[ERROR] /bin/sh -c '/usr/lib/jvm/java-8-oracle/jre/bin/java' '-Xss512m' '-Xmx2048m' 'com.google.gwt.dev.Compiler' '-logLevel' 'INFO' '-war' '/home/chakraborty/slx/che/assembly/assembly-ide-war/target/assembly-ide-war-5.5.0-SNAPSHOT' '-localWorkers' '1' '-XfragmentCount' '-1' '-sourceLevel' '1.8' '-gen' '/home/chakraborty/slx/che/assembly/assembly-ide-war/target/.generated' 'org.eclipse.che.ide.IDE'
[ERROR] ]] failed with status 1

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
Reproduction Steps:
?

**Comment by chakraborty-slx** [comment]
I am not able to reproduce this issue after git pull and rebuild.
