### ISSUE TITLE
Unexpected exceptions after deleting a project (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4414]
**Reproduction Steps:** Create a maven project, open console, delete project. Wait a few seconds.
![selection_030](https://cloud.githubusercontent.com/assets/1640058/23895572/e3231300-08ae-11e7-9573-30add7260375.png)

**OS and version:**    Ubuntu 14 TLS, chrome browser

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by SkorikSergey** [comment]
Exception after renaming a project with **.git** folder:
![selection_017](https://cloud.githubusercontent.com/assets/7760565/23991631/a8c2d9da-0a42-11e7-95b5-2227ec9eee74.png)
![anim](https://cloud.githubusercontent.com/assets/7760565/23991641/af2b8c40-0a42-11e7-8ff2-61bba3c914a7.gif)

**Comment by slemeur** [comment]
I can reproduce this on 5.8.0.
