### ISSUE TITLE
Improvements for intelligent commands - P2 

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4417]
# Goals
The goal of this issue is to polish intelligent commands UX and UI similarly to the issue #4295 
This issue covers the various feedbacks received during the beta.

## UX Improvements
- [x] **Goal improvement**
- Clicking everyone on the dropdown must expand the list of choices. At this moment, user has to click only on the `v` arrow which is not convenient.
- We need to get ride of the ability to edit in the dropdown to create a new goal. We will list all the existing commands and have the last choice "New Command Goal...". If the user clicks on it, we will display a popup with title "New Command Goal" with a textfield and buttons [Create] [Cancel]. (when the popup is opened, the textfield is having the focus, so user can directly input)

- [x] **Shortcut for default "Run" and "Debug" commands**
Would suggest `cmd+R` for "Run" and `cmd+D` for "Debug"

- [x] **Properly close the command toolbar**
When the user stops a process from drop down the tab in process panel does not close.

- [x] **Previews dropdown menu not working**
Some areas in the dropdown are not allowing to select the preview.

- [x] **Add tooltip for process ID in command toolbar**

- [x] **Refreshing the browser or reopening the workspace should reopen previous command's editors**

- [x] **Properly clean the list of previews when a command is stopped**
QA reported situations where the list of previews is not cleaned after the commands have been stopped.

# UI improvements
- [x] **Light theme**
We need to adopt the light theme for the command toolbar:
![screen shot 2017-03-14 at 11 27 34](https://cloud.githubusercontent.com/assets/1636769/23896331/4ef05508-08a9-11e7-962a-b7e30a940128.png)

- [x] **Don't display editor details**
We are displaying `UTF-8 text/x-sh` in command line + preview editors. This is not necessary.

**Comment by azatsarynnyy** [comment]
This issue has been separated to #4442 and #4590 
And fixed by related PRs #4611 #4700 #4707
