### ISSUE TITLE
Integrating JoinJS library in Che View

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4419]
Hi, i'm developping a plugin for eclipse che and i want to integrate JoinJS library into a view, but i don't know how to do it... any help please ????

**Comment by ghost** [comment]
@ahmedchemek if you want community to help you, please be more precise in what you are trying to achieve and what have you already tried.

**Comment by ghost** [comment]
Closing as duplicate of https://github.com/eclipse/che/issues/4494
