### ISSUE TITLE
Inject text/code to the editor area 

### ISSUE THREAD

**Issue by eladc898** [eclipse-che/che#4421]
I want to open some html file(not the json file)in the editor area(where the files are currently opening) with double click on the json file.
I did it in the INFORMATION (console) area, but in the EDITING area I didn't succeeded.
Any idea anyone?
-->

**Comment by ghost** [comment]
@eladc898 can you please elaborate? It is definitely not clear what you are trying to achieve.

**Comment by eladc898** [comment]
openPart(helloWorldPresenter, PartStackType.**EDITING**);
where does the area of the EDITING should open?
I have tried some feature and it didn't affect the EDITING part, but works for INFORMATION part.

Elad

**Comment by azatsarynnyy** [comment]
@eladc898 Part Stack EDITING (central part) designed for editors only. It can't contain any Part. You can provide your Editor for your File Type and it will be opened in central area.

**Comment by eladc898** [comment]
@azatsarynnyy 
Can you help me with some example of user Editor?

**Comment by azatsarynnyy** [comment]
Sure.
You need to provide your file type. The documentation is [here](https://eclipse.org/che/docs/plugins/code-editors/index.html) and **sample-plugin-filetype** is [here](https://github.com/eclipse/che/tree/master/samples/sample-plugin-filetype).
And bind it with your editor. Simple example of difining your own editor is [here](https://github.com/eclipse/che/tree/master/samples/sample-plugin-json/che-sample-plugin-json-ide/src/main/java/org/eclipse/che/plugin/jsonexample/ide/editor).

**Comment by azatsarynnyy** [comment]
There're more examples of implementing editors in Che:
[ImageViewer](https://github.com/eclipse/che/blob/0e8b21ad3ff5da80a7a03ddf3f0b281cc3594dcb/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/imageviewer/ImageViewer.java)
[OrionEditorPresenter](https://github.com/eclipse/che/blob/035c3fe63f11d4d4e9e48379be21f032a024c086/plugins/plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorPresenter.java)

**Comment by eladc898** [comment]
Thanks
I will review the examples

**Comment by ghost** [comment]
@eladc898 do you have any further questions?

**Comment by eladc898** [comment]
not at the moment

**Comment by ghost** [comment]
Closing the issue. Feel free to reopen if you have more questions.
