### ISSUE TITLE
Factory accept not fully finished when in inactive window

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#4427]
When factory opens link in new tab, and user does not switch to this tab and let it load in the background, no projects are cloned and actions performed. See att.  Also no keyboard shortcuts are present.
![factory_nonono](https://cloud.githubusercontent.com/assets/1651062/23943456/383d4bde-0978-11e7-9c4e-136ab47845c1.png)

**Comment by evidolob** [comment]
Cannot reproduce in 9c8b763 version
