### ISSUE TITLE
Add machine user token to workspace runtime response

### ISSUE THREAD

**Issue by voievodin** [eclipse-che/che#4429]
Token itself is per-workspace per-user secret used to access workspace machine agents such as _workspace-agent_, _terminal-agent_ or _exec-agent_.

The idea is to include the token field into the _workspace.runtime_ so it looks like defined by #3778
```json
{
    "runtime" : {
        "userToken" : "machine0123456789abcdef"
    }
}
```

- The token must be dynamically calculated and added to the responses of corresponding `WorkpsaceService` methods for those users who call those methods. Along with that links returned by `WorkspaceService` must not include authentication token so it's going to be up to the client whether to use them with token or not. 
- The token must be added to IDE `AppContext` and reused in the places where requests to agents are sent or websocket connections are established

These changes allow to simplify the implementation of authentication logic and make response of _workspace.runtime_ clearer and lighter.

Needed for #3778

**Comment by garagatyi** [comment]
Closing it since it was implemented in SPI branch
