### ISSUE TITLE
Unexpected errors in the ws-machine console during test of the Language server (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4431]
**Reproduction Steps:** 
This easy to reproduce with CheckMainFeatureForLanguageTest. Note! Tests - pass. Because base features with autocomplete works as expected

**OS and version:**    Ubuntu 14.0 TLS, chrome browser
![selection_031](https://cloud.githubusercontent.com/assets/1640058/23948077/1ce23748-098a-11e7-88cf-01e3ef65a6b6.png)

**Comment by ghost** [comment]
C# LS is being re-worked, so closing the issue.
