### ISSUE TITLE
Plugin-docker is not a plugin

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4432]
Plugin-docker in our current vision is not a plugin. It's more like implementation of infrastructure layer. We would like to rename this plugin and move out from ```plugins``` folder. We are thinking about 
```
/che
/che/agents
/che/plugins
/che/infrastructure  
/che/infrastructure/docker 
```

Need for https://github.com/eclipse/che/issues/4403

**Comment by skabashnyuk** [comment]
Depends on https://github.com/eclipse/che/issues/4736

**Comment by gazarenkov** [comment]
I would say it can be closed.

**Comment by skabashnyuk** [comment]
will be fixed in spi branch
