### ISSUE TITLE
CHE-559 After creation a new machine in existed workspace output is empty

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#444]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-559
Reporter:  Maxim Musienko
Description: 1. Go to machine perspective and try to create a new machine
_Wrong:_ We should watch output - info about creation new machine but nothing happend. For a user this may be confusing

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/1c45ad6e2fe362746e669b12b4a0ac7529ecc5fb
