### ISSUE TITLE
Improvements for intelligent commands - P2 - UX Improvements

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#4442]
## UX Improvements
- [x] **Goal improvement**
- Clicking everyone on the dropdown must expand the list of choices. At this moment, user has to click only on the `v` arrow which is not convenient.
- We need to get ride of the ability to edit in the dropdown to create a new goal. We will list all the existing commands and have the last choice "New Command Goal...". If the user clicks on it, we will display a popup with title "New Command Goal" with a textfield and buttons [Create] [Cancel]. (when the popup is opened, the textfield is having the focus, so user can directly input)

- [x] **Shortcut for default "Run" and "Debug" commands**
Would suggest `cmd+R` for "Run" and `cmd+D` for "Debug"

- [ ] **Properly close the command toolbar**
When the user stops a process from drop down the tab in process panel does not close.

- [x] **Previews dropdown menu not working**
Some areas in the dropdown are not allowing to select the preview.

- [x] **Add tooltip for process ID in command toolbar**

- [x] **Refreshing the browser or reopening the workspace should reopen previous command's editors**

- [ ] **Properly clean the list of previews when a command is stopped**
QA reported situations where the list of previews is not cleaned after the commands have been stopped.

**Comment by azatsarynnyy** [comment]
> Properly close the command toolbar

after discussion with @slemeur decided to skip it since the current behaviour is OK
> Properly clean the list of previews when a command is stopped

isn't reproduced
