### ISSUE TITLE
How to use SelectionChangedHandler

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4445]
I want to make possible that everytime I change project, I get a notification. This is a code snippet that I tried but it doesn't work. 

    public class SelectionChangedUpdater implements SelectionChangedHandler{
	
	private NotificationManager notificationManager; 
	private EventBus 			eventBus; 
	private EventService 	    eventService; 
	
	@Inject
	public SelectionChangedUpdater(NotificationManager notificationManager, EventBus eventBus, EventService eventService)
	{
		this.notificationManager = notificationManager; 
		this.eventBus = eventBus; 
		this.eventService = eventService; 
		
		this.eventBus.addHandler(SelectionChangedEvent.TYPE, this);
		this.eventService.subscribe(new EventSubscriber<SelectionChangedEvent>(){
			@Override
			public void onEvent(SelectionChangedEvent event) {
				notificationManager.notify("Selection is changed ! ! !", Status.SUCCESS, DisplayMode.FLOAT_MODE);
			}		
		});
	}
	@Override
	public void onSelectionChanged(SelectionChangedEvent 
		notificationManager.notify("SELECTION IS CHANGED ! ! !", Status.SUCCESS, DisplayMode.FLOAT_MODE);
	}	
}

I am pretty sure I am not supposed to use both EventBus and EventService, but I added it to my class for testing purposes.

**Comment by vzhukovs** [comment]
Hello @ndjuric93!

You should inject into constructor only `com.google.web.bindery.event.shared.EventBus` to subscribe for events handling. You shouldn't use `EventService`.

**Comment by ghost** [comment]
I've changed but it's still the same. I've also binded it to the GinModule.
The result I expect is to get the notfication everytime I change something(preferably when I change project).
I also tried adding it to the end of the 
`void onSelectionChanged(SelectionChangedEvent event) 
`
in 
`    org.eclipse.che.ide.ext.java.client.command.mainclass.SelectNodeViewImpl`
But I just can't make it work, or understand how it's done.
