### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4446]
When I create JAVA workspace, and I want to use .cpp file in it. Autocomplete doesn't work? Not even exception is thrown in Chrome.
Is that how it's supposed to work?

**Comment by TylerJewell** [comment]
There is no C++ language server that exists in the market.  We support a subset of servers from langserver.org right now and will be adding more with each release.

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
Closing the issue.
