### ISSUE TITLE
After appearance of a context menu there is no way to select items by keyboard keys

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4448]
We need ability to select menu items by keyboard in a context menu
**Step to reproduce:**  
- Invoke context menu
- Try using the keyboard to select the menu item 

Observed behavior:
We can only select menu items using the mouse

![moving_with_keyboard_keys](https://cloud.githubusercontent.com/assets/7760565/24001438/ce420fb8-0a66-11e7-9e01-3b24763b007c.gif)

**Comment by musienko-maxim** [comment]
This problem still actual,  it may be not critical for users but it can create problems for some authotests

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
