### ISSUE TITLE
Multiple Che Servers Cleanup Wrong Workspaces 

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4452]
When running two Che servers on same docker daemon, a che server will destroy/remove workspace containers belonging to the another che server. There is currently now way based on the normalized container name to determine a workspace containers associated che server parent.

Currently working on fix in [fix-cleanup-2-che-servers-560 branch](https://github.com/eclipse/che/compare/fix-cleanup-2-che-servers-560)

**Comment by ghost** [comment]
Maybe you just lack RAM?

**Comment by JamesDrummond** [comment]
I don't think it's the problem with ram. I think it is has something to do with running codenvy and che on the same docker daemon. When only che or codenvy at any given time I no longer have this issue. Can someone use both che and codenvy on same docker daemon with ws running in each to see if they can reproduce. Is there a clean up routing the che/codenvy runs on containers with certain names? When there is a ws that it does not know about it auto destroys it. There could also be an issue with multiple che or codenvy servers running on same daemon as well.

Example docker container name ` workspace20dk10jiriqw9qu5_machinesgckw3zwlvoo0rh7_admin_dev-machine` and docker image name `eclipse-che/workspace20dk10jiriqw9qu5_machinesgckw3zwlvoo0rh7_admin_dev-machine`

**Comment by ghost** [comment]
Codenvy cleaner kills Che ws containers as it thinks they are orphaned.

**Comment by JamesDrummond** [comment]
We should provide a different naming scheme where the server name is included like `workspace20dk10jiriqw9qu5_machinesgckw3zwlvoo0rh7_admin_dev-machine_codenvy_codenvy_1`. I am pretty sure che also kills codenvy ws too. Also, two codenvy servers or two codenvy servers on the same docker daemon would kill each other ws containers.

**Comment by ghost** [comment]
You cannot have 2 Codenvy installations on one server. But otherwise, you are right. I wouldn't say it's a bug though since 2 Codenvy installations on one Docker daemon has never been a use case that we keep in mind. 2 Che installations - yes, possible - Che farm with servers on different ports. But I think there's already a similar issue. @TylerJewell and @garagatyi and myself were actively discussing it but I cannot find it now.

**Comment by garagatyi** [comment]
Multiple CHEs would do the same.

**Comment by garagatyi** [comment]
@eivantsov https://github.com/eclipse/che/issues/4178

**Comment by garagatyi** [comment]
Fixes #4178

**Comment by slemeur** [comment]
@skabashnyuk I let you add the severity label on this issue.

**Comment by ghost** [comment]
Closing the issue after discussion in a related PR
