### ISSUE TITLE
"ipconfig" , "ipconfig", "ip addr" etc commands are not being recognized at terminal

### ISSUE THREAD

**Issue by SumanSaurabh44** [eclipse-che/che#4453]
Stack environment:
1. java+ubuntu+tomcat+sql
2. java+CentOs

Issue Description: Unable to get IP of my virtual machine using commands like ipconfig, ifconfig or ip addr 

Steps to reproduce:
1. Go to the terminal 
2. enter following commands
#ipconfig 
#ifconfig 
#ip addr

Expected output: Ip address should be listed on terminal console
Actual output: bash: ip : command not found

**Comment by ghost** [comment]
Can you elaborate on why you need these commands and what blocks you from running them on the host or doing docker inspect on a container?

**Comment by SumanSaurabh44** [comment]
I have Client (java code on eclipse neon on my laptop) and server (java code on eclipse che at codenvy). I am not able to establish the connection between them because full access of virtual servers (CentOs+java or Ubuntu+java) are restricted.

**Comment by ghost** [comment]
You may install packages yourself as a workaround

**Comment by SumanSaurabh44** [comment]
What all packages needs to be installed in order to have full virtual server (Linux) access? My understanding is that when I choose a stack like (CentOS+ java), I should get full access of Centos.

**Comment by ghost** [comment]
No, you need to install packages yourself. Your workspace is a Docker container, not a VM.

**Comment by SumanSaurabh44** [comment]
Can you please provide me name of the packages and  steps to install required packages in order to have full access to virtual server.

**Comment by TylerJewell** [comment]
You need to google it. It is appropriate for you to do more research and investigation on these matters.

**Comment by ghost** [comment]
`sudo apt-get install net-tools -y` will install it for an Ubuntu container. I think CentOS is the same: `yum install net-tools -y`

**Comment by SumanSaurabh44** [comment]
I tried the below commands but still I have the same issue. I am unable to install any required packages. Please help me in resolving that.
sudo apt-get install net-tools -y
yum install net-tools -y

**Comment by ghost** [comment]
I just tried installing net-tools on Ubuntu and ifconfig as well as ip ad sh worked for me.

**Comment by ghost** [comment]
Closing the issue.
