### ISSUE TITLE
Use of exec-maven-plugin:exec:java with System.exit() kills build silently

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#4458]
In many project, for example in /che/assembly/assembly-ide-war/pom.xml, we use the exec:java goal of the maven plugin "exec-maven-plugin".
In this particular instance, the maven plugin call org.eclipse.che.util.GwtXmlGenerator. This main class catches exceptions and call System.exit(1). Since the exec:java goal does not start a separate VM to execute the main class, this immediately terminates the maven process. 
The problem is much worse when using the Eclipse IDE, since in that case, the System.exit() happens inside the process that runs the IDE. Basically, running an incremental build reilably terminates the IDE.
I see three options:
1. Don't use the exec-maven plugin, but instead write mojos like DtoGeneratorMojo, for example
2. Don't call System.exit(), but instead throw an exception. I would expect the exec:java goal to catch excptions and handle them properly.
3. Use exec:exec instead of exec:java

**Comment by tsmaeder** [comment]
This is a total blocker for me and anyone using Eclipse.

**Comment by davidfestal** [comment]
it happens I had this quite a few times also.

**Comment by skabashnyuk** [comment]
Will be fixed by #4373

**Comment by tsmaeder** [comment]
True for the GwtXmlGenerator, but there are other classes using System.exit() in Che.

**Comment by sunix** [comment]
Any updates on this bug ? many Che developers are suffering from that ...

**Comment by skabashnyuk** [comment]
No progress. If you can, please propose pr.
