### ISSUE TITLE
Support window container based workspace

### ISSUE THREAD

**Issue by javagg** [eclipse-che/che#4460]
Has anyone scceeded in creating a recipe that is based on window container(nano server or windowcoreserver)?

**Comment by TylerJewell** [comment]
We are not aware of anyone who has done this testing yet.  We have been very eager to give this a try but priorities have just not allowed us the time to set things up yet.  We would appreciate any notes you can paste into this thread on what you experience while trying a recipe.

**Comment by ghost** [comment]
I'll label this as an enhancement which is likely to be closed though.
