### ISSUE TITLE
Javascript file not refreshed

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4469]
Hi, i'm injecting native javascript code from javascript file, when i make changes in the javascript file and compile with superdevmode, it load the last javascript file loaded and don't take the changes !!! how can i load every time the last javascript file ???

**Comment by ghost** [comment]
@ahmedchemek i think yo need to be more specific here. Also, please note that browser may aggressively cache previous Javascript. So, trying in an incognito tab/window is always a good idea.

**Comment by ahmedchemek** [comment]
@eivantsov 

I have done these steps :
1- I linked Sample-Plugin-EmbedJS to Eclipse Che.
2- I launched the superdevmode.
3- The new view is displayed and everything is fine.
4- I made changes in the file helloworld.js
5- I compiled by clicking on "Dev Mode On" then "Compile"
6- I always get old content of helloworld.js
7- I refresh but i have also the old content of helloworld.js

**Comment by ghost** [comment]
@ahmedchemek the way it is currently implemented, the JS file is a 3rd party URL for GWT not part of GWT resources.

If you want to be able to user superdevmode and see changes after recompiling, here's what you may want to try: have this js as part of GWT resources:

```
public interface JsResources extends ClientBundle {
final JsResources INSTANCE = GWT.create(JsResources.class);
@Source("public/helloworld.js")
TextResource firstScript();
}
```
And then inject it:

```
ScriptInjector.fromString(JsResources.INSTANCE.firstScript().getText()).inject();
```

**Comment by ghost** [comment]
@ahmedchemek were you able to try it this way?

**Comment by ahmedchemek** [comment]
@eivantsov no, every time i rebuild my extension then i rebuild assembly-ide-war then assembly-main

**Comment by ghost** [comment]
Well, this is the way this sample is authored now, and helloworld.js is not part of GWT resources.

**Comment by ghost** [comment]
Closing the issue - the original question has been answered and default behavior explained.
