### ISSUE TITLE
Debug panel displays variables of C++ project in broken view

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4470]
**Reproduction Steps:**
1. Create workspace from _C++ stack_ and import project https://github.com/dmytro-ndp/simple-cpp-project into it.
1. Open **hello.cc** file and set breakpoint at line _12_.
1. Make project and run **gdbserver** by executing the command:
`cd ${current.project.path} && make && gdbserver :8000 ./a.out`
1. Wait until command panel opens and there is message `Listening on port 8000` appears.
1. Create debug configuration for _gdb_ and start debug.
1. Wait until notification popup `Remote debugger connected` appears.

**Expected result**
There is next info displayed in **Variables** section of _Debug Panel_ in the following view:
```
this = 0x7fffffffe9fe
name = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
  _M_p = 0x7fffffffea10 "man"}, _M_string_length = 3, {_M_local_buf = "man\000\377\177\000\000q\021@\000\000\000\000", _M_allocated_capacity = 140733200621933}}
```

**Actual misleading result**:
![screenshot from 2017-03-17 19 30 41](https://cloud.githubusercontent.com/assets/1197777/24057514/48f980a8-0b50-11e7-9a5d-c89f1a43331c.png)

**Screencast**:
![out_fixed](https://cloud.githubusercontent.com/assets/1197777/24096320/e1dd59aa-0d69-11e7-8a45-97ac2f79a31d.gif)

**OS and version:**    
Ubuntu 14.04 LTS
Browser: Chrome Version 55.0.2883.87 (64-bit)
Che version: 5.6.0-SNAPSHOT.
Revision: 4c3bd9321c65dd7f

**Diagnostics:**

**Comment by ghost** [comment]
Closing as cannot reproduce:

![image](https://user-images.githubusercontent.com/5337267/28055094-26972dd2-6620-11e7-8949-1e0712a60177.png)

Tested with 5.15-SNAPSHOT
