### ISSUE TITLE
MacOS Sierra  - Mount docker.sock

### ISSUE THREAD

**Issue by ahpetrot** [eclipse-che/che#4473]
<!--- 

Using docker-machine .  Tried in both default and eclipse-che box same result on a 16.10 Ubuntu and MacOS .

Ubuntu was a fresh install of docker-machine.

~ docker run  eclipse/che start
INFO: Welcome to Eclipse Che!
INFO:
INFO: You are missing a mandatory parameter:
INFO:    1. Mount 'docker.sock' for accessing Docker with unix sockets.
INFO:    2. Or, set DOCKER_HOST to Docker's location (unix or tcp).
INFO:
INFO: Mount Syntax:
INFO:    Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...
INFO:
INFO: DOCKER_HOST Syntax:
INFO:    Start with 'docker run -it --rm -e DOCKER_HOST=<daemon-location> ...'
INFO:
INFO: Possible root causes:
INFO:    1. Your admin has not granted permissions to /var/run/docker.sock.
INFO:    2. You passed '--user uid:gid' with bad values.
INFO:    3. Your firewall is blocking TCP ports for accessing Docker daemon.

MacOS Serris 10.12.3

Other boxes and containers seem to run fine.

**Comment by TylerJewell** [comment]
This is not an appropriate issue ticket.  You must provide full reproduction steps.  Consider reopening the ticket with full details.
