### ISSUE TITLE
Real Time Collaboration

### ISSUE THREAD

**Issue by ConProgramming** [eclipse-che/che#4474]
I was wondering if anyone has a good guide to setup real time collaboration? I saw some online, but none were very good. Help would be appreciated.

**Comment by TylerJewell** [comment]
What do you mean by 'real time collaboration'?  That is a broad topic that covers 100s of possible things.

**Comment by ConProgramming** [comment]
By real time collaboration I mean pair programming in a google docs type way, where you can do things like  see another user type.

**Comment by TylerJewell** [comment]
There is a pull request for this capability - https://github.com/eclipse/che/pull/2131.  You would need to build a custom assembly of Che that includes this enhancement.  We'll be doing more testing on it later this year.
