### ISSUE TITLE
After starting a workspace sometimes  projects and commands aren't visible in the IDE (regression)

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4479]
Sometimes a workspace starts not correctly. There are no project and commands visible in the IDE and after refreshing a page they appears. 
List of tests that are failed because of this problem:
- ProjectStateAfterRefresh
- ProjectStateAfterWorkspaceRestart
- WorkingWithNodeWsTest
- WorkingWithJavaMySqlStackTest
- CheckExpressStackTest
- CheckCodeigniterStackTest
- CheckSwiftStackTest
- CheckLaravelStackTest
- CheckRailsStackTest
- CheckSymfonyStackTest

![swift_refresh](https://cloud.githubusercontent.com/assets/7760565/24093784/4939b582-0d5e-11e7-8fde-ecb3e9a822f9.gif)

![1](https://cloud.githubusercontent.com/assets/7760565/24093560/26109518-0d5d-11e7-9b36-ccbf5e3ccb11.png)

**Comment by ibuziuk** [comment]
@amisevsk  seems to be upstream for - https://issues.jboss.org/browse/CHE-134

**Comment by TylerJewell** [comment]
@skabashnyuk @ashumilova @slemeur @vkuznyetsov @vparfonov - I am labeling this as a blocker.  This showed up for Brad at a conference.  It seems that when you are in the cloud where there is more resources this issue does not happen as often as a situation where you are on a laptop with constrained resources.

TLs - we need to consider this for current sprint, or if we cannot do it that fast, next sprint.

**Comment by SkorikSergey** [comment]
This bug is not reproduced in revision f9511af4d2fbe043.

**Comment by amisevsk** [comment]
@SkorikSergey Are you sure? The bug does not occur 100% of the time. I see it on maybe 10% of workspace creations.

I'm a little uncertain of closing it without a commit to reference as a fix.

**Comment by slemeur** [comment]
@amisevsk:  which version are you using? could you describe your environment?
@SkorikSergey: could you describe on which environment and how you tried to reproduce the problem? 

@amisevsk: we are about to do a new release. Would be helpful if you'll try to reproduce it with this upcoming version.

**Comment by SkorikSergey** [comment]
Before release the intelligent commands this bug often occurred during tests. For now this bug is not reproduced. I will try to reproduce it in a new release.
**OS and version:**
**Che version:** 5.6.0
**OS and version:** Ubuntu 16.04
**Docker version:** 1.31.1
**Che install:** Docker container

**Comment by amisevsk** [comment]
@SkorikSergey @slemeur Most of the time I'm running off of the openshift-connector branch, which is based off of 5.5.0. Since the bug was always really intermittent for me, I don't have time to try reproduce it on the current master, so the issue can remain closed and I'll reopen it if it looks like it's still a problem. 

I took a quick look through the commits since 5.5.0 and nothing looks like it would have affected the bug -- the issue was not in creating the project resources, just the project explorer display not showing those resources until the page was reloaded.

**Comment by ibuziuk** [comment]
still reproducible on openshift-connector branch
