### ISSUE TITLE
Add --che and --codenvy options for CLI build/run of archetypes

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#4484]
Add options --che --codenvy for CLI archetype run and build commands, for specifying what assembly to work with. If none declared, use Che as default

**Comment by mkuznyetsov** [comment]
@TylerJewell We're figuring out how to make --che/--codenvy work with build command, how to tell what modules to exclude from building.

First, `mvn clean install -pl '!assembly-che'`  wouldn't work, as it doesnt exclude modules recursivelly, so only parent will be excluded
As there is no easy way to exclude a list of submodules through `-pl` (as they vary from sample to sample, also cannot use wildcards).

Using maven profiles to specify different list of modules in parent doesn't work, as archetype, when generated, appends a list of all modules, which is then "merged" with the one from profile during build.

We found this solution:

mvn clean install -pl `com.sample.che:assembly-main` --am

it says to build main assembly, as well as projects that are required by it. So it should cover all existing samples, as all artifacts that are built go into assembly-main, So problem can be if user creates a module that doesn't go into assembly main

**Comment by TylerJewell** [comment]
Why do we need to deal with maven module selection?  The Che assembly is located in `/assembly-che` and the codenvy assembly is in a different folder.  Why not just `cd <folder>` and then `mvn clean install` from that working directory?

**Comment by mkuznyetsov** [comment]
I presume, that build should build everything, not only assembly.

Parent pom and other modules (depending on sample, `agents` in agent sample, `plugins` in plugin-xxx sample) will be omitted if we are bulding assembly-che/codenvy folders only.

**Comment by TylerJewell** [comment]
That feels like it's over thinking hte problem :)

I think of the Che assembly and the Codenvy assembly as two different assemblies and the `build` command should only ever build one of them.  It will never build both.

So a build is ALWAYS in the sub-directory of one of the assemblies.  So the `--che` and `--codenvy` flags are just simple flags to indicate which folder is the working directory.

**Comment by mkuznyetsov** [comment]
ok, let's look at this, user generated archetype, which has following structure:
- assembly-che
- assembly-codenvy
- plugins
- pom.xml

if he then proceeds to build of `assembly-che`, it will skip parent pom here and plugins modules.
Would even fail if he havent build them before.
So I think concept of "building all needed for Che/Codenvy" depending of chosen flag is more obvious

**Comment by TylerJewell** [comment]
Ok - I see your point.  Ok, then I think the first step is that you should update the `che-archetypes` repository with an instruction for how to build Che or Codenvy only using maven commands, with a skip module command.  And then just apply that into the CLI second.

**Comment by mkuznyetsov** [comment]
So, you agree with the following command and it's downside (it will skip modules that don't go into assembly-main)

`mvn clean install -pl com.sample.che:assembly-main --am`

Or the other way, we can list all modules for exclusion like this.

`mvn clean install -pl `!com.sample.che:assembly-main,com.sample.che:assembly-ide-war,com.sample.che:assembly-wsmaster-war`

but list will vary from sample to sample, so requires some hardcode in CLI

**Comment by TylerJewell** [comment]
The simplest approach is probably the best approach.

**Comment by mkuznyetsov** [comment]
@TylerJewell would it make sense if none flag specified, then build all (do simple mvn clean install).
I can see usage of it, if user wants to rebuild everything

**Comment by TylerJewell** [comment]
No - there is no need to build both. Just wastes time and makes system seem slow.

**Comment by mkuznyetsov** [comment]
commited in Che cli-archetype branch,
--che & --codenvy flags for build & run/stop commands
https://github.com/eclipse/che/commit/5a1a5dd369a5a51694b2051fb804f97ca3e3630b
https://github.com/eclipse/che/commit/8550165597f01d98085689f8742d3c2bdb5a172f
