### ISSUE TITLE
Adding host entry to che container

### ISSUE THREAD

**Issue by vinu** [eclipse-che/che#4491]
Hi 

I am trying to run che with this command
`docker run -it --add-host foo:176.2.3.1 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/chedata:/data eclipse/che start`

che starts good, but I was expecting 176.2.3.1 foo to be added to the /etc/hosts of the che container, but it is not happening. Any idea why?

thanks

**Comment by TylerJewell** [comment]
Yes.  The main docker image for Che is stateless.  It does not run the Che server itself.  It instead generates a docker compose file which is used to run a different image which is the Che server.   

You can see this compose syntax in the instance folder.  It is generated on every run.

Why are you looking to pass hosts into the Che image?

**Comment by vinu** [comment]
@TylerJewell thanks for the explanation 
I am trying to run che behind https using nginx reverse proxy, I have adjusted the che server tomcat server.xml to have the proxy port and scheme to https. 

and configured another system as nginx reverse proxy to do the ssl termination and forward to 8080 and other websocket ports on the che server

So i have to start the che sever with CHE_HOST=public host name, but just before the project creation the che server application tries to connect to the wsagent on http://CHE_HOST:randomport/, I am not sure why it is http, but nevertheless I needed that ping to pass so the project creation can pass, so I had to add a dummy hosts entry to the che container for CHE_HOST with the ip of the host machine, and ping passes.

**Comment by TylerJewell** [comment]
@vinu - I think the approach that you are taking is going to cause a number of issues with how browsers route to the backend workspaces.

So you have three options:
1. You can go in and modify the `docker-compose.yml`, but then any changes you make here will be lost if you try to re-run the CLI.  

2. You can consider upgrading to Codenvy which provides security built in with a sophisticated URL routing strategy with built in security, TLS for SSL, and authentication. It is installed the same way as Che and is free for three users, too.

3. Or you can try playing with this prototype - which works to handle all URL routing (other than SSH) through a single port.  It embeds a traefik proxy to achieve this basic capability.  https://github.com/eclipse/che/pull/4440.  This one, does require recompiling Che and building some custom images to make this work until it is merged.

**Comment by vinu** [comment]
Thanks @TylerJewell I will have a look at the options, but with the current setup - I added the hosts entry manually to the che container ;) - it is all working good, I created a simple util program to connect to the docker daemon and it updates the nginx config  whenever a container comes or goes down.

**Comment by TylerJewell** [comment]
Ha!  Ok, then - cool hack.
