### ISSUE TITLE
Developping extensions to newest Che version

### ISSUE THREAD

**Issue by ahmed-jelassi11** [eclipse-che/che#4493]
I recently migrated to the **_5.5.0 version of che_** and I did notice a lot of changes on some modules especially the `assembly-ide-war` .
So how we can develop **extension** for this new version and how to use **_SuperDev_** mode if there is no more GWT modules for the IDE?

**Comment by TylerJewell** [comment]
@ahmed-jelassi11 - I've added the platform team.  We are going through a deep restructuring of the module structure to decentralize the GWT components into their respective plugins and to no longer require a centralized one.  This makes everything easier to maintain and faster to compile.

I am not a superdev mode expert, so there is probably a change in the way you have to source libraries as a result of this.  This document is in a PR that will be merged that introduces the new way in which people will work with custom assemblies.  We have archetypes and a CLI to support this in testing now.

https://github.com/eclipse/che-docs/blob/04a9d61dff4d55a42a593973f50d06c8f6806240/src/main/_docs/assemblies/assemblies-lifecycle.md

**Comment by vparfonov** [comment]
@ahmed-jelassi11 You should build firstly `assembly-ide-war` after in `generated-sources` you can find generated GWT module

**Comment by ahmed-jelassi11** [comment]
@vparfonov I'm asking how can I bind the custom plugins to the `assembly-ide-war` where the IDE.gwt.xml doesn't exist anymore.

**Comment by vparfonov** [comment]
@ahmed-jelassi11 You need to add dependency  to your pom.xml, try to follow https://github.com/eclipse/che-docs/blob/04a9d61dff4d55a42a593973f50d06c8f6806240/src/main/_docs/assemblies/assemblies-lifecycle.md#include

**Comment by chakraborty-slx** [comment]
I am getting this error 


chakraborty@intus:~/slx/che$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock  -v /home/chakraborty/slx/che_work/archetype:/archetype -v /home/chakraborty/cheData:/data -v /home/chakraborty/.m2/repository:/m2 eclipse/che-cli:5.4.0 archetype generate


WARNING: No swap limit support
INFO: (che cli): 5.4.0 - using docker 17.03.0-ce / native
WARN: Newer version '5.5.0' available
ERROR: You passed an unknown command.

USAGE: 
  docker run -it --rm <DOCKER_PARAMETERS> eclipse/che-cli:5.4.0 [COMMAND]

**Comment by TylerJewell** [comment]
That CLI command is only available in a branch that has to be built separately.  

https://github.com/eclipse/che/pull/4179

**Comment by chakraborty-slx** [comment]
So at this point what is the working Guide for Developing extensions ? For master is the docs https://www.eclipse.org/che/docs/plugins/create-and-build-extensions/index.html still applicable ?

I saw you have already requested merge for the cli-archetype branch to master, should i wait for it to merge ?

**Comment by TylerJewell** [comment]
We are transitioning to a new approach for assembly development which makes things simpler.  The extnesion model is not changing however.  The archetype capability in the CLI is also available on the maven command line: https://github.com/eclipse/che-archetypes.

The link @vparfonov provided was a branch where the extension docs are getting refactored.

**Comment by ghost** [comment]
@AChakraborty1982 can this issue be closed now?

**Comment by chakraborty-slx** [comment]
For me it is fixed i m not sure about @ahmed-jelassi11 who is actual creator for the issue

**Comment by chakraborty-slx** [comment]
I have another question regarding the archetype 
# Build project
mvn clean install

current build both the che and codeenvy module, which take twice the time, can we skip one of them , as I might run one one version

# Run this Che assembly
./run.sh --che

**Comment by ghost** [comment]
`--che` should build just Che. Isn't is so in your case?

**Comment by chakraborty-slx** [comment]
to build  === mvn clean install --che ????

this is to run===  ./run.sh --che

**Comment by chakraborty-slx** [comment]
Reactor Summary:
[INFO] 
[INFO] Plugin Embed JavaScript :: Parent pom .............. SUCCESS [  2.088 s]
[INFO] Plugin Embed JavaScript :: Plugins ::  Parent ...... SUCCESS [  0.025 s]
[INFO] Plugin Embed JavaScript :: Plugin Embed JavaScript :: Parent SUCCESS [  0.028 s]
[INFO] Plugin Embed JavaScript :: Plugin Embed JavaScript :: IDE SUCCESS [  6.108 s]
[INFO] Plugin Embed JavaScript :: Che Assembly :: Assembly Parent SUCCESS [  0.031 s]
[INFO] Plugin Embed JavaScript :: Che Assembly :: Assembly Parent SUCCESS [05:17 min]
[INFO] Plugin Embed JavaScript :: Che Assembly :: Assembly Parent SUCCESS [ 10.806 s]
[INFO] Plugin Embed JavaScript :: Codenvy Assembly :: Assembly Parent SUCCESS [  0.070 s]
[INFO] Plugin Embed JavaScript :: Codenvy Assembly :: Compiling GWT Application SUCCESS [05:44 min]
[INFO] Plugin Embed JavaScript :: Codenvy Assembly :: Assemblies Tomcat SUCCESS [  8.648 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:30 min
[INFO] Finished at: 2017-03-22T22:09:50+01:00
[INFO] Final Memory: 113M/1314M
[INFO] ------------------------------------------------------------------------

**Comment by chakraborty-slx** [comment]
Both Che Assembly and Codenvy Assembly are build, if this is default behaviour ?

**Comment by ghost** [comment]
It shouldn't be. Will investigate

**Comment by mkuznyetsov** [comment]
@AChakraborty1982 this will be a feature for the CLI archetype build command (using flags --che/--codenvy to build everything for Che/Assembly only). Old `build.sh` will not be updated, as it is going to be removed.

As of now, you can try building like this (using `--am` flag to tell maven to build main Che assembly and it's requirements):
`mvn clean install -pl 'com.sample.che:assembly-main' --am`

**Comment by chakraborty-slx** [comment]
Reactor Summary:
[INFO] 
[INFO] Plugin ServerService :: Parent pom ................. SUCCESS [  2.144 s]
[INFO] Plugin ServerService :: Plugins ::  Parent ......... SUCCESS [  0.023 s]
[INFO] Plugin ServerService :: Plugin :: Parent ........... SUCCESS [  0.025 s]
[INFO] Plugin ServerService :: Plugin :: Server ........... SUCCESS [  6.147 s]
[INFO] Plugin ServerService :: Plugin :: IDE .............. SUCCESS [  5.959 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Parent SUCCESS [  0.031 s]
[INFO] Plugin ServerService :: Che Assembly :: Workspace Agent War Packaging SUCCESS [  3.246 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Workspace Agent Server SUCCESS [  4.076 s]
[INFO] Plugin ServerService :: Che Assembly :: Compiling GWT Application SUCCESS [09:02 min]
[INFO] Plugin ServerService :: Che Assembly :: Assemblies Tomcat SUCCESS [ 37.418 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:02 min
[INFO] Finished at: 2017-03-23T15:18:43+01:00
[INFO] Final Memory: 107M/1475M
[INFO] ------------------------------------------------------------------------

**Comment by chakraborty-slx** [comment]
Compiling GWT Application is taking too much time, is there any way to reduce it 
I am using Intel® Core™ i7-4710MQ CPU @ 2.50GHz × 8  with 16GB RAM.

**Comment by chakraborty-slx** [comment]
[INFO] Reactor Summary:
[INFO] 
[INFO] Plugin ServerService :: Parent pom ................. SUCCESS [  1.829 s]
[INFO] Plugin ServerService :: Plugins ::  Parent ......... SUCCESS [  0.042 s]
[INFO] Plugin ServerService :: Plugin :: Parent ........... SUCCESS [  0.029 s]
[INFO] Plugin ServerService :: Plugin :: Server ........... SUCCESS [  6.050 s]
[INFO] Plugin ServerService :: Plugin :: IDE .............. SUCCESS [  6.067 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Parent SUCCESS [  0.042 s]
[INFO] Plugin ServerService :: Che Assembly :: Workspace Agent War Packaging SUCCESS [  3.543 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Workspace Agent Server SUCCESS [  4.500 s]
[INFO] Plugin ServerService :: Che Assembly :: Compiling GWT Application SUCCESS [06:53 min]
[INFO] Plugin ServerService :: Che Assembly :: Assemblies Tomcat SUCCESS [ 16.100 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:18 min (Wall Clock)
[INFO] Finished at: 2017-03-23T15:30:40+01:00
[INFO] Final Memory: 99M/1246M
[INFO] ------------------------------------------------------------------------



When i ran send time with 
mvn clean install -pl 'com.silexica.sequentialc.che:assembly-main' --am -TC8

**Comment by ghost** [comment]
Try `Dgwt.compiler.localWorkers=2` or `Dgwt.compiler.localWorkers=3` This way permutations will be executed in parallel.

**Comment by skabashnyuk** [comment]
Agree with @eivantsov 
This is my
```
MAVEN_OPTS=-Xms256m -Xmx2g -Djava.net.preferIPv4Stack=true -Dgwt.compiler.localWorkers=2
```
I think you can play with 4 localWorkers

**Comment by TylerJewell** [comment]
We document these nuances in the wiki about how we develop internally - https://github.com/eclipse/che/wiki/Development-Process

**Comment by chakraborty-slx** [comment]
export MAVEN_OPTS="-Xms256m -Xmx2g -Djava.net.preferIPv4Stack=true -Dgwt.compiler.localWorkers=2"

mvn clean install -pl 'com.silexica.sequentialc.che:assembly-main' --am



[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Plugin ServerService :: Parent pom ................. SUCCESS [  2.259 s]
[INFO] Plugin ServerService :: Plugins ::  Parent ......... SUCCESS [  0.030 s]
[INFO] Plugin ServerService :: Plugin :: Parent ........... SUCCESS [  0.024 s]
[INFO] Plugin ServerService :: Plugin :: Server ........... SUCCESS [  4.257 s]
[INFO] SLX :: SequencialC :: IDE .......................... SUCCESS [  4.141 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Parent SUCCESS [  0.018 s]
[INFO] Plugin ServerService :: Che Assembly :: Workspace Agent War Packaging SUCCESS [  2.197 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Workspace Agent Server SUCCESS [  2.655 s]
[INFO] Plugin ServerService :: Che Assembly :: Compiling GWT Application SUCCESS [06:27 min]
[INFO] Plugin ServerService :: Che Assembly :: Assemblies Tomcat SUCCESS [ 14.213 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:58 min
[INFO] Finished at: 2017-03-23T16:22:52+01:00
[INFO] Final Memory: 103M/838M
[INFO] ------------------------------------------------------------------------


20 Seconds improvement

**Comment by skabashnyuk** [comment]
Can you share your code?

**Comment by chakraborty-slx** [comment]
There is no change in the project generated using plugin-serverservice-archetype
except a name change in the pom.xml for IDE

**Comment by skabashnyuk** [comment]
With disabled  assembly-codenvy in parent pom I have

Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz Linux
MAVEN_OPTS=-Xms256m -Xmx2g -Djava.net.preferIPv4Stack=true -Dgwt.compiler.localWorkers=4

```
INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Plugin ServerService :: Parent pom ................. SUCCESS [  1.634 s]
[INFO] Plugin ServerService :: Plugins ::  Parent ......... SUCCESS [  0.025 s]
[INFO] Plugin ServerService :: Plugin :: Parent ........... SUCCESS [  0.024 s]
[INFO] Plugin ServerService :: Plugin :: Server ........... SUCCESS [  3.596 s]
[INFO] Plugin ServerService :: Plugin :: IDE .............. SUCCESS [  3.010 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Parent SUCCESS [  0.016 s]
[INFO] Plugin ServerService :: Che Assembly :: Workspace Agent War Packaging SUCCESS [  1.695 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Workspace Agent Server SUCCESS [  2.468 s]
[INFO] Plugin ServerService :: Che Assembly :: Compiling GWT Application SUCCESS [02:27 min]
[INFO] Plugin ServerService :: Che Assembly :: Assemblies Tomcat SUCCESS [ 10.325 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:51 min
[INFO] Finished at: 2017-03-24T09:42:12+02:00
[INFO] Final Memory: 96M/830M
[INFO] ------------------------------------------------------------------------
```


OSX 2,7 GHz Intel Core i5
MAVEN_OPTS=-Xms256m -Xmx2g -Djava.net.preferIPv4Stack=true -Dgwt.compiler.localWorkers=2
```
[INFO] Plugin ServerService :: Parent pom ................. SUCCESS [  5.731 s]
[INFO] Plugin ServerService :: Plugins ::  Parent ......... SUCCESS [  0.154 s]
[INFO] Plugin ServerService :: Plugin :: Parent ........... SUCCESS [  0.108 s]
[INFO] Plugin ServerService :: Plugin :: Server ........... SUCCESS [ 10.183 s]
[INFO] Plugin ServerService :: Plugin :: IDE .............. SUCCESS [  7.284 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Parent SUCCESS [  0.071 s]
[INFO] Plugin ServerService :: Che Assembly :: Workspace Agent War Packaging SUCCESS [  4.524 s]
[INFO] Plugin ServerService :: Che Assembly :: Assembly Workspace Agent Server SUCCESS [  6.073 s]
[INFO] Plugin ServerService :: Che Assembly :: Compiling GWT Application SUCCESS [05:47 min]
[INFO] Plugin ServerService :: Che Assembly :: Assemblies Tomcat SUCCESS [ 14.990 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:37 min
```
So I think your result is expected. It's happened because now you are recompiling ide with all plugins.
In this issue https://github.com/eclipse/che/issues/4403 we are working on two concept ***Basic*** and ***Full*** assembly. In theory if you are going to compile your plugin with minimal IDE it can save ~30% of time on GWT compilation.

**Comment by chakraborty-slx** [comment]
That would be a solution which can solve this delay, I also saw in the docs you have mentioned that in future we can create CHE plugins inside CHE, that would be the perfect solution.
"Building Che Extensions In Che Coming Soon"

**Comment by skabashnyuk** [comment]
@AChakraborty1982 is anything else what we can do for you? Can we close this issue?

**Comment by chakraborty-slx** [comment]
yes we can close this issue, most of my concepts are cleared !!!
