### ISSUE TITLE
Loading native javascript file

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4494]
Hello, I want to add the library joint.js to my extensio that I am currently developing. I inserted the file joint.js under the folder ~ / resources / public but when I run eclipse che this file does not load

**Comment by TylerJewell** [comment]
We document an example of how to do this here - https://www.eclipse.org/che/docs/plugins/embed-htmljs/index.html.

**Comment by ahmedchemek** [comment]
@TylerJewell This is not detailed, I want to add a Javascript library that will be loaded when opening Eclipse Che. How can I do that?

**Comment by TylerJewell** [comment]
This is what we have documented.  I would take a look inside the code base for other examples.  Otherwise, engineers may be slow to respond.

**Comment by ghost** [comment]
@ahmedchemek the example that @TylerJewell mentions is actually worth studying. It's a simple one, but definitely shows a way to execute JavaScript on IDE opening or when calling certain functions.

**Comment by ghost** [comment]
Closed due to inactivity.
