### ISSUE TITLE
[Factory] Renaming .codenvy.json

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4498]
In Che, the `.codenvy.json` file can't be kept.

The `.codenvy.json` file is also used in the JIRA plugin. We have customers and existing outsiders who are using the `.codenvy.json` file to instantiate factories.

Proposal would be to:
- Maintain the `.codenvy.json` file for Codenvy- but deprecate it.
- Use a similar filename for both Codenvy/Che. Could be `.factory.json` which will be extended to certain capabilities with Codenvy

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/4548
