### ISSUE TITLE
[Factory] Rename `.codenvy.dockerfile`

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4499]
For Che, we can’t keep the `.codenvy.dockerfile`.

Proposal would be to:
- Maintain the `.codenvy.dockerfile` file support for Codenvy- but deprecate it.
- Use a similar filename for both Codenvy/Che. Could be `.che.dockerfile` or `.runtime.dockerfile`

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/4548
