### ISSUE TITLE
[Factory] Remove {username} from named URL factories

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4500]
A named factory on Codenvy is attached to a username. We support the various format:
- /f?user={username}&name={factoryname} 
- /factory?user={username}&name={factoryname}
We need to remove the {username} for Che as it will be always {che}.

We can keep the `/f?user=che&name={factoryname}` but we need to handle that kind of url:
- /f?name={factoryname} 
- /factory?name={factoryname}

**Comment by skabashnyuk** [comment]
Removed ```/factory/username/factoryname``` and ```/factory/factoryname``` since they wasn't implemented

**Comment by skabashnyuk** [comment]
Decided to abandon this issue. Since we may be will need user name. We will left fake user "che".
