### ISSUE TITLE
How to create a welcomepage-like view in the editor area, like a welcome page in visual studio

### ISSUE THREAD

**Issue by javagg** [eclipse-che/che#4503]
I am developing a plugin which need to open a view in  in the editor area. This view will display some summary infomation about the current project but is not associated with any of the project files.

**Comment by ghost** [comment]
@javagg what you want to do is open a tab in the editor area? Is that correct? It does not have to be editable?

**Comment by javagg** [comment]
@eivantsov Yes, it just can show some charts and text, or even read-only previews (such as markdown)

**Comment by azatsarynnyy** [comment]
Hello @javagg. Editor PartStack (editor area) isn't intended for opening other Parts than editors.
To show some Part in an editor area you should register your FileType with an associated editor and open a VirtualFile which should have an appropriate FileType. But your editor may be represented by any widget.

**Comment by ghost** [comment]
@javagg did @azatsarynnyy's suggestion help?

**Comment by ghost** [comment]
Closed due to inactivity.
