### ISSUE TITLE
There is a possibility to rename a project with cyrillic symbols

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4509]
While renaming a projects name there is a possibility to put to name cyrillic symbols.

Che version: 5.6.0-SNAPSHOT
OS and version: Ubuntu 16.04 LTS
Docker version: 1.12.3
Che install: Docker container
![symbols_in_project_name](https://cloud.githubusercontent.com/assets/7760565/24197141/2161296c-0f09-11e7-9cdd-5e067bd8e562.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by xcariba** [comment]
But does it cause any problems? Everything seems to work fine.
It would be nice if it would be possible to create projects with cyrillic names.
The only minor problem with that is in dashboard, font, that is used in dashboard, does not contain cyrillic characters.

**Comment by ghost** [comment]
@SkorikSergey what is the actual problem with such filenames? They seem to open just fine in the editor.

**Comment by SkorikSergey** [comment]
We cannot create a project or a file with cyrillic characters but have possibility to rename. For now it is bug.

**Comment by xcariba** [comment]
So the issue is that we cannot create project with a cyrillic name, not that we can rename project to with cyrillic symbols. Probably the only thing that prohibits cyrillic names is a project name verifier in dashboard and new project wizard.

**Comment by ghost** [comment]
@SkorikSergey are you certain? I can create files with Cyrillic characters in their names.

**Comment by SkorikSergey** [comment]
Yes, it's my fault. This issue about **projects** names. Cyrillic symbols in a project name are not allowed.

**Comment by bdshadow** [comment]
according to the @xcariba 's last comment it should be allowed create project with cyrillic symbols, but the last comment by @SkorikSergey says, that we shouldn't. So how should it work?

**Comment by SkorikSergey** [comment]
Cyrillic symbols in a project name are not allowed.

**Comment by xcariba** [comment]
But it should be allowed to use cyrillic letters (and probably others, except special characters like slashes) since it works just fine and restriction is only in one ui dialog.
