### ISSUE TITLE
If the page refresh the Command Explorer closed with all commands tabs

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4514]
This is issue related with epic https://github.com/eclipse/che/issues/4511

**Reproduction Steps:**
- Create spring project
- Click on the "Commands" tab in the left panel
- Click refresh button
- Pay attention to the explorer 

**Expected behavior :**
After refresh page command explorer will be open .

**Observed behavior :**
After refresh page project explorer was opened .

**See attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24198977/ae844854-0f10-11e7-8d53-3efbec022831.gif)

**Comment by slemeur** [comment]
Agree with that bug.

Would be nice to fix it before we ship the intelligent features, but it's a P2 and can be fixed in the next sprint.

**Comment by azatsarynnyy** [comment]
Fixed

**Comment by Ohrimenko1988** [comment]
If refresh page several times , we will not had single-valued behavior .

![anim](https://cloud.githubusercontent.com/assets/22724619/25000355/a8f09556-2049-11e7-9022-090f3a111bb9.gif)

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che/commit/1428369f6b776b7f9f5844d2c68e59c0f502c616
