### ISSUE TITLE
After deleting project , project commands still present

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4515]
This is issue related with epic https://github.com/eclipse/che/issues/4511

**Reproduction Steps:**
- Go to spring project
- Delete this project
- Go to the command explorer
- Pay attention to the commands list

**Expected behavior :**
Commands will be remove with project .
 
**Observed behavior :**
Commands stay after deleting project .

**See attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24200545/1674e054-0f16-11e7-8678-2ef5ec6f5ebc.gif)

**Comment by slemeur** [comment]
Here the use case is close to issue: https://github.com/eclipse/che/issues/4512

Commands are bound to the workspace, they are not bound to projects. 
A single command can be used by multiple projects from the workspace.

When we delete a project, it'll be the responsability of the user to update the list of his commands. we can't know that in advanced for him.

Intelligent commands are not changing this behaviour - it is already working like this in the current versions of commands.

Closing as won't fix
