### ISSUE TITLE
Add new goal with existing name 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4516]
This is issue related with epic https://github.com/eclipse/che/issues/4511

In the command explorer we have folders who named on upper register , but in the edit command form in the "Goal" drop-down list we have names in the down register , and if try to type existing folder name with upper register in the "Goal" field and click "Save" button , we will see that new command was created not in this folder , but in its duplicate .
**Reproduction Steps:**
- Go to the web - java - spring project 
- Click on "Commands" tab in the left panel
- Click "+" button on any goal 
- Choose any command type
- In the opened commands editor go to the "Goal" text field and input exist goal name in upper register
- Click "Save" button .
- Pay attention to the command explorer .

**Expected behavior :**
New command will be added to the inputted goal .

**Observed behavior :**
New command was added in the new created goal

**See attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24201390/91b406c6-0f18-11e7-9f3e-7a4ea04c032f.gif)
al with inputted name .

**Comment by slemeur** [comment]
I agree with that bug.

At this moment it's not critical or blocker as we are reworking the ability to create a new goal as well. But this need to be handled as well.

I'm linking the issue with: https://github.com/eclipse/che/issues/4417

**Comment by azatsarynnyy** [comment]
Fixed by https://github.com/eclipse/che/pull/4656
