### ISSUE TITLE
[dashboard] Update the styles of inputs

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#4518]
Update the styles of inputs due to the following spec:
https://app.zeplin.io/project.html#pid=5875f7218d4086df39a3a603&sid=58ca6362295490ebed2a12eb

Prepare page in dashboard demo components with different states samples.

![image](https://cloud.githubusercontent.com/assets/1611939/26443334/9488d8cc-4140-11e7-8f0e-8779c13b5644.png)
![image](https://cloud.githubusercontent.com/assets/1611939/26443342/a0378e8e-4140-11e7-896c-41281d2170a8.png)

**Comment by olexii4** [comment]
1. After erasing the team name.
![selection_001](https://user-images.githubusercontent.com/6310786/27134392-145bd120-511e-11e7-9e4b-3ea7e33f0571.png)
2. After erasing the workspace cap.
![selection_002](https://user-images.githubusercontent.com/6310786/27134393-173888de-511e-11e7-9157-8f4276aae45f.png)
3. After team selected.
![selection_003](https://user-images.githubusercontent.com/6310786/27134397-1a071e18-511e-11e7-9488-40a0199d5210.png)
4. After adding special characters to the team name.
![selection_004](https://user-images.githubusercontent.com/6310786/27134404-1e38cf9a-511e-11e7-9e43-0a90afecd934.png)
5. After resizing to width < 960px ('xs' 
 and 'sm')
![selection_005](https://user-images.githubusercontent.com/6310786/27134409-2181076c-511e-11e7-8fb8-08b659a8bd1f.png)

**Comment by slemeur** [comment]
Great work @olexii4 ! 

I just have a question on the second screenshot, comparing to the third screenshot I don't get the state that you want to show. Could you describe it?

*Note:* You should add in your comment the description of each state you are showing, this way it will make it easier to other to easily understand ;)

**Comment by olexii4** [comment]
done
