### ISSUE TITLE
There is a error notification when create a new command after a project renaming

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4519]
This is issue related with epic https://github.com/eclipse/che/issues/4511

**Reproduction Steps:**
- Go to the spring project 
- Rename the project 
- Try to create any command

**Expected behavior :**
The new command is created

**Observed behavior** 
A error notification "Unable to create command" appeared and the command is created but is not visible in the Command Explorer.

See attachment :
![anim](https://cloud.githubusercontent.com/assets/7760565/24203474/8386ec2a-0f1e-11e7-904a-0336d0fc199f.gif)

It's looks like a new name of the project was added to the "Apply to" section of a command settings.
![anim](https://cloud.githubusercontent.com/assets/7760565/24506828/6ad0dfa2-1567-11e7-8af6-f39d318fdc3b.gif)

**Comment by slemeur** [comment]
This issues needs to be fixed before we merge.

**Comment by azatsarynnyy** [comment]
should be fixed by #4647

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
