### ISSUE TITLE
'Creating' workspace state looks a little bit measleading in Dashboard

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4522]
**Reproduction Steps:**
Open dashboard and click on **Add workspace** button.

There is **Creating** state label which could be understood as the situation when workspace is being created at the moment by system, and user should wait for a moment on status **Created**:
![screenshot from 2017-03-22 17 42 46](https://cloud.githubusercontent.com/assets/1197777/24206851/25df8c9e-0f28-11e7-80d1-aca09f7d5db8.png)

There are two variants instead which look more suitable here as for me:
- State: **New**
![screenshot from 2017-03-22 17 39 39](https://cloud.githubusercontent.com/assets/1197777/24206864/2f74dc46-0f28-11e7-915b-941469c25b71.png)

- State: **(isn't created yet)**
![screenshot from 2017-03-22 17 38 17](https://cloud.githubusercontent.com/assets/1197777/24207190/f8f7f9e0-0f28-11e7-916c-b4157520dbd8.png)

@slemeur, @TylerJewell what do you think?

**Comment by ashumilova** [comment]
+1 on New

**Comment by slemeur** [comment]
@dmytro-ndp It's a nice proposal. I'd prefer "New".

@ashumilova If this is a quick fix, let's take it. Otherwise this issue will be covered with new workspace creation flow: https://github.com/eclipse/che/issues/4359

**Comment by ashumilova** [comment]
will fix it - it's quick fix

**Comment by slemeur** [comment]
thanks

**Comment by ashumilova** [comment]
Fixed
