### ISSUE TITLE
gdbserver doesn't work in workspace with docker's privileged mode = false

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4524]
**Reproduction Steps:**
1. Start Che with environment property `CHE_DOCKER_PRIVILEGED=false`.
1. Create CPP workspace with C++ project.
1. Make C++ project and start gdbserver to debug this project by the command:
```cd ${current.project.path} && make && gdbserver :8001 ./a.out```

After that there is error message was displayed in command panel:
> gdbserver: linux_ptrace_test_ret_to_nx: Cannot PTRACE_TRACME: Operation not permited
> gdbserver: linux_ptrace_test_ret_to_nx: status 256 is not WIFSTOPPED!

![screenshot from 2017-03-22 22-40-52](https://cloud.githubusercontent.com/assets/1197777/24220713/0eed3d20-0f54-11e7-8212-7bec4d96842e.png)

At the same time **gdbserver** started correctly when Che had environment property `CHE_DOCKER_PRIVILEGED=true`.

**OS and version:**    
Ubuntu 16.06, Fedora, Linux Mint 18
Eclipse Che ver. 5.6.0-SNAPSHOT

At the same time in Ubuntu 14.04 gdbserver works correctly.

**Selenium tests**: there is test [CppProjectDebuggingTest.shouldDebugCppProject()](https://github.com/codenvy/qa/blob/master/src/test/java/com/codenvy/ide/debugger/CppProjectDebuggingTest.java#L119) which should be enabled after this issue has been fixed.

**Comment by TylerJewell** [comment]
Blocker bugs should only be reserved for data corruption or system outage issues.  This is definitely a P1.

**Comment by dmytro-ndp** [comment]
I see.

**Comment by ghost** [comment]
How are we going to solve this? I think I had this issue before. With new Docker security policies, it is what it is. I do not think this is a Che problem at all. Please see -https://github.com/docker/docker/issues/7276#issuecomment-194137403

Also, do debug a local binary, one does not need to start gdbserver at all. Just gdb is more than enough.

**Comment by dmytro-ndp** [comment]
@eivantsov: thank you for commenting on this. Could you, please, show an example of debugging C++ project without **gdbserver** withing the workspace from our C++ stack in Che by using GDB debug configuration?

**Comment by ghost** [comment]
You should check debug local binary, however, I have just checked it and the program does not stop at the breakpoint. So, it looks liek calling gdb directly also required privileged mode - http://stackoverflow.com/questions/34856092/gdb-does-not-hit-any-breakpoints-when-run-it-from-inside-docker-container

However, when running locally on Ubuntu 14.04 both methods are ok.

**Comment by ktosiek** [comment]
It seems adding --cap-add=SYS_PTRACE should work now: https://github.com/moby/moby/issues/21051#issuecomment-267433557 - can I somehow make che use that option?

**Comment by ghost** [comment]
@ktosiek right now privileged mode is the only option

**Comment by ghost** [comment]
Closing this issue. If the community or project lead we should introduce CAPs in Che env file, we will open a new issue. Otherwise, there's no Che fault here - gdb requires privileged mode or certain CAPs
