### ISSUE TITLE
How to use git via ssh using both gitlab and eclipse che in the same server

### ISSUE THREAD

**Issue by Filocava99** [eclipse-che/che#4529]
Hello.
I'm trying to clone my repository hosted on my private gitlab server on eclipse che, hosted in the same server. However I have no idea how to achieve that. I already tried adding the eclipse che private key on gitlab but I'm still getting the same problem: " can't store ssh keys. Unable to get ssh private key. "
Any suggestion?

**Comment by ghost** [comment]
Hello,

1. Profile > Preferences > SSH Keys > VCS
2. Generate key. Hostname `yourserver.com`
3. View key, copy it.
4. Save it to your gitlab account

This should do the trick.

**Comment by Filocava99** [comment]
Thank you for quick answer. Anyway, after creating the key and have added it to gitlab, if I try to import the project I get the same error. Also it doesn't display a login form to allow the cloning.

**Comment by ghost** [comment]
There should not be any login form. Can you share a screenshot with the error?

**Comment by Filocava99** [comment]
Sure. Here it is: http://prntscr.com/engi7o

**Comment by ghost** [comment]
Are you certain you have generated the key for the right host?

**Comment by Filocava99** [comment]
Yes. I used the server ip, cause I haven't a domain name.
EDIT:
I also have a default domain name set by ovh to identify the vps, but I think it isn't the problem

**Comment by ghost** [comment]
Have you restarted your workspace after that? They key will be injected after restart.

**Comment by ghost** [comment]
I just did the same and was able to clone a private ssh repo

**Comment by Filocava99** [comment]
To restart I have to stop and restart only the interessed workspace or also the others? Also, I have to do this using shell or with the web panel?

**Comment by Filocava99** [comment]
Still having the same problem. 
Quick recap:
I have generated the private key in the VCS panel. I've added it in my gitlab accaunt.
I have restarted the workspace but I can't clone the repository.
I'm using the Import->GIT panel

**Comment by ghost** [comment]
What url format is it? Do you have IP in the URL?

**Comment by Filocava99** [comment]
I'm using an ip

**Comment by Filocava99** [comment]
If you mean the domain name assigned by ovh, it something like HTTP://vps16482814.ovh.com
The series of numbers change for every vps

**Comment by ghost** [comment]
Hm.. I don't know what to suggest further. What I did is started a VM, installed GitLab there, generated a key, added it to Gitlab account and was able to clone the repo.

Can you confirm you do it this way?

https://youtu.be/efCALeYVNk4

**Comment by Filocava99** [comment]
In the workspace settings there is a section containing both public and private ssh keys. Is it relevant or indipendent from ones that I have generated?

**Comment by ghost** [comment]
No, this is the wrong one

**Comment by Filocava99** [comment]
If I give you the datas of eclipse che so you can check personally if I have done correctly? Only if you want of course :)

**Comment by ghost** [comment]
Just do exactly what I did in the video. It shold work

**Comment by Filocava99** [comment]
What video?

**Comment by ghost** [comment]
https://github.com/eclipse/che/issues/4529#issuecomment-288705577

**Comment by Filocava99** [comment]
Oh god, I don't know how I missed it... Thank you for your patience!

**Comment by Filocava99** [comment]
I resolved using the domain name assigned by ovh instead of using the server ip. Now it works.
