### ISSUE TITLE
New created commands not added to the toolbar drop-down list

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4533]
This is issue related with epic https://github.com/eclipse/che/issues/4511

**Reproduction Steps:**
- Create spring project .
- Go to the commands explorer .
- Create any command in any goal .
- Click on the command toolbar drop-down list .
- Pay attention to the commands list .

**Expected behavior :**
Command will be add to the list .

**Expected behavior :**
Command was not added to the list .

**See attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24246149/a9d3878e-0fce-11e7-80c7-db090ec418b5.gif)

**Comment by Ohrimenko1988** [comment]
After fix need to update DebugServices.stopDebuggerWithUiAndCleanUpTomcat in QA project

**Comment by musienko-maxim** [comment]
Also this actual for commands from factories and commands form workspaces that was created before this feature

**Comment by slemeur** [comment]
This is the expected behaviour.

The commands that are listed from the "run" button are the commands that are having the "Run" goal. (The same apply to "debug" button)

If the commands is added to another goal, they will be available from the command palette (other button)
