### ISSUE TITLE
Debug breakpoint disappears after the first symbol in line has been removed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4536]
Debug breakpoint disappears from left panel of editor after the first symbol in line has been removed.

**Reproduction Steps:**
![out](https://cloud.githubusercontent.com/assets/1197777/24256874/012f31b8-0ff2-11e7-815c-594a9d8e45be.gif)

**OS and version:**    
Ubuntu 14.04
Chrome ver. 57.0.2987.110 (64-bit)
Che 5.6.0-SNAPSHOT

Fixed, but need to add selenium test.
https://github.com/eclipse/che/tree/CHE-4536

**Comment by ghost** [comment]
Can be reproduced with 5.15-SNAPSHOT
