### ISSUE TITLE
no such id ：eclipse/ubuntu_jdk8

### ISSUE THREAD

**Issue by scstc** [eclipse-che/che#4538]
**Reproduction Steps:**
install workspace
**OS and version:**    
ubuntu 16.04
**Diagnostics:**
install any workspace for java , then show "no such id ：eclipse/ubuntu_jdk8"
Could not start workspace wksp-ra96. Reason: Start of environment 'default' failed. Error: no such id: eclipse/ubuntu_jdk8
how to solve?

**Comment by PKUliwp** [comment]
I have met the same error and my OS is ubuntu 14.04

**Comment by ghost** [comment]
@turing1989 `docker pull eclipse/ubuntu_jdk8`

Can you successfully pull the image? It looks like you have got problems with your local Docker or DockerHub was acting up at the moment you tried to start a workspace.

@TylerJewell I removed bug and P1 label.

**Comment by PKUliwp** [comment]
It's okey now, I didn't do any thing. Maybe something wrong with DockerHub.
