### ISSUE TITLE
Can not clone or delete some default commands .

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4540]
This is issue related with epic https://github.com/eclipse/che/issues/4511

**Reproduction Steps:**
- Create web spring project
- Go to the commands explorer 
- Click on commands as in gif .

**Expected behavior :**
All commands can clone and delete .
**User** 
Some commands not cloned and not deleted .

**See attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24288649/e6ef1e54-1086-11e7-811d-3e193fed2924.gif)

**Comment by Ohrimenko1988** [comment]
Some clarification , problem related with resize Commands Explorer . See attachment :

![anim](https://cloud.githubusercontent.com/assets/22724619/24602268/be7d0a2c-1864-11e7-8654-477c3a45e0ad.gif)

**Comment by azatsarynnyy** [comment]
fixed
