### ISSUE TITLE
IllegalStateException appears in the browser console when creating a project

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#4543]
IllegalStateException appears in the browser console each time when creating a project.

![error](https://cloud.githubusercontent.com/assets/1655894/24293701/c6b9dd62-109b-11e7-8555-f535d9f44e77.png)

**Comment by vzhukovs** [comment]
This issue should be already fixed. Check this on nightly builds.

**Comment by slemeur** [comment]
I can reproduce but the error is not the same:
![screen shot 2017-04-18 at 18 28 35](https://cloud.githubusercontent.com/assets/1636769/25141767/e66e256e-2464-11e7-9d47-9361ae844919.png)

Could you check please @vzhukovskii

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
