### ISSUE TITLE
CHE-565 Improvements on the crane design

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#455]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-565
Reporter:  Stévan Le Meur
Description: The goal is this issue is to improve the design of the crane.

We already have this implementation:
http://codepen.io/okurinnyi/pen/OMqXWq

We need to make it looking more like the new design:

(at this moment, I removed the pipeline, to simplify the implementation)

**Comment by ddementieva** [comment]
Fixed
