### ISSUE TITLE
Project explorer show folder as for unconfigured projects

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#4550]
I have an old python project that I sometime using for tests.
It made from python simple.
It shows folder with icon for unconfigured projects
I can reconfigure project , and after clicking 'save' it show normal icon.
But after browser refresh or stop/start workspace icon goes back.
Please see screenshot, it show that responsec are OK and project is configured
![unconfigured-project](https://cloud.githubusercontent.com/assets/1636620/24300305/b10d6312-10b4-11e7-9642-855a9685650a.png)

**Reproduction Steps:**

**OS and version:** Centos 7.3   Codenvy 5.5.1

**Comment by ghost** [comment]
Closing as cannot reproduce in 5.15-SNAPSHOT
