### ISSUE TITLE
Can not delete any project created by the workspace 

### ISSUE THREAD

**Issue by SancezZ** [eclipse-che/che#4551]
I create a new workspace. It uses the java-default stack.

If I try to delete this "console-java-simple" project an error appears with 
[ERROR] [a.v.i.f.LocalVirtualFileSystem 593]  - Unable delete file /projects/console-java-simple

![deleterootproject](https://cloud.githubusercontent.com/assets/1170357/24302032/7d4dd802-10b1-11e7-8045-9b07efa33197.PNG)

**Reproduction Steps:**
Create a new workspace with the java-default stack.
Try to delete this project.

**OS and version:**    
Win 8.1 Pro
Eclipse Che Tag 5.5.0 

**Diagnostics:** 
INFO: (che cli): :/assembly mounted - using assembly from local host
INFO: (che cli): 5.5.0 - using docker 17.03.0-ce / boot2docker
**CLI:**
 

- TTY:            true
-  Daemon:         /var/run/docker.sock
-  Image:          eclipse/che:5.5.0
-  Version:        5.5.0
-  Command:        info
-  Parameters:     info

**Mounts:**

-  /data:          \<userDir\>/data
-  /data/instance: not set
-  /data/backup:   not set
-  /repo:          not set
-  /assembly:      \<userDir\>/git/che/assembly/assembly-main/target/eclipse-che-5.5.0/eclipse-che-5.5.0
-  /sync:          not set
-  /unison:        not set
-  /chedir:        not set

**System:**
 

- Docker:         boot2docker
-  Proxy:          not set

**Internal:**
 
-  CHE_VERSION:    5.5.0
-  CHE_HOST:       192.168.99.100
-  CHE_INSTANCE:   \<userDir\>/data/instance
-  CHE_CONFIG:     \<userDir\>/data
-  CHE_BACKUP:     \<userDir\>/data/backup
-  CHE_REGISTRY:   /version
-  CHE_DEBUG:      false
-  IP Detection:   192.168.99.100
-  Initialized:    true

**Image Registry:**
 

- IMAGE_INIT=eclipse/che-init:5.5.0
-  IMAGE_CHE=eclipse/che-server:5.5.0
-  IMAGE_COMPOSE=docker/compose:1.8.1
-  BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
-  BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.5.0
-  UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.5.0
-  UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.5.0
-  UTILITY_IMAGE_CHETEST=eclipse/che-test:5.5.0
-  UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.5.0

**che.env:**

-  CHE_HOST=192.168.99.100

**Comment by ghost** [comment]
Should be fixed by https://github.com/eclipse/che/pull/4418

Just checked it on Windows 10 - projects can be deleted.

Can you try deleting project in the terminal?

**Comment by SancezZ** [comment]
![deleteviaterminal](https://cloud.githubusercontent.com/assets/1170357/24345349/fc21cb6e-12cf-11e7-9937-633d1c6a6f07.PNG)

Maybe its a problem on my side?

**Comment by ghost** [comment]
Hm.. this is exactly the bug that the abovementioned commit fixes. Can you try a nightly version?

**Comment by SancezZ** [comment]
this is the result of 

**docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/tmp:/data eclipse/che:nightly start**

![del2](https://cloud.githubusercontent.com/assets/1170357/24393789/c09e961a-1399-11e7-9b14-db8b29926fd9.PNG)

**Comment by ghost** [comment]
Looks like this is a boot2docker problem only.

**Comment by SancezZ** [comment]
My colleague runs also the same 5.5.0 tag on MacOS-X 10.12.3

He can delete the root project but got some NPE

![delnpe](https://cloud.githubusercontent.com/assets/1170357/24404458/dbdc7852-13c1-11e7-9772-2136ec0ca6ba.PNG)

**Comment by ghost** [comment]
@SancezZ can you open another issue since it seems to be unrelated?

**Comment by ghost** [comment]
Closed as cannot reproduce. The issues observed are Win > VM mount issues.
