### ISSUE TITLE
Machine API deprecated - How to execute a command over rest api

### ISSUE THREAD

**Issue by philipp-lein** [eclipse-che/che#4553]
In the last release the machine api removed. So how is the best practice to run a command now ?

**Comment by TylerJewell** [comment]
The Machine API was deprecated in 5.2 and removed in 5.5.  Please do some searches in the code base for how built-in extensions execute commands.  You will be able to find the syntax more quickly this way - as engineers are in a release cycle and may not pay attention to issues for a number of days.

**Comment by ghost** [comment]
@phill1234 commands are now executed by an exec agent which is deployed in a workspace machine. Here are some good docs to read - https://github.com/eclipse/che/blob/master/agents/go-agents/docs/rest_api.md

In a nutshell, this is a rest service that accept requests and returns links to subscribe to command output.

**Comment by ghost** [comment]
@phill1234 can we close the issue?

**Comment by philipp-lein** [comment]
yes thank you very much
