### ISSUE TITLE
Documentation of REST API is outdated 

### ISSUE THREAD

**Issue by philipp-lein** [eclipse-che/che#4555]
Most examples doesn´t work. 
Especially the editing File examples.
Can someone explain me how to get the content of a file over the api?
I would be very happy.
Thanks

**Comment by TylerJewell** [comment]
The SDK docs are getting a rewrite.  The new doc for this is located at https://github.com/eclipse/che-docs/tree/che-assembly-sdk/src/main/_docs/assemblies.

@mkuznyetsov @JamesDrummond - in the upcoming sprint, please add a task to review the REST page with examples and verify their accuracy.

**Comment by TylerJewell** [comment]
For the rest examples that are provided in the docs:
1. Make sure the REST snippet is provided is accurate.
2. Also provide a link to a commit in the source repo that shows how we use the same REST API in either the IDE or the UD as an example of usage.

**Comment by skabashnyuk** [comment]
>he REST page with examples and verify their accuracy.

https://github.com/eclipse/che-docs/blob/che-assembly-sdk/src/main/_docs/assemblies/assemblies-sdk-rest-apis.md  this?

>Make sure the REST snippet is provided is accurate.

What snippet?

**Comment by JamesDrummond** [comment]
Do I need api_key? If so where do I get it?

![image](https://cloud.githubusercontent.com/assets/20580888/24666185/365c4092-1925-11e7-8623-cea72795eb58.png)

**Comment by ghost** [comment]
@JamesDrummond currently it is not possible to use swagger for ws agent. The generated json should have a dynamic api endpoint, while it does not. It is tru for Codenvy.

In case of Che, everything works just fine:

`http://172.17.0.1:${ws-agent-port}/api/docs/swagger.json`

**Comment by JamesDrummond** [comment]
@skabashnyuk Can we assign this to your team? I update what I could but I think your team would be better suited for this task. Most examples do not work so it would involve someone figuring out the equivalent for the new REST api call syntax.

**Comment by skabashnyuk** [comment]
Are you talking about this
https://github.com/codenvy/codenvy/issues/2047
https://github.com/codenvy/codenvy/issues/403
or this 
https://github.com/eclipse/che/issues/4576
?

**Comment by JamesDrummond** [comment]
@skabashnyuk You got it #4576 . Thanks.

**Comment by skabashnyuk** [comment]
will try to do this sprint.

**Comment by ghost** [comment]
Docs have been updated. Commands API will be added soon. Closing the issue.
