### ISSUE TITLE
Is there any good way to save extend attributes in project or workspace for plugin developing?

### ISSUE THREAD

**Issue by Madixin** [eclipse-che/che#4557]
I want to save extend attributes in project or workspace  in my che plugin.

I could find appropriate API to implement it

**OS and version:**    
CentOS
Che5.2.2

**Comment by ghost** [comment]
@Madixin here's an example of how C and CPP project types are extended with new attributes - compilation options for a build command - https://github.com/codenvy/artik/blob/aa439cb30aee4334331e971d99344541be3fc639/plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/command/options/EditCompilationOptionsAction.java

**Comment by Madixin** [comment]
@eivantsov thanks.but I do not want create a new project type,I just want to save extend attributes for each project, such as gitlab ID or branch info where it clone from

**Comment by ghost** [comment]
In the example above, existing project types are extended.

**Comment by Madixin** [comment]
Oh thanks,I will try it next week.
Just make sure  it will not remove this attribute if user change project type?

**Comment by ghost** [comment]
If a user re-configures project type, attributes that you have added will be lost.

**Comment by Madixin** [comment]
wow.....that may be a problem.
Is there any other way?

**Comment by Madixin** [comment]
I have tested that I could use workspace attribute to save more infos for each project

**Comment by vzhukovs** [comment]
Hello @Madixin. You can create a _mixin_ type, that will holds for you your additional attributes.
We have such mechanism for **git** extension. You can see implementation of _mixin_ [here](https://github.com/eclipse/che/blob/master/wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectType.java).

**Comment by Madixin** [comment]
@vzhukovskii   Thanks
I think mixin type is a good way . However ,  I found if we could only persist these attributes into a files which in project folder,. If user delete this files ,we would lost these attributes

**Comment by ghost** [comment]
@Madixin what file do you mean?

**Comment by Madixin** [comment]
I found  "GitValueProviderFactory" and "MavenValueProviderFactory" both getValues from "FolderEntry" which could only get values from project folder.  Could wsagent service access to database?

**Comment by ghost** [comment]
This way user selection in the project tree is respected.

**Comment by Madixin** [comment]
@eivantsov   
Sorry， what do you mean?

**Comment by ghost** [comment]
Project attributes are not persisted into any files. Examples that @vzhukovskii has provided are quite self explaining.

A mixin checks the project to search for particular attributes. It may or may not be necessary. In case of maven this is pom.xml.

@vzhukovskii can elaborate

**Comment by vzhukovs** [comment]
Yes, when you extends `org.eclipse.che.api.project.server.type.ValueProviderFactory` you have instance of `org.eclipse.che.api.project.server.FolderEntry` with your project folder, where you can create any files and operate with any data you want. So, your implementation of `org.eclipse.che.api.project.server.type.ValueProvider` can store and provide value for the specific attribute name, such as gitlab ID.

**Comment by Madixin** [comment]
@vzhukovskii 
I mean user may delete this file which store attribute.  Is there any case that store in database?

**Comment by Madixin** [comment]
hi ,I have got it . It could store attributes in database .  Just add mixin type and attributes in parameter when create project

Thanks again.      @vzhukovskii @eivantsov

**Comment by ghost** [comment]
@Madixin yes, exactly. Project attributes are stored with the project an an entity, not some project files.

Can I close the issue or do you have any further questions?
