### ISSUE TITLE
Browser hangs up when moving/deleting many files in the terminal

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#4558]
**Reproduction Steps:**

1. Create node.js app.
2. npm install in `Terminal` view.
3. rm -fr node_modules/ in `Terminal` view.

 But I think this doesn't depend on Node.js.
Che-server's version is nightly image-id:3d2dcd195a90.

Log in Chrome. Looks 500 error received and wasn't caught by Promise#catch().

```
_app-0.js:17582 GET http://40.115.251.65:33189/api/project/tree/frontend?depth=7&includeFiles=true 500 (Internal Server Error)
mz @ _app-0.js:17582
nz @ _app-0.js:8740
Jqi @ _app-0.js:11255
Iqi @ _app-0.js:15048
Rqi @ _app-0.js:18368
j8d @ _app-0.js:18337
(anonymous) @ _app-0.js:11097
h8d @ _app-0.js:11136
ymf @ _app-0.js:15663
rmi @ _app-0.js:17293
pmi @ _app-0.js:17277
zmi @ _app-0.js:10787
oni @ _app-0.js:6978
qni @ _app-0.js:18368
(anonymous) @ _app-0.js:10705
_app-0.js:11095 Uncaught (in promise) Error: Internal Server Error occurred, error time: 2017-03-25 00:58:55
    at A8d (_app-0.js:11095)
    at k8d (_app-0.js:8062)
    at Sqi.Tqi [as Qp] (_app-0.js:18368)
    at _Yg (_app-0.js:17416)
    at dZg (_app-0.js:15552)
    at Sqi.kZg [as Cn] (_app-0.js:18357)
    at cz (_app-0.js:12651)
    at uz.vz [as An] (_app-0.js:18331)
    at XMLHttpRequest.eval (_app-0.js:11744)
    at Dn (_app-0.js:8218)
    at Gn (_app-0.js:11145)
    at XMLHttpRequest.eval (_app-0.js:11815)
A8d @ _app-0.js:11095
k8d @ _app-0.js:8062
Tqi @ _app-0.js:18368
_Yg @ _app-0.js:17416
dZg @ _app-0.js:15552
kZg @ _app-0.js:18357
cz @ _app-0.js:12651
vz @ _app-0.js:18331
(anonymous) @ _app-0.js:11744
Dn @ _app-0.js:8218
Gn @ _app-0.js:11145
(anonymous) @ _app-0.js:11815
```

Che server doesn't show any special messages.

```
2017-03-25 00:23:00,056[ted-scheduler-9]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
2017-03-25 00:50:54,236[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacezrjhr8li87bneas3
2017-03-25 00:50:56,527[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspacezrjhr8li87bneas3
2017-03-25 00:51:26,444[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.ssh' agent at workspace workspacezrjhr8li87bneas3
2017-03-25 00:51:26,996[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 756]    - Workspace 'che/something' with id 'workspacezrjhr8li87bneas3' started by user 'che'
```

**Comment by monaka** [comment]
My browser is Chrome  56.0.2924.110 (64-bit).

**Comment by monaka** [comment]
I got same result by executing `mv somewhere/* .`. So I changed the title of this issue.

**Comment by ghost** [comment]
@monaka I will take a look and respond. Quick question - when you delete node modules, is this directory expanded in the project explorer?

**Comment by monaka** [comment]
> is this directory expanded in the project explorer?

Yes. But in some cases it doesn't hang up even if the directory is opened. In such cases, I got 404 error [like this comment](https://github.com/eclipse/che/issues/4559#issuecomment-289187483).

**Comment by ghost** [comment]
I was unable to reproduce it locally on my Ubuntu 14.04. Are you using Che remotely?

**Comment by monaka** [comment]
@eivantsov Yes, my Che server is in Azure.
The server is located in Japan Esst. And I'm in Tokyo. Connected with the broadband.
Not LAN but not poor bandwidth.

**Comment by ghost** [comment]
@monaka I am using the default Angular sample.. maybe there aren't as many node modules there as in your project?

**Comment by ghost** [comment]
So, what I did is:

1. Started Che on a Digital Ocean Node (San Francisco)
2. My local machine is in Europe so, there's some latency
3. Created a sample Angular project
4. `npm install`
5. `rm -rf node_modules`

My browser is ok. I am using the latest Che tag which is 5.6.0 (yesterday's release).

Perhaps, it is a good idea for you to try this tag too.

**Comment by monaka** [comment]
@eivantsov Yes. There were a lot of modules in the directory.
In my just guess, this issue is occurred by huge files deletion.
It's my regular task to operate a few files in 'Terminal' tab. And I've never encountered this issue in such situation yet.

**Comment by ghost** [comment]
It is a public project that I can clone and give it a shot myself?

**Comment by monaka** [comment]
It's a private project... I'll try to setup repository that can reproduce this issue.

**Comment by ghost** [comment]
@monaka well, I cloned https://github.com/angular/angular and ran `npm install`. It took a while to populate `node_modules`. Removing this directory in a terminal was a success for me, and browser never hang.

**Comment by monaka** [comment]
Hmm... 
I think there have two points in this issue.

* The reason why "http://.../api/project/tree/frontend?depth=7&includeFiles=true" returned 500 error.
* The reason why my browser hanged.

**Comment by ghost** [comment]
@monaka please try to reproduce it with 5.6.0. There have been some fixes to project explorer.

**Comment by monaka** [comment]
@eivantsov I upgraded the latest nightly (means > 5.6.0).
Good! Good! Good! It is really faster file loading than the nightly at a week ago.
I'm going to check it more.

**Comment by monaka** [comment]
I tried file accesses by some patterns on the latest nightly.
And I couldn't reproduce this issue.
So I close this. @eivantsov  Thanks for your support.

(But it seems there have some another synchronization issues. I'll report later.)

**Comment by monaka** [comment]
Note: Probably PR #4505 fixes this.
