### ISSUE TITLE
My Chrome hangs when I'm working in Terminal tab.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#4559]
This is caused in similar situation and similar result to #4558. But different logs.
I got this issue on executing `npm install` in Terminal tab.
My environment is same as #4558.

```
_app-0.js:17188 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at gPf (_app-0.js:17188)
    at lPf (_app-0.js:10186)
    at GPf.HPf [as sl] (_app-0.js:18348)
    at eval (_app-0.js:10704)
gPf @ _app-0.js:17188
lPf @ _app-0.js:10186
HPf @ _app-0.js:18348
(anonymous) @ _app-0.js:10704
```

**Comment by monaka** [comment]
I connected to the container via ssh and executed `npm install -S sails.js.io`.
My Chrome was frozen with logs below.
Possibly this issue is also caused by file handlings?
 
```
_app-0.js:18330 Uncaught (in promise) Error: java.lang.IllegalStateException: Not a file
    at zBd.Gm [as Pm] (_app-0.js:18330)
    at zBd.Jm [as Rm] (_app-0.js:18330)
    at zBd.Em (_app-0.js:9500)
    at zBd.Mm (_app-0.js:5206)
    at zBd.Qm (_app-0.js:5207)
    at zBd (_app-0.js:5362)
    at Yc (_app-0.js:8485)
    at _mi (_app-0.js:14406)
    at ani.bni [as sl] (_app-0.js:18368)
    at eval (_app-0.js:10704)
Gm @ _app-0.js:18330
Jm @ _app-0.js:18330
Em @ _app-0.js:9500
Mm @ _app-0.js:5206
Qm @ _app-0.js:5207
zBd @ _app-0.js:5362
Yc @ _app-0.js:8485
_mi @ _app-0.js:14406
bni @ _app-0.js:18368
(anonymous) @ _app-0.js:10704
```

**Comment by AndrienkoAleksandr** [comment]
Dear @monaka, your first exception this is bag xterm.js https://github.com/sourcelair/xterm.js/issues/385 which is reproducible in Eclipse CHE https://github.com/codenvy/codenvy/issues/1836. After merge new xterm.js version this bug will be fixed https://github.com/eclipse/che/issues/4251.

**Comment by AndrienkoAleksandr** [comment]
About froze chrome tab I don't know. Bag xterm.js should not froze chrome tab. Second exception which you described it is not a terminal bag.

**Comment by AndrienkoAleksandr** [comment]
When you delete files with help terminal this external changes for our ResourceManager. ResourceManger with help file watchers on the server side synchronize this changes to display this changes in the ProjectExplorer, update list opened files and so on. Seems when you do a lot external changes with help terminal this synchronization hangs up browser tab.

**Comment by monaka** [comment]
@AndrienkoAleksandr I see. I'll try newer nightly image after merged #4251.
And I'll keep tracking "Not a file" error on #4558.

**Comment by vzhukovs** [comment]
Hello @monaka. Issue with IllegalStateException (error message "No a file") should be fixed in nightly builds, so you can get fresh sources of Che, and re-try your actions on nightly build.

**Comment by monaka** [comment]
@vzhukovskii Thank you for your good news.I'll retry it and report something to #4558.

**Comment by ghost** [comment]
@monaka it looks like the issue's gone. Can I close this issue?

**Comment by monaka** [comment]
@eivantsov Looks this issue has gone. I close this. Thanks!
