### ISSUE TITLE
File is not updated in the editor after git checkout (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#4567]
**Reproduction Steps:**
* Open a project in the IDE(e.g. web-java-spring), create local branch.
* Open a file in the editor and checkout to another local branch.
* Change content of the file and commit it.
* Checkout to master branch

**Expected behavior:**
* Content of the file should be updated immediately

**Observed behavior:**
* Content of the file is not updated
* Need to reopen file

**Che version:** 5.6.0
**OS and version:** Ubuntu 14.04
**Docker version:** 1.12
**Che install:** [Docker container]

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by mmorhun** [comment]
Fixed
