### ISSUE TITLE
CHE-567 Display the outputs with syntax coloration on the right side of the loader

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#457]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-567
Reporter:  Stévan Le Meur
Description: We need to display the outputs properly, accordingly to the design.

We will have to find ways to provide syntax coloration for the outputs.

At this moment, we will not make the link clickable.

!Screen Shot 2016-02-22 at 10.20.24.png|thumbnail!

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/04de24b206f9451645d62c78a71e01f63ad1be06
