### ISSUE TITLE
Rename command is disabled in context menu of Project Explorer within the java package

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4573]
**Reproduction Steps:**
1. Create java project with package.
1. Go to java package in the _Project Explorer_.
1. Click on right mouse button to open context menu for the package item and java class item.

**Actual wrong result**
Context menu of _Project Explorer_ has disabled "**Rename**" item
- for the package item
![screenshot from 2017-03-27 15 46 25](https://cloud.githubusercontent.com/assets/1197777/24357042/f15616ba-1304-11e7-823e-f3c16987fec0.png)

- for the java class item
![screenshot from 2017-03-27 15 46 04](https://cloud.githubusercontent.com/assets/1197777/24357036/eaa01f0a-1304-11e7-9b9a-30f7c81f02aa.png)

**OS and version:**    
Ubuntu 14.04
Chrome 57.0
Che 5.5.0
Che 5.6.0-SNAPSHOT

**Comment by vzhukovs** [comment]
It is a normal behavior, for java packages and classes we do allow only refactoring rename.

**Comment by dmytro-ndp** [comment]
User could easily decide that **Rename** operation is not supported at all for java classes or packages in IDE. So, disabled command **Rename** there should be replaced by its equivalent in context menu of _Project Explorer_, even from accessibility point. It could be, for example, **Refactoring > Rename** command, of something similar.
Also _Shift + F6_ is working perfectly despite of context menu command with this hotkey "Rename _Ctrl+F6_" is disabled.

**Comment by ghost** [comment]
Closing the issue as it does not seem to impact UX or makes the product misbehave.
