### ISSUE TITLE
CHE-566 Prototype transitions on the right side of the loader

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#458]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-566
Reporter:  Stévan Le Meur
Description: We need to prototype the animation and the transition for the right part of the loader.

!Screen Shot 2016-02-22 at 10.20.24.png!

We will have map the animation to similar ones from an accordion menu. We will keep each steps expandable/collapsable.

As an option (not mandatory to start), we would like the console being collapsible/expandable as well.

**Comment by ddementieva** [comment]
Fixed
