### ISSUE TITLE
Debug capability becomes inaccessible after the workspace has been restarted at the middle of debugging

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4582]
**Reproduction Steps:**
1. Create and open java workspace.
1. Create **console-java-simple** project.
1. Start application in debug mode and set breakpoint into the main class.
1. Create debug config and start debug.
1. Restart workspace without stopping debug session in IDE.
1. Start application in debug mode again and start debug.

**Expected behavior**
IDE clear old debug session and start new one.

**Actual wrong behavior**
Call of "**Run > Debug > Debug 'Remote Java**" top menu command doesn't affect. Debug is impossible,
There is old session metadata in the _Local Storage_ of browser.

After the cleaning old session metadata from _Local Storage_ of browser and refreshing browser, debug becomes an accessible.

**Screencast**
![out](https://cloud.githubusercontent.com/assets/1197777/24368405/fea329ba-1328-11e7-98d7-76c8345f0aa1.gif)

**OS and version:**    
Ubuntu 14.04
Chrome 57.0
Che 5.6.0-SNAPSHOT

**Comment by ghost** [comment]
Quite a nasty issue! Took me a while to figure it out.

**Comment by ghost** [comment]
Labeling as a blocker. This affects Che, codenvy.io and on-prem users.

**Comment by bmicklea** [comment]
@vkuznyetsov @tolusha please address this ASAP.
