### ISSUE TITLE
How to deploy eclipse-che on swarm?

### ISSUE THREAD

**Issue by bobowang2017** [eclipse-che/che#4583]
I was just studying eclipse-che and now my duty is to deploy eclipse-che on swarm, but I have no idea about it, who can help me ,thanks

**Comment by ghost** [comment]
@bobowang2017 you should be looking at Codenvy - which is cloud implementation of Eclipse Che with auth and scalability - https://github.com/codenvy/codenvy

**Comment by bobowang2017** [comment]
@eivantsov Thank you, But I have no idea about it, can you susseed in deployment it in swarm?

**Comment by ghost** [comment]
@bobowang2017 do you want to use swarm as an orchestrator when launching workspaces?

**Comment by bobowang2017** [comment]
@eivantsov Yes, are you have any good idea?

**Comment by bobowang2017** [comment]
@eivantsov Yes, do you have any good idea about it?

**Comment by ghost** [comment]
Che is single server. Codenvy provides swarm implementation of it.

**Comment by bobowang2017** [comment]
ok, thank you ,I will try it again

**Comment by bobowang2017** [comment]
@eivantsov ok, thank you, I will try it again
