### ISSUE TITLE
Python language server fails if Python 3.5 already installed but pip3 is not

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4586]
The problem is here - https://github.com/eclipse/che/blob/master/agents/ls-python/src/main/resources/org.eclipse.che.ls.python.script.sh#L85

In environments with Python 3.5 already installed, like Ubuntu 16.04, the script skips installation of python and pip3. As a result, ls never starts and it is impossible to open .py files since Python ls is enabled but never started.

The script should also check if pip3 is installed.

**Comment by 20avva** [comment]
pip3 might not be installed, check the outputs from starting the workspace.
