### ISSUE TITLE
error creating a standard stack. only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.

### ISSUE THREAD

**Issue by andreabisello** [eclipse-che/che#4600]
on a updated windows 10 pro
i installed the last stable version of windows docker 17.03.1-ce

then i run this command
docker run -p 8080:8080 --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v c:/data eclipse/che-server:5.0.0-latest

as described here https://eclipse.org/che/docs/setup/docker/index.html

then i try to create a php stack but there is an error

this is the log

> PS C:\Users\andrea.bisello> docker run -p 8080:8080 --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v c:/data eclipse/che-server:5.0.0-latest
> Using embedded assembly...
> Using embedded che.properties... Copying template to <no value>/conf.
> 2017-03-28 15:56:04,579[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.38
> 2017-03-28 15:56:04,581[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Oct 6 2016 20:51:55 UTC
> 2017-03-28 15:56:04,582[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.38.0
> 2017-03-28 15:56:04,582[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
> 2017-03-28 15:56:04,583[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.9.13-moby
> 2017-03-28 15:56:04,583[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
> 2017-03-28 15:56:04,583[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
> 2017-03-28 15:56:04,584[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_111-b14
> 2017-03-28 15:56:04,584[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
> 2017-03-28 15:56:04,584[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/tomcat
> 2017-03-28 15:56:04,585[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/tomcat
> 2017-03-28 15:56:04,585[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/tomcat/conf/logging.properties
> 2017-03-28 15:56:04,586[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
> 2017-03-28 15:56:04,587[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.docker.network=bridge
> 2017-03-28 15:56:04,588[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
> 2017-03-28 15:56:04,588[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/user/che
> 2017-03-28 15:56:04,589[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/tomcat/logs/
> 2017-03-28 15:56:04,589[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
> 2017-03-28 15:56:04,589[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
> 2017-03-28 15:56:04,590[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
> 2017-03-28 15:56:04,591[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
> 2017-03-28 15:56:04,591[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
> 2017-03-28 15:56:04,591[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
> 2017-03-28 15:56:04,591[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/data/conf
> 2017-03-28 15:56:04,592[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/tomcat/endorsed
> 2017-03-28 15:56:04,593[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/tomcat
> 2017-03-28 15:56:04,593[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/tomcat
> 2017-03-28 15:56:04,594[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/tomcat/temp
> 2017-03-28 15:56:04,671[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 443]  - Initializing ProtocolHandler ["http-nio-8080"]
> 2017-03-28 15:56:04,698[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
> 2017-03-28 15:56:04,700[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 397 ms
> 2017-03-28 15:56:04,726[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
> 2017-03-28 15:56:04,727[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
> 2017-03-28 15:56:04,727[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.38
> 2017-03-28 15:56:05,015[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/dashboard.war
> 2017-03-28 15:56:05,133[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/dashboard.war has finished in 117 ms
> 2017-03-28 15:56:05,135[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/ROOT.war
> 2017-03-28 15:56:05,790[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/ROOT.war has finished in 655 ms
> 2017-03-28 15:56:05,791[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/swagger.war
> 2017-03-28 15:56:05,841[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/swagger.war has finished in 50 ms
> 2017-03-28 15:56:05,842[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 911]        - Deploying web application archive /home/user/che/tomcat/webapps/wsmaster.war
> 2017-03-28 15:56:12,254[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
> 2017-03-28 15:56:12,272[ost-startStop-1]  [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.0.3 by Boxfuse
> 2017-03-28 15:56:12,274[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
> 2017-03-28 15:56:12,300[ost-startStop-1]  [INFO ] [i.f.CustomSqlMigrationResolver 153]  - Searching for sql scripts in locations [classpath:che-schema]
> 2017-03-28 15:56:12,314[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 2 migrations (execution time 00:00.015s)
> 2017-03-28 15:56:12,335[ost-startStop-1]  [INFO ] [o.f.c.i.m.MetaDataTableImpl 44]      - Creating Metadata table: "PUBLIC"."schema_version"
> 2017-03-28 15:56:12,353[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "PUBLIC": << Empty Schema >>
> 2017-03-28 15:56:12,354[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.8.1 - 1__init.sql
> 2017-03-28 15:56:12,457[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.0.0.9.1 - 1__add_index_on_workspace_temporary.sql
> 2017-03-28 15:56:12,463[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Successfully applied 2 migrations to schema "PUBLIC" (execution time 00:00.128s).
> 2017-03-28 15:56:14,342[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 975]        - Deployment of web application archive /home/user/che/tomcat/webapps/wsmaster.war has finished in 8,500 ms
> 2017-03-28 15:56:14,349[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 488]  - Starting ProtocolHandler ["http-nio-8080"]
> 2017-03-28 15:56:14,355[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 9653 ms
> 2017-03-28 15:56:41,806[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 884]    - Workspace 'che:test1' with id 'workspacevj6ywgzsfuzf3yhh' created by user 'che'
> 2017-03-28 15:56:44,939[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 660]    - org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error response from docker API, status: 500, message: create <no value>/workspaces/test1: "<no
> value>/workspaces/test1" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path
> 
> java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error response from docker API, status: 500, message: create <no value>/workspaces/test1: "<no value>/workspaces/test1" includes invalid charact
> ers for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path
> 
>         at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_111]
>         at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_111]
>         at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$4(WorkspaceManager.java:639) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) ~[che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
>         at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
> Caused by: org.eclipse.che.api.core.ServerException: Start of environment default failed. Error: Error response from docker API, status: 500, message: create <no value>/workspaces/test1: "<no value>/workspaces/test1" includes invalid characters for a local volume name, o
> nly "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path
> 
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:665) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
>         ... 3 common frames omitted
> Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: create <no value>/workspaces/test1: "<no value>/workspaces/test1" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
>  If you intented to pass a host directory, use absolute path
> 
>         at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:856) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:251) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:635) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         ... 6 common frames omitted
> Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: create <no value>/workspaces/test1: "<no value>/workspaces/test1" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
>  If you intented to pass a host directory, use absolute path
> 
>         at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:947) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:791) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         ... 8 common frames omitted
> Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: create <no value>/workspaces/test1: "<no value>/workspaces/test1" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
>  If you intented to pass a host directory, use absolute path
> 
>         at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:327) ~[che-plugin-docker-machine-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$17(CheEnvironmentEngine.java:764) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:894) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
>         ... 9 common frames omitted
> Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: create <no value>/workspaces/test1: "<no value>/workspaces/test1" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-
> Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path
> 
>         at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1324) ~[che-plugin-docker-client-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.plugin.docker.client.DockerConnector.createContainer(DockerConnector.java:1075) ~[che-plugin-docker-client-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:525) ~[che-plugin-docker-machine-5.0.0-M8.jar:5.0.0-M8]
>         at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:273) ~[che-plugin-docker-machine-5.0.0-M8.jar:5.0.0-M8]
>         ... 11 common frames omitted

![image](https://cloud.githubusercontent.com/assets/2149815/24414907/036ff7d6-13e0-11e7-92de-a37c9181b74e.png)

**Comment by ghost** [comment]
@abioneperhobby here's what you need to try:

`docker run -p 8080:8080 --name che --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/andrea.bisello/che-data:/data eclipse/che-server:5.0.0-latest`

You should mount your existing Win directory into `/data`, so it should be `-v /c/Users/andrea.bisello/che-data:/data`. `che-data` directory will be automatically created in `C:\Users\andrea.bisello`.

**Comment by andreabisello** [comment]
@eivantsov it works, thanks!
