### ISSUE TITLE
Add support to specify package while creating class

### ISSUE THREAD

**Issue by rakesh-roshan** [eclipse-che/che#4603]
When a package is empty then it is not shown in the CHE workspace. So when I have to add a file to that empty package, I have to create the class in some other non empty package then move that to the empty package.

Either show option to display empty package or, while creating a new class option of package should be provided.

**Comment by ghost** [comment]
@rakesh-roshan I cannot reproduce such behavior - just created an empty package and it is displayed there. I can create a Java class in such a package. Can you perhaps share more info on how to reproduce?

![image](https://cloud.githubusercontent.com/assets/5337267/24439646/295af2ac-1458-11e7-8e33-54bc72d61a7e.png)

**Comment by rakesh-roshan** [comment]
You created only one empty package. Create another empty package inside that empty package. Then the parent empty package will not be visible in the workspace.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
