### ISSUE TITLE
Can not create package in the java project

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4606]
**Reproduction Steps:**
- Create workspace with java stack .
- Start workspace .
- Click "Create project" link .
- Choose web-java-spring .
- Expand project tree and try to create package from context menu .
- Pay attention to the screen .

**Expected behavior :**
Package will be create 

**Observed behavior :**
Package not created

**OS and version:**    

**Che version:** 5.6.0
**OS and version:** Ubuntu 16.04
**Docker version:** 1.31.1
**Che install:** Docker container 

**Additional information :**
This issue related with https://github.com/eclipse/che/issues/4605
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
See the attachment:

![anim](https://cloud.githubusercontent.com/assets/22724619/24443551/c5cecad8-146b-11e7-849a-543e21c08c84.gif)

**Comment by musienko-maxim** [comment]
I think it is the same with https://github.com/eclipse/che/issues/4605
