### ISSUE TITLE
Move plugin-dashboard to ide core

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4614]
Without this plugin UI looks incomplete. 
<img width="216" alt="2017-03-29 14 40 09" src="https://cloud.githubusercontent.com/assets/1614429/24453031/dbeefbf8-148e-11e7-8d35-061253830401.png">
It means it's not a plugin, it's core mandatory part of ide

Need for https://github.com/eclipse/che/issues/4403

**Comment by vitaliy-guliy** [comment]
As it was discussed:
 - don't move plugin to IDE core
 - don't add the button by dashboard
 - control the navbar from the IDE directly using window messaging
