### ISSUE TITLE
Bug: equals called on same variable

### ISSUE THREAD

**Issue by wlsc** [eclipse-che/che#462]
Description of problem: Spotted a bug in PasteAction class, line 207 in the project che-core-ide-app. Equals called on the same variable
Che version: last trunk copy (commit 0235c85ab9bce05ebf5409270f8e0f4e8144766b)
Che install directory: not relevant
Docker version: not relevant
Java version: not relevant
Environment details (AWS, VirtualBox, physical, etc.): not relevant
How reproducible: 
Steps to Reproduce: find the line 207
Actual Results: if (fileDirectory.equals(fileDirectory)) {...}
Expected Results: something like if (selectedNode.getStorablePath().equals(fileDirectory)) {...}

**Comment by ddementieva** [comment]
Bug is fixed. Can you please confirm?
