### ISSUE TITLE
Not correctly work shortcuts for default "Run" and "Debug" commands (Alt+R , Alt+D)

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4625]
**Reproduction Steps:** 
- Go to spring project
- Run some command from toolbar 
- Press Alt+R 
- Create, update or move some command 
- Press Alt+R again 
- Pay attention to result 

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24461789/f06dab80-14aa-11e7-8e1d-50c109b7d3cb.gif)

**Comment by azatsarynnyy** [comment]
fixed
