### ISSUE TITLE
If click on stop/rerun button drop-dawn list will be open

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4626]
**Reproduction Steps:**
- Go to spring project
- Run some command 
- Click on rerun/stop button
- Pay attention to result 

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24462111/cbca62e0-14ab-11e7-8c92-d079d604c102.gif)

**Comment by slemeur** [comment]
That's a bad behaviour indeed. 
@azatsarynnyy could you check that please?

**Comment by azatsarynnyy** [comment]
I confirm. It's a bug with dropdown list

**Comment by azatsarynnyy** [comment]
fixed
