### ISSUE TITLE
Building custom assembly-ide-war

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#4631]
Hi, i'm trying to build my custom ide war after adding dependency to my custom extension but i have this error 
**Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.0:compile (default) on project assembly-ide-war: Command [[
[ERROR] /bin/sh -c '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java' '-Xss512m' '-Xmx2048m' 'com.google.gwt.dev.Compiler' '-logLevel' 'INFO' '-war' '/home/ahmed/workspace/che-5.4.0/assembly/assembly-ide-war/target/assembly-ide-war-5.4.0' '-localWorkers' '1' '-XfragmentCount' '-1' '-sourceLevel' '1.8' '-gen' '/home/ahmed/workspace/che-5.4.0/assembly/assembly-ide-war/target/.generated' 'org.eclipse.che.ide.IDE'
[ERROR] ]] failed with status 1
[ERROR] -> [Help 1]**

anyone can help ? thanks

**Comment by skabashnyuk** [comment]
more logoutput please. Can we take a look on your pom.xml or project itself?

**Comment by ghost** [comment]
@ahmedchemek any update please?

**Comment by ahmedchemek** [comment]
@eivantsov i think that it's caused by out of memory... each time i have this error, i clear my memory and everything be ok. thanks eivantsov
