### ISSUE TITLE
Use HTML5 clipboard api instead flash object

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#4634]
Investigate and then use HTML5 clicpboard API for text copying instead flash object.
Moreover, sometimes flash become blocked and can not be used by javascript.

![flash is blocked](https://cloud.githubusercontent.com/assets/1655894/24493409/5f536d3c-1537-11e7-8f49-26a591df803d.png)

And also there is a [bug](https://github.com/eclipse/che/issues/4296) with font smoothing in webkit browsers.

**Comment by vzhukovs** [comment]
This one is duplicated. See https://github.com/eclipse/che/issues/3186
