### ISSUE TITLE
After restarting a workspace the command explorer tab is always open

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4635]
**Reproduction Steps:**
- Open a project 
- Check the project view tab is open
- Stop a workspace and start it by Start button

**Expected behavior:**
The workspace is started and the project view tab is open

**Observed behavior:**
The workspace is started and **the command explorer tab** is open

Che version: 5.6.0-SNAPSHOT
OS and version: Ubuntu 16.04 LTS
Docker version: 1.12.3
Che install: Docker container
![anim](https://cloud.githubusercontent.com/assets/7760565/24494060/9c27b306-1539-11e7-8f47-37d2361c4470.gif)

**Comment by azatsarynnyy** [comment]
fixed
