### ISSUE TITLE
Variable values can't be reviewed when IDE steps into JRE class for debug

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4636]
**Reproduction Steps:**
1. Create and open workspace from java stack.
1. Import project https://github.com/dmytro-ndp/java-with-external-libs.git and configure it as maven project.
1. Add command "**build and debug**" to the IDE: `mvn -f ${current.project.path} clean install && java -jar -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 ${current.project.path}/target/java-with-external-libs-1.0-SNAPSHOT-jar-with-dependencies.jar`
1. Open **SimpleLogger.java** file in editor.
1. Set debug breakpoint to the line 13 with command `javaLogger.log(Level.INFO, "Info from java logger");`.
1. Execute command "**build and debug**".
1. Call top-menu command "_Run > Debug > Remote Java_".
1. Wait until execution is stopped at the breakpoint.
1. Go to _Debug Panel_ and call "**Step Into**" command.

**Expected behavior**
IDE opens class **Logger** and there are values of variables "**msg**" and "**level**" in _Variables Panel_ list.
_Evaluate Expression_ popup displays values of "**msg**" and "**level**" variables.

**Actual wrong behavior**
There were no values of variables "**msg**" and "**level**" in _Variables Panel_ list.
_Evaluate Expression_ popup displays next error message when requested values of "**msg**" and "**level**" variables:
> Error: Failed to evaluate an expression.
> Reason: {}

Server returns _500 Internal Server Error_ on address http://172.19.20.32:33739/api/debugger/6/evaluation?expression=msg

![screenshot from 2017-03-30 12 06 11](https://cloud.githubusercontent.com/assets/1197777/24496970/8ccc45c6-1542-11e7-9b61-7a1df0429279.png)

**Screencast**
![out](https://cloud.githubusercontent.com/assets/1197777/24497017/b5cced90-1542-11e7-9943-1e7708d4fc67.gif)

**Error reason**
There was **org.eclipse.che.plugin.jdb.server.expression.ExpressionException** at the server caused by **com.sun.jdi.AbsentInformationException**.

Stack trace from [this line](https://github.com/eclipse/che/blob/0e8b21ad3ff5da80a7a03ddf3f0b281cc3594dcb/plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/expression/Evaluator.java#L264):
```
[org.eclipse.che.plugin.jdb.server.expression.Evaluator.getLocalVariable(Evaluator.java:264),
 org.eclipse.che.plugin.jdb.server.expression.JavaTreeParser.primaryExpression(JavaTreeParser.java:8197),
 org.eclipse.che.plugin.jdb.server.expression.JavaTreeParser.expr(JavaTreeParser.java:7821),
 org.eclipse.che.plugin.jdb.server.expression.JavaTreeParser.expression(JavaTreeParser.java:6317),
 org.eclipse.che.plugin.jdb.server.expression.JavaTreeParser.evaluate(JavaTreeParser.java:6220),
 org.eclipse.che.plugin.jdb.server.expression.ANTLRExpressionParser.evaluate(ANTLRExpressionParser.java:41),
 org.eclipse.che.plugin.jdb.server.JavaDebugger.evaluate(JavaDebugger.java:681),
 org.eclipse.che.plugin.jdb.server.JavaDebugger.evaluate(JavaDebugger.java:674),
 org.eclipse.che.api.debugger.server.DebuggerService.expression(DebuggerService.java:199),
...
]
```

**Root problem**
There were no visible variables at all in debug thread when executing method [org.eclipse.che.plugin.jdb.server.expression.Evaluator#getLocalVariable](https://github.com/eclipse/che/blob/0e8b21ad3ff5da80a7a03ddf3f0b281cc3594dcb/plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/expression/Evaluator.java#L255-L255) 

**Selenium tests**
Test [com.codenvy.ide.debugger.DebugExternalClassTest#shouldDebugJreClass](https://github.com/codenvy/qa/blob/ac955f14036b474d004fe81f3e9cc95e429162dd/src/test/java/com/codenvy/ide/debugger/DebugExternalClassTest.java#L140-L140) should be enabled after the successful fix of this bug.

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by tolusha** [comment]
Won't be fixed due to https://github.com/eclipse/che/issues/6480
I will provide PR to remove test.

**Comment by dmytro-ndp** [comment]
Why it will not be fixed? It's still actual bug.

**Comment by tolusha** [comment]
Never!

**Comment by dmytro-ndp** [comment]
If I understand it correctly, implementing of _VS Code_ (#6480) could, potentially, fix this issue as well. So, I propose do not close this issue until we ensure this bug doesn't reproduce with _VS Code_.

**Comment by tolusha** [comment]
Expected behavior. JDK classes were not compiled with debug info. 
My proposal is to remove this usecase and close the issue.

**Comment by dmytro-ndp** [comment]
@tolusha: do we still have error message:
> Error: Failed to evaluate an expression.
> Reason: {}

IMHO, we have to fix it, at least, to have a clear meaning

**Comment by sffc** [comment]
I was getting this error in Codenvy.

> Error: Failed to evaluate an expression.
> Reason: {}

The solution is to add `-g` to `javac` line in the debug build configuration file.

It would be nice if the error message from Codenvy/Che suggested that fix.
