### ISSUE TITLE
After refresh page not restore processes list 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4639]
**Reproduction Steps:**
- Open  spring project
- Run some commands
- Refresh page 
- Pay attention to the process bar 

**Expected behavior :**
Process list will be restore 

**Observed behavior :**
Process list not restored 

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24497588/a1b1f592-1544-11e7-93b6-872a0f3a69cb.gif)

**Comment by slemeur** [comment]
Close cannot reproduce
