### ISSUE TITLE
CHE-574 After using a factory the just cloned project is not configured

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#464]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-574
Reporter:  Maxim Musienko
Description: 1. Create(or clone) maven - multimodule project
2. Create factory from the IDE (Workspace -> Create Factory)
3. Consume the factory

_Expected result:_ after workspace creation, the project should be configured as maven multimodule
_Actual result:_ The project type is not setted. In the Events console operations 'Configuring project and cloning source code.,' and 'Configuring and cloning source code' are hung.

**Comment by ddementieva** [comment]
Cannot Reproduce
