### ISSUE TITLE
Server Side Dtos generated in shared langaugeserver.shared Project

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#4640]
When building the project che/wsagent/che-core-api-languageserver-shared, DTO classes for the server side are generated in the project. This is wrong, the classes should be generated in the project che/wsagent/che-core-api-languageserver. The curent situation leads to the availability of classes like gson (which is not available in with gwt) in the ide project for the language server support.

**Comment by bmicklea** [comment]
@skabashnyuk - can you label this please?

**Comment by vparfonov** [comment]
@tsmaeder Can you elaborate more detail? It's not clear what proble you are tring to solve. FYI client-side DTO not depends on Gson it need only GWT framework, but server-side depends on Gson.

**Comment by skabashnyuk** [comment]
@tsmaeder do you want to keep this issue?
