### ISSUE TITLE
stacks.json and samples.json are not updated when upgrading Che

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4642]
**Reproduction Steps:**
- Go to dashboard
- Choose java stack and web-java-spring project
- Wait until project will be open
- Open commands explorer
- Pay attention to the commands goals

**Expected behavior :**
Commands will be create in the different goals 

**Observed behavior :**
Commands created in the one goal

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24499285/d15f9164-1549-11e7-9226-381221d144ad.gif)

**Comment by slemeur** [comment]
This is problematic. @azatsarynnyy could you please check that?

**Comment by azatsarynnyy** [comment]
It's because CHE instance **data** folder contains old **samples.json** file where goals aren't not assigned to the commands.
@Ohrimenko1988 try to delete your CHE instance's data with **che destroy** command and run it again with **che run**

**Comment by azatsarynnyy** [comment]
BTW @slemeur I'm afraid that user may not receive updated **samples.json** and **stacks.json** after upgrading his CHE to the newer version with **che upgrade**

**Comment by slemeur** [comment]
Thanks @azatsarynnyy . 
I have re-labelled the issue.

@Ohrimenko1988 : Please clarify your issue and use case. Here the problem is not related to intelligent command but about how we handle the upgrades.

**Comment by ghost** [comment]
Yes, ever since we have introduced che-cli, updates to samples and stacks is impossible if you run a new version with an existing instance folder.

**Comment by ghost** [comment]
The issue does not make sense anymore with the introduction of a new stacks loading policy.
