### ISSUE TITLE
Autocomplete into commands editor does not work after save

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#4644]
**Reproduction Steps:**
* Open a project in the IDE.
* Create a command into commands editor
* Make some changes and save them.
* Try to use autocomplete in the commands editor

**Expected behavior:**
autocomplete should work

**Observed behavior:**
* autocomplete form is open, but feature does not work

**Che version:** 5.6.0
**OS and version:** Ubuntu 14.04
**Docker version:** 1.13
**Che install:** [Docker container]

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment
![autocomplete_commands_editor](https://cloud.githubusercontent.com/assets/5408906/24501586/d0a89848-1552-11e7-83ad-0585a5bad960.png)

**Comment by slemeur** [comment]
@azatsarynnyy Could you please check this issue?

**Comment by azatsarynnyy** [comment]
@slemeur I confirm, it's reproducible on my side
