### ISSUE TITLE
Cannot edit multi-line recipe in stack

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4650]
I cannot edit the recipe in stack unless I do it through raw configuration which is one line. Not sure this was ever a feature or if this issue is an enhancement request.

![image](https://cloud.githubusercontent.com/assets/20580888/25232693/eee52326-25a1-11e7-9305-c315fb8452f4.png)

**Comment by ghost** [comment]
Recipes are not editable. You may want to open an enhancement request if you think this will be some useful functionality.

**Comment by JamesDrummond** [comment]
Labelled this as P1 as I think it is a very important enhancement. I think there will be many users trying to use an existing compose file. Expecting them to enter each machine one by one is not practical.

**Comment by ghost** [comment]
Applying existing composefile to an existing workspace?

**Comment by TylerJewell** [comment]
Enhancement requests do not get priority labels.  Please remove.

**Comment by JamesDrummond** [comment]
@eivantsov To a new stack.

**Comment by ghost** [comment]
You have got stack authoring tab where you can write your composefile.

**Comment by ghost** [comment]
The screenshot that you have attached shows an existing workspace config.

**Comment by JamesDrummond** [comment]
@eivantsov The highlighted area on image above cannot be edited only viewed. I questioned if editing this area should have been included when we came out with stack editing/creation page. I thought we had discussed it.

Editing raw configuration is not practical of course with `\n` for line breaks.

codenvy 5.7.2

**Comment by ghost** [comment]
For **existing** workspace, not a new one, correct?

**Comment by JamesDrummond** [comment]
For a stack definition to be used on a new workspace. I update image above to show you the area I am in.

**Comment by ghost** [comment]
Well, when you created this workspace, you first went to runtime > stack authoring. Where you can do edits. You cannot edit your composefile once it's parsed by UD

**Comment by JamesDrummond** [comment]
Hit show next to recipe. I will do a screen capture in just a sec an update description to issue with it.

**Comment by JamesDrummond** [comment]
@eivantsov See video below.
![capture](https://cloud.githubusercontent.com/assets/20580888/25556846/34a7d262-2cca-11e7-94ba-395d11496358.gif)

**Comment by JamesDrummond** [comment]
What's the status on this?
