### ISSUE TITLE
Modify Stack Description

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4651]
Should be able to modify stack description without having to do it in raw configuration.

![image](https://cloud.githubusercontent.com/assets/20580888/24522800/549bcf78-1556-11e7-9ae3-9307d3b944bd.png)

 Codenvy 5.5.0

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/5073/files#diff-0bc1c5f039296e0c1800d11cb676d207R49
