### ISSUE TITLE
Unexpected reset of Applicable slider after saving command

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4657]
**Preconditions:** we should have a workspace with 2 prjects
**Reproduction Steps:**
1. Open Command explorer, add a command, in the command editor disable command for a project with slider. Save it.
![anim](https://cloud.githubusercontent.com/assets/1640058/24546403/c71df8e2-1613-11e7-8af4-fcbabb7c7ea6.gif)

**Expected result:** The state of sliders should be saved.
**Actual result:** The just disabled slider unexpectedly returned to enable state.
**OS and version:**  Ubuntu 14.0 TLS, chrome browser.

**Comment by slemeur** [comment]
@azatsarynnyy Could you please check this issue?

**Comment by azatsarynnyy** [comment]
@slemeur I confirm, it's reproducible on my side
