### ISSUE TITLE
Document "Servers" in workspace stack

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#4658]
When creating a Workspace in Che, under Runtime tab, expanding Machines section allows to add "Servers" but it's not documented what it's used for. Even on https://www.eclipse.org/che/docs/workspace/stacks/index.html it seems there is no documentation.

**Comment by ghost** [comment]
Added docs label and assigned @JamesDrummond 

A few words about servers. By adding a server we will expose and publish a specified port as well as show preview URLs in user Dashboard and when using macros in Commands.

**Comment by JamesDrummond** [comment]
@slemeur  We should really relabel this in UI to "Exposed Ports".

**Comment by JamesDrummond** [comment]
@wernight I created a factory to help users contribute to docs. https://codenvy.io/f?name=che-codenvy-docs&user=jdrummond . We are coming out with factories for che this week which I will create a factory/repo for.

**Comment by wernight** [comment]
Nice! Double nice actually. I love the concept of factories. Factories are so nice that I think most people don't even expect that much would happen by clicking on a badge.

I cannot fully test as I've other issues with Che 5.6 right now (ws:// giving 404). Exposed Ports sounds better, but I wouldn't know who/what exposes them when. Are those ports exposed by the workspace itself, or by a command?

**Comment by ghost** [comment]
Ports are exposed and published when a container is created. So, it is workspace master that does it. Some ports are forcibly exposed and published (those required by agents, like terminal, ssh, ws agent), others get published based on ports exposed in the image itself. On top of that, users can expose and publish ports from User Dashboard.

**Comment by wernight** [comment]
Okay got it. Workspace images run what you tell them to run, I wouldn't know how to run something in a Dockerfile for Che, except by telling Che to auto-run a command in Che but then it's be the preview URL field. So that wouldn't exactly be an exposed port. I've seen that Che can plug in some optional services, but I didn't thing people would create such a service.

**Comment by ghost** [comment]
How to add a server i.e. make sure you can preview a process?

1. In a Dockerfile

`EXPOSE 1111`

Just having this in your recipe is enough for Docker to expose it to a random port from the ephemeral range. In User dashboard you will see your ports in Server section. However, it will have an auto generated name: `server-1111-tcp    1111   -    Address:	  172.19.20.16:32796`

2. If you want to give your server a name, use `LABEL` instruction:

`LABEL che:server:1111:ref=myAwesomeServer che:server:1111:protocol=http`

As a result, your server will look like this in user Dashboard:

```
ref                            port   protocol Runtime
myAwesomeServer 1111  http        Address:	172.19.20.16:32789
                                                       URL:	http://172.19.20.16:32789
```

**Comment by wernight** [comment]
Great example, it's just missing how to start that service exposing 1111. For example usually a Dockerfile is like:

    CMD ["nginx", "-d"]

This would start a service and this service may expose port 1111. However Dockerfiles for Che need to derive from one of the base images normally and therefor I think people cannot just run `CMD`; can they?

**Comment by ghost** [comment]
All Che base images have a non terminating command in their CMDs: `CMD tail -f /dev/null`. So, if you want to override the default CMD (which you can easily do), make sure this is a non terminating process, otherwise a container will start, CMD will be executed and container will be shut down.

Yes, you can start nginx in CMD, but then your container life will depend on this process, and if you kill it or it is killed as a result of OOM, your workspace will be stopped.

**Comment by wernight** [comment]
Ok that answers my question. Now I understand how it could be used. So basically the "Exposed Ports" could link to a documentation page with a section including:

All Che base images have a non terminating command like `CMD ["tail", "-f", "/dev/null"]` which you can override with any non terminating process (otherwise the container will be shut down). You can start a process which exposes one or more ports. To make those ports accessible to users of your workspace:

  - Replace `CMD` to start one or more servers.
  - (Optional?) Add `EXPOSE <port>`
  - Optionally label ports to make them more descriptive like (example you gave)
  - (Optional?) Add "Exposed Ports" in Che UI

**Comment by ghost** [comment]
If you want expose port solely in a Dockerfile, EXPOSE is mandatory, LABEL is optional.

If you add ports in User Dashboard, nothing is to be done in a Docker recipe.
