### ISSUE TITLE
ftp on file save 

### ISSUE THREAD

**Issue by Bana0615** [eclipse-che/che#4661]
Is there a way to setup che so when i save a file it ftps up to my server? I cannot find any settings that seem to handle that.

**Comment by ghost** [comment]
@Bana0615 

1. Files are auto saved
2. There's no plugin in Che that will do it.

In a workspace, there's a file watcher service that notifies about file system changes. It's possible to develop a custom plugin that listens to these kinds of events and ftps files to a server. 

As an immediate solution, you may create a custom stack and run a script that will backup your projects.

**Comment by ghost** [comment]
@Bana0615 do you have any further questions?

**Comment by Bana0615** [comment]
@eivantsov Do you guys have any plans to add this to che? This is the only featured needed for me and my team to fully use this.

**Comment by ghost** [comment]
@Bana0615 there are no immediate plans to add ftp support of this kind.

As a workaround, you may start a script that will ftp files once every n seconds.

**Comment by Bana0615** [comment]
Is there any where you can point me that would help me with that?

**Comment by ghost** [comment]
@Bana0615 it depends on what you are trying to achieve - a real plugin that will listen to file changes and ftp project, or a simple ftp script that you start when a workspace starts.

**Comment by ghost** [comment]
Closed due to inactivity. Feel free to reopen if you have decided to write such a plugin or have questions about writing a script that will ftp files as a cron job
