### ISSUE TITLE
Che cli fails on 3G connection.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#4666]
I was trying to run che locally when on a 3G connection. This fails with an error message (see below). My expectation would be that this works even when offline or on a bad connection:

Error:
 docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/thomas/.che:/data -v /home/thomas/git/che:/repo eclipse/che:nightly start
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
WARN: Did not detect TTY - interactive mode disabled
INFO: (che cli): /repo mounted - using assembly and manifests from your local repository
INFO: Welcome to Eclipse Che!
INFO: 
INFO: We could not resolve DockerHub using DNS.
INFO: Either we cannot reach the Internet or Docker's DNS resolver needs a modification.
INFO: 
INFO: You can:
INFO:   1. Modify Docker's DNS settings.
INFO:      a. Docker for Windows & Mac have GUIs for this.
INFO:      b. Typically setting DNS to 8.8.8.8 fixes resolver issues.
INFO:   2. Does your network require Docker to use a proxy?
INFO:      a. Docker for Windows & Mac have GUIs to set proxies.
INFO:   3. Verify that you have access to DockerHub.
INFO:      a. Try 'curl --head hub.docker.com'
INFO:   4. Skip networking checks.
INFO:      a. Add '--fast' to any command

**Comment by TylerJewell** [comment]
This is an expected message given the network configuration that you have
set up..

The CLI is unable to access DockerHub and errors out.

Either you can skip networking checks, or run the CLI in offline mode.

**Comment by bmicklea** [comment]
Closing this issue as resolved.
