### ISSUE TITLE
Wrong behavior when import a project without a default name 'master' branch

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#4673]
**Reproduction Steps:**
* Import a project with default remote branch which is not named 'master' (e.g.https://github.com/idexmai/testRepo-2.git; _**the default remote branch is named 'develop'**_).
* Go to 'Git' -> 'Branches'.

**Expected behavior:**
* the local current branch should be the 'develop'

**Observed behavior:**
* the local current branch is the 'master'.

**Che version:** 5.7.0
**OS and version:** Ubuntu 14.04
**Docker version:** 1.13
**Che install:** [Docker container]

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![not master_default_branch](https://cloud.githubusercontent.com/assets/5408906/24606750/59287ab8-1877-11e7-8f4e-b022dd1f0590.png)
![default_branch](https://cloud.githubusercontent.com/assets/5408906/24607398/1a6bb904-187a-11e7-8678-6e370c555802.png)

**Comment by AndrienkoAleksandr** [comment]
This is JGit bug. So we depends on https://bugs.eclipse.org/bugs/show_bug.cgi?id=516226 
And this issue can be reproducible for seldom testcase which you described, for your repository https://github.com/idexmai/testRepo-2.git which contains branches with commit tree very similar to default branch. In most cases commit tree for branches is different and jgit clone operation set current branch correct. For example for my test project  https://github.com/AndrienkoAleksandr/JGitTest2 with default branch "New". So it's a minor and seldom bug.

**Comment by ghost** [comment]
Closing the issue. If it becomes a burning problem of project leads think it should be reopened, they may do so.
