### ISSUE TITLE
Wrong text in tooltip

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4674]
This is issue related with epic #4511 

If run some command in the project with two machines ,  the name of the machine will be display in the tooltip.

**Reproduction Steps:**
- Create some project with two machines .
- Run command from toolbar (like in attachment) .
- Hover the mouse on the "Run" button in the command toolbar .
- Pay attention to the tooltip .

**Expected Behavior :**
The name of launched command will be display in the tooltip .

**Observed behavior :**

The name of the machine displayed in the tooltip .

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24608142/e9d619de-187d-11e7-997b-3e2f1c766868.gif)

**Comment by azatsarynnyy** [comment]
fixed
