### ISSUE TITLE
che-core-api-auth contains mix of different purpose classes.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4677]
This module contains
- classes for ws master
  1. AuthenticationService
  2. OAuthAuthenticationService - OAuth2.
  3. OAuthAuthenticationService - OAuth1. 
- classes for ws-agent server side
  1.OAuthAuthenticatorProvider, RemoteOAuthTokenProvider
  2.OAuthAuthorizationHeaderProvider RemoteOAuthAuthorizationHeaderProvider 
- ws-master <-> ide - DTO
- ws-master <->  ws-agent - DTO
- OAuth2.gwt.xml https://github.com/eclipse/che/blob/master/ide/commons-gwt/src/main/java/org/eclipse/che/security/oauth/JsOAuthWindow.java#L18-L18

We need to organise source code by separate modules according to their logical structure

**Comment by gazarenkov** [comment]
still actual?

**Comment by skabashnyuk** [comment]
Yes. will do this cleanup during https://github.com/eclipse/che/issues/5362

**Comment by skabashnyuk** [comment]
Implementation of https://github.com/eclipse/che/issues/5362 can give more clear view how to do it.
