### ISSUE TITLE
[Feature Request] Ability to Filter Git Branches in the branches pop up

### ISSUE THREAD

**Issue by rhughes89** [eclipse-che/che#4678]
I have a project with several git remotes. When selecting a branch, there is a very large list of branches from each remote that I have set up with the project. It is very cumbersome to have to scroll to the exact branch that I need ( I'd rather use the git command line to do it ). This can be fixed if there was a filter input box on the top of the branches sections so that I can fuzzy find the branch that I am looking for.

## **Reproduction Steps:**

1. Turn on workspace with git project
2. click on menu option git > branches
3. window should popup with a list of all available git branches. I have to scroll down to the remote/branch that I want.

## **Expected Results:**
1. Turn on workspace with git project
2. click on menu option git > branches
3. window should popup with a list of all available git branches with a filter input box on the top of the list. When I start typing the branch that I want, it will filter down to match what I am typing.

## **OS and version:**    
**OS**: Ubuntu Xenial 16.04
**Version**: 5.6.0-SNAPSHOT

## **Diagnostics:** 
N/A

**Comment by bmicklea** [comment]
@rhughes89 you can use git from the terminal as well. All our built-in stacks have git and you can add it to a custom stack as well.  Adding enhancement request label.
