### ISSUE TITLE
Test runner launch tests on the same JVM with dev-machine

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4679]
**Reproduction Steps:**
1) Create java console application from wizard
2) Open  the AppTest class and add   `System.exit(1);`  invocation in the test.
**Expected result:** the test should pass
**Actual result:** the test has invoked System.exit. The workspace 
has crashed. The test can invoke any java code on the JVM of dev-machine! It is very critical for security.
![anim](https://cloud.githubusercontent.com/assets/1640058/24615491/13923ffa-1897-11e7-80a5-dbf98548a364.gif)
**OS and version:** Ubuntu 14.0 TLS, chrome browser

**Comment by vparfonov** [comment]
Done for TestNG test framework
