### ISSUE TITLE
Cannot launch a test in a workspace without predefined commands

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4683]
**Reproduction Steps:**
1) Create workspace based on java stack
2) Create console-java application
3) Remove all commands from commands explorer
4) Open test folders, select test class and launch it as junit test
**Expected result:** the test should pass
**Actual result:** unexpected 500 server error
**Note:** for correct working the runner needs compiled classes. The plugin for compiling and running -
 uses predefined commands. But if command is absent - the runner will work wrong
 Related selenium tests: JavaTestPluginJunit3Test,  JavaTestPluginJunit4Test, JavaTestPluginTestNgTest
**OS and version:**   Ubuntu 14.0 TLS, chrom browser, nightly server

**Comment by musienko-maxim** [comment]
For this has been workaround in the next tests:
* JavaTestPluginJunit3Test
* JavaTestPluginJunit4Test
* JavaTestPluginTestNg 
Also has beeb added auxulary class: CompileCommand

**Comment by ghost** [comment]
Cannot reproduce with 5.15-SNAPSHOT
