### ISSUE TITLE
Intelligent Commands Not Filtering per Project

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4686]
Cannot filter commands per project selected. Also doesn't let me switch projects off for commands at first.
![capture](https://cloud.githubusercontent.com/assets/20580888/24621333/b3a4ad92-1866-11e7-8744-e58a26fe1398.gif)

Can use factory https://codenvy.io/f?name=che-codenvy-docs&user=jdrummond to reproduce.

Codenvy 5.6.0

**Comment by slemeur** [comment]
@azatsarynnyy could you please check this one?

**Comment by azatsarynnyy** [comment]
@slemeur I confirm, it's reproducible on my side.
The same bug has been already registered https://github.com/eclipse/che/issues/4657

**Comment by svor** [comment]
It was fixed in this [PR](https://github.com/eclipse/che/pull/4955)
