### ISSUE TITLE
Intelligent Command Multiple Lines 

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4688]
Multiple line commands do not execute all lines.

![image](https://cloud.githubusercontent.com/assets/20580888/24659236/bc4bc402-1911-11e7-8ea3-f8e346a9b9fa.png)

**Reproduction Steps:**
Create new custom command with :
```
echo "hello" > /home/user/world
cat /home/user/world
```

Codenvy 5.6.0

**Comment by slemeur** [comment]
@azatsarynnyy Could you please check. This issue is really problematic.

@musienko-maxim : Need to add automated test cases to cover this.

Thanks.

**Comment by ghost** [comment]
@JamesDrummond you have got an error in your `echo syntax`

The right command is `echo "This is not a bug" > /home/user/world`

**Comment by eivantsov** [comment]
And it looks like it's end of line that appends `?`

**Comment by azatsarynnyy** [comment]
@slemeur can't reproduce it with the right command `echo "This is not a bug" > /home/user/world`

**Comment by JamesDrummond** [comment]
@azatsarynnyy Markdown didn't add return please check again with above.

**Comment by ghost** [comment]
@JamesDrummond can you run `ls -la` in `/home/user`?

**Comment by JamesDrummond** [comment]
OK took video. Weird stuff happening. Make sure to start new workspace.

does not work
```
echo "hello" > /home/user/world
cat /home/user/world
```
works
```
echo "hello" > /home/user/world
cat /home/user/world
ls -la /home/user
```
![capture](https://cloud.githubusercontent.com/assets/20580888/24660371/f297e7a4-1914-11e7-99d3-43205936cd0c.gif)

**Comment by azatsarynnyy** [comment]
I've tried to reproduce this problem but it works fine on my side

**Comment by JamesDrummond** [comment]
@azatsarynnyy Please get with @eivantsov if you have not done so already. Please do a video so I can see your steps. Also let me know browser version you are using just in case.

**Comment by ghost** [comment]
@JamesDrummond i am unable to reproduce it. I deleted the bad command and recreated it - ever since the issue's gone.

**Comment by azatsarynnyy** [comment]
@JamesDrummond there're my steps:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1636395/24707680/45b0a152-1a1d-11e7-9cf3-2b212936ba80.gif)

Chrome 57.0.2987.133 (64-bit)

**Comment by ghost** [comment]
@JamesDrummond can you reproduce it again?

**Comment by JamesDrummond** [comment]
@azatsarynnyy I see you are using the 5.7.0 snapshot. Maybe something changed. I will test again.

**Comment by vparfonov** [comment]
@JamesDrummond still actual for you?

**Comment by slemeur** [comment]
Closing - I can't reproduce the issue with provided use case.
@JamesDrummond : Please reopen if you still have the problem.
