### ISSUE TITLE
Investigate problem unexpected regression of Che integration tests on CI

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4690]
We have unexpected regress for CHE integration test  since 03.03.2017. 
This is next jobs: 
https://ci.codenvycorp.com/view/qa/job/che-integration-tests/286/
https://ci.codenvycorp.com/view/qa/job/che-integration-tests/285/
* com.codenvy.ide.plugins.testrunner
* com.codenvy.ide.intelligencecommand
* com.codenvy.ide.codeserver
* com.codenvy.ide.filewatcher
* com.codenvy.ide.debugger
**Also we have unexpected error like:**   `java.util.concurrent.TimeoutException: Workspace ShowFileRefered406 with expected status has not been found.` It means that the workspace has not been created correctly.  But more details are not received with test in log. 
We have issue for this: https://github.com/codenvy/qa/issues/664.
We should resolve 2 problems: 
1) Unexpected skipping of tests
2) Unexpected stopping workspaces with error
It is very critical. Because data from CI use all developers for analize of regression.

**Comment by riuvshin** [comment]
This happened due to bug in docker https://github.com/docker/docker/issues/26111
docker restart fixed issue, but it seems we need to upgrade docker version.
