### ISSUE TITLE
Syntax Highlighing for new filetype

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4696]
So I've created a new filetype according to docs, and it registered successfuly, so far so good.
But the sysntax highlighing is marking me a hard time to implement.
The docs aren't clear.
I'm using this example: https://www.eclipse.org/che/docs/plugins/code-editors/index.html#add-syntax-highlighting-for-your-own-language

and I have few questions: 
1. where do I implement the code? 
2. i search for reference in che, and I found one plugin that uses this function (plugin-language-server), and I followed the code but nothing seems to work.

Do you have any example on how to use this feature? Thanks :)

**Comment by slemeur** [comment]
Hi @noamb13 . Thanks for reaching.

Take a look at this issue https://github.com/eclipse/che/pull/1392 which introduced the ability to inject your own syntax highlighting.

You have to insert the method in your editor extension. 
In the following sample: https://github.com/eclipse/che/tree/master/samples/sample-plugin-json
It could have been added in this class:
https://github.com/eclipse/che/blob/master/samples/sample-plugin-json/che-sample-plugin-json-ide/src/main/java/org/eclipse/che/plugin/jsonexample/ide/JsonExampleEditorExtension.java

Alternatively, you can check example made by a community member: 
https://github.com/lgas/fpp-editor/blob/master/plugins/che-plugin-fpp-editor/che-plugin-fpp-editor-ide/src/main/java/org/eclipse/che/plugin/fpp/editor/ide/FppJSEditorExtension.java

Hope this will help. 

Separately, I created the following documentation enhancement request: https://github.com/eclipse/che-docs/issues/192

**Comment by ghost** [comment]
@slemeur Thank you, but it has the same effect. 
another question: 
I saw you add pattern ( i guess it highlight the syntax with regex match)
config.setPatterns(
                "[\n" +
                        "  {include: \"orion.java\"},\n" +
                        "  {\n" +
                        "    match: \"\\\\b(?:it|delegate|owner|as|in|def|threadsafe|assert|use|with)\\\\b\",\n" +
                        "    name: \"keyword.fpp\"\n" +
                        "  }\n" +
                        "]");

what does the name mean?

**Comment by slemeur** [comment]
You maybe have an issue in the registration of the grammar. 

I recommend you to check the documentation about Pattern Objects from Orion here: https://wiki.eclipse.org/Orion/Documentation/Developer_Guide/Plugging_into_the_editor#Pattern_objects

**Comment by ghost** [comment]
@slemeur 
I simply copy-pasted your code with little bit of changes:

   @Inject
    protected void configureContentType(final OrionContentTypeRegistrant contentTypeRegistrant) {
        // register content type and configure orion
        final String contentTypeId = "text/x-pythonect";

        OrionContentTypeOverlay contentType = OrionContentTypeOverlay.create();
        contentType.setId(contentTypeId);
        contentType.setName("Pythonect Language");
        contentType.setExtension(Constants.PY_EXT);

        // highlighting
        OrionHighlightingConfigurationOverlay config = OrionHighlightingConfigurationOverlay.create();
        config.setId("orion.pythonect");
        config.setContentTypes(contentTypeId);
        config.setPatterns(
                "[\n" +
                        "  {include: \"orion.python\"},\n" +
                        "  {\n" +
                        "    match: \"(?:it|delegate|owner|as|in|def|threadsafe|assert|use|with|{{headers}})\",\n" +
                        "    name: \"keyword.pythonect\"\n" +
                        "  }\n" +
                        "]");

        contentTypeRegistrant.registerFileType(contentType, config);
    }

**Comment by ghost** [comment]
@slemeur 

I've successfuly managed to highlight using my custom regex, but I want to be able to style them as I want.
The "name" key is the class name I guess, but the styling is come from the plugin-orion project.

**Comment by ghost** [comment]
@noamb13 you may want to take a look at `/che/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/theme/Theme.java` and `getEditor...` strings and override with your own, however, changes will be applied globally.

Applying custom styles to your particular project type and keywords is smth that we have never done.

**Comment by ghost** [comment]
@noamb13 do you have further questions?

**Comment by SharkJ** [comment]
> Alternatively, you can check example made by a community member:
> https://github.com/lgas/fpp-editor/blob/master/plugins/che-plugin-fpp-editor/che-plugin-fpp-editor-ide/src/main/java/org/eclipse/che/plugin/fpp/editor/ide/FppJSEditorExtension.java

Hi,
Does this still apply @slemeur? If not, is there a new way to implement this?
Thank You!

**Comment by slemeur** [comment]
It depends what you are trying to build. But that probably could still be applied in Che 6.

Would you be able to describe a bit what you are looking to achieve?

**Comment by SharkJ** [comment]
@slemeur I have created a DSL using Xtext and implemented it as a language server sidecar in Eclipse Che. Everything was successful except syntax highlighting. I want to implement syntax highlighting for my new language in Eclipse Che, and AFAIK I should add an extension to Orion Editor and add the necessary commands there. 
Could you please tell me if there is a possibility to do that using the above approach?
