### ISSUE TITLE
Provide ssh vcs editing in dashboard.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4701]
We currently require ssh vcs keys to be added via workspace `Profile > Preferences > SSH > VCS
And generate a key`. However, it should be in dashboard too. A user emailed me because he thought this needed to be done in dashboard which makes logically sense to me. This isn't a critical enhancement so labeling it P2.

Codenvy 5.6.0

**Comment by TylerJewell** [comment]
@slemeur - pleaes *bump* this as git actions in dashboard which may require git implementation into ws-master for certain functions will take a higher precedence in Q3.

**Comment by ghost** [comment]
@TylerJewell generating and saving ssh key is on ws-master already. One does not need a running ws-agent to generate ssh key and save it to user prefs.

**Comment by slemeur** [comment]
Created the following epic: https://github.com/eclipse/che/issues/4827
