### ISSUE TITLE
Can't reset panel layout.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#4704]
I coudn't access explorer/editor when I opened Che workspace on my laptop (w/ 12inch display).

![screenshot 2017-04-05 at 07 53 58](https://cloud.githubusercontent.com/assets/101795/24682681/f4a60ad2-19d5-11e7-98d0-6362ba8f69d5.png)

This workspace was opened on my workstation (w/ 24inch display).
One of the easiest fix is to reset its panel layout. But I couldn't the menu item for it.

**Comment by ghost** [comment]
@monaka what happens when you click tabs in the bottom - events, processes etc?

**Comment by monaka** [comment]
Tabs are working. Components looks sane.
Just I can't resize since the top of Events/Processes/Debug panel is out of my window.

**Comment by ghost** [comment]
I see, so it is either no panels for you, or panels are dragged to the top so that they block everything. Correct?

**Comment by monaka** [comment]
The drag point for resize is out of my screen.
It is shown in case 24inch. But it is out of the screen in 11inch.
This issue will be occurred only in case he uses Che on multi-devices which have different size screen.

**Comment by ghost** [comment]
When on 24 inch screen you may resize the panel, stop workspace and then start it from a small screen device. It should do the trick.

**Comment by ghost** [comment]
Alternatively, you may remove user prefs. Go to `/swagger/#!/preferences/removePreferences` and click Try it out. All of your user preferences like opened files and project tree state will be removed, however, panel positions will be reset to default.

Labeling this issue as improvement. Indeed, it'd be great to have this option in the IDE - reset IDE state to default or smth like that.

**Comment by monaka** [comment]
@eivantsov Thanks for your suggestion. I want to try them but I can't reproduce this issue by myself...
I'm not sure why I can't but may my nightly is updated.
So I close this for now.
And I still hope "IDE state to default" was added into the menu.
