### ISSUE TITLE
Cannot crate workspace

### ISSUE THREAD

**Issue by XDDK** [eclipse-che/che#471]
**_1 Upvote**_ I have Eclipse Che downloaded from here: [https://install.codenvycorp.com/che/eclipse-che-latest.zip](url) (Version 4.0.0 - RC3).
I installed docker from here: [https://docs.docker.com/engine/installation/linux/centos/](url)
Java JRE Installed: Java(TM) SE Runtime Environment (build 1.8.0_72-b15)

1) I start the che.sh with "./che.sh --skip:uid --port:15143".
2) I wait for it to load.
3) I enter the dashboard and make a new workspace.
4) I get this error after some time: 
![image](https://cloud.githubusercontent.com/assets/9017523/13234440/4ab55406-d9c1-11e5-9571-17c90450ce5d.png)
![image](https://cloud.githubusercontent.com/assets/9017523/13234449/53d33e9a-d9c1-11e5-9a8b-8c1cba50a72f.png)

Thanks for helping! :D

**Comment by TeknoloGenie** [comment]
Lucky you, i don't even get that far with the Codenvy OnPrem :) I had this same issue when i was building just the plain Eclipse Che project a few days ago and it was an issue with my networking. Specifically for me it was i had to set the `--remote:ip` to my public ip instead of the local. Then there was some small issue with my Che build not communicating to the Docker Deamon running on port 4411...

Do you mind posting you `che.properties` file you have with your credentials and public ip's X'd out?

**Comment by TylerJewell** [comment]
The engineers will come online shortly and can diagose the issue. It looks like a networking configuration where the workspace is unable to connect back to the Che server.  And also the Che server is not able to reverse call the workspace back.  We have just inserted into the main branch a bunch of error detection messages that will indicate our best guess as to what is causing a particular networking issue and also the che.properties items that you typically change when this issue occurs.

Also, this networking page was just updated this morning with more details on the logic flow for how Che - WS - Browser are connecting to each other.  Depending upon your setup, you may need to explore setting one of those additional properties.

https://eclipse-che.readme.io/docs/networking

**Comment by TylerJewell** [comment]
Also, in the past 30 minutes, I just updated the docs with some more clarity on this issue.  It looks like you are running into the Workspace agent connecting to the Che server.  See the notes in the docs for your configuration about how we set the `che-host` value.

**Comment by TeknoloGenie** [comment]
+1 for the updates to networking doc's, and another +1 for the added error handling!

**Comment by ghost** [comment]
@TeknoloGenie do you run Che locally or in the cloud/local VM?

Also, it's worth trying the nightly build since we have improved error handling for ws-agent-server connection - https://install.codenvycorp.com/che/eclipse-che-nightly.zip

Another thing you can try is:
1. Edit /conf/che.properties to increase ws agent start timeout
   `machine.ws_agent.max_start_time_ms=600000` (I added an extra zero)
2. run `docker ps` while ws-agent is trying to connect to a server
3. `docker exec -ti $containerID bash`
4. `cat /etc/hosts`
5. `curl -v -X OPTIONS che-host:8080/ide/api`
6. or `curl -v -X OPTIONS $IP/8080/ide/api` where $IP is IP for che-host in /etc/hosts

**Comment by XDDK** [comment]
This is my eclipse che properties now: http://pastebin.com/kCqj4ueg

**Comment by ghost** [comment]
@1Tudor1 can you please answer questions in my previous post? This is important to localize the issue and solve it.

**Comment by XDDK** [comment]
When the ws-agent is trying to connect?

**Comment by ghost** [comment]
Ws-agent is trying to connect Che server when ide.was is being deployed, ie. when a ws-agent Tomcat is being started.

Without details on if or not you run Che in the cloud and how you run it (natively or Docker) the only suggestion that I can offer is to follow the 6 step diagnostic guide.

**Comment by XDDK** [comment]
And how can i get container ID? for "docker exec -ti $containerID bash"

**Comment by ghost** [comment]
Run docker ps while ws-agent is trying to connect to a server

**Comment by XDDK** [comment]
https://gyazo.com/53b3cdb5b8b0c3956e71210513f55744

**Comment by ghost** [comment]
Please, complete all 6 steps. Your Che server and workspace container should be running.

**Comment by XDDK** [comment]
Please give me exact details about where i should type the commands (i'm a noob, sorry :L), and look here "1) I start the che.sh with './che.sh --skip:uid --port:15143'.", i run the che with the port 15143

**Comment by ghost** [comment]
I think I know what has caused the issue. You are running Che on a non default port. We had a bug in that version, where server address port is hardcoded in the configuration.

Open `/conf/che.properties` and replace

`machine.docker.che_api.endpoint=http://che-host:8080/ide/api`

with 

`machine.docker.che_api.endpoint=http://che-host:${SERVER_PORT}/ide/api`

Restart Che afterwards.

**Comment by XDDK** [comment]
I had it already like this, take a look: http://pastebin.com/kCqj4ueg . I think reinstalling the eclipse will be  better? Can you please tell me a full set of instructions for installing eclipse che with port 15143 for CentOS 7? Appreciate!

**Comment by ghost** [comment]
Replace

`machine.docker.che_api.endpoint=http://che-host:${SERVER_PORT}/ide/api`

with

`machine.docker.che_api.endpoint=http://che-host:15143/ide/api`

**Comment by XDDK** [comment]
Now i get this error https://gyazo.com/481da66e108e8e01e113890d75691cd4

**Comment by ghost** [comment]
Where are you running Che? Locally? Amazon, Digital Ocean?

**Comment by XDDK** [comment]
locally, but i modified to " `machine.docker.che_api.endpoint=http://89.136.150.117:15143/ide/api` ", where `89.136.150.117` is my external ip

**Comment by ghost** [comment]
What do you mean locally? I can access your server.

You should also add -r:89.136.150.117 to che.sh when starting.

**Comment by XDDK** [comment]
i mean is on my network

**Comment by ghost** [comment]
https://github.com/eclipse/che/issues/471#issuecomment-187572087

**Comment by XDDK** [comment]
When i run `docker ps` i get no values: https://gyazo.com/ee602f58a5f5577f907447face24e54b , so i cannot run `docker exec -ti $containerID bash`.
After i execute the step 4 i get these: https://gyazo.com/409d36f13fe53be79f2f2993e88bd9e1
Step 5 result: https://gyazo.com/ac7aee2e18860e8e1aaadaea07baa0ef

**Comment by ghost** [comment]
You may contact support@codenvy.com if you think you may give a temporary access to a server.

**Comment by XDDK** [comment]
I think another bug is, if i have a dns and i open the eclipse che with it, example: `uniteelite.com:15143` which ping for `uniteelite.com` is `89.136.150.117` i get this error when creating https://gyazo.com/ad1c92ccabc4df1f9c2b372b6d77e252

**Comment by ghost** [comment]
Can uniteelite.com be resolved in the VM itself? Can you ping it?

**Comment by XDDK** [comment]
yep

**Comment by ghost** [comment]
Can you wget the recipe script yourself? Or access it from the outside?

**Comment by ghost** [comment]
I can create workspace when I access your server by IP. You need to make sure uniteelite.com is properly resolved, and you can manually retrieve the recipes when in the VM.

**Comment by XDDK** [comment]
i get this response when accesing the script by website: `FROM codenvy/ubuntu_jdk8`

**Comment by TeknoloGenie** [comment]
@eivantsov Currently for now while im getting a stable version setup im using a temporary Digital Cloud server, after that i'll permanently place it on my small hosting center.

Thanks so much for the nightly installation guide. Much appreciated!

**Comment by ghost** [comment]
> i get this response when accesing the script by website: FROM codenvy/ubuntu_jdk8

Are you doing it from within the VM?

Also, @1Tudor1 and @TeknoloGenie  are you guys using the same server? It is Digital Ocean? If so, there might be some problems with DO droplets and Che. 

Try creating a workspace with a custom recipe

FROM codenvy/ubuntu_jdk8
RUN sudo sed -i 's/random/urandom/g' /opt/jdk1.8.0_45/jre/lib/security/java.security

**Comment by siliconalchemy** [comment]
Hi, I was having similar problems.  Using the checklist from @eivantsov I worked out the docker container couldn't communicate with che over port 8080 because (as is very common) the server was running iptables.  If you're familiar with docker it's not immediately obvious that each container has it's own IP and communicates with the central process over IP so the first thing to do is to make sure the server has port 8080 opened in the firewall for 172.16/16.  This should be more clearly marked in the docs, I wasted half a day on this.
Now I've got workspaces running but have all sorts of other issues creating projects..

**Comment by ghost** [comment]
@siliconalchemy
Open a new one on project creation.

**Comment by ddementieva** [comment]
@1Tudor1 any update on this?

**Comment by ghost** [comment]
The latest releases of Che run OK on Digital Ocean. Closing the issue as cannot reproduce. Feel free to reopen if the problem is still there for you.
