### ISSUE TITLE
Keyboard control doesn't work in the Command Palette

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4711]
This is issue related with epic https://github.com/eclipse/che/issues/4511

**Reproduction Steps:**
- Create spring project 
- Go to the commands palette
- Try to close some goal by keyboard 
- Pay attention that you will close some goal using keyboard only after click on the palette .

**Expected behavior :**
Goal is closed .

**Observed behavior :**
Goal not closed .

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24705374/42bbb918-1a14-11e7-8d25-a6eb5ceffc53.gif)

**Comment by azatsarynnyy** [comment]
fixed
