### ISSUE TITLE
Eclipse Che support for cross compilation 

### ISSUE THREAD

**Issue by vijaypa1** [eclipse-che/che#4712]

**Comment by ghost** [comment]
@vijaypa1 please follow rules and suggestions on submitting issues to Che - https://github.com/eclipse/che/wiki/Submitting-Bugs-and-Suggestions

If you provide details on what you want to achieve with Eclipse Che, the community will be eager to help. Otherwise this issue will be closed.

**Comment by vijaypa1** [comment]
@eivantsov , took note of your comments.

when I checked in the forum last year, about Eclipse che support for embedded devices (cross compilation and push binary to target board (e.g raspberry pi) and execute it), i was asked to look at ARTIK IDE, which is a variant of Eclipse Che.
  with the recent Eclipse Che releases, is the support for embedded devices available? Or do we have to depend on ARTIK IDE?

**Comment by ghost** [comment]
@vijaypa1 yes, those features are in Artik IDE, not Eclipse Che. FYI, Artik remove has been moved to https://github.com/codenvy-legacy/artik
