### ISSUE TITLE
Git remotes randomly disappear

### ISSUE THREAD

**Issue by rhughes89** [eclipse-che/che#4713]
I turned on the ec2 box where my eclipse che is running and all my git remotes for my project dissappeared. 

**Reproduction Steps:**

**Not sure** but i think it happend when i phyiscally shut down without stopping the workspace first.

**OS and version:**    
OS: Ubuntu 16.04
Version: 5.6 Snapshot

**Diagnostics:** 
N/A

**Comment by ghost** [comment]
@rhughes89 I do not think there are enough details and steps to reproduce. Can you reliably reproduce this behavior?

Can you see these remotes at `/instance/data/workspaces/ws-name/project_name/.git/refs/remotes`

**Comment by rhughes89** [comment]
@eivantsov I am not able to constantly reproduce this issue. I will keep trying and report my findings here. 

seems like `/instance/data/workspaces/{{ws-name}}/{{project_name}}/.git/refs/remotes` was missing. Also the remotes where missing from `/instance/data/workspaces/{{ws-name}}/{{project_name}}/.git/config` as well. 

My local branches remained intact however

**Comment by ghost** [comment]
Well, I can't say anything at this point. Branches are missing because they are physically missing. If you import, remotes are physically there, then shut down the node, and they are missing...well, it's a bug then. But let's reproduce it first.

**Comment by ghost** [comment]
@rhughes89 I am going to close this one. Feel free to reopen if you have steps to reproduce and can reliably reproduce it.
