### ISSUE TITLE
Gitignored files get deleted when starting and stoping workspace

### ISSUE THREAD

**Issue by rhughes89** [eclipse-che/che#4714]
Gitignored files get deleted when starting and stoping workspace. This is a problem since may projects keep configurations and enviroment variables in gitignored folders

**Reproduction Steps:**
- Turn on workspace
- import a project with a folder that is gitignored
- place a new file in that folder
- turn off workspace
- turn back on workspace
- the file recently created will be deleted

**OS and version:**    
OS: Ubuntu 16.04
Version. 5.6.0-SNAPSHOT

**Diagnostics:** 
N/A

**Comment by TylerJewell** [comment]
This is currently expected behavior according to the spec of how the product was designed.  We are working on a more advanced backup mechanism for projects that give end users control over what is included in the backup.  I cannot link the tracking issue as I am on a phone right now.  But proper thing to do is to cross link that tracking issue and then close this one asking everyone to track the master issue.

Tyler

**Comment by rhughes89** [comment]
Thanks @TylerJewell  for the response. 

can I suggest that users be can use a .cheignore file in thier project so that ignored files are specific to the ide?

**Comment by TylerJewell** [comment]
The reference issue is https://github.com/codenvy/codenvy/issues/1518
driven by Codenvy.

It  would be ideal if it could be as simple as just having a .cheignore
file, but that wouldn't actually work.

There are a number of scenarios that have to be accounted for:
1. In Che, we just do straight volume mounts to move projects in / out of a
workspace during the start / stop operation.  So, in this scenario, we have
a crude script that can then apply a filter to remove what is or what is
not volume mounted.
2. In a distributed system, like Codenvy, we have no guarantees where the
nodes that will have the workspaces will be, so the projects are likely
located in one location and the workspace runtimes in another. We have an
rsync implementation that moves the projects in and out.  And so any syntax
that would be used needs to be consistent for che and codenvy, a
distributed version.
3. Even in more advanced scenarios, if you have a compose syntax where
there are multiple containers for a single ws, those containers may be on
different nodes.  So a central location for /projects may need to move
different parts of the project into different containers.
4. And then finally, for systems like Che or Codenvy running on top of
Kubernetes, we then have to make sure this all works with a storage
abstraction as we may not have direct access to the file system the way we
do with Codenvy natively.

We tried using a clustered in-memory, distributed file system but the perf
was awful as they are read-sensitive, but not write-sensitve.  Imagine
cloning a huge repo, it would take nearly 10x longer.  So we have to do
something smarter.

So these are the thoughts that are going into a larger design.



Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by ghost** [comment]
And the reason behind using .gitignore is avoiding restoring and backing up project artifacts and other binaries.

**Comment by ghost** [comment]
Btw, @rhughes89 you should have created this issue in Codenvy project, since in Che projects are volume mounted.

**Comment by ghost** [comment]
@rhughes89 closing this issue. You are very welcome to follow and comment on https://github.com/codenvy/codenvy/issues/1518

**Comment by rhughes89** [comment]
@TylerJewell @eivantsov Thank you for the responses. Will follow that issue
