### ISSUE TITLE
Nodejs debugger server returns wrong value

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#4720]
There is selenium test [com.codenvy.ide.debugger.NodeJsDebugTest#debugNodeJsTest](https://github.com/codenvy/qa/blob/master/src/test/java/com/codenvy/ide/debugger/NodeJsDebugTest.java#L83) which fails sometimes [here](https://github.com/codenvy/qa/blob/ca03d5444eedca895c489ea5c14c00bbc8eaf769/src/test/java/com/codenvy/ide/debugger/NodeJsDebugTest.java#L142) because of server returns value **5.5.372.41** instead of **19**:
![com codenvy ide debugger nodejsdebugtest debugnodejstest_u1rj1h86](https://cloud.githubusercontent.com/assets/1197777/24741567/2551009a-1aaf-11e7-8a0f-6f5960634948.png)

**OS and version:**    
Ubuntu 14.04
Chrome Version 57.0.2987.110 (64-bit)
Che 5.7.0-SNAPSHOT

- [x] Review existed nodejs debuggers https://github.com/eclipse/che/issues/6651

**Comment by tolusha** [comment]
Can't reproduce

**Comment by tolusha** [comment]
The root of the issue is that nodejs debugger mixes outputs from different commands.
Let's start from reviewing existed nodejs debuggers (wrappers) to figure out how they deal with this problem.

**Comment by tolusha** [comment]
- [ ] Move all tests into the docker container 2SP
- [ ] Setup connection with nodejs debugger (init websocket protocol) 
- [ ] Add required DTO objects 3SP
- [ ] Implement communication with nodejs debugger
* connect/disconnet
* step in/out/over
* breakpoints
* evaluation
* threaddump

**Comment by dmytro-ndp** [comment]
Logs:
- [webdriver logs](https://github.com/eclipse/che/files/1822510/org.eclipse.che.selenium.debugger.NodeJsDebugTest.debugNodeJsTest_hcic.log)
- [ws-agent.zip](https://github.com/eclipse/che/files/1822512/ws-agent.zip)

**Comment by vkuznyetsov** [comment]
actual in Version: 6.10.0
