### ISSUE TITLE
Agent installation scripts fail to download binaries if both curl/wget are not installed in container

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#4721]
We merged an [improvement](https://github.com/eclipse/che/commit/950dd692c0148da45e99b48b4a1f32cf7a0ad7e7) that allowed to use wget instead of curl in agents installation scripts.
Looks like this feature wasn't tested on machines when no wget/curl are present.
Now start of exec agent fails because of that.
Agents scripts that should be fixed:
- exec
- terminal
- wsagent

**Reproduction Steps:**
1. Create workspace with a machine from image that don't have neither curl nor wget.
1. Start workspace

**OS and version:**    
Ubuntu 16.04

**Diagnostics:**

**Comment by garagatyi** [comment]
@bmicklea @slemeur Please add severity level

**Comment by garagatyi** [comment]
Looks like to fix this issue we need to add `CURL_INSTALLED=true` after line
https://github.com/eclipse/che/blob/master/agents/exec/src/main/resources/org.eclipse.che.exec.script.sh#L22
and repeat this fix in other 2 scripts.

**Comment by skabashnyuk** [comment]
Looks like it was made in https://github.com/eclipse/che/pull/4029 @benoitf  can you take a look?

**Comment by benoitf** [comment]
Thx

**Comment by garagatyi** [comment]
NP
