### ISSUE TITLE
The same processes in the process bar disappeared after relaunch process 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4728]
**Reproduction Steps:**
- Go to any project
- Launch three times the one command
- Click on process bar and wait drop-down list
- Relaunch some command from this list
- Pay attention to result

**Expected behavior :**
The commands will be relaunched and stay in the list .

**Observed behavior :**
The commands relaunched but disappeared from drop-down list .

**Attachment :**

![anim1](https://cloud.githubusercontent.com/assets/22724619/24754787/7997b780-1ae0-11e7-9e0a-ad09d08c9242.gif)

**Comment by azatsarynnyy** [comment]
fixed
