### ISSUE TITLE
Files and folders are not visible in the Project Explorer if in the Editor opened a file from root of a project folder 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4733]
**Reproduction Steps:**

1. Create a workspace from Java stack with web-java-spring project.
2. Open in the Editor README.md or pom.xml file.
3. Refresh the page

**Observed behavior:**
After refreshing in **the Project Explorer** visible only files which opened in **the Editor**.
This bug happens if open a file from root of a project folder.

Che version: 5.7.0-SNAPSHOT
OS and version: Ubuntu 16.04 LTS
Docker version: 1.12.3
Che install: Docker container

![anim](https://cloud.githubusercontent.com/assets/7760565/24751330/cc42d6c2-1ad1-11e7-8ed7-42fb28be7241.gif)

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT

**Comment by ghost** [comment]
UPDATE. Indeed, src/man/java is missing.
