### ISSUE TITLE
After rename factory just added parameters into json are reseted

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4734]
**Preconditions:** we should have a factory with a name.
**Reproduction Steps:**
`Dashboard->Factory->Open configuration->add some parameters into json->rename factory`

**Expected result:** the parameters should be saved.
**Actual result:** all parameters have lost. It may disappoint a user very much.
**Env.** Ubuntu 14.0 TLS, Chrome browser

**Comment by ghost** [comment]
Can be reproduced with the latest master 5.15-SNAPSHOT. Probably either auto-save for changing factory name should be turned off, or when it a new name is saved, json config currently in the editor should be picked up (as if a users has pressed Update button)
