### ISSUE TITLE
How to make eclipse-che language internationalization?

### ISSUE THREAD

**Issue by bobowang2017** [eclipse-che/che#4735]
How to make eclipse-che language internationalization?

**Comment by ghost** [comment]
@bobowang2017 There's no hwo-to guide for Che, however, you may want to take a look at http://www.gwtproject.org/doc/latest/DevGuideI18n.html

**Comment by bobowang2017** [comment]
@eivantsov Is the language internationalization function exist in future? thank you

**Comment by TylerJewell** [comment]
@bobowang2017 @eivantsov - I do not understand the question.  Internationalization is a broad topic covering dozens of different elements and considerations.  Please be specific in what you are requesting.

**Comment by bobowang2017** [comment]
@TylerJewell How to replace the language in eclipse-che dashboard with another language?

**Comment by ghost** [comment]
@bobowang2017 current design of user Dashboard does not offer localization capabilities, which means you need to change everything right in code.

**Comment by bobowang2017** [comment]
Thank you

**Comment by lkc0626** [comment]
Hi,
This post has been a quite a while... Is it okay for me to ask whether internationalization of Eclipse Che is available now?...

Thank you.
