### ISSUE TITLE
Preview URL is lost after refresh page [REGRESSION]

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#4740]
**Reproduction Steps:**
* Open the IDE and create a web aplication from a template (e.g. web-java-spring)
* Run the application, check the preview URL
* Refresh page, check the preview url

**Expected behavior:**
* Preview URL should be displayed in the console

**Observed behavior:**
* Preview URL won't display anymore

**Che version:**  5.8.0
**OS and version:** Ubuntu 14.04
**Docker version:** 1.13
**Che install:** Docker container

**Additional information:**
* **_Note:_**_The bug is not reproduced, when an application is created from template on the dashboard_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![preview-url](https://cloud.githubusercontent.com/assets/5408906/24798802/adc4373e-1ba0-11e7-839b-68b5070dd38b.png)

**Comment by ghost** [comment]
Can be reproduced with the latest master.
