### ISSUE TITLE
Eclipse CHE not starting up on CentOS with Docker 1.12

### ISSUE THREAD

**Issue by venuwin** [eclipse-che/che#4747]
Hi,
I have a Virtualbox running on my Windows 7 laptop.
Installed Ubuntu 16.04 and then installed Docker on it.

As per the Getting started guide of Eclipse CHE, I am not able to start Eclipse CHE.

Please find below the command and output :+1: 
_sudo docker run -it eclipse/che start_
INFO: Welcome to Eclipse Che!
INFO: 
INFO: You are missing a mandatory parameter:
INFO:    1. Mount 'docker.sock' for accessing Docker with unix sockets.
INFO:    2. Or, set DOCKER_HOST to Docker's location (unix or tcp).
INFO: 
INFO: Mount Syntax:
INFO:    Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...
INFO: 
INFO: DOCKER_HOST Syntax:
INFO:    Start with 'docker run -it --rm -e DOCKER_HOST=<daemon-location> ...'
INFO: 
INFO: Possible root causes:
INFO:    1. Your admin has not granted permissions to /var/run/docker.sock.
INFO:    2. You passed '--user uid:gid' with bad values.
INFO:    3. Your firewall is blocking TCP ports for accessing Docker daemon.

**Docker Version:**

venu@venu-VirtualBox:~$ docker --version
Docker version 1.12.6, build 78d1802

Please help.

Thanks
Venu

**Comment by ghost** [comment]
@venuwin please take a look at the error message itself. There's a hint on how to proceed:

`INFO: Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...`

**Comment by venuwin** [comment]
Hi eivantsov,

I tried it already. The output of command "docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock" is given below :

_venu@venu-VirtualBox:~$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
"docker run" requires at least 1 argument(s).
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container_

**Comment by ghost** [comment]
Here you go: `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che-data:/data eclipse/che start`

**Comment by venuwin** [comment]
Hi Eivantsov,

Thanks for helping me out.

While the above command worked on Ubuntu, it is still throwing the same error on CentOS7.

Due to hard disc limitations on one box, i moved to the other box having enough space , but this VM is running CentOS. Any help would be great!

I am able to successfully run the hello world program, but the problem is while launching CHE.

[cheuser@localhost-localdomain-2 docker.service.d]$ sudo docker run hello-world
[sudo] password for cheuser: 

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

[cheuser@localhost-localdomain-2 docker.service.d]$ sudo whoami
root
[cheuser@localhost-localdomain-2 docker.service.d]$ whoami
cheuser
[cheuser@localhost-localdomain-2 docker.service.d]$ sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che-data:/data eclipse/che start
INFO: Welcome to Eclipse Che!
INFO: 
INFO: You are missing a mandatory parameter:
INFO:    1. Mount 'docker.sock' for accessing Docker with unix sockets.
INFO:    2. Or, set DOCKER_HOST to Docker's location (unix or tcp).
INFO: 
INFO: Mount Syntax:
INFO:    Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...
INFO: 
INFO: DOCKER_HOST Syntax:
INFO:    Start with 'docker run -it --rm -e DOCKER_HOST=<daemon-location> ...'
INFO: 
INFO: Possible root causes:
INFO:    1. Your admin has not granted permissions to /var/run/docker.sock.
INFO:    2. You passed '--user uid:gid' with bad values.
INFO:    3. Your firewall is blocking TCP ports for accessing Docker daemon.

Thanks
Venu

**Comment by ghost** [comment]
@venuwin what you can try is:

1. `sudo chmod 777  /var/run/docker.sock`
2. Disable SElinux. 
3. Update your Docker to the latest version. 1.12 has some issues on CentOS, Fedora, RHEL.

**Comment by ghost** [comment]
@venuwin any update please?

**Comment by venuwin** [comment]
Hi Eugene,

Thanks for your interest to help me. We are not able to update the docker version to the latest on that box. Only 1.12 gets installed. Trying to fix it. Will definitely keep you posted.

Many Thanks for your help!

Regards
Venu

**Comment by ghost** [comment]
@venuwin I am going to close this issue since it looks like more like a Docker issue, and there's nothing I can really help with on Che side. Feel free to reopen if Docker update does not fix it for you.

**Comment by MrYing** [comment]
[root@localhost ~]# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che-data:/data eclipse/che start
WARN: Bound 'eclipse/che' to 'eclipse/che:5.18.0'
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
INFO: Welcome to Eclipse Che!
INFO: 
INFO: We could not resolve DockerHub using DNS.
INFO: Either we cannot reach the Internet or Docker's DNS resolver needs a modification.
INFO: 
INFO: You can:
INFO:   1. Modify Docker's DNS settings.
INFO:      a. Docker for Windows & Mac have GUIs for this.
INFO:      b. Typically setting DNS to 8.8.8.8 fixes resolver issues.
INFO:   2. Does your network require Docker to use a proxy?
INFO:      a. Docker for Windows & Mac have GUIs to set proxies.
INFO:   3. Verify that you have access to DockerHub.
INFO:      a. Try 'curl --head hub.docker.com'
INFO:   4. Skip networking checks.
INFO:      a. Add '--fast' to any command
