### ISSUE TITLE
auto-expand child folders containing exactly 1 folder like github does when browsing source

### ISSUE THREAD

**Issue by jstrachan** [eclipse-che/che#4749]
when expanding the tree of maven projects things are often very deeply nested. e.g. a simple maven based microservice might have a path of `src/main/java/com/acme/foo/bar/something/MyThing.java` so thats 8 clicks of the folders to find some actual source code to view.

When browsing projects on github its common to automatically open folders which contain only 1 folder. e.g.

```
expand `src`
src/
  main/
  test

expand `src/main`

src/
  main/
   java/
   resources/
  test

expand `src/main/java`

src/
  main/
   java/
    com/
      acme/
       foo/
        bar/
          something/
            MyThing.java
   resources/
  test
```
So the above helped speed the user through to the real content (the source code) by using the rule that if a folder containers only 1 child folder then just expand it too.

If a project has no tests and no `src/main/resources` then a single expand of `src` could list source code.

**Comment by TylerJewell** [comment]
@jstrachan - James.  In this scenario, did you have the "maven" project type set?  It's interesting that you chose maven, as our language server for it applies that logic to source code package structure  In the case of java, you'd see the fully qualified package name if there is a single folder, like "com.acme.foo.bar.something".  This only applies to Java packages, however, and I can appreciate that you are talking about the more generic "folder" case irrespective of any project typing designation that may be applied.

**Comment by jstrachan** [comment]
@TylerJewell thanks for the heads up - it could well be that the project type was wrong! This issue was the result of watching someone use Che in a demo which was a maven / vertx based project and found it painful watching them open all the folders to find source code ;) Lemme go pester them to check their project type!

**Comment by mlabuda** [comment]
See https://github.com/redhat-developer/che-starter/issues/113 the problem was in passed request body to Che server. Now, it should be ok.
