### ISSUE TITLE
What's the "temporary workspace"?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#475]
I see there is an api:

> POST /workspace/runtime Start the temporary workspace from the given configuration

I'm not sure what does the "temporary workspace" mean and how can we use it. What's the difference between it and normal workspace?

**Comment by ddementieva** [comment]
Temporary workspace is a workspace that is valid for a limited period of time. Projects created in temporary workspaces will be destroyed when the timeout is reached. 

Currently temporary workspaces are not usable for Che.

**Comment by freewind** [comment]
@ddementieva thanks for answering
