### ISSUE TITLE
Golang agents fails to build locally on Windows

### ISSUE THREAD

**Issue by bartlomiej-laczkowski** [eclipse-che/che#4758]
After upgrading my fork with some recent changes for CHE, my local build on Windows fails with the following:
```
[INFO] --- exec-maven-plugin:1.4.0:exec (build-go-sources) @ go-agents ---
# github.com/eclipse/che-lib/pty
..\..\..\che-lib\pty\ioctl.go:6: undefined: syscall.SYS_IOCTL
..\..\..\che-lib\pty\ioctl.go:6: not enough arguments in call to syscall.Syscall
..\..\..\che-lib\pty\run.go:21: unknown syscall.SysProcAttr field 'Setctty' in struct literal
..\..\..\che-lib\pty\run.go:21: unknown syscall.SysProcAttr field 'Setsid' in struct literal
..\..\..\che-lib\pty\util.go:18: undefined: setsize
..\..\..\che-lib\pty\util.go:30: undefined: syscall.SYS_IOCTL
..\..\..\che-lib\pty\util.go:32: undefined: syscall.TIOCGWINSZ
..\..\..\che-lib\pty\util.go:34: not enough arguments in call to syscall.Syscall
# github.com/eclipse/che/agents/go-agents/exec-agent/exec
exec-agent\exec\process.go:267: undefined: syscall.Kill
```
Is there anything that I might be missing in my development environment or is it just "no go" for Windows in current state?

**Reproduction Steps:**

Try to build CHE 5.8.0 locally on Windows machine.

**OS and version:**    

Windows 10

**Comment by skabashnyuk** [comment]
What version of golang do you have installed? Can you test with latest?

**Comment by bartlomiej-laczkowski** [comment]
I updated Golang to the latest 1.8.1 give it a try and build still fails. Might it be something related to this [issue](https://github.com/yudai/gotty/issues/18) for gotty?

**Comment by skabashnyuk** [comment]
@garagatyi @evoevodin wdyt?

**Comment by garagatyi** [comment]
Do you know on what commit in Che your fork were before update? If commit is hard to find then maybe project version?

**Comment by ghost** [comment]
I think for now the best way to build Che on Windows is to use `eclipse/che-dev` image.

**Comment by bartlomiej-laczkowski** [comment]
@eivantsov Hello, was there any fix applied for this issue?

**Comment by ghost** [comment]
@bartlomiej-laczkowski I don't think so. AFAIK, use of che-dev image is the only certified way to build all Che modules on Windows.

**Comment by ghost** [comment]
@bartlomiej-laczkowski you may want to try the following solution for Win systems http://stackoverflow.com/questions/20829155/how-to-cross-compile-from-windows-to-linux/20830892#20830892

**Comment by voievodin** [comment]
Hi @bartlomiej-laczkowski.
go-agents build fails on windows because exec & terminal agents use linux syscalls.

If you do not change go-agents sources you don't need to build them either.
To skip the build of go-agents
```
mvn clean install -pl '!:go-agents'
```
You can also follow the disscussion about [docker profile](https://github.com/eclipse/che/issues/5127)

**Comment by ghost** [comment]
I am closing the issue since build of go agent natively on Windows isn't supported.
