### ISSUE TITLE
Github PR panel: use .github/PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#4759]
**Reproduction Steps:**
- Import an existing project on Github containing Che
- open the PR panel
- we expect the content of .github/PULL_REQUEST_TEMPLATE.md to be in PR Comments section by default

**Comment by sunix** [comment]
Reopening it as it would be a nice improvement in the PR panel

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
