### ISSUE TITLE
Adding usermanagement on top of che

### ISSUE THREAD

**Issue by vinu** [eclipse-che/che#4761]
Hi 
I understand che has a user management / authentication / authorization module, and it currently uses che as the default user. What is the best way to have a a user management module added to che, what are the extension points I should be looking at so I can have the user log in/sigup - as codenvy does - and pass that user info through the application ,have workspaces attached to the user.
thanks

**Comment by ghost** [comment]
@vinu perhaps you should look at https://github.com/codenvy/codenvy?

**Comment by vinu** [comment]
thanks @eivantsov 
Any hint  on what will be the bare minimum requirement to have a basic user management - I believe codenvy could be too much overwhelming ? :)

**Comment by TylerJewell** [comment]
Vinu: 

There are many surface points that can be attacked and each of them have to be tokenized for authentication.  This includes the master, all workspace file systems, terminals, and servers launched by users within the workspaces.  This requires the introduction of reverse proxies to intercept and manage tokens and URL rewriting.

You also have to introduce ssl, tls support for all of the traffic endpoints between the browser and each of the connections, which then introduces certificate management and cross browser injection attacks that you must manage.

Codenvy is the simple approach to security for this broad problem.

Tyler

**Comment by vinu** [comment]
thanks @TylerJewell 
Let me checkout codenvy code and see if I can follow the approach (y)

**Comment by TylerJewell** [comment]
Vinu - Codenvy's code is proprietary and you cannot copy / use it.  So be
careful with how you study it to make sure that you are not in violation of
any intellectual property rights.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by vinu** [comment]
@TylerJewell yes thanks :)
