### ISSUE TITLE
Cannot delete user from admin dashboard, if he has running workspaces

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#4771]
Cannot use UserService to delete a user, if he has running workspaces:

This is the response, that will be returned {"message":"org.eclipse.che.api.core.ServerException cannot be cast to java.lang.Error"}

That ServerException will  occur in JpaWorkspaceDao in event subscriber, that tries to remove the workspace in onCascadeEvent method

**Comment by mshaposhnik** [comment]
Confirmed it's fixed with https://github.com/eclipse/che/pull/4856/files
