### ISSUE TITLE
Factories command validation invalid error

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#4772]
**Reproduction Steps:**

 1. Go to /factory/
 2. When creating a factory try to add a command with a space in the name like:

![image](https://cloud.githubusercontent.com/assets/145667/24908441/557509dc-1ec0-11e7-9418-39945c39e762.png)

Note the invalid error reported

**OS and version:**    Docker image of Che 5.7.2

**Comment by ghost** [comment]
@bmicklea why is this labeled as bug? Do you think commands should have spaces in them?

Moreover, I think this issue https://github.com/eclipse/che/issues/4780 is a perfect answer

**Comment by bmicklea** [comment]
Commands in the IDE allow names with spaces so the error in the dashboard is a bug. If you feel 4780 covers it then close this as a duplicate.

**Comment by wernight** [comment]
Those are not the same issues. This is the custom command command lines, the other issue is the auto-run on startup command name.

**Comment by slemeur** [comment]
Added for next sprint.

**Comment by ghost** [comment]
Never ended up in a sprint. @ashumilova @slemeur we should either remove next sprint label or take it to the next sprint.
