### ISSUE TITLE
Factories lose the per-project attributes

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#4778]
**Reproduction Steps:**

1. Create/edit a factory on /dashboard/#/factory
2. Under "Configuration" section, give your project some attribute in the JSON like:

````
{
  "v": "4.0",
  "workspace": {
    "projects": [
      {
        "links": [],
        "name": "foo",
        "attributes": {
          "commands": [
            "{\"commandLine\":\"docker-compose up\", \"name\":\"Start server\", \"attributes\":{\"previewUrl\":\"\", \"goal\":\"Run\"}, \"type\":\"custom\"}"
          ]
        },
        "type": "blank",
        "source": {
          "location": "example.com",
          "type": "git",
          "parameters": {}
        },
        "path": "/foo",
        "problems": [],
        "mixins": []
      }
    ],
...
````

3. Click "Update" (you may reload and note that the `attributes` field has the `commands`.
4. Use the UI to change any value, for example use the UI to add or remove a common command in "Configure Commands"

It should have kept the attributes but it replaced them with empty ones: `"attributes": {}`.
 
**OS and version:**    5.7.2 (Docker image)

**Comment by mshaposhnik** [comment]
Confirmed to be DASHB glitch, requested fix from  @ashumilova

**Comment by mshaposhnik** [comment]
Fixed in https://github.com/eclipse/che/pull/4840
