### ISSUE TITLE
CHE-581 New workspace from 'Import an existing workspace configuration' is created wrong

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#478]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-581
Reporter:  Aleksandr Shmaraev
Description: \* Open the dashboard and go to 'Workspaces' -> 'New Workspace'.
- Select the 'Import an existing workspace configuration' and insert a json file (e.g.https://gist.githubusercontent.com/idexmai/68382088ebe82f9b901d/raw/9fecf4257c5f8f530550c3b4135edafdb889993c/phpWs.json).  
- Create workspace, open in IDE, switch to the 'Machine Perspective' and select the 'Recipe'.
  Expected: should be displayed 'From codenvy/php'.
  Actual: the 'From codenvy/ubuntu_jdk8' is displayed.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/c6c03be8bcb0f4a7f6045a2e7b44da91d3072088
