### ISSUE TITLE
Can't create stack from composefile

### ISSUE THREAD

**Issue by yang378848032** [eclipse-che/che#4781]
I want to create a stack from composefile which have three containers,but it's failed,I want to know whether can't create stack when containers more than two. also I want to expose a confirmed IP，like
expose 5234:5234，how can I do？also I can't create myserver machine from my custom image,show this error: Can't create machine from image. Cause: Error response from docker API, status: 500, message: Get https://registry-1.docker.io/v2/library/yxc-tomcat/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fyxc-tomcat%3Apull&service=registry.docker.io:

services:
 dev-machine:
  image: eclipse/gcc
  mem_limit: 2147483648
  depends_on:
    - myserver
    - test
 myserver:
  image: yxc-tomcat
  mem_limit: 1073741824
 test:
  image: yxc-test
  mem_limit: 1073741824

**Comment by ghost** [comment]
The error says that library/yxc-tomcat is missing at DockerHub. Is it a local image?

And publishing ports is not supported. All exposed ports will be published to ports randomly chosen by Docker from the ephemeral port range.

**Comment by yang378848032** [comment]
yes.it is local image，the compose whether support more than two cotainer as above？

**Comment by ghost** [comment]
Compose supports multiple services.

To be able to use a local image, go to che.env file and uncomment the following line:


`#CHE_DOCKER_ALWAYS__PULL__IMAGE=true`

Restart Che.

**Comment by yang378848032** [comment]
@eivantsov。thank you.whether have guide for multiple services.or you give me a example for three service

**Comment by ghost** [comment]
https://docs.docker.com/compose/compose-file/

I think these docs are quite helpful. Note that Eclipse Che does not support some Compose syntax: https://www.eclipse.org/che/docs/devops/runtime-recipes/index.html#unsupported-compose-syntax

**Comment by yang378848032** [comment]
uncomment  #CHE_DOCKER_ALWAYS_PULL_IMAGE=true     is useless. Show:can't create machine from image.cause:error response from docker API,status:404,message:repository yxc-tomcat not found:does not exist or no pull access.  
This image is local image.if I replace this image with tomcat which has been pulled from dockerhub.it is ok,but my custom image is failure.and my docker version is 17.03.1-ce

**Comment by TylerJewell** [comment]
@yang378848032 - If you set the property to `true`, then it will always attempt a pull from DockerHub.  If you set it to false, then it can reuse local images.  Also, please note that the property that you wrote is different than the one that @eivantsov wrote.  Eugene's had additional underscores in the property name.

**Comment by yang378848032** [comment]
thank you I solved.It is not support docker 17.03-ce,change to 1.12.05 is ok
