### ISSUE TITLE
Initial splash should be smarter

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#4783]
Even when opening a project from a factory, the splash is still:
![image](https://cloud.githubusercontent.com/assets/145667/24914826/b31dc24e-1ed5-11e7-84a8-62e87ab70fd1.png)

If there is a project, it should instead show common shortcuts like:
 - Ctrl + Shift + A Find Action...
 - Ctrl + Alt + N Navigate to File...

**OS and version:**    5.7.2

**Comment by slemeur** [comment]
Hi @wernight. 

Yes that's a good enhancement request. Thanks.

**Comment by slemeur** [comment]
Tks @ashumilova.
