### ISSUE TITLE
Machine output of just started worspace is visible on all other started workspaces

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4786]
**Reproduction Steps:**
Create and start a workspace
Create a other workspace and change its machine name
Start second workspace and see the first workspace Processes area

**Observed behavior:**
In the first workspace Processes area appears the second workspace machine output

**Che version:** 5.8.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
**Docker version:** 1.12.6
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/24963242/b86e0f3e-1fa6-11e7-898b-54e91496672c.gif)

![com codenvy ide intelligencecommand commandspalettetest commandpalettetest_c4p9yfm0](https://cloud.githubusercontent.com/assets/7760565/24944549/6a164cc6-1f64-11e7-982b-254e2d1933cc.png)

![screenshot from 2017-04-11 13-00-01](https://cloud.githubusercontent.com/assets/7760565/24905353/659cd550-1ebc-11e7-8390-07d6b525b84d.png)

**Comment by vitaliy-guliy** [comment]
Processes panel must have outputs for all machines.

**Comment by JamesDrummond** [comment]
How often does this happen? We may want to release then follow up with a bug release.

**Comment by riuvshin** [comment]
@JamesDrummond always, for all workspaces.

**Comment by SkorikSergey** [comment]
If a new workspace is starting we can see its machine output on all others started workspaces.
![anim](https://cloud.githubusercontent.com/assets/7760565/24962978/12975282-1fa6-11e7-99a6-f8e754f60993.gif)
