### ISSUE TITLE
Changes not displayed in the splitted commands editor tabs  

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4787]
**Reproduction Steps:**
- Go to any project with commands -> commands explorer
- Click twice on the any command and go to the commands editor 
- Click right mouse button on the command tab and in the context menu choose "split pane in two columns"
- Do some changes in the opened  tab 
- Pay attention to another tab

**Expected Behavior :**
The changes displayed in the both tabs .

**Observed Behavior :**
The changes displayed only in the one tab .

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/24952495/4ff8f73c-1f80-11e7-9895-79ffbe8de22a.gif)

**Comment by ghost** [comment]
Can be reproduced with the latest master. Content isn't synced. I doubt this is a bug though and can't imagine any good use cases when having the same command in two side by side editors makes sense or benefits a user.

**Comment by TylerJewell** [comment]
It is certainly an unusual use case.  Though I imagine that if an end user did use the product this way it would be seen as a bug because end users have reasonable expectation that the same content in two views are kept in sync.

**Comment by ghost** [comment]
It's Codenvy QA who created the issue. Let it sit with P2 label for a while.
