### ISSUE TITLE
The "Delete" button in the "Factories" list is visible after deleting a factory

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4791]
**Reproduction Steps:**
In the **Factories** list create any factory.
Try to delete this factory.

**Expected behavior:**
The factory deleted and the **Delete** button isn't visible.

**Observed behavior:**
The factory deleted but the **Delete** button is still visible.

**Che version:** 5.7.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS

![anim](https://cloud.githubusercontent.com/assets/7760565/24957709/4317b99e-1f95-11e7-887c-c1e770a47125.gif)

**Comment by ghost** [comment]
Cannot reproduce on 5.15-SNAPSHOT
