### ISSUE TITLE
Wordwrap Highlighting

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4796]
Highlighting a word wrapped line does not highlight other lines.

![capture](https://cloud.githubusercontent.com/assets/20580888/24969805/9f84d270-1f77-11e7-8fb3-053ef84e7569.gif)

Codenvy 5.7.2

**Comment by ghost** [comment]
It's tricky to select the right area, but I did manage to do that:

![image](https://user-images.githubusercontent.com/5337267/28058660-f6ec99b4-6629-11e7-881b-a027e8a931bd.png)

**Comment by JamesDrummond** [comment]
@eivantsov Can you explain in greater detail what you did? The problem shown in my video is that you cannot highlight part of a single wrapped line. The image you indicate only shows highlighting of two lines.

**Comment by ghost** [comment]
I see. OK, let it be opened then
