### ISSUE TITLE
Allow macros to be used in the terminal

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4800]
## Goals
Allow user to use Che's macros in the terminal

## Details
We have a long list of macros which can be used inside of commands:
https://www.eclipse.org/che/docs/ide/commands/index.html#macros
Today those macros cannot be used in the terminal.

The idea would be the following:
- If the user is inputting just a macro, we return and print the corresponding evaluation of that macros.
- If user is using a macros in command given in the terminal, we would evaluate it for execution in the given command.

## Linked issues
https://github.com/codenvy/codenvy/issues/2077

**Comment by davidwindell** [comment]
Yes! This would be awesome, I just searched for this feature and found this issue. Our use case is that we have many commands that are based on macros so it would be useful to have those commands work in the CLI. I suppose we could use the API for this though.
