### ISSUE TITLE
Add machine button in add workspace has no label.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4809]
Add machine button in add workspace has no label. Bottom left of image below.

![image](https://cloud.githubusercontent.com/assets/20580888/25556789/070871e6-2cc9-11e7-875c-34b9292d4386.png)

**Comment by ghost** [comment]
@JamesDrummond should it be Add Machine?

**Comment by JamesDrummond** [comment]
Maybe "Add New Machine" and place it above recipe.

**Comment by ghost** [comment]
Yes, makes sense
