### ISSUE TITLE
Add/Import project to an existing workspace from URL

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4810]
Allow to add/import project to an existing workspace from URL. Currently you can only import template/sample projects.

![image](https://cloud.githubusercontent.com/assets/20580888/25018264/5e08e6b2-204c-11e7-89bb-d481391e93b7.png)

![image](https://cloud.githubusercontent.com/assets/20580888/25018294/7741786a-204c-11e7-8ff3-2fd2cecadfd9.png)

**Comment by ashumilova** [comment]
@JamesDrummond the first section has "Import from existing location" - there you can provide URL.

**Comment by JamesDrummond** [comment]
@ashumilova Does not work. Imports a sample project not git repo I provide.

Try importing `https://github.com/eclipse/che.git`

**Comment by ghost** [comment]
The new create workspace flow addresses this issue. You can provide your own URL and add it to a workspace when creating.
