### ISSUE TITLE
Cannot create preview url for custom command

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4811]
Cannot create preview url for custom command.

![image](https://cloud.githubusercontent.com/assets/20580888/25019703/2a3c8df2-2051-11e7-8562-28d63a5ed003.png)

Codenvy 5.7.2

**Comment by vparfonov** [comment]
Cannot reproduce

**Comment by JamesDrummond** [comment]
@vparfonov I cannot reproduce on codenvy.io so maybe it was fixed after 5.7.2 where I still get bug . When I upgrade I will test again. Thanks.
