### ISSUE TITLE
Cache causes that WS doesn't start

### ISSUE THREAD

**Issue by cifren** [eclipse-che/che#4814]
I have an issue on my workspace, sometimes I have to disable the cache to be able to start up my workspace. If I don't do it, the browser debug shows that some network request doesn't reach the IDE and the workspace stays down. The requests are "Machine" and "Process".

I have to press F12 (browser Debug), and check "disable cache" and the workspace starts like nothing happened...

**Reproduction Steps:**
I am not sure how to reproduce it. What I have done was to install the latest version and nigthly version and try them on the same browser. I have restarted several times the docker and workspace, it didn't resolve the issue.

I have disabled the cache, it worked.

**OS and version:**    
Linux Debian
**Diagnostics:** 
CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:latest
 Version:        5.7.2
 Command:        info
 Parameters:     info
Mounts:
 /data:          /webide/che_latest
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.7.2
 CHE_HOST:       domain.fr
 CHE_INSTANCE:   /webide/che_latest/instance
 CHE_CONFIG:     /webide/che_latest
 CHE_BACKUP:     /webide/che_latest/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   IP.IP.IP.IP
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.7.2
 IMAGE_CHE=eclipse/che-server:5.7.2
 IMAGE_COMPOSE=docker/compose:1.8.1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.7.2
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.7.2
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.7.2
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.7.2
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.7.2

**Comment by ghost** [comment]
@cifren I think I need more details from you to reproduce this one.

**Comment by cifren** [comment]
Yes I know... That is more to share in case someone meets a cache issue. I'll try to add debug images if one of my workspace fails to start again, this morning it did though, maybe on next Tuesday it will again.

**Comment by ghost** [comment]
I will close it for now. If you have clear steps to reproduce, feel free to reopen.
