### ISSUE TITLE
GWT and AngularJS integration

### ISSUE THREAD

**Issue by 19yak** [eclipse-che/che#4815]
I develop a small UML graphical editor with the following technologies: JointJS, angularJS, angular Bootstrap-ui, jquery.

And when testing the addition of my editor I notice that the use of angularJS with GWT is not possible.

Are there any solutions to do this?

**Comment by ghost** [comment]
@19yak can you elaborate on how you add this lib to GWT?

**Comment by 19yak** [comment]
@eivantsov I want to develop a UML plugin for Che. I develop an editor based on an existing source(AngularJS and JointJS library). During the integration of my editor with Che, I put the resources of my editor on the public folder of my ide module.

**Comment by TylerJewell** [comment]
@19yak - you need to provide examples and steps to reproduce the issue if you'd like help.  Include samples and source code necessary for engineers to see the same issue you have.

**Comment by AChakraborty1982** [comment]
I have been able to create the editor for JointJs but resolution of js library is not possible.
![screenshot from 2017-03-30 12-47-31](https://cloud.githubusercontent.com/assets/26390759/25074209/4ed8db14-22f6-11e7-9b04-5d4ad64aae28.png)
![screenshot from 2017-03-30 17-47-03](https://cloud.githubusercontent.com/assets/26390759/25074208/4ed8afa4-22f6-11e7-8fb0-e256333d0d8f.png)

**Comment by chakraborty-slx** [comment]
EMF4CHE use angularjs for the ecore editor, using jsonforms.

**Comment by 19yak** [comment]
For me I worked on two plans, a first one is to run che, test existing
plugins and develop my plugin which consists of adding a new type of UML
project.

And a second plan selecting a graphic library (JointJs) so search for
sources on github not to start at zero. I can select a developed in
AngularJS and JointJs.

Yakoubi Khaled
*Élève Ingénieur*
Informatique
*Faculté des sciences de Tunis*
m: +216 23 463 164
w: www.fst.rnu.tn  e: khaledyakoubi19@gmail.com

2017-04-16 21:56 GMT+01:00 Abhishek Chakraborty <notifications@github.com>:

**Comment by ghost** [comment]
@19yak when saying 

> use of angularJS with GWT is not possible

you need to provide code samples, screenshots and any other information that may help.

Some ppl from Che community have faced issues with using all off 3rd part js libs in one application together with javascript generated by GWT. There might be conflicts there. We currently investigate a way to load these libs in a separate iframe. However, there investigation is in progress and there are no results to share.

**Comment by ghost** [comment]
Closed due to inactivity.
