### ISSUE TITLE
Sometimes an error notification appears when rename a java class

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4816]
**Reproduction Steps:**
Open a project with java files 
Open in the Editor any java file, click on its Class name
**Menu** -> **Assistant** -> **Refactoring**-> **Rename**
Change name and press Enter button

**Expected behavior:**
Class and file names changed

**Observed behavior:**
There is "Failed to rename" error notification appeared.

**Che version:** 5.8.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25040849/a221b3ce-2114-11e7-8520-4800eda65911.gif)

**Comment by musienko-maxim** [comment]
Also actual for calling refactoring by SHIFT+F6, but from Refactoring wizard works as well.
