### ISSUE TITLE
Java reconciler does not show error in some cases

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#4818]
Java reconciler does not show error when we use class which is not exist anymore

**Reproduction Steps:**
1. Create a new java class
2. Open another java class and use the newly created class(create a new object for example) 
3. Remove the newly created class 

**Expected behavior:**
Java reconciler shows error 

**Observed behavior:**
We don't have any errors.

![javareconcilerbug](https://cloud.githubusercontent.com/assets/5676062/25042626/46f3a85a-2122-11e7-96cd-e072fecfd5d5.gif)

**Comment by slemeur** [comment]
@vparfonov I let you assign the proper severity on this bug.

**Comment by ghost** [comment]
Still an issue in 5.15.-SNAPSHOT

**Comment by musienko-maxim** [comment]
In che-6 cannot reproduce
