### ISSUE TITLE
After rename project , default commands not work 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4819]
**Reproduction Steps:**
- Go to the spring project
- Rename project
- Try to run some command where project name is the part of the command

**Expected Behavior :**
After rename project , default commands will be works without any updates

**Observed Behavior :**
After rename project some default commands do not work. 

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/25043647/1a75ffbe-212a-11e7-8dcf-f4656f2972d1.gif)

**Comment by ghost** [comment]
Hm.. this is what macros are used for, right? 

`cd ${current.project.path}` is the remedy here.

I don't think that when updating a project, we should get workspace config and mess with commands there. This is the downside of hardcoding. If you delete the project, the command will fail as well.

Of course, you may execute commands using a different client (pure rest for example), but trying to fix commands when a project is renamed is an overkill.

Closing the issues. PMs may reopen though.
