### ISSUE TITLE
Advanced terminals features

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4824]
# Goal
This epic main's goal is to improve and add new features to the terminals currently provided in Che.

## Sub-Tasks

**Save state between sessions**
When the user is refreshing his browser, we are restoring the process outputs but not the terminal. We should restore the state of the terminals as well. (see issue: https://github.com/eclipse/che/issues/274 for community proposal).
This behavior should work when the user is refreshing his browser, but also when the user is stopping his workspace and restarting it.
(Solution based on tmux, would be an option to explorer)

**Allow macros to be used in the terminal**
See the corresponding issue: https://github.com/eclipse/che/issues/4800

**Allow the user to name his terminals**
When the user is setting his developer environment, he sometimes wants to name his terminals. This way, it gets easier to switch from one terminal to another one. (See request in issue: https://github.com/eclipse/che/issues/274)

**Allow the user to create a command from instructions given in the terminal**
We should allow a user to create a command from the instructions he just executed in the terminal.
User should be able to highlight the instructions (to select them) and then click from the left tabbar to create a command from those instructions. It will ask in which goal the command must be created and it will opened the command's editor with the instruction already filled.

**Comment by TylerJewell** [comment]
@slemeur - please make sure you have sub-tasks for each of the issues so that we can track completion state.

**Comment by skabashnyuk** [comment]
@slemeur do you want to keep this issue?

**Comment by slemeur** [comment]
Yes, that is still something valuable, even with the future switch to Theia IDE
