### ISSUE TITLE
Unified preferences management

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4827]
# Goal
Today, we are providing settings and preferences into various places. The goal of this epic is to unify the experience related to user's preferences.

# Details 
We have preferences that are displayed from the IDE: (Profile > Preferences). 
![screen shot 2017-04-18 at 10 00 23](https://cloud.githubusercontent.com/assets/1636769/25120359/fe3733b2-241d-11e7-9d12-b12bf33c47fe.png)

Certain of those preferences are related to the editor and should stay in the IDE. But there are other preferences that should be unified and manage-able directly from the dashboard. For example, user should be able to manage from the dashboard:
- his VCS settings
- his SSH keys
- his Connected services (OAuth authorized services)

## Referenced issues
https://github.com/eclipse/che/issues/4701

**Comment by skabashnyuk** [comment]
@slemeur do you want to keep this issue?

**Comment by slemeur** [comment]
Closing as it will be fixed with the switch to Theia IDE
