### ISSUE TITLE
A "Download outputs" log file is empty while a workspace is starting

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4830]
**Reproduction Steps:**
Start a workspace
While the workspace is starting click on the Download outputs link
Open a saved log file

**Observed behavior:**
The log file is empty

**Che version:** 5.9.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25130282/51a9f5bc-244a-11e7-9d4f-7a9814aa3521.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by vitaliy-guliy** [comment]
Works fine in IDE5 and IDE6
