### ISSUE TITLE
Hard to read text on blue background when switched to the Light Theme style

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4832]
**Reproduction Steps:**
Start a workspace and switch to **the Light Theme** in the  **Preferences** menu
Open a project with java files
Open in the **Editor** any java file, click on its Class name
**Menu** -> **Assistant** -> **Refactoring**-> **Rename**

**Observed behavior:**
It is hard to read the class name on blue background

**Che version:** 5.9.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![selection_028](https://cloud.githubusercontent.com/assets/7760565/25132102/f41a2dde-2450-11e7-9e74-7fb543723683.png)

![anim](https://cloud.githubusercontent.com/assets/7760565/25132093/ec860dc2-2450-11e7-80ec-e8be637ca047.gif)

**Comment by ghost** [comment]
The issue is still there - 5.15-SNAPSHOT
