### ISSUE TITLE
List and open existing pull requests

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#4839]
Having imported a Github project,
A nice improvement of Che would be to have a new view that would list existing pull requests.
Opening one of the listed pull requests would automatically fetch and checkout the right fork/branch and display the comments in the PR panel.

**Comment by sunix** [comment]
Reopening it as it would be a nice improvement.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
