### ISSUE TITLE
Che does not respond

### ISSUE THREAD

**Issue by fnkr** [eclipse-che/che#484]
Eclipse Che is running, and curl can connect to port 8080, but I get no response.

[![asciicast](https://asciinema.org/a/2yjtcth1v40xswttjgt6di7ri.png)](https://asciinema.org/a/2yjtcth1v40xswttjgt6di7ri)

Logs: https://gist.github.com/fnkr/beebe07b0332934611f2

**Comment by ghost** [comment]
Hello,

What if you go to localhost:8080 in your browser?

**Comment by fnkr** [comment]
Same thing, page keeps loading forever.

**Comment by ghost** [comment]
What is your environment? Where are you running Che? According to the logs, ide.war hasn't been deployed.

**Comment by fnkr** [comment]
I'm running Che on a fresh Ubuntu 14.04 instance on Digital Ocean. Here is what I've done:
1. Installed Oracle Java 8
2. Set JAVA_HOME
3. Installed docker
4. Started docker registry
5. Created a new user for che (name `che` id `1000`)
6. Added the `che` user to the `docker` group
7. Logged in as `che` (`su che`)
8. Downloaded/extracted the latest che release from https://www.eclipse.org/che/download/ (RC3)
9. Started it (`bin/che.sh`)

**Comment by ghost** [comment]
Here's what you can do:

sudo sed -i 's/random/urandom/g' $JAVA_HOME/lib/security/java.security

If the path is not correct, look for the right location of java.security in $JAVA_HOME

Alternatively, you may run che with `Djava.security.egd=file:/dev/urandom` argument.

**Comment by fnkr** [comment]
Thanks, that works!

**Comment by ghost** [comment]
FYI, this is a known issue with DO droplets, so we'll add this argument in Tomcat's `setenv.sh` by default.
