### ISSUE TITLE
Can`t start apache in PHP project

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4843]
**Reproduction Steps:**
- Go to the PHP project
- Try to start apache 
- Pay attention to console

**Expected result :**
Apache will be started.

**Observed behavior :**
Apache does not start.

**OS and version:**    
OS : Ubuntu 16.04
Docker version : 1.13.1

**Attachments:**

![anim](https://cloud.githubusercontent.com/assets/22724619/25178413/697a8cbe-250e-11e7-9985-da3659b5b30a.gif)

User permisions:

![selection_001](https://cloud.githubusercontent.com/assets/22724619/25178577/01c6f76e-250f-11e7-82ed-0fe9c5c884be.png)

**Comment by ghost** [comment]
Cannot be reproduced on Ubuntu 14 with Docker 17.x
