### ISSUE TITLE
Can't find out IDE.gwt.xml

### ISSUE THREAD

**Issue by yang378848032** [eclipse-che/che#4848]
As eclipse che docs "To manually add your plug-in to the Che assembly, you update the IDE.gwt.xml",but I can't find out this file.I want to test example plugins .

**Comment by ghost** [comment]
@yang378848032 there's no need to add anything to IDE.gwt.xml. This file is auto generated now. All you need is to add plugin dependencies.

Can you point me to docs that have this GWT.xml statement?

**Comment by yang378848032** [comment]
in old docs，In assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml add:<inherits name='org.eclipse.che.ide.ext.helloworld.HelloWorldExtension'/>
...

**Comment by ghost** [comment]
Are those old docs somewhere online?

**Comment by yang378848032** [comment]
no my host off-line

**Comment by ghost** [comment]
Closing the ticket then. Feel free to reopen or open a new one if you have questions/comments
