### ISSUE TITLE
Develop plugins on windows

### ISSUE THREAD

**Issue by yang378848032** [eclipse-che/che#4857]
whether support develop on windows？I want to build che source code on windows use eclipse，and add a sample plugins in che.if it is feasible？

**Comment by ghost** [comment]
Yes, this is possible. However, certain Che modules can only be reliably built on Linux.

You may want to study some docs - https://www.eclipse.org/che/docs/assemblies/intro/index.html

**Comment by yang378848032** [comment]
thank you
