### ISSUE TITLE
Jump to location in file

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#4863]
For training use cases organizations want to be able to insert markdown or HTML documentation into the workspace (displayed in the editor or in a dedicated panel in the IDE). The user can read through the documentation and then click a link that opens a source code file to a specific location relevant to the task being documented.

Ideally the link would be able to start a workspace or execute a Factory, however this isn't required for this phase.

Requirements
- The link needs to operate only within the context of an already running workspace.
- The link will specify:
  - The file to be opened.
  - The line of the file on which to place the cursor (if unspecified it will be the first line)
  - The character within that line on which to place the cursor (if unspecified it will be the 1st character)
- If the file isn't already open: open the file in the editor, placing the cursor in the specified location.
- If the file is already open: bring the file to the foreground of the editor and place the cursor in the specified location.

**Comment by slemeur** [comment]
cross linking with a recent improvements from @sunix related to this use case: https://github.com/eclipse/che/pull/4802

**Comment by bmicklea** [comment]
@slemeur I think this use case is a little different though since it deals with an already running workspace where @sunix improvement is more about the behavior when opening a workspace. But in speaking with @sunix I believe all the pieces for this use case exist, but they'll need to be built into an implementation specific to it.
