### ISSUE TITLE
Initializing Language Server Forever

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#4864]
Time to time when I start workspace initializing ls is freezing and there is no any errors in the browser console output. 
It's very hard to reproduce, but it appears for JSON Language Server as for as custom YAML Language server. 

Blank stack. 
Che 5.8.0.
Windows 7

![image](https://cloud.githubusercontent.com/assets/11683340/25240673/1f52633e-25fc-11e7-9557-887d9c051eb0.png)

**Comment by ghost** [comment]
@zatsepinvl what's a custom YAML language server? Can you provide more details please?

**Comment by zatsepinvl** [comment]
From the point of the gist, it doesn't matter. It's just simple java application based on lsp4j which starts as language server for yaml file types and send notification to the client on didSave event. It works fine, but sometimes initializing is going forever. It's also true for JSON language server.

**Comment by zatsepinvl** [comment]
More over I noticed the following things:

- One instance of Language Server is initialized for one project, not for the whole workspace.
- If I open 4-5 json files from different projects and stop workspace, I will increase chance to get freezing initializing during the starting workspace back. 
- During the freezing client sends didOpen requests and gets successful responses.
- During the freezing highlighting works and I can see the json syntax errors in the editor.

It seems that everything is fine except this freezing notification. Maybe there is some problems just only on the client after simultaneously responses from server on language server initialization requests? 

Also when I stay Che opened and stop workspace from the another tab I get (yes, it's yaml, but it was the same for the json language serverm, trust me =) ):
![image](https://cloud.githubusercontent.com/assets/11683340/25243878/4d568ffc-2607-11e7-8b10-f0ee64835b11.png)

**Comment by zatsepinvl** [comment]
Ok, I just fix it by changing loading to simple notifications:

![image](https://cloud.githubusercontent.com/assets/11683340/25265395/8092951e-2675-11e7-9e76-a65f09395ebb.png)

![image](https://cloud.githubusercontent.com/assets/11683340/25264472/e71f54a8-266f-11e7-8214-0e4e2997fa0c.png)

However, in this case, initializing is also freezing sometimes, but  it doesn't affect user to continue work with Che and language server works OK.

**Comment by ghost** [comment]
Indeed, notification is better in some cases. And yes, a new instance of a language server is started for each file afaik.

> If I open 4-5 json files from different projects and stop workspace, I will increase chance to get freezing initializing during the starting workspace back.

That's a god way to reproduce it, thanks.
