### ISSUE TITLE
Workspace does not start with Java 1.7 installed

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4865]
Steps to reproduce:

1. Create a workspace from the following recipe:

```
FROM codenvy/jdk7
CMD tail -f /dev/null

```

Workspace agent does not start since it uses JDK 1.7 that is pre installed in the image. However, this piуce of script https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.script.sh#L52-L57 should have detected that Java version installed in a workspace is not 1.8 and install openjdk package from a debian repo.

**Comment by bmicklea** [comment]
@tolusha and @vkuznyetsov - this is preventing TIAA from continuing their rollout.

**Comment by ghost** [comment]
Looks like the way script extracts and compares Java version is wrong. Should be an easy fix.
