### ISSUE TITLE
Error in archetype documentation

### ISSUE THREAD

**Issue by levjason** [eclipse-che/che#4866]
**Reproduction Steps:**
See above

**OS and version:**  
Windows 7, Ubuntu 16.04  

**Diagnostics:**

**Comment by ghost** [comment]
@levjason can you please point to exact section in docs that has errors? Thanks

**Comment by levjason** [comment]
@eivantsov It's the example in the middle of the page: https://www.eclipse.org/che/docs/assemblies/archetype/index.html

![comm](https://cloud.githubusercontent.com/assets/10375396/25246810/cdbc7890-25d6-11e7-9151-e6202e9c4e4b.png)

**Comment by levjason** [comment]
Sorry,didn't mean to close.

**Comment by bmicklea** [comment]
@eivantsov can you confirm?

**Comment by ghost** [comment]
@bmicklea yes, docs, are wrong. There's also a bug in the cli itself. For some reason, CLI takes 5.6.0-SNAPSHOT as a default version when no version is specified https://github.com/eclipse/che/blob/master/dockerfiles/base/scripts/base/commands/cmd_archetype.sh#L76

This snapshot does not even exist. So, we should either give up on having any defaults and have a user explicitly specify the version, or have a tagged version there.

And docs do not say that you have to set a version, and the provided command fails:

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/archetype:/archetype -v ~Documents/arch:/data -v ~/.m2/repository:/m2 eclipse/che archetype all --no:interactive`

**Comment by skabashnyuk** [comment]
you can pass version with ```--archversion=5.8.0```

**Comment by ghost** [comment]
Another thing is that https://github.com/eclipse/che/blob/20165fe9fcc1dc5e7258af12adceb4bc2b39ad49/dockerfiles/base/scripts/base/commands/cmd_archetype.sh#L71 is hardcoded and used as a default. This plugin is now just `plugin-menu-archetype` not `che-plugin-menu-archetype`

**Comment by ghost** [comment]
@skabashnyuk yes, but it is not obvious from docs. I am going to issue a few PRs to fix cli and docs.

**Comment by ghost** [comment]
https://github.com/eclipse/che/pull/4905
https://github.com/eclipse/che-docs/pull/212 
Both merged

**Comment by ghost** [comment]
Closing the issue. Fixed in 5.9.0
