### ISSUE TITLE
Will there be a python debug plugin?

### ISSUE THREAD

**Issue by xfdonga** [eclipse-che/che#4869]
Will you develop a python debug plugin later? If i want to use python debug, do I need to write a plugin myself?

**Comment by ghost** [comment]
@xfdonga currently, Eclipse Che does not have Python debugger.

**Comment by tk3369** [comment]
I think the question was - **will** a debugger be developed for Python...

**Comment by atfuentess** [comment]
@eivantsov, So no plans to implement this for Eclipse Che at all?

**Comment by cmsalmeida** [comment]
@eivantsov any plans to implement a python debugger in Che?
