### ISSUE TITLE
Alignment on Piechart on Diagnostics

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#4871]
![image](https://cloud.githubusercontent.com/assets/14976516/25269788/b160912e-26b0-11e7-9613-ad3ac8ad23cd.png)

Tested with the Desktop Client

**Reproduction Steps:**
1:) Install the Desktop Client
2:) Run Diagnostics

**OS and version:**    
 Che 5.8.0 on Windows 10 Version 1607 (OS Build 14393.187) in Docker (not Docker for Windows)

**Comment by sr229** [comment]
Issue seems to be persistent on 5.18.0-SNAPSHOT 
![image](https://user-images.githubusercontent.com/14976516/29654614-776f844c-88e0-11e7-9701-36b0ae048680.png)

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
