### ISSUE TITLE
Cannot install phantomjs

### ISSUE THREAD

**Issue by yang378848032** [eclipse-che/che#4872]
I want to build che code,request install phantomjs,exec  npm install -g phantomjs,show error msg.
npm ERR! Linux 3.13.0-101-generic
npm ERR! argv "/usr/local/node/node-v4.8.2-linux-x64/bin/node" "/usr/local/node/node-v4.8.2-linux-x64/bin/npm" "install" "--ignore-ssl-errors=true" "-g" "phantomjs"
npm ERR! node v4.8.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@2.1.7 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /etc/npm-debug.log

**Comment by ghost** [comment]
@yang378848032 please provide information on the environment you have.

**Comment by ghost** [comment]
@yang378848032 any update on this please?

**Comment by ghost** [comment]
Closed due to inactivity.
