### ISSUE TITLE
The panel for resizing the Processes panel is barely visible when switching to the "Light theme" style

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4874]
**Reproduction Steps:**
Start a workspace and switch to the Light Theme in the Preferences menu
Try to resize the Processes panel

Che version: 5.9.0-SNAPSHOT
OS and version: Ubuntu 16.04 LTS
![resize](https://cloud.githubusercontent.com/assets/7760565/25277090/fb245fb2-26a5-11e7-95aa-f8759a01679a.gif)

**Comment by vparfonov** [comment]
@slemeur do you have ideas?

**Comment by ghost** [comment]
Smth like a borderline will help I think

**Comment by slemeur** [comment]
Closing as won't fix as it will be revisited with the new light theme from CHE 6
