### ISSUE TITLE
Workspace machine API

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#4880]
[Docs](https://www.eclipse.org/che/docs/assemblies/sdk-rest-apis/index.html#execute-a-command-and-stream-output) vs [Issue](https://github.com/eclipse/che/issues/4553)? Where the truth? Actually, it's complicated to find out the right way to use API, swagger expose just little and docs give just examples.

**Comment by ghost** [comment]
Indeed, docs have to be updated with commands API of an exec agent. Meanwhile, you may study this https://github.com/eclipse/che/tree/master/agents/go-agents/docs

**Comment by ghost** [comment]
And here are some more up to date REST API docs that haven't been published yet - https://github.com/eclipse/che-docs/blob/master/src/main/_docs/assemblies/assemblies-sdk-rest-apis.md

If you have questions regarding any specific APIS and/or methods, go ahead and ask.

**Comment by zatsepinvl** [comment]
Ok, as an example, what should I do to run command 'mvn clean install' inside workspace?

**Comment by ghost** [comment]
https://github.com/eclipse/che/blob/master/agents/go-agents/docs/rest_api.md#start-a-new-process

**Comment by zatsepinvl** [comment]
Thanks.
