### ISSUE TITLE
Question : How to compile C++ that using external library?

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#4882]
OS : 16.04 ubuntu
Che : 5.8.1

#include <boost/thread/thread.hpp>
#include <boost/thread/mutex.hpp>

boost::mutex mutex1, mutex2;
 
void ThreadA()
{
    // Solves deadlock problem
    mutex1.lock();
    std::cout << "Thread A" << std::endl;
    mutex2.lock();
    mutex2.unlock();
    mutex1.unlock();
}
 
void ThreadB()
{
    // Solves deadlock problem
    mutex1.lock();
    std::cout << "Thread B" << std::endl;
    mutex2.lock();
    mutex1.unlock();
    mutex2.unlock();
}
 
void ExecuteThreads()
{
    boost::thread t1( ThreadA );
    boost::thread t2( ThreadB );
 
    t1.join();
    t2.join();
 
    std::cout << "Finished" << std::endl;
}
 
int main()
{
    ExecuteThreads();
 
    return 0;
}

i have the above C++ code that using external library, so how should i compile using this compile CLI `g++ thread.cpp -o thread -L/usr/lib -Lbuild -L. -lboost_system -lboost_thread` inside Che?

p/s : iostream can not be paste in, need to include also

**Comment by ghost** [comment]
@thyeun have you tried authoring a command or executing the same command in a terminal? I am not sure I understand what issues you have faced with this in Che.

**Comment by thyeun** [comment]
@eivantsov, afternoon, when you compile C++ using Che, for an example, using `g++ abc.cpp -o abb.out` to do compilation. but if i'm using external library as inside the code `thread.hpp`, if i'm using the same compilation way, i will getting error (terminal/run inside Che).

And even i'm using the correct compilation way `g++ thread.cpp -o thread -L/usr/lib -Lbuild -L. -lboost_system -lboost_thread` (this one can compile not inside Che) but getting error inside Che (terminal/run inside Che).

i'm doubt that the CPP images are not including the extra library.....

**Comment by ghost** [comment]
@thyeun yes, quite possibly some libs are missing in the default cpp image. Any hints on what those libs might be?

Looking at your compilation command, I'd try smth like this in a terminal and compile it again:

`sudo apt-get update && sudo apt-get install libboost-system-dev libboost-thread-dev -y`

**Comment by thyeun** [comment]
`sudo apt-get install libboost-all-dev` this will install the fullset of the extra library.

hope it can be include into the CPP image.

**Comment by ghost** [comment]
I don't think it's a big problem.I'll update the issue once the image is updated.

**Comment by thyeun** [comment]
@eivantsov, ok thanks!!!

**Comment by thyeun** [comment]
i getting below error when try using `sudo apt-get update && sudo apt-get install libboost-system-dev libboost-thread-dev -y`

![selection_016](https://cloud.githubusercontent.com/assets/1939446/25307455/cf12830c-27d3-11e7-8b0f-1cb1738e86f0.jpg)

**Comment by ghost** [comment]
Looks like a warning to me... Has the command finished execution?

**Comment by thyeun** [comment]
Hanging there almost 20mins, i will try it on terminal also, see what happen.

**Comment by thyeun** [comment]
using terminal for the library installation, is OK!

using execution way to done the installation, it will hanging there!

**Comment by ghost** [comment]
Are there any user prompts during the installation? If so, then installing in a terminal or creating a custom stack (so that the required packages are already there) is the only way to go for now.

**Comment by thyeun** [comment]
@eivantsov, no user prompts during the installation.

**Comment by ghost** [comment]
It looks like the the last line of the output is displayed but the installation is a success. You may modify your command this way:

`sudo apt-get update && sudo apt-get install libboost-system-dev libboost-thread-dev -y && echo "Installation completed!`"

**Comment by thyeun** [comment]
@eivantsov, good result, no hanging! thanks~

**Comment by ghost** [comment]
Great! I am closing the issue then.

**Comment by BallisticBill** [comment]
Can I ask what IDE you are using?
