### ISSUE TITLE
Wish : To have a special t-shirt to all contributor/communities

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#4883]
I been follow Codenvy and Che quite a long time.
hope that Codenvy or Eclipse foundation can have a whole new Codenvy or Che new t-shirt for all the contributor/communities

Same like the below 
![image_043](https://cloud.githubusercontent.com/assets/1939446/25307004/e32ca2ee-27cb-11e7-9176-097af4f91e3b.jpg)

:)

**Comment by TylerJewell** [comment]
@JamesDrummond @bmicklea - oh yeah!!

**Comment by thyeun** [comment]
@TylerJewell, sorry for my bad to come out this wish, but i been wearing the blue t-shirt during my office hours, alot of my colleagues wish to have one also. 

:)
