### ISSUE TITLE
Unable to open this guide docs

### ISSUE THREAD

**Issue by yang378848032** [eclipse-che/che#4885]
some guide docs cannot open like this.

Extension Development

An extension is a set of code and resources that are packaged into a plugin that alter the behavior of the system. Extensions can be IDE extensions, workspace extensions (they are injected into the workspace agent running within each workspace), or Che extensions (injected into the Che server). Extensions are authored in Java and maven, and then packaged into JAR / ZIP files for deployment into Eclipse Che.

    Extension Intro
    Developing Extensions
    JSON Extension Tutorial
    Authoring Extensions in Che
    Authoring Extensions in Eclipse
    Authoring Extensions in IntelliJ
    Dependency Injection
    Extensions Packaged With Che
    Extension SDK JavaDoc

**Comment by ghost** [comment]
@yang378848032 please be more specific. Broken links?

http://www.eclipse.org/che/docs/ here are Che docs

**Comment by yang378848032** [comment]
@eivantsov In this link[](https://github.com/eclipse/che/blob/master/CUSTOMIZING.mdl),most link cannot open. such  as 'Extension SDK JavaDoc',tip:error 404.

**Comment by yang378848032** [comment]
@eivantsov [https://github.com/eclipse/che/blob/master/CUSTOMIZING.md](url)

**Comment by yang378848032** [comment]
@eivantsov in this link [https://github.com/eclipse/che/blob/master/CUSTOMIZING.md](url),some link cannot open. such as [Extension SDK JavaDoc](url) .tip error 404

**Comment by TylerJewell** [comment]
Looks like that page didn't get updated after we refactored all of the new SDK docs.  @yang378848032 - all of the docs that we have are labeled "SDK" in the docs section. Those links were just pointers to older docs that we have.

@bmicklea - let's get someone to take an hour and update this page with proper links. Many of the links are no longer needed given the new structure of the SDK. So we need to relabel things properly as well along with updating the links.  Also, does this mean that the extend page on the eclipse.org site is also filled with broken links?

**Comment by yang378848032** [comment]
@TylerJewell Can you give me a full api guide docs?I need to know some class and their function for extension.

**Comment by TylerJewell** [comment]
Everything that we have is either located in:
1. http://www.eclipse.org/che/docs, or:
2. In our Swagger documentation, for which you can navigate all of the APIs live while running Che.  See the REST API docs for how to get the URL for accessing the various Swagger APIs.
