### ISSUE TITLE
Eclipse Che JS Linter doesn't analyze the JS code on the fly.

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#4886]
Whenever I edit a JS File, the linter has to always wait for the save event to update it's analysis. It wuld be nice if the JS Linter lints on the fly without waiting for the file to be saved.

**Comment by ghost** [comment]
@sr229 doesn't auto save help the situation? As soon as you stop typing, the linter shows you errors.

**Comment by sr229** [comment]
@eivantsov it does a bit but the linter should **always** lint IMHO regardless if the file changed is saved or not. Take for example, Cloud9's JS Linter which observes unsaved file changes and lints it without waiting for the file to be saved.

**Comment by ghost** [comment]
Marking it as a bug since for me, linting does not show errors on the go and the file needs to be closed and opened to see errors. This makes all Orion js support pretty much useless.

**Comment by sr229** [comment]
Can verify the said issue at my end. Orion's JS support does not work in Codenvy 5.14.0

**Comment by ghost** [comment]
Even though I wouldn't say that

> Orion's JS support does not work in Codenvy 5.14.0

this is a nasty bug indeed.

**Comment by sr229** [comment]
Might be able to be fixed by #5330 as Monaco has native JS support.

**Comment by SkorikSergey** [comment]
Is this still an issue?

**Comment by sr229** [comment]
@SkorikSergey it's persistent on my end, probably a Orion-related bug

**Comment by eivantsov** [comment]
Closing as it cannot be solved on Che side.
