### ISSUE TITLE
The test runner console does not show result of tests

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4894]
**Reproduction Steps:** Create for example the console java application application from wizard. Run the test class from the project

**Expected result:** we should get the result of just run test
**Actual result:** the console is empty
![selection_035](https://cloud.githubusercontent.com/assets/1640058/25329300/e191ebf6-28e3-11e7-83db-5c63a67515e4.png)

**Environment:** chrome browser, ubuntu 14.TLS, server location: nightly.codenvy-stg.com

**Related selenium tests:** JavaTestPluginJunit3Test, JavaTestPluginJunit4Test, JavaTestPluginTestNgTest

**Comment by davidfestal** [comment]
This is not the test console output. This is the place for the stack trace of failed test to be displayed. But in the first implementation of the Testing support only the failed tests were shown in this stacktrace panel. So it was never empty. Now that I added the ability to also show successful tests, it is empty for successful tests.

The real-time test output console is provided as an additional `Tests` tab in the `Processes` view.

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT
