### ISSUE TITLE
Command execution rest API

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#4897]
I try to use API from this [docs](https://github.com/eclipse/che/blob/master/agents/go-agents/docs/rest_api.md). Command starts successfully, but I don't understand how to create channel to pass it as an argument (POST /process?channel=channel-1&types=stderr,stdout body...) and then subscribe to it to listen events.

**Comment by voievodin** [comment]
Hi @zatsepinvl!

`channel` is an identifier of websocket connection which you get when connect to the exec-agent using its [Websocket API](https://github.com/eclipse/che/blob/master/agents/go-agents/docs/ws_api.md), the exact event is [Connected](https://github.com/eclipse/che/blob/master/agents/go-agents/docs/events.md#connected).

So there are 2 APIs
- REST
- Websocket 

We're using websocket API throughout our clients(at least those i know) so there is always a channel(websocket connection) which receives API requests from client and responds back with events.
Nevertheless REST API allows you to play around the channel handling more complex use-cases, e.g. you want to execute a command but don't want to stream its output or you want to stream it but using existing channel. 

So i would recommend you to try and use [Websocket API](https://github.com/eclipse/che/blob/master/agents/go-agents/docs/ws_api.md) instead as it was designed exactly for this purpose(commands execution & output streaming), once you execute the command you get its output back. 

I hope I helped. Have fun!

**Comment by zatsepinvl** [comment]
That's enough. Thanks.
