### ISSUE TITLE
404 /admin

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#490]
Whenever I load the ui through a browser, I see this in the console:
GET http://xxx.net/admin/ 404 (Not Found)
This happens in a remote or local browser.

**Comment by ddementieva** [comment]
It's a known bug. Dev team will take a look. Thanks for letting us know.

**Comment by TylerJewell** [comment]
@ddementieva, @benoitf, @ashumilova - when I load 4.4.2 UD, I get two 404 not found error messages.  Please remind me, are these necessary as some sort of test?  Something in my memory tells me that these GET requests are necessary for a test.  If not, we should include the favicon, and get rid of the test for /admin/ in any Che scenarios.

```
/admin/
/favicon.ico
```

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-588

**Comment by TylerJewell** [comment]
@ddementieva - can you cross link the appropriate GitHub issue?

**Comment by ghost** [comment]
@TylerJewell this is the appropriate GitHub issue

**Comment by TylerJewell** [comment]
I cannot reproduce this - so believe this is resolved now.
