### ISSUE TITLE
Change terminal cursor color into white

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4901]
**Reproduction Steps:**
Start a workspace and switch to the Light Theme in the Preferences menu
In the Terminal run the Midnight Commander and open any file for editing

**Observed behavior:**
Cursor is barely visible on blue background.

**Che version:** 5.9.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25340389/444e599e-290e-11e7-9dc0-c66803876971.gif)

**Comment by slemeur** [comment]
Let's put the cursor into white. It will fit this kind of use cases.

**Comment by vparfonov** [comment]
@slemeur can you provide priority label for this issue?

**Comment by SkorikSergey** [comment]
Not actual.
