### ISSUE TITLE
Improvements for terminal UI

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4902]
This is the current Ui of the process panel needs to be improved:
![screen shot 2017-04-24 at 18 30 06](https://cloud.githubusercontent.com/assets/1636769/25347774/446545d8-291c-11e7-945f-29b3484b92dc.png)

*Process tree*
- [ ] Remove the "dev" tag
- [ ] Rework the position of the "terminals" and "processes" nodes under a machine, so they look better aligned (whole node elements should be more to the left, as in the project explorer, and t). 

*Terminal Margings*
At this moment we have some inconsistency with the margings. I think those inconsistency are coming from the scrollbars. 
![marging-terminals](https://cloud.githubusercontent.com/assets/1636769/25349220/4d630b3e-2921-11e7-9392-801a1bca0770.png)

We need to make sure that:
- between process and terminal, we have the same marging.
- we have the same marging (=1px) left-right-top-bottom
- The left alignement of 'command' + 'preview' is consistent with the outputs

If needed, we will display the scrollbars with transparency over the content.

**Comment by vitaliy-guliy** [comment]
What shall we do with non-dev machine / target ?
Do we need to remove tags?

![processes-1](https://cloud.githubusercontent.com/assets/1655894/25472100/8248db54-2b32-11e7-812e-716a9d51080d.png)

**Comment by slemeur** [comment]
Yes let's remove the tags at this moment.
