### ISSUE TITLE
Focus lost after adding macros

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4906]
**Reproduction Steps:**
- Create spring project
- Go to the commands editor 
- Click on the "Macros"
- Add any macros  
- Pay attention to the screen 

**Expected Behavior:**
Editor field stay focusable after added macros

**Observed Behavior:**
Editor field does not stay focusable

**Attachment:**
![anim](https://cloud.githubusercontent.com/assets/22724619/25384169/f3cd69c8-29c7-11e7-8ef3-bcb3bdb57cbe.gif)

**Comment by ghost** [comment]
Fixed in 5.15-SNAPSHOT
