### ISSUE TITLE
Non-DevMachine information through macros

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#4912]
Working on converting a multi-machine project from production to a workspace recipe I was not able to effectively reference exposed port number of machines other than dev-machine. This was a pretty big problem for me (and other users) as there were client side calls to other containers that needed to be made. Currently I have to manually set the ephemeral ports assigned to these machine's exposed port manually in a configuration file in the projects folder. Below is a proposed solution.

| Macro   | Details
| --- | ---
| `${machine.<name>.<port>}`	| Returns protocol, hostname and port of an internal server for a machine named `<name>`. <port> is defined by the same internal port of the internal service that you have exposed in your workspace recipe. 
| `${machine.<name>.<port>.protocol}`	| Returns protocol of a server registered by name for a machine named `<name>`
| `${machine.<name>.<port>.hostname}`	| Returns hostname of a server registered by name for a machine named `<name>`
| `${machine.<name>.port.<port>}`	| Returns the hostname and port of a service or application you launch for a machine named `<name>` . 

Example: 
 `${machine.db.<port>}` for the petclinic project using the `java mysql` stack would return the protocol, hostname and port of the workspace machine `db` not `dev-machine`.

Codenvy 5.8.1

**Comment by ghost** [comment]
@JamesDrummond can you elaborate on what you are trying to achieve? You just want to be ble to execute commands against a non-dev machine and be able to use IDE macros in the commands editor?

Or do you expect such macros to work outside the IDE?

**Comment by JamesDrummond** [comment]
Inside IDE. There are cases where I will run a command on one machine like `dev-machine` but need exposed port information on another machine like `db`. Not sure this is a great example but lets say the `dev-machine` hosts a tomcat server application . If the client side of the server application needs direct access to `db` container resource via exposed port there is no way to do this currently with resorting to manually entering the ephemeral port of `db` container.

As an example I would like the following to be able to work:
```
// Command ran on dev-machine
echo "Exposed external ephemeral port of db machine: ${machine.db.port.3306}"
```

**Comment by ghost** [comment]
Why do you need exposed port? You can talk to db machine directly

**Comment by JamesDrummond** [comment]
You can talk to the machine `db` directly from `dev-machine` but not from client side that would be on remote machine like a user's browser.
