### ISSUE TITLE
A duplicated stack always exists in the "Stack library" list

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4913]
**Reproduction Steps:**
Create  a duplicated stack from any predefined stack.
In the duplicated stack settings click on **Ready-to-go** button.

**Expected behavior:**
While creating a workspace this stack exists only on the **Ready-to-go Stacks** list.

**Observed behavior:**
This stack exists in the **Stack library** list too.

**Che version:** 5.9.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![stackscategory](https://cloud.githubusercontent.com/assets/7760565/25389823/4ca0c240-29da-11e7-9cab-aadcbede7f8a.gif)

**Comment by ghost** [comment]
Expected behavior. All stacks are in stacks library, and ready to go stacks are just filtered by scope
