### ISSUE TITLE
Diagnostics would spin up a empty stack but doesn't delete it

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#4916]
Done on a local Copy

**Reproduction Steps:**
1:) Run Diagnostics
2:) Expected Diagnostics workspace to be deleted after diagnostics has finished but diagnostics stack stays on there.
**OS and version:**   Che 5.8.0 on Docker Toolbox on Windows 10 1607

**Comment by ghost** [comment]
Marking it as an enhancement.
