### ISSUE TITLE
CHE-589 Broken project tree

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#492]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-589
Reporter:  Daria Dementieva
Description: Java files are not displayed in the project tree if the project type is Blank.

Steps to reproduce:
1. Import project https://github.com/che-samples/console-java-gradle. 
2. Open it in the IDE.
3. Open /src directory.

As a result, project tree is broken and Java files are not displayed.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/pull/523
