### ISSUE TITLE
Commands are not removed after deleting related project

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#4938]
After creating a project we have several default commands, but when the project was deleted, commands still are in the Commands Panel. After refreshing IDE commands disappear.

**Reproduction Steps:**
1. Create some project (for example spring-sample);
2. Delete the project;
3. Go to the Commands panel, all commands related to the deleted project still are here.

**Comment by ghost** [comment]
Indeed, if the command is applicable to a particular project and this project gets deleted, the described behavior is true.
