### ISSUE TITLE
CHE-591 Clean up plugin installer

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#494]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-591
Reporter:  Tyler Jewell
Description: 1. Add in the logback logger to eliminate errors.
2. Error in IF logic where skipping wasn't updated.
3. Update to support latest assembly structure.
4. Print out all directories in DEBUG mode.

**Comment by ddementieva** [comment]
Fixed
