### ISSUE TITLE
There is a duplicate commands goal in a project context menu after changing a command settings

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4940]
**Reproduction Steps:**
From the Commands Explorer in one of  goal(for example "Run") create at least two command.
Do some change for one command and click Save button.

**Observed behavior:**
In Commands context menu are two "Run" goals.

**OS and version:**
Che(Che6 branch) 6.0.0-M5; Chrome 63.0; Fedora 25
![anim](https://cloud.githubusercontent.com/assets/7760565/25481017/09764a82-2b54-11e7-8eaf-596417ea0d5d.gif)

**Comment by ghost** [comment]
Reproduced in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
![teams-11-5](https://user-images.githubusercontent.com/7760565/30917881-ac6eb0f2-a3a5-11e7-9720-10d19305a57e.gif)

**Comment by SkorikSergey** [comment]
This issue is actual for Che 6.11.0-SNAPSHOT.
