### ISSUE TITLE
Add new terminal feature works wrong after closing split pane

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4941]
**Reproduction Steps:**
1. In the **Processes panel** create a new **Pane** and add a terminal to it.
2. Close this **Pane** and don't click on the **Processes panel**.
3. Add a new terminal.

**Expected behavior:**
The new terminal added to the **Processes Panel**.

**Observed behavior:**
The new terminal tab isn't visible on the **Processes Panel** but exists in the **Machines tree**. 
If after closing **Pane**(step 2) click on the **Processes panel** a new terminal creates correctly.

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25482473/b1a05d14-2b5a-11e7-87f8-a9c9922e9c17.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5
