### ISSUE TITLE
Question : Issue on python 3.5 images

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#4945]
OS : 16.04 ubuntu
Che : 5.9.1

I have make a working Eclipse Che indicator by using python, but when i try it to compile on Eclipse Che (i been install all the library and ect dev package) but still cant make it. So, it is something missing on python 3.5 images.

Below are the working code, while compile outside of Eclipse Che.

```
import os
import signal
import json
import subprocess
import gi

gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')


from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator


APPINDICATOR_ID = 'myappindicator'

def main():
    indicator = appindicator.Indicator.new(APPINDICATOR_ID, os.path.abspath('/home/thyeun/Pictures/type-che.png'), appindicator.IndicatorCategory.SYSTEM_SERVICES)
    indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
    indicator.set_menu(build_menu())
    gtk.main()

def build_menu():
    menu = gtk.Menu()
    item_start = gtk.MenuItem('Start Che')
    item_start.connect('activate', start)
    menu.append(item_start)
    item_stop = gtk.MenuItem('Stop Che')
    item_stop.connect('activate', stop)
    menu.append(item_stop)
    item_che = gtk.MenuItem('Eclipse Che')
    item_che.connect('activate', che)
    menu.append(item_che)					
    item_quit = gtk.MenuItem('Quit')
    item_quit.connect('activate', quit)
    menu.append(item_quit)
    menu.show_all()
    return menu

def start(_):
    subprocess.call('/home/thyeun/Desktop/che-start.sh')
    return start	

def stop(_):
    subprocess.call('/home/thyeun/Desktop/che-stop.sh')
    return stop

def che(_):
    os.system('/opt/google/chrome/chrome --profile-directory=Default --app-id=cagdgppejagmigblhodalodfhllclleg')	
    return che

def quit(_):
    gtk.main_quit()

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    main()`

```

Below is the **error message** while compile inside Eclipse Che (terminal and execution)

![selection_024](https://cloud.githubusercontent.com/assets/1939446/25494292/c7040c5e-2bab-11e7-8e34-6600a6c17fb9.jpg)

**Comment by ghost** [comment]
@thyeun a couple of issues I see at a first glance:

1. Have you `pip install` modules that you import?
2. In your Python script you use paths that do not exist in a workspace - `/home/thyeun/...` This is your local host path
3. In your Python script you call Google Chrome - `/opt/google/chrome/chrome`. Python 3.5 image does not have gui support. You will need to install x server and a vnc server/client to be able to develop gui apps.

**Comment by thyeun** [comment]
@eivantsov, i try also pip, but cant also, for the path is can be change later, and the last one, that actually not a gui, it is created using google chrome "add to desktop" apps (i already have that desktop apps).

problem is ```gi``` even i install at the terminal (success install) but still come out no module ```gi```.

**Comment by thyeun** [comment]
@eivantsov, compile outside of che (local compile), result show below

![unity-panel_018](https://cloud.githubusercontent.com/assets/1939446/25517632/e15524d6-2c22-11e7-9447-5846a4668c24.jpg)

![menu_022](https://cloud.githubusercontent.com/assets/1939446/25517660/f9303bf4-2c22-11e7-9d88-00193361f065.jpg)

**Comment by ghost** [comment]
You won't be able to achieve the same in this image. No gui support. Unless, this is a webapp.

Here's a Dockerfile for Python 3.5 image - https://github.com/eclipse/che-dockerfiles/blob/master/recipes/ubuntu_python/Dockerfile

When I try your script and run `sudo pip install gi` i get a different error - from `gi` itself.

**Comment by thyeun** [comment]
@eivantsov, oh ok, that is why even i success install ```gi```, but still come out no module.

thanks, i'm too stupid (didn't understand the background story). and sorry for trouble you.
