### ISSUE TITLE
`chedo` A terminal command to trigger ide actions

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#4949]
It would be nice if from the terminal we could have a command to trigger action in the IDE. For instance:

in the terminal in che :

    chedo openFileAction myProject/pom.xml

would open the file in the IDE !!! 

This could be very useful also when using git from the terminal:
we could configure this `chedo` command in git/config and when we have conflicts while merging:

    git mergetool

Would open the diff compare in Che Web UI

**Comment by skabashnyuk** [comment]
@sunix @slemeur do you want to keep this issue open?

**Comment by slemeur** [comment]
Thanks @sunix for this proposal. I think it's a great idea. It's something we should be considering in a native CLI for Eclipse Che.

**Comment by sunix** [comment]
this could still be useful. Same example for using git merge-tools and having the theia ide diff tool poping up

**Comment by sunix** [comment]
it would be also useful when using Reactjs app: when you have a error in the app preview, and click on the source code, it would use REACT_EDITOR to open the editor (atom or code or any other command to run from the command line). If we could make that cli available by default and set REACT_EDITOR by default to that (and maybe others ...) it would be really cool.

**Comment by sunix** [comment]
WIP: https://github.com/che-incubator/chedo

/remove-lifecycle stale
