### ISSUE TITLE
"Go into" item in context menu does not exist after used it in other module

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4953]
**Reproduction Steps:**
- Go to the redhat.codenvy-stg.com
- Import some project by git
- Open context menu on some folder and click on "Go into"
- Click "Workspace" -> "Import Project" -> and import the same ptoject from git
- Try to use "Go into" in any folder of the new project .

**Expected behavior:**
- "Go into" will be existed .

**Observed behavior:**
- "Go into" is not exist .

**Attachment:**
![anim](https://cloud.githubusercontent.com/assets/22724619/25526653/33e709a4-2c1d-11e7-9272-3fbfaff2ec26.gif)

**Comment by musienko-maxim** [comment]
A think the same with: https://github.com/eclipse/che/issues/1853. Looks like duplicated

**Comment by Ohrimenko1988** [comment]
Duplicated https://github.com/eclipse/che/issues/1853
