### ISSUE TITLE
Issues with restoring debugger state

### ISSUE THREAD

**Issue by bartlomiej-laczkowski** [eclipse-che/che#4956]
While investigating issue [#1952](https://github.com/codenvy/codenvy/issues/1952) I have found that there are some general problems with restoring debugger state on IDE side while working with CHE:
- When user starts debug session for particular debugger type and stops the workspace (without stopping debug session) it can not be started once again after workspace restart. It is true for different debugger types.
- When debug session is started in one workspace it can not be started in another workspace for the same debugger type (nothing happens when trying to start debug session)

Removing debug configurations or creating new ones for affected debugger type doesn't help at all.

After some digging I have found that the problem is related to the way how the debug session state is being preserved/restored with the use of browser local storage (in particular usage of AbstractDebugger#LOCAL_STORAGE_DEBUGGER_SESSION_KEY and AbstractDebugger#LOCAL_STORAGE_DEBUGGER_STATE_KEY). It looks like this storage keys are not being cleaned up after workspace shutdown what may lead to inconsistent state after workspace restart. Another problem is that this keys are global for different workspaces which prevents running debug sessions in more than one workspace.

Soon I will send a pull request with the fix proposal.

**Reproduction Steps:**

As described above.

**OS and version:**    

CHE 5.x.x and browsers with local storage support. 

**Diagnostics:** 

Not relevant.

**Comment by bmicklea** [comment]
@tolusha - FYI

**Comment by ghost** [comment]
I think this has been fixed. @bartlomiej-laczkowski feel free to reopen though if the problem persists.
