### ISSUE TITLE
Command still exists in the Commands Editor after deleting

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4958]
**Reproduction Steps:**
Create any project with commands and open a command in the **Commands Editor**.
Change the command name and without saving delete it.

**Expected behavior:**
The command deleted from the **Command Explorer** and the **Commands Editor**.

**Observed behavior:**
The commands is still exist in the **Commands Editor**.

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25529823/68062850-2c2c-11e7-87c3-ceb4a1fdcc9a.gif)

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
