### ISSUE TITLE
Workspaces list is broken while create a new factory

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4959]
**Reproduction Steps:**

- **Factories** -> **Create Factory**
- In the **New Factory From** click on **Git** tab and then to the **Workspace** tab
- In the **Workspace** tab click on **Search** field

**Observed behavior:**
List of workspaces is broken

Che version: 5.10.0-SNAPSHOT
OS and version: Ubuntu 16.04 LTS
![factoriesbrockenlist](https://cloud.githubusercontent.com/assets/7760565/25531570/e722700c-2c32-11e7-9c72-e3a4c0996265.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT
