### ISSUE TITLE
No feedback from ui when starting workspace

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#496]
If a workspace is stopped, and I press Run to start, there is no feedback at all from the UI.  If (when) the container fails to start, there is no feedback from the UI.

**Comment by siliconalchemy** [comment]
Same if the workspace is successfully created.  I'm running nightly build from today (24.02.2016) and when I 'create' a workspace it creates the workspace in the ui but clearly not on the backend.  The first time I hit run it then goes away in the background and creates the actual docker container and injects the magic stuff.
Also no response from the ui when I stop a running workspace.  I have to refresh the browser to get the actual state of the workspace.

**Comment by ghost** [comment]
Hello,

This is a known issue. The team is working on it.

**Comment by siliconalchemy** [comment]
This is working in today's nightly build (25.02.2016) :)
