### ISSUE TITLE
Java packages are not displayed in the spring project after upload project from zip 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4960]
**Reproduction Steps:**
- Go to the spring project.
- Upload project from zip.
- Pay attention to the screen.

**Expected result :**
Java packages will be displayed in the project .

**Observed behavior :**
Java packages are not display .

**Attachment :**

![anim](https://cloud.githubusercontent.com/assets/22724619/25532382/dea18424-2c35-11e7-97ef-83cd18286321.gif)

**Comment by ghost** [comment]
Cannot reproduce in 5.15-SNAPSHOT
