### ISSUE TITLE
The Processes panel button for downloading a log file doesn't have tooltip message

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4962]
**Reproduction Steps:**

- Create a project with commands and start any
- Hover cursor on button for downloading a log file in the **Processes panel**

**Observed behavior:**
There is not tooltip message

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25532299/9a407718-2c35-11e7-94ed-28794b73bc72.gif)

**Comment by ghost** [comment]
Reproduced in 5.15-SNAPSHOT

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa @RomanNikitenko @vparfonov @eivantsov is this up to date issue or we just forgot to close it?

**Comment by SkorikSergey** [comment]
This issue is actual for Che 6.8.0-SNAPSHOT.

**Comment by SkorikSergey** [comment]
Not actual.
