### ISSUE TITLE
Does ws-agent require JDK?

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#4963]
I'm getting the below error when starting a ubuntu workspace using a base image that doesn't have JDK.

```
[STDOUT] 2017/04/28 10:20:12 Terminal routes:
[STDOUT] 2017/04/28 10:20:12 ✓ Connect to pty(webscoket) ............... GET    /pty
[STDOUT] 2017/04/28 10:20:12 
[STDERR] /bin/sh: 57: [: Illegal number:  <<<<<<<<<<<<<<<<<
[STDOUT] Reading package lists...
[STDOUT] Building dependency tree...
[STDOUT] Reading state information...
[STDOUT] software-properties-common is already the newest version (0.96.20.6).
```

I think this refers to https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.script.sh#L57

Is JDK required to use the ws-agent? We are developing with PHP in the ws not Java and the [docs](https://eclipse.org/che/docs/devops/runtime-recipes/index.html#other-optional-dependencies) seem to imply it isn't required.

*Dockerfile in use https://github.com/outeredge/edge-docker-che-base/blob/master/Dockerfile*

**Comment by ghost** [comment]
@davidwindell yes, jdk is required for a workspace agent.

And it looks like a bug in a bash script. Testing it on a clean ubuntu image now.

**Comment by ghost** [comment]
I have just created a workspace from the following recipe

```
FROM ubuntu:16.04
CMD tail -f /dev/null
```

**Comment by davidwindell** [comment]
@eivantsov I was able to create the workspace just fine, but the error was in the logs still

**Comment by ghost** [comment]
Yeah, got it. Will issue a PR to fix it.

**Comment by davidwindell** [comment]
Just to check, Maven isn't required for this setup is it?

**Comment by ghost** [comment]
Maven isn't required for a non-java workspaces.

And here's a PR that fixes script error https://github.com/eclipse/che/pull/4971

Generally, I recommend that you inherit from `eclipse/stack-base:ubuntu` in your custom recipe.

**Comment by davidwindell** [comment]
👍 would be good to get an official Alpine base image
