### ISSUE TITLE
Allow to configure and see default commands per goals

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4966]
# Goal
The goal of this enhancement is to allow the user to configure and see default commands per goals. At this moment, the only way for the user to select the default commands are to use the goal's button. There is no way to see and configure those default command for a particular workspace. So when sharing a workspace, there are no default commands associated with the buttons. 

##  Sub-tasks

We will:
- [ ] Materialize the default commands in project explorer by adding "(default)" after the name of the command.
- [ ] Allow user to select the default command for the goal by using a contextual menu (right-click on the command): "Set as default".

**Comment by skabashnyuk** [comment]
@slemeur do you want to keep this issue?

**Comment by slemeur** [comment]
Close as won't fix - to be reconsidered with the switch to Theia IDE
