### ISSUE TITLE
Add contextual menu for commands in Commands Explorer

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4967]
# Goal
The goal of the issue is to allow contextual actions on commands displayed in the commands explorer. 

We need to allow right-click actions in the commands explorer to:
- Run
- Delete
- Duplicate
- Set as default (see #4966)

**Comment by skabashnyuk** [comment]
@slemeur do you want to keep this issue?

**Comment by slemeur** [comment]
Closing as won't fix with the upcoming switch to Theia IDE
