### ISSUE TITLE
Commands Chaining Automator

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4968]
# Goal
The goal of this epic is to allow chaining of commands. A user must be able to define a sequence of commands and make their execution chained: either parallelized or sequentially. 
The chaining automator script would also have the ability to require new containers to be spined-up in order to parallelized more operations.

We should provide the ability for the user to define those chains with a custom editor. 
The editor could either be based on a form, or better with a visual editor (with a palette and drag&drop capabilities). 

# Sample Use Cases
*Production Environment replica*
The environment used for building a project might be different from the environment used to run it. To build and code on a project, there might be dedicated dependencies (aka dev-machine) which are useless in a runtime environment.

*Parallelized test execution*
Running selenium test in parallel, on dedicated containers spined-up just for faster execution.

**Comment by ghost** [comment]
Was this already implemented? I would love to be able to run two different java programms at the same time... However I am not sure wether the command is the right tool for this purpose

**Comment by TylerJewell** [comment]
This spec has not been implemented.  But you do not need this feature. You can run as many commands in parallel as you want today.  Just launch them as you see fit.

**Comment by skabashnyuk** [comment]
@slemeur do you want to keep this issue?

**Comment by slemeur** [comment]
Yes, that is something to keep in the backlog. 
> A user should be able to define a sequence of commands and make their execution chained: either parallelized or sequentially.

**Comment by gorkem** [comment]
Related https://github.com/theia-ide/theia/issues/5517
