### ISSUE TITLE
Git preferences for command line

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#4969]
Setting git preferences such as ssh keys should also configure the command line git. Users should be able to do a commit and push identically without doing any additional configuration from UI an terminal.

**Comment by ghost** [comment]
Maybe when starting a workspace, we should grab all ssh keys from user prefs and inject them into `~/.ssh` so that native git installed in a workspace can use them?

**Comment by sunix** [comment]
problem is when multiple users can access to the workspace, would you let another user to perform a `git push` with your ssh keys ?

**Comment by ghost** [comment]
Yes, exactly! We already have a solution by launching a script that will get all git prefs and save them into a workspace.

**Comment by davidwindell** [comment]
@sunix see https://github.com/eclipse/che/issues/4715#issuecomment-292089667
