### ISSUE TITLE
Enhancement : Desktop GUI for Eclipse Che

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#4972]
Any possible for Eclipse Che to running X11 (VNC server) in a workspace with a desktop plugins?

Meaning that, have a VNC connection to view X11 desktop. Once a success connection are make, the X11 view will appear on a workspace tab.

It will be very useful for the programmer that need to develop GUI using Eclipse Che.

**Comment by bmicklea** [comment]
@eivantsov

**Comment by sunix** [comment]
You can try ssh -X (ssh with X forward) https://twitter.com/sunsengdavidtan/status/730880109805207552
For GTK apps, you can also try broadwayd ... but some apps are buggy with it https://twitter.com/sunsengdavidtan/status/839082778104901632

**Comment by ghost** [comment]
We do have a certified image with VNC. You may want to take a look at this tutorial http://www.eclipse.org/che/docs/tutorials/swing/index.html

**Comment by thyeun** [comment]
@sunix, do you have any step by step to configuration for both client and server to make eclipse Che working on X-11, i'm kind of new to this, and kindly help me up with it

thanks in advanced

**Comment by ghost** [comment]
http://www.eclipse.org/che/docs/tutorials/swing/index.html

**Comment by sunix** [comment]
@thyeun This how you can do it with ssh. I can write a full blog post later if you like :) If you want to use vnc, you can follow @eivantsov links

In the process panel, che shows you how to connect using ssh:
![eclipse che che-openshift-con - google chrome_019](https://cloud.githubusercontent.com/assets/650571/25669419/bf460422-3029-11e7-8167-b2657054e209.png)

I just add `-X` to the ssh command (in my case I've uploaded my ssh public key so no password to enter):

    ssh user@172.17.0.1 -p 33475 -X

and then if you run in this terminal any X11 app (In my case I have eclipse neon installed in my workspace):

    ./eclipse/eclipse

![workspace 1_020](https://cloud.githubusercontent.com/assets/650571/25669687/85a15b62-302a-11e7-86f8-844c660fd9e0.png)

**Comment by thyeun** [comment]
@sunix, thanks, you save my life, i'm make things into more complicated way (by setting client and server with the ./.ssh/config) .....and so on!!!

And kindly let me play abit, if still hanging here n there, possible to consult you?

@eivantsov, will try it also 

And lastly thank you both of you

**Comment by thyeun** [comment]
@sunix for the upload key, after i created the ssh key ```ssh-keygen -t rsa -C "user@172.18.0.1" ```, than inside che, i should go to "preferences" than upload the key right?

**Comment by ghost** [comment]
@thyeun once the key is generated, you do not need to save it in prefs

**Comment by thyeun** [comment]
@eivantsov, still can not make it work.....

**Comment by ghost** [comment]
@thyeun cannot make work what? gui app question or sshing into a container?

**Comment by thyeun** [comment]
@eivantsov getting the below message

![selection_025](https://cloud.githubusercontent.com/assets/1939446/25712204/9b7b7310-3123-11e7-9eb9-3c633a831ea5.jpg)

**Comment by ghost** [comment]
@thyeun what stack is it?

**Comment by thyeun** [comment]
@eivantsov cpp stack

**Comment by sunix** [comment]
`-X` is to be used from your desktop terminal ... :)

**Comment by thyeun** [comment]
@sunix haha....thanks for corrected me, than if i want to use it on Che, which one i should use?

**Comment by ghost** [comment]
@thyeun i don't think you can use -X in a workspace terminal. There's no X-server in a workspace.

**Comment by thyeun** [comment]
@eivantsov, ok, thanks. 

@sunix, thanks 

i will close this, since i get my issue solve

**Comment by sunix** [comment]
@eivantsov it depends on your run time, if you install any software that needs X11, X11 will be installed

**Comment by ghost** [comment]
I mean ready to go stacks

**Comment by trevortknguyen** [comment]
I am sorry to comment on a closed thread. I have tried to use the SSH way and I have logged in successfully, but none of my graphical applications (like Python matplotlib) work because they throw an error on $DISPLAY not being set. I have checked the variable on the server and have not found a way for it to get it set. If I have to set that manually I do not know what to set it to.

My stack is based off of this docker image: codenvy/ubuntu_jdk8_x11 from the tutorial.

Thank you!

**Comment by ghost** [comment]
Hmm.. I have started this image, and then ran

`ssh -X user@localhost -p $port` where '$port' is a published 22 port

Then I cloned a Java swing app, built it and executed a jar:

![image](https://user-images.githubusercontent.com/5337267/26913630-da44c09e-4c24-11e7-8ce1-9de4f851da78.png)

**Comment by ghost** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
