### ISSUE TITLE
How generate getters and setters 

### ISSUE THREAD

**Issue by hc3** [eclipse-che/che#4973]
hi for all, how i can generate getters , setters , equals and hashcode in eclipse che?, i have another question... the eclipse che desktop client is working?

**Comment by bmicklea** [comment]
There are currently no auto-generate getters, setters, etc... in Che. You can use the desktop IDE with Che workspaces by [mounting and syncing the workspace to your local machine](https://eclipse.org/che/docs/ide/sync/index.html).

**Comment by ghost** [comment]
Here's a related enhancement request that has been closed though - https://github.com/eclipse/che/issues/3471

**Comment by hc3** [comment]
and about eclipse che desktop client with electron... it's work?

**Comment by ghost** [comment]
@hc3 we did some work around it, but I am not sure it's actual. You may want to take a look at https://github.com/TylerJewell/che-electron

**Comment by TylerJewell** [comment]
Unfortunately that repo is not being maintained anymore and has compilation issues.
