### ISSUE TITLE
Study to use UseStringDeduplication jvm flag for workspace agent configuration

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4977]
It can help us to reduce memory usage of agent
Proposed JVM config 
```
-XX:+UseG1GC -XX:+UseStringDeduplication 
```
See more https://blog.codecentric.de/en/2014/08/string-deduplication-new-feature-java-8-update-20-2/

**Comment by mshaposhnik** [comment]
Here is brief comparative result between current and new Java settings. 
All screenshots taken on workspace with an medium-sized Java + Maven project, loaded and idling abt. 15 mins.

Current settings | G1GC + UseStringDeduplication
---------------------|------------------------------------------
![memory_23_with_no_options](https://cloud.githubusercontent.com/assets/1651062/26063725/8224ab6c-3997-11e7-99f1-df09b191ec03.png) | ![memory_20_with_gc1_options](https://cloud.githubusercontent.com/assets/1651062/26063744/8b416ac8-3997-11e7-8d1f-30dac3010f33.png)

Fig.1  Difference in total memory consuming right after GC action. Note used memory value 50 vs 40 Mb.

Current settings | G1GC + UseStringDeduplication
---------------------|------------------------------------------
![memory_15_with_no_options](https://cloud.githubusercontent.com/assets/1651062/26057133/e096250c-3980-11e7-9b08-62adc5f6d8b1.png) | ![memory_18_with_gc1_options](https://cloud.githubusercontent.com/assets/1651062/26057139/eb0a5530-3980-11e7-9807-994d1e9de456.png)

Fig.2  Difference in total memory consuming. Note that G1GC decreases heap size more accurate.

Current settings | G1GC + UseStringDeduplication
--------------------- |------------------------------------------
![memory_16_with_no_options](https://cloud.githubusercontent.com/assets/1651062/26057207/50fee68a-3981-11e7-8e4f-d02543263f4c.png) | ![memory_17_with_gc1_options](https://cloud.githubusercontent.com/assets/1651062/26057214/57fcef40-3981-11e7-8cda-391e4f586a83.png)

Fig. 3 Memory by classes. Note significant reduction of the char[] objects size.

**Comment by mshaposhnik** [comment]
Done.
