### ISSUE TITLE
LSP didChange Parameters Wrong Line Number

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#4978]
While implementing open file handling in a test language server, I have received the following message in the language server when inserting a character at the end of a file:

```json
{
   "jsonrpc": "2.0",
   "method": "textDocument/didChange",
   "params": {
     "textDocument": {
       "version": 4,
       "uri": "file:///projects/console-java-simple/src/gurke.test"
     },
     "uri": "file:///projects/console-java-simple/src/gurke.test",
     "contentChanges": [
       {
         "range": {
           "start": {
             "line": 0,
             "character": 0
           },
           "end": {
             "line": 0,
             "character": 59
           }
         },
         "text": "textDocument/badWord:Error:asdf:A Problem\n asdf asdf g3f gsf"
       }
     ]
   }
 }
```
While reporting the whole file contents as changed is a bit overkill in this instance, that is not the problem: the problem is that the range given is simply wrong: the end of the range should be on line one, not line 0. A language server would be correct to reject this message as wrong.

**Comment by tsmaeder** [comment]
One way to fix this would be to hook up the "documentChanging" event because we could calculate the begin/end line of the range being removed at that point. Assuming there is always a "changing" even before the "changed" event, we would could calculate the range on "changing" and send it on "changed"

**Comment by tsmaeder** [comment]
Stand by for a PR.

**Comment by gorkem** [comment]
@tsmaeder What is the latest with this one?
