### ISSUE TITLE
Inner packages are lost after rename (after refresh page they are restored )

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4979]
**Reproduction Steps:**
- Go to the spring project with 
- Create some packages (see attachment)
- Choose package and press "shift + F6" 
- **Important** In the opened window **clear** input field and type package name as in attachment
- Click "Ok" button
- Pay attention to result 

**Expected behavior:**
![anim](https://cloud.githubusercontent.com/assets/22724619/25653063/ecbbd926-2ff3-11e7-966f-abf6c4e067e1.gif)

**Observed behavior:**
![anim](https://cloud.githubusercontent.com/assets/22724619/25653088/09cc6eea-2ff4-11e7-88bf-d28baf8eff35.gif)

**Additional information:**
* Related selenium test is the _RenamePackageTest_

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by riuvshin** [comment]
@vparfonov we have pretty high regression due to this, can we take this to current sprint?
