### ISSUE TITLE
Very long startup due to entropy gathering

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#498]
Che main process takes a very long time to startup - sometimes up to 10 minutes - because it uses blocking entropy gathering.   

2016-02-24 18:51:30,108[ost-startStop-1]  [INFO ] [o.a.c.u.SessionIdGeneratorBase 241]  - Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [449,673] milliseconds.
2016-02-24 18:51:30,335[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 453752 ms

This is unnecessary for a lot of development environments (and is absolutely infuriating when trying to get che working in the first place!) and there should be an option in che.sh to bypass it.  It can be bypassed by (on linux, at least) by simply adding this environment setting before running che.sh:
export JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"

Result: Startup takes 5 seconds instead of 7.5 minutes.
2016-02-24 18:52:35,449[main]             [INFO ] [o.a.catalina.startup.Catalina 638]   - Server startup in 4266 ms

**Comment by TylerJewell** [comment]
@siliconalchemy Are you doing this work on a desktop, or is this on DigitalOcean?  @eivantsov was planning to add some options into the Docker image version of Che that solves this. But I believe we were only encountering it on Digital Ocean. So if it's a broader issue, we may need to add this to the default execution (and have it turned off). And maybe it is appropriate so that it is there for all executions.

**Comment by siliconalchemy** [comment]
Ref:
https://wiki.apache.org/tomcat/HowTo/FasterStartUp

**Comment by siliconalchemy** [comment]
@TylerJewell - Hi, this is in a bog standard CentOS VM, in a regular server.

**Comment by TylerJewell** [comment]
Ok - adding this as an enhancement.  I imagine that having this off by default should be the way to go, and then a --blocking-entropy flag into the startup script.

@siliconalchemy Sorry you ran into this issue and had to overcome it.  We'll get this addressed to some reasonable approach.

**Comment by TylerJewell** [comment]
https://github.com/eclipse/che/pull/502/files

**Comment by ghost** [comment]
Yes, this issue is taken to a current sprint. Community and us noticed it when running Che on Digital Ocean.

**Comment by siliconalchemy** [comment]
Thanks :)
