### ISSUE TITLE
The Editor cannot open a file if its name ended with space

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4981]
**Reproduction Steps:**

- Start a workspace.
- Change any file name and add a space in the end of file name.

**Observed behavior:**
There is a error notification without a text and this file doesn't open in the Editor.

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25655715/8daa868e-2ffe-11e7-85f5-a442e9f73ff3.gif)

**Comment by ghost** [comment]
Yes, it looks like we should more carefully validate file names when created in the IDE
