### ISSUE TITLE
Terminal frame doesn't scale correctly when window is resized

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#4985]
Terminal frame doesn't scale correctly when window is resized. It can be found when browser window height is decreased or when browser developer tools frame is opened.

**Reproduction Steps:**
1. Start WS
![selection_054](https://cloud.githubusercontent.com/assets/1851863/25659046/86ba8a8a-300e-11e7-99cb-cf36ce0ceadf.png)
2. Increase size of terminal frame, but without usage of maximization button of terminal.
![selection_056](https://cloud.githubusercontent.com/assets/1851863/25659051/8ddcba86-300e-11e7-86e2-f7cae6fd6696.png)
3. Decrease height of window or open browser developer tools.
![selection_059](https://cloud.githubusercontent.com/assets/1851863/25659062/985bea7c-300e-11e7-88ef-e051c29dab95.png)
![selection_057](https://cloud.githubusercontent.com/assets/1851863/25659065/9d16d5ae-300e-11e7-8e42-fc30ddf46af1.png)

Expected:
Terminal frame control buttons are present as in case it was resized using maximize button of the frame.
![selection_058](https://cloud.githubusercontent.com/assets/1851863/25659093/cb78e734-300e-11e7-9df3-380e1121db61.png)

Actual:
Terminal frame control buttons are missing, top lines of content of terminal are missing.
![selection_059](https://cloud.githubusercontent.com/assets/1851863/25659115/e86fdeb0-300e-11e7-909c-eaf28b849e7e.png)

**OS and version:**    

**Diagnostics:**

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
