### ISSUE TITLE
There is not warning message when try to get to not existing workspace

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4986]
**Reproduction Steps:**
- Create any workspace.
- Change in url name of the workspace.

**Observed behavior:**
There is not warning message about this workspace is not exist.

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![ws_isn t_exist](https://cloud.githubusercontent.com/assets/7760565/25660387/a4d771c6-3014-11e7-8f4c-5090269dc2f6.gif)

**Comment by ghost** [comment]
Reproduced in 5.15-SNAPSHOT
