### ISSUE TITLE
There is no Stack description in Ready-to-Go section.

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#4987]
Missed stack description in ready-to-go stack section.

**Reproduction Steps:**
1 - Go to dashboard.
2 - Click 'Create Workspace'
3 - Look at Ready-to-Go Stacks section

Expected:
There are Stack name with a stack description

Actual:
There are Stack name with a stack tags. 
![codenvy dashboard](https://cloud.githubusercontent.com/assets/2101815/25660797/9039a700-3016-11e7-8312-6044208a582b.png)

It needs to replace tags with a stack description.

**Ubuntu 16.10:**    

**Diagnostics:**

**Comment by olexii4** [comment]
![selection_016](https://cloud.githubusercontent.com/assets/6310786/25740979/7caecea0-3191-11e7-975e-49d04ba3f2db.png)
