### ISSUE TITLE
There is a wrong message when creating a new workspace

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4988]
**Reproduction Steps:**

1. Workspaces -> "Add Workspaces".
2. In "Runtime" tab click on "Stack import" and then on "Ready-to-go Stacks".
3. Click on the "Workspace Config".

**Observed behavior:**
There is a message **"Runtime tab contains error(s): Recipe URL: URL is required."** under the "Workspace config".

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![runtimetaberror](https://cloud.githubusercontent.com/assets/7760565/25661127/ed44df2c-3017-11e7-8172-98907211a7d4.gif)

**Comment by ghost** [comment]
It looks like stack import is missing in the new UD. Closing the issue. Feel free to reopen though.
