### ISSUE TITLE
Eclipse CHE logo is hidden in the Google Chrome browser

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#4989]
**Reproduction Steps:**
1. Open Google Chrome browser.
2. Open Eclipse CHE.
3. Run workspace. Don't open any files.
Actual result: svg logo is exist in the editor partStack, but it's hidden. Seems main reason these are svg styles.
Expected result: svg log should be visible like in the Firefox.

**OS and version:**    
Fedora 25, but I think it's doesn't matter.
CHE version: 5.10.0-SNAPSHOT
Google Chrome version: 58.0.3029.81
![logohiddenonthechrome](https://cloud.githubusercontent.com/assets/6873095/25661404/2c7b6b74-3019-11e7-9f70-8f71e98b1029.png)
Firefox 53:
![fireforresult](https://cloud.githubusercontent.com/assets/6873095/25661474/7d42f8f6-3019-11e7-88e6-c3c76758d8a3.png)

**Comment by slemeur** [comment]
@vparfonov This should be a quick fix along with https://github.com/codenvy/codenvy/issues/2095
