### ISSUE TITLE
CHE-596 Make non-blocking entropy the default for Che startup

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#499]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-596
Reporter:  Tyler Jewell
Description: 1. Make non-blocking entropy the default.
2. Add --blocking-entropy flag on che.sh command line to activate blocking entropy.
3. Update usage docs with an explanation of entropy.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/pull/502
               https://github.com/eclipse/che/pull/551
