### ISSUE TITLE
Investigate integration of clangd language server

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4991]
To provide a better support for C/C++ project, we should study the integration of the clangd language server.

https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-Clangd-Server

**Comment by maximilianodendahl** [comment]
great to see that progressing! 

I guess latest code is here: https://github.com/llvm-mirror/clang-tools-extra/tree/master/clangd

**Comment by tolusha** [comment]
@evidolob 
WDYT?

**Comment by evidolob** [comment]
Yes, we should look at this, but clangd is very limited for now, it's has on formatting stuff

**Comment by maximilianodendahl** [comment]
I dont think this is true. I believe it already supports

* code completion: https://github.com/llvm-mirror/clang-tools-extra/commit/ca5f112a2e2f05d9a5cc8662ac740ff5a931d13c
* FixIts: https://github.com/llvm-mirror/clang-tools-extra/commit/6fbfc8451e5c1ce11298e2ec5b0f80cf02f78913

which is quite powerful already

**Comment by evidolob** [comment]
Yes, my bad. I check only initial commit :(

**Comment by AndrienkoAleksandr** [comment]
Result of investigation https://docs.google.com/document/d/1Hr1kYhJsPQoaNJXWkGfrtLG0RzvRXmkEUqD2V-fakM0/edit

**Comment by TylerJewell** [comment]
This is great and thorough.  @bmicklea - perhaps send this link to our friends over at Silexica. They'll have comments for the analysis of @AndrienkoAleksandr

**Comment by bmicklea** [comment]
Agreed, nice write up @AndrienkoAleksandr!  I've sent it to the Silexica team on Slack.

**Comment by gazarenkov** [comment]
@vkuznyetsov so, investigation is done, the issue supposed to be closed?

**Comment by hassec** [comment]
Hi, 
didn't want to open a new issue. 
Are there any plans to revisit this sometime soon?

Even an experimental C++ language server would be much better than none.

**Comment by maximilianodendahl** [comment]
@hassec Silexica will start looking into this next month as part of our slx.cloud offering, hoping to have a first version ready quite soon. I'll keep you updated

@hkolvenbach FYI

**Comment by hassec** [comment]
Hi @maximilianodendahl, 

just wondering if there has been any progess on this? :)

**Comment by hkolvenbach** [comment]
@hassec we have ported the work from https://github.com/eclipse/che-dependencies/tree/CHE-4991 to work with CHE 5.21 (forked here https://github.com/hkolvenbach/che/tree/kolvenbach.clangd_v3) and are able to successfully initialize the clangd binary (using the latest svn version of llvm). However, clangd currently does not give us any autocomplete information or error warnings, so you won't notice any improvement in the IDE. We are still debugging that and to figure out if the error is on the Eclipse Che or clangd side.

**Comment by hassec** [comment]
@hkolvenbach, thanks for the quick reply and your work :+1:

**Comment by 0Grit** [comment]
Commenting here so as not to distract too much from #7516 

Supposedly [cquery](https://github.com/jacobdufault/cquery) currently has more complete support for language server than clangd.

Has anyone investigated integrating cquery into Che versus clangd?

**Comment by tolusha** [comment]
@loverdeg-ep 
Hello.
Unfortunately I haven't chance to do checks.

**Comment by hkolvenbach** [comment]
@loverdeg-ep thanks for the suggestion, i will see how cquery compares to clangd.

EDIT: we should check how that affects Eclipse Che with real world projects https://github.com/jacobdufault/cquery#limitations
