### ISSUE TITLE
A web page is not redirected correctly, if after "http:" a link has only one slash

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#4992]
**Reproduction Steps:**

1. Start a workspace and in a project create a html file.
2. Create a link in this file with only one slash after 'http'.
3. Click on this link.

**Observed behavior:**
The IDE frame opens itself

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![orion](https://cloud.githubusercontent.com/assets/7760565/25664570/aecf8efc-3023-11e7-890c-14541adb9221.gif)

**Comment by ghost** [comment]
Reproduced in 5.15-SNAPSHOT

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa  @vparfonov @eivantsov is this up to date issue or we just forgot to close it?

**Comment by eivantsov** [comment]
Let's close it
