### ISSUE TITLE
Modify stacks.json

### ISSUE THREAD

**Issue by bobowang2017** [eclipse-che/che#4995]
In my project, I want to delete the java-mysql images in the stacks.json. But I found it has never change when I start the eclipse-che, how to make the change by modify stacks.json?

**Comment by davidwindell** [comment]
@bobowang2017 there is no way to do this at the moment except from modifying the stacks.json before first run (or deleting the users database and then restarting).

**Comment by bobowang2017** [comment]
@davidwindell You mean there is no way to reduce the images show in dashboard?

**Comment by ghost** [comment]
@bobowang2017 yes, you either need to flush database, then edit stacks.json and start Che.

**Comment by bobowang2017** [comment]
@eivantsov Thank you, I have got it
