### ISSUE TITLE
Che Factory api 

### ISSUE THREAD

**Issue by MuraliVidhya** [eclipse-che/che#4996]
Am trying to retrieve factory info (list of factories - json which contains detailed info on all available factories) using che factory api. The GET api /factory/find is based on name as an attribute and using this i could see one factory object - http://machinename:8080/api/factory/find?name=sampleF1

How do i use get API to list all the factories - irrespective of name/creator name  ?

Eclipse Che version 5.8.0
Docker version 1.13.0

**Comment by ghost** [comment]
@mvidhya86  `/find?creator.userId=che` should do the trick for you
