### ISSUE TITLE
Workspace undefined successfully created

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#500]
When creating a new workspace, a growl type message is shown in the ui saying 'Workspace undefined successfully created'.  I assume this should say 'Workspace -name- successfully created'.

**Comment by siliconalchemy** [comment]
Is this an appropriate use of issues in your github?  Do you want me to keep raising issues for bugs I find?

**Comment by ghost** [comment]
Yes, this is the right way to report issues.

So, you have given your ws a name, but the UI message says otherwise?

**Comment by siliconalchemy** [comment]
Yes exactly, it says 'undefined' where I would expect it to say the name of the workspace just created.

**Comment by ddementieva** [comment]
What Che version do you use?

**Comment by siliconalchemy** [comment]
Nightly 25.02.2016

**Comment by ddementieva** [comment]
Issue confirmed. The team is working on a fix.

**Comment by ghost** [comment]
Fixed in master - 4.1.0-RC1-SNAPSHOT
