### ISSUE TITLE
A last page button in the Factories list doesn't work

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5000]
**Reproduction Steps:**
Create at least 16 factories
In the Factories list click on a last page button

**Observed behavior:**
The button is not clickable

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![selection_035](https://cloud.githubusercontent.com/assets/7760565/25696593/6e36c7d2-30c0-11e7-9ba0-39793d7266b4.png)

![anim](https://cloud.githubusercontent.com/assets/7760565/25696548/4050a1ee-30c0-11e7-8188-c6d2ea6bf4bf.gif)

**Comment by olexii4** [comment]
We have wrong response header in a case with factories:
![selection_019](https://cloud.githubusercontent.com/assets/6310786/25699296/51e89410-30cb-11e7-991a-bdeca0d9c88e.png)
For example, we have another request with needed information:
![selection_018](https://cloud.githubusercontent.com/assets/6310786/25699311/61a1e8d4-30cb-11e7-9442-de7f7e9c439f.png)

**Comment by olexii4** [comment]
We have the same problem with stack request:
![selection_020](https://cloud.githubusercontent.com/assets/6310786/25699490/25030646-30cc-11e7-96ee-0159da429841.png)

**Comment by SkorikSergey** [comment]
Not actual.
