### ISSUE TITLE
String Written to Dev-Machine stdout not Escaped Properly

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#5001]
For debugging purposes, I have written the following string to stdout of the ws-agent:

```
<span>
<?php
        echo "Hallo, ich bin ein PHP-Skript!";
?>
</span> 
```

The text shows up in the console like this:
```
[STDOUT] 
[STDOUT]         echo "Hallo, ich bin ein PHP-Skript!";
[STDOUT] ?>
```

I suspect there is unsufficient quoting for html text at work here. My expectation would be that the html tags show up in the output.

**Comment by vrubezhny** [comment]
This issue is fixed by PR #5396
