### ISSUE TITLE
The "Create File" link is active when a readonly file is selected

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5004]
**Reproduction Steps:**
- Click on a read-only file (from external libraries, for example) in the **Project Explorer**.
- Try to create a new file

**Expected behavior:**
There is not possibility to create a new file(all items for creating a new file disabled).

**Observed behavior:**
There is possibility to  start **New File** dialog by clicking the **Create File...** link.

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25703371/febef686-30dd-11e7-9e84-436ee7fd10c5.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
