### ISSUE TITLE
Workspace project storage created with insecure permissions

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#501]
Where -che- is the root of the app, -che-/workspaces/-workspace- and -che-/workspaces/-workspace-/-project- are both created with 777 permissions.  It is also owned by 33:33 which isn't correct, but the permissions is much more serious issue.

**Comment by siliconalchemy** [comment]
[root@dev /srv/che]# ls -lR workspaces/
workspaces/:
total 0
drwxrwxrwx. 3 33 33 27 Feb 24 20:09 testphp

workspaces/testphp:
total 0
drwxrwxrwx. 4 33 33 64 Feb 24 20:09 web-php-simple

workspaces/testphp/web-php-simple:
total 8
-rwxrwxrwx. 1 33 33  30 Feb 24 20:28 index.php
-rwxrwxrwx. 1 33 33 548 Feb 24 20:28 README.md

**Comment by ghost** [comment]
For php environment we run `chown` in CMD instruction of a Dockerfile to let apache write to that folder. Will look for a more elegant solution.

**Comment by ghost** [comment]
Removed chown and chmod from CMD
