### ISSUE TITLE
Improve python language server

### ISSUE THREAD

**Issue by philipp-lein** [eclipse-che/che#5011]
Hey guys,
is there any reason why Che doesnt use the plantir language server for python ? (https://github.com/palantir/python-language-server)
Is there a problem I doesn´t see ?
When not I would try to integrate it. 

Best regards :)

**Comment by TylerJewell** [comment]
We do a good job with pull requests. Will you consider packaging it as an agent (see docs) and submitting appropriate PR for inclusion?

**Comment by philipp-lein** [comment]
Thanks for the answer.
I try my best !

**Comment by bmicklea** [comment]
@phill1234 I'm closing this as I think the question is answered, let me know if you need it reopened.
