### ISSUE TITLE
Incorrect behavior at refactoring

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#5013]
External operation event is displayed at refactoring

**Reproduction Steps:**
1. Create "spring" project
2. Create java classes "A" and "B" for example
3. Create a new field of "B" type in the "A" class
4. Select  "B" type of the created field and rename this one by Assistant -> Refactoring -> Rename action
You can see "B" type is renamed but external operation event is displayed 
![rename_bug](https://cloud.githubusercontent.com/assets/5676062/25745096/0064950e-31a6-11e7-9c22-e41edb176975.gif)

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS

**Comment by svor** [comment]
Can't reproduce it.

**Comment by RomanNikitenko** [comment]
I think it's fixed by https://github.com/eclipse/che/pull/5041
