### ISSUE TITLE
PHPDoc for ls-php

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5017]
Can anyone see PHP.net phpdoc showing for any built in functions?

I'm only seeing the list of core functions (so lsp must be working) but nothing to the right.

*che-server v5.9.1*

**Comment by ghost** [comment]
@davidwindell I can see much more functionality declared for https://github.com/felixfbecker/php-language-server as compared to what's available in Eclipse Che. Labeling it as a task.

**Comment by davidwindell** [comment]
Any progress on assigning a milestone to this @eivantsov? Is it a big task?

**Comment by gorkem** [comment]
@davidwindell have you checked this with Che 7?

**Comment by davidwindell** [comment]
Fixed in Che 7
