### ISSUE TITLE
an error when I complied the code 

### ISSUE THREAD

**Issue by yuqitao** [eclipse-che/che#5018]
[exec] > node install.js
     [exec] 
     [exec] PhantomJS not found on PATH
     [exec] Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
     [exec] Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
     [exec] Receiving...
     [exec] 
     [exec] Error making request.
     [exec] Error: connect ECONNREFUSED 52.216.226.88:443
     [exec]     at Object.exports._errnoException (util.js:870:11)
     [exec]     at exports._exceptionWithHostPort (util.js:893:20)
     [exec]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
     [exec] 
     [exec] Please report this full log at https://github.com/Medium/phantomjs
     [exec] npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
     [exec] npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

**Comment by TylerJewell** [comment]
This is not a reproducible set of steps.  Provide a clear reproducible set of steps and then the issue can be reconsidered to be opened. This is open source - you have to provide explanations to get help.
