### ISSUE TITLE
MongoDB in Meteor application failing to write

### ISSUE THREAD

**Issue by brian-k** [eclipse-che/che#5019]
In a new Meteor application, MongoDB fails to start and provides the below error:

> user@6eda3fe79bde:/projects$ cd prod-sched-tool/
> user@6eda3fe79bde:/projects/prod-sched-tool$ meteor
> [[[[[ /projects/prod-sched-tool ]]]]]
> 
> => Started proxy.
> Unexpected mongo exit code 100. Restarting.
> Unexpected mongo exit code 100. Restarting.
> Unexpected mongo exit code 100. Restarting.
> Can't start Mongo server.
> MongoDB had an unspecified uncaught exception.
> This can be caused by MongoDB being unable to write to a local database.
> Check that you have permissions to write to .meteor/local. MongoDB does
> not support filesystems like NFS that do not allow file locking.
> user@6eda3fe79bde:/projects/prod-sched-tool$

**Reproduction Steps:**
1. Build a workspace based off of eclipse/meteor:ubuntu
1. Import an empty Meteor application (https://github.com/brian-k/prod-sched-tool) as a project in the new workspace
1. Change to the project directory (prod-sched-tool) and run `meteor`

**OS and version:**    
Microsoft Windows [Version 10.0.10586]

**Diagnostics:** 
C:\WINDOWS\system32>docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v %userprofile%/.che:/data eclipse/che info
WARN: Bound 'eclipse/che' to 'eclipse/che:5.9.1'
INFO: (che cli): 5.9.1 - using docker 17.03.1-ce / docker4windows

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che
 Version:        5.9.1
 Command:        info
 Parameters:     info
Mounts:
 /data:          /C/Users/brian-k/.che
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         docker4windows
 Proxy:          not set
Internal:
 CHE_VERSION:    5.9.1
 CHE_HOST:       10.0.75.2
 CHE_INSTANCE:   /C/Users/brian-k/.che/instance
 CHE_CONFIG:     /C/Users/brian-k/.che
 CHE_BACKUP:     /C/Users/brian-k/.che/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   10.0.75.2
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.9.1
 IMAGE_CHE=eclipse/che-server:5.9.1
 IMAGE_COMPOSE=docker/compose:1.8.1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.9.1
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.9.1
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.9.1
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.9.1
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.9.1
che.env:
 CHE_HOST=10.0.75.2

**Comment by TylerJewell** [comment]
Thanks for reporting this - will ask @eivantsov take a look.

**Comment by ghost** [comment]
@brian-k I am pretty sure this is a Windows issue. I do not have it on linux. Mongo can be picky about file permissions. Since Win file system is mounted into the VM, this can cause troubles.

Here's how you can verify it:

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /somevolume:/data eclipse/che start`

I suggest `-v /somevolume:/data` on purpose since this way we make sure that Win file system isn't involved when workspace containers start.

**Comment by ghost** [comment]
@brian-k may I have an update on this one? Have you tried syntax with a non existing win path?

**Comment by brian-k** [comment]
That worked. Thanks.

**Comment by ghost** [comment]
@brian-k I don't think I can offer any other solution at this moment.  You will have the same problem without Che, i.e. starting a meteor container manually.
