### ISSUE TITLE
Che tries to connect to internet to retrieve the stack's image in offline mode.

### ISSUE THREAD

**Issue by banafshebamdad** [eclipse-che/che#5021]
I've installed Che in offline mode by the following instruction. But when I want to create a new workspace, it tries to connect to internet to retrieve the stack's image and launching it.

1. While connected to the Internet, I've downloaded Che’s Docker images.
	docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:5.8.0 offline
 This command downloaded the following files:
			alpine:3.4.tar  
			docker_compose:1.8.1.tar  
			eclipse_che:5.8.0.tar  
			eclipse_che-action:5.8.0.tar  
			eclipse_che-init:5.8.0.tar  
			eclipse_che-server:5.8.0.tar
2. Then I copied these files to an Internetless server and started Che in offline mode by the following commands:
	docker load < /tmp/offline/eclipse_che:5.8.0.tar
	docker run -it --rm -e -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/offline:/data/backup eclipse/che:5.8.0 start --offline
	
I have run all commands with root user.

Any advice would be greatly appreciated

**OS and version:**    
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by bmicklea** [comment]
@banafshebamdad you'll have to also download the stacks that you are interested in. You can find them listed under the Eclipse organization on DockerHub: https://hub.docker.com/u/eclipse/

If you want to have Che pull images from your local image registry then you'll have to add the private registry to the configuration: https://eclipse.org/che/docs/setup/configuration/index.html#private-images

**Comment by mersadkhan** [comment]
Dear @bmicklea 
we download the eclipse/ubuntu_python and also other stacks and load them by 
`docker load </tmp/offline/eclipse_ubuntu_python.tar`
`docker load </tmp/offline/eclipse_ubuntu_go.tar`
and so on. but when we make a workspace for python as an example docker try to connect to internet and download the stack. how can we independent it from internet completely and also make it to load the stack which we have download and load it?

**Comment by bmicklea** [comment]
@eivantsov can you help here?

**Comment by benoitf** [comment]
It is related to https://github.com/eclipse/che/issues/4197

**Comment by ghost** [comment]
Yes, currently, it is only possible to build images offline, however, when using an image directly, Che first checks the registry and compares to a local image.

**Comment by ghost** [comment]
Closing this one. Please follow https://github.com/eclipse/che/issues/4197
