### ISSUE TITLE
there is no stacks

### ISSUE THREAD

**Issue by linpengfei** [eclipse-che/che#5023]
**Reproduction Steps:**

**OS and version:**    
che 5.8.0
ubuntu 14.04
**Diagnostics:** 

when i add a new agent for che and run che the stacks is empty,can you help me?

**Comment by skabashnyuk** [comment]
How we can reproduce this issue?

**Comment by ghost** [comment]
@linpengfei please provide detailed steps to reproduce, especially for:

> when i add a new agent for che
