### ISSUE TITLE
Machine is Destroyed

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5024]
We are seeing this consistently across multiple Che installs after launching a workspace. It usually happens within the first half an hour or so. I can't see any other errors than "Machine is destroyed". Any thoughts?

```
[STDOUT] 2017-05-09 10:27:48,119[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /root/che/ws-agent/webapps/ROOT.war has finished in 8,771 ms
[STDOUT] 2017-05-09 10:27:48,141[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-4401]
[STDOUT] 2017-05-09 10:27:48,191[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 9043 ms
[STDOUT] 2017/05/09 10:27:55 A new channel with id 'channel-1' successfully opened
[STDOUT] 2017-05-09 10:27:55,858[nio-4401-exec-7]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 49]   - Web socket session opened
[STDOUT] 2017-05-09 10:27:55,860[nio-4401-exec-7]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 50]   - Endpoint: 475087258
[STDOUT] 2017/05/09 10:27:55 A new channel with id 'channel-2' successfully opened
[STDOUT] 2017-05-09 10:27:55,889[nio-4401-exec-3]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 49]   - Web socket session opened
[STDOUT] 2017-05-09 10:27:55,891[nio-4401-exec-3]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 50]   - Endpoint: 565413378
[STDOUT] 2017/05/09 10:27:55 Start new terminal.
[STDOUT] 2017/05/09 10:27:55 Start new terminal.
Machine is destroyed
```

Running `eclipse/che-server:5.9.1`.

**Comment by TylerJewell** [comment]
Machine destruction is almost always due to memory limitations. What is the performance profile of the processes that are running within the system at the time of the crash?

**Comment by davidwindell** [comment]
:+1: I'll monitor this with `docker stats` and report back.

**Comment by davidwindell** [comment]
Ok, so after testing it doesn't hit any memory limits (we have 8GB set and ~2GB is used). CPU is not limited by any config option but `docker stats` reports CPU at ~150% for a few minutes while scanning PHP files is happening. Here's the logs from the server:

```
2017-05-09 15:40:10,300[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 796]    - Workspace 'che/xyz' with id 'workspacen7xyssjdg84gcc0z' is being stopped by user 'undefined'
2017-05-09 15:40:10,301[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 861]   - Creating snapshot of workspace 'workspacen7xyssjdg84gcc0z', machines to snapshot: '0'
2017-05-09 15:40:10,301[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 884]   - Saving new snapshots metadata, workspace id 'workspacen7xyssjdg84gcc0z'
2017-05-09 15:40:10,479[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 827]    - Workspace 'che/xyz' with id 'workspacen7xyssjdg84gcc0z' stopped by user 'undefined'
2017-05-09 15:40:14,959[ted-scheduler-2]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
2017-05-09 15:40:32,668[p-nio-80-exec-8]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 78]   - Web socket session error
2017-05-09 15:40:32,668[p-nio-80-exec-8]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 69]   - Web socket session closed
```

So...something is destroying it but I'm not sure what?

**UPDATE** When this happens, ALL running workspaces on the host seem to get stopped at the same time (multiple che-servers via docker)

**Comment by TylerJewell** [comment]
I note that this is also a user that is undefined. Possible that someone is connecting over API and stopping the workspaces?

**Comment by davidwindell** [comment]
Not a possibility in this case as access to the API is only from one IP address.

**Comment by TylerJewell** [comment]
Last question as I think @eivantsov will be fascinated by this use case - is there anything running on the host that could be predatory against the docker daemon itself?  @skryzhny

**Comment by ghost** [comment]
@davidwindell @TylerJewell 

> When this happens, I think that all running workspaces on the host seem to get stopped at the same time (multiple che-servers via docker)

This makes me think that ResourcesCleaner kills those containers. However, the weird part is that logs say it does not.

Does it happen when you run just one che-server?

**Comment by davidwindell** [comment]
I'm just testing this now, it looks so far like it might be when we are running more than one server only. Will confirm.

**Comment by davidwindell** [comment]
@eivantsov @TylerJewell Ok so, I can easily reproduce this now, I left a workspace running on one che-server and that stayed up overnight. As soon as I start a second che-server, the workspace that was running fine overnight is immediately terminated with:

```
[che-david-1]2017-05-11T16:01:11.374810678Z 2017-05-11 16:01:11,374[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 796]    - Workspace 'che/zebreco' with id 'workspacem5k8814ir0q4dgbp' is being stopped by user 'undefined'
[che-david-1]2017-05-11T16:01:11.379841290Z 2017-05-11 16:01:11,379[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 861]   - Creating snapshot of workspace 'workspacem5k8814ir0q4dgbp', machines to snapshot: '0'
[che-david-1]2017-05-11T16:01:11.380134400Z 2017-05-11 16:01:11,379[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 884]   - Saving new snapshots metadata, workspace id 'workspacem5k8814ir0q4dgbp'
[che-david-1]2017-05-11T16:01:11.384660153Z 2017-05-11 16:01:11,384[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 827]    - Workspace 'che/zebreco' with id 'workspacem5k8814ir0q4dgbp' stopped by user 'undefined'
```

What is `ResourcesCleaner` and how can I disable it? Thanks!

**Comment by ghost** [comment]
@davidwindell there's no way to disable abandoned resource cleaner which makes sure that Che workspace containers not registered with a given Che server are destroyed.

This PR has been issued to fix this problem - https://github.com/eclipse/che/pull/4565

However, looks like we need to refresh it. @TylerJewell should it be taken by someone from enterprise team?

**Comment by davidwindell** [comment]
Ah, fantastic news, this is making it unusable for us at the moment. I'll see if I can patch our local copy with the PR so we can at least use it for now.

Thanks again!

**Comment by ghost** [comment]
@davidwindell I will close this one as a duplicate of https://github.com/eclipse/che/issues/4452 which you are welcome to follow.
