### ISSUE TITLE
Workspaces can't be created <1gb

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#503]
Minimum size for a workspace (being created through the ui) is 1gb.  It is sometimes useful to create smaller containers than this, having this constraint limits container density and wastes resources.

**Comment by TylerJewell** [comment]
Inside of the workspace, Che is running its own agents that are launching in a Tomcat.  In some cases, this agent requires only 256MB but depending upon the PT and the agents that are activated (such as Java Intellisense) those services can consume up to 1GB.  For now we keep it at this minimum until we hvae some intelligence to understand based upon the PT what the minimum could be.

**Comment by siliconalchemy** [comment]
OK, thanks :)
