### ISSUE TITLE
Broken links to stack documentation

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#5030]
The link in:
'New workspace' -> 'Runtime' -> 'stack authoring' -> 'Custom stack documentation'

is pointing to:  
https://www.eclipse.org/che/docs/workspace/stacks/index.html#stack-administration

instead of:
https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html

**Comment by ashumilova** [comment]
depends on https://github.com/codenvy/codenvy/issues/2035
