### ISSUE TITLE
swagger.json shows old API for factory

### ISSUE THREAD

**Issue by bs-matil** [eclipse-che/che#5031]
Hello,
I'm currently try to generate a client for swagger so I can use the che api. While working on that I regonized a lot of things I don't fully understood. 

First thing is that the factory api has an [impl](https://github.com/eclipse/che/blob/5.9.1/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java) which has two methods one with `application/json` and one with `multipart `input which is depricated. The swagger json only contains the deprecated method. Is that intentional? 

Next I would like to know why some things appear in the wsmaster like an auth api for login and logout but they are not displayed in the api even an [impl](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/api/auth/AuthenticationService.java) exists? How are they excluded? Can I activate them somehow to play with simple authentication?

**Comment by ghost** [comment]
@bsukramlitt good questions!

1. Yes, swagger still shows a deprecated method. We will fix that.
2. Che is a single user. You may take a look at https://github.com/codenvy/codenvy to see how authentication is implemented there.

**Comment by TylerJewell** [comment]
Actually Codenvy is proprietary software. It does have an authentication implementation of Che, but it is not open source. We provide source code for people to understand our internals but it cannot be copied.

[Tyler Jewell - Contact Using Hop](http://GetHop.com/?_hmid=1494592805)

On May 12, 2017 at 12:23 GMT, Eugene Ivantsov <notifications@github.com> wrote:

[@bsukramlitt](https://github.com/bsukramlitt) good questions!

- Yes, swagger still shows a deprecated method. We will fix that.
- Che is a single user. You may take a look at https://github.com/codenvy/codenvy to see how authentication is implemented there.

**Comment by bs-matil** [comment]
Hi guys. I have no issue with that practice in general but there are to me only two options.
The source is in the codenvy repo then its closed source in some way which i respect. Or its in che and can be used open source. But why is there an impel for authentication open source but not build into the open source assembly. I don't get why is that. Could you say something about that?

If you have a look at https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/api/auth/AuthenticationService.java you'll see a probably functional implementation for authentication within che. So why is it there? and Why can't I use it then? Was this copied to che without intention?

**Comment by ghost** [comment]
@bsukramlitt are you asking why Che does not have a real auth implementation? If so, @TylerJewell as a project lead can elaborate.

**Comment by TylerJewell** [comment]
We have all of the apis in che for compatibility. But some of the implementations have empty implementations. This approach is how we keep consistency between Che and other proprietary assemblies and make it possible for plugins to move seamlessly between Che and Codenvy.

[Tyler Jewell - Contact Using Hop](http://GetHop.com/?_hmid=1494593471)

On May 12, 2017 at 12:47 GMT, Markus Till <notifications@github.com> wrote:

Hi guys. I have no issue with that practice in general but. There are to me only to options.
The source is in the codenvy repo then its closed source in some way which i respect. Or its in che and can be used open source. But why is there an impel for authentication open source but not build into the open source assembly. I don't get why is that. Could you say something about that?

If you have a look at https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/api/auth/AuthenticationService.java you'll see a probably functional implementation for authentication within che. So why is it there? and Why can't I use it then? Was this copied to che without intention?

**Comment by bs-matil** [comment]
Okay Thanks for the explanation. So we are using both and therefore i wanted to know how this fits. 

Thanks a lot!
