### ISSUE TITLE
Git clone via IDE import missing execute bits

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5037]
When we import a project using the IDE "Import Project" feature, execute bits seem to be lost from the upstream repository. For example, this is the the result of an import...

`-rw-r--r-- 1 root root 827 May 10 12:30 run.sh`

...and this is what we get from a manual `git clone` in the terminal (and what we expect)...

`-rwxr-xr-x 1 root root 827 May 10 12:43 run.sh`

**Comment by ghost** [comment]
Must be JGit that does that. We will investigate.

**Comment by ghost** [comment]
My findings:

IDE import

`-rwxr-xr-x 1 user user  387 May 24 06:16 build.sh
`

Git clone in the terminal

`-rwxr-xr-x 1 user user  387 May 24 06:17 build.sh`

Permissions are the same

**Comment by davidwindell** [comment]
@eivantsov try cloning https://github.com/outeredge/edge-docker-php, that gives me

```
# ls -la build.sh
-rw-r--r-- 1 root root 2505 May 24 09:08 build.sh
```

**Comment by ghost** [comment]
@davidwindell they are exactly the same on my side:

```
-rwxr-xr-x 1 user user     2505 May 24 09:32 build.sh
and
-rwxr-xr-x 1 user user     2505 May 24 09:33 build.sh
```

Maybe it has smth to do with the fact that you have root user.

**Comment by davidwindell** [comment]
Right you are, works fine as `user`. Eek, I am going to have to find a way to run docker in docker as `user` then. My last attempt failed trying to create a docker group and add user to it in the Dockerfile.
