### ISSUE TITLE
A workspaces name isn't appear in the "Recent Workspaces list" after starting

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5039]
**Reproduction Steps:**
1. Create at least 6 workspaces.
2. In **the Workspaces** list find a workspace that isn't exists in **the Recent Workspaces** list.
3. Click on the **Run workspace** button.

**Expected behavior:**
The workspace started and its name appears in **the Recent Workspaces list**.

**Observed behavior:**
The workspace started but its name isn't appear in **the Recent Workspaces list**.

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![ws_behind_rc_list](https://cloud.githubusercontent.com/assets/7760565/25900283/9dc8ff80-359b-11e7-8911-50a9552b3137.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT
