### ISSUE TITLE
Workspace state Error removes Run button

### ISSUE THREAD

**Issue by siliconalchemy** [eclipse-che/che#504]
When starting a workspace and an error occurs, the Run button is removed so you cannot correct the error and start again (and you don't see what the error is from the ui, either).  The page has to be refreshed to see the Run button again.

**Comment by ddementieva** [comment]
It's a known bug. We plan a number of improvements around Run button.

**Comment by siliconalchemy** [comment]
I hear 'it's a known bug' for a lot of issues I'm raising.  I do look for existing issues first, am I missing them or are you not using github to track issues?

**Comment by ddementieva** [comment]
Some of them are not on GitHub yet.

**Comment by TylerJewell** [comment]
We are working on a system to export our jira into github.  We h e about 1000 issues to synchronize.   This proves to be quite the challenge.

**Comment by ddementieva** [comment]
Fixed in master by https://github.com/eclipse/che/commit/6fbb2494a5de93161b013ee8bdabeb4f74c8094f. Fix version 4.2.0.
