### ISSUE TITLE
There is log error message  when working with big files

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5040]
**Reproduction Steps:**
1. Create a workspace.
2. Open a file in the **Editor** with size at least 200 Kb.

**Observed behavior:**
There is "File is too big and might not be retrieved as bytes" error  from **eWatcherService**.

**Che version:** 5.10.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/25901292/fd0f3ff6-359e-11e7-9ed5-cc5ac1879298.gif)

**Comment by riuvshin** [comment]
216kb is not too big... and even if we think it is big we should improve UX here.

**Comment by RomanNikitenko** [comment]
We have some [restrictions](https://github.com/eclipse/che/blob/6a95b6d74a7a592b082180f5e343e29de2519532/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/impl/file/LocalVirtualFileSystem.java#L81)
At this case the exception is thrown [here](https://github.com/eclipse/che/blob/7faecbadc9950856a28885793ea748a0bcaaa3b7/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/impl/file/LocalVirtualFile.java#L113)
AFAIK we won't have this restriction after merge [PR](https://github.com/eclipse/che/pull/6726)
I've tested it:
![big_file](https://user-images.githubusercontent.com/5676062/32232200-2b7cd99e-be60-11e7-9098-0fa182b80e0f.gif)

**Comment by RomanNikitenko** [comment]
Fixed by https://github.com/eclipse/che/pull/7380
