### ISSUE TITLE
Creation project from archetype - maven-plugin API

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#5046]
I tried POST request /<wsagent>/project/batch. It is working with maven type (defined in maven plugin) and it provides ability to use archetype. 
```
 {
  "name": "ABC",
  "path": "/ABC",
  "attributes": {
      "maven.groupId": ["com.xxx.yyy"]
      "maven.artifactId": ["ABC"],
      "maven.version": ["1.0.0-SNAPSHOT"],
  },
  "type": "maven",
  "options": {
     "type": "archetype",
     "archetypeGroupId": "com.xxx.yyy.archetype",
     "archetypeArtifactId": "com.xxx.yyy-service-archive",
     "archetypeVersion": "1.0.0",
     "archetypeRepository": null
  }
}
```
This API is official? It can be changed in future? From which version it supported?

**Comment by ghost** [comment]
@gorshkov-leonid yes, this is project API that usually does not change too much and too often. I don't have info on when creating projects from archetypes has been introduced, but they have been around for quite a while.

**Comment by gorshkov-leonid** [comment]
Thank u

**Comment by ghost** [comment]
You're welcome. I am closing the issue then. Feel free to reopen if you have further questions though.
