### ISSUE TITLE
How to migrate existing Eclipse RCP application to Eclipse Che? 

### ISSUE THREAD

**Issue by Swanand777** [eclipse-che/che#5053]
Hi,
How to migrate existing Eclipse RCP application to Che? How stack should be configured. what are basic steps needed? 
For e.g. I have developed one RCP application. Now I want to migrate it to Eclipse Che. How to migrate? I want to see the output for application like view, perspective, application window, menus. If it's launched from Eclipse Che. Does eclipse Che support's such migration? If yes, how to do that?. As in desktop IDE we set target platform, it consists of set of plugins which are required to launch the application. Eclipse che provide's such functionality, if we migrate rcp plugins to Eclipse Che?
Let me know if more data is required.
Thanks,
Swanand

**Comment by ghost** [comment]
@Swanand777 you may want to take a look at the following tutorial: https://www.eclipse.org/che/docs/tutorials/swing/index.html

Even though it's for Java Swing apps it shows what environment to use for GUI apps.

And most likely, you will have to mavenize your project - https://www.eclipse.org/che/docs/tutorials/maven/index.html or configure it as plain java and add libraries to classpath on your own.

Currently, there is no step by step tutorial for Eclipse rcp apps

**Comment by Swanand777** [comment]
@**eivantsov** . Thanks for your reply. Currently we have a eclipse rcp based product. As Eclipse Che provides cool features, we want to demonstrate this to DevOps team.  "How eclipse Che will increase productivity for developer!", "How Eclipse Che makes your Devops operations in organization easy!" . But we have to do it on our product itself. So Do you know any commiters or developers who knows the process for such migration of eclipse rcp apps? 
Thanks,
Swanand

**Comment by ghost** [comment]
Is your project public so that you can share it here? I am not aware of any community efforts to migrate Eclipse rcp apps to Che. But if you start sharing info and steps you have taken to import, compile and run your project in Che, you will definitely get help.

**Comment by Swanand777** [comment]
@eivantsov . No its not public. Its our product  :) . I am interested having this migration task on plate. Would like to contribute to Eclipse che regarding existing rcp apps. Thanks for your time and help :)

**Comment by ghost** [comment]
I am closing the issue. Feel free to reopen if you have questions about your specific use case

**Comment by SatishChGit** [comment]
> Hi,
> How to migrate existing Eclipse RCP application to Che? How stack should be configured. what are basic steps needed?
> For e.g. I have developed one RCP application. Now I want to migrate it to Eclipse Che. How to migrate? I want to see the output for application like view, perspective, application window, menus. If it's launched from Eclipse Che. Does eclipse Che support's such migration? If yes, how to do that?. As in desktop IDE we set target platform, it consists of set of plugins which are required to launch the application. Eclipse che provide's such functionality, if we migrate rcp plugins to Eclipse Che?
> Let me know if more data is required.
> Thanks,
> Swanand

did you able to convert RCP application to che framework?
