### ISSUE TITLE
Custom Che Assembly version to version migration

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#5054]
What's the best way to migrate custom Che assembly to the new version?

Imagine, I have custom assembly with version 5.2.0 and the following modules structure:
![image](https://cloud.githubusercontent.com/assets/11683340/25987916/92b8ba86-36fe-11e7-94a9-50a77da3d6bd.png)

I change some pom.xml files from root and assembly module to include custom plugins and agents. 
But now I want to migrate to the last Che version. Is some special approach or tool to do it or only manual file changing (ad hoc)?

**Comment by ghost** [comment]
@zatsepinvl you have more than one option

1. Keep everything as is and just change che-parent version to the latest tag.
2. Use Che archetypes to generate a new optimized assembly and then add your plugins - https://www.eclipse.org/che/docs/assemblies/archetype/index.html and https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html

**Comment by zatsepinvl** [comment]
@eivantsov the first option didn't work when relative module's names were changed.
I try it to migrate from 5.2.2 to 5.8.0, but I had to deal with problems caused changed modules names.

**Comment by ghost** [comment]
Then, I'd suggest you use archetype to generate a new assembly, and then manually add your plugins and/or modules.

**Comment by vnea** [comment]
I am also trying to migrate from 5.2.2 to 5.10.0 (see #5032).

@eivantsov 

> Then, I'd suggest you use archetype to generate a new assembly, and then manually add your plugins and/or modules.

I want to know if I understand correctly what you said.

Let's say I generate a new custom assembly with this command and that I choose the **plugin-embedjs-archetype** archetype :
```
docker run -it --rm
  -v /var/run/docker.sock:/var/run/docker.sock 
  -v <archetype_path>:/archetype 
  -v <data_path>:/data 
  -v <m2_path>:/m2 
    eclipse/che-cli 
      archetype generate
```

Then I will have this:
![image](https://cloud.githubusercontent.com/assets/10775422/26000215/610746cc-3728-11e7-9e00-f5eb1bedb00d.png)

If I follow what you said, now I can add all my developed plugins in the **plugins** folder and remove the **plugin-embedjs** plugin and then edit all pom.xml files generated to include my new plugins (and finaly build+run).

Is that the right way to create a custom assembly with personal plugins ?

**Comment by ghost** [comment]
@vnea yes, removing a sample plugin and adding your own is the way to go.

When a new Che tag is out, you simple update parent version in root pom.xml

**Comment by vnea** [comment]
@eivantsov thank you for your response, but I have a last thing that I don't really understand.
What is the difference between using the archetype tool and adding a new pluging following this [process](https://github.com/eclipse/che/tree/5.10.0/samples/sample-plugin-embedjs).

What I mean is that we can have the same result with these two processes (a custom assembly with plugins), so which one should I follow and what is the difference ?

**Comment by ghost** [comment]
Assembly generated from an archetype is cleaner and smaller and easier to manage. It re-uses most artifacts as dependencies.

**Comment by vnea** [comment]
@eivantsov Thank you I understand now.
