### ISSUE TITLE
Display somewhere currently selected stack

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#5055]
Display somewhere currently selected stack when creating a workspace.

![screenshot from 2017-05-12 12 01 29](https://cloud.githubusercontent.com/assets/1655894/25991142/f6adc3ae-370a-11e7-9d49-47d68af29754.png)

**Comment by slemeur** [comment]
It is displayed in the "runtime" tab.

**Comment by vitaliy-guliy** [comment]
Yes, sure. But I was confused when I created a workspace and it was based on .NET stack. So, .NET was the default stack. We had JAVA+MYSQL before.

**Comment by ashumilova** [comment]
Fixed by new creation flow
