### ISSUE TITLE
CHE-602 [dashboard] Allow to send to IDE some loading parameters

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#506]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-602
Reporter:  Florent Benoit
Description: UD need to exchange some data with IDE, it could be a generic way to send these parameters

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/d09773183c56c3674b5032df6fa290539c01e9ba
