### ISSUE TITLE
Maven project does not display a content with invalid POM file

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5067]
**Reproduction Steps:** show screencast below:
![anim](https://cloud.githubusercontent.com/assets/1640058/26024614/90453a9c-37dd-11e7-8370-9d64a7ecac9e.gif)

**OS and version:**    Ubuntu 14, chrome browser, CHE-5.11.0-SNAPSHOT, rev. 79e7c44e02f582ac

**Comment by vparfonov** [comment]
Can't reproduce i will close issue, feel free to reopen it if have more information

**Comment by vzhukovs** [comment]
Closed, because issue does not reproduce.
