### ISSUE TITLE
How to add action to the view toolbar , to close/refresh the view.

### ISSUE THREAD

**Issue by chakraborty-slx** [eclipse-che/che#5068]
I would like to add a view toolbar action, which closes the view or refresh the view. 

Any example would be helpful.

**Comment by ghost** [comment]
@vparfonov can someone from IDE team comment please?

**Comment by vparfonov** [comment]
@AChakraborty1982 here you can find example https://github.com/eclipse/che/blob/master/samples/sample-plugin-actions/che-sample-plugin-actions-ide/src/main/java/org/eclipse/che/plugin/sampleactions/ide/SampleActionsExtensions.java#L68-L68

**Comment by chakraborty-slx** [comment]
@vparfonov as I mentioned , the action need to be added for the View and not for the CHE IDE toolbar,
For example if i create a custom viewpart like https://www.eclipse.org/che/docs/assemblies/sdk-parts/index.html

How can I add a close action in the viewpart toolbar which contains only minimize and maximize buttons.

**Comment by vparfonov** [comment]
@AChakraborty1982 Here simple example with close button https://github.com/eclipse/che/blob/master/plugins/plugin-help/che-plugin-help-ext-client/src/main/java/org/eclipse/che/ide/ext/help/client/about/AboutViewImpl.java#L41-L41

**Comment by chakraborty-slx** [comment]
Thanks this helps
