### ISSUE TITLE
CHE-603 [dashboard] allow to add new routes on route history

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#507]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-603
Reporter:  Florent Benoit
Description: we may need to change the "goes back" link when we leave the IDE to go inside UD

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/660d58d51cb627c81ae33313c6564872a083032c
