### ISSUE TITLE
Provide missing java.output.folder attribute for java based projects

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#5071]
**Reproduction Steps:**
1. Create spring project from samples
2. Refresh page

**Expected behaviour:** the project is configured as maven project
**Observed behaviour:** the project is not configured
**Che version:** 5.11.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![maven_project_bug](https://cloud.githubusercontent.com/assets/5676062/26048122/8a7ee5ae-395e-11e7-9d8b-6b310247d89a.gif)

**Comment by Ohrimenko1988** [comment]
And we also have a problem in the git tests (CommitFilesTest, CheckoutBranchTest, AddFilesToIndexTest) who related with this problem :
Tests tries to create a java class , but folder where he do it do not  recognize as java package , so java class can not be created .

![selection_002](https://cloud.githubusercontent.com/assets/22724619/26050036/dfa148fe-3965-11e7-8d92-b6de2eeff405.png)

![com codenvy ide git commitfilestest commitfilestest_cpgesneh](https://cloud.githubusercontent.com/assets/22724619/26050352/f94fa39e-3966-11e7-9ca9-bb3f610d4fae.png)

**Comment by ghost** [comment]
It's a P1 for sure.

**Comment by vzhukovs** [comment]
Will be fixed after https://github.com/eclipse/che/issues/5164
