### ISSUE TITLE
Building a custom Che CLI

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5077]
Docs to be written:

1. How to build a custom Che CLI that can reference custom images (server, utilities images etc)
2. Suggestions on setting up CI around it.

The same set of docs should be written for Codenvy.

A few users have asked for it. Once of them is https://github.com/eclipse/che/issues/5076

**Comment by slemeur** [comment]
@vkuznyetsov : Please consider to add that issue into the next sprint. we have more requests coming for packaging custom Che.

**Comment by riuvshin** [comment]
@slemeur we'll do this in current sprint

**Comment by slemeur** [comment]
Thanks @riuvshin ! that's even better 👍

**Comment by ghost** [comment]
Fixed in https://github.com/eclipse/che-docs/pull/231
