### ISSUE TITLE
Configuration parameters of ws-agent from che.env

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5082]
For now, I have no normal ways to add an additional configuration parameter to ws-agent.  The only one way to work around it is to add additional file to war file like this: https://github.com/codenvy/plugin-openshift/pull/64/files#diff-40381beb2c15cc1c34a34691d4a07ff6R12 
But we have implemented https://github.com/eclipse/che/blob/master/plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java a way to do it from the properties file. All we need to do it to somehow define it in ```che.env``` file and then add to ```plugin-conf``` folder of ws-master

**Comment by riuvshin** [comment]
@skabashnyuk this feature with `plugin-conf` does not work, draft PR to reproduce https://github.com/codenvy/plugin-openshift/pull/66

**Comment by skabashnyuk** [comment]
I'm sorry my assumption was made on the outdate codebase. It's not longer possible to do.
