### ISSUE TITLE
Sometimes terminal scrollport adds one exceed line than terminal need

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#5084]
**Reproduction Steps:**

1. Open terminal.
2. Open Midnight Commander by typing "mc"
3. Resize terminal few times and click to the item "Help". If all Ok, try few times.

Actual result: terminal scrollport adds one exceed line and terminal input becomes broken.
Expected result: amount terminal lines in the scrollport should be the same like in the terminal widget.

![terminal_exceed_line](https://cloud.githubusercontent.com/assets/6873095/26097432/3623c630-3a2d-11e7-85df-9948d54306fe.png)

**OS and version:**    
os version: Fedora 25.
CHE version: 5.10.0-SNAPSHOT

**Comment by AndrienkoAleksandr** [comment]
I have a branch where is I'm working on fix for this issue: https://github.com/AndrienkoAleksandr/xterm.js/tree/CHE-5084 . But while I was working on this issue I saw that I need normal buffers to store info about current active terminal screen. And I saw such mechanism in the branch https://github.com/sourcelair/xterm.js/tree/buffer-set  . So I will merge my changes with this branch.
I created few pull requests for stabilization branch "buffer-set", because it still in progress:
https://github.com/sourcelair/xterm.js/pull/728
https://github.com/sourcelair/xterm.js/pull/740
https://github.com/sourcelair/xterm.js/pull/739
So this issue depends on "buffer-set" and I'm awaiting on merge my pull requests.

**Comment by AndrienkoAleksandr** [comment]
Buffer-Set branch merged. Guys from xterm.js created pull request https://github.com/sourcelair/xterm.js/pull/855/files to fix current issue, but into branch xterm.js 3.0. So we need create cq and update xterm.js to the version 3.0 when it will be released.

**Comment by SkorikSergey** [comment]
Cannot reproduce in CHE 6.12.0-SNAPSHOT.
