### ISSUE TITLE
che-cli would try to install docker/compose even though it's not found on dockerhub

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5088]
**Reproduction Steps:**
1:) Docker Pull on the latest Eclipse Che (5.10.0)
2:) Run CLI
Expected: would skip over and error out when docker/composer is not found
Result: 
![image](https://cloud.githubusercontent.com/assets/14976516/26099887/b62d2a3e-3a5e-11e7-8e7b-b15c52bf59ca.png)

**OS and version:**    Che 5.10.0 on Ubuntu 16.04.1 LTS

**Comment by sr229** [comment]
somehow the CLI has a precheck to see if the following exists, however, this seems to be only a check and ignores the following being not found and proceeds direct to pulling it.

**Comment by ghost** [comment]
@sr229 if you don't have such an image locally, then CLI pulls it. If the image is not found locally, it is not an error at all, it just means you do not have an image locally.

**Comment by ghost** [comment]
@sr229 and in your case, it's not compose image that is not found... you have connectivity issues.. your Docker daemon cannot connect to DockerHub...or DockerHub was down when you ran your start command.

**Comment by sr229** [comment]
I know but I noticed it has a precheck before pulling.

Shouldn't it not continue pulling when the image won't be found in DockerHub during the discovery stage for pulling the image?

**Comment by ghost** [comment]
@sr229 CLI checks for a local image. If not found, it then tries to pull it from DockerHub.
