### ISSUE TITLE
Support for custom colour themes and bundle default custom colour themes

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5089]
one of the things I've also noticed is Che doesn't have support for custom editor colour schemes.

It would be nice if we have support for such + prebundled custom colour schemes (preferrably the most loved ones)

**Comment by davidwindell** [comment]
I know my team are asking for Solarized!

**Comment by skabashnyuk** [comment]
Won't fix for GWT based ide.

**Comment by sr229** [comment]
Requesting this to be re-opened to target Theia IDE instead? They have a ThemeService (if I remember
 the precise name for the class).
