### ISSUE TITLE
Rework SPI components to allow clients to get current state of Runtime while it is still starting.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5092]
To allow clients make a load of workspace more smooth and provide a feeling that it starts faster we should allow retrieving of the current state of runtime while it is in starting state.
Goal:
-  Rework WorkspaceRuntimes and  WorkspaceManager - Workspace runtime should be available during workspace start 
- Revise methods WorkspaceManager.removeWorkspace an DockerAbandonedResourcesCleaner.cleanNetworks . Now we have assumptions that WorkspaceRuntimes.hasRuntime true if a workspace is running. After 1. it wouldn't be true.

**Comment by gazarenkov** [comment]
The contract of Context and Runtime changed.
Now Context is able to create/return Runtime independently of its state (unconditionally getRuntime() added).
So *start()/stop()* methods as well as *status* should be moved from Context to InternalRuntime
