### ISSUE TITLE
 How to tell Che to only build one type of browser JavaScript with new Che extension

### ISSUE THREAD

**Issue by vnea** [eclipse-che/che#5106]
Hello,

With the old Che, it was possible to [tell Che to only build one type of browser JavaScript](https://www.eclipse.org/che/docs/assemblies/plugin-lifecycle/index.html#improving-incremental-builds):
```
<!-- Tell Che to only build one type of browser JavaScript -->
<!-- Values can be 'safari' or 'firefox'.  Safari builds for chrome -->
<set-property name="user.agent" value="safari"/>
```

But now the file **/assembly/assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml** does not exist anymore with the new Che.

Is it still possible with the new Che to edit this property somewhere to make the build process faster ?

**Comment by skabashnyuk** [comment]
This template is used https://github.com/eclipse/che/blob/master/ide/che-core-ide-generators/src/main/resources/org/eclipse/che/util/gwt.xml.template to generate IDE.gwt.xml  I think ```user.agen``` is not configurable right now but I think you can easily contribute this change to https://github.com/eclipse/che/blob/master/ide/che-core-ide-generators/src/main/java/org/eclipse/che/util/GwtXmlGenerator.java if you can explain how to use it.

**Comment by vnea** [comment]
Thank you, I won't be able to do it during my working time but maybe later...
