### ISSUE TITLE
Register Language Server for File Name

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#5107]
There are many instances where a particular filename defines a "subtype" of a file type, for example, pom.xml or package.json and the likes.
We would like to register language servers for those particular file names as well as for extensions.

I am currently working on a PR for this issue.

**Comment by iamslite** [comment]
Are you meaning specific language servers, or being able to relate existing language servers to additional extensions?

When developing for Drupal7 I would want to be able to indicate that '.inc' and '.module' are also PHP files for example.

**Comment by tsmaeder** [comment]
This is not a user-level feature, I'm talking about the registration code for language servers.
