### ISSUE TITLE
After rename and deleting packages the new created packages are not displayed

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5108]
**Reproduction Steps:**
- Create spring java project
- Go to the root package and create new packages (p.p.p)
- Click on them and open refactor window (shift + F6)
- Rename one of the packages (p.r.p)
- After rename delete all three packages
- Click on root package and try to create new packages (n.n.n)
- Pay attention to the screen

**Expected Behavior:**
Packages will be displayed

**Observed behavior:**
Packages are displayed only after browser refresh

**Attachment:**

![anim](https://cloud.githubusercontent.com/assets/22724619/26111517/fa5c49d4-3a5d-11e7-9251-6925f3045cfb.gif)

**Comment by svor** [comment]
Can't reproduce
