### ISSUE TITLE
Workspace crashing browser

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5111]
One of my colleagues @minlare is experiencing Che locking up his browser (Chrome 58) window and according to `top` the tab is stuck using over 100% CPU. 

At the moment we are struggling to find a pattern for this one as often he is just writing code and not using any workspace functions. It can happen after an hour or more of running the workspace running fine.

Opening the same workspace in another tab at the same time works without any problems.

What debug information can we provide to help isolate the issue?

*Che 5.10 on Docker*

**Comment by ghost** [comment]
@davidwindell does it happen when you run a command that produces a lot of output? Or just leaving a workspace inactive for a long time?

**Comment by minlare** [comment]
@eivantsov I am not running any commands, or leaving a workspace inactive for a long time. The only way I seem to be able to speed it up again is to killall chrome processes and clear the browser cache. Will taking a trace of some sort from Chrome help?

_This is not isolated to Chrome as I encounter the same issue with Firefox_

**Comment by ghost** [comment]
@minlare what I am asking for is steps to reproduce. Or at least try to reproduce.

**Comment by minlare** [comment]
![eclipse-che-speed-issue](https://cloud.githubusercontent.com/assets/1862882/26152935/212be710-3b01-11e7-9ced-444c2b1afa7c.png)
![eclipse-che-speed-issue-code](https://cloud.githubusercontent.com/assets/1862882/26152937/24e3772e-3b01-11e7-8498-ee3ed023f09a.png)

guessing this might be causing the issue...

**Comment by ghost** [comment]
Do you have this in an incognito tab? Maybe Chrome or FF extensions are to blame here 'cause I do not have the same in dev console of my Chrome.

**Comment by davidwindell** [comment]
@eivantsov yep same problem with all extensions disabled and on a completely different machine remotely accessing this (you have to enable Verbose logging in Chrome). 

Those errors are endlessly reported which probably causing an overflow somewhere?

**Comment by davidwindell** [comment]
@eivantsov would remote access to the che-server help you debug?

**Comment by ghost** [comment]
Yes, accessing workspace from my machine will help

**Comment by davidwindell** [comment]
@eivantsov can you drop me an email with your IP and I'll whitelist you?

**Comment by ghost** [comment]
@davidwindell after updating Chrome to 58 I do see the same behavior when accessing a workspace with opened files on your instance.

However, when trying to reproduce it locally with the same version of Che, and your particular project, I failed to see so many violations. In my case, I see one per opened file.

I wonder if it has smth to do with networking and nginx being in front of Che.

@davidwindell @minlare can you reproduce it locally with Che?

And a fun fact - since I have Core i7, browser tab doers not crash my Chrome :) But I assume on less powerful machines it does.

**Comment by davidwindell** [comment]
@eivantsov I've now tried without Nginx proxy on the same workspace and the problem persists so it's not related to that. On my i7 it goes uber slow within a minute or two.

I seem to be able to reproduce it by opening a minimum of two, large, php files with big arrays in them and the refreshing the page (although I don't see how this relates to reflows, etc in the browser).

I'll keep testing and report back when I can reproduce in another workspace.

**Comment by ghost** [comment]
The weird part if that I cannot reproduce it with the same Chrome version and your exact project. When a file is opened, this warning shows up once in Chrome console - one per opened file.

@davidwindell can you reproduce it on a local machine? Or any other instance different from the one where it can be reproduced?

**Comment by davidwindell** [comment]
@eivantsov It's just happened on another colleagues workspace with a completely different project/set of files. He wasn't doing anything unusual, it just seems to suddenly go into those excess error loops.

**Comment by ghost** [comment]
@davidwindell I was unable to reproduce on a few machines. Does it happen to one particular Che installation? Can you reproduce the same behavior locally with a new install?

**Comment by davidwindell** [comment]
This seems to have resolved itself at some point between 5.10 and 5.16!
