### ISSUE TITLE
Step into feature works wrong with debugging some external classes

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5113]
**Reproduction Steps:**
1. Import next project as maven:   
[java-ext-class-project.zip](https://github.com/eclipse/che/files/1007390/java-ext-class-project.zip) . Context Menu -> Maven->reimport.
2. Edit->RemoteDebug Configuration -> set default configuration for java.
3. Open  SimpleLogger.class.
4. Open  Run next command:
```mvn -f ${current.project.path} clean install && java -jar -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 ${current.project.path}/target/java-with-external-libs-1.0-SNAPSHOT-jar-with-dependencies.jar```
5. Set breakpointin 13. 
6. Run->debug->connection to debug. Wait active state breakpoint with highlighting current string
7. Launch Step Into button
**Expected result :**   
Should be open Logger external class, the content ```filterAndLog_1(FQCN, null, Level.INFO, format, arg, null);``` should be highlighted in red color.
**Actual result**:
The breakpoint is not set in the class properly. I think it happens because when debugger try to set breakpoint unexpectedly performs 'Download Source' operation. After that, the content is updated and breakpoint position became broken.
![anim](https://cloud.githubusercontent.com/assets/1640058/26153366/a9a96790-3b13-11e7-9a60-49d671ddffcd.gif)

**OS and version:**   Ubuntu 14.0 TLS, Chrome browser, server location: **nightly.codenvy-stg.com**

Related selenium test: DebugExternalClassTest

**Comment by ghost** [comment]
Looks similar to https://github.com/eclipse/che/issues/5236
