### ISSUE TITLE
The Python language server isn't enabled by default for Python stacks

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5114]
**Reproduction Steps:**
- **Workspaces** -> **Add workspace** button -> **Runtime** tab
- From the **Stack Library** tab select any python stack
- See on the **Machine** settings

**Observed behavior:**
The Python language server isn't enabled 

**Che version**: 5.11.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/26148679/37fd9962-3b00-11e7-844f-3f07f8404f43.gif)

**Comment by artaleks9** [comment]
The bug is reproduced on the CHE only.
On the hosted version works correctly.

**Comment by Ohrimenko1988** [comment]
This is problem also reproduced on the redhat.codenvy.com

**Comment by ashumilova** [comment]
Is not reproduced on fresh Che version
