### ISSUE TITLE
Cannot start new debug session after session that has been created earlier

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5116]
**Reproduction Steps:**
1. Import next project as maven:   
[java-ext-class-project.zip](https://github.com/eclipse/che/files/1007390/java-ext-class-project.zip) . Context Menu -> Maven->reimport.
2. Edit->RemoteDebug Configuration -> set default configuration for java.
3. Open  SimpleLogger.class.
4. Open  Run next command:
```mvn -f ${current.project.path} clean install && java -jar -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 ${current.project.path}/target/java-with-external-libs-1.0-SNAPSHOT-jar-with-dependencies.jar```
5. Set breakpointin 13. 
6. Run->debug->connection to debug. Wait active state breakpoint with highlighting current string
7. End Debug Session. clear all breakpoints
8. Start new debug session (perform steps that have been described above)
**Expected result:** The new debug connection should be set
**Actualr result:** The new debug connection does not start. We have console browser exception like:
![selection_040](https://cloud.githubusercontent.com/assets/1640058/26300500/f5f08634-3ee6-11e7-88e7-f915c4e5ecdd.png)

**OS and version:**   Ubuntu 14.0 TLS, Chrome browser,  server location: **nightly.codenvy-stg.com**

Related selenium tests: MultimoduleProjectDebuggingTest, DebugExternalClassTest

**Comment by slemeur** [comment]
@vkuznyetsov please take a look.
I have seen the same problem.

**Comment by tolusha** [comment]
It isn't a issue unless it prevents to create another debug session.

**Comment by slemeur** [comment]
My use case was a bit different.

- I created a workspace and imported a project. 
- Use the debugger and setup a breakpoint.
- I stop workspace and delete it.
Then:
- I created another workspace (with a different name) and import the same project.
- when I opened the file where I previously setup a breakpoint in the previous workspace, I was having the same breakpoint displayed back into this newly created workspace.

**Comment by tolusha** [comment]
How long ago did you face the issue?

**Comment by slemeur** [comment]
I'm having it right now.

See the attached gif, where I'm creating a new workspace - but once loaded, I have a breakpoint already there:
![debugger-cache-issue](https://cloud.githubusercontent.com/assets/1636769/26242442/c23e2482-3c88-11e7-8d26-d5a06a87a66e.gif)

**Comment by AndrienkoAleksandr** [comment]
@slemeur issue description was changed, so your comments is not actual for current issue. Create, please, separated issue.
