### ISSUE TITLE
Editor is not updated after to perform refactor move an item(regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#5124]
**Reproduction Steps:**
* Create a project which has a few packages and java files
* Open a java file and create instance of another java class (e.g. _Java-class_ _A5_)
* Make refactor move a java-class in another package   

**Expected behavior:**
* the editor should update the content of import after moving a java class

**Observed behavior:**
* the editor is not updated
* need to reopen java file or refresh browser

**Che version:** 5.11.0
**OS and version:** Ubuntu 14.04
**Docker version:** 1.13
**Che install:** Docker container  

**Additional information:**

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![move_item](https://cloud.githubusercontent.com/assets/5408906/26197833/60ee55e2-3bcc-11e7-9544-09f9d357b9ad.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT

**Comment by artaleks9** [comment]
* A few last days this bug is not reproduced.
* Related autotest 'CodeAssistAfterMoveItemTest' passes successful on the CI.
* I presume that it was fixed by https://github.com/eclipse/che/pull/5391
