### ISSUE TITLE
Make Docker SPI implementation pass events to master that should pass it to clients

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#5125]
In new SPI Runtime implementation should pass events such as servers statuses, machines statuses to master. Then master will be able to pass them to interested clients.

**Comment by sleshchenko** [comment]
## Events specification
The current version of specification is placed here https://github.com/eclipse/che/issues/5144
It's not done yet and it's planned to extend it.

## Implemented approach
1. Infrastructure publishes DTO events about something by direct usage of EventService.
\* Decided to use DTO events on the server side while there is no necessity to create separated implementations.
2. Workspace master listens to these events and:
- process them itself 
- propagate them for subscribed clients.

#### Machine Events
Within https://github.com/eclipse/che/pull/5318 implemented publishing of events about machine status by infra. Workspace master republishes these events to subscribed clients (see MachineStatusJsonRpcMessenger).

#### Server Events
Publishing of events about servers statuses changes will be implemented later when Installer and maybe health checks will be done.

## Alternative approach
As the alternative way, we could use [EventsConsumer](https://github.com/eclipse/che/compare/spi...sleshchenko:spi_infrastructure_events?expand=1#diff-9ada5b98733e749d9a68c19f83824b90) interface for declaration contract within java code.

In this case, master provides an instance of EventConsumer to infrastructure, infrastructure propagates events by invocation corresponding methods of this instance. Master is able to process propagated event by itself and propagate them for subscribed clients.

#### Advantages
That give the ability for infra implementors easy find the specification about events.
Also it this case we would avoid dependency of infra on EventService and Dto frameworks.

In this approach publishing of machines events would have following https://github.com/eclipse/che/compare/spi...sleshchenko:spi_infrastructure_events?expand=1#diff-ca7c746b73f047271463f02b7caf51e0R130.
