### ISSUE TITLE
Executing a command via terminal works fine, but fails when executed as a Eclipse-Che-Command

### ISSUE THREAD

**Issue by sg82fe** [eclipse-che/che#5126]
I did not find a similar issue, so i started this one.
I have a C++ project that is hosted on git.  
The project can be build via cmake and make.
There is a specific SDK (poky-compiler/linker/... etc -  created with yocto) to cross-compile the C++ project for another hardware.

So what is working fine in che is: 
- I imported the project (git)
- I use the **Terminal** to build the project what works fine: 
  `cd /opt/poky/2.1`
  `source environment-setup-corei7-64-poky-linux`  // setup environment (correct compiler..)
  `cd /projects/myProject` // go to the CMakeLists.txt location
  `cmake -Dmytargetapp=On` // run cmake succesfully builds the executable
  'make' // build it
- So this works fine in the terminal console of Che, the project is build (compiled and linked) 

- _But_ in case i create a Che command by combining the steps done in Terminal:
   ( source /opt/poky/2.1/env-setup && cmake &&  cmake) 
   I get this error at the *cmake* stage:

> cmake -Daracomex=ON .. && make
>-- The C compiler identification is GNU 4.9.3
>-- The CXX compiler identification is GNU 4.9.3
>-- Check for working C compiler: /opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux/x86_64-poky-linux-gcc
>-- ....
>-- ...
>CMake Error at /opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.4/Modules/FindBoost.cmake:1247 (message):
>  Unable to find the requested Boost libraries.
> 
 > Unable to find the Boost header files.  Please set BOOST_ROOT to the root
 > directory containing Boost or BOOST_INCLUDEDIR to the directory containing
 > Boost's headers.
>Call Stack (most recent call first):
>  CMakeLists.txt:224 (find_package)
> 
>
>CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
>Please set them or make sure they are set and tested correctly in the CMake files:
>-- Configuring incomplete, errors occurred!
>Boost_INCLUDE_DIR (ADVANCED)
>   used as include directory in directory /projects/public-sample-repo
>See also "/projects/public-sample-repo/output/CMakeFiles/CMakeOutput.log".
>See also "/projects/public-sample-repo/output/CMakeFiles/CMakeError.log".
  
for completeness, here are the lines from CMakeLists.txt
```
218 # Dependency management of 3rd party libraries
219 #
220 # Threads
221 find_package(Threads REQUIRED)
222
223 # Boost
224 find_package(Boost COMPONENTS program_options REQUIRED)
225 set(Boost_USE_STATIC_LIBS ON)
226 include_directories(${Boost_INCLUDE_DIRS})
```

It might be none-che Issue, but i don't understand why the behaviour is different between Terminal and Command.

**Reproduction Steps:** as described above.

**OS and version:**    Ubuntu 16.04 LTS 

same behaviour on RedHat Linux and Che 5.9.0 / 5.10.0

**Comment by ghost** [comment]
@sg82fe I am pretty sure it is because of the following command:

`source /opt/poky/2.1/env-setup`

Sometimes, if source is performed in a non interactive shell, it does nothing: for example it is so with `~/.bashrc`:

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;

```
Can you share content of `source /opt/poky/2.1/env-setup`?

**Comment by sg82fe** [comment]
Thanks for your reply,
But how do i come out of the situation - i put everything from the source script to the command?

The content of the source script is:

`export SDKTARGETSYSROOT=/opt/poky/2.1/sysroots/corei7-64-poky-linux`
`export PATH=/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/sbin:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/bin:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/sbin:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/../x86_64-pokysdk-linux/bin:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux-uclibc:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux-musl:$PATH`
`export CCACHE_PATH=/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/../x86_64-pokysdk-linux/bin:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux-uclibc:/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/bin/x86_64-poky-linux-musl:$CCACHE_PATH`
`export PKG_CONFIG_SYSROOT_DIR=$SDKTARGETSYSROOT`
`export PKG_CONFIG_PATH=$SDKTARGETSYSROOT/usr/lib/pkgconfig`
`export CONFIG_SITE=/opt/poky/2.1/site-config-corei7-64-poky-linux`
`export OECORE_NATIVE_SYSROOT="/opt/poky/2.1/sysroots/x86_64-pokysdk-linux"`
`export OECORE_TARGET_SYSROOT="$SDKTARGETSYSROOT"`
`export OECORE_ACLOCAL_OPTS="-I /opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/share/aclocal"`
`unset command_not_found_handle`
`export CC="x86_64-poky-linux-gcc  -m64 -march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2 --sysroot=$SDKTARGETSYSROOT"`
`export CXX="x86_64-poky-linux-g++  -m64 -march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2 --sysroot=$SDKTARGETSYSROOT"`
`export CPP="x86_64-poky-linux-gcc -E  -m64 -march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2 --sysroot=$SDKTARGETSYSROOT"`
`export AS="x86_64-poky-linux-as  "`
`export LD="x86_64-poky-linux-ld   --sysroot=$SDKTARGETSYSROOT"`
`export GDB=x86_64-poky-linux-gdb`
`export STRIP=x86_64-poky-linux-strip`
`export RANLIB=x86_64-poky-linux-ranlib`
`export OBJCOPY=x86_64-poky-linux-objcopy`
`export OBJDUMP=x86_64-poky-linux-objdump`
`export AR=x86_64-poky-linux-ar`
`export NM=x86_64-poky-linux-nm`
`export M4=m4`
`export TARGET_PREFIX=x86_64-poky-linux-`
`export CONFIGURE_FLAGS="--target=x86_64-poky-linux --host=x86_64-poky-linux --build=x86_64-linux --with-libtool-sysroot=$SDKTARGETSYSROOT"`
`export CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/sni1si/6iPlatform/tmp/work/x86_64-nativesdk-pokysdk-linux/meta-environment-mohonpeak64/1.0-r8=/usr/src/debug/meta-environment-mohonpeak64/1.0-r8 -fdebug-prefix-map=/home/sni1si/6iPlatform/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/home/sni1si/6iPlatform/tmp/sysroots/x86_64-nativesdk-pokysdk-linux= "`
`export CXXFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/sni1si/6iPlatform/tmp/work/x86_64-nativesdk-pokysdk-linux/meta-environment-mohonpeak64/1.0-r8=/usr/src/debug/meta-environment-mohonpeak64/1.0-r8 -fdebug-prefix-map=/home/sni1si/6iPlatform/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/home/sni1si/6iPlatform/tmp/sysroots/x86_64-nativesdk-pokysdk-linux= "`
`export LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"`
`export CPPFLAGS=""`
`export KCFLAGS="--sysroot=$SDKTARGETSYSROOT"`
`export OECORE_DISTRO_VERSION="2.1"`
`export OECORE_SDK_VERSION="2.1"`
`export ARCH=x86`
`export CROSS_COMPILE=x86_64-poky-linux-`
`echo Append environment subscripts`
`if [ -d "$OECORE_TARGET_SYSROOT/environment-setup.d" ]; then`
`    for envfile in $OECORE_TARGET_SYSROOT/environment-setup.d/*.sh; do`
`	    source $envfile`
`    done`
`fi`
`if [ -d "$OECORE_NATIVE_SYSROOT/environment-setup.d" ]; then`
`    for envfile in $OECORE_NATIVE_SYSROOT/environment-setup.d/*.sh; do`
`	    source $envfile`
`    done`
`fi`




and in case i extend the script with `cmake -Dmytarget=ON` , then i still get the error that  'Boost'-Libraries are not found

**Comment by ghost** [comment]
@sg82fe I can see more sourcing in this file:

```
if [ -d "$OECORE_TARGET_SYSROOT/environment-setup.d" ]; then
for envfile in $OECORE_TARGET_SYSROOT/environment-setup.d/*.sh; do
source $envfile
done
fi
if [ -d "$OECORE_NATIVE_SYSROOT/environment-setup.d" ]; then
for envfile in $OECORE_NATIVE_SYSROOT/environment-setup.d/*.sh; do
source $envfile
```

Maybe those .sh scripts cannot be sourced when in a non interactive mode?

**Comment by sg82fe** [comment]
I was not aware of interactive / non-interactive shells, and that there are side-effects.

So what would be the option to setup the environment and call cmake properly in a non-interactive mode?
- using 'bash' source in the command?
- putting all from the sourced script into the command? 

I'll continue playing around with it..

**Comment by ghost** [comment]
@sg82fe i have tried a few workaround but they failed for me. If the file/script explicitly says it does nothing in an interactive mode (like ~/.bashrc).

Most likely files sourced from the original one are ignored in a non interactive shell.

**Comment by sg82fe** [comment]
Meanwhile i could a little isolate and also 'solve' the problem. To Summarize
so basically the sourcing of the file works in the command, what seems to be what was not working is an alias for the cmake(?)

Long Story: I believe it makes no difference if i source the script in the che command by
`source /opt/poky/2.1/source environment-setup-corei7-64-poky-linux && cmake && make`
or i put the whole content of the shell-script into the command 
`$ export PATH=.... && ... && ... && make`
My observation after testing many variations is: The behaviour is the same, the environmentvariables that are set in the (non-interactive)shell / process are set correct and can be verified.

### The shell script contains some inclusion of further sourcing:
```
if [ -d "$OECORE_TARGET_SYSROOT/environment-setup.d" ]; then
for envfile in $OECORE_TARGET_SYSROOT/environment-setup.d/*.sh; do
source $envfile
done
fi
```
The result of the conditional looped inclusions/sourcing evaluates to one line in console. It is an alias:
`alias cmake="cmake -DCMAKE_TOOLCHAIN_FILE=/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/share/cmake/OEToolchainConfig.cmake"`

 **And now the strange thing**
### What is _not_ working:  
`source environment-setup && echo $PATH && echo alias cmake && cmake -Dtarget=ON`
everything looks perfect, the alias of cmake is as expected - But I get the error executing cmake, with not finding the Boost Libraries.
### What _is_ working:
`source environemnt-setup && echo $PATH && echo alias cmake && cmake -DCMAKE_TOOLCHAIN_FILE=/opt/poky/2.1/sysroots/x86_64-pokysdk-linux/usr/share/cmake/OEToolchainConfig.cmake -Dtarget=ON`

ignoring the alias, and writing the cmake command with all arguments, this is working perfect - no error at Boost libraries, and the output is exactly the same as i would have done everything manually in a user-interactive terminal console.(Checked with Beyond compare)

So i have a workaround/solution- i can use the eclipse che command
`source env-setup && cmake -DCMAK_TOOLCHAINFILE=/...bla && cmake -Dmytarget=ON`

But still this alias behaviour makes me curious

**Comment by mdnasr** [comment]
I have faced the same problem, and I have found that aliases are not expanded when the shell is not interactive, unless the `expand_aliases` shell option is set using `shopt`.

```
shopt -s expand_aliases
source environment-setup-corei7-64-poky-linux
```

Also see this [Stackoverflow answer](https://unix.stackexchange.com/questions/1496/why-doesnt-my-bash-script-recognize-aliases)
