### ISSUE TITLE
Create docker build profile

### ISSUE THREAD

**Issue by voievodin** [eclipse-che/che#5127]
Che project uses many technologies and programming languages and requires developer to have all of them installed if he/she wants to build the project. Moreover the versions of all the installed tools must match the version supported by the project.

These technologies include:
- java
- maven
- nodejs
- gulp
- bower 
- golang

Some of che subprojects such as [exec-agent](https://github.com/eclipse/che/tree/master/agents/go-agents) might depend on linux specific stuff like sys calls - which causes problems like [this one](https://github.com/eclipse/che/issues/4758). Obviously sometimes we can workaround such problems by skipping build of some of the artifacts, but it doesn't work always.

The solution i see is creation of a __docker__ build profile which brings the following benefits: 

1. Reduced amount of tools needed to build the project.
Well, we still need _java_,  _maven_ and _docker_ but that's all. 

2. Tool version switch made easier  e.g. if we want to switch golang version from 1.6 to 1.8 we don't need to force user to do that.

3. Better stability, less bugs.
Lets say we require _build-tool-x v11+_, we're using _build-tool-x v11_ for building the product and on our CI and everything works fine but it turns out that _build-tool-x v12_ introduces a bug and developers who have it installed might have build issues.

The *docker* profile could help us to cover these topics.

@TylerJewell, @benoitf, @skabashnyuk, @riuvshin  what do you think about it?

**Comment by benoitf** [comment]
Building with docker is really good, we've start to do it for dockerfiles directory
Also, even if it may include an overhead in performance, it's good to have a universal build that work on all platforms where docker is installed. 

BTW @evoevodin, do you see docker profile being the only way or it's an alternate way when required tools are not setup (or user doesn't want to) of native builds

**Comment by voievodin** [comment]
i see it as alternate way to build the project
```
mvn clean install          <- uses native tools
mvn clean install -Pdocker <- uses docker even if there are native tools installed
```

**Comment by benoitf** [comment]
@evoevodin ok this is how I was understanding it but I wanted to be sure.

**Comment by skabashnyuk** [comment]
won't fix
