### ISSUE TITLE
Question on bannedDependencies

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#5129]
The che root pom bans some dependencies via the maven-enforcer-plugin (org.sl4j:sl4j-nop, -jdk14, ....) and some more.
I wanted to include a library into an agent that requires some of the banned dependencies.

Can you provide some general background, why these dependencies are banned? 

Will it cause trouble if I use those dependencies or are they just banned to enforce the use of standard libraries for the project?

**Comment by ghost** [comment]
@ChristianSchenk711 you may skip enforcer with `-Denforcer.skip=true`

As to why some libs are banned, @skabashnyuk can elaborate on each case, but for example if case of sl4j-nop these will be troubles with logs.

**Comment by skabashnyuk** [comment]
>Will it cause trouble if I use those dependencies or are they just banned to enforce the use of >standard libraries for the project?

Yes it will cause some trouble and yes it forced to use standard. For example:
org.sl4j:sl4j-nop, -jdk14, .... -> forced to use logback as backend
xalan,woodstox,xml-apis,xml  - JDK
jsr250-api - license is not allowed.

BTW you are not forced to use che parent in your projects.

**Comment by ChristianSchenk711** [comment]
Thanks for the answers. So it's not only enforced to keep the set of libraries lean/clean but there are definintly issues I might run into. I'm aware that I can skipt the enforcer, but if it's likely that I run into problems, I would rather avoid that. Even if I don't use the che-parent, still my code runs as part of the ws-agent so the problems will still be there, right?

**Comment by skabashnyuk** [comment]
> Even if I don't use the che-parent, still my code runs as part of the ws-agent so the problems will >still be there, right

Something like that. Do you have some concrete issues with that list of banned libraries?

**Comment by ChristianSchenk711** [comment]
My specific use case is that I want to include org.eclipse.lyo.clients:oslc-java-client.  (to talk to IBMs ALM suite via OSLC). This has a ton of dependencies (added below) and these three are banned:

xml-apis:xml-apis:jar:1.3.04
org.slf4j:slf4j-log4j12:jar:1.6.4
javax.xml.stream:stax-api:jar:1.0-2

So I'm wondering if I can remove them form the ban -or-  if I rather start putting my client in a separate agent to avoid potential problems. -or- talk to the IBM interfaces using plain REST, which should also be possible, just a little bit more work on my side.

just FYI: These are all the dependencies lyo wants:
\- org.eclipse.lyo.clients:oslc-java-client:jar:2.1.2:compile
   +- org.apache.jena:jena-core:jar:2.7.1:compile
   |  +- org.apache.jena:jena-iri:jar:0.9.1:compile
   |  \- org.slf4j:slf4j-log4j12:jar:1.6.4:compile
   +- net.oauth.core:oauth:jar:20090617:compile
   +- net.oauth.core:oauth-consumer:jar:20090617:compile
   +- net.oauth.core:oauth-httpclient4:jar:20090913:compile
   +- org.apache.wink:wink-client:jar:1.4:compile
   |  +- org.apache.wink:wink-common:jar:1.4:compile
   |  |  +- org.apache.geronimo.specs:geronimo-jaxrs_1.1_spec:jar:1.0:compile
   |  |  \- org.apache.geronimo.specs:geronimo-annotation_1.1_spec:jar:1.0:compile
   |  +- javax.xml.bind:jaxb-api:jar:2.2:compile
   |  |  \- javax.xml.stream:stax-api:jar:1.0-2:compile
   |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.1.1:compile
   |  \- javax.activation:activation:jar:1.1:compile
   +- org.apache.wink:wink-client-apache-httpclient:jar:1.4:compile
   |  \- org.slf4j:jcl-over-slf4j:jar:1.7.24:compile
   +- org.eclipse.lyo.oslc4j.core:oslc4j-core:jar:2.1.2:compile
   +- org.eclipse.lyo.oslc4j.core:oslc4j-jena-provider:jar:2.1.2:compile
   +- org.eclipse.lyo.oslc4j.core:oslc4j-json4j-provider:jar:2.1.2:compile
   |  \- org.apache.wink:wink-json4j:jar:1.2.1-incubating:compile
   +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
   +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
   |  +- commons-logging:commons-logging:jar:1.2:compile
   |  \- commons-codec:commons-codec:jar:1.10:compile
   +- log4j:log4j:jar:1.2.17:compile
   +- xerces:xercesImpl:jar:2.8.0:compile
   +- xml-apis:xml-apis:jar:1.3.04:compile
   +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
   \- javax.ws.rs:jsr311-api:jar:1.1.1:compile

**Comment by skabashnyuk** [comment]
you want to develop a plugin that will be working inside of ws-agent and it will include  org.eclipse.lyo.clients:oslc-java-client. Correct?

**Comment by ChristianSchenk711** [comment]
That was the plan and then I encountered the "bannedDependencies".

**Comment by skabashnyuk** [comment]
I'm 99% sure you can exclude this list of libraries without the problem
```
xml-apis:xml-apis:jar:1.3.04
org.slf4j:slf4j-log4j12:jar:1.6.4
javax.xml.stream:stax-api:jar:1.0-2
```

**Comment by ChristianSchenk711** [comment]
99% is enough for me to give it a try.  I will exclude the bans locally and check. Thanks for the advice.
