### ISSUE TITLE
Unexpected resetting of the scroll to bottom automatically button

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5130]
**Reproduction Steps:** 
1. Create a new workspace base on Java stack. Create the Spring project. 
2. Launch the buils and run command.  Watch on log of the command.
**Expected result:**  the ```Scroll to bottom automatically``` button should be pressed. The log should be scrolled automatically.
**Actual result:** after first line under scroll the button becomes unselected.
**OS and version:**    Ubuntu 14 TLS, Chrome browser
![anim](https://cloud.githubusercontent.com/assets/1640058/26240620/4bd144c6-3c8a-11e7-9ab2-b29137ac25a0.gif)

**Comment by slemeur** [comment]
please @vitaliy-guliy give a look.

**Comment by ghost** [comment]
@slemeur this heavily impacts user experience. I am surprised it has slipped from your catchy eye.

**Comment by slemeur** [comment]
I can't be more agree with you :) ! It has been planned in the sprints, and is in the current one. 

I imagine that @vitaliy-guliy has not been able to get it solved. Maybe @ashumilova we could have @vzhukovskii giving a quick look on that?
