### ISSUE TITLE
Autocomplete does not work in Terminal

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5132]
Autocomplete tab actions don't seem to work for programs like git (and others).

For example, if you SSH into the workspace and type `$ git pull <tab>` it will autocomplete `origin` for example and then list the remote branches. 

This doesn't seem to work in the browser terminal and instead <tab> always only lists the files in the $PWD.

**Comment by ghost** [comment]
@davidwindell it has just worked for me. When you say SSH into a workspace, does it mean you SSH into it from your own terminal?

**Comment by davidwindell** [comment]
@eivantsov what stack did you test? This is happening for us on the ubuntu base stack. Using the SSH into workspace option (i.e. on a custom port) it works just fine.

**Comment by ghost** [comment]
What is ubuntu base stack? `eclipse/stack-base:ubuntu`?

**Comment by davidwindell** [comment]
@eivantsov I've just tested `eclipse/stack-base:ubuntu` and `eclipse/php` and those work fine :confused:  so it must be something our custom stack is doing.

Can you see anything unusual? https://github.com/outeredge/edge-docker-che-base/blob/master/Dockerfile

**Comment by ghost** [comment]
@davidwindell I do actually

https://github.com/outeredge/edge-docker-che-base/blob/master/Dockerfile#L3

Maybe adding `USER user` at the end helps?

**Comment by davidwindell** [comment]
@eivantsov thanks, I'll try and report back. We do want default user to be root though

**Comment by davidwindell** [comment]
Probably worth adding that `gi<tab>` autocompletes to `git` just fine.

**Comment by davidwindell** [comment]
Apparently `/root/.bashrc` on ubuntu doesn't source `/etc/bash_completion` by default (which is where git autocomplete additions lives). Thanks for the help @eivantsov !

https://askubuntu.com/a/156668
