### ISSUE TITLE
Incorrect processing JSON RPC responses

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#5135]
We get NPE at processing JSON RPC responses. 

**Reproduction Steps:**
1. Create a JSON RPC request
2. Don't process JsonRpcPromise

You can see NPE in a browser console.

**OS and version:**    Ubuntu 16.04 TLS, Chrome browser

**Comment by dkulieshov** [comment]
Can't reproduce

**Comment by RomanNikitenko** [comment]
Fixed by PR #5341
