### ISSUE TITLE
Client-Master-Infrastructure v6 communication  

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#5144]
DRAFT:

Peers to communicate:
- client (like IDE or UD or anything)
- master (where Workspace API/SPI works)
- infrastructure which covers all the complexity of Workspace Runtime starting/stopping and communication 

For asynchronous JSON-RPC communication Workspace use 2 WebSocket endpoints (physical channels):
- Status Channel maintained by Master. Which means that Master creates unique per-Workspace endpoint and sends it to Client and passes to Infrastructure as a Status Channel. Infrastructure uses this channel to send status events to. Master listens and reacts on events from Infrastructure which causes changes of Workspace state.
- Output Channel may be created by Infrastructure and point to different than Master host in order to not to load it with potentially big amount of output from Machines and Installers. In a simpler case Infrastructure may point this channel to Master host (same host/port as Status Channel).

Workspace Starting status messages:
- Client (directly or by reference to persisted configuration)  sends sync (REST API) Workspace.start with **Workspace Configuration object** (JSON format)
- Master broadcasts Workspace.start event (state channel), set Workspace.STARTING state, prepares Runtime Context object and asynchronously calls Infrastructure.start(). Starting from this moment by Client request Workspace API should return Workspace Runtime Object which includes Runtime (Machines, Servers) in its actual intermediate state.
- Infra starting Runtime. It supposed to be long process. In a course of Workspace starting:
- Infra starting Machines and (optionally if it it can support it) emits Machine.start event and sets Machine.STARTING, then RUNNING state
- Infra installing **Bootstrapper** and starting **Installers**. Installer emits start/finish event. Also, in a case if it starts Servers it may emit Server.start and running 
- Infra may support some specific statuses and emit specific events  (such as snapshotting/restoring) to inform a Client
- Infra may recognize if something wrong happened on start, decide to stop Runtime and notify Master about it with Runtime.stop event. Master broadcasts Workspace.stop event (Status channel), set Workspace.STOPPING state
- Infra returns Runtime, Master broadcasts Workspace.didStart event and set Workspace.RUNNING.
Running Workspace:
- Client request or by Infra scheduler performed Servers healthchecking (?)
- Infra may recognize if something wrong happened on runtime (OOM for example), decide to stop Runtime and notify Master about it with Runtime.stop event. Master broadcasts Workspace.stop event (Status channel), set Workspace.STOPPING staus

Workspace Stopping:
- Client sends sync (REST API) Workspace.stop OR Infra recognizes that something wrong happened and notifies Master.
- Master broadcasts Workspace.stop event (Status channel), set Workspace.STOPPING status
- In a case if Client asks for the Workspace Runtime Object  Master returning Runtime (Machines, Servers) in its actual intermediate state (stopping in progress)
- Runtime destroyed, Master broadcasts Workspace.didStop event and set Workspace.STOPPED status

Output messages sent to OutputChannel:
- Output of Machine starting (such as Docker container create/start output)
- Output of Installers (Agents)

**Comment by TylerJewell** [comment]
Hi @gazarenkov - a question about how certain functions work.  It is written that `Output Channel may be created by Infrastructure and point to different than Master host`.  What would be the technique for how different output and status channels are sent (or moved) from the Master host to another host?

Is it correct to say that each workspace gets exactly 1 status and output channel?  And do we require that both of those channels communicating to the client are on the same host?

Thanks - the overall spec is rather clear.

**Comment by gazarenkov** [comment]
@TylerJewell 
It is the matter of infrastructure how to provide this physically.
It may provide some proxy server deployed on different than Master computing resource (node, container etc) and may provide it as one per infrastructure or per-workspace.  

Yes, each workspace has exactly 2 channels (which can be the same in simplest case).

We do not say that theirs endpoint must be the same as one provided (by API) to the client.
I suppose in most "hosted" cases (Codenvy) there will be rather internally ONLY accessed channels unlike ones provided by Workspace API to a client. No requirements for client place so.

**Comment by dkulieshov** [comment]
Hi,

If I understand right the way the event status communication is done right now, we have the following picture:
- When we start a workspace runtime, infrastructure is firing/listening to some events through SPI to/from master (programmatically in a single JVM)
- When a workspace runtime has been started, it fires/listens to some events through JSON-RPC to/from master (locally over WebSockets loopback or remotely over WebSockets connection)

So, eventually we have two places where we're looking for event status notifications, this looks a bit too complicated to me as we have to implement two approaches for handling events: the one within the master/infrastructure machine programmatic environment and the other over the JSON-RPC transports. 

What I believe is worth discussing here is the way we can simplify the mentioned problem. I'm wondering if we could shift the master WebSockets endpoint to infrastructure, so we could receive all event statuses on infrastructure level and then pass them in a handy way to a master in a homogenous manner. I see one of the `EventService `implementations as a suitable candidate here.

Summarizing, my suggestion is: infrastructure aggregates events from a workspace runtime/machines, etc., (over WebSockets/JSON-RPC and/or any other custom way, e.g. how it is done for docker) and then it notifies master through the `EventService` or something similar.

**Comment by gazarenkov** [comment]
@dkuleshov 
What you propose is to let Infrastructure perform remote Status Events calls (if any) internally, implementation specific way (like this).

Do I understand you correct?
What about Output messages? 
Thx

**Comment by dkulieshov** [comment]
@gazarenkov 

Yes, absolutely correct. 

Output message, as I think, are well defined so I have nothing to add here at the moment.

**Comment by garagatyi** [comment]
@dkuleshov I'd suggest using some events consumer in SPI instead of usage of EventService. 
It would simplify implementation of SPI if the consumer was in SPI contract. Whereas it is not obvious that EventService which is not included in SPI contract should be used and how it should be used. Also, EventService accepts any event, so to implement infrastructure a developer would have to be very accurate with sending events through it.

**Comment by gorkem** [comment]
How will this play when workspace does not wait for all agents to come online or agents get their own containers? Should there be a new event type so that clients can enable certain functionality as agents come online?

**Comment by TylerJewell** [comment]
The loading specification is still being drafted. I believe that it needs to get further along and then we assess whether there are missing infrastructure events or hooks that need to be added to this specification.

I reviewed a first draft of the loading specification last week. @slemeur - when will you migrate this into a GitHub issue?

https://docs.google.com/document/d/1mkPE4_uffsIfj-N2puBdW57l_1Md5m2JIuqTdhuFShs/edit

**Comment by slemeur** [comment]
I published it here https://github.com/eclipse/che/issues/5231.

We will circulate it and iterate a bit on it still.

**Comment by slemeur** [comment]
@gazarenkov + @dkuleshov : What's the state of this issue ?

**Comment by gazarenkov** [comment]
I consider it as done (long time ago in fact)
@dkuleshov  ?

**Comment by dkulieshov** [comment]
Hi,

Yes, as long as I remember, the work under this issue was indeed finished about a half of a year ago or so.
