### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#5146]
# Goal
The current Eclipse Che version is providing a minimal support of TypeScript. 
The goal of this issue is to provide support of TypeScript by using a langage server which would allow:
- Code Completion
- Errors and syntax highlighting
- Formatting
- Refactoring 
- Code navigation

# Linked issues and discussions
https://github.com/eclipse/che/issues/550
https://github.com/eclipse/che/issues/3741

Important to follow:
- TSServer: https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)
- Work on https://github.com/w0rp/ale/issues/517

**Comment by StevenDoesStuffs** [comment]
So, exactly what's left to be implmented? I've read #550 which says Che already uses https://github.com/sourcegraph/javascript-typescript-langserver, so I'm guessing some of those things on that list are already done. It would be nice to have a checklist.

**Comment by TylerJewell** [comment]
@slemeur - why is this an epic?  Please make sure that there are sub-issues, or just convert this to an enhancement request.

**Comment by slemeur** [comment]
Fixed by: https://github.com/eclipse/che/pull/7079
