### ISSUE TITLE
Define agents configuration file format

### ISSUE THREAD

**Issue by voievodin** [eclipse-che/che#5151]
Agent installer [specification](https://github.com/eclipse/che/issues/4096) (Workflow 7.) says:

7. Machine starts IA and pass path to agents configuration file. It is up to implementation to decide how agents config object is delivered and saved into file in machine.

But specification doesn't define file format, the goal of the issue is to define agents configuration file format and add it to the specification.

**Comment by akorneta** [comment]
Added specification for installer configuration file, [see 2nd item](https://github.com/eclipse/che/issues/4096#issuecomment-283067971)
