### ISSUE TITLE
Using Git Support in Che

### ISSUE THREAD

**Issue by broopdias** [eclipse-che/che#5159]
Is possible to add git support in Che and have inline highlighting of changes?

See image attached
![left-margin](https://cloud.githubusercontent.com/assets/2809478/26319889/bcbb54e8-3f18-11e7-9b12-ba6d81e6052d.png)

**Comment by ghost** [comment]
@slemeur do you plan any git visuals baked in the editor?

**Comment by slemeur** [comment]
We have that specified in the issue https://github.com/eclipse/che/issues/5128

You can check the [latest screen](https://cloud.githubusercontent.com/assets/1636769/26213265/b13531d4-3bf8-11e7-9516-8217c68a6af8.png)

**Comment by ghost** [comment]
@broopdias I will close this issue then. You're welcome to follow https://github.com/eclipse/che/issues/5128
