### ISSUE TITLE
CHE-610 Restarting a workspace with a project results in an attempt to recreate a project

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#516]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-610
Reporter:  Eugene Ivantsov
Description: Steps to reproduce:
1. Create a project from UD.
2. Stop a workspace.
3. Re-run the workspace.
4. There's an error message that project already exists - there's also project api call to import it.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/2740097f08cd9a92903cec46215494ccafd7d1e1
