### ISSUE TITLE
Errors during build of openshift-connector

### ISSUE THREAD

**Issue by humaton** [eclipse-che/che#5160]
**Reproduction Steps:**
Checkout openshift-connector branch
Run build mvn clean install

**OS and version:**  
Fedora 25  

**Diagnostics:** 
build logs on fpaste:
https://paste.fedoraproject.org/paste/8xdGanlJP-2TGLA2TadJEl5M1UNdIGYhyRLivL9gydE=

**Comment by ghost** [comment]
@humaton try using a different branch - https://github.com/eclipse/che/tree/openshift-connector-rebased

**Comment by ibuziuk** [comment]
@humaton you should first build https://github.com/eclipse/che-dependencies from `openshift-connector ` branch. After that try building using some extra flags:
` mvn -Dskip-enforce -Dskip-validate-sources -DskipTests -Dfindbugs.skip -Dgwt.compiler.localWorkers=2 -T 1C clean install`

**Comment by ghost** [comment]
@ibuziuk i don't think it will help. openshift-connector branch depends on 5.6.0-SNAPSHOT which does not exist anymore.

UPD. Yes, a local build helps. But shouldn't rebased branch be used instead?

**Comment by ibuziuk** [comment]
@eivantsov hmmm.... the build works fine for me, but I might just have all required artifacts in local repository
cc: @l0rd

**Comment by ghost** [comment]
Yes, building che-dependencies does make sense since there is not such artifact in a remote maven repo.

**Comment by ibuziuk** [comment]
> UPD. Yes, a local build helps. But shouldn't rebased branch be used instead?


I personally still work with openshift-connector and AFAIK CI jobs also use this branch for building rhche/cheserver images https://hub.docker.com/r/rhche/che-server/

**Comment by ghost** [comment]
Since a custom parent is used, che-deps should be first built locally since https://maven.codenvycorp.com/content/groups/public/ does not have this artifact.

**Comment by humaton** [comment]
Thanks, local build of the dependencies worked.
