### ISSUE TITLE
Add projects section to new  workspace creation page

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5166]
The projects section should contain:
- [x] Add or Import project button (always at the top left corner)
- [x] The list of projects buttons (each button opens popover with project details)
- [x] New project popover should provide ability to choose project sample or import from github/git/zip or create blank project

![image](https://cloud.githubusercontent.com/assets/1611939/26350309/6472fafe-3fbb-11e7-918b-24b14199584f.png)

Add details for github section:
![screen shot 2017-06-16 at 14 46 57](https://user-images.githubusercontent.com/1636769/27227446-c8b3a14e-52a3-11e7-9376-18519275c797.png)

**Comment by slemeur** [comment]
added mockup for the github section
