### ISSUE TITLE
Sync user ssh keys with git in a dev machine

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5169]
Che uses JGit, and there's Git installed in a workspace. These two gits do not share user SSH keys that are stored in user prefs (`/api/preferences`). It becomes quite confusing for users who, having uploaded ssh keys using UI Git, expect these keys to be available for a console git in a terminal.

Proposed solution:

1. When a workspace starts get user keys from `/api/preferences` and inject them in a workspace
2. Let a user choose if or not it should happen on workspace start since this might be a security issue - when a workspace is shared with another user, such a user has access to ssh keys. It may be a check box in user dashboard for example.

**Comment by slemeur** [comment]
link https://github.com/eclipse/che/issues/4969

**Comment by hkolvenbach** [comment]
I understand that this might have security implications, but I think it should be the default to have git working from the command line.

From my understanding most users are also much more familiar with the git command line opposed to the git menu commands.

**Comment by maximilianodendahl** [comment]
is that a duplicate from #3672 from @bmicklea ?

**Comment by ghost** [comment]
@maximilianodendahl yes, I have closed that one as a duplicate.
