### ISSUE TITLE
Improving search results

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5174]
One of the main things we are missing coming from using a desktop IDE (Netbeans in my case) is a search feature that shows line numbers and links to the result in the file.

Please refer to the screenshot below:

![screenshot from 2017-05-23 14-05-52](https://cloud.githubusercontent.com/assets/1720090/26355596/31387794-3fc1-11e7-9427-e31802405bb7.png)

The key features are;

 * Column AND line numbers are shown for matches
 * Multiple matches in the same file are shown individually
 * When you click on a search result, the editor loads the file AND jumps straight to the matching line with all instances of the search term already highlighted

Most of the work I do relies heavily on the ability to quickly find basic strings across a very large project and at the moment I can't work in Che on the project because of this limitation.

Thanks!

**Comment by davidwindell** [comment]
@TylerJewell does closing this issue mean it won't be considered in the epic or..?

**Comment by TylerJewell** [comment]
@davidwindell - I am just bulk closing a lot of older issues right now that are kind/enhancement and then allowing dev teams or other contributors to re-open them if they have a reasonable confidence it will be implemented in the upcoming 6 months or so.  We have a large backlog of enhancement requests and trying to sort out which ones are more wishes that we cannot likely ever get to vs. those that are part of an upcoming dev plan.  The backlog had 600 issues opened at start of the day and it's too big to properly manage, so trimming shears are out!

**Comment by davidwindell** [comment]
@TylerJewell I got pinged on a couple of these. Thanks for the reasoning, I guess I just wanted to check that the "epics" you are leaving open that refer back to my feature requests/issues (you've now closed) will still be considered? Like this one for example.

**Comment by TylerJewell** [comment]
Yeah, the epics are all still valid and all intentions are that dev teams will be assigned to them over the coming year.

**Comment by vparfonov** [comment]
We will work on it soon here https://github.com/eclipse/che/tree/searchwithpossitions

**Comment by davidwindell** [comment]
That's awesome news! Ping @broopdias
