### ISSUE TITLE
Adapt IDE to the new SPI (v6) model 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#5175]
Under this epic will be done several issues around changes in client side related to changes in workspace model such as:
- other behavior on workspace events (it will affect as core IDE part and plugins initialization itself);
- workspace config/runtime changes; 
- server available/unavailable events;
- plugin initialization procedure; 
- switch some services to JSON-RPC    

Related to:
Client-Master-Infrastructure v6 communication #5144

**Comment by TylerJewell** [comment]
@slemeur @vparfonov - please provide the list of issues that make up this epic, add them as checkable boxes, and cross-link to each issue.  Otherwise, this just becomes a `kind/enhancement`.
