### ISSUE TITLE
User does not receive notification after refactoring

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5183]
**Preconditions:**
* Create a workspace with the Spring project. 
* **user#1** should be login into workspace in first browser tab.
* **user#2** should be login into the same workspace in second browser tab.

**Reproduction Steps:**
The users should open the GreetingController class. The **user#2** performs refactoring feature in the editor (set cursor on the class name. Type Shift + F6. Rename the class ). The **user#1** wait notification with message about updating the file.

**Expected result:** The **user#1** should receive notification about updating file. The file should updated in the editor and Project explorer.
 **Actual result:** The file is not updated. There are no any notifications about updating the file

**Additional info:** i've tried to trace the request under websocket. But it looks like there is no messages after refactoring in the related websocket chanel.

**Related selenium test:**  RefactoringFeatureTest.

**OS and version:**  Chrome browser, https://nightly.codenvy-stg.com, server, Ubuntu OS 14.0 TLS

**Comment by RomanNikitenko** [comment]
I've tested it on branch related to https://github.com/eclipse/che/pull/7380

Actual result for user#1 at renaming method of java class is:
- content of the file is up to date

Actual result for user#1 at renaming java class is:
- the file is updated in Project tree
- the editor tab is closed 
- user get notification with message about removing the file with old name.

Actual result for user#1 at moving java class into another package is:
- the file disappears in Project tree, refreshing page resolve the problem 
- the editor tab is closed 
- user get notification with message about removing the file with old name.

**Comment by musienko-maxim** [comment]
Still actual for che5
