### ISSUE TITLE
Opening large file crashes browser

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5189]
Opening (or copying and pasting) a large file into Che will crash the browser tab.

**Reproduction Steps:**
Upload the file below from the AWS SDK into a Che project and try to open it.

https://raw.githubusercontent.com/aws/aws-sdk-php/master/src/data/iam/2010-05-08/api-2.json.php

**OS and version:**    
Eclipse Che 5.10.0

**Comment by ghost** [comment]
@vparfonov should we investigate? Che used to handle big files quite gracefully.

**Comment by davidwindell** [comment]
Still experiencing this in 5.15, also > 2000 lines in a file crashes the browser.

**Comment by davidwindell** [comment]
This is still crashing in 5.19

**Comment by RomanNikitenko** [comment]
I've investigated this bug, cause of the problem is: file has very long lines and originally this is [bug of Orion](https://bugs.eclipse.org/bugs/show_bug.cgi?id=354435)

**Comment by artaleks9** [comment]
Still actual for ver.6.5.0

**Comment by skabashnyuk** [comment]
@vkuznyetsov why you consider this issue as a blocker?

**Comment by vparfonov** [comment]
not actual
