### ISSUE TITLE
In the editor split mode not displayed changes

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5190]
- Go to the spring project
- Open any java class 
- Open context menu on this class editor tab and click on "Split in two column"
- Refresh the page 
- Set cursor on any place in the second column and do some changes
- Pay attention to the screen 

**Expected behavior**
Changes in one window will be shown and in second window too

**Observed behavior**
Changes in one window not displayed in the others

**Attacment**
![anim](https://cloud.githubusercontent.com/assets/22724619/26404129/704dabf6-4099-11e7-9469-66f4af78f612.gif)

**Comment by Ohrimenko1988** [comment]
Related with https://github.com/eclipse/che/issues/5206

**Comment by ghost** [comment]
Cannot reproduce with 5.15-SNAPSHOT. Feel free to reopen though if it persists.

**Comment by RomanNikitenko** [comment]
I still can reproduce it - so reopening the issue

**Comment by ghost** [comment]
I worked for me with non java files. So, yes, it is a legitimate issue

**Comment by ghost** [comment]
@RomanNikitenko suggests that it is a duplicate of https://github.com/eclipse/che/issues/5206 So closing again )
