### ISSUE TITLE
Add hotkey to save changes in the command editor

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#5192]
Need to add a hotkey (Ctrl+S) for saving changes after editing a command.

**Reproduction Steps:**
1. Create some project
2. Go to Commands panel
3. Edit some command
4. For saving we should click on Save button.

**Comment by skabashnyuk** [comment]
@slemeur @vparfonov @svor  do you want to keep this enhancement in backlog?

**Comment by slemeur** [comment]
Closing as won't fix with the future switch to Theia IDE
