### ISSUE TITLE
It is not possible to associate files with a language server at runtime

### ISSUE THREAD

**Issue by iamslite** [eclipse-che/che#5194]
At the moment you can only specify which file extensions relate to which language server when building. It should be possible to specify this at the per-workspace level because the same extension may be used in different ways by different languages and applications.

eg Drupal uses ".module" and ".inc" for PHP files.

**Comment by ghost** [comment]
@iamslite can you be more specific? The title says at runtime, which means after a workspace has started, while you then seems to suggest that this should be configurable per workspace, which makes me think you want to associate files before you start a workspace.

**Comment by ghost** [comment]
And @vparfonov's comment will help here too.

**Comment by vparfonov** [comment]
@iamslite yes for now we can't  change this association in runtime, this is the configuration of our LanguageServiceRegistry. Can you elaborate in details how do you see this ability?

**Comment by iamslite** [comment]
In Eclipse you do this at the project level. For simplicity I said at the workspace level because, as far as I'm aware, the language servers are at the workspace level not the project level. It would logically be something you can change within the running workspace because that is where the user expects it to be  based on other IDEs.

If this can only be done from the external configuration that is fine, so long as it is possible to do it and it is clearly documented. (It obviously isn't ideal, but ....)

Without this, for Drupal work at least, the PHP support might as well be back where Che/Codenvy was over a year ago when a colleague and I were discussing the possibilities with Tyler. Sure you can edit the files but you don't have any of the language specific support you get from other IDEs. I'm sure that other frameworks would have similar issues too.

**Comment by tsmaeder** [comment]
@iamslite is it correct to say that for you it is important that the _user_ can change the association of files to language servers, not necessarily that you can change it on the fly?

**Comment by iamslite** [comment]
It is more important that the user *can* make the change than that they can make it on the fly.

Having it as something which is stored with the workspace configuration would mean that it gets carried over into factories etc. which would be very practical, and there are other changes for which the workspace already needs to be restarted. What we don't really want is for the user to have fiddle about directly with the JSON settings or having to inject a properties file.

**Comment by ghost** [comment]
Closing as won't fix for now.

**Comment by iamslite** [comment]
May I ask why not, and why this has effectively been rejected as a feature long term?

**Comment by ghost** [comment]
Relabeled as enhancement although there are no immediate implementation plans.

**Comment by skabashnyuk** [comment]
@tsmaeder do you want to keep this issue?
