### ISSUE TITLE
Make header of stacks list fixed - not scrollable

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5198]
The introduced stacks widget has the header, which scrolls with the content. It should be fixed on the page.

![image](https://cloud.githubusercontent.com/assets/1611939/26443513/64bc7026-4141-11e7-8878-2a1ad2f0967c.png)

**Comment by slemeur** [comment]
Can we also display the scrollbar "over" the list, instead of next to it? and also hide it, when there is no scrolling?

**Comment by olexii4** [comment]
![selection_054](https://cloud.githubusercontent.com/assets/6310786/26494245/8442ca9a-4226-11e7-8c43-190e77f598d6.png)
![selection_053](https://cloud.githubusercontent.com/assets/6310786/26494247/8724a2ce-4226-11e7-8b74-4bd8e5ebe224.png)
![selection_052](https://cloud.githubusercontent.com/assets/6310786/26494250/897e6c3a-4226-11e7-8704-86beda5d1e57.png)

**Comment by slemeur** [comment]
Nice !

**Comment by olexii4** [comment]
https://github.com/eclipse/che/commit/9063a776206e4d90b9973ab649eb70f57347d5fa

**Comment by ghost** [comment]
Looks like it's fixed - I can see scrollbars in the widget.
