### ISSUE TITLE
Provide "Show Whitespace Characters" functionality for editors

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#5199]
In Eclipse IDE there is a button which provides functionality for showing spaces / tabs in editors. Would be great to have something similar in Che.
![image](https://cloud.githubusercontent.com/assets/1461122/26446795/deea8762-4145-11e7-8680-1d960cc15bf1.png)

**Comment by ghost** [comment]
Profile => Preferences => (IDE) Editor => (White Spaces) Show Whitespace Characters :)

**Comment by ibuziuk** [comment]
oh, thanks for clarification. Closing
