### ISSUE TITLE
"Sharp language server" initialization fails on CHE launched from OS Fedora 25.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#5201]
Steps to reproduce:
1. Run workspace from stack ".NET". 
2. Create project from template "aspnet-web-simple". 
3. Open project.
4. Open file "Program.cs".  After opening this file will begin initialization sharp language server. 

Actual result: sharp launguage server initialization fail with error:
![launguage-server initialization error](https://cloud.githubusercontent.com/assets/6873095/26449507/36f385de-415b-11e7-8faf-0e6ab996a883.png)
And loader didn't hidden.
Main reason of the server error:
![dotnet_restore_fail](https://cloud.githubusercontent.com/assets/6873095/26449569/9b78dbbc-415b-11e7-97f3-637582ef6638.png)

Expected result: sharp language server should initialize successfully. In case server error, IDE should hide loader.

**Comment by AndrienkoAleksandr** [comment]
I investigated this problem and found that we uses in the language server "dotnet" with version 1.0.0-preview2-003121. After updating dotnet to the upper version, f.e "1.0.4" sharp launguage server works fine. Seems main reason this bug command "dotnet restore" : 

https://github.com/dotnet/cli/issues/3681
https://github.com/dotnet/core/issues/172

And this bug was fixed:
https://github.com/dotnet/coreclr/pull/6027

So I propose update Sharp language server to newer version. @eivantsov what do you think?

**Comment by ghost** [comment]
@AndrienkoAleksandr yep, will do that

**Comment by AndrienkoAleksandr** [comment]
@eivantsov thanks. Correct hiding loader will be fixed after merge https://github.com/eclipse/che/pull/5176

**Comment by ghost** [comment]
Having updated dotnet to 1.0.4 csharp language server does not work. There are no errors with `dotnet restore`, however, code completion and other ls features do not work.

**Comment by vrubezhny** [comment]
Any news on fixing this?
Looks like I'm facing this issue. As result, I cannot build/run even a simple c# project on CHE:

```
/bin/bash: line 1:   344 Segmentation fault      (core dumped) dotnet restore
...
/bin/bash: line 1:   361 Segmentation fault      (core dumped) dotnet run
```


```
user@9026fe9b8908:/projects$ dotnet --version
1.0.0-preview2-003121
```

**Comment by AndrienkoAleksandr** [comment]
Related https://github.com/eclipse/che/issues/5385

**Comment by slemeur** [comment]
@vkuznyetsov Could you add that into your upcoming sprint please.

**Comment by TylerJewell** [comment]
It looks like the issue is that the language server is not stable.  We will either need to find a different, stable language server provided by the csharp community, or we may have to consider removing csharp intellisense from the standard distribution.

**Comment by AndrienkoAleksandr** [comment]
Hmm... maybe update LS doesn't fix this problem for Fedora https://github.com/OmniSharp/omnisharp-node-client/issues/398

**Comment by mickaelistria** [comment]
@TylerJewell Despite the hype, language servers remain tricky to implement, OmniSharp is maintained by C# language developers from Microsoft, so I dont think we should place any serious hope in "finding a different one". I think OmniSharp is likely to be the only offering of a LSP-compliant server in the .NET world for a while (and add to this that as opposed to the Java community, the .NET one doesn't usually have multiple projects doing the same thing - mostly for "cultural" reasons).

What we (Red Hat) can try is maybe to provide them more assistance to improve the integration. @AndrienkoAleksandr and myself already do report bugs for our resp. integration with Che and Eclipse IDE, and write some basic patches but if we want to make sure that Omnisharp LS quality meet our expectations, I believe it would require someone to work directly on the OmniSharp code-base for a few months.
In the meantime, OmniSharp folks are doing their job well, it's just that they don't have high resources or high pressure to work on our issues, environments or LSP stuff with highest priority (fair enough).

**Comment by ghost** [comment]
It looks like update to .NET 2.0 fixes this issue.

**Comment by AndrienkoAleksandr** [comment]
Fixed after update C# LS.
