### ISSUE TITLE
'Starting workspace agent' fails + specifying CHE_HOST breaks pre-flight checks

### ISSUE THREAD

**Issue by colemickens** [eclipse-che/che#5204]
I'm running `nginx` in front of Che (runing from Docker).

Che is exposed on `10.0.0.2:8080` and I have nginx with TLS (che.chimera.mickens.io) pointing to 10.0.0.2. Aka, https://che.chimera.mickens.io should point at the running Che instance.

If I configure nothing else, Che appears to run successfully, I can connect to https://che.chimera.mickens.io and start creating a workspace. However, the agent never starts up. Or at least, Che is unable to talk to the workspace agent and so I'm unable to proceed.

From like half a dozen other Issues, it seems that setting `CHE_HOST` would help... but if I edit `che.env` to set `CHE_HOST=che.chimera.mickens.io` then the preflight validation checks fail:

```
[38;5;220mWARN:[0m Bound 'eclipse/che' to 'eclipse/che:5.11.0'
[0;32mINFO:[0m (che cli): 5.11.0 - using docker 17.05.0-ce / native
[38;5;220mWARN:[0m (che cli): 'CHE_HOST=che.chimera.mickens.io' is != discovered IP '10.0.0.2'
[0;32mINFO:[0m 
[0;32mINFO:[0m ---------------------------------------
[0;32mINFO:[0m --------   CONNECTIVITY TEST   --------
[0;32mINFO:[0m ---------------------------------------
[0;32mINFO:[0m (che network): eclipse/che-ip:5.11.0: che.chimera.mickens.io
[0;32mINFO:[0m (che network): Browser => Workspace Agent (localhost): Connection failed
[0;32mINFO:[0m (che network): Browser => Workspace Agent (che.chimera.mickens.io): Connection failed
[0;32mINFO:[0m (che network): Server  => Workspace Agent (External IP): Connection failed
[0;32mINFO:[0m (che network): Server  => Workspace Agent (Internal IP): Connection succeeded
```

This seems overly complicated... There are a non-trivial number of other Issues that are about the same topic, and I don't see any docs on what exact configuration steps are required to make a setup like this work. I've really never had anywhere near this difficulty just putting something behind nginx before. Maybe I'm making a simple basic mistake/assumption...

**Comment by colemickens** [comment]
I'm trying to play with the CHE_SINGLE_PORT stuff now, but not really crazy about having Traefik run as well, just to be able to run through nginx..

How is anyone supposed to use Che today with TLS, or behind a reverse proxy? I can't even figure out how to access it with an SSH tunnel. I really can't tell how anyone is meant to access Che remotely. In other words, I can't figure out how Code Envy is even working right now.

**Comment by ghost** [comment]
@colemickens there are ppl in Che community that successfully run Che behind a reverse proxy. You need to keep in mind one thing - both ws-master and your browsers should be able to reach a workspace agent. You need to make sure your nginx handles the ephemeral port range, since it is used to published exposed ports in a workspace container.

I assume that when you started without any modifications to che.env, ws master started ok, but when you try to open a workspace, you have connection refused in your browser console since nothing is running on `10.0.0.2` on your machine. 

When you set `CHE_HOST` to point to your dns with nginx in front of it, odds are that when ws master tries to ping ws agent, it fails because it does so like this: che.chimera.mickens.io:32763 (just a random port in my example).

A few things that will help me help you

1. A screenshot with dev console opened (standard config)
2. Try starting Che with `--skip:preflight` and see what happens in logs and browser console.
3. Make sure `32768-65535` port range is accessible

**Comment by colemickens** [comment]
@eivantsov Thank you for the very comprehensive reply, it's very much appreciated! I've opened the port range `32768-65535` through my firewall. The preflight check now passes!

However, with and without `CHE_HOST=che.chimera.mickens.io`, I'm still seeing problems. I think it stems from the point here: `You need to make sure your nginx handles the ephemeral port range, since it is used to published exposed ports in a workspace container.`. In theory, that IP resolves to my router, that port range is forwarded to my machine where docker is exposing those ports. But I think the problem is coming from my use of TLS with the che http port. This is the relevant line from Chrome's dev console (There is another exception, but it's a failure to read property of null, presumably stemming from this error):
```
(unknown) Mixed Content: The page at 'https://che.chimera.mickens.io/dashboard/#/ide/che/acs-engine-default' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://che.chimera.mickens.io:32882/api/languageserver/supported'. This request has been blocked; the content must be served over HTTPS.
```

I suspect that I need to get `CHE_API` set properly to use `https` and then I'll also need to get nginx configured to handle that port range. Presumably then things should click.

Sadly, I'm using Kubernetes Ingress to run/configure `nginx` which doesn't support expressing port ranges and I don't plan to enumerate thousands of ports by hand. An alternative might be to use `CHE_SINGLE_PORT` but I'm also using LetsEncrypt and can't get a wildcard TLS cert. This is certainly off-topic, and I'll run through things with a manual nginx config + self-signed TLS cert so I can close this issue, but I'd be curious to hear any alternative approaches given Kubernetes Ingress + LetsEncrypt.

Thanks again.

**Comment by ghost** [comment]
@colemickens yes, single port policy can be a solution. However, I am unaware if someone has tried with https.

**Comment by chungyan5** [comment]
@eivantsov, i am trying to do for https for eclipse che, but i get stuck with the same case of "Colemickens". Now i am setup a openvpn, and works inside VPN network. Finally, i still hope to get work of https which i can skip the open vpn client in my desktop.

**Comment by TylerJewell** [comment]
Have you tried deploying Codenvy yet?  It is free for three users and was tested for ssl so you do not have to make this sort of configuration.

**Comment by ghost** [comment]
Closed due to inactivity.

**Comment by colemickens** [comment]
Sorry, should've closed this sooner.

FWIW, single port worked fine, but a number of things assumed it was HTTP (one of the variables that needed to be overriden for the API endpoint only allows you to specify hostname and then assumes HTTP, not HTTPS). I more or less gave up on getting a good setup, since the port to re-platform on Kubernetes will force a solution to these things. Alternatively, the existing kubernetes-che project might be good, since it has the user run a SPDY proxy as a psuedo-VPN in front.
