### ISSUE TITLE
Workspace is started with not imported project if try to create it from configuration file

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5211]
**Reproduction Steps:**
- Go to dashboard -> "Create workspace" -> "Create from configuration"
- Paste configuration to the field
- Choose "web-java-spring" in the "Ready to run project samples" list
- Click on "Create" button
- Wait until workspace will be started 
- Pay attention to the screen

**Expected behavior**
Project will be created without errors

**Observed behavior**
Workspace is started with not imported project

**Attachment**
![anim](https://cloud.githubusercontent.com/assets/22724619/26494678/83e2e07e-4228-11e7-9f27-1b0f87fef434.gif)

**Comment by ashumilova** [comment]
Will be fixed by workspace creation flow
