### ISSUE TITLE
Workspace config is returned to default value, if try to change it 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5214]
**Reproduction Steps:**
- Go to "Workspaces" -> "Add Workspace" -> "Workspace Config"
- Try to remove current config and paste new
- Pay attention to the screen

**Expected behavior**
Changes will be staying in the field

**Observed behavior**
Pasted config changed to default config. 
If to do the same actions once more, all changes will be saved .    

**Attachment**

![anim](https://cloud.githubusercontent.com/assets/22724619/26496466/4f730eb0-4230-11e7-8f21-5914cf05ae68.gif)

**Comment by ghost** [comment]
Currently, create from config is missing from create a workspace options. Closing the issue since there's no such screen in UD anymore.
