### ISSUE TITLE
Fix Popup for extenal operation file updated.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#5215]
When I have a log file that is open that get changed often too many popup come up. I propose we notify user of external change in another manner or limit repeats of message. 

![image](https://cloud.githubusercontent.com/assets/20580888/26498099/7173ff16-41f3-11e7-90de-487ee6356f9d.png)

codenvy 5.10.0

**Comment by davidwindell** [comment]
+1 this is really annoying at the moment as we run lots of external scripts, logs, etc. A `.cheignore` might also be an idea to ignore entire files/folders from external operations, etc.

We also seem to be having excessive numbers of these "External operation" messages since 5.11.1 but I'll raise another issue for that.

**Comment by marciobrst** [comment]
+1 any solution?

**Comment by Anthony-Janin** [comment]
Hi I've got the same issue but for all files, event Main.java for example, once I open the file and that I add some text, i've got this popup infinitly....

**Comment by asacamano** [comment]
Just upgraded to  5.14 yesterday - and I saw similar behavior creating a new file and editing it.  Is this the same issue?

Steps to reproduce:

1. Create a workspace with an empty project (e.g. Ubuntu workspace, blank project)
1. Create a new file - docker-compose.yml, or edit the README file.
1. Wait for the file to open in the editor.

Result

An (apparently) endless stream of "External Operation: File docker-compose.tml is updated." notifications.

**Comment by davidwindell** [comment]
Yes, this seems to be the same problem. We're stuck on 5.10 until this is resolved.

**Comment by slemeur** [comment]
@vparfonov + @dkuleshov : Could you please check that behaviour. We don't ave an appropriate fix for that. At least #5495 is not fixing this problem.

Updating the status to blocker.

**Comment by dkulieshov** [comment]
Hi, 

As of what I see here I can say:
- @slemeur according to the description of this issue I don't think we can say that https://github.com/eclipse/che/pull/5495 does not fix the problem
- Many thanks to @asacamano who reported a bug, however it seems that it is not quite related to this specific issue so I created another: https://github.com/eclipse/che/issues/5515
- I also created an issue to improve general external operation notifications behavior: https://github.com/eclipse/che/issues/5514
