### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5220]
Che seems not to have support for Markdown and I find it tricky sometimes to work with Markdown without live preview.

Having some basic functionality like syntax highlighting for Markdown would be nice. There's a readily-available Language Server for Markdown in VS Code if I remember

**Comment by TylerJewell** [comment]
Cross-linking - https://github.com/eclipse/che/issues/3932

**Comment by kaloyan-raev** [comment]
Have you considered the Orion's markdown editor?
http://planetorion.org/news/2014/07/orions-new-markdown-editor/
