### ISSUE TITLE
No visual effect when choose project in the github projects list

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5222]
**Reproduction Steps:**
- Go to "Dashboard" -> "Import from existing location"' -> "GitHub"
- Try to choose any repository
- Pay attention to the screen

**Expected result**
After choosing project, selection will be shown by some visual effects

**Observed behavior**
Selection is not displayed
    
**Attachment**
![anim](https://cloud.githubusercontent.com/assets/22724619/26545162/3f8fe560-446d-11e7-87a6-a47ad13db9d6.gif)

**Comment by ghost** [comment]
Closing the issue as UD has an entirely new workspace+project creation flow.
