### ISSUE TITLE
URL for zip import will be changed if select some stack

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5223]
**Reproduction Steps:**
- Go to "Dashboard" -> "Import from existing location" -> "Zip"
- Fill the "Zip URL" field by some URL
- Choose some stack 
- Pay attention to the "Zip URL" field 

**Expected behavior**
Value in "Zip URL" will be saved after choose some another stack 

**Observed behavior**
Value is changed 

**Attachment**
![anim](https://cloud.githubusercontent.com/assets/22724619/26548019/9e218e64-447a-11e7-9bc4-c27314206f8d.gif)

**Comment by ghost** [comment]
The issue cannot be reproduced in the new UD flow when creating a workspace.
