### ISSUE TITLE
URL for zip file importing can be without "zip" extension

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5224]
**Reproduction Steps:**
- Go to "Dashboard" -> "Import from existing location" -> "Zip"
- In the "Zip URL" field, try input address without "zip" extension
- Pay attention to result

**Expected behavior**
Some error message will be shown and "Create" button will be not active

**Observed behavior**
Error message not displayed and "Create" button is active

**Attachment**
![anim](https://cloud.githubusercontent.com/assets/22724619/26548543/62bee508-447d-11e7-8b05-30a4621298b8.gif)

**Comment by gmcouto** [comment]
I don't think this should be a defect. URLs don't need to have extension to deliver the goods.

**Comment by gazarenkov** [comment]
Not a bug
