### ISSUE TITLE
Sometimes Java debugger doesn't highlight current position in decompiled class

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#5236]
**Reproduction Steps:**
1. Create a workspace from `codenvy/jboss-eap7` image.
2. Clone sample kitchen sink project: `https://github.com/codenvy-templates/redhat-kitchensink-webapp.git`
3. Run JBoss in debug mode, compile and deploy the project.
4. Open `MemberController`, and set breakpoints on line:
```
facesContext.addMessage(null, m);
```
5. Connect debugger.
6. Open the application and register a user.
7. When the debugger stops on the first breakpoint use step into.

**Expected behavior:** Current debugger position should be highlighted.
**Actual behavior:** Partially decompiled class is opened, but no highlight is shown.
![screenshot from 2017-05-30 15-18-12](https://cloud.githubusercontent.com/assets/15607393/26582842/419bf9fa-454b-11e7-8d8b-75fe8869dd04.png)

**Comment by mmorhun** [comment]
May be related to https://github.com/eclipse/che/issues/5113

**Comment by musienko-maxim** [comment]
Depended selenium test: DebugExternalClassTest
