### ISSUE TITLE
Change title of tab

### ISSUE THREAD

**Issue by vnea** [eclipse-che/che#5239]
Hello,

I'm currently trying to change the title of a tab (CHE 5.10.0).

I have for example this project:
![image](https://cloud.githubusercontent.com/assets/10775422/26594186/fa4c600a-4566-11e7-8d56-1e4c1ee010f2.png)
and when I open the file **README**, I got this:
![image](https://cloud.githubusercontent.com/assets/10775422/26594192/06e1cefe-4567-11e7-82ea-e8d75c61e5c7.png)

Is there a simple way to change the title of the tab without modifying the existing CHE source code, with an extension for example ?

**Comment by vzhukovs** [comment]
Hi, @vnea! You can create an implementation of `org.eclipse.che.ide.api.resources.ResourceInterceptor` for this purpose.

See example:
```java
import com.google.inject.Singleton;

import org.eclipse.che.ide.api.resources.Resource;
import org.eclipse.che.ide.api.resources.ResourceInterceptor;
import org.eclipse.che.ide.api.resources.marker.PresentableTextMarker;

@Singleton
public class CustomResourceInterceptor implements ResourceInterceptor {

    public static final String README = "README";

    @Override
    public void intercept(Resource resource) {

        // or by specific path resource.getLocation().equals(Path.valueOf("/ChangeTabTitle/README"))

        if (resource.isFile() && README.equals(resource.getName())) {
            resource.addMarker(new PresentableTextMarker("custom_title"));
        }
    }
}
```

Then register this interceptor in your gin module:
```java
@ExtensionGinModule
public class MavenGinModule extends AbstractGinModule {

    @Override
    protected void configure() {
        // ...
        GinMultibinder.newSetBinder(binder(), ResourceInterceptor.class).addBinding().to(CustomResourceInterceptor.class);
        // ...
    }
}

```

And you'll have smth like that:
![eclipse che](https://cloud.githubusercontent.com/assets/1968177/26621270/e2caba52-45ee-11e7-90a4-2e7ed84e4212.png)

**Comment by vnea** [comment]
@vzhukovskii Thank it works perfectly !
