### ISSUE TITLE
Ready-to-go stack node wrong metadata/info v0.12

### ISSUE THREAD

**Issue by elonmallin** [eclipse-che/che#5242]
The ready-to-go stack for node says that it's version v0.12 but it's actually v7.7.3. The info wherever it is should be updated to reflect this.
![image](https://cloud.githubusercontent.com/assets/9149793/26605757/819752cc-458f-11e7-8193-c4b90c4a2ad0.png)

**Comment by elonmallin** [comment]
Well, tried to contribute but just jumping through hoops with endless sign up to eclipse and sign ECA and read the guidelines etc and in the end ip-validation check fails for the ECA validation and I think this issue is supposed to be verified before any pull requests are made etc.

Hopefully it goes through anyway, cheers.

**Comment by TylerJewell** [comment]
The CLA process with Eclipse and GitHub is a bit buggy. Our committers and maintainers are allowed to look up a hidden registry of email addresses for those people who have signed the CLA, and then they are allowed to make a merge if they can verify the email.

**Comment by elonmallin** [comment]
Okey, I signed up to eclipse with the same email as my github so hopefully that should work. The commit should just be a simple version update in hardcoded json so I guess it should be quite safe.

**Comment by ghost** [comment]
@elonmallin will you issue a PR or should I do it?

**Comment by elonmallin** [comment]
Sorry, what do you mean? I already created a PR https://github.com/eclipse/che/pull/5243 it is linked to this issue right?

**Comment by ghost** [comment]
Sorry, my bad. Didn't notice it.

**Comment by ghost** [comment]
Merged. Closing the issue.
