### ISSUE TITLE
Factory creation from dashboard works wrong

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5246]
**Reproduction Steps:**
1. Create a workspace with the Spring project.
2. Dashboard ->Factory ->Create factory->Select just created workspace. 

**Expected result:** the factory should be created
**Actual result:** we have **Create factory failed** message. **More details:** after POST request for creation of the factory we have HTTP response from server with 415 code and next error message: ```Media type multipart/form-data;boundary=----WebKitFormBoundaryvbYudw59o8KDYd06 is not supported```

**OS and version:**   Chrome browser, Ubuntu 14.0 TLS, Che version: 5.12.0-SNAPSHOT,  server location: nightly.codenvy-stg.com

**Comment by mkuznyetsov** [comment]
fixed by https://github.com/eclipse/che/pull/5249
