### ISSUE TITLE
When I download the che for offline on Mac, it continue failed on che-action

### ISSUE THREAD

**Issue by Anne369** [eclipse-che/che#5247]
Always failed to download che-action
INFO: (che offline): Saving /projects/che/backup/eclipse_che-action:5.11.2.tar...
Error response from daemon: reference does not exist
ERROR: Docker was interrupted while saving /data/backup/eclipse_che-action:5.11.2.tar

**Reproduction Steps:**
docker run -it  --rm -v /var/run/docker.sock:/var/run/docker.sock -v /projects/che/data:/data -v /projects/che/instance:/data/instance -v /projects/che/backup:/data/backup  eclipse/che:5.11.2 offline
**OS and version:**    
MacOS
**Diagnostics:** 
docker run -it  --rm -v /var/run/docker.sock:/var/run/docker.sock -v /projects/che/data:/data -v /projects/che/instance:/data/instance -v /projects/che/backup:/data/backup  eclipse/che:5.11.2 offline

**Comment by ghost** [comment]
Bug confirmed. Some utility images do not get pulled.

**Comment by ghost** [comment]
As a workaround:

`sudo rm -rf  /projects/che/backup `
`docker pull eclipse/che-action:5.11.2 eclipse/che-dir:5.11.2 eclipse/che-test:5.11.2 eclipse/che-mount:5.11.2`
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /projects/che/data:/data eclipse/che:5.11.2 offline`

**Comment by riuvshin** [comment]
hey, @Anne369 thanks for reporting this bug, it should be fixed by: https://github.com/eclipse/che/pull/5263
