### ISSUE TITLE
debugging golang with gdb - cannot connect to localhost:8080

### ISSUE THREAD

**Issue by JCzz** [eclipse-che/che#5254]
**Reproduction Steps:**

1. Running Che with the following docker run:
docker run -it --privileged --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(PWD):/data eclipse/che:latest start

2. Create Workspace; selecting go stack with web-go-simple

3. install gdb:
sudo apt-get update
sudo apt-get install gdb

4. In the Che editor menu: "Run / Edit Debug Configuration"
5. Select the "gdb/ remote gdb" with port 8080.
6. Press "Debug"

Error message: "Can not connect to: localhost:8080."

**OS and version:**    
Mac 10.12.3
Docker version: 17.03.1-ce

**Comment by ghost** [comment]
@JCzz first off, you should start your workspaces in a privileged mode. In your che.env file, look for `PRIVILEGED` and set it to true.

Secondly, you should start gdbserver on port 8080, and then connect debugger to it.

Lastly, I do not think Che supports golang debugger with current gdb implementation.

**Comment by JCzz** [comment]
I am not sure what you mean, but I have --privileged in step 1. ?

**Comment by JCzz** [comment]
Can you describe what you do to start the gdbserver?

**Comment by ghost** [comment]
This was you run CLI container in a privileged mode.

As to debugging golag, it is not supported right now in Eclipse Che.

**Comment by JCzz** [comment]
Ok, thank you for the information. Looking forward to hawing go onboard a some point :-)
