### ISSUE TITLE
Add machine page to workspace details

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5259]
Mock-up of the machines page inside workspace details:

![screen shot 2017-07-03 at 09 43 42](https://user-images.githubusercontent.com/1611939/27782833-c7f29b5c-5fdc-11e7-83c1-4f2125f35f71.png)

**Comment by olexii4** [comment]
1. Delete bulk operation.
![selection_065](https://user-images.githubusercontent.com/6310786/28064508-9cf473b4-663d-11e7-9a2d-8cb60c0bade6.png)
2. Edit dockerfile machine recipe.
![selection_064](https://user-images.githubusercontent.com/6310786/28064512-a487a6e6-663d-11e7-9941-279eb410db13.png)
3. In the case without changes.
![selection_063](https://user-images.githubusercontent.com/6310786/28064517-a9da6728-663d-11e7-964d-296556befd05.png)
4. Machine list in the case with dockerfile.
![selection_062](https://user-images.githubusercontent.com/6310786/28064524-b0890fe8-663d-11e7-9a3b-920ddc49b534.png)
5. When clicking on DEV switch for DEV-machine.
![selection_061](https://user-images.githubusercontent.com/6310786/28064533-b5616650-663d-11e7-8130-f53df727aeeb.png)
6. Compose file validation.
![selection_060](https://user-images.githubusercontent.com/6310786/28064548-c83fe6f2-663d-11e7-9ea1-82e69589eee7.png)
7. Catch parse errors.
![selection_059](https://user-images.githubusercontent.com/6310786/28064558-d1917360-663d-11e7-9065-04b800a7be2b.png)
8. After a valid change.
![selection_058](https://user-images.githubusercontent.com/6310786/28064563-d799b434-663d-11e7-8a47-a010cc299433.png)

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/5451/commits/0747ce8eb0432cfdf93bc707e909e42b1b745f43
