### ISSUE TITLE
Assembly Dev Lifecycle - Production Mode (Windows 10)

### ISSUE THREAD

**Issue by vnea** [eclipse-che/che#5264]
Hello,

I tried to deploy a custom **CHE 5.10.0** binaries in production mode following this [guide](https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#production-mode).

As it is said in the guide, I created a folder **dockerfiles** with the following folders/files in my CHE assembly repo (taken from [here](https://github.com/codenvy/plugin-openshift/tree/master/dockerfiles)):
![image](https://cloud.githubusercontent.com/assets/10775422/26682888/4d96f2d0-46e2-11e7-86cd-da914b0e6100.png)

I then executed the **build.sh** script in each folder but each time I got this error:

> Building Docker Image .../...-cli:nightly from /c/Users/.../dockerfiles/cli directory with tag nightly
> time="2017-06-01T15:53:08+02:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
> **unable to prepare context: unable to evaluate symlinks in Dockerfile path: GetFileAttributesEx C:\c: Le fichier spécifié est introuvable. (=The system cannot find the file specified.**)
> Build of .../...cli:nightly [OK]
> Script run successfully: .../...-cli:nightly

I use **Windows 10** and I run the **build.sh** scripts with **Docker Quickstart Terminal** (=Docker Toolbox).

It seems like other people have a [similar same problem](https://stackoverflow.com/questions/35511604/docker-unable-to-prepare-context-unable-to-evaluate-symlinks-in-dockerfile-pat) but I checked and there is not the **.txt** extension in the filenames of the **Dockerfile** files.

**Comment by TylerJewell** [comment]
Hi ... what happens if you run the scripts without the Docker Quickstart Terminal?  The particular scripts that you are running were tested on Windows systems that have git bash installed - we never use the quickstart terminal.

**Comment by ghost** [comment]
I'll give it a shot on Win 10. Custom cli build was extensively tested on Linux.

**Comment by vnea** [comment]
With Git Bash:

> Building Docker Image .../...-cli:nightly from /c/Users/.../dockerfiles/cli directory with tag nightly
> error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.26/build?bui                                                                                                                                   ldargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&                                                                                                                                   cpusetmems=&cpushares=0&dockerfile=.Dockerfile&labels=%7B%7D&memory=0&memswap=0&                                                                                                                                   networkmode=default&rm=1&shmsize=0&t=convertigo%2Fconvertigo-che-cli%3Anightly&u                                                                                                                                   limits=null: open //./pipe/docker_engine: Le fichier spécifié est introuvable. (=The system cannot find the file specified.) I                                                                                                                                   n the default daemon configuration on Windows, the docker client must be run ele                                                                                                                                   vated to connect. This error may also indicate that the docker daemon is not run                                                                                                                                   ning.
> Build of .../...-cli:nightly [OK]
> Script run successfully: .../...-cli:nightly

**Comment by ghost** [comment]
Looks like docker in unavailable from that shell. Can you run `docker ps` there? I think you need to export some must have envs for docker toolbox.

**Comment by vnea** [comment]
@eivantsov Yes, that's why I always use **Docker Quickstart Terminal**.

**Comment by vnea** [comment]
By the way you can close this issue if you want, I now build the custom assembly with Travis.

**Comment by TylerJewell** [comment]
Thanks, @vnea
