### ISSUE TITLE
Allow removing the SVN support by simply removing the Subversion plugins from the assembly

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#5271]
Currently, the The `SubversionCredentialsDialog` interface is injected into the standard project wizard (through constructor), to be used by the  Subversion support. When the Subversion plugins are removed from a customized assembly, the GWT build fails in `assembly-ide-war`, because no `SubversionCredentialsDialog` implementation is found to be injected into the project wizard class.

We should remove this requirement, to allow dropping the Suversion support in customized assemblies more easily.

**Comment by sunix** [comment]
done with https://github.com/eclipse/che/pull/4490
