### ISSUE TITLE
Workspace Config, minimum memory limit for a machine

### ISSUE THREAD

**Issue by vnea** [eclipse-che/che#5273]
Hello,

When creating a workspace, we can defined all the machines we want.
For a **mysql** machine, I will have somehing like that:
```
...
"mysql": {
   "attributes": {
       "memoryLimitBytes": 1073741824
   }
}
...
```
But for a **mysql** machine, 1 GB of memory is too much.
However it is not possible to put less memory...

Will you change this limit ?

**Comment by ghost** [comment]
@vnea server side imposes no limits. This is a User Dashboard limitation.

To create a workspace with this config, you may go to `/swagger/#!/workspace/create` or use cURL or any other tool/client.

**Comment by vnea** [comment]
So if I define a machine in a stack directly in the [ide/che-core-ide-stacks/src/main/resources/stacks.json](https://github.com/convertigo/convertigo-che-assembly/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json) file with a **memoryLimitBytes** less than  1GB, will it work ?

I guess the answer is yes but I want to be sure.

**Comment by ghost** [comment]
@vnea I am not sure how Dashboard reacts. Definitely worth trying.

**Comment by vnea** [comment]
@eivantsov I'll try it now.

**Comment by vnea** [comment]
I tried to put in the custom [stack.json](https://github.com/convertigo/convertigo-che-assembly/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json):
```
"attributes":{
    "memoryLimitBytes":"900000000" // 0.9 GB
 }
```
As you can see below, the Dashboard block the creation of the workspace.
![image](https://user-images.githubusercontent.com/10775422/26933208-28cf9f9a-4c66-11e7-82ea-f45e6751a9b6.png)

> To create a workspace with this config, you may go to /swagger/#!/workspace/create or use cURL or any other tool/client.
It's a nice idea but I don't want the future users to create the worskpace like that.

It would be very nice if the Dashboard limits is removed/decreased.
It seems like the server side imposes a min limit of 4 MB.

Thank you.

EDIT: If needed, you can close the issue.

**Comment by ghost** [comment]
@vnea I do not think server side imposes any limits. It's just Dashboard. I have already labeled this issue as improvement and assigned a team to it.
