### ISSUE TITLE
The File Structure widget does not close after pressing Esc button

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5274]
**Reproduction Steps:**

1. Create and start a workspace with the **web-java-spring** project .
2. Open the **GreetingController.java** file in the Editor.
3. Press **Ctr+F12**. The **File Structure** widget appeared.
4. Press **Ctr+F12** again and then press **Esc** button to close the widget.

**Expected behavior:**
The File Structure widget closed.

**Observed behavior:**
The **File Structure** widget  didn't close. This bug happens only once when open a java file after starting a workspace or refreshing a page. 
This bug was reproduced by **FileStructureBaseOperationTest**.

**Che version:** 5.12.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://cloud.githubusercontent.com/assets/7760565/26730841/ed571498-47ba-11e7-9d28-acd473845e23.gif)

**Comment by ghost** [comment]
The widget loses focus indeed.
