### ISSUE TITLE
Adding a fullscreen graphical UI editor

### ISSUE THREAD

**Issue by chenthillrulz** [eclipse-che/che#5279]
We are trying to create a graphical UI editor which should run in a che workspace. It would be developed as an angular 4 app.  The need is to show it in fullscreen (hiding main menu, partstack's such as NAVIGATION, INFORMATION, EDITING, TOOLING etc.). The angular app would use the REST api's to communicate with the workspace.

Is it possible to add a custom route to the work-space and show the app similar to che dashboard ? 
Is it possible to write a ide plugin for this use case ?

There are some options which we have been thinking about,
1) Add a custom route to existing work-space and show the GUI editor angular app. (not sure if its feasible)
2) Run the angular app under another web server inside the workspace.
3) Add the app in a custom route on che server similar to dashboard app.

It would be nice to know a recommendation for this use case. tia!!

**Comment by ghost** [comment]
@chenthillrulz unfortunately, there's no such existing plugins or custom Che assemblies that we are aware of.

Smth that may help you: the IDE is loaded in an iframe. So, you are always on a Dashboard page, and workspaces are loaded in it.

Some Che assemblies did run webservers in workspaces to server content displayed in the IDE parts (not a fullscreen custom editor view as in your case) https://github.com/codenvy-legacy/artik/blob/master/plugins/plugin-artik-ide/src/main/java/org/eclipse/che/plugin/artik/ide/apidocs/DocsPartPresenter.java
