### ISSUE TITLE
How to extend edtior to support syntax error checking on new language

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5280]
For Orion, it allow register service to show syntax errors in editor, does Che provide similar api? And is there any example/guide on how to extend Editor to support syntax validating(show syntax error in editor)?

**Comment by ghost** [comment]
@m7luffy Che uses Orion with all the features that are available in Orion out of the box.

As to examples, you may want to take a look at the following docs: https://www.eclipse.org/che/docs/assemblies/sdk-code-editors/index.html

**Comment by qi-min** [comment]
@eivantsov I go through this editor doc, it provides example for syntax highlight and code completion. But it does not mention how to implement syntax error checking in editor for my own language.

The extension to Orion is js based. But seems Che need Java in plugin to communicate with Orion. So if there is any example about how to implement this function will be helpful.

**Comment by ghost** [comment]
You can implement code validation in a language server. This is how it works for json or C# files for example.

Docs: https://www.eclipse.org/che/docs/assemblies/sdk-language-server-protocol/index.html

**Comment by qi-min** [comment]
@eivantsov Is there code or guide on how to setup a language server and interact with Editor? The link above focus on the agent, but does not provide instruction about how to implement the validation in language server and how to return the result to Editor.
What I need to do is show warnings/errors in a Editor for a language, just like Json editor.
<img width="386" alt="screen shot 2017-06-26 at 3 40 09 pm" src="https://user-images.githubusercontent.com/10006307/27529265-66586ae4-5a86-11e7-809f-e134289d5d36.png">

I do not see any network traffic between the browser and server when validation happens on Json. So I am not sure how Che implement the validation on Json.

For Orion, it define the methods to compute the errors and return to editor in a Json format, is there any code in Che do the similar things?
https://wiki.eclipse.org/Orion/Documentation/Developer_Guide/Plugging_into_the_editor#orion.edit.validator
```
provider.registerServiceProvider("orion.edit.validator", {
        computeProblems: function(editorContext, options) {
                var problems = [];
                return editorContext.getText().then(function(contents) {
                        var lines = contents.split(/\r?\n/);
                        for (var i=0; i < lines.length; i++) {
                                var line = lines[i];
                                var match = /\t \t| \t /.exec(line);
                                if (!match) {
                                    continue;
                                }
                                problems.push({
                                        description: "Mixed spaces and tabs.",
                                        line: i + 1,
                                        start: match.index + 1,
                                        end: match.index + match[0].length + 1,
                                        severity: "warning"
                                });
                        }
                        var result = { problems: problems };
                        return result;
                });
        }
```

**Comment by ghost** [comment]
@dkuleshov @evidolob any pointers here? Thanks

**Comment by ghost** [comment]
@m7luffy are you willing to provide syntax validation though own language server?

**Comment by eivantsov** [comment]
Closed due to inactivity
