### ISSUE TITLE
close file issue

### ISSUE THREAD

**Issue by ahmedchemek** [eclipse-che/che#5286]
Hello, I added a new type of editor to Che, the problem is when I want to close the editor just the view disappears but the Head that contains the name of the file remains open. this is the close method in the Presenter :
public void close(final boolean save) {
view.setVisible(false); 
partStack.removePart(this);
}

**Comment by ghost** [comment]
@vzhukovskii can you assist please?

**Comment by vzhukovs** [comment]
Hello @ahmedchemek! You should inject into your component `org.eclipse.che.ide.api.editor.EditorAgent` and call `org.eclipse.che.ide.api.editor.EditorAgent#closeEditor` then your tab with editor will be completely closed.

**Comment by ahmedchemek** [comment]
Hi @vzhukovskii !!
 I injected org.eclipse.che.ide.api.editor.EditorAgent in my Presenter
and in the methode close i added :
public void close(final boolean save) {
view.setVisible(false);
partStack.removePart(this);
editorAgent.closeEditor(this);
}
but i have the same result

**Comment by vzhukovs** [comment]
You don't need to modify the method `public void close(final boolean save)`. Just when you want to close programmatically your custom editor you should call only `editorAgent.closeEditor(editorPresenterToClose);`

**Comment by TylerJewell** [comment]
@ahmedchemek - please be mindful that this is a public forum for the entire community. We need to remove the perception of emotion from the discussions so that we can help you effectively.  So, there is no need to use exclamation (!!) marks or bold. Just plain, simple English will be ok.

**Comment by ahmedchemek** [comment]
@TylerJewell ok sorry.
@vzhukovskii where i should write editorAgent.closeEditor(editorPresenterToClose); ?

**Comment by ahmedchemek** [comment]
@eivantsov when executing close,
i have this in the console:
`com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'c0' of nul`l

**Comment by ghost** [comment]
@ahmedchemek this exception can be ignored. It is unrelated.

**Comment by vzhukovs** [comment]
@ahmedchemek in any place where you want to close editor programmatically.

**Comment by ahmedchemek** [comment]
@vzhukovskii i writed it in the close method but always not working

**Comment by ghost** [comment]
@ahmedchemek is this still an issue?

**Comment by ghost** [comment]
@ahmedchemek I am closing the issue. Feel free to reopen if the problem persists.
