### ISSUE TITLE
Custom stack for a custom assembly

### ISSUE THREAD

**Issue by vnea** [eclipse-che/che#5287]
Hello,

I want to have a custom stack for a custom CHE assembly.

For the moment I have just tried to remove all defined Stacks and only keep the **Default Java Stack with JDK 8, Maven and Tomcat**. Later, I will define my own Stack and only keep this one.

I tried to do what was done [here](https://github.com/codenvy/redhat/tree/master/ide) but without success.
The source code of my custom CHE assembly can be found [here](https://github.com/convertigo/convertigo-che-assembly).

Can you please give more details on how to do it ?

**Comment by gorkem** [comment]
Can you elaborate, what exactly did not work?

**Comment by ghost** [comment]
@vnea @gorkem since database is already populated, changing stacks.json will bring just changes to an existing set of stacks.

I think flushing a database (removing db files) and restarting Che should do the trick.

**Comment by vnea** [comment]
@gorkem 
First of all, I created the Maven modules **convertigo-che-assembly/ide** and **convertigo-che-assembly/ide/che-core-ide-stacks** with the following pom.xml files:
- **convertigo-che-assembly/ide** [pom.xml](https://github.com/convertigo/convertigo-che-assembly/blob/master/ide/pom.xml)
- **convertigo-che-assembly/ide/che-core-ide-stacks** [pom.xml](https://github.com/convertigo/convertigo-che-assembly/blob/master/ide/che-core-ide-stacks/pom.xml) (especially look at the line 17 (`<executions>`) and the line 36 (`<plugin>`)

Then I created the [convertigo-che-assembly/ide/che-core-ide-stacks/src/resouces/stack.json](https://github.com/convertigo/convertigo-che-assembly/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json) file which only contains the **Java** stack.
I also created the [convertigo-che-assembly/ide/che-core-ide-stacks/src/assembly/assembly.xml](https://github.com/convertigo/convertigo-che-assembly/blob/master/ide/che-core-ide-stacks/src/assembly/assembly.xml) file.

Afterwards, I defined the dependecy in the root [convertigo-che-assembly/pom.xml](https://github.com/convertigo/convertigo-che-assembly/blob/master/pom.xml)
```xml
<dependency> // Line 84
    <groupId>com.twinsoft.convertigo</groupId>
    <artifactId>che-core-ide-stacks</artifactId>
    <version>${project.version}</version>
</dependency>
```
and also the **convertigo-che-assembly/ide** Maven module:
```xml
</modules>
    //...
    <module>ide</module> // Line 174
 </modules>
```

Next I added the dependency in the [convertigo-che-assembly/assembly-che/assembly-main/pom.xml](https://github.com/convertigo/convertigo-che-assembly/blob/master/assembly-che/assembly-main/pom.xml):
```xml
<dependency> // Line 27
    <groupId>com.twinsoft.convertigo</groupId>
    <artifactId>che-core-ide-stacks</artifactId>
</dependency>
```
In the [convertigo-che-assembly/assembly-che/assembly-main/src/assembly/assembly.xml](https://github.com/convertigo/convertigo-che-assembly/blob/master/assembly-che/assembly-main/src/assembly/assembly.xml) file, I added the entries:

-  **dependencySet**

```xml
<dependencySet> // Line 27
    <useProjectArtifact>false</useProjectArtifact>
    <unpack>true</unpack>
    <outputDirectory>stacks</outputDirectory>
    <includes>
        <include>com.twinsoft.convertigo:che-core-ide-stacks</include>
    </includes>
    <unpackOptions>
        <excludes>
            <exclude>META-INF/**</exclude>
        </excludes>
    </unpackOptions>
</dependencySet>
```

- **fileSets**

```xml
<fileSets> // Line 43
    <fileSet>
        <directory>${project.build.directory}/dependency/eclipse-che-${che.version}</directory>
        <outputDirectory></outputDirectory>
        <excludes>
            <exclude>**/tomcat/webapps/ROOT.war</exclude>
            <exclude>**/stacks/**</exclude> // I ADDED THIS EXCLUDE ENTRY
        </excludes>
    </fileSet>
</fileSets>
```
Finally I built and started CHE but I still had all stacks:
![image](https://user-images.githubusercontent.com/10775422/26921351-13b13d0a-4c3c-11e7-8cbd-5742812d6385.png)

However I excepted to have this:
![image](https://user-images.githubusercontent.com/10775422/26921413-41219280-4c3c-11e7-9d59-3b1a6f492943.png)


As there were no tutorial, I inspected the [Codenvy-Redhat CHE assembly](https://github.com/codenvy/redhat/tree/master/ide) repository and tried to do the same thing.
So maybe I did something wrong or missed something.

**Comment by vnea** [comment]
@eivantsov
>  I think flushing a database (removing db files) and restarting Che should do the trick.

By removing db files do you mean the db files from the browser ?
![image](https://user-images.githubusercontent.com/10775422/26921744-3bbb5ac8-4c3d-11e7-9ec9-3070c0716d37.png)
If yes I tried to flush it but I still got the same result (**Google Chrome 58**).

**Comment by ghost** [comment]
@vnea from your local storage - `/instance/data/db/che.mv.db` It will flush the entire database though.

FYI, we are working on a better mechanism of handling stacks.  One part of it is already implemented - stacks.json will be used as a source for database only once.

**Comment by vnea** [comment]
I removed the **/instance/data/db/che.mv.db** file and when I re-started CHE, the **docker 
logs -f che** command displayed this error:

> 2017-06-08 12:28:16,174[ost-startStop-1]  [ERROR] [o.e.c.a.w.s.stack.StackLoader 80]    - Failed to store stacks
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 144 column 4 path $[1].stackIcon
>...
and there were no stack in the list when creating the workspace.

Then deleted the **che-data/** folder (the one which contains the **instance/** folder) and it worked perfectly !

@eivantsov Thank you again for your support, it's really great ! :)
