### ISSUE TITLE
MVN clean install fails on Mac

### ISSUE THREAD

**Issue by ronnielking** [eclipse-che/che#529]
Hi, I'm seeing a build/test failure on mac. I just cloned the repo, ran mvn clean install, and after some time I get an error on "Git Impl Native":

[INFO] Che Core :: IDE :: STACKS .......................... SUCCESS [  0.081 s]
[INFO] Che Core :: Git Impl Native ........................ FAILURE [ 43.920 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:00 min
[INFO] Finished at: 2016-02-25T14:05:46-06:00
[INFO] Final Memory: 154M/1389M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project che-core-git-impl-native: There are test failures.

I am using the Oracle JDK 1.8 build 60 and Maven 3.3.3. 

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T06:57:37-05:00)
Maven home: /usr/local/apache-maven-3.3.3
Java version: 1.8.0_73, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre

Any thoughts?

**Comment by TylerJewell** [comment]
@ronnielking Sorry, this is a temporary issue that our build is failing on Windows and Macs right now due to a merge.

You can work around this - go into `/assembly/assembly-main` directory.  Run `mvn clean install` here.  This is the final stage in building and creates an assembly from compiled binaries hosted in Che's nexus repository.

**Comment by ronnielking** [comment]
That worked, thanks for the quick turn Tyler!

**Comment by skabashnyuk** [comment]
@ronnielking master works ok on mac. Can you provide more details?

**Comment by ddementieva** [comment]
@ronnielking any update on this?

**Comment by dhuebner** [comment]
@ddementieva Still failing on mac 4.1.0RC1
The most test cases are failing with the java.lang.ArrayIndexOutOfBoundsException: 2

---

##  T E S T S

Running TestSuite
Configuring TestNG with: TestNG652Configurator
Tests run: 94, Failures: 76, Errors: 0, Skipped: 0, Time elapsed: 57.522 sec <<< FAILURE! - in TestSuite
testAddUpdate(org.eclipse.che.git.impl.AddTest)  Time elapsed: 0.84 sec  <<< FAILURE!
java.lang.ArrayIndexOutOfBoundsException: 2
    at org.eclipse.che.git.impl.nativegit.commands.LogCommand.execute(LogCommand.java:56)
    at org.eclipse.che.git.impl.nativegit.NativeGitConnection.commit(NativeGitConnection.java:316)
    at org.eclipse.che.git.impl.AddTest.testAddUpdate(AddTest.java:88)

testSimpleAdd(org.eclipse.che.git.impl.AddTest)  Time elapsed: 0.406 sec  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [2]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:494)
    at org.testng.Assert.assertEquals(Assert.java:123)
    at org.testng.Assert.assertEquals(Assert.java:370)
    at org.testng.Assert.assertEquals(Assert.java:380)
    at org.eclipse.che.git.impl.AddTest.testSimpleAdd(AddTest.java:69)

testBranchCreateWithStartPoint(org.eclipse.che.git.impl.BranchCreateTest)  Time elapsed: 0.675 sec  <<< FAILURE!
java.lang.ArrayIndexOutOfBoundsException: 2
    at org.eclipse.che.git.impl.nativegit.commands.LogCommand.execute(LogCommand.java:56)
    at org.eclipse.che.git.impl.nativegit.NativeGitConnection.commit(NativeGitConnection.java:316)
    at org.eclipse.che.git.impl.BranchCreateTest.testBranchCreateWithStartPoint(BranchCreateTest.java:83)

**Comment by skabashnyuk** [comment]
what version of git do you have installed?

**Comment by dhuebner** [comment]
@skabashnyuk 
git --version
git version 2.6.4 (Apple Git-63)

**Comment by ghost** [comment]
@dhuebner @ronnielking can you share your env? Run `env` or `export` please and attach the output to this issue if possible.

**Comment by skabashnyuk** [comment]
FYI. it works for me

[INFO] Che IDE :: Compiling GWT Application ............... SUCCESS [06:11 min]
[INFO] Che IDE :: Assemblies Tomcat ....................... SUCCESS [ 10.949 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38:53 min
[INFO] Finished at: 2016-04-13T11:09:35+03:00
[INFO] Final Memory: 264M/1302M
[INFO] ------------------------------------------------------------------------
[11:09:37]sj:che[master]#: mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T18:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_74, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre
Default locale: uk_UA, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.4", arch: "x86_64", family: "mac"
[11:19:02]sj:che[master]#:
[11:19:03]sj:che[master]#:
[11:19:03]sj:che[master]#: git --version
git version 2.8.1
[11:19:06]sj:che[master]#:

**Comment by dhuebner** [comment]
@eivantsov Maybe I should try to update my git

MacHuebner:assembly-main dhuebner$ env
rvm_bin_path=/Users/dhuebner/.rvm/bin
TERM_PROGRAM=Apple_Terminal
GEM_HOME=/Users/dhuebner/.rvm/gems/ruby-2.2.0
SHELL=/bin/bash
TERM=xterm-color
CLICOLOR=1
IRBRC=/Users/dhuebner/.rvm/rubies/ruby-2.2.0/.irbrc
TMPDIR=/var/folders/q2/w6yhy0vs4z9c5wwk8q7pbyxm0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.WVsEPsfz47/Render
TERM_PROGRAM_VERSION=361.1
OLDPWD=/Users/dhuebner
MY_RUBY_HOME=/Users/dhuebner/.rvm/rubies/ruby-2.2.0
TERM_SESSION_ID=BF78122C-183E-440D-8370-B9A75749154B
USER=dhuebner
_system_type=Darwin
rvm_path=/Users/dhuebner/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.l3hjp98NQP/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x3
LSCOLORS=ExFxBxDxCxegedabagacad
rvm_prefix=/Users/dhuebner
PATH=/opt/local/bin:/opt/local/sbin:/Users/dhuebner/.rvm/gems/ruby-2.2.0/bin:/Users/dhuebner/.rvm/gems/ruby-2.2.0@global/bin:/Users/dhuebner/.rvm/rubies/ruby-2.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/opt/local/bin:/Users/dhuebner/.rvm/bin
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
LANG=de_DE.UTF-8
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.11
XPC_SERVICE_NAME=0
rvm_version=1.26.10 (latest)
SHLVL=1
HOME=/Users/dhuebner
LOGNAME=dhuebner
GEM_PATH=/Users/dhuebner/.rvm/gems/ruby-2.2.0:/Users/dhuebner/.rvm/gems/ruby-2.2.0@global
RUBY_VERSION=ruby-2.2.0
_system_name=OSX
_=/usr/bin/env

**Comment by TylerJewell** [comment]
@dhuebner - can you revisit this issue?  A few things:
1. We now provide a docker image that you can run to perform a build.  We have this documented in the README on the home page.
1. A test for this updated to 4.4 with the latest maven and git installed.

I'd like to close the issue if it's not a bug anymore.

**Comment by dhuebner** [comment]
@TylerJewell The issue I described here is about failing git tests during the maven build. With the docker image the tests are also skipped:
https://github.com/eclipse/che#build-che-using-docker

So I'm not sure what I can revisit here. We are currently on 4.4 with our fork and the git tests are still failing on our linux  jenkins they are green. 
I would suggest to close the issue or fix the test in platform specific way.

**Comment by TylerJewell** [comment]
What about upgrading your Mac git client to the latest version?

I just ran a test on Mac and it was ok for me.

**Comment by dhuebner** [comment]
I'm using git from XCode and have any other git version installed on my machine, sorry.

**Comment by TylerJewell** [comment]
Ok - I am going to choose to close this issue for now. We can reopen and revisit in another configuration if this becomes a serious blocker.
