### ISSUE TITLE
Testing Server Protocol

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#5293]
With the latest changes to the unit testing on Che, we have a good understanding for a testing server protocol that is similar to Language Server protocol. 
This is a request for creation of a Testing Server Protocol that can streamline the integration of different test frameworks for Che and any other clients that implements the protocol.

- Extract and document the protocol
- Collect comments
- Provide Che's implementation of the protocol as a library

**Comment by gorkem** [comment]
@mickaelistria this may be interesting for Eclipse Desktop IDE too.

**Comment by mickaelistria** [comment]
I have the impression there could be some overlap with the Debug Protocol. As both testing and debugging include "Running". For tests, we could imagine it as an extension of a "Run", and standardize around a few notification (test started/succeed/fail) which could be inspired by JUnit notification.
I believe testing could only be an extension of the Debug/Run protocol with such notifications.

**Comment by gorkem** [comment]
I think it is essential that the protocol should accommodate for continuous testing scenarios.   
@mickaelistria I am reluctant to tie this with the debug protocol but you made a good point with debugging though. 

How does the current implementation handle debugging tests? /cc @davidfestal

**Comment by mickaelistria** [comment]
I see tests as a special case of running/debugging stuff, so there is IMHO a dependency on a protocol to run apps before we can properly consider the testing part.
The JUnit notifications and reports are pretty simple and efficient to use and are already standardized across several tools. Maybe simply sending notifications like JUnit does, but allowing those notifications to be transmitted over JSON-RCP would work.

**Comment by mickaelistria** [comment]
By the way, testing could be seen as a possible language server that would run tests continuously on edits and report test failures as errors on the code.

**Comment by gorkem** [comment]
Yes, that is the continuous testing scenario I have referred to earlier.

**Comment by gorkem** [comment]
Also related to #5482
