### ISSUE TITLE
Workspace cannot resolve Che server?

### ISSUE THREAD

**Issue by JCaraballo113** [eclipse-che/che#530]
> [STDOUT] 2016-02-25 22:45:40,580[ost-startStop-1]  [ERROR] [piEndpointAccessibilityChecker 62]   - connect timed out
> [STDOUT] java.net.SocketTimeoutException: connect timed out
> [STDOUT]    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_65]
> [STDOUT]    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_65]
> [STDOUT]    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_65]
> [STDOUT]    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_65]
> [STDOUT]    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_65]
> [STDOUT]    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_65]
> [STDOUT]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_65]
> [STDOUT]    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_65]
> [STDOUT]    at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:225) ~[che-core-api-core-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
> [STDOUT]    at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:136) ~[che-core-api-core-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
> [STDOUT]    at org.eclipse.che.ide.ext.java.server.ApiEndpointAccessibilityChecker.start(ApiEndpointAccessibilityChecker.java:57) ~[classes/:4.0.0-RC7-SNAPSHOT]
> [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
> [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
> [STDOUT]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
> [STDOUT]    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
> [STDOUT]    at org.eclipse.che.inject.lifecycle.InitModule$1$1.afterInjection(InitModule.java:44) [che-core-commons-inject-4.0.0-RC7-SNAPSHOT.jar:4.0.0-RC7-SNAPSHOT]
> [STDOUT]    at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) [guice-4.0.jar:na]
> [STDOUT]    at com.google.inject.Guice.createInjector(Guice.java:96) [guice-4.0.jar:na]
> [STDOUT]    at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:137) [everrest-integration-guice-1.12.0.jar:na]
> [STDOUT]    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) [guice-servlet-4.0.jar:na]
> [STDOUT]    at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:84) [everrest-integration-guice-1.12.0.jar:na]
> [STDOUT]    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4793) [catalina.jar:8.0.29]
> [STDOUT]    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236) [catalina.jar:8.0.29]
> [STDOUT]    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.29]
> [STDOUT]    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.29]
> [STDOUT]    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.29]
> [STDOUT]    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.29]
> [STDOUT]    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.29]
> [STDOUT]    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795) [catalina.jar:8.0.29]
> [STDOUT]    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
> [STDOUT]    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
> [STDOUT]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
> [STDOUT]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
> [STDOUT]    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
> [STDOUT] 2016-02-25 22:45:40,591[ost-startStop-1]  [ERROR] [piEndpointAccessibilityChecker 65]   - The workspace agent has attempted to start, but it is unable to ping the Che server at http://che-host:8080/ide/api/
> [STDOUT] 2016-02-25 22:45:40,592[ost-startStop-1]  [ERROR] [piEndpointAccessibilityChecker 66]   - The workspace agent has been forcefully stopped. This error happens when the agent cannot resolve the location of the Che server. This error can usually be fixed with additional configuration settings in /conf/che.properties. The Che server will stop this workspace after a short timeout. You can get help by posting your config, stacktrace and workspace /etc/hosts below as a GitHub issue.
> [STDOUT] 2016-02-25 22:45:40,593[ost-startStop-1]  [INFO ] [piEndpointAccessibilityChecker 74]   - Workspace /etc/hosts: 127.0.0.1  localhost
> [STDOUT] ::1    localhost ip6-localhost ip6-loopback
> [STDOUT] fe00::0    ip6-localnet
> [STDOUT] ff00::0    ip6-mcastprefix
> [STDOUT] ff02::1    ip6-allnodes
> [STDOUT] ff02::2    ip6-allrouters
> [STDOUT] 192.168.99.1   che-host
> [STDOUT] 172.17.0.3 60a4d02b99b8
> [STDOUT] 
> [ERROR] Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.

**Comment by TylerJewell** [comment]
@JCaraballo113 All right, so this is kind of a good thing. We just updated that error message and it told you exactly what it needed to say.  You should have seen the errors before - they were quite unhelpful!  Please check out this networking page on the things that you may need to configure to ensure that Che & your workspace can communicate with one another.  Please feel free to provide your details of your environment here too.

https://eclipse-che.readme.io/docs/networking

**Comment by JCaraballo113** [comment]
Thanks Tyler that link did it for me!
