### ISSUE TITLE
A project name and description don't change when adding the project to a workspace

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5301]
**Reproduction Steps:**

1. On the **Dashboard** click the **Create Workspace** button
2. From the **Ready-to-go Stacks** select the **Java** stack
3. From the projects **Template** select the **console-java-simple** project sample
4. Change the project name and description
5. Select the **web-java-spring** sample

**Expected behavior:**
The project name changed to "web-java-spring"

**Observed behavior:**
The project name and description didn't change.

**Che version:** 5.12.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://user-images.githubusercontent.com/7760565/26930337-bde7d49a-4c65-11e7-96db-ade056a10099.gif)

**Comment by ashumilova** [comment]
Is not actual, https://github.com/eclipse/che/issues/6916 - removes all old project creation flow stuff.
