### ISSUE TITLE
jdwp debug - cannot connect to localhost 

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5306]
After starting `java -agentlib:jdwp=transport=df_socket,server=y,suspend=y,address=8000 ...` Then selecting the appropriate `.java` file in the Projects Explorer, the debugger sometimes runs correctly allowing me two stop through the code.

    //example method 
    public static void main(String[] args){
        System.out.println("foo");
        System.out.println("bar"); // break point here
        System.out.println("baz");
    }

95% of the time the output of the jdwp process and the example method above prints the following (below) which appears to have stopped at the break point correctly BUT, the debug buttons are grayed out and the line that prints "bar"  is not red. 

    Listening for transport df_socket at address: 8000
    foo

Under the run tab I can now click on "End Debug Session".  Clicking this gives a new event "Remote debugger disconnected".  Rerunning the entire process results in the error: 

    Can not connect to: localhost:8000

**OS and version:**    
REL: 7
Docker: 17.03
Che: 5.11.0

:::EDIT:::
After a failure, refreshing the screen (F5) and running everything again but on port 5005 works but like before only once.  Changing it now to 5001 had the same effect.  At this point, I tried port 8000 again and it was working like before.

**Comment by ghost** [comment]
This issue is different but may be related to [#5235]( https://github.com/eclipse/che/issues/5235)

**Comment by ghost** [comment]
@sixteenornumber after ending debug session, do you rerun your process in a debug mode before re-attaching the debugger?

**Comment by ghost** [comment]
@eivantsov when you say rerun the process, do you mean the `java -agentlib:jdwp=...`? if so, yes.  In the "EXEC" bar on the top of the screen, I do see the jdwp process running with an incrementing timer.   My initial thought is that there is a suspended thread.  Is that possible with che?  Is there any way to check?

**Comment by ghost** [comment]
I'm getting the exact same output running Che on Ubuntu 17.x which leads me to think it's something I'm doing wrong (which I'm really hoping is the case).  Using the command below I did eventually get it to work and stop at the break point but it took 7 or so attempts doing the exact same thing before it finally worked correctly. The exact command I'm running is, 

    java -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y -cp ${project.java.output.dir} org.eclipse.che.examples.HelloWorld


As you can see in this image it says "connected" but the break line is not highlighted in red nor are the step buttons accessible. 
![connected](https://user-images.githubusercontent.com/4027214/27003689-8d42883e-4dc9-11e7-88e1-8ba047b476e8.png)

Here is some additional info on the Ubuntu config.

Ubuntu 17.04
Kernel 4.10.x

and,
CLI:
 TTY:            false
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che
 Version:        5.11.1
 Command:        info
 Parameters:     info
Mounts:
 /data:          /c/tmp
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.11.1
 CHE_HOST:       172.17.0.1
 CHE_INSTANCE:   /c/tmp/instance
 CHE_CONFIG:     /c/tmp
 CHE_BACKUP:     /c/tmp/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   172.17.0.1
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.11.1
 IMAGE_CHE=eclipse/che-server:5.11.1
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.11.1
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.11.1
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.11.1
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.11.1
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.11.1
che.env:
 CHE_HOST=172.17.0.1
 CHE_SINGLE_PORT=false

**Comment by ghost** [comment]
@sixteenornumber I have just tried it with the following command: https://www.eclipse.org/che/docs/ide/debug/index.html#java-console-apps and it worked for me.

**Comment by ghost** [comment]
@eivantsov thanks for the help so far. I ran it using the maven example and I'm still seeing the same behavior.  Is there a known OS/version  docker/version that is for a fact working that I can try?  What other possible debug info could I add to help troubleshoot this?  I'll try to add a screen capture video of my process later today/tonight.

**Comment by bryanSME** [comment]
I'm seeing the same issue.

**Comment by ghost** [comment]
@sixteenornumber any update please? I still cannot reproduce this one.

**Comment by ghost** [comment]
@eivantsov There were three issues, I found workarounds/solutions for two of them.  

**1) Using macros.**
 I was using macros eg: `${current.class.fqn}` I would select the class I wanted to run from the project explorer, then open my jdwp command from the commands explorer.  If I then click back on the project explorer, i can see that my java class is still selected.  I click run and nothing ever because i had last click on my jdwp command so no class was actually selected.  My fix was to hard code the class path and class I'm debugging.  Hasn't failed a single time.
java -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y -cp **${project.java.output.dir}** org.eclipse.che.examples.HelloWorld
vs
java -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y -cp **/projects/myProject** org.eclipse.che.examples.HelloWorld

This was unrelated to my problem but I think it's worth mentioning. Maybe someone will google this at some point or you will get another question in the future. 
I suspect there is a bug in here but it's VERY hard to recreate and doesn't happen too often.  When using ${current.project.path} having two projects in the projects explorer, I've seen the macro get stuck on the first project even though I have clearly selected project two.  I first notice it when I try to run a class and I get a class not found error.  Looking closer shows that the wrong class path is being used.  Running `echo ${current.project.path}` continues to print `/project/projectOne` despite clearly having selected projectTwo. The fix is to refresh the browser. 


**2) scrolling up**
I don't know if the issue is my browser or (Firefox 52) not.  Lets say that you are viewing myClass.java and you can see from line 20 to line 80 in your editor but you have a break point at line 10.  When the debugger navigates "UP" to line 10 it actually stops on line 11 making it look like nothing is happening. I somehow doubt this is happening to anyone else.

**3) only able to run the debugger one time**
I mentioned this before but I think it may have gotten lost in some other issues I've been having. After completing a jdwp session, you should see a two messages in the `events` pane in the bottom left of the screen.  `Remote debugger connected` and `Remote debugger disconnected`. Running it again results in the message `cannot connect to localhost:8000` 100% of the time.  My workaround has been to click on `Dashboard` or `Workspaces` or `Factories` etc. then click back to my workspace.  the event messages are now gone and it works again but only once.

**Comment by ghost** [comment]
3) Do you run `java -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y -cp ${project.java.output.dir} org.eclipse.che.examples.HelloWorld` once again before re-attaching the debugger?

Here's a short video with what's going on:

https://www.youtube.com/watch?v=WYJRNzUN9Rg

3 debug sessions in a row. My Che version is 5.14.0 - ie the latest tag.

**Comment by ghost** [comment]
@eivantsov thanks for the video, that is exactly they way i would expect it to work. I am running that command each time.  Given that it works for you and doesn't appear to be effecting anyone else, I think this is an isolated issue.

**Comment by ghost** [comment]
@sixteenornumber can you perhaps upgrade to the latest version and give it a try  again?

**Comment by ghost** [comment]
Closing as cannot reproduce. Feel free to reopen if the issue persists.
