### ISSUE TITLE
Need help to be able to checkin into Perforce via Eclipse CHE editor

### ISSUE THREAD

**Issue by kevinmat** [eclipse-che/che#5307]
HI,

I wanted to know how I can achieve being able to checkin code into Perforce via Eclipse CHE editor.

**OS and version:**    
Windows 10

Thanks,
Kevin

**Comment by TylerJewell** [comment]
@kevinmat - we only support GUI in the IDE for Subversion and Git. You can consider installing perforce tools in the terminal or with a custom stack. Once installed, you can use perforce tools on the command line from within the shell, but they will not be available within the IDE itself.

**Comment by kevinmat** [comment]
Thanks Tyler
