### ISSUE TITLE
Review current implementation of support of Language Service Protocol

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#5314]
Under this issue we need to revise what we have now for LS and all early created issues. We need to investigate the ability to support multiple Languages Servers per file (#4609) and start LS as micro-service in a separate container.

As a result we expect a document which will contain the description of problems and the proposal of a resolution, close all not actual issues.

**Comment by evidolob** [comment]
The document there https://docs.google.com/a/redhat.com/document/d/1amfRJAO4GpANmU6PtKWIMkmBJF7xWHliPXYlTKhCw8U/edit?usp=sharing

**Comment by gazarenkov** [comment]
@evidolob 
Some notes about Che6. (I think should affect terminology part of your doc.)
In Che6 Agent is renamed to Installer
Also please sync with @evoevodin we probably will not need Launchers (java part of agents) anymore
