### ISSUE TITLE
Creating workspace after starting up registry fails

### ISSUE THREAD

**Issue by JCaraballo113** [eclipse-che/che#532]
This is my stacktrace:

> [DOCKER] Step 1 : FROM codenvy/node
> [DOCKER] latest: Pulling from codenvy/node 
> [DOCKER] 03e1855d4f31: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] 76cbda9acd90: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] 7eae9fe3790e: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] 0e37b9ebfe40: Already exists 
> [DOCKER] aec735af35f2: Already exists 
> [DOCKER] a3ed95caeb02: Already exists 
> [DOCKER] Digest: sha256:8229fd4ff8ab888e03bf5200f3943fce5a3bf276a96f5acb794cefaa4dbe6afc 
> [DOCKER] Status: Image is up to date for codenvy/node:latest 
> [DOCKER] ---> 373384fc382a
> [DOCKER] Successfully built 373384fc382a
> [ERROR] java.nio.file.AccessDeniedException: /home/user/che/workspaces/wksp-zz7u

**Comment by TylerJewell** [comment]
@JCaraballo113 Can you provide some more details on this?  Are you saying that your workspaces are able to start if you do not have a registry already booted?

@garagatyi FYI - might be in your area of investigation.

**Comment by JCaraballo113** [comment]
@TylerJewell  Ok so if my registry is not running the workspace is created and the project creation finishes successfully. But with registry running it gives me that error and I cannot create a project.

Also I am running Che in Windows x64 running the default docker machine and running bash che.sh --image run

Oh also running the latest nightly as the official release refuses to launch on windows or mac for that matter.

**Comment by TylerJewell** [comment]
So this may be the nature of how you chose to run Che & the registry.  Can you attempt to run Che natively and launch the registry that way.  This would be `che --registry run`. This will run Che in a Tomcat server on your native system. And, it will launch a registry as a docker container.  Does this cause you problems?

I'm wondering if the running of Che itself in a container while having the registry in a sibling container is what is causing the issue.

We will investigate the latest RC build. I believe we are doing another one tomorrow morning and will update the official shipping binary with that one.  We just did a major merge and it's caused some chaos with our builds that have affected some users. Sorry about that.

**Comment by JCaraballo113** [comment]
@TylerJewell I tried your command but it still failed, my "fix" was to just delete the docker-machine default and recreate it from scratch, now it works.

**Comment by ghost** [comment]
I do not see anything related to Docker registry here. Glad Che is running OK for you.

Closing this issue byt feel free to reopen is the problem persists.
