### ISSUE TITLE
Link local Source folders to Projects in Eclipse CHE

### ISSUE THREAD

**Issue by kevinmat** [eclipse-che/che#5323]
Hi,

Is it possible to link local source folders to Projects in Eclipse CHE?

**OS and version:**    
Windows 10

Thanks,
Kevin

**Comment by slemeur** [comment]
Hi @kevinmat. 

Yes it is possible. Check the `sync` command to handle that: https://www.eclipse.org/che/docs/setup/cli/index.html

Alternatively you can also use Chedir for that: https://www.eclipse.org/che/docs/chedir/up-and-down/index.html . It will automate the flow to start che (if not yet running) and create a workspace with the local source synced into a new workspace.

**Comment by kevinmat** [comment]
Thanks @slemeur .
I tried using chedir as per the link which you suggested and was partially successful in creating the che server and the local workspace. I used the command below:

docker run  -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v C:\kevin\data:/data -v C:\kevin\data\utilityapp:/chedir eclipse/che:latest dir up

However the workspace project is not launching.

I was wondering that the source can be any src folder in which there are java files or it needs to be of any format which the workspace will accept?

**Comment by kevinmat** [comment]
Hi,

This is the exception which I see in chrome tools

Uncaught (in promise) Error: Workspace with name 'machine' in namespace 'workspacelsgrvxqzoq9r95mx' doesn't exist

Uncaught (in promise) Error: Workspace with name 'process' in namespace 'workspacelsgrvxqzoq9r95mx/machine/machinemoj87jnacf1ade2a' doesn't exist

Can you please suggest what could be the issue

Thanks,
Kevin

**Comment by kevinmat** [comment]
I switched my Browser to Microsoft Edge from Chrome and the Project loaded fine
Seems compatibility issue with Chrome
