### ISSUE TITLE
Loading Workspace Snapshots back into Eclipse CHE

### ISSUE THREAD

**Issue by kevinmat** [eclipse-che/che#5325]
Hi,

I am working on Windows 2010.
I have installed Docker for Windows and also Eclipse CHE server via docker commands.

When I create a Workspace using any of the provided stacks and make change to it , a snapshot gets created for it which I can see if I execute the command

docker images 

Now , my Docker crashed due to memory issues and I had to restart it and also load eclipse che container again. However I was not able to see the workspaces loaded into Eclipse CHE editor. 
My only option was to delete the snapshot and the workspace image.

Can the workspace snapshot be made available in eclipse CHE editor post restart of eclipse CHE?

Thanks,
Kevin

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by ghost** [comment]
@kevinmat can you elaborate on 

> However I was not able to see the workspaces loaded into Eclipse CHE editor.

It is possible that after you have reset Docker, all of the images were wiped out, including the snapshot image.

**Comment by kevinmat** [comment]
I can see below after I have run the command the command:
docker run  -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v C:\kevin\data2:/data -v C:\kevin\data2:/chedir eclipse/che:latest dir up


C:\Users\kevinmat>docker images
REPOSITORY                                                                      TAG                 IMAGE ID            CREATED             SIZE
eclipse-che/workspace62lccn18vmyygdjg_machineoxtunpc613ypjvt2_che_dev-machine   latest              bc10e6488461        8 hours ago         773 MB
machine_snapshot_7ehdj5x15zjdjoyu                                               latest              bc10e6488461        8 hours ago         773 MB
eclipse/che-cli                                                                 latest              8b93584e6d0a        2 weeks ago         51.2 MB

After I restart Docker I can see the above images.

However , how do I load the snapshot back into the eclipse CHE editor as I do not see the workspace "local" anymore

**Comment by ghost** [comment]
> I do not see the workspace "local" anymore

Can you elaborate here?

From your docker run syntax I can see wrong volume mounts. The format should be `c/kevin/data2` and using the same folder for `/data` and `chedir`.

**Comment by ghost** [comment]
Closed due to inactivity. @kevinmat feel free to reopen if the issue persists.
