### ISSUE TITLE
Real-Time Collaboration

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5329]
Most of the web IDEs that exists in the market have this functionality, I think Che would excel alot if we have this feature

**What does it do?**
Real-Time Code Collaboration or we can shorten it to code collab, is a feature that allows multiple users to share the same IDE Stack. This allows the guest users to use the stack without downloading the whole image just to join the fun.

This allows live pair-coding possible and allows for other developers to jump right in to your progress.

Although this would require it's dedicated panel (a Members' list plus a chat box), it's a great feature to have around if you want to do pair-coding often in your group.

**Comment by TylerJewell** [comment]
Hi - this is tracked in other issues.  See:
https://github.com/eclipse/che/issues/3080
https://github.com/eclipse/che/issues/4474

Red Hat is going to be putting more enginers onto the project and we will get closer to true real time collaboration available within Che. It's a complicated problem as you have to have an operational transform / buffer management algorithm within the workspace server itself.  Public cloud IDEs like cloud9 do this by using a hosted service like Firebase, which you cannot use in Che as it's isolated and stand alone.

**Comment by sr229** [comment]
Although this would require a custom assembly for this to be fullfilled in Che?

**Comment by TylerJewell** [comment]
No, not the way we would do it. We would implement an operational transform / editor buffer within the workspace container to control multiple edit / users interacting ith a single file at the same time.

It's a heavy weight thing to provide but we have to do it anyways as we are working on providing the ability to have multiple language servers on a single file at the same time.  Imagine an XML file that has both XML language server and a dependency analysis module at the same time.  Buffering analysis is the same as an operational transform, so we will get the benefit of that engine for pair programming.
