### ISSUE TITLE
CHE-622 Commands are added to custom stacks

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#533]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-622
Reporter:  Daria Dementieva
Description: Steps to reproduce:
1. In UD create a new project from custom stack and existing location.
2. Open it in the IDE.

As a result, default Java stack commands are added to a workspace.

It looks like when we select custom stack, UD still respects the stack selected by default, which is Java.

A different way to reproduce it is to select a NodeJS stack, then custom stack.

As a result, Node commands are saved into workspace config.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/42e1e28e27787b712268fff344ff93c008d62c61
