### ISSUE TITLE
Replace Orion based editor by Monaco

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#5330]
Replace orion based editor with [monaco editor](https://github.com/Microsoft/monaco-editor). Monaco seems to be much more performant and provide a better typing experience. Also it has built-in features such as click navigation and [command palette](https://github.com/eclipse/che/issues/4993) which can enhance the overall experience of Che

- Font size must be customizable in the editor window.

**Comment by TylerJewell** [comment]
One of the things we need to do is a comparative study on internationalization and globalization between Monaco and Orion.  My understanding is that this element is why IBM has such a strong commitment.

**Comment by sr229** [comment]
Monaco seems to have first-class support on LSP so this would be a bit easy to implement and to extend.

Full support on this one.

**Comment by sr229** [comment]
Also extending my opinion: it seems to have Search and replace + Command Pallette built in already

**Comment by sr229** [comment]
@TylerJewell I think the switch for Monaco would improve che performance wise plus judging the usability of VS Code (which uses Monaco) and how fast it is, this is something that would benefit us in the long run.

**Comment by skabashnyuk** [comment]
@gorkem looks like in terms of Next Gen Che https://github.com/eclipse/che/issues/8266 we will get out of the box. Shall we keep this issue?

**Comment by benoitf** [comment]
closing due to theia use
