### ISSUE TITLE
Enablers for JavaScript based IDE plugins

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#5331]
Che needs to open a way to implement IDE plugins using JavaScript. We can use [JsInterop](https://docs.google.com/document/d/10fmlEYIHcyead_4R1S5wKGs1t2I7Fnp_PaNaa7XTEk0) to define these APIs. In addition to GWT backed JavaScript APIs, we also need a loading mechanism defined for these plugins. This is a complicated issues that needs more study and discussions, opening this one as to serve as the epic.

**Comment by gazarenkov** [comment]
Yes, thats what we consider for a quite a long time, @evidolob even prototyped it a bit.
but, yes, complicated and massive.

**Comment by TylerJewell** [comment]
Converting this into a enhancement request until we have a list of sub-issues to track it as an epic.

**Comment by benoitf** [comment]
I think we can close this issue as it is replaced by https://github.com/eclipse/che/issues/6642

**Comment by skabashnyuk** [comment]
@gorkem do you prefer to keep this issue, or this can focus on  https://github.com/eclipse/che/issues/8266 or this https://github.com/eclipse/che/issues/6642

**Comment by gorkem** [comment]
Yes, we can close this one. We got alternates covering this.
