### ISSUE TITLE
Regression: Hover breaks PHP intellisense

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#5334]
A simple hovering over an element in the PHP editor breaks the PHP intellisense. I see the below error in the dev-machine output and then no intellisense works anymore.

```
[STDERR] Jun 12, 2017 7:31:08 AM org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
[STDERR] SEVERE: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT
[STDERR] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT
[STDERR] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
[STDERR] 	at com.google.gson.Gson.fromJson(Gson.java:810)
[STDERR] 	at com.google.gson.Gson.fromJson(Gson.java:875)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.createMessage(MessageTypeAdapterFactory.java:162)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.read(MessageTypeAdapterFactory.java:130)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.read(MessageTypeAdapterFactory.java:54)
[STDERR] 	at com.google.gson.Gson.fromJson(Gson.java:810)
[STDERR] 	at com.google.gson.Gson.fromJson(Gson.java:775)
[STDERR] 	at com.google.gson.Gson.fromJson(Gson.java:724)
[STDERR] 	at com.google.gson.Gson.fromJson(Gson.java:696)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:70)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:148)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
[STDERR] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDERR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDERR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDERR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDERR] 	at java.lang.Thread.run(Thread.java:745)
[STDERR] Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT
[STDERR] 	at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:154)
[STDERR] 	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:358)
[STDERR] 	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:78)
[STDERR] 	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:54)
[STDERR] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
[STDERR] 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
[STDERR] 	... 18 more
[STDERR] 
```

This seems to be related to the adoption of LSP4J (#4765), which implements newer version of LSP. The current version of the PHP language server in Che is quite old, based on LSP 1.x. I will prepare a PR with the latest version of the PHP language server.

Considering how easy is to trigger a hover request, this is a pretty serious issue.

**Reproduction Steps:**

1. Start a PHP workspace
1. Open a PHP file and have a code like this:
```php
<?php
$x = "myvar";
var_dump($x);
```
3. Hover on `var_dump`
3. The error will be printed in the dev-machine output and the intellisense will stop working.

**OS and version:**    

Fedora 24

**Diagnostics:** 
CLI:
TTY: true
Daemon: /var/run/docker.sock
Image: eclipse/che:5.11.2
Version: 5.11.2
Command: info
Parameters: info
Mounts:
/data: /home/kraev/Work/che-data
/data/instance: not set
/data/backup: not set
/repo: not set
/assembly: /home/kraev/git/che/assembly/assembly-main/target/eclipse-che-5.12.0-SNAPSHOT/eclipse-che-5.12.0-SNAPSHOT
/sync: not set
/unison: not set
/chedir: not set
System:
Docker: native
Proxy: not set
Internal:
CHE_VERSION: 5.11.2
CHE_HOST: 172.17.0.1
CHE_INSTANCE: /home/kraev/Work/che-data/instance
CHE_CONFIG: /home/kraev/Work/che-data
CHE_BACKUP: /home/kraev/Work/che-data/backup
CHE_REGISTRY: /version
CHE_DEBUG: false
IP Detection: 172.17.0.1
Initialized: true
Image Registry:
IMAGE_INIT=eclipse/che-init:5.11.2
IMAGE_CHE=eclipse/che-server:5.11.2
IMAGE_COMPOSE=docker/compose:1.8.1
IMAGE_TRAEFIK=traefik:v1.3.0-rc1
BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.11.2
UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.11.2
UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.11.2
UTILITY_IMAGE_CHETEST=eclipse/che-test:5.11.2
UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.11.2
che.env:
CHE_HOST=172.17.0.1
CHE_SINGLE_PORT=false

**Comment by ghost** [comment]
@kaloyan-raev I managed to reproduce it, however, in my case, I do not have any traces in ws-agent logs.

**Comment by kaloyan-raev** [comment]
The response from the PHP LS looks like this:
```json
{
  "result": {
    "contents": [
      {
        "language": "php",
        "value": "<?php\nfunction var_dump($expression, $_ = \\null)"
      },
      "Dumps information about a variable"
    ],
    "range": {
      "start": {
        "line": 2,
        "character": 0
      },
      "end": {
        "line": 2,
        "character": 8
      }
    }
  },
  "id": "2",
  "jsonrpc": "2.0"
}
```

So `contents` has two items: the first is a `MarkedString` object, the second is a pure `string` (which is also a `MarkedString` object by definition). This complies with the LSP protocol.

The issue is with how LSP4J 0.1.2 handles the response.

LSP4J 0.1.2 defines `contents` like this:
```java
private List<String> contents = CollectionLiterals.<String>newArrayList();
```
i.e. it expects only pure Strings. Hence the problem.

This is a regression of LSP4J compared to Typefox. Typefox defined `contents` like this:
```java
def List<? extends MarkedString> getContents()
```

Luckily, this seems to be fixed in LSP4J 0.2.0 where the definition is changed to:
```java
private List<Either<String, MarkedString>> contents;
```

So, updating LSP4J to 0.2.0 (#5360) should resolve this issue.

**Comment by ghost** [comment]
@vparfonov do you happen to know what is being done in regards to this issue?

**Comment by kaloyan-raev** [comment]
This is still not working after resolving #5360.

Now the exception is different:

```
[STDOUT] java.lang.ClassCastException: org.eclipse.lsp4j.MarkedString cannot be cast to org.eclipse.che.api.languageserver.server.dto.DtoServerImpls$MarkedStringDto
[STDOUT] 	at org.eclipse.che.api.languageserver.server.dto.DtoServerImpls$HoverDto.toJsonElement(DtoServerImpls.java:6484)
[STDOUT] 	at org.eclipse.che.api.languageserver.server.dto.DtoServerImpls$HoverDto.toJson(DtoServerImpls.java:6510)
[STDOUT] 	at org.eclipse.che.dto.server.DtoFactory.toJson(DtoFactory.java:158)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.getJsonElement(GsonJsonRpcMarshaller.java:165)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.getElement(GsonJsonRpcMarshaller.java:139)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.getResult(GsonJsonRpcMarshaller.java:125)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.impl.GsonJsonRpcMarshaller.marshall(GsonJsonRpcMarshaller.java:45)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.transmitOne(RequestHandlerManager.java:246)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:182)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:53)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ghost** [comment]
Hmmm.. I have just built the latest master, and do not see any exceptions in ws-agent logs:

![image](https://user-images.githubusercontent.com/5337267/28215177-b9e2dc2a-68b5-11e7-9ac5-7989c101efe2.png)

Hover works as well.

**Comment by SkorikSergey** [comment]
**Step to reproduce exception on CHE:**

- Start a workspace from the PHP stack
- Open index.php file and type code with variables
- Click on the variables

Che version: 5.15.0-SNAPSHOT
OS and version: Fedora 25
![config-21](https://user-images.githubusercontent.com/7760565/28216649-1f2a3cfe-68bb-11e7-882a-ae66c8122da0.gif)
