### ISSUE TITLE
The next and previous page buttons in the Factories list don't work(regression)

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5337]
**Reproduction Steps:**
Create at least 16 factories
In the **Factories** list click on the next page button

**Observed behavior:**
The factories list didn't change.

**Che version:** 5.12.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://user-images.githubusercontent.com/7760565/27028900-f260e53e-4f6e-11e7-8e27-facbb4d50bcc.gif)

**Comment by ghost** [comment]
Still an issue. Moreover, I cannot create more than 15 factories at all. No matter how many of them I create, Dashboard shows only 15 in the left nav pane and in the factories list.

**Comment by SkorikSergey** [comment]
Not actual.
