### ISSUE TITLE
JSONRPC connection doubles messages after start/stop of WS without page refresh

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#5342]
When a user starts WS and then stops it and starts again without refreshing browser page JSONRPC connection starts sending multiple copies of the same events, e.g. WS status change events.

**Reproduction Steps:**
1. Open IDE.
1. Open dev tools in the browser.
1. Find WebSocket connection to master and start tracking WebSocket frames.
1. Start WS X.
1. Stop it with the menu.
1. Ensure that there is only 1 copy of WS status messages.
1. Start it again without refreshing browser tab.
1. Ensure that there is several copies of each WS status event appear.

**Comment by garagatyi** [comment]
@dkuleshov FYI

**Comment by dkulieshov** [comment]
Seems like this is not reproducible anymore.
