### ISSUE TITLE
Rework client for Project service in order to avoid using Everrest based Websocket calls

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#5347]
[ProjectServiceClientImpl](https://github.com/eclipse/che/blob/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/project/ProjectServiceClientImpl.java#L144) uses `WsAgentStateController#getMessageBus` for importing a project. Need to avoid using it (replace with JSON-RPC if needed).

**Comment by dkulieshov** [comment]
Duplicates https://github.com/eclipse/che/issues/4591
