### ISSUE TITLE
Rework Composer plugin to avoid using Everrest based Websocket calls

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#5348]
[ComposerOutputHandler](https://github.com/eclipse/che/blob/master/plugins/plugin-composer/che-plugin-composer-ide/src/main/java/org/eclipse/che/plugin/composer/ide/communication/ComposerOutputHandler.java#L69) uses `WsAgentStateController#getMessageBus` for listening an output. Need to replace it with JSON-RPC.

**Comment by gazarenkov** [comment]
@kaloyan-raev could you look at it?
that is a part of a movement to replace our "old styled" WS calls with JSON-RPC

**Comment by kaloyan-raev** [comment]
@gazarenkov I am not sure what exactly I should do here. The ComposerOutputHandler is designed after the MavenMessageHandler. So when a PR for #5350 is created, I can do a similar one for Composer.

**Comment by gazarenkov** [comment]
Just to make sure you aware, nothing urgent
and @dkuleshov can help you if needed
thanks

**Comment by svor** [comment]
@kaloyan-raev You can see how it is in PR https://github.com/eclipse/che/pull/5527.
Especially pay attention to:
`ArchetypeGenerator.java`, `MavenArchetypeJsonRpcMessenger.java` and `MavenMessagesHandler.java`
Feel free to ask me if something is not clear.

**Comment by kaloyan-raev** [comment]
@svor Thank you for the pointers. I will work on this on Friday.

**Comment by kaloyan-raev** [comment]
@svor I created PR #5629

**Comment by svor** [comment]
@kaloyan-raev I've reviewed, good job :+1:
