### ISSUE TITLE
Not able to add commands on workspace created with eclipse chedir

### ISSUE THREAD

**Issue by kevinmat** [eclipse-che/che#5355]
Hi,

I have created a local workspace using chedir as below:

:\kevin\data\utilityapp>docker run  -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v C:\kevin\data3:/data -v C:\kevin\data3:/chedir eclipse/che:latest dir up
WARN: Bound 'eclipse/che' to 'eclipse/che:5.9.1'
INFO: (che cli): 5.9.1 - using docker 17.03.1-ce / docker4windows
INFO: (che dir): Generating default /C/kevin/data3/Chefile
INFO: (che dir): Adding /C/kevin/data3/.che directory
INFO: (che dir): Starting Eclipse Che silently
INFO: (che dir): Eclipse Che will be available at http://localhost:8080 (it's running but configuration is still in progress)
INFO: (che dir): Workspace created
INFO: (che dir): Workspace booting...
INFO: (che dir): Generating ssh key
INFO: (che dir): Updating project...
INFO: (che dir): Executing post-loading commands
INFO: (che dir): Workspace booted and ready for development
INFO: (che dir): Connect to http://localhost:8080/dashboard/#/ide/che/local

When I open the project in editor and try adding a command I get the error 
"Failed to execute command. Machine <machine name> not found". I have attached screenshot of the same.

*OS and version:**    
Windows 2000

I have also attached screenshot of the output of docker commands for images and containers on my system.

Can you please suggest what could be the issue

Thanks,
Kevin
![docker_command_output](https://user-images.githubusercontent.com/29288687/27065712-92bf8b40-501c-11e7-8f02-a6a7110eddf5.jpg)
![error](https://user-images.githubusercontent.com/29288687/27065720-a0db5c72-501c-11e7-90dc-626cc3e35e18.jpg)

**Comment by ghost** [comment]
@kevinmat can you try it in an incognito tab? Look like a caching issue.

**Comment by kevinmat** [comment]
Yes worked in using incognito.Thanks,closing this issue
