### ISSUE TITLE
Upgrade LSP4J library version to 0.2.0

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#5360]
For some (JSON) LS we need to get newer API to get ability configure client capability

http://projects.eclipse.org/projects/technology.lsp4j/releases/0.2.0

**Comment by kaloyan-raev** [comment]
The new version of LSP4J should also resolve the Hover issue in the PHP intellisense (#5334).

**Comment by evidolob** [comment]
We have this pull request #5292 I will continue work on that pull request
