### ISSUE TITLE
Improve JSON language server

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5365]
We need to improve JSON language server autocomplete because we have wrong behavior.

Steps to reproduce:
- Go to the workspace with launched JSON language server
- Create C# project with JSON file
- Open JSON file
- Launch autocomplete (Ctrl + Space) in the places like in the attachment
- Pay attention to result 

**Expected behavior**
Autocomplete will be provided pieces of the code 

**Observed behavior**
Autocomplete does not provide the pieces of the code

**Attacment**

![anim](https://user-images.githubusercontent.com/22724619/27084014-1153c3fa-5053-11e7-9b2b-a4cf6394acc0.gif)

**Comment by kaloyan-raev** [comment]
The `$1` in the inserted text is a placeholder for the so called "tab stop". The client (i.e. Che editor) is supposed to remove `$1` and place the cursor there. This is specified in LSP 3.0: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-request. Look for `InsertTextFormat`.

**Comment by rcjsuen** [comment]
Alternatively, Che needs to make it clear that it doesn't support snippets when it sends the initialization request to the server. The server will then know that the client doesn't support snippets and won't bother sending back completion items with tab stops in them..

Please refer to `completion.completionItem.snippetSupport` in `TextDocumentClientCapabilities` in the [protocol](https://github.com/Microsoft/language-server-protocol/blob/e1ecd6a23a80735a1a7dc2abe3b684a7032e651e/protocol.md#initialize).

**Comment by tsmaeder** [comment]
Snippet description: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/browser/snippet.md

**Comment by tsmaeder** [comment]
Snippet description has changed since I have started implementation. The associated PR implements https://github.com/Microsoft/vscode/blob/0ebd01213a65231f0af8187acaf264243629e4dc/src/vs/editor/contrib/snippet/browser/snippet.md
