### ISSUE TITLE
PostgreSQL db-machine

### ISSUE THREAD

**Issue by dev-gbassanini** [eclipse-che/che#5368]
Everytime I restart my workspace the db-machine recreates the database and all the content from previous runs is lost. 

**Reproduction Steps:**

1.  Created and started a custom workspace based on postgresql  (db-machine) and ubuntu_jdk8 (dev-machine) images. I created my images, built them and added them to my local registry.
For the db image I'm using the docker-entrypoint-initdb.d and add a sql script that creates the DB and all it's objects.

1. I'm referring to the image in my compose as: 
services:
db:
image: 'localhost:5000/fe_db'

1. I created some data in a table of the DB and restarted workspace. The debug starting process shows every object in the DB is recreated and when I check for the data, it's lost.

**OS and version:**    
Dockerized version of che 5.2 running in my local machine (Ubuntu 16.04) and docker version reports: 17.05.0-ce

**Comment by ghost** [comment]
@dev-gbassanini when restarting the workspace, do you snapshot it? You may want to peek in your che.env file and take a look at SNAPSHOTTING env values.

**Comment by dev-gbassanini** [comment]
Hi @eivantsov sure! Just checked che.env and yes, I have those values to always take snapshots.
Also tried using the che_workspace_volume with no success. In a multi machine environment che sets the mount to the dev-machine instead of the db-machine.
Also tried the pet-clinic sample that comes with che but no luck either:

- Connected to DB via a external client in host (dbeaver)

- Created the db tables with the provided script in the workspace

- Inserted data

- Stopped the workspace (made sure it got snappedshot) via the dashboard

- Started the workspace via dashboard

- Connected to the MySQL DB via dbeaver client in my host and all tables were lost

I didn't make any change to the recipes or anything at all, just used the sample as is.

**Comment by ghost** [comment]
@dev-gbassanini are you using an official image for postgresql machine? I suspect that there's a volume declared in a Dockerfile that points to the location where postgres keeps data. When Docker commits to a container, data in volumes is untouched. That's a problem. However, I cannot offer an immediate solution for it.

**Comment by ghost** [comment]
@dev-gbassanini you need to rebuild your db image without VOLUME instruction. This way, when an image is snapshotted data will be persisted.
