### ISSUE TITLE
CHE-624 readme file should provide more information to get started with Che

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#537]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-624
Reporter:  Stévan Le Meur
Description: When a user download Che, he has a package where he can see a readme file.

The first things the user is doing, is reading the readme file, but at this moment, there are no useful information other than redirecting to the che website.

We should at least:
- redirect to the correct documentation pages on readme.io
  better:
- directly provide the content in the readme.

**Comment by ddementieva** [comment]
Fixed
