### ISSUE TITLE
[Regression] PHP language server fails to start

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5373]
Steps to reproduce:

1. Create a php workspace, enable php language server
2. Open .php file

There's an error :
 
`Error fetching server capabilities php. org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Argument 2 passed to LanguageServer\LanguageServer::initialize() must be an instance of LanguageServer\Protocol\ClientCapabilities, string given, called in /home/user/che/ls-php/php-language-server/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php on line 164`

This can be reproduced with the latest master.

**Comment by musienko-maxim** [comment]
Related selenium test: PhpProjectDebuggingTest

**Comment by kaloyan-raev** [comment]
I hit this too and did some debugging. The LSP protocol specifies that the `InitializeParams.capabilities` field is mandatory. It can be an empty object, but not undefined/null. So the PHP language server expects it in the `initialize` request and fails if it is not present in the JSON message body.

On the Che side the `ServerInitializerImpl` sets an empty `ClientCapabilities` object as the `InitializeParams.capabilities`, but then the `InitializeParams` object is serialized to something like this:

```json
{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "initialize",
  "params": {
    "processId": 24734,
    "rootPath": "/home/user/projects/myproj",
    "clientName": "EclipseChe"
  }
}
```
i.e. the `capabilities` object is missing.
