### ISSUE TITLE
[Regression] The Create button is not active while creating a workspace from the Java-Mysql stack

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5374]
**Reproduction Steps:**

1. Create and start a workspace from the **Java-Mysql** stack with the **web-java-petclinic** project.
2. In the **Dashboard** click the **Create Workspace** button.
3. Select the created workspace and click the **Create new workspace from stack** radiobutton.
4. Select the **Java-Mysql** stack.

**Observed behavior:**
There is an error **"This project name is already used"** for project name and the **Create** button is not active.

**Che version:** 5.12.0-SNAPSHOT
**OS and version:** Ubuntu 16.04 LTS
![anim](https://user-images.githubusercontent.com/7760565/27124259-2bcaea64-50f9-11e7-8752-feb01f76c283.gif)

**Comment by ghost** [comment]
The issue becomes irrelevant with the new workspace creation flow. Feel free to reopen if it can be reproduced in UD
