### ISSUE TITLE
Flickering error markers at refactoring in some cases

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#5383]
We have too many error markers at refactoring in some cases and it leads to flickering effect.

**Reproduction Steps:**
1. Create 'web-java-spring' project from samples
2. Open GreetingControler class
3. Try to rename variable 'view' by Assistant -> Refactoring -> Rename action
4. Type long name as new name for variable

Note: the bug is reproduced when we have a few places in file to rename.

**OS and version:**    
Che 6.0.0-M5; 
Fedora 25, GNOME Version 3.22.2

**Diagnostics:** 
In current implementation we have queue on client side which sends document changes on server side with delay in one second.
When user types some text, document changes is added to queue, merged and sent on server side as one change. Server side handles changes and notify client side about result of reconcile operation.
In case refactoring when we have a few places in file to rename, client side gets many events about document changes and can not merge it, so sends as separate changes on server side. As result we have too many events with reconcile result and flickering effect.

![reconcilebugatrefactoring](https://user-images.githubusercontent.com/5676062/27176185-494a3e06-51ca-11e7-85d0-e76e94155e3b.gif)

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
