### ISSUE TITLE
Update C# language server

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#5385]
Update the C# language server to the latest available community release

**Comment by AndrienkoAleksandr** [comment]
Awaiting on update omnisharp-client https://github.com/OmniSharp/omnisharp-node-client/issues/435

**Comment by ghost** [comment]
@gorkem I'd also add that it should be compatible with `.net 2.0`

**Comment by gorkem** [comment]
Correct, it needs to be tested for .Net 2.0. Please contact @vrubezhny for a test stack

**Comment by ghost** [comment]
@gorkem @vrubezhny by the way, it definitely looks like LS does not like the way dotnet command are called in RH .net stacks - `scl enable rh-dotnet20`. Can you elaborate on why dotnet isn't added to PATH directly?

**Comment by gorkem** [comment]
@dharmit can we update the stack so that .Net is enabled by default?

**Comment by AndrienkoAleksandr** [comment]
LS was updated, so I close this issue.

**Comment by gorkem** [comment]
@AndrienkoAleksandr were you able to run the LS for .Net 2.0?

**Comment by ghost** [comment]
@gorkem yes, C# LS runs ok for .NET 2.0
