### ISSUE TITLE
Double clicking a line number adds a star.  What is it for?

### ISSUE THREAD

**Issue by bryanSME** [eclipse-che/che#5387]
When double clicking a line number in the code, a small blue star appears to the left of the line number.  What is the star for?  I wasn't able to find anything about it in the docs.

**Comment by ghost** [comment]
Look like a bookmark.

**Comment by bryanSME** [comment]
I was thinking the same thing.  How do I access the list of bookmarks?

**Comment by maximilianodendahl** [comment]
isn't that rather a debugging breakpoint?

**Comment by ghost** [comment]
@maximilianodendahl no, it id not.

@bryanSME you can see icons in the editor on the right. They will navigate you to the bookmark:

![image](https://user-images.githubusercontent.com/5337267/27273492-f2216c06-54d7-11e7-89f4-9004e942bd7a.png)

**Comment by bryanSME** [comment]
@eivantsov thank you
