### ISSUE TITLE
Maven tests fails on some configurations

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#5395]
Due to [this](https://github.com/eclipse/che/blob/6a427e3b64fcbbc7725c9637b2b9beddd9471e19/plugins/plugin-maven/maven-server/maven-server-impl/src/test/java/org/eclipse/che/maven/server/ProjectResolverTest.java#L62-L62) line tests fails on environments where M2_HOME property is not set. We need to find more flexible way to configure maven server independently of the hosting OS.

**Comment by dkulieshov** [comment]
this is actual for CHE 5.14.0

**Comment by benoitf** [comment]
This property is required in the wiki: https://github.com/eclipse/che/wiki/Development-Workflow#build-and-run-from-source
so if it's not required anymore, doc will have to be updated

**Comment by tsmaeder** [comment]
if we DO require M2_HOME to be set, it would be more user friendly to explicitly fail with a message like "M2_HOME env variable required but not set".

**Comment by benoitf** [comment]
yes, as well ;-)
