### ISSUE TITLE
Python lsp is crashing

### ISSUE THREAD

**Issue by philipp-lein** [eclipse-che/che#5407]
Hey Che Team,
thanks for your work. You are doing a great job.
The new python lsp is awesome.
But when you write an char like (ä,ü,ö) in the editor the lsp crash and all features doesn't work anymore.
So you had to delete the char and reload the workspace.

**Comment by ghost** [comment]
Bug confirmed

**Comment by ghost** [comment]
The actual error happens on LS side. Closing the issue. Opening an issue at https://github.com/palantir/python-language-server probably makes sense
