### ISSUE TITLE
Switch project importing begin operation from REST to JSON-RPC protocol

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#5410]
Need to rewrite `org.eclipse.che.api.project.server.ProjectService#importProject` to be able to start project importing via JSON-RPC protocol.

**Comment by gazarenkov** [comment]
I do not understand this task.

If you want to replace REST calls with RPC for Project API there should be general idea for it, I am not OK with making it little by little.

Or you mean something else?

**Comment by vzhukovs** [comment]
After discussion with @vparfonov were decided that generally operation import of the project will be divided into two separated issue. First issue just broadcasting importer logs over JSON-RPC and second one is start/stop importing also over JSON-RPC. I created this issue just not to forget to return to this discussion with @vparfonov. Sure, this idea should be discussed globally.

**Comment by gazarenkov** [comment]
I see, so what I am saying is that transition Project API from REST to RPC should be considered in a scope of whole service, i.e. all the methods, that's why this issue is confusing

**Comment by vzhukovs** [comment]
Totally agree

**Comment by dkulieshov** [comment]
We will need more global issue in order to replace REST Project Service API to JSON-RPC
