### ISSUE TITLE
Autobrackets not working (PHP)

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5411]
Auto Brackets for PHP seem to be broken on Windows with Chrome browser (Tested on Codenvy 5.12.0). When typing { or [ the closing bracket does not appear while it works with < and (. On a chromebook (Chrome OS 58) it works in Chrome. Also works perfectly fine in Firefox on the same test devices.

**Reproduction Steps:**
- Create PHP Workspace
- Create PHP File
- Write Brackets

**OS and version:**    
Windows 8 with Chrome 59
Windows 10 with Chrome 59

**Comment by ghost** [comment]
@ex-q I am on Win 10 and it works for me -  `(` `{` `<`

**Comment by ghost** [comment]
@eivantsov I made many more tests and found out something interesting. When applying the german (DE) keyboard layout it does not work. When switching to US keyboard layout it works perfectly. Would you mind switching to the german layout and test it again? This is really a weird bug. Thanks a lot!

**Comment by ghost** [comment]
Confirmed on German keyboard layout.

**Comment by ghost** [comment]
@gorkem It is not PHP specific issue, but Windows + Orion + non-English keyboard layout problem. It's totally fine on Ubuntu but can be reproduce on Windows and non-English keyboard layouts only.

So, assigning @kaloyan-raev as a PHP expert does not seem reasonable here. I'd suggest @AndrienkoAleksandr - he has already fixed a few of those before.

**Comment by SkorikSergey** [comment]
Is this still an issue?
