### ISSUE TITLE
Project import never finishes if no wizard was provided for the project importer

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#5415]
[Project import](https://github.com/eclipse/che/blob/3ab62469230c2c48d89dc2dddb1e36f14c7665b3/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projectimport/wizard/presenter/ImportProjectWizardPresenter.java#L148-L148) looks like never ending if no wizard was provided for the project importer.
Import dialog must not display importer in the list if no appropriate wizard was provided.

Please, pay attention that there's the same problem in the [project creation wizard](https://github.com/eclipse/che/blob/3ab62469230c2c48d89dc2dddb1e36f14c7665b3/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardPresenter.java#L233-L233).

**Reproduction Steps:**
Run CHE without client-part of git-plugin.
Try to import a project with GIT importer.

**Diagnostics:** 
There's the error message in browser's console:
`Caused by java.lang.IllegalStateException: WizardRegistrar for the importer git isn't registered.`

**Comment by gazarenkov** [comment]
IMO it is somewhere in the MainPagePresenter.loadImporters()

I think no needs to call server side at all, just make a list using WizardRegistrars on the client side, it will be simpler and correct.

**Comment by ghost** [comment]
@vparfonov can you prioritize this?

**Comment by gazarenkov** [comment]
+
it is quite critical
