### ISSUE TITLE
Diagnostics Finished With Error: Websockets

### ISSUE THREAD

**Issue by Anthony-Janin** [eclipse-che/che#5418]
Hello,

Websockets
No reply of websocket test after 5 seconds. Websocket is failing to connect to ws://5.196.26.55:9793/api/ws

I've got this issue only when I use the browser behind a proxy

Have you any idea?

Thanks & Regards
Anthony

**Comment by ghost** [comment]
@Anthony-Janin do you run Che on a different machine?

**Comment by Anthony-Janin** [comment]
No on my VPS server.

When I use CHE on my phone or tab for example all it's ok.
But when I use CHE behind a proxy I've got this issue..

Thanks

**Comment by ghost** [comment]
Your proxy may either block websockets or the ephemeral port range.

**Comment by Anthony-Janin** [comment]
Yes,

So What is the solution?

Thanks & Regards

**Comment by ghost** [comment]
If websockets are blocked, there is nothing to do on Che side - you won't be able to use Che when accessing in from your company network. If the ephemeral port range is filtered, you may want to try a single port policy. In your `che.env` file set `CHE_SINGLE_PORT=true` and restart Che. In this case, your client (browser) will reach ws-agent and services inside a workspace container on port 8080

**Comment by Anthony-Janin** [comment]
Ok thanks I will test...

But it's strange because when I use https://codenvy.io all work well... So it's that why I don't understand why my eclipse che don't work...

**Comment by ghost** [comment]
codenvy.io networking differs from that of Che.

**Comment by Anthony-Janin** [comment]
same issue  CHE_SINGLE_PORT=true 

No reply of websocket test after 5 seconds. Websocket is failing to connect to ws://5.196.26.55:8080/api/ws

**Comment by ghost** [comment]
Maybe outgoing traffic through port 8080 is blocked.

**Comment by Anthony-Janin** [comment]
Ok but on my network (on my phone) all work well...
I changed the port 8080 to 9793 it's the same....

I need to have a tool like eclipse CHE and this tool must work everywhere like codenvy.io ...

:(

**Comment by ghost** [comment]
@Anthony-Janin I was able to start a workspace on your Che server. It worked for me. Unfortunately, there's nothing I can do about your network restrictions. I have given you clues on what might cause connection failures.

**Comment by Anthony-Janin** [comment]
Greatttttttttttttttttttt yes it's workkkk (workspace work well) only the diagnostics doesn't work...

Thanks the solution is well CHE_SINGLE_PORT=true
So why the default value is not TRUE for CHE_SINGLE_PORT but false?

Thanks

**Comment by ghost** [comment]
Yes, false is the default.

**Comment by Anthony-Janin** [comment]
Yes but why?

**Comment by ghost** [comment]
@Anthony-Janin because Eclipse Che when running locally use of the ephemeral port range is not a big deal.

**Comment by Anthony-Janin** [comment]
Ok Thanks for all..

**Comment by Anthony-Janin** [comment]
Finally there others issue doesn't work correctly arfff

**Comment by ghost** [comment]
@Anthony-Janin if these issues aren't related to connectivity, please, close this issue and open a new one

**Comment by Anthony-Janin** [comment]
oki

**Comment by Anthony-Janin** [comment]
Yes now my issue is this one: https://github.com/eclipse/che/issues/5215

**Comment by Anthony-Janin** [comment]
Hi,

I changed the PORT to 1122 for example and disable the autosave and all is ok.

Thanks again.
