### ISSUE TITLE
Callback URL different from GitHub callback and che.properties

### ISSUE THREAD

**Issue by adolinski** [eclipse-che/che#542]
The callback URL under the Use Che as an IDE->Git has a root context of http://localhost:8080/che and the che.properties file is http://localhost:${SERVER_PORT}/ide. When using /che as the root context, and trying to upload an OAuth token to GitHub, Che gives a 404. When changing the GitHub root context to /ide, Che is able to authenticate with GitHub.

**Comment by ddementieva** [comment]
Fixed in docs. Thanks for reporting it. Just checked. GitHub oAuth is working fine.

**Comment by ghost** [comment]
Closing the issue. Feel free to reopen if you have problems with GitHub oAuth.
