### ISSUE TITLE
Rework server pinging to make it more interactive and fast

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#5420]
Now pinging of the servers is sequential and slow. We should rework it to allow a really interactive load of Workspace and speed up the whole process.

**Comment by gazarenkov** [comment]
Could you please be more precise, what exactly should be reworked?

**Comment by garagatyi** [comment]
Right now we ping server by server. So while we are pinging the first one others might have already been available, but we will wait until the check of the first one succeeded. So it is not really interactive from client POV. 
So we want to rework this component in such a way that if a server is already available then we send an event to the client about that even if this is the last server from our list.

**Comment by gazarenkov** [comment]
I guess you are talking about some technical debt in the Docker impl, right?
I would suggest to be more precise, if you just point out the class you see the problem in, it would worth many words :)

**Comment by garagatyi** [comment]
yes, it is all about technical debt in Docker infra impl. 
Here is the [code](https://github.com/eclipse/che/blob/spi/infrastructures/docker/src/main/java/org/eclipse/che/workspace/infrastructure/docker/DockerInternalRuntime.java#L268) I'm talking about.

**Comment by gazarenkov** [comment]
I see, thanks
