### ISSUE TITLE
Need to investigate ability re-compiles only those portions of a program that have been modified

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#5422]
Now we have an ability to run/debug tests, but if make some changes in the project firstly need to compile project for getting actual state and then run/debug tests. 

So main idea of this issue is compile only changed part of code automatically before running/debugging tests.

It will help us save a lot of time for example: for compiling some modules in che project take around 45 sec, but if we change only one class we don't need recompile all module just changed and related classes it can take less then 1 second. 

It is a next step after https://github.com/eclipse/che/issues/5316

**Comment by vparfonov** [comment]
Need to investigate ability re-compiles only those portions of a program that have been modified. (Incremental compiler)

**Comment by vparfonov** [comment]
Depends on https://github.com/eclipse/che/issues/6157

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
