### ISSUE TITLE
Editor is not updated if refactor rename is performed more one time

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#5424]
_* When I try to perform rename refactor (field, parameter or variable) in the same file by refactor form more than one time, then the editor is not updated. The content is updated only after reopen file._

**Reproduction Steps:**
* Open a java file in the IDE (e.g. web-java-spring project from template)
* Perform refactor rename (field, parameter or variable) by refactor form
* Perform refactor rename again

**Expected behavior:**
* the editor should update the content immediately

**Observed behavior:**
* the editor is not updated
* need to reopen java file or refresh browser

**Che version:** 5.13.0
**OS and version:** Fedora 25
**Docker version:** 17.03
**API docker version:** 1.27
**Che install:** Docker container  

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![refactor_rename](https://user-images.githubusercontent.com/5408906/27395121-5a706b46-56b7-11e7-9bac-6d65376b9c72.gif)

**Comment by AndrienkoAleksandr** [comment]
Fixed by https://github.com/eclipse/che/commit/00421dd624355630860c0d12737e6ce39b5c83d5
