### ISSUE TITLE
Unexpected behavior when using the "move lines up/down" keybind on Chromebook

### ISSUE THREAD

**Issue by Lokoboon** [eclipse-che/che#5430]
When trying to use the alt + arrow up/down keybind to move lines in your code, it seems to trigger the page up/down keybind instead. 

Che version: 5.12.0

**Reproduction Steps**:
On chromebook:
Create php workspace
Create a php file
Try to use alt + arrow up/down keybind

**OS and version:**    
ChromeOS version 58

**Comment by ghost** [comment]
The actual error happens on LS side. Closing the issue. Opening an issue at https://github.com/palantir/python-language-server probably makes sense

**Comment by ghost** [comment]
Closing the issue due to ow priority.
