### ISSUE TITLE
Eclipse Che application authentication

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5435]
We are going to use OpenID protocol + Keycloak ID to introduce authentication in Eclipse Che. 
In terms of Keycloak we have such clients.
## Private client
 - wsmaster(aka api) - 
## Public client
- dashboard
- ide
- docs (aka swagger)
- cli - ?

Goal of this task 
-  setup kycloak adapters for each client
- find the way how to provide configuration for each client. Important parts: secret for a private client, OpenID endpoint.

Note 1 : wsagent authentication is part of separate issue https://github.com/eclipse/che/issues/5434
Note 2: May be  wsmaster is  bearer-only client.

**Comment by benoitf** [comment]
FYI cli is also a client

**Comment by skabashnyuk** [comment]
Depends on https://github.com/redhat-developer/rh-che/issues/133

**Comment by mshaposhnik** [comment]
Done - merged into branch.
