### ISSUE TITLE
 Synchronize user profile with keycloak database

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5438]
We used such profile attributes in such products
# Eclipse Che
 - "email"
# Codenvy
 - "firstName"
 - "country"
 - "jobtitle"
 - "phone"
 - "email"
 - "lastName"
 - "employer"

We need to find a way how to map it to keycloak attributes for two use-cases.
- API to read profile attributes to display it on UI. 
We might just need to implement ```ProfileDao.getById```.
- API to update profile. 
 Either find a way how to implement ```ProfileDao.update``` to update profile in keycloak database either made a redirect to profile page on Keycloak application.

**Comment by mshaposhnik** [comment]
Added DAO. By default it always accesses only current user profile.
To make it possible for single user (aka admin) to access the other users profiles, it should be correctly configured into Keycloak console by following steps:
1) Go to realm-management client, check if authorization switch enabled;
2) Go to client authorization tab, select policies sub-tab;
3) In the "Create policy" dropdown at top right, select "User";
4) Put the username which will have access, and policy name, and save; (pic 1);
![screenshot_20170815_152603](https://user-images.githubusercontent.com/1651062/29315862-1d1f676e-81ce-11e7-81de-24f07c5343da.png)

5) Go to menu users, permissions tab. Enable switch if needed.
6) Select "view" permission. It allows to view other users.
7) Paste new created policy name into "Apply policy" field and save.
![kk2](https://user-images.githubusercontent.com/1651062/29316027-f33f8b94-81ce-11e7-9af1-fd3dc34954b5.png)
Result (token from user admin, so logged as admin and viewing profile ur3cma) :
![kkk3](https://user-images.githubusercontent.com/1651062/29316340-5257b3ee-81d0-11e7-8707-fa36c68b04b8.png)
