### ISSUE TITLE
Startup issues on Windows 10 Pro

### ISSUE THREAD

**Issue by koppor** [eclipse-che/che#5440]
At an #EclipseCon talk we were recommended to run `docker run eclipse/che dir up`. This did not work, but the output help (indirectly) suggested to run `docker run -it --rm -e DOCKER_HOST=tcp://localhost:2375 eclipse/che dir up`

(Refs https://twitter.com/TylerJewell/status/877602018478612480)

**Reproduction Steps:**

![grafik](https://user-images.githubusercontent.com/1366654/27434560-6bbb272c-5759-11e7-976d-e898b0f5319c.png)

**OS and version:**    

Microsoft Windows 10 Pro 10.0.15063

Docker 17.03.1-ce

**Diagnostics:** 

`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Comment by ghost** [comment]
@koppor perhaps you should check the box to expose Docker daemon on 2375 without TLS

Also, when you run `docker info` do you get any response?

**Comment by koppor** [comment]
docker info:

```
> docker info
Containers: 31
 Running: 0
 Paused: 0
 Stopped: 31
Images: 131
Server Version: 17.03.1-ce
```

Disabling TLS also does not help.

Other docker images work. Also docker-compose images. Without having to set some extra parameters.

**Comment by slemeur** [comment]
Hi @koppor ! Thanks for reaching.

In the demo we gave at EclipseCon we had an alias on the `che dir up` command to simplify it. The command is having certain parameters to be provided to che.
You can check those in the documentation here:
https://www.eclipse.org/che/docs/chedir/getting-started/index.html

Let us know how it goes.

**Comment by koppor** [comment]
I don't understand `<path>`  in https://www.eclipse.org/che/docs/chedir/getting-started/index.html, because "web-java-spring-petclinic" seems to be the demo project. It is also unclear, what I have to use at `<version>`. I have used `latest`.

But the command line output helps:

```
> docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock eclipse/che dir up
WARN: Bound 'eclipse/che' to 'eclipse/che:5.12.0'
INFO: Welcome to Eclipse Che!
INFO:
INFO: We could not detect a location to save data.
INFO: Volume mount a local directory to ':/data'.
INFO:
INFO: Simplest syntax:
INFO:   docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock
INFO:                       -v <YOUR_LOCAL_PATH>:/data
INFO:                          eclipse/che dir up
```

So, I fired up

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /C/git-repositories/OpenTOSCA/opentosca-dockerfiles:/data eclipse/che dir up
```

and got following at the end:

```
WARN: ':/chedir' not mounted - using /C/git-repositories/OpenTOSCA/opentosca-dockerfiles as source location
INFO: (che dir): Generating default /C/git-repositories/OpenTOSCA/opentosca-dockerfiles/Chefile
INFO: (che dir): Adding /C/git-repositories/OpenTOSCA/opentosca-dockerfiles/.che directory
INFO: (che dir): Starting Eclipse Che silently
```

The docs read "You can either open the IDE in your browser to work on the project immediately. " Which URL should I have to use? I don't see any URL.

**Comment by ghost** [comment]
Add -v `/C/git-repositories/OpenTOSCA/chedir:/chedir` to your docker run syntax.

**Comment by koppor** [comment]
It even run without. I was just too impatient. I had to wait for the following lines

> INFO: (che dir): Eclipse Che will be available at http://localhost:8080 (it's running but configuration is still in progress)

I still have two minor things, which are not important in normal settings (I suppose)

## Update required, but not working

```
ERROR: Your CLI version 'eclipse/che:5.13.0' is newer than your installed version '5.12.0'.
ERROR:
ERROR: Run 'eclipse/che:5.13.0 upgrade' to migrate your installation to '5.13.0'.
ERROR: Or, run the CLI with 'eclipse/che:5.12.0' to match the CLI with your installed version.
```

Then, I get the following:

```
> docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /C/git-repositories/OpenTOSCA/opentosca-dockerfiles:/data -v /C/git-repositories/OpenTOSCA/chedir:/chedir eclipse/che:5.13.0 upgrade
INFO: (che cli): 5.13.0 - using docker 17.06.0-ce-rc5 / docker4windows
INFO: (che upgrade): che is not installed or configured. Nothing to upgrade.
```

## Timeout issue

Sometimes, I could not test at, as I have following issue:

> Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Is it possible to increase the timeout at bad internet connections?

**Comment by ghost** [comment]
@koppor timeout isn't configurable. It is the CLI that checks it. You may add `--skip:preflight` to your run syntax and all those checks are gone.
