### ISSUE TITLE
Diagnostics will be failed by BusyBox's wget.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#5446]
Diagnostics will be failed by BusyBox's wget.

**Reproduction Steps:**

Execute `dianostics`.

**OS and version:**    

CoreOS but must be independent from OS.

```
Version :5.11.0-SNAPSHOT
Revision :63b440af28634235
Build Time :2017-05-19 16:01:18
```

**Diagnostics:** 

```
[STDOUT] Exec Agent binary is downloaded remotely
[STDERR] wget: unrecognized option: s
```

Note: I've already report this issue at https://github.com/eclipse/che/issues/2424#issuecomment-310569555 and moved here.

**Comment by monaka** [comment]
It seems it is caused by there.
https://github.com/eclipse/che/blob/33107440b2eae0f2e5d2f4468e87abd56fffa391/agents/exec/src/main/resources/org.eclipse.che.exec.script.sh#L191-L195

I'm not sure but. Were command line options in BusyBox changed...?

**Comment by ghost** [comment]
It used to work before. Maybe wget package was updated.

**Comment by monaka** [comment]
I found it was fixed on 9month before.  https://github.com/mirror/busybox/commit/2972e2c4acb9c46a8cc05c857acac2b3d439bf69

**Comment by Ohrimenko1988** [comment]
Duplicated https://github.com/codenvy/codenvy/issues/2269

**Comment by monaka** [comment]
@Ohrimenko1988 I agree they are same issue but Codenvy and Che has separarated product/repository right?

**Comment by ghost** [comment]
Yes. You are welcome to follow Che issue though.
