### ISSUE TITLE
Unable to launch Exec Agent in workspace when CHE_DOCKER_DAEMON__URL is set to remote host - AWS EC2

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#5449]
Scenario:
EC2 Instance1: Che-Server
       External IP: 13.X.X.169
       Internal IP:  172.31.9.201

EC2 Instance2: Docker Daemon  & Workspaces
       External IP: 13.X.X.116
       Internal IP:  172.31.8.50

I use the following command to start eclipse che

docker run -it --rm  -e CHE_DOCKER_IP_EXTERNAL=13.X.X.169 -e CHE_DOCKER_DAEMON__URL=http://13.X.X.116:2375 -v /var/run/docker.sock:/var/run/docker.sock -v /opt/data:/data eclipse/che:5.13.0 start --debug

Eclipse Che setup goes through fine,  I'm able to access the che dashboard at http://13.X.X.169:8080

However, when I launch any workspace,  I get the following error pop-up

Error when starting agent
Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment 'default' failed. Error: Fail launching agent Exec-agent. Workspace ID:workspacehpdfbe9zsilur0ui

The logs from machine:

[DOCKER] latest: Pulling from eclipse/ubuntu_jdk8 
[DOCKER] Digest: sha256:5a67c924f0ca4086897b29d2920579857f035b304a438b50805b6de58a2540bd 
[DOCKER] Status: Image is up to date for eclipse/ubuntu_jdk8:latest 
[STDOUT] Exec Agent binary is downloaded remotely
[STDERR] 
[STDERR] gzip: stdin: unexpected end of file
[STDERR] tar: Child returned status 1
[STDERR] tar: Error is not recoverable: exiting now
[STDERR] /bin/sh: 216: /home/user/che/exec-agent/che-exec-agent: not found

My thoughts:
The workspace creation is successful, I can see the workspace being created on running docker ps in EC2 Instance2 i.e. 13.X.X.116
But, all the libraries required to launch the wsagents are located in EC2 Instance1 i.e. 13.X.X.169 under /opt/data/instance/data/lib, hence the STDOUT "Exec Agent binary is downloaded remotely", 
could it be that agents libraries are being download into EC2 Instance2 i.e. 13.X.X.116 through CURL & workspace creation is being timed out or any firewall rules blocking the execution or such a setup of che doesn't work ?

I'd glad if you could help in finding the right answer.

**Reproduction Steps:**

Mentioned above.

**OS and version:**    
Ubuntu-Xenial 16.04

**Diagnostics:** 

INFO: (che cli): 5.13.0 - using docker 17.03.1-ce / native

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:5.13.0
 Version:        5.13.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /opt/data
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.13.0
 CHE_HOST:       172.31.9.201
 CHE_INSTANCE:   /opt/data/instance
 CHE_CONFIG:     /opt/data
 CHE_BACKUP:     /opt/data/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   172.31.9.201
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.13.0
 IMAGE_CHE=eclipse/che-server:5.13.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.13.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.13.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.13.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.13.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.13.0
che.env:
 CHE_HOST=172.31.9.201
 CHE_SINGLE_PORT=false

**Comment by hbhargav** [comment]
I have managed to get past the above issue by manually updating "che-host" to "13.X.X.169" in che.properties 
i.e.
che.workspace.che_server_endpoint=http://che-host:${SERVER_PORT}/wsmaster/api
to
che.workspace.che_server_endpoint=http://13.X.X.169:${SERVER_PORT}/wsmaster/api

Now, I hit another road block 

2017-06-23 12:49:10,405[aceSharedPool-2]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 127]   - Fail pinging ws agent with http://172.31.9.201:33182/api/ url in workspace14ppkle3cnwgsdpp workspace in machine9q9mq3g4qvmd2fcf machine on 13.X.X.116 node.
2017-06-23 12:49:11,198[aceSharedPool-2]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.

I'm not sure why Che-Server is pinging ws agent on http://172.31.9.201:33182/api/ it should instead ping on http://13.X.X.116:33182/api/.

Is there any property that I can set to have che-server ping ws agent on a specific IP address ?

**Comment by ghost** [comment]
-e "CHE_HOST=$IP" is the right env. However, you are likely to run into other issues, such as persisting data. Can you share workspace start logs? Did the workspace agent start?

**Comment by hbhargav** [comment]
Hello @eivantsov 

Specifying -e CHE_HOST=13.X.X.169 doesn't help, che-host in /etc/hosts for workspace container will be mapped to docker network ip of the Che Server running under 13.X.X.169 
172.17.0.4	che-host

Since the containers are running on bridge network & the scope of bridge is 'local', workspace container cannot access che server on 172.17.0.4.

After manually updating "che-host" to "13.X.X.169" in che.properties
Workspace start log :
2017-06-27 08:35:42,452[nio-8080-exec-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 897]    - Workspace 'che/wksp-nky8' with id 'workspaceez1crwcgp8o9ylh3' created by user 'che'
2017-06-27 08:39:33,043[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.exec' agent at workspace workspaceez1crwcgp8o9ylh3
2017-06-27 08:39:36,619[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.terminal' agent at workspace workspaceez1crwcgp8o9ylh3
2017-06-27 08:39:41,940[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspaceez1crwcgp8o9ylh3
2017-06-27 08:42:47,966[aceSharedPool-0]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 127]   - Fail pinging ws agent with http://172.31.9.201:33382/api/ url in workspaceez1crwcgp8o9ylh3 workspace in machinedzhpauukkar752y5 machine on 13.126.94.116 node.
2017-06-27 08:42:48,549[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
	at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:132)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:695)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:819)
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:268)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:712)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:977)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:941)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-06-27 08:43:44,785[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 377]    - Workspace 'workspaceez1crwcgp8o9ylh3' removed by user 'che'

As you can see from the above logs launching of ws-agent fails. The reason being che server is pinging ws-agent on http://172.31.9.201:33382/api/, which is the wrong IP address of ws-agent it should have ideally performed a ping on http://13.X.X.116:33382/api/

On further debugging the issue, I found that the URL's for launching agents are generated using getServers() function under the MachineRuntimeInfo interface.

The MachineRuntimeInfo Servers Map is built on calling MachineRuntimeInfoImpl.doGetRuntime()
 In here, dockerMachineFactory.createMetadata(docker.inspectContainer(container),
                                                                                  getConfig(),
                                                                                  node.getHost())

node.getHost() - 13.X.X.116 is the value passed into this function

However, on completion on createMetadata the getServers() function is contains the internal IP address of Che Server i.e. 172.31.9.201 for all the agents instead of 13.X.X.116 the external IP address of the Workspace, which is passed in node.getHost()

**Comment by ghost** [comment]
@hbhargav in any case, the ephemeral port range should be opened, even if Che server is using an internal IP to ping ws agent.

> che-host in /etc/hosts

This is che-server IP that ws-agent uses to reach ws-master. And it does reach it since it starts OK. It is server that cannot reach agent. Checking the ephemeral port range is definitely a way to go.

**Comment by hbhargav** [comment]
@eivantsov Your statement is correct that "Server is unable to reach agent", I did check the ephemeral port range & all the ports are open.
I believe this issue is arising from the following piece of code

@Inject
    public DefaultServerEvaluationStrategy(@Nullable @Named("che.docker.ip") String internalAddress,
                                           @Nullable @Named("che.docker.ip.external") String externalAddress) {
        this.internalAddressProperty = internalAddress;
        this.externalAddressProperty = externalAddress;
    }

The value of internalAddress (che.docker.ip) is resolved to the "172.31.9.201".
If I hardcode this value to "13.X.X.116", everything works fine, The workspace is running, projects get loaded & I'm able to run the commands as well.

I did pass the CHE_DOCKER_IP & CHE_DOCKER_IP_EXTERNAL as environment variables during start but @Named("che.docker.ip") is not picking it up, while @Named("che.docker.ip.external") is being picked up.

I did try manually updating the che.properties file as well, but dint help.

**Comment by ghost** [comment]
`CHE_DOCKER_IP_EXTERNAL` is used by the client ie your browser.

Don;t you think it is weird that two AWS nodes cannot reach each other using an internal IP?

**Comment by hbhargav** [comment]
You're right in saying AWS nodes can reach each other using Internal IP

Let me explain the issue again

172.31.9.201 (External IP is 13.X.X.169) is the internal IP of the node running Che Server & 172.31.8.50(External IP is 13.X.X.116) is the internal IP of the node running the workspace.

Che Logs:
2017-06-27 08:42:47,966[aceSharedPool-0] [ERROR] [o.e.c.a.agent.WsAgentLauncher 127] - Fail pinging ws agent with http://172.31.9.201:33382/api/ url in workspaceez1crwcgp8o9ylh3 workspace in machinedzhpauukkar752y5 machine on 13.126.94.116 node.


The failure point being che server(172.31.9.201) is pinging ws-agent on http://172.31.9.201:33382/api/, which is the wrong IP address of ws-agent it should have ideally performed a ping on http://13.X.X.116:33382/api/ OR on http://172.31.8.50:33382/api/, which is where the workspace is running.

**Comment by ghost** [comment]
@hbhargav what is your run syntax once again?

**Comment by hbhargav** [comment]
docker run -it --rm  -e CHE_HOST=13.X.X.169 -e CHE_DOCKER_IP=13.X.X.116 -e CHE_DOCKER_IP_EXTERNAL=13.X.X.116 -e CHE_WORKSPACE_HOSTS=che-host:13.X.X.169            -e CHE_DOCKER_DAEMON__URL=http://13.X.X.116:2375 
-v /var/run/docker.sock:/var/run/docker.sock -v /opt/data:/data eclipse/che:5.13.0 start --debug

**Comment by hbhargav** [comment]
13.X.X.169 - Che Server
13.X.X.116 - Workspace

**Comment by ghost** [comment]
Can you run `docker ps` on 13.X.X.169?

**Comment by hbhargav** [comment]
bc3b22c5adee        eclipse/che-server:5.13.0   "/entrypoint.sh"    4 minutes ago       Up 4 minutes 
0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp   che

**Comment by hbhargav** [comment]
docker ps on 13.X.X.116

78cd5c1ae2a7        eclipse-che/workspace8yzqsujwfcxjrk90_machinemx247rs3e297lj9p_che_dev-machine   "/home/user/entryp..."   4 seconds ago       Up 3 seconds        0.0.0.0:34025->22/tcp, 0.0.0.0:34024->4401/tcp, 0.0.0.0:34023->4403/tcp, 0.0.0.0:34022->4411/tcp, 0.0.0.0:34021->4412/tcp, 0.0.0.0:34020->8000/tcp, 0.0.0.0:34019->8080/tcp, 0.0.0.0:34018->9876/tcp   workspace8yzqsujwfcxjrk90_machinemx247rs3e297lj9p_che_dev-machine

**Comment by ghost** [comment]
@hbhargav reproduced it with two nodes. Even though Che is singe server, it looks like a bug here. I will update the issue with more findings.

**Comment by hbhargav** [comment]
Hi @eivantsov 
I'm guessing the issue is due to CHE_IP overriding the value for CHE_DOCKER_IP passed during run command or set in properties file.

if you look at the che/entrypoint.sh 

#CHE_DOCKER_IP is used internally by Che to set its IP address
  if [[ -n "${CHE_IP}" ]]; then
    export CHE_DOCKER_IP="${CHE_IP}"
  fi

Here, CHE_IP (which is believe is figured out during docker run) is actually set as the value for CHE_DOCKER_IP, hence not matter where I set the value for CHE_DOCKER_IP (passed during run command or update the properties file) its not picked up.

I may be wrong in my analysis.

**Comment by ghost** [comment]
Yes, same conclusion on my side. Testing changes and issuing a PR soon

**Comment by ghost** [comment]
@hbhargav try a nightly tag tomorrow. Just make sure you use a different local data dir.

**Comment by hbhargav** [comment]
@eivantsov Thanks.. I will give it a try tomorrow.

**Comment by hbhargav** [comment]
@eivantsov Tested the nightly build. It works !
