### ISSUE TITLE
Agents descriptions are not consistent.

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#5452]
AGENTS
1. The agent names are not consistent.  They should be:
a) "First second",not "First-second", "First-Second", or "First Second"
b) There is no need to add "agent" in the name, so it's "Git" not "Git Agent" or "Exec Agent"

**Comment by slemeur** [comment]
@vkuznyetsov https://github.com/eclipse/che/issues/5450 :)

**Comment by slemeur** [comment]
I'm going to close #5450 since you already start to track this one.
