### ISSUE TITLE
Tune dashboard for a long agent's description.

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#5453]
1. Git agent should be activated by default.
2.  If we need more details on what the agent does with a long description, we should have a hover help message where we can then provide docs-like explanations.
![codenvy dashboard wksp vlvq](https://user-images.githubusercontent.com/2101815/27483053-7d1ed274-582c-11e7-975c-25157a58fcc5.png)

**Comment by vkuznyetsov** [comment]
related to https://github.com/eclipse/che/issues/5452

**Comment by ashumilova** [comment]
Fixed by new design
