### ISSUE TITLE
Redesign workspace overview page

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5458]
#### Workspace Overview
![1 - workspace details - overview](https://user-images.githubusercontent.com/1636769/27130582-31ef50de-5107-11e7-98b3-454e38b1d07b.png)

**Comment by olexii4** [comment]
![selection_004](https://user-images.githubusercontent.com/6310786/28355063-20b15248-6c6b-11e7-93f8-3b9a251f7053.png)
