### ISSUE TITLE
Create widget for button with menu

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5460]
Need to create widget for the button with dropdown menu:
![image](https://user-images.githubusercontent.com/1611939/27508150-fe8297fe-58e7-11e7-9de8-265860fdbc35.png)

**Comment by ashumilova** [comment]
@slemeur can you please attach the dropdown mockup?

**Comment by slemeur** [comment]
Here you are:
![screen shot 2017-06-26 at 09 23 30](https://user-images.githubusercontent.com/1636769/27528536-29731d84-5a51-11e7-9a68-c7f5d483c592.png)

**Comment by olexii4** [comment]
![selection_010](https://user-images.githubusercontent.com/6310786/28426218-3cd1bc4a-6d7b-11e7-9dba-0e6784ff26da.png)

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/5451/commits/ced7c994206ba94c3698cd957fda171e17c3cbfa
