### ISSUE TITLE
The warning message is not informative after creating a factory with the same name

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5462]
**Reproduction Steps:**
Create a factory
Try to create a new factory with same name

**Expected behavior:**
There is a notification about the factory with this name exist

**Observed behavior:**
The warning message is not informative

**Che version:** 5.14.0-SNAPSHOT
**OS and version:** Fedora 25
![screenshot from 2017-06-26 10-58-40](https://user-images.githubusercontent.com/7760565/27529772-7ab38fbe-5a5e-11e7-8091-24563a9efd17.png)

![out-4](https://user-images.githubusercontent.com/7760565/27529608-d290633e-5a5d-11e7-8ad4-0a77f4b79395.gif)

**Comment by ghost** [comment]
Still an issue in 5.15-SNAPSHOT
