### ISSUE TITLE
ESLint Language server

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5463]
since Orion, by default uses JSHint for linting, it would be nice to have a ESLint service.
Visual Studio Code sports the following functionality by an extension and running it as a Language Server.

#### Refrences 

-  [The Official repository for the ESLint extension](https://github.com/Microsoft/vscode-eslint)

### How does this work?

the ESLint extension referenced above, queries to a local ESLint instance. The package somehow has a ``api.js`` that is used by the extension to communicate with the server component of the extension which brings real-time quick-actions, analysis, Intellisense, etc.

**Comment by slemeur** [comment]
Linking with https://github.com/eclipse/che/issues/5146
