### ISSUE TITLE
Eliminate necessity for the extensions to depend on the IDE App module

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#5464]
There are about 30 IDE extensions, in the CHE/Codenvy assemblies, which must depend on the `IDE App` (`che-core-ide-app` module) in order to use just a few interfaces/classes. Like  `org.eclipse.che.ide.CoreLocalizationConstant`, 
`org.eclipse.che.ide.newresource.AbstractNewResourceAction`, etc. Having a such dependency really is a bad practice for the IDE extensions.

The goal of this task is to eliminate the necessity for the IDE extensions to depend on the `che-core-ide-app` module. This may require moving some interfaces/classes from `che-core-ide-app` to `che-core-ide-api` or improve IDE API in some way.

**Comment by gazarenkov** [comment]
Totally agree, let's clean framework and make a real distinction between framework and app on top.

**Comment by sr229** [comment]
+1 on this since Che aims for modularization, this is a step forward

**Comment by skabashnyuk** [comment]
@vparfonov what are the state of this issue?

**Comment by gazarenkov** [comment]
@azatsarynnyy @vparfonov 
Let's review and try to find a "golden mean" (not putting a lot of effort).
Indeed, let's do not consider a "refactoring" but be dependent on other module just due to a couple of constants does not look that reasonable.
Thoughts?

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
