### ISSUE TITLE
What's a runtime?

### ISSUE THREAD

**Issue by robbirob** [eclipse-che/che#5467]
Hi,

I am currently reading the Docs again and i am having a little trouble to understand what the word _runtime_ is supposed to mean. 
There is the following paragraph in the "Runtime Recipes" section which confuses me:

> Workspaces can have a single runtime or multiple runtimes. Che uses Docker, though Che could handle runtimes other than Docker, to create runtime(s) from Dockerfiles for a single-container runtime, or compose files to create single-container/multi-container runtime(s).

"Che could handle runtimes other than Docker" suggests that Docker itself is the runtime, but the next part ("to create runtime(s) from Dockerfiles") tells me, that i am creating runtimes with Dockerfiles/Composefiles. From my understanding, Dockerfiles create Runtime-Machines not the runtimes itself.

What is a runtime in this context?

Thank you.

**Comment by benoitf** [comment]
hello,

@robbirob In the sentence 

> Workspaces can have a single runtime or multiple runtimes.
runtime = container

single runtime = single container = Dockerfile
multiple runtimes = multiple containers = Docker Compose file

in the sentence 

> Che could handle runtimes other than Docker

Runtime here means that we can plug something else than docker.
We could use a "localhost implementation of Machine" or delegates to k8s, etc.

**Comment by robbirob** [comment]
That you for the clarification, i suspected that, but was'nt sure.
