### ISSUE TITLE
CHE-629 Remove Help menu from left sidebar

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#547]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-629
Reporter:  Stévan Le Meur
Description: We need to remove the Help menu from the left siderbar in dashboard.

Since we have the "Community" button in the footer, this is not needed anymore.

(+ CODENVY-167)

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/528bdf89d7541cc5348fff1fe987b50e001f2dd5
