### ISSUE TITLE
The Save button in the Workspace config tab appears only after adding second symbol to config

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5477]
**Reproduction Steps:**
Create a workspace and click on the Workspace config tab
Add one symbol to config

**Expected behavior:**
The Save button appeared

**Observed behavior:**
The Save button will appears only after adding second symbol

**Che version:** 5.14.0-SNAPSHOT
**OS and version:** Fedora 25
**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![factory-1](https://user-images.githubusercontent.com/7760565/27585214-f36417c2-5b43-11e7-91c7-060f01cb31cf.gif)

**Comment by bdshadow** [comment]
@SkorikSergey @ashumilova the issue can be closed

**Comment by SkorikSergey** [comment]
Fixed.

**Comment by ashumilova** [comment]
@bdshadow Thank you
