### ISSUE TITLE
pytest added along side JUnit Test menu

### ISSUE THREAD

**Issue by bryanSME** [eclipse-che/che#5478]
Is there any plan to add "pytest" along side JUnit?  

Two places to find what I'm talking about are:
1) In "Projects Explorer", right click on class/file, seconds one down is "Run Test"
2) From the menu tab along the top, "Run" last item on the bottom is "Test".

**Comment by ghost** [comment]
@bryanSME there are no immediate plans. However, it does look like a good feature for the python plugin.

**Comment by gorkem** [comment]
Another one #5293

**Comment by gorkem** [comment]
Closing since Che 6 is not actively developed and on Che 7 we depend on extensions to bring this functionality.
