### ISSUE TITLE
Error messages in console after start php language server

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5481]
**Reproduction Steps:**
- Create php project
- Open php file
- Wait until language server will be started
- Pay attention to "dev-machine" console

**Expected Behavior:**
Message about successful language server start

**Observed Behavior:**
Error messages are displayed

**OS and version:**    
CHE 5.14.0 ; Fedora 25 ; Chrome 59.0

**Attachment**
![eclipse che wksp fnyp](https://user-images.githubusercontent.com/22724619/27591859-a6eef6d8-5b5b-11e7-8fed-49cf433f143f.png)

**Comment by slemeur** [comment]
@vparfonov any idea about this issue?

**Comment by riuvshin** [comment]
Im not sure that this is an issue, Idk why "info" output we show as ERROR but it looks good.

**Comment by ghost** [comment]
It does look ok, just stdout becomes stderr for some reason.

**Comment by Ohrimenko1988** [comment]
Log level was changed to "INFO"
