### ISSUE TITLE
Create stacks oriented commands

### ISSUE THREAD

**Issue by mlabuda** [eclipse-che/che#5486]
Pasted from https://github.com/redhat-developer/rh-che/issues/119:

At the moment we have quite general commands among stacks. We have e.g. "mvn clean install" or "java -jar target/*.jar" etc. We could have more technology oriented commands.

For example, vertx booster has maven vertx plugin with goal vertx:run. This would improve UX, because now, user has to at first build, then run. With vertx:run, it is one-click-to-go command.

Same could apply for other stacks as well (springboot, wildfly...).

**Comment by gorkem** [comment]
Closing as devfile gives this capability
