### ISSUE TITLE
JDT validation does not work on some classes

### ISSUE THREAD

**Issue by mlabuda** [eclipse-che/che#5488]
Pasted from https://issues.jboss.org/browse/CHE-208

Working with https://github.com/fabric8-quickstarts/vertx-web and either java-default or vert.x stack, I dont get any validation of test class SimpleWebVerticleTest located in src/test/java/io/vertx/example. Even if I do compilation error, nothing happens.

Validation on class src/main/java/io/vertx/example/SimpleWebVerticle works fine, after some time there appear a validation error mark on uncompilable changes.

**Reproduction Steps:**
EXEC: Create a new workspace based on vert.x or java-default stack.
EXEC: Import a project https://github.com/fabric8-quickstarts/vertx-web
EXEC: In test class io.vertx.example.SimpleWebVerticleTest do some uncompilable changes. Wait some time.
RESULT: There is no error marker.
EXPECTED RESULT: There should be error marker.

**Comment by TylerJewell** [comment]
@mlabuda - when you post issues, please apply appropriate labels.  You can see the definitions and our processes in the wiki.  

If you are unsure of a bug's severity, the TL will assign it.

**Comment by gorkem** [comment]
@TylerJewell Are you aware that non-committers do not have access to labels?

**Comment by TylerJewell** [comment]
Yes yes of course.  Brain fart that I forgot Marlan wasn't a committer yet.

**Comment by ghost** [comment]
Bug confirmed. Test Class has no Java features at all
