### ISSUE TITLE
Node.js linter seems to only look for modules defined in package.json

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5491]
Seems that che's module resolver only checks on package.json for modules which results in false-positives for missing modules.

The following screenshot is a statement referencing a local non-npm module

![image](https://user-images.githubusercontent.com/14976516/27672633-c9eca576-5cce-11e7-9f35-32bd46a44da8.png)

**OS and version:**    
Windows 7 on Codenvy 5.13.0

**Comment by sr229** [comment]
Additional Notes: It would be nice if it can also get types from local JS files other than modules.

**Comment by ghost** [comment]
@sr229 the problem is clear, but just a side note - it is not Che or node-js plugin that does that, but Orion editor that is used as is.

Does appending .js extension help?

Meanwhile, I will give it a try with orionhub.org.

**Comment by sr229** [comment]
thanks for triaging, yeah it seems to be a hassle because local files aren't treated as proper modules without appending ``.js``.

VS Code's Monaco seems to be doing the job pretty well at detecting local modules. Orion seems to suffer from that syntax.

**Comment by ghost** [comment]
Closing the issue. We do have an issue to use Monaco editor, though there is no ETA or priority for it.
