### ISSUE TITLE
After split some file in the few editor tabs, autoSave marker updates only for active editor

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#5497]
After split  editor in the few tabs  autoSave marker will be updated only for active editor.

**Reproduction Steps:**
1. Open some file from project.
2. Open context menu on the editor tab by right mouse button.
3. Click on the item: "Split panel in two rows" (or  "Split panel in two cols"). The same file will be opened in the two rows (or columns) in the two editors.
4. Change file. 

Actual result: content was changes in the two editors synchronously -  it's a fine and correct, but only in the active editor "autosave marker" ("*" in the editor title) was updated and dissapeared. On the second editor "autosave" marker still exists. And If you try to close file on the tab where is still exist marker you will get window "Close" with proposal to save file content, but this content was already saved with help autosave in the active editor.

Expected result: autosave marker should dissapear on the both editors.

![capture image](https://user-images.githubusercontent.com/6873095/27683204-df6fd72a-5ccd-11e7-9847-4b0de1cd780c.png)

**OS and version:**    
Fedora 25
**CHE version: **
5.14.0-SNAPSHOT

**Comment by AndrienkoAleksandr** [comment]
![capture image](https://user-images.githubusercontent.com/6873095/27683191-d64aafbc-5ccd-11e7-87fd-2ca1f7f23acc.png)

**Comment by ghost** [comment]
Yeah, clicking in this faulty editor area makes `*` go away though.
