### ISSUE TITLE
Start Che with customized assembly failed

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5498]
Hi, I am a beginner about Che Extension. I am trying to follow the guide https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html
to test how to cutomize assembly. But I always get error when opening Che page. 

Here are my steps, is there any additional steps needed?

1. generate build and select `2) plugin-menu-archetype          - Assembly with IDE extension to customize menu`
```
docker run -it --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /data/Che/test/archetype:/archetype \
  -v /data/Che/test/data:/data \
  -v /root/.m2/repository:/m2 \
    eclipse/che-cli:5.13.0 \
      archetype generate
```
2. build by archetype:                          
```
docker run -it --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /data/Che/test/archetype:/archetype \
  -v /data/Che/test/data:/data \
  -v /root/.m2/repository:/m2 \
    eclipse/che-cli:5.13.0 archetype build 
```
3. start server   
```
docker run -it --rm --name run-che \
    -e CHE_HOST=<my_ip> \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /data/Che/test/data:/data \
    -v /data/Che/test/archetype/assembly/assembly-che/assembly-main/target/eclipse-che-5.13.0/eclipse-che-5.13.0:/assembly \
    eclipse/che:5.13.0 start --skip:nightly  
```
But I always get error in browser and the pages is always black.
![screen shot 2017-06-29 at 6 38 48 pm](https://user-images.githubusercontent.com/10006307/27683975-9d7f7398-5cfa-11e7-900e-1ea732ee3c82.png)

**Comment by skabashnyuk** [comment]
Is something not working or you just worried about an error in browser console?

**Comment by TylerJewell** [comment]
Looks like he says that the page is always black and never loads.

**Comment by qi-min** [comment]
Yes, the page is always black and nothing else is displayed.

**Comment by ghost** [comment]
@m7luffy can you run a standard Che image? Just drop `-v /data/Che/test/archetype/assembly/assembly-che/assembly-main/target/eclipse-che-5.13.0/eclipse-che-5.13.0:/assembly`

Also, can you provide server logs? `docker logs -f che`

**Comment by qi-min** [comment]
@eivantsov I tried archetype with template 'plugin-menu-archetype' several times, and always got the same error result. Today I try the same commands with template 'plugin-json-archetype',  the Che page can be opened correctly. After that I re-try to generate and build template 'plugin-menu-archetype' again, it works now. So I am not sure why it did not work before, seems building template 'plugin-json-archetype' make some impact.

Another question is what is the recommended way to provide extension to Che. I see the guide in sample plugin which add the dependency to assembly directly and run Che with :/repo to apply the extensions. And archetype also provide a way to build and run Che by che-cli. What are the differences between these two ways?

**Comment by TylerJewell** [comment]
@mkuznyetsov - please see the specific use case. We may want to consider this in the next sprint if our archetype if failing for a certain use case.

**Comment by ghost** [comment]
@TylerJewell i don't see any problem at the moment and any particular use case. Plugin menu archetype worked for me from take one. I don't think we have enough details in this issue to qualify it as a bug.

**Comment by TylerJewell** [comment]
Ok - happy to leave it to you if you want to change the labels and downgrade this to a question, waiting for us to get double verification.

It seemed odd that one archetype would work while another would not on the user's machine.

**Comment by m7luffy** [comment]
@eivantsov I see the error again after I make some changes to the POM and run mvn clean install again.  
Here is the build result:
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:31 min
[INFO] Finished at: 2017-07-04T18:59:04-07:00
[INFO] Final Memory: 87M/1453M
[INFO] ------------------------------------------------------------------------
```

And there is no error in log. Here are last lines in log:
```
2017-07-05 02:01:37,241[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.7.0.1 - 1__add_factory.sql
2017-07-05 02:01:37,305[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.7.0.2 - 2__remove_match_policy.sql
2017-07-05 02:01:37,324[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "PUBLIC" to version 5.8.0.1 - 1__add_foreigh_key_indexes.sql
2017-07-05 02:01:37,343[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Successfully applied 10 migrations to schema "PUBLIC" (execution time 00:00.393s).
2017-07-05 02:01:39,378[ted-scheduler-1]  [INFO ] [ockerAbandonedResourcesCleaner 124]  - List containers registered in the api: []
2017-07-05 02:01:39,709[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /assembly/tomcat/webapps/wsmaster.war has finished in 10,402 ms
2017-07-05 02:01:39,715[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-8080]
2017-07-05 02:01:39,733[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 13140 ms
```

Is there anyway can get more details which can help figure what happens?

**Comment by ghost** [comment]
@TylerJewell I tried a few archetypes and both worked for me. It looks like dashboard war was never deployed in @m7luffy's case. Not sure why that happened.
