### ISSUE TITLE
Will it be possible each of the new version can be clean up the docker images ID?

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#5502]
Below it the multiple version of Eclipse Che, but with the same Images ID, and this will have a fall down that eating up some of the hard disk space (for current only three version, if let say 10 new version, than it will become a problem)

![selection_032](https://user-images.githubusercontent.com/1939446/27702092-8c674f8c-5d35-11e7-955e-639edf74a24a.jpg)

**Comment by gorkem** [comment]
I do not believe this is such a large issue since we dropped docker support, closing
