### ISSUE TITLE
VS Code debug protocol support on Che

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#5508]
Investigate what are the requirements, tasks areas and impediments to integrate VS Code debug protocol [1] to Che. 
Create more detailed tasks on how to continue.
[1] https://github.com/Microsoft/vscode-debugadapter-node

**Comment by jonahgraham** [comment]
At EclipseCon Europe we (Kichwa Coders) demonstrated debug servers running in Che based on VS Code debug protocol. We will soon be providing a PR for Che to add this support.

**Comment by jonahgraham** [comment]
I posted a question on [che-dev](https://dev.eclipse.org/mhonarc/lists/che-dev/msg02454.html) asking about upgrading to 0.4.0 of LSP4J. That upgrade is a dep of this bug. Hopefully it is on someone's todo list :-)

**Comment by skabashnyuk** [comment]
@tolusha @tsmaeder are you interested in this issue?

**Comment by gorkem** [comment]
Closing as this is done for Che 7 and Che 6 is not active anymore
