### ISSUE TITLE
Endless stream of notifications about external file modification

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#5515]
Seems like in some situations we get an endless stream of notifications when edit files. According to @asacamano [comment](https://github.com/eclipse/che/issues/5215#issuecomment-312365895) we have the following: 

> Just upgraded to 5.14 yesterday - and I saw similar behavior creating a new file and editing it. Is this the same issue?
>
> Steps to reproduce:
>
> 1. Create a workspace with an empty project (e.g. Ubuntu workspace, blank project)
> 2. Create a new file - docker-compose.yml, or edit the README file.
> 3. Wait for the file to open in the editor.
> Result
>
> An (apparently) endless stream of "External Operation: File docker-compose.tml is updated." notifications.

**Comment by RomanNikitenko** [comment]
@asacamano Could you provide some details or record a small video - I can not reproduce endless stream of notifications - I get one notification on one save file content...
- Do you create workspace from Default Blank Stack?
- Do you edit README file from terminal and next open this one in the editor or you have opened README file in editor and change it from terminal for example?

**Comment by sokraflex** [comment]
I am experiencing very similar errors and tried to make a gif, but could not reproduce it completely.

All I can say is:
 - When I change a file and save it, Che saves it.
 - After saving the file, Che changes its state back to "changed", although no content was added or removed to the file.
 - In combination with the "Auto-Saving" feature, this leads Che to save the file again, change it to changed, save it, make it changed, save it, and so on, in an endless loop.
 - I was unable to reproduce this behaviour with any newly created file. However, on every single file from my 2 projects, that have been cloned using git-cli, the issue appears.
 - My 2 projects are nodejs-based, one of them using cordova. However, I don't think the bug has anything to do with the project's technology.

Could git somehow cause the issue?
We have a pretty standard setup (as far as I can tell), the only thing is, we installed git using `apt-get install` and cloned our repositories using `$ git clone https://....git`, because the built-in features did not work for us right away.

We're using an own stack (in order to use Node.JS 6), but I don't think that this might have anything to do with the issue. However, for clearity, the following is the dockerfile we use to create our stack:

```
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs git build-essential

# setup folders
RUN mkdir /projects
WORKDIR /projects

# setup server environment
EXPOSE 3000

ENV DEBIAN_FRONTEND teletype
```

**Comment by davidwindell** [comment]
As far as I can tell, this issue started to affect us too around v5.11/v5.12 so we are stuck back on 5.10.

@SargTex are you able to pinpoint it back to those releases too?

**Comment by sokraflex** [comment]
I'm new to eclipse and only started using it in 5.14.0, and in that version we're experiencing the issue.
However, I will try 5.10 out, maybe it fixes it at least for us temporarily.

Could it be, that this is a client-related issue? I just sent a friend the link to my workspace and told him to change and save a specific file where I had the problems, the result:
 - Using Ctrl + S does nothing for him
 - Saving the file over the save-button saves the file, and it does not become marked as "changed" again.

I'm using chrome 59.0.3071.115, my friend Firefox 54.0.1, both 64-bit. However, when I tried it using Firefox, I experienced the same issues as in chrome.

**Comment by sokraflex** [comment]
@davidwindell I can confirm this bug does not occur in 5.10.0.

However, it does not seem like 5.10.0 did mark files as "changed" at all: When I edit a file and change a few lines, and not save it, it is not marked as "changed" or "unsaved" or anything like that - the little blue asterisk next to the filename indicating that just does not show up (using the chrome).

So, 5.10.0 can be considered to be a workaround to this bug.

At least it fixes it for my current usage, so thanks a lot 👍

**Comment by davidwindell** [comment]
@SargTeX could you just check that it's broken in 5.11 now? Then at least we can agree on where it was introduced :+1:

**Comment by sokraflex** [comment]
@davidwindell Unfortunately, I can not. It does work in 5.11.0 as well, and the "changed"-state is not introduced in 5.11.0 as well, the asterisk does not show up.

/EDIT: Oh, nevermind - the error shows up. I get one notification after another. However, the "changed"-state is at least not graphically introduced in 5.11.0.

**Comment by davidwindell** [comment]
@SargTeX great. thanks for checking. So the issue was first introduced in 5.11. Fingers crossed!

**Comment by asacamano** [comment]
@RomanNikitenko 

With apologies for the clumsy use of the screencast software - you can see the effect at https://youtu.be/C6Rk8LXcx4I .

This time it seemed to take a moment to start happening, whereas in the past it was faster.

I also had been using the "Ubuntu" workspace, but used the "Blank" version (because not all the templates were visible, likely because I set my screen resolution so low in order to record the screencast.).

**Comment by musienko-maxim** [comment]
Can you provide more information about environment, where CHE instance has been run? Yesterday QA team tried to reproduce this bug. We did different usecases about 1 hour but filewatcher worked properly. I guess that problem may reproduces in specific environment. On this behavior may influence many factors (mounting of data, internet connection and etc.). We should clarify this details for reproducing the issue

**Comment by davidwindell** [comment]
@musienko-maxim we can reproduce this reliably from 5.11 up. Our setup is running Che via `eclipse/che-server` behind an Nginx proxy and connecting remotely. Could it be the mounting of data with Docker or a remote connection - how does the code work that triggers the message i.e. what is it looking for?

**Comment by asacamano** [comment]
As for my use case - I'm running on GCE:

Host env:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

$ uname -a
Linux dev-box-2 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ docker-compose -v
docker-compose version 1.11.2, build dfed245
```

Running che using `docker-compose run che start`
```
version: "3.1"

services:
  che:
    image: eclipse/che:5.14.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./chedata:/data
    environment:
      - CHE_HOST=192.168.8.8
```

Browser is 
```
Google Chrome	58.0.3029.140 (Official Build) (32-bit)
Revision	0
Platform	9334.72.0 (Official Build) stable-channel kevin
Firmware Version	Google_Kevin.8785.178.0
ARC	4015103
JavaScript	V8 5.8.283.38
```

**Comment by dkulieshov** [comment]
Thanks a lot guys, looks like a real blocker. We're experiencing problems trying to reproduce it but we'll try to fix it ASAP.

**Comment by asacamano** [comment]
Thank you for digging into what is I'm sure a real pain in the neck!

**Comment by ghost** [comment]
@asacamano can you run ls -la in `./chedata/instance/data/workspaces/ws-name/project-name` before and after changes? Ideally, before those external change popups show up.

You may also periodically run this command to see if there are any clues there.

**Comment by asacamano** [comment]
Hi - I'm away from my computer until the 10th, but I can do that easily
when I get back.

On Jul 6, 2017 4:54 AM, "Eugene Ivantsov" <notifications@github.com> wrote:

@asacamano <https://github.com/asacamano> can you run ls -la in
./chedata/instance/data/workspaces/ws-name/project-name before and after
changes? Ideally, before those external change popups show up.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/che/issues/5515#issuecomment-313323708>, or mute
the thread

**Comment by ghost** [comment]
@asacamano my only suspicion is that the issue might be caused by the environment you use, ie GCE. I have tested Che on AWS and DigitalOcean and was never able reproduce the issue.

Would it be possible to provide temp access to the server somehow?

**Comment by sokraflex** [comment]
@eivantsov I've experienced this issue on an self-hosted environment, not on GCE, AWS or similar.

**Comment by asacamano** [comment]
@eivantsov

After opening the file but before making changes:

asacamano@dev-box-2:~/che$ ls -la chedata/instance/data/workspaces/sandbox/blank
chedata/instance/data/workspaces/sandbox/blank:
total 16
drwxr-xr-x 3 ubuntu ubuntu 4096 Jul 11 15:59 .
drwxr-xr-x 3 ubuntu root   4096 Jul 11 15:58 ..
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul 11 15:59 .che
-rw-r--r-- 1 ubuntu ubuntu  497 Jul 11 15:58 README


After editing the file, and waiting for the "Uploading file"  alert to pop up:

asacamano@dev-box-2:~/che$ ls -la chedata/instance/data/workspaces/sandbox/blank
chedata/instance/data/workspaces/sandbox/blank:
total 16
drwxr-xr-x 3 ubuntu ubuntu 4096 Jul 11 15:59 .
drwxr-xr-x 3 ubuntu root   4096 Jul 11 15:58 ..
drwxr-xr-x 2 ubuntu ubuntu 4096 Jul 11 15:59 .che
-rw-r--r-- 1 ubuntu ubuntu  547 Jul 11 16:01 README


After playing around with this a bit more - I've realized it is not endless - it seems to be between 4 alerts and 30 alerts show up.  I wonder if there is maybe some issues with the modification timestamp resolution?

**Comment by dkulieshov** [comment]
@asacamano

That sounds pretty strange as we're using hashes to avoid exactly the situation you've described. I mean even if timestamp is different but content is the same we should not get notification in the right upper corner. The steps are the following (if I remember well :D ):
- Each time server side catches an event of file modification it notifies the client but also sends a hash of file content
- Each time client is notified of file modification it compares current and previous hash values to accurately process the situation when we have timestamp modification without real content change.

So right now my assumption here is either we have a bug inside the routine responsible for those operations or for some reason client constantly receives notifications with different hashes. Or by the way it might be quite possible that there is something within the environment that you have as on our side we're unable to reproduce the use case.

FYI @eivantsov @vparfonov

**Comment by davidwindell** [comment]
@dkuleshov can we provide any useful debug information on the hashes, i.e. are they sent in any API responses so we can see if they are changing?

**Comment by dkulieshov** [comment]
@davidwindell the most simple way I guess is to check dev console in a browser, the websockets section. Server side notifications are sent in a JSON-RPC format.
The message should be something like this
```json
{
"jsonrpc":"2.0",
"method":"event:file-state-changed",
"params":{
  "type":"MODIFIED",
  "hashCode":"ec4eb96467f3194032e978d4f274414a",
  "path":"/1/main.py"
  }
}
```
While the websocket connection for codenvy.io is wss://codenvy.io/35391_node15.codenvy.io/websocket/9323731 and you should also have something similar. Please also tell me if you will find any other messages that will seem suspicious for you.

**Comment by vparfonov** [comment]
For now we have fixed not problem itself but consequences. For solving problem we don't have  decision. 
Remove **blocker** state and milestone

**Comment by davidwindell** [comment]
@vparfonov can you link me to the fixing commit?

**Comment by RomanNikitenko** [comment]
@davidwindell https://github.com/eclipse/che/commit/6bc14afaa08ba2121bb8b1001c29d6711a59aa37

**Comment by davidwindell** [comment]
Just a quick update, we don't seem to be able to reproduce this from our side anymore in the latest master although we are seeing some strange file save issues which may possibly be related in #5826
