### ISSUE TITLE
[REGRESSION] Preview feature doesn`t work

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5516]
Related with https://github.com/eclipse/che/issues/5517

**Reproduction Steps:**
- Create Java Spring project from project wizard
- Run "build and run" command
- Wait "server startup" message in console
- Click on preview button in the intelligence toolbar
- In the drop down list click on the link "ws-machine:8080"
- Pay attention to result

**Expected result:**
Link will be opened in the new window

**Actual result:**
Link doesn`t work

**OS and version:**    
Che - 5.15.0  ;  Chrome - 59.0  ; Fedora - 25

**Attachment:**
![codenvy wksp g5c3](https://user-images.githubusercontent.com/22724619/27787870-0882af74-5fef-11e7-877d-0a56875c3f47.png)

**Comment by riuvshin** [comment]
@vparfonov please take a look.

**Comment by riuvshin** [comment]
I think it is P1 regression because preview feature completely broken.

**Comment by TylerJewell** [comment]
Bumping to blocker if preview is not working at all.  No preview = no viable product.
