### ISSUE TITLE
[REGRESSION] Preview feature from the context menu doesn`t work 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5517]
Related with https://github.com/eclipse/che/issues/5516

**Reproduction Steps:**
- Create web-java-pet-clinic project from project wizard
- Expand project tree to "overview.html" item
- Open context menu on the "overview.html" item
- Click on "Preview"
- Pay attention to result

**Expected result:**
Html document will be shown like in browser

**Actual result:**
Document does not opened

**OS and version:**    
Che - 5.15.0  ;  Chrome - 59.0  ; Fedora - 25

**Attachment:**

![eclipse che wksp 0jnl](https://user-images.githubusercontent.com/22724619/27788546-c1857888-5ff1-11e7-867f-1d31a4eb4fd1.png)

**Comment by riuvshin** [comment]
@vparfonov please take a look. it seems same issue as https://github.com/eclipse/che/issues/5516

**Comment by riuvshin** [comment]
I think it is P1 regression because preview feature completely broken.

**Comment by TylerJewell** [comment]
Bumping to blocker if all preview capabilities are broken.
