### ISSUE TITLE
Does CHE Keep the editing histories of a file?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#552]
When a file is modified, does che keep the editing histories of it on the service side? And I can get them from the rest API.

I ask about this feature, because we use che for students, for their programming training. We want to find a way to know about all his changes, so we know how he/she was thinking when programming

**Comment by ghost** [comment]
There's no track of file changes on the API level. Is use of Git a suitable workaround?

**Comment by freewind** [comment]
Git might not be enough. Since the students are new to programming, they are not familiar with git, and also we want to track every tiny modifying of the files in order to find all kinds of problems, which might not be possible with git
