### ISSUE TITLE
GitHub page does not open when pull request is created (regression)

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#5521]
_I try to open GitHub page from pull request panel after creating pull request, but the GitHub page does not open._

**Reproduction Steps:**
* Import a project (e.g. https://github.com/artaleks9/pull-request-plugin-test.git)
* Open a file in the editor, do some changes and create pull request
* Try to open GitHub from pull request panel

**Expected behavior:**
* the GitHub page should open

**Observed behavior:**
* the GitHub page does not open

**Che version:** 5.15.0
**OS and version:** Fedora 25
**Docker version:** 17.03
**API docker version:** 1.27
**Che install:** Docker container  

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by riuvshin** [comment]
https://github.com/eclipse/che/issues/5516

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by vinokurig** [comment]
Must be fixed by https://github.com/eclipse/che/issues/5578
