### ISSUE TITLE
Rework Language Server plugin to avoid using Everrest based Websocket calls

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#5524]
Language Server plugin uses Everrest based Websocket calls for broadcasting events about language server initialization. See [`LanguageServerRegistry`](https://github.com/eclipse/che/blob/master/plugins/plugin-languageserver/che-plugin-languageserver-ide/src/main/java/org/eclipse/che/plugin/languageserver/ide/registry/LanguageServerRegistry.java#L168). Need to replace it with JSON-RPC.

**Comment by dkulieshov** [comment]
Seems like this bug is an impediment for this task to be properly tested  https://github.com/eclipse/che/issues/5547

**Comment by dkulieshov** [comment]
After this https://github.com/eclipse/che/commit/9f88048572795ac8dcb4c40bfff8ae5a773136b7 commit this issue seems to become outdated.

**Comment by gazarenkov** [comment]
still actual or can be closed?

**Comment by azatsarynnyy** [comment]
closed as outdated
