### ISSUE TITLE
Che somehow doesn't know which normal user account to use for container when custom username  is set.

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5525]
I created a [Codenvy Factory](https://codenvy.io/f?id=factory9vmsb0qie9v6a027) to demo this.

Apparently if the user name isn't ``user``, Che doesn't know the normal user and fallbacks to root, which is a bit irritating if you want to have custom username for the workspace container that che runs.

**OS and Version**
Codenvy 5.14.0 on Ubuntu 16.04.1 LTS

**Comment by ghost** [comment]
@sr229 you need to use the following instruction in your recipe

`USER clara`

**Comment by sr229** [comment]
even with the ``USER`` field, it seems still not to recognize it.

or I'm doing something wrong.

[this is the whole Dockerfile](https://gist.githubusercontent.com/sr229/a1b8df79a92cafbc7ec773848a6351f5/raw/43ee4bf6182866da057aefcb9a8edd3cd2be0cbc/Dockerfile)

**Comment by ghost** [comment]
@sr229 in this case ssh agent cannot start, since the way you created a user does not allow ssh connections. Can you create this use the way it is created in stack images?

https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/Dockerfile

**Comment by sr229** [comment]
@eivantsov which line does allow the SSH agent  to connect to SSH?

kinda confused since the Dockerfile is really large

**Comment by ghost** [comment]
https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/Dockerfile#L28-L32

**Comment by sr229** [comment]
Thank you so much, will close shortly after confirming it has resolved.

**Comment by sr229** [comment]
![image](https://user-images.githubusercontent.com/14976516/27912925-0f9b4704-6291-11e7-9234-491cbacc06b7.png)

I did add the following lines but this seems to pop up and put Che on a stall

**Comment by ghost** [comment]
@sr229 all you need is to have user clara not user?

**Comment by sr229** [comment]
I modified the line before I added though, I might be doing something terribly wrong in my end

will redo and retry again

**Comment by ghost** [comment]
How does your new Dockerfile look now?

**Comment by sr229** [comment]
Still waiting

(the Dockerfile is actually to test the Nodesource repository for a future PR in the dockerfiles repo in Che)

(UPDATE: Still failing 😭 )

anyways, feel free to help me out on this, I have moved the Dockerfile on its own [repo](https://github.com/sr229/test-dockerfile/tree/master)

**Comment by sr229** [comment]
marked fixed.

I forgot `openssh-server` so it kept failing
