### ISSUE TITLE
[REGRESSION] Error message is shown when try to open file

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5528]
If try to open file in the stack where this file type language server is disabled, the error message will be shown.

**Reproduction Steps:**
- Create Java project
- Create create and run json (ts, python, php) file 
- Pay attention to the screen 

**Expected result:**
File will be opened

**Observed result:**
Error message is shown and file has not opened

**OS and version:**    
Che - 5.15.0 ; Chrome - 59.0 ; Fedora - 25;

**Attachment:**
![eclipse che workspace3xndsy](https://user-images.githubusercontent.com/22724619/27819343-704eaa50-60a2-11e7-8f22-3a036d8b2ea2.png)

**Comment by riuvshin** [comment]
@vparfonov please take a look.

**Comment by tsmaeder** [comment]
This works perfectly fine once you enable the python agent in the workspace's runtime configuration.
Not a bug.

**Comment by vparfonov** [comment]
@tsmaeder If you don't mind I would like to disagree with you. It is extremely important for us to keep the ability to open any file either with LS enabled or even without it. If LS is not available for a specific file we must open it as plain text. In my opinion what you're calling not a bug I would call an obvious regression.

**Comment by riuvshin** [comment]
Definitely regression, I want to be able to open / edit any file regardless LS enabled or not, that should affect ONLY extra features like autocompletion, syntax highlight, etc.
