### ISSUE TITLE
Port stripped from request when behind a reverse proxy

### ISSUE THREAD

**Issue by lethevimlet** [eclipse-che/che#5535]
I've been working on a custom implementation of a reverse proxy filter based on Wildfly with quite a success. The idea behind the proxy is quite simple, provide a basic credential system and re-routing based on request subdomain, so that the same port on the WAN could be used for different local machines, nothing to fancy.
This have been working perfectly fine with all web services I've tested except with Eclipse Che.

For example for the following super simple configuration:

```
NAT: 
<wan-ip>:8080 forwarded to <proxy-ip>:8080

Proxy: 
<proxy-ip>:8080 forwarded to <che-server-ip>:8080

With the following address:
proxy: 192.168.0.110
che-server: 192.168.0.111

```

The dashboard loads fine, but when I try to open a workspace angular throws:

```
Blocked loading resource from url not allowed by $sceDelegate policy.  URL: http://192.168.0.110/che/wksp-opo2?uid=427793
```
The problem is as you can see for some reason port gets stripped of the url but only for workspaces. While in dashboard things works fine, in fact if I open the same workspace url that fails adding the port manually it also works fine.

```
WORKS: http://192.168.0.110:8080/che/wksp-opo2?uid=427793
```

I really doubt it has something to do with sceDelegate policy itself.

This kind of setup should be transparent to the services running behind the reverse proxy
I've tested the proxy with other complex services even with websockets and also tested the setup bypassing the proxy forwarding the WAN directly to Che to discard any docker port issue and it worked fine.

Furthermore currently i'm using the proxy on port 80 so that when port are stripped, the request will still be valid urls since default port on http is 80 and its quite nice very similar to what people are trying to achieve with Keycloak but being forced to use port 80 is not fun and quite limiting.

So I was really wondering how or what could be causing this magical ports strip issue. My wild guess is that Che behind the proxy is missing some kind of information and handles workspace in a different way that if it had that information or maybe angular needs some sort of header perhaps any clues of what could be going on?

**Comment by ghost** [comment]
@josevimlet have you tried it with an iframe? `/dashboard/#/ide/che/workspaceName`?

**Comment by lethevimlet** [comment]
@eivantsov, that's exactly the url where angular throws the sceDelegate policy error, and port gets stripped (Can’t interpolate: {{ideIframeLink}}).

![image](https://user-images.githubusercontent.com/2963923/27863661-7d081daa-618b-11e7-86a5-3ffa752b57cf.png)

As you can see, the console error url lacks the port 8080.

Note: localhost:8080 here is the reverse proxy address while che is running on a different machine of the same LAN also on port 8080.

**Comment by lethevimlet** [comment]
Just to bring a bit more info to the table here is what both iframes looks like when run through the proxy and without directly to che.

![image](https://user-images.githubusercontent.com/2963923/27873064-192d0afa-61ab-11e7-8c48-07518f84b403.png)

As you can see when run through the proxy iframe lacks its **src** and its angular **ng-src** attributes.

I guess this is because since the error "blocked loading resource from url not allowed by $sceDelegate policy" happens, iframe attributes never get set in the first place.

Note: localhost:8080 here is the reverse proxy address while che is running on a different machine 100.100.100.111:8080.

**Comment by ghost** [comment]
@josevimlet yes, it's loading resources into iframe that causes troubles. 

A few folks fromt he community successfully run Che behind nginx. At this point I don't know how to help.

**Comment by lethevimlet** [comment]
I'll try to mess a bit with iframes behind the proxy and strip the X-Frame-Options header to see if I can draw some conclusions, thanks @eivantsov i'll let you know if I find whats the issue.

**Comment by lethevimlet** [comment]
@eivantsov, I think I'm on the right track here, when I view http://localhost:8080/api/workspace being localhost the proxy the json also lacks the port

```
      {
        "produces": "text/html",
        "rel": "ide url",
        "href": "http://localhost/che/wksp-opo2",
        "method": "GET",
        "parameters": [
          
        ]
      },
```
whereas when I view it directly without the proxy, using http://100.100.100.111:8080/api/workspace, the json has the port

```
      {
        "produces": "text/html",
        "rel": "ide url",
        "href": "http://100.100.100.111:8080/che/wksp-opo2",
        "method": "GET",
        "parameters": [
          
        ]
      },
```
I asume this is the info the iframe uses for src and ng-src.

I guess a horrible simple solution would be to find and replace **localhost** string with **localhost:8080** for that **/api/workspace** url but I feel dirty doing it this way, any ideas of how this json is constructed specially the href value, maybe there is a config file or a js variable where I can force che to use the static ip:port I want for this json or a reason why is getting the proxy ip correctly but striping the port on that json?

**Comment by lethevimlet** [comment]
OK, I found why the address had its ports stripped behind a proxy, the reason was rewriteHostHeader must be set to true, here is the source for anyone who's also trying to run Eclipse Che behind a Wildfly reverse proxy.

![image](https://user-images.githubusercontent.com/2963923/27995899-912214c8-64d6-11e7-984e-66866950be1b.png)

That fixes **/api/workspace** port strip issue but now I find myself trying to expose Eclipse Che through a single port and WAN IP (Leaving out the proxy to keep things simple)

The problem is **/wsmaster/api/workspace/che/wksp-opo2** points to the Eclipse Che LAN address and there are many ports in use (Not very practical for NAT)

For example this IP and ports

![image](https://user-images.githubusercontent.com/2963923/27995947-8a7ba7be-64d7-11e7-8300-f8f2bef7e3ab.png)

should point to the WAN IP and use only a single port.

If I set CHE_HOST or CHE_IP to <WAN_IP>  CHE_PORT=8080 and CHE_SINGLE_PORT=true will **/wsmaster/api/workspace/che/wksp-opo2** json point to the WAN IP using justo one port in this case 8080, or are they additional steps to expose Eclipse Che to a public IP?

The real question is, what things one must set up to run Eclipse Che on WAN IP,

**Comment by josevimlet** [comment]
Finally I managed to get everything working ^^

So here a the steps in a nutshell for everyone:

1) Use a proxy that supports headers rewrite to avoid **/api/workspace** port strip issue
2) Setup **CHE_SINGLE_PORT=true** and **CHE_DOCKER_IP_EXTERNAL=<YOUR_EXTERNAL_IP>**
3) (Optional) Remove X-Frame-Options from headers to avoid iframe issues.

Enjoy your nice web IDE thanks to Eclipse Team <3

**Comment by josevimlet** [comment]
Using CHE_SINGLE_PORT=true and CHE_DOCKER_IP_EXTERNAL=**YOUR_EXTERNAL_IP** I can now access through the WAN Eclipse Che without the proxy.

The problem is the moment I use the proxy I get CORS error, and If add Access-Control-Allow-Origin: * I get body refused errors. I see that fancy nip.io is being used here but

`http://wsagent.dev-machine.workspacem5b3nyg4l072byq1.1XX.2XX.3XX.4XX.nip.io:8080/api/languageserver/supported.`

But I'm struggling on how to proceed from this point.

**Comment by lethevimlet** [comment]
@eivantsov , I believe found the answer, but for my disgrace I'm afraid that with a new answer there's a new issue, but hopefully all this can help others in a similar struggle, anyway... 

While using CHE_SINGLE_PORT=true and CHE_DOCKER_IP_EXTERNAL=**YOUR_EXTERNAL_IP** I can now access through the WAN Eclipse Che without the proxy. (Yaiii this is quite something!).

The problem is nip.io plays nastily behind a proxy. (Wooo this is sad!)

For example, this is the url that CHE_SINGLE_PORT generates for nip.io:

```
http://wsagent.dev-machine.workspacem5b3nyg4l072byq1.1XX.2XX.3XX.4XX.nip.io:8080/api/languageserver/supported.
```

I asume the nip.io role here is to provide the CHE_SINGLE_PORT logic info extracted from the url wildcard, in this case

**workspacem5b3nyg4l072byq1**

I believe the problem here is that Che expects the url with its fancy nip wildcard and although the wildcard resolves to the expected WAN IP, but since the NAT actually points to the reverse proxy instead of directly to the Che machine, it receives the url from the proxy not from nip.io, therefore lacking the wildcard info and resulting in a 503 response.

This is the topology to illustrate nip.io wildcard never reaching Che. 

(Works fine)
WILDCARD.nip.io ------> WAN ------> CHE

(Does't work)
WILDCARD.nip.io ------> WAN ------> PROXY------> CHE

If this really is the case nip.io here is quite limiting, unless I'm missing something.
I understand the idea behind it but maybe Che could get wildcard info, if not found in the url through a different method, for example using a custom header tag for this purpose. This will still be transparent to other setups since it will not modify the request url.

Maybe using X-Forwarded-For or Referer is it supported in this scenario?

I'm struggling on how to proceed from this point any ideas?

**Comment by benoitf** [comment]
@josevimlet 

I'm successfully able to add a nginx server in front of eclipse che with `CHE_SINGLE_PORT=true` 

 X-Forwarded-For and X-Forwarded-Proto (if you're using ssl) are required to be added on your PROXY configuration (like nginx/your reverse proxy)

Here was a dummy configuration to try che behind a https nginx frontend.
```
   location / {
      sub_filter_last_modified off;
      sub_filter '.127.0.0.1.nip.io:8080' '.127.0.0.1.nip.io';
      sub_filter_types "application/json";
      sub_filter_once off;
      proxy_set_header    Accept-Encoding "";      
      proxy_pass http://192.168.1.72:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto "https";
      add_header       X-Upstream      $upstream_addr;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
   }

```
nip.io is not doing some extra magic. It just resolves the hostname to the ip provided before the `nip.io` string.

If you need another ip naming, you can customize the hosts returned by che with your own strategy.

add this into your che.env file : 
```
CHE_DOCKER_SERVER__EVALUATION__STRATEGY_CUSTOM_TEMPLATE="...something"
```
default is `"<serverName>.<machineName>.<workspaceId>.<wildcardNipDomain>:<chePort>"`

if you have your own DNS you can set it up with your own domain, replacing `<wildcardNipDomain>`by for example `che.mydomain-name.com`

**Comment by lethevimlet** [comment]
Should I include the host, port and path on X-Forwarded-For?
for example x.x.x.x:8080/request or x.x.x.x:8080 or just x.x.x.x?

Also now it seems I'm having issues with web sockets and the workspace loads partially 

![image](https://user-images.githubusercontent.com/2963923/28015091-d4aeddd2-656e-11e7-800e-92d5b9b29b7e.png)

I'll check my proxy to see if there's some issue with ws

![image](https://user-images.githubusercontent.com/2963923/28015016-8cf2cf76-656e-11e7-98ac-19a3ef7cbee4.png)

**Comment by lethevimlet** [comment]
Thanx @benoitf for your help and the sample configuration, very handy.
Looking at your configuration and double checking my wildfy version, I've just tested a simple webapp that uses websockets behind the proxy and it worked fine so I guess I can discard any websockets issue, but still can't access Che. 

I believe the problem here still relies on the nip.io addresses, I will mess with them to see If I can get new conclusions.

![image](https://user-images.githubusercontent.com/2963923/28066091-d8f36156-663b-11e7-9a96-a854054c7c50.png)

This is the error that I get when running behind the proxy, any suggestions?

**Comment by ghost** [comment]
Hmmm..looks like the browser tries to connect to ws agent at the wrong endpoint , namely Che master endpoint.

**Comment by lethevimlet** [comment]
I did more testing and I'm quite confident that the issue is wildcards from xxxx.nip.io not reaching Che when using the proxy.

When I access a nip.io resource with che behind the proxy I get 
`There is no any resources matched to request .....`

So I bypassed the proxy and tested passing a bad wildcard to Che and I get the exact same message that when I use the proxy.

![image](https://user-images.githubusercontent.com/2963923/28079692-a8748ea0-6669-11e7-9707-d885d483987d.png)

Both of these urls are without the proxy, just to check the behaviour when no wildcard or bad wildcard reaches Che, and since the behaviour is the same my conclusion is that I need some sort of mechanic so that the proxy can provide Che this wildcard, any suggestions?

**Comment by lethevimlet** [comment]
Good news, I finally managed to get it working behind the Wildfly as a custom reverse proxy with authentication and load balancing.

First, thanks a lot to @eivantsov  and @benoitf for your help I really appreciate it, I believe you'll find pleasing someone using a Redhat server for this purpose <3 .

I was on the right track with the the wildcard thing, after studying the Nginx API and @benoitf  example, I did my best to port it to Wildfly, and finally I managed to get things working...  

The problem was with the fix I used for the port strip issue, rewriteHostHeaders = true, that was messing with the Host header, that's needed when wildcards (nip.io) where used. I did a nasty quick fix for it with
` boolean rewriteHostHeader = !exchange.getHostName().contains("nip.io");`
to do the rewrite only on the cases that arent nip.io, but I'm planning to tune a lot this approach to create a better solution.

Here are the steps to solve the problems I encountered for using Eclipse Che behind a Wildfly reverse proxy, thou I imagine most of this steps apply to other servers too, hopefully someone will find this useful.

## Poxy setup:
1) Create a reverse proxy, in my case I used Undertow LoadBalancingProxyClient and ProxyHandler in a custom handler module for undertow that I wrote.
(Note that ProxyHandler parameter **rewriteHostHeader fixes port strip issue** but mess wildcards used by Che single port mode, so I used the approach described above)

Here is the main code:
```
        // Proxy the request
        boolean rewriteHostHeader = !exchange.getHostName().contains("nip.io");
        boolean reuseXForwarded = false;
        final ProxyClient proxyClientProvider = new LoadBalancingProxyClient().addHost(URI.create("<CHE_IP_AND_PORT_HERE>"));        
        final HttpHandler handler = new ProxyHandler(proxyClientProvider, 30000, ResponseCodeHandler.HANDLE_404, rewriteHostHeader, reuseXForwarded);;
        
        exchange.dispatch(handler);
```

2) Added the following headers:
**X-Forwarded-For: <client_ip>
Host: <request_host>
X_Forwarded_Proto: http**

and the typical **CORS** headers to allow all (Optional, but just in case)

3) Removed **X-Frame-Options** header (Once again, just in case)

## Eclipse Che setup:
1) Enabled single port mode
2) Set che docker external IP

here is the command to do it directly through the command line although you could also edit che.env

```
docker run -it —rm -e CHE_SINGLE_PORT=true -e CHE_DOCKER_IP_EXTERNAL=<YOUR_WAN_IP_OR_DNS> -v /var/run/docker.sock:/var/run/docker.sock -v /home/che:/data  eclipse/che start
```

## NAT: 
1) Forward your WAN IP to your proxy LAN IP on the same port as CHE_PORT, not sure why but I had issues with nip.io when using a different port (I'll look at this asap).

## Notes:
1) When using CHE_SINGLE_PORT, Che diagnostics will fail.
2) When implementing some sort of authentication bare in mind that request from nip.io come from a different domain and things like session or cookie based authentication will fail. 
I currently bypass this issue white-listing the authenticated IP + User-Agent thou this solution has its own drawbacks, a better alternative would be to use your own wildcard on the same domain so cookies could propagate in ajax calls, but i'm afraid this wont work unless **XMLHttpRequest.withCredentials** is set to **true** on all client XMLHttpRequest, a PR for this would be nice.

And that's all, hope this help someone to get things going ^^

**Comment by TylerJewell** [comment]
This has been one of the most educational issues of the year. Reading this thread has been like getting a master class on the nuances of how reverse proxies are supposed to work. Congratulations to @josevimlet on perseverance and a successful implementation.

@eivantsov - do you think there is any value in packaging up the instructions at the end here as a short doc page, or maybe just a short tutorial page?
