### ISSUE TITLE
How to debug the workspace agent in Eclispe

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5536]
Hi, I am trying to debug the code in extension for workspace agent. I use the JSON editor template generated by archetype.

I see following instruction from guide
```
Dashboard -> Workspaces -> Runtime tab -> Servers
# Find the server with the `wsagent.debug` reference
wsagent.debug 4403 http	http://172.17.0.1:40037
```
 https://github.com/eclipse/che/wiki/Development-Workflow#debugging-workspace-agent 

I can see these information from Che page, then what should I do in Eclipse to debug following code? I tried remote java application on the ports, but the connection can not be established.
<img width="496" alt="screen shot 2017-07-05 at 2 36 53 pm" src="https://user-images.githubusercontent.com/10006307/27851910-787d7dda-618f-11e7-9a4f-622fe5679ca8.png">

**Comment by ghost** [comment]
@m7luffy I just tried to connect and it worked for me. Are you sure you are using the right IP and port?

**Comment by qi-min** [comment]
@eivantsov I tried both port listed in server: 33063 and 4403, all failed. 
This is what I set in Eclipse:
<img width="419" alt="screen shot 2017-07-05 at 6 01 32 pm" src="https://user-images.githubusercontent.com/10006307/27859669-14225c26-61ac-11e7-9b6d-66b4d149a18b.png">

Anything else need I added in Eclipse or the Che start commands?

**Comment by benoitf** [comment]
@m7luffy you've to use 40037 

the one at the right in the URL
```
wsagent.debug 4403 http	http://172.17.0.1:40037
```

**Comment by qi-min** [comment]
@benoitf the debug port in my page is not 40037.
![screen shot 2017-07-05 at 6 21 23 pm](https://user-images.githubusercontent.com/10006307/27860361-da93b312-61ae-11e7-9f38-4a8ef608f471.png)

**Comment by benoitf** [comment]
@m7luffy : on which URL do you access eclipse che ? it seems a network issue

**Comment by ghost** [comment]
@m7luffy debug port changes each time you restart a workspace. So, start a workspace, get a port, connect.

**Comment by qi-min** [comment]
@benoitf I just use http://9.30.146.229:8080 to access che

**Comment by qi-min** [comment]
@eivantsov But I get error after run debug from Eclipse with the correct port, it always reports connection to vm refused.

**Comment by qi-min** [comment]
It may be caused by network issue, I got the debug succeed several times after I changed to another network although the debug does not always succeed every time.

**Comment by qi-min** [comment]
Close this issue now since it maybe related to my network problem. Thanks for all your help.

**Comment by tsmaeder** [comment]
FWIW, for me docker -ls reliably shows local port mappings.
