### ISSUE TITLE
che custom workspace questions

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5538]
Hello,
in my project i would like to be able to create workspaces with projects containing just a folder with some files... 

For that , I would probably want to implement something like zip file upload at in the workspace creation menu, where a user creates and configures the workspace. As of now i can see that when i create a workspace i am able to import sources as zip, however an url must be provided there. I would like to change this functionality to  be able to upload files just from the local machine. Would it be possible? If yes, where would i find the code to tweak?

I would appreciate any help. Thank you in advance.

**Comment by vparfonov** [comment]
@willikynah you cant start from here https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectService.java#L644
hope this help you

**Comment by ghost** [comment]
Hey, i do not quite understand where would i use this. So this is a static method to upload an archive file. Where does the file get uploaded. If I understand correctly, I could for example define an action which would call this method, is it correct?

**Comment by ghost** [comment]
Yes, this is correct. We do not have such an action since there's no such functionality so far. Server side provides such a possibility, all you need is to create own action and use it.

**Comment by ghost** [comment]
Closing the issue since the questions seems to have been answered. Yo need to register an action and then call it as per your user case (from UD or IDE)
