### ISSUE TITLE
Super Dev mode does not work in code generated by archetype generate command

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5539]
Hi, I follow the development guide to setup the super dev mode,  but I got following error after run in Eclipse:
```
Super Dev Mode starting up
   workDir: /var/folders/h1/pv6r45557zqgf4fbbn0nwx_40000gn/T/gwt-codeserver-7497921084797402526.tmp
   Job org.eclipse.che.ide.IDE_1_0
      Loading inherited module 'org.eclipse.che.ide.IDE'
         [ERROR] Unable to find 'org/eclipse/che/ide/IDE.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```
I do not see org/eclipse/che/ide/IDE.gwt.xml under assembly-ide-war generated by archetype generate command. Does code generated by archetype support debug in super dev mode?

Version of Che is 5.10.0

**Comment by TylerJewell** [comment]
Can you try this with 5.14?  I do not recall, but some time around 5.10 was when we were doing GWT.XML decentralization.  If you wipe everything and start over do you get similar issues?

**Comment by qi-min** [comment]
OK, I will try 5.14. Because there is endless external file modification notification after 5.11, I have to use 5.10.

**Comment by qi-min** [comment]
I do see this file if I build the repository of Che. But I do not see this file if I build the customized Che generated 'archetype generate' command. Does anyone use super dev mode with archetype successfully?

**Comment by vnea** [comment]
@m7luffy Yes, I'm using CHE 5.10.0 and I can use Super Dev Mode in code generated by archetype generate command.

Can you give the **EXACT** command you used to generate the archetype and the **Program arguments** in the running configuration of the Super Dev Mode (in **Eclipse**).

**Comment by qi-min** [comment]
@vnea Here are the command I used to generate code:
```
docker run -it --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /data/Che/test/archetype:/archetype \
  -v /data/Che/test/data:/data \
  -v /root/.m2/repository:/m2 \
    eclipse/che-cli:5.10.0 \
      archetype generate
```
Here is my Eclipse configuration:
<img width="647" alt="screen shot 2017-07-06 at 4 27 07 pm" src="https://user-images.githubusercontent.com/10006307/27902441-535f4806-6268-11e7-9139-5eaf84cf0449.png">
<img width="663" alt="screen shot 2017-07-06 at 4 27 14 pm" src="https://user-images.githubusercontent.com/10006307/27902442-53948d04-6268-11e7-98f6-a260cba56ac8.png">
<img width="350" alt="screen shot 2017-07-06 at 4 29 28 pm" src="https://user-images.githubusercontent.com/10006307/27902443-53d2bb74-6268-11e7-88c7-f1b9e3d55492.png">

**Comment by vnea** [comment]
Try to replace
`-src target/generated-sources/gen`
by
`-src PATH_TO_GENERATED_ASSEMBLY/assembly-che/assembly-ide-war/target/generated-sources/gen`

Is it maybe a stupid question but did you **build** the generated archetype ?

**Comment by qi-min** [comment]
@vnea I use mvn clean install in the root dir of assembly in Eclipse. Build succeed, but I do not see 'IDE.gwt.xml' under assembly-ide-war/target/generated-sources/gen/org/eclipse/che/ide/

**Comment by vnea** [comment]
>  I do not see 'IDE.gwt.xml' under assembly-ide-war/target/generated-sources/gen/org/eclipse/che/ide/

Same for me but it works.

Did you try the path replacement of the **-src** argument ?

**Comment by qi-min** [comment]
@vnea I got same error if I use absolute path in -src.

```
Super Dev Mode starting up
   workDir: /var/folders/h1/pv6r45557zqgf4fbbn0nwx_40000gn/T/gwt-codeserver-460078759221459340.tmp
   Job org.eclipse.che.ide.IDE_1_0
      Loading inherited module 'org.eclipse.che.ide.IDE'
         [ERROR] Unable to find 'org/eclipse/che/ide/IDE.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

**Comment by qi-min** [comment]
I finally get it works, the IDE file is not under org/eclipse/che/ide. In the code generated by archetype, the file is under com/sample/ide.
