### ISSUE TITLE
How to resolve these compile errors in my Eclipse workspace

### ISSUE THREAD

**Issue by yhjyang** [eclipse-che/che#5540]
Hi, 
After I imported che source code to my Eclipse workspace, some plugin compiled failed.

My steps are:
1. Import the source code to my work space as a Maven Project  
<img width="521" alt="image" src="https://user-images.githubusercontent.com/29750858/27861498-ad855f7e-61b3-11e7-8805-92b9df17aa67.png">
2. Update all plugins
<img width="674" alt="image" src="https://user-images.githubusercontent.com/29750858/27861525-cc53bb8a-61b3-11e7-90ad-27ab4af99d87.png">
3. Build maven project in assembly-main
<img width="660" alt="image" src="https://user-images.githubusercontent.com/29750858/27861637-39a4307a-61b4-11e7-8e36-5aa2fb87644b.png">
4. 
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/29750858/27861707-7a315226-61b4-11e7-914e-21a7cac71faf.png">
5. Now, I try to start super dev mode, an error dialog will be popup:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/29750858/27861765-c4d46ffc-61b4-11e7-9d09-cea697aa8615.png">

Do you have some suggestions or experiences to remove these errors.
My branch is created from tag 5.13.0 and my Eclipse is 4.6.3
Thanks for any help.

**Comment by tsmaeder** [comment]
"mvn clean install" in the ROOT dir, not assembly-main. The assembly-main pom does not recursively build everything. In particular, you're missing classes generated during the maven build.

**Comment by yhjyang** [comment]
Thanks @tsmaeder , "mvn clean install" in the ROOT dir does resolve my problems.

**Comment by sau3242** [comment]
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: C:\Users\saurabh\eclipse-workspace\project1\bin
Caused by: java.lang.module.InvalidModuleDescriptorException: Javapackage.class found in top-level directory (unnamed package not allowed in module)
