### ISSUE TITLE
Super Dev Mode can not be started up

### ISSUE THREAD

**Issue by yhjyang** [eclipse-che/che#5544]
Hi, I followed the [wiki](https://github.com/eclipse/che/wiki/Development-Workflow#debugging-che-ide-extensions) to start Super Dev Mode in my Eclipse.
But it is not start up due to some compile errors.
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/29750858/27899492-032aa822-625d-11e7-8a41-a09fb73904f3.png">
Full log could be find here: [log.txt](https://github.com/eclipse/che/files/1126988/log.txt)

Thanks.

**Comment by ghost** [comment]
@yhjyang have you modified source code of the testing plugin? Can you compile Che from the command line?

`cd assembly`
`mvn clean install`

**Comment by ghost** [comment]
@yhjyang any update please?

**Comment by ghost** [comment]
Closed due to inactivity.
