### ISSUE TITLE
stacks-archetype fails because it does not exist

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-che/che#5548]
I can't create the new stacks-archetype introduced in #5417.

**Reproduction Steps:**

I get a `The desired archetype does not exist (org.eclipse.che.archetype:stacks-archetype:5.14.0)` error message when generating.

It looks like the archetype jars are not being published to: http://maven.codenvycorp.com/content/groups/public/org/eclipse/che/archetype/

This is the command line I am using with 5.14.0.

```
$ docker run -it --rm    -v /var/run/docker.sock:/var/run/docker.sock   -v /tmp/archetype:/archetype   -v /tmp/data:/data   -v ~/.m2/repository:/m2   -v /etc/group:/etc/group:ro   -v /etc/passwd:/etc/passwd:ro   --user=1000:1000   --group-add 999     eclipse/che-cli:5.14.0       archetype generate
WARNING: No swap limit support
INFO: (che cli): 5.14.0 - using docker 17.06.0-ce / native
INFO: (che download): Pulling image eclipse/che-dev

Using default tag: latest
latest: Pulling from eclipse/che-dev
Digest: sha256:a2bbf2588edda44a5b91e434c536b5bac436786cd61e4296eae47a07851735af
Status: Image is up to date for eclipse/che-dev:latest

INFO: (che archetype): Welcome to Eclipse Che custom assembly generator!
INFO: (che archetype): 
INFO: (che archetype): You can skip this message with '--no:interactive'.
INFO: (che archetype): 
INFO: (che archetype): This generator requires:
INFO: (che archetype):   1. Maven 3.3+ to be installed on your host.
INFO: (che archetype):   2. Your host Maven M2 repo mounted to ':/m2'.
INFO: (che archetype):   3. A local path for us to place the assembly mounted to ':/archetype'.

      Ready? [Y/n] 

1) agent-archetype                - Assembly with sample agent
2) plugin-menu-archetype          - Assembly with IDE extension to customize menu
3) plugin-wizard-archetype        - Assembly with custom C project type extension
4) plugin-serverservice-archetype - Assembly with simple IDE extesion and a server service
5) plugin-embedjs-archetype       - Assembly with simple IDE extesion for using native javascript in widgets
6) plugin-json-archetype          - Assembly with sample JSON project type, editor codeassistant, and workspace services
7) stacks-archetype               - Assembly with sample stack packaging module, for using custom stacks in assemblies
Please enter your choice: 7

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype defined by properties
Downloading: http://maven.codenvycorp.com/content/groups/public/org/eclipse/che/archetype/stacks-archetype/5.14.0/stacks-archetype-5.14.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.003 s
[INFO] Finished at: 2017-07-06T09:39:24+00:00
[INFO] Final Memory: 14M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.eclipse.che.archetype:stacks-archetype:5.14.0) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

And this is the one for nightly:

```
$ docker run -it --rm    -v /var/run/docker.sock:/var/run/docker.sock   -v /tmp/archetype:/archetype   -v /tmp/data:/data   -v ~/.m2/repository:/m2   -v /etc/group:/etc/group:ro   -v /etc/passwd:/etc/passwd:ro   --user=1000:1000   --group-add 999     eclipse/che-cli:nightly       archetype generate
WARNING: No swap limit support
INFO: (che cli): nightly - using docker 17.06.0-ce / native
INFO: (che download): Pulling image eclipse/che-cli:nightly

nightly: Pulling from eclipse/che-cli
Digest: sha256:b1227f0a75a38e451657596c11dd58ad8ccae95a113c0e7fcc4418e2b08bf477
Status: Image is up to date for eclipse/che-cli:nightly

INFO: (che download): Pulling image eclipse/che-dev

Using default tag: latest
latest: Pulling from eclipse/che-dev
Digest: sha256:a2bbf2588edda44a5b91e434c536b5bac436786cd61e4296eae47a07851735af
Status: Image is up to date for eclipse/che-dev:latest

INFO: (che archetype): Welcome to Eclipse Che custom assembly generator!
INFO: (che archetype): 
INFO: (che archetype): You can skip this message with '--no:interactive'.
INFO: (che archetype): 
INFO: (che archetype): This generator requires:
INFO: (che archetype):   1. Maven 3.3+ to be installed on your host.
INFO: (che archetype):   2. Your host Maven M2 repo mounted to ':/m2'.
INFO: (che archetype):   3. A local path for us to place the assembly mounted to ':/archetype'.

      Ready? [Y/n] 

1) agent-archetype                - Assembly with sample agent
2) plugin-menu-archetype          - Assembly with IDE extension to customize menu
3) plugin-wizard-archetype        - Assembly with custom C project type extension
4) plugin-serverservice-archetype - Assembly with simple IDE extesion and a server service
5) plugin-embedjs-archetype       - Assembly with simple IDE extesion for using native javascript in widgets
6) plugin-json-archetype          - Assembly with sample JSON project type, editor codeassistant, and workspace services
7) stacks-archetype               - Assembly with sample stack packaging module, for using custom stacks in assemblies
Please enter your choice: 7

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype defined by properties
Downloading: http://maven.codenvycorp.com/content/groups/public/org/eclipse/che/archetype/stacks-archetype/nightly/stacks-archetype-nightly.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.194 s
[INFO] Finished at: 2017-07-06T09:39:41+00:00
[INFO] Final Memory: 14M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.eclipse.che.archetype:stacks-archetype:nightly) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**OS and version:**    

XUbuntu 17.04

**Diagnostics:** 
```
$ docker run -it --rm    -v /var/run/docker.sock:/var/run/docker.sock   -v /tmp/archetype:/archetype   -v /tmp/data:/data   -v ~/.m2/repository:/m2   -v /etc/group:/etc/group:ro   -v /etc/passwd:/etc/passwd:ro   --user=1000:1000   --group-add 999     eclipse/che info
WARN: Bound 'eclipse/che' to 'eclipse/che:5.14.0'
WARNING: No swap limit support
INFO: (che cli): 5.14.0 - using docker 17.06.0-ce / native

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che
 Version:        5.14.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /tmp/data
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.14.0
 CHE_HOST:       172.17.0.1
 CHE_INSTANCE:   /tmp/data/instance
 CHE_CONFIG:     /tmp/data
 CHE_BACKUP:     /tmp/data/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   172.17.0.1
 Initialized:    false
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.14.0
 IMAGE_CHE=eclipse/che-server:5.14.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.14.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.14.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.14.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.14.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.14.0
che.env: not initialized
```

**Comment by slemeur** [comment]
@eivantsov + @mkuznyetsov : Could you please take a look at that.

**Comment by ghost** [comment]
Yes, it's a bug - stack-archetype has never been added as a maven module here - https://github.com/eclipse/che-archetypes/blob/5.14.0/pom.xml#L34-L41

**Comment by slemeur** [comment]
@mkuznyetsov : Could you fix that asap?
@riuvshin : Once this one is fixed, we will need a bug fix release to include it in 5.14.1

Thanks!

**Comment by ghost** [comment]
It's an easy fix and I'd argue this is a blocker for a release.

**Comment by ghost** [comment]
Here's a PR https://github.com/eclipse/che-archetypes/pull/50

**Comment by riuvshin** [comment]
hey @jonahkichwacoders,
I've just uploaded missing jar to nexus
http://maven.codenvycorp.com/content/groups/public/org/eclipse/che/archetype/stacks-archetype/5.14.0/

it should be fine now, just rerun CLI command and it should work. 
Thanks for rising this 👍 

@slemeur @TylerJewell we don't need bugfix release for this, adding missing jar solved issue for 5.14.0 version.

**Comment by jonahgraham** [comment]
@riuvshin Thanks for the quick turnaround, it works as expected now.

**Comment by ruzalsh** [comment]
**Still same issue :::**

[root@localhost ~]# docker run -it --rm \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -v /rujal/archetype/:/archetype \
>   -v /rujal/tmp:/data \
>   -v /root/.m2/:/m2 \
>   --user=0 \
>   --group-add 993 \
>     eclipse/che-cli \
>       archetype generate --archid=1
WARN: Bound 'eclipse/che-cli' to 'eclipse/che-cli:6.8.0'
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
INFO: (che cli): 6.8.0 - using docker 18.04.0-ce / native
INFO: (che download): Pulling image eclipse/che-dev

Using default tag: latest
latest: Pulling from eclipse/che-dev

Digest: sha256:516beea3dd0487853af8b59f3fcbfa03f032251fdd821696836ca0f907a4ae5c
Status: Image is up to date for eclipse/che-dev:latest

INFO: (che archetype): Welcome to Eclipse Che custom assembly generator!
INFO: (che archetype):
INFO: (che archetype): You can skip this message with '--no:interactive'.
INFO: (che archetype):
INFO: (che archetype): This generator requires:
INFO: (che archetype):   1. Maven 3.3+ to be installed on your host.
INFO: (che archetype):   2. Your host Maven M2 repo mounted to ':/m2'.
INFO: (che archetype):   3. A local path for us to place the assembly mounted to ':/archetype'.

      Ready? [Y/n] Y
1) agent-archetype                - Assembly with sample agent
2) plugin-menu-archetype          - Assembly with IDE extension to customize menu
3) plugin-wizard-archetype        - Assembly with custom C project type extension
4) plugin-serverservice-archetype - Assembly with simple IDE extesion and a server service
5) plugin-embedjs-archetype       - Assembly with simple IDE extesion for using native javascript in widgets
6) plugin-json-archetype          - Assembly with sample JSON project type, editor codeassistant, and workspace services
7) stacks-archetype               - Assembly with sample stack packaging module, for using custom stacks in assemblies
Please enter your choice:
1) agent-archetype                - Assembly with sample agent
2) plugin-menu-archetype          - Assembly with IDE extension to customize menu
3) plugin-wizard-archetype        - Assembly with custom C project type extension
4) plugin-serverservice-archetype - Assembly with simple IDE extesion and a server service
5) plugin-embedjs-archetype       - Assembly with simple IDE extesion for using native javascript in widgets
6) plugin-json-archetype          - Assembly with sample JSON project type, editor codeassistant, and workspace services
7) stacks-archetype               - Assembly with sample stack packaging module, for using custom stacks in assemblies
Please enter your choice: 1

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype defined by properties
Downloading: http://maven.codenvycorp.com/content/groups/public/org/eclipse/che/archetype/agent-archetype/6.8.0/agent-archetype-6.8.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.819 s
[INFO] Finished at: 2018-07-28T04:10:53Z
[INFO] Final Memory: 15M/472M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.eclipse.che.archetype:agent-archetype:6.8.0) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by slemeur** [comment]
You are not mad at all ! A lot of people in the community are building their own custom cloud IDE based from Eclipse Che.

I would recommend to give a look at the following documentation:
- https://www.eclipse.org/che/docs/framework-overview.html

Are you able to share a bit what you are looking to customize? Would you be looking for contributing your tools to the whole Eclipse Che community?

If you want to discuss with the teams working on Eclipse Che, we have a community call: https://github.com/eclipse/che/wiki/Che-Dev-Meetings You are welcomed to join with your questions !
We have

**Comment by ruzalsh** [comment]
@slemeur  Thank you for your heartwarming words. **I would love to contribute.** but before that, i want to practice on my own. 
Fields i want to customize are : 
1. IDE (include context menu/menu bar, run/build functionality)
2. Add custom Stack
3. Assembly and 4. Plugin 

Simply, i want to make light weighted IDE with few functionality.
Being weak in English, i am not able to fully grasp **che documentation** and i was looking for step by step documentation like you have in **Develop your first Plugin using che**

**Comment by ruzalsh** [comment]
@slemeur  Thank you alot. **I dont have words to express**. but i am very excited in upcomming **extensibilty** and also **Eclipse Theia**
