### ISSUE TITLE
Delete Java class from Project Explorer should consider as Refactoring 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#5549]
If user want to delete some class from from java project before deleting IDE must analyze code base and show warn message with information where this file are used.
How it work now in Eclipse Che:
![delete-class](https://user-images.githubusercontent.com/1636592/27906118-e7f944e4-624a-11e7-8ed1-ec335ef54b1a.gif)

Must be something like:
![delete-class-idea](https://user-images.githubusercontent.com/1636592/27906209-48a7379c-624b-11e7-91b2-5d17165fd1c7.png)

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
