### ISSUE TITLE
Ugly text rendering

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5557]
![image](https://user-images.githubusercontent.com/14976516/27943344-dcc0c78e-6310-11e7-9d4e-5828483bfbd7.png)

This is a rare bug I encountered while I was testing my Dockerfile

**OS and version:**  

Codenvy 5.14.0  on codenvy.io

**Comment by ghost** [comment]
@sr229 is ugly the right word here? :) Maybe the issue title "Word wrap in a workspace start terminal can be improved" sounds a little bit better, don't you think?

@slemeur I might be mistaken, but we are going to give up on a crane screen with this small window for docker logs, right?

**Comment by sr229** [comment]
@eivantsov I meant the statement "Starting workspace agent" word which seems pixelated. Rendering seems broken

**Comment by ghost** [comment]
@sr229 i was unable to reproduce it on my screen. Probably it has smth to do with screen resolution.

**Comment by sr229** [comment]
I believe so, but the screen resolution is at 1920x1080 fullres.

This is a rather weird and irreproducible bug 

Marking closed.
