### ISSUE TITLE
Can't boot up ws-agent with huge workspace.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#5560]
**Reproduction Steps:**

0. Place project on NFS volume.
1. Create huge project (e.g. `npm install` after cloning ng2-admin)
2. Restart workspace.

**OS and version:**    

5.15.0-SNAPSHOT c7c1ee807cc2d85f

**Diagnostics:** 

Small size workspaces work fine on the same instance.
Referring `docker exec -it <container-id> ps -ef`, my ws-agent was blocked in `chown -R usr /projects`.
Is it possible to run `chown` in background ?

**Comment by ghost** [comment]
This is where it happens - https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.script.sh#L48

I think just appending `&` may fix it

**Comment by monaka** [comment]
@eivantsov I also suspect the line you pointed.
And in addition.
Is this line is really required?
AFAIK, all users can be sudoer. So he/she can execute `chown` by themselves, I think.

**Comment by ghost** [comment]
This line is required in certain use cases, for example when uid of a host and container user aren't the same. So, user in a container cannot create resources in `/projects`. Perhaps we can improve the script, and check permissions first, and if uid differ, execute chown.

**Comment by monaka** [comment]
I see. I'll keep trying how to fix this issue on my environment.

**Comment by monaka** [comment]
How about using `find` ?

I tried to run on my workspace that causes this issue.
All files/dirs have uid=1000 and gid=1000.

At the first, the baseline.
```
time chown -R 1000:1000 *

real    3m16.323s
```

The worst case with  `find`. All files/dirs are matched.
```
time find -uid 1000 -print0 | xargs -0 -P3 --no-run-if-empty chown 1000:1000

real    3m23.360s
```

And the best case. It doesn't execute `chown`.
```
time find -not -uid 1000 -print0 | xargs -0 -P3 --no-run-if-empty chown 1000:1000

real    0m46.230s
```

In case using `find`, it may be failed to boot up on worst cases.
But it will be fixed after some retry.

**Comment by ghost** [comment]
@monaka in your case (and most cases on Linux where uid==1000) chown isn't even necessary. Perhaps, adding a check can partially resolve this issue.

**Comment by ghost** [comment]
@monaka will you be issuing a PR soon?

**Comment by monaka** [comment]
I created a patch but, just for me, this issue is fixed by stopping to use NFS home...
I'll send PR for something helps.

**Comment by ghost** [comment]
@monaka is this still an issue for you?

**Comment by eivantsov** [comment]
@monaka Looks like a simple check may fix the problem.

For instance, run `stat -c '%u'` and run `chown` only in case owner of `/projects` differs from current uid.

```
CURRENT_OWNER=$(stat -c '%u' /projects)
UID=$(id -u -n)
if [ "${CURRENT_OWNER}" != "${UID}" ]; then
${SUDO} sh -c "chown -R $(id -u -n) /projects"
fi
```
WDYT?

**Comment by monaka** [comment]
@eivantsov 
Looks your shell script effective. But recently I failed to catch up new versions of Che.
And this issue is caused by slow file systems like NFS/CIFS and it may be a rare case.
So I close this now. Thanks for your support.
