### ISSUE TITLE
Error: [$interpolate:interr] Can't interpolate: {{ideIframeLink}}

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5562]
![image](https://user-images.githubusercontent.com/14976516/27959677-fb238730-635a-11e7-9054-c72590c0453f.png)

I can't understand the error to give out a detailed description but the screenshot should do
Done on BrowserSync'ed Dashboard from the che repo.

**Reproduction Steps:**
1:) Run ``gulp:dist``
2:) wait for everything to transpile
3:)go to dashboard and click to workspace.

Expected : IDE should work as expected.
Result: Infinite loading.

**OS and version:**    
Eclipse Che 5.15.0 Snapshot on Windows 10 Build 14393 on Docker 17.05 CE
**Diagnostics:** 
```
CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:nightly
 Version:        nightly
 Command:        info
 Parameters:     info
Mounts:
 /data:          /c/tmp
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         boot2docker
 Proxy:          not set
Internal:
 CHE_VERSION:    nightly
 CHE_HOST:       192.168.99.100
 CHE_INSTANCE:   /c/tmp/instance
 CHE_CONFIG:     /c/tmp
 CHE_BACKUP:     /c/tmp/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   192.168.99.100
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:nightly
 IMAGE_CHE=eclipse/che-server:nightly
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:nightly
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:nightly
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:nightly
 UTILITY_IMAGE_CHETEST=eclipse/che-test:nightly
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:nightly
che.env:
 CHE_HOST=192.168.99.100
 CHE_SINGLE_PORT=false
```

**Comment by ghost** [comment]
@sr229 please provide more steps to reproduce. Do you mount your local binaries to test some dashboard changes? What is your run syntax?

**Comment by sr229** [comment]
The tests were done with a already-pulled Eclipse Che nightly image in DockerHub. 
The following was ran with ``docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/tmp:/data eclipse/che start`` 

Then I pulled from che repo, compiled dashboard with gulp as per instructed in README, some errors shown up (mostly doesn't exist in the current context errors, etc.) using ``gulp serve``  with server arg.

no local binaries were mounted to test dashboard changes.

**Comment by sr229** [comment]
It was running from the local, uncontainerized repository using BrowserSync at http://localhost:3000 

Because I only meant to test dashboard without compiling the whole Che project

**Comment by sr229** [comment]
Additional info, during the `gulp:serve` process these errors shown up

This was before it served the dashboard on localhost

![image](https://user-images.githubusercontent.com/14976516/27961028-f40f375a-635f-11e7-897f-2821aa436b57.png)

Not sure if intentional

**Comment by ghost** [comment]
Two problems then. As to iframe loading, I suspect that it's because dashboard runs on localhost and che-server is in VM.

**Comment by sr229** [comment]
@eivantsov so they have to be inside the VM to work?

let me try running it inside VM this time

**Comment by sr229** [comment]
Marking closed.

Seems resolved.

Thanks for the assitance @eivantsov
