### ISSUE TITLE
Can't search with backslash

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5564]
When trying to search (through multiple files) with a backslash, for example, `Mage\Community` a 400 error is shown and the search does not complete.

**Reproduction Steps:**
Press `Ctrl + Shift + S` on any folder tree and search for any string with a `\` in it.

**Comment by skabashnyuk** [comment]
@davidwindell is this search by name or by content?

**Comment by davidwindell** [comment]
@skabashnyuk by content, searching through all files in the project

**Comment by AndrienkoAleksandr** [comment]
Seems it's a project api. For example 
```http://172.19.20.22:32841/api/project/search/che/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console?text=*test*&maxItems=30```
I think it's just because this symbol `"\"` is not valid http character. But we send search expression like query. I think we should send "search" expression with help json.

**Comment by AndrienkoAleksandr** [comment]
Seems another way it's a configure Tomcat to redirect invalid http symbols. But it's overhead.

**Comment by davidwindell** [comment]
Does the search string just need urlencoding properly?

**Comment by AndrienkoAleksandr** [comment]
@davidwindell Fix me if I am wrong but for such characters url encoding doesn't work.

**Comment by davidwindell** [comment]
Forward slash URL encoded is `%2F`

**Comment by AndrienkoAleksandr** [comment]
Search really works incorrectly for a lot symbols. Such like `Ö, Ü, ß, !, #, +, |, &` and much more another. And it's really encoding problem. @davidwindell thanks.

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
