### ISSUE TITLE
gpu support with docker eclipse-che/workspace

### ISSUE THREAD

**Issue by TuranTimur** [eclipse-che/che#5567]
I'm using eclipseche for my python development,
and I need to use gpu during programming.
but currentlt there is no gpu option when creating workspace.

Is there any work around or plan for implementation of gpu support on eclipse che?

**Comment by ghost** [comment]
@donghwicha interesting question. AFAIK, no immediate plans. However, if you have sense of adventure you may give it a try yourself: https://github.com/NVIDIA/nvidia-docker

**Comment by ibuziuk** [comment]
should be possible with the container overrides features in the latest version of Eclipse Che - https://github.com/devfile/devworkspace-operator/issues/945
