### ISSUE TITLE
Syntax errors are not displayed in java editor if Che is start from archetype template

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5568]
When I start Che from the code generated by archetype generate, java syntax errors are not displayed. I can see the errors from Che in same tag(5.10.0) if I start it from Che image.

And I also notice there is a red fork on the project icon. When I start Che from Che image, there is no fork.
![screen shot 2017-07-10 at 1 56 53 pm](https://user-images.githubusercontent.com/10006307/28004500-ac149354-6577-11e7-97b8-72e6b3d7b7bf.png)

**Comment by ghost** [comment]
@m7luffy how did you create your project? You can go to Project > Update project configuration and set it to maven

**Comment by qi-min** [comment]
@eivantsov I just select the sample java project when create a workspace for java.

And there is way to change the project to maven, only save button is enabled.
![screen shot 2017-07-10 at 2 26 22 pm](https://user-images.githubusercontent.com/10006307/28005197-eb793258-657b-11e7-8f1f-fe6c7608c97d.png)

**Comment by ghost** [comment]
@m7luffy I see, this sample registers only 2 project types. It's rather an example showing how one can provide own project type, create a custom assembly etc. ws-agent in this assembly inherits just the core module with the minimal set of dependencies https://github.com/eclipse/che/blob/master/wsagent/che-wsagent-core/pom.xml

**Comment by qi-min** [comment]
@eivantsov  Do you mean the pom.xml under assembly-wsagent-war? I only see following dependency in pom generated by archetype:
```
<dependency>
            <groupId>org.eclipse.che.core</groupId>
            <artifactId>che-wsagent-core</artifactId>
            <type>war</type>
        </dependency>
```
Should I add following dependency to pom.xml?
```
<dependency>
    <groupId>org.eclipse.che.core</groupId>
     <artifactId>che-core-api-languageserver</artifactId>
  </dependency>
```
 
We are planing to build some plugins to Che, so we choose the templates from archetype generate, it is simple than the full repository. But seems the template does not inherits all the features from Che. So does archetype still the correct way to be used to develop plugin extensions?

**Comment by ghost** [comment]
It depends on the archetype. This one shows adding a new project type. Others show different things. For instance, here ws-agent is used as is - https://github.com/eclipse/che-archetypes/blob/master/plugin-wizard-archetype/src/main/resources/archetype-resources/pom.xml

In your case, you will need to to have own ws-agent module just like https://github.com/eclipse/che-archetypes/blob/master/plugin-json-archetype/src/main/resources/archetype-resources/assembly-che/assembly-wsagent-war/pom.xml

You may take at deps set for Che out of the box: https://github.com/eclipse/che/blob/master/assembly/assembly-wsagent-war/pom.xml, add, remove, play around - it's your assembly.

And to answer your question, you need all dependencies that have `java` and `maven` keywords in them. And `testing` too.

**Comment by ghost** [comment]
Closing the issue as the original question seems to have been answered.
