### ISSUE TITLE
Can not start a project with my customized stack

### ISSUE THREAD

**Issue by yhjyang** [eclipse-che/che#5571]
Hi, I want to create a project with my customized stack.
In my stack, I add a new node named db2 with a local docker image:

    db2:
       image: 'db2server:v11.1.2fp2_1'
       mem_limit: 2147483648
       environment:
       LICENSE: accept
       DB2INST1_PASSWORD: passw0rd
When I click the test button to test this stack, an error dialog shows can not find my docker image
![image](https://user-images.githubusercontent.com/29750858/28008747-5967617c-658b-11e7-91ad-7f0779b01963.png)
But I can see my docker image is stored in my local with `docker images` 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/29750858/28008819-9a9ec7b6-658b-11e7-9a70-3f5d55b20199.png">

And I try to set `CHE_DOCKER_ALWAYS__PULL__IMAGE=false` in my data/che.env, but it does not work.

Any suggestions about this kind of issue would be appreciate, thanks.

**Comment by TylerJewell** [comment]
@yhjyang - what is your Docker version?  We uncovered recently a limitation in certain Docker daemon versions that preview the `CHE_DOCKER_ALWAYS__PULL__IMAGE` property from working properly.

**Comment by yhjyang** [comment]
@TylerJewell , my docker's version is 17.06.0-ce

**Comment by yhjyang** [comment]
It works after I switched to che 5.14.0, thanks.
