### ISSUE TITLE
Test docker infrastructure

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#5575]
Revise the `infrastructure-docker` module and provide corresponding unit test suite for all components inside this module and remove components moved from master which are essentially useless.
Sub tasks:
- [x] Move docker container settings applying from DockerMachineStarter #5871
- [ ] Move code of DockerMachineStarter into several classes for managing containers/images 
- [ ] Add tests for DockerMachineStarter
- [ ] Uncomment commented tests
- [ ] Improve test coverage of DockerInternalRuntime
- [ ] Add tests for DockerMachine
- [ ] Add tests for DockerMachineCreator
- [ ] Add tests for DockerRuntimeContext
- [ ] Add tests for DockerRuntimeInfrastructure

**Comment by skabashnyuk** [comment]
Will implemented on demand.
