### ISSUE TITLE
CHE-639 Investigate how to add new file formats in editor

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#558]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-639
Reporter:  Anna Shumilova
Description: Need to investigate registering new file formats in editor and provide the docs. More details can be found in this thread https://github.com/eclipse/che/issues/550

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/54589660bd3bd540e5b3d4754bf7b50383666aff
