### ISSUE TITLE
Provide links of the workspace to the client

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#5581]
We already have at least two endpoints which may be useful for clients:
`output endpoint`
`workspace status endpoint`
So we need to rework our workspace links injector in accordance with client`s needs and changes in spi branch.
Note that the set of endpoints may expand.
We also want to simplify Links model. It is supposed to be done as a part of this issue.
The current model is complicated and, lately, we used to use it in the simplest use cases only. So we decided to simplify it significantly.
The current model of an object that contains links is: 
```json
{
    "field1" : "",
    "links" : [
        {
            "href" : "http://some-server.com:9090/path1/path2",
            "rel" : "myserver.api",
            "method" : "GET",
            "produces" : "application/json",
            "consumes" : "application/json",
            "parameters" : [
                {
                    "name" : "parameterName",
                    "defaultValue" : "defvalue1",
                    "description" : "Some user-friendly description",
                    "type" : "string",
                    "required" : true,
                    "valid" : [
                        "valid1",
                        "valid2",
                    ]
                }
            ],
            "requestBody" : {
                "description" : "body user-friendly description"
            }
        }
    ]
}
```
and the new model would be:
```json
{
    "field1" : "",
    "links" : {
        "myserver.api" : "http://some-server.com:9090/path1/path2",
        "anotherserver.api" : "http://another-server.com",
    }
}
```

**Comment by garagatyi** [comment]
I've updated description of this issue to extend its DoD with links model simplification

**Comment by gazarenkov** [comment]
Let's also take seriously the name convention for the links and servers.
Before we our naming was rather random.
Does that make sense to consider the ["namespace"]/"name" pattern (both names - camel-cased)?

**Comment by garagatyi** [comment]
I think it is OK - then it will be similar to JSON_RPC method naming
