### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by iamslite** [eclipse-che/che#5587]
Is it possible to get the release notes for the releases listed on github. The changelog in the repository is not being kept up to date and the last release note listed on the blog is for 5.12.

**Comment by TylerJewell** [comment]
You have to navigate through the old milestones to see what is in each release right now.

https://github.com/eclipse/che/wiki/Milestone-Plans

The engineers in the weekly meeting are discussing about using tools to more consistently generate a nice changelog. Unfortunately there are not great ones available that parse the release notes the way we'd want them to.

**Comment by ghost** [comment]
Changelog is generated for each release now https://github.com/eclipse/che/releases

Closing the issue
