### ISSUE TITLE
Actual releases?

### ISSUE THREAD

**Issue by iamslite** [eclipse-che/che#5588]
The latest release according to the Github releases page pre-dates 5.9.0, despite there being releases all the way to the 5.14.0 if you use the "show newer tags" link.

**Comment by TylerJewell** [comment]
All of the releases are there. You just have to expand the "..." at the top of the releases page when it loads.
https://github.com/eclipse/che/releases

**Comment by ghost** [comment]
Indeed, we stopped drafting releases on GitHub, so everything from 5.9 are tags.

**Comment by iamslite** [comment]
It isn't helped by the "Latest Release" link from the navigation on https://che.eclipse.org/ also going to the 5.9 release notes.

**Comment by ghost** [comment]
@slemeur can you please take a look? I have no control over that page.

**Comment by slemeur** [comment]
@eivantsov : Same for me, I don't have the ability to edit it. 
@TylerJewell or @bmicklea could you update that too?

**Comment by bmicklea** [comment]
> It isn't helped by the "Latest Release" link from the navigation on https://che.eclipse.org/ also going to the 5.9 release notes.

That's my fault - I'll update once the 5.14 release note is published later today.

**Comment by riuvshin** [comment]
also we should draft releases here with changelog and some links

**Comment by iamslite** [comment]
At the moment we have 5.14 tagged as the latest release on github and the blog has been updated. Thanks.

**Comment by riuvshin** [comment]
we've restored automated changelog generation.
