### ISSUE TITLE
how to build cpp code/project with CHE 

### ISSUE THREAD

**Issue by leon541** [eclipse-che/che#5589]
I am new to CHE, and trying to build some sample cpp code with CHE. 
How am I support to build cpp code with CHE command, where there is no gcc, g++ or make. 
or, how can I access gcc/g++/make.

Thanks
Leon

**Comment by ghost** [comment]
@leon541 you need to create a C/CPP stack. You can see it in ready to go stacks in User Dashboard.

**Comment by leon541** [comment]
Thank you! @eivantsov
