### ISSUE TITLE
CHE-640 Password strength meter is broken on account view

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#559]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-640
Reporter:  Anna Shumilova
Description: Password strength meter not working when changing password on account view

**Comment by ddementieva** [comment]
Fixed by https://github.com/codenvy/che-dashboard/commit/5645f721a677c9a654891dce7f1f753c2b900d88
