### ISSUE TITLE
[Regression] Some workspaces which created from the Dashboard don't have commands

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5592]
**Reproduction Steps:**

- Create and start a workspace from the Java stack with the web-java-spring project
- Check availability of the project's command by in the project context menu

**Observed behavior:**
The project's commands aren't exist in the context menu and will appear there after refreshing a page. This problem are in the Java, Bitnami, My-Sql, Node stacks

**Che version:** 5.15.0-SNAPSHOT
**OS and version:** Fedora 25
![config-5](https://user-images.githubusercontent.com/7760565/28059984-90b18966-662e-11e7-80e4-5b50fd7904ff.gif)

**Comment by Ohrimenko1988** [comment]
Maybe this is related with https://github.com/eclipse/che/issues/5188
