### ISSUE TITLE
content assistant does not work correctly

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5594]
The function document.replace in Completion does not work as expected. For example, in the Json example code, proposal is expected to be appended after cursor. but it will append another string after proposal.
1. input 'fir' in Json file
![screen shot 2017-07-11 at 5 21 20 pm](https://user-images.githubusercontent.com/10006307/28061542-896c6386-665d-11e7-9059-bd87aab4e323.png)
2. select 'firstname' and the text become 'firfirstNamefir'. Extra 'fir' is appended after proposal.
![screen shot 2017-07-11 at 5 21 37 pm](https://user-images.githubusercontent.com/10006307/28061591-b4c0f826-665d-11e7-8a99-3d93cb995dd6.png)
3. Is there API to just append the missing part? For example, if I have already input 'fir', then only 'stName' should be appended.

```
public void apply(Document document) {
        document.replace(
                document.getCursorOffset(),
                proposal.length(),
                proposal);
    }
```

**Comment by tsmaeder** [comment]
What version of Che are you using?

**Comment by qi-min** [comment]
@tsmaeder I see this in both Che 5.10.0 and Che 5.14.0

**Comment by qi-min** [comment]
@eivantsov is this a bug of  method `document.replace`? Or does sample code call the function in wrong way?

**Comment by ghost** [comment]
@vparfonov will this issue be taken to the next sprint? I think auto completion in Python ls is impacted as well.

**Comment by RomanNikitenko** [comment]
@m7luffy It works for me on current version
May be you have another use case or it's already fixed...
![contentassjson](https://user-images.githubusercontent.com/5676062/28974873-9f540564-7940-11e7-9b52-b0477a309238.gif)

**Comment by RomanNikitenko** [comment]
I am closing the issue. Feel free to reopen if the problem persists.

**Comment by ghost** [comment]
@m7luffy in particular we're interested in how you imported your JSON scheme

**Comment by tsmaeder** [comment]
Technical note: the IDE should NOT decide to remove any common prefixes here: only the language server should make that decision.
