### ISSUE TITLE
Automate generation of changelog

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#5595]
We would like to completely automate the generation of the changelog when doing a release, by using:  https://github.com/skywinder/github-changelog-generator

The idea is the following:
- CI handle the generation of the changelog.
- The changelog is based on PRs merged.
- The changelog has sections to regroup PRs by `kind/*` labels

We will need to see how we can distinguish the security and deprecation issues. (probably by introducing new labels)

**Comment by riuvshin** [comment]
@slemeur bad news here, that tool can't decorate / filter PRs it work only with issues.
so for PRs we can only adjust the title "Merged pull requests"
So... I think we will generate for future versions in same way as simple list of all merged PRs for particular version.

**Comment by riuvshin** [comment]
ci job - https://ci.codenvycorp.com/view/release/job/generate-changelos/
