### ISSUE TITLE
Workspace is not started when RAM not in 0.5 step and error message is not shown

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5601]
**Reproduction Steps:**
 - Go to the "Workspaces" -> "Add Workspace"
 - Select "Java" stack
 - Input "2.3" in the "RAM" field
 - Click on "Create" button
 - Pay attention to the screen 

**Expected behavior**
Workspace will be started with 2.3 GB RAM or error message will be shown

**Observed behavior**
Workspace is not started and error message is not shown

**OS and version:**    
CHE - 5.15.0 ; Chrome 59.0 ; Fedora 25

**Attachment**
![codenvy dashboard new workspace](https://user-images.githubusercontent.com/22724619/28071862-e8440624-6659-11e7-9526-069c3e83f569.png)

**Comment by slemeur** [comment]
@ashumilova : we should not let a user start a workspace with RAM under 1GB

**Comment by ashumilova** [comment]
@slemeur it was done on purpose - users were asking for ability to start machine with 512Mb (database for example).
