### ISSUE TITLE
Add stack with predefined options

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5605]
- Maybe should create some action buttons on all default stacks, who will be redirecting to the create stack page with this stack predefined options.
- Or maybe should redirecting to the "dashboard/#/stacks" page after click on "Add Stack" button. And in this page rename "Add Stack" button on "Add New Stack".

![codenvy dashboard stacks](https://user-images.githubusercontent.com/22724619/28073889-d4aef974-665f-11e7-80fa-fcdd09491702.png)

- In my opinion, this is not very usable - one default stack (Java) on all cases.

**Comment by gorkem** [comment]
Closing
