### ISSUE TITLE
Che tries to pull local images (and fails)

### ISSUE THREAD

**Issue by iamslite** [eclipse-che/che#5607]
When configuring a custom stack that uses an 'image' Che tries to pull the image. This fails if the image is purely local.

**Reproduction Steps:**

Build an image on the host, using '-t' to tag it. Then reference it (eg in an composer recipe)

```
version: '2'
services:
  web:
    image: my_image
``` 
In the default configuration, with `CHE_DOCKER_ALWAYS__PULL__IMAGE` set to `true`, che tries to pull the latest version, which obviously fails.

If the image is not marked as coming from an upstream repository then it should not be pulled (or at least the failure to pull the image should not be considered a hard failure in this case.)

The workaround is obviously to restart che with `CHE_DOCKER_ALWAYS__PULL__IMAGE` set to `false`, but as noted this has potential currency issues for other images.

**Comment by ghost** [comment]
@iamslite this is expected behavior. The abovementioned property defines behavior. 

What you propose is check if an image is available in the repo, if it's not there, check if it's available locally and fail only in case both check fail?

**Comment by iamslite** [comment]
Well according to docker my local image name *is* the repository. However, yes, that is in essence what I'm suggesting.

**Comment by ghost** [comment]
@garagatyi what do you think about it?

**Comment by garagatyi** [comment]
It is not really possible to check whether image is local or not. We can only try to pull and see what will happen. That's why there is a property for that.
How do you expect to differ those images that should not be pulled from those that should be pulled?
What if the image exists in remote registry, but we don't have rights to pull it (in this case response would be as there is no such an image)?

**Comment by iamslite** [comment]
How about looking at the RepoTags. For something to be in a registry this would be set -- either because you have tagged it in order to be able to push it or because it was brought down when the image was pulled. Just building a local image will not cause it to have a tag.

So the flow would be that if it has a tag and `CHE_DOCKER_ALWAYS__PULL__IMAGE` is `true` then the pull must succeed in order for the image to be used. The other two cases (no tag, or tagged but `CHE_DOCKER_ALWAYS__PULL__IMAGE` is `false`) mean that no pull is required.

**Comment by ghost** [comment]
> Just building a local image will not cause it to have a tag.

Why is that? Can't I build a local image `eivantsov/che:4.3.6` and never push it to DockerHub?

**Comment by garagatyi** [comment]
There is an ability to pull images that doesn't have tags from registry. Or pull some image without using its tag

**Comment by ghost** [comment]
Agree with @garagatyi there's no way to tell a local image from non-local.

I won't close the issue to let ppl have their say, however, I personally think current behavior with switching property value is quite logical and intuitive.

**Comment by ghost** [comment]
Closing as expected behavior.
