### ISSUE TITLE
How to support highlights for comments

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5608]
Hi, I try to enable highlights for single line comments. In orion, following code can be used to highlight comment in editor.
<img width="201" alt="screen shot 2017-07-12 at 1 14 59 pm" src="https://user-images.githubusercontent.com/10006307/28102787-28a9a548-6704-11e7-87ac-e35d3a67ca89.png">

```
id: "SQL",
            contentTypes: ["text/sql", "text/sqlSegment"],
            patterns: [
                {include: "#comment_singleLine"}, 
```
and following code can be used to define the prefix of comment
```
repository: {
                comment_singleLine: {
                    match: {match: "--.*", literal: "--"}, 
                    name: "comment.line.double-dash", 
                    patterns: [
                        {
                            include: "orion.lib#todo_comment_singleLine" //$NON-NLS-0$
                        }
                    ]
                }
            } 
```

Document from Orion:
_Implementations of orion.edit.highlighter define the following attributes:
**id**
String A name that uniquely identifies this grammar.
**contentTypes**
String[] An array of Content Type IDs that this grammar will be used for.
**patterns**
Object[] An array of pattern objects to be used to assign style classes. Pattern objects are described below.
**repository**
Object Optional. A set of named pattern objects that can be referenced by this grammar and others._

In Che, I can enable highlight for some keywords by OrionHighlightingConfigurationOverlay. But`#comment_singleLine` does not work, comments is not highlighted.
And OrionHighlightingConfigurationOverlay does not support set repository, so I can not set the comments prefix. 
Does any one know how to enable comments highlight in Che?

**Comment by ghost** [comment]
@azatsarynnyy @evidolob can you help here?

**Comment by qi-min** [comment]
@azatsarynnyy @evidolob Any comments?

**Comment by ghost** [comment]
@m7luffy btw, there's such an issue https://github.com/eclipse/che/issues/5330 Once it's done, Monaco provides far more comprehensive docs.

**Comment by eivantsov** [comment]
Closed due to inactivity
