### ISSUE TITLE
Provide all endpoints of an server as separate servers in Runtime

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#5609]
Related to SPI branch only. 
Some servers have several endpoints for clients. For example, exec server has REST API and websocket JSON_RPC API. wsagent has REST API and websocket JSON_RPC API. 
It is not convenient for a client to know insights of these servers deployments to findout how to change server URL to connect to different endpoints.
So, we decided that if for example, an installer provides a server with several endpoints these endpoints should be represented as several servers with different references. In that case, client wouldn't need to modify server URL to connect to different endpoints.

**Comment by gazarenkov** [comment]
@garagatyi please provide more concrete specification of what exactly endpoints (ref, url format) proposed for existed agents (servers), such as exec, terminal, ws-agent...

**Comment by garagatyi** [comment]
I suggest to not change existing servers' references and add new. Something like:
```
{
    "servers" : {
        "wsagent" : {
            "url" : "http://172.17.0.1:32500/api"
        },
        "wsagent/jsonrpc" : {
            "url" : "ws://172.17.0.1:32500/websocket"
        },
        "exec-agent" : {
            "url" : "http://172.17.0.1:32501/api"
        },
        "exec-agent/jsonrpc" : {
            "url" : "ws://172.17.0.1:32500/connect"
        },
        "terminal" : {
            "url" : "ws://172.17.0.1:32502/pty"
        }
    }
}
```
@gazarenkov @evoevodin WDYT?

**Comment by voievodin** [comment]
I would change the references to
```
{
    "servers" : {
        "wsagent/http" : {
            "url" : "http://172.17.0.1:32500/api"
        },
        "wsagent/ws" : {
            "url" : "ws://172.17.0.1:32500/websocket"
        },
        "exec-agent/http" : {
            "url" : "http://172.17.0.1:32501"
        },
        "exec-agent/ws" : {
            "url" : "ws://172.17.0.1:32500/connect"
        },
        "terminal/ws" : {
            "url" : "ws://172.17.0.1:32502/pty"
        }
    }
}
```
First, because it is not clear what reference should be default for which server, for example
while for exec-agent it makes sense to have _ws://host:port/connect_ ref as default(REST API is not used by IDE and the other our clients) for wsagent it might be useful to use REST API endpoint as default instead.

Second,  jsonrpc is different level of abstraction, AFAIU the main idea is to separate http/ws/other endpoints while jsonrpc can work on top of any of them.

The unified format also brings its benefits.

**Comment by garagatyi** [comment]
If backward compatibility here is not really required, probably it is not, then I agree that unified format is better and doesn't require us to decide which endpoint is the default. 
What if software provides 2 different servers with the same protocol? Then ws/http doesn't fit here. Sure it is theoretical and is not case for our current servers, while we can't force devs of new servers in Che to stick to the same notation we use.

**Comment by gazarenkov** [comment]
Backward compatibility is not an issue here (anyway the format is not backward compatible with 5).
I am fine with format like "wsagent/http" and let's take it as a name only i.e. it is not specified that after slash protocol expected, it is just a unique name and putting protocol is just the simplest clear way to express what is it.
