### ISSUE TITLE
CHE-641 Add default blank stack

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#561]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-641
Reporter:  Stévan Le Meur
Description: We need to add a Blank ready-to-use stack.
When the user select Blank ready-to-use stack, we will also provide a sample project, which will come with a readme.md file.

In this readme.md file we will provide information for:
- how to import a project
- how to change the project type (if Java...)
- how to add commands
- how to install software in the terminal
- how to make a snapshot.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/83b066aa6c48fabba3a178e93cf8cd385887dc79
