### ISSUE TITLE
Sometimes there is not a possibility to create a workspace from dashboard in CHE

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5613]
After clicking the "Add a workspace" button the page freezes
**OS and version:**
CHE 5.15.0; Chrome 59.0 ; Fedora 25
![config-7](https://user-images.githubusercontent.com/7760565/28106269-ec98a968-66eb-11e7-8d1a-6f1975b20ed0.gif)

**Comment by daesmondid** [comment]
![error](https://user-images.githubusercontent.com/14317482/28110771-ab5db29c-66f3-11e7-9df3-96360964d5ff.png)
Yes, I also have this issue after the latest pull and merge from the che git; create workspace is not working.
**OS and version:**
CHE 5.15.0; CHE Docker nightly; Chrome 59.0.3071.115;  Mac OS Sierra 10.12.5

**Comment by ashumilova** [comment]
@daesmondid Merged the fix - could you please check.

**Comment by daesmondid** [comment]
@ashumilova Thank you, I'm now able to successfully create a workspace; problem solved!

**Comment by SkorikSergey** [comment]
Fixed.
