### ISSUE TITLE
Java packages are not displayed in the new created java project

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5624]
Java packages are not displayed in the new created java project, they will be shown only after refresh browser.

**Reproduction Steps:**
 - Go to dashboard and create java stack with spring project
 - Wait until workspace will be started
 - Expand project explorer tree
 - Pay attention to the "java" folder and another packages

**Expected behavior:**
Java packages will be displayed like packages but not like folders

**Observed behavior:**
Java packages are displayed like folders

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**
![config-10](https://user-images.githubusercontent.com/22724619/28119080-3d1a09a6-671c-11e7-9db3-cb72d60f665c.gif)

**Comment by musienko-maxim** [comment]
duplicated: https://github.com/eclipse/che/issues/5545

**Comment by Ohrimenko1988** [comment]
Issue #5545 is includes but not describe the problem what we have. So issue is reopened and attached to the #5545 as one of the description of the problems

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
