### ISSUE TITLE
Custom Stack by 'stacks-archetype' does not work 

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5628]
Hi, I am try to custom stack by Archetype assembly, add our stacks by default in Che server. I try following code from archetype generate and template 'stacks-archetype'.
But the stacks are not customized after start the server, all the stacks are displayed and I do not see the custom stack. 

Here are the steps I try:
1. generate assembly
```
docker run -it --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /data/Che/test/archetype_stack:/archetype \
  -v /data/Che/test/data_stack:/data \
  -v /root/.m2/repository:/m2 \
    eclipse/che:5.14.0 archetype generate --archid=stacks-archetype --che
```
And select 7)
```
7) stacks-archetype               - Assembly with sample stack packaging module, for using custom stacks in assemblies
Please enter your choice: 7
```
2. run 'mvn clean install' under /data/Che/test/archetype_stack/assembly

3. start Che 
```
docker run -it --rm --name run-che \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /data/Che/test/data_stack:/data \
           -v /data/Che/test/archetype_stack/assembly/assembly/assembly-main/target/eclipse-che-5.14.0/eclipse-che-5.14.0:/assembly \
              eclipse/che:5.14.0 start --skip:nightly
```

**Comment by vnea** [comment]
Hello,

It currently doesn't work with CHE 5.14.0: #5548.
Apparently it will work with CHE 5.14.1.

**Comment by ghost** [comment]
@m7luffy @vnea the bug is fixed, this artifact has been released and published.

@m7luffy you need to tun mvn clean install in the ide directory first to build your custom jar.

Here's what I have got after having followed your steps + building ide module before building Che assembly:

![image](https://user-images.githubusercontent.com/5337267/28159984-7b957b10-67c7-11e7-9558-e6f8628d4eb6.png)

**Comment by qi-min** [comment]
@eivantsov Is it fixed in 5.14.1? Or I can continue using 5.14.0 but build ide module first?

**Comment by ghost** [comment]
> the bug is fixed

> I can continue using 5.14.0 but build ide module first?

Correct!

**Comment by qi-min** [comment]
@eivantsov 
I build IDE first, but I still can not see the custom stacks. I can see these jars under ide/assembly,
```
root@huber1:/data/Che/test/archetype_stack/assembly/ide/assembly/target# pwd
/data/Che/test/archetype_stack/assembly/ide/assembly/target
root@huber1:/data/Che/test/archetype_stack/assembly/ide/assembly/target# ls
che-stacks-sample-5.14.0-sources.jar  che-stacks-sample-5.14.0.jar  classes  findbugs  maven-archiver
```
But this directory is still empty
archetype_stack/assembly/assembly/assembly-main/target/eclipse-che-5.14.0/eclipse-che-5.14.0

**Comment by ghost** [comment]
Build ide first, then assembly-che.

**Comment by qi-min** [comment]
@eivantsov yes, I run clean install under ide first.
1. /data/Che/test/archetype_stack/assembly/ide# mvn clean install
2. /data/Che/test/archetype_stack/assembly/assembly-che# mvn clean install

**Comment by ghost** [comment]
@m7luffy you should be all set now then

**Comment by qi-min** [comment]
@eivantsov   I finally get it works after I clean the data directory, thank you very much.

One more question, must the stack.json be put under ide? May I put these stack definitions in a plugin?

**Comment by ghost** [comment]
Yes, your plugin can provide this jar. Just make sure, your stacks.json gets into resources. And the default stacks artifact is excluded.

**Comment by qi-min** [comment]
@eivantsov  If I do not exclude the default stack, will my stack be added into default stacks list?

**Comment by ghost** [comment]
You didn't, the assembly did :) You may want to look at pom.xml of assembly-wsmaster-war module:

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <overlays>
                        <overlay>
                            <groupId>org.eclipse.che</groupId>
                            <artifactId>assembly-wsmaster-war</artifactId>
                            <type>war</type>
                            <includes>
                                <include>**/**</include>
                                <include>META-INF/context.xml</include>
                                <include>META-INF/web.xml</include>
                            </includes>
                            <excludes>
                                <exclude>WEB-INF/lib/che-core-ide-stacks-${che.version}.jar</exclude>
                            </excludes>
                        </overlay>
                    </overlays>
                </configuration>
            </plugin>
```

**Comment by qi-min** [comment]
@eivantsov How can I add my custom stacks to Che and keep the default ones?

**Comment by ghost** [comment]
You may add default stacks to your custom stacks.json.

**Comment by qi-min** [comment]
got it, thank you!
