### ISSUE TITLE
Improve experience when adding projects to a workspace

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#5633]
With the new creation flow the UX of adding new projects is not clear enough.

![screen shot 2017-07-13 at 11 52 39](https://user-images.githubusercontent.com/1636769/28160878-cc5e7af2-67c1-11e7-98ec-aa3505d33001.png)

When the user is adding a project, he would select it from the list of templates or repo, but he might easily forgot (or missing) to click on "Add" button to validate the action.

I propose the following improvements:
- We don't automatically show the popover to add project. We'll require the user to click on the blue button "Add or import project"
- We change the color of the primary action in the popover to be more present and avoid the user to miss it. We would use the primary blue button for the "Add".

**Comment by SkorikSergey** [comment]
I think we need move **Add - Cancel** button to be close to project's checkboxes.

**Comment by slemeur** [comment]
We could do that too @SkorikSergey .
