### ISSUE TITLE
Make it possible to configure different WebSocket message receivers in IDE

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#5635]
Now we have two implementations of WebSockets in IDE:
* [the older one](https://github.com/eclipse/che/blob/master/ide/commons-gwt/src/main/java/org/eclipse/che/ide/websocket/WebSocket.java) was developed a long time ago mainly for using it in conjunction with everREST;
* [the newer one](https://github.com/eclipse/che/tree/master/ide/commons-gwt/src/main/java/org/eclipse/che/ide/websocket/impl) more flexible and configurable which used now for JSON-RPC messaging.

No need for the older impl since we've been removed `everREST over WebSocket` support from IDE in CHE6. But there's still [one place](https://github.com/eclipse/che/blob/spi/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/terminal/TerminalPresenter.java#L147) where we need to use a WebScoket connection for raw (non JSON-RPC) messaging. In order to replace it with the newer WebSocket impl we need to be able to configure different implementations of [WebSocketMessageReceiver](https://github.com/eclipse/che/blob/spi/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/websocket/commons/WebSocketMessageReceiver.java).

Because now we have [a single implementation](https://github.com/eclipse/che/blob/spi/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/JsonRpcMessageReceiver.java) of WebSocketMessageReceiver used for transforming a raw web socket message to a JSON-RPC known structure.

**Comment by azatsarynnyy** [comment]
need for #5637

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
