### ISSUE TITLE
Can`t manage cursor from keyboard in the quick fix window 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5643]
**Reproduction Steps:**
 - Create java stack with project
 - Open java class 
 - Type in the editor "String str = 5;"
 - Wait until error marker will be displayed and press "Alt + Enter"
 - Try to press arrows in the keyboard
 - Pay attention to result

**Expected behavior:**
Cursor will be moved 

**Observed behavior:**
Cursor is not moved, and cursor is not displayed at all .

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![aaaa-1](https://user-images.githubusercontent.com/22724619/28211063-64d187f2-68a3-11e7-8b52-de8f1142cc7a.gif)

**Comment by slemeur** [comment]
This breaks the use of auto-completion. it's a regression and needs to be fixed for 5.15

**Comment by Ohrimenko1988** [comment]
This is not regression, because this is problem also reproduced on codenvy.io , and i think that it was in previous versions also .

**Comment by riuvshin** [comment]
it was never working yet :)
