### ISSUE TITLE
A notification text shows with html tags while uploading a SSH key

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5648]
**Reproduction Steps:**
- Create a workspace 
- Menu **Profile** -> **Preferences** -> **SSH** **Machine** or Menu **Profile** -> **Preferences** -> **SSH** **VCS**
- Create a new SSH key by clicking on the **Generate Key** button
- Upload a new SSH key and set it title as in the previous key

**Expected behavior:**
There is an error notification about SSH key with this title exists already

**Observed behavior:**
The notification text shows with html tags.

**Che version:** 5.15.0-SNAPSHOT
**OS and version:** Fedora 25

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config-18](https://user-images.githubusercontent.com/7760565/28214928-d77de3f2-68b4-11e7-9db0-4910646b3a24.gif)
![screenshot from 2017-07-14 16-39-16](https://user-images.githubusercontent.com/7760565/28214994-1d3c7458-68b5-11e7-9468-6a85df45ad57.png)

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa is this up to date issue?

**Comment by SkorikSergey** [comment]
This issue is actual for Che 6.8.0-SNAPSHOT.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
