### ISSUE TITLE
Creating stacks names  with symbols : "-" , "+" , "." is possible

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5649]
**Reproduction Steps:**
 - Go to the "Stacks" -> "Add Stack"
 - In the name field input "--------" or ".+-" 
 - Click "Save" button
 - Pay attention that stack name is saved

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**
![eclipse che new workspace](https://user-images.githubusercontent.com/22724619/28215242-f169729e-68b5-11e7-84ee-7d684b93b1f7.png)

**Comment by SkorikSergey** [comment]
It is possible to create a stack with a name consisting only of spaces.
![eclipse che stacks - google chrome_002](https://user-images.githubusercontent.com/7760565/31233673-d5f1e358-a9f5-11e7-90a8-920bae9c23ac.png)

**Comment by pmiranda07** [comment]
Hi Guys, I'm part of a group that is trying to build/run the project eclipse che in eclipse oxygen to try to solve this issue and others...we're having some troubles...we already saw some guides available but we still can't run the project...can anyone help us please?

**Comment by ghost** [comment]
@pmiranda07 can you open a separate issue with detailed description of the problems you have with Eclipse Che?

**Comment by pmiranda07** [comment]
@eivantsov Alright i will create a issue

**Comment by pmiranda07** [comment]
@eivantsov here it is the issue [https://github.com/eclipse/che/issues/7329](url)

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa  is this up to date issue?

**Comment by SkorikSergey** [comment]
This issue is actual for Che 6.8.0-SNAPSHOT.
