### ISSUE TITLE
Wrong order of stacks after sorting

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5650]
**Reproduction Steps:**
 - Open "Dashboard"
 - Click on the "Workspace" -> "Add Workspace"
 - On "New Workspace" page click on the "ALL" button
 - Pay attention that first three stacks should be in the static order, independent from what sorting is used
 - Click on "NAME" button
 - Pay attention that buttons are changed their positions

**Expected behavior:**
First three stacks should be in the static order, regardless of what kind of sorting is used.

**Observed behavior:**
First three stacks change their order

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25
**Failed selenium test:** NewWorkspacePageTest

**Attachment:**

![aaaa 1](https://user-images.githubusercontent.com/22724619/28215708-95207ae4-68b7-11e7-8d30-8cf6b9e9e6e9.gif)

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa  is this up to date issue?

**Comment by SkorikSergey** [comment]
This issue is actual for Che 6.8.0-SNAPSHOT.
