### ISSUE TITLE
Need to move OutputCustomizers to the according plugins and make them to be loaded according to workspace's settings

### ISSUE THREAD

**Issue by vrubezhny** [eclipse-che/che#5652]
Currently all the existing Output Customizers are placed into `che-core-ide-app`. However it  doesn't appear to be a correct to tCore IDE App to hold the output customizers for the different runtimes...

We need to move OutputCustomizers to the according runtime plugins and make them to be loaded according to workspace's settings (or a list of runtimes used in the workspace projects).

**Comment by gorkem** [comment]
@vrubezhny Is this still a valid issue?

**Comment by vrubezhny** [comment]
@gorkem As we moved to use more or less native VSCode extensions (with no additions/changes)  I don't think so. 
Anyway, the current PR cannot be easily rebased and probably needs to be re-developed from the very beginning
