### ISSUE TITLE
Adapt existing selenium tests that use workspace details page

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5653]
As far as new workspace details page is introduced, the existing selenium tests need to be adapted to proper test this stuff.
The task can be divided into phases:
- [ ] Overview page
- [ ] Machines page
- [ ] Environment variable page
- [ ] Servers page
- [ ] Agents page
- [ ] Projects page

The new stuff can be found on https://a2.codenvy-stg.com :

**Comment by ashumilova** [comment]
Overview page
![image](https://user-images.githubusercontent.com/1611939/29169383-788d3220-7ddc-11e7-9996-5c1d374a0126.png)

**Comment by ashumilova** [comment]
Machines page
![image](https://user-images.githubusercontent.com/1611939/29169869-dbaec7d6-7dde-11e7-9b89-c82ad54d4574.png)

**Comment by ashumilova** [comment]
Agents
![image](https://user-images.githubusercontent.com/1611939/29169886-f08edc4a-7dde-11e7-8472-19278e2bc88b.png)

**Comment by ashumilova** [comment]
Servers: 
![image](https://user-images.githubusercontent.com/1611939/29169907-047a313c-7ddf-11e7-9ffe-c451a2a2ab78.png)

**Comment by SkorikSergey** [comment]
Merged https://github.com/eclipse/che/pull/6214.
