### ISSUE TITLE
Hash "#" character in filename causes multiple issues

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5655]
Steps to reproduce:

1. Create a file with `#` in its name, say, `new#new`
2. The file gets successfully created with the abovementioned name (API returns 201)
3. However, when opening a file, GET request fails with 404, since Che looks for a file named `new`, ie everything after `#` is cut out. Therefore, it is impossible to open, edit or delete a file.

Perhaps, file name should be validated not to contain `#`

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
