### ISSUE TITLE
Wrong alignment in team workspaces table

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5656]
_From @vitaliy-guliy on February 1, 2017 11:59_

Fix alignment in team workspaces table.

![wrong alignment](https://cloud.githubusercontent.com/assets/1655894/22505970/9f4299d2-e886-11e6-9efd-a9b443314dd2.png)

_Copied from original issue: codenvy/codenvy#1671_

**Comment by eivantsov** [comment]
_From @vitaliy-guliy on February 1, 2017 12:2_

The same we have in Menu -> Workspaces

![wrong alignment 2](https://cloud.githubusercontent.com/assets/1655894/22506034/f31a6288-e886-11e6-8425-7e493145e144.png)

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
