### ISSUE TITLE
che sync command ignores ~/.unison local profile

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5658]
_From @janat08 on April 23, 2017 21:25_

I'm on opensuse tumbleweed/linux with exposed hidden folders. 

I've run this command
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/Docker/:/data -v ~/Documents/Docker/:/sync eclipse/che sync meteor --url https://codenvy.io --password * --user * --unison-verbose

I returns this versions: (che cli): 5.8.0 - using docker 1.13.0

**Codenvy cli.log output:**  

_Copied from original issue: codenvy/codenvy#2127_

**Comment by ghost** [comment]
_From @TylerJewell on April 23, 2017 21:27_

Can you elaborate further?  I believe that this is a folder that you create
on your system, and then you provide the unison profile that you want
locally to define the nature of the synchronization that you desire.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by ghost** [comment]
_From @janat08 on April 23, 2017 21:37_

Right, its just that the doc read that it's meant to be there, so I worried that it is awry.

**Comment by ghost** [comment]
_From @TylerJewell on April 23, 2017 21:39_

Yeah, I think the docs could be clearer on this point. It's a file that you must add locally before you do the sync, and the sync utility will use it as its definition.

**Comment by ghost** [comment]
_From @janat08 on April 23, 2017 22:29_

I actually misread the instructions about how file should be there.

**Comment by ghost** [comment]
_From @janat08 on April 24, 2017 0:48_

Doesn't work. What to diagnose?>

**Comment by ghost** [comment]
_From @janat08 on April 24, 2017 0:54_


Codenvy version: 
INFO: (che cli): 5.8.0 - using docker 1.13.0 / native

OS and version:
Opensuse tumbleweed.

**Docker version:**

Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7
 Git commit:   78d1802
 Built:        Wed Mar 22 23:25:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7
 Git commit:   78d1802
 Built:        Wed Mar 22 23:25:45 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Codenvy cli.log output:** 
INFO: (che mount): Starting sync process to /home/jk/Documents/Docker/
Mon Apr 24 00:29:47 UTC 2017
/usr/bin/curl "-I -k https://hub.docker.com -s -o /dev/null --write-out %{http_code}"
Checking registry for version '5.8.0' images
eval BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
eval BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.8.0
eval IMAGE_INIT=eclipse/che-init:5.8.0
eval IMAGE_CHE=eclipse/che-server:5.8.0
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.8.0
eval UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.8.0
eval UTILITY_IMAGE_CHETEST=eclipse/che-test:5.8.0
eval UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.8.0
INFO: (che cli): 5.8.0 - using docker 1.13.0 / native
/usr/bin/curl "-s https://hub.docker.com/v2/repositories/eclipse/che/tags/"
INFO: Newer version '5.8.1' available
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-action:5.8.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-dir:5.8.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-test:5.8.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-mount:5.8.0'... found
INFO: (che mount): Starting sync process to /home/jk/Documents/Docker/

**Comment by ghost** [comment]
@janat08 is the process just stuck? Please provide more details otherwise it's difficult to help you

**Comment by ghost** [comment]
_From @janat08 on April 24, 2017 8:55_

It won't listen to default.prf
```
ignore = Path garlic/node_modules
ignore = Path */node_modules
```

**Comment by ghost** [comment]
Have you mounted your custom unison config? What's your docker run syntax?

**Comment by ghost** [comment]
_From @janat08 on April 24, 2017 9:12_

docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/Docker/:/data -v ~/Documents/Docker/:/sync eclipse/che sync meteor --url https://codenvy.io --password * --user * --unison-verbose

I 've created it in directory specified ./che/unison where it's meant to be installed itself.

**Comment by ghost** [comment]
@janat08 perhaps you need to add `-v ${HOME}/.unison:${HOME}/.unison` to your run syntax, to make sure that your custom unison config is respected?

**Comment by ghost** [comment]
_From @janat08 on April 24, 2017 9:23_

documentation says che will look look for that directory by itself, but ill give it a go

**Comment by ghost** [comment]
@janat08 can you point to exact section in docs that says that?

**Comment by ghost** [comment]
_From @janat08 on April 24, 2017 9:28_

in sync>optimization

**Comment by ghost** [comment]
_From @janat08 on April 25, 2017 4:23_

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/Docker/:/data -v ${HOME}/.unison:${HOME}/.unison -v ~/Documents/Docker/:/sync eclipse/che sync meteor --url https://codenvy.io  --password * --user * --unison-verbose
```
Doesn't work, and replacing ${HOME} with ~/.che/unison doesn't work:
```
docker: Error response from daemon: invalid bind mount spec "/home/jk/.che/.unison:~/.che/unison": invalid volume specification: '/home/jk/.che/.unison:~/.che/unison': invalid mount config for type "bind": invalid mount path: '~/.che/unison' mount path must be absolute.
```

**Comment by ghost** [comment]
`~/.che/unison` does not work as expected - you have got a Docker error.

I'll take a look and give it a shot myself.

**Comment by ghost** [comment]
@janat08 Indeed, docs are wrong - just having ~/.unison with a default profile file isn't enough.

This command worked for me, and Ctrl+C interrupts it ok. Also, I have tested my unison profile, and exclusions were respected.

`docker run --rm -it -e "CHE_VERSION=5.8.1" --security-opt apparmor:unconfined --cap-add SYS_ADMIN --device /dev/fuse --name che-mount -v /var/run/docker.sock:/var/run/docker.sock -v /etc/group:/etc/group:ro -v ~/.unison:/profile -v ~/Documents/sync/:/mnthost eclipse/che-mount python --url https://codenvy.io --password $pass --user $user --unison-verbose`

**Comment by ghost** [comment]
_From @janat08 on April 25, 2017 10:2_

I won't close the other issue for interrupt since these -v have to probably be passed by che CLI, this open too.

**Comment by ghost** [comment]
Yes, both issues are legitimate and they are bugs.

**Comment by ghost** [comment]
To recap:

1. eclipse/che sync command does not have any arguments to respect a local unison profile
2. Docs https://codenvy.io/docs/user-guide/sync/index.html#optimize are wrong

**Comment by ghost** [comment]
_From @garagatyi on July 6, 2017 5:27_

@TylerJewell should we move it to Che?

**Comment by SkorikSergey** [comment]
Is this still an issue?

**Comment by gorkem** [comment]
Closing as this does not seem to be valid anymore
