### ISSUE TITLE
Log data when user access a workspace

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5659]
_From @tolusha on August 27, 2016 12:56_

Write to log file each time when user access a workspace. Log file should be located near the tomcat access log.

Log data:
- access timestamp in  some universal format.
- user name
- workspace id 
- workspace name

Trigger:
- User request a workspace by @GET  'api/workspace` method

_Copied from original issue: codenvy/codenvy#638_

**Comment by ghost** [comment]
_From @tolusha on August 28, 2016 7:10_

@bmicklea @TylerJewell any requirements or we can postpone these issue?

**Comment by ghost** [comment]
_From @TylerJewell on August 28, 2016 12:7_

Ok for me

**Comment by ghost** [comment]
_From @tolusha on August 29, 2016 11:29_

> What kind of info to log

accessTime userId workspaceId permissions

> What triggers should initiate logging

`api/workspace/get` method

**Comment by ghost** [comment]
_From @TylerJewell on August 29, 2016 14:4_

I think you are assuming that this is logging access through the Codenvy server.  But I think that this would need to be any time that someone accesses the workspace directly.  Since we do not proxy all user traffic through the Codenvy server, wouldn't this need to be something in the ws agent that logs the access back to the codenvy core?

The access would be any time someone does something that causes one of our agents to be accessed on the workspace.  The agent would then log an agent access back with Codenvy for the user.

accessTime would be day / time in some universal format.
userid would be the username (pretty format) so tylerjewell@gmail.com if an email address
workspaceid would be the workspace id + workspace pretty name

Permissions would not be part of this logging.  In the other issue where we display the permissions that a user has for each workspace they are a member of, then we would show their permission type there.  This issue is specifically about when a user accesses a workspace.

**Comment by ghost** [comment]
_From @tolusha on August 29, 2016 14:15_

No Codenvy server. Ws master will log data once user requests a workspace.

**Comment by ghost** [comment]
_From @TylerJewell on August 29, 2016 14:19_

We need to assume that every access a user makes to any agent in a ws, will need to be logged as access in codenvy master.

**Comment by ghost** [comment]
_From @tolusha on August 29, 2016 14:22_

Do you mean ws-agent/terminal? anything else?

**Comment by ghost** [comment]
_From @TylerJewell on August 29, 2016 14:25_

Yes, fair question.  I think ws-agent and terminal agent - those two make sense.

**Comment by ghost** [comment]
_From @tolusha on August 29, 2016 14:38_

Logging access to the terminal - an issue. Can't be solved quickly.

**Comment by ghost** [comment]
_From @TylerJewell on August 29, 2016 14:39_

Ok to defer that.  Just handle ws-agent access initially.

**Comment by ghost** [comment]
_From @tolusha on August 29, 2016 14:51_

I've updated the description.

**Comment by ghost** [comment]
_From @TylerJewell on July 5, 2017 13:48_

@slemeur @bmicklea - do we think this is still useful in a k8s world?

**Comment by ghost** [comment]
_From @bmicklea on July 10, 2017 16:51_

up to @slemeur but I would assume the logging in k8s would be a decent start.

**Comment by slemeur** [comment]
It depends what logs k8s are providing.

We will anyway need some sort of analytics and telemetry https://github.com/eclipse/che/issues/5483.  So I think this issue is still relevant.

**Comment by skabashnyuk** [comment]
@slemeur @eivantsov are we talking about ws-agent logs?

**Comment by ghost** [comment]
hm... that's a very old issue that was moved from Coednvy repo and I don't think it makes sense for Che.

**Comment by bmicklea** [comment]
Closing as no longer relevant. We can open a new issue if this is a requirement going forward.
