### ISSUE TITLE
Improve User Management page

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5660]
_From @vitaliy-guliy on January 30, 2017 14:40_

Improve User Management page:
- don't scroll action buttons and table header
- apply scroll only to the user list

![user management improved](https://cloud.githubusercontent.com/assets/1655894/22427114/80580ae8-e70a-11e6-870f-623db803ce87.png)

_Copied from original issue: codenvy/codenvy#1651_

**Comment by ghost** [comment]
_From @vitaliy-guliy on January 31, 2017 10:13_

In current version pager displays only one page but there are two.

![incorrect pager](https://cloud.githubusercontent.com/assets/1655894/22460666/9c72e76c-e7ae-11e6-8a31-b795246168e4.png)

**Comment by ghost** [comment]
_From @TylerJewell on July 5, 2017 14:13_

@ashumilova - is this still actual given the latest redesigns?

**Comment by ghost** [comment]
_From @ashumilova on July 6, 2017 6:33_

still actual

**Comment by ashumilova** [comment]
not actual
