### ISSUE TITLE
Squash layers when snapshoting containers

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5661]
_From @skryzhny on May 19, 2017 7:29_

As per problem described in #2199 we may implement additional enhancement: squash layers when snapshotting containers.

For frequently changed big files, like appending logs this may greatly help in reducing snapshot's image size and thus download/startup time.

**Reproduction Steps:**
Same as in #2199 

**Codenvy version:**    5.10.0-SaaS

_Copied from original issue: codenvy/codenvy#2218_

**Comment by ghost** [comment]
_From @garagatyi on May 19, 2017 7:33_

Maven local repo would do a lot of troubles here! So apparently this issue is very important for maven projects

**Comment by ghost** [comment]
_From @mmorhun on June 12, 2017 8:6_

For now docker cannot squash layers with commit operation (which is used for snapshotting).
In this situation we have at least 3 options:
- Write our own docker images squash tool.
- Try to get CQ for third-party code for squashing image layers (like [this](https://github.com/goldmann/docker-squash) or [that](https://github.com/jwilder/docker-squash)).
- Wait until this feature will be implemented in docker (see [this](https://github.com/moby/moby/issues/33633) issue).

**Comment by ghost** [comment]
_From @garagatyi on June 12, 2017 8:27_

> Wait until this feature will be implemented in docker (see this issue).

I believe this is not an option for us since we can't always control version of docker we are using.

**Comment by garagatyi** [comment]
We decided no to support snapshots in Che 6 [here](https://github.com/eclipse/che/issues/6213). So I'm suggestion closing the issue.

**Comment by mmorhun** [comment]
If so, let's close it.
