### ISSUE TITLE
Add dashboard UI for changing user permissions

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5662]
_From @bmicklea on October 6, 2016 16:22_

In Codenvy you can share a workspace with users by adding them to the workspace. However, you can't alter their access permissions through the UI. Only through the API.

It would be helpful to be able to select one or more users and click a "Permissions" button. When pressed this would bring up a popup:
- Title: Edit Workspace Permissions
- List all permissions with checkboxes beside each
- Buttons at the bottom are "Save" and "Cancel"

The popup should be styled like other popups in the product.

**Codenvy version:** 5.0.0-M4

_Copied from original issue: codenvy/codenvy#920_

**Comment by ghost** [comment]
_From @bmicklea on October 6, 2016 16:23_

@slemeur not sure if you want a design for this - it's pretty straightforward I think but it's up to you.

**Comment by ghost** [comment]
_From @TylerJewell on October 6, 2016 16:26_

I believe this scenario is handled by the team enhancements.

**Comment by ghost** [comment]
_From @TylerJewell on July 5, 2017 13:57_

@bmicklea @slemeur - is this issue still actual or does team management capabilities manage properly?

**Comment by ghost** [comment]
_From @bmicklea on July 10, 2017 16:48_

@TylerJewell still an issue - you can add people through the UI but can't select their permissions except via the API.

**Comment by slemeur** [comment]
I confirm - this is still an issue today
