### ISSUE TITLE
Show user email somewhere

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5663]
_From @vitaliy-guliy on January 30, 2017 14:2_

I cannot see email of the current user. It's displayed only when creating a team.
It would be great to display email in user menu or somewhere else.

![edit user](https://cloud.githubusercontent.com/assets/1655894/22425752/4cfa5868-e705-11e6-9a86-646c44039e7e.png)

![create team](https://cloud.githubusercontent.com/assets/1655894/22425775/600d4848-e705-11e6-9a49-5aef0022e9c0.png)

_Copied from original issue: codenvy/codenvy#1650_

**Comment by ashumilova** [comment]
Already have it in multi-user che on the profile page
