### ISSUE TITLE
Remove or replace api_token input on swagger landing page

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5664]
_From @skabashnyuk on November 9, 2016 14:26_

```api_token``` input is legacy field that comes from original swagger. In codenvy we use ```token``` query parameter so we should either remove it either replace with ```token```
<img width="1440" alt="2016-11-09 16 22 09" src="https://cloud.githubusercontent.com/assets/1614429/20141484/357af0c8-a699-11e6-9bac-a2a91cd746ad.png">

_Copied from original issue: codenvy/codenvy#1123_

**Comment by ghost** [comment]
_From @TylerJewell on July 5, 2017 14:0_

@skabashnyuk @mshaposhnik - is this still actual or has it already been resolved?

**Comment by skabashnyuk** [comment]
depends on https://github.com/eclipse/che/issues/6015
