### ISSUE TITLE
Don't add unregistered user to a team

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5669]
_From @vitaliy-guliy on February 1, 2017 9:45_

Do not allow to add unregistered user to a team.
The `Add` button has to be disabled if not registered user email is entered.

For now `Add` button is enabled and an error message is appeared after closing the popup.

![add unregistered user](https://cloud.githubusercontent.com/assets/1655894/22501814/1007d998-e873-11e6-92ad-822370d74b10.png)

![user is not registered](https://cloud.githubusercontent.com/assets/1655894/22501833/254259fa-e873-11e6-90aa-94d361d7ebcc.png)

_Copied from original issue: codenvy/codenvy#1670_

**Comment by ghost** [comment]
_From @vitaliy-guliy on February 1, 2017 10:1_

And also place `Add` button on the right in the `Invite developer` popup.

**Comment by ghost** [comment]
_From @ashumilova on February 1, 2017 13:2_

Not registered users will be possible to invite to team by sending email notification/invitation, now not implemented, so need to decide whether disable the add button and show error message on popup, or leave as it's now - notify user. Notification was first chosen to be able to invite multiply users (both mixed registered and not) and to list those not registered in notification, but still add existing ones.

**Comment by ghost** [comment]
_From @slemeur on February 8, 2017 14:55_

I think it is an enhancement that we can add later. This is not mandatory for the time being as a notification is shown.

The question is, how it is behaving when a user is doing "bulk invitation"? Are the registered users added and all the other ones listed in the error message? Are we displaying one notification per unknown email, or do we process and display a single notification?

**Comment by ghost** [comment]
_From @ashumilova on February 9, 2017 9:11_

With bulk invitation: the registered users are added and the unregistered are listed in one notification:
![image](https://cloud.githubusercontent.com/assets/1611939/22776503/8b2d5cf6-eeb8-11e6-9b81-a831450384e5.png)

**Comment by ashumilova** [comment]
the invitation is sent to unregistered user.
