### ISSUE TITLE
There is no way to specify password during registering via email.

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5672]
_From @sleshchenko on March 6, 2017 16:20_

There is no way to specify password during registering via email.

Dashboard in 3.x version asks user to update password immediately after signing up. But in 4.x version it doesn't and user should know that he should update password on Dashboard#Account & Account#Security when he signs up or he will have to recover password later.

We can implement such feature in codenvy dashboard 4.x
Or redirect user to {HOST}/site/setup-password page for setting up password after signing up with email.

_Copied from original issue: codenvy/codenvy#1888_

**Comment by ghost** [comment]
Yes, a simple redirect to dashboard account settings is a nice thing to do.

**Comment by skabashnyuk** [comment]
Will be fixed by https://github.com/eclipse/che/issues/5362 All workflow will be rewritten by this issue.
