### ISSUE TITLE
Stack management in user dashboard

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5674]
_From @ashumilova on June 1, 2017 12:22_

The system admin should be able to do following with the help of UI:
- [ ]  add stack(s) from json file - need to show "Import" button in the header of stack list
- [ ] export stacks - need "Export" button in the header of stack list, which exports selected stacks
- [ ] switch stack from personal to public and vice versa for existing stack and on creation

_Copied from original issue: codenvy/codenvy#2252_

**Comment by ghost** [comment]
_From @slemeur on June 9, 2017 12:35_

In the flow to create a new stack. Let's add a new section.

Section Title: “System stack”
Section Description: “Register a system stack for all users.”
Form component: switcher

If it’s Che -> by default yes
If it’s Codenvy -> if user is admin - by default yes. Other users will not see the section

**Comment by ghost** [comment]
_From @TylerJewell on June 9, 2017 12:58_

@slemeur - I changed the description to make it clearer.

**Comment by azatsarynnyy** [comment]
closing it as outdated
