### ISSUE TITLE
Recover servers logs streaming

### ISSUE THREAD

**Issue by voievodin** [eclipse-che/che#5675]
Bootstrapper continues streaming logs after workspace is started and there is at least one server.
But right now there is no way to _reconnect_ to the logs stream after master is restarted.
I see  several ways to solve this issue:
1. Bootstrapper attempts to reconnect to master once disconnected.
2. Master asks bootstrapper to continue logs streaming sending _push-logs-endpoint_ to it.
3. Master connects to bootstrapper and asks to stream logs using established connection.

I would start from the option 1, as it is the simplest way to achieve recovery.

The logs format is defined in the bootstrapper [spec](https://github.com/eclipse/che/issues/4096#issuecomment-283067971). 

Needed for #5097
Needs #5814

**Comment by garagatyi** [comment]
I believe that this issue is fixed by @evoevodin but doesn't work because of behavior described in #5814. Closing the issue, feel free to reopen if this feature won't work after the closure of the mentioned issue.
