### ISSUE TITLE
Support long Docker Registry passwords

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5678]
_From @wernight on March 18, 2017 8:57_

**Reproduction Steps:**

 1. Go to `/dashboard/#/administration` URL
 2. Click "Add Registry"
 3. Fill in:
      - Address: `https://gcr.io`
      - Username: `_json_key`
      - Password: Content of the file generated.

Should support long password to support for example pulling from [Google Container Registry](https://cloud.google.com/container-registry/docs/advanced-authentication) (which generates a JSON file which is the password and is about 2000 characters long).

**Codenvy version:** 5.5.0

_Copied from original issue: codenvy/codenvy#1948_

**Comment by ghost** [comment]
@wernight as a workaround, you may add your gcr details in codenvy.env.

Marking this one as improvement.

**Comment by ghost** [comment]
_From @wernight on March 21, 2017 19:44_

Set in `codenvy.env`:

    CODENVY_DOCKER_REGISTRY_AUTH_REGISTRY1_URL=https://eu.gcr.io
    CODENVY_DOCKER_REGISTRY_AUTH_REGISTRY1_USERNAME=_json_key
    CODENVY_DOCKER_REGISTRY_AUTH_REGISTRY1_PASSWORD='<content_of_file>'

It does no appear in the admin registry UI, which may be normal, but seems not working even though if I try manually on the CLI it works. Anyway using the `codenvy.env` should probably work and I probably made a mistake somewhere.

**Comment by ghost** [comment]
_From @wernight on March 31, 2017 8:3_

Note: This also affects Che.

**Comment by ghost** [comment]
@wernight yes, correct. And yes, not showing registries added in .env file in User Dashboard is expected.

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che/pull/13569
