### ISSUE TITLE
Stacks, Samples and Factories administration in Che

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5679]
_From @slemeur on March 8, 2017 16:41_

# Goals
Che system allow to control:
- Stacks
- Templates
- Factories
- Recipes

Today, a Che admin can provision Stacks and Templates for all users, but only by editing the `stacks.json` or `samples.json` files. 

The goals of this epic are to:
- Allow a Che admin to provision Stacks and Templates from Admin Dashboard (without having to edit the configuration files) for users + organizations
- Similarly, we'll need to allow the Che admin to provision Factories and Recipes.

### Linked issues:
https://github.com/codenvy/codenvy/issues/1002
https://github.com/codenvy/codenvy/issues/1780

_Copied from original issue: codenvy/codenvy#1902_

**Comment by gorkem** [comment]
#5165 seems to be related

**Comment by eivantsov** [comment]
@slemeur stack management is must have for enterprises that adopt Che on OpenShift. 

Adding a new global stack is a pain now.

Do you have a spec or should I come with some use cases that Admin dashboard should cover?

**Comment by gorkem** [comment]
@slemeur I am closing this one. Can you file a new one if you feel we need a new one that covers devfiles and registries?
