### ISSUE TITLE
Editor is not restored after refresh page sometimes

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#5682]
**Reproduction Steps:**
1. Open some java class
2. Split this one
3. Refresh page

Also please see video.
The issue is not reproduced permanently.

**OS and version:**    
Fedora 25
**Che version:**    
Version: 5.15.0-SNAPSHOT
Revision: 8d2e43bf6e44aa86
![restore_state](https://user-images.githubusercontent.com/5676062/28261318-59a46728-6ae7-11e7-8b35-7944f319e3d2.gif)

**Comment by SkorikSergey** [comment]
Not reproduced.
