### ISSUE TITLE
Implement URLRewriter for Docker infrastructure

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#5684]
Related to SPI branch only.
We replaced the concept of ServerEvaluationStrategy with URLRewriter in spi branch. Now URLRewriter impl doesn't change URLs at all. We need to create impl that can cover Docker infra needs, such as local Linux, remote Linux,  Windows, Mac environments.

**Comment by benoitf** [comment]
Hi, could you explain more how 'urlrewriter' is not changing URL at all ? Based on the name 'URL rewriter'  it seems it is rewriting URLs
Also what kind of changes are expected with Reverse proxy like traefic. And why it was required to change the interface of server evaluation strategy with something not backward compilant ? We couldn't do a helper ?

**Comment by garagatyi** [comment]
Hello. It is not changing URL because we have NoOp implementation only for now.
Whole SPI was redesigned for simplification, so pretty everything has changed.
> Also what kind of changes are expected with Reverse proxy like traefic.

I don't have anything specific in mind about reverse proxy for now.
