### ISSUE TITLE
Cannot consume a factory from workspace that have name with 20 symbols

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5685]
_From @musienko-maxim on February 16, 2017 10:15_

*Steps to reproduce:*
**See screencast:**
![anim](https://cloud.githubusercontent.com/assets/1640058/23017028/5c15870c-f441-11e6-9a91-413fac70ba36.gif)

**OS version:** Ubuntu 14 TLS, chrome browser
**Server location:** nightly.codenvy-stg.com
**Additional information:** It happens because a factory service adds suffix for creation a new workspace, that based on name main workspace and exceeds the allowable limit. We should validate this case in the IDE and User Dashboard

_Copied from original issue: codenvy/codenvy#1790_

**Comment by ghost** [comment]
_From @garagatyi on July 6, 2017 5:30_

@TylerJewell should we move it to Che?

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
