### ISSUE TITLE
Link recipe and configuration machines

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#5687]
Launching and resolving (already started) machines is implemented by OpenShift spi in following way:
1. Parse openshift recipe (aka kubernetes list in yaml format).
2. Create all objects from the recipe.
3. Bootstrap all containers with hardcoded installers.
4. For fetching all started machines - fetch all pods in openshift project and resolve servers by existing services and routes.

It is needed to rework this approach to:
- link recipe machines and configuration that are specified in the environment;
- bootstrap only specified in configuration installers;
- maybe store machines not to analyze openshift objects each time;
- publish events about machine status changes.

**Comment by bmicklea** [comment]
@sleshchenko I think this is an enhancement, but can you apply the correct label?
