### ISSUE TITLE
Add using of persistent volumes for storing sources of projects

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#5691]
Not to lose local changes in sources of projects after workspace restarting we should use persistent volumes for storing sources of projects.

**Comment by bmicklea** [comment]
Please add correct labels.

**Comment by gorkem** [comment]
Every PV has different characteristic depending on the backend performance may be different? Is this going to be configurable?

**Comment by akorneta** [comment]
@gorkem I'm not sure that I fully understand question, could you please clarify what exactly should be configurable?

**Comment by benoitf** [comment]
there are several implementations of PV : https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/index.html

**Comment by akorneta** [comment]
@benoitf So we do not manage PVs in che at all. The current issue is about adding PVCs for storing workspace projects. As far as I understand PVC doesn't provide an ability to choose which back end should be used. It is a part of OpenShift instance configuration managed by admins or I missed something?

**Comment by benoitf** [comment]
@akorneta when you claim a persistent volume, you ask for characteristics

https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/storage.html#persistent-volume-claims
like the access mode, etc.

so maybe you want to be able to choose options of the PV claim.

**Comment by gorkem** [comment]
It is not even that advanced. Some PVCs are slow for small writes but optimized for larger writes. I think we should have the option disable persistent volume storing in case we see that it affects the performance of the IDE.

**Comment by akorneta** [comment]
Current implementation of `OpenShiftConnector` has hard coded access mode to `ReadWriteOne` and has configurable `quantity`. I'm going to make configuration property for `quantity`. 
@benoitf Do you think that it makes sense to make access mode configurable?
> disable persistent volume

@gorkem But then we may lose changes of projects sources after workspace restart or crash. I think it is not good UX. Do you think it is acceptable?

**Comment by gorkem** [comment]
It is not good UX but I was thinking of it as a fallback if PV starts to render IDE unusable.

**Comment by akorneta** [comment]
@gorkem ok it makes sense I'll add appropriate config property
