### ISSUE TITLE
Error marker has not disappeared 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5692]
In some cases, error marker stay visible in editor even if mistake was fixed 
**Reproduction Steps:**
1) Use case:
 - Create workspace with java stack and default web-spring project
 - Open java class 
 - Remove one figure bracket 
 - Restore this bracket 
 - Pay attention to the error marker  

2) Use case:
 - Create workspace with java stack and default spring project
 - In the class body input "String s = "some text""
 - Click "Profile" -> "Prefferences" -> "Errors/Warnings"
 - In the "Value of local variable is not used" drop-down list choose "error"
 - Wait until warning marker will be changed to error marker 
 - Do the 2-nd, 3-rd, and 4-th steps but in drop-down list click on "ignore"
 - Pay attention that error marker is not disappeared  

3) Use case:
 - Create workspace with java stack and default spring project
 - Set cursor to 17-th line and press "Enter" , set cursor to the 17-th line     
 - Type "error" and wait for error marker
 - Press "Enter" twice 
 - Set cursor to 17 - th line and delete "error"
 - By pressing "Ctrl + Z" remove all changes
 - Pay attention to error markers 

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25

**Attachments:**
1) Use case :
![aaaa-1](https://user-images.githubusercontent.com/22724619/28266270-961fb422-6afc-11e7-9bed-f1169a94a5d2.gif)

2) Use case :
![aaaa_1](https://user-images.githubusercontent.com/22724619/28266323-dbf28a92-6afc-11e7-8b1c-eba2a838525c.gif)

3) Use case :
![aaaa-2](https://user-images.githubusercontent.com/22724619/28266340-f23b58ba-6afc-11e7-9203-468bb266f8b0.gif)

**Comment by bdshadow** [comment]
Couldn't replicate any of the use cases. 
My versions:
- Che: master branch (5.15.0-SNAPSHOT)
- Fedora 25
- Chrome 59.0.3071.104 (Official Build) (64-bit)

1st Use case
Doesn't happen at all. After i restored the bracket the error marker disappeared immediately
2nd Use case
The refreshment of the document took really much time (i feel like up to 10 seconds), but finally after applying any of the ["error", "ignore", "warning"] in any order the document was showed with the correct markers.
3rd Use case
After removing all changes by pressing "Ctrl-Z" several times, an error marker blinked for a moment but disappeared very quickly.

**Comment by SkorikSergey** [comment]
I reproduced all use cases. 
It is looks like in 3st use case will not be an errors marker if there is any warning.
![config-27](https://user-images.githubusercontent.com/7760565/28315757-91fa3b98-6bc8-11e7-9a1a-2f6c42da925a.gif)

**Comment by Ohrimenko1988** [comment]
**New use case that related to this issue :**
- Create java stack with default project
- Open java class and move code 
- Open context menu and click "Format"
- Pay attention that after code is formatted, error markers are displayed

**Attachment:**

![config-32](https://user-images.githubusercontent.com/22724619/28420513-13879ad6-6d6b-11e7-8cad-0280a2f88f65.gif)

**Comment by ghost** [comment]
I confirm these issues exist.
