### ISSUE TITLE
[Regression] A file opens in the Editor twice if double click on its name in the NavigateToFile widget

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5695]
**Reproduction Steps:**

1. Create a workspace from the **Java** stack with the **the web-java-spring** project
2. Menu **Assistant** -> **Navigate To File**
3. Type "po" symbols and double click on "**pom.xml**" from list
4. Close opened tab in the **Editor**
5. Do reproduction's steps 2-4  again

**Expected behavior:**
- Only one **pom.xml** opens in the **Editor**

**Observed behavior:**
- The **pom.xml** opened twice after selecting from list. For next time there the file will be opened 3 times.

**Che version:** 5.15.0-SNAPSHOT
**OS and version:** Fedora 25
**Failed test: NavigateToFileTest**

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![peek 2017-07-27 10-47](https://user-images.githubusercontent.com/7760565/28659867-8fa00394-72b9-11e7-9373-4d130cbcaf2b.gif)

**Comment by evidolob** [comment]
Cannot reproduce.

**Comment by SkorikSergey** [comment]
This issue is reproduced again after https://github.com/eclipse/che/commit/62fc1745e07a6afa129457c37f51a72d93c0875a. And there is a problem with the list of files. Sometimes the found file is displayed in the list twice.

![teams-11-1](https://user-images.githubusercontent.com/7760565/30846477-89e21642-a2a0-11e7-816f-2ebcdb940d14.gif)
