### ISSUE TITLE
Redesign workspace details -> servers page 

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5700]
#### Workspace Servers
![1 - workspace details - servers](https://user-images.githubusercontent.com/1636769/27130685-9be73542-5107-11e7-8bb6-855a9d9029c2.png)

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/5451/commits/2bd24a736f4b3b73398b5c79011cdc51a4bcc25a

**Comment by olexii4** [comment]
![selection_021](https://user-images.githubusercontent.com/6310786/29022432-f1d4ecd0-7b71-11e7-9c7e-aa4e9185c008.png)
