### ISSUE TITLE
Redesign workspace details -> environment variables page

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5701]
#### Workspace Environment Variables
![1 - workspace details - env variables](https://user-images.githubusercontent.com/1636769/27130682-96cc3abc-5107-11e7-8d19-8155e4e04c6e.png)

**Comment by olexii4** [comment]
![selection_017](https://user-images.githubusercontent.com/6310786/29022497-398de946-7b72-11e7-850c-844f0fa3abeb.png)
https://github.com/eclipse/che/pull/5451/commits/2bd24a736f4b3b73398b5c79011cdc51a4bcc25a
