### ISSUE TITLE
Add "resend invitation" option for team member invites

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5702]
_From @bmicklea on March 29, 2017 13:16_

When you invite a user to join your Codenvy team you should be able to choose to resend the same invitation in the event that they did not receive it.

_Copied from original issue: codenvy/codenvy#2010_

**Comment by ghost** [comment]
@bmicklea @slemeur is this still a valid enhancement request?

**Comment by ghost** [comment]
_From @bmicklea on July 17, 2017 10:59_

Yes, it's expected functionality that we are missing.

**Comment by j2Bud** [comment]
I assume there is not movement or workaround for this yet?
