### ISSUE TITLE
Allow customers to set minimum and maximum workspace size (in RAM) via configuration.

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5703]
_From @bmicklea on September 16, 2016 16:23_

As a Codenvy Admin I want to be able to set the minimum and maximum workspace RAM allowed when users configure their workspace. This would prevent users from creating overly small or large workspaces from the API or UI.
- [ ] Add a configuration parameter to set lower limit for workspace RAM: `limits.user.workspace.min.size` which prevents users from creating a workspace with less RAM than the limit defines.
- [ ] Add a configuration parameter to set upper limit for workspace RAM:`limits.user.workspace.max.size` which prevents users from creating a workspace with more RAM than the limit defines.
- [ ] Enforce this parameter for all workspaces in the system via the API and Dashboard
- [ ] In the UD the RAM slider and the validation on the RAM input text field will respect the values in these two configuration parameters

- [ ] Allow this parameter to be overridden as part of https://github.com/codenvy/codenvy/issues/582

_Copied from original issue: codenvy/codenvy#764_

**Comment by ghost** [comment]
_From @bmicklea on September 16, 2016 16:25_

@slemeur can someone set the min and max RAM allowed in each stack today?  I saw a reference to something like this...

**Comment by ghost** [comment]
_From @vkuznyetsov on October 20, 2016 7:48_

@bmicklea In my opinion we can set default size of memory for each Ready-to-go stack and show it on progress bar in dashboard instead of setting the max/min RAM limits. As I know it is easy to implement this. @ashumilova am I right?

**Comment by ghost** [comment]
_From @ashumilova on October 20, 2016 8:18_

@vkuznyetsov yes, that's true - stacks define the memory limit for each machine - needed to start properly. Like this https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L114.

**Comment by ghost** [comment]
_From @bmicklea on October 20, 2016 14:18_

Okay - so if I create a new stack "Brad-Stack" I can set a minimum RAM of 3GB and a maximum RAM of 16GB?  If so then is it possible for a user to create a workspace from my stack that uses 2GB or 20GB either through the UI or API?

**Comment by ghost** [comment]
_From @slemeur on October 20, 2016 14:24_

Both. 

Those values are used to pre-set the RAM setting when creating the workspace. 
Actually:
- the UI allow to set a value under the minimum limit
- the API allow to create the workspace too

Moreover we don't have any parameter to handle the "maximum limit".

**Comment by ghost** [comment]
_From @bmicklea on October 25, 2016 11:37_

Okay that's what I thought. So the description of this task is correct and I've clarified it further.

@slemeur I think we need you to specify what the dashboard should do when the min and max limits are set. Do we show the full slider and somehow indicate that some parts are not accessible?  Or do we redraw the slider so that it only goes from the defined min to max?  Also I think we might need an info hover that explains why other RAM values aren't possible.

**Comment by ghost** [comment]
_From @vkuznyetsov on October 25, 2016 13:46_

BTW I understand that we need to set min limit to make possible to start a WS. What is the purpose of max limit?

**Comment by ghost** [comment]
_From @bmicklea on October 25, 2016 15:0_

Max limit is so that admins can control resource use (and cost)

**Comment by ghost** [comment]
_From @tolusha on November 1, 2016 15:26_

I think it is better to relate these limitations to the stack but to have them globally.

**Comment by ghost** [comment]
_From @bmicklea on November 2, 2016 12:59_

@tolusha what would we do with custom stacks?  Do we need a workspace limit and then a per-stack limit where the workspace limit "wins" if there's a conflict with the stack limit?

**Comment by ghost** [comment]
_From @tolusha on November 2, 2016 13:8_

No workspace limits at all.
Only limits in stack if needed.

Min value might be good for some projects but is not suitable of others. That's why it is more related to project but not to workspace.

**Comment by ghost** [comment]
_From @bmicklea on November 2, 2016 14:51_

No we need a global workspace limit as well...I can create a custom stack and set a huge RAM limit. That could be bad since organization could end up with an unexpectedly large bill.

Imagine this use case:
- I create two stacks for my organization
  - Stack 1: Min RAM = 2GB; Max RAM = 8GB
  - Stack 2: Min RAM = 2GB; Max RAM = 16GB 
- I set "global" workspace limits:
  - Min RAM = 2GB
  - Max RAM = 16GB

With these set I know that even if someone creates a custom workspace or a new stack they can't have it use >16GB RAM so I won't get surprised by a huge Amazon hosting bill because someone created a 128GB RAM workspace.

**Comment by ghost** [comment]
_From @vkuznyetsov on November 7, 2016 16:6_

There is a collision here
- setting the min RAM limit makes sense for stack, which should be managed by user. They define the min RAM limit related to how much ram they needed for instance they want to run. Some custom instances may require less than 1GB RAM.
- setting min RAM limit by admin will prevent users from creating the small instances they want.

**Comment by ghost** [comment]
_From @bmicklea on November 7, 2016 16:39_

@vkuznyetsov that's correct, the collision is possible but since all these configurations are optional there's no need for someone to use the global in your scenario.

However, if there is a collision the global will override the stack.

**Comment by ghost** [comment]
_From @sleshchenko on December 9, 2016 13:3_

Looks like the parameter `limits.user.workspace.max.size` already exists but with another name.  [limits.workspace.env.ram](https://github.com/codenvy/deployment/blob/master/puppet/modules/all_in_one/templates/general.properties.erb#L40) configuration parameter that defines maximal number of RAM per workspace's environment.
In other word, users are not able to create workspace that will use more than specified number of RAM. They are able to create workspaces with multi environments which in summary will define more than specified RAM. But there can be only one active (running) environment.
Note: It doesn't affect stacks, but affects ability to create workspace configuration defined by stack.

**Comment by ghost** [comment]
_From @bmicklea on December 9, 2016 13:44_

Okay, please change the name to limits.user.workspace.max.size so it
matches the others.

**Comment by ghost** [comment]
_From @TylerJewell on July 5, 2017 13:53_

@bmicklea - is this still an actual customer need?  Labeled to move to Eclipse Che repo.

**Comment by ghost** [comment]
_From @bmicklea on July 10, 2017 16:50_

I believe it's still actual.

**Comment by ghost** [comment]
Should we really move this to Che? I think we're ok to close it.

**Comment by ghost** [comment]
_From @TylerJewell on July 17, 2017 9:59_

It's still actual. We are moving the workspace management into Che, and this basic control will be expected for how to structure workspace scaling.  What aspects were you thinking were not needed?

**Comment by ghost** [comment]
But it looks like the goal of this issue is just to rename an existing property? See @sleshchenko's comment above

**Comment by ghost** [comment]
_From @TylerJewell on July 17, 2017 10:32_

It's that and also new functionality - such as the minimum RAM requirement, which does not exist today.  So it is the collection of elements done together.

**Comment by tolusha** [comment]
It is not relevant anymore.
