### ISSUE TITLE
Wrong autosave behavior in the editor split mode 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5705]
**Reproduction Steps:**
 - Create java stack with default spring project
 - Open java class
 - Split editor to the two columns
 - Do any changes in the first column
 - Wait until changes will be saved 
 - Pay attention that in the first column class save status is "saved" and on the second column status is "not saved".

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![aaaa](https://user-images.githubusercontent.com/22724619/28272861-695988e6-6b15-11e7-8486-d5d18ffdd232.gif)

**Comment by RomanNikitenko** [comment]
@Ohrimenko1988 #5497 is it duplicate?

**Comment by Ohrimenko1988** [comment]
Duplicated #5497
