### ISSUE TITLE
Warning marker is not displayed when new error markers are shown

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5706]
**Reproduction Steps:**
 - Create java stack with default java spring project
 - Open java class and type some code for warning marker (for example String s = "text";)
 - Wait until warning marker will be shown
 - Do some error changes in the import 
 - Wait until error markers will be displayed
 - Pay attention that warning marker is not displayed

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![aaaa-1](https://user-images.githubusercontent.com/22724619/28273602-7b831df0-6b17-11e7-9c29-850ab4f198c1.gif)

**Comment by ghost** [comment]
For example, in desktop Eclipse, if there's an error before a warning, a yellow bulb turns gray when a file isn't saved. When you save a file, and you have got errors before warnings, those warnings go away.

File unsaved:

![image](https://user-images.githubusercontent.com/5337267/28358077-303f31b6-6c76-11e7-9166-562a4e8f1435.png)

File saved:
![image](https://user-images.githubusercontent.com/5337267/28358107-4323b612-6c76-11e7-9185-595fa0585afe.png)

**Comment by ghost** [comment]
Closing it since this is expected behavior, since in order to show warnings AST should be built which is impossible with errors.
