### ISSUE TITLE
CHE-650 Cannot export a workspace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#571]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-650
Reporter:  Maxim Musienko
Description: Preconditions: i have used two hosts for testing this feature. Base host (host1) onprem assembly on vagrant. And target host (host2) on http://nightly4.codenvy-stg.com/.
Steps to reproduce: 
1) Go to to dashboard of the host1, create a workspace with project (if it did not exist) and  Workspaces -> click on worksaces -> export->select tab "to private cloud" -> fill your credentials on nightly4 ->Export
_Expected result:_ the workspace with the project should be created on nightly4
_Actual result_: 400 http error with responce mess.: FailedExporting workspace failed: Workspace name required

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/4b81105e07711c3cfc3caedd9a6a8f580a6fc020
