### ISSUE TITLE
How does Che stop/start the containers when stop/start workspace or stop/start Che server?

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5711]
I have a workspace with three machines node. When I stop workspace and open the workspace again, I found some data lost in container and the script in ENTRYPOINT will be run again. For example, I have a machine which will install a database when the containers startup. If I restart the workspace, I found the install script will be executed again. I do not see this problem if I run the container in docker directly with docker stop/start.

What does Che do to the containers when stop a workspace and start it again?

**Comment by garagatyi** [comment]
Hi! Stopping workspace removes containers which belong to it. That's why docker start/stop is not equivalent of workspace start/stop. There is also snapshotting feature in Che and, I suppose, it would make the behavior of start/stop similar to what you expect.

**Comment by qi-min** [comment]
@garagatyi Even I use stop with snapshot, there are some errors.
1. The first time open a workspace, a user and a group are created in the container. But after stop and start the workspace, the user and group is kept, but the user home directory disappeared which leads lots of function does not work.
2. The script in ENTRYPOINT still be executed again, which means any configuration to the container will be executed again.

I see the sample stack 'java-mysql' also have similar problem. Lots of errors are displayed in the mqsql machine during re-open workspace.

**Comment by qi-min** [comment]
does Che use 'docker commit' to make snapshot?

**Comment by ghost** [comment]
@m7luffy I think it'd help if you elaborate on lots of errors.

Yes, docker commit is executed.

And yes, of course, if you do not snapshot a workspace, everything you have outside `/projects` dir is lost.

**Comment by qi-min** [comment]
If Che use docker commit to snapshot, then I can reproduce my issue by docker commit directly with my image. So this is my image problem. Thanks for your answers and I will Close this issue.
