### ISSUE TITLE
Build a new CentOS based che-server Docker image

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#5715]
In [dockerfiles/che/](https://github.com/eclipse/che/tree/master/dockerfiles/che) there are 2 Dockerfiles to build the che-server image:
- [Dockerfile](https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile): alpine based
- [Dockerfile.centos](https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile.centos): CentOS based

Che CI is currently building the alpine based Dockerfile only. The CentOS based Dockerfile is used for k8s and OpenShift deployments and should be built too. 

The resulting CentOS based images should be tagged `eclipse/che-server:nighlty-centos`, `eclipse/che-server:latest-centos`, `eclipse/che-server:5.15-centos` and pushed to [the docker hub](https://hub.docker.com/r/eclipse/che-server/tags/).

This new che-server image should not replace the Alpine based that is and will remain the default image to use when running Che on Docker.

**Comment by riuvshin** [comment]
Done, https://hub.docker.com/r/eclipse/che-server/tags/  new tags already available for nighty and latest release 5.15.0

**Comment by wernight** [comment]
Why many is CentOS based for Kubernetes? I've all my k8s images based on Alpine when possible.
