### ISSUE TITLE
Develop UI panel for changing Java code formatter preferences

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#5720]
This panel  lets you manage your code formatter profiles for the Java code formatter.
It should be something similar to the Eclipse (Java > Code Style > Formatter ) 
1. 
![eclipseformatter1](https://user-images.githubusercontent.com/1636592/28314945-33d384dc-6bc5-11e7-9f8b-c76132128ed2.png)

Action | Description
-- | --
Active profile | Selects the profile active for the workspace or current project.
Edit... | Shows a dialog which displays the settings stored in the active profile. Only user-defined profiles can be modified.
Remove | Removes the selected profile. This action is only available on user-defined profiles.
New... | Shows the dialog to create a new profile. The dialog requires you to enter a name for the new profile. Additionally, you may select a built-in or user-defined existing profile to base your new profile on.
Import... | Imports profiles from the file system. #5721
Details | Displays a sample how the active profile formats a Java code snippet

2. Next screenshot just for sample how it can look in Che. In case formatter has a lo of settings  UI will be very heavy.  
![eclipseformatter2](https://user-images.githubusercontent.com/1636592/28315328-9fedd0c2-6bc6-11e7-9215-94383ff76d72.png)

**Comment by gorkem** [comment]
Formatter preferences actually only modify a java properties style file used by JDT formatter. Instead of creating a traditional preferences UI for this, perhaps we can actually implement an editor.  This needs to be addressed also with https://github.com/redhat-developer/vscode-java/issues/2 so some synergies? @slemeur WDYT?

**Comment by slemeur** [comment]
I agree. Morevover we need to consider that not only for Java, but also for other languages. 

Providing such UI for handling the formatter preferences is going to take really long time. 
Instead we should just consider the basic use cases:
- A user can use a list of predefined formatters per languages
- A user can edit formatters by using an editor 
- A user can manage formatters from a new "Formatters" section in the preferences wizard

Few more details:
- We will just list all the languages.
- For each languages, we provide: a dropdown to select the formatter + a button to "Edit" + a button to "Restore" the formatter to the default properties.
- When the user hits the button "Edit", it shows the formatter property file in an editor where he can change the configuration of the formatter. It also adds "-Edited" to the end of the formatter's name, so this way the user knows that the formatter has been edited.
- If the user wants to restore the default formatter options, he just has to click on the button "Restore"

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
