### ISSUE TITLE
CHE-651 Notification loose their shadow

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#573]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-651
Reporter:  Stévan Le Meur
Description: See the attached snapshot, we loose the shadow for the notification we have on dashboard

!Screen Shot 2016-02-29 at 16.47.28.png|thumbnail!

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/985802fc5a04abc76b612c92a4606068a07d670d
