### ISSUE TITLE
Provide consistent "new tab" behaviour

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#5735]
## Goals
With the new layout of Che 6, we want to simplify the experience to get a new tab inside of the pane. Today, user has the ability to get multiple tabs into process and editor panes.

## Requirements
In the panes where it's possible to get multiple panes, we will add a "+" button. When clicked, this "+" button will allow to display a menu, where the user can select what the tab will be for.

**For Processes pane:**
![screen shot 2017-07-19 at 10 50 50](https://user-images.githubusercontent.com/1636769/28358800-819fab90-6c70-11e7-80db-36f7d34c4e94.png)

**For Editor pane:**
![screen shot 2017-07-19 at 10 53 52](https://user-images.githubusercontent.com/1636769/28358824-98caf40a-6c70-11e7-83ea-741caed95fe6.png)

When the user will click on "+" button, it will allow to create a new file (it will propose the choices that we have from the toolbar today which is the same as right click "New File")

**Comment by AndrienkoAleksandr** [comment]
@slemeur I think new tab in the ProcessPanel contains duplicated information about list machines. We already have such information in the machine tree. And if user have 5 machines in the workspace he  will see quite big menu to create new tab. Maybe it would be better to get information about selected machine from machine tree and display in the menu two items: "new Terminal", "SSH"? What do you think?

**Comment by slemeur** [comment]
Hi @AndrienkoAleksandr . Yes I understand your point. The list of machines could be hidden as well - so the user still have to choose "on which machine" he wants a new terminal or ssh or list the servers. 

I agree it's going to duplicate the information and the menu is going to be really "big". Do you think we should have a second level in the menu? 
Something like this (if servers is selected):
Terminal > 
SSH        > 
Servers  > Machine 1                  Machine 2     |             Machine 3

**Comment by AndrienkoAleksandr** [comment]
Who... I didn't think that machine tree can be hidden, I forgot about this feature... I think second level it's not bad idea to reduce menu size... But from another side, for now I guess most of our users don't have a lot machines per workspace, and maybe current merged implementation it's not a problem for them...

**Comment by AndrienkoAleksandr** [comment]
Another "possible" solution it's a display one level: 
Terminal >
SSH >
And when machine tree is hidden and user clicked to some item "Terminal" or "SSH" display list machine and when user selected on of them, than create new one tab. 
But I'm not sure that's it's a good concept. Interesting stuff to thinking :)
