### ISSUE TITLE
Che: Terminal Tab default focus

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#5741]
From @burrsutter on June 7, 2017 2:6

When I click on the Terminal tab header, I also have to click into the window to give it focus and a cursor. This is particularly annoying when switching command tabs. How about the Terminal tab gain focus/cursor by default when clicked on and brought to the foreground.

Copied from original issue: openshiftio/openshift.io#202 and redhat-developer/rh-che#93

**Comment by slemeur** [comment]
Please take into consideration the use case when a new terminal is created too. see video in #6034

**Comment by AndrienkoAleksandr** [comment]
QA cycle branches https://github.com/eclipse/che/tree/CHE-5741-2 and https://github.com/eclipse/che-lib/tree/CHE-5741-2.

**Comment by AndrienkoAleksandr** [comment]
QA found regression: focus disappear from editor after first opening.

**Comment by AndrienkoAleksandr** [comment]
It was not regression. It was activated feature "Link with editor feature". But this feature contains bugs  https://github.com/eclipse/che/issues/6182 and  https://github.com/eclipse/che/issues/6183. I didn't see that it was activated on my CHE when I run selenium tests.
