### ISSUE TITLE
How to link an extension to IDE ?

### ISSUE THREAD

**Issue by sudaraka94** [eclipse-che/che#5742]
Hi all,
I'm trying to link my extension to the IDE. I read the documentation
[in this url](https://www.eclipse.org/che/docs/assemblies/plugin-lifecycle/index.html#ide-extension-link-to-assembly) . But couldn't find the .gwt.xml file in the description `/che/assembly/assembly-ide-war/src/main/resources/org/eclipse/che/ide/IDE.gwt.xml`

I think the documentation has not been updated with the [Gwt xml generator #4298 pull request](https://github.com/eclipse/che/pull/4298)

**Comment by ghost** [comment]
@slemeur that's a docs issue. gwt.xl is auto generated now and there's no need to inherit anything, just add dependencies.

@sudaraka94 you need to add dependencies to pom.xml and that's it.

**Comment by ghost** [comment]
Here's a PR https://github.com/eclipse/che-docs/pull/265

**Comment by ghost** [comment]
Closing the issue.
