### ISSUE TITLE
Current bottom panel is shown on workspace stop instead of dev-machine logs

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#5754]
**Reproduction Steps:**
1. Open a workspace
2. Switch to non-precesses tab in the bottom
3. Stop workspace

**Expected behaviour:** Processes panel with dev-machine logs should be maximized
**Actual behaviour:** Active panel is maximized
Screencast:
![stopws](https://user-images.githubusercontent.com/15607393/28410480-83b075c8-6d46-11e7-9b68-cbe1fa660458.gif)

**OS and version:**   Fedora 25

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
