### ISSUE TITLE
CHE-653 Change value fails with NullPointerException

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#576]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-653
Reporter:  Mykola Morhun
Description: _Steps to reproduce:_
1) create workspace
2) import pet clinic project (https://github.com/spring-projects/spring-petclinic)
3) set breakpoint in VetController.java:50 (model.put("vets", vets);)
4) run application in debug mode
5) switch to application and lick on "veterinarians" in top menu (after this the execution should be stopped on breakpoint)
6) return into CHE, expand "vets" list in variables tree (vets->elementData->[0]->firstName)
7) select firstName and click change value (or press F2)
8) in change value dialog change "James" to another name (John for example)
_Expected result:_ variable value and value in variables tree should be changed
_Actual result:_ NullPointerException in Chrome console

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/8815ce4d412fa79c16c0265bf8923db037f119dc
