### ISSUE TITLE
Check if ".che" folder exists before adding to  File Watcher excludes

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5760]
**Reproduction Steps:**

- Create a workspace from the **Java** stack with the **web-java-spring** project
- From the Menu enable the **"Show/Hide Hidden Files"**
- Delete ".che" folder
- Select any file from the project and in the context menu select the "Add to File Watcher excludes"

**Observed behavior:**
There is an error notification **"Can not add paths to File Watcher excludes"**

**Che version:** 5.16.0-SNAPSHOT
**OS and version:** Fedora 25

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config-31](https://user-images.githubusercontent.com/7760565/28419838-fb47572e-6d68-11e7-93d8-d936ddee4141.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by ghost** [comment]
@riuvshin @vparfonov isn't it expected behavior? Deleting a hidden folder with project metadata may lead to unpredictable consequences in any IDE. `./che` also contains classpath file that Maven plugin uses.

**Comment by RomanNikitenko** [comment]
I think we can have some project types which haven't .che by default. In this case "Add to File Watcher excludes" feature will not work and we need to handle this case. 
@vparfonov WDYT?

**Comment by ghost** [comment]
@RomanNikitenko yes, this is the question of if or not `./che` is there for all Che projects. If it should be there, then this is expected behavior. Maybe we should add some warning that deleting this folder leads to unpredictable consequences. 

I'd also add that this is not a real life use case, and a developer will hardly delete a hidden folder with project metadata in his IDE, right?

**Comment by ghost** [comment]
UPDATE. It looks like only maven and java projects have `./che`. A blank project type does not have it. So, exclude feature does not work for those project types too. I think we should not depend on `./che` here. Or create `./che` for all project types.

**Comment by RomanNikitenko** [comment]
We can create .che when we need it. For example, we can check if .che exists when we adding paths to File Watcher excludes.

**Comment by ghost** [comment]
@RomanNikitenko and if it does not, where do we create this file with excludes? First, create `./che`?

**Comment by RomanNikitenko** [comment]
@eivantsov yes, first, we need create ./che in this case

**Comment by RomanNikitenko** [comment]
Depends on https://github.com/eclipse/che/issues/6575
