### ISSUE TITLE
Whatever port I set to the tomcat server, it always says that it is in use.

### ISSUE THREAD

**Issue by lamarios** [eclipse-che/che#5767]
I'm trying to run che  and set it up in my docker compose file where i run a bunch of other things.

Whatever port i use for the CHE HTTP server it throws me telling me that the port is already in use. 

Here's my docker-compose setup

`che:
  container_name: che
  image: eclipse/che
  restart: unless-stopped
  command: start
  ports:
   - "27393:27393"
   - "33000-33099:33000:33099"
  volumes:
   - "./che/data:/data"
   - "/var/run/docker.sock:/var/run/docker.sock"
  environment:
   CHE_PORT: 27393
   CHE_HOST: mydomain.com`

**Reproduction Steps:**

docker-compose up -d

docker logs -f  che -> 

`WARNING: No swap limit support
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 27393 (http):        [ALREADY IN USE] 
`

**OS and version:**    
Ubuntu 16.04
**Diagnostics:** 

I tried 20 different random ports numbers but no luck.

**Comment by TylerJewell** [comment]
I think your compose file generation is causing errors. Our CLI is purposefully stateless and on the command line it will generate a docker-compose.yml file that is specific to your OS and other configuration parameters base dupon the `CHE_PORT` value.  You can inspect how that file looks if you want to generate one that is similar that bypasses the stateless CLI.

I think the error in your compose syntax is that you should not need the `27393:27393` line.

**Comment by TylerJewell** [comment]
You should not be exposing the other ports either, `"33000-33099:33000:33099"`

**Comment by lamarios** [comment]
ah yeah,  i also removed those as well, still getting the same.

**Comment by TylerJewell** [comment]
Hmmm, that is suggesting that something is blocking it.  remove the `CHE_HOST` parameter. Does it boot without overriding the defaults?

**Comment by lamarios** [comment]
No difference.

I did an lsof -i :32768 but no process is using it.

**Comment by TylerJewell** [comment]
Maybe you have some old containers running that have accidentally bound services.  Can you wipe all known containers and try again?

**Comment by ghost** [comment]
@lamarios there's an easy way to check if it's Che fault or nor. 

`docker run -d -p 32768:80 nginx`

If container starts and you can see nginx welcome page at `localhost:32768` then Che is to blame.

**Comment by lamarios** [comment]
I can't start that container. Same error.

**Comment by TylerJewell** [comment]
Can you recycle your Docker daemon?

**Comment by lamarios** [comment]
Ok, it seems to work now.
What I did: clean my docker-compose file by removing all the network_mode: "host" and set ports manually

It still didn't work.

After restarting (if it's what you meant by recycling) my docker daemon, it's starting !

Thanks a lot !

**Comment by TylerJewell** [comment]
Yeah, I think your daemon got jumbled - so now you can play around with the other parameters.
