### ISSUE TITLE
CHE-654 Unclosed zip archive when building che

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#577]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-654
Reporter:  Florent Benoit
Description: when building che we have logs like
Cleaning up unclosed ZipFile for archive che-websocket-terminal-4.0.0-RC9-SNAPSHOT.zip
Cleaning up unclosed ZipFile for archive che-websocket-terminal-4.0.0-RC9-SNAPSHOT.zip

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che-parent/commit/9231ccd46f07e0d7dbe3b6c76495cadc0a2f62fd
