### ISSUE TITLE
Close workspace with snapshot still lost data stored in container volume

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5771]
1. Create a stack with a custom docker image. The image expose a volume.
2. Open the workspace from the stack. A container is started by workspace and a volume is mount on host. e.g: `var/lib/docker/volumes/da486eeb2b4d8652c5cae5301e80374173d0137dd8151d13377b4cb2a2fa8a5d/_data"`
3. Stop workspace with snapshot and open it again
4. Che will assign another volume for the container. So all data stored in previous volume lost.

Che does not support specify volume in stack recipe, so every time a workspace startup, a random volume will be bind to container,  the data stored in that volume can not be persisted.

Is it possible to always use same volume to start container if workspace is closed with snapshot? 
Or have methods to specify volume of container for workspace?

**Comment by TylerJewell** [comment]
We have a vision that should address this in Che 6. We will support Che on Kubernetes in that version. One benefit of K8S is that you can have a shared, persistent volume that is replicated across nodes. We'll place more of the workspace's contents onto that volume and it will be recoverable between snapshots.

**Comment by qi-min** [comment]
@TylerJewell What is the release date of Che 6?

**Comment by TylerJewell** [comment]
As soon as humanly possible.  

Unfortunately, we do not advertise dates in advance since software is hard to predict. So it ships as soon as its done. We started on Che 6 almost a year ago and most of the hard parts are done, so it moves into productization exercise next.  But it is measured in months, not days.

**Comment by qi-min** [comment]
@TylerJewell  Is there any workaround for now? I see the container for DEV will mount to directories under 'data' directory. Is it possible to let other containers in workspaces also mount to directories under 'data' directory? Then restart workspace can always pickup the same data.

**Comment by TylerJewell** [comment]
There is no workaround until Che 6. It is not as simple as sharing a volume mount as many volume mounts are not available in a distributed mode where containers are on different nodes.  Che 6 handles this cleanly.

**Comment by ghost** [comment]
@m7luffy how do you mount a custom volume into a workspace? Even though named volumes are not supported, persisting data across workspace restarts should be ok

**Comment by qi-min** [comment]
@eivantsov I can not mount a volume to my machine in workspace. Restarting workspace will restart he docker which will mount to a different temp volume. I see the data of dev machine is mount to /data/**, restarting workspace will keep the data in dev machine. So  I am wondering is there similar way to specify volume mounting on other machine besides dev machine in workspace.

**Comment by ghost** [comment]
Volumes mounts happen for dev machine only.

**Comment by qi-min** [comment]
yes, so the data on other machine may be lost after restart if the data need be mount on a volume. Che or Docker will mount them to a random directory automatically and it changes every time the workspace restarted.

**Comment by garagatyi** [comment]
@m7luffy have you tried to uncomment and edit (or add if it is missing) [such a line](https://github.com/eclipse/che/blob/55bee0b7b57af0a80192ead04a76c5f8ae17947d/dockerfiles/init/manifests/che.env#L104) in your che.env file.

**Comment by ghost** [comment]
@m7luffy are you talking about dev machine? Your projects are mounted and they are persisted. You may provide additional volume mounts for dev machine.

**Comment by qi-min** [comment]
no, I am not talking about dev machine. For example, I have a dev machine and another machine for database. And I need to mount  volume for database machine for some reason. But I can not do it now.

**Comment by ghost** [comment]
@m7luffy I see. Weel you can snapshot the entire machine but do not declare a volume.

**Comment by qi-min** [comment]
@garagatyi can I set this list for the machine other than dev machine?

**Comment by qi-min** [comment]
@eivantsov the image which I need to use declare a volume. I know it maybe not a good choice for current Che, just want to find out is there any workaround.

**Comment by garagatyi** [comment]
No, just for the dev machine right now

**Comment by ghost** [comment]
Closing the issue. Che on OpenShift will likely have more freedom when it comes to persisting data
