### ISSUE TITLE
Disable findbugs check from default build

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5774]
I think fixing all issues reported by findbugs is quite idealistic but not achievable goal.
I can assume that 99% of developers ignore or skip this check. And it just became some sort of
masochism when it just takes time and never used.

**Comment by garagatyi** [comment]
I would prefer to fix issues reported by findbugs, but we don't commit any obligations on findbugs reporting fixes. when we added it into the build we had to set some process of usage of these reports.
If we won't do that then it doesn't make sense to keep this plugin in build at all.

**Comment by ghost** [comment]
Closing the issue since the discussion is being held in a PR.
