### ISSUE TITLE
[Regression] The debug connection is not set for Node.js project properly

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5779]
**Reproduction Steps:**
**Preconditions:** create a workspase based on NodeJs stack.
1. Go to the IDE. Create the NodeJs project by Wizard. Select the root folder of the project.
2. Run -> Edit debug configuration -> NODEJS ->Click  + icon ->click Debug
**Expected result:** debug connection - should be established
**OS and version:**  we see endless pop up notification with attempt to connection. The debugger is not active 
**Env.:** che v. 5.16.0, was reproduced on https://nightly.codenvy-stg.com server, rev.: ca5ba8d98e66351b

**Comment by ghost** [comment]
Node update to 8.x cause this trouble. Downgraded to 7.x Please, check it again

https://github.com/eclipse/che-dockerfiles/pull/112

**Comment by riuvshin** [comment]
@musienko-maxim please recheck this

**Comment by sr229** [comment]
@eivantsov works as intended now. the Node 8.x did break the debugger

**Comment by musienko-maxim** [comment]
The related functional test passes
