### ISSUE TITLE
[Doc] Broken link

### ISSUE THREAD

**Issue by micaelgallego** [eclipse-che/che#5782]
The link to "build the exec agent submodule" in doc page https://github.com/eclipse/che/wiki/Development-Workflow points to https://github.com/eclipse/che/tree/master/exec-agent, but this returns 404 Not found

**Reproduction Steps:**
Click on the link "build the exec agent submodule" in https://github.com/eclipse/che/wiki/Development-Workflow docs page.

**OS and version:**    
Any

**Diagnostics:** 

NA

NA

NA

**Comment by TylerJewell** [comment]
Thanks for pointing this out. We just changed the location of the agents to simplify the naming scheme. I've updated the wiki to point here: https://github.com/eclipse/che/tree/master/agents/exec
