### ISSUE TITLE
autobracket in C-Like Languages Seems to follow only JS-like bracket syntax

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5783]
After meddling with the C# for a while, I noticed the autobracket behaviour only sticks with the JS-style bracket syntax. C# Standards define it's brackets to be a line after it's statement along with some other C-like langs (like C++)

**OS and version:**    
Codenvy 5.15.0 on Docker Toolbox on Windows 10 10586

**Comment by ghost** [comment]
@sr229 This is obviously how Orion editor behaves. Mirroring `( { [ "` and similar characters works identically irrespective of the file extension.

**Comment by sr229** [comment]
IMHO there should be independent behaviors for the autobracket language-wise.

**Comment by ghost** [comment]
Since Orion is a dependency for us, there's little that we can do on Che side. Closing the issue. Perhaps, using a different editor fixes it.
