### ISSUE TITLE
Edit->Format does not support bind on different formatters

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5784]
To extend Edit->Format to support my language file, I need to bind my formatter to ContentFormatter like below and it works.
```
protected void configure() {
    	bind(ContentFormatter.class).to(MyFormatter.class);
    }
```
But after I add the java-ext-lang-client back, the build failed because java editor also bind on ContentFormatter.  I searched code but do not find any other language support format. So what is the correct way to extend the Format menu to support format based on file type?
Here is build error:
` [ERROR] Key org.eclipse.che.ide.api.editor.formatter.ContentFormatter is Double-bound: Bound at org.eclipse.che.ide.ext.java.client.inject.JavaEditorGinModule.configure(JavaEditorGinModule.java:38) in org.eclipse.che.ide.client.inject.IDEInjector and ...`

**Comment by evidolob** [comment]
Hi @m7luffy, you should to use [TextEditorConfiguration](https://github.com/eclipse/che/blob/0e8b21ad3ff5da80a7a03ddf3f0b281cc3594dcb/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/editor/editorconfig/TextEditorConfiguration.java#L45) to provide your content formatter, when you configure editor for your language file.

**Comment by qi-min** [comment]
got it, thanks!
