### ISSUE TITLE
Customizing site pages related to authentication and Keycloak

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5786]
In Codenvy we had a couple of customized pages 
1. Login
2. Create account
3. Recover password
4. Reset password

We need to find out if we need to have it customized for Che with Keycloak

**Comment by mmorhun** [comment]
Created draft of login pages for Keycloak Che theme:
Login page: 
![login](https://user-images.githubusercontent.com/15607393/28676756-2b1385be-72f4-11e7-9d9c-71e93d2689f7.png)
Login page after wrong password : 
![wrongpassword](https://user-images.githubusercontent.com/15607393/28865126-7e60a5b2-7777-11e7-9076-1af1c100a687.png)
Register page:
![register](https://user-images.githubusercontent.com/15607393/28676835-6e265700-72f4-11e7-99e7-0930f6c3a580.png)
Reset password page:
![reset-password](https://user-images.githubusercontent.com/15607393/28676848-7955db3c-72f4-11e7-905c-13684749bf55.png)
Login page after reset password:
![afterresetpassword](https://user-images.githubusercontent.com/15607393/28865075-4854ad7e-7777-11e7-9e03-3ce43d79ea8c.png)
Keycloak error:
![kc-error](https://user-images.githubusercontent.com/15607393/28676953-cc510a46-72f4-11e7-8b88-b0e5797ec21c.png)

**Comment by mmorhun** [comment]
@slemeur could you please review it?

**Comment by mmorhun** [comment]
Done
