### ISSUE TITLE
Revise functionality of Profile & Security page

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5788]
Now, these pages look like this.

![2017-07-24 11 41 20](https://user-images.githubusercontent.com/1614429/28515167-4e3b8ba4-7065-11e7-8141-7b88fa0b3b60.png)
![2017-07-24 11 41 14](https://user-images.githubusercontent.com/1614429/28515168-4e3c9cce-7065-11e7-843d-6fafc642bfe0.png)

The functionality of this pages is supported by ProfileService.  But in the case of integration of keycloak all this information are not stored in Che database and delighted to ID provide service (keycloak in our case). In this https://github.com/eclipse/che/issues/5438 we are going provide an ability to get some information for  ProfileService from Keycloak via OpenID protocol. In the first stage, it will be this fields
```
{
  "sub": "c8785721-f72d-4628-a9b5-391ff65f7b93",
  "name": "max shaposhnik",
  "preferred_username": "uy7c",
  "given_name": "max",
  "family_name": "shaposhnik",
  "email": "uy7c2@yahoo.com"
}
```
A couple of notes to consider.
1. ProfileService will be readonly. 
2. Consider to redirect to profile and change passwor page insted of editing it directly.

**Comment by mshaposhnik** [comment]
Profile endpoint URL will be available at `/api/keycloak/settings` under the `che.keycloak.profile.endpoint` and `che.keycloak.password.endpoint`  key.

**Comment by skabashnyuk** [comment]
This is how 
```/api/keycloak/settings``` looks like
<img width="1154" alt="2017-09-05 11 51 34" src="https://user-images.githubusercontent.com/1614429/30053771-9b6a644c-9232-11e7-838e-e9a39fae447e.png">
profile page 
<img width="1280" alt="2017-09-05 12 02 45" src="https://user-images.githubusercontent.com/1614429/30054172-dfd0a7b2-9233-11e7-94bb-aae3c98e3080.png">
Password
<img width="1280" alt="2017-09-05 12 02 47" src="https://user-images.githubusercontent.com/1614429/30054181-e979dafe-9233-11e7-843d-e1120efd42af.png">
Logout url looks like 

```http://192.168.65.2:5050/auth/realms/che/protocol/openid-connect/logout?redirect_uri=http%3A%2F%2F192.168.65.2%3A5050%2Fauth%2Frealms%2Fche%2Faccount%2F```
See more http://www.keycloak.org/docs/3.2/securing_apps/topics/oidc/java/logout.html

@ashumilova @slemeur  please revise this info. Do you need something else?

**Comment by slemeur** [comment]
Curious, why do you think we need to redirect to keycloack pages? Are we not able to reuse the pages that we already have and connect them to the keycloak API?

**Comment by skabashnyuk** [comment]
I doubt that such API exists.
