### ISSUE TITLE
Activate displaying a maven module name in User preferences.

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#5792]
We decided to put git branch name next to project name in project explorer panel.
At the time we have a maven module name there. If we put the git brunch name next to maven module name it may be visually overwhelming for some users, but very useful to another ones.

I propose:
1. make it possible to turn off/on a maven module name in the user preference menu.
2. displaying a maven module name should be off by default.

**Comment by sunix** [comment]
Maybe, we could display the maven info groupId:artifactId:version (or just artifactId) to pom.xml ? That would be useful :)

**Comment by vinokurig** [comment]
@sunix The project item in the project explorer would have really long name in this case. Anyway this sounds like a new issue.
