### ISSUE TITLE
Python language server - offline mode

### ISSUE THREAD

**Issue by bryanSME** [eclipse-che/che#5797]
Should the Python language server work in offline mode? My question may be related to [#3809](https://github.com/eclipse/che/issues/3809)

I'm trying to upgrade from 5.11 to 5.15 mainly for the python language server.  I'm running this in offline mode.  When I create a new workspace, `Python  Defauly Python Stack with Python 3.5.1, pip 8.1.1` the work space starts with errors "missing /home/user/.cache/pip". 

Ignoring the error, I create a new project and double click on the "main.py" file what was created for me. This throws the error, 

`Can't start language server process. Got error: /home/user/che/ls-python/launch.sh: 1: /home/user/che/ls-python/launch.sh: pyls: not found`

the launch.sh file does exsist and as expected, it contains "pyls".  running `pyls` from the command line yields "bash: pyls: command not found".  At thins point, I'm assuming that Che needs to download some files to get the language server running but that's as far as I've gotten.

**Comment by ghost** [comment]
@bryanSME yes, the agent script downloads binaries and if you are offline, an agent won't start:

https://github.com/eclipse/che/blob/master/agents/ls-python/src/main/resources/org.eclipse.che.ls.python.script.sh

**Comment by ghost** [comment]
Closing the issue. In future, ls binaries delivery methods may change.
