### ISSUE TITLE
Problem to install Eclipse Che on Windows Server 2016 : "image operating system "linux" cannot be used on this platform"

### ISSUE THREAD

**Issue by braffet** [eclipse-che/che#5798]
Hello,

We plan to migrate to Eclipse Che and we would like evaluate the IDE "Next Generation" for a specific project for one of our clients. they use only Windows Server OS, so I'd tried to configure a sandbox server with Eclipse Che.

On Windows Server 2016, once Docker installed, an error occured just after 
PS> docker run -it eclipse/che start
Unable to find image 'eclipse/che:latest' locally
latest: Pulling from eclipse/che
C:\Program Files\Docker\docker.exe: image operating system "linux" cannot be used on this platform.
See 'C:\Program Files\Docker\docker.exe run --help'.
PS>

Windows Server 2016 Standard
32 Gb / 16 proc Inten Xeon 2,3Ghz

I had checked the Docker installation with success :
 - docker run hello-world:nanoserver  (ok)
 - docker run microsoft/dotnet-samples:dotnetapp-nanoserver  (ok)

It's seems to me that Eclipse Che shoud be worked on Windows?

Many thanks for your help

Bruno

**Comment by TylerJewell** [comment]
Unfortunately, the Docker daemon that is running on Windows Server requires specialized Docker images built for Windows.  The Docker images that we distribute right now have a Linux OS dependency. We have not yet done the work to build the windows-specific Docker images.

**Comment by braffet** [comment]
Thanks a lot for your answer.
So, I'm waitting your next version on Windows. ;-)
Best regards
Bruno
