### ISSUE TITLE
CHE-655 Dashboard view changes

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#581]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-655
Reporter:  Anna Shumilova
Description: # On the dashboard view, we should have a "Recent Workspaces" box, and it should appear above the "Recent Projects" box.
# On the dashboard view, we should also have a "+" in the header in the upper right.  Have this create a new project.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/222d4c3b254f358b493b786d5b517b82c9f74003
