### ISSUE TITLE
[Regression] The code validation is not available for language servers

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5818]
**Preconditions:** Create a workspace based on C# stack. Create the Asp. application from the Wizard. 

**Reproduction Steps:** 
1. Open the Program.cs.  After init  LS, do some error in the code.
**OS and version:**    Fedora 25, chrome browser, nightly.codenvy-stg.com/ server

**Expected result:**  The error marker should appear in the line with error
**Actual result:**  There is no any markers
**Additional information:**  The problem actual for PHP and Python language servers

The related test: CheckMainFeatureForLanguageTest

**Comment by tsmaeder** [comment]
I can confirm that for python files. First inspection reveals that the python language server is not started. Investigating.

**Comment by tsmaeder** [comment]
Are the language server agents enabled in the workspace in question?

**Comment by tsmaeder** [comment]
Works for me when enabling the the language servers in the workspace. What behaviour are you expecting?

**Comment by Ohrimenko1988** [comment]
This problem also actual for TypeScript language server

**Comment by ghost** [comment]
For Python, hover and auto completion worked for me But not error marking.

**Comment by musienko-maxim** [comment]
The language server agents was enabled. I think the LS process also was run.

**Comment by tsmaeder** [comment]
The notification channel for diagnostics is no longer working. My suspicion is that the registration mechanism in PublishDiagnosticsParamsJsonRpcTransmitter and PublishDiagnosticsReceiver got broken (maybe by the work on unique endpoint ids?). When the request transmitter tries to transmit the diagnostics even, there is one websocket connection registered, but the id is not the one that got recorded in PublishDiagnosticsParamsJsonRpcTransmitter.

**Comment by tsmaeder** [comment]
One more thing: this worked before I rebased on master today. So the problem must have been introduced recently.

**Comment by dkulieshov** [comment]
Quite possible that the new endpoint ID's mechanism may have impact however at first glance I can't tell how exactly as, for example, file watching is okay (according to QA reports) while it uses similar endpoint ID based subscription. I'm going to debug to get more info.

**Comment by dkulieshov** [comment]
Okay, so the reason why this happens is hidden within the way we process JSON-RPC requests on server side.They are processed in parallel so we have the following situation: when web application (IDE) is instantiated almost simultaneously server side receives a request to set a proper endpoint (client) ID and a request to subscribe to some event. So in one thread we're changing actual ID of websocket client and in another thread we're subscribing to an event using previous client ID. At the end we have subscription assigned to the old ID while the new ID have already taken its place.

So @tsmaeder guess about different IDs is accurate. The most simple and yet effective way to solve this issue I believe is to use mixture of current approach and the way @evoevodin described in [this](https://github.com/eclipse/che/pull/5775#issuecomment-316982948) comment.

**Comment by musienko-maxim** [comment]
The related selenium test passed. After manual testing other LS's worked as well
