### ISSUE TITLE
CHE-656 Switching between editor tabs by hotKeys works incorrect after rename opened file 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#582]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-656
Reporter:  Aleksandr Andrienko
Description: Steps to reproduce:
1. Open some project.
2. Open at least 4 file from project.
3. Navigate between files with help hot key Alt + Left Arrow or Alt + Right Arrow. Feature works correct.
4. Rename second opened file and try navigate with hotKey again.
Actual result: switching by hotkey between editors works incorrect, order of switching is broken
Expected result: switching by hotkey between editor should works correct after rename file.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/6a83ce5acc3ef1e44c0dee25f39eda3d782cc591
