### ISSUE TITLE
[Regression] The output is absent after generation maven project from archetype

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5820]
**Reproduction Steps:**
* ```Go to the IDE ->Create Project->Maven->Next->Set checkbox 'From Archetype:' -> select quick start from dropdown list ->Create```

**Expected result:** during the maven quick start sample creation should be present output with **_BUILD SUCCESS_** message

**Actual result:** the output is absent but the template is created

**OS and version:**   Fedora 25, chrome browser, CHE 5.16.0

**Comment by riuvshin** [comment]
@vparfonov check this pls

**Comment by musienko-maxim** [comment]
The related test has been passed
