### ISSUE TITLE
[Regression] Step into feature does not open external class after applying the operation

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5822]
**Reproduction Steps:**
1. Go to the workspace based on java stack.
2. Create the java spring project from wizard
3. Open the Greeting controller class, set breakpoint in the 22 postion
4. Run debug command 
5. Run -> Debug configuration -> select Java and click '+' icon -> Debud
6. After activating breakpoint click on Step Into button of the debugger panel
**Expected result:**  The **_ModelAndView_**  class should be opened. The highlighter should be set.
**Actual result:**  The **_ModelAndView_**  class is not opened
**OS and version:**   Fedora 25,  CHE 1.16.0

**Comment by riuvshin** [comment]
@tolusha can you check this?

**Comment by tolusha** [comment]
Is fixed in https://github.com/eclipse/che/pull/5808

**Comment by riuvshin** [comment]
@musienko-maxim please check this bug on next qa iteration and close issue if not reproduced

**Comment by musienko-maxim** [comment]
The related selenium tests - passed
