### ISSUE TITLE
Saving a file does not update file saved status symbol

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5826]
Saving a file does not always update Che's file saved status with auto-save turned off. 

**Reproduction Steps:**
Disable auto-save, open a file and add 1 new character. Press Ctrl + S, the * symbol on the filename will flash and remain. Press Ctrl + Z and the whole of the file will be selected.

**OS and version:**
Che 5.15.0 on Chrome 59, Docker 17.03.1 with AWS EBS filesystem

**Comment by ghost** [comment]
@davidwindell I cannot reproduce it on Chrome 57 and Ubuntu 17. Ctrl+S and Ctrl+Z do what they are supposed to do. Any additional details? Does it happen to all file types? You also mentioned that it does not `always` update.

**Comment by minlare** [comment]
Also having this issue exactly as @davidwindell states. In addition, I have noticed that saving the file multiple times (eg. 3+ (random amount)) the problem does not occur. Then after another change it comes back (again after saving multiple times the problem stops).

**Comment by ghost** [comment]
@minlare still cannot reproduce. Same steps as @davidwindell described?

**Comment by davidwindell** [comment]
Could it be to do with EBS file storage?

**Comment by ghost** [comment]
@davidwindell what you say is that a local data directory mounted into `/data` in a container is an ESB storage?

**Comment by davidwindell** [comment]
@eivantsov that's right, for example on the host /var/lib/rancher/volumes/rancher-ebs/ebs-che is an EBS volume mounted on the host which is then mounted into /data in the server

**Comment by ghost** [comment]
@davidwindell have you tried it without ESB volume?

**Comment by ghost** [comment]
@davidwindell it is highly probable that this PR fixes the issue https://github.com/eclipse/che/pull/5929

Can you try the latest tag which is 5.16.0?

**Comment by davidwindell** [comment]
Yep, that fixed it, awesome work @RomanNikitenko!
