### ISSUE TITLE
The project still present after deletion through terminal or project service

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5832]
**Reproduction Steps:**
1. Go to the IDE and create 2 Spring projects: Spring#1, Spring#2 for example.
2. Open terminal delete the Spring#1

**Expected result:** the Spring#1 should disappear from the Project Explorer. In the Events panel should present notification message about deleting project
**Actual result:** the Spring project still present in the Project Explorer (but on the file system is deleted). There is no any notifications about deleting.

**OS and version:**   Fedora 25, chrome driver, CHE 5.16.0
**Note:** this usecase is not covered by authotets

**Comment by RomanNikitenko** [comment]
@musienko-maxim Could you confirm the bug is still relevant and provide some details? I can not reproduce it.

![deleteprojectsbug](https://user-images.githubusercontent.com/5676062/29213316-5df1110a-7eab-11e7-8c77-133ecea73472.gif)

**Comment by ghost** [comment]
Just hit F5 to refresh the tab - the project re-appears, moreover it is marked as a valid project. And of course, you cannot expand it since 404 is returned.
