### ISSUE TITLE
Wrong behavior "Add or Import Project" form

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5834]
**Reproduction Steps:**
- Go to dashboard -> click "Create Workspace" button
- Choose java stack and click "Add or Import Project" button
- Choose "web-java-spring" project and click "Add" button
- Pay attention that in opened form the "Save" button is enabled
- Click on "Save" button
- Pay attention that chosen project was changed to another 

**OS and version:**    
CHE 5.16.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![peek 2017-07-28 13-04](https://user-images.githubusercontent.com/22724619/28712873-7fec0506-7395-11e7-9a12-6b940ff61760.gif)

**Comment by SkorikSergey** [comment]
Before the **Reproduction Steps** of this issue need next steps:
- From the Dashboard -> click "Create Workspace" button
- Choose a stack and add a project(for example **web-java-spring**) and don't click on the Create button.
After that if create a new workspace then in its project's setting the Save button will be active and after clicking the project's settings will be changed to settings of **web-java-spring** project.
![peek 2017-07-28 12-52](https://user-images.githubusercontent.com/7760565/28715762-306a0944-73a2-11e7-906d-5e15100492b7.gif)
