### ISSUE TITLE
The highliter for NodeJs project set incorrectly

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5838]
**Preconditions:** create a workspace base on NodeJs stack
**Reproduction Steps:**
1. Go to the workspace and create nodejs-hello-world project.
2. Set debugger connection. 
**Expected result:** The app.js file should open, the highlighter should set in first line
**Actual result:** The file is not opened. 

**Env.:** Fedora 25, chrome browser,  CHE 1.16.0

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
