### ISSUE TITLE
Transmission of Websocket Message fails based on Content

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#5843]
Version: 5.15.0-SNAPSHOT:

How to reproduce:

1) in  a project, create a file named pom.xml with the following content: https://gist.githubusercontent.com/invincibleJai/57377d0fd99d7d5a904b4afc5b07d357/raw/3515b741c6d02ed51362126c2fc6ac9204038a38/pom.xml
2) Put a breakpoint in TextDocumentServiceClient (in the Browser) and in TextDocumentService (in the wsagent).
3) open the file
4) observe: you hit both breakpoints
5) add the following text at the end of the file:
```
<plugin>
</plugin>
```
6) close the file and reopen it
7) observe: you only hit the breakpoint in the Browser, but not the one in the wsagent

**Comment by vparfonov** [comment]
can't reproduce it
