### ISSUE TITLE
[ERROR] Error occurs while initializing command...

### ISSUE THREAD

**Issue by profiluefter** [eclipse-che/che#5846]
**Diagnostics:** 
I started Eclipse Che and did create a workspace, but when i tried to create a project it downloads and then prints: 

[ERROR] Error occurs while initializing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-8.pid ] && rm /tmp/docker-exec-8.pid' EXIT; echo $$>/tmp/docker-exec-8.pid; #

**OS and version:**    
Raspberry Pi Raspbian(up-to-date)
I'm NOT using docker because there isn't a version for Raspberry!

**Reproduction Steps:**
I don't know if others have this problem, but at me it occurs when i just do that written above.

**Comment by ghost** [comment]
@Fabian-Fabian docker is a must have dependency for Eclipse Che.

**Comment by profiluefter** [comment]
How to do that? I'm a newbie to docker. 

EDIT: Oops, I forgot i already use docker. Is there a minimum Version?

**Comment by ghost** [comment]
There is a minimum version but I doubt that standard images will run OK on Raspberry Pi.

**Comment by profiluefter** [comment]
The standard image isn't compatible with this architecture  

I used this guide: https://blog.benjamin-cabe.com/2016/04/01/running-eclipse-che-on-a-raspberry-pi 

EDIT: I've just don't read the guide carefully enough.

**Comment by profiluefter** [comment]
I just tried it with some changes for "compatibility for armhf", but it is still not working.

Error message:
Could not start workspace wksp-java. Reason: Start of environment default failed. Error: Error occurs while initializing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-4.pid ] && rm /tmp/docker-exec-4.pid' EXIT; echo $$>/tmp/docker-exec-4.pid; command -v pidof >/dev/null 2>&1 && { pidof che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1 } || { ps -fC che-websocket-terminal >/dev/null 2>&1 && echo 0 || echo 1 }] in docker container 9186592d4cfc675dea54317039f51406788c0aab91c9083c4f700b5bd1286779: Error response from docker API, status: 500, message: Container 9186592d4cfc675dea54317039f51406788c0aab91c9083c4f700b5bd1286779 is not running

**Comment by ghost** [comment]
@Fabian-Fabian you will need a different stack image. I cannot provide instructions at the moment, but recall some ppl from a community managed to run Che in Pi.

**Comment by profiluefter** [comment]
I did change the stack image, but it still doesn't work

**Comment by ghost** [comment]
@Fabian-Fabian it will definitely help others help you if you shed some night on how exactly you modified stack image. Thanks.

**Comment by profiluefter** [comment]
My stacks.json:

https://paste.sh/UYDhHJl7#FtXtyhlCT_9cK0970BLbOtZ3

PS: I tried it with a simple Java Stack

**Comment by ghost** [comment]
@Fabian-Fabian perhaps author of this image can help you better - `kartben/armhf-che-jdk8`

Meanwhile, on your Pi, can you run this image manually?

`docker run -ti kartben/armhf-che-jdk8`

**Comment by profiluefter** [comment]
I can run the image without errors, but it happens nothing. 
When I start the process, it waits 5 seconds and then quit.

**Comment by ghost** [comment]
@Fabian-Fabian if you want to get help please invest some time in describing the issue you face in details. Any logs?

It looks like the image that you use cannot start, so the container exits.

**Comment by profiluefter** [comment]
Oh sorry, you were right, the container can't start and "docker logs --details xxx" also didn't output anything. I will look for a better image.
