### ISSUE TITLE
Cursor position jumping back to top of file.

### ISSUE THREAD

**Issue by bellers** [eclipse-che/che#5850]
Cursor position skips back to the top when moving away and back to a tab. This happens after certain files are introduced to the workspace. For example, it doesn't happen on a workspace and then after creating a testfile with the contents of the link below it will proceed to happen on that workspace from thereafter. Makes working on large files very frustrating.

**Reproduction Steps:**

- Copy the following file into a workspace:

https://raw.githubusercontent.com/magento/magento2/develop/app/code/Magento/Catalog/Controller/Category/View.php

- Scroll cursor position down in any file within the workspace

- Move away from that tab.

- Move back to that tab (the tab will be positioned back at the top).

**OS and version:**  

Ubuntu 14.04, Chrome 60, Eclipse Che 5.15

**Comment by ghost** [comment]
Fixed in master
