### ISSUE TITLE
Inject CHE Keycloak theme into Keycloak container

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#5854]
In https://github.com/eclipse/che/issues/5786 I [prepared a draft](https://github.com/eclipse/che/files/1187620/che_kc-theme-28.07.17.zip) of Che Keycloak theme. We have to inject Che theme files with puppet into `themes` directory. Path inside Keycloak container: `/opt/jboss/keycloak/themes`. Also branch `che-multiuser-che-theme` contains necessary settings to apply this theme by default (not tested).

**Comment by riuvshin** [comment]
Done https://github.com/eclipse/che/commit/ee5ab96282d1df30028b73904b6e4d3e14cd2e2b
