### ISSUE TITLE
How to speed up a custom assembly build?

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5856]
I'm running the script below as part of our CI pipeline:

```
##!/bin/bash
echo "=> Building the binary"
docker run --rm \
  -v $(pwd):/home/user/che-build \
  -w /home/user/che-build \
  eclipse/che-dev \
  mvn clean install -Pfast
```

This takes 24 minutes to complete on a test machine.

At the moment, the only file we are changing in our custom assembly is https://github.com/outeredge/che/commit/dc8bb5464a3b2afe365465370a1c4da7a783f43c.

I'd appreciate some community advice on how we can speed up the build above. Can we just do a `assembly/assembly-main && mvn clean install` instead? I'm not clear whether the change above would then be "built" into the main assembly as it's in a plugin? Also, it doesn't look like the `fast` profile exists in the assembly-main pom.xml? Thanks!

**Comment by TylerJewell** [comment]
Compiling using a Docker image is about 4x slower than doing it native on your host. If you are willing to set up a dev environment you can then build natively and bypass the container. The wiki has the instructions on all of the software you need installed.

**Comment by davidwindell** [comment]
Thanks, but our CI environment builds everything on docker so there is no native environment. We're happy to accept the performance impact coming from that.

Is there a way to build just the main assembly with our changes above?

**Comment by TylerJewell** [comment]
You can build assembly-main when all of the other plugins and sub-modules have been built for that particular version.  So if you have custom plugins, build those individually, and then build assembly-main. so if you have smart insights into the structure of your custom assembly, then you can incrementally build in order like this.

**Comment by ghost** [comment]
@davidwindell you do not need to build the IDE stuff, looks like only ws-master, then ws-master server and then assembly main. No IDE, no plugins, no dashboard.

**Comment by davidwindell** [comment]
@eivantsov thanks, how do I do that and still end up with the one assembly zip file to mount in as a volume?

**Comment by ghost** [comment]
You mount assembly main only in any case, right?

**Comment by davidwindell** [comment]
Yeah, that's right (hence why I'm a little confused lol!). The change I make to the docker machine cleaner plugin works when mounting the target folder under assembly-main does that mean that going into the directory and mvn building will do what I need? (Sorry about my limited Java knowledge!)

**Comment by ghost** [comment]
Yes, you will eventually build assembly main that will package wsmaster war into server tomcat.

**Comment by davidwindell** [comment]
@eivantsov doing a `cd assembly/assembly-main && mvn clean install` doesn't seem to build our change in (only `mvn clean install` in the root does).

What command should we use instead to just build ws-master and main?

**Comment by ghost** [comment]
Build modules in this order:

1. https://github.com/eclipse/che/tree/master/plugins/plugin-docker (your custom jar will be installed in a local maven repo)
2. https://github.com/eclipse/che/tree/master/assembly/assembly-wsmaster-war (your jar will be packaged into a ws-master war)
3. https://github.com/eclipse/che/tree/master/assembly/assembly-main (ws-master war along with other wars is packaged into a tomcat server)

**Comment by davidwindell** [comment]
Ah, so I go into each folder! Something like:

* `cd plugins/plugin-docker && mvn clean install -Pfast`
* `cd assembly/assembly-wsmaster && mvn clean install -Pfast`
* `cd assembly/assembly-main && mvn clean install -Pfast`

Which gives me `eclipse-che-*.tar.gz`? :)

**Comment by ghost** [comment]
Not necessarily `cd`

For example -  `mvn clean install -f /path/to/module/pom.xml`

**Comment by TylerJewell** [comment]
Maven is a dependency management solution where artifacts from one build depend upon those from another. If you build assembly-main and maven cannot find the artifacts that match the version in our registry, then it will analyze all of the dependencies and then build them one at a time. But if many of the dependencies are not changed, you can just go build the leaf dependencies one at a time, and then build the things that depend upon those dependencies, and then build assembly-main.

**Comment by davidwindell** [comment]
That works brilliantly, thank you for taking the time to help and for explaining the mystery of Maven!
