### ISSUE TITLE
CHE-660 Connection timeout when updating a sizable project

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#586]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-660
Reporter:  Eugene Ivantsov
Description: This issue can be reproduced on a hosted environment like nightly4.codenvy-stg.

Steps to reproduce:
1. Import che repo
2. Open a project, open assembly-main module
3. Project is being updated.

PUT request fails due to connection timeout. Then another PUT request is initiated. It fails as well.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/pull/605
