### ISSUE TITLE
CHE-661 unzip ws-agent in quiet mode

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#588]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-661
Reporter:  Florent Benoit
Description: when starting ws agent, we see in logs tons of messages about the unzip of the agent.zip file
we don't need to see these traces

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/48a2e54df661619291cc0130c3759fa2a170486b
