### ISSUE TITLE
There is an external notification while working with the File Watcher exclude feature

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5883]
**Reproduction Steps:**

1. Start a workspace from the **Java** stack with the **web-java-spring** project
2. Menu  **Project** -> **Show/Hide Hidden Files**
3. Click right mouse button on any file from the project folder and from context menu select **Add to File Watcher excludes**.
4. From **.che** folder open **fileWatcherIgnore** file
5. Do step 3 with any file

**Observed behavior:**
There is an external notification (**File 'fileWatcherIgnore' is updated **) in the **Events** panel. 

**Che version:** 5.16.0-SNAPSHOT
**OS and version:** Fedora 25
**Failed test:** _CheckFileWatcherExcludeFeatureTest_

**Additional information:**
![config-41](https://user-images.githubusercontent.com/7760565/28880035-74515262-77ac-11e7-982a-0c7f42a6bcc5.gif)

**Comment by vparfonov** [comment]
@SkorikSergey, @musienko-maxim  Add selenium test class in description, please

**Comment by dmytro-ndp** [comment]
The problem has still remained in Che 5.x: see failed tests [CheckFileWatcherExcludeFeatureTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/114/testReport/junit/org.eclipse.che.selenium.filewatcher/CheckFileWatcherExcludeFeatureTest/checkIsNotExcludeOperationEventAboutIgnoreFile/).
@RomanNikitenko, @vparfonov: please, take a look at this.

**Comment by vparfonov** [comment]
@dmytro-ndp thanks for you attention. For Che we determinate this as normal behavior and `CheckFileWatcherExcludeFeatureTest.checkIsNotExcludeOperationEventAboutIgnoreFile` need to remove.
@SkorikSergey can you remove this test from master branch
