### ISSUE TITLE
che idle timeout 5.15

### ISSUE THREAD

**Issue by shadowcodex** [eclipse-che/che#5898]
Currently when running latest version our workspace's timeout/idle when not used for some time (within 24 hours). I'd like to set a single workspace as persistent and to not idle or timeout. I have not been able to find clear documentation for doing this.

**Comment by ghost** [comment]
@shadowcodex timeout will be in che.env soon. Right now, AFAIK, it is hardcoded (one hr).

**Comment by ghost** [comment]
https://github.com/eclipse/che/pull/5896 makes timeout configurable in che.env
