### ISSUE TITLE
Move retrieving of estimated environment from RuntimeInfrastructure to RuntimeContext

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#5901]
Related to SPI branch only.

Now normalized by infrastructure implementation environment can be retrieved in RuntimeInfrastructure#estimete.
We want to move it to RuntimeContext#getEstimatedEnvironment.

**Comment by gazarenkov** [comment]
I am not sure in it now :) 

I just realized that RuntimeContext may be delegated to do more job, for example - it seems to me that image building (if any) can be delegated here.

So, probably we have to leave RuntimeInfrastructure#estimate as it is and reuse it calling when create RuntimeContext.

**Comment by garagatyi** [comment]
Currently, RuntimeContext downloads environment recipe if it is needed. If you think we should leave estimation in RuntimeInfrastructure then I suggest removing this functionality from context. WDYT?

**Comment by gazarenkov** [comment]
Let's consider moving this code to RuntimeInfrastructure OR to some utility class then.
