### ISSUE TITLE
SPI OpenShift Infrastructure: support recipes of type dockerimage

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#5904]
In SPI branch OpenShift infrastructure only support recipes of type `openshift` but we want users to be able start workpace on OpenShift based on a `dockerimage` recipes too. 

A first implementation of the `dockerimage` recipe support has been made in the `OpenShiftConnector`. This issue is about deprecating `OpenShiftConnector` and porting its logic in the new SPI based OpenShift Infrastructure.

**Comment by sleshchenko** [comment]
depends on https://github.com/eclipse/che/pull/7126
