### ISSUE TITLE
SPI OpenShift Infrastructure: support dockerfile based recipes

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#5906]
In SPI branch, OpenShift infrastructure only support recipes of type `openshift` but we want users to be able start workpace on OpenShift based on a `dockerfile` recipes too. 

That's something that the existing `OpenShiftConnector` is not capable of and therefore should be implemented from scratch.

**Comment by skabashnyuk** [comment]
@l0rd is this issue still relevant for Che7?

**Comment by l0rd** [comment]
No this one can be definitely close
