### ISSUE TITLE
The Version field is not filled after creating a maven project from archetype

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5910]
**Reproduction Steps:** 
**Preconditions:** create a workspace based on java stack.
 * Go to the IDE,  Alt+X -> Select maven in the wizard -> set a name of the project -> Next -> set check Box From Archetype -> Select 
**Expected result:** the version field should have the predefined version 
**Actual result:** the field is empty
![selection_010](https://user-images.githubusercontent.com/1640058/28966748-89f283f0-7920-11e7-80e0-8425491077ae.png)

**OS and version:** chrome browser, fedora v.25, CHE v.5.16.0

**Comment by bmicklea** [comment]
@musienko-maxim can you set the priority?

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
