### ISSUE TITLE
Ability to switch to the Classic Che 5.x layout

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5911]
Since Che 6 would introduce a new IDE layout +panels it would be nice if we have the classic IDE layout as an option to switch to. It could be a redesign of it since I already fell in love with the current Che 5.x Layout.

**Comment by TylerJewell** [comment]
We hear you @sr229.  But unfortunately the work that was required for the new layout was deep engineering and not something that is reversible.  There will not be a flag for switching it back and forth.

**Comment by sr229** [comment]
I kinda liked how ergonomic was the Classic layouts so it would be nice to ship with two panel layouts instead of just one so the user has more than one choice
