### ISSUE TITLE
Add possibility run Junit suites from editor

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5912]
On this moment we can run tests defined in a Junit testsuite only through project explorer. But many users launch a tests from suite using Editor (if junit testsuite class has been opened in an editor). Also all main IDE support this fuctionality. I think we should implement this in the CHE

**Comment by ibuziuk** [comment]
@musienko-maxim duplicate ?

[1] https://github.com/eclipse/che/issues/5890

**Comment by ibuziuk** [comment]
> On this moment we can run tests defined in a Junit testsuite only through project explorer

it is also possible to run tests via "Run" menu & selection in the editor ?

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
