### ISSUE TITLE
only one stack is visible  in eclipse che that build customly from che 5.14.0 release

### ISSUE THREAD

**Issue by karthikchakravarthy** [eclipse-che/che#5914]
**Reproduction Steps:**
changed the value of CHE_PREDEFINED_STACKS_RELOAD__ON__START to true in che.env
changed the value of che.predefined.stacks.reload_on_start to true in che.properties.
added a new stack in stacks.json in che-core-ide-stacks and rebuilt it.
rebuilt the assembly wsmaster war and assembly main.
and reran the eclispe che by using che 5.14.0 release as a repo

**OS and version:**    
 windows 10
**Diagnostics:**

**Comment by bmicklea** [comment]
@eivantsov can you investigate?

**Comment by ghost** [comment]
@karthikchakravarthy please provide step by step instructions how you initially started Che. If you have added one stack, then previously you saw all of them?

**Comment by karthikchakravarthy** [comment]
The problem is resolved i had added a stack which is may of old syntax of stack data model . I rewritten the stack and all the stacks with my new stack are visible now thank for your response
