### ISSUE TITLE
when che create a workspace, it fails to update pod metadata

### ISSUE THREAD

**Issue by Jooho** [eclipse-che/che#5917]
Hi,
I have tested it on openshift 3.5. 

On openshift, I run che-host and I try to create workspace from dashboard.
However, it failed to start up workspace due to following error message:
~~~
INFO: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"che-ws-w8nj6d3fi1gs1mdu-505330371-tgnk7\" is invalid: spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`","reason":"Invalid","details":{"name":"che-ws-w8nj6d3fi1gs1mdu-505330371-tgnk7","kind":"Pod","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`","field":"spec"}]},"code":422}
~~~

**Reproduction Steps:**
I followed [this doc](https://libraries.io/github/redhat-developer/rh-che) to set up eclipse che on openshift and try to create workspace.

**OS and version:**    
RHEL7.3
Che 5.16.0
oc v3.5.5.26
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master10.example.com:8443
openshift v3.5.5.26
kubernetes v1.5.2+43a9be4

**Diagnostics:** 

I debuged this issue and I realised this issue is from [this code](https://github.com/eclipse/che/blob/master/plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java#L1589-L1597)

From APIwise, it uses following:
~~~
curl -H "Accept: application/json, */*" -H "Authorization: Bearer *****" -H "User-Agent: oc/v1.5.2+43a9be4 (linux/amd64) kubernetes/43a9be4"   -H "Content-Type: application/json" -X PATCH -d '[{"op":"add","path":"/metadata/labels/cheContainerIdentifier","value":"33a873da77f7"}]' https://master10.example.com:8443/api/v1/namespaces/eclipse-che/pods/che-ws-w8nj6d3fi1gs1mdu-505330371-tgnk7
~~~

With same api with Content-Type is "application/json-patch+json", it is possible to change che-host pod but workspace pod still show same error messages.

So I guess pod is something different from between deploymentConfig and replicaset.

I attached 5 files : Workspace_Trace_Error.log  / Success_API_with_che-host.log / Fail_API_with_workspace.log / openshift_webconsole.png / che_dashboard.png

[logs.zip](https://github.com/eclipse/che/files/1201882/logs.zip)
![openshift_webconsole](https://user-images.githubusercontent.com/2375181/28990155-97939936-7948-11e7-99f2-c4f85435c5b0.png)
![che_dashboard](https://user-images.githubusercontent.com/2375181/28990228-4e0059f2-7949-11e7-9890-b7a2b42bb519.png)

**Comment by hbhargav** [comment]
@Jooho 
Can you post a screenshot of browser console ?

**Comment by Jooho** [comment]
@hbhargav 
Which browser console you want to see?
I upload openshift/dashboard.

**Comment by Jooho** [comment]
@hbhargav 

When I add system:serviceaccount:eclipse-che:default to hostnetwork scc, now the workspace is running.

should I update this ?

**Comment by Jooho** [comment]
@hbhargav I think ocp cluster has some issues.. now it works without any reasons.

So I close this case now.
