### ISSUE TITLE
CHE-666 Refine icons in project configuration wizard

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#592]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-666
Reporter:  Stévan Le Meur
Description: We need to apply colors on the icon in the project configuration wizard.

At this moment, it does not look OK.

!Screen Shot 2016-03-01 at 12.05.38.png!

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/39bc42f1adcfd1d5d174ca955bdaea8d783ce1f3
