### ISSUE TITLE
The Print button of the Key Bindings widget doesn't work

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5921]
**Reproduction Steps:**
- Create a workspace
- Menu **Assistant** -> **Key Bindings**
- Click the **Print** button

**Observed behavior:**
Nothing changed.
If the workspace has a project then after clicking will opens the first file(by alphabet sorting) of the project.

**Che version:** 5.16.0-SNAPSHOT
**OS and version:** Fedora 25

**Additional information:**
![config-43](https://user-images.githubusercontent.com/7760565/29025098-cfb7a712-7b7d-11e7-88b0-8710dbc6171f.gif)

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.

**Comment by RomanNikitenko** [comment]
Fixed by https://github.com/eclipse/che/pull/8183 for che6
