### ISSUE TITLE
Add 'Git local changes panel'

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#5924]
Add 'Git local changes panel' that will show list/tree of changed files.

- The panel should be placed in the bottom panels area.
- The panel should show changed files (compare with lates).
- Clicking on the file should open/activate the file in the editors area

**Comment by slemeur** [comment]
This issue will duplicate the capabilities expected in the dedicated git panel https://github.com/eclipse/che/issues/5128. 

I see no important value in this issue regarding the expectations in #5128.

**Comment by tolusha** [comment]
@slemeur 
Just to recall, are we going to display list of changed files on the left side panel?
Our concerns were about that panel might be too narrow with comparison to the path of the file.

**Comment by slemeur** [comment]
We will handle that in the git panel. We will have a tooltip displayed on hover, to display the full path and we will also provide the ability to display the list of files in a tree view. 

Will be fixed by #5128
