### ISSUE TITLE
Add hotkeys for the most usefull git actions

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#5925]
It will be useful to add hotkeys for the most usefull git operations.
Also it will be great to have separate group of shortcuts for git operations in the keybinding list.

List of shortcuts:
- git commit `Alt + c`
- git push `Alt + Shift + c`
- git pull `Alt + p`
- git branches `Ctrl + b`

**Comment by gazarenkov** [comment]
Could you please specify what exactly operations you have in mind, it sounds quite strange otherwise

**Comment by mmorhun** [comment]
It is under discussion now. Actually this issue is the place where others can describe their vision for this.
But we think that we have to add shortcuts for:
- git commit
- git push
- git pull
- git branches

**Comment by mmorhun** [comment]
@slemeur I updated description. Please take a look and approve or give some proposals.

**Comment by slemeur** [comment]
seems okay for me.
Don't forget that those keyboard shortcuts needs to be in the docs + in the `Assistant` -> `Key bindings`

**Comment by tolusha** [comment]
@mmorhun 
Why shortcuts aren't the same as intellij idea has?

**Comment by mmorhun** [comment]
@tolusha because we aren't intellij idea.

**Comment by tolusha** [comment]
Your explanation hits the nail on the head :)

**Comment by mmorhun** [comment]
Done
