### ISSUE TITLE
Information about error does not displayed if make error in the java class and close this file. 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5926]
In my opinion, it will be great to have some information about error even if file is closed

**Reproduction Steps:**
- Create java stack with project 
- Open the java class and do some error (error marker must be displayed)
- Close this class and pay attention to the project explorer 

**Expected behavior:**
Error markers will be shown in the project explorer

**Observed behavior:**
Error markers are not shown

**OS and version:**    
CHE 5.16.0 ; Chrome 59.0 ; Fedora 25

**Comment by vparfonov** [comment]
For now we can implement this feature. Possibly will be fixed then we will switch to the jdt.ls 
https://github.com/eclipse/che/issues/6157
