### ISSUE TITLE
OpenShift Topology, Repo Location, and Install Guide

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#5928]
Is there a network topology showing how Che will/currently works with OpenShift? Currently there is [https://codenvy.com/docs/assets/imgs/codenvy/AIO.png](https://codenvy.com/docs/assets/imgs/codenvy/AIO.png) at codevy docs [https://codenvy.com/docs/admin-guide/installation/index.html](https://codenvy.com/docs/admin-guide/installation/index.html). It would be nice to see something similar for Che openshift/Kubernetes implementation.

Where is the current Eclipse Che OpenShift adapter repository [https://github.com/eclipse/che/tree/openshift-connector](https://github.com/eclipse/che/tree/openshift-connector)? Is it in master? Is there a guide on how to build and test it on OpenShift Origin?

![image](https://user-images.githubusercontent.com/29362989/29035542-977ca0e4-7b61-11e7-8ca3-ebc3c588b823.png)

**Comment by ghost** [comment]
@JamesDrummond not at the moment. There are manual deployment steps and scripts. As to architecture graphic and overall deployment model, I think this is smth that will be useful both internally and for Che community.

**Comment by gorkem** [comment]
I feel like our current docs cover this already
