### ISSUE TITLE
CHE-665 Refine icons in git menu

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#593]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-665
Reporter:  Stévan Le Meur
Description: At this moment the icons in the Git menu are looking horrible.

We need to adjust there sizes so it'll look consistent.

!Screen Shot 2016-03-01 at 12.05.22.png!

**Comment by ddementieva** [comment]
Fixed
