### ISSUE TITLE
Implement heartbeat mechanism with JSON RPC protocol

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5935]
Need to implement ping-pong mechanism for detecting websocket connections or ability to use heartbeats for keeping connections alive. We already have it in everrest websocket implementation.

**Comment by dkulieshov** [comment]
I guess that could be a simple JSON-RPC service receiving a ping request and responding a ping response.

**Comment by ashumilova** [comment]
yes, receiving "ping" and responding "pong" on it - and that's all. Clients will know what to do with that on their own.

**Comment by garagatyi** [comment]
Websocket protocol implements this already, doesn't it? Why do we need to do it on application level?

**Comment by dkulieshov** [comment]
According to websocket specification [section](https://tools.ietf.org/html/rfc6455#section-5.5.2) that describes ping/pong sequences that should be technically possible, however my suggestion is based on similar thoughts: 

> There is no Javascript API to send ping frames or receive pong frames. This is either supported by your browser, or not. There is also no API to enable, configure or detect whether the browser supports and is using ping/pong frames.

> However, if you control both the client and server code, then you can easily add ping/pong support at a higher level. You will need some sort of message type header/metadata in your message if you don't have that already, but that's pretty simple. 

Origin: https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser

And that seems to me much easier to implement and to support.

**Comment by garagatyi** [comment]
I see your point
