### ISSUE TITLE
Openshift - Workspace Creation fails with error "Unable to initialize IDE" because of 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Jooho** [eclipse-che/che#5946]
Hi,

I tried to create a new workspace and I encounter "Unable to initialise IDE", when I see developer tool, it was because of  'Access-Control-Allow-Origin'

![access-control-allow-origin](https://user-images.githubusercontent.com/2375181/29091084-bb6610a0-7c4f-11e7-93ec-83d89f94faaa.png)

Thanks,
Jooho Lee

**Comment by hbhargav** [comment]
@Jooho 
I'm using the following script as suggested by @l0rd 

curl -fsSL http://bit.ly/2v0getche -o get-che.sh
sh get-che.sh

In addition I made following changes
export CHE_IMAGE_REPO="eclipse/che-server"
export CHE_IMAGE_TAG="nightly"

export OPENSHIFT_NAMESPACE_URL="${CHE_OPENSHIFT_PROJECT}.sysevaluate.com"
export OPENSHIFT_FLAVOR=osio

export OSIO_VERSION=1.0.268

echo "# Deploying on osio"
  curl -sSL http://central.maven.org/maven2/io/fabric8/online/apps/che/${OSIO_VERSION}/che-${OSIO_VERSION}-openshift.yml | \
    if [ ! -z ${OPENSHIFT_NAMESPACE_URL+x} ]; then sed "s/    hostname-http:.*/    hostname-http: ${OPENSHIFT_NAMESPACE_URL}/" ; else cat -; fi | \
    sed "s/          image:.*/          image: \"${CHE_IMAGE_SANITIZED}\"/" | \
    sed "s/    che-openshift-secure-routes: \"true\"/    che-openshift-secure-routes: \"false\"/" | \
    sed "s/    che-secure-external-urls: \"true\"/    che-secure-external-urls: \"false\"/" | \
    sed "s/    che.docker.server_evaluation_strategy.custom.external.protocol: https/    che.docker.server_evaluation_strategy.custom.external.protocol: http/" | \
    sed "s/    che-openshift-precreate-subpaths: \"false\"/    che-openshift-precreate-subpaths: \"true\"/" | \
    grep -v -e "tls:" -e "insecureEdgeTerminationPolicy: Redirect" -e "termination: edge" | \
    sed "s/    keycloak-disabled: \"false\"/    keycloak-disabled: \"true\"/" | \
    oc apply --force=true -f -

I have both Che & Workspaces running on http

**Comment by bmicklea** [comment]
@Jooho I'm closing this as it appears resolved. If not please leave a comment to reopen and explain what is wrong after having used the step suggested above.
