### ISSUE TITLE
Websocket API docs

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#5947]
I can't find any Websocket API docucemntation, particularly I need WS API to watch files (create, save, delete) in a whole project.

**Comment by slemeur** [comment]
Hi @zatsepinvl I don't think we have docs on these components other that javadocs. 
 
@dkuleshov Could you please confirm and advice?

**Comment by dkulieshov** [comment]
That is correct, no docs other than javadocs are available at the moment. Please take a look at [FileWatcherManager](https://github.com/eclipse/che/blob/6bc14afaa08ba2121bb8b1001c29d6711a59aa37/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherManager.java), [FileTreeWalker](https://github.com/eclipse/che/blob/4f1b766dcc47505beafaf00e84c28d298ed3f3f5/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileTreeWalker.java) and [ProjectTreeTracker](https://github.com/eclipse/che/blob/cc8fd2473a66d614bb498534d4124d6bae8d13b0/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/impl/file/event/detectors/ProjectTreeTracker.java) or [EditorFileTracker](https://github.com/eclipse/che/blob/22fecf27d0d69427742ddfa3492bc80a1d035830/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/impl/file/event/detectors/EditorFileTracker.java) classes.

**Comment by zatsepinvl** [comment]
Thanks.
