### ISSUE TITLE
[Regression] Part of the text in the link is not displayed

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5954]
**Reproduction Steps:**
- Create java stack without project or delete all projects in the existing workspace
- Pay attention to the project explorer

**Expected behavior:**
Links in project explorer will be the same like in editor

**Observed behavior:**
Part of the text in the links "Import project" and "Create project" are not displayed

**OS and version:**    
CHE 5.16.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![eclipse che wksp 6ezz](https://user-images.githubusercontent.com/22724619/29119018-1f2c756c-7d0d-11e7-8819-4cdfc02717ba.png)

**Comment by vitaliy-guliy** [comment]
Fixed by https://github.com/eclipse/che/pull/5961
