### ISSUE TITLE
Che thinks Workspace has stopped responding with too long maven-build.

### ISSUE THREAD

**Issue by robbirob** [eclipse-che/che#5958]
On maven-builds with long build-times (a couple of minutes) Che throws an error and restarts the workspace.

![nolongerresp](https://user-images.githubusercontent.com/466034/29124779-310092d4-7d1a-11e7-8111-39250a83427e.png)

Clicking on "Close" doesn't just Close the Dialog, but also seems to shutdown the Workspace.

**Reproduction Steps:**

1.  Create Multi Machine Workspace (Java-MySQL).
2. Import a maven Project with a long build time. 
3. Do a "mvn clean install".
4. Wait.

**OS and version:**    
CentOS 7

**Diagnostics:** 

INFO: (che cli): 5.15.0 - using docker 17.03.1-ce / native

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:5.15.0
 Version:        5.15.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /data
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.15.0
 CHE_HOST:       10.1.102.206
 CHE_INSTANCE:   /data/instance
 CHE_CONFIG:     /data
 CHE_BACKUP:     /data/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   10.1.102.206
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.15.0
 IMAGE_CHE=eclipse/che-server:5.15.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.15.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.15.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.15.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.15.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.15.0
che.env:
 CHE_HOST=10.1.102.206
 CHE_DOCKER_IP=192.168.222.1
 CHE_SINGLE_PORT=false
 CHE_WORKSPACE_AUTO__SNAPSHOT=false
 CHE_WORKSPACE_AUTO__RESTORE=false
 CHE_WORKSPACE_AUTO__SNAPSHOT=false

**Comment by benoitf** [comment]
@robbirob I suspect that maven is eating all of the memory of the container which kill it.
Could you use a workspace with higher memory (increase the memory allocated)

**Comment by robbirob** [comment]
@benoitf I will try that, thanks for your reply.

**Comment by ghost** [comment]
@benoitf is right - it is OEM, and if the IDE cannot reach workspace agent which is a Tomcat server running in a container, this popup is displayed.

**Comment by robbirob** [comment]
Yes, giving "dev-machine" more memory helped. thanks.
