### ISSUE TITLE
Improve networking when running on OpenShift

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#5960]
Currently, internal networking on OpenShift works only if the Che host service is named `che-host`. In short:

- The property `che.workspace.che_server_endpoint` is by default `http://che-host:${SERVER_PORT}/wsmaster/api`
- This property is used for communication between wsagent and wsmaster -- it is added to workspace containers under the environment variable `CHE_API`
- The intent behind the property is that `che-host` is a hostname that gets added to the hosts file of a workspace, so that workspaces can contact wsmaster.
- On OpenShift, `/etc/hosts` is not modified, but it works anyways thanks to OpenShift's internal DNS, so long as the service is named `che-host`
- None of the OpenShift behavior is well-documented, which could lead to support and debugging difficulties in the future.

To improve this issue, a few changes should be made

- There should be some way for Che server to figure out the service name associated with it
- OpenShift integration should not depend on the `che-host` service name, and should work even if the service name is changed
- As much as is possible, OpenShift network configuration infrastructure should be consolidated into one area. We currently sometimes depend on Docker infrastructure, and work around its idiosyncrasies. This makes understanding where some setup comes from difficult.
- (Ideally) Instead of depending on service names anywhere, we should be using ClusterIPs associated with those services, to enable networking even when not all components are in the same namespace

Preferably, development in this area would also be adaptable/useful to the SPI development branch.

**Comment by garagatyi** [comment]
Hi, Angel. There is an inconvenient setting of Che master URL in the master branch your idea is really useful. But in SPI branch OpenShift infrastructure is separated from Docker infrastructure and can use any way of setting the master URL it wants.
So, probably, this issue won't affect SPI branch.
You may consider implementing convenient URL setting in SPI branch and leave OpenShift connector in master work as it is now. It is up to you and Californication team to decide.

**Comment by patlachance** [comment]
Any idea of the impacts of using IP instead of names for environments in which a web proxy need to be configured? For example, it is possible to exclude **IP range** for java apps (using -Dhttp.nonProxyHosts), but not really for utility such as curl of wget that rely on system configuration (no_proxy) which doesn't allow IP range.

**Comment by garagatyi** [comment]
@amisevsk is this issue still actual?

**Comment by amisevsk** [comment]
@garagatyi I don't think so -- I forgot that I had even created this issue. This all should be fixed with the SPI implementation (which is almost old at this point)
