### ISSUE TITLE
CHE-669 Make terminal easier to find

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#597]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-669
Reporter:  Stévan Le Meur
Description: At this moment, it is really difficult to know how to get a terminal in a machine.

We have two wuick things to do to improve that.

_1-Change the get terminal icon_
Instead of the "+" button let's use this button:

!Screen Shot 2016-03-01 at 14.39.49.png!

_2-Add an entry in Run menu to get a terminal_
At first line:
!Screen Shot 2016-03-01 at 15.00.21.png!
add "Terminal" with terminal icon that we have in the console panel.
then add a separator

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/b1fbe7f3366a20644c24ba9eddfbeffcc82141fc
