### ISSUE TITLE
External libraries are not downloaded with project

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#5970]
**Reproduction Steps:**
- Create workspace based on java stack with spring default project
- Open root folder 
- Open "External libraries" folder
- Pay attention that "External libraries" folder is empty and libraries are downloaded after opened this folder

**OS and version:**    
CHE 5.16.0 ; Chrome 59.0 ; Fedora 25

**Comment by riuvshin** [comment]
@vparfonov

**Comment by eivantsov** [comment]
@Ohrimenko1988 @riuvshin Cannot reproduce in 5.17.0-SNAPSHOT.

**Comment by ghost** [comment]
Moreover, since libs aren't downloaded, all imports in project classes aren't resolved. Labeling as P1.

**Comment by riuvshin** [comment]
@Ohrimenko1988 does that happens for any maven project? or in some particular case?

**Comment by ghost** [comment]
@riuvshin only when ws and a project are created from the dashboard.
