### ISSUE TITLE
There is error notification after project deletion from workspace details page

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5973]
**Reproduction Steps:**
- Create a workspace with two or more project and start it
- Wait importing of the projects and go to this workspace details page
- In the **Project** tab delete any project and press **Save** button
- Restart the workspace by the **Apply** button
- Try to delete the other project

**Observed behavior:**
The project was  deleted but there is error notification(see screenshot below).

**Che version:** 6.12.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
**Screenshots:**
![selection_128](https://user-images.githubusercontent.com/7760565/45611177-2205bf80-ba67-11e8-9832-bbe1bd77b565.png)

![selection_129](https://user-images.githubusercontent.com/7760565/45612278-30ee7100-ba6b-11e8-8841-9ad00b40d392.png)

**Screencast:**
![screencast-172 19 20 234-8080-2018 09 17-10-33-52](https://user-images.githubusercontent.com/7760565/45611180-27630a00-ba67-11e8-9bd9-304be3a389cb.gif)

**Comment by riuvshin** [comment]
@vparfonov check this please

**Comment by SkorikSergey** [comment]
Still reproduces in Che 6.0.6.

**Comment by riuvshin** [comment]
is this still actual?

**Comment by SkorikSergey** [comment]
Issue updated according to CHE version 6.12.0-SNAPSHOT.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
