### ISSUE TITLE
A html file opens many times in the browser if you start it by using the Find Actions function

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5976]
**Reproduction Steps:**
1. Start any workspace
2. Create a html file and select it in the **Project Explorer**
3. Menu **Assistant** -> **Find Action**
4. Type "**preview**" in the Enter action name and double click on **Preview**

**Observed behavior:**
The html file will opens in many tabs.
Similar behavior with selecting item by double clicking: https://github.com/eclipse/che/issues/5695.
Similar behavior is if click on the **Community**(see pic. 2).

**Che version:** 5.17.0-SNAPSHOT
**OS and version:** Fedora 25

**Additional information:**
![ws-3](https://user-images.githubusercontent.com/7760565/29213871-c81da762-7ead-11e7-9846-cda09300c918.gif)
![teams-4](https://user-images.githubusercontent.com/7760565/29307495-d31e4da6-81aa-11e7-9bd9-5d7e1bcd77b9.gif)

**Comment by riuvshin** [comment]
@vparfonov please check this

**Comment by vparfonov** [comment]
similar to https://github.com/eclipse/che/issues/5695

**Comment by evidolob** [comment]
Cannot reproduce.
