### ISSUE TITLE
Files and folders are not visible if in the Editor opened a file from root of a project folder

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#5986]
**Reproduction Steps:**

1. Create a workspace with two or more projects.
2. Open the first project.
3. In the second project open any file from the root of this project
4. Refresh the page

**Observed behavior:**
After refreshing in the second project visible only files which opened in the **Editor**.
This bug happens if open a file from root of a the second and next projects.
This issue related with https://github.com/eclipse/che/issues/4733.

**Che version:** 5.17.0-SNAPSHOT
**OS and version:** Fedora 25

**Additional information:**
![teams](https://user-images.githubusercontent.com/7760565/29265126-7c0aff36-80e8-11e7-8608-6fa84d6cc4b2.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look

**Comment by vzhukovs** [comment]
Duplicates https://github.com/eclipse/che/issues/7128
