### ISSUE TITLE
Opening a file using Assistant > Navigate to File with double-clicking creates multiple tabs

### ISSUE THREAD

**Issue by vazexqi** [eclipse-che/che#5992]
If you use the Assistant > Navigate to File with the mouse, it create multiple tabs of the same file.

**Reproduction Steps:**

I can reproduce this locally on my own instance of Che. But, this is reproducible on the instance that is running on CodeEnvy as well so I am using those steps here.

1. Create a new workspace in Che.
1. Use the che-in-che project.
1. Wait for the project to be ready.
1. Use Assistant > Navigate to File to open the XMLTreeTest.java file. **I used my mouse to double-click the option and select it. This seems to be the trigger since using just the keyboard and hitting enter doesn't produce the issue.**
1. Notice that it opens up multiple tabs with the contents of the file.

See the following gif for the issue
![multiple_tabs](https://user-images.githubusercontent.com/54414/29282660-7a838184-80d8-11e7-967f-9d6a10fb12a0.gif)

**OS and version:** OS X on Chrome.

**Comment by bmicklea** [comment]
@eivantsov I can't reproduce this on codenvy.io, can you try?

**Comment by ghost** [comment]
I can reproduce it. Although it was 4 tabs of the file for me :)

**Comment by SkorikSergey** [comment]
Duplicated: https://github.com/eclipse/che/issues/5695.
Similar issue: https://github.com/eclipse/che/issues/5976.
