### ISSUE TITLE
Code completion on large files moves cursor randomly to top of file

### ISSUE THREAD

**Issue by vazexqi** [eclipse-che/che#5993]
I've noticed that the code editor on Che on large files (> 1000 LOC) has some strange behavior. I suspect that this is because of the current way that sends the entire contents of the file over to the server. As the LOC increases, this becomes a real bottleneck.

**Reproduction Steps:**
 
I can reproduce the issue on a local installation of Che, but you can see the issue easily on the Codenvy version as well.

1. Start up a new Che workspace with Java support.
1. For this example, use the che-on-che project.
1. Wait for the maven configuration to take effect so that we can get code completion.
1. Pick a file that is > 1000 LOC. I used XMLTreeTest.java
1. Navigate to the end of the file (this is not strictly necessary but is how I tested).
1. Start typing quickly and invoke code completion.
1. Notice if you start typing too quickly, it bounces your cursor to the top of the file randomly.

See attached gif.

![not_catching_up](https://user-images.githubusercontent.com/54414/29283471-b06707fa-80db-11e7-8c1b-ee0737796154.gif)

I've noticed the same issue with Che locally on my own, simple language server. This makes it hard to  use Che for code editing of larger files. 

I think this is an underlying issue with the current Che protocol. Are there any plans to optimize this?

**OS and version:**   OS X and Chrome, but this shouldn't matter.

**Comment by ghost** [comment]
@vazexqi this is fixed in master. If you try the latest nightly tag, the issue should be gone. Thanks for reporting it.
