### ISSUE TITLE
Ability to add connections in the IDE

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#5994]
currently the only way to do it is going to dashboard and adding it as a machine or use the ``ssh`` command from the terminal. It would be nice if we can add connections from the IDE itself

**Comment by ghost** [comment]
@sr229 what is `add connections`? Can you elaborate please?

**Comment by sr229** [comment]
@eivantsov a remote machine that can be SSH'ed or creating a another Docker container to supplement the main workspace container

**Comment by ghost** [comment]
Sorry, but if you want to have a good answer here, please take some time in explaining it in a bit more details. What is a remote machine in your case?

**Comment by sr229** [comment]
@eivantsov It could be a physical machine or a container that is connected in the internet and can be accessible by a remote shell (like SSH). Che already has this feature although you can't really do this inside the IDE and you have to navigate to the dashboard

![image](https://user-images.githubusercontent.com/14976516/29393425-27622766-8336-11e7-9f8f-8fcb7e80398e.png)

**Comment by gazarenkov** [comment]
@sr229 This is part of Workspace/Stack configuration, something which will be accessible runtime, when workspace starts. IDE naturally does not contain it since there are no workspace creation/configuration functionality there (unlike UD)
