### ISSUE TITLE
Adapt creating  workspaces by REST API for selenium test for SPI branch

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5999]
In the SPI branch have been changed many objects for new REST API. For selenium tests most workspaces create and prepare in background through REST. We should adapt creation workflow for selenium tets

**Comment by gazarenkov** [comment]
I think involving @garagatyi will speed it up significantly

**Comment by musienko-maxim** [comment]
It has  been already done by M. Kuznetsov.
