### ISSUE TITLE
Options for displaying artifact id in the maven project does not working when project created from dashboard

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6000]
**Reproduction Steps:**
- Go to dashboard and create java stack with default "java-spring-project"
- Wait until workspace will be started
- Go to "Profile" -> "Preference"
- Chose Maven and change state of the "Show artifact id in project explorer" checkbox 
- Pay attention that state of the project explorer does not changed

**Expected behavior:**
After change checkbox state , the project id must be displayed (or not displayed if before changes checkbox was enabled)

**Observed behavior:**
Artefact id in the project explorer does not displayed in any cases.

**OS and version:**    
CHE 5.17.0 ; Chrome 59.0 ; Fedora 25

**Comment by SkorikSergey** [comment]
Artifact Id will appears if rename this project and will disappear if change the name to the previous.
**Artifact Id will be visible if it not equal to a name of a project.**
![teams-6](https://user-images.githubusercontent.com/7760565/29315720-52a6501a-81cd-11e7-8149-3ab3a108d08d.gif)

**Comment by vinokurig** [comment]
This is expected behaviour, Artifact ID is displayed only if it is different from package name. Created a PR to docs that explains that, @slemeur WDYT?
