### ISSUE TITLE
Rework and migrate dockerimage recipe 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6006]
Related to SPI branch only.

Now `dockerimage` recipe uses next format:
```
{
    "type" : "dockerimage",
    "location" : "eclipse/ubuntu_jdk8",
    "contentType" : null,
    "content" : null
}
```

Since field 'location' is supposed to contain URL to recipe content we decided to move docker image from `location` field to field `content`, e.g.:
{
    "type" : "dockerimage",
    "location" : null,
    "contentType" : null,
    "content" : "eclipse/ubuntu_jdk8"
}

In addition to making Docker infrastructure use content field instead of location, in this case, we also need to migrate dockerimage environment type in all the cases: Codenvy DBs, accepting workspace config and factories in a backward compatible way.

**Comment by gorkem** [comment]
This sounds like an expensive migration for a marginal benefit

**Comment by mshaposhnik** [comment]
@skabashnyuk @garagatyi As far as I understood it is not supposed  removal of `location` field ? It is still valid for `dockerfile` types, correct?

**Comment by mshaposhnik** [comment]
@garagatyi @skabashnyuk so I see 3 aspects what has to be done:
1) Fix recipes in predefined stacks (`stacks.json`);
2) Migrate DB `environmens` table;
3) Remove code workarounds like [this](https://github.com/eclipse/che/blob/master/infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/dockerimage/DockerImageEnvironmentFactory.java#L48-L53)
Is that all ?

**Comment by skabashnyuk** [comment]
1 and 2 - yes.
3 - no.

**Comment by garagatyi** [comment]
> Is that all ?

Can't say for sure
