### ISSUE TITLE
Freeze (high CPU usage) when adding commands

### ISSUE THREAD

**Issue by wernight** [eclipse-che/che#6012]
**Reproduction Steps:**
1. Open a workspace
2. Go to Commands
3. Duplicate an existing (custom) command, or create a new custom command

Uses 100% CPU in that tab and I need to kill the tab.

**OS and version:**    
Tried Linux and Chrome OS, both running Chrome 60.

**Diagnostics:** 
Che Docker image tagged 5.16.0 running on k8s (but CPU usage is client-side).

**Comment by ghost** [comment]
@wernight I was unable to reproduce. Chrome 60, Ubuntu 14.

**Comment by wernight** [comment]
I never debugged performances on JS code, but I could run something on my side if you like.

**Comment by ghost** [comment]
@wernight is this still an issue for you? I was unable to reproduce. Are you certain it is related to commands?

**Comment by ghost** [comment]
@wernight it may be related to https://github.com/eclipse/che/issues/6311

**Comment by wernight** [comment]
Could be. I didn't check memory usage.

**Comment by ghost** [comment]
@wernight is this still an issue if you try the latest nightly?

**Comment by ghost** [comment]
@wernight I am going to close this as cannot reproduce. Feel free to reopen if you can consistently reproduce it.
