### ISSUE TITLE
Adapt swagger to use keycloak openid authentication

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#6015]
We need to make swagger functional with keycloak auth on api.   That probably means adding `/docs/ ` URL to KC filter exlusions and add  KC JS library into swagger to sigh every request (similar like it did in dashb)

**Comment by gorkem** [comment]
Why do we want to protect swagger docs?

**Comment by mshaposhnik** [comment]
@gorkem  no we just want to allow swagger to access  API which is protected

**Comment by garagatyi** [comment]
@skabashnyuk can we close this issue?
