### ISSUE TITLE
There isn't syntax highlighting in cs files after a workspace restarting

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6016]
**Reproduction Steps:**
1. Create a workspace from the **.NET** stack with the **dotnet-web-simple** project.
2. Open the **Program.cs** file and wait initialization of the language server.
3. Stop the workspace with snapshot and start it.

**Observed behavior:**
There isn't syntax highlighting  in the  Program.cs file.
After refreshing the web page syntax highlighting will appear, but without notification markers.

**Che version:** 5.17.0-SNAPSHOT
**OS and version:** Fedora 25

**Additional information:**
![teams-11](https://user-images.githubusercontent.com/7760565/29361783-bdee3ff8-8291-11e7-94ea-2e3bbee80f2a.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look
