### ISSUE TITLE
CHE-673 Unexpected behavior "Commands" dialog

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#602]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-673
Reporter:  Roman Nikitenko
Description: Steps to reproduce:
1. Commands widget -> Edit commands
2. Change name of existing command
3. Press tab and select "Cancel" button("Cancel" in the focus)
4. Press enter
You can see - command will be renamed, but shouldn't!

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/4d6379d3dea5fa69804fc2e8ff3ddd51e2779407
