### ISSUE TITLE
Add 'Git revert commit' action

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#6024]
It is useful for developers to have ability to revert files to latest Git version. The action should be present in the main Git menu, context menu of project explorer and context menu of the file in the editor.

**Comment by bdshadow** [comment]
hi che team! I know that there will be a planning soon, so this task is going to be assigned to smb. And i hope that it hadn't assigned and started by anybody yet.
I've almost finished with it: https://github.com/bdshadow/che/commit/bff9513e34dd89b6567b09b7bc519244cd911c62
In case of hesitations. you can try to pull and try it - it works.

I'll make a PR in a couple of days, when i finish with tests and adding javadocs.

**Comment by tolusha** [comment]
@bdshadow nice to hear!

**Comment by vinokurig** [comment]
It has to be similar to `git checkout <file path>` by native Git

**Comment by tolusha** [comment]
@bdshadow If you don't mind we will finish this issue in our next sprint starting 20.09 using your PR

**Comment by bdshadow** [comment]
@tolusha no problem! Sorry for not replying for so long. I was in PTO

**Comment by riuvshin** [comment]
@bdshadow @tolusha should we close issue?

**Comment by tolusha** [comment]
@riuvshin I will a selenium test and close it.
