### ISSUE TITLE
[REGRESSION] Project wizard does not closed after maven project creating

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6025]
Bug is reproduced if ( profile -> preference -> maven -> Show artifact id in project explorer ) checkbox is enabled , if this checkbox is disabled (artifact id is not shown in project explorer) all works correctly.

**Reproduction Steps:**
- Create java workspace without project 
- After workspace will be started, click on "Create project" link
- Choose "web-java-spring" project, input project name and click "Create" button
- Pay attention that project is created but project wizard is not closed, and default commands are not added . 

**Codenvy version:** 
CHE 5.17.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**
Console output:
![screenshot from 2017-08-17 15-13-05](https://user-images.githubusercontent.com/22724619/29411735-c8c97d98-835e-11e7-9a10-ac0769be2fd9.png)

**Comment by SkorikSergey** [comment]
A maven project, that created from the Dashboard, will be without commands if ( profile -> preference -> maven -> Show artifact id in project explorer ) checkbox is enabled.

**Comment by riuvshin** [comment]
@vparfonov please check this
