### ISSUE TITLE
Editor is almost unusable - missing edits, automatically moving cursor to top

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#6026]
The editor is behaving in a way which is making it challenging to use.

I'm experiencing issues while reproducing the workshop doc instructions:
**1- After few edits, the editor's cursor is moving to the top of the file**
![editor-move-to-top](https://user-images.githubusercontent.com/1636769/29413546-066b7766-835d-11e7-88ee-aa3ae796d528.gif)

**2- Some edits are lost**
![editor-remove-changes](https://user-images.githubusercontent.com/1636769/29413438-ab81181a-835c-11e7-9b17-36c57c8f75ea.gif)
(you can see at the end of the animated gif, that I input a `d` and it was removed nearly instantly)

**3- Nearly each input fires the display of the modal loader at the middle of the screen**
![lot-of-events-while-editing](https://user-images.githubusercontent.com/1636769/29413306-3db12f78-835c-11e7-9757-f0f29f5f0ac3.gif)

**Comment by slemeur** [comment]
downstream issue: https://github.com/openshiftio/openshift.io/issues/603

**Comment by slemeur** [comment]
closing with:
https://github.com/eclipse/che/issues/6028
https://github.com/eclipse/che/issues/6027

**Comment by riuvshin** [comment]
is that duplicate of #6028 ?

**Comment by slemeur** [comment]
it has been splitted by @eivantsov into separate issues yes.
