### ISSUE TITLE
Auto save call Updating file loader

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#6027]
On fast connections and local Che this is barely visible. However, if Che is a remote one, each time auto save happens, Updating file loader shows up. Then, Getting projects.

It can be reproduced by using throttling in browser dev console on a local Che.

These loaders  aren't necessary at all.

**Comment by slemeur** [comment]
The problem here is that when the autosave happens, if the user is typing while that event is fired, then the changes are getting lost.

**Comment by sunix** [comment]
@slemeur to properly handle this kind of issue, we should use a OT strategy to sync content changes.

**Comment by slemeur** [comment]
You should discuss that with @RomanNikitenko and @vparfonov. 

I agree that it's something we will need at some point and we should get an epic created in order to plan work on this.
