### ISSUE TITLE
Cursor jumps to the top of the file

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#6028]
Steps to reproduce:

1. Use throttling in dev console to simulate slow connection.
2. Open a Java class and start typing smth. Wait for auto save, then keep typing. 
3. Cursor jumps to the top of the file.

**Comment by riuvshin** [comment]
it looks like this could be fixed by removing loader here https://github.com/eclipse/che/issues/6027

**Comment by slemeur** [comment]
Tested on OSIO. Confirm it is fixed.

**Comment by nkolban** [comment]
+1 for this problem running build 6.15.0.

**Comment by slemeur** [comment]
@vparfonov could you please check this.
cc @rhopp
