### ISSUE TITLE
Wrong git status displayed in editor's tab after pushing changes

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#6033]
After pushing changes onto the remote repository, the git status color used for the committed is incorrect.

**Reproduction Steps:**
1- Do some changes in existing files
2- Create a new file and include content in it
3- Commit and push to the remote repository

*Expected Output:*
The filename color used in the editor's bar is "normal" = gray after the changes have been pushed - exactly as in the project explorer.

*Current Output:*
The filename color is green, while in the git status that file is clean and the color is "normal" in the project explorer.

See attached snapshot and file "deployment.yml" :
![screen shot 2017-08-17 at 17 05 48](https://user-images.githubusercontent.com/1636769/29419355-3a3ca3be-836f-11e7-9424-c48dabd8aa31.png)

**Related to:**
https://github.com/eclipse/che/pull/5722

**OS and version:**    
OSIO Che 1.0.289 - 08/17/2017

**Comment by slemeur** [comment]
@vinokurig : Could you please check?

**Comment by slemeur** [comment]
Can still reproduce it currently

**Comment by vinokurig** [comment]
@slemeur It's in progress now
