### ISSUE TITLE
Opening a terminal tab must take the focus

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#6034]
When the user is creating a new terminal tab or clicking to open an existing, the focus is not given into the terminal, which force the user to click one more time to be able to start typing.

**Reproduction Steps:**
1- Open the Processes panel
2- Click on default terminal provided
--> Focus is not given into the terminal
3- Click into the terminal
--> Focus is given into the terminal and user can start input commands
4- Click to create a new terminal
--> Focus is not given into the terminal

See animated gif:
![switching-terminal-tab-no-focus](https://user-images.githubusercontent.com/1636769/29419752-35beb4b6-8370-11e7-8781-487ca7838062.gif)

**OS and version:**    
OSIO 1.0.289 - 08/17/2017

**Comment by SkorikSergey** [comment]
Similar issue: **Che: Terminal Tab default focus**  https://github.com/eclipse/che/issues/5741.

**Comment by ghost** [comment]
@slemeur yes, looks like a duplicate. Can you please verify and close if necessary?

**Comment by slemeur** [comment]
Yes duplicated by #5741
