### ISSUE TITLE
Language Server loading processes should be an async background process

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6037]
it's a bit irriating to wait for the language server to load for a specific file (for example, the JSON langserver) and displays a loader. It would be nice if the loading process for the LSes would be a background async task and the user can still edit a specific file without waiting for the LS for the file.

**Comment by gorkem** [comment]
Probably a duplicate/subtask of #5231

**Comment by bmicklea** [comment]
Closing as duplicate of #5231
