### ISSUE TITLE
Created files that matches a specific entry in .gitignore does not save after Workspace restart

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6039]
I somehow found this "bug" while adding a ignored file from ``.gitignore `` on our project.

A [Factory](https://nightly.codenvy-stg.com/f?id=factoryyjqh34keob34i0rc) has been created for easier reproduction

**Reproduction Steps:**
1:) using the factory above, create a file named ``config.json`` 
2:) restart the workspace

**Expected**: The file should persist even in restart
**Result**: The file disappears after restart

**OS and version:**    
Codenvy 5.17.0-SNAPSHOT on Windows 10

**Comment by ghost** [comment]
This issue was moved to codenvy/codenvy#2381
