### ISSUE TITLE
There are no any notifications after deleting project from terminal

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#6056]
**Preconditions:** Create a workspace with some projects. Open events panel.
**Reproduction Steps:** Go to the workspace  and delete a project from terminal.
**Expected result:** should appear a notification about deleting project
**Actual result:** the notification does not appear
**Env:** CHE-5.17.0-SNAPSHOT, chrome browser

**Comment by riuvshin** [comment]
@vparfonov check this out pls
