### ISSUE TITLE
CHE-676 Dialogs lose focus when we use tab button

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#606]
This is an autogenerated issue.
Original: https://jira.codenvycorp.com/browse/CHE-676
Reporter:  Roman Nikitenko
Description: For example we have input dialog: text box and two buttons("OK" and "Cancel").
1. Focus on the text box.
2. Press tab button: Focus will be on "OK" button.
3. Press tab button: Focus will be on "Cancel" button
4. Press tab button: dialog will lose focus. I think at this moment focus should be on the text box and dialog shouldn't lose focus when we press tab several times.

**Comment by ddementieva** [comment]
Fixed by https://github.com/eclipse/che/commit/17a39002b1de99bf5e2ddd14cc7183de411faf38
