### ISSUE TITLE
Checking out from a branch with a file open that exists only on that specific branch does not close the editor tab that has it opened

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6062]
Checking out from a branch with a file that exists only on the previous branch makes the IDE hang on "getting item" Loader state and does not close the editor tab with the nonexistent file.

Can be reproduced with this [Stack](https://nightly.codenvy-stg.com/f?id=factoryyjqh34keob34i0rc)

**Reproduction Steps:**
1:) Using the factory I provided, go to project root and do ``git checkout development``
2:) try navigating to ``lib``, open a file, don't close.
3:) run git checkout to ``release`` or ``lts``

Expected Behavior: the tab with the nonexistent file would close.
Observed Behaviour: IDE goes on a long "Getting Item" Loader

![image](https://user-images.githubusercontent.com/14976516/29561503-3c9d2a96-8768-11e7-9024-09f6b6e9af4d.png)

And checking to dev console, you get this type of errors

![image](https://user-images.githubusercontent.com/14976516/29561542-5edd6f76-8768-11e7-9296-8ae322f00e4d.png)

**OS and version:**    
Codenvy 5.17.0-SNAPSHOT on Windows 10

**Comment by sr229** [comment]
It seems to refuse to connect once you leave the IDE

**Comment by ghost** [comment]
@sr229 cannot reproduce. Clara.js was closed as soon as I checked out to a branch. I assume there are poor network conditions on client side

**Comment by sr229** [comment]
I guess this only happens when you throttle the speed. Might need to reproduce this while throttling

**Comment by ghost** [comment]
Either throttle or have a poor connection. Well, when running Eclipse Che in the cloud you need to always to bear in mind that this is a web IDE, so a lot of things depend on networking conditions.

**Comment by ghost** [comment]
@sr229 do you see any changes if you try the latest nightly?
