### ISSUE TITLE
Manual testing of the che-multiuser branch 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6064]
We have new multiuser functionality for che in the developing, on the current stage we need to do checking of the login page and all functionality that related with authentification : creating user, restoring password, negative testing for user creating, features that related with workspace creating and other.

**Comment by Ohrimenko1988** [comment]
- Eclipse che logo on the login page does not clickable (after click on it must be redirected to the started login page)
- Creating of the user name with special symbols (@#$%^&*?:%) is possible
- Creating of the very long (40 and more characters) usernames is possible
- User can see, run, change, delete, the another user's workspaces
- Workspace, that owner has special characters in the name, can`t be opened
- After registration, confirmation letter does not come
- Restore password feature does not work

**Comment by gorkem** [comment]
Is this a list of findings from the manual test?

**Comment by Ohrimenko1988** [comment]
Yes, this is a manual testing result
