### ISSUE TITLE
401 error when opening project from Multiuser Che Dashboard

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6070]
**Reproduction Steps:**
1. Create workspace with projects.
1. Goto _Dashboard_, find workspace and try to open project.

Dashboard opened page with 401 error message:
![screenshot from 2017-08-22 18 33 00](https://user-images.githubusercontent.com/1197777/29607039-abb8eefc-87f8-11e7-94e7-0c5d121df66a.png)

Also there was a problem with obtaining token:
![screenshot from 2017-08-22 18 35 22](https://user-images.githubusercontent.com/1197777/29606955-68d6145c-87f8-11e7-8e38-71f52323b64d.png)

Screencast:
![out](https://user-images.githubusercontent.com/1197777/29607062-bb3adb88-87f8-11e7-982b-d24dcc083418.gif)

This issue is related to #5362.

**Comment by dmytro-ndp** [comment]
It is still actual in Eclipse Che version 5.21.0-SNAPSHOT

**Comment by artaleks9** [comment]
Right now it is not reproduce for CHE master
