### ISSUE TITLE
Add ability to logout from Multiuser Che Dashboard

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6073]
There is no ability to log out from Che Multiuser Dashboard:
![screenshot from 2017-08-23 14 39 13](https://user-images.githubusercontent.com/1197777/29613966-ed272c74-8810-11e7-98b2-ee05bec44009.png)

This issue is related to #5362.

**Comment by dmytro-ndp** [comment]
@ashumilova: could you, please, explain why did you close the issue?

**Comment by benoitf** [comment]
I think it's because it's implemented

**Comment by dmytro-ndp** [comment]
But I don't see pull request, or link on another issue which this one duplicates in comments.

**Comment by benoitf** [comment]
I think it has been merged as part of other items in multi-user branch.
https://github.com/eclipse/che/blob/ee01b2998feac77f3408a80ee6e5386e09e23b9f/dashboard/src/app/navbar/navbar.controller.ts#L30-L42

**Comment by dmytro-ndp** [comment]
I see. Thank you, @benoitf, for your kind comments.

**Comment by ashumilova** [comment]
@dmytro-ndp it was merged along with all multi-user stuff - https://github.com/eclipse/che/pull/6441/files#diff-14a16d160f46cdc140edaabb758eeb7bR220.

**Comment by dmytro-ndp** [comment]
Thank you for explanation.
