### ISSUE TITLE
Project import is broken on slow networks

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#6075]
Steps to reproduce:

1. Turn on throttling in Chrome
2. Create a workspace with a project in UD
3. What the IDE loading

Expected results: The project is imported
Actual results: the project is marked as broken in project explorer and the import never happens. Project api returns `problems: [{code: 10, message: "No project folder on file system /console-java-simple"}]`

**Comment by ghost** [comment]
@vparfonov @ashumilova can you take this one to the next sprint please?

**Comment by vparfonov** [comment]
fixed in https://github.com/eclipse/che/pull/6387
