### ISSUE TITLE
How to use che.sh to run a custom docker image?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#608]
The `che.sh` provides some nice configurations for running che, but the `-i` related options can only be used with che official images, like:

```
che.sh -i run
che.sh -i:nightly run
```

But I have build some che images by myself, which is under `nowind/che` namespace. I can't find a way to pass it to `che.sh` shell.

Is it possible to make che.sh supports custom images?

**Comment by TylerJewell** [comment]
That seems like something that would be outside the scope of the Che scripts.

Any thing is possible but what would be the motivation for doing so?  If you want to launch custom images you could just launch your own docker run commands.  Wouldn't that be easier?

**Comment by freewind** [comment]
che.sh has something like:

```
-p:port
-r:ip
-b
-g
```

which I think is useful, so I'm thinking to use che.sh to run my own che image. I'm not sure if all the options are useful for images.

PS: my own che image is just a backup of `codenvy/che:nightly` some days ago, because the "nightly" of these days are not working well. I treat it as an official image without my custom namespace

**Comment by TylerJewell** [comment]
You could make a quick modification.  The image name I believe is only used in a single location in the entire script.  Look up the run command in the script and replace it with a bash variable.  The input parameters are easy to extend as well.

**Comment by freewind** [comment]
Yes, thanks, I found the location and can modify it easily. 

I just think it might be a general requirement, and could be considered go into the official shell

**Comment by TylerJewell** [comment]
Che shoukd be stabilizing quite quickly these days.  So surprised to hear the nightly is behaving badly.  Any specific issues?

**Comment by freewind** [comment]
Post it here: https://github.com/eclipse/che/issues/609

This issue has been appeared since after 2016-02-16. I just tried latest nightly build, still has the same problem

**Comment by ghost** [comment]
Closing this issue, as it's out of Che script scope.

You may hack the script itself as Tyler has suggested.
