### ISSUE TITLE
OpenShift infrastructure doesn't work on Minishift because of dependency on Docker runtime

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6085]
Related to SPI branch only.
In SPI branch both OpenShift and Docker infrastructures are working. 
On MiniShift Docker infra tries to reach Docker API and fails. 
This prevents us from testing OpenShift infrastructure on MiniShift.
So, we need some way to Disable Docker infrastructure in this case. Probably, it should be done by some property.
Note that it is supposed to be a temporary solution until we realize the proper way to fix it.

**Comment by ibuziuk** [comment]
@garagatyi why do we really need to have both OpenShiftft & Docker infrastructures working simultaneously (is there real usecase for this) ? Could we just have some property for choosing infra when che-server is starting

**Comment by garagatyi** [comment]
It is exactly what supposed to be done by this issue

**Comment by ibuziuk** [comment]
@garagatyi thanks for clarifications. I was just a bit baffled with the following note:
> Note that it is supposed to be a temporary solution until we realize the proper way to fix it.

Was wondering why it is not good enough for the long running solution (not sure that there is a use case where both OpenShiftft & Docker infrastructures need to be working simultaneously)

**Comment by gazarenkov** [comment]
My vision is that it is a right solution.

On a framework level we should be ready to assembly/test/deploy different assembly.
I.e. it is normal when Che have separated Openshift and Docker and many other assemblies, of course they will have different level of support.
Current project structure and tooling/procedure for making necessary assembly/packaging is probably not good enough for the time for this purpose, let's think about it.

So, my conclusion - having separated Openshift and Docker assembly is normal.
Even if SPI provides ability to make multi-infra assembly I can not find any real-life usecase to keep them both in one.
