### ISSUE TITLE
Integration for JavaScript Build Systems

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6088]
Eclipse Che has integration to build systems like GCC. JavaScript, like any other language, has a build system used by many large projects to automate transpilation, getting dependencies, etc. An integration to these Node.js build systems, like gulp, would ease workflow

**Comment by ghost** [comment]
@sr229 are you talking about having these tools installed in a machine (which you can do yourself by the way)? Or is it some UI integration? Smth like a dedicated menu for JS projects?

**Comment by sr229** [comment]
@eivantsov I noticed Che has JUnit and Maven integration from the UI so yes, it's more of a dedicated UI Integration

**Comment by gazarenkov** [comment]
Hi, if you want to improve node-js project type you can contribute to plugins/plugin-nodejs (which currently does almost nothing in fact).

**Comment by sr229** [comment]
thanks for the heads-up about this plugin @gazarenkov ,I'll drag some friends to help me out on this

**Comment by ghost** [comment]
@sr229 I will close this one. You may reopen if you have specific questions related to a soon-to-be-plugin.
