### ISSUE TITLE
TypeScript files has incorrect file icons

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6089]
Noticed this while working on a TS project

they seem to use JS icons

![image](https://user-images.githubusercontent.com/14976516/29654465-ed0c4cd6-88df-11e7-8fd6-b2583ae9dbc5.png)

**OS and version:**    
Codenvy 5.18.0-SNAPSHOT on Windows 10

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/11043
