### ISSUE TITLE
Errors in nightly che

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#609]
When creating a project from dashboard, there is such an error in Chrome console:

```
TypeError: Cannot read property 'status' of undefined
    at app-debdde175d.js:1403
    at l (vendor-94d8cfba30.js:66)
    at vendor-94d8cfba30.js:66
    at h.$eval (vendor-94d8cfba30.js:67)
    at h.$digest (vendor-94d8cfba30.js:67)
    at h.$apply (vendor-94d8cfba30.js:67)
    at o (vendor-94d8cfba30.js:66)
    at g (vendor-94d8cfba30.js:66)
    at XMLHttpRequest.x.onload (vendor-94d8cfba30.js:66)
```

And at the meanwhile, there is not output displayed in the panels of each step:

![output](http://snag.gy/ZqoFl.jpg)

And it will block at this step forever, but the server side has no exceptions in the console

**Comment by ghost** [comment]
Did you run Che natively or in Docker?

**Comment by freewind** [comment]
In docker, this is my command:

```
docker run -ti --net=host 
    -v /var/run/docker.sock:/var/run/docker.sock 
    -v /home/user/che/lib:/home/user/che/lib-copy 
    -v /home/user/che/workspaces:/home/user/che/workspaces 
    -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage 
    -e DOCKER_MACHINE_HOST=198.199.105.97 
    codenvy/che:nightly
```

**Comment by ddementieva** [comment]
We have renamed DOCKER_MACHINE_HOST into CHE_DOCKER_MACHINE_HOST.

As to exceptions in console, I've failed to reproduce it locally.

**Comment by freewind** [comment]
I just tried with the new property `CHE_DOCKER_MACHINE_HOST`:

```
docker run -ti --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage -e "CHE_DOCKER_MACHINE_HOST=198.199.105.97" codenvy/che:nightly
```

but have exactly the same issue

**Comment by ghost** [comment]
I cannot reproduce it locally with Docker. Can you try it in an incognito tab? Create Project flow.

**Comment by freewind** [comment]
The browser in the image of the post is in an incognito window already. I will try it again today

**Comment by freewind** [comment]
I found it a docker issue in my server. I just deleted all the existing docker images `docker rmi -f`docker images -aq``, then restart it, and everything is OK now. Thanks ~
