### ISSUE TITLE
There are no any controls to delete workspaces in Che Dashboard at landing page

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6092]
There is no control elements to delete workspaces from the list at the main page of in Che 5.17 Dashboard:
![screenshot from 2017-08-24 14 38 27](https://user-images.githubusercontent.com/1197777/29664907-55d47b40-88da-11e7-8a5f-5fdea4e4c02b.png)

**Comment by ashumilova** [comment]
It's not related to multi-user branch - it was done on purpose from the very beginning of the landing page.

**Comment by dmytro-ndp** [comment]
You are right, Ann. 
Are there any plans to add delete workspace controls to the landing page of Dashboard?

**Comment by gorkem** [comment]
Delete seems to be there now
