### ISSUE TITLE
403 error page instead of GitHub authorization page in Multiuser Che

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6093]
**Reproduction Steps:**
1. Create and open Che workspace.
1. Goto **Profile > Preferences > SSH > VCS** window.
1. Click on "Generate key and upload it to GitHub" button.

**Expected result:**
Che opens authorization window like the follow:
![screenshot from 2017-08-25 11 59 23](https://user-images.githubusercontent.com/1197777/29707622-91d3da8c-898e-11e7-8974-98c063d10b6c.png)

**Actual wrong result:**
Che opens page with 403 error content inside:
![screenshot from 2017-08-25 11 43 40](https://user-images.githubusercontent.com/1197777/29707266-5e03ecca-898d-11e7-9a91-de8270e6ef8d.png)

**Screencast:**
![out](https://user-images.githubusercontent.com/1197777/29707593-71debbca-898e-11e7-8c18-d425b40b971c.gif)

This issue is related to #5362.

**Comment by skabashnyuk** [comment]
will be fixed by https://github.com/eclipse/che/issues/5943

**Comment by mshaposhnik** [comment]
Checked - SSH key functionality is working.
