### ISSUE TITLE
Feature to add R script language

### ISSUE THREAD

**Issue by dipenpatel235** [eclipse-che/che#6094]
Hello..
How to add R language based workspace and ide
centos7 64 bit

**Comment by ghost** [comment]
@dipenpatel235 can you elaborate on what you mean by R support? If it's all about installing smth in a dev machine, you can do that yourself. If this is about having editor support for R (auto completion, error marking etc), you'd probably need a dedicated language server.

**Comment by dipenpatel235** [comment]
Thanks.
R means it is language script  like Python.
So I dont know how to add that language in it.
Thanks.

**Comment by ghost** [comment]
@dipenpatel235 please be more specific. What do you mean by support?

**Comment by dipenpatel235** [comment]
Support mean can I able to to add that type of specific language editor and
compiler ?

Thanks.

**Comment by dipenpatel235** [comment]
editor support, right now there's no R language server available for Che. - Yes that i am looking for.
Editor + compiler

**Comment by sr229** [comment]
@dipenpatel235 I think you're looking for Language Server Integration and a default stack for it,

The stack itself is easy enough to make

**Comment by dipenpatel235** [comment]
can u please explain me or give some step so i can understand.

i am not understand below point.
The stack itself is easy enough to make

**Comment by ghost** [comment]
@dipenpatel235 you will need to build a Docker image with R script installed. Here are some docs on building stacks: https://www.eclipse.org/che/docs/devops/runtime-stacks

**Comment by sr229** [comment]
@dipenpatel235 currently implementing this as a stack. You can view on how it builds before I make the PR  [here](https://circleci.com/gh/sr229/test-dockerfile/21)

**Comment by dipenpatel235** [comment]
thanks..

**Comment by dipenpatel235** [comment]
ok

**Comment by sr229** [comment]
Recommending closure since a plugin would come sooner for this (if anyone dares to make one), but a full stack with already suffice @eivantsov
