### ISSUE TITLE
how sould I do to build a che-samples/che-ide-extension plugin

### ISSUE THREAD

**Issue by feitiange** [eclipse-che/che#610]
there is a hint in plugin/examples, it points to https://github.com/che-samples/che-ide-extension.git, but I cannot build by mvn ,how should I do to build a che-icde-extension plugin

[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.eclipse.che.depmgt:che-examples-action:[unknown-version](/home/webide/plugin-example/che-ide-extension/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.che.depmgt:che-examples-action:[unknown-version]: Could not find artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:4.0.0-beta-9-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by ghost** [comment]
Change version of parent pom to 4.0.0-RC8

We'll think of the way to keep this repo in sync

**Comment by feitiange** [comment]
I got a 4.0.0-RC3 version, while I change the parent pom to 4.0.0-RC3, I have to add repositories manually, even assembly pom, now it works well, but 4.0.0-RC3 is a stable version?

**Comment by ghost** [comment]
Yes, RC3 is the latest stable version. You can of course try the latest nightly build https://install.codenvycorp.com/che/eclipse-che-nightly.zip

**Comment by TylerJewell** [comment]
@feitiange - please take a look at docs.  The plugin / extension development stuff was rewritten in 4.4.
