### ISSUE TITLE
Unable to run custom assembly

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-che/che#6102]
**Reproduction Steps:**
Build and run the custom assembly at: https://github.com/BarryDrez/softwareag-che.git

To build, run the build.sh script.

To run, use run.sh --che.

If necessary, run dos2unix against the scripts.

**OS and version:**    
Windows 7 running Oracle Virtual Box

**Diagnostics:** 

[cli.log.txt](https://github.com/eclipse/che/files/1261572/cli.log.txt)

**Comment by ghost** [comment]
@BarryDrez looks like a dockertoolbox glitch (issues with mounting win drive into VM). Closing it.
