### ISSUE TITLE
Projects in custom stack

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-che/che#6103]
It's unclear how to use projects in custom stacks.

If I edit the raw config of a custom stack and add a project, then after creating a workspace from this that stack I do not see that project in my workspace. 

This is what I added to stack config:
```
"projects": [
      {
        "source": {
          "location": "",
          "type": "",
          "parameters": {}
        },
        "mixins": [],
        "links": [],
        "problems": [],
        "name": "test-project",
        "type": "blank",
        "path": "/test-project",
        "attributes": {}
      }
    ]
```

Also on the "New Workspace" page it says
> SELECT STACK
> Choose your workspace runtime environment used to build and run your projects.

Projects are not part of workspace environment in stacks. Does this mean, that the project information is ignored then?

**Comment by gorkem** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Item 1](https://trello.com/c/6Aok9QAq/1-item-1)

**Comment by sr229** [comment]
@AlexTugarev There's Documentation on [Runtime Stacks](https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html)

worth a read about it.

**Comment by AlexTugarev** [comment]
@gorkem, it's a private board. Do you want to share something?

@sr229, thanks! That's exactly the thing, have a look at the comment in stack json:
> // Projects can be pre-loaded into the workspace.

I was thinking that predefined projects will be created in new workspace from a stack, but it looks like only `workspaceConfig.environments` is evaluated.

**Comment by gorkem** [comment]
@AlexTugarev sorry, that was me testing the trello integration :)

**Comment by ghost** [comment]
@AlexTugarev location should not be empty. As well as importer type.

```
       "location": "https://github.com/eclipse/che",
          "type": "git",
```
This should do the trick

**Comment by AlexTugarev** [comment]
Actually I tried this with another git repository, but the project was not imported automatically. 'Will give it another try, just in case.

**Comment by ghost** [comment]
@AlexTugarev can you share the entire workspace config if possible?

**Comment by ghost** [comment]
@AlexTugarev any update please?

**Comment by sr229** [comment]
@eivantsov newer snapshot of 5.18.0 seems to allow Workspaces with empty projects

This was done on the new project wizard, not as a stack configuration

**Comment by ghost** [comment]
@sr229 i think what @AlexTugarev needs is to create workspace configs with empty projects.

**Comment by ghost** [comment]
Closing as the original question has been answered. @AlexTugarev feel free to reopen though if you have further questions.
