### ISSUE TITLE
Cannot add blank project in New Workspace wizard

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-che/che#6104]
When I try to add new blank project to a workspace in New Workspace wizard, it still requires to specify Git URL.

![2017-08-30 11 07 00](https://user-images.githubusercontent.com/914497/29864638-9a3cdde8-8d73-11e7-8b32-449a58d7207b.gif)

**Comment by ghost** [comment]
@AlexTugarev you have added a blank project. As you can see, once you clicked Add, project git url appeared and green check marks are there. You then deleted the URL. If you paste it back, Save button will be enabled.

**Comment by AlexTugarev** [comment]
@eivantsov, thanks for answering! Does this mean, that projects can only be created if they are backed by repository or hosted archive? 

Though docs (https://eclipse.org/che/docs/ide/projects/index.html) say "Projects can be mapped 1:1 to a source code repository.", I would not expect this to be mandatory.

**Comment by ghost** [comment]
@AlexTugarev yes, a project needs to be imported from some location.

**Comment by AlexTugarev** [comment]
How about to start with an empty project?

**Comment by ghost** [comment]
Creating an empty git repo might be a suitable workaround
