### ISSUE TITLE
unable to download Eclipse/Che

### ISSUE THREAD

**Issue by xiaolinliu17** [eclipse-che/che#6105]
I try to download and setup Eclipse Che on my computer. 
When I run docker run -it eclipse/che start, got following error message, how can I fix it.

>docker run -it eclipse/che start
INFO: Welcome to Eclipse Che!
INFO:
INFO: You are missing a mandatory parameter:
INFO:    1. Mount 'docker.sock' for accessing Docker with unix sockets.
INFO:    2. Or, set DOCKER_HOST to Docker's location (unix or tcp).
INFO:
INFO: Mount Syntax:
INFO:    Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...
INFO:
INFO: DOCKER_HOST Syntax:
INFO:    Start with 'docker run -it --rm -e DOCKER_HOST=<daemon-location> ...'
INFO:
INFO: Possible root causes:
INFO:    1. Your admin has not granted permissions to /var/run/docker.sock.
INFO:    2. You passed '--user uid:gid' with bad values.
INFO:    3. Your firewall is blocking TCP ports for accessing Docker daemon.

**Comment by sr229** [comment]
@xiaolinliu17 you already have the CLI installed! All you need to do is 

- Mount docker.sock
- mount your temporary directory

Which can be done using 
```bash
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v <path>:/data eclipse/che start
```

Refer to the [Getting Started](https://www.eclipse.org/che/docs/setup/getting-started/index.html) article if you need additional help

If you setup everything correctly, it would download everything that it needs then start Che at http://localhost:8080 (default address)

**Comment by ghost** [comment]
@xiaolinliu17 instructions on how to fix it are in the error message itself.

**Comment by ghost** [comment]
@xiaolinliu17 I am closing the issue due to inactivity. Feel free to reopen though if you still have issues with launching Che.
