### ISSUE TITLE
Mobile application for Eclipse CHE

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#6106]
It may be usefull to have mobile application for Eclipse CHE. Such application should be fast, light, simple, and obviously for user. It should consist of base functionality: editor,  project explorer, terminal, base vcs function. It's not nessusary use GWT for this application, we can use some another technologies.

**Comment by pgagne** [comment]
Desktop app too, using something like electron. This would allow visual separation on the desktop so the page doesn't get lost in a tab somewhere.
