### ISSUE TITLE
Eclipse/che docker Run workspace agent connectivity issues

### ISSUE THREAD

**Issue by varunsai2494** [eclipse-che/che#6110]
I disabled the firewall on ubuntu and on this command 
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/tmp:/data eclipse/che start
Specs:
Ubuntu 16.04 LTS
16Gb Ram

  

**Diagnostics:** 
It gives 
root@imiadmin-Latitude-5480:/home/imiadmin# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/tmp:/data eclipse/che start
WARN: Bound 'eclipse/che' to 'eclipse/che:5.17.0'
WARNING: No swap limit support
INFO: (che cli): 5.17.0 - using docker 17.05.0-ce / native
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
WARNING: No swap limit support
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]

INFO: (che network): eclipse/che-ip:5.17.0: 172.17.0.1
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (172.17.0.1): Connection failed
INFO: (che network): Server  => Workspace Agent (External IP): Connection failed
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded

**Comment by ghost** [comment]
@varunsai2494 perhaps smth else blocks connection in your case. The issue is that two containers are unable to communicate using `docker0` IP.

Can you run `ifconfig` and share the output here?

**Comment by varunsai2494** [comment]
Hi Eugene ,
thanks for replying back!!

[image: Inline image 1]

**Comment by ghost** [comment]
@varunsai2494 you haven't shared an image you wanted to share. Just copy and paste the output.

Also, are you running a VM?

**Comment by ghost** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
