### ISSUE TITLE
Fix logger strings format

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#6119]
It is necessary to fix logger string format throughout the project according to our code styling and also after the new formatter is applied. To get the idea of a wrong format in logs refer to the [link](https://github.com/eclipse/che/blob/master/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/jsonrpc/commons/reception/ResultConfiguratorFromMany.java).

**Comment by bmicklea** [comment]
Is this closed now Dmitri?

**Comment by dkulieshov** [comment]
No, it's not, the work is yet to be done here.
