### ISSUE TITLE
Add script to enable GitHub oAuth  in OpenShift deployment

### ISSUE THREAD

**Issue by kameshsampath** [eclipse-che/che#6120]
Currently the OpenShift deployment scripts does not add Github ENV variables related to oAuth2 enablement. 

Item #5 of the epic #6097

**Comment by eivantsov** [comment]
@kameshsampath it is Che admin who need to register an app on GitHub side and client ID and secret. So, this is impossible to automate and do out of the box.

Here are some docs https://www.eclipse.org/che/docs/version-control.html#github-oauth
