### ISSUE TITLE
Add  JSON-RPC over Websockets back-end in Project API 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#6122]
For now our client (IDE) communicate with Project Service via REST in same time we receive notification from File Watching System via JSON-RPC over Websockets. This situation complicate our model and hard for documentation, so we decide to switch client communication to the JSON-RPC calls.

Under this issue need to:
- add JSON-RPC handlers/transmitters on server-side;
- deprecate ProjectServiceClient in IDE client API;
- replace ProjectServiceClient with JSON-RPC calls  
- remove deprecated classes

**Comment by gazarenkov** [comment]
@dkuleshov could you please draft a short specs (right here) about how we replace REST with JSON-RPC for Project API, it is really interesting and important exercise since there are a lot of different methods.

**Comment by dkulieshov** [comment]
@gazarenkov here is a spec draft https://github.com/eclipse/che/issues/6219
