### ISSUE TITLE
Ports should not be exposed automatically, but rather be explicitly defined in workspace config 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#6124]
Related to SPI.
Machine info from workspace config must contain information about the exposed port in `servers` property:

```
    "workspaceConfig": {
      "environments": {
        "default": {
          "machines": {
            "app/main": {
              "installers": [
                "org.eclipse.che.exec", "org.eclipse.che.terminal", "org.eclipse.che.ws-agent"
              ],
              "servers": {
                "web": {
                  "protocol": "http",
                  "port": "8080/tcp"
                }
              }
            }
.
.
.
```
This would make it easier and more straight forward creating workspaces on different infrastructures ( e.g. no need for inspecting image while creating workspace against `dockerimage` recipe)

**Comment by gazarenkov** [comment]
Not sure I understand the issue ...
Yes, it is expected that servers are explicitly declared (with port and protocol) in the configuration, that is why they needed to give a permanent reference to the client (and be portable).

Or you mean that existed stacks should be checked against this rule?

**Comment by benoitf** [comment]
@ibuziuk when you're saying "This would make it easier and more straight forward"
You're talking about the end user or the developer of the infrastructure ?
If end user has to grab all exposed port of an existing image it might become tricker

**Comment by ibuziuk** [comment]
@gazarenkov this issue has been created as a result of SPI discussion during f2f.  Currently when workspace is created the ports are exposed automatically. The problem is that in order to verify which ports are exposed one needs to run the image first, which make it difficult to implement for OpenShift / k8s infrastructures. 

@benoitf yeah, I was mainly talking from the infrastructure developer perspective. However, there was a good point during the discussion that exposing ports automatically is not smth. that is done by Docker  and can only be achieved by using '-P' flag. So, exposing ports explicitly via machine servers can be also considered as a more secure solution

However, I agree that new policy of exposing ports might be more tricky in some cases and @garagatyi proposed that there should be a possibility of automatic port exposing disabled by default

**Comment by garagatyi** [comment]
@gazarenkov Ilya suggests not to publish ports that are not in servers lists at all. This will make the behavior of Docker and OpenShift infras more consistent and lead to better user experience when if something is available in Docker infra it is available in OpenShift infra too.

@benoitf his is talking about user experience, not the convenience of the infra implementation.

**Comment by garagatyi** [comment]
:) looks like we see the convenience from different perspectives. 
I mean that it would lead to better UX because it is more consistent and would work in the same way on both infras. Ilya says that it is really difficult to implement that automatic ports publishing that we have in Docker API (the mentioned `-P` flag).

**Comment by ghost** [comment]
@gazarenkov and yes, we will re-write `stacks.json` to add servers, so that this file works the same way for both infras.

**Comment by gazarenkov** [comment]
I totally agree that exposing everything as a server is a bad idea.
My confusing is about issue description, in my mind it is a problem of Docker infra implementation, not a rule.
Otherwise - it is OK

**Comment by l0rd** [comment]
@gazarenkov I think we agree that it's something to fix in Docker infra implementation (and default stacks.json should be updated to explicitly list the exposed servers). But I am not sure I understand why it should not be a rule.

**Comment by ghost** [comment]
@l0rd my take-away from SPI discussion was that this `is` a rule, at least for infras where such port publishing (or service + route creation) makes sense.

**Comment by gazarenkov** [comment]
@l0rd I am trying to put as less restrictions as possible for start, we can do that after when have more experience and real demand.

**Comment by sleshchenko** [comment]
Note that current OpenShift implementation allows a user to make container ports publicly accessible by adding own services and routes to OpenShiftRecipe. 
And then ports that are exposed by user's services and routes will have publicly accessible URLs but they wouldn't be resolved as servers. So a user wouldn't be able to get these URLs with IDE.

It is needed to decide in which way it should be done:
1. Leave it as it is. A user is able to expose ports manually in the OpenShift recipe but they wouldn't be resolved as servers.
2. Resolve as servers ports that are exposed manually by a user with services and routes that are present in OpenShift recipe.
3. Deny user to specify Routes in OpenShift. But not services, because they can be useful for internal communication between pods.

**Comment by garagatyi** [comment]
In case of Docker, we have ports exposure in docker image layers, Dockerfile, compose file. With these different types of the environment which ports should be published by Docker infra and which should not be published?

**Comment by sleshchenko** [comment]
While `Spi Sync` daily meeting It was decided to ignore Routes that are specified in OpenShift recipe. Created corresponding issue #6216

**Comment by garagatyi** [comment]
@sleshchenko Rather should be ignored than denied

**Comment by sleshchenko** [comment]
@garagatyi thanks. Fixed comment.
