### ISSUE TITLE
Search is slow and crashes browser

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6126]
The search seems to be ultra slow and can crash the browser after a few minutes waiting for results.

**Reproduction Steps:**
Download a large project (for example) from https://github.com/outeredge/edge-docker-magento/releases/download/2.1.8/Magento-CE-2.1.8.tar.gz, try searching for "test" amongst all files.

**OS and version:**    
Chrome, Ubuntu, Che 5.17

**Comment by ghost** [comment]
@davidwindell IDE guys will take a look. Thanks.

**Comment by vparfonov** [comment]
@davidwindell temporary fix here https://github.com/eclipse/che/pull/6142 and soon we will start work on https://github.com/eclipse/che/issues/6143
