### ISSUE TITLE
It's impossible to import SVN-project in Multiuser Che

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6127]
**Reproduction Steps:**
1. Create and open workpace.
1. Open **Import Project** wizard.

**Expected result:**
There is **SUBVERSION** item in _Source Control_ list:
![screenshot from 2017-09-04 17 13 17](https://user-images.githubusercontent.com/1197777/30030244-1cb5a276-9195-11e7-9525-ed4e597d1423.png)

**Actual wrong result:**
There is no **SUBVERSION** item in _Source Control_ list:
![screenshot from 2017-09-04 17 13 35](https://user-images.githubusercontent.com/1197777/30030248-20d57ebc-9195-11e7-87c3-4c5311ad408a.png)

This issue is related to #5362.

**Comment by ghost** [comment]
@skabashnyuk haven't we agreed to discontinue svn support for Che 6 at least? So, this might be just expected behavior.

**Comment by skabashnyuk** [comment]
Not sure this is the case. I've asked @SkorikSergey @Ohrimenko1988  to check this usecase once again and give more information. Like master logs, http log etc.

**Comment by dmytro-ndp** [comment]
@skabashnyuk: there is response from **project-importer** service on screenshots where _subversion_ is not in the list.
Why do you need additional logs? Do you have a problem with reproducing this bug locally?

**Comment by gazarenkov** [comment]
If I remember well it was decided at some point to remove SVN from default assembly, no?

**Comment by SkorikSergey** [comment]
Not reproduced in Che 6.0.0-M5.
