### ISSUE TITLE
Swagger is inaccessible in Multiuser Che

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6128]
**Reproduction Steps:**
Login into the Multiuser Che and go to the _Swagger_ page http://172.17.0.1:8080/swagger

**Expected result:**
page with _Swagger_ UI is opened in browser:
![swagger](https://user-images.githubusercontent.com/1197777/30030615-cf59f6e2-9196-11e7-82d4-33e3868b17cd.png)

**Actual wrong result:**
There was redirection to http://172.17.0.1:8080/dashboard/#/ page:
![out](https://user-images.githubusercontent.com/1197777/30030845-acda79ce-9197-11e7-9436-54430fa4ffdb.gif)

This issue is related to #5362.

**Comment by skabashnyuk** [comment]
Duplicate https://github.com/eclipse/che/issues/6015
