### ISSUE TITLE
Upgrade to the GWT 2.8.1

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#6129]
http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_1

**Comment by vparfonov** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14117

**Comment by bmicklea** [comment]
So, this is waiting on Eclipse to verify the CQ?

**Comment by vparfonov** [comment]
yes

**Comment by azatsarynnyy** [comment]
All necessary changes have been prepared in the following branches:
- [che-parent#gwt-plugin](https://github.com/eclipse/che-parent/tree/gwt-plugin)
- [che-dependencies#gwt-2.8.1](https://github.com/eclipse/che-dependencies/tree/gwt-2.8.1)
- [che#gwt-maven-plugin-migration](https://github.com/eclipse/che/tree/gwt-maven-plugin-migration)

**Comment by azatsarynnyy** [comment]
Upgrade has been done for Che 6. For more details on this, see the following commits:
* https://github.com/eclipse/che-parent/commit/847d3c57e92decd529402895739808ada7bb8329
* https://github.com/eclipse/che-dependencies/commit/01c0c0bb08c344ef0d9f987237fe5921b8c3f3c6
* https://github.com/eclipse/che/pull/6822
