### ISSUE TITLE
Is there an easy way to change the log level of the tomcat in the che docker container?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#613]
I want to show more `debug` level log when che is running, how can I do it if I start che with docker:

```
docker run -ti --net=host 
    -v /var/run/docker.sock:/var/run/docker.sock 
    -v /home/user/che/lib:/home/user/che/lib-copy 
    -v /home/user/che/workspaces:/home/user/che/workspaces 
    -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage 
    -e CHE_DOCKER_MACHINE_HOST=198.199.105.97 
    codenvy/che:nightly
```

If I didn't understand mistakely, it is defined in the file `/home/user/che/tomcat/conf/logback.xml` of a docker container. I can change the log level to `debug` in it, but how can I make it affect? 

I tried to run `che.sh stop`, but the container exits immediately without having a chance to restart it.

Or is there any easier way to do it?

**Comment by garagatyi** [comment]
You understand it correctly. Correct path to logging conf is `/home/user/che/tomcat/conf/logback.xml`.
+1 for that issue. Sometimes I find myself thinking about that feature. + configure the same for wsagent.

**Comment by freewind** [comment]
@garagatyi Thanks for correcting the file name :+1: It is useful when debugging some strange bugs

**Comment by ghost** [comment]
Well, you may override the default CMD with your own and use `sed` to replace info with debug.

Here's the default CMD - https://github.com/eclipse/che/blob/master/Dockerfile#L27

**Comment by freewind** [comment]
@eivantsov Yes, that is a good method, thanks! 

I just have another method: 

Prepare the logback file in local file system, and modify its content:

```
wget https://raw.githubusercontent.com/eclipse/che-lib/master/che-tomcat8-slf4j-logback/src/assembly/conf/logback.xml
```

Then when starting che with docker, add this mounting:

```
-v path/to/logback.xml:/home/user/che/tomcat/conf/logback.xml
```

**Comment by freewind** [comment]
There is another related question: How to modify the conf file which runs in workspace machine? 

There will be a `ws-agent.zip` injected to workspace machine, which contains the tomcat and the `logback.xml`. But seems it's not easy to modify it

**Comment by garagatyi** [comment]
I think it should be modified by env variable. In that case you don't need to modify zip.

**Comment by ghost** [comment]
@freewind we have registered a JIRA issue. It'll be taken in the coming sprint.

**Comment by TylerJewell** [comment]
This was resolved in previous releases. Closing issue.
