### ISSUE TITLE
Allowed workspace name length should be up to 100 chars (currently only 20 is allowed)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#6130]
Related osio issue - https://github.com/openshiftio/openshift.io/issues/446
On osio there is a requirement with prefixing workspace name with github repository name. Currently, workspace name is validated against the following pattern: `"[a-zA-Z0-9][-_.a-zA-Z0-9]{1,18}[a-zA-Z0-9]"` which allows names up to 20 chars and GitHub repo name length can be up to 100 chars. So, with current validation it would not be possible to create workspaces with names based on github repos

**Comment by ghost** [comment]
@skabashnyuk @ashumilova that's perhaps for you guys i think both API and UD client limit it.
