### ISSUE TITLE
Improve rh-che CI job

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#6138]
@riuvshin has recently [created a CI job](https://ci.codenvycorp.com/job/rh-che-ci-master) to verify rh-che build against eclipe/che master branch `HEAD`. Here are some possible improvements:

- [x]  Build che server image `eclipse/che-server:nightly-centos-rhche` using the artifact built by rh-che build and `Dockerfile.centos` (I think that we don't need to push the image to the docker hub for now).
- [x] Start OpenShift in a [Docker container](https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container), deploy Che there and verify that Che is started and accessible - https://github.com/codenvy/infrastructure/issues/133
- [x] Run a simple test (e.g. create a new workspace using the vert.x stack and verify that terminal and wsagent services are started successfully)

**Comment by riuvshin** [comment]
[here](https://github.com/riuvshin/ocp/blob/master/ocp.sh) is a script that should cover all requirements, @l0rd if that is what you wanted please let me know :)

**Comment by l0rd** [comment]
Great @riuvshin ! The script does exactly what I was thinking. If you are ok I would like to keep this issue open until the script is going to be part of rh-che job.

**Comment by riuvshin** [comment]
@l0rd script is integrated to job, https://ci.codenvycorp.com/job/rh-che-ci-master/51/console 

each build of that will run ocp deploy and run test :)

**Comment by l0rd** [comment]
@riuvshin cool!
