### ISSUE TITLE
Why is google and facebook in the factory extension? 

### ISSUE THREAD

**Issue by bs-matil** [eclipse-che/che#6148]
Hi recently I saw facebook and google calls within che. Is there a techincal reason why facebook and google is included?
in here:
https://github.com/eclipse/che/tree/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory

**Comment by ghost** [comment]
@bsukramlitt good question :) This code is pretty ancient and odds are it may be unused.

**Comment by sr229** [comment]
Probably unused since google and FB calls are only used in OAuth in Codenvy

idk about che

**Comment by ghost** [comment]
I don't think Login with FB button has been ever seen in Codenvy :)

**Comment by ghost** [comment]
@skabashnyuk perhaps you are the one who can possible recall why we required FB scripts.
