### ISSUE TITLE
Ease implementation of new language servers

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6149]
Right now ws-agent connects to LSP servers using Java classes such as [this one](https://github.com/eclipse/che/blob/master/plugins/plugin-json/che-plugin-json-server/src/main/java/org/eclipse/che/plugin/json/languageserver/JsonLanguageServerLauncher.java#L41-L41).
This class provides [LanguageServerDescription](https://github.com/eclipse/che/blob/master/wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/registry/LanguageServerDescription.java#L35-L35) with:
- file watchers patterns
- language IDs
- LS ID
- document filters (paths regexes, schemas, etc)
And also responsible for starting LSP servers binaries, connecting to LSP of the server, checking whether certain LSP server is available.
We have the same classes for [PHP](https://github.com/eclipse/che/blob/master/plugins/plugin-php/che-plugin-php-lang-server/src/main/java/org/eclipse/che/plugin/php/languageserver/PhpLanguageServerLauncher.java#L35-L35), [Python](https://github.com/eclipse/che/blob/master/plugins/plugin-python/che-plugin-python-lang-server/src/main/java/org/eclipse/che/plugin/python/languageserver/PythonLanguageSeverLauncher.java#L29-L29), [CSharp](https://github.com/eclipse/che/blob/master/plugins/plugin-csharp/che-plugin-csharp-lang-server/src/main/java/org/eclipse/che/plugin/csharp/languageserver/CSharpLanguageServerLauncher.java#L34-L34), [TypeScript](https://github.com/eclipse/che/blob/master/plugins/plugin-web/che-plugin-web-ext-server/src/main/java/org/eclipse/che/plugin/web/typescript/TSLSLauncher.java#L30-L30).
With such an approach we need 1 Java class per LSP implementation and the addition of new LSP implementations require the addition of new Java class and recompilation of ws-agent.

Instead of this approach, we can provide some JSON file with everything needed for communication with LSP server. Then ws-agent should know some path where LSs configs are placed. It can have nested structure. Example:
```
/ls-configs/
/ls-configs/json/conf.json
/ls-configs/php/conf.json
/ls-configs/java/java.json
/ls-configs/non-lang-name/some-ls-conf.json
```
Where configuration file would have data like the following:
```
{
    "id" : ""org.eclipse.che.plugin.json.languageserver"",
    "languagesIds" : [], // IDK what it is, I haven't found usage in Che
    "fileWatchPatterns" [ // taken from tests, I haven't found usage in Che
        "glob:*.foo",
        "glob:*.bar"
    ],
    "documentFilters" : [
        {
            "pathRegex" : ".*\\.(cs|csx)",
            "languageId" : "csharp",
            "scheme" : "",
        }
    ]
}
```
Fields of this JSON are just example. One more thing that might be useful in such JSON is way how to connect to LS: 
- unix socket or tcp socket or input-output
- configuration of connection. binary path in case of launching LS and using IO; address to connect to TCP socket; path to unix socket.

As Tomas noticed it should be still possible to use Java class to provide this thing in an LS implementation specific way when something is hard coded on purpose if it can not be done in JSON configuration.

**Comment by garagatyi** [comment]
@evidolob @vparfonov @gazarenkov @tsmaeder @gorkem FYI here is an idea we discussed on F2F.
If something is not clear from the description do not hesitate to ping me for clarification.

**Comment by tsmaeder** [comment]
We would still have to provide the actual LS implementation somehow. But if we have the ```StandardLanguageServerLauncher``` at least the client side would be taken care of (no maven module, etc.)

**Comment by garagatyi** [comment]
We can have default implementation of the launcher which can be created for each config file found in certain directory. So to use LS we can add config file only into container with wsagent. And the way we added such config does not matter for wsagent. So we can play with ways of providing it separately

**Comment by benoitf** [comment]
IMHO this issue still doesn't fully "ease" the pluggability of a LSP as this issue is only discussing about the "configuration" part while we still require binaries of LSP as well. (BTW configuration is important)
For now agents are bringing the binaries and then you need to build assembly of che in order to add one agent for every workspaces.


If I talk only on this issue, json format is not so user friendly in comparison to yaml.

Also one point of the discussion was also to provide LSP binaries through a docker image (side car) and you might provide all the configuration in the docker image or through the use of docker labels.

**Comment by garagatyi** [comment]
Outdated
