### ISSUE TITLE
New workspace details page manual testing 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6153]
We need test the new workspace details page.
This issue related with https://github.com/eclipse/che/issues/5653

1. The warning message about deleting a workspace or a team is not visible. (fixed)
2. If stop a workspace by the Stop button it is always be with snapshot. (fixed)
3. The workspace name appears if hover the cursor on the Run and the Open buttons. (fixed)

**Billing:**
We have problems with billing functionality: 
Does not works rows validation in the credit card creation form, and after filling the form by valid values the "Continue" button is still disabled, so the user can not buy more RAM. (fixed)

**Teams:**
1. After creating a workspace from a team its the team status changes to personal.
2. After moving from a workspace to a team the go back button works wrong.(Can't reproduce for now because of the bug above)

**The Machines tab:**
1. The Links and the Settings links in the Machines tab don't work(there aren't tabs with this names in the workspace details). (fixed)
2. There is a problem with changing the RAM by keyboard(Up and Down keys) in the Machines tab. After pressing the Up or the Down keys the field loose focus. Similar behavior is if try to type amount of RAM - after the first digit the field loose focus.
3. New machine always adds with 2 GB RAM.(fixed)
4. There is not a possibility change **RAM** to 0.5 GB in the **Edit the Machine** dialog/ https://github.com/eclipse/che/issues/6153#issuecomment-327740203(fixed)

**The projects tab:**
1. The Open in IDE link works wrong (fixed)
2. A project settings doesn't open after clicking on its name (fixed)
3. An url doesn't change after a workspace renaming (fixed)
4. If create a new project by the **Add project** button from the **Workspaces** list there is not an error message if a project with this name exists already.https://github.com/eclipse/che/issues/6153#issuecomment-327422411 (fixed)
5. There is not a possibility to create a new project by Add project button from the Workspaces list.https://github.com/eclipse/che/issues/6153#issuecomment-327422734 (fixed)
6. If delete a project from its config then the page will redirect to the Overview tab(need the Projects tab).https://github.com/eclipse/che/issues/6153#issuecomment-327424199 (fixed)
7. After adding a new project there is not a possibility to go to its config. Need to refresh a web page. https://github.com/eclipse/che/issues/6153#issuecomment-327427479
8. If add a new project and save changes by the Save changes button is still active. https://github.com/eclipse/che/issues/6153#issuecomment-327431098 (fixed)

**The Env Variables tab:**
1. There is a difference with  a variable name in the variables list and the **Add a new environment variable** dialog(in first case its name is **"key"**, in second - **"name**"). https://github.com/eclipse/che/issues/6153#issuecomment-328017467(fixed)

**The Servers tab:**
1. The server referense does not apply names with Upper cases symbols see vide screencast:https://github.com/eclipse/che/issues/6153#issuecomment-329117960

**The Agents tab:**
1. Unexpected reset of C# agent slider on Agent tab:https://github.com/eclipse/che/issues/6153#issuecomment-329114422.

**Comment by SkorikSergey** [comment]
If create a new project by the **Add project** button from the **Workspaces** list there is not an error message if a project with this name exists already.
![teams-29](https://user-images.githubusercontent.com/7760565/30103494-7dfd9c5c-92fb-11e7-8d8f-c2b43a99022b.gif)

**Comment by SkorikSergey** [comment]
There is not a possibility to create a new project by **Add project** button from the **Workspaces** list.
![teams-2 1](https://user-images.githubusercontent.com/7760565/30103564-b230d2aa-92fb-11e7-9443-9c11633db799.gif)

**Comment by SkorikSergey** [comment]
If delete a project from its config then the page will redirect to the **Overview** tab(need the **Projects** tab).
![teams-1 1](https://user-images.githubusercontent.com/7760565/30103829-80188d5c-92fc-11e7-92a3-68134cd1d301.gif)

**Comment by SkorikSergey** [comment]
After adding a new project there is not a possibility to go to its config. Need to refresh a web page.
![teams-3 1](https://user-images.githubusercontent.com/7760565/30104436-465c1564-92fe-11e7-85c2-3a159e7e5987.gif)

**Comment by SkorikSergey** [comment]
If add a new project and save changes by the **Save** changes button is still active.
![teams-7 1](https://user-images.githubusercontent.com/7760565/30105101-38825ac8-9300-11e7-901b-80f61bf2f2fc.gif)

**Comment by SkorikSergey** [comment]
There is not a possibility change **RAM** to 0.5 GB in the **Edit the Machine** dialog
![teams-8 1](https://user-images.githubusercontent.com/7760565/30155388-5879d67e-93c5-11e7-9ec7-0c29db352fdb.gif)

**Comment by SkorikSergey** [comment]
There is a difference with  a variable name in the variables list and the **Add a new environment variable** dialog(in first case its name is **"key"**, in second - **"name"**). 
![screenshot from 2017-09-07 12-19-22](https://user-images.githubusercontent.com/7760565/30199674-69bc09c2-947c-11e7-9310-7125b2faa8ea.png)

**Comment by musienko-maxim** [comment]
Unexpected reset of C# agent slider on Agent tab:
steps to reproduce:
* create a workspace based on java + MySQL stack 
* go to the Agents tab and enable C# LSP by slider
The slider unexpected to disable status it some confuses

**Comment by musienko-maxim** [comment]
The server referense does not apply names with Upper cases symbols see vide screencast:
![out](https://user-images.githubusercontent.com/1640058/30371160-58e93390-9882-11e7-89a5-73573e973ef7.gif)
