### ISSUE TITLE
Can not move java package in the another java package 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6154]
**Reproduction Steps:**
- Run default java stack with default spring project
- In the "java" folder create java package (for example "newPackage")
- Click on new created package and press "F6" button on the keyboard
- In the opened "Move item" form click on expand button of "web-java-spring" -> "/src/main/java"
- Pay attention to the error message

**OS and version:**    
CHE 5.18.0 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![eclipse che wksp rbsb](https://user-images.githubusercontent.com/22724619/30105435-402c80d6-9301-11e7-9689-e2003eb604a4.png)

**Comment by gazarenkov** [comment]
@Ohrimenko1988 still actual?

**Comment by Ohrimenko1988** [comment]
@gazarenkov Yes, it is actual for current 6.5.0 Che version
