### ISSUE TITLE
New workspace details page manual testing

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6155]
We need to cover new workspace details page by manual testing. All feedbacks will be attached with this issue.
The new stuff can be found on https://a2.codenvy-stg.com.

* [x] The warning message about deleting a workspace or a team is not visible. 
* [x] If stop a workspace by the Stop button it is always be with snapshot. 
* [ ] The workspace name appears if hover the cursor on the Run and the Open buttons 

Teams:
* [ ] After refreshing web page the team status of a workspace changes to personal. 
* [ ] After moving from a workspace to a team the go back button works wrong. 
* [ ] For team's workspaces there is not the "Buy more RAM to get 5 hour idle timeout" button. 

The Machines tab:
* [x] The Links and the Settings links in the Machines tab don't work(there aren't tabs with this names in the workspace details). 
* [ ] There is a problem with changing the RAM by keyboard(Up and Down keys) in the Machines tab. After pressing the Up or the Down keys the field loose focus. Similar behavior is if try to type amount of RAM - after the first digit the field loose focus. 
* [ ] New machine always adds with 2 GB RAM.

The projects tab:
* [x] The Open in IDE link works wrong 
* [x] A project settings doesn't open after clicking on its name 
* [x] An url doesn't change after a workspace renaming 

(it is copy of https://github.com/codenvy-legacy/qa/issues/1115)

**Comment by SkorikSergey** [comment]
New issue about workspace details page manual testing is there: https://github.com/eclipse/che/issues/6153.
