### ISSUE TITLE
Presentation mode

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#6187]
It would be great to have a presentation mode [similar to IntelliJ's](https://www.jetbrains.com/help/idea/intellij-idea-viewing-modes.html). Because the terminal and command panel are pretty key for Che I think we'd handle it a little differently by having two presentation modes - with and without terminal / command panel:

### Requirements
- Assign a hotkey to get in/out of this mode
- Hide the left nav
- Hide project explorer
- Hide the toolbar, leave top menu and tabs
- Collapse terminal and command panel so it's 5 terminal lines tall
- Increase font size for editor and terminal / command output (configurable by the user through their preferences)
- Shrink terminal/command/info panel at the bottom of the window to 5 terminal lines tall
- Button/turner to hide/bring back the terminal (already possible)

**Comment by yanaga** [comment]
It's a must for promotion on developer's conferences: live coding with a presentation mode rocks!

**Comment by slemeur** [comment]
@yanaga : Thanks for the feedback. Do you run live coding usually with a light or a dark theme? 

@bmicklea I think that should be an epic, as there is probably other few things to consider like:
- Abilty to define a keyboard shortcut to activate the presentation mode
- Ability to configure the presentation mode (which panels, which theme, font size)

**Comment by yanaga** [comment]
@slemeur I prefer the light background. Dark background is harder to see depending on which room you are.

**Comment by bmicklea** [comment]
@l0rd I think this remains an important feature. But now that we're using Theia I expect that it can come from there. I've filed a mirror issue in Theia: https://github.com/eclipse-theia/theia/issues/7850

If Che needs to do something different than Theia then let's leave this open and discuss when we can fit it into a release. If it's going to be covered by the Theia issue then we can close this issue with a reference to that.

**Comment by l0rd** [comment]
@bmicklea makes sense

**Comment by bmicklea** [comment]
This Theia issue discusses how to address this presentation need now that Che is using the Theia IDE. It's not 100% perfect, but it should be good enough for most situations.

https://github.com/eclipse-theia/theia/issues/7850
