### ISSUE TITLE
Runtime Exception `Message: Can't find IClasspathEntry`

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#6204]
```
[STDOUT] 2017-09-10 08:07:27,430[equestProcessor]  [ERROR] [oggingUncaughtExceptionHandler 31]   - Runtime exception caught in thread ServerSideRequestProcessor. Message: Can't find IClasspathEntry for path /che/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java
[STDOUT] java.lang.RuntimeException: Can't find IClasspathEntry for path /che/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.getRuntimeException(AbstractJavaTestRunner.java:257)
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.findCompilationUnitByPath(AbstractJavaTestRunner.java:191)
[STDOUT] 	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.detectTests(AbstractJavaTestRunner.java:80)
[STDOUT] 	at org.eclipse.che.api.testing.server.TestingRPCService.handleTestDetection(TestingRPCService.java:95)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:328)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:315)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:212)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:51)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:97)
[STDOUT] 	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:72)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
```

**Reproduction Steps:**

* Import https://github.com/eclipse/che.git
* Edit FileWatcherService.java
* Watch dev-machine console.

**OS and version:**    

Container Linux by CoreOS 1520.1.0 (Ladybug)

Che's version

Version :5.18.0-SNAPSHOT
Revision :5231059555dc1838
Build Time :2017-09-08 13:45:52

**Comment by bmicklea** [comment]
@monaka does the workspace start properly for you? Or is this a fatal error?

**Comment by monaka** [comment]
I got some fatal errors already reported. So I can't determine now if this is a fatal error or not. 
At least it's not fancy that RuntimeException was logged. ;)

**Comment by bmicklea** [comment]
@eivantsov, can you investigate?

**Comment by ghost** [comment]
@dkuleshov any thought on what may have caused this?

**Comment by dkulieshov** [comment]
Hi,
@monaka thanks for the report

> @dkuleshov any thought on what may have caused this?

@eivantsov as of what I see - not really :smile: I mean if you could take a bit of your time to analyze stack trace you would see that actually it is not likely to be related neither to Json RPC nor to file watcher service, as it might have seemed to be the case at first glance.

I think that the main issue here is more about `TestRunner` implementation. To the best of my understanding I would say that test runner at some point of its execution can't properly find class path entry for a class `FileWatcherService` [here,](https://github.com/eclipse/che/blob/514913d5d14b4d9a01bbbdd290623590d4577a78/plugins/plugin-testing-java/plugin-testing-classpath/src/main/java/org/eclipse/che/plugin/java/testing/AbstractJavaTestRunner.java#L193) which is indicated by this line: `java.lang.RuntimeException: Can't find IClasspathEntry for path /che/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java` in a stack trace. In general it can be any java class, not `FileWatcherService` specifically. However I have no idea why it happens :smile: So I think we should first ask @svor (as a test runner expert) if he could clarify this incident for us.

**Comment by dkulieshov** [comment]
> @monaka does the workspace start properly for you? Or is this a fatal error?

@bmicklea I think this is not related to workspace start, workspace probably starts properly. According to the description it is about errors during java class modifications using IDE editor, so this is not looking to be a fatal error.

**Comment by ghost** [comment]
I think @svor has either fixed it or is fixing it now

**Comment by svor** [comment]
Hi @monaka! I think this problem has already been fixed. Can you reproduce it again?

**Comment by ghost** [comment]
Closing as fixed.
