### ISSUE TITLE
[SPI branch] Auto snapshot does not work

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6213]
**Reproduction Steps:**
* Open a workspace in the IDE
* Create a file in the terminal
* Restart the workspace from Menu

**Expected behavior:**
* Auto snapshot does not work when to perform restart 

**Observed behavior:**
* Auto snaphot should work like in the  master branch

**Che version:** 5.18.0
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by gazarenkov** [comment]
I think we need to revise "snapshotting" policy
- It looks quite like an anti-pattern for container world 
- adds quite a lot for infrastructure price
- and quite expensive to support already

**Comment by gorkem** [comment]
@gazarenkov any suggestions for a policy?

**Comment by gazarenkov** [comment]
@gorkem 
Sure, a couple:
Optimal - remove snapshotting  at all.
Minimal - remove it as a default option.
as soon as possible

**Comment by gorkem** [comment]
@slemeur @bmicklea I think removing this sort of snapshotting going forward makes more sense. I think we are targeting immutable workspaces possibly through sidecars in the future. 

Also I am not sure if we can support this on OS.

**Comment by bmicklea** [comment]
Conceptually I agree, but snapshotting was created because of a real world issue that affected most Codenvy users. While git is good for tracking and saving project state between uses, there isn't a similar mechanism for handling runtime state changes.

For a local Che without workspace idling this isn't a big deal because the user takes a positive action to stop the workspace and (usually) understands what that means for the container runtime state changes.

For a SaaS offering (public or private) where workspace idling occurs it becomes somewhat common for a user's runtime to be powered down and runtime state lost without warning. This is deeply frustrating and sometimes catastrophic to a user's work. Snapshotting was created (and made default) to solve this problem.

Is there another solution to this that OpenShift provides us?

**Comment by garagatyi** [comment]
I don't know any way to implement snapshotting on OpenShift. And since snapshotting is containers world antipattern it is understandable.

**Comment by ghost** [comment]
yeah, implementing snapshotting for OpenShift won't be easy but i think still doable. Not sure it makes any sense for OpenShift and its philosophy.

**Comment by garagatyi** [comment]
Can you elaborate on how we can implement it?

**Comment by ghost** [comment]
Sorry, I was thinking about s2i.

Yes, snapshotting in OpenShift is never an option.

**Comment by bmicklea** [comment]
I think we're agreed that snspshotting is tricky/won't work in OpenShift. So what options do we have for not just deleting customer data when we idle a workspace?  Or are you suggesting we don't idle workspaces in OpenShift?

**Comment by gazarenkov** [comment]
@bmicklea 
If we all agree conceptually and so see it as the only future for containerized env, why we encourage  the things we consider as a bad practice?
The more time we do it, the more painful transition for users in future.

Idle does not matter if workspace is immutable,  i.e:  "want persisted env changes? change configuration, not runtime (only)"

**Comment by bmicklea** [comment]
If I'm developing a database app or a machine learning algorithm/model I (or my app) will make changes to my runtime that won't be persisted in git.  These are the situations I'm most concerned about.

People who get a node stack and change deps manually should know (and have the opportunity to) codify those changes in the stack definition. I don't see how someone can do the same for a dataset change brought on by running a recently changed ML algorithm or database change executed as a result of a git committed code change.

**Comment by garagatyi** [comment]
We have projects folder for that. We might have another volume for syncing user's data. But syncing whole container runtime is heck as expensive and hard for OpenShift. 
I think that users won't love OpenShift implementation if it removes Docker's implementation feature as snapshotting. Do we want such an effect for OpenShift implementation?

**Comment by gazarenkov** [comment]
@bmicklea it is different thing
persisted storage is decoupled from containers' file system
So yes, what you mentioned is definitely possible but you have to store your sensitive data in mounted volume (or use some, non-standard/custom data syncing mechanism), 
files written "anywhere" wont to be saved for next container launch.

**Comment by bmicklea** [comment]
If it's stored in projects it'll be committed with git, right? I'm not sure
that people will want that for things like models and data.

Otherwise I can see your point Gennady about either setting up PVs or
attaching to a pod that doesn't get idled automatically. If this last
option is possible then we'd have to enable that in the UI somehow wouldn't
we?
-- 

Brad Micklea // Developer Products // 416.707.0792

**Comment by gorkem** [comment]
Storing on projects does not mean it will be committed to git. It can be ignored by the developer. I think developer needs to decide if it is something that can be shared or not.

**Comment by bmicklea** [comment]
But if they want it persisted and it's in /projects it would be somewhat
complicated to persist it anywhere other than git, no?

**Comment by gorkem** [comment]
If it is saved in /projects but not added to git the data is still persistent and is not lost when workspace is idled and revived. Adding them to git allows the data to be shared among developers, hence workspaces.

**Comment by bmicklea** [comment]
Thanks @gorkem that makes it clearer for me. So our statements to users would be:
1) Containers are (by definition) immutable and should be treated that way even by developers
2) Git is the primary mechanism through with changes in the container code are stored and shared.
3) Any state information that needs to be persisted between container executions should be saved to `/projects` (adding to git is only required if you need to share this information with your team); or persisted to a PV.

**Comment by garagatyi** [comment]
@bmicklea looks good!

**Comment by bmicklea** [comment]
Great, please make sure that there's a Che Docs PR to match the code PR so we can include this info.

**Comment by gazarenkov** [comment]
Back to the issue - I think we should close it as wont fix

**Comment by bmicklea** [comment]
+1

**Comment by garagatyi** [comment]
As snapshotting is not possible on OpenShift infra and is an antipattern in containers world where containers are immutable we won't restore this functionality in SPI branch.
