### ISSUE TITLE
[CHE6 branch] Macros for creating preview URL is not exist

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6215]
**Reproduction Steps:**
- Run java stack with default spring project
- Open commands explorer and click twice to the "build and run" command
- Wait until project will be started 
- Click on the preview link in the terminal or "preview" button on the toolbar -> preview link
- Pay attention that link is incorrect and correct macros is not exist

**Expected behavior:**
Preview link will be valid

**Observed behavior:**
Preview link is not valid and macros for creating valid link is not exist

**OS and version:**    
Che 5.18.0 ; Chrome 59.0 ; Fedora 25 

**Additional information:**
* Related selenium test:
 

1. _WorkingWithJavaMySqlStackTest_
2. _CheckIntelligenceCommandFromToolbarTest_
3. _MacrosCommandsEditorTest_
4. _WorkingWithNodeWsTest_
5. _PhpProjectDebuggingTest_

**Comment by SkorikSergey** [comment]
Preview link is not valid:
![screenshot from 2017-09-29 16-47-35](https://user-images.githubusercontent.com/7760565/31018871-482d36e4-a536-11e7-8b70-3f18e4c946ff.png)

![screenshot from 2017-09-29 16-47-21](https://user-images.githubusercontent.com/7760565/31018878-4edac182-a536-11e7-9b98-aa1d978eb128.png)

**Comment by ghost** [comment]
Preview URLs here need to be revisited https://github.com/eclipse/che/blob/che6/ide/che-core-ide-templates/src/main/resources/samples.json
