### ISSUE TITLE
Changes to files not being reflected in IDE

### ISSUE THREAD

**Issue by vseager** [eclipse-che/che#6228]
Files which are open in the workspace are not updated in IDE when updated on the file system.

**Reproduction Steps:**
* Open file and edit in IDE
* Save file
* `git reset --hard HEAD`

**Expected result**
* File should appear in IDE as it was in the last commit

**Actual result**
* File remains the same
* Close file, and reopen required to update file in IDE

**OS and version:**    
* Ubuntu
* Che 5.17
* Google Chrome

**Comment by slemeur** [comment]
@vinokurig  + @RomanNikitenko : Any idea on this one?

**Comment by davidwindell** [comment]
I think this used to work at some point so perhaps the watcher is broken?

**Comment by RomanNikitenko** [comment]
I can not reproduce it on current version, but I'm going to check out on 5.17.

![gitreset](https://user-images.githubusercontent.com/5676062/30415135-549d5f7a-992f-11e7-929d-bf59d466a13e.gif)

**Comment by davidwindell** [comment]
@RomanNikitenko try turning auto save off

**Comment by RomanNikitenko** [comment]
I can not reproduce it on 5.17 too. Could you provide some details to help reproduce it?
Or may be your project/folder/file is added to file watcher excludes by 'Add to File Watcher excludes' action?
![gitreset_5_17](https://user-images.githubusercontent.com/5676062/30415668-bccdbf7a-9931-11e7-8b39-7ef746ee5fbd.gif)

**Comment by RomanNikitenko** [comment]
@davidwindell thank you, I will try!

**Comment by RomanNikitenko** [comment]
I can reproduce it only for case when we have nothing to reset on file system.
But when we have something to reset - it works correctly.
Please see video.
![gitresetautosaveturnedoff](https://user-images.githubusercontent.com/5676062/30416712-e96df4ce-9935-11e7-9d8f-cbc9205888bd.gif)

**Comment by davidwindell** [comment]
I'm seeing the opposite, even after saving it doesn't refresh. I'll try and see if I can find out what differs. @vseager any idea?

In the case above (although a different issue), in Netbeans we would see a message `File modified externally, do you want to reload it?`, can Che have similar to avoid risking overwrite?

**Comment by vseager** [comment]
I have tried again and can consistently reproduce the issue every time. Auto save is disabled.

**Comment by RomanNikitenko** [comment]
@davidwindell about external changes and unsaved data - I've created [issue](https://github.com/eclipse/che/issues/6271) - thank you!

**Comment by RomanNikitenko** [comment]
I still can not reproduce it neither for 5.17.0 version nor for current 5.19.0. 
On my side it's reproduced only for cases: 
 - we have nothing to reset on file system (content of a file was not saved);
- Item (project/folder/file) was added to file watcher excludes (to check it - go projectName/.che/fileWatcherIgnore);

Could someone provide some details to help reproduce it?

**Comment by davidwindell** [comment]
@RomanNikitenko I can 100% reproduce this on every file in Che 5.18, there is nothing in the fileWatcherIgnore list.

Would it help if you had access to a test workspace?

**Comment by davidwindell** [comment]
This has been fixed in Che 5.19 for us.

**Comment by RomanNikitenko** [comment]
@davidwindell Thank you for the update.

**Comment by RomanNikitenko** [comment]
@vseager Could you inform - do you still have this issue? Is it fixed for you  in Che 5.19?

**Comment by vseager** [comment]
@RomanNikitenko I've just tested again (Che v5.20), the issue now only seems to be when I don't save the file:

**Reproduction Steps:**

* Open file and edit in IDE
* DON'T Save file
* git reset --hard HEAD

**Expected result**

File should appear in IDE as it was in the last commit
Actual result

**File remains the same**
Close file, and reopen required to update file in IDE

**Comment by RomanNikitenko** [comment]
@vseager thank you for your response!
I guess there is nothing to reset in your case: content of a file was not saved.
What result of command 'git status' before 'git reset --hard HEAD'?
Does it match the first case  on the video [here](https://github.com/eclipse/che/issues/6228#issuecomment-329395477)?
So:
- Open file and edit in IDE
- DON'T Save file
- git status -          result   ====>   nothing to commit, working tree clean
- git reset --hard HEAD   ====>    File remains the same - it's expected - there is nothing to reset on file system

**Comment by RomanNikitenko** [comment]
So I'm closing the issue, feel free to reopen it when you have another use case
