### ISSUE TITLE
Cursor is set up to the next line after using autocomplete feature in the C# files

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6229]
**Reproduction Steps:**
- Run C# stack with default project
- Open any C# file until C# languageserver will be started
- Delete the part of any method and use "Ctrl + Space" 
- Pay attention to the cursor location

**Expected behavior:**
The cursor is located at the end of the row where autocomplete was launched

**Observed behavior:**
The cursor is located at the next row 

**OS and version:**    
Che 5.18.0 ; Chrome 59.0 ; Fedora 25

**Comment by musienko-maxim** [comment]
Cannot reproduce che6
