### ISSUE TITLE
Clean up svn-server containers after termination of test execution

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6234]
There is **svn-server** container could remain after termination of tests execution, and they stay after restarting of docker:
![screenshot from 2017-07-31 14 20 52](https://user-images.githubusercontent.com/1197777/28835898-a17b4a62-76ef-11e7-9e8c-d5415fea7728.png)

We need to remove odd **svn-server** containers in time of termination.

**Comment by skabashnyuk** [comment]
Please do not hurry with this issue. We are working on some sort of depreciation of svn plugin https://github.com/eclipse/che/issues/5484

**Comment by dmytro-ndp** [comment]
The issue is outdated so as SVN plugin actually isn't supported by default.
