### ISSUE TITLE
[CHE6 branch] Pull Request plugin does not work

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6237]
**Reproduction Steps:**
* Import a project (e.g.https://github.com/artaleks9/pull-request-plugin-test.git)
* Open the 'README' file and change it

**Expected behavior:**
* Should be showed 'Pull Request' tab on the right panel

**Observed behavior:**
* The 'Pull Request' tab is not displayed on the right panel

**Che version:** 5.18.0
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Related selenium test: _PullRequestPluginTest_, _PullRequestPluginWithForkTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by tolusha** [comment]
PullRequest panel is not opened.
