### ISSUE TITLE
Don't create redundant default workspace at start of test

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6238]
Selenium tests creates test workspace through REST API by default by invoking [TestWorkspaceProviderImpl.initializePool()](https://github.com/eclipse/che/blob/master/selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/workspace/TestWorkspaceProviderImpl.java#L141) method at start.

But there are situations exist when default test workspace in the pool is redundant:
1. In tests which use dedicated workspace with non-default parameters, for example org.eclipse.che.selenium.languageserver.**CheckMainFeatureForLanguageTest**;
1. In tests which create test workspace in test methods by using factory, for example org.eclipse.che.selenium.factory.**DirectUrlFactoryWithSpecificBranch**
1. In tests which create test workspace in test methods through Dashboard UI, for example org.eclipse.che.selenium.dashboard.stacks.**CheckLaravelStackTest**

In some cases we have too little resources to run even two workspaces of 3 GB size, for example, on codenvy.io or in OCP (in issue https://github.com/eclipse/che/issues/6475). As a result, tests fail because it's impossible to run just single workspace.

Fix selenium tests to recognize such situation in some way and don't create default workspace at start of those tests at all.

**Comment by riuvshin** [comment]
set as blocker because this blocks running tests on OCP where we can run only 1 ws
