### ISSUE TITLE
Create selenium test for checking text selection and a copy-paste functions in console

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6239]
We need create selenium test for checking next functions in console:

1. Text selection
2. Copy-paste text

**Comment by SkorikSergey** [comment]
If selenium test started in **-Mgrid** mode it cannot work with clipboard by Ctr+c/Ctrl+v buttons.We need to resolve this problem.

**Comment by rhopp** [comment]
Not relevant anymore. Closing.
