### ISSUE TITLE
Nightly docker image issue: can't open the created project

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#624]
The command to run che:

```
docker run -ti --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage -e CHE_DOCKER_MACHINE_HOST=198.199.105.97 codenvy/che:nightly
```

And created a java project successfully:

![create-successful](http://snag.gy/hzPdM.jpg)

But when click on "OPEN PROJECT IN IDE", it will show such a dialog:

![dialog](http://snag.gy/Vrhd3.jpg)

If click on the "Create" button, it will show an tip says the workspace is already existed

**Comment by apovtx** [comment]
Have you tried clearing browser cache? I had a similar problem and trying with incognito fixed it.

**Comment by freewind** [comment]
@apovtx Thank, incognito fixes it :+1:
