### ISSUE TITLE
Create selenium tests for checking outputs from machines

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6240]
On this moment we don't have special test cases for testing outputs from machines. 
We've had many problems for 5.8.0 version because this functionality didn't tested properly. 
We found some bugs in context others auto tests but we need of documentations or specifications for creating test cases that will test only the outputs.

**Comment by gazarenkov** [comment]
Please be more precise, what exactly you want to test here

**Comment by dmytro-ndp** [comment]
In fact, this duplicates https://github.com/eclipse/che/issues/6242
So, I should close it.
