### ISSUE TITLE
Create test for checking project commands starting from the Processes area

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6241]
We need create test for checking projects commands starting from the _Processes_ area.

**Comment by gazarenkov** [comment]
Could you be more precise defining the task please.

**Comment by SkorikSergey** [comment]
We need check starting commands from machine names in the Processes area by context menu.
![teams-11 1](https://user-images.githubusercontent.com/7760565/30366435-ad1dc2b4-9873-11e7-841e-d97667d49aef.gif)
