### ISSUE TITLE
Create selenium test for check interactions between machine processes

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6242]
Create selenium test which covers https://github.com/eclipse/che/issues/4786 issue.

**Comment by gazarenkov** [comment]
Why we need that?
https://github.com/eclipse/che/issues/4786 CLOSED

**Comment by dmytro-ndp** [comment]
We need to create such test to cover use case described in issue #4786 to ensure that functionality works properly without bugs on regular base.

**Comment by rhopp** [comment]
Does not look relevant anymore. Closing.
