### ISSUE TITLE
Workspace details stabilization in spi branch

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#6244]
After workspace details are merged to master, the spi branch should have this changes too. The merge may cause destabilization of workspace details stuff in spi branch, and the goal of the issue - to fix that.
- [x] pay attention to machine's servers management (that part changed)
- [x] check events channels work through json rpc properly: environment status and environment output, workspace's status
- [x] "agents" were renamed to "installers"
- [x]  check open in IDE link
- [x] dashboard tests fail for agent's services

**Comment by SkorikSergey** [comment]
Project is created without default commands https://github.com/eclipse/che/issues/6198.

**Comment by SkorikSergey** [comment]
The **Add Developer** button in workspace details doesn't work.
![teams-11-18](https://user-images.githubusercontent.com/7760565/31129020-156f5e84-a85c-11e7-80ca-902080474d0b.gif)

**Comment by SkorikSergey** [comment]
There is an error notification after entering to workspace details.
![teams-11-17](https://user-images.githubusercontent.com/7760565/31129102-47fe8c9e-a85c-11e7-8e7c-a5e4ed30ddef.gif)

**Comment by olexii4** [comment]
cannot reproduce
