### ISSUE TITLE
Project import fails with 'Not a git repository' error

### ISSUE THREAD

**Issue by bbijelic** [eclipse-che/che#6249]
Hi,

when trying to import git project from private repository on 5.17.0 release, fails with error message 'Not a git repository'. Please note that import of the same project with exact same steps works on 5.16.0 and earlier releases.

Cloning project from terminal works OK, project appears in `Project Explorer` but is unusable and can not be expanded. 

Chrome Console:
[Chrome_Console_Errors.txt](https://github.com/eclipse/che/files/1298894/Chrome_Console_Errors.txt)

From logs above, request to: `http://172.16.0.3:32806/api/project/tree/ra?depth=1&includeFiles=true` results with `{"message":"Not a git repository"}`

**Reproduction Steps:**
Go to `Workspace > Import Project...`
Under `Source Control` select `GIT`
Input repository URL
Proceed with 'Import' button

On `Project Configuration` dialog:
Select `Maven` and proceed with `Save` button

**OS and version:** 
OS: Linux CentOS 7.3 on VirtualBox VM
Eclipse Che: 5.17.0 

**Diagnostics:** 
```
INFO: (che cli): 5.17.0 - using docker 17.06.2-ce / native

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:5.17.0
 Version:        5.17.0
 Command:        info
 Parameters:     info
Mounts:
 /data:          /home/vagrant/che
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      not set
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.17.0
 CHE_HOST:       172.16.0.3
 CHE_INSTANCE:   /home/vagrant/che/instance
 CHE_CONFIG:     /home/vagrant/che
 CHE_BACKUP:     /home/vagrant/che/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   10.0.2.15
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.17.0
 IMAGE_CHE=eclipse/che-server:5.17.0
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc3
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.17.0
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.17.0
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.17.0
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.17.0
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.17.0
che.env:
 CHE_HOST=172.16.0.3
 CHE_SINGLE_PORT=false
```
**Screenshot:**
![Not a git repository](https://image.ibb.co/dimz1v/not_a_git_repository.png)

**Comment by ghost** [comment]
@bbijelic what stack do you use?

**Comment by ghost** [comment]
So, in your custom recipe add:

`WORKDIR /projects`

This bug is fixed in master, so you may try nightly image.

**Comment by ghost** [comment]
Closing as fixed.

**Comment by sanjaysingatalur** [comment]
Hi I am using latest che-server but i am unable to import any projects to my CHE IDE,It fails with unable to import error.

**Comment by eivantsov** [comment]
@sanjaysingatalur it will help if you share more details

**Comment by sanjaysingatalur** [comment]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/34025569/37585858-7b5041ee-2b80-11e8-86dc-7557f272b093.png">

**Comment by sanjaysingatalur** [comment]
when i click on import project it says import failed ..thats it.
I might be doing it in a wronf away,can you please through some light on how to import a new project from github?

**Comment by eivantsov** [comment]
You have shared a screenshot with an empty import wizard which means the IDE cannot connect to a workspace agent. Most likely, the ephemeral port range is filtered

**Comment by sanjaysingatalur** [comment]
ok but what is the solution for this?

**Comment by eivantsov** [comment]
Open the ephemeral port range?

**Comment by sanjaysingatalur** [comment]
Thanks..I have opened them ,now i am able to upload a github repo via zip file onto Che .however, i am not able to push the changes back to github after committing. its throwing error.
Note: I have created public key and put the same into my github.

**Comment by sanjaysingatalur** [comment]
till now i have used https..is there any preference in this?

**Comment by eivantsov** [comment]
If you are using ssh key, your remote should be ssh@

**Comment by sanjaysingatalur** [comment]
ok part from this is any other configuration that need to be taken care?
like i have generated ssh key from che and copied it to GIt.Like this if there are any other configurations?

**Comment by eivantsov** [comment]
You may setup GitHub oAuth and push to http will work - https://www.eclipse.org/che/docs/6/che/docs/version-control.html

**Comment by sanjaysingatalur** [comment]
thanks @eivantsov  i am able to configure github repo and import the projects.
