### ISSUE TITLE
What does the asterisk on the left of the editor panel mean?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#625]
I opened a file and double clicked on the left of an editor panel, it show a small beautiful asterisk, as in this picture:

![editor](http://snag.gy/pV8vq.jpg)

Just want to know what does it mean? Just a mark for remembering?

**Comment by ddementieva** [comment]
It's something like a bookmark - an embedded feature of the Orion editor.

**Comment by freewind** [comment]
Thanks!
