### ISSUE TITLE
[LS] Language Servers stop working on large files

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#6251]
`**Reproduction Steps:**
* Go to [codenvy.io](https://codenvy.io)
* Create _blank_ workspace
* Enable _Python language server_
* Open workspace
* Create sample project _web-python2.7-simple_
* Open _main.py_
* Copy-past text several times up to 400-500 lines
* See that validations stops working

**The same behavior has seen on Che v.5.16.0 and for JSON language server too.**

![screenshot_103](https://user-images.githubusercontent.com/11683340/30373692-cefdfd74-988a-11e7-8a55-88426a9b339e.png)

I guess this problem occurs for all LS due to the same mechanize somewhere deep inside _plugin-languageserver_ or on the server side.

**Comment by slemeur** [comment]
@evidolob + @vparfonov : Could you please check that issue?

**Comment by gorkem** [comment]
Is this different from #6231

**Comment by zatsepinvl** [comment]
@gorkem, The same. 

> I have payed attention that Che establishes new WebSocket connection to ws-agent after all "didChanged" messages to server and thus publishDiagnostics can't be received due to re-connection time.

**Comment by zatsepinvl** [comment]
@slemeur, @gorkem 
I try to investigate the problem and the most appropriate reason is _WebSocket text message buffer size_ which is **8KB** as a default value. I guess isn't enough to send all large file text and connection closes and reopens.
Just try to debug this class: [BasicWebSocketEndpoint.java]( https://github.com/eclipse/che/blob/master/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/websocket/impl/BasicWebSocketEndpoint.java)

Setting up session buffer size in this class fixes the problem: 
```java

    @OnOpen
    public void onOpen(Session session)
    {
        String combinedEndpointId = getOrGenerateCombinedEndpointId(session);

        LOG.debug("Web socket session opened");
        LOG.debug("Endpoint: {}", combinedEndpointId);

        session.setMaxIdleTimeout(0);
        session.setMaxBinaryMessageBufferSize(1 << 20);
        session.setMaxTextMessageBufferSize(1 << 20);

        registry.add(combinedEndpointId, session);
        reSender.resend(combinedEndpointId);
    }
```

**Comment by tsmaeder** [comment]
Note that sending arbitrarily large messages is mandated by LSP (didChange() with full sync). So increasing the max buffer size is probably not the answer.
