### ISSUE TITLE
Git commit window tree files view selection model confused

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#6255]
**Reproduction Steps:**
1. Open a workspace with a project.
2. Make changes in a few files from the same directory.
3. Open commit window, uncheck some files from the directory.

![git-commit-tree-view](https://user-images.githubusercontent.com/15607393/30378041-91e0a18e-989a-11e7-967e-3960d39f0c32.png)
The directory is still checked like all files inside are checked. But actually some files aren't included into commit. It is confusing and error prone.

My suggestion is to add third state to checkbox for folders, like
![git-commit-tree-view-sug1](https://user-images.githubusercontent.com/15607393/30378587-67b2879a-989c-11e7-9659-7518fc454dd0.png)
or
![git-commit-tree-view-sug2](https://user-images.githubusercontent.com/15607393/30378596-6cf85428-989c-11e7-8625-9b1cdc59d0c7.png)
and it will appears only if some (not all) internal nodes are checked.
In case if a user clicks on third-state checkbox it should jump to unchecked state and uncheck all subnodes recursively.

- [x] Introduce a new icon for partially selected entry
- [x] Fix logic detecting partially selected entry
- [x] Make a new abstraction to use into Git dedicated panel

**Comment by mmorhun** [comment]
This is very inconvenient behaviour, marking as a bug...

**Comment by slemeur** [comment]
Good idea !

**Comment by vinokurig** [comment]
@mmorhun What is the behavior  of this panel when there are no Git projects are present in the workspace? If it becomes empty may be it would be better to hide the panel (like pull-request panel does)?
