### ISSUE TITLE
Does che supporting single step debugging now?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#626]
Just want to know if che supports single step debugging for Java projects, like we normally do in eclipse.

If I understand it correctly, it doesn't support now, since we can only run some simple commands for building or running, is it?

If not, does this feature on the plan?

**Comment by ddementieva** [comment]
Che provides remote debug option. 

You can run Java console application with JVM options to debug it. Your command may look like this: `clean install && java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y ${current.project.path}/target/*.jar`

This will start debug on the port 8000. Now you can go to Run > Remote Debug menu, choose port 8000 and click OK.  

As to web Java applications, it is possible to start Tomcat with jpda options. Debug command for sample web apps looks like this: `clean install && cp ${current.project.path}/target/*.war $TOMCAT_HOME/webapps/ROOT.war && $TOMCAT_HOME/bin/catalina.sh jpda run`

**Comment by freewind** [comment]
@ddementieva Thanks for showing how to do it, many thanks!

I just tried it, this is my debugging command (just copied from your answer):

![debug-command](http://snag.gy/LYCK9.jpg)

When run it, the remote side is ready:

![ready](http://snag.gy/jjUll.jpg)

And I connect it with remote debugging:

![remote](http://snag.gy/kergJ.jpg)

It seems the breakpoints are working:

![breakpoints](http://snag.gy/w4e7z.jpg)

Everything seems well now, but after that I can't do anything with them. The "step into" or "step over" buttons seems all be disabled.

Do I miss anything?

**Comment by ddementieva** [comment]
Error message says that port 8000 is already in use. You can try to change the port in command to 8001, run command, open Run > Remote Debug menu, paste port 8001 and click OK.

**Comment by freewind** [comment]
@ddementieva Thanks for pointing this error :+1: 

This time I changed the port to `18000`, but when I started the debug session and connected to the remote `18000` port, the breakpoints didn't work and it run to the end and printed `Hello world!bbb` immediately.

![1](http://snag.gy/PDEFx.jpg)

![2](http://snag.gy/aCTKQ.jpg)

![3](http://snag.gy/8LZVY.jpg)

![4](http://snag.gy/mwbyP.jpg)

I didn't do anything yet, but it ran to the end and didn't give me any chance to step debug:

![5](http://snag.gy/015sG.jpg)

**Comment by ddementieva** [comment]
You have to set breakpoints before starting debug session.

**Comment by freewind** [comment]
@ddementieva I did set the breakpoints before starting the debug session

**Comment by ghost** [comment]
https://youtu.be/DP1uHy92V-E

Please take a look and let me know if this is smth that you expect.

**Comment by freewind** [comment]
@eivantsov Thanks for your video, my steps are exactly the same as yours, but it doesn't work on my side.

You could try this online project now: http://198.199.105.97:8080/dashboard/#/ide/wksp-f7de

I won't change it and wait for you, and monitor this issue for any updates

**Comment by ghost** [comment]
Can you try with the latest nightly? I can reproduce the issue with your version. And no issues with the latest nightly.

**Comment by freewind** [comment]
@eivantsov My che should be latest nightly. This is the info:

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
codenvy/che                nightly             91b1dbfadc2a        2 days ago          635.8 MB
```

I just ran `docker rmi 91b1dbfadc2a` and redownload `docker pull codenvy/che:nightly` and got the same image

**Comment by ghost** [comment]
Hm.. I ran it locally in Docker (RC10-SNAPSHOT) and can debug a console app.

Can you keep your VM alive for a bit? I'll poke around.

**Comment by freewind** [comment]
Yes, I will keep it alive

**Comment by ghost** [comment]
OK, we have found the problem. Will create an issue. The problem is that client and servers are not on the same host. And, debugger fails to add a breakpoint.

We have added a thread sleep and it works ok now - http://198.199.105.97:8080/dashboard/#/ide/wksp-f7de

**Comment by freewind** [comment]
@eivantsov Thanks for finding the issue!

**Comment by ghost** [comment]
@freewind This commit should fix it - https://github.com/eclipse/che/commit/ed31c538ad15fcf5edda99f7c49b43e1273d623a

**Comment by asyzdykov** [comment]
Hi guys, 

I've got the same problem in my workspace. Is this problem already solved?
