### ISSUE TITLE
Tooltip seems to use Orion default style instead of Eclipse Che's tooltip styling

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6288]
I don't know if this is a bug or intended feature since I spotted this while I have errors in my project

![image](https://user-images.githubusercontent.com/14976516/30474244-9012aef0-9a35-11e7-8d6c-8c8941a08111.png)

This is how it should normally look

![image](https://user-images.githubusercontent.com/14976516/30474458-56d74c62-9a36-11e7-9542-1abb59ce1c65.png)

**Reproduction Steps:**

- Normally open a project and hover to a statement with errors, you might get lucky to spot this since it might be a rare bug.

Expected: Gray tooltips on hover.
Resulting Behavior: uses Orion's default scheme instead.

**OS and version:**    
Codenvy 5.18.0-SNAPSHOT on Windows 10

**Comment by bmicklea** [comment]
@eivantsov @vparfonov

**Comment by ghost** [comment]
I have hard time reproducing this one

**Comment by bmicklea** [comment]
@sr229 are you able to consistently reproduce it?  It may be some kind of side effect of another error...

**Comment by sr229** [comment]
@bmicklea seems not to reproduce on newer snapshots, again, this is a rather rare bug

**Comment by bmicklea** [comment]
Closing as no longer reproducible.
