### ISSUE TITLE
Project explorer randomly fail to expand some folders

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#6289]
**Reproduction Steps:**
- Import projects
- Try to expand some folders
- Some folders fail to expand
- No error from server
- No console log error

When refreshing the browser (F5), sometime the folder that couldn't be expanded magically expand well. but can't expand new other folders ....

**Comment by sunix** [comment]
Maybe related to files that are openned in a previous session

**Comment by SkorikSergey** [comment]
This bug reproduced if open any file not from root of the project and refresh web page. And in this use case there is not a possibility to open the "main" folder after refreshing.
![teams-17](https://user-images.githubusercontent.com/7760565/30476324-5a1c3730-9a12-11e7-8e14-175a3820d9c3.gif)

**Comment by SkorikSergey** [comment]
Fixed.

**Comment by sunix** [comment]
hi @SkorikSergey 
thanks for the fix,
which PR is fixing this ?

**Comment by SkorikSergey** [comment]
This bug was fixed by https://github.com/eclipse/che/pull/6287.
