### ISSUE TITLE
Unable to see Swagger documentation for WS Agent REST APIs

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-che/che#6309]
When I enter the URL in my browser: http://192.168.99.100:8080/swagger/?URL=http://192.168.99.100:32811/api/docs/swagger.json

where 32811 is the port of my WS Agent

I only see Swagger documentation for WS Master REST APIs (e.g., agent, factory, preferences, profile...).  I even see documentation for my own REST API that is in WS Master.

**Reproduction Steps:**

**OS and version:**    
Windows 7 using Oracle VirtualBox

I followed the instructions here:
https://www.eclipse.org/che/docs/assemblies/sdk-rest-apis/

I would like to see Swagger REST API documentation for my APIs that run in the WS Agent.  Also, I'd like to see them for the /Project REST API and other Che REST APIs that run in WS Agent.

I am running a custom assembly with Che 5.17.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/5337267/30514361-dcf241ea-9b1b-11e7-8c65-6f4b7229ce9c.png)

I am on Ubuntu though. 

Or, there's another way - `http://172.17.0.1:8080/swagger/?url=http://172.17.0.1:32774/api/docs/swagger.json`

In my case, its' `?url` not `?URL`

**Comment by BarryDrez** [comment]
What version is this?  Also, I notice you have the Error (bottom right).

**Comment by ghost** [comment]
@BarryDrez nightlty tag. And disregard the error. 

I wonder if this is some sort of boot2docker issue.

**Comment by BarryDrez** [comment]
I just tried it on a Ubuntu Linux machine, and I get the same error.

**Comment by ghost** [comment]
Tried 5.17.0 tag. Cannot reproduce. Are you certain you use the right port? Have you tried mydifying port in the main Swagger page?

**Comment by BarryDrez** [comment]
I am using the wsagent port

**Comment by ghost** [comment]
@BarryDrez can you share a screenshot with browser address bar visible?

**Comment by BarryDrez** [comment]
![image](https://user-images.githubusercontent.com/24534027/30542046-d0337db2-9c4b-11e7-897b-6cd7a8fc1331.png)

**Comment by ghost** [comment]
@BarryDrez I mean with swagger page

**Comment by BarryDrez** [comment]
![image](https://user-images.githubusercontent.com/24534027/30542098-fb5a83b4-9c4b-11e7-8db5-7c383e1a13f5.png)

**Comment by BarryDrez** [comment]
Is this the correct way?

**Comment by ghost** [comment]
@BarryDrez yes.

Quick question:

1. You are on Ubuntu, right? Why do you use IP that you use? Why not localhost?

**Comment by BarryDrez** [comment]
Right.  That is the URL that the console displays when I start Che.  I tried it with localhost, and I get the same error.
![image](https://user-images.githubusercontent.com/24534027/30542825-cad290c6-9c4e-11e7-8184-8f53b022704b.png)

**Comment by ghost** [comment]
@BarryDrez i think I got it. You have created your assembly using achetypes. And those, use stripped version of ws-agent.

Please, take a look at https://github.com/eclipse/che/blob/master/assembly/assembly-wsagent-war/src/main/java/org/eclipse/che/wsagent/server/SwaggerServletModule.java

**Comment by BarryDrez** [comment]
Do I need to add this class to my assembly?

**Comment by ghost** [comment]
Yes, please take a look at how it's done in the default assembly.

**Comment by BarryDrez** [comment]
Yes.  It works now.  Thanks
