### ISSUE TITLE
Memory leaks on Chrome after saving files.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#6311]
This is not 100% (but highly frequency) reproduction to me for now.

My workspace is hang up after saving action.
CPU usage becomes mostly 100%.
Memory usage increases from 300M to over 800MB.

**Reproduction Steps:**

1. Open Workspace
2. Open text.
3. Edit it
4. Save it.

**OS and version:**    

Browser
Chrome : 60.0.3112.114（Official Build） （64 bit）

Che
Version :5.18.0-SNAPSHOT
Revision :20d596648cb1bf4b
Build Time :2017-09-15 16:12:46

May not be specific versions. I got this error for a few weeks.

**Diagnostics:** 

Some additional info:

* It got this issue even if I set auto-save off.
* My Che server is on my cloud (not intranet).

**Comment by monaka** [comment]
I'm not sure what is the trigger. But the memory is increased periodically after triggered this issue.
I suspect this will be related on timer handlings.

**Comment by ghost** [comment]
@monaka i am pretty sure it's related or the same as https://github.com/eclipse/che/issues/6208

**Comment by ghost** [comment]
@monaka it should be fixed by https://github.com/eclipse/che/issues/6208 Feel free to reopen if you see the same behavior in the latest nightly
