### ISSUE TITLE
[SPI branch] The snapshotting workspace failed to delete

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6312]
**Reproduction Steps:**
* Crate a workspace and open in the IDE
* Stop it with snapshot by context menu in the navbar
* After that try to delete the workspace

**Expected behavior:**
* the workspace should be deleted

**Observed behavior:**
* the deleting of the workspace is failed

**Che version:** 5.18.0
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See ther atachment:
![stop-ws-with-snapshot](https://user-images.githubusercontent.com/5408906/30518748-edafb3b4-9b8e-11e7-904c-68466d40c38c.png)

![failed-delete-ws](https://user-images.githubusercontent.com/5408906/30518689-eeb2d404-9b8d-11e7-9509-d959e3c5fd17.png)

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/commit/96d9328baeaa26f191a5fba5035e5439747a7498#diff-09106a0b8bd8bd2e645bc960fb67ee0cR70
