### ISSUE TITLE
Project Name and icon seems to be missing after successful init of Workspace

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#6314]
This might be a new bug since it didn't happen to earlier snapshots of 5.18

![image](https://user-images.githubusercontent.com/14976516/30529823-1263eda2-9c74-11e7-9538-f207d3193601.png)

**Reproduction Steps:**
1:) Using this [Sample Factory](https://nightly.codenvy-stg.com/f?name=kotnyan&user=chinodesuuu), wait for the WS to load

Expected behavior: Project icon and name should appear and registered properly.

Resulting behaviour: Project icon and name is missing.

**OS and version:**    
Codenvy 5.18.0-SNAPSHOT on Windows 10

**Comment by ghost** [comment]
@sr229 it's ok on my side:

![image](https://user-images.githubusercontent.com/5337267/30529921-f741b38e-9c4a-11e7-893b-be34f1d48957.png)

Can you reliably reproduce it?

**Comment by sr229** [comment]
yes, after a couple of restarts, issue still persists @eivantsov 

![image](https://user-images.githubusercontent.com/14976516/30530303-3b8e06be-9c78-11e7-962d-9a2421bb5efb.png)

Clicking on it however, adds the icon and the project name

**Comment by ghost** [comment]
@sr229 try it in an incognito tab

**Comment by AndrienkoAleksandr** [comment]
@eivantsov I saw it few times . It's a some unstable bug.

**Comment by SkorikSergey** [comment]
**Steps to reproduce this bug:**
1. Create and start a workspace with any project
2. Stop this workspace and start

![teams-20 1](https://user-images.githubusercontent.com/7760565/30539794-ce6f1db6-9c7c-11e7-9604-18341728fea1.gif)

**Comment by sr229** [comment]
This seems to be a regression I think due to the fact it has happened after leaving the IDE and you jump back in on my situation
