### ISSUE TITLE
Add links to GitHub and  Mattermost channel in the IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#6321]
We should include links in the product in order to let a user being able to engage with the community more easily.

Since we opened the mattermost channel we should add a new entry in the Help menu:
![screen shot 2017-09-18 at 14 24 28](https://user-images.githubusercontent.com/1636769/30541850-4a850500-9c7d-11e7-8a4d-779ee72ecea8.png)

The item "Public Chat" should be below "Community" and point to: https://mattermost.eclipse.org/eclipse/channels/eclipse-che

Also we add "Report Issue" and point to: https://github.com/eclipse/che

**Comment by vparfonov** [comment]
@slemeur Is this still actual ?

**Comment by slemeur** [comment]
Yes.
