### ISSUE TITLE
IDE doesn't execute a command after start of workspace 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6324]
Related to SPI branch only.
When I start workspace either in IDE or UD client doesn't connect to exec server. 
So when I try to execute any command IDE doesn't show the result of the command since it doesn't send command execution request to exec server.
Also, IDE should not activate RUN panel when there is no connection with exec server.
BTW reloading the page fixes the issue.

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by azatsarynnyy** [comment]
Executing commands in IDE fixed by https://github.com/eclipse/che/commit/c04314da1a6ecf5ca2100e10dafa7cbeab0bffe4

**Comment by garagatyi** [comment]
@slemeur How do you think should we disable run commands panel until the server is available? Isn't it the purpose of new start flow?

**Comment by ghost** [comment]
@garagatyi in my case exec agent is up and OK since F5 fixes it.

**Comment by garagatyi** [comment]
It is exactly what I have experienced.

**Comment by ghost** [comment]
But exec agent is the first to start, even before ws agent. It is there and accepting requests (I used rest console to check)

**Comment by garagatyi** [comment]
yes, I completely agree with you

**Comment by garagatyi** [comment]
@eivantsov can you check whether it is fixed or not?

**Comment by ghost** [comment]
@garagatyi @azatsarynnyy cannot reproduce it with the latest SPI

**Comment by slemeur** [comment]
@garagatyi you are right, this is also something we need to handle as part of the work on the new workspace loading sequence.

BTW - We should not start by the exec server. 

See #5231
