### ISSUE TITLE
Upgrade base java to 8u131 or above

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6328]
Eventually, we would like to use some docker specific jvm option like ```-XX:+UseCGroupMemoryLimitForHeap``` or ```XX:MaxRAM``` we not yet decided which one but it would be nice to upgrade java to most recent one.
Related to this issue https://github.com/eclipse/che/issues/4152
See more https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Comment by garagatyi** [comment]
Can you elaborate on where exactly to upgrade and the reason for the upgrade?

**Comment by skabashnyuk** [comment]
where - all our base images
reason - use docker specific jvm options

**Comment by garagatyi** [comment]
Do you mean base images for stacks?

**Comment by skabashnyuk** [comment]
yes. They are most interesting.

**Comment by ghost** [comment]
Our current openjdk version is 8u131-b11

**Comment by skabashnyuk** [comment]
Can we do the same here https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile#L22 ?

**Comment by garagatyi** [comment]
ping @eivantsov

**Comment by skabashnyuk** [comment]
I think we can postpone this issue.
