### ISSUE TITLE
Nothing is displayed after stop workspace by command

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6329]
**Reproduction Steps:**
* Create a workspace and open it in the IDE
* Type in the terminal the command _kill -9 $(ps ax | grep java | grep ws-agent | grep conf | grep -v grep | awk '{print $1}')_ and perform it

**Expected behavior:**
* should be displayed the 'ask dialog form' with message and restart button the workspace 
* it may be like on che5 :
![kill-process](https://user-images.githubusercontent.com/5408906/30579654-3fa35970-9d22-11e7-83e2-1a4a395ec0b9.png)

**Observed behavior:**
* nothing displayed after stop process:
![kill-process-2](https://user-images.githubusercontent.com/5408906/30579763-ac9531a2-9d22-11e7-9857-e36d523b3fe9.png)

**Che version:** che6
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Related selenium test: _CheckRestoringWorkspaceAfterStoppingWsAgentProcess_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by skabashnyuk** [comment]
Depends on https://github.com/eclipse/che/issues/7550

**Comment by vparfonov** [comment]
Will be fixed in https://github.com/eclipse/che/issues/4437

**Comment by vparfonov** [comment]
fixed in https://github.com/eclipse/che/pull/8376
