### ISSUE TITLE
What's the difference between the two concepts "recipe" and "stack"

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#633]
I found there are two concepts are quite similar in CHE, one is "recipe" and another one is ["stack"](https://eclipse-che.readme.io/docs/environments#che-stacks).

In my opinion, a "recipe" just a Dockerfile which defines some ports and softwares and can be used to build a workspace machine, what's the difference between "stack" and it?

**Comment by ghost** [comment]
Recipe is a part of stack which is a wider entity. For instance, stacks have tags that are used to filter sample apps on a Dashboard. It also contains meta info on the software used in the environment, its type (one of them is recipe, but it can be an image or URL).

You can find stacks json on `/stacks`

**Comment by freewind** [comment]
@eivantsov Thanks for answering me, I'm much clear now.

One thing is do you mean the url is like http://198.199.105.97:8080/stacks? It returns 404

**Comment by AndrienkoAleksandr** [comment]
Stack contains workspace config and you can add predefined commands and
projects to your stack. "Stack" contains description of technologies which
will used in workspace created from this stack. And stack contains tags for
bind this stack with project samples. This samples should work correct in
workspace created from stack because projects uses technologies described
in the stack.

On Fri, Mar 4, 2016 at 8:23 AM, freewind notifications@github.com wrote:

> I found there are two concepts are quite similar in CHE, one is "recipe"
> and another one is "stack"
> https://eclipse-che.readme.io/docs/environments#che-stacks.
> 
> In my opinion, a "recipe" just a Dockerfile which defines some ports and
> softwares and can be used to build a workspace machine, what's the
> difference between "stack" and it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eclipse/che/issues/633.

## 

Andrienko Alexander -- Developer @codenvy.com -- +38 068 334-55-95
Cloud Dev Weekly Newsletter (free!) -- Codenvy Blog

**Comment by AndrienkoAleksandr** [comment]
http://198.199.105.97:8080/api/stack/list

On Fri, Mar 4, 2016 at 9:32 AM, Aleksandr Andrienko aandrienko@codenvy.com
wrote:

> Stack contains workspace config and you can add predefined commands and
> projects to your stack. "Stack" contains description of technologies which
> will used in workspace created from this stack. And stack contains tags for
> bind this stack with project samples. This samples should work correct in
> workspace created from stack because projects uses technologies described
> in the stack.
> 
> On Fri, Mar 4, 2016 at 8:23 AM, freewind notifications@github.com wrote:
> 
> > I found there are two concepts are quite similar in CHE, one is "recipe"
> > and another one is "stack"
> > https://eclipse-che.readme.io/docs/environments#che-stacks.
> > 
> > In my opinion, a "recipe" just a Dockerfile which defines some ports and
> > softwares and can be used to build a workspace machine, what's the
> > difference between "stack" and it?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/eclipse/che/issues/633.
> 
> ## 
> 
> Andrienko Alexander -- Developer @codenvy.com -- +38 068 334-55-95
> Cloud Dev Weekly Newsletter (free!) -- Codenvy Blog

## 

Andrienko Alexander -- Developer @codenvy.com -- +38 068 334-55-95
Cloud Dev Weekly Newsletter (free!) -- Codenvy Blog

**Comment by AndrienkoAleksandr** [comment]
http://198.199.105.97:8080/swagger/#/stack   and even more

On Fri, Mar 4, 2016 at 9:34 AM, Aleksandr Andrienko aandrienko@codenvy.com
wrote:

> http://198.199.105.97:8080/api/stack/list
> 
> On Fri, Mar 4, 2016 at 9:32 AM, Aleksandr Andrienko <
> aandrienko@codenvy.com> wrote:
> 
> > Stack contains workspace config and you can add predefined commands and
> > projects to your stack. "Stack" contains description of technologies which
> > will used in workspace created from this stack. And stack contains tags for
> > bind this stack with project samples. This samples should work correct in
> > workspace created from stack because projects uses technologies described
> > in the stack.
> > 
> > On Fri, Mar 4, 2016 at 8:23 AM, freewind notifications@github.com
> > wrote:
> > 
> > > I found there are two concepts are quite similar in CHE, one is "recipe"
> > > and another one is "stack"
> > > https://eclipse-che.readme.io/docs/environments#che-stacks.
> > > 
> > > In my opinion, a "recipe" just a Dockerfile which defines some ports and
> > > softwares and can be used to build a workspace machine, what's the
> > > difference between "stack" and it?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/eclipse/che/issues/633.
> > 
> > ## 
> > 
> > Andrienko Alexander -- Developer @codenvy.com -- +38 068 334-55-95
> > Cloud Dev Weekly Newsletter (free!) -- Codenvy Blog
> 
> ## 
> 
> Andrienko Alexander -- Developer @codenvy.com -- +38 068 334-55-95
> Cloud Dev Weekly Newsletter (free!) -- Codenvy Blog

## 

Andrienko Alexander -- Developer @codenvy.com -- +38 068 334-55-95
Cloud Dev Weekly Newsletter (free!) -- Codenvy Blog

**Comment by freewind** [comment]
@AndrienkoAleksandr Thanks for all the replies, I understand it now, and also thanks for the links
