### ISSUE TITLE
Scrolled line should appear in the middle of the editor

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#6330]
We have dozens of places where we programmatically scroll the file to the specific line:
```
    new Timer() {
      @Override
      public void run() {
             textEditor.setCursorPosition(new TextPosition(lineNumber, 0));
      }
    }.schedule(300);
```
The scrolled line usually appears in the bottom of the editor that isn't a convenient. 
It should be the middle of the editor.

https://orionhub.org/jsdoc/symbols/orion.editor.TextViewShowOptions.html

The goal of the task is to rework method https://github.com/eclipse/che/blob/fc3a2d2b2db7b1a319c33ff1774be9fb3969ec93/ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorPresenter.java#L743
to avoid using timer and to display scrolled line in the middle of the editor.

https://github.com/eclipse/che/blob/6e9825c699d34eef6b8bf36fc0194ff871cbee84/ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionTextViewOverlay.java#L128
https://github.com/eclipse/che/blob/6e9825c699d34eef6b8bf36fc0194ff871cbee84/ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionTextViewShowOptionsOverlay.java#L15

**Comment by tsmaeder** [comment]
https://github.com/eclipse/che/issues/6673 duplicate?

**Comment by vinokurig** [comment]
No that's another problem.
