### ISSUE TITLE
How to define another environment and switch between environments?

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#634]
I see in the che documents, there is a concept "environment" and a workspace may have multiple environments. 

But in a workspace, I can find a way to define other environments and switch between them. Is there feature already provided? Or do I miss anything?

**Comment by ghost** [comment]
Right now, there's no such an option when it comes to starting workspaces from Dashboard or IDE. API, however, allows it.

You may want to see what's happening when you create a workspace. First a workspace is created. By default, it's created with one environment which is based on a chosen recipe. However, API allows having multiple environments associated with a workspace. So, you may create a ws with env1 and then update it with env2. 

When a workspace is started, environment is defined in a query parameter:

`/api/workspace/$ws-id}/runtime?environment=${ENV_NAME}`

At the moment, we do not have any UI that will be linked to the right API calls, letting a users create multiple envs associated with a workspace and choose env when starting a workspace.

**Comment by freewind** [comment]
@eivantsov  Thanks, I'm clear now :)
