### ISSUE TITLE
Save Eclipse Che logs into the target directory of Che integration tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6348]
Sometimes we need _Eclipse Che_ logs for analyzing selenium tests failures including.
So, it would be useful if _Jenkins_ obtains logs from docker container with _Che_ server and save it into the **target/che-logs** subdirectory of tests codebase.

**Comment by riuvshin** [comment]
logs will be available in `${WORKSPACE}/che_server_logs`

example: https://ci.codenvycorp.com/view/qa/job/che-integration-tests/ws/che_server_logs/
