### ISSUE TITLE
[Regression]  Sometimes after creating a workspace a project is not valid 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6353]
**Reproduction Steps:**
1. Create a workspace with 2 or more projects
2. Wait while the workspace started

**Observed behavior:**
Sometimes the project is not valid. Basically this issue is reproduced in ** codenvy **.

**Che version:** 5.19.0-SNAPSHOT
**OS and version:** Fedora 25
**Failed test:** CreateAndDeleteProjectsTest

**Additional information:**
May be depend on https://github.com/eclipse/che/issues/6344
Problem happens randomly: [Yes]
![org eclipse che selenium dashboard createanddeleteprojectstest createanddeleteprojecttest_9lpqazfl](https://user-images.githubusercontent.com/7760565/30633854-e7a56342-9df5-11e7-84a6-af75646610f3.png)
![teams-24](https://user-images.githubusercontent.com/7760565/30633855-e7a6f02c-9df5-11e7-9109-5f9847f15624.gif)

**Comment by ghost** [comment]
Related to https://github.com/eclipse/che/issues/6075

**Comment by SkorikSergey** [comment]
This bug is still reproduced.

**Comment by ghost** [comment]
@SkorikSergey steps to reproduce please

**Comment by vparfonov** [comment]
@SkorikSergey  https://ci.codenvycorp.com/view/qa/job/che-integration-tests/50/Selenium_tests_report/ 
CreateAndDeleteProjectsTest marked as success

**Comment by SkorikSergey** [comment]
**Reproduction Steps:**
1. Create a workspace with 2 or more projects
2. Wait while the workspace started
![teams-11-2](https://user-images.githubusercontent.com/7760565/30849985-b94cea2c-a2ac-11e7-9844-8109f959e85a.gif)

Test failed on https://ci.codenvycorp.com/view/qa/job/nightly-onprem-selenium-tests/45/Selenium_tests_report/.

**Comment by SkorikSergey** [comment]
This issue is still reproduced.
