### ISSUE TITLE
No code validation for C# files after workspace restart

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#6355]
Steps to reproduce:

1. Start a .NET workspace with a sample project
2. Open .cs file, ensure error marking is there.
3. Stop a workspace
4. Start a workspace.

No code validation in the file. Refreshing the page fixes it.

**Comment by SkorikSergey** [comment]
There was similar issue: https://github.com/eclipse/che/issues/6016.

**Comment by gorkem** [comment]
wonder if there is a language server issue around this going on, see https://github.com/redhat-developer/rh-che/issues/367

**Comment by ghost** [comment]
@gorkem when this bug shows up, there's nothing scary in language server logs. It's rather Che editor issue. I can't say for sure though, but it looks like it is. For instance, this is true for php language server too.

**Comment by thyeun** [comment]
@eivantsov , yup, php having the same issue also, will it be a fix on C# and php on this issue?

**Comment by ghost** [comment]
@thyeun i think once it's fixed for one LS, others will benefit from that fix as well
