### ISSUE TITLE
SPI - OpenShift Implementation - Show workspace Pod events in the IDE

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#6356]
This is en enhancement request. I think it would be nice to show workspace pods events when a workspace is being started. Currently, when a workspace is starting no logs are streamed until pod is up and Che agents starts, it can take a while for pod image to be pulled, and pod to be created. For a user it may look like Che stopped responding.

@sleshchenko @akorneta @l0rd @ibuziuk what do you think?

**Comment by ibuziuk** [comment]
@eivantsov there is already a similar issue[1] for `OpenShiftConector` in rh-che , so huge +1 for having this in SPI

[1] https://github.com/redhat-developer/rh-che/issues/148

**Comment by garagatyi** [comment]
Can you elaborate on which events OpenShift is firing except the pod creation events?

**Comment by ghost** [comment]
pulling image is one of them. I think it is most interesting for us:

```

4:02:03 PM | Normal | Created | Created container with docker id 27089818d453; Security:[seccomp=unconfined]
4:02:03 PM | Normal | Started | Started container with docker id 27089818d453
4:02:02 PM | Normal | Pulled | Successfully pulled image "rhche/centos_jdk8:latest"
4:02:01 PM | Normal | Pulling | pulling image "rhche/centos_jdk8:latest"
4:01:41 PM | Normal | Scheduled | Successfully assigned app to ip-172-31-53-149.ec2.internal


```

**Comment by garagatyi** [comment]
The feature looks interesting. This feature involves changes on both server and client side.

**Comment by sleshchenko** [comment]
I think publishing text part of events to output channel would be enough. So it doesn't require changes on the client side.

**Comment by ghost** [comment]
Yeah, the idea is to show a user that smth's happening, rather than display a static message that workspace is being started.

**Comment by garagatyi** [comment]
I mean that AFAIK client doesn't subscribe to such events right now and doesn't display them.

**Comment by sleshchenko** [comment]
As far as I know, the client subscribes on infrastructure output and display it. Docker infra and agents have already pushed own logs there.

**Comment by garagatyi** [comment]
It is not about logs it is about status events. We have RuntimeStatusEvent designed for such purposes. But it is used in a single place for now. We just need to add it on client side and on server side

**Comment by sleshchenko** [comment]
I'd start with publishing messages of the pods' events to the output channel. Because pods images are pulling parallel, I don't think that runtime status should be changed when one of the images are pulling or pulled. I just have no idea to how to name this status.
I propose to implement publishing events message to output. And only then if it would not be enough then create an issue for investigating how RuntimeStatusEvents can help us, and how to implement it for such purpose.

**Comment by sleshchenko** [comment]
Added publishing of events messages which are related to containers (where field path has the following format `spec.container{CONTAINER_NAME}`. Here is how it is displayed in IDE
![screenshot_20171106_120528](https://user-images.githubusercontent.com/5887312/32487216-ae83fd94-c3b1-11e7-9a8e-1ebd30882886.png)

But there is another Pod related event like `no nodes available to schedule pods`
<details>
<summary>full_event.json</summary>

```json
{
  "metadata": {
    "name": "workspace4e9b8473ls0ge4et.db.14f475382eaf01be",
    "namespace": "workspace4e9b8473ls0ge4et",
    "selfLink": "/api/v1/namespaces/workspace4e9b8473ls0ge4et/events/workspace4e9b8473ls0ge4et.db.14f475382eaf01be",
    "uid": "32b1b279-c2d5-11e7-ad32-e6f47d235b4d",
    "resourceVersion": "127873",
    "creationTimestamp": "2017-11-06T09:30:59Z"
  },
  "involvedObject": {
    "kind": "Pod",
    "namespace": "workspace4e9b8473ls0ge4et",
    "name": "workspace4e9b8473ls0ge4et.db",
    "uid": "32b08de8-c2d5-11e7-ad32-e6f47d235b4d",
    "apiVersion": "v1",
    "resourceVersion": "127854"
  },
  "reason": "FailedScheduling",
  "message": "no nodes available to schedule pods",
  "source": {
    "component": "default-scheduler"
  },
  "firstTimestamp": "2017-11-06T09:30:59Z",
  "lastTimestamp": "2017-11-06T09:31:14Z",
  "count": 6,
  "type": "Warning"
}
```
</details>


So it is not related to the particular machine. It was decided not to publish it as machine log. And it there will be a necessity to listen or display such event, later will be able to publish it as a warning of the Runtime or infrastructure specific event.
