### ISSUE TITLE
[Homepage] HTTPS everywhere

### ISSUE THREAD

**Issue by koppor** [eclipse-che/che#6360]
I am trying to enter a GitHub URL at https://www.eclipse.org/che/getting-started/cloud/

Although that site is HTTPS, the form POST target seems to be non-SSL:

![grafik](https://user-images.githubusercontent.com/1366654/30642220-416d7f5e-9e0a-11e7-8be9-5ecc7b720fbb.png)

Even though HTTPS is not really relevant there, [HTTPS everywhere](https://www.eff.org/de/https-everywhere) propagates to use HTTPS everywhere.

**Comment by ghost** [comment]
@koppor I cannot reproduce this behavior

**Comment by ghost** [comment]
Even though my browser does not complain, I see what you mean:

![image](https://user-images.githubusercontent.com/5337267/31265262-9e59b520-aa76-11e7-9e5a-5bc0fd4eca17.png)

@slemeur who's in a control of this page?

**Comment by koppor** [comment]
Firefox 56.0 does complain, Chrome 61.0.3163.100 does not.

**Comment by slemeur** [comment]
The issue should be fixed now. Thanks for raising this @koppor ;)

@eivantsov : anyone who is commiter on che project can edit the website. It is managed on an eclipse repository.
