### ISSUE TITLE
Use editor working copies for lsp didChange, etc.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6364]
Currently, LSP notifies language servers of document changes purely from the front end. This means that we don't know in the workspace agent what the current state of the document is (in LSP code). So whenever one of the language servers requests full text updates on "didChange", we have to send the full text from the ide to the wsagent and then on to every language server. 
Also, when we press F5 in the IDE, we send a "didOpen" notification to a language server that thinks the file in question already is open. The behaviour of the LS in this case is not defined.
However, we already track the contents of open files in the wsagent in working copies. I would like to leverage the working copy support to solve the above problems.

**Comment by evidolob** [comment]
Yes I agree, also we track changes in two way for LS and working copies, so we defiantly need reuse working copies. Also we need to review save and autosave features, to simplify code and increase quality of IDE.

**Comment by bmicklea** [comment]
Please add the appropriate issue labels, not sure if this is a bug or enhancement for example.
