### ISSUE TITLE
Java language server not available

### ISSUE THREAD

**Issue by skahil** [eclipse-che/che#6373]
After creating a che docker container and adding a sample Java project (codenvy/ubuntu_jdk8) no Java language server is available.  
DEV-MACHINE agents include C#, JSON, and PHP (all off) but no Java.

Could you please explain how I can install and/or make this available?  

Thank you!

**Reproduction Steps:**
I created a che container as per the insructions here:
http://www.eclipse.org/che/docs/setup/docker/index.html
I.e. eclipse/che-server:5.0.0-latest

I created a new project based on codenvy/ubuntu_jdk8

**OS and version:**    
16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64)

**Comment by ghost** [comment]
@skahil a few things to note:

1. 5.0.0 version is way too old
2. Use default java stack
3. There's no Java language server but Java tooling is deployed with the workspace agent. Just create a java project and it should be there.
