### ISSUE TITLE
Move  ANTLRv3 capable Java 1.5 grammar to lib

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6375]
Here https://github.com/eclipse/che/tree/master/plugins/plugin-java-debugger/che-plugin-java-debugger-server/src/main/java/org/eclipse/che/plugin/jdb/server/expression we have generated grammar of Java 1.5.  This is not our code. Taken from here http://www.habelitz.com/index.php/projects/java-grammars CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10093
Since we are not going to change here anything and compilation and maven checks take significant time (3.5 minutes on my OSX , 1.5 minutes on Linux) I'm proposing to move it to che-lib repository.

**Comment by benoitf** [comment]
+1
