### ISSUE TITLE
Che git will display empty cell if remote git url starts with spaces

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#638]
If the remote git url I added to che starts with spaces mistakenly, che can accept it:

![1](http://snag.gy/IXsFD.jpg)

but can't show it properly:

![2](http://snag.gy/hMIb0.jpg)

If I push to this remote, it will show such an error:

![3](http://snag.gy/tGVOE.jpg)

I think che should display an error when the url contains spaces, or just trim it directly

**Comment by ddementieva** [comment]
Thanks for reporting a bug.

**Comment by TylerJewell** [comment]
@ddementieva, @akorneta - please comment - is this bug still actual?

**Comment by ddementieva** [comment]
Yes, the problem is still there.

**Comment by TylerJewell** [comment]
@ddementieva - please include tracking issue either from GitHub or jira.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-1484

**Comment by TylerJewell** [comment]
@vkuznyetsov - can you assign the right engineer.  We are still assessing the priority, but let's make sure that this is in the right team's backlog.
