### ISSUE TITLE
Add submit on enter to search dialogue

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6382]
It would be really great if one could press enter after typing a search term on the search through all files (Ctrl + Shift + F) dialogue to submit/start the search.

It can be frustrating to get there with the keyboard only to need the mouse to submit.

**Comment by RomanNikitenko** [comment]
@davidwindell As a workaround you can use Tab to give focus "Search" button and next press Enter.

**Comment by davidwindell** [comment]
Looks like this has been merged with #7858 #7863
