### ISSUE TITLE
Starting a second container of eclipse/che will kill all the workspaces container of the first one

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#6383]
I'm trying to run 2 che-server in the same docker engine using the CLI. If I start a second che-server, the che launcher is killing all the workspaces started by the first one.
This issue is very annoying when trying to launch another che instance from a che workspace (che in che)

**Reproduction Steps:**
1. Start a first che-server

        docker run -t --rm  -v /var/run/docker.sock:/var/run/docker.sock -v /home/sutan/che-data:/data eclipse/che:nightly

2. Create and start a workspace from this new che-server
3. Start another che-server with different name and port

        docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /home/sutan/data-dev:/data -e CHE_CONTAINER=che-dev -e CHE_PORT=8081 eclipse/che:nightly start

4. Then, the workspace created by the first che-server is killed

**OS and version:**    
RHEL 7

**Comment by garagatyi** [comment]
This issue is a duplicate of existing closed issue. Take a look here https://github.com/eclipse/che/issues/4452

**Comment by ghost** [comment]
Yes, abandoned resource cleaner does its job.

**Comment by sunix** [comment]
It's closed as not a bug because there is no use case. But for che in che this is a issue.
Could we have an option to skip this cleanup ?

**Comment by ghost** [comment]
@sunix can you elaborate on the use case where you need to Che servers? With Che going multi user it does not make any sense to me. Right now some users try launching a few masters just to imitate Che SaaS, so that each user has own master.

**Comment by sunix** [comment]
@eivantsov my use case is Che in Che: with https://www.eclipse.org/che/docs/tutorials/che-in-che/index.html
This tutorial is working quite well except that the commands would need to be updated and this workspaces being killed issue.

**Comment by sunix** [comment]
Should be fix with #6505 and `che.docker.cleanup_period_min--1` in che.properties or `CHE_DOCKER_CLEANUP__PERIOD__MIN=-1` in che.env
