### ISSUE TITLE
Che can't authorise to github

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#639]
I click on the menu: Help -> Preferences, then click the right bottom cat to authorise to github:

![1](http://snag.gy/PExzM.jpg)

But the popped page is a 404:

![2](http://snag.gy/W1JBt.jpg)

**Comment by ddementieva** [comment]
You need to register an application in your GitHub account to enable automatic key upload. 

Find more details on how you can do that at https://eclipse-che.readme.io/docs/git#ssh-key-management

**Comment by freewind** [comment]
Thanks, I see it now. But I still feel a little bit strange when I see there is a 404, without any tips or warnings about my application configuration.

**Comment by ghost** [comment]
We'll improve user experience for this scenario. Yes, it is not obvious even though docs explain it.

**Comment by ghost** [comment]
This pull request will bring a more informative message on how to configure GitHub oAuth - https://github.com/eclipse/che/pull/646
