### ISSUE TITLE
After restarting workspace the project name does not displayed

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6393]
**Reproduction Steps:**
- Run java stack with spring default project
- Wait until project will be started
- Click right mouse button on the workspace name in the dashboard workspaces list and stop workspace with snapshot
- Run workspace 
- Repeat stop with snapshot and run 
- Pay attention that project name does not display

**OS and version:**    
Che 5.19.0 ; Chrome 59.0 ; Fedora 25

**Comment by RomanNikitenko** [comment]
@Ohrimenko1988 Is it similar to #6314?

**Comment by Ohrimenko1988** [comment]
Yes, I agree, this issue is duplicated of https://github.com/eclipse/che/issues/6314
