### ISSUE TITLE
Can't copy from or paste to the che terminal

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#640]
Che IDE has a `terminal` panel, which is useful, but we can't copy the content from it, or paste commands to it, which is not convenient.

Is there any way to make it possible? Or do we have plan to support it?

**Comment by ghost** [comment]
What is your OS?

**Comment by freewind** [comment]
Mac EI Capitan `10.11.1 (15B42)`, with Chrome

**Comment by freewind** [comment]
The **terminal** I mean is Che IDE's terminal panel, does it related to my OS in some way?

![terminal](http://snag.gy/G2Z1Z.jpg)

**Comment by ghost** [comment]
Yes, it works on Win and Ubuntu. Known issue.

What you can do is open a terminal in a new tab and use context menu to copy and paste.

**Comment by ShashankaNataraj** [comment]
Any updates on this?

**Comment by ddementieva** [comment]
The team is working on a fix.

**Comment by ddementieva** [comment]
Fixed in master by https://github.com/eclipse/che-lib/commit/a9955389efa41f079a87346b8c32994e54495225. Fix version 4.2.0.
