### ISSUE TITLE
SPI: Port AppStatesPreferenceCleaner to spi branch

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6406]
Looks like preference cleaning was implemented in master and not ported correctly in spi branch.
We don't have this feature in spi but have a class that implements it in abandoned module che-plugin-docker-machine. Looks like it is the result of the merge of the master in the spi.

**Reproduction Steps:**

**OS and version:**    

**Diagnostics:**

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che/pull/6611
