### ISSUE TITLE
PHP workspace cost long time to start up due to slow download speed

### ISSUE THREAD

**Issue by gt945** [eclipse-che/che#6411]
Hello,  It's very slow to download files from codenvy.com in china.
How about read url in ENV, so that I can download it from another place?

https://github.com/eclipse/che/blob/a013d28a95603d2d345f4426cbb74871456495c5/agents/ls-php/src/main/resources/org.eclipse.che.ls.php.script.sh#L29

**Comment by ghost** [comment]
@gt945 so what you propose is add some checks for `AGENT_BINARIES_URI` being exported in the environment and if not use the default one?

**Comment by ghost** [comment]
Closing the issue dueo to inactivity. @gt945 we're working on launching language servers in parallel containers. Also, I think we may end up having binaries in our ready to go stacks.
