### ISSUE TITLE
[SPI] Remove usage of deprecated OldRecipe object

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#6412]
Remove usage of deprecated [OldRecipe](https://github.com/eclipse/che/blob/2e3fe5b15e373a88fe1c58396e260f1798b9ff3a/wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/recipe/OldRecipe.java) object.

Note that Recipe API should be reworked as it uses OldRecipe. And it is not enough just to replace it with Recipe because it may not make sense to use RecipeService for storing recipes references to wit their URL but not contents.

**Comment by gazarenkov** [comment]
Can we do that before M1?

**Comment by skabashnyuk** [comment]
yes

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/6729
