### ISSUE TITLE
User limit of inotify watches reached

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6417]
I've just upgraded our team from 5.16 to 5.18 and unfortunately we are now experiencing Chrome crashing with the Che tab consuming 100% CPU.

I managed to get some debug from the workspace. Bear in mind we run large projects with many thousands of files (like Magento 2) but this was working fine in 5.16. We've rolled back for now.

```
[STDOUT] 2017-09-25 10:18:52,212[ted-scheduler-5]  [ERROR] [o.e.c.a.v.w.FileWatcherService 198]  - Can't register dir /projects/test/pub/static/frontend/test/default/en_GB/knockoutjs in file watch service
[STDOUT] java.io.IOException: User limit of inotify watches reached
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
[STDOUT] 	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
```

**OS and version:**    
Chrome 61, Ubuntu, Che 5.18

**Comment by slemeur** [comment]
@vparfonov : This seems to be related to #6208 and similar to the issues @sunix was having.

Could you please investigate?

**Comment by davidwindell** [comment]
@slemeur I'm not convinced this is related, as this is not the same issue as https://github.com/eclipse/che/issues/6114

**Comment by ghost** [comment]
@slemeur yes, this is not the same kind of issue. Can you increase the limit on the host machine and see if it helps?

**Comment by davidwindell** [comment]
Increasing the host limit helps stop these errors being thrown. Some questions:

 * Can you do anything to stop these breaking the browser if the inotify limit isn't high enough?
 * Has anything changed since 5.16 that would increase the number of inotify watchers significantly? We have been using Che for some time and never hit this issue before. Could it be that all the files in `.git` folders are being watched?

**Comment by davidwindell** [comment]
Closing this now the FileTreeWatcher has been removed in #6688

**Comment by slemeur** [comment]
Thanks for the update @davidwindell
