### ISSUE TITLE
When browser is resized, the content of the IDE terminal is missing partly

### ISSUE THREAD

**Issue by freewind** [eclipse-che/che#642]
There are some content in the IDE terminal. If I resize the browser to be smaller, then larger, some part of the content is missing, like:

![1](http://snag.gy/pzJWs.jpg)

You can see the right columns are not visible anymore

**Comment by ddementieva** [comment]
Issue confirmed.

Thanks for reporting it.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-705

**Comment by TylerJewell** [comment]
@ddementieva @jamesdrummond - I am escalating this as a blocker temporarily so that we discuss it during the next sprint planning session.

**Comment by TylerJewell** [comment]
We agreed to take this for investigation into the next sprint.

**Comment by vitaliy-guliy** [comment]
Dimensions of the terminal were not updated after resizing.
Spent 3h.
