### ISSUE TITLE
[MultiUser-branch] Page crashed when to delete a workspace on the dashboard

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6423]
**Reproduction Steps:**
* Create a workspace and open it in the IDE
* Go to back on the dashboard
* Try to delete the workspace

**Expected behavior:**
* the workspace should be deleted without any errors

**Observed behavior:**
* we have unexpected crashing of the page

**Che version:** 5.19.0
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![ws-not-permis](https://user-images.githubusercontent.com/5408906/30810831-f52cec7a-a20e-11e7-8096-91bc4b7ee798.png)
![page-crashed](https://user-images.githubusercontent.com/5408906/30810842-fdfb4888-a20e-11e7-9196-5aa5550a6b51.png)

**Comment by riuvshin** [comment]
not only delete, I saw that even on create workspace
