### ISSUE TITLE
[MultiUser-branch]  cache.js must be cached on che multiuser

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#6425]
for multiuser che we must cache `cache.js` because it makes it super slow on workspace start when CHE is hosted on remote node like that: http://a5.codenvy-stg.com:8080

**Comment by skabashnyuk** [comment]
Can't reproduce

<img width="1277" alt="2017-09-26 13 32 13" src="https://user-images.githubusercontent.com/1614429/30855916-42b295b6-a2bf-11e7-8e29-47a891e97fa1.png">
Make sure you are not disabling cache in dev tools.
