### ISSUE TITLE
Create project error: Client has aborted connection

### ISSUE THREAD

**Issue by ArthurHlt** [eclipse-che/che#643]
**Che-version**: 4.0.0-RC8

When creating i had this kind of error during _Injecting and starting workspace agent_ : `Client has aborted connection. Response writing omitted.` 

After read this: https://eclipse-che.readme.io/docs/networking
I get that I had to specified my host and port to make it work.
i change those values `api.endpoint` and `machine.docker.che_api.endpoint`, it seems to work as we can see in the trace during _Injecting and starting workspace agent_:

```
[STDOUT] 2016-03-04 13:04:40,847[rrest.WSClient1]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to ws://10.203.7.51:8080/ide/api/eventbus/?token=dummy_token. 
[...]
[STDOUT] 2016-03-04 13:04:41,387[nio-4401-exec-2]  [WARN ] [i.ContainerResponse$BodyWriter 90]   - Client has aborted connection. Response writing omitted.
[STDOUT] 2016-03-04 13:04:41,390[nio-4401-exec-1]  [WARN ] [i.ContainerResponse$BodyWriter 90]   - Client has aborted connection. Response writing omitted.
```

so, I continued to investigate and i found that when i tried to go to my workspace with the browser (e.g: http://10.203.7.51:8080/dashboard/#/workspace/workspacetv9s56bvl46huqvm <- this an internal url it will not work if you click on it) and tried to see what's happen in network connection panel I found this:
![capture d ecran 2016-03-04 a 14 22 29](https://cloud.githubusercontent.com/assets/5410858/13528163/92a0439c-e214-11e5-94f3-f36d9a9312bc.png)

It seems the ip is not change (Here it's still 127.0.0.1), do I miss a parameter to set the good ip ?
Is it a bug on che version 4.0.0-RC8 ? 

Btw, this is related to my project https://github.com/ArthurHlt/codenvy-che-boshrelease this kind be interesting for you, the goal to this project is to be able to make run che on any IaaS by using bosh (a deployment tool for any IaaS made by Pivotal), this will be reversed to https://github.com/cloudfoundry-community

**EDIT:** Forgot to say that I've also tried to directly hit 10.203.7.51:8080 from the container and it's worked

**Comment by ghost** [comment]
`che.sh run -r:${EXTERNAL_IP}` should help

or export DOCKER_MACHINE_HOST in the system to point to this external IP

**Comment by ArthurHlt** [comment]
I thought it was related to the ip of my docker (which is on the same machine and listening only on 127.0.0.1 for security reasons)
So, instead of -r:ip I've set `CHE_IP` (i saw that -r:ip set this value and in this context I preferred manipulate your env var)
We will see if it does the work, I will let you know.

**Comment by ghost** [comment]
Client has no need to connect to Docker. The connection is made to a process in the Docker container that runs a workspace. And you do not have anything like that running locally. Change that to an external IP and make sure that ephemeral port range is accessible.

**Comment by ArthurHlt** [comment]
do you mean that i should change how my docker daemon is listening?

**Comment by ghost** [comment]
Wait, is Docker running locally? I mean Che server and browser are on the same host?

**Comment by ArthurHlt** [comment]
for now, yes, but it will change (if you look at my project i need to go step by step to make all the things work)

**Comment by ghost** [comment]
Do you have DOCKER_HOST env variable exported in your system?

The browser connects to a container and if that connection cannot be made, there's some networking rule that prohibits it.

**Comment by ArthurHlt** [comment]
is after docker pull, docker container is created and i can even ssh into it. It's after in fact, I suspect that it's the connectivity between browser and docker workspace the problem (cause the ip set in websocket is 127.0.0.1 and not ip of my machine).
But to answer to your question, yes I exported this var :)

**Comment by ghost** [comment]
I knew it :)

You can try removing it for a while and make Docker listen over unix socket. In this case, the connection will be made to localhost.

**Comment by ArthurHlt** [comment]
Thank you for everything, set -r did the work.
Now, I have problem cause of proxy but I can handle it :)

About, unix socket, i was using socket connection first but the problem is that in your code you're taking the content of the var `DOCKER_HOST` and do `new URI(varDockerHost);` and with this URI can't understand unix:///my/path. I can't point you the code cause, sadly, I didn't keep the trace.

**Comment by ghost** [comment]
We first look for env vars and some Che properties and if not found, use unix:///my/path. So, envs are optional

**Comment by ArthurHlt** [comment]
yeah but you're trying to find in a default sock path, no ? Cause for me, in my context it's not the default one but `/var/vcap/sys/run/docker/docker.sock`

**Comment by ArthurHlt** [comment]
anyway, i will put the docker daemon on another VM. Thank you, and by the way, che is really awesome, thanks for the works

**Comment by ArthurHlt** [comment]
I know that you're working with IBM Bluemix, I understood that you've deployed codenvy on it. My work will certainly help you to update, install, remove codenvy/che on IBM Bluemix. What I use they must use it cause they use cloud foundry

**Comment by TylerJewell** [comment]
@ArthurHlt What you are working on is very cool. Can you email me at tyler@codenvy.com. We'd like to consider a blog post on it and to understand the use cases you are thinking about.

**Comment by ArthurHlt** [comment]
@TylerJewell this is related to a blog post: http://blog.codenvy.com/run-cloud-foundry-codenvy/ (see _to go further_ point 3)
I'm little in late i wanted to do the work before. I could make a blog post, maybe when i will finish a good release i could do it ? 

I know on the blog post it's related to Cloud Foundry but Bosh is a tool for IaaS not for Cloud Foundry

**Comment by TylerJewell** [comment]
Sounds good - we'd love to post the blog.

**Comment by ghost** [comment]
Closing the issue since the original problems seems to have been solved.
