### ISSUE TITLE
Synchronize the list of test repositories before running selenium tests

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#6430]
The list of repositories to fork is declared in  [README.md](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/README.md)

But if somebody  merged something in the original repos then users don't know if there forked repos are up to date.

The goal of this issue is to detect and let user know the difference between original repos and forked ones.

**Comment by rhopp** [comment]
New tests are not using those forked repos. Closing.
