### ISSUE TITLE
Publish Maven artifacts to central repository

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#6444]
Eclipse Che artifacts should be available/synchronized on maven central repository instead of having only a private repository.

Example:
https://mvnrepository.com/search?q=eclipse+che
users are not finding eclipse che

while end users would expect to find it at http://central.maven.org/maven2/org/eclipse/ (with che folder)

Also it would help ppl by having local mirrors.

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

Moved to central:
- [x] che-dev
- [x] che-parent
- [x] che-lib
- [x] che-docs
- [x] che
- [x] che-ide-extension
- [x] che-ide-server-extension
- [x] che-plugin-embedjs
- [x] che-plugin-json
- [x] che-plugin-menu
- [x] che-plugin-wizard

**Comment by benoitf** [comment]
it should fix as well issues when codenvy maven repository is not reliable

```
[ERROR] Failed to execute goal on project che-keycloak-plugin-server: Could not resolve dependencies for project com.redhat.che:che-keycloak-plugin-server:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.che.core:che-core-api-core:jar:5.18.0 -> 
org.eclipse.che.core:che-core-api-dto:jar:5.18.0: Failed to read artifact descriptor for org.eclipse.che.core:che-core-api-dto:jar:5.18.0: Could not transfer artifact org.eclipse.che.core:che-core-api-dto:pom:5.18.0 from/to codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/): 
Failed to transfer file: https://maven.codenvycorp.com/content/groups/public/org/eclipse/che/core/che-core-api-dto/5.18.0/che-core-api-dto-5.18.0.pom.
 Return code is: 502 , ReasonPhrase:Proxy Error. -> [Help 1]
```

**Comment by riuvshin** [comment]
we have some issues with che-lib
```
failureMessage    Missing: no sources jar found in folder '/org/eclipse/che/lib/org-eclipse-jdt-core-repack/6.100.0
failureMessage    Missing: no javadoc jar found in folder '/org/eclipse/che/lib/che-tomcat8-slf4j-logback/6.100.0'
failureMessage    Missing: no javadoc jar found in folder '/org/eclipse/che/lib/org-eclipse-jdt-core-repack/6.100.0'
```
this should be fixed, otherwise we wont be able to deploy on central

**Comment by riuvshin** [comment]
now all snapshots are pushed to central: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/che/
tags will appear with next release
