### ISSUE TITLE
Fix subversion selenium tests to have the same result locally and on CI

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6452]
We have selenium subversion tests which fails because of we use _local test svn repo_ locally and _remote test svn repo_ on CI, and those repos differ each other by number of revisions: _local repo_ has 1 revision whereas _remote repo_ - 4:
- [org.eclipse.che.selenium.subversion.UpdateToRevisionTest.updateToRevisionTest](https://ci.codenvycorp.com/view/qa/job/nightly-selenium-tests/48/testReport/org.eclipse.che.selenium.subversion/UpdateToRevisionTest/updateToRevisionTest/)
- [org.eclipse.che.selenium.subversion.LockFileTest.lockFileTest](https://ci.codenvycorp.com/view/qa/job/nightly-selenium-tests/48/testReport/org.eclipse.che.selenium.subversion/LockFileTest/lockFileTest/)

**_Solution_**: 
- fix local test svn repo to have the same revisions as remote one;
- fix subversion tests to comply revision number = 4.

**Comment by rhopp** [comment]
Part of old selenium suite. Not going to fix this. Closing.
