### ISSUE TITLE
Don't reload already opened workspace

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#6457]
We don't need to reload already opened workspace when switching between items in navbar.
Is needed for https://github.com/eclipse/che/issues/5231

![reload-the-workspace](https://user-images.githubusercontent.com/1655894/30903085-3a7ae1b6-a376-11e7-9881-f1bbec33eb13.gif)

**Comment by slemeur** [comment]
@vitaliy-guliy : Please link as subtask this issue to the epic on #5231 Thanks
