### ISSUE TITLE
Adapt multi-user functionality for spi branch

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6463]
We would like to start revising multi-use functionality terms of new spi. It should be XShift based assembly. 
Interesting points.
 - Are we correctly send authentification tokens? 
 - Do we have aligned our SPI and permissions and resource management?

**Comment by sleshchenko** [comment]
`che-multiuser` branch is merged into `spi` branch. It is possible to run `multiuser che` with new `spi ` that will start workspaces on `minishift`.

> Are we correctly send authentification tokens?

Situation is the same as in `che-multiuser` branch

> Do we have aligned our SPI and permissions and resource management?

New `spi` doesn't require any changes to permissions.
For making Resource API working there is the [issue](https://github.com/eclipse/che/issues/6555).
