### ISSUE TITLE
Log uncaught exceptions in ws-agent

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6468]
The default exception handler in Java logs to the console. In the wsagent process, only uncaught exceptions for particular threads are logged, the rest goes unnoticed. 
I suggest we replace the default exception handler with one that logs exceptions.

**Comment by garagatyi** [comment]
Hi, Thomas.
We are aware of this problem. And we have exception handler for that: [LoggingUncaughtExceptionHandler](https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-lang/src/main/java/org/eclipse/che/commons/lang/concurrent/LoggingUncaughtExceptionHandler.java#L22-L22)
[Here](https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectManager.java#L118-L118) is how we use it.
Do you have a particular place where we need to add it?

**Comment by tsmaeder** [comment]
I have seen that. My suggestion is to set that as the _default_ exception handler. That way we will see exceptions in all threads, no just the ones we start in this way.

**Comment by garagatyi** [comment]
I agree. What place do you think would be a good fit for such code?
Maybe static block somewhere here in [CheBootstrapper](https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/CheBootstrap.java#L119)?

**Comment by tsmaeder** [comment]
I'm not familiar enough with the code to suggest a location, but it should be early on the main thread, as soon as we have a logging infrastructure available.

**Comment by garagatyi** [comment]
@mkuznyetsov can we close this issue now?

**Comment by mkuznyetsov** [comment]
yes, default exception handler is now set for ws-master and ws-agent
