### ISSUE TITLE
Run selenium tests on CHE (single user) deployed on OCP

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#6475]
We should make it possible to launch existing selenium tests on OCP assembly.I think it will be complete with 2 phases:
1. Make possible running existsing tests, analyzing results. Exclude tests that fail for known reasons (like permission restrictions or absent functionality)
2. Make test suite with actual tests and run it on CI

**Comment by musienko-maxim** [comment]
After last running we have 40% passed tests. 
Most tests failed for next seasons:
1) Some features unavailable because of restrictions of permissions for launching a web applications
2) Some features are disabled like custom stacks and etc.
3) Unexected stopping workspaces (this should be investigated)

**Comment by musienko-maxim** [comment]
So, yesterday we have new image with enable permissions for running web applications in the IDE we should run new test session and analyze results again

**Comment by riuvshin** [comment]
we've fixed all infra related issues.

ci job: https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6-ocp/
