### ISSUE TITLE
Create A Factory Based On A Repo

### ISSUE THREAD

**Issue by kameshsampath** [eclipse-che/che#6479]
When we create a  factory from a github repo, it fails to pick the `.factory.json` when the url tend to contain `.git`. Usually when we copy the URLs from GitHub it ends with `.git` e.g. *https://github.com/kameshsampath/che-boot-demo.git* . Because of this the factory create fails and uses the default `codenvy/ubuntu_jdk8` image ref https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/plugins/plugin-urlfactory/src/main/java/org/eclipse/che/plugin/urlfactory/URLFactoryBuilder.java#L64.

It will be nice to sanitise the repo url if it ends with `.git` and use that as `jsonFileLocation`.

**Reproduction Steps:**

Install Che on minishift baed on the instructions https://www.eclipse.org/che/docs/setup/openshift/index.html#deploy-che-on-minishift

**Execute the command** 
http://che-eclipse-che.192.168.64.8.nip.io/f?url=https://github.com/kameshsampath/che-boot-demo.git (modify the che url as per your install)

This will fail with the error as the Repo url is not found because of `.git` in the end 

```
Error when starting agent
Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment 'che-boot-demo.git' failed. Error: We detected that a machine exited unexpectedly. This may be caused by a container in interactive mode or a container that requires additional arguments to start. Please check the container recipe.
```

Now try the same command like http://che-eclipse-che.192.168.64.8.nip.io/f?url=https://github.com/kameshsampath/che-boot-demo this will work well as the image now will pulled correctly.

**OS and version:**    
All OS 

**Diagnostics:** 

Minishift install as per https://www.eclipse.org/che/docs/setup/openshift/index.html#deploy-che-on-minishift

**Comment by ghost** [comment]
And of course, codenvy/ubuntu_jdk is the wrong default image to use. It should be `eclipse/ubuntu_jdk8`
