### ISSUE TITLE
Integrate vscode debugger for java applications

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#6480]
Che Debugger vs jdt.ls
Comparison list of features https://docs.google.com/document/d/1ZkyI1CgRpK7lY2RANuIPgX-nRNdce6Q1neX2N_aq0Tg/edit#

Replace the current implementation of [Java Debugger](https://github.com/eclipse/che/tree/master/plugins/plugin-java-debugger) with one provided by VSCode
https://code.visualstudio.com/blogs/2017/09/28/java-debug

https://github.com/vscjavaci/eclipse.jdt.ls

**Comment by tsmaeder** [comment]
Shouldn't this be an epic?

**Comment by tolusha** [comment]
Make sence

**Comment by slemeur** [comment]
Closing as duplicated of https://github.com/eclipse/che/issues/8383
