### ISSUE TITLE
Remove rewrite  /wsmaster/api/* to /api/*

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6481]
A long time ago requests to ws-master were like ```http://localhost:8080/api/user```. 
After we decided to change the name of ```api``` war to ```wsmaster```.
To make this change compatible with the previous version we have a rewrite rule.
```RewriteRule ^/api/(.*)$     /wsmaster/api/$1    [L]```
After that, part of our application are making request to ```/api``` some to ```/wsmaster/api```
Internally this solution works more or less. But eventually, it produces small chaos and unpredictable problems. Like I have redirection loop with Keycloak Opeid Filter because I have a request to ```/api``` but it was internally transformed to ```/wsmaster/api``` and result cookies was set on the path ```/wsmaster/api``` but it wasn't expected. 

I think it's time to drop this workaround with RewriteRule in next version of Che.

**Comment by benoitf** [comment]
I would say it was also to be consistent between che and codenvy across all clients

and you can use other flags than `[L]`

**Comment by skabashnyuk** [comment]
Yes. And after Che6 this consistency is not required, it means that is a good time for drop off.

**Comment by mshaposhnik** [comment]
There is no other ways to keep `/api` path than:
 - Rewrite valve;
-  Define app configuration in _Tomcat/conf/server.xml_ and override `Path`
-  Rename war;

@skabashnyuk @benoitf  what we decide ?

**Comment by benoitf** [comment]
@mshaposhnik I would say that the goal was to get rid of the valve so there is option 2 and option 3
and option 3, @gazarenkov does not want to rename it so we've only option 2

We may also add a file into conf/ folder which avoid to modify server.xml

- move wsmaster.war to `tomcat/` folder instead of `tomcat/webapps` folder
- add `conf/Catalina/localhost/api.xml` with content

```
<Context 
  docBase="../wsmaster.war" 
  reloadable="true" 
/>
```

Another topic could be to get rid of tomcat and use Jetty or Undertow

**Comment by skabashnyuk** [comment]
lets go with ```Define app configuration in Tomcat/conf/server.xml and override Path```

**Comment by benoitf** [comment]
AFAIK it's not the best practice to modify server.xml for extensibility.

**Comment by gazarenkov** [comment]
I am OK with any, just see no point to make it more difficult with files manipulation as we already have server.xml in the assembly and it does the job

**Comment by benoitf** [comment]
up to you guys

**Comment by skabashnyuk** [comment]
We are going to rename wsmaster.war to api.war
