### ISSUE TITLE
Websocket on Workspace Agent unable to perform call

### ISSUE THREAD

**Issue by glerat** [eclipse-che/che#6489]
Hi,
I deploy Eclipse che on Ubuntu(not a VM) and I try to connect via ssh from external IP.
Some time it works some times I get this error when I run the diagnostics (and of course the workspaces).
I have tried : 
docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock -v ~/EclipseChe:/data -e CHE_DOCKER_MACHINE_HOST=1xx.xxx.xxx.xx eclipse/che start

failed

docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock -v ~/EclipseChe:/data -e  eclipse/che start
failed

docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock -v ~/EclipseChe:/data -e CHE_HOST=192.168.1.32 eclipse/che start
failed

docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock -v ~/EclipseChe:/data -e CHE_DOCKER_IP=1xx.xxx.xxx.xx eclipse/che start
failed

docker run -it --rm -e CHE_PORT=9500 -v /var/run/docker.sock:/var/run/docker.sock -v ~/EclipseChe:/data -e CHE_HOST=192.168.1.32 eclipse/che start
failed

docker run -it --rm -e CHE_PORT=8080 -v /var/run/docker.sock:/var/run/docker.sock -v ~/EclipseChe:/data -e CHE_WORKSPACE_CHE__SERVER__ENDPOINT=172.17.0.1 -e CHE_HOST=176.186.250.14 eclipse/che start

failed

docker run --privileged --name che -it -p 32768-32788:32768-32788  -v /var/run/docker.sock:/var/run/docker.sock -v ~/EclipseChe:/data  -e CHE_PORT=80  -e CHE_HOST=192.168.1.32 -e CHE_DOCKER_IP=172.17.0.1   eclipse/che start --skip:preflight

failed 

I disabeled firewall.

Always the same issue.

I'm newbie in Eclipse Che. I'm completly discourage by this application. It s so hard to understand how to configure it.
I spent days and it still doesn't work.

When it works some times I can't figure how to display the result page. I can't open all the ephemerals ports on my router!?

**OS and version:**    UUBUNTU 16

**Diagnostics:**

**Comment by ghost** [comment]
`-e CHE_HOST=$external_IP` should be enough. And yes, the ephemeral port range should be opened on the VM

**Comment by glerat** [comment]
Thanks for your answer. 
When you say external_ip is it the computer ip or the external modem ip wich is redirected in my modem?
 I m not using a vm but a machine with Ubuntu on it. I m using che  from outside in ssh and I have to open(redirect) all ephemeral port on my internet modem?

**Comment by ghost** [comment]
This should be a public IP (I suppose it can be your router).

200-300 ports from the ephemeral range should be enough

**Comment by glerat** [comment]
Hi, if I indicate the external public IP it doesn't work, I put the ip of the Ubuntu machine in my network and it works, as I can't open range ip on the internet router(because it s the provider acces s router) I open them manually. But finally it works and it s a great ide. Now I'm looking for active t he completion for imports because it doesn't work. Thanks for you help.

**Comment by ghost** [comment]
@glerat I'm closing this issue then. Do open a new one regarding imports.

**Comment by glerat** [comment]
It is not fix, because when I try to connect from outside che open a ephemeral port randomly, and I have open 20 ports on my router without succes to connect on it. I spend One month , It never work from outside. I have tried every tickets on github or stackOverflow and it never works properly outside of my network. But I m giving  up. Thank you anyway.

**Comment by ghost** [comment]
Yes, Docker does port publishing for Che and it does it randomly. You gotta make sure that the ephemeral port range is not filtered for inbound connections from outside.
