### ISSUE TITLE
Question about templates folder

### ISSUE THREAD

**Issue by ArthurHlt** [eclipse-che/che#649]
I was reading this from docs: https://eclipse-che.readme.io/docs/templates
But I have a question, if I `git clone` all projects from `samples.json` inside the directory `project.template_location_dir` before runnning che, did che will link these cloned project to all samples or I have to set `.zip` file ?

Context is that I want to download all project template locally before running che on a server without internet access.

**Comment by ghost** [comment]
The json file is just a reference to git or zip sources. However, zip importer would only accept a URL to a remotely hosted zip archive.

What you can do though is add `host.projects.root` to conf and point it to a persistent location on your machine, git clone all examples there, and you will have these examples as projects in every workspace you create.

As to docs, the are not up to date, I'll fix that.

**Comment by ArthurHlt** [comment]
Thank you for the tip, it's nice to have this

**Comment by ghost** [comment]
https://eclipse-che.readme.io/v4.0/docs/templates

Updated docs
