### ISSUE TITLE
How to edit files in the default image? No vi, vim, nano or any text editors found

### ISSUE THREAD

**Issue by TrisDing** [eclipse-che/che#6491]
I'm using the default che stack (eclipse/ubuntu-jdk8) however, I don't find any text editor in the image (vi, vim, nano, etc). Due to my company policy, I can't do apt-get update && apt-get install (URL blocked), so can I use the che workspace editor to open a file in the image (say /home/user/tomcat8/conf/catalina.properties).

**Comment by AndrienkoAleksandr** [comment]
@TrisDing Yes, it's a bit tricky behavior of ubuntu docker image... You need first of all:
sudo apt-get update
And only than you can do:
 sudo apt-get install nano
P.S. I saw such behavior only for ubuntu image... Our image based on the original ubuntu docker image. And this behavior extends from original image...

**Comment by AndrienkoAleksandr** [comment]
@TrisDing  By the way In the default image installed midnight commander: mc , so you can edit file with help mc or mcedit

**Comment by TrisDing** [comment]
@AndrienkoAleksandr Thanks! mcedit works for me. I found the default alpine image has vi at least. Anyways, as long as I have something to edit, I'm good here. Closing.
