### ISSUE TITLE
Investigate problem of failing selenium tests for Find Usage and Navigate File Structure features

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6499]
**FileStructureNodesTest** and **FindUsagesBaseOperationTest** selenium tests fail while trying to open Node by double click action. If do double click action twice then Node will open. We should clarify of reason why the tests do not work properly.

**Comment by riuvshin** [comment]
seems this is related to: https://github.com/eclipse/che/issues/6524
