### ISSUE TITLE
Openshift 3.5 : Multiple ImageStreamTags found for name che when launching Java-MySQl Multi Machine workspace

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#6500]
I've setup Openshift 3.5 & running Che 5.18.0 on the same.
When I launh a multi machine workspace i.e. Java-MySQL, che reports an error stating "Multiple ImageStreamTags found for name che"

$oc get is

NAME                          DOCKER REPO           TAGS                                               
eclipse_mysql              eclipse/mysql             latest,che-ws-etisvb14x536bo800mhavmqgpn2n1t9l      
eclipse_ubuntu_jdk8   eclipse/ubuntu_jdk8   che-ws-etisvb14x536bo80e4hp2bwgrr2wefqn,latest,qa 
  
**Reproduction Steps:**
Setup OS v3.5 
Run Che 5.18.0
Launch multi-machine workspace i.e. Java-MySQL

**OS and version:**    
CentOS 7.3

**Diagnostics:** 
I see the issue is coming from OpenShiftConnect, getImageStreamTagFromRepo method

String imageTagTrimmed =
        imageStreamTagName.length() > 20 ? imageStreamTagName.substring(0, 20) : 
imageStreamTagName

Since, the above code trims the imageStreamTagName to 20 characters 

Tag Name for eclipse_mysql image stream changes from che-ws-etisvb14x536bo800mhavmqgpn2n1t9l to che-ws-etisvb14x536b

Tag Name for eclipse_ubuntu_jdk8 image stream changes from che-ws-etisvb14x536bo80e4hp2bwgrr2wefqn to che-ws-etisvb14x536b

In the following piece of code 
List<String> imageStreamTags =
        imageStreams
            .stream()
            .filter(e -> e.getMetadata().getName().contains(imageTagTrimmed))
            .map(e -> e.getMetadata().getName())
            .collect(Collectors.toList());

We are checking for trimmed image tag in both the images streams and adding it to a list.
Now the list has 2 entries which enters the ELSE condition in the following code & throws exception

if (imageStreamTags.size() < 1) {
      throw new OpenShiftException(
          String.format("ImageStreamTag %s not found!", imageStreamTagName));
    } else if (imageStreamTags.size() > 1) {
      throw new OpenShiftException(
          String.format("Multiple ImageStreamTags found for name %s", imageStreamTagName));
    }

We should either increase the trim to 30 characters or have check which includes image stream name along with trimmed image tag.

**Comment by ibuziuk** [comment]
related rh-che issue - https://github.com/redhat-developer/rh-che/issues/334

**Comment by gorkem** [comment]
I can also reproduce this easily on minishift.

**Comment by ibuziuk** [comment]
PR with hot fix is sent - https://github.com/eclipse/che/pull/6604
Note that it will be possible to create Java-MySQl Multi Machine workspace only on minishift. 
Here is a separate issue for making  Java-MySQl stack usable on osio - https://github.com/redhat-developer/rh-che/issues/364

**Comment by ibuziuk** [comment]
PR is merged - closing
