### ISSUE TITLE
Populate rangeLenth on didChange

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6502]
When sending "didChange" notifications over LSP, we are currently sending the "rang", but not the "rangLength" field. Language servers (like jdt.ls) could assume rangeLenght to be valid if range is set, since this is not clearly specified in the LSP spec.
This is already done on the branch "5730_java_ls_poc", in commit 862b759597f94233e4a1c7e2c0f6eb4f30a574d1 . Since the jdt.ls work may take some time, it might make sense to cherry pick that commit onto master, though.

**Comment by bmicklea** [comment]
Please add the appropriate issue labels, not sure if this is a bug or enhancement for example.

**Comment by gazarenkov** [comment]
@tsmaeder labels?
https://github.com/eclipse/che/wiki/Labels
