### ISSUE TITLE
Updating project configuration does not immediately reflect to IDE

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#6512]
When I import a project to workspace with blank project type and then update its configuration to Maven. The java features are not enabled until IDE is reloaded. 

**Reproduction Steps:**
1. Create a workspace and import a project with a pom.xml . for instance https://github.com/gorkem/demo-j1-vertx
2. Observe that IDE is not aware of java packages and External Libraries is not present since this is a blank project type at this point
3. Open a Java file and observe that content assist does not work.
3. Use `Update Project Configuration...`to update project type to _Maven_
4. Observe that External Libraries are resolved and appears on the project explorer but the package structure is not update to the project explorer's tree. 
5. Observe that Java file still does not provide content assist. 
6. Reload the IDE (F5) and observe that both java package structure is visible on project explorer and content assist is functional.

**Comment by ghost** [comment]
Confirmed. By the way, External libs are updated just with jdk jars, so project deps are ignored. So, when updating a Maven project type, project tree should be updated as well and Maven update applied too.

**Comment by RomanNikitenko** [comment]
I'm closing the issue as 'Can not reproduce'
