### ISSUE TITLE
PostreSQL container doesn't stop gracefully on each stop of multi-user Che

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6530]
When multi-user Che is restarted it takes 3 minutes to stop PosgreSQL container. After 3 minutes it is killed by Docker compose. Docker Compose should be able to stop it gracefully.

**Reproduction Steps:**
1. Start multi-user Che.
2. Stop multi-user Che.

**OS and version:**    

**Diagnostics:**

**Comment by thyeun** [comment]
sorry, it this error already be fix on Che v5.19.0? due to that i'm still getting this error.

getting error message as below

ERROR: Error during graceful stop - see /home/thyeun/che/cli.log. (hint: --skip:graceful bypasses workspace stop)

**Comment by ghost** [comment]
@thyeun afaik, it's not fixed.

**Comment by riuvshin** [comment]
hello @thyeun, this will be fixed in 5.20.0, PR is already proposed.

**Comment by thyeun** [comment]
@riuvshin Che v5.20.0, i still need to use``` sudo docker run -it --rm -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop --skip:graceful```

to stop che after upgrade from v5.19.0 to v5.20.0

**Comment by riuvshin** [comment]
that is separate thing. this is expected behaviour for multi user as to stop it properly you have to authenticate CLI to perform graceful stop OR bypass it with `--skip:graceful`
Read CLI help for more explanation

**Comment by ghost** [comment]
@thyeun a graceful stop makes sure other ppl's workspaces are correctly stopped and not orphaned.

**Comment by thyeun** [comment]
@riuvshin , @.@ i given that comment because i already stop my workspace than only i stop it using CLI, but why i still need to put in ``` --skip:graceful``` .

**Comment by thyeun** [comment]
@eivantsov , only myself using Multi-user mode, and i have already stop my workspace but why i still need ```--skip:graceful```

**Comment by ghost** [comment]
@thyeun what error do you see when you do not skip graceful?

**Comment by thyeun** [comment]
@eivantsov 

> Wed Nov  1 08:31:14 UTC 2017
/usr/bin/curl  "-I -k https://hub.docker.com -s -o /dev/null --write-out %{http_code}"
Checking registry for version '5.20.0' images
eval BOOTSTRAP_IMAGE_ALPINE=${BOOTSTRAP_IMAGE_ALPINE:-alpine:3.4}
eval BOOTSTRAP_IMAGE_CHEIP=${BOOTSTRAP_IMAGE_CHEIP:-eclipse/che-ip:5.20.0}
eval IMAGE_INIT=${IMAGE_INIT:-eclipse/che-init:5.20.0}
eval IMAGE_CHE=${IMAGE_CHE:-eclipse/che-server:5.20.0}
eval IMAGE_CHE_MULTIUSER=${IMAGE_CHE_MULTIUSER:-eclipse/che-server-multiuser:5.20.0}
eval IMAGE_COMPOSE=${IMAGE_COMPOSE:-docker/compose:1.10.1}
eval IMAGE_POSTGRES=${IMAGE_POSTGRES:-centos/postgresql-96-centos7:9.6}
eval IMAGE_KEYCLOACK=${IMAGE_KEYCLOACK:-jboss/keycloak-openshift:3.3.0.CR2-3}
eval UTILITY_IMAGE_CHEACTION=${UTILITY_IMAGE_CHEACTION:-eclipse/che-action:5.20.0}
eval UTILITY_IMAGE_CHEDIR=${UTILITY_IMAGE_CHEDIR:-eclipse/che-dir:5.20.0}
eval UTILITY_IMAGE_CHETEST=${UTILITY_IMAGE_CHETEST:-eclipse/che-test:5.20.0}
eval UTILITY_IMAGE_CHEMOUNT=${UTILITY_IMAGE_CHEMOUNT:-eclipse/che-mount:5.20.0}
INFO: (che cli):  5.20.0 - using docker 17.05.0-ce / native
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/eclipse/che/tags/"
DEBUG: cmd_stop
docker inspect -f '{{.Id}}' che
/usr/bin/curl  "-I -k 172.18.0.1:8080/api/ -s -o /dev/null --write-out %{http_code}"
403
INFO: (che stop):  Stopping workspaces...
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-action:5.20.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-dir:5.20.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-test:5.20.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-mount:5.20.0'... found
[31mERROR:[39m (che action/graceful-stop): Call on rest url /api/system/state returned invalid response code (403) with error:<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.11 - Error report</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style> </head><body><h1>HTTP Status 403 - </h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><hr class="line"><h3>Apache Tomcat/8.5.11</h3></body></html>
ERROR: Error during graceful stop - see /home/thyeun/che/cli.log. (hint: --skip:graceful bypasses workspace stop)

**Comment by thyeun** [comment]
@eivantsov i stop the workspace till i see the green button turn back to gray color than i close the browser and only stop che using CLI, but i still need ```--skip:graceful```.

Question : once the green button turn gray, it is mean workspace already stop? or do i still need to wait certain time before i stop che using CLI? if your answer is yes, than it might be the issue, because after green button turn back to gray color, i did not wait.

**Comment by riuvshin** [comment]
this is how designed CLI, in case of multiuser mode and enabled auth to perform graceful stop you have to auth OR bypass it. that is not only matter of stopping workspaces but prepare whole system to graceful stop. So to stop it correctly you have to auth like `... stop -u admin -w admin` OR force shutdown with `--skip:graceful` 
btw this is absolutely not related to this issue.

**Comment by thyeun** [comment]
@riuvshin , question, where is your so call? ```stop -u admin -w admin``` appear from the link https://www.eclipse.org/che/docs/setup/cli/index.html ?

**Comment by thyeun** [comment]
@riuvshin i really dont understand what you mean by not related, why cant a CLI once i stop che with ```CHE_MULTIUSER=true``` it will automatically kill auth and all the system in one time, instead of i need to do things two time?

do you get what i mean or not?

**Comment by ghost** [comment]
@thyeun what things do you need to do two times?

**Comment by thyeun** [comment]
@eivantsov , as you can see the answer from @riuvshin, i need to perform auth kill than only without using ```--skip:gradeful```.

so, if my CLI with ```CHE_MULTIUSER=true```, it is so obvious that i want to stop multi-user mode, but why i still need ```--skip:graceful```.

An example : Once my CLI with multi-user true, ```sudo docker run -it --rm -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop``` 

than the command should automatically kill auth and stop che.

but now, the things are not that way, even i got the command line with multi-user true, but i still need to perform ```--skip:graceful```

**Comment by ghost** [comment]
`docker run -it --rm -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop --skip:graceful` or `docker run -it --rm -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop -u admin -w password` correctly stops everything.

**Comment by thyeun** [comment]
@eivantsov show you something

```docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop``` (this is stop che with single-user mode), am i right?

```docker run -it --rm -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop``` (why cant this stop everything including stop auth?)

do you see one got ```-e CHE_MULTIUSER=true``` and one dont have?

what i try to explain here is, once the command with ```docker run -it --rm -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop``` it should be done the things ```docker run -it --rm -e CHE_MULTIUSER=true -v /var/run/docker.sock:/var/run/docker.sock -v /home/thyeun/che:/data eclipse/che stop --skip:graceful```, instead that why still need ```--skip:graceful```
