### ISSUE TITLE
Allow adding new Logstash logback appenders to che-server tomcat logback.xml

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#6537]
At the moment, it is not possible to add logstash-logback appenders to logback.xml. It would be useful to just provide a proper logback-additional-appenders.xml and nothing else

**Reproduction Steps:**
Adding a logback-additional-appenders.xml like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<included>
    <appender name="file-json" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${che.logs.dir}/logs/catalina.log.json</file>
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
          <level>info</level>
        </filter>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${che.logs.dir}/archive/%d{yyyy/MM/dd}/catalina.log.json</fileNamePattern>
            <maxHistory>${max.retention.days}</maxHistory>
        </rollingPolicy>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
    </appender>

    <root level="${che.logs.level:-INFO}">
        <appender-ref ref="file-json"/>
    </root>
</included>
```
won't work at the moment

**Pull Requests**
- [x] https://github.com/eclipse/che-lib/pull/42
- [x] https://github.com/eclipse/che/pull/6539
- [x] https://github.com/eclipse/che-dependencies/pull/60
- [x] PR docs: https://github.com/eclipse/che-docs/pull/297

** PR for che6 **
- [x] https://github.com/eclipse/che-lib/pull/58
- [x] https://github.com/eclipse/che/pull/7415
- [x] https://github.com/eclipse/che-dependencies/pull/73

**Comment by skabashnyuk** [comment]
closing after discussion with @l0rd
