### ISSUE TITLE
The autosave feature works wrong with Editor panes

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6538]
**Reproduction Steps:**
1. Open any file in the **Editor**.
2. See that the **Enable Autosave** checkbox  in the **Preferences** -> **Editor** is checked.
3. Split pane in two rows or columns.
4. Do some changes in the file.

**Expected behavior:**
A marker for changes to the file appeared. Then the file will be saved and the marker will disappear.

**Observed behavior:**
The marker disappears only in the active panel. If click on another panel, the marker disappears and the file is saved again.
And the problem with the error markers in xml files. They will appear in other panes only after they become active.

**Che version:** 5.19.0-SNAPSHOT
**OS and version:** Fedora 25
![teams-11-13](https://user-images.githubusercontent.com/7760565/31114722-1a11b966-a828-11e7-82ad-c164e5738cf0.gif)
![teams-11-15](https://user-images.githubusercontent.com/7760565/31115124-bc4655ba-a829-11e7-88cc-247b28bd069b.gif)

**Comment by RomanNikitenko** [comment]
@SkorikSergey may be duplicate https://github.com/eclipse/che/issues/5497

**Comment by SkorikSergey** [comment]
Duplicated.
