### ISSUE TITLE
Che multiuser: Style organization email notifications

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#6546]
It is needed to apply Che style to organization email notifications. Now it is just plain text what is not good UX.

##### Member added to an Organization
![added_to_org](https://user-images.githubusercontent.com/5887312/31122482-b9b1706c-a844-11e7-8d6c-725796f76d36.png)

##### Member Removed from an Organization
![removed_from_org](https://user-images.githubusercontent.com/5887312/31122499-d0d01f32-a844-11e7-8b71-fe3e3f90b189.png)

##### Organization Renamed
![org_remaned](https://user-images.githubusercontent.com/5887312/31122510-d9f93666-a844-11e7-9f9b-d4a5fd96427c.png)

##### Organization Removed
![org_deleted](https://user-images.githubusercontent.com/5887312/31122503-d3b36fa6-a844-11e7-850b-fc6b59db3933.png)

**Comment by skabashnyuk** [comment]
@sleshchenko can you add existed examples so @slemeur  can help us with new styles ?

**Comment by ghost** [comment]
@sleshchenko @skabashnyuk @slemeur  should be probably reuse smtht that we use as KeyCloak email templates?

**Comment by slemeur** [comment]
Yes, we need to be consistent with the styles that we are using in "all" emails that we are sending. Reusing the styles we have defined for keycloak mails should be fine.

**Comment by mshaposhnik** [comment]
Added styles, but it looks ugly - seems we need more text:
Yahoo:

![mail_yahoo](https://user-images.githubusercontent.com/1651062/31178310-4ffb2c8e-a921-11e7-80ff-cd3b82fc3ddd.png)
Gmail:

![mail_gmail](https://user-images.githubusercontent.com/1651062/31178311-50074e88-a921-11e7-95a4-4189ad1587d5.png)
@slemeur can you provide a wider texts ?

**Comment by slemeur** [comment]
The texts are the one we used on Codenvy. They are short, but they are going to the point. We can move forward this way.

Ideally, admins from a multi-user Che should be able to modify those emails and style them the way they want (without having to rebuild a new custom Che)

**Comment by mshaposhnik** [comment]
Done in https://github.com/eclipse/che/pull/6584
