### ISSUE TITLE
Run As -> JUnit test works only if the project was built beforehand

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#6549]
`When I right click on and invoke Run JUnit Tests for a vertx booster project it executes and fails with No test found to run.Test suite is empty..`
In desktop IDEs building project manually before executing tests is not required.
Related rh-che issue https://github.com/redhat-developer/rh-che/issues/365
**Reproduction Steps:**
1. Start che and import vertx project with JUnit tests - https://github.com/openshiftio-vertx-boosters/vertx-http-booster
2. Once project is imported right click on it -> Run As -> JUnit test
3. ERROR: The following logs would be printed to the console

`No test found to run.Test suite is empty
`
4. Build the project and repeat step 2
5. SUCCESS: JUnit tests will be executed

**Comment by ibuziuk** [comment]
cc: @eivantsov

**Comment by ghost** [comment]
@ibuziuk yes, it's a known problem. At the moment, we're expecting test classes in target.

Take a look at https://github.com/eclipse/che/issues/5422

Running build automatically will solve the problem for small projects of course, but will make the feature barely usable for sizable ones.

afaik, jdt.ls will solve it for us.

**Comment by slemeur** [comment]
We need a short term solution for that, before we have the jdt.ls in place.

As a workaround, could we detect if the project has been built before executing the tests? And if not, then trigger the build?

**Comment by ghost** [comment]
@slemeur that will work just for demo projects. Detecting if there are test classes in target isn't a big deal.

**Comment by ibuziuk** [comment]
just seen the demo where JDT LS does the build for tests automatically https://youtu.be/zE9Cvu_u9-c

**Comment by ibuziuk** [comment]
Fixed after jdt.js switch - eclipse/che#6157
Closing
