### ISSUE TITLE
Implement required features for Resource API

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#6555]
Resource API should be able to calculate the amount of RAM that will be used by workspace after the start and the amount of currently used RAM by workspaces.
But such logic in commented in spi branch because it was designed to use docker workspaces only.
Calculating of RAM before workspace start is [here](https://github.com/eclipse/che/blob/master/multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/usage/tracker/EnvironmentRamCalculator.java#L46).
Calculation of used RAM by user's workspaces is [here](https://github.com/eclipse/che/blob/master/multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/usage/tracker/RamResourceUsageTracker.java#L80).
It is needed to implement in spi branch abstract entity which will be implemented by infrastructure. And then Resource API will be able to get needed values without depending on specific infrastructure.

**Comment by sleshchenko** [comment]
Is was decided to implement it in the following way:
1. Define constant in [Machine](https://github.com/eclipse/che/blob/6e9825c699d34eef6b8bf36fc0194ff871cbee84/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/runtime/Machine.java#L20) for storing the amount of RAM in machine properties.
2. Infrastructure should use a value from machine config attributes or use a default one if it is not specified while machine settings memory limit.
3. Infrastructure should return an amount of machine RAM in machines configs properties of the estimated environment and in machine description of runtime.

**Comment by garagatyi** [comment]
> Infrastructure should use a value from machine config attributes or use a default one if it is not specified while machine settings memory limit.

It also should respect environment type specific values in the recipe.
