### ISSUE TITLE
Workspace idle timeout in Che 5.18.0

### ISSUE THREAD

**Issue by pierbettassa** [eclipse-che/che#6564]
I upgraded my Che server from 5.14.0 to 5.18.0.
In the new version, there is an idle timeout that stops workspaces after one hour of inactivity. 
I would like to disable that timeout an let workspaces run forever.

**Reproduction Steps:**
Upgrade from 5.14 to 5.18:
`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/piergiuseppe_bettassa/che:/data -e CHE_HOST=10.8.0.1 eclipse/che:latest upgrade`
Init and config:
`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/piergiuseppe_bettassa/che:/data -e CHE_HOST=10.8.0.1 eclipse/che:latest init --force`
`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/piergiuseppe_bettassa/che:/data -e CHE_HOST=10.8.0.1 eclipse/che:latest config`

Run Che:
`sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/piergiuseppe_bettassa/che:/data -e CHE_HOST=10.8.0.1 -e CHE_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS=0 eclipse/che:latest start`

Tried with and without CHE_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS argument, and with the value set to 0 and greater than zero.  The workspaces always time out after 1 hour.

**OS and version:**    
Ubuntu 16.04 x86_64

**Diagnostics:** 
Output of  `docker run <DOCKER_OPTIONS> eclipse/che info`:

> CLI:
>  TTY:            true
>  Daemon:         /var/run/docker.sock
>  Image:          eclipse/che:latest
>  Version:        5.18.0
>  Command:        info
>  Parameters:     info
> Mounts:
>  /data:          /home/piergiuseppe_bettassa/che
>  /data/instance: not set
>  /data/backup:   not set
>  /repo:          not set
>  /assembly:      not set
>  /sync:          not set
>  /unison:        not set
>  /chedir:        not set
> System:
>  Docker:         native
>  Proxy:          not set
> Internal:
>  CHE_VERSION:    5.18.0
>  CHE_HOST:       10.8.0.1
>  CHE_INSTANCE:   /home/piergiuseppe_bettassa/che/instance
>  CHE_CONFIG:     /home/piergiuseppe_bettassa/che
>  CHE_BACKUP:     /home/piergiuseppe_bettassa/che/backup
>  CHE_REGISTRY:   /version
>  CHE_DEBUG:      false
>  IP Detection:   10.128.0.3
>  Initialized:    true
> Image Registry:
>  IMAGE_INIT=eclipse/che-init:5.18.0
>  IMAGE_CHE=eclipse/che-server:5.18.0
>  IMAGE_COMPOSE=docker/compose:1.8.1
>  IMAGE_TRAEFIK=traefik:v1.3.0-rc3
>  BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
>  BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.18.0
>  UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.18.0
>  UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.18.0
>  UTILITY_IMAGE_CHETEST=eclipse/che-test:5.18.0
>  UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.18.0
> che.env:
>  CHE_HOST=10.128.0.3
>  CHE_SINGLE_PORT=false

Output of  `sudo docker logs -f che` (see bold text at the end):
> Using embedded assembly...
> Found custom che.properties...
> 2017-10-03 19:37:47,762[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.11
> 2017-10-03 19:37:47,772[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Jan 10 2017 21:02:52 UTC
> 2017-10-03 19:37:47,772[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.11.0
> 2017-10-03 19:37:47,773[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
> 2017-10-03 19:37:47,774[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.10.0-35-generic
> 2017-10-03 19:37:47,778[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
> 2017-10-03 19:37:47,779[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
> 2017-10-03 19:37:47,779[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_111-internal-alpine-r0-b14
> 2017-10-03 19:37:47,780[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
> 2017-10-03 19:37:47,780[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/eclipse-che-5.18.0/tomcat
> 2017-10-03 19:37:47,780[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/eclipse-che-5.18.0/tomcat
> 2017-10-03 19:37:47,781[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dnop
> 2017-10-03 19:37:47,785[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
> 2017-10-03 19:37:47,786[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms512m
> 2017-10-03 19:37:47,789[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
> 2017-10-03 19:37:47,790[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
> 2017-10-03 19:37:47,791[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+HeapDumpOnOutOfMemoryError
> 2017-10-03 19:37:47,797[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseConcMarkSweepGC
> 2017-10-03 19:37:47,798[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+CMSParallelRemarkEnabled
> 2017-10-03 19:37:47,799[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseCMSInitiatingOccupancyOnly
> 2017-10-03 19:37:47,799[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+ScavengeBeforeFullGC
> 2017-10-03 19:37:47,803[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+CMSScavengeBeforeRemark
> 2017-10-03 19:37:47,803[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/conf
> 2017-10-03 19:37:47,804[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.docker.network=bridge
> 2017-10-03 19:37:47,804[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
> 2017-10-03 19:37:47,804[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/user/eclipse-che-5.18.0
> 2017-10-03 19:37:47,805[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/logs
> 2017-10-03 19:37:47,805[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
> 2017-10-03 19:37:47,806[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/eclipse-che-5.18.0/tomcat/conf/tomcat-logger.xml
> 2017-10-03 19:37:47,809[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
> 2017-10-03 19:37:47,813[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
> 2017-10-03 19:37:47,814[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
> 2017-10-03 19:37:47,815[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
> 2017-10-03 19:37:47,817[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
> 2017-10-03 19:37:47,818[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/conf
> 2017-10-03 19:37:47,818[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/eclipse-che-5.18.0/tomcat
> 2017-10-03 19:37:47,819[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/eclipse-che-5.18.0/tomcat
> 2017-10-03 19:37:47,825[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/eclipse-che-5.18.0/tomcat/temp
> 2017-10-03 19:37:47,993[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 525]  - Initializing ProtocolHandler ["http-nio-8080"]
> 2017-10-03 19:37:48,024[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
> 2017-10-03 19:37:48,029[main]             [INFO ] [o.a.catalina.startup.Catalina 617]   - Initialization processed in 1283 ms
> 2017-10-03 19:37:48,106[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port 32001 and the server on port 32101 for the Platform server
> 2017-10-03 19:37:48,107[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service Catalina
> 2017-10-03 19:37:48,110[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.11
> 2017-10-03 19:37:49,287[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/swagger.war
> 2017-10-03 19:37:49,590[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/swagger.war has finished in 300 ms
> 2017-10-03 19:37:49,596[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/ROOT.war
> 2017-10-03 19:37:50,326[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/ROOT.war has finished in 730 ms
> 2017-10-03 19:37:50,334[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/docs.war
> 2017-10-03 19:37:51,131[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/docs.war has finished in 796 ms
> 2017-10-03 19:37:51,133[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/dashboard.war
> 2017-10-03 19:37:51,652[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/dashboard.war has finished in 519 ms
> 2017-10-03 19:37:51,659[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/wsmaster.war
> 2017-10-03 19:38:05,595[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
> 2017-10-03 19:38:05,669[ost-startStop-1]  [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.0.3 by Boxfuse
> 2017-10-03 19:38:05,677[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
> 2017-10-03 19:38:05,763[ost-startStop-1]  [INFO ] [i.f.CustomSqlMigrationResolver 157]  - Searching for sql scripts in locations [classpath:che-schema]
> 2017-10-03 19:38:05,850[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 11 migrations (execution time 00:00.093s)
> 2017-10-03 19:38:05,913[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "PUBLIC": 5.11.0.1
> 2017-10-03 19:38:05,930[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Schema "PUBLIC" is up to date. No migration necessary.
> 2017-10-03 19:38:08,796[ost-startStop-1]  [INFO ] [e.c.a.w.s.i.ServerIdleDetector 57]   - Idling che server scheduled [timeout=1800] seconds]
> 2017-10-03 19:38:08,808[ted-scheduler-1]  [INFO ] [ockerAbandonedResourcesCleaner 126]  - List containers registered in the api: []
> 2017-10-03 19:38:09,753[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/eclipse-che-5.18.0/tomcat/webapps/wsmaster.war has finished in 18,094 ms
> 2017-10-03 19:38:09,770[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-8080]
> 2017-10-03 19:38:09,792[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 21756 ms
> 2017-10-03 19:38:23,948[nio-8080-exec-2]  [INFO ] [o.e.c.a.f.s.jpa.JpaFactoryDao 111]   - FactoryDao#getByAttributes #maxItems: 15 #skipCount: 0, #attributes: [{first=creator.userId, second=che}]
> 2017-10-03 19:40:11,521[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspacewad5faipgfchks2p
> 2017-10-03 19:40:13,754[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspacewad5faipgfchks2p
> 2017-10-03 19:40:15,913[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspacewad5faipgfchks2p
> 2017-10-03 19:41:04,125[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ssh' agent at workspace workspacewad5faipgfchks2p
> 2017-10-03 19:41:06,177[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ls.json' agent at workspace workspacewad5faipgfchks2p
> 2017-10-03 19:41:07,158[aceSharedPool-0]  [INFO ] [e.c.a.w.s.i.ServerIdleDetector 69]   - Idling che server canceled
> 2017-10-03 19:41:07,170[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 658]    - Workspace 'che/nodejs-dev' with id 'workspacewad5faipgfchks2p' started by user 'che'
> 2017-10-03 20:16:43,132[nio-8080-exec-8]  [INFO ] [o.e.c.a.f.s.jpa.JpaFactoryDao 111]   - FactoryDao#getByAttributes #maxItems: 15 #skipCount: 0, #attributes: [{first=creator.userId, second=che}]
> 2017-10-03 20:38:08,913[ted-scheduler-0]  [INFO ] [ockerAbandonedResourcesCleaner 126]  - List containers registered in the api: [/workspacewad5faipgfchks2p_machinefni36zp1jazsdfzm_che_dev-machine]
> 2017-10-03 20:44:09,109[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 700]    - Workspace 'che/nodejs-dev' with id 'workspacewad5faipgfchks2p' is being stopped by user 'activity-checker'
> 2017-10-03 20:44:09,136[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 855]   - Creating snapshot of workspace 'workspacewad5faipgfchks2p', machines to snapshot: '1'
> 2017-10-03 20:44:11,067[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 882]   - Saving new snapshots metadata, workspace id 'workspacewad5faipgfchks2p'
> 2017-10-03 20:44:11,116[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 887]   - Removing old snapshots binaries, workspace id 'workspacewad5faipgfchks2p', snapshots to remove '1'
> 2017-10-03 20:44:14,021[aceSharedPool-1]  [INFO ] [e.c.a.w.s.i.ServerIdleDetector 80]   - Idling che server scheduled [timeout=1800] seconds]
> **2017-10-03 20:44:14,022[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 733]    - Workspace 'che/nodejs-dev' with id 'workspacewad5faipgfchks2p' stopped by user 'activity-checker'**
> 2017-10-03 20:52:39,220[nio-8080-exec-6]  [INFO ] [o.e.c.a.f.s.jpa.JpaFactoryDao 111]   - FactoryDao#getByAttributes #maxItems: 15 #skipCount: 0, #attributes: [{first=creator.userId, second=che}]

```

**Comment by ghost** [comment]
@pierbettassa uncomment the following line in your che.env file 

`#CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS=0`

**Comment by pierbettassa** [comment]
Thanks @eivantsov, I solved the problem.
But the `che.env` file that I found in the root folder, after upgrading to 5.18, did not include the `CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS` variable.
I replaced it with with the `che.env` file that I downloaded from `https://raw.githubusercontent.com/eclipse/che/master/dockerfiles/init/manifests/che.env`, uncommented the line, ran `init` and `config` commands. Then it worked.
