### ISSUE TITLE
Creation of a new file in collapsed project cause hide of all project files

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#6569]
If create a file in project which is not unwrapped, all project items will be hide except new one.

**Reproduction Steps:**
1. Open an workspace with a project. Collapse the project.
2. Refresh page.
3. Create a new file using `Main Menu` -> `Project` -> `New` -> `File`.

**Actual behaviour:** The only created file is in project directory.

Screencast:
![pe-fce](https://user-images.githubusercontent.com/15607393/31167595-3ee341d2-a8fb-11e7-8089-1f55588dec6b.gif)

**Comment by SkorikSergey** [comment]
It appears that this issue is reproduced for the first created file after each update of the web page.

**Comment by musienko-maxim** [comment]
in che6 cannot reproduce

**Comment by mmorhun** [comment]
I made a bit imprecise description. Workspace shouldn't be just created. After creation, restart workspace or refresh page (without cache). The problem is still here.

**Comment by mmorhun** [comment]
Not actual for Che 7.
