### ISSUE TITLE
Cannot create a new stack

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#6571]
When creating a new stack, it does not apper in the stacks list. 'Save' button is disabled when editing stacks details.

**Reproduction Steps:**
1. In the dasboard click 'Stacks' tab.
2. Click 'Add Stack' button.
3. Make some changes.

Expected: 'Save' button must be active after changing stack details. The new stack must be present in the stacks list.
Wrong: 'Save' button is inactive after changing stack details. There is no new stack in the stacks list.

**OS and version:**    
Ubuntu 16.0.4 CHE 5.19.0-SNAPSHOT

**Diagnostics:**

**Comment by SkorikSergey** [comment]
The **Save** button inactive if change stacks name, description or runtime name. If add a **command** or change **category** then the **Save** button will enable, the stack can be saved and visible in the **Stacks** list. But stacks name, description or runtime name will not be saved.
![teams-11-21](https://user-images.githubusercontent.com/7760565/31169265-b46ce6d8-a900-11e7-9e58-35eaf1875bb1.gif)
