### ISSUE TITLE
[che-multiuser] Unable to deploy multiuser branch on minishift

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#6585]
Error during Postgres build:
error: build error: error copying source path /etc/puppet/modules/postgres/templates/init-che-user.sh.erb to ./: API error (404): {"message":"lstat /mnt/sda1/var/lib/docker/aufs/mnt/021359b12530f01e7de39dffe623857db6f37105d2d9b0b639076508f5eae0b2/etc/puppet/modules/postgres/templates/init-che-user.sh.erb: no such file or directory"}

Error during Keycloak build:
error: build error: error copying source path /etc/puppet/modules/keycloak/files/che/ to ./themes/: API error (404): {"message":"lstat /mnt/sda1/var/lib/docker/aufs/mnt/06cc3cde1c9286a7c90d120a372a1e0916fd0e6af2c2db574a0f82e5a106167c/etc/puppet/modules/keycloak/files/che/: no such file or directory"}

**Reproduction Steps:**
git clone multiuser branch from eclipse/che repository
set CHE_MULTI_USER=true
run deploy_che.sh

**OS and version:**    
macOS Sierra 10.12.6
minishift v1.2.0
docker version 17.09.0-ce

**Diagnostics:** 
I see docker itself seems to have an issue when executing COPY command.
https://github.com/docker/for-mac/issues/1922

**Comment by riuvshin** [comment]
@davidfestal is that fail that expected to happen for first time ?

**Comment by davidfestal** [comment]
no, not at all.

I'm surprised about this:

> git clone multiuser branch from eclipse/che repository

multi-user has been merged to master.

@hbhargav could you precise a bit more what you are cloning exactly ?

**Comment by hbhargav** [comment]
@davidfestal  

Clone was prior to merging multi-user to master.

I've downgraded docker/for-mac to 1.13.1 & able to run che locally, haven't tried the same on minishift yet.

**Comment by riuvshin** [comment]
I'm actually able to deploy multiuser on  minishift / ocp from master and even from che6 branch

**Comment by riuvshin** [comment]
I think that issue were actual when multiuser functionality was in branch which required some images like `init` to be rebuilt before deploy. Now it is in master and works with default images `nightly` so I don't think it is still actual.
I'm able to deploy che multiuser on OCP and minishift without any issues.
@hbhargav please feel free to reopen If you will be able to reproduce this.
