### ISSUE TITLE
documentation: Improving Incremental Builds out of date for GWT soft permutations

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-che/che#6601]
#4298 introduced a new way to generate IDE.gwt.xml, but the [documentation](https://www.eclipse.org/che/docs/assemblies/plugin-lifecycle/index.html#improving-incremental-builds) still refers to the old way.

Can these instructions be updated with the new way to turn on soft permutations?

**Comment by ghost** [comment]
@jonahkichwacoders yep, you are right.

https://github.com/eclipse/che-docs/pull/298
