### ISSUE TITLE
Migrate to the new generation gwt-maven-plugin

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#6602]
CQ:
- [x] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14390

Related to [Che 6](https://github.com/eclipse/che/tree/che6) branch only.
Should also fix #2595 

The goal of this task is migrate from the legacy [`org.codehaus.mojo:gwt-maven-plugin`](https://gwt-maven-plugin.github.io/gwt-maven-plugin/index.html) (aka Mojo's) to the new one - [`net.ltgt.gwt.maven:gwt-maven-plugin`](https://tbroyer.github.io/gwt-maven-plugin/index.html).

### Cons of the legacy plugin:
- since 7 Apr 2017 Mojo's maven plugin has been considered as a legacy;
- designed a long time ago when most of the GWT projects contained client, server and shared code within the same maven module. So the old plugin promotes hacking to make it work. E.g. it's really hard to configure launching Super DevMode from the command line regardless of the used IDE;
- Mojo's plugin is tightly linked to a specific version of GWT.

### Some of the advantages of the new plugin:
- the new plugin is considered as the new generation GWT maven plugin and it's strongly encouraged to use it instead of the legacy one;
- designed from the beginning with multi-module projects in mind and follows best practices;
- independent of the GWT version (should work with GWT version provided by the gwt-dev dependency).

### Opportunities Che will get with the new plugin:
- better UX for plugins' developers:
  - flexible options for generating GWT-module descriptors (.gwt.xml):
    - it may be generated automatically if you follow the provided layout
    - it may be generated from a template
    - `<inherits>` may be generated from the project's dependencies
- proceeding from the previous points we don't need to use our [GwtXmlGenerator](https://github.com/eclipse/che/blob/master/ide/che-core-ide-generators/src/main/java/org/eclipse/che/util/GwtXmlGenerator.java) with [exec-maven-plugin execution](https://github.com/eclipse/che/blob/0f0be98d0abf680a428553ebc4ba391ae32caad1/assembly/assembly-ide-war/pom.xml#L272-L285);
- correct work with multi-module projects, e.g., Super DevMode.

### To migrate to the new plugin we need:
- use [`gwt-lib`](https://tbroyer.github.io/gwt-maven-plugin/lifecycles.html) lifecycle/packaging for all artifacts with client code;
- use [`gwt-app`](https://tbroyer.github.io/gwt-maven-plugin/lifecycles.html) lifecycle/packaging for `assembly-ide-war`;
- slightly adapt projects structure according to the layout provided by the new `gwt-maven-plugin`;
- avoid using [GwtXmlGenerator](https://github.com/eclipse/che/blob/master/ide/che-core-ide-generators/src/main/java/org/eclipse/che/util/GwtXmlGenerator.java);
- get rid of Mojo's `gwt-maven-plugin`.

**Comment by benoitf** [comment]
I would add as well that with the new plugin and the new HEAD-MASTER branch of GWT (will be 2.8.2) we can use Java9 binaries to build the GWT modules.

https://github.com/gwtproject/gwt/milestone/18

**Comment by vparfonov** [comment]
@benoitf sorry but o miss your point about Java 9, you want to say what GWT 2.8.2 will support Java 9?

**Comment by vparfonov** [comment]
@benoitf  thanks for explanation

**Comment by azatsarynnyy** [comment]
Short status update.
The new gwt-maven-plugin is already in use for compiling IDE in Che 6 (see https://github.com/eclipse/che/pull/6822). So now we do not depend on the legacy gwt-maven-plugin.
Currently, I'm finalizing Che's maven modules adaptation for gwt-lib/gwt-app lifecycle.

**Comment by azatsarynnyy** [comment]
Has been done in https://github.com/eclipse/che/pull/7084
