### ISSUE TITLE
Synchronize list of repositories and the list of local changes

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#6608]
Epic: https://github.com/eclipse/che/issues/5128

1. Add the list of repository to the git panel:
![repositories](https://user-images.githubusercontent.com/7668752/31336878-82aa8b78-ad01-11e7-83a7-684060915e5c.jpg)
2. Select the first repo if there is no selection at all.
3. Synchronize list of local changes with selected repo.

**Comment by mmorhun** [comment]
done
