### ISSUE TITLE
One of project disappears from project explorer after 'Go back'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6613]
**Reproduction Steps:**
* Open the IDE and import project (e.g. https://github.com/artaleks9/java-multimodule)
* Perform `Go into` for `my-lib` module
* After that import a project again (e.g. https://github.com/artaleks9/java-multimodule2)
* Perform `Go back` for `my-lib` module

**Expected behavior:**
* Both projects should be displayed into project explorer

**Observed behavior:**
* the second project is not displayed into project explorer
* need to do refresh web page

**Che version:** 5.19.0
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![go-back-project](https://user-images.githubusercontent.com/5408906/31273593-094d4a60-aa98-11e7-9af5-8b2805670ec6.gif)

**Comment by musienko-maxim** [comment]
not actual for che6
