### ISSUE TITLE
Add "openshift" recipe processing on dashboard

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#6629]
Add one more environment manager implementation (along with docker and compose ones) for processing "openshift" recipe type. It should support machine adding, exposing ports, adding variables.

**Comment by slemeur** [comment]
Is this linked to an epic @ashumilova ?

**Comment by ashumilova** [comment]
@slemeur done

**Comment by ghost** [comment]
There are a few things to take note when implementing this feature:

1. Validation of a recipe just an yaml file
2. Validation of objects (currently there's a list of objects with pods)
3. Validate names and other values in pod spec.

**Comment by olexii4** [comment]
spent - 20days
