### ISSUE TITLE
The debugger does not stop a breakpoint in certain case

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#6640]
***Preconditions:***
1) Create a workspace base on java stack and clone the next test project: https://github.com/maxura/LambdaAndInnerClasses.git
2) Configure the project as maven if it need. Open ```/LambdaAndInnerClasses/src/main/java/test/App.java``` 
***Reproduction Steps:***
1. Build the project by command ```mvn -f ${current.project.path} clean install && java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y ${current.project.path}/target/*.jar```
2. Create debug connection for java (Run -> Edit  Debug Connection -> Java)
3. Set breakpoint in line 41 and Run -> Debug -> Remote Java
4. After stopping in the line 41 Click on remove all breakpoints button. Run -> End debug session
5. Build project by the command again, set breakpoint in the 41 line, set debug connection and wait the highlighter in the 41 position.
6. Set breakpoint in the line #53.
7. Click resume button
***Expected result:*** the breakpoint should be set in the 53 position
***Actual result:***  the breakpoint does not set, all active breakpoints become disable

**OS and version:**  Fedora 25, Chrome browser, CHE v.5.19.0
**Additional information:** related selenium test: **InnerClassAndLambdaDebuggingTest**

**Comment by tolusha** [comment]
@musienko-maxim 
Do we have selenium test ?

**Comment by musienko-maxim** [comment]
yes it is InnerClassAndLambdaDebuggingTest

**Comment by tolusha** [comment]
FQN recognized `test.App$MethodLocalInner`
FQN loaded `test.App$1MethodLocalInner`

**Comment by tolusha** [comment]
Duplicates https://github.com/eclipse/che/issues/4211
