### ISSUE TITLE
Apply new styles to the widget displaying local changes

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#6645]
Epic: https://github.com/eclipse/che/issues/5128

Apply new styles to the list of local changes
![Local changes styles](https://cloud.githubusercontent.com/assets/1636769/26212804/1f8deb32-3bf7-11e7-9106-e134bc094628.png)

**Comment by vinokurig** [comment]
Icons: [icons.tar.gz](https://github.com/eclipse/che/files/1372025/icons.tar.gz)
