### ISSUE TITLE
Unable to log in with a user if an organization with the same name already exists

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#6650]
### Description
Unable to log in with a user if an organization with the same name already exists.

### Reproduction Steps
1. Log in as admin.
2. Create an organization with some name e.g. `test`.
3. Log out.
4. Try to register a new user with the same name.
Expected: User is registered and logged in successfully or gets an error with the message that he has to use another username.
Actual: User is created on `keycloak` server but the dashboard is not opened because of error while importing `keycloak` user into `che-server` database because of name uniqueness constraint.

**Comment by riuvshin** [comment]
@skabashnyuk should we close issue?
