### ISSUE TITLE
Investigate problem of failing selenium tests from dashboard package on CI

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6655]
Selenium tests from dashboard package fail on CI because the main dashboard elements do not appear. This is not reproduced on local machines but actual on CI,  when we launch tests in the multithread mode

**Comment by musienko-maxim** [comment]
So, the reason looks like request on keycloak performs earlier than all elements of page become available. The Dashboard team have got required information and will have to fixed it.

**Comment by musienko-maxim** [comment]
In the https://github.com/eclipse/che/pull/6924 problem looks like fixed.
