### ISSUE TITLE
Replace JDT search & AST use with jdt.ls implementation

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6659]
The junit and testng plugins in Che use jdt search and AST support to find test cases in code. We need to move this support to jdt.ls. In particular:
1. Design a LSP extension that can fulfil the requirements of the test plugins. Ideally, this would be a start for an LSP extension that can be used from other clients, as well.
2. Implement the API in jdt.ls. We need to coordinate with @fbricon on how to do this: I think this would be a good case for an extension bundle to jdt.ls. If we do an extension, we need to set up a way to build and package the server + extension. 
3. Remove jdt from the testing plugin dependencies and use the new API.

**Comment by fbricon** [comment]
Building an extension on top of jdt.ls should be pretty straightforward, since we expose p2 repositories under http://download.eclipse.org/jdtls/snapshots/repository/

Designing a good API is the hardest part :-) Let's start by: what do you need?

**Comment by fbricon** [comment]
I'm thinking I could even make a Maven archetype to bootstrap jdt.ls extensions :-)

**Comment by tsmaeder** [comment]
I've filed https://github.com/eclipse/che/issues/6670 as a separate task.
