### ISSUE TITLE
[Regression] Not expected error message after succesful added command in the command explorer

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6675]
**Steps to reproduce:**
- Create workspace from java stack with default spring project
- Go to the commands explorer
- Click on "+" button in any goal ( "RUN", "BUILD" ... )
- Click on any type of commands ("GWT", "Maven", "Java" ... )
- Wait until command will be displayed
- Pay attention to the error message

**Expected behavior:**
Command is created and confirm message is displayed

**Observed behavior:**
Command is created but error message is shown

**OS and version:**
CHE 5.19.0 ; Ubuntu 16.04 ; Fedora 25 ; Chrome 59.0

**Attachment:**

![screenshot from 2017-10-11 12-19-56](https://user-images.githubusercontent.com/22724619/31436610-6fbd5816-ae8b-11e7-966f-5f55c9afd742.png)

![teams-11-26](https://user-images.githubusercontent.com/22724619/31437215-30dfe2d8-ae8d-11e7-8662-50c064c6829a.gif)

**Comment by RomanNikitenko** [comment]
Can not reproduce for 6.0.0-M5-SNAPSHOT

**Comment by Ohrimenko1988** [comment]
This bug is actual only for Che 5.xx versions since 5.19.0 and higher
