### ISSUE TITLE
Use jdt.ls for "usages" view

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6682]
Come up with a way to use LSP "references" infrastructure to implement the "usages" view. Particularly, we need to implement:
1. Tree view
We'll need to map the Locations (url, Range) to a tree of elements. We'll have to know how to parse JDT urls
2. Snippets
The usages view shows excerpts of the source text with the searched symbol highlighted. We will have to look at the source text to extract those.
3. Search only in source. Currently, jdt.ls also searches in application libraries (mvn dependencies, for example).

**Comment by gazarenkov** [comment]
@tsmaeder labels?
https://github.com/eclipse/che/wiki/Labels

**Comment by tsmaeder** [comment]
After some more investigation, I have come to the conclusion that it is not possible to implement the functionality of the "usages" view using only LSP protocol. The usages view shows a tree made of Java elements (types, methods, packages, etc.) We cannot easily reproduce this without parsing file contents, which would be overkill. 
It's probably best to port the code called from SearchJsonRpcService to the Che jdt.ls extension. Note that code in SearchManager is based on jdt.ui search, but I haven't seen anything that could not be done with pure jdt.core so far.

**Comment by tsmaeder** [comment]
Custom command is implemented.
