### ISSUE TITLE
Improve "references" and "declarations" LSP view

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6683]
We would like to support features like in the "usages" view of the current Java support the LSP references and declarations views. In particular
1. Tree view of matches instead of flat list
2. Showing excerpts of the source code showing the matches.

Language server plugins can contribute code to build paths and compute excerpts (optinal)

**Comment by gazarenkov** [comment]
@tsmaeder labels?
https://github.com/eclipse/che/wiki/Labels

**Comment by tsmaeder** [comment]
With the move to Theia, this optional task becomes irrelevant, closing.
