### ISSUE TITLE
Add python interactive environment with ability to "run selected lines"

### ISSUE THREAD

**Issue by jgbradley1** [eclipse-che/che#6685]
### Description
Currently when using the python stacks, users have two options:
* run the entire script
* run the script in debug mode (which only partially worked for me) stopping at breakpoints

I propose a feature where an interactive environment (possibly IPython) be made available. Allow users to highlight lines of code and add an option in the run menu to "run selected lines". Default behavior should be to send the selected lines to the currently running IPython session. The overall idea would be to mimic some of the **interactive** developer experience found in other IDEs like Spyder (or RStudio for the R community).

**Comment by ghost** [comment]
@jgbradley1 I'd label it as an enhancement to make it more visible for the community.

Implementation of such a feature would be an extension to python plugin. And IDE plugin that sends line for execution to virtual env.
