### ISSUE TITLE
[Regression] Cannot open files in the Editor from the Find panel

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6687]
**Reproduction Steps:**
1. Start a workspace from any stack with project.
2. Press Ctrl+Shift+F, type text for finding and click the **Search** button
3. Select any occurrence and double click on it.

**Expected behavior:**
File opened in the **Editor**

**Observed behavior:**
Nothing happens.

**Failed test:** FindTextFeatureTest

**Che version:** 5.19.0-SNAPSHOT
**OS and version:** Fedora 25
![teams-11-29](https://user-images.githubusercontent.com/7760565/31483862-cbaf13e8-af36-11e7-9640-882d5afcf2db.gif)

**Comment by riuvshin** [comment]
set as blocker because we can't ship in that state especially after adding pagination feature for search. @vparfonov please assign someone to this asap. Thanks
