### ISSUE TITLE
Error "unable to find user user"

### ISSUE THREAD

**Issue by t-moe** [eclipse-che/che#669]
Description of problem:  When creating a new project on step3 (Injecting and starting workspace agent) i get the error:

>  [STDERR] Unable to find user user

Che version: 4.0.0-RC13
Che install directory: ~/eclipse-che-4.0.0-RC13-SNAPSHOT
Docker version: 

> Client:
>  Version:      1.10.2
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   c3959b1
>  Built:        Mon Feb 22 21:30:48 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.10.2
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   c3959b1
>  Built:        Mon Feb 22 21:30:48 2016
>  OS/Arch:      linux/amd64

Java version: 

> java version "1.8.0_74"
> Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
> Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

Environment details (AWS, VirtualBox, physical, etc.):

> Kernel Version: 3.2.0-4-amd64
> Operating System: Debian GNU/Linux 7 (wheezy)
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 1.965 GiB
> The my user `foo` has the id 1000, and permissions to access docker.

Steps to Reproduce:
1. start che locally  `./bin/che.sh`  as user `foo`(id 1000)
2. create a new project from stack "node".
3. On step 3, you'll get the error: `[STDERR] Unable to find user user`

Other way to produce a similar error:
1. start che in a docker container using: `./bin/che.sh -i`
2. you will get the output

> Starting Che server in docker container named che.
> Found a container named che. Attempting restart.
> Successful restart of container named che. Restarting Che server...
> Unable to find user user

**Comment by ghost** [comment]
Interesting...

What if you run this image manually:

`docker run -ti codenvy/node bash`

Will you be able to enter a container as a user?

FYI, I was unable to reproduce it on a fresh Debian 8 instance with the latest Docker installed.

**Comment by t-moe** [comment]
If I run this manually I get into the shell of the container as expected.

How can I find out which steps are executed in "step3 injecting....". ?

This might be totally unrelated but: 
`./bin/che.sh -p:4433 -r:<IP> -d` 
gives me

> ERROR: transport error 202: bind failed: Address already in use
> ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
> JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
> FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
> ./bin/che.sh: line 461: 29564 Aborted                 "${ASSEMBLY_BIN_DIR}"/catalina.sh jpda ${CHE_SERVER_ACTION}

Where as starting it without the `-d` flag, raises no error.

**Comment by ghost** [comment]
When a workspace agent is injected, we unzip it from /mnt/che into /home/user/che - https://github.com/eclipse/che/blob/master/assembly/assembly-ide-war/src/main/java/org/eclipse/che/api/deploy/ApiModule.java#L125

Address already in use is quite self explaining - there seems to be a process listening on the debug port - 8000

**Comment by ghost** [comment]
Another text you can do is:

`docker run -d --name=test codenvy/node`
`docker exec test cat /etc/hosts`

The exec command can be anything you want. I want to make sure execs are working ok.

Looks like you have got an old Kernel. I suspect this may be related - https://github.com/RocketChat/Rocket.Chat/issues/1530

Can you run `uname -a`?

**Comment by t-moe** [comment]
```
$ docker run -d --name=test codenvy/node
$ docker exec test cat /etc/hosts
Unable to find user user
```

```
uname -a
Linux <HOSTNAME> 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u1 x86_64 GNU/Linux
```

**Comment by ghost** [comment]
It is a Kernel issue then. Docs docs say:

> Docker requires a 64-bit installation regardless of your Debian version. Additionally, your kernel must be 3.10 at minimum.

**Comment by t-moe** [comment]
You were right. I upgraded the kernel to 3.16 and now it works.
Thanks a lot!
