### ISSUE TITLE
[Multiuser] After registration user is redirected to the not working Dashboard

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6693]
**Reproduction Steps**
- Go to che-multiuser login page
- Click on "Register" link
- Fill in all fields
- Click "Register" button
- Pay attention to the screen

**Expected behavior**
New registered user will be redirected to the working dashboard

**Observed behavior**
New registered user is redirected to the not working dashboard

**OS and version:**    
Che(multiuser) 5.19.0 ; Fedora 25 ; Chrome 59.0

**Attachment**

![screenshot from 2017-10-12 12-30-22](https://user-images.githubusercontent.com/22724619/31489553-ad94c836-af49-11e7-80e0-96bb5bd2cb75.png)

**Comment by ghost** [comment]
```
<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.11 - Error report</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style> </head><body><h1>HTTP Status 500 - Unable to identify user a8081cfc-ee9c-4d0d-8ef5-22515673b4dd in Che database</h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u>Unable to identify user a8081cfc-ee9c-4d0d-8ef5-22515673b4dd in Che database</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b></p><pre>javax.servlet.ServletException: Unable to identify user a8081cfc-ee9c-4d0d-8ef5-22515673b4dd in Che database
	org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:96)
	org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:124)
	org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:60)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
</pre><p><b>root cause</b></p><pre>org.eclipse.che.api.core.ConflictException: User with such id/name/email/alias already exists
	org.eclipse.che.api.user.server.jpa.JpaUserDao.create(JpaUserDao.java:84)
	org.eclipse.che.api.user.server.UserManager.doCreate(UserManager.java:107)
	com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:62)
	org.eclipse.che.api.user.server.UserManager.create(UserManager.java:99)
	org.eclipse.che.multiuser.api.account.personal.PersonalAccountUserManager.create(PersonalAccountUserManager.java:57)
	com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:70)
	org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.getOrCreateUser(KeycloakEnvironmentInitalizationFilter.java:119)
	org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitalizationFilter.doFilter(KeycloakEnvironmentInitalizationFilter.java:86)
	org.eclipse.che.multiuser.keycloak.server.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:124)
	org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:60)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
</pre><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/8.5.11 logs.</u></p><hr class="line"><h3>Apache Tomcat/8.5.11</h3></body></html>
```

All requests to wsmaster return 500 the first time.

**Comment by ghost** [comment]
@atdhcs don't use M2 tag. You can try it with `eclipse/che:nightly`. Che6 has been merged to master.

**Comment by atdhcs** [comment]
Thanks. No luck, it's failing still...

ssh-keygen: generating new host keys: RSA1 DSA

[INFO] Scanning for projects...

[INFO]

[INFO] ------------------------------------------------------------------------

[INFO] Building Maven Stub Project (No POM) 1

[INFO] ------------------------------------------------------------------------

[INFO]

[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>

[INFO]

[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<

[INFO]

[INFO]

[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---

[INFO] Generating project in Batch mode

[INFO] Archetype defined by properties

Downloading: http://maven.codenvycorp.com/content/groups/public/org/eclipse/che/archetype/stacks-archetype/nightly/stacks-archetype-nightly.jar

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 2.013 s

[INFO] Finished at: 2017-12-21T19:25:20Z

[INFO] Final Memory: 11M/203M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.eclipse.che.archetype:stacks-archetype:nightly) -> [Help 1]

[ERROR]

    On Thursday, December 21, 2017, 6:13:31 AM PST, Eugene Ivantsov <notifications@github.com> wrote:  
 
 
@atdhcs don't use M2 tag. You can try it with eclipse/che:nightly. Che6 has been merged to master.

**Comment by atdhcs** [comment]
please ignore my other email. Thanks Eugene, will try and let you know.
    On Thursday, December 21, 2017, 11:29:27 AM PST, Scooby Doo <dscooby1960@yahoo.com> wrote:  
 
  Thanks. No luck, it's failing still...

ssh-keygen: generating new host keys: RSA1 DSA

[INFO] Scanning for projects...

[INFO]

[INFO] ------------------------------------------------------------------------

[INFO] Building Maven Stub Project (No POM) 1

[INFO] ------------------------------------------------------------------------

[INFO]

[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>

[INFO]

[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<

[INFO]

[INFO]

[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---

[INFO] Generating project in Batch mode

[INFO] Archetype defined by properties

Downloading: http://maven.codenvycorp.com/content/groups/public/org/eclipse/che/archetype/stacks-archetype/nightly/stacks-archetype-nightly.jar

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 2.013 s

[INFO] Finished at: 2017-12-21T19:25:20Z

[INFO] Final Memory: 11M/203M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.eclipse.che.archetype:stacks-archetype:nightly) -> [Help 1]

[ERROR]

    On Thursday, December 21, 2017, 6:13:31 AM PST, Eugene Ivantsov <notifications@github.com> wrote:  
 
 
@atdhcs don't use M2 tag. You can try it with eclipse/che:nightly. Che6 has been merged to master.

**Comment by atdhcs** [comment]
@eivantsov thanks for the quicker response. @skabashnyuk, @Ohrimenko1988 
I tried with eclipse/che:nightly and got the same error as I mentioned above. if you following the same 5 steps you can replicate it

Here is the db error from PostgreSQL after connecting to the container i retrieved.
ERROR:  duplicate key value violates unique constraint "index_usr_email"
DETAIL:  Key (email)=(erty@gmail.com) already exists.
STATEMENT:  INSERT INTO usr (id, email, name, password) VALUES ($1, $2, $3, $4)
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:  SELECT 1
DETAIL:  Key (email)=(erty@gmail.com) already exists.
STATEMENT:  INSERT INTO usr (id, email, name, password) VALUES ($1, $2, $3, $4)
ERROR:  current transaction is aborted, commands ignored until end of transaction block

**Comment by ghost** [comment]
Use a clean local data directory - the one you mount into :/data

**Comment by atdhcs** [comment]
Thanks @eivantsov. Yes I used clean local data dir initially. Since you said it retired again with new data dir and still got the same issue.

**Comment by ghost** [comment]
@atdhcs i cannot reproduce it. Are you certain you are running the latest version? I'd recommend removing all Docker images and start:

`docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/data -e "CHE_MULTIUSER=true" eclipse/che:nightly start`

**Comment by atdhcs** [comment]
@eivantsov. Interesting. My che.env is default, meaning no changes made.  I created new data dir, deleted all containers and images [docker rm $(docker ps -a -q) ,docker rmi $(docker images -q)] and ran with below command. still same issue...no luck..
docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=****.com  -v /var/run/docker.sock:/var/run/docker.sock -v /che-data-6:/data eclipse/che:nightly start

once the clean install is made...and i logged into keycloak as admin and toggle off "login with email"..see below and did the four steps mentioned below...
![image](https://user-images.githubusercontent.com/34726431/34309156-739c0074-e705-11e7-9731-a82e0864a9c5.png)

1)bringup che IDE using browser and register new user and can login successfully.

2) login in to keycloak as admin and delete the newly registered user.

3)bringup che IDE using browser and re register using same details used for previous registration ,

4) try to login and you get  user/exists error...

Any other info that you are looking for please let me know. Did you made any changes to che.env? . Mine is default one. should i have make any changes? one again thanks for looking into this @eivantsov.

**Comment by ghost** [comment]
@atdhcs yes, reproduced. Not sure if this is a Keycloak or Che bug. But we will take a look.

P.S. Most certainly a Che bug

**Comment by atdhcs** [comment]
Great that's good news @eivantsov. I have a feeling when Keycloak deletes a user, it's not reflected in usr table in db and next time when user tries to re-register, db throws below constraint exception.
 
If you change your email id while re-registering you can register successfully. 

ERROR: duplicate key value violates unique constraint "index_usr_email"
DETAIL: Key (email)=(erty@gmail.com) already exists.
STATEMENT: INSERT INTO usr (id, email, name, password) VALUES ($1, $2, $3, $4)
ERROR: current transaction is aborted, commands ignored until end of transaction block
STATEMENT: SELECT 1
DETAIL: Key (email)=(erty@gmail.com) already exists.
STATEMENT: INSERT INTO usr (id, email, name, password) VALUES ($1, $2, $3, $4)
ERROR: current transaction is aborted, commands ignored until end of transaction block

**Comment by skabashnyuk** [comment]
@eivantsov @atdhcs I think usecase with ```3 Delete the newly registered user``` is a bit different from original. Please consider opening the new issue.

**Comment by ghost** [comment]
Closed. Opened a new one https://github.com/eclipse/che/issues/8081
