### ISSUE TITLE
Trying to connect my github account produces a 404 page (from Github)

### ISSUE THREAD

**Issue by adam-buckley** [eclipse-che/che#670]
Hi everyone,

Description of problem: I've just downloaded and installed Che locally on my Mac, everything starts fine and I can create workspaces etc, but when I try to connect my Github account to import repos, I get a 404 page from Github, please see below.
![screen shot 2016-03-10 at 1 15 23 pm](https://cloud.githubusercontent.com/assets/1585392/13657302/4ba71120-e6c2-11e5-83c6-156b424cbabf.png)
It's probably worth noting that I'm _already signed into github in my browser_.

Che version: 4.0.0-RC11
Che install directory: /Users/adambuckley/work/eclipse-che-4.0.0-RC11
Docker version: 1.9.1
Java version: 1.8.0_40-ea
Environment details (AWS, VirtualBox, physical, etc.): Physical, locally on Mac OSX 10.10
How reproducible: Not sure
Steps to Reproduce: 
1. Download latest version of Che, install and start
2. Try to connect Github account
3. ????
Actual Results: 404 page from Github
Expected Results: Page requesting approval to connect Che

Kind regards,
Adam

**Comment by TylerJewell** [comment]
Hi Adam:  you still have to configure Che to support oauth with your credentials.  This info is unhelpfully buried in the configuration page of the Che docs.  We just committed an issued to master that detects this lack of configuration and informs you of how to configure it so that the 404 is less confusing.

**Comment by adam-buckley** [comment]
Aha, my apologies, didn't even think to RTFM. If anyone has the same issue, you can find the configuration setup at [https://eclipse-che.readme.io/docs/configuration](https://eclipse-che.readme.io/docs/configuration) under "GitHub oAuth".

Thanks Tyler
