### ISSUE TITLE
[CHE 6] Add environment variables configuration to Machine model

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6702]
### Description
We need to add an ability to set environment variables configuration in [machine config](https://github.com/eclipse/che/blob/che6/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/MachineConfig.java#L21).
I suggest next structure of the MachineConfig object:
```
{
    "installers" : [ ],
    "attributes" : { },
    "servers" : { },
    "env" : {
         "my_env1" : "value1",
         "my_env2" : "value2"
    }
}
```

**Comment by gazarenkov** [comment]
OK with this model extension, can we consider "env" name instead of "envVariables" though?

**Comment by garagatyi** [comment]
ok, I changed the issue description.
