### ISSUE TITLE
Terminal doesn't recieve Alt Gr characters

### ISSUE THREAD

**Issue by MattiJarvinen** [eclipse-che/che#671]
**Description of problem:**
Terminal doesn't receive "Alt Gr" characters like  | or \
AltGr characters work in code editor though.

Bug concerns Google Chrome. Firefox seems to work ok.

**Che version:** 
Version:4.0.0-RC12Revision :15571e40395fd7c8Build Time :2016-03-06 17:34:32
**Environment details (AWS, VirtualBox, physical, etc.):** 
Default PHP Stack from Che distribution
**How reproducible:** 
Always
**Keyboard layout:**
Finnish
**Browser:**
Chrome
**Steps to Reproduce:**
1. Create workspace with Che's PHP Stack
2. Create PHP Simple project https://github.com/che-samples/web-php-simple.git
3. Start PHP project
4. Open workspace terminal
5. Try to type in Alt Gr character like | or \

**Actual Results:**
No input
**Expected Results:**
Correct character entered

**Comment by ghost** [comment]
I can type \ using Finnish keyboard layout on Chrome, Ubuntu 14.04

What\s your OS?

**Comment by MattiJarvinen** [comment]
Windows 10

**Comment by ghost** [comment]
I'll check on a Win machine

**Comment by belnadris** [comment]
Hi everyone,

Same problem on W7 (Chrome).

**Comment by ghost** [comment]
@maximegris what is keyboard layout in your case?

**Comment by belnadris** [comment]
@eivantsov AZERTY (French)

**Comment by ghost** [comment]
Confirmed on Windows 10, Chrome. Cannot reproduce on Ubuntu, Chrome. So, OS-Browser specific issue.

**Comment by MattiJarvinen** [comment]
And only affecting the terminal in che. In code editor it works just fine.

Could it be related to ctrl + alt being sent from webkit browsers instead of altGraphKey?
http://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press

**Comment by TylerJewell** [comment]
@ddementieva - can you confirm that the issue still exists?

**Comment by ddementieva** [comment]
Confirmed. The bug is still there.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-951

**Comment by Leward** [comment]
@MattiJarvinen-BA The "€" symbol does not work well on french keyboard layout on code editor and terminal. The key combination is `Alt Gr` + `E`

However character such as `@~|` do work on text editor.

**Comment by samssann** [comment]
All of the `ALT` + `<symbol>` combinations work in the editor. But not in the terminal. Config #2752

**Comment by TylerJewell** [comment]
@bmicklea @jamesdrummond - let's consider this for 5.0.0-M7 or 5.0.0-M8.  The issue keeps coming up so it's affecting a larger group of people now.

**Comment by samssann** [comment]
In the meantime, one can always ssh into the workspace from your local terminal. Press SSH and follow the instructions.

![image](https://cloud.githubusercontent.com/assets/19807339/19287382/29792f6a-900a-11e6-90d8-941e449efe1f.png)
