### ISSUE TITLE
Temporary files doesent cleared by che-plugin-svn-ext-server

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#6716]
Found out that che-plugin-svn-ext-server doesn't clear temporary files
Over the time it may lead to out of disk space situation
In **/tmp** folder lots of floders like 
```
org.eclipse.che.plugin.svn.server.SubversionApiITest-1000244451859738986/
```

### Reproduction Steps
1. Run tests
2. Observe /tmp folder for leftovers

**OS and version:**    
Che/Codenvy 5.18.0

**Comment by tolusha** [comment]
Outdated.
Master branch doesn't contain svn plugin.
5.x version located in a maintenance branch.
