### ISSUE TITLE
[Multiuser] Workspace is not displayed and error message is not shown when choose more RAM than available

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6727]
### Reproduction Steps
- Go to dashboard and click "Workspaces" -> "add Workspace"
- Choose any stack and set for it more RAM than available
- Click on "Create" button
- Pay attention to the screen

**Expected behavior**
Error message is shown and stopped workspace is displayed in dashboard

**Observed behavior**
Error message is not displayed and created workspace is not shown in dashboard

**OS and version:**    
Che(multiuser) 5.19.0 ; Chrome 59.0 ; Fedora 25

**Comment by musienko-maxim** [comment]
Looks like not actual for che6

**Comment by ashumilova** [comment]
Hi, yes, the workspace creation is allowed even if there is less available RAM, than workspace needs, but this error is shown on workspace start in IDE, workspace details page, workspace list page. What can be done to improve the flow - warn user about the RAM - not error , but warning message.
