### ISSUE TITLE
Is it possible to use Sonarqube with Eclipse Che?

### ISSUE THREAD

**Issue by synergiator** [eclipse-che/che#673]

**Comment by ghost** [comment]
Can you elaborate on how you see the ideal use-case?

**Comment by ndlu2** [comment]
Sonarqube is a useful tool for looking at and visualizing code quality. 

Here's an example of an large open source project that uses sonarqube
https://ci.openmrs.org/sonar/

**Comment by synergiator** [comment]
Well I would say, the ideal use case is to have access to a series of Maven prototype based project templates with built-in Sonarqube integration as a basic feature. The sexy thing about Sonarqube is that it can inject quality hints just in time into the editor view, just like we know it from Java grammar hints in Eclipse. There is a standard Sonarqube container available, so I think the feature is feasible.

Screenshot how it looks like in the classical Eclipse IDE: 
http://vitalflux.com/wp-content/uploads/2014/09/sonarqube-analysis-in-eclipse.png

Background information to extend ndlu2's comment:
Screenshot of large-scale OSS deployment of Sonar (JDK7 is green, good for all of us who codes in Java ;)
https://jaxenter.com/wp-content/uploads/2012/06/treemap-sonar.png

**Comment by TylerJewell** [comment]
Going to close this as it was more of a support ticket than an enhancement request.  We can reopen this if there is strong community support and we can get a detailed set of specifications on what may be implemented.
