### ISSUE TITLE
[CHE6] Rename environment variable with machine token to CHE_MACHINE_TOKEN

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#6730]
Now machine token is provided for agents as `USER_TOKEN` environment variable.  But it would be much better to name it as `CHE_MACHINE_TOKEN`. I'd indicated that it is token for accessing to agents in machine/for accessing to wsmaster from MACHINE. It is also needed to rename the corresponding field in `RuntimeDto` from `userToken` to `machineToken`.

**Comment by davidwindell** [comment]
@sleshchenko this one had me stuck after upgrading to v6, is there any BC break list anywhere to save scouring issues?

**Comment by sleshchenko** [comment]
@davidwindell :worried:  no, we don't have such list.
