### ISSUE TITLE
Workspace not change his status after starting

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6731]
### Reproduction Steps
- Create and run any workspace 
- Not do any actions and wait until workspace will be started
- Pay attention that workspace status in dashboard is not changed

**OS and version:**    
Che(multiuser) 5.19.0 ; Fedora 25 ; Chrome 59.0

**Attachment**

![eclipse che wksp u7sy](https://user-images.githubusercontent.com/22724619/31545745-49b40332-b029-11e7-9f31-151ffcbaf0d0.png)

**Comment by musienko-maxim** [comment]
For che6 is not actual
