### ISSUE TITLE
[CHE6 branch] Unexpected error notification when create command

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6734]
**Reproduction Steps:**
* Create a project in the IDE
* Create a new command from command explorer (e.g. `newJava` command)

**Expected behavior:**
*  should not be displayed any error notification after create the command

**Observed behavior:**
* command is created, but there is an error notification

**Che version:** 5.19.0
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Related selenium test `ConfigureSomeSourceFoldersTest`(_need to delete the workaround after resolve)_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![error-mess-create-comm](https://user-images.githubusercontent.com/5408906/31547703-015d36b4-b031-11e7-8b6a-63cde7a0e088.png)

**Comment by Ohrimenko1988** [comment]
Is this a duplicate ? 
https://github.com/eclipse/che/issues/6675
