### ISSUE TITLE
[CHE6 branch] Git color for files works incorrectly

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#6741]
**Reproduction Steps:**
* Open a project in the IDE and open  files (e.g. web-java-spring)
* Add some changes to files and commit them

**Expected behavior:**
* the color of files should be changed immediately

**Observed behavior:**
* the color of files is not changed
* it is changed after refresh web page

**Che version:** 5.19.0
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Related selenium test: _GitColorsTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![git-colors-1](https://user-images.githubusercontent.com/5408906/32098957-080896f2-bb17-11e7-82ce-75f08b6a9813.gif)

**Note:**
* sometimes the same behavior is had for git marker in the editor
* related selenium test: _GitChangeMarkersTest_
* see the attachment:
![git-marker](https://user-images.githubusercontent.com/5408906/32374435-54111e68-c0a6-11e7-8652-5278dcc08884.png)
_

**Comment by tolusha** [comment]
Missed JSON RPC channel initialization. Might be merge issue.
