### ISSUE TITLE
Implement Move Refactoring

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6748]
Implement "move" refactoring as in current Che Java support in the Che jdt.ls extension. The idea is to extend WorkspaceEdit objects with the possibility to move/rename files.
See also https://github.com/Microsoft/language-server-protocol/issues/272
Once we get extended workspace edits, we need to 
1. Implement a service that can apply those across open editors and files in the workspace
2. Adapt the refactoring UI we have now to use those edits.

**Comment by gazarenkov** [comment]
@tsmaeder labels?
https://github.com/eclipse/che/wiki/Labels

**Comment by svor** [comment]
PRs:
- https://github.com/eclipse/che/pull/9953
- https://github.com/eclipse/che-ls-jdt/pull/51
- https://github.com/eclipse/eclipse.jdt.ls/pull/683
