### ISSUE TITLE
Can't create workspace in Che 5.19.0 behind proxy

### ISSUE THREAD

**Issue by bs-matil** [eclipse-che/che#6749]
### Description
Can't get a workspace running with http proxy enabled. To me it looks a lot like the no_proxy setting has been ignored within the che server code.

#### Environment:
Start eclipse che behind a http proxy (Port 1234. IP 1.3.4.5) 

**Proxy in che container**

```

JAVA_HTTP_PROXY_PORT=-Dhttp.proxyPort=1234
JAVA_HTTP_PROXY_HOST=-Dhttp.proxyHost=1.3.4.5
JAVA_HTTPS_PROXY_HOST=-Dhttps.proxyHost=1.3.4.5
JAVA_HTTPS_PROXY_PORT=-Dhttps.proxyPort=1234
JAVA_HTTP_PROXY_SET=-Dhttp.proxySet=true
CHE_WORKSPACE_JAVA_OPTIONS=-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom -Dhttp.proxySet=true -Dhttp.proxyHost=1.3.4.5  -Dhttp.proxyPort=3128 -Dhttps.proxyHost=1.3.4.5 -Dhttps.proxyPort=1234 -Dhttp.nonProxyHosts='che-host||1.3.4.5|localhost|


```

**Proxy in che container**

```

http_proxy=http://1.3.4.5:1234/
https_proxy=http://1.3.4.5:1234/
no_proxy=che-host,,1.3.4.5,localhost

```

Steps
1. Create a Workspace
2. tail the log of container "che"

Result:
che workspace does not boot up. 

### Reproduction Steps
create a workspace behind a http proxy

**OS and version:**   
5.19.0
ubuntu 
docker 17.03.ce 

**Diagnostics:** 
```
2017-10-16 12:53:13,870[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspace20zt3gxmcn724j5z
2017-10-16 12:53:16,170[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspace20zt3gxmcn724j5z
2017-10-16 12:53:30,695[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspace20zt3gxmcn724j5z
2017-10-16 12:53:32,922[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspace20zt3gxmcn724j5z
2017-10-16 12:53:35,104[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspace20zt3gxmcn724j5z
2017-10-16 12:53:36,146[aceSharedPool-0]  [WARN ] [a.a.s.WsAgentHealthCheckerImpl 63]   - Failed to get machine token
java.io.IOException: Failed access: http://localhost:8080/api/machine/token/workspace20zt3gxmcn724j5z?token, method: GET, response code: 502, message: <html><body><h1>502 Connection refused</h1><p>
```

HINT: The connection refused message was returned by the proxy. So the proxy is called but it should be localhost.

**Comment by garagatyi** [comment]
Hi. Is CHE_HOST set in your che.env?  Looks like it is set to localhost

**Comment by bs-matil** [comment]
Hi. I'll look into it but anyways it should work dosn't it? 
```

/tmp/data/che.env  | grep CHE_HOST
#     line with '-e CHE_HOST=<value>'.
CHE_HOST=10.0.2.15

```

```
bash-4.3# docker exec -ti che bash
bash-4.3# env | grep CHE_HOST
CHE_HOST_COMPOSE_FILE=docker-compose.yml
CHE_HOST_OFFLINE_FOLDER=/tmp/data/backup
CHE_HOST_ENV=
CHE_HOST_PROTOCOL_ENV=http
CHE_HOST=10.0.2.15
CHE_HOST_CONFIG_MODULES_FOLDER=/tmp/data/instance/modules
CHE_HOST_PROTOCOL=http
CHE_HOST_BACKUP=/tmp/data/backup
CHE_HOST_CONFIG_MANIFESTS_FOLDER=/tmp/data/instance/manifests
CHE_HOST_INSTANCE=/tmp/data/instance
CHE_HOST_LOCAL=10.0.2.15
CHE_HOST_CONFIG=/tmp/data

```

**Comment by garagatyi** [comment]
Can you grep your che.env for localhost results?

**Comment by bs-matil** [comment]
```
root@tim1be-VirtualBox:~# cat  /tmp/data/che.env  | grep -i localhost
CHE_NO_PROXY=localhost,10.0.2.15
CHE_WORKSPACE_NO__PROXY=che-host,localhost,10.0.2.15
```

**Comment by garagatyi** [comment]
Looks like a bug. I'll add labels.
@eivantsov can you take a look, maybe you have any ideas?

**Comment by bs-matil** [comment]
I can confirm that the issue is not related to the Multi User Che option at all. Its the same without multi user che

**Comment by bs-matil** [comment]
I can confirm that the issue can be fixed by removing the doubled comma if you haven't had a no_proxy setting upfront 5.19.0 

example
 ```
no_proxy=che-host,,1.3.4.5,localhost
```
to
```
no_proxy=che-host,1.3.4.5,localhost
```

But this still leaves open why che_host isn't used at all

**Comment by ghost** [comment]
@bsukramlitt what do you mean CHE_HOST isn't used?

**Comment by bs-matil** [comment]
That interal API calles within the Webservice Master are not done through che_host:8080/api/.. they are done with localhost:8080/api/..

**Comment by AndrienkoAleksandr** [comment]
Did you uncomment property CHE_HOST in the che.env  (remove "#") ?

**Comment by ghost** [comment]
@bsukramlitt this is because, endpoint used for those calls is defined with a named property `che.api` + which is `http://localhost:${SERVER_PORT}/wsmaster/api` by default in Che properties - https://github.com/eclipse/che/blob/master/dockerfiles/init/manifests/che.env#L194

**Comment by bs-matil** [comment]
Thats a good hint. I'll try this setting.
@AndrienkoAleksandr: see my other comments

```

/tmp/data/che.env  | grep CHE_HOST
#     line with '-e CHE_HOST=<value>'.
CHE_HOST=10.0.2.15

``

**Comment by ghost** [comment]
Please see my reply above

**Comment by bs-matil** [comment]
@eivantsov thanks for your advice it works so far. Still I think there is a bug in the generation of the che.env if no_proxy is not set.

**Comment by ghost** [comment]
Why is that?

**Comment by bs-matil** [comment]
because my che server had the env:
no_proxy=che-host,,1.3.4.5,localhost 

and the che.env was like
`CHE_WORKSPACE_JAVA_OPTIONS=-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom -Dhttp.proxySet=true -Dhttp.proxyHost=1.3.4.5  -Dhttp.proxyPort=3128 -Dhttps.proxyHost=1.3.4.5 -Dhttps.proxyPort=1234 -Dhttp.nonProxyHosts='che-host||1.3.4.5|localhost|`

both:
`-Dhttp.nonProxyHosts='che-host||1.3.4.5|localhost|'`
and 
`no_proxy=che-host,,1.3.4.5,localhost `

caused issues. As they seem not to be valid no_proxy configurations. 
Ans this configuration had been generated by the che cli so it didn't respected the fact that there is no no_proxy set.

**Comment by ghost** [comment]
@bsukramlitt probably because of two commas?

**Comment by bs-matil** [comment]
@eivantsov 
Thats exactly what I want to say. This commas are the problem but I didn't put them in there. Its the code of che which generates this wrong config file because no_proxy=""

**Comment by ghost** [comment]
Do you have no_proxy for docker daemon?

Can you run docker info please?

**Comment by bs-matil** [comment]
in any context also the docker daemon the no_proxy setting was not set. 
(In the meanwhile I changed it. to no_proxy=localhost)

**Comment by ghost** [comment]
Was it unset ot set to an empty string?

**Comment by bs-matil** [comment]
unset

**Comment by bs-matil** [comment]
that's what confuses me 
And we had the exact same behaviour  on two completely independent systems which different docker versions and configurations.

**Comment by ghost** [comment]
@bsukramlitt is it fixed by setting no_proxy for Docker daemon?

**Comment by bs-matil** [comment]
yes then the initial config is created correct.

**Comment by ghost** [comment]
Found a bug. PR submitted. Thanks for noticing it.

**Comment by bs-matil** [comment]
@eivantsov 
Thanks!

**Comment by ghost** [comment]
PR merged, closing the issue.
