### ISSUE TITLE
Move support for "libraries" to Che jdt.ls extension

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6751]
There are services for getting classpath entries and for getting children of stuff in jars (ClasspathService, JavaNavigationService). 
Move the code in question to the Eclipse Che extension and make available via a custom command.

- [x] Getting  classpath entries 5SP
- [x] Getting children in jars 5SP

**Comment by gazarenkov** [comment]
@tsmaeder labels?
https://github.com/eclipse/che/wiki/Labels
