### ISSUE TITLE
Use LSP for file structure view.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6752]
Use symbol data from LSP textDocument/symbol data for displaying the file structure view. jdt.ls will add a second call for inherited symbols. We can determine the tree structure by looking at containment of the text ranges and the parent name field.
See also https://github.com/eclipse/eclipse.jdt.ls/issues/366

**Comment by gazarenkov** [comment]
@tsmaeder labels?
https://github.com/eclipse/che/wiki/Labels

**Comment by tsmaeder** [comment]
While the case without inherited members can be solved by looking at the containment hierarchy, that is not the case when inherited symbols come into play. 
One problem is that the locations of the inherited members are outside of the original compilation unit, so using containment to map to a unique parent is not possible anymore. The second problem is that we don't have a unique parent for symbols: the method Object#equals() will be in the inherited symbols of every type in the file structure hierarchy.
The solution I envision is to have a custom command that returns an extended SymboIInformation object including children like so:
```{
   "name": "MyClass",
   ...
   "children": [
       ...
   ]
}
```
The command would be located in the jdt.ls extension and be proxied in the wsagent.

**Comment by tsmaeder** [comment]
Note that the current file structure view has a couple of weaknesses, for example it only shows the main type in a compilation unit, and it switches between inherited members and without every time you open it.
