### ISSUE TITLE
[Regression] Cursor returns to top of file

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6753]
As per previous issues #5850 #6043, since Che 5.19 we are seeing the cursor jump to the top of the file when switching away from the file and back. 

To reproduce, open a two files, make a change in one and leave the cursor at that position. Switch to the first file, then switch back - the cursor returns to the top of the file.

**Comment by slemeur** [comment]
@vparfonov + @dkuleshov : Could you please give a look at that bug?

**Comment by davidwindell** [comment]
Just to add, this also affects the search which no longer jumps to the correct line when clicking a result.

**Comment by dkulieshov** [comment]
Hi,
Thank you for the bug report. If I remember well, in 19th version there were changes in this area, I guess we can ask @RomanNikitenko may be he can give a quick review.

**Comment by dkulieshov** [comment]
By the way I can't reproduce it locally.

**Comment by RomanNikitenko** [comment]
@davidwindell Do you do the same steps to reproduce it?
![cursorbug](https://user-images.githubusercontent.com/5676062/31663218-f7044718-b349-11e7-8d1a-f6d6d7b74cc9.gif)
It's not reproduced on my side, so I can't investigate cause of the problem. 
Could you add project/folder/files to file watcher excludes and try again - it may tell us if file watchers are involved.

**Comment by davidwindell** [comment]
We've switched to multi-user CHe now and can't reproduce at the moment.
