### ISSUE TITLE
Slow workspace startup caused by chmod

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6755]
Please could someone kindly explain what the purpose of [this chmod](https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.script.sh#L65) line in the ws-agent startup is? 

`find /projects -type d -exec ${SUDO} chmod 755 {} \;`

We run on EBS so IO is not as good as local and with our very large projects, this can take some time to complete making WS startup slow.

Why do all workspace sub directories need to be 755 and have that done to them on *every* startup?

**Comment by garagatyi** [comment]
@riuvshin Can you take a look at this question?

**Comment by ghost** [comment]
@davidwindell it is done to avoid the problem of uid mismatch. A user in a workspace container has uid 1000 while your local user may have different uid. When projects are volume mounted, they are mounted with your local uid. As a result if uid in a workspace and a local one do not match, a user in a container does not have write access to `/projects`.

But I wonder what `chmod` is added... looks like chown should be enough...

**Comment by riuvshin** [comment]
+1, `chown` should be enough here. 
Moreover we should not apply chmod to `/projects` because it change original user files mode and in some cases that could break user project. That line looks very strange...

**Comment by davidwindell** [comment]
I see, so this really is only for people who are running Che locally (not cloud based where all files are created in Che anyway).

This should really be optional, perhaps via a config flag. `chown` would also interfere with the source filesystem.

**Comment by ghost** [comment]
chmod removed

**Comment by davidwindell** [comment]
@eivantsov is the `chown -R $(id -u -n) /projects` still necessary (it's not for us at least) or can it be made optional somehow?

**Comment by ghost** [comment]
In 90% of cases it's not necessary. If local uid is 1000 or a local user is root, then there can be potential issues. I will run some tests and update the issue with results.

**Comment by davidwindell** [comment]
Thanks, it's just a bit of a pain with EBS/lots of files performance wise although I appreciate it's a difficult balance.

**Comment by adoukkali** [comment]
Hi, 
I am experiencing a huge slowness with chown when starting up the workspace (worth to mention that my project + its build has a lot of files , ~2go).
is it possible to disable the chown at the startup ?

**Comment by eivantsov** [comment]
@adoukkali I think I'll issue a pr that will add a check to run chown only if there's a real need to do so
