### ISSUE TITLE
The "Typescript" template creates the empty folder

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6757]
### Reproduction Steps
- Create workspace with Typescript language server
- Wait until workspace will be ran 
- Click on "Create project" link in the project explorer
- In the opened "Create New Project" window choose "TypeScript project" set the project name and click "Create" button
- Click twice on the created project in the project explorer
- Pay attention to the folder content

**Expected behavior:**
Project will be include files  

**Observed behavior:**
The empty folder is created

**OS and version:**    
Che 5.19.0 ; Chrome 59.0 ; Fedora 25

**Attachment**

![screenshot from 2017-10-17 12-44-24](https://user-images.githubusercontent.com/22724619/31658178-060d3ece-b339-11e7-98d7-09c3288de2c1.png)

**Comment by musienko-maxim** [comment]
This is not actual for che6
