### ISSUE TITLE
[REGRESSION] import from github does not work if ssh key  wasn't added before

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#6765]
can be reproduced on che / che-multiuser / codenvy
steps to reproduce:
1) open IDE 
2) go to Workspaces > Import project
3) select `GITHUB` and click `Load Repo`
4) chose any loaded repo and click `import`
expected behaviour:
ssh key will be added for github and project will be imported
actual results:
error:
<img width="1680" alt="screen shot 2017-10-17 at 3 21 49 pm" src="https://user-images.githubusercontent.com/1636732/31664889-c7760c42-b34f-11e7-82d2-32d8823e0c11.png">

**NOTE:** **_Import works OK if ssh key for git hub added first manually from preferences._**

**Comment by vparfonov** [comment]
Fixed in https://github.com/eclipse/che/issues/7061

**Comment by riuvshin** [comment]
@artaleks9 steps to reproduce are the same?

**Comment by artaleks9** [comment]
Yes, the same
