### ISSUE TITLE
Assembly created from plugin-serverservice-archetype doesn't work in 5.19.0

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#6766]
### Description

I try to run a custom assembly created from the plugin-serverservice-archetype and it fails when I try to open a workspace: I see the flashing workspace icon which appears before the IDE layout is loaded and that's it. 

### Reproduction Steps
I have created an archetype like this:

mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeRepository=http://maven.codenvycorp.com/content/groups/public -DarchetypeGroupId=org.eclipse.che.archetype -DarchetypeArtifactId=plugin-serverservice-archetype -DarchetypeVersion=5.19.0 -DgroupId=com.sample -DartifactId=assembly -Dversion=5.19.0 -DinteractiveMode=false

and I can build an assembly for that with mvn install in the root.

Now I run this with:

docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v <path_to_the_archetype_assembly>:/assembly -v <mydatalocation>:/data eclipse/che-cli:5.19.0 start

When opening a workspace it gets stuck with the flashing workspace icon but never proceeds to the workbench.
I was able see a 404 for this URL: http://<my-che-machine>:8080/che/wksp-pzqs?uid=220766 in my browser at that point.

The same works with 5.17.0.

**OS and version:**  
Linux / Ubuntu in Virtualbox.  All operations done in the VM.

**Diagnostics:** 

The root cause seems to be that _app/IDE.html (new between 5.17. and 5.19, replaces IDE.jsp) is not included in the custom assembly. I added:

<include>_app/IDE.html</include>

in the overlay configuration of the maven-war-plugin in the assembly-ide-war/pom.xml and then it worked.

**Comment by ghost** [comment]
@ChristianSchenk711 indeed, archetypes weren't updated. Thanks for reporting it.

@skabashnyuk @mkuznyetsov i think it's for you guys to handle.

**Comment by benoitf** [comment]
I will look at it

**Comment by ghost** [comment]
@benoitf thanks. Things like that remained https://github.com/eclipse/che-archetypes/blob/master/plugin-menu-archetype/src/main/resources/archetype-resources/assembly-che/assembly-ide-war/pom.xml#L210

**Comment by skabashnyuk** [comment]
```
8:27:34]sj:che-archetypes[master]#: git grep jsp
plugin-embedjs-archetype/src/main/resources/archetype-resources/assembly-che/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-embedjs-archetype/src/main/resources/archetype-resources/assembly-codenvy/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-json-archetype/src/main/resources/archetype-resources/assembly-che/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-json-archetype/src/main/resources/archetype-resources/assembly-codenvy/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-menu-archetype/src/main/resources/archetype-resources/assembly-che/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-menu-archetype/src/main/resources/archetype-resources/assembly-codenvy/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-serverservice-archetype/src/main/resources/archetype-resources/assembly-che/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-serverservice-archetype/src/main/resources/archetype-resources/assembly-codenvy/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-wizard-archetype/src/main/resources/archetype-resources/assembly-che/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
plugin-wizard-archetype/src/main/resources/archetype-resources/assembly-codenvy/assembly-ide-war/pom.xml:                                <include>IDE.jsp</include>
```
This is a cause.

**Comment by benoitf** [comment]
I merged PR that fixes the issue, using 5.20-SNAPSHOT should fix the issue on your side @ChristianSchenk711

**Comment by ChristianSchenk711** [comment]
This is what I did locally and it worked, so I guess that fixes it. Thanks for the quick action.

**Comment by benoitf** [comment]
thanks for reporting the issue
