### ISSUE TITLE
Creating workspace - wrong error visible

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#6772]
### Description
When trying to create new workspace and entering a name with 2 chars it returns error: "The name should not contain special characters like space, dollar, etc. and should start and end only with digits, latin letters or underscores." But it seems like this is not the problem, the problem is probably with length of name of workspace. 

![screen](https://user-images.githubusercontent.com/29278800/31672226-46596638-b35c-11e7-95e2-d50802f56d5f.png)

**Comment by ghost** [comment]
@ashumilova @olexii4 defnitely not a critical bug, but perhaps smth to improve though.

**Comment by ashumilova** [comment]
@olexii4 is there any PR to che5(master) ?
