### ISSUE TITLE
Need to remember LSP diagnostics for ALL files

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6773]
Currently, diagnostics from LSP language servers are passed onto the LSP editors directly. However, this is wrong: language servers may produce diagnostics at any time, for example, when a build is finished. If an editor for a file "X" is not open at the time the LS sends diagnostics for "X", no diagnostics are shown when the file is opened.

**Comment by gazarenkov** [comment]
@tsmaeder labels?
https://github.com/eclipse/che/wiki/Labels

**Comment by julsarik** [comment]
When you open a file handled by a language server. The language server re-compile the code and if they are errors, they are shown in the editor.
If errors are not shown, the problem concerns the code server implementation.
Right ?

**Comment by tsmaeder** [comment]
@julsarik no, there is nothing in LSP that mandates that language servers behave that way. In particular, jdt.ls does not.

**Comment by tsmaeder** [comment]
To clarify this: when jdt.ls sends a diagnostic for a file that is not currently open in an editor, that diagnostic is lost. It will not be resent when the file in question is opened.

**Comment by julsarik** [comment]
Yep got it. What is annoying is that some Language Server implementations (e.g. Groovy) recompile and resend diagnostics when a file is opened, whereas jdt.ls does not.
Implementing a fix on the LSP client (aka Che) for specific LS implementation(s) (aka  jdt.ls) is kind of breaking the LS concept which is abstraction.
That being said I don't know the behavior of other LS implementations regarding diagnostic sending on files opening.

**Comment by tsmaeder** [comment]
@julsarik I suspect LSP does not specifiy when diagnostics are sent because they want to leave that freedom to implementers.

**Comment by tsmaeder** [comment]
Theia does this anyway, AFAIK. Closing because we have a workaround for jdt.ls
