### ISSUE TITLE
Archetypes should create assemblies for multi user mode

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#6805]
### Description

Today's archetypes (5.19.0) do contain projects to build the Che and the Codenvy assemblies.
We are using a project derived from archetypes and we mount the /assembly to run che.

We intend to run in multi user mode,  so as far as I understand, I need the multi-user assembly (which in the che 5.19.0 codebase is in the assembly-multiuser subfolders).

It would be nice if the archetypes generate projects for building the multi-user assembly as well.

As far as I could see the maven projects in "assembly-multiuser" already basically use the same technique like the archetypes to assemble the multi-user assembly from the existing ones by adding more plugins. However these projects also add some code and when we use that in our projects, we have to merge for every release.  Ideally the maven projects that build the assemblies should be as simple as possible and should not contain any code.

**Comment by ghost** [comment]
AFAIK, it will be one assembly which simplifies the task or even makes it irrelevant.

**Comment by skabashnyuk** [comment]
Will be fixed by https://github.com/eclipse/che/issues/6981

**Comment by skabashnyuk** [comment]
fixed for che 6 in https://github.com/eclipse/che/issues/6981
