### ISSUE TITLE
Connections to Keycloak 404 on non-multiuser

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6810]
I'm not sure if this is intended behaviour but I noticed that running `che-server` in normal mode, connections are still being made to keycloak, organisation which show as 404 errors in the console.

Che 5.19

**Comment by ghost** [comment]
@davidwindell this is how dashboard identifies if there's KC and thus multi user mode

**Comment by davidwindell** [comment]
Ok, cool, perhaps this should be in the API.

**Comment by ghost** [comment]
Well, the client does not know if it's a single or a multi user until this call to keycloak is made.
