### ISSUE TITLE
Add search filter by branch name for git "Branches" window.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#6813]
It would be very useful add search filter for git "Branches" window ("Git" -> "Branches"). It's very useful in case when you have a project with big branch list and you want to find branch by name.

- [x] Handle dom events (if necessary)
- [x] Add label at right side of the filter drop box
- [x] Backspace removes the last character
- [x] Esc cleans filter 
- [x] Add selenium test
- [x] Consider general approach to filter list if all items are loaded (if possible)

**Comment by mmorhun** [comment]
+1 had the same idea this morning)
