### ISSUE TITLE
Che CLI pulls multi-user Che master image even though I use single user mode

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6815]
### Description
This adds quite a bit of time to start Che for local development. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by ghost** [comment]
That's the drawback of having one CLI. @riuvshin can elaborate

**Comment by riuvshin** [comment]
expected behaviour :)

**Comment by ghost** [comment]
https://github.com/eclipse/che/pull/6854

This worked for me in 4 modes:

1. Single port true and single user
2. Single port true and multi user
3. Single port false and multi user
4. Single port false and single user (default and most common use case)

**Comment by garagatyi** [comment]
@eivantsov I assume that the issue is fixed now, right?

**Comment by riuvshin** [comment]
yes this is fixed already.
