### ISSUE TITLE
It is not clear whether it is possible to create a workspace without importing a project

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6816]
### Description
I added mounts with my projects for local development in Che and found that new project is created in case of workspace creation on UD. 
Is it possible to avoid projects creation when a user doesn't need that?

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by benoitf** [comment]
AFAIK, unless I click on "Add project" button
![image](https://user-images.githubusercontent.com/436777/31796010-463b1b60-b528-11e7-9fdd-6a2d9f388580.png)

I don't have projects in my workspace

**Comment by garagatyi** [comment]
OK, then I misunderstood something. Thanks
