### ISSUE TITLE
[CHE-6] Git command output console is not consistent

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#6817]
### Description
Git command output console style in CHE-6 doesn't fit to comon colors and icons.

### Reproduction Steps
Perform any Git operation e.g. Git -> Status.

Wrong:
![gitstatus](https://user-images.githubusercontent.com/7668752/31763067-cbee6f54-b4c5-11e7-9ab8-71966ad274d1.png)

**OS and version:**    
CHE-6 Ubuntu 16.0.4

**Diagnostics:**

**Comment by zacharysang** [comment]
Could this eventually be resolved by the move to Theia this year? I am not sure what the scope of the Theia changes will be.
