### ISSUE TITLE
Display current loading step in top menu

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#6819]
### Description
Rework command controller component to display loading status and step name

![31430943-fe33dcca-ae7a-11e7-835e-fff6a994bbbc](https://user-images.githubusercontent.com/1655894/31763650-8ff383ca-b4c7-11e7-9b1f-794f82d8cb6b.png)

Is a part of https://github.com/eclipse/che/issues/5231

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by gazarenkov** [comment]
@vitaliy-guliy could you please rephrase the issue to make it more clear
