### ISSUE TITLE
IDE UI elements are hard to recognize

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6820]
### Description
It is hard for me to recognize UI elements in Che because of small size and/or contrast.
The code in the editor is small and I haven't found any way to increase it without increasing all the elements of the window.
Zooming of the browser doesn't allow to change elements size in a comfortable way and it is not persisted across IDE usage sessions.
Even after I increased zooming of the tab by 10% some buttons were too small. 
Take a look at file tree buttons in zoomed by 10% Che and regular buttons in IDEA:
![screenshot from 2017-10-19 12-15-51](https://user-images.githubusercontent.com/1851863/31763868-4182632c-b4c8-11e7-8ad2-ed77b9a38193.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
+1.

**Comment by ashumilova** [comment]
+1 menus state are not clear when all are enabled.
Enabled:
![screenshot from 2017-10-19 14-55-34](https://user-images.githubusercontent.com/1611939/31769780-b2e0ef60-b4dd-11e7-8ca4-91f976ef0a41.png)

Mixed state:
![screenshot from 2017-10-19 14-55-47](https://user-images.githubusercontent.com/1611939/31769788-bf65e16e-b4dd-11e7-9c0a-9c5b25cdd70c.png)

**Comment by ashumilova** [comment]
Same with find results:
![screenshot from 2017-10-19 15-00-34](https://user-images.githubusercontent.com/1611939/31769946-56e7d86c-b4de-11e7-939f-436ee1974154.png)

**Comment by garagatyi** [comment]
Would be very useful to be able to customize fonts size and font type.

**Comment by AndrienkoAleksandr** [comment]
+100 about menus state are not clear when all are enabled.

**Comment by vparfonov** [comment]
@slemeur Can you take a look and revise those colors?

**Comment by slemeur** [comment]
@vitaliy-guliy : I feel that the redesign work is not completed. Have those elements been cleaned during your work on the UI? 

There are a lot of different issues reported in this issue. We will not be able to track those properly. I'd recommend to split that into separate issues and link them here.

Few points:
- We need to control the size of the icons - they are not consistent
- We can rework the styles, put more contrast - but keep in mind users have different tastes and will want flexibility - having ability to customize the font and styles is quite important. 
- What about the light theme?

**Comment by gazarenkov** [comment]
Let's leave here the only things which are related to styles/colors which, as it stated to description are "hard to read" and consider it as a "bug" (P1 I would say). 
"Enhancements" (like customization), indeed, can be moved to other issues.

**Comment by vitaliy-guliy** [comment]
@slemeur It seems I changed only the menu background. Other components are unchanged.
The issues means to increase readability of the text in menu, editor and find results.
Let's go with this for both themes.
