### ISSUE TITLE
Navigate to file opens file that doesn't match search

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6821]
### Description
For some reason when navigate to file doesn' provide any suggestion of a file a user looks for pressing enter opens a completely irrelevant file.
Here are 2 examples:
https://youtu.be/KwWechB9xNU
https://youtu.be/LqTnEcOBFRI
### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by vparfonov** [comment]
can't reproduce, free to re-open it with new details
