### ISSUE TITLE
Stack renaming doesn't work properly

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#6824]
### Description
Stack editing has weird behaviour.

### Reproduction Steps
1. Create a stack (or duplicate existing one)
2. Open it for editing
3. Try to change name

The stack name is lag behind for one symbol:
![screenshot from 2017-10-19 12-56-44](https://user-images.githubusercontent.com/15607393/31765456-1906f412-b4cd-11e7-8253-e16285323ae2.png)
Also it is possible to save a stack without name by deleting its name and typing one symbol; Then click `Save` button.
Such strange behaviour is present for `Description` field.

One more problem: back arrow button saves changes, so, no way to discard current edits.

**OS and version:**   Fedora 25

**Comment by sleshchenko** [comment]
I faced a little another use issue with setting stack name while creation.
Dashboard cuts the last symbol.
Reproduction Steps:
1. Try to create a new stack and name it `dockerfile`.
2. Press Save button.
Expected: Stack `dockerfile` is created
Actual: Stack `dockerfil` is created.

<details>
<summary>See gif</summary>

![stack_creation](https://user-images.githubusercontent.com/5887312/32660132-485c4e06-c62a-11e7-8196-6c2b6a6ec0df.gif)
</details>

**Comment by ashumilova** [comment]
@olexii4  is there any PR to che5 (master) ?

**Comment by diddledan** [comment]
The fixes in #7584 and #7608 missed the same behaviour on the description field of the stack edit screen. For clarification, when changing the description of a stack the last character is stripped off when saved.
