### ISSUE TITLE
Undo changes does not rename a file to its previous name

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#6828]
### Description
Undo changes feature does not process file renaming properly.
### Reproduction Steps
1. create workspace(from default Java stack)
2. import project(e.g. che)
3. rename any java file from editor
4. click undo changes

expected: renamed file must be with the previous name
actual see attachments:
![rename](https://user-images.githubusercontent.com/12269156/31766760-3b089346-b4d1-11e7-9a92-c41fa3d9748b.gif)

**Comment by sleshchenko** [comment]
Closing as `won't fix` since it's related to deprecated GWT IDE.
