### ISSUE TITLE
How to configure docker image to use unicode ?

### ISSUE THREAD

**Issue by msohn** [eclipse-che/che#683]
- install Che 4.0.0 RC11 on Mac OS X 10.11.3
- create a new project for jgit
- clone jgit git repository from https://git.eclipse.org/r/jgit/jgit
- open project in Che
- open terminal in Che
- run 
  $mvn install
  in root folder of jgit's source tree
  -> build and tests take ~54min (directly on my Mac they take around 3min)
- some tests fail since locale in docker image is POSIX

How can I configure the docker image to use LC_ALL="en_US.UTF-8" ?
I think it would make sense to configure this by default

**Comment by ghost** [comment]
Yes, `LC_ALL="en_US.UTF-8"` does make sense.

As to JGit.. probably you have a local maven repo with all the deps. Also, how much RAM did you allocate for a workspace where JGit was built? This also matters.

**Comment by ghost** [comment]
I have updated all base images. It should be OK now.

Feel free to reopen the issue if it does not work for you.

**Comment by msohn** [comment]
Thanks, this fixed the unicode problems I had running jgit tests.

Now I would like to tackle the poor performance I see for the jgit Maven build.
I tried with 2GB RAM and 4 cores for the VirtualBox image, but mvn clean install for jgit still takes 54min,
running the same locally takes 3-4min only.

Also loosing the .m2 directory when restarting the workspace comes with a high price since after restarting the workspace Maven has to download all dependencies again which takes quite a while.
How can I mount maven.home to a directory on the host system similarily how the /projects folder is mounted ?

**Comment by TylerJewell** [comment]
Let's open a new issue for this particular performance issue. And we can get a good dialog going to discuss options.

**Comment by msohn** [comment]
ok, I filed https://github.com/eclipse/che/issues/694 for this
