### ISSUE TITLE
Fix project import menu wording

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6833]
### Description
In project import menu we have "Import From Codenvy Config..." menu. I think it should not mention Codenvy.
![image](https://user-images.githubusercontent.com/1851863/31768813-9c2d26fc-b4d9-11e7-9cc2-ba0915b85f02.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by gazarenkov** [comment]
@vparfonov can we fix it fast pls?
