### ISSUE TITLE
Git branch is not updated in file tree view after checkout to another branch

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6835]
### Description
After checkout to another branch with Git menu file tree view mark of git branch is not updated.

### Reproduction Steps

**OS and version:**    

**Diagnostics:** 

- [x] Bind as eager singleton https://github.com/eclipse/che/blob/46ddf5e8403cde5a2c9e827b8916ae94f52830a4/plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/plugins/GitCheckoutNotifier.java#L36
- [x] Get rid of root context synchronization
https://github.com/eclipse/che/blob/46ddf5e8403cde5a2c9e827b8916ae94f52830a4/plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/plugins/GitCheckoutNotifier.java#L85

**Comment by tolusha** [comment]
Investigation shows that `FileWatchers` work too slowly.

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/7407
