### ISSUE TITLE
Usage of terminal is uncomfortable without terminal aliases and scripts user is used to

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6838]
### Description
I'm using bash aliases and scripts heavily on my local working machine. But in Che I don't have those aliases and even if I have added them they would disappear after workspace start.
It would be nice being able to configure some environment stuff for Che terminal - e.g. personal bash settings. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
Where is do you want to store this information? I think we should have special storage for saving such different kind information like: debugger breakpoints (for now we store them in the browser storage)  and watch expressions, personal bash, java compiler preferences and so on...

**Comment by davidwindell** [comment]
We achieve this with `CHE_WORKSPACE_VOLUME` like  `/hostdir/users/username/bash_aliases:/home/user/.bash_aliases` although that probably won't with with the new multi user Che.

**Comment by garagatyi** [comment]
@davidfestal Nice idea for local development! But yes it would not work in multi-user mode.
@AndrienkoAleksandr I'm not sure now. I created this issue to start the discussion and maybe someone will have useful ideas.

**Comment by davidfestal** [comment]
@garagatyi seems you answered to the wrong person

**Comment by gazarenkov** [comment]
I think the only place we can store it (and we do it for other cases) for the moment is User Preferences.
Can start with it no?

**Comment by garagatyi** [comment]
@davidfestal Yes, thank you for pointing out!

**Comment by garagatyi** [comment]
@gazarenkov since it requires injection of something into the terminal it is not clear how to inject this information

**Comment by skabashnyuk** [comment]
```curl http://..../user/preferences >> .bashrc```

**Comment by gorkem** [comment]
Do we have support for bash only? Should the solution be generic?

This is a slightly advanced use, I think we can treat this one as user knows what he/she is doing and provide a free format preference

**Comment by garagatyi** [comment]
+1

**Comment by garagatyi** [comment]
outdated
