### ISSUE TITLE
Language Server initialization on multi module maven project

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#6839]
Imagine I have a maven  multi module project with the following structure:
/projects/multi-project
----pom.xml
----module_a
--------pom.xml
----module_b
--------pom.xml

If the module folders are not resolved as maven projects (which is done when open pom.xml), LS initialized with rootPath as "/project/milti-project".
But after resolving twice for "/projects/multi-project/module_a" and "/projects/multi-project/module_b".

[LSP](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize) defined rootPath as "The rootPath of the workspace." . For LS in my case it's ambiguous to be initialized with module root folder when multi-module project root is expected. 

Thus, because of the lack of information for LS about when modules will be resolved, I have to define such kind of Che's behavior as non-deterministic. 

Che version 5.16.0.

**Comment by tsmaeder** [comment]
@zatsepinvl I really don't understand what you mean. Are you reporting a bug or asking for information? What behaviour do you expect and what are you seeing?

**Comment by zatsepinvl** [comment]
The question is how "rootPath" is defined as a LSP term in Che? 
Moreover, how should I deal with it: 

> Thus, because of the lack of information for LS about when modules will be resolved, I have to define such kind of Che's behavior as non-deterministic.

I expect that Che will send the root path (e.g. /projects/milti-module) also when all sub-modules are resolved.

**Comment by tsmaeder** [comment]
Che launches one instance of a language server per project. The root path is the top level project, in your case it should be "/projects/multi-project". 
However, it would be better to use the "rootURI" field, since the path field is deprecated. That should be file:///projects/multi-project

**Comment by zatsepinvl** [comment]
Yes, "rootURI", of course, it's just my typo mistake. But the root cause of the problem is that sub-module (e.g. _module_a_) is also resolved by Che as a project and two LS will be initialized for _module-a_ and _module-b_, but not for _multi-project_.

**Comment by gorkem** [comment]
I think there are 2 project concepts here. Every Che project `/project/multi-project` in the example above will run its own jdt.ls instance and recognize submodules as jdt projects (the second project concept).

I think this may change as we introduce multi-root support on jdt.ls though.

**Comment by garagatyi** [comment]
@gorkem in case of LS that is running in a separate container would we have to start a container per maven module than?

**Comment by gorkem** [comment]
__Today:__ It should be single container with jdt.ls started as many times as there are Che projects "/project/multi-module". Every single instance of jdt.ls is capable of scanning a root folder and extracting modules as JDT projects. A JDT project is not visible to users. It is just something that jdt.ls keeps internally. You can imagine the container as a way of delivering the jdt.ls binaries in this case. 

__With multi-root support:__ We should be able to start a single jdt.ls and handle all Che projects by fetching them in as root folders. The plan on jdt.ls is to be able to add remove roots while jdt.ls is running. See [multi-root issue](https://github.com/redhat-developer/vscode-java/issues/281) for details.

**Comment by ghost** [comment]
@tolusha how will jdt.ls handle a multi module maven project?

**Comment by tolusha** [comment]
We have an issue with maven multi-module project https://github.com/eclipse/che/issues/8510

**Comment by ghost** [comment]
Closing this one.
