### ISSUE TITLE
Scroll button click on file tab closes tab and puts buffer content into the following active tab editor

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6840]
### Description
Scroll button closes editor tab. It is a very handy feature. But in Che, it also pastes the content of the buffer into the editor tab that becomes active. It is very frustrating.  

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by vzhukovskii** [comment]
Checked on revision: 5c4fd8b6982f7be2 (6.6.0-SBAPSHOT)

Issue is closed, because it cannot be reproduced. Feel free to re-open the issue in case if this bug still exists.

**Comment by SkorikSergey** [comment]
This issue is still reproduced.
![nimbus-record-video-2018-05-15-12-35-29](https://user-images.githubusercontent.com/7760565/40049117-86dab43e-583c-11e8-84f7-980c9cd4f60d.gif)

**Comment by vzhukovskii** [comment]
It seems that issue reproduces only in Google Chrome in linux. Firefox (linux) and Google Chrome (macOs) don't reproduce the issue.
