### ISSUE TITLE
Panel's buttons don't work properly after hiding/restoring a panel

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#6842]
### Description
 
Panel's buttons (Hide/Maximize) stop working after hiding a panel followed by manually restoring it.
### Reproduction Steps

* Hide any panel (part) e.g. Project Explorer
* Restore it "manually" with mouse pointer

`Hide`, `Maximize` buttons don't work after these steps. Also, the corresponded items disappeared from the `Options` menu.

![bug](https://user-images.githubusercontent.com/1636395/31774100-70f369ec-b4ed-11e7-8674-cec4bdd2438d.gif)

**OS and version:**    
Che 6.0.0-M1-SNAPSHOT

**Diagnostics:**

**Comment by vparfonov** [comment]
out of date

**Comment by vparfonov** [comment]
not actual
