### ISSUE TITLE
Navigate to file improvement

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#6848]
It would be great to have some filters in `Navigate to file` widget:
1. include/exclude results by file extension. (For example include only *.java files or exclude *.class files from results)
2. Case sensitive/insensitive flag (checkbox)

**Comment by sleshchenko** [comment]
Also, I'd do automatically sorting of the result list by types which makes sense to open with the editor and which doesn't make. Like, it doesn't make sense to open with editor `.class` files or zip archives, so I'd put them to bottom of the result list.
See attachment where I tried to find OpenShiftInfrastructure class, and I have to type `.java` file extension evidently or skip all `.class` files.
![screenshot_20171102_145138](https://user-images.githubusercontent.com/5887312/32326931-58e2834c-bfdd-11e7-9bed-adf106506e74.png)

**Comment by slemeur** [comment]
@vparfonov : We have #5330 and #4993 . Is this issue going to help towards on those goals too?

**Comment by vparfonov** [comment]
yes in some way it could help, but here more about filtering result
