### ISSUE TITLE
[Regression]GDB-Debugging not working in 5.20.0

### ISSUE THREAD

**Issue by hkolvenbach** [eclipse-che/che#6855]
### Description
 
GDB debugging does not work in Eclipse Che 5.20-SNAPSHOT even though privileged mode is enabled.
- GDB debugging without specifying the port for gdbserver does not work at all
- when correctly specifying the port, debugging crashes instantly
- using GDB from command line to connect to gdbserver works

### Reproduction Steps

- Following the guide in https://eclipse.org/che/docs/ide/debug/index.html#gdb with `Che_DOCKER_PRIVILEGED=true`
- Use C++ stack and cpp console application sample
- add `int test1 = 200;` to the main function to have a variable and set a breakpoint on it
- compile with the run command (or use `gcc -g Hello.cc` directly)
- Start the gdbserver with `gdbserver :4000 a.out`
- Try to connect to gdb through the che gui by going to `run -> debug -> edit debug configuration`, set the port to 4000 as specified above
- The debug window opens briefly and crashes instantly (breakpoints are visible, but no variables. "gdb 7.1.. flashes up briefly in the top right corner of the debug window)

**OS and version:**    
Debian 9 (64bit), Chrome 62

**Diagnostics:** 

![debug-not-working](https://user-images.githubusercontent.com/26924052/31808277-b28d522a-b572-11e7-8b25-bef0747fdb5e.gif)

TODO:
- [x] Pass absolute path to the file where breakpoint is set
- [x] Move all server side tests into the docker container like Java Debugger does

**Comment by ghost** [comment]
Can be potentially caused by gdb update in the stack.

**Comment by tolusha** [comment]
The root of the issue:
```
Can't parse 'No source file named /console-cpp-simple/hello.cc.
Make breakpoint pending on fu' into GdbBreak
```
It means that https://github.com/eclipse/che/blob/master/wsagent/che-core-api-debug-shared/src/main/java/org/eclipse/che/api/debug/shared/model/Location.java#L16
has to consist the absolute path including `/projects`. The issue might be caused the recent Debugger refactoring.
