### ISSUE TITLE
Upgrade to GWT 2.8.2

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#6859]
- [x] CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14599

### Description
There are a lot of [bugfixes and enhancements](https://gwt.googlesource.com/gwt/+log/2.8.1..2.8.2) in GWT 2.8.2.
One of the most important things for Che is that it enables us to compile GWT projects with Java 9 JRE.

[Release Notes for 2.8.2](http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_2)

**Comment by azatsarynnyy** [comment]
Related CQ has been already approved

**Comment by benoitf** [comment]
@azatsarynnyy I've created https://github.com/eclipse/che-dependencies/pull/69

**Comment by azatsarynnyy** [comment]
done in https://github.com/eclipse/che-dependencies/pull/69
