### ISSUE TITLE
Rework dashboard on managing environment variables

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#6868]
As far as new ability to save environment variables to machines config was introduced in che6, there is need to rework the way of how environment variables are saved and retrieved by dashboard application. It was available only for compose and docker files, now - for all types of the recipe, so restrictions should be removed as well.

**Comment by olexii4** [comment]
depends on https://github.com/eclipse/che/issues/7509

**Comment by olexii4** [comment]
spent - 3days
