### ISSUE TITLE
Consider JGit 4.9 upgrade

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6884]
### Description
We are using 4.2 jgit that is about ~2 years old
Among other things, I've seen a couple of notes about performance improvements.
See 
- https://wiki.eclipse.org/JGit/New_and_Noteworthy/4.9#Performance_Improvements
- https://wiki.eclipse.org/JGit/New_and_Noteworthy/4.8#Performance_Improvements

It would be interesting to see benefits on basic operation with repository like ```eclipse/che```

- [ ] Check selenium tests

**Comment by tolusha** [comment]
Version: `4.9.0.201710071750-r`
Server side tests passed.
