### ISSUE TITLE
Can´t start workspace in multiuser mode

### ISSUE THREAD

**Issue by alber7rp** [eclipse-che/che#6885]
Then of install and run eclipse che in multiuser mode, i can create a new workspace but i cant run it.
I run a server in a vm virtualbox with the next command:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /data/example:/data -e CHE_PORT=9000 -e CHE_CONTAINERT=example -e CHE_MULTIUSER=true eclipse/che start`

Then i create a new workspace for the user, but when i run it this error appears:

> Could not start workspace wksp-q0qx. Reason: Start of environment 'default' failed. Error: Error response from docker API, status: 404, message: No such network: che_che-network

![captura](https://user-images.githubusercontent.com/10332003/31850619-6d9af77c-b64d-11e7-9ba7-4608ac37df1f.PNG)

**OS and version:**  
Ubuntu 16.04.3

**Comment by gorkem** [comment]
Possibly duplicate of #6872

**Comment by ghost** [comment]
@gorkem no, it is not. Here, workspace cannot start because of a missing network. 

@alber7rp can you run `docker network ls`? Also, what kind of variable is this `CHE_CONTAINERT`?

Can you start a single user Che?

I'd recommend to reset Docker for Windows and give it another try.

**Comment by alber7rp** [comment]
Sorry, I wanted to put "CHE_CONTAINER", which is the name of the docker container.
On the command "docker network ls" the output is as follows:
![seleccion_209](https://user-images.githubusercontent.com/10332003/31861792-fe711a6e-b72a-11e7-883a-5de9094c9695.png)
When I run a single user server everything works fine.

**Comment by alber7rp** [comment]
I have noticed that if I don't put a port and leave the default port (8080), the corresponding network is created (che_che-network) and thus the workspaces are created well. Then I sense that in multiuser mode you can't change the listening port.

**Comment by thyeun** [comment]
@alber7rp, something to know from you, when you use multi-user, your "connection information", will it create extra two more bridge or not? if yes, than you should possible to changing the listening port. (i'm mean logically it should be)

**Comment by ghost** [comment]
@alber7rp does single user Che work for you with a custom port?

**Comment by alber7rp** [comment]
Yes, I can create a single user server with a custom port, which is why I found it strange that in multiuser mode it wasn't possible.

**Comment by ghost** [comment]
@alber7rp i managed to reproduce the error. The problem is that the network name inherits port:

```
1e8923e12376        che9000_che-network   bridge              local
e8edcf4e1763        che9000_default       bridge              local
```
While, Che is looking for che_che-network.

**Comment by ghost** [comment]
OK, found what causes the issue.

@riuvshin please take a look:

Here we instruct Che server what docker network to use:

https://github.com/eclipse/che/blob/ee01b2998feac77f3408a80ee6e5386e09e23b9f/dockerfiles/init/modules/che/templates/che.env.erb#L27

When CHE_PORT is set, docker networks are created with a prefix which is `che$port`

As a result, networks are created according to this naming pattern and a non existent network is passed to server's java opts.

**Comment by riuvshin** [comment]
@alber7rp as a workaround you can override `CHE_DOCKER_NETWORK=`
I will take a look on this one
