### ISSUE TITLE
Firewall settings for multi-user mode

### ISSUE THREAD

**Issue by Michael-Liao** [eclipse-che/che#6890]
### Description
I have tried local install with **eclipse che 5.19.0** alongside **docker 17.09.0-ce** on a Ubuntu desktop 16.04.3 and it went great.
Today I decided to install the same configuration on a Ubuntu Server 16.04.3 with 4GB RAM using the getting started command:
`sudo docker run -it --rm -e CHE_MULTIUSER=true -e CHE_HOST=xxx.xxx.xxx.xxx -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-data:/data eclipse/che start`
I got a black dashboard (without the flashing icon in the middle). However, when I disabled the firewall, everything works fine.
I already learned from another post that `port 32768` (which is apparently where `docker0` is) has to open for the installation to work. What else did I miss there?

**Opened ports** 
80, 443, 8080, 32768:65535

**Comment by Michael-Liao** [comment]
found what I'm looking for at [#5204](https://github.com/eclipse/che/issues/5204). Sorry for the inconvenience

**Comment by ghost** [comment]
@Michael-Liao the ephemeral port range needs to be opened, as well as port 5050 (Keycloak server).

**Comment by gorkem** [comment]
@slemeur Should this be documented somewhere?

**Comment by ghost** [comment]
http://www.eclipse.org/che/docs/setup/getting-started/index.html#internalexternal-ports

**Comment by ghost** [comment]
@Michael-Liao have you resolved this one?

**Comment by Michael-Liao** [comment]
Yes indeed! Thank you
