### ISSUE TITLE
Add support for MySQL

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6902]
I would like to suggest support for MySQL in Che instead of PostgreSQL.

In our case we already have a MySQL server setup (on RDS) for infrastructure management and would like to be able use the same server for Che.

**Comment by skabashnyuk** [comment]
@davidwindell do you know mysql jdbc driver with the acceptable license? I mean not GPL?

**Comment by skabashnyuk** [comment]
This is a core issue https://www.eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE
why we can't have MySQL support in official Eclipse Che.

**Comment by davidwindell** [comment]
Could this be something the user can enable as an add-on somehow - a way around the license issue?

**Comment by skabashnyuk** [comment]
Yes, user can enable it in his custom assembly.

**Comment by ghost** [comment]
@davidwindell since MySQL cannot be part of Che bundle, I am going to close it. You may try adding MySQL support in a custom assembly though - I'd be happy to add docs on that

**Comment by davidwindell** [comment]
@eivantsov @skabashnyuk can it not be implemented via the FOSS exception? https://www.mysql.com/about/legal/licensing/foss-exception/
