### ISSUE TITLE
Getting an error /bin/sh: 102: let: not found

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#6906]
OS : Ubuntu 16.04.3
Che : 5.19.0
Mode : Multi-User 

Last night Che 5.19.0 working perfectly, but today once i reopen my workspace, i getting an error as below picture.

![selection_035](https://user-images.githubusercontent.com/1939446/31887426-e769a1d2-b82a-11e7-9725-8b03dae048b3.jpg)

**Comment by ghost** [comment]
Must be this line https://github.com/eclipse/che/blob/master/agents/ls-csharp/src/main/resources/org.eclipse.che.ls.csharp.script.sh#L102

Does this happen to a new workspace?

**Comment by thyeun** [comment]
@eivantsov, yes, only happen for new workspace (on Multi-User Mode), due to that last version 5.18.0, i'm not using Multi-User Mode, and it is not happen, but after upgrade to version 5.19.0 and switch to Multi-User Mode and create a new workspace, than it is appear as i show you from the above picture

**Comment by thyeun** [comment]
@eivantsov , how do i change that line? for not using "let" because unix system only will using "let", but not for ubuntu system.

**Comment by ghost** [comment]
@thyeun you cannot check that line without rebuilding the project and using your own assembly. I'll try to reproduce the error on my side and get back to you.

**Comment by ghost** [comment]
@thyeun bug confirmed. But even though it's there, it does not affect C# LS

**Comment by thyeun** [comment]
@eivantsov , not affected C# LS, but the start-up workspace take longer time (not sure you feel that or not)

**Comment by mmorhun** [comment]
Fixed
