### ISSUE TITLE
Implement "get effective pom"

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6907]
The maven plugin offers an action to open the effective pom. We need to add a custom command to the che jdt.ls extension to offer this service. M2e (embedded in jdt.ls) should offer API to do this. 
See MavenServerService#getEffectivePom()

- [x] Familiarization with jdt.ls 1SP
- [x] Add a new command 1SP
- [x] Implement the new command 5SP
- [x] Add unit tests 1SP

**Comment by fbricon** [comment]
With m2e, you need to:
- get a hold of the maven project registry: MavenPlugin.getMavenProjectRegistry()
- call IMavenProjectRegistry.create(IFile pom, boolean load, IProgressMonitor monitor) to get an IMavenProjectFacade
- then MavenProject mavenProject = facade.getMavenProject(monitor);

from there, you can reuse your existing code

**Comment by mmorhun** [comment]
done
