### ISSUE TITLE
Check diagnostics in Maven plugin vs. jdt.ls

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6908]
Jdt.ls reports diagnostics against pom.xml files. We need to check whether the jdt.ls diagnostics are sufficient to replace what the current plugin has.
Work with @fbricon to check features.

**Comment by tolusha** [comment]
So far jdt.ls diagnostics doesn't support:

* declared module existense
```
<modules>
  <module>somemodule</module>
</modules>
```

* unrecognized tags

**Comment by tolusha** [comment]
https://github.com/eclipse/eclipse.jdt.ls/issues/496
https://github.com/eclipse/eclipse.jdt.ls/issues/498
