### ISSUE TITLE
workspace not restored from snapshot when che server is restarted

### ISSUE THREAD

**Issue by arunkutty** [eclipse-che/che#691]
**Description of problem:**

> Snapshots let users capture, save, and re-constitute this state. Make snapshots for workspace machines, which are stored as Docker images in a configured registry. **Reopening the workspace instantiates a new workspace machine from the snapshot with the projects then mounted.** This leads to superior long term performance as snapshot re-activation is immediate.

I am running Che natively on Windows 7. A "snapshotted" workspace stops after stopping Che. When Che starts up again, booting up the workspace in the process, the workspace doesn't get restored from the snapshot. However, when the workspace is stopped from within the browser client, it prompts to restore from snapshot on the next start.

**Che version:**

```
Version: 4.0.0-RC12
Revision: 15571e40395fd7c8
Build Time: 2016-03-06 17:34:32
```

**Che install directory:**
"C:\Users<Username>\AppData\Local\Programs\Eclipse Che\eclipse-che-4.0.0-RC12" 
Docker version: 
`1.9.1 build a34a1d5`

*_Java version: *_
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

**Environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox, Windows 7 64-bit.

**How reproducible:**
Using Firefox Firefox ESR 38.7.0, 100% reproducible.

**Steps to Reproduce:**
1. Create a workspace and start it up
2. Install a ruby gem or an npm package using the terminal
3. Snapshot the workspace
4. Stop the workspace and che server
5. Restart Che server which automatically starts up the workspace in step 4

**Actual Results:**
The packages installed on to the workspace machine prior to creating snapshot are not available. 

**Expected Results:**
Workspace has to restore from snapshot after Che restart.

**Comment by ghost** [comment]
Do you have a Docker registry running in a Docker VM?

Also, do you restart a workspace from the User Dashboard or the IDE?

**Comment by arunkutty** [comment]
> Do you have a Docker registry running in a Docker VM?

Registry was running while I created the snapshot. However, at the point of creating this issue, I hadn't been keeping it running when restarting Che server. After your comment, I tried starting Che server while Registry was running and that hasn't made any difference. 

> Also, do you restart a workspace from the User Dashboard or the IDE?

I've been restarting the workspace from the IDE to boot up the workspace machine from the snapshot.

**Comment by TylerJewell** [comment]
@arunkutty Is it possible that you are shutting down the registry and the saved snapshot is getting lost?  I doubt this is the issue, but want to double check.

**Comment by arunkutty** [comment]
@TylerJewell, No. The registry was running. The workspace does get restored from snapshot when I stop/start it from the IDE.

**Comment by TylerJewell** [comment]
@arunkutty Ahhh - you know, I think this is a misstatement in the docs. I think there is a missing element of the development lifecycle that there are certain scenarios that if you restart a workspace from within the dashboard, it is not picking up the proper snapshotted workspace.

@ashumilova would have the specific answer. But I believe, yes, the entire expectation is that if you snapshot your workspace, stop it, open the dashboard, and then restart the workspace - it should pull from the snapshot instead of the base image.

**Comment by ghost** [comment]
Yes, when running a ws from User Dashboard, we do not display a message "Would you like to restore a workspace from snapshot".

**Comment by ashumilova** [comment]
Hi, we have an issue for managing snapshots in dashboard, but it's not yet implemented or scheduled.

**Comment by ghost** [comment]
@innovateworld thanks for a detailed report. Checking it today. @ddementieva will write back.

**Comment by ddementieva** [comment]
@innovateworld, just checked it on Ubuntu 14.04 and it worked OK there. Workspace has been restored from the manually created snapshot after the Che restart and automatically restored after adding `workspace.runtime.auto_restore=true` property. 

Have you checked if the snapshot has been successfully created the first time? It's possible that you've stopped Che before workspace has been snapshoted. Can you try to reproduce this problem again and send us complete Che server logs?

**Comment by ghost** [comment]
@arunkutty Can you check it again? This has been fixed.
