### ISSUE TITLE
Replace "reimport maven project" for m2e

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#6910]
The maven plugin offers an action "Reimport Maven Projects". We need to analyze what exactly it does and reimplement equivalent functionality in the Che jdt.ls extension.

The interesting code starts in MavenServerService#reimportDependencies(). We need to work with @fbricon to determine what we need to do to replace the functionalty. (Think m2e "update project" action).

- [x] Study the current implementation of  "Reimport Maven Projects"  2SP
- [x] Study M2E 3SP
- [x] Implement the new command 5SP

**Comment by mmorhun** [comment]
Synchronous implementation done.
Asynchronous depends on: https://github.com/eclipse/eclipse.jdt.ls/issues/404
