### ISSUE TITLE
Provide an xml editor with xsd completion and validation

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#6925]
It would be nice to support an xml editor with xsd completion and validation.

**Comment by mickaelistria** [comment]
See https://github.com/microclimate-devops/xml-language-server , it seems like a language server now exists for XML. It's used by this vscode extension: https://marketplace.visualstudio.com/items?itemName=IBM.XMLLanguageSupport

**Comment by apupier** [comment]
Red Hat has provided a [client for vs code](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml)  using a newly [written xml language server](https://github.com/angelozerr/lsp4xml) .
using the Language Servers should provide compatibility with Camel La,nguage Server as-is.

(both language servers are working fine together in VS Code for information)

**Comment by apupier** [comment]
I think that it was covered with https://github.com/eclipse/che/issues/12437
