### ISSUE TITLE
'Microsoft.NETCore.App', version '1.1.2' was not found.

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#6926]
OS : Ubuntu 16.04.3
Che : 5.19.0
Mode : Multi-User Mode

Create an example from the ASP.NET core ready make example, and getting the below error message, as you can see from the picture.

![selection_037](https://user-images.githubusercontent.com/1939446/31903495-d818c4b2-b85a-11e7-9384-780af804d8d6.jpg)

**Comment by AndrienkoAleksandr** [comment]
Current version language server supports net core 2.0 project. You can create such project with help command line ("cd projects && dotnet new web -o TestProject") or with help Project wizard: 
1. Click "Workspace".
2. Select "Create project...".
3. In the window "Create new project..." select from the "Samples" project with name "dotnet-web-simple".

**Comment by thyeun** [comment]
@AndrienkoAleksandr , do you mean aspnet-web-simple? if yes, i'm actually using it now, and it is the one given me the above error!!!

**Comment by thyeun** [comment]
@AndrienkoAleksandr, if using the command line, it will create net core 2.0, but if you using "create project" with that "Samples", than it will have the issue that i facing on at the above error

**Comment by AndrienkoAleksandr** [comment]
Hmm...  @thyeun  Seems it's a some migration mistake after update Eclipse CHE from older version. I see you IDE copy generates our old sample https://github.com/che-samples/web-aspnet-simple. 
Actually Eclipse CHE 5.19.0 should generate this one project: https://github.com/che-samples/dotnet-web-simple 
IDE get this path from sample.json: 
https://github.com/eclipse/che/blob/29aaf4b47df9cc080c26b7f09deadd13f9164678/ide/che-core-ide-templates/src/main/resources/samples.json#L924
My working copy Eclipse CHE generates exactly this one sample from wizard: 

![netsampleinsideeclipseche](https://user-images.githubusercontent.com/6873095/31912377-5ca35e04-b84c-11e7-88e5-21cea19b2c62.png)

**Comment by thyeun** [comment]
@AndrienkoAleksandr, yup, i figure out that might be one of the reason also, because from new installation of Che v5.19.0, aspnet-web-simple (no more seeing), and replace with dotnet-web-simple.

So, hope Che team and contributor can help-up "clean" the old coding before release a new version. Due to that, alot of mis-information or mis-things might be repeat asking and solving (same problem) each time when new version come out!...

been wasted more than 2 hours to figure out how come my Che v5.19.0 do not have "dotnet-web-simple".
