### ISSUE TITLE
Apply "this" scope for debugger variables.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#6927]
### Description
It would be nice to split java (and not only java) debugger variables by "this" scope:
![capture image](https://user-images.githubusercontent.com/6873095/31917196-e01b25d4-b85e-11e7-851c-56f56d40f702.png)

- [ ] Update server side test
- [ ] Display just after watch expressions
- [ ] Update selenium tests

**Comment by tolusha** [comment]
Not hard to implement. Should return `this` instance instead of list of fields.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
