### ISSUE TITLE
Make Che-in-che stack more usable for Che development

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6928]
### Description
- [x]  Use ```eclipse/che-dev```  image instead of  ```codenvy/alpine_jdk8```
- [x] Make sure che-dev image is set up for Che build
- [x] Upgrade golang and nodejs version 
- [x] Add commands to build maven project and module
- [x] Set up memory limit to 7G
- [x]  try Centos based image

**Comment by skabashnyuk** [comment]
@sunix suggest to try Centos based image in next iteration.

**Comment by sleshchenko** [comment]
@skabashnyuk I propose to change WORKDIR in `Che-in-che` stack to `/projects/`. Now the location of the newly opened terminal is `/home/user/`and it is inconvenient.
