### ISSUE TITLE
Make IDE more informative

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6929]
### Description
Sometimes it's not really obvious what is going on behind the scene. Nothing is happening
on screen and user may think that IDE does nothing. But in that time on the background,
we are doing really important things. Like maven pom processing, indexing, etc.
The proposal is to have something similar to the status bar. We can put such information:

1. The progress of long operation like maven import, indexing.
2. VCS  branch
3. Memory consumption
4. CPU consumption.

<img width="617" alt="2017-10-24 08 50 41" src="https://user-images.githubusercontent.com/1614429/31926799-8556340a-b899-11e7-8eb8-29257875f8df.png">

**Comment by garagatyi** [comment]
I'm not sure how memory and CPU consumption are useful, but +1 on processing indicator. 
In my case, after importing Che project I couldn't use code assist. I started to investigate why it hadn't been working and after 10 minutes it just started working. The reason was that maven importing and processing wasn't finished yet but I had no idea about that, so thought code assist was not working.

**Comment by skabashnyuk** [comment]
>I'm not sure how memory and CPU consumption are useful

It's useful for a couple of reasons. 
1. To identify some wired frizes or OOM
2. Since there is no swap it makes more reasonable for a user to adjust his memory limit for the workspace  with proper value. 
3. As a developer, I would like to know what is going on on my dev machine. When you working on a local computer you can feel if it overloaded by side effects like a browser or video freezing. But when server side is somewhere far you can't feel it, that's is why you need some indicator. Maybe they can be optional and configured with some profile settings

**Comment by tsmaeder** [comment]
We also have a need for this in https://github.com/eclipse/che/issues/6157 (See maven plugin section)

**Comment by gazarenkov** [comment]
+1 it is extremely useful feature

**Comment by skabashnyuk** [comment]
VSCode example
![2017-11-04 21 18 41](https://user-images.githubusercontent.com/1614429/32408709-e489d6ba-c1a5-11e7-8be0-e2a4e606cd91.png)

**Comment by skabashnyuk** [comment]
Not needed anymore.
