### ISSUE TITLE
UI usage experience

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6933]
### Description
I would like to share the major concern after one-day usage of Che6 of 30 peoples.
It was:
- Small, blurred fonts
- Blurred contrast
- Small buttons.
- Hard to read text on developers monitors (24 inc DELL, FullHD)

**Comment by skabashnyuk** [comment]
Comparation Font size and contrast in 
1. Tabs
2. Project tree

![2017-11-06 09 35 54 2](https://user-images.githubusercontent.com/1614429/32430089-4c4fbc3e-c2d6-11e7-8b93-8fa41d3d3477.png)
It would be nice if we can enhance our version.
I think menus can have large fonts too.

**Comment by slemeur** [comment]
OK. 
We are going to review/refine/finalize the theme for Che6 and will take that into consideration to improve the contrast and readability of the texts. 

Note: It would be better to allow the user to define the font sizes. A unique font size might not fit for all users :)

**Comment by ashumilova** [comment]
Also need to 
- [x] Add more space between icon and title on tabs in the Processes panel
- [x] Review icons to have proper sizes and paddings
