### ISSUE TITLE
Maximize contrast between panels

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6934]
### Description
The contrast between the panel (1) and (2) is really low. It's very hard to understand where movement bar a located. Since of that is hard to resize panels. 
![2017-10-24 09 45 41](https://user-images.githubusercontent.com/1614429/31928348-82dfeb60-b8a0-11e7-8df0-79ae45eb5344.png)

**Comment by vitaliy-guliy** [comment]
https://github.com/eclipse/che/tree/CHE6-5231 [ Workspace Loading Sequence ] branch has already fixed this case. Will be verged soon.

![che6_2](https://user-images.githubusercontent.com/1655894/31931890-44161f28-b8ad-11e7-85e9-dff996380e17.png)

**Comment by skabashnyuk** [comment]
I would like to close this issue when the feature will be merged in che6 branch.
Lets consider this feature is linked to https://github.com/eclipse/che/issues/5231 epic

**Comment by skabashnyuk** [comment]
Linked to https://github.com/eclipse/che/issues/5231

**Comment by skabashnyuk** [comment]
Reopened since it not merged to che6 branch
