### ISSUE TITLE
Navigation in branches dialog

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6935]
### Description
 Branches dialog has no support for arrow keys. I would like to operate with this dialog with keyboard only. 

![2017-10-24 09 52 02](https://user-images.githubusercontent.com/1614429/31928554-3f9a3986-b8a1-11e7-8520-8cbc0b3c0cfc.png)

TODO:

It is easy to handle arrow keys events based on: https://github.com/eclipse/che/blob/7fd75238547e52173095d32039462b3d49c20be9/ide/commons-gwt/src/main/java/org/eclipse/che/ide/ui/list/FilterableSimpleList.java#L32

Let's make it more universal: 
- [ ] Rename to ExtendedList
- [ ] Add methods: `setNavigationHandler` (covers arrow keys events), `setFilterHandler` (covers current behavior to filter content), `setMouseHandler` (to replace `ListEventDelegate`)
- [ ] If handlers are set then `ExtendedList` responds to events
- [ ] Selenium test

**Comment by vitaliy-guliy** [comment]
Also popup may contain text field for searching branches and switcher between branch/tag.

**Comment by gazarenkov** [comment]
@vitaliy-guliy what do you mean by "switcher"?

**Comment by mmorhun** [comment]
Also filter by name will be very useful

**Comment by AndrienkoAleksandr** [comment]
@mmorhun For filter branches by name we have another one issue: https://github.com/eclipse/che/issues/6813

**Comment by tolusha** [comment]
We will add supporting arrow keys for all lists.

**Comment by tolusha** [comment]
Depends on https://github.com/eclipse/che/issues/6813

**Comment by skabashnyuk** [comment]
not needed anymore.
