### ISSUE TITLE
Project import dialog is overloaded with features

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6937]
### Description

There are many features on this dialog that used very rarely like: Import recursively,  keep the following directory.
Some of the features are opened in a very small place like the list of repositories after you pressed "Load Repo" button.
I would like to propose to revise the content of this dialog. And decouple really often used features and advances.
Compare 
![2017-10-24 09 55 42](https://user-images.githubusercontent.com/1614429/31928833-476d04b2-b8a2-11e7-9b3f-43125067508c.png)
![2017-10-24 09 55 11](https://user-images.githubusercontent.com/1614429/31928839-504ac740-b8a2-11e7-97ca-dcddc808869b.png)

**Comment by gazarenkov** [comment]
+1
Can consider "Advanced..." button which extends the dialog somehow with rare features.

**Comment by sleshchenko** [comment]
IMHO GitHub importing should be reworked to provide different pages. Also, On GitHub page a user is able to clone git project with URL not from GitHub only, it contains the same ability as `Git` section provides. 
So I propose to implement `GitHub` importing in the following way. 
1. A User chooses GitHub Account and required repository on the first page. The first page could contain `Advanced git settings` like Gennady said. (So Remove ability to input URL manually)
2. The second page gives user ability to configure Che Project -> Name, Description

**Comment by tolusha** [comment]
@skabashnyuk @sleshchenko 
https://wireframepro.mockflow.com/view/D773451cdb18922d35d70a7fcc8e9a72f

**Comment by skabashnyuk** [comment]
Not needed anymore.
