### ISSUE TITLE
[CHE6 branch] Exceptions are displayed in the "dev-machine" terminal

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#6947]
### Reproduction Steps
 - Run Java stack with default spring project
 - Wait until WS will be started
 - Open project
 - Open "pom.xml"
 - Delete one "dependecy" tag
 - Pay attention to "dev-machine" terminal output

**OS and version:**    
Che(che6 branch) 6.0.0-M1 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![screenshot from 2017-10-24 13-08-24](https://user-images.githubusercontent.com/22724619/31937936-a00f5b1c-b8be-11e7-9ce4-8634cb4a518b.png)

**Comment by musienko-maxim** [comment]
Looks like parser is triggered after any error in the pom file and throw exceptions in the dev console. We should clarify is it bug or feature?
