### ISSUE TITLE
Git colors works incorrectly for several projects

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6968]
**Reproduction Steps:**
- Create in a workspace 2 or more similar projects
- Select any project and from the **Menu** -> **Git** -> **Init Repository** 

**Expected behavior:**
Color of file names changed only in the selected project

**Observed behavior:**
Color of file names changed in all projects

**Che version:** 5.20.0-SNAPSHOT 
**OS and version:** Fedora 25

**Additional information:**
![teams-11-42](https://user-images.githubusercontent.com/7760565/31988484-f1055422-b977-11e7-9fd3-c8fcb45ebdff.gif)

**Comment by vinokurig** [comment]
Need to remove repository initialized and delete events from `GitJsonRpcMessenger`.

**Comment by vinokurig** [comment]
Need to apply filtering by project in `GitChangesHandler`
