### ISSUE TITLE
Feature Request: Creating Snapshots of a Workspace from the UI.

### ISSUE THREAD

**Issue by luckcolors** [eclipse-che/che#698]
Hello.
I found eclipse che a very usefull tool for developing software but i would like to be able to preserve every action i do in a workspace (eg apt, or edited files).
So is it possible to add from the web UI the action to snapshot, import, export(the current snapshot to public or private docker registries), and even rollback snapshots of a workspace?
Thanks in advance.

**Comment by ghost** [comment]
Hello

It is possible to snapshot a workspace and use whatever docker registry you need (even DockerHub).

You may want to take a look at these docs - https://eclipse-che.readme.io/docs/install-pre-reqs#docker-registry-optional

**Comment by luckcolors** [comment]
The thing is that i'm already starting eclipse che with --registry option.
If you are talking about the Export button in any workspace tab it's not actually what i would mean about the feature i'm asking.

**Comment by luckcolors** [comment]
Probably a better way to explain what i need is: Close the workspace and save snapshot
And next time i want to start the workspace i could select to start it from one of the snapshots i made or to start it from the original state(as it is doing now).

**Comment by TylerJewell** [comment]
@gazarenkov @slemeur Another request for having a configuration where users want their workspaces to be auto-snapshotted, and then auto-reloaded.

@luckcolors There is a long time discussion internally to the engineering team as to whether this is a viable workflow, and how it should be set up. Should it be the default, or activated by users.  Some snapshots can take a long time to make, so it can be an intrusive set of steps.

**Comment by ghost** [comment]
@luckcolors you can manually snapshot a workspace at Machine > Create Snapshot. This menu is available in machines perspective (see screenshot below):

![screenshot-beta codenvy com 2016-03-13 18-05-37](https://cloud.githubusercontent.com/assets/5337267/13729797/4d3c9844-e946-11e5-9161-95e4641ee982.png)

**Comment by TylerJewell** [comment]
@luckcolors - please see Eclipse Che 4.3 and the docs. Many parameters were added that make it possible to configure whether workspaces are automatically snapshot when the workspace is shut off.  You can also snapshot to a registry or to hard drive.
