### ISSUE TITLE
[CHE 6] Cannot create a workspace with name more than 20 symbols

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#6986]
**Reproduction Steps:**
- Try to create a workspace with name size between 21 and 100 symbol

**Observed behavior:**
The new workspace is not created  and there is an error notification.

**OS and version:**
Che(Che6 branch) 6.0.0-M1; Chrome 59.0; Fedora 25
**Failed test:** _RenameWorkspaceTest_

**Additional information:**
![teams-11-43](https://user-images.githubusercontent.com/7760565/31999738-0a66282c-b99d-11e7-86e3-df823d3286f9.gif)

**Comment by skabashnyuk** [comment]
fixed https://github.com/eclipse/che/pull/7413
