### ISSUE TITLE
Add CDT Support

### ISSUE THREAD

**Issue by scotthernandez** [eclipse-che/che#699]
Please support the CDT (as well as the JDT).

I'd like to see support for the following features:
- Intellisense
- Build
- Debugging
- Types (hierarchy)
- Call graph
- Editor/Syntax

**Comment by TylerJewell** [comment]
@scotthernandez At EclipseCon from last week, @marckhouzam began the investigation process of what would be involved in supporting CDT.  Let's go ahead and start using this thread to discuss some of the specifications that would be required.

The Che core team is going to add in a C/C++ project type in the next month with build and gdb remote debugger integration at a basic level. But until the CDT port is completed, we will miss out on important intellisense capabilities.

**Comment by scotthernandez** [comment]
@TylerJewell, 

That sounds great. As an aside, I'm excited to see support for LLDB from the CDT multicore debugger side.

While I'm not an eclipse developer I'd be happy to learn more in an effort to get CDT support working. Please call out anything that might need user testing or help.

**Comment by TylerJewell** [comment]
@scotthernandez - now that Che is adding support for the language server protocol, there will be work started on adding C/C++ with CDT as a language server available over the protocol.

**Comment by ferdaarikan** [comment]
Great news!  Looking forward to test and use this.

**Comment by TylerJewell** [comment]
@ferdaarikan - While it is not CDT itself - the cfe-dev mailing list has indicated that clang is going to have a language server shortly.  We will integrate and deploy it as soon as those builds are available.

**Comment by ferdaarikan** [comment]
@TylerJewell thanks for the update, exciting news. Following the same thread I have found a post from Doug Schaefer (cdtdoug,ca) which talks about possibility of plugging cdt into language server. 

I can see how clang may be useful to provide the some of the functionality. I am not sure if this will help with features like managed builds that cdt provides.

**Comment by TylerJewell** [comment]
I suspect that within 12 months, the landscape around language servers will be dramatically different, giving us more options to choose from.  Right now, our options feel quite limited.  So we are all in a state of wait.

**Comment by mbmcc** [comment]
It's been over a year since the last comment on this thread. Is this issue being worked? 

I just discovered **Codenvy.io** / **eclipse/che** and it is just the tool that I'm looking for with learning C++ development. 

Code completion, but especailly syntax highlighting would be great. 
<https://github.com/codenvy/codenvy/issues/1980> (related issue)

**Comment by slemeur** [comment]
Closing in favor of https://github.com/eclipse/che/issues/13698

**Comment by ferdaarikan** [comment]
In the meantime https://github.com/eclipse-cdt/cdt-vscode is happenning
