### ISSUE TITLE
Authenticating my GitHub Account with Eclipse Che Won't Work

### ISSUE THREAD

**Issue by ashajjar** [eclipse-che/che#700]
I am trying this on `eclipse-che-4.0.0-RC11` the application is installed in : `/Users/mac/Documents/Apps/eclipse-che-4.0.0-RC11`

**Docker Version**

```
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64
```

**Java Version**

```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Whenever I try to connect my GitHub account to the IDE  get the following window

<img width="987" alt="screen shot 2016-03-14 at 1 56 20 am" src="https://cloud.githubusercontent.com/assets/2855050/13730398/0464f196-e989-11e5-818c-51f39e14913a.png">

To reproduce:
1- Start a workspace.
2- workspace > Import Project 
3- Select GitHub as source control
4- Define repo URL
5- Click Import the following will show 
<img width="464" alt="screen shot 2016-03-14 at 2 10 17 am" src="https://cloud.githubusercontent.com/assets/2855050/13730431/fc34ff06-e989-11e5-8014-dd5f2067bec7.png">
6- Click OK with the check box ticked ( to generate key ) the following will show
<img width="987" alt="screen shot 2016-03-14 at 1 56 20 am" src="https://cloud.githubusercontent.com/assets/2855050/13730398/0464f196-e989-11e5-818c-51f39e14913a.png">

**Comment by ghost** [comment]
Hello,

This is fixed in current master. We will display a more helpful message.

Here are instructions on how to configure GitHub oAuth - https://eclipse-che.readme.io/docs/git#ssh-key-management

**Comment by ashajjar** [comment]
thanx I think the authentication problem is solved

**Comment by ashajjar** [comment]
I think the following is not related to the original issue but when I setup the GitHub as mentioned in the given documentation ... and try to import my project from GitHub I get this error:
<img width="1064" alt="screen shot 2016-03-14 at 12 13 55 pm" src="https://cloud.githubusercontent.com/assets/2855050/13735071/03224750-e9e0-11e5-839b-fe277109a096.png">

Which I think is related to the config on the docker image. is there any advice on this ?

**Comment by ghost** [comment]
I think this is a network related issue. Can you run git clone in the Terminal? Or just ping github.com from within a container? GitHub status page says there were no downtime at all.

Just checked on 2 different networks, GitHub import is OK.

**Comment by ashajjar** [comment]
I checked on two different networks as well and everything looks fine... but from within the container it does not work! it pings the IP but does not ping the name ... seems like no DNS is defined there, I tried to look in the output of `ifconfig` but it did not recognize the command

**Comment by ghost** [comment]
Must be some local network settings. Do you have more information on this? Output from ping or curl to github etc.

What you can do is run any Docker image, get a shell into it and try doing the same. Without Che.

**Comment by ghost** [comment]
@ashajjar do you have the same problem, when just manually running `docker run -ti codenvy/ubuntu|_jdk8 bash` and using git from within a container? What I mean is that it looks like it is not a Che specific issue.

**Comment by ashajjar** [comment]
I'll try that later at home :+1:

**Comment by symbiat** [comment]
Im running Che purely from the Docker image and when I try to connect to my GitHub account I get an error:
![screen shot 2016-05-10 at 2 30 02 pm](https://cloud.githubusercontent.com/assets/59488/15158193/ab3c867c-16bc-11e6-9af5-802cb1fbcdc8.png)
So the stock Docker image needs to be updated?

**Comment by ghost** [comment]
@symbiat if you run Che as a Docker container, it is possible to manually override properties. Create a `che.properties` file, follow docs to configure oAuth https://eclipse-che.readme.io/docs/git#ssh-key-management and then run:

`docker run -ti --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /home/user/che/lib:/home/user/che/lib-copy -v /home/user/che/workspaces:/home/user/che/workspaces -v /home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage -v /path/to/che.properties:/home/user/.che/che.properties codenvy/che`

where

`/path/to/che.properties` is an absolute path to che.properties file that you have created.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
