### ISSUE TITLE
Che Dashboard doesn't load on port 8081 when using the server name instead of IP address

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#7007]
### Description
I try to run the single user Che 5.19.0 on port 8081. But the dashboard doesn't come up if I use the DNS name of the server (my.server.at.my.company) instead of the IP address. The same works with 8080 or 8082 or any other port I tried.

### Reproduction Steps

Basically I run the below with an empty data area:

```
docker run -it --rm -e CHE_PORT=8081 -v /var/run/docker.sock:/var/run/docker.sock -v /usr/local/data:/data eclipse/che:5.19.0 init
docker run -it --rm -e CHE_PORT=8081 -v /var/run/docker.sock:/var/run/docker.sock -v /usr/local/data:/data eclipse/che:5.19.0 start
```

The output tells me that the server is available at http://myipaddress:8081.   (numerical ip address, e.g. 1.2.3.4)
If I use this URL everything is fine.
If I however use the DNS name of my server http://my.server.at.my.company:8081 the dashboard never finishes loading. It shows the "Create Workspace" Button but continues to indicate loading and the normal start screen to select a stack doesn't come up.

If I do the same with other ports (8080, 8082, ...) it works.

**OS and version:**    
Red Hat Enterprise Linux Server 7.3 (Maipo)
Operated behind company proxy

**Diagnostics:** 

In the browser it looks like it starts to go wrong with the call to http://myipaddress:8081/api/.
When it works, this call returns a JSON with the list of resources.
In the broken case, it returns this: /che-parent/assembly/assembly-ide-war/src/main/webapp/_app/IDE.html  (the file contents).

**Comment by ghost** [comment]
@ChristianSchenk711 i don't think it's some problem with Che. When dashboard comes up it tries to reach master api. Can it be something in your network that blocks it.

Meanwhile, I will try to reproduce it on my side.

**Comment by ChristianSchenk711** [comment]
Won't rule that out. However tried the following: launched a simple static webserver on port 8081 on the same machine and was able to access this properly from my browser. And anyway there seems to be some kind of connection but the wrong things come back (the IDE.html file, instead of the JSON) in this scenario.

**Comment by ghost** [comment]
@ChristianSchenk711 If you go to `http://myhostname:8081/api/` in a browser - same results? Can you share a screenshot?

**Comment by ChristianSchenk711** [comment]
Some more observations:

- I figured out that the whole thing works in Chrome. It doesn't work in Firefox only (we have Firefox 52.4.0 (32bit) here)

I pasted the URLs in the browser: 
  - when using the hostname: I get immediately redirected to some other page (judging the sourcecode: IDE.html) and a dialog pops up "Can not get workspaces. The reason: Workspace with name "" in namespace 'api' doesn't exist."
  - when using the ip: I see the JSON proper.


I logged in on the machine and used curl:
  - http://ourhost:8081/api/   returns the API description just as it should
  - http://ourip:8081/api/ returns the same stuff
  - http://ourhost_or_ip:8081/api  (no trailing slash) redirects to the dashboard.

To me it looks  a little bit like Firefox is somehow loosing the trailing slash and gets the redirected page instead of the JSON during the API call.

**Comment by ghost** [comment]
@ChristianSchenk711 jist for port 8081???

**Comment by ChristianSchenk711** [comment]
Yes. Just tested again: Currently I have Che deployed on port 8081 and 8082: if I paste http://ourhost:8082/api/ into the FIREFOX, it returns the proper api description.  If I paste http://ourhost:8081/api/ into the FIREFOX, it redirects to the page with the error dialog. 
Super strange. I also disabled our company proxy configuration just for testing, but same result.

**Comment by ChristianSchenk711** [comment]
![firefox_vs_chrome](https://user-images.githubusercontent.com/28617133/32049867-04f12452-ba4f-11e7-9d7a-5c1fede02160.png)

attached screenshot: same server, once in Chrome, once in Firefox.

**Comment by ChristianSchenk711** [comment]
Just came back to work, my browser was still open with the same pages that didn't load, pushed reload (had another thing I was about to check) and suddenly everything is working on port 8081.

I have no idea what happened but it's much more likely to be within my work environment then in Che, so I'm closing that. Sorry for wasting your time.

**Comment by ChristianSchenk711** [comment]
Just to track this: The issue popped up again and I could resolve it by clearing my browser cache. It looks like in some situation wrong data ends up in the browser cache and then it will never work unless the cache is cleared. Since I deployed different versions of Che on the same machine on this port, there might have been a wrong page cached there (from a different version?) and then this problem appeared.
