### ISSUE TITLE
[CHE6 branch] Open Declaration works only for first library file 

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#7013]
### Description
Open declaration of library classes works only for first one. E.g.  if i have class A from library, which extends another class B from the same library, Open Declaration action opens class A,  but doesn't opens for class B and any subsequent.
Example:
![screenshot_20171026_122355](https://user-images.githubusercontent.com/1651062/32045297-93073080-ba48-11e7-9b3b-1eace9b6d7fe.png)
I can not open EverrestServlet here.

**Comment by vparfonov** [comment]
If you click "Download source ..." it should work, in other case it will be fixed fot jdt.ls in https://github.com/eclipse/che/issues/7852
