### ISSUE TITLE
Paste after editor tab closing using mouse wheel

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7015]
### Reproduction Steps
1. Open a project file
2. Copy something into clipboard
3. Open another tab
4. Close just opened tab using mouse wheel

After that, text from clipboard will be pasted into first opened tab.

**Comment by RomanNikitenko** [comment]
@mmorhun is it duplicated? https://github.com/eclipse/che/issues/6840

**Comment by garagatyi** [comment]
@RomanNikitenko I think so

**Comment by mmorhun** [comment]
Yes, this is duplicate.
