### ISSUE TITLE
The Find text feature doesn't find text with '|' symbol

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7016]
**Reproduction Steps:**

- Create any workspace with project 
- **Menu** -> **Edit** -> **Find**
- Type any text with '|' symbol in the **Text to find:** field and click the **Search** button

**Observed behavior:**
Nothing happened and there is an error in the console of browser.

**Che version:** 5.20.0-SNAPSHOT 
**OS and version:** Fedora 25

**Additional information:**
![che6](https://user-images.githubusercontent.com/7760565/32047448-a33c525e-ba4e-11e7-9d59-862e642b8355.gif)

**Comment by musienko-maxim** [comment]
This is not actual for CHE6
