### ISSUE TITLE
[CHE 6] A workspace has two Workspace API installers

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7021]
**Reproduction Steps:**
- Create any workspace 
- In the workspace details click on the **Installers** tab

**Observed behavior:**
There are two **Workspace AP**I installers

**OS and version:**
Che(Che6 branch) 6.0.0-M1; Chrome 59.0; Fedora 25

**Additional information:**
![eclipse che wksp-9c2h - google chrome_020](https://user-images.githubusercontent.com/7760565/32056779-38592eba-ba6e-11e7-9098-ba86c2031513.png)
![teams-11-53](https://user-images.githubusercontent.com/7760565/32056914-8bb93622-ba6e-11e7-9f90-0fd8feae4e1a.gif)

**Comment by garagatyi** [comment]
I've added wsagent installer v 1.0.1. I believe it is the reason for 2 entries here. 
@tolusha added installers versioning in Che6. 
@ashumilova Does UD know about versioning?

**Comment by tolusha** [comment]
@garagatyi If no version is set then the latest will be used

**Comment by benoitf** [comment]
as che6 is not yet GA released, should we still keep two versions of the installer ?
it looks strange to have two versions if product is not yet GA
