### ISSUE TITLE
Improve and rework selenium tests from package 'git'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#7033]
*  _We have enough much selenium tests in the package `git` still from the second version of product, so test cases can be obsolete and cumbersome_
* _We need to reconsider exist tests and rework them, if will be such necessity_ 
* _Target of this issue is to do `git` selenium tests more compact and reliable_

- [ ] Rework GitPull test #7031

**Comment by vkuznyetsov** [comment]
There are a few independent tasks on code refactoring in 'git ' package. Let's create clear tasks for each case.
