### ISSUE TITLE
Set different color to editale part of editor

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7042]
### Description
We have some indents from the left (rulers) and right (preview) in the editor, which have the same color as editable part. Sometimes it is not comfortable. It could seem that there are some editable place before first possible symbol in a line. Also, part of a long line could be hidden behind preview bar, and it could make an effect that the line is incomplete.
![rullers](https://user-images.githubusercontent.com/15607393/32102592-bd7557ce-bb25-11e7-9b3f-d43405810331.png)

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
