### ISSUE TITLE
Create events objects which will be published as infrastructure specific

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7046]
### Description
`RuntimeStatusEvent` was designed to use it for custom runtime events that can be published by infrastructure.
For example, an event about pulling of docker image. So, docker images can be pulling simultaneously then it is not good to send event about changing of Runtime status, because actually status is `STARTING` and this event is just information event about starting, progress, finishing pulling images for machines.

So it is decided to rename `RuntimeStatusEvent` to `RuntimeEvent` and rework it in the following way:
```
public interface RuntimeEvent {
  String getType();

  RuntimeIdentityDto getIdentity();

  Map<String, String> getAttributes();
}
```
Then it may be used by the infrastructure for publishing infrastructure specific events related to Runtime such as runtime abnormally stopped event.

Events about the start, progress, finish of pulling images are machine related events. So it is needed to create the following `MachineEvent` object:
```
public interface MachineEvent {
  String getType();

  RuntimeIdentityDto getIdentity();

  String getMachineName();

  Map<String, String> getAttributes();
}
```
For such process as pulling images, it makes sense to send progress of it. `attributes` field is designed to provide additional information. Then infrastructure will be able to send progress of pulling on clients if it has such information.

Since infrastructure-specific events are introduced clients should know which custom events they can expect. So clients should be able to check which active infrastructure is now. For such purposes, it is needed to add `infrastructure` field to `Runtime` object.

**Comment by sleshchenko** [comment]
Issue is changed according to the last discussion around infrastructure specific events

**Comment by skabashnyuk** [comment]
This events can be reused during implementation https://github.com/eclipse/che/issues/5231

**Comment by sleshchenko** [comment]
@garagatyi We still haven't rework `RuntimeStatusEvent` to `RuntimeEvent` and haven't introduced `MachineEvent`. So, I don't think we can close this issue.
