### ISSUE TITLE
Add ability to highlight name under cursor

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7048]
### Description
It will be useful to have an ability to highlight word under cursor in current file.
Taking into account complexity of analyzation of different statements in different languages, let's just find occurrences for start. It doesn't require server side complicated logic (and if we have it, the current behaviour will be overridden), but brings useful feature.
An example in Lazarus:
![highlight](https://user-images.githubusercontent.com/15607393/32105058-c1701b66-bb2f-11e7-98f4-b81cd0b169c2.png)
We can add small improvement and highlight only whole word, ignoring partial occurrence (or add an setting for this behaviour). Note, that it isn't necessary that a name has spaces before/after. It could be another symbols as well (for example `.`, `->`, ...)
We have to add checkbox in the preferences which turn on/off this feature, because some people can find it pretty annoying.

**Comment by gorkem** [comment]
LSPs already provide highlights [1]. 
@tsmaeder @vparfonov do we support document highlights on Che IDE?

[1]  https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_documentHighlight

**Comment by mmorhun** [comment]
Unfortunately, we don't have LS for each language/file-type in Che yet. More, it could be some specific file-type. My suggestion is to use occurrences highlight when no LS found for edited file (and if appropriate option is turned on).
