### ISSUE TITLE
Multi-user sub-organisation workspace files not unique

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#7056]
When creating a workspace in a sub-organisation, it can be created with the same name as one in a different sub-organisation. This leads to the filesystem of these two workspaces being shared, potentially a security risk and causing confusion as to why there are already files existing in the WS.

**OS and version:**    
Che 5.19

**Comment by skabashnyuk** [comment]
related to https://github.com/eclipse/che/issues/3574
I think this is due to the fact that we string workspaces with the name in a path instead of id.

**Comment by davidwindell** [comment]
Yes, because everything is stored in `/data/workspaces/{workspacename}`. 

I suppose this could either be solved by adding the organisation (namespace) into the storage path OR restricting workspaces to one name per che-server.

**Comment by skabashnyuk** [comment]
Fixed by https://github.com/eclipse/che/issues/3574
