### ISSUE TITLE
Question : Regarding dotnet-web-simple not appear in Che 5.19.0

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#7057]
OS : 16.04.3
Che : 5.19.0
Mode : Multi-User and Single-user

**First Case**
i been using che from the first version till now, meaning that upgrade repeatly till latest version 5.19.0, but i still can't find the dotnet-web-simple.

**Second Case**
I try first done the installation on version 5.18.0 and upgrade to 5.19.0, sadly i still can't find the 
dotnet-web-simple.

**Third Case**
I deleted docker and all related files for Che, meaning that i done an installation from fresh, in this case, i can find dotnet-web-simple.

![screenshot from 2017-10-28 00-18-32](https://user-images.githubusercontent.com/1939446/32114698-ac4a1628-bb76-11e7-9610-2924e26120a0.png)

![screenshot from 2017-10-28 00-19-39](https://user-images.githubusercontent.com/1939446/32114706-b4aa3e7e-bb76-11e7-9295-4309ce5e1895.png)

**so, what wrong with Che?**

**Comment by ghost** [comment]
@thyeun check if `instance/data/templates/samples.json` has the right sample app.

**Comment by thyeun** [comment]
@eivantsov no,  that files had been not update since " Sat 22 Apr 2017 08:48:26 PM MYT ", this is why i question?

![screenshot from 2017-10-30 15-04-50](https://user-images.githubusercontent.com/1939446/32158478-ccbb0430-bd83-11e7-9909-55d855deda8a.png)

**Comment by ghost** [comment]
@thyeun probably update command does not update this file.

**Comment by thyeun** [comment]
@eivantsov @.@ so, it is consider bug?

**Comment by thyeun** [comment]
@eivantsov sorry for disturbing you, an examples like this actually very important for new user, as for me, i try to introduce Che to my colleagues and friends, but if an examples can't even work it out, than i will be very hard to promote Che to my colleagues and friends.

Even that it is a tiny issue and it won't affected anything, but once come to a reputation to promote Che, it will appear getting a bad image.

**Comment by ghost** [comment]
@thyeun I have labeled an issue as a bug. thanks

**Comment by ghost** [comment]
@thyeun right now I am considering the following:

It is possible to always override a local samples.json. However, in this case, all changes you may have made to that file (like adding own samples) will be lost.

This json file comes with the binaries, and the following check happens - https://github.com/eclipse/che/blob/c8b92fcc745ac14c733fb5ef57ec1b20b4490c6f/dockerfiles/che/entrypoint.sh#L314

In your case, updated json was never copied since the file exists as it is mounted from a local data directory into Che server container.

**Comment by thyeun** [comment]
@eivantsov , i have never add-in any extra example into the sample.json.

Question : will it be better everytime an upgrade on the version, sample.json will have to automatically delete and replace with the current version of sample.json? and for people that will add-in extra sample, he/she need to add-in extra sample into second file, or call it as user_sample.json, so it wont mix-up.

Meaning that inside the folder will have two files, sample.json and user_sample.json. and the appear at the GUI part, it will be sample (as appear now) and extra sample (add-in by user).

=.= more job for you... hahaha~

**Comment by ghost** [comment]
@thyeun yes, that will add in some complexity. I hoped to solve that on the CLI/Dockerfile entrypoint level. However, it looks like in this case only the override solution is possible.

**Comment by thyeun** [comment]
@eivantsov yes, for current solution, but why you have to do the double job? i mean why not make a "new" change for the version 6.0.0 and it will given more flexibility for new user and old user that want to advance his/her skill (learn and apply at the same times)?

**Comment by riuvshin** [comment]
@thyeun that [PR](https://github.com/eclipse/che/pull/7452) fixing samples loading issue. Just in case if you need add your own custom sample just put your own `instance/data/templates/my_custom_samples.json` this one won't be touched.
