### ISSUE TITLE
[multi-tenant] Can not create workpace against multi-tenant che-server when ssl is enabled

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#7058]
### Description
Error while creating workspaces with mt che-sever deployed on https://glusterpoc37aws.devshift.net:8443 :

> 2017-10-27 17:07:27,631[aceSharedPool-0]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 137]   - Fail pinging ws agent with http://wsagent-egrqz99hlzu1byha-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com/api/ url in workspaceegrqz99hlzu1byha workspace in machinenkwzppnuq6kfmwjd machine on localhost node.

> 2017-10-27 17:07:29,461[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.

### Reproduction Steps
Create a workpace on mt che-server deployed on https://glusterpoc37aws.devshift.net:8443  with ssl enabled: 

**OS and version:**    
https://glusterpoc37aws.devshift.net:8443 
image `rhche/che-server-multiuser/903ed59-fabric8-4ee7187`

**Diagnostics:** 
For some reason protocol for `WsAgentPingRequestFactory` returns an http url even with ssl enabled

**Comment by ibuziuk** [comment]
cc: @davidfestal

**Comment by eivantsov** [comment]
Why is ws-agent route http but not https?
