### ISSUE TITLE
Question: Mismatch in the version of Git in the Ready to go Stacks?

### ISSUE THREAD

**Issue by venkatzhub** [eclipse-che/che#7060]
### Description
I noticed that the version of Git when using the Node stack is 2.1.4, where as when using the Java stack is 2.14.1, I'm a newbie just getting started on Che, so wondering why there is a difference of Git version in each of those stacks? How can I upgrade the Git version in the Node stack? I tried adding it as a component, by specifying the version, but that did not help. 

Any help/guidance would be greatly appreciated. 

**OS and version:**    
Mac OS Sierra, Version of Che is 5.19.0 (local install)

**Comment by ghost** [comment]
@lilcubby in Che there's JGit (what you see in UI) and console Git, ie the one installed in the image. 

We do not explicitly set Git version when installing in in base stacks - https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/Dockerfile#L36

Node stack uses debian based image, and thus the latest git available in debian repos. Java stack is Ubuntu based and uses whatever latest version Ubuntu repos offer. But once again, Git in the console and UI git are two different systems.

**Comment by AndrienkoAleksandr** [comment]
I see second time that our user tries to apply some custom software and does it by applying stack "Component". I guess we need apply some better explanation about stack "Component" in the ui. Something like "Component it's only stack component description . It doesn't install any software inside stack. It describes had already installed software.". And it would be nice to apply link to the documentation, where is user can read how to create custom stack with custom software. @eivantsov @akurinnoy What do you think? I guess without explanation It's not obviously...

**Comment by venkatzhub** [comment]
@eivantsov - Thanks for the response, I now get why the Git version is different in both the stacks, with that said, would it be possible to know what the user would be getting when picking a stack? For e.g I do see what version of Node or NPM I would get, but there is no indication of the Git version - and the fact that there is JGit which is different from the console Git would make it even more important to have a way to know which version of Git the user is getting as part of a stack. 

I do need the console Git, and the latest version of it - so based on what you said, my choice would be create a stack based on the base stack recipe but specify the Git version I desire?

**Comment by venkatzhub** [comment]
@AndrienkoAleksandr - The way the Component UI is set up - it is indeed very confusing, so an explanation would be very helpful. I'm surprised that I'm the second user - the natural instinct seeing that UI is to think and assume - you are "adding" a component with a specific version to an existing stack. Thanks for the quick responses ! Appreciate it!!

**Comment by ghost** [comment]
Well, there's a tooltip saying it's a mere description of the stack. Closing it. However, I think we will revise components nature in stacks
