### ISSUE TITLE
Unable to upload SSH key in multi-user Che

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#7061]
Try to upload a VCS private key in a multi-user workspace. The request responds with a 403 error, possibly due to the missing user token from the request?

**OS and version:**    
Che 5.19 (multi-user)

**Comment by skabashnyuk** [comment]
>>Try to upload a VCS private key in a multi-user workspace

More concrete how?

**Comment by davidwindell** [comment]
@skabashnyuk like this http://www.eclipse.org/che/docs/ide/git-svn/index.html#use-existing-ssh-keys

**Comment by skabashnyuk** [comment]
What image or stack you are using in this case?

**Comment by ghost** [comment]
@skabashnyuk stack should not matter here since the key is saved to user prefs and jgit fetches (or at least should) everytime it needs it.

I'll check it myself and update the issue

**Comment by davidwindell** [comment]
I would say this is a blocking bug.

![screenshot from 2017-10-30 10-38-52](https://user-images.githubusercontent.com/1720090/32166755-ba8c2660-bd5e-11e7-9017-d2f5480c0f9e.png)

**Comment by ghost** [comment]
Labeled as a bug.
