### ISSUE TITLE
why not allow "_" in name, when create workspace

### ISSUE THREAD

**Issue by liuxihua** [eclipse-che/che#7065]
when create new workspace with a name “a_a”,

it will show the error information "The name should not contain special characters like space, dollar, etc. and should start and end only with digits, latin letters or underscores."

but name like "a-a" is allowed.

It seams a lit bit strange,  and why?

**Comment by ghost** [comment]
@liuxihua the error message is wrong indeed, since an underscore isn't allowed.

@ashumilova this should be an easy fix. Btw, why is underscore not allowed?

**Comment by SkorikSergey** [comment]
Underscores in workspace name allowed if rename workspace from its workspace details.
![nimbus-record-video-2018-04-26-17-05-35](https://user-images.githubusercontent.com/7760565/39310901-43909a6c-4974-11e8-9873-46171a2e03da.gif)
