### ISSUE TITLE
How to debug Che deployed on OpenShift?

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7066]
### Description
Sometimes I need to debug Che server on some OpenShift flavor, e.g. MiniShift. 
And when I debug Che OpenShift kills the Che master container due to the failure of liveness probes. 
We need to have a way how to do debug on an OpenShift in a painless way. 

BTW solution I used before is removing liveness probes.
### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@l0rd @ibuziuk @riuvshin @sleshchenko FYI

**Comment by riuvshin** [comment]
seems liveness probes should be changed somehow, but Im not sure.

**Comment by l0rd** [comment]
What I would do is set liveness probe timeout to 1h if `CHE_DEBUGGING_ENABLED` is set to `true` in `deploy_che.sh`

**Comment by garagatyi** [comment]
@l0rd I like the idea! @riuvshin wdyt?

**Comment by riuvshin** [comment]
@riuvshin likes the idea!

**Comment by sleshchenko** [comment]
@garagatyi Can it be removed since you merge a PR where probes is removed is `--debug` option is specified https://github.com/eclipse/che/pull/11409?
