### ISSUE TITLE
[CHE 6] The active tab from the Processes area isn't restored correctly after refreshing web page

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7072]
**Reproduction Steps:**
1. Create a workspace from the **Java** stack with the **web-java-spring** project.
2. Start the "**web-java-spring:build and run**" command and wait that building is finished.
3. Refresh the web page.

**Expected behavior:**
After refreshing the "**web-java-spring:build and run**" tab is active

**Observed behavior:**
1. The "**dev-machine**" tab is active.
2. In the "**web-java-spring:build and run**"  tab preview url is missing(see screenshot below).

**OS and version:**
Che(Che6 branch) 6.0.0-M2; Chrome 59.0; Fedora 25
**Failed test:** : WorkingWithNodeWsTest

**Additional information:**
![teams-11-57](https://user-images.githubusercontent.com/7760565/32167729-7c83bf22-bd72-11e7-830f-1f425df9a60a.gif)

![eclipse che wksp-4k1l - google chrome_026](https://user-images.githubusercontent.com/7760565/32167471-98e3b88a-bd71-11e7-8b79-3baf57eaa0b4.png)

**Comment by SkorikSergey** [comment]
This issue is reproduced.

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy could you take a look - is this regression related to last changes in ProcessesPanelPresenter within [the PR](https://github.com/eclipse/che/pull/7396)?

**Comment by slemeur** [comment]
I confirm this issue is a regression.

**Comment by vitaliy-guliy** [comment]
Will be fixed

**Comment by AbhiGit89** [comment]
Hi,
I am not able to get preview url of a application which i am trying to run into eclipse che workspace.
Is preview url issue has been resolved in che 6.0.0-M2 version?
Previouslly it is reported at below link.
https://github.com/eclipse/che/issues/7072

**Comment by RomanNikitenko** [comment]
@AbhiGit89 yes, preview url issue has been resolved for 6.0.0-M2 version: https://github.com/eclipse/che/pull/7108

**Comment by RomanNikitenko** [comment]
@AbhiGit89 do you have the issue with preview url for your application only or for che samples as well?
