### ISSUE TITLE
[CHE6 branch] Project root folder duplicate is created after rename project

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7086]
### Reproduction Steps
 - Run Java stack with default spring project
 - Rename project
 - Pay attention to the project explorer

**Expected behavior:**
Project will be renamed 

**Observed behavior:**
Project is renamed but duplicated root folder is created

**OS and version:**    
Che(che6 branch) 6.0.0-M1 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![eclipse che wksp hmoh](https://user-images.githubusercontent.com/22724619/32175751-8473556e-bd8e-11e7-9d9d-13b0eafb2e3e.png)

**Comment by Ohrimenko1988** [comment]
Can not reproduce

**Comment by SkorikSergey** [comment]
This issue reproduces in Che 6.2.0.
![nimbus-record-video-2018-03-01-16-48-43_1](https://user-images.githubusercontent.com/7760565/36851535-1978fce8-1d72-11e8-9d97-450c12b70327.gif)

**Comment by Ohrimenko1988** [comment]
This particular issue has fixed. But it can be related to https://github.com/eclipse/che/issues/9393
