### ISSUE TITLE
Che deploy to Openshift script doesn't check whether OpenShift is ready

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7087]
### Description
deploy_che.sh script doesn't check whether OpenShift is ready, e.g. registry service is running. Because of that deployment of Che fails when it is done right after the start of MiniShift or OCP on Docker. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@riuvshin @l0rd @davidfestal @ibuziuk  FYI

**Comment by sr229** [comment]
Do we need to listen for `/healthz` like K8s, or theyhave a different liveness probe API?

**Comment by garagatyi** [comment]
Outdated
