### ISSUE TITLE
Unify the way how che-server image is configured

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#7094]
### Description
In Che 6 we introducing infrastructures as a first level citizens. 
It happened that easiest and most widely way to provide configuration become an environment variables. In our configuration framework, we have this support.
The sequence are following :
1. che.properties inside of war.
2. che.properties in CHE_CONF dir
3. System variables
4. Environment variables.

In times of Che5 where docker was our primary target we used che.properties
https://github.com/eclipse/che/blob/master/assembly/assembly-main/src/assembly/assembly.xml#L162-L165
and put it outside of war. Also, we doing some other actions with this file in 
https://github.com/eclipse/che/blob/master/dockerfiles/che/entrypoint.sh#L247-L292

this way make a couple of difficulties.
1. Not all configuration parameters of che-dev image is configured with environment variables
2. Changes default values in che.properties inside of war have no effect of existed installation.
3. It brings difficulties for developers in understating where actually properties are located.
4. It revert's upside down original concept of default values packaged in war and managed by authors of code.

**Comment by skabashnyuk** [comment]
After some discussions with @riuvshin  we have such proposal.
Remove default che.properties extraction from CLI in Che6. 
All properties have to be configured from che.env. If user wants to configure some additional 
properties he can do that by adding additional values to che.env.

@benoitf please validate this idea and let me know if you have some concerns.

**Comment by benoitf** [comment]
@skabashnyuk I'm perfectly fine

**Comment by davidwindell** [comment]
Will env vars still work as overrides?

**Comment by benoitf** [comment]
@davidwindell I would say yes

**Comment by skabashnyuk** [comment]
@davidwindell I confirm - yes env vars still work as overrides
The schema will be
1 .defaults che.properties inside of war.
2. che.properties in CHE_CONF dir
3. System variables
4. Environment variables.
