### ISSUE TITLE
Add ability to prevent closing of Che tab

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7098]
### Description
Sometimes a browser tab with Che could be closed occasionally. It would be nice to add an ability to ask user before tab closing. To not to brake current behaviour let's add a flag into preferences.

**Comment by sleshchenko** [comment]
For me, it usually happens when I try to use Ctrl+W hotkey in a terminal for clearing word before the cursor. And suddenly IDE tabs becomes closed. :sob:

**Comment by azatsarynnyy** [comment]
Please take into account the [existing check](https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/editor/EditorAgentImpl.java#L187-L196) that prevents closing browser's tab when some editor has unsaved content. It probably makes sense to remove it.

**Comment by mmorhun** [comment]
Done
