### ISSUE TITLE
Bootstrapper uses bash as shell interpreter

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7124]
Currently, bootstrapper uses `/bin/bash` as the only shell interpreter which makes it impossible to run workspaces that have no bash installed.

Bootstrapper should be configured to use shell interpreter from the container just like other agents.

**Comment by benoitf** [comment]
it's an issue for UD diagnostics component which uses the tiniest jdk8 alpine image (which has no bash)

**Comment by ghost** [comment]
@benoitf yeah, right now we workaround it by installing bash - so adding a new line in a Dockerfile. @akurinnoy is working on it

**Comment by benoitf** [comment]
@eivantsov yes I've commented in the UD PR.
I'm commenting here to be sure that when this issue will be fixed, the 'workaround' on UD will be deleted as well as it will add delay at runtime each time the workspace is launched.

**Comment by ghost** [comment]
Sure, it's temporary

**Comment by garagatyi** [comment]
@eivantsov @benoitf can you add removal of workaround to the issue description with the link to the code when PR is merged?

**Comment by benoitf** [comment]
the line with apk add bash should be removed at https://github.com/eclipse/che/blob/def395d61420c9543b34f1b58496b22f947f8aa3/dashboard/src/app/diagnostics/test/diagnostics-workspace-start-check.factory.ts#L182

**Comment by garagatyi** [comment]
@benoitf tnx
