### ISSUE TITLE
[Multiuser] The Edit account button is not work in CHE multiuser

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7125]
**Reproduction Steps:**

- From the **Dashboard** open the **Account** page
- Click the **Edit** button

**Observed behavior:**
There is "**No access**" error

**Che version:** 5.21.0-SNAPSHOT **Multiuser**
**OS and version:** Fedora 25

**Additional information:**
![teams-11-64](https://user-images.githubusercontent.com/7760565/32273635-e7bfe6f4-bf0b-11e7-92fa-edf72b17c249.gif)

**Comment by mshaposhnik** [comment]
Fixed;
