### ISSUE TITLE
Improve DtoGenerator to annotate overridden methods

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#7132]
There are a lot of messages outputted during Che build about missed `@Override` annotations on the generated DTO implementations.
![image](https://user-images.githubusercontent.com/1636395/32280226-d282adb8-bf23-11e7-8e77-9539cd5920e7.png)

DtoGenerator should be fixed to annotate overridden methods with `@Override` or annotate generated classes with `@SuppressWarnings("MissingOverride")`.

I've tried to build Che with disabled Error Prone plugin (to avoid outputting these compilation warnings) and reverted [fix](https://github.com/eclipse/che/commit/da1895f0c25815d1c658e160df4857f71c9dc83f) that limits the amount of output in IDE. As a result, browser's tab with IDE was frozen much less time during Che build.

**Comment by gazarenkov** [comment]
Good point and investigation, thanks!
I'd qualify it as a bug of P1 severity b/c it looks really bad and impacts on performance (as you mentioned)
