### ISSUE TITLE
Can not Launch che with docker run -it eclipse/che start

### ISSUE THREAD

**Issue by hargoniX** [eclipse-che/che#7136]
I am trying to install/run che on a raspberry pi 3 with Raspbian stretch on it. Whenever i run docker run -it eclipse/che i get, after some time, the error: standard_init_linux.go:195: exec user process caused "exec format error"

**Comment by ghost** [comment]
@hargoniX Che CLI uses images that are not compatible with ARM7 arch. There were people in the community who ran Che on Pi though. You may want to take a look at [this blog post](https://blog.benjamin-cabe.com/2016/04/01/running-eclipse-che-on-a-raspberry-pi)

**Comment by hargoniX** [comment]
That worked perfect for me thank you @eivantsov

**Comment by kartben** [comment]
Great to see my post is still useful 😄
