### ISSUE TITLE
Project tree loses selection  

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#7143]
### Description
Some actions are required selected item in project tree to be enabled.
For example, 'Find' action is disabled when project tree has lost selected item.
### Reproduction Steps
1. Select some item in project tree.
2. Use Edit ----> Find action to find some text
3. After displaying search result try to use Ctrl+Shift+F hot key to call 'Find' action again
Also you can see in Edit menu that 'Find' action is disabled at this moment.

Click in project tree resolve the problem, but it's very annoying to click in project tree each time you need to call some action.

**OS and version:**    
Fedora 25
Che version: 6.0.0-M2
mounted project
![selection_lose](https://user-images.githubusercontent.com/5676062/32320741-6ed7e306-bfc7-11e7-8d68-d089aa760a15.gif)

**Comment by vinokurig** [comment]
Also it can be reproduced when selecting `External libraries` of a project in the project explorer

**Comment by RomanNikitenko** [comment]
The both described cases are not reproduced for 6.1.0
