### ISSUE TITLE
Cursor jumps in the beginning of file at using Content Assist action 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#7146]
### Description
Sometimes cursor is set at the beginning of a file at using Content Assist action

**OS and version:**    
Fedora 25
Che version: 6.0.0-M2
mounted project

![content_assist_cursor](https://user-images.githubusercontent.com/5676062/32321983-98202e4a-bfcb-11e7-8153-fd26133742fd.gif)

**Comment by mmorhun** [comment]
Also, after such error occurs, there is a notification about external change of the edited file.
