### ISSUE TITLE
Error creating simple java project in che

### ISSUE THREAD

**Issue by vitenlonkar** [eclipse-che/che#715]
I am unable to create a java project in the workspace created using **java-stack**. Whenever I create a new java project it gives me an error saying project name already exists. But when i try to create a java project in the workspace created using **php-stack** the project is created successfully. Any idea on what could be the issue?

**Comment by ghost** [comment]
What is your OS? Do you run Che as root?

**Comment by vitenlonkar** [comment]
My Os is Ubuntu and i am running che as root.

**Comment by ddementieva** [comment]
Can you please try to run `sudo chown -R user:user /projects` command in the Terminal after the workspace has started? 

You can find more details in the similar issue at https://github.com/eclipse/che/issues/693

**Comment by vitenlonkar** [comment]
Thank you *_eivantsov *_and *_ddementieva *_.. Finally the project is created. Also got the desired output..

**Comment by ghost** [comment]
We're thinking of the best way to handle such situations. Will come up with some solution pretty soon.

**Comment by vitenlonkar** [comment]
Yes a full proof solution is required. Because every time I create a new work-space I have to run the command which is not recommended for automating the development environment.

**Comment by ghost** [comment]
This pull request should fix it - https://github.com/eclipse/che/pull/754

I am closing the issue. You may try the latest nightly build. Feel free to reopen if it does not work for you.
