### ISSUE TITLE
IDE memory consumption grows and the tab becomes crashed

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#7151]
### Description
After using of IDE and leaving it for some time opened, the tab with IDE becomes crashed and the memory consumption is continuously increasing. In my case, there is no any huge process in IDE (like maven build), there is only imported and configured Che project, three open files and one terminal tab.

Environment:
- single user Che
- branch che6 with the following state https://github.com/eclipse/che/tree/6d06d10273
- A workspace with 1 machine(6gb RAM) that is created from Default Java stack with JDK 8, Maven and Tomcat.

### Reproduction Steps
Open IDE and leave it for a while.
**Expected:** IDE works as well
**Actual:** the IDE tab is crashed.
Take a look at the following screenshot
![screenshot_20171102_143052](https://user-images.githubusercontent.com/12269156/32326448-83166810-bfdb-11e7-84b8-314dd30614ad.png)

**Comment by artaleks9** [comment]
Still actual for ver.6.5.0

**Comment by SkorikSergey** [comment]
![workspace 1_001](https://user-images.githubusercontent.com/7760565/39918441-1af12e86-5519-11e8-805e-0cb068f8e0cb.png)

**Comment by SkorikSergey** [comment]
Issue with similar behavior:
-  Che IDE locks up https://github.com/eclipse/che/issues/9477.

**Comment by vparfonov** [comment]
Looks like I also reproduce this issue, important step "Link with editor" feature must be turn on
