### ISSUE TITLE
Debug toolbar looses pictograms

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7153]
### Reproduction Steps
1. Open debug panel
2. Click `Run` in the Main Menu

Debug toolbar looses most of pictograms.
![screenshot from 2017-11-02 15-23-42](https://user-images.githubusercontent.com/15607393/32328239-06bb7e52-bfe2-11e7-8e9b-325eed93867e.png)

**OS and version:**  Fedora 25, Che 6.0.0-M2, mounted project

**Comment by tolusha** [comment]
Fixed https://github.com/eclipse/che/pull/7204
