### ISSUE TITLE
[CHE 6] Add an ability to scroll to a file that is opened in the editor

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7163]
### Description
Add an ability to scroll to a file that is opened in the editor.
There is an ability to link editor and project tree. But I don't like it because of unnecessary switching of selection in the project tree which distracts my attention. It also requires some resource to perform refreshing of project tree each time when an active file in the editor is changed.
It would be better to provide an ability to scroll to a file that is opened in the editor once when a user needs it.

**Comment by mmorhun** [comment]
I also miss this feature. +1
I would say navigate instead of scroll because it could be folded and noting to scroll to. Sometimes it is needed to expand folders before scroll.

**Comment by RomanNikitenko** [comment]
Some part of discussion this feature here: https://github.com/eclipse/che/issues/6932
