### ISSUE TITLE
The background of a project with visible test - sources looks unreadable 

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7165]
**Reproduction Steps:**
* Clone CHE project and open a module with test sources. Looks on screenshot: the 'green' background and selection for a file with linked editor look strange as for me.
![selection_015](https://user-images.githubusercontent.com/1640058/32335557-cd22c376-bff5-11e7-8325-799e4bd95117.png)

**Che version:**  Che version: 6.0.0-M2, chrome browser, Fedora 25

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
