### ISSUE TITLE
[CHE6 branch] In the light theme some toolbar items are not available

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7168]
### Description
* Select light theme in the IDE. Apply it and enable toolbar. The delete/cut/copy commands are not shown.
![scr9](https://user-images.githubusercontent.com/1640058/32338634-07f2f2de-bffe-11e7-965e-bf14bbb32a97.png)

**OS and version:**  Che version: 6.0.0-M2

**Comment by SkorikSergey** [comment]
It looks like the toolbar items are not available if do any operations with the context menu from the project.
The same issue is with the **Dark theme** too.
![teams-11-73](https://user-images.githubusercontent.com/7760565/32363671-1e9129c2-c079-11e7-8ee9-1128fa2d9528.gif)

**Comment by RomanNikitenko** [comment]
@musienko-maxim @SkorikSergey may be duplicate https://github.com/eclipse/che/issues/7078

**Comment by RomanNikitenko** [comment]
So I'm closing as duplicate #7078
