### ISSUE TITLE
Problem on debugging of IDE extension 

### ISSUE THREAD

**Issue by peppiss** [eclipse-che/che#7171]
### Description
Hi guys, I’m facing some problems during debug.
I prepared a little test to extend the ide in order to manage a new file extension and opening it on editor but customizing the syntax highlighting.

I’m using the 5.21.0-Snapshot and I started from this example:
https://github.com/lgas/fpp-editor

Unfortunately I’m stuck, because adding the method with syntax regex in order to customize the highlighting the file doesn’t show the editor page , instead if I remove this method from the class
https://github.com/lgas/fpp-editor/blob/master/plugins/che-plugin-fpp-editor/che-plugin-fpp-editor-ide/src/main/java/org/eclipse/che/plugin/fpp/editor/ide/FppJSEditorExtension.java
All work fine and the editor window is showed normally.

How I can debug this plugin by my IntelliJ ? Workspace? I didn’t found documentation only the page on official site but it’s very poor, anyway I’ve already configured the gwt run configuration, and I’m able to start the super dev mode and also to recompile the module , but after this how to start the debugging using some break points on sources?

**Comment by ghost** [comment]
@vparfonov @svor can you help please?

**Comment by peppiss** [comment]
Hi all ,
another question is  : where i can found the standard output log for the plugin extensions execution ??
I putted a simple sys.out on one method of FppJSEditorExtension.java but I didn't find it on logs .... 
I'm missing something I'm sure .... but what???
thanks

**Comment by AndrienkoAleksandr** [comment]
Log for client side (will be print in the browser console): 
org.eclipse.che.ide.util.loging.Log(getClass(), "your log text");

**Comment by peppiss** [comment]
thanks a lot ! it's a useful trick to start my debug! 
For sure I'd like to debug using GWT and IntelliJ but it's a nightmare , i don't find any docs or guide to do it , I'm searching on google since yesterday , but nothing ..... i don't understand if it's possible maybe no.... but for other application based on GWT it's more simple , just set the run configuration.
for this project there are a lot of submodules and i don't understand how configure GWT to debug for example the che-sample-plugin-json-parent project .... :-(
Some one could explain to me??

**Comment by peppiss** [comment]
Other interesting topic is : every changes on plugins source code (for example adding a log row on method of one of java class inside on che-sample-plugin-json-parent project) need the rebuild of Assembly (if i understand well) and run the new assembly on Che CLI (based on Docker) but the building of Assembly module needs a lot of time!!!!! specially to rebuild the permutations....
It's the correct process or I'm wrong something???

Thanks again!

**Comment by svor** [comment]
Hi @peppiss!  Have you seen this documentation: https://github.com/eclipse/che/wiki/Development-Workflow#debugging-che-ide-extensions ?

**Comment by svor** [comment]
If your changes are on client side you just need to recompile by GWT super dev mode, you don't need to rebuild all assembly. And If you'll have some problems with configuring super dev mode, please feel free to ask me.

**Comment by ghost** [comment]
Here are some docs https://github.com/eclipse/che/blob/master/ide/README.md
