### ISSUE TITLE
Runtime error with Java 9

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#7177]
### Description
When using Java 9 to launch Eclipse Che, there are errors 
NoClassDefFoundError for javax.activation package and also for javax.xml.bind

it's because Java runtime disable by default access to javax.* API

Fix can either be:
 - add the `-add-modules java.activation --add-modules java.xml.bind` option at runtime
 - package activation.jar / jaxb implementation in the war file so there is no need to expose API from the JVM

### Reproduction Steps
Run Che with Java9 runtime

**OS and version:**    
macOS High Sierra

Related to epic #5326

**Comment by tsmaeder** [comment]
I would prefer the first option, if the jar is already there, why duplicate it? Are there any downsides to this?

**Comment by benoitf** [comment]
Option 1 allow to not increase size of war files as dependencies are provided by the JVM. The only downside of this approach is that each JVM may provide its own implementation of javax.activation and jaxb so it may not work for Che. (But in reality most of the JVMs are providing the same implementations and for Che stack we're always using the same vendor so downside is pretty null)

**Comment by benoitf** [comment]
Fixed
