### ISSUE TITLE
Build fails with symbolic links under windows

### ISSUE THREAD

**Issue by zenobios** [eclipse-che/che#718]
We tried to build one of our web applications with Eclipse Che. The build fails because one of the maven plug-ins we use (https://github.com/eirslett/frontend-maven-plugin) needs to create symlinks in the directory of our project. If we trigger the build on a Windows 10 host, it fails.

Steps to reproduce (in Windows):
1. Create a new workspace and import project from https://github.com/akoch/che-symlink-problem.git
2. Create a new maven command with 'Command line' -> 'compile'
3. Execute the command

The resulting error message is: 

> "Could not extract the Node archive: Could not extract archive: '/projects/che-symlink-problem/node/node_tmp/node.tar.gz': No such file or directory
> This message is misleading. The failing reason is an error when a symlink is created while the node.js-archive is unpacked."

**Comment by ddementieva** [comment]
We'll check it on Linux. However, it looks like this is OS specific docker issue.

Update: works on Linux and Mac. Will test on Windows 8 and 10. Pretty sure it's because when a process in the container attempts to create a symlink it fails as this directory is mounted from Windows filesystem.

**Comment by ghost** [comment]
Cannot reproduce on Win8 with `mvn compile` and it does fail with `mvn clean install`.

If you take Che out of the equation and just run codenvy/ubuntu_jdk8 with your project sources mounted into it, I suspect there will be the same outcome. Certain file system operations aren't permitted for Windows.

There's a fix though - http://www.ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/ - enable symlink in virtualbox settings.

Let me know if this helps

**Comment by zenobios** [comment]
Setting the extra data in virtualbox as described in http://www.ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/ was not necessary since someone (either docker or Che itself) is already setting this extra data.

However, to get symbolic links working within Che, both Che and virtualbox have to be started in elevated mode which might not be the best idea.

After being able to create symbolic links, we ran into the next trouble concerning long paths: we were not able to extract a the tar.gz file which was downloaded by the frontend-maven-plugin because of too long path names. To solve this issue, a possible workaround is explained here https://www.virtualbox.org/ticket/11976. Although it could be possible to re-mount the shared folder using the syntax described in the virtualbox defect programmatically, I’m not sure what other side effects this might have concerning non-working relative paths (see https://www.virtualbox.org/ticket/11976#comment:1)

**Comment by TylerJewell** [comment]
@zenobios - going to close this issue as we are moving to a pure docker running model with volume mounts where symbolic links are supported.  You will not need virtualbox for docker anymore.

https://github.com/eclipse/che/pull/1683
