### ISSUE TITLE
[CHE-6][Regression] The item from maven module does not appear in autocomplete proposal in some specific cases

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7187]
### Description
Import the project:
* Clone the project: https://github.com/Tarrantella/check-maven-plugin-test.git
* Expand Project nodes like on screenshot:
![image](https://user-images.githubusercontent.com/1640058/32452067-2cbb782c-c321-11e7-83cc-05d6cbfac920.png)
* Create TestClass.java in the hello package
* Open Aclass.java. Type ```Test``` and launch autocomplete.
**Expected result:** TestClass from hello package  should present in the autocomplete proposal.
**Actual result:** There is no expected item

**OS and version:**   Fedora 25, chrome browser, Che-
CheckMavenPluginTest
**Diagnostics:**

**Comment by ghost** [comment]
@musienko-maxim can you please add more info and set labels - the issue does not look good now.

**Comment by artaleks9** [comment]
Right now the bug is not reproduced
