### ISSUE TITLE
Can't find any GWT Modules on this page.

### ISSUE THREAD

**Issue by feitiange** [eclipse-che/che#719]
when I try to use super dev mode to debug assembly-ide-war, everything is okay in localhost:9876, and I add dev mode on bookmark, and then, In IDE page, I got the error like this:
"Can't find any GWT Modules on this page."

Eclipse version: 4.5
gwt version: 2.7
che: 4.0.0-RC11
arguments: -noincremental 
                   -src target/generated-sources/gen
                   -src D:/che-source/che-ide-extension/src/main/java
                   org.eclipse.che.ide.IDE

**Comment by vitaliy-guliy** [comment]
Try to open IDE in dedicated window, not in dashboard frame.
Use http://localhost:8080/ide/your_workspace 
instead 
http://localhost:8080/dashboard/#/ide/your_workspace

Also try to change arguments on '-noserver -noincremental'.

**Comment by feitiange** [comment]
thanks very much

**Comment by feitiange** [comment]
I think it should be write in README

**Comment by TylerJewell** [comment]
@eivantsov Let's take an issue to update this in the docs where we teach people how to set up super dev mode.  I agree that we need to educate people to use the direct /ide syntax instead of the managed dashboard syntax.

**Comment by ghost** [comment]
@TylerJewell this will be part of develop Che extensions using Eclipse and IntelliJ.

**Comment by pethirajan-apptium** [comment]
@eivantsov  and @TylerJewell I am developing extension for 4.4.0 and using IntelliJ IDEA. I followed the instructions from https://eclipse-che.readme.io/docs/setup-che-workspace but it ends up as "Can't find any GWT Modules on this page." I tried "http://localhost:8080/ide/your_workspace " but this will reload to http://localhost:8080/dashboard/#/ide/your_workspace and will still give me the same message.

**Comment by rnavagamuwa** [comment]
@pethirajan-apptium use `http://localhost:8080/ide/your_username/your_workspace` default username would be **che** so use `http://localhost:8080/ide/che/your_workspace`. But this url pattern is not working in 4.5-RC1. @TylerJewell  and @eivantsov any suggestions?
