### ISSUE TITLE
Che6 : with macOS Che is connecting to internal ip

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#7191]
### Description
On macOS, che is using internal IP instead of "localhost"

### Reproduction Steps
Run che6 on macOS

**OS and version:**    
macOS

**Comment by garagatyi** [comment]
From what we found with Sergii today is that external IP is used actually. 
But internal IP is used on links generation and it is because of changed code of links generation.

**Comment by benoitf** [comment]
I've also issue with new beta of docker (edge channel). I may open a separate issue on that.
