### ISSUE TITLE
Create ci job for working wit jdt.ls extension

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#7202]
Now we have own extension of jdt.ls -  https://github.com/eclipse/che-ls-jdt, so we should create ci job for getting artifact in che project when jd.ls is starting. The location of the artifact is: `che-ls-jdt/org-eclipse-che-jdt-ls-extension/jdt.ls.extension.product/target/distro/jdt-language-server-latest.tar.gz`

**Comment by riuvshin** [comment]
ci job is ready https://ci.codenvycorp.com/job/che-ls-jdt-ci-master/
but please note that build are failing due to unknown for me reasons.

**Comment by benoitf** [comment]
https://ci.codenvycorp.com/job/che-ls-jdt-ci-master/ws/org-eclipse-che-jdt-ls-extension/jdt.ls.extension.test/target/work/data/.metadata/.log (headless issue)

**Comment by riuvshin** [comment]
yeah, fixed build by enabling xvfb
