### ISSUE TITLE
Unable to start workspace that is stopped..

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#7205]
Eclipse-Che -version:5.19.0 

Docker version: 1.13.1,

Host OS:RHEL 7.2

Getting below error:
[STDOUT] 2017/11/06 12:47:59     - Activity tracking enabled: true
[STDOUT] 2017/11/06 12:47:59   Authentication
[STDOUT] 2017/11/06 12:47:59     - Enabled: true
[STDOUT] 2017/11/06 12:47:59     - Tokens expiration timeout: 10m
[STDOUT] 2017/11/06 12:47:59   Workspace master server
[STDOUT] 2017/11/06 12:47:59     - API endpoint: http://che-host:9500/wsmaster/api
[STDOUT] 2017/11/06 12:47:59 
[STDOUT] 2017/11/06 12:47:59 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/11/06 12:47:59 Terminal routes:
[STDOUT] 2017/11/06 12:47:59 ✓ Connect to pty(webscoket) ............... GET    /pty
[STDOUT] 2017/11/06 12:47:59 
[STDERR] rm: cannot remove '/home/user/che/ws-agent/conf': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/logs/archive/2017/11': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/temp': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/META-INF/maven/org.eclipse.che.assembly-multiuser': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/codenvy': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/org/eclipse/che/wsagent': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/work/Catalina': Directory not empty
[STDOUT] Listening for transport dt_socket at address: 4403

Server logs:
2017-11-06 12:47:57,295[aceSharedPool-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.exec' agent at workspace workspaceperacpqtr5h0tcw8
2017-11-06 12:47:59,630[aceSharedPool-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.terminal' agent at workspace workspaceperacpqtr5h0tcw8
2017-11-06 12:48:01,869[aceSharedPool-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 676]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspaceperacpqtr5h0tcw8
2017-11-06 12:51:02,865[aceSharedPool-9]  [ERROR] [o.e.c.a.agent.WsAgentLauncher 137]   - Fail pinging ws agent with http://10.0.0.79:34778/api/ url in workspaceperacpqtr5h0tcw8 workspace in machinebqrkkpe8g8v4awf8 machine on localhost node.
2017-11-06 12:51:08,424[aceSharedPool-9]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
org.eclipse.che.api.core.ServerException: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.
        at org.eclipse.che.api.agent.WsAgentLauncher.launch(WsAgentLauncher.java:143)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:681)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1048)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:262)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Commnad used to run Eclipse-che:
docker run -d  --name chemultiusernew -e CHE_DOCKER_IP_EXTERNAL=10.50.68.49 -e CHE_MULTIUSER=true -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://10.50.68.41:8089/auth -e CHE_KEYCLOAK_REALM=Test -e CHE_KEYCLOAK_CLIENT__ID=openshiftio-public -p 9090:9500 -e CHE_PORT=9500 -e CHE_DOCKER_NETWORK=che9500_che-network -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start

**Comment by LahariGuntha** [comment]
Hi,

Firstly I started creating workspace using "Java-mysql" stack.I imported some github project into my workspace.My workspace is now up and running.Now I stopped my workspace.

when I stopped my workspace Eclipse-che is itself creating a snapshot.It created snapshot succesfully and stopped the workspace.

A pop up comes saying that Work space is not running. With a "start" button and with a checkbox "Use latest snapshot".

Here when I uncheck the checkbox and start the workspace ....It is getting started properly.

But if the "Use latest snapshot" is checked and now if I started the workspace it is throwing Error like below:
[STDOUT] Exec Agent binary is downloaded remotely
[STDOUT] 2017/11/08 05:01:28 Exec-agent configuration
[STDOUT] 2017/11/08 05:01:28   Server
[STDOUT] 2017/11/08 05:01:28     - Address: :4412
[STDOUT] 2017/11/08 05:01:28     - Base path: ''
[STDOUT] 2017/11/08 05:01:28   Authentication
[STDOUT] 2017/11/08 05:01:28     - Enabled: true
[STDOUT] 2017/11/08 05:01:28     - Tokens expiration timeout: 10m
[STDOUT] 2017/11/08 05:01:28   Workspace master server
[STDOUT] 2017/11/08 05:01:28     - API endpoint: http://che-host:9500/wsmaster/api
[STDOUT] 2017/11/08 05:01:28   Process executor
[STDOUT] 2017/11/08 05:01:28     - Logs dir: /home/user/che/exec-agent/logs
[STDOUT] 2017/11/08 05:01:28 
[STDOUT] 2017/11/08 05:01:28 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/11/08 05:01:28 Process Routes:
[STDOUT] 2017/11/08 05:01:28 ✓ Start Process ........................... POST   /process
[STDOUT] 2017/11/08 05:01:28 ✓ Get Process ............................. GET    /process/:pid
[STDOUT] 2017/11/08 05:01:28 ✓ Kill Process ............................ DELETE /process/:pid
[STDOUT] 2017/11/08 05:01:28 ✓ Get Process Logs ........................ GET    /process/:pid/logs
[STDOUT] 2017/11/08 05:01:28 ✓ Get Processes ........................... GET    /process
[STDOUT] 2017/11/08 05:01:28 
[STDOUT] 2017/11/08 05:01:28 Exec-Agent WebSocket routes:
[STDOUT] 2017/11/08 05:01:28 ✓ Connect to Exec-Agent(websocket) ........ GET    /connect
[STDOUT] 2017/11/08 05:01:28 
[STDOUT] 2017/11/08 05:01:28 ⇩ Registered RPCRoutes:
[STDOUT] 
[STDOUT] 2017/11/08 05:01:28 Process Routes:
[STDOUT] 2017/11/08 05:01:28 ✓ process.start
[STDOUT] 2017/11/08 05:01:28 ✓ process.kill
[STDOUT] 2017/11/08 05:01:28 ✓ process.subscribe
[STDOUT] 2017/11/08 05:01:28 ✓ process.unsubscribe
[STDOUT] 2017/11/08 05:01:28 ✓ process.updateSubscriber
[STDOUT] 2017/11/08 05:01:28 ✓ process.getLogs
[STDOUT] 2017/11/08 05:01:28 ✓ process.getProcess
[STDOUT] 2017/11/08 05:01:28 ✓ process.getProcesses
[STDOUT] 2017/11/08 05:01:30 Terminal-agent configuration
[STDOUT] 2017/11/08 05:01:30   Server
[STDOUT] 2017/11/08 05:01:30     - Address: :4411
[STDOUT] 2017/11/08 05:01:30     - Base path: ''
[STDOUT] 2017/11/08 05:01:30   Terminal
[STDOUT] 2017/11/08 05:01:30     - Slave command: ''
[STDOUT] 2017/11/08 05:01:30     - Activity tracking enabled: true
[STDOUT] 2017/11/08 05:01:30   Authentication
[STDOUT] 2017/11/08 05:01:30     - Enabled: true
[STDOUT] 2017/11/08 05:01:30     - Tokens expiration timeout: 10m
[STDOUT] 2017/11/08 05:01:30   Workspace master server
[STDOUT] 2017/11/08 05:01:30     - API endpoint: http://che-host:9500/wsmaster/api
[STDOUT] 2017/11/08 05:01:30 
[STDOUT] 2017/11/08 05:01:30 ⇩ Registered HTTPRoutes:
[STDOUT] 
[STDOUT] 2017/11/08 05:01:30 Terminal routes:
[STDOUT] 2017/11/08 05:01:30 ✓ Connect to pty(webscoket) ............... GET    /pty
[STDOUT] 2017/11/08 05:01:30 
[STDERR] rm: cannot remove '/home/user/che/ws-agent/bin': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/conf/Catalina': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/lib': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/logs/archive/2017/11/07': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/logs/logs': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/maven-server': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/temp': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/META-INF/maven/org.eclipse.che.assembly-multiuser/assembly-wsagent-war': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/codenvy': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/org/eclipse/che/wsagent/server': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib': Directory not empty
[STDERR] rm: cannot remove '/home/user/che/ws-agent/work/Catalina/localhost': Directory not empty
[STDOUT] Listening for transport dt_socket at address: 4403
[STDOUT] 2017-11-08 05:01:42,465[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.11
[STDOUT] 2017-11-08 05:01:42,468[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Jan 10 2017 21:02:52 UTC
[STDOUT] 2017-11-08 05:01:42,469[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.11.0
[STDOUT] 2017-11-08 05:01:42,469[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2017-11-08 05:01:42,469[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-327.el7.x86_64
[STDOUT] 2017-11-08 05:01:42,469[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2017-11-08 05:01:42,469[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
[STDOUT] 2017-11-08 05:01:42,470[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
[STDOUT] 2017-11-08 05:01:42,470[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2017-11-08 05:01:42,470[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2017-11-08 05:01:42,470[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2017-11-08 05:01:42,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dnop
[STDOUT] 2017-11-08 05:01:42,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2017-11-08 05:01:42,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2017-11-08 05:01:42,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
[STDOUT] 2017-11-08 05:01:42,471[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2017-11-08 05:01:42,472[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2017-11-08 05:01:42,472[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
[STDOUT] 2017-11-08 05:01:42,472[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/che/ws-agent/conf/tomcat-logger.xml
[STDOUT] 2017-11-08 05:01:42,472[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
[STDOUT] 2017-11-08 05:01:42,472[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
[STDOUT] 2017-11-08 05:01:42,472[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
[STDOUT] 2017-11-08 05:01:42,472[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2017-11-08 05:01:42,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2017-11-08 05:01:42,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2017-11-08 05:01:42,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2017-11-08 05:01:42,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2017-11-08 05:01:42,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2017-11-08 05:01:42,473[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2017-11-08 05:01:42,677[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 525]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2017-11-08 05:01:42,690[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
[STDOUT] 2017-11-08 05:01:42,692[main]             [INFO ] [o.a.catalina.startup.Catalina 617]   - Initialization processed in 445 ms
[STDOUT] 2017-11-08 05:01:42,766[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2017-11-08 05:01:42,766[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service Catalina
[STDOUT] 2017-11-08 05:01:42,767[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.11
[STDOUT] 2017-11-08 05:01:42,892[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] 2017-11-08 05:01:43,199[ost-startStop-1]  [ERROR] [o.a.c.core.ContainerBase 755]        - ContainerBase.addChild: start: 
[STDOUT] org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] Caused by: java.lang.NullPointerException: null
[STDOUT] 	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:337)
[STDOUT] 	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:193)
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1898)
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1126)
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
[STDOUT] 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
[STDOUT] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
[STDOUT] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[STDOUT] 	... 10 common frames omitted
[STDOUT] 2017-11-08 05:01:43,200[ost-startStop-1]  [ERROR] [o.a.c.startup.HostConfig 955]        - Error deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war
[STDOUT] java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
[STDOUT] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
[STDOUT] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
[STDOUT] 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
[STDOUT] 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[STDOUT] 	at java.lang.Thread.run(Thread.java:748)
[STDOUT] 2017-11-08 05:01:43,201[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 308 ms
[STDOUT] 2017-11-08 05:01:43,203[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-4401]
[STDOUT] 2017-11-08 05:01:43,208[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 515 ms

Should I need to add any extra configurations??

**Comment by LahariGuntha** [comment]
Hi,

It was finalu throwing an error like:

Could not start workspace logs. Reason: Start of environment 'default' failed. Error: Timeout. The Che server is unable to ping your workspace. This implies a network configuration issue, workspace boot failure, or an unusually slow workspace boot.

**Comment by ghost** [comment]
@LahariGuntha can you consistently reproduce it? It does look like there are issues with removing ~/che directory so that ws-agent starts from blank page.

I cannot reproduce it on Ubuntu 16.04.

**Comment by matrix-developer** [comment]
Yes we can reproduce it.We are using RHEL 7.2.

**Comment by LahariGuntha** [comment]
Yes we can reproduce it.We are using RHEL 7.2 as our Host.

**Comment by ghost** [comment]
@matrix-developer @LahariGuntha 

can you run the following?

`docker run -ti $snapshotted_image bash`

`rm -rf /home/user/che/ws-agent`

**Comment by LahariGuntha** [comment]
Hi,
I tried to execute the given commnads.


[root@sso che]# docker run -it machine_snapshot_ozfq1wi0fifnjox7 bash
user@a21a4adb3509:/projects$
user@a21a4adb3509:/projects$
user@a21a4adb3509:/projects$
user@a21a4adb3509:/projects$ rm -rf /home/user/che/ws-agent
rm: cannot remove '/home/user/che/ws-agent/bin': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/conf/Catalina': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/lib': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/logs/archive/2017/11/08': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/logs/logs': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/maven-server': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/temp/indexes': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/META-INF/maven/org.eclipse.che.assembly-multiuser/assembly-wsagent-war': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/codenvy': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/classes/org/eclipse/che/wsagent/server': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/webapps/ROOT/WEB-INF/lib': Directory not empty
rm: cannot remove '/home/user/che/ws-agent/work/Catalina/localhost': Directory not empty

It is showing that it cannor remove because it was not an empty directory...as shown above...

**Comment by ghost** [comment]
@LahariGuntha your kernel version please?

**Comment by matrix-developer** [comment]
Kernel Version is 3
uname -a
Linux sso 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LahariGuntha** [comment]
Kernel Version is 3
uname -a
Linux sso 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ghost** [comment]
Looks like you have hit https://github.com/moby/moby/issues/27214

**Comment by LahariGuntha** [comment]
so what can be done so that we can resolve this Isuue??

**Comment by ghost** [comment]
@LahariGuntha have you tried https://github.com/moby/moby/issues/27214#issuecomment-315185785?

**Comment by matrix-developer** [comment]
May I know to which comment you are referring to??

**Comment by LahariGuntha** [comment]
May I know to which comment you are referring to??

**Comment by ghost** [comment]
@LahariGuntha the one I have posted in my previous reply.

**Comment by LahariGuntha** [comment]
I did not get "/PATH/TO/DEVICE" ...what path is it referring to??

**Comment by ghost** [comment]
@LahariGuntha Docker community is a better place to get help with this one. There are other links with discussions. Meanwhile you may not snapshot workspaces.

**Comment by LahariGuntha** [comment]
okay ...will try that command then will contact you if the problem still persists..

**Comment by pixystone** [comment]
Same on RedHat 7.2...

I set these flags to workaround the problem:

```
CHE_WORKSPACE_AUTO__SNAPSHOT=false
CHE_WORKSPACE_AUTO__RESTORE=false
```

Is there any doc support or description for `snapshot workspace`?

**Comment by ghost** [comment]
Closing as cannot reproduce in Che6.
