### ISSUE TITLE
[Che6-OCP] Project dependencies are not imported

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7210]
### Description
We have a big regression in the selenium tests which runs on the OCP platform. 
The dependencies which include to the pom.xml  are not imported to the project.

Report before: 
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6-ocp/3/Selenium_tests_report/

Report after: 
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6-ocp/12/Selenium_tests_report/

### Reproduction Steps
1. Run default java stack with default spring project
1. Open the "pom.xml" 
1. Open the "AppController.java" file
1. Expand "External Libraries" folder

**Expected behavior:**
The list of dependencies in the "pom.xml" and imported libraries in the "External Libraries" folder are matched. The java code in the opened editor is validated and without error markers.

**Observed behavior:**
The list of dependencies in the "pom.xml" and imported libraries in the "External Libraries" folder are not matched. The java code in the opened editor is not validated and error markers are presents.

**Attachments:**

![aaa](https://user-images.githubusercontent.com/22724619/32450139-241db810-c31c-11e7-8eb5-c97ee8ae24de.png)

![bbb](https://user-images.githubusercontent.com/22724619/32450374-b8670f30-c31c-11e7-8a4d-585187d64a35.png)

**OS and version:**    

Che6 (OCP) 6.0.0-M2 ; Chrome 59.0 ; Fedora 25

**Comment by musienko-maxim** [comment]
@slemeur The problem looks like the maven dependencies are not resolved during performance of test. But for the tests we do not have any visual indicators for checking this event. For the test we need clear visual indicator on UI.

**Comment by slemeur** [comment]
@musienko-maxim : There are two problems here:
1- Why the maven dependencies are not resolved? 

2- I agree that we are missing a feedback to the user in order to inform him that the maven dependencies cannot be resolved. 
- I think an event like "Maven dependencies cannot be resolved." could be fine. 
- We could also display an "error" mark on the project root's folder, in the project explorer - but the reason of displaying this error mark will be unclear. So we would need to show the error on hover and in right-click panel.

**Comment by AndrienkoAleksandr** [comment]
We need bring back resolve indicator to CHE 6. It's important not only for selenium tests. We extremely MUST have this important feature for internal use. 
![indicator](https://user-images.githubusercontent.com/6873095/32540502-970801c8-c475-11e7-8a36-1f7f739da791.png)

**Comment by skabashnyuk** [comment]
Here is an issue about resolve indicator https://github.com/eclipse/che/issues/6929

**Comment by slemeur** [comment]
Let's agree on the following: 
The status bar in its current form is used only for maven project and it is rarely active. The information displayed in is important, but we must always look to optimize the use of the space in the screen. 
As at this moment, the status bar is used only for maven project, anyone who's using Che for something different than a maven project is loosing 20px. And even if you are 

We discussed with @ashumilova and @vitaliy-guliy to restore the status bar. But let's also discuss how we can better optimize the use of this status bar:
- Display it only for maven project
- Hide the bar, when no information to be displayed
- Display the information somewhere else

**Comment by slemeur** [comment]
https://github.com/eclipse/che/issues/7314

**Comment by Ohrimenko1988** [comment]
Problem is resolved and not reproduced
