### ISSUE TITLE
Unable to Push the code to Github

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#7239]
Hi,

We are trying to make changes to the code in Eclipse-che and push it back ti git hub repository.
We followed the below document to setup Github with Eclipse-che:
https://www.eclipse.org/che/docs/ide/git-svn/index.html#github-oauth

Eclipse-Che -version:5.19.0
Docker version: 1.13.1,
Host OS:RHEL 7.2

Commnad used to run Eclipse-che:
docker run -d --name chemultiusernew -e CHE_DOCKER_IP_EXTERNAL=10.50.68.49 -e CHE_MULTIUSER=true -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://10.50.68.41:8089/auth -e CHE_KEYCLOAK_REALM=Test -e CHE_KEYCLOAK_CLIENT__ID=openshiftio-public -p 9090:9500 -e CHE_PORT=9500 -e CHE_DOCKER_NETWORK=che9500_che-network -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start

While trying to push code to Github from eclipse-che it is throwing below Error;
You are not authorized to perform this operation
This may be because you have not setup SSH keys or oAuth.
Check the documentation for using Git for more information on setting these up.

From the terminal that we can see in Eclipse-che..we were able to commit and push code to the repository.It was working fine.
But from the UI ...Using "Remotes" option under Git Dropdown...and selecting push...we were not able to push the code to GitHub.It was throwing above Error.

We have Added the user name and Email id under Git Commiter options.But still we are facing the same Issue.

**Comment by ghost** [comment]
@LahariGuntha what happens when you go to Profile > Preferences > SSH Keys > VCS and click GitHub icon?

**Comment by LahariGuntha** [comment]
After going to Profile > Preferences > SSH Keys > VCS and click Octocat icon I was redirected to git hub page as shown in the image..
![eclipseche](https://user-images.githubusercontent.com/33144388/32551169-a20df696-c4b5-11e7-9222-f8c7776528e1.PNG)
After entering the github account credentials where we Configured our oAuth apps...i am getting a page that shows 

"github.com" as shown in the image...
![eclipseche1](https://user-images.githubusercontent.com/33144388/32551223-cf03a402-c4b5-11e7-9d45-d0d0bb7dac25.PNG)

**Comment by LahariGuntha** [comment]
Is that the expected output???

**Comment by ghost** [comment]
@LahariGuntha no it's not.

Can you share your github app settings and che,env entries related to GitHub oAuth?

**Comment by LahariGuntha** [comment]
Here is the Setting in GitHub..
![image](https://user-images.githubusercontent.com/33144388/32552008-86459b3c-c4b8-11e7-80ad-664d12dc7bd7.png)

Entries related to Github oAuth in che.env:
CHE_OAUTH_GITHUB_CLIENTID=f1dec3e3c30502f55d27
CHE_OAUTH_GITHUB_CLIENTSECRET=b3608a6908275301cf869bb28b792f4f0f87ae9f
CHE_OAUTH_GITHUB_AUTHURI= https://github.com/login/oauth/authorize
CHE_OAUTH_GITHUB_TOKENURI= https://github.com/login/oauth/access_token
CHE_OAUTH_GITHUB_REDIRECTURI= http://10.50.68.49:9500/wsmaster/api/oauth/callback

Entries related to Github oAuth in che.properties file:

che.oauth.github.clientid=f1dec3e3c30502f55d27
che.oauth.github.clientsecret=b3608a6908275301cf869bb28b792f4f0f87ae9f
che.oauth.github.authuri= https://github.com/login/oauth/authorize
che.oauth.github.tokenuri= https://github.com/login/oauth/access_token
che.oauth.github.redirecturis= http://10.50.68.49:9500/wsmaster/api/oauth/callback

**Comment by LahariGuntha** [comment]
Should the user that we login into Eclipse-che should be the same with the user with which we configured oAuth apps in Github???

**Comment by ghost** [comment]
@LahariGuntha, no, it can be any GitHub user.

Is the screenshot you have shared the only thing you see? Just word github?

**Comment by LahariGuntha** [comment]
yes...just word github.com

**Comment by ghost** [comment]
@LahariGuntha have you tried Chrome? I also wonder why it's an incognito tab...

**Comment by LahariGuntha** [comment]
Yes I first tried it in Chrome...the output was the same...I was just trying incognito..But no difference when trying in Firefox as well as chrome...

**Comment by ghost** [comment]
Can you remove user tokens in App settings in GitHub and try it again? Please make screenshots of every step.

**Comment by matrix-developer** [comment]
Hi,

I got my code pushed to Github...
I solved this Issue by passing CHE_OAUTH_GITHUB_CLIENTID,CHE_OAUTH_GITHUB_CLIENTSECRET,CHE_OAUTH_GITHUB_AUTHURI,CHE_OAUTH_GITHUB_TOKENURI,CHE_OAUTH_GITHUB_REDIRECTURIS  as Environment variables in the docker run command..that is used to bring Eclipse-che up...

Thanks a lot for your support..Thank youu...

**Comment by LahariGuntha** [comment]
Hi,

I got my code pushed to Github...
I solved this Issue by passing CHE_OAUTH_GITHUB_CLIENTID,CHE_OAUTH_GITHUB_CLIENTSECRET,CHE_OAUTH_GITHUB_AUTHURI,CHE_OAUTH_GITHUB_TOKENURI,CHE_OAUTH_GITHUB_REDIRECTURIS as Environment variables in the docker run command..that is used to bring Eclipse-che up...

Thanks a lot  Eivantsov ...for your support..Thank youu...
