### ISSUE TITLE
[Multiuser] Workplace member permissions do not change after changing his role in organization

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7244]
**Reproduction Steps:**
1. Create an organization and add a member with the **member** role 
2. Create an workspace in this organization and share it with the member
3. Change role of the member to **admin**
4. Check the **Share** tab of the workspace

**Expected behavior:**
The member permissions for the workspace changed(added **setPermission** because the member is admin now in the organization).

**Observed behavior:**
Nothing changed. If delete the member from the **Share** tab and add again then he will be has **admin** permission.

**Che version:** 5.21.0-SNAPSHOT **Multiuser**
**OS and version:** Fedora 25

**Additional information:**
![permission_for_member](https://user-images.githubusercontent.com/7760565/32543616-cd0ebc04-c47e-11e7-8738-aa4cca8d54e2.gif)

**Comment by ashumilova** [comment]
@SkorikSergey Workspace permissions should not change, when you change the permissions of the organization. On your flow - you provide the the user "Admin" role for the organization, thus he has "setPermissions" inside organization - not for particular workspace. setPermissions inside organization and setPermissions inside workpace are not related.
