### ISSUE TITLE
[Multiuser] Member can still work with shared workspace after removing from organization

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7245]
**Reproduction Steps:**
1. Create an organization and add a member in the organization 
2. Create an workspace in this organization and share it with the member
3. Remove this member from the organization

**Expected behavior:**
The member removed from the organization and the workspace is not visibled in his workspaces list.

**Observed behavior:**
The member still can work with the workspace. 
If the member was in the organization as an administrator, he can delete all users from the workspace **Share** tab and work with the workspace using the organization's resources.

**Che version:** 6.0.5-SNAPSHOT **Multiuser**
**OS and version:** Fedora 25

**Comment by skabashnyuk** [comment]
@SkorikSergey need to check this issue against Che6 master.
Question. Did you restart this workspace or it's without restart?

**Comment by SkorikSergey** [comment]
This issue is reproduced in CHE 6.0.5.
After removing from an organization the member can do all operations with this workspace except it deleting.
