### ISSUE TITLE
Che fails to create workspace with a Traefik error (NullPointerException)

### ISSUE THREAD

**Issue by osallou** [eclipse-che/che#7249]
### Description

che works behind a web proxy, with options single_port=true and a specific CHE_DOCKER_SERVER__EVALUATION__STRATEGY_CUSTOM_TEMPLATE.
I can access che, and it starts creation of a workspace. I can see in web ui, the download of the docker image for my workspace  (final message: [DOCKER] Status Image is up-to-date ...), but error occurs when Che tries to start the container.

Shown error is:

    Could not start workspace wksp-d4ol. Reason: Start of environment 'default' failed. Error: null

### Reproduction Steps

Debian GNU/Linux 9.1 (stretch)
Docker version 17.09.0-ce, build afdb6d4
Che: 5.20.0

**Diagnostics:** 

In Che Docker container, following error is shown when trying to start the workspace:

    2017-11-08 11:55:57,172[aceSharedPool-1]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - null
    org.eclipse.che.api.core.ServerException: null
    	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)
    	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
    	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
    	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
    	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
    	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
    	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
    	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.eclipse.che.api.core.ServerException: null
    	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:398)
    	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)
    	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)
    	... 11 common frames omitted
    Caused by: java.lang.NullPointerException: null
    	at java.util.HashMap.putMapEntries(HashMap.java:500)
    	at java.util.HashMap.putAll(HashMap.java:784)
    	at org.eclipse.che.plugin.traefik.TraefikCreateContainerInterceptor.invoke(TraefikCreateContainerInterceptor.java:89)
    	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:645)
    	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:354)
    	... 13 common frames omitted

I don't know if this is related but system/network messages appears:

    Nov  8 12:03:20 chedevide kernel: [ 3607.281695] IPv6: ADDRCONF(NETDEV_UP): vetha163065: link is not ready
    Nov  8 12:03:20 chedevide kernel: [ 3607.402766] eth0: renamed from veth99995c7
    Nov  8 12:03:20 chedevide kernel: [ 3607.418737] IPv6: ADDRCONF(NETDEV_CHANGE): vetha163065: link becomes ready
    Nov  8 12:03:20 chedevide kernel: [ 3607.420982] docker0: port 1(vetha163065) entered blocking state
    Nov  8 12:03:20 chedevide kernel: [ 3607.423025] docker0: port 1(vetha163065) entered forwarding state
    Nov  8 12:03:26 chedevide kernel: [ 3612.565886] docker0: port 1(vetha163065) entered disabled state
    Nov  8 12:03:26 chedevide kernel: [ 3612.569309] veth99995c7: renamed from eth0
    Nov  8 12:03:26 chedevide kernel: [ 3612.610339] docker0: port 1(vetha163065) entered disabled state
    Nov  8 12:03:26 chedevide kernel: [ 3612.615237] device vetha163065 left promiscuous mode
    Nov  8 12:03:26 chedevide kernel: [ 3612.617944] docker0: port 1(vetha163065) entered disabled stat

I have however no issue to run manually some containers.

**Comment by ghost** [comment]
@osallou can you share the command you are using to start Che?

**Comment by osallou** [comment]
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/che-data:/data -e CHE_SINGLE_PORT=true -e CHE_DOCKER_SERVER__EVALUATION__STRATEGY_CUSTOM_TEMPLATE="<serverName>.<machineName>.<workspaceId>.XX.YY.vm.openstack.genouest.org"  eclipse/che start

**Comment by ghost** [comment]
@osallou does it work for you if drop `CHE_DOCKER_SERVER__EVALUATION__STRATEGY_CUSTOM_TEMPLATE`?

**Comment by osallou** [comment]
no, same error

**Comment by ghost** [comment]
@osallou Can you run a clean installation with a new data dir mounted?

`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/che-data1:/data -e CHE_SINGLE_PORT=true eclipse/che start`

Please share output from this command.

**Comment by osallou** [comment]
it "works" if I disable CHE_SINGLE_PORT, but of course if fails to connect to agent as I am behind a web proxy and IP/port is not reachable.
With CHE_SINGLE_PORT, web socket access is ok, but container/workspace start is the issue....
Before each start, I delete the /opt/che-data directory, so data dir is not the issue

**Comment by osallou** [comment]
Here is output of start command

     root@CheDevIde:/var/log# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/che-data:/data -e CHE_SINGLE_PORT=true   eclipse/che start
    WARN: Bound 'eclipse/che' to 'eclipse/che:5.20.0'
    WARNING: No swap limit support
    WARN: Did not detect TTY - interactive mode disabled
    INFO: (che cli): 5.20.0 - using docker 17.09.0-ce / native
    WARN: Newer version '6.0.0-M1' available
    INFO: (che init): Installing configuration and bootstrap variables:
    INFO: (che init):   CHE_HOST=192.168.100.79
    INFO: (che init):   CHE_VERSION=5.20.0
    INFO: (che init):   CHE_CONFIG=/opt/che-data
    INFO: (che init):   CHE_INSTANCE=/opt/che-data/instance
    INFO: (che config): Generating che configuration...
    INFO: (che config): Customizing docker-compose for running in a container
    INFO: (che start): Preflight checks
    WARNING: No swap limit support
             mem (1.5 GiB):           [OK]
             disk (100 MB):           [OK]
             port 8080 (http):        [AVAILABLE]
             conn (browser => ws):    [OK]
             conn (server => ws):     [OK]

    INFO: (che start): Starting containers...
    INFO: (che start): Services booting...
    INFO: (che start): Server logs at "docker logs -f che"
    INFO: (che start): Booted and reachable
    INFO: (che start): Ver: 5.20.0
    INFO: (che start): Use: http://192.168.100.79:8080
    INFO: (che start): API: http://192.168.100.79:8080/swagger

**Comment by ghost** [comment]
@osallou maybe configuring proxy in your Docker daemon settings is the right thing to do in the first place...

**Comment by osallou** [comment]
che and docker are on the same host, which configuration is necessary in Docker regarding use of SINGLE_PORT? Che can access Docker (and docker pull for workspace image is ok).
Without SINGLE_PORT (and still through proxy), workspace can be launched with no issue.

**Comment by osallou** [comment]
By the way, it seems not a ip/port reach issue:

    Caused by: java.lang.NullPointerException: null
    	at java.util.HashMap.putMapEntries(HashMap.java:500)
    	at java.util.HashMap.putAll(HashMap.java:784)
    	at org.eclipse.che.plugin.traefik.TraefikCreateContainerInterceptor.invoke(TraefikCreateContainerInterceptor.java:89)

seems a hashmap is not initialized (is null)

**Comment by osallou** [comment]
I just tried on my local computer, with no proxy (using localhost), I face the same error:

    sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/che-data:/data -e CHE_SINGLE_PORT=true eclipse/che start
    $ sudo docker ps
    CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                               NAMES
    a300905441c2        traefik:v1.3.0-rc3          "/traefik --logLev..."   46 seconds ago      Up 46 seconds       80/tcp, 0.0.0.0:8080->8080/tcp      che_traefik_1
    399051d3b7e9        eclipse/che-server:5.20.0   "/entrypoint.sh"         46 seconds ago      Up 46 seconds       8000/tcp, 0.0.0.0:32769->8080/tcp   che

In Web UI (http://localhost:8080), start diagnostics => "Error while starting the workspace"
In che logs:

    ...
    Caused by: java.lang.NullPointerException: null
	    at java.util.HashMap.putMapEntries(HashMap.java:500)
	    at java.util.HashMap.putAll(HashMap.java:784)
	    at org.eclipse.che.plugin.traefik.TraefikCreateContainerInterceptor.invoke(TraefikCreateContainerInterceptor.java:89)

**Comment by osallou** [comment]
In machineId.logs coming from diagnostic on my local computer test I see:

    ...
    [DOCKER] 3b27fd892ecb: Pull complete 
    [DOCKER] Digest: 
    sha256:7285d7c365392d1a9921f6e5449bfab3ff913e6e4cc8e64e819ef62eea34667b 
    [DOCKER] Status: Downloaded newer image for openjdk:8-jre-alpine 
    [DOCKER] ---> b36ec9de53a8
    [DOCKER] Step 2/2 : CMD tail -f /dev/null
    [DOCKER] ---> Running in c72000b45f8f
    [DOCKER] ---> 45c547682bc4
    [DOCKER] Removing intermediate container c72000b45f8f
    [ERROR] null

**Comment by osallou** [comment]
My 2 cents:
Error seems to occur in TraefikCreateContainerInterceptor.java when adding image labels

     Map<String, String> imageLabels = imageInfo.getConfig().getLabels();
    // Now merge all labels
    final Map<String, String> allLabels = new HashMap<>(containerLabels);
    allLabels.putAll(imageLabels);

If I look at generated images

    sudo docker inspect eclipse-che/workspacekabb30hhcwkoopvj_machine3yj1fhepwyl0tcos_che_dev-machine

 => Config.Labels = null

So either there is an issue when trying to add some labels to image, either the case where there is no label is not handled.

**Comment by ghost** [comment]
@osallou I cannot reproduce it on my local Ubuntu so it must be smth with your local setup. Not sure what though.

**Comment by ghost** [comment]
So, you don't have this in your container?

` "Labels": {
                "che:server:22/tcp:protocol": "ssh",
                "che:server:22/tcp:ref": "ssh",
                "che:server:4401/tcp:path": "/api",
                "che:server:4401/tcp:protocol": "http",
                "che:server:4401/tcp:ref": "wsagent",
                "che:server:4411/tcp:protocol": "http",
                "che:server:4411/tcp:ref": "terminal",
                "che:server:4412/tcp:protocol": "http",
                "che:server:4412/tcp:ref": "exec-agent",
                "che:server:8000:protocol": "http",
                "che:server:8000:ref": "tomcat8-debug",
                "che:server:8080:protocol": "http",
                "che:server:8080:ref": "tomcat8",
                "che:server:9876:protocol": "http",
                "che:server:9876:ref": "codeserver",
                "traefik.frontend.rule": "workspacext20j2srs8nkcgk5_machine030w77p6j8l7ir23_che_dev-machine",
                "traefik.service-codeserver.frontend.entryPoints": "http",
                "traefik.service-codeserver.frontend.rule": "Host:codeserver.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-codeserver.port": "9876",
                "traefik.service-exec-agent.frontend.entryPoints": "http",
                "traefik.service-exec-agent.frontend.rule": "Host:exec-agent.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-exec-agent.port": "4412",
                "traefik.service-server-4403-tcp.frontend.entryPoints": "http",
                "traefik.service-server-4403-tcp.frontend.rule": "Host:server-4403-tcp.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-server-4403-tcp.port": "4403",
                "traefik.service-ssh.frontend.entryPoints": "http",
                "traefik.service-ssh.frontend.rule": "Host:ssh.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-ssh.port": "22",
                "traefik.service-terminal.frontend.entryPoints": "http",
                "traefik.service-terminal.frontend.rule": "Host:terminal.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-terminal.port": "4411",
                "traefik.service-tomcat8-debug.frontend.entryPoints": "http",
                "traefik.service-tomcat8-debug.frontend.rule": "Host:tomcat8-debug.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-tomcat8-debug.port": "8000",
                "traefik.service-tomcat8.frontend.entryPoints": "http",
                "traefik.service-tomcat8.frontend.rule": "Host:tomcat8.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-tomcat8.port": "8080",
                "traefik.service-wsagent.frontend.entryPoints": "http",
                "traefik.service-wsagent.frontend.rule": "Host:wsagent.dev-machine.workspacext20j2srs8nkcgk5.172.17.0.1.nip.io",
                "traefik.service-wsagent.port": "4401"
            }
        }
`

**Comment by osallou** [comment]
Labels are null in *images* created for workspace.

    $sudo docker images
    REPOSITORY                                                                      TAG                                        IMAGE ID            CREATED             SIZE
    eclipse-che/workspacekabb30hhcwkoopvj_machine3yj1fhepwyl0tcos_che_dev-machine   latest                                     45c547682bc4        About an hour ago   81.4MB


Those labels are used by Traefik interceptor when in SINGLE_PORT use case.
The container itself (the instance of the created image) is never executed (or failed and deleted immediatly by che, can't know), due to the NullPointerException raised in interceptor

**Comment by ghost** [comment]
@osallou yeah, you cannot inspect a container since Che server kills it after a failed attempt to start a workspace. Or it never gets created

**Comment by ghost** [comment]
@benoitf any pointers here? I'm kind of stuck since cannot reproduce it myself.

**Comment by osallou** [comment]
what is strange is it occurs (proxy or not) on 2 different setup (Debian 9 and Ubuntu 16.04.3)

**Comment by ghost** [comment]
Both VMs and same Docker version?

**Comment by osallou** [comment]
Debian 9 is a VM, Ubuntu is my computer, same Docker on both

**Comment by ghost** [comment]
And what stack do you use to create a workspace? I am almost sure it does not matter.. just in case...

**Comment by osallou** [comment]
I have tested with a python stack, and also simply executing diagnostics (which launches a java stack)

**Comment by ghost** [comment]
Can you try java stack?

**Comment by osallou** [comment]
java stack works on my local computer and my VM

**Comment by ghost** [comment]
OK, I got it finally :)

Java stack image has this https://github.com/eclipse/che-dockerfiles/blob/master/recipes/ubuntu_jdk8/Dockerfile#L4

Others may or may not have labels. And the code does not expect labels to be missing.

**Comment by osallou** [comment]
indeed some recipes do not have labels. so this is a bug, not managing case where labels=null

**Comment by ghost** [comment]
@osallou yes, it is. Sorry it's taken me a while to figure it out. As a workaround you may create a custom stack with own Dockerfile:

```
FROM eclipse/ubuntu_python
LABEL #something_goes_here
```

Or switch to a multi port mode until this issue is fixed.

**Comment by osallou** [comment]
multi-port mode is not possible due to http proxy restrictions.
Regarding stacks, this a temporary solution indeed. In fact, for the moment it was for testing only, no real project, but I had in plan to propose Che in our private cloud. I can go this way for the moment, waiting for the fix.
Thanks @eivantsov

**Comment by ghost** [comment]
> multi-port mode is not possible due to http proxy restrictions.

but you can configure Che to work behind proxy.

**Comment by osallou** [comment]
Pb is access for browser to container port range via reverse proxy, i need
single port for that

Le mer. 8 nov. 2017 16:00, Eugene Ivantsov <notifications@github.com> a
écrit :

**Comment by artaleks9** [comment]
Hello, @osallou
As I see the bug is fixed by #7252 pull request.
So I would like to clarify, the bug is not produced more?

**Comment by osallou** [comment]
As author of pr, i confirm that fixed issue for me

**Comment by artaleks9** [comment]
@osallou 
Perfectly, thanks a lot.
So then I close the issue.
