### ISSUE TITLE
how to use content assist automatically

### ISSUE THREAD

**Issue by feitiange** [eclipse-che/che#725]
I't seems like there is a content assist in menu, I can use it to autocomplete my java code, but how can I use it automatically? such as I press (.), show it.

**Comment by ghost** [comment]
It's Ctrl+Space

**Comment by feitiange** [comment]
I'm sorry, My mean is how to use content assist like eclipse IDE, and Ctrl+Space might conflic with windows hot key

**Comment by TylerJewell** [comment]
We do not currently support allowing users to change key bindings.  We will label this as an enhancement request. If this is a feature that you'd like to contribute to, let us know and we can provide some recommendations on how to get started.

**Comment by feitiange** [comment]
@TylerJewell I'll take this, but It's might be difficult for me due to unfamiliar with CHE source，is there any recommendations？

**Comment by TylerJewell** [comment]
@feitiange: In the documentation, we currently have tutorials for creating client-side and server-side extensions. They are simple tutorials right now. We do not yet have a detailed resource center on how to do deep customizations, such as working with editors & key bindings. Though we know that it is very important and will start working on collecting these materials.

We'll keep a record of all of our resources in https://github.com/eclipse/che/blob/master/CUSTOMIZING.md.

As a starting point, many people start learning how to write extensions for Che by reviewing the /plugins directory as we keep all of the plugins for Che in that directory. 

If you are really interested in helping to add user-defined key bindings, that would be great. I think it would be a significant project, however.  We would need to develop a specification here on this GitHub issue.  And then you should get inputs from @ashumilova about any particular implementation approaches that should be taken.  The requirements of proper supportability would be multi-part:
1. We need to support changing keybindings on existing keys.
2. There is different key binding assignments for Linux, Windows, Mac.
3. International keyboards may have to be taken into account.
4. What is the process for dealing with key binding conflicts - detecting and alerting to them?
5. Key binding storage - we probably need to move this into storage configuration that can be edited by the user.
6. Key binding editor - today we display existing key bindings in the help menu, but we'll need a settings dialog box that allows changing bindings.
7. Integration & system tests - we'll need to exercise this on a range of systems.

**Comment by feitiange** [comment]
@TylerJewell  thanks for your suggestion. In fact I have read the doc, installed che-examples-action sucessfully, & maked my own build extension refs to  che-plugin-machine-ext-client.

**Comment by TylerJewell** [comment]
@feitiange - curious - any update on your efforts here?

**Comment by TylerJewell** [comment]
@svenefftinge - is this part of the language server protocol, or is it IDE-specific to choose on whether to auto-trigger intellisense?

**Comment by svenefftinge** [comment]
There is CompletionOptions#triggerCharacters as part of the initialization options, where the server signals on which characters completion should be shown.

**Comment by StevenDoesStuffs** [comment]
Any progress?

**Comment by TylerJewell** [comment]
Language server protocol work is tracked in this epic.  
https://github.com/eclipse/che/issues/1287

**Comment by StevenDoesStuffs** [comment]
TY

**Comment by TylerJewell** [comment]
LS has been merged.  It will ship as part of the 5.0 GA train.

**Comment by elpddev** [comment]
@TylerJewell 
As I understand, now there is a way to specify the key combinations in the language server initialization ? Is there another way to set those key combinations on the editor in che ?
