### ISSUE TITLE
[CHE6 branch] Factory creates without project

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7253]
Related test: **CreateFactoryFromUiWithKeepDirTest**

### Reproduction Steps
 - Run default Java stack without projects
 - Wait until project is started
 - Click “Import Project” link in the project explorer
 - In the opened “Import Project” form select “GitHub”
 - Input “https://github.com/spring-guides/gs-rest-service” in the “URL” field
 - Enable “Keep following directory” checkbox
 - Input “complete” to the “Directory” field
 - Click on “Import” button
 - In the opened "Configure project" form select "Blank" and click "Save"
 - Click twice on the project root folder
 - Open context menu for the "complete" folder and click on "Convert to project" and convert to the "Maven"
 - Select "complete" folder
 - Click on the "Workspace" item in the top menu 
 - Click on "Create Factory" item in the opened drop-down list
 - In the opened "Create Factory" form input factory name
 - Click on the "Create" button
 - Click on the "Invoke" button 
 - Wait until new workspace will be started
 - Pay attention to the project explorer

**Expected behavior:**
New workspace will be started with only "complete" project

**Observed behavior:**
Workspace is started but "complete" project displays as inner module

**OS and version:**    
Che6(multiuser) 6.1.0 ; Chrome 63.0 ; Fedora 25

**Comment by SkorikSergey** [comment]
Not actual
