### ISSUE TITLE
Dark theme- the blue text in a css file isn't correctly visible against the black background.

### ISSUE THREAD

**Issue by arunkumar413** [eclipse-che/che#7257]
### Description
I'm using trying to edit a .css file using the dark theme in the editor. However the CSS attributes are in blue color and aren't correctly visible against the theme's dark black background. Could you please change this to some other color or guide me to the file of the theme so that I can edit and push my suggestion.

![darktheme](https://user-images.githubusercontent.com/7776779/32563897-75b34e98-c4d8-11e7-877e-ed46625c9eab.png)

Thanks,
Arun

**Comment by slemeur** [comment]
We built-in editor in Che is Orion at this moment but we are looking to move to Monaco in near future (#5330). 

For the time being, we have some documentation about adding a new syntax highlighting : https://www.eclipse.org/che/docs/assemblies/sdk-code-editors/index.html#syntax-highlighting 

We unfortunately don't have docs on how to edit an existing highlighting configuration.
@ashumilova Could you guide @arunkumar413 ?

**Comment by ashumilova** [comment]
Hi, @arunkumar413 
There is set of styles that override the orion default ones - https://github.com/eclipse/che/blob/master/ide/che-core-orion-editor/src/main/resources/org/eclipse/che/ide/editor/orion/client/orion-codenvy-theme.css 
here nothing for overriding the css file types was added, so such files are not properly handled by IDE application in the Dark Theme. To do that - you' ll need to edit mentioned above css file by adding proper styles.
I can provide you the class names: support type propertyName css
You can see it from the following screenshot:
![screenshot from 2017-11-09 11-49-16](https://user-images.githubusercontent.com/1611939/32599446-40831a06-c545-11e7-969e-1b0606a1528a.png)

**Comment by arunkumar413** [comment]
Hi @ashumilova ,

Thanks a lot. I'm not able to push the changes to the master and also not able to create my own branch. Please help. I'd like to add this snippet to the css file.

```
.support type propertyName css{
       color: #00bcd4;
    }
```

**Comment by skabashnyuk** [comment]
@arunkumar413 are you doing that in your fork?

**Comment by arunkumar413** [comment]
No, I'm trying to push to the master of this respository

**Comment by skabashnyuk** [comment]
you can't do that if you are not Eclipse Che commiter. You can do it in your personal fork.

**Comment by arunkumar413** [comment]
If I do it in my personal fork will the changes reflect in the master branch of this repository.

**Comment by skabashnyuk** [comment]
Yes, when you'll create PR https://help.github.com/articles/creating-a-pull-request/ will see it.
