### ISSUE TITLE
GitHub oAuth in Che

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#7268]
Hi....

I am using my Multi-user Che..I have multiple users who use Eclipse-Che..
Each user will have their own Github account.Now how should I make my configuration in Eclipse-Che so that each and every user can push to their respective Github account??

**Comment by ghost** [comment]
@LahariGuntha can you elaborate on the use case?

Once you configure GitHub oAuth, your users can go to Profile > Preferences > SSH Keys and click GitHub icon. They will approve your GitHub app, and ssh key will be generated and uploaded to their accounts. Once done, they can clone, pull  and push to their repositories.

**Comment by LahariGuntha** [comment]
Hi,

I am using my Multi-user Che..I can login into my Eclipse-che with multiple users.
For example..I can login with Lahari,I can login with Teja etc...

My UseCase:
I have logged into exclipse-Che with User named Lahari.I have my own GitHub account.I have configured oAuth in my Github account.
While bringing up Eclipse-Che we have passed the values that are generated in Github while configuring oAuth as follows:

 docker run -it --name che -e CHE_OAUTH_GITHUB_CLIENTID=f1dec3e3c30502f55d27 -e CHE_OAUTH_GITHUB_CLIENTSECRET=b3608a6908275301cf869bb28b792f4f0f87ae9f -e CHE_OAUTH_GITHUB_AUTHURI=https://github.com/login/oauth/authorize -e CHE_OAUTH_GITHUB_TOKENURI=https://github.com/login/oauth/access_token -e CHE_OAUTH_GITHUB_REDIRECTURIS=http://10.50.68.52:9500/wsmaster/api/oauth/callback -e CHE_DOCKER_IP_EXTERNAL=10.50.68.52 -e CHE_MULTIUSER=true -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://10.50.68.41:8089/auth -e CHE_KEYCLOAK_REALM=Test -e CHE_KEYCLOAK_CLIENT__ID=openshiftio-public  -e CHE_PORT=9500  -e CHE_DOCKER_NETWORK=che9500_che-network  -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data -p 9090:9500 eclipse/che start

Here the values of "CHE_OAUTH_GITHUB_CLIENTID","CHE_OAUTH_GITHUB_CLIENTSECRET" are the values that was generated at the time of configuring oAuth in my GitHub account.

So now I can push my changes to my Github Account.

But when I login with other user into Eclipse-che  with user name as Teja...and she has her own Github account..she has to again configure her Github account with oAuth..We will the =n have different values for "CHE_OAUTH_GITHUB_CLIENTID","CHE_OAUTH_GITHUB_CLIENTSECRET" ..How to again configure Keycloak so that Teja can push her own changes to her own github accont???



Inorder to push our code from Eclipse-che to Github..We need to set Github oAuth

**Comment by ghost** [comment]
@LahariGuntha no, you don't have to configure anything once you initially did that. Any user should just go to Profile > Preferences > SSH Keys > VCS and click GitHub icon.

**Comment by LahariGuntha** [comment]
Okay...will try that...Thank you for the Information...

**Comment by LahariGuntha** [comment]
Hi,

It is working.Every user can push to their own Repositories...

Thank you...@Eivanstov.....Thanks a lot...

**Comment by ShubhasisMathur** [comment]
As soon as I click on the Git Hub icon, it opens up a page and throws error, Error starts with :
422 Unprocessable Entity

**Comment by fr34kyn01535** [comment]
I would generate new API credentials btw. @LahariGuntha
