### ISSUE TITLE
There is no way to restart workspace in the IDE

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#7270]
### Description
As far as workspace loading popup was removed:
![screenshot from 2017-11-09 15-13-08](https://user-images.githubusercontent.com/1611939/32607143-8c5c82a8-c560-11e7-990e-882a40efab7b.png)

There is no ability to restart the stopped workspace inside IDE. Workspace menu is disabled as well.

**Comment by SkorikSergey** [comment]
Close because it duplicated https://github.com/eclipse/che/issues/7273.
