### ISSUE TITLE
Openshift Origin 1.5 || Che 5.20.0 - Snapshots do not contain installed packages

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#7271]
### Description
I deployed Che 5.20.0 on Openshift Origin 1.5 & have created persistent volumes on nfs server for che-data & claim-che-workspace persistent volume claims.

- Launch a workspace with default Java stack & console-java-sample project.
- Make changes to HelloWorld.java class
- Install vim packages on dev-machine using terminal i.e. **sudo apt-get install vim -y**
- Check vim installation using **which vim** 
- Stop the workspace with snapshot from che dashboard.

Issue 1 - Only on Openshift
Start the same workspace by hitting "**RUN**" from workspaces dashboard. On executing **which vim** on dev machine terminal to check vim installation, It says **"Unable to find package vim"**. 

Expected Output
It should output the path of vim "/usr/bin/vim"

Issue 2 - Openshift & Docker
Changes done in project files are reflected on workspace restart (with/without snapshot), I believe this is because the changes are synced to NFS Server & workspace containing project files are loaded. 
The same behaviour is seen in Che running on Docker, as we mount a host volume to /data folder.

Expected Output
The workspace project folder should be deleted on external volume mounts, so that they can be synced again on workspace restart with changes contained in the snapshot.

### Reproduction Steps
Described above

**OS and version:**    
CentOS 7.3

**Diagnostics:**

**Comment by ghost** [comment]
@hbhargav snapshot support will be discontinued in Che 6.  Currently, when you start a workspace from Dashboard it does not use the latest snapshot.

And yes, project sources are mounted.

**Comment by hbhargav** [comment]
@eivantsov 
I've tried to start workspace with latest snapshot using the following methods.
- From Dashboard
- From the pop-up with check for using latest snapshot
- From REST API by passing restore = true

All of them result in the same behaviour.

**Comment by ghost** [comment]
@hbhargav there can be issues with snapshotting of Che 5 workspace on OpenShift since this scenario was never taken into consideration. Even though this is technically a bug, I don't think I should label it as such, since support of snapshots is discontinued in Che 6.

**Comment by ghost** [comment]
@hbhargav this is anti pattern for a container world. Both for Docker and OpenShift. Basically, container != VM. 

The idea behind creating developer environments with Eclipse Che is that they can be replicated. Snapshotting does save your env but it cannot be recreated in a true Docker or OpenShift way. 

In OpenShift world, snapshots are even more foreign.

**Comment by hbhargav** [comment]
@eivantsov 
Thanks for clarifying. 
I'm curious to know about the alternatives to snapshots coming in Che 6 or future releases. 
For ex :- DB changes, package installations etc how do these continue to exist despite workspace restarts. 
I'm sure developer would expect the above feature right ?

**Comment by ghost** [comment]
@hbhargav volume mounts and PVCs I suppose.

**Comment by ghost** [comment]
Yes, volumes are supported both for OpenShift and Docker. If you try eclipse/che:nightly you will find Volumes tab in workspace details view.
