### ISSUE TITLE
[CHE6(multiuser) branch] Project configuration form is not  opened after import project from GitHub

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7274]
### Description

**Important** - this bug reproduced only for **multiuser** 

**Related test** - _DirectUrlFactoryWithKeepDirectory_

### Reproduction Steps (**Only for multiuser**)
 - Run default Java stack without projects
 - Wait until project is started
 - Click “Import Project” link in the project explorer
 - In the opened “Import Project” form select “GitHub”
 - Input “https://github.com/spring-guides/gs-rest-service” in the “URL” field
 - Enable “Keep following directory” checkbox
 - Input “complete” to the “Directory” field
 - Click on “Import” button

**Expected behavior:**
The “Import Project” form will be closed and project configuration form will be opened

**Observed behavior:**
The “Import Project” form is closed, notification “project is imported” is shown, but project is empty and project configuration form is not opened.

**OS and version:**    
Che6(multiuser) 6.0.0-M2 ; Chrome 59.0 ; Fedora 25

**Comment by vzhukovs** [comment]
As for: 
>but project is empty 

this can not be reproduced.

As for:
>project configuration form is not opened

this is normal behavior.
