### ISSUE TITLE
Cannot use GWT SDM launched from Che IDE

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#7277]
### Description
While developing Che in Che IDE, I launch GWT SDM from IDE (at a dev-machine).
Since default GWT SDM's configuration has a restriction to allow loading js files (e.g. *.cache.js) from the localhost only, it's impossible to reload IDE with a recompiled js file from the CodeServer launched inside a container (at a dev-machine).

There is  the message in browser's Dev console:
`Ignoring non-whitelisted Dev Mode URL: http://172.19.20.35:32888/_app/_app.nocache.js`

Need to allow loading GWT permutation file in Super DevMode from any URL but not from the localhost only.

**Comment by benoitf** [comment]
```
<set-configuration-property name="devModeUrlWhitelistRegexp" value=".*" />
```
?

**Comment by azatsarynnyy** [comment]
@benoitf exactly

**Comment by vikas-sachdeva** [comment]
@benoitf In which file, I should put this `devModeUrlWhitelistRegexp` configuration ?

**Comment by benoitf** [comment]
@vikas-sachdeva I would put it in the common GWT file
ide/commons-gwt/src/main/resources/org/eclipse/che/ide/Commons.gwt.xml
