### ISSUE TITLE
[CHE6 branch] Workspace doesn't rerun properly by click on 'Run' button from navbar

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#7278]
**Reproduction Steps:**
* Create workspace and open it the IDE
* Stop the workspace
* Click 'Run' from context menu in the navbar
![button-run-ws](https://user-images.githubusercontent.com/5408906/32611502-8c72ee9a-c56e-11e7-8d98-3e78f9918bd2.png)

**Expected behavior:**
* workspace should work
 
**Observed behavior:**
* workspace has green indicator in the navbar, but does not work

**Che version:** 6.0.0-M2
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information**:
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![click-run-ws](https://user-images.githubusercontent.com/5408906/32611688-f3f0d262-c56e-11e7-84fb-750fc8b4dcc1.png)

**Comment by ashumilova** [comment]
Checked dashboard part - it works. Should be fixed on IDE by https://github.com/eclipse/che/issues/7278
