### ISSUE TITLE
Make it possible to call Git diff widget from folder

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#7280]
Git diff widget can show several files in the same widget by listing with the help of `next` / `previous` buttons:
![git_diff](https://user-images.githubusercontent.com/7668752/32614127-3a8633ce-c575-11e7-9763-e36ab3b1e41c.png)
Git compare widget can show changed files tree, but diff cannot be called when folder is selected:
![git_compare](https://user-images.githubusercontent.com/7668752/32614321-ae118e06-c575-11e7-9ac6-cf282caf586c.png)
It would be great to have an ability to call diff from folder.

If git diff  is invoked on the folder then the first file in the folder should be appeared in the git diff widget. 
But a user still will be able to navigate (prev/next) through the whole list of files.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
