### ISSUE TITLE
Che is not handling correctly Docker for mac 17.11 (edge stream)

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#7282]
### Description
Using edge stream of Docker for mac is making issues with Che

Docker For Mac Version 17.11.0-ce-rc2-mac37 

```
$ docker run -it --rm alpine:3.6 uname -r
4.9.44-linuxkit-aufs
```

### Reproduction Steps
Start Che and it fails as it is thinking we're using 'native' docker

**OS and version:**    
macOS and Docker For Mac Version 17.11.0-ce-rc2-mac37

**Comment by artaleks9** [comment]
I would like to know, this issue is still actual and if yes, set severity, please
