### ISSUE TITLE
OpenShift Keycloak

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#7284]
### Description
I couldn't get dedicated Keycloak to work created from the https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh . So I am trying to get Keycloak in different Openshift project to work with Che. Seems like I am getting close after getting redirected to the keycloak server, registering a new user, and then getting the flashing che logo but doesn't go past that. I get the following in the chrome development console. Seems like api is not working for me. Is there something in my realm's client "che-public" configuration I need to do? I had to add Valid Redirect URIs (https://che-eclipse-che.devcomb.com/* and /*/* etc) and set Web Origins to "+".

```
GET https://che-eclipse-che.devcomb.com/api/ 403 ()
GET https://che-eclipse-che.devcomb.com/api/workspace/settings 403 ()
OPTIONS https://che-eclipse-che.devcomb.com/api/ 403 ()
....
```

`VM2698:1 POST https://keycloak-keycloak.devcomb.com/auth/realms/che/protocol/openid-connect/token 400 (Bad Request)`

`{error: "unauthorized_client", error_description: "Client secret not provided in request"}`

**Comment by skabashnyuk** [comment]
How do you run Che? What version? How to reproduce your issue?

**Comment by skabashnyuk** [comment]
```
GET https://che-eclipse-che.devcomb.com/api/ 403 ()
GET https://che-eclipse-che.devcomb.com/api/workspace/settings 403 ()
OPTIONS https://che-eclipse-che.devcomb.com/api/ 403 ()
```
All of that can mean that you pass invalid jwt token (or not pass it at all)

**Comment by ghost** [comment]
@JamesDrummond what's in server logs?

**Comment by JamesDrummond** [comment]
Browser throws this error.


Below is an image of the server logs via the webconsole.

![image](https://user-images.githubusercontent.com/20580888/32852656-4649e7f4-c9fe-11e7-8a60-fffbe97a18ee.png)

**Comment by JamesDrummond** [comment]
Attached is the log from the [catalina.log](https://github.com/eclipse/che/files/1515530/catalina.log).


Edited 12/4/17: Removed logs. See attached.

**Comment by skabashnyuk** [comment]
Can you dump your ```che``` realm configuration and compare with reference https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/keycloak/templates/che-realm.json.erb?

**Comment by JamesDrummond** [comment]
I couldn't find anything that was different what would cause and issue. [realm-export (1).txt](https://github.com/eclipse/che/files/1516041/realm-export.1.txt)

Keep in mind I currently have che and keycloak working without ssl/https.

How to **possibly** reproduce. I have not been able to get minishift to work so I use my own keycloak server inside openshift origin running on linux host.

Working:
1. Set Keycloak env var `PROXY_ADDRESS_FORWARDING=true`. This sets `proxy-address-forwarding="${env.PROXY_ADDRESS_FORWARDING}" ` in standalone.xml.
1. Set route for che as nonsecure http.
1. Set route for keycloak to as secure https and allow all insecure traffic.
1. Set Che's env var `CHE_KEYCLOAK_AUTH__SERVER__URL="http://(keycloak sub).devcomb.com/auth"` via the config map associated variable.
1. Add to keycloak che-realm.json file `"redirectUris" : [ "http://(che sub).devcomb.com/*","https://(che sub).devcomb.com/*" ],`
1. Add to keycloak che-realm.json file `"webOrigins" : ["http://(che sub).devcomb.com","https://(che sub).devcomb.com"  ],`
1. Start Keycloak pod within a dedicated openshift project.
1. Start Che pod within a dedicated openshift project.
1. Go to http://(che sub).devcomb.com which redirects to keycloak login page which is http.
1. Create new user and hit submit which redirects me back to http://(che sub).devcomb.com/dashboard/#/
1. Everything works

Does not work:
1. Stop che pod.
1. Set Che's env var `CHE_KEYCLOAK_AUTH__SERVER__URL="https://(keycloak sub).devcomb.com/auth"` via the config map associated variable.
1. Set route for che to as secure https and allow all insecure traffic.
1. Start/Deploy che pod
1. Go to https://(che sub).devcomb.com which redirects to keycloak login page which is https.
1. Create new user and hit submit which redirects me back to https://(che sub).devcomb.com/dashboard/#/.
1. Does not work and have flash che logo. Errors are as mentioned per this issue description.

Note I can log into keycloak admin webapp both with http and https.

**Comment by ghost** [comment]
@JamesDrummond just tried in on a dedicated instance with valid certs. Cannot reproduce.  We have never tested it with self signed certs by the way.

**Comment by JamesDrummond** [comment]
@eivantsov OK I purchased wildcard cert for my website and it is still not working. See images below to demonstrate. You can see both applications are now secure in the top left corner.

![image](https://user-images.githubusercontent.com/20580888/33585099-335cd8e8-d928-11e7-9c4b-7e188ff7ca2a.png)

![image](https://user-images.githubusercontent.com/20580888/33585153-6fd73188-d928-11e7-9805-b2b2594f9b8d.png)

![image](https://user-images.githubusercontent.com/20580888/33585121-49f6780c-d928-11e7-9fcc-7251a8de26d9.png)

**Comment by skabashnyuk** [comment]
Can I see response ```/api/keycloak/settings/``` ?

**Comment by JamesDrummond** [comment]
Response:
HTTP Status 403 -
type Status report
message
description Access to the specified resource has been forbidden.
Apache Tomcat/8.5.11


Request URL:https://che-eclipse-che.devcomb.com/api/workspace/settings
Request Method:GET
Status Code:403 
Remote Address:163.172.137.97:443
Referrer Policy:no-referrer-when-downgrade

Content-Language:en
Content-Length:998
Content-Type:text/html;charset=utf-8
Date:Tue, 05 Dec 2017 16:31:09 GMT

Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Authorization:Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMjNGc3kzRlI5dnRUZms3TGlkX1lQOGU0cDNoY0psM20wQTRnckIzNnJJIn0.eyJqdGkiOiI1YTM1MTI0OC0wODNiLTQ0N2YtYTNmOS1lYmNjODRmODI1ZjkiLCJleHAiOjE1MTI0OTE3NjksIm5iZiI6MCwiaWF0IjoxNTEyNDkxNDY5LCJpc3MiOiJodHRwczovL2tleWNsb2FrLWtleWNsb2FrLmRldmNvbWIuY29tL2F1dGgvcmVhbG1zL2NoZSIsImF1ZCI6ImNoZS1wdWJsaWMiLCJzdWIiOiIzZDdmMGFhYy1hNGE5LTQ1YmItOGY1MC0yNDAzY2VlZGIyMjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJjaGUtcHVibGljIiwibm9uY2UiOiIwYjNlYWI2NC0xNDY3LTRmMzItOGUxMC1hM2E5MDk0NzQzNGQiLCJhdXRoX3RpbWUiOjE1MTI0OTE0MzIsInNlc3Npb25fc3RhdGUiOiJhYzE3Y2Y0Yi0wYTVjLTQxZDQtOTZkZC1iNDEyNjdmMDZkMDMiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9kZXZjb21iLmNvbTo4MDgwIiwiaHR0cHM6Ly9jaGUtZWNsaXBzZS1jaGUuZGV2Y29tYi5jb20iLCJodHRwOi8vY2hlLWVjbGlwc2UtY2hlLmRldmNvbWIuY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ1bWFfYXV0aG9yaXphdGlvbiIsInVzZXIiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJuYW1lIjoidGVzdCB0ZXN0IiwicHJlZmVycmVkX3(hidden-jd)
Connection:keep-alive
Cookie:e7e832c4d3d17f241325692f83b9abbe=5bdd9ea8f5e75eb83f3c0626f34eacff
Host:che-eclipse-che.devcomb.com
Referer:https://che-eclipse-che.devcomb.com/dashboard/
User-Agent:Mozilla/5.0 (X11; CrOS x86_64 9901.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.97 Safari/537.36

**Comment by skabashnyuk** [comment]
Wrong request I asked about ```/api/keycloak/settings/ ``` not ```/api/workspace/settings```

**Comment by JamesDrummond** [comment]
Fixed with PR [https://github.com/eclipse/che/pull/8263](https://github.com/eclipse/che/pull/8263)
