### ISSUE TITLE
I'm having trouble accessing the codenvy.io site

### ISSUE THREAD

**Issue by marisvaldo1** [eclipse-che/che#7285]
### Reproduction Steps
I was using the site normally. I had to leave and could not get in anymore.
I am using the chrome. I was emulating the ubunto when I had to leave and could not get in anymore.
I can see the login page but when I log in with my username and password, I get the message

Authentication failed. Please check username and password.
![image](https://user-images.githubusercontent.com/13384629/32629761-65e2b838-c581-11e7-8640-1f8b61de19fa.png)

When I click on the button to reset my password and I put my email I get the message

User marisvaldo@gmail.com is not registered in the system.
![image](https://user-images.githubusercontent.com/13384629/32629792-88c2927e-c581-11e7-8db6-bf79dd7931fd.png)

When I try to create a new account to register with the system, I get the message

User mail marisvaldo@gmail.com is forbidden.
![image](https://user-images.githubusercontent.com/13384629/32629850-bbaca3a0-c581-11e7-80f7-788515af8abc.png)

### If I can not resolve it, I'd like to know if you can delete my account and re-create it.

**OS and version:**    
windows 10

**Diagnostics:**

**Comment by ghost** [comment]
Wrong repo. But the last screenshot says you are trying to log in, not register. 

https://github.com/codenvy/codenvy/issues this is the right place to open an issue for Codenvy.

**Comment by iddy47** [comment]
I have a problem like a "marisvaldo " so how I can solve this problem
