### ISSUE TITLE
Client hangs after changing theme

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-che/che#730]
When trying to switch to the light theme, the dialog hangs. I can only click the cross on the right top to get rid of it. The theme doesn't get updated unless I go back to the dashboard and reopen the project.

**Comment by ddementieva** [comment]
You need to refresh the page after changing theme.

**Comment by slemeur** [comment]
Hi @svenefftinge,

When you are changing the theme, the effect is not immediate and the IDE needs to be reloaded in order to apply the theme. 
We'll have improvements coming on this behaviour.

**Comment by svenefftinge** [comment]
ok, it appeared as a bug to me. Also I was somehow expecting an ok button, to close the dialog, but now noticed that using the cross is the metaphor you use in these cases. Refreshing works for me.
