### ISSUE TITLE
Project explorer should not show hidden folders from `/projects`

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#7302]
### Description
The project explorer is displaying all the folders in `/projects` including the hidden ones - which can be a problem for certain types of projects.

See issue in: https://github.com/openshiftio/openshift.io/issues/1294

### Reproduction Steps
1. Create a workspace and open the IDE
2. Once loaded, open the terminal and create folder `.foo`
3. Do `chmod 770 .foo`

Expected behaviour:
- The folder `.foo` should not be displayed in the project explorer.

Current behaviour:
- The folder `.foo` is shown in the project explorer.

**Comment by skabashnyuk** [comment]
Do we need some way to show hidden files? Like button or some checkbox in preferences?

**Comment by slemeur** [comment]
We already have that ability in "Project" menu. It should impact the whole "project explorer" (so folders in `/projects` too)

**Comment by garagatyi** [comment]
> which can be a problem for certain types of projects.

@slemeur Can you elaborate on which problems it brings?

**Comment by slemeur** [comment]
@garagatyi : As an example you can give a look at the issue on OSIO : openshiftio/openshift.io#1294

Also, it's not logical/consistent, that we don't show the hidden files/folders in project's folder, but we show them in the root folder `/projects`
