### ISSUE TITLE
[CHE 6] Handle an error on starting a workspace during workspace creation flow

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7303]
### Description
Handle an error on starting a workspace during workspace creation flow.
<details>
<summary>See gif file</summary>

![out-2](https://user-images.githubusercontent.com/5887312/32658822-899a5148-c624-11e7-8a5c-aac127ba0c77.gif)
</details>

**Comment by ashumilova** [comment]
The new flow with workspace creation fixed this problem: 
- [x] workspace creation error is handled
- [x] after workspace creation user has choice to edit workspace or open in IDE - thus the create runtime error cannot be reproduced
