### ISSUE TITLE
Move project related actions to the Project menu section

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#7305]
#### Description
There is a proposal to move `Create Project` and `Import Project` to the Project menu section.

<p align="center"><img src="https://user-images.githubusercontent.com/1968177/32660680-6b9afe7e-c62c-11e7-9bc6-a6e8a5802af2.png"/></p>

#### Motivation
It a bit distracts when you want to create a project you instinctively go to Project menu.

**Comment by vzhukovskii** [comment]
Not actual
