### ISSUE TITLE
Errors when setting custom CHE_CONTAINER value with multiuser mode

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#7307]
### Description
 
I have 2 issues when trying to run che with multi user:

### `Invalid parameter, redirect_uri` when accessing to che with multiuser mode and with `CHE_CONTAINER` containing a `-`
This one can be reproduced with the command 

```
docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP}  -e CHE_CONTAINER=che-multi -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start
```
so accessing to EXTERNAL_IP:8080 brings us to the page from keycloak:

![selection_078](https://user-images.githubusercontent.com/650571/32660658-f6e8161e-c623-11e7-91fe-4c14423e2572.png)

From keycloak logs:
```
12:34:40,406 WARN  [org.keycloak.events] (default task-16) type=LOGIN_ERROR, realmId=che, clientId=che-public, userId=null, ipAddress=192.168.0.11, error=invalid_redirect_uri, redirect_uri=http://192.168.0.11:8081/dashboard/
```

The issue seems to be related to the `-` contained in the container name `che-multi`.

With `CHE_CONTAINER=che-multi`, it fails but with `CHE_CONTAINER=chemulti`, it works. I suspect it is related to the generated containers name for keycloak and postgres (`che-multi`, `chemulti_postgres_1`, `chemulti_keycloack_1` insteadof `che-multi`, `che-multi_postgres_1`, `che-multi_keycloak_1`)

Also if we only set `CHE_PORT` to 8081, it fails as well as the container name becomes `che-8081`

### Can not start a workspace
So if I set any value that is not `che` as a container name, I can not start a workspace:

![selection_079](https://user-images.githubusercontent.com/650571/32660889-fb374c5c-c624-11e7-8e6e-077e2cc0f969.png)

Good to know: I also had another error message about che not being able to find network `che-multi_che.....` but can not get this error back again.

**OS and version:**    
RHEL 7 (CSB)

**Comment by skabashnyuk** [comment]
Docker or openshift.
Che5 or Che6?

**Comment by benoitf** [comment]
@skabashnyuk based on the command line it's che latest (5.x) and Docker.

**Comment by skabashnyuk** [comment]
Missed that. Sorry.

**Comment by sunix** [comment]
@skabashnyuk actually I tried with eclipse/che and eclipse/che:nightly for the second issue but tried only che5 in any case.

**Comment by skabashnyuk** [comment]
BTW @sunix what is your usecase? Is there any reason to change ```CHE_CONTAINER```?

**Comment by sunix** [comment]
My usecase is che in che I run the multi user assembly I built on one workspace with the cli. But if you have another way to do I would be happy :).

**Comment by cenkce** [comment]
I gave same error in che server extension sample project.

**Comment by eivantsov** [comment]
@cenkce can you elaborate on how to reproduce it?

**Comment by eivantsov** [comment]
Closed due to inactivity.
