### ISSUE TITLE
Restore statusbar

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#7314]
## Description
We removed the statusbar which is used to display the maven import.

**Initial intent**
The status bar in its Che5 form is used only for maven project and it is rarely active. The information displayed in is important, but we must always look at how we can optimize the use of the space on the screen.
We removed it in order to better use the space available on the screen but without implementing the replacement solution. The users who are not doing a maven project are loosing 20px.

**Restore statusbar**
As we removed the statusbar but without having a replacement solution, we need to restore the statusbar, for immediate fix of #7210. But we need to think about how we can better display those information. #7313

**Comment by azatsarynnyy** [comment]
BTW Che's actions have:
* titles which are displayed as the related menu items' titles;
* descriptions which are not displayed anywhere.

Maybe we could use the statusbar for displaying those descriptions on mouse hovering on an action.

For example, how it looks in IDEA:
![descr](https://user-images.githubusercontent.com/1636395/32667909-d0e54290-c644-11e7-892e-820cefd82427.gif)

**Comment by vzhukovs** [comment]
Created another issue related to the api of status panel: https://github.com/eclipse/che/issues/7586
