### ISSUE TITLE
IDE trying to load localhost address when accessing from in network laptop

### ISSUE THREAD

**Issue by Marcosdg3** [eclipse-che/che#732]
Description of problem: IDE partially loads on laptop on same internal network as desktop running eclipse che
Che version: 4.0.0-RC11
Che install directory: /home/user/Documents/dev
Docker version: 1.10.3, build 20f81dd
Java version: 1.8.0_74
Environment details (AWS, VirtualBox, physical, etc.): physical desktop, Ubuntu 14.04, Chrome (latest)
How reproducible: Have Che running on desktop and am unable to load IDE on networked laptop.

Steps to Reproduce:
1. Start Che on Ubuntu desktop using /home/user/Documents/dev/eclipse-che-4.0.0-RC11/bin/che.sh run --port:9000
2. Open IDE on desktop, looks good, everything works great.
3. Open IDE on laptop on same internal network, doesn't open completely, console errors.

Actual Results:
[chrome-console.txt](https://github.com/eclipse/che/files/176552/chrome-console.txt)
GET http://localhost:9000/ide/api/recipe/recipex59ysjme5k9t2ol6/script net::ERR_CONNECTION_REFUSED
WebSocket connection to 'ws://localhost:32950/ide/ext/ws/workspaceb8fi79yml3smlgia' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Expected Results:
Confirmed changing the url seems to fix the issue. 
http://desktop.address:9000/ide/api/recipe/recipex59ysjme5k9t2ol6/script

**Comment by ghost** [comment]
If you want to use a local client and a remote server you need to run Che with -r parameter and specify your server IP. The server will use this IP to ping workspace and the same endpoint is used when you connect to a workspace with a local client.

Is the issue resolved for you now?

**Comment by Marcosdg3** [comment]
Ah that was the piece I was missing.

Still seeing this error in console: GET http://localhost:9000/ide/api/recipe/recipex59ysjme5k9t2ol6/script net::ERR_CONNECTION_REFUSED

But it looks to be working otherwise.

Thank you for your help and quick reply, really enjoying che!

**Comment by TylerJewell** [comment]
@Marcrazyness: We encourage you to read this page - it explains the stuff to check when setting up Che as a server.

https://eclipse-che.readme.io/docs/che-as-a-server

**Comment by ghost** [comment]
Have you created a new workspace or try to open an existing one? If you have created a workspace on localhost, its recipe is saved into workspace config as localhost. Try creating a new workspace now.

**Comment by Marcosdg3** [comment]
Thanks @TylerJewell I will read up on the link you sent me now.

@eivantsov I haven't created a new workspace, I will create a new workspace in the next couple hours and confirm the recipe address is correct.

Thanks for your help guys!

**Comment by ghost** [comment]
I am 99% positive that creation of a new workspace will fix the issue.

**Comment by Marcosdg3** [comment]
@eivantsov, it looks like that fixed the console error. Initially I did a workspace export and saw that url in exported json, changed it to my ip, imported into a new workspace and now there is not a console error. 
Thanks!
