### ISSUE TITLE
how to debug in che with  local environment ?

### ISSUE THREAD

**Issue by buaa0110** [eclipse-che/che#7322]
### Description
i can run a helloworld demo with che but when i want to dubug in this online ide, i failed.
i wanna how can  i run this debugger successfully with local environment.
need your help！
thanks！
 

### Reproduction Steps

by click this 
![image](https://user-images.githubusercontent.com/22358515/32715226-57ff6ce4-c88c-11e7-9143-87c5af26574a.png)
i can connect to the debug port
![image](https://user-images.githubusercontent.com/22358515/32715269-85f65432-c88c-11e7-85ef-411c804caeed.png)
but after a success tip
![image](https://user-images.githubusercontent.com/22358515/32715325-d08cd336-c88c-11e7-8ce4-dc706a48716d.png)
the debugger is still unable to run
![image](https://user-images.githubusercontent.com/22358515/32715342-e4274cf0-c88c-11e7-8a95-2a4e2c687955.png)

**OS and version:**    
windows 10  
lastest eclipse che 
**Diagnostics:**

**Comment by tolusha** [comment]
@buaa0110 
Hello. 
Nothing wrong with behavior above. Debugger is connected and then is suspended since application is has been stopped.  Just add a breakpoint before connecting to remote debug

**Comment by ghost** [comment]
@buaa0110 

What's `helloworld demo`? Is it a sample console app?

You may want to take a look at https://www.eclipse.org/che/docs/ide/debug/index.html

**Comment by buaa0110** [comment]
thank u@tolusha  i added breakpoints before but it did't work

**Comment by buaa0110** [comment]
@eivantsov  emm.. yep it's just a simple print statement. I tried to do as the doc but it didn't work as excepted

**Comment by ghost** [comment]
@buaa0110 you need to connect to port 8000 and start your app in a debug mode.

What exact errors did you have when following docs instructions?

**Comment by buaa0110** [comment]
oh thank u@eivantsov  the port i connected before is port 4403  
but a new problem comes, port 8000 can not be connected
it runs like this 
![image](https://user-images.githubusercontent.com/22358515/32769433-d6158116-c956-11e7-9923-7e9e9e046a79.png)
and then it disappeared without other info

**Comment by buaa0110** [comment]
@eivantsov  and chrome consoles
![image](https://user-images.githubusercontent.com/22358515/32769513-25c75e14-c957-11e7-994d-fc0ca6af49f1.png)

**Comment by ghost** [comment]
@buaa0110 did you execute your jar with debug flags?

**Comment by buaa0110** [comment]
sorry I don't quite understand 
is there any steps to do before run debugger?
i'm a new user to this app
would u like to tell me a little more about this ?i'll be so thankful

**Comment by ghost** [comment]
http://www.eclipse.org/che/docs/ide/debug/index.html#java-console-apps

**Comment by buaa0110** [comment]
@eivantsov thank u,i did it  successfully as u said
