### ISSUE TITLE
Remove CHE_LOCAL_CONF_DIR support

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#7324]
### Description
Che agent or wsmaster assemblies are based on `CheBootstrap`class allowing to use `CHE_LOCAL_CONF_DIR` as a property to specify an alternate configuration file.

In Che, there is already support of che.env  (in addition to overriding default .properties in custom war assemblies) and system or environment variables so it would be nice to fully get rid of this alternate configuration file override.

It has been done for WSMaster as part of https://github.com/eclipse/che/pull/7299
we should do it for Agent and for all instances.

**Comment by dmytro-ndp** [comment]
FYI: Selenium tests use [CheBootstrap.CHE_LOCAL_CONF_DIR](https://github.com/eclipse/che/blob/5.20.0/selenium/che-selenium-core/src/main/java/org/eclipse/che/selenium/core/configuration/SeleniumTestConfiguration.java#L139) to configure test-specific properties.

**Comment by benoitf** [comment]
@dmytro-ndp yes thanks for the link. I've noticed that it was used by selenium but I was thinking it could probably use a custom che.env as well

**Comment by garagatyi** [comment]
@benoitf Hasn't linked PR closed this issue?

**Comment by benoitf** [comment]
@garagatyi there was a PR targeting only WSMaster but not for the agent.

**Comment by garagatyi** [comment]
ok, thanks
