### ISSUE TITLE
Problems Running Eclipse Che in Eclipse Oxygen

### ISSUE THREAD

**Issue by pmiranda07** [eclipse-che/che#7329]
### Description
I'm trying to build/run Eclipse Che in Eclipse Oxygen but I'm having some troubles because I can't build the project.

### Reproduction Steps
I open the eclipse che project in Eclipse Oxygen but i can't build it or run because the eclipse doesn't recognize the project in the "Run as..." option.

**OS and version:**    
Mac OS High Sierra 10.13.1

**Comment by ghost** [comment]
@pmiranda07 it should be available in Run as.. You need to take a look at docs first https://www.eclipse.org/che/docs/

Also, can you elaborate on build failures if any?

**Comment by pmiranda07** [comment]
@eivantsov i don't have any build failures...I'm trying to Run as but it asks me to create a configuration...i will take a look at those docs and see if it works...thanks!!
