### ISSUE TITLE
Add missing loading pieces: installers info 

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#7330]
### Description
The workspace loading flow is missing the information and statuses about the installers.
![screenshot from 2017-11-13 12-34-40](https://user-images.githubusercontent.com/1611939/32721462-4258f7e2-c86f-11e7-80bb-16ac134de0d9.png)

The **server/statusChanged** should be tracked.
See [the handler](https://github.com/eclipse/che/blob/che6/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/workspace/events/ServerStatusEventHandler.java)

**Comment by slemeur** [comment]
@ashumilova : How do you handle that on OpenShift infrastructure?

**Comment by slemeur** [comment]
Linking to #5231

**Comment by ashumilova** [comment]
The Installers status events should be the same.

**Comment by vitaliy-guliy** [comment]
Linking to https://github.com/eclipse/che/issues/7332
