### ISSUE TITLE
Save server logs and oc events before resetting environment

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7331]
To troubleshoot QA test failures the following logs are extremely helpful:

* OpenShift events (oc get events)
* server logs (oc logs $che_server_pod)
* workspace logs - probably the best way is to get PV path by `oc describe pv`

**Comment by riuvshin** [comment]
currently we do not have workspaces logs stored on master, so for now we will store only ws master logs and oc events, for multi user che we also will store KC and PG logs
