### ISSUE TITLE
Add proper IDE events/handlers for workspace loading flow

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#7332]
### Description
The workspace loading flow is not processing all of the events that server can provide for workspace/machines/server statuses or logs. Need to review following [document](https://docs.google.com/document/d/1usjNc83j7pxA4DowoGdXKYpUK-x0O4b-XWq4ceQaB7I/edit) and implement missing ones.

**Comment by ashumilova** [comment]
Depends on https://github.com/eclipse/che/issues/7046

**Comment by slemeur** [comment]
Linking to #5231
