### ISSUE TITLE
Sometimes the message about deleted file under filewatcher is absent in the events panel

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7339]
### Description
Sometimes on CI failed RemoveFilesWithActiveTabs. We should investigate reason of failing and fix it
### Reproduction Steps
The test  launches 2 instances browser for common workspace. The browsers open the same file. In the browser#1 deletes file from IDE. In the browser#2 checks deleting with the message.
**Add info:**    
This reproduces only on CI in multithread mode, related selenium test: RemoveFilesWithActiveTabs

**Comment by musienko-maxim** [comment]
Last time the problem is not reproduced

**Comment by artaleks9** [comment]
Today is reproduced again

**Comment by vparfonov** [comment]
@musienko-maxim  @artaleks9 any updates for now

**Comment by dmytro-ndp** [comment]
@vparfonov: new info about issue from test execution [on Eclipse Che Singleuser on docker](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/217/testReport/org.eclipse.che.selenium.filewatcher/RemoveFilesWithActiveTabs/checkDeletionWithSingleOpenedTabFromIde/):

- browser tab 1
![org eclipse che selenium filewatcher removefileswithactivetabs checkdeletionwithsingleopenedtabfromide_crgkyho9](https://user-images.githubusercontent.com/1197777/37670427-ef83bff4-2c71-11e8-8c9b-829928ef78c9.png)
[webdriver1.log](https://github.com/eclipse/che/files/1830386/org.eclipse.che.selenium.filewatcher.RemoveFilesWithActiveTabs.checkDeletionWithSingleOpenedTabFromIde_g8od.log)

- browser tab 2
![org eclipse che selenium filewatcher removefileswithactivetabs checkdeletionwithsingleopenedtabfromide_h11sht2o](https://user-images.githubusercontent.com/1197777/37670461-078988a4-2c72-11e8-8ba5-8a977a45c74f.png)
[webdriver2.log](https://github.com/eclipse/che/files/1830392/org.eclipse.che.selenium.filewatcher.RemoveFilesWithActiveTabs.checkDeletionWithSingleOpenedTabFromIde_hlpc.log)

- ws-agent
[localhost-access.log](https://github.com/eclipse/che/files/1830491/localhost-access.log)

**Comment by musienko-maxim** [comment]
It happens pretty rare only CI infrastructure under selenium tests that start in 3 threads mode. So i suppose that problem may be reproduced under specific loading (network, file system, CPU). But i think this is not critical for a potential user. Because this usecase very difficult to reproduced in manual mode.
