### ISSUE TITLE
Include Organization tests into acceptance tests execution on the Multiuser Che

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#7359]
### Description
We have separate package [org.eclipse.che.selenium.dashboard.organization](https://github.com/eclipse/che/tree/5.20.0/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/organization) of selenium tests which is dedicated to _Organization Management_ in _Mutli-User Eclipse Che_. 

We need to find the way to run **organization** package automatically in case of testing the _Che_ which is run in _multi-user mode_.

_**Possible solution**_: add special annotation above the Organization test class - `@Multiuser`, to mark the class to be excluded from the execution in case of testing _Single User Che_. 
We can use listener [IAnnotationTransformer](https://jitpack.io/com/github/cbeust/testng/master-6.12-g8d0fb04-194/javadoc/org/testng/IAnnotationTransformer.html) to fix list of executing tests.

**Comment by tolusha** [comment]
ok for me

**Comment by dmytro-ndp** [comment]
Thank you for comment, @tolusha.

**Comment by dmytro-ndp** [comment]
We have to run organization tests in **single-thread** mode because of next circumstances:
1. In case of _test organization_ isn't removed after organization test execution, next test, which creates _test workspace_ from _Dashboard_, will not be able to remove such workspace because it is created in the remained test organization by default, for example:
![screenshot from 2017-11-20 19-02-32](https://user-images.githubusercontent.com/1197777/33032482-0abff2ac-ce2a-11e7-9906-31c96c781777.png)
As result, there is a number of test workspaces (seven ones) which are created from _Dashboard_, are remain after all tests execution:
![screenshot from 2017-11-20 19-49-42](https://user-images.githubusercontent.com/1197777/33033117-05c4f174-ce2c-11e7-9fd5-10188d27d195.png)

1. It's impossible to remove test organization which has running workspace. For example, when we  had running workspace with id='_workspacel0ev13h149qyq7go_' from organization **parent-orginttw/child-org23f7b**, there was an error it time of removal of this organization:
![screenshot from 2017-11-20 19-41-22](https://user-images.githubusercontent.com/1197777/33032777-f23823fc-ce2a-11e7-952a-d68470f2ff97.png)

**Comment by dmytro-ndp** [comment]
@riuvshin: for organization tests we need to have separate non-admin user (that is differ from admin@admin.com) on CI in properties:
> che.test_user.email=
> che.test_user.password=
