### ISSUE TITLE
CHE_SINGLE_PORT=true mode is broken with Che6

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#7362]
### Description
Start Che 6 with `-e CHE_SINGLE_PORT=true` expecting that all traffic is using 8080 port.
It doesn't work.

### Reproduction Steps
Use of `-e CHE_SINGLE_PORT=true` to start Che 6

**OS and version:**    
macOS High Sierra 10.13.1 (17B48) / Docker version 17.11.0-ce-rc3-mac38 (20152)

**Comment by benoitf** [comment]
I don't know why platform label has been removed but all components used by this features has been changed by platform team without adressing the usecase of single port (I added many feedback through comments in PR/issues and it was not answered)

**Comment by skabashnyuk** [comment]
Yes, I confirm that my team has made significant changes in runtime model, basically that was the goal of CHE 6, but unfortunately, we have no room to place this task on our TODO list right now, I'll ask the maintainer of this code to take a look, maybe he can help us.

**Comment by mshaposhnik** [comment]
Done;
