### ISSUE TITLE
[CHE 6] Foreign containers events are shown while a workspace starting

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7367]
### Description
Foreign containers events are shown while a workspace starting.

It can be reproduced only when `CHE_INFRA_OPENSHIFT_PROJECT` is specified (when all workspaces objects are created in one OpenShift project).
### Reproduction Steps
1. Deploy Che server on `minishift` or `ocp` with configured `CHE_INFRA_OPENSHIFT_PROJECT`.
2. Start two OpenShift workspaces at the same time.
3. Check output tabs in Che IDE.
<details>
<summary>See screenshot</summary>

![screenshot_20171114_175952](https://user-images.githubusercontent.com/5887312/32790088-20f4b4a4-c966-11e7-9de6-8d9112a11da6.png)

</details>

**Comment by akorneta** [comment]
should be fixed in https://github.com/eclipse/che/pull/7391
