### ISSUE TITLE
How to expose port from my container?

### ISSUE THREAD

**Issue by Mirokko** [eclipse-che/che#7369]
### Description
I cant figure out how i should do this. I need to expose port 3333 for my node.js application (i'm testing adonis framework, if it helps). I added server in workspaces -> test_workspace -> servers like this:
![image](https://user-images.githubusercontent.com/11059471/32798956-4d703c30-c987-11e7-8125-fc927bf53a0c.png)
Next, in commands i have simple command like `cd ${current.project.path} && node server.js`, and in preview url `http://${server.port.3333}`. 
So, problem starts when i try to access generated url. Its unreachable while i can access it via `curl localhost:3333`. I really feeling that i missed something really simple because sample node js project works great on port 3000 (when i serve my app on 3000 port,its not working).

### Reproduction Steps

1. Create new workspace with default node.js template. No project importing.
2. Add server that expose 3333 like on image above.
3. Run workspace.
4. Install adonis cli: `sudo npm i -g @adonisjs/cli`.
5. Run `adonis new test_project`.
6. Copy .env.example to .env
7. Add command that executes `cd ${current.project.path} && node server.js` and have preview url `http://${server.port.3333}` and than run it, click on generated url.
8. Get error in a browser

P. S. Sorry my english isnt very good.

**Comment by ghost** [comment]
@ToKaTpoHb you need to unbind your application from localhost, ie specify host at 0.0.0.0 in your node.js app

**Comment by Mirokko** [comment]
Thanks. Now it works like a charm. For those who wondering how to do it:
You need to edit .env file and change HOST to 0.0.0.0.
