### ISSUE TITLE
Is it possible to manual save?

### ISSUE THREAD

**Issue by alenaksu** [eclipse-che/che#737]
Now everytime I make a change to the code in the editor, it is saved automatically. I would rather be able to save the file manually, with CTRL+S for example.

**Comment by slemeur** [comment]
Hello @alenaksu. At this moment, the editor is auto-saving the edits you are doing in file.
For now, user does not have the ability to deactivate this feature but it is something we have considered to add in the future..

**Comment by TylerJewell** [comment]
We have no plans to add this feature for now.
