### ISSUE TITLE
Multi User Che: Can't use identiy provider delegation for login because the che theme doesn't support it

### ISSUE THREAD

**Issue by bs-matil** [eclipse-che/che#7371]
### Description
Goal:
As a User I want to login with a custom idP into multiuser che. 

### Reproduction Steps
* The idP has been configured in the che realm. 
* Login to che
* No element shown to choose the configured provider

**OS and version:**    
5.19.0

**Comment by ghost** [comment]
@bsukramlitt no element may be displayed if a provider is miconfigured though it then worked for GitHub for me...

**Comment by bs-matil** [comment]
@eivantsov in which way? If I use the default keycloak theme everything works out fine.

**Comment by bs-matil** [comment]
If I add a provider there is just a string "Login with OAuth" displayed but nothing else while in the keycloak default theme a selection box on the right works as expected.

**Comment by ghost** [comment]
@bsukramlitt labeled as a bug. Custom identity providers slipped from our attention.

**Comment by artaleks9** [comment]
Still actual for ver.6.5.0

**Comment by slemeur** [comment]
@vkuznyetsov + @ashumilova + @skabashnyuk : Could you sync on this issue and see how it can be  handled in your next sprint ?

**Comment by ashumilova** [comment]
@slemeur IDE2 team is taking it.
