### ISSUE TITLE
Add an ability to hide and restore the workspace/machines output tabs from IDE

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7375]
### Description
After start of IDE workspace start and machines output tabs are useless for me but they consume space on UI and I'm not allowed to close/hide them. 
It would be useful to allow a user to do that. For example, we can show them in machines tree view and allow to close on tabs list, but when user need it he would be able to click on the needed entry in machines tree to open that view.

**Comment by ashumilova** [comment]
Need to add new item to machine's menu:
![screenshot from 2017-11-22 11-55-03](https://user-images.githubusercontent.com/1611939/33120902-10ed36c8-cf7c-11e7-93f1-bef9f7a4c001.png)
called **Logs** that will open the machine's logs.
