### ISSUE TITLE
Do not change focus of a currently opened panel

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7376]
When trying to follow logs of a workspace start, the focus is changed to a different tab:

![image](https://user-images.githubusercontent.com/5337267/32829032-80b31c44-c9f9-11e7-95d1-5ffabb1ac9e2.png)
![image](https://user-images.githubusercontent.com/5337267/32829048-94000fe6-c9f9-11e7-9e07-87644f80014b.png)

**Comment by garagatyi** [comment]
This behavior leads to failure of selenium tests since changing the focus when a test doesn't expect it make a test fail.
