### ISSUE TITLE
CHE-6: Persist workspace logs

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7386]
Currently, workspace logs are not saved anywhere which makes debugging and investigating issues quite problematic.

**Comment by skabashnyuk** [comment]
Your proposals?

**Comment by ghost** [comment]
@skabashnyuk If a common strategy is used, create a subpath with mkdir pod and mount ~/che/ws-agent/logs. So, there will be /projects and /logs in this directory.

In case of a unique strategy just mount an additional path.

@akorneta may want to comment too :)

**Comment by skabashnyuk** [comment]
Will be fixed by https://github.com/eclipse/che/issues/7807

**Comment by akorneta** [comment]
for the OpenShift flavours, the log backup was done in the scope of this PR: https://github.com/eclipse/che/pull/8535

**Comment by eivantsov** [comment]
Closing as implemented. WS logs are in workspace PV.
