### ISSUE TITLE
Data stored in Che volumes on OpenShift are not removed after removal of a workspace

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7393]
### Description
The reason is that Che removes PVCs but doesn't control removal of data from PVs.
This may lead to the situation when FS of CI is overblown with out-of-date data of removed workspaces.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by akorneta** [comment]
Such behaviour was desired for `unique` strategy. For cleanup PV the cluster admin can configure reclaim pod that is scrub all the volume data in PV after PVC removal or do it manually. How to configure such job see also:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#recycling
https://kubernetes.io/docs/admin/kube-controller-manager/

**Comment by garagatyi** [comment]
Fixed by @riuvshin in #7529
