### ISSUE TITLE
"Workspace Loading" Animations Use Much CPU

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#7424]
The anmations shown in Che 6 when starting a new workspace (or when the workspace has been idled) seem to take up a full core of my 4-core machine. 
I determined that by observing the chromium processes with "top" on my fedora 27 machine.

**Comment by ghost** [comment]
@vitaliy-guliy @ashumilova can you comment please?

**Comment by vitaliy-guliy** [comment]
We removed the animation. It's in my latest [pull request](https://github.com/eclipse/che/pull/7396) and will be merged soon.

**Comment by tsmaeder** [comment]
![cpuload](https://user-images.githubusercontent.com/13163770/32947147-bfba7be2-cb9a-11e7-9860-31c8c571eb1e.gif)

**Comment by vitaliy-guliy** [comment]
Could you please investigate it using Chrome task manager?

![chrome task manager](https://user-images.githubusercontent.com/1655894/32950921-c5dcc4e2-cbb0-11e7-8f25-7181994b14a1.png)
