### ISSUE TITLE
Signature help is too slow on big projects

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7432]
### Description
Signature help feature is slow on big projects, which makes it barely usable.
For Che in Che it takes about 15-20 seconds and IDE is blocked by loader.

### Reproduction Steps
1. Open Che in Che
2. Find any `System.getenv(VAR_NAME)`
3. Go to `getenv` word in editor
4. Invoke signature help with `Ctrl + P` shortcut

Quick response is expected, but loader appears for 15-20 seconds.

**OS and version:**   Fedora 25, Che6, mounted Che project.

**Comment by tsmaeder** [comment]
@mmorhun how does jdt.ls behave?

**Comment by mmorhun** [comment]
@tsmaeder I don't know

**Comment by mmorhun** [comment]
I've just tried to reproduce the issue using Che 7 Multiuser with TLS on Minikube and signature help (`Shift`+`Ctrl`+`Space`) didn't work for me at all.
So the issue is still actual!
