### ISSUE TITLE
Add action to open selected file in editor

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#7434]
### Description
Using Eclipse Che on an iPad user may discover a problem when double tapping the screen will zoom in display instead of process a double click. So, it would be useful to add action in _Edit_ menu which will open selected file from application context in editor.

![img_0008](https://user-images.githubusercontent.com/1968177/32951589-19e51754-cbb3-11e7-892d-0eace1d9565b.PNG)

**Comment by vzhukovs** [comment]
There is an action in context menu for this kind of operation. So this issue is redundand.

**Comment by Transmitt0r** [comment]
@vzhukovskii  Alright, but how does one open the context menu on a touch-device?
