### ISSUE TITLE
[CHE6 branch] Wrong default "build and run" command for build maven spring project

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7438]
*Related test:*
**_CheckIntelligenceCommandFromToolbarTest_**

### Reproduction Steps
 - Go to dashboard and run default java stack with default spring project
 - Wait until workspace is started
 - Click on drop-down list with commands on the command toolbar
 - Click on "build and run" command
 - Pay attention to the terminal output

**Expected behavior:**
Command will be successfully completed without errors. And preview link will be available in the terminal and after click on the preview button in the commands toolbar.

**Observed behavior:**
The project build is broken and preview links are not available.
 
**OS and version:**    
Che6 - 6.0.0-M2 ; Chrome 59.0 ; Fedora 25

**Attachment:**

![aaa](https://user-images.githubusercontent.com/22724619/32954478-e50b018e-cbbb-11e7-9dcc-3538ca6074a7.png)

**Comment by ghost** [comment]
Looks like project selection did not work and current.project  macro returned nothing

**Comment by Ohrimenko1988** [comment]
Fixed
