### ISSUE TITLE
Italic text glyphs looks clipped.

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#7445]
![image](https://user-images.githubusercontent.com/14976516/33005768-462210e6-ce02-11e7-8da1-db2855479dd6.png)

Found this on current stable 5.x

**OS and version:**    Codenvy 5.20.0 in Windows 10

**Comment by sr229** [comment]
Seems to be present in 6.5.3 as well.

**Comment by ashumilova** [comment]
Fixed by https://github.com/eclipse/che/pull/10632
