### ISSUE TITLE
Refactor installers provisioning in machine config

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7464]
### Description
As result of the following discussion https://github.com/eclipse/che/pull/7126#discussion_r151607557
Now we add common environment variables and apply installers servers and env vars on machines configs while preparation step in `RuntimeInfrastructure`.
It's needed to move this logic to the creation of `InternalEnvironment`.
It's also needed to remove `InfrastructureProvisioner` extension point on SPI level, including ProjectsVolumeForWsAgentProvisioner.
To accomplish this redesign we want to add `volumes` and `env` fields to Installer object which would synchronize installer and machine models.

**Comment by garagatyi** [comment]
I've changed title and added additional info into the description in accordance with our latest discussions.

**Comment by garagatyi** [comment]
Won't be addressed in Che6 and in Che7 we won't have installers. Closing.
