### ISSUE TITLE
There is a blank screen in the Editor after refreshing web page

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7468]
**Reproduction Steps:**
- Create a workspace with the **web-java-spring** project;
- Open in the **Editor** any file from the **External libraries**;
- Refresh the web page.

**Expected behavior:**
The opened file is not restored  and in the **Editor** is visible link for creating new project.

**Observed behavior:**
The file is not restored but there is a blank screen in the **Editor**.

**Che version:** 5.21.0-SNAPSHOT 
**OS and version:** Fedora 25

**Additional information:**
![external_libraries](https://user-images.githubusercontent.com/7760565/33025752-7662bafc-ce17-11e7-8825-21f0c499c097.gif)

**Comment by vparfonov** [comment]
not actual any more
