### ISSUE TITLE
How to get the workspace port in previewUrl?

### ISSUE THREAD

**Issue by alenaksu** [eclipse-che/che#747]
Hi, 
is it possible to get only the workspace port in the previewUrl?
I want to achieve something like this: `http://ws-${workspace.port}.mydomain.com/${current.project.relpath}`
Where `${workspace.port}` is the hypothetical variable

Thanks in advance

**Comment by ghost** [comment]
Take a look at available macros in docs - https://eclipse-che.readme.io/docs/commands#macros

**Comment by alenaksu** [comment]
@eivantsov Thank you for reply
`${server.port.<port>}` returns also the server address. I would get just the port.

There's a macro that I'm missing?

**Comment by ghost** [comment]
Unfortunately, there's no macro that will be translated into a port.

**Comment by TylerJewell** [comment]
@eivantsov This needs to be tracked as a development issue. I think this would be a good enhancement to add to the macros list.

**Comment by TylerJewell** [comment]
@alenaksu hi - this is getting slotted into an upcoming sprint.  You can expect a resolution soon.
https://github.com/eclipse/che/issues/953

**Comment by alenaksu** [comment]
@TylerJewell thanks a lot guys!

**Comment by TylerJewell** [comment]
Going to close this issue and ask that you track #953 instead.
