### ISSUE TITLE
Add an ability to manage machine volumes in UD

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7478]
### Description
PR #7446 adds volumes to the machine configuration. But to add volumes user have to edit raw workspace config or use API.
We need UI for this feature.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@ashumilova @slemeur FYI

**Comment by ashumilova** [comment]
@garagatyi thank you
