### ISSUE TITLE
Remove exec/terminal agents from dependencies of ws-agent

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7482]
### Description
Currently, ws-agent installer [has terminal and exec agents as dependencies](https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.json#L6). But it doesn't depend on it, to be honest.
I suggest removing these dependencies.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@gazarenkov FYI

**Comment by gazarenkov** [comment]
It is logical.
@vparfonov @azatsarynnyy 
Does or will and how IDE support the case when there is ws-agent but no exec-agent (no command so) and|or no terminal-agent (terminal wont work)?

**Comment by azatsarynnyy** [comment]
IDE in Che 6 should handle it properly.
