### ISSUE TITLE
Add some new macro for commands

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#7485]
### Description
When I'm trying to develop che plugin in che I need couple more macro for commands.
1. ```{workspace.name}``` - the name of the current workspace
2. ```{workspace.namespace}``` - the name of the workspace namespace
3. ```{current.project.root.path}``` - root path of the current project

**Comment by dkulieshov** [comment]
Hi,

I as of what I see `${workspace.name}` and `${current.project.root.path}` are already present. Please refer to [`CurrentProjectPathMacro.java`](https://github.com/eclipse/che/blob/6e9825c699d34eef6b8bf36fc0194ff871cbee84/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/macro/CurrentProjectPathMacro.java) and [`WorkspaceNameMacro.java`](https://github.com/eclipse/che/blob/6e9825c699d34eef6b8bf36fc0194ff871cbee84/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/macro/WorkspaceNameMacro.java) correspondingly.

**Comment by skabashnyuk** [comment]
@dkuleshov please make sure that ```${current.project.root.path}``` and ```${current.project.path}``` are different. For instance if I select ```/projects/che/core/che-core-api``` module ```${current.project.root.path}=/projects/che``` and ```${current.project.path}= /projects/che/core/che-core-ap```

**Comment by dkulieshov** [comment]
I see what you mean, however I'm not sure that `${current.project.root.path}` is suitable name here, I guess we should call it `${current.project.parent.path}` or something like that, because for me project root path and project path mean the same.

**Comment by skabashnyuk** [comment]
@dkuleshov up to you and @vparfonov
