### ISSUE TITLE
Upgrade Docker API version to latest supported in Docker 1.11 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7496]
### Description
Our Docker client uses Docker API version 1.20. 
According to [our docs](https://www.eclipse.org/che/docs/setup/getting-started/index.html#quick-start) minimal Docker version is 1.11.
So we can upgrade Docker API version to be able to use more features and more modern API 1.23.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@eivantsov FYI

**Comment by skabashnyuk** [comment]
I'm proposing   Docker 17.04.0-ce release 04/03/2017 API version 1.28.

**Comment by riuvshin** [comment]
update to 1.23 is safe because we don't change minimal docker engine version, but update to 1.28 could be a problem, because for example, RHEL / CentOShave own packaging of docker which still 1.12.x so we could have issues with running on it.

**Comment by skabashnyuk** [comment]
@riuvshin @garagatyi Make sense I agree with you.
