### ISSUE TITLE
Apply changes for selenium tests from Che6 branch to master

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7504]
### Description
In the **che6** branch we made some important improvements and fixes that can be applied for master branch. This will be able to stabilize tests and enhance results. Also it'll reduce time for checking regression by QA.
Next selenium test will be updated:
- **NavigateToFileTest**
- **SwaggerTest**
- **CheckMavenPluginTest**
- **CheckFindActionFeatureInCheTest**
- **DebugExternalClassTest**

We also need add try/catch blocks to selenium tests as is in **CHE-6** branch:
- **DiffViewTest**
- **UpdateToRevisionTest**
- **LockFileTest**
- **CheckMavenPluginTest**
- **RefactoringFeatureTest**

Next selenium tests need change for tests stability:
- **CheckFactoryWithSincePolicyTest**
- **CheckFactoryWithUntilPolicyTest**
- **DeleteProjectsTest**
- **CreateAndDeleteProjectsTest**

**OS and version:**  Che 5.22.0 SNAPSHOT.

**Comment by dmytro-ndp** [comment]
This issue is redundant, IMHO, so as we are updating master branch on a regular base usually.
If we have some non-merged changes for Che6, we ought to merge them into the master branch as part of specific issue for that changes.
