### ISSUE TITLE
Configure CHE6 for passing the 'CppProjectDebuggingTest' 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#7513]
### Description
* Need to configure CHE6 environment for success pass the 'CppProjectDebuggingTest'
* Uncomment the _**CHE_DOCKER_SECURITYOPT=seccomp:unconfined**_ in the 'Workspaces' part of environment
![che6-env-debugger](https://user-images.githubusercontent.com/5408906/33132359-2e4cca78-cfa2-11e7-9a0c-e446756be063.png)

**Comment by riuvshin** [comment]
Done
