### ISSUE TITLE
[CHE 6] Set default memory limit for OpenShift workspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7518]
### Description
There is [default memory limit](https://github.com/eclipse/che/blob/84564f2e5547e36a65c9f89c2959451494c869ce/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L82-L83
) configuration property that is used by Docker infrastructure but not used by OpenShift infrastructure.

So it is needed to set default memory limit for workspaces started by OpenShift infrastructure.
For such purposes `che.workspace.default_memory_mb` can be used or new ones can be introduced while one property could be not enough because OpenShift Resources Limits allow setting memory request and memory limit and setting both of them can be useful.

**Comment by akorneta** [comment]
done in https://github.com/eclipse/che/pull/8228
