### ISSUE TITLE
Che breaks some utf symbols

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7528]
### Description
If java file with UTF-8 encoding contains some language specific symbols, the symbols will be replaced with `?` after save.
Note, if autosave is enabled, then user will see the breaks immediately after save, but if autosave is disabled Che saves `?` but continue displaying correct characters. The problem will be spotted when file reopened.

### Reproduction Steps
1. Open a java file with some special symbol like `ă` or `Ž` or so.
2. Make any changes and save changes (or wait autosave)
3. Reopen file

All special symbols will be replaced with `?`

Screencast:
![utf-8](https://user-images.githubusercontent.com/15607393/33174195-97b92246-d05f-11e7-8260-b78b3882be51.gif)

**OS and version:**   Fedora 25, Che6, mounted Che in Che

**Comment by dkulieshov** [comment]
Can't reproduce on 6.0.0-M3, please reopen if this bug happens again.

**Comment by tsmaeder** [comment]
"Computer says no" to my name :-(
