### ISSUE TITLE
Unexpected hanging of a browser during using of CHE

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7534]
**Reproduction Steps:**
* Launch CHE 6 under docker.
* Create workspace from the CHE stack and clone CHE based on master
* Build  the project with maven 
* Open a class form the current project and Git->Compare with che6
* Copy all content from CHE6 section and paste into CHE
* Save changes
* Open the just changed file

**Problem:**
When i tried copy and paste content from the right section of compare widget (with che6), the copy/paste feature did not work. As clarifed later - the browser was hung. After 5-10 min the browser became avialible. I applied changes from the right section of the comparator. But after opening just edited file the code validator shown all code as invalid. Refreshing browser did not resolve the problem. I stopped the workspace and launch it again. I tried open the test class by Navigate to file. But feature did not work. In the ws console were a lot of exceptions. In java script console of the browser also were exceptions. See below for more details:

**Js errors:**
![selection_020](https://user-images.githubusercontent.com/1640058/33176969-a7143820-d069-11e7-95dc-4fb8a82d008b.png)

![selection_021](https://user-images.githubusercontent.com/1640058/33176961-9e481d06-d069-11e7-8905-875af63765ba.png)

![selection_022](https://user-images.githubusercontent.com/1640058/33176950-945202c6-d069-11e7-8a53-32c053d2e32c.png)

**ws-agent errors fragment:**
![selection_024](https://user-images.githubusercontent.com/1640058/33177097-21783a3a-d06a-11e7-88cd-a9cc59f6fa98.png)

**Che version:**  Che6 -M2, chrome browser V.62, rev.:25b42c41bc29e50e

**OS and version:**    Fedora 25

**Comment by mmorhun** [comment]
I found a way how to reproduce IDE hunging:
1. Open Che in Che (mounted project)
2. Open a few files from different modules
3. In project explorer select root Che project and from context menu hit `Maven` -> `Reimport`
4. Invoke Content Assistant in an open file, a popup with message that the feature unavailable during reimport should appear.
5. Wait a minute or two. Finally, in most cases, IDE hungs and a Chrome's window with Wait and Kill buttons will appear.

**Comment by RomanNikitenko** [comment]
I faced with IDE freezing too. 
In my case doesn't matter mounted project or not, but it is reproduced for project configured as maven.
I can not reproduce it for project configured  as Blank.

**Comment by vinokurig** [comment]
Should be fixed by https://github.com/eclipse/che/issues/7773
