### ISSUE TITLE
Host field is unreadable at uploading ssh key

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#7536]
### Description
Host field is unreadable at uploading ssh key
![host_bug](https://user-images.githubusercontent.com/5676062/33182701-ba470dfa-d07d-11e7-8a1f-222148d40fc9.gif)

**OS and version:**    
Fedora 25
Che version: 5.22.0

**Comment by slemeur** [comment]
won't fix on Che 6
