### ISSUE TITLE
Docker store image fails to start (or info)

### ISSUE THREAD

**Issue by mikarinneoracle** [eclipse-che/che#7546]
### Description
Running https://store.docker.com/images/eclipse-che
I get this error below on OSX and OL6.6
both info and start

docker run -it --rm -v /tmp:/data -v /var/run/docker.sock:/var/run/docker.sock store/eclipse/che:5.1.2 info
INFO: (che cli): Checking network... (hin: '--fast' skips version, network, and nightly checks)
INFO: (che cli): Pulling image alpine:3.4
INFO: (che cli): Pulling image eclipse/che-ip:nightly
INFO: (che cli): Loading cli...
parse error: Invalid numeric literal at line 1, column 10
/scripts/base/library.sh: line 537: [: 10: unary operator expected
parse error: Invalid numeric literal at line 1, column 10
/scripts/base/library.sh: line 284: 2: unbound variable

### Reproduction Steps
See above

**OS and version:**    
OSX
OL6.6

**Diagnostics:**

**Comment by ghost** [comment]
@mikarinneoracle why such an old tag? Can it be reproduced with the latest tag?

**Comment by mikarinneoracle** [comment]
Absolutely, what's the latest ?
This works .. eclipse/che-server:5.0.0-latest - 5.5.0 ?
What's the latest for that one ?

**Comment by ghost** [comment]
@mikarinneoracle Drop the tag and you will get the latest one.

**Comment by mikarinneoracle** [comment]
Ok, thanks

**Comment by mikarinneoracle** [comment]
Solved.
