### ISSUE TITLE
Unexpected fails of selenium tests after web page refreshing

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7551]
### Description
We have unexpected fails of selenium tests when the project sometimes is not restored previous state in the IDE after refreshing the browser. It must be restored with expanded project explorer and opened tabs in the editor exactly like before refresh.

**Before refresh:**
![screenshot from 2017-11-24 17-02-17](https://user-images.githubusercontent.com/22724619/33215719-61d3a27a-d139-11e7-9c16-f14be1694f24.png)

**After refresh:**
![screenshot from 2017-11-24 17-02-43](https://user-images.githubusercontent.com/22724619/33215720-64425ac4-d139-11e7-84cb-6a9021716c46.png)

*Report with reproduced problem:*
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6/92/Selenium_tests_report/
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/126/Selenium_tests_report/
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/66/Selenium_tests_report/

**OS and version:**    
Che 6.0.0-M2 ; Chrome 59.0 ; Fedora 25

**Related selenium test:** ProjectStateAfterRefreshTest, CheckRestoringSplitEditorTest, ConvertToProjectWithPomFileTest, ProjectStateAfterRenameWorkspaceTest

**Comment by Ohrimenko1988** [comment]
preferences in the tests:

success test:
```
{\"revealPath\":
[\"/projectq6j9\",\"/projectq6j9/src\",\"/projectq6j9/src/main\",\"/projectq6j9/src/main/java\",\"/projectq6j9/src/main/webapp\",\"/projectq6j9/src/main/java/che/eclipse/sample\",\"/projectq6j9/src/main/java/org/eclipse/qa/examples\",\"/projectq6j9/src/main/webapp/WEB-INF\",\"/projectq6j9/src/main/webapp/WEB-INF/jsp\"],\"showHiddenFiles\":false}
```

failed test:
```
{\"revealPath\":
[\"/pull-request-plugin-test\"],\"showHiddenFiles\":false}
```

**Comment by SkorikSergey** [comment]
This issue sometimes reproduces after restarting of workspaces. 
**Failed test:** ProjectStateAfterRefreshTest

**Comment by vparfonov** [comment]
Will be very useful to have ability to see logs form Chrome console in selenium reports

**Comment by SkorikSergey** [comment]
Steps to reproduce:
1. Start two workspaces with projects.
2. Open any files in the both workspaces.
3. Check workspaces preferences on **your_url:8080/api/preferences**. Project states from both workspaces is present(see **screenshot 1**).
4. Open any file in any workspace and check workspaces preferences again.

Project state from other workspace doesn't exist(see **screenshot 2**).

Screenshot 1.
![172 19 20 28 8080-api-preferences - google chrome_196](https://user-images.githubusercontent.com/7760565/36896057-d0ee5b3c-1e19-11e8-92c1-3180f66575cb.png)


Screenshot 2.
![172 19 20 28 8080-api-preferences - google chrome_197](https://user-images.githubusercontent.com/7760565/36896060-d3f99c42-1e19-11e8-9fc7-c02587eb62f1.png)
