### ISSUE TITLE
Factories are not consumed properly

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7555]
### Description
This issue is moved from "codenvy" repository:
https://github.com/codenvy/codenvy/issues/2255

If we launch for example **CheckBitnamiSwiftFactory** test,   the factory that is consumed by test hangs on workspace creation operation. The test performs next steps: go to the login page, set authorization cookies, through WebDriver mechanism and get factory.

**Additional info:** html traffic produced by test below. For analize - unpack file and load to HAR viewer.
[traffic.zip](https://github.com/codenvy/codenvy/files/1048217/traffic.zip)
**Har viewer:** https://ericduran.github.io/chromeHAR/

![screenshot from 2017-11-24 16-35-10](https://user-images.githubusercontent.com/22724619/33217404-8013568e-d140-11e7-9ea3-ee80e7d47fbe.png)

**Comment by tolusha** [comment]
master/agent logs needed

**Comment by olexii4** [comment]
fixed in https://github.com/eclipse/che/pull/7956/commits/924120cc8d5747d07ea7202f013422a297b8c5a8

**Comment by Ohrimenko1988** [comment]
reproduced in:
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/118/Selenium_tests_report/
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/115/Selenium_tests_report/
