### ISSUE TITLE
Display resource errors (e.g. compiling errors) displayed by a language server into the Project Explorer view

### ISSUE THREAD

**Issue by julsarik** [eclipse-che/che#7557]
### Description
Errors detected by a language server should be reflected in the Project Explorer view.

### Requirements
Let's suppose I have a resource containing errors. I want this resource and its parents to be underlined in the Project Explorer as in the following example :

- current behaviour :

![no-error](https://user-images.githubusercontent.com/33962711/33218668-6a434e10-d13e-11e7-94eb-94dc70349a57.png)

- expected behaviour :

![error](https://user-images.githubusercontent.com/33962711/33218679-79c2b5c4-d13e-11e7-854c-dc3cf7f08999.png)

### Linked issues
This requirement is an extension of #5926 but applied to resources managed by a code server.

**Comment by julsarik** [comment]
I've done the development on my machine. It's only 5 classes to change. If I'm given the rights on the repository I can do a pull request.

**Comment by gorkem** [comment]
You do not need rights to the repository for making a Pull Request. Follow these [instructions](https://help.github.com/articles/creating-a-pull-request/)

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
