### ISSUE TITLE
Cannot input tab in Makefile

### ISSUE THREAD

**Issue by oska874** [eclipse-che/che#7559]
### Description
tabs in makefile must be real tab,but eclipse che changed tab into 4 spaces as default.
Now I can change the configuration to input real tab,but I think che can recognize where tab should not be changed to spaces

### Reproduction Steps
create a makefile and input tab.

**OS and version:**    
ubuntu 16.04.3
**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
You can change tab size for current active editor: Profile -> Preferences -> In the IDE chapter select editor item. In the editor preferences page you can change tab size. Default value is really 4.

**Comment by bmicklea** [comment]
Closing this issues as solved. You can reopen if there an issue remains.
