### ISSUE TITLE
Investigate how CHE server can be configured in case of deploy on OCP

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#7571]
Today we have many issues with `deploy_che.sh` and `che-openshift.yml` due to lots of `sed` commands that really hard to support and also we are not able to change all CHE configuration parameters on OCP. For example just to add ability to configure oAuth for CHE I used to extend deploy script https://github.com/eclipse/che/pull/7212/files which is really bad thing to do if we are talking about whole set of CHE configurations that way does not work at all.

~~So the idea is try to generate `che-openshift.yml` from a puppet template and make deploy script really simple.~~

We decided that using CHE CLI for that will make this very complex and non trivial in support, So I will try to get rid of seds and allow to set any config for CHE server with minimum effort for a user

**Comment by gorkem** [comment]
What is the advantage of using a puppet template over any other? Would openshift templates be enough here?

**Comment by riuvshin** [comment]
~~We use CHE CLI to manage CHE configuration, and in CHE CLI we use puppet. So we have all CHE configurations in the CLI and we just need to generate `che-openshift.yml` based on that configuration instead of doing lots of `sed`. Btw `che-openshift.yml` is already under puppet but as a file not as a template: https://github.com/eclipse/che/tree/che6/dockerfiles/init/modules/openshift/files/scripts
With that approach using CHE CLI we should be able to run CHE on docker OR on OS with exactly same set of configuration~~

After some investigation it becomes clear that CHE CLI is overkill and makes it really complicated. I was not familiar with `openshift templates` and it seems it should be something better... And I should investigate that.
