### ISSUE TITLE
New Che 6 UI completion/refinements

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#7577]
### Description
The goal of this issue is to list all the different elements that are not yet completed in the new Che 6 UI. Those elements could be styles and behaviours.

#### Sub tasks list
- [x] Panel: Make panel icons (options, maximize and close) size consistent, review icons on correct paddings, etc. Change the colors to a lighter color (proposal: #878FA5)
- [x] Process Panel: Add more space between icon and title on tabs in the Processes panel
- [x] Process Panel: Add header in list of machines and revise the styles for each machine item
![screen shot 2017-11-27 at 13 19 49](https://user-images.githubusercontent.com/1636769/33268244-d27ce776-d37c-11e7-984c-a89300828f3f.png) 
- [x] Process Panel: The style of the output toolbar is not consistent
- [x] General: Use consistent font size and styles in the project explorer, editor tabs. 
- [x] General: Review the separator styles between each areas of the IDE
![screen_shot_2017-11-27_at_15_11_37](https://user-images.githubusercontent.com/1636769/33270808-95afad8e-d385-11e7-8377-68cd50877b64.png) 
- [x] General: Replace the background color of the "<" button to show/hive the dashboard sidebar to (#FCC13D)
- [x] General: Adopt style in the popups 
- [x] General: Buttons' style should not use rounded corners
![screen shot 2017-11-27 at 14 48 06](https://user-images.githubusercontent.com/1636769/33270860-c49382ba-d385-11e7-8348-febcb8e02525.png) 
- [x] Commands: Update styles of command's editor
- [ ] Commands: Consistent font size for the command controller
- [x] Preferences: Update styles

**Comment by sr229** [comment]
To be honest the rounded buttons looks like more of a feature than a bug. 😄

**Comment by slemeur** [comment]
@sr229 : As for now, with the current styles of Che, it feels inconsistent. Don't you think so?

**Comment by sr229** [comment]
@slemeur I agree but probably we can adapt the design if that's the case for these buttons
