### ISSUE TITLE
Use widgets instead of custom actions to show the last ones in status bar

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#7586]
### Description
In according to issue https://github.com/eclipse/che/issues/7314 there was a need to restore status bar only. But during the work were discovered a few moments that need to be improved:

1. Status Bar uses Action Manager to display the actions on the status panel, see class `org.eclipse.che.ide.menu.StatusPanelGroupViewImpl`
2. To display the action on the status panel developer need to extends `CustomComponentAction` to provide custom widget for the action.

There were thoughts that it is not logical to display widgets via actions. We can operate directly with widgets. So I propose to create hierarchy of interfaces in api and app to operate with widgets in status bar.

![img_0140](https://user-images.githubusercontent.com/1968177/33280043-778e2816-d3a9-11e7-8c67-bb8490af6bbf.jpg)

User will operate only with interface `StatusBarManager` to provide custom widgets into status panel.

**Comment by vzhukovskii** [comment]
Not actual
