### ISSUE TITLE
Google Hangouts logo?

### ISSUE THREAD

**Issue by Arcanemagus** [eclipse-che/che#7587]
### Description

On the https://www.eclipse.org/che/ website in the "Chefiles - Clonable, Reproducible, Lightweight Workspaces in Eclipse Che" section there is a giant Google Hangouts logo. Since this section has nothing to do with Google Hangouts, I'm a bit confused as to what their logo is doing here, especially since no mention is made in the text of the site as to that it's their logo. Right now it _looks_ like somebody just grabbed a random image, but the source code explicitly stating it's `google-hangout` means this was done on purpose for some bizarre reason.

### Reproduction Steps

Open https://www.eclipse.org/che/ and scroll down till you find the giant Google Hangouts logo:
![image](https://user-images.githubusercontent.com/427137/33289377-305597e8-d374-11e7-9838-ddf48630b3a5.png)

**OS and version:**    

N/A

**Diagnostics:** 

N/A

**Comment by slemeur** [comment]
Fixed:
<img width="1201" alt="screen shot 2017-11-28 at 18 17 52" src="https://user-images.githubusercontent.com/1636769/33333889-78d0af22-d468-11e7-8a09-76e8b5e9c6db.png">

Thanks for reporting this @Arcanemagus.

**Comment by Arcanemagus** [comment]
@slemeur I'm seeing this:
![image](https://user-images.githubusercontent.com/427137/33345929-d2b9d48a-d442-11e7-9e08-53eb7f3b2632.png)

Browser: Chrome (62.0.3202.94 and 64.0.3278.0)
OS: Windows 10 x64
Resolution: 1920x1080
Scaling: 100%

**Comment by slemeur** [comment]
Should be better now. Thanks.
