### ISSUE TITLE
Support for EditorConfig

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#7588]
### Description
We should support the [EditorConfig](http://editorconfig.org/) to define coding styles and honor `.editorconfig` files that exists on a project.

**Comment by AndrienkoAleksandr** [comment]
Seems related https://github.com/eclipse/che/issues/7559

**Comment by skabashnyuk** [comment]
Probably related to https://github.com/eclipse/che/issues/8266 because of this https://github.com/eclipse/che/issues/5330

**Comment by skabashnyuk** [comment]
@ashumilova @evidolob please take a look at this issue. wdyt how it can be related to Theia IDE?

**Comment by vitaliy-guliy** [comment]
Left to do:
- handle charset, trim_trailing_whitespace and insert_final_newline properties
- listen changing of .editorconfig file and update configuration of opened editors
- write tests for the plugin using jest

**Comment by vitaliy-guliy** [comment]
Work is done.
Editorconfig extension in separate branch on Theia repository.
https://github.com/theia-ide/theia/tree/editorconfig

**Comment by vitaliy-guliy** [comment]
An issue with discussion on Theia repository
https://github.com/theia-ide/theia/issues/1694

**Comment by vitaliy-guliy** [comment]
PR with the extension
https://github.com/theia-ide/theia/pull/1708
