### ISSUE TITLE
Vanilla Kubernetes support

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#7589]
### Description
We need to support kubernetes  either by removing Openshift specific bits or creating a kubernetes SPI implementation for Che 6. @l0rd had a demo at JavaOne that worked with Che5  which can be useful here is the [branch](https://github.com/l0rd/che/tree/kubernetes), and the [bash script to install Che on k8s](https://raw.githubusercontent.com/l0rd/che/kubernetes/dockerfiles/init/modules/k8s/files/scripts/deploy_che.sh), and `mariolet/che-server:kube-201710101353` is a che image ready to use with k8s.

**Comment by skabashnyuk** [comment]
@gorkem can you explain how it differs from https://github.com/eclipse/che/issues/5908?

**Comment by gorkem** [comment]
Yes, this is a duppo. Closing.
