### ISSUE TITLE
Merge tables of ServerConfig objects from installers and machines

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7590]
### Description
PR #5876 introduced storing of Installers in the Che DB.
In this PR new table for [ServerConfig of an Installer](https://github.com/eclipse/che/blob/che6/wsmaster/che-core-api-installer-shared/src/main/java/org/eclipse/che/api/installer/shared/model/Installer.java#L61-L61) object was created, but these are the same [ServerConfigs as in MachineConfig](https://github.com/eclipse/che/blob/che6/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/workspace/config/MachineConfig.java#L40-L40) and have its own table in the DB.
This leads us to the situation when we have 2 places with the same entities and will have to maintain/migrate them in 2 places.
So I suggest merging those tables in the DB.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
won't fix. Not relevant for che7
