### ISSUE TITLE
Investigate problem of unexpected failing of WorkingWithTerminalTest selenium test

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#7592]
### Description
Sometimes on CI server we have unexpected fail of next test methods of **WorkingWithTerminaleTest** selenium test:
- **shouldNavigateToMC**
https://ci.codenvycorp.com/job/che-pullrequests-test/157/Selenium_tests_report/
![org eclipse che selenium miscellaneous workingwithterminaltest shouldnavigatetomc_c7i7zc2e 1](https://user-images.githubusercontent.com/7760565/33310887-c9d7a1ec-d42b-11e7-81ce-5ed276ae2b7a.png)
- **shouldScrollIntoTerminal**
https://ci.codenvycorp.com/view/qa/job/che-multiuser-integration-tests-che6/Selenium_tests_report/
![org eclipse che selenium miscellaneous workingwithterminaltest shouldscrollintoterminal_rivfyr9n 1](https://user-images.githubusercontent.com/7760565/33312504-c51a4a2e-d430-11e7-8993-ccc0b04bcfb7.png)
- **shouldResizeTerminal**.
https://ci.codenvycorp.com/view/qa/job/che-multiuser-integration-tests-che6/30/Selenium_tests_report/

**OS and version:** Ci-server, che-selenium integration tests

**Comment by SkorikSergey** [comment]
This issue will be fixed by updating **xterm.js** version(**Update xterm.js to the newer version** - https://github.com/eclipse/che-lib/issues/57).

**Comment by dmytro-ndp** [comment]
Are you sure it is still actual bug? 
I don't see any failures of [WorkingWithTerminaleTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/76/testReport/org.eclipse.che.selenium.miscellaneous/WorkingWithTerminalTest/) on https://ci.codenvycorp.com/view/qa/job/che-integration-tests/ during this month.

**Comment by dmytro-ndp** [comment]
It seems the investigation was done, @SkorikSergey
