### ISSUE TITLE
Not expected behavior in the ProjectExplorer page-object methods

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7605]
### Description
 
We need update ProjectExplorer page-object in the selenium tests, because we have a lot of methods in this page-object which have not expected behavior and must be fixed. This issue is a part of stabilization changes.
This issue affects the problems described in https://github.com/eclipse/che/issues/6524 and complements them with the task of optimizing the code and eliminating duplication and "legacy" code.

For example before optimizing:
```
public void scrollToItemByPath(String path) {
    waitItem(path);
    String locator = "//div[@path='/" + path + "']/div";
    WebElement item = seleniumWebDriver.findElement(By.xpath(locator));
    actionsFactory.createAction(seleniumWebDriver).moveToElement(item).perform();
  }
 ```
 
after optimizing:
```
waitItem(path);
    actionsFactory
        .createAction(seleniumWebDriver)
        .moveToElement(getProjectExplorerItem(path))
        .perform();
```

*Report with reproduced problem:*
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6/96/Selenium_tests_report/

**Comment by dmytro-ndp** [comment]
@iokhrimenko: can you, please, explain what is the "definition of done" of this issue? 
There should be a list of methods which are going to be fixed, IMHO.
Also it looks like the issue duplicates another one: https://github.com/eclipse/che/issues/6524

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp Thank you for your comment. The description was updated.

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/7631
