### ISSUE TITLE
Import project from hosted GIT repository URL: the host name must start with www

### ISSUE THREAD

**Issue by jack-y** [eclipse-che/che#761]
Hi,

I want to import a project from its hosted repository.
The repository is located on an internal server.

The hosted project repository URL is like:
ssh://myname@myserver/srv/git/myproject.git
When i write this URL into The Eclipse Che IDE import project window, i get the error:
The address of the remote server is incorrect.
But if i change this URL as:
ssh://myname@www.myserver/srv/git/myproject.git
there's no error.

How can i import from an internal server repository ?
Thanks

**Comment by ghost** [comment]
You may go to the Terminal:

`cd /projects`
`git clone ssh://myname@myserver/srv/git/myproject.git`

However, you need to set up ssh keys.

Once done, hit refresh button on a project panel, open the project to configure it.

**Comment by jack-y** [comment]
It works like a charm. Thanks!
Eclipse Che is amazing :)
