### ISSUE TITLE
Editor lose focus at switching of displaying panels mode

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#7616]
### Reproduction Steps
1. Turn on mode when all panels are displayed
2. Set focus in editor
3. Turn on another mode (for example, mode when only editor will be displayed)

Expected behavior:
Focus in editor

Observed behavior:
Editor lose focus 

**OS and version:**    
Fedora 25
CHE version: 6.0.0-M3

![focus_switching_displaying_mode](https://user-images.githubusercontent.com/5676062/33367083-f79a8142-d4f5-11e7-9934-9d3a523b9cc3.gif)

**Comment by Ohrimenko1988** [comment]
Small clarification, focus is lost already after click on "panel selector" button
