### ISSUE TITLE
Does Eclipse-che support gogs???

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#7623]
Hi,

Can I use Eclipse-che with Gogs???

**Comment by skabashnyuk** [comment]
Yes. For private repositories you need small aditional step with uploading ssh key to your Eclipse Che profile

**Comment by LahariGuntha** [comment]
Could you please elaborate the steps that need to be followed??

**Comment by LahariGuntha** [comment]
Hi,

Gogs doesn't support OAuth...Then how can we achive this???

**Comment by LahariGuntha** [comment]
Hi 

Here mainly we want to Push our changed code back to Gogs...Is it possible???
We can clone code from Gogs to Eclipse Che...But we are unable to push back the code to  Gogs..

**Comment by skabashnyuk** [comment]
>Here mainly we want to Push our changed code back to Gogs...Is it possible???

If  gogs support ssh - when follow this link https://www.eclipse.org/che/docs/ide/git-svn/index.html#git-using-ssh-keys

**Comment by ghost** [comment]
@LahariGuntha have you tried to set up ssh keys?

**Comment by LahariGuntha** [comment]
Hi,

I did not try yet...But I tried using Gitlab....I have cloned from Gitlab...made changes and was able to push the changes back to gitlab...It was working fine....

**Comment by eivantsov** [comment]
@LahariGuntha any update on this one please?

**Comment by LahariGuntha** [comment]
Yes....It supports cloning from gogs provided the username and password to be provided at the time of cloning..so that we can make any changes to the code and then push it back to Gogs..
