### ISSUE TITLE
Remove data about model entities/fields removed in Che6 from Che DB

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7634]
### Description
We have plenty of data from Che5 which are not needed in Che6. We should remove them if we don't want to wipe the old DB.
Some of the entities to remove:
- MachineSourceImpl
- ServerConfImpl (or ServerConf2Impl)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by mkuznyetsov** [comment]
while using Old Che 5.22.1 and the upgrading to Che 6, I coudn't find neither MachineSourceImpl nor old ServerConfImpl objects  in database. I will close this one, if there are no clear reproduction steps for it
