### ISSUE TITLE
Support for multiple applications on a workspace

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#7642]
Enhance our workspace definitions so that Che allows to develop 2 or more projects that are deployed on different containers within a single workspace.

![image](https://user-images.githubusercontent.com/82738/37248424-35ba5098-24a0-11e8-873e-b9d53a8f84bf.png)

When implementing this feature we should not assume that these projects would be coming from different code repositories. However, it should be safe to assume a project could only be deployed to a single container.

The experience of development activities such as debugging across these multiple containers should also be handled. For instance we should be able to put a breakpoint on two projects that are deployed to two different containers and be able to start debugging for both on a single action. 

See also #8809

**Comment by skabashnyuk** [comment]
Technically I think we have everything on a model to do so. For instance, we can imagine a workspace where you developing serverside on spring and frontend on angular. It will run two containers one with java other with nodejs. I do not guarantee that debugging experience will be silky-smooth,  but I believe we are able to run this workspace, develop code inside of it, run commands, etc.

**Comment by gorkem** [comment]
How would the IDE behave in this case? I have not found a good way to set the IDE to deploy one application to container A and the other to container B. I feel that IDE is missing some piece of information to be able to do that.

**Comment by skabashnyuk** [comment]
I see three ways how IDE can interact with multiple containers.

1. With shared volume. For example, if you have tomcat is running in one container you
can share his webapp folder as the volume between all containers. After that all you need
is just replace the content of application and tomcat will automatically reload it.
2. Over the port. If your server is able to interact with the port you can just talk over http or tcp. For example: if tomcat in the parallel container has management application
you can redeploy other application over the http.
3. Commands. You can run any command in any container. 

I think this 3 ways or combination of it cover pretty much all the cases.

**Comment by gorkem** [comment]
@eivantsov It turns out this is more of a documentation issue can you work with @skabashnyuk on creating a doc for explaining how one can achieve this?

**Comment by ghost** [comment]
I'll create a tutorial for this one as I'll be bringing back tutorials from old docs (need to validate all of them to make sure they are in sync with Che 6)
