### ISSUE TITLE
Use real hostname in functional test on CI of Che6 on OpenShift instead of nip.io

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7643]
### Description
While I'm creating this issue nip.io is unavailable. This leads us to the unstable state of Che6 CI for OpenShift infrastructure.
We need to reconfigure start of OCP to use the public host of CI instance where OpenShift is running.
From what I see now we need:
- fix hardcoded value [here](https://github.com/eclipse/che/blob/che6/dockerfiles/init/modules/openshift/files/scripts/ocp.sh#L131-L131)
-  set OPENSHIFT_NAMESPACE_URL to the public hostname of CI instance with the OpenShift

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by riuvshin** [comment]
we running test on local ocp which is using nip.io not on real hostnames.
We will be able to do so only on acceptances.

**Comment by riuvshin** [comment]
with that PR: https://github.com/eclipse/che/pull/7654/files
we will be able to use other DNS providers. In the same time we've already set up similar service here: `nip.codenvy-stg.com` so if `nip.io` is down we can use our own with:
`export DNS_PROVIDER=nip.codenvy-stg.com`
