### ISSUE TITLE
OutOfMemoryError when use mounted project

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#7645]
### Reproduction Steps
1. Mount project by configuring CHE_WORKSPACE_VOLUME in che.env file
2. Create workspace from 'Java' or 'Eclipse Che' stack
3. Start workspace
4. See logs in dev-machine tab

**OS and version:**    
Fedora 25
![che_version](https://user-images.githubusercontent.com/5676062/33423322-1f03c8b2-d5c1-11e7-8718-62764bce9aed.png)

![che_errors](https://user-images.githubusercontent.com/5676062/33423335-2705ecfc-d5c1-11e7-9e86-2dd153557cb3.png)

**Comment by AndrienkoAleksandr** [comment]
During Dogfooding I catch the same.

**Comment by gazarenkov** [comment]
Do we still need CHE_WORKSPACE_VOLUME in che.env file?

**Comment by garagatyi** [comment]
It is still available for usage

**Comment by skabashnyuk** [comment]
Quite useless BTW if you are not on Linux. Performance of it on not native to docker environments are veeeeeeeery slow.

**Comment by gazarenkov** [comment]
Not sure I understand what does "available for usage" mean :)

**Comment by garagatyi** [comment]
I meant that user can enable this feature by uncommenting this environment variable

**Comment by RomanNikitenko** [comment]
I am closing the issue as using of mounted project is an anti-pattern.
