### ISSUE TITLE
Investigate the reason falling tests from 'dashboard', 'workspaces' packages on the CHE6-ocp

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#7646]
### Description
* Running on the CHE6-ocp the selenium tests from package 'dashboard', 'workspaces' have regress to CHE6 (single/multi)
* We need to find the reason (or reasons) of it
* Related test report: https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-che6-ocp/6/Selenium_tests_report/

**Comment by garagatyi** [comment]
@artaleks9 can you elaborate on which results led to the closing of the issue?

**Comment by artaleks9** [comment]
1) The main reason fail of tests is ssh in the recipe when create workspace on the dashboard
2) When switch to dashboard from the IDE have the error with configuration workspace
3) One of the test is failed by: `Infrastructure not found for type: compose`
