### ISSUE TITLE
Add an ability to exclude tests from test suite

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7669]
### Description
Sometimes we know that some tests will fail and it is a normal situation. For example, compose recipe is not supported by OpenShift infra, so tests that use compose fail.
We need some way to exclude some tests to have an ability to get 100% tests success rate even in such situation. This would decrease the amount of time needed for analyzing tests results by QA and devs.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by dmytro-ndp** [comment]
It was done in issue #7820.
Documentation can be found [here](https://docs.google.com/a/redhat.com/document/d/1UHNYB31q-lVMTbOcqSHTcMJjpCySF9szW4-DHufQKno/edit?usp=sharing).
