### ISSUE TITLE
Reconnect debugger works wrong

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7671]
### Reproduction Steps:
* Set for example incorrect debugger connection (with wrong port). Wait error message. 
* Go to edit debugger configuration menu and set correct values

**Expected result:** We should have ability fix wrong connection parameters and set correct connection.
**Actual result:** After setting correct parameters we have 'Debugger already connected'.

**OS and version:** Fedora 25, chrome browser, CHE-6.0.0-M3

**Comment by tolusha** [comment]
It seems when connection failed the current debugger isn't cleaned up.

https://github.com/eclipse/che/blob/6e9825c699d34eef6b8bf36fc0194ff871cbee84/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/debug/DebuggerManager.java#L56
