### ISSUE TITLE
Encoding issue with jdt.ls javadoc

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#7674]
This happens when using the jdt_ls_poc branch.
1. Create a "quickstart" maven project
2. In the generated test class, hover over the "TestSuite" constructor.
3. Observe: the 'ü' Character is not displayed correctoy in "Hüffihütte"

**Comment by tsmaeder** [comment]
I haven't had time to check wether this is a jdt.ls issue or more general.
![encodingproblem](https://user-images.githubusercontent.com/13163770/33475895-4a2825fa-d680-11e7-887b-492aff5c38f0.png)

**Comment by mmorhun** [comment]
Might be related to https://github.com/eclipse/che/issues/7528

**Comment by mmorhun** [comment]
The problem here that original source isn't utf-8 encoded as we expect.

**Comment by tsmaeder** [comment]
There will be many projects not encoded in utf-8. Does LSP say anything about encoding? Is this our problem or a jdt.ls problem?

**Comment by tolusha** [comment]
![vscode](https://user-images.githubusercontent.com/1640675/35157564-09f63416-fd3d-11e7-8a25-c5c0e2ed4994.png)
