### ISSUE TITLE
Wrong organization shown for workspace

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#7681]
### Description
Started a local multi user che (6.0.0-M2) with empty data area:
```
docker run -it --rm -e CHE_MULTIUSER=true -v ~/chedata_plain600m2:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.0.0-M2 init
docker run -it --rm -e CHE_MULTIUSER=true -v ~/chedata_plain600m2:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.0.0-M2 start
```

- Login as admin
- Create two organizations: one and two
- Go to “Workspaces” and press “Add”
- the "Create Workspace" form opens. **but doesn’t allow to select the organization.**  (Problem 1, might be related to #6725 )
- to  workaround that: refresh the browser page. Now the organizations are visible and can be selected
- create a workspace ws_one in organization one
- create a workspace ws_two in organization two
- now go to "Workspaces" 
- open the configuration page for workspace two/ws_two
- switch to the overview tab
- **the organization is listed as "one" here.**

**OS and version:**    
Chrome on Ubuntu VM
Che running locally in the Ubuntu VM

**Comment by dmytro-ndp** [comment]
Is actual for Che 5.22.0-SNAPSHOT as well:
![screenshot from 2017-12-01 15-50-56](https://user-images.githubusercontent.com/1197777/33485576-83a5909a-d6af-11e7-8860-9ad5b5423201.png)

@ashumilova: please, take a look at this.

**Comment by SkorikSergey** [comment]
Issue for **problem 1** - https://github.com/eclipse/che/issues/7247.
**Problem 2**: All created workspaces have the first created organization name in the workspace details.
![output-_3_](https://user-images.githubusercontent.com/7760565/33485660-df2f2da4-d6af-11e7-8428-a169f707692d.gif)

**Comment by SkorikSergey** [comment]
Not reproduced.
