### ISSUE TITLE
Multi User Che: Cannot open a workspace in a sub-organization

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#7697]
### Description

In some settings I'm not able to open a workspace in a sub-organization:

Started a local multi user che (6.0.0-M2) with empty data area:
```
docker run -it --rm -e CHE_MULTIUSER=true -v ~/chedata_plain600m2:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.0.0-M2 init
docker run -it --rm -e CHE_MULTIUSER=true -v ~/chedata_plain600m2:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.0.0-M2 start
```

- create an organization org and a sub-organization org/suborg
- create a workspace in the sub-organization
- go to "Workspaces" > "Add Workspace"  
- select the suborg as organization (if the organization dropdown doesn't show, refresh the browser).
- Create the workspace
- The workspace loads properly
- Select "Workspaces"
- The list of workspaces shows the workspace just started
- Try to open the workspace that was just created.

Bug: 
- workspace doesn't open
- "The project's workspace is currently not open" message on the screen.
- There is another "Open" button, but when using it I get the message "Workspace doesn't exist. Unable to open the IDE"

**OS and version:**    
Chrome on Ubuntu VM
Che running locally in the Ubuntu VM

**Comment by ghost** [comment]
@ChristianSchenk711 i was unable to reproduce using the latest Che6 nightly

**Comment by ChristianSchenk711** [comment]
Just retested on eclipse/che:nightly and indeed it works. 
Thanks.
