### ISSUE TITLE
Button icons disorder in `Git Show History` panel 

### ISSUE THREAD

**Issue by zhongyi-tong** [eclipse-che/che#771]
**Description of problem:** The button icons in `Git > Show History` panel show up in disorder. Suggested in the snapshot below.
**Che version:** `Version :4.0.0-RC11 Revision :31194172ac236965 Build Time :2016-03-03 20:31:58`
**Che install directory:** docker default
**Docker version:** `1.10.3, build 20f81dd`
**Java version:** 1.8
**Environment details (AWS, VirtualBox, physical, etc.):** VirtualBox
**How reproducible:** `Git > Show History`

The button height is 18px, however the icon svg is 32px.
![image](https://cloud.githubusercontent.com/assets/7262715/13951214/6f1f3752-f06a-11e5-89ad-d17263d2ffe0.png)

**Comment by ddementieva** [comment]
This is a known issue. Thanks for reporting it.

**Comment by ddementieva** [comment]
@geeeeeeeeek Can you try to reproduce this issue with latest Che version? Icons are rendered OK for me.

**Comment by ghost** [comment]
Cannot reproduce with the current master. @geeeeeeeeek Feel free to reopen if the problem is still there for you.
