### ISSUE TITLE
Improve UX to delete a command

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#7715]
Following: https://github.com/openshiftio/openshift.io/issues/1502 

We should be improving the UX to delete a command.
- The icon does not look intuitive
- We are missing a right click action on commands (to duplicate, rename, delete, move)
- We are also missing a delete button in the command editor. 
- Also please consider handling the case when "delete" on the keyboard is pressed.

**Comment by slemeur** [comment]
Also please consider handling the case when "delete" on the keyboard is pressed.

**Comment by vzhukovs** [comment]
![2018-1-24 15-39](https://user-images.githubusercontent.com/1968177/35378851-e6ced298-01bc-11e8-9534-5cb514972eff.png)

I don't know if it is a good idea to duplicate buttons, wdyt?

**Comment by ashumilova** [comment]
@slemeur do we need both context menu and delete&copy buttons?

**Comment by slemeur** [comment]
Can the contextual menu have actions for:
- rename: it will open the command if not opened, and gives the focus into the name's textfield.
- move: it will also open the command if not opened, and gives the focus on the goal dropdown.

Can we add the icons in the contextual menu?

Then:
- I think the colors for the quick actions should not be in blue - it seems overwhelming.
- The spacing between the icons also seems to be too important.

**Comment by vzhukovs** [comment]
During implementing this issue, two moments where discovered:

- [ ] Don't set up focus forcibly after editor initialization https://github.com/eclipse/che/issues/8573
- [ ] Make an ability to handle focus and key press event on CustomListBox https://github.com/eclipse/che/issues/8574

Created a PR: https://github.com/eclipse/che/pull/8581
