### ISSUE TITLE
UI issues on very wide displays

### ISSUE THREAD

**Issue by matevarga** [eclipse-che/che#7730]
### Description
Some UI components fall apart when the window size is very wide.  See attached file.
![2017-12-05 14_09_24-eclipse che _ wksp-l0md](https://user-images.githubusercontent.com/3673552/33608869-25c8e192-d9c6-11e7-810b-16154f78809f.png)

### Reproduction Steps
Open Eclipse Che on a 4K display, go to workspaces menu.

**OS and version:**    
Any browser.

**Comment by slemeur** [comment]
@olexii4 : Could you give a look please?

**Comment by skabashnyuk** [comment]
It may be related to the opposite issue https://github.com/eclipse/che/issues/6405

**Comment by olexii4** [comment]
Yes. We have UI problem with this size which damages a header of the table and the first row
![selection_045](https://user-images.githubusercontent.com/6310786/33876644-c1041f56-df2e-11e7-9247-2e2e6fa9d838.png)
