### ISSUE TITLE
Codenvy infrastructure unable to start workspace, exit code 2

### ISSUE THREAD

**Issue by ken-graham** [eclipse-che/che#7739]
### Description

Codenvy infrastructure is unable to start workspace, returning with exit code 2

The message is: Restoring of workspace workspacewyn34hk66c4uadjk filesystem terminated on node22.codenvy.io node. Synchronization process failed. Exit code 2

### Reproduction Steps

**OS and version:**    Irrelevant

All I need to do is "Start" the workspace, and it errors out.

**Diagnostics:** 

The logs I get now are no longer relevant. Instead, find below an earlier paste, indicating the error condition.

[STDOUT] Executing busybox-1.26.2-r9.trigger
[STDOUT] OK: 84 MiB in 55 packages
[STDOUT] ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
[STDOUT] v3.6.2-214-g1b7a02dada [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
[STDOUT] v3.6.2-213-g7117bcd532 [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
[STDOUT] OK: 8437 distinct packages available
[STDOUT] (1/4) Installing libattr (2.4.47-r6)
[STDOUT] (2/4) Installing libacl (2.2.52-r3)
[STDOUT] (3/4) Installing popt (1.16-r6)
[STDOUT] (4/4) Installing rsync (3.1.2-r5)
[STDOUT] Executing busybox-1.26.2-r9.trigger
[STDOUT] OK: 85 MiB in 59 packages
[STDOUT] Rsync agent installed
[STDOUT] Exec Agent binary is downloaded remotely
[STDERR] wget: unrecognized option: s
[STDERR] BusyBox v1.26.2 (2017-11-23 08:40:54 GMT) multi-call binary.
[STDERR]
[STDERR] Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
[STDERR]        [--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
[STDERR]        [-U|--user-agent AGENT] [-T SEC] URL...
[STDERR]
[STDERR] Retrieve files via HTTP or FTP
[STDERR]
[STDERR]        --spider        Spider mode - only check file existence
[STDERR]        -c              Continue retrieval of aborted transfer
[STDERR]        -q              Quiet
[STDERR]        -P DIR          Save to DIR (default .)
[STDERR]        -T SEC          Network read timeout is SEC seconds
[STDERR]        -O FILE         Save to FILE ('-' for stdout)
[STDERR]        -U STR          Use STR for User-Agent header
[STDERR]        -Y on/off       Use proxy
[STDERR] wget: unrecognized option: s
[STDERR] BusyBox v1.26.2 (2017-11-23 08:40:54 GMT) multi-call binary.
[STDERR]
[STDERR] Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
[STDERR]        [--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
[STDERR]        [-U|--user-agent AGENT] [-T SEC] URL...
[STDERR]
[STDERR] Retrieve files via HTTP or FTP
[STDERR]
[STDERR]        --spider        Spider mode - only check file existence
[STDERR]        -c              Continue retrieval of aborted transfer
[STDERR]        -q              Quiet
[STDERR]        -P DIR          Save to DIR (default .)
[STDERR]        -T SEC          Network read timeout is SEC seconds
[STDERR]        -O FILE         Save to FILE ('-' for stdout)
[STDERR]        -U STR          Use STR for User-Agent header
[STDERR]        -Y on/off       Use proxy
[STDERR] tar: can't open '/root/che/exec-agent-linux_amd64.tar.gz': No such file or directory
[STDERR] /bin/sh: /root/che/exec-agent/che-exec-agent: not found

**Comment by bmicklea** [comment]
Can you include the recipe you're using for the workspace?

**Comment by eivantsov** [comment]
It looks like installer script uses wget argument that is not supported by wget in Busybox
