### ISSUE TITLE
while upgrading eclipse che to 6.0.0-M2 pulling eclipse/che-ip:5.17.0 issue , how to resolve it

### ISSUE THREAD

**Issue by aachman** [eclipse-che/che#7740]
When running following command to upgrade the version of Eclipse-che from 5.17.0 : 
docker run -it --rm -v /root/che/:/repo -v /che-data:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.0.0-M2  upgrade.
Then it is Pulling image eclipse/che-ip:5.17.0 . How to get resolve the issue.

Thanks in advance.

**Comment by eivantsov** [comment]
@aachman utilities images aren't that important. Can you provide all output from upgrade command?
