### ISSUE TITLE
Add che-samples to CI and CD

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#7743]
### Description
We need to add samples projects to CI and release them with Che releases.
- https://github.com/che-samples/che-ide-server-extension
- https://github.com/che-samples/che-ide-extension

**Comment by riuvshin** [comment]
done
https://ci.codenvycorp.com/job/che-ide-extension-ci-master
https://ci.codenvycorp.com/job/che-ide-server-extension-ci-master/
