### ISSUE TITLE
Consolidate Workspace Config format 

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#7748]
**NOTES:** 
- content type serializing WSConfig is out of scope, we can imagine other than JSON (for instance YAML) as an alternative.
- serialization mechanism and accessibility are out of scope as well. We can imagine storing WSConfig anywhere (DB, local file etc) and keep it locally or remotely (accessible via http using URL for ex)

**Context:**
For the time we have several formats and mechanisms to start Workspace such as (Factory, Stack, Chefile) which extends WorkspaceConfiguration to add additional automation ability and semantic.
I suppose for the time being we have enough experience to formalize consolidated model of WSConfig which would add "useful" metainfo from Factory and Stack definition and so remove different evolution branches of it and in perspective retire other formats from the Che core model.

**Proposal**
It is proposed to extend it adding  two top-level objects: 
- tags (inherited from stack)
- ide (inherited from factory)

```
config: {
  name: "",
  description: "",
  defaultEnv: "",
  environments: {},
  projects: {},
  commands: {}
  tags: [],     --  from stack, things like "java", "maven", "sample" etc
  ide: {}        --  from factory, things like handlers for IDE app events etc
}
```

**Comment by gorkem** [comment]
@benoitf @l0rd FYI

**Comment by benoitf** [comment]
chefile was also handling the start of the server there were some server startup options

**Comment by l0rd** [comment]
@gazarenkov why `tags` at the root level? Shouldn't it be a `project` attribute rather than a workspace attribute?

**Comment by gazarenkov** [comment]
@l0rd copied from stacks model...
I do not have really strong opinion but It seems to me it will not make difference if we put it to project level.
Indeed, it's purpose to somehow simplify search of suitable workspace configuration to create workspace as a whole with all projects inside.
WDYT?

**Comment by garagatyi** [comment]
Addition Ide entity from the factory doesn't provide all the features of the factory to WSConfig. Does it mean that we are no longer interested in those features? 
Also, Ide entity adds some actions on IDE opening/closing and project fetching it is not clear to me for this can be used on a workspace level. Should the actions from this entity be called on each opening/reloading of the IDE page? 
Let's imagine the case when it is configured to open project manual in IDE window on project fetching or IDE opening. Is it interesting to a user when he reloads the browser page or restarts the workspace? I doubt. Because of this, I'm not sure we need this entity in WorkspaceConfig.

**Comment by skabashnyuk** [comment]
>Addition Ide entity from the factory doesn't provide all the features of the factory to WSConfig. Does it mean that we are no longer interested in those features?

Can you give a concrete example?

>Also, Ide entity adds some actions on IDE opening/closing and project

Maybe it would be a good reason to put it on project level as @l0rd  suggested. Or both. I think we need to revise it one by one.

**Comment by garagatyi** [comment]
> Can you give a concrete example?

[Authoring](https://github.com/eclipse/che/blob/master/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/factory/Author.java) WSConfig, [policies](https://github.com/eclipse/che/blob/master/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/factory/Policies.java#L18) of acceptance, [versioning](https://github.com/eclipse/che/blob/master/core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/factory/Factory.java#L26) which is useful for a config stored outside of our DB

**Comment by gazarenkov** [comment]
`Authoring WSConfig, policies of acceptance, versioning which is useful for a config stored outside of our DB
`
@garagatyi - yes, it is in our factory format but usefulness is doubtful, do you have some arguments? (well, "version" that's what we probably should consider for wsconfig indeed)

@skabashnyuk , @l0rd was talking about tags, not ide
`Let's imagine the case when it is configured to open project manual in IDE window on project fetching or IDE opening. Is it interesting to a user when he reloads the browser page or restarts the workspace? I doubt. Because of this, I'm not sure we need this entity in WorkspaceConfig.
`
Not sure I understand. If it is expected that IDE (for example) opens the same file on loading - then yes it should be the case (thats what factory does). If it is not needed (which is the case for 99%) then no actions should be configured.
No?

**Comment by benoitf** [comment]
@gazarenkov is it on purpose that it is only targeting the workspace configuration, and not all the configuration ?

Also, do we have real configuration with multiple environments ?
I think until now I've only seen in workspaces  defaultEnv with environments with an array of one element.

**Comment by gazarenkov** [comment]
@benoitf 
On the scope configuration needed for start workspace.
what do you mean by "all configuration"?

yes, we do not have multiple environments in our default assembly yet.

**Comment by garagatyi** [comment]
+1 to consider removing multiple environments. 

> yes, it is in our factory format but usefulness is doubtful, do you have some arguments? 

We have those features in factory. If we remove factory concept then either we move those features to WSConfig or declare that they are not needed anymore.

> Not sure I understand. If it is expected that IDE (for example) opens the same file on loading - then yes it should be the case (thats what factory does). If it is not needed (which is the case for 99%) then no actions should be configured.

If we remove factory object and use stored WSConfig instead than configured onOpen action IS useful on WSConfig applying, but might not be useful or even bad for UX in case applied WSConfig is used continuously.
Am I correct that this issue suggests removing factory object?

**Comment by gazarenkov** [comment]
@garagatyi 
as you can see from issue description the goal is to retire other than WSConfig formats, so the answer is "yes".
not sure i understand "but might not be useful or even bad for UX in case applied WSConfig is used continuously" but I guess it is related to your previous comment about IDE loading (if not, please specify). 
I do not think it makes a lot of differences in principle for IDE comparing to current state.
AFAIK, now IDE rewrites URL and so when you refresh browser IDE behaves differently.

**Comment by garagatyi** [comment]
@gazarenkov I meant that if we want to use WSConfig as we used factory before then the following case might happen:
1. Author of WsConfig (which is supposed to be used as a factory) configured the onOpen action that opens tutorial of a project/framework.
1. A user applies it.
1. IDE opens tutorial.
1. User likes the projects and works on it, then leave it until the following day.
1. The following day user opens WS from that WsConfig to continue his work on the project.
1. What should IDE open? Should it restore the last session as IDE does now or apply `onOpen` action or both? 
In this case, onOpen action might cause bad UX for a user. Don't get me wrong, I DO understand why having different formats complicates the product, I'm against it. But we should think about UX we will provide when we do the change.

**Comment by skabashnyuk** [comment]
@garagatyi I think you are right some combination of the parameters may look confusing from UX perspective. But I think the goal of this task is to consolidate features that look similar in single place and provide instruments for factory authors to do that way want to do. Maybe in some cases, the behavior that you wrote may be expected.   I think the solution for your use case can be additional parameters that explain how this action should behave for the first time, or all other time, or something else to adjust UX to make it reasonable.

To make it more useful let's take a look at the list of available factory actions. 

onProjectsLoaded
 - runCommand - specify the name of the command to invoke after the IDE is loaded. Specify the commands in the 
 - openFile - Open project files as a tab in the editor.

onAppLoaded
 - openWelcomePage  - Customize the content of the welcome panel when the workspace is loaded.

onAppClosed
 - warnOnClose - Opens a warning popup when the user closes the browser tab with a project that has uncommitted changes.

I think they ```onAppLoaded``` and ```onAppClosed``` are consistent if we add it to the root of workspace config. I'm thinking maybe onProjectsLoaded we should add not to the root but somewhere closer to projects.
WDYT?

**Comment by gazarenkov** [comment]
@garagatyi 
I understand your point but "original" WSConfig and WSConfig of created workspace are not the same entity and they do not have to have the same content at the end. And I would say default behavior should be not to store those scripts (if any) to the WS's WSConfig. 

BTW, IDE stores the last state of the things and normally it is expected to restore this state next time and not perform original script every time.

**Comment by benoitf** [comment]
I would say that new events are also required like when the workspace is loaded for the first time (so we can avoid some actions on next loaded) 
Also some workspace commands could be executed automatically but not by using IDE actions. (so it's workspace-centric)

**Comment by gorkem** [comment]
@gazarenkov do you think we can close this one now
