### ISSUE TITLE
centos/postgresql-96-centos7:9.6 is not running

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#7764]
Hi,

I am using Eclipse-che 5.20.0...My container centos/postgresql-96-centos7:9.6 got stopped...Here are the logs of my centos/postgresql-96-centos7:9.6 container:

docker logs 4962288dcffd
Initial call to run-postgresql...
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 1) running in data directory "/var/lib/pgsql/data/userdata"?
pg_ctl: could not start server
Examine the log output.
 stopped waiting
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 1) running in data directory "/var/lib/pgsql/data/userdata"?
pg_ctl: could not start server
Examine the log output.
 stopped waiting
Initializing Che user...
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Warning: Failed initializing the Che user and database
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
pg_ctl: server does not shut down
waiting for server to shut down............................................................... failed
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start............LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
................................... done
server started
ALTER ROLE
waiting for server to shut down.... done
server stopped
LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
Initial call to run-postgresql...
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 1) running in data directory "/var/lib/pgsql/data/userdata"?
pg_ctl: could not start server
Examine the log output.
 stopped waiting
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 1) running in data directory "/var/lib/pgsql/data/userdata"?
pg_ctl: could not start server
Examine the log output.
 stopped waiting
Initializing Che user...
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Warning: Failed initializing the Che user and database
psql: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Because of this I am unable to use Eclipse-che...How to overcome this???

**Comment by skabashnyuk** [comment]
Please answer to this mandatory question from issue template

Reproduction Steps

OS and version:

Diagnostics:

**Comment by LahariGuntha** [comment]
OS:
RHEL 7.2

We are unable to find why that postgresql is not getting started..
