### ISSUE TITLE
Synchronized update git state and project configuration

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#7765]
### Description
When user switch to another branch he expect that project also will be switched to expected branch on UI. But we have a bit different situation. When Che performs a branch switch client gets success response from git server and immediately requests project tree from the project service and in this moment we have an old value for the git branch in project configuration. In awhile, when we request project tree again, we'll get a new value of git branch in project configuration.

![git-branch-update](https://user-images.githubusercontent.com/1968177/33711563-22fc43d6-db4d-11e7-8bc5-a2e4413a722b.gif)

**Comment by vinokurig** [comment]
Is fixed by https://github.com/eclipse/che/pull/7791
