### ISSUE TITLE
Refactoring method does not work properly in certain case

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7768]
### Reproduction Steps
I've used che during dog fooding session. I opened the CodenvyEditor class and try to rename method ``setCursorToDefinedLineAndCharForVisible``. But refactoring did not complete and i had 500 error from server without clarified details in the response.
![ezgif com-video-to-gif2](https://user-images.githubusercontent.com/1640058/33716151-c2e447c6-db5d-11e7-8d44-fe8eb5ce2abb.gif)

**OS and version:**    
Che 6.0.0-M3, Chrome browser, Eclipse Che stack.
**Diagnostics:**

**Comment by mmorhun** [comment]
Seems this is quite good reprodusable on some methods in `CodenvyEditor`
