### ISSUE TITLE
Browser with IDE hang after git  hard resetting

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7773]
### Reproduction Steps
* Create a workspace based on Eclipse Che stack. Clone Che project, checkout on che6 branch.
* I've renamed method by refactoring. This changed about 20 -30 files.
* After that i applied hard resetting from the Git menu
**Wrong:** the browser is hung
**OS and version:**    Chrome browser, che6.0.0.M3

**Comment by dkulieshov** [comment]
Depends on https://github.com/eclipse/che/issues/7768
