### ISSUE TITLE
Document the base steps for extending Che IDE with a simple plugin

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#7786]
Need to document the base (minimal) steps for preparing a simple plugin for Che IDE:
- plugin project structure
- essential files
- entry point
- packaging
- adding a plugin to Che IDE

**Comment by dmytro-ndp** [comment]
We have already had the document https://www.eclipse.org/che/docs/assemblies/plugin-lifecycle/index.html with similar proposal, haven't it?

**Comment by slemeur** [comment]
@vparfonov : Please link to the epic

**Comment by vparfonov** [comment]
not actual any more
