### ISSUE TITLE
Move language description configuration out of source code

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#7790]
Right now we use `LanguageDescription` instances when we want to find which language corresponds to specific file and further which language server corresponds to mentioned file. Those `LanguageDescription` instances are configured inside `Guice` modules.

If we want to make it possible to have complete language server configuration as a part of workspace configuration, we need to find a way how we can move language description from `Guice` to workspace configuration or change the way we define a correspondence between file and language server instance.

**Comment by tsmaeder** [comment]
There are two things that link a particular resource to a language server:
1. The language description links a path name to a language id
2. A language server description maps a path name or language id to a language server launcher.

**Comment by ghost** [comment]
But in this case we don't have a launcher as it is now. Language server starts in a container as part of CMD or entrypoint instructions.

**Comment by dkulieshov** [comment]
I think the problem is likely within these lines of `org.eclipse.che.api.languageserver.registry.LanguageServerRegistryImpl`
```java
public List<Collection<InitializedLanguageServer>> getApplicableLanguageServers(String fileUri)
      throws LanguageServerException {
    String projectPath = extractProjectPath(fileUri);
    LanguageDescription language = findLanguage(fileUri);
    if (projectPath == null || language == null) {
      return Collections.emptyList();
    }
    ...
}
```
If we can't find `LanguageDescription` that corresponds to a specific file we will skip further actions and won't have any language server returned. Language descriptions are configured in Guice modules, not workspace configuration, so to use container with new language server (which we should be able to add via workspace configuration) we have to add corresponding language description (which we can't add via workspace configuration but instead we have to edit Guice classes and recompile server).
