### ISSUE TITLE
[CHE6 branch] Git color for files does not work properly 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#7792]
### Description
* When the test suite is running on the CI job, we often have failing  test 'CitColorsTest', because git color does not work properly. After performing git commit and create new file the color does not change, although the timeout in the selenium test is 10 sec
* See the attachment:

**_- git color after commit_**
![git-color-commit](https://user-images.githubusercontent.com/5408906/33771173-b7fb96bc-dc38-11e7-94fa-81335631aa79.png)

**_- git colotr after add new file_**
![git-color-newfile](https://user-images.githubusercontent.com/5408906/33771967-b5bc4c18-dc3b-11e7-84c0-1e451b181750.png)

**Che version:** 6.0.0-M3
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version: 1.30**
**Che install:** Docker container

**Additional information:**
* Related selenium test: _GitColorsTest_
* Problem can be reliably reproduced, doesn't happen randomly: [No]

**Comment by vinokurig** [comment]
Need to find a way how to reproduce `testNewFileColor` locally https://github.com/eclipse/che/issues/7856
