### ISSUE TITLE
External Libraries not available before opeining a Java File

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#7794]
In the jdt.ls branch, when you start the workspace and try to expand the external libraries node of a java project before opening the first Java file, a failure occurs.
The problem is that the Java language server is not started yet.

**Comment by tsmaeder** [comment]
@svor I remember we talked about this before my PTO, but then I guess it got lost.

**Comment by tolusha** [comment]
Done here
https://github.com/eclipse/che/issues/7836
