### ISSUE TITLE
Minishift HTTPS

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#7798]
### Description
Is there a guide to getting minishift to work with ssl/https? Currently I have everything working with http using [https://www.eclipse.org/che/docs/setup/openshift/index.html](https://www.eclipse.org/che/docs/setup/openshift/index.html).

**Comment by skabashnyuk** [comment]
https://github.com/minishift/minishift/issues/1031 hth

**Comment by ghost** [comment]
Also, we will have problems with self signed certs - Java won't like them. So, I'd say that Che is certified for https only with proper certs for OpenShift itself

**Comment by JamesDrummond** [comment]
@skabashnyuk Thanks. Great information.

@skabashnyuk @eivantsov Could Eclipse Che be made to have Java "like"/accept self-signed certificates by setting an environment variable for the Che server to allow insecure HTTPS connections globally? Not something that would be great for production but for testing it would be very nice. Also if there are issues with workspaces not connecting with HTTPS, setting this variable would be the first thing to have someone set to see if it fixes the issue. Then the user/admin would know that certs are the issue.

I would think this would be something that would take some time to implement but would be great to have. "Insecure" ssl/https connections are still more secure than http so this would be a great default for most users.

**Comment by ghost** [comment]
@JamesDrummond to enable self signed certs, they gotta be added to trust store for Java. We did that in Codenvy by the way

**Comment by JamesDrummond** [comment]
@eivantsov I added a wildcard certificate to openshift router. I wrote an article on  [https://medium.com/@james_devcomb/adding-wildcard-certificate-to-default-openshift-origin-router-77402464a782](https://medium.com/@james_devcomb/adding-wildcard-certificate-to-default-openshift-origin-router-77402464a782) . I get locked secure in my browser so I am pretty sure my certification is ok. I still am getting the same issue where api and wss calls fails with 403 status code. When I set to `CHE_INFRA_OPENSHIFT_TLS__ENABLED=false` everything works. 

ws request:
```
GET wss://che-testing123.example.com/api/websocket?token=eyJhbGciO<hide>_rw HTTP/1.1
Host: che-testing123.example.com
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: https://che-testing123.example.com
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3137.0 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cookie: a0e05d81bc223c8f66d2bb75f9083b22=9b02909b9a245012f5ead0ea602a6d76
Sec-WebSocket-Key: cL7QjQ1e<hide>+N5I9tw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```
ws response:
```
HTTP/1.1 403
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 983
Date: Tue, 13 Feb 2018 23:41:27 GMT
```

**Comment by JamesDrummond** [comment]
@eivantsov Maybe I should have asked how do I add a trust store to che?

**Comment by JamesDrummond** [comment]
@eivantsov OK I think that some updates or new features need to be added to che to make this easier for users. Openshift automatically mounts certificates at `/var/run/secrets/kubernetes.io/serviceaccount/`. However they are not in the accepted format of "ca.pem", "cert.pem", and "key.pem" for the docker implementation [https://github.com/eclipse/che/blob/master/infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerCertificates.java#L44-L46](https://github.com/eclipse/che/blob/master/infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerCertificates.java#L44-L46)  . Also for openshift the default path to find certs should be set to "/var/run/secrets/kubernetes.io/serviceaccount" from the current [https://github.com/eclipse/che/blob/master/infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerCertificates.java#L44-L46](https://github.com/eclipse/che/blob/master/infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/DockerCertificates.java#L44-L46) that contains "ca.crt" and "service-ca.crt".

I am sure this maybe low on the radar for the Che team with the big epic you guys are working on right now but I think it important to provide ssl feature for the OCP version out of the box. I see no reason for it to be non-secure with openshifts built in certificate handling. 

For now I guess I will manually add converted jks file to data directory since for my case the certificate I have set globally(wont change) and set `-Djavax.net.ssl.trustStore` and `-Djavax.net.ssl.trustStorePassword=<<generate>>`. I'll let you know how that goes.

**Comment by JamesDrummond** [comment]
I am going to close this issue so there is no confusion on where I am at with trying to get https to work with ocp.
