### ISSUE TITLE
Multiuser replace_stacks.sh

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#7801]
### Description
When using multiuser with minishift I cannot use [https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/openshift/files/scripts/replace_stacks.sh](https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/openshift/files/scripts/replace_stacks.sh) due to access error. Is there another way to replace the default stacks with the ones found at https://raw.githubusercontent.com/redhat-developer/rh-che/master/assembly/fabric8-stacks/src/main/resources/stacks.json ?

Seems like there should be another docker image altogether for openshift versus running this script.

**Comment by skabashnyuk** [comment]
Is this issue related to che6, can you check it for che6?

**Comment by JamesDrummond** [comment]
Replace stacks script is not needed in che6.
