### ISSUE TITLE
minishift get-che.sh fails with runtime.Unknown

### ISSUE THREAD

**Issue by Themodem** [eclipse-che/che#7803]
### Description
Following the instructions from [https://www.eclipse.org/che/docs/setup/openshift/index.html#deploy-che-on-minishift](https://www.eclipse.org/che/docs/setup/openshift/index.html#deploy-che-on-minishift)

Installing minishift (works fine) then running the bash files produces the following output

```bash
minishift version
minishift v1.9.0+a511b25

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-01T06:24:02Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

bash ./get-che.sh
[CHE] Checking if minishift is running...done!
[CHE] Logging on using OpenShift endpoint "https://192.168.64.3:8443/"...done!
[CHE] Checking if project "eclipse-che" exists...done!
[CHE] Switching to "eclipse-che"...done!
[CHE] Setting admin role to "che" service account...rolebinding "che" configured
[CHE] Retrieving latest version of fabric8 tenant Che template...done! (v.2.0.73)

[CHE] Deploying Che on minishift (image docker.io/eclipse/che-server:nightly)
serviceaccount "che" configured
service "che-host" configured
persistentvolumeclaim "che-data-volume" configured
persistentvolumeclaim "claim-che-workspace" configured
configmap "che" configured
error: unable to get type info from the object "*runtime.Unknown": no kind is registered for the type runtime.Unknown
```

### Reproduction Steps
```bash
minishift start

DEPLOY_SCRIPT_URL=https://raw.githubusercontent.com/eclipse/che/master/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh
curl -fsSL ${DEPLOY_SCRIPT_URL} -o ./get-che.sh
bash ./get-che.sh
```

**OSX 10.13.2 (17C88)**

**Comment by ghost** [comment]
@Themodem I wasn't able to reproduce on MiniShift 1.9 on Fedora. Can you update to MiniShift 1.10 and give it a try? I am sure this isn't a bug in deployment script since this error comes from OpenShfit itself.

**Comment by Themodem** [comment]
Hi @eivantsov, still happens on 1.10

Ill dig into the script and see which part is triggering the issue then raise the issue with the appropriate repo :)

Thanks for the help

**Comment by ghost** [comment]
@Themodem as far as I can see, it happens on `oc apply` at the following stage: `deploymentconfig "che" created`

**Comment by Themodem** [comment]
@eivantsov found the issue :)

`get-che.sh: 425` pulls a yml file from maven.

This file has invalid api versions

`apps.openshift.io/v1`

```yml
    che-keycloak-client-id: openshiftio-public
    che-wsagent-ping-success-threshold: "2"
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
```

`sed "s/apps.openshift.io\///" | \` fixes the issue.

Ill open a PR with a fix

**Comment by l0rd** [comment]
@Themodem you probably have this issue because you are using an old version of `oc` (your are not using the one bundled with minishift 1.10).
