### ISSUE TITLE
Make displaying of vcs head name in project explorer configurable

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#7809]
### Description
There is a proposal to make a displaying of vcs head name in project explorer configurable via preferences and hidden by default.

![eclipse che 2017-12-11 12-15-13](https://user-images.githubusercontent.com/1968177/33826257-0a88e962-de6d-11e7-81e5-f5b8c739032a.png)

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
