### ISSUE TITLE
Dashboard has to handle properly the supported types of environments

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#7811]
As the result of this [issue](https://github.com/eclipse/che/issues/7530) - the dashboard client will know the list of supported environment types, and  should handle them properly. 
 - [ ] The stack creation should propose end user to choose the type of recipe (examples: openshift, compose, dockerfile, dockerimage)
- [ ] The user should be notified when there is workspace with unsupported environment type before start.
- [ ] All recipe validations should be based on the types of the environments, that are currently supported.
- [ ] A bunch of tests should be added to validate the recipe validation.

**Comment by gazarenkov** [comment]
@ashumilova do we have recipe validation on client side?

**Comment by ashumilova** [comment]
yes, now for dockerfile, compose format and partly for openshift.

**Comment by gazarenkov** [comment]
Why?
I suppose it is implementation specific thing where we have SPI implemented exactly on server side.
Propose to remove it from UD.
If it is about language validation - better to spend time on using/writing some LS which can be reused then

**Comment by ashumilova** [comment]
It's about detecting format by key words and primitive validation of the known items of the recipe, that are interested for the client.

**Comment by slemeur** [comment]
@ashumilova : Do you confirm, the goal of the issue, is to notify the user that certain type of recipes are not compatible. 

Example:
- The current OpenShift implementation of the SPI does not support `dockerfile` as recipe type. So you would display a message to the user, if he tries to create a workspace with a runtime definition relying on a `dockerfile`.

**Comment by ashumilova** [comment]
The main goals of the issue - notify about unsupported type and provide ability to define recipes of supported types - now it's hard coded when we define stack from recipe.
