### ISSUE TITLE
Create test user at start of selenium tests execution on Eclipse Che Multi User

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#7816]
### Description
We need to have an ability to create test user of _Eclipse Che Multi User_ and to setup _Keycloak_ server automatically at the start of execution of selenium tests. Now creation of test user is done by build script on CI and it's hard to support it at the number of jobs. Also, test user is usually being created manually through the _Keycloak Web admin console_ when someone is starting selenium tests locally.

**OS and version:**    
Eclipse Che Multi User 6.x.

**Comment by mshaposhnik** [comment]
Please, don't forget OAuth scopes: `repo,user,write:public_key`
