### ISSUE TITLE
Consider a way to warn users about outdated che.env file entries configured by a user

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7827]
### Description
Since we do a lot of changes in Che it happens that some environment variables in `che.env` file get outdated and doesn't work anymore. A user doesn't know about such changes, so he may be confused that something stopped to work. Sometimes it is tricky to even realize that some setting stopped to work.
To provide better UX we may add some mechanism that warns a user about outdates settings and provide a link to a doc where the change is described. 
A possible solution is to have a file that contains outdated env var keys and message to the user if this env var is found. Then developer that shines down a setting adds an entry to this file and points to a PR or other resource with a description why env var is outdated and how to migrate.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@eivantsov @gazarenkov @skabashnyuk @gorkem @riuvshin WDYT?

**Comment by skabashnyuk** [comment]
That looks like a building a framework to make detailed warning message on tomcat startup telling that some property is outdated and it can be cleaned out. I would not say we should not do that, but it's probably not a big priority. And I doubt that everybody will correctly track removing some properties.

**Comment by benoitf** [comment]
there was a discussion at https://github.com/eclipse/che/issues/4190

**Comment by gazarenkov** [comment]
@garagatyi I do not think we need some sort of tools here. You can start with making comparison table Che5 vs Che6 properties set (with description of each) and then reflect it in docs/release notes.

**Comment by eivantsov** [comment]
Closing since the issue seems to be irrelevant
