### ISSUE TITLE
Can we have a prettier image name for Che pod on OCP?

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7828]
### Description
We have a random name for Che pod image on OCP whereas other containers are created from images with pretty names. It is hard to figure out what Che container from `docker ps` output does.
![image](https://user-images.githubusercontent.com/1851863/33850443-973bd08c-debc-11e7-9d0b-42e2eab01eab.png)
Probably it is related to image streams feature, so I'm not sure whether we can improve that.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@riuvshin can you take a look?

**Comment by riuvshin** [comment]
just checked on my side I have pretty name:
<img width="1680" alt="screen shot 2017-12-22 at 5 48 12 pm" src="https://user-images.githubusercontent.com/1636732/34304001-8d158ff8-e740-11e7-82a2-5d16fbbd204d.png">
