### ISSUE TITLE
Add status for machines in workspace runtime

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#7834]
### Description
 

Add status for each machine in workspace runtime section.

![workspace runtime](https://user-images.githubusercontent.com/1655894/33877792-2128343c-df32-11e7-8e2b-52e2f8a2826a.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by gazarenkov** [comment]
Ok for me but specify what exactly statuses.

(removed severity label since it is applicable for bugs only)

**Comment by vitaliy-guliy** [comment]
For now it's needed for properly displaying statuses of machines when we open the IDE.
To display statuses of machines client listens `machine/statusChanged` events. But sometimes client become loaded when workspace is starting and some `statusChanged` events already sent. Here we need to know somehow the status of machines.
