### ISSUE TITLE
Accidentally delected a project. Could you please recover it?

### ISSUE THREAD

**Issue by arunkumar413** [eclipse-che/che#7845]
### Description
I accidentally deleted a project on codevny. Unfortunately I didn't back it up on github. Could you please help me recover the project. Here are the details of the project.

Project name: EDA
Workspace: EDA
username: arunkumar413
Deleted time: 2.45 PM Indian Standard Time (IST)

**Comment by skabashnyuk** [comment]
@arunkumar413 don't promise, but we'll take a look.

**Comment by skryzhny** [comment]
We have backup for one day old state, do you interested in it?
@arunkumar413 if yes please contact me from email you're used to register you codenvy account.

**Comment by arunkumar413** [comment]
@skryzhny 

Yes, please back it up.

**Comment by arunkumar413** [comment]
@skryzhny I sent an email to your email id mentioned on your github profile

**Comment by arunkumar413** [comment]
@skryzhny 

Thanks.  You may close this ticket

**Comment by Parul1201** [comment]
Hi All, the same thing happened with me today, suddenly all java files got closed and was not able to see src folder. I somehow managed to get my src/main/java and src/test/java folders but there no files it. In refactoring history can see : delete original element src
Can anyone of you please help me, its of utmost importance as dont have back up on scm also
