### ISSUE TITLE
Error when creating new workspace

### ISSUE THREAD

**Issue by 454824** [eclipse-che/che#7849]
### Description
There is a JavaScript error when creating a new work space in che.  This issue was not present in 5.21.0 and first appeared in 5.21.1 and is still present in the latest nightly build as of 12/12/2017.

Server is started as:
docker run -it --rm -e CHE_MULTIUSER=true -e CHE_HOST=11.25.21.220 -e CHE_PORT=8081 -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-nightly:/data eclipse/che:nightly restart --skip:graceful

### Reproduction Steps
http://11.25.21.220:8081/dashboard/#/create-workspace

![image](https://user-images.githubusercontent.com/26026003/33909335-92227f10-df48-11e7-846b-f709645f63c8.png)

![image](https://user-images.githubusercontent.com/26026003/33909366-a8a8b632-df48-11e7-9fad-3fe8760099be.png)

Click, "Ok"

The page is blank:

![image](https://user-images.githubusercontent.com/26026003/33909495-15f7668e-df49-11e7-8695-5c04fdb89924.png)

**OS and version:**    
NAME="SLES"
VERSION="12-SP1"
VERSION_ID="12.1"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"

**Diagnostics:** 
[catalina.log](https://github.com/eclipse/che/files/1553414/catalina.log)

**Comment by ghost** [comment]
@454824 the error says that your browser cannot connect to a workspace agent. But Che server was able to do so.

This might be a blocked port issue. Can you make sure that the ephemeral port range is not filtered for you?

**Comment by 454824** [comment]
Duplicating these steps on a server on my home network resulted in no error and the successful creation of a workspace.  I didn't anticipate ports being blocked over the course of a couple of hours and the only thing that I had seen that had changed was the software version.  My apologies and thank you for your time.  A follow-up question: when you refer to "the ephemeral port range"  are you referring to the port range 32768 to 61000 (typical Linux kernel range)?

**Comment by ghost** [comment]
@454824 yes, correct - the typical linux kernel range
