### ISSUE TITLE
Eclipse Xtend

### ISSUE THREAD

**Issue by sirolf2009** [eclipse-che/che#785]
I would like to be able to use Xtend in Che.
Maven can already do all the compiliing work, but the editor needs code completion and syntax highlighting

**Comment by TylerJewell** [comment]
@svenefftinge - can you comment on the effort involved to deliver on this now that we have xtext within Che?  Once the language server protocol is fully released, what additional items would be needed?

**Comment by TylerJewell** [comment]
As this can now be done as part of the language server protocol, we will leave this open to the community to provide an extend language server.
