### ISSUE TITLE
Switch IDE LSP stuff to use URIs instead of paths

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#7852]
Currently, language server related services use workspace paths (e.g. "/asdf/src/main/java/Foo.Java") instead of URIs like in LSP proper. We are converting those paths to file URI's for use by language servers (e.g. "file://projects/asdf/src/main/Foo.java"). 
This does not work anymore once we have URI's that represent stuff that is not in the workspace, for example the the class "java.lang.Object". An editor for that class will likely display attached source from a jar in a JDK installation. Currently, stuff like hover documentation, etc. will fail in such an editor, because we cannot convert the path to a file URI.
My proposal is to use URIs instead of paths in all LSP related communication between IDE and workspace agent. There are really only two cases to be covered: if the IDE has a workspace path in hand, we prefix it with "chewksp://" to mark it as a che workspace path. In all other cases, we should be dealing with a URI that has been passed to us by a language server, and we pass it on unchanged.

**Comment by garagatyi** [comment]
@tsmaeder can you elaborate on why `chewksp://` is needed whereas we can use `file://projects`?

**Comment by tsmaeder** [comment]
@garagatyi becausae the IDE does not know where the projects are mounted in the workspace.

**Comment by tsmaeder** [comment]
To be more precise, we get paths from the workspace resource API, which we can't really convert to file uri's in the IDE:

**Comment by tsmaeder** [comment]
The simplest approach is to use paths for che workspace resources and to use uri's for everything else. LSP services in WS agent check for starting "/" to transform che paths to file uri's. All other uris are passed onto LSPs unchanged.

**Comment by dkulieshov** [comment]
@tsmaeder Do you have any plans on making a unified way of addressing resources or is this the final version? I mean using single identification mechanism for all kind of resources looks more attractive to me rather than having two different approaches. A good option that you've mentioned earlier is to use URI, why it should be difficult, can you please share your opinion?

Not directly related to this issue but ideally we could extend your suggestion and unify even more: did you consider using URIs (or something similar) both on server and client sides? 

@benoitf FYI

**Comment by tsmaeder** [comment]
@dkuleshov I think using URIs instead of paths makes sense everywhere (see the "chwksp://..." idea above). However, that is not necessary for making our jdt.ls stuff work and is not addressed here.
We are getting che file paths from the che resource API. Converting them to a uri in the ide and than back to a path immediately in the WS agent does not add any value in my opinion. If we want to go down that route, we should convert the resource API to use URI's.
