### ISSUE TITLE
JavaScript endpoint for Editor API 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#7853]
### Description
We need to provide ability for JavaScript Plugins.
For start we need to only basic functionality like get document, cursor position and etc. This should work for any editor not dependence will we switch to Monaco or not

**Comment by benoitf** [comment]
for the first item (syntax coloring) if thee is switch to monaco it will make use of https://microsoft.github.io/monaco-editor/monarch.html configuration

I would say that new plugins will be more interested at first with item number 3. which is (get active editor/open new editor)

The customize of editor rules and annotations may be changed with the switch to monaco.

**Comment by vparfonov** [comment]
Yep @benoitf you are right, we think about that and want to make API close to Monaco

**Comment by vparfonov** [comment]
Closed according to the new priorities
