### ISSUE TITLE
Provide revision number in assembly Che artifact

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7854]
### Description
There is a use case for custom assembly when it needs revision number of Che artifact. See the following discussion: https://github.com/redhat-developer/rh-che/pull/465#discussion_r154952666.
For Che 5, it uses revision number from [BuildInfo](https://github.com/eclipse/che/blob/master/assembly/assembly-ide-war/pom.xml#L403:153), but it is not included into war in Che6.

It is needed to include somewhere revision number. It can be part of a war archive or all of them. It can be done with `maven-war-plugin` by adding the following configuration
```
<plugin>
    <artifactId>maven-war-plugin</artifactId>
    <configuration>
        <archive>
            <manifest>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
            </manifest>
        </archive>
    </configuration>
</plugin>
```

**Comment by skabashnyuk** [comment]
It's already there 
https://github.com/eclipse/che-parent/blob/master/pom.xml#L1145
```
Manifest-Version: 1.0
Date: 13.12.17 10:02
Implementation-Title: Che Workspace Agent War Packaging
Implementation-Version: 6.0.0-M3-SNAPSHOT
Built-By: sj
Specification-Vendor: Red Hat, Inc.
Implementation-Vendor-Id: org.eclipse.che
Specification-Title: Che Workspace Agent War Packaging
SCM-URL: scm:git:git@github.com:eclipse/che.git/che-assembly-parent/as
 sembly-wsagent-war
Implementation-Vendor: Red Hat, Inc.
SCM-Revision: 9acc1b8768358ab1b52885f427e47d4070de78e2
Created-By: Apache Maven 3.5.2
Build-Jdk: 1.8.0_152
Implementation-URL: https://codenvy.com/maven-depmgt-pom/che-parent/ch
 e-assembly-parent/assembly-wsagent-war
Specification-Version: 6.0


```
