### ISSUE TITLE
New files can be not colored in yellow in Git projects

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#7856]
### Description
 
Sometimes selenium test `GitColorsTest` fails on CI when the test creates a new file and expects to see it colored in yellow, but the file doesn't change color.

### Reproduction Steps

It is not reproduced locally, so need to find a way haw to reproduce it locally. 

**OS and version:**    
6.0.0-M3
**Related selenium test:** _GitColorsTest_
**Diagnostics:**

**Comment by tolusha** [comment]
It is recommended to stress the system to reproduce the issue
```
for ((; ; )) do dd if=/dev/zero of=./tmp.tmp bs=4k iflag=fullblock,count_bytes count=10G; done
```
