### ISSUE TITLE
Suggestions for improved global search

### ISSUE THREAD

**Issue by hkolvenbach** [eclipse-che/che#7858]
### Description
Open for discussion, before I actually start implementing anything.

For me, one of the "killer" features of VSCode is its global search (including and excluding specific folders and giving a list of files with snippets). I think if we implement a similar, easy to use search in Eclipse Che it would enhance the usability significantly.
![image](https://user-images.githubusercontent.com/26924052/33934891-73a27dc6-dffa-11e7-955b-bc28f5949727.png)

I think https://github.com/eclipse/che/issues/5174 already helped a lot, but there are a few things that could be improved:
- [x] pressing enter in seach dialog should start search directly (right now you need to click or tab to the search button) see https://github.com/eclipse/che/pull/8101
![image](https://user-images.githubusercontent.com/26924052/33934532-714d1ece-dff9-11e7-99d6-0330155ac485.png)
- [ ] offering the search panel next to the file explorer (like VSCode), because searching is one of the most important features of an IDE. I had a hard time finding `Edit -> Find` the first time trying to search. even though `ctrl+shift+F` sounds like common sense in retrospect, I wouldn't assume that new users will get it on first try

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
About Enter key you read my mind https://github.com/eclipse/che/issues/7863

**Comment by gazarenkov** [comment]
Like it, full text search is extremely useful feature, it should be easily accessible
