### ISSUE TITLE
ssh installer enabled by default when adding a new machine

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7865]
Steps to reproduce:

1. Create a multi machine workspace.
2. In User Dashboard, go to machines, add machine.
3. Check workspaces config
4. A new machine is added with ssh installer.

On  OpenShift this causes workspace start failure as ssh installer does not have sudo.

This installer should not be added by default. All we need in a new machien by default is exec agent and terminal.

**Comment by gazarenkov** [comment]
Do we need adding anything by default at all?

I have impression that everyone around **thinks** that Che does not work w/o installers which is not true and such a behavior of UD helps ppl to **think so**.

WDYT?

**Comment by ghost** [comment]
Probably a terminal is enough

**Comment by olexii4** [comment]
Fixed in  https://github.com/eclipse/che/pull/7838
https://github.com/eclipse/che/pull/7838/commits/4a17686b51d449fa8b7d43eecf6c1028e336509e
