### ISSUE TITLE
Unable to access eclipse/che instance from another machine through proxy

### ISSUE THREAD

**Issue by sahejsingh** [eclipse-che/che#7868]
### Description
Unable to access eclipse/che instance from another machine through proxy

**Machine 1**
IP - 10.187.33.1
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/che:/data eclipse/che:5.20.1 start --fast`

Eclipse Che is accessible from localhost:8080

**Machine 2**
In Browser, access che on http://10.187.33.1:8080

**Issue**
Dashboard shows up, but unable to bring up any workspace.

Chrome Devtools -> Network Requests -> you will see there is a 
GET http://localhost:8080/api
which is wrong.

localhost should be replaced with the IP address.

**OS and version:**    
Docker for Mac - 17.09.1-ce

Got the same result with latest version (5.21.1) as well.

**Later**
I tried the same by changing the following env vars:
CHE_HOST=10.187.33.1
CHE_API=http://10.187.33.1:${SERVER_PORT}/wsmaster/api
CHE_DOCKER_IP=10.187.33.1
CHE_DOCKER_IP_EXTERNAL=10.187.33.1
CHE_SINGLE_PORT=false

And 
**Added the following configuration in NGINX**

```
http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/access.log  main;
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       8000;
        server_name  localhost;

        location / {
            proxy_pass http://10.187.33.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
}
```

**Expected result**
Once this is working, I want to ultimately put in NGINX proxy in front of it, so that all the communication goes through the proxy.

**Comment by slemeur** [comment]
@eivantsov Can you please provide guidance to @sahejsingh ?

**Comment by skabashnyuk** [comment]
@sahejsingh Do you have http proxy and want's Eclipse Che to work behind this http proxy?

**Comment by slemeur** [comment]
@skabashnyuk : Yes that is what @sahejsingh is explaining.

**Comment by ghost** [comment]
@sahejsingh after you have set CHE_HOST to an IP, what connection do you see in browser console? Still localhost?

By the way, request to master APIs are ok to go to localhost as long as it's available for you

**Comment by skabashnyuk** [comment]
@slemeur I'm not sure that @sahejsingh followed this tutorial https://www.eclipse.org/che/docs/setup/getting-started/#proxy-installation. That is why I'm asking about is this http proxy scenario or not.

**Comment by sahejsingh** [comment]
Here is what I am trying to do is setup nginx reverse proxy. (sorry if it was not clear earlier).
Machine 1 (browser) -> Machine 2 (nginx proxy) -> machine 3 (eclipse che).

The key point is
nginx proxy is on a different machine than eclipse che.

**Comment by ghost** [comment]
Yeah, no proxy involved.

@sahejsingh you ignored my question though :)

I'd try setting CHE_DOCKER_IP_EXTERNAL to nginx IP. However, you need a rule for the ephemeral port range since when a workspace is started, the client connects to it on one of the ports from the ephemeral range.

Can you also share a screenshot with chrome dev console on - network tab - when a workspace cannot be accessed?

Please, try describing the issue you have in detail, otherwise this thread won't be helpful for you and others too.

**Comment by sahejsingh** [comment]
> However, you need a rule for the ephemeral port range since when a workspace is started, the client connects to it on one of the ports from the ephemeral range.

Can you please provide an example of this?

**Comment by sahejsingh** [comment]
Shown below is what I get when I click on the workspace link on the left side-bar.

<img width="1974" alt="screen shot 2017-12-18 at 4 35 57 pm" src="https://user-images.githubusercontent.com/31713463/34091445-c31f21b8-e411-11e7-8cd9-bb8e8bb3d47f.png">

**machine1 and machine2 are same in the image above.**

Screenshot with
CHE_HOST=machine-3-ip
CHE_DOCKER_IP=machine-3-ip
CHE_DOCKER_IP_EXTERNAL=machine-3-ip and also same for nginx-machine-ip

**Comment by sahejsingh** [comment]
Another comment:
When accessing from machine 1, I dont see browser making any connection attempts to machine 3 on ephemeral port range.

**Comment by ghost** [comment]
@sahejsingh i got lost in your actual configuration. 

When a workspace is being loaded, you should see requests to project and project-type api.

**Comment by ghost** [comment]
Also, please share server logs - `docker logs -f che`

**Comment by sahejsingh** [comment]
> @sahejsingh i got lost in your actual configuration.

Not, sure what you mean. There is no special config. 

Here is my simple setup...
>Machine 1 (browser) -> Machine 2 (nginx proxy) -> machine 3 (eclipse che).

The idea is **Machine-2** could be a well defined endpoint (in the internal nw) and should be able to distribute this to various teams who want to use che. 

Do you think che supports this?

> When a workspace is being loaded, you should see requests to project and project-type api.

Are you seeing the api calls in the screenshot I posted?

> Also, please share server logs - docker logs -f che

@eivantsov I don't have access to logs at the moment, I will try to get them tomorrow.  But, I remember looking at the logs and didn't see any error there. Are you looking for something in particular?

>  However, you need a rule for the ephemeral port range since when a workspace is started, the client connects to it on one of the ports from the ephemeral range.


Again, can you please post an example of  **eclipse/che + nginx reverse proxy config** that handles the ephemeral ports. Will this even work? 

Or am I am better off waiting for openshift support (without needing to provide pods with privileged=true)

**Comment by ghost** [comment]
Have you exported all three?

```
CHE_HOST=machine-3-ip
CHE_DOCKER_IP=machine-3-ip
CHE_DOCKER_IP_EXTERNAL=machine-3-ip and also same for nginx-machine-ip
```

No, I don't see requests to project api in your screenshot. 
And I do need server logs.

**Comment by sahejsingh** [comment]
[che-same.log](https://github.com/eclipse/che/files/1569945/che-same.log)
[che-cli-same.log](https://github.com/eclipse/che/files/1569946/che-cli-same.log)

PFA che and che-cli logs.

The command to start che was...

**On Machine-3**
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/che:/data -e CHE_HOST=10.187.33.1  -e CHE_DOCKER_IP=10.187.33.1 -e CHE_DOCKER_IP_EXTERNAL=10.187.33.1  eclipse/che:5.21.1 start --fast`

**On Machine 2**
nginx proxy is running with config mentioned above. Server is listening on 8080.
browser is accessing the proxy via localhost:8080

**Result**
Able to create a workspace, but not able to access/start the workspace.

See screenshot
<img width="1933" alt="screen shot 2017-12-19 at 12 26 21 pm" src="https://user-images.githubusercontent.com/31713463/34136013-f3b5abca-e4b7-11e7-84dc-94c4f3147f13.png">

**Comment by ghost** [comment]
OK, server is able to start a workspace, according to the logs. Any errors in Console tab?

The thing is that the browser should connect to `10.187.33.1` to the container where the workspace agent is running. And the port will be a random one.

**Comment by sahejsingh** [comment]
> The thing is that the browser should connect to 10.187.33.1 to the container where the workspace agent is running. And the port will be a random one.

Does that mean we cannot have reverse proxy in front?

**Comment by ghost** [comment]
@sahejsingh I think you can. But running Che server on a Mac in such configuration looks a bit unusual. Also, can you explain why you need nginx in front?

**Comment by sahejsingh** [comment]
>can you explain why you need nginx in front?
Because I want to share URL of a che instance and the following attempts didn't work...

1. Installing CHE in openshift requires privileged containers (che version 5.x).   The openshift cluster we have does not allow privileged containers.
2. CHE in minishift (on a standalone machine) didn't work because xip/nip io domains were not working. But as I write this, I see that I am able to access these domains now. Might give one more try to this with the latest 5.x image.

That leaves me with one option. Run CHE standalone on a single machine, but since I didn't want to share an ip address to anyone who wanted to use it, I thought lets put nginx proxy (running in openshift) in front of che. I can share a url to a service running in openshift and internally that traffic is routed to a machine running che. This issue is an attempt to get this use case working. But I see nginx needs to listen and forward traffic coming on these ephemeral ports. I have counted 5 to 7 ports per workspace. I could make it work but that is not very flexible/usable.

Ultimately, che running in openshift is what would work the best. But since that path seems to be blocked, for now, hence all these complicated attempts to get che working in a standalone environment.

**Comment by ghost** [comment]
> Installing CHE in openshift requires privileged containers (che version 5.x). The openshift cluster we have does not allow privileged containers.

Why is that? Installing Che on OpenShift requires a running OpenShift instance and that's it.

**Comment by eivantsov** [comment]
Closed due to inactivity. Reopen or create a new issue if you have got a particular problem to solve.
