### ISSUE TITLE
Git branches filter doesn't work after click on the dropdown filter.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#7872]
### Description
Git branches filter doesn't work after click on the dropdown filter.

### Reproduction Steps
1, Clone some project. 
2. Click Git -> Branches... 
3. Begin type some existed branch name to activate branch filter.
4. Click on the branch dropdown filter (with items "All", "Local", "Remote").
5. Try to type some new symbols.
Expected: After click on the "dropdown filter" branch name typing should work too. We should bring back focus to the branch list panel. 
Actual result: typing new symbols for branch name doesn't work. But if you click on the branch list focus come back to the branch list and filter typing works again. 

**OS and version:**    
Fedora 25
**Diagnostics:** 
CHE version:

**Comment by AndrienkoAleksandr** [comment]
P.S. We should think about one more test case. When I type some inexistent branch I will get window with empty branch table. When I click on this empty branch panel, branch filter lose focus too. And I can not remove previous typed text. Yes it begin work again if I clicked on the filter icon, but I think it's not obviosly. Maybe keydown handler should be moved from branch list table to the branch list panel.

**Comment by vinokurig** [comment]
We can not bring back the focus to the branch list panel on drop-down list is opened because it will close the drop-down immediately.  
To handle drop down close without selecting an item in it, we need to add a handler to list-box element that will be fired on list closed event. Then return focus to the filter element in the event.

**Comment by vinokurig** [comment]
Probably wrapping all widgets to a `FocusPanel` will solve this problem
