### ISSUE TITLE
Support for Openshift Origin?

### ISSUE THREAD

**Issue by diogosaad** [eclipse-che/che#7878]
### Description
The current setup process for Openshift (https://www.eclipse.org/che/docs/setup/openshift/index.html) mentions deployment compatibility to  Minishift and OCP. However nothing is mentioned about Openshift Origin. Is it afterall compatible with Origin? If not, any plans?

Basically I´m looking for a scalable topology where I don´t need to spend on Licenses.

**Comment by ghost** [comment]
@diogosaad I do not see any reasons why it should not work with origin. Have you tried it by the way? Basically, Minishift is a VM with Origin that runs in there.

**Comment by diogosaad** [comment]
No I have not tried. I'm basically relying on the documentation provided.

I'm willing to try, should I follow the same steps as described for OCP?


On Dec 14, 2017 7:46 PM, "Eugene Ivantsov" <notifications@github.com> wrote:

@diogosaad <https://github.com/diogosaad> I do not see any reasons why it
should not work with origin. Have you tried it by the way? Basically,
Minishift is a VM with Origin that runs in there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/che/issues/7878#issuecomment-351800556>, or mute
the thread

**Comment by ghost** [comment]
@diogosaad yes, correct. Please do let us know about the outcomes. Once you have it up and running I will update docs.

**Comment by eivantsov** [comment]
Closing the issues, as MiniShift runs Origin and Che can be successfully deployed.
