### ISSUE TITLE
Git amend is disabled without commit message

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7880]
### Description
In git commit dialog there is a flag that allows amending changes to the previous commit. 
But in case user didn't provide message button that does commit is disabled. This is supported by git and very common approach, so it would be useful to allow such a flow.  
![selection_008](https://user-images.githubusercontent.com/1851863/33991433-3f2d5682-e0d7-11e7-93da-62e78541fc6a.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by vinokurig** [comment]
Applying of this check-box sets the latest commit message to the message text-box (just like native git does). It looks like it takes some time  to get the Git log and the message part is empty during the request. We need to call the log request with `maxCount` parameter. And may be it will be suitable to show a loader during the Log request.
