### ISSUE TITLE
Add Github identity provider automatically into the Keycloak server in time of launching of Eclipse Che Multi User

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#7899]
### Description
It may be useful to add _Github identity provider_ automatically into the _Keycloak_ server in time of launching of _Eclipse Che Multi User_ to compensate removal of support of `CHE_OAUTH_GITHUB_CLIENTID` and `CHE_OAUTH_GITHUB_CLIENTSECRET` variables as part of issue https://github.com/eclipse/che/issues/5943. 
Command to add github provider through the [Keycloak's _Admin CLI_](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.1/html/server_administration_guide/admin_cli#identity_providers_operations):
```
kcadm.sh create identity-provider/instances -r che -s alias=github -s providerId=github -s enabled=true -s storeToken=true -s addReadTokenRoleOnCreate=true -s 'config.useJwksUrl="true"' -s config.clientId=<GITHUB_CLIENTID> -s config.clientSecret=<GITHUB_CLIENTSECRET> -s 'config.defaultScope="repo,user,write:public_key"' --no-config --server http://localhost:8080/auth --user <admin's name> --password <admin's password> --realm master
```
Created provider can be observed in the _Keycloak Administration Console_:
![screenshot from 2017-12-11 19-15-15](https://user-images.githubusercontent.com/1197777/33843993-a8e868b4-dea7-11e7-9a37-4835988344d5.png)

#### Authorization callback URL
1) For multiuser Eclipse Che: 
> http://<CHE_SERVER_IP>:5050/auth/realms/che/broker/github/endpoint
2) For single user Eclipse Che:
> http://<CHE_SERVER_IP>:8080/api/oauth/callback

**OS and version:**    
Eclipse Che 6.x

**Comment by riuvshin** [comment]
added 4 types of client id/secret pairs for each qa-slave:
- che single user docker
- che multi user docker
- che single user ocp
- che multi user ocp

**Comment by riuvshin** [comment]
Done. after some discussion we come to conclusion that we should not put that 
```
kcadm.sh create identity-provider/instances -r che -s alias=github -s providerId=github -s enabled=true -s storeToken=true -s addReadTokenRoleOnCreate=true -s 'config.useJwksUrl="true"' -s config.clientId=<GITHUB_CLIENTID> -s config.clientSecret=<GITHUB_CLIENTSECRET> -s 'config.defaultScope="repo,user,write:public_key"' --no-config --server http://localhost:8080/auth --user <admin's name> --password <admin's password> --realm master
```
to any deploy script but add this to CHE docs

**Comment by riuvshin** [comment]
@patlachance in docs we describe how to configure it manually with KC Admin panel.
if you are looking for KC CLI docs Eclipse CHE docs site is the wrong place to look at you better check  KC docs http://www.keycloak.org/docs/3.3/server_admin/topics/admin-cli.html

**Comment by riuvshin** [comment]
I think we can add this, @eivantsov WDYT?

**Comment by eivantsov** [comment]
@riuvshin but we need GitHub app with the right redirect URL. Yes, we can add a provider with dummy data but it is helpful at all?

**Comment by riuvshin** [comment]
I mean should we have just an example of how to do the same but using CLI ?

**Comment by eivantsov** [comment]
Yeah, that makes sense. Will do

**Comment by patlachance** [comment]
@riuvshin yes, exactly!
@eivantsov thanks
