### ISSUE TITLE
Machine is absent in workspace runtime after receiving an event that machine become starting

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#7900]
### Description
 

Client subscribes on `machine/statusChanged` events and listens changing states of machines.
After machine status has been changed to STARTING client must send internal `MachineStartingEvent`.
But before sending the event IDE updates the workspace by sending GET request to `/api/workspace`.
As it turns out the workspace runtime doesn't contain machine which status has changed to STARTING and it appears in the runtime after few seconds.
This leads to internal `MachineStartingEvent` is not sent and IDE does not react on changing of the machine state.

**Comment by garagatyi** [comment]
We found that runtime state doesn't have machine object when an event that the machine is starting is received by a client. So we need to rework this part on the server-side to provide more consistent behavior.
