### ISSUE TITLE
[CHE6-OCP] Investigate reason of failing tests to regenerate and upload SSH key on GitHub when running on CI job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#7901]
### Description
* There are some tests where performing generate and upload ssh key on GitHub by UI form. When the tests run on CI job (slave qa-builder) on the ocp platform they fail in this case
* Need to find the reason of it and fix up

**See the attachment:**
![generate-upload-ssh-key](https://user-images.githubusercontent.com/5408906/34048286-d4d9ebca-e1bb-11e7-9c9f-1eb0d919086b.png)

**Che version:** 6.0.0-M4
**CI job slave:** qa-builder
**Che install:** OCP  
 
**Additional information:**
* Related selenium test: _ImportProjectIntoSpecifiedBranchTest_, _ImportRecursiveSubmoduleTest_, 
_PullRequestPluginTest_, _PullRequestPluginWithForkTest_, _KeepDirectoryGitImportTest_

**Comment by riuvshin** [comment]
fixed wrong resolv.conf on pr-builder slave
