### ISSUE TITLE
No instructions to deploy Che6 to minishift

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#7905]
There are no working instructions that I can see for deploying Che6 to OpenShift. The current scripts for deploying to minishift does not work. Also I do not think [the minishift add-on](https://github.com/minishift/minishift-addons/tree/master/add-ons/che) works for che-6. 

@gazarenkov minishift deployment through add-on is a release criteria

**Comment by ghost** [comment]
@gorkem I haven't pushed my docs branch yet. You can use this script https://github.com/eclipse/che/blob/che6/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh

**Comment by gorkem** [comment]
@eivantsov can you point me to the branch

**Comment by gazarenkov** [comment]
@gorkem yes, it is condition of release and the goal with Jan'18 deadline, as we discussed on Nov 30 (when we estimate the date of Che6), we rely on @l0rd for this instruction (do not mind if it is @eivantsov who do that :) ).

**Comment by gorkem** [comment]
Yeah we need to get this organized. I think not doing che6 on master is not doing us any favors at this point either

**Comment by gazarenkov** [comment]
Yes, we should not wait for it to move Che6 on master I believe, it is needed for release.

**Comment by skabashnyuk** [comment]
https://www.eclipse.org/che/docs/6/che/docs/openshift-single-user.html#minishift
