### ISSUE TITLE
colored console output looks weird

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#7910]
### Description
When  a command produces a colored output the console just looks weird. Che console should support colored output.
![image](https://user-images.githubusercontent.com/82738/34073959-96d835bc-e273-11e7-9707-6dddefcbe4a8.png)

**Comment by skabashnyuk** [comment]
I think we already have a plan https://github.com/eclipse/che/pull/7720#issuecomment-349221386
afaik it's part of this issue https://github.com/eclipse/che/issues/7008

**Comment by gorkem** [comment]
@skabashnyuk I thought #7008 would fix it but was not aware of #7720 reported. Closing this since it is a duppo
