### ISSUE TITLE
Incorrect author information on Git History

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#7912]
### Description
The information displayed for author for a commit is incorrect. Che history seems to show committers but it should really show author for a commit.

![image](https://user-images.githubusercontent.com/82738/34082477-216253a2-e32d-11e7-90a2-bbabe49995dc.png)

**OS and version:**    

minishift 1.10 on OSX

**Comment by ghost** [comment]
@vinokurig can you comment please?

**Comment by vinokurig** [comment]
Easy to fix!
https://github.com/eclipse/che/blob/c2c1c19e4299c4bcea7d0a69ff9d5a9d73a344fa/plugins/plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/history/HistoryViewImpl.java#L154
Need to replace to `return revision.getAuthor().getName();`
