### ISSUE TITLE
User Dashboard: workspace is started when a project is added

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7916]
Steps to reproduce:

1. Add a project to a stopped workspace
2. Save config
3. Workspace is automatically started

**Comment by ashumilova** [comment]
Proposed solution: 
- The edit mode of the workspace details should explain the following - 
The changes will be affected only after workspace restart. and buttons: "Save" "Save and Restart" "Cancel"
after "Save" is clicked - next button changes title to "Restart"
