### ISSUE TITLE
Can't install on Fedora 23

### ISSUE THREAD

**Issue by tecimovic** [eclipse-che/che#792]
*_Following instructions, I get this:
*_
[~/che/eclipse-che-4.0.0-RC11/bin]$ ./che.sh --image run
###### ######## HOW TO CONNECT YOUR CHE CLIENT

After Che server has booted, you can connect your clients by:
1. Open browser to http://localhost:8080, or:
2. Open native chromium app.
###### 

Starting Che server in docker container named che.
A Docker container named che does not exist or duplicate conflict was discovered.
Cleaning up any zombie containers named che...
Pulling the Docker image labeled codenvy/che:latest...
Trying to pull repository docker.io/codenvy/che ... latest: Pulling from codenvy/che
fcee8bcfe180: Pull complete 
4cdc0cbc1936: Pull complete 
d9e545b90db8: Pull complete 
c4bea91afef3: Pull complete 
f332d67eaa06: Verifying Checksum 
1d551183d586: Download complete 
47923467af26: Download complete 
5365e4732309: Download complete 
b855879bf0d2: Download complete 
3b28039ec239: Download complete 
a61defc0326c: Download complete 
f5e27d4e47bd: Download complete 
94d00ed955b2: Download complete 
14e0e01172cb: Download complete 
895b070402bd: Download complete 
02e5bca4149b: Download complete 
b2ae0a712b39: Download complete 
af88597ec24b: Download complete 
4544cbc68a5d: Download complete 
563adf72d821: Download complete 
93d191d8467d: Download complete 
0b5d081894b4: Download complete 
52dd3af13bf5: Download complete 
3131adb10ad7: Download complete 
5bbed062a066: Download complete 
6efea3ec007c: Download complete 
Status: Downloaded newer image for docker.io/codenvy/che:latest
docker.io/codenvy/che: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

Launching a new Docker container named che from image codenvy/che:latest...
2a7c507f7868d85713b62af53d72f874c4895c038725e13669cfc0b51822ff48
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
Docker container named che successfully started.
Launching Che in a container named che...
chown: cannot read directory '/home/user/che/tomcat/temp/local-storage': Permission denied
chown: cannot read directory '/home/user/che/lib-copy': Permission denied
chown: cannot read directory '/home/user/che/workspaces': Permission denied

**I don't know why did the script create "/home/user/che". I'm just running this from within my user directory: 
   ~/che/eclipse-che-4.0.0-RC11

Version info:
**
[~]$ docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-6.git6ec29ef.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      7206621
 Built:           Mon Jan 25 20:52:22 UTC 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-6.git6ec29ef.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      7206621
 Built:           Mon Jan 25 20:52:22 UTC 2016
 OS/Arch:         linux/amd64
[~]$ docker info
Containers: 4
Images: 19
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-529230-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.027 GB
 Data Space Total: 107.4 GB
 Data Space Available: 43.92 GB
 Metadata Space Used: 1.827 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.3-300.fc23.x86_64+debug
Operating System: Fedora 23 (Workstation Edition)
CPUs: 8
Total Memory: 7.636 GiB
Name: localhost.localdomain
ID: CTJL:2M3Y:EICG:YC7F:XP6M:LTWK:6ZXU:TEOU:RPU4:3NSF:VIVD:PVVX
[~]$ java -version
openjdk version "1.8.0_72"
OpenJDK Runtime Environment (build 1.8.0_72-b16)
OpenJDK 64-Bit Server VM (build 25.72-b16, mixed mode)

**Comment by ghost** [comment]
Did you try running Che natively, i.e. not in a Docker container? Just skip `-i` flag.

As to the Docker issue, `chown` is run in an exec inside the container, but since this directory is mounted into the host as well, there's something that prevents changing directory permissions. Do you have SELinux enabled? Can you disable it and give it a try?

**Comment by tecimovic** [comment]
If I remove -i I can start it up. Thanks!

I'll play with selinux as well.

Cheers,
    T

**Comment by ghost** [comment]
@tecimovic I am closing the issue. Feel free to reopen if Che fails to start on your system.
