### ISSUE TITLE
Installers fail in OpenShift multi-container workspace

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#7927]
### Description
Installers fail in OpenShift multi-container workspace if multiply machine have the same installers. 
The issue can be reproduced only if machines are placed in one Pod. It happens because containers in one Pod uses the same ports. So if a machine has the same installers as is declared in another machine, this installer will get ` bind: address already in use` error while the process starting.

### Reproduction Steps
1. Create a workspace with the following OpenShift multi-container workspace configuration:
<details>
<summary>Workspace Config</summary>

```json
{
  "environments": {
    "default": {
      "machines": {
        "ws/typescript-ls": {
          "servers": {
            "ls": {
              "attributes": {
                "internal": "true",
                "type": "ls",
                "config": "{\"id\":\"org.eclipse.che.plugin.web.typescript\", \"documentFilters\":[  {  \"languageId\":\"typescript\",  \"pathRegex\":\".*\\\\.(ts|tsx)\"} ]}"
              },
              "port": "4417",
              "protocol": "tcp"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal"
          ],
          "env": {}
        },
        "ws/dev": {
          "attributes": {},
          "servers": {
            "codeserver": {
              "attributes": {},
              "port": "9876",
              "protocol": "http"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent"
          ],
          "env": {}
        }
      },
      "recipe": {
        "type": "openshift",
        "content": "---\nkind: List\nitems:\n-\n  apiVersion: v1\n  kind: Pod\n  metadata:\n    name: ws\n  spec:\n    containers:\n      -\n        image: eivantsov/tsls\n        name: typescript-ls\n      -\n        image: eclipse/ubuntu_jdk8\n        name: dev",
        "contentType": "application/x-yaml"
      }
    }
  },
  "defaultEnv": "default",
  "projects": [
    {
      "links": [],
      "name": "greeter",
      "attributes": {},
      "type": "typescript",
      "source": {
        "location": "https://github.com/Microsoft/TypeScriptSamples.git",
        "type": "git",
        "parameters": {
          "convertToTopLevelProject": "true",
          "keepVcs": "false",
          "keepDir": "greeter"
        }
      },
      "path": "/greeter",
      "problems": [],
      "mixins": []
    }
  ],
  "name": "TypeScript_LS_Demo",
  "commands": [],
  "links": []
}
```
</details>
2. Try to start the created workspace.
Expected: Workspace is started.
Actual: Workspace failed to start

![screenshot_20171218_123229](https://user-images.githubusercontent.com/5887312/34102084-7f2eabc0-e3f0-11e7-8729-9a978059bf85.png)

**OS and version:**    

**Diagnostics:**

**Comment by gazarenkov** [comment]
should it work if you override the server declared by installer in concrete machine->servers ?

**Comment by sleshchenko** [comment]
Do you mean specifying a different port for server explicitly in machine configuration?
If yes, then my answer is no. There two reasons why it won't work
- when machine configuration has specified server that has the same name as installer's one but with different configuration then an exception will be thrown. See
https://github.com/eclipse/che/blob/148fe48c1e116301d46cc40204856089cd419329/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/InstallerConfigProvisioner.java#L97-L103
- ports for agents are hardcoded in installers scripts or in packaged agents. See 
https://github.com/eclipse/che/blob/8ad7973a80eaf1ec9ed2d1f594907a54737d299d/agents/exec/src/main/resources/installers/1.0.0/org.eclipse.che.exec.script.sh#L228
https://github.com/eclipse/che/blob/e67979d3379eaa435f7ffb6b5bcc673bd23a60ac/agents/terminal/src/main/resources/installers/1.0.0/org.eclipse.che.terminal.script.sh#L224
https://github.com/eclipse/che/blob/b0dfd90f8c10e8561a8b3ff5e1c51b70e14ca015/assembly/assembly-wsagent-server/src/assembly/server.xml#L72

**Comment by gazarenkov** [comment]
OK, then:
`when machine configuration has specified server that has the same name as installer's one but with different configuration then an exception will be thrown`
Do you think we can not change the behavior like: 
- always override server configuration which come from other sources (like installer) with one specified in concrete workspace's machine->server config.  
- always recommend to to use env variables instead of hardcoding if you consider "portable installer" and use the same policy as for servers (i.e. workspace's config prevails over installer's)

WDYT?

**Comment by sleshchenko** [comment]
@gazarenkov I think it could be useful and it will help resolve such conflicts manually.
But I'd say that it's a workaround because I think it's not a good UX to require from user overriding servers configuration and environment variables if current infrastructure has limitations for machines. Or do you mean that there will be another component in OpenShift infra that will be able to resolve such conflicts automatically by overriding configuration?

**Comment by gazarenkov** [comment]
@sleshchenko I do not think you comment about UX is appropriate...
It is definitely a way to fix problem for OS infra and make things more flexible for others (note in general case you can have the same problem in any environment if by some reason port is engaged by other application).

Sure, you can think about further improvement of OS infra, like analyzing and automatically resolving this conflict if you see some reliable solution. 
But, even so, ability to override server configuration individually is a good and logical feature and ability (not a requirement) to make custom configuration and fix infrastructure problem.

**Comment by benoitf** [comment]
@gazarenkov IMHO UX is definitely not handle correctly if user has to manually override ports for agents that come with che. User expect it's straightforward. 
Also flexible does not mean it can not provide good UX

**Comment by sleshchenko** [comment]
@gazarenkov I fully agree with you that overriding server configuration individually is a good and logical feature. We can use it for resolving such conflicts in our stacks. A user can use it but he has to know about such way of fixing an issue when installers failed because of an occupied port. UI can be improved and allows users to do it quite easily.
But for users, it would be better to provide automatically (or really clear) way of resolving conflicts between installers. I agree that it's better to consider such functionality as a further improvement but not required feature for this issue.

**Comment by gazarenkov** [comment]
@sleshchenko 
yes, exactly, it is 2 different topics revealed by this issue

**Comment by slemeur** [comment]
Why agents are defining their ports and why would it be the responsibility of the end-user to override ports of agents he wants to use?

I'm struggling a bit with the discussion because, as a user, I might enable tooling (aka agent) but I should not care where/how they are running.

It feels more logical that the system assign the ports to the agents automatically - and ensure there is no conflict.

**Comment by garagatyi** [comment]
I think we can (later) solve this by making some rules for agents developers that explain how we can pass port that should be exposed by an agent to work properly when a collision occurs. Then it won't affect UX for end-users but will complicate a bit development of agents. I think it is what @gazarenkov suggested [here](https://github.com/eclipse/che/issues/7927#issuecomment-352761037). 
But this doesn't change the fact that when we have a collision and agent doesn't support changing exposed port by env var end user cannot use such an agent. And in this case, overriding by a user is a way which allows the user to use an agent even though it is definitely a workaround which spoils the UX.

**Comment by sleshchenko** [comment]
There was a discussion with @garagatyi, @skabashnyuk and me. 
So, it was decided to resolve this issue in the following way:
1. Declare that installers must expect `port` where the server should be run. The value of server port can be provisioned with environment variable which name should be constructed in the following way: ~~`{INSTALLER_ID}:{SERVER_NAME}.port`~~
There is a problem with such environment variable name (colon and dot should be escaped). So it is needed to investigate which environment name format will suit the best.
2. OpenShift infrastructure will detect installers servers conflicts and will inject the corresponding environment variables. There will be configured range for ports for new ports, and infra will choose anyone that is not occupied by another installer. Note that except environment variable injection infra must override the configuration of installers servers.

~~So, a user will be able to specify the port for an installer in environment variable manually.~~
If an installer doesn't respect the corresponding environment variable and infra specify it - then workspace won't work correctly.

@garagatyi @skabashnyuk Please, correct me if there is something wrong or missed.
@gazarenkov Are you OK which such an approach?

**Comment by skabashnyuk** [comment]
I suggest such name for environment variable: ```CHE_SERVER_```+```SERVER_NAME``` +```_PORT```
Where SERVER_NAME - uppercases name of the server, where all non-letter characters replaced with ```_```

**Comment by gazarenkov** [comment]
@sleshchenko 
`The value of server port can be provisioned with environment variable`
you mean in the workspace -> environment -> machine -> env ?

**Comment by sleshchenko** [comment]
@gazarenkov Yes. I mean environment variables from machine configuration.
