### ISSUE TITLE
Introduce a Java9 stack

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#7938]
### Description
The current Che IDE does not support Java9, while JDT.LS is supporting it. Until we do the switch of Java support with JDT.LS (#6157) we should proive a custom stack which will have Java9 installed and the JDT.LS enabled. 

We will need to provide a default sample Java9 project too.

We can follow : https://che.eclipse.org/java-9-part-1-using-java-9-in-eclipse-che-c23ab49050d

**Comment by gazarenkov** [comment]
Good idea, but I believe new stack is not enough, Java extension has to be replaced by JDT.LS.
Are we ready for that in terms of features set and quality?

**Comment by gregar** [comment]
Bump.  Any update on Che6 with LS and Java9?
@benoitf

**Comment by benoitf** [comment]
It depends on https://github.com/eclipse/che/issues/6157. When this issue ils completed the support will be ready

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
