### ISSUE TITLE
Setup CI and basic functional testing for a sample custom assembly

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#7958]
There's a sample custom assembly with ide and server side plugin: https://github.com/che-samples/che-ide-server-extension

We need to make sure we know when it's broken:

1. It should be released
2. It should be regularly built, and a custom assembly run (with :/repo mount)
3. Create and start a workspace
4. Create a simple selenium test that opens a running workspace, right clicks in project explorer, clicks My Action, and makes sure there's a notification.

**Comment by riuvshin** [comment]
done, test will be performed as part of ci job https://ci.codenvycorp.com/job/che-ide-server-extension-ci-master
