### ISSUE TITLE
Pull request panel is opened and selection from project explorer item is lost after the first click on project explorer item 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#7959]
*Related tests:*
Potentially all tests from "factory" package and tests from issue(https://github.com/eclipse/che/issues/7940)

*Report with reproduced problem:*
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6/119/Selenium_tests_report/

### Reproduction Steps
 - Run workspace by factory link
 - Wait until workspace will be started
 - Pay attention to the project explorer tree

**Expected behavior:**
After workspace start, the project must be automatically expanded

**Observed behavior:**
The project is not expanded but Pull Request panel is opened.

**Attachment:**
![aaaa](https://user-images.githubusercontent.com/22724619/34158131-e3c46156-e4cc-11e7-85f0-1d301bfc581b.png)

Also, this is a big problem for selenium tests, because after clicking on project explorer item pull request panel opened and selection from the item is lost. 

**OS and version:**    
Che 6.0.0-M4 ; Chrome 63.0 ; Fedora 25

**Comment by Ohrimenko1988** [comment]
Also related to this issue: https://github.com/eclipse/che/issues/7940

**Comment by Ohrimenko1988** [comment]
We have problems in the selenium tests relayed to this problem. For example from issue #7940.

**Comment by tolusha** [comment]
It isn't and IDE issue. Test has to be fixed.

**Comment by vkuznyetsov** [comment]
not actual issue
