### ISSUE TITLE
Unable to use Git menu in IDE

### ISSUE THREAD

**Issue by thejaay** [eclipse-che/che#796]
Hello,

While using Che I noticed that I am no longer able to use most of Git menu options (I don't usually use it so I didn't noticed it immediately). 
Even after initialized Git repository I can't add a remote server or do any request (fetch, pull, commit...), Git is installed in the workspace (PHP standard stack from codenvy dockerfile) and I am able to perform Git operation using the embedded terminal so Git is perfectly working
I'm on Che builded version from master branch (2 days ago)

Here is a snapshot

![image](https://cloud.githubusercontent.com/assets/4380207/14013724/5453aa26-f1ae-11e5-8ea6-039f27efa6e5.png)

Is there a similar issue known for that problem, how can I help you to provide more information.
Thank.
PS: I'm not very familiar with Git yet so I may have made a mistake...

**Comment by ghost** [comment]
Does F5 help?

Also, what is the entire flow? How did you create a project?

**Comment by thejaay** [comment]
F5 didn't help gettin Git menu.
I've redone the process of creating a new project : 
- New project
- Ready to go stack
- PHP stack
- sample PHP project (leave everything as default)
- Still no Git menu

During project/workspace creation I got everything fine except the following error (twice then the project is done creating)

```
[ERROR] [c.s.o.RemoteOAuthTokenProvider 75] - Exception on token retrieval, message : Unsupported OAuth provider github
```

I want to use my own GitLab server and don't want to connect with GitHub, are Git tasks linked to GitHub ?

**Comment by gharriso** [comment]
Also saw this on maser - create project with import from github, git menu actions are all greyed out.  As Tyler is my witness :-)

**Comment by TylerJewell** [comment]
I just tested this as well - this will be a blocker issue to a release, probably.

**Comment by gharriso** [comment]
This resolved on my system once I fixed a Dockerfile permission in my custom stack.  My stack was creating the /projects directory in the workspace as root and consequently the git workspace was not writable by the default user in the workspace.  Once I added "USER user" as the last line in my docker instructions the Git menu became active again.

**Comment by ghost** [comment]
@thejaay I cannot reproduce it with the current master. 

What is your OS? I wonder if this issue is somehow related to mounting.

Tested on Ubuntu and Win. No issues. Can you compile the latest master and give it a shot?

**Comment by ghost** [comment]
@thejaay any update in this? Double checked on different OS. Still cannot reproduce. Are there any special conditions to reproduce the issue?

**Comment by thejaay** [comment]
@eivantsov I will test on latest master when I got some time and feed back with informations. OS is Debian 3.16.7-ckt20-1+deb8u3. I dont' recall any special steps, if there is something to check I can perform some tests (as of what I've read it can be a permission issue)

**Comment by thejaay** [comment]
@eivantsov Just compiled master (commit a790fd4c3501e1ab8cbe04dcda7353201068389b) and created a new workspace (PHP stack), still no Git.
I have tried to create a new workspace/project with Java stack => Git is working
I believe the problem is when you create a new workspace/project with PHP stack, the permissions are differents because we need to grant www-data to use the project folder. I have not yet figured out how things work and I'm not very friendly with Git so if you have any more informations to share :)

**Comment by ghost** [comment]
I see. The usecase is importing a project from the IDE. Yes, I have reproduced it. I think I will remove the default chown from php Dockerfile's CMD.

**Comment by ghost** [comment]
OK, I have updated codenvy/php image. It should be OK now. Just checked on my side. All you need to do is to `docker pull codenvy/php`

**Comment by thejaay** [comment]
After deleting all my docker images and creating a new workspace/project PHP stack I see now all the Git items, good job !!
