### ISSUE TITLE
i can't remove docker container 

### ISSUE THREAD

**Issue by hoban5889** [eclipse-che/che#7964]
### Description

I created 3 che server using docker. and then i created  10 more workspace for test.
and then i overred ram size. i'm first using docker. so i can't handle docker memory issue.

Error response from daemon: Cannot kill container: 5073fb926bd0: Cannot kill container 5073fb926bd0a7bce2579dd4fce610ef770767be2e6d3fbecd51a7c94dfb7784: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown
 
how can i  unlock /var/run/doker/containerd/docker-containerd.sock?

### Reproduction Steps
i created workspace over 7.5G

**OS and version:**    
ubuntu 16.04LTS ram:8G 
**Diagnostics:**

**Comment by ghost** [comment]
@hoban5889 what container do you want to remove?

**Comment by hoban5889** [comment]
I'm trying to delete one of workspace instance for restore docker. any command doesn't work. I think /var/run/docker.sock locked. how can i unlock /var/run/doker/containerd/docker-containerd.sock? how many workspace is possible in 16G Ram? all workspace use /var/run/docker.sock for network?

![image](https://user-images.githubusercontent.com/34687194/34280816-d72b82e8-e6fd-11e7-938b-997f28b890a0.png)

docker stats image.
![image](https://user-images.githubusercontent.com/34687194/34280833-ee25b2e8-e6fd-11e7-8940-398378a59be7.png)

**Comment by ghost** [comment]
So, `docker rm -f $containerID` doesn't work for you? If not, then it's rather a question to a Docker forum.

**Comment by ghost** [comment]
Closed due to inactivity. @hoban5889 feel free to reopen if the issue is still there
