### ISSUE TITLE
LSP Goto definition and External Libraries 

### ISSUE THREAD

**Issue by zatsepinvl** [eclipse-che/che#7970]
There is a feature [textDocument/definition](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_definition) in LSP. How can I return location in some file from External Libraries in Eclipse Che as a response to definition request?

**Comment by ghost** [comment]
@zatsepinvl are you talking about jdt.ls?

**Comment by zatsepinvl** [comment]
To be more concrete, yes. But I want to know about some general mechanism to show location in file from external libraries. For example, there is a TextDocumentContentProvider in vscode to implement custom logic to get content from .class file and show it in new editor: https://github.com/atom/ide-java/issues/42

**Comment by ghost** [comment]
@tolusha @svor @tsmaeder are workinf on jdt.ls - it should be straightforward as go to definition is one of the core features.

**Comment by svor** [comment]
@zatsepinvl We've implemented custom commands of jdt.ls for working with external libraries. Please take a look these changes for more understanding https://github.com/eclipse/che-ls-jdt/commit/8752d3bcd86198bb505f108de476396e6b4b1ffe

**Comment by zatsepinvl** [comment]
@svor Thanks
