### ISSUE TITLE
Workspace does not inherit DNS resolver configuration from the host (Ubuntu 16.04 with Network Manager)

### ISSUE THREAD

**Issue by vsenko** [eclipse-che/che#7973]
### Description
[Docs](https://www.eclipse.org/che/docs/setup/configuration/index.html#dns-resolution) state that
> The default behavior is for Che and its workspaces to inherit DNS resolver servers from the host.

It is not true for Ubuntu 16.04 with Network Manager enabled.

### Reproduction Steps
- Install Ubuntu Desktop 16.04
- Configure DNS resolver to use custom DNS server with specific DNS zone
- Install Che according to [Getting Started: Local](https://www.eclipse.org/che/docs/setup/getting-started/index.html)
- Create any workspace
- Use any tool to resolve DNS name from specific zone - this will fail (if specific zone is not presented in public, then it will simply fail to resolve; if specific zone overrides public zone, then DNS name will resolve to original name)

**OS and version:**
Ubuntu Desktop 16.04
Che 5.22.0

**Comment by ghost** [comment]
@vsenko when your workspace is up, can you grab its id and run docker inspect against it? I will try to reproduce it with a local DNS server a bit later.

**Comment by vsenko** [comment]
Is this it?

    [
        {
            "Id": "f2983b254f6e6b41d84167ddfa922316db3c3e98e9dd9f49c7fd624adfe12f03",
            "Created": "2017-12-21T07:44:50.918454952Z",
            "Path": "/home/user/entrypoint.sh",
            "Args": [
                "/bin/sh",
                "-c",
                "tail -f /dev/null"
            ],
            "State": {
                "Status": "running",
                "Running": true,
                "Paused": false,
                "Restarting": false,
                "OOMKilled": false,
                "Dead": false,
                "Pid": 14560,
                "ExitCode": 0,
                "Error": "",
                "StartedAt": "2017-12-21T07:44:51.428542121Z",
                "FinishedAt": "0001-01-01T00:00:00Z"
            },
            "Image": "sha256:636f58f8ff887ffe53e26a2db5b11b7b9ebb678770d9bd3429e24b70a197787e",
            "ResolvConfPath": "/var/lib/docker/containers/f2983b254f6e6b41d84167ddfa922316db3c3e98e9dd9f49c7fd624adfe12f03/resolv.conf",
            "HostnamePath": "/var/lib/docker/containers/f2983b254f6e6b41d84167ddfa922316db3c3e98e9dd9f49c7fd624adfe12f03/hostname",
            "HostsPath": "/var/lib/docker/containers/f2983b254f6e6b41d84167ddfa922316db3c3e98e9dd9f49c7fd624adfe12f03/hosts",
            "LogPath": "/var/lib/docker/containers/f2983b254f6e6b41d84167ddfa922316db3c3e98e9dd9f49c7fd624adfe12f03/f2983b254f6e6b41d84167ddfa922316db3c3e98e9dd9f49c7fd624adfe12f03-json.log",
            "Name": "/workspace7wasb5884oikq4f4_machineucvkd03iwqkqyz0k_che_dev-machine",
            "RestartCount": 0,
            "Driver": "aufs",
            "MountLabel": "",
            "ProcessLabel": "",
            "AppArmorProfile": "",
            "ExecIDs": [
                "bde89e99962db15d04cec0cdf8eaba7f5f27001fa1ed8e074f0187dccbae683d",
                "a6fb7384edc4654e0b037cf916d17d3d46e059e49a4c597d62507e6e6eb42e0b",
                "dd1e38d11398406de334fee7e4c89561ea1739149800641ad6f0282502517666"
            ],
            "HostConfig": {
                "Binds": [
                    "/data/Che/instance/data/lib/linux_amd64/terminal:/mnt/che/terminal:ro,Z",
                    "/data/Che/instance/data/lib/linux_amd64/exec:/mnt/che/exec-agent:ro,Z",
                    "/data/Che/instance/data/workspaces/node-mongo:/projects:Z",
                    "/data/Che/instance/data/lib/ws-agent.tar.gz:/mnt/che/ws-agent.tar.gz:ro,Z"
                ],
                "ContainerIDFile": "",
                "LogConfig": {
                    "Type": "json-file",
                    "Config": {}
                },
                "NetworkMode": "workspace7wasb5884oikq4f4_6bx1b42r11a7lxgu",
                "PortBindings": {},
                "RestartPolicy": {
                    "Name": "",
                    "MaximumRetryCount": 0
                },
                "AutoRemove": false,
                "VolumeDriver": "",
                "VolumesFrom": [],
                "CapAdd": null,
                "CapDrop": null,
                "Dns": null,
                "DnsOptions": null,
                "DnsSearch": null,
                "ExtraHosts": [
                    "che-host:172.17.0.4"
                ],
                "GroupAdd": null,
                "IpcMode": "",
                "Cgroup": "",
                "Links": null,
                "OomScoreAdj": 0,
                "PidMode": "",
                "Privileged": false,
                "PublishAllPorts": true,
                "ReadonlyRootfs": false,
                "SecurityOpt": null,
                "UTSMode": "",
                "UsernsMode": "",
                "ShmSize": 67108864,
                "Runtime": "runc",
                "ConsoleSize": [
                    0,
                    0
                ],
                "Isolation": "",
                "CpuShares": 0,
                "Memory": 2147483648,
                "NanoCpus": 0,
                "CgroupParent": "",
                "BlkioWeight": 0,
                "BlkioWeightDevice": null,
                "BlkioDeviceReadBps": null,
                "BlkioDeviceWriteBps": null,
                "BlkioDeviceReadIOps": null,
                "BlkioDeviceWriteIOps": null,
                "CpuPeriod": 0,
                "CpuQuota": 0,
                "CpuRealtimePeriod": 0,
                "CpuRealtimeRuntime": 0,
                "CpusetCpus": "",
                "CpusetMems": "",
                "Devices": null,
                "DiskQuota": 0,
                "KernelMemory": 0,
                "MemoryReservation": 0,
                "MemorySwap": -1,
                "MemorySwappiness": -1,
                "OomKillDisable": false,
                "PidsLimit": -1,
                "Ulimits": null,
                "CpuCount": 0,
                "CpuPercent": 0,
                "IOMaximumIOps": 0,
                "IOMaximumBandwidth": 0
            },
            "GraphDriver": {
                "Name": "aufs",
                "Data": null
            },
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/data/Che/instance/data/lib/linux_amd64/terminal",
                    "Destination": "/mnt/che/terminal",
                    "Mode": "ro,Z",
                    "RW": false,
                    "Propagation": ""
                },
                {
                    "Type": "bind",
                    "Source": "/data/Che/instance/data/lib/linux_amd64/exec",
                    "Destination": "/mnt/che/exec-agent",
                    "Mode": "ro,Z",
                    "RW": false,
                    "Propagation": ""
                },
                {
                    "Type": "bind",
                    "Source": "/data/Che/instance/data/workspaces/node-mongo",
                    "Destination": "/projects",
                    "Mode": "Z",
                    "RW": true,
                    "Propagation": ""
                },
                {
                    "Type": "bind",
                    "Source": "/data/Che/instance/data/lib/ws-agent.tar.gz",
                    "Destination": "/mnt/che/ws-agent.tar.gz",
                    "Mode": "ro,Z",
                    "RW": false,
                    "Propagation": ""
                },
                {
                    "Type": "volume",
                    "Name": "7c05ba19273c5373538a02cc717bd5622eb8f0d0a02e2101b8dcb11896c4ea4c",
                    "Source": "/var/lib/docker/volumes/7c05ba19273c5373538a02cc717bd5622eb8f0d0a02e2101b8dcb11896c4ea4c/_data",
                    "Destination": "/tmp",
                    "Driver": "local",
                    "Mode": "",
                    "RW": true,
                    "Propagation": ""
                }
            ],
            "Config": {
                "Hostname": "f2983b254f6e",
                "Domainname": "",
                "User": "user",
                "AttachStdin": false,
                "AttachStdout": false,
                "AttachStderr": false,
                "ExposedPorts": {
                    "22/tcp": {},
                    "4401/tcp": {},
                    "4403/tcp": {},
                    "4411/tcp": {},
                    "4412/tcp": {}
                },
                "Tty": false,
                "OpenStdin": false,
                "StdinOnce": false,
                "Env": [
                    "EXEC_AGENT_LOGS_DIR_SETTER=export EXEC_AGENT_LOGS_DIR=\"$HOME/che/exec-agent/logs\"",
                    "MAVEN_OPTS=-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom",
                    "CHE_LOCAL_CONF_DIR=/mnt/che/conf",
                    "CHE_LOGS_DIR_SETTER=",
                    "USER_TOKEN=dummy_token",
                    "CHE_MACHINE_NAME=dev-machine",
                    "JAVA_OPTS=-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom",
                    "CHE_WORKSPACE_ID=workspace7wasb5884oikq4f4",
                    "CHE_PROJECTS_ROOT=/projects",
                    "CHE_IS_DEV_MACHINE=true",
                    "CHE_API=http://che-host:8080/wsmaster/api",
                    "PATH=/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64",
                    "LANG=en_US.UTF-8",
                    "HOME=/home/user"
                ],
                "Cmd": [
                    "/bin/sh",
                    "-c",
                    "tail -f /dev/null"
                ],
                "ArgsEscaped": true,
                "Image": "eclipse-che/workspace7wasb5884oikq4f4_machineucvkd03iwqkqyz0k_che_dev-machine",
                "Volumes": {
                    "/tmp": {}
                },
                "WorkingDir": "/projects",
                "Entrypoint": [
                    "/home/user/entrypoint.sh"
                ],
                "OnBuild": null,
                "Labels": {
                    "che:server:22/tcp:protocol": "ssh",
                    "che:server:22/tcp:ref": "ssh",
                    "che:server:4401/tcp:path": "/api",
                    "che:server:4401/tcp:protocol": "http",
                    "che:server:4401/tcp:ref": "wsagent",
                    "che:server:4411/tcp:protocol": "http",
                    "che:server:4411/tcp:ref": "terminal",
                    "che:server:4412/tcp:protocol": "http",
                    "che:server:4412/tcp:ref": "exec-agent"
                }
            },
            "NetworkSettings": {
                "Bridge": "",
                "SandboxID": "e3740db0c8a3ebe28740b6b4840832dc95274d76864fc4a5aeb7547740689f8c",
                "HairpinMode": false,
                "LinkLocalIPv6Address": "",
                "LinkLocalIPv6PrefixLen": 0,
                "Ports": {
                    "22/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "32782"
                        }
                    ],
                    "4401/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "32781"
                        }
                    ],
                    "4403/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "32780"
                        }
                    ],
                    "4411/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "32779"
                        }
                    ],
                    "4412/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "32778"
                        }
                    ]
                },
                "SandboxKey": "/var/run/docker/netns/e3740db0c8a3",
                "SecondaryIPAddresses": null,
                "SecondaryIPv6Addresses": null,
                "EndpointID": "7a01303d3769623abeb1a1119a479d1e2d88e480f2a8f061ed3bc12ed59c85c0",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "MacAddress": "02:42:ac:11:00:02",
                "Networks": {
                    "bridge": {
                        "IPAMConfig": null,
                        "Links": null,
                        "Aliases": null,
                        "NetworkID": "ad69bf5dbaeb4986c1edc871b6c52d1112a8262b03d39ee1631a79eaf007bdd1",
                        "EndpointID": "7a01303d3769623abeb1a1119a479d1e2d88e480f2a8f061ed3bc12ed59c85c0",
                        "Gateway": "172.17.0.1",
                        "IPAddress": "172.17.0.2",
                        "IPPrefixLen": 16,
                        "IPv6Gateway": "",
                        "GlobalIPv6Address": "",
                        "GlobalIPv6PrefixLen": 0,
                        "MacAddress": "02:42:ac:11:00:02"
                    },
                    "workspace7wasb5884oikq4f4_6bx1b42r11a7lxgu": {
                        "IPAMConfig": null,
                        "Links": [],
                        "Aliases": [
                            "dev-machine",
                            "f2983b254f6e"
                        ],
                        "NetworkID": "90817fa59ff7e65d92846426527c6d0d9d3e06567bb89d3bbd3f0d5692b713ef",
                        "EndpointID": "fcb2e6539cf46210e519e4aee884687c6e7e38ab7d775c6d9866b875faa50d4c",
                        "Gateway": "172.18.0.1",
                        "IPAddress": "172.18.0.2",
                        "IPPrefixLen": 16,
                        "IPv6Gateway": "",
                        "GlobalIPv6Address": "",
                        "GlobalIPv6PrefixLen": 0,
                        "MacAddress": "02:42:ac:12:00:02"
                    }
                }
            }
        }
    ]

**Comment by ghost** [comment]
@vsenko two findings from me:

1. Che does inherit search but now nameserver. 

2. Provision of custom dns resolvers is indeed broken.

Labeling as a bug.
