### ISSUE TITLE
Do not show Pull Request panel from the start 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#7975]
### Description
I think this behavior very annoying. When i create project from the our sample i don't want to provide any pull request. This is useless. In may daily work i can say what before providing PR i need to work with code firstly and only after that i will provide PR. For me not big problem to push some button on toolbar or use hotkey for opening this this panel. So my propose is show this panel only when user initiate PR creation process.

**Comment by vzhukovs** [comment]
I think it would be better not to show this panel at all and activate it as needed.

**Comment by sunix** [comment]
To me this is a personal point of view. Vitally wants to hide it by default, I want to show it, ... these are preference stuff. Let's create an issue: so the IDE remembers the last layout used by the user and store that in the preferences.

**Comment by slemeur** [comment]
With Che 5 - it is not working like this.
- When you create a new workspace and add a default project in it: the PR panel is not displayed
- When you are in an existing workspace and add a new project from the samples: the PR panel is not displayed
- When you are switching from one project to another project, the PR panel is not displayed.

At first we show the PR Panel, but once it is closed, it must stay closed - even if the user is switching between project or adding a new project.

This is a regression.

**Comment by skabashnyuk** [comment]
@slemeur can you clarify: under which circumstances PR panel should be displayed?

**Comment by benoitf** [comment]
@vzhukovskii looking from external eye, AFAIK this is totally linked to personal point of view when some ppl like and some people dislike.

**Comment by slemeur** [comment]
@skabashnyuk : This panel is important for Che and it is valuable to highlight it for user when they first use the product. And then, the state of the PR panel should be persisted. If the PR panel is closed during his last session, don't show it again. We could and should also allow the user to change that behavior in his user preferences.

Of course, when the PR flow is enabled in a factory, we need to show the panel.

Otherwise, behaviours should not be changed from Che5.

**Comment by Ohrimenko1988** [comment]
Also, we have issue related to this Pull Request panel behavior:
https://github.com/eclipse/che/issues/7959

**Comment by skabashnyuk** [comment]
@slemeur how I can open PR panel after it was closed and state was persisted?
Why are we not using a menu for this?

**Comment by gazarenkov** [comment]
I see no sense in showing this panel for other than "I want to make Pull Request to GitHub" reason.

@slemeur : in Che5  it looks much better from UX standpoint. User *is able to* open it easily, clicking on collapsed panel (button in fact). IDE does not open it automatically *for user* just because user imported project from GH etc.
That is the real problem of Che6 UI and the reason of this issue. It is not about lack of preferences or storing the state.

**Comment by vparfonov** [comment]
[Che 5 Pull Request Panel](https://youtu.be/klZO9C0eVHk)

[Che 6 Pull Request Panel](https://youtu.be/-TC2aXMVb6A)

**Comment by slemeur** [comment]
The discussion is moving away from the initial issue. 
With Che 5:
- When you create a new workspace and add a default project in it: the PR panel is not displayed
- When you are in an existing workspace and add a new project from the samples: the PR panel is not displayed
- When you are switching from one project to another project, the PR panel is not displayed.

To fix this issue, we should just go back to those behaviour. 


--- 
Now, to your specific questions:
@skabashnyuk : It was explained here: https://github.com/eclipse/che/issues/7304#issuecomment-345945429 

@gazarenkov and others in the thread : I understand the problem you are trying to explain. The way to interact with the panel has changed and it is not what an IntelliJ user is used to.
1- We have introduced a new "Views" button in the menu bar, which allow to display the companion side panels. When you click on the button, you can choose which side panels you want to show.
2- We remove the sidebars for three reasons: a/There were no way for the user to completely remove those, b/they are always using space on the screen and c/when a panel is opened, they are duplicating information with the panel header. 
3- It was also intended to get a command palette (but have been able to get it). So when you want to do an action (git commit, push, pull request, trigger a command), you call the command palette or the appropriate keyboard shortcut. 

The goals, are really to remove any sort of distraction and be minimalistic, keep only in the UI the primary actions, focus the user to the code, provide him the largest editor area as possible and let him interact with any IDE actions by using only his keyboard leveraging shortcuts and/or the command palette.
We heard a lot of developers, who just don't want to touch the mouse when they are coding. 

To your point:
> I see no sense in showing this panel for other than "I want to make Pull Request to GitHub" reason. 

Agree - and I see no sense in showing a button "Pull Request" if the user will not use it.


Now, that is true that the initial promise is only partially delivered at this moment - as we don't have the command palette (sic...). That is also true that there are always ways to improve - and I'd like you to keep in mind the goals and propose solutions that are aligned with those. I also would like to invite you to try Visual Studio and XCode to see how panels are handled.  Even IntelliJ and Eclipse allows to remove the sidebars. (with the previous versions of Che, we were not)

I see few proposals:
1- The "Views" button, could be better if we list all the panels (with their name) that are available. Clicking on one of them in the list would display the panel to the user. 
2- We could add a "Views" menu in the menubar, which would list all the panels (and their names) and we would keep the "Views" button as it is.
3- We can change the "Views" button to a toggle, to active the sidepanels, similarly as many Mac OS applications and XCode.
![screen shot 2017-12-20 at 19 32 28](https://user-images.githubusercontent.com/1636769/34222672-9eafbfd4-e5bc-11e7-90e1-2446b637342c.png)

**Comment by AndrienkoAleksandr** [comment]
I totally agree with @gazarenkov . Main reason of the bug it's a new UI concept. We should not "guess on the cards" when user really want to create pull request. It's a user desire when user really need it. Our IDE is not Vanga. 
I think the best solution in this case it's a pull request button. Current behavior it's a like obsessive advertising.

**Comment by gazarenkov** [comment]
@slemeur oh yes, we have problems with UX but let's back to concrete issue:
I do not propose back to Che5 design, we just need "GH Pull Request" feature implemented/callable as a normal IDE Action (via menu item and|or toolbar button and|or shortcut and|or find action item)

**Comment by gorkem** [comment]
@slemeur FWIW closing PR panel is the first thing that I do when I browse to a workspace. I think it is best if it appears on demand via an action or similar.
