### ISSUE TITLE
Add ability to comment a line in editor under cursor with the hotkey

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#7980]
### Description
Some times there is a need to quickly comment a line in the editor under cursor. And it could decrease time for example to comment a line in xml files (find open tag, place `!--` and place `--` in closing tag). Proposed hotkey for macOs `command+/`, for other os `Ctrl+/`.

**Comment by tolusha** [comment]
@vzhukovskii Actually Orion support formatting using `ctrl+shift+/`. Is that you are looking for?

**Comment by vzhukovs** [comment]
@tolusha on macOS there is a hotkey `control`+`command`+`/` but it works in one way only and in if you have selected text.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
