### ISSUE TITLE
che server does not start if CHE_SINGLE_PORT=true

### ISSUE THREAD

**Issue by sahejsingh** [eclipse-che/che#7984]
### Description
CHE CLI throws following error when trying to start che with CHE_SINGLE_PORT=true
```
INFO: (che config):  Customizing docker-compose for running in a container
INFO: (che start):  Starting containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p="che" up -d >> "/data/cli.log" 2>&1
yaml.parser.ParserError: while parsing a block mapping
  in "/data/instance/docker-compose-container.yml", line 22, column 7
expected <block end>, but found '<block mapping start>'
  in "/data/instance/docker-compose-container.yml", line 26, column 11
ERROR: Error during 'compose up' - printing 30 line tail of /Users/next/che/cli.log:
```
### Reproduction Steps
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/che:/data -e CHE_SINGLE_PORT=true eclipse/che:5.22.0 start --fast`

**OS and version:**    
5.22.0 - using docker 17.09.1-ce / docker4mac

**Diagnostics:** 
[cli.log](https://github.com/eclipse/che/files/1577716/cli.log)

**Comment by monaka** [comment]
Same here.

The indent at `restart: always` in `docker-compose-container.yml` looks broken.

```
# ###################################
# This file is generated by puppet
# PLEASE DON'T MODIFY BY HAND
# ###################################


  ########################
  # CHE
  ########################
  che:
    image: eclipse/che-server:nightly
    mem_limit: 750m
    memswap_limit: 0
    env_file:
      - '/data/instance/config/che/che.env'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/opt/home/8081/instance/data:/data'
      - '/opt/home/8081/instance/logs:/logs'
      - '/opt/home/8081/instance/config/che:/conf'
    ports:
      - 8080
    labels:
      traefik.che.frontend.backend: "che-server"
      traefik.che.frontend.entryPoints: "http"
      traefik.che.port: "8081"
      traefik.che.frontend.rule: "PathPrefix:/"
          restart: always
    container_name: che-8081
```

**Comment by ghost** [comment]
Yes, I can confirm the issue. The other thing is since Che6 has been merged to master now, it does not yet support single port routing.

**Comment by monaka** [comment]
Thank you your information. I see the status of the master branch.
At the same time, it looks `dockerfiles/init/modules/compose/templates/docker-compose.yml.erb` is sane.
So it must be generated `docker-compose-container.yml` with correct indents...

**Comment by ghost** [comment]
@monaka yes, we'll look at it. But once again, once this is fixed, single port policy isn't supported yet. Unless you use 5.x tags of course.

**Comment by monaka** [comment]
I got it how to fix this issue.
@eivantsov which is it better to send PR, `5.22.x` or `master` ?

**Comment by monaka** [comment]
I checked with same command line. This issue was not reproduced. It can be closed.
