### ISSUE TITLE
Some quickstarts fail to run on OpenShift

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#7990]
### Description

Here is the list of the failing quickstarts:

| Stack  | Commands for quckstart projects work correctly|
| ------------- | ------------- |
| .NET   | Commands work but for some reason preview URL is not resolved `${server.dot.net.server} ` |
| Android | `run` command error - `keytool error: java.io.FileNotFoundException: /home/user/.android/debug.keystore (Permission denied)` |
| CentOS Node.js  | `Unable to open /etc/scl/conf/rh-nodejs4!` and quickstart itself seems to have issues with dependencies `bower install` - `ECONFLICT Unable to find suitable version for jquery`|
| CentOS Wildfly Swarm | `wfswarm-rest-http` quickstart - build command fails [1] |
| Ceylon with Java JavaScript Dart on CentOS | :question: |
| Debian | :question: |
| Debian LSP | :question: |
| Eclipse Che | build command stucks at `[INFO] Compiling module org.eclipse.che.ide.IDE`|
| Eclipse Vert.x | `vertx-http-booster'` build command fails [3] |
| Java CentOS | `web-java-spring sample` command `web-java-spring:build` - `cp: cannot create regular file '/home/user/tomcat8/webapps/ROOT.war': Permission denied` / SEVERE: Cannot start server. Server instance is not configured. |
| Java Debian | `web-java-spring sample` command `web-java-spring:build` - `cp: cannot create regular file '/home/user/tomcat8/webapps/ROOT.war': Permission denied` / SEVERE: Cannot start server. Server instance is not configured. |
| PHP | :question: |
| PHP  GAE | :question: |
| PHP-5.6 | sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted |
| PlatformIO | ``pio account login` command and try again.` / Error: Not a PlatformIO project. `platformio.ini` file has not been found in current working directory (/projects/.chexq86iy). To initialize new project please use `platformio init` command` |
| Python | Python language initialization failure [6] |
| Python 2.7 | Python language initialization failure [6]  PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted [5] |
| Python GAE | Python language initialization failure [6]  |
| Rails | :question:  |
| Spring Boot | `spring-boot-http-booster` build command fails [8] |
| TomEE | :question: |
| Ubuntu | no quickstarts for the stack |
| Zend  |:question:|

### Reproduction Steps

Run Che on minishift, create a workspace with one of the proposed quickstart and try to run the available commands to build and run the sample.

**Comment by SkorikSergey** [comment]
@l0rd Is this issue still actual.

**Comment by l0rd** [comment]
Yes it should

**Comment by gorkem** [comment]
Closing @l0rd feel free to reopen if there is anything to do
