### ISSUE TITLE
There is no notification about exception occurred during workspace start

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#8001]
### Description
For some reason user's computer may reboot and docker images could be corrupted. And when user is trying to start a broken workspace from the dashboard there is no any notification about the reason.

![screencast 2017-12-21 16-04-37](https://user-images.githubusercontent.com/1968177/34259135-b62e8b24-e669-11e7-9d4c-7f4268b614fd.gif)

**Comment by ashumilova** [comment]
cannot reproduce
