### ISSUE TITLE
Cannot create local repository

### ISSUE THREAD

**Issue by levjason** [eclipse-che/che#8013]
### Description
Trying to create a web application using the default Java stack.  Created the stack and a volume for the m2 repository. Generating the app from a Maven archetype fails with a message that it cannot create a local repository.  6.0.0-M4
### Reproduction Steps
1.   Create a new workspace using the default Java stack
2.   Add a volume called m2 for /home/user/.m2
3.   Create a new project:
     a. Select Java and maven, put in a project name
     b. Click checkbox "From Archetype". Select org.apache.maven.archetypes:archetype-webapp:RELEASE
     c. Click create.

**OS and version:**    
Ubuntu 16.04

**Diagnostics:** 

Start Project generation
Command output

[ERROR] Could not create local repository at /home/user/.m2/repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
Done
Generation project occurs error

**Comment by skabashnyuk** [comment]
open terminal and execute
```chown user ~/.m2```

**Comment by levjason** [comment]
Thank you!
