### ISSUE TITLE
How to get the src of JSON plugin sample?

### ISSUE THREAD

**Issue by gibbon-cn** [eclipse-che/che#8033]
### Description
https://github.com/eclipse/che/tree/master/samples/sample-plugin-json

The page could not be found any more. Where can I get the source code of sample-plugin-json?

**Comment by ghost** [comment]
@gibbon-cn https://github.com/eclipse/che-archetypes/tree/master/plugin-json-archetype/src/main/resources/archetype-resources/plugins

**Comment by gibbon-cn** [comment]
Thanks!
