### ISSUE TITLE
Git credentials installer broken

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#8040]
https://github.com/eclipse/che/blob/e90eaa97fe06f2fbea4ad56351919087fe78d627/agents/git-credentials/src/main/resources/installers/1.0.0/org.eclipse.che.git.script.sh#L12

If there's no `~/.ssh` dir in the container, the script fails to create another script that is then echoed to `~/.bashrc`

**Comment by davidwindell** [comment]
@eivantsov didn't my PR in Oct fix this for you? https://github.com/eclipse/che/pull/7062/

**Comment by ctron** [comment]
I do have the same problem. Git credentials don't work and in the startup log of the dev-machine you can see:

~~~
/bin/sh: 39: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 42: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 33: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 41: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 40: cannot create /home/user/.ssh/git.sh: Directory nonexistent
chmod: cannot access ‘/home/user/.ssh/git.sh’: No such file or directory
/bin/sh: 46: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 44: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 43: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 37: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 45: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 34: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 38: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 32: cannot create /home/user/.ssh/git.sh: Directory nonexistent
/bin/sh: 31: cannot create /home/user/.ssh/git.sh: Directory nonexistent
~~~

Running on OpenShift 3.9, Che 6.5.0.

**Comment by ctron** [comment]
I actually think this is pretty severe bug pretty easy to fix. For me this completely knocks out Git support.

**Comment by phinaliumz** [comment]
I agree with ctron, this makes Git unusable for me aswell. I can use git when I manually copy the keys from `/etc/ssh`, but thats hardly cloud-IDE way to do this.

**Comment by eivantsov** [comment]
Closing as fixed
