### ISSUE TITLE
How to force che-server to bind to localhost (127.0.0.1) using CLI?

### ISSUE THREAD

**Issue by vsenko** [eclipse-che/che#8060]
### Description
I'm trying to setup Che as a local IDE on my workstation. According to the [docs](https://www.eclipse.org/che/docs/index.html#single-and-multi-user-flavors) this scenario is supported:

> This makes a single user Che a good choice for developers working locally.

The problem is that `che-server` binds to **any** local address:

    tcp6       0      0 :::8080                 :::*                    LISTEN      1217/docker-proxy

So my IDE and all my workspaces are accessible without any access control to anyone in my LAN.

### Reproduction Steps
- setup Che according to [Getting Started: Local guide](https://www.eclipse.org/che/docs/setup/getting-started/index.html)
- run `sudo netstat -anp | grep 8080`

**OS and version:**
- ubuntu 16.04
- che 5.22.0

**Comment by ghost** [comment]
@vsenko there's no such CLI feature. In a composefile that is generated when you invoke CLI start command, there's a simple port binding - https://github.com/eclipse/che/blob/26ce7fc554b8f3c7f5c49add8bc480112cfcca78/dockerfiles/init/modules/compose/templates/docker-compose.yml.erb#L54

There's a workaround for you though:

1. Stop Che.
2. Edit `${data_dir}/instance/docker-compose-container.yml` so that ports are:

```
    ports:
      - '${IP}:8080:8080'
```
3. Start Che with `--skip:config`.

**Comment by vsenko** [comment]
@eivantsov, thank you! I'll try the proposed workaround, but it looks a bit messy to me: it seems to me that it is not compatible with `upgrade` command, is it?

IMHO such a feature would be very valuable. Moreover binding to `localhost` in [Local](https://www.eclipse.org/che/docs/setup/getting-started/index.html) scenario could be a sane default. Whereas currently, users who are trying to use Che as a desktop IDE and do not mention the fact that default installation procedure leads to an unsecured che-server available to anyone, are in danger. The ones who deploy Che on laptops and connect to public networks are in real danger.

**Comment by ghost** [comment]
@vsenko if you need security, go for a multi-user Che.

And yes, upgrade will overwrite it.

**Comment by vsenko** [comment]
Suggested workaround didn't work, `start --skip:config` output was:

    WARN: Bound 'eclipse/che' to 'eclipse/che:5.22.0'
    WARNING: No swap limit support
    INFO: (che cli): 5.22.0 - using docker 1.13.1 / native
    WARN: Newer version '6.0.0-M3' available
    INFO: (che config): Generating che configuration...
    INFO: (che config): Customizing docker-compose for running in a container
    INFO: (che start): Preflight checks
    WARNING: No swap limit support
             mem (1.5 GiB):           [OK]
             disk (100 MB):           [OK]
             port 8080 (http):        [AVAILABLE]
             conn (browser => ws):    [OK]
             conn (server => ws):     [OK]

    INFO: (che start): Starting containers...
    INFO: (che start): Services booting...
    INFO: (che start): Server logs at "docker logs -f che"
    The IP variable is not set. Defaulting to a blank string.
    The IP variable is not set. Defaulting to a blank string.
    INFO: (che start): Booted and reachable
    INFO: (che start): Ver: 5.22.0
    INFO: (che start): Use: http://x.x.x.x:8080
    INFO: (che start): API: http://x.x.x.x:8080/swagger

But `netstat` showed that `che-server` was still binded to `*`:

    tcp6       0      0 :::8080                 :::*                    LISTEN      -               


Patching `${data_dir}/instance/docker-compose-container.yml` to

    ports:
      - '127.0.0.1:8080:8080'

produces the following output:

    WARN: Bound 'eclipse/che' to 'eclipse/che:5.22.0'
    WARNING: No swap limit support
    INFO: (che cli): 5.22.0 - using docker 1.13.1 / native
    WARN: Newer version '6.0.0-M3' available
    INFO: (che config): Generating che configuration...
    INFO: (che config): Customizing docker-compose for running in a container
    INFO: (che start): Preflight checks
    WARNING: No swap limit support
             mem (1.5 GiB):           [OK]
             disk (100 MB):           [OK]
             port 8080 (http):        [AVAILABLE]
             conn (browser => ws):    [OK]
             conn (server => ws):     [OK]

    INFO: (che start): Starting containers...
    INFO: (che start): Services booting...
    INFO: (che start): Server logs at "docker logs -f che"
    ERROR: (che start): Timeout waiting for server. Run "docker logs che" to inspect.

But `che-server` is functioning correctly and `netstat` show that it is bound to `127.0.0.1`:

    tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -

**Comment by vsenko** [comment]
@eivantsov, as for me (form a user angle), it is not very handy to password-protect local IDE, so multi-user Che is not the best option.

**Comment by vsenko** [comment]
@eivantsov, thank you for the help!

**Comment by vsenko** [comment]
@eivantsov, pardon me, but there is a problem with `stop`:

    WARN: Bound 'eclipse/che' to 'eclipse/che:5.22.0'
    WARNING: No swap limit support
    INFO: (che cli): 5.22.0 - using docker 1.13.1 / native
    WARN: Newer version '6.0.0-M3' available
    INFO: (che stop): Server che on port 8080 not running...

it actually doesn't stop `che-server`.

This occurs with:

    ports:
      - '127.0.0.1:8080:8080'

**Comment by ghost** [comment]
https://github.com/eclipse/che/blob/69d51483859d828aa285bcef324244ca236109ad/dockerfiles/base/scripts/base/commands/cmd_stop.sh this is the script that stands behind it.

There must be some check that depends on format of port binding.

**Comment by vsenko** [comment]
OK, the problem with `localhost` is that it is problematic to access `127.0.0.1` from the inside of the docker container in the default docker configuration. [Why?](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach#24326540)

I managed to bind `che-server` to docker bridge interface (`docker0`) this way preventing access to it from LAN:
1. in `${data_dir}/che.env` set `CHE_HOST=<ip-of-the-docker0>`
1. in `${data_dir}/instance/docker-compose-container.yml` `'8080:8080'` -> `'${CHE_HOST}:8080:8080'`
1. start Che only with `--skip:config` to restrain it from rewriting `${data_dir}/instance/docker-compose-container.yml`
1. Che URL is `http://<ip-of-the-docker0>:8080`

Anyway it bothers me that official docs encourage new users to run Local installation in such an unsafe manner.
