### ISSUE TITLE
Add a sample project to the 'Openshift Sql' stack

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8070]
### Description
*  Need to add a sample project to the Openshift Sql stack on the OCP platform
* It may be as on the docker platform the `java-petclinic` project
* And after that create a selenium test which covered working with the 'Openshift Sql stack'

**Che version:** 6.0.0-M4
**OS and version:** Fedora 25
**Che install:** OCP (single/multi)

**Additional information:**
![ocp-sql](https://user-images.githubusercontent.com/5408906/34383931-76168796-eb21-11e7-9d75-641eff5b3e91.png)

**Comment by vkuznyetsov** [comment]
not actual
