### ISSUE TITLE
[OCP] Unexpected long timeout to open web-application 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8075]
### Description
* We have a too long timeout to open a web application on ocp platform

**Reproduction Steps:**
* Create the web-java-spring project from template  
* Build and run it
* Click on  the link in the console after start

**Expected behavior:** 
* the application should be available immediately

**Observed behavior:**
* need to wait some time to application is available (appr. 10s)
* timeout in the selenium test is 10 sec

**Che version**: 6.0.0-M4
**OS and version:** Fedora 25
**Che install:** OCP (single/multi)

**Additional information:**
* Related selenium test: _CheckIntelligenceCommandFromToolbarTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![web-app](https://user-images.githubusercontent.com/5408906/34385622-c014dec8-eb2c-11e7-87f3-2eea90244434.gif)

**Comment by skabashnyuk** [comment]
is this up to date?

**Comment by artaleks9** [comment]
It is already not actual.
