### ISSUE TITLE
Is docker compose environment supported?

### ISSUE THREAD

**Issue by levjason** [eclipse-che/che#8079]
### Description
I'm trying to create a multi machine stack from a compose file that has environment variables:

services:
  db:
    image: 'daerepository03.eur.ad.sag:4443/design-server/test:mariadb-10.1'
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: wm
      MYSQL_USER: wmuser
      MYSQL_PASSWORD: 222222
    mem_limit: 1073741824
  dev-machine:
    image: 'daerepository03.eur.ad.sag:4443/design-server/test:is10.1-mariadb'
    mem_limit: 2147483648
    depends_on:
      - db

The stack is created but there are no environment variables for db. Is environment syntax supported?
I am using 6.0.0-M4-SNAPSHOT. 

### Reproduction Steps
Try to create a new stack from the compose file shown above.

**OS and version:**    
Ubuntu 16.04

**Diagnostics:** 
Nothing in the logs.

**Comment by ghost** [comment]
@levjason you need to provide envs in machine config. You can do it in User Dashboard > Workspaces > Your Workspace > Machines > Your machine > Env.

**Comment by garagatyi** [comment]
Yes, environment vars in the recipe are supported. It is strange that they don't work for you.
Can you provide the recipe with the preserved indentation?

**Comment by levjason** [comment]
[multi.txt](https://github.com/eclipse/che/files/1591364/multi.txt)

**Comment by garagatyi** [comment]
I could use your compose recipe as it seems that it uses private Docker registry but I tried to modify workspace created from a default Che mysql stack and env vars injection worked. I checked it by adding new env var into the recipe.

**Comment by levjason** [comment]
I changed the recipe to use public images and the environment variables were still not created for db.  For now I'll use @eivantsov suggestion but it would be better if the variables could be created from the recipe.
