### ISSUE TITLE
Cannot register a user after it has been deleted in Keycloak

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#8081]
Steps to reproduce:

1. Register with email
2. Login to Keycloak admin console and delete this user
3. Try to register again.

It says user already exists.

**Comment by mkuznyetsov** [comment]
KeycloakEnvironmentInitializationFilterr should work as following
1) retrieve Keycloak user information from JWT Token
2) check database for existing user by ID, extracted from Token.
3) if user is not present, then check by email, in case he was recreated in the Keycloak.
4) if user is found by email, then delete previous user in Che DB and create new one. If user is not found by email, the just create new user. To avoid collision with user name, it will attempt to create user with different name, in case if there is conflict
5) in case, if user was found by ID in step 2, then proceed to check, if his email matches the one that has come in Token, and update it in DB if necessary
6) set resulting user in Environment Context
