### ISSUE TITLE
Don't duplicate same installer of different versions in the Workspace Details page

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8092]
### Description
It's weird to see similar installer of different versions divided on separate items in the _Workspace Installers_ list in _Workspace Details_ page on _Dashboard_:
![34408470-cfbaf1b4-ebcc-11e7-82b4-af50ac688fea](https://user-images.githubusercontent.com/1197777/34410889-e63389a6-ebdb-11e7-8090-48e0d5df0833.png)

Alternatives:
- display all available versions in comma-separated view in the single item in the list and underscore current version ;
- display list of versions in drop-down popup in the column **VERSION**.

**OS and version:**    
Eclipse Che 6.0.4-SNAPSHOT

**Comment by SkorikSergey** [comment]
In stack details installers with the same name are enabled:
![eclipse che java-default - google chrome_244](https://user-images.githubusercontent.com/7760565/39366087-98b75806-4a3b-11e8-887e-c98e3a403ff3.png)

**Comment by SkorikSergey** [comment]
Fixed.
