### ISSUE TITLE
Allow editing of workspace recipe in stack configuration

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#8094]
### Description
Sometimes it is very useful to be able to edit workspace recipe. But for now a user can only see it in read only mode on stack editing page

### Reproduction Steps
1. Create a stack from recipe and save it.
2. Open the stack to edit, in section `Recipe` click `Show`
3. The recipe is in read only mode.
![screenshot from 2017-12-28 15-03-24](https://user-images.githubusercontent.com/15607393/34411595-49e0f746-ebe0-11e7-9b7b-697fab0aa4e3.png)

**Comment by andrewsosa** [comment]
In my opinion, this really should be core functionality. The workaround is to create a brand new stack, copy in the old stack's recipe, and then to add the changes that you want -- but why couldn't we just edit the original stack's recipe in place? That way the recipe can be used next time the stack is deployed.

**Comment by gorkem** [comment]
Closing as this works differently with devfiles.
