### ISSUE TITLE
when creating workspace following error occurs at step 2 starting workspace master

### ISSUE THREAD

**Issue by dkapuganti** [eclipse-che/che#810]
[DOCKER] Pulling repository docker.io/codenvy/ubuntu_jdk8 
[DOCKER] [ERROR] Error while pulling image: Get https://index.docker.io/v1/repositories/codenvy/ubuntu_jdk8/images: dial tcp 52.73.94.64:443: connection refused
[DOCKER] Step 1 : FROM codenvy/ubuntu_jdk8
[DOCKER] Pulling repository docker.io/codenvy/ubuntu_jdk8 
[DOCKER] [ERROR] Error while pulling image: Get https://index.docker.io/v1/repositories/codenvy/ubuntu_jdk8/images: dial tcp 52.4.72.58:443: connection refused
[ERROR] Docker image build failed

**Comment by ghost** [comment]
What is your OS?

Can you manually pull images from DockerHub? Make sure everything's OK with connectivity in your machine or VM (if you're on a Mac or Win)

**Comment by dkapuganti** [comment]
it was an issue with proxy solved it.
thanks
