### ISSUE TITLE
Loads of warnings and errors when building dashboard 5.22.x

### ISSUE THREAD

**Issue by andrew-mclachlan** [eclipse-che/che#8109]
### Description
[exec] ERROR in [default] /dashboard/src/app/admin/plugins/plugins.controller.ts:27:9 
     [exec] Property '$scope' does not exist on type 'AdminPluginsCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/app/admin/plugins/plugins.controller.ts:28:9 
     [exec] Property '$q' does not exist on type 'AdminPluginsCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/app/admin/plugins/plugins.controller.ts:29:9 
     [exec] Property '$mdDialog' does not exist on type 'AdminPluginsCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/app/admin/plugins/plugins.controller.ts:30:9 
     [exec] Property '$interval' does not exist on type 'AdminPluginsCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/app/admin/plugins/plugins.controller.ts:31:9 
     [exec] Property '$location' does not exist on type 'AdminPluginsCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/app/admin/plugins/plugins.controller.ts:32:9 
     [exec] Property '$anchorScroll' does not exist on type 'AdminPluginsCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/app/admin/plugins/plugins.controller.ts:33:9 
     [exec] Property 'cheNotification' does not exist on type 'AdminPluginsCtrl'.
     [exec] 

### Reproduction Steps
     mvn clean install in dashboard.

**OS and version:**    
    macOS Sierra

**Diagnostics:** 
         [exec] Sending build context to Docker daemon  10.83MB
     [exec] Step 1/9 : FROM node:6.11.2
     [exec]  ---> cb4fff641acf
     [exec] Step 2/9 : RUN apt-get update &&     apt-get install -y git     && apt-get -y clean     && rm -rf /var/lib/apt/lists/*
     [exec]  ---> Using cache
     [exec]  ---> 6183a6d6c0ed
     [exec] Step 3/9 : COPY package.json /dashboard/
     [exec]  ---> Using cache
     [exec]  ---> d3a509e96f5a
     [exec] Step 4/9 : RUN cd /dashboard && npm install
     [exec]  ---> Using cache
     [exec]  ---> d51904a98745
     [exec] Step 5/9 : COPY bower.json /dashboard/
     [exec]  ---> Using cache
     [exec]  ---> c82dff5eebee
     [exec] Step 6/9 : RUN cd /dashboard && ./node_modules/.bin/bower install --allow-root
     [exec]  ---> Using cache
     [exec]  ---> 9b2a85901de9
     [exec] Step 7/9 : COPY . /dashboard/
     [exec]  ---> f3324a870c53
     [exec] Step 8/9 : RUN cd /dashboard && npm run build && npm run test && cd target/ && tar zcf /tmp/dashboard.tar.gz dist/
     [exec]  ---> Running in d11f65c6a95e
     [exec] npm info it worked if it ends with ok
     [exec] npm info using npm@3.10.10
     [exec] npm info using node@v6.11.2
     [exec] npm info lifecycle che-dashboard@4.0.0~prebuild: che-dashboard@4.0.0
     [exec] npm info lifecycle che-dashboard@4.0.0~build: che-dashboard@4.0.0
     [exec] 
     [exec] > che-dashboard@4.0.0 build /dashboard
     [exec] > gulp build
     [exec] 
     [exec] Using remote Che server http://localhost:8080
     [exec] [13:50:52] Using gulpfile /dashboard/gulpfile.js
     [exec] [13:50:52] Starting 'outputcolorstemplate'...
     [exec] [13:50:52] Starting 'proxySettingsTemplate'...
     [exec] [13:50:52] Starting 'colorstemplate'...
     [exec] [13:50:52] Starting 'styles'...
     [exec] [13:50:53] Starting 'partials'...
     [exec] [13:50:53] Starting 'images'...
     [exec] [13:50:53] Starting 'htmlassets'...
     [exec] [13:50:53] Starting 'brandingassets'...
     [exec] [13:50:53] Starting 'existingfonts'...
     [exec] [13:50:53] Starting 'other'...
     [exec] [13:50:53] Finished 'htmlassets' after 64 ms
     [exec] [13:50:53] Finished 'proxySettingsTemplate' after 1.46 s
     [exec] [13:50:53] Starting 'proxySettings'...
     [exec] [13:50:53] Finished 'outputcolorstemplate' after 1.51 s
     [exec] [13:50:53] Starting 'outputcolors'...
     [exec] [13:50:54] Finished 'colorstemplate' after 1.48 s
     [exec] [13:50:54] Starting 'colors'...
     [exec] [13:50:54] Finished 'proxySettings' after 111 ms
     [exec] [13:50:54] Finished 'outputcolors' after 96 ms
     [exec] [13:50:54] Finished 'colors' after 86 ms
     [exec] [13:50:54] Starting 'scripts'...
     [exec] [13:50:55] Finished 'brandingassets' after 2.36 s
     [exec] [13:50:59] Finished 'images' after 6.2 s
     [exec] [13:50:59] Finished 'existingfonts' after 6.19 s
     [exec] [13:50:59] Starting 'fonts'...
     [exec] [13:52:21] Time: 87320ms
     [exec]           Asset     Size  Chunks             Chunk Names
     [exec] index.module.js  2.38 MB       0  [emitted]  main
     [exec] 
     [exec] WARNING in ./src/app/factories/factories-config.ts
     [exec] [58, 5]: expected an assignment or function call
     [exec] [59, 5]: expected an assignment or function call
     [exec] [60, 5]: expected an assignment or function call
     [exec] [35, 49]: expected parameter: '$routeProvider' to have a typedef
     [exec] 
...
     [exec] ERROR in [default] /dashboard/src/components/widget/selecter/che-selecter.controller.ts:57:9 
     [exec] Property 'selectedValuesByKey' does not exist on type 'CheSelecterCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/components/widget/selecter/che-selecter.controller.ts:69:13 
     [exec] Property '$scope' does not exist on type 'CheSelecterCtrl'.
     [exec] 
     [exec] ERROR in [default] /dashboard/src/components/widget/selecter/che-selecter.controller.ts:71:11 
     [exec] Property 'selectedValuesByKey' does not exist on type 'CheSelecterCtrl'.
     [exec]

**Comment by ghost** [comment]
@andrew-mclachlan should be fixed in master now.
