### ISSUE TITLE
.SymbolMap Files

### ISSUE THREAD

**Issue by SangeethaSivanesan11** [eclipse-che/che#811]
Can you please share what is the use of .symbolMaps file which is in WEB-INF/deploy/_app/symbolMaps folder?

I cannot see any real use for symbol maps in che application. It is mapped with client java files  with FQN.

Awaiting for your reply. Please clarify.

**Comment by SangeethaSivanesan11** [comment]
Just a clarification regarding .symbolMaps files. I have been waiting for your reply. 

Please clarify my doubts which will be much helpful to proceed further.

**Comment by ddementieva** [comment]
These files are generated by GWT during the Che build. They are used to deobfuscate stack traces: http://www.gwtproject.org/javadoc/latest/com/google/gwt/logging/server/StackTraceDeobfuscator.html

**Comment by SangeethaSivanesan11** [comment]
Thanks much for  your reply.  

Is this file referred by client side ? If so, please clarify. 

I had few more queries too. Please refer the below link  in which I have raised my queries:

https://github.com/eclipse/che/issues/789

Awaiting for your response.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.

**Comment by omertabibi** [comment]
Hi, @ddementieva is thie .SymbolMap files have a security impact when exposed publicly. Should we kept them privately?
