### ISSUE TITLE
.Generated Files

### ISSUE THREAD

**Issue by SangeethaSivanesan11** [eclipse-che/che#812]
I can see a java files in ./assembly/assembly-ide-war/target/.generated/ in this path. I think, these files are created in runtime and moved to .Generated folders. 

When these files are created? What is the use of these files? Is it used for any api request or guice injection ?

Can you please clarify !

Awaiting for your reply. Thanks in Advance.

**Comment by ddementieva** [comment]
The same as .symbolMap files, these files are generated by GWT during the Che build.

**Comment by SangeethaSivanesan11** [comment]
Ok.  Thanks much for your reply. Is this files (.generated and .SymbolMap ) are used for content assist ? Will it referred by any other file to trigger a request from client side ?

Awaiting for your reply. Thanks in Advance.

**Comment by ddementieva** [comment]
No, they are not used for the content assist and they are not referred by the client side.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
