### ISSUE TITLE
Conditions of displaying the "artifact id" is not obvious

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8125]
### Description
 If the project name and name of "artifact id" match, the "artifact id" is not displaying. On my opinion this is not obvious.

### Reproduction Steps
- Run default java stack with default spring project
 - Go to the top menu Profile -> Preferences
 - In the opened "Preferences" form click on "Maven" item
 - Click on "Show artifact id in project explorer" checkbox and enable it
 - Click on "Save" button
 - Pay attention that artifact id is not displayed

**OS and version:**    
CHE 6.0.0-M4; Chrome 63.0; Fedora 25

**Diagnostics:**

**Comment by vzhukovs** [comment]
I suppose we need to add:

* A tooltip to artifact id label in Project Explorer to tell user, that this is an artifact id.
* A note label into preference page to tell user, that in case if artifact id is the same as folder names, than artifact id label is omitting.

Hope, this will clarify some misunderstanding in this case.

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
