### ISSUE TITLE
Implement clickable stack trace feature for output console based on xterm.js

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#8145]
### Description
Reimplement clickable stack trace feature in the output customizers for output console based on xterm.js. This feature uses to open file by click on the stack trace link in the console. Needed for test plugin.

**Comment by AndrienkoAleksandr** [comment]
Related to nice integration command output widget based on xterm.js https://github.com/eclipse/che/issues/7008

**Comment by vzhukovs** [comment]
Take into account, that when workspace agent is stopped, we shouldn't customize the locators, cause we won't be able to load those files.

**Comment by AndrienkoAleksandr** [comment]
Task is done in  the pull request https://github.com/eclipse/che/pull/8143
