### ISSUE TITLE
Implement  ability of storing  docker image for custom PRs

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#8152]
### Description
Checking a some specific details after selenium cycle for custom pull-requests need from QA team building CHE from branch related with PR and launching this assembly under Docker. But for this need about 15-25 min. We can reduce this time if we will have ability getting a docker image with CHE.

**Comment by riuvshin** [comment]
Done.  images will be pushed to: https://hub.docker.com/r/eclipseche/che-server/tags/
