### ISSUE TITLE
Signature option in commits using git menu interface in workspaces.

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#8157]
### Description
I would like to request a signature option in commits using git menu interface in workspaces. Currently I have to copy/paste my name and email. (eg Signed-off-by: James Drummond <james@devcomb.com>)

**Comment by JamesDrummond** [comment]
@slemeur Please review.

**Comment by slemeur** [comment]
Hi @JamesDrummond ! Agree. 

That's something I have been thinking about in the new git panel too #5128 
See the mockup: https://cloud.githubusercontent.com/assets/1636769/26212659/8d93942a-3bf6-11e7-98aa-9a733adf6a2b.png

cc @vinokurig

**Comment by JamesDrummond** [comment]
@slemeur Unfortunately I think the signature thing is specific problem of eclipse CLA verification. I have a PR open at https://github.com/googlesamples/assistant-sdk-python/pull/151 and signed the google CLA specifying my email/name then it associates it with my github username.

I'll just keep this open until your great new feature is pushed to master :)

**Comment by JamesDrummond** [comment]
@slemeur Have you added this task to the epic #5128 ?

**Comment by JamesDrummond** [comment]
@slemeur I think this is covered in your epic "Sign off the commit (taken from git preferences defined in the workspace)". Going to close this.
