### ISSUE TITLE
Unable to run mvn clean install successfully for sample project of che-ide-extending 

### ISSUE THREAD

**Issue by dkapuganti** [eclipse-che/che#816]
getting following error:

![result](https://cloud.githubusercontent.com/assets/17871631/14043066/5b90341e-f2a6-11e5-9519-ccea954d2a89.png)

**Comment by TylerJewell** [comment]
We discovered some Pom errors in the sample extensions yesterday.  They will be fixed by Monday.

**Comment by ghost** [comment]
The error says there's no connection to our public Maven repo. Can you repeatedly reproduce it?

**Comment by TylerJewell** [comment]
@eivantsov I think this is due to the bad groupid / artifactid.  I am going to do some improvements / fixes to the sample extensions this weekend.  Also, we are missing the third example (the one that connects the IDE + Server together) in /che-samples. So will add that, too.

**Comment by ghost** [comment]
I have just compiled this extension in Che.

**Comment by TylerJewell** [comment]
@dkapuganti We have fixed these issues and should be ok now.

**Comment by ghost** [comment]
@dkapuganti you seem to have no connection to `maven.codenvycorp.com` which is where parent pom is. Maven fails to download it, and thus considers this pom as non resolvable.

Make sure you can connect to `maven.codenvycorp.com` - try to build this extension locally, without Che - you will need JDK 1.8 and Maven

**Comment by ghost** [comment]
In this thread you mentioned proxy https://github.com/eclipse/che/issues/810

I am sure this is the problem here. You may want to add the following to your settings.xml

```
<settings>
      <proxies>
       <proxy>
          <id>example-proxy</id>
          <active>true</active>
          <protocol>http</protocol>
          <host>proxy.example.com</host>
          <port>${port}</port>
          <username>proxyuser</username>
          <password>somepassword</password>
          <nonProxyHosts>www.google.com|*.example.com</nonProxyHosts>
        </proxy>
      </proxies>
    </settings>
```

**Comment by dkapuganti** [comment]
where exactly is this settings.xml?

**Comment by ghost** [comment]
it's in `$M2_HOME/conf/settings.xml`

**Comment by ghost** [comment]
I suppose you fixed the problem by configuring Maven to use proxy - https://github.com/eclipse/che/issues/816
