### ISSUE TITLE
Select current branch in push drop-down in Git commit dialog

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#8170]
### Description
 
It would be very useful to have selected by default current branch in the push drop-down in Git commit dialog. The list of branches can be very long at it is a bit difficult to find the current branch in the list if I want to push the changes directly after the commit. As for now the first branch from the list is selected by default.
![push_commit](https://user-images.githubusercontent.com/7668752/34558410-b5a65f46-f146-11e7-963c-01ec9fed67b4.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by gorkem** [comment]
Closing
