### ISSUE TITLE
Make dialog confirm buttons consistent 

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#8173]
Now IDE and dashboard, especially dashboard have the confirm buttons located and different positions (left and right),  and with different styles. The aim is to make it consistent for all existing dialogs.
Samples: 
![screenshot from 2018-01-04 12-00-36](https://user-images.githubusercontent.com/1611939/34558648-a0f31160-f147-11e7-93c7-5bff98b23e52.png)
![screenshot from 2018-01-04 12-00-58](https://user-images.githubusercontent.com/1611939/34558649-a1103d26-f147-11e7-9ef0-89a211691031.png)
![screenshot from 2018-01-04 12-08-55](https://user-images.githubusercontent.com/1611939/34558907-8340cd3c-f148-11e7-9548-4e054ac5b657.png)
![screenshot from 2018-01-04 12-10-00](https://user-images.githubusercontent.com/1611939/34558908-835c125e-f148-11e7-9b89-22aa8f43cc5b.png)
![screenshot from 2018-01-04 12-11-00](https://user-images.githubusercontent.com/1611939/34558910-83d57482-f148-11e7-87fe-ff635b693d8c.png)

**Comment by vitaliy-guliy** [comment]
The article [Why ‘Ok’ Buttons in Dialog Boxes Work Best on the Right](http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/) clarifies why it's important.
