### ISSUE TITLE
Wrong CHE_SERVER_CONTAINER_ID in entrypoint.sh in some cases

### ISSUE THREAD

**Issue by aaalex474** [eclipse-che/che#8180]
### Description
In some environments and sometimes CHE_SERVER_CONTAINER_ID got in entrypoint.sh is wrong.
As a consequence, CHE_DATA_HOST is also wrong and different after restart.
As a consequence, workspaces path is also wrong and different after restart.

Particular environment: Azure VMs with Ubuntu Server 16.04

### Reproduction Steps
1. Start Che Server. 
2. Add a workspace.
3. Add a project with some files.
4. Restart docker.
5. Try to open the workspace.
6. Retry 4-5 until the project isn't found any more.
7. Check instance/config/che.properties. che.workspace.agent.dev has a wrong path.

**OS and version:** 
Azure VMs with Ubuntu Server 16.04
Docker version 1.6.0, build 4749651
Eclipse Che 5.18.0

**Diagnostics:** 
get_che_server_container_id() in entrypoint.sh doesn't work as it's supposed

```
get_che_server_container_id() {
  # Returning `hostname` doesn't work when running Che on OpenShift/Kubernetes/Docker Cloud.
  # In these cases `hostname` correspond to the pod ID that is different from
  # the container ID
  echo $(basename "$(head /proc/1/cgroup || hostname)");
}
```
Inside a docker container in Azure VM /proc/1/cgroup can be sometimes like the following one:

```
bash-4.3# cat /proc/1/cgroup
12:blkio:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
11:pids:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
10:hugetlb:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
9:devices:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
8:cpu,cpuacct:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
7:perf_event:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
6:memory:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
5:freezer:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
4:cpuset:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
3:rdma:/
2:net_cls,net_prio:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
1:name=systemd:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2

```
So
```
bash-4.3# head /proc/1/cgroup
12:blkio:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
11:pids:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
10:hugetlb:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
9:devices:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
8:cpu,cpuacct:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
7:perf_event:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
6:memory:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
5:freezer:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
4:cpuset:/docker/56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2
3:rdma:/

```
And

```
echo $(basename "$(head /proc/1/cgroup || hostname)");
56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2 3:rdma:

```
Thus, CHE_SERVER_CONTAINER_ID value sometimes becomes
`"56dcae6d44d00601e9bcfe4e8f82731ef6abc970ae478d286688809e5a8b1db2 3:rdma:"`

As a consequence:

```
bash-4.3# echo $(docker inspect --format='{{(index .Volumes "/data")}}' "$CHE_SERVER_CONTAINER_ID" 2>/dev/null || echo /data)
/home/data/instance/data /data
```

And CHE_DATA_HOST value sometimes is `"/home/data/instance/data /data"`. Yes, with the space in the middle! Instead of `/home/data/instance/data`

Possible fix;

get_che_server_container_id() {
  echo $(basename "$(grep docker /proc/1/cgroup | head -n 1 || hostname)");
}

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.
