### ISSUE TITLE
Add a possibility to run functional tests on CI on the OpenShift infrastructure instead of Docker

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#8186]
### Description
Now we have a possibility to start functional tests in Github PRs on Che with the Docker infra enabled. But we also need to test PRs that change or impact OpenShift infra. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by riuvshin** [comment]
done, to launch tests against che multi user on ocp trigger phrase is: `ci-test-ocp`
ci job: https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/
