### ISSUE TITLE
Named volumes do not work

### ISSUE THREAD

**Issue by ToeiRei** [eclipse-che/che#8203]
### Description

Trying to use volumes to save data to doesn't work

### Reproduction Steps

1. `docker volume create --name eclipse ....`
2. `docker run  -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v eclipse:/data eclipse/che start`

**OS and version:**    

table | header
-- | --
OS | VMware Photon/Linux
OS type | linux
Architecture | amd64
Kernel version | 4.4.86-1.ph1-esx
Version | 17.06.0-ce
API version | 1.30
Go version | go1.8.1

**Diagnostics:** 

```
WARN: Bound 'eclipse/che' to 'eclipse/che:6.0.0-M4'
INFO: (che cli): 6.0.0-M4 - using docker 17.06.0-ce / native
WARN: Newer version '6.0.0-M4' available
INFO: (che config): Generating che configuration...
docker: Error response from daemon: create eclipse/instance: "eclipse/instance" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

**Comment by ghost** [comment]
@ToeiRei this is by design. Support of named volumes for CLI will basically mean rewriting a lot of CLI logic.

**Comment by conrallendale** [comment]
@eivantsov with driver cloudstor:aws this works out of the box. I was expecting to see the same behavior with local volumes. Is there any plan to implement this? thanks.
