### ISSUE TITLE
CHE_LIMITS_USER_WORKSPACES_COUNT don't work

### ISSUE THREAD

**Issue by alu0100825510** [eclipse-che/che#8204]
### Description
i'm triying to put limit for the users workspaces creation in 1, in the file "che.env" it's all ok, but when in the server i can create all workspaces that i want, so the limits don't work.

### Reproduction Steps

sudo docker run --rm -e CHE_CONTAINER_PREFIX='che' -e CHE_LIMITS_USER_WORKSPACES_COUNT=1 -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/che/example:/data -e CHE_PORT=8081 eclipse/che start

**OS and version:**   
ubuntu 16.04

**Comment by ghost** [comment]
@alu0100825510 I will check it myself and update the issue with findings.

**Comment by alu0100825510** [comment]
any idea about this? 
i have tried to do it with differents versions but with the same result

**Comment by ghost** [comment]
@alu0100825510 this is a multiuser Che feature only.

**Comment by alu0100825510** [comment]
@eivantsov  So, there is no type of limitation that can be put on the normal server type (ram, worskpaces, etc)?
Thanks and sorry.

**Comment by ghost** [comment]
@alu0100825510 not sure about RAM, but workspace count cap works only in multi user mode. You can try it though.
