### ISSUE TITLE
Move directory with installed Che JS Plugin from the WS Master instance to the separate service

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8221]
### Description
Need to move directory with installed Che JS Plugin from the Workspace Master instance to the separate service. This make customization model more flexible.
Here we will provide special service that will be part of workspace and have ability provide information about installed plugins and plugin content itself

**Comment by slemeur** [comment]
I thought, the configuration of the plugins of a workspace would be part of the description of the workspace itself. Why would we make a service to know the installed plugins?

**Comment by vparfonov** [comment]
Yes plugins will be part of the description of the workspace, in this case as you understand we can't keep IDE with plugins on the WS master, because the plugin list will be workspace specific.
During working on the https://github.com/eclipse/che/issues/7492 in terms of Plugin life cycle we recognize this problem and solution that we see is a dedicated server that provides plugins scripts per workspace configuration.
Note: thanks for reminding me to add this task to the sprint issues list.

**Comment by slemeur** [comment]
There is probably two level of configuration that we need to configure:
- system level: the user configure the plugins that he wants to be available in all of his workspaces. A user might enable the "Git Panel plugin" for all his workspaces. 
- workspace level: the user can configure what are the plugins that are available per workspace. For example, a Python LS would not be necessary if there is not Python code in the workspace.

Are you considering those two aspects?

**Comment by slemeur** [comment]
Could you please clarify a bit what this means:
> solution that we see is a dedicated server that provides plugins scripts per workspace configuration

What do you mean by "dedicated server" and "plugins scripts" ?

**Comment by vparfonov** [comment]
System level is something new for me and I don't understand why we need this feature. 
Dedicated server - we need it because a user will have his own combination of plugins and it will be fully isolated.
Plugins scripts - source code of plugin.

**Comment by slemeur** [comment]
@vparfonov As a user of Che. If you are interested by a plugin which gives you a Git plugin. Do you want to go into the configuration of each workspaces, and for each workspace enable the Git Plugin? And then similarly, when you'll create a new workspace, you'll have to again go add that plugin? 

As a user, I should be able to configure certain plugins for all my workspaces.
As a user, I should be able to configure other plugins, only for certain specific workspaces.

**Comment by vparfonov** [comment]
@slemeur As a user how many workspace do you have plan create per day?

**Comment by slemeur** [comment]
It depends how Che is integrated with your Devops toolsuite.

Certain integrations will lead users to get one workspace created per work item. (see JIRA plugins and integration in OSIO)
