### ISSUE TITLE
The process number does not coincide with expected in the commands toolbar

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8277]
*Related test:*
CheckIntelligenceCommandFromToolbarTest

### Reproduction Steps
 - Run default java stack with default spring project
 - Click on commands drop-down button button in the intelligence commands toolbar
 - In the opened drop-down list choose "build and run" command
 - Pay attention to the process number in the "EXEC" field of the commands toolbar

**Expected behavior:**
The process number is "#1"

**Observed behavior:**
The process number is "#2"

**Attachment:**

![hgggg](https://user-images.githubusercontent.com/22724619/34874974-fc4fb236-f7a3-11e7-9a68-1668312829c9.png)

**OS and version:**    
Che 6.0.0-M5 ; Chrome 63.0 ; Fedora 25

**Comment by azatsarynnyy** [comment]
It's not a bug of IDE. "Command controller" (drop-down) just displays the PID received from exec-agent. For some reasons, exec-agent assigns 2 as ID for the first launched process.

**Comment by vparfonov** [comment]
@Ohrimenko1988  Let's make fixes in Selenium test according this behavior

**Comment by Ohrimenko1988** [comment]
Selenium test was changed according to the new expected behavior
https://github.com/eclipse/che/pull/8493
