### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#8279]
Since Kotlin is becoming more and more being used in development, I think Eclipse Che should be able to support it along with Java. Both Langs are interopable in terms of IntelliSense too.

**Comment by ghost** [comment]
@sr229 do you know a relatively stable language server for Kotlin?

**Comment by ghost** [comment]
I'll answer this one - https://discuss.kotlinlang.org/t/any-plan-for-supporting-language-server-protocol/2471/7

**Comment by sr229** [comment]
@eivantsov there's a VSCode extension for Kotlin but I doubt it's LSP implementation

**Comment by eivantsov** [comment]
I'm closing the issue. Eclipse Che implements support of new languages only through LSP. As soon as there's one for Kotlin, we'll definitely plug it in

**Comment by jpapejr** [comment]
@ghost https://github.com/fwcd/KotlinLanguageServer ?

**Comment by bbeaupain** [comment]
Just wanted to say +1 for needing Che+Kotlin support. I totally love Che, but love Kotlin a little bit more; and this is the only missing feature holding me back from jumping off the IntelliJ boat.

**Comment by benoitf** [comment]
Hello, do you have tried https://marketplace.visualstudio.com/items?itemName=fwcd.kotlin as vs code extension in Che ?
