### ISSUE TITLE
Define Serverless/Fass development support in Che

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#8284]
### Description
The goal of this epic is to explore the different solutions and determine the Che architecture that will be suitable for Serverless/Fass development.

First study and exploration can be found on the Eclipse Blog: https://che.eclipse.org/apache-openwhisk-eclipse-che-and-openshift-minishift-13627bf2452

**Comment by skabashnyuk** [comment]
As far as I can see in Eclipse Blog is a guide how to run wsk example from Che workspace. 
@slemeur  Is that all that expected? 
@benoitf is there any other ideas how Eclipse Che can benefit from Apache Wsk
