### ISSUE TITLE
https support / nginx reverse proxy

### ISSUE THREAD

**Issue by napalmyourmom** [eclipse-che/che#8285]
I want to preface this post by saying I know this question has been asked and that I want to revisit it, as I think it is a core security requirement for any application that is expected to be publicly facing.

**tl;dr

I want to expose my che infra to the internet over https and with a limited ephemeral port range using a reverse proxy (nginx is preferred).  Has anyone successfully set this up?**

I am trying to setup a che configuration with https so I can expose it to the internet and access workspaces over the internet.

I am doing all of this in docker and attempting to use the nginx-jwilder container to setup automated proxy configuration ( see https://github.com/jwilder/nginx-proxy)

The only instance I have been able to setup where I can access Che workspaces and and successfully pass all diagnostics is using http (so accessing che locally or via openvpn remotely with NO ssl).

If I setup Che with https, I can access the che master container and spin up a workspace container(s) but the diagnostics fail browser --> workspace.

I know this has to do with the docker ephemeral port range, as well as the inability of the master container running on https and the workspace container running on http to speak to each other.

I have a few questions:

1) Can the range of ports che uses in the ephemeral port range be limited?  Based on expected capacity, I would only need to open the first 20 ports in the ephemeral range to the internet... 

2) What are the implications of opening these ephemeral ports to the internet? (assuming the containers themselves do not have direct access to the host network, and are not running as root)

3) nginx-jwilder requires that you pass two -e env variables on the container (VIRTUAL_HOST & VIRTUAL_PORT) and based on these values sets up proxy rules in nxinx (http or https, depending on if an associated cert exists).  Could this be leveraged to run the che infra in https?  I have tried all of the config combinations I could think of, but cannot get it to work.

4) Is the general expectation with che that it is to be used over http? (so only locally and over a vpn if even the most basic security is being taken into consideration)

I can provide specific configuration parameters to my instance a little later today, but wanted to pose the question

**Comment by eivantsov** [comment]
You may follow this PR https://github.com/eclipse/che/pull/9097

Once merged, docs will be updated with instructions as well
