### ISSUE TITLE
[Multiuser] Authorize an application on GitHub from the 'Import GiitHub' does not work

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8288]
### Description
* When I try to authorize an application on GitHub from the 'Import Project GitHub' form    I have error notification and nothing more

**Reproduction Steps:**
* Open the IDE, go to the 'Workspace' in the Menu
* Select the 'Import Project' -> 'GitHub'
* Click the 'Load Repo'
 
**Expected behavior:**
* should be appeared web page with a login form to GitHub 

**Observed behavior:**
there is message: 'Failed to authorize application on GitHub'

**Che version:** 6.0.0-M5
**OS and version:** Fedora 25
**Che install:** Docker/OCP (multiuser)

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![auth-github-import](https://user-images.githubusercontent.com/5408906/34907156-eea7d584-f882-11e7-9afc-5933ccab781e.gif)

**Comment by ghost** [comment]
@artaleks9 I think adding steps on configuring GitHub oAuth are necessary too. Please, update the issue.

**Comment by mshaposhnik** [comment]
Fixed;
