### ISSUE TITLE
All traffic doesn't go through unique single port

### ISSUE THREAD

**Issue by alu0100825510** [eclipse-che/che#8289]
i'm triying to enable 'CHE_SINGLE_USER=true', but i have detected that all traffic doesn´t go throuw a unique port, because when i start a workspace the browser try to connect with the agents throuw the range of ephemeral ports (32768-65535).

So, why doesn't all traffic go throuw the single port?

![che](https://user-images.githubusercontent.com/22496548/34909118-3d25120c-f893-11e7-9b74-1ab1ecc5f3b6.PNG)

sudo docker run -it --rm -e CHE_SINGLE_PORT=true -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/che/example:/data -e CHE_PORT=8084 -e CHE_HOST=192.168.0.162 eclipse/che:6.0.0-M4 start

**Comment by ghost** [comment]
@alu0100825510 single port routing is not yet ported from Che 5.

**Comment by alu0100825510** [comment]
now i'm triying to do it eith the version 5.22.1 with the single port 8085, but when the workspace is starting appears this message

![ch2](https://user-images.githubusercontent.com/22496548/34909825-b850ad8a-f8a0-11e7-9448-7b017c3719de.PNG)

**Comment by alu0100825510** [comment]
This is the command, i have 2 network with dnat rules.

sudo docker run --rm -e CHE_SINGLE_PORT=true -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/che/example:/data -e CHE_PORT=8085 -e CHE_DOCKER_IP_EXTERNAL=192.168.0.162 -e CHE_HOST=77.77.77.72 eclipse/che:5.22.1 start

**Comment by alu0100825510** [comment]
I tried to try che_single_port with version 5.22.1. In the creation of the first server everything is correct, but if I try to run a new server in a different port I get the following error in the creation of the container.

![seleccion_070](https://user-images.githubusercontent.com/22496548/34911866-bf21c02a-f8ca-11e7-89da-c283d1563890.png)

che version: 5.22.1
SO: ubuntu 16.04
docker version : 17.12.0-ce

**Comment by alu0100825510** [comment]
Now I have changed to version 5.22.1 and it works fine. But an error occurs when I try to run a second server at the same time on a different port, I always get this error.
![seleccion_249](https://user-images.githubusercontent.com/22496548/34921692-b7bf6496-f97d-11e7-8f58-ea6c1d13576f.png)
And the log shows:
![seleccion_250](https://user-images.githubusercontent.com/22496548/34921694-bb5d4ec4-f97d-11e7-9f02-82fa97aa30fe.png)
in other cases (for example when in the first server there are any workspace running) the log shows:
![seleccion_251](https://user-images.githubusercontent.com/22496548/34921966-30aa6df8-f981-11e7-991d-04ddfcbf4118.png)

so, can che_single_port run with various servers (in differents port each) in the same host ?

**Comment by skabashnyuk** [comment]
Duplicates https://github.com/eclipse/che/issues/7362

**Comment by skabashnyuk** [comment]
Close since https://github.com/eclipse/che/issues/7362 has been fixed

**Comment by skabashnyuk** [comment]
@alu0100825510 can you clarify are you using che5 or che6? Can you test it on che6?

**Comment by skabashnyuk** [comment]
Closed due inactivity and because it's already fixed in Che6
