### ISSUE TITLE
Information on the "Account" page is not updated after change it on "Keycloak" page

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8296]
### Reproduction Steps
 - Go to the "Che" login page and register a new user
 - Log in with this user
 - Click on username button in the down of dashboard 
 - Click on "Account" button
 - On the opened page click on the "Edit" button
 - On the opened Keycloak account page do changes in the "Email", "First Name" and "Last Name" fields and click on "Save" button. Pay attention that alert with a successful message is displayed.
 - Close "Keycloak" browser tab and pay attention that on the dashboard account page is nothing changed.
 - Try to click on the different buttons on the dashboard (for example "Workspace", "Dashboard" or "Stacks") and return back to the "Account" page. 
 - Pay attention that fields values are not changed.

**Expected behavior:**
The information on the "Account" page will be updated after clicked on the dashboard items and return back to the "Account" page.

**Observed behavior:**
The information is not updated.

**Attachment:**
![after](https://user-images.githubusercontent.com/22724619/34945142-f2f4552a-fa0a-11e7-8845-faaabf844402.png)

![before](https://user-images.githubusercontent.com/22724619/34945146-f648666c-fa0a-11e7-920a-ab1296ed3856.png)

**OS and version:**    
CHE 6.0.0-M5 ; Chrome 63.0 ; Fedora 25

**Comment by ashumilova** [comment]
Discussed long time ago - it should not be updated, Keycloak is a separate application - that does not notify dashboard one about the changes. Only "Refresh" should work.
