### ISSUE TITLE
Link to Installers page in machine settings is broken

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8311]
**Reproduction Steps:**
- Create any workspace and open its **Machines** page
- Click on a machine **Settings** button
- Click on the **Installers** link

**Expected behavior:**
The **Installers** page is opened

**Observed behavior:**
Nothing changed

**OS and version:**
Che 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
![eclipse che wksp-j42i - google chrome_134](https://user-images.githubusercontent.com/7760565/34985591-3d394a66-fabd-11e7-8221-67659f94999c.png)

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/8482/commits/1720c815ba6355ab648bcf8104a87ce3a2dfee06
