### ISSUE TITLE
LSP support for next gen Che

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#8322]
### Description
The goal of this epic is to work on the next gen Che and provide support for the LSP as complete as we have today in the current Che's IDE.

We should identify the gaps and collaborate with Theia contributors in order to start filling the missing features in the support of the LSP. 

We should target to ship JDT.LS with Theia. Even if all capabilities of the LS are not leveraged.
We should be running performance tests to see how it behaves compared to Che GWT IDE.

### Linked Issue
https://github.com/eclipse/che/issues/6157 Switch to jdt.ls
https://github.com/eclipse/che/issues/9441 Allow consuming LS functionality running as a sidecar in Theia base ide 
https://github.com/eclipse/che/issues/8514 Che/Theia Feature gap
https://github.com/eclipse/che/issues/10227 Support for multiple tabs per language server

**Comment by tsmaeder** [comment]
For one thing, we'll have to have a way to start and connect to language servers inside the workspace machine or in a side car. Second, we'll have to deal with protocol extensions in some way: for example, when we open a Java project, we need the language server started right away to have access to external libraries. 
But I guess the first task would be to find out what needs to be done.

**Comment by slemeur** [comment]
Cross link to https://github.com/eclipse/che/issues/8514
