### ISSUE TITLE
Workspace agent is no longer responding.

### ISSUE THREAD

**Issue by alu0100825510** [eclipse-che/che#8323]
### Description
I am running a server in che_single_port mode, but this error appears when I try to run a workspace

### Reproduction Steps
sudo docker run --rm -e CHE_CONTAINER_PREFIX='xxx' -e CHE_SINGLE_PORT=true -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/che/example:/data -e CHE_PORT=8081 -e CHE_HOST=10.6.134.51 -e CHE_DOCKER_IP_EXTERNAL=10.6.5.248 eclipse/che:5.22.1 start

**OS and version:**    
Debian 9
Che version : 5.22.1
docker version : 17.09.1-ce
**Diagnostics:** 
![seleccion_072](https://user-images.githubusercontent.com/22496548/35022880-13ff8412-fb30-11e7-8e52-cae6339e6938.png)

**Comment by ghost** [comment]
@alu0100825510 are Che and your browser on different machines?

**Comment by alu0100825510** [comment]
@eivantsov Yes, in different machines. I have run a server in local to test and I have obtained the same result:
sudo docker run --rm -e CHE_CONTAINER_PREFIX='xxx' -e CHE_SINGLE_PORT=true -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/che/example:/data -e CHE_PORT=8085 -e CHE_HOST=local_ip -e eclipse/che:5.22.1 start

![seleccion_073](https://user-images.githubusercontent.com/22496548/35033775-c66d218a-fb63-11e7-9496-908a051e8b51.png)

**Comment by ghost** [comment]
@alu0100825510 your `CHE_HOST` should be IP that is accessible from the machine you access Che.

Also, I can see that http://nip.io is down, which means these urls won't be resolved.

**Comment by alu0100825510** [comment]
@eivantsov in local should go well, but nevertheless it is not like that:
sudo docker run --rm -e CHE_CONTAINER_PREFIX='xxx' -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/che/x:/data -e CHE_PORT=8085 -e CHE_SINGLE_PORT=true eclipse/che:5.22.1 start

![seleccion_074](https://user-images.githubusercontent.com/22496548/35034439-17e7ed40-fb66-11e7-821e-f0b34f8f882a.png)

**Comment by alu0100825510** [comment]
if I remove the che_single_port mode everything works correctly, so it has to be something related to that mode, I think

**Comment by ghost** [comment]
@alu0100825510 nip.io is down.

**Comment by alu0100825510** [comment]
@eivantsov Sorry, I had not seen it. From what I understand, I have to wait for it to resume nip.io, it's an external service to us, thank you very much.

**Comment by ghost** [comment]
@alu0100825510 yes, correct

**Comment by benoitf** [comment]
@alu0100825510 you might use xip.io in config file as well as a workaround (wildCardXipDomain instead of wildcardNipDomain)

```
starting with -e CHE_DOCKER_SERVER__EVALUATION__STRATEGY_CUSTOM_TEMPLATE="<serverName>.<machineName>.<workspaceId>.<wildcardXipDomain>:<chePort>"
```

**Comment by alu0100825510** [comment]
@benoitf perfect! Now that works well, thank you very much
