### ISSUE TITLE
Log contains no information on Creating A Factory Based On A Repo

### ISSUE THREAD

**Issue by JackEF** [eclipse-che/che#8328]
### Description
Creating a Factory based on a git repository using a (likely) bad .factory.json file fails with "Cannot build factory with any of the provided parameters.". This is also the only content within the log in the lower right corner (downloadable using the link "Problem? download logs"). The log should contain more information on what caused the error or how it could be fixed.

### Reproduction Steps
Execute e.g.  http://localhost:8080/f?url=https://gitlab.idial.institute/ESMDPS/factory
(adapt the link to your che instance)

**OS and version:**    
All OS

**Diagnostics:** 
Only obtainable information (so far): "Cannot build factory with any of the provided parameters."

**Che-Version**
6.0.0-M4

**Comment by ghost** [comment]
@JackEF what Che version do you have?

**Comment by ghost** [comment]
And afaik only GitHub urls are supported. I have given it a try with Gitlab.com and it failed with the same error.

**Comment by JackEF** [comment]
Thanks for the quick reply! I assumed this function is independant of the underlying git repo hosting service. 
I've updated my initial post, the version im using is 6.0.0-M4

**Comment by ghost** [comment]
https://github.com/eclipse/che/blob/master/plugins/plugin-github/che-plugin-github-factory-resolver/src/main/java/org/eclipse/che/plugin/github/factory/resolver/GithubFactoryParametersResolver.java

GitHub only

**Comment by benoitf** [comment]
@eivantsov it seems https://github.com/codenvy/codenvy/tree/master/plugins/plugin-gitlab

https://github.com/codenvy/codenvy/blob/master/plugins/plugin-gitlab/codenvy-plugin-gitlab-factory-resolver/src/main/java/com/codenvy/plugin/gitlab/factory/resolver/GitlabFactoryParametersResolver.java has not been moved when factories have been moved from codenvy

**Comment by edeandrea** [comment]
Has this moved anywhere or been resolved in the last year? This still seems to be broken in Che 6.8.0. The same `.factory.json` file works fine if served from GitHub but fails when served from GitLab.

**Comment by edeandrea** [comment]
ping to keep open

**Comment by rhopp** [comment]
@edeandrea I'm afraid we will not fix this one for Che 6.x stream.
For Che 7 we've moved to "devfiles" concept. I suggest you to try to move to Che 7 & devfiles.
I took a look at your factory and it seems there is nothing devfile couldn't handle. Once you have your devfile, you can create workspace from that devfile exactly the same way you created workspace from factory: `<che-server-url>/f?url=<devfileUrl>`.

If you wan to take a look at some devfile examples, you can here: https://github.com/eclipse/che-devfile-registry/tree/master/devfiles
