### ISSUE TITLE
Remove modifying of image command/entrypoint in Docker infra

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#8344]
### Description
The feature this issue is about is modifying image entrypoint/cmd in case image is using terminating entrypoint/cmd whereas Che needs non-terminating one, such as `tail -f /dev/null`.
This feature allows using base images in workspace definitions, such as `ubuntu` and others. 
To implement this feature on Docker we inspect image after pulling and if we find that command is terminating we change it to `tail -f /dev/null`.
We can not do that on OpenShift/k8s because it is OpenShift who pulls images and deploys containers, so we don't have an ability to change image configuration in a MITM-like way.

I believe that this feature should be removed even though it is me who implemented it.
### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
@garagatyi is it correct if we implement this issue we would not be able to base images in workspace definitions, such as ubuntu and others?

**Comment by garagatyi** [comment]
@skabashnyuk yes, we won't be able to use such images in our stacks on docker infrastructure. But they don't work on other (k8s, OS) infrastructures, so it makes sense to me to align the behavior and not to change user's containers.

**Comment by skabashnyuk** [comment]
Not sure we need that. I guess we need PM @slemeur  confirmation on that.

**Comment by slemeur** [comment]
How this would be impacted with workspace.next?

**Comment by garagatyi** [comment]
As far as I understand it won't overlap with the Workspace Next. Workspace Next won't modify user's images as it is not possible on most infras (k8s/OS) and it conflicts with the unmodifiable nature of containers. So this would be an issue irrespective of Workspace Next.

**Comment by slemeur** [comment]
I agree @garagatyi that we don't want to change the user's images - and I agree that it is true for all infrastructure supported by Che.

The question I had is a bit broader, how workspace.next will handle the situation where the image(s) given for the workspace is(are) a terminating ones?

**Comment by skabashnyuk** [comment]
if we don't invent something smart then we simply should fail with a reasonable message.

**Comment by garagatyi** [comment]
@slemeur Workspace.Next won't handle this situation any better than we can do it now because it is rather related to APIs of kubernetes not our implementation of usage of it. 

@skabashnyuk I've added a comment about that to the existing issue in Che https://github.com/eclipse/che/issues/7926#issuecomment-389499634

**Comment by slemeur** [comment]
That is something we can remove only when doing a major version change. Otherwise it's going to affect existing users on Docker.

**Comment by garagatyi** [comment]
Outdated
