### ISSUE TITLE
Calling php script with xmlhttprequest doesn't work

### ISSUE THREAD

**Issue by halaszlo** [eclipse-che/che#8351]
### Description
I have a test workspace with a html file (index.html), a Javascript file, and a php file.
The html file call the js file with `<script src="js/test.js"></script>`.

The js file call a php file with xmlhttprequest, and write the php result into a container:
test.js:
`var url = "php/test.php";		
var http = new XMLHttpRequest();
http.open("GET", url, true);
http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
http.onreadystatechange = function() 
{
	if(http.readyState == 4 && http.status == 200) 
	{				
		var container = document.getElementById("test");
	    container.innerHTML = http.responseText;
	}
}
http.send();
` 
The php script only write a "Hello World!" by echo:
test.php:
`
echo "Hello World!\n";
`

On a simple apache server it works fine.
In Che it doesn't work. (In docker)
Could you help me?
Thanks

**OS and version:**    
Tested on codenvy.io .
[test.zip](https://github.com/eclipse/che/files/1643117/test.zip)

**Comment by ghost** [comment]
@halaszlo but where's test div in your html?

And it is just Apache running in a Che workspace (docker container).

**Comment by ghost** [comment]
This is how it works for me. I added test div to html page
```
<!DOCTYPE html>
<html>
<head>
<script src="test.js"></script>
    <title>It WORKS</title>
</head>
<body>
<div id="test"></div>
</body>
</html>
```

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/5337267/35208735-6fe1a2da-ff52-11e7-9614-16ef3001e2de.png)

**Comment by halaszlo** [comment]
@eivantsov Did you see the attached test.zip? It has the div in the index.html.
And what do you mean by "Apache running in che workspace"?

I tried to add you in the workspace team of my codenvy test workspace.
But i don't know how to share the link of the workspace.
Can you help me how to set the environment in my codenvy workspace in order to this php calling could work?
Thanks

**Comment by ghost** [comment]
@halaszlo you can try it with 3 simple files. So, index.html, test.js and test.php - it worked for me this way. Once you get it to work you can then find out what's wrong with your project.

And by saying `Apache running in che workspace` I mean that it's apache that runs in a Che workspace, just like Apache runs locally.

**Comment by halaszlo** [comment]
OMG, It works! Only preview does not work. (Right click on html file and Preview). But clicking on the link you got when you start the apache in Che terminal it works. Thanks a lot!

**Comment by ghost** [comment]
@halaszlo  preview html may not work for your particular case since it's using a different mechanism and Apache isn't involved there.
