### ISSUE TITLE
Document "IDE agnostic way to launch GWT Super DevMode" and other GWT dev settings

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-che/che#8352]
### Description

In #7084 @azatsarynnyy wrote up a great bit of doc on launching in super dev mode. Can this be added to the [wiki](https://github.com/eclipse/che/wiki/Development-Workflow#debugging-che-ide-extensions) with now irrelevant sections removed?

#7084 also refactored the gwt template and the [documentation](https://www.eclipse.org/che/docs/assemblies/plugin-lifecycle/index.html#improving-incremental-builds) on increasing incremental build speed is out of date again.

In general, any advice on speeding up the turnaround time of the edit/run cycle of the IDE would be most welcome. Is there any other ways that the regular IDE devs speed up the cycle? How long does it normally take?

**Comment by ghost** [comment]
@jonahkichwacoders https://www.eclipse.org/che/docs/6/che/docs/ide-extensions-gwt.html this is already part of docs, not yet published as mainstream docs though
