### ISSUE TITLE
How do I do a git checkout from sourceforget.net using password

### ISSUE THREAD

**Issue by harlanb** [eclipse-che/che#836]
Hello,
  I'm trying to checkout my project from SourceForge.net using git.  The checkout keeps failing.

  I'm using ?token=xxxx as part of the git: line.  I've setup an API key at sourceforge and put that as the token.  I've also created a public rsa key and put that in sourceforge.  Che can't find the private key and I haven't found how to import the private key into che.

  Suggestions or pointers gratefully accepted.

Thanks,

Harlan...

**Comment by harlanb** [comment]
I've also tried to create an empty workspace and import from a git repository.  That also failed because of authentication.  On the URL, I was not able to use the "?token=" syntax; che showed an error saying the URL wasn't right.

**Comment by TylerJewell** [comment]
@skabashnyuk Is this an authentication issue?  I thought we had checked all of the git hosting providers, but in looking at our interoperability list of git providers, I don't see any tests run against sourceforge.

**Comment by harlanb** [comment]
Hi Tyler,
  Yes, it appears to be an authentication issue, at least that's what it's telling me the problem is.  It seems to find sourceforge just fine.

Thanks,

Harlan...

**Comment by ghost** [comment]
@harlanb you can generate a private key and save its public part to your sourceforge account. This would work. I haven't tried sourceforge, but it works for a number of git providers.

A URL with token does not pass regex check, i.e. Che does not expect a Git URL in this format.

**Comment by harlanb** [comment]
From within Che, I did generate a key, and saved the public part to sourceforge.  Che still failed to authenticate complaining about not being able to find the private part.

**Comment by ghost** [comment]
What hostname did you use when generating the key? Can you share screenshot with this error?

**Comment by harlanb** [comment]
For the hostname, I've tried sourceforge.net, shell.sourceforge.net.
![screenshot03](https://cloud.githubusercontent.com/assets/1940011/14063507/046eb2fe-f392-11e5-97ab-573dd81c9acf.png)

Here is the text of the error message:

Unable get private ssh key. You can create a new SSH key pair in Help->Preferences->SSH->Git.

Screenshot attached.

----- Original Message -----

**Comment by ghost** [comment]
Why don't you try git.code.sf.net - the hostname in a Git URL?

**Comment by harlanb** [comment]
That worked today.  When I tried it yesterday (and forgot to mention it earlier) it didn't work.

Thank You for all your help!!!

This ticket may closed. 

Harlan...

**Comment by TylerJewell** [comment]
Cool - well done @eivantsov.  Enjoy @harlanb!
