### ISSUE TITLE
Severe browser performance issues when using Soft Wrap

### ISSUE THREAD

**Issue by digiltd** [eclipse-che/che#8365]
### Description

Our team has been using Che for a while now, though myself and another developer have been struggling with:

- constant browser crashes
- extremely jerky scrolling (both the project tree and editor)
- very laggy typing (sometimes a 2-3 second delay)
- been unable to create a new Javascript file using the IDE (we would have to create the file in the terminal and add some content in Nano before it would open)
- unable to open/rename (some) Javascript files that had created/uploaded previously

The problem would only affect the two of us and we ruled out:

- browser (tried Chrome, Canary, Safari, and Firefox, disabled add-ons, went incognito etc)
- operating system (one uses Mac, the other Windows whilst the rest of the team Ubuntu)

The problem was definitely linked the account as when a team member (who wasn't having problems) logged into their account on the machine of a member (who was having problems), everything would be fine and problem free, and vice-versa.

We also ruled out our Che server as the cause, as the problem existed when running Che locally, and when using Codenvy.

**Eventually we discovered that Soft Wrap was the source of the problem.**

It would cause the browser to constantly output `[Violation] 'setTimeout' handler took 123ms` entries in the console. 

The amount of violations seemed to be related to:

- the length of the file (the file has to be able to scroll)
- the level of syntax highlighting e.g. 
  - plain text is all white and not affected
  - CSS has simple highlighting and a narrow wrap to begin with and is moderately affected
  - JS/PHP/Python etc have complex highlighting and are severely affected
  - XML which although has simple highlighting, it typically contains lots of long lines that need wrapping

**Screencast**

[![alt text](https://user-images.githubusercontent.com/5680968/35099871-8442ad0e-fc51-11e7-8ad6-fb09220615ed.png "See screencast demo on Vimeo")](https://vimeo.com/251631116)

https://vimeo.com/251631116

### Reproduction Steps

Create new workspace using the Blank stack and Blank project

Import some files (here are some from the Che repo, and jQuery)

```
wget https://github.com/eclipse/che/blob/6.0.0-M4-x/pom.xml https://raw.githubusercontent.com/eclipse/che/6.0.0-M4-x/ide/che-core-orion-editor/src/main/resources/org/eclipse/che/ide/editor/orion/client/orion-codenvy-theme.css https://code.jquery.com/jquery-2.2.4.js https://raw.githubusercontent.com/codenvy/che-docs/master/src/main/pages/ide/version_control.md 
```

Turn on Soft Wrap

`Profile > Preferences > IDE > Editor > Edit > Soft Wrap (ticked)`

Open browser Console and set level to verbose

Use the editor

- open the downloaded `jquery-2.2.4.js` file
- scroll around
- split pane into two columns
- resize browser window or pane
- try to create a new Javascript file (note it only affects files that have no boilerplate, Javascript and generic "new file" like sass, json etc)

Try the same with Soft Wrap off

Also try and open the previously created javascript file you tried to create with Soft Wrap on.

**Comment by davidwindell** [comment]
This can be reproduced in 6.0.0-M4 also.

**Comment by slemeur** [comment]
Thanks for reporting this issue @digiltd. 

FYI @vparfonov

**Comment by AndrienkoAleksandr** [comment]
Related issue: https://github.com/eclipse/che/issues/5189
It's Orion editor bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=354435 . Current Orion is 14.  I will check Orion 17. If this issue is still not resolved we are blocked.

**Comment by digiltd** [comment]
I think they are separate issues. Granted my browser crashed when I reproduced #5189, but it did so with soft wrap both off and on.
