### ISSUE TITLE
Is multithreading debug available in che?

### ISSUE THREAD

**Issue by Antossio** [eclipse-che/che#837]
Hello,
I want to ask if is it possible to debug all threads in the java program? I've tried to debug both the console and the swing desktop application, but Remote debug mode finished when main thread reaches the end and doesn't step to other threads. So, I can't understand if I'm doing something wrong, or there is no such possibility in che debug.

Thank you in advance.

**Comment by TylerJewell** [comment]
@tolusha is the engineer that has done most of our distributed debugger work.  He would be the best one to comment here.  I know that he is working on adding gdbserver support to enable the debugger to work across a wide degree of languages with the same usability.  I think some of that work just got merged in.

**Comment by tolusha** [comment]
Hello.
Currently che supports debugging only for current single thread.
Support switching between threads is expected in new versions.

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/2611
