### ISSUE TITLE
InstallerRegistryService is not protected with permissions

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#8370]
### Description
InstallerRegistryService is not protected with permissions. It means that every user is able to update/create/delete installer for the system. But there should be limitations only for admins.

### Reproduction Steps
1. Login to MultiUser Che with non-admin user.
2. Try to update installer
Expected: The action is forbidden
Actual: Installer is updated successfully.

**OS and version:**    

**Diagnostics:**

**Comment by mshaposhnik** [comment]
Done;
