### ISSUE TITLE
Question: Why not use Unison SSH instead of SSHFS?

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#8379]
Looking at https://github.com/eclipse/che/blob/master/dockerfiles/mount/entrypoint.sh

Just trying to get my head around why sshfs is combined with unison and direct unison ssh mode wasn't used like so?

 ` unison testunison ssh://user@my-che-server.com:36470//projects/testunison`

**Comment by davidwindell** [comment]
PIng @benoitf

**Comment by davidwindell** [comment]
@TylerJewell any chance you could recall why you chose this route?

**Comment by TylerJewell** [comment]
Ping @benoitf - my mental model is fuzzy here....

**Comment by davidwindell** [comment]
In a gitlab issue about IDEs @TylerJewell said that che-mount was:

`A desktop-based docker container for mac / windows / linux which runs sshfs + unison with a host volume mount. It connects to a remote SSH environment, synchronizes the content into the host container, which then moves it onto the host volume.`

I'm trying to understand why sshfs is used at all, it doesn't seem necessary to mount the remote into the container before syncing to the host mount when unison can do that directly.

**Comment by eivantsov** [comment]
I don't have an answer. Maybe @JamesDrummond has?

**Comment by JamesDrummond** [comment]
@eivantsov Been awhile for me to. I think unison would work without needing sshfs. Would probably be an improvement letting unison handle the ssh connection itself. This would eliminate the need to copy files in the container I think.

@davidwindell Are you able to run anything testing using unison directly?

**Comment by davidwindell** [comment]
Yep, all [works fine](https://github.com/outeredge/che-sync/blob/master/entrypoint.sh) for us without the need for sshfs.

I'd look at doing a PR but currently, che mount is completely broken (since v6 multi-user) #8569
