### ISSUE TITLE
Hello All,

### ISSUE THREAD

**Issue by ShivaniBali** [eclipse-che/che#8381]
I am facing issue on running eclipse Che via docker 
 

### Reproduction Steps

**OS and version:**    MAC 10 +

**Diagnostics:**

**Comment by ghost** [comment]
@ShivaniBali please take edit your issue to add details on what exact issue do you face otherwise it will be closed.

**Comment by ShivaniBali** [comment]
I got the below response when I use : eclipse/che:nightly version:

INFO: (che start): Starting containers...
INFO: (che start): Services booting...
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Booted and reachable
INFO: (che start): Ver: nightly
INFO: (che start): Use: http://localhost:8080
INFO: (che start): API: http://localhost:8080/swagger
Shivanis-MBP:~ shivanibali$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                              NAMES
a26cd2d83e81        eclipse/che-server:nightly   "/entrypoint.sh"         2 minutes ago       Up 2 minutes        8000/tcp, 0.0.0.0:8080->8080/tcp   che

And Image is being created.

Please let me know is this the right way  I am doing it?
Thanks!

**Comment by ghost** [comment]
Yes, it looks like everything's ok. Go to localhost:8080 in your browser

**Comment by ShivaniBali** [comment]
yea, does it mean like on hitting the above command, need to just open the localhost, because eclipse che directly opens up on the browser. 

I am new to this, so could not assure if its right.

thanks!

**Comment by ghost** [comment]
Yes, open `localhost:8080` in your browser.
