### ISSUE TITLE
eclipse che is support jetty project?

### ISSUE THREAD

**Issue by wuyurong** [eclipse-che/che#8384]
### Description
 
my project is build by jetty , I want to use eclipse che to run my project , It has been trying for a long time, but it failed. 
As shown in the following figure，I have a port (8087) in local Adress ,But foreign adress is *，I donot know how to visit my project.

![image](https://user-images.githubusercontent.com/11847116/35214303-bd60d834-ff9b-11e7-9eac-9056a44ae10d.png)

**Comment by ghost** [comment]
@wuyurong sharing more information will definitely help others help you. Please, update your issue accordingly

**Comment by ghost** [comment]
@wuyurong maybe this page can help you https://www.eclipse.org/che/docs/6/che/docs/servers.html

**Comment by dihlorfos** [comment]
reopen please

**Comment by dihlorfos** [comment]
I cannot see jetty stack in the list of stacks. Is it possible to add one?
