### ISSUE TITLE
eclipse che how to appoint Foreign Address

### ISSUE THREAD

**Issue by wuyurong** [eclipse-che/che#8385]
hi，all
I have a project build by jetty，when run the project ,need to appoint foreign address，how do it？

**Comment by ghost** [comment]
@wuyurong not exactly a Che question, but here you go https://www.eclipse.org/jetty/documentation/9.4.x/quickstart-config-what.html

**Comment by wuyurong** [comment]
@eivantsov my jetty project is run sucessful in eclipse ,but failed in eclipse che. the log As shown in the following figure，I have a port (8087) in local Adress ,But foreign adress is *，I donot know how to visit my project.

![image](https://user-images.githubusercontent.com/11847116/35215363-fb6c5a42-ff9e-11e7-94a9-6a16f22cbd47.png)

**Comment by ghost** [comment]
@wuyurong you need to add server to your workspace with port 8087 and then use generated preview URL. Your process is running in a docker container, and ports are exposed and published to a random ports from the ephemeral port range.

https://www.eclipse.org/che/docs/6/che/docs/servers.html

**Comment by wuyurong** [comment]
@eivantsov Thank you for your reply，after read the servers.html，found my eclipse che cannot add a server，as shown in the following figure. Is it related to the way I install it？the way is followed by this:
http://blog.csdn.net/ccfeng2008/article/details/50881024

![123](https://user-images.githubusercontent.com/11847116/35253624-637c4e80-0021-11e8-9908-bd0dd931582e.png)

**Comment by ghost** [comment]
@wuyurong you seem to have a very old Che version. Can you follow docs here https://www.eclipse.org/che/docs/6/che/docs/docker.html?

**Comment by wuyurong** [comment]
ok，I know，thank you very much. @eivantsov
