### ISSUE TITLE
Using CLI mapping the local repo/assembly , I can't see my IDE estension 

### ISSUE THREAD

**Issue by dorinburcea** [eclipse-che/che#8386]
### Description

Hi, I am trying to create an extension plugin for Che IDE menu customizationb , using the reference doc https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html

**GENERATE:**
mkdir /tmp/archetype
mkdir /tmp/data
docker run -it --rm  \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ~/archetype:/archetype \
  -v ~/data:/data \
  -v ~/.m2/repository:/m2 \
  -v /etc/group:/etc/group:ro \
  -v /etc/passwd:/etc/passwd:ro \
  --user=0:0 \
  --group-add 112 \
    eclipse/che-cli:6.0.0-M4 \
      archetype generate --archversion=6.0.0-M2 --group=com.mygroup

The above command successfully create the archetype with assembly and plugin folder structure for the "plugin-menu-archetype" sample menu. 

**BUILD:**

docker run -it --rm  \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ~/archetype:/archetype \
  -v ~/data:/data \
  -v ~/:/home/$USER/ \
  -v /etc/group:/etc/group:ro \
  -v /etc/passwd:/etc/passwd:ro \
  --user=0:0 \
  --group-add 112 \
  -w /archetype/assembly \
    eclipse/che-dev \
      mvn clean install
The above command build successfully and generate the tomcat .war files

**RUN:**

Option 1:
docker run -it --rm  \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ~/archetype:/archetype \
  -v ~/data:/data \
  -v /etc/group:/etc/group:ro \
  -v /etc/passwd:/etc/passwd:ro \
  --user=0:0 \
  --group-add 112 \
    eclipse/che-cli:6.0.0-M4 \
      archetype run
Option 2:
docker run -it --rm --name run-che \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /tmp/data:/data \
           -v ~/archetype/assembly/assembly/assembly-main/target/eclipse-che-6.0.0-M4/eclipse-che-6.0.0-M4:/assembly \
              eclipse/che-cli:6.0.0-M4 start --skip:nightly

Executing run of my archetype with both Option 1 and 2 the che-server says starts from local assembly and docker -f logs che shows no errors.

**RESULTS:**

Starting che as SINGLE user:
docker run -it --rm --name run-che \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v ~/data:/data \
           -v ~/archetype/assembly/assembly/assembly-main/target/eclipse-che-6.0.0-M4/eclipse-  che-6.0.0-M4:/assembly \
              eclipse/che-cli:6.0.0-M4 start --skip:nightly
The above command works fine and opening the IDE I can see the "Sample" menu item

Starting che as MULTI USER

docker run -it --rm --name run-che \
           -e CHE_MULTIUSER=true \
           -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://xxx.xxx.xxx.xxx:5050/auth \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v ~/data:/data \
           -v ~/archetype/assembly/assembly/assembly-main/target/eclipse-che-6.0.0-M4/eclipse-che-6.0.0-M4:/assembly \
              eclipse/che-cli:6.0.0-M4 start --skip:nightly
The above command works fine without che-server start errors

However, after opening a new workspace the IDE  I got  this error during the loading progress bar:

_IDE Initialization failed
org.eclipse.che.api.promises.client.OperationException: org.eclipse.che.api.promises.client.OperationException: Unable to load user's profile: java.lang.Exception: 403 http://xxx.xxx.xxx.xxx:8080_

Please help me to understand what I am missing.

**Comment by ghost** [comment]
@dorinburcea updated docs:

https://www.eclipse.org/che/docs/6/che/docs/ide-extensions-gwt.html
And a sample extension:
https://github.com/che-samples/che-plugin-menu

**Comment by dorinburcea** [comment]
@eivantsov Thank you for the updated docs. Tried the sample ext. now works fine! .
The issue can be closed.
