### ISSUE TITLE
Event workspace/didChangeWatchedFiles doesn't work after workspace restarting

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#8399]
### Description
 
Have no  workspace/didChangeWatchedFiles events for existing project if the workspace was restarted.

### Reproduction Steps

1. Create Maven sample project;
2. Stop/Start workspace;
3. Edit some class or pom.xml.

Don't get modified events in `org.eclipse.che.api.languageserver.registry.LanguageServerFileWatcher`

**Comment by tsmaeder** [comment]
@svor what is the case where you DO get those notfications?

**Comment by svor** [comment]
@tsmaeder just seen it in the debug mode. When I try to change pom.xml `workspace/didChangeWatchedFiles` should be fired and jdt.ls (in my case `MavenBuildSupport`) should update a project.
