### ISSUE TITLE
Bad Dockerfile link on website

### ISSUE THREAD

**Issue by lqueryvg** [eclipse-che/che#840]
The "Suggest Edits" link on eclipse-che.readme.io brought me here.

https://eclipse-che.readme.io/docs/usage-docker#using-docker-syntax
Under section "Using Docker Syntax"

It says:

  We provide a Docker image and Dockerfile that has Ubuntu, ...

... where "Dockerfile" is a link to:
  https://github.com/eclipse/che/blob/4.0/Dockerfile

this doesn't exist.

**Comment by TylerJewell** [comment]
Thanks - should have pointed to here.
https://github.com/eclipse/che/blob/master/Dockerfile
