### ISSUE TITLE
Is white labeling still supported?

### ISSUE THREAD

**Issue by levjason** [eclipse-che/che#8404]
### Description
 
The Che 5 documentation had instructions for white labeling Che.  Does Che 6 support white labeling
and is it somewhere in the documentation? For example we'd like to change the colors, use our own bitmap in place of the standard Che bitmap, and remove the buttons in the lower right corner of the dashboard.

**Comment by ghost** [comment]
@levjason in Che 5 you still had to move ide modules to provide own colors. As to changing logos, it should be still possible, as well as removing buttons. You need to look at https://github.com/eclipse/che/tree/master/plugins/plugin-product-info

**Comment by levjason** [comment]
@eivantsov Can we change the dashboard colors and fonts without modifying Che source? Thanks.

**Comment by ghost** [comment]
@levjason no, as far as I know. @ashumilova can keep me honest though

**Comment by ashumilova** [comment]
@levjason the customizable stuff is defined here https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/product.json
and footer buttons are also removed by removing the items from the json above (help, support)

**Comment by ghost** [comment]
@ashumilova but it means modifying source, not overriding with a plugin. I think this is what @levjason means

**Comment by ashumilova** [comment]
That's about the white labeling that is described in docs for che 5, same here in che 6. And about changing the stuff without modifying Che source - no, do not have that.

**Comment by levjason** [comment]
@eivantsov @ashumilova   Yes, we'd like to change the fonts and colors as well without modifying Che source. We had to modify Che 5 source to change the fonts and colors and we had to remove those changes in order to migrate to Che 6.

**Comment by levjason** [comment]
I'll submit a feature request for this. Thanks.
