### ISSUE TITLE
Add che-samples to CI build & release

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#8420]
Following samples need to be added to CI build and set up for releasing:

Repo: | CI | Release
------------ | ------------- | -----------
https://github.com/che-samples/che-plugin-menu | ✅   | ✅
https://github.com/che-samples/che-plugin-wizard | ✅ | ✅
https://github.com/che-samples/che-plugin-json | ✅ | ✅
https://github.com/che-samples/che-plugin-embedjs | ✅ | ✅

**Comment by riuvshin** [comment]
Done
