### ISSUE TITLE
Feature Request:  Make it possible to override  dashboard fonts and colors

### ISSUE THREAD

**Issue by levjason** [eclipse-che/che#8421]
Feature Request: Some parts of Che can be white labeled. But its not possible to override the colors and fonts in the Dashboard without modifying Che source. Modifying the source makes it very difficult to migrate to newer versions of Che. This is a request to include an option to change the default colors and fonts in the Dashboard without modifying the Che source.  See #8404

**Comment by skabashnyuk** [comment]
@slemeur @ashumilova can you comment?

**Comment by slemeur** [comment]
That is something that is not possible at this moment. But we would need to keep this in mind when we will start bigger effort on Che Dashboard.

With the new version of Eclipse Che 7, there will be some adaptation which will be needed to the dashboard - and it will be important to make it extensible to a certain degree. I agree that being able to replace the logo, the font and the color theme would be great. It could be the introduction of Themes for dashboard, with the ability to create a new one.
