### ISSUE TITLE
Issue in flux installation : Docker

### ISSUE THREAD

**Issue by ShivaniBali** [eclipse-che/che#8423]
Hello,

Hello Sir, I tried using flux docker commands, but I am not able to install flux, just because apt-get / apt-key packages are not being installed. I tried Macports and home-brew. it doesn't work. Please help me to install it correctly.

PS: I tried adding admin rights in sudoers. Nothing worked.

2 Ways with MacPorts:

Shivanis-MBP:~ shivanibali$ port install apt-key
Error: Insufficient privileges to write to MacPorts install prefix.
Shivanis-MBP:~ shivanibali$ sudo port install apt-key
Error: Port apt-key not found

And may I know is this package not supported in Homebrew, as I installed home-brew then I installed package for wget, it worked. But there is no package available for "brew install apt-key" or "brew install apt-get".

Looking forward to hear from you!

Thank you!

**Comment by ghost** [comment]
@ShivaniBali this is Eclipse Che project. I think it's the wrong place to post this question. Is it somehow related to Eclipse Che?

**Comment by ShivaniBali** [comment]
hello Sir, 

yea I was trying to perform pair programming with eclipse che. However for that I need to install flux before. But during that installation I was facing a lot of command line issues.

For which I am able to install related backgrounds for flux. 

Thanks for coming back on this.!

**Comment by ShivaniBali** [comment]
@eivantsov : I have a question for eclipse che, are we allowed to create a UI interface from scratch on eclipse che and perform peer programming on it?

Hoping to hear back from you!

Thanks!

**Comment by ghost** [comment]
@ShivaniBali if you are asking if Che license allows it, then the answer is yes. You can modify and distribute Che.

**Comment by ShivaniBali** [comment]
Ok, thank you!

**Comment by sunix** [comment]
@ShivaniBali futur of pair programming in Che will not use Eclipse Flux. We plan to use Atom Teletype, stay tuned.

**Comment by ShivaniBali** [comment]
@sunix awsum, as I have to develop a webversion of JucmNav using Eclipse Che. So possibly I will be using pair programming with my partner. When can we expect the advanced use of Che with Atom?

thank you!

**Comment by sunix** [comment]
Not sure when but we are working on it :)

**Comment by ShivaniBali** [comment]
@sunix Cool :)
