### ISSUE TITLE
Create workspace failed on OpenShift: Name for persistent volume too long 

### ISSUE THREAD

**Issue by jaxx0r** [eclipse-che/che#8439]
I have successfully deployed Che 6.0.0-M5-SNAPSHOT on Red Hat OpenShift Container Platform 3.7, but creating a workspace always fails in my setup.

Root cause is that the persistent volume for the storage of the dev machine can not be provisioned. I am using GlusterFS (Container Native Storage) with dynamic provisioning as storage backend for OpenShift. I can see the following event in OpenShift:

> _Failed to provision volume with StorageClass "gluster-container": glusterfs: create volume err: failed to create endpoint/service error creating service: Service "glusterfs-dynamic-claim-che-workspace-workspaceb2jggx3x4a0138v8-projects" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-claim-che-workspace-workspaceb2jggx3x4a0138v8-projects": must be no more than 63 characters_

Unfortunately the prefix "glusterfs-dynamic-" is always added in this kind of setup which leads to 73characters total (which is too long for kubernetes).

Is there a way to modify the template for deploying a new workspace, to make the persistent volume name shorter (e.g. drop "claim-che-workspace" or "-workspace" )? Workspace ID plus "-projects" might be enough for a unique name?

**Comment by akorneta** [comment]
@jaxx0r As a temporary solution, you can change the [prefix](https://github.com/eclipse/che/blob/master/dockerfiles/init/manifests/che.env#L466) name to something shorter e.g. `che` instead of `claim-che-workspace` till we fix that.
