### ISSUE TITLE
Improve Debugger Menu: Make it possible to Choose between available debuggers

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#844]
It should be possible for a user to choose between available debuggers (Java debugger and Gdb). Once chosen, a user should be able to specify host and port.

In case of gdb, one should be able to provide a path to a binary file.

**Comment by TylerJewell** [comment]
I don't think the type of debugger should be a Ux choice.  To the end user all debugging ports are the same and would not be chosen differently in the menu.
