### ISSUE TITLE
Add ability to provide github personal access token into selenium configuration

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#8442]
### Description
Sometimes selenium tests may failure due to rate limit. In this case docs provide the information to set up own login and password:

https://github.com/eclipse/che/tree/master/selenium/che-selenium-test#2-add-configuration-file

where described: 

>Set CHE_LOCAL_CONF_DIR environment variable and point to the folder where selenium tests configuration will be stored. Create file selenium.properties in that folder with the following content:

```
...
# GitHub account credentials
github.username=<MAIN_GITHUB_USERNAME>
github.password=<MAIN_GITHUB_PASSWORD>
...
```

this case won't work when user has configured two factor authorization. Selenium tests will fail with exception:

`org.eclipse.che.api.core.UnauthorizedException: Must specify two-factor authentication OTP code.`

Setting up a personal access token instead of password also won't work, because selenium tests uses Basic type authorization:

`org.eclipse.che.api.core.ForbiddenException: This API can only be accessed with username and password Basic Auth`

What I propose is to check, when user sets up a hash in password field then use token based authorization:

https://developer.github.com/v3/auth/#via-oauth-tokens

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/21)

**Comment by rhopp** [comment]
We are not investing more time in old selenium tests suite. If the same issue happens with Happy Path tests, we'll reopen this one. Until then, I'm closing this issue.
