### ISSUE TITLE
Preview URL not Generated in OpenShift

### ISSUE THREAD

**Issue by kameshsampath** [eclipse-che/che#8456]
### Description
When deploying a Spring Boot application with Che deployed on OpenShift, its observed that the preview URL does not include the proper host name.

See attachment for reference

### Reproduction Steps
1. Create workspace using Che factory, with the project at https://github.com/skshiftio/demo03 
2. Once the workspace is created, try executing run command 
3. you will see the preview url is broken as show in the screenshot
4. It is also seen that logs from cli is also truncated (refer to screenshots)

![preview-url-broken](https://user-images.githubusercontent.com/947745/35397989-ecab6e1a-0216-11e8-88af-21a3e2846515.png)
![no server process running or shown](https://user-images.githubusercontent.com/947745/35397977-e267c458-0216-11e8-9ca4-38420ca69e6f.png)
![logs truncated](https://user-images.githubusercontent.com/947745/35397980-e55049b0-0216-11e8-960d-a9defc40a213.png)

**Comment by musienko-maxim** [comment]
Can you provide please json from factory? Looks like incompatible macros parameter for getting server url.
As variant try to use `${server.tomcat8}` instead of `${server.port.8080}`

**Comment by riuvshin** [comment]
Yeah looks like in CHE6 some macro are changed format

**Comment by slemeur** [comment]
downgrading the severity

**Comment by ghost** [comment]
I'll cover that in compatibility guide

**Comment by ghost** [comment]
But it's not a bug. Just the right macro needs to be used. Or are we going to support old macros too?

**Comment by kameshsampath** [comment]
@musienko-maxim here is the factory json https://github.com/skshiftio/demo03/blob/master/.factory.json , i tried to fix 2 of them one is `installers` instead of `agents` in the workspace config  and now trying to use `server.tomcat8` for `server.port.8080`

**Comment by kameshsampath** [comment]
@musienko-maxim @eivantsov I don't think the macro `${server.tomcat8}` works I am again seeing the same issue see the screenshot, we should have command that can list all the macros, i doubt we have them in docs. Check the updated  .factory.json https://github.com/skshiftio/demo6/blob/master/.factory.json#L76

<img width="1487" alt="screenshot 2018-01-26 00 45 13" src="https://user-images.githubusercontent.com/947745/35407531-471ffc2e-0232-11e8-87f3-72749749b2d8.png">

**Comment by ghost** [comment]
You need to add tomcat8 server then....

**Comment by skshiftio** [comment]
thanks @eivantsov I was able get the right preview url with macro ${server.tomcat8} and was need to add the `servers` section to workspace config. Also one thing I noted is that the ${server.tomcat8} macro does return with `http://` so preview urls done need to suffix them. 

Thanks @musienko-maxim @slemeur @riuvshin @eivantsov  for help.

you can find the working .factory.json here 

* https://github.com/skshiftio/demo9/blob/master/.factory.json#L12-L25
* https://github.com/skshiftio/demo9/blob/master/.factory.json#L89

<img width="1160" alt="screenshot 2018-01-26 16 49 04" src="https://user-images.githubusercontent.com/31317059/35437546-dfb7f3a2-02b8-11e8-8a46-5c676fd3e087.png">

**Comment by slemeur** [comment]
Closing the issue as it has been resolved
