### ISSUE TITLE
Errors in the browser console when importing the eclipse-che project

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8459]
**Reproduction Steps:**
1. Start a workspace from the **Java** stack.
2. Menu **Workspace** -> **Create Project**.
3. Import the **eclipse-che** project.

**Observed behavior:**
There are "**org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher
SEVERE: No corresponding to method 'importProject/progress' handler is registered**" errors in the browser Console.

**OS and version:**
Che 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
![eclipse che wksp-51ec - google chrome_144](https://user-images.githubusercontent.com/7760565/35399060-14b04392-01fc-11e8-859a-d78847b205d2.png)

![nimbus-record-video-2018-01-25-18-08-44](https://user-images.githubusercontent.com/7760565/35399040-096025d4-01fc-11e8-97db-3eea5ec167f1.gif)

**Comment by SkorikSergey** [comment]
Cannot import this project on OCP:
![eclipse che wksp-98to - google chrome_145](https://user-images.githubusercontent.com/7760565/35432195-f301ce5a-0287-11e8-8951-0bf4016b4491.png)

**Comment by artaleks9** [comment]
This bug was reproduced on the multiuser-ocp platform, version 6.7.0

**Comment by vinokurig** [comment]
Probably updating to JGit v5 will help: https://github.com/eclipse/che/issues/10260

**Comment by musienko-maxim** [comment]
Cannot reproduce on ocp-multiuser platform with CHE-6.8.0 snapshot:
![selection_024](https://user-images.githubusercontent.com/1640058/42277497-3b281258-7fa0-11e8-96ef-bf1f681cf3d9.png)
