### ISSUE TITLE
Unexpected failing of NavigateToFileTest selenium test on CI 

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8465]
### Description
We have unexpected fail of **NavigateToFileTest** selenium test. The test sometimes fails on CI when waiting suggestion list with found files from the **Navigate To File** feature. We should clarify reason and fix it.

**Log:**
```
org.openqa.selenium.WebDriverException: 
unknown error: Element <td style="opacity: 0.6;">...</td> is not clickable at point (895, 300). Other element would receive the click: <div class="GIWAMGHBPOB" style="right: 0px; bottom: 0px; position: absolute; left: 0px; top: 0px;">...</div>
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.16.1.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 129 milliseconds
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: 'bf642ff2277b', ip: '172.18.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.zvskk5}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 33994dcb-678a-4b12-adc2-a997bfb381c4
	at org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.launchNavigateToFileAndCheckResults(NavigateToFileTest.java:149)
	at org.eclipse.che.selenium.miscellaneous.NavigateToFileTest.shouldNavigateToFileWithJustCreatedFiles(NavigateToFileTest.java:107)```
```
Screenshot:
![org eclipse che selenium miscellaneous navigatetofiletest shoulddonavigatetofileforsecondproject_w4x5hl6w](https://user-images.githubusercontent.com/7760565/34935870-055e2b46-f9e8-11e7-986b-e07d584c9f16.png)

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/145/Selenium_tests_report/

**Comment by SkorikSergey** [comment]
Try to get more information about this issue by starting **NavigateToFileTest** selenium test from https://github.com/eclipse/che/tree/makeScreenshotBeforeItemSelectingNavigateToFileTest branch on.

**Comment by musienko-maxim** [comment]
We've found that previews data which was found by NavigateToFileTest are not cleared from DOM. It may be reason of the problem. @vparfonov will try to implement    the mechanonzm of clearing previews data ant this ona may fix the problem

**Comment by SkorikSergey** [comment]
https://github.com/eclipse/che/issues/8293 reopened.

**Comment by SkorikSergey** [comment]
This issue is still reproduced.

**Comment by vzhukovskii** [comment]
Issue can't be reproduced manually and via selenium testing on local machine.

**Comment by musienko-maxim** [comment]
I suspect that problem may be reproduced under specific loading (processor, IO, filesystem). For start a try to load network by load - instrument (Jmeter) and reproduce it again.
