### ISSUE TITLE
Adapt selenium tests for JDT LS

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#8466]
### Description
 
Make it possible to run selenium tests in the jdt.ls branch.
- [x] Apply jdt.ls in the test work-spaces.
- [x] Wait for the jdt.ls is loaded in all tests where it is needed.
- [x] Create `.classpath` and `.project` files when importing not a maven project.

**Comment by tsmaeder** [comment]
@vinokurig "Adopt" or "Adapt"?

**Comment by vinokurig** [comment]
@tsmaeder fixed
