### ISSUE TITLE
Command Editor fails to properly initialize its Dirty state after it's saved

### ISSUE THREAD

**Issue by vrubezhny** [eclipse-che/che#8475]
### Description
 

When editing the list of projects a command is to be applied to, the Command Editor fails to properly calculate the "Dirty" state and enablement of "Save" button.

Steps to reproduce may vary depending on the user actions that are done before the "Save" button is clicked, but despite of that the issue remains highly reproducible.

### Reproduction Steps

- Create the first Project (ProjectOne)
- Create the second Project (ProjectTwo)
- Create a Run->Java Command 
  ASSERT: Command Editor is opened and has both the projects listed and selected as applicable in its "Apply to" panel
- Deselect ProjectOne 
  ASSERT: The editor has "Dirty" state and "Save" button is enabled
- Save the changes by clicking the "Save" button
  ASSERT: The editor has "Not Dirty" state and "Save" button is disabled
- Select ProjectOne 
  ASSERT FAILED! The editor still has "Not Dirty" state and "Save" button disabled while it should be "Dirty" and able to  be saved.

![che8475](https://user-images.githubusercontent.com/620781/35439122-a6b17692-0299-11e8-8916-253b77ce583a.gif)

**OS and version:**    

**Diagnostics:**

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che/pull/8781
