### ISSUE TITLE
Bug with closing tabs in processes panel

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#8479]
### Description
 

Nothing is selected when closing a tab in processes panel.

![close-tab](https://user-images.githubusercontent.com/1655894/35441379-021830ea-02ac-11e8-8600-08a04ab362a4.gif)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by RomanNikitenko** [comment]
It's duplicated https://github.com/eclipse/che/issues/8272
