### ISSUE TITLE
NPM global packages work in terminal, but not as a command

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#8486]
### Description

Attempts to use a NPM package installed globally within a command fails.

##### The easiest way: 

- Use the Dockerfile at 51234/nodeeight as a source for the machine

![image](https://user-images.githubusercontent.com/4656027/35445751-2fdfb91e-0278-11e8-8a7d-6a01d7f4887f.png)

- Open and run the workspace.

- In the terminal run `npm-gui'

![image](https://user-images.githubusercontent.com/4656027/35445948-dfd83292-0278-11e8-99e1-442eeaf4130a.png)

- Create a command called "NPM-GUI" with a command line entry of `cd ${current.project.path} && sudo npm-gui` and preview of `${server.NPM-GUI}`

![image](https://user-images.githubusercontent.com/4656027/35446055-2a6919ca-0279-11e8-9db5-8d7d47939ad4.png)

- Result: 

![image](https://user-images.githubusercontent.com/4656027/35446107-5435f070-0279-11e8-94cc-fb7541aa2981.png)

##### What I believe is important to reproducing this:

Create a dockerfile that uses [NVM](https://github.com/creationix/nvm) to utilize the current LTS version of node as of [1/26/2018](https://web.archive.org/web/20180126064823/https://nodejs.org/en/), 8.9.4. The dockerfile should also install a global package usable from the terminal such as NPM-GUI, pug-cli, or speedtest-net.

##### Why use NVM ?

When I initially, lazily created a dockerfile to use Node 8 by simply changing the [eclipse/node](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/node/Dockerfile) dockerfile from `RUN wget -qO- https://deb.nodesource.com/setup_7.x | sudo -E bash -` to `RUN wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -` there were issues running `npm i`. All npm commands failed unless ran as `sudo` with an EACCESS error.

I wasn't concerned with with the sudo problem until I was unable to install [puppeteer](https://github.com/GoogleChrome/puppeteer) even as `sudo.`

This problem doesn't appear to be present in the eclipse/node image.

![image](https://user-images.githubusercontent.com/4656027/35447129-7a56153e-027c-11e8-9c9c-3e121769379c.png)

**OS and version:**   

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Che Version: 6.0.0-M4 - using docker 17.05.0-ce

**Diagnostics:** 

Above in images

**Comment by gnoejuan** [comment]
Here is the workspace as a file

```
{
  "environments": {
    "default": {
      "recipe": {
        "contentType": "application/x-yaml",
        "type": "compose",
        "content": "services:\n dev-machine:\n  image: 51234/nodeeight\n"
      },
      "machines": {
        "dev-machine": {
          "env": {},
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh",
            "org.eclipse.che.ls.js-ts"
          ],
          "volumes": {},
          "servers": {
            "3000": {
              "attributes": {},
              "protocol": "http",
              "port": "3000"
            },
            "5000": {
              "attributes": {},
              "protocol": "http",
              "port": "5000"
            },
            "9000": {
              "attributes": {},
              "protocol": "http",
              "port": "9000"
            },
            "NPM-GUI": {
              "attributes": {},
              "protocol": "http",
              "port": "1337"
            }
          },
          "attributes": {
            "memoryLimitBytes": "2147483648"
          }
        }
      }
    }
  },
  "projects": [
    {
      "description": "hello",
      "source": {
        "location": "https://github.com/che-samples/web-nodejs-sample.git",
        "type": "git",
        "parameters": {}
      },
      "mixins": [
        "pullrequest"
      ],
      "problems": [],
      "name": "HelloWorld",
      "type": "node-js",
      "path": "/HelloWorld",
      "attributes": {
        "contribute_to_branch": [
          "master"
        ],
        "commands": [
          "{\"commandLine\":\"cd /projects/HelloWorld \\nnode app/app.js\", \"name\":\"HelloWorld: run\", \"attributes\":{\"previewUrl\":\"${server.3000/tcp}\", \"goal\":\"Run\"}, \"type\":\"custom\"}",
          "{\"commandLine\":\"echo \\\"hello\\\"\", \"name\":\"newCustom\", \"attributes\":{\"goal\":\"Deploy\", \"previewUrl\":\"\"}, \"type\":\"custom\"}"
        ]
      }
    }
  ],
  "commands": [
    {
      "commandLine": "cd{$current.project.path} && bower-browser --port 1337",
      "name": "Bower-Browser",
      "type": "custom",
      "attributes": {
        "previewUrl": "${server.1337}"
      }
    },
    {
      "commandLine": "cd ${explorer.current.file.parent.path} && live-server --port=9000",
      "name": "live-server",
      "type": "custom",
      "attributes": {
        "goal": "Run",
        "previewUrl": "${server.9000}"
      }
    },
    {
      "commandLine": " cd ${current.project.path} && npm run dev",
      "name": "Webpack Dev",
      "type": "custom",
      "attributes": {
        "goal": "Run",
        "previewUrl": "${server.9000}"
      }
    },
    {
      "commandLine": "cd ${current.project.path} && npm-gui",
      "name": "NPM-GUI",
      "type": "custom",
      "attributes": {
        "previewUrl": "${server.NPM-GUI}"
      }
    }
  ],
  "defaultEnv": "default",
  "name": "wksp-gysh"
}
```

**Comment by ghost** [comment]
@gnoejuan here you go

`source ~/.nvm/nvm.sh && cd ${current.project.path} && npm-gui

When you enter a terminal nvm script is sourced automatically, while commands are detached.

![image](https://user-images.githubusercontent.com/5337267/35457711-22074a5c-02da-11e8-92b2-b7a2d8216467.png)

**Comment by gnoejuan** [comment]
Seriously, many thanks!
