### ISSUE TITLE
Stopping of inactive workspaces by timeout doesn't work in Eclipse Che

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8487]
### Reproduction Steps
There are two Eclipse Che properties:
- [CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS](https://github.com/eclipse/che/blob/6.0.0-M4/dockerfiles/init/manifests/che.env#L149);
- [CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT](https://github.com/eclipse/che/blob/6.0.0-M4/dockerfiles/init/manifests/che.env#L618).

Setting them to non-zero values don't lead to stopping idle workspaces by timeout set by these variables.
Possible reason is that [WorkspaceActivityNotifier](https://github.com/eclipse/che/blob/6.0.0-M4/plugins/plugin-activity/che-plugin-activity-server/src/main/java/org/eclipse/che/plugin/activity/WorkspaceActivityNotifier.java#L29) is calling [WorkspaceActivityService](https://github.com/eclipse/che/blob/6.0.0-M4/plugins/plugin-activity/che-plugin-activity-wsmaster/src/main/java/org/eclipse/che/plugin/activity/WorkspaceActivityService.java#L65) by schedule and it makes idle (inactive) workspace kind active.

**OS and version:**    
Tested on Multiuser Eclipse Che ver. 6.0.0-M5-SNAPSHOT, docker infrastructure

**Comment by mshaposhnik** [comment]
Fixed;
