### ISSUE TITLE
Need to know how to secure access to Che

### ISSUE THREAD

**Issue by RobertBrown3** [eclipse-che/che#8488]
I have installed the latest Che (multi- user installation) on a test server using the docker command described in the documentation. I am accessing it using the web page.

There are several problems I am encountering. These are security- related.

The first problem I am seeing is that the application displays a login page. This would nt be a problem, except that there are no usernames or passwords set up (that I am aware of) for logging in. The documentation does not talk about default usernames or passwords, and provides no description of administrative usernames or passwords set by default.

The second problem is that the web page offers the ability for anyone without a username or password to "register" as a user. This concerns me, because when I deploy this over the Internet I do not want any somebody who finds my URL to be able to create an account on my development system.

The third problem is generic: going through the documentation, there doesn't appear to be any documentation on how to administer the Che installation. In particular, there is apparently nothing on how to set up users on the system. I see plenty of user documentation on how to set up and use workspaces, and I see a lot on how the Che authentication/authorization system works, but not how to use it. 

Is there any documentation on how to set and configure Che security? In particular, I need to know the following:

1. Is there an administrative username/password set up by Che so that a new administrator can configure the security?

2. Does the administration system allow for disabling Registration on a Che system in order to prevent any random person from creating an account? If there is, how do I engage it?

3. In general, how does an administrator manage users in this system?

If the documentation I need here does not exist, how do I do the things I need?

**Comment by ghost** [comment]
@RobertBrown3 Che 6 docs are on the way - they are temporarily published here https://www.eclipse.org/che/docs/6/che/docs/user-management.html

`admin:admin` is the default username/password for a Keycloak admin. When in Keycloak, you may configure user registration flow:

![image](https://user-images.githubusercontent.com/4285392/35497346-76f2d32a-04d2-11e8-907d-bd7ef8000d54.png)

But good point - even existing new docs may be a little bit more helpful. I'll issue a PR.

**Comment by RobertBrown3** [comment]
Thank you for the info and the link.

(Hopefully) quick questions:

(1) It looks like I successfully logged in using the default admin:admin, but the "dashboard" consists of a slowly blinking Che logo.  No menus or anything else, just a black space and the blinking logo. Have I actually successfully logged in or do I need to do something else? The documentation gives no indication of what to expect.

(2) I presume the Keycloak screen you showed me is the one accessible from my installation. There appears to be no description in the documentation on how to access it. I did install everything on Docker using:

docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=<my-external-ip>} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start

as described in the documentation (the command in the new documentation appears to be the same as the one in the old), so I didn't make any mistakes here).  I should have the keycloak stuff running -- or do I need to do something else to start it? How do I get to the screen you showed?

(3) Hopefully quick question: the documentation talks a lot about running workspaces in Docker containers. When creating workspaces, do we have to run seperate docker containers in order to use them?

**Comment by RobertBrown3** [comment]
It occurs to me: I should show what I see when I log in. The screen capture below shows what I see when I log in as admin (or anyone else):
![cheproblem](https://user-images.githubusercontent.com/13591779/35544775-09be5672-053a-11e8-97f9-c98718e34aa1.JPG)

**Comment by ghost** [comment]
@RobertBrown3 

1. Can you open browser console a share a screenshot? There must be some errors. You may also provide server logs and keycloak logs: docker logs -f che and docker logs -f ${keycloak_container}

2. Default Keycloak credentials are admin:admin. You can find your Keycloak URL either in OpenShift web console > keycloak namespace (if you deployed to OpenShift) of go to $CHE_HOST:5050/auth if Che is running on Docker.

That's from docs I have previously shared.

**Comment by RobertBrown3** [comment]
Greetings:

I believe I found the problem.

I am running things behind several firewalls (I really need to do that for several very good reasons!). I remember the last time I posted questions here my problem was related to a port that was not open. That was the case here.

I checked my logs and noticed failures to get keys due to the fact that my machine's Port 5050 was not open. I opened it and now I am getting the normal dashboard. From there, it was a short jump to accessing Port 5050 in order to see the Keycloak screen.

I mentioned this the last time I was here, and I respectfully mention it again: you guys *please* publish something that lists the ports that this system uses. You do talk about Port 8080, but had I known about Port  32768 before and Port 5050 this time it would have saved a lot of headache (for you as well as me). 

   Information about ports could be included in a document that addresses security (the documents I see, even now, talk about how the security is implemented but gives no real practical information about securing a Che deployment).

I stopped using Che before partly because of the poorly implemented (and poorly documented) security (there were other reasons, but that was a big one). I see a lot of improvements in just about everything since the last time I looked at Che, but I am still seeing holes -- mostly in the documentation which I am studying now with great interest. There is far more "how it works" than there is "how to make it work" in areas of concern, particularly where security is concerned.

Last couple of questions: are there any other ports that I will need to open in order to use this system? Also: Multi- user Che on Docker does not use SSL by default (I consider this a serious flaw, by the way!). Can you point me to some documentation that tells how to configure it (and Keycloak) so that it does?

BTW: if you folks are unable to include the kind of info I am talking about in your documentation, I am happy to do so. I like Che and would be happy to contribute useful documentation, like a step- by- step guide to securing a multi- user deployment.  Unfortunately, I first need to learn how to do this myself! Someone please advise.

**Comment by ghost** [comment]
https://www.eclipse.org/che/docs/6/che/docs/docker_openshift.html - http/https. Only OpenShift supports Che in https mode.

https://www.eclipse.org/che/docs/6/che/docs/docker.html#pre-requisites - ports

We'll improve docs with some clearer getting started guides. You can also contribute to docs - https://github.com/eclipse/che-docs

**Comment by RobertBrown3** [comment]
Thanks for the links.

   A small set of problems FYI: the list of ports lists Port 5000 as the Keycloak port. It should be 5050. Also: the port range for the Che agents is one that my firewall will not set. I was able to set a range close to the last port number, though. My Che system is now working without problems (so far).

   As for using https with Docker: I had heard that there were ways of setting up the servlet container so that it serves Che pages over SSL. I was hoping that someone could point me to documentation that would enable me to do this. I am, however, thinking that considering there is no official support for doing Che over SSL on Docker, and considering all the ports I have to have open in order to use Che, the best way to handle secure communication over the Internet is to run Che from within a VPN. I am going to work to set that up (can anyone give a reason why this can't/shouldn't be done?). If there is interest, I will document my setup when/if I have it working.

Anyway, thanks for the assistance. I will now learn how to play with this new toy! :-)
