### ISSUE TITLE
No corresponding to method 'track/git-change' handler is registered

### ISSUE THREAD

**Issue by andrew-mclachlan** [eclipse-che/che#8489]
### Description
When starting up new workspaces, "I get an error No corresponding to method 'track/git-change' handler is registered".

I get the error using my custom Stacks and the default develop Che stack.

### Reproduction Steps
``
docker run -it --rm -e CHE_HOST=192.168.1.232 -e CHE_DOCKER_IP_EXTERNAL=192.168.1.232 -v /var/run/docker.sock:/var/run/docker.sock -v /Users/amclach/LearningJavaScript/cheData:/data -v /Users/amclach/LearningJavaScript/che-assembly/assembly-che/assembly-main/target/eclipse-che-5.22.0/eclipse-che-5.22.0:/assembly eclipse/che:5.22.0 start --skip:nightly
``

**OS and version:**    
macOS Sierra.

**Diagnostics:** 
``
[STDOUT] 2018-01-28 09:12:50,642[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.11

[STDOUT] 2018-01-28 09:12:50,693[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Jan 10 2017 21:02:52 UTC

[STDOUT] 2018-01-28 09:12:50,700[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.11.0

[STDOUT] 2018-01-28 09:12:50,701[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux

[STDOUT] 2018-01-28 09:12:50,701[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.9.49-moby

[STDOUT] 2018-01-28 09:12:50,703[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64

[STDOUT] 2018-01-28 09:12:50,728[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_92/jre

[STDOUT] 2018-01-28 09:12:50,734[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_92-b14

[STDOUT] 2018-01-28 09:12:50,795[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation

[STDOUT] 2018-01-28 09:12:50,796[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent

[STDOUT] 2018-01-28 09:12:50,798[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent

[STDOUT] 2018-01-28 09:12:50,868[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties

[STDOUT] 2018-01-28 09:12:50,869[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager

[STDOUT] 2018-01-28 09:12:50,872[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m

[STDOUT] 2018-01-28 09:12:50,872[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m

[STDOUT] 2018-01-28 09:12:50,873[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom

[STDOUT] 2018-01-28 09:12:50,873[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs

[STDOUT] 2018-01-28 09:12:50,874[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO

[STDOUT] 2018-01-28 09:12:50,874[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/che/ws-agent/conf/tomcat-logger.xml

[STDOUT] 2018-01-28 09:12:50,876[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048

[STDOUT] 2018-01-28 09:12:50,894[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources

[STDOUT] 2018-01-28 09:12:50,895[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n

[STDOUT] 2018-01-28 09:12:50,896[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote

[STDOUT] 2018-01-28 09:12:50,907[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false

[STDOUT] 2018-01-28 09:12:50,922[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false

[STDOUT] 2018-01-28 09:12:50,989[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf

[STDOUT] 2018-01-28 09:12:50,990[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent

[STDOUT] 2018-01-28 09:12:50,990[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent

[STDOUT] 2018-01-28 09:12:50,992[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp

[STDOUT] 2018-01-28 09:12:52,016[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 525]  - Initializing ProtocolHandler ["http-nio-4401"]

[STDOUT] 2018-01-28 09:12:52,072[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read

[STDOUT] 2018-01-28 09:12:52,088[main]             [INFO ] [o.a.catalina.startup.Catalina 617]   - Initialization processed in 2342 ms

[STDOUT] 2018-01-28 09:12:52,254[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server

[STDOUT] 2018-01-28 09:12:52,262[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service Catalina

[STDOUT] 2018-01-28 09:12:52,263[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.11

[STDOUT] 2018-01-28 09:12:52,682[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 923]        - Deploying web application archive /home/user/che/ws-agent/webapps/ROOT.war

[STDOUT] 2018-01-28 09:12:58,988[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 59]      - Workspace ID: workspacejqjt9e01h48ao801

[STDOUT] 2018-01-28 09:12:58,999[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 60]      - API Endpoint: http://che-host:8080/wsmaster/api

[STDOUT] 2018-01-28 09:12:59,000[ost-startStop-1]  [INFO ] [o.e.c.a.p.s.WorkspaceHolder 61]      - User Token  : true

[STDOUT] 2018-01-28 09:13:01,868[ost-startStop-1]  [WARN ] [org.reflections.Reflections 180]     - given scan urls are empty. set urls in the configuration

[STDOUT] 2018-01-28 09:13:01,930[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 987]        - Deployment of web application archive /home/user/che/ws-agent/webapps/ROOT.war has finished in 9,246 ms

[STDOUT] 2018-01-28 09:13:01,944[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 570]  - Starting ProtocolHandler [http-nio-4401]

[STDOUT] 2018-01-28 09:13:01,974[main]             [INFO ] [o.a.catalina.startup.Catalina 668]   - Server startup in 9873 ms

[STDOUT] 2018/01/28 09:13:03 Start new terminal.

[STDOUT] 2018-01-28 09:13:04,120[equestProcessor]  [ERROR] [.e.c.a.c.j.c.RequestDispatcher 61]   - No corresponding to method 'track/git-change' handler is registered
``

**Comment by ghost** [comment]
@andrew-mclachlan a few words on your custom assembly will definitely make it easier for the community to help you. Ideally, push your assembly to GH repo.

**Comment by andrew-mclachlan** [comment]
Thanks @eivantsov. I'll see what I can do re: sharing our assembly. Our assembly is based on 5.22.0. I am trying a build of Che from [master] to see if I can reproduce the problem there. It could be that there is a new dependency needed between assembly and workspace agent(?)

**Comment by ghost** [comment]
@andrew-mclachlan btw you can disregard this error. This is fixed in 6.x version

**Comment by andrew-mclachlan** [comment]
Thanks @eivantsov. Meaning that the error isn't an issue when running with 5.22.0.
I can confirm that using the latest [master], I do not see the problem.

**Comment by ghost** [comment]
I'll close this issue then.
