### ISSUE TITLE
CHE CLI prints wrong info about CHE_HOST

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#8492]
on mac os starting CHE with CLI shows:
```
INFO: (che start): Use: http://localhost:8080
INFO: (che start): API: http://localhost:8080/swagger
```

while in che.env `CHE_HOST=192.168.65.2`

**Comment by benoitf** [comment]
hello, what is wrong ? The IP is not reachable this is why it's replaced by localhost

**Comment by riuvshin** [comment]
localhost seems hardcoded, on mac we should never show `localhost` because on localhost in CHE single user not all features are working and CHE multi user does not work at all

**Comment by benoitf** [comment]
we have to see localhost for end users. Tools may use internal IP only if they're inside containers
Also the docker IP is not reachable by default while localhost is ( it's the goal of docker for mac)

**Comment by riuvshin** [comment]
I think localhost should not be used on mac os at all, @slemeur faced this issue few days ago he tried to use CHE on mac os with localhost and it didn't work for him. 
I think this should be the very first lines in `installation` section of CHE docs for MAC OS that user should create an alias: `sudo ifconfig lo0 alias <DOCKER_FOR_MAC_VM_IP>` and never use localhost

**Comment by benoitf** [comment]
this is kind of a blocker if users need to change their network configuration ( also they will not read the documentation)

**Comment by riuvshin** [comment]
@benoitf yeah, require network change isn't a perfect thing but without this CHE multi-user will not work at all... So what do you propose? leave as it is?

**Comment by benoitf** [comment]
@riuvshin to make che working as expected without changing networking.

**Comment by riuvshin** [comment]
@benoitf I'm not sure that that is possible. I can't imagine how {preview.url} will work on mac os if url will be `localhost:{ephemeral_port}`.

**Comment by riuvshin** [comment]
Btw, single-port feature will also not work with localhost.
So I still believe that we should not use localhost at all...

**Comment by riuvshin** [comment]
btw OCP on MAC OS actually has the same issue and it fails on the start if alias is not in place.

```
FAIL
   Error: timed out waiting for OpenShift container "origin"
   Solution:
     Ensure that you can access 192.168.65.2:8443 from your machine
```

**Comment by sunix** [comment]
looks like won't fix
