### ISSUE TITLE
[dashboard] Make che-simple-selecter component use images

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#850]
Make it possible for che-simple-selecter use images as well, needed for new stack icon to display in ready-to-go-section.

**Comment by ddementieva** [comment]
(Comment by Oleksii Orel)

[https://github.com/eclipse/che/pull/927](https://github.com/eclipse/che/pull/927)

**Comment by ddementieva** [comment]
(Comment by Jenkins CI server)

SUCCESS: Integrated in ![](http://ci.codenvy-dev.com/jenkins/images/16x16/blue.png) [che-ci-master #758](http://ci.codenvy-dev.com/jenkins/job/che-ci-master/758/)  
CHE-890: add stack icon link as icon image to stack widget (oorel@codenvy.com: [681a8ad92345a06d2d7c486493b065e3802d47d7](https://github.com/eclipse/che/commit/681a8ad92345a06d2d7c486493b065e3802d47d7))
- core/ide/che-core-ide-stacks/src/main/resources/stack_img/type-aspnet.svg
- dashboard/src/app/workspaces/create-workspace/select-stack/ready-to-go-stacks/ready-to-go-stacks.controller.js
- dashboard/src/components/widget/simple-selecter/che-simple-selecter.directive.js
- core/ide/che-core-ide-stacks/src/main/resources/stack_img/type-node.svg
- dashboard/src/components/widget/simple-selecter/che-simple-selecter.html
- dashboard/src/app/workspaces/create-workspace/select-stack/ready-to-go-stacks/ready-to-go-stacks.html
- dashboard/src/components/widget/simple-selecter/che-simple-selecter.styl
- core/ide/che-core-ide-stacks/src/main/resources/stack_img/type-blank.svg
- core/ide/che-core-ide-stacks/src/main/resources/stack_img/type-php.svg
