### ISSUE TITLE
Cannot show inherited members of class in the File Structure form

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8509]
**Reproduction Steps:**
1. Create a workspace from the **Java** stack with the **web-java-spring** project.
2. Open **GreetingController** class in the **Editor**.
3. Press **Ctrl+F12** for File Structure form.
4. Press **Ctrl+F12** again to show inherited members in the form.

**Observed behavior:**
Nothing changed. 

**Failed test:** FileStructureBaseOperationTest
**OS and version:**
Che 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
![nimbus-record-video-2018-01-30-09-11-35](https://user-images.githubusercontent.com/7760565/35552743-cdf3c8ca-059d-11e8-9acd-fb3641d63052.gif)

![org eclipse che selenium miscellaneous filestructurebaseoperationtest checkfilestructurebaseoperations_kvn66zqx](https://user-images.githubusercontent.com/7760565/35552871-5d1db66e-059e-11e8-98dc-99928bf34438.png)

**Comment by riuvshin** [comment]
any errors recorded?
