### ISSUE TITLE
Che doesn't recognize maven multi-module project after import

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#8510]
### Description
 
JDT LS doesn't resolve maven multi-module project after import

### Reproduction Steps

1. Create a workspace with JDT LS installer
2. Import a maven multi-module project

WRONG:
The project is not resolved. JDT LS begins to resolve after editing a `pom.xml` file.
EXPECTED:
The project must be resolved after import.

**OS and version:**    

**Diagnostics:**

**Comment by tsmaeder** [comment]
@tolusha what do you mean by "resolved"?

**Comment by tolusha** [comment]
Unrecognized modules:
![notresolved](https://user-images.githubusercontent.com/1640675/35724856-ed8bdb2a-0807-11e8-8d9c-45a5e96a4195.png)


Recognized modules:
![resolved](https://user-images.githubusercontent.com/1640675/35724745-89cb2758-0807-11e8-8e7e-8401716145e9.png)

**Comment by tsmaeder** [comment]
Aha...but does the java support work in the java file that are inside the modules?

**Comment by tolusha** [comment]
Hover works at least ^)
