### ISSUE TITLE
Project explorer: Action to expand folders that contains modified/added files

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#8515]
### Description
When restarting a workspace, most of the time, user would like to reopen or see files that have been modified/added previously (whether it has been git staged or not). The workaround is to perform a `git status` and open the files but this is not ideal.
One way to do would be to have an action (right click on a project item?) that would expand all the folders that contains modified/added files.

**Comment by gorkem** [comment]
Closing this as Che 7 provides enough hints for git status
