### ISSUE TITLE
Parameters for Git clone with submodules not obvious and/or do not work

### ISSUE THREAD

**Issue by andrew-mclachlan** [eclipse-che/che#8516]
### Description

I am trying to add a sample that clones from a Git repository that has submodules. I am adding
``
 "parameters": {
    "recursive": "true"
 }
``
to the template because that is what the code in Che seems to be checking for but it does not work.

The clone starts to clone but does not seem to use --recursive or ``git submodule init && git submodule update``.

### Reproduction Steps

To test use the samples ``https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json`` and try to clone a Git repo with submodules.

**OS and version:**    

macOS.

**Comment by andrew-mclachlan** [comment]
I am unable to add labels to this Issue.

**Comment by eivantsov** [comment]
@andrew-mclachlan this param isn't supported.

You may use `"keepDir":"module"` in params though

**Comment by andrew-mclachlan** [comment]
Hi @eivantsov. Not sure that I follow. Perhaps you could show me an example of how to clone a repo. that has sub modules.

**Comment by eivantsov** [comment]
@andrew-mclachlan https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L1150
