### ISSUE TITLE
Can not configure maven project in Che

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#852]
Steps to reproduce:
# Open Che with mapped on fs projects
# Create new workspace
# Try to configure any maven project as maven

Wrong: error appears

**Comment by ddementieva** [comment]
(Comment by Jenkins CI server)

SUCCESS: Integrated in ![](http://ci.codenvy-dev.com/jenkins/images/16x16/blue.png) [che-ci-master #746](http://ci.codenvy-dev.com/jenkins/job/che-ci-master/746/)  
CHE-891: Initialize projects from unconfigured folders on starting (azatsarynnyy@codenvy.com: [3dfb6d12bd764e70b25683c19dcfd49cf4d963c5](https://github.com/eclipse/che/commit/3dfb6d12bd764e70b25683c19dcfd49cf4d963c5))
- wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/ProjectRegistry.java
- wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/WorkspaceHolder.java
