### ISSUE TITLE
Block project download

### ISSUE THREAD

**Issue by crfcarlos** [eclipse-che/che#8522]
**Reproduction Steps:**

1. In Project -> Download as zip ...
2. Right click on the project -> Download

**Observed behavior:**
How to block the download for users

**OS and version:**
Che 6.0.0-M4 multiuser; Chrome 64.0; Ubuntu Server 16.04.3 LTS

**Additional information:
![download 1](https://user-images.githubusercontent.com/19939398/35581489-0a32cc20-05d3-11e8-862c-00eef6fcf945.PNG)
![download 2](https://user-images.githubusercontent.com/19939398/35581490-0a52ed66-05d3-11e8-9726-8a1d3fb7ec68.PNG)

**

**Comment by ghost** [comment]
@crfcarlos it cannot be solved with pure configuration. You may need to build own Che assembly and remove those menu items. However, it'll be possible to do that using REST API.

**Comment by crfcarlos** [comment]
where is the REST API? And how do I use the REST API with CHE?

**Comment by ghost** [comment]
https://www.eclipse.org/che/docs/6/che/docs/authentication.html

**Comment by crfcarlos** [comment]
Eugene, how low is the eclipse ché project to effect this change? Help me please ?

**Comment by ghost** [comment]
@crfcarlos not sure I have understood your question. Do you need instructions on building own Che assembly without this project api method and UI menu entry?

**Comment by crfcarlos** [comment]
Hello Eugene!

Yes I need help in building a proper Che assembly. Can you help me?

Att.

___________________________
Ferreira (Carlos Roberto)
cel.: 11 9.6069-8919 (Tim)
res.: 11 3593-9753

2018-02-02 4:50 GMT-02:00 Eugene Ivantsov <notifications@github.com>:

**Comment by eivantsov** [comment]
@crfcarlos https://www.eclipse.org/che/docs/6/che/docs/framework-overview.html

I am closing this issue. Open a new one if you face particular problems with removing this methid and ide action from a custom assembly
