### ISSUE TITLE
Shell Script Saved with Windows Line Endings

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#8523]
### Description
When adding a new Linux Shell file to a project, the file is saved with Windows line ending which prevents the file from being executed correctly.

### Reproduction Steps

1. Create aworkspace from Ubuntu (Simple) and start.
2. Create blank project in new workspace
3. Add a shell file to project using Alt-Shift-N
4. Name the file test.sh
5. Edit test.sh to have the following:
`#!/bin/bash

echo "This script executes!"`

6. Using the console, make the shell file executable.
7. Execute the shell file.
8. Execution fails with:
`bash: ./test.sh: /bin/bash^M: bad interpreter: No such file or directory`

**OS and version:**    
Ubuntu 16.04
Che 6.0.0-M4

**Diagnostics:** 
IDE indicates is `text/x-sh` MIME type in lower right corner.

**Comment:**
This feels like a configuration issue. The installation is a clean 6.0.0-M4 install.

**Comment by ghost** [comment]
@rab-sp I cannot reproduce it on Linux.

![image](https://user-images.githubusercontent.com/5337267/35608343-66a0ff16-0661-11e8-9d75-602ab432de0d.png)

Can you reproduce it this way?

```
docker run -ti eclipse/ubuntu_jdk8 bash
cd ~
mcedit test.sh
```
paste
```
#!/bin/bash
echo "This script executes!"
```
```
chmod +x test.sh
```

**Comment by ghost** [comment]
So, Che is running on Ubuntu. I'm actually running the IDE within Chrome on Windows. Could that be it?  I'm developing from my laptop but building scripts for an Ubuntu server.

If it is detecting the OS my browser is running on, how do I make it stop?

**Comment by ghost** [comment]
@rab-sp this could be it if you copy/paste maybe.

**Comment by ghost** [comment]
The script file is being edited with the IDE.  I typed it into the IDE.

**Comment by ghost** [comment]
@rab-sp I have suggested a way to reproduce it using just terminal. Did you have a chance to do that?

**Comment by ghost** [comment]
The steps you gave work fine. The script executes with the correct line endings.

**Comment by ghost** [comment]
Can this be reliably reproduced? I don;'t have a Win machine to check it

**Comment by ghost** [comment]
Fails every time when trying to create a *.sh file. Note, if I make it a `.xml` or `.json` file and exectute it anyway, the line endings are correct. It seems to be the something about the `.sh`
![line-endings](https://user-images.githubusercontent.com/24442517/35631817-ed07535a-0672-11e8-8f87-b2d433340dea.PNG)

Edit:
*.xml and *.json files seem to have windows line endings as well when created with the IDE.

**Comment by ghost** [comment]
For comparison, same procedure on SaaS, though granted version 5.22.
![codenvy-shell-fail](https://user-images.githubusercontent.com/24442517/35632496-d6605910-0674-11e8-8212-7ad545d242a7.PNG)

**Comment by ghost** [comment]
@rab-sp I'll try to check it on Windows

**Comment by ghost** [comment]
For the record, I tried spoofing my browser string using the develop tools. It didn't help.

**Comment by eivantsov** [comment]
@rab-sp is this still an issue for you? Have you tried the latest nightly tag? Not sure we did anything to fix it, but who knows, maybe it cannot be reproduced anymore.

**Comment by rab-sp** [comment]
I have tried 6.2.0, and yes it is still an issue.

**Comment by zbacsi** [comment]
Why is there no option to change line endings?
