### ISSUE TITLE
Eclipse Che Preview URL issue

### ISSUE THREAD

**Issue by amrit28** [eclipse-che/che#8524]
Hello , Can any one suggest, how we can get the running server url in eclipse che 6.0.0-M2, As the support of macros ${server.port.3000} or ${server.port} has been removed from 6.0.0-M2 vesrion.
Is the preview url issue has been fixed in 6.0.0-M4?

**Comment by ghost** [comment]
https://www.eclipse.org/che/docs/6/che/docs/servers.html
