### ISSUE TITLE
TreeTable UI in eclipse che

### ISSUE THREAD

**Issue by amrit28** [eclipse-che/che#8525]
Hello , Can any one suggest.
Is there any way to implement tree table structure into eclipse che.
As we have tried Smart GWT but it seems there is compatibility issue.
After inheriting the module  che work space view is not coming.

**Comment by ghost** [comment]
@EclipseChe89 if you expect to-the-point responses I think you need to share a bit more information on what you are trying to achieve and what you have already tried.
