### ISSUE TITLE
Investigate the failing of the selenium test 'ImportProjectIntoSpecifiedBranchTest' on CI

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8529]
### Description
* Sometimes the selenium test 'ImportProjectIntoSpecifiedBranchTest' fails when run on the CI
* Usually it happens on the multi-user assemblies
* Need to find the reason of it it and fix
**_report:_**
![loader](https://user-images.githubusercontent.com/5408906/35721757-32b579b0-07fc-11e8-81d1-60febb1ac72e.png)

**_screenshot:_**
![loader-2](https://user-images.githubusercontent.com/5408906/35721799-6f606528-07fc-11e8-8b14-72194743ee0e.png)

**Comment by vkuznyetsov** [comment]
Is there any logs or screenshots from CI?

**Comment by artaleks9** [comment]
Have be added the logs of report and screenshot

**Comment by artaleks9** [comment]
The problem is resolved by the PR #8619
