### ISSUE TITLE
Refactor rename/move does not work properly

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8531]
### Description
* __Sometimes refactoring rename/move does not work when selenium tests run on CI job or local machine._ After refactoring 'rename/move' the content of file in the editor is not update._
 
**Expected behavior:**
* the content of file should be updated

**Observed behavior:**
* the content of file is not updated

**_rename package:_**
![rename-pack](https://user-images.githubusercontent.com/5408906/35614459-df36f0e6-0677-11e8-8177-ee6490aaff7c.png)

**_refactor move:_**
![refactor-move](https://user-images.githubusercontent.com/5408906/35614492-f4fae4dc-0677-11e8-8808-aa5b95580d4c.png)

**Che version:** 6.0.0-M5
**OS and version:** Fedora 25
**Che install:** Docker

**Additional information:**
* Related selenium tests: _MoveItemsTest_, _RenamePackageTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by riuvshin** [comment]
provide manual steps to reproduce this issue

**Comment by gazarenkov** [comment]
@artaleks9 provide steps to reproduce

**Comment by artaleks9** [comment]
It happened when the test suite was launched on the CI. My tries to reproduce this bug on the local machine is not success. And the next launches on the CI do not reproduce it more. So I think the issue need to close. 
WDYT?
