### ISSUE TITLE
Broken installers in workspace status panel

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#8534]
### Description
 
Sometimes installers displayed with empty name and description.
It's because the browser receive WorkspaceStartingEvent earlier than list of installers with names and descriptions.

![broken installers](https://user-images.githubusercontent.com/1655894/35618134-b5e1ca8a-0682-11e8-9f5e-61be05cbdbec.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
It's hard to find clear reproduction steps but I face this issue quite often.
Usually, it happens when IDE is loaded in a background tab.

**Comment by dmytro-ndp** [comment]
I am facing this issue every time I am using the command _"Add Workspace -> Open in IDE"_:
![out](https://user-images.githubusercontent.com/1197777/35678859-9f838d24-075d-11e8-991f-d62b116b2dd9.gif)

Also I had broken "Workspace Status" widget in another way when I was trying to open workspace in another browser tab in time of starting:
![screenshot from 2018-02-01 14-36-39](https://user-images.githubusercontent.com/1197777/35678960-f7aa15ae-075d-11e8-826e-c85252fec48e.png)

**Comment by vitaliy-guliy** [comment]
@dmytro-ndp Thank you!

**Comment by dmytro-ndp** [comment]
You are welcome, @vitaliy-guliy :-)

**Comment by vitaliy-guliy** [comment]
Case on your second screenshot will be fixed by https://github.com/eclipse/che/issues/7278
