### ISSUE TITLE
The IDE hangs after starting a workspace from context menu

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8539]
**Reproduction Steps:**
1. Start a workspace.
2. From the **Recent Workspaces** list stop this workspace from its context menu.
3. Start the workspace from the context menu.

**Observed behavior:**
Status of the workspace in the **Recent Workspaces** list changed to the **STARTING** but there are not any changes in the **IDE**.

**OS and version:**
Che 6.0.0-M5; Chrome 63.0; Fedora 25

**Additional information:**
![nimbus-record-video-2018-01-31-12-22-33](https://user-images.githubusercontent.com/7760565/35621866-86114f04-068e-11e8-8324-e1f06c97e47a.gif)

**Comment by riuvshin** [comment]
@ashumilova can you please take  a look

**Comment by SkorikSergey** [comment]
Not reproduced.
