### ISSUE TITLE
Workspaces aren't timing out by default

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#8543]
Since switching to CHE6, workspaces no longer time out after the default of 1hr (no env vars set).

**Comment by ghost** [comment]
@davidwindell if this is tru, it's a bug then: https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L108

**Comment by davidwindell** [comment]
Can you try running a workspace idle for an hour on docker infra with multi-user and all the default and see what happens?

**Comment by davidwindell** [comment]
I've tried explicitly setting `CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS` and `CHE_DOCKER_CLEANUP__PERIOD__MIN` in case the default wasn't kicking in but it had no effect.

**Comment by davidwindell** [comment]
This is fixed for me in latest nightly
