### ISSUE TITLE
Unexpected error messages in the console IDE after refactor

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8545]
**Reproduction Steps:**
* Open the project in the IDE
* Perform the refactor 

**Expected behavior:**
* the console IDE does not have error messages after performing refactor

**Observed behavior:**
* there is unexpected error message in the console IDE 

**Che version:** 6.0.0-M5
**OS and version:** Fedora 25
**Che install:** Docker/OCP 

**Additional information:**
* Similar related issue: #6947
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![error-terminal-after-refactor](https://user-images.githubusercontent.com/5408906/35627101-8c81898c-06a0-11e8-8296-74e08c3d118f.png)

**Comment by slemeur** [comment]
Closing as this is expected to be fixed with the work on JDT LS. #6157
