### ISSUE TITLE
Search fails on certain workspaces

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#8552]
### Description
We're not quite sure how to reliably reproduce this but it happens daily on different workspaces (but not all).

![image](https://user-images.githubusercontent.com/1720090/35638821-18ccb4b6-06b0-11e8-91ad-c932a45cbf4c.png)

Could it be related to https://github.com/eclipse/che/pull/8112?

**OS and version:**    
Che 6.0.0

**Comment by skabashnyuk** [comment]
It may happen after removing large project tree. Pending changes in Licene index keep in memory and not saved to disk.
