### ISSUE TITLE
 Factory support in Next gen Che.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#8553]
Current factory feature based on Eclipse CHE actions. But new generation IDE doesn't contains CHE actions, it provides own concept with Commands and Tasks. We need think about implementation factory with next gen Che.

**Comment by AndrienkoAleksandr** [comment]
@slemeur what do you think?

**Comment by slemeur** [comment]
Agree @AndrienkoAleksandr. Factories will need to be supported in the new generation Che and we will need to ensure that we have the same level of capabilities - including all the factories actions.
We will list all the features and prioritize the work.

**Comment by AndrienkoAleksandr** [comment]
Duplicated to https://github.com/eclipse/che/issues/9074
