### ISSUE TITLE
Don't set up focus forcibly after editor initialization

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#8573]
### Description
There is a problem, when editor already initialized it forcibly takes focus to own DOM element. We should provide a flag to init configuration to allow editor take focus or not after initialization.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/20)

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
