### ISSUE TITLE
Swagger page is broken if no trailing slash in url

### ISSUE THREAD

**Issue by ddementieva** [eclipse-che/che#859]
Swagger page is broken if no trailing slash in url.
See attached screenshot.

**Comment by skabashnyuk** [comment]
Linked https://github.com/eclipse/che/issues/459

**Comment by mkuznyetsov** [comment]
Upgrading Apache Tomcat to 8.0.32 will fix the problem. [](url)
There is an [Eclipse CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11107) for it, awaiting approval.
