### ISSUE TITLE
Organize Imports action doesn't show an import dialog if more than one import is possible for unresolved reference

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#8593]
### Description
 
Organize Imports action doesn't show an import dialog if more than one import is possible for unresolved reference

### Reproduction Steps

1. Create a simple java project.
2. Open a Java class and introduce a `List` variable, List should be underlined by wavy red line. It means that `List` is not resolved.
3. Go to menu Assistant -> Organize Imports
WRONG: Nothing happenes.
Expected: Organize Imports dialog must appear to propose an import.

**OS and version:**    
JDT LS branch

**Diagnostics:**

**Comment by tolusha** [comment]
![organizeimports](https://user-images.githubusercontent.com/1640675/36034311-5370f646-0dbc-11e8-8143-3d63d28d86ec.png)
