### ISSUE TITLE
Not able to add external JARs in Eclipse Che IDE module

### ISSUE THREAD

**Issue by usersk12** [eclipse-che/che#8596]
I'm facing an issue while adding io.swagger.models dependency in IDE of module i've created.
I've added following dependencies in the pom.xml:

```
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
            <classifier>sources</classifier>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
        </dependency>

```
When I'm using the classes of io.swagger.models in IDE of my project, following error is thrown during build of che/ide/che-ide-gwt-app folder:

```
[ERROR] Line 17: No source code is available for type io.swagger.models.Swagger; did you forget to inherit a required module?
[INFO]    Tracing compile failure path for type 'com..wizard.ide.ui.PanelView'
[INFO]       [ERROR] Errors in 'jar:file:/root/.m2/repository/org/eclipse/che/sample/che-sample-plugin-wizard-ide/6.0.0-M2/che-sample-plugin-wizard-ide-6.0.0-M2.jar!/com..wizard.ide.ui.PanelView.java'
[INFO]          [ERROR] Line 17: No source code is available for type io.swagger.models.Swagger; did you forget to inherit a required module?
[INFO]    [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible
```

However, the code for io,swagger.models works perfectly if added in SHARED module of my project.

Also, I checked there is no gwt.xml file for io.swagger.models.
Kindly provide help on the issue for how to add external dependency to IDE module of project.

**Comment by ghost** [comment]
@usersk12 perhaps sharing your plugin source code and a few words about what you are trying to achieve will help.

**Comment by usersk12** [comment]
Thank you for the reply. I am trying to use Swagger parser and models to parse swagger json data and use it as given below:

import io.swagger.models.Swagger;
import io.swagger.parser.Swagger20Parser;

Swagger20Parser parser = new Swagger20Parser();
Swagger swagger = parser.parse(treeDataString); //treeDataString is a string 

I have included this code in a separate shared plugin folder and included it in the dependency of main ide plugin. I am making call to the shared plugin folder for getting the parsed swagger json data. main ide plugin the following packaging:

<packaging>gwt-lib</packaging>

I am getting error while trying to build che/ide/che-ide-gwt-app folder.

Source Code:
//Shared plugin class
package org.eclipse.che.sample.shared;

import org.eclipse.che.sample.shared.api.ModelConvertor;
import org.eclipse.che.sample.shared.api.WAPath;
import org.eclipse.che.sample.shared.api.WebApiInfo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.swagger.models.Swagger;
import io.swagger.parser.Swagger20Parser;

public class RightPaneTreeValue {
	private static final Logger logger = LoggerFactory.getLogger(RightPaneTreeValue.class);
	
	public WebApiInfo constructTreeValue(String treeDataString) {
		try {
			if (treeDataString != null && !treeDataString.isEmpty()) {
				Swagger20Parser parser = new Swagger20Parser();
				Swagger swagger = parser.parse(treeDataString);
				ModelConvertor convertor = new ModelConvertor();
				WebApiInfo api = convertor.convert(swagger);
				 return api;
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		}
		return null;
	}
}

//main plugin class
package org.eclipse.che.sample.ide.rightpanetreeview;

import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.eclipse.che.sample.shared.RightPaneTreeValue;
import org.eclipse.che.sample.shared.api.WebApiInfo;
import  org.eclipse.che.sample.shared.api.WAPath;
import com.google.gwt.user.client.ui.TreeItem;

public class RightPaneTree {
	private static final Logger logger = LoggerFactory.getLogger(RightPaneTree.class);
	private String treeDataString;
	private String jsonName;

	public RightPaneTree(String treeDataString, String jsonName) {
		this.treeDataString = treeDataString;
		this.jsonName = jsonName;
	}

	public TreeItem constructTree() {
		try {
			if (treeDataString != null && !treeDataString.isEmpty()) {
				WebApiInfo api = new WebApiInfo();
				RightPaneTreeValue rightPaneTreeValue = new RightPaneTreeValue();
				api = rightPaneTreeValue.constructTreeValue(treeDataString);
				api.setFileName(jsonName);
				TreeItem rootItem = new TreeItem(new DragDrop("" + jsonName + " - http://" + api.getHost() + "" + api.getBasePath(),false, false));			
				List<WAPath> waPath = api.getPaths();
				for(WAPath waPathTemp: waPath)
				{
					TreeItem pathItem = new TreeItem(new DragDrop(waPathTemp.getPath(), true, false));
					rootItem.addItem(pathItem);
				}
				 return rootItem;
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		}
		return null;
	}
}

Please tell me if you need any more details.

**Comment by eivantsov** [comment]
@usersk12 ideally your plugin module and the pom where you have added its dependency
