### ISSUE TITLE
Multi_User_Mode_Eclispe_Che: not working.

### ISSUE THREAD

**Issue by ShivaniBali** [eclipse-che/che#8597]
**Issue:** After hitting below command on terminal, I am not able to open Che on my localhost. It just keeps on blinking with che logo on **URL**: http://localhost:8080/dashboard/#/

I used below command for Multi-User:

**Command:** docker run -it -e CHE_MULTIUSER=true -e CHE_DOCKER_IP_EXTERNAL=10.0.75.2 -v /var/run/docker.sock:/var/run/docker.sock -v /applications/tmp:/data eclipse/che start

Which is a success as images are being created in Docker.

CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                 PORTS                              NAMES
3e328860baed        jboss/keycloak-openshift:3.3.0.CR2-3   "start-keycloak.sh -…"   7 hours ago         Up 7 hours             0.0.0.0:5050->8080/tcp             che_keycloak_1
7caa5f388653        eclipse/che-server-multiuser:5.22.1    "/entrypoint.sh"         7 hours ago         Up 7 hours             8000/tcp, 0.0.0.0:8080->8080/tcp   che
6eabb285d371        centos/postgresql-96-centos7:9.6       "container-entrypoin…"   7 hours ago         Up 7 hours (healthy)   0.0.0.0:5432->5432/tcp             che_postgres_1

Looking forward to hear from you guys!

Thanks!

**Comment by ghost** [comment]
@ShivaniBali what is your OS?

Also, can you open browser dev console and share a screenshot of the blinking logo page being loaded?

**Comment by ShivaniBali** [comment]
@eivantsov : OS is : MAC OS version: 10.13

Please find below screen shot of web console.

<img width="1440" alt="screen shot 2018-02-05 at 2 02 51 pm" src="https://user-images.githubusercontent.com/35276146/35823438-89866f00-0a7d-11e8-85e6-8113734459d8.png">

Thanks!

**Comment by ghost** [comment]
`docker logs -f che` server logs too, please

Do you see this screen after you log in? Hiw much RAM does your Docker VM have?

**Comment by ShivaniBali** [comment]
@eivantsov : Please see attached log file.

Yes, I see this screen on first login to local. 

Ram:  CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
3e328860baed        che_keycloak_1      0.52%               975.9MiB / 1.952GiB   48.82%              760B / 314B         0B / 0B             105
7caa5f388653        che                 0.28%               323.3MiB / 1.952GiB   16.17%              40.7kB / 3.05MB     88MB / 111kB        52


[Docker_logfile.docx](https://github.com/eclipse/che/files/1696507/Docker_logfile.docx)

Thanks!

**Comment by ghost** [comment]
@ShivaniBali I can see that postgres is not accessible, according to the logs. And I don't see postgres container in the output you have shared too.

Can you do the following?:

1. docker rmi -f eclipse/che eclipse/che-server
2. docker pull eclipse/che eclipse/che-server
3. re-run Che

And I was asking about how much RAM does your Docker VM have? You can find this info in your Docker application

**Comment by ShivaniBali** [comment]
@eivantsov : Sorry for the delay. 
Ram I can see on my docker application is : 1,179,453,854 bytes (1.18 GB on disk)
To be more precise, please let me know any step for it.

I removed the container for now, because I was trying to work on Xtext with Eclipse Che and was developing plugin.
https://blogs.itemis.com/en/how-to-get-started-with-xtext-language-servers-and-che
With this as well, I see below issue with the port:

Shivanis-MacBook-Pro:che shivanibali$ docker run -v /var/run/docker.sock:/var/run/docker.sock -e CHE_DEBUG_SERVER=true -e CHE_ASSEMBLY=/home/dietrich/che-dev/che/assembly/assembly-main/target/eclipse-che-5.1.2/eclipse-che-5.1.2/ codenvy/che-launcher:nightly start
INFO: ECLIPSE CHE: Found image codenvy/che-server:nightly
INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 5.0.0-M8-SNAPSHOT
INFO: ECLIPSE CHE: Use: http://172.17.0.1:8080
INFO: ECLIPSE CHE: API: http://172.17.0.1:8080/swagger
INFO: ECLIPSE CHE: JPDA Debug - http://172.17.0.1:8000

<img width="1440" alt="screen shot 2018-02-06 at 9 09 25 pm" src="https://user-images.githubusercontent.com/35276146/35894712-21a13b80-0b82-11e8-98a8-a5056bbf7c55.png">

Hoping to hear back from you, what shall I do to make it work!

Thanks!

**Comment by ghost** [comment]
@ShivaniBali I am lost now since I cannot understand what problem we're trying to solve.

This is documentation https://www.eclipse.org/che/docs/6/che/docs/docker-multi-user.html to follow. You used a very old syntax.

As to RAM for Docker, if you're saying you have 1GB that's not enough to run multi user Che. 3-4 GB is required.

**Comment by ShivaniBali** [comment]
@eivantsov I tried the steps you asked me to: as to remove docker Image, pull it back and restart it. Now I am not even able to open localhost for Single User. The above image is of single user.

PS: And how do I increase the RAM for docker, do I need to specifically make some changes on my system for the Docker Application : such as some memory alignment ? As I have 8 GB of RAM on my machine.

thank you!

**Comment by ShivaniBali** [comment]
@eivantsov : Now the issue looks with all, even with Single User. Earlier I was able to open che for single user but now it keeps on blinking and on console it throws me error.

Attached ScreenShot and Log file, Please have a look.
<img width="1440" alt="screen shot 2018-02-07 at 12 19 33 pm" src="https://user-images.githubusercontent.com/35276146/35931082-b2aeecec-0c01-11e8-84a1-4c036c0cfe7e.png">

[Single_User_LogFile.docx](https://github.com/eclipse/che/files/1704089/Single_User_LogFile.docx)

PS: Is it the memory issue in this case as well?
Looking forward to hear from you!

**Comment by ghost** [comment]
@ShivaniBali server logs look fine. Must be a Docker for Mac glitch. Also, giving it a go in an incognito mode and flushing a local data directory (the one mounted int :/data) is also a good idea.

**Comment by eivantsov** [comment]
@ShivaniBali Any update on this?

**Comment by ShivaniBali** [comment]
@eivantsov: Hi there, yes it’s working well now. Thank you :)

**Comment by ShivaniBali** [comment]
@eivantsov: Hi there, yes it’s working well now. Thank you :)
