### ISSUE TITLE
server ports not exposed

### ISSUE THREAD

**Issue by jgroom33** [eclipse-che/che#8598]
### Description
Goal is to expose previewUrl: ${server.port.8080}
The port is not mapped 

### Reproduction Steps
EXPOSE 80 in Dockerfile

set previewUrl: ${server.port.80} in factory

Resulting docker inspect of container:

<details>
[
    {
        "Id": "52ad510064650abe6eabd027f9c2fac28a3a815b4dcf7ce60e7f51221a59e1d9",
        "Created": "2018-02-04T12:04:07.250442624Z",
        "Path": "nginx",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 94968,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-02-04T12:04:07.614433348Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:3556049f65b18a207ca715a54dade4802475e41ab814a6c25bf97f254b0d4c7d",
        "ResolvConfPath": "/var/lib/docker/containers/52ad510064650abe6eabd027f9c2fac28a3a815b4dcf7ce60e7f51221a59e1d9/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/52ad510064650abe6eabd027f9c2fac28a3a815b4dcf7ce60e7f51221a59e1d9/hostname",
        "HostsPath": "/var/lib/docker/containers/52ad510064650abe6eabd027f9c2fac28a3a815b4dcf7ce60e7f51221a59e1d9/hosts",
        "LogPath": "/var/lib/docker/containers/52ad510064650abe6eabd027f9c2fac28a3a815b4dcf7ce60e7f51221a59e1d9/52ad510064650abe6eabd027f9c2fac28a3a815b4dcf7ce60e7f51221a59e1d9-json.log",
        "Name": "/workspace4b25n480zn6xilrm_null_jgroom_ui",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/ubuntu/devops-toolkit/dtk_dist_workspace_mount:/home/user/dtkdist",
                "/var/run/docker.sock:/var/run/docker.sock"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "workspace4b25n480zn6xilrm_wss",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [
                "che-host:172.19.0.2"
            ],
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 2147483648,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": -1,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": -1,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/72ad8787fcf240cc0250c0625401d39372ceb61075d922f07b358cc18ef04197-init/diff:/var/lib/docker/overlay2/801f5ea2434aa86d939bb5c2db33af307ab97b3f948aadfd99ee5ad2a139c7bb/diff:/var/lib/docker/overlay2/726017c07774f5cab90b4978252ec8e579cfcfd23accf7e8e18b391bd1e4d4bb/diff:/var/lib/docker/overlay2/227b563e103be17de6f548d0cd99603ca410151d64d722d159856e3edf684fd3/diff:/var/lib/docker/overlay2/1de046b4cbe27a888eda979f13da8511cfc6c67f9bbd43fd0396b61d32085b89/diff:/var/lib/docker/overlay2/77de0c9cef429c4f871540d35f68351f5ccc7cbae85f0c28475cae40c5800347/diff:/var/lib/docker/overlay2/524a4ed57f4546c725b6ee42a7adeb3a8614c812d6bb32ec98a5beb045ab832e/diff:/var/lib/docker/overlay2/193158e13499e96fe1028ff9ed03c47412d6538d42aedccbff03b57f18aaa217/diff:/var/lib/docker/overlay2/3b3b19ddeae01866594ef5b800408262464ca549907367ba44f964c8d258e2d5/diff:/var/lib/docker/overlay2/ea100109ba3dde9d46ff5ea04013be6f609819460c720871ca07863ca4c4aafb/diff:/var/lib/docker/overlay2/4b4aba5c1857dffa95b804126bde6b043f1eac13d571874080be0aad4bc52b44/diff:/var/lib/docker/overlay2/d4d94f0651a70f19ae28ed77fa017b04d1ab74813389a0f18265e020ffc0f1b9/diff:/var/lib/docker/overlay2/0998a9d3b9d4a06ea25e5f7174e471650d4b91b9020a2a8ca083a4098fc0387e/diff",
                "MergedDir": "/var/lib/docker/overlay2/72ad8787fcf240cc0250c0625401d39372ceb61075d922f07b358cc18ef04197/merged",
                "UpperDir": "/var/lib/docker/overlay2/72ad8787fcf240cc0250c0625401d39372ceb61075d922f07b358cc18ef04197/diff",
                "WorkDir": "/var/lib/docker/overlay2/72ad8787fcf240cc0250c0625401d39372ceb61075d922f07b358cc18ef04197/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/ubuntu/devops-toolkit/dtk_dist_workspace_mount",
                "Destination": "/home/user/dtkdist",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "52ad51006465",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MAVEN_OPTS=-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom ",
                "CHE_MACHINE_TOKEN=machineyz4dfa2xiltvmjmffvftp5i07fk8527y8xdv20ir7jypcw882cw72dhssszn2ctdicktfugxuaf9fs5ksmobbucv4b9k8s66rdq98hlr41af8lbmgoyji1avj2j2dq6c",
                "CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS=-XX:MaxRAM=600m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms50m -Djava.security.egd=file:/dev/./urandom ",
                "CHE_WORKSPACE_ID=workspace4b25n480zn6xilrm",
                "JAVA_OPTS=-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom ",
                "CHE_PROJECTS_ROOT=/projects",
                "CHE_API=http://che-host:8080/api",
                "CHE_AUTH_ENABLED=true",
                "CHE_WORKSPACE_MAVEN__SERVER__JAVA__OPTIONS=-XX:MaxRAM=128m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom ",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "BP2HOOK_heartbeat=/bin/true",
                "BP2HOOK_peer-status=/bin/true",
                "BP2HOOK_peer-update=/bin/true",
                "NBI_orchestrate_type=http",
                "NBI_orchestrate_port=80",
                "NBI_orchestrate_url=http://{ip}:{port}",
                "NBI_orchestrate_appbar=True",
                "NBI_orchestrate_landing-page=True"
            ],
            "Cmd": [
                "nginx"
            ],
            "ArgsEscaped": true,
            "Image": "eclipse-che/workspace4b25n480zn6xilrm_null_jgroom_ui",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.eclipse.che.machine.attributes": "{\"memoryLimitBytes\":\"2147483648\"}",
                "org.eclipse.che.machine.name": "ui",
                "org.eclipse.che.workspace.env": "wss",
                "org.eclipse.che.workspace.id": "workspace4b25n480zn6xilrm",
                "org.eclipse.che.workspace.owner": "jgroom"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "eac99ec509ce26a8cf063c747e010fd2b188c120f9a3b0680409079aa83ae94d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/eac99ec509ce",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "che_che-network": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "52ad51006465"
                    ],
                    "NetworkID": "0628addeea27e5c3f078aa6cd27e5624a4d9a5913b78aebb3278d68f4de7db07",
                    "EndpointID": "78a5c69d3f132d401be148e4a0b549d90823482043e4f5d26fdb06914819072b",
                    "Gateway": "172.19.0.1",
                    "IPAddress": "172.19.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:13:00:04",
                    "DriverOpts": null
                },
                "workspace4b25n480zn6xilrm_wss": {
                    "IPAMConfig": null,
                    "Links": [],
                    "Aliases": [
                        "ui",
                        "52ad51006465"
                    ],
                    "NetworkID": "77cf5cca47b82d0449123e1f39c1b484cfbfbd15566130bf131bc96dd6af3773",
                    "EndpointID": "8f7aac78cade01acb7645bd70340629e64ae78b5fe5221bdfa239f40074dba05",
                    "Gateway": "172.23.0.1",
                    "IPAddress": "172.23.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:17:00:03",
                    "DriverOpts": null
                }
            }
        }
    }
]
</details>

Same behavior occurs with dev-machine (EXPOSE 8081)

Attempted workaround in factory (workspace.environments.wss.machines.ui.servers):

<details>
{
  "v": "4.0",
  "name": "DTK-17.10-1",
  "workspace": {
    "environments": {
      "wss": {
        "machines": {
          "ui": {
            "attributes": {
              "memoryLimitBytes": "536870912"
            },
            "servers": {
  "80/tcp":{
     "url":"http://172.17.0.1:9980",
     "ref":"ui",
     "properties":{
       "internalUrl":"http://172.17.0.1:9980",
       "internalAddress":"172.17.0.1:9980"
     },
     "address":"172.17.0.1:9980",
     "protocol":"http"
  }
}
,
            "volumes": {},
            "installers": [],
            "env": {}
          },
          "bpocore-dev": {
            "attributes": {
              "memoryLimitBytes": "2147483648"
            },
            "servers": {},
            "volumes": {},
            "installers": [],
            "env": {}
          },
          "dev-machine": {
            "attributes": {
              "memoryLimitBytes": "2147483648"
            },
            "servers": {},
            "volumes": {},
            "installers": [
              "org.eclipse.che.ws-agent",
              "org.eclipse.che.terminal",
              "org.eclipse.che.ls.json",
              "org.eclipse.che.ls.python",
              "org.eclipse.che.ssh",
              "org.eclipse.che.git-credentials",
              "org.eclipse.che.exec",
              "org.eclipse.che.ls.yaml"
            ],
            "env": {}
          }
        },
        "recipe": {
          "type": "compose",
          "content": "services:\n dev-machine:\n  image: 'artifactory.ciena.com/blueplanet/eclipse/dtk:0.0.1'\n  mem_limit: 2147483648\n  expose:\n   - 8080\n   - 8081\n  environment:\n   - DEVOPS_TOOLKIT=/home/user/dtkdist/dtkdist-17.10.0-7\n   - BPOCORE_DEV=\"true\"\n  depends_on:\n   - bpocore-dev\n bpocore-dev:\n  image: 'artifactory.ciena.com/blueplanet/bpocore-dev:1.8.1-8588-50dd182'\n  mem_limit: 2147483648\n  expose:\n   - 8181\n   - 9092\n ui:\n  image: 'artifactory.ciena.com/blueplanet/frost-orchestrate-ui-dev:1710.6.5'\n  mem_limit: 1073741824\n  expose:\n   - 80\n  depends_on:\n   - bpocore-dev\n",
          "contentType": "application/x-yaml"
        }
      }
    },
    "defaultEnv": "wss",
    "projects": [
      {
        "links": [],
        "name": "radocker",
        "attributes": {},
        "type": "blank",
        "source": {
          "location": "git@git.blueplanet.com:devops-sample-ra/radocker.git",
          "type": "git",
          "parameters": {
            "branch": "master",
            "keepVcs": "false"
          }
        },
        "path": "/radocker",
        "problems": [],
        "mixins": []
      }
    ],
    "name": "dtk",
    "commands": [
    ],
    "links": []
  },
  "id": "factoryrjj9grooohntrcpa",
  "ide": {
    "onProjectsLoaded": {
      "actions": [
        {
          "properties": {
            "name": "set BPOCORE_IP"
          },
          "id": "runCommand"
        }
      ]
    }
  },
  "creator": {
    "name": "jgroom",
    "email": "jgroom@ciena.com",
    "created": 1517746538340,
    "userId": "d2fe461b-8d23-422a-b45e-6b8e1c868e6a"
  }
}
</details>

Result:
UI banner:
You are missing a mandatory parameter getPort. For more information, please visit http://docs.codenvy.com/user/project-lifecycle/#configuration-reference

**OS and version:**    

Ubuntu 16.04
Che 6.0.0

**Comment by ghost** [comment]
@jgroom33 please follow instructions here https://www.eclipse.org/che/docs/6/che/docs/servers.html

**Comment by jgroom33** [comment]
Thanks @eivantsov 
IIRC, the previous version docs state that only EXPOSE in the Dockerfile is necessary.
The method you noted works great.
