### ISSUE TITLE
Che tries to remove the non-existing OpenShift namespace

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#8611]
### Description
In Che, we create OpenShift project lazily at moment of getting our internal representation of OpenShift client( this happens on the first need of OpenShift API call). On the moment of the workspace creation, there is no any interaction with OpenShift API so we have no OpenShift namespace for this workspace yet. When we will try to remove the workspace it will trigger the removal of all related OpenShift objects and in case of relation 1 namespace to 1 workspace we will get next error in master Che logs:
<details>
<summary>Failure executing: DELETE</summary>

```
2018-02-05 13:41:17,446[nio-8080-exec-7]  [ERROR] [o.e.c.a.c.n.EventService 109]        - Failure executing: DELETE at: https://172.19.20.43:8443/apis/project.openshift.io/v1/projects/workspace4nfjxapkb4tqz2q0 . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "developer" cannot delete projects.project.openshift.io in the namespace "workspace4nfjxapkb4tqz2q0": User "developer" cannot delete projects.project.openshift.io in project "workspace4nfjxapkb4tqz2q0".
```
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: https://172.19.20.43:8443/apis/project.openshift.io/v1/projects/workspace4nfjxapkb4tqz2q0 . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "developer" cannot delete projects.project.openshift.io in the namespace "workspace4nfjxapkb4tqz2q0": User "developer" cannot delete projects.project.openshift.io in project "workspace4nfjxapkb4tqz2q0".
```

</details>

### Reproduction Steps
  1. create a new workspace (not running it)
  2. remove the workspace

Also, take a look at attachments:
![delete_failed](https://user-images.githubusercontent.com/12269156/35807562-caed6706-0a8b-11e8-8ae4-a8a8bfae6626.gif)

**Comment by sleshchenko** [comment]
Fixed by https://github.com/eclipse/che/commit/d5707e2626fc5bb1f8e23d8b8469ab973adadd66
