### ISSUE TITLE
Investigate unexpectedly stopping a workspace after consuming DirectUrlFactoryWithSpecificBranch

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#8616]
### Description
* Sometimes after performing the DirectUrlFactoryWithSpecificBranch the workspace which produced is stopped.  I've reproduced this several times - locally in the multithread mode.
We should provide more information and fix it.

### Reproduction Steps
As possible solution for reproducing launch all tests from 'factory' package in the multithread mode (3 threads).
**OS and version:**    
Chrome browser, Fedora 25, Che 6.0.1
**We have next screenshot after problem:** 
![org eclipse che selenium factory directurlfactorywithspecificbranch factorywithdirecturlwithspecificbranch_q1li30lk](https://user-images.githubusercontent.com/1640058/36092628-b07e7760-0ff0-11e8-9f44-c5caf717417b.png)

And logs like: ```SEVERE _app-0.js 17266:125 Error: org.eclipse.che.api.promises.client.OperationException: Can't load Factory. Workspace is not running```

**Comment by dmytro-ndp** [comment]
Should be fixed by issue #8667.
