### ISSUE TITLE
JDT LS Quick Fix action doesn't show any proposals

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#8617]
### Description
 
JDT LS Quick Fix action doesn't show any proposals.

### Reproduction Steps

1. Open a Java file.
2. Introduce a local String variable.
3. Set cursor after the variable and call Quick Fix action (Alt + Enter).

WRONG: No proposals are present in the opened pop-up:
![screenshot from 2018-02-05 17-38-23](https://user-images.githubusercontent.com/7668752/35813172-9e856e9c-0a9b-11e8-9817-4db4950f8d77.jpg)

**OS and version:**    
JDT LS branch
**Diagnostics:**

**Comment by tsmaeder** [comment]
@vinokurig class file or source file? If it's a class file, it's to be expected, because you can't fix a file you don't have in source. Also: what file are you looking at?

**Comment by vinokurig** [comment]
@tsmaeder You are right, the description is a bit wrong, it's a Java source file.

**Comment by vinokurig** [comment]
> Also: what file are you looking at?

It's a `GreetingController.java` from Spring sample project

**Comment by tolusha** [comment]
It works when cursor before the variable.

**Comment by vinokurig** [comment]
@tolusha master version CHE shows proposals if the cursor is either before or after the variable.
