### ISSUE TITLE
Save output of terminal sessions when stopping workspace

### ISSUE THREAD

**Issue by skryzhny** [eclipse-che/che#8622]
I was working in terminal session and then suddenly left room for some time.
In that time Idler decided to stop workspace.
Now I have no way to see output of commands, but seeing useless massages about workspace-agent internals.

Can we somehow store state or just text from terminals when stopping workspaces?
It may be not default behaviour, but for automatic stops initiated by IDLERS  this is MUST HAVE feature.

### Reproduction Steps
Try to put some important info in terminal and let IDLER stop your workspace.

**OS and version:**    
Codenvy 5.22.1 but probably all che 5.x and che 6.x

**Comment by gorkem** [comment]
@skryzhny Can you check Che7 if it has the behaviour you want?
