### ISSUE TITLE
wait_until_che_is_available.sh not found

### ISSUE THREAD

**Issue by jcordes73** [eclipse-che/che#8625]
### Description
wait_until_che_is_available.sh not found

### Reproduction Steps
Following the instructions at https://www.eclipse.org/che/docs/6/che/docs/openshift-multi-user.html for OCP 3.6:

git clone https://github.com/eclipse/che
cd che/dockerfiles/init/modules/openshift/files/scripts
export ...
./deploy_che.sh && ./wait_until_che_is_available.sh

**Diagnostics:** 
wait_until_che_is_available.sh is not included in the repo.

This looks like a documentation issue as actually deploy_che.sh seems to have all the logic for checking if che is available.

Omitting wait_until_che_is_available.sh deployment works fine.

**Comment by ghost** [comment]
Thanks for noticing. Fixed by this PR https://github.com/eclipse/che-docs/pull/351
