### ISSUE TITLE
replace_stacks.sh not found

### ISSUE THREAD

**Issue by jcordes73** [eclipse-che/che#8626]
### Description
Documentation at https://www.eclipse.org/che/docs/6/che/docs/openshift-multi-user.html points to the usage of replace_stacks.sh

"In both cases, you can additionally run replace_stacks.sh that will replace Che upstream stacks with the ones currently used in OSIO flavored Che."

However, this script is not included in the repo.

### Reproduction Steps
git clone https://github.com/eclipse/che
find che -name "replace_stacks.sh"

**OS and version:**    
RHEL 7.3

**Diagnostics:**

**Comment by ghost** [comment]
Thanks. Fixed by this PR https://github.com/eclipse/che-docs/pull/351
