### ISSUE TITLE
Make it possible to close Proposals window via Esc

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#8628]
For using **quick fix** feature need to open the window with proposals. But we can't close this window by using some hotkeys.

1. The first improvement is : make it possible to close this window via `Esc` button 
2. The second one is: to close already opened window if the new one is opening.

**Comment by svor** [comment]
Maybe will be fixed by https://github.com/eclipse/che/pull/8374

**Comment by svor** [comment]
Fixed

**Comment by svor** [comment]
If the window does not have any proposals it is not possible to close it by Esc otherwise it's ok

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/19)
