### ISSUE TITLE
User creation using Rest API does not work.

### ISSUE THREAD

**Issue by jayden-ko** [eclipse-che/che#8629]
It doesn't seem to be possible to create a new user using the REST API, using the latest trunk of Che 6 & Che 5.22.1 on multiuser mode.

But it works well in single user mode.

Reproduction Steps:

Browse to the Swagger UI for the Che installation (http://{SERVER_IP}:8080/swagger/).

Create a new user - expand the "user" heading, then expand [POST] /user and enter the following as the body.
--- request body ---
`{
  "name": "test",
  "id": "test",
  "password": "test12345",
  "email": "test@test.com"
}`

I created a token through the rest api using curl.
--- creating token ---
` curl --data "grant_type=password&client_id=che-public&username=admin&password=admin" http://{SERVER_IP}:5050/auth/realms/che/protocol/openid-connect/token`

I got a 'access_token' value. And enter the token editbox.

Then click the "Try it out!" button.

Response Body has following text.
`{
  "message": "User email required"
}`

I have tried several times by changing the contents of the body, but only the same contents are output.

But if i install single user mode che and create user in same swagger, it works well.

Also, take a look at attachments (multiuser mode):

![image1](https://user-images.githubusercontent.com/31949722/35850496-6adb6100-0b68-11e8-94b3-495f3f50f56b.png)

![image2](https://user-images.githubusercontent.com/31949722/35850517-75a1f0fe-0b68-11e8-9ecd-9fab67961d25.png)

**Comment by ghost** [comment]
@chisong-yu that's probably leftovers from single user Che. Users are created in Keycloak.


POST at  http://172.19.20.180:5050/auth/admin/realms/che/users

```
{"enabled":true,"attributes":{},"emailVerified":"","username":"developer12","email":"ivantsoft1@gmail.com","firstName":"Eugene","lastName":"Che"}
```

**Comment by jayden-ko** [comment]
Thank you, eivantsov.
It works fine with that url.
I'll use the rest API of keycloak directly.
But the url('http://{SERVER_IP}:8080/api/user') that swagger showed seems to have an error.
Thank you again.
