### ISSUE TITLE
Npm cannot connect to registry server

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#8631]
### Description
Npm cannot connect to registry server in che-dev container.

### Reproduction Steps

**OS and version:**    
- Macos 10.13.3
- Che-dev:nightly
- Node 6.11

**Diagnostics:** 
Npm error
Invalid protocol: docker.for.mac.http.internal

**Comment by ghost** [comment]
@cenkce i think this is not a Che issue but rather your local network setup issue. 

Can you share some steps to reproduce"?

**Comment by cenkce** [comment]
1. docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock \
-v $PWD/dev:/data \
-e "CHE_PREDEFINED_STACKS_RELOAD__ON__START=true" \
-e "IMAGE_CHE=eivantsov/che:js" \
eclipse/che start
2. Add workspace, select JS Plugin Tools and create workspace
3. Open the workspace, installDeps and installPlugin or npm i

**Comment by cenkce** [comment]
I can ping to registry.npm.org via workspace terminal but can't ping to https version. Npm gave network error and couldn't connect to npm server. And I configured npm proxy as docker.for.mac.http.internal:3129, then gave error above.

**Comment by ghost** [comment]
@cenkce that's rather a Docker issue - can you just start any image and run npm install there?

I cannot reproduce this one on my local machine.

**Comment by cenkce** [comment]
I ran node:9 and npm worked.

**Comment by cenkce** [comment]
And there is no problem in node:7 as well

**Comment by cenkce** [comment]
I can just run as root in che container

**Comment by cenkce** [comment]
I open the IDE then I run '**$ npm i**'  and npm gives network error. I run "**$ sudo su**" then run "**$ su user**" and npm starts to connect server. When I initially open the IDE, I can't work it as the user

**Comment by cenkce** [comment]
When I execute installPlugin command and then npm gives error

npm ERR! network tunneling socket could not be established, cause=connect EINVAL 0.0.12.57:80 - Local (0.0.0.0:0)
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
 
But When I run "npm i ", it works.

**Comment by ghost** [comment]
@cenkce Che does not interfere with any Docker network settings. 

You may just run che-dev image without Che, clone the  project https://github.com/evidolob/che-js-plugin and execute two commands.

Let's take Che out of equation for a while.

**Comment by cenkce** [comment]
When I manually executed command lines, everything works. And I'll try your recommendation.

**Comment by eivantsov** [comment]
Closed as cannot reproduce.
