### ISSUE TITLE
Make Debug view tabbed (like editors / machines)

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-che/che#8632]
### Description

Feature request: Be able to have tabs that are openable/closeable/rearrangeable for the various Debug views, like they are for machine processes or editor tabs.

I envision that the tabs start with a default set of Debug views open, and allow the "+" for the tabs to allow additional tabs to open. For example, if a particular debug backend supports it, show registers, memory, disassembly, console, etc.

**Comment by jonahgraham** [comment]
This is something I am working on now. I am planning on reusing org.eclipse.che.ide.ui.multisplitpanel.SubPanel to achieve this.

**Comment by gorkem** [comment]
Closing as we are no longer active on Che 6 editor
