### ISSUE TITLE
Unable to open dashboard without clearing cache if API war as broken before

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#8646]
### Description
Unable to open dashboard without clearing cache if API war as broken before.

### Reproduction Steps
1. Simulate case when API war fails. For example, configure an invalid value for a configuration attribute. So start Che with the following command
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/.che:/data -e CHE_WORKSPACE_POOL_TYPE=invalid eclipse/che-cli:nightly start --skip:pull
```
2. Check Che Server logs.
3. Open dashboard.
4. Stop Che and rerun with right configuration 
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/.che:/data -e CHE_WORKSPACE_POOL_TYPE=cached eclipse/che-cli:nightly start --skip:pull
```
5. Check Che Server logs.
6. Try to open dashboard.
Actual: Dashboard can't be loaded.
Expected: Dashboard is loaded.

<details>
<summary>More see screencast</summary>

![cacheissue](https://user-images.githubusercontent.com/5887312/35906896-e3a27b3c-0bf4-11e8-8a69-6d4da923b3aa.gif)

</details>

**OS and version:**    
Doesn't matter

**Diagnostics:** 
The reason why it happens is that first time when API is unavailable dashboard loaded `IDE.html` with caching information in response headers instead of getting an error.
The second time browser uses cached IDE.html instead recall API.

**Comment by garagatyi** [comment]
PR #9168 fixes caching problem for API URLs, but this issue is more common and won't be fixed by this PR
