### ISSUE TITLE
Unable to clone the code ffrom gogs/gitlab

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#8665]
Hi,

I am using Multi-user Eclipse-che on openshift.

Openshift:3.6
Eclipse-che: 6.1.0-SNAPSHOT
It is properly deployed on to openshift. But when I tried to Import project from Gogs/Gitlab.....it is not able to import the project..It is truing to import import import....it is taking more than 5 minutes...But still not able to Import the project....

![che1](https://user-images.githubusercontent.com/33144388/35957310-f7758dda-0cc0-11e8-88f9-4c2ec28f92ae.PNG)

**Comment by ghost** [comment]
@LahariGuntha are you able to do git clone in the terminal? Is this a public repo?

**Comment by LahariGuntha** [comment]
Hi,

I am able to Import the code now.I did not modify anything...but now it is working fine.I was able to clone the code from Gogs...But after making changes and pushing back to the repo it is throwing 
"Failed to push to the repository"

![che2](https://user-images.githubusercontent.com/33144388/35963537-07180e60-0cdb-11e8-9ae0-2710945cf655.PNG)

**Comment by ghost** [comment]
@LahariGuntha you cannot push to https repo. Use ssh protocol instead and setup ssh keys for your server.

**Comment by LahariGuntha** [comment]
Hi,

I was able to push back to https repo Gogs in one of my environment...Where my Gogs and Eclipse-che are both in Openshift...It worked fine without setting any ssh keys...

But I have another Scenario where my Gogs is in Openshift and Eclipse-che is launched as a container in a VM that is outside Openshift cluster.So in this case I was getting below error..
"401 Unauthorized"
after some time when I tried again I got the below Error:
"cannot open git-receive-pack"

What might be the main reason for this change in the behaviour??

**Comment by ghost** [comment]
This error may mean that your git server hostname isn't resolved in your workspace pod

**Comment by LahariGuntha** [comment]
Hi,
I have updated the /etc/hosts file of my workspace conrtainer.....
So it was able to resolve the hostname...

But I am facing the Isuue as mentioned above.....

"Failed to push to the repository"
![che2](https://user-images.githubusercontent.com/33144388/36012908-4c4ecdd2-0d87-11e8-88fa-cbd6261a75fc.PNG)

When I click on the URL that is mentioned in the Image I am getting the following o/p:
![che5](https://user-images.githubusercontent.com/33144388/36012965-91d56abe-0d87-11e8-80a2-957344ba9cdb.PNG)

**Comment by LahariGuntha** [comment]
when I try to force push...i.e Git >Remotes > Push ...
 I get the error as:
Project name: openshift-tasks
http://gogs@gogs-cicd.apps/gogs/openshift-tasks.git: 401 Unauthorized

**Comment by ghost** [comment]
You cannot push to https repo. Use ssh protocol instead. Alternatively, you may try using credentials in https url

**Comment by LahariGuntha** [comment]
Yeah ...I have tried using credentials in the URL....
eg:

http://username:password@gogs-cicd.apps/gogs/openshift-tasks.git

It was able to clone properly...
But it was not able to push it to the Repo...

I tried the same with a repo in Gitlab...by passing the User credentials..in the Url...Pulling and pushing to Gitlab is working fine...It is throwing  "401 Unauthorized" error when I am trying to do the same with Gogs....

**Comment by LahariGuntha** [comment]
For the "Gogs" that is present on Openshift...and Eclipse-che that is present as a container in a VM...where the VMis outside of the Openshift's cluster...I am facing this Isuue....

if "GOGS & CHE" if both are present  on the Openshift then I was able to successfully clone and push the code back to the Repo..
