### ISSUE TITLE
Selenium tests of package 'org.eclipse.che.selenium.factory' are trying to delete not existed workspace

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#8667]
### Description
It can be reproduced randomly on CI. Most often this happens with `DirectUrlFactoryWithRootFolder` test in tearDown() method.
I think problem on selenium test side. 
**Example:** https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-docker/173/Selenium_tests_report/ 
In this example looks like the test tried to delete workspace from github testsuite (chepullreq3).
```
[ERROR] tearDown(org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolder)  Time elapsed: 104.05 s  <<< FAILURE!
org.eclipse.che.api.core.NotFoundException: Workspace with name 'chepullreq3' in namespace 'che' doesn't exist
	at org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolder.tearDown(DirectUrlFactoryWithRootFolder.java:63
```

**OS and version:**  Chrome browser, CHE-6.0.1 SNAPSHOT

**Comment by dmytro-ndp** [comment]
The problem caused by usage of one workspace with name = \<github username> in three tests simultaneously: 
- DirectUrlFactoryWithKeepDirectory
- DirectUrlFactoryWithRootFolder
- DirectUrlFactoryWithSpecificBranch 

Solution: run those tests one-by-one.
