### ISSUE TITLE
Unexpected interrupting of start ws agent after consuming a factory

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#8671]
### Description
This usually happens with DirectUrlFactoryWithSpecificBranch test on multiuser/docker assembly on CI. Looks like infrastructure problem. 
**Example:**
![org eclipse che selenium factory directurlfactorywithspecificbranch factorywithdirecturlwithspecificbranch_kwlujtjl](https://user-images.githubusercontent.com/1640058/35965850-cb3235c6-0cc4-11e8-8313-58988d4e1b82.png)

**OS and version:**   Chrome browser, Che-6.1.0 Snapshot

**Comment by skabashnyuk** [comment]
Any errors on ws-master at this time? 
How to reproduce it?

**Comment by musienko-maxim** [comment]
This produces randomly about 1 time per week. But i try to provide logs if problem will reproduced again

**Comment by artaleks9** [comment]
When the load on the CI server was reduced to two threads the bug is not reproduced.
