### ISSUE TITLE
After deleting a project all projects whose names begin with the name of the deleted project will be removed from a workspace config

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#8674]
**Reproduction Steps:**
1. Create and start a workspace from the **Blank** stack with two **blank-project** projects.
2. Open  workspace details of this workspace.
3. In the **Projects** tab open a project setting of the first created project(**blank-project**).
4. Delete this project by the **Delete** button.

**Expected behavior:**
The **blank-project** project is deleted from the projects list and **blank-project-1** still exists.

**Observed behavior:**
The projects list is empty. Both projects were deleted from workspace config.

**OS and version:**
Che 6.1.0; Chrome 63.0; Fedora 25

**Additional information:**
![nimbus-record-video-2018-02-08-11-55-57](https://user-images.githubusercontent.com/7760565/35966688-3a2f441c-0cc7-11e8-88d3-6fe51a322ee2.gif)

**Comment by ashumilova** [comment]
It's not a dashboard issue - same behavior happens in pure IDE: project removal, causes the deletion of other projects, which contain that name. Here ProjectService has to be fixed.
