### ISSUE TITLE
UI for workspace loading application

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#8682]
#8556 needs a proper UI containing a simple loader and field with log messages.

**Comment by benoitf** [comment]
hello, do we have a mockup ?

**Comment by ashumilova** [comment]
no, we do not

**Comment by vitaliy-guliy** [comment]
First steps. Animating loader with output area at the bottom.

![wsloader 01](https://user-images.githubusercontent.com/1655894/36032495-e0fd8962-0db6-11e8-9ba9-7e8778561eae.png)

Output can be maximized by simple clicking.
![wsloader 02](https://user-images.githubusercontent.com/1655894/36032639-532c154e-0db7-11e8-9842-23e5649ea328.png)

**Comment by slemeur** [comment]
@vitaliy-guliy : Great progress.

Can you confirm: This loader is displayed while the container for the new IDE is being started and is displaying only the outputs of that container. Correct?

**Comment by vitaliy-guliy** [comment]
@slemeur Yes, this loader is displayed while the workspace is loading and displaying machine logs.

**Comment by benoitf** [comment]
@vitaliy-guliy what is displayed with openshift ?

**Comment by vitaliy-guliy** [comment]
@benoitf I think only the loader will be displayed and no outputs. Openshift doesn't send any output to the client.

**Comment by benoitf** [comment]
@vitaliy-guliy I have access to machine logs through openshift console so I suppose output are somewhere

**Comment by benoitf** [comment]
@vitaliy-guliy but it's more a platform issue remark
