### ISSUE TITLE
Unable to bring Up New workspace

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#8687]
Hi,

Hi,

I am using Multi-user Eclipse-che on openshift.

Openshift:3.6
Eclipse-che: 6.1.0-SNAPSHOT
It is properly deployed on to openshift.
It was working fine earlier.But suddenly I am unable to create even a workspace now...Wen I try to create a workspace it is throwing me the below Error:
Start workspace Error:
Unexpected response (401 Unauthorized), to the authorization request. Missing header:[Location]!

When I see in the SYSTEMS DEV CONSOLE:
che-eclipse-che.ocp-allinone.project.matrix.com/api/workspace/workspaceyjcf84a5s4lxngm4/runtime?environment=default
Failed to load resource: the server responded with a status of 500 ()
![che4](https://user-images.githubusercontent.com/33144388/36012655-a7c38c68-0d85-11e8-8279-4370eb7b3e78.PNG)

What might be the reason for this reason??

**Comment by LahariGuntha** [comment]
Hi,

Got this Issue resolved....

It is because of the change in the credentials of the Openshift user that is used while launching Eclipse-che in Openshift.
I have set these ENV while deploying the Eclipse-che on Opensshift
"CHE_INFRA_OPENSHIFT_USERNAME"
"CHE_INFRA_OPENSHIFT_PASSWORD"...

There was a change in the password...so it used to throw the above Error...

When I reset the password to earlier one i.e the password that I gave at the time of deployment of che on Openshift....then it is working fine....

But in future if there is a change in password it will not work again...Is there any way to overcome this Isuuee??

**Comment by ghost** [comment]
@LahariGuntha https://github.com/eclipse/che-docs/pull/355 You may use these instructions

**Comment by LahariGuntha** [comment]
Hi Eivanstov,

I have tried 
oadm policy add-cluster-role-to-user self-provisioner system:serviceaccount:eclipse-che:che

provided in the docs....
Then tried to create a workspace...
Then it is throwing below error:

![che6](https://user-images.githubusercontent.com/33144388/36091809-153a1ad2-100b-11e8-82a9-b0a745b8ce56.PNG)
