### ISSUE TITLE
How to Use Local volumes Instead of Persistent Volumes??

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#8690]
Hi,

Is there an option to configure multi-user Eclipse-che that is deployed on Openshift  to use the local volumes instead of using Persistent volumes???

Is there any way so that I can configure to use local volumes??

**Comment by ghost** [comment]
@LahariGuntha there is no such a possibility. Eclipse Che uses PVCs

**Comment by gorkem** [comment]
@LahariGuntha What is the motivation for using local volumes instead of PVs?

**Comment by LahariGuntha** [comment]
Hi Gorkem,

We have deployed Eclipse-che in Openshift all in one where  we will be having a single node.The node has reached its maximum number of PVC's atttached to it.We were not able to connect more pVC's to that node.Because of this my Ecliopse-che workspace is not getting Created...Workspace pod is not getting up because it was Unable to attach any more PVC' sto that node..

So I just had a query to know whether we can use Volumes instead of PVC's

**Comment by ghost** [comment]
@LahariGuntha do you use a recycler pod for PVs?

**Comment by LahariGuntha** [comment]
We are currently using OCP 3.6 which uses dynamic provisioning instead of Recycler pod

**Comment by eivantsov** [comment]
@LahariGuntha you may use a commotn PVC strategy. You can find a corresponding env in Che deployment. This way all workspaces will use one PVC.
