### ISSUE TITLE
Add an ability to use host-based routing instead of path-based for k8s infra

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#8694]
### Description
Many applications expect to be the only one application deployed on a host. And they may use absolute links. In case of using path-based routing, such applications will be broken.
An example of it is [che-samples/web-java-spring](https://github.com/che-samples/web-java-spring).
There is the [main page](https://github.com/che-samples/web-java-spring/blob/master/src/main/webapp/index.jsp#L2) that redirects users to `spring/hello` page. But in case of host-based routing, it doesn't work.
<details>

<summary>See screencase how it works</summary>

![web-spring-k8s](https://user-images.githubusercontent.com/5887312/36026222-cacd3a06-0d9e-11e8-9264-d23df0617df6.gif)

</details>

So it is needed to investigate host-based routing for k8s-infra and add it as an option or replace current path-based routing.

**Comment by eivantsov** [comment]
This makes dev flow on k8s almost impossible

**Comment by riuvshin** [comment]
this also blocks testing k8s infra on CI

**Comment by skabashnyuk** [comment]
@eivantsov what do you mean?

**Comment by riuvshin** [comment]
@skabashnyuk have you seen attached screencast? it is not possible to access your application started in a WS to check your changes and even debug it.

**Comment by skabashnyuk** [comment]
@riuvshin understood

**Comment by eivantsov** [comment]
Looks like @guydaichs's PR fixes this one. Worked for me
