### ISSUE TITLE
Create TS lib implementing JSON RPC client

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#8699]
There is need to create light lib on TypeScript, that implements the client for JSON RPC communication - to be reused in such clients as - dashboard, workspace loading application etc.

**Comment by gorkem** [comment]
Is this a generic library or has Che workspace specific types built-in.

**Comment by ashumilova** [comment]
This one for generic and this one https://github.com/eclipse/che/issues/8700 for Che specific.

**Comment by svenefftinge** [comment]
I don't think there is a need for another generic library, as `vscode-jsonrpc` works very well.
Also you should have a look at https://github.com/theia-ide/theia/blob/master/packages/core/src/common/messaging/proxy-factory.ts which we use for all JSON-RPC protocols.

**Comment by akurinnoy** [comment]
thanks, @svenefftinge, we came to the same conclusion to use `vscode-jsonrpc`

**Comment by akosyakov** [comment]
there is `vscode-ws-jsonrpc` implemented on the top of `vscode-jsonrpc` for web sockets, also used by `Theia`

**Comment by akurinnoy** [comment]
There are things left to do:
- run WebSocket related tests separately from other because it needs to start and stop fake backend server;
- refactor and publish the updated workspace client;
- update the WIP pull request for using workspace client in Dashboard and start CI tests again;
