### ISSUE TITLE
Build dependencies and instructions without docker/openshift

### ISSUE THREAD

**Issue by fengshaun** [eclipse-che/che#8712]
For environments where docker is not the right choice, or visibility into the running software is required, it would be helpful to have at least a list of dependencies and brief build steps. This would allow others to deploy Che in the manner most appropriate for them.

**Comment by fengshaun** [comment]
hmm alright, I guess I could sift through dockerfiles to see how it's set up. Thanks.

**Comment by nicaiseeric** [comment]
@fengshaun i'm running into the same concerns, did you succeed to run chethrough tomcat ? if yes could please share your hints?

**Comment by nicaiseeric** [comment]
@fengshaun i'm running into the same concerns, did you succeed to run che through tomcat ? if yes could please share your hints?

**Comment by fengshaun** [comment]
No, I ended up not deploying it due to the hassle. Sorry :(
