### ISSUE TITLE
Cannot create custom stack from Dashboard

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#872]
Steps to reproduce: 
Go to the Dashboard -> Click New Workspace -> Select Custom Stack and try to apply your stack.
**Wrong**: the stack has not applied, in fact - has been used: codenvy/node recipe (first selected)

**Comment by ddementieva** [comment]
(Comment by Jenkins CI server)

SUCCESS: Integrated in ![](http://ci.codenvy-dev.com/jenkins/images/16x16/blue.png) [che-ci-master #747](http://ci.codenvy-dev.com/jenkins/job/che-ci-master/747/)  
CHE-894: fix creating custom stack from Dashboard (okurinnyi@codenvy.com: [a9f2b25c4d3b012b7403fcfc4211a8ba8e4ea356](https://github.com/eclipse/che/commit/a9f2b25c4d3b012b7403fcfc4211a8ba8e4ea356))
- dashboard/src/app/workspaces/create-workspace/create-workspace.controller.js
