### ISSUE TITLE
Set up Theia Debugger Project

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8720]
Set up a project complete with build infrastructure for a debugger extension for Theia. 
The project will live at github.com/eclipse/<to be determined>

The goal is that people can just check out this project and start coding.

**Comment by tolusha** [comment]
The project will live here https://github.com/theia-ide/theia/tree/vscode-debug-protocol

**Comment by tsmaeder** [comment]
The idea I had was to set up a project structure with the appropriate dependencies, etc. Did I miss something?

**Comment by tolusha** [comment]
It seems I misunderstood the task.
