### ISSUE TITLE
Update Libraries, etc. based on JDT notifications

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8721]
When we import Maven projects, for example, the structure of Java projects changes, for example, the classpath (shown as "libraries" in Che) changes. JDT notifies listeners of changes to Java elements. We should listen to those events and send notifications to Che to update the UI.
This would allow us to implement things like "reimport maven project" in an asynchronous manner.

**Comment by tsmaeder** [comment]
Depends on https://github.com/eclipse/eclipse.jdt.ls/issues/522

**Comment by vrubezhny** [comment]
Depends on https://github.com/eclipse/che-ls-jdt/pull/44
