### ISSUE TITLE
Create Theia plugin for management SSH keys

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8727]
### Description
The goal is to have ability generate, upload and remove existing SSH keys. Mainly we need this to providing access to the VCS providers like GitHub 

- [x] UI Widget for SSH key management for Theia #8737
- [x] Develop server-side for SSH key management for Theia #8738

**Comment by dorinburcea** [comment]
Is this extension already working? 

I use Che 6.19 with theia. When  I try to generate SSH keys for VCS github.com but error.

**Comment by sunix** [comment]
I am not sure we have any complete and usable workflow for that at the moment. @vparfonov ? we are focussing on integrating VSCode Github extension right ?
