### ISSUE TITLE
Che 6 on OSO

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#8729]
### Description
The goal of this issue is to properly support Che on OSO and provide a simpler installation flow as well as dedicated documentation and tests.

Note:
- Che will not be running on OSO Starter, those requirements target only OSO Pro.

**Single-User**
Che single-user is running on OSO Pro, but this installation makes Che's url available to any user without requiring any authentication. It is possible to install Che single-user secured behind keycloak and we need to provide documentation on how to do that.  

**Multi-User**
The installation of Che 6 multi-user on OSO Pro may lead into various errors. We need to properly test the installation on OSO Pro and try to simplify the installation to avoid errors. 

### List of stacks
The list of stacks running on OSO Pro should be identical as the list of stacks of Che running on OCP.

### Installation
The installation of Che on OSO could run into various errors and we need to study different solutions to make the process simpler and more interactive. For example, the installation flow requires to setup a certain set of environment variables which in certain case should not be required. This could impact the steps to get Che installed on any OpenShift flavors.
[x] Simplify the install of Che multi-user on OSO Pro - https://github.com/redhat-developer/rh-che/issues/542 
[x] Remove the build image step (which is not available on OSO)
[ ] Make Che available under Service Catalog on OSO Pro

### Documentation
[x] Introduce specific documentations on how to deploy on OSO.

### Tests
Have proper tests in place to ensure the stability of the installation of Che on OSO.

**Comment by garagatyi** [comment]
Here is my 0.05c:
Should we setup unsecured Che inside of secured OSO at all? Maybe it is better to provide authentication out of the box and describe in docs how to tweak or completely change/remove it?
