### ISSUE TITLE
Log related test class name when creating test workspace

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8733]
### Description
It might be quite hard to recognize which workspace certain test is consuming of when several tests are being executed simultaneously. So, it would be quite useful to have this information in text log, for example:
> 2018-02-12 15:48:34,653[onPool-worker-1]  [INFO ] [c.c.TestWorkspaceServiceClient 201]  - Workspace name='workspace5xhwm8' and id='workspace8qma7an4o63qusf2' created **and linked with field 'org.eclipse.che.selenium.miscellaneous.DialogAboutTest#testWorkspace'**

**Comment by rhopp** [comment]
Not investing time in old selenium tests. Closing.
