### ISSUE TITLE
UI Widget for SSH key management for Theia 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8737]
### Description
Introduce some simple UI that allow view/add/remove and upload SSH keys. This is part of #8727 
Unfortunately we don't have any mock up so details will be discussed during following sprint

**Comment by azatsarynnyy** [comment]
@slemeur I've fixed your notes after today's sprint review. Could you, please, validate it?

![screenshot from 2018-03-06 16-58-17](https://user-images.githubusercontent.com/1636395/37039630-a1d0deca-2160-11e8-84b8-4c86c160e46e.png)
