### ISSUE TITLE
Client side OAuth Authorizations API for Theia 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8739]
### Description
Need to introduce same or close to same behavior that we have now in Che GWT IDE.
This is will be useful for communicate with VCS providers that support OAuth Authorizations. 
(Like GitHub) Current server side implementation [OAuthAuthenticationService](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticationService.java )

**Comment by RomanNikitenko** [comment]
the plugin is placed https://github.com/RomanNikitenko/che-theia-oauth-authentication-plugin
