### ISSUE TITLE
Ability to display the github repositories by user and cloning them in Theia IDE

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8741]
### Description
Part of  #8740. Need to develop UI widget for showing repository information by user. Depends on  #8739

**Comment by slemeur** [comment]
Let's focus only on:
- Ability to display the repositories
- Cloning the repository.

That will be a great first iteration.

**Comment by vzhukovskii** [comment]
@slemeur demo video: https://drive.google.com/open?id=19Y7zVklAJ41CDUGjatIBm_22QZjhuPQw
