### ISSUE TITLE
Deploy Multi-User Che on Kubernetes

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#8745]
### Description
There is a yaml file for deploying Single-User Che.
It is needed to provide a way for deploying Multi-User Che on Kubernetes.

**Comment by gorkem** [comment]
This seems to be already handled as part of the kubernetes SPI

**Comment by sleshchenko** [comment]
@gorkem I haven't heard that it is already implemented. Do you know where it is implemented and how is solved an issue with configuring `postgresql` and `keycloak` containers (source to image feature is used for OpenShift)

**Comment by gorkem** [comment]
@sleshchenko I imagine the helm chart is handling that @l0rd Is that the case?

**Comment by l0rd** [comment]
https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/che-kubernetes-helm/readme.md#multi-user

**Comment by sleshchenko** [comment]
@l0rd Thanks for pointing. 
@gorkem You're right, deploying of Che multiuser is covered helm chart.

And answering my question 
> how is solved an issue with configuring postgresql and keycloak containers?

Looks like Postgresql doesn't require configuration and setting the corresponding env variables is enough.
Keycloak container is configured with [Job](https://github.com/eclipse/che/blob/8c7ebc6751e05cd29c8f04a6dabcdd98f1069458/dockerfiles/init/modules/che-kubernetes-helm/charts/che-keycloak/templates/keycloak-configure-job.yaml)
