### ISSUE TITLE
CI should tag image of latest version of 5.x branch

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#8751]
### Description
Right now docker.io/eclipse/che-server:latest points to Che 6 latest. We don't have anything similar for Che 5. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@riuvshin @l0rd @ibuziuk

**Comment by riuvshin** [comment]
will do

**Comment by riuvshin** [comment]
@garagatyi  pushed alias `5-latest`
