### ISSUE TITLE
Enable code completion (content assist / autocomplete) as you type

### ISSUE THREAD

**Issue by svarlamov** [eclipse-che/che#8761]
### Description
Using both the default Java and Python stacks and projects (I haven't tried the other languages yet), I'm unable to get code completion as I type -- as one would expect in, for instance, VS Code or IntelliJ. When I hit ctrl+space, the completion box pops up, so I'm certain the lang server is functioning -- at least enough to give me correct completion options. I have also read through the dozen or so issues related to content assist in this repo, but most answers tell users that they need to use the key combo. However, I don't believe that this is the intended usage, at least coming from other popular IDEs...

Subsequently, when I go into `Profile -> Preferences -> IDE -> Editor` I have tried using the IDE with the "Show Content Assist automatically" parameter both checked and unchecked and it doesn't seem to make a noticeable difference either way. I have also looked at the `/api/preferences` call, and I see that it is indeed updating the `"contentAssistAutoTrigger":true` value...

In essence, I would like to see if there's any way to have the content assist show up as I type. At the moment, this is basically the only feature stopping us from adopting Che as our primary dev IDE. Thank you all for a wonderful IDE and I'm also hoping that I can help to add GoLang support in the future too :)

**OS and version:**    
Che: Multi-user, Docker, v6.0.0 (Ubuntu 16.04 host)
Browser: Chrome v64 on Windows 10, Ubuntu 16.04 and Mac OS X

**Comment by eivantsov** [comment]
I can confirm I see the same behavior

**Comment by caglar1** [comment]
I am golang developer,
I am waiting for golang intellisense feature
whithout intellisense

**Comment by charlesrichard** [comment]
Is this going anywhere?
