### ISSUE TITLE
investigate failing CHE selenium tests on k8s infra

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#8766]
investigate failing CHE selenium tests on k8s infra
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-k8s/

**Comment by dmytro-ndp** [comment]
@riuvshin: it's interesting to see test workspace logs, and to obtain they you can selenium tests from branch https://github.com/eclipse/che/tree/che-7889.

**Comment by riuvshin** [comment]
tests are failing because of internal links are not available for chromenode containers. tests are working in local mode. to make tests working it should be possible to set hostname for ingresses
which is part of this epic https://github.com/eclipse/che/issues/5908
