### ISSUE TITLE
Improving TS syntax highlighting in Theia

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#8774]
As far as the readability and context of the text in editor has impacts on developing process - there is ability to improve syntax highlighting mechanism in Theia - to target customization of this stuff. To start with could try the TS one.

**Comment by gorkem** [comment]
This probably needs issue(s) on the upstream repo as well for visibility.

**Comment by evidolob** [comment]
Fixed by https://github.com/theia-ide/theia/issues/944
