### ISSUE TITLE
Che Terminal adds whitespaces and linebreaks into copied text

### ISSUE THREAD

**Issue by hkolvenbach** [eclipse-che/che#8777]
### Description
When copying text from the Che Terminal (especially relevant for things like SSH keys), it will add whitespaces even though these should not be there. This will break keys in obscure ways which need to be fixed manually by removing all the wrong line breaks and whitespaces.

![line_breaks_from_terminal](https://user-images.githubusercontent.com/26924052/36208330-05bacee6-1199-11e8-8e22-3d748820c98f.gif)

Tested with Chrome 64.
 

### Reproduction Steps

1. Open any text file (without line breaks) from the terminal in Eclipse Che
2. Copy it from the terminal into any other text editor

**OS and version:**    
Ubuntu 16.04, Chrome 64, Che 6.1.0-SNAPSHOT

**Diagnostics:**

**Comment by AndrienkoAleksandr** [comment]
Fixed after [update xterm.js to version 3.3.0](https://github.com/eclipse/che-lib/issues/57.)
