### ISSUE TITLE
Starting Workspace Agent

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#878]
On my local machine I can start a project IDE but when I try to do it remotely it seems to be getting stuck on Loading "Starting Workspace Agent". Not sure what could be causing the issue.

Remote
![image](https://cloud.githubusercontent.com/assets/16562450/14088510/a331d65a-f4f5-11e5-8101-e7fbcbaf926f.png)

Local
![image](https://cloud.githubusercontent.com/assets/16562450/14088523/b444c024-f4f5-11e5-8314-2c32c2c44bdd.png)

**Comment by TylerJewell** [comment]
You have to do some additional networking configuration when browsers are no longer localhost.  See the specifics here.
https://eclipse-che.readme.io/docs/networking

**Comment by james10174** [comment]
Where do I set the CHE_DOCKER_MACHINE_HOST variable at in windows 8? Is this a system property I must set through system properties environment variables or is there a file in the che install directory I need to add it to?

**Comment by TylerJewell** [comment]
That is just a system environment variable.  You can either set it on the command line with "set CHE_DOCKER_MACHINE_HOST=" or you can permanently set it in your windows environment variable configuration.

But I think it will be easier for you to configure `machine.docker.local_node_host` in your conf/che.properties file.  Then you just have to restart the server.

**Comment by james10174** [comment]
OK so I modified the bat script to be "<path>/bin/che.bat" run -r:192.168.99.100 and I cannot get workspaces to run on my local machine. When I run without -r:192.168.99.100 it works. What am I missing? Is it the right ip address? Does the vm machine need to be configured somehow to let remote ip address it?

![image](https://cloud.githubusercontent.com/assets/16562450/14097197/4e96b176-f534-11e5-823c-a38824c2e28d.png)

**Comment by ghost** [comment]
There is no need to modify any scripts. You simple pass `-r` parameter when running Che.

As to accessing Che remotely, yes, you should make sure the VM IP is externally accessible, since when loading the IDE your browser will attempt to connect to a workspace agent and terminal that are running inside a VM.

As to why it fails for you locally, I see no good reasons for it. Just tested on Win 8 - works like a charm. In fact, by default, we detect OS type, and use VM IP for server to connect to a workspace. Browser uses the same URL to establish ws:// connection with a workspace agent and a terminal.

**Comment by TylerJewell** [comment]
@james10174 If this doesn't solve the problem, I'd like to have a look into your system.

**Comment by james10174** [comment]
@eivantsov Where do I pass -r parameter inside che? Is this parameter provided when creating workspaces or projects? Is the ip address I mentioned above what I need to put for the -r parameter.

Can you explain more in depth your steps in getting it to work in windows 8. Do any preferences for the VM VirtualBox need to be entered in the VM VirtualBox Manager or are all these setup through che server when it starts the VM VirtualBox up?

![image](https://cloud.githubusercontent.com/assets/16562450/14110740/6c573740-f58d-11e5-8737-dde888cf065e.png)

**Comment by ghost** [comment]
`-r` is passed to che.bat

There's nothing special to make Che work on Win 8. You faced an issue with a remote access to Che. For this scenario, you need to make sure your VM can be externally accessed by IP.

**Comment by ghost** [comment]
And yes, it should be VM IP. However, if you access Che from another machine, it won't work, unless you assign a publicly available IP for it.

**Comment by james10174** [comment]
@eivantsov I am on the local machine trying to get this to work with the -r parameter set to ip address above. It does not work. Well one thing to note though is I had to install VirtualBox-5.0.16-105871-Win.exe and DookerToolbox-1.10.3.exe after installing eclipse-che-latest.exe to get things to work without the -r option. Maybe installing VirtualBox-5.0.16-105871-Win.exe after is causing issues?

**Comment by ghost** [comment]
What are the issues? Can you share the entire command line - how you started Che?

Also, screenshots with network-ws in Chrome console will also help. What websocket connections are initiated when ws agents starts?

**Comment by james10174** [comment]
What version of VirtualBox does eclipse-che-latest.exe install?

With -r option
![image](https://cloud.githubusercontent.com/assets/16562450/14111492/8eaee718-f590-11e5-913e-cbbdf206beba.png)

Without -r option
![image](https://cloud.githubusercontent.com/assets/16562450/14111652/25f33e80-f591-11e5-8214-0a6724e70bf4.png)

[https://codedump.io/share/jSLsO1Ixad8U/1/che](url)

**Comment by ghost** [comment]
You have one workspace running! What happens when you press the arror icon on the top right?

**Comment by ghost** [comment]
Also, can you share server logs when error occurs? And I'd like to see what URL is used to establish a ws://connection. You need to hit Network Tab - WS.

**Comment by james10174** [comment]
Got it. I was messing with the ip address on the shortcut script yesterday and forgot to set it back to 192.168.99.100. I had it on 127.0.0.1 when I was testing different ip addresses. I know I tested 192.168.99.100 yesterday and it didn't work. Oh well it works now :)

So now that the local machine works how do I let the VM be accessible via the internet through my router?

**Comment by ghost** [comment]
I haven't tried it myself but I am pretty sure this problem has a lots of search results in Google.

**Comment by james10174** [comment]
Looks like I need to bridge the NAT of the VM. The following looks like a good start. The default I will need to shutdown and the change the network options. I will let you know how it turns out.

![image](https://cloud.githubusercontent.com/assets/16562450/14112246/9075b9a2-f593-11e5-9de2-6934d062e35e.png)

[http://www.howtogeek.com/122641/how-to-forward-ports-to-a-virtual-machine-and-use-it-as-a-server/](url)

**Comment by james10174** [comment]
The default network setting has adapter 1 attached to NAT. I tried to just add to the port forwarding rules but I don't think you can add ranges required 32768-65535. So I tried to attach to bridge and the che server stops at waiting for IP with a ssh timeout. I noticed that ssh forwards host port 60252 to guest port 22. Is there a way to change host port 60252 for ssh to 22 in che? I don't use ssh for anything on my local machine that I know about so I am not to worried about using port 22.

![image](https://cloud.githubusercontent.com/assets/16562450/14112974/91447ee2-f596-11e5-824e-8b14579678fb.png)
![image](https://cloud.githubusercontent.com/assets/16562450/14112994/9d8b4f8c-f596-11e5-8d44-a7184334599d.png)
![image](https://cloud.githubusercontent.com/assets/16562450/14112999/ac5198aa-f596-11e5-95f3-00fccd923c20.png)

**Comment by james10174** [comment]
Maybe there is an easier way. I will see if I can change the ssh default 22 port to port 60252. Then the bridge should work.

**Comment by ghost** [comment]
Well, it is not Che that has set this port forwarding rule. It must be Docker-Machine since, it nees ssh connection to the VM. You are on the right track though.

**Comment by james10174** [comment]
How is the .docker\machine\machines\default machine created. I am having an issue with getting the server to run so I decided to delete the folder and reinstall everything but the folder does not get recreated. Maybe I am missing a step I did before.

**Comment by james10174** [comment]
I had to delete the .docker and .VirtualBox from my home directory using windows 8 then reinstall. I am now going to try to get the remote server working now.

**Comment by ghost** [comment]
Docker machine on windows is quite a pain sometimes. So, starting anew is a good idea overall.

**Comment by james10174** [comment]
Well I couldn't get remote setup on windows 8 to work. So I got out an old machine 2008 machine with amd 64 processor. I installed docker but couldn't get che to work. I think it's because it only had 512MB of ram. I order 2GB which hopefully solves the problem. Seems pretty fast so maybe it will work just fine once I have more ram.
