### ISSUE TITLE
Theia plugin that can read environement

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#8782]
Che specific Theia plugins need to know what workspace Theia container/pod is part of, so that workspace config can be retrieved and analyzed.

There's a need for a tiny Theia plugin that can read environment variables in Theia container. Specifically, workspace ID and Che API endpoint are required first, but other envs might be necessary as well (token).

Ideally, the plugin should either returns all envs and value for a specified env.

**Comment by AndrienkoAleksandr** [comment]
First prototype https://github.com/AndrienkoAleksandr/theia-env-variables-extension

**Comment by AndrienkoAleksandr** [comment]
https://github.com/eclipse/che-theia-env-variables-plugin/pull/1

**Comment by AndrienkoAleksandr** [comment]
Integrated to the Theia core:
https://github.com/theia-ide/theia/tree/master/packages/core/src/node/env-variables
https://github.com/theia-ide/theia/tree/master/packages/core/src/common/env-variables

**Comment by dhananjayharel** [comment]
Will be nice to see an example code to read the Environment Variables

**Comment by azatsarynnyy** [comment]
Hello @dhananjayharel 
Here's the example https://github.com/eclipse/che-theia/blob/a44b0ca2862618d32b283b298a5abeca0c9a341c/plugins/factory-plugin/src/factory-plugin.ts#L19
