### ISSUE TITLE
Need help configuring my Stack/Workspace for an Open Source Project

### ISSUE THREAD

**Issue by terrywbrady** [eclipse-che/che#8785]
### Description
I work on an open source project DSpace (https://github.com/DSpace/DSpace).

I believe that Codenvy could be a great solution for onboarding new developers.

I am having some difficulty configuring my Stack and my workspace for Codenvy.   My definitions are here.
https://gist.github.com/terrywbrady/a37a3a42be9f67e70b9243dfef38793a

#### Here are my questions
- I cloned the Stack for Java/MySql and I believe I have installed postgres on a database server.  I would also be happy to install this on the development server.  
  - Would it be acceptable to add the database service to the DEV machine.  If so, how could I make the postgres install local? 
  - If that is not recommended, how do I determine the hostname for my database server?  I need to add this to a configuration file.
- I need Apache ANT to be included on the DEV server.  I added it as a component, but I think I must need to modify the dockerfile for my Stack.  Do you have any recommendations?

### Reproduction Steps
This is a how-to question rather than a problem to reproduce.

**OS and version:**    
I am basing my stack on an existing Codenvy Stack containing Java/Maven/Tomcat

**Diagnostics:**

**Comment by eivantsov** [comment]
@terrywbrady yes, ideally, you need to build own Docker image and push it to DockerHub.

```
FROM ecllipse/ubuntu_jdk8
RUN sudo <ant installation instructions come here>
```

Reference the resulting image in your composefile

Let me know if you need help with image build

**Comment by terrywbrady** [comment]
@eivantsov , thanks for the additional instructions.  I have been able to make a good deal of progress as a result.

I have encountered an issue which I logged here: https://stackoverflow.com/questions/48814922/create-postgres-extension-in-docker-container

I am currently working around the issue by adding an item to my command palette.

psql -U postgres -d dspace -c 'create extension pgcrypto;'

**Comment by terrywbrady** [comment]
I have resolved this issue.  Thank you
