### ISSUE TITLE
[ERROR] read tcp 192.168.1.2:58748->13.33.194.178:443: read: connection reset by peer

### ISSUE THREAD

**Issue by thyeun** [eclipse-che/che#8786]
OS : Arch Linux 2018.01
docker : 18.02.0-ce
Che : 6.1.0
Mode : Single user (not multi-user)
stack : original stack (not custom make)

I been 24 hours try to upgrade python workspace for the newer version of Che 6.1.0, but sadly i been keep on getting ```[ERROR] read tcp 192.168.1.2:58748->13.33.194.178:443: read: connection reset by peer```

![screenshot from 2018-02-15 11-59-00](https://user-images.githubusercontent.com/1939446/36239825-b8be8ab0-1247-11e8-9c8e-85ae85dd02b4.png)

**Comment by eivantsov** [comment]
@thyeun looks like connectivity issue on your side

**Comment by thyeun** [comment]
no, using che version 5.20.0 successful without any issue, happen only version 6.1.0 

been trying it on two system

1. OS - Ubuntu 16.04 - Che - 5.20.0 , no issue, successful update.
2. OS - Arch linux 2018.01 - Che - 6.1.0, as you can see the result from the picture.
3. OS - Ubuntu 16.04 - Che - 6.1.0, same like second one.
4. OS - Arch linux 2018.01 - Che - 5.20.0, same like first one.

so, what going wrong here?

**Comment by thyeun** [comment]
got anyway to keep it continue? like an example ```wget -c ``` ?

**Comment by eivantsov** [comment]
@thyeun I cannot reproduce it

**Comment by thyeun** [comment]
ok, i will try using different internet provide see any different result on 6.1.0, if because too slow internet speed, than causing the issue, it should happen on 5.20.0 also

but for 5.20.0, it will continue download until it finish even i'm not on my desk

**Comment by thyeun** [comment]
using different internet provide with 6.1.0, having same message but with an extra message ```no images latest eclipse/ubuntu_python```

**Comment by eivantsov** [comment]
Can you run `docker pull eclipse/ubuntu_python:latest`? It must be some Docker glitch, since I am able to pull the image.

**Comment by thyeun** [comment]
i can pull it, but always everything download completed than this message appear ```[ERROR] read tcp 192.168.1.2:58748->13.33.194.178:443: read: connection reset by peer``` than i have to re-download everything again.

i'm not sure what happen, but i'm can confirm it is not related with my internet connection.

**Comment by thyeun** [comment]
Fresh installation for 6.1.0, i getting the below message...(using multi-user), i really dont know what happen now.

![screenshot from 2018-02-14 19-30-54](https://user-images.githubusercontent.com/1939446/36319133-f2ce731a-137c-11e8-9282-82b84fd58125.png)

**Comment by eivantsov** [comment]
Looks similar to https://github.com/moby/moby/issues/21524

**Comment by thyeun** [comment]
not exact, because it only happen on latest images (or latest version), old images or old version never getting that reset peer issue. i been trying version 5.20.0, 5.21.0, 6.0.0-M1 to M3 and 6.0.0 all ok

just happen on 6.1.0

**Comment by thyeun** [comment]
it is something that i really dont understand, it should be in the same machine, but why only happen on latest version?

**Comment by eivantsov** [comment]
@thyeun the screenshot you have shared shows that pull of keycloak image failed. Che hasn't come into play. It's CLI. And CLI just does pucker pull. In fact, it does docker compose up, and it's Docker that pull the image.

**Comment by thyeun** [comment]
@eivantsov, so which giving the faulty? come back to the version that i tested out, why only happen on 6.1.0? and others older version never give me that reset peer error? and even i have a super slow speed internet connection on older version, it still finish the download without and reset peer.

so my question is, if it is docker issue, than it will be affected older version too, but in this cases, it is not, so?????

**Comment by thyeun** [comment]
@eivantsov , i'm not only tested out the older version and newer version on linux system, i been tested it on windows system too, and for your info, windows for newer version having the same ```reset peer``` too.

i'm really given-up, every time a new version out, i will have to troubleshoot, and find out what the changing and what make it not working, i been wasted alot of time on che just to make it work after each newer version out. (i think you notice also, every time newer version out, you will see me posted an issue). 

Anyway thanks for helping, i think you can close this issue, i will stop wasted time on che, since i don't have the luck to make it work.

**Comment by eivantsov** [comment]
@thyeun what i am saying is that I cannot reproduce it on Mac, Windows and Linux myself.

**Comment by thyeun** [comment]
@eivantsov , it is ok, you can close this issue. thanks for helping!
