### ISSUE TITLE
Investigate the failing selenium tests on CI jobs with unexpected 'keycloak refused'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8788]
### Description
* Sometimes the selenium tests fail when run on the CI job with unexpected error 'keycloak refused connect'
* Need to find the reason of  it and fix

**_Screenshot:_**
![keyclock-refused](https://user-images.githubusercontent.com/5408906/36247298-290989de-123c-11e8-8d34-a80d780bbf04.png)

**_Report:_**
![connection-error](https://user-images.githubusercontent.com/5408906/36248260-886fb81e-123f-11e8-81d9-af7967555ba7.png)

**Comment by vkuznyetsov** [comment]
not actual issue
