### ISSUE TITLE
Autosave of open texteditor triggered after external file change

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#8789]
### Description

If a file, that is currently open in a text editor, is modified externally, the editor is updated with the new file content and in addition the autosave will send back the file to the workspace agent to save it again.

This causes unnecessary traffic (file sent back to the agent) and the timestamp of the file gets updated although there is no change of content.

This is my use case:
My problem currently is mainly the timestamp:  The use case I'm implementing is an alternative form based editor for a certain filetype. This editor should also update if  the file is changed externally. So to know if a file was modified by the form  based editor or by the user externally or in a texteditor I store the last modified timestamp after writing the content. So when my editor receives a file change event, I check the timestamp assuming that it wasn't modified by somebody else if it is the same as before. 
This mechanism is breaking in the presence of an open text editor because the text editor will (unnecessarily) update the timestamp.

### Reproduction Steps

- in a Che 5.22.1 workspace (I used a simple java stack):
- create a project with a file (say: theproject/thefile)
- in the terminal of the workspace: echo newcontent > /projects/theproject/thefile
Observe the network traffic: first the file will be fetched and then 1 second later (AUTOSAVE period) a PUT will be issued for the same file.

**Diagnostics:** 
EditorGroupSyncronizationImpl calls replaceContent on the document to update and this will automatically set the dirty state of the document.
Therefore AUTOSAVE will save the file a second later.

**Comment by eivantsov** [comment]
@RomanNikitenko @dkuleshov @vparfonov can you comment? I think it's expected behavior for us now

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen if the issue persist in 6.10+ version.
