### ISSUE TITLE
The factory does not finish loading after a long time

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#8798]
### Description
This problem happens randomly on CI infrastructure with tests from the ```factory``` package. 
On screenshot this looks like:
![factory-fail](https://user-images.githubusercontent.com/1640058/36260015-bef98490-1268-11e8-983c-172491b38bd1.png)
**Report link:** https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/118/
**OS and version:**   CI-infrastructure CHE-6.1.0

**Comment by ashumilova** [comment]
@musienko-maxim are there any error logs, when this issues occurs?

**Comment by vkuznyetsov** [comment]
actual in Version: 6.10.0

**Comment by musienko-maxim** [comment]
I try to provide more info like logs and etc.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
