### ISSUE TITLE
Cancel button too similar to disabled button

### ISSUE THREAD

**Issue by SpicySpaceman** [eclipse-che/che#8811]
### Description

Maybe it's just me, but the cancel button and disabled "Ok" button are way too similar. Hard to tell if the cancle button is enabled at all.

![image](https://user-images.githubusercontent.com/10995998/36282511-ade3de56-12a1-11e8-9e16-835a154e88a1.png)

 

### Reproduction Steps

1. Go to "Stacks"
2. Click on "Build Stack From Recipe"
3. Compare the cancel and ok button

**OS and version:**    Windows 10 x64
Che 6.2.0-SNAPSHOT (be0d15d5222f00cf)

**Comment by eivantsov** [comment]
@slemeur @olexii4 ?

**Comment by slemeur** [comment]
The "Ok" button is in disable state. 

@olexii4 + @ashumilova : The "Ok" button is the primary action in the popup - but at first that primary action is disable. It seems that the "disable state" for a primary button should still be reflecting the "primary" color. 

Another UX points that I understand from this issue:

1. The user is not really understanding what he should be doing and why the "OK" button is disabled. We could let the user click on "OK" button and when the content of the textbox is empty display the following message "You can't create a new stack -- your recipe cannot be blank"
2. The label "OK" is unclear. In fact here, it will create a stack and the primary button should reflect that action. Would "Create Stack" be more efficient and meaningful?

**Comment by olexii4** [comment]
@slemeur 
Totally agree with you: add an error message, change "OK" button title and "Cancel" button style.
As for me, an error message "your recipe cannot be blank" is enough and change "OK" title to "Build" will be better because the form name is "Build stack ...".

WDYT?

**Comment by eivantsov** [comment]
@slemeur we should either convert this to a task and do or close. I'll close it. Feel free to reopen.
