### ISSUE TITLE
Outdated report on CI in selenium testing jobs after build fail

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8815]
### Description
We have selenium testing jobs on CI like https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/ which display test results from the previous test execution because of workspace directory **selenium/che-selenium-test/target** isn't removed.
For example here https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/34/ we see results from the last build on the **qa-slave-1**:

![screenshot-ci codenvycorp com-2018 02 16-14-50-47](https://user-images.githubusercontent.com/1197777/36308393-31f1c5a0-1329-11e8-86d1-af51ec32bd89.png)

**Comment by riuvshin** [comment]
fixed
