### ISSUE TITLE
Misleading error notification from pr-build CI job 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8816]
### Description
After [the build on CI job had been failed](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/34/), CI server sent notification with misleading information:
> che-pullrequests-test-ocp - Build # 34 - Still Failing:
> Please check console output at https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/34/ to view the results.
> PR: https://github.com/eclipse/che/pull/8803
> Failed tests: **All tests passed**

_Expected status:_
> Failed tests: **No tests ran.**

**Comment by riuvshin** [comment]
fixed.
