### ISSUE TITLE
Store pre-saved workspace logs after the selenium test execution finished at pr-build CI job

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8817]
### Description
Selenium tests are storing _failed test workspace logs_ in the directory **"selenium/che-selenium-test/target/workspace-logs"**. They should be stored in the http://tests.codenvycorp.com/selenium_test_report_data folder as well in case of executing selenium tests on [pr-build CI jobs](https://ci.codenvycorp.com/view/pr-builds/).

**Comment by riuvshin** [comment]
Done
