### ISSUE TITLE
Docker Multiuser 6.X version Stop with Snapshot?

### ISSUE THREAD

**Issue by kattunga** [eclipse-che/che#8824]
I installed Eclipse 6.0.0 and 6.1.0 on Docker Multiuser.
I don't find any option to stop workspace with snapshot.
Actually if I stop a workspace I lost any package installed.

In codenvy.io I see the option

![image](https://user-images.githubusercontent.com/2139720/36342612-a382d34c-13df-11e8-979b-33d54d9e59f9.png)

But in my installation I don't se the option:

![image](https://user-images.githubusercontent.com/2139720/36342622-b84acaa0-13df-11e8-8d79-755e1379ff09.png)

In documentation:

https://www.eclipse.org/che/docs/devops/runtime-machines/index.html#machine-snapshot

talks about this option:

```
# Enable/Disable auto snapshotting and auto restoring from a snapshot
CHE_WORKSPACE_AUTO__SNAPSHOT=true
CHE_WORKSPACE_AUTO__RESTORE=true
```

But I don't find this options in my che.env file, should I manually add it?

Are snapshots supported en version 6.x?

**Comment by eivantsov** [comment]
@kattunga snapshotting support has been discontinued. Che6 allows defining volumes per machine https://www.eclipse.org/che/docs/6/che/docs/volumes.html
