### ISSUE TITLE
Docker multiuser installation with https for Keycloak authorization

### ISSUE THREAD

**Issue by kattunga** [eclipse-che/che#8825]
I know that using OpenShift is posible, but using docker, Is there any way to configure HTTPS for the Dashboard and Keycloak authorization?

I'm using User Federation with LDAP, and making the authentication via HTTP expose user password to anybody in the LAN.

**Comment by eivantsov** [comment]
@kattunga https on Docker isn't officially supported. Someone from the community has asked the same question, but I don't think there's a working prototype of Che infra on Docker using https

**Comment by kattunga** [comment]
But i am not trying to setup https with docker, i want to setup the dashboard and keycloak behind nginx and setup https in nginx.
The problem is that i don't find how to configure the https entry for keycloak in che server to redirect to nginx instead of the 5050 port of keycloak and then from keycloak to dasboard after autentication.

**Comment by eivantsov** [comment]
@kattunga you will face cert issues since Keycloak and Che workspace agents are Java processes - self signed certs need to be added to Java trust store.

As to redirection to your nginx that acts as a proxy and redirects to Kayecloak, you may use env variable `CHE_KEYCLOAK_AUTH__SERVER__URL`. By default it's `CHE_HOST:5050/auth`.

You may pass this env in your docker run syntax `-e ENV=VALUE`

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen if you have further questions

**Comment by JuanVilla18** [comment]
HI,

Re open this becuase i have the same error but its not completlly explained.

at this moment my dashboard is accesing on domain, at the moment of install i has been used the option -e ENV=https://domain/auth.

Please guide me to the next steps.

**Comment by eivantsov** [comment]
@JuanVilla18 what exact problem do you have with Che? Not sure I have understood your comment

**Comment by JuanVilla18** [comment]
@eivantsov I need to access my eclipse che in https acctually work over http.

What do I need to access through https?

**Comment by mjb6z9** [comment]
There doesn't seem to be any documentation that shows how to use something like Nginx proxy for SSL when running a docker host. A guide for how to do this in the documentation would be ideal.

**Comment by Mbd06b** [comment]
I've been puzzling this problem for about three weeks now.
Has anyone found a working Apache or Nginx config with cleqn ssl termination at the proxy?  Or got a https working on a multi user install some other way?

Sidenote, I've git one public IP address to work with, so proxy is required.
