### ISSUE TITLE
[OCP-single] Investigate the failing selenium tests related to authorization on GitHub on CI job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8831]
### Description
* Sometimes the selenium tests fail related to authorization on GitHub, when they run on the **_OCP-single_** CI job
* We expect appearing the authorized form, but the form does not displayed
* We have the next: 
  * 15.02 - tests fail,  qa-slave2
  * 16/17.02 - OK, qa-slave4
  * 18.02 - tests fail, qa-slave3
  * 19.02 - tests fail, qa-slave2
 
* Need to find the reason of it and fix

* Related selenium tests: _AuthorizeOnGithubFromDashboardTest_, _AuthorizeOnGithubFromImportTest_, _AuthorizeOnGithubFromPreferencesTest_, _ImportProjectIntoSpecifiedBranchTest_, _ImportRecursiveSubmoduleTest_, _PullRequestPluginTest_, _PullRequestPluginWithForkTest_, _KeepDirectoryGitImportTest_

**_screenshot:_**
![github-form](https://user-images.githubusercontent.com/5408906/36372595-2c19567e-156e-11e8-8f72-81d6bd778a0f.png)

**Comment by riuvshin** [comment]
issue was fixed by fixing `resolv.conf` on ci slave
