### ISSUE TITLE
Eclipse Che Websockets error.

### ISSUE THREAD

**Issue by Minvinn** [eclipse-che/che#8839]
Hi,

### Description

I'm trying to set up a che server and connect it to the internet behind an Apache reverse proxy.
This is what I'm trying to achieve (Apache and Che are on the same machine):
```
-----------------     ------------     -----------------     -------
|     Client    |_____| INTERNET |_____|     Apache    |_____| CHE |
| (web browser) |     |          |     | reverse proxy |     |     |
-----------------     ------------     -----------------     -------
```

I saw it's not possible to have Che in HTTPS (correct me if I'm wrong), due to the websockets using ws:// and not wss://.

Right now, with this is my Apache configuration
```bash
$ cat /etc/apache2/sites-enabled/che.conf 
<VirtualHost *:80>
	ServerName che.domain.xyz

	<Location />
		AuthType Basic
		AuthName "Che"
		AuthUserFile /etc/apache2/.htpasswd
		Require valid-user
	</Location>

	ProxyPass / http://127.0.0.1:8080/
	ProxyPassReverse / http://127.0.0.1:8080/
	ProxyRequests Off
</VirtualHost>
```

With this, I can access the dashboard, create workspaces, and modify their configuration.
Although I can access this, I can't access a workspace.
To be more precise, I can load a workspace, but when it's loaded, I can't do anything inside.
I've got this error int the JavaScript console
```
Firefox can't establish a connection to the server at ws://che.domain.xyz/api/websocket?token=null.
```

I've tried to use the `CHE_SINGLE_PORT` option by usig the command below to start Che
```bash
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/cheWorkspace:/data -e CHE_SINGLE_PORT=true eclipse/che start
```

As it wasn't working, I've found a StackOverflow thread (dont't remember which one) and I tried to add this in che.conf virtualhost:
```
RewriteEngine On
RewriteCond %{QUERY_STRING} transport=websocket    [NC]
RewriteRule /(.*)           ws://127.0.0.1:8080/$1 [P,L]
```
But that don't work too, I always have the same error.

**OS and version:**    Debian 9, last Apache version, last docker `eclipse/che` single-user version.

Do somebody have any idea or hint ?

**Comment by Minvinn** [comment]
Hmmm... it seems to work when I don't block some ports.

Which ports does Che needs ?

**Comment by eivantsov** [comment]
@Minvinn you need the ephemeral port range to be available if you don't use a single port.

What's the exact error with single port? And why do you need apache with single port anyway? It's Traefik container that will manage traffic routing.

And it is **not impossible** to provide https support for Che on Docker. It's just not supported out of the box. And for self signed certs you will have to somehow add them to Java trust store for workspace agent. But that's a different topic anyway.

What's your single port error? Give it a go without Apache.

**Comment by eivantsov** [comment]
@Minvinn with single port AND Apache?

As to password protected Che, there's a multi user flavor.

**Comment by Minvinn** [comment]
no single port only, without apahe, just the built-in traefic

**Comment by eivantsov** [comment]
Can you use IP address instead of hostname? What IP does CLI prints when you start Che?

**Comment by Minvinn** [comment]
@eivantsov Zhen I start Che, the displayed IP is the locat IP (192.168.1.2)
I tried to use the `CHE_HOST` option but I have this error when I try to start a workspace:
```Internal Server Error occurred, error time: 2018-02-20 13:39:45```

**Comment by eivantsov** [comment]
@Minvinn let's solve one problem at a time. Does single port work for you when using a local IP?

**Comment by Minvinn** [comment]
@eivantsov yes, all trafic are routed on the 8080 port.

**Comment by eivantsov** [comment]
@Minvinn che single port uses nip.io as wildcard dns, so when you provide CHE_HOST as a hostname, not IP, this is unlikely to work properly.

**Comment by Minvinn** [comment]
So how can I provide a hostname instead of a IP ?

**Comment by Minvinn** [comment]
Ok, I think I will not use the single port functionality to be able to not use an IP for the `CHE_HOST` option.

But now, how can I use Apache as a reverse proxy to reroute che.domain.xyz:80 to che.domain.xyz:8080 ?

Right now, with this config, even the dashboard don't work:
```
<VirtualHost *:80>
	ServerName che.domain.xyz

	ProxyRequests Off
	ProxyPass / http://127.0.0.1:8080/
	ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>
```

**Comment by eivantsov** [comment]
What does browser dev console have to say about it? I think you said dashboard worked for you on take one?

**Comment by Minvinn** [comment]
@eivantsov I have this error
```
Error: t.data is undefined
r</<.value/<@http://che.domain.xyz/dashboard/scripts/app-b77322866e.js:2753:743
l@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:75:30211
u/<@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:75:30383
yn/this.$get</h.prototype.$eval@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:76:5877
yn/this.$get</h.prototype.$digest@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:76:4389
yn/this.$get</h.prototype.$apply@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:76:6159
o@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:75:13555
g@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:75:15405
_t/</w.onload@http://che.domain.xyz/dashboard/scripts/vendor-73784b1bca.js:75:15948
```

**Comment by eivantsov** [comment]
@Minvinn works for me with your Apache config. Can you restart Che with :nightly tag?

**Comment by Minvinn** [comment]
@eivantsov Same with nightly, I will reinstall debian to check if it's me.

**Comment by Minvinn** [comment]
@eivantsov I think this strange error was my system. I have reinstalled debian, but when I launch Che on the port 8080 end use this Apache configuration, I get a HTTP 500 error code.
```
<VirtualHost *:80>
	ServerName che.domain.xyz

	ProxyRequests Off
	ProxyPass / http://127.0.0.1:8080/
	ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>
```

I tried to use the Che local IP
```
<VirtualHost *:80>
	ServerName che.domain.xyz

	ProxyRequests Off
	ProxyPass / http://192.168.1.2:8080/
	ProxyPassReverse / http://192.168.1.2:8080/
</VirtualHost>
```
But that don't work too.

**Comment by eivantsov** [comment]
@Minvinn let's take Che out of equation for a while. Can you stop Che and run nginx?

`docker run -d -p 8080:80 nginx`

Then go to `che.domain.xyz`. Can you see nginx welcome page?

Also, when you say it's 500 - are you talking about 500 returned by Che or Apache?

**Comment by Minvinn** [comment]
@eivantsov Yeah, I can see nginx welcome page.

The 500 was returned by Apache.

**Comment by Mbd06b** [comment]
@Minvinn  Did you ever figure out the Apache config?  I'm trying to use the built-in user management of the the multi user install, but can't seem to configure Che to use a FQDN instead of an unreliable External Dynamic IP address.  

I can access some resources externally, but there are resources my external client(browser) is trying to load private IP resources 172.17.0.1  (not found) <- I think this IP address is the eclipse che/docker applicaiton default

IMO,  CHE_HOST should accept a FQDN, instead of a raw External IP address and I think it would make this configuration a lot easier. 

Current state of my  Apache  sub.conf file...

`<VirtualHost *:80>
         ServerName sub.domain.xyz
        ServerAlias sub.domain.kyz

        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>
        <Location />
                ProxyPass  http://192.168.1.130:8080/
                ProxyPassReverse  http://192.168.1.130:8080/
        </Location>
               #Currently not loading /auth/ 
                ProxyPass /auth/ http://192.168.1.130:5050/
                ProxyPassReverse /auth/  http://192.168.1.130:5050/


`
