### ISSUE TITLE
Create method for refreshing browser by "JavaScript"

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8841]
### Description
For now, for refreshing browser we using SeleniumWebDriver#navigate()#refresh() method. But this is not the best way in our case. Because this method works by using HTTP requests:
```
HttpRequest httpRequest = commandCodec.encode(command);
```
And some events, which wait for click on the refresh button, maybe not activated.
In this case will be better to use "JavaScript" method:
```
SeleniumWebDriver#executeScript("location.reload()");
```
Which simulates the native click on the "refresh" button

**Comment by dmytro-ndp** [comment]
Both of commands: `SeleniumWebDriver.navigate().refresh()` and `SeleniumWebDriver.executeScript()` do the same thing: is sending commands to the web driver by using HTTP requests:
- `refresh()` sends command `DriverCommand.REFRESH`;
- `executeScript()` sends command `DriverCommand.EXECUTE_SCRIPT`.

**Comment by Ohrimenko1988** [comment]
I agree with you, but I think refresh by "JavaScript" has one useful function - refresh from server without using a cache. And on my opinion, this function has to realized in our framework.

**Comment by dmytro-ndp** [comment]
`SeleniumWebDriver.navigate().refresh()` should clean up cache as well, shouldn't it?

**Comment by Ohrimenko1988** [comment]
Yes, you are definitely right. But we need to keep in mind that `SeleniumWebDriver.navigate().refresh()` refreshes page without cache. `SeleniumWebDriver.getKeyboard().sendKeys("F5")` refreshes page, and can use cache.
  According to conversation's result, this issue does not make sense.
