### ISSUE TITLE
Openshift Origin 1.5 : Che 6.1.0 - MultiUser Deployment Workspace Start Failure

### ISSUE THREAD

**Issue by hbhargav** [eclipse-che/che#8847]
### Description

I've deployed Che 6.1.0 MultiUser on Openshift Origin 1.5. When I try to launch workspace, I get the following error 

"Message: Route in version "v1" cannot be handled as a Route: no kind "Route" is registered for version "route.openshift.io/v1". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=Route in version "v1" cannot be handled as a Route: no kind "Route" is registered for version "route.openshift.io/v1", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={})."

oc version 
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://ha-oso.xxxx.com:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4

 I've set value for CHE_INFRA_OPENSHIFT_PROJECT, inspite of which every workspace is launched in separate project/namespace.
I'm using dynamic provisioning for pvc & DEFAULT_CHE_INFRA_KUBERNETES_PVC_STRATEGY="unique", as a result of which every workspace will claim pv, dynamic provision isn't working & the claims are running forever

### Reproduction Steps
I've deployed che 6.1.0 using deploy-che.sh script from Che project repo

**OS and version:**    
Openshift 1.5.1
Kubernetes 1.5.2

Keycloak & Postgres have been setup manually outside openshift.

**Diagnostics:** 
 I suspect this is related to Kubernetes version, but thats a wild guess

**Comment by eivantsov** [comment]
@hbhargav a couple of comments:

1. Any chances you upgrade to Origin 1.6?\
2. Do you use a custom recipe to launch a workspace? If so, which one?
3. "CHE_INFRA_OPENSHIFT_PROJECT" should be set to `eclipse-che` or whatever namespace you used for Che server deployment

**Comment by hbhargav** [comment]
@eivantsov 
Please find my response inline

1. Any chances you upgrade to Origin 1.6?
We have been running che 5.20 on origin 1.5 for couple of months & upgrade to origin 1.6 would require considerable effort, I would consider upgrade if we manage to nail down the issue to origin 1.5 with kubernetes 1.5.

2. Do you use a custom recipe to launch a workspace? If so, which one?
I'm not using any custom recipe to launch a workspace, I'm using java-default stack & console-java-simple project.

3. "CHE_INFRA_OPENSHIFT_PROJECT" should be set to eclipse-che or whatever namespace you used for Che server deployment
I've set CHE_INFRA_OPENSHIFT_PROJECT to the same namespace that che-server is being launched.

The reason why workspaces were being launched in a new namespace boils down to the issue
https://github.com/eclipse/che/pull/8795

To overcome this I set CHE_INFRA_KUBERNETES_NAMESPACE, which matches the value of CHE_INFRA_OPENSHIFT_PROJECT.

Now, the workspace pod starts in the same namespace as che-server, however it throws the following error message
"Message: Route in version "v1" cannot be handled as a Route: no kind "Route" is registered for version "route.openshift.io/v1". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=Route in version "v1" cannot be handled as a Route: no kind "Route" is registered for version "route.openshift.io/v1", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={})."

I tried to diagnose the issue, the following are my findings.

## 1
I've set DEFAULT_CHE_INFRA_KUBERNETES_PVC_STRATEGY="unique" & dynamic provisioning is enabled using storage class as below

kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

$oc patch storageclass gp2 -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'

$oc get storageclass
NAME      TYPE
gp2           kubernetes.io/aws-ebs

$ oc describe storageclass
Name:		        gp2
IsDefaultClass:	No
Annotations:	        storageclass.kubernetes.io/is-default-class=true
Provisioner:	        kubernetes.io/aws-ebs
Parameters:	        type=gp2

The following happens when launching workspace, The workspace requests for 2 pvc's each of which are 10Gi size, I believe this is picked up from default che.env

I've not created any pv since dynamic provisioning needs to launch 2 aws-ebs volumes & made available for workspace pod.
I see that the dynamic provision isnt triggered & the claim requests are running forever. In the background che reports the above error on Dashboard & Che Server Logs.

I made the following changes to che-openshift.yaml for PVC

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: che
    name: che-data-volume
    annotations:
       volume.beta.kubernetes.io/storage-class: gp2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: che
    name: claim-che-workspace
    annotations:
       volume.beta.kubernetes.io/storage-class: gp2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

Che-server deployment goes through fine, dynamic provisioning gets triggered and things work as expected. Workspace starts fail with error message mentioned above
On debugging more into pvc claim request during workspace launch, I see an error stating no default storage class found, though storageclass default is set to true.

So I plan to create another storageclass which is cluster-wide default using the below script.

kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: generic
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

## 2
I tried the option of using common volume for all workspaces. 
I've set DEFAULT_CHE_INFRA_KUBERNETES_PVC_STRATEGY="common", so that workspace uses the claim-che-workspace pvc already provisioned as part of che-server deployment.

In this mode as well it throws
"Message: Route in version "v1" cannot be handled as a Route: no kind "Route" is registered for version "route.openshift.io/v1". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=Route in version "v1" cannot be handled as a Route: no kind "Route" is registered for version "route.openshift.io/v1", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={})."

**Comment by eivantsov** [comment]
@hbhargav I wonder why `route.openshift.io/v1` is the version.

**Comment by hbhargav** [comment]
@eivantsov I'm not sure as well

**Comment by eivantsov** [comment]
@hbhargav can you copy Che route yaml and share it here please?

**Comment by hbhargav** [comment]
@eivantsov 
Any Idea what is the kubernetes client version used in Che project, I tried to look but couldn't find the version.

May be issue lies in the version difference between client version used in che project & server version running on openshift for kubernetes

Router yaml from openshift 

apiVersion: v1
kind: Route
metadata:
  name: che
  namespace: kodepro
  selfLink: /oapi/v1/namespaces/kodepro/routes/che
  uid: 8860142c-16e6-11e8-b520-026ea6b0480a
  resourceVersion: '10561174'
  creationTimestamp: '2018-02-21T09:06:42Z'
  labels:
    app: che
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"kind":"Route","apiVersion":"v1","metadata":{"name":"che","namespace":"kodepro","creationTimestamp":null,"labels":{"app":"che"}},"spec":{"host":"","to":{"kind":"Service","name":"che-host","weight":100},"tls":{"termination":"edge","insecureEdgeTerminationPolicy":"Redirect"},"wildcardPolicy":"None"},"status":{"ingress":null}}
    openshift.io/host.generated: 'true'
spec:
  host: che.oso.xxxx.com
  to:
    kind: Service
    name: che-host
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: che.oso.xxxx.com
      routerName: router
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2018-02-21T09:06:42Z'
      wildcardPolicy: None

**Comment by eivantsov** [comment]
@sleshchenko can shed some light on fabric8 client version

And yes, it does look like there's some incompatibility here... I think I will install Origin 3.5 and check it myself. Not sure I will have the same environment as you though

**Comment by sleshchenko** [comment]
So, we don't specify API version obviously for workspace-related Kubernetes/OpenShift objects.
We use [fabric8io.kubernetes-client:3.1.0](https://github.com/fabric8io/kubernetes-client) for interacting with Kubernetes/OpenShift APIs. I guess fabric8 client may specify the wrong version. We need to check that and then decide how to solve this issue.

**Comment by eivantsov** [comment]
Cannot find Origin 3.5 tag :(

**Comment by hbhargav** [comment]
Openshift Origin 1.5 is equivalent v3.5

For your reference https://github.com/openshift/openshift-ansible

**Comment by eivantsov** [comment]
I have hard time installing 1.5 on my Fedora

**Comment by hbhargav** [comment]
@eivantsov 
route.openshift.io/v1 is set in io.fabric8.openshift.api.model.Route, which is used on org.eclipse.che.workspace.infrastructure.openshift.environment.OpenShiftEnvironment

public class Route implements HasMetadata {
  @NotNull
  @JsonProperty("apiVersion")
  private String apiVersion = "route.openshift.io/v1";

The above is coming from kubernetes-model:2.0.4

**Comment by hbhargav** [comment]
@eivantsov 
Would this be considered a bug ?

**Comment by eivantsov** [comment]
I would not say this is a bug as we rely on fabric8 client. By the way, Che 6 is certified to work on OpenShift 3.5 - in fact it was tested on 3.6+ versions. So, odds are that there might be other issues too.

I'll make sure docs clearly say which versions are officially supported.

You may issue a PR though to fix your particular issue.

**Comment by hbhargav** [comment]
@eivantsov 
That makes it clear.. Thanks. 
I will issue a PR soon.
