### ISSUE TITLE
Could not start workspace wksp-omcj. Reason: Installation 'org.eclipse.che.ws-agent' failed, script exit code is 127

### ISSUE THREAD

**Issue by ouladck** [eclipse-che/che#8848]
Hi I get a error when I started a new workspace with a custom docker image
this is the image of the bug:
![error](https://preview.ibb.co/gLK6hc/Screenshot_from_2018_02_20_17_55_54.png)
this is my configuration
```json
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "odoo": {
          "attributes": {
            "memoryLimitBytes": "2147483648"
          },
          "servers": {},
          "volumes": {},
          "installers": [
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent"
          ],
          "env": {}
        }
      },
      "recipe": {
        "type": "dockerimage",
        "content": "odoo"
      }
    }
  },
  "projects": [],
  "name": "wksp-omcj",
  "commands": [],
  "links": []
}
```

**Comment by eivantsov** [comment]
@karim88 sharing the Dockerfile you used to build this image will definitely help.

Also, if you click odoo tab in consoles panel, odds are that you see some logs.

I suspect that your image does not have Java which is a dependency for a  workspace agent, and ws agent installer failed to install Java (say, no sudo in the image etc)

**Comment by karim88** [comment]
@eivantsov Thank for your helpful answers, infact i used the offical odoo 11.0 Dockerfile https://github.com/odoo/docker/blob/b3d6d018f740ad2a816b5209300b875e2760085e/11.0/Dockerfile,
I will add jdk to the image then test it again.
