### ISSUE TITLE
Selenium tests doesn't work with Java 9

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8852]
### Description
The problem is listener **org.eclipse.che.selenium.core.CheSeleniumTestHandler** isn't run and as a result all tests fail with _NullPointerException_ because of injection of test page objects, workspaces, users... doesn't work.

[Tests log file.](https://github.com/eclipse/che/files/1744873/tests.log)

**OS and version:**    
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by vzhukovskii** [comment]
@dmytro-ndp does this issue still actual?

**Comment by rhopp** [comment]
At this point in time we will run tests still with java 8. If the need to run selenium tests with newer java arises, we can reopen this.
