### ISSUE TITLE
[OCP-platform] Unexpected failed start of workspace when tests run on CI job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8856]
### Description
* The selenium tests sometimes fail when run on CI on the ocp-platform
* The reason of it - the workspace does not start

**Che version:** 6.2.0
**OS and version:** Fedora 25
**Che install:** OCP (single/multi)

**Additional information:**
* Related selenium test: _it may be any test_
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* See the attachment:

## Folder ocp-logs/che-server-pod.log:
**_Che version: 6.2.0_ (_Installation 'org.eclipse.che.terminal' failed, script exit code is 127_):_**
![filed-start-ws](https://user-images.githubusercontent.com/5408906/36483644-643c86c2-171f-11e8-9414-8fa2d14fcf8e.png)

## Console output:
![filed-start-ws-3](https://user-images.githubusercontent.com/5408906/36483633-5b45e720-171f-11e8-87cd-075ec8bd9d7d.png)

## Test report:
![ws-failed-ocp](https://user-images.githubusercontent.com/5408906/39042405-60174342-4493-11e8-8383-60e42c72bc56.png)

## Screenshot:
![filed-start-ws-2](https://user-images.githubusercontent.com/5408906/36483649-6c2dad98-171f-11e8-8f5d-008aa96107d4.png)

**Comment by artaleks9** [comment]
The bug is still actual for Che version 6.5.0

**Comment by skabashnyuk** [comment]
@artaleks9 please rerun tests after merge of https://github.com/eclipse/che/pull/9619 and pay attention to KubernetesInternalRuntime errors on ws-master. Let us know if you saw something.

**Comment by skabashnyuk** [comment]
((

**Comment by eivantsov** [comment]
@sleshchenko there's another thing that I will ask for in case these logs may contain helpful info:

```
bootstrapper.log
$ cat bootstrapper.log
2018/05/07 13:56:44 Bootstrapper configuration
2018/05/07 13:56:44   Push endpoint: wss://che-eugene-che.6923.rh-us-east-1.openshiftapps.com/api/websocket
2018/05/07 13:56:44   Push logs endpoint: wss://che-eugene-che.6923.rh-us-east-1.openshiftapps.com/api/websocket
2018/05/07 13:56:44   Auth enabled: true
2018/05/07 13:56:44   Runtime ID:
2018/05/07 13:56:44     Workspace: workspaces0rvt8j295cd0b0m
2018/05/07 13:56:44     Environment: default
2018/05/07 13:56:44     OwnerId: b07e3a58-ed50-4a6e-be17-fcf49ff8b242
2018/05/07 13:56:44   Machine name: dev-machine
2018/05/07 13:56:44   Installer timeout: 180seconds
2018/05/07 13:56:44   Check servers period: 3seconds
2018/05/07 13:56:44   Push logs endpoint reconnect period: 10seconds
2018/05/07 13:56:44 Planning to install
2018/05/07 13:56:44 - org.eclipse.che.exec:1.0.1 - Agent for command execution
2018/05/07 13:56:44 - org.eclipse.che.terminal:1.0.1 - Embedded web terminal
2018/05/07 13:56:44 - org.eclipse.che.ws-agent:1.0.3 - Workspace API support
2018/05/07 13:56:44 Starting installations
2018/05/07 13:56:44 Installing 'org.eclipse.che.exec'
2018/05/07 13:56:47 Installation of 'org.eclipse.che.exec' successfully finished
2018/05/07 13:56:47 Installing 'org.eclipse.che.terminal'
2018/05/07 13:56:50 Installation of 'org.eclipse.che.terminal' successfully finished
2018/05/07 13:56:50 Installing 'org.eclipse.che.ws-agent'
2018/05/07 13:56:53 Installation of 'org.eclipse.che.ws-agent' successfull
```

Will there be any clues in bootstrapper.log in case a terminal installer fails? If so, can we somehow have it in master logs?

**Comment by sleshchenko** [comment]
@eivantsov I think we can log installer error output.

**Comment by eivantsov** [comment]
Registered an issue: https://github.com/eclipse/che/issues/9641

**Comment by artaleks9** [comment]
This bug is not reproduced for the last month.
At this moment we have fail run tests on CI only by reason #9556.
