### ISSUE TITLE
Create a list of stateful components of ws-master

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#8870]
### Description

The goal of this task is to create a list of components that are doing something at runtime without user interaction on ws-master or have some state inside. For instance, DockerAbandonedResourcesCleaner is making some periodical cleaning or MachineTokenRegistry. We need this list because in case if we will run several masters in parallel (https://github.com/eclipse/che/issues/8547) we need to make sure that they can work together and not brake anything.

**Comment by mshaposhnik** [comment]
So the brief overview of existing  self-executed components on the master side shows us a following:

## Without an state inside:
 1) `WsMasterAnalyticsAddresser` periodically sends activity ping to the usage(?) analytinc script;
 2) `LuceneSearcher` which is periodically commits lucene index;
 3) `DockerAbandonedResourcesCleaner` which is periodically cleans up abandoned docker containers and networks

## With state:
1) `WorkspaceActivityManager` holds the WS activity timestanps inside. Can potettially stops active workspaces when activity pings will go to another instance.

2) `MachineTokenRegistry` and related stuff - holds the machine tokens for every WS and can cause indefined states.

**Comment by garagatyi** [comment]
Isn't `LuceneSearcher` a `wsagent` component which runs inside of a workspace?

**Comment by mshaposhnik** [comment]
Oups, yes, it's project API :)
