### ISSUE TITLE
[OCP-platform] Failed start of workspace when tests run on CI job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8876]
### Description
* The selenium sometimes fail when run on CI on the ocp-platform
* The reason of it - the workspace does not start

**Che version:** 6.2.0
**OS and version:** Fedora 25
**Che install:** OCP (single/multi)

**Additional information:**
* it is very similar on the #8031
* Related selenium test: _it may be any test_
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* See the attachment:

## Folder ocp-logs/che-server-pod.log:
**_(che-version 6.2.0):_**
![failed-start-5](https://user-images.githubusercontent.com/5408906/36528193-f32f33be-17bc-11e8-939d-d5a472ff79c2.png)

## Console output:
![ws-not-starting-2](https://user-images.githubusercontent.com/5408906/36533480-58535ba8-17cc-11e8-89f5-5bec0ed5bf6f.png)

## Test report:
![ws-stopped-1](https://user-images.githubusercontent.com/5408906/36532932-bb18a7cc-17ca-11e8-8169-fe50a1fb3c1d.png)

## Screenshot:
![ws-not-starting](https://user-images.githubusercontent.com/5408906/36533290-c2b100f0-17cb-11e8-9c43-111e1c5edd6c.png)

**Comment by sleshchenko** [comment]
@artaleks9 Server logs file contains info that workspace start failed. I think that UD or IDE should show the corresponding error message. But the attached screenshot is empty. For me, it looks like an issue in QA tests. Do you know why does it appear?

**Comment by artaleks9** [comment]
This bug is not reproduced for the last month.
At this moment we have fail run tests on CI only by reason #9556.
