### ISSUE TITLE
Can not type  {,[,| (Alt Gr + key) in editor (windows 10 with french keyboard)

### ISSUE THREAD

**Issue by STRULLU** [eclipse-che/che#8877]
Hello,
I can not type {,[,|   (alt Gr + character) in eclipse che editor on windows 10. These keys trigger windows layout adaptation in the workspace. Is It possible to configure or remove these key bindings.
Thanks 
Laurent

**Comment by eivantsov** [comment]
@STRULLU currently keybindings aren't configurable. Che does have issues with non English keyboard layouts on Windows.

**Comment by STRULLU** [comment]
Ok thanks for your feedback, good work work anyway!
