### ISSUE TITLE
Update lsp4j Version to Latest

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8881]
We'll need to update lsp4j to latest once @gorkem has been able to get his changes for WorkspaceEdit with file operations.

**Comment by tsmaeder** [comment]
Need to make sure the dto generator works correctly.

**Comment by tsmaeder** [comment]
https://github.com/eclipse/lsp4j/pull/163 has been merged, so we can start on this one.

**Comment by svor** [comment]
@tsmaeder to which version should we update? To  `0.4.0.M6` ?
