### ISSUE TITLE
Stack-Base Image Build Fail

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#8884]
### Description
Stack-Base che image fails to build due to version of jdk not being found https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/Dockerfile#L39 . Changed it to https://github.com/eclipse/che-dockerfiles/commit/7f1650812e6ffd8fe4c051ee988a98421ee0e1e3#diff-0a7d86eee77dd50d7da72764dd0471b9R39 .

**Comment by eivantsov** [comment]
This file needs to be changed too https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/open-jdk-source-file-location

**Comment by eivantsov** [comment]
@JamesDrummond will you issue a PR?

**Comment by eivantsov** [comment]
Fixed by https://github.com/eclipse/che-dockerfiles/pull/176
