### ISSUE TITLE
EditFilesWithTabsTest opens redundant chromium window which doesn't close

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8902]
### Description
Selenium test **EditFilesWithTabsTest** opens **three** chromium windows instead of **two**, that means it creates **three** _SeleniumWebDriver_ instances instead of **two**, and one of them remains empty and open after the test execution.

### Reproduction Steps
Run test with _-Mlocal_ parameter to see redundant chromium window: `che-selenium-test/selenium-tests.sh --multiuser -Mlocal --test=EditFilesWithTabsTest`

### Solution
The problem has been appeared since we started usage of **SeleniumWebDriverHelper** class (commit fefef18dcc0db665055a80c935b8efe32d9734e8) which injects _SeleniumWebDriver_ instance. 
To fix the problem we can get rid of additional injection of **SeleniumWebDriver** instance into **SeleniumWebDriverHelper** class by merging it into the _SeleniumWebDriver_ class.

**OS and version:**    
Eclipse Che 6.2.0-SNAPSHOT

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/8865
