### ISSUE TITLE
 Regarding mouse hover event on main menu   

### ISSUE THREAD

**Issue by Mohdzaved2434** [eclipse-che/che#8907]
### Hi All,
When we right click on project then main menu is opened if we mouse hover on it then its sub menu are displayed which are added by us but its behaviour is not working as expected when we mouse hover first time. If we mouse hover secound time then it is working as expected.

**We have overridden apply() method for achiveing this functionality.
So can you please let me know there is any other method for resolving this issue?**    

**Thanks,
Zaved**

**Comment by eivantsov** [comment]
@vzhukovskii @vparfonov do you have some pointers here?

**Comment by Mohdzaved2434** [comment]
@eivantsov  I am using following code 
 @Override
    public void update(ActionEvent e) {
	Resource resource = appContext.getResource();
	Project project = resource.getProject();
	// Optional
	project.getContainer("path").then(new Operation<Optional<Container>>() {
	    @Override
	    public void apply(Optional<Container> container) throws OperationException {
		if (!container.isPresent()) {
		    return;
		}
		Container ram = container.get();
		ram.getFile("fileName").then(new Operation<Optional<File>>() {

		    @Override
		    public void apply(Optional<File> fileOptional) throws OperationException {
			if (fileOptional.isPresent()) {
			    e.getPresentation().setEnabled(false);
			}else{
				e.getPresentation().setEnabled(true);
				}
		    }

		});
	    }
	});
	


}
