### ISSUE TITLE
How to add FileWatcher to /projects directory in Eclipse Che

### ISSUE THREAD

**Issue by usersk12** [eclipse-che/che#8914]
I'm trying to create a new project directory in /projects directory in Eclipse Che in Terminal using following command:

`user@12345:/projects$ sudo mkdir ABC`

The folder is created in workspaces in che-data but it is not displayed in the Package Explorer in Eclipse Che.

However, the directories created using mkdir in Terminal inside already imported projects are reflected without 'Refresh'.
It is because FileWatchers are not enabled on /projects directory in Eclipse Che.

Kindly provide necessary help on how to enable FileWatcher on import Projects in Eclipse Che as File watchers are disabled in certain situations, like project import, to avoid flooding events.

I've referred following links:

https://www.eclipse.org/che/docs/6/che/docs/ide-projects.html#file-watchers

**Comment by eivantsov** [comment]
@dkuleshov @vzhukovskii should mkdir in the terminal force project explorer to refresh itself?

**Comment by skyskip** [comment]
I have same problem.
I'd like to make reflected by copying a project folder to /projects.
That seems reflected in codenvy. But, on 6.0.0 M3,  that doesn't work.

**Comment by dkuleshov** [comment]
Hi,

Could you please check if that is happening on the freshest Che tag (which is 6.1.0 if I remember correct)?

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen.
