### ISSUE TITLE
Reading Excel sheet in Eclipse Che ide plugins.

### ISSUE THREAD

**Issue by Mohdzaved2434** [eclipse-che/che#8915]
### Reading Excel sheet in Eclipse Che ide plugins.

Hi All,

Could you please let me know How I can read an Excel sheet inside the eclipse Che ide plugins.
I am able to read xml using following code in plugins

asyncRequestFactory.createGetRequest(url, false).send(new AsyncRequestCallback<String>(unmarshaller) {
@Override
protected void onFailure(Throwable exception) {
fileNotAvailable();
}
@Override
protected void onSuccess(String result) {
xmlData.setData(result);
 }
 
But not able to read excel sheet.

Thanks,
Zaved.

**Comment by eivantsov** [comment]
@Mohdzaved2434 what exactly do you mean by readying Excel sheets?

**Comment by Mohdzaved2434** [comment]
@eivantsov I am trying to retrieve data from Excel sheet
