### ISSUE TITLE
Feature request: Edit keybindings

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#8920]
Currently there is no way to remap existing keybindings. I use Vi in Eclipse Che, and Vi commands such as `Ctrl-B` are taken up by the default Eclipse Che keybindings.

**Comment by bdube** [comment]
I also use the vi keybindings and find that some of my frequently used bindings are not implemented (or maybe can't be implemented for other reasons). Where are the keybindings implemented?

**Comment by RomanNikitenko** [comment]
@bdube 
We use Orion editor with built-in vi keybindings support, you can try it here https://orionhub.org

**Comment by bdube** [comment]
I found this [vi.js](https://github.com/eclipse/orion.client/blob/master/bundles/org.eclipse.orion.client.editor/web/orion/editor/vi.js) for Orion. Is that also the keybinding implementation used in Che?
