### ISSUE TITLE
Not possible to add new file extension to make it work with LS. "documentFilters" does not work. 

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#8925]
### Description

Document Filters, declarative LS configuration ( #7554  ) does not work.

### Reproduction Steps
Configure Clang LS as server and add "h" to documentFilters->pathRegexp, like:
```
 "clangd": {
              "attributes":{
                "internal":"true",
                "type":"ls",
                "config":"{\"id\":\"org.eclipse.che.plugin.cpp\", \"languageIds\":[\"c\", \"cpp\"], \"documentFilters\":[  {  \"languageId\":\"cpp\",  \"pathRegex\":\".*\\\\.(c|cpp|h)\"} ]}"
              },
              "port": "4417",
              "protocol": "tcp"
            } 
```

It is expected that LS work for h files but it does not.
In fact "documentFilters" does not work at all (adding or removing it changes nothing).
The only way I could make it work is adding fake "h" language to Default Languages.

**Comment by artaleks9** [comment]
Still actual for ver.6.5.0

**Comment by tsmaeder** [comment]
@artaleks9 is it fixed by the PR that was merged?
