### ISSUE TITLE
Unable to install Che on OpenShift 3.7 with script

### ISSUE THREAD

**Issue by ctron** [eclipse-che/che#8933]
### Description

Following the "Script-based method" in the setup instructions for Minishift [1] results in the following error:

~~~
[CHE] Checking if minishift is running...done!
[CHE] Logging on using OpenShift endpoint "https://192.168.42.112:8443/"...done!
[CHE] Checking if project "eclipse-che" exists...Project "eclipse-che" does not exist...trying to creating it.
Project "eclipse-che" creation done!
[CHE] Creating serviceaccount, service and route for CHE pod
serviceaccount "che" created
service "che-host" created
route "che" created
[CHE] Setting admin role to "che" service account...rolebinding "che" created
[CHE] Retrieving latest version of fabric8 tenant Che template...done! (v.2.0.81)

[CHE] Deploying Che on minishift (image docker.io/eclipse/che-server:6.1.1)
cat: ./che-openshift.yml: No such file or directory
error: no objects passed to apply

~~~

[1] https://www.eclipse.org/che/docs/6/che/docs/openshift-single-user.html

### Reproduction Steps

~~~sh
DEPLOY_SCRIPT_URL=https://raw.githubusercontent.com/eclipse/che/6.1.x/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh
curl -fL "$DEPLOY_SCRIPT_URL" -o get-che.sh
export CHE_IMAGE_TAG=6.1.1
bash ./get-che.sh
~~~

**OS and version:**    

Linux xxx.xxx.csb 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
minishift v1.13.1+75352e5
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.112:8443
openshift v3.7.1+a8deba5-34
kubernetes v1.7.6+a08f5eeb62

**Diagnostics:** 
See above

**Comment by eivantsov** [comment]
@ctron can you follow instruction in this page please? https://github.com/eclipse/che-docs/blob/master/src/main/pages/setup-openshift/openshift-single-user.md?

Looks like docs weren't updated

**Comment by ctron** [comment]
For me this issue is fixed, as I did the PR 😁

But the docs looked fine.

**Comment by eivantsov** [comment]
Oops :) I have updated docs anyway. Thanks
