### ISSUE TITLE
Investigate Way to Address jdt.ls

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8941]
A lot of the extended Che functionality is implemented as custom commands in jdt.ls. In order to call those commands, we need to address jdt.ls specifically. 
We need to find out how to send commands to jdt.ls in Theia. If not possible, we need to open an issue for implementing this functionality.

**Comment by JPinkney** [comment]
I believe we can use https://github.com/theia-ide/theia/blob/master/packages/java/src/browser/java-commands.ts#L68 to address the jdt.ls specifically

**Comment by tsmaeder** [comment]
Marking as fixed, as per @JPinkney's comment.
