### ISSUE TITLE
Transfer object from tree via drag and set transferred object to other model using drop in GWT.

### ISSUE THREAD

**Issue by AbhiGit89** [eclipse-che/che#8944]
is there any implementation available in GWT to transfer object from tree via drag and set transferred object to other model with same type of instance using drop?
As with SWT there we can use DragSource ,Transfer and DragSourceEvent. 
is there any alternative available for GWT of package  org.eclipse.swt.dnd ?

**Comment by skabashnyuk** [comment]
@vparfonov can you answer?

**Comment by vparfonov** [comment]
@AbhiGit89 Hi, we never implemented d'n'd in Che IDE, but for GWT itself you can look at https://gwt-dnd.appspot.com/#InsertPanelExample, (but looks like project not updated from 2015)
