### ISSUE TITLE
How do I persist data when my Codenvy workspace resumes - eclipse/ubuntu_jdk8

### ISSUE THREAD

**Issue by terrywbradyC9** [eclipse-che/che#8946]
### Description
I have a project that needs to perform the following steps
- maven build
- ant installation
- database setup

The built system is then run by tomcat.

Every time that I stop my workspace, all of the built artifacts are deleted.  

As I attempt to build Dockerfiles based on eclipse/ubuntu_jdk8, I seem to only be able to write content to /home/user/...  This content is not persisted when I restart my workspace.

Where should I be writing this data so that it will be present when I restart the workspace?  What is the proper way to build a directory that will persist?

### Reproduction Steps

**OS and version:**    
eclipse/ubuntu_jdk8

**Diagnostics:**

**Comment by JamesDrummond** [comment]
How are you starting up che? If you are using docker then you can set `-e CHE_WORKSPACE_VOLUME=/example/local/host/path:/home/user` using the cli.

**Comment by terrywbradyC9** [comment]
@JamesDrummond, thanks for the response.  I am running on Codenvy.io so the docker image is created in their cloud.  I have updated the issue title to reflect that environment.

**Comment by skabashnyuk** [comment]
Just checked. Snapshot functionality work as expected.
Do you see this output on workspace stop
<img width="787" alt="2018-03-05 09 25 34" src="https://user-images.githubusercontent.com/1614429/36962289-954be7da-2057-11e8-9c47-567dc1315403.png">
or this output on workspace start
<img width="821" alt="2018-03-05 09 25 50" src="https://user-images.githubusercontent.com/1614429/36962294-9715fc7c-2057-11e8-8f72-a4ee6bcc8089.png">
or this checkbox on workspace stop 
<img width="615" alt="2018-03-05 09 27 45" src="https://user-images.githubusercontent.com/1614429/36962303-a13de4e4-2057-11e8-82a7-a83b3002b686.png">

**Comment by terrywbrady** [comment]
@skabashnyuk , I am sorry that I missed your reply.  I do see that the snapshot is saved.

![image](https://user-images.githubusercontent.com/1111057/37295617-ddeccc4c-25d5-11e8-9e04-f8aa293cd3d9.png)

![image](https://user-images.githubusercontent.com/1111057/37295631-e58f61d0-25d5-11e8-815c-9c48d82cd800.png)

When I restart the workspace, I see that the image is loaded

![image](https://user-images.githubusercontent.com/1111057/37295661-f52b92c6-25d5-11e8-9878-9e648212170d.png)

I took a closer look at the workspace after it restarted.  I see that my installed webapps have persisted.  Unfortunately, the database data has not persisted.

I suspect that there is an issue with the way I have configured the database machine.  When I attempt to add a "volumes" declaration, I see error messages.

        "recipe": {
          "type": "compose",
          "content": "services:\n db:\n  image: 'terrywbrady/dspacedb:latest'\n  mem_limit: 1073741824\n dev-machine:\n  image: 'terrywbrady/dspace:latest'\n  mem_limit: 2147483648\n  depends_on:\n   - db\n",
          "contentType": "application/x-yaml"
        }
  
Here is my dspacedb Dockerfile.  Is there some way that I can declare PGDATA to get things to persist?

https://github.com/DSpace-Labs/DSpace-codenvy/blob/master/CodenvyConfig/db/Dockerfile

**Comment by terrywbrady** [comment]
@skabashnyuk , I believe that I have resolved this issue by adding a PGDATA declaration on my "db" machine.

      "recipe": {
        "type": "compose",
        "content": "services:\n db:\n  image: 'terrywbrady/dspacedb:latest'\n  mem_limit: 1073741824\n  environment:\n   PGDATA: /home/user/pgdata\n dev-machine:\n  image: 'terrywbrady/dspace:latest'\n  mem_limit: 2147483648\n  depends_on:\n   - db\n",
        "contentType": "application/x-yaml"
      }

If I understand Che/Codenvy correctly, a "workspace" is a VM that runs docker containers.

Does Che run on the workspace, or does Che run in a container?  Is it essential to derive a dev-machine container from an image published under eclipse/*?

**Comment by eivantsov** [comment]
Che workspaces run in docker containers.

**Comment by eivantsov** [comment]
https://www.eclipse.org/che/docs/6/che/docs/volumes.html

**Comment by terrywbrady** [comment]
@eivantsov , I checked out the link you provided, but I am unable to figure out how to add a volume into my machine config in Codenvy.

      "machines": {
        "db": {
          "attributes": {
            "memoryLimitBytes": "536870912"
          },
          "servers": {},
          "agents": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal"
          ]
        },
        "dev-machine": {
          "attributes": {
            "memoryLimitBytes": "2684354560"
          },
          "servers": {},
          "agents": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh"
          ]
        }
      },

Here is what I have tried

      "machines": {
        "db": {
          "attributes": {
            "memoryLimitBytes": "536870912"
          },
          "servers": {},
          "agents": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal"
          ]
        },
        "dev-machine": {
          "attributes": {
            "memoryLimitBytes": "2684354560"
          },
          "servers": {},
          "agents": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh"
          ],
          "volumes": {
            "dspace": {
              "path": "/dspace"
            }
          }
        }

When I add the "volumes" block, I get the following error

> **The key 'volumes' is redundant in machine.**

**Comment by eivantsov** [comment]
@terrywbradyC9 this is a Che repo. Codenvy is 5.x version. Che is 6.x

**Comment by terrywbrady** [comment]
Thanks @eivantsov .
