### ISSUE TITLE
Issue in building language server pom.xml

### ISSUE THREAD

**Issue by ShivaniBali** [eclipse-che/che#8947]
Facing build issue, while trying to build plugins (trying Che integration with Xtext).
It fails for extension server 

FO] Che Plugin :: MyDsl (Xtext) :: Parent .............. SUCCESS [  2.703 s]
[INFO] Che Plugin :: MyDsl (Xtext) :: Extension Server .... FAILURE [  3.283 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.646 s
[INFO] Finished at: 2018-02-27T23:52:41-05:00
[INFO] Final Memory: 47M/1323M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.coveo:fmt-maven-plugin:2.0.0:check (default) on project che-plugin-mydsl-lang-server: Found 2 non-complying files, failing build -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :che-plugin-mydsl-lang-server

Complete terminal logs attached for reference!

Kindly have a look.
Thanks!
[Extension-Server-POM.docx](https://github.com/eclipse/che/files/1765647/Extension-Server-POM.docx)

**Comment by skabashnyuk** [comment]
This error is mean that your code is not compatible with Eclipse Che coding standards. See https://github.com/eclipse/che/wiki/Coding-Guidelines. To fix it just run ```mvn fmt:format```

**Comment by ShivaniBali** [comment]
Hello @skabashnyuk  thank you it fixed my issue 👍
