### ISSUE TITLE
Connect Debugger to NodeJS

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8955]
Implement an action to connect to a nodejs instance with a given port
  * detect that "nodejs" adapter contribution is present
  * create UI to populate "connect" parameters
  * send "connect" request to adapter

**Comment by tolusha** [comment]
![screenshot from 2018-04-18 09-56-18](https://user-images.githubusercontent.com/1640675/38916117-cd211108-42ee-11e8-8112-bf2ae7efe529.png)
