### ISSUE TITLE
Show Debug Sessions

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8956]
Create a UI to show active debug sessions. Behind the UI, we need a component that manages the active debug sessions.
An important constraint on this UI is that we need to be able multiple debug sessions being active at the same time. For self-hosting, we will want to debug Theia and jdt.ls at the same time, for example.

**Comment by tolusha** [comment]
![screenshot from 2018-04-23 12-26-48](https://user-images.githubusercontent.com/1640675/39118255-a7779bd2-46f1-11e8-814b-ac97edeeb313.png)
