### ISSUE TITLE
Theia: Implement jdt.ls "libraries" feature

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8965]
Jdt LS shows the libraries of a project in the project navigator. We need to investigate a way to add this feature to Theia. I would expect that Theia has a way to show artificial nodes in the project structure.

**Comment by tsmaeder** [comment]
Depends on https://github.com/eclipse/che/issues/8941

**Comment by JPinkney** [comment]
Ack, forgot to post the PR here for external libraries here https://github.com/eclipse/che-theia-java-plugin/pull/2
