### ISSUE TITLE
With Eclipse Che v6.0.0 + OCP v3.6, bootstrapper is corrupted when creating workspace

### ISSUE THREAD

**Issue by ktdjun** [eclipse-che/che#8968]
### Description
I constructed the environment of Eclipse Che v6.0.0 + OCP v3.6(v3.6.173.0.96) by the same procedure as the following Reproduction Steps.<br/>

I confirmed that Workspace pod can be started with OCP 3.6.
However, the Workspace screen can not be displayed in the browser.
The following message is displayed in the browser.

    Could not start workspace wksp-vryu. Reason: Bootstrapping of machine dev-machine reached timeout

From the browser console of OpenShift, when I executed the following command with Workspace pod, I noticed that bootstrapper size was wrong.<br/>
The result of executing the command is as follows.

    $ cd /tmp/bootstrapper
    $ ls -al
    total 32
    drwxr-xr-x. 2 user root    69 Feb 26 05:32 .
    drwxrwxrwt. 4 root root    49 Feb 26 05:32 ..
    -rwxr-xr-x. 1 user root   250 Feb 26 05:32 bootstrapper
    -rw-r--r--. 1 user root   100 Feb 26 05:32 bootstrapper.log
    -rw-r--r--. 1 user root 23906 Feb 26 05:32 config.json

The content of the bootstrapper was as follows.

    $ cat bootstrapper                                                                                                                                                     
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">                                                                                                                     
    <html><head>                                                                                                                                                           
    <title>404 Not Found</title>                                                                                                                                           
    </head><body>                                                                                                                                                          
    <h1>Not Found</h1>                                                                                                                                                     
    <p>The requested URL /agent-binaries/linux_amd64/bootstrapper/bootstrapper was not found on this server.</p>                                                           
    </body></html>                                                                                                                                                         

In the workspace pod, we manually executed the wget command using CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL in environment variable of Che Server's pod. I can successfully download boostrapper.
However, Workspace will not start.

    $ wget http://<My Route name>-<My Project Name>.<My Prefix>/agent-binaries/linux_amd64/bootstrapper/bootstrapper
    --2018-02-26 06:19:25--  http://<My Route name>-<My Project Name>.<My Prefix>/agent-binaries/linux_amd64/bootstrapper/bootstrapper
    Resolving <My Route name>-<My Project Name>.<My Prefix> (<My Route name>-<My Project Name>.<My Prefix>)... <Che Server's Node IP>
    Connecting to <My Route name>-<My Project Name>.<My Prefix> (<My Route name>-<My Project Name>.<My Prefix>)|<Che Server's Node IP>|:80... connected.
    HTTP request sent, awaiting response... 200
    Length: 6146825 (5.9M)
    Saving to: ‘bootstrapper’

    bootstrapper        100%[===================>]   5.86M  --.-KB/s    in 0.08s

    2018-02-26 06:19:26 (73.1 MB/s) - ‘bootstrapper’ saved [6146825/6146825]

    $ ls -l
    total 6032
    -rw-r--r--. 1 user root 6146825 Jan 31 15:07 bootstrapper
    -rw-r--r--. 1 user root      49 Feb 26 06:15 bootstrapper.log
    -rw-r--r--. 1 user root   23906 Feb 26 06:15 config.json

How can I solve this problem?<br/>
Please let me know if there is information to help.

### Reproduction Steps
1.Get Scripts

    git clone https://github.com/eclipse/che
    cd che/dockerfiles/init/modules/openshift/files/scripts

2.Set environment

    export CHE_MULTIUSER=true
    export OPENSHIFT_ENDPOINT=https://<My URL>:8443
    export OPENSHIFT_TOKEN=<My Token>
    export OPENSHIFT_ROUTING_SUFFIX=<My Suffix>
    export ENABLE_SSL=false
    export OPENSHIFT_FLAVOR=ocp
    export CHE_INFRA_OPENSHIFT_PROJECT=eclipse-che6
    export CHE_OPENSHIFT_PROJECT=eclipse-che6
    export CHE_IMAGE_TAG=6.0.0

3.Execute Script

    ./deploy_che.sh

**OS and version:**    

- Eclipse Che : v6.0.0
- OCP : v3.6(v3.6.173.0.96)

**Diagnostics:** 
- The value of Che_HOST is "che-<CHE_OPENSHIFT_PROJECT>.<OPENSHIFT_ROUTING_SUFFIX>".
- The URLs of KeyCloak and Che are as follows.
http://che-<CHE_OPENSHIFT_PROJECT>.<OPENSHIFT_ROUTING_SUFFIX>
http://keycloak-<CHE_OPENSHIFT_PROJECT>.<OPENSHIFT_ROUTING_SUFFIX>

**Comment by skabashnyuk** [comment]
Can you share workspace config?

**Comment by ktdjun** [comment]
Share my workspace config.
In order to minimize the configuration, I selected Blank Stack and removed codeserver, tomcat 8, tomcat 8-debug from Servers.
The same problem occurs even if I do not delete the definition of Servers.

    {
      "environments": {
        "default": {
          "machines": {
            "dev-machine": {
              "attributes": {
                "memoryLimitBytes": "2147483648"
              },
              "servers": {},
              "volumes": {},
              "installers": [
                "org.eclipse.che.exec",
                "org.eclipse.che.terminal",
                "org.eclipse.che.ws-agent"
              ],
              "env": {}
            }
          },
          "recipe": {
            "type": "dockerimage",
            "content": "eclipse/ubuntu_jdk8"
          }
        }
      },
      "defaultEnv": "default",
      "projects": [],
      "name": "wksp-test-blank",
      "commands": [],
      "links": []
    }

I have noticed one thing in Che's source code.
"che.infra.openshift.bootstrapper.binary_url" in che.properties is set in org.eclipse.che.workspace.infrastructure.openshift.bootstrapper.OpenShiftBootstrapper.

    che.infra.openshift.bootstrapper.binary_url=http://${CHE_HOST}:${CHE_PORT}/agent-binaries/linux_amd64/bootstrapper/bootstrapper

"CHE_PORT = 8080" is set in the environment set to pod of OpenShift, but CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL has no port specification.
Try to access "http://che-<CHE_OPENSHIFT_PROJECT>.<OPENSHIFT_ROUTING_SUFFIX>:8080/agent-binaries/linux_amd64/bootstrapper/bootstrapper", "404 Not Found" was returned.

Is there a shortage in the setting?

**Comment by skabashnyuk** [comment]
You are using Eclipse Che : v6.0.0
can you use latest che after this pr https://github.com/eclipse/che/pull/8805?

**Comment by ktdjun** [comment]
@skabashnyuk 
Thank you for your answer.
I will try it with the v6.2.0.

**Comment by eivantsov** [comment]
@ktdjun any update on this? What's the bootstrapper binary url in Che deployment?
