### ISSUE TITLE
Items from "Proposal Autocomplete" form are not selected by mouse single click

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#8972]
### Reproduction Steps
 - Run default java stack with default "web-java-spring" project
 - Expand project tree and open "GreetingController.java" file
 - In the opened editor put cursor to the 21-th row and type "String s;"
 - Press "Alt" + "Enter";
 - In the opened form click once on "Rename in file item"
 - Pay attention that item is not selected; 

**OS and version:**    
Che 6.2.0 ; Chrome 63.0 ; Fedora 25;

**Attachment:**

![jhjhjhfj](https://user-images.githubusercontent.com/22724619/36844615-1f29057c-1d5c-11e8-9f4f-bdf3a79ed939.png)

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/18)
