### ISSUE TITLE
Ability to quickly find the preferences (from menu or command palette) in Theia

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8981]
### Description
Ability to quickly find the preferences (from menu or command palette).

Inside of Theia, user has the ability to change few of the IDE preferences. The preferences are stored in an hidden file - and there is no easy way to open it. 

The goal of this task, is to add the ability to open the preference file from the command palette in Theia.

**Comment by gorkem** [comment]
@vparfonov Is this somehow related with https://github.com/theia-ide/theia/issues/1106 ? 

I think for Che we need to somehow centralize the user settings. Also there is a plan to implement language level settings https://github.com/theia-ide/theia/issues/1106 which is also a candidate for centralizing. Are you covering this sort of Che-Theia mapping with this one?

**Comment by vinokurig** [comment]
Theia team proposed next approach: (https://github.com/theia-ide/theia/issues/1433#issuecomment-370135224)
- Command to open the settings file (create one if it doesn't exist)
- JSON schema support

JSON schema support should give an ability to see all possible preferences.
There is an issue for that: https://github.com/theia-ide/theia/issues/1434 but I am not sure about it's state.
