### ISSUE TITLE
how to get wrokspace key

### ISSUE THREAD

**Issue by sunnoy** [eclipse-che/che#8985]
when i want use api
the doc has mention it ”get workspace object with runtimes fetched (using /api/workspace/<workspace_key> service)“

how get wrokspace_key ?

**Comment by skabashnyuk** [comment]
key can be
-  just workspace ID or in
-  the namespace:workspace_name form, where namespace is optional (e.g :workspace_name is valid key too. 
- namespace/workspace_name form, where namespace can contain '/' character.
