### ISSUE TITLE
Move preparing of RuntimeContext to the async phase of workspace start

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#8989]
### Description
[Preparation of RuntimeContext](https://github.com/eclipse/che/blob/2c2bd6637c8169018e2b33397f9d738bbf82a0b1/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/RuntimeInfrastructure.java#L98) may last a long period of time, like when Infrastructure needs to fetch images or send few requests during context preparing.
But it leads to issue with interruption of start workspace request. It happens because it is performing synchronously (see related code [here](https://github.com/eclipse/che/blob/21e00e9b15795415259ed06d65d83fbd1eb47913/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L213
)). And browser interrupts requests if they last more than 30 seconds.
![screenshot_20180302_125034](https://user-images.githubusercontent.com/5887312/36895747-b3e85502-1e18-11e8-8901-991698ba3f4d.png)

To fix this issue and make it possible to perform long living tasks while RuntimeContext preparing it is needed to move preparing of RuntimeContext to the async phase of workspace start. So context preparation should be a part of the [WorkspaceRuntime.StartRuntimeTask#run](https://github.com/eclipse/che/blob/21e00e9b15795415259ed06d65d83fbd1eb47913/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L262) method.

Also, it is required to set workspace status to STARTING when infrastructure is preparing context.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
Since the creation of a runtime context is one of the points of extension of SPI there is a lot of reasons why it may last a long time. I think it is very frustrating if this cause long execution of workspace starts API which is supposed to be asynchronous API.
@sleshchenko I think we even might tag it as a bug.

**Comment by sleshchenko** [comment]
Update:
Also, it is required to set workspace status to STARTING when infrastructure is preparing context.

**Comment by sleshchenko** [comment]
Tried to move preparing of RuntimeContext to the async phase of workspace start and found out that there is an issue with cancelation. It is supposed that the workspace start may an interruptible process if infrastructure supports it (as docker, kubernetes, openshift support do). 
There should be an ability to cancel context preparing as well when it will be moved to async part and long tasks can be submitted here.
SPI interface should be adapted to support it: 
- maybe contexts should be cached by WorkspaceRuntime instead of caching of runtimes;
- infrastructure should return something like cancelable future or context should provide a method for preparing interruption;
- Infrastructures implementations should provide their own context preparing cancelation, the same as it is done with runtime start interruption;
