### ISSUE TITLE
[OCP-platform] It is not enough information in ocp logs when test failed 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#8991]
### Description
* Sometimes the selenium tests fail by reason fail  start workspace
* And we do not have enough information in the _ocp logs_
* It impedes to find and resolve the bug 

**Che version:** 6.2.0
**OS and version:** Fedora 25
**Che install:** OCP (single/multi)

**Additional information:**
* Related issues: #8876, #8856
* Related selenium test: _it may be any test_
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* See the attachment:

**_ocp-logs (che-version 6.2.0):_**
![info-ws-failed](https://user-images.githubusercontent.com/5408906/36896687-49895446-1e1c-11e8-826f-469d20cc7cc3.png)

**Comment by garagatyi** [comment]
@artaleks9 is this still actual?

**Comment by artaleks9** [comment]
I think, it is not already actual.
I close the issue.
