### ISSUE TITLE
Workspace Pod throws Insufficient Memory Error

### ISSUE THREAD

**Issue by EriksonMurrugarra** [eclipse-che/che#8996]
### Description

Hi.

I am deploying Eclipse che on my minikube cluster and when it tries to create a workspace Pod it is throwing the following error:

**0/1 nodes are available: 1 Insufficient memory.**

I am starting minikube with the default options by running : **minikube start.**

Could you please provide some advice? thank you.

**Comment by skabashnyuk** [comment]
How much memory can you give for minikube. I recommend to start with 8G and then test with 6G or 4G

**Comment by eivantsov** [comment]
Recreate MiniKube with `--memory=4096`

**Comment by kostiamol** [comment]
And what about multi-user mode with keycloak and postgresql? How much memory do we need in that case?
