### ISSUE TITLE
Allow to configure logback logger with env variables

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#8997]
### Description

Now in most cases, we have two regimes of logger INFO or DEBUG.
But during development, especially when Che is working inside of containers,
when it's not easy to reconfigure logback with xml configuration or JMX,
it might be useful to be able to configure particular logger. For example like 

```
CHE_LOGGER_CONFIG=org.eclipse.che=DEBUG,org.eclipse.che.api.installer.server.impl.LocalInstallerRegistry=OFF 
```
To be able to configure ws-master  - a user will have to add this variable to che.env
In case of ws-agent - a user will have to add this variable to env configuration of the desired machine.

**Comment by benoitf** [comment]
It would be nice to toggle dynamically a logger as well
Through jmx or rest API or with Admin/UD console

**Comment by skabashnyuk** [comment]
>It would be nice to toggle dynamically a logger as well
> Through jmx or rest API or with Admin/UD console

Nice idea, do you see a way how it can be easily implemented?

**Comment by benoitf** [comment]
I implemented it once, I will search how I had it done
