### ISSUE TITLE
The CHE try to apply nonexistent installer in configuration after consuming a factory

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9001]
### Reproduction Steps:
**Try to consume the factory like:**
`che_url/f?url=https%3A%2F%2Fgithub.com%2FTarrantella%2FgitPullTest%2Ftree%2Fcontrib-12092015`
**Expected result:** The factory do not have `terminal installer` in the configuration. So, the workspace should be created without including the terminal. The workspace should be created without errors.
**Actual result:** The workspace try to load terminal and we have unexpected errors like on screenshot.
![selection_003](https://user-images.githubusercontent.com/1640058/36932449-beee7562-1ed1-11e8-8f17-43085740297b.png)

**OS and version:**   Fedora 25, CHE-6.2.0 SNAPSHOT

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
