### ISSUE TITLE
Store pre-saved web driver logs after the selenium test execution finished at pr-build CI job

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9008]
### Description
Selenium tests are storing _failed test web driver logs_ in the directory **"selenium/che-selenium-test/target/webdriver-logs"** (issue #8857). 
They should be stored in the http://tests.codenvycorp.com/selenium_test_report_data folder as well in case of executing selenium tests on [pr-build CI jobs](https://ci.codenvycorp.com/view/pr-builds/).

**Comment by riuvshin** [comment]
Done
