### ISSUE TITLE
manageUsers is not a valid action for system domain in Permissions

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#9009]
### Description

I was trying to create users using the API in multi-user che and realized I need to give manageUsers permission to the current user, but when attempting to do so, it seems like manageUsers is not a valid action for the domain system.

Is this a known issue or expected behaviour since this is a crucial requirement in our use-case.

### Reproduction Steps

![screenshot from 2018-03-05 12-22-46](https://user-images.githubusercontent.com/16825130/36961147-03c9cc50-2070-11e8-8404-1b23fae24e84.png)

OS and version:

Ubuntu 16.04
Multi-user Che v6.1.1

**Comment by skabashnyuk** [comment]
Unfortenently may not help. Our multi-user bundle is made in the way that user is creating automatically on a first login. https://github.com/eclipse/che/blob/master/multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakEnvironmentInitalizationFilter.java#L109 That means if you are using multiuser Che with Keyclok - you have to create a user on Keycloak and not on Che.

**Comment by mjshashank** [comment]
Okay, understood.

Does #9011 fix this though?

Because even if I create a user on Keycloak using its API, the user is not accessible to Che as such to be added to workspaces and other things.

**Comment by skabashnyuk** [comment]
>Does #9011 fix this though?

not really. 

>Because even if I create a user on Keycloak using its API, the user is not accessible to Che as such to >be added to workspaces and other things.

He has to login to Che at least once.

**Comment by mjshashank** [comment]
Oh. So just to clarify,

There's no way for me to create a user on Keycloak and add him to a workspace without having the user login with the credentials at least once?

If yes, there's no way for a user to be logged in and recognised by Che from an API call?

**Comment by skabashnyuk** [comment]
>If yes, is there a way for a user to be logged in from an API call and be recognized by Che?

You need to login on keycloak get jwt token and made a call to any Che API with this token. For instance
```
GET /api/user
```

Are you working on this usecase? https://github.com/eclipse/che/issues/6335

**Comment by mjshashank** [comment]
A very similar use-case actually. I am looking at this flow.
1. admin creating a workspace
2. creating a user on keycloak
3. adding the user to the created workspace
4. providing the user with the credentials to start working. (Preferable: should already be added to the workspace instead of it happening on login)

> You need to login on keycloak get jwt token and made a call to any Che API with this token.
I tried this. I created a user with username: newuser and password: password and got the token using

``` curl --data "grant_type=password&client_id=che-public&username=newuser&password=password" http://35.231.114.94:5050/auth/realms/che/protocol/openid-connect/token ```

Using the token received, I made a GET request to /api/users but got back

``` HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Unable to identify user bc4c19e7-ed2e-4fb0-ae95-cfaaeef30cd9 in Che database</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: Unable to identify user bc4c19e7-ed2e-4fb0-ae95-cfaaeef30cd9 in Che database ```

Is there something wrong I'm doing here or did you have something else in mind?

**Comment by skabashnyuk** [comment]
How did you add jwt token to your request to ```/api/user/```?

**Comment by mjshashank** [comment]
This was the CURL command I used

``` curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlMjNGc3kzRlI5dnRUZms3TGlkX1lQOGU0cDNoY0psM20wQTRnckIzNnJJIn0.eyJqdGkiOiI1MzM1YjUyNC1hNTliLTRjZGQtODJkZS02YWI1Y2QzMzc0NTIiLCJleHAiOjE1MjAyNDk1NjgsIm5iZiI6MCwiaWF0IjoxNTIwMjQ4NjY4LCJpc3MiOiJodHRwOi8vMzUuMjMxLjExNC45NDo1MDUwL2F1dGgvcmVhbG1zL2NoZSIsImF1ZCI6ImNoZS1wdWJsaWMiLCJzdWIiOiJiYzRjMTllNy1lZDJlLTRmYjAtYWU5NS1jZmFhZWVmMzBjZDkiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJjaGUtcHVibGljIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiNjk4MzQxOTItMzliZC00MzdiLThhNjQtMTMxY2ZmNjQ4N2QyIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vMzUuMjMxLjExNC45NDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInByZWZlcnJlZF91c2VybmFtZSI6Im5ld3VzZXIifQ.gum7gHXZ_TLLTbvimH59_woYMxRlCwqTaa-AFnDaZLoC7zAgCi3h94EquapjxBR0NdZU2XrYBYoQVt8EQGhZuig8TNQsO_uuywK4F_YMnZkU4EJy6eBAp6cwzw6ltbfrwXb4EY08lIbsjy5SlBpGZnXmVy0hXbE5un280LBVsfUOl9PiI7jsKPv7xBKuy1tjkk7Sz96SMJpHuxkVY_Jrw7Ptn-Rp6eqxNc2MrIVZhTxzJoxbEQB51T88Y-MsYoCt8wKjqjULI6QjrnWxmDgsVxlKVpjQKjJiiuSGcXbAGvF1PeMk6kht2j9eqq43FKQhifVsc5hLtU9dZhZIm48m9w' 'http://35.231.114.94:8080/api/user' ```

**Comment by skabashnyuk** [comment]
Do you have stack traces on che-master side?

**Comment by mjshashank** [comment]
Solved the issues, thanks for all the help.
The problem was that when I was creating a user in Keycloak, i was providing only a username and the values for email and name were being left as ```null```. This caused an error while making a GET call to che api. Populating all the required fields works, I'm able to get a successful response

**Comment by mjshashank** [comment]
@sbryzak As a related issue, deleting the user from Keycloak does not remove the user from Che as well, and since as admin user I don't have permissions to manageUsers (as described above), I'm unable to add a removed user to Che.

**Comment by skabashnyuk** [comment]
At this moment we don't have a plans to react to user deletion in Keycloak. But we are going to polish some corner cases https://github.com/eclipse/che/issues/8081

**Comment by mjshashank** [comment]
Okay, thank you!
