### ISSUE TITLE
Unable to manage users by an admin

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#9010]
### Description
Unable to manage users by an admin. The reason is that UserService and UserProfileService are covered with `manageUsers` action but this action is not returned by PermissionsService as supported.

Actual for Che 6.1.1 https://stackoverflow.com/q/49079318/9365723
**OS and version:**    

**Diagnostics:**

**Comment by benoitf** [comment]
related to https://github.com/eclipse/che/issues/9009
