### ISSUE TITLE
[REGRESSION] CHE Multiuser, cannot start workspace from the Dashboard

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#9024]
**Reproduction Steps:**
Start any workspace from the **Dashboard**

**Actual result:** the workspace not started

**OS and version:**
Che 6.2.0-SNAPSHOT; Chrome 63.0; Fedora 25

**Additional information:**
![org eclipse che selenium factory checkfactorywithsincepolicytest checkfactoryacceptingwithsincepolicy_8ss6az1b](https://user-images.githubusercontent.com/7760565/37019601-92e02798-2121-11e8-9ea8-abc57f7540d3.png)
![nimbus-record-video-2018-03-06-09-33-26](https://user-images.githubusercontent.com/7760565/37019615-a0717d8a-2121-11e8-93ab-bf6ed63d6ac7.gif)

![selection_200](https://user-images.githubusercontent.com/7760565/37020042-1e1845ec-2123-11e8-9b39-0456e6031fea.png)

**Comment by Ohrimenko1988** [comment]
![screenshot from 2018-03-06 09-37-25](https://user-images.githubusercontent.com/22724619/37019721-08d730e0-2122-11e8-9cb0-7c004d7291b1.png)

**Comment by riuvshin** [comment]
seems issue is related to: https://github.com/eclipse/che/pull/8838
