### ISSUE TITLE
Files created in terminal don't appear in the project explorer

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#9026]
### Description

In some situations the project explorer is not kept in sync with the filesystem when creating or deleting files via terminal or other tools.

### Reproduction

In Che 6.1.1: 

- create blank project named "test" (the project is created in collapsed state in the project explorer)
- expand the project (the README.md should appear)
- collapse the project in the project explorer
- in the terminal do "echo hello > test/test.txt"
- now expand the project node in the project explorer

-> the file text.txt is not there and will not appear unless you perform a refresh or create a new subfolder.

- the same problem happens on all subfolders and also when deleting files.
- note, that this doesn't happen if you don't expand and collapse the project initially.

**Comment by artaleks9** [comment]
Still actual for ver.6.5.0

**Comment by vzhukovskii** [comment]
Confirm this bug. Taking this issue into progress.

**Comment by vzhukovskii** [comment]
Fixed
