### ISSUE TITLE
Username of git committer on shared workspaces does not change after first commit

### ISSUE THREAD

**Issue by mt-k** [eclipse-che/che#9029]
### Description
When using a shared workspace in che multi-user, git commit and push uses always the username and email of the user who committed first after the workspaces has started.

### Expected Behavior
Git commands should use the name and email of the user executing the command.

### Reproduction Steps
* As user1:
  * Create a new workspace
  * Share the workspace with user2
  * Open the workspace and go to Profile / Preferences
  * Set username and email for user1 in Git / Committer and save the values
  * Checkout a git project
  * Change a file
  * Go to Git / Commit...
  * Commit the changes
  * Git Console shows username and email of user1
* As user2:
  * Open the shared workspace and go to Profile / Preferences
  * Set username and email for user2 in Git / Committer and save the values
  * Change a file in the project
  * Go to Git / Commit...
  * Commit the changes
  * Git Console shows username and email of **user1** instead of username and email of user2

**OS and version:**    
  * Che 6.1.0 on CentOS 7.4

**Comment by eivantsov** [comment]
@vinokurig what's expected behavior here?

**Comment by vinokurig** [comment]
Committer info is stored in the user preferences, so commit message should show committer info related to current user.

**Comment by eivantsov** [comment]
@vinokurig so behavior @mt-k describes is a bug?

**Comment by vinokurig** [comment]
looks like that

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/17)
