### ISSUE TITLE
Do not use data volume to store agents on OpenShift/Kubernetes

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9040]
### Description
The basic idea is not to use data volume on OpenShift/Kubernetes at all. If ws-master want's to persist something it has to be stored in database or external storage. Now we store three things
 - Logs
- h2 database
-  agents

The goal of this issue is to deal only with agents

**Comment by akorneta** [comment]
removed backup of agents, removed che-data PVC for Kubernetes/OpenShift deployments:
https://github.com/eclipse/che/pull/9236
