### ISSUE TITLE
Add documentation for running single user Che with Keycloak on oso pro

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#9045]
### Description
The motivation behind this requirement is making `che-host` url **not** publicly available for single-user usecase. However, `single user Che with Keycloak = multi-user Che with Keycloak` where there is only one user registered. e.g. if user wants to have che-host secured by keycloak he will need to deploy multi-user che and have only one user registered for his account. Probably, we just need to clarify this point in the docs. Also,  we could have a mention about why we do not recommend to deploy Che single-user on OSO (url will be publicly available)

related rh-che issue: https://github.com/redhat-developer/rh-che/issues/542

**Comment by skabashnyuk** [comment]
> Probably, we just need to clarify this point in the docs

I gues it's not a case. I think we never assume that ```single user Che with Keycloak ```as something real.
The use case for me is a bit unclear.  Do you want to connect ws-master in the multiuser mode to remote keycloak?

**Comment by gorkem** [comment]
@ibuziuk I am closing this as I do not think this is a valid case anymore
