### ISSUE TITLE
CHE_WORKSPACE_AGENT_DEV_MAX__START__TIME__MS not being applied

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#9048]
### Description

Using the following command to run Che:

`docker run -it --rm -e CHE_MULTIUSER=true -e CHE_WORKSPACE_AGENT_DEV_MAX__START__TIME__MS=90000000 -e CHE_HOST=$(ip route get 8.8.8.8 | awk '{print $NF; exit}') -v /var/run/docker.sock:/var/run/docker.sock -v /home/me/che/:/data eclipse/che:6.2.0 start --fast --offline`

I would hope I provided enough time for a workspace to boot, but the boot stops after four minutes, seemingly ignoring the 1500 minute argument.

![image](https://user-images.githubusercontent.com/4656027/37126516-fa009780-2236-11e8-8700-38e850476c72.png)

![image](https://user-images.githubusercontent.com/4656027/37126623-743eeb8c-2237-11e8-868b-3f16487120f7.png)

### Reproduction Steps

Create a workspace that needs a time to create _such as `
51234/nodeeight`_ . . .Or perhaps use a computer with similar specs as mine: 

[speedtest-net](https://www.npmjs.com/package/speedtest-net)

| Ping | Download | Upload |
| ------------- | ------------- | ------------- |
| 79.3 ms  | 10.2 Mbps | 2.9 Mbps |
  
`lshw`

```
    *-cpu
          product: Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
          vendor: Intel Corp.
     *-memory
          description: System memory
          physical id: 0
          size: 7841MiB
```

**OS and version:**    

Ubuntu 16.04.4 LTS

```
Your CLI version is '6.2.0'.
Your installed version is '6.2.0'
```

I was facing this issue with 6.1.1 too, but I waited to comb through documentation to ensure I hadn't overlooked a simple configuration issue. I've also had some life changing events happen the last week.

**Diagnostics:** 

`2018-03-08 01:30:02,615[nio-8080-exec-7]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 228]   - Starting workspace 'me-Home/wksp-8ez6' with id 'workspace7y5xstn0zurgaoiy' by user 'admin'`
`2018-03-08 01:33:17,799[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 284]   - Workspace 'me-Home:wksp-8ez6' with id 'workspace7y5xstn0zurgaoiy' start failed`

**Comment by agala-stratio** [comment]
Try to change it directly in the file 
<data_path>/conf/che/che.properties, param: _che.workspace.agent.dev.max_start_time_ms_
I had a similar issue with che.workspace.agent.dev.inactive_stop_timeout_ms

**Comment by gnoejuan** [comment]
Hmm, I seem to be unable to find that file

![image](https://user-images.githubusercontent.com/4656027/37154066-70407024-22a4-11e8-83fc-809e5c69ca21.png)

![image](https://user-images.githubusercontent.com/4656027/37154124-a69f1b70-22a4-11e8-9562-67c6cf219a41.png)

I was able to find two che.env, one at che/che.env and one at che/instance/config/che and both have the appropriate value. 

I also ssh'd into che server with `docker exec -it che /bin/bash` and `/conf/che.env` has the appropriate value....

I found `che.properties` in `/home/user/eclipse-che/tomcat/webapps/api/WEB-INF/classes/che` using `find -name che.properties`

using vi and typing "/che\.workspace\.agent\.dev\.max_start_time_ms` returned no results

is /conf/che/che.properties somewhere else?

**Comment by gnoejuan** [comment]
I found two more instances at `/etc/che/che.properties` and `/home/user/che/conf/che.properties` .

Changing the values did not solve the issue

**Comment by eivantsov** [comment]
@gnoejuan can you give it a try with modifying this property in `che.env` which is in the root of your local Che data folder.

**Comment by gnoejuan** [comment]
Sorry. After changing the values of /etc/che/che.properties and /home/user/che/conf/che.properties che.properties, Che would not start. I tried 'che init' and uninstalling both che and docker. 

In the end, I simply started over with a fresh install of Ubuntu. 

Now there is no 'che.properties' on the local system, but now the `-e CHE_WORKSPACE_AGENT_DEV_MAX__START__TIME__MS` appears to be respected.

**Comment by eivantsov** [comment]
@gnoejuan to qualify it as a bug I'd need steps to reproduce.
