### ISSUE TITLE
Che server not loading

### ISSUE THREAD

**Issue by ShivaniBali** [eclipse-che/che#9050]
Eclipse Che server not loading:
Command: docker run -v /var/run/docker.sock:/var/run/docker.sock -e CHE_DEBUG_SERVER=true -e CHE_ASSEMBLY=/home/dietrich/che-dev/che/assembly/assembly-main/target/eclipse-che-6.0.0-M4/eclipse-che-6.0.0-M4/ codenvy/che-launcher:nightly start

On every run of che-server container, blank page opens on server. http://172.17.0.1:8080/

Kindly let me know what do I need to fix this issue?

Screenshot attached for reference.
<img width="1433" alt="screen shot 2018-03-09 at 12 22 39 am" src="https://user-images.githubusercontent.com/35276146/37191884-5d31e74c-2330-11e8-9b5e-98224dfa53f5.png">

PS: No error message is appearing on console. Docker logs attached.
[Logs.docx](https://github.com/eclipse/che/files/1795738/Logs.docx)

Thanks you!

**Comment by eivantsov** [comment]
You are using outdated installation instructions.

https://www.eclipse.org/che/docs/6/che/docs/docker-single-user.html

**Comment by ShivaniBali** [comment]
@eivantsov Thank you, I will make a note of it!
