### ISSUE TITLE
Copy and pasting a file onto itself will delete its contents

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#9052]
### Description

This is a minor misbehaviour in the project explorer (not a really important use case, just felt I can report it):

- In Che 6.2.0 create a blank workspace with a blank project and a file inside (e.g. README)
- Right-click the file: copy
- Right-click on the project node: paste.  (A dialog appears and asks whether I want to rename the file or just overwrite it (or abort).)
- Choose "Overwrite".
> The file is gone.

Expected Behaviour: the file is unchanged.
Note: in 5.22.1 the file remains but is empty afterwards.

**Comment by eivantsov** [comment]
@ChristianSchenk711 confirmed. The file is indeed removed from fs
