### ISSUE TITLE
Python and installing library (MIDIUtil)

### ISSUE THREAD

**Issue by DisruptiveAudio** [eclipse-che/che#9054]
### Description
Hello,
I am new to CodeEnvy and trying to get MIDIUtil library installed on a Python installation but can't seem to figure it out.

Can you possible help?

Thank you

>> HERE IS THE ERROR MESSAGE FROM TERMINAL.

user@7a26cbf6a741:/projects$ pip install MIDIUtil
Collecting MIDIUtil
  Using cached MIDIUtil-1.2.1.tar.gz
Installing collected packages: MIDIUtil
  Running setup.py install for MIDIUtil ... error
    Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n3xno_94/MIDIUtil/setup.py';f=getat
tr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0juel
fgo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/midiutil
    copying src/midiutil/MidiFile.py -> build/lib/midiutil
    copying src/midiutil/__init__.py -> build/lib/midiutil
    running egg_info
    writing src/MIDIUtil.egg-info/PKG-INFO
    writing dependency_links to src/MIDIUtil.egg-info/dependency_links.txt
    writing top-level names to src/MIDIUtil.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'src/MIDIUtil.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'build'
    warning: no previously-included files matching '*' found under directory 'dist'
    warning: no previously-included files matching '*.pyc' found under directory '.'
    warning: no previously-included files matching '__pycache__' found under directory '.'
    writing manifest file 'src/MIDIUtil.egg-info/SOURCES.txt'
    creating build/lib/midiutil/__pycache__
    copying src/midiutil/__pycache__/MidiFile.cpython-35.pyc -> build/lib/midiutil/__pycache__
    copying src/midiutil/__pycache__/MidiFile.cpython-36.pyc -> build/lib/midiutil/__pycache__
    copying src/midiutil/__pycache__/__init__.cpython-35.pyc -> build/lib/midiutil/__pycache__
    copying src/midiutil/__pycache__/__init__.cpython-36.pyc -> build/lib/midiutil/__pycache__
    running install_lib
    creating /usr/local/lib/python3.5/site-packages/midiutil
    error: could not create '/usr/local/lib/python3.5/site-packages/midiutil': Permission denied
### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
@DisruptiveAudio give it a try with `sudo` perhaps?
