### ISSUE TITLE
centralized snapshots on che 6 ?

### ISSUE THREAD

**Issue by alu0100825510** [eclipse-che/che#9055]
How can you make snapshots in che 6? I know it is with volumes, I would like to be able to have that data centralized in an external machine, just like it was done with che 5.x when sending everything to an address of a docker registry server.

**Comment by gorkem** [comment]
snapshots is no longer supported on Che 6. It was kind of an anti-pattern and was not really supported by container management systems like kubernetes. 

I am interested to know your use case for the snapshots?

**Comment by alu0100825510** [comment]
@gorkem With che 5.x I could do a centralized storage of all the data, for example on a machine had a server of docker registries to save the snapshots and the information stored in /data, in this way I can create all the machines that I want around this, since accessing the snapshot and /data will not lose any information giving equal to what machine Che runs.
with Che6 I do not know how I could save all the information that I have named outside the machine and that it is accessible from others.

**Comment by eivantsov** [comment]
@alu0100825510 I do not understand what you mean by information named outside machines. Can you elaborate?

**Comment by alu0100825510** [comment]
for example I have three machines, m1 m2 and m3, in m1 I keep all the information /data of the che servers, which are running in m2 and m3. So I want all the information of the workspaces to be saved in m1 (not just the projects)

**Comment by eivantsov** [comment]
You can define volumes per machine. Go to workspace details view in UD, and you will see volumes tab

**Comment by alu0100825510** [comment]
@eivantsov yes, but how do I indicate that they are stored inside the folder of their corresponding external workspace like /projects?

**Comment by eivantsov** [comment]
They are stored in docker volumes. It's not bind mount

**Comment by alu0100825510** [comment]
This is the inconvenience that I said, because if for example we change from machine m2 to m3 and try to run the same server accessing / data that is centralized in m1, the volumes will disappear, since before they were in m2 and now in m3 they aren't.
With the snapshots of Che5, we could centralize the 'volumes' in a centralized record server, so they were accessible from all the machines, they were not overlapped to the machine.
I do not know if I explained myself well, thank you very much

**Comment by eivantsov** [comment]
@vivasagit once again, you can define volumes for workspaces and persist npm modules
