### ISSUE TITLE
About load balancing when Eclipse Che is executed on AWS

### ISSUE THREAD

**Issue by ktdjun** [eclipse-che/che#9056]
### Description
I am trying the load balancing of Eclipse Che 6.2.0 on EC2 instance of AWS.
I am using Application Load Balancer provided by AWS, and the following settings are applied.

- 8080 port and 5050 port are set in Listener.
- Multiple EC2 instances are set for Target Group for each Listener.
   The states of 8080 port and 5050 port are all healthy.
- I am applying Sticky Session.

Che Server and Key Cloak were load balanced among multiple EC2 instances.

However, I can not display the screen of Workspace to the browser.
Connection refused from Application Load Balancer.

I think that probably because I can not set the port used by Workspace as Listener of Application Load Balancer.
This is automatically assigned from the ephemeral port, so port setting to the Listener is difficult.

Could you please provide some advice?
If there is any mistake in my way of thinking, please point out.
Thank you.

**OS and version:**    
- OS          : Amazon Linux AMI release 2017.09
- Eclipse Che : v6.2.0 (Multi-User: Install on Docker)
- Docker      : 17.09.1-ce

**Comment by skabashnyuk** [comment]
What is the end goal what you want to achieve? Is this performance of ws-master? Or this is about redundancy or fail tolerance https://github.com/eclipse/che/issues/7662? Or this is about hot-update https://github.com/eclipse/che/issues/8547 or blue-green deployment. Are you using Kubernetes or OpenShift as a platform?

**Comment by ktdjun** [comment]
@skabashnyuk 
Thanks for the reply.

I think the goal is the same as #7662.
What I mean is that the goal is load balancing and availability of che-server container.
Also, I would like to use multi-user authentication of KeyCloak.

I'm sorry, In combination with AWS, I have not used Kubernetes or OpenShift yet.
At the moment, can I use OpenShift to realize load balancing and availability?

I confirmed that the multi-user function of Kubernetes has not yet been implemented from the following.
#8745

**Comment by skabashnyuk** [comment]
>At the moment, can I use OpenShift to realize load balancing and availability?

At this moment - no. But we are moving in that direction. A first step will be https://github.com/eclipse/che/issues/8547
