### ISSUE TITLE
Feature Request: Provision to integrate Codota with eclipse-che

### ISSUE THREAD

**Issue by sachidananda04** [eclipse-che/che#9060]
Hi,

Was just wondering, if there is any provision to integrate Codota (more info: https://www.codota.com/) with che.  I have a debian package of Codota and have installed on ubuntu and was able to bring up the codota application. I am trying to explore whether the same deb package can be integrated with eclipse-che. Looking for useful pointers/references.

Thanks

**Comment by eivantsov** [comment]
@sachidananda04 not with Codota

You may follow this epic https://github.com/eclipse/che/issues/8286
