### ISSUE TITLE
K8S / OpenShift infrastrucrures should support grace termination period of pods

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#9062]
By default grace shutdown period of pods on k8s / openshift defaults to 30 seconds. In Che 5 pods are created with `0` grace period which allows to kill a pod almost instantly and free the resources. This becomes vital for osio where it is only allowed to have single running workspace at a time. We need to support `0` grace termination period either via default property or hardcoded (not sure if this property should be configurable actually)

[1] https://github.com/eclipse/che/blob/5.22.x/plugins/plugin-docker/che-plugin-openshift-client/src/main/java/org/eclipse/che/plugin/openshift/client/OpenShiftConnector.java#L197

**Comment by ibuziuk** [comment]
@garagatyi @l0rd WDYT ?

**Comment by garagatyi** [comment]
I opt for a property that configures or enables/disables zero time shutdown.
@sleshchenko WDYT?

**Comment by l0rd** [comment]
@ibuziuk it makes sense to set grace period to zero but having a property to disable it is even better

**Comment by ibuziuk** [comment]
sounds good, so looks like we need a property for setting workspace pod termination period which would defaults to 0

**Comment by garagatyi** [comment]
@ibuziuk do we have a tracking issue in rh-che repo? What priority should be set on this issue?

**Comment by ibuziuk** [comment]
There is no issue in rh-che for that, in terms of priority IMO it's P1

**Comment by ibuziuk** [comment]
PR is sent https://github.com/eclipse/che/pull/9118

**Comment by ibuziuk** [comment]
PR for doc

**Comment by ibuziuk** [comment]
PR & PR for docs have been merged. Closing
