### ISSUE TITLE
Wrong author name when perform 'git revert commit'

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#9066]
### Description
_There is unexpected wrong author name when perform 'git revert commit'_

**Reproduction Steps:**
* Open the IDE, create a project from template (e.g. `web-java-spring`)
* Delete the local repository and then initialize it again
* Update a file/s and commit changes (e.g. _README.md_ file)
* Perform `git revert commit` a file
* Check the author name in the `git revert commit` form

**Expected behavior:** 
* should be correct user name

**Observed behavior:**
* the author name is wrong 

**Che version**: 6.3.0
**OS and version:** Fedora 25
**Che install:** Docker/OCP
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Related selenium tests: PR #9030: _RevertCommitTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![unknown-user-git-revert](https://user-images.githubusercontent.com/5408906/37287709-1cc09e7a-260e-11e8-9343-1b6fb9bfdf35.png)

**Comment by vinokurig** [comment]
This is expected behavior. Revert commit removes changes from specified commit and makes a new commit from current user.
