### ISSUE TITLE
Investigate the better way for providing list of plugins to web worker

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9068]
Need to find the way of providing plugins to the web worker. It could be es6 modules introduced by http 2 or  commonjs modules or providing single js generated.

**Comment by akurinnoy** [comment]
As far as the support of ES6 modules is not completely implemented in the browsers, we decided to use `importScripts` method from WebWorker to be able to load a bunch of plugin scripts at ones. See https://html.spec.whatwg.org/multipage/workers.html#importing-scripts-and-libraries
