### ISSUE TITLE
Workspace life cycle events for Workspaces apart from Factories

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#9077]
For the use case I'm working on, we'd prefer to use individual workspaces rather than factories, but would be great to be able to use the life cycle events that factories are provided with to perform IDE actions. Is this possible right now or something that might be added later?

**Comment by mjshashank** [comment]
I was looking at the [documentation](https://www.eclipse.org/che/docs/6/che/docs/factories_json_reference.html) for factories and saw that there were events like ``` onProjectsLoaded ``` or ``` onAppLoaded ``` which could be used to trigger IDE actions like runCommand or openFile. 

I was wondering if the same could be done in workspace configuration even though the workspace documentation doesnt describe it.

**Comment by skabashnyuk** [comment]
I think there is no way to do like you want. Maybe you can reuse one of this features of factory https://www.eclipse.org/che/docs/6/che/docs/creating-factories.html#multiplicity
