### ISSUE TITLE
How do I change the port 5050 for keycloak?

### ISSUE THREAD

**Issue by unisqu** [eclipse-che/che#9078]
How do I change the port 5050 for keycloak?
i only found CHE_PORT

**Comment by skabashnyuk** [comment]
In case if you have your custom keycloak installed somewhere you can configure it with ```CHE_KEYCLOAK_AUTH__SERVER__URL```

**Comment by unisqu** [comment]
i dont have custom keycloak, i just dont like my ports to be opened here and there without control. i do prefer if have a keycloak port change feature though.

**Comment by skabashnyuk** [comment]
How do you run Eclipse Che?

**Comment by eivantsov** [comment]
@unisqu you can customize composefile which is in your Che local data directory.

**Comment by unisqu** [comment]
ok thanks.
