### ISSUE TITLE
Overriding CHE_HOST from che.env file works, but output of "start" command is wrong.

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#9080]
### Description
Overriding CHE_HOST variable works - che starts up successfully, but at the end of the startup script, wrong IP (the one from che.env) is used to show user where to access che and swagger.

```
╭─rhopp@rhopp ~/ 
╰─$ docker run -e CHE_HOST=10.40.5.135 -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/rhopp/temp/data:/data eclipse/che:6.2.0 start         
INFO: (che cli): 6.2.0 - using docker 1.13.1 / native
WARN: (che cli): 'CHE_HOST=10.40.5.135' from command line overriding 'CHE_HOST=10.40.4.120' from che.env
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [OK]
         conn (server => ws):     [OK]

INFO: (che start): Starting containers...
INFO: (che start): Services booting...
INFO: (che start): Server logs at "docker logs -f che"
INFO: (che start): Booted and reachable
INFO: (che start): Ver: 6.2.0
INFO: (che start): Use: http://10.40.4.120:8080
INFO: (che start): API: http://10.40.4.120:8080/swagger
```
Notice that I've passed `-e CHE_HOST=10.40.5.135`. This is the correct IP I want che to start with. 
Line `WARN: (che cli): 'CHE_HOST=10.40.5.135' from command line overriding 'CHE_HOST=10.40.4.120' from che.env
` says it was correctly used instead of `10.40.4.120` from che.env.

So far everything is good.

But on the end of the output, the wrong IP (from che.env) is used:

```
INFO: (che start): Use: http://10.40.4.120:8080
INFO: (che start): API: http://10.40.4.120:8080/swagger
```

### Reproduction Steps
* Have some value of CHE_HOST in che.env
* Start che with `-e CHE_HOST <different_value>`
* See output.

**OS and version:**    
Fedora 27,
Docker 1.13.1

**Diagnostics:**

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.
