### ISSUE TITLE
shm_size is not supported when creating a stack.

### ISSUE THREAD

**Issue by Daniel-Dos** [eclipse-che/che#9081]
### Description
When I try to create a custom stack with Oracle Database for multiple machines from the Java-MySQL stack, the "shm_size" parameter is not allowed.

The same is required for the Oracle 11g docker image to work as demonstrated by the docker command:

```
docker run --name <container name> \
--shm-size=1g \
-p 1521:1521 -p 8080:8080 \
-e ORACLE_PWD=<your database passwords> \
-v [<host mount point>:]/u01/app/oracle/oradata \
oracle/database:11.2.0.2-xe
```
is there any way this parameter works or is not supported by Eclipse Che?

thanks
**OS and version:**    
Ubuntu 16.04
Docker CE 17
Eclipse Che 6.1.1

**Comment by eivantsov** [comment]
@Daniel-Dos currently there's no way to pass this param to a workspace container.

**Comment by garagatyi** [comment]
Hi Daniel. You can contribute this feature to the project and become a member of our Eclipse committers community!
Here is a bit long but not very complex flow on how to contribute it:
- add the field to [compose model](https://github.com/eclipse/che/blob/master/infrastructures/docker/environment/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/compose/model/ComposeService.java#L61-L61). See docs from Compose on how it looks like https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources
- add it to [Docker container model](https://github.com/eclipse/che/blob/master/infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/model/DockerContainerConfig.java#L57-L57)
- [copy](https://github.com/eclipse/che/blob/master/infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/environment/convert/ComposeEnvironmentConverter.java#L47-L47) it from Compose model to Docker container config model  
- Add it to [Docker client model](https://github.com/eclipse/che/blob/master/infrastructures/docker/docker-client/src/main/java/org/eclipse/che/infrastructure/docker/client/json/HostConfig.java#L46-L46). Look how `ShmSize` field looks in [Docker API docs](https://docs.docker.com/engine/api/v1.25/#operation/ContainerCreate)
- [copy](https://github.com/eclipse/che/blob/master/infrastructures/docker/infrastructure/src/main/java/org/eclipse/che/workspace/infrastructure/docker/DockerMachineStarter.java#L255-L254) it from Docker container config model to Docker API client 
- add it to your's workspace compose the recipe

Looking forward seeing you as a contributor!

**Comment by Daniel-Dos** [comment]
thanks @eivantsov  for the feedback.

@garagatyi  ,
I will try to implement this feature, thank you very much for providing the way.

**Comment by eivantsov** [comment]
@Daniel-Dos I am going to close this one. Feel free to open a PR or an issue if you have difficulties in implementing it

**Comment by Daniel-Dos** [comment]
@eivantsov , 

wonder, thank you very much. As soon as I have a cool time, I'll try the implementation.
