### ISSUE TITLE
eclipse-che Could not start workspace xxx Reason: Server 'wsagent/http' in machine 'dev-machine' not available.

### ISSUE THREAD

**Issue by zcc370884413** [eclipse-che/che#9083]
1、install che in win7 use docker with aliyun Image Accelerator： docker-machine create --engine-registry-mirror=https://xxx.aliyuncs.com -d virtualbox default
2、che start cmd：docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/user/che:/data eclipse/che:6.2.0 start
3、after install success，the ui diagnostics show error: "No reply of websocket test after 5 seconds. Websocket is failing to connect to ws://192.168.99.100:8080/api/ws"
4、create workspace（java stack）through ui，the ui ‘dev-machine’ panel show: " 2018-03-14 03:30:03,934[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 22991 ms"。but after a long time，the ui show error dialog："Could not start workspace zcc-java. Reason: Server 'wsagent/http' in machine 'dev-machine' not available".
5、another error tip:"Could not start workspace zcc-java. Reason: Runtime start for identity 'workspace: workspaceuwqgf44gv24sa1qi, environment: default, owner: che' is interrupted"

**Comment by eivantsov** [comment]
@zcc370884413 the error indicates that Che server cannot verify that ws agent is up even though it's actually up according to the logs. It means there's connectivity issues in your Docker VM, ie the ephemeral port range is unavailable from within a container.

There's a simple test that you can run without Che itself:

```
docker run -d -p 38999:80 nginx
docker run -ti appropriate/curl sh
curl -v $IP:38999
```
Can you see nginx welcome page this way? `$IP` is your local IP address.

**Comment by zcc370884413** [comment]
I try it with not stop the che container by Docker Quickstart Terminal，it's no problem，here is detail:
```
Administrator@5ZMVWBXFZH6AMR2 MINGW64 ~
$ curl -v 192.168.99.100:38999
* STATE: INIT => CONNECT handle 0x605a20; line 1392 (connection #-5000)
* Rebuilt URL to: 192.168.99.100:38999/
* Added connection 0. The cache now contains 1 members
*   Trying 192.168.99.100...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x605a20; line 1444 (connection #0)
* Connected to 192.168.99.100 (192.168.99.100) port 38999 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x605a20; line 1561 (connection #0)
* Marked for [keep alive]: HTTP default

```
should I close the firewall or ?

**Comment by zcc370884413** [comment]
@eivantsov Haha，this question is resolved，I closed the firewall when start che，here is the cmd：
`docker run **--privileged=true** -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/user/che:/data eclipse/che:6.2.0 start`
