### ISSUE TITLE
Ambiguous behaviour of resources.asFolder.getTree(depth) method

### ISSUE THREAD

**Issue by usersk12** [eclipse-che/che#9084]
I've following project structure in Eclipse Che

|-- A
|--|-- OPF
|--|--|--B
|--|--|--C

I'm using following code to access folder B and C inside OPF folder:

 ```
    Resource resource = appContext.getResource();
	if (resource == null) {
	    Log.info(Test.class, "Resource null");
	    return;
	}
	Project project = resource.getProject();
	if (project == null) {
	    Log.info(Test.class, "Project null");
	    return;
	}
	// Optional
	project.getContainer("/OPF").then(new Operation<Optional<Container>>() {

	    @Override
	    public void apply(Optional<Container> container) throws OperationException {
		if (container == null) {
		    Log.info(Test.class, "Container null");
		    return;
		}
		if (!container.isPresent()) {
		    return;
		}
		Container opf = container.get();
		Promise<Resource[]> resources = opf.asFolder().getTree(1);
		resources.then(new Operation<Resource[]>() {

		    @Override
		    public void apply(Resource[] resource) throws OperationException {
			if (resource == null) {
			    Log.info(Test.class, " resource null");
			    return;
			}
			for (int i = 0; i < resource.length; i++) {
                               Log.info(Test.class, "Folder name: " + resource[i].getName);
                        }
             }
```

The method opf.asFolder().getTree(1); behaves in an ambiguous manner. Sometimes, it returns the folder B and C only as resources (which is correct as depth is 1) and sometimes it returns the folders and files inside B and C folder too. 

Also, "Resource resource = appContext.getResource();" returns null when workspace first starts. It is loaded only after workspace is refreshed.

Kindly provide necessary help with the issue.

**Comment by eivantsov** [comment]
@vparfonov @vzhukovskii can you help please?

**Comment by vzhukovskii** [comment]
@usersk12, sorry for long delay in reply. Yes, there's a bug in the code, when user can received nested files and folders instead of requesting the first level depth. As a workaround, I can suggest you to use 'org.eclipse.che.ide.api.resources.Container#getChildren()' method instead call 'org.eclipse.che.ide.api.resources.Container#getTree'. I've reported an issue for this bug: https://github.com/eclipse/che/issues/9254

**Comment by eivantsov** [comment]
Closing. Feel free to follow https://github.com/eclipse/che/issues/9254
