### ISSUE TITLE
Already have a docker container running perfectly, how to share volume?

### ISSUE THREAD

**Issue by unisqu** [eclipse-che/che#9090]
Already have a docker container running perfectly, I would like share the volume

the perfected docker container is running with 
-v /usr/local/src/perfectedcontainer:/usr/local/src

how do i share this as a workspace while preserving the permission etc? how do I create a workspace that can do -v /usr/local/src/perfectedcontainer:/project/... etc?

**Comment by eivantsov** [comment]
@unisqu can you elaborate a bit on what you mean by having a docker container running perfectly? Do you want to share volumes between containers? Or do you want to bind mount a host volume?

**Comment by unisqu** [comment]
1. i want to share volumes between containers
2. i would also like to bind mount a host volume if possible.

for example, i've already ran 
    docker run -v /usr/local/src:/usr/local/src -it ubuntu:16.04 /bin/bash

i would like my docker container created to also have /usr/local/src/ shared... e.g. 
    -v /usr/local/src:/projects

along that line. is that possible? actually would like my workspace to directly access /usr/local/src/ on the host if possible

**Comment by unisqu** [comment]
any feedback on this question?

**Comment by eivantsov** [comment]
https://www.eclipse.org/che/docs/6/che/docs/volumes.html

And if you want to mount a host path, you can do so in a centralized way only, ie it will be mounted into all workspaces. In your che.env:

`CHE_WORKSPACE_VOLUME=/host/path:/container/path`
