### ISSUE TITLE
Exposed ports should be authenticated

### ISSUE THREAD

**Issue by ishitatsuyuki** [eclipse-che/che#9098]
### Description

Currently no authentication is performed in either single port mode or random ephemeral exposure mode, allowing attacker to access arbitrary services.

This is a **bad idea**! Workspace normally contains private information.

In multi-port mode, a port scan can be performed and you now have access to many user's VNC, essentially allowing you to do anything with their workspace. **This applies to Codenvy as well, basically trashing the privacy.**
In single-port mode, predicting workspace URL is harder but still possible. The procedure is basically same.

### Comparison with other providers

- Google Cloud Shell: an App Engine based proxy is used for authenticating all user requests. They use kind of wildcard DNS except it's single level so HTTPS is possible.
- Cloud9: authentication is performed using cookie or something. I don't use it so I don't know the details.

### Possible ways to solve

- Place some reverse proxy agent inside the workspace
- Put https://github.com/bitly/oauth2_proxy in front of Traefik. I'm not sure how we can configure the restriction.

**Comment by eivantsov** [comment]
@ishitatsuyuki are you talking about the IDE itself or user applications? In a multi user Che, all requests are secured with a token, both master and workspace services. User applications are merely webapps, so yes, they are exposed to the world, provided that you know the URL.

Please, note that Che isn't designed to host apps.

**Comment by ishitatsuyuki** [comment]
@eivantsov I'm talking about user applications.

> User applications are merely webapps

You can't call it "merely", servers for development and production are two different things. Development servers are not secured, and exposing them without authentication is a bad thing.

Also, VNC is a valid usecase to expose ports, while the default workspace example doesn't attempt to secure it. There are plenty of running workspaces with unprotected VNC enabled on Codenvy (detected from port scan), which means that it's a widespread usecase.

> Please, note that Che isn't designed to host apps.

I didn't get what you mean by "host apps", but previewing and remote desktop are both important when developing in the cloud.

I have listed what the alternatives do, and it's quite clear that we should put an authentication layer like others do.

**Comment by eivantsov** [comment]
@ishitatsuyuki in Eclipse Che, you need to explicitly declare a server to publish an exposed port (unlike Codenvy where all exposed ports are automatically published).

What do you call an unprotected VNC? Can't you secure it with a password?

**Comment by ishitatsuyuki** [comment]
> in Eclipse Che, you need to explicitly declare a server to publish an exposed port

It doesn't matter. When you create things from a stack, they are open by default.

https://github.com/eclipse/che/blob/a5494dd4ee3f7bb6e019531889a751a79c6a66b8/ide/che-core-ide-stacks/src/main/resources/stacks.json#L1801-1804

> Can't you secure it with a password?

Configuring password for each workspace by hand is poor UX.

**Comment by eivantsov** [comment]
Closing the issue.

Che relies on Docker, OpenShift and Kubernetes. Each has own ways to expose services. Che just uses what an infrastructure has to offer.
