### ISSUE TITLE
Unexpected failure of selenium tests which are create workspaces from Dashboard

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#9100]
### Description
We have unexpected fail of selenium tests that create workspaces from **Dashboard**. The tests, sometimes, fail while waiting that **Project Explorer** visibility. We should clarify reason and fix it.

**Log:**
```
org.openqa.selenium.TimeoutException:  Expected condition failed: waiting for visibility of element located by By.id: gwt-debug-projectTree (tried for 240 second(s) with 500 MILLISECONDS interval) Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host: 'slave6.codenvycorp.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.16.1.el7.x86_64', java.version: '1.8.0_102' Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver 	at org.eclipse.che.selenium.dashboard.ImportProjectFromZipTest.importProjectFromZipTest(ImportProjectFromZipTest.java:83) Caused by: org.openqa.selenium.NoSuchElementException:  no such element: Unable to locate element: {"method":"id","selector":"gwt-debug-projectTree"}
```

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/146/Selenium_tests_report/

**Comment by SkorikSergey** [comment]
Check is this issue will not reproduce after https://github.com/eclipse/che/pull/9117.

**Comment by SkorikSergey** [comment]
Not reproduced after https://github.com/eclipse/che/pull/9262.

**Comment by SkorikSergey** [comment]
Reproduced on CI https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/177/Selenium_tests_report/.
**Failed test:** DirectUrlFactoryWithKeepDirectoryTest.

**Comment by dmytro-ndp** [comment]
IMHO it's worth to mention in merge commit that https://github.com/eclipse/che/pull/9375 fixes selenium tests DirectUrlFactoryWithKeepDirectoryTest.

**Comment by SkorikSergey** [comment]
Not reproduced.
