### ISSUE TITLE
Improve generation code from json to dto

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#9103]
### Description
Need to improve process of generating DTOs to avoid multiple unnecessary validation here:

https://github.com/eclipse/che/blob/master/wsagent/che-core-api-languageserver-maven-plugin/src/main/java/org/eclipse/che/api/languageserver/generator/FromJsonGenerator.java#L68

Firstly try to check if it is not JsonSerializable object

**Comment by mmorhun** [comment]
Not actual any more.
