### ISSUE TITLE
JAVA_HOME is null when running test via UI

### ISSUE THREAD

**Issue by dipak-pawar** [eclipse-che/che#9105]
### Description
Env variable JAVA_HOME is null when running tests from UI. Whereas it's working as per expectation when running maven build from terminal.

Reproduction Steps:
* Open project https://github.com/dipak-pawar/che_java_home_reproducer in che
* Run Junit Test from UI.

![screenshot from 2018-03-14 18-45-27](https://user-images.githubusercontent.com/7941617/37464049-2e8fe6ee-287d-11e8-95c1-cfecebfcd8ba.png)

**Comment by eivantsov** [comment]
@dipak-pawar what stack do you use?

**Comment by dipak-pawar** [comment]
@eivantsov I have used `vert.x`, `java-centos`. Getting same issue for both the stack.

**Comment by eivantsov** [comment]
Is `JAVA_HOME` set as env there? Does `java.home` work?

**Comment by dipak-pawar** [comment]
I can echo `$JAVA_HOME` on che terminal. But couldn't get it in java program. 

whereas I can get `System.getProperty("java.home")` to respective jre directory.

**Comment by eivantsov** [comment]
Worked for me:

![image](https://user-images.githubusercontent.com/5337267/37467010-ca533542-2867-11e8-8bd1-bffd2bc4e765.png)
![image](https://user-images.githubusercontent.com/5337267/37467019-d09bda58-2867-11e8-8a2e-70cb434c2632.png)

**Comment by ibuziuk** [comment]
@eivantsov does it work in junit test ?

**Comment by eivantsov** [comment]
@ibuziuk I'll check

**Comment by ibuziuk** [comment]
@eivantsov thanks, because it fails for me ;-)

**Comment by dipak-pawar** [comment]
same case for me. It fails for Junit test.

**Comment by garagatyi** [comment]
Same for me - not available in unit tests

**Comment by vparfonov** [comment]
I think you can use `System.getProperty("java.home");` instead. 
We will close this issue as normal behavior because in you case tests run in separate jvm which doesn't have JAVA_HOME properties
