### ISSUE TITLE
Participation in openshift.io manual testing session.

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9106]
### Description
QE team should take part in the openshift.io manual testing session.
Details of this task in the internal document:
https://docs.google.com/document/d/1n6YiTgmd5dXyTNqtT7IRG41NC7fdBns8qzOx3EZZyFU/edit#heading=h.3ine1wuahhiw

**Comment by vkuznyetsov** [comment]
Test session completed. Here is the feedback.
