### ISSUE TITLE
Keycloak initialization failed

### ISSUE THREAD

**Issue by Alex1607** [eclipse-che/che#9108]
### Description
Che wont boot up / wont show me a login screen. After a whole reinstall.

### Reproduction Steps
Install Che with this command:
`docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=${EXTERNAL_IP} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start`
And the visit the site.

**OS and version:**    
Debian 9

**Diagnostics:** 
Chrome Console Log:
https://i.imgur.com/AdVGblw.png

Keycloak it self works just fine.

**Comment by eivantsov** [comment]
@Kavatch I can see that your CHE_HOST is null. Have you actually substituted `${EXTERNAL_IP}` with an actual IP of your machine?

**Comment by Kavatch** [comment]
When I replace the CHE_HOST with the IP and run the command it produces this error:
`Unable to find image 'eclipse/che:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
`
And this command:
`sudo docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=xxx.xxx.212.137 -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start`
(I replaced some numbers with a x)

**Comment by eivantsov** [comment]
Can you pull Docker images? Looks like there are some connectivity issues

**Comment by Kavatch** [comment]
Mh ok seems to be a connection error. I'll try to fix it and get back to you.

**Comment by patlachance** [comment]
@Kavatch any progess?

**Comment by Kavatch** [comment]
Unfortunately not yet, because I still have some difficulties with my hoster and have to clarify these first.

**Comment by Kavatch** [comment]
Okay, I got it 'working' now. It redirects me to Keycloak but gives me the error:
Invalid parameter: redirect_uri

I know there is a option somewhere in Keycloak of the config files to change this but I cant find it at the moment.

**Comment by eivantsov** [comment]
Login to Keycloak admin console at `${CHE_HOST}:5050`

Go to Clients, che-public:

![image](https://user-images.githubusercontent.com/5337267/37841461-783270f4-2ec8-11e8-886f-d33fed7d90a7.png)

Add urls you use to access Che. Both webOrigins and redirectUris.

**Comment by Kavatch** [comment]
Working now :D Thanks

**Comment by eivantsov** [comment]
I'm closing the issue then. Good to know it worked for you.
