### ISSUE TITLE
Preference property displacement 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#9110]
### Description
We have a preference property displacement  in Errors/Warnings section
![err_warn](https://user-images.githubusercontent.com/5676062/37508899-c0db1336-28fd-11e8-9e2f-b3a08b11b0d6.png)

**OS and version:**    
![che_version](https://user-images.githubusercontent.com/5676062/37508924-e4b9955c-28fd-11e8-8bb7-0b7a7c54f75e.png)

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/16)
