### ISSUE TITLE
Implement Custom Rename Refactoring Command

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9112]
The plan is to port what is necessary from org.eclipse.jdt.internal.corext.refactoring.rename in jdt.ui into jdt.ls (core ext package) in order to implement a command that can take the parameters we collect in the Che UI and returns a WorkspaceEdit (with file level ops)
@gorkem has code that uses a RenameProcessor and creates a WorkspaceEdit. Port more  RenameProcessors as needed to implement what we have currently in Che.

**Comment by svor** [comment]
Need to implement:

- [ ] Create custom command which takes the RenameSettings parameter. This parameter  collect all optional setting which can be chosen from UI and `org.eclipse.lsp4j.RenameParams` (where is an information about renamed element and position in the editor).

**Rename Method**
- [ ] Update References (by default is true)
- [ ] Keep original method as delegate to renamed
- [ ] Mark as deprecated

**Rename Field**
- [ ] Update References (by default is true)
- [ ] Update textual occurrences in comments and strings

**Rename Type**
- [ ] Update References (by default is true)
- [ ] Update textual occurrences in comments and strings
- [ ] Update fully qualified names in non-Java text files (With file name patterns)

**Rename Package** (not inplemented)
- [ ]  Add an ability to make rename for packege
- [ ] Update References (by default is true)
- [ ] Rename subpackages
- [ ] Update textual occurrences in comments and strings
- [ ] Update fully qualified names in non-Java text files (With file name patterns)
