### ISSUE TITLE
WAN port forwarding IP N.N.N.N doesnt work with local LAN virtual host 192.168.2.1:8080 

### ISSUE THREAD

**Issue by unisqu** [eclipse-che/che#9121]
WAN port forwarding IP N.N.N.N doesnt work with local LAN virtual host 192.168.2.1:8080 
When I'm within the LAN with laptop or desktop 192.168.2.100 IP connecting to VM Host 192.168.2.1:8080, it works.

but i did port forwarding router with 192.168.2.1:8080 using external IP and it doesnt load complete. It just keep showing Elipse CHE loading icon. WAN Port is forwarded to LAN IP correctly.

My che env setup is with  -e CHE_HOST=192.168.2.1

What should I do? I've tried -e CHE_HOST=N.N.N.N and docker fails while connecting. (as expected)

Please help. Thanks in advance. I would like that my external port forwarded IP can load Eclipse Che too. Is there other port I need to do port forwarding too? for external IP access be used properly?

**Comment by eivantsov** [comment]
@unisqu you need port 8080 and the ephemeral port range publicly accessible.

What's the output of your docker run when you try it with `CHE_HOST=n.n.n.n`?

Also, you may want to give it a try with `-e DOCKER_IP_EXTERNAL=n.n.n.n`. However, make sure the abovementioned ports aren't filtered.

**Comment by unisqu** [comment]
with or without the -e DOCKER_IP_EXTERNAL=n.n.n.n, it will show

> INFO: (che init):   CHE_VERSION=6.2.0
> INFO: (che init):   CHE_CONFIG=/var/lib/docker/bcz_src/che-multiuser9080
> INFO: (che init):   CHE_INSTANCE=/var/lib/docker/bcz_src/che-multiuser9080/instance
> INFO: (che config): Generating che configuration...
> INFO: (che config): Customizing docker-compose for running in a container
> INFO: (che start): Preflight checks
> WARNING: No swap limit support
>          mem (1.5 GiB):           [OK]
>          disk (100 MB):           [OK]
>          port 9080 (http):        [AVAILABLE]
>          conn (browser => ws):    [NOT OK]
>          conn (server => ws):     [NOT OK]
> 
> 
> ERROR: Try 'docker run <options> eclipse/che info --network' for more tests.

how do i resolve this?

**Comment by eivantsov** [comment]
@unisqu Eclipse Che lets Docker randomly published exposed ports. Che server needs to communicate with ws-agent. In your case, it cannot reach workspace agent, most probably because the ephemeral port range is filtered. You need to make sure this port range is accessible for inbound connections.

**Comment by unisqu** [comment]
What are the port range for this... ws thing? can I just preassign ports for them?

**Comment by unisqu** [comment]
I've done multiple CHE_HOST with n.n.n.n and DOCKER_EXTERNAL_IP but when i connected by WAN using another line (mobile data or another IP address from the outside), it just keeps display "Loading Dashboard" on the browser and stopped with the CHE icon flashing on the browser. Please help and provide the test instruction for external IP connection. I've enabled my firewall to use the LAN ip 192.168.2.1 as DMZ IP. What should I do now?

**Comment by eivantsov** [comment]
@unisqu you cannot pre assign ports.

As to blinking Dashboard icon, it'd be great if you open browser dev console and look for errors there.

By the way, if you go to `$IP:5050` and log in as `admin:admin`, navigate to che real settings, you will see webOrigins. Make sure the URL you are using to access Che is there, otherwise you will get CORS error, which I suspect you're getting now.

**Comment by unisqu** [comment]
@eivantsov You are right. That's wonderful. You have all the answers here that I can't find online.
http://192.168.10.2:5050/auth/js/keycloak.js shows error in Browser Dev Console (which is not supposed to happen) but I can't seem to find the webOrigins area you mentioned in che realm settings.

I'm using the latest eclipse che.

Please help me in this. I really would like to connect to my CHE remotely. It's a fantastic piece of software. Great work by the way. Thanks.

**Comment by eivantsov** [comment]
@unisqu try adding `-e CHE_KEYCLOAK_AUTH__SERVER__URL=http://$IP:5050/auth` to you Docker run syntax where `$IP` is your wan IP.

**Comment by unisqu** [comment]
@eivantsov after adding  -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://$IP:5050/auth , i got Invalid parameter: redirect_uri

    -e CHE_HOST=192.168.10.2
    -e CHE_KEYCLOAK_AUTH__SERVER__URL=http://[MYIPADDRESS]:5050/auth
    -e DOCKER_IP_EXTERNAL=[MYIPADDRESS]

**Comment by eivantsov** [comment]
OK. Now, go to MYIPADDRESS:5050/auth and login as `admin:admin`.  Go to che-public client and add `MYIPADDRESS:8080` as webOrigin and redirectUri.

**Comment by unisqu** [comment]
I finally get to see login and changed password for the "admin". Now I see "Failed to load http://MYIPADDRESS:5050/auth/realms/che/protocol/openid-connect/token: No 'Access-Control-Allow-Origin' header is present on the requested resources. Origin "http://MYIPADDRESS:9080" is therefore not allowed access. I made the port to be 
    -e CHE_PORT=9080

**Comment by unisqu** [comment]
i've restarted my che docker etc and now I dont see any errors on the browser dev console except a flashing CHE icon, doesn't load up at all. Keeps spinning the browser. Will update after spinning is done. It has been a few minutes already.

**Comment by eivantsov** [comment]
After you log in and see access control error, make sure that web origins in keycloak config have your wan IP

**Comment by eivantsov** [comment]
![image](https://user-images.githubusercontent.com/5337267/37670900-20220d22-2c73-11e8-93aa-a2c29485b5f1.png)
You need to add IP that you use to access Che both to redirectUris and webOrigins

**Comment by unisqu** [comment]
On browser dev console, i see failure in:
VM378:164 WebSocket connection to 'ws://[MYIPADDRESS]:9080/api/websocket?

I dont understand this statement
> After you log in and see access control error, make sure that web origins in keycloak config have your wan IP

I've already added IP for both as the screenshot.

**Comment by eivantsov** [comment]
Can you share your keycloak config as a screenshot?

**Comment by unisqu** [comment]
Here it is:
https://s9.postimg.org/gpavyduy7/checonfig.png

I can't do ws:// only I think that's why the CHE icon is there.

Also having the below, but shouldn't be an issue because it will work if I'm using LAN IP setup on chrome browser on macbook air. 

> You are using the ngTouch module. 
> Angular Material already has mobile click, tap, and swipe support... 
> ngTouch is not supported with Angular Material!
> (anonymous) @ vendor-73784b1bca.js:33381
> e @ vendor-73784b1bca.js:75483
> i @ vendor-73784b1bca.js:25384
> (anonymous) @ vendor-73784b1bca.js:25205
> o @ vendor-73784b1bca.js:21201
> et @ vendor-73784b1bca.js:25205
> s @ vendor-73784b1bca.js:22537
> u.test.Pr.resumeBootstrap @ vendor-73784b1bca.js:22566
> (anonymous) @ app-c697ea5815.js:143
> Promise.then (async)
> (anonymous) @ app-c697ea5815.js:142
> c @ vendor-73784b1bca.js:14749
> fireWith @ vendor-73784b1bca.js:14861
> ready @ vendor-73784b1bca.js:15067
> a @ vendor-73784b1bca.js:15083
> 5vendor-73784b1bca.js:33381 Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.

**Comment by eivantsov** [comment]
I am a bit lost now about what works and what doesn't :)

1. You navigate to $WAN_IP:9080
2. You are redirected to login page
3. You log in
4. You see a blinking icon and no exceptions in browser console?

**Comment by unisqu** [comment]
1. I cleared browser cache (everything from the beginning of time) and retried. Initial loads up was very slow with "waiting for available websocket". Then it loads to the login page.
2. I log in but it hangs there as if trying to load something for a long time. waiting for [MYIPADDRESS]
3. I think I'm going to see this error in browser dev console again... normally will need to wait >10 mins to show this failure of: 
VM378:164 WebSocket connection to 'ws://[MYIPADDRESS]:9080/api/websocket?

**Comment by unisqu** [comment]
This is the error 
failed: WebSocket opening handshake timed out

**Comment by eivantsov** [comment]
Do you see your successful login in keycloak logs?

**Comment by unisqu** [comment]
I see the Sessions inside che-public but i'm not sure if it's considered successful login or not...

> Show Sessions
> --
> 
> admin | MYIPADDRESS | Mar 21, 2018 1:05:54 AM
>

**Comment by unisqu** [comment]
Am really looking forward to resolving this part asap this week. Would like to buy a coffee for you too @eivantsov . Do send me the link to the coffee contribution paypal link. Thanks.

**Comment by eivantsov** [comment]
@unisqu it looks like a websocket issue that happens during forwarding. I'd look at some simple websocket test, like starting a container with a server that accepts websocket connections and then trying to connect to it with any client.

**Comment by unisqu** [comment]
for this websocket connection is it using the same port 9080 or 5050 or...? how do i get any error logs from the server? which directory has the error logs / logs file?

**Comment by eivantsov** [comment]
Port 9080. I don't think server logs will say anything as this is not a server problem

**Comment by unisqu** [comment]
can you give me the simplest command line docker run that i can test for this simple startup to make sure it works?

I have a private network LAN 192.168.10.211 for my KVM Virtual Machine, running the docker command and i would like my WAN being used to connect to this KVM VM eclipse che. my WAN is N.N.N.N and I've enabled DMZ to this N.N.N.N

What else I need to do? The port is 9080 instead of default 8080. ( i can try default 8080 no issues ) 

Can you just give me the command to run the most basic one and what needs to be done to make it accessible remotely? Appreciate this.

**Comment by unisqu** [comment]
Any help here? Please help with vanilla che for multi user remote ip n.n.n.n with a lan ip 192.168.10.211

Anyone has gotten it done before? I have no idea why I'm having a lot of problem with this one.

**Comment by eivantsov** [comment]
@unisqu in your case, websocket connection fails. Usually public IP is directly used and it causes no issues.

**Comment by unisqu** [comment]
so what's the remedy?

**Comment by unisqu** [comment]
i've exposed WAN IP and used docker run with port 9080
I'm getting the error below. How do i resolve this? I've managed to log in with admin but when I tried to "Add workspace" it gives the error in browser dev console:

> vendor-73784b1bca.js:75 GET http://n.n.n.n:9080/api/oauth/ 405 (OK)e @ vendor-73784b1bca.js:75v @ vendor-73784b1bca.js:75$get.c @ vendor-73784b1bca.js:75l @ vendor-73784b1bca.js:75(anonymous function) @ vendor-73784b1bca.js:75$get.h.$eval @ vendor-73784b1bca.js:76$get.h.$digest @ vendor-73784b1bca.js:76$get.h.$apply @ vendor-73784b1bca.js:76(anonymous function) @ vendor-73784b1bca.js:74i @ vendor-73784b1bca.js:74s @ vendor-73784b1bca.js:74u.test.Pr.resumeBootstrap @ vendor-73784b1bca.js:74(anonymous function) @ app-c697ea5815.js:143
> vendor-73784b1bca.js:75 TypeError: n.find is not a function

**Comment by eivantsov** [comment]
@unisqu did it happen when you pressed - Create Workspace?

There should be a call to workspace API, switch to network tab in dev console and share a screenshot please

**Comment by unisqu** [comment]
it's working on my laptop now, so I guess it's fine now.
I have limited IPs for CHE use.

so what's the remedy or alternatives I can try/explore?
LAN IP and Remote IP DMZ etc. What other alternatives can I have?

**Comment by unisqu** [comment]
it was not working on Chromium Browser. Seems like browser compatibility needs to be mentioned too.
