### ISSUE TITLE
Do new users have to create another new workspace to share existing workspace?

### ISSUE THREAD

**Issue by unisqu** [eclipse-che/che#9122]
Do new users have to create another new workspace to share existing workspace?
I realised that each new workspace created by a new user will create another docker instance.
Do we really need so many docker instances created per user to edit existing same workspace?

This is kind of like a design flaw to me knowing that each docker container is additional overhead for the system when the workspace env is the same for existing workspace.

**Comment by eivantsov** [comment]
@unisqu when sharing a workspace one shares permissions - it does not mean a new container is started.

**Comment by unisqu** [comment]
Ok, I think my question is thus, how do I limit users by Projects permission/access rights instead?

**Comment by eivantsov** [comment]
@unisqu what exactly do you want to limit?

**Comment by unisqu** [comment]
who can or who can't work on a project. i've "-v /usr/local/src/firstproject:/projects/firstproject;/usr/local/src/secondproject:/projects/secondproject; ..." etc

and there are a lot of projects within the Workspace with [x] mark as folder icon created as Workspace name.

I would like to limit what project each user can work on or see. meaning, given my docker creation of the volumes the way i've mounted, each user should not be able to see / know what project is available. is this possible?

Otherwise, i've tried creating another instance of che to mount host volume with -v /usr/local/src/secondproject:/projects/secondproject but it seems postgres and other ports will conflict and it won't run.

What's a better way for users to only be able to work specific projects etc? Each Workspace i've created will end up with 
/projects/firstproject
/projects/secondproject
/projects/thirdproject

seen by all users with different workspace access.

Also, I've tried been watching 3 hours of youtube and 2 hours research on how to do privileges for multi user and I can't find anything online. The links to keycloak are all down. You can try one yourself here with 404
https://www.eclipse.org/che/docs/user-management/user-management/index.html

Please help. Appreciate this.

**Comment by eivantsov** [comment]
@unisqu i don't think this is a good use of mount-to-all-ws feature. Why do you necessarily need to mount host projects?

What do you try to achieve? Can you share the entire ideal flow? Do you want all new users to have pre-defined projects in their workspaces?

**Comment by eivantsov** [comment]
@unisqu can those projects be hosted as Git projects? You may create a Factory for each project, and each user clickin on it will have a workspace with a project that will be imported into this workspace.

**Comment by unisqu** [comment]
Those projects can't be hosted as Git projects. What's the workaround? for each che workspace, can't limit by projects? I can't create multiple workspaces on the same hosts right? What's a better way to show /project/(differentprojectfordifferentusers) ?

**Comment by eivantsov** [comment]
@unisqu I have replied in a different issue that you have created
