### ISSUE TITLE
mvn clean install failed and the error looks strange

### ISSUE THREAD

**Issue by buaa0110** [eclipse-che/che#9123]
i made some changes in plugin module for some reason
but when i use      
     mvn clean install
to build my code ,it responds like this 
![image](https://user-images.githubusercontent.com/22358515/37565714-11deb124-2ae9-11e8-8d1b-efce678e28e4.png)
and i looked the help up but without useful result

i also tried to use 
     mvn build 
and got same result

hope ur help !
thanks

**Comment by eivantsov** [comment]
@buaa0110 you are using an old snapshot. Please use a tag and it should resolve the problem

**Comment by buaa0110** [comment]
@eivantsov  thank u so much for ur advice  ,it works well!
but here i have a new problem.
maven throws a MISSING LICENSE HEADER exception.
Is this problem due to the old version?
Thank u!
![image](https://user-images.githubusercontent.com/22358515/37630669-d4e4444e-2c20-11e8-8e1e-9e1dd79c9c88.png)

**Comment by buaa0110** [comment]
@eivantsov  thank u very much again!
i fixed the problem by using

       mvn license:format
