### ISSUE TITLE
Getting error to retrieve users from Keycloak: User test.user@domain.com is not registered in the system.

### ISSUE THREAD

**Issue by sedatkestepe** [eclipse-che/che#9127]
I have been evaluating Eclipse Che with no tag specification: latest
I did not have any problems with adding user as organization member until now.
Now on Eclipse Che user management page I cannot add members. 
I have realised that I have evaluated Eclipse with 5.22.1 and 6.1.1 versions. Now with 6.2.0 I get this error. Eclipse Che starter image on the other hand gets another error if i want to use older version. Below outputs are for when i try 6.1.1 as version tag:

WARN: Newer version '6.2.0' available
ERROR:
ERROR: Your CLI version 'eclipse/che:6.1.1' is older than your installed version '6.2.0'.
ERROR:
ERROR: You cannot use an older CLI with a newer installation.
ERROR:
ERROR: Run the CLI with 'eclipse/che:6.2.0' to match the CLI with your existing installed version.

So there is no turn back to older versions as I see.

When I try to add members to organizations I see below lines in localhost-access.log (/var/lib/docker/volumes/che_data/_data/instance/logs/logs/localhost-access.log) :

192.168.2.4 - - [19/Mar/2018:14:40:11 +0000] "GET /api/user/find?email=test.user@domain.com HTTP/1.1" 404 -
192.168.2.4 - - [19/Mar/2018:14:40:11 +0000] "GET /api/permissions/organization/all?instance=organization9fpkbgpw18q8308d HTTP/1.1" 304 -

<img width="627" alt="screen shot 2018-03-19 at 16 47 00" src="https://user-images.githubusercontent.com/6594843/37599191-2a541bde-2b95-11e8-807b-461a896698de.png">

I live similar issue as i navigate to Users page.
In log file below lines were generated as i navigate to users page (<eclipse_che_host>:8080/dashboard/#/admin/usermanagement)

192.168.2.4 - - [15/Mar/2018:15:03:01 +0000] "GET /api/permissions/system HTTP/1.1" 304 -
192.168.2.4 - - [15/Mar/2018:15:03:01 +0000] "GET /api/admin/user?maxItems=12&skipCount=0 HTTP/1.1" 404 -

<img width="647" alt="screen shot 2018-03-19 at 16 08 49" src="https://user-images.githubusercontent.com/6594843/37597226-dab3f89c-2b8f-11e8-9f41-69878d50bfcc.png">

Host: CentOS 7.4.1708

Docker version:
$ docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:15:20 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:17:54 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by eivantsov** [comment]
@sedatkestepe which version is giving you the above error?

**Comment by sedatkestepe** [comment]
@eivantsov Eclipse Che image version 6.2.0 is giving me above error.

**Comment by eivantsov** [comment]
![image pasted at 2018-3-19 15-57](https://user-images.githubusercontent.com/5337267/37600047-e05220d6-2b8e-11e8-9e7a-8cb19505ed25.png)
Confirmed.

**Comment by thangamani-arun** [comment]
any one has fixed this issue ?

**Comment by sleshchenko** [comment]
I doubt no. The described case use deprecated Che CLI. 
@thangamani-arun Do you face the same issue with user/organization on the latest version of Che?

**Comment by thangamani-arun** [comment]
@sleshchenko I think the above scenario is when you do not register the user and try to add them as a member, it throws error stating that user is not registered in the system which is correct. 

when I register the user and then add that user a member, then it works.

**Comment by thangamani-arun** [comment]
@sleshchenko I use Che v5.20.1 and I do not see User Menu, hence can not create a user from the UI. I have to visit the login page and select "new-user Register" option to create a new user.

**Comment by sleshchenko** [comment]
> when I register the user and then add that user a member, then it works.

Ah, OK. Then it's related to https://github.com/eclipse/che/issues/6335
