### ISSUE TITLE
Che docs are outdated

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#9128]
### Description
Che 6 is in master for one and a half months but Che [docs](https://www.eclipse.org/che/docs/) point to old Che 5 docs. Whereas there is a link to new docs it seems not the best choice to put Che 5 docs on the main page because of both Che CLI and Che master branch in the repo point to Che 6.
![image](https://user-images.githubusercontent.com/1851863/37597279-a6b719be-2b87-11e8-8e40-0a63f1da1964.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@eivantsov @slemeur WDYT?

**Comment by gorkem** [comment]
I do not think we need to wait for the redirection setup for the old docs anymore. This is now hurting us more than some links ending up to 404s

**Comment by gorkem** [comment]
@slemeur @eivantsov Is there anything that is preventing us from making this change?

**Comment by sleshchenko** [comment]
@garagatyi Can we close it since [Che docs](https://www.eclipse.org/che/docs/) points to Che 6 documentation?
