### ISSUE TITLE
Support identity providers besides Keycloak

### ISSUE THREAD

**Issue by mlbiam** [eclipse-che/che#9134]
### Description
According to the documentation, Keycloak is required in order to support external authentication.  If someone already has an identity provider in place that supports openid connect this is requires additional configuration, supporting a database and another system to manage and configured.  Since OpenID Connect is a standard, can che simply support the standard (as OpenShift does) OpenID Connect?

### Reproduction Steps
Documented here - https://www.eclipse.org/che/docs/6/che/docs/user-management.html  

**Diagnostics:** 
N/A

**Comment by eivantsov** [comment]
@mlbiam you can still use KeyCloak and add your OpenID provider.

You may also be interested in this PR https://github.com/eclipse/che-docs/pull/375

**Comment by mlbiam** [comment]
Thanks @eivantsov.  Yes, I could, but that means extra databases, extra servers, an extra identity silo that has to be managed and protected.  Better to just use existing infrastructure.

Looking at the PR, it appears to just be a documentation update?  So this should work with the current version of eclipse che?

**Comment by eivantsov** [comment]
That's documentation update based on PR to Che itself

**Comment by eivantsov** [comment]
Closing the issue. Feel free to reopen if you faced issues with using OpenID system
