### ISSUE TITLE
Build che-ide-gwt-app-6.2.0 will not work properly on Windows

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#9136]
### Description

I tried to build a slightly modified che-ide-gwt-app-6.2.0 on windows 10 and the IDE didn't load.

I'm actually not sure if you support building on Windows at all. We do it a lot here, since the corporate infrastructure is windows. If you don't support that just comment, we will adopt. 
### Reproduction

- get the 6.2.0 che sources on windows.
- build che-ide-gwt-app-.6.2.0
- build the che-ide-assembly
- build the assembly-main
-> try to run che with this custom assembly.

When starting a workspace the initial progress bar will not proceed and the application will just stop at that.

### Analysis:

The root cause seems to be the compilation-mappings.properties file.
This is created in che-ide-gwt-app with a antrun by using "length+echo" to create a file with the full path of the *.js files + their length and then using "replace" to replace the full path with the name of .js:

    <replace file="${project.build.directory}/${project.artifactId}-${project.version}/_app/compilation-mappings.properties" token="${project.build.directory}/${project.artifactId}-${project.version}/_app/" value="" />

Unfortunately the above statement will not work on windows which leads to the start-up problems. I simply added a second line in the pom.xml locally now and this works:

    <replace file="${project.build.directory}/${project.artifactId}-${project.version}/_app/compilation-mappings.properties" token="${project.build.directory}\${project.artifactId}-${project.version}\_app\" value="" />

(Better would be to use a regex replace)

**Comment by eivantsov** [comment]
@ChristianSchenk711 thanks for reporting it. Che docs and dev wiki suggest using Docker to build Che.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/15)

**Comment by gorkem** [comment]
Closing as Che 6 editor is no longer under active development
