### ISSUE TITLE
A workspace item in an organization workspaces list is not clickable

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#9148]
**Reproduction Steps:**

1. Create an organization.
2. Add a workspace to this organization.
3. Open the **Workspace** tab in organization details page.
4. Click on the workspace name in list to open its workspace details.

**Expected result:** workspace details page is opened.

**Actual result:** workspace item in list is not clickable.

**OS and version:**
Che 6.3.0-SNAPSHOT; Chrome 63.0; Fedora 25

**Failed test**: AddWorkspaceToOrganizationTest

**Additional information:**
![selection_218](https://user-images.githubusercontent.com/7760565/37658774-f6e44dd8-2c56-11e8-9e52-56613f8c873f.png)

![nimbus-record-video-2018-03-20-15-41-10](https://user-images.githubusercontent.com/7760565/37658523-673e6f2e-2c56-11e8-958e-51dafee11956.gif)

**Comment by vkuznyetsov** [comment]
Still actual in Version: 6.10.0
