### ISSUE TITLE
Improve and rework the 'ImportRecursiveSubmoduleTest' for ability to launching in multi-threaded mod

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#9150]
### Description
* Need to rework the exist selenium test _ImportRecursiveSubmoduleTest_ for launching in the multi-thread mode
* Need to improve the exist selenium test _ImportRecursiveSubmoduleTest_ related to removing extra steps (add to index, commit, push, etc.)
* Use the _kohsuke Github_ library(if it is needed) for performing operations that are not the main goal of the test
* Related to the #8153

**Comment by Ohrimenko1988** [comment]
Done https://github.com/eclipse/che/pull/9372
