### ISSUE TITLE
Confusing error messages on failed git push

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#9154]
### Description
I have a workspace that does not have any SSH or OAuth has been set up. When I do a git commit and select to do push as expected it fails, however the messages are confusing. See the image below for the specific confusions.

![image](https://user-images.githubusercontent.com/82738/37683199-2a8cd92e-2c62-11e8-937a-f52e500203c4.png)

**Comment by vinokurig** [comment]
@gorkem I've changed the message to: `May be the authorization failed because you have not setup SSH keys or OAuth.` (see the PR). I couldn't reproduce the successful message after push failed error. Cold you please check if this issue is actual with your repository?
