### ISSUE TITLE
MongoDB installation

### ISSUE THREAD

**Issue by Sammirzad** [eclipse-che/che#9175]
Hi

I'd like to know how to install MongoDB on my workspace on Codenvey so i can use mongo shell and later use database on my application. my application is written on NodeJS - Express

Thanks

**Comment by eivantsov** [comment]
@Sammirzad you need to create a Dockerfile https://www.eclipse.org/che/docs/6/che/docs/recipes.html#dockerfile

There are lots of examples on how to install Mongo in a Dockerfile

**Comment by Senior-Oz** [comment]
Hi @eivantsov I would like to know where to find those Dockerfile examples for MongoDB Installation. I have searching for an example and I couldn't find nothing yet. I would appreciate your help. Thank you.

**Comment by eivantsov** [comment]
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

Just move that to RUN instructions of a Dockerfile
