### ISSUE TITLE
Deploying multi-user CHE on Linux server not functioning properly.

### ISSUE THREAD

**Issue by unnatch** [eclipse-che/che#9176]
### Description
So, I have been trying to deploy Che with a multi-user setup on a Linux Server so that it is publicly accessible to the users from any browser.

### Reproduction Steps
This was my command on the Command Line: 

docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=203.142.91.82 -v /var/run/docker.sock:/var/run/docker.sock -v ~/che-multiuser:/data eclipse/che start

When I received this error: 
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]

I changed the che.env to in che-multiuser/ to:

DOCKER_HOST=203.142.91.82
CHE_DOCKER_IP=172.17.0.1
CHE_DOCKER_IP_EXTERNAL=203.142.91.82

203.142.91.82 (Public IP)
192.168.0.2 (Internal IP)
172.17.0.1(Docker IP)

Also, when I try to run Che on my internal IP with multi-user setup, it runs and functions fully and properly. It does not run when I change the Che_Host to public IP

**OS and version:**    
Linux my_comp 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Diagnostics:** 

DOCKER IP: 172.17.0.1
* when I run -
INFO: (che init): Installing configuration and bootstrap variables:
INFO: (che init):   CHE_HOST=203.142.91.82
INFO: (che init):   CHE_VERSION=6.1.1
INFO: (che init):   CHE_CONFIG=/home/sample/che-multiuser
INFO: (che init):   CHE_INSTANCE=/home/sample/che-multiuser/instance
INFO: (che config): Generating che configuration...
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
WARNING: No swap limit support
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 8080 (http):        [AVAILABLE]
         conn (browser => ws):    [NOT OK]
         conn (server => ws):     [NOT OK]

*with network --info

WARN: Bound 'eclipse/che' to 'eclipse/che:6.1.1'
WARNING: No swap limit support
INFO: (che cli): 6.1.1 - using docker 17.05.0-ce / native
WARN: Newer version '6.2.0' available
INFO: 
INFO: ---------------------------------------
INFO: --------   CONNECTIVITY TEST   --------
INFO: ---------------------------------------
INFO: (che network): eclipse/che-ip:6.1.1: 203.142.91.82
INFO: (che network): Browser => Workspace Agent (localhost): Connection failed
INFO: (che network): Browser => Workspace Agent (203.142.91.82): Connection failed
INFO: (che network): Server  => Workspace Agent (External IP): Connection failed
INFO: (che network): Server  => Workspace Agent (Internal IP): Connection succeeded

**Comment by eivantsov** [comment]
@unnatch did you open 5050 and the ephemeral port range?

**Comment by unnatch** [comment]
I do not use a firewall so I am assuming that none of the ports are closed.

**Comment by unnatch** [comment]
I have enabled firewall and opened the ports as mentioned. 

The command $ufw status gives this output:
Status: active

Status: active

To                         Action      From
--                         ------      ----
8000                       ALLOW       Anywhere                  
32791                      ALLOW       Anywhere                  
80                         ALLOW       Anywhere                  
22                         ALLOW       Anywhere                  
32768                      ALLOW       Anywhere                  
12030                      ALLOW       Anywhere                  
32768:65535/tcp            ALLOW       Anywhere                  
5050                       ALLOW       Anywhere                  
8080                       ALLOW       Anywhere                  
8000 (v6)                  ALLOW       Anywhere (v6)             
32791 (v6)                 ALLOW       Anywhere (v6)             
80 (v6)                    ALLOW       Anywhere (v6)             
22 (v6)                    ALLOW       Anywhere (v6)             
32768 (v6)                 ALLOW       Anywhere (v6)             
12030 (v6)                 ALLOW       Anywhere (v6)             
32768:65535/tcp (v6)       ALLOW       Anywhere (v6)             
5050 (v6)                  ALLOW       Anywhere (v6)             
8080 (v6)                  ALLOW       Anywhere (v6)

**Comment by eivantsov** [comment]
@unnatch well, smth is blocking the ephemeral port range.

Here's a simple test:

```
docker run -d -p 32987:80 nginx
docker run -ti appropriate/curl
curl -v http://203.142.91.82:32987
```

Does curl return 200?
