### ISSUE TITLE
Create support bundle mechanism for Che on OpenShift

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#9179]
### Description
Diagnosing issues with user installs of che on OpenShift would be much easier if there was a command that could be run on the OpenShift cluster to gather all the relevant kinds and environment variables for Che and zip those up.

**Comment by bmicklea** [comment]
@eivantsov is this possible?

**Comment by eivantsov** [comment]
It is possible, yes.

**Comment by bmicklea** [comment]
Which team's backlog does it go in?
