### ISSUE TITLE
Creating and Starting eclipse che workspaces from backend or CLI

### ISSUE THREAD

**Issue by sanjaysingatalur** [eclipse-che/che#9194]
I have installed latest Eclipse/che onto my machine and integrated it with github as well.
Also i am able to created workspace using IDE.But i need to know if workspaces can be created using cli.Also i came to know that there are REST API's available using which i can create workspaces.
Can anyone let me know the procedure to create workspaces from backend either by CLI or API .
Thanks.

kind/question

**Comment by sanjaysingatalur** [comment]
I have installed latest Eclipse/che onto my machine and integrated it with github as well.
Also i am able to created workspace using IDE.But i need to know if workspaces can be created using cli.Also i came to know that there are REST API's available using which i can create workspaces.
Can anyone let me know the procedure to create workspaces from backend either by CLI or API .
Thanks.

**Comment by skabashnyuk** [comment]
All CLI command are listed here https://www.eclipse.org/che/docs/6/che/docs/docker-cli.html AFAIK there is no create workspace command.
About rest api you can read here https://www.eclipse.org/che/docs/6/che/docs/rest-api.html

**Comment by sanjaysingatalur** [comment]
@skabasjnyuk   Thanks for the Info..
Like I need to know more about how to use these API's,I understand there is a link to github in the above doc which you have provided in which the .java code for the same exist.
As i am bit new to this, please help in understanding below queries.

From where these API's can be called ? should i be inside the container or any other server?
What are the requirements ?
Currently i have worspaces runing fine and also i am running 3 containers keycloak,che and postgres.
From i can make API's to talk to my workspaces.

Thanks

**Comment by eivantsov** [comment]
@sanjaysingatalur you can call Che APIs using any client you want. It can be a bash script, or a go binary or anything that can call a remote API.
