### ISSUE TITLE
Allowed characters of the name of volume

### ISSUE THREAD

**Issue by ahshum** [eclipse-che/che#9198]
Would it be possible to allow some characters like `_`, `-` as well as uppercase letters, for the favor of creating a namespace liked volume name?

![image](https://user-images.githubusercontent.com/4080806/37809181-41a0d7d2-2e0b-11e8-99ff-88be5545995c.png)

**OS and version:**    CHE 6.2.0

**Comment by eivantsov** [comment]
@aHxShUM not in UI. You can add a volume with allowed characters, then go to config tab and edit it in json. However, Docker or Kubernetes (depending on what infra you use) may not be happy with a particular volume name.

**Comment by aHxShUM** [comment]
@eivantsov Sure. I did try to edit the name of volume in this way but the same message is showing up.

My config :
![image](https://user-images.githubusercontent.com/4080806/37828297-a66e2eec-2ed5-11e8-8331-a06076736f27.png)

The message after I clicked on `Save` :
![image](https://user-images.githubusercontent.com/4080806/37828310-b388d744-2ed5-11e8-8cb3-3101ff56ac4f.png)

**Comment by eivantsov** [comment]
@aHxShUM try using any REST client. Copy ws config as json, edit your volume.

`${CHE_HOST}:${CHE_PORT}/swagger/#!/workspace/getByKey'
Enter composite key `che:php`. You will get a json in response. Find id field.

Go to `${CHE_HOST}:${CHE_PORT}/swagger/#!/workspace/update`
Enter ID and paste edited json and execute

**Comment by eivantsov** [comment]
Closing as Che respects Kubernetes regexp for object names
