### ISSUE TITLE
Add an ability to use distributed cache for storing workspace statuses in WorkspaceRuntimes

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#9206]
### Description
For using Rolling Update strategy for updating of the Che Server it is needed to use distributed cache for storing workspace statuses in WorkspaceRuntimes.

A distributed cache will be used for sharing information (the another Che Server should know about actual Workspace Status) and operation synchronizations(like it should be forbidden to start a workspace on a Che Server instance if the same operation is in progress on another Che Server instance).

It may be needed to have a listener to perform the same operation after workspace status update, like 
 Cancels workspace servers probes https://github.com/eclipse/che/blob/d8d24aece6f46ff5bfad428feddaa8f98684018c/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java#L278.
It should be investigated more, and maybe Infrastructure should implement it but not Workspace API.

Because of performance reasons, it may make sense to configure distributed or in-memory cache if Infrastructure doesn't support existing more than one Che Server at the same time.

More info about OpenShift Recovery and Rolling update can be found [here](https://github.com/eclipse/che/issues/5919#issuecomment-374883339).

**Comment by akorneta** [comment]
This issue will be merged as part of PR: https://github.com/eclipse/che/pull/9439. If there any problem with implementation an appropriate fixes will be added as part of https://github.com/eclipse/che/issues/9415
