### ISSUE TITLE
Define plugin's metadata and it's storage

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9210]
Plugin's metadata is analyzed by some kind of scanners that can be plugged. Plugin’s metadata is available both for/from frontend and backend extension manager parts.

**Comment by ashumilova** [comment]
Define fields that should be taken from the package.json. 
Store paths to package.json (notion of plugins FQN - publisher, market id, plugin name and version).
Have dedicated folder with all the plugins metadata.
Document the metadata properly.

**Comment by ashumilova** [comment]
the work on this issue is related to branch https://github.com/theia-ide/theia/tree/isolated-extension-api

**Comment by ashumilova** [comment]
define metadata -> document the metadata -> extract the metadata -> provide metadata to interested parts

**Comment by akurinnoy** [comment]
https://github.com/theia-demo-plugins/wiptheia/commit/e05c66dea7ae59df2cb8e5d000c41691c0ffe178
