### ISSUE TITLE
Refresh frontend/backend plugin parts on plugin disabled state

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9211]
Provide a way to refresh the whole frontend/backend plugin parts if a plugin is disabled and user want to be sure it’s cleanly removed.

**Comment by slemeur** [comment]
What options are you considering? 

What is the purpose, for the end user to ensure that it has been cleanly removed? 
When the user is disabling a plugin, he is naturally expecting that the plugin will be removed cleanly. We should consider displaying a status of the plugin and when it is disabled, display an update to the user via a notification.
