### ISSUE TITLE
Add UI to differ developer mode in Theia

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9214]
Hosted(developer) mode will have a dedicated UI for user to differ it from the main one. Here need to define what should be shown on UI as a marker.

**Comment by slemeur** [comment]
What about displaying an horizontal message bar (in green) above the menu bar, with the message: "Hosted Mode IDE:{pluginName}"? Have you considered adding specific actions?

**Comment by slemeur** [comment]
Revised requirement.

From @vitaliy-guliy :
![screenshot from 2018-04-23 11-57-53](https://user-images.githubusercontent.com/1636769/39421533-c8211f02-4c69-11e8-8f65-b614d7c059ee.jpg)

We also need to display in the browser title: "Developement Host - workspace"
