### ISSUE TITLE
Plugin API definition and implementation

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9215]
This is the umbrella issue to define all plugin APIs that should be implemented and exposed for the plugin developers.

- [x] Command Manager API https://github.com/eclipse/che/issues/9283
- [x] Notification API https://github.com/eclipse/che/issues/9284
- [ ] Menu API https://github.com/eclipse/che/issues/9285
- [x] Command palette https://github.com/eclipse/che/issues/9286
- [ ] File API
- [x] Editor API https://github.com/eclipse/che/issues/9409
- [ ] Widget API

**Comment by slemeur** [comment]
Consider the API documentations as part of the definition of done for this issue.
