### ISSUE TITLE
How to change port for 5050?

### ISSUE THREAD

**Issue by unisqu** [eclipse-che/che#9223]
How to change port for 5050? CHE_PORT=8080 can be changed but what's the variable to change for port 5050?

Possible to have multiple che instances hosted on the same host? Seems like had conflict with the postgres database and keycloak docker. If it's not possible, it's ok so long as I can change port 5050 above will do.

**Comment by eivantsov** [comment]
@unisqu running multiple Che installations on one host isn't recommended. You can avoid conflicts though by manually editing `$local_dir/instance/docker-compose-container.yml`. Re run Che with `--skip:config` flag. 

However, you may run into issues when Che server checks for abandoned containers. Two servers may kill one another's workspaces. 

Out of curiosity, why do you need two multi user Che installations on one host?

**Comment by unisqu** [comment]
I'll re-read the recommended workspace environment setup and revert. Basically, I would like to limit Projects access per user. There are different Workspaces for different development teams. It's good to be able to limit the access based on their user privileges set especially for actual development vs beta test roll etc. I know I can do branch commit but there are sensitive part of the code whereby I would prefer to have them on a different Workspace. Currently my only concern is /projects/* seems to be accessible by all Users. That doesn't make sense to me.

**Comment by eivantsov** [comment]
Well, it is accessible because you mount them. Use of a git hosting provider will solve it for you

**Comment by unisqu** [comment]
other than github (public hosting), what is eclipse che recommended (or supported) private self hosting git software? gitlab...??
