### ISSUE TITLE
WAN n.n.n.n, LAN 192.168.9.211, not working with remote ip

### ISSUE THREAD

**Issue by unisqu** [eclipse-che/che#9225]
@eivantsov , I thought I resolved the problem but i realised that there is some settings I need to set additional for this to work I've done, under Keycloak -> Clients -> Valid Redirect URIs : http://n.n.n.n:8080/*

Web Origins : http://n.n.n.n:8080

I realised it works if i'm connected using the same LAN IP but once I tried to connect it using another external network, the flashing CHE icon will appear in 8080. It will work for 5050 settings.

e.g. LAN PC -> REMOTE IP CHE 8080 (same LAN network) = works
ANOTHER EXTERNAL IP PC -> REMOTE IP CHE 8080 (different LAN Network) = not working (che icon flashing)

-e CHE_HOST=192.168.9.211
-e DOCKER_IP_EXTERNAL=n.n.n.n

on router,
DMZ = 192.168.9.211

I must have missed setting something since it's trying to call the LAN IP of 192.168.9.211 ... what could it be? Anyone have any ideas?

**Comment by eivantsov** [comment]
@unisqu what's the error in browser dev console? ws connection failure? failure to load Keycloak script?

**Comment by unisqu** [comment]
browser dev console : 

> Get 192.168.9.211:5050/auth/js/keycloak.js net::ERR_CONNECTION_TIMED_OUT
> Keycloak initialization failed with error: Error loading script.

That's the problem! How do I resolve this? All I need to do is make it get n.n.n.n keycloak javascript.

**Comment by eivantsov** [comment]
@unisqu add `-e CHE_KEYCLOAK_AUTH__SERVER__URL=$EXTERNAl_IP:5050/auth` to your Docker run syntax.

You may also give it a try with `-e CHE_HOST=$EXTERNAL_IP`, the CLI constructs `CHE_KEYCLOAK_AUTH__SERVER__URL` based on `CHE_HOST` value.

**Comment by unisqu** [comment]
with the above suggested, my browser dev console writes: 
> app-c697ea5815.js:141 Keycloak initialization failed with error:  Error loading script.

thereafter i see a lot of 403s msg:

> GET http://n.n.n.n:9080/api/ 403 ()
> (anonymous) @ vendor-73784b1bca.js:31626
> v @ vendor-73784b1bca.js:31419
> c @ vendor-73784b1bca.js:31129
> l @ vendor-73784b1bca.js:35653
> (anonymous) @ vendor-73784b1bca.js:35669
> $eval @ vendor-73784b1bca.js:36913
> $digest @ vendor-73784b1bca.js:36731
> $apply @ vendor-73784b1bca.js:37021
> (anonymous) @ vendor-73784b1bca.js:22540
> i @ vendor-73784b1bca.js:25384
> s @ vendor-73784b1bca.js:22538
> u.test.Pr.resumeBootstrap @ vendor-73784b1bca.js:22566
> (anonymous) @ app-c697ea5815.js:143
> Promise.then (async)
> (anonymous) @ app-c697ea5815.js:142
> c @ vendor-73784b1bca.js:14749
> fireWith @ vendor-73784b1bca.js:14861
> ready @ vendor-73784b1bca.js:15067
> a @ vendor-73784b1bca.js:15083
> vendor-73784b1bca.js:31626 OPTIONS http://n.n.n.n:9080/api/ 403 ()
> (anonymous) @ vendor-73784b1bca.js:31626
> v @ vendor-73784b1bca.js:31419
> c @ vendor-73784b1bca.js:31129
> l @ vendor-73784b1bca.js:35653
> (anonymous) @ vendor-73784b1bca.js:35669
> $eval @ vendor-73784b1bca.js:36913
> $digest @ vendor-73784b1bca.js:36731
> $apply @ vendor-73784b1bca.js:37021
> (anonymous) @ vendor-73784b1bca.js:22540
> i @ vendor-73784b1bca.js:25384
> s @ vendor-73784b1bca.js:22538
> u.test.Pr.resumeBootstrap @ vendor-73784b1bca.js:22566
> (anonymous) @ app-c697ea5815.js:143
> Promise.then (async)
> (anonymous) @ app-c697ea5815.js:142
> c @ vendor-73784b1bca.js:14749
> fireWith @ vendor-73784b1bca.js:14861
> ready @ vendor-73784b1bca.js:15067
> a @ vendor-73784b1bca.js:15083
> vendor-73784b1bca.js:31626 GET http://n.n.n.n:9080/api/workspace/settings 403 ()

i've been trying to get the remote ip up for the past few days. I know directly exposing external IP will work 100% no issues but I need to set up 3 different eclipse che for other projects and I don't have so many static ips to go around. Hope to resolve this asap. I'll be back again in 12 hours. Appreciate all further suggestions. Thanks.

**Comment by eivantsov** [comment]
403s are consequences of Keycloak script loading failure. 

Why did it fail to load? There should be a reason like connection refused or smth like that.

**Comment by unisqu** [comment]
i tried all combinations possible, and even did load the keycloak.js file manually. loading manually  works just have no idea why it fails.

https://s9.postimg.org/mfv3c4w5b/Screen_Shot_2018-03-24_at_11.50.34_AM.png

on router,
DMZ = 192.168.9.211

-e CHE_HOST=n.n.n.n
-e DOCKER_IP_EXTERNAL=n.n.n.n
-e CHE_KEYCLOAK_AUTH__SERVER__URL=n.n.n.n:5050/auth

I've been using docker for 3 years (normally with the standard default apt-get install version) and I'm quite expert with networking ip address setup etc (knowing how to do NAT, advanced proxies setup and firewall settings)

I have no idea why it doesnt load. I've tried DMZ 192.168.9.211 already. 

**What works**
Externally exposing and using the docker CHE = N.N.N.N ip as WAN IP will definitely work perfectly. 

**What doesn't work**
LAN IP 192.168.9.N exposed through WAN's DMZ on router.

Can anyone test what I mean?

Again, these are my settings

> on router,
> DMZ = 192.168.9.211
> 
> -e CHE_HOST=n.n.n.n
> -e DOCKER_IP_EXTERNAL=n.n.n.n
> -e CHE_KEYCLOAK_AUTH__SERVER__URL=n.n.n.n:5050/auth
> 

Failed at
https://s9.postimg.org/mfv3c4w5b/Screen_Shot_2018-03-24_at_11.50.34_AM.png

**Comment by eivantsov** [comment]
What is the error itself? Connection refused, same origin or any other error?

**Comment by unisqu** [comment]
all errors are shown here
https://s9.postimg.org/mfv3c4w5b/Screen_Shot_2018-03-24_at_11.50.34_AM.png

the browser doesn't load anything when going to http://n.n.n.n:9080/

thereafter a lot of 403s. Manually downloading http://n.n.n.n/......keycloak.js works even when error says in the attached image above.

**Comment by eivantsov** [comment]
Don't you have smth like this? I mean a reason why Keycloak initialization failed?

![image](https://user-images.githubusercontent.com/5337267/37860437-72ba27a6-2f2d-11e8-8fe9-35c1627baf9c.png)

**Comment by unisqu** [comment]
I dont have that. let me check and get back to you but what's your docker run configuration command line?

**Comment by eivantsov** [comment]
To come to the situation when Keycloak is unavailable I just started Keycloak container on a different port. 

Can you capture requests like I did it below?

![peek 2018-03-24 07-50](https://user-images.githubusercontent.com/5337267/37860932-45e42e74-2f38-11e8-982e-278d2873e510.gif)

**Comment by unisqu** [comment]
can you give me the same docker run command you did? i'll do the same and test on my end.

**Comment by eivantsov** [comment]
Peek

As to command, what exact command do you need? I used the default one to start Che multiuer, just provided the wrong `CHE_KEYCLOAK_AUTH__SERVER__URL`. That's it

**Comment by unisqu** [comment]
I finally got it all working with the default Che multiuser and deleted my chemultiuser directory. All additional che environment variables are not needed. Thanks. It's working now. Appreciate all the help given for the past few days. Will buy a drink if there's paypal link.
