### ISSUE TITLE
Error with chedir creation

### ISSUE THREAD

**Issue by unisqu** [eclipse-che/che#9232]
I'm not sure what chedir does but i'm having these problems with this creation
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /che-multiuser:/data -v /chedir:/chedir eclipse/che:6.2.0 dir up

> WARNING: No swap limit support
> . exit code was 1
> ERROR: (che dir): Startup traces were on stdout:
>  WARN: Did not detect TTY - interactive mode disabled
> INFO: (che cli): 6.2.0 - using docker 17.12.1-ce / native
> INFO: (che start): Booted and reachable
> INFO: (che start): Ver: <not-configed>
> INFO: (che start): Use: http://1{CHE_PRODUCT_NAME}_HOST:8080
> INFO: (che start): API: http://1{CHE_PRODUCT_NAME}_HOST:8080/swagger
> 
> ERROR: (che dir): Startup traces were on stderr:
>  WARNING: No swap limit support
> 
> ERROR: (che dir): process has exited

what's the problem? it's che:6.2.0 (definitely) the /che-multiuser:/data is the same as the original docker server run, /chedir:/chedir is totally new though... what's chedir and how do I resolve this?

**Comment by eivantsov** [comment]
@unisqu Chedir command will start a single user Che for you. In your case, you already have a running Che server, maybe even more than one.

**Comment by eivantsov** [comment]
@unisqu as I have previously said, mounting host dir with projects into all workspaces is definitely a misuse of this feature. It was introduced to mount some files and directories that are common for all workspaces, say, a sample db, Docker socket (to enable use of host Docker daemon in workspaces), configuration files for some services etc.

Eclipse Che relies on Git. Yes, you can create Factories, but project sources need to be hosted on Git, then the IDE will clone them.

**Comment by unisqu** [comment]
Ok thanks.
