### ISSUE TITLE
Diagnostics broken

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9234]
Two issues:

1. Connections are made at `ws://${CHE_HOST}:${CHE_PORT}/api/ws?token=${TOKEN}`

Dashboard itself connects at `/api/websocket`.

2. Even having fixed the endpoint, it looks like ping pong mechanism does not work. A successful connection is made but the UI displays an error.

![image](https://user-images.githubusercontent.com/5337267/37890916-fdbaedb4-30da-11e8-8fd9-c0648bd01643.png)

**Comment by SkorikSergey** [comment]
Still actual for CHE ver.  6.5.0.

**Comment by SkorikSergey** [comment]
There is an error in CHE multiuser:
![eclipse che diagnostic - google chrome_007](https://user-images.githubusercontent.com/7760565/40232827-1068ea9a-5aa9-11e8-911c-db9f9ad27e9b.png)

**Comment by eivantsov** [comment]
For OCP it fails with a clear reason - `{"message":"Infrastructure not found for type: dockerfile"}` There's a Dockerfile used there - we need to use Docker image.

On Docker, shouldn't it use machine token?
