### ISSUE TITLE
CHE tomcat should not fail if KC is not accessible on starting

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#9235]
with changes introduced by this PR https://github.com/eclipse/che/pull/8650
we have a regression that CHE server may completely fail during start-up if it will fail to connect to KC.
we added few workarounds which managed the right sequence of launching services but it will not cover a use case for instance with OSIO when we will need to restart CHE server and due to some reason it will not be able to connect to KC server on startup due to network issues or some other things.
I see two potential ways of solving that:
- refactor code and add an ability to retry to connect to the KC
- move everything that CHE is retrieving from KC to the configuration, and configure it before CHE start.

I prefer the first one because less to configure - easier to deploy / maintain

**Comment by skabashnyuk** [comment]
is this issue up to date?

**Comment by riuvshin** [comment]
yes, I think the problem is still there.
