### ISSUE TITLE
Update loading steps language

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#924]
Update loading steps language for project creation and open workspace flows to be the same as for loading factory.

**Comment by ddementieva** [comment]
(Comment by Jenkins CI server)

SUCCESS: Integrated in ![](http://ci.codenvy-dev.com/jenkins/images/16x16/blue.png) [che-ci-master #757](http://ci.codenvy-dev.com/jenkins/job/che-ci-master/757/)  
CHE-904: update loading steps language (ashumilova@codenvy.com: [adc54daf98e99e464f7b7b7276cc6315be5f7aec](https://github.com/eclipse/che/commit/adc54daf98e99e464f7b7b7276cc6315be5f7aec))
- dashboard/src/app/projects/create-project/create-project.service.js
- dashboard/src/app/ide/ide.service.js
