### ISSUE TITLE
Spring Boot and Vert.x: Debugger does not list frames and variables

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9243]
1. Create a Java Workspace
2. Import https://github.com/snowdrop/spring-boot-http-booster
3. Build command: `export MAVEN_OPTS="-Xmx1G"; mvn clean install -f ${current.project.path}`
4. Debug command: 
```
cd ${current.project.path}
mvn spring-boot:run -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
```
Preview URL: `${server.tomcat8}`

5. Attach a debugger to port 5005
6. Set breakpoint `GreetingEndpoint.java` line 40
6. Interact with the app

![image](https://user-images.githubusercontent.com/5337267/37906453-d0520be8-310a-11e8-96ed-84641ba5cdcc.png)

It is possible though to evaluate expression, and actually get user provided value.

Same behavior with Vert.x stack and sample app

![image](https://user-images.githubusercontent.com/5337267/42278653-35fa026a-7fa4-11e8-8038-6f5f0d4ecb4c.png)

For example, debugging the same project with IntelliJ results in:

![image](https://user-images.githubusercontent.com/5337267/37906595-55be48f0-310b-11e8-9e1f-365a7c4e0198.png)

**Comment by slemeur** [comment]
@tsmaeder + @tolusha : Could you please prioritize this bug for next sprint?

**Comment by eivantsov** [comment]
@tsmaeder 

1. I have no idea. Never debugged spring boot or vertx. 
2. Other Java apps are fine.
3. Yes, it does. You can evaluate expression as well.
4. Yes, it is master

**Comment by tolusha** [comment]
![screenshot from 2018-07-19 13-23-29](https://user-images.githubusercontent.com/1640675/42937218-08bd9bb8-8b57-11e8-8d2c-3a0d77482023.png)

**Comment by tolusha** [comment]
ThreadDump appears despite the stacktrace. 
This is a performance issue and might be related to https://github.com/eclipse/che/issues/7156

**Comment by eivantsov** [comment]
@tolusha are you checking on Docker? It never worked for me on OpenShift.
