### ISSUE TITLE
Springboot stack: http booster sample app fails to compile

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9246]
Steps to reproduce:

1. Create a workspace from Spring Boot stack
2. Import a project https://github.com/snowdrop/spring-boot-http-booster
3. Run build command

Build fails because artifacts are missing at https://github.com/eclipse/che-dockerfiles/blob/master/recipes/centos_jdk8/contrib/settings.xml#L31 

This particular custom stack overrides the default Maven central repo. Works ok in other stacks though

UPD. Looks like a local maven repo isn't writable

**Comment by eivantsov** [comment]
Fixed by https://github.com/eclipse/che-dockerfiles/pull/174
