### ISSUE TITLE
Finalize Theia terminal stuff by adding missing features

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9265]
- [x] Terminal restore:  re-connection to the previous opened session (on browser refresh) 
- [x] Run terminal server in separate Che container (per workspace or per che installation)
- [ ] kill exec ?
- [x] implement ping-pong handler on the server side and client side

**Comment by AndrienkoAleksandr** [comment]
Pull request: https://github.com/eclipse/che-theia-terminal-plugin/pull/1#issuecomment-384539800

**Comment by AndrienkoAleksandr** [comment]
Under CQ.

**Comment by AndrienkoAleksandr** [comment]
Pull request merged. Close issue.
