### ISSUE TITLE
Unable to launch Eclipse-che on openshift...

### ISSUE THREAD

**Issue by LahariGuntha** [eclipse-che/che#9266]
Hi,

I am tryiing to launch Eclipse-che on openshift...

I am following the below document : 
https://www.eclipse.org/che/docs/6/che/docs/openshift-multi-user.html

git clone https://github.com/eclipse/che
cd che/dockerfiles/init/modules/openshift/files/scripts

when executing cd command...
It is throwing error like:
 cd che/dockerfiles/init/modules/openshift/files/scripts

cd: che/dockerfiles/init/modules/openshift/files/scripts: No such file or directory

openshift directory under modules directory is missing...

Can you please update the docs regarding how to deploy che on openshift??

**Comment by garagatyi** [comment]
@LahariGuntha try path `che/deploy/openshift/`
@eivantsov looks like docs haven't been updated since my PR

**Comment by eivantsov** [comment]
@LahariGuntha https://github.com/eclipse/che-docs/tree/master/src/main/pages/setup-openshift

Docs site will be updated soon

**Comment by LahariGuntha** [comment]
Thank you for the Information.
