### ISSUE TITLE
Ability to define/see preview URL for Theia tasks

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#9273]
### Description
User should have ability during creation of a new task (command in Che terminology) to provide Preview URL using macros (see #8974). 
After successful execution of a command this URL will be shown on UI

**Comment by azatsarynnyy** [comment]
A preview URL can be defined by adding the optional filed `previewURL` in a task definition:
```json
{
    "type": "che",
    "label": "...",
    "command": "...",
    "target": {
        "machineName": "..."
    },
    "previewUrl": "${server.tomcat8}"
}
```
Variable substitution is supported.
