### ISSUE TITLE
Run to Cursor stops on old cursor location in loops

### ISSUE THREAD

**Issue by lolo58200** [eclipse-che/che#9281]
### Description
When debugging a loop structure, a run to cursor behaves as a breakpoint for each interation

COMMITTERS: please include labels on each issue. Labels are listed here: https://github.com/eclipse/che/wiki/Labels but at a minimum you should include `kind` and `status` labels.
--> 

### Reproduction Steps
When debugging a loop structure, set a breakpoint.
Once at that breakpoint, select one line later and run to cursor to go straight to it.
Now resume, it goes to next iteration of the loop if exists and to the breakpoint. 
Finally resume, it stops to the original place where the cursor was run (even if the cursor has moved)

**OS and version:**    
Che 6.2

**Diagnostics:** 
Each Run to cursor action seems to create a non visible breakpoint
Expected : this non visible breakpoint can be hit only once and removed

**Comment by eivantsov** [comment]
@tolusha is this expected behavior?

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/13)
