### ISSUE TITLE
Need to override eclipse che's default maven settings in Openshift

### ISSUE THREAD

**Issue by dimplerohara** [eclipse-che/che#9282]
### Description
In our organization, we are running Che in Openshift Environment. Our organization does not support downloading dependencies from public maven repository. We have a private artifactory setup to download all the required dependencies. How should I be overriding Che's default maven settings with my custom settings.xml?

**OS and version:**    
Windows 7 +  Chrome

**Comment by garagatyi** [comment]
Do you need to override maven repo to build Che or in Che workspaces?

**Comment by dimplerohara** [comment]
To build project in Che workspaces.

**Comment by skabashnyuk** [comment]
you can build your image with your settings.xml

**Comment by eivantsov** [comment]
You can also add a volume to your machine https://www.eclipse.org/che/docs/volumes.html

Inside that volume, you can store maven repo and settings.xml. It will be persisted.
