### ISSUE TITLE
Introduce Notification Manager Plugin API 

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9284]
The new plugin model should contain API for accessing Notification Manager from Theia core. The task includes following items to be done:
- [x] define the API of the Notification Manager
- [x] document the API
- [x] develop the defined API
- [x] test it on the sample plugin

**Comment by benoitf** [comment]
hello, how is looking like the api ?
theia.window.showInformationMessage / theia.window.showWarningMessage / theia.window.showErrorMessage ?

**Comment by olexii4** [comment]
Hello
Yes. It looks like:
showInformationMessage<T extends MessageItem>(message: string, ...items: T[]): PromiseLike<T | undefined>;
...

**Comment by olexii4** [comment]
https://github.com/theia-demo-plugins/wiptheia/pull/2
