### ISSUE TITLE
Add ability to tracking the container status through WebSocket connection for containers plugin

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#9291]
Add ability to tracking the container status through WebSocket connection for containers plugin.

**Comment by gorkem** [comment]
I am not sure if we need to track the status of each machine @slemeur WDYT? However as a first step, can we add a status indicator on the status bar of the Theia if the workspace is running or not. Also if workspace is not running we could present a command on the status bar to start the workspace.
Ideally we can replace the current 'Offline' status item that appears when Theia looses connection to backend with something that can start a workspace, if it is not running.

**Comment by gorkem** [comment]
@olexii4 Why did you close this one?
