### ISSUE TITLE
"Created" Notifications for existing Files on Startup

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9294]
To reproduce:
1. Create a workspace and import a large project
2. Stop the workspace
3. Put a breakpoint on FileTreeWalker.java on line 159
4. Start the workspace and connect the debugger when ready
Observe: you hit the breakpoint thousands of times (each file, I believe)

**Comment by tsmaeder** [comment]
This is an important bug for jdt.ls, as we are reacting to file change notifications on *.java files

**Comment by dkuleshov** [comment]
Hi,

As of what I see in [FileTreeWalker#updateFsTreeAndAcceptConsumables](https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/watcher/server/impl/FileTreeWalker.java#L142) we determine file creation by comparing current state with previous, while for workspace that just has been started states for all existing files are undefined, so comparison erroneously gives us invalid status.

Probably initialization of file system items' states just before actual tracking starts is the most obvious solution here.

**Comment by tsmaeder** [comment]
@dkuleshov also, as I read the code, the file tree walk is called every 10 seconds, even if the previous one has not finished yet. Isn't the idea to have 10 seconds between runs?

**Comment by dkuleshov** [comment]
@tsmaeder the idea is to run tree walk not more often than every ten seconds, so taking into account  what they say [here](https://github.com/eclipse/che/blob/2c2bd6637c8169018e2b33397f9d738bbf82a0b1/core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/ScheduleRate.java#L24) in the `ScheduleRate` annotation description: "If any execution of this task takes longer than its period, then subsequent executions may start late, but will not concurrently execute", we walk the tree either every ten seconds or in your case just right after the previous walk is finished.
