### ISSUE TITLE
Terminal does not reconnect automatically if websocket connection is closed

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#9295]
### Description
For example on AWS, if no data is sent for 60s, the websocket is closed
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout

So by default on AWS, Che terminal will hang after 60s if user did not enter any characters on it.

### Reproduction Steps
Close websocket of terminal.
Expect: terminal should try to reconnect or to send ping/alive items as well to maintain connection.

**OS and version:**    
Eclipse Che 6.3.0

**Comment by AndrienkoAleksandr** [comment]
Server side contains ping/pong handler, but I guess client doesn't contains such handler. Seems we need apply it.

**Comment by benoitf** [comment]
@AndrienkoAleksandr do you know the ping/pong handler delay ?

**Comment by AndrienkoAleksandr** [comment]
Yes, 60 second: https://github.com/eclipse/che/blob/master/agents/go-agents/terminal-agent/term/server.go#L36

**Comment by gorkem** [comment]
@benoitf Is this Che 6 only?
