### ISSUE TITLE
[Docs] Add instructions for deploying in Kubernetes

### ISSUE THREAD

**Issue by sr229** [eclipse-che/che#9298]
### Description
When I last checked the Eclipse Che documentation, there is a depoyment instruction for OS Online and OS (Origin, Dedicated, etc.) but there is no deployment instruction for k8s. There should be some instructions regarding deployments on native Kubernetes if user wants to deploy on k8s clusters.

**Comment by eivantsov** [comment]
@sr229 https://www.eclipse.org/che/docs/6/che/docs/kubernetes-single-user.html

But we will update docs soon with details instructions base don help installation method.

**Comment by eivantsov** [comment]
https://www.eclipse.org/che/docs/kubernetes-single-user.html
