### ISSUE TITLE
Website typo

### ISSUE THREAD

**Issue by ShalokShalom** [eclipse-che/che#9305]
Since the website is either closed source or very well hidden, here an issue report for it:

[Prouduction instead of Production](https://www.eclipse.org/che/features/)

**Comment by ShalokShalom** [comment]
Ah yeah: And the link to CheConf in the footer is broken: https://www.eclipse.org/che/checonf/

And webmaster in this page is supposed to be spelled with an uppercase W, thanks. 

P.S: Can help to prevent such issues: https://addons.mozilla.org/de/firefox/addon/grammarly-1/
https://validator.w3.org/checklink

**Comment by ShalokShalom** [comment]
It is twice here on the 404

**Comment by eivantsov** [comment]
404 is a default Eclipse site page, so out of our control.

**Comment by eivantsov** [comment]
Yes, whoever manages eclipse.org site

**Comment by ShalokShalom** [comment]
However
