### ISSUE TITLE
Single port policy: CHE_PORT is always appended to ws urls

### ISSUE THREAD

**Issue by antoine-morisseau** [eclipse-che/che#9306]
Hello,

i am following this guide to configure the single port policy : https://www.eclipse.org/che/docs/6/che/docs/docker-config.html#single-port-policy
but i have some trouble for it on the keycloak admin console.
it said that is use the `$chePort` to connect to keycloak.
but i'm using `CHE_PORT=8084` on the docker eclipse che container and use nginx to reverse proxy the url `che.morisseau.me` to `containerip:8084`

i saw after several test that it use the `CHE_KEYCLOAK_AUTH__SERVER__URL` to specify this information so i tried to override it in the `che.env` but it doesn't work.

since i use `CHE_SINGLE_PORT=true` i thought the `CHE_SINGLEPORT_WILDCARD__DOMAIN_PORT=80` would do the trick but it does nothing.

**Question 1** : 

> Is there a way to specify the external port in this configuration in order to truly have a single port policy ?

**Question 2** : 
Why the `CHE_KEYCLOAK_AUTH__SERVER__URL` start with `http` ? how can it manage to switch http or http if needed ?

**Comment by eivantsov** [comment]
@antoine-morisseau passing `-e CHE_KEYCLOAK_AUTH__SERVER__URL=$yourURL` should fix the issue

**Comment by antoine-morisseau** [comment]
I tried that.
but since i use the `CHE_SINGLE_PORT=true` i think the script creating the `che.env` file does'nt work properly.
after tried that, i saw two occurrence of `CHE_KEYCLOAK_AUTH__SERVER__URL=` in the generated `che.env` file.

same for `CHE_INFRA_DOCKER_MASTER__API__ENDPOINT` and `CHE_INFRA_DOCKER_MASTER__WEBSOCKET__ENDPOINT` that i tried to override too.

**Comment by antoine-morisseau** [comment]
I managed to override the `che.env` file manually and start with `docker-compose`.
I did that in order to avoid `eclipse/che` create the `che-env` file again.
It solve the issue about the `CHE_KEYCLOAK_AUTH__SERVER__URL` but i encounter several others.

when starting a workspace, the workspace URL agent is like this `wsagent-http.dev-machine.workspace0bcgkgkvsqi31b4u.193.12.34.56.che.morisseau.me:8084`.

i used  `CHE_SINGLEPORT_WILDCARD__DOMAIN_HOST` to `che.morisseau.me`
But why is it using the `8084` port ? 
i would like to specify the port to `80` or `443`.

**Comment by eivantsov** [comment]
@antoine-morisseau appending a port does sound like a bug. I'll run some tests on my machine and get back with findings

**Comment by antoine-morisseau** [comment]
@eivantsov The port appended is the port that is specified in `-e CHE_PORT=80804`.
But i can't specify `-e CHE_PORT=80` since i use a reverse proxy in order to avoid that.
But i'm wondering how can we specify eclipse-che in single-port policy to only use the 80 or 443 port ?

**Comment by eivantsov** [comment]
@antoine-morisseau it should not. `CHE_SINGLEPORT_WILDCARD__DOMAIN_PORT` says it all but does not work. Labeling as a bug.

**Comment by eivantsov** [comment]
@antoine-morisseau CHE_PORT is appended by default, this is how it works at the moment. Your use case is quite clear, however, SINGLE_PORT policy wasn't tested in such scenarios, so putting a reverse proxy in front causes such behavior.

**Comment by antoine-morisseau** [comment]
Glad i could help :)

**Comment by antoine-morisseau** [comment]
How a `kind/bug` can be also an `kind/enhancement` ?

Since this ticket is open i froze my works on eclipse che since i rely heavily on the one port policy.

Is there any other workaround ? like some leads on how to create a one port policy for eclipse che without using the one provided ?

**Comment by eivantsov** [comment]
@antoine-morisseau your particular use case isn't standard. Single port policy works this way on Docker. You may deploy Che on Kubernetes or OpenShift, and get one port policy via OpenShift routes or K8S ingress.
