### ISSUE TITLE
Eclipse Che Dashboard not loading for created user.

### ISSUE THREAD

**Issue by hailcarlitos** [eclipse-che/che#9314]
### Description
 
User not dashboard not loading, just stuck in loading splash screen.
Admin user can will load just fine.

I have Eclipse Che running on one machine acting as a server, and second machine acting as the developer's workstation. These computers are networked through a switch.

### Reproduction Steps
Started Eclipse Che in multiuser mode using the following command:
`docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=X.X.X.X -v /var/run/docker.sock:/var/run/docker.sock -v ~/chedata:/data eclipse/che start`

Created a user account through the Keycloak admin page, with the effective roles of "offline_access", "uma_authorization", "user"

The following ports are publicly available:
5050, 8000, 8080, 32768-65535

Able to get to the login screen, when logging in as the created user I get stuck on the loading slash screen. Logging in as the admin gets me to the dashboard just fine.

Not sure what I am doing wrong, any suggestions?

**CentOS 7 and Che version:6.3.0**

**Comment by carlangus** [comment]
I figured out what was wrong. I needed to provide an email on the user information, not even a real email, and check that it was verified. Then I was able to log in just fine.
