### ISSUE TITLE
Eclipse Che Always points To Localhost instead of Docker Machine

### ISSUE THREAD

**Issue by EriksonMurrugarra** [eclipse-che/che#9315]
### Description

I am running Eclipse che on Kubernetes. When the workspace is created I navigate to the servers tab and find that the client is always trying to connecto to 127.0.0.1 instead of my server IP Address.
I have configured the following variables: CHE_HOST, CHE_HOST_IP and CHE_DOCKER_MACHINE_HOST and It stills point to 127.0.01

Following is a picture:

![image](https://user-images.githubusercontent.com/21296976/38219466-5697cb30-369b-11e8-8c9e-1ff9c7ed626d.png)

In the POD logs:

![image](https://user-images.githubusercontent.com/21296976/38220679-20f014fa-36a1-11e8-8431-e6eeae725b12.png)

**Comment by eivantsov** [comment]
@EriksonMurrugarra how exactly did you deploy Che on Kubernetes? Can you share more details?

All of the envs you tried are for Che on Docker.

**Comment by EriksonMurrugarra** [comment]
Hi @eivantsov.

I am using the following yaml file [https://raw.githubusercontent.com/EriksonMurrugarra/eclipse-kube/master/che.yml](https://raw.githubusercontent.com/EriksonMurrugarra/eclipse-kube/master/che.yml) . This yaml creates a StatefulSet instead of a Deployment.

**Comment by sleshchenko** [comment]
`CHE_DOCKER_MACHINE_HOST` is used for only for Docker infrastructure.

And `127.0.0.1` is the host of created Ingress. And there is no an ability to override hostname of ingresses. But there is an issue for it https://github.com/eclipse/che/issues/9131

Or maybe this issue can be solved by ingress controller configuration.

**Comment by sleshchenko** [comment]
@EriksonMurrugarra Sorry for a late response. Unfortunately, I have no idea how ingress controller can be configured. 

I assume that `single-host` or `multi-host` (introduced in https://github.com/eclipse/che/pull/9329) can help you.

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
