### ISSUE TITLE
Commands not properly installed when creating project from a template in a workspace

### ISSUE THREAD

**Issue by kartben** [eclipse-che/che#932]
When creating a project from "/create-project", and selecting e.g the "console-java-simple" ready-to-run sample, I end up with a new workspace, and a new project that has "mvn build" and "mvn run" properly installed. All good.

If I instead navigate in an existing workspace (created from /create-workspace) and create the console-java-simple project from there (Workspace / Create Project... menu entry), the commands do not get installed. Sounds like a bug?

**Comment by ghost** [comment]
This is expected behavior. Right now, when creating a project from User Dashboard, commands are part of the samples definition. In the IDE, it is a normal import operation - git clone, so there's no fancy logic there.

I'll let @TylerJewell decide if it's a bug or not.

**Comment by TylerJewell** [comment]
Seems like a bug to me.  Templates have embedded commands and should always add to the drop down.  @fbenoit: does the IDE import templates differently than the dashboard?

**Comment by benoitf** [comment]
yes IDE import is not taking into account commands from templates as it is let to client logic

**Comment by kartben** [comment]
Well then I guess there is some room for some UX improvements as the IDE import templates look very much like they are just the same as the dashboard templates: same name, same description, etc.
FWIW I am not sure I understand the subtle difference there seems to be between the templates that are provided from the dashboard, and "workspace templates".

**Comment by TylerJewell** [comment]
It's not a UX improvement.  The templates are identical between the IDE and dashboard.  It's a bug because how the template is onboarded into the system is left to the client, not the server and UD / IDE implemented it differently..

@gazarenkov - we will need to move the template onboarding activities out of client and into the server to avoid these inconsistencies in the future.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-1503

**Comment by TylerJewell** [comment]
I am going to close this particular issue @kartben - because we are restructuring commands into a more intelligent system, and there will be a lot more flexibility that comes from it (and frankly a ton simpler). This is in branches now and going through testing.

**Comment by kartben** [comment]
cool :)
