### ISSUE TITLE
Add external che api url as workspace environment variables.

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9323]
### Description
Web clients that can be loaded from one of the servers running in the workspace may want to know che api url accessible from a browser.  Now,```CHE_API``` points to internally accessible url of che-master. We want to add
```
CHE_API_EXTERNAL -  external (for web browsers)
CHE_API_INTERNAL - internal (from the inside of containers)
CHE_API  = CHE_API_INTERNAL
```

**Comment by garagatyi** [comment]
I think we can skip `_URL` suffixes since CHE_API doesn't have such.

FYI Now CHE_API *may* point to internal or external URL of Che master depending on the infrastructure implementation behavior.

**Comment by sunix** [comment]
@garagatyi I am updating the description to avoid confusion (I just tried `CHE_API_EXTERNAL_URL` and not `CHE_API_EXTERNAL` :-/ )
