### ISSUE TITLE
What is the best way to develop javascript ide extensions?

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#9332]
### Description
I need to develop extensions that it should be installed and updated using npm.

**Comment by eivantsov** [comment]
No, extensions for Theia are extensions for Theia. You may write an extension for Theia and then launch Theia as an alternative IDE.

As this point there are no docs or readmes or smth worth sharing since it is a bit too early.

**Comment by cenkce** [comment]
And it isn't possible such that in che right now, is it?

**Comment by eivantsov** [comment]
Correct. Currently, adding client side plugin is possible with GWT plugins only
