### ISSUE TITLE
Keycloak redirection

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#9333]
### Description
When start and deploy server extension sample project, it run on different ports everytime and keycloak gives redirection error constantly. Can I add the ports to Valid Redirect URIs as range ?

**OS and version:**    
Ubuntu 16.04
Che 6.3.0 Multiuser

**Comment by eivantsov** [comment]
@cenkce earlier Keycloak versions used to accept wildcard for redirectURI and webOrigin. It's worth trying though.

**Comment by cenkce** [comment]
No it doesn't work for example http://{IP}:*
