### ISSUE TITLE
Display `identity_id` and `request_id` properties in plaintext console logger by default.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#9334]
### Description
https://github.com/eclipse/che/issues/9275 adds the ability to add and choose appenders for ouput console log. Default loggers are plain text and json. json logger is showing mdc properties `identity_id` and `request_id` but plain text one doesn't by default. I think showing these information in plaintext would be useful as well.

**Comment by eivantsov** [comment]
@skabashnyuk @sunix can we label this one as an enhancement or task? Or has this been already done?

**Comment by skabashnyuk** [comment]
@eivantsov I guess we are debating pros and cons of this issue. I'm sure it will be more informative but not so sure about the usability of this form, that is why I was asking for a prototype.

**Comment by sunix** [comment]
yes to me, these informations could be useful while debugging. The question is not about human or bot but if it is useful to fix an issue or not. I think we need to be consistent: if these are displayed in the json logs, should be display either in the text logs.

**Comment by garagatyi** [comment]
Never felt a need for this information in Che plaintext logs before, so it is arguable whether we need it or not. But I don't have a strong opinion on that. And I agree with @skabashnyuk if we had an example how it looks on different screens we would be able to consider it more thoughtfully.

**Comment by skabashnyuk** [comment]
@sunix can you provide some examples? I agree with @garagatyi's statements.

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen with additional details so that this issue can be converted into a task
