### ISSUE TITLE
Parts of Che UI freezes when a file is open

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#9335]
### Description
The Che UI is freezing when you have a file open in the editor and you try to do something such as create a new file. The only way to get rid of the UI is to refresh the page. If you do not have a file currently open in the editor and try to create a new file it works fine.

### Reproduction Steps
Import a project, open any type of file, right click the project and click new file of any type. The UI should freeze and you cannot close the new file UI. 

![che_bug](https://user-images.githubusercontent.com/8839537/38315692-fd6245b0-37f6-11e8-9869-2114603a63d9.gif)

**Comment by eivantsov** [comment]
@JPinkney what environment was it? OSO? MiniShift? Local Docker? thanks

**Comment by JPinkney** [comment]
Local Docker and it looks like its only happening on 5730_java_ls_poc branch. I cannot reproduce on master.

**Comment by JPinkney** [comment]
We can close this because the issue was only happening because I needed to build a different branch of che-lib.
