### ISSUE TITLE
Preferences System for Che with Theia IDE

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#9336]
## Goal
Developers using Eclipse Che might use different workspaces and be able to define preferences at workspace level or user level.

### Description
Need to store and sync Theia global user preferences to the persistent storage . 

Theia has two levels of preferences settings:
- one per workspace (possible will be backed up in same way the project sources)
- another - global user settings should be available for any user's workspaces (in local Theia installation stored in $HOME/.theia)

This issue should cover second behavior

### Tasks

- [x] Preferences UI for Theia IDE https://github.com/eclipse/che/issues/9730

See also #8981

**Comment by vinokurig** [comment]
PR: https://github.com/vinokurig/preferences-plugin/pull/1

**Comment by slemeur** [comment]
@vparfonov + @vinokurig : Could we decompose a little bit more the work that has to be done, so we can followup on the progress of this epic?
