### ISSUE TITLE
Newer Go and C# language servers do not work with Che LSP client

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9351]
## The problem

Having tried to launch Go and new C# language server, I faced the same problem:

1. Language server is initialized ok
2. Language server capabilities do not work, and ws agent spits the following log: https://gist.github.com/eivantsov/45ba02bec3d7112a500a3b94e7c80186

## Steps to reproduce

1. Create and launch a workspace using the following config https://gist.github.com/eivantsov/6b52bafaca1b7a4180229ae289a46d0a
2. Open .go file

1. Create and launch workspace using the following config
https://gist.github.com/eivantsov/caae9c485402c2e91ec3372b4d634918
2. Open .cs file

## Language servers used

https://github.com/theia-ide/go-language-server
https://github.com/OmniSharp/omnisharp-roslyn/releases

**Comment by gorkem** [comment]
Do we need the new version of LSP4J @vparfonov probably good candidate for next sprint. @tsmaeder are we going to update LSP4J together with jdt.ls

**Comment by eivantsov** [comment]
Language servers do not necessarily have to be in sidecars. You can install C# with an installer and launch with a launcher script as usual (`./run --lsp --verbose`)
