### ISSUE TITLE
We should ensure that pom.xml are opened with LSP editor

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9352]
### Description
Recently we tried to do some tests around pom.xml and LSP and we have a feeling that currently (as CHE 6.4.0-SNAPSHOT ) we do not use LSP editor configurations for pom.xml files, but default editor instead. We must check it to be sure that everything works as expected.
**OS and version:**   Fedora 25, Chrome browser, CHE 6.4.0-SNAPSHOT, rev.219802a1e075d68e

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/12)
