### ISSUE TITLE
Add empty port to keycloak if port 80 is specified

### ISSUE THREAD

**Issue by jgroom33** [eclipse-che/che#9356]
### Description
When CHE_PORT=80 forwarding entries in keycloak should added automatically

![image](https://user-images.githubusercontent.com/3970574/38438098-b65f38fc-3996-11e8-8e1f-c521dbb30000.png)

### Reproduction Steps

**OS and version:**    
Che=6.3

**Diagnostics:**

**Comment by eivantsov** [comment]
@jgroom33 Yes, CLI should handle it in a more graceful way, for ports 443 and 80. Thanks for noticing that.
