### ISSUE TITLE
Unable to clone Github private repositories (if oauth app has not permission)

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#9358]
On Github, by default there is no access for oauth apps
https://help.github.com/articles/about-oauth-app-access-restrictions/

Thus If you try to clone a repository from an organization that is not letting this access, it's not working.

I should be able to provide my username/password to successfully clone the repository in that case.

### Reproduction Steps
Clone private repo on a ORG that is not authorizing oauth apps (this is the default setting)

**Comment by maxandersen** [comment]
also cannot push to public repositories without full github style oauth/ssh setup.

Prevents using che with any non-github/oauth repository.

basic username/password via https should at least be supported.

**Comment by skabashnyuk** [comment]
@vinokurig @tolusha  wdyt would it be possible to change GWT-base git plugin to ask username/password to successfully clone the repository? @ashumilova  Or it would make sense to implement that in Theia-based plugin and not lose our time gwt plugin refactoring? Anyway, we have to do that in the Theia-based plugin too.

**Comment by vinokurig** [comment]
@skabashnyuk I don't see any problems from a technical point of view to implement this.

**Comment by artaleks9** [comment]
Still actual for ver.6.5.0

**Comment by skabashnyuk** [comment]
This is an enhancement since we never had this ability. And I guess it's related to Theia ide.
