### ISSUE TITLE
Drag & drop workflow UI in Eclipse che

### ISSUE THREAD

**Issue by prateekkohli21** [eclipse-che/che#9361]
### Description
Hi,

I want to develop a drag & drop workflow UI for Eclipse che. Something like mxGraph.
How should I proceed further, which technologies should I use. Can I get any already built plugin for eclipse che supporting the same.

Thanks

**Comment by eivantsov** [comment]
@prateekkohli21 there's no ready to use drag and drop plugin for Eclipse Che and no immediate plans to write one.

Eclipse Che uses GWT http://www.gwtproject.org/ as a client side technology. 

There are a few tutorials in docs on how to modify UI https://www.eclipse.org/che/docs/parts.html

FYI, at this moment there's an ongoing effort to integrate Theia https://github.com/theia-ide/theia into Che. Theia's core techologies are Node.js and TypeScript for client side. Perhaps, something is planned in this regard by Theia maintainers.
