### ISSUE TITLE
Wrong committer when sharing a workspace in an org

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9362]
Steps to reproduce.

1. User A created an org and added a workspace and shared it with User B
2. User A generated a key, uploaded it to GitHub and added git committer name at Profile > Preferences > Git Committer
3. User B generated own key and added own committer name and email
4. User B commits and pushes as user A.

**Comment by vinokurig** [comment]
should be fixed by https://github.com/eclipse/che/issues/10243
