### ISSUE TITLE
Clarify reason of failing the CheckGeneratingMavenArchetypeTest

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9365]
### Description
Today the test has fallen on all ci jobs.  We should investigate reasons of this problem.
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/209/Selenium_tests_report/
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-docker/174/Selenium_tests_report/
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/177/Selenium_tests_report/

**Comment by musienko-maxim** [comment]
Looks like the `maven-archetype-quickstart project` has been changed on central repo. We should update dependent  resource on the test

**Comment by dmytro-ndp** [comment]
@musienko-maxim: can you please, add error log and link to the CI job where the test had failed in description of issue?
