### ISSUE TITLE
Not compiled example from custom build che

### ISSUE THREAD

**Issue by Flax163** [eclipse-che/che#9373]
### Description
Hello, trying to build an example  https://github.com/che-samples/che-ide-server-extension/tree/6.3.0
but build with error in Module (Plugin ServerService :: Che Assembly :: IDE Assembly FAILURE)

link for example from the documentation https://www.eclipse.org/che/docs/assemblies.html

### Reproduction Steps
1) git clone https://github.com/che-samples/che-ide-server-extension/tree/6.3.0
2) mvn clean install

**OS and version:**    
OS: WINODWS 7
JAVA_VERSION: 1.8.0_161
MAVEN_VERSION: 3.3.9

**Diagnostics:** 
[log.txt](https://github.com/eclipse/che/files/1897647/log.txt)

**Comment by eivantsov** [comment]
@Flax163 I cannot reproduce it. Besides, this repo is on CI, so we'd notice build fail. Are you certain you have not modified anything in sample source code?

**Comment by Flax163** [comment]
@eivantsov No, I did not change anything in source

**Comment by eivantsov** [comment]
@Flax163 probably Win specific. You can try building it in a Docker container. Instructions are in docs and wiki

**Comment by Flax163** [comment]
It seems that it was with a maven repository or a version of JDK,

cleaned the caches and changed the version to 8_131 (I do not really understand what helped) but now the project is going to
