### ISSUE TITLE
Investigate execution of Eclipse Che dashboard related selenium tests on OSIO

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9374]
### Description
We need to execute _Eclipse Che 6_ selenium tests on _Dashboard_ on OSIO on regular base. This issue is aimed to investigate possible drawbacks of existed tests and to organize their fix up.

Also we need to prepare the list of _Dashboard_ functions which are not covered by selenium tests.

**Comment by dmytro-ndp** [comment]
Found issues:
1. We need to work around "_Start_" workspace button in selenium tests which open workspace in IDE from Dashboard (an issue #9381).
1. Organization tests from package **org.eclipse.che.selenium.dashboard.organization.*** require _system admin account_ which creates organization in Eclipse Che.

**Comment by dmytro-ndp** [comment]
Eclipse Che Dashboard features which should don't have E2E selenium tests:

Main menu | Window title | Tab title | Issue
--------- | ------------ | --------- | -----
Workspaces | Workspace Details | Config | 
Factories | Factory Details | * | 
Stacks | Stacks list | * | 
Stacks | New Stack | * | 
Stacks | Stack details | * | 
Recent workspaces | * | * | 
Account | * | * | 
Diagnostics | * | * | 
Documentations | * | * |

**Comment by SkorikSergey** [comment]
Result of starting selenium tests from **org.eclipse.che.selenium.dashboard** package on  **prod-preview**.
![selection_236](https://user-images.githubusercontent.com/7760565/38932783-ddd973e2-431f-11e8-8b81-63b5b85d0932.png)


[target.zip](https://github.com/eclipse/che/files/1924007/target.zip)
