### ISSUE TITLE
IMAGE_POSTGRES env var is must be before running `deploy_postgres_only.sh`. Could we have a default value set ?

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#9376]
### Description
running `./deploy_postgres_only.sh` results in:

`[CHE] **ERROR**Env var IMAGE_POSTGRES is unset. You need to set it to continue. Aborting
`

If env var is not set could we fall back on `docker.io/eclipse/che-postgres` instead of failing ?

**Comment by ibuziuk** [comment]
wdyt @eivantsov @l0rd @garagatyi ?

**Comment by eivantsov** [comment]
@ibuziuk I think this script should not be executed alone. `IMAGE_POSTGRES` is set here https://github.com/eclipse/che/blob/master/deploy/openshift/deploy_che.sh#L275

**Comment by ibuziuk** [comment]
@eivantsov @garagatyi  when deploying on dev cluster I tend to use it alone, so thought it might be good check to have in place since it should not hurt. If you think it is not relevant feel free to close the issue

**Comment by l0rd** [comment]
Setting to `eclipse/che-postgres` if the env var is empty should not do any harm.

**Comment by eivantsov** [comment]
@l0rd I don't mind if this check shows up in deploy script.

**Comment by ibuziuk** [comment]
PR is sent https://github.com/eclipse/che/pull/9382

**Comment by ibuziuk** [comment]
merged. Closing
