### ISSUE TITLE
Workspace is not started automatically from Dashboard after clicking  "Open in IDE" button

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#9381]
I suspect there is some problem / race condition with starting workspace - was able to reproduce the problem against https://rhche.openshift.io/dashboard/#/ dashboard:
1. Create workspace against vert.x stack
2. Press "Open in IDE" button:
![image](https://user-images.githubusercontent.com/1461122/38628941-ee31cca2-3db2-11e8-9dfe-f5b03ffad4ed.png)
3. ERROR: Workspace is not starting
![image](https://user-images.githubusercontent.com/1461122/38629019-23c04c68-3db3-11e8-81ae-3692d27c5e5e.png)
4. Press "Start" -> workspace is successfully started
 
NOTE: `che.workspace.auto_start` is set to `false` for rh-che deployment, not sure if it is expected but IMO if user press `Open in IDE` button workspace should be started in anycase (the property should only handle the case of direct opening of the workspace URL e.g from bookmark ). Description of the property:

```
# By default, when users access to a workspace with its URL the workspace
# automatically starts if it is stopped. You can set this to false to disable this.
che.workspace.auto_start=true 
```

**Comment by garagatyi** [comment]
@vparfonov has IDE changed its behavior since Che5 in such cases?

**Comment by eivantsov** [comment]
@ibuziuk this is expected behavior since auto start is set to false.

**Comment by ibuziuk** [comment]
@eivantsov yeah, I wrote about it in the issue description.

> NOTE: che.workspace.auto_start is set to false for rh-che deployment, not sure if it is expected but IMO if user press Open in IDE button workspace should be started in anycase (the property should only handle the case of direct opening of the workspace URL e.g from bookmark ).

IMO "Open in IDE"  should start workspace in any case regardless of the `che.workspace.auto_start` property if we are planning to leave dashboard on osio

**Comment by eivantsov** [comment]
Has @ashumilova had her say already?

**Comment by ibuziuk** [comment]
after thinking more about the problem I now started to doubt why `che.workspace.auto_start` is needed at all in Che 6 (e.g. which usecase are we trying to handle with it). Please, comment in https://github.com/redhat-developer/rh-che/issues/629#issuecomment-382344002
if there are some concerns I'm missing

**Comment by ibuziuk** [comment]
Closing as outdated
