### ISSUE TITLE
Unable to mount CHE_WORKSPACE_VOLUME

### ISSUE THREAD

**Issue by mulhauser** [eclipse-che/che#9390]
### Description
I'm trying to pass maven configuration by mounting CHE_WORKSPACE_VOLUME with this command
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v D:\Tools\che-data:/data -e CHE-WORKSPACE-VOLUME=D:\Tools\che-conf:/home/user/.m2 eclipse/che start`

My settings.xml file is located in D:\Tools\che-conf
I reproduced this [closed issue](https://github.com/eclipse/che/issues/2309) but it failed.
When I print the listed files/folders in any container-workspace, I did not find any .m2 folder or settings.xml file

### Reproduction Steps
Just running the above command

**OS and version:**    
Host: Windows 10
Eclipse che: latest

**Comment by eivantsov** [comment]
@mulhauser there are 2 things you need to be aware of:

1. unix like path format /d/Tools/...
2. Make sure drive d is mounted into Docker VM filesystem

**Comment by mulhauser** [comment]
My D drive si already mounted into Docker VM filesystem. 
And the che-data folder which is located in my D drive is mounted on che-server.
I’m running docker on Windows 10. So the path must be Windows style?

**Comment by mulhauser** [comment]
I found this [bug](https://github.com/eclipse/che/issues/6769). Is there a relationship ?

**Comment by mulhauser** [comment]
Now it is working. But I don’t understand why I can use windows style path for che-data?

**Comment by mulhauser** [comment]
I close this issue and this the following working command line:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v D:\Tools\che-data:/data -e CHE_WORKSPACE_VOLUME=/d/Tools/che-conf:/home/user/.m2:ro,Z eclipse/che start`
