### ISSUE TITLE
Exported folder packs with absolute paths

### ISSUE THREAD

**Issue by xcariba** [eclipse-che/che#9397]
### Description
When I try to download folder as Zip archive Che zips it with absolute paths.
I expect it to zip with paths, relative to selected folder.

### Reproduction Steps
Download folder as zip
![image](https://user-images.githubusercontent.com/7170514/38682531-fd09a79c-3e73-11e8-8d66-e12f2153ab82.png)
It contains full path in zip
![image](https://user-images.githubusercontent.com/7170514/38682647-526851ac-3e74-11e8-9f59-deafe0bdfae0.png)

**OS and version:**    
Fedora 27
Che 6.3.0
**Diagnostics:**

**Comment by dkuleshov** [comment]
Hi,

This issue should be fixed by the following pull request: https://github.com/eclipse/che/pull/9400

**Comment by eivantsov** [comment]
Closing the issue in favor of https://github.com/eclipse/che/pull/9400
