### ISSUE TITLE
Impossible to copy/paste into Terminal

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#9398]
### Description
When opening a terminal, sometime it is not possible to do copy/paste in it

See the attached video:
![copy-paste](https://user-images.githubusercontent.com/1636769/38684715-94720f1a-3e70-11e8-80ca-a4eb9b354e31.gif)

**OS and version:**    OSIO + Che

**Comment by AndrienkoAleksandr** [comment]
Should be fixed after https://github.com/eclipse/che-lib/issues/57

**Comment by artaleks9** [comment]
Still actual for ver.6.5.0

**Comment by vkuznyetsov** [comment]
Should be fixed in new version of terminal. Let's postpone it until merging https://github.com/eclipse/che/pull/10037

**Comment by AndrienkoAleksandr** [comment]
Fixed after update xterm.js to version 3.3.0. Current issue was actual not "sometimes", It was reproducible  only for first line of the terminal.
