### ISSUE TITLE
An error occurred, please login again through your application when using Github OAuth

### ISSUE THREAD

**Issue by Blendman974** [eclipse-che/che#9399]
Hi, I get the message "An error occurred, please login again through your application." when trying to use github Oauth : 
![lagin](https://user-images.githubusercontent.com/35555508/38684289-65ea5034-3e80-11e8-9ce1-9bd9ad2820cc.png)
Same occur in the IDE : profile -> preferences -> SSH -> VCS -> Github button
![image1](https://user-images.githubusercontent.com/35555508/38684435-c53e8e2e-3e80-11e8-9a63-310d85dc518a.png)
Steps to reproduce : enabling github in keycloak : 
![image2](https://user-images.githubusercontent.com/35555508/38684593-181f2892-3e81-11e8-81d1-8708c776a395.png)
**OS and version:**    
Debian 9 , eclipse che v6.3.0 (docker v18.03.0-ce)
**Diagnostics:** 
The url of the error page is : "http://aspaku.com:5050/auth/realms/che/broker/github/endpoint?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=sBs9Iugwgnnql3Gg2vqjGPhjr8t1L-ZeeZVRvgB3n9g.che-public"

**Comment by eivantsov** [comment]
@Blendman974 what I see is that there's IP address in redirect uri:

`https://github.com/login/oauth/authorize?scope=repo%2Cuser%2Cwrite%3Apublic_key&state=N3QzeorlSKxxcwKSk_wI1MK1AbGO_ns9kfBHeB_EsKI.che-public&response_type=code&client_id=04dd6795420217bbd231&redirect_uri=http%3A%2F%2F173.249.14.106%3A5050%2Fauth%2Frealms%2Fche%2Fbroker%2Fgithub%2Fendpoint`

**Comment by Blendman974** [comment]
Yeah, just reinstalled everything, now the error is : "Unexpected error when authenticating with identity provider" :
![v2](https://user-images.githubusercontent.com/35555508/38718315-78b56d20-3efd-11e8-83b9-089c07004a83.png)
The URL seems good now : "http://aspaku.com:5050/auth/realms/che/broker/github/endpoint?code=aa2dcf8cd8b540fd952e&state=6UoLGD6AwaJFF-gRQK2pSf7OGipZy4vpDsCKrzHTiV4.che-public"
Keycloak config is still : 
![keyv2](https://user-images.githubusercontent.com/35555508/38718480-676ca46a-3efe-11e8-96db-a61b44952f42.png)
and is described in this doc : "https://www.eclipse.org/che/docs/user-management.html" ; read token is a default role : 
![brokev2](https://user-images.githubusercontent.com/35555508/38718569-a22d1314-3efe-11e8-8235-63f423114899.png)

My redirects URIs are for Che-Public : 
![chepub](https://user-images.githubusercontent.com/35555508/38718747-9795303e-3eff-11e8-84d3-c5e1c83bb203.png)
Don't know if normal but in Client -> Brokers I have * in redirect URIs and in Web origins : 
![brokerrevelant](https://user-images.githubusercontent.com/35555508/38718830-04b2e954-3f00-11e8-8edf-63403c7bfa1c.png)
My che start command is "docker run -it -e CHE_MULTIUSER=true -e CHE_HOST=aspaku.com -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start". There is almost nothing in che logs and I don't know how to provide the keycloak logs.

**Comment by eivantsov** [comment]
@Blendman974 Keycloak logs please.

`docker logs -f $keycloak_container`

**Comment by Blendman974** [comment]
Keycloak logs : https://pastebin.com/b76f67Fm
So seem secret/ID isn't right so I generated a new apps and now the login throught github is working but still no luck in the IDE (Profile->Preferences->SSH->VCS->Gihub button) wich seems to be loading but just close the popup window without doing anything. This button does : 
"06:47:45,755 ERROR [org.keycloak.services.resources.IdentityBrokerService] (default task-25) Client [che-public] not authorized to retrieve tokens from identity provider [github].
06:47:47,401 WARN  [org.keycloak.events] (default task-31) type=REFRESH_TOKEN_ERROR, realmId=che, clientId=che-public, userId=b07e3a58-ed50-4a6e-be17-fcf49ff8b242, ipAddress=90.10.67.15, error=invalid_token, grant_type=refresh_token, refresh_token_type=Refresh, refresh_token_id=8d547358-144a-4cb0-879d-a6546630f37e, client_auth_method=client-secret"

**Comment by eivantsov** [comment]
@Blendman974 it just worked for me using your installation - you will find a new user in Keycloak :)

Try loggin out and loggin in again.

**Comment by Blendman974** [comment]
Ok everything is working using a new account, seem that the admin account has somes problems with OAuth ! Thanks alot
