### ISSUE TITLE
How to externalize che.properties to use custom property in workspace agent

### ISSUE THREAD

**Issue by nitish54** [eclipse-che/che#9416]
### Description
I have an use-case in which I need to have few custom properties externalized for the workspace agent and the user should be able to provide those properties as a parameter while starting the Che docker image like this: <br/>

> docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v <path>:/data -e CUSTOM_PROPERTY=some_custom_value eclipse/che start

I know that we can override the che.properties with the similar syntax but those properties are only applicable to the che server. I need some custom property that should be applicable to the agent code. <br/>

I tried directly injecting some existing property in che.properties but I was not able to read in the workspace agent. But on the other hand the properties present in this path https://github.com/eclipse/che/blob/master/assembly/assembly-wsagent-war/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties I was successfully able to inject from workspace.

I have two questions: <br/>
1. How can we add custom properties in che-machine-configuration.properties file or any other property file accessible to workspace agent? Does it have to be manual adding the new property or is there any other process to do so? <br/>
2. If a new property is added, is there any way to override the property from docker run command so that it uses the new value given while starting che?<br/>

I also tried to follow steps given [here][1] but I am not really sure about <p>
`mkdir -p /home/$user/.che/plugin-conf

export CHE_LOCAL_CONF_DIR=/home/$user/.che

Create props file ~/.che/plugin-conf/che.properties
</p>

This is unclear to me where to create these folders and the property files in the agent or in the assembly repo somewhere. <br/>

I am currently using eclipse-che 5.14.0 local assembly building. We have plans to move to latest but currently I want to find a solution for this problem in this build.

Any help is appreciated.

  [1]: https://github.com/eclipse/che/issues/2511

**Comment by eivantsov** [comment]
@nitish54 I do not think we have a mechanism of providing custom properties to ws agent through CLI.

**Comment by nitish54** [comment]
@eivantsov Thanks for the reply. 
Is there any other way to achieve this kind of behavior then? 
This may not override through CLI but should be able to inject any other property from any .properties file from any other mounted location. Is there any possibility of this kind?

**Comment by eivantsov** [comment]
Do you need property only? Env variable will do the same. And users can define them

**Comment by nitish54** [comment]
Yes I need only property. 
I tried updating che.env for adding one custom property but still I was not able to inject that property in ws agent code. May be I did something wrong.
Can you describe how to achieve this?

**Comment by eivantsov** [comment]
@nitish54 say, you have property `my.property`

If you declare an env in your machine `MY_PROPERTY`, ws agent will use it.

https://www.eclipse.org/che/docs/properties.html#properties-and-environment-variables

**Comment by nitish54** [comment]
@eivantsov I think what are you explaining here can be used in che-version >= 6.0. Can we achieve this in 5.14?
How to achieve this kind of behavior lets say, I have che.my.property defined somewhere to be accessible to ws agent (Don't know if this is possible?) and this property could be overridden by the agent machine if they define their own property?

**Comment by eivantsov** [comment]
@nitish54 it should work with 5.x

If you introduce a new property, you have your own Che assembly, correct? Then you must have some default value. If a user provides env CHE_MY_PROPERTY in the machine, ws agent will use its value.

One thing to note - providing envs per machine has been introduced in Che 6 workspace model. In Che 5, it is possible by adding an env to a Dockerfile or Composefile.

**Comment by eivantsov** [comment]
@nitish54 you reference ws-master not ws agent. 

So you need to add a custom property in https://github.com/eclipse/che/blob/master/wsagent/che-wsagent-core/src/main/webapp/WEB-INF/classes/codenvy/che-machine-configuration.properties and your plugin should use it.

Them, if there's CHE_MY_PROPERTY environment variable in a machine, ws agent will use its value rather than the default property.

**Comment by nitish54** [comment]
@eivantsov Yes, I am able to inject the custom property and override it using environment variables. Thanks for the help.
Just one question, Is there any plan to support the custom properties from docker CLI in the near future?

**Comment by eivantsov** [comment]
@nitish54 there are no such plans
