### ISSUE TITLE
Nearly all links on https://github.com/eclipse/che/blob/master/CUSTOMIZING.md are 404'd

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#9419]
### Description

There are four links under the Stacks section of https://github.com/eclipse/che/blob/master/CUSTOMIZING.md ... and all 4 are 404'd links:

https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html#stack-administration
https://www.eclipse.org/che/docs/devops/runtime-stacks-data-model/index.html
https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html#stack-library
https://www.eclipse.org/che/docs/devops/runtime-stacks/index.html#adding-stacks-to-the-che-default-assembly

I had a quick look in the actual Che docs on eclipse.org and found only 1 vaguely related page:

https://www.eclipse.org/che/docs/stacks.html

Also found these pages:

https://www.eclipse.org/che/docs/recipes.html
https://www.eclipse.org/che/docs/workspace-data-model.html

But where have the runtime-stacks pages gone?

### Reproduction Steps

1. Go here: https://github.com/eclipse/che/blob/master/CUSTOMIZING.md
2. Click these links:

![image](https://user-images.githubusercontent.com/227597/38737779-49d4812a-3efe-11e8-9676-92a2d250b663.png)

3. Observe the 404edness.

**OS and version:**    

n/a

**Diagnostics:** 

n/a

**Comment by nickboldt** [comment]
Links are also 404'd under **Recipes**, **Project Samples**, **Commands**, **Extension Development** (all but 2 links), **IDE Extensions**, **Server-Side Extensions and Agents** (all but 1 link), & **Workspace REST API**.

So... yeah. This page is almost entirely broken. :(

**Comment by gorkem** [comment]
It is suffering from the docs switch between che5 and che6, you can find referenced links under https://www.eclipse.org/che/docs/5/che/docs/. I think on the che6 docs under [Developer Guiders](https://www.eclipse.org/che/docs/framework-overview.html) we got similar information.

**Comment by eivantsov** [comment]
@gorkem Che 6 docs are fine. However, we still catch different pages that refer to Che 5 docs.
