### ISSUE TITLE
Maven pom.xml and project configuration are not synced

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-che/che#942]
I added a maven pom using the project configuration. Afterwards I opened the pom-xml and changed the group id and version number. When reopening the project configuration I still see the old information.

**Comment by ghost** [comment]
Can you elaborate? Not sure I understand how to reproduce the issue.

**Comment by svenefftinge** [comment]
1) open any mavenized project.
2) open pom.xml file in editor and change the group-id
3) open though the menu Project->Configuration, select "Maven Project" and click next.
4) See the old group id in the dialog form.

**Comment by svenefftinge** [comment]
Also the pom.xml is not updated when I change values in the "Project Configuration".

**Comment by ddementieva** [comment]
This is a known issue. Thanks for reporting it.

**Comment by TylerJewell** [comment]
@ddementieva - please cross-link any other issues since this is known, even if they are in a Jira.  Also, please provide any details on if it's scheduled for a milestone release, or just floating in the backlog.

**Comment by TylerJewell** [comment]
@ddementieva - please cross-link any other issues here.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-914

**Comment by TylerJewell** [comment]
Setting this as a blocker for now so that we discuss its status in next sprint planning meeting. This may not be actual any more.

**Comment by bmicklea** [comment]
@jamesdrummond can you please document how to do the Maven update for this?
