### ISSUE TITLE
Add apache httpd to an existing eclipse/* image

### ISSUE THREAD

**Issue by terrywbrady** [eclipse-che/che#9427]
### Description
I am running a workspace in Codenvy that is built from eclipse/x11_vnc.

I would like to add Apache httpd into this workspace.

What is the best way to accomplish this in a Che workspace?

Should I create a new image based on eclipse/x11_vnc that installs httpd, or should I create a multi-machine workspace that runs httpd as a separate image?

If an existing example exists, I would find it very helpful to see.

Please let me know if this request should be created somewhere else.

### Reproduction Steps

**OS and version:**    
Running in Codenvy

**Diagnostics:**

**Comment by eivantsov** [comment]
Closing the issue. Feel free to reopen if the suggested Dockerfile fails
