### ISSUE TITLE
Edit (Cut, Copy, Paste) are always disabled for the standard editor

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-che/che#943]
The menu entries for cut and copy in edit menu are disabled although I have a character selection in the currently opened text editor. The actions seem to work for the selection in the package explorer only.

**Comment by ghost** [comment]
@svenefftinge Yes, these actions are intended to work for a project explorer. Shortcuts like Ctrl+C are more handy, aren't they?

**Comment by svenefftinge** [comment]
Sure, I am personally ok with this. :)
But I think this is not inline with common expectations.

**Comment by TylerJewell** [comment]
While not a bug since the behavior is as expected, I am labeling it this way since the common user will have a different expectation than what is provided.

**Comment by ddementieva** [comment]
https://jira.codenvycorp.com/browse/CHE-952

**Comment by vparfonov** [comment]
In normal behavior JS code don't have access to the clipboard
