### ISSUE TITLE
Root folder is not skipped when it is performed the 'Upload folder' 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#9430]
### Description
When I perform the _Upload Folder..._ with a selected checkbox _Skip the root folder of the archive_, then the root folder is not skipped   

**Reproduction Steps:**
* Select a project in the IDE
* Go to the _Project_ and select _Upload Folder.._
* Choose the archive project which has a root folder (e.g. 
[TestNG-Spring.zip](https://github.com/eclipse/che/files/2205447/TestNG-Spring.zip)

* Select the '_Skip the root folder.._' in the _Upload Folder_ form
* Perform the 'Upload Folder'

**Expected behavior:** 
* the root folder should be skipped

**Observed behavior:**
* the root folder is not skipped

**Che version**: 6.4.0
**OS and version:** Fedora 25
**Che install:** Docker/OCP
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Related selenium test: _UploadIntoProjectTest_ [_shouldUploadDirectorySkippingRoot_()]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![upload-folder-skip-root](https://user-images.githubusercontent.com/5408906/38776359-da6d80d8-409d-11e8-8fce-65564efec3f6.gif)

**Comment by vparfonov** [comment]
#11002
