### ISSUE TITLE
Allow consuming LS  functionality running as a sidecar in Theia base ide

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9441]
### Description
One of the major advantages of Workspace.Next concept would be an ability to select languages support as features. This LS are going to run as sidecars. We need to make sure that Theia based IDE is able to connect to this LS.

Related to https://github.com/eclipse/che/issues/8322

**Comment by tsmaeder** [comment]
What exactly is the problem that needs to be solved here?

**Comment by tsmaeder** [comment]
I really don't see that as a problem. If you look at theia/packages/java/src/node/java-contribution.ts, you can see that the plugin already uses a socket connection to the LS. All we have to do is read the URL from the machine configuration and not start a local process.

**Comment by skabashnyuk** [comment]
>All we have to do is read the URL from the machine configuration and not start a local process.

The problem is that someone has to implement it. The goal of this issue to make it work out of the box.

**Comment by tsmaeder** [comment]
Update on this one...what we would like to do is to find a way to reuse existing language server contributions with sidecars. This involves somehow enabling existing contributions to connect to a remote address or start a local language server process depending on some configuration.
This may be implemented by abstracting away the process of starting the language server and then provide local and remote implementations or by adding an if (local) {...} to existing language servers.
Whichever way we want to go, we need to change the language contribution API in Theia to allow this.

**Comment by amiramw** [comment]
@tsmaeder 
On Theia do you plan to have a dedicated LSP agent to communicate with the client? (which was done by the workspace agent)

**Comment by tsmaeder** [comment]
This issue has been superseded by the effort of running theia plugins in containers: we can just reuse the langauge plugins for theia and run them as a sidecar. Also, should solve the problem of running multiple LS instances if the plugin desires to to so.
