### ISSUE TITLE
Error logged in dev-machine window when changing a file of a freshly initialized git repo

### ISSUE THREAD

**Issue by ChristianSchenk711** [eclipse-che/che#9442]
### Description

When changing file in a freshly initialized git project, some errors are logged. 

### Reproduction Steps

- in Che 5.22.1 (actually tested on codenvy 5.22.1 on codenvy.io,  but the same error appears locally for Che 6.3.0 on my machine):
- create a workspace from the blank template
- create a project from the blank project template
- select the project and use "Git > Initialize Repository"
- open "README" in the text editor
- change the file a little bit (a few extra spaces, delete a few characters).

Now on the dev-machine console an error appears: 
[STDOUT] 2018-04-16 13:18:19,008[eWatcherService]  [ERROR] [o.e.c.a.git.GitChangesDetector 196]  - null

**Comment by eivantsov** [comment]
@ChristianSchenk711 cannot reproduce with the latest nightly. Are there maybe any additional steps to reproduce?

**Comment by ChristianSchenk711** [comment]
Just tested: still reproducible on 6.4.0 and nightly. I updated the description a little bit to avoid misunderstandings, but it's basically exactly like described there.

**Comment by ChristianSchenk711** [comment]
![exception](https://user-images.githubusercontent.com/28617133/39169835-8e7b1e26-4799-11e8-99d6-38ab22547890.gif)

**Comment by eivantsov** [comment]
@ChristianSchenk711 thanks. I was missing the last step :)
