### ISSUE TITLE
Commit time in Git reset widget may be incorrect in certain cases

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9444]
### Reproduction Steps
1. Create the php-simple-project from wizard
2. Git -> Reset. The commit time of first item: `2017 Mar 30 12:47:36`.
3. Check by console git that time is coincides with previews value.
4. Set the Time zone
5. Repeat the 2 step.
**Expected result:** The time values from console git and reset to commit widget should be the same
**Actual result:** The time is different
**OS and version:**  Chrome browser v. 63 Fedora 25, CHE 6.4.0 Snapshot

![selection_010](https://user-images.githubusercontent.com/1640058/38812485-0b561ae6-4195-11e8-900f-dbcab62528ac.png)

**Comment by SkorikSergey** [comment]
not actual
