### ISSUE TITLE
[Regression] The Debugger connection does not set for NodeJS projects

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9449]
Step to reproduce:
1 .Create `nodejs hello world project` from wizard 
2. Open app.js file and set breakpoint for 7 string
3. Launch debugger 
**Expected result:** The debugger connection should be set
**Actual result** We see notification with message like `Connetcting to /projects/nameofProject/app.js`. But connection is never end
**OS and version:**    
Chrome browser, che-6.4.0, 7d31a5aa24c4fc8f

**Comment by vparfonov** [comment]
Problems comes from this PR https://github.com/eclipse/che-dockerfiles/pull/173. 
Here we can to ways for fix it:
- like workaround in nearest sprint, we will fix output parsing according new nodejs version
- make NodeJs debugger stable to changes of this type (like node version upgrade) in future, we need to rework it totally according https://github.com/eclipse/che/issues/4720 but possibly it will take a lot of time.
@slemeur we need to you interaction here, what do you prefer?
