### ISSUE TITLE
Avoid "Contact support" wording in error messages

### ISSUE THREAD

**Issue by kartben** [eclipse-che/che#945]
**_1 Upvote**_ It's a bit confusing to stumble upon error messages asking to "contact support", when running OSS Che.
I think those error messages could be improved to point people to GH, or wherever you think support for Che "happens" :-)

``` shell
12:13 $ ack 'contact support' -i
core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiInfoService.java
79:            throw new ServerException("Unable read info about API. Contact support for assistance.");

plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java
323:            throw new MachineException("Machine creation failed. Snapshot state is invalid. Please, contact support.");

plugins/plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.properties
135:terminal.error.start=Cannot launch Terminal. Try re-starting current machine and contact support if Terminal keeps failing.

wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitProjectImporter.java
202:                    "or file system corruption. Please contact support for assistance.",
```

FWW, regarding the "Cannot launch terminal" error, my impression is this might be cause by a workspace machine not exposing port 4411, correct? so maybe that particular message could be changed in that direction?

**Comment by ghost** [comment]
It is Che that exposes 4411 port in a workspace container, so it is very unlikely that such a scenario is possible.

As to contacting support, good point. @TylerJewell what do you think?

**Comment by TylerJewell** [comment]
I agree.  Though it is better practice to not put any sort of reference to a support or issue management function from within an API error message such as this.

So in these four instances, we should remove the "Please contact support for assistance" statement, or make an appropriate statement.  We already make it clear in the product and online for how people can get help, so that should be sufficient.

**Comment by kartben** [comment]
+1. The fact that one will contact "support", whoever that is, is implicit for an OSS project.

**Comment by TylerJewell** [comment]
WE have scrubbed the error messages.  These should not exist anymore.  We will need to create separate issues if we uncover something.
