### ISSUE TITLE
Workspace Start/Stop failed while tomcat shutdown

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#9452]
### Description
All the service terminations are performed on container `@PreDestroy` and since the shutdown calls are not [ordered](https://github.com/eclipse/che/blob/2c2bd6637c8169018e2b33397f9d738bbf82a0b1/core/commons/che-core-commons-inject/src/main/java/org/eclipse/che/inject/lifecycle/Destroyer.java#L21) there is no guarantee that workspace service terminator will be the first one. So there are possible cases when e.g. [KubernetesClientFactory.cleanup()](https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java#L232) will be called first then workspaces might fail because all the connection to `OpenShift` will be closed.
As result, there is no guarantee that  user workspaces will be started or normally stopped while rolling updates of Che master.

**Comment by mshaposhnik** [comment]
Done, moved KubernetesClientFactory.cleanup() into separate termination instead of `@PreDestroy`.
