### ISSUE TITLE
Allow switching between KeycloakOAuthAuthenticationService and OAuthAuthenticationService in multi-user Che

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9461]
### Description
We would like to make multi-user che less coupled with Keycloak. To improve this situation we want to allow switching between  Keycloak based OAuthAuthenticationService and dedicated OAuthAuthenticationService.

**Comment by gazarenkov** [comment]
I am not an expert but IMO we considered Keycloak as a way for decoupling the things (it supposed to be highly pluggable).
What's the current plan?
To develop/use something even more abstract instead?

**Comment by skabashnyuk** [comment]
I guess Keycloak now is one of the possible components of infrastructure that is implementing OpenId protocol.

**Comment by garagatyi** [comment]
@gazarenkov we can not cover all the use-cases with the keycloak, e.g.
1. When someone doesn't want to use a keycloak at all
1. When Keycloak is present but it is unwanted to use it for OAuth token management for some reason

**Comment by gazarenkov** [comment]
@garagatyi it's clear and as I said I am quite neutral about this decision (same as used to be about decision to use Keycloak :) ).
Just would like to understand what we'll use instead as an a/a framework.

**Comment by garagatyi** [comment]
In case of OSIO, we still use Keycloak but need another OAuthAuthenticationService implementation to inject a Github token in che-starter.
