### ISSUE TITLE
Connection failed with terminal [SOLVED]

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#9464]
Each time I open my project I get this error. I'm behind the proxy which I denoted in the docker config files.

![screenshot from 2018-04-17 15-04-03](https://user-images.githubusercontent.com/5477699/38871292-b96a8426-4250-11e8-8961-791026b7d0f5.png)

![screenshot from 2018-04-17 15-09-18](https://user-images.githubusercontent.com/5477699/38872348-50383ca2-4253-11e8-8430-a293643a60e8.png)

![screenshot from 2018-04-17 15-21-51](https://user-images.githubusercontent.com/5477699/38872420-81d080f8-4253-11e8-88b8-d894c85ac7bd.png)

**Comment by eivantsov** [comment]
@kostiamol can you take a look at failed requests in your browser's dev console > network > ws?

**Comment by kostiamol** [comment]
@eivantsov Sure.
![screenshot from 2018-04-18 08-42-18](https://user-images.githubusercontent.com/5477699/38915734-1382734e-42e5-11e8-9e12-4a8dff9213fc.png)
![screenshot from 2018-04-18 08-43-02](https://user-images.githubusercontent.com/5477699/38915735-13a90950-42e5-11e8-9c23-74cdbf3a6c91.png)
![screenshot from 2018-04-18 08-43-16](https://user-images.githubusercontent.com/5477699/38915736-13d331ee-42e5-11e8-936b-74034e62e93b.png)

**Comment by eivantsov** [comment]
Anything in frames? Also what's the response code?

**Comment by kostiamol** [comment]
Is that what you meant?

![screenshot from 2018-04-18 09-09-30](https://user-images.githubusercontent.com/5477699/38916635-75162418-42e8-11e8-9427-608715a16b33.png)

**Comment by eivantsov** [comment]
@kostiamol you need to figure out why websocket connection fails. Probably because of proxy.

**Comment by kostiamol** [comment]
@eivantsov That's clear. If it's due to proxy, is there any way to fix the problem? Because I tried to set proxy configuration wherever it was possible.

**Comment by kostiamol** [comment]
I can create different projects. But when I try to execute a simple Go web-app - the error occurs on opening `preview:${server.8080/tcp}`

![screenshot from 2018-04-18 10-52-38](https://user-images.githubusercontent.com/5477699/38921838-fe396d64-42f6-11e8-8437-7eebf6e5e14c.png)

![screenshot from 2018-04-18 10-54-17](https://user-images.githubusercontent.com/5477699/38921840-fe7bdd5c-42f6-11e8-8939-c085b210fe19.png)

![screenshot from 2018-04-18 11-01-53](https://user-images.githubusercontent.com/5477699/38922249-077d8f8a-42f8-11e8-8c4a-361e0d7e72e7.png)

![screenshot from 2018-04-18 10-53-41](https://user-images.githubusercontent.com/5477699/38921863-0e54734c-42f7-11e8-89a8-35d1d9f2863f.png)

**Comment by eivantsov** [comment]
@kostiamol you need to add a server with port 8080

https://www.eclipse.org/che/docs/servers.html

**Comment by kostiamol** [comment]
@eivantsov I've added a server.

![screenshot from 2018-04-18 13-51-51](https://user-images.githubusercontent.com/5477699/38930324-cb38713a-430f-11e8-8fd1-855257ca8a74.png)

Eclipse mapped  port 8080 to 32791.

![screenshot from 2018-04-18 13-52-01](https://user-images.githubusercontent.com/5477699/38930397-0aec5706-4310-11e8-9532-e77868acdfa9.png)

![screenshot from 2018-04-18 13-54-53](https://user-images.githubusercontent.com/5477699/38930459-3ed590dc-4310-11e8-83a2-4427ab00a564.png)

I used the link for preview but address resolution has failed. The system thinks that my localhost address is external?

![screenshot from 2018-04-18 13-57-36](https://user-images.githubusercontent.com/5477699/38930568-a1e4b9fa-4310-11e8-8417-b67a2923ffb4.png)

**Comment by eivantsov** [comment]
@kostiamol to solve this you do not even need Che.

Just run any Docker container and try to access your webapp using the URL that you use to access Che.

**Comment by kostiamol** [comment]
@eivantsov I pulled the alpine image, installed curl and executed the command in the container, that was run with proxy as an env variable. The result is the same. Does it mean that the problem is docker proxy configs? But if it's true, I don't know... I tried to put the proxy info wherever it's possible.

**Comment by kostiamol** [comment]
I found the problem. It turned out that I used proxy not only for http and https, but also for sockets. So I deleted corresponding env variable and everything is ok now.
