### ISSUE TITLE
Current FileTypeRegistry does not properly support Language Servers

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#9465]
Right now client-side `FileTypeRegistry` and `FileType` architecture does not suit language servers requirements. Especially if we're focusing on making workspace configuration self-sufficient to use language servers.  According to the [LSP specification](https://microsoft.github.io/language-server-protocol/specification) `TextDocumentItem` requires language id:
```typescript
interface TextDocumentItem {
	/**
	 * The text document's URI.
	 */
	uri: DocumentUri;

	/**
	 * The text document's language identifier.
	 */
	languageId: string;

	/**
	 * The version number of this document (it will increase after each
	 * change, including undo/redo).
	 */
	version: number;

	/**
	 * The content of the opened text document.
	 */
	text: string;
}
```

So we have to provide it in the configuration of a workspace and pass it to the client to register corresponding `FileType`. 

While `FileType` has no field to represent language id, it (file type) is associated with language id through `LanguageServerRegistry`. Such complex and stale mechanism rises several problems: the first one - similar or exactly the same `FileType` may be already registered on client through its own ways and there is no clear workflow on how to resolve the collision, the second - several language servers may be configured for a single language (multi-language server case) and again no appropriate way to deal with it. Saying no clear workflow I mean client typing system was not initially designed for such situations and there is no clear technical way and no clear vision at the moment how that can be overpassed.

Currently, it seems like it works more or less satisfying, mostly because we do not heavily use multi-language server setups. However, I'm afraid that actual behavior in those cases is unpredictable and it is highly likely that we will have issues sooner or later.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/10)
