### ISSUE TITLE
Implement launching plugins from defined place

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9476]
There is need to launch the list of plugins, that are located in defined place. For now, as the first step, we do not care how plugins appear in that location, the task is to configure that location and implement running those plugins. 
Steps are the following:
- [x] Read the plugins list
- [ ] Handle the versions conflict by taking the latest version
- [x] Create service or extend existing to provide the list of already installed plugins
- [x] Run installed plugins in new worker and/or new node instance

**Comment by benoitf** [comment]
I may work on this part next week, let me know if it's an issue ?

**Comment by ashumilova** [comment]
@benoitf yes, sure, would be great!
