### ISSUE TITLE
Remove SSH info from IDE UI for OpenShift

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#9488]
### Description
You cannot SSH into a pod in OpenShift (you have to use `oc rsh` or `oc rsync` instead). As a result, the SSH info that's presented in the UI should be hidden as it's misleading. We have already hit this issue with a large OpenShift user.

**Type and version:** Che 6.x on OpenShift

**Comment by bmicklea** [comment]
@eivantsov please add any details you feel are necessary to the description.

**Comment by gorkem** [comment]
Closing as Che 6 editor is not under active development and I think this was fixed
