### ISSUE TITLE
Parametrize keycloak admin user in templates

### ISSUE THREAD

**Issue by siamaksade** [eclipse-che/che#9489]
The KeyCloak admin user and password is hard-coded to `admin` in the templates:
https://github.com/eclipse/che/tree/master/deploy/openshift/templates

They should become template parameters.

**Comment by eivantsov** [comment]
@siamaksade they are hardcoded but in jsons here - https://github.com/eclipse/che/tree/master/dockerfiles/init/modules/keycloak/templates

Env variables are ignored in this case. I'll issue a PR to fix it. Thanks for the pointer.

**Comment by siamaksade** [comment]
Slight relevant to this, the `CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD` template param should only be in the keycloak template. It's not used in [Che template](https://github.com/eclipse/che/blob/master/deploy/openshift/templates/che-server-template.yaml)

**Comment by eivantsov** [comment]
@siamaksade it is not use din Che template. Not sure I understand your comment.

**Comment by eivantsov** [comment]
Closing this issue as the original request was addressed in a merged PR. @siamaksade feel free to open a separate issue related to your another concern.
