### ISSUE TITLE
SecurityException !!

### ISSUE THREAD

**Issue by ayedhedi** [eclipse-che/che#949]
**Che Version**: 4.0.1
**OS**: Mac OSX El Capitan 10.11.3
**Java Version**:  1.8.0_73
**Docker version** : 1.10.3, build 20f81dd
**VirtualBox**: Version 5.0.16 r105871

I'm getting this logs: 

[logs.txt](https://github.com/eclipse/che/files/197831/logs.txt)

Thanks to help.

**Comment by eivantsov** [comment]
Hello

You have downloaded binaries rather than compiled Che yourself? What version?

**Comment by ayedhedi** [comment]
Hello,

Thanks for your answer. 

Yes I have downloaded the binary version 4.0.1.

**Comment by ghost** [comment]
Yes, issue confirmed. Investigating.

**Comment by ghost** [comment]
Can you give it a try with this one? https://install.codenvycorp.com/che/eclipse-che-latest.zip

**Comment by ayedhedi** [comment]
Good, this version works correctly no **Exceptions** and I can now get access to the dashboard. 
thanks.

**Comment by Marcosdg3** [comment]
The latest works for me as well :+1:

**Comment by ghost** [comment]
Updated all of the links. Should be ok now.
