### ISSUE TITLE
Servers checkers won't be started if a workspace is started by another Che Server instance

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#9502]
### Description
Servers checkers won't be started if a workspace is started by another Che Server instance.

Note that it will affect a user only if there is STARTING workspace during Rolling Update and one of the following workspace servers failed: exec-agent, terminal, ws-agent. 

One of the possible solutions is to implement distributed messaging service and start servers checkers when workspace becomes `RUNNING`.

### Reproduction Steps
1. Start a workspace with a non-pulled image.
2. Start a rolling update.
3. Wait until Che Server will be updated and the workspace will be started.
4. Open a terminal and execute `/home/user/che/workspace-agent/bin/catalina.sh stop`.
5. Wait a period of scheduling servers checkers (default value: 1 minute).

Expected: IDE shows that workspace agent is stopped and asks to restart a workspace.

Actual: Workspace agent is stopped but IDE doesn't show the corresponding dialog. Workspace API responds that `ws-agent/http` is `RUNNING`.

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
Our goal, for now, is to cover "Hot update use case" https://github.com/eclipse/che/issues/8547. That means that we can add a periodical job that will try to find missing workspaces and start server checkers.
