### ISSUE TITLE
Che compile error

### ISSUE THREAD

**Issue by james10174** [eclipse-che/che#951]
I get an error compile from git with the goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:compile (default) on project assembly-ide-war: Command

[https://codedump.io/share/Iodp8Q5iJDDk/1/che-compile-error](url)

**Comment by TylerJewell** [comment]
That error link doesn't work. But are you building on windows?

If so, in the repository readme, there is a comment:

```
# Windows: maven-patch-plugin does not work, so skip tests when building:
# See: https://maven.apache.org/plugins/maven-patch-plugin/faq.html#Why_doesnt_this_work_on_Windows
`mvn -DskipTests=true -Dfindbugs.skip=true  -Dskip-validate-sources clean install`
```

**Comment by ghost** [comment]
`[INFO] java.lang.OutOfMemoryError: unable to create new native thread` says it all. How much RAM do you have? Btw, you may just compile assembly-main module to skip GWT compilation. ide.war will be downloaded from Che public Maven repo.

**Comment by james10174** [comment]
@eivantsov Memory was the problem. Nothing like building che using che ;) the VirtualBox Manager ran out of memory. I increase available ram in the manager settings and it compiled.
