### ISSUE TITLE
Newer version of PHP LS available

### ISSUE THREAD

**Issue by SpicySpaceman** [eclipse-che/che#9510]
### Description
There is a newer version (5.4.0) of the PHP LS available (https://github.com/felixfbecker/php-language-server/releases/latest)
Currently Che uses 5.3.7.
Would be awesome if guys could update to the newest version.

**Version:** 6.4.0

**Comment by eivantsov** [comment]
@danidoedel thanks for the pointer. Will test and update if everything is fine.
