### ISSUE TITLE
Performance improvement for large npm install project

### ISSUE THREAD

**Issue by ESTrainer** [eclipse-che/che#9511]
### Description
npm install on a large project in free workspace of online eclipse che is taking longer time. Wondering if there is anything that can be tuned to improve the speed. 

### Reproduction Steps
take a large node project and run `npm install` and measure the time between cloud eclipse che and local docker.
**OS and version:**    
Cloud Eclipse Che
**Diagnostics:** 

What is the underlining storage used in the cloud? Was it SSD? If not do we have option to select the type of storage in the cloud. Also, is it possible to have underlining storage to be on NFS so we can share between projects.

**Comment by eivantsov** [comment]
@ESTrainer do you have any observations on your side? Since npm install downloads and saves artifacts, network and disk are two major factors here.

**Comment by eivantsov** [comment]
Closed due to inactivity
