### ISSUE TITLE
Example dashboard plugin

### ISSUE THREAD

**Issue by ThomasDeLetter** [eclipse-che/che#9512]
I have been able to make a custom Che extension and building a custom assembly. 

My current project looks a lot like this example: https://github.com/che-samples/che-ide-server-extension

However, I can't find any docs or exampes on how to extends the **dashboard**. 
Is the dashboard also GWT? Do I have to add another assembly module to my project?

Can you guys help me?

Thanks!

**Comment by ThomasDeLetter** [comment]
Thanks for you answer.

Is there and example that shows how to extend the dashboard? Do i need to copy the full source code of che/dashboard?

**Comment by eivantsov** [comment]
@ThomasDeLetter it does not look like dashboard is smth hat supports pluggable plugins. So, you need to copy source code to your assembly. I'll be happy to be wrong - @ashumilova can you confirm?

**Comment by ashumilova** [comment]
@ThomasDeLetter there is really no plugin system designed in dashboard.
