### ISSUE TITLE
It is possible to create a workspace with project which has no name, or it has a special characters in the name

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9518]
### Reproduction Steps
 - Open "Dashboard" and go to "New Workspace" page
 - Select "Java" stack
 - Click on the "Add or Import Project"
 - Select and add "web-java spring" project
 - In the opened form set cursor to the "Project Name" field and clear it
 - Pay attention that error tip is displayed but "Cancel" and "Add" buttons are still available
 - Click on the "Save" button
 - Pay attention that project name is not displayed in the project tab
 - Click on "Open in IDE" button
 - Pay attention to stack trace in terminal

**Attachments:**
![dssdsfsfs](https://user-images.githubusercontent.com/22724619/39119090-adf956d8-46f3-11e8-979e-83df36297ff1.png)

![gghtrd](https://user-images.githubusercontent.com/22724619/39119099-b5ba4562-46f3-11e8-9f5b-065ba043eae9.png)

**OS and version:**   
Che 6.5.0 ; Fedora 25 ; Chrome 63.0

**Comment by SkorikSergey** [comment]
Still actual for CHE ver.  6.5.0.

**Comment by Ohrimenko1988** [comment]
Fixed
