### ISSUE TITLE
Java auto completion: show content assist automatically does not work

### ISSUE THREAD

**Issue by hxssgaa** [eclipse-che/che#9519]
### Description
For now, Eclipse Che use ctrl+space or "Content Assist" from the menu to trigger the code completion. But for users who are getting used to platforms like Intellij IDEA, it's just uncomfortable to use short cuts to trigger the code completion.

Another problem is that when user inputs "<", it would always follow the ">". But it's not always the right case, for example, user wants to input "<=" less equals. 

It would be great to automatically trigger the code completion when detecting  user editing types or "." to trigger methods or something like that, and make some enhancements to resolve the correct code completes case.

### Reproduction Steps
Must use ctrl+space or "Content Assist" from the menu to trigger the code completion, can't trigger the code completion automatically like Intellij IDEA does.

In Java project, when inputting "<" would always follow the ">" regardless case like "<=".

**OS and version:**    
Mac OS X 10.12 sierra, Eclipse Che 6.4

**Diagnostics:**

**Comment by eivantsov** [comment]
@hxssgaa 

1. Do you expect content assist to pop up as you type?


2. Take a look at settings
![image](https://user-images.githubusercontent.com/5337267/39125852-20c275b8-4709-11e8-8e2e-6ca7de6de990.png)

**Comment by hxssgaa** [comment]
@eivantsov Yes, but the setting doesn't work unless I invoke the content assist with ctrl+space. I expect it to pop automatically based on the context, for example, it would be better if the content assist automatically show when typing “.” to get available methods. Currently any content assist must start with ctrl+space or "Content Assist" from the menu.

**Comment by tsmaeder** [comment]
Merging jdt.ls should fix this. Let's not waste time on code that will disappear.
