### ISSUE TITLE
ERROR: for che  no such image [SOLVED]

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#9520]
I didn't figure out how to update che so I decided just to remove old images and download the new ones. But when I tried to run eclipse I get this error:

ERROR: for che  no such image: sha256:8fad10168b410419da8aa6620f21f0c99536abe19a5534ce7769b65b0b38f0c9: No such image: sha256:8fad10168b410419da8aa6620f21f0c99536abe19a5534ce7769b65b0b38f0c9
Encountered errors while bringing up the project.
ERROR: Error during 'compose up' 

![screenshot from 2018-04-23 13-54-48](https://user-images.githubusercontent.com/5477699/39125078-1d452f58-46fe-11e8-8c10-f1ba9423374a.png)

**Comment by eivantsov** [comment]
@kostiamol can you give it a try with `--pull`?

**Comment by eivantsov** [comment]
https://stackoverflow.com/questions/37454548/docker-compose-no-such-image

Can you try deleting all containers?

`docker rm -f $(docker ps -aq)`

**Comment by kostiamol** [comment]
I knew about that option but I had some important for me containers so I used command `docker rmi $(docker images | grep "^eclipse/" | awk "{print $3}")`. It seemed that I deleted all the unnecessary images. But only after running `docker rm -f $(docker ps -aq)` everying is again ok. Thanks.
