### ISSUE TITLE
OpenShift/K8S: Cannot add a new stack with dockerimage recipe type

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9523]
Steps to reproduce:

1. On OpenShift or Kubernetes, login as admin or create a user, go to stacks
2. Click Add stack
3. The page shows that recipe is docker image.
4. Try to create one with existing docker image or a custom one
5. Dashboard converts it to composefile.

![image](https://user-images.githubusercontent.com/5337267/39137261-dbdf98be-4725-11e8-8fad-43879d7296b3.png)

**Comment by SkorikSergey** [comment]
Still actual for CHE ver.  6.5.0.

**Comment by SkorikSergey** [comment]
Failed selenium test - **StacksListTest**.
