### ISSUE TITLE
Recreate Hot Update

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9528]
### Description
We want to introduce "Recreate Update" before "Rolling Update". 
We saw some instability of che-master during - Hot update testing on working master | #9415 
As part of this issue should and documentation how to do Recreate Hot Update on OpenShift

**Comment by mshaposhnik** [comment]
How to perform Recreate type update without stopping active workspaces:

0) Make sure deployment update strategy set to `Recreate`
1) Make `POST` request to the system api to start WS master suspend `/api/system/stop` 
(means that all new attempts to start workspaces will be refused, and all current starts/stops will be finished).  Note that this method requires system admin credentials.
2) Make periodical `GET` requests to `/api/system/state` api, until it returns `READY_TO_SHUTDOWN` state. Also, it may be visually controlled by line "System is ready to shutdown" in the server logs
3) Perform new deploy.
