### ISSUE TITLE
Macro for selected files in the project explorer

### ISSUE THREAD

**Issue by dhuebner** [eclipse-che/che#953]
It would be handy to have a macro that points to the current selected file (multiple files could be separated by a comma) in the package explorer:

e.g. ${explorer.selected} 

https://eclipse-che.readme.io/docs/commands#macros

**Comment by TylerJewell** [comment]
It seems that the initial set of command macros that have been provided are somewhat limited right now.  Let's go ahead and define a wider list of macros for inclusion.

```
${current.project.file} -- Currently selected file
${current.project.path}  -- Absolute path to the selected file
${current.project.relpath} -- Path relative to the /projects folder
${server.port.<port>} -- Returns protocol, hostname and port of a service registered with an EXPOSE port
${server.port.<port>.protocol} -- Returns protocol of a service registered with an EXPOSE port
${server.port.<port>.hostname} -- Returns hostname of a service registered with an EXPOSE port
${server.port.<port>.port} -- Returns port of a service registered with an EXPOSE port

** Note that <port> is the port that is exposed by the Dockerfile provided by the user.  But the port returned is the ephemeral port assigned by Docker to that server.
```

**Comment by juampe** [comment]
If this is implemented, will be a big ergonomic enhancement for language scripting users

command: cd /projects/python && PYTHONUNBUFFERED=1 python ${current.project.file}
/bin/bash: ${current.project.file}: bad substitution

**Comment by TylerJewell** [comment]
@juampe - we are going to include the analysis and implementation of many of these into our next sprint.

**Comment by gazarenkov** [comment]
better
${server.<ref>} -- Returns server by ref name and so on

**Comment by TylerJewell** [comment]
Proposed new specification:

```
${current.project.file} -- Currently selected file
${current.project.path}  -- Absolute path to the selected file
${current.project.relpath} -- Path relative to the /projects folder
${server.<port>} -- Returns protocol, hostname and port of an internal server
${server.<port>.protocol} -- Returns protocol of a service registered with an EXPOSE port
${server.<port>.hostname} -- Returns hostname of a service registered with an EXPOSE port
${server.<port>.port} -- Returns port of a service registered with an EXPOSE port
${server.<ref>} -- Returns protocol, hostname and port of an internal server
${server.<ref>.protocol} -- Returns protocol of a server registered by name
${server.<ref>.hostname} -- Returns hostname of a server registered by name
${server.<ref>.port} -- Returns port of a server registered by name
```

**Comment by sunix** [comment]
Hi,
Selected files in the the explorer and active open file in the editor are not the same. Should we have 2 different macros for these ?
Also, we should keep ${current.class.fqn} which is very useful for java project.

**Comment by TylerJewell** [comment]
Sure - please propose a syntax that makes sense given the specification above.

**Comment by gazarenkov** [comment]
```
${server. <port>.*} 
AND
${server. <ref>.*} 
```

wont work together (no chance to resolve), lets remove `server.<port>.*` option

**Comment by gazarenkov** [comment]
For a subject - yes, It is 2 different areas - editor and tree, so I think it should be like:

```
explorer.selected.* 
editor.current.*
```

**Comment by vzhukovskii** [comment]
@gazarenkov as for `explorer.selected.*`.
If multiple files is selected, what should we return after replacing the macro? Last selected file?

**Comment by TylerJewell** [comment]
Updated syntax.  @vzhukovskii - also since we are renaming some existing parameters, please still support the OLD parameters so that upgrades will not have migration issues.

```
${editor.current.file.name} -- Currently selected file in editor with context
${editor.current.file.path}  -- Absolute path to the selected file in editor with context
${editor.current.file.relpath} -- Path relative to the /projects folder in editor with context
${editor.current.project.name} -- Project name of the file currently selected in editor with context
${editor.current.project.type} -- Project type of the file currently selected in editor with context
${explorer.current.file.name} -- Currently selected file in project tree
${explorer.current.file.path}  -- Absolute path to the selected file in project tree
${explorer.current.file.relpath} -- Path relative to the /projects folder in project tree
${explorer.current.project.name} -- Project name of the file currently selected in explorer
${explorer.current.project.type} -- Project type of the file currently selected in explorer
${server.<name>} -- Returns protocol, hostname and port of an internal server
${server.<name>.protocol} -- Returns protocol of a server registered by name
${server.<name>.hostname} -- Returns hostname of a server registered by name
${server.<name>.port} -- Returns port of a server registered by name
${workspace.name} -- Returns the name of the workspace
${host.name} -- Returns the hostname of the underlying OS running Che native or its Docker daemon.
${host.ip} -- Returns the IP address of the underlying OS running Che native or its or Docker daemon.
```

**Comment by vzhukovs** [comment]
@TylerJewell as for:

```
${explorer.current.project.file} -- Currently selected file in project tree
${explorer.current.project.path}  -- Absolute path to the selected file in project tree
${explorer.current.project.relpath} -- Path relative to the /projects folder in project tree
```

what should we provide if we'll have more than one selected file?

**Comment by TylerJewell** [comment]
Provide comma separated list of all files selected.

**Comment by TylerJewell** [comment]
@ashumilova - a customer today asked for the ability to configure a custom working directory for commands of a custom type.  We provide this field for maven commands, but not custom commands.  Is there value in adding this?

**Comment by TylerJewell** [comment]
@ashumilova @vzhukovskii - can you talk about where this issue is in the priority list for the upcoming sprints?  We are coming up with additional macros - that each show some simple stuff.  So want us to think about when this gets scheduled.

**Comment by JamesDrummond** [comment]
@vzhukovskii Commit today without the following.
${host.name} -- Returns the hostname of the underlying OS running Che native or its Docker daemon.
${host.ip} -- Returns the IP address of the underlying OS running Che native or its or Docker daemon.

Discuss with Tyler later on how to do the above removed items.

**Comment by ashumilova** [comment]
Added issue for host macros - https://github.com/eclipse/che/issues/2230
