### ISSUE TITLE
Build node JS application with Webpack dev server in Eclipse Che

### ISSUE THREAD

**Issue by ShagunBhatt** [eclipse-che/che#9534]
I am trying to build Node JS application in Eclipse Che.
Default Node stack of Eclipse Che has been used and an application has been imported in the workspace.

Application has been successfully deployed and is available on : http://localhost:5000.
It has been verified through Che terminal by running below command :
elinks http://localhost:5000

Issue : I am unable to access this application in the browser's new tab[from windows machine.] using URL given by PreviewURL[Macro used : ${server.5000/tcp] .
However, if application is deployed using http-server, i am able to access the application using below URL with ephemeral port : http://172.30.65.138:32783/
Cannot get the same result in case of webpack-dev-server development mode.
Is there any other configuration required for webpack-dev-server in Eclipse Che ? As, in linux machine, it is successfully deployed.
Help will be highly appreciated.

**OS and version:**    
Eclipse Che Version: 6.0.0
OS : Cent OS 7

**Comment by eivantsov** [comment]
You probably need to specify host for your app as `0.0.0.0`

**Comment by ShagunBhatt** [comment]
I have also tried as suggested.
In the "webpack.dev.js", i have added host like this : 
 devServer: {
      historyApiFallback: true,
      host:'0.0.0.0',
      stats: 'minimal',
      port: 3000
    }
When app is build, it gives a URL : http://0.0.0.0:3000/HTML5Ext/ which is unreachable.
Also , if i click "servers" tab, and then use the URL provided by Ecipse Che containing ephemeral port for 3000 port, it says invalid host reader "http://172.30.65.138:32796/". 

On going by some links, i found , i should use webpack-dev-server 4.2 version.
On downgrading , i was able to access my application from outside environment.

It will be helpful if you explain, why adding host to 0.0.0.0 resolves it.

**Comment by eivantsov** [comment]
@ShagunBhatt usually when the server is bound to localhost it accepts local connections only. When the app runs in a container, you access it using a non localhost URL.

**Comment by ShagunBhatt** [comment]
Thanks for the explanation. @eivantsov . It was helpful.
