### ISSUE TITLE
Kubernetes deployment with single port?

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#9535]
In docker multi user setup it is possible to run Che in a single-port mode using the environment variable ``` CHE_SINGLE_PORT=true ```.

Is the same possible for a kubernetes setup I've gotten running?  Also, does it require a re -setup or can the same deployment be updated from a configmap value change?

**Comment by eivantsov** [comment]
@mjshashank for Kubernetes ingress is used to expose services. In case of SINGLE_PORT on Docker it's traefik that does routing, in case of Kubernetes it's Nginx.

Have you checked installation docs?

**Comment by mjshashank** [comment]
Okay, makes sense.

But in the case of Nginx Controller in Kubernetes, are the other ports and workspace ports (like server ports, terminal websocket ports etc) still exposed to the outside world like in the case of Docker?

**Comment by eivantsov** [comment]
No, those ports are exposed via ingress.

**Comment by mjshashank** [comment]
Ah, my bad, understood now. Thanks.
