### ISSUE TITLE
Several "dev-machine" are created after several changes the name in the "Edit the machine" form

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9537]
### Reproduction Steps
 - Create workspace by default "Java" stack and "web-java-spring" project
 - Go to the "Workspaces"
 - Find created workspace in the list and click on it (The "workspace details" page should be opened)
 - Click on the "Machines" button
 - Click on the "Edit" button
 - In the opened "Edit the machine" form st cursor to the "Name" text field
 - Append "1" digit to the existing name 
 - Wait until "Save" button is enabled
 - Clear "1" digit and wait until "Save" button is disabled
 - Append "2" digit to the existing name 
 - Wait until "Save" button is enabled
 - Clear "2" digit and wait until "Save" button is disabled
 - Append "3" digit to the existing name 
 - Wait until "Save" button is enabled
 - Clear "3" digit and wait until "Save" button is disabled
 - Append "4" digit to the existing name 
 - Wait until "Save" button is enabled
 - Clear "4" digit and wait until "Save" button is disabled
 - Append "5" digit to the existing name 
 - Wait until "Save" button is enabled
 - Click on the "Save" button
 - Pay attention to the count of items in the list

**Attachment:**
![screencast-3](https://user-images.githubusercontent.com/22724619/39242805-0d87bdf0-4894-11e8-98f9-8c870660e801.gif)

**OS and version:**    
Che 6.5.0 ; Fedora 25 ; Chrome 63.0

**Comment by SkorikSergey** [comment]
Still actual for CHE ver.  6.5.0.

**Comment by Ohrimenko1988** [comment]
Fixed
