### ISSUE TITLE
Commands API for Workspace.Next

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#9546]
### Description
In workspace next when a client starts a workspace, with current API definitions, it’s complicated to retrieve the full list of commands, in particular, the commands defined at a service level.
A client has to get features, then services from these features, eliminate duplications, get all the commands from all the containers in services, match them with machines. After that, it can use it for commands execution UI. 
This approach is too complicated. We should consider changes in the APIs that would simplify it dramatically. 
Possible solutions are:
- add commands list to the workspace runtime. Then workspace strat flow can add commands from features to the appropriate machine
- create new Command API that would allow fetching commands by workspace/machine/etc.

**Comment by eivantsov** [comment]
@garagatyi is this an epic? If so please label it accordingly. Thanks

**Comment by garagatyi** [comment]
I'm not sure whether this is an epic. AFAIK we haven't discussed what has to be done with commands in Workspace NEXT, so can't say whether it is something like an epic or a regular task.

**Comment by l0rd** [comment]
@garagatyi does this issue still makes sense?

**Comment by garagatyi** [comment]
I'm OK with either way because I don't have strong opinion on that at the moment.

**Comment by garagatyi** [comment]
Feel free to use this issue for the scope you are tackling.

**Comment by sleshchenko** [comment]
Now `Workspace#Runtime#getCommands` returns commands list which contains: commands from workspace config, commands from plugins. Also, command in workspace config may be configured to be executed in plugin's container, the `plugin` attribute should be specified and the format of the value is `{pluginId}:{pluginVersion}`, like "che-machine-exec-plugin:0.0.1". The Che Server will resolve `machineName` that belongs to a specified plugin. Example:
WorkpaceConfig
```json
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      ...
    }
  },
  "projects": [],
  "name": "che7",
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1"
  },
  "commands": [
    {
      "commandLine": "echo Hello From Exec Plugin",
      "name": "hello-plugin",
      "attributes": {
        "previewUrl": "",
        "goal": "Build",
        "plugin": "che-machine-exec-plugin:0.0.1"
      },
      "type": "mvn"
    },
    {
      "commandLine": "echo Hello From Runtime",
      "name": "hello-runtime",
      "attributes": {
        "goal": "",
        "previewUrl": ""
      },
      "type": "custom"
    }
  ]
}
```
Runtime
```json
{
  "machines": {
    "ws/theia-ide": {
         ...
      },
      "status": "STARTING"
    },
    "ws/che-machine-exec": {
      "servers": {
        "che-machine-exec": {
          "url": "ws://routeyjs82ne2-eclipse-che.192.168.0.108.nip.io",
          "attributes": {
            "type": "terminal",
            "internal": "false"
          },
          "status": "UNKNOWN"
        }
      },
      "status": "STARTING"
    }
    ...
  },
  "warnings": [],
  "activeEnv": "default",
  "commands": [
    {
      "commandLine": "echo Hello From Runtime",
      "name": "hello-runtime",
      "attributes": {
        "goal": "",
        "previewUrl": ""
      },
      "type": "custom"
    },
    {
      "commandLine": "echo Hello From Exec Plugin",
      "name": "hello-plugin",
      "attributes": {
        "goal": "Build",
        "previewUrl": "",
        "plugin": "che-machine-exec-plugin:0.0.1",
        "machineName": "ws/che-machine-exec"
      },
      "type": "mvn"
    }
  ],
  "machineToken": "...",
}
```

**Comment by sleshchenko** [comment]
A separate issue is created for IDEs adaptation https://github.com/eclipse/che/issues/12053

**Comment by garagatyi** [comment]
@sleshchenko thanks for the JSON!
