### ISSUE TITLE
http/https proxy ENV in helm chart

### ISSUE THREAD

**Issue by bcg62** [eclipse-che/che#9549]
currently it looks like there's no way to apply proxy settings, or additional env vars in general to the deployment.

simple things like:
`command: ["sh", "-c", "apk --no-cache add curl....` will fail in a cluster that does not have direct internet access

**Comment by artaleks9** [comment]
Still actual for ver.6.6.0

**Comment by slemeur** [comment]
@eivantsov : I think you have a way to handle this. As this been added to the documentation?

**Comment by eivantsov** [comment]
@slemeur no, not in docs yet. It felt somewhat wrong to document it, so I hoped some automation on server side is possible.

**Comment by eivantsov** [comment]
So, this is both a docs and eng task.

As the moment, the following envs work for Docker infra only:

```
CHE_WORKSPACE_HTTP__PROXY
CHE_WORKSPACE_HTTPS__PROXY
CHE_WORKSPACE_NO__PROXY
```
We need env provisioners for them. Once done, I can summarize in docs all the proxy envs that a user might need.

**Comment by eivantsov** [comment]
Will be fixed by https://github.com/eclipse/che/pull/10387
