### ISSUE TITLE
How to use sprotty to visualize XText language server which is already integrated with Theia?

### ISSUE THREAD

**Issue by ShivaniBali** [eclipse-che/che#9550]
Hi there,

I am successful in integrating my DSL language server with Theia, but now I would like to use sprotty to visualize the content.

I have gone through one example online: https://github.com/theia-ide/theia-sprotty-example

It executes well, but not clear how one can use sprotty with (XText LSP into Theia).

I would appreciate your inputs.
Thanks!

**Comment by eivantsov** [comment]
@ShivaniBali you should perhaps open an issue in Theia repository since Che community and can be most efficient when answering questions related to Che-Theia integration.
