### ISSUE TITLE
Kubernetes: Cannot create workspace with multi-machine setup (compose type)

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#9551]
### Description

I've setup Che on kuberenetes and everything seems to be working fine except when I try to create a workspace withe a multi-machine setup using a docker-compose recipe.

### Reproduction Steps

1. Open Dashboard in Eclipse Che running on kubernetes.
2. Select create workspace, choose Java-MySQL multi-machine stack and click create.

It throws an error saying InternalEnvironmentFactory is not configured for recipe type: 'compose'

**OS and version:**
 
version: Che-nightly

![screenshot from 2018-04-27 11-24-56](https://user-images.githubusercontent.com/16825130/39347084-db71601a-4a0e-11e8-8c28-72ff919dd518.jpg)

**Comment by eivantsov** [comment]
@mjshashank docker compose isn't yet supported on OpenShift and Kubernetes infras. I'm sure there's an issue for that, but I cannot find it now.

**Comment by skabashnyuk** [comment]
https://github.com/eclipse/che/issues/7860

**Comment by eivantsov** [comment]
Closing the issue. Follow https://github.com/eclipse/che/issues/7860
