### ISSUE TITLE
Debugger: Connection refused [SOLVED]

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#9552]
I'm trying to debug Java project locally but eclipse says that connection is refused. Should I manually open any ports or what the reason?

![screenshot from 2018-04-27 09-21-32](https://user-images.githubusercontent.com/5477699/39349870-c7791b64-49fc-11e8-8ed0-88af32a87a86.png)

![screenshot from 2018-04-27 09-21-12](https://user-images.githubusercontent.com/5477699/39349869-c75215e6-49fc-11e8-8649-28f3bd632e06.png)

![screenshot from 2018-04-27 09-52-32](https://user-images.githubusercontent.com/5477699/39351132-d21bf3d0-4a00-11e8-9f72-a9763177f39b.png)

**Comment by eivantsov** [comment]
@kostiamol have you started your app in a debug mode so that it listens on 8000?

**Comment by kostiamol** [comment]
@eivantsov I created new debug command set:
```
mvn clean install
java -jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y ${current.project.path}/target/*.jar
```
executed it (with errrors) and started debugging with Run-Debug-Debug... and now it works.

![screenshot from 2018-05-02 14-07-50](https://user-images.githubusercontent.com/5477699/39522712-6154a3ba-4e13-11e8-84f9-599f46031c5c.png)
