### ISSUE TITLE
[OpenShift Origin] Failed start of workspace when tests run on CI job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#9556]
### Description
* _We have unexpected failed start of workspace when tests run [on CI on ocp-platform](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp)_
* _The reason of it - the workspace does not start_

**Che version:** 6.5.0
**OS and version:** Fedora 25
**Che install:** OCP (single/multi)
**Performance info**: we are running 3 Che workspaces in parallel on server with CPU 4 cores, 30.5G RAM

**Additional information:**
* Related selenium test: _it may be any test_
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* There maximum time of Che workspace startup lasted about 4 minutes compare to 8 minutes of timeout error
* Decreasing the number of test threads from 3 to 2 (that is equal to 50% of CPU cores) helped to almost prevent such an error on CI job https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/ 
* See the attachment:
**_Che version 6.5.0_ (_Waiting for Kubernetes environment 'ws-name' of the 'ws-id' reached timeout_):**
![ocp-ws-start-failed-2](https://user-images.githubusercontent.com/5408906/39289174-a9a67fd8-4933-11e8-8c5d-9d807cd62d3f.png)

**Another example:**
- [che-server-pod.log](http://tests.codenvycorp.com/selenium_test_report_data/9659/che_server_logs/che-server-pod.log)
- [ocp-events.log](http://tests.codenvycorp.com/selenium_test_report_data/9659/che_server_logs/ocp-events.log)

**Comment by riuvshin** [comment]
@artaleks9 can you please try to find out when that kind of issues appeared first time.

**Comment by artaleks9** [comment]
Today 11 May,  we again have fail tests on the ocp-single CI job.
I attach the archive of the _ocp_logs_ folder:
[ocp_logs.zip](https://github.com/eclipse/che/files/1994663/ocp_logs.zip)

**Comment by dmytro-ndp** [comment]
@riuvshin: we can be more precise if you can grep in directory `http://tests.codenvycorp.com/selenium_test_report_data/*/che_server_logs/` among the files _che-server-pod.log_ on text `reached timeout`.

**Comment by artaleks9** [comment]
The last three day I don't see this problem, but I think, we still can't close the issue.
We need wait some time to make sure exactly.

**Comment by artaleks9** [comment]
Last two weeks this issue is not produced, when the tests run on the CI.
So, I think, we can close the issue.
@riuvshin  Couldn't you give a short explain, what changes you have made on the CI job.

**Comment by riuvshin** [comment]
the problem was related to failing attachment of pvc to pod, so we've changed pvc strategy from `unique`  to `common` to avoid of mounting pvc to each workspace. since we've changed strategy we do not see that kind of issues anymore, it seems it is related to high CPU load on ci slaves because we run OS cluster and tests on the same node. So for now we are OK with using `common` strategy.
