### ISSUE TITLE
Ctrl + l creates new line

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#9559]
### Description
When pressing Enter instead of OK button, the new line is created. It seems like the cursor is moved to correct line and then interprets "Enter" and create new line. 

### Reproduction Steps
Open file, press "Ctrl + l", insert some line number, press Enter. 

**OS and version:**    
Chrome Version 65.0.3325.181 

**Diagnostics:** 
![evpszk3 - imgur](https://user-images.githubusercontent.com/29278800/39359710-682e5c54-4a1b-11e8-9608-802d96649c1d.gif)

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/9)
