### ISSUE TITLE
Make UD recognize URLs in errors from server-side

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#9562]
### Description
Sometimes an error from the server side contains a URL to docs that explain how to fix the issue user got in Che. 
It would be very cool to allow a user to click the URL as a link instead of copying it and pasting to the browser tab.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@ashumilova @slemeur WDYT?

**Comment by slemeur** [comment]
It'd be a nice improve yes.

**Comment by ashumilova** [comment]
we can do that

**Comment by garagatyi** [comment]
Outdated
