### ISSUE TITLE
Fail build of QA-related jobs on CI just after Eclipse Che deployment has failed

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9565]
### Description
We have a dozen of QA-related jobs on CI:
- https://ci.codenvycorp.com/view/qa
- https://ci.codenvycorp.com/view/pr-builds/
- https://ci.codenvycorp.com/view/qa-release

There is `Build > Execute shell` script defined in CI jobs configuration which deploys _Eclipse Che_ and then run selenium tests on it. When _Eclipse Che_ deployment has failed, build script runs selenium tests anyway despite it doesn't make sense in that case.

We need to fail CI job build just after _Eclipse Che_ deployment script (**ocp.sh** or **che_cli.sh**) finishes its execution with non-zero exit code.

**Comment by mbn217** [comment]
You have to config your CI job to run only when your Eclipse Che passes. This is done in Build trigger section.

**Comment by riuvshin** [comment]
I've found a few jobs which were missing `set -e` and added it back. Since we've changed the way how we deploy it should not affect build anymore.
