### ISSUE TITLE
Add an ability to run selenium tests on 'Multi-User Eclipse Che on Docker' by command in pull request comment

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9566]
### Description
We sometimes need to have an ability to run selenium tests on _Multi-User Eclipse Che on Docker_ by command **ci-test-docker-multi** in pull request comment.

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.
