### ISSUE TITLE
Add an ability to run selenium tests on 'Single-User Eclipse Che on OCP' by command in pull request comment

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9567]
### Description
We sometimes need to have an ability to run selenium tests on _Single-User Eclipse Che on OCP_ by command **ci-test-ocp-single** in pull request comment.

**Comment by sunix** [comment]
Hello, this issue has not been updated for a while
I am closing it but feel free to reopen it if this is still relevant.
