### ISSUE TITLE
Documentation: Prerequisites for Che install

### ISSUE THREAD

**Issue by dneary** [eclipse-che/che#9576]
### Description
The [installation instructions](https://www.eclipse.org/che/docs/quick-start.html) do not list prerequisites for the system (N hosts, M memory , Y disk space) or service requirements (networking, PVCs, identity, security...) from k8s. I feel like I need to learn a lot about OpenShift networking and storage just to get started with Che. It would be great to have a pre-flight checklist, with commands I can run to verify whether I have successfully completed prereq steps.

**Comment by eivantsov** [comment]
@dneary this is quick start. If you take a look at https://www.eclipse.org/che/docs/openshift-admin-guide.html you will find info that you need. Quick start page redirects you to OpenShift installation pages for single and multi user flavors.

And Che is just a deployment, and docs say what objects are created. I mean there is nothing special about it. It does not differ, say, from PHP + MySQL example on OpenShift console. You still need PVs.

**Comment by dneary** [comment]
@eivantsov Thank you for the pointer to the admin guide. I would still expect to have a prerequisites list before the quick start, with some way to know if your platform was ready to deploy Che.

**Comment by eivantsov** [comment]
Getting started guide has been edited to redirect to different installation pages that do have these reqs.
