### ISSUE TITLE
How To Run Program?

### ISSUE THREAD

**Issue by larson-carter** [eclipse-che/che#9578]
### Description

I need help on how to run my java program. I saw the link https://codenvy.io/docs/tutorials/java/index.html it does not make any sense to me. Can you please help me by simplifying the instructions.

**Comment by eivantsov** [comment]
@larsonthekidrs what exactly isn't clear? At what stage are you puzzled or blocked?

**Comment by larsonthekidrs** [comment]
The class path part @eivantsov

**Comment by eivantsov** [comment]
@larsonthekidrs it does not look like you share a lot of details on what you tried and what failed for you.

**Comment by larsonthekidrs** [comment]
@eivantsov  Ok, sorry about that. I got to the part of where I create the action. But I do not get what to do after that. I just need like a video or way simpler instructions.

**Comment by larsonthekidrs** [comment]
@eivantsov I just figured it out with another solution. Thanks for trying to help me.
