### ISSUE TITLE
Custom Stack created via REST API not visible to all users

### ISSUE THREAD

**Issue by davidjbrewer** [eclipse-che/che#9579]
### Description

Added custom stack to CHE via REST API. New stack is only seen by 'admin' user that added the custom stack.

Here is the new stack in the 'admin' account. That stack is not visible to other users.
![image](https://user-images.githubusercontent.com/7935568/39500317-531f8980-4d79-11e8-9a94-eeb72d204f48.png)

### Reproduction Steps

Che 6.2.0 on-premise running on:

[centos@kvmhost2 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[centos@kvmhost2 ~]$ 

**Diagnostics:**

**Comment by eivantsov** [comment]
* log in as admin
* find your stack ID by refreshing Dashboard page and looking at response of /stacks call. Find your stack my name and get its ID.
* go to CHE_ROUTE/swagger
* permissions
* find the below post method

![image](https://user-images.githubusercontent.com/5337267/39523286-53dbba00-4e15-11e8-9936-45fb0788f35d.png)

* use the following JSON (replace ${STACK_ID} with an actual ID)
```
{
"userId": "*",
  "domainId": "stack",
  "instanceId": "${STACK_ID}",
  "actions": [
    "read",
    "search"
  ]
}
```
* If you get 204, all users in the system will be able to see this stack

**Comment by davidjbrewer** [comment]
@eivantsov Thanks. That worked like a champ.

![resultfromansweredissue](https://user-images.githubusercontent.com/7935568/39524462-b00cb8c4-4dde-11e8-9946-a7728e6ea79e.png)

**Comment by eivantsov** [comment]
Happy to help. Btw, there's an issue on that - to wire up those calls in Admin Dashboard.
